### ISSUE TITLE
Explore Cypress

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10048]
As part of our effort to improve e2e test coverage for VAOSR, VAOS FE team wants to get access to and explore the Cypress tool being adopted by VSP. 

We should pick an existing Nightwatch test of ours and convert it to Cypress. Choose the simplest one you can. Then we can evaluate the following questions:

1. How did you find the learning curve of Cypress?
2. How was the va.gov documentation for migrating to Cypress?
3. Is the test easier to understand than Nightwatch?
4. Do you feel like you could write e2e style tests more efficiently with Cypress?

Note: multiple developers can take on this ticket, choose different tests, and give their feedback

* **Appointment list:** Narin

Cypress documentation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/tools/frontend/cypress-migration-guide.md

**Comment by narin** [comment]
> How did you find the learning curve of Cypress?

Cypress documentation was very good and the learning curve was not bad.  I ran into a little bit of a hurdle when trying to rewrite the api mocks.  The nightwatch mocks support query params, whereas I had to write regex's for some of the mocks on Cypress.  Other than that I found Cypress pretty fun to work with.

> How was the va.gov documentation for migrating to Cypress?

The va.gov documentation was a good starting point for me and covered some of the basics of how Cypress is integrated into our stack. I would add use of the `login()` plugin to the documentation which takes care of the login process.  It may not yet be in the documentation since it looks like @U-DON created the plugin recently.

Another issue I ran into was that the `axeCheck()` accessibility plugin is not working. 

> Is the test easier to understand than Nightwatch?

I think that without the need manually write `waitForElement` calls, tests are much more readable.

> Do you feel like you could write e2e style tests more efficiently with Cypress?

Aside from not needing the wait for element calls, writing e2e tests with Cypress wasn't significantly easier than Nightwatch.  I will say that the UI for the test runner is very helpful in debugging e2e tests though.  The ability to time travel back through the steps or inspect why a test is failing is extremely useful.  Whereas with Nightwatch, it's hard to tell exactly where something is failing with the browser instance that runs.
