### ISSUE TITLE
FE research temporary service interruption / planned outage verbiage (Prod Error Handling)

### ISSUE THREAD

**Issue by saneshark** [department-of-veterans-affairs/va.gov-team#10087]
On the FE we should investate to see how we can trigger various banners for planned and known outages as well as banners we can put up in a pinch for a variety of different things that could go wrong -- such as the CDW reelated timeouts we were experiencing yesterday as part of the 4.20.2 release.

**Comment by jbalboni** [comment]
On the FE we have downtime notifications, which are triggered through maintenance windows returned from the backend `/v0/maintenance_windows` service. There are entries for different internal VA dependencies, and on the FE you specify which of them to look for.

There are two main ways of using this feature. You can mark the app is down, by returning a maintenance window for a require dependency:

![Screen Shot 2020-06-29 at 4.44.06 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/38b13080-a2f7-485c-a212-1e67ea1966f7)

And can specify upcoming downtime:

![Screen Shot 2020-06-29 at 4.43.16 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/cdf56e0d-e922-47be-bc1a-2107f1d7984e)

The front end is set up with both of these, if we create maintenance windows using a `vaos` service key.

Alternatively, we could modify VAOS to just shown the banner when there's a maintenance window, rather than hide the whole app, though this is less common usage.

**Comment by jbalboni** [comment]
@saneshark @lenaecb I'm not sure what else you'd like us to investigate in this ticket. This is set up on the FE, the changes required to start using it are on the BE. These services used to be set up in PagerDuty, but given that we don't really have access to that now, I'm not sure what the current expectation is for VFS teams.

**Comment by saneshark** [comment]
As a separate ticket, perhaps we might want to have something like a feature toggle. It would be nice to have one that disables the app or portions of the app altogether with a notification and also one where we can just put a notification up thats more generic. It's too bad that we can't set the messaging somehow from within feature toggles (not really its intended use).

**Comment by lenaecb** [comment]
Hmmm, I am not sure either of those windows work for VAOS if the copy/content can't be edited.

At a minimum, for now, we can set the maintenance banner but still allow for users to use the app. 

How can we go about having an additional app specific notification display when the app is experiencing degradation, but it's still functional to a degree?  cc: @saneshark @jbalboni

**Comment by jbalboni** [comment]
@lenaecb We can override the content for both of those messages if we need to.

For your second question, I think we'd have to do something like the feature flag approach that Kam mentions to have two variations of downtime like that. Unless we had two different PagerDuty services, but that seems like it'd be confusing.

@saneshark Did we get an answer on how we would go about requesting maintenance windows be put up? 

I think we should consider the feature flag approach if we want full control over how we show maintenance messages, especially if the PagerDuty windows can't be automatically triggered. Maybe we create a PagerDuty service for VAMF that VSP can control for major, cross-platform issues, and we can create feature flags to control banners for VAOS-specific problems.

**Comment by lenaecb** [comment]
For the upcoming maintenance window, we're going to show the standard modal via PagerDuty. 

In the future we should consider create more app specific window when some features (but not all) are down due to maintenance or issue. 

Closing out
