### ISSUE TITLE
Analytics Implementation for [Facility Locator]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#10126]
# Google Analytics Implementation 

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA? `Google Analytics implementation`

- Who is this request for? `Michelle Middaugh`
    
- What team/project is this work for? `Facilities Team, Facilities Locator`
     
- Provide the Domain where Google Analytics needs to be implemented: `https://www.va.gov/find-locations/ `
   
- Please provide any upcoming deadlines or important milestones: `no particular deadline`

## Typical Website Interactions to Track 
**Conversions - Understanding the User Flow**
We would like to track the click rate of "Directions" links from Facility Locator search and detail pages. Veterans can access the Directions link in two ways:
1- By clicking the Directions link within the search result cards displayed left of the map:
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/8adc7a51-3feb-4618-ae4c-c2bd89de678e)

2- By clicking on the facility name within a search results card, the Veteran is taken to a detail page which also displays a Directions link
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/7b52c4a3-ba1e-47e2-b8e4-bc3b396ec27d)

It will be valuable to know if the link was accessed from the search results card or the detail page, if that is possible. 

**Certain conditions/responses that need to be reviewed**
Detail pages exist for all facility types except the following
- Facility type = urgent care + service type = Community urgent care (in VA's network)
- Facility type = Community pharmacies (in VA's network)

**Additional Comments**
- There is no concrete way to know if the Veteran has completed his/her goal of visiting the Facility Locator. We can't tell the difference between a Veteran leaving the page after viewing desired information which was provided in the search results and a Veteran who leaves the page unsatisfied. We're making the assumption that clicking a link for directions is one way to indicate a successful search. 
- This information may already be available in GA but I have been unable to find a way to view it. 
    

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thank you @mmiddaugh , confirming receipt! Will be in touch soon.

**Comment by jonwehausen** [comment]
Hi @mmiddaugh , 

Thank you for providing examples of metrics wishing to track yet also detailing the larger analytics goal here of measuring search success, and filling the template out thoroughly with site-side conditions to keep in mind, we really appreciate it. 

Here are a couple custom reports you can replicate withing your own GA account within the Facility Locator Modernized View: 
- [Total Direction link Clicks from Facility Profile Pages](https://analytics.google.com/analytics/web/template?uid=oxFa0tLvRYKwgTSp5diTsQ)
- [Total Direction link Clicks from Search Page Results](https://analytics.google.com/analytics/web/template?uid=_14RZxW7QyyvsiEHPJchHA)
_You can adjust each of those reports to include their respective pages by toggling Secondary Dimension > Page_

To answer your primary question here  -- **Clicks on "Directions" directly from the search page occurred almost 50k more times since Jan 1 than clicks from facility pages**

### Taking a step back...
- The clicks on directions is the closest form to an implicit offline "conversion" we have seen -- the veteran intends to visit the facility. 
- How this conversion can be correlated specifically with search relevancy and search results is a bit trickier. We would like to have a conversation with you all to understand a bit better what items may be of interest. 
- After taking a thorough look at the data we have a couple improvement we would like to make as well to help take our analysis to the next level -- @bsmartin-ep and I will have those discussions on what implementation items will need to come out
- Also, perhaps this is a conversation we feed into overall Q3 adjustments / improvements to the Facility Locator Product Success Tool.

What is your availability next week for a chat?
