### ISSUE TITLE
Request Contact Center Review for Estimate Your Benefits

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#10166]
- Context: Updates have been made to the "Estimate Your Benefits" section of the Institution Profile page within the Comparison Tool.  These changes have been made to address mobile, usability, and 508 concerns.
- Launch Date and Details: Planned Launch is Thursday June 18, 2020
- URL: 
   - Non-VET TEC: https://staging.va.gov/gi-bill-comparison-tool/profile/11929140
   - VET TEC: https://staging.va.gov/gi-bill-comparison-tool/profile/2V000105/HACK%20REACTOR%20SOFTWARE%20ENGINEERING%20ONLINE
- Product Guide:
   - Word: [GIBillComparisonTool_ProductGuide_07202020.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4949749/GIBillComparisonTool_ProductGuide_07202020.docx)
   - PDF: [GIBillComparisonTool_ProductGuide_07202020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4949750/GIBillComparisonTool_ProductGuide_07202020.pdf)
- [Product Video](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/EYB%20-%20Call%20Center%20Recording.mp4)
- [Product Video Transcript](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/estimate-your-benefits/EYB%20-%20Call%20Center%20Recording%20Transcript.docx)

**Comment by desireeturner** [comment]
@clantosswett checking in on this to see if there is anything else needed on our end. Is there anything else that needs to be done before this issue can be closed?

**Comment by Kimberley2019** [comment]
@desireeturner Chante is on vacation this week.  I will review this today and provide any feedback.  If I do not have any questions or concerns, I will pass along to the Contact Center for their review and feedback.

**Comment by Kimberley2019** [comment]
@desireeturner after review it appears to have all the required information. As long as there have been not edits to the content that has been provided, I have passed it along to the contact center to ensure that they do not have any feedback.  I have given them a response date of COB 7/3/2020.

Can you advise that no additional content has been added or updated?

**Comment by desireeturner** [comment]
@Kimberley2019 that is correct. No additional content has been added or updated.

**Comment by Kimberley2019** [comment]
@desireeturner I have some feedback from the Contact Center.  Please see below and advise accordingly so that I can provide the information to them.

I have already advised them that this is an update to a current functionality.  I did not include the attachment since it was only for typo correct purposes, but can slack to you if needed.


_I found a couple of typos in the product guide so attaching that.  Also, I feel like there is something missing here.  Is this an update to a current functionality or a new functionality?  There isn’t any information on things that could go wrong that our agents would be fielding questions on.   If this is updated, we should probably make reference to the previous training and include any of the error messages/things that could go wrong from that training as well._

Thanks,
Lana_

**Comment by Kimberley2019** [comment]
@desireeturner Have you been able to review the feedback in order to provide any details that they are requesting?

**Comment by desireeturner** [comment]
@Kimberley2019 The updates are limited to the Estimate Your Benefits section within the Comparison Tool. More specifically, this is related to how this section of the tool functions related to mobile and accessible versions (not new functionality). Can you share an example of what it is you are looking for? This is the first time this type of request has been made of our team with regard to our call center materials, so an example would be helpful to make sure we are getting you all what you need. If it is easier to discuss via phone call please let me know and we can set something up. Thank you!

**Comment by Kimberley2019** [comment]
@desireeturner I have advise the Contact Center of this and informed them that I would like t have this matter resolved by COB (5 PM ET) today.

**Comment by Kimberley2019** [comment]
@desireeturner I have received the response below from then Contact Center.

_Hi Kimberly,_
_I guess my concern is the product guide would be helpful if the agent was simply helping the caller walk through the site.  However, if the caller encounters an error of some kind in this section then our agents have nothing to help them identify why it might be happening or what it means.  If there are no known errors, then it’s good._ 
_Thanks,
Lana_  

Are there any known errors and/or workarounds?  I am assuming that if there were, they would have been included in the video and product guide.  If not, please add to all items and include that in the table of contents for the product guide.

If there are no known errors, please advise so that I can inform the Contact Center of this.

**Comment by Kimberley2019** [comment]
@desireeturner Please advise on previous comment above.

**Comment by desireeturner** [comment]
@Kimberley2019 I've updated the Product Guide and included the updated document in the body of this issue (both .doc and .pdf versions). Hopefully this addresses everything. I tried to cover any issues that might arise during use, but for the most part any errors that come up using the Comparison Tool should be reported to us because they are most likely bugs. Thank you and let me know if you need anything else!

**Comment by Kimberley2019** [comment]
This updated information has been provided to the VEO call center.
