### ISSUE TITLE
IA Request BDD on Benefits and Memorials 1

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10184]
What this is: Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

When to use this: After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to product outline ([Product Outline BDD](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d1119b8bd6d108240a363e76c08ab9360ab4b39d/products/disability/disability-compensation-claim/bdd/product-outline.md))
- Link to or attach prototype or mockups ([InVision Prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens)
- Link to research readout/results ([Latest Research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d1119b8bd6d108240a363e76c08ab9360ab4b39d/products/disability/disability-compensation-claim/bdd/BDD%20Research/BDD-usability-test-April/Research-findings-test2.md))
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d1119b8bd6d108240a363e76c08ab9360ab4b39d/products/disability/disability-compensation-claim/bdd/BDD%20Research/Initial-usability-March2020/BDD-research-findings.md) showing that you have added your research to the list as applicable.  Note: In Lieu of a history document we are showing only the previous research results.
- Link to or attach final content including H1s (should be part of mockups but my understanding it is this image)
![Screen Shot 2020-06-12 at 4.00.33 PM.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/35b58e00-1c4f-4153-a92a-781fe83ff1c0)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords**
- BDD, Pre-Discharge, Benefits Delivery at Discharge, 526

**Proposed site map/page structure** (if more than one page)
- InVision link above should cover it.  But, it is the same as our 526 flow.

**Suggested URL(s)**
- https://www.va.gov/disability/how-to-file-claim/
- Same as 526 since this is a variation on that form

**Suggested entry points**
- From the main box like 526
- ![image.png](https://images.zenhubusercontent.com/5d54025346ffca000148e7f7/a26001f2-cdbd-4ddd-a0fa-bca6930fe680)

**Crosslinking opportunities**
- https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/

**Redirects/canonical tags**
- N/A, eBenefits has this capability currently and we will be working with them

## Definition of Done
- [x] Issue is created, tagged and assigned to Content and IA team
- [x] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation
- [ ] Requesting team member complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

**Comment by mnorthuis** [comment]
@luke-gcio @chrvalla 
I am working on the final IA for the static content pages, entry points and redirects needed for this work.  For the most part, all of the static content needed already exists on the site, but @DanielleThierryUSDSVA and I will be reviewing it for changes to simplify the content/structure and hopefully improve the findability.   

If you have any questions about any of this or would like to discuss, please let me know. 

A few things to note at this time:
- I see a few issues with the prototype that I want to make sure are called out.  
  - Since this application is simply a part of the existing 526 claim flow, the URL and breadcrumb of the form are already established - it should be the same as what is live today (https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction)
  - The existing [How to file page](https://www.va.gov/disability/how-to-file-claim/) should also be utilized - the prototype shows a version with an incorrect breadcrumb and missing left nav
 - Danielle and I will work to define any changes to the existing static content - the Public Websites team will assist in making those changes.  There should not be any new content to write, but if it does come up, they would do that work as well. 
- Once Danielle and I have a chance to discuss, I will finalize the IA 

Final IA will be documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-benefits-at-discharge.md

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mnorthuis. Confirming that the new sitemaps align with my notes re: our discussions and decisions around the IA/content strategy. Thanks!

**Comment by mnorthuis** [comment]
@luke-gcio Final IA is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-benefits-at-discharge.md

Please feel free to reach out with any questions or if you want to walk through this.  You can close this issue at your discretion.

**Comment by luke-gcio** [comment]
@mnorthuis 

Kevin pointed out that we will still be redirecting to eBenefits until BDD is fully rolled out (obviously) and for IDES, although I am not sure IDES is something we talk about on VA.gov.

**Comment by mnorthuis** [comment]
I don't believe we reference IDES in disability currently, what scenario would require reference to IDES?   Would that reference go away once BDD is rolled out?

**Comment by mnorthuis** [comment]
Updated the IA info based on follow up conversations around what work is needed to best support the BDD launch and what can be postponed.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-benefits-at-discharge.md

Redirect request to support above IA work has been submitted: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12825

**Comment by shiragoodman** [comment]
@luke-gcio can this be closed out?
