### ISSUE TITLE
Create combined coronavirus and generic natural disaster homepage banner text 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10231]
## Create combined coronavirus and generic natural disaster homepage banner text 

**Problem:**
As we head into regional natural disaster seasons (fires in the west; hurricanes in the southeast/east), how will we communicate the evolving coronavirus situation as well as other natural disasters of a more regional nature?

**Recommendation:**
Instead of enabling multiple and simultaneous homepage emergency banners, we will combine messaging into 1 emergency alert banner.

User story:
As a Veteran, I want to quickly be able to see where to go for services, benefits, or facility impacts, whether that impact is due to coronavirus or a hurricane/fire/earthquake/mass protests, shootings/other major event.

[x ] Share proposal with OPIA and JTF (draft text) @jenniferlee-dsva 
[ ] Incorporate OPIA feedback if any
[ ] Finalize proposed text ( @DanielleThierryUSDSVA )

Example combined msg - DRAFT - FPO.
Note @DanielleThierryUSDSVA will provide final text (300 characters max incl spaces).

Some VA facilities and services are affected

Coronavirus: Visit our coronavirus FAQS to learn how it may affect VA health care and benefit services.

Facility statuses due to natural disasters in your area: Go to the facility locator for the specific hours and status of your local VA facility.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @jenniferlee-dsva. 2 potential versions to consider:

V1 - (299 characters with spaces)

**Some VA facilities and services are affected by current events**

**Coronavirus:** Visit our [coronavirus FAQS](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) for the latest on affected VA health care and benefit services.
**Natural disasters in your area:** Use our [Find VA locations](https://www.va.gov/find-locations/) tool to get current hours and status for your local VA facility.


V2 - (296 characters with spaces)

**Updates on VA facility and service status due to current events**
**Coronavirus:** Visit our [coronavirus FAQS](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) for the latest on COVID-19’s impact on VA health care and benefit services.
**Natural disasters in your area:** [Find VA locations ](https://www.va.gov/find-locations/)for the latest hours and operating status of your local VA facility.

**Comment by jenniferlee-dsva** [comment]
Thx @DanielleThierryUSDSVA - I've sent deck with draft text to OPIA. Will let you know when Gary has a chance to sync with Curt re feedback.

**Comment by DanielleThierryUSDSVA** [comment]
@jenniferlee-dsva Just adding note based on your slack that feedback came in - Curt doesn't want pre-written banner. We'll meet on next steps soon.

**Comment by jenniferlee-dsva** [comment]
done
