### ISSUE TITLE
CF: Research caution flag file usage

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#10440]
As a developer, I need to research the caution flag file contents to identify questions that need to be answered by the business so that we can identify which files can be combined.

## Assumptions:
1. The caution flag files are:
    - Hcm
    - Mou
    - SchoolClosure
    - Sec702
    - Settlement

## Acceptance Criteria
1. Documentation is created that outlines additional questions to the business.
2. Documentation is created that outlines potential ideas for file consolidation.

## Supporting Artifacts:
1. N/A

**Comment by dmccurdybah** [comment]
# Edu CSV Consolidation Notes

## Suggested Solution

It should be possible to combine the "hcm", "mou", "school_closure", and "sec702_schools" CSV files into one file with the following fields:

- one of (`facility_code`, `ipeds`, `ope`)
- `hcm_reason` - string
- `school_closing` - boolean
- `school_closing_date` - date
- `sec_702` - boolean
- `dodmou` - boolean
- `dod_status` - boolean

The "settlements" CSV file has multiple rows for the same institution (which are used to generate multiple caution flags) so these files aren't good candidates for consolidation.

## Questions

- Would it be possible to enter one ID field instead of three (facility_code, ope, and ipeds)? That would simplify this file even more and seems like it should be possible if this file is being manually entered.  If so, which ID do we keep?

- Is the suggested file structure something that would be possible for them to create manually? It seems simpler to ask them to manually add two

## CSV / DB Notes

- ## HCM

  table: `hcms`

  CSV/DB columns:
    - `method reason desc` / `hcm_reason` - string
    - `ope id` / `ope` - string

- ## Mou
  table: `mous`

  CSV/DB columns:
    - `status` / `dod_status` - boolean based on whether or not `status` contains "dod". Used to generate a caution flag (hard coded in old caution flag code)
    - `status` / `dodmou` - boolean based on whether or not `status` matches "probation - dod" or "title iv non-compliant"
    - `ope id` / `ope` - string

- ## SchoolClosure
  table: `school_closures`

  CSV/DB columns:
    - `facility code` / `facility_code` - string
    - `school closing` / `school_closing` - boolean
    - `school closing date` / `school_closing_on` - date
    - `school closing message` / `school_closing_message` - text - this is not used in vets-website

- ## Sec702
  table: `sec702s`

  CSV/DB columns:
    - `facility code` / `facility_code` - string
    - `sec702` / `sec_702` - boolean
    - `state` / `state` - string

  note: probably not a CSV they meant since it's data for US states and territories (only 59 rows)

- ## Sec702_schools
  table: `sec702_schools`

  CSV/DB columns:
    - `facility code` / `facility_code` - string
    - `sec702` / `sec_702` - boolean

  note: overrides per-state data for institution

- ## Settlement
  table: `settlements`

  CSV/DB columns:
    - `unitid` / `cross` - string
    - `settlement_description` - string

  note: not a good candidate for consolidation because it looks like there can be multiple rows per institution
