### ISSUE TITLE
On Site Search - Type-Ahead Design + UX 

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#10489]
**Problem Statement**

As part of its product feature releases in Q2 2020, Search.gov has introduced [Type-Ahead for API-enabled ](https://search.gov/manual/typeahead-api.html)clients such as VA.gov.

The Public Websites team believes this feature helps improve the utility of site search, by surfacing the most common/popular related links to the user faster and more efficiently.

While work continues on the quality of the query results, design and UX expertise is needed to address this question for implementation:

-  Should this global type-ahead feature be consistent with the type ahead UX and functionality already available in the [GI Bill Comparison Tool ](https://www.va.gov/gi-bill-comparison-tool/)and in the [Find A VA Location > Community Providers ](https://www.va.gov/find-locations)tool on VA.gov (e.g. is this a design system component)  See attached screenshots fo reference.

An initial design review of the site-wide Type Ahead featured was conducted by @andaleliz with notes [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/9486).

**Tasks**
[x] Put Type-Ahead feature -- as is -- on staging.va.gov as a rough POC to allow for broader internal access for Collab Cycle. (note: there are algo/relevancy issues under investigation by Search.gov)
[ ] Schedule session with @ncksllvn + @andaleliz + @rtwell to determine if consistency is needed/required
[ ] Check in with the Design Council for input
[ ] Schedule accessibility review of the site-wide Type-Ahead feature

**Search.gov Type-Ahead for VA.gov (As Is)**

<img width="717" alt="Screen Shot 2020-06-19 at 3 05 33 PM" src="https://user-images.githubusercontent.com/63107147/85172113-662a8300-b23e-11ea-9303-05558b4bb915.png">

### VA.gov type ahead examples

**Find a VA Location Type-Ahead**

<img width="803" alt="VA gov_Find_a_Location_Type-Ahead" src="https://user-images.githubusercontent.com/63107147/85172145-7c384380-b23e-11ea-8c54-a63bd548d7d9.png">

**GI Bill Comparison Tool Type-Ahead (Desktop)**

<img width="1136" alt="VA_GIBCT_Type-Ahead" src="https://user-images.githubusercontent.com/63107147/85172308-c5889300-b23e-11ea-87ab-cf892825ab88.png">

**GI Bill Comparison Tool Type-Ahead (Mobile)**

![IMG_A830EBDCB96C-1](https://user-images.githubusercontent.com/63107147/85172482-27e19380-b23f-11ea-8b3a-1ec25f3cea64.jpeg)

**Apply for pre-need eligibility determination form**
(military branch and cemetery fields)
![Screen Shot 2020-06-22 at 11 04 24 AM](https://user-images.githubusercontent.com/55992116/85303444-7ded4b80-b478-11ea-9639-644cadfc4090.png)
![Screen Shot 2020-06-22 at 11 04 58 AM](https://user-images.githubusercontent.com/55992116/85303449-804fa580-b478-11ea-87dc-98115a581f9f.png)

**Apply for disability compensation form**
![Screen Shot 2020-06-22 at 11 10 16 AM](https://user-images.githubusercontent.com/55992116/85303939-269bab00-b479-11ea-8fa9-ebe06ea45921.png)

**Comment by andaleliz** [comment]
Is there any problem w/ me bringing this up in #design on Slack? I'm interested to know about the reasoning behind the design decisions made for GIBCT or the facility locator field, before we move forward. That may help our meeting w/ Ryan be more productive as well.

Side note: I so wish the GIBCT wasn't all CAPS.  I know that's an API/data thing, boy is it hard to read.

**Comment by johnhashva** [comment]
Love this idea -- go for it, Liz.

**Comment by ncksllvn** [comment]
@andaleliz I'm predicting that the UX of this component was just never streamlined across apps, since each app seems to make its own decision on style

**Comment by andaleliz** [comment]
@ncksllvn I'm with you 100%.  I think this is a great time to talk about making them consistent, now that we'll have 3 of these. If there isn't a pattern established or some kind of guidance to follow, I think it makes sense for us to work toward doing that, and asking the others to update, since we'll have the most visibility/usage on the site.

**Comment by ncksllvn** [comment]
Sounds good. I don't want to use the word "design system"...but we're definitely in that ballpark

**Comment by andaleliz** [comment]
[I posted in #design](https://dsva.slack.com/archives/C0NGDDXME/p1592837454460800?thread_ts=1592834606.458500&cid=C0NGDDXME), if you want to follow along. Might discuss today as a group during our weekly sync.

**Comment by andaleliz** [comment]
Found a couple of other examples from forms and added them to the description above. It looks like the styling is consistent (no bottom border, light blue highlighted text) across all type-aheads except the facility locator.  Which is a little humorous to me because I prefer the facility locator styling to the others :)

**Comment by andaleliz** [comment]
@johnhashva I just took another look at this ticket, and have a few questions.

1. I want to clarify the work that should come out of this.   I understand the goal of this ticket to be to 
- evaluate which of the 2 existing patterns currently on VA.gov we should follow (or do we pave our own path)?
- evaluate whether or not we should propose our direction as a new design system component

Am I understanding correctly? 

2. Should we do the a11y review before or after we have our solution on staging? I would love to have one earlier, but I think it typically happens once it's on staging, and if that's the case, I think that might need to be separated from this effort of determining which pattern to follow on the site.

Also, I noticed this didn't have any labels, so I took the liberty of adding some of the usual suspects. I also added it to our Type Ahead epic.  Lmk if I need to make any corrections. Thanks!

**Comment by johnhashva** [comment]
@andaleliz in answer to your Q's:

1. Yes.  My plan is to schedule a convo with you and @rtwell on that question when he is back next week.  Good?
2. Got it.  So, I will create a **separate ticket** for accessibility review once @ncksllvn has the "prototype version" on staging -- will do.

And thanks for adding the labels.  I'll make sure to tack those on from now on.

**Comment by ncksllvn** [comment]
https://dsva.slack.com/archives/C011K1VSTC3/p1592853360008800

**Comment by ncksllvn** [comment]
Per the Slack thread linked above, I implemented the typeahead using a `<datalist>` element per the accessibility recommendation. I think this is a great suggestion but it does conflict with the typeahead style that we're use to on the website - the typeahead UX becomes more native to the browser so there is little flexibility in terms of styling it. I haven't explored styling it, but we might be able to change the highlight color (currently gray in Chrome; blue in Safari; not a dropdown at all on Mobile Safari). So, before we make design improvements/recommendations, we should make sure that they are aligned with accessibility because we might not be able to do them without forgoing the `<datalist>`.

Here are some screenshots -

### Chrome
![image](https://user-images.githubusercontent.com/1915775/89920343-483c2780-dbca-11ea-9337-fe096b7b64da.png)

### Safari
![image](https://user-images.githubusercontent.com/1915775/89920512-7a4d8980-dbca-11ea-9bd8-c91e0c2cc683.png)

### Mobile Safari
![image](https://user-images.githubusercontent.com/1915775/89920749-c7316000-dbca-11ea-819d-015daa3e72a4.png)

**Comment by denisecoveyduc** [comment]
@mgleo to read thru history as there are a few mentions of other drop downs that may be of interest in the future for type ahead enhancements. @andaleliz can clarify any questions. For now closing this design + UX Epic
