### ISSUE TITLE
[Discovery] Identify opportunities for visual regression testing

### ISSUE THREAD

**Issue by rtluu** [department-of-veterans-affairs/va.gov-team#105]
## Description
Currently, we have visual regression testing, but now we want to identify opportunities for improvement to increase our *detection*.

## AC
- [x] Research has been conducted to identify opportunities for automated testing improvements
- [x] A research readout has been written and shared with the tools and improvement teams
- [x] New tickets have been written to break out the work to be done

**Comment by rianfowler** [comment]
# Visual Regression Testing

## Overview 

Visual regression testing captures and compares screenshots. Failure occurs when the test image deviates significantly from the baseline image. 

Good for detecting 
- CSS regression  
- SPA loading errors 

## Short term

Use VRT to monitor critical pages on the site - testing at least once a day or testing after every deploy to production 

Tasks: 
- Run the current set of VRT everyday: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16518
  - validates production 
  - only validates on page load (no interactions to code)
  - only validates on Chrome 
- Notify slack channel when there are failures 
- Expand test coverage to highest traffic pages of the website 

## Medium / Long term: 
Improve detection and make easier to use

- drive test coverage with a config or the sitemap (ideally no developer intervention to test new pages)
- easily update baseline images 
- track historical baseline images 
- VRT on other browsers (specifically IE 11) 
- Improve reporting 
  - notifying through slack doesn't scale 
  - include information about failures e.g. base image vs failure image, link to page that failed 


Other tickets: 

https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1248
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1249
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/1251

**Comment by rianfowler** [comment]
# Unit testing 

## Short term 
Improve error detection before merge 

- Improve unit test coverage to more than 90% 

## Medium / Long term 
Make it easy to maintain high test coverage 

- investigate using Jest or Jest-like features
  - see [Why we use mocha instead of Jest](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/front-end-standards/documented-decisions/jest/)
  - incorporate jest-like snapshot testing of react components into mocha: https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15830
- Improve unit test output 
- Facilitate test driven development for common tasks (e.g. fix the watch task, patterns for TDD)
- Improve test run time (this could part of facilitating TDD)

**Comment by rianfowler** [comment]
Moved the medium / long term stuff into the epic #157
