### ISSUE TITLE
Access for Will Drougas

### ISSUE THREAD

**Issue by wdrougas-tista** [department-of-veterans-affairs/va.gov-team#10552]
# Instructions
1. Fill out **Description**
2. Add the label used by your team (eg: `BAH-526`)
3. Add a comment @department-of-veterans-affairs/vsp-operations to ping the operations team
4. When the issue is closed you will be notified and can continue with on-boarding setup

# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Geoffrey Stienblock
- Please provide your name.
   > Will Drougas
- Please Provide your email.
   > wdrougas@tistatech.com or william.drougas@va.gov
- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > Foxtrot, Systems Analyst, Tista

- Requesting SSH key authorization?
   > YES  
   - What is your **public** SSH key?
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCfUzWCz+vieTgIJ2wNNRaZ8DRx59IXwatrOMrWS9OUsL8wD0/L3RtnuKb9WHZKFt8P/r9NSvm+XCrmjuohRmLA1IJVUOZt2r5GscMQgLifurG7DiC6yMG1p0JzkhJVAhxtHkhpjICJqMEV8Rhh4+Vhb3MjdHEIcoMIJ1MACro4BpRsl2qPeYnhcpYmzgSojT2nHPKl1y89+VhcvAwizXJPdVNU2d8gt6Vf2tyYX9uclIf5XBJv4lCwoVetyLJPMAOrhjEHjInWnKwd78sStZ4KzhmzZbFbnyMIyIs9WG42Lb3t0OtUdM0//E3cV0Shty0cPx1FTxCfT13hS7EPbwpRK+uuGJgBfo0v1MG5p+aHICI//RBHDNHn8IQsNGUncCfu9DtfJqzHQaaCxmA0Ron5gPRPDhV9mLDbo/6ArUG2NO2xfwtgMol9/Gd7TTDiztrmdr6xAsBwgQMkmH7i/s4kmmHBo+L7sBUJTsve1MJ+exEbE7il2/YHPoZNUwr2Qb1jlKshOvqrXNliXQp/TZxOCVOg6mwzkpT4JyAJveBuqDI57eTios6hDrkXBjLTVIqMgA3myan6UClKH2JYJ2yFgkMHVoGszaOuqWAo8WPXyvzeqdBvRMucg3C+UQDzUguaiBFkaBAQXwVgfi0vo2i8f4m2mRFqFWejmeaKGmFDbw== williamdrougas@TST-C02RR2L7G8WN
```

- Grant AWS Console access?
  > YES 
  - Need access to Sentry

**Comment by tskinn** [comment]
@wdrougas-tista did you close this ticket because you do not need access?

**Comment by wdrougas-tista** [comment]
@tskinn Yes apologies, I have received the access I need

**Comment by tskinn** [comment]
Sorry I'm still confused. I added your ssh key to the socks proxy so you could access things like sentry. Do you no longer need that access?

**Comment by wdrougas-tista** [comment]
I will need that access. Sorry for the confusion, the initial reason why I submitted this request was to be able to log in to Sentry on my GFE. I was provided that login information from Tista but having access through socks proxy will be helpful as well. Again, apologies for the confusion and thank you for the assistance

**Comment by tskinn** [comment]
No worries. Thanks for clarification!

**Comment by wdrougas-tista** [comment]
Hi @tskinn. I am trying to use the SOCKS proxy and am not having any luck and was wondering if you had any idea what my issue might be. Below is the response I get when running the sockson command. I hope this isn't the wrong route to go about solving this but appreciate any insight you may have!


<img width="793" alt="Screen Shot 2020-07-24 at 10 38 33 AM" src="https://user-images.githubusercontent.com/63597932/88403003-e68e5780-cd99-11ea-8e13-2dd0af190638.png">

**Comment by jbritt1** [comment]
I personally am not familiar with the `sockson` command. I usually refer folks to [this guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md#configure-the-socks-proxy). Within that doc, there is instruction on running the command manually (vs using a script) the first time and not including an `&` character (which backgrounds the process) in order to accept the initial SSH connection. Could you perhaps use that doc and go through the steps there and comment back letting us know if you were successful?


Also, are you also still requesting AWS access at this time?

**Comment by wdrougas-tista** [comment]
Thanks @jbritt1. I have been able to install a proxy switcher in Chrome and able to connect to Sentry but when trying to access other sites such as Github I then need to turn the proxy switcher off so this is not ideal. I have been able to work my way through the instructions provided but when running the `$ ssh socks -D 2001 -N` command nothing happens. I have been able to ssm into other environments so I think my AWS access is all set but for some reason trying to get the socks proxy set up has not been successful. Appreciate the help on this!

**Comment by jbritt1** [comment]
The proxy switcher, if properly configured, should only use proxy settings on the specified domains within the guide. The socks command you referenced, does the terminal get suspended? The only reason to run `$ ssh socks -D 2001 -N` is for the first time in order to accept the SSH connection and add it to the known hosts for your machine. From then on, you will want to run it with `$ ssh socks -D 2001 -N &` in order to background the process.

**Comment by jbritt1** [comment]
There is also an alternative route to the proxy switcher [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/scripts/socks) if this works better perhaps?

**Comment by wdrougas-tista** [comment]
Ok got it. Yes the terminal got suspended but when backgrounding the process it appears to be working. I will try running the script

**Comment by jbritt1** [comment]
Is this one good to close? Or are you still in need of some form of access or assistance @wdrougas-tista?

**Comment by wdrougas-tista** [comment]
This is good to close, thank you @jbritt1
