### ISSUE TITLE
CT - Yellow Ribbon drop-downs not behaving correctly

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#10634]
On a school profile page, one of the calculator questions is "Will you be a Yellow Ribbon recipient?". If the user selects Yes, several conditional questions are displayed including drop-downs for "Degree Level" and "Division or school". There should be additional options in those drop-downs. 

1. navigate to https://staging.va.gov/gi-bill-comparison-tool/profile/11806124
2. expand the "Scholarships and other VA funding" mini-accordion 
3. select Yes for "Will you be a Yellow Ribbon recipient?"

### Current Behavior:
- "Degree Level" drop-down only has "Enter an Amount" and "all" as options
- "Division or school" drop-down only has "all" as an option
- "Division or school" drop-down is missing the arrows that indicate it is a drop-down

![Screen Shot 2020-06-25 at 10.16.58 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/4ea7c8ca-be23-4826-8178-a662b522ab2a)

---

![Screen Shot 2020-06-25 at 10.17.45 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2cf18edd-27be-49d3-8891-18134aebc1e9)

---

![Screen Shot 2020-06-25 at 10.17.53 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/747e3179-8f06-4bd4-a582-2de51b572ea4)

### Expected Behavior
- Degree Level works as designed. Move value "Enter an amount" to be the second value in the pick list.
  Note: Could possibly benefit from a re-design or better labelling.
- Division or School - when value is a single value, it should behave as a disabled text box.

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/13299

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
@delli-gatti-michael UX has reviewed and there are two items of concern:
1.  The Expected Behavior says that "Enter an amount" should be the second value in the pick list for Degree Level.  It is actually appearing as the last item in the list.
2. For Division or School, a single value is supposed to behave as a disabled text box.  While the value is behaving as a disabled text box, it does not look like one.
See screenshots for both issues
<img width="446" alt="Screen Shot 2020-07-02 at 11 59 24 AM" src="https://user-images.githubusercontent.com/36964225/86386566-ed74ef00-bc5f-11ea-80bc-e8555a8e6821.png">
<img width="565" alt="Screen Shot 2020-07-02 at 11 53 55 AM" src="https://user-images.githubusercontent.com/36964225/86386525-dfbf6980-bc5f-11ea-84aa-02361f838c1f.png">
<img width="446" alt="Screen Shot 2020-07-02 at 12 02 07 PM" src="https://user-images.githubusercontent.com/36964225/86386555-e948d180-bc5f-11ea-85f1-4f06994f21ee.png">

**Comment by sonntag-adam** [comment]
@elder-joseph moving back to in progress for the issues above.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/13367

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-07-02 at 2.16.34 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/6d401fcd-bf4c-494c-a309-3e3e76ed4407)
##
![Screen Shot 2020-07-02 at 2.17.45 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/16e6b6b9-18ef-4580-986e-ea15c5b28ce9)

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by ccruzgra** [comment]
@sonntag-adam UXers took a look and this checks out!

**Comment by sonntag-adam** [comment]
Closing out bug
