### ISSUE TITLE
Analytics for 'update physical address' prompt

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10662]
Once we complete this story -- #9852 -- we need to set track on two events

## Events to track:
- [ ] track when update address prompt is displayed (We want to know how many Veterans are getting/seeing this prompt)
- [ ] track when Veteran clicks the blue "update my address" button

For reference here is the prompt:
![Screen Shot 2020-06-26 at 9.10.27 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/50908ac2-e137-41d2-a69e-01c2c084572b)

**Comment by bsmartin-ep** [comment]
@jbalboni -

I think we do.  We have some preexisting alert-related taxonomy we can use:


 > track when update address prompt is displayed (We want to know how many Veterans are getting/seeing this prompt)

```
{
    'event': 'vaos-alert-box-displayed',
    'alertBoxHeading': 'You need to have a home address on file to use some of the tool's features'
}
```
> track when Veteran clicks the blue "update my address" button

```
{
    'event': 'nav-warning-alert-box-content-link-click',
    'alertBoxHeading': "You need to have a home address on file to use some of the tool's features"
}
```

Work for you?

**Comment by jbalboni** [comment]
Yep, that works. Do we need to clear `alertBoxHeading` after pushing those events?

**Comment by bsmartin-ep** [comment]
@jbalboni - 

I think it's unlikely to cause any issues (especially if this is the end of the flow for these users), but I say - **yes** - let's null it out if it's not too much trouble.

We really should automate this at some point.  Like a hit-only / clear me flag that immediately clears the DL var after the initial push.

**Comment by narin** [comment]
Hi @bsmartin-ep.  After some additional discussion, we were thinking a more specific event for this particular alert would be preferable.  There are several alerts throughout VAOS, but this one is more important to track.  Would something like the following work?

* Alert displayed: `vaos-update-address-alert-displayed`
* User clicked `vaos-update-address-alert-link-clicked`

**Comment by bsmartin-ep** [comment]
@narin -

> User clicked: `vaos-update-address-alert-link-clicked`

My plan for this was to append the Click Text and alertBoxHeading to the event action.  So something like...

`Navigation - Alert Box Link Click - {{Click Text}} - {{alertBoxHeading}}`

Would that be enough for you to differentiate clicks?

> Alert displayed: `vaos-update-address-alert-displayed`

Good call on this one.  I forgot Jon W was trying to keep the VAOS event actions clean (and instead load up on custom dimensions).

I'm cool with your event label.  Think we still need `alertBoxHeading` on this event?

### While I have your attention...

1. I noticed the `tab-click` event (for the first tab) is automatically firing on page load.  Any way to restrict that to just user tab clicks?

2.  I'm feeling a little queasy about attaching _number of cards_ to a navigation event.  Is this a dimension more associated with an API call rather than a navigation / tab event in your opinion?
