### ISSUE TITLE
[FE] Connected apps carrot is in a line by itself

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#10686]
## Background

In connected apps the last FAQ carrot sits in a line by itself on iPhone 6,7,8, X.  It should have a word or two with it so it's not confusing.

**Comment by sanlouise** [comment]
@mshea0606 @tressaellen As discussed with Tressa, it makes sense to halt working on  this issue for now since the solution would require setting a max-width on to all `AdditionalInfo` components (FAQ links) in Connected Apps which results in a non-desirable UX.  The other workaround to determine whether a line has wrapped or not, and then apply a className accordingly, would be too involved for this arguably minor issue.
