### ISSUE TITLE
Discovery - personas and journey map

### ISSUE THREAD

**Issue by arickalewis1** [department-of-veterans-affairs/va.gov-team#10716]
## Acceptance Criteria
- [x] [Personas](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/user-research/discovery-personas.md) based on discovery research
- [x] [Journey map](https://app.mural.co/t/vsa8243/m/vsa8243/1595002246550/dcc8f89e70628bfb9f123075ff514189005fa17c) based on discovery research

**Comment by abuckley3385** [comment]
@arickalewis1  Can you please update your ticket with the links to the docs in github you have created for personas and journey map. tx

**Comment by abuckley3385** [comment]
@arickalewis1 I've reviewed the Journey maps in the link, are these finished?  There is not acceptance criteria in this ticket so Im not sure what outcome these were to achieve.  Are we wanting one for each persona?  I was thinking these would identify workflow gaps ...is there a way to call those out?

**Comment by abuckley3385** [comment]
@arickalewis1 For the Personas how are you thinking we can use these in our design and engineering? For example [Newbie Nancy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/user-research/discovery-personas.md#newbie-nancy) doesn't have info for us on what a newbie Vet expects differently than the occurring - seems to have more of a mental health focus. 

Same for the rest - Im not clear what we need to design and think differently about each one. 
ie. Elmer - if someone is only focused on Eligibility they are unlikely to fill lout forms because they just want to check the box and get RX vs. ensure the VA team knows their story and everything is correct.  So we need to figure out what will make Elmer want to fill out forms?

**Comment by arickalewis1** [comment]
@abuckley3385 short answer is no not all of them are complete. I focused on who I assumed would be our main user and flushed out the journey as we know it based on the research we have conducted thus far. I think we should do more targeted research on those new to VA and those who only use VA for eligibility to expand on those journeys more. There is a section documenting areas of opportunity for us to incorporate our solution into the current journey. Would you mind clarifying the workflow gaps you are referring to? I think once we have a solid first direction, we can update a journey with concrete gaps in that specific experience.

As far as personas, those were high level based on our initial conversations. I don't think that these personas should point to what needs to be designed but they should assist in understanding how what we create affects these user types.

**Comment by abuckley3385** [comment]
Maybe we need a session (if you could schedule before EOS) same as we are doing for Tech Feasibility where you have a chance to walk the team through these. I need to do the same with the User stories!   Im just wanting to see how to incorporate these docs into our strategy/prioritization so maybe I just need a bit more explanation into your thoughts vs. how I've used personas and blueprints in the past.

**Comment by arickalewis1** [comment]
@abuckley3385 sure thing. These felt like more of a discovery deliverable than anything else. There is a need to create more specific versions of these and use them in the way that I'm assuming you (and I) have used in the past to inform design/tech decisions. These are very much a "here is what I learned" exploratory deliverable.

For example, if we focus on Medications (just an example) we could get more in depth in understanding pain points, gaps, etc. though I can't say for sure a persona or experience map would be the correct method until we get there.

Hope this clarifies!
