### ISSUE TITLE
686c Top Recommendation link going to a 404

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#10735]
## What happened?
_686c Top Recommendation link going to a 404_

## Specs:
- Device: (HP PC - GFE)
- Browser: Chrome

## Steps to Reproduce
- search for "686c' in site search
-  click on the Top Recommendation result https://www.va.gov/disability/add-remove-dependent/add-dependent-form-21-686c/
- goes to a Not Found page

## Screenshot

![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/98052db0-b527-4af8-b60e-4a1ac4efe03b)

## Desired behavior
_Go to the page, not 404_

## Acceptance Criteria
- [ ] _Not 404_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by johnhashva** [comment]
@jenniferlee-dsva  I can fix this easily/quickly today but we need to specify the right URL -- and it looks like I have various options:

- New Find a Form page here, with the correct form found: https://www.va.gov/find-forms/?q=21-686c  
Or:
- The [Add or Remove a Dependent information page here](https://www.va.gov/disability/add-remove-dependent/) -- which does not appear to contain a link to the PDF form 21-686c but instead steers users to eBenefits to make the change.

Which one is better?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @johnhashva. Following up on slack request. 

This is a little bit of a tricky one because, as you mentioned above, the "Add dependents" page doesn't include a prominent link to the 686c (it does include a link, but it's inside the accordions at the bottom of the page that speak to mail or fax. 

In future iterations of form detail landing page, I think the online option will be highlighted (at least as I recall).

But for now, I think we should link to "Add dependents". Assumption being that if user is searching for a specific form, they know and will recognize the reason they're searching for that form. And the form is mentioned in the meta data. Let me know if you agree/have additional questions/thoughts. Thanks!

**Comment by johnhashva** [comment]
@DanielleThierryUSDSVA makes sense -- but look what happened when I plugged the new URL in the Best Bets tool ... I'm guessing this means you can't use the same referral URL for multiple Best Bets (which makes no sense at all).   So for now, I'm linking this best bet to the form page  https://www.va.gov/find-forms/?q=21-686c.   Am I missing something you think?

<img width="891" alt="Screen Shot 2020-06-30 at 1 35 52 PM" src="https://user-images.githubusercontent.com/63107147/86158706-2c2b6d80-bad7-11ea-868b-4c962b9b2b98.png">

**Comment by johnhashva** [comment]
Confirmed this Top Recommendation is now linking to the form page https://www.va.gov/find-forms/?q=21-686c.   At same time, am following up with Search.gov to validate if the error shown above (_URL is already boosted_) means we it is not possible to use the same referral URL for multiple Best Bets.

<img width="755" alt="Screen Shot 2020-07-01 at 9 52 18 AM" src="https://user-images.githubusercontent.com/63107147/86251989-9b10d100-bb80-11ea-9dcf-dd7a6bada129.png">
