### ISSUE TITLE
[Schema.org] [Build] Implement schema.org data for Coronavirus FAQ page content

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#10772]
We recently published a schema.org JSON-LD data structure on `/coronavirus-veteran-frequently-asked-questions/` containing content we wanted to see surface on Google search results. However, we discovered that because this content is not directly represented visually on the page as DOM content, Google invalidates the data.

To fix, we should simply make a schema.org representation of the visual content on the [Coronavirus FAQ page](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/). We can do this by -

1. Fix the schema.org microdata in the templates used to render `/coronavirus-veteran-frequently-asked-questions/`
    - There is schema.org microdata already, but it fails Google's tool for validating schema.org, so it probably doesn't have any affect on search results.
1. Or, figure out a method to generate JSON-LD from the page content

Additional info -

1. The valid schema.org markup should only apply to `/coronavirus-veteran-frequently-asked-questions/` for now. This page will serve as a proof of concept. Other pages should not be affected.
1. We can remove the current JSON-LD structure since it isn't working.

## Acceptance Criteria
- Rich text results for covid related info, which is dependent on when Google's starts to show these results
- [x] Internal AC: changes passes Google's verify tool 
  - **this is validated i.e. no errors. but still tbd about verifying google results**

**Comment by ncksllvn** [comment]
FYI we ultimately want to remove the errors as shown on this page, https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.va.gov%2Fcoronavirus-veteran-frequently-asked-questions%2F

**Comment by ncksllvn** [comment]
The page on Staging appears to pass Google's Structured Data Testing Tool, https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fstaging.va.gov%2Fcoronavirus-veteran-frequently-asked-questions%2F

**Comment by MickinSahni** [comment]
tbd whether we see these results on google. holding onto this ticket to capture final result before closing (probably monday)

**Comment by johnhashva** [comment]
@ncksllvn Received this word back from the Google Group leads re: our FAQ markup ...

- First of all I would like to confirm that the page is indexed, so that's not an issue. 
- However, the FAQ markup is not implemented properly on that page - [here is the Rich Results Test tool verdict](https://search.google.com/test/rich-results?id=tIVKK3fY1oCPVWF2K7qvWg). You can forward this implementation example to your developer and note that when they fix the page, they can upload the code to https://goo.gle/richresults and run the test to validate the page before moving it to production.

The issue appears to be a Page Loading error as seen here

<img width="588" alt="Screen Shot 2020-07-27 at 7 57 52 AM" src="https://user-images.githubusercontent.com/63107147/88539260-ed59dc00-cfde-11ea-8ef3-835a0d257b8a.png">

**Comment by ncksllvn** [comment]
> However, the FAQ markup is not implemented properly on that page - here is the Rich Results Test tool verdict. You can forward this implementation example to your developer and note that when they fix the page, they can upload the code to https://goo.gle/richresults and run the test to validate the page before moving it to production.

Maybe I just can't figure out how to use this tool properly...When I click that link I do see `Page partially loaded` but I don't see any schema.org validation errors.  I only see two unrelated JavaScript errors. Maybe this tool is just very limited in what it offers?

I noticed the URL in that link was missing the trailing slash at the end of `https://www.va.gov/coronavirus-veteran-frequently-asked-questions/`. I added it then reran the tool - https://search.google.com/test/rich-results?id=iH4eB33rBFZajsQbjr-YEw. On this page I see `Page not eligible for rich results known by this test` but no further information so I don't know what to do with that either.

**Comment by johnhashva** [comment]
You don't think the JS errors are the reason for the "rejection"?

**Comment by ncksllvn** [comment]
I don't think so. The first error is just failing to load Google Analytics, which I think is fine since this tool is executing a crawler. The second error is actually just a warning that doesn't affect anything. I wouldn't think that JS errors would affect this anyway since we aren't using JS to render the schema.org data (it's static HTML.) 

I'm looking into the feasibility of using the JSON-LD approach now...

**Comment by ncksllvn** [comment]
I'm having better luck with the validator they suggested by pasting the raw HTML rather than using the URL of the page but I will have to circle back to this tomorrow. I'm gonna try to knock out a couple smaller tickets first.

**Comment by MickinSahni** [comment]
These changes impact all VA.gov pages using the FAQs template. That includes coronavirus faqs as well as disability-related pages.

**Comment by ncksllvn** [comment]
The schema.org validator checks out for the Coronavirus FAQ page! Hopefully we'll start seeing some traffic via rich results soon.

https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=url&id=Yj2p6xxN4-3yiRjqWP7Gzg

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/35dc2ef2-f2f2-4b9c-b420-8a9dfb4a7a66)

**Comment by MickinSahni** [comment]
Covered scope of this ticket. Seems like we're competing with other rich results e.g. CDC. Closing out but may revisit

**Comment by johnhashva** [comment]
As a postscript, adding this exchange with Google re: our COVID 19 Rich Results (FAQ) deployment and validation:

**John's 8/6 post to Google COVID-19 Search Group:**

We have re-formatted the VA COVID-19 FAQ page for rich results, confirmed that it passed validation via the RR tool -- and it is now live here: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/.

However:

- When we preview the markup on the test results page, only the first paragraph of the FAQs (the intro) displays (see here) -- not the actual question/answers.  Is that because the preview feature does not display the entire markup -- or is there an issue in our markup?

- For tracking performance via Google Search Console -- we are seeing Rich Results for FAQs (see attached screen shot) -- but suspect this aggregates search results data for all VA.gov pages that contained the FAQ structured markup.   Is it fair to assume there is no way to track the specific performance of our COVID-19 FAQ rich results?

- If we want to track just the impressions/clicks for the COVID-19 FAQ rich results, do we need to build it in a different way so that -- like Special Announcements markup (see attached) -- it will appear in Search Console as a unique trackable entity?

Google's 8/10 response:

- Regarding the search preview, it is just a simulation, you can see that the URL is not right either... In the validation page you can actually see all the questions and answers Google found in your markup, just click the arrow(please refer to the attached RRT.png) to expand the FAQ details.

- For tracking performance via Search Console, you can actually click the "FAQ rich results" row in the table you sent - this will add a filter to the Performance report that includes only FAQs. Following that, click the "Pages" tab and you will see all pages that showed for a specific search appearance (in your case FAQ). Here is a similar screen (please refer to the attached SC.png) of what you will find.

- Please note that FAQs and Special Announcements are two different types of structured data, there is no such a thing as a COVID-19 FAQ. In your case, it seems pretty clear that the feature to be used in the page is FAQ, there are no announcements in the page.

![SC](https://user-images.githubusercontent.com/63107147/89903177-5469ba00-dbb5-11ea-9acc-dee8e560f07e.png)

![RRT](https://user-images.githubusercontent.com/63107147/89903184-559ae700-dbb5-11ea-8291-34de0853a7ad.png)

**Comment by ncksllvn** [comment]
@johnhashva whoa, based on that chart, it seems like the schema.org fixes we made are working?

**Comment by johnhashva** [comment]
Yes, but as noted, my gut analysis of the pages/links that are driving the impressions and clicks are not related to the COVID-19 FAQ.   On second thought, maybe the issue here is that so many of the page links in the FAQ link out to cdc, www.myhealth.va.gov, veteran.mobile.va.gov -- basically NOT va.gov domain -- meaning we are not able to track all those impressions/clicks.

**Comment by ncksllvn** [comment]
We have FAQ rich results!

![image](https://user-images.githubusercontent.com/1915775/89927115-d668db80-dbd3-11ea-896e-e39c78fa0dae.png)

**Comment by johnhashva** [comment]
**### Postscript/Postscript Update:**   After a bit more finagling with Google Search Console, @ncksllvn and I have confirmed that the COVID-19 FAQs rich results -- with Schema.org structured markup -- is live on Google and generating impressions and clicks.  

<img width="543" alt="Screen Shot 2020-08-11 at 12 27 55 PM" src="https://user-images.githubusercontent.com/63107147/89926551-13809e00-dbd3-11ea-9d44-aa1f4f06b75e.png">

As this implementation involved fixes to templating issues for VA.gov (which came to light via GSC), we now are able to confirm and track that other FAQs rich results are appearing in search results.

<img width="872" alt="Screen Shot 2020-08-11 at 11 18 50 AM" src="https://user-images.githubusercontent.com/63107147/89926983-a3bee300-dbd3-11ea-8524-f88056b8ffe6.png">

We believe this "breakthrough" -- really the result of  a new Google rich results validation and preview tool and our recent implementation of Google Search Console -- will allow us to expand/exploit the rich results format for additional VA.gov use cases.   That will be part of a follow-up phase which we will capture as a Product Outline.
