### ISSUE TITLE
Agent Orange consolidation: Socialize with SMEs

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#10862]
**Related ticket: [Agent Orange consolidation: Implement #10765](#10765)**
## Issue Description
We need to share our recommended approach with SMEs before publishing and implementing redirects.

---
## Tasks

- [x] Share new page/approach with SMEs in meeting (Danielle, Beth)
- [x] Send preview link to SMEs via email (Danielle)

## Acceptance Criteria
Content shared with SMEs.

**Comment by DanielleThierryUSDSVA** [comment]
Email sent to SMEs below. Requested SME feedback by 8/3/20.

Hi Shawn and Paul,

It was so nice talking to you both last week. Thank you again for your collaboration on this.

We’ve finalized the content for the consolidated Agent Orange disability compensation page.

**Here’s the preview for your team’s review:**
preview-prod.vfs.va.gov/preview?nodeId=874

If you could send any feedback by **Monday, August 3**, we’d greatly appreciate it. And if your team has any questions while reviewing, please feel free to reach out anytime.

**Here are the details of our approach:**
 
**Goals:**

- To streamline and consolidate the information about Agent Orange disability compensation eligibility and evidence requirements. This will help Veterans find information on one page rather than having to click into deeper pages for details about eligibility and required evidence based on different exposure situations.

- To limit redundancy of information. Many of the deeper pages currently have information that repeats across multiple pages.

- To ensure that this information is as clear and plain language as possible. While we didn’t introduce new facts, we did look for any opportunities to break up long sentences, use words choices that are as simple and clear as possible, and streamline the flow of information.

New structure for consolidation:
 
Once we’re all in agreement on content, we’ll publish these updates for the main Agent Orange page at https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/. We’ll then retire the subpages highlighted in yellow in the screenshot of the site section’s left navigation below, and redirect their URLs as noted below.

**URLs that we’ll retire and redirect to the updated main Agent Orange page:**

- Related diseases: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/related-diseases/

- Service in Vietnam or Korea: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea/

- Navy or Coast Guard ships in Vietnam: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam/

- Thailand military bases: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/thailand-military-bases/

- C-123 aircraft: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/c-123-aircraft/

- Testing and storage: https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/testing-storage-areas/


**URL that we’ll retire and redirect to a public health page:**

 https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/registry-health-exam/
**Note:** Because this page is about a public health exam rather than disability compensation, we’ve included abbreviated information about the exam on the newly updated main Agent Orange disability compensation page and then will link over to the main public health page for more information.

Thank you again!
Danielle

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. FYSA: We've socialized this work with SMEs, but they've requested until 8/3/20 to give feedback because they have a large group of SMEs. So I've reduced this issue down to just the steps we can complete this sprint, and then created another ticket (#11421) in the backlog for the actual implementation work. Thanks!
