### ISSUE TITLE
SSOe Brain dump

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#10879]
Create a document that outlines the relationships, integrations, and known limitations of the current SSOe implementation.
Audiences to consider:

- Identity team

- Cerner team

- VAOS team

- MHV team

**Comment by patrickvinograd** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/VAgovSSOBrainDump.md

**Comment by patrickvinograd** [comment]
Above is v1; not planning on updating except based on feedback.

**Comment by jholton** [comment]
A few questions after reading the doc.  I'll link to the section in question and provide the bullet points I'm addressing.  My actual questions will be preceded by "Q:"

[Sign-in page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/VAgovSSOBrainDump.md#sign-in-page)
- **Q: is the point of this to allow other VA properties to use va.gov as a authentication gate/broker? Can you provide a full example/use case?**

[Standard Junction/eauth proxy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/VAgovSSOBrainDump.md#standard-junctioneauth-proxy)
- If you see the domain change to “eauth.va.gov” when you sign in, an application is using the standard junction pattern. Makes linking between websites hard because URLs change depending on whether user is signed in or not.
  - **Q: Can you expound on "Makes linking between websites hard because URLs change depending on whether user is signed in or not"?**
- The SSOe proxy server looks up the session contents and passes them to the application as HTTP headers.
  - **Q: example of headers? Does va.gov receive these headers? If so, what do we do with them?**

[Maintaining the SSOe session - VA.gov](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/VAgovSSOBrainDump.md#maintaining-the-ssoe-session---vagov)
- Each call to /keepalive extends the session to (now + 15 min).
  - **Q: Does this mean va.gov sessions are now 15 min? What happens when a user becomes active after 16 minutes of inactivity? Do we need to change TTL values in `redis.yml`?**


**Q: Do you have SAML payload examples?  What's it look like if a ID.me UUID is missing on SSOi?**

**Comment by patrickvinograd** [comment]
I addressed all questions/comments above, and added links to example SAML payloads from vets-api spec factories.

**Comment by jholton** [comment]
The updates look good.  Thanks!
