### ISSUE TITLE
Design - Screens for Express Care flow (happy path)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#10902]
Once Veteran sees active EC prompt on VAOS homepage, Veteran can then start the follow EC flow:

## AC:
- Need designs that enable this flow
- Veteran can exit flow without making EC request

**Comment by rtwell** [comment]
https://vsateams.invisionapp.com/share/U9XQMY2GS5V#/424141776_Express-Care-02a

for reference here:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/f6efb12b-0479-4329-ba5b-71728fbc25a1)

**Comment by rtwell** [comment]
one question i have regarding the H1s on these pages—in vaos, i think we have a lil mini header that says "new appt" persistently on every page, and then the h1 for the page is the question we're asking, correct? if that's the case, we can modify these mocks to keep that pattern. however, since EC is its own thing, i'm not sure its 100% necessary to maintain that parity.

**Comment by melissajschaff** [comment]
Edits to EC flow and content based on research thus far [https://app.zenhub.com/files/133843125/22b0204a-00b3-40a3-8423-51cd81040128/download](https://app.zenhub.com/files/133843125/22b0204a-00b3-40a3-8423-51cd81040128/download)

**Comment by rtwell** [comment]
updated prototype viewable here: https://vsateams.invisionapp.com/share/BVY4QCOJM4U

**Comment by peggygannon** [comment]
@lenaecb and @rtwell Content recommendations for updated EC prototype below (and as dropped into the prototype)

Screen 1

Under Create a new Express Care request
Please update first sentence to:
Do you have a health concern that you need help with today, but it isn't an emergency?

please format the time as:
9:00 to 11:00 a.m.


*Question about the time*: should this be shown in PT, since SF is the first medical center to launch this? time would be 6:00 a.m. for SF Veterans...

please update last bullet point to:
After your screening, we may schedule a follow-up phone, video, or in-person visit or other care if needed.

------

Screen 2
Please update bullet 2 to: 
Any available VA health care provider will respond to your request. They may not be a member of your PACT.

Recommend moving this sentence to be the last sentence in bullet 3:
Not all requests will result in a follow-up appointment. 

 Recommend bolding this sentence as it’s getting lost under the alert: 
**By choosing to continue with your Express Care request, you agree that you don’t have any of the symptoms above**

------
Submitted screen

Add time zone to appointment card as well


-------

EC statuses

Can we see cards for Completed and Canceled?

**Comment by lenaecb** [comment]
@peggygannon - Screen 1: The days/times are dynamic in that we will be pulling that data from VATS based on the facilities configuration. So that will change based on the facilities settings.


These are all the statuses (not currently reflected/updated in the latest prototype). These statuses are part of issue #11002

![image.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/2928d1ae-39f3-43b4-9435-1ffdc87193a4)

**Comment by peggygannon** [comment]
@lenaecb  ok, thank you for clarification on the time zones.

**Comment by rtwell** [comment]
prototype updated w/ @peggygannon's edits: https://vsateams.invisionapp.com/share/BVY4QCOJM4U

**Comment by melissajschaff** [comment]
@peggygannon do you think the button on the VA appointments landing page for Express Care makes sense, or should it say "Create an Express Care request"?

**Comment by peggygannon** [comment]
hi, @melissajschaff I just stepped through the prototype again and I do think we should update this button to
"Create an Express Care request" to match the header and our treatment of other buttons. 

We should also update the button the How it works page to also say: "Create an Express Care request"

**Comment by lenaecb** [comment]
My only concern is that now that button is getting pretty wordy. 

@rtwell - can you make these slight tweaks to the prototype? I am about to break these pages apart into stories so we can implement this sprint.

**Comment by rtwell** [comment]
I can update—however I'm ok leaving the button on the How it works page as "Continue with Express Care request", in fact it could simplify to "Continue" imho but I'm ok with it as-is

**Comment by lenaecb** [comment]
Closing this ticket. Updates for each screen will now be in their respective tickets.
