### ISSUE TITLE
[Engineering] Cerner implementation discovery

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#10960]
## Product Outline
[Link to be updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## Definition of done
 Answer outstanding technical questions re: the Cerner health page implementation

---
## Outstanding questions
1. Are there any resources such as developer docs or centralized code so that we can see what data to work with and how to do so? **answered**

1. What user should we log in with in order to test this implementation? As in, what are the credentials for the test user that contains Cerner-related data?
1. Who do we use for local vs Staging? What do we need to know to get started locally? Is there mock data to help us work locally and if so, who do we login as to use that mock data? **answered**
1. When/how/whether we remove hardcoded approach tracking list of Cerner facilities in the FE- @jenniferlee-dsva 
   - consideration: integrate with "cleaned up" vets-api /user route (to clean up `isCerner`)
1. Who will write end-end-end tests? - @jenniferlee-dsva

**Comment by ncksllvn** [comment]
The biggest issue here that I can see is that we didn't know what we didn't know, so we didn't even know what questions to ask. Going into it, we really just knew it was a new external health care website that we should direct users similar to MHV and that we had mockups. It was also somehow related to SSO. It was very much discovery and it felt strange for a large body of work (integration into a new system) to be passed along as a time-sensitive task to Public Websites. Also, just by the nature of time-sensitive and new, it feels like we should just immediately dive in and discover what questions to ask along the way (which is basically what we did.)

1. Who is the SME or PoC for this? As in, if there is a gray area in the mockups that we don't understand or a technical limitation, how do we get in touch to discuss? 
1. Data questions...do we have it, and how do we work with it?
   - It would have been really useful to have known a user's registered facilities is in the `/user` API route, and that they are actually "parent" facilities (like an ID representing a grouping) that I _think_ are referred to as system IDs rather than facility IDs. The user doesn't necessarily know their facility's parent facility, so they may not recognize the title. [This came up today](https://dsva.slack.com/archives/GTUSXTBNE/p1594128734133000?thread_ts=1594127423.128200&cid=GTUSXTBNE)
    - Once we discovered that the `/user` route contains the user's facilities, we had to uncover what to do with the facility IDs in order to get the facility's name. There was a test facility ID that wasn't in the Facility Locator's API, so we were unclear on what to do. We didn't know we were seeing a test facility, so our understanding was that the facility ID in the user object was different than the IDs expected by the Facility Locator's API.
    - There was also an `isCerner` property on each facility belonging to the user that [we discovered is unreliable](https://dsva.slack.com/archives/C52CL1PKQ/p1594047082451800?thread_ts=1594045778.444400&cid=C52CL1PKQ), and had to scramble to fix it. We did so via a frontend lookup table is likely not scalable, but saves us for the time being. This is somehow related to MVI/MPI doing a test of their own, as [MPI is where the data for Cerner-enrolled facilities seems to originate](https://dsva.slack.com/archives/C52CL1PKQ/p1594047684453700?thread_ts=1594045778.444400&cid=C52CL1PKQ).
1. What can we expect technically speaking?
    - Are there any resources such as developer docs or centralized code so that we can see what data to work with and how to do so?
1. What user should we log in with in order to test this implementation? As in, what are the credentials for the test user that contains Cerner-related data? 
    - We pieced this together by pinging other engineers and discovering ID.me test users such as `chester.morgan@id.me` and `ssoissoetesting+mhvcss3@gmail.com` by scattered Slack messages
    - Who do we use for local vs Staging? What do we need to know to get started locally? Is there mock data to help us work locally and if so, who do we login as to use that mock data?
    - I'm still confused on the various test-only facility IDs and who is using ...us, MVI, or Cerner and test facilities 983, 984, 668, and 757 🤷

**Comment by MickinSahni** [comment]
2020-07-17
LA, JL, KA, NS, DT, MS
---
Background:
- Auth Exp making call to `/user`
- using `/user` to find list of facilities a use belongs to
- created a table on vets-website and go thru the user's facilities and check if it's a Cerner facilities
- if a new facility becomes a Cerner facility, that requires an update from PW to add the new Cerner facility

Best solution - MPI passes the correct data on whether a facility is Cerner

Complication - moving target if a facility is a Cerner facility. 
- current ones will remain: Columbus, Chalmers
- next ones (could be novor dec or even 2021): Spokane
- We should have plenty of notice before a new Cerner facility goes live

Q: is there a way to add fake facilities to test the dynamic logic in lower envs. rather than rely on hard-coding?
- there are test facilities in dev/staging
- long-term solution in prod

Collab Cycle
- PW will go thru Staging Review
  - handle e2e testing **for scheduling only**
  - from auth to various states 
    - can user go to Cerner, MHV, VA.gov  
      - Note: Cerner has a sign-up service. if you're a first time user, it checks the person in Millennium and drops them into the right portal. next time, it takes to the MyVAHealth directly

Scenarios:
- Scheduling scenarios
  - only registered at Cerner --> MyVAHealth (first time vs. later)
  - VA.gov
  - Registered at more than one facility 
- Other health tools
  - MHV
  - My VA Health
