### ISSUE TITLE
[Development/Design] 526: Wizard Updates

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#10966]
## Issue Description
The public websites team is working on a new wizard for 526 and decision reviews.  This story is to capture the time having the initial meetings and discussions leading up to a solution.

John Hashimoto is wanting to start talking about this again.

## Acceptance Criteria
- [ ] Setup meeting with John
- [ ] New work captured in stories
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Spoke with John about this - he would like to understand what timeline we have in mind for implementing this for 526. 

@luke-gcio I'm going to leave this ticket open as a reminder to comm that to him. Otherwise, this ticket has been satisfied. After speaking, John and I determined that a meeting would not be necessary.
