### ISSUE TITLE
Re-evaulate required vs desired acronym inflections for Zeitwerk

### ISSUE THREAD

**Issue by alexpappasoddball** [department-of-veterans-affairs/va.gov-team#10976]
## Description 
Need to evaluate the desired vs required acronyms in order to complete the Zeitwerk migration.

## list of evaluated inflections
Check off when they have been addressed.  View comments on this ticket for details on addressing.
- [x] 'FHIR'
- [x] 'HCA'
- [x] 'ICN'
- [x] 'JWT'
- [x] 'MHV'
- [x] 'NCA'
- [x] 'PCIU'
- [x] 'PDF'
- [x] 'VA' + ‘VAR’

**Comment by alexpappasoddball** [comment]
@erluti are you currently working on this one yet?  Is it in the correct column?

**Comment by erluti** [comment]
@alexpappasoddball I've been focused on the MPI rename story. I think I'll have a PR today and then I'll move on to this

**Comment by erluti** [comment]
Reverted commits for the rollback https://github.com/department-of-veterans-affairs/vets-api/pull/4456/commits

**Comment by erluti** [comment]
What I found out about acronyms that were reverted below, looking at other acronyms from original zeitwerk PR next

- 'JWT'
 - There is a VAOS wrapper for JWT, `modules/vaos/app/services/vaos/jwt.rb`
   - It’s only used in `modules/vaos/app/services/vaos/user_service.rb`
 - Could be renamed something like “JwtToken” or “WebToken”
 - JWT is an acronym (initialism) for JSON Web Tokens and already used by the `jwt` gem, so renaming would probably be helpful anyway
 - Is only used for headers, so no serializing
- 'MHV'
 - Multiple files named ‘mhv_’ with classes named ‘MHV’
   - Causes a zeitwerk loading error when inflection is missing
 - `app/models/messaging_preference.rb` and `app/models/prescription_preference.rb` both have serializers and a method `mhv_params`, but that data doesn’t show up in the serializer
 - `/v0/user` endpoint has a `:mhv_account_state` value that comes from the Users::Profile class’ `va_profile`
   - Inflection doesn’t seem to affect this output in the request spec
- 'NCA'
  - Needed to load `NCAFacility` in `app/facilities/models` and related files
  - Higher_level_review has `nca` as a benefit_type, but the data is passed directly from caseflow and should be unaffected
- 'PCIU'
  - Has a modulespace and subdirectories in `lib/evss`
  - Also weirdly has PCIUAddressLineValidator not in the module
  - User model has ‘pciu_’ attributes, but are not serialized
- 'PDF'
  - We use [pdf-reader](https://rubygems.org/gems/pdf-reader/versions/2.4.0) gem, which uses the namespace ‘PDF’
  - `lib/vso_pdf/vso_appointment_form.rb` uses a `VSOPDF` namespace, but zeitwerk doesn’t seem to care about lib since it’s not autoloading
  - `valid_pdf` is an attribute in a serializer
- 'VA'
  - ‘VAR’ only needed if ‘VA’ is used
  - Swagger has multiple properties with `VA` at the start
  - Serialization discoveries:
    - `va_profile` is a section returned in `/v0/users`, but inflection doesn’t change the response in request specs
    - EVSSClaimDetailSerializer returns a `va_representative`, but the serializer test doesn’t show a difference with inflection
    - Multiple serializers have a type defined as `va_X`
  - VA is used inconsistently throughout the app
  - Without the inflection, `VA` is being “humanized” to `va` in some pdf_fill documents

**Comment by erluti** [comment]
Found out `BGS` is inflected twice currently in master (probably a poorly resolved merge)

**Comment by erluti** [comment]
My recommendations:

- 'FHIR'
  - Should add inflection
- 'HCA'
  - Should add, make sure files are named consistently
- 'ICN'
  - Unnecessary for zeitwerk, revisit if we have an inflection standard
- 'JWT'
  - Only instance that requires inflection could be renamed to not conflict with `jwt` gem
- 'MHV'
  - Should add inflection and consistently name files
- 'NCA'
  - Should add inflection
- 'PCIU'
  - Unnecessary for zeitwerk, revisit if we have an inflection standard.  `lib/evss` could use some more refactoring in general related to names and namespaces
- 'PDF'
  - Only instances of file names using “pdf” in `/app` or `/modules` have it camel-style, `Pdf`.  So we don’t have to introduce this knowing that it breaks a serializer.
- 'VA' + ‘VAR’
  - This should be added, but there is a greater risk of unintended consequences.  I haven’t gathered a list of serializers with `va` in their keys, but many do.
  - This change was isolated and reverted by https://github.com/department-of-veterans-affairs/vets-api/pull/4456/commits/410b18d0a2e937b1bd458895751986eefc4f5cd6 (so it could be un-reverted and potentially have some tests added)

**Comment by erluti** [comment]
Realized the surface area of our risk is a bit smaller.  [OliveBranch](https://github.com/vigetlabs/olive_branch)'s `camel` inflection is contrasted with `pascal` in that it doesn't change the first word in the key.  Which means if the inflected acronym is the first part of the name of a key, wether camel is requested or not won't change the resulting key.  We ran into an issue with `validPDF` because the acronym isn't the first word.
