### ISSUE TITLE
Select Express reason for EC request

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#11035]
As a Veteran who is eligible for EC, I want to be able to submit an EC request to talk to a healthcare provider today about the symptoms I am having. 

## Acceptance Criteria:
- [ ] A veteran can choose from a predefined list of symptoms
- [ ] A veteran can add additional details about their symptoms to send to VA staff with their request
- [ ] A veteran will see their phone # and email pre-populated if they have supplied that in their VA profile
- [ ] A veteran can update their phone # and/or email to a new phone or email for this request
     - [ ] Open item - add copy to help Veteran understand these changes are not reflected in VA profile
- [ ] A veteran can submit a request
- [ ] A veteran can go back to previous screen to re-read 'how to use express care'
- [ ] Open item - how are we handling if a user doesn't see their symptoms in the list?

## Mockups: ([prototype here](https://vsateams.invisionapp.com/share/BVY4QCOJM4U#/screens/425790746))
![Screen Shot 2020-07-22 at 10.37.17 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/a2551537-2a17-4e02-8ec8-ec1f8244c24d)

Symptom with inline open text box
![Screen Shot 2020-07-22 at 10.37.36 AM.png](https://images.zenhubusercontent.com/5e41a7217d1a39827f6e83fe/f5e16a40-f930-4271-af24-908454357a9f)

**Comment by lenaecb** [comment]
@rtwell - do you have a mock with all the current 'approved' symptoms? For implementation I feel like we should consider moving forward with that list, but it's long so not sure how that's looking from a UI perspective and taking into consideration the expansion on the selection to expose the open text box. 

Also @rtwell @peggygannon, I have two open items for us to consider on this page:
- Feedback from stakeholders that we should consider adding copy to help Veteran understand these changes are not reflected in VA profile - I can see where this would be helpful, but we are not doing that elsewhere (idt) in the app
- I think we need to consider how are we handling if a user doesn't see their symptoms in the list

**Comment by peggygannon** [comment]
@rtwell should we be using the updated conditions list from the SMEs that you shared in our sync this week? i don't think that is reflected above. I have the list you shared in the meeting, so just let me know if should edit that one or the one in the mock?

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/88309345-2d1d7c80-ccdc-11ea-8d94-b8c39ed63e3c.png)

**Comment by peggygannon** [comment]
@lenaecb @rtwell Content recommendations for this screen are below. Please let me know if you have any questions. 

[https://app.zenhub.com/files/133843125/bb84352a-2870-4575-bdca-22b073888621/download](https://app.zenhub.com/files/133843125/bb84352a-2870-4575-bdca-22b073888621/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lenaecb. Here are the 2 versions of the symptoms list, based off of the list the SMEs provided.

**Approach 1** is the approach we discussed in slack. In this approach, we include the full emergency warning signs (based largely on Mayo Clinic) for each condition. 

This is the give-all-the-info approach. But it makes for a lot of content, especially on some of the symptoms. And some of the lists include some symptoms that are in our emergency disclaimer (because it wouldn't work to not include them in the emergency warning signs).

**Approach 2** scales this back to a more general "If you have other severe or unusual symptoms" approach and adds "(mild to moderate)" with relevant symptoms. 

[Express Care conditions list approach 1_7.30.20](https://app.zenhub.com/files/133843125/d15e2803-b73e-4da5-8c04-8cb825ac06b1/download) 

[Express Care conditions list approach 2_7.30.20](https://app.zenhub.com/files/133843125/dbbc28ba-3017-4cce-bed6-bbf0196f056e/download)

**Comment by narin** [comment]
Thanks for helping out with the design and copy, all! One concern I have is that the reason field is only expecting a string of up to 256 characters, so I'm not sure how the checkboxes will work, especially if they have the ability to choose several.

**Comment by DanielleThierryUSDSVA** [comment]
Ah, okay. Thank you, @narin. Let me check in on how many options they can choose. The doc that came for editing had "choose all that apply" so thought that would be checkboxes. But that may not be the case, so will check and circle back here. Thanks!

**Comment by rtwell** [comment]
if we end up going this route, we can move the reason field to its own page (which i think you wanted to do anyway).

again, that's a big **IF** we go this route.

**Comment by lenaecb** [comment]
For clarity - from an implementation perspective for this version we are moving forward with the 'approved' list and single selection. (see Ryan's mock on 7/23/20)

We will be sharing the recommended symptoms list from @peggygannon and @DanielleThierryUSDSVA with stakeholders today to get conversations going.

It should be noted that if we do proceed with a multi-select option based on confirmation from stakeholders, we will need to have the BE service updated to allow for that type of functionality as it does not currently exist. 

cc: @rtwell

**Comment by lalexanderson-dsva** [comment]
I agree with implementing with the current approved list now and iterating on this in v2 of EC. I don't much like either option of the symptom list, TBH. 

- The short list repeats the phrasing 'If you have unusual symptoms" so many times that I think users will become numb to it. - The full list is a LOT of content. 

Could we do a variation on this where we use the content of the long list, but parse it in a different way? For example, if we have users FIRST select their symptoms using only the simple names (backache, headache, etc.). That shorter string of text would be what we submit to the BE (per @narin 's comment above). However, if a user selects, say, "cough", we follow up with a series of questions:

> You said you're experiencing a cough. Are you choking or vomiting when you're coughing? (Option to hit: Yes, No)
> Are you having any trouble breathing or swallowing? (Option to hit: Y/N)
> Are you coughing up blood or phlegm that looks ping? (Option to hit Y/N)
> Are you experiencing any chest pain? (OPtion to hit Y/N).

If the user hits YES for any of these symptoms, then we say: "We recommend that you call 911 instead of submitting a request for an express care appointment."

**Comment by DanielleThierryUSDSVA** [comment]
@lalexanderson-dsva Yes, this is one reason why I think we need to regroup before moving forward. I want to make sure we're helping users understand when a symptom or combination of symptoms is an emergency, but in a way that makes sense within the bigger picture.

> The short list repeats the phrasing 'If you have unusual symptoms" so many times that I think users will become numb to it.

I was thinking that the note would appear once the person clicked the symptom. So they'd only see it for the symptom(s) they chose. We have an "add details" field that appears when they select a symptom, right? This note could appear beneath that perhaps?

If it has to appear beneath each symptom on the main page, then I don't think this would work for the reason you state.

> The full list is a LOT of content.

Yes! Couple of things:

- Also thinking this content would appear only if the user clicks a specific symptom.
- We'd said in slack that we didn't want to introduce logic, but definitely happy to talk more about it!
