### ISSUE TITLE
[Design] Create UAT conversation guide

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11245]
## Background
[Sample conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/discovery-research/UAT/conversation-guide.md)

[Profile UAT Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/UAT/profile-conversation-guide-UAT.md)

## Tasks
- [x] Create UAT conversation guide

**Comment by tressaellen** [comment]
Adding this for documentation - the connected apps team wants to add a task around making sure the timestamp shown on a connected app reflects when the app was originally connected rather than when it was last used/loaded.

How we do this:

1.) Make sure that you record the time that the connection takes place (obv you would need to get the Veteran to connect on the call). Then load up the connected apps and make sure the timestamp is correct..
2.) Use the dev tools for whatever browser they’re using to look at the created timestamp in the response for the call to fetch connected apps. Then make sure that’s the time that’s showing :slightly_smiling_face:

You may not even need to do that though – if they’ve already got a connected app, you can just double check that the ‘connected on’ time isn’t the current date and time
