### ISSUE TITLE
[Design] Create UAT Research plan

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11244]
## Background information
[Sample UAT Research Plan]( https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/discovery-research/UAT/research-plan.md)

[Profile UAT Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Research/UAT/profile-research-plan-UAT.md)

## Tasks
- [ ] Create UAT research plan

**Comment by Samara-Strauss** [comment]
Plan for UAT participants:

**LOA 1 users**
- 2 - 3 users
- Can be people from our team who have LOA1 prod accounts. We shouldn't use perigean to recruit for this.

**LOA3 users**
- 4 users who have direct deposit (receive comp & pen benefits)
- 4 who do not have direct deposit (do no receive comp & pen benefits)

**Connected apps** — We should see if the connected apps team has a prod account or can create a prod account that shows what it looks like to have at least one app connected. Perigean won't be able to recruit for this.

Generally, on top of this, Erik and I can also look at things in prod since we both have LOA3 prod accounts. This will be a good opportunity to see what it looks like for people who do not have military information or direct deposit.
