### ISSUE TITLE
[FE] Connected apps error in the wrong screen

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#11333]
## Background

On user +27 the 'cannot retrieve connected apps' error is showing up on a page that there is no connected apps to begin with. This should appear on the connected apps page.

![Screen Shot 2020-07-16 at 11.40.50 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/f6295757-0d4d-4e11-9817-cc0c3e1d3b27)

## Tasks

- [ ] Remove error

**Comment by sanlouise** [comment]
Hey @tressaellen ,

It is not possible to show the 'We could not retrieve your apps' error message _only_ to users who actually have connected apps, because when this error occurs, we get an empty array of `apps` back (since they could not be retrieved), meaning we cannot differentiate between those users _with_ and _without_ connected apps.

Some options I can think of are:
(1) Only showing the error message and leaving the 'Third-party apps you can connect to your profile' out of the UI, since that would be (from my point of view) possibly the only slightly confusing part to have on the UI if I have already connected to apps on that list
(2) Leaving the screen as is but move the alert above 'Third-party apps you can connect to your profile` , I think it's clear enough for the user that we're having issues
(3) Update the copy entirely for the page when we have an error, but I think that would be overfill and the current copy should still be relevant

**Comment by tressaellen** [comment]
@sanlouise thank you for the clarification... for now let's do option 2 and just bump up the alert to be above 'Third-party apps you can connect to your profile'. How often do you think this type of error would occur? Is this a fairly common thing?

cc/ @careyotto for visibility

**Comment by sanlouise** [comment]
@tressaellen I assume it is not a common thing, if this error occurs often we'd need to look into the issue on the backend

**Comment by careyotto** [comment]
Looping @markgreenburg into this convo. I believe he looked up error logs the other day and found 4 in the last 2 weeks? Not sure if those were erros of not being able see which apps a person is connected to or if they were errors in disconnecting.
