### ISSUE TITLE
Documentation Support Request: guidance on User Guides for VSP Products

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#11384]
## Please describe your documentation feedback, describe your request, or ask your question here: 

We need a "User Guide" template and/or guidance for VSP Teams, including:
* What content should (and shouldn't) go in a User Guide
* Emphasis on who the audience is (typically VFS teams) and how to write for them
* A template for User Guide, and/or links to some existing User Guides we think represent the kind of work well
* Possibly accounting for different types of User Guides? (i.e. how are things different for developer-focused, technical User Guides vs. say, a doc on how to use the Sentry UI)

The context is the VSP Initiative Development Checklist ([notes](https://docs.google.com/document/d/1j_9zne5lEfXLjkkrxhcjL-Rg2-esIdGOtdp8C7yjoLI/edit?ts=5efdff9b&pli=1#), [PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/11376)) and wanting to set expectations for VSP teams (primarily PMs) on what a User Guide should contain for a VSP Product/Tool/Feature.

### _What happens now?_ 
_The VSP Content & Information Architecture will triage your request and reach out for more info as needed. If your issue is urgent or you don't hear from us in a timely manner, please reach out to @Megan Kelley, @Gretchen Maciolek, @Kristina Gore in #vfs-platform-support._

**Comment by gmaciolek** [comment]
I suspect that user guides will vary enough across products and practice areas that it might be hard to create a standardized template, but guidelines make sense. And, maybe I'm wrong about the template, but I would have to work through a few examples or write a few to know for sure. 

For existing products, since hardly any of them have product briefs or user guides in the recommended format yet, maybe it would make sense to do a quick audit this sprint to identify which ones would be most valuable for VFS teams to have more thoroughly documented and next sprint use those products to work on drafting guidelines/templates?

Something to consider: With respect to documentation requirements, I think the initiative checklist should be flexible enough to account for the fact that, in some cases, the effort to create and maintain (robust) product documentation may not be worth the effort. Particularly for things that are very new/changing rapidly. I'd love to see us documenting things "just in time" based on a broader communication plan/risk assessment rather than creating more documents to maintain for the sake of checking things off a list. (I'm not necessarily saying that's what we're doing, but having more/new documents on a checklist makes me a little nervous. The minimum documentation standards should be really minimal and anything more than that should be based on an assessment of risk/value.)

**Comment by gunsch** [comment]
@andreahewitt-odd a and I agree a lot with your stance here, especially "minimum documentation standards should be really minimal" --- we're not trying to have this be a heavy-weight process at all, and trying to keep the Initiative Dev Checklist to as few things as needed, while still providing structure and consistency to PMs. For this specific topic, a "User Guide template" is probably unnecessary... though I'm less willing to walk all the way to "User Guides are optional", because IMO without _any_ kind of user documentation we don't have a Product for users to actually use. 

I think what would be more helpful in the short-term is a "User Guide how-to", something that talks through specific high-level advice and questions. Things like:
- What kinds of questions should you be asking when you write a user guide?
- Keeping in mind for VFS users as audience
- Providing step-by-step instructions for specific tasks, and actually walking through them step-by-step to verify

I'm less interested in doing an audit in the meantime. We know about several existing things that don't have great docs, and teams are scheduling efforts working on those (forms library, SOCKS proxy, BE development setup), and I don't imagine the engineering teams to have much more bandwidth beyond that. I'm down to revisit this in this idea in the future though.

**Comment by gunsch** [comment]
Oh, one last thing: in the meantime, Andrea and I scheduled a meeting with you next week to dig into this. I think we could collectively hack together a "User Guide how-to" in that short working session, or at least a good enough draft to then polish up, circulate for review, and publish afterwards. And we can see how it works!

Our process approach so far is trying to be "let's get something minimal, try it out a bit, and iterate on it or even abandon it entirely if needed" --- we'd rather lean toward that than shooting for an ideal state with too much process on the first try. I'm confident that people will just skip/circumvent process entirely if it's too much overhead, or things where they don't see the value (process for process' sake, "checking the box")

**Comment by gmaciolek** [comment]
👍 This sounds like a great plan. I'll move this issue to in progress and spend a few minutes before Thursday thinking of some ideas.

**Comment by gunsch** [comment]
Artifact: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/product-management/writing-user-guides.md

@gmaciolek I'll leave it up to you on whether or not to close this ticket --- but from my POV the immediate request has been completed :)
