### ISSUE TITLE
make up migration/schema issue

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#11450]
## Issue Description
The make up target to run vets-api currently produces a diff to the db/schema.rb file. Migrations exist to drop the two tables changes that are being applied to the schema. 

[Slack thread on the issue](https://dsva.slack.com/archives/CBU0KDSB1/p1595342183425800)

It looks like this is an issue via docker flow and not when natively running/migrating vets-api

---
## Tasks
- [x] Investigate why docker flow makes changes to the schema

**Comment by johnpaulashenfelter** [comment]
Not clear exactly what led to this, but once the db is out of sync with migrations that have been run, with  there's a loop where unapplied or seemingly unapplied migrations can be re-run when using `make up` which runs `rails db:migrate` as part of the process.

Usually this happens because of switching branches and running migrations that are later removed (or ones removed from an existing branch). Cleaning up the db and rebuilding from scratch in the docker container is the simplest solution.

**Comment by johnpaulashenfelter** [comment]
All the diffs between production, our schema.rb as checked in, and a new generated schema are in the PR. We're really close.

I think the plan is likely this:

* Finish tracking down reason/impact of any differences
* Replace the schema with the production schema
* Announce the removal of old migrations
* Remove the old migrations

**Comment by johnpaulashenfelter** [comment]
Difference in schema vs production is being tracked by lighthouse team in https://vajira.max.gov/browse/API-1837
