### ISSUE TITLE
Public Websites [MVP learning center templates]: Back to top component

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11498]
This is a subtask of Accessibility feedback - Design intent collaboration - Public Websites [MVP learning center templates]
#11386

![image](https://user-images.githubusercontent.com/12564977/88180075-d12ef700-cbfa-11ea-9fbe-963189c12d33.png)

1. Jump links must not use smooth-scroll animated scroll. The setting must be 0.
2. “Back to top” should be a component. This would be a great opportunity for inter-op with the “On this page” component. Working in lock-step would be pretty cool!
3. Specification possibilities for Back to top link
        - Use for screens that are longer than 2400px (screens > 600px wide) or 1800px (screens < 600px wide)
        - Use when there are three or more h2 level headings (items in the jump links)
Nielsen Norman (NN) recommends the Back to Top link be placed in the lower right side of the page, and says this is where people expect to see it. User research to determine in the lower left is used.
        - The recommendation from NN is to have one sticky, stationary Back to Top link per page, rather than multiple links in every section.
        - Movement back to top should not be animated.
        - Consider delaying the appearance of the Back to Top link until users reach 1800px vertical height.
        - `<a href=”#content”>Back to top</a>`
        - Example of potential lower right sticky link shown.

**Comment by andaleliz** [comment]
> Jump links must not use smooth-scroll animated scroll. The setting must be 0.
agree with this, something to be communicated to devs during that stage. Shouldn't this be a standard across the site?

Regarding the rest of the feedback, I took a look at the [NNgroup article](https://www.nngroup.com/articles/back-to-top/) I think she references, which states:
> In usability studies, we observe people ignoring these repetitive links because they are so predictable.
That makes sense to me.  I've always designed/implemented back to top buttons as a sticky element in the bottom right (sometimes conditionally appearing depending on page length) too. 

I think sticky elements are a no-go on our site though, due to conflicts w/ alerts.  Interested to hear what others think.

I agree w/ comments about animation and the mark-up.

**Comment by andaleliz** [comment]
This is going to be addressed with a global component (yay!) that @rtwell will handle.

**Comment by andaleliz** [comment]
@rtwell Is there a ticket interested parties can use to track progress on the global back-to-top component? Do we need to keep this ticket open for any reason?

**Comment by andaleliz** [comment]
Yay! That's exciting - I LOLd at your response:

> I certainly do!

Very cool. 

I'll close this out, don't think we need it anymore.
