### ISSUE TITLE
[Design] - MVP learning center templates, tables 

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11499]
Create desktop and mobile mock-ups reflecting responsive tables in the learning center `about` template.

**Acceptance Criteria**
- [x] Update design of desktop templates with tables
- [x] create design for mobile experience
- [x] @andaleliz @jenniferlee-dsva @rtwell and @ncksllvn to review
- [x] refine based on meeting of the minds ^ 

**Background**
This is a subtask of Accessibility feedback - Design intent collaboration - Public Websites [MVP learning center templates]
#11386

**Considerations**
- How we handled rates tables
- can people jump to specific locations? sort of do this with h2's

# Tables - simple

![image](https://user-images.githubusercontent.com/12564977/88180681-bc069800-cbfb-11ea-85fe-3c3be11d0156.png)

1. Data tables on Tables pages should use the new responsive table component. The new component includes aria to patch when CSS display property changes from semantic table values in the smaller viewports.

# Tables - complex

![image](https://user-images.githubusercontent.com/12564977/88180741-d6d90c80-cbfb-11ea-89c6-2c7297dacd6b.png)

1. Data tables on Tables pages should use the new responsive table component.
2. What would the mobile expectation be? I’m happy to work through that with you.
3. Perhaps the columns to the right drop into an expandable drawer and are stacked, as shown in examples from my Fidelity.com work.

**Comment by andaleliz** [comment]
Makes sense to me to leverage the new responsive table component. I don't see it on design.va.gov/components though - must be in development? Maybe what was shown in the last sprint demo?

I like the suggestion about the expandable drawer, but I'm not convinced that is a valid solution across the many use cases for complex tables content authors will surely come up with.  Tables are great for comparing data, and you can't do that easily when data is hidden in a drawer.  I think in the example in the screenshot, that would be a fine solution. Perhaps we can offer a couple of versions, in versions post-MVP?

**Comment by jenniferlee-dsva** [comment]
RE tables - @kevwalsh @oksana-c  for awareness. There were some CMS table bugs (e.g., having to have a fake 'null' value in a cell) that I want to make sure doesn't collide with above FE and design enhancements.

**Comment by andaleliz** [comment]
@jenniferlee-dsva will content authors have the ability to use tables on LC pages for MVP 1.0?  Also, will they be limited to using tables only in certain templates (e.g. only `About`)?

**Comment by andaleliz** [comment]
FYI, for inspiration or use if has been added to design system: [example of responsive table](https://staging.va.gov/va-payment-history/payments/) by eBenefits team (Jason Wolf posted in Slack).

**Comment by andaleliz** [comment]
Put together a [Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1599058756286/389fe124296d14b2ceee7ea532497e8e12c3aaad) exploring possibilities.

I mocked-up solutions to explore: 
- using what eBenefits team has started
- use cases where people are looking up something specific in a table, such as a rate that applies to them (look up table 
- use cases where people need to compare values side by side (comparison table - I don't know have a handy content example for this)

Currently, my thinking is that our MVP should build upon what eBenefits has started with the addition of some functionality to either help users traverse a tall table (a "jump to row" or filter), or putting things into an expandable drawer.  It may be a combination of the two, or maybe logic where the "jump to" displays if the table has more than 5 rows, and the drawer appears when there are more than 3 columns.  

Once we know more about how people are using tables in the learning center, we could roll out a second table component or upgrade, that would give people side-by-side comparison functionality when needed.  Maybe users can toggle between the two views (like a list view vs grid view).

I'll get feedback from a11y about these approaches Tuesday next week, and then continue on with mobile mock-ups for MVP 1.0.

**Comment by andaleliz** [comment]
Forked @jenstrickland's [code pen](https://codepen.io/surfbird/pen/dyMdEzL), very much a WIP

**Comment by sshein** [comment]
For the comparison tables (I know probably future work) have you thought about the affordance where the user doesn't just choose which columns appear on the tables, but instead there are a set number of columns always (e.g. 3) and the user chooses which 3 columns appear. Or the first column is always set, but the user can choose what appears in the 2nd and potentially 3rd columns. e.g. something like this
<img width="691" alt="Screen Shot 2020-09-10 at 3 53 27 PM" src="https://user-images.githubusercontent.com/3856611/92819577-cc2a3080-f37d-11ea-87b3-e67650ed1c18.png">

**Comment by andaleliz** [comment]
@jenstrickland and @rtwell - I've moved the latest versions of the tables into [UXPin](https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132502661/documentation/no-panels?mode=i) - not everyone finds Mural to be easy/clear to navigate and understand.  

I translated Ryan's complex table template example into a mobile template w/ the new design, and then included a few other table examples w/ different types of content, outside of the mobile template. Thought it might be helpful to see how the design would scale to different content.

Hopefully this is more clear/scannable than the previous version we looked at.  The `show details` links are 10px from the line above. We usually do things in 8's, but 8px is too close to the text above, and 16px felt too far. Since that text could be a link, I used the same px distance that gov.uk has between clickable elements in their step-by-step map.

Check out the `show all` treatment - interested to know what you think. This will apply to the step-by-step template as well.

@jenstrickland, I have a few questions for you:
- Is the phrasing `show details` a11y friendly, if we have more specific SR text?
- I know you took this similar approach of putting things in drawer for Fidelity. How did your drawer concept translate to desktop?  In the screenshots, it looks like there are no drawers on the desktop version.
- Do you have any additional notes you want included in the documentation?
- Would it be possible to update your Codepen to reflect this version?

I think the next step would be to share w/ Jen Lee, and devs (FE and CMS). I'm not sure what the breakup of the work would be between the CMS and PW teams.

**Comment by andaleliz** [comment]
@jenstrickland and @rtwell, also wanted to get your input on something else we didn't really discuss - [the comparison table concepts](https://app.mural.co/t/vsa8243/m/vsa8243/1599058756286/389fe124296d14b2ceee7ea532497e8e12c3aaad?wid=0-1599236806339).  

I don't think we have a strong use case to build these out for our MVP. In my "blue sky" world, content authors can choose between a `look up` or `comparison` table type and select the one most appropriate for their data.

What are your thoughts on this? Do we just put those ideas on hold until we're ready to iterate on MVP 1.1 or beyond? I'm inclined to at least get those concepts on product/CMS's radar but maybe it's too early.

**Comment by jenstrickland** [comment]
**Re the comparison table**, here's a link from CMS's WDS that uses the responsive horizontal scrolling: https://design.cms.gov/components/table/ and an implementation https://design.cms.gov/components/date-field/.

I think it's wise to keep the comparison use case in mind as we work through the look up design. Making sure we're thinking about that is important for the architecture of how the MVP is constructed.

**Comment by jenstrickland** [comment]
**Re the lookup table**, is there a mobile UXPin version? The link looks like a desktop version, and I don't see `show details` on the screen.

1. Did you consider 12px (so that it is multiples of 4)?

**Comment by andaleliz** [comment]
There are mobile screens after the desktop screen - I put the desktop in
there for context but maybe better to just link to it. In UXPin, there’s a
site map drop down in the upper left that should give you a list of all the
screens.

I didn’t consider 12px because I was trying to keep it as close to the text
as possible.
-- 
Liz Lantz
Senior UX Designer, Ad Hoc
843-898-4463
http://adhoc.team

**Comment by jenstrickland** [comment]
> - give user option to expand/collapse all, when there is more than 1 row of data (also, is a table the best presentation if there's only 1 row?

It will be up to the content author to decide if they use a table, list, or 🤷 . We could make the collapse functionality only kick in if a table has more than one row.

<hr/>

> Aside, something I noticed

![Screen Shot 2020-09-14 at 12 15 47 PM](https://user-images.githubusercontent.com/57469/93111005-0a786600-f684-11ea-894c-bc74807eba42.png)

This paragraph could be broken into bullets to help users digest the content, if this is real content, and provide an example for content authors.
* **Level L through O** …
* **Level R** …
* **Level S** …

<hr/>

> Is the phrasing show details a11y friendly, if we have more specific SR text?

Sharing an idea I had while reviewing this; perhaps it isn't necessary to repeat the first column header. I need to review some other tables, though. If there are other tables where repeating this information is useful. My hunch, though, is that the first column header would be too noisy to repeat in tables, and it would more likely that the caption/heading conveys this info.

![Screen Shot 2020-09-14 at 12 17 54 PM](https://user-images.githubusercontent.com/57469/93111922-524bbd00-f685-11ea-9eec-e9e6deafd87b.png)

![Screen Shot 2020-09-14 at 12 20 33 PM](https://user-images.githubusercontent.com/57469/93111962-6099d900-f685-11ea-9cbc-bc0880601940.png)

<hr/>

> I know you took this similar approach of putting things in drawer for Fidelity. How did your drawer concept translate to desktop? In the screenshots, it looks like there are no drawers on the desktop version.

For Fidelity's Positions grid, at the time of this comp we were only showing what happens when horizontal space is reduced and columns drop into a drawer. In the actual implementation, we also have much more information in the drawer so the drawer opened on desktop too to display the additional information — including interactive content. If you have a Fidelity.com account, it's possible to review that. Here's a very blurry screenshot of the open drawer:

![Screen Shot 2020-09-14 at 12 49 43 PM](https://user-images.githubusercontent.com/57469/93114645-d3f11a00-f688-11ea-98f5-017a33525086.png)

<hr/>

> Do you have any additional notes you want included in the documentation?

There are annotations in the Codepen code for development (i.e., that the `role="various_values"` needs to be added to the table markup because the CSS display properties are changed in the mobile view. This may result in some axe errors — we'll need to see how that goes.

<hr/>

> Would it be possible to update your Codepen to reflect this version?

I can set aside some time to do that. Let me know when there's a version you'd like updated to.

**Comment by andaleliz** [comment]
>Re the comparison table, here's a link from CMS's WDS that uses the responsive horizontal scrolling: https://design.cms.gov/components/table/ and an implementation https://design.cms.gov/components/date-field/.


@jenstrickland , I interpret your reference to that documentation as `This is the most accessible way we can present a comparison table on VA.gov and IMO we should not pursue any of the concepts you shared in Mural` ... lmk if I'm misinterpreting that.  

On my end it looks like basically they are just leaving the table presentation as-is and letting the view scroll horizontally on the table itself.  There is something really nice about that simplicity, but I wonder for a many-column table, if the user would lose context since the row headings 

---
>For Fidelity's Positions grid, at the time of this comp we were only showing what happens when horizontal space is reduced and columns drop into a drawer. In the actual implementation, we also have much more information in the drawer so the drawer opened on desktop too to display the additional information — including interactive content. If you have a Fidelity.com account, it's possible to review that. Here's a very blurry screenshot of the open drawer:

The majority of the table examples I've seen have 3 columns, so it doesn't seem to me like the drawer on desktop makes a lot of sense. But I'm not sure how to handle the mark-up going from a regular table on desktop to what I've proposed.  I'd like to avoid a totally separate DOM for desktop and mobile.

---

>Sharing an idea I had while reviewing this; perhaps it isn't necessary to repeat the first column header. I need to review some other tables, though. If there are other tables where repeating this information is useful. My hunch, though, is that the first column header would be too noisy to repeat in tables, and it would more likely that the caption/heading conveys this info.

I totally see what you're saying. We just don't know what content authors are going to populate these with or how they'll use them.   Check out the [first table on this page](https://www.va.gov/disability/survivor-dic-rates/) - I think this would be weird if it just said "show all [value of first cell] details"

---

Thank you SO SO SO much for helping me with this! These comments feel a little unwieldy to me, so if you feel the same and want to hop on a call, lmk.

**Comment by jenstrickland** [comment]
> I interpret your reference to that documentation as This is the most accessible way we can present a comparison table on VA.gov and IMO we should not pursue any of the concepts you shared in Mural ... lmk if I'm misinterpreting that.

🤦‍♀️  I'm sorry I gave that impression. I think I forgot to complete my thought since there were so many moving parts all happening at the same moment. I should have focused on one bullet point (and project!) at a time.

I'm not convinced that this horizontal scrolling solution is appropriate for anything more than an MVP. In user research sessions at other companies, this solution suffered from a couple of issues: 
  - understandability - people didn't realize there was more to scroll to even with the text indicating such
  - rendering issues - the horizontal scroll breaks the page layout on mobile, so what appears above and below is blank, leading to confusion and lack of context; we also had some redrawing and freezing issues with the device performance 

That's how we landed on implementations like the Fidelity Account Positions grid.

**Comment by jenstrickland** [comment]
> The majority of the table examples I've seen have 3 columns, so it doesn't seem to me like the drawer on desktop makes a lot of sense. But I'm not sure how to handle the mark-up going from a regular table on desktop to what I've proposed. I'd like to avoid a totally separate DOM for desktop and mobile.

Agreed! There would be one table markup, adding the role attributes to patch semantics when CSS display properties break them.

```
<table data-template="paragraphs/table" data-entity-id="7237" class="va-table rwd" role="table">

            <caption>SMC&nbsp;rate payment variations</caption>
    
                <thead>
                    <tr role="row">
                        <th scope="col" role="columnheader">SMC letter designation</th>
                        <th scope="col" role="columnheader">Monthly payment (in&nbsp;U.S.&nbsp;$)</th>
                        <th scope="col" role="columnheader">How this payment variation works</th>
                    </tr>
                </thead>
                <tbody>
                    <tr role="row">
                        <td role="cell"><dfn>SMC letter designation</dfn><span>SMC-K</span></td>
                        <td role="cell"><dfn>Monthly payment (in&nbsp;U.S.&nbsp;$)</dfn><span class="currency">110.31</span></td>
                        <td role="cell"><dfn>How this payment variation works</dfn><span class="paragraph">If you qualify for SMC-K, we add this rate to your basic disability compensation rate for any disability rating from 0% to 100%. We also add this rate to all SMC basic rates except SMC-O, SMC-Q, and SMC-R. You may receive 1 to 3 SMC-K awards in addition to basic and SMC rates.</span></td>
                    </tr>
                    <tr role="row">
                        <td role="cell"><dfn>SMC letter designation</dfn><span>SMC-Q</span></td>
                        <td role="cell"><dfn>Monthly payment (in&nbsp;U.S.&nbsp;$)</dfn><span class="currency">67.00</span></td>
                        <td role="cell"><dfn>How this payment variation works</dfn><span class="paragraph">This is a protected rate that we haven’t awarded since August 19, 1968. If we awarded you an SMC-Q designation, we pay this rate in place of your basic disability compensation rate.</span></td>
                    </tr>
                </tbody>
                    
            </table>
```

**Comment by jenstrickland** [comment]
> I totally see what you're saying. We just don't know what content authors are going to populate these with or how they'll use them. Check out the first table on this page - I think this would be weird if it just said "show all [value of first cell] details"

When I look at that table, I think the caption needs to be revisited with plain language in mind, and should include the heading of the first column to be clearer, and would ask Peggy to help compose a better heading without "If this description is true…". I acknowledge there may be tables that we would use the first column table heading, but with the tables I've seen so far, it seems that the first cell in each row is a `th` and doesn't need the column heading.

**Comment by jenstrickland** [comment]
Agreed! The comments did feel unwieldy. This virtual collab stuff can be hard. Monday and Tuesday are so full of meetings that async collab becomes necessary. Feel free to ping me on Slack, and maybe we can find some time — or put some time on my calendar. 💓

**Comment by andaleliz** [comment]
@kelsonic, I'm at a point where I'd like to get your input on these designs.  Specifically:
-  Is anything here that would require updates in the CMS? If so, it'd be helpful to get details that I can share w/ that team when I get their eyes on it.
- Is there anything here that you would break out as MVP 1.0, MVP 1.1, etc? Not sure what the lift is to execute what I've outlined here.

I reviewed these with @ncksllvn last Friday and the documentation captures his thoughts.  Nick, feel free to take another look and chime in if you'd like! Everything is in [bunch of screens in UXPin](https://preview.uxpin.com/192f5be770c74272f782765a19a196aed0a4a588#/pages/132502689/documentation/no-panels?mode=i), along w/ notes and documentation that I hope are helpful.

The first 2 screens show a table inside the template.  The rest of the table screens after that have documentation about specific elements, and show examples of how this pattern would scale with different types of content.  If you go far enough you'll get to a couple of step-by-step screens which are part of a different ticket :)

I'd love to hear your thoughts before I request a design review from VSP.   Let me know if you have questions, or if it's better to discuss in a call.

**Comment by andaleliz** [comment]
@sshein I had considered that, and it didn't make it into the mural because I got excited about those other options! It is future work, but I'll add your screenshots so we remember that when we get there. Thanks for that addition.

**Comment by MickinSahni** [comment]
@jenniferlee-dsva to take a look for global vs. not.

**Comment by jenniferlee-dsva** [comment]
Jeeez - I am not sure where to drop in to this gianormous thread. Addressing the simple questions - ignoring the tremendous back-n-forth that's impossible to follow: 

**>andaleliz
>commented on Aug 31, 2020
>@jenniferlee-dsva will content authors have the ability to use tables on LC pages for MVP 1.0? Also, will they be >limited to using tables only in certain templates (e.g. only About)?**

Yes, table component will be enabled in the About LC 1.0 . 

**RE comparison tables - per slack: https://dsva.slack.com/archives/C0173CAJ7A6/p1600265414191500?thread_ts=1600262696.189100&cid=C0173CAJ7A6**
"...comparisons are so particular, they should /could be a niche type of table. Which we are not implementing for mvp 1 or 1.1, but it could be good follow on improvement for tables in general/globally  (not specific to LC)."

**RE mobile responsiveness:** So I'm assuming we're already mobile responsive - as suggested above - these exist. If our tables are currently NOT mobile responsive, that is something we can and should address with LC table component -- this would be to make it mobile responsive, NOT to add a bunch of new functionalities like expand/collapse. The expand/collapse would collide a bit with tables when they're in an accordion (accordion expand/collapse; then table expand/collapse - no please! )

@andaleliz - here is the [CMS ticket on LC tables ](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2487undefined#issuecomment-693605279)- tldr: we are basically using the existing table component in the CMS with a few updates such as column # limits, so on. So I think you can safely 'table' most of the updates here for global work. (If we encounter that comparisons are a typical content model in VA - we don't actually know that today and it seems silly to create a new CMS product for 1 or 2 use cases.)

**Comment by andaleliz** [comment]
@jenniferlee-dsva the current tables aren't responsive.  The eBenefits team has a [responsive table solution,](https://staging.va.gov/va-payment-history/payments/) but it has a11y problems and from what I understand, hasn't been through a design review. It's not really a model we should follow.

I think appropriate next steps are to revise what I have in UXPin to be MVP mobile responsive and submit that for a design intent review once I'm done with the card sort synthesis.  Hopefully that means we can have that process resolved by the end of the upcoming sprint.  Let me know if you disagree.

The rest of the concepts - including comparison - can be revisited once we know more about how people are populating, and using these tables.  I hear what you're saying about the expand/collapse inside an accordion, but Ryan, Jennifer, and I all agreed that it'd be a UX improvement worth considering.

**Comment by jenniferlee-dsva** [comment]
Ah, got it. If the mobile table solutions are not currently in use, then we will not be able to launch with it for LC 1.0.  This is a global design system issue to be resolved through design system global channel. 

Expand/collapse table - let's sync @rtwell @andaleliz  - I'm not sure I understand this and whether this is more important than sticky column and row headers for 1.0.

**Comment by jenstrickland** [comment]
The eBenefits teams has the start of a responsive table solution for the React apps. It is a start, but needs some accessibility enhancements. 

@rtwell can elaborate on the collaborations sessions the three of us had where we included the possibility of the expand/collapse all functionality, following gov.uk models and my previous responsive tables work for Fidelity.com.

**Comment by andaleliz** [comment]
@jenniferlee-dsva I'm confused. In your first comment you said:
> If our tables are currently NOT mobile responsive, that is something we can and should address with LC table component -- this would be to make it mobile responsive, NOT to add a bunch of new functionalities like expand/collapse. 

but then the following comment doesn't quite jive with that:

>Ah, got it. If the mobile table solutions are not currently in use, then we will not be able to launch with it for LC 1.0. This is a global design system issue to be resolved through design system global channel.

Do you mean that we will address mobile responsiveness in the learning center table component in 1.1 then? Any clarification  is appreciated.

I agree that a global solution is something separate from the learning center.  I see the learning center as an opportunity to make changes incrementally, on a smaller scale.  I need to verify with @kelsonic, but I think it's possible that at a minimum, we can make LC tables responsive without changing the CMS, or introducing new a11y problems.  We may even be able to **improve** a11y without changing the CMS. 

---
>Expand/collapse table - let's sync @rtwell @andaleliz - I'm not sure I understand this and whether this is more important than sticky column and row headers for 1.0. (Maybe it is? But I haven't seen/heard anything about this collapse table feature. ) Also, could we have sticky columns/rows based on how many rows or columns a table has? i.e., kind of like ourback to top based on page height.

Sticky column/row headers haven't been part of any of the designs I'm proposing for now. That UX introduces a lot of complexities that, IMO, would be out of scope to solve for an MVP 1.x.  We'd need to do a fair amount of usability testing with live prototypes, and from the table examples I've seen, I think we're better off starting with some basic improvements and learning how those go over with content authors and Veterans.

A super brief summary of the convo we had regarding expand/collapse in an accordion, and approach to the mobile tables - when you're holding a device in your hand, it's a much more intimate experience than a desktop.  The user wouldn't really see the accordion expanding/contracting as they interacted with the cells, unless they were at the very bottom...but even then they'd likely be focusing on the data and not if bottom border of the accordion that flows with the content they're interested in.

If you still want to sync up with the three of us, we can certainly do so!  Otherwise, I'm prepared to move forward reworking a bare bones MVP and getting that into the collab cycle review once I'm done with the card sort synthesis.

**Comment by jenniferlee-dsva** [comment]
@rtwell and I synced. Thx @rtwell for walking me through the massive ^ thread. 
@andaleliz @jenstrickland - the show/hide UX for mobile table cells is really clever - it looks like a very smart mobile solution. Sorry I was a little slow to grok the comments ^.  my only requirements wrt to this FE UX, from a business side are - yes let's do this for LC MVP IF: 

1/  this does NOT require cms implementation, and
2/ this does NOT get bogged down in global design system approval processes

I would also say the ETA for FE mobile optimization can be 1.1  - the December launch - if we need the time to figure out the details. (Just know that the About template is launching with 1.0. This shouldn't be a big problem because we will likely do a soft/beta launch first.

**Comment by andaleliz** [comment]
Thanks @jenniferlee-dsva. @rtwell, @jenstrickland and I synced today as well. I'm excited that we can improve this UX for our learning center users!  I updated the [status and decisions doc ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md#091820)with what we talked about, so information isn't lost in this crazy thread.  

@jenstrickland if you have a codepen to add to the prototype info in the status doc, please do!  We can also add it to Kelson's FE ticket to build the About template once that gets created (I'll keep my eyes peeled).

I briefly spoke to @kelsonic to try to get an idea of any CMS changes that might be required to implement my design.  He couldn't answer definitively today, but said that as long as the data comes from the CMS, there shouldn't be any problems.   @kelsonic , can you let us know what you need to confirm what can/can't be done on your end?

To keep things moving, I'd like to request the async design review from the collab cycle ASAP to get their sign off on the designs. I foresee stripping down the designs rather than adding anything new if Kelson comes back with changes, so I think we'll be okay. @jenniferlee-dsva are you good with that?

**Comment by andaleliz** [comment]
@kelsonic, friendly reminder: can you let us know what you need to confirm what can/can't be done on your end?

**Comment by jenniferlee-dsva** [comment]
@andaleliz - Responding to https://github.com/department-of-veterans-affairs/va.gov-team/issues/11499#issuecomment-695070590 - yes, that sounds great. If anything requires CMS changes, let's sync again as we will need to scuttle it for MVP in that case.

**Comment by kelsonic** [comment]
@andaleliz Checked in with @ncksllvn and we can't see any problems, this seems 100% doable 👍

**Comment by andaleliz** [comment]
Wonderful!  I submitted the [design review request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13825), and am closing this ticket.
