### ISSUE TITLE
[Design] - MVP learning center - mobile home page MVP 1.1

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#11490]
Create mobile version of home page for MVP 1.1

## Acceptance criteria

- [x] create mobile version of MVP 1.1 . address what happens to audience sections, possibly a `show more` for topics, and maybe less articles
- [x] @andaleliz, @rtwell, and @jenniferlee-dsva to review
- [x] review w @jenstrickland  

## Background
This is a sub-ticket of https://github.com/department-of-veterans-affairs/va.gov-team/issues/11386

![image](https://user-images.githubusercontent.com/12564977/88173481-a2ac1e80-cbf0-11ea-87f9-cc7eb60b3772.png)

![image](https://user-images.githubusercontent.com/12564977/88173495-a9d32c80-cbf0-11ea-894e-326a2a00a1fa.png)

### Original feedback from design intent #10955 
1. Unsure about the radio buttons for searching just Learning Center or all of VA.gov. Does the whole VA.gov search return results here, or does it go somewhere else? Is there a way to just silo this to the Learning Center? Is there a need to search on VA.gov here? A use case?
2. Search boxes need labels. This could be ‘aria-label’ which won't translate if we start supporting additional languages, or ‘aria-labelledby’ that references a nearby heading by ID.
3. How do these Show more work? 
        - If the area expands, the other does not, or does this go to a new page?
        - How many list items must there be for the Show more to appear?
    - For mobile, perhaps these lists collapse/expand?
    - The Learning Center home has a lot of lists. I recommend adding `aria-labelledby` attributes to the UL or OL tags that reference their heading by ID. This is very helpful when SR users land on the list, it'll read the heading, and add context.

**Comment by andaleliz** [comment]
@andaleliz  will explore
- complete mobile package: what happens to audience (converst to audidence), show more topics, maybe less articles

We will hold off on changes to search until we hear from participants, but possibly explore adding an h3 and label if needed.

**Comment by andaleliz** [comment]
Ryan says no to bullets.

**Comment by andaleliz** [comment]
@rtwell FYI added new AC based on convo w/ Jen Lee

> create mobile version of MVP 1.0 (what we'll launch with)

**Comment by andaleliz** [comment]
talked to @rtwell today; he has this underway and will take care of this.

**Comment by rtwell** [comment]
@andaleliz there is also #12758, which feels duplicative but i trust your github expertise more than mine. posting comps in both issues (hopefully, this is helpful)

![image](https://user-images.githubusercontent.com/12564977/91847189-607eef80-ec28-11ea-918a-8ab739f15f4f.png)

**Comment by andaleliz** [comment]
Thanks @rtwell - this is for mobile, whereas the other one was for desktop.  They came up at separate times otherwise I would've just put them both in the same ticket.

**Comment by andaleliz** [comment]
@rtwell Do you have a mobile home page design for MVP 1.1, or are you working on one? I don't see one in the Mural board. Wondering if we can close this out.

**Comment by rtwell** [comment]
i do not, unfortunately

**Comment by andaleliz** [comment]
No problem @rtwell - I'll update the ticket to make it more clear that this is for 1.1. Is this something you're going to tackle, or should we put it in the public websites backlog so the team can prioritize this work?

**Comment by andaleliz** [comment]
I'm comfortable tackling it from all perspectives except time :) But I'll put it in our backlog and prioritize with the team. I'll be sure to include you. If you decide to work on it, please let me know when you start.

**Comment by jenniferlee-dsva** [comment]
Could we make sure to update the mockups here, in GH, and on mural? I think the mobile search bar design has changed for instance, and not sure if there are other things as well. (Of course, content has.) @andaleliz @rtwell

**Comment by andaleliz** [comment]
Going forward, is it possible to use something like UX Pin or InVision for
mockups instead of GH or Mural?

 It’d be great to use a tool We can sync directly to Instead of manually
exporting/uploading to multiple places.

We could put a link to the Mockups into the GH ticket which would provide
easy access for interested parties to the most up to date versions.

Devs and QA are also familiar with these tools and and confirm design
details through code using them.
-- 
Liz Lantz
Senior UX Designer, Ad Hoc
843-898-4463
http://adhoc.team

**Comment by andaleliz** [comment]
I have access to UXPin these days- I can ask about sharing my login so you
could sync from Sketch via the plugin, if that works for you.

Or, does Zeplin have a similar function, where I could just login to a
plugin and and push updates to the prototype? I don’t think either of us
would need to log into the app UI itself too often.

There’s a chance I’ll be out for 6-12 weeks starting Dec 7, which I think
will be most of 1.1 and will result in you leading the design effort
for that.
-- 
Liz Lantz
Senior UX Designer, Ad Hoc
843-898-4463
http://adhoc.team

**Comment by jenniferlee-dsva** [comment]
Leave the tool up to you both. I am actually not invested in the what - I just want to be able to send the exact mockup(s) to Nick or Kelson, as that was a bit of an issue for FE.

**Comment by jenniferlee-dsva** [comment]
Also ^ We'll need updated 1.1 mobile homepage view showing additional topic categories and the audience boxes.

**Comment by andaleliz** [comment]
Yep, there are a few 1.1 design tickets out there, I believe assigned to both me and Ryan. Not sure if you want me to prioritize them over the IRIS research, or have Ryan tackle them.  Something to figure out in grooming/planning, I believe.

**Comment by jenniferlee-dsva** [comment]
Would you two mind conferring to see who has availability?  there are mobile interactions that ryan and I discussed which we would def need to capture regardless of who does the design and design validation. Thank you!

**Comment by andaleliz** [comment]
I don’t mind at all. When do they need to be completed by?
-- 
Liz Lantz
Senior UX Designer, Ad Hoc
843-898-4463
http://adhoc.team

**Comment by brianalloyd** [comment]
@andaleliz @rtwell can you provide an estimate on this ticket as well?  Once estimated please remove the `needs-grooming` label in support. TY

**Comment by andaleliz** [comment]
@rtwell and @jenstrickland I have [a new concept](https://preview.uxpin.com/716fd9c0d105393853b9655f4edd35f11dbca438#/pages/134194336/documentation/no-panels?mode=i) I'd like to get your feedback on. (FYI Jennifer, this does include changes to the desktop version as well - got the OK from Ryan to explore that.)

I included my reasoning behind the choices I made in the documentation on the prototype.  Comments/feedback welcome in the UXPin comments, here, or any other way that works for you.

I have several iterations if you want to see how I landed on this.  The team was hoping to have this completed in this sprint, so if you could please provide feedback as soon as you're able, that'd be great. Thanks in advance!

**Comment by brianalloyd** [comment]
@andaleliz please focus this ticket on creating a mobile home page version for MVP 1.1 as discussed during grooming.  @jenniferlee-dsva reaching out to @rtwell to validate future designs.  Let's move forward with 1.1 home page version in support.

**Comment by andaleliz** [comment]
Per [this Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1605553209254700) w/ additional guidance from Jen, I've created [a mock-up](https://preview.uxpin.com/716fd9c0d105393853b9655f4edd35f11dbca438#/pages/134261285/documentation/no-panels?mode=i) that visualizes the [decisions made on 7/27](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md#072720). There are some notes in the documentation panel on the first screen.

@jenniferlee-dsva what are your thoughts now that you see a visualization? I think this was decided pre-collapsing search on mobile, so not sure if the search box + accordion combo was considered. 

I included [a screen](https://preview.uxpin.com/716fd9c0d105393853b9655f4edd35f11dbca438#/pages/134262012/simulate/sitemap?mode=i) that is the outcome of Ryan and I iterating on each other's designs for your reference. One thing we talked about was un-collapsing search on the homepage only, since that is probably how most people will get started.

I mentioned this, but I'm glad to know we can revisit this down the road. I don't think the topics provide a great UX on mobile as they are.

**Comment by jenniferlee-dsva** [comment]
Hi Liz - The mobile mockup lgtm - https://preview.uxpin.com/716fd9c0d105393853b9655f4edd35f11dbca438#/pages/134261285/documentation/no-panels?mode=i  -- I left a comment, very minor, about the updated H1. 

I really like your `Load 5 more` affordance. Let's incorporate that feature into the ^ 1.1 mobile design - obviously would work only for the topics section. (I take it we're using "load" nomenclature because we're trying to avoid "view/see" language? I might suggest: "Show" -- "load" is okay too but feels a little techie.)

In general, I do like your mobile design updates; BUT as we are right in the throes of continuous releases for 1.1, I don't want us to spin on big design changes, and more importantly, I would really like us to use IRL user data to rethink future iterations.

**Comment by jenniferlee-dsva** [comment]
editing ^

**Comment by andaleliz** [comment]
>I really like your Load 5 more affordance. Let's incorporate that feature into the ^ 1.1 mobile design - obviously would work only for the topics section. (I take it we're using "load" nomenclature because we're trying to avoid "view/see" language? I might suggest: "Show" -- "load" is okay too but feels a little techie.)

Oh glad you're on board with the load more concept @jenniferlee-dsva !  What do you think about starting with 3 topics instead of 5, since the height of each topic box needs to include the 6 links (5 articles + view all)? [Here's how it looks](https://preview.uxpin.com/716fd9c0d105393853b9655f4edd35f11dbca438#/pages/134261285/comment/sitemap)

Yes, language is trying to avoid language that assumes someone can see. IMO `show` still makes that assumption.

**Comment by andaleliz** [comment]
@jenstrickland, what are your thoughts on the yellow fade technique ([code pen example](https://codepen.io/Mestika/pen/KVGwKb)) when a user loads more topics?  A fellow a11y friend suggested this, and I can see the value for sighted users. I don't see a lot of recent writings on this, or a11y articles for a load more functionality, so wanted to check with you.  

I'm thinking a live region ([simple live region docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions#Simple_live_regions)) would be appropriate for assistive tech.

**Comment by jenstrickland** [comment]
Trevor and I discussed the possibility of a fading yellow background for text items that programmatically receive focus, but haven't yet made a decision. I have concerns about this for Veterans with PTSD and TBI. 

The Codepen yellow flash timing is really fast. I have a TBI and it makes my head hurt. 

For load more functionality, @rtwell and I worked through a process for VAOS "Add a provider". When the "Load 5 more" button is selected, then focus moves the first one of the next five. If it is interactive, then it gets a gold focus halo.

**Comment by andaleliz** [comment]
@jenstrickland definitely don't want to make anyones head hurt. Yikes.

>For load more functionality, @rtwell and I worked through a process for VAOS "Add a provider". When the "Load 5 more" button is selected, then focus moves the first one of the next five. If it is interactive, then it gets a gold focus halo.

Sounds good, I'll include guidance along these lines. Thanks!

**Comment by andaleliz** [comment]
@jenniferlee-dsva, are you good w/ showing 3 instead of 5 items? If so, I will go ahead and make the remaining screens before closing this out:
- audience accordion open
- state after `load more` button is clicked first time, w/ guidance on focus

**Comment by jenniferlee-dsva** [comment]
Let's keep to 5 topics on default.

It's not hard to scan, and 3 seems annoyingly skimpy. We're either forcing scanning or clicking 'load more' sooner, and I don't think scanning is that hard and comes naturally.

**Comment by andaleliz** [comment]
Will do.  I'll add the link to the mock-up on the corresponding FE ticket
