### ISSUE TITLE
Contact Center Review for [Profile 2.0]

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#11573]
# Request the Contact Center Review 

## What this form is for
Use this template to request a Contact Center review of your product.

Please review the Self service Product Guide Template [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/self-service-product-guide-template.md) and the Contact Center Review How to [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/contact-center/request-contact-center-review.md)
 

## Description
*Please provide the name(s) of your product and a high level description of your product.*

Name: Profile 2.0
Description: This is a change to the existing VA.gov profile. We are combining the "Profile" and "Account" pages as well as making the UI more effective and easier to scan. We also have included a side navigation menu to make the Profile easier to navigate.

### Launch Date
**[Release Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Profile%202.0%20Release%20Plan.md)**

### Product Guide
**[Product guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Call%20Center/VA%20Profile%20-%20Product%20Guide.docx)**

### Product Video
**[Product Video](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Call%20Center/VA.gov%20Profile%20Product%20Video%20Transcript.docx)**

### Product Video Transcript
**[Product Video Transcript](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Call%20Center/Profile%20Product%20Video%20Transcript.docx)**

## Acceptance Criteria
- [x] Product Guide completed
- [x] Product Video completed
- [x] Release plan completed
- [x] Review meeting scheduled

**Comment by Kimberley2019** [comment]
I have reviewed the document that was sent to me by Matt Shea.  I have also passed the document along to WHVAH for their review and advised that any feedback needs to be received by COB 8/7/2020.

**Comment by mshea0606** [comment]
@Samara-Strauss The product video and product video transcript have been added

**Comment by Kimberley2019** [comment]
@mshea0606 or @Samara-Strauss when I click on the Product Video, it takes me to a 404 page.  Any way to look into this so that I can pass it along to the Contact Center for review?  The transcript is fine, I have to view it raw then it populates as a Word document, which I can easily save and send. It is beneficial if I send them together.

**Comment by mshea0606** [comment]
Hi @Kimberley2019, I just sent you the video via slack. If the file doesn't work or is too big, i can try sending by email. cc @Samara-Strauss

**Comment by mshea0606** [comment]
@Kimberley2019  i've also put the product video transcript into Git Hub [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Combine%20Profile%20and%20Account/Call%20Center/Product%20Video%20Transcript%208-5-20.md) cc @Samara-Strauss

**Comment by Kimberley2019** [comment]
@mshea0606 I just reviewed the video and it's GREAT!  Thank you so much.
I just heard back from the Contact Center, please see their request below.

_Kimberley, since this is an updated guide, could the team that makes these guides highlight what is new within them?  I think this is super important.  Would it be possible to update this guide with those highlighted changes?  Thanks, Todd_

Please let me know if this request is possible.  
I am going to send over the video and transcript now.  This may help a bit and you MAY not have to process the request, but let me get that feedback first.

**Comment by Samara-Strauss** [comment]
@Kimberley2019 most of the guide is new, so highlighting what is different would leave almost the whole guide highlighted. This new guide consolidates a couple old ones — namely the direct deposit guide and the address validation guide — and adds a bunch of content to explain the rest of the profile and account settings features that we had not previously made guides for. For the content that is getting replaced, most of that is the same, but all the visuals are different since the profile has been overhauled entirely. I would recommend the call center discards the old guides for address validation and direct deposit and uses this new profile guide as the source of truth.

**Comment by Kimberley2019** [comment]
@Samara-Strauss @mshea0606 I have informed the Contact Center of this.  Hopefully they will be receptive to the advice that has been provided.  I will advise if there is any additional feedback that is given.

**Comment by Samara-Strauss** [comment]
@Kimberley2019 any updates here? We are wondering if we can close this out or if you need anything else from us.

**Comment by Kimberley2019** [comment]
@Samara-Strauss I have not received any more feedback concerning this particular guide.  I would like to confirm with them this Friday during our call. I can close this out if there is nothing additional.

**Comment by Samara-Strauss** [comment]
Great, thank you for the update @Kimberley2019! I appreciate it. Let us know if anything comes up in tomorrow's meeting.

**Comment by Kimberley2019** [comment]
Will do @Samara-Strauss

**Comment by Kimberley2019** [comment]
@Samara-Strauss @mshea0606 During our call with WHVAH on Friday 8/14/2020, there were no additional questions or feedback concerning this product guide.  This ticket can be closed.
