### ISSUE TITLE
VFS Support: Review CMS editorial and IA workflow

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#116]
@mnorthuis  - We are missing the current state of how IA is created/updated in Github today. Could you provide that either in Word doc or here in comments? Once I have that, I'll add it to the deck, and sync with the CMS team on what capabilities they currently have to support it -- and add that to the process deck. 

@ everyone else - please take a look and offer any corrections or feedback. I made updates per our weekly sync -- on slides #18 and 19. 

[CMS-editorial-workflow-tier-1-benefits-052919.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3234316/CMS-editorial-workflow-tier-1-benefits-052919.pdf)

**Comment by bethpotts** [comment]
@jenniferlee-dsva here are my knitpicky suggestions! I love process docs... and these are all small polishing edits, so take 'em or leave 'em as you wish.

**SLIDE 18 (bolded text is just to show suggested edits):** 
1. Change "and" to "or": VHA, VBA, **or** NCA digital team makes the update directly in Drupal.* (INSIDE)

2. (no changes to suggest here)

3. I would get rid of the sub-bullet and just line this up on the left margin, like this:
If the content team makes the change in Drupal, the content person will: 
- Email the SME/requestor the preview URL to review, and 
- CC the relevant VHA/VBA/NCA digital point person. (OUTSIDE)

4. Move location of "repeat": If needed, **repeat** steps 3 – 4.

5. Change "and" to "or": Randi or Peggy emails SME and VHA, VBA, **or** NCA digital team that the update has been pushed into deployment queue. (OUTSIDE)

6. I'd delete "Current state." I think it's obvious enough that what you say above is the current state.

**SLIDE 19:**

Cap "benefits" to start the list of examples at the top of the page. I'd also add to the examples something about a new page, like: "a new page that addresses a new program, service, or benefit"

1. Change "and" to "or": Business contacts the VHA, VBA, **or** NCA digital team directly.
2. Lowercase "OR": Web content team makes the update **or** creates the new content in Drupal. (INSIDE)
3. Add "s" to "CC": Web content team saves as “Draft” (INSIDE); emails SME a preview link and **CCs** VHA/VBA/NCA digital team for awareness. (OUTSIDE)
4. Delete "via meeting": SME reviews the preview page; provides feedback to the content person—either via email (if simple) or **a call** (if complex). (OUTSIDE)
5. I think the second parentheses should have "INSIDE" rather than "OUTSIDE" right?: Content person changes state in Drupal to “In Review” (INSIDE), and emails Randi Hecht and Peggy Gannon to proofread. **(OUTSIDE)**
6. (no changes)
7. (no changes)
8. Remove the comma after "SME": Content person emails **SME and** the relevant VHA/VBA/NCA digital team a final preview URL prior to changing state to “publish.” (OUTSIDE)

**Comment by mnorthuis** [comment]
@jenniferlee-dsva I don't do the updates in GH today, so I'm probably not the best to provide the how.  @bethpotts may be  better equipped to flush out the current process.

**Comment by jenniferlee-dsva** [comment]
@mnorthuis - How do you create new IA today for webpages and update existing IA? I guess it doesn't matter where it happens. Just want to document out how that happens today. I know there have been a few different Slack threads about how that happens but it would be helpful to have it in one place, and I can combine it with the new Drupal process in the same deck. 

@bethpotts - Thanks for your feedback! I made them all except the one about "new page addressing benefit, service or program." I just added the "new page for a benefit" example -- left off the service/program. Don't want to confuse stakeholders, as I think they think of many things, including administrative office/about us info, as a service or a program.

**Comment by mnorthuis** [comment]
@jenniferlee-dsva The IA is designed/determined/documented in the visual sitemap in Moqups and in the Master URL Mapping spreadsheet.  Many times writing has already began, so once IA and URLs are finalized, the pages in GH are updated with revised URLs as needed.  Separate tickets are often then created for updates to the top nav and left nav as needed.

**Comment by jenniferlee-dsva** [comment]
@mnorthuis Thanks for that detail. That helps. Could you send me a screenshot to the visual sitemap - just something I can include on a slide in the deck for stakeholders? 

And also - you mentioned that often the writing has already started and that sometimes pages are even already created before IA and URLs are determined. In an ideal world, what would you LIKE for the steps/process to be?

**Comment by jenniferlee-dsva** [comment]
Following up: @mnorthuis could you upload a screenshot of your IA/sitemap here?

**Comment by mnorthuis** [comment]
@jenniferlee-dsva there is a site map for each hub, do you want a screenshot of every hub or else here's the link: https://app.moqups.com/Rnc4BDEKrA/view/page/a4dc7a719
