### ISSUE TITLE
Update "vetsgov" to "vagov" on internal tools doc

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#11653]
### What is your documentation request, question, comment, or issue?
The historical website `vets.gov` has been deprecated in favor of `va.gov` however some docs still use `vetsgov` terminology: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/internal-tools.md

This document should be updated to use the current terminology.

Note: if this depends on technical changes those may need to be spun off

**Comment by gmaciolek** [comment]
This is a known issue that for now, we are leaving up to individual practice area groups to address within their own docs. 

If there are specific, high priority docs with outdated info, we would certainly prioritize updating those sooner rather than later, but we don't have the bandwidth right now to audit all of our docs for these updates.

That said, I think the internal tools doc may be getting an update soonish. The backend tools team is auditing their docs right now and I'm sure this is something they will be paying attention to at as they make updates.

Flagging a few people for awareness on this: @alexpappasoddball @thilton-oddball

**Comment by alexpappasoddball** [comment]
To be transparent, we won't be making changes to the actual documentation that don't directly belong to our team (BE Tools).  This document is owned by Ops @ricetj and I'll defer to him for updates!

**Comment by ricetj** [comment]
Hello, This is in connection with our issue around improving SOCKS documentation. https://github.com/department-of-veterans-affairs/va.gov-team/issues/11443. Additionally, some of these changes refer to technical implementation or valuables that would also need to be changed before we could update the documentation.

**Comment by mchelen-gov** [comment]
@gmaciolek that makes sense. it seems like some of these docs & tools cross team boundaries, so maybe we can figure out what steps & coordination would be involved long-term?

**Comment by jbritt1** [comment]
All `vetsgov` entries updated to `vagov` and removal of all `vetsgov-internal` domain references removed in #11950. Please use #11443 for further tracking, feedback, suggestions, etc. for consolidation.
