### ISSUE TITLE
[Design] Blue Sky Product Health Tool Iteration

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1171]
## User Story
As a Insights team member and stakeholder, I need to understand what the Product Health Tool will look like so I can prioritize the data that will be needed and run through platforms that the tool can live on.

## Goal
Continue iteration of the 'paper draft' of the product health tool.

## Acceptance Criteria
- [x] Insights team meeting to go over first draft
- [x] Amy: Meet with DSVA to go over thoughts
- [x] Meet with Emily to align on Research plan

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by amycesal** [comment]
### Note from meeting with Insights and Analytics team:
- On the trend charts, would be great to see “milestones” (product launches, comms campaigns, redirects from eBenefits, etc) so you can get a sense of whether they may have impacted the outcomes trajectory
- What if we had a chart that showed 3 lines on it: processing times, call center volume, and user sentiment? That would be really telling. Essentially, lumping some of the data together too to test correlative or causal relationships in the data
- ROI -> did the strategic decision help to alter metrics
- KPIs, leadership looking for specific metrics (OKRs and bets) 
- give metrics more context (pivot table to change the metrics)
- PA&I data (how do online forms compare to offline data) (once a month or once a quarter)
- time to receive benefits
- are veterans getting their benefits, and is the process better with the website
- call center data comparison (CSAT)
- Call center: how many cases are tier 1 vs 2
- Forsee “other” word cloud
- time per page
- number of sessions
- heatmap of session recording
- segment out logged in vs logged out users
- bounce rate of hub pages where form is housed
- link to KPI workshop
- text field for goal
- Average number of minutes to complete the form

**Comment by amycesal** [comment]
Adding the notes from @rroueche 

- Like the description context to link thought back to desired outcomes of the product in question
- Like the current "time to complete" and number of clicks, would be good to add "avg time to receipt of benefit" and compare all that to paper version of form
- Like orienting ppl to the fact that the experience starts before the actual "product" - could we add data around this? entry points? common nav paths? common search terms?
- Like milestones on the overall tracking, but don't think it should just be submissions on that chart. - What about a chart showing multiple lines representing different things (VA processing time, call center volume, downtime, abandonment, etc), and w/milestones on it? And the milestones IMO shouldn't be just specific to the product in question, but about VA.gov overall - so like "Login enhancements launched" "VA press release about VA.gov" etc.
- Just 1990 isn't how ppl get edu benefits, there are like 5 different forms just for this. How can we roll this stuff up to show Education overall?
- Failed submissions past 30 days not useful bc no context. Is that number good? bad? normal? In general, how can we be more opinionated w/the data?
- Like days w/downtime chart and the dependent systems downtime!!
- 263 min of downtime (would like to see as compared to private sector best practice, and as compared to general avg across VA.gov)
- Calls in past 24 hrs, not useful w/o being able to see over time. Is the # of calls a spike? rather low? a high number, but it's always high compared to other products or as a % of usage volume, so that in and of itself is a problem?
- Instead of quotes, could we include sentiment analysis from submitted user feedback? (knowing we don't have a mechanism for user feedback today aside from Foresee, so this is truly blue sky)
- Need to be showing more "outcomes" data - VA processing times, and time to receipt of benefits

**Comment by amycesal** [comment]
Trying a version of the "mega-chart" from the conversation with @rroueche and @leahbannon 
- I normalized the data by using a target for each metric and visualizing if the data was above or below that target by percentage. 
- The graphs below dig a bit deeper into each ling and, for the most part, give a point of comparison as well as what the target is and actual numbers. 

Interactivity and some sort of hover would help readability of the mega-chart, but I don't know if it gives you the big picture, easy takeaway visual you were looking for. 

![Blue-er_Sky](https://user-images.githubusercontent.com/1656046/63973843-9f102600-ca79-11e9-88f9-3efebf1897cc.png)

**Comment by joanneesteban** [comment]
An additional note for our product health tool:
VSP's goal is to `Establish what “sub-par” means, for this KR: Any VA.gov product w/sub-par health metrics is on the VA.gov roadmap for iteration (note: VSP is not wholly responsible for meeting this KR bc it’s up to DSVA to do something w/the information - like have a VA.gov roadmap  - but still believes it’s important to track)`

One of our objectives for our Product Health tool is for the tool to be automatically opinionated and to establish concept of having a standard baseline above/below which products are considered stable/at risk.

**Comment by joanneesteban** [comment]
@amycesal Can we close out? Can you add the additions that were mentioned above:

- Instead of quotes, could we include sentiment analysis from submitted user feedback? (knowing we don't have a mechanism for user feedback today aside from Foresee, so this is truly blue sky)
- Need to be showing more "outcomes" data - VA processing times, and time to receipt of benefits
- Failed submissions past 30 days - add context. Is that number good? bad? normal? In general, how can we be more opinionated w/the data?
- Just 1990 isn't how ppl get edu benefits, there are like 5 different forms just for this. How can we roll this stuff up to show Education overall?
- Calls in past 24 hrs - add ability to see over time. Is the # of calls a spike? rather low? a high number, but it's always high compared to other products or as a % of usage volume, so that in and of itself is a problem?

**Comment by joanneesteban** [comment]
@amycesal Also, can you add your notes from your meeting with Emily?

**Comment by amycesal** [comment]
- research template: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Research/research_plan_template.md
- We are going to do research on Grey Sky with stakeholders after:
  - we figure out goals from stakeholders
  - we figure out grey sky with date holders

**Comment by amycesal** [comment]
### Updated Blue Sky

![BlueSky_01](https://user-images.githubusercontent.com/1656046/64276177-e7fa2b80-cf0c-11e9-879e-47055583688d.png)

### Blue-er Sky
![Blue-er_Sky](https://user-images.githubusercontent.com/1656046/64276215-ff391900-cf0c-11e9-84c5-df1ced419a6d.png)

**Comment by nedierecel** [comment]
@amycesal A few observations for Blue (and Bluer) Sky:

1. Users - We occasionally get asked to provide "# of users" on the product. This could be a new metric to add.
2. Forsee - Within the other trendlines, the historical data is on the left, but in this reportlet it is on the right. 
![image](https://user-images.githubusercontent.com/24525739/64283958-7dee8000-cf26-11e9-9bf0-d86eb4258275.png)
3. Bounce Rate - Bounce rate may be less of an indicator of success. I know it's an easy one to measure to see how introductory content is performing, but I don't feel like it's as important as the other metrics listed.
