### ISSUE TITLE
Support VFS team with EVSS test users

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#11823]
### Background

Original request found [here](https://dsva.slack.com/archives/CU9KYKMM5/p1594832120062800)

> Hello, I need functional test user data to test-out form 22-10203, I need 1 user+ID.me account with all prefill data and > 6 months of benefit remaining and 1 user+ID.me account with all prefill data and < 6 months of benefit remaining . Both accounts with recent enrollment information. Thank you

- See this [Slack thread](https://dsva.slack.com/archives/CU9KYKMM5/p1594937728079000) for more details

We've been helping to identify and access users for testing in staging.va.gov and encountering various obstacles along the way. 

This ticket is to track the work done as support, for future reference.

**Comment by pjhill** [comment]
@jholton Here's a quick summary --
**Who**: The BAH team is working on a product that needs to make a determination about a Veteran's remaining GI Bill entitlements. 

**What:** They want to make the determination as part of a multi-page application that starts here -- https://staging.va.gov/education/how-to-apply/. They need to retrieve the Veteran's `remainingEntitlement`.

**Doing what:** The team will use the `remainingEntitlement` value to either display an alert informing the Veteran that they are not eligible for a specific benefit because they have greater than 6 months of `remainingEntitlement`.
![Screen Shot 2020-07-15 at 3 13 18 PM](https://user-images.githubusercontent.com/52456633/88844792-3bbed480-d1b1-11ea-8bca-54d13617b954.png)

**Comment by kfrz** [comment]
aws ssm start-session --target i-0d9559b344f7d57a3

Staging test accounts ()[https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-gibill.md]

#<EVSS::GiBillStatus::GiBillStatusResponse:0x000056424e3f9e68 @timeout=false, @response=#<OpenStruct status=500, body={"chapter33_education_info"=>nil, "messages"=>[{"key"=>"education.chapter33claimant.partner.service.down", "severity"=>"FATAL", "text"=>"Chapter33 Claimant partner service error"}]}>, @content_type="application/json", @status=500>

**Comment by kfrz** [comment]
**2020-08-27**

- @thilton-oddball and I met w/ Mike Fraysher today and walked through some more examples
- Mike was able to insert data into the LTS database
- We were able to curl the LTS service directly and recieved a 200 + XML response
- Maybe we will be able to try the SOAP project to test
- All responses are the same, even for existing test users

**Next steps:**

We are going to collect the user data we know to be in MPI, and have Mike update the LTS database to include these users. 

We are going to schedule another meeting with:
- EVSS - Mahesh Raparthi
- LTS - Mike Fraysher
- IAM - Thomas Sapp (?) or someone at Datapower
- VSP - Keifer & Travis
- OIT - Boris Ning (?) or someone who can help us trace packet traversal

On this next call we aim to validate the request path by capturing network data. We will also be prepared to provide First, Last, email, SSN, DOB for given users. 

We should likely look at our mock data and go from that list. Might need some further support from others on the platform, or maybe the BAM teams (@annaswims)

**Comment by annaswims** [comment]
I don't think the `csraciapp6.evss.srarad.com` domain exists anymore.  My understanding is that it  was a domain from a former contract.  I think you would want pint.ebenefits.va.gov or int.ebenefits.va.gov

**Comment by annaswims** [comment]
I did some work to find EVSS staging user for claims a few weeks ago.  I was looking for users with an EDIPI, BIRLS ID and Participant id in MVI and not more than one ICN (so that they weren't blocked by SSOe). 

https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users-birls-participant-edipi.csv

It's essentially a filtered list of the [staging users csv](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv), joined with some data from MVI

**Comment by kfrz** [comment]
**2020-09-16**

Meeting Notes

- PINT CH33 service is down at start of meeting
- This happens a lot, according to the EVSS team
- Returns 500 errors regardless, which makes it nigh impossible to code/capture
- Manual entry Ch33 (IVV3) data is scorched on deployments - should only get updated after each prod release
- This is owned by ISQA - which could deploy at will - but quarterly is the expected cadence
- We *did* get IAM to see user: `Glen Mitchell, vets.gov.user+53@gmail.com, 796127777`
- And user `Kyle Cole` 
- The 500 is coming from Ch33 webservice
- Mike Walker joins us to explain why this doesn't work and what we need to do to make it work_
	- When EVSS hits the IAM service (`sqa.services.eauth.va.gov:9304/ch33/dti/claimaint`) there's a backend error 
	- Pulled in Timi Elvuchio from IAM to help debug that part
- Fred creating a user that exists in MVI via IAM so we can at least get one user
