### ISSUE TITLE
Handle Express Care request limit

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#11978]
We're currently not doing the request limit check for Express Care requests. We need to figure out where this check should be surfaced.

**Comment by jbalboni** [comment]
@rtwell Can you help figure out where we should tell someone that they're at the request limit for EC? I think the max is usually/always 2 requests.

**Comment by narin** [comment]
I can start work on code the limit check, but we'll need some guidance on where to put it.

@rtwell To add some additional context, we have to either perform a separate API call on each facility to see if the user has reached the limit **or** fetch the express care requests and compare it against that.  

With this in mind, I think we might want to avoid displaying this messaging on the homepage to cut down on unnecessary API calls.  The other two options I see are doing it on load of the Express Care Info page, or performing the check upon submission.

FYI this is the request limit copy we show for regular requests if the user has reached the limit:

![image](https://user-images.githubusercontent.com/786704/89445692-5a205500-d708-11ea-98a1-73422907e8c0.png)

**Comment by rtwell** [comment]
a couple thoughts/notes:

1. first, I suspect it would behoove us to always refer to appointments the same way (in the app, in review, in alerts, statuses, etc). On our request cards, we refer to them as "Pending", so we should align our language in this alert to be consistent. For example, "Go to your appointments list and cancel open requests" should read "Go to your appointments list and cancel _pending appointments_" cc @peggygannon 

2. given a user is registered at 2 facilities which _also_ have EC enabled _and_ **both are available at this moment,** it might look like this:

![image](https://user-images.githubusercontent.com/12564977/89593463-3c90df80-d81d-11ea-867e-d76eb2531dfe.png)

3. given a user is registered at 2 facilities which _also_ have EC enabled _but_ **only one facility is available right now,** it might look like this:

![image](https://user-images.githubusercontent.com/12564977/89594266-5a5f4400-d81f-11ea-9715-5327fb67e396.png)


**Note:** stating that EC is "available" vs "open" when 2 facilities are present can easily become confusing. Additionally, listing the hours of EC availability doesn't also necessarily help because of the time zones (e.g. time zone A = 1–5 pm, time zone B is also 1–5 pm,). The onus is on the user to figure out which time zone applies to them _right now_. We could consider detecting their current time zone via browser. We could also consider always hiding unavailable express care…but that wades into the territory of showing users some options some of the time, and other options at other times.

**Comment by rtwell** [comment]
one approach might be to list the availability of each location with the same time zone, and add another affordance to indicate what is currently open/closed:

![image](https://user-images.githubusercontent.com/12564977/89597713-df9b2680-d828-11ea-8440-98c51d95d0c7.png)

**Comment by rtwell** [comment]
interesting tidbits here: https://www.nngroup.com/articles/international-web-usability/

**Comment by narin** [comment]
Hey @rtwell, this mockup looks good. In regards to the request limit check, I think we should perform the check once the user selects a radio button (similar to how we do it in the normal appointment flow).  Checking request limits has to be done one by one, so to reduce these unnecessary API calls, ideally we should only do it once the user has shown intent that they want to schedule there.

**Comment by narin** [comment]
Copying description over from dupe ticket:

> If a Veteran has too many open requests for Express Care concurrently, they need to be prompted with an alert that they have reached their limit for express care requests.
> 
> ## Acceptance criteria:
> * [ ]  request care limit check happens when Veteran clicks "Continue express care request" on the How express care works
> * [ ]  if veteran has reached limit they are how the 'request limit' alert

**Comment by peggygannon** [comment]
Hi, @narin @rtwell. Please use this content for the EC limit message: 

**You've reached the limit for Express Care requests**
Our records show that you have an open Express Care appointment at this location. We can't accept any more Express Care requests until your pending appointment is scheduled or canceled.  To cancel a pending Express Care appointment, go to [your appointment list](/schedule-view-va-appointments/). 

please delete the 2nd bullet point "Call your medical facility" as we don't need it for the EC limit message.

**Comment by narin** [comment]
Thanks @peggygannon.  There is one more unlikely, but possible scenario where the request limit check might fail and they should not be able to continue.  Do we have a generic error message we might want to display? I was thinking something similar to the error message for a failed request:

**Error**
Something went wrong when we tried to check your request eligibility. We suggest you wait a day to try again or you can call your medical center to help with your request.

**Comment by peggygannon** [comment]
hi, @narin Yes,  here's our generic message for a scenario like this. 

**We've run into a problem**
Something went wrong when we tried to check your request eligibility. We suggest you wait a day to try again, or you can call your medical center to help with this request.
