### ISSUE TITLE
Add reverseFieldOffice to fieldOffice in node-health_services_listing

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#12069]
## Issue Description
The `fieldOffice` field on `node-health_services_listing` needs data from the published `regional_health_care_service_des`s in `reverse_field_region` (or something). The GraphQL sub-query can be found [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/graphql/healthServicesListingPage.graphql.js#L35).

---
## Tasks
- [ ] Add the `reverseFieldRegionPageNode` to the `node-health_services_listing` on the `fieldOffice` field

## Acceptance Criteria

- [ ] The health services listing section of`pittsburgh-health-care/health-services/index.html` has no significant diffs when built using cms-export vs. graphql

Other diffs on this page will be covered by additional tickets.

**Comment by cvalarida** [comment]
Marking as blocked until we get the `reverse_field_region` (or something) field in the CMS export.

**Comment by mpelzsherman** [comment]
Bumping this up to an 8 based on my experience so far.

**Comment by mpelzsherman** [comment]
The issue here is that the items in the list of Health services have no content:

![Health_services___Veterans_Affairs](https://user-images.githubusercontent.com/80267/97064883-81542900-1577-11eb-82a1-be093c2f096d.png)

So we need to find a way to populate that Health services data.

That content is expected to live in `fieldOffice.entity.reverseFieldRegionPageNode.entities`, based on this code in [pipeDrupalPagesIntoMetalsmith](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/metalsmith-drupal.js#L101-L104).

**Comment by mpelzsherman** [comment]
As @cvalarida pointed out back in August, it looks like there is some data missing from the cms export.

I grepped through all of the files and `reverse_field_region_page` is always empty.

I don't know how to debug this so I'm marking this as "blocked" until I can get some help.

**Comment by mpelzsherman** [comment]
Removing block now that @theodur is on the case!

**Comment by mpelzsherman** [comment]
Fixed by https://github.com/department-of-veterans-affairs/vets-website/issues/14752
