### ISSUE TITLE
'Presumptive Herbicide' should not be a valid production condition name / classification code

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1206]
@markgreenburg commented on [Fri Jul 19 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/19331)

Prod error: ` form526.disabilities[23].classificationCode.isInvalidValue / “The classification code for a claimants primary disability is not a valid value”

Triggering condition: `109: '2010 Presumptive Herbicide Condition',`

## AC
- [ ] `disabilityLabels.js` should not include entry key `109` / value `'2010 Presumptive Herbicide Condition', because BGS does not recognize this value in production.

**Comment by ndsprinkle** [comment]
@YanaRoy Am I okay to pull this onto the current sprint? This relates heavily to the contentions list story I currently have in review and may even alter my code because I actually added "109: '2010 Presumptive Herbicide Condition'" with my changes, so I'll need to do some research and testing to see if I am actually supposed to add this or not. This contention was in the excel document that Mark provided, so I would think it should be added.

**Comment by YanaRoy** [comment]
@ndsprinkle Yes. :) I appreciate the heads up, but I don't think you need to ask me to do it if it's in favor of work you are currently working on.

**Comment by ndsprinkle** [comment]
A commit that addresses this issues was pushed into this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/10731
