### ISSUE TITLE
[Discovery] - Topline Summary for Learning Center MVP

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12164]
Use [this template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/topline-summary-template.md) to create a topline summary for research findings immediately following last session

Acceptance criteria
- [x] Create summary ([published in research folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/topline-summary.md))
- [x] Share with team (Jen, Mickin, Kelson, Nick, Mikki, Oksana, Meg and Beth)
- [x] Capture team feedback

**Comment by mpeterz** [comment]
*Recommend testing this concept with these scenarios to ensure we get realistic feedback:*
* Veteran comes straight from Google to LC article page
* Veteran goes from VA.gov homepage to LC homepage 
* Veteran searches VA.gov and lands on LC article page

*Also, we need more mobile testing.* 
I think we only had 1 mobile participant (Android). 

*RE: promoting LCs:* 
I heard 2 people say the VA should promote LCs. 

*Under the first hypothesis, what is the rest of this sentence?*
“Everyone understood that the search functionality was keyword based and were clear that the Learning Center”

*Observation:* 
Because most people would search for benefit info in LC, there will be a lot of “pogo-sticking” — extra clicking to get to benefit info in the hubs. And many participants said they want as few clicks as possible. 

Still reading through the findings and my notes...

**Comment by andaleliz** [comment]
@mpeterz 
>Under the first hypothesis, what is the rest of this sentence?
“Everyone understood that the search functionality was keyword based and were clear that the Learning Center”

completed my sentence. Sorry about that, and thanks for catching it!

>Everyone understood that the search functionality was keyword based and was clear that the Learning Center radio option would search within the learning center.
About half of the participants were unsure about what the search VA.gov radio button would do.

**Comment by andaleliz** [comment]
Adding feedback from Slack comment by @sshein so it's all in one place:

Thanks Liz! A few things.

For this "How easily are people able to navigate between learning center articles, and topics?" I would be interested to have your final results dig into how people navigated / e.g. did everyone use the browser back button

I only watched 1 participant (P10) but a few things I noticed: 
- he thought the "about" tag would be useless and didn't like it; 
- his point that he thought "Learning center" would be about how to use the site was a good one, I know you have it in the topline but I think might be worth folks ruminating on; 
- he primarily would use search and felt overwhelmed by all the links on the page

**Comment by bethpottsVADEPO** [comment]
**One piece of feedback that stood out to me about the labels, specifically the audience tag:** 
One participant said, "Vietnam War Veterans doesn’t look clickable. Everything else that you click is blue. Why not do the same for this?" Another said something to the effect of, "I guess people will eventually figure out that they can click on these." (as if it isn't immediately obvious)

**Seems like there's a need to define or explain a couple terms/words, so I'll capture them here:**
- We need to define "fiduciary" so it's clear who that's for (not for the sake of the fiduciaries, but for the non-fiduciaries, so they know it's not for them!)
- One participant misinterpreted “Sign in FAQs” as meaning he could sign in to find more FAQs about account and profile. He didn't understand that this was an FAQ about how to sign in. Suggest changing to “FAQs about how to sign in" or something like that.
- Learning Center: If we go with this name, we'll need to explain somewhere/somehow what type of content the user can expect to find in this area. There was some confusion about that. Some participants expected to find benefit info here too.
