### ISSUE TITLE
Batch 2: Publish Find VA Form detail pages

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#12213]
## Issue Description
Given we need to publish the Find VA Form detail pages via Drupal
we want to publish them in batches
so that we safely launch the detail pages. 

---
## Tasks
- [x] Publish the pages via Drupal

## Acceptance Criteria
- Form detail pages are safely launched
 - Publish batch 1: Top 30-40 identified MVP form pages.
- Publish batch 2: Remaining ~450 form pages.

**Batch 2 forms spreadsheet can be found here:**
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/form-detail-landing-pages/final-docs#content-for-the-other-400-forms

**Dependency:**
Because of transformer and processing memory dependency, we will have the pages ready in Draft CMS state and check memory/transformer situation before publishing. (We may need to publish batches as separate tickets.)

**Note:** may be able to soft launch without having redirects completed first to at least verify results to detail page transition. In that case, we can remove the blocker on this ticket (see Detail Page Release Plan ticket for further details #11311)

**Comment by MickinSahni** [comment]
@jenniferlee-dsva to add forms here (csv, etc.)

**Comment by jenniferlee-dsva** [comment]
Added link to the spreadsheet with the 400ish forms ^ ; and clarified one of the ACs. 

@lunascoop  and @RLHecht  - I'm not sure what the easiest/best way to batch publish these 400ish forms are. As you have reviewed these forms previously and changed their state to "In Review," that might be the only way to filter for these forms in order to publish then as a batch. 

_Note: There have been additional forms that form managers have added to the VA forms DB since we reviewed the 400 form pages in the spreadsheet. We will NOT publish those form pages with this mvp launch, and will handle those as net new form pages post-mvp._ 

If there are any `NON-VA `forms in the list of the 400ish batch 2 forms - please omit them from the batch publish. You may need to filter out these SF forms separately prior to batch publishing. ([Related slack thread here](https://dsva.slack.com/archives/CUB5X5MGF/p1599691495072600).)

**Comment by jenniferlee-dsva** [comment]
[Edited ^](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12213#issuecomment-689864248) - some non-VA forms will have OF in them, so SF and OF forms.

**Comment by lunascoop** [comment]
VA forms that were in an _In review_ state are scheduled to be published later today (386 total). I filtered out **SF**, **OF** and **GSA**-related forms. I noticed some VA forms in a Draft state. I assume they are the ones that were just added by form managers.

**Comment by jenniferlee-dsva** [comment]
>I noticed some VA forms in a Draft state. I assume they are the ones that were just added by form managers.

confirming yes. we will not publish these as part of batch 2.  we'll review and publish them separately as part of post-launch. thank you @lunascoop !

**Comment by lunascoop** [comment]
These pages are live w/authentication. Don't know if we want to change the URL names for the URLs listed below since we are unable to change the Form titles for the 400+ forms.

- https://va.gov/find-forms/about-form-21p-0512s-1spanish/
- https://va.gov/find-forms/about-form-21p-0517-1spanish/ 
- https://va.gov/find-forms/about-form-21p-0519s-1spanish/ 
- https://va.gov/find-forms/about-form-5655blank/
- https://va.gov/find-forms/about-form-21p-0516-1-spanish/ 
- https://va.gov/find-forms/about-form-21p-0514-1spanish/
- https://va.gov/find-forms/about-form-21p-0510spanish/ 
- https://va.gov/find-forms/about-form-21p-0518-1spanish/
- https://va.gov/find-forms/about-form-21p-0519c-1spanish/
- https://va.gov/find-forms/about-form-21p-0513-1spanish/

**Comment by jenniferlee-dsva** [comment]
@lunascoop - re above: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12213#issuecomment-696970980

Yes, I think we do want to update the URLs of those detail pages so that they follow Mikki's URL schema. Can you open a new ticket to capture that work and loop in @mnorthuis there?

**Comment by jenniferlee-dsva** [comment]
This 5655blank form appears to be a duplicate of another 5655 form: 

https://va.gov/find-forms/about-form-5655blank/

https://www.va.gov/vaforms/va/pdf/VA5655.pdf

I will ask the form stakeholders to remove the "5665blank" file, so we can remove that one from your above list. (Thank you for catching it - crazy.)
