### ISSUE TITLE
Analytics Reporting Request for Screener Team - Addition to COVID Dashboard

### ISSUE THREAD

**Issue by jonwehausen** [department-of-veterans-affairs/va.gov-team#12274]
# Metrics Reporting Request

## Description 
How might we incorporate components from [our GA Screening Tool](https://analytics.google.com/analytics/web/#/dashboard/qHm9KfILQnmYWnUVDycH0w/a50123418w177519031p184624291/_u.date00=20200601&_u.date01=20200810/) dashboard into our current COVID-19 VA.gov response dashboard. 

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- Patrick Bateman

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

    _this adds context for the data_
    - VA CTO Health Products Team who is working on the [VA.gov COVID-19 Screening Tool](https://staging.va.gov/covid19screen)
    
## Timeframe for Analytics Requested
Non-urgent. Next week or two would be nice.

## Analytics to Track Down
- [x] Total number of completed screens
- [x] Total number of completed screens, by metro area (top 10 or 25)
- [x] Total number of completed screens, by outcome ("Pass" or "More screening needed")
- [x] Total number of metro areas with >=1000 completed screens in last week

## Acceptance Criteria
- [ ] Determine which metrics we would like to expose from the GA dashboard in our COVID-19 response dashboard
- [ ] Configure connection and construct query
- [x] Create visualization and add to dashboard
- [ ] QA for accuracy

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@bmcgrady-ep As part of your auditing/QA of the COVID dashboard Could you take a look at the description above and perform the following tasks. We will want to have this done prior to our export for Lauren/Chante next week: 
- [ ] Configure the GA connector to pull in this data. See [this as a starting point](https://va-gov.domo.com/datasources/6b31f414-d723-45af-8b92-0ebe18527d95/details/overview)
- [ ] Create mockup chart against your data sources
- [ ] QA for accuracy and have Amy integrate with the current dashboard

**Comment by jonwehausen** [comment]
Pivoted to taking care of this request personally. 

Configured single [BQ dataset](https://va-gov.domo.com/datasources/fab61f8d-5f95-44ea-bdda-59aacf012439/details/overview) to house this data by date and geographic location. 

@amycesal Mockup charts have been added to the bottom of the dashboard ready to work your magic

@bmcgrady-ep could I just have you briefly QA the charts for accuracy?

**Comment by jonwehausen** [comment]
@amycesal Created a [temporary dashboard](https://va-gov.domo.com/page/18680411) to house the screener tool charts to merge-in to the COVID dashboard -- ready for your visualization review.

**Comment by joanneesteban** [comment]
## Dashboard Release Checklist

**GA Reporting Specialist:**
  - [ ] For user/session based metrics, create shared GA segment
  - [ ] Stable automated connection to data source, BigQuery where possible
  - [ ] Data is structured in a convenient way to meet the metric with little manual effort
  - [ ] QA data sources to ensure data accuracy & cleanliness
  - [ ] Non line graphs have date ranges (dynamic text boxes)
  - [ ] Cross-team: work with designer to ensure the data is explained
  - [ ] Cross-team: work with designer to ensure each "card" has a data source that is clearly linked & that the link works

**Designer:**

  - [ ] Content is not "too long" so that export is possible
  - [ ] All graphs are logically grouped in layouts so exporting works and feels logical
  - [ ] Each graph and table has appropriate titles & labels
  - [ ] Each graph has appropriate date ranges
  - [ ] Set goal lines
  - [ ] Cross-team: work with GA Reporting Specialist to ensure that data is explained ([metric definitions reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/google-analytics-cheat-sheet.md))
  - [ ] Cross-team: work with GA Reporting Specialist to ensure each "card" has a data source that is clearly linked & that the link works

**Contact Center Lead:**

  - [ ] Ensure accuracy of contact center data
  - [ ] Contact center data has appropriate dimensions, descriptions, and sources

**Product Manager:**

  - [ ] Groom descriptions for grammar, date ranges, & accuracy
  - [ ] Groom titles for grammar, date ranges, & accuracy
  - [ ] Groom notes for grammar, date ranges, & accuracy
  - [ ] Groom dashboard and charts for flow & usability
  - [ ] Schedule onboarding with VFS PM/PO/Stakeholder

**Comment by joanneesteban** [comment]
## Feedback Notes
(Mostly around visualization)
- [ ] Edit dashboard title (Are these Screener Tool KPIs? Or discovery metrics?)
- [ ] Add dashboard description/objective (looking for the objective of this request; it seems like it might be around, "How might we improve the Screening Tool completions by metro area")
- [ ] Edit titles (remove BQ; by "x" is inconsistent)
- [ ] Date ranges: should these be daily, weekly, monthly?
- [ ] Goals: Are there user goals for completions? 
- [ ] Area charts might be better closer together. Thoughts? 
- [ ] Is there another way to visualize the first chart? I have a difficult time distinguishing the outcomes
- [ ] Add GA source links


@jonwehausen @amycesal

**Comment by joanneesteban** [comment]
Updated dashboard description: Something around "increase physical distancing and veteran safety by reducing lines for screening and make the screening process easier and faster for veterans and facilities."

Thanks for putting this together, Jon!

**Comment by joanneesteban** [comment]
^Actually, in that case, do we have metrics around time to complete and page load time?

**Comment by jonwehausen** [comment]
## Updates / Next Steps
- Met with Amy on the labeling components of the screener tool 
- Still working through a time to complete query (time between `-start` and `-result-displayed` events.
- Once we have a usable time to complete query drafted we can create the final chart and close

**Comment by joanneesteban** [comment]
Do the `Number of Completed Screens (pass and fail)` charts mean tests and both passed _and_ failed?

**Comment by amycesal** [comment]
@joanneesteban yes. Completed Screens = Pass and Fail. Thoughts on how we can make that language more clear?

**Comment by joanneesteban** [comment]
### Other to do

- [ ] Clarifying the funnel:
- Raw dataset
- Explanation for the sessions

- [ ] Opening a Content request for the content

- [ ] Adding overall dashboard description: `How might we improve the Screening Tool completions by metro area`

**Comment by joanneesteban** [comment]
Closing this ticket in favor of the covid dashboard redesign. This information is going to be in the `Tools Dashboard`
