### ISSUE TITLE
Review LC articles list for LC card sort 

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#12329]
## Review LC articles list for LC card sort 

**Spreadsheet can be viewed, edited, and commented on here:** 
https://dvagov-my.sharepoint.com/:x:/g/personal/jennifer_lee27_va_gov/EeZlOnNcqcNHldoCwec_vo4BvZHDA0qRPYdkMyFx5wa0yQ?e=SIwxqz 

**AC:**
- [x] Please review list of articles and topic and audience labels. 
- [x] Provide comments and feedback. 

**Purpose:** 
We need to create a list of articles for beneficiaries to map to topic/audience tags. 
- This list will be used for both the Veteran and non-Veteran (VA business SME) participants. 

We need to create a list of articles for non-beneficiaries to map to topic/non-beneficiary audience tags. 
- This list will be used used only by the non-Veteran (VA business SME) participants to map, in addition to the beneficiary articles. 

**Audience tags used:**

- Schools, administrators, and other education professionals
- Career counselors and other employment specialists
- Fiduciaries
- Funeral directors and cemeteries
- Lenders, appraisers, and other real estate professionals
- Veteran service organizations and accredited representatives
- ~Clinicians, researchers, and health care workers~
- Veterans 
- Elderly Veterans / Veterans age 65+ / Senior and aging Veterans
- Former prisoners of war
- Gulf War Veterans
- Incarcerated Veterans
- Korean War Veterans
- LGBTQ+ Veterans
- Minority Veterans
- Native American Veterans
- Vietnam War Veterans
- Women Veterans
- World War II Veterans
- Family members
- Service members

**Topic tags:**

- VA account and profile
- General `<-- nomenclature totally TBD - General Info, More resources - label is TBD. See spreadsheet with examples of real content that might fall under this 'general' Learning Center category. `
- Burials and memorials
- Careers and employment
- Decision reviews 
- Disability
- Education and training
- Health care
- Housing assistance and home loans
- Life insurance
- Pension
- Records
```
Hey team - the functionality of the administration data is in flight, per our convo. Just be aware, the spreadsheet doesn't reflect that.
- Veterans Benefits Administration
- Veterans Health Administration
- National Cemetery Administration
```

**Related work/tickets:**

Ticket #11012
Ticket #10982

**Comment by jenniferlee-dsva** [comment]
This task is part of work to get read for the [card sort in ticket #10982](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/10982)

**Comment by jenniferlee-dsva** [comment]
fysa @oksana-c vis-a-vis audience and topic CMS taxonomy

**Comment by jenniferlee-dsva** [comment]
Note: @JeffBarnesUSDS and I discussed a few evolutions of tags governance (such as enabling a 'none' topic value and restricting the administration labels for use only for non-beneficiary audience content). The card sort is primarily a nomenclature test, so this shouldn't affect the card sort, except for some articles in the spreadsheet may be okay to map just to an audience label and 0/null topic label.

**Comment by andaleliz** [comment]
I've heard from other VA researchers that they experienced a high abandonment rate and weren't happy with the results of their sorts with 60+ cards.  Their recommendation is to keep it to 20-30 cards (which also closely aligns with [the best practices from usability.gov](https://www.usability.gov/how-to-and-tools/methods/card-sorting.html#:~:text=Best%20Practices%20for%20Card%20Sorts,especially%20for%20an%20open%20sort.)), and have a max of 10 categories to keep participants engaged and prevent them from getting overwhelmed.  I set up a [draft card sort](https://adhoc.optimalworkshop.com/optimalsort/eaihc576/sort) using content from the prototype a while back, to get a feel for what folks would see.  Personally, I think this is a little overwhelming as it is, with only 20 cards and 12 categories.

@jenniferlee-dsva and team, what do you think about cutting this article list in half, and selecting the 10 topic and audience categories we are most interested in learning more about?

**Comment by jenniferlee-dsva** [comment]
I agree! Purposely provided too much so you and the content team can help curate down to make sure we have right coverage. 

Note - as I commented on draft plan - I do think that Veteran/beneficiaries should have a card sort with just beneficiary articles and tags. (i.e., exclude non-beneficiary content for Veterans card sort.) 

But for VA business authors, we should include a mix of beneficiary and non-beneficiary things bc they could be potentially creating content for both.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva I agree with your last comment here--it makes sense to have separate card sorts for beneficiaries and non-beneficiaries. Along those lines, below are my suggestions, separated as such.

I pasted this from above. I think you've made updates to these lists that aren't reflected here, but I'll still provide my 2 cents on cutting them down a bit. You can take what you agree with and revise the above master lists. Ones I've removed altogether have a strike through. I've indicated with bolding which tags could appear for both beneficiaries and non-beneficiaries. Maybe from what I've done here, we can winnow it down even more, but this is a start: 20 articles / 10 audience tags / 10 topic tags. I think what @andaleliz is saying is that we should shoot for 10 total audience and topic tags, rather than 20 (10 of each). So there's some more work to do.

<H2>10 Audience tags used for beneficiary card sort:<H2>
**Veterans** (7 articles identified in the spreadsheet in green highlighting)
Elderly Veterans / Veterans age 65+ / Senior and aging Veterans (2 articles identified in green)
~~Former prisoners of war~~
**Gulf War Veterans**  (1 article identified in green)
Incarcerated Veterans (1 article identified in green)
~~Korean War Veterans~~
LGBTQ+ Veterans (1 article identified in green)
Minority Veterans (1 article identified in green)
Native American Veterans (1 article identified in green)
**Vietnam War Veterans** (2 articles identified in green)
Women Veterans (3 articles identified in green)
~~World War II Veterans~~
Family members (1 article identified in green)
~~Service members~~

<H2>10 Audience tags used for non-beneficiary card sort:<H2>
Schools, administrators, and other education professionals
Career counselors and other employment specialists
Fiduciaries
Funeral directors and cemeteries
Lenders, appraisers, and other real estate professionals
Veteran service organizations and accredited representatives
Clinicians, researchers, and health care workers
**Veterans**
**Gulf War Veterans** 
**Vietnam War Veterans**

<H2>10 Topic tags used for beneficiary card sort:<H2>
VA account and profile (2 identified in green)
General (4 identified in green)
Burials and memorials (1 identified in green)
Careers and employment (1 identified in green)
~~Decision reviews (Are Veterans familiar with this term yet? If not, maybe we should use "Appeals" for the sake of this exercise)~~
Disability (3 identified in green)
Education and training (1 identified in green)
Health care (4 identified in green)
Housing assistance and home loans (2 identified in green)
Life insurance (1 identified in green)
Pension (1 identified in green)
~~Records~~

<H2>10 Topic tags used for non-beneficiary card sort:<H2>
VA account and profile
General <-- nomenclature totally TBD - General Info, More resources - label is TBD. See spreadsheet with examples of real content that might fall under this 'general' Learning Center category.
Burials and memorials
Careers and employment
~~Decision reviews (Are Veterans familiar with this term yet? If not, maybe we should use "Appeals" for the sake of this exercise)~~
Disability
Education and training
Health care
Housing assistance and home loans
Life insurance
Pension
~~Records~~

**Comment by andaleliz** [comment]
We’re going to have to test the topic and audience tabs in separate card
sorts, since people can’t put one article into multiple categories.

I think we’re okay with 10 audience, and 10 topic tags (20 total). Sorry
for any confusion.
-- 
Liz Lantz
UX Designer, Ad Hoc
843-898-4463
http://adhoc.team

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO - thank you so much! I _think_ I grok most of what you wrote. Could we sync on a call to confirm?

**Comment by andaleliz** [comment]
@jenniferlee-dsva and @bethpottsVADEPO any more developments on this?  I also _think_ I understand most of what Beth wrote but am not totally sure. 

It sounds like we've narrowed it down to 10 tags per card sort, and the beneficiary sets (2) above would go to Veterans, and the non-beneficiary sets (2) would go to the content authors.  Do I have that right?

**Comment by DanielleThierryUSDSVA** [comment]
Hi.

Just adding some notes (and 1 request) on the tags for our records...

- Can we go with this for the age-related tag options?

Elderly Veterans / Veterans age 65+ / Older Veterans

AP style prefers "older adult" or "older person" over "senior citizens," "seniors," or "elderly" (and specificity of age when possible) so would recommend replacing "senior and aging Veterans" with "older Veterans".

- AP style doesn't add the + to LGBTQ. They do say LGBTQIA is okay to use, if you explain the last 2 letters (but we wouldn't have room for that). So I think we can stick with LGBTQ no plus if we'd like.

- AP style calls for the use of "female" rather than "women" as an adjective. But VA definitely uses "women Veterans" across the board. Noting here for further discussion.

- We discussed the use of the term "minority Veterans" as well, and that there's a lot of trickiness here with best practice typically advising against it for different reasons (including creating a feeling of otherness & the fact that the U.S. is moving toward becoming a majority-minority country) but VA having a Center for Minority Veterans and the need for a tag that can be generally applied. 

AP style does note that "people of color" and "racial minorities" are generally acceptable terms (though specificity is preferred when possible). AP style also notes to be mindful that some Native Americans feel these terms fall short by not encompassing their sovereign status (we do have a specific category for Native American Veterans so I think that's okay). 

I know we decided to keep this term as a tag option for now. But I do think it's one we may want to revisit at some point.

  - Re: Native American Veterans - AP Style says that both "American Indians and Alaska Natives" and "Native Americans" are acceptable terms. VA is interesting because for benefits, VA uses "Native American Veterans," but the VA Center for Minority Veterans page uses "American Indian and Alaskan Native Veterans." I think we're okay with what we have; just noting here for our records.

**Comment by andaleliz** [comment]
>Can we go with this for the age-related tag options?
Elderly Veterans / Veterans age 65+ / Older Veterans

@DanielleThierryUSDSVA are we testing 3 different tags, or is the intention that this is all on one tag?

**Comment by DanielleThierryUSDSVA** [comment]
@andaleliz I was assuming 3 different tag options. We definitely don't want one tag with all of those.

**Comment by andaleliz** [comment]
Got it - was confused because all of the others have a bullet point per tag. So then we are up to 12 audience tags, which become categories in our card sort. Not the end of the world, but the fewer categories we have the more manageable the card sort will be for participants.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. Right, yes, totally understand that. In my comment, I was just asking if we could change one of the 3 options that were already there in the list (2nd bullet under beneficiary card sort - Elderly Veterans / Veterans age 65+ / Senior and aging Veterans (2 articles identified in green)). 

So I think this is a separate question. Which is, do we want to test those different variations, or do we want to just go ahead and make a decision on which one of them to use for the card sort? I'm not sure of the value of testing those, especially if those are the only variations we're testing for an audience tag.

**Comment by jenniferlee-dsva** [comment]
Hi - responding to @DanielleThierryUSDSVA and @andaleliz's Qs above. 

> @DanielleThierryUSDSVA are we testing 3 different tags, or is the intention that this is all on one tag?

- Elderly Veterans / Veterans age 65+ / Older Veterans

To test as variations of one tag - not that this is all on one tag. Per other comments elsewhere - VHA uses "Senior and aging Veterans" and VBA uses "Elderly Veterans." VHA's new plain language health services taxonomy uses [ "Geriatrics: older adult care, senior care." ](https://www.va.gov/pittsburgh-health-care/health-services/#social-programs-and-services)
Because there's a concern about how people may interpret the existing VA labels vs. more modern nomenclature, we'd like to make sure that Veterans' mental model maps okay to the content that VA has for this audience.


>AP style doesn't add the + to LGBTQ. They do say LGBTQIA is okay to use, if you explain the last 2 letters (but we wouldn't have room for that). If we want to be 100% true to AP style, we could drop the +?

@DanielleThierryUSDSVA - added the + based on your recommendation from one of our previous convos. I'm fine leaving it out! 

>AP style calls for the use of "female" rather than "women" as an adjective. But VA definitely uses "women Veterans" across the board. Noting here for further discussion.

Let's keep "women Veterans." "Female" seems like a still very new outlier and would also introduce a major nomenclature discrepancy with VHA's current plain language health services taxonomy which uses "women Veterans care" and "women's health services." If at some point "female" becomes the new common norm, we can reconsider.

>We discussed the use of the term "minority Veterans" as well, and that there's a lot of trickiness here with best practice typically advising against it for different reasons (including creating a feeling of otherness, erasing more specific identities, & the fact that the U.S. is moving toward becoming a majority-minority country) but VA having a Center for Minority Veterans and the need for a tag that can be generally applied.

Agree with many points here. Especially that over time it will be tricky - bc "people of color" in the future will not be a population "minority." However, I think "minority" is pretty well understood to mean not just population numbers but political power/equal access, so let's stay with "minority Veterans" for now. Also, VHA plain language health services taxonomy uses "minority Veteran care," so I would like very much to _not_ introduce a new variation within the larger VA landscape of service terms. 

There are a handful of services - health, social, programmatic and otherwise - that all VA medical centers are required to provide and which have dedicated VAMC coordinators. They currently use the terms: 

Minority Veterans
Women Veterans
Native American Veterans
LGBT Veterans

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @jenniferlee-dsva!

Follow-up:

- **LGBTQ:** Yes, I'd said I'd follow up on AP style direction on the + to see what they said. Since they don't use it, I think dropping it is fine. I do think keeping the Q is good.

- **Women vs. female:** Totally agree. Was just wanting to note this for awareness since we were checking AP style on these other audience tags.

- **Minority:** Works for me. Thanks!

**Comment by andaleliz** [comment]
@jenniferlee-dsva Yes, I would recommend a more diverse distribution for the sake of the card sort. I'd focus on the categories that leave the biggest question mark in your mind - `All Veterans` seems like it would be the most straightforward of all (and thus not the most interesting to gather data on).

For your second bullet - OptimalSort doesn't have the functionality to randomize a category (thought we can randomize the order). What do you think about asking people at the end of the session via question w/ three radio buttons (one being each label). Not quite sure off the top of my head how we'd phrase it, but I think this would be the best way to help us understand which of the 3 resonates the strongest.

**Comment by andaleliz** [comment]
Also, RE your comments in the doc - 

>33 articles total here – is this okay or do we want to further reduce for content authors? We can also redistribute (add more articles for some audiences, reduce for others). 

If we can reduce that list even further, that'd be great. 30 is really the ultimate max we want to hit - closer to 20 would be better.  

I see we also have 15 audience tags for the non-beneficiary card sort, and I'd love to see that closer to 10. If we make the senior/elderly/65+ audience a radio at the end, that brings us down to 14.  Are there any others that we have more confidence around that perhaps we don't need to test?

**Comment by jenniferlee-dsva** [comment]
Asking a question at the end of the card sort gets us into survey territory, so I don't think we can do that without OMB approval. 

If we need to create 3 versions of the card sort for Veterans, that would be simpler and get us the actual user behavior data that we need. This would be more helpful and realistic than survey feedback. 

1. Veteran group 1 - test with Elderly Veterans
2. Veteran group 2  - test with Veterans age 65+
3. Veteran group 3 - test with Older Veterans

Ditto for Author groups.

**Comment by andaleliz** [comment]
I've heard of other teams using the Questionnaire feature at the end of an unmoderated sort with no issues, so I don't _think_ it'll be an OMB issue. I'll double check w/ Lauren if we wanted to go that way.

I have some concerns about 3 separate card sorts to test these variations:
1.  How does that inform whether one is stronger than the other if the responses are equally distributed across the three options? 
2. Other teams have had a hard time getting the participation they want. Say we can only get 70% of our target, and the randomization caused only a small group to get `older veterans`?  We wouldn't really have the data we want. 
3. I'm not sure if/how Perigean will manage the randomization appropriately to try to get even distribution.
4. OptimalSort has features/data output that make synthesis very efficient. If we have to combine the data from 3 separate card sorts, we'll lose that and spend more time on synthesis.

Looking back at the comments around testing these variations, I don't think we've clearly defined the question we're trying to answer through testing these. Is that captured anywhere? That might help us find the best way forward.

**Comment by jenniferlee-dsva** [comment]
Hi @andaleliz - Either way, I prefer we gather data by actual card sort rather than via survey feedback. 

Flagging @JeffBarnesUSDS to confirm one way/other re asking questions at the end of a card sort - whether that needs OMB survey approval.

**Comment by jenniferlee-dsva** [comment]
RE first bullet point:
> How does that inform whether one is stronger than the other if the responses are equally distributed across the three options?

@bethpottsVADEPO  @DanielleThierryUSDSVA and I discussed this during last week's working session. Our concern about including all 3 variations in one card sort is that it will definitely skew comprehension bc:
1/ The other labels map 1:1 to articles. 
2/ But by having all 3 older/elderly/65+ labels together, by juxtaposition, it already breaks the pattern of a label mapping 1:1 to an article. Now for just these 3 labels, users have to figure out what to use, not in contrast to the OTHER audience labels but to each other. 

We want to make sure that the user results are based on the same 1:1 audience to an article mapping model that the other labels are based on. 

@DanielleThierryUSDSVA @bethpottsVADEPO  - feel free to add/clarify ^.

**Comment by sshein** [comment]
Hi all - Liz and I discussed the options at our 1:1 today around how to test between the three "elderly" labels, and I wanted to chime in a few thoughts:

- Three different card sorts doesn't seem like it would necessarily solve the problem, and plus it would be a lot to ask of Perigeon. Given we only have a couple articles that we think would "fit" in those categories, and the fact that the labels are all pretty similar, there is a likelihood veterans would sort things into those categories for all 3 studies, and then we wouldn't have an answer for which one is the best one to use. I suppose the answer then would be "any of these work." 3 studies is an option but it seems a little overkill and could potentially not give us our answer.
- @lildziner recently ran a study similar to this (it did not need further approval) for the facilities team, where they were trying to assess the best label for facilities for particular scenarios. She had a question she asked before the card sort where she gave veterans a blurb "imagine this scenario" and then asked them to pick between 3 multiple choice questions about which status they thought was the best fit for that particular scenario. Wondering if this would work for this case. I understand it's not the same as sorting all the cards into categories with others available, but I think it would probably answer the question you're looking for with the least amount of effort/time. You could do a few different article titles/scenarios as well to make it less targeted. You can see [her conversation guide here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/facility-status/conversation-guide.md).
- Another option would be to punt this question to a smaller study. e.g. Liz could run the first 5 card sorts through a moderated study where have more leeway to ask them things - in that case we could potentially have all 3 labels as groupings the veteran could use, but have some conversation with them about what we were looking for / talk to them, and then once we got a clear preference for one of the labels, we use that one for the remaining unmoderated 45 folks.

**Comment by sshein** [comment]
also I'm on PTO tomorrow through Friday so if this turns into a discussion and I'm not replying, that's why! :)

**Comment by jenniferlee-dsva** [comment]
This is complete. 

**The document with the final list is here:** 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/card-sort-audience-topic-082720.docx

Final decisions for card sort:

- We'll use Veterans age 65+ with complex care needs;  LGBTQ - no + sign; Family members and caregivers. 
- We're doing a hybrid card sort, no questions asked at the end of sorting. 

Card sort includes: 

- Veteran sort with audience labels
- SME author sort with audience labels
- Topic card sort - everyone gets same inventory of topics

**Comment by andaleliz** [comment]
@jenniferlee-dsva 
> no questions asked at the end of sorting.

A recent Facilities sort similar to ours had a post-sort question asking Veterans to enter a participation code given to them by Perigean to confirm completion. This is how Perigean keeps track to compensate people, and I'm pretty sure Lauren was part of the process to set that up.

I've reached out to Lauren to see what is the preferred way to keep track of this for our study.  I'll update our study set-up accordingly once I hear back. It may be that we end up having that one question at the end of sorting.
