### ISSUE TITLE
Finish buildout of Products folder

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#1239]

**Comment by rroueche** [comment]
### Goal
All VFS teams can learn about and add documentation about their products from the va.gov-team repo.

### Description
We need to finish the PR for getting that folder skeleton in place on va.gov-team, and then we need to determine how we want to actually move content in from vets.gov-team.

### Definition of Done
- [ ] All product folders exist in va.gov-team repo
- [ ] Convos have been had w/PMs on VFS Team side for collab on how to move from vets.gov-team
- [ ] Decision from ^ is documented and shared for global awareness

**Comment by mnorthuis** [comment]
Folder structure is in place and ready to be used.  Need to determine process for moving/copying files into their new home. 

@rroueche Moving files over into the products area from vets.gov-team repo is going to take a number of discussions and time to actually do. With each product, we will need to determine what older documents are needed in the new repo.  How much history do we want to bring over? 

I suggest we close out this issue since the structure is built out, and let the planning on how/what to move over be a separate issue.

**Comment by mnorthuis** [comment]
Closing this issue, structure in in place.  Moving files from other repos wil be covered in other issues.
