### ISSUE TITLE
Enforce unit test coverage on vets-website

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#12432]

**Comment by mchelen-gov** [comment]
possible checks:
- overall code coverage must increase or stay the same due to code coverage
- apply minimum [application code coverage](https://github.com/department-of-veterans-affairs/va.gov-team/issues/184) based on files modified

relevant tools:
- https://coveralls.io/
- https://codecov.io/

it might also be worth making code coverage more visible, regardless of enforcement?

**Comment by timwright12** [comment]
@mchelen-gov We have an in progess ticket to publish the coverage report https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/184

Would that satisfy this?
