### ISSUE TITLE
[Development] CST: Claims Estimation Date

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12480]
## Issue Description
We have heard from our stakeholders that the estimate for time to completion of a claim is not correct and too far out.  This story is to investigate where/how this is shown/calculated and then probably remove it like we did for the appeals.

Here is the note:

> Thank you for working with us to help improve the way Veterans view the status of their pending claims and appeals in VA.gov.  The edits that have been made to date are a great start and we are excited to see the final outcome. 

> We do have a hot issue that for which we need some immediate assistance.  We have seen a significant increase in the number of complaints/concerns we receive related to the estimated completion date for claims, as may are reflecting est. completion dates of fall of 21.  This issue has also been a hot topic of conversation during the USB’s Tele-townhalls.  The USB/PDUSB has asked that we reach out to discuss options. 

> There is a meeting later today for which we will need to provide some info - is there someone I can reach out to for a quick discussion?  We are looking a two-phase approach, a temporary solution to improve the Veteran’s experience and then a comprehensive review of the methodology of the calculation to ensure it is an accurate reflection of the current environment.

> Do you have time for a quick chat this morning or can you point me in the right direction for assistance?

## Acceptance Criteria
- [x] Discover where/how we make the calculation
- [ ] Potentially code up a removal of this estimate as another short term fix
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Mottie** [comment]
In the code, we:

- Get the claim status from EVSS (`/v0/evss_claims_async`)
- Get the `maxEstDate` value from a particular claim
- Make a calculation of "today" plus 2 years
- If the `maxEstDate` if greater than "today" plus 2 years, we show the user `Estimate not available`, and nothing else.
- For dates within the 2 years, we show the `maxEstDate` AND
  - If the `maxEstDate` is less than "today", we show the user `We estimated your claim would be completed by now but we need more time.`
  - Otherwise we show the user `We base this on claims similar to yours. It isn’t an exact date.`

**Comment by Mottie** [comment]
I'm not sure what needs to be done here?

**Comment by luke-gcio** [comment]
@kevinstachura is using another ticket to explore the design elements and this ticket will be used to code up his changes.  Moving to sprint 29 since we did not get all the necessary info from stakeholders until late in 28.

**Comment by Mottie** [comment]
I'm still awaiting a design for this change. It looks like we got an email today with the requested changes.

**Comment by Mottie** [comment]
Actually, the email I referred to above applies to https://github.com/department-of-veterans-affairs/va.gov-team/issues/11801 - I'm still not sure what needs to be done with this issue. The duration cards have been hidden in https://github.com/department-of-veterans-affairs/va.gov-team/issues/10293, and there shouldn't be any `maxEstDate` information shown to the user (at this time).

**Comment by Mottie** [comment]
As far as I know, we don't have any feedback nor designs for adding an estimated time to the claim status. It _should_ include mention of COVID delays.

**Comment by kevinstachura** [comment]
@Mottie hopping in here! So the design for this ticket is located here:

https://vsateams.invisionapp.com/share/VUYLT5C9KEZ#/430229164_Claim_Appeal_Status_-_Claim_Detail

For those catching up: We've had to remove the 'completion estimation date' since the algorithm was totally off due to exams not being able to be scheduled in certain areas - due to COVID. Since the exam scheduling factors heavily in the date algorithm, this date has been way off. Our solution has been to remove the incorrect completion estimation date and replace it with an explanation for why the user does not see the estimated completion date.

@peggygannon we received this explainer text from our VBA SMEs:

>The estimated claim completion date feature has been temporarily removed. Due to the impact COVID-19 has had on the availability and scheduling of required in-person medical disability exams, the estimated completion date is not accurate at this time.  VA is coordinating efforts to ensure all exams are scheduled and conducted as soon as it is safe in each area.  You can review the status of exams in your area here. 

'Here' is actually a link, and goes here: https://benefits.va.gov/compensation/claimexam.asp

But we know this might not fit the content guidelines for va.gov (for example, using 'here' as a link). Could you please take a look and see how you might improve it? We appreciate any assistance you can provide. Thanks Peggy!

**Comment by Mottie** [comment]
Here is a screenshot of what I ended up with...

![](https://user-images.githubusercontent.com/136959/92815614-07326100-f38a-11ea-839f-208def330103.png)

Note: I fixed the "COVID-19 has **had**" text immediately after the screenshot; I can't test to ensure it's working since we don't have a user that has any claims. My previous method of using the Nightwatch end-to-end tests no longer works since all Nightwatch tests are broken now.

**Comment by peggygannon** [comment]
ok, thank you will take a look at this tomorrow and provide recommendations.

**Comment by Mottie** [comment]
Result after Peggy's feedback

![](https://user-images.githubusercontent.com/136959/93378205-b905dd80-f821-11ea-9bfd-3e71725211c3.png)
