### ISSUE TITLE
VAOS front end discovery questions

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#1249]
These are design/requirements focused questions that we've come up with by researching how the new design (https://adhoc.invisionapp.com/share/WATIINRHZ3F#/screens/379622434) compares to the existing application.

1. There's no community care flow in the current designs, is this is being worked on?
1. The current app enforces limits for the number of requests a Veteran can submit, are we doing the same in the new app? We need the UI for this if so
1. There's no direct scheduling, type of care flow. Is this in progress, or intentionally left out?
1. Is the provider flow meant to be used with VistA, or just with Cerner?
1. There are some form patterns that are different from current multi page forms. Are these intentional?
   - Progress bar indicator
   - Descriptions underneath radio buttons, larger typed radio button descriptions on one page
   - Review page with editable blocks
1. Under what conditions will a user need to choose a clinic?
   - What's the UI for this
1. The designs appear to be stopping a user with a PACT team from choosing clinics outside of that team. Is that intentional?
1. How do we choose what specific type of care for an appointment, given that the new design has users choosing from a handful of groups?
1. Are we displaying any of the current custom text/messaging for facilities? Where is this displayed?
1. Are we still displaying the patient/scheduler messaging on the appointment details page?
   - Need the UI for this if so
1. Are we still showing the notifications that exist in the current app?
   - Need the UI for this if so
1. Veterans can no longer choose if they want email notifications, is this intentional?
   - Need UI if we will still implement this
1. Do we know what impact CC drive time will have on the new flows?

**Comment by rtwell** [comment]
1) first pass is getting the UX improvements working with the current VAOS flow. Community Care stuff will come next. 

2) I wasn't aware of these limits. We should discuss!

3) this prototype is to test the three flows depicted. The results will inform the next version, which will include it. i suspect the type of care - self schedule flow will utilize 99% of the screens from the other flow(s).

4) this is the clinic/Cerner mashup. this is conversation. 

5) correct, there are things here that dont exist yet, or are modified. 
   - progress bar indicator: i would like to stay away from this until we know we need it.
   - these are different than what we currently have. however, this is a prototype and we're still figuring out how folks think about this stuff. our current radio button design didnt work as well. we may need to add an additional radio button style to the design system. OR we may need a completely different interaction (like a drop down menu, etc etc).
   - review page is new

6) A user will need to choose a facility in the flow where they have chosen a Specialty Care (like Audiology) and then get a list of facilities within the current Health care system they are browsing. This flow will be part of the next prototype.

7) Yes and no. Veterans have to be "registered" in a VA "health care system" e.g. "VA Pittsburgh health care system", which includes 8 facilities within it. Veterans can be registered at multiple healthcare systems. that what's this screen is determining:

![image](https://user-images.githubusercontent.com/12564977/63550019-b55d3580-c4ff-11e9-8ed0-967dea60c030.png)

If a veteran is only registered at one system, they wont even see a choice there. If they are in a situation where they have to go to a clinic in a different system (for instance, a Veteran is on vacation and needs to see a doctor), they have to register at the system first, and then proceed to make an appointment after enrollment (this will more than likely happen over the phone or in person).

8) Each group is a starting point. i see it kinda like buckets—a user can click the specialty care bucket, and then get a list of the specialty care services available, click one of those, see which facilities offer that service, click one of those and see what times are available (_if that VAMC service is enrolled in self-scheduling_). otherwise, it would be a "request" flow

9) No, i propose we move all messaging to secure messaging on MHV.

10) no

11) no. notifications (like chat) will be via Secure Messaging in MHV.

12) correct, they are going to get email notifications when they create / cancel / reschedule appointments like any other enterprise service on the planet. they can opt out of them in the email themselves.

13) we do. let's discuss!

**Comment by jbalboni** [comment]
Thanks @rtwell!

To clarify for question 7, I was only asking about the choice after the health care system one. Right now, you can choose both your system and then the clinic, when choosing primary care. You could opt to choose a clinic that isn't associated with your PACT team. That second choice is what it looks like we're removing in the new designs.

**Comment by rtwell** [comment]
ah, gotcha. 

PACT Teams = Primary care, always (as I understand it). There are no Specialists on your Primary Care team, although they do refer Veterans to specialists.

**Comment by jbalboni** [comment]
That seems true from what I can see in staging, but it also looks like you
can make primary care appointments outside of your pact team in the current
app.

**Comment by jbalboni** [comment]
Summarizing the answers:

Follow up discussions:
- Talk about request limits
- CC drive time
- Question 7, primary care/PACT team relationship (I think @rtwell and I are maybe still talking past each other)
- Anything @lalexanderson-dsva wants to add to these answers

In-progress design work (dependent on research outcomes)
- Community care request flow
- Direct schedule, type of care flow
- Clinic choice page/conditions
- Choosing type of care from group flow
- Community care drive time updates
- Adjustments to some current form field patterns

Newly identified design discovery work
- Request limits

Technical discovery work to do:
- How does provider first scheduling work on the backend and what do we need to build to accomplish it?
- Can you currently opt out of email notifications from the email itself? If not, how do we implement this?
- How can we leverage secure messaging to replace the current messaging/notifications?

**Comment by markgreenburg** [comment]
## Answer to request limits:
- Request limits are configured by VATS, so in theory each site could set a per-veteran appointment request limit (unclear what the limits are usually set to or how often veterans exceed them).

## General PACT business rules
- A veteran can probably have more than one PACT, but can only have at maximum one PACT per facility (see section below, some of this still tbc)
- A veteran can only *direct-schedule* for Primary Care with (one of) their PACT
- A veteran can *request* Primary Care at any facility that allows this appointment type (within the instances / parent facilities where they're registered)

## PACT-Site Associations:
Is it possible for a veteran to have more than one PACT per healthcare system / parent facility?
- Marcy remembers this as being possible though it's not confirmed yet
- If this is confirmed possible, we'll need some extra UX to allow veterans to either select a facility or select from a list of PACT teams in the 'care type' flow (currently, the prototype allows for selecting a healthcare system, then a type of care, and then auto-selects the PACT for booking - which won't work if a veteran has more than one PACT team).
![Screen Shot 2019-08-23 at 3 34 39 PM](https://user-images.githubusercontent.com/24251447/63622900-ab017100-c5bd-11e9-9bbf-540bd05f02fc.png)
