### ISSUE TITLE
Discovery Around Migration from Prometheus to DataDog

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#12650]
## Description
We are going to be making the switch to DataDog for our monitoring tool, but first, need to come up with a plan for how to do that. Right now we are not sure when Datadog is going to get here so there are still a few unanswered questions.  

## Background/context/resources
DataDog refferenec Docs:
- https://dsva.slack.com/archives/CR838KMV1/p1589320178055700 (link to the ask for DataDog) 
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/8053#issuecomment-622015459 (ticket that was for testing a trial of DataDog)
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/infrastructure_recommit/monitoring/solution_evaluation.md (document for monitoring evaluation when DataDog was being tested) 

## Technical notes
_Notes around work that is happening, if applicable_

---
## Tasks
- [ ] _What things need to happen?_

## Definition of Done
- [ ] _What is the expected outcome of this issue?_

---
### Reminders
- [x] Please attach your team label and any other appropriate label(s) 
- [x] Please attach the needs grooming tag if needed
- [x] Please connect to an epic

**Comment by jhouse-solvd** [comment]
@mydesignrocks - this was an existing ticket, and I believe most of the work is done already, but just want to tie up loose ends and ensure that original discovery / planning / design needs were met. 

There is no immediate action required on your part, but we can discuss in an upcoming chat about this.

**Comment by jhouse-solvd** [comment]
We will attach relevant background documentation to this ticket and then close it out.

**Comment by jhouse-solvd** [comment]
Please see parent ticket for ongoing efforts to migrate from Prometheus to Datadog. We do not yet have the full number of licenses for Datadog that we would need to monitor all hosts in all environments. For now, we will apply those licenses selectively so that we can use Datadog for application performance monitoring (APM). Prometheus will continue to exist for at least the next 3-6 months, as we are gradually allotted additional licenses. 

Closing.
