### ISSUE TITLE
AWS Staging: CC Podiatry Ineligible Veteran Confusing Modal

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#12689]
![PodiatryCommunityCare Modal.PNG](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/1e88b1cf-a706-4e40-965a-02cb887e0838)
## Acceptance criteria (update message to following)
**You need to call your VA facility for a Podiatry appointment**
You’re not eligible to request a community care Podiatry appointment online at this time.
Please call your local VA medical center to schedule this appointment
[Find your VA health facility’s phone number](https://www.va.gov/find-locations/)

----
## What happened?
Confusing modal for Vets not CC eligible or vets not drive time eligible for CC

## Specs:
- Device: (e.g. iPhone 8, Macbook):   PC
- Browser: (e.g. Firefox, IE 11):  Chrome
- Test User _(if applicable)_:  noahjames.j.staknis@id.me

## Steps to Reproduce
- Login as Veteran who is Drive Time CC Primary Care Eligible but not specialty care eligible (noahjames.j.staknis@id.me), or just not Community Care Eligible (john.morrison@id.me)
- Select Podiatry as type of care.
- Modal displays the following:
> You canʼt schedule a Podiatry appointment right now
>     At this time, podiatry appointments can only be scheduled online for Community Care appointments. To schedule a podiatry appointment at a VA facility, please call your local VA medical center, or use the locator tool to find your nearest VA medical facility.
> 

## Feedback
- modal is confusing
- You are trying to schedule podiatry appointment on-line for Community Care and you get a message you can’t schedule on-line.  And then it says Podiatry can only be scheduled on-line.  But you can’t schedule on-line.   

## Desired behavior
- Podiatry is only available to schedule online in the community for Community Care-eligible veterans.

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

**Comment by marcynadeau** [comment]
@lenaecb Have you had a chance to look at this defect?  
I see this a lot in staging because I configured test patients to be eligible for drive time primary care but not specialty care.    And since Podiatry is not a VA type care, the veteran can't get into the VA flow where he selects a facility. These podiatry ineligible drive time vets just get this:  You canʼt schedule a Podiatry appointment right now.  At this time, podiatry appointments can only be scheduled online for Community Care appointments.

The text should let the veteran know that Podiatry available to schedule online in the community for Community Care-eligible veterans based on drive time.

**Comment by lenaecb** [comment]
@peggygannon - we will need your input here. 

Essentially, Veterans who are drive-time community care eligible for Primary Care only are receiving this alert when they try and book for a speciality care. In all other cases, we redirect the user to the VA request flow for that speciality ( @jbalboni correct me if I am wrong there), but for podiatry, since it's not a care type offered for online scheduling by the VA, we need to treat it differently if the veteran isn't eligible. 

I suggest something close to this:
**Online scheduling for Podiatry is not available for you**
You are only eligible to schedule Primary Care community care appointments online at this time. To schedule a podiatry appointment at a VA facility, please call your local VA medical center, or use the locator tool to find your nearest VA medical facility.

My suggestion above is pretty direct, but until VA enables podiatry for VA online scheduling, we need to be as direct to Veterans as possible.

cc: @lalexanderson-dsva for thoughts.

**Comment by peggygannon** [comment]
Hi, @lenaecb Let me know if you think this message will work:

**You’ll need to call your VA facility for a Podiatry appointment**
Online scheduling for a community care Podiatry appointment is limited.  Only primary care appointments can be scheduled online at a community care facility right now.
To schedule a Podiatry appointment, please call your local VA medical center. 
[Find your VA health facility’s phone number](https://www.va.gov/find-locations/)

**Comment by marcynadeau** [comment]
@peggygannon  @lenaecb  Veterans. There are three scenarios where I have seen this error:  Veteran 1 is CC ineligible based on hard code and drive time for all types of care.  Veteran 2 is drive time ineligible for podiatry but is drive time eligible for at least one of other type of care like primary care, optometry, etc.   For example veteran 2 could be drive time eligible for optometry but not podiatry if that nearest VA clinic had an optometrist but not a podiatrist at the clinic.   

So to put in "only primary care appointments can be scheduled online at a community care facility right now" is incorrect because.  1) veteran not be Community Care primary care eligible.  2) Veteran could be cc drive time eligible for other types of care like optometry, etc.  

Also the veteran is not actually scheduling an appointment online. Veteran is only making an appointment request.

**Comment by peggygannon** [comment]
thanks, @marcynadeau for further clarification. Here is an updated alert. Let me know if this'll works:  

**You’ll need to call your VA facility for a Podiatry appointment**
You’re not eligible to request a Podiatry appointment online due to community care distance requirements for this type of care.   
To schedule a Podiatry appointment, please call your local VA medical center.
[Find your VA health facility’s phone number](https://www.va.gov/find-locations/)

cc @lenaecb

**Comment by peggygannon** [comment]
@lenaecb Based on yesterday's sync, here's new message: 

**You need to call your VA facility for a Podiatry appointment**
You’re not eligible to request a community care Podiatry appointment online at this time.
Please call your local VA medical center to schedule this appointment
[Find your VA health facility’s phone number](va.gov/find-locations/)

**Comment by marcynadeau** [comment]
Tested and passed in staging.  	
You need to call your VA facility for a Podiatry appointment
You’re not eligible to request a community care Podiatry appointment online at this time. Please call your local VA medical center to schedule this appointment.
Find your VA health facility’s phone number
