### ISSUE TITLE
[Pre-release] Update `cache-control` headers

### ISSUE THREAD

**Issue by billfienberg** [department-of-veterans-affairs/va.gov-team#12700]
>we’re going to rely on the cache-control header which will remove the need to hash the file names and pass that into the static content - Rian

References:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
- https://dsva.slack.com/archives/CQH357ZTP/p1598016727019500
- https://dsva.slack.com/archives/CQH357ZTP/p1597412873067400?thread_ts=1597247865.029100&cid=CQH357ZTP
- https://dsva.slack.com/archives/CJYRZK2HH/p1588618591260600?thread_ts=1588602342.228900&cid=CJYRZK2HH
- https://dsva.slack.com/archives/CJYRZK2HH/p1588602342228900
- [Search results for `cache-control` in devops repo](https://github.com/department-of-veterans-affairs/devops/search?q=cache-control&unscoped_q=cache-control)
- Heroku article about HTTP Cache Headers: https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers#conditional-requests
- [Slack message reporting apps intermittently crashing when using cached assets](https://dsva.slack.com/archives/CJYRZK2HH/p1588175840156000)

**Comment by billfienberg** [comment]
## Notes
>The Cache-Control header is the most important header to set as it effectively ‘switches on’ caching in the browser. With this header in place, and set with a value that enables caching, the browser will cache the file for as long as specified. Without this header the browser will re-request the file on each subsequent request. - https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers#cache-control

**Comment by billfienberg** [comment]
Notes: 

The [`vets-website-deploy` script](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-vets-website/files/vets-website-deploy.sh) uses [`aws s3 sync`](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html). 

## References

- https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

**Comment by billfienberg** [comment]
>this is the page we’ll want to validate the headers against: https://www.va.gov/education/how-to-apply/ - https://dsva.slack.com/archives/CQH357ZTP/p1598017123019600?thread_ts=1598016727.019500&cid=CQH357ZTP

**Comment by billfienberg** [comment]
Optimized build entry file (staging): https://staging-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/static-pages.entry.4c24affda28387eada77-1600897578611.js

Non-optimized build entry file (dev): https://dev-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/static-pages.entry.js

**Comment by meganhkelley** [comment]
Notes from convo w/ Rian: 

* Related: https://adhoc.slack.com/archives/DT5GF6HCG/p1601565472019600?thread_ts=1601564816.017700&cid=DT5GF6HCG
* Rian talked to Fleet about this, Fleet says we should do this now — ”go back to using the random filename approach but rather than building it into the static markup (which requires the two build processes to talk to each other somehow)- VSP handles it in the html server somehow.”
   * We’re already doing this, we were going to stop doing this, Fleet thinks we might not have to stop doing this 
   * We have random filenames on javascript apps. Right now bc build process is together with static content, we can build random filename and give it to static content. We’re splitting those. They’re not talking to each other anymore. Now how do they know what the random file names are? They don’t. We’re going to use just the plain filenames, they don’t change, but what changes is a token that the browser has to fetch about the file. This token way means that the browser has to make an additional request to see if there’s a new file or not. With the filename approach, the browser just downloads a new file
      * The way the browser knows that something is new — currently, we change the name of it, so then it just knows. When something’s new, the name of it changes. WHen the name doesn’t change, the browser has to make another request to see if it’s new or not.
      * The other option is that it downloads the file every time which we don’t want it to do. We have complete control over what the browser does in this situation, we just need to figure out what that beavior should look like. 
   * We need to know what Fleet and Bill decide what to do — this is about the cache-control header (etags). The etag is the identifier for the file that tells you the ID of the file.

**Comment by timwright12** [comment]
**Current Cache Settings for vets-website via:** 
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/roles/deploy-vets-website/files/vets-website-deploy.sh

INFO: Syncing compressed assets to $ASSET_DEST: public, no-cache
INFO: Re-sync subset with shorter cache control to $ASSET_DEST: public, no-cache
INFO: Syncing assets to $ASSET_DEST: public, no-cache
INFO: Syncing assets to $DEST": public, no-cache
INFO: Syncing all content to $DEST: public, no-cache
INFO: Cleanup sync for $ASSET_DEST: public, no-cache

**Glossary**

**Public**: The response may be stored by any cache, even if the response is normally non-cacheable.

**no-cache**: The response may be stored by any cache, even if the response is normally non-cacheable. However, the stored response MUST always go through validation with the origin server first before using it, therefore, you cannot use no-cache in-conjunction with immutable. If you mean to not store the response in any cache, use no-store instead. This directive is not effective in preventing caches from storing your response.

**Comment by timwright12** [comment]
Moving forward on this one to remove the filename hashes from vets-website to allow cache-control to take over

**Comment by timwright12** [comment]
Tested on staging at: https://staging.va.gov/education/how-to-apply/

Staging PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15154

Production PR: https://github.com/department-of-veterans-affairs/vets-website/pull/15171

**Comment by timwright12** [comment]
this has been merged into master
