### ISSUE TITLE
[Design] - MVP learning center - home page 1.0

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#12758]
Create MVP 1.0 version of home page for desktop:
- should include search
- exclude find articles by audience sections
- include 2 topics only 
- needs some kind of 'beta' info alert - telling users this is in beta and will continue to evolve over the next few months

## Acceptance criteria

- [ ] create version of MVP 1.0 homepage
- [ ] @andaleliz, @rtwell, and @jenniferlee-dsva to review

**Comment by andaleliz** [comment]
@jenniferlee-dsva Just want to confirm I've captured the MVP 1.0 elements correctly:

>include search, exclude find articles by audience, include only 2 topics (VA account + profile, and General)

Is that right?

**Comment by jenniferlee-dsva** [comment]
Confirming: 

- exclude find articles by audience, include only 2 topics (VA account + profile, and General)

Everything else should be the same as what's there today in Ryan's mural files: H1, intro text, search options, search bar. 

P.S. I think there's an A11y ticket wrt adding labels for the search options and the search bar, so that iteration overlaps with this one a bit.

**Comment by jenniferlee-dsva** [comment]
One missing thing from discussion - the 1.0 LC home needs some kind of 'beta' info alert - telling users this is in beta and will continue to evolve over the next few months. Similar to the beta messaging we had on the Pittsburgh VAMC site until it reached full launch state.

**Comment by andaleliz** [comment]
talked to @rtwell today; he has this underway and will take care of this.

**Comment by andaleliz** [comment]
talked to @rtwell today; he has this in progress already and will take care of this.

**Comment by rtwell** [comment]
![image](https://user-images.githubusercontent.com/12564977/91845408-19dcc580-ec27-11ea-92d4-23a9330e9b7b.png)

**Comment by rtwell** [comment]
for the beta alert, I would think we'd use the modal we've used in the past for VA.gov (this obviously needs some content eyes):

![image](https://user-images.githubusercontent.com/12564977/91848819-0cc0d600-ec29-11ea-9bff-23824e7a0c3b.png)

**Comment by jenniferlee-dsva** [comment]
I'm sorry I missed the ^ reply (GH notifications in the inbox is a mess). 

@rtwell  @andaleliz - I think we can use the modal when we are fully launched with 1.1. However for 1.0, I prefer to have a persistent message on the LC homepage, rather than the user experiencing the popup every time they come to the page. I'm open to suggestions if this is a truly bad idea, but the reationale is we want visitors to understand that the 1.0 minimal state they are seeing is truly beta, unfinished, and actively evolving (especially since 1.1 will follow on so closely). 

All of the lc pages have our existing in-body info alert components as an option that can be enabled, so thought we could simply use one of those info alerts. We can finalize the text later with the content team but my main Q is regarding where this alert component should be displayed in the content model -- like below the search bar? (Always above the 'articles by audience' and 'articles by topic' sections.)



Remember, the alert might be some other type of messaging in the future - for example, it could in the future be an alert telling people 'hey, for all your coronavirus questions, go to our coronavirus VA page and the cdc website.'

**Comment by andaleliz** [comment]
>my main Q is regarding where this alert component should be displayed in the content model -- like below the search bar? (Always above the 'articles by audience' and 'articles by topic' sections.)

My recommendation would be above the search bar, below the intro text.  If it's below search, and someone jumps right into searching, there's a higher possibility of missing the alert if it's below the search bar.  Above the h1 would give us the greatest chance of it not being missed, but could introduce a weird alert stacking situation when we have other sitewide alerts.

**Comment by jenniferlee-dsva** [comment]
I think we can close this as 1.0 homepage is complete. TY!
