### ISSUE TITLE
[Development] BDD: Separation Location Pulled from API not HardCoded

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#12792]
## Issue Description
Looks like we are still hardcoding separation location and not calling the endpoint developed by the back end.  This story is to integrate and remove the hardcoded file here: https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/content/separationLocations.js

The endpoint is 
[v0/disability_compensation_form/separation_locations](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getIntakeSites)

## Acceptance Criteria
- [ ] No more hardcoded JS file

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
related: https://github.com/department-of-veterans-affairs/va.gov-team/issues/10275

**Comment by ndsprinkle** [comment]
I will be moving on to this ticket to work on today since the banking info screen ticket has been determined unnecessary.

**Comment by ndsprinkle** [comment]
I have successfully adjusted the separation locations file to pull from the api. This file now also formats the response into data that the searchable drop down can use. That functionality is working as expected, but there are still issues with validation on the input that I believe are due to the fact that the data in the separation locations file are a promise. Going to talk with Robin about this to see what he thinks. Also, going to discuss with design a possibility for not validating the field at all and instead allowing the users to select options or do free form. On submission, the free form would select the most matching field.

**Comment by ndsprinkle** [comment]
After talking with design, I am going to pursue the option to let users enter freely, but match to the closest field on submission. However, this whole thing is getting tricky with the asynchronous data. I think the actual ideal solution will be to try to load all this data with the prefill data. If this is possible, then that would make it to where validation would be a breeze.

**Comment by ndsprinkle** [comment]
I guess I will close this for now since the attached PR has been merged that address using the appropriate separation locations list based on environment. After meeting with FE engineers, it was determined that it would be impossible to implement the call to the api to populate the separation locations drop down and also keep all other associated functionality. This is due to how the form system is set up and primarily stems from an issue with using redux in our pages. Down the road, we can revisit to see if there is a better way to handle the api call for this field.

**Comment by luke-gcio** [comment]
Reopening - we will wrap up the solution Nick found in sprint 31.
