### ISSUE TITLE
Google schema.org Improvements

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1284]
**Goal:**
- Conduct schema.org pilot to test how selected Hub pages render on Google search with 
  enhanced display.

**Steps:**  
1.  Select a few pages  -- 3 to 5 -- (from attached PDF) that still exist in Github to use as experiments
2.  Pages should be from one or more of the following Hubs:
      - [ ]  Disability
      - [ ]  Burials
      - [ ]  Education
3.  Make changes suggested in the PDF to those pages, or note where we cannot exactly follow 
     the guidance.
4.  Determine which metrics will be used to measure success (e.g., GA pageviews / traffic sources / before & after screenshots of how content renders in search)
5.  Assess results and determine whether or not to expand this more broadly via Drupal

[VA Markup (1).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3535942/VA.Markup.1.pdf)

**Comment by Karak888** [comment]
@JeffBarnesUSDS @jenniferlee-dsva  Please edit away on this as I really did not have a ton more background to go on.

CC:  @mnorthuis

**Comment by jenniferlee-dsva** [comment]
@Karak888 - edited ^.

**Comment by Karak888** [comment]
https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Global/Search

**Comment by kelsonic** [comment]
This is how one of the pages **currently** appears in my google search:
![image](https://user-images.githubusercontent.com/12773166/65344775-94433f80-dba6-11e9-8f54-63a691fbad21.png)

It seems quite informative and there already exits relevant questions on this SERP. Note that this is **before** I've added any Schema microtags. So I have 2 questions from this:

```
1. What are we hoping that the Schema microtags will solve? What's the problem that led us to creating this ticket in the first place?

2. What are the specific Schema microtags we want to introduce for each route specified in the PDF?
```

I am a little confused what the acceptance criteria are for this ticket. If I can get answers to the above questions, then I should be able to start making progress on the issue. @Karak888 @JeffBarnesUSDS Thanks! 😃

**Comment by ncksllvn** [comment]
Hey @kelsonic, so we do have schema.org markup implemented in the website already, at varying levels per page. If you visit `view-source:https://www.va.gov/change-address/`, search for `schema.org`, you'll see that page is actually pretty well-decorated with schema.org markup already, so it does a pretty good job in the Google search results.

This ticket appears to be asking us to enhance the schema.org work in other pages of the site using the PDF attached in the issue description. All of these pages should either live in `vagov-content` as Markdown files or as the root-level component of a React app in vets-website. I think the plan is to apply schema.org to these page as a test to see if it's worth applying to pages from the CMS as well.

 So I think this boils down to this -

- [ ] https://www.va.gov/disability/eligibility
    - `FAQPage`, `Adding mainEntity to the Question` (from PDF)
    - Lives in vagov-content
- [ ] https://www.va.gov/disability/add-remove-dependent/
    - `FAQPage`, `Title tag only, no real markup on the page`
    - Lives in vagov-content
- [ ] https://www.va.gov/discharge-upgrade-instructions 
    - `FAQPage`, `No Markup present, but a good candidate`
    - React app in vets-website
- [ ] https://www.va.gov/education/eligibility
    - `FAQPage`, `Title tag only, no real markup on the page`
    - Lives in vagov-content
- [ ] https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit
    - `FAQPage`, `No Markup present, but a good candidate`
    - React app in vets-website
 
This should cover items 1, 2, and 3 in the issue description, then I think we can figure out item 4 together. Item 5 will probably just be coming to a consensus on the schema.org work, deciding basis for next steps (implement more widely or not), then closing this ticket.

**Comment by ncksllvn** [comment]
> Determine which metrics will be used to measure success (e.g., GA pageviews / traffic sources / before & after screenshots of how content renders in search)

I'm trying to think of ways to gauge success. We can use Google's [structured data tool](https://search.google.com/structured-data/testing-tool) to make sure we've implemented schema.org correctly on the five pages outlined above. Then, it will probably take a few days to a week for Google to crawl the site, process the schema.org changes so that the changes are visible from a Google search, thus making the FAQ widget visible to us and other users. At that time, how do we measure its value? 🤔 

Couple thoughts -

1. After publishing the schema.org updates, we can check for an increase in pageviews on those five pages over X amount of time. 
    - I don't think this will tell us a lot.
2. Is there some of Google analytics that allows us to see when a schema.org-backed widget is rendered during search results?
    - @nedierecel @jonwehausen have you all worked with schema.org widgets?

**Comment by kelsonic** [comment]
Sent up 2 PRs for this:

[1 on vets-website](https://github.com/department-of-veterans-affairs/vets-website/pull/10792) that updates https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit and https://www.va.gov/discharge-upgrade-instructions.

[1 on vagov-content](https://github.com/department-of-veterans-affairs/vagov-content/pull/562) that updates https://www.va.gov/disability/eligibility, https://www.va.gov/disability/add-remove-dependent, and https://www.va.gov/education/eligibility.

Going through both of those PRs I found that [this Chrome extension](https://chrome.google.com/webstore/detail/structured-data-testing-t/kfdjeigpgagildmolfanniafmplnplpl?hl=en) is invaluable for validating the schema.org microtags on various pages and I highly recommend using it in the future! 👍

**Comment by Karak888** [comment]
@kelsonic @ncksllvn - Does this ticket still need to be validated? It is currently residing in "In Progress" column.  Please let me know, thanks!!

**Comment by kelsonic** [comment]
@Karak888 I wasn't sure if I should put this in the Validate column just yet since this specific issue seems to be more of an epic and the PRs I sent up were POCs only for [the pages mentioned above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1284#issuecomment-534581334) and not across the whole website. Happy to put it in the Validate column though if that's what we should do! :)

I also am wondering whether or not we should experiment with JSON-LD, though perhaps that should be a separate ticket? What do you think @ncksllvn?

**Comment by chrisj-usds** [comment]
For now, I think we can consider this done. 

This particular issue was to properly tag a handful of pages so we could look at search results and try to identify any other positive aspects from using schema.org.  

From there we can decide if / how to move forward and write a larger epic to do so. (That work, if we chose to continue it, would likely include some testing with JSON-LD and integration with the CMS so that these things can be automated.) 

Another side note: I think the content we tagged was all of the FAQ variety (question and answer) but there is another common tag for "how to" type content. We'd investigate that as well.

**Comment by Karak888** [comment]
Moving this to close but will brainstorm on where to store this amazing info for future rollouts! Thanks again for working this so great!

**Comment by ncksllvn** [comment]
@chrisj-usds Should we do a follow-up ticket for evaluating the results using @nedierecel's suggestion after X amount of time has passed?

**Comment by chrisj-usds** [comment]
Sounds good to me @ncksllvn !

**Comment by ncksllvn** [comment]
Follow-up ticket added here, https://github.com/department-of-veterans-affairs/va.gov-team/issues/2040!
