### ISSUE TITLE
Duplicate Spool Submission reports and Year to Date reports being sent in staging

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#12855]
Duplicate reports are being sent by the staging environment. These reports include the Spool Submission Report and Year to Date report. One of the two YTD reports sent is missing the `22-1995 STEM` section. Only one of each report should be sent daily and the `22-1995 STEM` section should be present in the YTD report.

### Expected Behavior
1. Only one of each of the following reports is sent daily:
    - Spool Submission Report
    - Year To Date Report
2. The Year to Date report includes the `22-1995 STEM` section

### Actual Behavior
1. **Two** of each of the following reports is sent daily:
    - Spool Submission Report
    - Year To Date Report
2. One of the YTD reports is missing the `22-1995 STEM` section

**Comment by zurbergram** [comment]
Based on the instances in ![image](https://user-images.githubusercontent.com/1094999/91326561-79a02000-e792-11ea-86e6-802318c7afa7.png)

And when jobs were ran at https://staging-api.va.gov/sidekiq/recurring-jobs

We cannot tell if any old instances existed at the time of job occurring because all the new instances were created after the job was ran

**Comment by zurbergram** [comment]
Recommend checking again tomorrow to see if issue occurs again

**Comment by zurbergram** [comment]
Duplicates were not sent on 8/26/2020
