### ISSUE TITLE
[FE] Make "My home address is the same as my mailing address." un-clickable

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#12876]
On the profile under home address, there is a checkbox to indicate that a user's home address is the same as their mailing address.

It is not possible to un-check this box, which is confusing for users as checkboxes are usually always un-checkable.

### Tasks

- [ ] Design: determine whether we clear the home address fields or not if someone un-checks this checkbox
- [ ] FE: Implement fix — Make box unclickable and handle home address fields according to design recommendations

![image](https://user-images.githubusercontent.com/14869324/91327278-8ddc2100-e782-11ea-9512-bd1e842f4c11.png)

**Comment by Samara-Strauss** [comment]
Actually, I think this just might be a bug. I'm 95% sure that people could check or uncheck that box in profile 1.0. If they go to one of the Home address fields while the box is checked and edit that field, the "Same as mailing address" box unchecks itself, so there's no reason we shouldn't allow the user to check and uncheck.

Here's how it should work:

- Check box:
  - Home address should change to match whatever is in the Mailing address field.
- Uncheck box:
  - Remove the checkbox.
  - The open question is what we do with the address that has been filled in. Here are the options I can think of:
     - Don't change the fields. This seems low risk, and users can edit the fields as needed.
     - Revert to whatever was in the fields before. This seems like it has potential to be confusing and maybe not even possible from a FE perspective.
     - Clear all the fields in the Home address form. I think this could also be an acceptable approach. If someone unchecks the box accidentally, they can just check it again.

At most, I think Tressa or Cassandra needs to weigh in on whether we clear the address fields or not when the box is unchecked, but otherwise, I think we can move this right to FE implementation.

**Comment by Samara-Strauss** [comment]
Sorry, should have tagged — @tressaellen or @callen2563 can you weigh in on a preference for the options I outlined above? I think that's all we should need before moving this over to FE.

**Comment by mshea0606** [comment]
Great job @sanlouise
