### ISSUE TITLE
[FE] Match error messages with VA Profile codes

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#12923]
## Background

I mentioned [in this Slack convo](https://dsva.slack.com/archives/C909ZG2BB/p1598377650070400) that we had someone outside of our team request that we let them know what error messages go with which VA Profile error codes. While I'd love to have a full audit of this, that would be insane; there are about 200 error codes. So, I got this person to scope the request for us and drastically reduce it to these 6 codes:

CORE500
CORE102
CORE103
ADDRVAL109
ADDRVAL112
ADDRVAL108
 
## Tasks

- [ ] In a comment in this ticket, provide the corresponding error message we show for users in the VA.gov profile for the error codes mentioned above. If we don't show anything to the user, note that.

**Comment by erikphansen** [comment]
@Samara-Strauss are you sure that `ADDR108` shouldn't be `ADDRVAL108`?

**Comment by Samara-Strauss** [comment]
You're right – it should be `ADDRVAL108`. Apologies for the typo.

**Comment by erikphansen** [comment]
There isn't really an easy way to answer this. Most error codes are not given any special treatment by the frontend. So then the question becomes: what action triggered the error? Did the error come from running an address through the address validation server? Did the error come when trying to create a save/update transactions? Did the error come because a pending transaction errored out? Each of those will be shown a different error message. To make things more confusing, if a pending transaction errored out, the error messaging will be different depending on how long it took for the transaction to error out; ie, is the user still looking at the edit form or has the edit form/modal exited and they're back at the read-only view?

And there is yet another place where errors could be handled and presented to the user: let's say the user tried to update their phone number, and the transaction was still pending (had not succeeded or failed) when they left the Profile. Now if they come _back_ to the Profile and the API reports that that old transaction had failed, we'll show them an alert telling them about the failure. If that super edge case happens and the error code is `CORE500` or `CORE103`, we show an error alert with the headline of `Your recent profile update didn’t save` and body of `We’re sorry. Something went wrong on our end and we couldn’t save the recent updates you made to your profile. Please try again later.`

**Comment by Samara-Strauss** [comment]
OK, thank you for this. I sent this along to the person who made the original request. I think we are otherwise good to close this out.
