### ISSUE TITLE
Pass through geolocation properties in VA Profile address

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#12967]
We need to add some additional properties from the VA Profile address into the address the va.gov profile uses for residential address.

I believe this is the file that needs to be updated: https://github.com/department-of-veterans-affairs/vets-api/blob/f0e152273b693d3ee61246c1b3f44f99f749b3ce/lib/vet360/models/address.rb

Address swagger (must be on VA network): https://qa.vaprofile.va.gov:7005/address-validation/swagger-ui.html#/AddressValidation-v1

I believe we need the follow fields in the Address model:

- latitude
- longitude
- geocodePrecision (we might not use this, but I think it needs to be passed so that others don't misinterpret the lat/long)
- badAddress (I think we want to check this before using locations?)

We should talk to Lihan Li about this work, he's the auth exp team's BE resource.

**Comment by saneshark** [comment]
@jbalboni I have found the code and updated the model. However, I still need to write some specs to ensure that the new attributes come across when fetching. But this is what brings me to the next question: Are we trying to update these attributes or just trying to retrieve them or both?

**Comment by jbalboni** [comment]
@saneshark Just retrieve them. I believe VA Profile generates them internally, I don't think we can update them directly

**Comment by saneshark** [comment]
OK sounds good. @lihanli This code is not particularly familiar with me. I could test in the address model, but thats less than desirable. I can't seem to find a comprehensive schema for the person object anywhere. Is there a request spec you could point me to that validates the correct schema having this attribute? All specs are passing right now, but that shouldn't be the case since I added 4 new attributes -- i'm assuming we're doing strict schema validation somewhere but maybe not.

**Comment by saneshark** [comment]
Note: we're going to merge changes without badAddress field for now just to get something in the hands of FE. If we need that field in the future we can open a separate ticket to add it.
