### ISSUE TITLE
Refactor AddToCalendar component to use new va-link component

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#13011]
Once it's merged, we should use the new accessible Download link being added in Formation.

PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/369

**Comment by ldelacosta** [comment]
@simiadebowale - Please check if we need to implement this change in the near future. Thanks!

**Comment by simiadebowale** [comment]
Platform Design System team built a va-link component. We should update the existing AddToCalendar component to use the new va-link component.

[va-link Design component](https://design.va.gov/content-style-guide/links)
[va-link storybook](https://design.va.gov/storybook/?path=/docs/components-va-link--download)

**Comment by ryanshaw** [comment]
Currently in VAOS, the `Add to calendar link` makes use of a calendar icon and sends a dynamically generated string (in .ics format) to the browser when clicked. It currently uses the download={filename} attribute on the link so that that string of text is saved with a dynamically generated filename (like: `Community_care_appointment.ics` or `Appointment_at_Cheyenne_VA_Medical_Center.ics`).

However, when using the [va-link](https://design.va.gov/components/link/) ([storybook](https://design.va.gov/storybook/?path=/docs/components-va-link--default)) web component it adds a file download icon.

The download icon can be removed if I don’t set download={true} but at that point the custom filenames will not work with the web component and they will just be called `download.ics`. The filename attribute is ignored in that case.

To me, the calendar icon and the custom filename are great for usability reasons. It looks like there's an [open issue](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/603) for developing a `add to calendar` component.

Here's a screenshot of how it currently displays on VAOS:
![image](https://user-images.githubusercontent.com/587812/202329188-18633bd5-0590-4a44-8140-6c55b26ac1ce.png)

Here's a screenshot when using the `va-link` component:

![image](https://user-images.githubusercontent.com/587812/202329402-87df58a3-1583-453a-8520-c6e1357b5c76.png)


Here's the current [anchor element](https://github.com/department-of-veterans-affairs/vets-website/blob/3716c03f0dd9caabe8e47fba2f9cb0450d3752b6/src/applications/vaos/components/AddToCalendar.jsx#L155).

cc: @outerpress
