### ISSUE TITLE
Research Spike - Define various scenarios for triggering maintenance windows

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13173]
As part of improving user experience during maintenance/performance/errors:
- Define scenarios
    - focus on manual
- establish plan / ways / how we'll handle (or not handle) these scenarios

**Comment by saneshark** [comment]
### Scenarios where we would want to put up a warning banner, but not necessarily bring down any applications:

#### Manually triggered scenarios

- VAMF or VSP are aware of an interruption that could affect performance, but there is no clear estimate of when the service will become 100% stable.

#### Prometheus triggered scenarios

- Errors have exceeded threshold, possibly indicating a service interruption somewhere on the VAMF side.
- Latency has exceeded threshold, possibly indicating slow response times to users. 
- Breakers was recently fired, has since resumed normal operation but adverse issues could still be lingering.

### Scenarios where we would want to put up a warning banner and take down the application for scheduled maintenance:

#### Manually triggered scenarios
- VAMF or VSP has made us aware of a planned maintenance window between X and Y time periods. 

#### Prometheus triggered scenarios

- Breakers is currently fired, some or all VAMF services are currently unavailable for X number of minutes.

**Comment by jbalboni** [comment]
> VAMF or VSP has made us aware of a planned maintenance window between X and Y time periods.
> VAMF or VSP are aware of an interruption that could affect performance, but there is no clear estimate of when the service will become 100% stable.


I think I would tweak these two into 3 scenarios:

- VAMF or VSP has made us aware of a planned maintenance window between X and Y time periods in which the application will be down or significantly degraded for the entire period
- VAMF or VSP has made us aware of a planned maintenance window between X and Y time periods in which our application may be down or degraded for a short amount of time
- VAMF or VSP are aware of an interruption that could affect performance, but there is no clear estimate of when the service will become 100% stable.

We've had windows where the app was fully down during the whole window, and we've also had windows were the app was down for maybe a couple minutes during the hour window.

**Comment by saneshark** [comment]
I've updated based on comments left by Jeff. I think this issue good to close.
