### ISSUE TITLE
Review content updates for Claim Status Tool

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#13228]
## User story
Do a content review of SMEs updates to Claim Status tool to ensure they align with VA.gov tone and styleguide
These content updates are a result of this issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11801

Word doc with SME updates:
[https://app.zenhub.com/files/133843125/d81afc70-f438-4775-ad32-dee75f940a38/download](https://app.zenhub.com/files/133843125/d81afc70-f438-4775-ad32-dee75f940a38/download)

Draft PR for this work: https://github.com/department-of-veterans-affairs/va.gov-team/issues/11801

**Comment by peggygannon** [comment]
@bethpottsVADEPO 

Recommended content updates to the SME changes to Claim Status Tool are listed below. I didn't commit any of my changes, as I thought it best to just do 1 content commit. 

You can see the SME changes in this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/14131/commits/d262f52ac7765a7e1261ba335ec88e7b1047a162

1. Remove period after this sentence: 
To do this, you must complete and return a VA Form 9 within 60 days, **or**

2. Remove period before this sentence: 
3. Fix misspelling of “opt”
You have 60 days from the date on the Statement of the Case to opt in to the new decision review process.

4. Add “that” to this sentence for readability/clarity
You, your legal representative, your health care provider, or VA added new evidence to your appeal and requested “that” VA review it before certifying to the Board, **and/or**

**Beth**, **and/or** is the above sentence in the current online content, so I'm not sure we want to change at this point? What are your thoughts? 


5. Add period after this sentence/link: [opt in to one of the new decision review lanes].


6. Add “that” to this sentence for readability/clarity:
If you return VA Form 9 within 60 days, what happens next depends on whether you also submit new evidence and request “that” VA review it before sending to the Board. 


7. Add “that” to this sentence for readability/clarity:
8. Add acronym for Decision Review Officer (DRO) and then use DRO on 2nd reference: 
If you submit new evidence after the Statement of the Case on {date} **and** request “that” VA review the evidence first, the Decision Review Officer (DRO) will need to write a Supplemental Statement of the Case before sending your case to the Board of Veterans’ Appeals. Otherwise the DRO will send your appeal to the Board. 


9. Change “their” to “its” in this sentence: 
Your review may take longer than the expected 4-5 months because VA needs to correct an error before completing “its” review.

**Comment by bethpottsVADEPO** [comment]
@peggygannon I'm not finished yet, but getting this comment in here so I don't lose what I've done so far! I'll add information about what lines these are one as that'll be helpful to whoever makes the changes.

1. Rewrite as:
If you don’t agree with the Statement of the Case, you can continue your case by taking one of the actions listed below.

**You'll have to take one of these actions within 60 days from the date on the Statement of the Case:**

- Submit VA Form 9 to continue your appeal to the Board of Veterans’ Appeals, **or**
- Opt in to the new decision review process

2. "Take action" alert box: Delete "the" where it says, "Return the VA Form 9 by July 31, 2018..." 

3. "Take action" alert box: Add the word "blank" in the first sentence of the alert: "A blank VA Form 9 was included with your Statement of the Case."

4. "Take action" alert box: Flip the order of the second sentence and incorporate minor edits: "You can continue your appeal to the Board of Veterans' Appeals by submitting this form.

5. "Take action" alert box: When you fill it out, you can also request a hearing with a Veterans Law Judge if you'd like one.

6. After this line: The {aojDescription} sent you a Supplemental Statement of the Case on {formattedSocDate}.
Change "This is because" to "This is because one or both of these is true:"

7. Add "ask" and "to" / change "prior to" to "before" / delete "and/or": 
You, your legal representative, your health care provider, or VA added new evidence to your appeal and asked VA to review it before certifying to the Board.

8. Replace "VA found it had further duty to assist you to develop your appeal" with "VA determined it needed to provide you with more help in developing your appeal" 

9. After this line: You requested a {getHearingType(details.type)} hearing
Change: "When your hearing is scheduled," to "We'll schedule your hearing, and"

10. Lines 1161-1202	Pending SOC
In this sentence, change "lanes" to "options": You can then decide whether to continue your appeal to the Board of Veterans’ Appeals or opt in to one of the new decision review options.

11. Lines 1211-1253	Pending Form 9
In this sentence, delete "a" before "VA Form 9" / change "and request VA review it" to "and ask VA to review it" / add "it" at the end of the sentence before "to the Board":
If you return VA Form 9 within 60 days, what happens next depends on whether you also submit new evidence and ask VA to review it before sending it to the Board.

**Comment by Mottie** [comment]
I'm in the process of implementing the above changes. The only problem I ran into was
@peggygannon's point # 6&ndash;8 seems to clash with @bethpottsVADEPO suggestions in 11&ndash;17; essentially suggesting a change from "request that VA" to "ask VA to".

**Comment by peggygannon** [comment]
hi, @Mottie Yes, thank you! Please go with "ask VA to" as it's more plain language. thank you for catching this.

**Comment by Mottie** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/14131 has been updated with the above suggestions.

**Comment by peggygannon** [comment]
Hi, @Mottie I checked the updated PR. Content updates look good. thx!

**Comment by Mottie** [comment]
@kevinstachura notified me:

> From Fred, regarding the CST appeals items changes:
> "Looks good from what I can tell!"

**Comment by peggygannon** [comment]
thanks, @Mottie Do you think  I close this issue?  or do you anticipate more changes?

**Comment by Mottie** [comment]
Yes, we can close this issue. I just verified this with @kevinstachura.

**Comment by Mottie** [comment]
Thanks Peggy!

Does this ticket include the review of https://github.com/department-of-veterans-affairs/vets-website/pull/14176? Can I go ahead and merge that one too?
