### ISSUE TITLE
[BE] Create BGS CH33 DDEFT Service integration

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#13286]
add controller and service class for the BGS CH33 DDEFT read and update APIs

## Acceptance Criteria

- [ ] Add service class for calling BGS CH33 DDEFT APIs
- [ ] Add controller for BGS CH33 DDEFT read and update APIs
- [ ] Block this work so the endpoints are not accessible before the frontend is ready to start their build

**Comment by Samara-Strauss** [comment]
Since this work won't be accessible to the frontend by the time @lihanli  has completed this work, this work should be **blocked** for security reasons so that no one can access this endpoint before we are ready to surface it in the interface.

@mshea0606 will create an additional ticket needed for Lihan to unblock this code when the frontend is ready to work with it.

**Comment by mshea0606** [comment]
@lihanli  this is good to close right?
