### ISSUE TITLE
STEM: 10203 - Twilio update: DEPO Content review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13509]
## Tasks
[ ] Twilio update - DEPO Content Review
[ ] Prototype update 
[ ] Content doc update

**Comment by ccruzgra** [comment]
Hi @peggygannon We have a content update for our STEM application that we'd appreciate you taking a look at. We've been working on integrating Twilio to allow applicants to opt-in to text message updates for their education benefits. They can opt-in by entering a mobile phone number and then selecting the checkbox below. Trevor Pierce provided feedback to keep the interaction 508-compliant. 

If a user tries to select the checkbox without having entered in a mobile phone number, they see a "background color only" warning alert (https://design.va.gov/components/alertboxes#background-color-only). If they still try to continue without entering a mobile phone number, then they see an error message for the mobile field. 

Here's a screenshot of that functionality in action:
![Screen Shot 2020-09-16 at 9.04.40 AM.png](https://images.zenhubusercontent.com/5b55212f6dabc3393a2dbe50/b391976f-0288-4995-93b4-6dc500ab2a93)

You can view a prototype of the checkbox in context here: https://bahdigital.invisionapp.com/share/FAIAEVUYVKN#/screens/296049096

The updated copy is for the checkbox, the warning alert, and the error message only. If you could please take a look at those items and let us know if we need to update the copy somehow, that would be super helpful. Thank you.

**Comment by peggygannon** [comment]
hi, @ccruzgra Here's recommended content updates. Please let me know if you have any questions. 


{checkbox} I would like to receive text messages from VA about my GI Bill benefits. 

**Note:**Text messages may include status updates or requests to verify school attendance or other GI Bill benefit information. Message and data rates may apply.


{alert}
Since you’ve opted to receive text messages, you need to enter your mobile phone number so we can send updates to your device. 
{end conditional alert}

**Comment by ccruzgra** [comment]
@peggygannon Thanks so much! These suggestions look great.
