### ISSUE TITLE
Related Links missing across VA.gov

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#13501]
## Issue Description
Bug identified at VA.Gov / Tuition Assistance Top-Up page where a faint gray line is showing up at the bottom of each page. It's just under the last line of text and before the line with the date of when it was last updated.

### Tuition Assistance Top-up Page Bug Discovery - Thin Gray Line at Page Bottom
<img width="925" alt="Screen Shot 2020-09-14 at 11 35 16 AM" src="https://user-images.githubusercontent.com/70410912/93119074-69d37780-f67e-11ea-99b9-1f07cccffaf2.png">

### Find VA Forms Screen Shot:

![Screen Shot 2020-09-14 at 12 31 19 PM](https://user-images.githubusercontent.com/70410912/93124065-4ad8e380-f686-11ea-98be-8fb21eb88752.png)

Posting a link to this issue in cms-support for cross-referencing : https://dsva.slack.com/archives/CDHBKAL9W/p1599834440049900

## Front end tasks
- Discover bug issue
- Isolate bug issue and determine total affected pages (scope of issue) 
- Determine appropriate solution (resolution steps)
- Restore appropriate links in support of affected pages. 

## Acceptance Criteria
- [ ] Designer comments on this issue to validates bug 
- [ ] Validate affected pages are rendering correctly 

:link: CMS URL related to my task:
http://preview-prod.vfs.va.gov/preview?nodeId=927

:link: VA.gov URL related to my task:
https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up/

**Comment by MickinSahni** [comment]
Thanks, Brian! Could you add screenshots for the Find VA Forms scenario too?

**Comment by kelsonic** [comment]
Hey @kevwalsh, so it looks like there are 2 problems:

1. Our template for related links is expecting `null` instead of `[]` when there are no related links.
2. All templates are receiving `[]` for related links, even if there should be them.

#1 could be solved by fixing #2, but I can send up a PR for that to make sure it doesn't show that random line when there are no related links.

#2 I've looked at any GraphQL changes we've made over the past few weeks and it doesn't seem like there's any that affect `fieldRelatedLinks`, could you confirm that they are indeed being exported from the cms properly? I'm going to check out https://prod.cms.va.gov/graphql/explorer right now just to make sure it's not something we're doing with the graphql query 🙂

**Comment by MickinSahni** [comment]
PW Grooming 2020-09-16
- No changes seen to GraphQL so potentially a CMS item to prioritize

**Comment by kelsonic** [comment]
Is this still an issue? 
![image](https://user-images.githubusercontent.com/12773166/125515581-6ccecfcd-ff20-4242-8f9e-ed0bcfdd19a7.png)

CC @brianalloyd

**Comment by brianalloyd** [comment]
Work is completed, closing out now in support.  @MarciMcGuireGCIO if this problem remains, perhaps your team can work details on your board outside of this ticket.  Let me know if any questions exist.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @brianalloyd .  This issue is not ringing a bell for me, but I'll keep an eye out of I see anything.
