### ISSUE TITLE
CT Site Search: 107 Content - DEPO Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#13540]
## Tasks
- [x] DEPO Content Review  
- [x] Content doc update

**Comment by ccruzgra** [comment]
@peggygannon This content concerns an update to the housing question learn more modal for the Comparison Tool (https://www.va.gov/gi-bill-comparison-tool/). The housing question is found on the landing page, search results, and school profile pages. Currently, the question is "How do you want to take classes?", but we observed during many testing sessions that users interpret the question differently than how it actually behaves. They think the question will filter their results for online or in person schools only, depending on what they selected, when in actuality, it only updates the housing calculation on the school card. We've updated the question to "Will you be taking any classes in person?" (See a prototype with the question here: https://bahdigital.invisionapp.com/share/PVIAEVAXHK7#/screens). To go with the updated question and also to incorporate some copy for COVID, the learn more for it needed an update. 

This is the new Learn more modal content:

> Where you take classes determines your housing allowance
> 
> Under the GI Bill you’re eligible to receive a monthly housing allowance whether you take classes in-person or online. We calculate the monthly housing allowance based on where you take those classes.
> 
> If you're using Post-9/11 GI Bill benefits to take at least 1 in-person class, your housing allowance will be based on where you do most of your coursework. If you're taking distance-learning courses only, we’ll pay you a housing allowance based on 50% of the national average.
> 
> Through Dec. 21, 2020, current and new students can receive in-person rates if the school converted their approved program from in-person to online training due to COVID-19.
> 
> (View the current housing allowance payment rates)[https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp?_ga=2.144591223.39405460.1542131207-1582256389.1508352376].
> 
> { end modal }

If you could please provide any feedback you may have on the updated modal copy, we'd appreciate it. Thank you!

**Comment by peggygannon** [comment]
Hi, @ccruzgra Here are recommended content edits for the housing allowance modal. Let me know if you have any questions. thx. 

**Your housing allowance is determined by where you take classes**
 
Under the GI Bill you’re eligible to receive a monthly housing allowance. We calculate this monthly housing allowance based where you take classes. 
If you use Post-9/11 GI Bill benefits to take at least 1 in-person class, your housing allowance is based on where you do most of your coursework. If you take distance-learning courses only, your housing allowance is based on 50% of the national average.
Through Dec. 21, 2020, current and new students can receive in-person allowance rates if their school’s approved program changed from in-person to online learning due to COVID-19.

(View the current housing allowance payment rates)[https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp?_ga=2.144591223.39405460.1542131207-1582256389.1508352376].

**Comment by amyknox** [comment]
Thanks @peggygannon . These updates look good. 

@ccruzgra - could you add this to the prototype?

**Comment by ccruzgra** [comment]
Thanks so much for the feedback, @peggygannon!  

@amyknox I can add this after switching "distance-learning" to "online":

> **Your housing allowance is determined by where you take classes**
> 
> Under the GI Bill you’re eligible to receive a monthly housing allowance. We calculate this monthly housing allowance based where you take classes.
> If you use Post-9/11 GI Bill benefits to take at least 1 in-person class, your housing allowance is based on where you do most of your coursework. If you take online courses only, your housing allowance is based on 50% of the national average.
> Through Dec. 21, 2020, current and new students can receive in-person allowance rates if their school’s approved program changed from in-person to online learning due to COVID-19.
> 
> (View the current housing allowance payment rates)[https://www.benefits.va.gov/gibill/resources/benefits_resources/rate_tables.asp?_ga=2.144591223.39405460.1542131207-1582256389.1508352376].
