### ISSUE TITLE
Proposal - Technical Strategy/recommendation - CC provider selection

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#13602]
Based on initial discover and potential technical constraints for implementing Community Care Provider Selection feature (see epic here), we need to define a technical path forward to recommend to various VA teams. 

Recap of technical problems here -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/cc-provider-selection.md

### Next steps:
- [ ] Get latest performance metrics from Facility Locator team
- [ ] Draft technical proposal where we potentially get a snapshot of PPMS stored in VAMF / EAS architecture via CCSP (Community Care Service Provider)
    - Pro: allows us to minimize dependencies and have some control for what we need
    - Pro: given the strategy for VAMF/EAS (specifically CCSP in EAS) which is focusing on community care data - makes sense this would live within that framework and also repurpose FHIR spec
    - Pro: by taking the VAMF/EAS approach, we could (theoretically) improve multiple systems across the VA (VAOS, HSRM, Facility Locator)
    - Con: This approach is definitely long term which doesn't give us immediate option for solving for this user/org problem today
- [ ] Design mockup of 'desired' experience to supplement point about needing proper data to enable implementation (GH issue for this here)

**Comment by saneshark** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/request-for-comment/RFC-2020-10-01-CommunityCare-Provider-Selection.md

**Comment by lenaecb** [comment]
@saneshark - what remains to get us to a point that we tech strategy to work from for PMMS (which is a requirement for our community care provider selection feature)?

With updates coming in Nov for PPMS, is your POV that for our needs, we move forward vets-api PPMS integration? I'd like for us to have a plan fo attack by end of this sprint (Sprint 28).

**Comment by lenaecb** [comment]
@saneshark - based on our conversation last week, sounds like we have a plan. 
- Outline the current options for moving forward with existing knowns/unknowns for PPMS (consider adding that to this doc if you think fitting)
- Provide high level overview of these options and our recommendation to Lauren
- as part of that recommendation also make sure Lauren knows we need to engage with Dr. Greenstone on getting access to the PPMS data dump they are using for Cerner

Can we try and provide this to her (Lauren A.) by tomorrow so we can get the ball rolling with Dr. G?

cc: @laurenernest

**Comment by saneshark** [comment]
MVP:

Use existing Facilities API with some added work needed:

1. Facilities API to support querying by Lat/Long. This is already a priority item for the Facilities Team and will be worked on as part of upcoming sprint.
2. Taxonomy Mapping! I did a little bit of research around this problem, and it's captured in exhaustive detail here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/notes/CCProvider.md There is still some discovery work ahead, but for purposes of an MVP and maybe a phased rollout, I think we can come up with an intuitive mapping of our 6 CC Types to the 240+ PPMS specialty codes. 
3. In addition I think we want to look at adding Loki logging, there might be some minor PII concern that we'd want evaluated for ATO, I don't think it will be a problem really (but logging Lat/Long) even without veteran identity could be considered PII.
4. Pagination is non existent on the PPMS side, but vets-api does depend on it. We might want to look at a caching mechanism with our own pagination layered over top of that. This isn't critical to launching an MVP, but will make the developer experience with working with this data a little better and more performant.

Only #1 and #2 are critical to successful launch of an MVP and both efforts are either underway or discovery efforts to learn more about them are underway. 

There are still some outstanding questions I would like answered by PPMS to better understand their data. They have 6M records. Of these 6 Million records, how many of them have the generic "rollup code" specialty. How should we characterize the providers that don't have this generic specialty? Are they just smaller facilities? Is it fair for us to exclude them in our results shown to veterans simply because we are limited in how we can query by 4 specialty codes only? I don't know how to wrap my head around this problem without knowing more about the data.

As a longer term proposal. I do think we would want to discuss what Dr. Greenstone alluded to on PI Planning. He mentioned that Cerner is getting a data dump of their 6 Million records. If we could get a similar data dump we might want to just build our own service layer that could be optimized for the type of querying we do. There are a number of different geo-location algorithms out there, some perhaps more suitable for the "bounding box" style search we do as opposed to the radius based search that PPMS supports. Similarly we could build a mapping across taxonomies with join tables and such, essentially offering a service that would be scalable and more performant than what PPMS offers out of the box for us to consume. We could build a service that is optimized for our needs as well as the needs of some our partners such as VAOS backend, HSRM, Cerner, etc.

**Comment by saneshark** [comment]
Executive Summary / High Level Path Forward

The research and discovery related to this effort is linked or referenced in some of the documents available above.

## MVP 

For the sake of the MVP we can continue to use the Facilities API pending some improvements that are already underway. Most of the challenges identified before are already captured as part of their work, including de-duplication as well as efforts related to taxonomy mapping.

1. Facilities to support Lat/Long + radius querying as opposed to mailing address + bounding box.
2. Additional Logging 

The Facilities API already supports querying by PPMS specialty code. While it is limited to only 4 specialty codes at a time, this is a limitation on PPMS that is unlikely to be addressed. Continued research on taxonomy mappings will allow us to identify the optimal mapping for our 6 CC Types of Care to the 240+ on the PPMS side. 

## Medium Term

We will continue to do research based on our phased rollout strategy with veterans and research with schedulers handling these 
requests, coupled with logging data we collect we will have available to iterate and improve. We will share this research transparently with Facilities and PPMS teams.

## Longer Term

I'd still like for us to evaluate the possibility of a stand-alone service like the one we talked about Patrick Bateman. During PI Planning Dr. G mentioned that PPMS is already sending a data dump for Cerner. Something like this would allow us to build our own relational database optimized for the type of querying we wish to do. It would allow us to have taxonomy mapping across all the different health space domains that have unique taxonomies and position us for the convergence of these domains in months and years ahead.

**Comment by saneshark** [comment]
@lalexanderson-dsva @batemapf tagging you here for awareness and feedback! Thanks
