### ISSUE TITLE
Send simple test data over the API and receive a response 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1360]
## User Story
As a Veteran, I want to ensure the information I entered via an online submission method has been processed so that I can ensure my request has been received for review.   

## Goal
Send simple test data over the API and receive a response 

## Acceptance Criteria
  - [ ] Send test data over the API
  - [ ] Receive a response after sending test data over the API

## Definition of Done
- [ ] **Response received following a data test over the API

**Comment by SMLuthi** [comment]
I have setup a development Api key and have access to the lighthouse development environment. I've attempted some test calls vs their Decision Review API but am currently getting back auth issues. I've reached out and this due to issues on their end. So for the time being this is blocked until the issues are resolved on their end.

**Comment by YanaRoy** [comment]
9/19 meeting: API team is working on resolving their issues that are preventing @SMLuthi from completing this task. Working on issues endpoint; UAT.
