### ISSUE TITLE
Establish Higher Level Review Application Architecture 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1361]
## Story
Identify the architectural needs of the Higher Level Review process as it relates to Form 526

## Goal
Talk through the application architecture with the team that built 526, and decide whether this app should extend that app or live entirely separately 

## Acceptance Criteria
  - [ ] Identify whether Higher Level Review should be a part of Form 526
  - [ ] Compare Form 526 architecture with the needs of Higher Level Review process
  - [ ] Identify the architectural similarities of Higher Level Review and Form 526
  - [ ] Identify benefits of stand alone app vs extension of an existing app

## Definition of Done
- [ ] **Decision made on architecture of HLR as a stand alone app or extension of Form 526**

**Comment by SMLuthi** [comment]
As I am, ironically, the only one still here from the team that built the original 526 I can take a stab at answering the AC for this ticket.

- Personally, I believe the HLR should separate from the 526 flow. HLR does not require a veteran to have an ITF which would make it difficult to integrate into the preexisting 526 flow since we do a lot of automated work to gather and create ITF's for the veteran from the get go. Furthermore, the HLR is a totally separate paper form from the 21-526ez and I believe its worth keeping these digital forms just as separate. This is speaking strictly from a FE ignorant point of view... there may be reasons there for integrating the form INTO the 526 flow but someone like @cvalarida or @hinzed1127 would be better suited to answer that question.

- Architecturally speaking, the process would be very similar to the 526 process but much simpler in scope. From a high end view I would recommend we take advantage of the SiP (save in progress) feature, use a json schema (stored in vets-json-schema repo), create a saved claim (? this may be overkill but there may be worth in keeping a record of the higher level reviews we process), and handle the submission process (though we wouldnt need to feed this to an async job unless the lighthouse api has a long response time).

**Comment by cvalarida** [comment]
I don't know what the Higher Level Review is, but if it's not a part of the 526 or an ancillary form, I think it should be separate. Like @SMLuthi said, the 526 form does a lot of work that's pretty specific to the 526. It's far and away the most complicated form on VA.gov to date. From a front end perspective, keeping them separate would:
- Reduce the burden on the engineers; they wouldn't have to figure out where to "jack in" the new functionality (did I mention it's a complicated form?)
- ~Reduce~ Not increase the complexity of the 526, which is better for maintenance
- Not conflate two (potentially?) separate processes for the Veteran
  - Again, I don't know what HLR is, so maybe separating them would be clearer to the Veteran, but if they're already separate on paper, I'd default to keeping them separate without a good reason
- Allow the HLR to do exactly what it needs to without all the overhead that is the 526
  - There are kind of specific requirements that a Veteran has to meet in order to even _start_ filling the form out
  - See the `File a disability compensation claim` wizard at https://www.va.gov/disability/how-to-file-claim/

**Comment by jenniferlee-dsva** [comment]
FYI - I think Carola Ponce and Steve Kovacs would be able to give you information about HLR. HLRs are not claims per se; they are one of the 3 kinds of 'appeals' or asking for a review of a VA decision on the original claim. 

Our site has some info here:
https://www.va.gov/decision-reviews/   and
https://www.va.gov/decision-reviews/higher-level-review/ 

HLRs also cover other kinds of claims, not just disability. @carolaponce and @steve-gov I think are working on an MVP HLR tool. (Sorry if you already knew this!)

**Comment by carolaponce** [comment]
Work in progress documentation:
https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Global/Decision%20Reviews

**Comment by hinzed1127** [comment]
Adding to @cvalarida 's comments, from the perspective of a front-end engineer who on-boarded to that code pretty much after it had been completed and only made minor updates:
- It's very large and a lot to understand, especially with all the different conditional flows. My suspicion is adding more conditional logic for a completely different thing would be more pain than gain.
- There wouldn't be any performance hits by adding a new form, since it's its own thing.
- Potential redundancies in content/flow probably aren't a big deal, and if it ends up needing its own unique logic in the process of building or later on, adding it to an isolated form would be less cumbersome.

**Comment by aeltarhoni** [comment]
@SMLuthi @ndsprinkle @Mottie

**Comment by steve-gov** [comment]
The (theoretical) Higher Level Review workflow and the Claim for Increase workflow have a lot of things in common -- so much so that we've been saying things like "you know, very much like how 526 does it." (And so much so that Veterans sometimes confused the two things in our research sessions!) This led us to believe they could possibly share some architecture, but it completely makes sense that they don't. They're different apps with different outcomes.
