### ISSUE TITLE
Discovery: Blue Water Navy Veterans Identifiers

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1364]
@markgreenburg commented on [Thu Apr 04 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17772)

---

@markgreenburg commented on [Thu Apr 04 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/17772#issuecomment-479753062)

## Context:
Legislation was recently passed to help Blue Water Navy veterans who served in Vietnam with potential exposure to Agent Orange, under very limiting parameters. This will require further discussion with Paul to properly scope, and might need to get further broken down if we'll need to ask a lot of stuff.

## Story
As a rater, I want to know whether or not the veteran qualifies as a blue water navy veteran with Agent Orange exposure without spending lots of time looking records up manually.

As a veteran, I want to let the VBA know that I was exposed to agent orange in Vietnam as a blue water navy veteran, so that I can get the disability compensation I'm entitled to.

## AC:
- [ ] What is required to qualify as an BWN veteran with AO exposure during Vietnam?
- [ ] How many veterans do we think are affected
- [ ] How do we pass this info to raters? Do we need EVSS service updates?
- [ ] Design / Content: Design flow to qualify / disqualify veterans
- [ ] FE / BE Implement questions and update

**Comment by smoonpeyes** [comment]
@kevinstachura I found some references to this in the old repo: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/ead0fe129bfee6b8e7eaae59d7f4f681a37dec15/Products/Disability/Disability%20526EZ/product/blue_water_navy.md

**Comment by smoonpeyes** [comment]
### What is required to qualify as a Blue Water Navy veteran with Agent Orange exposure during Vietnam?
Veterans who qualify as Blue Water Navy Veterans must have served on a Blue Water Navy vessel offshore of the Republic of Vietnam, or on another U.S. Navy or Coast Guard ship operating in the coastal waterways of Vietnam, between January 9, 1962, and May 7, 1975.

**To receive disability benefits, the following must be true:**
The Veteran has an [illness we believe is caused by Agent Orange (called a presumptive disease)](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/agent-orange/related-diseases/)

**And at least one of these must also be true. The Veteran's military record must show that between January 9, 1962, and May 7, 1975, and the Veteran:**

* Was aboard a U.S. military vessel that operated in the inland waterways of Vietnam, or

* Served on a vessel not more than 12 nautical miles seaward from the demarcation line of the waters of Vietnam and Cambodia (as detailed in Public Law 116-23, the Blue Water Navy Vietnam Veterans Act of 2019)

#### How many veterans do we think are affected?
* An estimated 420,000 to 560,000 Vietnam-era Veterans may be considered Blue Water Navy Veterans. [Source: https://www.blogs.va.gov/VAntage/62832/va-extends-agent-orange-presumption-blue-water-navy-veterans/](https://www.blogs.va.gov/VAntage/62832/va-extends-agent-orange-presumption-blue-water-navy-veterans/)

**Comment by YanaRoy** [comment]
This scenario will be covered under the Supplement Claims Decision Review effort. Closing ticket.
