### ISSUE TITLE
Consolidate & improve transformer developer documentation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#13651]
### User Story 
As a VFS, VSP, or CMS team member who is involved in creating transformers, I need to know how to complete this task and what some common issues are that I might encounter, so that I can support content writers in publishing content from the VA.gov CMS.

### Details
Docs on transformers are currently dispersed and insufficient:

* [CMS export transformation overview](https://docs.google.com/document/d/1ysXf6nqlpq6e2c8biRXJWzlWjSWCbJbWU8Y9xl5fIJY/edit#heading=h.hi0euqwbapx)
* [Creating a CMS bundle transformer](https://docs.google.com/document/d/1WaLK1Lx3RcVlG56ssnb0LEs0Exq0iC7f9J4tIM1CE-w/edit#heading=h.s8rl0jtr6v3c)
* [CMS Export Content Model Transformation Overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/cms-integration)

How might we consolidate and improve these docs so that developers can learn about transformers & begin building & troubleshooting them with minimal manual support?

**Comment by Clark-W-Griswold** [comment]
Creating a CMS bundle transfomer
Lot's of build steps fail.

"openAPI schema bundle info" step is not ready yet.

"Assemble your bundle information" is not a thing yet. Do not use.

HIDDEN DOCUMENTATION!!1
we search the bundle using rg
like rg health_care_region_page $(find -type f -name 'node*')
to search for a node type and health_care_region_page bundle

docs are confusing.. we should wrap this with a common command that only executes the commands that work and are needed to get up and running. something like `make dev`.
More here:
https://www.peak6.com/stories/blog/simplicity-in-software-design-start-with-the-right-tooling/



CMS export doc
Terminology: is confusing. Maybe a visual diagram to show the relations?

Naming conventions: what’s a machine name and how does it relate to transformers?

Follow the node: screen shots are blurry. Should we get a better quality screen shot added? 
Why does the content end up with that URL? 
“Note that the content might not match the above, since it might be edited in the future.” What does this mean?

Documentation is not junior dev friendly.

**Comment by meganhkelley** [comment]
From Paul (VSA): https://docs.google.com/document/d/15azudqq43ijJkpBkTA0ZUGIbNh0M_Q9A8pa_jizVVPQ/edit?ts=5f639293#

**Comment by U-DON** [comment]
First draft of the [Transformers Development Guide](https://vfs.atlassian.net/wiki/spaces/VP/pages/637567205/Transformers+Development+Guide) has been published.

**Comment by meganhkelley** [comment]
No longer relevant due to pivot away from CMS export, documented in #20165
