### ISSUE TITLE
Javascript error in new disabilities/add

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1365]
@bshyong commented on [Fri Jun 07 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18892)

**Specs:**
- Device: Desktop
- Browser: Chrome, IE

The following error gets thrown from time to time on various URLs within 526, seemingly when trying to continue on the next page after adding new disabilities /disability/file-disability-claim-form-21-526ez/new-disabilities

`form_526_v1 / form_526_v2: capitalizeEachWord requires 'name' argument of type 'string' but got undefined`

http://sentry.vetsgov-internal/vets-gov/website-production/issues/54713/events/049ab3a708804227a66cc2707e47e163/

**Comment by ndsprinkle** [comment]
@YanaRoy It seems that the logging of this error message was removed in this pull request: https://github.com/department-of-veterans-affairs/vets-website/pull/10288

Should this story be changed to be about re-implementing this error message but only have it log at a more appropriate rate? Based on that PR, it sounds like the message was removed because it was logging a whole bunch.

**Comment by YanaRoy** [comment]
@ndsprinkle yes, it appears that the solution was temporary. Your recommendation sounds like the correct approach.

**Comment by ndsprinkle** [comment]
I moved this to Review/QA on the VSP board, but it looks like there is no column named that on the VFT board. Am I only supposed to be changing the column on one of the boards?

This is the PR for this story: https://github.com/department-of-veterans-affairs/vets-website/pull/10694

Is there a way for me to link the PR and this story?
