### ISSUE TITLE
STEM Form: too much space between breadcrumbs

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#13717]
The Introduction page for the 10203 form has breadcrumb links at the top so that the user has the ability to return to a page they were on previously. For this form specifically, the links are so long that they wrap. There is too much space between the two breadcrumb lines on screens above 767px. The spacing should match that of screens 767px wide and below.

### Steps to reproduce
1. Access the [Stem form intro page](https://staging.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction) using a screen over 767px wide

## Actual Behavior
Too much space between lines
![Screen Shot 2020-09-18 at 12.33.30 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/97865b69-4819-4a6e-843c-8b3a0fe3f7d7)

## Expected behavior
Should match the spacing of smaller screens
![Screen Shot 2020-09-18 at 12.33.22 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/dab9ad68-9421-4b5c-9d3c-7faaf29f800a)

## Alternative potential solution (enhancement)
Match the behavior used for mobile devices
![Screen Shot 2020-09-18 at 12.41.25 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/394ff6a0-1fea-4812-aec9-808b5549554a)

**Comment by amyknox** [comment]
@mnorthuis - Our team is having some issues with the updated breadcrumbs for the STEM application intro page.  Could you check this out? Wondering if there's DEPO guidance on using a mobile breadcrumb implementation if/when they need to wrap?

**Comment by ccruzgra** [comment]
@amyknox Thinking it'd be helpful to have some guidance on the recommended length for breadcrumbs, too, since users should be able to quickly read and scan the breadcrumb to help them navigate. Something like "Edith Nourse Rogers STEM Scholarship" could be condensed to "Rogers STEM Scholarship", for example.

**Comment by mnorthuis** [comment]
It looks like the breadcrumb vertical spacing issue is a global issue when I look at other examples where the breadcrumb may wrap on a smaller screen.  

When a page has a full proper name in it, its hard to control length, especially when it is a scenario where the name is legally established - we have similar issues in the VAMC experience.   Some thoughts: 
- You could look at shortening the last component of the breadcrumb to just "Apply for scholarship" but not sure if that will entirely help.   
- "Other VA education benefits" should not be shortened since it does need to be clear that its not just other education benefits, its other benefits that specifically VA offers.
- If we can shorten the breadcrumb component for the static page (i.e. shorten the name reference), we should have a conversation with the public websites team, as that will impact their page as well as potentially the left nav label. 

FWIW, the IA structure of the education area is not ideal and has been a challenge to work with due to the sheer amount of content and number of different benefits available.  Someday I would like to restructure the area and am working on a few things that may lead to that.  But that will not help with this in the near term.

**Comment by amyknox** [comment]
@mnorthuis - if we trim the trimmable breadcrumb components, it's still wrapping at 858 px.  (screenshot below)

Are you aware whether the other instances across VA.gov where breadcrumbs are wrapping, are they going with the odd vertical spacing or are the teams working a custom fix? 

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/7eb01c3e-af5d-4bf4-bda5-68861c8330a5)

**Comment by mnorthuis** [comment]
Sorry @amyknox I was out last week.  I am not sure if this is a known issue or not.

**Comment by amyknox** [comment]
Got it, @mnorthuis - I connected with Chris Valarida on VFS slack who's taking it on (per the design system & tools-fe tags added late last week).

**Comment by GnatalieH** [comment]
> @GnatalieH , would you review and respond? Thanks!

Yes. @mnorthuis CCing you because this ticket points out some issues with Breadcrumbs. I'll put a meeting on the calendar this week for us to discuss.

**Comment by cvalarida** [comment]
We should be able to, yeah. :+1:  We can put this on our backlog.
