### ISSUE TITLE
UAT: PDF link or file broken - 10-0137 form page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#13758]
## UAT: PDF link or file broken - 10-0137 form page

On this page https://www.va.gov/find-forms/about-form-10-0137/ when you click on the download link for form 10-0137, the stakeholder reports that he cannot open the file. 

**I've tried to recreate the step and here's what happened - using IE:**

1. I was able to download and save the form okay. (Screenshot 1).
2. When I then tried to open the downloaded PDF, I got an error message saying that the file is damaged or not supported. (Screenshot 2). 

Is this a FE bug that we can resolve? It sounds like it's a file problem but then I"m wondering why our 'invalid form' error message didn't surface. 

**screenshot 1:**   
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/89e8706b-67a2-43a1-b340-1b72910d6af8)
 

**screenshot 2:**
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/20e4ffa3-f461-44a8-8844-70320804401c)

**ETA:**
We should resolve this before removing basic auth (post batch 2 ).

**Comment by ncksllvn** [comment]
The "invalid form" message is surfaced only when a file does not exist at the PDF's specified location - basically, that page `va.gov/sample.pdf` has to result in a 404 Not Found. In this case, a file was found, and that's all our tool knows. It has no idea if the file is corrupted or if the user's PDF reader will be able to read it successfully.

Corrupted files will need to be fixed by a forms manager that can fix the damaged PDF and then re-upload it to the server. However, just now I was able to download this file and then open it using Chrome to view it. Is it possible that this was repaired between when this ticket was opened and now?

**Comment by MickinSahni** [comment]
@jenniferlee-dsva to let forms managers know this likely isn't a CMS or FE issue

**Comment by jenniferlee-dsva** [comment]
I've shared this feedback with Brian McCarthy.
