### ISSUE TITLE
Document Login Flows

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#13782]
## User Story

As a member of the mobile app team, or VA at large, I want to understand what type of users are allowed in VA's mobile app.

## Checklist

- [ ] Flows are documented in repo

- [ ] Significant decisions doc is updated with flows and explanation of why this decision was made, who approved it, etc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/significant%20decisions.md

**Comment by srmyers17** [comment]
- Login credentials for DS Logon + ID.me
- Documenting all the endpoints in API documentation
- Mostly done documenting the LOA 1 - LOA 3 permutations 
- Need to determine GFE acesss

**Comment by srmyers17** [comment]
hey @lexicalninja + @bessgreen - can you remind me why this is blocked? What can I do to help unblock it?

**Comment by lexicalninja** [comment]
adding @steve-gov for MHV

Steve, if you can test the following things and just post some screen shots here of what happens I can round out the log in work for the app. 

If you can go to this repo: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mhv-lower-env-test-accounts.md

In there, there are three INT user accounts at the bottom that should work on the Access VA int site here:  https://int.eauth.va.gov/accessva/?cspSelectFor=oauth.VAMobile


What I am looking for is screen shots of what each type of user sees when they log in for each type: 

- [ ] BASIC
- [ ] ADVANCED
- [ ] PREMIUM

For the Basic and Advanced I would like to know if it prompts for immediate uplevel or if something else happens. 
For premium my assumption is that it just works and logs in, but if something else happens I would like to know. 

If it succeeds you should see this error: 
![image](https://user-images.githubusercontent.com/7376126/96759188-51512e00-139d-11eb-8fa7-a45491fdade8.png)

That just means that we sent a bad URL because we aren't sending our secrets right now. If we need to get more granular we can share the url with all the params including the secret later. My guess is that this should be able to show us any errors, though. 

I think this should be it to start with. Let me know if you have questions or any issues pop up.

**Comment by steve-gov** [comment]
![5B296BAA-6A38-4EB0-A3EB-4FF48B766F34](https://user-images.githubusercontent.com/25468689/96799152-5327eb00-13b7-11eb-8c6c-6eb835ecbe43.png)

https://mhv-intb.myhealth.va.gov/html/portal/saml/sso_error.jsp

BASIC account results in the above screenshot at the above URL

**Comment by steve-gov** [comment]
ADVANCE account exactly the same

**Comment by steve-gov** [comment]
PREMIUM account lands on https://int.eauth.va.gov/accessva/#forVeterans

![EB9FA0A0-4C4D-474A-BEE3-FCC3B4570DFF](https://user-images.githubusercontent.com/25468689/96799574-4c4da800-13b8-11eb-92a9-eac89fcef7c0.png)

![9A66A1A2-4B78-438A-ACE9-F387CF588FD2](https://user-images.githubusercontent.com/25468689/96799576-4d7ed500-13b8-11eb-9615-ec8bb72ac613.png)

**Comment by srmyers17** [comment]
- Integration is moved into SQA, Patrick can use this to see if he can see MHV logins

**Comment by srmyers17** [comment]
- CAG access and GFE needed + android studio or X code
