### ISSUE TITLE
[Design] Research Plan for Usability Testing of EDU Direct Deposit

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#13807]
## Goal
We want to put the feature we have worked on in front of real users to ensure that we have provided an improvement over the legacy digital experience.

## Considerations 
- [Previous Research Plans used](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-research-plan.md)
- [General VSA eBenefits Research Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/design/vsa-research-process.md)
- Testing will be task-based
- There are several workflows that need to be looked at as well as a few hypotheses that need to be validated.

## Task
- Document a research plan to include ([previous](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/discovery/discovery-research-plan.md)):
  - Research method (moderated user interviews)
  - Participants & Recruitment
  - Timeframe
  - Team Availability
  - Roles (include emails)
  - Seek review before implementation
  - Incorporate feedback and revise as required
  
## Acceptance Criteria
- [ ] Research Plan has been started for later review by [Lauren Alexanderson in Recruiting](https://dsva.slack.com/team/U772MC9BQ) ([email](mailto:lauren.alexanderson@va.gov)) and Shawna

**Comment by sporeboy** [comment]
Research plan templated-out here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing/dd-edu-research-plan.md

**Comment by sporeboy** [comment]
Near-final draft available here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/direct-deposit/edu-direct-deposit

Draft will be finalized when the convo guide is complete.

**Comment by mshea0606** [comment]
[Direct Deposit for Edu - Research Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/usability-testing/dd-edu-research-plan.md)

**Comment by Samara-Strauss** [comment]
# Research plan feedback

## Guiding questions

- **Where on VA.gov do users expect to find direct deposit (DD) information?** This is great. It's probably already on your radar, but this should include the content page, so we can gauge how people might navigate from logged out > logged in. 

## Hypotheses

- **Users may have some difficulty locating their direct deposit information** They will. They get confused because it's not on the homepage. I'll be interested to see if anything has improved since removing the account page and since the profile 2.0 redesign, but they'll probably still get confused because this is not part of the top 20 tasks.

## Methods

- **The user will be given a test account password and email, and the participant will log in** Two things on this:
  - We need to use a prototype because the new direct deposit functionality will not be built in staging before testing
  - We *could* use the real website or staging to see how people would navigate to direct deposit, then switch to the prototype to test the Edu functionality. However, to the best of my knowledge, **we should not be sharing staging user info with research participants**. In the past, I've gotten around this by signing into staging and then sharing keyboard/mouse controls with participants so they can use the site on my screen without needing to share staging credentials.

## Participants and recruitment

- **At least one person who lives in a rural or remote area; At least one person who lives in a major metropolitan area** This came up with the My VA research plan, but I don't think this will make a big difference in test results or making sure the results are representative. Do you feel strongly about leaving this in?

Otherwise, this looks great!

**Comment by sporeboy** [comment]
@Samara-Strauss  I'll re-write the research plan around a prototype. So like you say above, we would have them click around on VA.gov then switch to a link to the prototype.

Regarding rural participants, I don't have strong feelings about including that group, but it seems we get a **lot** of urban, educated people. Maybe we leave it, but don't make it mandatory for Perigean.

**Comment by sporeboy** [comment]
Updates made! Dates will be added after usability prep feedback is reviewed.

**Comment by Samara-Strauss** [comment]
Great, thank you!!

**Comment by Samara-Strauss** [comment]
And updates look good! Closing, but feel free to reopen if needed.
