### ISSUE TITLE
[Design] MyVA Dashboard initial explorations: Conversation Guide

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#13926]
## Background

Epic #13924

This conversation guide is for the round of research we will be doing on the initial dashboard explorations we are working on in  #15115.

## Tasks

- [ ] Create conversation guide
- [ ] Review with Samara and Matt

**Comment by tressaellen** [comment]
Here is the [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research/MyVA-conversation-guide.md). It's not quite ready for review - but I'll ping here when it is.

**Comment by Samara-Strauss** [comment]
# Convo guide feedback

## Warm up questions

- I don't think we need to ask where they live because I don't think this will affect the results.
- People will probably not know what the "My VA" page is by name. You'd be better off by showing them the page and asking them if they've ever used it.
- To veterans, there is no difference between receiving benefits or health care (even though those are silo'd within the VA). You can probably just ask this as one question. Also, be careful because sometimes people don't mention everything at first, and then it will come up later that they have a disability rating or receive health care or used a VA home loan or something. Just be sure to listen out for this kind of stuff and make note of it!

## Prototype A: Updates up top

### First task: Overview and update
- **Go ahead and scroll through this page and walk me through your thoughts.** This is fine, and we should certainly get an overview of their thoughts at the beginning, but we should also ask people to talk through what they are looking at individually for each section so we can get better details/thoughts.
- **If you clicked on the disability rating, where would you expect that to go?** This is fine, but we should also ask them to talk through what they are looking at. I want to know if people understand this is their overall rating, or if that's not clear.
- **If you were looking for personal updates, where would you expect those to be?** What are personal updates? What does this mean? We need to be careful not to use language that isn't well defined.
- **Okay, now we are going to take a look at the updates section.** Can we start this section with something like, "Let's look a at the Updates section: can you tell me what you're looking at here?" We've moved right into super usability-focused questions right away. I want to know if participants even understand what they are looking at in the first place.
- For updates, can we also ask something like, "What kind of updates would be helpful to you?" 

### Second task: Claims scenario

- This is great. One request: when we draw their attention to the claims section, can we please add a question along the lines of "Now let's look at the Claims section. Can you describe to me what you are looking at?"
- Also, we might want to ask outright if something is missing if they don't directly answer that when you ask "what would you expect to see in this section?"

### Third task: Health care scenario

- Like above, once we draw their attention to the health care section, can we add a question to assess their overall first impression/understanding? "Now let's look at the health care section. Can you describe to me what you are looking at?"
- **Does the overall layout of the healthcare section makes sense to you?** I don't think people will understand what "overall layout" means. What are we actually trying to assess here? The objective of this question is unclear.
- I think the first or second question after gathering their initial impressions should be the same question you asked in the claims section — "What information would you expect to see related to your health care?" We need to be careful about how we evaluate if something is missing in this section or not. If you ask people if they want to add something, they'll probably say yes, but do they need it? At least starting with an open-ended question about expectations will start participants on a neutral ground instead of priming them that something might be missing or need to be added.
- That being said, I do think it's fine after assessing initial expectations to ask if something is missing or needs to be added.
- Why did you ask about expectations around prescriptions, but not secure messages? 
- Also, we should be careful in assessing whether they really need more information in this section or not. Idk how to make this clear, but it needs to be clear that we're linking them off to sections to manage claims/prescriptions/appointments/messages and they do not need to manage those entirely from this page. I'm worried people will say they need a ton more information because they don't understand that this page is meant to be an overview and not the place where they should actually refill a prescription, send a message, etc.

### Fourth task: Benefit applications

- **What information is the most important to see about your benefits?** I would change "benefits" to "benefit applications" since that drastically changes the meaning of the question, and since this section isn't mean to show other information about benefits beyond applications and links to learn more about VA benefits.

## Protoype B

### First task: Overview

- Same feedback as Prototype A above.
- **What are your thoughts about finding updates on this page?** This is confusing and I don't think it will be clear to veterans. What is the objective of this question?
- **Go ahead and click on claims and appeals.** These questions feel like they will be redundant since you're going to do a deeper dive into each section, so I would remove them. If you decide to leave them, I would remove "Was it easy or hard to understand your updates?" because "updates" is internal lingo and they won't know what you're asking about, and I would remove or clarify "Is there anything that you would add or change about this section?" because it's not clear what section you are talking about — the whole page? One section?

### Second task: Claims scenario

- **If they look for their claims in progress in the updates section** and **If they look for their claims in progress in the claims section**: I am confused, because there is no "updates" section in the second prototype. It's all one section.
- Same feedback as prototype A.

### Third Task: Health care

- Same as above — really confused by the "updates" section prompts since there is no "updates" section in this prototype. All updates are in the same section.
- Same feedback as prototype A.

### Fourth task: Benefits

- Just realized this is the same between the two prototypes, so we probably don't really need to evaluate it twice. I think we can skip this section for whatever prototype is shown second.

## Comparison

- **Which overall page layout makes more sense to you? Why?** We shouldn't be using internal lingo like "layout" with veterans. What are you trying to assess here?
- **Is this a page that you would be interested in using?** This is leading ("interested in using"). Can we clean this up to something like "Do you think you would or would not use this page when you log in to VA.gov? Why?" If the answer is no, we should follow up with "what would make this page more useful to you?"

## General thoughts

- Overall, I really appreciate how you noted what questions to ask/not to ask depending if the prototype is first or second. I thought that worked out really well. I would definitely do a mock session to practice walking through this so you feel comfortable when it comes to real testing.

**Comment by tressaellen** [comment]
Thanks so much for this feedback! I'll start editing this, but just a couple initial thoughts for you.

> Does the overall layout of the healthcare section makes sense to you? I don't think people will understand what "overall layout" means. What are we actually trying to assess here? The objective of this question is unclear.

I'd love your thoughts here - I'm trying to understand if they think the structure of the page is easy to use... Maybe something like "Do you think the healthcare section would be easy or hard to use?"

> Also, we should be careful in assessing whether they really need more information in this section or not. Idk how to make this clear, but it needs to be clear that we're linking them off to sections to manage claims/prescriptions/appointments/messages and they do not need to manage those entirely from this page. I'm worried people will say they need a ton more information because they don't understand that this page is meant to be an overview and not the place where they should actually refill a prescription, send a message, etc.

I'm worried about this too... I think we need to set up the intro better so that users know that they aren't trying to manage anything from this page. I'm thinking maybe in the intro section I can go over what the page is a little bit more and set up the scenarios better. I'll take a swing at it and see if I can get something that works.

> While you can certainly leave in more usability-focused questions (eg. "where do you think clicking link X would take you?"), remember that the goal of this research is to evaluate information balance and IA. If you want to cut this down slightly, I would take out those questions unless you feel like they'd impact how we approach visual design. Once MY VA is fully visually designed, we'll run a proper round of usability testing.

I agree with this as well... I'll sift through the questions and take some of the more usability-focused ones out.

**Comment by Samara-Strauss** [comment]
> I'd love your thoughts here - I'm trying to understand if they think the structure of the page is easy to use... Maybe something like "Do you think the healthcare section would be easy or hard to use?"

I think this is something that we'll be able to evaluate through questions like asking them to describe what they're looking at or find XYZ. If they're having trouble accurately describing what they're seeing, or if they can't find the thing you're asking them to find, you'll know the page/section is hard to use and confusing.

> I'm worried about this too... I think we need to set up the intro better so that users know that they aren't trying to manage anything from this page. I'm thinking maybe in the intro section I can go over what the page is a little bit more and set up the scenarios better. I'll take a swing at it and see if I can get something that works.

Sounds good to me. I do think clarifying this in the intro will help. We also may need to clarify or talk it out with them if they are insisting on seeing a lot of information. We can ask if they understand that they'll be able to manage [prescriptions, messages, claims, etc] on another page, and based on the answer to that, see if that changes what they would want to see on this page. We may just have to feel this one out along the way.

> I agree with this as well... I'll sift through the questions and take some of the more usability-focused ones out.

Sounds good. The one I might leave in is about what they would expect the "Go to all recent updates" link would do. Since this is totally new functionality and not a concept they'd otherwise likely be more familiar with (eg. "View all prescriptions"), that might help us in developing the feature if/when the time comes.

**Comment by tressaellen** [comment]
Okay, i've updated everything if you want to take another look. 

> I am confused, because there is no "updates" section in the second prototype. It's all one section.

We are adding a title in the prototype to this section called 'Claims updates' - it's still an updates section, it's just specific to claims or healthcare.

> Go ahead and scroll through this page and walk me through your thoughts. This is fine, and we should certainly get an overview of their thoughts at the beginning, but we should also ask people to talk through what they are looking at individually for each section so we can get better details/thoughts.

I changed the guide to include this at the beginning as part of the overview, let me know if you think that is a bad idea at all.

**Comment by Samara-Strauss** [comment]
# Convo guide feedback, round 2

## Warm up questions

- I should have thought of this yesterday — can we ask them how they manage their VA benefits online? I'd like to know which sites they use (VA.gov, MHV, eBenefits), how often they go online to manage benefits, and what things they typically do when managing benefits online. This will also probably help give us some context as we move into the convo on My VA.

## Prototype A

### First task: Overview & updates

- **If you were looking for any changes to your information, where would you expect those to be?** I personally find this to be kind of confusing, because I'm kind of like... the whole page? Wouldn't the whole page show me changes? I understand what you're getting at — we want to assess expectations — but I think we can either do that by (a) assessing how the prototype met their expectations (or not) at the end of viewing it, or (b) by keeping this at the beginning, but asking something like "what type of information would you expect to see on this page?"
- **What is not working with these updates?** This is personal preference, so feel free to ignore, but "what is not working" feels like unclear wording to me. I think "What works well? What doesn't work well?" or "Is there anything you would change?" or "Is there anything you find confusing about what you're looking at?" would be clearer to the participant and may give us better information.

## Prototype B

### First task: Overview & updates

- Same as prototype A.

## Comparison

- Can we please add a question here along the lines of "How did these pages meet your expectations? How did these pages not meet your expectations?" We'll probably get this along the way, so we can repeat back to them any expectations they've already stated, but this is a good place to assess overall impressions and see if there's anything we missed.

Otherwise, great! This is looking good. These are minor updates, so after this, we're probably good to call this done and submit to Lauren for recruiting.

**Comment by tressaellen** [comment]
Great! I've made these updates and we're wrapping up everything in invision now. I'll drop in those links and send everything to Lauren!
