### ISSUE TITLE
[Development] BDD: Separation Location No Longer Hardcoded - Suggest Solution

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#13977]
## Issue Description
We took an initial stab at figuring out how to use the sep location API.

This ticket is to continue the convo and likely pull in VSP to discuss a potential solution.  Fallback is to use prefill data. 

Sounds like we need a way to get "dynamic" data available to redux/form system.

Nick will write a list of issues here:
1. Nick reason #1 why this sucks
2. Nick reason #2 why this sucks
3. Nick reason #3 why this sucks

## Acceptance Criteria
- [ ] Either BAM or VSP knows what the "right" solution will be
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
I set up a meeting today for BaM engineers to discuss options before meeting with platform to see if the solution is already possible to implement.

**Comment by ndsprinkle** [comment]
Here are some potential solutions:

For separation location, we could hit the api to load the list in the prefill phase of the form, but this would be going a little bit off the standard form convention as we would have to load the list into the formData object.

For rated disabilities, we pull those during the prefill phase of the form, but this is not performed every time the user loads the form. The solution would be to force the pull every form load and somehow notify the user if any of their rated disabilities have changed in the form wrapper.

Another option for separation location is to pass the list of separation locations into the drop down as a promise, but this would remove any option for validation. The validation would somehow have to happen on the back end. They could either pass it on as entered (if there is a code) or fuzzy match it to the closest from the list if the user did not select an option from the drop down (no code) and rather simply typed free form text.

An even further simplified version of the previous option is to make the field a free form text field with no drop down and then do the code matching on the back end.

**Comment by ndsprinkle** [comment]
I believe this is now solved. 

To give some history, a couple of sprints ago I did successfully hit the api to pull the list of separation locations for the drop down in the BDD flow. The only issue this had was with validation, Because hitting the api returned a promise, there was an issue with timing on the validation on both the separation location page and on the review page. 

After meeting with Chris V from platform, he seemed to think that the autosuggest drop down should be handling the validation itself and enforce that the user select something from the list (unless `freeInput` is marked as true). This confused me and Robin because we thought we had already attempted to implement it this way and that we were required to mark `freeInput` as true to let the user search the list and that we were required to provide our own validation to enforce the list. 

After the meeting and looking into this more, I realized that we are using the standard `AutosuggestField` component which does not include the default validation of the list. To get this validation functionality and other more general functionality from the list, we need to be using [this](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/src/js/definitions/autosuggest.js#L27). That `uiSchema` uses the `AutosuggestField` component, but adds additional functionality that we are unable to implement in our separation location page. I am fairly certain at one point we were using this `uiSchema` instead of the regular component, but I need to dig through PRs to know for certain and to know why we made the switch if we did.

**Comment by ndsprinkle** [comment]
Just like Robin and I remembered, it was my PR but his commit that made this change. See [here](https://github.com/department-of-veterans-affairs/vets-website/pull/13116/commits/419002333e7bc818697765fd9d89c0f80cd19114) for the commit where Robin switched from using `autosuggest.uiSchema` to `AutosuggestField`. Not sure why this change was made, there aren't any obvious clues in either of our commit messages, but I will still look into it a little more. Regardless, it seems that this is our best course of action for a solution to use the api to retrieve the separation locations.

**Comment by ndsprinkle** [comment]
PR is [here](https://github.com/department-of-veterans-affairs/vets-website/pull/14416) that is also attached to a resurrected ticket for implementing the solution. Going to close this ticket as the solution has been determined.
