### ISSUE TITLE
[Content] 526: Draft Email to Veterans Regarding Their PTSD Related In Progress Claim

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14079]
## Issue Description
While doing our UAT testing and the follow-up analysis, we determined that over 3k veterans are impacted by PTSD issues with their claim.  We would like to send an email to veterans asking them to try their submission again.  The draft of the draft is something along the lines of:

> Dear ???, we have reviewed a number of in progress disability claims on the VA.gov website (https://va.gov/disability/how-to-file-claim/) and have recently made some improvements that should allow you to submit your claim.  Please log back into your in progress application and try and resubmit.
> If you have already submitted your form through other methods (mail, fax, or through your VSO) please disregard this email.
> Thank you

Now that I started thinking about the draft, this is going to have to be very carefully written.

## Acceptance Criteria
- [ ] Email drafted and submitted to Paul Shute for approval
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
Dear Veteran or Representative,

We’re writing to you today because our records indicate that you started a disability claim ([VA Form 21-526EZ](https://www.va.gov/disability/how-to-file-claim/)) on the va.gov website, but did not submit. We have since made some technical enhancements to this form which should allow you to submit online. If you have not yet submitted your disability claim, we encourage you to log into va.gov, complete your claim details and attempt resubmission.

If you have already submitted your form via other methods (mail-in, fax or in-person submission) please disregard this email.  

If you have further questions or need help, please feel free to reach out to us at [number] so we may assist you further.

Thank you,

[sender]

**Comment by kevinstachura** [comment]
This has been completed. @luke-gcio did you want me to send this directly to Paul, or were you planning on handling that communication? I know you mentioned something about CC'ing some call center folks. Please use the above messaging if you plan on handling this. Thanks! Once you have sent to Paul, let me know. I will close out this ticket for us.

**Comment by kevinstachura** [comment]
@luke-gcio I have sent this to Paul - and to you as well. It's an email thread. The acceptance criteria for this ticket has been satisfied.

**Comment by luke-gcio** [comment]
Replied to the email from Paul - he is out.  We still don't have a way to send this email as of now, unfortunately.
