### ISSUE TITLE
22-1995 Breadcrumb update

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#14089]
Review the 22-1995 breadcrumb and url to make sure what was proposed during WBC is still the desired approach to modernize with the rest of the standards implemented on va.gov.   When a final determination is reached, alert @amyknox on the BAH team so modifications can be made to the form, if necessary.

URL
www.va.gov/education/change-gi-bill-benefits/request-change-form-22-1995

Breadcrumb
Home > Education and training > Change your GI Bill school or program > Request change Form 22-1995

**Comment by mnorthuis** [comment]
Reviewed originally proposed URLs/breadcrumbs against current state of site across all applications.  Meeting with @peggygannon next to review H1s, URLs and breadcrumbs for the education forms on 10/1.

**Comment by mnorthuis** [comment]
@amyknox Here are the recommended changes to the 1995 form.  This has been reviewed with @peggygannon as well. 

H1: Change your education benefits
BC: Home > [Education and training](https://www.va.gov/education) > [Change your GI Bill school or program](https://www.va.gov/education/change-gi-bill-benefits/) > Change your benefits VA Form 22-1995
URL: va.gov/education/change-gi-bill-benefits/change-benefits-form-22-1995

Since the 5495 is related to this form, ideally this would be updated as well, or at least sometime in the near future.   I also have recommendations for all the other education forms when we are able to get those updated. 

H1: Change your dependent education benefits
BC: Home > Education and training > Change your GI Bill school or program > Change your dependent's benefits VA Form 22-5495
URL: http://va.gov/education/change-gi-bill-benefits/change-dependent-benefits-form-22-5495 (edited)

**Comment by amyknox** [comment]
@mnorthuis - what's the thinking on when the 22-1995 form should "move" to the new URL? Is that something that needs to wait until the wizard updates are ready or could it go as soon as it's ready? 

cc @dneel-bah

**Comment by mnorthuis** [comment]
@amyknox That is probably something that should be coordinated with the team that will do the wizard move for education. 

When this URL change is implemented, we will need to put a redirect in place for the old URL as well.  There is an issue template for requesting that redirect and that should be done in coordination with the form move so users do not get a 404 when trying to link to the form.  In addition, the wizard and the find forms tool would also need to be updated to direct users to the new URL where applicable.  

So there is a bit of coordination to be done for the URL component, but the H1 and breadcrumb could be done at any time.

**Comment by mnorthuis** [comment]
Yes, that is correct.  Technically the last component of the breadcrumb would not link though. 

Are you able to change the url for the form, or only the breadcrumb at this time?

**Comment by amyknox** [comment]
@mnorthuis only the breadcrumbs at this time. Based on your comment above, the URL update needs to be coordinated with the Wizard team so we're not addressing that now.  

Gotcha on the not linking the last breadcrumb item.

**Comment by mnorthuis** [comment]
To correct my previous statement, I completely missed commenting on the mobile breadcrumb.  

For mobile, only the previous page shows in the breadcrumb, not the current page, so when you are on the form, the breadcrumb would just be:

< Change your GI Bill school or program
url: https://www.va.gov/education/change-gi-bill-benefits/

**Comment by mnorthuis** [comment]
@amyknox I believe the breadcrumb work is complete, can we close this issue?
