### ISSUE TITLE
[Bug] 526: Error Found in 526 Schema During Submission

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14174]
## Issue Description
New error: http://sentry.vfs.va.gov/vets-gov/website-production/issues/209986/
“Error found in schema: Missing type in root.newDisabilities schema.”

Nick comment:
> Is the error saying the type has to be new or just that there has to be a type? because now I'm thinking that the newDisabilities array does contains non-new disabilities, but the type is what marks if they are actually new.

## Acceptance Criteria
- [ ] No more missing type errors
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by ndsprinkle** [comment]
After working on this for a couple days, I think I know what is going on. I'll probably post some follow up comments with screenshots and links to sentry logs to illustrate what I'm talking about.

Essentially, this issue only happens on the review page, specifically after the user adds a new disability on the review page and then immediately (or at least shortly after) hits submit. I believe this happens because of the separation on the review page between the add new disabilities section and the new disability follow up section and also because the new disability follow up section does not automatically expand. 

The main way I have verified this is by observing the breadcrumbs of the users in the sentry issues. In nearly every case I observed, the user added a new disability on the review page, hit "save" on that new disability, and then hit "submit". This of course results in a validation error as the user has not completed the new disabilities follow up page, which is the page that assigns the disability a type. As mentioned, I believe this is happening to some users because it is not super clear on the review page that they have another section that needs attention. We do show the little yellow exclamation mark icon, but nothing beyond that. The good news is that since the submit transformer fix for PTSD, there are no sentry issues appearing related to PTSD as missing a type.

Users are going to mess up validation stuff on the review page. It's an issue we've talked about many times. It's the nature of taking a complex, multi-step form where we carefully walk users through each question, and then throwing everything on the review page to be freely manipulated. So, I don't see how this sentry issue can ever be completely eliminated. That being said, we could do more to help users address all validation issues.

One obvious solution is the ongoing PR created by Robin that simply lists all of the validation errors the user has on the review page. Beyond that, there may be some better ways to highlight items that need attention. Like I mentioned, right now we (usually) just display the yellow exclamation mark icon and change the accordion color. Making changes to this would affect the entire form system, so it may be challenging to make changes to this.

**Comment by ndsprinkle** [comment]
Another note I wanted to make is that many of these errors are retries. The sentry errors have anywhere from 5 to 10 times the number of events as users, which suggests that users attempt to submit multiple times. Consulting the breadcrumbs, it seems that this is the case as many of these errors happen after the resume URL is hit. 

I also see some examples of users toggling the disability check boxes, the ones that dictate if the user is claiming rated or new, and then attempting to submit. There are a few other examples similar to this indicating that users are trying various things to fix the validation issue, but still are not properly assigning the new disability a type in the new disability follow up section.

**Comment by ndsprinkle** [comment]
There is one more golden solution that would address this issue and it's a feature that we have rolled out to the BDD form. We could default all new disabilities to a specific type (probably primary, and also default a primary description like in BDD) so that this validation error would be avoided. I think this makes sense from the perspective of the type being required, so there's no harm in defaulting the value. Maybe we could limit this to defaulting the type when the user adds a new disability on the review page?

**Comment by ndsprinkle** [comment]
@luke-gcio Sooooo really funny story, and I'm glad it's just the two of us on this ticket, because I completely misunderstood this issue both before when we discovered it in sentry and for the past two days as I've been looking at it. As soon as I read the word "type", and of course observed the surrounding context clues of review page and adding new disabilities and the like, I assumed it was talking about a newly added disability missing the type value that is required and added on the new disabilities follow up page. However, the error is actually referring to the entire form's schema missing a type value for the newDisabilities object. I have absolutely no idea how this could be getting dropped as we clearly defined a type value for this on the addDisabilities page, newDisabilityFollowUp page, unemployabilityDisabilities page, and the overall schema (these are all the places that schema is defined) so it may be something wacky going on during submission or even something wacky the back end is doing where that key/value is getting dropped when it's pulled from vets-json-schema. I am going to check that repo to make sure the schema there is not bugged, but I assume it's not since I've witnessed multiple successful submissions.

All the research I have done is not for nothing as it still helps me pinpoint the when and where of this bug. The where is the review page. The when seems to be after messing with new disabilities on the review page. I need to do some more experimenting locally. I'm also going to discuss with Anna as there was another recent issue with the objects getting manipulated in a weird way on the back end causing issues.

**Comment by ndsprinkle** [comment]
This is the matching sentry issue with the most events: http://sentry.vfs.va.gov/organizations/vsp/issues/333/

That one seems to be happening when trying to resume the form on the review page as opposed to submitting the form.

**Comment by ndsprinkle** [comment]
To go full circle, I'm starting to wonder if this is actually an issue with 526 V1 vs. 526 V2. The old schema would have been different and may be translating weird when users resume since we removed the code that handled that conversion from V1 to V2. This is just a hunch, but is another thing to look into.

**Comment by ndsprinkle** [comment]
I am now leaning heavily towards this being a V1 issue. Version 1 of 526 did not support new disabilities. It only supported filing for increase. This would explain how when attempting to resume an in progress 526 V1 form that there would be an issue with the schema for new disabilities, hence the missing type error (should be type 'array'). Robin, Anna, and I have talked about this before as it was a surprise to Anna that Robin removed the V1 functionality and it was a surprised to Robin that the V1 functionality was still needed. I believe Anna mentioned just removing all existing V1 forms (not sure what the number is, but maybe around a thousand) so I will connect with her on this again.

**Comment by ndsprinkle** [comment]
Anna is going to delete the existing 526 V1 forms and I will revisit this to determine if the sentry errors have been mitigated.

**Comment by luke-gcio** [comment]
Closing against #16824.

**Comment by annaswims** [comment]
we deleted the v1 forms 2 days ago and that had no effect on the error rate.

**Comment by annaswims** [comment]
I was able to look at api logs and piece together a plausible scenario for what's happening.  
I think that maybe a veteran submits a form, gets a notice that the submission failed and then maybe hits the back button .  

I'm going to find a few more examples, but I've looked pretty deeply into [this one ](http://sentry.vfs.va.gov/organizations/vsp/issues/333/events/a6e6a53672a24c689d115d872538d02e/?statsPeriod=14d)
* today a veteran logs in, resumes form 526 (it was started in August)
* Veteran submits form 562
* EVSS returns error and that status gets returned to the veteran (doesn't really matter what it is, but in this case it's https://github.com/department-of-veterans-affairs/va.gov-team/issues/15368 )
* ~10 minutes pass with no api calls
* Api call is made to V0::InProgressFormsController#show. with parameters `"id"=>"21-526EZ", "in_progress_form"=>{}`
  *  in_progress_form isn't a valid parameter for show so it's ignored, but it's maybe interesting that its `{}`
  * we see this error several times as the veteran apparently tries to do the same thing
* ~30 minutes later the veteran logs in again, resumes the form (we see the Intent to file API call does not make any changes to form data) and submits again.  
* The SIP data in the database appears to be valid.

**Comment by annaswims** [comment]
I looked at another one and the veteran was able to submit within 2-3 minutes of seeing the error.  
19:03:44 - updated SIP data (looks like it's probably valid but most of the values are redacted in the log)
19:03:47 V0::InProgressFormsController#show - sentry error
19:03:50 V0::InProgressFormsController#show - sentry error
19:03:52  V0::InProgressFormsController#show - sentry error
19:04:30 V0::InProgressFormsController#show
19:04:57  submit form 
 19:06:20 success
 
 Dec 31, 2020 7:03:52
Dec 31, 2020 7:03:50 PM UTC

**Comment by Mottie** [comment]
Waiting for the [accordion alert fix](https://github.com/department-of-veterans-affairs/vets-website/pull/14465) to get merged before we can determine if this is still a usability issue. We're still seeing the error pop up, and it's likely due to Veteran's editing their disability list on the review page and not knowing additional information is required.

**Comment by annaswims** [comment]
@Mottie What did you do to validate?  I still see the error in Sentry http://sentry.vfs.va.gov/organizations/vsp/issues/333/?query=root&statsPeriod=14d

**Comment by Mottie** [comment]
Oops, I only validated the fix locally & with unit tests
