### ISSUE TITLE
Determine what expected error states we need to include for MVP

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#14201]
This story is to capture the work to determine what known error states need to be accounted for and have a UI in the MVP app.

## Context
Before the app goes into the app store, we will design thorough error states. We need to determine how much work we want to do now vs. later. 

## Tasks
1. Determine what known error states exist in the following areas: 
- [ ] Personal & Contact Information
- [x] Military Information
- [ ] Direct Deposit
- [ ] VA Letters and Documents
- [ ] Claims
- [ ] Appeals
- [ ] Appointments
- [x] Authentication

2. Determine which of the identified error states we want to account for in the MVP
3. Design the UI
4. Ask for content help from VSP

**Comment by bridgethapner** [comment]
Some error states are here, but they're broader & there are more product-specific errors: https://design.va.gov/patterns/messaging-dictionary

**Comment by bridgethapner** [comment]
**Notes from 10/15 meeting with @srmyers17 @kreek @jperk51** 

- Errors are usually the same across endpoints
- API errors are more generic generally


## Rules for generic errors (there are 2 types)

#### Errors that will persist until we fix something: 
- 500
- 502
These are things where a service is down for time being, retrying likely **would not** help. Maybe "We’re sorry. Something went wrong on our end. Please call the call center."

#### Errors where uses should try again, then call call center:
- 503
- 504
These are things where a service is down for time being, retrying **might** help. Maybe "We’re sorry. Something went wrong on our end. Please refresh this page or try again later. Or please call the call center." 


## Rules for specific errors (there's 2)

#### Error codes where a user should try again: 
- 422: [specific message TBD]

#### Sign in error (user might not need to know anything went wrong, but if Refresh token is out of date, the user goes to login screen) 
- 401

**Comment by srmyers17** [comment]
@bridgethapner - I created two stories:

1. Generic Error State - Errors that we ask users to retry before calling call center [#14917](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14917)
2. Generic Error State - Msg to Call the Call Center [#14919](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/14919)

I do not think we need error stories for 422 (because those are essentially inline validation errors) or 401 (because those are behind the scenes timeouts that the user won't ever see)

If you agree, I think we can close this one!

**Comment by bridgethapner** [comment]
@srmyers17 Thank you! I think we can close this as well. In addition to #14917 and #14919 it seems like we should keep #13991 as a separate story. I agree that we don't need anything for Error 401. I'm not sure I understand my own note above about 422 :facepalm: and have forgotten what that is but it seems like it's covered by #14917.

**Comment by bridgethapner** [comment]
Closing in favor of #14917, #14919, and #13991.
