### ISSUE TITLE
[FE] - Build Search Results for LC

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14288]
## Issue Description
_Build search results for LC_

## Front end tasks
[Detailed Task Layout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md) 
- toggles from search.va 
- keeping users on page and yielding results.
- Build a react app for LC search 

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All screenreader checks pass

**Comment by jenniferlee-dsva** [comment]
Please see here for UX and error messages: #13983

**Comment by ncksllvn** [comment]
IA reqs for the search results, https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/status-and-decisions.md#101520

**Comment by ncksllvn** [comment]
This estimate was way low...I bumped it to a 5 but it could easily have been an 8.

**Comment by ncksllvn** [comment]
Still an open PR waiting for review but looking sharp 

![image](https://user-images.githubusercontent.com/1915775/97219760-d1620400-17a0-11eb-83e8-84648be76b98.png)

**Comment by ncksllvn** [comment]
I need to make an adjustment. On the Audience label, I was putting the categories instead of the `fieldAudienceBeneficiares`. I have to adjust it.

**Comment by jenniferlee-dsva** [comment]
@ncksllvn - okay to close this as complete and open a new epic for search 1.1 iterations?

**Comment by ncksllvn** [comment]
Yeah, this is done. 

Summary is that we went with a client-side search instead of a search.gov-powered one. Reasons for this -

1. Search.gov-powered search would have required many action items immediately post-launch to index the pages and test a brand new search tool. This carried with it many unknowns and became an increasing source of anxiety for engineering.
1. Search.gov's search response data carried with it several limitations - no article category/tag data, no ability to search by category/tag, ellipses scattered throughout the article description created an odd/inconsistent experience, etc.
1. MVP rollout was defined to include about 25 articles - this is a very limited set of pages, opening the door to a client-side-powered search.
1. Engineer realized the possibility of a client-side search after learning the MVP would be scoped to only 25 articles and exploring this strategy by generating a JSON file representing the entire LC search dataset. This was immediately actionable; had no unknowns; has data in sync with Drupal in terms of rollout (page data updates immediately once content is deployed) and has access to any Drupal fields, including article category; and opens the door for an instant lookup after the initial search is performed, as their are no external dependences or network requests sent from the browser (besides the JSON file on the page load.)

Sorry to those I confused with changing search strategy at the last minute, but I sincerely believe that this was the right choice.
