### ISSUE TITLE
[FE] Build "How do you rate..." page component

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#14302]
## Issue Description
_Need a "how do you rate this page" component_

## Front end tasks
- Ensure the page is styled according to design spec. 
- Validate verbiage "Specific Terminology" 
- Design doesn't exist, need FE build (entirely FE)
- Dispatch following event on good/bad click:
```js
{
  'event': 'int-radio-button-option-click',
  'radio-button-label': "How do you rate your experience on this page?",
  'radio-button-optionLabel': event.target.value, // "Good" | "Bad"
  'radio-button-required': false,
}
```

## Acceptance Criteria
- [ ] Keep the text the same as it is today. "How do you rate your experience on this page?"
- [ ] Keep the radio button choices - Good / Bad.
- [ ] Add our standard secondary "ghost" "Submit" button. (Don't need to disable it or anything fancy.)
- [ ] When the user selects a radio button and hits "Submit," the radio choices and Submit button goes away and is replaced with our thank you message text.
- [ ] Add suggested verbiage for the error message (when no selection is made) to "Please select an answer" as the validation error.
- [ ] All screenreader checks pass
- [ ] Analytic Tags are validated as working via QA test 

## Planning Considerations
- Design exists, need FE (entirely FE)
- Section is called `How do you rate your experience on this page?`
- The user response options are: `Good` / `Bad` 
- After the user clicks on a response, the radio buttons should go away and a confirmation message display in its place. 
- The confirmation message should be: `Thank you for your feedback.` 
- Check in with Analytics team re backend integration. ([Ticket #13774](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13774) ) 

## [Screenshots in mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)

![image](https://user-images.githubusercontent.com/43381063/96153844-27e75c80-0edc-11eb-9369-65710c07891e.png)

![image](https://user-images.githubusercontent.com/43381063/96153918-3b92c300-0edc-11eb-9ad8-70df5e81d079.png)

**Comment by jenniferlee-dsva** [comment]
For reference: analytics backend ticket here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13774  
Please let Joanne and team know when this layer is available to preview in the demo env.

**Comment by jenniferlee-dsva** [comment]
Added screenshots from Mural.

**Comment by brianalloyd** [comment]
@ncksllvn @kelsonic can you estimate once you pull in for action.  Thanks.

**Comment by kelsonic** [comment]
PR is open, pending review :) https://github.com/department-of-veterans-affairs/vets-website/pull/14692

**Comment by kelsonic** [comment]
cross-posting comment for visibility: https://github.com/department-of-veterans-affairs/va.gov-team/issues/13774#issuecomment-716746506

**Comment by kelsonic** [comment]
This issue is blocked until we either 1) decide to use the ForeSee widget, 2) can use Medallia, or 3) use another solution

More context here: https://dsva.slack.com/archives/C52CL1PKQ/p1603742591027700?thread_ts=1603737957.022900&cid=C52CL1PKQ

Throwing this in the backlog for now then CC @jenniferlee-dsva

**Comment by kelsonic** [comment]
PR is up to add the boilerplate HTML markup: https://github.com/department-of-veterans-affairs/vets-website/pull/14711

**Comment by jenniferlee-dsva** [comment]
We can move this to 1.1 work. Opened design ticket to update per Foresee info: [#15314](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15314)

**Comment by brianalloyd** [comment]
@jenniferlee-dsva and @kelsonic updating ticket and moving to MVP 1.1 Epic in support.

**Comment by kelsonic** [comment]
FYSA Jump link to top of page design directly conflicts with ForeSee widget atm

**Comment by jenniferlee-dsva** [comment]
Thx @kelsonic -good eye -  def don't want that kind of collision! we will not implement the foresee widget. that is why we created the article rating component within the body of the template. 

we weren't expecting to use foresee responses though, so we will be [re-evaluating our current component design ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15314)to use the foresee responses and find a way for users to send that data without a big submit button, floaty affordance, or modal popup.  ultimately, we want to avoid having another floaty widget.

**Comment by jenniferlee-dsva** [comment]
FYSA - Followed up re Medallia pilot here: https://dsva.slack.com/archives/C1Q4294JJ/p1610552969228800 

Will add more info here re if/when Medallia might be ready for us to integrate with. 

@brianalloyd @johnhashva

**Comment by brianalloyd** [comment]
Thanks @jenniferlee-dsva was going to follow up on this during tomorrow's link up with the Analytics team.  Thanks for reaching out with the details.

**Comment by jenniferlee-dsva** [comment]
Medallia isn't ready yet. [Per this slack from Chante](https://dsva.slack.com/archives/C1Q4294JJ/p1610554131231300), there is a 508 compliance blocker they are trying to get Medallia to address.

**Comment by brianalloyd** [comment]
I'm in the loop with the Contact Center team that is now handling Medallia implementations and am on the waiting list for integrations once Medallia is operational.  I'll follow up with status on this ticket forward. CC @johnhashva

**Comment by brianalloyd** [comment]
April 1, 2021 had a meeting with Contact Center team to review details on Medallia and was told this type of implementation would be a custom ask for the team and needed to be vetted with their VA lead.  We also determined that medallia does have this capability, styling and look but we would need to wait another 3-4 months before a possible implementation.

**Comment by brianalloyd** [comment]
@jenniferlee-dsva we discussed this in planning and due to the recent discussion with the Customer Contact team concerning Medallia we would like to move forward with this with a FE to GA integration front.  We discussed this with @johnhashva who validated approval and suggested we also validate with you in support.  Let me know thoughts and if you would like to have a quick convo on the subject.  Thanks.

**Comment by jenniferlee-dsva** [comment]
I'm okay with this approach. Thanks @brianalloyd

**Comment by brianalloyd** [comment]
@jenniferlee-dsva is the design hardcoded?  Wanted to ask as ideas concerning a thumbs up/down approach Vs. radial button input was discussed internally but wanted to validate with you and gather thoughts and ideas.  CC @johnhashva 
![Screen Shot 2021-04-13 at 9 23 57 AM](https://user-images.githubusercontent.com/70410912/114770661-e7e92100-9d28-11eb-8a6f-633b8ad476c4.png)

**Comment by callen2563** [comment]
@Kelson I was just wondering if it's possible with GA integration to store gathered veteran feedback into a database. I'm just asking because if I design this to have a field where veterans can enter feedback will this be a feasible design.

**Comment by kelsonic** [comment]
@callen2563 so I'm imagining when there's a click event for the up or down vote, or if a user were to type feedback in a text field, I can pass all of that data along to GA using our `recordEvent` module. So definitely feasible! 🙂

**Comment by brianalloyd** [comment]
Planning Discussion: A/B testing with a percentage of both designs with text field (both positive and negative) responses.  Other options to discuss: 1) GTM funnels for context on how they arrived to the R&S page OR
2) Text field that allows vet to give additional context into their positive/negative response.  Need to also getting with Insights team to review.

**Comment by jenniferlee-dsva** [comment]
Couple of comments. There's a lot here, so I haven't had a chance to read through all the new comments. 

In no particular order:

1/ We are somewhat legally restricted in how we collect textual user feedback, so let's not open that can of worms here.

2/ We deliberately want to keep this interaction binary and simple. Additional reason we want to stay away from collecting textual feedback in addition to rating. 

3/ Using` thumbs up / thumbs down` vs. `yes/no` radio buttons:  I don't know why we didn't use the thumbs affordance; we did consider it at one point. I assume it must have had something to do with 508 compliance. I am ok with either if they equally meet accessibility best practice. If not, please stay with Yes/No as it has already been vetted by J. Strickland, the accessibility person at the time. 

4/ RE is the design hard coded? - this component is completely FE, and not pulling from the CMS. The text and design have already gone through the collab cycle and received early accessibility input, so let's stay with what we've got.  

It serves the purpose and has been vetted by platform and is ready to use without going through another collab cycle review. I'd rather get this out there without further delay just for the sake of changing the design without any substantive improvement in problem solving.

**Comment by johnhashva** [comment]
@brianalloyd + @jenniferlee-dsva just dropping here @joshkimux 's take on the icon approach -- confirming Jen's recall:

- Icons don’t have a visible label, so Veterans with mobility disabilities who rely on voice based assistive technology may struggle understanding how to activate the icons e.g. a Veteran may say “Click on thumbs up”, but the AT may not recognize the command if it’s accessible name is “Yes”, not thumbs up.
- Thumbs up and thumbs down may not have as strong of an affordance as being interactive compared to actual radio options as the latter is a semantic default. For older generations, Veterans with cognitive disabilities, etc-- icons may not be as intuitive.
- Making custom radio buttons (thumbs up/down icons) accessible will be a dev-intensive task. We’ll need to hide the semantic yes/no radio options and use an SVG to create a radio image.
- Quoting @Martha Wilkes, we should aim for being boring and accessible over magic

@jenniferlee-dsva one more Q from me:  Any issue with changing the text in that Rate component to "How do you rate this article” (vs. experience on this page?) with the options labeled: Recommended / Not Recommended  OR Helpful / Not Helpful (vs. the current Good / Bad)?   Facebook, for one, uses Recommended / Not Recommended.

**Comment by jenniferlee-dsva** [comment]
Because of PRA things, I think we should stick with the vetted language, even if the backend will be GA rather than Medallia. (The language comes from the list of approved customer feedback question text for Medallia and Foresee.)

**Comment by jenniferlee-dsva** [comment]
The vetted preapproved language is in the original design mock referenced here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/14302#issuecomment-716749875

How do you rate your experience on this page? 
- Default state: Good / Bad
- After click state:  Thank you for your feedback.

**Comment by brianalloyd** [comment]
@joanneesteban could you help us route this ticket to the appropriate team member that could help us determine event tracking for this component?  Thanks for the support.

**Comment by kelsonic** [comment]
PR merged, should be on staging/preview servers shortly 🙂

**Comment by kelsonic** [comment]
Good/bad live on staging, ready for validation + just need the greenlight to promote it to prod: https://staging.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/ CC @brianalloyd @jenniferlee-dsva @johnhashva

**Comment by joshkimux** [comment]
@kelsonic and team, some quick accessibility feedback! 

To meet Section 508 compliance, we'll need to:
- write the radio buttons semantically within a form and fieldset
- provide an explicit submit button
- place the `h2` within a legend inside said fieldset

For example (needs styling):
```html
<form>
  <fieldset>
      <legend><h2>How do you rate your experience on this page?</h2></legend>
    <div>
      <input type="radio" id="good" name="rate" value="good">
      <label for="good">Good</label>
      <input type="radio" id="bad" name="rate" value="bad">
      <label for="bad">Bad</label>
    </div>
    <div>
      <button type="submit">Submit</button>
    </div>
  </fieldset>
</form>
```

As for the why:
- Folks may unintentionally submit an incorrect response because it's not a common pattern for a radio to both select and submit
- Unexpected behavior can also break habituation. Folks may become nervous that selecting radio options will automatically submit on other parts of VA.gov
- Without an explicit fieldset and legend, should a screen reader user tab to "good," they won't hear the question and thus won't know the context of the radio button
- We won't need to worry about positive tab indexes, which [can cause a number of launchbreaking accessibility issues](https://www.scottohara.me/blog/2019/05/25/tabindex.html)

## Launchblocking issues

### Tab order is unexpected due to positive values

https://user-images.githubusercontent.com/14154792/119155671-6b311d00-ba21-11eb-88aa-12cafd796271.mov

### "Good" will be selected when keyboard users attempt to navigate to "Bad" using the `right arrow` key

https://user-images.githubusercontent.com/14154792/119155980-bfd49800-ba21-11eb-8556-bec71a99373f.mov

## After
- Screen readers can hear the context of the question
- A clear submit button prevents unexpected submissions for mouse users
- Keyboard users can now access "bad"

https://user-images.githubusercontent.com/14154792/119156238-0a561480-ba22-11eb-91cf-68ffa24d1fe7.mov

**Comment by jenniferlee-dsva** [comment]
Great feedback @joshkimux regarding keyboard tabbing. 

I notice that on the Gov.UK site, the behavior of submitting a 1/0 feedback is different when it's tabbed to vs. moused over. See this page - https://www.gov.uk/1619-bursary-fund -- scroll to the bottom where it has the Yes and No 'buttons.' 

When you mouse click, the Yes/No submits immediately. But, if you tab to it via keyboard, you have to hit Enter/Return on your keyboard in order to actually submit it -- this allows you to tab from Yes to No without submitting. 

Can we do this approach? This was our intended UX approach.

**Comment by jenniferlee-dsva** [comment]
If this needs a little more time to address the accessibility experience and FE design, I'm okay postponing production go-live. Let's not rush.

**Comment by joshkimux** [comment]
@jenniferlee-dsva , gov.uk's version works because they've written and styled both of these as buttons, so there's a stronger affordance to keyboard and screen reader users that "yes" will also submit.

<img width="1049" alt="Screen Shot 2021-05-21 at 11 59 18 AM" src="https://user-images.githubusercontent.com/14154792/119165903-05965e00-ba2c-11eb-8c5d-74504e242742.png">

Something interest I found inspecting there code is they have a bot-specific choice too hahaha
```html
<!-- Maybe button exists only to try and capture clicks by bots -->
<button data-track-category="yesNoFeedbackForm" data-track-action="ffMaybeClick" aria-expanded="false" style="display: none" hidden="hidden" aria-hidden="true">
      Maybe
    </button>
```

**Comment by jenniferlee-dsva** [comment]
>We'd need to weigh the pros/cons of each.

Very agree. From a product and design POV, I'm also thinking about this in the context of the whole page, and all article templates. Since an article can have up to 2 CTA buttons -- and if it's a super long page, could potentially repeat the buttons at the bottom of the article too -- I'm also thinking about having too many buttons on the same page. Especially for this type of action which isn't at all an important CTA. 

Sorry to delay us on this @brianalloyd @kelsonic @johnhashva.  I'd like consult design on this.

**Comment by jenniferlee-dsva** [comment]
Let's stay with @joshkimux  recommended approach of adding a separate button, but consider the following design and UX edits, so we're not overwhelming users with potentially a ton of equally weighted CTA buttons. (Feel free to ticket separately if you need to keep track outside of this issue.)

1/ Use our secondary button design: https://design.va.gov/components/buttons#secondary-button , **and**

2/ Default disabled state until user selects one of the radio options https://design.va.gov/components/buttons#disabled-buttons 

@brianalloyd @johnhashva - would you mind getting PW designer's check on this approach before moving forward?

**Comment by kelsonic** [comment]
CC @callen2563

**Comment by brianalloyd** [comment]
@jenniferlee-dsva and @joshkimux all great considerations, I'm looping in @callen2563 from the PW team to give a designers review on the above mentioned approach.  @callen2563 please comment on this ticket with your feedback.

**Comment by joanneesteban** [comment]
@bsmartin-ep will QA this! Thanks!

**Comment by brianalloyd** [comment]
Thanks @joanneesteban we were able to connect with @bsmartin-ep on Friday and get the data layers connected appropriately.  Appreciate the QA support as discussed.

**Comment by callen2563** [comment]
@brianalloyd @jenniferlee-dsva @kelsonic @joshkimux 
I agree with Jen that the buttons would be too weighty and would compete with other CTAs on the page or other pages this might eventually live on. The radio button treatment isn't something from a UX design perspective that users are are used to using for page ratings and from a visual design perspective this looks visually dated. The universal page rating treatment is a thumbs up or down, or star icons and my recommendation would be to move forward with something users are more familiar with using. Here is a [helpful article on the subject and why Netflix switched from a star rating to a thumbs up/ down](https://www.appcues.com/blog/rating-system-ux-star-thumbs).

**Comment by callen2563** [comment]
@brianalloyd @jenniferlee-dsva @kelsonic I was just chatting with Josh to get caught up because last time I heard from Brian we were moving forward with the radio button approach Ryan previously mocked up. I will mock up the button version and we can decide which solution you all would like to move forward with.

**Comment by callen2563** [comment]
@brianalloyd @jenniferlee-dsva @joshkimux You can view the button mock up on [InVision here](https://vsateams.invisionapp.com/console/share/BX2LX1CVVA/638475693).

**Comment by joshkimux** [comment]
@callen2563 way to combine best of both worlds! The 👍 and 👎 icons paired with a visible label can help some folks with cognitive disabilities more easily understand the prompt at a glance AND still includes folks who use voice assistive technology with a visible label they can call out 🥳

**Comment by jenniferlee-dsva** [comment]
@brianalloyd @joshkimux @callen2563 @kelsonic  - While I appreciate the ingenuity of bringing back the thumbs up/down icons in button forms, since my original expressed concern above was not having too many buttons on the article pages, I'd still like to stick with Josh's recommendation to add ONE submit button. (One button vs. 2 buttons for this - prefer fewer buttons.) 

Also after more thought and discussion, providing a Submit button would give users who are NOT using screen readers more intentional signal -- they can't accidentally or just 'trying' out clicking things send a response they didn't intend. This was definitely not part of our original design thinking, but Josh's explanations have changed my thinking on this.

We need to stay with the pre-approved and legally vetted PRA feedback language. This includes the answer texts that goes with that question. This has legal impact, so I do not want to reinvent the wheel with new text and new icons. 

**So, let's keep this simple and do this:** 

1. Keep the text the same as it is today. "How do you rate your experience on this page?"
2. Keep the radio button choices - Good / Bad. 
3. Add our standard secondary "ghost" "Submit" button. (Don't need to disable it or anything fancy.) 
4. When the user selects a radio button and hits "Submit," the radio choices and Submit button goes away and is replaced with our thank you message text. 

I think because the user will have the potential to hit the Submit without selecting a radio choice, we'll need a standard error message. Could you check @brianalloyd with Peggy or Randi? If one exists, let's go with that. If not, we can say something very simple like "Select an answer before you click Submit."

**Comment by brianalloyd** [comment]
@jenniferlee-dsva thanks for the great feedback and direction forward, I'm all in favor of keeping things simple.  I'll reach out to Randi and Peggy and get some guidance on standard error messaging and annotate on the ticket forward.  CC @kelsonic @johnhashva

**Comment by joshkimux** [comment]
> @brianalloyd @joshkimux @callen2563 @kelsonic - While I appreciate the ingenuity of bringing back the thumbs up/down icons in button forms, since my original expressed concern above was not having too many buttons on the article pages, I'd still like to stick with Josh's recommendation to add ONE submit button. (One button vs. 2 buttons for this - prefer fewer buttons.)
> 
> Also after more thought and discussion, providing a Submit button would give users who are NOT using screen readers more intentional signal -- they can't accidentally or just 'trying' out clicking things send a response they didn't intend. This was definitely not part of our original design thinking, but Josh's explanations have changed my thinking on this.
> 
> We need to stay with the pre-approved and legally vetted PRA feedback language. This includes the answer texts that goes with that question. This has legal impact, so I do not want to reinvent the wheel with new text and new icons.
> 
> **So, let's keep this simple and do this:**
> 
> 1. Keep the text the same as it is today. "How do you rate your experience on this page?"
> 2. Keep the radio button choices - Good / Bad.
> 3. Add our standard secondary "ghost" "Submit" button. (Don't need to disable it or anything fancy.)
> 4. When the user selects a radio button and hits "Submit," the radio choices and Submit button goes away and is replaced with our thank you message text.
> 
> I think because the user will have the potential to hit the Submit without selecting a radio choice, we'll need a standard error message. Could you check @brianalloyd with Peggy or Randi? If one exists, let's go with that. If not, we can say something very simple like "Select an answer before you click Submit."

Yesss, love the fact that we'll have a simple error message in favor of an inactive button. Big win for a11y. Thanks @jenniferlee-dsva 🥳

**Comment by bsmartin-ep** [comment]
@brianalloyd -

Radio button events look good BTW...

Description|dataLayer|Tag|Pass
----|----|-----|-----
"Good" radio button click|![image](https://user-images.githubusercontent.com/62304138/119747694-3ed23200-be61-11eb-9373-345af0a6c348.png)|![image](https://user-images.githubusercontent.com/62304138/119747553-fadf2d00-be60-11eb-92d7-0d80a82de958.png)|**PASS**
"Bad" radio button click|![image](https://user-images.githubusercontent.com/62304138/119747666-2eba5280-be61-11eb-89d4-65ecc6b82a84.png)|![image](https://user-images.githubusercontent.com/62304138/119747517-e69b3000-be60-11eb-9fc9-5d54411937c9.png)|**PASS**

From what I'm reading, your changes shouldn't require me to QA again.  But let me know if you think different.

**Comment by brianalloyd** [comment]
@jenniferlee-dsva @kelsonic I received feedback from Peggy concerning the suggested language for 

> I think because the user will have the potential to hit the Submit without selecting a radio choice, we'll need a standard error message. Could you check brianalloyd with Peggy or Randi? If one exists, let's go with that. If not, we can say something very simple like "Select an answer before you click Submit."

The suggested verbiage for the error message is "Please select an answer"  as the validation error.
Here's a helpful link to the standard validation error/feedback messaging here: https://design.va.gov/patterns/messaging-dictionary

Let me know if any questions exist, @kelsonic looking forward to working next steps as outlined here:

> 1. Keep the text the same as it is today. "How do you rate your experience on this page?"
> 2. Keep the radio button choices - Good / Bad.
> 3. Add our standard secondary "ghost" "Submit" button. (Don't need to disable it or anything fancy.)
> 4. When the user selects a radio button and hits "Submit," the radio choices and Submit button goes away and is replaced with our thank you message text.

**Comment by kelsonic** [comment]
@brianalloyd I'll pick this up today, thanks! 🙂 Does it make sense to have this as a separate ticket since the AC have changed?

**Comment by callen2563** [comment]
@kelsonic In answer to you question earlier about where the error alert should go I would place it above the submit button. Here is a link to read though that specifies how and where to use alerts.. https://design.va.gov/components/alertboxes
Let me know if you have any questions. Thanks!

**Comment by kelsonic** [comment]
PR merged 👍

**Comment by brianalloyd** [comment]
@kelsonic looks like this might be ready in staging, is that correct?  If so, could you pass link for Validation in staging?  Thanks.

**Comment by kelsonic** [comment]
Hey @brianalloyd you can view it here! 🙂 https://staging.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/

**Comment by brianalloyd** [comment]
Thanks @kelsonic visually looks great, not able to validate logic as once you hit submit or test for "ghost submit" error nothing happens.  

> 3. Add our standard secondary "ghost" "Submit" button. With suggested verbiage for the error message is "Please select an answer" as the validation error.
> 4. When the user selects a radio button and hits "Submit," the radio choices and Submit button goes away and is replaced with our thank you message text.

**Comment by joshkimux** [comment]
Likewise, the thank you message is not announced to screen reader users. I recommend using an `aria-live` region to do this. Let me know if you need any help with that!

https://user-images.githubusercontent.com/14154792/121210670-d8c6b100-c849-11eb-8689-d0ae86ae75ea.mov

I also [added some additional comments to the code review](https://github.com/department-of-veterans-affairs/content-build/pull/220#pullrequestreview-678641770) which I caught post-testing including:
- removing `tab-index="0"`
- placing the `h2` question within a `legend` and making it the first child of the `fieldset`
- writing the button's text as "Submit Rating" or "Submit Feedback" instead of just "Submit"

**Comment by kelsonic** [comment]
PR merged for above a11y findings! 🙂 Another follow-up PR to ensure the script tags run properly: https://github.com/department-of-veterans-affairs/content-build/pull/236 This will be ready for validation on staging tomorrow following the daily deploy 🚀

**Comment by brianalloyd** [comment]
Thanks for the update @kelsonic and the work effort on this, excited to see if in staging and validating forward.

**Comment by brianalloyd** [comment]
@kelsonic let's take some time tomorrow to review this together post SU tomorrow.  Thanks.

**Comment by jenniferlee-dsva** [comment]
Feedback on the staging preview: 

1/ the Good/Bad radio buttons should be side by side on the same line, [per mock here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14302#issue-713213890)

2/ the Submit button should use a secondary button styling per [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/14302#issuecomment-856848020) above - design system: https://design.va.gov/components/buttons#secondary-button

3/ The text of the button - let's use  `Submit feedback`   since our thank you message says, "Thank you for your feedback."

**Comment by jenniferlee-dsva** [comment]
Fast forward to around 35 seconds. (Sorry - couldn't trim Zoom video.) 


https://user-images.githubusercontent.com/43381063/122061171-4465cc80-cdbc-11eb-9976-0ab23a85b640.mp4

**Comment by jenniferlee-dsva** [comment]
A couple of observations, top of the page on down: 

1/ When I use the tab key, it skips over the "All VA.gov" radio button choice above the search bar. (Unrelated bug that we should resolve separately.) 

2/ Whether going down the page or up the page, the order should always enable hitting both Good and Bad in succession. 

Example: 
- When I tab down the page, I can get to the Good radio choice, but then next tab skips me to the Submit button. It should allow me to go from the Good radio choice to the Bad radio choice. 
- When I tab up/reverse, I can get to the Bad radio choice. BUT, when I continue to reverse tab, it skips over the Good choice and takes me to the All Veterans topic tag. 

4/ When I try to select an answer, I hit the Enter/Return key but it didn't allow me to select. I had to hit the Space bar. Not sure if this is typical 508 behavior and just an issue with my keyboard, but I was expecting to be able to hit Enter/Return. Could you check with @joshkimux what is appropriate to do here?

**Comment by jenniferlee-dsva** [comment]
If the above are not true bugs - per [Josh's explanation here](https://dsva.slack.com/archives/C52CL1PKQ/p1623763558150700?thread_ts=1623695538.144000&cid=C52CL1PKQ) - then I'm fine with this. I think it looks great. Thank you @kelsonic for all the attention to details!

**Comment by kelsonic** [comment]
Thank you both for your due diligence here! 🙂 When we feel comfortable with the how do you rate component on staging, please let me know when I should promote it to production! 🚀

**Comment by brianalloyd** [comment]
@jenniferlee-dsva look like you are good with the above based on thread.  Are we clear to promote it to production in support?

**Comment by brianalloyd** [comment]
Work is complete on this and validated. PR merged, will go out with daily deploy today. Closing ticket in support.
