### ISSUE TITLE
Reporting metrics for the online 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#14355]
As the Caregiver Program team,
I want to understand a number of metrics about the online application,
So that I can share that with leadership and build trust in the VA.gov platform.

How might we make it easier to review and distribute those live metrics so that we're not relying on GA (unreliable) or manually parsing logs (labor intensive)?

**Comment by mlighdc** [comment]
Hi @ala-yna and @kevinmirc, here is my list: 

- How any applications were submitted on VA.gov each day?
- How many applications were successfully sent to CARMA on each day?
- How many applications were not sent to CARMA due to errors on each day? This category would include veteran not found in MPI, as well as unanticipated issues or bugs.
- Of the applications that had issues, what were the reasons that they did not make it into CARMA?
- Cumulative totals by week and since 10/1

In talking to a few folks, it seems like we should be able to use Google Analytics and Sentry to get most of the information. I know Google Analytics may be off a little bit but I don't think it is significant unless you think differently. Hopefully @kevinmirc you will only need to use the logs sparingly. I really appreciate your thoroughness on launch day. I think it was really helpful and much appreciated by the Caregiver team. If you need any log query support, it sounds like we can reach out to the platform team.

**Comment by kevinmirc** [comment]
Hi @mlighdc,

Thanks for providing specifics.

Since GA will not be entirely accurate, I think the best approach is to pull from the logs. We can:
- count **Attempts** by counting API calls to `POST /v0/caregivers_assistances_claims`
- count **Successful** with logs where `@message like "[Form 10-10CG] Submission Successful"`
- count **Blocked** with logs where `@message like "[Form 10-10CG] Submission Failed: qualifications not met"`
- calculate **Total Errors** with `Attempts - Successful - Blocked`
- count **Validation Errors** with logs where `@message like "[Form 10-10CG] Submission Failed: invalid data provided by client"`
- calculate **All Other Errors** with `Attempts - Successful - Blocked - Validation Errors`

This can be made with a simple script and event run on a regular (maybe daily?) basis.

> Of the applications that had issues, what were the reasons that they did not make it into CARMA?

This is the one that would require a higher level of effort. We can cross-reference with other logs, or Sentry, to get the error message, but the error message will likely not provide a "reason" for why the error occurred. Each of these errors will likely require manual investigation and research as to why and how they occurred.

**Comment by kevinmirc** [comment]
Want to also clarify, that we just need to know on a high level what percent of applications typically bounce, what percent are successful, or other high-level trends, GA is sufficient. But it sounds like the requirement is getting an exact count in each of those categories.

**Comment by mlighdc** [comment]
@kevinmirc do you know how big of a discrepancy there is between GA and the logs? I am actually fine either way, if the script is easy to create. But I am okay if we are off 1 or 2 or some reasonable amount and use GA. I am most concern about us being able to catch errors and address them.

I am curious to understand how much of a delta between GA and the logs. But I also would not want you to spend a crazy amount of time pulling the data vs. potential using the time to trouble shoot if we spot an issue. Let's discuss during sprint planning next week. Thanks.

**Comment by kevinmirc** [comment]
@ala-yna @mlighdc Is this ticket considered complete, now that we have a process for gathering and reporting these stats (Cloudwatch Query + Excel)?
