### ISSUE TITLE
Type Ahead POC: Implement Feature Flag

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#14452]
## Issue Description

FE needs a feature flag to limit production access to 5% of VA.gov authenticated users for a one month proof of concept test of Type-Ahead search functionality.

---
## Tasks
- [ ] Add feature flag `TBD'

## Acceptance Criteria
- [ ] Flag should appear on flipper dashboard

**Comment by denisecoveyduc** [comment]
To be assigned to Sam; will work with Nick Sullivan. Will be assigned for Sprint 34.

**Comment by denisecoveyduc** [comment]
11/12 - Grooming - Resizing as per Sam's initial review. Still working on setting up environments.

**Comment by srsuddath** [comment]
Our group has changed story point estimation values, hence change from a 2 to a 3. There is a minimal amount of work remaining on this ticket however

**Comment by srsuddath** [comment]
@jonwehausen We are looking at releasing this functionality to 5% of users side-wide, rather than just on the homepage. Does the analytics for the event tracking monitor which page the events come from? Or does the data layer not specify what the source of the traffic is? Just looking to get some clarifications before we release this feature.
