### ISSUE TITLE
[Discovery] Understand how to bring BGS gem under VSP code ownership

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#14534]
## Background

We should bring the [BGS gem](https://github.com/department-of-veterans-affairs/bgs-ext) into VSP code ownership, so that we can maintain upgrades/connectivity as teams migrate and change.

## Tasks

- [x] Discover what it will take to consider the gem under "VSP ownership"
- [x] Document & create issues for the tasks required as discovered :point_up:

**Comment by LindseySaari** [comment]
It looks like as of now, the `platform-console-services` Github team has Admin access of the BGS gem, so the ask in this ticket is completed. The team includes Igor, myself and Rachal, but this brings up a bigger point though because I think the GH teams may need to be renamed according to CoP. `platform-console-services` doesn't have all the appropriate people (e.g. Ryan, Rebecca) and Igor is technically devops.

![Screen Shot 2022-12-19 at 1.58.17 PM.png](https://images.zenhubusercontent.com/5d4836dda95c51615db9bdc9/4c292ed5-5ca0-41e8-9062-e3ec9b000fc7)

**Comment by LindseySaari** [comment]
[va-platform-cop-backend](https://github.com/orgs/department-of-veterans-affairs/teams/va-platform-cop-backend/members) was added with the Admin role to the BGS gem

**Comment by little-oddball** [comment]
Provided link to this list of the "new" teams:

https://github.com/orgs/department-of-veterans-affairs/teams?query=va-platform

**Comment by laineymajor** [comment]
@holdenhinkle @LindseySaari are we good to close this ticket? Just doing some zenhub spring cleaning :)

**Comment by laineymajor** [comment]
Good to close per @LindseySaari
