### ISSUE TITLE
STEM: 22-1995 UI Updates - Form Title / Breadcrumb

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14659]
- [ ] Update prototype & content doc with "Change education benefits" updates to support dev efforts  

14089 VSP Story; 14365 Booz Story"

**Comment by amyknox** [comment]
22-1995 mobile breadcrumb: < Change your benefits VA Form 22-1995

**Comment by watersemma** [comment]
Updated screens are now in invision and can be seen here: https://bahdigital.invisionapp.com/share/VUIAEXFPHBC

Updated content documentation can be seen here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/1995/content/1995-content-doc-v3.0.md

**Comment by amyknox** [comment]
The work is beautiful but, sadly, I think Mikki steered us wrong with the mobile breadcrumb.  If it's "< Change your benefits VA Form 22-1995" and you tap it, you're already on that page.  

I think it actually has to be "< Change your GI Bill school or program" so when you tap it, it goes to the [soon to be] preceding page. 

@dneel-bah, Super Breadcrumb Tracker, can we get your .02 on this.

**Comment by amyknox** [comment]
@watersemma 

Per Mikki the IA at DEPO, the REAL mobile breadcrumb is:

"< Change your GI Bill school or program" 
url: https://www.va.gov/education/change-gi-bill-benefits/ 

cc @ccruzgra , @dneel-bah

**Comment by dneel-bah** [comment]
So that should be the default behavior based on my understanding, @shawkey-daniel can confirm.

Desktop/tablet breadcrumbs for 1995 are:
Home > Education and training > Change your GI Bill school or program > Change your benefits VA Form 22-1995
a. "Home" url: https://www.va.gov/
b. "Education and training" url: https://www.va.gov/education/
c. "Change your GI Bill school or program" url: https://www.va.gov/education/change-gi-bill-benefits/
d. "Change your benefits VA Form 22-1995" url: https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction

Mobile breadcrumbs for 1995 are:
Home > Education and training > Change your GI Bill school or program ~> Change your benefits VA Form 22-1995~ (Not shown on mobile.
a. "Home" url: https://www.va.gov/
b. "Education and training" url: https://www.va.gov/education/
c. "Change your GI Bill school or program" url: https://www.va.gov/education/change-gi-bill-benefits/
~d. "Change your benefits VA Form 22-1995" url: https://www.va.gov/education/apply-for-education-benefits/application/1995/introduction~ (Not shown on mobile)

**Comment by watersemma** [comment]
Updated screens: https://bahdigital.invisionapp.com/share/VUIAEXFPHBC

Updated content documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/1995/content/1995-content-doc-v3.0.md

**Comment by amyknox** [comment]
@watersemma Looks fantastic - and closeable. Thank you!
