### ISSUE TITLE
RESEARCH: Community care Request Managers (schedulers)

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#14658]
## High level prompt
We want to get a better understanding what type of data a community care request managers (schedulers) uses when processing Veterans' community care requests/referrals. 

In addition, and more specific to the Facility Locator team, we want to understand how and where Community Care Request managers search for type of care/specialties and providers. 

The VAOS team and the Facility Locator team will both benefit from understanding the type of data Request Manager get and use to process a community care request.  

## Context
- Community care schedulers at VA follow a very specific process for managing VAOS requests for community care appointments
- To review the SOP for CC schedulers you'll need to get on the network to access the Sharepoint & use [this url](https://dvagov.sharepoint.com/sites/VHAOCC/CNM/CI/OCCFGB/SitePages/FGB.aspx)

## Goals
- Understand the current data & process that a community care request manager follows/uses to process Veteran's community care requests
- Understand/gather feedback (where possible) about the VAOS requests for community care coming in to Community Care request manages

## Questions to answer:
- How does a community care request get processed by Request managers once it is received in Schedule Manager?
    - Do you schedule appointments for community care? How does that process work?
- What type of data is a Request manager looking for from a Veteran when processing community care requests?
    - What information do you see from the VAOS request? Of that information, what do you use? What is helpful?
    - How do you search for type of care/specialities? Where do you search for that data + providers?
- What are the different systems a Scheduler uses to process a community care request?
- If you could change anything about community care online scheduling through VAOS what would it be?

## Issues to create within this Epic 
(For reference [here's the 'Research' folder](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/README.md) to assist with developing research project)
- [ ] Create research plan [#13583](https://github.com/department-of-veterans-affairs/va.gov-team/issues/13583) 
- [ ] Recruit for research sessions/Schedule research sessions -- @lenae to assist with getting candidates 
- [ ] [Create conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)
- [ ] Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- [ ] Discovery Synthesis - should be conducted as a team, led by designer.
- [ ] Discovery [Research Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/session-report-template.md) (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)

**Comment by mmiddaugh** [comment]
Thanks @lenaecb. This looks great and we're looking forward to the collaboration.  

Just to expand a bit from the Facilities team perspective: 

**What type of data is a Request manager looking for from a Veteran when processing community care requests?**
- If the schedulers are able to share anecdotal experience, we'd love to know what factors are important to a Veteran so that we can present Facility Locator Community care provider search results accordingly. 

**How do you search for type of care/specialties? Where do you search for that data + providers?**
- For the work mapping PPMS to VHA health service taxonomy, we're very interested in the words/categories the schedulers use when searching. (NUCC taxonomy organizes services with Code, Grouping, Classification, and Specialization. It would be helpful to learn which - if any - of these categories are used by schedulers.) 
- We would also be interested in understanding their expectations for search results, such as the number of results and distance/drive time. Also interested in learning how individual provider name vs group practice name is handled. 

Will this research be focused on the Top 5 services (optometry, food/nutrition, podiatry, audiology and emergency)? If so, it might help to know if the process of searching for these services is generally representative of Community Care.

**Comment by lenaecb** [comment]
Met 10/16 - determined in meeting we would target this research for beginning of Nov

**Comment by mmiddaugh** [comment]
@lenaecb @davidconlon 

Related to our discussion of choosing "non-VAOS" specialties to include in the research, here are the top Community care codes searched on Facility Locator (prod) since Jan 1, 2020: 

Site Search Category |   |   | Total Unique Searches
-- | -- | -- | --
261QU0200X | Clinic/Center | Urgent Care | 39,873
261QP2300X | Clinic/Center | Primary Care | 22,671
111N00000X | Chiropractor |   | 4,071
3336C0003X | Pharmacy | Community/Retail Pharmacy | 3,301
152W00000X | Optometrist |   | 3,260
363LP2300X | Nurse Practitioner | Primary Care | 2,790
282N00000X | General Acute Care Hospital |   | 2,489
207P00000X | Emergency Medicine |   | 2,461
207N00000X | Dermatology |   | 2,448
101YM0800X | Counselor | Mental Health | 2,333
171100000X | Acupuncturist |   | 2,309
207X00000X | Orthopaedic Surgery |   | 2,271
122300000X | Dentist |   | 2,175
231H00000X | Audiologist |   | 2,059

If we exclude the VAOS 5 and pharmacy (since I don't think scheduling applies), how about Chiropractor and Dermatology?
