### ISSUE TITLE
CT Redesign: Recruiting	Recruit non-Veteran Users & Stakeholders

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#14674]
Recruit non-Veteran Users & Stakeholders for Discovery Interviews

**Comment by amyknox** [comment]
Jen, since you’re recruiting for SCO’s, Luke and Kevin give their pointers in the below emails.

Cindy

From: Amy Knox <Knox_Amy@bah.com>
Date: Tuesday, August 20, 2019 at 4:48 PM
Subject: SCO Discovery - Recruiting SCO's

For near-term efforts…
 
FROM LUKE re Recruiting participants… 
 
If we want to reach out to SCOs my recommendation would be to group them based on the number of GI Bill students at the school.  
 
Using the data on the GIBCT we can break the schools up by the number of Post 9/11 GI Bill students they have.  The data shows:
•	75 schools have 1000 or more students
•	140 schools have between 500-1000 students
•	About 1000 schools have between 100-500 students
•	About 2000 schools have between 20-100 students and
•	About 5000 schools have less than 20 students.  
 
If we look at those groups and take a sampling from each I think we would get a sense of what the SCOs at schools with lots of users need and SCOs at schools with very few users need.  Ideally, everyone needs the same thing, but this would help in that part of the discovery as well.  
 
I am indifferent to the schools that are picked.  As Matt mentioned, Kevin just finished up some research and we can probably leverage some of that.  If you pull the file from the GIBCT you can select a couple of schools from each group (or feel free to break the groups up differently too, this way just made sense to me).
 
I should be able to get the SCO contact information if you have a list of schools you’d like to reach out to.  I can’t remember how Kevin did that but he may have some tricks for finding folks as well.
 
Thanks,
Luke 
 
 
From Kevin re: Cold Calling SCO’s
 
Not sure if you reached out to SCOs yet, but if it's useful, my cold call email copy:
Hello []!
 
My name is Kevin M. Hoffman, and I’m a Digital Services Expert at the Veteran’s Affairs Central Office. I help Veterans by researching and designing websites, applications, software for them and their beneficiaries. It’s nice to meet you!
 
I’m working on the tools we build for Veterans and their families to help them reach their academic and professional goals. We are currently conducting research with Veterans, service members, and the schools that support them through the Post-9/11 GI Bill and related benefits and policies.
 
Would you or someone on your team be open to scheduling a 45 minute chat with me?  I’d like to speak with the director of your Veteran’s Support Office (or similar) or any member of your staff who has detailed knowledge about how we help Veterans through the process. We would like to learn about the work you do with Veterans to help them achieve their goals, and how we might improve the tools we design and build to support that work.
 
We’re interested in speaking with one and only one person from your school that personally works directly with Veterans and/or has detailed knowledge of how that work is done.

**Comment by amyknox** [comment]
To recruit MOC / staffers 
- draft email for Terry Warren with brief description of our work.

**Comment by JenLJ** [comment]
@amyknox All non-Veteran users and current prospective stakeholders have been scheduled for interviews - closing story
