### ISSUE TITLE
GIDS: Add the ability to upload a single tab excel file

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14735]
As an EDU team member, I need the ability to upload excel files so that I can minimize the number of manual steps involved with maintaining the comparison tool

## Assumptions:
1. N/A

## Acceptance Criteria
1. The user can upload an excel file containing the corresponding data for all of the GIDS file upload types.

## Supporting Artifacts:
1. N/A

## Notes
When testing make sure to CSVs as well

Files types to test
- .xlsx
- .xls
- pipe delimited .txt
- comma delimited .txt
- .csv
- .csv with skip_line other than 0
- SCOs csv because it had issues with headers

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/738

To test upload and export various CSVs

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/737/

These files were added in sample_csvs to assist testing effort
- AccreditationInstituteCampus.xls
- AccreditationInstituteCampus.xlsx

This was tested using files below along with modifying `skip_lines` value after adding dummy lines to a file, yes this means skip lines should work with xls and xlsx
- AccreditationInstituteCampus.xls
- AccreditationInstituteCampus.xlsx
- program_pipe.txt
- program.csv
- accreditation_institute_campus.csv
- school_certifiying_officials.csv (this was used because of its header issue)

**Comment by zurbergram** [comment]
Roo gem PR - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/740
Refactor - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/741
Warning and Error ordering change for uploads - https://github.com/department-of-veterans-affairs/gibct-data-service/pull/742

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Tested by the following RestRail test case:
https://dsvavsp.testrail.io/index.php?/runs/view/703&group_by=cases:section_id&group_order=asc

**Comment by delli-gatti-michael** [comment]
This is now in Staging. Closing this issue
