### ISSUE TITLE
rename MVI lib to MPI

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#14738]
This change had to be reverted on 11/4 due to redis caching of MVI::Responses::FindProfileResponse
vs MPI::Responses::FindProfileResponse: https://github.com/department-of-veterans-affairs/vets-api/pull/5223

https://dsva.slack.com/archives/CBU0KDSB1/p1604514730074600
https://dsva.slack.com/archives/CQHBJ5U06/p1604507598335500

Update the MVI namespace in /lib to match the new name Master Person Index.  This is renaming the directory and then updating `MVI` namespace modules to `MPI`

**Comment by ericbuckley** [comment]
@LindseySaari an [error popped up on staging](http://sentry.vfs.va.gov/organizations/vsp/issues/6059/?environment=staging&project=3&query=is%3Aunresolved&statsPeriod=14d#) this morning that may be related to [PR#5213](https://github.com/department-of-veterans-affairs/vets-api/pull/5213).  It looks like `mvi_response&.profile` is raising an error because `mvi_response` is a Hash and it doesn't contain that attribute.  Can you think of any differences between using MVI and MPI that would have changed the value of `mvi_response`?

**Comment by LindseySaari** [comment]
Possible solutions:
1. Clear the cache before releasing the MPI rename changes
2. Temp solution to skip the cache if the cache.response has a class of MVI::Responses::FindProfileResponse
`if cached && !cached.response.is_a?(MVI::Responses::FindProfileResponse)
  #pull from cache  
else.  
  #add to cache
end. 
`
