### ISSUE TITLE
[Content] File Uploads: Review Error Messaging for Content

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#14752]
## Issue Description
We are updating the error messaging related to file uploads.  The linked story (#14751) will do the work of using the Rails error messaging framework to make sure we have a consolidated approach/location for these error messages.  This story is meant to review all the error messages now that they are in one place.

## Acceptance Criteria
- [ ] Content approval
- [ ] Updates made to messaging
---
## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Content is in https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/locales/en.yml. I'll come back and add some screenshots to give context to the error messages.

**Comment by peggygannon** [comment]
Thanks @annaswims and @luke-gcio thank you for adding screenshots! that will help with my review.

**Comment by annaswims** [comment]
This is how the error text will appear on form 526

![Screen Shot 2020-10-30 at 9.32.15 AM.png](https://images.zenhubusercontent.com/5bb3c3a61c43df49f8b08cfb/cf4c70bc-c044-4220-8a78-fc5b1aec9f57)

**Comment by peggygannon** [comment]
Hi, @annaswims @luke-gcio is this the only "file upload" error message we have right now? do we need to create messages for each document type that we can't open or upload?

**Comment by peggygannon** [comment]
@annaswims Here's my PL update to this validation error in above screenshot:

We can't open this PDF. Please save and upload it again.

**Comment by annaswims** [comment]
Here's the complete list of potential error messages, where the italics part is just he key (not displayed).  Thanks!

_carrierwave_processing_error:_ failed to be processed
_carrierwave_integrity_error:_ is not of an allowed file type
_carrierwave_download_error:_ could not be downloaded
_extension_whitelist_error:_ "You are not allowed to upload %{extension} files, allowed types: %{allowed_types}"
_content_type_whitelist_error:_ "You are not allowed to upload %{content_type} files"
_min_size_error:_ "File size should be greater than %{min_size}"
_max_size_error:_ "File size should be less than %{max_size}"
_document_type_unknown:_  Must use a known document type
_encrypted:_ PDF must not be encrypted
_malformed_pdf:_ PDF is malformed
_ascii_encoded:_ Cannot read file encoding. Text files must be ASCII encoded.

_locked:_ PDF must not be encrypted or locked. Please re-save it without a password
_invalid:_ We can't open this PDF. Please save and upload it again.
_incorrect_password:_ We're sorry, we were unable to unlock this PDF.

**Comment by peggygannon** [comment]
Hello, @annaswims Please see below for updated file upload error messages. Please let me know if you have any questions! 

File upload error validation messages: 

PDF is not able to be opened. Try re-saving or re-uploading it. 

- Updated message
**We couldn’t open this PDF. Please save it and try uploading it again.**

arrierwave_processing_error: failed to be processed


- Updated message: 
**We couldn’t process your file.**

QUESTION: Is there an action we could give the user to fix? should they resave and try again?

carrierwave_integrity_error: is not of an allowed file type

- Updated message: 
**We couldn’t upload your file because it’s not one of the allowed file types.**

carrierwave_download_error: could not be downloaded

- Updated message
**We couldn’t download your file. **

QUESTION: Is there an action we could give the user to fix? should they resave and try again?

extension_whitelist_error: "You are not allowed to upload %{extension} files, allowed types: %{allowedtypes}"

- Updated message: 
**You can’t upload %{extension} files. The allowed file types are: %{allowedtypes}"**

_content_type_whitelist_error: "You are not allowed to upload %{contenttype} files"

- Updated message: 

**You can’t upload %{contenttype} files. The allowed file types are: %{allowedtypes}"**


_min_size_error: "File size should be greater than %{minsize}"

- Updated message: 

**We couldn’t upload your file because it’s too small. File size needs to be greater than %{minsize}**

_max_size_error: "File size should be less than %{maxsize}"

- Updated message: 
**We couldn’t upload your file because it’s too large. File size needs to be less than %{maxsize}**

_document_type_unknown: Must use a known document type

- Updated message: 
**We couldn’t upload your file because it’s not a known document type.** 

encrypted: PDF must not be encrypted

- Updated message: 
**We couldn’t upload your PDF because it’s encrypted. Save your file without a password and try uploading it again.**

malformed_pdf: PDF is malformed

- Updated message: 
**We couldn’t upload your PDF because the file is corrupted.** 

ascii_encoded: Cannot read file encoding. Text files must be ASCII encoded.

- Updated message: 
**We couldn’t upload your file because we can’t read its characters. Text files must be ASCII-encoded.** 


locked: PDF must not be encrypted or locked. Please re-save it without a password

- Updated message: 
**We couldn’t upload your PDF because it’s encrypted. Save your file without a password and try uploading it again.**

invalid: 
We can't open this PDF. Please save and upload it again.

- Updated message: 
**We couldn’t open your PDF. Please save it and try uploading it again.**

incorrect_password: We can’t unlock this PDF.
We're sorry, we were unable to unlock this PDF.

- Updated message: 
**We can’t unlock your PDF. Save your file without a password and try uploading it again.**
