### ISSUE TITLE
GIBCT Redesign: Research indexing CT profile pages with VA.gov Elastic search

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#14817]
As a developer, I need to research elastic search so that I can understand how to include Comparison Tool profiles in the VA.gov search results.

## Assumptions: 
1. VA.gov primary site is using elastic search
2. We might need another environment to test elastic search for CT if we decide to do so
3. BAM2 (POC: Matt Self) is working on site search right now and can provide context if needed. 

## Acceptance Criteria: 
1. Research has been completed and documents how to include CT institutions within the VA.gov site search.

## Supporting Artifacts:
1. N/A

**Comment by elder-joseph** [comment]
### Associated Research: 

**What even is elasticsearch?**
Elasticsearch is an open source JSON-Based Search engine that searches indexed data quickly. Elasticsearch documentation has been pretty helpful in evaluating the tool.

**Installing and running Elasticsearch:**
Different options exist for installation, including homebrew for mac which I used for general evaluation and exploration of the tool. Setup is pretty straightforward. Elasticsearch can be installed on Windows, Mac, or Linux.

**Elasticsearch gems**
For my evaluation of elasticsearch with a rails application, I used the: 
`elasticsearch-rails` & `elasticsearch-model` gems. 
Currently, our rails apps that we commonly use do not have either of these gems bundled with them, so if we chose to use elasticsearch with GIDS, they would need to be added to the `Gemfile`.

**Setting up Elasticsearch Indexes**
Once the Elasticsearch gems have been bundled we need to tell the models (the ones we want to index at least) that they are going to be indexed using elasticsearch.

Generically this looks something like:

```
class ModelName < ApplicationRecord
	Include Elasticsearch::Model
	Include Elasticsearch::Model::Callbacks
end
```

Where the ModelName is an application record, but also a model to elasticsearch. Additionally, the callbacks are added so that anytime an instance of that ModelName are modified/deleted, the indexed data gets updated along with it.

From there, indexes can be defined in the rails application on the fields we want to use as it makes sense to optimize our search result sets.

However, this research is mostly related to standing up a new instance of elasticsearch vs leveraging the instance that is currently being used for the main va.gov site search.


**Usage of Elasticsearch for the va.gov main site search.**

An elastisearch instance must be run somewhere in order for it to be used to quickly index search results.
Elasticsearch can be run locally or remotely on “Elastic cloud”. Additionally, it can be run as a docker container. The install includes several binaries including a CLI option. Currently an instance of elasticsearch is being run via search.gov for the main site search.

It would be beneficial to know if we have (or could get) permissions to modify the existing elasticsearch instance configuration to add additional indexes, I am operating under the assumption that this would be possible. If we cannot or are not allowed to use/modify the existing elasticsearch instance to accommodate our comparison tool indexing needs, then we will have to setup our own elasticsearch instance in a separate environment, assuming we wish to leverage elasticsearch. This would also mean that our usage of the new elasticsearch index would be limited to the comparison tool search and not the site wide search.


The main site search located at https://va.gov leverages https://search.gov, which is built using Elasticsearch and takes advantage of its indexing features. As indicated on the https://search.gov/blog/. The main site search hits a search.gov API to return results.
 
![image](https://user-images.githubusercontent.com/48804834/97908519-ce24c600-1d14-11eb-9303-e7e8cb8b27fb.png)



**Adding Results to a search.gov site**

By creating an account on search.gov and associating it with a site, in our case va.gov, a user is able to add and edit site search configurations using an "admin center" page after logging in to search.gov, which acts as a front end to add new sites to the search results.

The search configurations and indices are managed by the search.gov team and in order for us to include search results and optimize indexing for comparison tool institutions, we will first need to add our pages to be indexed via a pragmatic approach to the search.gov admin page. After the results are added to the main search, we would then have to coordinate with the search.gov team to optimize the indices and deploy the changes making our search content and any updates live.

There appears to be a way to add pages/subdomains in bulk via an [XML Sitemap](https://search.gov/manual/sitemaps.html), which would need to be generated to reflect each of the GIDS institution profile pages to be searched. This sitemap is limited to 50MB or 50,000 URLs, whichever comes first.

This may or may not prove to be a practical approach to adding results to the main site.

**Comment by shawkey-daniel** [comment]
The VA.gov site search utilizes elastic search via search.gov. Elastic search utilizes sitemaps and web crawling to index content. The Comparison Tool (CT) is not currently configured to support web crawling. The CT generates content from data in a database. The CT could be configured to support elastic search with several optimization steps.

Elastic search utilizes HTML5 semantic markup to qualify the site content. CT content should be reviewed to ensure semantic markup is properly implemented to ensure indexed content is of highest quality. Semantic markup should be beefed up if it is found to be lacking.

Elastic search utilizes a sitemap to find content to index. A sitemap of search results could be generated from the database content. The sitemap would have to be generated each time a new version is generated in GIDS. The previous sitemap would have to be retained and compared with the new sitemap to derive the diff. 

Elastic search will utilize the sitemap to crawl all of the search result pages listed in the sitemap. Elastic search would be crawling approximately 34,000 search results and indexing the content. This operation could affect performance of the CT. A special server instance may be required to handle the web crawl. This could possibly be mitigated by limiting web crawl counts per day and utilizing slow traffic times.

The next step would be to setup a meeting with search.gov to talk about similar configurations and strategies.

Semantic markup - large to extra large
Sitemap generator - large
Sitemap diff tool - medium
Elastic search configuration - medium
Special server instance - extra large

**Comment by shawkey-daniel** [comment]
The VA.gov site search utilizes elastic search via search.gov. Elastic search utilizes sitemaps and web crawling to index content. The Comparison Tool (CT) is not currently configured to support web crawling. The CT generates content from data in a database. The CT could be configured to support elastic search with several optimization steps.

Elastic search utilizes HTML5 semantic markup to qualify the site content. CT content should be reviewed to ensure semantic markup is properly implemented to ensure indexed content is of highest quality. Semantic markup should be beefed up if it is found to be lacking.

Elastic search utilizes a sitemap to find content to index. A sitemap of search results could be generated from the database content. The sitemap would have to be generated each time a new version is generated in GIDS. The previous sitemap would have to be retained and compared with the new sitemap to derive the diff. 

Elastic search will utilize the sitemap to crawl all of the search result pages listed in the sitemap. Elastic search would be crawling approximately 34,000 search results and indexing the content. This operation could affect performance of the CT. A special server instance may be required to handle the web crawl. This could possibly be mitigated by limiting web crawl counts per day and utilizing slow traffic times.

The next step would be to setup a meeting with search.gov to talk about similar configurations and strategies.

Semantic markup - large to extra large
Sitemap generator - large
Sitemap diff tool - medium
Elastic search configuration - medium
Special server instance - extra large

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/research/elasticsearch/vagov.md
