### ISSUE TITLE
Rewrite IRIS Q&A about problems with PDF forms

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14981]
Based on information Nick provided, fact check and rewrite this IRIS Q&A:

**Why am I having problems with PDF forms on VA.gov?**

You may have an older version of Adobe Reader, the software you need to view and use VA forms. Please download the latest version of Adobe Reader 

If you’ve installed the latest version of Adobe Reader but are still experiencing problems using VA forms, your browser may be set up to use its internal PDF viewer instead of Adobe Reader. 

In this case, use your browser to download the form. Then, rather than clicking on the form to open it, open Adobe Reader, go to the File menu, choose Open, and select the VA form.

**Comment by jenniferlee-dsva** [comment]
One of the main reasons for this problem is a known issues with VA PDFs using a more recent format that's not supported by browsers. Suggest changing the order of the troubleshooting recommendations, because the more likely culprit is the VA pdf not playing nicely with modern browsers. Also, the PDF might not always be a form.

**What do I do if I'm having problems opening a PDF on VA.gov?**    {I don't think ppl care 'why,' they just want to know how to fix it; also, the pdf may not be a form}

The most common reasons for problems with opening PDF documents are browser settings or using an older version of Adobe Reader.

Try downloading and saving the PDF to your desktop. Then open the document directly by double clicking on the PDF on your desktop. 

If you still can't open the PDF, you may have on outdated version of Adobe Reader, and you'll need to download the [latest version of the free Adobe Reader](url).

**Comment by jenniferlee-dsva** [comment]
![image](https://user-images.githubusercontent.com/43381063/96461914-f67bd300-11f2-11eb-95fc-c10324cc1505.png)

**Comment by jenniferlee-dsva** [comment]
^ That's the error that appears on these pdfs. (BTW, image is not inteded for ^ Q/A bc screenshots are only enabled on the step by step format.)

**Comment by lunascoop** [comment]
I've updated the QA in Drupal, https://prod.cms.va.gov/node/8539. There's currently an issue previewing the page, https://dsva.slack.com/archives/CDHBKAL9W/p1603159435140900 but here's the copy for review:

### What if I'm having problems opening a PDF on VA.gov in my web browser?

First, try to download the PDF to your desktop and open it in Adobe Reader, the software you need to view and use PDFs. 

**To open the PDF in Adobe Reader**, open Adobe Reader, go to the File menu, choose **Open**, and select the PDF.

If you're still experiencing problems, you may have an older version of Adobe Reader. [Please download the latest version of Adobe Reader](https://get2.adobe.com/reader/).

**Comment by bethpottsVADEPO** [comment]
@lunascoop I'm wondering if we could make this a step by step... see below.

@jenniferlee-dsva @ncksllvn Is this accurate now?:

**What if I'm having trouble opening a PDF on VA.gov?**

1. Download the PDF to your desktop. 

2. Open Adobe Reader.

3. From the **File** menu, choose **Open**.

4. Select the PDF.   

If you're still having trouble, you may have an older version of Adobe Reader. Please download the latest version of Adobe Reader.

**Comment by lunascoop** [comment]
@bethpottsVADEPO I can create it as a step-by-step. Thus far, all of the step-by-steps begin with "How do I...." Should this title be rephrased?  

I think there are other instances of single Q&As with steps as part of the content, though they mostly are included as an accordion item for a multiple QA article (ex: _What if I see an error message when I try to sign in to VA.gov?_
in **Signing in to VA.gov** http://preview-prod.vfs.va.gov/preview?nodeId=8222).

**Comment by bethpottsVADEPO** [comment]
How do I open a PDF on VA.gov? 

Thanks @lunascoop

**Comment by lunascoop** [comment]
Hi @bethpottsVADEPO cc: @RLHecht I've re-created this page using the step-by-step template (http://preview-prod.vfs.va.gov/preview?nodeId=8684). I did add a page intro, which was required for the page template. I also moved the last line of the copy and link to the page intro since there is no "wysiwyg" content block included in the template. My only option was to rewrite the last sentence to fit in the intro, or add it to step 4, which did not look right. Here's the last sentence:

_If you're still having trouble, you may have an older version of Adobe Reader. Please download the latest version of Adobe Reader._

**Comment by bethpottsVADEPO** [comment]
@lunascoop I like your solution of moving the info from the last sentence to the intro. I'll take it from here! Thanks so much. The step by step was the way to go. @ncksllvn Do these steps makes sense from your perspective?

**Comment by bethpottsVADEPO** [comment]
@ncksllvn Sorry, never pasted in the steps:

**What if I'm having trouble opening a PDF?**

Follow these steps to open a PDF in your browser.
**Note:** If you're still having trouble, you may have an older version of Adobe Reader. You'll need to download the latest version.

THIS IS IN A SUBWAY MAP IN DRUPAL:
1. Download the PDF to your desktop.
2. Open Adobe Reader.
3. From the File menu, choose Open.
4. Select the PDF.

**Comment by bethpottsVADEPO** [comment]
Here's the preview link if you're on the network and want to see the full page:
http://preview-prod.vfs.va.gov/preview?nodeId=8684

**Comment by bethpottsVADEPO** [comment]
Closing. This is going out with MVP.
