### ISSUE TITLE
Analytics Reporting Request for TJ Rice/ Bilby Team

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#14984]
# Metrics Reporting Request

## What this form is for

Use this template to request one-off performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

We are trying to provide a solid SEO foundation for the application directory we are building right now. We would like to know what types of keywords or phrases users use when trying to find VA mobile apps, so that we can ensure people search for the app directory can find it.

- [Insert Name(s)]

    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
    
- What team/project is this work for?

This is for the VA Lighthouse API team Bilby (end user experience team)
    

## Timeframe for Analytics Requested
Ideally we would have this in a week or so.

## Analytics to Track Down
> Examples
> 
> - [ ] top searched terms or phrases on google coming to VA.gov
> - [ ] Top searched terms of phrases on VA.gov's search 

## Other Helpful Questions to think through
- Who is your audience?
    -  Veterans, Their family members, maybe VSOs. 
- Why do you need this data?
    - So we can have a better SEO experience to ensure user can find our page when using search engines. 
- What are you hoping to find?
  - key terms of phrases we can use that user.
- What is your hypothesis that you're hoping the data will support?
  - Users are trying to find mobile apps on VA.gov.
- What area of the VA are you hoping to assess?
  - All, but for now Health  
- How frequently do you need this data?
  - For now just once, but we may want to reevaluate after a period of time to see if search behavior has changed. 

## Additional Comments

Ref: https://dsva.slack.com/archives/C1Q4294JJ/p1602866156037900

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Thanks @ricetj , acknowledging receipt!

**Comment by bsmartin-ep** [comment]
I also added you to the [Google Search Console](https://search.google.com/search-console) if that's immediately helpful @ricetj.

**Comment by ricetj** [comment]
> I also added you to the [Google Search Console](https://search.google.com/search-console) if that's immediately helpful @ricetj.

O interesting. I will have to play around with this

**Comment by ricetj** [comment]
> I also added you to the [Google Search Console](https://search.google.com/search-console) if that's immediately helpful @ricetj.

@bsmartin-ep any tips on how to find what I am looking for?

**Comment by bmcgrady-ep** [comment]
@ricetj Here are a couple of reports that I believe will help answer your questions:

1. [Google Search Console Report](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fwww.va.gov%2F&search_type=WEB) with the most searched terms on Google. I searched for `mobile`, `apps`, and `mobile apps` with little results. You can filter for different terms by selecting "New" and then "Query" as outlined in the screenshot. 
![image](https://user-images.githubusercontent.com/66263904/96758778-0da1f880-138c-11eb-973c-e8fb739ee134.png)

2. [GA Search Terms Report](https://analytics.google.com/analytics/web/#/report/content-site-search-search-terms/a50123418w177519031p176188361/_u.date00=20200101&_u.date01=20201020&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.searchKeyword%22,%22RE%22,%22mobile%20app.*%22,0%5D%5D&explorer-table.rowCount=100) - This shows all of the search terms on VA.gov related to `mobile app` since January 2020.

**Comment by bmcgrady-ep** [comment]
@ricetj - After checking with Jon and Brian, we don't have access to the GA or GTM for mobile.va.gov website. Let me know if there is anything else you need in regard to this request. Thanks!

**Comment by joanneesteban** [comment]
@ricetj we're closing this ticket, but please let us know if you need anything else!
