### ISSUE TITLE
Implement fourth chunk of account and profile and other MVP content in drupal

### ISSUE THREAD

**Issue by bethpottsVADEPO** [department-of-veterans-affairs/va.gov-team#14980]
## Issue Description
Attached here in two Word docs is content that needs uploading into drupal in the R&S templates. One doc has the claims and appeals content, and the other has other topics and questions.

[https://app.zenhub.com/files/133843125/0adba3d9-bde8-42e6-a2bf-adc72d44ad2b/download](https://app.zenhub.com/files/133843125/0adba3d9-bde8-42e6-a2bf-adc72d44ad2b/download)

[https://app.zenhub.com/files/133843125/a73094f2-89f2-4fe5-b6cb-f8cbc8d18216/download](https://app.zenhub.com/files/133843125/a73094f2-89f2-4fe5-b6cb-f8cbc8d18216/download)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by brianalloyd** [comment]
Adding to Sprint 33 as discussed in SU.  @RLHecht or @lunascoop could please provide an estimate in support of planning efforts for next sprint.  TY in advance.

**Comment by lunascoop** [comment]
Finished inputting the copy from first doc. Here are the node links and addt'l notes:

### How can I find out the status of my VA claim or appeal? 
http://preview-prod.vfs.va.gov/preview?nodeId=8504 need to add related info links for first two items.

### What types of claims and appeals can I track online? 
http://preview-prod.vfs.va.gov/preview?nodeId=8514 tagged Kelson to review the Related Info field. It's showing in preview although no content has been added.

### What you can learn from the claim tracking tool 
http://preview-prod.vfs.va.gov/preview?nodeId=8528 I repeated the CTA buttons per the specs in the Word doc but it doesn't seem necessary. Also added intro text per Beth's comment here: https://dsva.slack.com/archives/G018JLSB4A2/p1603140000014400
#### H2: Information provided in the claim tracking tool (Changed "status" to "tracking" per Beth's comment) here:https://dsva.slack.com/archives/G018JLSB4A2/p1603139930014100
- What kind of information can I get from VA.gov’s claim tracking tool? https://prod.cms.va.gov/node/8515
- Why does my VA.gov claim info seem different from what’s on eBenefits? https://prod.cms.va.gov/node/8522 rephrased question to not exceed character count https://dsva.slack.com/archives/G018JLSB4A2/p1603138704012000
- Can the tool tell me when I’ll receive a decision letter for my claim? https://prod.cms.va.gov/node/8521 removed "VA" from question title to not exceed character count

### What does my claim status mean? 
http://preview-prod.vfs.va.gov/preview?nodeId=8516

### Managing your documents with the claim tracking tool 
http://preview-prod.vfs.va.gov/preview?nodeId=8523 I made this using the learning center about page template. But, I did attempt a single QA template version first: http://preview-prod.vfs.va.gov/preview?nodeId=8517

### Steps to checking your VA claim or appeal status online 
http://preview-prod.vfs.va.gov/preview?nodeId=8520

**Comment by lunascoop** [comment]
I've finished entering the content from the second word doc. Here are my notes and node links:

### How do I get my discharge upgraded or changed? 
http://preview-prod.vfs.va.gov/preview?nodeId=8541 I made this a learning center detail page instead of a single QA

### How can I be rated competent and exit the Fiduciary Program?
http://preview-prod.vfs.va.gov/preview?nodeId=8540 
- added CTA button per Beth's comment here: https://dsva.slack.com/archives/G018JLSB4A2/p1603145242024100?thread_ts=1603144455.023500&cid=G018JLSB4A2 
- The related info links to the modern VA locations page

### Why am I having problems with PDF forms on VA.gov? 
http://preview-prod.vfs.va.gov/preview?nodeId=8539 
- This is currently a Single QA template page, which requires a CTA button (find a VA form). Perhaps I can create this as a Learning Center detail page

### What’s VA's policy regarding service dogs? 
http://preview-prod.vfs.va.gov/preview?nodeId=8538 

- This is currently a Single QA template page, which requires a CTA button (find a VA location). Perhaps I can create this as a Learning Center detail page

**Comment by RLHecht** [comment]
The work has been completed in this ticket. Reworking the question about PDFs is captured in #14981 and the related info/buttons will be worked on in #14979. FYSA @bethpottsVADEPO @brianalloyd
