### ISSUE TITLE
Urgent Care:  Add info back into Community Care Facility Locator

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#1499]
As a Veteran, Family member, Caregiver, I need to be able to use the facility locator to search for Urgent Care facilities that are in or near my location, so that I can easilly find the Urgent Care location and type I need.

 **Problem:**
When the Mission Act was launched on 6/6/19, Urgent Care services were removed from the Facility Locator due to incorrect data being returned. 
       _Note:_  The data will supposedly be fixed around 9/10/19. 

**Goal:**
-Complete work by November at the latest; ideally should be completed prior to November for future OCC work.

**Acceptance Criteria:**
- [ ] Urgent Care is listed in the dropdown for Community Care Facility Locator 
- [ ] Dropdown for service Type includes urgent care locations 
- [ ] Dropdown for service Type includes urgent care locations with Retail 
- [ ] Database will store both retail and non retail Urgent Care Facilities as:
      - [ ] Place of Service (POS) 17:  Urgent Care locations with Retail 
      - [ ] Place of Service:  Urgent Care locations without Retail

**Comment by ncksllvn** [comment]
@Karak888 I moved the issue to `va.gov-team` for you 😄

**Comment by Karak888** [comment]
many thanks @ncksllvn !

**Comment by ncksllvn** [comment]
I tested in Staging and it looks good to me!

Urgent Care search -
https://staging.va.gov/find-locations/?address=10%20Chapman%20Lane%2C%20Newport%2C%20Kentucky%2041076%2C%20United%20States&context=Newport%2C%20Kentucky%2041076%2C%20United%20States&facilityType=cc_provider&location=39.03%2C-84.46&page=1&serviceType=261QU0200X&zoomLevel=9

Community/Retail Pharmacy search - 
https://staging.va.gov/find-locations/?address=10%20Chapman%20Lane%2C%20Newport%2C%20Kentucky%2041076%2C%20United%20States&context=Newport%2C%20Kentucky%2041076%2C%20United%20States&facilityType=cc_provider&location=39.03%2C-84.46&page=1&serviceType=3336C0003X&zoomLevel=9

**Comment by Karak888** [comment]
@ncksllvn @chrisj-usds are there any outstanding things that need to be completed here? Chris I know you said there would be follow-up items but will we be able to create those as new tickets under our PPMS Epic?  @ncksllvn looks like you just had that one merge, do you need any further PRs or reviews needed.  Thanks!

**Comment by ncksllvn** [comment]
I'm not sure I follow what this piece means - `Database will store both retail and non retail Urgent Care Facilities as:` but everything else appears to be complete with just that one PR!

**Comment by ncksllvn** [comment]
The options show as `Clinic/Center - Urgent Care` and `Pharmacy - Community/Retail Pharmacy`.

**Comment by Karak888** [comment]
@chrisj-usds I will wait for your blessing here or what if anything needs to be done for this specific ticket?  Thanks @ncksllvn !!

**Comment by chrisj-usds** [comment]
Short answer: approved. 
Longer answer: we're not quite done. There are a few things that we need to do and some we should try to improve. Examples: 

- Take out the link to tri-west
- OR perhaps update the text and link to be "quick access" to our urgent care and pharmacy search
- Generally, we need to improve the way these searches work, because nobody is going to search for "Pharmacy - Community/Retail" especially when there 20+ entries that start with "pharma"

**Comment by Karak888** [comment]
thanks @chrisj-usds - Short term for our current sprint, I will move this ticket to done.  Will look into some research for bullets 2 and 3 above..(I am actually going to stop adding "..." after prepositions, because Danielle told me that is no longer the rule, and I was blown away)! 
- bullet 2 we can probably do rather easilly (understanding that new Facility Locater will likely be proposing a new UX experience for long term)? The question mark is that I have no idea what that team will be responsible for (yippee another preposition)! 
- How much effort would you like for us to put into improving these searches (bullet 3 above)?  We can certainly attack it via research and certianly make improvements, just not sure how far you would like for our team to dig into (hahaha I can go all day)!

Thanks!! @ncksllvn btw, SUPER IMPRESSIVE getting this ticket knoked out;  we are learning that  client expectations are higher than what has been produced to date (and I don't blame them)!

CC:  @jenniferlee-dsva

**Comment by Karak888** [comment]
@Karak888 to go back to 3 bullets provided by @chrisj-usds and get tickets made for those.
