### ISSUE TITLE
[DESIGN]: Should the Express Care radio button labels be bold, or regular weight like requesting an in-person appointment?

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#15084]
## Issue Description
While auditing the Express Care feature, I noticed the radio button labels for Express Care were bold, where our labels are typically regular weight. The screenshot below is not exactly Express Care. The window for today closed while I was creating this ticket, so I approximated by making another group of radio button labels bold for illustration only. Adding VSP design for a judgment call. 

---
## Tasks
- [ ] Confirm the design is correct, or offer guidance on updates needed

## Acceptance Criteria
- [ ] Design will be updated **or** ticket closed with no work needed

---
<img width="886" alt="Screen Shot 2020-10-20 at 4 27 59 PM" src="https://user-images.githubusercontent.com/934879/96646406-b5b6b380-12f1-11eb-80ca-7c700b1e33f5.png">

**Comment by rtwell** [comment]
my recommendation would be to make all of our radio buttons consistent across the app. with the addition of the descriptors to the types of care, we've got another layer to incorporate. @outerpress this might be a good experiential design problem to solve as we work on decoupling requests/appointments

**Comment by outerpress** [comment]
@rtwell are there any other radio button patterns aside from...

1. Radio button + label
2. Radio button + "header" label + additional descriptive text

...that we should be looking at as part of this?

My initial thought for #1, we shouldn't make all of the labels bold - if every option is bold, there's no hierarchy benefit. And for #2, the header labels should always be bold so they're easy to scan.

**Comment by rtwell** [comment]
i'm semi-indifferent—if they are all bold or all not-bold, in both scenarios all are equal anyway. I'm thinking more about consistency across all instances of radio buttons, and any combination thereof. A scenario that might (and probably will) come up is: what does it look like if those two scenarios are mixed: a mix of single-line and single+description options?

**Comment by outerpress** [comment]
I finally got into Express Care and hey hey, it's a mixed list. I tried three treatments [(Mural for the curious)](https://app.mural.co/invitation/mural/adhoccorporateworkspace2583/1604960234680?sender=ub08ff1d80ee7bd38d6c02354&key=aa44cf80-e2d9-45bc-b03a-3992c1762d01) and I think all bold is the most easily scannable when you have mixed headers and non-headers.

Having some headers bold and others non-bold just looks weird. But if nothing's, bold the added descriptions just look like a long label that I'd skip over.

So I'd say header lists and mixed lists should get the bold treatment, standard lists should not.

@emilywaggoner do you want to weigh in from a VSP perspective?

**Comment by rtwell** [comment]
any chance you can make that mural public-viewable? apparently my adhoc mural account is deactivated because of inactivity (although I have been on mural a bunch). im wondering if i have multiple mural accounts? either way would you mind posting here or making it public? thank you!

**Comment by outerpress** [comment]
Don't mind at all, this _should_ work: https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1604960234680/788d1185c94b99665dedd7e92243a30034a92002

**Comment by emilywaggoner** [comment]
So I agree with the following that Peter said:
- Standard lists should not be bold
- Lists with headers should have a bold header, normal description

But I'm not totally convinced about the mixed list. How likely is it that we would have a situation with a mixed list? 

Thinking about looking at this on mobile, a mixed list could look like a bold list for much of what appears in the viewport. Wondering if it's worth the weirdness of bolding only the headers in a mixed list because of that.

**Comment by rtwell** [comment]
VAOS has a couple of instances of the mixed list, unfortunately. And i'm guessing your brain is going where my brain is, asking "should we carry this formatting through to all of our radio buttons…and if so, what happens when a bold radio label is next to a regular checkbox"? and it quickly spirals into a design system / form system problem not a VAOS problem. However, when a mixed list is on the same page with other form components (e.g. check boxes and drop downs and radio buttons on the same form page), which i can totally see happening across forms, it might look like the radio buttons are somehow more important if we went with the bold treatment across all radios. hmmmmmm 🤔 

I'm wondering if the bold/not bold is trying to do the heavy lifting of the UX. The reason we have the items with headers/description is b/c we learned Veterans were having challenges understanding what it means to schedule an appointment for "**Joint or muscle pain or minor injury**". I don't know about you but I could not tell you if a possible sprained ankle (which can feel pretty severe) qualifies as a "minor injury". However, this is the language we have to work with from VHA (which we can ask to change if we want). Given that, should we consider a different UX for this situation? Maybe the [additional info component](https://design.va.gov/components/additional-info) could be utilized to allow Veterans to read more about a thing, whilst not creating inconsistency with bolding some things and not others across pages/forms.

**Comment by rtwell** [comment]
OR perhaps this is grounds for a **new tooltip componenttttttttttttt** 🎉

**Comment by outerpress** [comment]
Sorry I've been plodding in getting back to this one.

I like the idea of providing the additional descriptions as needed, maybe not in additional info blocks (In my head it looks like rows of dotted lines, very distracting). But a tooltip could work!

Some stories are coming up to improve the type of care list, one of which adds the header list pattern. Those would be good opportunities to try a new tooltip pattern.

- https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/14108
- https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/16412

**Comment by emilywaggoner** [comment]
I have also been meaning to get back to this one! We did some research earlier this year on the usability of tooltips, including the accessibility of them, vs. the [additional info component](https://design.va.gov/components/additional-info) for providing contextual help, and found that tooltips performed worse all around. The exception to this perhaps worth exploring is a tooltip used for explaining an acronym. Attaching the readout from that research here. Let me know if you have questions or other thoughts about it!

[Learn More Research Presentation.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5569134/Learn.More.Research.Presentation.pdf)

**Comment by 1Copenut** [comment]
I agree with @emilywaggoner . We had a level of confusion around tooltips. There's a possibility my research test tried to do too much with not enough distinction between additional information and tooltips, causing the participants' hesitation. If you do decide to explore tooltips, I'd encourage a CSS-only solution (tested better) and use it as Emily suggested for things like unpacking acronyms.

Here's the Codepens we used to test with research participants and for inspiration:
* Testing - https://codepen.io/tpierce_402/pen/PoYVKKa
* CSS-only tooltips - https://codepen.io/cbracco/pen/nufHz

**Comment by outerpress** [comment]
I played with using the additional info option, steering clear of tooltips as suggested - and IMO it adds a lot of unnecessary noise and interaction (added to the [Mural here](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1604960234680/788d1185c94b99665dedd7e92243a30034a92002)) . I worry it could get overused, and if I'm scanning the page for information it's a lot more work to dig into each, and you'd need to open all of them to compare options.

Is 16px our minimum size for typography? We could drop the font size of the description text, or lighten it (or both) if we can maintain a good contrast ratio. 

I added a couple of examples of that to the Mural as well. @1Copenut would those cause accessibility issues?

**Comment by 1Copenut** [comment]
@outerpress & @rtwell I took a look at the Mural and I agree, the existing UI patterns add visual (and cognitive) noise to the radio button labels. It does seem a tooltip would be an opportunity worth exploring. I have a few requirements if we go this route:

* The tooltips must be CSS only, no JavaScript. The second tooltip in [this Codepen](https://codepen.io/tpierce_402/pen/PoYVKKa) is CSS only and tests well with screen readers. Jennifer found that example and linked to an original Codepen in the CSS comments.
* The tooltips have a hard character limit, and it be a short one. Tooltips should be used to spell out acronyms like TOP (Treasury Offset Program) or describe symptoms like "Such as pain in your joints, a twisted ankle or sprained wrist" using plain language.
* There must be no interactivity like buttons or links. If we need to link out to a resource, it's better to have that link inline after the `<label>` element.
* Tooltips must have SR-only text that can be passed in as a prop to the React component, so we don't have a lot of links with "Learn more" as the semantic label. Ideally, the visual text and semantic text could match, but I understand that may not be possible.
