### ISSUE TITLE
Frontend - Add mailing and home address to the 10-10EZ

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#15159]
As a Veteran
I want to be able to distinguish between my mailing and home address on my health care application
While logged in or unauthenticated
So that I can be contacted in the best way by the VA.

Frontend: See designs [here](https://vsateams.invisionapp.com/share/3WZ5PNQSX67#/screens/435149167_Unthenticated-Blank_-v-2-2) 
Backend: Update backend to use Address types: 
P - “Permanent” aka Mailing Address
R - “Residential” aka Home Address

Note: this feature should be flagged and rigorously tested before being deployed to Production.

Acceptance Criteria
- [x] Form prefills address and if they have two addresses in profile and they dont match then prefill
- [x] Form duplicates address and send if they are the same 
- [x] Feature flip allows for fallback functionality (one address without yes/no question) and only sends one address
- [x] Feature flip is integrated with preSubmit transformer and removes all extra data if flip is off

Note:
- [ ] If is flip on with SaveInProgress data saved the data is cleansed of additional data and UI before user continues form will be reserved as an enhancement

**Comment by LinnJS** [comment]
@ala-yna not sure why this ticket isnt showing up on the VFT board, tried to change pipeline but nothing happened

**Comment by ala-yna** [comment]
10/14 Team Meeting notes:

- Reach out to Josh/HCA team:
     - Is there a field that accepts whether mailing and residential address are the same? 
     - Do we want to send both if they are the same?
     - If the second address isn't there, do we want the backend to fail?

- When/how are we implementing the backend changes?

- To do: Ming to reach out to HCA team, team should follow up on technical questions
- Alayna: Schedule a time with Mike to talk through dual implementation (for testing in Staging)

**Comment by LinnJS** [comment]
Conversation with Chris from VSP on moving parts to feature flip a schema breaking change
https://dsva.slack.com/archives/CBU0KDSB1/p1607958122212900

**Comment by LinnJS** [comment]
Currently the feature flip is being implemented via a `flipper` API call via redux thunk on HCA Application mount. I am then storing the feature flip in formData so I can turn pages on and off according to the boolean.

The problem with this is the app state gets rehydrated without a refresh so the feature flip state remains the same. The only way to fix this is to be able to access that boolean value at the SaveInProgress transform level to cleans the data before the app rehydration takes place. There is currently no way to access this data at that function transformer level due to it not being in a React/Redux environment which is only explicit way feature flips are to be implemented currently as per these [docs](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#add-feature).

I have discussed solutions with peer engineers in this [slack thread](https://dsva.slack.com/archives/CBU0KDSB1/p1609177498311200) and have also done my own research and have a theoretical solution but am having trouble implementing it in the context of the FormBuilder platform code.

**Comment by LinnJS** [comment]
After non-stop testing today I found that the future flip is working really well for non-authenticated non-saved forms after a refresh in between toggling the feature flip.

As for SaveInProgress experiences the state is currently always being persisted regardless of state after being toggled as described above.

**Comment by jonathanjnelson** [comment]
@LinnJS and @ala-yna 

Wanted to document the conversation here around: 

- Content on the 10-10EZ address pages 

### Content 

Current designs: 

**Mailing address**

![Screen Shot 2021-01-05 at 12 01 04 PM](https://user-images.githubusercontent.com/58444931/103683642-113b2980-4f50-11eb-9f82-1910d0dea080.png)

**Home address**

![Screen Shot 2021-01-05 at 12 19 31 PM](https://user-images.githubusercontent.com/58444931/103683993-860e6380-4f50-11eb-8c34-865b85ae28ab.png)

**Currently the content is not in FE. Can we add the content to the FE?**

- [ ] Mailing: 

_We’ll send any important information about your application to this address._

_Any updates you make here to your address will apply only to this application__

- [ ] Home: 

 _Any updates you make here to your address will apply only to this application._

**Comment by jonathanjnelson** [comment]
Hi again @ala-yna and @LinnJS 

Wanted to start a conversation around the address fields: 

### Address pattern

Current designs: 

![Screen Shot 2021-01-05 at 12 01 04 PM](https://user-images.githubusercontent.com/58444931/103684291-f9b07080-4f50-11eb-98cc-668846d619cf.png)

Staging: 

![Screen Shot 2021-01-05 at 9 33 15 AM](https://user-images.githubusercontent.com/58444931/103685758-5f056100-4f53-11eb-8995-bbab6c6d31c9.png)

I was under the understanding VA.gov was now collecting addresses with the "This is a United States military base..." checkbox. @LinnJS I know we touched on this briefly. Did you find out anything regarding this pattern?

**Comment by LinnJS** [comment]
Discussion in platform support about using migrations as well as other methods to redirect users around based on a feature flip.

https://dsva.slack.com/archives/CBU0KDSB1/p1609965817104600
