### ISSUE TITLE
Test CH36 Submission Process

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#15152]
## Goal
CH36 uses Central Mail as its submission process; we need to now test its submission for CH36 to operate properly in staging.

## Tasks
- [x] Test in staging

## Acceptance Criteria
- [x] A first pass at testing CH36 has been attempted, results documented in this ticket below

**Comment by digitaldrk** [comment]
This took way longer than expected.

## Desired Outcome
We hoped that if we pushed the code to staging we would get a successful response from central mail since our computers do not have login credentials for the central mail service.

## Actual Outcome
We are still receiving an error. It is not clear though if it is the same error although it _acts_ the same way in that no new code added from this feature is throwing errors.

Steve is still going back and forth it seems with folks in va email, sounds like they don't even have a 'staging' type env to send to anyway, also since the deadline for this project got pushed back, I shelved this effort to complete other objectives.

## Steps Taken
We ended up just pushing code to Staging since there were login issues with the review instance in the feature branch. Then we tested in staging, got an error, and then created a new branch and PR with added error reporting to see what exactly the error was. There were conversations in vfs-platform-support about the login issue being resolved with new PRs. I was still not able to login though.
