### ISSUE TITLE
Set up CI to create a PR in vets-website with the updated component library dependency version

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#15173]
## Issue Description
Set up CI to create a PR in vets-website with the updated component library dependency version

---
## Tasks
- [ ] Set up continuous integration to create a pull request in vets-website with updated dependency version

## Acceptance Criteria
- [ ] CI creates PR in vets-website with updated dependency version 
---

**Comment by bkjohnson** [comment]
Dependabot can already do this - [it was disabled due to the volume of PRs it was creating](https://github.com/department-of-veterans-affairs/vets-website/pull/14242). We could look into enabling it again possibly with some restrictions.

We could use the [`allow` option](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#allow) to only trigger on certain dependencies, for example.

**Comment by k80bowman** [comment]
I'm not sure about this one. Even if we are auto-creating PRs in vets-website when we release a new component-library version, I would still want the person creating the release to test the new version in vets-website before it gets merged. It worries me that someone on release tools could merge this kind of PR before we have a chance to make sure things are working correctly.

**Comment by bkjohnson** [comment]
That's valid. One thing that could help prevent that is that dependabot can automatically put release notes in the PR description, so ideally nobody would approve it before the listed changes have been tested. There's still the risk of someone approving without testing though.

**Comment by k80bowman** [comment]
I very much doubt anyone not on our team is going to test these changes before approving. If anything, they would probably ping our team to test them. But that's dependent on who is doing the review. I just wonder how much work something like this actually saves us and if it's worth spending time on.

**Comment by bkjohnson** [comment]
I'm fine with working on other things, I was just looking through old issues. I also don't want people merging a version bump before we've had a chance to test things.

**Comment by caw310** [comment]
Closing as this is old.
