### ISSUE TITLE
Loading state for new facility page may be confusing

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#15184]
Based on the breadcrumbs in this Sentry issue, the way we disable radio buttons makes it look like we unselect a users option while they're waiting for eligibility or other things to happen. We also don't appear to disable links during this state.

We may want to consider handling the loading state differently.

http://sentry10.vfs.va.gov/organizations/vsp/issues/4084/?environment=production&project=4&query=is%3Aunresolved+url%3Ahttps%3A%2F%2Fwww.va.gov%2Fhealth-care%2Fschedule-view-va-appointments%2Fappointments%2Fnew-appointment%2Fva-facility-2&statsPeriod=24h

**Comment by outerpress** [comment]
Just to sum up the slack thread on this issue:
* Currently the page load notification shows an alert under the next/continue button, so it can show below the scrolled position - effectively hidden.
* That load notification is styled as a static notification box, so it doesn't call attention to itself, even if the veteran can see it

To solve this, we discussed:
* A page overlay loading spinner (similar to the calendar page)
* The page overlay loading spinner should only show up after three seconds, as this process happens quickly most of the time, and we want to avoid most users seeing a message flashing by so quickly that they can't read it.

@narin does that sound right to you? I'll work on getting together a mockup of the loading overlay.

**Comment by narin** [comment]
@outerpress Yes that sounds about right.  Here is a what a potential overlay could look like:

![image](https://user-images.githubusercontent.com/786704/97138253-fe68d500-1714-11eb-98ad-dcf05f63c407.png)

I have it overlaying just the radio buttons, but could make the rest of the top transparent as well depending on what you think is best. 

@peggygannon This copy is duplicated from the alert box we were previously showing below.  Maybe we could make it a little less wordy since it's now showing as a loading message.  What do you think?

**Comment by outerpress** [comment]
@narin it'd make sense to overlay all of that content. We don't want them doing anything on that page until loading is complete, and the only content that's really important at that point is the loading text.
