### ISSUE TITLE
Convert Prometheus SSOe metrics to Utility

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#15191]
Currently the SSOe prometheus metrics we rely on are only kept for 2 weeks, we need to move the metrics over to the utility side of prometheus to ensure the logs are kept longer than 2 weeks. If we can pick an expiration I would make the metrics expire after 1 year.

**Comment by joeniquette** [comment]
https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/rules/job.rules and https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/prometheus/prometheus.yml.j2#L149-L160 are what we need to work with.

**Comment by bramleyjl** [comment]
Metrics collection is in the process of being moved to DataDog, so spending resources to improve Prometheus metrics would not provide long-term benefits. The default for [DataDog system metrics retention is 15 months](https://docs.datadoghq.com/developers/faq/data-collection-resolution-retention/#pagetitle), so that takes care of the 2 week issue that Prometheus metrics currently has. I will start looking at our current DataDog metrics to make sure that all of the currently-monitored ones on Prometheus are moved over properly.

**Comment by dginther** [comment]
Hi @bramleyjl , I have new information regarding the DataDog transition, which is that we cannot expand our currently installed agent base until more licenses become available, so we will actually need to do this work in Prometheus instead for the time being. Let me know if I can be of assistance to you in the meantime. The date we currently have for **starting** to sunset Prometheus is June of 2021.
