### ISSUE TITLE
Missing section - /decision-reviews/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15206]
## Issue Description
There is a missing section

## Example:
![Screen Shot 2020-10-22 at 4.53.16 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/89fe4a50-17ee-4384-a357-4023e1256759)

## Example File
`/decision-reviews/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.

**Comment by theodur** [comment]
After looking into this issue, I discovered the section is missing because the `fieldAlert` field is `null`. I believe there is a problem with the graphql query or cms-export. 

The corresponding `fieldAlert` entity (`.cache/localhost/cms-export-content/block_content.97cd6b1d-a0dc-4c96-8694-50ba3b78dec1.json`) has a status of `false`. This means our transformation process is correctly not including that entity. This is most likely related to the same problem [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15339#issuecomment-721347968). 

Once this [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15756) is resolved, this problem should be resolved.

**Comment by kevwalsh** [comment]
I've addressed this in the content layer. the Alert was unpublished. There's a frontend GraphQL bug that allows unpublished alerts to go out. The PW team will be working on that at some point in #15756, but in the meantime you still may see a few of these. FWIW, Content export / transformers is treating this "correctly".

**Comment by theodur** [comment]
This issue was resolved by the cms team fixing the [content layer.](https://dsva.slack.com/archives/C01512KN35G/p1604508451126000?thread_ts=1604499661.123700&cid=C01512KN35G)
