### ISSUE TITLE
Build appointment list selector page

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#1528]
## Story
As a veteran, I want to choose whether to view my confirmed, pending, or past appointments so that I don't get confused about which appointments are scheduled successfully and which appointments aren't confirmed yet.

## AC
- [ ] Page exists on staging and not in production
- [ ] Page reflects latest mocks in https://adhoc.invisionapp.com/share/WATIINRHZ3F#/screens/379622473
- [ ] UX for empty list(s) confirmed with Ryan and integrated into this page's behavior
- [ ] Business logic for current VAOS frontend appointments list documented in this ticket (e.g., fact that current tool lists all appointments in one view and doesn't allow filtering by status)

![Screen Shot 2019-09-04 at 11 24 28 AM](https://user-images.githubusercontent.com/24251447/64273294-9e0e4700-cf06-11e9-957a-bb4857bdbaae.png)

**Comment by markgreenburg** [comment]
@rtwell can you confirm UX for cases where one or more of these three appointment status types are empty? Should the category show at all? Do we need to indicate that an empty status type isn't clickable because it's empty? Etc. Thanks!

**Comment by rtwell** [comment]
ah, good question! i will dive into this.

**Comment by jbalboni** [comment]
Note that because we have the counts there, we should probably initiate the api calls here. However, I don't think we want to block the whole page waiting on those calls. We can just hide the counter text while the calls are returning. If user clicks through to the next page before the request is done, we can show a spinner while the call finishes.
