### ISSUE TITLE
Wrong data - /outreach-and-events/events/past-events/

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#15362]
## Issue Description
There are some sections that are wrong

## Example:
![Screen Shot 2020-10-27 at 2.28.09 PM.png](https://images.zenhubusercontent.com/5d89589c3ac3440001d19c89/f79b4d04-091b-4ecc-a764-40e966d2a0a0)

## Example File
`/outreach-and-events/events/past-events/index.html`

## Tasks
- [ ] Figure out why the discrepancy exists.
- [ ] Fix the issue

**Comment by theodur** [comment]
The wrong sections isn't an issue anymore. They were most likely fixed in the CMS export. Now the only discrepancy for `/outreach-and-events/events/past-events/index.html` is `window.sideNav` is blank in the GraphQL. This problem doesn't seem related to transformers, as the CMS export properly displays the populated `window.sideNav` links.
