### ISSUE TITLE
[Call Centers] Schedule Relationship Revitalization Meetings w Call Centers

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1546]
## User Story
As a call center lead, I need to maintain and build relationships with VA call centers so I can work closely with them on improving the customer experience and get access to critical metrics and data.

## Goal
Schedule meetings with WHH, NCC, and Education. 

## Acceptance Criteria
- [x] Reconnect with WHH to discuss and finalize outstanding documents (current escalation process and CRM development).
- [x] Set up meeting with education call center to discuss operations and collaboration on reporting and issue triage
- [x] Follow up with NCC to determine if any additional materials or work is needed for direct deposit launch.

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by clantosswett** [comment]
Recap of conversation with Education Call Center Conversation on 9/9:

The call was with Mary Ann McMullen and Brian Ellis from the EDU call center as well as Kevin Hoffmann and Matt Self from DSVA. The call was primarily focused on understanding how the call center works and how they go about tracking the calls and the associated metrics. We learned that there is a daily/weekly email that is a readout of those daily/weekly metrics. A request was made to be added to that report but so far we haven't received any confirmation that we have been added. I would like to additional outreach to this team to see if we can get some more insight into how they handle issues related to VA.gov technical problems. This call center is a big one and it would be great to improve our relationship and collaboration with them.

**Comment by clantosswett** [comment]
Recap of conversation with White House Hotline Team on 9/6:

I was finally able to find a time to speak with Rebecca and a few others from the White House Hotline team. The main focus of the discussion was on the documents that we provided several weeks earlier. We were able to go through them and get feedback from Rebecca and her team. Since then, we've updated the documents and sent back out for review.

We also learned that they are in the process of training agents for the new SLC WHH location. I asked about whether they wanted us to plan a trip out there to conduct training and they said not right now. I also asked if this meant they were going to make any changes to Salesforce or move forward with the migration to MS Dynamics but they said they didn't imagine many changes would be needed to their CRM so the answer for right now is no. 

Because of the work they are focused on to get this new call center site up and running, we haven't been able to get a final okay on the escalation process/crm requirements documents. Our bi-weekly meeting was also cancelled but we hope to have something rescheduled for either 9/25 or 9/26.

**Comment by clantosswett** [comment]
Recap of conversation with National Call Center on 9/4:

I have been able to touch base with the heads of the National Call Center quite a bit (Regina Yount) because of the upcoming roll out of direct deposit. We've had several conversations around training for the new direct deposit feature on VA.gov. Nothing major to report here but the hope is we can get their CRM updated to reflect direct deposit issues that can be directly reported to us and the necessary teams.
