### ISSUE TITLE
[Design] Blue Sky Feedback

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1547]
## User Story
As a Insights team member and stakeholder, I need to understand what the Product Health Tool will look like so I can prioritize the data that will be needed and run through platforms that the tool can live on.

## Goal
Continue iteration of the 'paper draft' of the product health tool.

## Acceptance Criteria
- [x] Insights team look over https://github.com/department-of-veterans-affairs/va.gov-team/issues/1171 and comment with feedback
- [x] Amy: Meet with DSVA to go over thoughts
- [x] Iterate Blue Sky Design based on feedback

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Looks great! Especially like the forms that roll up into the overall parent product, the thumbs up/down for opinionated knowledge, and the target lines.

One potential sentiment analysis from Foresee would be adding a word cloud.

**Comment by jonwehausen** [comment]
Fantastic so far! Really starting to convey ROI. 

_Few more pieces of feedback / ideas:_
- Setting up thresholds for some of these charts so we can be more proactive instead of reactive if metrics start to reach certain peaks/valleys
- I think the milestone portion is a great idea > give a greater level of detail of how certain functionality is influencing outcomes and if that functionality was worth while. 
- Obtaining a metric that gives insight into how many benefits users are adopting over time > for a returning user, we should be able to determine benefits they currently have from their profile, and use that to determine like 'benefits per veteran' and gain insight into new benefits they're trying to obtain.

**Comment by joanneesteban** [comment]
For more "Blue-er Sky," here are some additional notes:

- On the KPI section, adding green/yellow/red light (or something more accessible) to each KPI, indicating if they are on the way to meeting their goals or not
- On the top, some sort of score or indicator of how the product is doing overall (super blue sky, like if we had machine learning or something to quantify problem areas on the product. An example would be a great or something like a credit score, etc. with a threshold explanation). Essentially something that hand holds, motivates, and guides with immediate _insights_ and then go down the page for more drill down
- If the product doesn't reach a threshold on a chart, maybe highlighting the chart in some way or adding a flag to the top of the page. If there's something wrong or should be improved, it should be easy for our users to take action.
- Heatmaps of the pages (showing where is clicked most). Are there part of forms that are more frequented? Perhaps that part is more complicated, etc. and needs a redesign. 

*Essentially, the question we should be asking throughout this whole process and as we move forwards is: does our product health tool enable users to act on the data and improve their products for the veteran experience.* As we continue to iterate through the design, we want to make sure that it easily pushes teams to make product decisions. In other words, we should be providing decisions, not just data.

**Comment by nedierecel** [comment]
This is cross-posted from #1171 - @amycesal A few observations for Blue (and Bluer) Sky: 

1. Users - We occasionally get asked to provide "# of users" on the product. This could be a new metric to add.
2. Forsee - Within the other trendlines, the historical data is on the left, but in this reportlet it is on the right. 
![image](https://user-images.githubusercontent.com/24525739/64283958-7dee8000-cf26-11e9-9bf0-d86eb4258275.png)
3. Bounce Rate - Bounce rate may be less of an indicator of success. I know it's an easy one to measure to see how introductory content is performing, but I don't feel like it's as important as the other metrics listed.

**Comment by amycesal** [comment]
# Blue Sky
![BlueSky_01](https://user-images.githubusercontent.com/1656046/64554620-65ed7680-d301-11e9-9c32-b85b673365d1.png)

----

# Blue-er Sky
![Blue-er_Sky](https://user-images.githubusercontent.com/1656046/64554619-6554e000-d301-11e9-9ba6-4bccbce6fb62.png)

**Comment by leahbannon** [comment]
After reviewing this, I want to build on this comment from Joanne’s notes from our earlier discussion:
> Essentially, the question we should be asking throughout this whole process and as we move forwards is: does our product health tool enable users to act on the data and improve their products for the veteran experience. As we continue to iterate through the design, we want to make sure that it easily pushes teams to make product decisions. In other words, we should be providing decisions, not just data.

To do this effectively, I think we need to first start by providing a high level overview of product health, which is designed to pique interest in potential problem areas — and then empowers further research and investigation. To that end, I outlined a draft list of the areas that I think are more important red flags to product teams. (I think the product health meter is a good example of heading in this direction as well, even though it’s designed for the overview of multiple products).

I’m thinking the results of a user clicking on the top level info listed below could be to display/hide additional trend information over time, scroll down on the page to additional info, link to google analytics, or link to another page we develop that’s designed to provide additional possible data points that we believe are likely to help understand/diagnose a problem, or some combo. (I'm interested in your thoughts on how to do this best.) For broad product health overview, I’m thinking:
- product name, #, description, 
- Funnel conversions chart (likely link to google analytics exit info, or additional information about why a phase of a form has a high exit rate, such as failed submission info at that phase, or?)
- Significant change in average time to completion (not trend over time)
- Significant change in customer satisfaction score (not trend over time)
- Significant change in successful/unsuccessful page interaction ratio (not trend over time)
- Possibly word cloud of ‘what were you looking for today?’ and call centers, but has anyone come up with a better way to convey this yet?
- KPI numbers
- Total users over past year+
- Failed Form Submissions section
- Significant change in VA processing time/benefit receipt
- Significant increase in down time
- Significant change in call center call # or sentiment
 Information that’s more helpful in researching/understanding a top level trend described above
- Heat map
- Items listed above with “significant change in…” displayed as trends over time
- Additional satisfaction score data
- Everything else

Also, I like the basic stats of # of pages, # of questions, # of clicks at the top, but I think it should be smaller since it’s more contextual and doesn’t need to catch the user’s eye.

Other thoughts…
- Is there a good automated way to refresh the screenshots of the forms? Perhaps something related to the visual regression testing we run? If not, it might not make sense to include it.
- I like the idea of having some kind of product timeline that enables marking milestones — what would the UX of this be like?
- Similar question, but for KPIs — I think we discussed we’d work with teams to help them develop/update this. I’m interested in what folks think of this idea now that you’ve run some of the KPI workshops with the teams.
- For the Blue-er sky product health meter, I think it would help to visually separate 👍 and 👎 items.

**Comment by amycesal** [comment]
![Bluest Sky](https://user-images.githubusercontent.com/1656046/65096477-bd878400-d98a-11e9-931a-239333415497.png)

**Comment by amycesal** [comment]
Hey @leahbannon I just wanted to address some of your feedback and provide some further context. 

The newest version (Bluest Sky) hopefully enables leadership to make decisions about teams of specific tools or products by allowing selections of what metrics go into that one score number. For all 8 metrics that go into the score, teams will need to set a target, and the score is measured on how far away from the target they are. 

The rest of the metrics are product specific and hopefully allow people to drill a little bit deeper into different aspects of the product. Having numbers over time allows people to see if this is a new problem, or something that has been going on for a while, as well as having more graphs for further context to hopefully diagnose the issue. 

I'm excited to see how this does in testing and get more insight into what would be most helpful to people. Are there any specific questions you would like me to ask in the interviews?
