### ISSUE TITLE
DebtRes FSR Ch5 Debt Resolution Options HiFI Design 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15502]
As a Veteran who has filled out my financial information and see a calculated field for disposable income I want the ability to chose the resolution path for DMC to consider.

**Comment by rebeccawalsh** [comment]
@leahkeeler I've added my first pass of these designs here. There are a couple of options for the resolution selection screens which will need to be discussed with the DMC - we'll also need to get some feedback from Accessibility since the page is a little special.

Financial resolution options ([option 1](https://app.uxpin.com/edit/8733985#?id_page=134053627), [option 2](https://app.uxpin.com/edit/8733985#?id_page=134053628), [option 3](https://app.uxpin.com/edit/8733985#?id_page=134053629))

[Additional comments / letter](https://app.uxpin.com/edit/8733985#?id_page=134053630)

**Comment by leahkeeler** [comment]
@rebeccawalsh It's asking me to log in :)

**Comment by rebeccawalsh** [comment]
@leahkeeler fixed my links in the original comment :o) sorry!
