### ISSUE TITLE
Issue: VSA dev intent / spot check review request Questionnaire Drupal Page

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#15596]
### For reference

**VSA Development Review** - [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/vsa-accessibility-review-process.md#development-review)

## Team Name

Health care experience

## Product/Feature Name

Questionnaires

## Product description

Our goal is to improve the in-person and online pre- and post-appointment experiences for Veterans, contribute to physical distancing efforts in VA facilities, and better integrate Veteran-provided data in VA workflows by providing Veterans with a digital option to complete pre- or post-appointment questionnaires and screeners.

Our MVP will focus on improving the pre-appointment experience at primary care appointments. We are also creating a tool that will display all questionnaires that need to be completed as well as completed questionnaires.
[MVP: Visit Intro Initiative (Proof of Concept)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/product/initiatives/visit-intro.md)

## Review stage

- [x] **Development intent review** (Review design to discuss approach to take with development, identify what components and semantic HTML would be appropriate, identify any accessibility issues and how to address) - This would happen as designs are passed to development, before development begins.
  - The only portion that I need reviewed is our main content (Drupal) page for our questionnaire feature. This is the main page that Veterans would navigate to for our feature from the va.gov homepage. Jennifer has reviewed all of the other pages already.
   - [Authenticated wireframe version](https://zpl.io/2jDmm3q)
   - [Unauthenticated wireframe version](https://zpl.io/anxG0zQ)

_Just if this helps, our entire wireframe set for the whole feature can be viewed here: https://scene.zeplin.io/project/5f3d86a458ea2231e60a4780_

- [ ] **Spot check review** (Review and follow the steps in the [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md) first.) This happens well before launch, so that the 508 office can review and any issues addressed *before* launch.

- [ ] **Other:** Please indicate what you're requesting

## Point of contact

Kristen McConnell

## Preferred times for dev intent checkpoint

Asynchronous review completed through this ticket.

## Staging URL and credentials

Nothing is built yet, so not applicable.

## Test plan
N/A

**Comment by kristenmcconnell** [comment]
@jenstrickland - Should I also be tagging Josh Kim in these stories as well? Let me know if you have any questions. This page that I'm asking you to review is circled in this site map.

![Site Map.jpg](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/a80b09fb-05cf-4ab2-9232-17258f692380)

**Comment by jenstrickland** [comment]
- "Complete health care questionnaires" is an h1 (stating the obvious, as a way of starting). 😸 

- The intro paragraph uses a utility style, `<p class="va-introtext">VA Intro Text…` — apologies if you know this already. This is something that some developers didn't know about. 

- For the "Please sign in to complete…" alertbox, please make sure that is an `h2` with a utility class of `vads-u-font-size--h3` to style as an `h3`. There is a [documented issue for this (#7708)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7708), and it may not be possible to address prior to launch.

- If you direct users to phone numbers, there is a telephone number component that uses an `aria-label` pattern to adjust the readout for screen reader users. I'm not sure if it is in the CMS, yet.

- When you run your accessibility scans, there will be universal issues with "color contrast" to check for multiple items in the header (these may be disregarded), the telephone number pattern will throw an error (may be disregarded), and in the footer the "Veteran Programs and Services" will come up as an issue (it is already documented and assigned to VSP). There is likely to be another issue about the sidenav needing a unique name, and that is also already documented and assigned to CMS front-end devs (Public Websites, I believe is responsible for this template).

That's it for this page, since it's very straightforward. Thanks so much for the dev intent request. They're usually more complicated. 😉 

![Screen Shot 2020-10-30 at 3 36 27 PM](https://user-images.githubusercontent.com/57469/97750573-6c235100-1ac7-11eb-8dee-38c9d9f80b97.png)

**Comment by kristenmcconnell** [comment]
@jenstrickland Thank you. The comments has been added to our wireframes.
