### ISSUE TITLE
508-defect-2 [Headings] Resources and support - Multiple FAQ page skips heading level 2

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#15619]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## What happened?
Resources and support - Multiple FAQ page skips heading level 2, on this page http://learningcenter.web.demo.ci.cms.va.gov/node/8487/. This doesn't happen on all the multiple FAQ pages if an author puts an h2 (e.g. http://learningcenter.web.demo.ci.cms.va.gov/node/8249/, which suggests we need to rethink this template to put in guardrails against a11y errors.
<img width="300" alt="Screen Shot 2020-10-29 at 4 55 33 PM" src="https://user-images.githubusercontent.com/55992116/97631638-a9280e80-1a07-11eb-80cb-793dd1eb85ad.png">
<img width="300" alt="Screen Shot 2020-10-29 at 4 54 46 PM" src="https://user-images.githubusercontent.com/55992116/97631655-adecc280-1a07-11eb-95cf-d738a89b3fed.png">

## Specs:
I saw this in IE11 in CAG via my Macbook

## Steps to Reproduce
Visit the URLS above and see the heading level order.

## Desired behavior / AC
Heading levels aren't skipped

**Comment by andaleliz** [comment]
@jenstrickland I added the defect label per your comment in the other ticket - if there are additional updates needed to this ticket, please feel free to tweak/edit as needed. Thanks!

**Comment by jenstrickland** [comment]
I just adjusted the title, so that a PM can identify what the priority is when looking at list of issues. I recommend using the 508 issue ticket template for accessibility issues. It outlines the necessary criteria to provide for issues to be fixed, and the bug template doesn't. Since this is a relatively straightforward issue, I'm not going to copy the contents over to fill them all in.

**Comment by jenniferlee-dsva** [comment]
This might be something we need to address on the FE side. 

Force requiring an H2 on these templates, especially the multiple FAQs articles, created a lot of cases where there were only 3 or 4 questions, and so they didn't need a 'grouping' section header. And forcing the editors to add one caused a lot of duplicative headers where the h2 was just a repeat of the h1 or a variation. It forced bad, redundant filler content. 

@andaleliz @jenstrickland - do you think there is a way to address this in the FE so that if the question texts don't have an H2 section, that we make the question texts flagged as h2s?  Similar to the way we display h3 font for our Related information and other global components that appear at the bottom of various pages, but use a h2 flag in the FE. (Class, element - not sure of verbiage.)

**Comment by jenstrickland** [comment]
Sure. Rather than using a heading for each section, it would be possible to use an H2 for each question, and then if there is a section with a heading and questions beneath it then use the H3 for those. On Healthcare's Questionnaires they are using H2s for each of the questions. 

The alternative would be to create a style where the markup is an H2 with an H3 utility class applied (`<h2 class="vads-u-font-size--h3">An H2 that looks like an H3</h2`). I'm not sure how that would work in the administrative panel, though. Perhaps there is an FAQ Question style that could be created and applied for FAQ pages?

**Comment by brianalloyd** [comment]
resolved, closing in support.
