### ISSUE TITLE
Request access to Google Analytics

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#15643]
# Request Google Analytics access

## What this form is for
Use this template to request access to Google Analytics

## User Email Address
Please grant access for:
Denise Coveyduc - dcoveyduc@governmentcio.com
Megan Gayle - mgayle@governmentcio.com

## Access Requirements
_Please provide access to Google Analytics, Google and Bing Search Console and DOMO for both @denisecoveyduc and @mgleo ._

## Date Required
_Week of November 2 or as soon as possible would be great. We are launching a new team to enhance the search and discovery experiences on va.gov and we have begun our own analysis and discovery efforts._

## Product Team / External Team / VA Office
_Denise & Megan are part of the Search and Discovery team working on Unauthenticated Products on the VSA program with John Hashimoto_

*Please leave the following blank*

---

### Definition of Done
- [x] Provide access to user
- [x] Ensure user received email confirmation

**Comment by jonwehausen** [comment]
Thanks @denisecoveyduc! Confirming receipt

@bmcgrady-ep could you work with Denise and Megan to get them added to GA, thanks in advance

**Comment by bmcgrady-ep** [comment]
@denisecoveyduc @mgleo - You should now have access to DOMO and Google Analytics. I don't have access to add users to Google Search Console or Bing Search Console. 

@jonwehausen - Do you know who can grant access to Google Search Console and Bing Search Console?

**Comment by jonwehausen** [comment]
Hi @denisecoveyduc & @mgleo ,

I have added both of the emails provided as users to Google Search Console. You can access that data [here](https://search.google.com/search-console?resource_id=https%3A%2F%2Fwww.va.gov%2F&hl=en).  

In order to get you both added to **Bing Webmaster Tools**, we'll need to get you signed-up first. In order to get you signed-up, you'll need to create an account either with Microsoft or Google. Please find the "sign-up" link [here](https://www.bing.com/toolbox/webmaster/) and the instructions for either Google or Microsoft below. 

![image](https://user-images.githubusercontent.com/48527022/97912318-a7698e00-1d1a-11eb-9468-cce7e221a461.png)


## Google
If you have a @va.gov email, we would recommend associating your va.gov email with a Google account -- you can do that [here](https://accounts.google.com/signup/v2/webcreateaccount?flowName=GlifWebSignIn&flowEntry=SignUp). If you don't have a @va.gov email you can also try this process with your government cio email. 

Please make sure the first page of the sign-up screen looks like this when doing so... should say "Create a new gmail address instead" at the time of having the first page complete and clicking "Next" 

![image](https://user-images.githubusercontent.com/48527022/97912080-4d68c880-1d1a-11eb-91bc-a8e6eab50a4f.png)


## Microsoft
You may be able to use your existing va.gov to sign-up with Microsoft directly, have not tried this method specifically so not 100% familiar with all of the steps. 

![image](https://user-images.githubusercontent.com/48527022/97912436-d1bb4b80-1d1a-11eb-8220-70f48a04ff78.png)


## Last Steps
@bmcgrady-ep - Once signed-up we just then need to provision access under "User Management" [here](https://www.bing.com/webmasters/usermgmt?siteUrl=https://www.va.gov/) as a "Read-Write" user.

**Comment by bmcgrady-ep** [comment]
@denisecoveyduc @mgleo - Were you able to get your Bing Webmaster Tools accounts created? If so, we can get you added to the va.gov Bing Webmaster Tools account.

**Comment by denisecoveyduc** [comment]
@bmcgrady-ep  Yes, I have created a Bing Webmaster Tool. What's next?

**Comment by bmcgrady-ep** [comment]
@jonwehausen - can you add @denisecoveyduc and @mgleo to Bing Webmaster Tools? I currently don't have admin access in Bing Webmaster Tools. Thanks!

**Comment by denisecoveyduc** [comment]
@jonwehausen - As discussed please implement the same request for our new FE Engineer, Sam Suddath @srsuddath  Thanks to you and @bmcgrady-ep

**Comment by jonwehausen** [comment]
Hi @denisecoveyduc, 

No problem! @srsuddath should have received an email to his ssuddath@governmentcio.com account with his GA access. 

Can also confirm both of your emails dcoveyduc@governmentcio.com & mgayle@governmentcio.com have been added to Bing Webmaster Tools. We can get @srsuddath added to Bing Webmaster Tools if needed as well, he will want to go thru the same steps you did outlined [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15643#issuecomment-720690780). 

If nothing else needed access-wise, we can close this guy out 😄

**Comment by denisecoveyduc** [comment]
@bmcgrady-ep  I believe my email has been added for Bing. Are you able to provision as @jonwehausen outlined?

@mgleo  Were you able to add your email to Bing Webmaster Tools (see above)
@srsuddath Can you please also add your email to the Bing Webmaster tools using the link Jon provided above?

Thanks all! We are almost there ;)

**Comment by mgleo** [comment]
Yes, I was able to add my email to Bing Webmaster Tools.

**Comment by jonwehausen** [comment]
@denisecoveyduc wanted to verify with you your account has been added (see screenshot below). Please let us know if you have any access-related issues, you should be able to access Bing Webmaster Tools [here](https://www.bing.com/webmasters/home?siteUrl=https://www.va.gov/)
![image](https://user-images.githubusercontent.com/48527022/99441219-95c0e280-28e5-11eb-8e81-70f0ba2875c0.png)

We'll get this closed out once @srsuddath has performed the sign-up instructions. 

Thanks again here!

**Comment by srsuddath** [comment]
@jonwehausen I believe I have completed the steps above: ssuddath@governmentcio.com

**Comment by jonwehausen** [comment]
Thanks @srsuddath, you should have now received an invite indicating your access. Thanks again!
