### ISSUE TITLE
DebtRes FSR Ch8 Review Page Hifi Design

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15656]
As a Veteran filling out the FSR form, I want the ability to review the information on the form I just filled out before submitting to DMC

**Comment by rebeccawalsh** [comment]
I have created a scaffold of the intended review page (including signatures) here: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134117869/simulate/no-panels?mode=i 

It makes sense for us to hold off on building out all of the individual review screen accordions until we've had a chance to really solidify copy and get reviews from DMC and VSP. This way, when we get feedback, we'll only need to change things once instead of having to fiddle with the review screen too.

In the meantime, we have a representative page to include in demos.
