### ISSUE TITLE
DebtRes FSR Ch7 eSignatures Hfi Designs 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#15655]
As a Veteran who has finished filling out FSR form I want the ability to esign the form

**Comment by rebeccawalsh** [comment]
Ho-kay! So we found that on the 1010cg, they are asking for signatures on the Review step of the form! Here's a screenshot of their solution:
![screen_shot_2020-11-11_at_2.43.33_pm.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/21ae22a0-a482-4a24-9cbc-85222c8d7c57)

I think this will be a good solution for us because:
- Consistency with existing form(s)
- Reduce the number of chapters, making the form's progress bar less daunting for Veterans
- The Veteran will have access to all of their previous submissions in order to certify it's truthful
- Our implementation will be even simpler than this, since we have only one required signature

I've included a scaffold of the review page with the signature included here: https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/134117869/simulate/no-panels?mode=i
