### ISSUE TITLE
[SPIKE] CC provider data available

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#15651]
## Summary
Users currently copy+paste provider data into preferred community care provider form. We would like to understand the facility data available in order to populate a list of options.

---

## Questions to Answer
- [ ] What Community Care provider data is available? (defaults, full list of options)

- Name?
- Address?
- Languages spoken?
- Specialty types?

- [ ] What information is required in our request to retrieve provider data?

- [ ] How many results are returned?

- [ ] How are the results sorted? Distance, alphabetical?

---

## Acceptance Criteria
- [ ] Questions are answered and documented

- [ ] Document which api/endpoints we can work with, and recommendations

- [ ] Rough visualization of the data on the page

---

## Time Box
2 days

**Comment by jbalboni** [comment]
WIP notes:

Data in current facilities endpoint:

- Name
- Address
- Caresite phone (maybe this is the location phone)
   - There's a regular phone attribute, too
- uniqueId (NPI, I think)
- Accepting new patients

Interface

- specialities (service types)
- bbox
   - This is translated to a lat long and radius, which is what we'd prefer to send in the first place. However, we can convert our
      lat/long and distance range to a bounding box if we need to
- pagination

**Comment by jbalboni** [comment]
I think my biggest conclusion here is that we'll need to modify the existing endpoint for pulling CC providers in vets-api to support our needs (passing a lat/long and radius, and potentially searching by multiple specialty codes), assuming we go the route of using the existing va.gov connection. We could also create our own interface in vets-api that uses the existing PPMS connection code, potentially.

**Comment by jbalboni** [comment]
FYI @saneshark @laurenernest @outerpress, questions answered above.

**Comment by saneshark** [comment]
1. Lat/Long is more performance than address based lookup. I agree that we'd want to use Lat/Long ideally. 
2. Radius is an interesting one we might have to play around with from a UI perspective. The current mechanism on Facilities API whereby it auto zooms out indefinitely is a little bit jarring. That being said, for some remote areas we'd want a larger radius than more metropolitan areas.

The biggest hurdle to overcome is still going to be the specialty codes. We have 6 CC Types, of those 6 CC types we need a mapping to the most pertinent (4 out of X) specialty codes since we're limited to 4 in our query. This will however mean that for a given Lat/Long + Radius, our results will be limited to only those 4 specialty codes queried. We could possibly munge multiple queries together but thats going to make things even more complicated -- particularly with expanding and contracting radii based on location.

**Comment by saneshark** [comment]
@jbalboni suppose we go with only doing a single query for the 4 most relevant specialty code mappings, not munging any data together to build a full set -- would we be able to track at a granular level in google analytics successful hits and users progress in such a way that we could use this analytics to later tune what we are doing in our query? In other words, start with something, but tune it over time, iterating based on analytics we collect.

**Comment by jbalboni** [comment]
I made some updates above. I don't think the `address` param on vets-api is important (it's not required), `bbox` is important, since that is a lat/long box that is turned into a lat/long point and radius.

I don't think we can expand/contract radius depending on location; I don't know what data you'd base that expansion/contraction on. You could do additional queries if you didn't get a certain number of results, I guess.

That analytics question is more of a @laurenernest or @lenaecb question, technically we can provide whatever event data is necessary there.

**Comment by lenaecb** [comment]
@saneshark - I think we can make the analytics happen if we have a clear question or outcome we're trying to track. So i don't see that being a hurdle.

**Comment by jbalboni** [comment]
@laurenernest I think this is complete, but I'll leave it to you to close it or update it with any more questions you have.

**Comment by laurenernest** [comment]
- [x] Questions are answered and documented

- [x] Document which api/endpoints we can work with, and recommendations
- Facilities API

[-] Rough visualization of the data on the page _(Waived. FE work has started)_
