### ISSUE TITLE
Auto-expand accordion items if the URL hash matches the item ID 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#15798]
## Issue Description
_Auto-expand accordion items if the URL hash matches the item ID_

Slack Discussion [Here](https://dsva.slack.com/archives/C52CL1PKQ/p1604441562376800)

## Front end tasks
- Estimate task and remove needs grooming label
- Build and Implement auto-expand accordion item as described and validated in Slack convo

## Acceptance Criteria
- [ ] Designer comments on this issue to approve page styling 
- [ ] Unit tests pass
- [ ] E2E tests cover current code and regression
- [ ] End-to-end tests show 0 violations.
- [ ] The data returned matches API response (for given user or scenario)
- [ ] All axe checks pass
- [ ] All color contrast checks pass
- [ ] All zoom testing passes
- [ ] All keyboard checks pass 
- [ ] All screenreader checks pass

**Comment by ncksllvn** [comment]
For visibility, this was a design system change because the "accordion" component's style lives in that repo. So, I had to add this functionality there, get the VSP design system team to review (took a couple days) and now I have to update the website's design system version to receive the updates on the website. I'm waiting for a review on that now.

**Comment by ncksllvn** [comment]
Actually managed to finally get that review, so this work should go live today

**Comment by brianalloyd** [comment]
Thanks @ncksllvn I'll close this out once it goes live during today's deploy.

**Comment by brianalloyd** [comment]
Awesome Job @ncksllvn super cool functionality.  Closing per validation.
