### ISSUE TITLE
IA Request [Facilities Team - Vet Center Pages]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#15819]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After completion of usability/protyping, prior to moving to development

## Required Inputs:
- [Link to product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/vet-centers/product-brief.md)
- Link to or attach prototype or mockups
- Link to [research folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers/discovery
- [Facility IA map](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** - Provide link or image of proposed page structure (if more than one page)

**Suggested URL(s)** - Provide suggested URLs and any background or rationale

**Suggested entry points** - What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [ ] Issue is created, tagged and assigned to VSP Product Support
- [ ] Required information above is complete and optional information provided where available
- [ ] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation

**Comment by mmiddaugh** [comment]
We're requesting a meeting to review the Vet Center prototype and begin the IA discussion. Please include: 
Facilities Team
- Dave Conlon
- Michelle Middaugh
- Leyda Hughes
CMS
- Clarence Maeng (clarence.maeng@agile6.com)
- Natalie Dunbar (natalie.dunbar@agile6.com)
- Kevin Walsh (kevin.walsh@civicactions.com)
- Steve Wirt (steve.wirt@civicactions.com)

**Comment by shiragoodman** [comment]
Hi @mmiddaugh  - Can you look over our [VSP Collaboration Meetings Calendar](https://calendar.google.com/calendar/u/0/embed?src=adhocteam.us_4dn3o77gcm5e3vbiedlha96tc0@group.calendar.google.com&ctz=America/New_York) and find a timeslot that works for you? We don't typically hold meetings for IA Requests, however please allow 2 full days for review (ie, we can't accommodate the Friday timeslot). Thanks!

**Comment by lildziner** [comment]
@mmiddaugh Here is a link to the [prototype in UXPin]. This is still rough.  (https://preview.uxpin.com/603da0b67ccefbbee74fcd8bb77a8fed12baabb5#/pages/133912052/simulate/no-panels?mode=i).

**Comment by mnorthuis** [comment]
@mmiddaugh @lildziner Based on our discussion this morning, here is draft IA based on the recent prototyping. Once user testing is complete, we can review this information and the findings and adjust as needed. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/facilities-vet-centers.md

Please note:
- The breadcrumb variation must be tested in user research in order to be approved by VSP since it is a variation of the standard component.
- Recommend testing that users are able to also get back to the Vet Center page from the child location page to ensure that navigation options/paths are clear in the absence of the left nav. 
- We will need to finalize requirements around the URL of the Vet Center pages - if they are driven from data in VAST, we will need to enforce rules for proper formatting and govern how/if the URL can be changed/altered.

**Comment by mmiddaugh** [comment]
Additional considerations raised this morning for Community access points:
Are naming conventions established?
How to avoid creating 404 errors when these are sunset ("no index"?)
