### ISSUE TITLE
[Research] Create Grey Sky Product Health Research Plan

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1584]
## User Story
As a Insights team member, I need to understand the research plan moving forward for the "grey sky" product health tool that will go into production so I can understand what the stakeholder goals are for the tool.

## Goal
Create a robust research plan for the "grey sky" product health tool.

## Acceptance Criteria
- [x] Create and document "grey sky" research plan
- [x] Create and document "grey sky" discussion guide

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Resources
_Notes from Amy<>Emily meeting:_
Research template: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Research/research_plan_template.md
We are going to do research on Grey Sky with stakeholders after:
- we figure out goals from stakeholders
- we figure out grey sky with date holders

**Comment by joanneesteban** [comment]
Stakeholder should include product owners/manager as well as DSVA goals.

**Comment by amycesal** [comment]
# Research Plan for Insights and Analytics, Grey Sky prototype, September 2019

## Goals
1. What product & team are you doing this research for?
To learn what leadership and product owners want out of an analytics tool and how they will use findings from it

2. Background: The goal of the dashboard is to surface analytics with actionable items so leadership and product owners have information in order to make product decisions. 

3. Research questions: 
- What sort of metrics would lead people to make product decisions? 
- What will you do after viewing this dashboard?
- What information is missing or is there any extra information that's not needed?

4. Hypothesis: Some users will find one score helpful to compare different products, while other users will want to dig more into the data get a wholistic view. 

## Method
1.	What method of research are you planning? 
  - Directed interviews with low-fidelity prototypes, remote moderated

2.	Why this method? Leverages the current work and validates if we are moving in the right direction with the product. 

3.	Where are you planning to do your research? online using zoom or slack video with screensharing

4.	What will you be testing? Design mocks with fake data 

5.  If remote: What tool do you plan to use: Zoom or Slack Video

## Participants and Recruitment
1.	Participant criteria: What are you looking for in a participant?
Users/stakeholders:
DSVA: Leah, Chris, Patrick
Leadership: Rachael, Andrew G, Emily

Product: Andrea Schneider, Matt, Kevin, Kara, Justin, Yana, Dorothy, Mark G

2.	What is your recruitment strategy? 
Recruiting existing product owners and leadership who we intend to use this product. 

## When? 
1.	Timeline: What dates do you plan to do research? 
Next sprint

2.	Prepare: When will the thing you are testing be ready? Currently working to create the grey sky prototype after conversations with data stakeholders to make a realistic version of the blue sky prototype. 

3. Length of Sessions: How long do you estimate each session will be? about 30 minutes

4.	Availability: If applicable, when would you like sessions scheduled?  flexible with people's schedule's within the sprint. 


## Team Roles
Please list the people who will be serving in each role. **Include the primary phone number for moderator and the emails for moderator, notetaker, and observers. If you need Perigean to take notes for you, indicate that next to Notetaker** 
- Moderator:
- Research guide writing and task development (usually but not always same as moderator):
- Participant recruiting & screening:
- Project point of contact:
- Participant(s) for pilot test:
- Note-takers:
- Observers:

**List email addresses for those who should attend and observe the sessions: VA Stakeholders, engineering team members, design team members, any other people who might find this research relevant to their work**

## Resources
- Project Brief: 
*Project brief should live in the appropriate vetsdotgov-team product folder, simply paste a link to it here*

- Discussion Guide
*Discussion guide should live in the appropriate vetsdotgov-team product folder, simply paste a link to it here*

- Notes & Recordings
*Session notes and recordings should live in the appropriate vetsdotgov-team product folder, simply place links to them here.*

- Synthesis
*Link to any documents used for synthesis (Mural or Realtimeboard boards, excel sheets, other data outputs, etc.)* 

- Lessons Learned
*Did you have any takeaways from the process of this research round that you want the team to remember for the future? Document them here.* 

- Read-Out/Results
  - *Read-out presentation should live in the appropriate product repo and folder; paste a link to it here.* 
  - ** Don't forget to add a link to your research folder to the research tracker! [https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Research/Research%20History.md](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Practice%20Areas/Research/Research%20History.md)

**Comment by amycesal** [comment]
# Conversation Guide

## Moderator logistics

*Use [#feedback-backchannel](https://dsva.slack.com/messages/C40B45NJK/details/) in Slack for real-time feedback from observers.*

*Before the session, send out the [observer instructions](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Work%20Practices/Research/Research%20Process%20and%20Templates/observer-instructions.md) to your observers (Slackbot will do this for you if you type "observer instructions" into #feedback-backchannel).*

*When the participant is ready, begin the session with the following intro*

## Intro - 5 minutes

Thanks for joining us today! My name is Amy and I have some colleagues on the line observing and taking notes. Today we're going to talk about a prototype for the Product Health Analytics dashboard. 

Before we start, a few things I want to mention:

- **This entire session should take about 45 minutes.** I want to be sure not to keep you much longer, so I may occasionally prompt you with the next question or topic.
- **In this session, we want to hear your honest opinions.** We are not testing your ability. We just want to improve these tools to better meet the needs of product owners. I will not be offended by any opinions you express, and I welcome your feedback.
- **If for any reason and at any time you want to stop the session, please let me know.** 
- **Are you comfortable if I record your screen and audio as we talk today?** We use the recordings to confirm that we have captured your opinions accurately.

*Start screen recording using Zoom.*

## Warm Up Questions - 5-10 minutes
* Before we start, I want to take a few minutes to ask you some questions.
* Can you tell me a little bit about what your role is? (Role at DSVA, what product do they focus on)

#### General product health questions
- What decisions would analytics data help you make?
- Once you had the data, what sort of action would you take?
- How specific are you expecting the data to be? Per product? Per form? Per page? And why is that level of detail useful?
- How often would you ideally look at analytics data? Monthly? Weekly? Daily?
- What metric is most important to you for determining the health of a product?

## First task: React to Product Health Analytics dashboard

Okay, I am going to show you the Product Health Analytics dashboard.

* Take a moment to scan this page, and tell me what you're looking at here.
    * What is the purpose of this page?
    * What do you think you can do here?
* What steps would you take next?


## Second task: Interpret product health
* Are there any metrics that are unclear?
* Are there any metrics that you don't need? 
* Are there any metrics that are missing?


## Thank-You and Closing - 5 minutes
Well we really appreciate you taking the time to share your thoughts with us today. Your feedback is so helpful to us as we continue to work on the dashboard and make sure it really works for users.

**Comment by joanneesteban** [comment]
Completed first drafts of the research plan and conversation guide. Closing this issue.
