### ISSUE TITLE
[Bug] 526: Upon Form Submission, Submission Date is "Unknown"

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#15852]
## Issue Description
Actual submission date needs to show up and not just "unknown".

1. Make sure we are using the UTC date.
2. We likely never need to get this from the backend.

## Acceptance Criteria
- [ ] No more "unknown".

**Comment by Mottie** [comment]
Looking in the `ConfirmationPoll` component, it looks like we're passing the `submittedAt` value from `form.submission` when we should be passing `timestamp`.

**Comment by ndsprinkle** [comment]
"Unknown" is what our `formatDate` function defaults to if the passed in date is `null` OR if `moment.isValid()` is false, so that explains why we get that text. I guess this means Robin is right in saying that we shouldn't be using `submittedAt`, though it is confusing because all other forms use `submittedAt` with no issues. Looking at the back end, it looks like `submittedAt` is just an alias for the `createdAt` attribute, so it should be working. I'm fine to just use the current time since it is nearly identical to the submitted at time, but I'd like to figure out why `submittedAt` isn't working. @Mottie You suggested that we shouldn't be using `submittedAt` at all, what did you see that made you think that? Because I may be missing something

**Comment by Mottie** [comment]
Sorry, that's what I was thinking would work after my quick glance at the code. I don't know what service other forms are using, but I think we might be unique in using EVSS. So maybe that's why `submittedAt` doesn't work?

Either way, it sounds like you did a lot more digging than I did, so I would go with whatever you think is the best route.

**Comment by ndsprinkle** [comment]
You know what, I spoke too soon! Looking at the redux state in staging, `timestamp` is what we need to be checking. You were right, I'll make the change :)

**Comment by Mottie** [comment]
<img alt="ghe-emoji" title=":_tuzki_yipee:" src="https://cloud.githubusercontent.com/assets/136959/13203739/b390cc24-d883-11e5-9f1d-52d7b8ec9a61.gif">

**Comment by ndsprinkle** [comment]
@luke-gcio I merged this yesterday afternoon, so it should be deployed and available in staging soon. To test, all you need to do is successfully submit a 526/BDD form and the timestamp will show on the confirmation page that follows.
