### ISSUE TITLE
Why might I have this debt - Content

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#16113]
![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/86418aae-40ff-47ce-8381-76e57e8bccf4)

Create content to explain why a veteran has debt that is displayed in the cards

**Comment by 3obryandogs** [comment]
If this is suitable with Becca and Riley, I will send it to Peggy/Danielle for their OK.

Why might I have this debt?
A letter was sent to the address on file with details about VA overpayment for specific benefits. 
Compensation and pension
Some reasons you might owe disability compensation or pension repayment to VA include:
•	A change in eligibility
•	A duplicate payment
If you want more information about repayment options, please call the DMC at 800-827-0648.
 If you want more information about why you owe this repayment, please call 800-827-1000 for disability compensation or 877-294-6380 for pension.
Education
Some reasons you might owe education repayment to VA include:
•	A change in course enrollment
•	A withdrawal from college, university or higher education program
•	A change in eligibility
•	A duplicate payment
Note: For Post-9/11 GI Bill benefits, three separate payments are made by the VA for tuition, housing, and books and supplies. When there is a change in this benefit’s use, VA will collect the three debts separately.
If you want more information about repayment options, please call the DMC at 800-827-0648.
If you want more information about why you owe this repayment, please call the Education office at 888-442-4551.

**Comment by 3obryandogs** [comment]
After the conversation with DMC ladies:

Why might I have this debt?
A letter was sent to the address on file with details about VA overpayment for specific benefits. 
Compensation and pension
Some reasons you might owe disability compensation or pension repayment to VA include:
•	Military pay and disability compensation at the same time
•	Change in active duty status
•	Change in eligibility
•	Change in your marital status 
•	Change in your dependents
•	Duplicate payment by VA
•	Unreported income
•	Unreported incarceration
If you want more information about repayment options, please call the DMC at 800-827-0648.
 If you want more information about why you owe this repayment, please call 800-827-1000 for disability compensation or 877-294-6380 for pension.
Education
Some reasons you might owe education repayment to VA include:
•	Academic probation or suspension
•	Change in active duty status
•	Change in your enrollment (drop a class)
o	Note: Change in course enrollment can cause overpayment in tuition, housing, and book and supplies.
•	Change in your eligibility
•	Change in your housing 
•	Duplicate payment by VA
•	Your withdrawal from college, university, or higher education program
Note: For Post-9/11 GI Bill benefits, three separate payments are made by the VA for tuition, housing, and books and supplies. When there is a change in this benefit’s use, VA will collect the three debts separately.
If you want more information about repayment options, please call the DMC at 800-827-0648.
If you want more information about why you owe this repayment, please call the Education office at 888-442-4551.

**Comment by rileyorr** [comment]
Thanks for providing the updated content! I added some suggestions in areas I think could be more concise for our users. Let me know what you think!

> A letter was sent to the address on file with details about VA overpayment for specific benefits.

A letter was sent to your mailing address explaining overpayment for your benefit. 


**Compensation and pension**

> Some reasons you might owe disability compensation or pension repayment to VA include:

Reasons you owe disability compensation and pension repayment might include:


> • Military pay and disability compensation at the same time

You received disability compensation and drill pay at the same time 


> • Change in active duty status

What change in active duty status would result in a VA repayment? 


> • Change in eligibility

I don't fully understand this one - what change in eligibility would result in a VA repayment?  


> • Change in your marital status
 
You didn't notify us when your marital status changed


> • Change in your dependents

You didn't notify us when your dependents changed


> • Duplicate payment by VA

We sent duplicate compensation and pension payments


> • Unreported income

Where are Veterans reporting their income that would result in a VA repayment? 


> • Unreported incarceration

You didn't notify us when you were incarcerated


**Education**

> Some reasons you might owe education repayment to VA include:

Reasons you owe education benefits repayment might include:


> • Academic probation or suspension

You were suspended or put on academic probation

> • Change in active duty status

Same question as in the comp & pen list. We should try to be specific so our users aren't confused

> • Change in your enrollment (drop a class)

You changed your course enrollment or dropped a class

> o Note: Change in course enrollment can cause overpayment in tuition, housing, and book and supplies.

Is a change in course enrollment the only way a Veteran could receive overpayment in tuition, housing, and books/supplies? 

> • Change in your eligibility

Same question as in the comp & pen list 

> • Change in your housing

Do you have more information about this? What specifically about the change in housing causes the repayment?

> • Duplicate payment by VA

We sent duplicate education benefit payments

> • Your withdrawal from college, university, or higher education program

You withdrew from college, university, or a higher education program

> Note: For Post-9/11 GI Bill benefits, three separate payments are made by the VA for tuition, housing, and books and supplies. When there is a change in this benefit’s use, VA will collect the three debts separately.

This seems similar to the change in course enrollment resulting in three repayment types - maybe we could combine that info somehow? I also think it might be helpful to highlight this info higher up in the list since it's important and our users may not read down this far.

**Comment by 3obryandogs** [comment]
Those sound good. The word is definitely more personal if it can be consistent throughout the bullets. I'm still trying to get the "voice" right.  
A few that you had questions about:
• Change in your housing
**No, I don't. The DMC could elaborate. I got the idea it related to on-base housing.** Do you have more information about this? What specifically about the change in housing causes the repayment?

o Note: Change in course enrollment can cause overpayment in tuition, housing, and book and supplies.
**We should double-check with DMC team.** 
Is a change in course enrollment the only way a Veteran could receive overpayment in tuition, housing, and books/supplies?\

• Change in active duty status
**DMC team picked this terminology. There was discussion among them about this. According to them, drill pay didn't seem to cover all the options**
Same question as in the comp & pen list. We should try to be specific so our users aren't confused

• Unreported income
**The example DMC team used was what if Veteran won the lottery, got a $$ gift for Christmas, or inherited money.**
Where are Veterans reporting their income that would result in a VA repayment?\

• Change in eligibility
**DMC team wanted it put under comp/pen and education. We can double-check with them.**
I don't fully understand this one - what change in eligibility would result in a VA repayment?

**Comment by rileyorr** [comment]
Thanks for that info, @3obryandogs! We should add the outstanding questions to next week's content meeting with the DMC SMEs and consolidate the content changes we've made so it's easier for us to read. What do you think about sending this updated content and our questions over earlier for feedback? 

Also, how do you feel about keeping in-progress content in a Google Doc so we can collaborate and comment easier than in these Zenhub tickets? We can post in the ticket whenever there's been a content update or comment/question added about a piece of content.

**Comment by 3obryandogs** [comment]
I’m for that. Tickets get confusing when we’ve had a lot of back and forth. I’m in for whatever is easier for you and Becca.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leahkeeler** [comment]
Here is the feedback from DMC 
[https://app.zenhub.com/files/133843125/5b7e2390-01a4-433f-bf9e-97c92dab0a4c/download](https://app.zenhub.com/files/133843125/5b7e2390-01a4-433f-bf9e-97c92dab0a4c/download)

**Comment by rileyorr** [comment]
Bringing over my response from our Slack thread so we don't lose it: 
I think this rewrite is going to confuse our users. For example: Veterans don’t receive overpayments because they’re incarcerated, but rather they receive overpayments for unreported incarceration. And the bullet point above it, ‘Additional income’. What does that mean?

Also, I don’t think this is written in plain language and/or following VA.gov’s style guide. From what I can tell, we usually write complete sentences in our bullet points. An example of this can be found on the [“How to file a VA disability claim” content page](https://staging.va.gov/disability/how-to-file-claim/).

I think this updated content should be reviewed by Peggy to make sure we’re following best practices.

**Comment by 3obryandogs** [comment]
Below is what I emailed to Jill. I don't think Jill was trying to rewrite the content, but rather was just addressing the questions that were bolded. 
 
Compensation and pension
Reasons you owe disability compensation and pension repayment might include:
•	You received disability compensation and drill pay at the same time **– what other pay might they receive besides drill pay?**
•	Change in active duty status **- What change in active duty status would result in a VA repayment?**
•	Change in eligibility **- what change in eligibility would result in a VA repayment?**
•	You didn't notify us when your marital status changed
•	You didn't notify us when your dependents changed
•	We sent duplicate compensation and pension payments
•	You didn’t notify us of additional income
•	You didn't notify us when you were incarcerated
Education
Reasons you owe education benefits repayment might include:
•	You were suspended or put on academic probation
•	Change in active duty status **- What change in active duty status would result in a VA repayment? Same question as in the comp & pen list. We should try to be specific so our users aren't confused**
•	You changed your course enrollment or dropped a class
o	Note: Change in course enrollment can cause overpayment in tuition, housing, and book and supplies. Is a change in course enrollment the only way a Veteran could receive overpayment in tuition, housing, and books/supplies?
•	Change in your housing **- Do you have more information about this? What specifically about the change in housing causes the repayment?**
•	Change in eligibility **- what change in eligibility would result in a VA repayment?**
•	We sent duplicate education benefit payments
•	You withdrew from college, university, or a higher education program
o	Note: For Post-9/11 GI Bill benefits, three separate payments are made by the VA for tuition, housing, and books and supplies. When there is a change in this benefit’s use, VA will collect the three debts separately.

**Comment by rileyorr** [comment]
It doesn't look like the questions in bold were addressed; it looks like the same content as in the original version you posted in this ticket. Maybe I'm missing something!

**Comment by 3obryandogs** [comment]
@Riley Orr<mailto:riley@amida.com> I’m also confused since what they sent back doesn’t match what we sent them. What I took from their response was that they didn’t feel it was necessary to explain “eligibility” and such.
@Leah Keeler<mailto:lkeeler@governmentcio.com> What’s the next step? Will you reach out to Jill?

**Comment by rileyorr** [comment]
@3obryandogs no worries! Since we have the first pass of this content written, do you mind if I close this ticket and create a new one outlining what needs to be done so we can finalize this content?

**Comment by 3obryandogs** [comment]
@Riley Orr<mailto:riley@amida.com> Sure!

**Comment by rileyorr** [comment]
Sounds good! I added the content you provided yesterday to [this Google Doc](https://docs.google.com/document/d/17cfVffip0guLS_Y_Nf8bLar6ZI--zc66CoXngWKLSiY/edit?usp=sharing). I'm gonna close this ticket and make a new one :)
