### ISSUE TITLE
[Frontend] Profile 2.0 bug fix: Add 2FA prompt for when someone is LOA3 but not 2FA and is eligible for direct deposit

### ISSUE THREAD

**Issue by sanlouise** [department-of-veterans-affairs/va.gov-team#16218]
## Background

In profile 1.0, if a direct deposit-eligible user was LOA3 but did not have 2FA set up (a rare use case that can happen if people sign on through DS Logon or MHV), we showed the direct deposit section of the profile, but we showed a prompt that told them they had to add 2FA before they could update their information.

Unfortunately, this state somehow got missed in the profile 2.0 transition, so we need to add it back.

Here is a screenshot of how this should work in the new profile:

![DD 2FA.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/54f75199-8689-4af5-abe1-19808432375f)

## Tasks

- [ ] Add in 2FA prompt for LOA3 users who are direct deposit eligible but don't have 2FA set up.

**Comment by tressaellen** [comment]
Hello - here is the content/mock for this.

Content:

**You'll need to set up 2-factor authentication before you can edit your direct deposit information.**

We require this to help protect your bank account information and prevent fraud.

Authentication gives you an extra layer of security by letting you into your account only after you've signed in with a password and a 6-digit code sent directly to your mobile or home phone.  This helps to make sure that no one but you can access your account - even if they get your password.

[Set up 2-factor authentication]


![DD 2FA.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/8bfa1f01-c420-49c1-86e2-2c6ceb8623e9)

**Comment by erikphansen** [comment]
This is great. I'm wondering if the messaging should be massaged at all. This makes is sound like "once you set up 2FA you'll have access to direct deposit!" But in reality it's more like "once you set up 2FA we can see if we need to show you the direct deposit feature." On the one had this'll motivate people to set up 2FA is they don't have it set up. On the other hand, it's a bit like false advertising. But in the short term I think we should plow ahead with this as soon as we can.

There are two ways I can envision adjusting our API so we know if someone is eligible to see the Direct Deposit section:

1. Adjust the response from our `GET user` call to add a flag that indicates if they are eligible for Direct Deposit. That's probably not going to happen.
2. Adjust the existing `GET ppiu/payment_information` endpoint so that if it's called by a signed in user who _does not_ have 2FA set up, it would respond with something other than a 401 not authorized but does not respond with any bank info associated with the user. There are likely security implications to this.

@lihanli do you have any thoughts about idea 2 above?
