### ISSUE TITLE
Update CMS Preview Server to align with Live site 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1625]
Overtime, the CMS Previews have visually diverged slightly from the live site. The CMS Preview server should be updated so that CMS editors have a more accurate preview prior to publishing.

**Comment by ncksllvn** [comment]
Hm, I'm actually having trouble finding a good example of this. @peggygannon any chance you can provide me a link to a page in preview that serves as example of a page that doesn't match the live site?

**Comment by Karak888** [comment]
- @ncksllvn looked at a few, on preview server and didn't see any visual inconsistencies (outside of those that are intentional) some things are not 1-1 aligned it is a bug CMS will fix after UAT- talk to @jefflbrauer can you help provide us with a screenshot

**Comment by ncksllvn** [comment]
From discussion, I am taking this issue to mean that we just need to enable anchor link-generation in the CMS Preview server. Starting this now...

**Comment by jefflbrauer** [comment]
@ncksllvn to be honest - we probably should hold off on preview work until we have that broader conversation around the build process. If we revamp that process to include single page builds, the preview process should just leverage that.

**Comment by ncksllvn** [comment]
@jefflbrauer agreed. I'm tackling solely the issue with the anchor links not aligning between CMS Preview and the live site...it looks like that we're applying some dynamic integers there that could change as the CMS grows, so we may start seeing (or may already be seeing) some anchor links becoming outdated in Prod. It's just surfacing most clearly in the Preview Server not aligning with Prod.

**Comment by ncksllvn** [comment]
@jenniferlee-dsva The issue you were seeing with the anchors in CMS Preview not aligning with Prod should be fixed after tomorrow's deployment.

Technical breakdown - Currently, if you visit https://staging.va.gov/health-care/how-to-apply/ and want to link to the `What happens after I apply?` heading, you'd have to link to ` https://staging.va.gov/health-care/how-to-apply/#what-happens-after-i-apply-85`. That 85 was applied to make the ID unique, because there are other headings in the website with the same text. The work here changes that to only look in the context of the current page for duplicate heading texts, so that integer isn't necessary anymore.  Tomorrow, the link should only be `http://localhost:3001/health-care/how-to-apply/#what-happens-after-i-apply`.

**Comment by Karak888** [comment]
@ncksllvn @jenniferlee-dsva - just wanted to see if this work had been validated yet?  Thanks

**Comment by ncksllvn** [comment]
All done from a tech standpoint! @jenniferlee-dsva does the issue with the anchor links seem fixed?
