### ISSUE TITLE
Compose a Message | BE

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#16271]
### **User Story**
As a Veteran, I want to compose a new message so that I can communicate a new question or need to my healthcare team.

### **Acceptance Criteria**
- User can create a new message and send it to a recipient
- User can execute the following tasks: 
  - select a recipient(required field)
  - select a subject (required field)
    - Options are General, COVID, Appointment, Medication, Test, and Education
  -  create a custom subject line
  - edit the message field (required field)
- User can choose to send the message or cancel 
  - Cancelling does not save a draft in the MVP launch 

Note: Attachments are handled by another ticket 

### **Tech Notes**
- What are the subject and message body character minimums/limits? 

### **Design**
[Wireframes ](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1613583900890/e6c19090bd775e88e1e13ff0a28aa23f12246bf5)

**Comment by ashley-matthews** [comment]
### **User Story**
As a Veteran, I want to compose a new message so that I can communicate a new question or need to my healthcare team. 

### **Acceptance Criteria** 
- user can create a new message and send it to a recipient
- includes: select a recipient, select a subject, message field, and sending the new message

**### Tech Notes**

### **Design**
