### ISSUE TITLE
Add R&S to sitemap for indexing

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#16287]
## Add R&S to sitemap for indexing

ETA: After Contact Us and IA footer links to the R&S are in production; before December 23 code freeze begins. 

Slack thread: https://dsva.slack.com/archives/C0173CAJ7A6/p1605628482409800

AC:
- [ ] Make https://www.va.gov/resources URL canonical
- [ ] Add canonical URL to sitemap
- [ ] Submit R&S pages to search.gov for indexing

**Comment by johnhashva** [comment]
@denisecoveyduc this is a good -- small -- ticket that would be good for Sam (with any help he needs from Nick) to tackle so he is familiar with the Site Map XML.

**Comment by denisecoveyduc** [comment]
@srsuddath are you able to review and add an estimate? Any clarifying questions needed to integrate this into Sprint 36?

**Comment by ncksllvn** [comment]
Here are the steps to make sure all of R&S is included in the sitemap. Because this launch entailed ordinary Drupal pages, generated pages, and a React app, there are several places we need to remove the "private" flags.

- Remove [this line to include the R&S homepage](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/page.js#L13)
- Remove [this line to include the R&S category/tag listing pages](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/create-resources-and-support-section.js#L200)
- Remove [this whole block to include ordinary R&S pages](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/create-resources-and-support-section.js#L330)
- Remove [this line to include the R&S search app](https://github.com/department-of-veterans-affairs/vets-website/blob/7d543054f907dd85c9cb4c0d093a64d9cd718efb/src/applications/registry.json#L896)

I think that's everything.

**Comment by srsuddath** [comment]
This work has been completed, and the R&S pages can be viewed on the sitemap at https://www.va.gov/sitemap.xml
