### ISSUE TITLE
Resources and Support: Build decision reviews "status label meanings table" in Drupal

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#16351]
For R&S 1.1, we are including a decision reviews article like https://www.va.gov/resources/what-your-claim-status-means/. The attached Word doc has been reviewed by Beth Potts and Randi and is ready to build. 

Preview page: preview-prod.vfs.va.gov/preview?nodeId=9626

##Acceptance Criteria##

- [x] Page built in Drupal
- [x] Node ID shared with SMEs[https://app.zenhub.com/files/133843125/f0075211-7554-471b-8cb3-b03adcc627ae/download](https://app.zenhub.com/files/133843125/f0075211-7554-471b-8cb3-b03adcc627ae/download)

**Comment by RLHecht** [comment]
@lwalsh617 This page is now built in Drupal. I put the preview link above in this ticket.

**Comment by lwalsh617** [comment]
Hey @RLHecht - If we're not making these accordions, should we instead add the "On this page" feature? (I didn't put OTP in the copy deck because I thought we were doing accordions. Am find with OTP instead if the tables can't go in accordions.)

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 @RLHecht 
- The first sentence of the intro is vague re: "it." I'd recommend: 
Your status tells you where your decision review or appeal is in the review process. 

- Can you rewrite the second sentence so it is more directed? This page is much bigger than the claim status one, and covers different types of appeals, so we'll want to direct the user to find the chart that's relevant to the appeal process they're in. The way it is now, it sounds like we're saying, go ahead and browse through all these charts to learn about all our statuses. When really, they only need to look at the one chart that's relevant to them. 

- For the chart labels: First 2 should be "Decision review status" rather than "Claim status" / third is correct / fourth please remove "Legacy" since we're trying to use this internal jargon as little as possible and to the Veteran, it's just an "appeal"

- For all the charts, remove the H2--it's just repetitive.

**Comment by RLHecht** [comment]
@lwalsh617 All of Beth's changes from Slack are now in there.

**Comment by bethpottsVADEPO** [comment]
@RLHecht Can you please bold the text down the left column like you did for the claim status chart? Thanks!

**Comment by RLHecht** [comment]
@bethpottsVADEPO The bolding is now done if you want to send to SMEs.

**Comment by bethpottsVADEPO** [comment]
I'm closing this issue. Thanks for your work on it @RLHecht and @lwalsh617 ! I passed it along to the SME for review.
