### ISSUE TITLE
"yarn fetch-drupal-cache" should always fetch the drupal cache. 

### ISSUE THREAD

**Issue by Clark-W-Griswold** [department-of-veterans-affairs/va.gov-team#16401]
We have seen instances when running `yarn fetch-drupal-cache` where the build will still attempt to pull the drupal data behind the socks proxy. Some background information can be found [here](https://dsva.slack.com/archives/CBU0KDSB1/p1605648714209800).

Definition of done:
When running `yarn fetch-drupal-cache` we always respect the flag to pull the drupal data from cache.

**Comment by U-DON** [comment]
This started to require pulling some Drupal data when the side nav was modified to be built dynamically. The "all pages" query now depends on an extra query for the side navs.

The side navs are interpolated into the final "all pages" query string:
https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/GetAllPages.graphql.js#L137

Before the interpolation, they're compiled after fetching from the CMS API:
https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/navigation-fragments/facilitySidebar.nav.graphql.js#L65

**Comment by U-DON** [comment]
The Drupal cache key is required to [fetch the cache](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/drupal-aws-cache.js#L74) or [create the cache](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/drupal-aws-cache.js#L104).

To generate it, [it hashes the GetAllPages query](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/utilities-drupal.js#L22).

That query [includes the facility sidebar query](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/GetAllPages.graphql.js#L145).

The facility sidebar query needs to [be compiled](https://github.com/department-of-veterans-affairs/content-build/commit/e79eea663861dd0276b2b873c6ded1af66855d1a#diff-cfc370f9a7c4ddbd47af85b2ecb2d579ca26e9d4eaa2192cddb2f6011e3fcd62L65).

In order to compile, it needs to query the side navs, so it [tries to access the CMS](https://github.com/department-of-veterans-affairs/content-build/commit/e79eea663861dd0276b2b873c6ded1af66855d1a#diff-217d4d100c939b569e5590de4f091d8a4d30e6f40c1a9445ae3c987d1ae60324L162).

**Comment by timwright12** [comment]
Closing as this does not seem to be an issue anymore
