### ISSUE TITLE
Ensure un-nesting Veteran Facility name and type does not break API

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#16477]
## User Story
As a Frontend Developer I have completed Schema updates to unnest veteran medical facility name & type from the 10-10CG form. To ensure lower risk we need to check the BE to make sure this schema update does not break the BE. 

## Expected Behavior
@kevinmirc please check vets-api to ensure [this](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/549) schema update does not break the BE.

## Back end tasks
- Ensure [this](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/549) update does not break API

## Acceptance Criteria
- [ ] 10-10CG BE can still accept applications
- [ ] Veteran Facility type & name are not required

**Comment by kevinmirc** [comment]
These schema change do require changes on the API and in the CARMA data-contract.

Specifically:
- The PDF generation relies on the nested fields
- CARMA relies on the nested properties
  - need to have CARMA update their references
  - OR we'll need to transform the data before sending it to CARMA in order to keep the existing data-contract intact

Opening a ticket to "Add support for new treatment facility schema changes" https://github.com/department-of-veterans-affairs/va.gov-team/issues/16883
