### ISSUE TITLE
STEM: SCO Contact / Applicant Alert - Content Updates

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#16595]
Update content doc to support development effort

**Comment by JenLJ** [comment]
SCO Contact/Applicant Alert email is up-to-date.  

Team opted to hold off on implementing alert changes to the 10203 because:
 - Conditional alert is not ideal since we cannot reliably notify each use case
 - Since Luke stated that an email would suffice (and no changes to the 10203), this is the option the team is pursuing
