### ISSUE TITLE
[Post-release] Configure Cypress in `content-build` repo

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#16722]
### User Story

As a VFS engineer developing in the `content-build` repo, I need to be able to set up functional tests on my code, so that I can ensure my code is production ready.

### Acceptance Criteria
- [x] Developers can set up functional tests for their code in the `content-build` repo

**Comment by meganhkelley** [comment]
cc @billfienberg @timwright12 
and cc @JoeTice @pjhill for awareness (this is not something we are working on yet, we will keep you posted when we get to it and discuss split of responsibilities between our teams)

**Comment by timwright12** [comment]
Reminder to confirm we have cypress tests to wire up before spending time on this ticket. As of right now, there are no Cypress tests in the content-build repo.

**Comment by theodur** [comment]
PR for configuring Cypress in `content-build` repo: https://github.com/department-of-veterans-affairs/content-build/pull/82

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/content-build/pull/82) for configuring Cypress in the `content-build` repo has been merged. Only 1 test was brought over, `src/site/layouts/tests/vamc/system_home.cypress.spec.js`. The other Cypress test in the `src/site/layouts/tests` directory can't be moved over because it tests a widget on the page that is generated from the app code. These two tests are expected to be converted into unit tests based on this conversation: https://dsva.slack.com/archives/C01512KN35G/p1616682290059700?thread_ts=1616682179.059200&cid=C01512KN35G
