### ISSUE TITLE
IA feedback - Staging review - BAM2 - Debt letters iteration 2 

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#16742]
**Feedback framework**

- **Must** for if the feedback must be applied 
- **Should** if the feedback is best practice 
- **Consider** for suggestions/enhancements 

## Description

**MUST**
- The breadcrumb on the Download debt letters page is incorrect. It should be:
Home > Manage your VA debt > Your VA debt > Download Debt letters

![image](https://user-images.githubusercontent.com/20994159/100782880-a8054b00-33d2-11eb-9ebe-7354a2b0acc5.png)

**SHOULD**
- On mobile, the content on the "Download debt letters page" is missing a left margin

![Screenshot 2020-12-01 at 12 52 06 PM](https://user-images.githubusercontent.com/20994159/100784469-da17ac80-33d4-11eb-8b81-25c8d8ea17d4.jpg)

**CONSIDER**
- I noticed that when clicking on the link within the content of the page to "< Return to your list of debts", the page refreshes quite quickly.  However, if you return to the "Your VA debt" page via the breadcrumb, there is a significant difference in load time.  Not sure what is causing that difference. 

## Definition of Done
- [ ] Must feedback is implemented
- [ ] Decisions on Should and Consider feedback and question responses documented in issue
- [ ] Issue is closed by VFS team once above items are complete

**Comment by bradl3yC** [comment]
@mnorthuis Im fixing the first 2 findings - the difference in load times is because of how we are changing routes - one is a SPA transition (meaning we're not reloading the entire page) and the other is a full page reload that requires hitting the API to update the data we have in the browser.  I hope this helps and I should have a PR open in a few minutes to address findings 1 and 2.

**Comment by bradl3yC** [comment]
@mnorthuis this should be ready for validation
