### ISSUE TITLE
IA Request | VSA-Public-Websites | Localization + Content | Translation

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#16825]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After completion of usability/protyping, prior to moving to development

## Required Inputs:
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)) https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11599
https://github.com/department-of-veterans-affairs/digital-experience-products/issues/39
- Link to or attach prototype or mockups: 
- Link to research readout/results https://github.com/department-of-veterans-affairs/va.gov-team/files/3273454/VA.gov-Spanish-benefits-link-user-research-061019.pdf
https://app.mural.co/t/workqueue2001/m/workqueue2001/1558543337827/1368018bebaf98469c253d22fdd4fc82efd7fa57
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** - Provide link or image of proposed page structure (if more than one page)

**Suggested URL(s)** - Provide suggested URLs and any background or rationale
Addition of "es" so we can keep URLs aligned but track easily.

**Suggested entry points** - What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [x] Issue is created, tagged and assigned to VSP Product Support
- [x] Required information above is complete and optional information provided where available
- [x] IA reviews information and provides final feedback/recommendation on ticket
- [ ] Requesting team closes issue upon implementation

**Comment by SKasimow** [comment]
Hi @mnorthuis - once I complete the info needed for this ticket I will assign to you -- but had a qq in the interim.

I was speaking with @DanielleThierryUSDSVA and we wanted to ask you if we could add "es" to the URLs for the spanish language Corona FAQ's and Research Volunteer form? 

https://www.va.gov/coronavirus-veteran-frequently-asked-questions/  
and
https://www.va.gov/coronavirus-research


cc: @youngfreezyVA

**Comment by mnorthuis** [comment]
@SKasimow I am looking into this now and plan to have this complete this week.

**Comment by SKasimow** [comment]
Thanks Mikki!

**Comment by mnorthuis** [comment]
@SKasimow @DanielleThierryUSDSVA 

Here are the general IA recommendations, and full detail is provided in the link.   If you would like to review or go over any of this, feel free to set some time up.  Otherwise you can close this issue once you have the information you need.  

- Show translated title of current page in breadcrumb to reinforce. While this does not provide a full translated experience, it further indicates that the user is on a translated page within an English experience.
- Each page needs to provide a link to the alternative language version - i.e. English links to Spanish and Spanish links to English.
- Tool needs to provide a link back to both the English and Spanish content page? 
- The CTA on the Spanish content page should include a note that tool is only available in English.
- Show the spanish version of the content page within the left nav.  Although it may appear to be redundant, it will provide an additional way to find the page and reinforce where the user is within the experience.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/cto-spanish-content.md

**Comment by SKasimow** [comment]
Closing as completed.
