### ISSUE TITLE
Add button in jenkins to deploy latest build to staging. 

### ISSUE THREAD

**Issue by Clark-W-Griswold** [department-of-veterans-affairs/va.gov-team#16939]
Currently, there is logic that prevents vets-website changes from being deployed to staging when another build is in progress. This can lead to instances where a staging deploy might now occur for 3 hours or more despite commits to master during that span.

https://dsva.slack.com/archives/CBU0KDSB1/p1606845204326200

**Comment by timwright12** [comment]
Is this the button? http://jenkins.vfs.va.gov/job/deploys/job/vets-website-vagovstaging/build?delay=0sec

Reference: https://dsva.slack.com/archives/CBU0KDSB1/p1610040664174500?thread_ts=1610038757.163400&cid=CBU0KDSB1

**Comment by jhonnyoddball** [comment]
There have been times where there are some commits that are in prod but never made it to dev/staging environments. This is due to the way that we skip deploys when a build finishes if there’s a later build in progress.

Jeremy Britt brought this up again on [slack](https://dsva.slack.com/archives/C5HP4GN3F/p1614011014002700)

Jeff Balboni made a suggestion in [slack](https://dsva.slack.com/archives/C5HP4GN3F/p1614011547008600)

```
I was wondering if separating the staging deploy from the build would make this better. You could in theory have a deploy job that ran every 15 minutes, checked for the latest undeployed, successfully built commit, and deployed it if it wasn’t on staging.
```

**Comment by mchelen-gov** [comment]
yeah this seems to be a consequence of the build/deploy logic. is it possible to improve that logic rather than adding a manual workaround?

**Comment by meganhkelley** [comment]
This functionality already exists — @U-DON will add to documentation here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/workflow/deploy/
