### ISSUE TITLE
need feedback: light-support track and earning trust

### ISSUE THREAD

**Issue by leahbannon** [department-of-veterans-affairs/va.gov-team#17]
#### Hypothesis
A “light support track” or opportunities for teams to earn trust (and therefore require less support and/or oversight) will help us handle the pressure to take on new Platform teams (and requests to ship something on va.gov). **I don’t see a viable path forward on this challenge in the short term. I suggest focusing on Intake (see below) and other Platform MVP iteration underway.** But of course, I’m interested in y’all’s thoughts on this.
**Priority:** Scaling

#### Current approach:
Primarily organized by internal/external team. 
* internal = USDS contractor and their sub?
* external = all other VA contractor
We’ll likely need to more clearly define this model as we grow — more on that [**HERE**](#18)

Do we foresee a future in which we don’t require someone from the VA.gov prime contractor team to do a final PR review before merging? For example, some teams are responsible for certain sections of code/repos after earning trust?

#### Major support/oversight and opportunities for gaining trust
* checkpoints — I really doubt we’d want to cut back on these - feedback from teams indicates these already provide minimum necessary review to prevent significant rework by external teams. (There’s more on this in the journey map [**HERE**](https://app.mural.co/invitation/mural/adhocvetsgov9623/1544801162127?sender=leahbannon20088&key=bef4f899-a448-41d3-9d92-ea048249e116), but we have more research to do here.)
* pre-launch checklists (e.g., would we want to tell external teams their final launch reviews will go faster if they have stronger internal resources for 508, IA, content, analytics, etc?)
* shipping on Platform! (And continuing to ship good PRs)
* PR reviews
* We’ve done work on clarifying/improving guidance on PR size
* Is there more we should do here to cut down on context switching for reviewers?

#### Intake
Research we need to look into:
* How much extra work are teams doing for VIP? Is there a way to influence this work so it’s more re-usable when they start on Platform?
* Are teams doing unnecessary ATO work before starting on Platform?
* Ensure teams have full-time leads from VA biz and VA IT before they start on Platform.

**Comment by RobertAlexanderUSDS** [comment]
Thinking out loud, why do teams need to earn trust before building on the platform? What risk are we trying to eliminate? When I worked at AWS we tried to build strong building blocks, and we tried to stay out of the way of customers building what they wanted, in a way that made sense to them. Is it possible to run the platform without needing to manage trust for the products on the platform?

(hopefully a basic question, I'm missing a lot of the historical context)

**Comment by dmethvin-gov** [comment]
It might help to look at Mikey's pyramid:

<img width="866" alt="dickersons hierarchy of reliability" src="https://user-images.githubusercontent.com/40182224/50453931-426cd200-0912-11e9-950a-6bc2032f5812.png">

The deployment gate we're discussing here is really in the middle. Assuming a team has the tools they need post-deployment, they should be able to (and expected to?) resolve any issues that arise. We all know there *will* be issues, so all of those following steps are just as important as (and in some ways more important than) the previous ones.

To me the biggest reason a team might have low quality or unreliable content is if they don't have tools or motivation to avoid it. When post-deployment tools and processes are lacking, a waterfall-esque solution is to to have experts do code/process reviews and hopefully catch the problems by virtue of their experience, to reduce the need to iterate on issues that arise. I have doubts about the success rates of those kinds of efforts though.

At the moment I don't have access to the proxied internal tools, they can't be reached from the White House network so I will wait until I have a VA laptop and know what they can accomplish. I understand the rationale mentioned in [this document](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Work%20Practices/Engineering/Internal%20Tools.md#design-rationale) about not making all of these tools completely public. However, why not generate regular public top-level reports from these sites showing how well va.gov is doing? That would be useful for both the public and for cross-team comparisons.

Are there formal requirements and practices for application monitoring, incident response, and escalating phone-based or face-to-face issues that are UX-related? I'm still trying to get the lay of the land here so I may have missed them.

> Put another way, the value system of the platform owner and the user of a platform may be different. If the platform is driven too much by the needs of the owner, and not enough by the needs of the user, then the user may choose not to use the platform. A user will only use a platform if they think it gives them a net benefit based on their value system.

I think a larger risk here is that some VA group sees the great outcome of the current va.gov site, wants their service to be there, and essentially forces an external contractor to use the platform when they don't really "get it." I think the current [Handbook](https://department-of-veterans-affairs.github.io/va-digital-service-handbook/digital-standards) does a great job of steering them right, but it's still possible they might see the job as "port the code" and create a bad outcome. 

One of the reasons I'm emphasizing the bottom of the pyramid is that it can identify the problems in a way that scores them highly and makes them more likely to be solved, even if mistakes were made higher up the pyramid. If important problems of any kind *aren't* being solved by monitoring, for example, it means you aren't getting feedback on the right things.

**Comment by RobertAlexanderUSDS** [comment]
> I think a larger risk here is that some VA group sees the great outcome of the current va.gov site, wants their service to be there, and essentially forces an external contractor to use the platform when they don't really "get it."

Ooo, that's a great point. I missed that.

Throwing out some more thoughts:

### How do we ensure that teams have effective monitoring?
One tool we used at a previous private sector company was to have a multi-team, regular/recurring metrics drill down meeting, focusing on metrics/incidents of the previous week. The format was that a tech lead/representative/on-call from each team attended. A high level overview of each team's status was quickly reviewed based on public dashboards (30min). Then a team was selected randomly to present an overview of the incidents they had. Did the metrics detect the incident quickly and clearly? Did incident response/post-mortem occur effectively? How can we improve and prevent this issue from recurring? Teams were encouraged to share feedback and learn from each others experience. This meeting created incentives for teams to care about reliability. The random team selection ensured that teams always felt pressure to be prepared, while keeping the meeting duration short (I.E. lighter support was needed). Sometimes issues were identified in shared tools, and then responsible teams were tasked with fixing those tools.

This worked well for an environment that needed very high availability/reliability, but may be overkill depending on the needs of projects we have on the platform. I'd also be cautious about contract boundaries if I tried to implement something like this.

### How do we handle project - platform mismatch?
The platform probably works well for a certain set of projects.
* Do we have documentation to help teams decide if their project matches our platform well?
* If teams incorrectly think their project would work well on our platform, do we have a mechanism to redirect them before they spend too many cycles?
* Do we have a feedback mechanism so that the platform can be improved from concerns the project teams raise?

**Comment by lalexanderson-dsva** [comment]
So many good questions raised here. 
I can only really speak to this from the research, design, content, IA, and 508 perspectives, tho I will say that any team assuming the risk of running the platform also assumes the risk of any new features launched on that platform that may break stuff (in all the ways that could happen). 

My observations are that even teams we're inclined to "trust" - e.g. another Digital Service team or our prime contractors working on a different contract (e.g. Lighthouse/APIs) - still need a fair amount of guidance and input from the team managing the platform. More importantly, the earlier this guidance can come, the better; ideally, we do not want projects to be working in a silo for a while, come to us ready to "launch", and for us to identify a laundry list of reasons why they cannot. Especially in this nascent stage of managing new VA.gov and managing the platform, we are finding that we have to be much more hands on in figuring out how to fit other teams' additions into this new space. I'm not sure any of the teams - website, apps, or platform - are ready to experiment with the free-range parenting/light touch approach until we have shored up some of our systems (design, style guides, etc.)

A few examples of issues that have come up recently: 
- We disagree with the idea/concept: A trusted team wanted to add a feature that is a planned part of a future build and doesn't really make sense to build in isolation. 
- We disagree with the approach: A trusted team proposed some content for an FAQ page. As a general principle, we do NOT want FAQ pages on the site (good content and design shouldn't require FAQ pages); this precipitated a debate about whether we add theirs "as an exception" or not. 
- New additions create a domino effect of IA and content changes: A trusted team has a bunch of new pages to add to the site, which requires us to revisit a lot of existing content and pages on the site to figure out what needs to be retired, what needs to change to coexist, etc. 

The demand for building on the platform definitely is not the problem; I think it's the supply and the timing. We have a lot of unfinished business in tightening up our handbook, our style guide, our design system, our review processes, our feedback mechanisms, etc. Robert raised a good point about "project fit" and the need to decide how we determine if a project is a good fit to build with us. Even for "trusted" teams, I think we want them coming to us EARLY in their process so we can a) Decide if it's a good fit before they go down the road of writing requirements, doing research, drafting and testing content, etc. b) Get their teams *and ours* on the same page about what might need to change in order to accommodate an idea and plan for that work accordingly. I have come to realize that support is not just about helping a team do a thing on our platform, but also that everything that is added has associated work for OUR team too w/r/t IA, content, design, etc. 

P.S. I do really like the idea of a weekly sync with any and all platform teams to drill down into issues.
