### ISSUE TITLE
[Design] Facility v2 - 0 & 1 facility found

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17006]
## Background
When the Facility Selection v2 page returns 0 or 1 valid result, an alert box with respective message displays. With the improvements to the page that show results for valid facilities that don't have online scheduling enabled, we should review the context of alert and if updates need to be made.

**Example 0 facility**
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/1335bda9-ccb9-492d-8781-d99482db0b7c)

## Request

- [x] Updated D/T/M spec for 0 valid facilities

- [ ] Updated D/T/M spec for 1 valid facilities

**Comment by outerpress** [comment]
@laurenernest, looking at the 0 valid facilities error:
- I think it would be helpful to list their registered facilities that don't offer online scheduling - basically the same list we're showing in the new additional info box
- I'm not sure how helpful the last sentence is. It's fine that they can go back, but directing them to do so seems confusing. Maybe that's just me.

**Comment by laurenernest** [comment]
Agreed. Once you add the list where you want in the design, let's get guidance on the copy for the whole page with the new context.

**Comment by outerpress** [comment]
No facilities found message: https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/439890195

I'll put together the one facility found message once I can get a look at its current state.

**Comment by laurenernest** [comment]
Created the dev ticket for 0 facilities #18707

@outerpress The updated alert assumes the user has an address on file. What should happen if they don't? I'm thinking just updating the copy, no other interaction.

**Comment by outerpress** [comment]
@laurenernest I really liked your idea of sorting facilities by recently visited first. Any facilities we don't have a last visited date for could then be shown alphabetically. [Here's a mockup of that version](https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/442723004).

If we can't do that, then we just drop the distance note and sort the facilities alphabetically. [Mockup here.](https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/442723005)

**Comment by outerpress** [comment]
@laurenernest @jbalboni I just want to confirm, is this the 1 facility found alert?

![Screen Shot 2021-01-22 at 4.58.12 PM.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/d0203379-4a35-4a82-bf83-19852a86956b)

**Comment by laurenernest** [comment]
@outerpress I was thinking about this one
![image.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/b8695986-c700-48bc-a0dc-d3b52dc8cb2e)


@jbalboni @narin Follow up question- For these single facility alerts, could this show if they're only registered at one facility _**and**_ if they're registered at multiple but only one is available for online scheduling? https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md

**Comment by jbalboni** [comment]
@laurenernest Yeah, that shows up when there's only one facility that they can continue with, which could be for either of those reasons.

@outerpress That alert in your screenshot is when the user only has one facility enabled in VATS for scheduling, but they've failed to meet some eligibility condition. The specific text in that shot will happen in a pretty unlikely scenario, but there are other variations of that single facility warning alert.

**Comment by outerpress** [comment]
Thanks @laurenernest and @jbalboni ! I'd love to see any other variations of the single facility warning alert.

At least for the one you posted Lauren, I don't think that needs to be an alert, since they can continue scheduling with that facility, right?

We could probably just show them the facilities page with the single facility and new "Why isn't my facility showing" dropdown. We might just modify it to include some language explaining that we're only showing registered facilities.

The one I found is a block to scheduling further, so that makes sense as an alert.

**Comment by laurenernest** [comment]
@outerpress Agreed, that blue one doesn't need to be an alert since they can still continue.
The rest of the single facility alerts should be captured under Facilities Page in this [alerts documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/alerts-audit.md#facilities-page).

@jbalboni are we able to pre-select the facility when there's only one? so that we don't add an extra click if it's taken out of the alert style.

**Comment by outerpress** [comment]
Finally got a chance to dig into this. I think we can:
* Remove the alert styling
* Remove any content/functionality around sorting - I'm assuming that changing from address to location won't make a difference in the number of facilities that show.
* Display the single option without a radio button. This might be confusing since the title indicates you need to make a choice, but a single selected radio button would be confusing too (likely an issue for screenreaders as well). I might play with adding the "confirmed" checkmark next to this to see if it helps communicate that this is the one you're going to.

It'd probably be helpful to include the info that not all locations support all types of care. That could be added to the "Why isn't my facility showing dropdown" 

Example:
![Facilities-Update-v1-1-single-facility.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/70742afd-8e3e-43ce-bac2-f717b6af9c42)

**Comment by jbalboni** [comment]
@outerpress @laurenernest Either with or without the radio button works technically, we can pre-select if we need to show the button.

For that latest design, I feel like having "Choose a location" in combination with no form fields is more confusing than the single radio button option for screen reader users since they might not be able to visibly see all the content and be confident that they're not missing something, or that we haven't made a mistake by inaccessibly marking up content.

**Comment by outerpress** [comment]
Thanks @jbalboni , I was going back and forth on whether to change the title for this state. That makes a lot of sense. 

Here's an example with a title that makes this page more informational than action-based:

![Facilities-Update-v1-1-single-facility.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/73f35a6f-2bef-4f87-a7a4-9fb54ff29795)

This way we're meeting the spirit of the current alert state without making the page feel like a big context switch.

@peggygannon I'll want your input on this one too, for the title change, as well as the instructions underneath. I'm wondering if we should tweak it slightly so the instructions say something like - "We found one facility that offers [Type of care] appointments" so it's clearer that TOC is playing a role here.

**Comment by peggygannon** [comment]
@outerpress yes, I agree with that tweak. This would apply if only 1 facility is found?

**Comment by outerpress** [comment]
Yep, that's right @peggygannon - for context, [this is the current screen that displays for this state](https://camo.githubusercontent.com/a2ca2fe237df897fdc2e62f3b63014a55a424a0dfebbdd38cfce511732b8b648/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566376464326461643662396139333031626261623934652f62383639353938362d633730302d343862632d613064632d643362353264633863623265)

**Comment by outerpress** [comment]
@laurenernest I think all of the states are covered - here's the 1 facility found state as discussed: https://adhoc.invisionapp.com/share/W8ZLYPI2S53#/screens/444263109

Reopen if anything's missing.
