### ISSUE TITLE
Add additional debt letter types to debt_letter_downloader

### ISSUE THREAD

**Issue by voidspooks** [department-of-veterans-affairs/va.gov-team#17189]
## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by leahkeeler** [comment]
As a veteran logged into debt portal I want the ability to see all my debt, not just the 5 letter types slated for release. 

1. investigate if additional debts are in vbms 
2. if so, verify that the letters are retrievable

**Comment by rebeccawalsh** [comment]
@camerontesterman Quick question -- do you remember why this was in Icebox? What was the status of this ticket? We're trying to clean up BE backlog.

**Comment by LinnJS** [comment]
This looks pretty old and might be related to PDF work. @kevinmirc might be worth looking into.

**Comment by rebeccawalsh** [comment]
@LinnJS From a product standpoint, I'm pretty sure this ticket was about pulling the other debt letter types into the backend for us to surface on Debt Portal. Right now, we're just showing a few debt types because they're the only ones that were scoped (they were retrievable as PDFs while others weren't).

We talked through it and felt that, even if we're not able to display debt _letters_ for all of the debts we show in the portal, we should still surface the data from those debts and just let the Veteran know that the PDFs for those particular debts won't be available.

**Comment by denisecoveyduc** [comment]
Given the recent decision to move away from VBMS this is no longer under consideration.
