### ISSUE TITLE
Implement custom expires_at for save in progress forms

### ISSUE THREAD

**Issue by dillo** [department-of-veterans-affairs/va.gov-team#17206]
## User Story
**In order** to successfully complete my pre-visit questionnaire for a primary care appointment and then get the information to a clinician
**As a** Veteran
**I want** my custom questionnaire responses data to expire from the PostgreSQL database on the day of my appointment

## Related Documentation
[Backend Architecture](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/diagrams/Clipboard%20Application%20Architecture.png)
[MAP Appointments Swagger](https://veteran.apps.va.gov/appointments/v1/)
[MAP Information](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/Clipboard_vagov_sdd.md)
[Vetext](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/discovery/engineering/vetext-meeting-sept18.md#vets-apivetext-flow)
[JWT info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/questionnaire/engineering/MAP/scripts/getQuestionnaire.sh)

## Description
Provide the ability for the Health Quest module expire save in-progress form for the pre-visit form on the day the appointment was a scheduled.

## Acceptance Criteria
- [ ] SIP data for the pre-vist questionnaire must expire from the PostgreSQL database on the day of the appointment

**Comment by tlei123** [comment]
@mdewey , I've attached my local Cypress test-results test-file's attached here.  I'm gonna ping our F/E colleagues in #vfs-frontend to look into the listed failures below, for help determining if they're related to this new custom-SIP-expiration feature.

Most tests Passed.  Failed tests for 3 products/features:
- 11 out of the 12 failures failed regardless of whether this feature's Disabled or Enabled via local Flipper-UI.
- applications/facility-locator/tests/e2e/mobile.cypress.spec.js only failed with this feature Disabled.

in_progress_form_custom_expiration **DISABLED** FOR EVERYONE [12 failed out of 88]:
- applications/edu-benefits/1990/tests/e2e/edu-1990.cypress.spec.js
- applications/edu-benefits/1990e/tests/e2e/edu-1990e.cypress.spec.js
- applications/edu-benefits/1990n/tests/e2e/edu-1990n.cypress.spec.js
- applications/edu-benefits/5490/tests/e2e/edu-5490.cypress.spec.js
- applications/edu-benefits/5495/tests/e2e/edu-5495.cypress.spec.js
- applications/facility-locator/tests/e2e/mobile.cypress.spec.js
- applications/gi/tests/e2e/00-required.cypress.spec.js
- applications/gi/tests/e2e/03-vet-tec.cypress.spec.js
- applications/gi/tests/e2e/04-dea.cypress.spec.js
- applications/gi/tests/e2e/05-ojt.cypress.spec.js
- applications/gi/tests/e2e/07-gibct-mobile.cypress.spec.js
- applications/personalization/view-representative/tests/view-representative.cypress.spec.js

in_progress_form_custom_expiration **ENABLED** FOR EVERYONE [11 failed out of 88]:
- applications/edu-benefits/1990/tests/e2e/edu-1990.cypress.spec.js
- applications/edu-benefits/1990e/tests/e2e/edu-1990e.cypress.spec.js
- applications/edu-benefits/1990n/tests/e2e/edu-1990n.cypress.spec.js
- applications/edu-benefits/5490/tests/e2e/edu-5490.cypress.spec.js
- applications/edu-benefits/5495/tests/e2e/edu-5495.cypress.spec.js
- applications/gi/tests/e2e/00-required.cypress.spec.js
- applications/gi/tests/e2e/03-vet-tec.cypress.spec.js
- applications/gi/tests/e2e/04-dea.cypress.spec.js
- applications/gi/tests/e2e/05-ojt.cypress.spec.js
- applications/gi/tests/e2e/07-gibct-mobile.cypress.spec.js
- applications/personalization/view-representative/tests/view-representative.cypress.spec.js

I'm having trouble getting the "deprecated" nightwatch tests to run on my local -- I've pinged #vfs-frontend Slack-channel for help.  I'll keep you posted on this.


[in_progress_form_custom_expiration_cypress_test_results_210105.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/5782904/in_progress_form_custom_expiration_cypress_test_results_210105.txt)

**Comment by tlei123** [comment]
Cypress test-results UPDATE...

@mdewey , I've re-run the local Cypress tests, this time manipulating the specific Flipper settings in the existing, mocked **feature-toggles.json** files instead of via Flipper-UI.

More tests passed this time; same 6 failures out of 88 for both Enabled and Disabled.

in_progress_form_custom_expiration **TRUE**:
- applications/gi/tests/e2e/00-required.cypress.spec.js
- applications/gi/tests/e2e/03-vet-tec.cypress.spec.js
- applications/gi/tests/e2e/04-dea.cypress.spec.js
- applications/gi/tests/e2e/05-ojt.cypress.spec.js
- applications/gi/tests/e2e/07-gibct-mobile.cypress.spec.js
- applications/personalization/view-representative/tests/view-representative.cypress.spec.js

in_progress_form_custom_expiration **FALSE**:
- applications/gi/tests/e2e/00-required.cypress.spec.js
- applications/gi/tests/e2e/03-vet-tec.cypress.spec.js
- applications/gi/tests/e2e/04-dea.cypress.spec.js
- applications/gi/tests/e2e/05-ojt.cypress.spec.js
- applications/gi/tests/e2e/07-gibct-mobile.cypress.spec.js
- applications/personalization/view-representative/tests/view-representative.cypress.spec.js

I'm still working on making the nightwatch tests working on my local -- I'll probably make an inquiry in Paul Short's VSA Front End Dev Topics mtg tomorrow.

Lemme know what you think.  Thx much!

**Comment by mdewey** [comment]
@tlei123  With the mocking, are you testing the API at all. This is an API only change.

**Comment by tlei123** [comment]
@mdewey , technically no -- I didn't directly test the API itself, BUT @dillo 's changes were pulled into vets-api, and vets-api rebuilt & restarted before the above Cypress tests.

VSA-QA is currently only covering browser testing (frontend behavioral & visual testing).  Sorry for any confusion, here are the [VSA-QA docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/engineering/qa) again.  I hope to expand involvement to other testing areas/aspects if/when QA staffing increases.
