### ISSUE TITLE
Security Review AI's before Direct Deposit Launch - Sidkiq Failures

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#1735]
File a ticket to investigate what happens to Sidekiq failures

Doesn't have to be followed up on before launch

Link to the the vets.gov repo - [19647] (https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets.gov-team/19647)

**Comment by lihanli** [comment]
errors in sidekiq jobs are logged to sentry. sidekiq will retry the DirectDepositEmailJob for 24 hours. afterwards it moves the job into Sidekiq::DeadSet. dead set jobs can retried manually through the console. jobs in the dead set are deleted after 6 months. https://github.com/mperham/sidekiq/wiki/Error-Handling

**Comment by gunsch** [comment]
Hey, I see you documented _what happens_ above but then closed this without much follow-up. Questions I have:

* are we okay with this behavior?
* is anyone notified when jobs end up in DeadSet?
* sure, they _can_ be manually retried, but is anyone actually doing that?

**Comment by gunsch** [comment]
cc @annaswims @johnpaulashenfelter PTAL at above

**Comment by Justin-Pickett** [comment]
@lihanli  will follow up on this item.

**Comment by lihanli** [comment]
i don't think we should be retrying jobs in the deadset manually for the same reason that we don't automatically retry the job for more than one day, because it would be strange if a user received an email about someone changing their banking information many days after they actually did it. i do think we should alerted the first time the `DirectDepositEmailJob` fails and made an issue for that https://github.com/department-of-veterans-affairs/va.gov-team/issues/2115

**Comment by Justin-Pickett** [comment]
@lihanli any updates regarding this ticket?

**Comment by Justin-Pickett** [comment]
will close this ticket. it is covered in ticket 2115.
