### ISSUE TITLE
IRIS Q&As: Education -- General -- Incorporate SME Feedback

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#17449]
### SME feedback and revisions to general education articles for resources and support

Articles were broken into batches. 

- [x] Batch 1 content for the following four questions was routed to SMEs on 12/14/20:

-  Can I get a replacement Certificate of Eligibility?: http://preview-prod.vfs.va.gov/preview?nodeId=14971
-  How VA education benefit payments affect your taxes: http://preview-prod.vfs.va.gov/preview?nodeId=15137
- How do I get college credits for my military service?(single QA) http://preview-prod.vfs.va.gov/preview?nodeId=15126
- What if my school closes because of a hurricane or natural disaster? http://preview-prod.vfs.va.gov/preview?nodeId=14968

Feedback to this and subsequent batches should be attached below under the appropriate header. 

### Copy decks routed to SMEs for feedback:
[https://app.zenhub.com/files/133843125/5e45b821-91a2-4aa8-8f18-0b8876301513/download]

### SME feedback documents:

[https://app.zenhub.com/files/133843125/f25b2ffb-fa37-4fe3-804c-1b76f830237a/download](https://app.zenhub.com/files/133843125/f25b2ffb-fa37-4fe3-804c-1b76f830237a/download)

### Acceptance Criteria

- [ ] Revisions complete. New copy deck attached to GH ticket for copyediting and publishing.

**Comment by bethpottsVADEPO** [comment]
@lunascoop I attached SME feedback above. Note that there is one link to create, pointing to the IRIS form. 
@lwalsh617 for awareness.
@RLHecht for copyediting and next step of publishing.

**Comment by lunascoop** [comment]
@RLHecht @bethpottsVADEPO 
I've made the edits, and noted some things below, somewhat as a reminder of some of the changes I made when creating the articles in Drupal.

- Can I get a replacement Certificate of Eligibility?: http://preview-prod.vfs.va.gov/preview?nodeId=14971 

   - (Changed CTA button to link to about GI Bill benefits, since we can't link phone numbers in CTA buttons. Made this change during initial creation of Drupal article.)

   - (Re: wanting to add a "Note" to IRIS link (see Word doc), I assume you meant to add the copy Tammy commented as a “note” beneath the first bullet. If so, the link for Go to our Inquiry Routing & Information System (IRIS) already has the user on the “Ask a Question page. This “Note” is somewhat repetitive. I’ve revised the copy in Drupal to cover everything Tammy mentioned.)
- How VA education payments affect your taxes: http://preview-prod.vfs.va.gov/preview?nodeId=14963 (Used the learning center detail page template instead of multiple QA template. Made this change during initial creation of Drupal article.)
- Get college credits for your military experience (changed title from How do I get college credits for my military experience? in Word doc): http://preview-prod.vfs.va.gov/preview?nodeId=14964 (Used the learning center detail page template instead of single QA template because copy exceeded character limit by 209 characters. Reworked some of the copy to add an intro text (per the template) and reworked title. Made this change during initial creation of Drupal article.)
- What if my school closes because of a hurricane or natural disaster?: http://preview-prod.vfs.va.gov/preview?nodeId=14968

**Comment by lwalsh617** [comment]
@bethpottsVADEPO @RLHecht -- SEO research attached. For COE, the keyword is "certificate of eligibility gi bill." For hurricane vs natural disaster there's no performing keyword. See Word doc for all variations that I tried. No monthly volume results until you get to the general term "school closings" and then it's related to snow days. You can see from the keyword suggestions that there's no volume around closures + gi bill. With no high performing keyword, maybe we go more general, "What if my school closes temporarily?" That covers any type of short-term closure. 
[Education SEO.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5716733/Education.SEO.docx)

**Comment by bethpottsVADEPO** [comment]
I'm closing this one. SME feedback and edits per SEO results have been incorporated. Now we're waiting for FE devs to resolve the issue with adding a less-than-5-article content block to the home page without the system thinking there's a broken link.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Let's talk about the templates for these two:

How VA education benefit payments affect your taxes
Get college credits for your military experience

I just want to set a good precedent for template choice. I want to understand why you chose "about" rather than "multiple FAQ"--and we can discuss whether we should switch to multiple FAQ before these go live. Specifically, if we're going to ask questions in the H2s, shouldn't they be single Q&As rather than part of an About article? And should our go-to structure for these articles necessarily be Q&As? I'm not sure. Are there CMS constraints that steered you toward About templates in both of the above cases?

**Comment by lunascoop** [comment]
@bethpottsVADEPO 
**re: How VA education benefit payments affect your taxes**
Looking at the word document, I can't readily recall why I chose the "about" template over "multiple QA" as it technically shouldn't have been a problem. I was likely thinking at the time as to if it was necessary, and wasn't thinking about being consistent in using the "Single QA" template for an H2 article question. I can switch this to a multiple FAQ article. 

**re: Get college credits for your military experience**
The word doc in the [first ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17407) noted to use the "Single QA" template to create this article. But I switched to the "About" template because the copy exceeded "Single QA's" character limit by 209 characters. There was no H2 in the initial draft copy for this page(which eliminated the possibility in using the "multiple QA" template). And the current H2s for this article aren't written in question format.

I kind of forgot the reason why we decided to make all H2 questions as a single QA and not use the "About" template, especially in instances like the [Veteran Identification Card (VIC) FAQs page](https://www.va.gov/resources/veteran-identification-card-vic-faqs/), where the single QAs/H2s are barely a sentence or more. 

- Did we solely do this for consistency? 
- Or for SEO and a better user experience since the template type displays above the article (see [Slack thread](https://dsva.slack.com/archives/G01CB9XH8UT/p1607444085001500))? The content structure has to match the template type. 
- Is it an issue that we used the "About" template instead of the "multiple FAQ" template for some articles such as [Life insurance if you have pre-existing conditions](http://preview-prod.vfs.va.gov/preview?nodeId=15059) because of a character limit issue or WSYWYG feature constraint. 
- Do we plan to publish any of these H2 questions as a single Q&A standalone article or include in multiple FAQ articles?

To your question:
>  Should our go-to structure for these articles necessarily be Q&As? I'm not sure. 

Are you asking: If the H2 isn't written in question format, should we still use the single Q&A template? Yes, we could technically do this, but this may confuse users since the front-end currently displays the template type above the article title. And it's technically not a multiple FAQ if the single FAQs aren't in question format. I think we discussed via Slack that there'll be R&S content testing, so we'll get feedback on how helpful showing the template type above the article is to users.

**Comment by bethpottsVADEPO** [comment]
@lunascoop These are all things I'd like to discuss as a group. It seems like part of the thought process when deciding which template to use should be whether the Q&As are one-off questions that happen to be on the same topic, in which case we should use the single Q&A to multiple FAQ structure. If there's an opportunity to arrange the article in an about template in a more cohesive way using H2s, then that's the way to go. Also, we'd need to use the about template when the info exceeds the character count for a single Q&A. 

We should also set the precedent for H2s not being in the form of a question, but continue to frame H1s for single Q&As as question. There may be exceptions to the former that we'll run into, but it doesn't make sense to use non-questions for single Q&As. After we discuss, it would be great if you could write up some guidance on this. It'll be helpful as more people start to use drupal.

Thank you for switching this template to be a multiple FAQ (so creating 2 single Q&As): How VA education benefit payments affect your taxes

Let's do the same for: Get college credits for your military experience
First Q&A: How do I request a transcript?
Second Q&A: What's in my transcript?

**Comment by lunascoop** [comment]
@bethpottsVADEPO Here are the node links for the two articles:

- How VA education benefit payments affect your taxes: http://preview-prod.vfs.va.gov/preview?nodeId=15137
- Get college credits for your military experience: http://preview-prod.vfs.va.gov/preview?nodeId=15127

**Comment by bethpottsVADEPO** [comment]
Hi @lunascoop --thanks for your patience with the college credits article. Danielle and I discussed that at some point we'll want to have a multiple FAQ about requesting your military transcript and all the ways it can help you--for education credits, employment, counseling, etc. So with that future article in mind, we'd like to make this one that's specific to getting college credits a single Q&A. Here it is--can you create this one below and delete the multiple FAQ you created and one of the singles? You can repurpose the other single and populate it with the below content:

**How do I get college credits for my military service?**

As an active-duty service member, Veteran, or member of the Reserves, you’ll need to request your transcript from your branch of service and share it with schools. Each school or program then decides how many credits they’ll accept.

Learn about the process for your branch of service:

- **For the Army, Navy, Marines, or Coast Guard,** go to the Joint Services Transcript (JST) website. Fill out the Official Transcript Request form to share your transcript with schools online.
- **For the Air Force,** contact the Community College of the Air Force to learn about the ways you can request your transcript. They'll mail your transcript to you.

Your transcript shows how many credits the American Council on Education has recommended for each military experience, including:
- Military Occupational Specialty (MOS) training
- Army Advanced Individual Training (AIT)
- Military jobs
- Courses you’ve completed

Your transcript may also include other courses or jobs that the American Council on Education hasn’t evaluated.

**Comment by bethpottsVADEPO** [comment]
@lunascoop Sorry, the links got stripped out, above, but they're the same as are in the current article you have up--for JST and CCAF.

**Comment by lunascoop** [comment]
@bethpottsVADEPO The new copy exceeds the Single QA character limit by 42 characters. Should I just recreate it as an About template?

**Comment by bethpottsVADEPO** [comment]
@lunascoop Without the H1, it's over by just 3 characters. I've rewritten the last sentence to fix that! Thank you. Here it is:

**How do I get college credits for my military service?**

As an active-duty service member, Veteran, or member of the Reserves, you’ll need to request your transcript from your branch of service and share it with schools. Each school or program then decides how many credits they’ll accept.

Learn about the process for your branch of service:

- **For the Army, Navy, Marines, or Coast Guard,** go to the Joint Services Transcript (JST) website. Fill out the Official Transcript Request form to share your transcript with schools online.
- **For the Air Force,** contact the Community College of the Air Force to learn about the ways you can request your transcript. They'll mail your transcript to you.

Your transcript shows how many credits the American Council on Education has recommended for each military experience, including:

- Military Occupational Specialty (MOS) training
- Army Advanced Individual Training (AIT)
- Military jobs
- Courses you’ve completed

Your transcript may also include other courses or jobs not evaluated by the American Council on Education.

**Comment by bethpottsVADEPO** [comment]
Thanks, @lunascoop! That's a great edit. I'll shorten it even further to: 
For the Air Force, contact the Community College of the Air Force to request your transcript. They'll mail it to you.

@RLHecht For awareness, I'll send these preview nodes to the SMEs for one last look before we put the pages live.

**Comment by lunascoop** [comment]
@bethpottsVADEPO @RLHecht FYI, for the "getting college credits for military experience" multiple QA, I deleted the multiple QA template and About template versions per Beth's previous comment here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17449#issuecomment-752774860

All that remains is the **How do I get college credits for my military service?** single QA, which is here: http://preview-prod.vfs.va.gov/preview?nodeId=15126

The other articles related to this ticket include (I'll also post them in the ticket description):

- How VA education benefit payments affect your taxes: http://preview-prod.vfs.va.gov/preview?nodeId=15137
- Can I get a replacement Certificate of Eligibility?: http://preview-prod.vfs.va.gov/preview?nodeId=14971
- What if my school closes because of a hurricane or natural disaster?: http://preview-prod.vfs.va.gov/preview?nodeId=14968

**Comment by RLHecht** [comment]
These four articles have been published and are live on the site. Closing ticket.

**Comment by bethpottsVADEPO** [comment]
We're done here.
