### ISSUE TITLE
[Discovery] Recruit for Research Sessions

### ISSUE THREAD

**Issue by kevinstachura** [department-of-veterans-affairs/va.gov-team#1752]
## Goal
We want to recruit participants for our Claim Status Tool research study

## Acceptance Criteria
- [x] The research plan has been attached to this ticket
- [x] Lauren Alexanderson has been assigned
- [x] Identify available dates / times for the sessions
- [x] Identify observers to Perigean (in Slack)
- [x] Recruiting has been kicked off with Perigean

**Comment by kevinstachura** [comment]
@lalexanderson-dsva can you please review the Research Plan documentation? Located here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/discovery-SEP-2019/research-plan.md

Thank you!

**Comment by lalexanderson-dsva** [comment]
Hi @kevinstachura  and @smoonpeyes. Just looked at your research plan. We do not have the granularity of detail in Perigean's recruiting database to be able to find people who have erroneously done this submission on VA.gov because this tool is too new to the website. I'm not confident that we will be able to get you the profile you're looking to talk to via Perigean, unless you are planning to provide a list of people who have submitted decision review through the claims status tool. It was not clear to me from your research plan if you have this list already.
