### ISSUE TITLE
[Design] Homepage - Distinguish phone only appointments

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17548]
## Issue Description
Phone-only VA appointments appear the same as in-person appointments on the pending and confirmed homepage cards.

Depends on BE adding boolean https://issues.mobilehealth.va.gov/browse/VAOSR-1334

**Comment by outerpress** [comment]
@laurenernest digging into this one, we should consider better instructions for phone appointments. A couple questions on that front: 

* Are Veterans expected to call, or will the facility call them?
* If the Veteran's calling, are we providing an extension/name of the person to contact?
* What other info/instructions should we provide them - like if the number's busy, or if they don't receive a call, etc.

I don't think we need to change the language for the appt review page. And for the "pending appointment" card we might remove the "VA Appointment" label and add a note that they requested a phone appt (since it could change after the scheduler gets back to them).

**Comment by laurenernest** [comment]
Answers to your questions below. We should split this into 2 pieces of work: 1) Adjust the labeling on the card (since we can do that without additional info), 2) Update with better instructions

> Are Veterans expected to call, or will the facility call them?

The facility will call them

> If the Veteran's calling, are we providing an extension/name of the person to contact?

n/a

> What other info/instructions should we provide them - like if the number's busy, or if they don't receive a call, etc.

Kay's going to ask about this

**Comment by outerpress** [comment]
Thanks! 

Another question - is this only for VA Appointments that are over the phone (not Community Care?)

Here's a first pass (with some filler where the instructions might go)

![Phone appointment](https://user-images.githubusercontent.com/2536801/103036464-b00e6180-451e-11eb-97d6-332c9df2e7f2.png)

**Comment by laurenernest** [comment]
Correct, only for VA not CC.

- Do you want to get Peggy's recommendations on the top label or are you comfortable moving forward with "over the phone"?
- Can you also account for the placement of the [booking note](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/design/appointments-cards/confirmed-va-note.png) placement with respect to the additional "we will call you" section?

**Comment by outerpress** [comment]
Thanks! Cleaned this up a bit with booking note placement and added tablet/desktop view: https://adhoc.invisionapp.com/share/7MZT9KV6UAY

And yep, while I think the top label I suggested will work if we wanted to get this out ASAP, Peggy will need to review that language, as well as whatever instructions we eventually come up with. 

Just for reference, here are the other top labels we're using:

- VA APPOINTMENT
- VA VIDEO CONNECT at home
- VA VIDEO CONNECT at a VA location
- VA VIDEO CONNECT using a VA device
- VA VIDEO CONNECT at an ATLAS location
- COMMUNITY CARE

**Comment by peggygannon** [comment]
Hi, @laurenernest and @outerpress 
The label above is fine: VA APPOINTMENT over the phone
