### ISSUE TITLE
Is there any reason the VA.gov Profile might treat some address updates as _creations_

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#17625]
We are seeing a fair amount of 301 errors from VA Profile when users attempt to update an address. This is because VA.gov is making a POST call when we should be making a PUT call. ie, the user already has an address on file, but we are acting as though they do not.

The FE needs to:
- [ ] investigate the logic behind determining if we make POST or PUT calls during an address update and determine if there are any holes in that logic

**Comment by Samara-Strauss** [comment]
Bringing over some of my analytics notes from Slack:

You can see [in this report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22PT%22,%22address%22,0%5D%5D&explorer-table.secSegmentId=analytics.customDimension57&_r.drilldown=analytics.eventLabel:profile-edit-failure) that the 301 failures are happening for **home address only**, whereas other errors have a more even distribution between both mailing and home addresses.

<img width="1062" alt="Screen Shot 2020-12-17 at 2 37 54 PM" src="https://user-images.githubusercontent.com/34068740/102536274-62ee4380-4077-11eb-8414-b52387cec352.png">

[In this report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20201210&_u.date01=20201216&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:profile-edit-failure,analytics.eventAction:Profile%20Save%20Failure%20-%20Home%20Address/), which shows how many 301 errors per day, we can see there is a significant uptick since Monday, 12/14.

<img width="1046" alt="Screen Shot 2020-12-17 at 2 40 46 PM" src="https://user-images.githubusercontent.com/34068740/102536365-83b69900-4077-11eb-9e2e-dc1c4234dfc9.png">

**Comment by Samara-Strauss** [comment]
Also adding [this from Slack](https://dsva.slack.com/archives/C909ZG2BB/p1608233138242800), mostly so it doesn't get lost and I can keep track of all the things:

From Erik:

> @Samara (She/Her) @Matt Shea Joshua uncovered a relatively new bug that could introduce some 301s (but doesn't explain all of the 301s since those have been happening since before this bug was introduced). I will make a ticket to revise the `My home address is the same as my mailing address` checkbox behavior so that unchecking it never totally wipes out the underlying address data that might already exist. That should resolve some (maybe a lot) of the 301s. (

**Comment by erikphansen** [comment]
Actually didn't make a new ticket as I said in Slack. We are using this ticket to track the work to fix the issue.

**Comment by erikphansen** [comment]
Closing this since Sandra merged in her fix. Will make a new ticket if 301s pop up again.

**Comment by Samara-Strauss** [comment]
Great, thanks! I'll check back in on the analytics on Monday.
