### ISSUE TITLE
Release plan | Translations | Spanish | Corona FAQs

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#17741]
## Acceptance Criteria
- [x] Make a copy of the [release plan template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md):

See: [https://app.zenhub.com/files/133843125/a2bf0d4d-cbf3-4299-a02a-5e1eee152a09/download](https://app.zenhub.com/files/133843125/a2bf0d4d-cbf3-4299-a02a-5e1eee152a09/download)

- [x] Complete release plan for launch

## How to configure this issue
- [x] **Attach to appropriate Epic**  
- [x] **Labeled with Team**

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi Danielle - can you review the link to the Release Plan and let me know if this looks ok?

cc: @youngfreezyVA

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. I looked at the link above. What I see looks good, but it looks like an image of only part of a page so I'm not sure if there's more I should be reviewing?

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi - yes your are correct. The full page is here:https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/release-plan-template.md 

I deleted what I thought wasn't applicable but take a look and let me know if I should add anything else from the template's outline for our release. Thx!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @SKasimow. Following up on this. 

I think the plan looks good, and agree that we don't need metric-based criteria before advancing to full roll out since this is just Drupal content with links between pages.

Let's check in at our meeting later today about whether we want to add some more info in the Go Live section. For example, something around the satisfaction survey results and/or call center results (ie, if we see low satisfaction rates or negative feedback via the contact centers after the first month, we'll want to look into doing more usability testing, evaluating translation quality, etc.).

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/spanish-translation/coronavirus-mvp/product-outline.md

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA  Hi - I replaced the excerpt with the release plan template and filled out as best I could. Please take a look.
