### ISSUE TITLE
STEM AD: Email Applicant 10203 Decision Ready

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17770]
As a STEM applicant, I need to be notified when a decision has been made regarding my application for the STEM scholarship so that I can review the details of the claim..

## Assumptions:
1. This story is completed behind feature flag `stem_automated_decision`.
2. A preview version is available at [http://localhost:3000/rails/mailers](http://localhost:3000/rails/mailers) that either uses fake data or most recent 10203 submission
3. This email will be sent to the address that is submitted with the STEM application. 

## Acceptance Criteria
1. A job is utilized to send email for automated decision.
    a. Job will find saved form 22-10203 with status of DENIED.
    b. An email populated using template in SA1 is sent to the applicant.

## Supporting Artifacts:
1. Email content: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-email-content.md

**Comment by shawkey-daniel** [comment]
As a STEM applicant, I need to be notified of the automated decision to deny my application for the STEM scholarship so that I am informed about my benefits.

## Assumptions:

1. This work is completed behind a feature flag as outlined in AC1.

## Acceptance Criteria

1. This story is completed behind feature flag `stem_automated_decision`.
2. When automated decision is made, an email populated using template in SA1 is sent to the form 22-10203 applicant.
    a. This is behind feature flag `stem_automated_decision`
    b. A preview version is available at [http://localhost:3000/rails/mailers](http://localhost:3000/rails/mailers) that either uses fake data 
    or most recent 10203 submission
3. Applicant appeal rights document SA2 is stored and externally available on VA.gov.
4. Link to appeal rights is included in the email template.

## Supporting Artifacts:
1. SA1
2. SA2

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/6062

**Comment by delli-gatti-michael** [comment]
[Testrail Test case](https://dsvavsp.testrail.io/index.php?/tests/view/80535)

**Comment by delli-gatti-michael** [comment]
Local testing complete

**Comment by delli-gatti-michael** [comment]
Email received. Closing this issue
