### ISSUE TITLE
STEM AD: Queue solution

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#17771]
As a developer, I need to create a job to process form 22-10203 for automated decision, so that form are processed during EVSS service uptime hours.

## Assumptions:
1. This work is completed behind a feature flag as outlined in AC1.
2. The job being referenced here is a sideqik job. 
3. For unauthenticated users, the submission is not added to the automated denial queue.

## Acceptance Criteria
1. This story is completed behind feature flag stem_automated_decision.
2. A job is configured to process form 22-10203 submissions.
3. Job is configured to run during EVSS service uptime (The tool is available Sunday through Friday, 6:00 a.m. to 10:00 p.m. ET, and Saturday 6:00 a.m. to 7:00 p.m. ET) Suggest 6 a.m. to 6 p.m. everyday to encompass uptime and keep it simple.
4. Job will look up previous application if it exists.
5. For users with EVSS data with no previous application:
    a. If the applicant answered no to the following questions, the form will be saved with status of DENIED.

       i. Are you enrolled in a science, technology, engineering, or math (STEM) degree program?
       ii. Do you have a STEM undergraduate degree and are now pursuing a teaching certification?

    b. If the applicant has greater than 180 days of remaining entitlement in EVSS, the form will be saved with status of DENIED.
    c. Otherwise, the form is saved with a status of PROCESSED.
6. For users with EVSS data with a previous application:
    a. If answers to the following questions are the same as previous submission, the form is saved with a status of PROCESSED.

       i. Are you enrolled in a science, technology, engineering, or math (STEM) degree program?
       ii. Do you have a STEM undergraduate degree and are now pursuing a teaching certification?
       iii. About how much of your education benefit do you have left?

    b. If answers are different, process as if there is no previous application (AC 5).
7. For users without EVSS data,  the form is saved with a status of PROCESSED.

## Supporting Artifacts:
1. [AutomatedDenial_Routing_DecisionTable.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/5776132/AutomatedDenial_Routing_DecisionTable.xlsx)
2. Q+A for AC5a & b:
![image](https://user-images.githubusercontent.com/48260534/104374538-02281e80-54f0-11eb-83b8-7fb9af2e2a78.png)

**Comment by shawkey-daniel** [comment]
As a developer, I need to create a job to process form 22-10203 for automated decision, so that form are processed during EVSS service uptime hours.

## Assumptions:
1. This feature flag was created in #12467.
2. UAT has been completed for this effort as of 11/09.
3. The new functionality is live in production with no need remaining need for the toggle.
4. The limited production rollout is completed as of 12/01.

## Acceptance Criteria
1. A job is configured to process form 22-10203 submissions.
2. Job is configured to run during EVSS service uptime (The tool is available Sunday through Friday, 6:00 a.m. to 10:00 p.m. ET, and Saturday 6:00 a.m. to 7:00 p.m. ET) Suggest 6 a.m. to 6 p.m. everyday to encompass uptime and keep it simple.
3. Job will look up previous application if it exists.
4. If no previous application:
    a. If the applicant answered no to the STEM degree/teaching certificate questions, the form will be saved with status of DENIED.
    b. If the applicant has greater than 180 days of remaining entitlement, the form will be saved with status of DENIED.
    c. Otherwise, the form is saved with a status of PROCESSED and submitted for manual decision.
5. If previous application:
    a. If answers are same as previous submission, submit form for manual decision.
    b. I answers are different, process as if there is no previous application (AC 4).

## Supporting Artifacts:
1. N/A

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/5619

To test after submitting the forms for the AC run `EducationForm::Process10203Submissions` then `CreateDailySpoolFiles` sidekiq jobs

**Comment by delli-gatti-michael** [comment]
Closing this out with #18622 as a follow-up story for dealing with an EVSS data retrieval issue
