### ISSUE TITLE
Project Kickoff [VAOS - Homepage Refresh]

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#17932]
## Steps to complete Project Kickoff
- [x] VFS Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] VFS: Attach all relevant artifacts to the ticket
- [x] VFS: Link to this issue once created in [#vfs-platform-support](https://dsva.slack.com/channels/vfs-platform-support) in Slack; tag @ Shira Goodman and @ AndreaHewitt 
- [x] VSP: Schedule meeting with VSP reviewers and requesting team attendees (as listed below)
- [x] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/u/1/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809) is updated

## Artifacts - _please bring the following to the kickoff meeting_
- [Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/product-projects/homepage-refresh-initiative-2021.md)
- [Prototype](https://adhoc.invisionapp.com/d/main#/console/20927730/440676958/preview)

## Meeting attendees from **requesting team**
- Product Manager (required): Lauren Ernest
- DEPO Product Lead (required): Lauren Alexanderson, Ryan Thurlwell, Leanna Miller
- Entire VFS team (recommended): Jeff Balboni, Kam Karshenas, Peter Russo
- Other specialists: Design, Content, Accessibility, QA

**Do you anticipate this initiative requiring updates to and/or creation of unauthenticated static content pages?** YES (more of a maybe)
https://www.va.gov/health-care/schedule-view-va-appointments/

### Preferred times
- 1/6 - 11:30am ET
- 1/7 - 1:30pm ET
- 1/19 - 11:30am ET

**Comment by shiragoodman** [comment]
hey @laurenernest and the VAOS team. Thank you for meeting with us today, showing us your prototype and helping us test our questions. We had a few things we wanted to bring to your attention:

1. We noticed a few areas where your prototyped designs diverge from the approved patterns in the Design System. We'd like to help you iterate on those now, so that you don't unintentionally end up usability testing patterns that you won't be able to use in production. This will involve us reviewing your prototype and giving you feedback in a Github issue for you and your DEPO Lead to consider taking action on prior to conducting the usability tests. Could you submit a [Usability Testing Prep ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=andreahewitt-odd%2C+shiragoodman&labels=vsp-product-support%2C+content-ia-team%2C+collaboration-cycle%2C+collab-cycle-review&template=usability-testing-prep.md&title=Usability+Testing+Prep+%5BTeam+Name%2C+Feature+Name%5D) so we can get started? We can coordinate on dates.
2. If you want to intentionally use a new design pattern, please be sure to specifically test that pattern against the prior one. In order for a new pattern to be added to the design system, and thus used in production, usability testing and accessibility testing need to indicate that this new design works better for users than the prior design (if there is a prior design). Ideally the design system team will then coordinate with the rest of the teams across VA.gov to update their patterns to use the newer, better design. This is so that we don't have users encountering different experiences for the same action from one VA.gov to another.)
3. Related to 2. -- InVision doesn't work so great for screen readers, so if you do want to use a new pattern, this is a head up that you'll need additional usability testing at some point prior to launch to make sure the pattern works well for users with disabilities. 

With that said, these are the Collaboration Cycle points we recommend for your initiative:

- Usability Testing Prep (per # 1 above)
- IA Request
- Research Plan Review
- Analytics Request
- Staging Review
- (while a Contact Center Review is probably not necessary, I'd advise that you reach out to the team just to verify that your existing Product Guide and/or Product Video is not in need of updating)
- Privacy & Security Review

Post Launch:

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

Thanks! Please let me know if you have any questions. The [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) has been updated with this information.

**Comment by outerpress** [comment]
Here's the public link to the prototype for anyone without an Ad Hoc Invision login: https://adhoc.invisionapp.com/share/URZV3YHCQFZ
