### ISSUE TITLE
[Development] Create pre-fill form profile for Higher Level Review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1803]
## User Story or Problem Statement
As a Veteran, I need to have all of my relevant information that the VA has stored about me to be pre-populated for me in the Higher Level Review form so I can avoid having to enter it again.

## Goal
_Avoid the need for user to be required to enter information that the VA already has about them_

## Acceptance Criteria
- [ ] Create a form profile to populate pre-fill data
- [ ] Add fields to `form_profile_mappings`
- [ ] Add form id to `form_profile` base class

**Comment by SMLuthi** [comment]
Theres a couple reasons this can't/shouldn't be finished yet.

1) We need to figure out which data is required for prefilling given the current state of the form. The lighthouse API will not require any veteran PII (besides an identifier like the veteran file number/ssn) for their submission endpoint. Which means we technically dont need to provide it to the veteran. But we should talk about if we still should so that they can see its up-to-date OR redirect them to their profile page where they can validate it themselves.

2) For prefilling to test successfully, the forms schema has to exist in the vets-json-schema repository (since prefilling attempts to prefill with the forms schema in mind). Prefilling cannot be completed until that it is accomplished.

**Comment by SMLuthi** [comment]
This has been blocked since @Mottie add the schema for the form to the vets json schema repo.
