### ISSUE TITLE
[Design] Create LOA1 Design (MyVA Dashboard)

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18043]
## Background
We need to create the design for LOA1 users.

## Tasks
- [x] Create LOA1 design
- [ ] Review with Matt/Samara

**Comment by tressaellen** [comment]
@Samara-Strauss @mshea0606 - here's the LOA1 mock.  I removed the CTA's in each of the benefit sections since they won't be able to do any of that if they are LOA1. Let me know if you have any thoughts or questions. :)

![My VA LOA1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/d0eae715-5e10-442a-aca1-b030ed1077b2)

**Comment by Samara-Strauss** [comment]
> Also, I removed the CTA's in each of the benefit sections since they won't be able to do any of that if they are LOA1. Let me know if you have any thoughts or questions. :)

Please add the CTAs back. They can still start and save EDU applications as LOA1, and for health care and disability claims, we should link them to the application pages even though those will also tell pages will also prompt them to verify their identity. But without CTAs, that section is effectively pointless, so we should add them back.

Otherwise, this looks good to me. I do think we should customize the copy so someone knows why it's worth their while to verify their identity to use this page, but we can work with copy on that.

**Comment by tressaellen** [comment]
Sounds good to me - I added the CTA's back in.

![My VA LOA1.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/92c25a1b-5864-4ef8-94f4-91d4be246049)

**Comment by Samara-Strauss** [comment]
Great! Sorry, I should have asked this earlier — can you also create a version that shows this page with some applications in progress? That'll be helpful in communicating to Erik and Sandra that LOA1 users can start (some) applications and save them in progress.

**Comment by tressaellen** [comment]
Sure, no problem! Let me know if you need anything else.

![My VA LOA1 Applications.jpg](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/2e4b4c2a-fe53-44ff-a226-be0b070dd468)

**Comment by Samara-Strauss** [comment]
Great, thank you!
