### ISSUE TITLE
Set default view for components to docs instead of canvas in Storybook 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#18149]
## Issue Description
Set default view for components to docs instead of canvas in Storybook 

---
## Tasks
- [ ] Set default view for components to docs instead of canvas in Storybook 

## Acceptance Criteria
- [ ] When viewing a component in Storybook, the default view is to docs tab

**Comment by cvalarida** [comment]
I see `selectedPanel` is [an option in `manager.js`](https://storybook.js.org/docs/react/configure/features-and-behavior), but I _think_ it's referring to the addons in the bottom pane, not the tab up top. At any rate, I can't get it to change anything because I don't know the panel names. At least I think that's the problem. The documentation is pretty scant.

Closing since it doesn't look like it's possible, unfortunately.

**Comment by bkjohnson** [comment]
:wink:

**Comment by cvalarida** [comment]
:astonished:
