### ISSUE TITLE
Add design.va.gov/BUILD.txt

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#18211]
## Issue Description
Like va.gov/BUILD.txt, this file will be useful for debugging what's currently in production.

## Acceptance Criteria
- [ ] The BUILD.txt is live on design.va.gov/BUILD.txt
- [ ] It includes:
  - [ ] Commit hash
  - [ ] Build time
  - [ ] Build ID or CircleCI job link

**Comment by bkjohnson** [comment]
Some additional details:

- The BUILD.txt file on va.gov [comes from here](https://github.com/department-of-veterans-affairs/content-build/blob/d5dafbdb3d8c4c0f2aa695ea2d54a8ef8e7e8a17/jenkins/common.groovy#L207)
- Our [environment variables in GitHub actions](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) include:
  - `GITHUB_REF`
  - `GITHUB_REF_NAME`
  - `GITHUB_JOB`

It may be easier for us to follow that pattern and creating the BUILD.txt in the `_site/` directory _after_ the jekyll build is finished rather than trying to have jekyll create it for us.
