### ISSUE TITLE
Analytics Implementation for VSP  Contact Center - Medallia

### ISSUE THREAD

**Issue by jwoodman5** [department-of-veterans-affairs/va.gov-team#18278]
# Google Analytics Implementation Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?

  * Google Analytics, Medallia

- Who is this request for?

   * @jwoodman5, @ianMcCullough-ob 
    
    
- What team/project is this work for?
    * Facility Locator Team, Medallia Survey
    
    
- Provide the Domain where Google Analytics needs to be implemented
    * https://va.gov/find-locations (for Feedback survey which executes a modal window)
    
    * No PII is passed
    
- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - Hoping to launch the production pilot on 1/12/21

- Typical Website Interactions to Track

Part 1:
    - User visits https://va.gov/find-locations to find facilities
    - Feedback Survey button is located on right side of page as shown here:
    - <img width="1356" alt="Screen Shot 2021-01-07 at 4 10 12 PM" src="https://user-images.githubusercontent.com/45946766/103959346-4b4d2c80-5104-11eb-971c-38e8970a5212.png">
    - If user chooses to provide feedback and clicks the "Feedback" button, a modal window pops-up with the survey as shown here:
    - <img width="1058" alt="Screen Shot 2021-01-07 at 4 10 32 PM" src="https://user-images.githubusercontent.com/45946766/103959435-87808d00-5104-11eb-80e0-95666633a421.png">
    

- - We want to track the following:

    - _Responses to all questions, matched with the questions that are being asked_
    - _# of users who click the Close button_
    - _# of users who “X” out of the survey_
    - _Page exits_
    - _Time to complete the survey (business logic: start is after the “Feedback” button has been clicked and the survey loads. 
       End is after the “Submit” button is clicked. Each question answer is a step in the funnel.)_
    - _# of users who click the Feedback button_
    - _# of users who submit the Feedback form_

Part 2:
    - User visits https://va.gov 
    - User is "intercepted" with this modal survey on any interior page (5% of users get intercepted)
    - <img width="1058" alt="Screen Shot 2021-01-08 at 10 55 04 AM" src="https://user-images.githubusercontent.com/45946766/104053514-3f16ad00-51a0-11eb-920f-624734e9c0e5.png">
    - 

- On this page/modal, we'd want to track:

    - _# of Users who 'X' out of the survey_
    - _# of Users who click 'Not right now'_
    - _# of Users who click 'Provide Feedback'_
    - _Page exits_
   
- _When a user selects 'Provide Feedback', they are presented with the survey shown here:
    - <img width="1058" alt="Screen Shot 2021-01-08 at 10 55 32 AM" src="https://user-images.githubusercontent.com/45946766/104054149-6a4dcc00-51a1-11eb-89fc-144fe18d6cb7.png">
   
- _On this page/modal, we'd want to track:
    
    - _Time to complete the survey (business logic: start is after the “Provide feedback” button has been clicked and the survey loads. End is after the “Submit” button is clicked. Each question answer is a step in the funnel.)_
    - _Scroll depth_
    - _# of users who click an answer on the survey and still exit (who click “close” or “X”)_
    - _# of Users who 'X' out of the survey_
    - _# of Users who click 'Close'_
    - _# of Users who click 'Submit'_
    - _Page exits_

- Additional Comments

    - This analytics request is specific to the new Medallia Feedback form on the https://va.gov/find-locations page. Tracking for anything else on the page/site should _not_ be changed.

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @jwoodman5 , 

Thank you very much for your request here. We think this would be a great opportunity for @ianMcCullough-ob to join us in the GTM implementation effort here. 

Just before the turn of the year I spoke with our Medallia rep Sarkis who informed us of Medallia's capability to push various survey engagement data to the data layer for the capability of being collected via GTM/GA.

I believe the first step here would be to reconnect with him to enable those events to push to the data layer. 

He also provided us the instructions to ultimately do this GTM configuration: 
- [Medallia Digital - Google Analytics Integration.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5788998/Medallia.Digital.-.Google.Analytics.Integration.pdf)
- [Medallia Digital - Google Analytics Integration - Creating variables.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5788999/Medallia.Digital.-.Google.Analytics.Integration.-.Creating.variables.pdf)
- [Medallia Digital - Google Analytics Integration - Creating triggers.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5789000/Medallia.Digital.-.Google.Analytics.Integration.-.Creating.triggers.pdf)
- [Medallia Digital - Google Analytics Integration - Creating tags.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5789001/Medallia.Digital.-.Google.Analytics.Integration.-.Creating.tags.pdf)

@bsmartin-ep and @ianMcCullough-ob perhaps one of you can take the implementation and the other QA? We may need to do some custom work here for those areas we would like to track that are not enabled by Medallia's events. 

We look forward to working with you and your team here. 

cc: @joanneesteban for visibility
.

**Comment by jwoodman5** [comment]
Hey Jon,

That's a great thought and great timing. Thanks for reaching out to connect
us on this. @Ian McCullough <ian.mccullough@oddball.io> Happy to chat
through this on Monday. Have a great weekend, everyone!

*Jason Woodman*
Product Manager | VSP Contact Center Team
240-506-2768
*Oddball.io <http://oddball.io/> *| A strangely human digital agency

**Comment by joanneesteban** [comment]
@ianMcCullough-ob - Hi! You should have all the access and instructions here to populate the events. Would you be able to speak with Sarkis about getting this through on the Medallia side?

**Comment by ianMcCullough-ob** [comment]
> @ianMcCullough-ob - Hi! You should have all the access and instructions here to populate the events. Would you be able to speak with Sarkis about getting this through on the Medallia side?

@joanneesteban sure! I can do that.

@jonwehausen, should I create a new Workspace in GTM with this ticket number and name?

**Comment by jonwehausen** [comment]
Hi @ianMcCullough-ob , 

Yes that would be great -- feel free to start on the GTM configuration at your earliest convenience. 

A couple other things here: 
- May you provide a status update on Sarkis being able to turn on those data layer events? 
- Also, I believe the majority of key items you all are looking to track you documented in the ticket are in-fact captured in the events [here](https://github.com/department-of-veterans-affairs/va.gov-team/files/5788998/Medallia.Digital.-.Google.Analytics.Integration.pdf), but would you mind taking a look and determining if there is any custom data layer work we will need to do here outside of the out-of-box medallia events? 

Thanks so much here, 
Jon

**Comment by ianMcCullough-ob** [comment]
@jonwehausen

There are some issues with the data layer events being turned on. Here's what Sarkis said:
> Unfortunately I just confirmed that GovClound does not support GTM due to security risks (its from the VA side) 
>

> It seems that the workaround they can provide is via manual setup (this mainly is used for third party integrations, for those that don’t use google). One of the drawbacks is having limited stats or variables to capture. Please review the documentation around Custom Event Listeners: [Medallia Digital Custom Events Integration Guide.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/5867261/Medallia.Digital.Custom.Events.Integration.Guide.pdf)
>

> I have already asked Medallia to turn this capability ON for our instance so that we have access to them, they are actively working on this.
>

> Additionally, Medallia does have a product update release on the road-map that will eventually capture these details/stats and more, automatically without the need of any setup (ie GTM, Custom Event Listeners, etc.) ... the product is called Cooladata. It will however take a bit longer for us to get this release (since we are in GovCloud).
> 

I'm not sure of the next steps, if you have any thoughts let me know. Thanks!

cc @jwoodman5

**Comment by jonwehausen** [comment]
## Update 1/25/2021

@ianMcCullough-ob Following Sarkis news that the pre-requisites identified below have been implemented, I began testing this with a custom HTML tag here: https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000446?orgId=oXPY3GFFQwaHnjNHpFLyFg

![image](https://user-images.githubusercontent.com/48527022/105769129-55a45e80-5f2b-11eb-96ca-302583625cba.png)

### Items to note
- I was able to modify the custom code to begin pushing some relevant metadata to the data layer. You can see this on lines 33-39
- One piece we are missing at this point is the actual survey data the user submitted -- my first hunch is perhaps `eventIncludeFeedbackContent` was not enabled
   - When trying to output the `content` of the form, Medallia is returning `undefined` 
![image](https://user-images.githubusercontent.com/48527022/105769720-3d810f00-5f2c-11eb-9bd4-c42328caf354.png)


### Next Steps 
1) @ianMcCullough-ob would you mind confirming with Sarkis if in fact all of the prerequisites listeners were turned on, and if they in fact were, any guidance he could provide as to why we're not seeing any actual survey data
2) Could you begin staging the tagging configuration? We traditionally like to pass the actual event name (i.e "FormSubmit" in this case) as the Event Label and pass more content in the "Event Action". We'll surely want to capture the actual survey data when we have the `undefined` issue outlined above resolved. 
3) Lastly, could you work with a FE developer to get the event listener code currently in the GTM workspace deployed on the site itself, so we're not needing to load the code through a custom HTML tag

Thanks and let me know any questions you have here. 

cc: @joanneesteban for visibility

**Comment by jonwehausen** [comment]
Hi @ianMcCullough-ob ,

Medallia GTM configuration is ready for your QA - please see [this workspace](https://tagmanager.google.com/?pli=1#/container/accounts/144676348/containers/2214120/workspaces/1000446)

### Context
- Since last unit testing (last comment), it seems we now have access to some content metadata we can pull in 🎉  -- _still not sure why we weren't before_
- The Medallia event names / taxonomy have been modified to align similarly to our form events -- you can see these event names on lines 43 - 71 [here - "cHTML - Medallia - With Datalayer"](https://tagmanager.google.com/?pli=1#/container/accounts/144676348/containers/2214120/workspaces/1000446/tags/1422)
- This workspace will support both the current medallia surveys 


### QA Tasks
 Please test the following: 
- [ ] GTM Tag Event Taxonomy: 
    - _Event Category_: "Interactions" or "Transactions" -- "transactions" only for `--submission-successful` event (when thank you page displays)
    - _Event Action_: "Forms - Medallia" -- will remain consistent
    - _Event Label_: _the event name from the data layer_ - per changes identified in the context section above
- [ ] Custom Metric value of the feedback submission value is collected in index `46`
- [ ] Custom Dimension value of the `feedbackUUID` is collected in index `121`
- [ ] Custom Dimension value of survey ID is collected in index `122`
- [ ] Please test on both active Medallia forms

### Logistics
- It would be great to have the code contained within `cHTML - Medallia - With Datalayer` deployed on the FE rather than injected via GTM if possible 

cc: @joanneesteban & @JasonTheBearded for visibility

**Comment by ianMcCullough-ob** [comment]
Hey @jonwehausen here's what all I've been able to test, and so far so good. I have a few questions highlighted below. There are a few items I haven't been able to test due to form limitations (next-click and back-click).

** Note: Form ID 11 is intercept survey, form ID 6 is the feedback survey. **

| Tag Values                                                   | Status |
| ------------------------------------------------------------ | ------ |
| <img width="506" alt="Screen Shot 2021-01-29 at 3 49 15 PM" src="https://user-images.githubusercontent.com/73119703/106326570-b6dd7200-624a-11eb-9533-e4766134a858.png"> |        |
| <img width="502" alt="Screen Shot 2021-01-29 at 3 40 06 PM" src="https://user-images.githubusercontent.com/73119703/106326574-b80e9f00-624a-11eb-8fc0-50882ae58749.png"> |        |
| <img width="800" alt="Screen Shot 2021-01-29 at 3 39 58 PM" src="https://user-images.githubusercontent.com/73119703/106326576-b80e9f00-624a-11eb-8f8a-7e8c2dcfd1e6.png"> |        |
| <img width="507" alt="Screen Shot 2021-01-29 at 3 37 32 PM" src="https://user-images.githubusercontent.com/73119703/106326577-b8a73580-624a-11eb-8f1a-6c292e993b51.png"> |        |
| <img width="800" alt="Screen Shot 2021-01-29 at 3 31 50 PM" src="https://user-images.githubusercontent.com/73119703/106326580-b8a73580-624a-11eb-8525-f9b5f8521115.png"> |        |
| <img width="800" alt="Screen Shot 2021-01-29 at 3 31 15 PM" src="https://user-images.githubusercontent.com/73119703/106326582-b93fcc00-624a-11eb-9b53-31db2059ecae.png"> |        |
| <img width="798" alt="Screen Shot 2021-01-29 at 3 30 11 PM" src="https://user-images.githubusercontent.com/73119703/106326583-b93fcc00-624a-11eb-93c8-d2b782444fa9.png"> |***Does it matter that some IDs are wrapped in single quotes and others aren't?***       |
| <img width="799" alt="Screen Shot 2021-01-29 at 3 28 41 PM" src="https://user-images.githubusercontent.com/73119703/106326585-b93fcc00-624a-11eb-95ff-3e6936a46712.png"> |        |
| <img width="800" alt="Screen Shot 2021-01-29 at 3 27 25 PM" src="https://user-images.githubusercontent.com/73119703/106326587-b9d86280-624a-11eb-8e47-439f8b7da9cf.png"> |        |
| <img width="800" alt="Screen Shot 2021-01-29 at 3 25 44 PM" src="https://user-images.githubusercontent.com/73119703/106326589-b9d86280-624a-11eb-885e-fa978304f411.png"> |        |
| <img width="811" alt="Screen Shot 2021-01-29 at 3 24 17 PM" src="https://user-images.githubusercontent.com/73119703/106326590-b9d86280-624a-11eb-8e5d-2b6b65d36abd.png"> |        |
| <img width="558" alt="Screen Shot 2021-01-29 at 3 23 30 PM" src="https://user-images.githubusercontent.com/73119703/106326591-ba70f900-624a-11eb-980e-aa9c770e5f9a.png"> |        |
| <img width="578" alt="Screen Shot 2021-01-29 at 3 22 49 PM" src="https://user-images.githubusercontent.com/73119703/106326592-ba70f900-624a-11eb-8d9c-74dfe3ffaa0e.png"> |        |
| <img width="504" alt="Screen Shot 2021-01-29 at 3 22 22 PM" src="https://user-images.githubusercontent.com/73119703/106326593-ba70f900-624a-11eb-8dd3-4aabc417f9ec.png"> |        |

| **Form Submission Data Layer**                               | Status                                     |
| ------------------------------------------------------------ | ------------------------------------------ |
| <img width="536" alt="Screen Shot 2021-01-29 at 3 55 46 PM" src="https://user-images.githubusercontent.com/73119703/106327115-96fa7e00-624b-11eb-99e5-8447fc11b485.png"> | Tested with other values, all worked.      |
| <img width="483" alt="Screen Shot 2021-01-29 at 3 52 30 PM" src="https://user-images.githubusercontent.com/73119703/106327118-982bab00-624b-11eb-8b03-472894b58cae.png"> | ***Should anything populate in content?*** |

Regarding adding this code directly to the page rather than injecting via GTM, @jwoodman5 is in contact with some FE people who are working on 508 fixes at the moment, can likely address after.

**Comment by jonwehausen** [comment]
Hey @ianMcCullough-ob ,

Thank you for your testing and great questions here, to follow-up on them: 

- No it doesn't matter than some for ID's populate with quotes and others not, all will eventually live in GA/BQ as strings anyhow 😄 
- Thanks for calling out the `content` variable on the VHA survey -- It looks like  we're not able to collect the content for this survey type through the event listener. According to the documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/files/5788998/Medallia.Digital.-.Google.Analytics.Integration.pdf), it looks like only the feedback survey types have `content` available. 
![image](https://user-images.githubusercontent.com/48527022/106519524-69127500-64a9-11eb-8b20-d5bcdd48f8ba.png)
  - This is a case where we need to leverage our Medallia > BigQuery export joined with our `feedbackUUID` to capture what values were submitted....cc: @JasonTheBearded

**Comment by jonwehausen** [comment]
@ianMcCullough-ob Do you have any update on if a developer is available to transfer the custom HTML code to the FE? Thanks so much in advance

**Comment by ianMcCullough-ob** [comment]
@jonwehausen thanks for the clarification on the content issue. In that case, everything looks good.

Also, I touch base with @jwoodman5 on the FE resource today.

**Comment by jonwehausen** [comment]
### Update
- Closing this ticket, new ticket will be opened to verify when FE javascript is added to site
- GTM tracking has been completed + validated


cc: @joanneesteban @jwoodman5 @ianMcCullough-ob

**Comment by ianMcCullough-ob** [comment]
@jonwehausen here are some screenshots from testing modernized staging. I tested feedback survey on [Find VA Locations](https://staging.va.gov/find-locations) and the intercept at [West Los Angeles VA Medical Center](https://staging.va.gov/find-locations/facility/vha_691)

​​	

| Tag Tested                                    | Tag Values                                                   | Status |
| --------------------------------------------- | ------------------------------------------------------------ | ------ |
| Intercept:<br />survey-submit-close           | ![intercept--survey-submit-close](https://user-images.githubusercontent.com/73119703/109337913-8251db80-7833-11eb-850a-675a6f29169d.png) | Pass   |
| Intercept:<br />survey--submission-successful | ![intercept--survey-submission-successful](https://user-images.githubusercontent.com/73119703/109337915-82ea7200-7833-11eb-9420-503179195f85.png) | Pass   |
| Intercept:<br />survey--submission            | ![intercept--survey-submission](https://user-images.githubusercontent.com/73119703/109337918-82ea7200-7833-11eb-9c42-1171490b3a45.png) | Pass   |
| Intercept:<br />survey-no-submit-close        | ![intercept--survey-no-submit-close](https://user-images.githubusercontent.com/73119703/109337921-83830880-7833-11eb-9da7-dad46a09660e.png) | Pass   |
| Intercept:<br />survey-start-form             | ![intercept--survey-start-form](https://user-images.githubusercontent.com/73119703/109337922-83830880-7833-11eb-98be-69586a5c663d.png) | Pass   |
| Intercept:<br />survey-invitation-accept      | ![intercept--survey-invitation-accept](https://user-images.githubusercontent.com/73119703/109337923-83830880-7833-11eb-9758-51edc981073e.png) | Pass   |
| Intercept:<br />survey-invitation-decline     | ![intercept--survey-invitation-decline](https://user-images.githubusercontent.com/73119703/109337924-841b9f00-7833-11eb-8bb0-01a005760fc2.png) | Pass   |
| Intercept:<br />survey-invitation-display     | ![intercept--survey-invitation-display](https://user-images.githubusercontent.com/73119703/109337925-841b9f00-7833-11eb-8bcf-b3dcd40c8c4e.png) | Pass   |
| Intercept:<br />survey-submit-close           | ![feedback--survey-sumbit-close](https://user-images.githubusercontent.com/73119703/109337928-84b43580-7833-11eb-85a0-4178e48338ae.png) | Pass   |
| Feedback:<br />survey--submission-successful  | ![feedback--survey--submission-successful](https://user-images.githubusercontent.com/73119703/109337929-84b43580-7833-11eb-8619-ca3aa116a529.png) | Pass   |
| Feedback:<br />survey--submission             | ![feedback--survey--submission](https://user-images.githubusercontent.com/73119703/109337930-84b43580-7833-11eb-87aa-68df5de5a9d0.png) | Pass   |
| Feedback:<br />survey-no-submit-close         | ![feedback--survey-no-submit-close](https://user-images.githubusercontent.com/73119703/109337932-84b43580-7833-11eb-9a6c-9f8311163a82.png) | Pass   |
| Feedback:<br />survey-start-form              | ![feedback--survey-start-form](https://user-images.githubusercontent.com/73119703/109337933-854ccc00-7833-11eb-990e-5b163ff19697.png) | Pass   |
| Feedback:<br />survey-button-click            | ![feedback--survey-button-click](https://user-images.githubusercontent.com/73119703/109337934-854ccc00-7833-11eb-8222-7364d6feadc8.png) | Pass   |

| Form Submission Data Layer                                   | Status |
| ------------------------------------------------------------ | ------ |
| ![feedback--survey-submit-dl](https://user-images.githubusercontent.com/73119703/109338573-71559a00-7834-11eb-832e-70f50f462488.png) | Pass   |
| ![intercept--survey-submit-dl](https://user-images.githubusercontent.com/73119703/109338555-6c90e600-7834-11eb-9cb0-8484a7da82ec.png) | Pass   |
