### ISSUE TITLE
Analytics Reporting Request for VA Forms for VSA Global UX 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#1828]
# Metrics Reporting Request

## Instructions

Please fill out the following sections:
- [X] Description:
- [X] Timeframe for Analytics Requested
- [X] Analytics to Track Down
- [X] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for?

- [Jennifer Lee]
- [Kara Kemahli]
    _Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
- What team/project is this work for?  
    _this adds context for the data_
    - [VSA Global UX )
    

## Timeframe for Analytics Requested
_September 25, 2019._

## Analytics to Track Down
>  [ ] Page Views for these pages:
https://www.va.gov/vaforms/
https://www.va.gov/vaforms/search_action.asp
https://www.va.gov/viewer.htm -
https://www.va.gov/vaforms/help.asp –
https://www.va.gov/vaforms/contact.asp-va.gov

Plus these pages that are also on the forms page (at the bottom): 
Request for DD 214 or other Military Records NARA SF 180 
https://www.archives.gov/veterans/military-service-records/standard-form-180.html
GSA Library of Standard and Optional Forms https://www.gsa.gov/reference/forms
DD Forms Department of Defense Forms Program https://www.esd.whs.mil/Directives/forms/
SGLI/VGLI Insurance Forms (including SGLV8286) https://www.benefits.va.gov/INSURANCE/resources-forms.asp

## Which Product Questions are you trying to answer?
For the Redesign of VA forms page, we need to know how many page visits there are to these pages so that we can take into account the top page visits to improve on-site search, general search results, and help us as we go to create search landing page templates. 

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._
EDITED/ADDED: Many of the ^ listed pages are not federally required; we want to know how often people go to these pages, so we can retire them and/or omit them from the redesigned forms search experience if appropriate. 

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jenniferlee-dsva** [comment]
Minor edit - these are pages, not forms. Also added clarifying comment, under Additional Comments.

**Comment by nedierecel** [comment]
@jenniferlee-dsva - This issue is cross-posted with #1637. Please see a [link to the report](https://analytics.google.com/analytics/web/?authuser=0#/analysis/a50123418w177519031p176188361/edit/8-kxQse4QCS3fyG8N0v98g) with 3 tabs:

_Timeframe: 2019 year-to-date_
1. Top 100 VA Forms pages ranked by pageview
2. Top 100 VA Forms Detail Pages ranked by pageview
3. Top Landing pages by organic traffic

**How to Navigate to this Page Using the Menus**
You can also access this by visiting the `VA.gov - Production Property>All VA.gov Website Data [Production] view`. From here, visit this icon on the left menu:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/82bc857f-1eea-4ba7-bc87-34e5e7e7ad36)

Then, click on a report that says `VSA Global UX - Legacy Form Analysis` .

**Comment by jenniferlee-dsva** [comment]
Hi @nedierecel - Thank you! Is there a way to expand the column that includes the URL info? 

Example:
![image](https://user-images.githubusercontent.com/43381063/65557254-9be54a00-df00-11e9-953d-531c720c6c95.png)

**Comment by jenniferlee-dsva** [comment]
P.S. This is truly awesome.

**Comment by nedierecel** [comment]
@jenniferlee-dsva Happy to help! Yes, that is a little frustrating that we can't drag the column widths like you would with GSheets or Excel. 

Speaking of Excel, there is a handy feature to download the data if that's a little more helpful for you:

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/8bbd6265-f9a1-42e2-b953-ade993c6ddd0)

**Comment by jenniferlee-dsva** [comment]
@nedierecel - I'm now getting a message that I don't have permission to view, even though I am signed in.

**Comment by nedierecel** [comment]
@jenniferlee-dsva Confirming I see this and will check out what's going on.

**Comment by nedierecel** [comment]
@jenniferlee-dsva It looks like the report is operating again, but please let me know if you are running into the issue. I wanted to also call out another item within the report. Because of the timeframe and filters we've applied, the data here is sampled: 

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/b6be0734-6b5f-4fe5-bd0a-d4ce00dc4ee8)

This should still be a good representative of performance across these pages. Thank you!

**Comment by Karak888** [comment]
@nedie I haven't been in yet but doing that today, but this is awesome info and I am excited to go through it.  Thanks!

**Comment by jenniferlee-dsva** [comment]
It is still giving me denied message

**Comment by jenniferlee-dsva** [comment]
Before permissions got blocked, I was able to download 2 of the reports as CSV docs. 

Since I'm still locked out, @nedierecel would you mind posting here or Slacking me the CSV export of the one I didn't get to download? I still need the one of the ^ listed page URLs associated with forms search: 

[ ] Page Views for these pages:
https://www.va.gov/vaforms/
https://www.va.gov/vaforms/search_action.asp
https://www.va.gov/viewer.htm -
https://www.va.gov/vaforms/help.asp –
https://www.va.gov/vaforms/contact.asp-va.gov

Request for DD 214 or other Military Records NARA SF 180
https://www.archives.gov/veterans/military-service-records/standard-form-180.html
GSA Library of Standard and Optional Forms https://www.gsa.gov/reference/forms
DD Forms Department of Defense Forms Program https://www.esd.whs.mil/Directives/forms/
SGLI/VGLI Insurance Forms (including SGLV8286) https://www.benefits.va.gov/INSURANCE/resources-forms.asp

**Comment by nedierecel** [comment]
@jenniferlee-dsva Please see the Excel document broken out by the top 5 pages. the `/search_action.asp` page includes the different iterations of forms and search.

For these pages, we'll have to get these from DAP:
- https://www.archives.gov/veterans/military-service-records/standard-form-180.html
- https://www.gsa.gov/reference/forms
- https://www.esd.whs.mil/Directives/forms/

[SGLI Insurance Forms](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p176188361/explorer-table.filter=www.benefits.va.gov~2FINSURANCE~2Fresources-forms.asp&explorer-table.plotKeys=%5B%5D/) - 36,134 Pageviews (Timeline: 01/01/2019-09/29/2019)

**Comment by jenniferlee-dsva** [comment]
Hi @nedierecel - I didn't see the Excel spreadsheet per your message. (Also, it looks like I am able to get into the 3-tabbed report dashboard now, but can't see or download anything bc it doesn't stop loading.)

**Comment by jenniferlee-dsva** [comment]
Nvmd - I'm in. Just took a few minutes!

**Comment by jenniferlee-dsva** [comment]
Hmm - @nedierecel can we try to connect tomorrow? I was able to download a CSV export for the pages, but want to make sure I'm ignoring irrelevant items or looking at this right. It looks like there are a ton of variations on the /search_action.asp URLs as well as random form URLs too, unless I'm reading this wrong and they're variations of same page... ?

For this particular report, I needed to see data only for these pages:
[ ] Page Views for these pages:
https://www.va.gov/vaforms/
https://www.va.gov/vaforms/search_action.asp
https://www.va.gov/viewer.htm -
https://www.va.gov/vaforms/help.asp –
https://www.va.gov/vaforms/contact.asp-va.gov

[Plus those other URLs that you said we have to get from DAP only. The DAP team sent me to GA, so a little bit loopy.]

**Comment by nedierecel** [comment]
@jenniferlee-dsva Apologies - the file was too large to send via Git, and I didn't realize it was blocked from uploading. 

To answer your question, there are multiple iterations for `/search_action.asp` as it is capturing the search query parameters used. For example, this link below indicates that users are looking for form 2850, since the `FormNo=` parameter includes that number in the URL. 

`https://www.va.gov/vaforms/search_action.asp?FormNo=2850&tkey=&Action=Search`

This can give you insight into the most popular forms searched since it is bringing over the form numbers into the URLs. This appears to be a healthcare professional form, but the highest veteran-facing form looks to be: 

https://www.va.gov/vaforms/search_action.asp?formno=21-4138&tkey=&action=search

I'll send you a Slack with times today, as I have a few meeting blocks.

**Comment by nedierecel** [comment]
@jenniferlee-dsva @lwalsh617 @artsymartha68 The file was too large to send over Git, so I will send over Slack. I am attaching an updated version of Jennifer's original request that filters out activity from employees coming from a VA Network Domain. 

**For Visibility:**
- Data Sources for 01/01/2019-10/11/2019: 
    - [Unsampled data from Top 5000 VA Forms URLs in Google Analytics](https://analytics.google.com/analytics/web/?authuser=0#/opusreport/7Ak6JH_nQ_GvQ0XrUFd-qQ/a50123418w177519031p176188361/_u.date00=20190101&_u.date01=20191011&_u.date10=&_u.date11=&_u.dateOption=&_r.dsa=1&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22www.va.gov~2Fvaforms.*%7Cwww.va.gov~2Fviewer.*%22,0%5D%5D&explorer-table.plotKeys=%5B%5D&_.useg=userFE7rdQFXQN2gqBbodJbZcw/)
    - [Unsampled data from Top VA Forms Organic Landing Page URLs in Google Analytics](https://analytics.google.com/analytics/web/?authuser=0#/opusreport/ysQ_6uGhReWOaAoRVDVdNg/a50123418w177519031p176188361/_u.date00=20190101&_u.date01=20191011&_u.date10=&_u.date11=&_u.dateOption=/)
- Other ISPs used - If a VA facility uses another network domain for their ISP and not the VA Network Domain, their activity might still be included here; we would need further discovery on what these domains might be.
- VA Forms Top-Level - This includes `www.va.gov/vaforms/` and `www.va.gov/vaforms/default.asp`. The latter URL with default.asp also renders the same user experience, but you can use the extra URL parameters to see (a) how deep users were paginating in the `currentpage` parameter and/or (b) how they were sorting the page by the `orderby` parameter.
- VA Forms Organic Landing Pages - When using this Google Analytics data, you'll see the metric of sessions instead of pageviews. This is intentional, since this is the start of sessions that came from Organic sources (and still excludes VA Internal Activity).

**Comment by nedierecel** [comment]
10/14/2019 - Provided XLS file via Slack; follow-up issue in #2182 will track PDF downloads
