### ISSUE TITLE
[Frontend] Switch veteran home address and veteran mailing address on the schema

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18327]
As a user with a saved-in-progress healthcare application
I want to be able to complete the form that I started
With proper labels for the address fields
So that I don't run into any validation errors. 

Includes carryover from: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15159

- [ ] merge [vets-json-schema PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/559)
- [ ] update `vets-website` to reference `master` branch of `vets-json` (also updates RI to use BE changes)
- [ ] test/QA in RI
- [ ] merge [vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15511)
- [ ] stakeholder review in Staging
- [ ] flip feature flag in Prod

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15511) for this ticket

**Comment by LinnJS** [comment]
[vets-website PR](https://github.com/department-of-veterans-affairs/vets-website/pull/15511)

[vets-json-schema PR](https://github.com/department-of-veterans-affairs/vets-json-schema/pull/559)

**Comment by kevinmirc** [comment]
Summary of yesterday's testing @jonathanjnelson and I did on this review instance 

**Test 1** ✅ 
as
- unauthenticated user
with
- feature toggle off
it
- worked as expected

**Test 2** ✅ 
as
- unauthenticated user
with
- feature toggle on
it
- worked as expected

**Test 3** ❌ 
as
- authenticated user (i don’t remember which user)
with
- an existing save in progress
- a home address in profile
- a mailing address in profile
it
- only asked one address as expected (since it was a SiP)
when
- starting a new 10-10ez (and discarding the SiP)
it
- ⚠️ Never asked for a second address
- ⚠️ The mailing address was populated with the “Home” address on Profile

Test 4 ❌  
as
- authenticated user 376
with
- a mailing address in profile
- a home address in profile
it
- ⚠️ populates the form’s Mailing Address with the profile’s Home Address
- ⚠️ populates the form’s Home Address with the profile’s Mailing Address
