### ISSUE TITLE
Change how we handle users who are blocked from Direct Deposit for Comp and Pen (DD4CNP)

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#18321]
Currently if the DD4CNP endpoint flags a user has being deceased, incompetent, or having a fiduciary, we:
- do not allow them to access the Direct Deposit section of the Profile at all
- show an alert on the top of the Personal Information page explaining that they do not have access to their bank info

Moving forward we should no longer block the Direct Deposit section. Instead, if they are blocked from DD4CNP:
- on the Direct Deposit page they will see the "cannot access bank info" alert in place of the CNP bank info.
- show the EDU section of Direct Deposit like normal

**Comment by erikphansen** [comment]
We might not change this behavior at all and continue to block users from the entire Direct Deposit section if they are "flagged" by the DD4CNP section. Based on emails around Jan 7 2021, Shay and Luke seem happy with the current approach.

**Comment by erikphansen** [comment]
@Samara-Strauss just for your awareness, this ticket exists now.

**Comment by Samara-Strauss** [comment]
@erikphansen I thought our final decision via Slack was that we were *not* going to change this behavior because the use case that someone will need to edit DD for edu but has a fiduciary/is incompetent/is deceased based on DD for comp & pen flags is highly unlikely, so we can just continue to prioritize the DD for comp & pen flags and block the whole section as we are now if we detect that someone has a fiduciary/is incompetent/is deceased.

So, I think we can close this with no further action.
