### ISSUE TITLE
IA Request VAMC-upgrade team, Secure URL for va.gov/Erie-health-care 

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18332]
## Story
In order to complete testing and final check off/punch list of VAMC-websites, they must go into Dual-state publishing.  VAMC-upgrade team is asking that IA confirm that URL for this system is ready to be put in use for Dual-State.

## Request:
Provide validation of URL and guidance in order to publish va.gov/erie-health-care  VAMC website into Dual-state to begin final 508 testing, and PAO training and review prior to Go Live.

## Required Inputs:
- Link to product outline ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md))
- Link to or attach prototype or mockups
- Research - N/A

- This has already been reviewed and updated.  Final out prior to Dual-state can be found here:  http://eriehealthcare.web.demo.ci.cms.va.gov/erie-health-care/
- 
## Information Architecture Worksheet (Optional)
N/A

## Definition of Done
- [x] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by shiragoodman** [comment]
hi @SgardnerPMP  - The Collaboration Cycle IA Request is intended to validate the full information architecture of a product/feature. A review would typically include a review of all pages, all navigation components, and all entry points. It appears that your request is solely for VSP to approve the url of 1 page. Our recommendation would be that you provide information for a full IA review. We need to see the IA within context in order to do a proper review.

**Comment by mnorthuis** [comment]
No response from team received, site launched without IA review. Closing issue.
