### ISSUE TITLE
General Analytics Request for [Matt Shea] - [Profile 2.0: Avg Session time update] 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18363]
# Metrics Reporting Request

## Description
Who is this request for?
- Matt Shea: Authenticated Experience team: Profile 2.0 DOMO data update/fix

##  What type of analytics/metrics support are you looking for?
 Improvement to existing KPI on an existing Profile 2.0 dashboard
[Profile 2.0 Domo](https://va-gov.domo.com/page/492918243)

- Average session time seems off

- We would like to remove the irrelevant pages to give a more accurate representation of "Avg session time". 
    
[GA analytics dashboard](https://analytics.google.com/analytics/web/#/report/content-drilldown/a50123418w177519031p184624291/_u.date00=20210104&_u.date01=20210110&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePathLevel1:~2Fprofile~2F/)

## Important Considerations
- There are page paths that existed on profile 2.0 that dont exist on profile 2.0
- I think we should not include "/" on profile 2.0 since it redirects to personal-contact info, but keep it for the time period before Oct, 2020.

Profile 1 (pre Oct 1st, 2020)
![profile 1.0 (pre-Oct 2020).png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/f8e91eb6-000a-4c52-915b-07e9191544ee)

Profile 2.0 (post Oct 1st, 2020)
![profile 2.0 (post Oct 2020).png](https://images.zenhubusercontent.com/5e41b49969d880e9f4f122b1/808a21f7-9b0f-493e-871f-785c0c247df3)

## Timeframe for Analytics Requested
- As soon as possible

## Which Product Questions are you trying to answer?
Has the average session time decreased since launching profile 2.0 in October 2020?
(if avg session time has decreased, users are finding things faster)

Send Slack message to DSVA Slack Channel, `#VFS-Platform-Support`, that includes: email address(es) for user(s) requesting data and link to this Github issue._
   

> Please leave the following blank
## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by bmcgrady-ep** [comment]
@mshea0606 - I updated the dataset to exclude the profile pages with a low average time on page (< 3 seconds). [Here](https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20200805&_u.date01=20210114&explorer-table.advFilter=%5B%5B0,%22analytics.pagePath%22,%22RE%22,%22%5Ewww.va.gov~2Fprofile%22,0%5D,%5B0,%22analytics.pagePath%22,%22RE%22,%22%5Ewww.va.gov~2Fprofile%3Fpostlogin=true$%7C%5Ewww.va.gov~2Fprofile~2F$%7C%5Ewww.va.gov~2Fprofile~2F%3Fpostlogin=true$%22,1%5D%5D&explorer-table.plotKeys=%5B%5D&explorer-graphOptions.primaryConcept=analytics.avgPageDuration&explorer-graphOptions.selected=analytics.nthWeek) is a GA report with the pages excluded as well. I did leave a few of the profile pages that were less than 3 seconds, due to the fact that these pages only had minimal pageviews and would not affect the overall time on profile number.

Let me know if you have any more questions.

**Comment by bmcgrady-ep** [comment]
@JasonTheBearded - When you have a chance, can you take a look at the dataset above? Thanks!

**Comment by mshea0606** [comment]
@JasonTheBearded would it be possible to also further segment the data to be 1. Profile page session time as mentioned above. 2.That same session time but only include sessions that contained an interaction (CTA click).

**Comment by JasonTheBearded** [comment]
Thanks @bmcgrady-ep I'll take a look. @mshea0606 I don't foresee any problem with segmenting those numbers out.

**Comment by mshea0606** [comment]
For the average session time, can we narrow the scope to be "average profile session time where there was an interaction (specifically a CTA click like adding/editing/saving/submitting)". We would like to see if users are able to complete tasks faster.

**Comment by JasonTheBearded** [comment]
@mshea0606 would this scope narrowing apply to the first segment or second segment in your above comment?

**Comment by Samara-Strauss** [comment]
We no longer need this. Closing.
