### ISSUE TITLE
Configure Webpack / Cypress Source Maps

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#18452]
## User Story

As a Cypress test author, debugging would be made easier if accurate stack trace line numbers were presented instead of the line numbers from compiled source.

## Expected Behavior

Stack traces present line numbers that match source file line numbers.

## Acceptance Criteria
- [ ] ~~The cost and downside to configuring webpack preprocessor to `inline-source-map` have been documented and discussed~~
- [ ] ~~Webpack preprocessor has been configured to use `inline-source-map`~~

**Comment by ddzz** [comment]
This is a known issue with Cypress itself and not a webpack configuration problem. Cypress displays the correct stack trace line numbers when using `cy:open` (in the browser) not but for `cy:run` (headless). After investigating different solutions to this I discovered that the Cypress development team is currently working on a fix for this problem:

- https://github.com/cypress-io/cypress/issues/7715
- https://github.com/cypress-io/cypress/issues/14484

The second linked issue (#14484) was tagged as `work in progress` yesterday, so it is very likely that this issue will be resolved soon in a new release of Cypress. For that reason we will hold off on trying to implement on own solution and wait for this fix to be released by the Cypress team. Since accurate line numbers are still available when running tests headed (using `cy:open`), documentation will be updated to suggest using `cy:open` when debugging failing tests.

**Comment by ddzz** [comment]
Cypress documentation has been updated to mention debugging approaches: https://github.com/department-of-veterans-affairs/va.gov-team/pull/19697

**Comment by pjhill** [comment]
Platform Cypress documentation has been updated with findings -- done
