### ISSUE TITLE
Research a fix for displaying "On this page"  in  spanish vs English

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#18527]
**Problem:** as a content creator for VA.gov, I would like to have the drupal component for "On this page"  on the Corona FAQ spanish page be displayed in spanish vs english.

**Acceptance Criteria:**

[ ] Identify a short-term solution for this issue
[ ] Identify a longer term approach that can be used on more thgan the Corona FAQs page

**Screenshot:** 
[https://app.zenhub.com/files/133843125/743a8900-54a1-425d-ab91-8d99dccfeb4d/download](https://app.zenhub.com/files/133843125/743a8900-54a1-425d-ab91-8d99dccfeb4d/download)

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - since we didnt have a chance to catch-up live on htis, could you advise what our options are for this issue?

Thanks, Sharon


cc: @DanielleThierryUSDSVA

**Comment by youngfreezyVA** [comment]
hi, in order to implement the short term solution we discussed yesterday, i would need an appropriate spanish translation for "On this page". I didn't want to just google something :) 
please advise @DanielleThierryUSDSVA @SKasimow 

the short term solution would be grabbing the on this page by ID ( `document.getElementById("on-this-page")`) and using this object to toggle the values:

`const faqI18Content = {
  en: {
    linkTitle: 'Read this page in English',
    langToggleLink: '/coronavirus-veteran-frequently-asked-questions',
    onThisPage: 'On this page',
  },
  es: {
    linkTitle: 'Leer esta página en Español',
    langToggleLink: '/coronavirus-veteran-frequently-asked-questions-esp',
    onThisPage: "Spanish Translation of On this Page"
  },
};`

**Comment by SKasimow** [comment]
@DanielleThierryUSDSVA Hi there - can we get the translation for "On this page" we should use so we can get this fix in? TRhanks, Sharon
