### ISSUE TITLE
Yellow Ribbon Search [DISCOVERY] - Search filter/result presentation enhancements

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#18553]
## High Level User Story
As a Veteran, I need to be able to apply filters, search for Yellow Ribbon schools, and easily determine why the same school appears in the results multiple times so I can have confidence in the search results presented to me.

## Goals
- Veterans are able to apply additional search criteria up front to narrow search results
- Veterans who opt not to apply additional filters are able to easily discern why the same school may appear more than once in the search results

## Additional Issues to create related to this Issue
_TBD_
```
- Create research plan
- Recruit for research sessions/Schedule research sessions
- Create conversation guide
- Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- Discovery Synthesis - should be conducted as a team, led by designer.
- Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)
```

## How to configure this issue
- [ ] **Labeled with `discovery` and `research` and `team-name`**

**Comment by laurellawrence** [comment]
A few things we might find useful if we decide to move forward with Yellow Ribbon Enhancements. An extensive research study of the current state of Yellow Ribbon can be found in [Yellow Ribbon MVP Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/a5bf9c37d2e38480507490f59bf69feef2ab8f90/products/public-websites/yellow-ribbon-mvp/research/research-findings.md). 

To recap: In order to complete research more efficiently, users would benefit from being able to input more specific criteria to view schools that participate in Yellow Ribbon. ie: 

- Specific area of study
- More specific with the location (e.g. a specific city or zip code radius)
- Maximum benefit amount
- Benefit available for most students
- Online or in-person only

The GI Comparison Tool is going through a redesign and prototype can be found here: 
https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens

If we proceed with Yellow Ribbon enhancements we should ensure that labels and selections for filtering are consistent with GI. I've provided a quick prototype of what these might look like https://xd.adobe.com/view/64e41973-fe83-4870-8d16-f9c64e078c82-31b7/

**Comment by laurellawrence** [comment]
<img width="838" alt="Screen Shot 2021-01-26 at 12 40 24 PM" src="https://user-images.githubusercontent.com/75386943/105891486-4fb78780-5fd6-11eb-85b0-07ccaef92904.png">

**Comment by johnhashva** [comment]
@laurellawrence and @MarciMcGuireGCIO  this is a great find (though, I'm blushing because this was sitting in plain site for me all this time).   We've booked a session with the YR program leads for next Friday -- I will include you in that session (should have anyway, apologies).  Prior to that meet, let's definitely take time (later this week or early next) to talk through the research findings -- and your comp (we will want to share this with the stakeholders to stimulate response).

**Comment by MarciMcGuireGCIO** [comment]
@laurellawrence am I good to close this?  If we proceed with this work, I'll create a new issue for any mockups you do, user testing, etc.

**Comment by laurellawrence** [comment]
@MarciMcGuireGCIO Yep, we can close for now. Looks like John has a meeting schedule for next Wednesday 2/3 to discuss whether or not we want to move forward with these updates. I just received a message from Amy Knox at Booz Allen and she gave the thumbs up to attend the GI Bill usability testing sessions in early Feb. We may want to table these potential updates on YR until we get a feel for the timeline and scale of the GI Bill redesign.

**Comment by MarciMcGuireGCIO** [comment]
Thank you!

**Comment by sshein** [comment]
FYI Google also conducted a UX review of the GI Bill comparison tool https://dsva.slack.com/archives/C0NGDDXME/p1611760485068600

**Comment by MarciMcGuireGCIO** [comment]
After meeting with Yellow Ribbon stakeholders on 2/3/2021, we learned a little more about the types of searches that are most important to Veterans, but are still compatible with this design:

- **Degree Type**
- **Out of Pocket Expense** (as opposed to funding/benefit amount).  This would be calculated by subtracting the benefit amount from tuition.
- Major (or area of study)
