### ISSUE TITLE
Design Feedback - Asynch Usability Testing Prep - VAOS Homepage Refresh

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#18587]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- This will be nice for veterans to have. I know this was a lot of work, great job!

**Request:**
The Design System team is working to add a new component to the design system and would like to test it on a longer page. Since you all are testing a mobile design that has some long pages, we thought we’d ask if we can work it into your study. It’s a Back to Top component [which can be seen here](https://app.zeplin.io/project/5e29e7ff922d4d961b5bff4d/screen/5fdbda435599ca472d759b4c) (and [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18289) is the Zenhub ticket for it). Would you be able to add this to one of the pages in the VAOS prototype and add a task for it during usability testing? If you’re willing/able to do this, Crystabel [tag in ZH ticket] will be able to provide the necessary assets and context.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Make gray cards more square instead of rounded corners (see Sketch file/ Styles/Cards)
- Make card title h3 (see Sketch file/ Styles/Cards))
- Use hyphens in phones numbers (see [design.va.gov](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers))
- Label email and phone number under contact details. (see Sketch file/ Styles/Cards/Location card for style)
- Remove X from Cancel Express Care Request text
- Use [address block style](https://design.va.gov/components/address-block) when showing addresses
- Add a title to the information callout “Contact this provider…” (see Sketch file/ Styles/Content Presentation for style)
- Bold “Main phone” on Video card
- Make sure chevron changes position on additional info accordion when it is clicked

**Should:**
- There may be some issues with only have a chevron to indicate a card is clickable. If you look at our Sketch file I think a link with text might be better.
- Instead of just using a phone or video icon to alert the user of the appt type, maybe you could add “Appointment type: phone”

**Consider:**
- Consider using labels in [this style](https://design.va.gov/components/labels) for canceled appointments instead of red text

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by outerpress** [comment]
Hi Allison, thanks for the feedback! I'm interested in adding the back to top component as a part of this test, but it looks like I need access to the Zeplin project - can you add me? I'll take a look and let you know if it'll fit.

**Comment by allison0034** [comment]
@CrystabelReiter can you add Peter Russo to the "Back to top" button?

**Comment by outerpress** [comment]
I've made most of the changes, and have some questions/notes about the rest:

> There may be some issues with only have a chevron to indicate a card is clickable. If you look at our Sketch file I think a link with text might be better.

This is definitely a key element of the usability test. On tablet/desktop I'm using a text link because these thumbnail cards spread out a little too far, making it harder to tell that the entire card is clickable.

> * Make gray cards more square instead of rounded corners (see Sketch file/ Styles/Cards)
> * Make card title h3 (see Sketch file/ Styles/Cards))

I added a version showing these changes [here](https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/442619368) - you can arrow left one screen to toggle between the two. There is one modification, I used an h4 instead of an h3 since the months are an h3.

I'm a worried that these changes remove the indication that the entire card is clickable. These thumbnail cards are a bit different than our regular cards in that they're not meant to contain other links or buttons, aside from a CTA to view details. Also, the added visual weight of the headers draws the eye away from the equally important information of time and location/appointment type. Because of this I'd prefer to stick with the current state for the calendar cards (though I will fix the CTA scheduling cards in the top section of the home page, those shouldn't have rounded corners).

> Add a title to the information callout “Contact this provider…”
Made the change [here](https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/441371953), just want to ping @peggygannon on whether "Need to make changes?" makes sense as a header.

> Consider using labels in this style for canceled appointments instead of red text
Thanks for pointing that out! I'm still in the process of updating that, but that should work.

> Instead of just using a phone or video icon to alert the user of the appt type, maybe you could add “Appointment type: phone”
I'd like to leave this one as is, because it the appt type is listed after the icon. But I do think the icon text is a consideration for screen readers.

>Use address block style when showing addresses
I don't have this done just yet, but will be adding it in ASAP.

**Comment by outerpress** [comment]
@allison0034 @CrystabelReiter I added the back to top interaction to [this test page](https://adhoc.invisionapp.com/share/URZV3YHCQFZ#/screens/442619368). Is that how you expect the interaction to work?

I'm doing the pilot for the usability study today at 12pm PT. I'll drop this screen in to see if it'll fit, but I don't think there'll be a problem. Let me know if you have any specific questions about the interaction (other than checking that it makes sense and does what they expect).

**Comment by CrystabelReiter** [comment]
@outerpress With the back to top button, it wouldn't appear until the user is farther down the page like this page in staging: https://staging.va.gov/resources/how-to-change-direct-deposit-information-for-va-education-benefits/

I'm unsure of how to do that with invision though since it looks like here it's just sticky on the entire page.

**Comment by outerpress** [comment]
@CrystabelReiter oh yeah that might be beyond invision's capabilities. I'll see if I can get something to work with scroll/fade animations in Studio. Looking at their support pages there doesn't appear to be a straightforward way to do it, but some folks have posted workarounds.

**Comment by outerpress** [comment]
@CrystabelReiter I'm not able to get the fade-in on scroll working using Studio (it might be possible, I'm just running low on time to figure it out). I'm happy to test without it if you like, but I'm assuming that wouldn't be very helpful since that's a critical part of the interaction.

**Comment by CrystabelReiter** [comment]
@outerpress Totally understandable and thanks for trying to get that fade-in scroll effect. This component has been tested before so it's not necessary to use this component during your usability testing.
