### ISSUE TITLE
Document how to use secrets in vets-api

### ISSUE THREAD

**Issue by erluti** [department-of-veterans-affairs/va.gov-team#18679]
**Status**: Content and IA is working on this. No action on our part yet.

This document haas information on secret keys https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/key-management.md
However it doesn't give any support for a dev trying to add a secret for the first time.

The original document should be in the new confluence documents and we need to add some instructions for a developer adding new keys.

**Comment by gmaciolek** [comment]
As promised in the [steps I outlined in Slack](https://dsva.slack.com/archives/CQHBJ5U06/p1610993890026000?thread_ts=1610978821.021900&cid=CQHBJ5U06), I copied the doc Key management doc to a DRAFTS section in Confluence and left a bunch of comments. 

The comments are all for your consideration, not requirements. 
(Since we're still mostly focused on getting existing docs migrated and filling in documentation gaps, I think you can prioritize your efforts to focus on updating anything inaccurate and filling in any important information that's missing. The comments will still be there when you have time to come back to the doc in the future for further refinements.)

Once you're done reviewing/udpating the doc, tag me here or assign this to me and I'll publish it to the live site.

**Comment by erluti** [comment]
@gmaciolek I left some responses and added a section.  Tag me back if there's more I can do.

**Comment by gmaciolek** [comment]
@erluti there are just a couple more outstanding questions in comments on the doc that I need your help with. Once we resolve those, we can publish it.

**Comment by gmaciolek** [comment]
Update: The Key management doc is 90% complete, but we're putting this on hold for a bit until we can come to an agreement on guidelines and workflow considerations for internal/external documentation. (This doc links to an internal VSP Ops doc.)
Thread for details: https://dsva.slack.com/archives/C01AS05BQ79/p1611606911009100

**Comment by ericboehs** [comment]
@andreahewitt-odd Could you reach out and check on the status of this?

**Comment by andreahewitt-odd** [comment]
@lianilychee @gmaciolek What's the status of this? Still on hold?

**Comment by gmaciolek** [comment]
@ericboehs and @andreahewitt-odd Wow, this issue has been neglected for a while! I'm so sorry that I'm just getting around to responding now.

Eric, here is the [Key management guidelines draft](https://vfs.atlassian.net/l/c/wQkGxczK) for the Platform website. Can you review it? I think it's mostly the same as the GitHub version of the page, but I'm particularly interested in your feedback on the bullets in the SSL Certificates section. Instead of linking to our internal [Obtain VA Signed SSL Certificates for External Backend Connections](https://vfs.atlassian.net/l/c/uqno3k1b) doc, I added a sentence that says "Once you have created an SSL certificate, [contact the Platform Ops team in Slack](https://vfs.atlassian.net/wiki/spaces/SUP/pages/1439138197/Getting+help+from+the+Platform+in+Slack) to to securely store the key."

Did I add that sentence in a logical place? Do you approve this doc for publishing?

Normally, we'd ask you to publish it, but since this page has a weird history, I'm happy to go ahead and publish it for you, if you'd like me to. I can also deprecate [the GitHub version of this page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/key-management.md).

CC: @lianilychee
