### ISSUE TITLE
Analytics Reporting Request for Digitized Modernized Content 

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#1869]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Chris J

- What team/project is this work for?
   Digitized Modernized Content meeting
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._

## Analytics to Track Down
Call Center data

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by clantosswett** [comment]
I put together a few graphs and charts for this request. I am not sure if these will be used because there is a desire to have the reporting to happen on a monthly basis and our numbers might not be consistent across sources for a little while and therefore not terribly useful for reporting and tracking. [https://app.zenhub.com/files/133843125/8a37603c-a4d0-42c1-9b6d-7018790d730d/download](https://app.zenhub.com/files/133843125/8a37603c-a4d0-42c1-9b6d-7018790d730d/download)

**Comment by joanneesteban** [comment]
@clantosswett was the limit for monthly reporting communicated to Chris?/can we close this ticket?

**Comment by clantosswett** [comment]
Yep. I talked with Chris and others about this so we are good to close.
