### ISSUE TITLE
Results from CMS/Staging data comparison for University Drive 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#18700]
## Issue Description
During a comparison between the data found in CMS and displayed on staging for Univerity Drive, the following issues were identified: 

1. On Prod, health service accordions include a link to the campus map. This is not true on Staging. 
   - ** What is the expected behavior?**
 ---
2. Within the Audiology accordion, CMS value for "Walkins accepted" = `Unknown`. On Staging, "Walkins accepted" = `No`. On Prod, "Walkins accepted"  does not appear at all. 
    - ** What is the expected behavior?**
---    
3. Critical care appointment phone label appears on front end without a number. No phone number is specified in CMS and none appears on Prod so Staging is accurate. 
   - A similar scenario occurs within the Patient advocates accordion. CMS indicates to use the general facility phone number but no number follows and only the label is displayed on the front end. 
  - **Should label appear if no phone number is present?** 
  - **Is the facility phone number expected to populate automatically?** 
  
<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/104960748-15286c00-5992-11eb-8d72-fd8be4d72d61.png)
 
</details>

---
4. Within the Intimate partner violence accordion, the Domestic Violence hotline displays the facility address on staging but is "off" in CMS
<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/104962173-1c9d4480-5995-11eb-9b8b-0f80ce2e4efa.png)

![image](https://user-images.githubusercontent.com/55411834/104962248-40f92100-5995-11eb-885a-be5c5515662f.png)

</details>

---
5. For accessibility, phone numbers should be interactive. It is present without link on Prod as well. 
<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/104962437-a4834e80-5995-11eb-8202-8fe180b01757.png)

</details>

---
6. Minority Veterans Program email label has a colon (different than phone label)
   - It is not in the CMS data so I suspect this may be happening on the front end. 
   -  ** What is the expected behavior?**
<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/104962870-94b83a00-5996-11eb-8711-04448d1092f6.png)

![image](https://user-images.githubusercontent.com/55411834/104962901-ab5e9100-5996-11eb-849e-d1a701db4052.png)

</details>

---
7. Nutrition, food, and dietary accordion calls for use of facility phone number which populates in CMS as 000-000-0000. It displays accordingly on Staging. On Production, the phone field is not included at all. 
   -  ** What is the expected behavior?**
  
<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/104963395-a77f3e80-5997-11eb-86a2-48c5490c540b.png)

![image](https://user-images.githubusercontent.com/55411834/104963362-95050500-5997-11eb-9584-1c5c7d1125f9.png)

</details>

---

8. Business question: PTSD accordion has the following (accurate from the data perspective)
   - Referral needed? Yes
   - Walk-ins accepted? Yes
   - ** These seem at odds. What is the expected behavior?**

Editorial experience question: List of pages shows "PTSD treatment - Pittsburgh VA Medical Center - University Drive
- Inside that service, the VHA health service name and description is `PTSD care`

---
9. Second empty location component seems to have been added for Recreation and creative arts therapy accordion. Renders correctly on Staging based on data but I don't think it should be there. It does not exist on Prod

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/104964961-cf23d600-599a-11eb-8c6b-a3c6810a35a7.png)

![image](https://user-images.githubusercontent.com/55411834/104964860-8f5cee80-599a-11eb-9bc1-cf69a2874785.png)

</details>

---
10. The Registry exams accordion uses the facility hours, making the service available hours 24/7. It renders correctly in Staging based on the data but is this correct? 
      The email contact is labeled with the person's name (rather than title) and uses a colon. 
    - ** What is the expected behavior?**

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/104965473-0b0b6b00-599c-11eb-8c2e-b4e6b8a02900.png)

![image](https://user-images.githubusercontent.com/55411834/104965515-1a8ab400-599c-11eb-8aae-e622ece33a7e.png)

</details>

---
11. Business question: Rehabilitation and prosthetics accordion has the following (accurate from the data perspective)
   - Referral needed? Yes
   - Walk-ins accepted? Yes
   - **These seem at odds. What is the expected behavior?**

---
12. The Suicide prevention accordion has several duplicated lines, incorrect data formatting for hours (added /) and non-interactive Crisis Line phone numbers. These are data issues. It is rendering correctly in Staging based on the data. 

<details>
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/104965224-7f91da00-599b-11eb-8f89-111bc1461305.png)

![image](https://user-images.githubusercontent.com/55411834/104965248-8a4c6f00-599b-11eb-96d2-5651acda74e8.png)

</details>

---

13. The Surgery accordion has an hours data formatting issue (added /). 
     - **Business question** This service has a particular location for `Questions or cancelations prior to surgery` which appears above the "Appointments" section. This makes the `Contact us to schedule, reschedule, or cancel your appointment.` language potentially confusing, especially considering they display different numbers. Not sure we can change it but I think the proximity/order of these two fields is awkward.

<details>
<summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/55411834/104965913-efed2b00-599c-11eb-9346-cebbeeba773c.png)

</details>

---
14. The Travel reimbursement accordion uses the facility hours, making the service available hours 24/7. It renders correctly in Staging based on the data but is this correct? 
    - ** What is the expected behavior?**
     
---
15. Should "Walk-ins accepted?" be an option for Telehealth? 

---
15. Women's health appointment phone numbers have labels that are not rendered on the front end. 

<details> 
<summary> Screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/104966538-5888d780-599e-11eb-916f-46f6931de75b.png)

![image](https://user-images.githubusercontent.com/55411834/104966548-663e5d00-599e-11eb-875f-b35f60316036.png)

</details> 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by davidconlon** [comment]
1. On Prod, health service accordions include a link to the campus map. This is not true on Staging.
** What is the expected behavior?**

We made a decision to not include the link to the campus map. 
In the future this will come back via the Campus Map content type b/c the system will know whether-or-not the facility has a map.

**Comment by davidconlon** [comment]
2. Within the Audiology accordion, CMS value for "Walkins accepted" = Unknown. On Staging, "Walkins accepted" = No. On Prod, "Walkins accepted" does not appear at all.
** What is the expected behavior?**

Possible Values for "Walk ins" and display settings:
- _Yes_: **Walk-ins accepted?** Yes
- _No_: **Walk-ins accepted?** No
- _Unknown_: _Do not display the line Walk-ins accepted?_

**Comment by davidconlon** [comment]
3. We should be receiving the main Facility Phone number from the CMS for this field.

![image](https://user-images.githubusercontent.com/56046371/105050320-a7d11580-5a3b-11eb-94be-e07007c2e550.png)

**Comment by davidconlon** [comment]
4. Within the Intimate partner violence accordion, the Domestic Violence hotline displays the facility address on staging but is "off" in CMS.

I *think* the location should be "united states" for now.
We need to revisit what to do about these national services.

**Comment by davidconlon** [comment]
5. For accessibility, phone numbers should be interactive. It is present without link on Prod as well.

This is a content thing.  
That is maintained locally.
We should consider a teachable moment but this is a slippery slope.

**Comment by davidconlon** [comment]
6. Minority Veterans Program email label has a colon (different than phone label)
It is not in the CMS data so I suspect this may be happening on the front end.
** What is the expected behavior?**

This is a FE error. Should be like "Phone" and no colon.
FYSA I updated label to "Email"

**Comment by davidconlon** [comment]
7. Nutrition, food, and dietary accordion calls for use of facility phone number which populates in CMS as 000-000-0000. It displays accordingly on Staging. On Production, the phone field is not included at all.
** What is the expected behavior?**

If the CMS says "use facility phone number", CMS should be populating the facility phone number and that's what we should be using on the FE.
In this case, there was a _second_ phone number in the hardened content as 000-000-0000. I have removed that.

**Comment by davidconlon** [comment]
8. Business question: PTSD accordion has the following (accurate from the data perspective)
Referral needed? Yes
Walk-ins accepted? Yes
** These seem at odds. What is the expected behavior?**
Yeah...this happened a few times. This is where we may (likely) need clarification on the intro from the business. E.g. "If you are in crisis you can walk-in" or understand why they are in conflict.


Editorial experience question: List of pages shows "PTSD treatment - Pittsburgh VA Medical Center - University Drive

I think Steve needs to bounce these for that to update. We can talk about this as a thing in an upcoming meeting.

Inside that service, the VHA health service name and description is PTSD care

**Comment by davidconlon** [comment]
9. This is a bug. I'm unable to delete a service location. I've opened an issue with CMS for them to fix. (#[4035](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4035))

**Comment by davidconlon** [comment]
10. The Registry exams accordion uses the facility hours, making the service available hours 24/7. It renders correctly in Staging based on the data but is this correct?
The email contact is labeled with the person's name (rather than title) and uses a colon.
** What is the expected behavior?**

Front-End was behaving correctly.
This was a data error.  Changed back end data to "Do not show hours"

**Comment by davidconlon** [comment]
12. The Suicide prevention accordion has several duplicated lines, incorrect data formatting for hours (added /) and non-interactive Crisis Line phone numbers. These are data issues. It is rendering correctly in Staging based on the data.

- Data has been cleaned
- Phone number rendering is possibly incorrect where we should be using the "label" for the phone. I think we need to check the design again.

![image](https://user-images.githubusercontent.com/56046371/105072337-af041d80-5a53-11eb-98a0-24e4fffc63b2.png)

**Comment by davidconlon** [comment]
14. The Travel reimbursement accordion uses the facility hours, making the service available hours 24/7. It renders correctly in Staging based on the data but is this correct?
** What is the expected behavior?**
24 hours is evidently correct

![image](https://user-images.githubusercontent.com/56046371/105086474-095aa980-5a67-11eb-8459-f74f7f537ca1.png)

**Comment by davidconlon** [comment]
15. Should "Walk-ins accepted?" be an option for Telehealth?

Updated the data to better reflect what should be there
Including making "Walk-Ins" unknown and "Referral needed" Unknown.
We need to think about this as a modality in the future.

**Comment by mmiddaugh** [comment]
2, Audiology Walk ins https://github.com/department-of-veterans-affairs/va.gov-team/issues/18816
