### ISSUE TITLE
[Design] - Re-evaluate submission experience on the 10-10CG

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#18736]
## Issue Description
What pain points are Veterans facing on the submission page of the family caregiver form?

Are there long response times, and what do they experience during them?

How could we improve the submission page experience?
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mlighdc** [comment]
@sshein - the progress indicator is part of this ticket. It looks like @jonathanjnelson has not broken this down or associated with the timed out work the team has been doing.

@jonathanjnelson can you let Shawna know where the ticket is for the progress indicator / submission time indicator? I could not locate it on the zenhub board.

**Comment by jonathanjnelson** [comment]
Hi @mlighdc @sshein @ala-yna - 

These are the tickets I was assigned this sprint: 

- [Finalize the prototypes for usability study](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/19805)
- [Moderate Usability Study](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20244)
- [QA FE Remove feature toggle for address work on HCA](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/18969)

I have not dug into this ticket yet because it is in the backlog.

**Comment by sshein** [comment]
Thanks @jonathanjnelson! When this ticket gets prioritized and into a sprint, Here are some links that might be useful: 

- Loading button that is currently in the profile a few places but is not an official component https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/loading-button/LoadingButton.jsx 
- The loading indicator component https://design.va.gov/components/loading-indicators

**Comment by mlighdc** [comment]
@Dene-human have talked about this one with Jonathan for a while.  Maybe want to connect with him to review all the backlog tickets that he had and did not get transfer to you. Thanks!

**Comment by hdjustice** [comment]
Closing this ticket - has not been addressed in over a year.  If work is needed, a new ticket will be created under an initiative
