### ISSUE TITLE
Decision Point: Get directions feature

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#18780]
Team needs to decide: how will we manage maps and directions in the app?

**Comment by bridgethapner** [comment]
I have a couple of thoughts from a UX perspective re using latitude and longitude or not: 

It seems like there are trade-offs for using lat/long vs. facility name -- the biggest pro of using lat/long seems to be the potential to have a more accurate location. The biggest con seems to be confusion on whether the coordinates entered in the Maps app are RIGHT and causing confusion to the user over where exactly they're being directed to. For this reason, I think we should use the facility name and not lat/long. I think we should avoid causing confusion, even if that means trading away the potential to offer a more accurate location -- especially because it doesn't seem like we're _sure_ lat/long will indeed with 100% certainty offer a more accurate location.

**Comment by ayushchak** [comment]
Thanks, Bridget - my intuition (which I would love to gut-check) also agrees and thinks that if users are sophisticated to be on a mobile app, they are sophisticated enough to use a navigation app (Google or Apple maps) and type the facility name in, but I'd love to check this against any existing research if possible

**Comment by bridgethapner** [comment]
I think a person who may be able to help us here is Leyda Hughes, the UX lead on Facility Locator. I can reach out to her and see if this issue of a more general location vs. a more specific location is something that's come up in her research.

**Comment by lexicalninja** [comment]
Closing. I did some work and spoke with @ayushchak about this. We can use a combination of Lat/Long and place name to create a good experience. Updating #15609 with the solution urls.
