### ISSUE TITLE
Analytics Implementation  [VAMC - Erie-health-care website]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#18822]
# Google Analytics Implementation 

## Description
- Google Analytics implementation is required for Erie-health-care VAMC website to match the pilot project and standards as set at va.gov/pittsburgh-health-care/ , so owners, PAOs, and stakeholders can have a consistent view and standard data sets to review and make decisions from regarding VAMC web pages.

- Who is this request for?
    * VAMC-upgrade - va.gov/erie-health-care
    * Product Manager - Stan Gardner - sgardner@govermentcio.com
    * Product Owner - Dave Conlon - david.conlon@va.gov
   
    
- What team/project is this work for?
    * VAMC - Upgrade
     * Main Slack Channel - vsa-vamc-upgrade
          
- Provide the Domain where Google Analytics needs to be implemented
    * va.gov/erie-health-care/
    
    _Identify if PII is passed in URL or title tag_
    * N/A
   
- Please provide any upcoming deadlines or important milestones
    **Go-Live for erie-health-care, set in 30 days from Dual-State.  Estimated approximately February 9th, 2021**
   
    - Typical Website Interactions to Track

    - * Please implement the exact KPI and tags set up for Pittsburgh-health-care, see the original request below 
    
    - [Please follow Original Analytics Implementation request #1846](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1846)
    
- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - N/A

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - N/A  "This is a website open to public access via va/gov

- Certain conditions/responses that need to be reviewed
    - N/A

- Additional Comments

    ** VAMC- upgrade will be repeating this process request 140 more times as VAMC websites come online.  This should become a standardized template to initiate on all future VAMC websites.**

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1710283887) is updated

**Comment by joanneesteban** [comment]
Thanks for opening this, Stan! We'll review and triage within our team.

**Comment by jonwehausen** [comment]
## Data Layer Specification

Hi @SgardnerPMP , thank you for your patience with this request. Please see the details below for FE data layer implementation and please do not hesitate to reach out with any questions 


### Context
- The following data layer specification mirrors the specification from 1846, but has improvements since Sep 2019 towards our goal of standardization according to the design system, so expect slight differences

### Data Layer

Description/Screenshot of Interaction | Data Layer Specification | Dev Notes
| -- | -- | -- |
[Sidenav (left nav) ](https://design.va.gov/storybook/iframe.html?id=components-sidenav--page&viewMode=docs)|  `'event': 'nav-sidenav' //consistently populate for side navs`<br>`'sidenav-click-action': //'expand', 'collapse', 'click-through'`<br>`'sidenav-click-label': //populate according to sidenav clicked on`<br>`'sidenav-click-level': //number representing the indent level of the navigation level clicked on`<br>`'sidenav-parent-label': //label of next 1-level higher parent, undefined if is parent`<br>`'sidenav-accordion-header': //label of the collapsible accordion header`<br>`'sidenav-section-title': //h4 in design system docs` |   • Please populate `undefined` for `'sidenav-accordion-header'` since those aren't present here  <br> • All clicks here can populate `'sidenav-click-action'` with `'click-thru'` since there's no accordions here <br> • Please populate `undefined` for `'sidenav-section-title'`  <br> • As an example, populate `'sidenav-parent-label'` with `'Work with us'` when "Jobs and careers", "Internships and fellowships", and/or "Volunteer or donate" is clicked <br><br> **It would be very much appreciated if this same spec could be updated to be on `'/pittsburgh-health-care'` pages as well**
Jumplinks <br> ![image](https://user-images.githubusercontent.com/48527022/106677652-1dce9400-6587-11eb-973c-7132dc56195a.png) | `'event': 'nav-jumplink-click'` | Looks like these are already implemented through an `onclick` handler within the HTML 😄 
CTA buttons ![image](https://user-images.githubusercontent.com/48527022/106677883-93d2fb00-6587-11eb-8c1a-b63771805b8d.png) | `'event': 'cta-button-click' //consistently populate for ALL types of button clicks`<br>`'button-type' //'primary', 'secondary', 'default'`<br>`'button-click-label': //dynamically populate with text of button`<br>`'button-background-color': //dynamically populate with the background color of the button`
Accordions (Collapsible Panels) ![image](https://user-images.githubusercontent.com/48527022/106678067-f2987480-6587-11eb-9453-30e30910f06e.png) |  `'event': 'int-accordion-expand', //OR 'int-accordion-collapse'`<br>`'accordion-parent-label' //accordion parent label (if there is two labels, if only one label on accordion, populate this value and make child-label undefined)`<br>`'accordion-child-label': //dynamically populate with secondary label of the accordion`<br>`'accordion-section-label': //populate with the label of the section where the accordion is present` | • This is a new taxonomy using 'int' instead of `'nav'` -- this is intentional to standardize our naming conventions further <br> • If the accordion only has 1 label, just populate the `'accordion-parent-label'`, otherwise populate both if there are 2 labels ![image](https://user-images.githubusercontent.com/48527022/106678263-5622a200-6588-11eb-8c12-053fdc410558.png) <br> • `'accordion-section-label'` should be things like "Primary care", "Mental health care", "Specialty care", etc 
Featured content (light blue boxes) | `'event': 'nav-featured-content-link-click' //consistently populate for all featured content link clicks`<br>`'featured-content-heading': //dynamically populate according to the header of the featured content`<br>`'featured-content-click-label': //dynamically populate according to the link label` | **Please reach out to #vfs-platform-support to discuss + confirm whether these are alert boxes with background only (see Alert Box spec below) or featured content, thank you**
Breadcrumbs ![image](https://user-images.githubusercontent.com/48527022/106678784-6be49700-6589-11eb-80c0-8cf7fa2143f0.png) | `'event': 'nav-breadcrumb-click' //consistently populate for all breadcrumb link clicks`<br>`'breadcrumb-click-level': //integer value for the level clicked on`<br>`'breadcrumb-total-levels': //integer value with the total amount of breacrumb click labels`<br>`'breadcrumb-mobile-first-enabled': //populate if mobile first prop was used`
Alert boxes (link click) ![image](https://user-images.githubusercontent.com/48527022/106679003-ce3d9780-6589-11eb-95f5-a0dff725ecb5.png) | `'event': 'nav-alert-box-link-click' //consistent for all links within an alert box`<br>`'alert-box-type': //dynamically populate according to the type of alert box, 'warning', 'error', 'informational'`<br>`'alert-box-heading': //dynamically populate according to the top level heading of the alert box`<br>`'alert-box-alert-box-subheading': //dynamically populate according to the sub level heading of the alert box`<br>`'alert-box-click-label': //dynamically populate according to the click label of the link`<br>`'alert-box-full-width': //populate with boolean true\|false if alert box full width prop was used`<br>`'error-key': //i.e 123_description_of_error, error code and description to give context if this alert box was used in accordance with error tracking`<br>`'alert-box-background-only: //dynamically populate with boolean true\|false if alert box background only prop was used`<br>`'alert-box-closeable': //dynamically populate with boolean true\|false if the alert box is in-fact closeable` | • Can populate `error-key` with `undefined` here 
Alert boxes (close click) | `'event': 'int-alert-box-close' //consistently populate when an alert box is closed`<br><br> **use variables listed above as well**

**Comment by jonwehausen** [comment]
@bsmartin-ep For your visibility, I had to tweak the Side Nav spec a little bit to account for some of the nuances with this particular navigation structure. You can find that reflected [here](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/platform/analytics/google-analytics/tracking-design-system-components.md)

**Comment by jonwehausen** [comment]
### Next Steps
- @jonwehausen to configure GTM

**Comment by SgardnerPMP** [comment]
Thank you.  I will share this output with the Facilities team, so they are aware.  I will reference this Issue# and 1846 for next roll outs coming soon.  Great Job!

**Comment by mmiddaugh** [comment]
Similar request: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15132

**Comment by jonwehausen** [comment]
Hi @SgardnerPMP & @mmiddaugh , 

Other VAMC Tickets (20131, 20130) have been updated to point towards this data layer specification. Please keep us posted on timeline for implementing. [This spec](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18822#issuecomment-772103021) can be referenced each time a new VAMC roll out is set to occur 

Thanks so much in advance.

**Comment by mmiddaugh** [comment]
@jonwehausen can you direct me to where the data can be viewed? (ie: for Pittsburgh)

**Comment by jonwehausen** [comment]
cc: @SgardnerPMP on above

**Comment by jonwehausen** [comment]
Hi @SgardnerPMP & @mmiddaugh , 

Could we have an update on the status of the DL implementation for VAMCs? Thanks so much

**Comment by mmiddaugh** [comment]
@jonwehausen we broke the work into individual issues captured in an epic (#21559)

The following issues are in our current sprint:
- Implement VAMC accordion data layer #21555
- Implement VAMC data layer for links within accordions #21556

The remaining issues will be pulled into future sprints (hopefully next sprint)
- Implement data layer for VAMC featured contentva.gov-team #21557 
- Implement data layer for VAMC new site alertva.gov-team #21558 
- Additional dataLayer attributes for SideNavva.gov-team #21748

**Comment by jonwehausen** [comment]
Hi @mmiddaugh , 

Thank you very much for this information!

**Comment by jonwehausen** [comment]
### QA Accordions

- @mpelzsherman thank you for your effort here -- we very much appreciate it. Per our test results below, there looks to be an issue with capturing the DL variables for accordions here. Please let us know any questions you may have here. 
- Fysa I was able to use this [review instance](http://53ae53620eedaf9217582ef75b4a4ae0.review.vetsgov-internal/erie-health-care/health-services/) to perform testing
- We'll be ready to test the accordion link clicks 

| Description/Screenshot of Interaction | Data Layer Screenshot | Test Status | Test Notes 
| -- | -- | -- | -- |
Click to EXPAND "Advice nurse" accordion -- _single label accordion_ | ![image](https://user-images.githubusercontent.com/48527022/115386289-32462400-a1a7-11eb-8d6d-37fbbcb302fc.png) | ⚠️ **DOES NOT PASS** | • @mpelzsherman with this accordion only having 1 label, we should only populate the `'accordion-parent-label'` with `'Advice nurse'` and `'accordion-child-label'` should be `undefined`
Click to COLLAPSE "Advice nurse" accordion -- _single label accordion_ | ![image](https://user-images.githubusercontent.com/48527022/115386722-c2846900-a1a7-11eb-92ba-6ddb30218e92.png) | ⚠️ **DOES NOT PASS** | • Same change needed here for `'accordion-parent-label'` and `'accordion-child-label'`
Click to EXPAND "Primary care" <br> "Family and internal medicine" accordion - _double label accordion)_ | ![image](https://user-images.githubusercontent.com/48527022/115387658-f744f000-a1a8-11eb-961c-35847a8cfd21.png) | ⚠️ **DOES NOT PASS** | • @mpelzsherman looks like we did not capture the relevant data layer variables here -- `'accordion-parent-label'`, `'accordion-child-label'`, `'accordion-section-label'`
Click to COLLAPSE "Primary care" <br> "Family and internal medicine" accordion - _double label accordion)_ | ![image](https://user-images.githubusercontent.com/48527022/115388041-6c182a00-a1a9-11eb-8f0f-6b0853620d08.png) | ⚠️ **DOES NOT PASS** |  • Same change needed here for `'accordion-parent-label'`, `'accordion-child-label'`, `'accordion-section-label'`

**Comment by mmiddaugh** [comment]
Thanks @jonwehausen. I moved your feedback into #23662 and will discuss it with Michael. 

FYI, our sprint began on 4/21 and ends on 5/4.

**Comment by jonwehausen** [comment]
### QA Retest of Accordions 

| Description of Interaction | Data Layer Screenshot | Test Status | Test Notes
| -- | -- | -- | -- |
Click on accordion "Audiology and speech" with subheading of _"hearing, speech and balance"_ | ![image](https://user-images.githubusercontent.com/48527022/116399572-13730d80-a7f7-11eb-9d63-2ffa36734225.png) | ✔️ **PASS**
Click on accordion "Pain management" with no subheading | ![image](https://user-images.githubusercontent.com/48527022/116410024-61414300-a802-11eb-9785-398a7bb56348.png) | ⚠️ **DOES NOT PASS** | @mpelzsherman -- In order to not risk metadata "bleedover" for when an accordion with 2 labels is clicked first, it's imperative we push `undefined` for `accordion-child-label` when a single accordion label is clicked

Let me know if you have any further questions here.

**Comment by mmiddaugh** [comment]
@bsmartin-ep @laurensimpson14 
As mentioned in [my comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18822#issuecomment-820507358), the team broke this into chunks and has been working on this data layer in pieces along with other sprint work. 
We have a few pieces of implementation ready to validate: 

- Implement VAMC data layer for links within accordions #21556
- Update accordion data layer #23662

**Comment by joanneesteban** [comment]
@mmiddaugh is this ready to be closed? Thanks!
