### ISSUE TITLE
User Survey Request for Debt Resolution (formerly BAM2) 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#18892]
# Request the Medallia Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/platform/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
The online FSR form will allow Veterans to fill out the Financial Status Report online when requesting debt resolution from DMC. See prototypes [here ](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/133701647/simulate/sitemap?mode=i)

I would also like to discuss how we can add this to the currently released Debt portal - va.gov/manage-va-debt without duplicaitng survey if the veteran goes on to fill out FSR 

### Launch Date
Mid February 

### Staging URLs
TBD next sprint 

### Production URLs
va.gov/manage-va-debt

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by leahkeeler** [comment]
Hi - Checking in to see when we can incorporate this

**Comment by jwoodman5** [comment]
Hi @leahkeeler I asked for another update from Medallia on the timing of their 508 fix and will let you know what I hear. The pilot launch is still dependent on that.

**Comment by leahkeeler** [comment]
Thanks-you @jwoodman5 - I thought I heard it was launching at ToT - maybe I heard what I wanted to hear lol 

Would it be possible to get a demo of all the capabilities from your team or the Vendor? I know we are somewhat limited in what we can ask the Veterans but we have some pretty complex products launching and would liek to collect more then smiley faces, if possible Thanks!!!!!

**Comment by jwoodman5** [comment]
@leahkeeler There are two different standard surveys, the intercept survey which will apply across all VA.gov pages (except for exclusions) and the Feedback survey, which will be on pages specifically requested by page owners. The latter is what it seems you are requesting. The intercept survey got cleared for the pilot prior to us getting the Feedback survey cleared for the pilot late yesterday. What you heard last week was in regards to the intercept survey.

Surveys have to be PRA approved and we only have the standard, 3-question Feedback survey available now. I will have some conversations about what kind of customization VA is or isn't interested in supporting.

**Comment by leahkeeler** [comment]
Thanks @jwoodman5 - I didn't get the nuance - makes sense. LMK when you are ready to go with the Feedback survey, we are ready when you are

**Comment by rileyorr** [comment]
Good morning @jwoodman5! I know your team just wrapped up a usability study surrounding the feedback button styling - what's the current status of the Medallia rollout? I tried to read more about requesting a survey but the link in this ticket redirected to a 404 and I couldn't find anything similar in Medallia's product folder.

**Comment by jwoodman5** [comment]
Hi @rileyorr - Here's the link for [requesting a Medallia Survey](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md). We had to move the document and existing/open tickets were not updated with this link. It basically just tells you how to access this ticket template and reiterates what the standard Feedback survey consists of, but please have a read and let me know if you have any questions. 

Are you looking to add the questions shown in the prototype linked in the description?

**Comment by rileyorr** [comment]
Hi @jwoodman5! Thanks for that link. 

The questions you're seeing in the prototype are part of the FSR's wizard that guides Veterans either to the FSR or a different resource depending on their needs. Since this ticket's creation, the FSR has been developed and [can be accessed here](https://staging.va.gov/manage-va-debt/request-debt-help-5655/introduction) using user+1. We're looking to implement the survey from the wizard page through the confirmation page if feasible. I think we'll also want it on the form's corresponding content page, but I don't believe that's been finalized yet. @leahkeeler might have more info about that.

Additionally, we'd like to add the survey to [the debt management portal](https://staging.va.gov/manage-va-debt/), which can also be accessed in staging with user+1. Would you like me to create a separate ticket for that second survey request?

**Comment by jwoodman5** [comment]
You bet, @rileyorr! 

Can you please confirm you are looking to add the standard feedback survey (as described on the `How to request a survey` page) added to the FSR wizard page through the confirmation page along with the corresponding content page? And then also on the debt management portal? 

I am not familiar with the FSR wizard. Is that affiliated with the debt management portal? If so, one ticket will suffice. If not, please do submit a separate ticket. Hope that helps. Thanks!

**Comment by rileyorr** [comment]
@jwoodman5 yup, I'm looking to add the standard feedback survey as described in the [How to request a survey](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md) page to the FSR wizard page through the confirmation page along with the corresponding content page whose link is TBD. 

The FSR wizard is affiliated with the debt management portal in the sense that both are part of the overall VA debt experience. One of the pathways within the wizard ([which you can view in staging here](https://staging.va.gov/manage-va-debt/request-debt-help-5655/introduction)) leads to the debt management portal's content page. Since it's a separate tool, I'll just write up a separate ticket for ya to make things easier! 

Apologies if my explanations are confusing, there's a lot of moving parts here! I'm happy to hop on a call if that would be helpful

**Comment by rileyorr** [comment]
Added [the separate survey request ticket for the Debt Management Portal](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23366) 👍

**Comment by rebeccawalsh** [comment]
@jwoodman5 Looking through our remaining tickets assigned to our sprint and we're not sure if we're meant to close it out, or leave this open? Are we supposed to be *assigned* to this work?

**Comment by jwoodman5** [comment]
Hi @rebeccawalsh - You do not need to do anything with this ticket. I and my team will handle the survey additions and moving the ticket through the pipeline. Feel free to remove yourself unless you wish to remain for visibility. Thanks!

**Comment by jwoodman5** [comment]
Hi @rileyorr No worries! All we need is a list of URLs you want the Feedback survey added to. If it is an entire directory (i.e. va.gov/manage-va-debt/ and all detail pages), you can just specify that. Once we have that info, it should be a pretty quick turn around. Thanks!

**Comment by rileyorr** [comment]
Cool! We'd like it added to the entire manage-va-debt directory. For this ticket, specifically va.gov/manage-va-debt/request-debt-help-5655/ all detail pages.

**Comment by jwoodman5** [comment]
Thank you! This request has been submitted and I will confirm when the survey is live.

**Comment by jwoodman5** [comment]
Okay, we are live! Thanks again.

**Comment by rileyorr** [comment]
@jwoodman5 I'm excited we're live! How are we able to access Medallia results?
