### ISSUE TITLE
Content Feedback - Usability Prep - GI Bill Comparison Tool redesign

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#18949]
## User story
VSP content feedback for GI Bill Tool redesign
Link to prototype: https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
Questions/Thoughts

-	Breadcrumbs are missing in the prototype. Assuming we'd use the same one as the current tool? 
-	The H1 no longer has “GI Bill” in it. Is this tool being renamed/rebranded? 
-	Can we see the flow if user searches by Employer or VET TEC. Do any of the labels or messaging change? 
-	In current tool, there are Learn more links that users can click on to get more information about a question or benefit. Where will that information live now in redesigned tool? 
-	Could the housing allowance setting be incorporated into the main search area rather than a modal? Users might miss the note below with link to modal.  
-	Is there a limit on how many schools or programs a user can compare? If so, we should include content to that effect. 
-	Some screens that have Lorum ipsum. What content will go there? 
-	“Each complaint can have multiple types" Does this sentence mean that there could be multiple complaints for a school? 
-	Compare button. .Can this button be more dynamic and descriptive. Could it be based on the type of search the user is doing? For example, 
Compare schools
Compare employer programs
Compare VET TEC
-	CTA buttons should more descriptive in the housing allowance modal. Could we update to: “Apply settings” and use this pattern consistently when the user is applying or updating a set of criteria? 

--For example, under Military details label
instead of Update benefits could it say: “Apply military settings” 
--For example, under Institution preferences label 
Instead of Apply button.. change to “Apply school settings”?
--For example, under Degrees / majors label
Change Apply button TO: Apply degree settings


https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055401
this screen shows the old search UI… should this be updated?  
 

**MUST**

1. All headers, labels, CTA buttons, subhead should be sentence-case. For example:
Search School> Search school
Search Employers> Search employers
Type of School>Type of school
4 Year> 4 year
2 Year> 2 year

Degree/Major> Degree or major
Level of degree > Degree level
Level of institution> School level

If leaving the housing allowance content in a modal, then we should rewrite that content to be more descriptive and provide mor detail where we are sending users. 
We base housing allowance estimates on you taking in-person classes. You can update your housing allowance settings by going [here]. 


https://bahdigital.invisionapp.com/share/2MIAFYF83FT#/screens/296055429
fix misspellings on this page
allowance
GI Bill 

Fix misspelling of student


Veteran programs chart
Use of red xs and green checkmarks. I recommend we don’t use just icons and color to show Yes/No. Could we include also some content to convey this?  

Estimate your benefits screen

 Suggested rewrite below to make it more content more  clear and to remove use of nondescriptive [here] as a link
These benefits are based on your military settings. To update your military settings, [return to the search page].


**SHOULD**
I recommend this rewrite intro to  incorporate “training” programs: 

Recommendation: Use the GI Bill Comparison Tool to learn what benefits you’ll get at the school or training program you want to attend.

“Looking for”  label is vague. Can this be more specific and tie to the type of search. For instance 
If user is Searching by school, label would be School name
If user is Searching by employer would be Program name


I recommend this paragraph be rewritten to make it more clear, as we’re not showing the user anything at this point. 

We based tuition estimates on the following criteria: Veteran, receiving Post-9/11 GI Bill (Chapter 33) benefits who has served for 36 months or more. You can change tuition estimates by updating your military detail settings. 



Breadcrumb on screen 2 is “How to apply” is this accurate? 



Learn more links should be more descriptive. For example, Learn more about [housing allowances]

Institution preferences label suggest not using "Institution" and instead use the more plain language “school or program”


All Locations label
Recommend updating Distance radius TO:  Search within 
Recommend updating Current location TO Use my current location

**Comment by amyknox** [comment]
@peggygannon thank you for all the thoughtful input. Here are answers to a few of the questions we didn't get to on Wednesday:

1. “Each complaint can have multiple types" Does this sentence mean that there could be multiple complaints for a school?
No.  Schools can have multiple complaints but that sentence means that each complaint could be tagged with multiple categories. So, for instance, I could make a single complaint against Devry for low-quality instruction, mis-handling my GI Bill funds, and lack of food options on campus.  So that 1 complaint would count against them 3 times. 

2. Compare button. .Can this button be more dynamic and descriptive. Could it be based on the type of search the user is doing? 
Yes. Making that update. For example,

3. CTA buttons should more descriptive in the housing allowance modal. Could we update to: “Apply settings” and use this pattern consistently when the user is applying or updating a set of criteria?
We'll play with that and see what happens. Some of the button labels would be really long so we want to make sure we're not causing other problems for ourselves.  Since the modal and drop-downs are all pretty small, it should be clear what the user is applying. 

Thanks again, Peggy. Always appreciate your time and attention to our work!
