### ISSUE TITLE
Update a11y labels to match page titles

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#18951]
## Context for this ticket
Currently, a11y labels and page titles are not 1:1. 

## Acceptance Criteria
1. Sweep all pages in the app and update the accessibility labels so they match the page titles
     - For example, on the Prepare for Video Visit page: the a11y label is "prepare for video visit screen". The page title is "prepare for video visit page." Please update the a11y label to match the title. 
2. For pages that do not display a header, use the programmatic title
3. For pages that have the same header (e.g. File Upload flow), combine the header with the specific screen functionality
     - Ex: "File upload: select a file to upload for the request" + "page"

## Related ticket
Bug: #16846

**Comment by digitalken** [comment]
Added to TestRail.

**Comment by digitalken** [comment]
2/18/2021 - @komaly15, I'm able to go through the screens with Android and hear things like "Claims page" when I tap onto a portion of the page that doesn't highlight text and read it back to me.  When I try the same with iOS, I only hear a 'click'.  I can never seem to hear "Claims page".  (This is only an example.). The Profile page would be another example.  If something else is highlighted and I tap into the blank section toward the bottom of the page, Android says "Profile page."  With iOS, it will 'click'.  Nothing said.  I'm sending this back into "In progress" for you to have a look again.  Thanks -Ken.

**Comment by digitalken** [comment]
PASS 2/18/2021 - only for Android.  Closing.
From @komaly15 -

"The issue though is that if we update it so that IOS can read the overall page accessibility label, then it can't access any of the individual elements on the page (Thats just how IOS is, if an outer element is accessible then any elements within that can't be accessed). The overall page accessibility labels are only something we added in for integration testing purposes, and from my understanding the main reason we updated these to match the page titles is so that when we do hear the page accessibility labels when clicking on a screen background in Android, there isn't a discrepancy between that and the page titles themselves."
