### ISSUE TITLE
[Design] MyVA LOA3 user who has everything but has no updates

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#18996]
## Background information

Desktop Invision Link (https://vsateams.invisionapp.com/share/RNZWCZBXZJ6#/screens/443287787)

## Tasks
- [ ] Work with Peggy to finalize copy for a user who has everything but no updates
- [ ] Review with Matt/Samara

**Comment by tressaellen** [comment]
@peggygannon - this is the screenshot for if a user has claims, healthcare, applications in progress and has NO updates in each of these.

- Everything is open for review except for the title (MyVA) and anything that is in the grey boxes (those came from the design system).
- The 'What benefits does the VA offer?' dropdown does not exist anywhere else, this was all made for this screen so this will likely need a lot of changes.
- The related links in the health care section need to be consolidated into 1 link since they go to the same place.

Let me know if you have any other questions.


![My VA No updates](https://user-images.githubusercontent.com/58752772/105865577-89b96700-5f9f-11eb-8247-abc558da91df.jpg)

**Comment by peggygannon** [comment]
@tressaellen @callen2563 Suggestions/thoughts below. Please let me know if you have any questions. 



You have no claims or appeals updates in the last 30 days. 

-----

Health care section
What do you think about the updates to card headings? I'm recommending this to take into account if a user doesn't have a "latest message" or if a user "has more than 1 upcoming appointment on same day" or if user doesn't have an upcoming appointment. 
Latest message> Messages
Next appointment > Appointments
Prescription update > Prescriptions


Messages
You have no new messages from your health care team.

Appointments
You have no appointments scheduled in the next 30 days. 

Prescriptions
You have no prescription refills or updates in progress.

------

Apply for benefits> Apply for VA benefits

QUESTION: Can we be more specific about the number of applications in progress?
Could we say:
You have [x] applications in progress
You have no applications in progress

------

QUESTION: will these links take user to main benefit hub pages? 
Please remove bullets from before each link

{addl component] What benefits does VA offer? 
Explore VA.gov to learn about the benefits we offer.

**Comment by callen2563** [comment]
@tressaellen @peggygannon I removed the healthcare card headers but wondering if "applications in progress" should be removed as well? Let me know your thoughts. Thanks! 
![My VA No updates](https://user-images.githubusercontent.com/68560244/107076266-30c8aa80-67b9-11eb-8880-016769d6d6be.jpg)

**Comment by callen2563** [comment]
@peggygannon @tressaellen This copy had also been updated..

![My VA No updates](https://user-images.githubusercontent.com/68560244/107395514-e3a34c00-6aca-11eb-863f-6a36f3ea1867.jpg)
