### ISSUE TITLE
[Design] MyVA 2.0 Convo guide for usability testing of finalized designs

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19121]
## Background
Now that we have finalized the designs for MyVA 2.0, we need to create a research plan and conversation guide in preparation for usability testing.

## Tasks
- [x] [Create conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-conversation-guide.md)
- [x] Review with Matt/Samara

**Comment by tressaellen** [comment]
Here is the [Conversation Guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-conversation-guide.md)

**Comment by Samara-Strauss** [comment]
Great work! Here is my feedback:

### First task: Disability rating**

- If you start them on the live site in a logged-out state, they won't be able to see My VA. So, this task will need some reworking if we are hoping to test putting My VA in the unauth nav as part of this task. One idea: include the homepage in the prototype, and start them there. Of course, this doesn't let them potentially try to dig around much, so that might not be ideal. Second idea would be to have them log in to VA.gov for real, but given that logging in alone could take a while if they have difficulty, this also isn't perfect. BUT it would allow them to both wander a bit and click into My VA, at which point you could switch them to the prototype. 

### Second task: Health care

**Messages**

Additional question for consideration:

- Why do you think we are showing the message in the gray box? How would you read this message?
- What is the most important thing we could tell you on this page about your messages?
- What would make you want to click to see more information about your messages?

**Appointments**

- Since we'll already be focused in this section, idk if there is much of a point in asking "You've come to this page to see when you are visiting your doctor next. Can you walk me through how you would do that?" This is probably going to be pretty obvious at this point since the Appointment heading will be right below Messages.
- **Was it easy or hard to find your appointments?** I also don't know that there is much point in asking this if they're already in the health care section.

Additional question for consideration:

- Why do you think we are showing the appointment in the gray box? How would you cancel this appointment if you needed to?
- What is the most important thing we could tell you on this page about your appointments?
- What would make you want to click to view more information about your appointments?

**Prescriptions**

- **Was it easy or hard to find your prescription refills?** Again, may not be totally helpful given the proximity to other tasks, BUT, I guess, if people did struggle, we'd definitely want to ask more about their thought process.

Additional question for consideration:

- Why do you think we are showing the prescription in the gray box? How would you get more information about this prescription if you needed to?
- How many prescriptions do you (aka Kim) have that are currently in the process of being refilled?
- What is the most important thing we could tell you on this page about your prescriptions?
- What would make you want to click to view more information about your prescriptions?

## Claims

This section is great!

I did have a thought, though, about the "totals" question in general (for this section and others). Do you think we should ask if that information is helpful or unhelpful to them? Or no? I'm going back and forth and am curious as to what you think. 

Additional question for consideration:

- What is the most important thing we could tell you about your claims and appeals?

## Apply for benefits

- **Why do you think these benefits are showing vs some other ones?** Just make it clear which ones you're talking about, unless this is intentionally vague to cover both in-progress apps and "Benefits you might be interested in."

Additional question for consideration:

- How could we improve this section?

## Overview and comparison

- "What additional features would you need for this to work as a homepage?" Let's stay away from "features" since that's tech speak. Maybe something like "What would you add, remove, or change about this page if it were your personal homepage?"
- I think you can remove the whole "Comparison" section to the original My VA. We already know it's a lot better now, and they'll have already done a lot of tasks at this point. I don't think this adds enough value to be worth your/their time.

Additional questions for consideration

- (Show real homepage) Let's look at the existing VA.gov homepage. Tell me how it compares to the page we just looked at.  
- Would you prefer to see the existing homepage when you log in or the My VA page we looked at today as your homepage? Why?

....that last question isn't perfect and there could be some bias since we spent a lot of time talking about My VA, but I'm curious as to what people might say.

**Comment by tressaellen** [comment]
@Samara-Strauss I've updated the conversation guide, but had a few thoughts that we can go over when we meet in an hour (I can come back and document our decisions here). 

1. I'd like to talk about the best way to start from the homepage/test the MyVA link on the unauth side of things, we can go over that shortly.

2. I left the 'Was it easy or hard to find...' questions in because I was considering splitting up the health care tasks into so they aren't all stacked together. The more that I think about it though I think it's fine to leave them together because they're all so close together on the page that if a user sees 'Messages' then they'll most likely also notice their 'Appointments' and 'Prescriptions'. I took those questions out. 

3. > What would make you want to click to see more information about your messages/appointments/prescriptions?

What are you trying to assess here? I'm a little confused by the wording and I just want to make sure I'm understanding what you're getting at in case I need to ask any follow up questions.

**Comment by Samara-Strauss** [comment]
Sounds good! We can definitely discuss all of this. See you soon!

**Comment by tressaellen** [comment]
Okay, I've made all the changes! Let me know if you see anything else that needs to be updated. Otherwise I think we're good to close this.

**Comment by Samara-Strauss** [comment]
This is great and should be good to close! I'm really looking forward to seeing how this research goes :D 

One thing: this is a bit long, so we might want to run a pilot session ASAP to get a sense of what kind of time window we should tell Perigean to recruit for. While there are a lot of questions, the tasks *should* be quick, but we should validate that assumption.
