### ISSUE TITLE
[Design] Regional Office Selection (step 4 of 6)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1915]
## User Story or Problem Statement
As a claimant, I need a comprehensive way to select a single regional office from a list or regional offices when completing the HLR form so that I can be certain that the right office is selected.

## Goal
_Display multiple regional offices in comprehensive, select-able view_

## Acceptance Criteria
- _As the designer, I need to identify a comprehensive way of allowing a user to select their regional office from a list of multiple locations_

## Definition of Done
- [x] Identify issue with current design
- [x] Identify design of proposed solution for displaying multiple regional offices
- [x] Request content review from VSP (Yana create a ticket and assign Peggy Gannon)
- [ ] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
<img width="552" alt="HLR-4of6-Request_Original_Jurisdiction" src="https://user-images.githubusercontent.com/54544300/65259930-8375c980-dad3-11e9-8e60-d02a3acbf05c.png">

**Comment by rileyorr** [comment]
@YanaRoy @Mottie I've created new mockups for the overall 'Contested issues' user flow that also shares aspects with #1919 
The mockups can be found [here](https://vsateams.invisionapp.com/share/W5U21BDFTQK) under the 'Contested Issues' section header.
My new user flow resulted from comparing patterns to the current 21-526EZ application process. In that process, Veterans select the disability(ies) they want to claim and are prompted with questions for each disability. Since each disability rating could have been determined at a different office, it makes sense to follow a similar pattern for each contested issue. I decided to include the optional notes question in the same screen since it pertains to that specific issue. 

Since the VA cannot promise that contested issues will be reviewed by the same office, I included an informational alert if the Veteran requests that the issue be reviewed by the same office. Additionally, a disability must be selected in order to apply, so I added an error if the Veteran attempts to continue the application before selecting a disability. LMK feedback or if you have any questions!

**Comment by rileyorr** [comment]
Requested content review on #1919 
I don't think I need to request it here as well, since it's the same mockup.

**Comment by peggygannon** [comment]
@rileyorr This screenshot is different than the one that appears in the HLR mockup I looked at earlier this week. ( https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/386841005/comments)

Can you tell me which one is the most up to date version? 

cc @meganhkelley @YanaRoy

**Comment by peggygannon** [comment]
Hi, @YanaRoy I think the screenshot above is out of date. I have provided content recommendations to the HLR mockup, via https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2011

As such, I think this issue #1915 can be closed.
