### ISSUE TITLE
[Design] MyVA 2.0: Mock up mobile screens to match desktop

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19163]
## Background
We need to convert mobile screens to match desktop

## Tasks
- [ ] MyVA Mobile screens have been mocked up to match desktop
- [ ] Review with Matt/Samara

**Comment by Samara-Strauss** [comment]
A few things:

- Of course, we need mobile screens for the prototype, so those are priority.
- Otherwise, work with Erik and Sandra to see what they actually need. They likely don't need every single screen in desktop AND mobile, so spend your time accordingly based on what is helpful to them (again, beyond making sure we have what we need for the prototype).

**Comment by Samara-Strauss** [comment]
Done. This should have been closed a long time ago.
