### ISSUE TITLE
[Design] MyVA: Create clickable prototype for research

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19164]
## Background
In preparation for usability testing, we need to create clickable prototypes.

https://vsateams.invisionapp.com/share/XNZWCYAYD45#/444774121_Home_Screen

## Tasks
- [x] Create clickable prototype
- [ ] Review with Matt/Samara

**Comment by callen2563** [comment]
@mshea0606 @Samara-Strauss I have reviewed the prototype with Tressa but let me know if there is any thing you would like to add https://vsateams.invisionapp.com/share/XNZWCYAYD45#/444774121_Home_Screen
thanks!
Cassandra

**Comment by Samara-Strauss** [comment]
Only thing I caught that needs to be changed is [on this screen](https://vsateams.invisionapp.com/share/XNZWCYAYD45#/screens/444040702). If you click into the main menu from the My VA dashboard and then click out of it, it takes you back to the signed out homepage. This isn't how it would work IRL, so if people can open the main menu from the dashboard (and I think they should be able to in case they want to look for information there), closing the menu should leave them on the dashboard. **This might mean having two different screens of the menu in the prototype**, one that will close/go back to the homepage if people open the menu from the homepage, and one that will close/go back to My VA if it's closed from there.

**Comment by callen2563** [comment]
I see what you mean, I had an extra link in there but removed it so that will fix the problem. The InVision link has been updated. Thanks!

**Comment by Samara-Strauss** [comment]
@callen2563 this is still not working how it needs to — now I can't close the menu from My VA or the homepage. If I click into this menu from My VA, I am forced to click "My VA" again and go through the sign in flow. This is not how things would work on the website, and it should not be how things work in the prototype, or it will cause confusion for users and potentially disrupt testing. Please fix this as follows:

- A user should be able to open and close the menu from the homepage and land on the homepage.
- A user should be able to open and close the menu from My VA and land on My VA. **Because of how InVision works, this probably means you will have to have the menu in their twice — one that links from the homepage and one that links from My VA**. This is OK because it will all appear as the same menu to participants.

**Comment by callen2563** [comment]
@Samara-Strauss @tressaellen @mshea0606 
I have made the above edits..
https://vsateams.invisionapp.com/share/XNZWCYAYD45#/444774121_Home_Screen

**Comment by Samara-Strauss** [comment]
Thanks!

One last thing I noticed: when you click the menu from My VA, it still shows as overlaying over the homepage. Can we make it so clicking the menu from My VA overlays over My VA?
