### ISSUE TITLE
[Research] Optional Notes Character Limit (step 3 of 6)

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1919]
## User Story or Problem Statement
As a researcher, I need to understand if there is a character limit for optional notes on the Higher-Level Review form so I can determine the size and type of the Optional Notes field.

## Definition of Done
- [x] Confirm the character limit for the optional notes field
- [x] Review condition listing pattern and update designs as needed
- [x] Remove icons at the bottom of the screen and consider adding an informational alert at the top of the form
- [x] If needed, update designs and post revision in Comments
- [x] Request content review from VSP (Yana create a ticket and assign Peggy Gannon)
- [ ] _ *This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
<img width="422" alt="HLR-3of6-Add_Notes" src="https://user-images.githubusercontent.com/54544300/65259425-a653ae00-dad2-11e9-90ab-70b9cf0485a6.png">

**Comment by rileyorr** [comment]
@YanaRoy @Mottie I've created new mockups for the overall 'Contested issues' user flow that also shares aspects with #1915 
The mockups can be found [here](https://vsateams.invisionapp.com/share/W5U21BDFTQK) under the 'Contested Issues' section header.
My new user flow resulted from comparing patterns to the current 21-526EZ application process. In that process, Veterans select the disability(ies) they want to claim and are prompted with questions for each disability. Since each disability rating could have been determined at a different office, it makes sense to follow a similar pattern for each contested issue. I decided to include the optional notes question in the same screen since it pertains to that specific issue. 

In the paper Higher-level Review (VA Form 20-0996) there is no section for notes to be submitted, but the Veteran is able to attach additional sheets. I noticed that similar 'notes' patterns on VA.gov's forms contain a 400 character limit, so I added that restriction to this form. We will likely want to validate this with user testing, since I couldn't find any research about how many sheets of paper are typically attached with notes about each contested issue. LMK feedback or if you have any questions!

**Comment by rileyorr** [comment]
@kevinstachura @carolynwill If either of you have time to review these mockups and give me feedback that would be fantastic! Commenting on the Invision mockups would be perfect!

**Comment by rileyorr** [comment]
@peggygannon @meganhkelley Requesting content review. Thank you! :)

**Comment by peggygannon** [comment]
@rileyorr The screenshot above is different than the one that appears in the HLR mockup I reviewed earlier this week (https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/386837701/comments)

can you tell me which screen is the most up to date? 

cc @meganhkelley @YanaRoy

**Comment by peggygannon** [comment]
Hi, @YanaRoy the screenshot above is out of date. I have provided content recommendations to the HLR mockup, via this issue. https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2011

As such, I think this issue #1919 can be closed. 

cc @meganhkelley
