### ISSUE TITLE
[Design] Time Periods rule 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#1920]
## User Story or Problem Statement
As a claimant, I need to identify the best day and times that work for me to have an informal review so I can communicate this in my form without any chance of error.

## Goal
_Create a user friendly way to select day/time for informal review_

## Acceptance Criteria
Scenario: System user wants to select time-frames of availability for informal review
- GIVEN the system user has confirmed their contact information
- WHEN the user moves forward in the HLR process to the Request an Informal Conference
- THEN the system will prompt the user to select if they want to request an informal conference
*and* select if they want VA to contact their representative
*and* select up to 2 time periods when they are available to schedule their informal review
*and* confirm the number of attempts the VA will make to reach the user
*and* user can click the Continue button
- THEN the system moves the user to the next page of the HLR process

## Definition of Done
- [x] Identify current design issue
- [x] Identify design of proposed solution for displaying time periods
- [x] Request content review from VSP (Yana create a ticket and assign Peggy Gannon)
- [x] _*This relates to epic ticket #1053 *Check the box below when this has been completed and comment "done"._

## Screen Shots
see below for latest

**Comment by rileyorr** [comment]
@YanaRoy @Mottie My mockups can be found [here](https://vsateams.invisionapp.com/share/W5U21BDFTQK).

I spent a lot of time comparing the mockup I was given to the paper [form](https://www.va.gov/decision-reviews/forms/higher-level-review-20-0996.pdf),  so many of my edits were to ensure the Veteran knows that the time and day selected not for when the informal conference will take place but rather when the VA will contact them **to schedule** the informal conference.
Additionally, I worked on the page's flow to align with current VA design patterns. I mostly compared the design to the Household Information section of the 10-10EZ form, since it requires a similar flow. When a Veteran selects a radio button that results in additional input, a light blue line animation occurs to guide them through the page. It's called ".form-expanding-group-open". 
Additionally, I did not see any checkboxes organized both horizontally and vertically in other forms, so I reorganized them to only display vertically. This will also work better with responsiveness in mobile. LMK your thoughts!

**Comment by rileyorr** [comment]
@Mottie Kevin Stachura just made a great point - so the users are only meant to choose up to 2 time slots. I'm unsure how much technical discovery occurred during the original design, but I was wondering if you know if that's possible to implement. I'm also going to add another screen showing the error message that would occur if the user selects more than two options.

**Comment by rileyorr** [comment]
I've added a screen displaying a potential error message the user would see if they selected more than 2 time slots.

**Comment by rileyorr** [comment]
Update: going to be speaking with someone from the Appeals team about this form and scheduling informal conferences so we can try to tackle how to create the best user experience for scheduling the conference. Going to be creating more iterations soon

**Comment by carolynwill** [comment]
Blocked due to InVision access.

**Comment by Mottie** [comment]
I just merged step 3/4 (this page) into the master. It should be available on staging with the next release (Monday?). The new design no longer has the day of the week selector, so I guess we can close this?

![](https://user-images.githubusercontent.com/136959/67985326-9d3c1d80-fbf6-11e9-9c49-b319926d41ae.png)

**Comment by YanaRoy** [comment]
@Mottie are you saying this does not need a content review? if so, why?

**Comment by Mottie** [comment]
Nope, just saying we don't need to worry about the weekday selector, since I guess a decision was made to not include it. And the image at the top of the page does not match the current design.

**Comment by YanaRoy** [comment]
Content review requested

**Comment by carolynwill** [comment]
Opening this ticket back up so that the revisions for this work are tracked. 
Flow begins here with Step 3.
https://vsateams.invisionapp.com/share/8JUSQKTUM76#/388976567_Default

**Comment by Mottie** [comment]
Closing in favor of #3382.
