### ISSUE TITLE
STEM Automated Denial: Research Roundup

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#19277]
Scan past research on Claims & Appeals  
Identify relevant findings & requests for new functionality 
Capture in easy-to-digest format 
Share with team & discuss

**Comment by amyknox** [comment]
Claims Status research links

**HELPFUL >>** Claim Status Tool Mapping: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/claim-status-tool-mapping.pdf

**HELPFUL >>** Survey of Previous Research 2016 - April 2020.  Not a lot of research, as it turns out, but some good links in this document.   https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/April-2020-dicovery-concept-usability/Previous%20Research%20Claims%20Tool%20.pdf

Claims Status Tool Research Readout - July 2020 https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/research/summary-CST-research-July2020/Claim%20Status%20Tool%2C%20Research%2C%20July%202020.pdf

NOTE: design files are in lower-level folders like "claims-status/track-claims-status" 


These may or may not be helpful

* Claim status flow https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/claims-status/file-claim/claim-status-logic.pdf
* Co-Design Mural
https://app.mural.co/t/vsa8243/m/vsa8243/1593457458758/027fcf7f9739e42018a3d5f4d9fd2222d59dacd7
