### ISSUE TITLE
[Research] Backend error handling for CARMA submission timeouts

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#19441]
When a timeout error occurs between the backend and CARMA, it is unclear whether:
- Submission was successfully received by CARMA
- Submission was not successfully received by CARMA 
- Submission was successfully received by CARMA without attachment

Options to investigate:
- Query CARMA with submission ID to check the status
  - Not receiving the case ID back on timeout errors, may be a constraint.
- Have CARMA publish to an event broker that we can subscribe to
  - This will allow us to send PDFs regardless of whether we receive a response to the submission request.
- Process the submission with a background job and have the front-end poll for the status
  - This will allow us the reattempt the submission when a network error occurs
  - Would result in duplicate applications, but the user would have a success status
- Admin dashboard to handle and report on erroneous submissions

A/C
- [ ] Investigate options to determine submission status
- [ ] Create backend implementation tickets
- [ ] Create frontend implementation tickets

**Comment by kevinmirc** [comment]
An intermediate solution to the timeout error could be rendering a specific message to the user that lets them know the application may or may not have gone through, and provided explicit next steps.

For example:
> :warning: **There has been a network outage.**
>
> Our systems experienced a network outage when your data was submitted. It is unclear if your application was processed successfully.
>
> You can call the Caregiver Support Line to confirm that your application was received, or submit another application.
>
> You can reach the Caregiver Support Line at 855-260-3274, Monday through Friday, 8:00 a.m. to 10:00 p.m. ET, and Saturday, 8:00 a.m. to 5:00 p.m. ET.

**Comment by kevinmirc** [comment]
Since we have to manually handle these right now (gather and report), and there is no clear cut solution I suggest we make an internal dashboard where we can see a complete list of these erroneous submissions and have ways of handling them with a click of a button (add the case id, re-submit, re-send the attachment, export (with claim IDs and veteran name, etc).

The pre-requisite to this is saving the claim in the database before attempting to send it to CARMA, whatever records are dormant or pending can be viewed and handled from this dashboard.

**Comment by ala-yna** [comment]
Closing this out - we'll be pausing on any more work to address the timeout issue until CARMA does more investigation into what's causing the issues, and how to resolve them.
