### ISSUE TITLE
Investigate and document an alternative tracking approach

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#19451]
## Issue Description
It was discussed that a proxy sinatra (middleware) app may be the solution needed to send metrics to Datadog for vtk tracking purposes. 

---
## Tasks
- [x] Document current approach and caveats in [Confluence](https://vfs.atlassian.net/wiki/spaces/VI/pages/557416547/Backend+Tools)

**Comment by ericboehs** [comment]
We're wanting to track command usage in `vtk`. Each command ran will increment a counter unique to the command (but not the individual who ran it). Currently, we have two external options for tracking that I'm aware of: Datadog and Google Analytics.

We talked with our analytic team and they said GA wouldn't be a great fit for our use case. We may want to revisit this since we're having to do workarounds for Datadog.

The primary issue we're facing is that Datadog doesn't allow client tokens to report metrics via their API. Their RUM and Mobile SDK somehow does but I'm not sure how. Perhaps a good step would be to contact Datadog and see if there's something that I'm doing wrong.

Since we're unable to use client tokens, we'd have to use our private API keys which we can't package with our open-source gem. To circumvent this issue, a middleware app could stand in between our clients and Datadog to allow for submission of these metrics without revealing our private API key.

In order to do this, we'll need a public facing endpoint available for our clients to access. This middleware would ideally be an independent application rather than an extra endpoint on vets-api as this functionality seems completely out-of-scope of something vets-api should handle. Since our applications should be hosted within our TIC, we'd need to add a rule to our revproxy to allow this endpoint to be accessible. Our production revproxy is "va.gov" which would mean our endpoint would be something like va.gov/cli-analytics/record. Demian suggested we use dev.va.gov as this is what we're using for our PACT broker. He also would like to get a tools.va.gov subdomain provisioned for stuff like this.
