### ISSUE TITLE
Review allow-list link validation proposal from CMS team & provide LOE

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#19462]
## Details 

Discussions are ongoing about link validation and its role in the content build - should links be validated upon every build, and should broken links be blocking? 

On 2/5/21, CMS team proposed a threshold idea where the content build would not be blocked unless there were > X number of broken links found. However, upon further discussion, stakeholders presented an idea of an allow list or inclusion list — a set of URLs, file paths, etc, where broken links would be fine. 

Current proposal - re: allow list/inclusion list - needs to be reviewed by VSP and we need to tell CMS & VFS teams what the level of effort would be to implement that proposal. From there, we can determine priority of the work. 

## Links

https://dsva.slack.com/archives/C01512KN35G/p1611954086246300

## Acceptance Criteria 

- [ ] Confirm that the proposal is clear, ask questions as needed, etc 
- [ ] Provide feedback as applicable to CMS team on proposed implementation 
- [ ] Determine tshirt size level of effort from VSP to implement

**Comment by mchelen-gov** [comment]
path for broken link checking:

https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L157

https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/glean-broken-links.sh#L12-L13

https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/build-content.js#L33

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/index.js#L277

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/index.js#L16

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/check-broken-links/index.js#L39

https://github.com/department-of-veterans-affairs/vets-website/blob/07edee371d66bf5a029635fccc72185047854a08/src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/applyIgnoredRoutes.js

https://github.com/department-of-veterans-affairs/vets-website/blob/07edee371d66bf5a029635fccc72185047854a08/src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/getErrorOutput.js

**Comment by k80bowman** [comment]
For an overall t-shirt size, I would give this a L to XXL depending on the direction we go.

There are two ways we can accomplish this. One way I feel gives us more flexibility to improve this functionality in the future and would make it easier to break the work up, however it is a bit harder. The other way is easier to accomplish and gets us the bare minimum, but would require that we do the work all at once instead of breaking it up.

**Option 1: Breaking the work up**
For this option, we would break the work up into two pieces (maybe even three). This option could go into the XXL territory for overall size, depending on whether we do part 3.
1. Indicate which broken links are allowed (Size: M)
  - Add a new helper to the [check-broken-links functions](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/check-broken-links/index.js) that will determine if a broken link is allowed and add an indication of such to the broken pages object. How this is done will depend on the format for the allowlist. Will we be getting URLS? File paths?
  - In [getErrorOutput.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/getErrorOutput.js) make sure that the log output indicates which broken links are allowed. We still need to print them (we can't just exclude them from the list the way we do with broken links for react pages), but we need to have some indication that these are on the allowlist.
    - The output should change in a way that this indication is an addition to the current output format, so that it doesn't make any functional changes. We still need the bash scripts that run as part of the Jenkins build process to be able to read the logs and detect how many broken links there are (without making any changes to that code yet), and the allowed links need to be included as part of that.
  - Add/update tests to validate
2. Detect allowed broken links as part of the Jenkins build process, change the build failure to only happen if the broken links are not on the allowlist, and add new Slack report for broken links that are on the allowlist. (Size: XL)
  - For this, we are going to need to write a bash script to parse the broken links from the log file (currently pulled from the log file and saved as a CSV - this could remain the same, could be changed depending on what works best for implementation) and determine which ones are allowed and which ones are not.
    - From what I understand, the original idea behind saving this information as a CSV was to be able to attach that file to a Slack message. However, we do not have the ability to attach files to Slack messages, so if it works better to alter that step, it might be a good idea. We still need to figure out some way for the CMS team to be alerted as to which links are broken, though, and whether or not they are allowed. Right now they just get a Slack message that tells them how many links are broken and they have to go digging to figure out which ones.
  - Update the build failure to only happen when broken links are not on the allowlist
    - As part of this task, we may also need to go into [check-broken-links/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/47befb1ecccace92d0f69b0bdc089a42f1c67ee0/src/site/stages/build/plugins/modify-dom/check-broken-links/index.js#L44-L46) and change the drupal build to only fail when broken links are not on the allowlist as well.
  - Add new Slack alert for broken links on the allowlist. For now this can probably mimic the current report that shows only the number of links failing.
3. (optional) Work with the CMS team to figure out an easy way to report which broken links are failing and whether or not they are on the allowlist. (Size: probably M)
  - Since we can't attach a file to a Slack message, we need to find a better way of getting the CMS team the information they need.

**Option 2: All in one Go**
Size: L
- In the [check-broken-links functions](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/check-broken-links/index.js), add functionality to separate out the allowed broken links from the full list of broken links. Print two separate lists for these in the logs.
  - update/add tests to validate this change
- Change the checkForBrokenLinks function in the Jenkins build process to detect and save both lists separately.
- Add a Slack message for when broken links on the allowlist are found
  - this can probably mimic the current report that shows only the number of links failing.
- Verify that the build now only fails when broken links not on the allowlist are found
  - As part of this task, we may also need to go into [check-broken-links/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/47befb1ecccace92d0f69b0bdc089a42f1c67ee0/src/site/stages/build/plugins/modify-dom/check-broken-links/index.js#L44-L46) and change the drupal build to only fail when broken links are not on the allowlist as well.

**Open Questions**
- For the allowlist, will we be getting URLs? File paths?

**Concerns**
- Changes to the allowlist could cause problems with the daily deploy if they are merged right before that happens. I'm not sure how we would enforce this, but it would be good if any changes to this list could be merged after the daily deploy so that if there are problems we have time to resolve them before the next day's deploy.

**Comment by k80bowman** [comment]
I want to make sure we keep a link to this Slack thread with discussion about this card here, for context.

Also, there are a couple of additional things @mchelen-gov would like for us to address as part of our work on the broken links code in general.

1. Send a warning message in Slack when we have broken links on staging (in addition to the failure message for prod).
2. Find a way for the Slack alerts to include a list of the broken links, either as a file or text. (I've looked at addressing this as part of an optional step 3 in Option 1 above)

**Comment by mchelen-gov** [comment]
> 2. Find a way for the Slack alerts to include a list of the broken links, either as a file or text. (I've looked at addressing this as part of an optional step 3 in Option 1 above)
@k80bowman i think this PR accomplishes this (still prod only): https://github.com/department-of-veterans-affairs/vets-website/pull/16008

**Comment by k80bowman** [comment]
@mchelen that's awesome. Is that what you were testing here? 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/12739849/108091104-5b342680-7049-11eb-953b-22870c48d8d5.png">

**Comment by meganhkelley** [comment]
Closing ticket, future research & estimates will be tracked separately.
