### ISSUE TITLE
Discovery for Not Authorized States

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#19533]
Not all services are authorized for all Veterans. 

What should the UI be for screens like Claims and Appeals, Appointments and Letters look like if a user is not authorized to use them?
Should the app skip making the api call if a service is not authorized.

**Comment by lexicalninja** [comment]
Here are the screens when I log in with my account in production that is not authorized for these services

![Screenshot_20210204-151131.png](https://images.zenhubusercontent.com/5f60e9930170febc016f0a50/c8afe3d7-e8d3-4c84-8c1b-b13fe28302ce)

![Screenshot_20210204-150954.png](https://images.zenhubusercontent.com/5f60e9930170febc016f0a50/b260c24a-1eb1-4111-a6e3-02ffe41a233d)

![Screenshot_20210204-151015.png](https://images.zenhubusercontent.com/5f60e9930170febc016f0a50/74849671-8080-4d99-9414-d819b38fb20c)

**Comment by bridgethapner** [comment]
Thanks for making this ticket @lexicalninja! 

I added the tags **backend** and **product** because we need to do discovery here - this isn't ready to go into UI yet. Here are all the questions I have (capturing for future investigation - don't have the capacity rn) -- we'll need to take some of these to Steve for guidance: 

- What does it mean to be unauthorized - is something missing in MPI?
- Do we know roughly how common it might be for a user to be unauthorized for each of the places we need an error? This would be really helpful to know in defining the UX. 
- Is there anything we can learn or borrow from VA.gov error messaging for Claims, Appeals, Profile, Appointments, or Letters?
    - Is this a complete list of places we need an "unauthorized error"?
    - If not, what else needs an error?
- What steps, if any, can a user take to get authorized?
- Is there **anything** (phone, link) we can offer to avoid these errors being a "dead end"? 
- What are the implications of skipping the API call? Is there a specific error code that will be associated with these errors or not? If not, what's the logic for when these errors display?

**Comment by lexicalninja** [comment]
#### What does it mean to be unauthorized:

A user cannot see or update data from a service. An example of how we already handle this is with Direct Deposit. If a user is not authorized to the DD service, we hide the DD option in profile.

A user cannot take steps to get authorized, they need to interact with the VA by sending in a claim, getting a claim granted for DD, or interact with the VA Health side in some way. The authorization comes when the VA does something with the Veteran like make an appointment or CEST a claim, etc. None of the statuses we currently use can be updated with a call to the call centers or an IRIS. 

We should have some way for them to avoid the "dead end" you called out in case a user might just be missing something and their profile is not showing what it should. Not sure what this should be, but you are 100% right that it should not just be sorry, no service.

Skipping API calls is to avoid hitting endpoints we know will return a `403 Forbidden` error. If the profile indicates the service is not authorized, any call to that specific service will be an error and there isn't a reason to hit the end point. 

I also need to point out that being unauthorized is not an error, per se; it is likely correct that a user doesn't have access to some of these services, depending on what they use VA for. I don't know if that is an important difference for us as we build the app, but we should understand that it isn't necessarily some fail state.

**Comment by bridgethapner** [comment]
Thank you for all this info! 

**A user cannot take steps to get authorized, they need to interact with the VA by sending in a claim, getting a claim granted for DD, or interact with the VA Health side in some way.** -- Knowing this, in our app, it seems like we can explain this and direct them to VA.gov to apply for benefits or health care ("e.g. You can use Claims in VA Mobile after you have filed a claim with VA. You can find information about filing a claim here [link to VA.gov page for filing a claim]"). That seems like it would be useful. 
- Does the relationship between unauthorized and unenrolled track 1:1?
- If so, should we be thinking about these as unenrolled states rather than "errors"?
- Should we use the integration to check enrollment status here?

**Comment by bridgethapner** [comment]
@ayushchak This is an area where I need guidance from you and Steve to help define the product feature...I think this "unhappy path" is important to get right before we go to market but need to better understand how VA can support & communicate to unauthorized users.

**Comment by lexicalninja** [comment]
> * Does the relationship between unauthorized and unenrolled track 1:1?

I am not sure I understand what distinction you are making here? What does unenrolled mean in this context? 

> * Should we use the integration to check enrollment status here?

My suggestion is that we not hit APIs that are marked as unauthorized in their profile. We should program defensively around this, since we know it will return an error from the api. If we know a service is not authorized we should avoid hitting an api endpoint we know will return an error. It is safer to handle it with stateful UX rather than hit the API and not be certain what error or content comes back from the service.

**Comment by bridgethapner** [comment]
I'm trying to understand if there's a relationship between unauthorized and the action a Veteran might take IF they are unauthorized. Understanding this will help us offer a meaningful & useful experience. If the way a Veteran becomes authorized is to interact with VA, I'm curious if we want this unauthorized state to display information that's helpful in taking the first step. If that is the case, it seems like there's an overlap between unauthorized and unenrolled.

I think it's super helpful to step back and define this feature clearly, especially after testing last week -- seeing that there are many unhappy paths we need to think about, I want to make sure we're understanding the how/what/why for each unhappy path clearly so we can develop the most helpful and context-aware corresponding UX.

**Comment by bridgethapner** [comment]
Here are some screenshots of the states on VA.gov for health and claims when a user doesn't have any: 

# Health
![Screen Shot 2021-02-08 at 4.46.37 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/1633f846-57dc-494f-8084-ec5e0555f948)

# Claims
![Screen Shot 2021-02-17 at 8.39.13 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/20375a8c-38dd-434d-96ad-f97461d942f5)

I'm going to do more digging to see if there's ever an unauthorized state for Claims that is more like the one shared above for Health - there's a lot of words and context and clear next steps in the Health screenshot, I wonder if there's something similar out there for Claims...

**Comment by lexicalninja** [comment]
@bridgethapner  user 1414 should not be authed for anything except profile, I can send you the pw, just message me for it

**Comment by bridgethapner** [comment]
I think we need 2 new screens to meet this requirement: 1 for Claims and 1 for Appointments/Secure Messaging that block access to those sections of the app when a user is not authorized to use those services and replicate the content shown in the web screenshots above. I started a Mural to track screenshots and content for this plus any other "unhappy paths" or errors we want to offer a unique state & next steps for - I'm going to close this ticket in favor of #20017.
