### ISSUE TITLE
App startup | Home screen buttons - accessibility issues

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#19575]
## What happened?
On the Unauthorized Home page:

1. The **Sign In** button lists accessibility labels as follows:
accessibilityLabel= “VA button” (incorrect)
accessibilityRole= "button" (correct)
accessibilityHint= _None added_ (incorrect)

2. The **Find a VA Location** button lists accessibility labels as follows:
accessibilityLabel= “Find a VA location” (correct)
accessibilityRole= _None added_ (incorrect)
accessibilityHint= _None added_ (incorrect)

## Specs:
- Device: iPhone 11

## Steps to Reproduce
Enable screen reading software (Talkback, Voiceover) and read the "Sign In" and "Find a VA Location" buttons on the Unauthorized Home page. 

## Desired behavior
1. Accessibility labels for **Sign In** button:
accessibilityLabel= “Sign In”
accessibilityRole= "button"
accessibilityHint= "Continue to the sign in page"

2. Accessibility labels for **Find a VA Location** button:
accessibilityLabel= “Find a VA location”
accessibilityRole= "button"
accessibilityHint= "Go to VA facility locator"

## Acceptance Criteria
See description.

## Bug Severity
- 4 - Low

## Linked Story
N/A

## Screen shot(s) and additional information
N/A

**Comment by digitalken** [comment]
FAIL - 2/11/2021 - The iPhone is not picking up accessibiltyRole = "button" on the 'Find a VA Location' button.  Other fixes seem to be OK and it is ok on Android.  (Making a new bug for Android on saying "Vaw" instead of "V" "A" for this button.
(new bug - https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/19830 )

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/2db4b8ce-19ef-4b67-9023-402567698753)

**Comment by digitalken** [comment]
PASS 3/4/2021 - Sounds good on iPhone XR.  Closing.
