### ISSUE TITLE
Discovery on Improving CMS Export Build Times

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#19612]
## Details 

In tests run as part of #18592, we have learned a lot about what parts of the build pipeline are taking the most time. 

The purpose of this ticket is to investigate ways that we could decrease build times (specific to CMS Export). 

From meeting on 2/5 [link to notes](https://docs.google.com/document/d/1gCGcU-Y-2HL7rxX9pcjNlf3JSOx8CJlfGv_zlx0QvoA/edit#), there are 3 options to look at off the bat: 

* Update asset URLs as part of Drupal export rather than as part of build pipeline 
   * Look into — what would this mean for transformers? Approximate level of effort for updating transformers accordingly? Also approximate level of effort for updating build pipeline
   * CMS Team says this could be done in Drupal — what’s the LOE for them to make that change?
* Get rid of the build step that runs in the pre-archive stage 
   * Look into this, figure out what it would mean and if it’s a valid possibility. 
   * If this is a viable option, what needs to happen in the build step to make this possible? 
* Local build times - for CMS Export we are not using local cache/not in the same way we use it for GraphQL. Look at local build times specifically to make sure we can speed that up for people.

**Comment by k80bowman** [comment]
I've analyzed the build process and talked with several people to come up with a list of recommended efforts to speed up the build process. The first two would get us the most gains in time for smaller amounts of work.

For the sake of clarity, I am also providing a list of things I looked into, but decided to not recommend and why.

## Recommendations
### 1. Refactor the `convertFilesToDrupal` function that runs as part of Step 3 in the build process
We need to look at optimizing the `convertDrupalFilesToLocal` function in `src/site/stages/build/drupal/assets.js`. This function currently takes around 30 seconds to run, but by the time we get to ~12,000 nodes this one function could take an estimated 15 minutes to run.

There are two places to look at optimizing this function.

First, @cvalarida suggested replacing the use of “cheerio” in the `convertDrupalFilesToLocal` replacer function provided to `replacePathInData` with regex to see if that offered any speed improvements. 
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/04dfc135-c58d-4397-8a69-0691598dad0b)
[Slack thread](https://dsva.slack.com/archives/GLDNCMRSP/p1613069711083800?thread_ts=1613058694.076100&cid=GLDNCMRSP)

Second, the `replacePathInData` function itself is recursive and goes through the full set of drupalData. Dror has suggested that we may be able to limit what data goes through the recursion, but we will need to dig in and see if that is possible, or if there is a better way of completing this operation that would allow us to get rid of the recursion altogether.

### 2. Work with the testing team to re-think testing strategy
Running the Cypress, accessibility, and end-to-end tests on every Jenkins build takes about half an hour. We understand that we need to make sure that the tests are passing, especially since we have an automated deploy that goes out every day. But is there a way to decouple the testing and the build process at least partially? What if we only ran the tests as part of the Jenkins build on PR builds? That could help us speed up the build process for the deploy (and for any difficulties we have in getting the daily deploy out)?

### Additional Optimizations to Consider
#### Optimizing Step 29: Parse a virtual DOM from every .html file and perform a variety of DOM sub-operations on each file
@ncksllvn had some comments on this in [Slack](https://dsva.slack.com/archives/C01512KN35G/p1613498894310500)
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/b256f2d4-915a-434e-b45c-ec62b965f13f)

#### Parallelization
This is a theme that has come up several times. Nick brought it up above and Chris Valarida [brought it up with relation to optimizing Step 3](https://dsva.slack.com/archives/GLDNCMRSP/p1613066124081900?thread_ts=1613058694.076100&cid=GLDNCMRSP). It could help with build performance. Depending on how and where we implement it, it could also increase the amount of memory we're using and complicate our already complicated build process even further. If we were to move forward with this, though, I would recommend putting together some kind of parallelization strategy first.

## Other Options Considered
#### Removing build step from the Prearchive stage
As part of the Jenkins build, we complete the site build process twice, once as part of the Build stage before the Integration testing stage and then again as part of the Prearchive stage. It was mentioned that maybe we could remove the build step from the Prearchive stage and save ourselves a little time, but I found out that this would not work.

According to @timwright12, we run that first site build so that we can run the tests, but for the Cypress tests to work we need the links to be local. We run the second site build as part of the Prearchive stage in order to point the links to S3, which helps us to then get the content-only build working (please correct me if I've misinterpreted any of that, Tim).

#### Maintaining a Cache on the Drupal Side
I talked briefly with @indytechcook about this, but I didn't follow up too much because it would only save us a couple of minutes of build time (which seems like a lot, but when put up against refactoring Step 3—which could save us 15 minutes by the time we hit 12k nodes—it's not that much). Apparently there is no caching on the Drupal side for the CMS Export. The data changes too much, and since it's only json files and we're compiling it all into one .tar file, it's not worth it. We do, however cache the GraphQL queries once a query has been made.

There has been a change here recently that could help with maintaining those GraphQL query caches, though. When we were only using one big query, the cache would be broken for the entire query any time data was updated. However, now we are running a series of smaller queries, so cache only gets broken for the queries with updated data.

#### Refactoring the Apply Layouts step (step 20)
Once we hit 12k nodes, this step could take around a minute and a half, so putting a lot of effort into refactoring this may not be worth it. Besides, it only runs the `metalsmith-layouts` plugin, so if we were to refactor we would either have to find something to replace it or find some way to parallelize the running of this function.

#### Offloading Tasks to Drupal
**Offloading the convertAssetPath function from Step 3**
@indytechcook had said that he could look into possibly shifting part of the functionality of Step 3 over to Drupal. However, we would still have to do the recursion and it wouldn't remove the use of the "cheerio" package. This is something we could look into in the future, but I'm not sure it would save us much, if any, build time.

**Broken Link Checking**
Another recommendation was to see if we could offload the broken link checking process to Drupal. I had a conversation with @indytechcook and @swirtSJW about how the broken link checking works in Drupal and, as things stand right now, I don't think we can do away with this as part of the build process at the current time. However, I do think it is worth taking another look at our broken link checking process as a whole, just maybe not as part of the current effort to improve build performance.

**Comment by ncksllvn** [comment]
For now I think the biggest win would be to use Cheerio in the `Prearchive` step when we are working with the DOM. I think right now it uses regex, and regex is slooooOOooooow. Also, we should make sure to make a Cheero DOM on one file at a time because all of them at once would use like > 7 gigs of memory. But if we could cut this step on down to a minute, we would have a build sitting at less than five minutes.

> 1. Refactor the convertFilesToDrupal function that runs as part of Step 3 in the build process

Not certain on this but since this step relies on Cheerio virtual DOMs, it would be cool if we could make this one of the steps run inside of `src/site/stages/build/plugins/modify-dom/index.js`. It would need to run before the broken link checker so that IMG/JS/ETC sources are evaluated. Then we could just move the call to `downloadDrupalAssets` to after `modifyDom` inside `src/site/stages/build/index.js`. 

> Parallelization
> This is a theme that has come up several times. Nick brought it up above and Chris Valarida brought it up with relation to optimizing Step 3. It could help with build performance. Depending on how and where we implement it, it could also increase the amount of memory we're using and complicate our already complicated build process even further. If we were to move forward with this, though, I would recommend putting together some kind of parallelization strategy first.

Parallelization would be cool, but right now the risk of complexity scares me so I heavily caution against it. The two things mentioned would be way, way easier wins for the time being.

**Comment by k80bowman** [comment]
Thank you for the comments @ncksllvn! I totally agree about parallelization, I wanted to include it because it had come up several times, but it should not be the focus of our work right now. The complexity scares me, too.

And yes, I agree that a big win would be getting the time down on that Prearchive build step, but I think the priority should be that refactor of the `convertFilesToDrupal` function. Moving it might be a good thing to do as part of that process (I think it would make more sense for it to live in the `modify-dom` step), but we really need to get the processing time down on that function before we get 12k or more nodes running through the build process. The prospect of just that function potentially taking 15 minutes to run scares me.

**Comment by ncksllvn** [comment]
Sounds good to me @k80bowman !

**Comment by timwright12** [comment]
We can investigate removing the build from the prearchive step (which would save about 3-5mins), we'll just need to do some work on the asset loading and file hashes again

**Comment by k80bowman** [comment]
Given that we may be sticking with our GraphQL query instead of changing to the CMS Export query process, I've updated my recommendations here to reflect that.

## Updated Recommendations
### Investigate re-organizing the Jenkins build process so that the site build only needs to happen once
This could mean removing the site build from the Prearchive stage. Or this could mean running our tests in a different way (that don't require a separate site build). Either way, it could shave at least 3-5 minutes off of our Jenkins build time.

According to @timwright12, we run that first site build so that we can run the tests, but for the Cypress tests to work we need the links to be local. We run the second site build as part of the prearchive stage in order to set the publicPath in Webpack and make sure dynamic module JS files are loading from S3 rather than va.gov so all the cache settings match on all assets.

There is also the potential to run our Cypress tests without needing the links to be local, which would make it easier to get rid of the site build that runs as part of the Prearchive stage. According to @U-DON "In CircleCI, where we have no direct VA network access, we run `yarn build:webpack —env.scaffold` to imitate the React-based landing pages in order to run Cypress tests and avoid a full build with content. The issue with doing the same in Jenkins is the existence of Nightwatch accessibility/sitemap tests." However, if we combine this work into an initiative to parallelize the Cypress tests (next suggestion) @U-DON notes that it might be worth converting the remaining Nightwatch tests to Cypress ("especially the accessibility/sitemap ones").

### Investigate parallelizing the Cypress tests (and converting the Nightwatch tests to Cypress)
Running the Cypress, accessibility, and end-to-end tests takes about half an hour, so anything we can do to get that time down would be beneficial. Parallelizing the Cypress tests is a good place to start with this.

@timwright12 tried just adding the parallel flag to our current test run but Cypress requires that we use their Dashboard service in order to use the parallel flag.
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/17bc77f9-8f14-4c86-a32b-277bf5ba3d93)

Additionally, if we do this as part of this process convert the remaining Nightwatch tests to Cypress, that could help get us down to only one site build as part of the Jenkins build process (see notes on above suggestion).

### Investigate whether using Cheerio instead of regex could speed up our build time
We have some conflicting reports on whether using [Cheerio](https://www.npmjs.com/package/cheerio) instead of regex for DOM traversal could help speed up our build time.

As @ncksllvn noted above:
>For now I think the biggest win would be to use Cheerio in the Prearchive step when we are working with the DOM. I think right now it uses regex, and regex is slooooOOooooow. Also, we should make sure to make a Cheerio DOM on one file at a time because all of them at once would use like > 7 gigs of memory. But if we could cut this step on down to a minute, we would have a build sitting at less than five minutes.

However, @cvalarida [suggested](https://dsva.slack.com/archives/GLDNCMRSP/p1613069711083800?thread_ts=1613058694.076100&cid=GLDNCMRSP) replacing the use of Cheerio in the `convertDrupalFilesToLocal` replacer function provided to `replacePathInData` with regex to see if that offered any speed improvements.

@U-DON had some good thoughts on how to move forward with this:
>* If you were to look into this, I’d say try to convert one to the other first (whichever seems easier) just to quickly test the impact.
* I would expect Cheerio to be easier to reason about as opposed to regex, and even if it ends up being slower, you still get to confirm that regex would be faster.
* I think the performance tradeoff would really depend on the time it takes for Cheerio to parse the HTML, so the time it takes would likely be proportional to the size of the HTML file.

@U-DON's recommendation to find a place where we can convert regex to Cheerio and test the effect is a good place to start with this. Figuring out the best way to reduce the amount of time it takes to run these DOM-traversal tasks could help us decrease the amount of time it takes to run build steps 3 and 29, two of the three steps that currently take the longest to run.

### Investigate ways we can further improve our GraphQL queries
@ncksllvn's [recent change](https://github.com/department-of-veterans-affairs/vets-website/pull/15974) to our GraphQL queries, which resulted in a massive performance improvement, makes me wonder if there are other things we could be doing to further optimize our GraphQL queries. As we move towards greatly increasing the amount of data we are retrieving and processing, there is still some concern that at some point our GraphQL queries will no longer be able to handle the load. So anything we can do to get out ahead of that would be beneficial.

### Re-thinking our broken link checking process
Currently we are checking for broken links in two places: inside Drupal and as part of the Jenkins build process.

The link checking that happens inside of Drupal analyzes both internal and external links, but it has its limitations. It cannot check links that are generated as part of the site build process and, inside of the Drupal environment, it can only be viewed page-by-page.

The link checking that happens as part of the Jenkins build process is able to check links that are generated as part of the site build process and is able to generate a list of all broken links (and report broken links to Slack). However, it happens farther away from the content generation process and puts pressure on the development team to resolve broken links.

It would be good if we could find a way to separate the broken link checking process from the site build and deploy process and move it back closer to the content generation process.

## Additional Optimizations to Consider
### Optimizing Step 29: Parse a virtual DOM from every .html file and perform a variety of DOM sub-operations on each file
@ncksllvn had some comments on this in Slack
![image.png](https://images.zenhubusercontent.com/5952ac1861b4ca3b0a727ca8/4d5c97fe-4c40-4311-a000-f30e8396a2cd)

### Move the `convertFilesToDrupal` function out of Step 3 and into Step 29 (part of the modify DOM process)
This isn’t necessarily related to speeding things up, but it will help clarify the site build process a little. It could also help with consolidating some of the Cheerio DOM manipulating we’re doing.

Note from @ncksllvn on this:
> Not certain on this but since this step relies on Cheerio virtual DOMs, it would be cool if we could make this one of the steps run inside of src/site/stages/build/plugins/modify-dom/index.js. It would need to run before the broken link checker so that IMG/JS/ETC sources are evaluated. Then we could just move the call to downloadDrupalAssets to after modifyDom inside src/site/stages/build/index.js.

**Comment by meganhkelley** [comment]
@k80bowman great info! Can you help me understand the role that Cypress & Nightwatch tests play in the content-only deploy? My understanding is that there are only a couple Cypress tests on anything to do with content generation (I think Michael P-S has some on Facilities' team's templates), and I'd be surprised to learn that there were any relevant Nightwatch tests. This came up in discussions re: content build separation, surrounding whether we need to maintain Cypress functionality in the new `content-build` repo.

But from your info, it sounds like _all Cypress & Nightwatch tests_ are run on a content-only deploy. Correct? 

In that case, I assume content build separation will give us a huge improvement here?

Let's chat more about this when we meet today! 

Also, question — if Nightwatch was fully deprecated & didn't have to run at all, but all those tests had been recreated in Cypress, would that save any time? That is an option, although we would need to coordinate with Testing Team.

**Comment by ncksllvn** [comment]
@meganhkelley No tests except for the broken link checker are run during a content-only deployment, so this wouldn't be a point of improvement for a content build separation. Is there a product outline describing the objectives of that content build separation?

**Comment by timwright12** [comment]
@k80bowman This is great! Thanks for putting it together. I see a couple buckets of improvements here:

1. Macro improvements (big stuff)
2. Micro improvements (small stuff)

**Macro**
While I'm not confident we'll be able to remove that second build completely when we move to content build separation, running cypress on the --env.scaffold might let us rework the pipeline enough to same some time. The largest improvement is going to be parallelization of the Cypress tests, so I think that should be priority 1

**Micro**
As @U-DON mentioned I think it's worth running tests on replacing reg with Cheerio just to get that data. I'm not sure it will made a large dent in the time, but it seems worth taking a few days to test.

Just to clarify the nightwatch tests for content-build separation. They are run on a schedule, so the don't block the pipeline and there are no cypress tests at all. With that, most of these items are applying to the general pipeline, and I think that's a good way to look at this. We can improve them both.

**Comment by k80bowman** [comment]
@timwright12 I completely agree with that assessment. Just to note, though, that the micro changes you mentioned are only micro if we stick with GraphQL. If we decide to move to CMS Export sometime in the future, those changes could become a much bigger deal.

**Comment by meganhkelley** [comment]
@ncksllvn thanks for clarifying! Content build separation is an initiative with a design doc outlining the approved solution. I suspect you've seen that doc but [it is here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2020-04-09-separate-content-build.md).

The content build itself as a product is currently subject to conversations about ownership. Once a long term owner is solidified, that team will be responsible for a product outline including info about long term success.

**Comment by mpelzsherman** [comment]
Thought I'd add a few observations which i hope might be helpful:

1. The Ops team announced at the ToT meeting on 2/16 that "Ops is pivoting away from CircleCI as its primary tool for Continuous Integration, due to some administrative limitations around effective management of security contexts across many projects, in an automated fashion"

2. AFAICT, the purpose of the `convertDrupalFilesToLocal` function is to replace the hostname in the asset links. Have we considered removing the hostname from all of the asset paths at the source (remove it from the graphql output), and populate the correct hostname in the liquid templates instead? That would remove the need for the function entirely, methinks.
