### ISSUE TITLE
Content feedback - Staging review - VAOS community care provider 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#19620]
## User story
VSP content feedback on VAOS community care provider selection feature
Link:  https://staging.va.gov/health-care/schedule-view-va-appointments/appointments/

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for any feedback you decide _not_ to take
- [ ] VFS team closes the ticket

**Comment by peggygannon** [comment]
HI, @outerpress and @laurenernest Please see below my feedback for this staging review. Let me know if you have any questions. 


Must = the feedback must be applied
Should = the feedback is best practice
Consider = suggestions/enhancements

**Questions/Thoughts**

1. Request a Primary care provider. (Optional)
Should this line be rendered as a header?  It gets lost styled as regular text


2. Should (Optional) be rendered in a bold? It’s easily lost with the rest of the questions. 


-------


**Must**
Change this question to the below, as the way the question is worded now,  assumes a yes/no answer. It doesn’t work with the drop down selection box

Do you prefer that your community care provider speak a certain language? Change TO> Select the preferred language for your community care provider


--------

**Should**

Under “Choose a provider** header, I'm recommending the below edit to make it more clear what the provider options are based on. I also recommend bringing up the option of "searching by location" so it's more clear that user choose this option as well. 

You can choose a provide based on your address on file. Or, you can [search by your current location]. 
{address on file}


-----

**Consider**

The following recommendations are opportunities to condense current content even further to be more mobile friendly

  
1. **Choose a day and time for your appointment** Change TO  "Choose an appointment day and time"

Choose your preferred date and time for this appointment You can request up to 3 dates. A scheduling coordinator will call you to schedule your appointment.


2. **Tell us your community care preferences** Change TO> **Your community care preferences**


3. Suggest edits to tighten up the content under **Your contact information**

Edited: 
This is the contact information we have on file for you. We’ll use this information to contact you about your appointment. Any updates you make to this information here, will only apply to this tool. If you want to update your contact information for all your VA accounts, [go to your profile page].


4. Suggest edits to tighten up the content under **Review appointment details**

What do you think about putting this content in an alert box to make it stand out a bit from the instructional content on editing info? 
 (I'm thinking of an example from the Health care questionnaire w/ green check box)

{begin alert} **You’re requesting a community care appointment**
Please review the information below before submitting your request. 
{end alert}

If you need to update any details, click Edit to go back to that screen. If you edit any information, you’ll need to go through the tool again to request your appointment.

**Comment by laurenernest** [comment]
"Must" feedback captured in this dev ticket #19705

**Comment by outerpress** [comment]
@peggygannon I created a new Invision project so we can look at some of these in context: https://adhoc.invisionapp.com/share/F3106OHDSJ9G

I think most of these look great! More detail on some of the trickier ones:

> Request a Primary care provider. (Optional) Should this line be rendered as a header? It gets lost styled as regular text

It definitely gets lost. I tried a couple different treatments with no great solution:
* Making it a header gives it too much weight in the hierarchy, especially since it's optional. It pulls your eye right past the required question. Same problem, if a little less, with making it bold.
* I tried moving the descriptive text ("You can request a provider....")  into an Additional Info component, but that separated the label from the "Add" button too much. It might work underneath the button...
* Bolding just the "(optional)" label as you suggested made the whole thing stand out a bit more, but we're not treating optional labels that way anywhere else, so I'd rather not go in that direction.

I'll keep playing with this. Ideally, there would be one question on this page, the header would read "Request a [TOC] provider" and the explanatory text would be below that. That would clean this up a lot. But I think we're stuck with the closest city/state question.

<hr>

>Under “Choose a provider** header, I'm recommending the below edit to make it more clear what the provider options are based on.

Note that there are a couple other states that modify this. I changed these, let me know if you have thoughts on these tweaks:
* [Sorting by location](https://adhoc.invisionapp.com/share/F3106OHDSJ9G#/screens/444665374)
* [Browser blocked from sorting by location](https://adhoc.invisionapp.com/share/F3106OHDSJ9G#/screens/444665375)
* [Can't find provider](https://adhoc.invisionapp.com/share/F3106OHDSJ9G#/screens/444665371)

<hr>

> What do you think about putting this content in an alert box to make it stand out a bit from the instructional content on editing info?

I'm trying to be really stingy with alerts, only using them when they'll really stand out. We've seen users skip over them in tests. I'd like to see that there's a problem where users aren't reviewing this page before we try to manage their attention here. 

The text changes in that section are great though, as are all the other recommendations that I didn't note above (fyi @laurenernest if you want to add the others to tickets). Thank you!

**Comment by peggygannon** [comment]
@outerpress Hi, thank you for the update! I appreciate your follow up. 

I think the tweaks for the Choose a provider states look good.

**Comment by laurenernest** [comment]
The additional should/consider-related changes are captured in #19841

**Comment by laurenernest** [comment]
"Must" feedback has been implemented. Closing ticket.
