### ISSUE TITLE
[Design]DD4edu: Create Research plan

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#19728]
## Background
Prior to UAT we need to create a research plan.

## Tasks
- [x] Create research plan
- [x] Review with Matt/Samara/Jason

**Comment by sporeboy** [comment]
WIP Research Plan here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/uat/dd-edu-uat-research-plan.md

**Comment by sporeboy** [comment]
Initial draft created.

**Comment by sporeboy** [comment]
@Samara-Strauss @jason-gcio I have the UAT plan set for review... As mentioned, there are no dates; we'll drop those in when we have a firm idea of when we're ready for UAT.

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/direct-deposit/edu-direct-deposit/design/uat/dd-edu-uat-research-plan.md

**Comment by Samara-Strauss** [comment]
Thank you! I will review when I get a chance.

**Comment by Samara-Strauss** [comment]
Re-opening, since no one has had a chance to give feedback to Jim.

**Feedback**

> We're requesting that Perigean recruit Veterans who need to change their direct deposit information for educational payments.

Participants don't necessarily need to change their direct deposit info for edu, they just need to have it in the first place. They can update their info with the exact same bank information they have now, and that should work just fine.

That being said, yes, we need people who actually have access to this feature, and testing will be a waste of time if we can't find this. I have a couple thoughts on this:

- First, we need to double check whether people who get the GI Bill automatically have DD4EDU payments. I think the answer to this is no, but I will confirm.
- Second, I can ask Luke Tickner about pulling a list of veterans who have DD4EDU, and if he/someone is able to do that, Perigean can use that list for recruiting. We've had to do this before with other specific use cases that were outside of what Perigean would be able to adequately screen for.

> In the event that we don’t get any Veterans that meet our criteria, or we can't find any who are comfortable displaying live/personal data, we may toggle the feature “on” to as tiny a percentage as possible, capture a small number of submissions during a "quieter" time of the week, and then revert back to eBenefits while we take some time to validate the small number of naturally gained submissions. With feature toggles we can control access quickly and with granularly. Again, we want to keep the data being collected real and accurate. In this scenario, it may take longer to get the volume of valid VA.gov submissions to 100%, but as our confidence in the new feature increases, we should be able to accelerate to full deployment.

I don't think we should do this. We should run proper UAT so we can see this feature live and troubleshoot issues if they exist, and I think we can do this even if it means having VBA give us a list of veterans.

> Must have for participants

- One that is not on here: they need to have a DS Logon, MHV, or ID.me account and be LOA3, otherwise, we're going to have to wait for them to sign up and verify their identities. Receiving DD4EDU payments does not necessarily mean they have an account to manage things online, since people could update and manage this info in other ways.
- **Do you need to change the direct deposit information for your educational VA payments? (pass = yes)** This is not a requirement. They can update their DD4EDU with their existing bank account information.

> Good to have for participants

I would be clearer about what is required and what is a nice-to-have. Right now, these all sound like nice-to-haves.

**Comment by Samara-Strauss** [comment]
From Luke Tickner on recruiting:

> Good afternoon.  If someone is using a GI Bill benefit other than Post 9/11, they receive a direct deposit for the full amount of the benefit.  This is about 20% of our beneficiaries who use something other than Post 9/11.
>  
> For those using Post 9/11 they receive a direct deposit for the monthly housing allowance (MHA), in most cases.  If someone is on active duty they do not get housing and would not get a direct deposit.  This is a small number.  If someone is going to school less than 50% time they would not get a housing allowance.  This is also a very small number.
>  
> **All that to say I think if you filter on Veterans using the GI Bill, I would expect 9 out of 10 folks on that list are getting a direct deposit payment.** 

So, we should confirm that Perigean can recruit off of GI Bill recipients. **I will leave one of you to check on that**. If they are able to filter participants by GI Bill, we *should* be able to assume they receive DD4EDU payments. However, we should still make sure that Perigean explicitly mentions receiving direct deposit payments for education in their recruiting materials. If for some reason we get people on calls and a bunch of them do not have DD4EDU, then we'll have to go back to VBA for help. This would suck and really push things back, but right now, it seems like we can reliably recruit off of GI Bill participants based on what Luke said. Please let me know if you have concerns with this approach. If so, we can try getting names from VBA.

**Comment by sporeboy** [comment]
@Samara-Strauss @mshea0606 If we want to test the transactional aspect of the DD-EDU feature, we'll need to be sure a change can be made. That's why I put in the stipulation about recruiting people who need to change their DD.

That said, I'm OK if we don't want to test that part of the tool, and I've changed the recruiting requirements accordingly.

I've revised the requirements to reflect other feedback.

**Comment by Samara-Strauss** [comment]
> @Samara-Strauss @mshea0606 If we want to test the transactional aspect of the DD-EDU feature, we'll need to be sure a change can be made. That's why I put in the stipulation about recruiting people who need to change their DD.

It *should* be ok to have them update with the same info, since that still needs to hit the backend, save, and show in their profile. We tested this way for direct deposit for comp & pen, and it worked out just fine, but please feel free to ask Erik or Lihan more about this and whether there is a fundamental enough difference between updating with the same info vs. changing altogether that we need to make this distinction. Tbh, though, I don't think we'd find people who intentionally knew they needed to change that info and had yet to do so. Perigean could ask for that, but since that's the type of thing people would self-select into, I could see that requirement causing a lot of confusion.

**Comment by sporeboy** [comment]
Revisions made to the research plan--convo guide will follow.

**Comment by Samara-Strauss** [comment]
> Success will be measured as 90% of participants can successfully re-enter and submit their bank info

Success is also that bank info successfully saves on the backend and is reflected in the profile.

Otherwise, looks good to me.

**Comment by Samara-Strauss** [comment]
Done! Materials have been submitted to Lauren for recruiting.
