### ISSUE TITLE
Anchor Tags - Product Outline

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#19813]
**Product outline for this effort:**

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags.md

**Comment by jenniferlee-dsva** [comment]
Hi @SKasimow - in the product outline, it would be great if you could document the comparative examples we looked at. Those examples are scattered in different tickets right now. 

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15758#issuecomment-721412929  --> this one is the federal gov't's 508 site example at https://www.access-board.gov/ict/#about-the-ict-accessibility-standards

Also the Whole Foods and NYT examples in this older ticket here: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/15758#issuecomment-721412929

**Comment by jenniferlee-dsva** [comment]
![nyt-deep-link-ux-021621](https://user-images.githubusercontent.com/43381063/108098744-bb2ecb00-7051-11eb-9a6f-13ab4be58619.gif)

**Comment by jenniferlee-dsva** [comment]
![access-board-508-deep-link-example-021621 (1)](https://user-images.githubusercontent.com/43381063/108099863-2331e100-7053-11eb-8e76-068d105d49f3.gif)

**Comment by jenniferlee-dsva** [comment]
Hi @SKasimow - adding a couple mobile interaction examples here for you to add to the product outline. Ryan Thurlwell and I checked out some nuanced edge case scenarios and we both like the NYT  approach which appears both 508- and mobile-friendly. 

https://www.nytimes.com/live/2021/02/16/us/winter-storm-weather-live#about-3500-sea-turtles-are-rescued-from-the-frigid-temperatures-in-texas

### Example - When the icon wraps to the next line in mobile and feedback message appears:

![image](https://user-images.githubusercontent.com/43381063/108742107-5ff35180-7505-11eb-8a7e-d93a7a8154d6.png)

### Example - when the icon fits on same line but is at the max line length in mobile - feedback message appears to the left of the icon (rather than to the right of it: 

![image](https://user-images.githubusercontent.com/43381063/108742695-f758a480-7505-11eb-9c52-1f3401e375d5.png)


### Example - focus state: 

![image](https://user-images.githubusercontent.com/43381063/108742886-3981e600-7506-11eb-9a5b-4f58320168f7.png)

**Comment by SKasimow** [comment]
Got it - thanks! 

I'll also add to the design ticket.
