### ISSUE TITLE
RFC - deprecate lodash 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#1983]
# Overview 

lodash/fp has some performance issues. determine if we should deprecate lodash as a common utility, if we should move to another version of it, or if it should be an optional dependency

**Comment by meganhkelley** [comment]
@rianfowler is this something we should pick up work on/start actively looking into?

**Comment by theodur** [comment]
@meganhkelley Not sure if this ticket is for `lodash/fp` specifically, or `lodash` as a whole. If it's the former, we can close this as well, since the work for it was completed from https://github.com/department-of-veterans-affairs/va.gov-team/issues/1678. I don't think there's the need to remove `lodash` right now, especially since we removed `lodash/fp`.
