### ISSUE TITLE
Design Request - Anchor Tags

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#19867]
## Story:

As a Veteran or VA call center representative, I'd like to provide someone with a link that opens to a particular question/answer within an accordion or outside of the accordion on the "Coronavirus FAQs: What Veterans need to know" page.

Link: https://www.va.gov/coronavirus-veteran-frequently-asked-questions/ 

(Please review epic for more details and examples)

##  Additional Info:

(Jen L)  Notes from  1/29 design council call:
Since we are thinking of only testing this affordance/ux out on one page, for now, no conclusions or specific approval or no approval. A few design feedback however: ppl prefer the simpler persistent behavior over the more complex hide/hover-show; also, instead of using this for the H2s, use it for the H3 question text, since it's the questions we want to provide users deep linking to.

**Comment by laurellawrence** [comment]
I have 2 design directions for us to go in and have both mocked up in a UXPin here: https://preview.uxpin.com/c24f0ec63fcc859b8eebaacad860a0d968bc3d45#/pages/136426835/simulate/sitemap

There's been alot of discussion lately as to what gets styled as a link or a button so I've started a discussion in the #design slack channel for feedback. 

After an anchor link is pressed, the text should be switched from "Copy to Clipboard" to "Copied to Clipboard" as well as the link icon be switched out for our circle checkmark icon to indicate "link copied success" to the user. 


<img width="292" alt="Screen Shot 2021-02-12 at 1 51 07 PM" src="https://user-images.githubusercontent.com/75386943/107815759-6e897e00-6d39-11eb-8dac-4415c3a53482.png">
<img width="292" alt="Screen Shot 2021-02-12 at 1 51 00 PM" src="https://user-images.githubusercontent.com/75386943/107815761-6f221480-6d39-11eb-853a-a97dd6515800.png">

**Comment by sshein** [comment]
@laurellawrence here are the notes from the design system council meeting:

Jen
Coronavirus - have ability to give someone a deep link.  Contact center and media people can do that in an accordion. Can share deeplink in an accordion question. They will land on the question with the accordion open. Want to be able to share more easily. 
Hypothesis - people at VA and Veterans will share more content if they are able to share more deep content. Don’t want to roll out right away. Want to test, do this on the coronavirus FAQs. Chose page b/c this is place where there were a lot of requests. This page gets up to 7k-8k unique views in a week. Implement something and see data to see what engagement is. Are people really using this? If not, don’t have to roll out sitewide. IF using, then do deeper dive into how to incorporate into content. 


Shawna
Is proposal to try out deep links in accordions? 

Jen
NYT does share deep links in H2 headers mostly on coronavirus. Most people may not notice that URL changes in H2 sections. Only when used as TOC jump link. Not sure if it happens on our site when not part of TOC jump link. Could be useful since our pages are quite long. 

Kevin
Question curious about. Behavior you’re looking for is share? 

Jen
It is share but also how many people click on it. We don’t know how they’ll share or who. It would be click engagement and could see incoming traffic. Already seeing that through FB shares. Could see through link ID. 

Kevin
Adding something to DS that would allow you to create deep link capability for anything you need. Light UI. 

Jen
Not request. Make us aware. Not sure if they want to implement everywhere. Want to implement on coronavirus to see if 1. It is used and 2. It doesn’t overwhelm people.  If used, what are next steps to roll out more broadly. This is a capability public affairs team at VA has been asking for. 

Kevin: 
What do developers think? 

Jen
Would want something where always exposed and actually copies deeplink for uesr. 

Kevin
Since current FAQ page has a lot of inks

Jen
When this page launched, it went w/o any accordions b/c went out with small set of questions but it has grown b/c pandemic has affected every area. Handful of questions were the top that users want. Didn’t want to hide important questions people are constantly looking for. Those are not in accordion. So it’s more easily sharable. If deep linking in accordions were to work, could imagine a few things happening on this page. Important questions get into an accordion. 
IF we want to do mix of links in accordion content and H2s is that bad? 

Brooks
Don’t want to click on another thing in the accordion to -- indicate there is a way to copy content. 
Click on header - indicate this is linkable thing. 

Kevin
Blend of UI presentation results in the necessity for a blended approach to link affordance. 
You’ve put good thinking into content prioritization around what questions are not expanded / not in accordion and which are in accordion. Want same UI for all of this (behavior). 

Jen
IF we experiment for accordion questions, should also include for questions not in accordions. H3s. 

Kevin
Propose experiment of deep links only H3s. Those are the questions. 
If we do something on design.va.gov -- is it something in the DS? Not sure it is. 
Given the mixed blend of presentation on FAQ page, it would better to explore H3 share. Have hover solution you could try.

**Comment by sshein** [comment]
Don't think it's here in the notes, but also in the chat we discussed how a hover over affordance and just an icon for copying would not be ideal

**Comment by laurellawrence** [comment]
@sshein - thanks for filling us in on the background of this. Based on this information and feedback in the design slack thread, I've updated the UXPin mock to include these changes: 

- Text for CTA is now "Copy link to section"
- Styled this as a link since this isn't a primary action on the page
- Moved this link so it is underneath each FAQ accordion heading H3, left aligned

https://preview.uxpin.com/c24f0ec63fcc859b8eebaacad860a0d968bc3d45#/pages/136426835/simulate/sitemap?mode=i

@SKasimow - Is the team considering tracking these links with analytics to see if they are being used by veterans?

**Comment by jenniferlee-dsva** [comment]
@laurellawrence @SKasimow  - feedback from our call, and the examples that we looked at. I'd like to stay as close to the examples we looked at rather than creating our own unique approach. 

https://www.access-board.gov/ict/

https://www.nytimes.com/live/2021/02/16/us/winter-storm-weather-live

https://design.va.gov/patterns

1/ Keep the icon affordance on the same line as the question text.

2/ Use aria or other screen reader text behind code, not as visible call-to-action text.(like the access-board.gov example) - e.g., 'Copy the link to this question' / 'Copy the link to this text'

3/ Hover behavior: indicate hover state, and indicate clicked on state (like NYT example). 

4 /Provide feedback mechanism - prefer NYT example where it shows `Link copied` message right next to the icon rather than in another location. 

5/ Avoid "clipboard" verbiage - older Veterans will not always understand what that is. Something very specific like "Link to question copied" or more generically, "Link copied" preferred. 

6/ Color - I prefer the default state be same color family as the question header text - black/gray - so as to reduce color noise on pages with a lot of questions or sections. But would be okay with color changing on hover or on click like other links. 

7/ Can we see example when this would appear for questions inside accordions?  (The test page will go out with this new UX on questions that are inside accordions as well as questions that are NOT in accordions.) 

8/ The current FE code of deep linking behavior uses the wysiwig component ID - in the BE, all answer text lives inside a wysiwig component, each with a unique ID.

**Comment by jenniferlee-dsva** [comment]
@laurellawrence 

>Is the team considering tracking these links with analytics to see if they are being used by veterans?

Yes. Sharon has been working with me and Analytics team to identify the engagement baseline rate for our coronavirus FAQs page to use as our performance goal. We deliberately selected this page based on analytics because it is a high traffic page that will let us collect data in a relatively reasonable time.

**Comment by SKasimow** [comment]
@youngfreezyVA fyi on notes

**Comment by laurellawrence** [comment]
Hi Ladies, based on the feedback above, I have a new prototype ready using only a black icon with "link copied" feedback after a user click 

https://preview.uxpin.com/c24f0ec63fcc859b8eebaacad860a0d968bc3d45#/pages/136710695/simulate/sitemap?mode=i

**Comment by SKasimow** [comment]
@laurellawrence looks good to me!

**Comment by laurellawrence** [comment]
I have the mock updated to change to blue (visited link color) after click and to still display the text "Link Copied." Whether or not this text is displayed to the user or only read out loud while using a screenreader using aria tags is up to an accessibility expert to review (Trevor or Josh). 

https://preview.uxpin.com/c24f0ec63fcc859b8eebaacad860a0d968bc3d45#/pages/136710695/simulate/sitemap?mode=i

Another thing I found this morning is that there is actually anchor links embedded within our design system with some differences here (Chain icon is on the left of heading, no feedback text). You can see an example of this on the "Research Insight" heading. 

https://design.va.gov/components/buttons#research-insight

**Comment by sshein** [comment]
tiny thing but I'd recommend removing the exclamation point after "link copied" - also funnily, the design system page itself is not built with our design system, so those anchor links are not necessarily recommended, but you can certainly use them as an example in the wild :)

**Comment by laurellawrence** [comment]
Removed exclamation - same mock link as above https://preview.uxpin.com/c24f0ec63fcc859b8eebaacad860a0d968bc3d45#/pages/136710695/simulate/sitemap?mode=i

**Comment by jenniferlee-dsva** [comment]
Hello - There are a couple of things unincorporated from previous feedback. Could we please see: 

1/ More than 1 instance on a page - no need to go mock a real page; just copying/pasting the same question a couple times would be fine. Maybe just add some lorem ipsums to make the question text longer or shorter to indicate how this might appear with many different items on the same page. 

2/ Example of what this would look like for a question inside an accordion - on the same page, since there is a mix of accordions and not-accordions on this page. 

3/ Mobile view.

**Comment by sshein** [comment]
Just a quick note that Laurel is no longer with the public websites team (she was a fill in), @callen2563 will be taking over starting next week and will finish up this ticket I assume. cc @SKasimow @brianalloyd

**Comment by brianalloyd** [comment]
Thanks for the update @sshein appreciate it.

**Comment by SKasimow** [comment]
@youngfreezyVA - am adding some feedback from Jennifer and Ryan depicting the mobile experience. Let's discuss at next stand-up:


Hi @SKasimow - adding a couple mobile interaction examples here for you to add to the product outline. Ryan Thurlwell and I checked out some nuanced edge case scenarios and we both like the NYT  approach which appears both 508- and mobile-friendly. 

https://www.nytimes.com/live/2021/02/16/us/winter-storm-weather-live#about-3500-sea-turtles-are-rescued-from-the-frigid-temperatures-in-texas

### Example - When the icon wraps to the next line in mobile and feedback message appears:

![image](https://user-images.githubusercontent.com/43381063/108742107-5ff35180-7505-11eb-8a7e-d93a7a8154d6.png)

### Example - when the icon fits on same line but is at the max line length in mobile - feedback message appears to the left of the icon (rather than to the right of it: 

![image](https://user-images.githubusercontent.com/43381063/108742695-f758a480-7505-11eb-9c52-1f3401e375d5.png)


### Example - focus state: 

![image](https://user-images.githubusercontent.com/43381063/108742886-3981e600-7506-11eb-9a5b-4f58320168f7.png)

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - until the new design resource is available to detail the necessary specs, please mock as best as you are able with the following design elements we touched on earlier today with Jen:

- decrease the size of the icon
- change to blue 
- place a thin, medium gray circular line around the icon (a la NYT)
- upon hover add background color to circle (try the medium gray and we can see if it shows up well with the blue icon)
- use sentence case for test "Link copied"
- display "Link copied" for 5 seconds
- after clicking icon, the color should change from blue to gray (?? I don't recall what color we said to use for this)
- change placement of icon to the end of the question
- if there is room, "Link copied" appears to the right of the icon
- if there isn't enough room or if adding the text will result in an additional line, place"Link copied" to the left of the icon
- in focus sate there should be a light blue border around the icon to help with focus
- the"Link copied" text should have same border in focus state

**Comment by jenniferlee-dsva** [comment]
Looks good @SKasimow . Per this slack thread https://dsva.slack.com/archives/C52CL1PKQ/p1614112622035800 Ryan is giving this some thoughts for us and will post iteration/solidification of concept here for you and Fareez.

**Comment by SKasimow** [comment]
@jenniferlee-dsva Thanks Jen!

**Comment by rtwell** [comment]
### design specs
feel free to [inspect specific colors, sizes](https://www.sketch.com/s/e4461f10-60cd-46f6-9479-69f0a4d71bab/a/ygVwY3b#Inspector), etc in sketch for teams!

#### mobile

![image](https://user-images.githubusercontent.com/12564977/109320070-9be82880-781d-11eb-8954-be4f3f4d61a2.png)

#### desktop (linking to an accordion)

![image](https://user-images.githubusercontent.com/12564977/109320349-eb2e5900-781d-11eb-8e35-304ffc73d486.png)





### accessibility and design notes
1. height and width of the button to the line height of our `h3`s hopefully to avoid weird line height changes when type wraps (which happens to be ~26px)
2. When the button + text cannot be displayed to the right of the button (because there is not enough room to the right of the button), it displays to the left, overlapping the h3 (see spec)
3. we could consider making the entire h3 + button interactive @1Copenut i defer to your expertise here
4. on click/tap, we display "Link copied" (or whatever the content team recommends) for 10 seconds
5. on click/tap, use a live-region to announce the "Link copied" text and keep the focus on the button. Since the text is an addition, we could do something like
```
<div aria-live="polite" aria-relevant="added text">
  <button aria-label="Copy RELEVANT_TEXT sharable link">
    <!-- SVG or Font Awesome goodness -->
  </button>
  <div>
    <p>Link copied</p>
  </div>
</div>
```
6. The accessible label will contain relevant, content specific titles for the screen reader to announce, e.g. “Copy [**How can I stay informed about COVID-19 vaccines at VA**] sharable link”.
7.  in the accordion instance, we will link the title of the accordion
8. behavior is identical on desktop and mobile, excluding a hover state
9. we do not need a `visited` state for the button

**Comment by SKasimow** [comment]
@rtwell This is great - appreciate the mocks and detailed specs!

**Comment by SKasimow** [comment]
@youngfreezyVA Hi - adding you back to this ticket not to own - just for the detailed design mocks and specs!

**Comment by sshein** [comment]
thanks for working on this @rtwell while the contract designers are transitioning teams! looks good.
