### ISSUE TITLE
[content] Review content on the revised 'Request for Higher-Level Review' page

### ISSUE THREAD

**Issue by smoonpeyes** [department-of-veterans-affairs/va.gov-team#1993]
## Goal
Review the content of the higher-level review content page to ensure:
- content follows the VA.gov style guide and 
- information and next steps are presented in a clear and usable way.

## Page to be reviewed
- [Higher-Level Review](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385333421_00-Request-Higher-Level-Review)
- [Higher-Level Review with expanded accordions](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/385333422_01-Request-Higher-Level-Review-Expanded-Benefit-Office)
- Design ticket #1989

## Acceptance Criteria
- [x] Content is reviewed
- [ ] Recommendations have been communicated to the team
- [ ] Recommendations have been updated in the designs

**Comment by peggygannon** [comment]
Hello, @carolynwill @YanaRoy 
I had provided content updates to the HLR mockup (https://vsateams.invisionapp.com/share/W5U21BDFTQK#/screens/385994365/comments) in  issue: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2011. 

Is there additional content I need to review for this issue here?

**Comment by peggygannon** [comment]
Hi, @YanaRoy and @carolynwill I'm checking back in on this issue. It's not clear to me what content I need to review. I had provided content recommendations to the HLR mockup via https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2011

Please advise if there is additional copy that needs a review? 

cc @meganhkelley
