### ISSUE TITLE
Copy edit check: 2 RS name articles

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#19937]
### HEADS UP only - content is out for final SME concurrence. 
Have asked SMEs to concur by EOD Feb 17, but this eta is squidgy. Not urgent and can be triaged accordingly. Just wanted to make you both aware in advance.  

**Request:** 

- Please review these 2 new RS articles for standards and style. 
- Feedback on anything that's unclear or awkward would also be much appreciated.

**Preview pages:**
1/ How to update your legal name change on file with VA http://preview-prod.vfs.va.gov/preview?nodeId=15995
2/ How do I change my name in DEERS? http://preview-prod.vfs.va.gov/preview?nodeId=16009

**Comment by jenniferlee-dsva** [comment]
**Source content used for validation along with SME reviews:**

1.	VHA 105HIG Health Info Gov DQ HC IDM SME VHA19HDIHCIdMSMEs@va.gov – re VHA VAMC requirements

2.	VBA – Procedures Manual -  M21-1, Part III, Subpart iii, Chapter 8 - Evidence Required to Change or Correct Existing Vital Information About a Beneficiary  - https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001034/content/554400000028396/M21-1,%20Part%20III,%20Subpart%20iii,%20Chapter%208%20-%20Evidence%20Required%20to%20Change%20or%20Correct%20Existing%20Vital%20Information%20About%20a%20Beneficiary#1a

3.	VBA – Procedures Manual -  Exceptions when name change is due to marriage, divorce, or annulment - https://vaww.vrm.km.va.gov/system/templates/selfservice/va_kanew/help/agent/locale/en-US/portal/554400000001034/content/554400000028396/M21-1,%20Part%20III,%20Subpart%20iii,%20Chapter%208%20-%20Evidence%20Required%20to%20Change%20or%20Correct%20Existing%20Vital%20Information%20About%20a%20Beneficiary#1b

4.	VBA National Call Center – phone agent said you have to update legal name with every VA benefit record individually – advised mailing in request with copy of name change document (like divorce decree, marriage cert, or court issued doc) as well as calling each intake center afterwards to confirm that it’s been changed.  

5.	DEPO history - There is no standard guidance and various paths forward.  
- You must get the name change processed in DEERS, and 
- your registered health care facility, and
- your registered RO, and 
- possibly do the same for EDU, LGY, INS, or other direct payment benefits you receive  in theory the RO should be able to take care of that but practice and knowledge seem inconsistent
- in theory VAMC should have an MPI admin who can submit the change in DEERS   practice and knowledge seem inconsistent
  
6.	IRIS DEERS article- https://iris.custhelp.va.gov/app/answers/detail/a_id/1700/kw/name%20change  (IRIS is being deprecated)

7.	DOD DEERS article - https://milconnect.dmdc.osd.mil/milconnect/public/faq/DEERS-Veterans_and_DEERS

**Comment by jenniferlee-dsva** [comment]
Adding additional clarification received from Camille Tello in the Office of Business Integration - confirmation post-call w/Camille.  Article content updated accordingly. 


> From: Lee, Jennifer Y. 
> Sent: Tuesday, February 16, 2021 3:41 PM
> To: Tadeo, Sandy A., VBAVACO <Sandy.Tadeo@va.gov>; Tunnell-Hindman, Shelley J <Shelley.Tunnell@va.gov>; Mitchell, Tamekia L. <Tamekia.Mitchell@va.gov>; Grandon, Jeffrey <Jeffrey.Grandon@va.gov>; Hamilton, Lori VBAPHILINS <lori.hamilton1@va.gov>; Trulock, Robyn F., VBAVACO <Robyn.Trulock@va.gov>; Hurley, Tammy, VBAVACO <tammy.hurley1@va.gov>; Contreras, Raleigh, VBAVACO <Raleigh.Contreras@va.gov>; Granato, Peter, VBAVACO <Peter.Granato@va.gov>; Wante, Kelly, VBAVACO <kelly.wante@va.gov>; Mims, Mike L <Mike.Mims@va.gov>; Temlitz, Sara <Sara.Temlitz@va.gov>; Smith, Alfreda, VBAVACO <Alfreda.Smith@va.gov>; Shute, Paul J., VBAVACO <Paul.Shute@va.gov>; VHA 105HIG Health Info Gov DQ HC IDM SME <VHA19HDIHCIdMSMEs@va.gov>; Kemper, Charlotte, VBAVACO <Charlotte.Kemper@va.gov>; LaPaglia, James <James.LaPaglia@va.gov>; Blumenthal, Dannielle <Dannielle.Blumenthal@va.gov>; Self, Matthew <Matthew.Self2@va.gov>; Kovacs, Steven D. <Steven.Kovacs@va.gov>; Potts, Beth <Beth.Potts@va.gov>; LantosSwett, Chante <Chante.LantosSwett@va.gov>; Hecht, Randi L. (Ad Hoc LLC) <Randi.Hecht@va.gov>; VHA Digital Media <VHADigitalMedia@va.gov>; Baker, Laurie, VBAVACO <laurie.baker@va.gov>
> Cc: Tello, Camille, VBAVACO <Camille.Tello@va.gov>; Pearson, Richelle, VBAVACO <richelle.pearson@va.gov>
> Subject: RE: Preview name change RS article (by Feb 17)
> 
> Hello,
> We received some additional clarification from VBA’s Office of Business Integration SME regarding the “vital” info update process for VBA benefits: Veterans and beneficiaries do not need to contact their registered regional office. 
> 
> They only need to send their request directly to each program office intake center address. 
> 
> Technically, the Veteran can go in person to their registered regional office and submit all of their information in person, and have the RO scan and route their request to each of benefit program office intake center, but contacting/going to the RO is not required and it is not something they need to do in addition to sending in their request to the specific program office intake center address. 
>

**Comment by bethpottsVADEPO** [comment]
Not sure if the version I edited had the above changes from Camille... but here you go, @jenniferlee-dsva, my substantive edits. It'll still need Randi's copyedit. Let me know if you want me to proceed with these edits in drupal. I thought you'd want to see track changes first, and my comments in the Word doc. Let me know if you have any questions!

**Comment by bethpottsVADEPO** [comment]
[How to update your legal name change on file with VA.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6006828/How.to.update.your.legal.name.change.on.file.with.VA.docx)

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva One other change, I unintentionally left out, so I want to note it here for you:

I wanted to suggest moving this information that was in a bullet point in the intro to the third section, as a note following the other text:

**Note:** When you change your legal name on file with VA, your information doesn't automatically get updated in DEERS. And if you change your name in DEERS, you'll still need to change it with the program offices you get payments from.

**Comment by bethpottsVADEPO** [comment]
Here's the DEERS article with my edits, @jenniferlee-dsva 
[https://app.zenhub.com/files/133843125/5f99a4f9-45cf-49d4-87dd-4410d244a00d/download](https://app.zenhub.com/files/133843125/5f99a4f9-45cf-49d4-87dd-4410d244a00d/download)

This one is a great example of a single Q&A that can be more broadly used when COPE is enabled!

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO - I love 95% of these changes! It is so much simpler. Take a look at my comments on the few areas where the edit changed the factual accuracy and needs either a different kind of phrasing or going back. 

Happy to just talk you through if faster. 

**How.to.update.your.legal.name.change.on.file.with.VA-jl-021921.doc**
[https://app.zenhub.com/files/133843125/4de5e1fc-9404-49ee-8c02-089c092e20f9/download](https://app.zenhub.com/files/133843125/4de5e1fc-9404-49ee-8c02-089c092e20f9/download)

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO - I forgot to include this comment on the main name change article. We can't remove the note about the veteran having to update their name in deers and vice versa. Many ppl assume that updating their name in DEERS automatically updates their info for VA benefits and it doesn't. The various databases don't connect/sync at all. 

>You’ll need to update your name separately ....including:
> - DEERS with the Department of Defense if you’re a Veteran. Note: Updating your legal name with VA doesn’t automatically update your information in DEERS or vice versa.

**Comment by jenniferlee-dsva** [comment]
@bethpottsVADEPO - here are a couple comments about the DEERS article to consider. Nothing factually changed by your edits. 

**DEERS-namc-change-IRIS-RS-article-021921-jl.doc**

[https://app.zenhub.com/files/133843125/5044598e-4cc0-4cc4-ad5e-91a66bc14a58/download](https://app.zenhub.com/files/133843125/5044598e-4cc0-4cc4-ad5e-91a66bc14a58/download)

**Comment by jenniferlee-dsva** [comment]
Oh, yes, feel free to make the updates in Drupal, incorporating the latest feedback I uploaded ^.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva Responding here to your comments.

**Name change article:**

**For the intro paragraph**...
1/ This sentence goes back essentially to what you had before! Works?:
You'll need to contact each program office that you receive direct benefit payments from.

2/ For this sentence, since we've already said it twice above in the intro (see No. 1 here, above), I think it would be overkill to say it a third time (like, by the third sentence, it would be assumed that it isn't "all" Veterans, spouses, dependents or caregivers, but the ones who receive health care or payments). But I'll leave it up to you! Just worried that it'll get pretty repetitive: 
If you’re a Veteran, spouse, dependent, or caregiver **who receives VA health care or direct benefit payments**, read below to find out how to change your name on file with VA.

**For the accordions,** my only suggestion was using "letter" vs "request" in each one--just that one word change, not the rest of the text.

----------

**For the last section about DEERS**, I'm not sure "their" is clear enough. And including DMDC is probably more important than mentioning that it's a DOD thing, since when the user calls, the rep will identify themselves as DMDC when they answer the phone. So how about this?:
Contact the Defense Manpower Data Center (DMDC) support office ~at the Department of Defense (DoD)~.

-----------

In a comment above (sorry, forgot to reinsert it in the Word doc!), I suggested moving the info about updating in both DEERS and program offices down into the DEERS section of the page, as the last bit of text, in a note:

**Note:** When you change your legal name on file with VA, your information doesn't automatically get updated in DEERS. And if you change your name in DEERS, you'll still need to change it with the program offices you get payments from.

**Comment by bethpottsVADEPO** [comment]
@jenniferlee-dsva Responding here to your comments about the DEERS article.

Agree with many of your notes/comments, but want to note 3 things here:

- The approach for the phone numbers and hours of operation that I edited is our style throughout the site--tier 1 and R&S. It appears this way, with this formula, on dozens of pages. If we want to discuss a new style, I'd like that to be part of a more formal strategy convo/decision...

Call the DMDC at 800-538-9552. They’re open Monday through Friday, 8:00 a.m. to 8:00 p.m. ET (closed on federal holidays). If you have hearing loss, call TTY: 866-363-2883.

- Since DEERS is the topic of this Q&A, I think we need to define that acronym somewhere in the answer. How about we combine it with that last sentence about it being maintained by DoD? If we move the other note about "vice versa" to be an in-body alert, this could turn into a note:

**Note:** DEERS is maintained by the Department of Defense (DoD). It's the Defense Enrollment Eligibility Reporting System.

- With PL, we avoid latin phrases, so I rewrote to avoid "vice versa."

**Comment by bethpottsVADEPO** [comment]
@RLHecht These two articles are now ready for your copyedit, then you can publish!

**Comment by RLHecht** [comment]
These articles have been published. Moving this ticket to validate.

**Comment by RLHecht** [comment]
These pages are published. Closing ticket.
