### ISSUE TITLE
VAOS controllers returning 401 exceptions that are not tied to VAMF errors

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#19965]
In our VAOS Sum of Errors dashboard, we are noticing a number of 401 exceptions being returned from the controller level that are not related to any error responses from VAMF. For example:
```
{action="create", controller="vaos/v0/appointment_requests", status="401"}
```

We need to figure out why these errors are triggering and may need to introduce new logging to help with this discovery.

**Comment by ajmagdub** [comment]
The discrepancy between the VAOS and VAMF errors has been fixed as seen by this screen capture from Apr. 19, 2021:

![Screen Shot 2021-04-22 at 8.35.11 AM.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/ea5c91a6-582a-40da-a475-ee18446f60d6)

It was probably fixed in [PR #6122](https://github.com/department-of-veterans-affairs/vets-api/pull/6122)
