### ISSUE TITLE
Investigate Whitelist Staging CSRF

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#20012]
Ryan Johnson has asked if we could look into possibly whitelisting CSRF for loadtesting situations.

Thread is [here](https://dsva.slack.com/archives/CSFV4QTKN/p1613415970143400?thread_ts=1612987332.117300&cid=CSFV4QTKN)

## Background:
Management desires automated load testing so performance reports can be generated on a recurring basis (monthly) rather than having to be invoked manually on an occasional basis. This allows for regular monitoring and health checks on important endpoints.

We were hoping to deliver this around the close of next sprint (3/2). If this is too tight or interfering with current work we can be flexible.

Whitelisting CSRF tokens for the use of Locust on staging environment will allow automated load tests to be run on a given interval (approximately every month) without human intervention, unblocking ticket https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17274
and unblocking the following epic https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/19400. 

Loadtests are located within`/devops/loadtest` and formerly ran (as of 2019) by fetching a cookie from a `cookies.json` object generated via this Jenkins task http://jenkins.vfs.va.gov/job/rake_tasks/job/vets-api-load-test-sessions/ . When rerunning the load tests manually in Jan 2021, they no longer succeeded with the cookies file alone, but required a CSRF token. The CSRF token was spoofed via manually navigating to the necessary load test endpoint via Chome and pulling them out of the request headers network tag. 

When attempting to automate this task by navigating to the load test endpoints via Puppeteer (Chromium) and pulling the request headers, the `api_session` and `CSRF` combination result in a `401 Unauthorized`. Chasing down the cause of this bug have proved elusive across several teams and enabling a whitelist from CSRF for the purpose of load testing was deemed a reasonable solution to the above issues.

## Problem Statement
 VSP Testing Team is not able to automate load tests because of a `401 Unauthorized` error on requests. The suspected cause is a mismatch between the cookie and CSRF token when the fields are requested via an automated process (Puppeteer). If the CSRF token is whitelisted for the purposes of running load tests, the necessary requests should succeed much how they did in the past with only requiring a generated cookie and not a CSRF token.

## Hypothesis or Bet
By whitelisting load tests from CSRF token 
- Load tests will be able to succeed without a CSRF token.
- Additional Info: The CSRF protection seems to be done via `protect_from_forgery` and `set_csrf_header` in the `application_controller` in `vets-api`, a conditional to whitelist CSRF tokens and allow them to pass CSRF protection for request should solve the `401 errors`.

## We will know we're done when... ("Definition of Done")
- [ ] Load test requests will succeed without requiring a CSRF token.

**Comment by rjohnson2011** [comment]
## Background:
Whitelisting CSRF tokens for the use of Locust on staging environment will allow automated load tests to be run on a given interval (approximately every month) without human intervention, unblocking ticket https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/17274
and unblocking the following epic https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/19400. 

Loadtests are located within`/devops/loadtest` and formerly ran (as of 2019) by fetching a cookie from a `cookies.json` object generated via this Jenkins task http://jenkins.vfs.va.gov/job/rake_tasks/job/vets-api-load-test-sessions/ . When rerunning the load tests manually in Jan 2021, they no longer succeeded with the cookies file alone, but required a CSRF token. The CSRF token was spoofed via manually navigating to the necessary load test endpoint via Chome and pulling them out of the request headers network tag. 

When attempting to automate this task by navigating to the load test endpoints via Puppeteer (Chromium) and pulling the request headers, the `api_session` and `CSRF` combination result in a `401 Unauthorized`. Chasing down the cause of this bug have proved elusive across several teams and enabling a whitelist from CSRF for the purpose of load testing was deemed a reasonable solution to the above issues.

## Problem Statement
VSP Testing Team is not able to automate load tests because of a `401 Unauthorized` error on requests. The suspected cause is a mismatch between the cookie and CSRF token when the fields are requested via an automated process (Puppeteer). If the CSRF token is whitelisted for the purposes of running load tests, the necessary requests should succeed much how they did in the past with only requiring a generated cookie and not a CSRF token.

## Hypothesis or Bet
By whitelisting load tests from CSRF token 
- Load tests will be able to succeed without a CSRF token.
- Additional Info: The CSRF protection seems to be done via `protect_from_forgery` and `set_csrf_header` in the `application_controller` in `vets-api`, a conditional to whitelist CSRF tokens and allow them to pass CSRF protection for request should solve the `401 errors`.

## We will know we're done when... ("Definition of Done")
- [ ] Load test requests will succeed without requiring a CSRF token.

**Comment by joeniquette** [comment]
@rjohnson2011 Can you please send us the URLs you are requesting to be whitelisted for the domain? Also is it possible for you to make a change within your deployment for staging to enable this whitelist only during your deployments.

**Comment by joeniquette** [comment]
Sudo code: 
```
WHITELIST_DOMAIN = 'vest-test.gov'
  protect_from_forgery with: :exception, if: -> { ActionController::Base.allow_forgery_protection && hostname != WHITELIST_DOMAIN} 

```
Is what Trevor proposes we do for the whitelist

**Comment by bosawt** [comment]
I think Ryan and I have found a path forward for him, and we've at least temporarily unblocked the load_test work. It looks like we can extract `csrf-token`, `api-session` cookie, and `vagov_session_staging` cookie, from a Puppeteer script. Then we can set these values in a series of calls for the load_tests. 

We don't need to whitelist the csrf token for this work, and for now we don't need to make changes in identity to support this. 

I think we can safely close this ticket. It's possible that the Puppeteer script will need some accommodations made if it can't get the cookies it needs from a headless implementation, but we can probably reopen a ticket if we need to help in some way for that.

**Comment by rjohnson2011** [comment]
Agreed, whitelisting CSRF is no longer an issue. Thanks for your work on this. Closing the ticket.
