### ISSUE TITLE
Investigate the use of LambdaTest for Cross-Platform Testing

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#20024]
# Description
Explore the possibility of implementing a cross-browser testing integration with [LambdaTest](https://www.lambdatest.com/). Given the initial assessment appears to be largely positive, create a proof of concept implementation.
# Tasks
- [ ] Create a rough outline of the product features and VSP disposition for each
- [ ] Given a generally positive disposition regarding the products, create a proof of concept implementation that demonstrates an integration with our platform.

**Comment by holdenhinkle** [comment]
I contacted LambdaTest's support earlier this morning and asked them if adding support for Cypress is on their roadmap. They answered, "We have released the beta phase for our cypress runner and will be going live with it in the next 3-4 weeks." and asked me if I'd like to meet with someone from the company to learn more. I agreed and met with at 12pm. When we met (I met with 
misbahf@lambdatest.com) I explained to him that we tried BrowserStack's Cypress offering but couldn't get it to work; we're guessing our non-standard Cypress configuration doesn't work with their system. I shared a link to our `cypress.json` and `support/index.js` files. He offered to have his engineers get our Cypress tests working with their system and asked to meet tomorrow to review it. I took him up on his offer and shared a link to our Cypress documentation, just incase that helps. I'm meeting with them tomorrow, Wednesday the 16th, at 1pm EST.

**Comment by holdenhinkle** [comment]
I had a meeting with LamdaTest yesterday where they were hoping to demo the `vets-website` Cypress tests running on their system. (Their Cypress integration is in beta and hasn't been launched yet.). Their lead engineer and a sales rep was on the call.  The engineer mentioned that their Cypress integration uses the same 'Cypress Wrapper' as they called it as BrowserStack, and their current integration can't work with a custom Cypress configuration like ours either. He was, however, very excited about the idea of getting a non-standard Cypress integration to work with their product. He said that he's spoken with this team, and they've decided to spent 6 weeks adding support for non-standard Cypress configurations to their system, starting on February 24th, the start of their next sprint. He said they have recognized that many apps have a non-standard Cypress configuration because Cypress is so flexible. I made it clear that we’re a large organization and that if they do that, I can't guarantee in any way that they’ll get our business and that we're currently exploring our options for cross platform testing. He said he totally understands and that the update will allow all non-standard Cypress configuration to work with their system, so it could benefit many potential customers of theirs.

**Comment by holdenhinkle** [comment]
LambdaTest Product Outline doc - https://docs.google.com/spreadsheets/d/15FEBrTcHly0zU97lFC4is2aka6P1QUeFGR5WfjJWMZ0/edit?usp=sharing

**Comment by pjhill** [comment]
@holden -- Do we want to leave this research ticket open for the moment? I believe that this product is a front-runner assuming BrowserStack falls through.

**Comment by holden** [comment]
Sounds fine to me, but maybe you want @holdenhinkle to advise?  ;-)

**Comment by holdenhinkle** [comment]
@holden, I like your name! :-)

@pjhill, yes, let's leave this open for now.

**Comment by holdenhinkle** [comment]
This ticket is old.

LambdaTest tried to demo the product with our custom Cypress configuration a few months ago and it didn't get well. Just errors.

Moving this to Review.

**Comment by pjhill** [comment]
Let's revisit LambdaTest in six months. The product seemed promising, but it was not where we needed it to be yet.
