### ISSUE TITLE
FE Tools Discovery: GitHub actions replacing CircleCI as VSP CI tool

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20126]
## Details 

VSP Ops & Leadership have decided to move away from CircleCI as a CI tool. Prior to this decision, VSP FE Tools had been planning to move _to_ CircleCI. 

This ticket represents the research we need to do on this decision, how it impacts us now, and how it impacts our future plans. 

The ticket that Ops made for this work is #19663 — they're also writing up a decision document for this, which we should get from them and link here. 

## Questions to Answer

* What exactly is the decision? Could we continue to use CircleCI if we chose to? What limitations would there be? 
* What do we use CircleCI for right now?
   * Do these things need to be moved off of Circle? If so, on what timeline? 
   * If so, where should they be moved to? 
* What have we discussed using Circle for in the future, and how does this change impact those plans? 
   * Recommend path forward for vets-website deploy 
   * Presumably this will have an impact on app isolation? (High level details would be helpful here but no detailed solutioning needed, since we don't have a recommendation for app isolation approach yet) 

Document answers to these questions in Confluence (?) & link to this ticket.

**Comment by U-DON** [comment]
# FE Tools Discovery: GitHub Actions replacing CircleCI as VSP CI tool

## What exactly is the decision? 

Operations is designating GitHub Actions as the primary continuous integration (CI) solution.

Each application (`vets-website` being one) will have an AWS user with limited permission scope.
- That user will have a token stored in GitHub Encrypted Secrets.
- Any application-specific secrets can be managed via AWS Parameter Store.

## Could we continue to use CircleCI if we chose to? What limitations would there be?

Operations can continue supporting VFS teams using CircleCI, but recommends GitHub Actions for consistency across VSP.

There are secrets that multiple repos may want to share, such as AWS keys. CircleCI manages this sharing through **contexts**.
- Contexts are too open; anyone in the GitHub organization can expose them.
- It's not possible to limit shared secret keys to specific repos within the organization.
- For security, contexts should no longer be used to manage secrets.
- However, without contexts, shared secrets will have to be managed and kept updated at the repo level.

VA also restricts the use of third-party **orbs** (packaged and reusable configurations). We would not even be able to use our own published orbs.

*For repos that have similar CI processes, individually managing secrets and workflows would be tedious and prone to error.*

As `vets-website` will continue to require access to various shared AWS features (e.g., S3), it would be best to use GitHub Actions.

## What do we use CircleCI for right now?

- Unit tests (Mocha)
- Linting (ESLint)
- Drupal cache test (to confirm that pulling the cached content in S3 works)
- Contract testing (Pact)
- Webpack build (apps only; no content)
- End-to-end tests (Cypress)

With the exception of the Pact flow and Drupal cache test, all of the steps are also in Jenkins, our current primary CI solution.

The Jenkins pipeline has some functionality not currently implemented in the CircleCI pipeline.
- It does a full build. CircleCI only does a Webpack build since it can't pull content from the Drupal server.
- It's also responsible for deploying the build. Our CircleCI pipeline does not currently deploy builds.

### Do these things need to be moved off of Circle?

Yes. In order to move to GitHub Actions, we should maintain parity with our existing pipelines.

It should preserve all of the functionality listed above from both Jenkins and CircleCI.

#### If so, on what timeline? 

TBD.

#### If so, where should they be moved to?

GitHub Actions. There will have to be a configuration file set up to use GitHub Actions. The format of this configuration will be fairly similar to CircleCI's configuration.

## What have we discussed using Circle for in the future, and how does this change impact those plans? 

CircleCI was originally intended to fully replace Jenkins as our primary CI tool.
- It already does many of the same things as Jenkins, but is missing the full build (with content), accessibility/sitemap tests, and deploys.
- In anticipation of switching to CircleCI, we've also already added some workflows that don't exist in Jenkins, such as Pact testing.

The only shift in the plan is the CI tool to which we port the existing functionality.

### Recommend path forward for `vets-website` deploy 

1. Start implementing the basic workflows from CircleCI in GitHub Actions (testing, linting, Webpack build).
2. Continue developing a solution for building the site without direct access to Drupal (frequently updated cache).
    - Like CircleCI, GitHub Actions will not have access to the VA network and cannot directly pull content from Drupal.
    - This would still be applicable once the content build is separated, since it would presumably also have to run its CI in GitHub Actions.
3. Determine the deploy process with GitHub Actions.

### Presumably this will have an impact on app isolation?

App isolation will likely require a major change in our CI process regardless of what CI solution we end up using.

That work will have implications for finer grain control over building and deploying at the app level.

**Comment by U-DON** [comment]
Ops has officially announced using GitHub Actions as the primary CI tool. I've confirmed with Ops about the new workflow for `vets-website`. The information in the write-up above is consistent with the announcement and recommendations.
