### ISSUE TITLE
Reduce the vendor bundle size

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#20161]
## Issue Description
In https://github.com/department-of-veterans-affairs/vets-website/pull/16096, I added a polyfill to fix an IE11 bug which increased the size of the vendor file by 10x. It's...pretty bad. Next step: Get the vendor bundle size back down as close to the ~307k that it was before as we can.

This may mean removing the polyfills from the vendor bundle in favor of more intelligently requesting the polyfills.

## Acceptance Criteria
- [ ] The vendor bundle size is reduced to < 500k in production
- [ ] The `date-fns-tz` bug isn't re-introduced in IE 11

**Comment by jbalboni** [comment]
@cvalarida Seems like it should go in here, possibly? https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/polyfills/preESModulesPolyfills.js

**Comment by cvalarida** [comment]
Yeah, good call. I'll end up moving this polyfill there, but _just_ moving it will still increase that bundle size by like 2.7MB, which is still not good. Less bad, since that one is only shipped to a subset of older browsers, but not great.

The order of operations I plan to attempt to solve this problem by goes something like:
- Using a different, lighter polyfill
- Optimizing the current polyfill
- Splitting out the polyfills from the vendor bundle

I'd actually love to get your thoughts on that last one. I believe you have context on why they're in the vendor bundle in the first place, yeah?

**Comment by jbalboni** [comment]
Yeah, I think step 1 or 2 is the way to go there. The current polyfill has locale information that we'll never need. You should be able to get it down to 300kb with one of the [other build](https://github.com/formatjs/date-time-format-timezone#browserified-file-size), if there's not another polyfill to use.

The polyfills are in the vendor bundle because historically we put everything that was needed across all apps in the vendor bundle, plus I believe some of the vendor bundle libraries need certain polyfills. We moved some polyfills out into the separate pre-ES5 bundle in order to lighten the load for the majority of users who don't need to download them.
