### ISSUE TITLE
RFC: VA.gov Content Scaling

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#20165]
## Approvals
- [x] @mchelen-gov 
- [x] @drorva 

### Requested Node Capacity
Requested node capacity for CMS from product teams is [estimated](https://docs.google.com/spreadsheets/d/1pa0EgHuOXINvool4QHjV3lIDyYf-p9JRr8z1AuW4HFE/edit#gid=0) to be:
- Q2 (April 1): 13,453 - 23,953
- Q3 (July 1): 32,733 - 62,733
- Q4 (Oct 1): 44,733 - 86,733

### Build Speeds
- GQL multiquery has been benchmarked to [14k nodes](https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=1540963105&range=G18:I18) and scales linearly:
  - 7 minutes (worst case, uncached)
  - 47 sec (best case, cached)
- Content only [build pipeline](http://jenkins.vfs.va.gov/job/builds/job/vets-website-content-vagovprod/) times are 8-16m
- CMS Export downstream build steps are slower than GQL and do not [scale linearly](https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=615400060).

## Implementation Status
- CMS Export build pipeline has been implemented on dev environment
- FE Tools team requires 4 weeks from point of build parity for production release
- Build parity has not yet been reached
- Product teams work estimate for build parity is over 2 weeks

## Conclusions
- CMS Export parity and implementation timing will not match requested capacity by Q2 (April 1).
- GQL performance has been determined to support current Q2 requested capacity
- Planned GQL performance improvements are expected to support Q3 requested capacity
- Additional benchmarks and performance improvements are needed validate Q4 requested capacity

## Risks
- Changes to requested capacity may affect the ability to deliver sufficient performance
- Downstream build step performance may affect overall deploy times
- GQL query work would become redundant if CMS Export is implemented in the future

## Next Steps
1. Halt work on CMS Export and preserving existing work
    - Includes FE Tools, CMS Core, Facilities, Public Websites teams.
    - Save current work into branches, document branch names.
1. Prioritize near term scaling work
    - CMS Core: [GQL scaling benchmarks](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4215)
    - FE Tools: Hourly content deploy pipeline #18844 #18845 #20100 
1. Plan ongoing scaling work
    - CMS Core: [GQL performance improvement](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4170)
    - FE Tools: [Downstream content build performance improvement](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20206)

## Proposed Milestones
April 1, 2021
- 20k node capacity
- Hourly content-only deploy

July 1, 2021
- 60k node capacity

**Comment by Yuffster** [comment]
What are the possible consequences of exceeding the supported capacity from a business perspective?

**Comment by mchelen-gov** [comment]
> What are the possible consequences of exceeding the supported capacity from a business perspective?

Good question, right now either 1) the build would complete but more slowly or 2) the build would fail. The system is currently dependent on editors not to overload it beyond capacity.

**Comment by meganhkelley** [comment]
> Content only build pipeline times are 8-16m

At what node count? How does this change as nodes scale? If 14k nodes = 16 minutes (sometimes), can we assume that 86k nodes = > 1 hour? If so, does that mean we are depending on significant further build time improvements happening well before end of year? 

Edit: ah I see it further in, that's what you're referring to with this line "Planned GQL performance improvements are expected to support Q3 requested capacity" and the next bullet — I'd say it is worth calling out more detail here, including responsible team and level of confidence.

> FE Tools team requires 4 weeks from point of build parity for production release

Worth clarifying: 2 weeks for production release, 2 weeks to implement auto-deploy. (Could just edit to say "for production release including hourly auto-deploy" or similar)

> CMS Export parity and implementation timing will not match requested capacity by Q2 (April 1).

Correct, but that doesn't influence this decision — because GraphQL as it is _will_ meet this capacity. What we need to have eyes on when we make this call is less April 1, more 6-18 months out.

> Risks 

I would recommend documenting risks in greater detail. Some suggestions: 

* Edit to your bullet 3 for clarity: If CMS Export is implemented in future, reaching parity would require numerous weeks of VFS team work, and GQL work completed in the intervening period would be redundant 
* GQL's ability to scale to end of year assumes further improvements to GQL and downstream content build pipeline (notes about confidence? notes about competing priorities and limited team resources?)
* _Are there any risks inherent in the new GQL approach — Nick S' magical PR from 2 weeks ago? Not actually magical, but I'd bet Nick or others can think of a couple._
* Ongoing lack of clarity around long-term ownership of content build pipeline impacts team resources & effective prioritization (perhaps this isn't the doc for that but I'd be remiss if I didn't mention it)
* If the new GQL approach is such a big & obvious win, why didn't the super team recommend it? Is it because the 5 min requirement changed? Is it because those folks didn't think of it? Is it because those folks did think of it and decided it wasn't a good approach? Not sure how to represent this as a risk/not sure it needs to be called out – perhaps it's best summarized as "Risk: There's something we're not thinking of" but that's likely assumed in everything we do

> Prioritize near term scaling work - FE Tools: Hourly content deploy pipeline

Perhaps this is picky, but hourly deploys are not scaling work. Scalability & hourly auto-deploys are 2 separate business requirements — we should call them out separately ("Prioritize near term GQL & pipeline improvements"?

**Other notes**
* Add a "required approvers" section & document those approvals

**Comment by drorva** [comment]
So to summarize, as of today with graphql:
* We're doing around 33 nodes per second
* The queries seem to scale linearly
* Q4 worst case 86,733 would take 42 minutes. Even with the rest of the pipeline should be under an hour.
So we're in good shape with this approach until the end of the year.
We should also explore optimizations that should take us even further including:
* Since we're using RDS Multi-AZ possibly use the replica rather than the main db. This might provide huge benefits if the cach stays warm
* Migrate to use Aurora
* Explore incremental deploys
* etc.

**Comment by mchelen-gov** [comment]
> > Content only build pipeline times are 8-16m
> 
> At what node count? How does this change as nodes scale? If 14k nodes = 16 minutes (sometimes), can we assume that 86k nodes = > 1 hour? If so, does that mean we are depending on significant further build time improvements happening well before end of year?
> 
> Edit: ah I see it further in, that's what you're referring to with this line "Planned GQL performance improvements are expected to support Q3 requested capacity" and the next bullet — I'd say it is worth calling out more detail here, including responsible team and level of confidence.

Current published node count is 3300. GQL query times have been [benchmarked to 14k](https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=1540963105) and are approximately 0.039s per node, worst case. Based on [FE benchmarks](https://docs.google.com/spreadsheets/d/1enwIGvEyGLVCLIHeRWXrp-ggDsnss8dyxSK4Bvxx4Mw/edit#gid=615400060&range=A33) the total build time scales linearly as well. For Q4 2021 max requested capacity of 86k nodes yes, we will need the GQL perf work by CMS team and downstream build perf work by FE Tools team. This allows both teams to do work in their area of expertise:
- CMS team has multiple known Drupal performance tuning approaches available
- FE Tools team is highly skilled at the JS used in downstream build steps

Absolutely agree about coordinating the timing of these efforts to hit capacity milestones.  An important advantage of this approach is that neither team is blocked from their work by the other teams. It's also important to note that many of the benchmark numbers are based on worst-case values, and ongoing real world performance should be tracked to see if we can safely revise the estimates upwards.

**Comment by meganhkelley** [comment]
Should this be documented in the adr folder? https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/docs/adr

**Comment by mchelen-gov** [comment]
Documented as "Accepted" https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/docs/adr/0006-scale-vagov-using-gql-not-cms-export.md
