### ISSUE TITLE
Investigate whether using Cheerio instead of regex could speed up our build time

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#20206]
## Details 

Research ticket: #19612
Use `cheerio` dependency instead of `libxmljs` #16486

From research ticket: We have some conflicting reports on whether using Cheerio instead of regex for DOM traversal could help speed up our build time. The purpose of this ticket is to investigate regex vs Cheerio and determine a path forward. Currently we use Cheerio in some places and regex in others — determine whether this is actually the most efficient approach. 

## Definition of Done
- [ ] Research Cheerio vs regex and make recommendation for one vs the other vs both. Identify specific places where we should be using one vs the other.
   - [ ] Peer review from 2 VSP team members - required
   - [ ] Peer review from other interested teams as applicable (CMS & VFS & Design Systems)
- [ ] Create new ticket for implementation of recommendation

**Comment by mpelzsherman** [comment]
I would like to gain a better understanding of how assets are managed in our CMS system.

The global asset hostname replacement we are currently doing, whether using cheerio or regex, is pretty expensive.

It currently takes about 15 seconds to replace all of the URL's using my MacBook Pro. The pages.json file is 25MB.

**Comment by k80bowman** [comment]
@mpelzsherman I'm working on trying to understand it better myself. I saw your comment on #19612 about moving all of that to the Liquid templates and I think that's not a bad idea. I'd like to get some comments on that from someone with a bit more knowledge around how all of this works, though.

**Comment by mpelzsherman** [comment]
When I suggested this during our CMS Export engineering sync meeting yesterday, @swirtSJW said we couldn't do this because of assets uploaded by users in WYSIWYG fields. I'd like to examine that bit further.

I think we also heard that some assets are hosted on S3, and others not. I'd like to understand why we can't host all of our assets in a consistent location?

**Comment by k80bowman** [comment]
I think those are great places to dig in. From looking at our build process, it seems that speed improvements are going to come mostly from tracking down a number of smaller things like this (especially things that have the potential to get bigger as we start processing more and more content).

**Comment by k80bowman** [comment]
**Synopsis**
My analysis determined that Cheerio is faster than using regex to traverse HTML files and update source paths. It would be worth creating a card to refactor the linkAssetsToBucket function from the Prearchive stage to use Cheerio. As part of this refactor I would recommend breaking that function up into smaller, more easily understandable parts and add unit tests. [This draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16215) can serve as a place to start.

**Analysis**
*Problem Statement*
During the research for #19612, two conflicting suggestions were made regarding how we handle traversing HTML files as part of our build process. One suggestion was made to remove Cheerio and use regex in the assets.js file, assuming that regex would be faster. Another suggestion was to update places in the code where we use regex for HTML document traversal to use Cheerio instead, assuming that Cheerio would be faster. The purpose of this card, then, was to choose a place in the code where we are using either regex or Cheerio and switch them out, comparing the results in order to determine which implementation would be faster.

*What is Cheerio?*
[Cheerio](https://www.npmjs.com/package/cheerio) is an npm package derived from JQuery that allows us to easily parse markup and then easily traverse and manipulate it. It is made to work only on markup, it is not a 1:1 replacement for tools like JSDOM. It does not apply any CSS, load any external resources, or execute any JavaScript. We currently use it in our assets.js file to update asset paths in the HTML files retrieved from Drupal.

*Where are we currently using Cheerio and regex?*
Where are we using Cheerio?
- [src/site/stages/build/drupal/assets.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/assets.js)
- [src/site/stages/build/plugins/modify-dom/index.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/index.js)
- [src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/getBrokenLinks.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/getBrokenLinks.js)

Where are we using Regex?
- [src/site/stages/build/drupal/assets.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/assets.js)
- [src/site/stages/build/plugins/rewrite-va-domains.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/rewrite-va-domains.js)
- [src/site/stages/build/plugins/rewrite-drupal-pages.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/rewrite-drupal-pages.js)
- [src/site/stages/build/plugins/rewrite-cms-aws-urls.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/rewrite-cms-aws-urls.js)
- [src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/getErrorOutput.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/check-broken-links/helpers/getErrorOutput.js)
- [src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/plugins/modify-dom/add-id-to-subheadings.js)
- [src/site/stages/build/drupal/utilities-drupal.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/utilities-drupal.js)
- [src/site/stages/build/drupal/page.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/page.js)
- [src/site/stages/prearchive/link-assets-to-bucket.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/prearchive/link-assets-to-bucket.js)

It’s important to note that we will not be able to replace all implementations of regex with Cheerio. Cheerio is only intended for use in cases where we need to parse markup.

*Comparing Cheerio and regex*
I chose to use the `linkAssetsToBucket` function for this analysis.

The time it takes to run this function has increased as the number of published VAMC facility pages has increased. In January, for the dev and staging environments, it was taking around 1m 30s to run. As of March 1st it is now taking around 2m 30s to run.

When I updated this function to use Cheerio (you can see my implementation in [this draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16215)), I was able to reduce the time it took to run the function to a little over 1 minute. 

Additionally, we had a problem with this function recently where we had to allocate more memory for it to be able to run. Using Cheerio resolves that issue and we are able to run it without allocating any more memory. I haven’t analyzed what exactly about this change fixes the memory issue, yet, however.

*Are there other places we could make this switch?*
Potentially.

These three functions use regex to parse markup, but they don’t usually take very long to run (2.5s for rewrite-va-domains):
- src/site/stages/build/plugins/rewrite-va-domains.js
- src/site/stages/build/plugins/rewrite-drupal-pages.js
- src/site/stages/build/plugins/rewrite-cms-aws-urls.js

**Comment by meganhkelley** [comment]
Thanks Katy! We can spin up a new ticket for the implementation during sprint planning today.

**Comment by k80bowman** [comment]
Just noting it here (from [this Slack thread](https://dsva.slack.com/archives/GLDNCMRSP/p1614716798014000)), @U-DON pointed out that, in this case, the comparison is really between JSDom and Cheerio, rather than just regex and Cheerio, and I have to agree. That could also account for the reduction in memory usage.

**Comment by k80bowman** [comment]
Closing this one. We created #20763 to complete the refactor work.
