### ISSUE TITLE
[Design]: Design details and customize copy and/or error messaging for the "upload" component in 10-10CG

### ISSUE THREAD

**Issue by jonathanjnelson** [department-of-veterans-affairs/va.gov-team#20318]
## Description 

_Work with Justin to make sure the upload feature in the 10-10CG is optimized for the use case_ 

Note, I (Shawna) recommend this ticket happen *after* Justin pulls in and codes the basic upload pattern from other forms (e.g. the 21-526EZ) so we can play around with what works and doesn't from our form

## Acceptance Criteria

- [ ] _Reserach error states_
- [ ] _Allign with content If needed_
- [ ] _Mockup error states_

**Comment by sshein** [comment]
Slack thread for research https://dsva.slack.com/archives/C0NGDDXME/p1616119139020800

**Comment by ala-yna** [comment]
@sshein  - what's the status of this ticket? is this still work that needs to be looked at?

**Comment by sshein** [comment]
Good question since I kept opening and closing it :) we haven't seen the upload feature actually fully coded yet so once it's closed I want Dené or I to actually go through the feature and make sure the error states and copy make sense

**Comment by Dene-human** [comment]
According to what FE can see, we are just using the upload component that a lot of other forms use, and getting those error states automatically (AKA they are not really in our control) and we don't have a complete list of possible errors.


**The error states that I was able to test:**
1. Internet connection error![network fail.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/4d03c108-7658-4a8d-a0f8-53006df98ffd)

2. File too large error
 ![file too large.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/fb418372-c3b0-49dc-be50-ff59918c3371)


I am not sure if we should run these by the content team since the wording doesn't really follow the [Style and Tone Guideline](https://design.va.gov/patterns/messaging-error-messages#style-and-tone). But as per above Slack reference it seems like Platform is already working on this.

Should we close this @sshein @ala-yna ?

**Comment by sshein** [comment]
yeah I don't think we need to run it by anyone at this point, I just wanted to make sure none of the error messages specifically referenced something that didn't make sense for the caregiver form. I think we can close the ticket.

**Comment by Dene-human** [comment]
That makes sense. Thank you!

**Comment by mlighdc** [comment]
Hi @Dene-human I am going to re-open this ticket per our conversation today about the **network request failure** and it does not tell the user what to do, especially since this can happen intermittently quite a bit. Happy to chat more about this.

**Comment by Dene-human** [comment]
As discussed in standup, next steps:

- [ ] [ Open ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25320)to platform to improve error messaging on doc upload in sitewide form system
- [ ] Explore how to improve messaging on just the 10-10CG doc upload page

**Comment by Dene-human** [comment]
Since it looks like the Platform team will not be handling this update, I suggest we create a new ticket based on the platform feedback to Ticket #[ 25320](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25320#issuecomment-849773667)

**Comment by ala-yna** [comment]
@tchrisdyer  - can you make a ticket for @dat-gcio to tackle this, based on Platform's response?

**Comment by tchrisdyer** [comment]
Added to Sprint 48 Epic for tracking purposes.

**Comment by tchrisdyer** [comment]
@dat-gcio and @Dene-human , I created [Frontend] Improve document upload error messaging#25405 for the implementation as requested.

**Comment by Dene-human** [comment]
The update to upload error messaging will take place in: 

Design
Ticket #[25320](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25320)

Development
Ticket #[25405](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25405)
