### ISSUE TITLE
Collaboration Cycle Kickoff [C+ L, Anchor Tags]

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20342]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [product outline] 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/anchor-tags.md
- Link to wireframes, mockups, or prototypes: 
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19867
https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/20125

- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

**Will your work result in visible changes to the user experience?**
- [x] Yes
- [ ] No

**Is your work a new product/feature or an iteration to an existing product/feature?**
- [x] New
- [ ] Iteration

**Will your work impact only static content pages?**
- [x] Yes
- [ ] No

**Are you making changes to the visual design?**
- [x] Yes
- [ ] No

**Are you making changes to content?**
- [ ] Yes
- [x] No

**Are you making a change to the user flow?**
- [ ] Yes
- [x] No

**Are you making a change to urls, navigation, or entry points?**
- [ ] Yes
- [x] No

**Are you doing research with VA.gov users?**
- [ ] Yes
- [x] No

**Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?**
- [ ] Yes
- [x] No

**If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?**
- [ ] Yes
- [ ] No

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @SKasimow  - do you know if there is a design system component for anchor tags?

**Comment by SKasimow** [comment]
Hi @shiragoodman - no it isn't. Jen recently reviewed this project at a Design Council meeting; since it is an experiment for just the 1 page, they were ok with us moving ahead. You can read the notes from the meeting here: 

https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/19867

Additionally, Ryan T. has been engaged and is providing feedback so think we are well covered.

Ping me though if you'd like to discuss further!

Thanks,

Sharon

**Comment by shiragoodman** [comment]
Thanks for the info @SKasimow ! that definitely helps. I checked with @mnorthuis on your response to the url question and she informed me that urls will be impacted because you are exposing deep links. With that info, we are recommending the following touchpoints:
- IA Request:
- Midpoint Review (can now be asynchronous)
- Analytics Request
- Staging Review
- Privacy & Security Review

For Contact Center, it seems unlikely that you'll need a review, but please check with that team to confirm.

We now have Collab Cycle Office Hours on Wednesday from 11:30am-12:00pm for any questions or concerns you may have about Collab Cycle, or if you need some assistance outside of the touchpoints. If you'd like an invite for your calendar, please let me know. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our [Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) page for next steps.

**Comment by SKasimow** [comment]
@shiragoodman Hi - can you add me to the collaboration cycle office hour invite? thanks!

**Comment by shiragoodman** [comment]
@SKasimow sent!

**Comment by SKasimow** [comment]
Staging review ticket: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/259
