### ISSUE TITLE
[Design] MyVA - Research Summary

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#20386]
## Background
Following the research sessions, we need to create a research summary. 

## Tasks
- [x] Create research summary
- [ ] Review with Samara

**Comment by Samara-Strauss** [comment]
Here is my feedback on the [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-topline%20summary.md) (btw, loved this format and how easy it was to scan and review). In general, great job! I think you covered all the main points.

## General

It's "My VA" (two words) not "MyVA" (one word).

## Findings (Wins)

> All users said they would look in the homepage links to find updates to benefits (specifically in the disability section)

I wouldn't consider this a "win" because nothing about our design impacted this behavior. People used the homepage because we started them there and because those links are super clear. I would just mention the above point later on in the section about My VA being hidden in the mobile nav, so people didn't know it was there to check for their personal info.

> Users easily found the information that they were looking for

I know this is just the topline summary, but mentioning this here so we don't forget — in the actual report, we should mention that this was likely because they were already on My VA, and more robust testing should be conducted once the feature is live to see if people can find information here when we don't effectively show them how to get to the page.

> Users did not think anything needed to be added to MyVA for it to be a successful homepage

Is this true? Later on, you mention a few things people did want to add to their own homepages. I know View Payment and Education were both mentioned a few times. This point seems to contradict that finding later on, so I would either clarify or remove. When you talk about information that people expected to see (eg. payment info), I think you can frame it as the page wasn't a total failure without this information, but the additional information should be considered in order for us to more fully serve veterans and meet their expectations.

## Findings (Pain points)

> Apply for benefits — no confusion

I thought multiple people had trouble finding more information on other benefits they could apply for, specifically the "What benefits does the VA offer?" dropdown and that we might want to consider moving that up under the main "Apply for benefits" heading. Am I misremembering? Was that just 1 or 2 people and not an issue overall? Let me know what the official record says and how this shook out in the actual notes.

Also, while this wasn't a huge pain point, people didn't seem totally sure why we were showing the benefits we chose under "Benefits you might be interested in," though people were generally able to parse it together. Some people did think it might have to do with eligibility, though, and it does not. Up to you whether you think this is worth calling out.

## Things participants mentioned that they would like added/changed

For this section, can you give a sense of how many participants asked for which features? I'm curious if there are things that were overwhelmingly mentioned vs. mentioned 1 -2 times. If all of these were mentioned by most participants, just let me know.

## Other thoughts

Here are some notes I had that may or may not fit somewhere in the larger summary. Take or leave them as you see fit:

- Overall, the info we have on My VA seems helpful. This dashboard works well to let people know the lay of the land. However, It will likely work less well to prompt people to do things (P4). We may want to continue exploring how we can more effectively prompt people to take action.
- While some people still preferred the homepage because it has more CTAs, many participants mentioned how much they appreciated the personalization of My VA and that they don’t want the VA to show them things that don’t apply to them. They just want to see their information. **This further validates the existence of My VA and our pursuit of personalization on VA.gov.**
- Given that we were using an InVision prototype and not testing in code, it’s unclear whether people easily found things just because we were already on My VA or whether they’d have as easy a time if we started them somewhere else on VA.gov. We should test this in follow-up sessions once My VA is live.
- People generally understood the difference between the My VA dashboard and the Profile, and were able to accurately describe the profile in their own words. However, they had a leg up because we asked them this when they were already on My VA.

**Comment by tressaellen** [comment]
> I know this is just the topline summary, but mentioning this here so we don't forget — in the actual report, we should mention that this was likely because they were already on My VA, and more robust testing should be conducted once the feature is live to see if people can find information here when we don't effectively show them how to get to the page.

Totally agree here, I'll be sure to include that in the full report

> Users did not think anything needed to be added to MyVA for it to be a successful homepage

In my head I had separated what Veterans said about what they wanted on the homepage vs on the dashboard... but they're really the same thing. I removed this point since there is an entire section dedicated to things they think should be added.

> For this section, can you give a sense of how many participants asked for which features? I'm curious if there are things that were overwhelmingly mentioned vs. mentioned 1 -2 times. If all of these were mentioned by most participants, just let me know.

I'm still sifting through the exact number that said each thing, but once I have that I'll be sure to specify in the larger report and then update this topline summary

**Comment by Samara-Strauss** [comment]
Awesome, sounds good on all accounts!

**Comment by tressaellen** [comment]
Here is the [Research Summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/product/Research%20V2/MyVA2-research-findings.md).  I still need to add in quotes, screenshots and a link to my synthesis tools.

**Comment by Samara-Strauss** [comment]
Feedback on the research summary:

- **Watch My VA vs. MyVA vs. MyVa** — Remember, it's My VA.
- What is the difference between Overall Findings and Additional Insights? The difference in how their hierarchy isn't clear to me — why is that two sections instead of one section?
- I think the Task Breakdown section of what went well vs. what didn't is really useful, but I am wondering if that could be combined somehow with the overall findings section in some way. I don't have any fully formulated ideas on this at the moment, but it feels like Overall Findings, Additional Insights, and the breakdown of what went well vs. what didn't are all related, yet they're all broken up. Let's maybe talk about how we can make this more cohesive, easier to scan, and more clearly tied to the final recommendations.
