### ISSUE TITLE
App Preview Pre Login

### ISSUE THREAD

**Issue by leanna-usds** [department-of-veterans-affairs/va.gov-team#20404]
Forcing login (which we know can be complex) before users understand the features may be a missed opportunity. Is there a way to demonstrate features of the app pre-login to affect the cost/benefit analysis?

**Comment by bridgethapner** [comment]
@leanna-usds We have a 4 screen onboarding flow in the app that we currently have after sign in - can be started [here](https://adhoc.invisionapp.com/share/GTZ1ESFF6BN#/screens/439611290_Onboarding_Group_1-_Scope_Of_App). Maybe we move the current onboarding flow to before sign-in? I agree that giving people the lay of the land before signing in is a good idea!

**Comment by leanna-usds** [comment]
Yes! This is so great, what do you think about showing this pre-login?

**Comment by bridgethapner** [comment]
I think it's a good idea -- I think we will likely get downloads from folks who don't use our features, and it'd be good to communicate our app's features earlier rather than later to avoid disappointment or frustration. 

Looping in @msmanak who did the design work here and @ayushchak. What do y'all think about moving the onboarding flow to pre-login? If it sounds good to both of you, I think Meli can make minimal design adjustments for this to work pre-login (the only one I can see is removing the user's name on the first screen) & we should be set.
