### ISSUE TITLE
Add submission loading spinner to 10-10CG

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#20405]
## Technical Task

On the 10-10CG we have long wait times that can make the user wait as long as 2 mins, so we need to create an alert and spinner to let the user what is going on and set expectations so they are not confused on whether their application went through or not

## Expected Behavior

- On the review page, user sees a note to set the expectation that submission may take a while. That note should say: 
     - Note: It can take several minutes for your application to process after you submit it. Please don’t refresh your browser during that time.
- After clicking the submit button, a loading spinner appears with the message:
     - Please wait while we process your application.
- After 30 seconds, the note on the spinner changes to: 
     - We’re processing your application. This may take up to 2 minutes. Please don’t refresh your browser.

## Acceptance Criteria

- [x] Content aligns with [design](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20320) && [UX Pin](https://preview.uxpin.com/669525e992a5edd248b84db96767fc607630185b#/pages/137223921/simulate/no-panels?mode=i)
- [x] Message changes after 15 seconds
- [x] UX confirmed with product stakeholders

**Comment by LinnJS** [comment]
@ala-yna @jonathanjnelson need acceptance criteria of what is happening when on this spinner and alerts

**Comment by ala-yna** [comment]
Content was reviewed by Peggy in the last comment on this ticket: https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20320

**Comment by LinnJS** [comment]
Hey @joshkimux just wanted to follow up here and add you to the loading spinner ticket so we can be assessable on this feature. Also thanks for the callout during the sprint demo!

A link to the [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16166) and the [RI](http://e18ca1dee6472faa20d311fe06e0106a.review.vetsgov-internal/)here

**Comment by joshkimux** [comment]
Hey @LinnJS , thanks for tagging me here! Off a quick read through, I'd suggest the following to ensure compliance ahead of a test in staging:

- Since a screen reader user would still be in form mode on this page, notes that are not a part of the tab order (e.g. `<p>`) will most likely be skipped over unless they are deliberately called out. You could potentially address this by giving the note a unique ID and tying it to the submit button with `aria-describedby` 
- Upon submitting, the dynamically added messages "Please wait while we process your application..." and "We’re processing your application. This may take up to 2 minutes..." should be announced to screen reader users using an `aria-live="polite"` region. Make sure that the region exists on page load before content is added in, otherwise it can get buggy.
- Design wise, y'all may also want to consider how long users will wait before refreshing the page or exiting. Even 30 seconds can feel like forever to most people when no active feedback like a progress bar is provided.

Let me know if you or the team have any questions about any of these and I'd be happy to explain in more detail over a call!

**Comment by sshein** [comment]
it looks like Peggy recommended content be added "if it takes longer than 2 minutes" - see this comment https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20320#issuecomment-785382430

But I think we don't need to add it personally if all the information shows up in the spinner immediately after the user clicks submit. Also, @LinnJS didn't you and Kevin just say that if the user clicks submit and it lasts more than 60 seconds it's a timeout and we stop the process and alert the user?

**Comment by sshein** [comment]
For the purposes of this ticket, I think we should just remove the note that says it takes several minutes to process. I also don't really know why we need the two separate messages - the one that happens before 30 seconds and the one that happens after 30 seconds. Couldn't we just do away with the first message and just have the second message?  @joshkimux I assume that would be better for accessibility anyway? For context these are the two messages

![Screen Shot 2021-03-10 at 12.17.00 PM.png](https://images.zenhubusercontent.com/5d4c59b26a82cc000106fdf0/b3de3de0-af88-4c99-90ed-28b5f461bdf9)

Then I think we should just write up a second smaller ticket to look at the other federal law note.

cc @ala-yna

**Comment by kevinmirc** [comment]
I think Peggy's content was created based on the max processing time of two minutes (where at the two-minute mark a timeout-error would occur). We did not extend the timeout, so it remains 60 seconds and the progressive message shows up at 15 seconds (instead of 30 seconds).

The purpose of providing a [message before the submission](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20320#issuecomment-789008062) is to set the user's expectations. This form on average takes ~10 seconds to process. After a few seconds of waiting it's reasonable to expect the user to think there is something wrong. The goal of [this specific content](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20320#issuecomment-789008062) content is to lessen the chance of a user refreshing (losing all the data they entered) or leaving the page while it's being processed.

**Comment by sshein** [comment]
right but if we have the more specific content as the loading message from the beginning (instead of the generic one first), we will have no need for the "Note" above, right?

**Comment by sshein** [comment]
So I'm proposing this as a simpler solution when the user clicks "Submit" - to address the issues Josh brought up with screen readers not seeing the "notes"

![Uploading Screen Shot 2021-03-10 at 1.14.39 PM.png…]()

**Comment by sshein** [comment]
trying to go with the design system council's motto of "Let's not have magic. Let's just have boring." 😆

**Comment by kevinmirc** [comment]
This revision looks good to me 👍

**Comment by ala-yna** [comment]
Created a follow up ticket to address the legal note: https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/21388

**Comment by sshein** [comment]
thanks!

**Comment by ala-yna** [comment]
This [RI](https://github.com/department-of-veterans-affairs/vets-website/pull/16166) looks good to me, thanks Justin! Once @joshkimux has a chance to look over it, I'd say it's good to go.

**Comment by sshein** [comment]
where can we see final screenshots or video or something of how it looks? Didn't see them on the linked RI.  Or is the removal of the first message and the "note" going to be as follow up ticket?

**Comment by LinnJS** [comment]
New updated specs are as follows with the old A/Cs being crossed out

- On the review page, user sees a note to set the expectation that submission may take a while. That note should say: 
~~Note: It can take several minutes for your application to process after you submit it. Please don’t refresh your browser during that time.~~
- After clicking the submit button, a loading spinner appears with the message:
  -   'We’re processing your application. This may take up to 1 minute. Please don’t refresh your browser.'
~~After 30 seconds, the note on the spinner changes to: 
      We’re processing your application. This may take up to 2 minutes. Please don’t refresh your browser.~~
      
   **The spinner will no longer have updating content see [*ticket*](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/20405)**
