### ISSUE TITLE
IA Request | Covid Vaccine Page | Tagalog URL | C&L Team 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#20500]
## What this is:

Request URLs for tagalog for the Covid Vaccine page, the Corona FAQ page and the User Research page.

## Required Inputs:

We've received a priority request to provide a spanish version of the Covid Vaccine page. We're going to use the same approach of providing a link to spanish <--> english above the H1 on these pages and we have the URLs previously provided to us from I/A: 

Covid Vaccine: https://www.va.gov/health-care/covid-19-vaccine/ 

I/A URL structure: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/cto-spanish-content.md

****However,** once that is complete our focus will shift to publishing a tagalog version of the Covid Vaccine page** . 

We plan to use a drop-down menu to enable the user to choose between spanish and tagalog on the Covid Vaccine page (followed by the Corona FAQ and User Research page).

- Link to product outline: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/11599 

- Link to or attach prototype or mockups: awaiting UI but expect to use a drop-down menu to chose between spanish and tagalog
- Link to research readout/results ([learn more](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/synthesis/how-to-do-research_synthesis.md)) 

https://github.com/department-of-veterans-affairs/va.gov-team/files/3273454/VA.gov-Spanish-benefits-link-user-research-061019.pdf

https://app.mural.co/t/workqueue2001/m/workqueue2001/1558543337827/1368018bebaf98469c253d22fdd4fc82efd7fa57

- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable

- Link to or attach final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** - Provide link or image of proposed page structure (if more than one page)

**Suggested URL(s)** - Provide suggested URLs and any background or rationale

**Suggested entry points** - What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
@DanielleThierryUSDSVA   Per our discussion this morning...

The translation work to Tagalog will impact the Covid pages only, and we will utilize the same implementation approach as we did with Spanish.  This implementation approach is not scalable long term or outside of the Covid pages, but will work as a short term solution to the urgent need for this content.  

IA recommendations are:

URL
- Append "-tag" at the end of the URL for the Tagalog translated pages.  
- Example: www.va.gov/health-care/covid-19-vaccine-tag/

Language selection
- General UX guidelines for when to use drop lists would generally be when there are more than 5 options.  We recommend using text links on the page rather than a drop list.  This will provide more visibility to the options available and not hide them in a drop list or require another click to expose the options. 

Breadcrumb 
- The current page should be represented in the breadcrumb and show the translated H1

Left nav
- To stay true to global navigation systems, all pages placed within a group of content (i.e. a hub) should appear in the left nav.  
- This would mean that the English, spanish and tagalog versions would show in the left nav.

**Comment by SKasimow** [comment]
@youngfreezyVA fyi

**Comment by SKasimow** [comment]
Completed. Closing.
