### ISSUE TITLE
[SPIKE] Investigation on why validations are not triggered on review page.

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#20605]
## Technical Task

On the review page the `Update page` button seems to not trigger validations enabling malformed data to be added on the review page and resulting in an unsuccessful submission. Discuss with Platform Support to figure out if this is a platform or implementation issue.

Was found while working this [ticket](https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/18849)

## Expected Behavior

Validations should be triggered in order to make sure all data is valid and sanitized correctly

## Acceptance Criteria

- [ ] Validations should be triggered on review page update
- [ ] Specifically you should not be able to add two of the same SSNs when a party is added and removed

**Comment by ala-yna** [comment]
@youngfreezyVA is this something you could look into? 

Please reach out to @LinnJS if you have any questions

**Comment by mlighdc** [comment]
@ala-yna, can you please provide the background to @dat-gcio?

**Comment by ala-yna** [comment]
@dat-gcio, we discovered that the Update page button doesn't seem to trigger data validations, resulting in invalid data being submitted.

**Comment by dat-gcio** [comment]
Was not able to repro. Form is preventing update of error’ed information. Tried multiple routes with toggling yes/no on primary/secondary/secondary(2) questions.

1)	Selected ‘yes’
2)	Filled out demographics information
3)	Clicked back to yes/no
4)	Select ‘no’
5)	Proceed to review page
6)	Change answer to yes from review page
7)	Unable to submit

Also tried selecting ‘yes’ on the review page, to then fill out the demographics information. Same result. Unable to submit.

It may have been fixed in this [PR](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20605) that happened after this spike was made.
