### ISSUE TITLE
Load Time Review of SSOe Redirect Solutions

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#20659]
Leadership would like to understand how much time could be saved for each of the solutions we recommended in [this](https://docs.google.com/presentation/d/1Kj-XlZ5tOWM7TqA0AfWZO2cnRHiNTBbxSdY1KEUp-os/edit#slide=id.ga275b9d4dd_0_238) document, slide 30. This ticket covers the work I need to pull Alex into to help get these numbers documented.

The result of this data will be presented to leadership to help get the solutions approved for implementation.

**Comment by AGarcia-Clarity** [comment]
Update: Timings for JS assets loading from S3 bucket are updated
3/3/2021 @ 4pm
3/4/2021 @ 9am
3/4/2021 @ 12pm (~ TODO)

I see some potential tweaks we can implement to ensure faster loading times
- ### **Use Brotli compression to further reduce sizes on Amazon S3**
  ![Screen Shot 2021-03-04 at 10.30.00 AM.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/31809a5b-f638-4710-bae5-684bc0f30876)
  - Current sizes of JS assets are (102Kb, 102Kb, 299Kb, and 194Kb); Using Brotli these could become (87.7Kb, 87.7Kb, 257Kb, and166.8Kb) respectively.  697Kb of data down to 599Kb (~100Kb)
  - Potential downside: Not supported in <IE11 browsers (see https://caniuse.com/?search=brotli)
- ### **Upgrade to HTTP/2 protocol with a fallback to HTTP 1.1** 
  - HTTP 1.1 only allows 6 connections per origin which is why some assets are Queued for so long (especially when network file sizes are big)
  - We already force VA.gov users to use HTTPS/TLS so this would be a huge speed improvement for all users (authenticated & unauthenticated)
  - Potential downside: Partial support for IE 11 for users with Windows 10 (no support for Windows 7); No support for <IE11 (see https://caniuse.com/http2)
- ### **Convert/minify all SVGs sent over the network**
  (Current size is 325 Bytes)
  ![Screen Shot 2021-03-04 at 11.01.09 AM.png](https://images.zenhubusercontent.com/5f3be621ca5d1e85751d760d/43cd5d1d-e336-4240-b2e5-9756d54a8123)`
 - With a refactor/minify option we can get that down to 261 Bytes (~80% reduction)

**Comment by AGarcia-Clarity** [comment]
Update
- [x] SVG optimizations - Closes https://github.com/department-of-veterans-affairs/va.gov-team/21034
- [ ] HTTP/2 (in RFC)
- [ ] Brotli compression (in RFC)

**Comment by AGarcia-Clarity** [comment]
From conversations within the team this ticket will be closed out from the research conducted.  The RFC ticket #21595 will take precedence for the optimizations recommended.
