### ISSUE TITLE
Direct Schedule - A/B Test Initial Messaging

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#20710]
Goal: Improve response rate to initial outreach message for COVID vaccine 2-way direct scheduling. 

Test 1: Does moving the action step to the bottom of the message content and breaking it into a second message improve response rate? 

Existing content and format = 'Initial Message 1A'
Test content and format = 'Initial Message 1B'

> You can now get a COVID-19 vaccine at %Facility_Name%. More info about COVID-19 vaccines at VA: https://go.usa.gov/xASD8

> To schedule a COVID-19 vaccine appointment, reply to this message within 24 hours. Send us a text with a date and time you're available from %start_date& to %end_date%.

We included some minor language changes for clarity and brevity, but no major changes to tone - those will come in a future iteration. 

Potential future tests:
* Include personal intro message
* Highlight ability to "self-schedule via text"

**Comment by snyderje** [comment]
Ideally, folks within a given site would randomly get either message 1A or 1B - do we have the power to do that? Would there be concerns about how sites would respond to having their Vets get two different messages? Otherwise, splitting by site would also be OK, but so many other confounding factors would enter in to that comparison.
