### ISSUE TITLE
fix direct deposit production errors

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/va.gov-team#2074]
http://sentry.vfs.va.gov/vets-gov/platform-api-production/issues/75312/?query=is%3Aunresolved%20ppiu

**Comment by lihanli** [comment]
we talked with EVSS about these errors. they say that need logs of the full request and responses from their servers along with user edipis to diagnose them. i asked if they can lookup logs by timestamp and they said it wasn't possible. i asked if we can omit bank account numbers from the logs and they said it should be ok for now but they might need them later.

**Comment by lihanli** [comment]
Adam Kinder says he needs user SSNs to check if a user has been flagged for fraud so we can see if that is causing the "Cannot perform an update due to restriction indicators" error

**Comment by lkoenigsberg** [comment]
Does this need to be re-assigned to @hinzed1127 to keep it moving?

**Comment by Justin-Pickett** [comment]
@lihanli will update this ticket with the list of errors. Validate if these errors are still happening. Open new ticket to address outstanding errors that may still be present.

**Comment by lihanli** [comment]
the majority of the errors we're still seeing are `Routing number related to potential fraud`
but the `Generic CnP payment update error. Update response: Update Failed: Night area number is invalid, must be 3 digits` errors are still happening

**Comment by Samara-Strauss** [comment]
Tracking down the final questions we have about the home phone number/address error in #4553.

**Comment by Samara-Strauss** [comment]
I think we can close this. According to Nedie in #4553, only a small fraction of people getting the home phone number error are actually seeing it again after going to fix their phone number, which means people are likely trying to update their direct deposit more than once in a row without going to fix their phone numbers first.

@lihanli let me know if you have any other questions/thoughts about this. Otherwise, I think we have a good enough understanding of the errors we're seeing and why and can close this.

**Comment by lihanli** [comment]
i don't have any more questions about this issue, closing sounds good to me
