### ISSUE TITLE
Content Feedback - Midpoint review - STEM Automated Denial 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#20744]
## User story
Content review of STEM automated denial work for the following: 

- [x] Link to claim tool prototype: https://bahdigital.invisionapp.com/share/G7IAG7A2XKD#/screens
- [x] Link to content doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-content.md
- [x] Automated email: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/automated-decision/automated-denial-email-content.md

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

**Comment by peggygannon** [comment]
Hi, @amy, here is my content feedback on the STEM denial email. Am still working on the other content. 

Question: 
Will you also be making changes to the [static landing page](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/) and the [STEM form introduction page](https://www.va.gov/education/other-va-education-benefits/stem-scholarship/apply-for-scholarship-form-22-10203/introduction) about applicants getting an email if their application is denied? 


[https://app.zenhub.com/files/133843125/fa3d96e5-1352-45fd-a184-6936a4a784b9/download](https://app.zenhub.com/files/133843125/fa3d96e5-1352-45fd-a184-6936a4a784b9/download)

**Comment by amyknox** [comment]
@peggygannon 

Yes - we need to update the STEM form intro. Here's a [link to the updated Decision info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/stem-standalone-10203/content/stem-22-10203-content.md#5-decision) on the intro page. 

We'll need to work with public websites for the static STEM Scholarship page update.

**Comment by peggygannon** [comment]
Hi, @amyknox  Here is my content feedback on the Claim Status Tool STEM Scholarship denied content. 

Let me know if you have any questions or need me to clarify any of my comments/recommendations in the document. 

My main question is about why we are including content on the criteria the applicant *did meet*. I am concerned that this will create a confusing UX if we're showing that in addition to reasons why they are denied. In addition, there's a lot of proposed content on the page and I am looking for areas to trim, so it's not an overwhelming amount of information. 

[https://app.zenhub.com/files/133843125/0031ec4f-e78e-4296-993c-6e2cbc45c09d/download](https://app.zenhub.com/files/133843125/0031ec4f-e78e-4296-993c-6e2cbc45c09d/download)

**Comment by amyknox** [comment]
Hi @peggygannon - Here are responses to the questions you posed in the doc...

**Why the criteria the applicant did meet**
When applicants are notified why they didn't get the scholarship, we also have to notify them what criteria they did meet - in the event they want to apply again.  It escapes me at the moment whether this is a mandate or a recommendation from the team but the denials that go out via USPS have that info so the web version needs it, too. 

I'll update that content so it follows the same format as denied criteria.  

**Sidebar**
The "Need help" information isn't typically on the Claims status page but that info is required to be delivered along with the STEM Scholarship denial.  As you noted, the page is pretty long already so instead of adding to the page length, we put that content in a VA-style sidebar.

LMK if you have any additional questions or suggestions based on this info.  Thanks for the input!.

**Comment by amyknox** [comment]
Comments look good except...

> If you don't agree with the decision on your Supplemental Claim or Higher-Level Review, you can appeal to a Veterans Law Judge by completing VA Form 10182. Download VA Form 10182.

You had suggested "If you've already filed a Supplemental Claim or Higher-Level Review and don't agree with the decision..."

That step is an escalation of either of the previous steps (supplemental claim or higher level review), so they won't have already filed.  Think we should leave as-is.

**Comment by peggygannon** [comment]
ok, thanks, @amyknox  for the context about the mandate (or SME recommendation) to also include the eligibility criteria they met. 

I still think this page is too dense, and I am offering 2  recommendations for your team to consider to trim down the content:


**Consider**

1. It sounds users will also get a denial letter in the mail? If so, I recommend removing the "eligible criteria" from the web page and adding a sentence referring the user to the letter for this information: Something like this: 

Your decision letter will tell you if there was any eligibility criteria you did meet.

-----

**Consider**

2. Instead of listing out the decision review/appeal options. I recommend we direct users to the decision reviews page.  
removing bullet points and replacing with: 

**What should I do if I disagree with your decision?**
If you disagree with our decision, you have 1 year from the date of this decision letter to request a decision review or appeal. You have 3 decision review options to choose from. 
[Learn about your decision review options](https://www.va.gov/decision-reviews/)

You also would need to remove this link further down the page: Learn more about the decision review process.

**Comment by amyknox** [comment]
@peggygannon Thanks for the additional input. To clarify: 

- Applicants who are routed to this page in the Claim Status Tool **won't** be getting a letter in the mail. This is their full notification.  That's why we're including all the info on this page.  

- On a similar note, "What should I do if I disagree" is a form they'd normally receive in the mail.  They won't get it so we're including it here.  Our language about options and next steps is straight-forward. I'm concerned that sending them directly to the decision review options page.  They'd have to hunt to find the info they need which could be confusing and frustrating. 


Also, we had some additional question on the updates you sent back yesterday. You'd suggested softening the info alert content (Your application was denied on MM/DD/YYYY) to "We didn’t approve your application on MM/DD/YY" but then suggest a heading directly below that says, "We denied your application because you didn’t meet all 3 eligibility criteria for this scholarship."

1. That doesn't appear to match the Claims Status Tool info alert content style for denied claims. Thoughts?
2. Wondering if it's necessary to "soften" the alert if we're essentially telling them the same info in the next line?

**Comment by peggygannon** [comment]
Hi, @amyknox  thanks for the additional clarification. 

regarding the info alert, my recommendation was to soften the language and to make it active voice. 

But I see now that this alert is following the alert pattern currently in use in the Claim Status Tool. That said, we should follow that current pattern for consistency--and keep what you have. Updating the language/tone of these alerts will need reviewed/done globally.
