### ISSUE TITLE
Breadcrumb, URL and IA misalignment for Pittsburgh COVID-19 page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#20865]
## Issue Description
Discrepancy between breadcrumb and URL and IA misalignment: 

Breadcrumb: VA Pittsburgh health care > Health services > COVID-19 vaccines
URL: https://www.va.gov/pittsburgh-health-care/covid-19-vaccines/

![image](https://user-images.githubusercontent.com/55411834/110022307-fd5e3a80-7ce8-11eb-9789-8d6a53934fd5.png)

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevwalsh** [comment]
This is all controlled and can be resolved in the content layer.  The URL can be changed (by a content admin, and would require a redirect) to `/pittsburgh-health-care/health-services/covid-19-vaccines/` OR the menu item can be changed to point to use the System page as a parent. 

FWIW, i think all these "care coordinator" AKA "health service detail page" pages have this same issue for Pittsburgh, and possibly some or all other VAMCs.

EG https://www.va.gov/pittsburgh-health-care/women-veteran-care/

Because they all just use the "Detail page" content type, we don't have a way of controlling where they live, and won't until they have their own content type.

**Comment by mmiddaugh** [comment]
This work has been addressed in a separate effort. The COVI-19 page is now under VA Pittsburgh health care >  Programs > COVID-19 vaccines with a corresponding url: https://www.va.gov/pittsburgh-health-care/programs/covid-19-vaccines/
