### ISSUE TITLE
Tech Ticket | Automate Script to Find All Non-English Pages on Va.Gov

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#21076]
## User Story

As a PM on the C+L team, I would like to have a complete inventory of all translated content that is currently on Va.Gov today.
This includes both pages and PDFs.

By way of background, we are going to be creating a new Spanish and Tagalog resource page which will provide users with  useful information and a list of existing in-language content they can link to from the new pages. As part of this effort, we'd like to know what is out there today so that we can check-usage, verify that content is up-to-date, know which URL to link and the like.

Ideally we can gather this for both Drupal and Teamsite content but we should get at least Drupal to start.

So for the output, would like to have some info in a spreadsheet  with Page Title, URL, last modified date ---- and anything else is available that that may be useful for vetting the pages.

## Acceptance Criteria

- [ ] Output is a list of page/PDF names, grouped by language
- [ ] Associated URLs
 - [ ] Date of last update
- [ ] Page owner and/or who made the update 
- [ ] Anything else helpful that you can pull

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @SKasimow!

**Comment by youngfreezyVA** [comment]
hey @Yuffster-usds @ncksllvn @kelsonic would love to get your input on the sitemap and trying to find non english websites (by searching urls for language suffixes or the word `espanol`). 

@SKasimow shared this screenshot from running an analytics report:

![Screen Shot 2021-03-19 at 1 03 17 PM](https://user-images.githubusercontent.com/46791771/111818997-0fb9a600-889d-11eb-9243-79230338d67a.png)


1. I was wondering, does this mean that `https://www.va.gov/sitemap.xml` is not an exhaustive sitemap? Is there a separate sitemap for `benefits.va.gov`? 
2. previously, was under the impression that language suffixes (ie, -tag, -esp) would be all that I would need to search for, however on `benefits.va.gov` i'm seeing a new pattern of using the language like so: `benefits.va.gov/rosanjuan/**language**`. Do we need to account for this type of content as well?
3. Is there a plan to make the sitemap queryable in graphql, so that we have one source of truth for sitewide urls by language? Or do we already have another way to query urls (outside of the sitemap(s))

**Comment by ncksllvn** [comment]
> I was wondering, does this mean that https://www.va.gov/sitemap.xml is not an exhaustive sitemap? Is there a separate sitemap for benefits.va.gov? The benefits.va.gov links in the screenshot were not present at https://www.va.gov/sitemap.xml

That sitemap only includes the pages that are part of the modernized www.va.gov experience - so just a small segment of the overall VA digital presence.

> previously, was under the impression that language suffixes (ie, -tag, -esp) would be all that I would need to search for, however on benefits.va.gov i'm seeing a new pattern of using the language like so: benefits.va.gov/rosanjuan/**language**. Do we need to account for this type of content as well?

I actually didn't know `benefits.va.gov` had translated content. I don't think we have a lookup for that domain though, so I'm not sure how we would query its pages to find those.

> Is there a plan to make the sitemap(s) queryable in graphql, so that we can have one source of truth for sitewide urls by language?
relying on a sitemaps xml file to get the latest content by language would potentially introduce competing data sources and a bit of re inventing the wheel when we already have queries in graphql, and wouldn't be maintainable imo if there are multiple sitemaps. definitely a point of discussion for our efforts moving fwd

This thread is relevant to the topic of sitemap config hosted in Drupal, https://dsva.slack.com/archives/CT4GZBM8F/p1616434061219300. But no plans to move forward, AFAIK.

**Comment by SKasimow** [comment]
@youngfreezyVA should we close this now?

**Comment by youngfreezyVA** [comment]
> @youngfreezyVA should we close this now?

yes, The script pulls from the site map which is representative of the modernized VA experience so I think we can safely close if those are the only websites that are relevant. if not, follow on tickets might be needed.
