### ISSUE TITLE
Determine approach for GitHub Actions in main pipeline

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#21135]
Current behavior: 
PR pipeline uses Jenkins 
Once something is merged to master, build pipeline runs again in Jenkins

Future behavior:
PR pipeline uses GHA
Once something is merged to master, build pipeline runs again in [???]

Ask Ops if Jenkins can communicate with GHA (can GHA trigger a Jenkins failure?) 
	If they can communicate, build pipeline runs again in GHA 
	If they can’t, build pipeline will need to run in Jenkins — this would mean that GHA is used only in PRs

**Comment by meganhkelley** [comment]
Notes: https://docs.google.com/document/d/1knicx2zXyy25Zuq05uukmy5EbZdAuMV58HHzYZKb0WU/edit

**Comment by U-DON** [comment]
Could potentially have the parts in Jenkins wait for the GitHub Actions parts using the [GitHub checks API](https://docs.github.com/en/rest/reference/checks).

**Comment by U-DON** [comment]
[Webhooks](https://docs.github.com/en/developers/webhooks-and-events/creating-webhooks) may also work as a way to coordinate multiple related pipelines.

**Comment by U-DON** [comment]
We can start migrating to GitHub Actions in `vets-website` by accomplishing some combination of these:
- The main/master pipeline is split between GHA and Jenkins such that deploys are handled by Jenkins but blocked by any failures in GHA (tests, linting,etc.). This is what this ticket is meant to investigate.
- The content caching work is completed so that we don't have to rely on Jenkins for building content.
- Create a self-hosted runner to do the content build. We can explore this as an alternative to the content caching approach from the earlier ticket if that doesn't pan out.
- The content build separation is completed so we don't have to do it in vets-website.

Essentially, we need to keep Jenkins in order to have a steady rollout for migrating to GitHub Actions while maintaining the complex workflows like the content build and deploy. Configuring those steps in GitHub Actions will take some time to figure out.

In the meantime, we can start moving simpler steps such as tests and linting into GHA.
- The GHA pipeline running these steps would ideally be a blocking check.
- If GHA is blocking, to avoid duplication, the same steps should be removed from the current Jenkins (and Circle) pipeline.
- On the `master` branch, deploys to dev and staging should still only occur if the rest of the build passed.
  - We could create a webhook that triggers the Jenkins deploys (`deploys/vets-website-vagovdev` and `deploys/vets-website-vagovstaging`) upon successful [check runs](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#check_run) on `master`. _Minimal Jenkins changes aside from removing the step in the Jenkins pipeline that directly invokes those deploys._
  - Alternatively, we could have the deploy step in the Jenkins pipeline poll the [GitHub API for the status of the check runs](https://docs.github.com/en/rest/reference/checks) from the same commit. _More involved Jenkins changes within that deploy step._

**Comment by U-DON** [comment]
Created #21750 as a result of this.
