### ISSUE TITLE
[DISCOVERY] R&S article ‘recommend/share’ feature

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#21180]
## Problem Statement(s)
As a Veterans (or someone that supports Veterans) I want to be able to ‘recommend/share’ an article from R&S via email.   
This could help increase content confidence through helping more Veterans better understand the benefits they have earned.  

Explore both a mobile and desktop version.  We know that mobile is the primary method in which Veterans and those that support Veterans are using to review content and interact with content tags.  Having an optimized mobile version and share component would be ideal in improving the user experience.  

## Bet 
As a Veteran I would share articles (content) that I found impactful to other Veterans that I know and support.   

As a person that supports Veterans I would find value in sharing content with Veterans to help them answer their questions and gain the benefits they need and deserve. 

## Outcomes 
Veteran confidence increased through self discovery and source of truth content via VA.gov/resources library. 

Veterans are more informed and are able to share and receive shared content from the Resources and Support library.

## Research 

What is a strong industry standard approach? (Tools for sharing via email content). 

What tools/plugins are needed to support this approach?

Start a research and design plan for review

Collaboration cycle kickoff to begin the process and test hypothesis and bets

**Comment by callen2563** [comment]
Hey Brian, are you able to share a link to any previous design exploration here I think you mentioned yesterday Ryan had already mocked some ideas up? Thanks! :)

**Comment by callen2563** [comment]
I dug into the website and chatted with Ryan, and Shawna and found these areas that use social media links but nothing for a share feature / component for articles.

https://www.va.gov/health-care/ (in the right rail)

https://www.va.gov/outreach-and-events/events/psycharmor-conversations-with-caregivers-the-importance-of-sleep/

I will mock up a few options for a share article component with these social links in mind.

**Comment by brianalloyd** [comment]
Thanks @callen2563 for the update, not sure any of the above fit as you've noted and would love to see your ideas via mock ups for the share component.  Thanks for your efforts on this, excited to see this idea take shape.

**Comment by sshein** [comment]
this is the related ticket I was talking about @callen2563 https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/406 - I wasn't in the council meeting where this was discussed and decided to put in the backlog but @joshkimux was so maybe he can let you know more about the decision. And see if a "button that looks more like a link" is still something you might use for this share feature

**Comment by callen2563** [comment]
I chatted with Crystabel yesterday and she informed me that the button that looks like a link has been put on hold for now and that I should use a secondary style button and it was ok to use an icon. I have mocked this up: 
![Share Article - desktop](https://user-images.githubusercontent.com/68560244/113433403-22f46780-93ad-11eb-9765-d0019494e49b.jpg)

**Comment by callen2563** [comment]
@joshkimux Hi Josh, when you get a spare minute would you be able to look over these 3 options and comment on which direction is most feasible for mobile and desktop with regard to accessibility? Thanks!

**Comment by brianalloyd** [comment]
Thanks @joshkimux really appreciate the support.

**Comment by sshein** [comment]
Do we have any idea which type of sharing veterans are typically wanting to do? for what it's worth I've read a fair amount of research studies that have been done that show that social sharing buttons (like the ones you have in option 3) are almost never used on mobile and rarely used on desktop - I think many users are confused about what might happen if the click/tap them

**Comment by joshkimux** [comment]
@callen2563 These can all _technically_ be accessible:

### Option 1: the user clicks the "share article" button and their email opens up
If the intended behavior is to open up email, this would be a _link_ as it would be using an anchor tag. It should also contain the destination within the link text (the Veteran's email). For example:
```html
<a href="mailto:?subject=Subject%20here&body=Body%20here">Share article by email</a>
```

### Option 2: the user clicks the "share article" button and the button state changes to a green "link copied" button where they could then paste into messenger, chat window or email etc
Option 2 would be a button, but it should explain its behavior in clearer terms so Veterans won't be nervous about clicking on it. For example, `<button>Share a link of this article</button>`

### Option 3: social media and email icons that open their personal facebook or email with the link populated
Option 3 should be a list of links with images nested within them. The `alt` for each of the images should explain their destination. They could also be linked to the string "Share this article" using `aria-describedby` to provide an explanation of purpose. For example:
``` html
<strong id="share-label">Share this article</strong>
<ul>
  <li>
    <img src="fb.png" alt="Facebook" aria-describedby="share-label"/>
  </li>
  <li>
    <img src="tw.png" alt="Twitter" aria-describedby="share-label"/>
  </li>
</ul>

However, to Shawna's point, the most important piece here is bridging the mental model of the Veteran vs. the model of the interaction. If Veteran's are nervous about using the share links, what could we do to reduce that anxiety? OR, are they even necessary to begin with?

I'd recommend perhaps some secondary research looking into Facebook groups or online forums to see how Veterans share out information from the VA if there's no research to reference immediately.

**Comment by callen2563** [comment]
Thanks @joshkimux 
I think either the first or second option makes the most sense based on yours and Shawnas' comments. @brianalloyd do you have any thoughts or comments since you mentioned this was a feature you were hoping for as a veteran? 

In the mean time I will make the link and text tweaks to the first two options you suggested and repost.

**Comment by callen2563** [comment]
I have made the suggested updated to options 1 & 2. @joshkimux I wanted to get thoughts on if it would be helpful to have explanation text next to the "link copied" button. 


![Share Article - option 1](https://user-images.githubusercontent.com/68560244/113769616-2eb69580-96ef-11eb-9db7-362247e73544.jpg)
![Share Article - option 2](https://user-images.githubusercontent.com/68560244/113769621-3118ef80-96ef-11eb-9d45-1fe051e3b2f4.jpg)
![Share Article - option 2 clicked](https://user-images.githubusercontent.com/68560244/113769631-35450d00-96ef-11eb-8632-2de5bfdef43b.jpg)

**Comment by joshkimux** [comment]
@callen2563 that's ultimately a ux question, are folks familiar with copying/pasting link behavior and usage?
From an accessibility perspective, I'm more interested in if our developers would be ok [creating a multi-state button](https://adrianroselli.com/2021/01/multi-function-button.html)

**Comment by callen2563** [comment]
@joshkimux Oh ok, I was wondering if help text was needed from a screen reader/accessibility standpoint but I'm not sure which is the best UX solution yet either without testing. @cindymerrill what are your thoughts on testing the two options for share article?

**Comment by cindymerrill** [comment]
@cassandra: Testing to determine whether to use a button or link? (I
haven't been following the conversation thread.) Seems too minor to me to
bother testing both options because I don't think participants will notice
much of a difference. Does one match the current design system more?

I would fix the spelling of "preferred", though...

--Cindy

**Comment by sshein** [comment]
maybe whichever design you choose can be included as part of a broader usability test that includes resources and support. I am not positive our user base will understand how to "paste" a link, especially on mobile... but I also do not know which method of "sharing" our user base prefers on the whole and if only sharing by email will seem limiting.

**Comment by callen2563** [comment]
So on mobile if they click the share link a menu pops up on smart phones asking where they would like to share (fb, email, chat etc). I think the only sticking point would be if someone was on a much older non smart phone. Also I'm not confident that users will know the short cut to past a link for desktop. Also, Cindy brought up a great point on our last call that if you click the link to open the users email it might open the wrong email or not open at all. We will be discussing these options more in our sprint planning today.

**Comment by cindymerrill** [comment]
I also suggested including the chosen design in an upcoming usability study
to assess understanding and usage, rather than doing a special study to try
to choose between two designs.

**Comment by callen2563** [comment]
@peggygannon @DanielleThierryUSDSVA @bethpotts Hi there, I wanted to get this on your radar for copy help with share article links and buttons, specifically copy for the help text next to the "link copied" button. Let me know if one of you has the bandwidth to help. thanks!

**Comment by callen2563** [comment]
Update: We chatted with John in sprint planning today and he would like to move forward with option 2 (the copied link direction) as he feels it's the most commonly used method after weighing all the options.

**Comment by bethpottsVADEPO** [comment]
@callen2563 Can you bring this to the unauth content office hours on Monday? Can it wait until then?

**Comment by callen2563** [comment]
@bethpotts yes, I will bring it on Monday thanks!

**Comment by callen2563** [comment]
@brianalloyd Hey Brian, Shawna and I were chatting about this copy link component that Laurel had added: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19867
We were wondering if this was ever built out and if so, should we make sure this and the share article link are consistent? I can bring both of these to the design council meeting next week to get thoughts as well.

**Comment by brianalloyd** [comment]
I believe it has, I'll verify with @SKasimow as I think her team was working the details.  I'll follow up in ticket. Great suggestion on this BTW.

**Comment by SKasimow** [comment]
@brianalloyd Hi Brian - yes this is the work we picked up in Feb; we had to hit "pause" for a bit to work on getting the translated COVID-19 pages launched. But we've picked back up again and just reviewed with @jenniferlee-dsva and @rtwell this week and @youngfreezyVA has finished the FE work. We still have to take through Staging and Privacy and Security which is next. Let's synch up next week.

**Comment by brianalloyd** [comment]
Thanks for the update @SKasimow I'll reach out this week for a quick convo if thats okay.  Appreciate the support.

**Comment by jenniferlee-dsva** [comment]
@brianalloyd  CC @SKasimow @johnhashva @bethpotts - Please do not move forward with this.  

1/ We are already piloting a `copy deep link` UX feature, and are in the final steps with the Platform team to launch it, per https://github.com/department-of-veterans-affairs/va.gov-team/issues/20342

- We have a very clear data plan for the pilot, testing it on one of our most trafficked pages. If upon launch, the baseline engagement data is met, we will be making it reusable by other teams and products. (If the baseline engagement rate is not met, we will deprecate it from the test page and not make it available to expand its use to other products.)

2/ The UX affordance our pilot is testing with has been designed and vetted by DEPO Ryan Thurlwell and the Accessibility team. 

3/ The above "shareable" link affordance in ticket 21180 is mooshing up several things - social media share affordance with copy-deep-link UX. They are actually 2 different things. Social share affordance generally initiiate an actual post to the user's Facebook/Twitter/Linked In/other social media platform. Your affordance above starts out like a standard social media share UX, but then ends as though it is a 'copy deep link` UX.  In any case, there is enough overlap here with the pilot `copy deep link` ux, that we should not be creating another version just for the sake of another version. 

4/ Lastly, and perhaps more importantly -- as the PO who launched RS - I would very much prefer to not add more random affordances and component elements to RS articles until we have done a couple things: 
A) Finish including all of the original MVP elements (I think the user feedback rating component is the only one that's left) 
B) Reviewed the cumulative data to determine what components users are actually interacting with 
C) Consider removing non-essential components that users are ignoring, 
D) Do user research with live pages to determine _**actual**_ user pain points to address. 

As far as social sharing, this was not one of the functionalities that users demanded when we did user research and usability testing for the launch. This doesn't mean that users don't change and that in the live environment, user's will actually find that as a feature that they say they really need but are hindered by not having a social share UX. But I would prefer that actually be a problem that users tell us they have, rather than make a design assumption that this is a pain point.

**Comment by brianalloyd** [comment]
@jenniferlee-dsva holding.  @SKasimow and I are collaborating on the share link and will remain aligned. Thanks for the feedback.  CC @johnhashva

**Comment by cindymerrill** [comment]
There may be some relevant research findings from the baseline wayfinding
research on VA.gov that I'm conducting right now.
