### ISSUE TITLE
[Development/Design] Robin's Validation Changes - Provide Better Validation Messages

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2138]
## User Story or Problem Statement
As a claimant, I need to see what information I missed while completing my claim so I can get back to that section of the form to provide it and successfully submit my form.

### Background Info
During a screen share, a Veteran was receiving an error message saying that information on his form is missing, but there was no way to tell what and where that information was. 
<img width="629" alt="Screen Shot 2020-09-10 at 3 57 32 PM" src="https://user-images.githubusercontent.com/19188/93779474-0c4aa800-fbf5-11ea-9b06-d2ec3377228a.png">
## Goal
_Allow a system user to view what required information they did not complete on their compensation form when error to submit occurs_

## Acceptance Criteria
- [ ] _Identify how validation errors act now_
- [ ] _Design input on how error handling could be improved_
- [ ] _Identify if this is a global need_

**Comment by Mottie** [comment]
It looks like the error message is there, but only if I edit the content of that confirmation page.

In this screenshot, I unchecked the second checkbox (gotten worse), and checked the new condition checkbox (user 228, on [this page](https://staging.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit)).

![](https://user-images.githubusercontent.com/136959/66861959-90140300-ef55-11e9-9f36-7c24ffcd7c86.png)

As you can see, the Disabilities block did show a warning; but, if I click "Update page" then completely reload the page so that it is populated from the saved data, the form shows no issues. But does show an alert if you try to submit.

![](https://user-images.githubusercontent.com/136959/66862223-1c262a80-ef56-11e9-8027-4feb26079be9.png)

I think it would be a better user experience if **the accordion edit button instead returned the user to the actual step of the form** instead of allowing them to edit the content inside the accordion. Or, at least limit the items that can be changed in the accordion.

**Comment by Mottie** [comment]
This issue is focused on research, but I discovered that I could include the form errors within the alert shown on the page after attempting to submit. I’ve included it here because I wanted to get feedback on adding this information, and possible a design review.

![](https://user-images.githubusercontent.com/136959/69977720-ebdc2080-14f0-11ea-9210-a8479b03b218.png)

Note:
* The "No rated disability selected" is currently an empty message within the form since errors are handled differently from the typical form schema validation. There are similar situations within form 526 that will also need to be updated to make it work with this method of showing errors.
* The “Missing…” items use the internal schema names, so “InformalConferenceChoice” is converted into “informal conference choice”, so this is very dependent on how the values are named in the schema, which may not be ideal.

I pushed my work to get the above done into the “2138-add-errors-in-review” branch - here is the commit: https://github.com/department-of-veterans-affairs/vets-website/commit/6458d252b5385e878e48ce91a4dd0a5c804c003c

**Comment by jenstrickland** [comment]
@Mottie This looks like it could be a test case for something @1Copenut and I have experimented with. We discussed making each of the error items a link to the field that has the error.

**Comment by Mottie** [comment]
> We discussed making each of the error items a link to the field that has the error.

Oh, that's a good idea!

**Comment by Mottie** [comment]
Including [our Slack discussion](https://dsva.slack.com/archives/CL181NRJQ/p1580919517045400) on this topic here:

@Mottie
> I'm working on adding error message links on the review & submit page of all forms after the user submits. The issue is that the errors refer to the property name, e.g. requires property "hasMilitaryRetiredPay". In the screenshot, I have altered that property name to We’re missing has military retired pay. It's still not ideal. I was in a meeting with @jenstrickland and she suggested I remove the We’re. Is there something else I could do to improve the content?
>
> ![Screen Shot 2020-02-05 at 10 06 25 AM](https://user-images.githubusercontent.com/136959/73964336-9ac52000-48d7-11ea-9a84-677ff866870d.png)

> I think the ideal solution would be to have the actual error messages that are presented to the user when they interact with the form (not the review page); but the code isn't very straight-forward

@jenstrickland
> That would likely be a valuable insight to consider in the redesign.

@meganhkelley   
> cc @peggygannon when you have time

@peggygannon   
> I'm curious why the error message doesn't appear on the actual screen where the error appears, it's my understanding that that is what the pattern should be across all forms.

> I have never seen the error message that is above. I'd be happy to discuss more on a call if that would be helpful

@Mottie   
> the review & submit page uses a secondary method to validate the form. This method appears to skip the code that add the actual error message to the form. I'd have to dig into the code a bit more to understand it, but as it is there are at least 3 different types of error messages that I have to parse to get the error message you're seeing in the screen shot.

> maybe I can discuss this with @cvalarida during (or after) the VSA meeting he is presenting at today

@jenstrickland   
> To my understanding this is a stop-gap fix on the current HLR form design, and there is a new design coming that may break up info differently. Is that correct, @Mottie?

@Mottie   
> yes, the flow of HLR. This work (error messages) applies to all forms

@jenstrickland 
> I think @peggygannon has a point. When we have the list of errors that go to where the actual error is, that spot should display the standard error message in place. The list is an enhancement for accessibility.

@jenny-h-l 
> Hi @Mottie, I don't know the context of the situation, but this caught my eye: I noticed the bullets use "pow" not "POW" (all caps). Veterans are likely to react poorly to that. Separately, you asked for ideas to improve the text. Seeing the error message list, my first reaction is that most of the issues are "missing" items. Could you re-write to say "We're missing these items" and then do a bulleted list of the items missing? It would seem easier to scan.  And while one item says "select one type of supporting evidence" that sounds like it's effectively a "missing" type of error too.

@Mottie   
> Thanks for the feedback @jenny-h-l. Yes, there is some formatting that still needs to be done, "POW" is just one case, I hope that I can get a list of abbreviations that need to remain capitalized. I think maybe changing the top line to "The following items are missing, and preventing submission", then only show the name of the item in the bullet list.

@peggygannon
> hi, @Mottie please let me know when you're ready for me to review the error message. It will be helpful for this to be tracked in a Zenhub ticket, rather than here in Slack. I want to be sure the update message following our error message best practices
https://design.va.gov/patterns/messaging-error-messages
https://design.va.gov/patterns/messaging-dictionary

**Comment by Mottie** [comment]
The original PR for this issue (https://github.com/department-of-veterans-affairs/vets-website/pull/11564) was too unwieldily,  so it was broken up into these smaller PRs:

- Update form errors & schema: https://github.com/department-of-veterans-affairs/vets-website/pull/11829
- Centralize number to word conversion: https://github.com/department-of-veterans-affairs/vets-website/pull/11832
- Shift focus to review-row after editing: https://github.com/department-of-veterans-affairs/vets-website/pull/11847
- Move review page alert directly below accordions: https://github.com/department-of-veterans-affairs/vets-website/pull/11849
- Show errors in review - TO DO - ideally, the above PRs should be merged before this can be completed

**Comment by Mottie** [comment]
Last PR being reviewed. Form errors are now set to only show for form 526, in all development & staging environments. It will not show in production.

**Comment by meganhkelley** [comment]
Thanks @Mottie ! I'll let you know when we have clarity on VSP re: how we'd like to proceed on the global form changes. Let me know if you need me to give 👍 on the 526 work moving forward on that PR (I know we had hit pause on it while we had time to sync).

**Comment by luke-gcio** [comment]
Adding into Sprint 27 - we are going to try and eat all of the major technical debt.

**Comment by annaswims** [comment]
This issue is no small thing.  It's happened 194k times to 27k unique users http://sentry.vfs.va.gov/vets-gov/website-production/issues/12188/?query=is%3Aunresolved%20validation

**Comment by Mottie** [comment]
Completed changes associated with this issue include:

- [x] Update form errors & schema: https://github.com/department-of-veterans-affairs/vets-website/pull/11829
- [x] Centralize number to word conversion: https://github.com/department-of-veterans-affairs/vets-website/pull/11832
- [x] Shift focus to review-row after editing: https://github.com/department-of-veterans-affairs/vets-website/pull/11847
- [x] Move review page alert directly below accordions: https://github.com/department-of-veterans-affairs/vets-website/pull/11849
- [x] Highlight accordion errors - https://github.com/department-of-veterans-affairs/vets-website/pull/14465

The remaining work will be specific to form 526 by adding error links to the review & submit page.

Closing this ticket in lieu of #21252
