### ISSUE TITLE
Documentation | Create VAOS to MAP Service / Operational Level Agreement

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21410]
## Tasks

- Duplicate the Agreement form from the Clipboard example https://wiki.mobilehealth.va.gov/pages/viewpage.action?pageId=192853920
- Complete form for VAOS

## Acceptance Criteria

- [ ] Form is complete

- [ ] PDF version of form is attached to this ticket

**Comment by laurenernest** [comment]
No longer needed

**Comment by saneshark** [comment]
I think the way to finalize this SDD is to delete it altogether. This never should have been required in the first place. VAOS FE is an API consumer of VA Mobile Services built entirely outside of the VAMF ecosystem. No new services were built as part of that ecosystem.

Instead, I think we want button up the architecture docs as much as possible and link to MAP docs where appropriate so that those don't need to be maintained in two places. Furthermore, it looks like VAMF now has an integration doc meant deliberately for API consumers such as us. I'll get that added as part of this ticket. Some of the other improvements including updating swagger documentation already live in separate issues.
