### ISSUE TITLE
Design Feedback - Design Intent: eBenefits - Dependency Verification Modal

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#21439]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Remove the bold labels on gray cards (e.g Relationship:). See Sketch/styles/cards for example
- Left align the primary button on the modal. See Sketch/styles/buttons for example.

**Should:**
- Do not use a modal, should be in-page (Ryan)

**Consider:**
- On screen #2, do you really need the second 2 paragraphs? (Ryan)
- On the modal, you could put an Edit/Delete on each gray card instead of the Make changes button at the bottom of the page. This would allow for in card editing. Just another option. See Sketch/styles/cards/interactive cards for example.
- It seems that adding or removing dependents is the primary focus of this page but the button to complete this action is very far down the page. You could move the button “Add or change dependents…” under the gray cards and remove the paragraph explaining how to add or change a dependent.

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by rtwell** [comment]
hello team! cc @KevinMHoffmanUSDS @allison0034 

I’m shifting my recommendation to use a page-intercept design rather than a modal design from **should** to **must** for two reasons:

1. Use case: a Veteran goes to VA.gov to complete a task, clicks sign in, gets a modal to sign in, completes that step, and gets a second (more complex) modal immediately following. 2 modals in a row is 1 modal too many. 
2. The complexity of the interactions that can happen within the modal—particularly on a phone—can get really hard to manage for screen readers, but a page could handle it nicely.

Let me know if anyone has any concerns. Thanks!

**Comment by jason-gcio** [comment]
Thanks @rtwell - So far in looking at straight page-intercepts, it shows that to be tricky to perform with the tools we have in place.  Can we keep going with the modal as we have it until we have some more information around how to do a page-intercept?  There is a sense of urgency from the CFO to have something in place and I think we can iterate with what we have so far.  To address your concerns above:

1. The only time this (double-modal situation) would happen, right now, is if they were getting redirected to the View Dependents page (SSO modal -> redirected to View Dependents -> Dependency Verification modal, which is showing the current dependents on award: an action they were expecting). Once that important question is answered, that modal goes away for a year.  As of right now, we are only showing the modal when visiting the View Dependents page.
2. I think our testing of screen readers might not be that bad, can we see if there are any issues before pivoting in another direction?

I am hoping to use this first version to get some real data around how a Veteran uses this and can definitely see where a landing page for this might be helpful across the spectrum of various Veteran journeys, even leveraging the View Dependents page itself for that.

**Comment by rtwell** [comment]
can you elaborate on this:

> So far in looking at straight page-intercepts, it shows that to be tricky to perform with the tools we have in place.

**Comment by jason-gcio** [comment]
Sure!
Basically, adding a page into a workflow might be difficult to do, especially if that page/feature is built in React - its hard to just pop a page in there based on the `diaryentry` status. If we are doing that somewhere, we would love to learn more about that.  is page-intercept only being contemplated only in the case of static page redirects?

Another version of this we are discussing is around using a modal to simply ask the question "Would you mind confirming your list of dependents?" and then taking them to a page, presumably View Dependents since the list lives there, for an action to be taken.  This had some research done by Kevin Hoffman when they were looking at interrupting flows as well.  That model might help quite a bit if seeing the list in a modal is not favorable as well.

**Comment by micahchiang** [comment]
Hey @rtwell! I have a couple concerns with the page intercept pattern you mentioned, and would love some clarification. 

1. Use case: A veteran navigates to a page on VA.gov which prompts them to log in to access the tool. They log in, but instead of being taken back to where they might expect to go, the tool page, they are instead taken to an unexpected page for which they lack ample context, a page possibly unrelated to their initial task. This feels like a relatively strong anti-pattern to me. As a user, I might click on a link to access a particular show on netflix, sling, or amazon, and feel frustrated or even suspicious if I were to instead be taken to the settings page of the app, or the billing page etc. Similarly, I might click on a link to access my credit card account, and feel frustrated or alarmed if instead of being taken there was instead redirected to another product from the same credit card company. Intercepting a route on login and redirecting a user to a dependency verification page is much the same issue. It feels unexpected. I would love some additional clarification on how you envision the implementation of this page intercept pattern. 

2. From an engineering standpoint, the lift for a page intercept is significantly heavier than a modal. Off the top of my head it probably would involve caching the original URL, and returning a brand new URL when the login process is finished, and then providing a way back to the original URL. Add in a couple of other requirements needed down the road - Accessing dependency verification from anywhere on VA.gov, only showing the modal once per year - and the engineering effort just doesn't feel worth the relatively simple task this feature needs to address, especially considering it could potentially involve fundamentally changing the log in method for VA.gov. These are significant changes to core mechanisms both in vets-website and vets-api, and involve conversations with a much broader group of people outside our direct eBenefits migration team. It feels as if there needs to be a further conversation around the trade offs between managing modal complexity and engineering effort required for a page intercept, and whether or not the juice is worth the squeeze. 

Anyway, those are the concerns that I have off the top of my head. Again, to reiterate, I'd love to hear more about an implementation plan for page interception, since I can't envision it without the aforementioned concerns being avoided. Looking forward to hearing more of your thoughts. Thanks!

**Comment by rtwell** [comment]
thanks for the background/additional info! For the record, I promise I'm not trying to add churn.

1. Modals should be used for simple, focused actions or information sent to help users make a decision (e.g. are you sure you want to delete X? Yes or No). The current design has the following challenges that deviate from this principle: 
    a. there are two "screens" within the modal (make sure dependents are correct and thank you)
    b. there is an additional interaction on one of them (When should I notify VA about…) which can make modals hard to use on phone, weird focus management, assistive tech
    c. These modals are quite tall on mobile (of which I have not seen a mock up of any mobile screens). Scrolling with a modal open on a mobile device that has other interactions built into it can lead to errors and frustration.
If there is a way to simply these ☝️  then the modal wouldn't as much of a problem

2. @micahchiang the _user flow_ for any intercept should be the same for a page or a modal. *When* we decide to intercept is the question, not the how. With either approach, the user has the choice to opt in to make edits, driving them away from wherever they were going, or not. **This is a UX problem (user flow) not UI (modal vs page) problem.** If we solve for the UX of this dependency interaction, again, a modal might not be bad. I don't know if we would trigger as much engineering work as you suspect, esp if we're limiting the interaction to users already authenticated and on their way to the dependency page. Jason's suggestion above sounds like it's moving in the right UX direction to me.

3. I cannot speak to the engineering lift and the implications this approach might incur, I leave that to the PO of this team to decide. If the pressure to deliver + the work to get there is too much for now, I would expect this team to create an issue to revisit the modal in a future sprint, ideally in a timely manner.

Thank you all for the hard work and patience as we wrestle with these complex problems!

**Comment by jason-gcio** [comment]
Thanks @rtwell - We really appreciate the feedback and will include these ideas as we move forward.  We can definitely commit to creating issues for more iterations in this space and will definitely keep you posted on developments.

**Comment by jason-gcio** [comment]
The must feedback has been incorporated and we have tickets addressing an inline version of this feature to live on this page in the event the modal window is moved elsewhere.
