### ISSUE TITLE
[Cheetah MVP] E2E Staging testing

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21487]
## Summary
Request for end to end testing for the MVP vaccine scheduling flow in Staging to identify any bugs prior to launch.

### VA.gov Feature Toggle
`va_online_scheduling_cheetah`

Toggle is currently ON in [Staging](https://staging.va.gov/)

### Designs & Copy
- All specs for dev: https://www.sketch.com/s/e3493682-f69f-4910-a45c-36720e9639d9
- Copy docs https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/products/health-care/covid-vaccine-distro/vaos-for-distribution-initiative/copy-docs

## Tasks
- Mobile and Desktop E2E tests
- Document bugs in GitHub and assign to @laurenernest for review and prioritization
- Document questions that arise (in this ticket or attach a separate doc)

## Recommended Scenarios
- User is registered at facilities that offer online scheduling, but have already had an initial dose.
  - Clinic set up correctly
  - Clinic not available
- User is registered at facilities that offer online scheduling and have not had an initial dose.

## Known Issues
None

## Additional Notes
- Here's a [Cypress best practices document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/testing/end-to-end/cypress-best-practices-on-vsp.md#viewport-presets-cyviewportpresetpreset-orientation-options) that includes notes on how to test multiple views.

**Comment by marcynadeau** [comment]
@laurenernest @beth-wodzinski 
I have found a couple issues so far:
1.  COVID Appt does not display in upcoming appointment list:  After I book a COVID appointment, the appt is not displaying on upcoming appointment list. I have to refresh the page to have it displayed.   This is not happening in the normal appt flow.  Steps to recreate:  Go through steps to direct schedule COVID appt.  At the end of the booking process, system confirms booking details.  Select to "view your appointments". System takes you back to home page.  Expected Response:  COVID appt displays in upcoming appointments. Actual Response:  COVID appt is not displayed in list of upcoming appointments.  User must refresh page to see new COVID appt.

2. Wrong/Misleading Error Message Wrong when Appt Can't be Booked:  If the appointment can not be booked system is displaying an error to tell the user to wait a day and try again and this is wrong information.   1) Go into VAOS and select to direct schedule an appt. I chose COVID. 2) Proceed until clinic availability is displayed. 3) Concurrently in VistA schedule an appointment for the same date/time that veteran in VAOS is about to select.  4) In VAOS select the date/time and confirm booking.   Actual Response:  Dev tools shows a 502 error with RESULT(0)=APTNOST^NO OPEN SLOTS THEN.  To the user,  VAOS shows an error message and tells them to wait a day and try again.   Expected response: Not sure what should happen but the error message that displays is incorrect. 

3.  Select to Book an appointment at Cheyenne in COVID CLINIC 2.  Since all slots have been booked, no availability system just shows a blank grey calendar.  I doubt Veterans will not know what this means.  It is just a calendar with all days in grey and nothing can be selected.

**Comment by laurenernest** [comment]
Logged #21567 and prioritized.
> 1. COVID Appt does not display in upcoming appointment list: 

---

Thanks for noting the ticket already created!
> 2. Wrong/Misleading Error Message Wrong when Appt Can't be Booked:
> This issue was previously logged in #20080

---

Thanks for noting the ticket already created! We also have it noted in #20789 and want to capture data for how often it occurs.
> 3. Select to Book an appointment at Cheyenne in COVID CLINIC 2
> This issues was previously logged in #17637
