### ISSUE TITLE
UI for multiple clinics in history

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#2149]
## Story
As a veteran, I want to be able to choose which clinic of the ones that I've been to before I want to schedule into, so that I can go to the clinic that most closely matches my existing needs.

## AC
- [ ] Multiple clinics are shown when veteran has multiple clinics that match 
Need a new UI for cases where a veteran has several clinics that they've been seen at within a given type of care & facility.
- [ ]  'This option doesn't work' / 'None of these options work' is shown whenever 1 or more clinics are in the list, respectively
- [ ] veterans go into request flow if haven't been seen at any clinic within that clinic + type of care combo (skip page)
- [ ] veterans only see this page if primary care or mental health care types were chosen

![Multiple Clinics](https://user-images.githubusercontent.com/1969/66064412-5386e700-e513-11e9-88db-afc2d0715b1a.png)

![One Clinic](https://user-images.githubusercontent.com/1969/66064723-f63f6580-e513-11e9-9deb-363e506e3929.png)

**Comment by markgreenburg** [comment]
@goldenmeanie could we please get an updated mock? The addresses won't be necessary here b/c all the clinics will be coming from the same facility. Not sure if you just wanted to strip that out or if you think other clinic-level info would be more helpful.

**Comment by goldenmeanie** [comment]
Ok, given less data and the focus on one facility, I've revised the screens.

Many clinics:
![Choose a clinic – three@2x](https://user-images.githubusercontent.com/1969/66064412-5386e700-e513-11e9-88db-afc2d0715b1a.png)

Only one clinic:
![Choose a clinic – one@2x](https://user-images.githubusercontent.com/1969/66064424-5c77b880-e513-11e9-8b7d-694db6fd51a6.png)

If there are no clinics, then they don't see this screen they just silently go into the request flow. If they select "this doesn't work for me" option it takes them to the request flow.

**Comment by lalexanderson-dsva** [comment]
@markgreenburg @goldenmeanie @jbalboni:  The language here is critically important. We really need to express: these are clinics where you have been before, not just "choose a clinic". I asked @jenniferlee-dsva for a bit of content wisdom. 

I think we do need to pull in the facility address if possible, as shown in the mockup. The user has selected it on the previous page, so we should be able to get that, right?

**Comment by jbalboni** [comment]
We don't get the facility address from any of the VAOS backend services (just name and city/state), but we could fetch it from the va.gov facility api at this point, since we know the facility. The address is going to be the same for all clinics, that's why Mark suggested removing it from displaying for each clinic choice, but there's no issue with displaying it on the page somewhere if that's what we want.

**Comment by lalexanderson-dsva** [comment]
I think if we know the facility location we should display it on the page. Veterans seemed more confident in choosing a clinic when supported both by the language "you've been here before" and the address of the facility where they are trying to go.

**Comment by jenniferlee-dsva** [comment]
@lalexanderson-dsva - uploading suggestions here in Word. Without going through the possible user flows, it was hard to understand exactly what the UI copy should say. I took a best guess -- albeit limited without knowing what might come before and after. Take this with a grain of salt because of that. 

[appointment-locations-screen-copy-draft-100919.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3708126/appointment-locations-screen-copy-draft-100919.docx)

**Comment by jenniferlee-dsva** [comment]
[appointment-locations-screen-copy-draft-100919-v2.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3708162/appointment-locations-screen-copy-draft-100919-v2.docx)

Of course, as soon as I uploaded it, I got an ah-ha! moment. Take another look...

**Comment by jbalboni** [comment]
@jenniferlee-dsva @lalexanderson-dsva 

This is my rough attempt based on the designs and content updates in here. It's not exact yet, but thought it was worth running past you both and seeing if it sparked more thoughts:

![Screen Shot 2019-10-10 at 5.08.29 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/39b33348-58f8-4353-90c2-926552cf19af)
![Screen Shot 2019-10-10 at 5.07.38 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/7ff06e5c-5433-45b3-a886-9929954f78c4)

Also, for what it's worth, it seems risky to use "VA location" in this context, because we've already asked for the location on a previous page and this is for choosing between clinics at a single VA location.

**Comment by jbalboni** [comment]
Yeah, I think there's some language clashing happening on the word clinic. Using Pittsburgh as an example:

1. There's the Pittsburgh health care system (code 646), which is also a facility in an of itself.
2. There are a bunch of child facilities in that system, like the Beaver County VA Clinic (code 646GC)
3. Each facility has a bunch of "clinics" defined in the VistA system, with names like "BEAVER - PC - SWEIGART."

The VAOS app guides you through each of those steps. On this page, you've made it to step 3, so you've already chosen something like Beaver County VA Clinic and now you're choosing some kind of office or abstract entity at that Beaver County facility. The word "clinic" seems like it can refer to what you're choosing in step 2 or 3, which is confusing.

I don't know what the right language choices here are, I just wanted to clarify the way the VAOS tool's flow fits together with VA facilities and locations.

**Comment by lalexanderson-dsva** [comment]
agreed @jbalboni that we should NOT use the word location, and stick with clinic.

**Comment by lalexanderson-dsva** [comment]
Suggested lang for this:

Title: Make a {toc} appointment at your last clinic: 
Sub head: Your last [toc] appointment was at {clinic name} in this location:  

{Facility name}
{Facility address}

[radiobutton] Yes, make my appointment here.
[radiobutton] No, I need a different location.

**Comment by jbalboni** [comment]
@lalexanderson-dsva What text do you want for the radio buttons for the clinics? Just the friendly name (or real name if that doesn't exist)? What about for the option at the end?

**Comment by jbalboni** [comment]
I've put updated screenshots in https://github.com/department-of-veterans-affairs/vets-website/pull/10890
