### ISSUE TITLE
CT Redesign: Location Search Solution - Interactive Prototype, Mobile

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#21504]
UPDATED TICKET DESCRIPTION: 

Mobile prototype for landing page has been updated to match existing

Mobile prototype **name search results**  has been updated to match existing

**Location search** updates to include 
* no results on map display
* map interaction for individual results 
  * clicking on a letter  / result in map view pulls relevant item in list view to top of list (Visible when the user clicks to list view; default listing is A - the closest facility to the searched term)
  * going back-forth from list to map view
  * clicking on a letter / result in map view displays element on map view page (pop-up tool  tip or possibly a bottom sheet, with X in the corner so people can close it easily)  This is may be an enhancement and would need to be validated with OCTO-DE

(Review facility locator research on map usage

Mobile experience: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/mobile-experience

Facility Locator general: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator

**Comment by amyknox** [comment]
Updates include:
- modifications from invision prototype comments
- Search disambiguation

**Comment by amyknox** [comment]
**UX SYNC: Search Disambiguation**

**Location search distance options**

- Within 5 miles
- Within 25 miles
- Within 50 miles
- Within 75 miles

**Type ahead drop-down based on CT data (or mapbox data… lower LOE)**

- ASSUMES dropdown items are city, state, and not points of interest
- Visual to come: dropdown style based on current CT implementation

**Search for single term that matches state name [Washington],**

- User does not click drop-down item
- User hits enter on keyboard,
- Show results for STATE
- Visual to come: "Did you mean" with alternate items (clickable links) which populated dropdown; "Did you mean" appears in horizontal row above filters / map

**Search for single term that doesn't match state name [Springfield],**

- User does not click drop-down item
- User hits enter on keyboard (instead of selecting a typeahead option)
- Show results for "top" matching search term
- Show "Did you mean" with alternate items (clickable links) which populated dropdown. "Did you mean" appears in horizontal row above filters / map

**WHEN NO RESULTS…**

- Sample language from Facility Locator for no results: https://www.va.gov/find-locations/?page=1&address=jesup.%20ia&facilityType=health&serviceType=WomensHealth&latitude=42.4755&longitude=-92.0638&radius=17&bounds%5B%5D=-92.8138&bounds%5B%5D=41.7255&bounds%5B%5D=-91.3138&bounds%5B%5D=43.2255&context=Jesup%2C%20Iowa%2C%20United%20States
- Visual to come: Location search with no results
