### ISSUE TITLE
VA.gov Search Consistency - Mock Up Find a Form Results Based on Possible Fields

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#21513]
## User Story

As a user I would like to see consistent design across all VA.gov search tools so that I don't have to re-learn a new pattern for each tool.

## Expected Behavior

VA.gov search tools follow the same design patterns as much as possible, based on the v[arious fields/metadata](https://github.com/department-of-veterans-affairs/va.gov-team/issues/21438) that may appear in the search results.

## Acceptance Criteria

- [ ] Mockups for various search tools are completed
- [ ] Accessibility has reviewed and provided feedback
- [ ] Design has reviewed and provided feedback

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 I think we talked on a call about only displaying the first 50-100 characters of the "When to Use" text in the Find a VA Form search results for consistency, but wanted to make sure to put that here as well. 

Most forms currently **don't** have that info, but it's something we want to add, so just keep that in mind. Thank you!

**Comment by callen2563** [comment]
I'm uploading the mocks I've created so far. After chatting with, Josh Kim, Marci and the unauthenticated team I will be making some adjustments to these but wanted to show the progress. 

[Find a Form mobile ](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4#/447613731_Find_A_Form_-_Mobile)

[Find a Form desktop](https://vsateams.invisionapp.com/share/SD10IE31CENR#/447613824_Find_A_Form_-_Desktop)

**Comment by callen2563** [comment]
FAF Update - I have just updated the InVision mocks to have the 17pt Serif, Bitter font that the unauthenticated team and I decided on based on the current styling on the majority of header stylings. I'm working with the design system team to update the action link to a square font awesome icon so that it is in alignment with the link next to it. 

[Find a Form mobile ](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4#/447613731_Find_A_Form_-_Mobile)

[Find a Form desktop](https://vsateams.invisionapp.com/share/SD10IE31CENR#/447613824_Find_A_Form_-_Desktop)

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @callen2563! Looks great! I really love the square icon for the online tool; nice and clean.


I also like that the online tool and PDF links side-by-side visually reinforces that one is equivalent to the other.

**Comment by callen2563** [comment]
Thanks Marci! Also - Leyda, Megan and I are meeting next week to discuss the spreadsheet of additional elements across tools that also need consistent styling. So we will be updating this thread with more mocks soon.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 @mgleo - Since this ended up being significantly more work than could be completed in a single Sprint, I will close this ticket, and we will create separate tickets for each product (Global, R&S, Find a Representative) so that you can keep each element's info contained.  They will still be attached to the same Epic, so it will be easy to see them all listed together.

**Comment by callen2563** [comment]
Edits were made to FAF:

- action link was updated 
- removed download icon from download link
- search bar: the grey background was removed to accommodate the [new main search page left rail](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21376) as it was no longer fitting in that space and in order to keep the search UI consistent on all search tools Megan, Leyda and I are proposing to remove the grey container on FAF

[Find a Form mobile ](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4#/447613733_Find_A_Form_-_Mobile_3)

[Find a Form desktop](https://vsateams.invisionapp.com/share/SD10IE31CENR#/447613826_Find_A_Form_-_Desktop_3)

**Comment by MarciMcGuireGCIO** [comment]
Hi @callen2563 have you finished your work on updates to Find a VA Form?  Just wondering if this ticket can be closed out.

**Comment by callen2563** [comment]
I just confirmed with Megan that we are done with the UI consistency updates so let's close this ticket

**Comment by MarciMcGuireGCIO** [comment]
Great! Thank you!
