### ISSUE TITLE
Content review: Vet Center taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#21531]
## Content review request
Requesting a review of proposed taxonomy for services provided at Vet Centers for new Vet Center pages, including: 

- Service name
- Veteran facing name 
- National description 

## Project background

This taxonomy will be used to describe the services offered at the 300+ Vet Centers and satellite locations across the country. Vet Centers are community-based counseling centers that provide a wide range of counseling, outreach, and referral services to eligible Veterans, active duty service members, and their families. Veterans are eligible for Vet Center services regardless of discharge status (unlike VA medical benefits). Because of this difference, Vet Centers may refer to the VA or community partner organizations to serve a Veteran's needs. Vet Center benefits never expire so Veterans can be engaged in services off/on/continuously throughout their lives. 

Vet Centers will use some of the VHA service taxons but may need to change the description to reflect the non-medical nature of the services offered. Vet Centers need to avoid words that imply medical care (such as "medication") and generally prefer "care" and "counseling" over "treatment". We're also proposing the addition of several new services not yet available in the taxonomy. 

The VHAhealth service taxonomy can be viewed on the [Pittsburgh health care pages](https://www.va.gov/pittsburgh-health-care/health-services/) for context. 

<details>
<summary> VAMC services </summary>

![image](https://user-images.githubusercontent.com/55411834/111187429-9575e280-8579-11eb-9265-e673994b891c.png)

</details>

## Request

We're beginning to build the MVP for these pages and need to have content eyes on these service taxons and the descriptions. We've been actively engaged with Jessica Schiefer (Communications Officer for Vet Centers) and a group of Outreach Specialists for our first 10 beta sites. They've given input on these services and the descriptions. 

I added a tab in the attached working spreadsheet [Vet Center National Description Working doc (2).xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6143151/Vet.Center.National.Description.Working.doc.2.xlsx) for you. You'll be able to see where we started on "Michelle's tab" as well as Jessica's feedback/edits. 

Please review the following for plain language. 

- Vet Center service name 
- Veteran facing name  
- Proposed Vet Center national descriptions 

I included the VHA national descriptions for context but they're already in Prod - no need to review. The "local description" is also a work in progress and is similar to the "Care we provide..." area in the Pittsburgh health services. 

Please let me know if you have any questions!

**Comment by bethpottsVADEPO** [comment]
@mmiddaugh Attaching rewritten descriptions and Vet Center service names (only 2 needed editing, so I called those out in red font) here in the excel spreadsheet. Let me know if you have any questions or want to talk through any of them. I wasn't sure what to do with the Veteran-facing names since a lot of those were missing. I can revisit that content if it would be helpful. 

Also, @DanielleThierryUSDSVA has been buried in COVID work, so she couldn't take a look at this, but she'll likely want to have input at some point. You may hear from her when she comes up for air. Or go ahead and ask for her to check it out once my edits have been incorporated. Thanks!

[https://app.zenhub.com/files/133843125/bea0bc52-2818-4551-a22b-3280d5e3931d/download](https://app.zenhub.com/files/133843125/bea0bc52-2818-4551-a22b-3280d5e3931d/download)

**Comment by davidconlon** [comment]
thanks @bethpotts !
This is fantastic.  We'll proceed and if/when @DanielleThierryUSDSVA gets some air/bandwidth we would love a future iteration.

**Comment by mmiddaugh** [comment]
Many thanks, @bethpottsVADEPO
