### ISSUE TITLE
Folder  system_folder attribute incorrectly shows as false when getting an individual folder

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#21554]
I noticed that when listing folders, `system_folder` is correctly set to true for any of the inbox/sent/deleted/etc folders.
`http://localhost:3000/mobile/v0/messaging/health/folders`

But when getting an indidivual folder resource, `system_folder` is always false for those  folders.
`http://localhost:3000/mobile/v0/messaging/health/folders/0`

This may be low priority because I don't even know that the mobile app has any use case for getting an individual folder vs. the list, but I would like to understand why that is happening so that it's not a lingering bug that we run across later.

**Comment by patrickvinograd** [comment]
I confirmed that the same behavior is seen when invoking the MHV API directly - so it's a bug there, not in how we are interpreting the response.

**Comment by narin** [comment]
MHV has created a [JIRA Ticket](https://vajira.max.gov/browse/MHV-14046) for this work and it has been marked as low priority since we aren't likely to use this endpoint in the mobile app.

Trello ticket here: https://trello.com/c/shXxR9iO/6-systemfolder-attribute-on-folders

Moving this to the Post-MVP Backlog for now.
