### ISSUE TITLE
Are we creating duplicate proc IDs?

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#21675]
## Background
When submitting a 674, we have found that there are sometimes duplicate proc IDs which is strange.  We need to investigate this and determine where the issue lies (within VA.gov or within BGS)

## Tasks
- [x] Debug the 674 submission to understand where the duplicate is coming from.

## Acceptance Criteria
- [x] A path forward can be established and documented in GH as applicable

**Next Steps**
- Write notes and/or tickets about next steps

**Comment by digitaldrk** [comment]
Is it possible they are both 686 and 674 submissions generating proc ids?

**Comment by kathleencrawford** [comment]
> Is it possible they are both 686 and 674 submissions generating proc ids?

While we were doing testing, we submitted just a plain 674.  However, on the BGS side, they seemed to get a proc id for a 686 and then another proc id for a 674.  I haven't been able to reproduce the error locally yet.

**Comment by kathleencrawford** [comment]
I do not see evidence of us creating duplicate proc IDs...I don't see this happening anywhere in the logs.  However, I am getting the CASE ALREADY ESTABLISHED error back when trying to insert the claim.  I'm still trying to track down the root cause of this error.  I think it may be a red herring and the error is actually something else, but I haven't determined what is causing it yet.  I am still troubleshooting.

**Comment by jason-gcio** [comment]
Per our convo, let's get some data/feedback from RBPS/BGS and go from there with potentially a new ticket.  Closing this but reopen if needed.
