### ISSUE TITLE
[Design] Define Color Thresholds in Analytics MVP

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#217]
## User Story
As a product owner, I need to understand my tool's critical indicators to iterate my product for successes and errors and improve the veteran experience.

## Goal
Define the color thresholds on the metrics of the Google Sheets MVP to clearly state what the colors mean in order for the product owner to see 'critical' metrics, either successes or failures. 

## AC
- [ ] Google Sheets MVP's color thresholds are defined and documented.

**Reference**: #134 
CC: @smoonpeyes will ask for design validation

**Comment by nedierecel** [comment]
@joanneesteban @smoonpeyes With the shading, one thought for MVP is to indicate increases or decreases by green or red rather than having the thresholds at this time.

**Comment by smoonpeyes** [comment]
@nedierecel I think we should consider up/down arrows to indicate increases and decreases for 508 compliance. Color coding may not work for users who are color blind.

**Comment by joanneesteban** [comment]
Would it be too cluttered to have both?

**Comment by joanneesteban** [comment]
We run through 2 options for defining these thresholds:

1. **Time based**: 
  - Definition: Up Arrow/Green for an increase from the previous week/month for Success Rates, Events, & Funnel Conversions as well as a decrease from the previous week/month for Error Rates, Repeat Event %, and Latency. Down Arrow/Red for a decrease from the previous week/month for Success Rates, Events, & Funnel Conversions as well as an increase in Error Rates, Repeat Event %, and Latency.
  - Build: To automate this, it would require a bigger BE lift where both current and previous week/month will need to be pulled and compared on the dashboard. 

2. **% Thresholds**:
  - Definition: Up Arrow/Green for Successes Above 99%, funnel conversion above 90%. Down Arrow/Red for Error Rate Above 1%, repeat event above 5%, funnel conversion below 70%, and Latency above 30ms.
  - Build: This can be built using current weekly/monthly numbers and automated using formulas/conditional formatting on Sheets.
  
@nedierecel For the 2nd option, please validate/edit threshold numbers as you see fit. 
@smoonpeyes @amycesal  
I think the 1st option is a better use of data interpretation for users, but for the MVP, I suggest we go with the 2nd option for a working prototype. Perhaps evaluate in user testing what would work better for the users to improve their products. 
The other thing is if using the up/down arrows, it might make sense to find other symbols since we have both _successes_ and _failures_ as data points.

**Comment by nedierecel** [comment]
@joanneesteban Additional feedback:

1. *Time-Based*

- Build: I agree the lift to implement would be high for MVP. When we get to the research portion of the roadmap that identifies tools, this may remove some of the frontload work to calculate changes.

2. *% Thresholds%

- Definition Feedback: Since WBC, funnel conversion rates across the forms vary, 90% would be too high. I indicated below where I've used the median since WBC launch. 

a) Up Arrow/Green for Successes Above 99%, funnel conversion above *38.5*% (This was the median for all goals).   
b) Down Arrow/Red for Error Rate Above 1%, repeat event above 5%, funnel conversion below *38.5%*, and Latency above 100ms.

For planning, Google Analytics doesn't expose `Funnel Conversion` rate in the API. It's an important metric, but we should consider this as an automation issue for future phases.

**Comment by joanneesteban** [comment]
Per @amycesal, 4 color/symbol categories:
- really good (blue star)
- neutral (no symbol)
- sorta bad (pink hexagon)
- needs attention (larger red hexagon)

**Example**
![image](https://user-images.githubusercontent.com/48964695/59532106-c3feef00-8eb5-11e9-9f44-ff42d79787e4.png)

**Comment by amycesal** [comment]
Red and green, commonly know as the "stoplight colors" are actually not a great color scheme to use for people to differentiate them. It's bad for people who are color blind because they can't see a difference in the two shades. 
http://stephanieevergreen.com/no-more-red-yellow-green/

Pulling from the USDS color palette, I looked for a paring that would still read as positive and negative, but would also work for people who are colorblind.

<img width="794" alt="Screen Shot 2019-06-13 at 5 33 35 PM" src="https://user-images.githubusercontent.com/1656046/59621968-63162780-90fe-11e9-9f25-e49d37e53f91.png">

Pulling from the **Red** and **Cyan** families work for colorblindness. 
<img width="785" alt="Screen Shot 2019-06-13 at 5 34 16 PM" src="https://user-images.githubusercontent.com/1656046/59621969-63162780-90fe-11e9-958f-baa36b938c02.png">

I also re-bucketed the existing conditional formatting to fit the success and error metrics. 
<img width="169" alt="Screen Shot 2019-06-17 at 12 55 52 PM" src="https://user-images.githubusercontent.com/1656046/59622348-4e865f00-90ff-11e9-99fb-a8f4a5bf6121.png">
<img width="1079" alt="Screen Shot 2019-06-17 at 12 56 01 PM" src="https://user-images.githubusercontent.com/1656046/59622355-55ad6d00-90ff-11e9-9b9e-d10fa925f620.png">



And explored the use of icons to add an additional layer 

<img width="195" alt="Screen Shot 2019-06-17 at 12 56 53 PM" src="https://user-images.githubusercontent.com/1656046/59622391-6f4eb480-90ff-11e9-9a88-3a82bae57b7c.png">
![Uploading Screen Shot 2019-06-17 at 12.57.01 PM.png…]()
