### ISSUE TITLE
Create local Product Health Tool site using Google Analytics data

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#2180]
## User Story or Problem Statement
How might we design an interactive MVP of the product health tool with the Insights Grey Sky design?

## Goal
Make the paper Grey Sky Product Health Tool mockup into an interactive site using available Google Analytics data.

## Objectives or Key Results this is meant to further
Implement second iteration of Product Health tool by Q1 2020

## Acceptance Criteria
- [x] Jon introduces Nicola to Google Analytics API
- [x] Jon provides relevant Education GA data to Nicola
- [x] Nicola creates local site with GA data on Education
    - [ ] Query for real data for each education product
    - [ ] Add ability to update charts based on selected product
    - [ ] Code the chart in D3 instead of Chart.js so it matches design features
    - [ ] Add Oauth2 to react app so the app itself can make the queries
- [ ] _Stretch_ Jon product use discovery for Education

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
@deweydell Could you add screenshots of the local site with notes by EOD today?

**Comment by deweydell** [comment]
I updated @joanneesteban, but here is where I am so far:
I have a chart with real data from OAuth spiked out with Chart.js:
<img width="1132" alt="Screen Shot 2019-10-15 at 8 43 24 AM" src="https://user-images.githubusercontent.com/11186572/66832535-1dd8f980-ef28-11e9-954b-b4ba6577101c.png">

I also have started a react app to reuse charts and be able to query multiple educatio products from a dropdown:
<img width="1180" alt="Screen Shot 2019-10-15 at 8 43 34 AM" src="https://user-images.githubusercontent.com/11186572/66832548-22051700-ef28-11e9-9b1b-df4ec8a7b8df.png">

These are my main priorities:
- Query for real data for each education product
- Add ability to update charts based on selected product
- Code the chart in D3 instead of Chart.js so it matches design features
- Add Oauth2 to react app so the app itself can make the queries

**Comment by joanneesteban** [comment]
Thanks @deweydell! I'm removing the Call Center data from this issue and branching it off to a separate issue (https://github.com/department-of-veterans-affairs/va.gov-team/issues/2480)

**Comment by deweydell** [comment]
Status Update as of 3pm:
- Will reach out to front end channel re: how to create a new repo on github in the org
- since the product is still being shaped, the plan is to create a separate repo and host it on github pages for review purposes
- Will post screenshots by EOD of d3 charts and progress

**Comment by deweydell** [comment]
Status update 10/28/2019:

- Published to this repo: https://github.com/department-of-veterans-affairs/product-tool
- Video demo of the tool in it's current state: https://drive.google.com/drive/folders/1fpfILNWQ0TyHfn17ctsr18ZquvCKVnPw 

Features:
- Right now the tool only makes requests for the following metrics:
  1. Page views on introduction page
  2. Successful online form submissions 
- Metrics table with bars that show if the metric is below or above target. Right now hardcoded to show as "above" since the targets are set to zero.
- Information and form URL printed for each form
- Three charts per form, one for each of the two metrics above and then a hardcoded empty paper forms chart.
