### ISSUE TITLE
IA Request - BAM1 - Notice of disagreement

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#21819]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After completion of usability/prototyping, prior to moving to development

## Required Inputs:
- Link to product outline: [Notice of Disagreement](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/readme.md)
- Link to or attach [prototype or mockups ](https://vsateams.invisionapp.com/share/8Y10I6K7DU9R#/447558866_NOD_-_Info_Page)
- Link to research readout/results (https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/Notice-of-Disagreement/_NODResearchPlanUsability.docx)
- Link to [reseach history masterlist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md) showing that you have added your research to the list as applicable
- Link to or attach your content source of truth/final content including H1s (if separate from prototype/mockup)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**SEO Keywords** - Provide a list of keywords used by your target audience when they talk about or search for your content

**Proposed site map/page structure** - Provide link or image of proposed page structure (if more than one page)

**Suggested URL(s)** - Provide suggested URLs and any background or rationale

**Suggested entry points** - What is the primary entry point for users to find your new content/tool - consider benefit hub pages, top nav, left nav, footer, profile/account, home page, etc.

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized?

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
IA approach is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-board-appeal.md

A couple notes:
- Please work with the sitewide content team for:  static content page modifications and left nav implementation.  
- I'm happy to help with the final URL slugs for each form chapter/page, but would need a list/breakdown of all the pages (hard to decipher what is a new page vs display state in a prototype).  Otherwise yout team can determine those.  A few tips: keep each one to 1-2 words max, use plain language, match to the purpose or title of the page, avoid insensitive language (i.e. disabled, homeless, etc). 

Let me know if you have any questions on anything.  You are welcome to close this issue at your discretion.

**Comment by mnorthuis** [comment]
@vhenry07 @Mottie Hi, I was just looking back on this one, and I may have made a mistake in terminology in the URL.   I noticed that I used the word "review" rather than "appeal" in the URL, and in looking back, I'm seeing all content reference "Board appeal" as the top level term, and a "direct review" is one of the options.  I'm worried that using the word "review" in the URL may be confusing and is  inconsistent.  

Can you let me know if this is something that can be corrected prior to launch?  Completely my miss, but hoping we can correct it!  Let me know if you can, I'll update documentation. 

Revised url would be  www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/

**Comment by Mottie** [comment]
Hi @mnorthuis!

Yes, it won't be a complicated fix, but I won't implement it until after review & demo tomorrow since it'll break the path to the form. I'll open a ticket and put it on my list for next sprint. Thanks for following up!

**Comment by mnorthuis** [comment]
@Mottie Perfect!  Thank you and sorry for the rework on that one!

**Comment by mnorthuis** [comment]
@vhenry07 You can close this issue when you have the information you need.  IA will remain documented outside this issue here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-board-appeal.md
