### ISSUE TITLE
Mobile xsmall screen level text wrap issue

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21810]
## What Happened?
On xsmall screen sizes, the full level text link drops to the next row, leaving the icon by itself on the first row.

## Specs:
- Device: Mac
- Browser: Chrome
- Test User _(if applicable)_: any

## Steps to Reproduce

1. Sign in to va.gov
2. Go to VAOS homepage
3. View page between 320-370 screen size

## Actual Results
Icon and level text are on separate rows
![Screen Shot 2021-03-19 at 4.10.16 PM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/a78d362f-e4c9-4d6a-98b8-9a4f04682806)

## Expected Results
Icon and level text fill the first row, with overflow text wrapping below

## Acceptance Criteria
- [ ] Icon and level text fill the first row

- [ ] Mobile breadcrumbs follow the Design System
- https://design.va.gov/components/breadcrumbs
- https://design.va.gov/storybook/?path=/docs/components-breadcrumbs--mobile-first
- If implementation matches Design System, add note in this ticket (so issue can be raised to VSP)

**Comment by LanceGundersen** [comment]
@caw310 I took a look at this and I think the wrapping is not VAOS specific. However, It does look like it shows up in the smaller screen sizes for us due to the longer breadcrumb.

**Comment by outerpress** [comment]
Confirmed seeing this if I modify breadcrumbs outside VAOS so that they're longer than one line.

@CrystabelReiter this looks like a design system issue - should I create a new ticket for it in [VSP documentation](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/labels/vsp-design-system-team?page=2&q=is%3Aopen+label%3Avsp-design-system-team) or just tag it for y'all?

Same issue in benefits hub:

![staging.va.gov_health-care_about-va-health-benefits_(iPhone 5_SE) (1).png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/4d9bee20-fbde-4e84-93a5-f039e01a61bd)

**Comment by CrystabelReiter** [comment]
@outerpress Thanks for being patient in my response, I'd make a ticket for VSP documentation if it isn't urgent.

**Comment by outerpress** [comment]
No rush on our side @CrystabelReiter - here's the VSP ticket: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/469

@laurenernest I think we can close this ticket out on our end.

**Comment by laurenernest** [comment]
Further action to be taken by Design System team. Closing ticket.
