### ISSUE TITLE
General Analytics Request for VAOS for Distribution Pilot

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#21931]
# Metrics Reporting Request

## Instructions

Please fill out the following sections:
- [x] Description
- [x] Timeframe for Analytics Requested
- [x] Analytics to Track Down
- [x] Which Product Questions are you trying to answer?
- [x] Additional Comments

## Description
Who is this request for?

- Lauren Ernest
    
- What team/project is this work for?
    - VAOS - COVID-19 vaccine scheduling
    
- What type of analytics support are you looking for?
  - [ ] one time metrics report (this is not a KPI dashboard, but a temporary or a one time report)
  - [x] metrics clarification (verification that the metrics you are looking at are being read accurately)
  - [x] analytics discussion (please share if you're looking for a general conversation, a KPI setting meeting, etc. in the "additional comments" section)
    

## Timeframe for Analytics Requested
_Please provide the timeframe for the metrics you are requesting._
What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?
Starting Tuesday, March 30

## Analytics to Track Down
- Conversion
- Submissions
- Facility/clinic availability
- Problematic pages/areas in the funnel

## Which Product Questions are you trying to answer?
- How is the pilot performing?
- What improvements can we make before rolling out to more sites?

## Other Helpful Questions to think through
- Who is your audience? Pilot sites, OVAC, DEPO
- Why do you need this data? Monitor pilot launch of initiative
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data? Daily

## Link to Metrics
- Short funnel https://analytics.google.com/analytics/web/template?uid=XnWPpwPIS1KehjY_2qv2xw
- Pilot dashboard https://analytics.google.com/analytics/web/template?uid=mbQoPORFRu2KYqEOMamA0Q
- Larger funnel (Analysis Hub) - the sharing function is disabled for me so here's a snapshot of what I tried to set up
![Screen Shot 2021-03-23 at 8 36 40 AM](https://user-images.githubusercontent.com/72046525/112176264-30dc0880-8bb5-11eb-90d6-43f1dc9e5bab.jpg)

## Additional Comments
Pilot planned to start Tuesday, March 30 so would like to validate what I've set up is correct and will pull in data as soon as there is some in Production. The performance of this pilot will be closely monitored, with daily reviews of the data.

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@laurensimpson14 have assigned you here - thanks in advance!

**Comment by laurensimpson14** [comment]
Hi @laurenernest, 

I’ve looked through both the short funnel and the pilot dashboard, and below are my comments:

##Short Funnel
With this funnel are you looking to see simply how many start the funnel and how many reach the submission? Or are you interested in knowing abandonment between the start and the end? If you are interested in knowing abandonment between the start and end, which is how you have it set up currently, then below are my suggestions. However, if you are interested in only how many start and finish then you would need to only add the “path-started” and “submission-successful” events.

The first step in your funnel you have Event Label "exactly matches" "covid19-path-started". However, I'm not seeing that event label when I go through the user flow in a test account.
 Do you consider starting the covid19 path as when a user selects the "COVID-19 vaccine" radio button at the top under "Schedule a new appointment" and then selects "Start scheduling" as entering the funnel? I would think that would be a good place to start the funnel since it takes the user to a new screen. If you'd like to start the funnel at that point then set the first step in the funnel in GA to Event Label "contains" "vaos-schedule-covid19-button-clicked".
 
The second step in the funnel is currently set to the link www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/received-dose, however when I go through the flow the second page that I come to is www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking. I'd recommend deleting the "/received-dose" part of the URL in step 2 and set it to "exactly matches" then enter the URL exactly as it is with no regex: "www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking".
 
Step 3 should then be "matches regex", like you have it, and should look like: "^www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/received-dose.*" (but without the quotation marks).
 
From the /receive-dose/ page users can go to two different pages.
1. If they select "Yes" they go to the /contact-facilities/ page
2. If they select "No/I'm not sure" they go to the /facility/ page
 
Which page would you like to track?
If you'd like to track both then I recommend setting it to “Page” “matches regex” “"^www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/(contact-facilities|facility).*" (but without quotation marks).

The final step in your funnel is the /select-date page, however I was unable to find that page when testing. It may be better to set it to “Event Label” “exactly matches” “vaos-covid19-submission”.

##Pilot Dashboard
Total Vaccine Submission Breakdown Widget: Because this is set to “Event Label” “Regular Expression” “^covid19-submission” it will show results for only the “vaos-covid19-submission” event. Would you like it to show all attempts to submission? Or only successful attempts? If the latter then I’d recommend changing it to “Event Label” “exactly matches” “vaos-covid19-submission-successful”.
 
Contact Facility Reason - Users Widget: Because there are two options, the "Show up to" drop down should be set to "2 slices" rather than "3 slices". It looks like what you're looking for here is to visualize how many users on the /receive-dose/ page select "Yes" and how many select "No/I'm not sure". Is that correct? If so, then change the first event label to "vaos-covid19-screener-yes" rather than "vaos-schedule-vaccine-contact-facility-dose-received" and the second event label to "vaos-covid19-screener-no" rather than "vaos-schedule-vaccine-contact-facility-none-online". Keep them both set as "Event Label" "containing".
 
Contact Facility - Users Widget: I would recommend changing the regular expression URL to be "^www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/contact-facilities.*" (but without the quotation marks). I also want to note that when I tested the flow I was only able to reach the /contact-facilities page by selecting "Yes" on the /receive-does page. If you are looking to show users who only selected "Yes" then this is fine. If however you'd like to show users who selected both "Yes" and "No/I'm not sure" then change the regular expression to be "^www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/(contact-facilities|facility).*" (but without quotation marks).
 
Choose Clinic - Pageviews Widget: I was not able to locate the page referenced here when going through the funnel (www.va.gov/health-care/schedule-view-va-appointments/appointments/new-covid-19-vaccine-booking/clinic)
 
To KMI Widget: I'm not sure which link/button clicks you are trying to track here. I'm not able to find the event label "vaos-COVID-19-vaccines-at-VA-link-clicked". 
 
User Location Widget: I would recommend setting this to "Event Label" "exactly matching" "vaos-schedule-covid19-button-clicked". (same as recommendation from step 1 in the funnel report)
 
Device Type Breakdown Widget:  I would recommend setting this to "Event Label" "exactly matching" "vaos-schedule-covid19-button-clicked". (same as recommendation from the "User Location" widget and same as recommendation from step 1 in the funnel report)


I hope these recommendations are clear and that they are helpful. Please let me know your feedback. 

Best, 
Lauren

**Comment by laurenernest** [comment]
Thanks for the notes! 

Short funnel: we discovered in another ticket that the path-started event wasn't firing so we're adding a fix for that. I'll use button-clicked for this funnel. Odd that the calendar page was the last step in your view. I've updated so that it's only 2 steps to show overall conversion.

Total Vaccine Submission Breakdown Widget: I was trying to mimic this table we have for our overall app dashboard https://analytics.google.com/analytics/web/template?uid=tumrAEYPRZqNfW2LVj5hbA
![Screen Shot 2021-03-26 at 1 53 46 PM](https://user-images.githubusercontent.com/72046525/112701756-b62e1a00-8e4e-11eb-8549-8da59ad34a17.jpg)

Contact Facility Reason - Users Widget: there are 2 different versions of the Contact a Facility page (which is different from the Facility Selection page) depending on the scenario. For this pilot, we should only run into one version to start so I updated it with the screener-yes event since that selection will load the page.

Contact Facility - Users Widget: I removed this one.

Choose Clinic - Pageviews Widget: Not all users will see this page

To KMI Widget: Removed this widget and added the Exit Links widget instead. I'll be looking for clicks to 2 other areas of VA.gov

User Location Widget: Updated

Device Type Breakdown Widget: Updated

https://analytics.google.com/analytics/web/#/dashboard/L1iaMzO6SVivDZmpNgRIrg/a50123418w177519031p176188361/

**Comment by laurensimpson14** [comment]
@laurenernest 
When I try to load the link to the dashboard that you sent I see a "Security problem" error popup. If you'd like to try to resend a shared link then I can take a look at it, however, everything in your note sounds good. I think what you have for the Total Vaccine Submission Breakdown Widget is perfect for what you're trying to achieve. 

Please let me know if you'd like me to take one final look at the updated dashboard, if you need anything else, or if this ticket is OK to close out.

**Comment by laurenernest** [comment]
Oops! Here's the template link https://analytics.google.com/analytics/web/template?uid=VE2aH7bFREav_BKN-UI1Gw

Traffic from VEText is a new section to track when we get traffic specifically from that outreach.

**Comment by laurensimpson14** [comment]
@laurenernest 
Traffic from VEText widget: I'd recommend setting it to "Containing" rather than "Exactly matching" since it is possible that other UTMs could get added on to the end of the URL.

Total Vaccine Submission Breakdown widget: I'd recommend adding a .* to the end of the regular expression to ensure it picks up both the successful and failed labels, so it would look like ^vaos-covid19-submission.*

Exit Link Clicks widget: It will show all pages where the previous page was the /new-covid-19-vaccine-booking/ page. So, if a user clicks the VA logo and returns to the home page, it would list the home page, if they click off to the "Contact us" page it would show that, etc. The only page it is set not to show is if the user clicks to go back to the /scheduling-view-va-appointments/ page. Is that what you're looking for?

**Comment by laurenernest** [comment]
Traffic from VEText widget: Updated

Total Vaccine Submission Breakdown widget: Updated

Exit Link Clicks widget: For this one, I'm trying to capture clicks from the covid flow (has /new-covid-19-vaccine-booking in the URL) to outside VAOS and not include anything in VAOS. In thinking about this table maxing out at 10 possible URLs and I am mainly looking at Facility Locator and the COVID-19 hub, I added those specific URLs to include instead of anything on VA.gov

https://analytics.google.com/analytics/web/template?uid=MCiJvppRSWmeqcsgS2JRGw

**Comment by laurensimpson14** [comment]
Because you've added in "Only show" Pages to the exit link clicks widget, you can delete the second line with "Don’t show". Once there are "Only show" entries then all other URLs besides the "Only show" URLs are automictically filtered out.

Rather than add all three pages to individual lines, which can sometimes cause issues, I'd recommend adding them all to one line with Regular Expression (like you have it) and using a pipe to separate each one (which means "or" in regular expression). You can delete the last two "Only show" "Page" lines and change the regular expression in the remaining "Only show" "Page" to be: ^https://www.va.gov/find-locations/.*|^https://www.va.gov/health-care/covid-19-vaccine/.*|^https://www.va.gov/health-care/covid-19-vaccine/stay-informed.*

I believe after those two changes are made it will reflect what you're looking for.

**Comment by laurenernest** [comment]
Great! Thanks so much! Good to close this ticket.

**Comment by laurensimpson14** [comment]
I hope you have a wonderful day!
