### ISSUE TITLE
Finalize copy for Sign as a Representative work

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#21964]
In #21230 we iterated on the initial Sign as a Representative work. Now that we've met with Platform and the Caregiver program, we need to finalize the language we're going to use and update the prototype needed to start development work.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @sshein. I think the 3 options look good for the new question. Just a few questions/notes for consideration:

- We usually have "Yes" or "No" as its own sentence in running copy. Not sure if that works for radio buttons, but would love your thoughts. So: <br> Yes. I'd like to upload documents now.

- I would slightly reword the middle option to: <br> No. I'm the Veteran's legal representative, but I'll provide documents later.

- I do wonder if the middle and last "No" options could be confusing. But I think as you mentioned, that's something that's better to test first than guess at how to best handle.

And then one other thing. It looks like the copy in the 2nd bullet under "Here's what you should know:" changed slightly. That's fine, of course, but can we just edit to make it active rather than passive voice and a couple other minor tweaks? I don't think you need to say "in the process" as I think that's implied. So instead of:

If you don't upload them now, you will be asked to provide them later in the process.

Change to:

If you don't upload your documents now, we'll ask you to provide them later.

**Comment by sshein** [comment]
thank you! that all makes sense.

**Comment by sshein** [comment]
latest designs in this PDF, will put it all into UXPin for easier copy/pasting soon!
[Uploading Representative-designs032521.pdf…]()

**Comment by sshein** [comment]
latest designs here: [https://app.zenhub.com/files/133843125/ec0f69b4-130f-4069-973f-ff2f548bb4a6/download](https://app.zenhub.com/files/133843125/ec0f69b4-130f-4069-973f-ff2f548bb4a6/download)

**Comment by sshein** [comment]
UXPin https://preview.uxpin.com/3bf6496017f55041a94c2cfc8009c35dad5a79f2#/pages/137666490/simulate/sitemap?mode=i

**Comment by sshein** [comment]
Updated copy based on the "single document" requirement:

**Comment by sshein** [comment]
latest copy based on the fact that users will only upload a single document. Will update the UXPin once we get feedback from the program team
![Screen Shot 2021-03-29 at 3.23.44 PM.png](https://images.zenhubusercontent.com/5d4c59b26a82cc000106fdf0/7a2e5b7f-f162-4ef1-9341-b46e58cc4444)

**Comment by sshein** [comment]
Final copy for the usability test based on the program team's feedback
[https://app.zenhub.com/files/133843125/eb90122f-0477-4f7c-826a-087e1cb87f26/download](https://app.zenhub.com/files/133843125/eb90122f-0477-4f7c-826a-087e1cb87f26/download)

**Comment by ala-yna** [comment]
Thank you Shawna! Closing this out - any future changes can be a part of: https://app.zenhub.com/workspaces/vsa---caregiver-5fff0cfd1462b6000e320fc7/issues/department-of-veterans-affairs/va.gov-team/22702
