### ISSUE TITLE
VA.gov Form Consistency: Resources & Support

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#21975]
## User Story

As a user I would like to see consistent design across all VA.gov search tools, including Resources & Support, so that I don't have to re-learn a new pattern for each tool.

## Expected Behavior

Elements on Resources & Support search tool follow the same design patterns as much as possible - see spreadsheet linked in issue https://github.com/department-of-veterans-affairs/va.gov-team/issues/21438

## Acceptance Criteria

- [x] Mockups for Resources & Support search completed
- [ ] Accessibility has reviewed and provided feedback
- [ ] Design has reviewed and provided feedback

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 this is the new issue for the search for Resources & Support.  Please assign an estimate when you have a minute.  Thx!

**Comment by brianalloyd** [comment]
@callen2563 @MarciMcGuireGCIO just including some details for PubWeb team based on the work for R&S.  Look forward to seeing the design mockups and what ideas the team has in terms of search consistencies across platforms.

**Comment by sshein** [comment]
cool. can I be included in any meetings where new consistent designs are being shown across our products?

**Comment by callen2563** [comment]
I have updated the headers on Resources & Support to match the styling for the other pages in the UI Consistency epic:
[Resources & Support](https://vsateams.invisionapp.com/share/SD10IE31CENR#/448325388_Resources_-_Support_-_Desktop)

**Comment by callen2563** [comment]
I found an inconsistency after looking over the component tracker with regard to the R&S search bar. Mainly that R&S has a different UI style for search from Find a Form and other search tools and the search bar and radio buttons get hidden under a filter icon on the mobile view of the page. I discussed this inconsistency with Megan, Leyda, Ryan, Shawna and Josh. 

We determined that R&S search should be updated to match Find a Form's search based on Joshes recommendation: "Find a form search looks more accessible and better balanced. Especially on mobile." 

I brought this issue up in standup with the PW team this morning and asked if there is bandwidth to update the search UI.

**Comment by callen2563** [comment]
After meeting with Megan and Leyda yesterday we made the decision to remove the grey container box behind the search bar due to the redesign for Search that features a [new left rail menu for tools](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21376) across all tool pages with the exception of Find a Facility, which contains more than one search form field.

R&S had the correct search bar UI on desktop but the mobile UI needed an update. Mainly the grey box / filter menu that was hiding the search bar and radio buttons was removed and adjusted to the grid width to create consistency with other mobile tool UI.

[R&S mobile update](https://vsateams.invisionapp.com/share/8Y10IE2JN2J4#/448630358_Resources_-_Support_-_Mobile)

**Comment by brianalloyd** [comment]
Thanks @callen2563 I've got this on the tracker to review during team grooming session so we can discuss next step and ticketing needs for action items.  Appreciate the work on this, excited to see the results and user feedback from the refinement.

**Comment by sshein** [comment]
hiya @callen2563 can you all have a design intent with platform or meet with Ryan regarding where you're aligning with all the search consistency patterns before implementing just to make sure they are aware?

**Comment by brianalloyd** [comment]
Closing out in support, based on planning review.
