### ISSUE TITLE
IA Request [vsa-education - Veterans Rapid Retraining Assistance Program (VRRAP)]

### ISSUE THREAD

**Issue by JenLJ** [department-of-veterans-affairs/va.gov-team#22142]
Important Note:  We are on a VERY fast timeline and artifacts may not always be in agreement.  For reference, content document is king (when incompatibilities exist between the content document and prototype).

## Required Inputs:
- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/product-outline.md)
- Link to [prototype](https://bahdigital.invisionapp.com/share/CUIAGI923MB)
- Link to [content doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/application/VRRAP/design/content-doc.md)

## Information Architecture Worksheet (Optional)

Provide the following information, as available, to support the final information architecture of your product.

**Suggested URL(s)** - Provide suggested URLs and any background or rationale
https://staging.va.gov/education/other-va-education-benefits/vrrap

**Suggested Breadcrumbs**
Home > Education and training > Other VA education benefits > Veterans Rapid Retraining Assistance Program

**Redirects/canonical tags** - Will existing pages/tools need to be redirected or canonicalized? No

## Definition of Done
- [x] VFS: Creates issue and provides all required information above
- [x] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
@JenLJ @amyknox Draft IA recommendations are here: 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-vrrap.md

cc @bethpottsVADEPO @peggygannon 

A few open items yet:
- Breadcrumbs and URLs will be finalized once content and H1s are finalized.
- Is there an official VA form number for this new form?
- Entry points are still TBD, but will include links in both education and careers. 

One thought I wanted to bring up, is whether this form truly belongs in education or careers.  I realize this program and direction is coming through the education group, but I'm looking at this from a Veteran perspective.  If the program is aimed at Veterans who lost their jobs due to the pandemic, they may be looking for career/job resources, not starting over with education.  That said, I understand that it's technically a program that provides education.  That is why I am recommending entry points in both areas, but would like to look at this after it launches to see how users are primarily looking for it and whether we can fine-tune the URL and placement to improve findability and SEO.

**Comment by amyknox** [comment]
@mnorthuis - VA form number has been assigned. :drum: : 1990s


Agree there's a question about whether this is an education or careers form.  It's training so that says "education" but applicants will have lost their job so "careers" makes sense, too.  

Either way, it's not likely users are going to find it clicking through the site.  We designed and built the STEM application and I still have no idea how to navigate to it and get lost when I try.  Social media, deep links, and email promotions are going to be vital for this application.

**Comment by mnorthuis** [comment]
Updated the IA information with the official form number in the URL and breadcrumb. 

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-vrrap.md

**Page** | **URL** | **Breadcrumb** | **Notes**
--- | --- | --- | ---
Static landing page | www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance  |  Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program   | The last segment of the breadcrumb should match the H1 of the page
VRRAP form | www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s | Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program > Apply for program VA Form 22-1990s |  

Thank you for catching the missing "Assistance" from the breadcrumb @amyknox - I hadn't refreshed the page yet and went to edit it to add it and ta-da, it was already there!  :-)

@bethpottsVADEPO I have provided some suggestions/recommendations on entry points, and where entry points should not be added per standards.  Crosslinking opportunities within Careers is challenging, as there isn't any highly visible places to put it.  Additional placement may be found within content pages, but it should not be added to the main hub or left nav given it does not live in that hub.

**Comment by JenLJ** [comment]
@mnorthuis For the VRRAP form, should the final breadcrumb be "Apply for program VA Form 22-1990s" or "Apply for VRRAP"?

**Comment by mnorthuis** [comment]
As far as standards go, here are a few things...
- Generally we should not utilize acronyms that are our users are not familiar with. In this case, it is also a bit confusing with the previous program labeled "VRAP" vs the new program being "VRRAP". 
- We must be clear and concise as possible in indicating what the page is about and its purpose - here we need to distinguish the two programs since eligibility and details are different. There is a lot of information out in the wild about the old program, and it will be easily confused.  
- The breadcrumb already includes a link to the static content page, which has the full program name in it, so its not necessary to repeat it again.

All of that said, we also generally match the segments of the breadcrumb with the H1s of the corresponding page, so if you are using "VRRAP" in the H1, then that can be used in the breadcrumb, but at the risk of the above items. 

**Having the VA form number in the breadcrumb, title and URL is a standard practice and must be included.**

**Comment by mnorthuis** [comment]
Updated the breadcrumbs in the IA documentation to reflect the use of "VRRAP".  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bah-vrrap.md

Marking the IA work for this as complete.  If there are any further questions, let me know.  Otherwise you can close this issue at your discretion.

**Comment by mnorthuis** [comment]
@JenLJ After reviewing the static content page and discussing with sitewide content, I made a few minor changes to my IA documentation for the breadcrumbs.  Since I'm not aware of final content or changes, I am removing reference to exact copy and indicating that the breadcrumb segment should match the H1 of the corresponding page.   

It looks like the static page H1 is currently "Veteran Rapid Retraining Assistance Program (VRRAP) " which would then mean the breadcrumb would be  `Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program (VRRAP)`

If the H1 changes, the breadcrumb segment should also change.  Same for the form.  

**Page** | **URL** | **Breadcrumb** | **Notes**
--- | --- | --- | ---
Static landing page | www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance  |  Home > Education and training > Other VA education benefits > [static page H1]   | The last segment of the breadcrumb should match the H1 of the page
VRRAP form | www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s | Home > Education and training > Other VA education benefits > [static page H1] > [Form introduction page H1]  |

**Comment by amyknox** [comment]
@bethpottsVADEPO 
LMK if the final answer for the static page H1 is "Veteran Rapid Retraining Assistance Program (VRRAP)".  

We need this info so we can make the final updates to the VRRAP form.

Thanks!

**Comment by amyknox** [comment]
@mnorthuis  - triple checking on this is what your direction is for the form intro breadcrumb: 

Home > Education and training > Other VA education benefits > Veteran Rapid Retraining Assistance Program (VRRAP) > Apply for the Veteran Rapid Retraining Assistance Program (VRRAP) ??

Curious about this b/c that update is a significant departure varies from the previous form intro page terminal crumb: Apply for VRRAP VA Form 22 1990s

**Comment by mnorthuis** [comment]
Hi @amyknox, the goal is to link the breadcrumb segments to the H1 on their corresponding page.  Although this may produce a not-so-ideal breadcrumb in some cases (such as this), it will help us better build out the breadcrumb components to be automatically determined rather than needing to be coded every time - thereby improving consistency and experience.  Trying to balance the breadcrumb with the evolution of other changes in components and content is challenging right now, but something we will be looking at as an evolution of the breadcrumb in the future.  Open to any feedback you have!

**Comment by amyknox** [comment]
@mnorthuis - thanks for the input.  I can appreciate that managing & normalizing across so much content & so many teams can be challenging!   

One thing I wanted to verify with you because it seemed especially important earlier:  You'd said, **Having the VA form number in the breadcrumb, title and URL is a standard practice and must be included.**  However, the VA form number is no longer in the breadcrumb.  Is the removal of the form number an update to the breadcrumb component or do we need to include that in the breadcrumb, too?

**Comment by mnorthuis** [comment]
I am aware of that and should have spoken to that specifically, sorry!

In this case, it will not be in the breadcrumb because the initial state of the /introduction page does not have it in the H1.  Once the user answers the wizard questions, the /introduction page refreshes to show the form number in the H1 (this is an accessibility work around).    Ideally, the breadcrumb would update to reflect that as well, but I didn't want to impose technical changes on you at point in the game - it would be a "consider" item.  If that is something that you think you could do, that would be great, if not, then this is the interim solution we have for form wizard scenarios.  For forms that don't have a wizard, its not an issue, but the wizard is introducing  a _few_ struggles.  :-)

**Comment by mnorthuis** [comment]
The original intent of the breadcrumb change mentioned above was to ensure that the breadcrumb and H1s are consistent with one another.  In this case, we have an issue where there are 2 pages with similar titles, making the  breadcrumb look very redundant (and long).  For the sake of this work effort, I will pause the change in approach so we can have a cleaner breadcrumb here, and until we can work out the approach from an IA/content perspective. 


**Page** | **URL** | **Breadcrumb** | **Notes**
--- | --- | --- | ---
Static landing page | www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance  |  Home > Education and training > Other VA education benefits > [static page H1]   | The last segment of the breadcrumb should match the H1 of the page
VRRAP form | www.va.gov/education/other-va-education-benefits/veteran-rapid-retraining-assistance/apply-for-vrrap-form-22-1990s | Home > Education and training > Other VA education benefits > [static page H1] > Apply for VRRAP with VA Form 22-1990s  |  Final segment of breadcrumb is/may be different from the H1 of the form in order to reduce redundancy and to ensure it includes the form number.

**Comment by bethpottsVADEPO** [comment]
@amyknox Confirming the H1: Veteran Rapid Retraining Assistance Program (VRRAP)
