### ISSUE TITLE
EDU Forms / VRRAP: Prototype - EDU Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#22218]
VRRAP protototype has been reviewed by EDU	

* Prototype is reviewed w EDU 
* Updates to prototype / content doc are incorporated, if needed

**Comment by amyknox** [comment]
@watersemma - a couple updates to the latest version on the intro screen:

For authenticated users, informational alert at the top of the screen should be: 
Note: Since you’re signed in to your account, we can prefill part of your application based on your account details. You can also save your application in progress and come back later to finish filling it out.

For both authenticated / unauthenticated users, last eligibility bullet should be: 
Not receiving unemployment benefits (including CARES Act benefits).

**Comment by amyknox** [comment]
@watersemma


**Form Intro**
Only authenticated form completions will be allowed. 
* Update info alert at top of page to VET TEC style & content. 
* Remove "Complete application without signing in" text link at top of page
* Remove "Complete application without signing in" text link at bottom of page

Add OMB info (looks like placeholder for this is already on the authenticated intro page - needs to be added to the unauthenticated page, too, and update there)
* Respondent burden: 10 minutes
* OMB Control #: TO COME
* Expiration date: TO COME

[Privacy Act Statement]() { modal with Privacy Act content } 

You can archive the screens with the unauthenticated application input form 

**Also, on the confirmation screen,** looks like the "Need help" footer needs to be updated. Left is what you have in the prototype, right is what's in VET TEC and STEM. If you have newer info that contradicts that, LMK!

![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/4f541921-721b-4dbb-ad4e-b3da3cf479f0)
