### ISSUE TITLE
10-10CG: Improve user experience of indicating whether users are applying for primary and secondary caregivers

### ISSUE THREAD

**Issue by sshein** [department-of-veterans-affairs/va.gov-team#22372]
# Background
In the usability studies we've done on the 10-10CG, Caregivers have been confused about the primary and secondary caregiver language.

# User Story
As a Caregiver/Veteran
I want to confidently choose primary or secondary caregivers
So that Veterans and Caregivers can receive the best support.

# Acceptance Criteria
Design created
Prototype updated
Testing tickets created
Front end/backend implementation tickets created

**Comment by sshein** [comment]
design thoughts include having a single page where we explain primary and secondary caregivers and ask users there what types they are applying for - e.g. initial sketch 
![Screen Shot 2021-03-30 at 9 53 22 AM](https://user-images.githubusercontent.com/3856611/113026321-ca6b6300-913d-11eb-83cb-0d2a5534ca70.png)

**Comment by sshein** [comment]
in the study being run right now, participants validated this need. One participant explicitly stated that she wanted the questions to be on a single page: _"Maybe if there is a way to have primary and secondary together to explain the differences so I know right off the bat what I'm applying for."_ Another had issues with the placement of the "Learn more" components and thought those components were the actual questions.

**Comment by Dene-human** [comment]
Note from the CG program team:

- They have been receiving a higher than usual amount of Secondary CG applications. These are from older Veterans. 
- They feel there is a lack of understanding what a secondary CG is - that is comes with heavy commitments and requirements similar to the primary. Such as check-ins, etc.
- Lack of understanding of the difference of Primary and Secondary- responsibilities, benefits, etc.
- Secondary is not just anyone who helps out (such as underage child, etc.)
- It is unclear whether when applying for secondary, the applicant needs to reenter primary CG information
- Applicants are unclear if they HAVE to enter both Primary and Secondary (eg. They see Secondary so they enter one- sometimes same info as Primary)

**Comment by SKasimow** [comment]
@Dene-human should we change this to backlog or icebox?

**Comment by Dene-human** [comment]
A few different designs ([Sketch link](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/v/15WML8/p/79BDE8AC-21C9-4FEF-B0FB-DA6E0C3990DD)) have been prepared with the intention to be shown at design intent. Because this project is paused, a new ticket is opened (#38119 ) to pick this up when ready.

Notes:
- V6 is a new, progressive flow depending on if applicant is new to the program or returning to change/add a caregiver (this is my current recommendation) 
- V5 includes the idea of a chart, but if a chart is created, it should likely live on a content page (must consult accessibility) 
- Other versions are intended to give options of elements and content
