### ISSUE TITLE
Review Pittsburgh Medical Records FAQs and Update content with Plain Language as needed

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#2243]
### **Objective:**
This ticket is to review the Pittsburgh Medical Records FAQs (attached), and identify content where plain language can be applied.  

### **Task:**
- [x] Review FAQs and mark-up content with plain language as needed (without changing the meaning of the information). This content should follow the new VA.gov content voice and tone, and must adhere to the style guide. Please work closely with @AnneHurley for supervision and feedback.  

**Please Note:** This is needed by **October 8** (Tuesday)- @jenniferlee-dsva will need time to do final review/revise if needed. 

Attached Word doc with specifics for @lunascoop 
[Medical Records FAQs.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3687821/Medical.Records.FAQs.docx)

**Comment by lunascoop** [comment]
@AnneHurley Here are my edits.
[Medical.Records.FAQs.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3699358/Medical.Records.FAQs.docx)

**Comment by AnneHurley** [comment]
[Medical.Records.FAQs-AH edits.docx]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/3699659/Medical.Records.FAQs-AH.edits.docx)

@lunascoop  Good start on this. Some questions and comments for you on this doc. Let me know if you have questions or concerns.

**Comment by lunascoop** [comment]
@Karak888 @AnneHurley @jenniferlee-dsva 

I have updated the document after Anne's feedback. I included responses to Anne's comments and comments requesting more information. There are some strikethrough text that I've kept in the document because they are attached to Anne's comment, but I have rewritten the response.

[Medical.Records.FAQs-Response to AH.edits.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3703948/Medical.Records.FAQs-Response.to.AH.edits.docx)

**Comment by AnneHurley** [comment]
[Medical.Records.FAQs-Response.to.AH.edits-3.docx]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/3704321/Medical.Records.FAQs-Response.to.AH.edits-3.docx)
@selina I had a few more questions, and then I think we may need @jenniferleedsva to weigh in on what/how much info to ask the SMEs for. LMK if you have any questions.

**Comment by lunascoop** [comment]
@AnneHurley @jenniferlee-dsva 
I have re-reviewed and accepted Anne's changes and added/responded to some questions.
[Medical.Records.FAQs-Response.to.AH.edits-4.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3704479/Medical.Records.FAQs-Response.to.AH.edits-4.docx)

**Comment by AnneHurley** [comment]
@lunascoop  Thanks! @jenniferlee-dsva  & @ karak888  I know this is time sensitive - did one of you want to review this to get it in the pipeline sooner?

**Comment by Karak888** [comment]
Thanks @AnneHurley and @lunascoop! Yes @jenniferlee-dsva will definintely be wanting to review this.

**Comment by jenniferlee-dsva** [comment]
It's unclear to me if this is 'baked.' Will assume that it is, and will take it from here! (I was hoping this would be an 'easy' hands-on, get-into-Drupal practice with one of you entering this in the CMS, but since access is still an issue, I'll take it from here.) Thank you @lunascoop. Thank you @AnneHurley for reviewing for our style guide and voice and tone! 

I'll reach out if I have any questions.
