### ISSUE TITLE
[Off-site Search] Structured Markup Entity Field Issue

### ISSUE THREAD

**Issue by johnhashva** [department-of-veterans-affairs/va.gov-team#22442]
## Why you're here 

SEO Audit/crawl reports from SEMRush -- and reported by Jen Lee --  have revealed issues that appear to be rooted in our site template structured markup for FAQs.  Details:

- attached report has identified 17 of our modernized pages as missing the mainEntity field value in structured data (schema markup).

[va.gov_structured_data_that_contains_markup_errors_20210218.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/6005669/va.gov_structured_data_that_contains_markup_errors_20210218.xlsx)

Google Search Console confirms the same issue:

<img width="1272" alt="Screen Shot 2021-03-31 at 2 48 42 PM" src="https://user-images.githubusercontent.com/63107147/113195752-a3418e00-9230-11eb-891c-d1e865549784.png">

### Additional Background and Context 

- Here, per Google is how to fix structured markup -- including the mainEntity field value.    Google also provides a URL inspection tool to determine if your fix works.

https://developers.google.com/search/docs/data-types/faqpage

### Frontend engineering support 

- Need Search engineer to analyze and validate the reported issue and determine steps and LOE to solve.
      
### Desired/target implementation date

- TBD

---

### About your team

- Team name: Search
- DEPO product owner: John Hashimoto
- Product manager: Denise Coveryduc
- Designer: N/A
- FE engineer: Sam Suddath
- Product/team Slack channel: #va-search

--- 
#### Acceptance Criteria
- [ ] Convert this request into a Zenhub epic
- [ ] Follow-up with requestor to address any lingering questions/concerns
- [ ] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed

**Comment by denisecoveyduc** [comment]
Higher priority items bumped this from S45. We will examine in future sprints.

**Comment by denisecoveyduc** [comment]
@srsuddath plans to make two new issues out of this exploration. One for PW with easy wins and the other for the Icebox which require multiple team coordination to complete.

**Comment by srsuddath** [comment]
@kelsonic can you add a Main Entity field value to the following pages that Public Websites maintains?
https://www.staging.va.gov/find-forms/
https://www.staging.va.gov/health-care/schedule-view-va-appointments/
https://www.staging.va.gov/health-care/refill-track-prescriptions/
https://www.staging.va.gov/health-care/view-test-and-lab-results/
https://www.staging.va.gov/health-care/secure-messaging/
https://www.staging.va.gov/health-care/get-medical-records/

**Comment by kelsonic** [comment]
PR merged, should go out with the daily deploy today (assuming that's how it works with the new content build repo) 🙂

**Comment by denisecoveyduc** [comment]
@srsuddath @kelsonic Are we able to close this issue now?

**Comment by kelsonic** [comment]
You may want to rerun the test to look for the pages that remain with the `mainEntity` issue, I hypothesize more still remain unfortunately 🙂

**Comment by denisecoveyduc** [comment]
@johnhashva are you able to rerun or do we need to wait for the end of the month SEM Rush report to come in?

**Comment by johnhashva** [comment]
@denisecoveyduc + @srsuddath   This report actually comes out of Google Search Console -- and this issue is ongoing based on latest crawl this week.

<img width="1126" alt="Screen Shot 2021-05-19 at 2 35 18 PM" src="https://user-images.githubusercontent.com/63107147/118866080-a3b0e980-b8af-11eb-9fcc-658089f39396.png">

Assuming you have access to GSC -- here is a link to the report page: https://search.google.com/u/1/search-console/faq/drilldown?resource_id=https%3A%2F%2Fwww.va.gov%2F&item_key=Cg4ICRoKbWFpbkVudGl0eRADGA0&hl=en&sharing_key=KgBXVSbmA64G5b-RzTkl0w

**Comment by johnhashva** [comment]
@srsuddath you may find some helpful insight here: https://developers.google.com/search/docs/data-types/faqpage

**Comment by kelsonic** [comment]
We added `itemprop="mainEntity"` to the page template, but I would have expected that number to decrease from 100 to like 5-10, which means the fix Google told us to do isn't fixing it 🤔

**Comment by srsuddath** [comment]
it did decrease from 100 to 76, which is a major improvement
especially because I don't think your change would affect any of the legacy content, which I believe was the bulk of the issues.

Looking at the original ticket, only 17 modern pages were flagged as having an issue, and now we are down to 76, so it seems you likely fixed all the modern pages + some?

**Comment by kelsonic** [comment]
Oh! That makes sense! Cool I will do the same for the react pages e.g. find forms / get-medical-records / etc. CC @brianalloyd

**Comment by srsuddath** [comment]
If you can do so, that will likely fix a large number of these remaining issues. However I don't think we will ever see this drop to 0.

**Comment by kelsonic** [comment]
Sorry diving into this a bit more... Some of these pages I don't think should have the QA structured format because it's not a valid use case:

![image](https://user-images.githubusercontent.com/12773166/118869190-5417f100-b8a2-11eb-809c-ba4893b90ef6.png)

For example, Find Forms doesn't have any QAs on it when you land on it, and it just feels wrong to wrap each header on that page with a question structured markup and the text as the answer structured markup: https://www.va.gov/find-forms/

**Comment by kelsonic** [comment]
IMO those errors are fine to have -- it's because we now wrap EVERY page with structured markup, whereas not every page needs it (debatably the majority don't). In the case where Google crawls a page that has one of those `mainEntity` errors, it will just default to its typical crawling process I'd imagine.

**Comment by johnhashva** [comment]
@kelsonic and @srsuddath do both of you have access to GSC so you can look at the report?  Based on a quick click-through, there are still quite a few modernized pages in the list here;  https://search.google.com/u/1/search-console/faq/drilldown?resource_id=https%3A%2F%2Fwww.va.gov%2F&item_key=Cg4ICRoKbWFpbkVudGl0eRADGA0&hl=en&sharing_key=KgBXVSbmA64G5b-RzTkl0w

**Comment by kelsonic** [comment]
We both have access to GSC 🙂

**Comment by denisecoveyduc** [comment]
Hey @kelsonic just following along on the thread. Do I understand this correctly? It sounds like the fix you and @srsuddath did dropped us from 100 to 76 and you are going to do the same for the react pages? I assume that may drops the total number down further. 

You pointed out that they don't have a QA structure format .. are they being flagged as though they do and that is why the `mainEntity` errors is appearing? Is there anyway to indicate that the page follows a different format to avoid the error? Might be a tedious process but if we can get the number down low enough might be worth it.  

If that isn't an option or we can't find a solution might be worth closing as you suggest since it defaults to the typical crawling process.  @johnhashva thoughts?

**Comment by kelsonic** [comment]
> You pointed out that they don't have a QA structure format .. are they being flagged as though they do and that is why the mainEntity errors is appearing?

Every page has the boilerplate now for structured markup. However, when a page doesn't utilize it, it's showing up as an error. I'm saying this error doesn't matter, the page still gets indexed just fine by Google among other search engines.

> Is there anyway to indicate that the page follows a different format to avoid the error? Might be a tedious process but if we can get the number down low enough might be worth it.

I think we need to ask ourselves why we should solve this error. I know the red seems scary in GSC, but if there's no impact from these errors to neither devs nor end users, then why bother spending the time to fix it?

> If that isn't an option or we can't find a solution might be worth closing as you suggest since it defaults to the typical crawling process

💯

**Comment by denisecoveyduc** [comment]
@johnhashva @srsuddath @kelsonic and I met and agree to close this one. The Search & Discovery team will be defining strategy to monitor error reports from SEMRush and Google Search Console going forward to continue monitoring these going forward.
