### ISSUE TITLE
Content Feedback - Staging review  - Debt resolution FSR form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#22475]
## User story
Content staging review for online FSR form. 
Staging link: 

## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback key
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
FSR form staging review

**Questions**

Wizard:
1.  Double checking that the Rogers STEM program is correct here? Is this related to the Rogers STEM Scholarship? 

Form:
2. Re-enter email address note (To receive a confirmation email when you submit your request, you must re-enter your email address.)
Is this true for all our forms? If so, I suggest updating current online forms with this note


3. Is the supporting personal statement optional? Or can users submit it later? If so, consider adding content to that affect. Or if not, then putting a “Required” on this screen. 

4. Are there error states/messages that need to be reviewed for this tool? 

5. Validation errors don’t follow error message and accessibility best practices. Some examples: 
*This field should be at least 6 character(s)*
*Please provide a response*
*Must certify by checking box*

We should identify the field we’re talking about and/or identify the input that's needed. 

6. Are there any changes to static pages entry points to get to the FSR wizard that need to also be reviewed?  

7. I was unable to submit this request on staging and see the confirmation page. As such, confirmation page has not had a VSP content review. 


-----

**Must feedback**

Wizard: 
1. Please fix typo in this sentence: **I this this debt is due to an error.** TO: **I think this debt is due to an error.**

2. Please delete error/ double Note in this sentence: 

Note: Note: You have 180 days from the date you received your first debt letter to submit your dispute statement. After this time, we can’t consider the request.

3. Fix misspelling of amount in this sentence: **I think the amout of this debt is wrong.**

4. Please double check the hours for this alert, as they don’t match the content provide by sitewide content team: 
For help with debt related to separation pay/attorney fees, call us at 800-827-1000. We're here Monday through Friday, 8:00 a.m. to 8:00 p.m. ET. If you have hearing loss, call TTY: 711.

5. Active duty service member should be Active-duty service member

6. For this alert: If you disagree with the VA decision that resulted in this debt, you can submit a supplemental claim or request a higher level review or board appeal.
 Supplemental Claim and Higher Level Review, should be capitalized to align with VA.gov styleguide

7. Per content outline, this CTA button “Submit a Financial Status Report” should be "Request help with VA Form 5655"

8. Please fix name of Board of Veterans’ Appeals in this sentence: “I want to appeal the decision with the board of Veterans Appeals.” 
Correct name is Board of Veterans' Appeals

Introduction page: 

9. Per content outline, CTA button on intro page should be: Start your request now

Form: 

10. https://staging.va.gov/manage-va-debt/request-debt-help-5655/available-debts: 
the intro on this page has duplicative sentences. I recommend removing this second sentence (bolded here), as it repeats the one above it. 
**You will be able to choose a repayment option for each debt you select.**

11. Per content outline, change Registered partnership TO: In a registered partnership

12. Social security should be Social Security throughout the form. (The Review and submit page is inconsistent with rest of form)

13.  Go Back to VA.gov button should follow sentence-case guidelines. It should be:  Go back to VA.gov 

-----
	
**Should**

Wizard: 
1. Update: Make a payment on a debt TO: Make a payment (to avoid duplicating “debt” again)

2 For this alert below, don’t use link in this sentence, as this link doesn’t take users **directly** to the place where they will request an appeal. 
If you disagree with our decision on your waiver request, you can [request a Board Appeal]. 

3. Per form label masterlist, for online forms we should use Postal code (to account for non-U.S. addresses) 

4. Change What is your marital status TO: What’s your marital status

5. https://staging.va.gov/manage-va-debt/request-debt-help-5655/resolution-options/0
I suggest moving header: "Your financial overview" into the blue box to more closely tie the header to the content in box. 

6. https://staging.va.gov/manage-va-debt/request-debt-help-5655/resolution-options/0
Change “Compensation & Pension” TO: Disability compensation and pension debt

Please update cards and headers throughout form with this change

7. Submit application CTA. 
I recommend updating this to: "Submit your request", as we refer to this as a “request” throughout the form

----

**Consider**

Consider moving the below content up on the page, so users understand that they can start type in expense into the text box: 

What counts as an expense?
Many everyday living costs count as expenses. If you’re not sure about a specific expense, we encourage you to start typing the expense into the form. The form will help you fill in options that count as expenses.

**Comment by rileyorr** [comment]
Hi @peggygannon! Thanks for the feedback!

 **Questions**

Wizard

>
> Double checking that the Rogers STEM program is correct here? Is this related to the Rogers STEM Scholarship?

The content within the wizard was reviewed by our stakeholders at the DMC and they requested that option be included because they receive requests for information about Rogers STEM program debts and need to reroute Veterans to a regional office. It looks like it is related to the scholarship program, so maybe we should specify it's the "Rogers STEM scholarship program"?

> Checking to see if using All caps in the email addresses in the VET TEC and STEM alerts is correct? recommend not using all caps for ease of reading.

Yup, the wizard content has been previously reviewed and the email addresses and alerts are correctly capitalized. Thanks for double-checking, I know it's not best practice to include all caps but those are the names of the programs. 

> Should the Appeals alert include the other decision review options?

We worked with our stakeholders to outline the wizard flow and those were the two appeal pathways they mentioned, and specifically wanted us to redirect Veterans to that page on our site. We can add this to our next meeting agenda with them to verify that we're not missing anything in that alert! 

Form

> 2. Re-enter email address note (To receive a confirmation email when you submit your request, you must re-enter your email address.)
> Is this true for all our forms? If so, I suggest updating current online forms with this note

Are you specifically wondering if the content in parentheses true for all forms? The 're-enter email address' pattern is fairly new and was a suggestion from the accessibility team back when we were building MDRT and I don't believe this has become a standard pattern across forms. 
 
> Is the supporting personal statement optional? Or can users submit it later? If so, consider adding content to that affect. Or if not, then putting a “Required” on this screen.

The supporting personal statement is optional, but highly suggested that it's included as part of the request. However, that's a good point! I believe Veterans could submit the personal statement later if they preferred to mail it, but during our usability study no one mentioned wanting to do that. It's a good thing for us to consider, though! 

> Are there error states/messages that need to be reviewed for this tool?

Yup! I drafted up error messages that can be found in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/16361). I believe Susan got the content reviewed prior to us closing that ticket, but it sounds like we aren't following best practices so we should probably get another set of eyes on that work!
 
> Have the changes to the static pages entry points to get to the FSR wizard been implemented and on staging?

I don't believe changes have been implemented yet. @leahkeeler may have more info about that work.

> I was unable to submit this request on staging and see the confirmation page. As such, confirmation page has not had a VSP content review.

Apologies you were unable to submit the request on staging and see the confirmation page! @DanielleThierryUSDSVA has been working closely with us on the form's content and has done a content audit on the form. Here's [a link to the confirmation page on UXPin](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138138134/simulate/sitemap?mode=i) for your reference!

> It looks like the privacy policy checkbox and content is missing from the Review and submit screen. Was there a decision to not include this component for this form?

This was brought up during the staging review meeting and both @rebeccawalsh and I were unfamiliar with that privacy policy checkbox! Is that a requirement for all VA.gov forms? Where can we find that content?

**Comment by peggygannon** [comment]
Hi, @rileyorr Thank you for your follow-up responses! 

The privacy policy checkbox line I referred to in my review is this : {checkbox}  I have read and accept the [privacy policy](*Required)

**Comment by rileyorr** [comment]
@peggygannon I broke out your feedback into multiple tickets outlined in [this epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23209). The privacy policy link you sent redirects to a 404 GH page, so if you could link the privacy policy or let me know where I might be able to find it, I'll be able to incorporate that change. Thank you!

**Comment by peggygannon** [comment]
Hi, @rileyorr , sorry, I didn't link to anything in my above comment.. I was just showing the language that we use for that line. 

The link should go to the Privacy Act statement modal, which should have content customized for each form. 

I believe the sitewide content team is making updates to the content for the Privacy Act statement modal, so they should be able to provide you with an update on where the latest content can be found.

**Comment by DanielleThierryUSDSVA** [comment]
Hi there. Just wanted to surface the backlog issue for this: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/21108

@peggygannon, I think this is what you're referring to, correct? This is something that's on our radar, but we haven't been able to dig in yet.

**Comment by rileyorr** [comment]
@DanielleThierryUSDSVA I'm so happy you linked that ticket because during my conversation with Beth I mentioned that I was convinced I'd previously seen a Privacy Act modal in a form like 10-10EZ that mentioned education. I feel sane again! 

Should our next step be to link to the privacy policy page linked in my previous comment and keep an eye out for when you're able to start digging into that backlog issue?

**Comment by peggygannon** [comment]
Hi, @rileyorr and @DanielleThierryUSDSVA yes, the link Danielle included above shows the Privacy Act Statement modal I mentioned.  

@rileyorr Do you know where designers are pulling this modal from for other forms? Most forms include a link to this modal on their intro pages.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @peggygannon and @rileyorr.

@bethpottsVADEPO and I just did a few minutes of research, and it seems that the only issue here is that you need to use the Privacy Act modal statement component, but fill it with the privacy policy and respondent burden language from the paper form.

For example, the modal people seem to be picking up has the education application language. 

Modal:
![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/0e87a9b0-3378-47ab-8fe5-25317ed3741a) 

Paper form 22-1990ARE

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/05e46716-94b5-49d9-ab52-95a4f41c21cd)

So we think you just need to go to the FSR paper form to pick up the right language. Language pasted below.

https://www.va.gov/find-forms/about-form-5655/

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/ff563ebf-dc24-40e1-ab16-400de185bd22)

And then, of course, double check this with the DMC folks. Thanks!

**Comment by denisecoveyduc** [comment]
In discussions with the team, this has been resolved
