### ISSUE TITLE
Prepare VSO Presentation 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#22502]
Prepare VSO presentation: 

- [ ] 20-25 minutes in length 

- [ ] Intro of "Why" we built this, "How" we built this and demo

**Comment by troyriser** [comment]
@leahkeeler The internal review draft of the VSO presentation is available, filename VSA_VSO_PRESENTATION_DRAFT_20210415.pptx. I should note the presentation is somewhat large since it's heavily animated, with video screen capture files also embedded, and I don't know what the file size limitations of Zen hub might be so it might not allow uploading here. If that is the case, I'll upload to our VSA shared drive or attempt an email. Also note the presentation is constructed solely for audience viewing in presentation mode because it's so video-heavy.


[https://app.zenhub.com/files/133843125/fdad38f3-aca9-4c39-b1d8-244cb6474926/download](https://app.zenhub.com/files/133843125/fdad38f3-aca9-4c39-b1d8-244cb6474926/download)
