### ISSUE TITLE
Content Feedback - Design intent - Preferred facilities

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#22519]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback key
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
hi, @andaleliz some high-level content questions/thoughts for this design intent: 

**Thoughts/questions**

 Consider removing the grey border/table so the facilities are better tied to the H1.  

Consider using Update in secondary button (rather than Edit) to more closely tie with the intro paragraph where it says: You can update this list at anytime.

Consider adding content when in edit list mode letting users know that by **not**  selecting a facility, it will be removed from list.  OR consider having users remove facilities they no longer use rather then select facilities they do use.

**Comment by andaleliz** [comment]
Thanks @peggygannon!  Here are my comments:

>Consider removing the grey border/table so the facilities are better tied to the H1.

I explored this in earlier versions, and the team wanted to stick w/ the bordered design pattern we have in the rest of profile to be consistent throughout this section of the site. I agree that there's room for improvement here and have this on my list of future improvements to consider.

>Consider using Update in secondary button (rather than Edit) to more closely tie with the intro paragraph where it says: You can update this list at anytime.

Again, in the spirit of consistency in the rest of profile, we'll stick with edit on the button label - but I updated the intro paragraph to say "You can edit this list at anytime".

>Recommend reviewing VAOS flow to ensure we're using same and consistent language when referring to a user's preferred facilities. Also we'll need to add content in VAOS letting users know they can update/edit facilities in Profile.

Yep, I agree. We'll be collaborating with them throughout this process and will be part of their design intent review as well.  

>Consider adding content when in edit list mode letting users know that by not selecting a facility, it will be removed from list. OR consider having users remove facilities they no longer use rather then select facilities they do use.

I'm not totally clear on this feedback point. Can you re-phrase and/or elaborate?  People aren't really "removing" any from their profile (e.g. nothing will get deleted); they're telling us what is current/not current.

I reviewed a more explicit way of saying this using radio buttons under each facility, instead of checkboxes. The options were "I still receive care here" and "I don't go here for care anymore" and the user would have to choose one or the other. Josh pointed out some a11y challenges with this repetition when I reviewed that w/ him though, so we stuck w/ the checkboxes.

**Comment by andaleliz** [comment]
@peggygannon I just realized that there was content above the checkbox on mobile that didn't get translated to desktop. Maybe that will help with your point about adding content when in edit mode...

![image](https://user-images.githubusercontent.com/55992116/113443336-c51d4b00-93bf-11eb-9566-ddd60b249353.png)

**Comment by peggygannon** [comment]
Hi, @andaleliz Yes, thank you for following up. My feedback was that we should provide users with some content as to what is happening or will happen when they select a facility. apologies for missing this on the mobile view!

**Comment by andaleliz** [comment]
I received great feedback from Allison that we need to include a success message.  What are your thoughts on the language in this mock-up? https://preview.uxpin.com/2c99ba26116e28b032d83eb4f636b448c9bde2b2#/pages/138006545/simulate/sitemap?mode=i

**Comment by andaleliz** [comment]
>Hi, @andaleliz Yes, thank you for following up. My feedback was that we should provide users with some content as to what is happening or will happen when they select a facility. apologies for missing this on the mobile view!

Oh yay! I'm glad we're good to go on this then. Thank you.

**Comment by peggygannon** [comment]
Hi, @andaleliz great suggestion from Allison. Here's my recommendation to make it active voice. (And note, health care is 2 words).  Please also run this alert by sitewide content. Tx!

We updated the list of facilities where you receive health care.

**Comment by andaleliz** [comment]
Thanks @peggygannon! I've updated the prototype with the new language, and added this to my content review request for sitewide content.

**Comment by andaleliz** [comment]
@peggygannon One more question, which I'm also reviewing with Danielle but want to get your input on. I'm considering linking the `schedule an appointment online` copy to the appointment scheduling page to make it easy for folks to go back to where they most likely came from, or complete that task if they need to do that from their profile.  Thoughts?

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/6f09bfbd-3eaa-4dac-8f4a-5764203fe687)

**Comment by andaleliz** [comment]
Hi @peggygannon, do I need to get your sign-off my last comment before we can close this issue? Still haven't heard from Danielle on this but hoping to discuss with her in content office hours on Thursday this week. Would love to close this particular issue in Sprint 44 if you feel everything has been addressed, given that we still need sitewide content to weigh in.

**Comment by peggygannon** [comment]
Hi, @andaleliz sorry for my delay. Yes, I agree with the decision to link back to make it easy for users. 
But again, please work with the content team on this! Let me know if you need anything from me at this stage? Otherwise we can close this issue.

**Comment by andaleliz** [comment]
We're good! Closing this out. Thanks.
