### ISSUE TITLE
[PM, Design] My VA: Review FE build

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22557]
## Background
In preparation for QA and testing the PM and Design team members should spend time reviewing the FE build and use case documentation to help provide additional validation.

## Tasks

- [x] Review [My VA use cases documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/MyVA%20-%20test%20cases.md) and feedback documented in #22185 
- [x] Test use cases for additional validation

**Comment by Samara-Strauss** [comment]
Hello! I wanted to check in about this while we're still plenty early in the sprint. My expectation around this is that **both** of you will do following:

- Test all of the [My VA test cases](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/MyVA%20-%20test%20cases.md) listed here on staging. Checking test cases now will help us get ahead for QA by fixing any obvious bugs. This way, the tool is going to be in better shape for QA, and it will free up brain space for Tze to find more granular/less-obvious issues and issues across browsers. You do **not** need to do multi-browser testing.
- For issues you find, please create bug tickets and assign them to FE so we have a sense of how much needs to be fixed and when we'll actually be ready for QA.

I would recommend doing this earlier rather than later in the sprint. And while I think things are probably pretty good to go now since the new My VA is up for all staging users, you might want to check in with Erik and Sandra before you start just in case there are known outstanding issues you should be aware of.

Let me know if you have any questions!

**Comment by ajakabcin** [comment]
Documenting all issues [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/My%20VA%20bugs%20pre-QA.md)

**Comment by Samara-Strauss** [comment]
Just completed my own QA. Things are looking great, and I've created a bunch of tickets for the issues I found. I did find some of the similar bugs that are noted in @ajakabcin's document, but I didn't create tickets for anything that already had one.

- [Results from my QA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/My%20VA_Samara%20QA.xlsx)
- [Slack thread with all the issues I created](https://dsva.slack.com/archives/C909ZG2BB/p1618324392019100)

**Comment by ajakabcin** [comment]
Closing this ticket - initial internal QA complete
