### ISSUE TITLE
Enable international phone numbers for profile

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2265]
@BBarone1 commented on [Thu Jul 26 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11750)

### FE work (@ncksllvn)
Should be a pretty low lift on the FE - we can easily add an input for the country code and remove what work we have now with ensuring USA-only - but it does depend on how sophisticated we want the UX to be

### BE work (@hpjaj): 
this former commit would be pretty representative of what we’d need to do:
https://github.com/department-of-veterans-affairs/vets-api/commit/70be1f95979614338dbffe2ff9307b5d6f7cc0ed

### What's needed
- [ ] UX for modal
- [ ] Vet360 is ready and capable (blocking ticket until this happens)

---

@hpjaj commented on [Fri Jul 27 2018](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11750#issuecomment-408466459)

Created this ticket to isolate the BE work:  https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11767

---

@batemapf commented on [Mon Sep 23 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11750#issuecomment-534152686)

Same deal on tis one as https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11767, @lkoenigsberg. Please let me know if you still need this.

---

@lkoenigsberg commented on [Mon Sep 23 2019](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/11750#issuecomment-534158591)

Will determine if we need this and if yes, incorporate into the Personalization 2.0 work.

**Comment by Justin-Pickett** [comment]
@lkoenigsberg will follow up with Vets360 team on this item.

**Comment by lkoenigsberg** [comment]
@Justin-Pickett ,

Confirmed that V360 does support international phone numbers.  The two required fields in the snippet here, countryCode and internationalIndicator identify its international

![international-phone](https://user-images.githubusercontent.com/51327745/66509937-00c4a680-eaa2-11e9-9ceb-78a0631083c2.png)

Propose next steps to do some cleanup between this ticket and https://github.com/department-of-veterans-affairs/va.gov-team/issues/2266 so that we can make a valid work request.

Please note that we probably won't do this work until after profile/account project is complete or as part of it if it's feasible.

**Comment by Samara-Strauss** [comment]
Update on this: I asked VA Profile today whether we should pursue this work and they said we could but international numbers aren't currently accepted by VHA or VBA. This makes the work kind of pointless on our end until updates from VA.gov can get written to other systems.

**Comment by Samara-Strauss** [comment]
Closing this. VA Profile doesn't have immediate plans to add international phone numbers. If/when this happens, we will open a new ticket.
