### ISSUE TITLE
Design Feedback - Design intent [VSA Authenticated Experience, Communication Permissions (Notification Preferences)]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#22706]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Nice work! You can tell you put a lot of thought into how these might work best.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Add a success alert (I know you mentioned you planned on adding one during the meeting)

**Should:**
- Remove icons, the On/Off text will be enough and less cluttered
- See if you can fix the text so it aligns, not sure if this is in the design system like this.![image.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/d55dc2cf-ff1f-4f97-8f99-4761b9c47968)

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by andaleliz** [comment]
Hi @allison0034, thanks for the feedback and facilitating the review session! Here are my comments:

>Add a success alert (I know you mentioned you planned on adding one during the meeting
Remove icons, the On/Off text will be enough and less cluttered

The prototype now reflects both of these updates.

>See if you can fix the text so it aligns, not sure if this is in the design system like this.

This is actually a symbol (custom, not design system) so the text is the exact same number of pixels from the edge. I think it just looks off due to the serif on the `H` and the curve of the `O` being so different.
