### ISSUE TITLE
Prioritize NOD Research Findings for Design

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#22709]
## Issue Description
Evaluate NOD design feedback and determine implementation schedule

---
## Tasks
- Prioritize phase 1 & 2 tasks

## Acceptance Criteria
- [ ] Plan documented in ticket
---

**Comment by kevinstachura** [comment]
Prioritized design items for NOD. For the first phase:

- In No. 1 of the subway map, please capitalize "Board Appeal" in the 2 places where it needs it.
- In No. 1 of the subway map, please capitalize "Supplemental Claim"
- Change "decision letter" to "decision notice"
- In No. 2, under the question, "What if I need help...?" change the first 2 sentences to: "If you need help requesting a Board Appeal, you can contact a VA regional office near you. <br>[Find a VA regional office near you] LINK
- In No. 4, lowercase "the" / add an "s" and an apostrophe to "Veterans'" / capitalize  "Appeals" where you have "the Board of Veterans' Appeals."
- In No. 5, please change the sentence to: After the Board has made a decision on your case, you'll get a decision notice in the mail.
- Just above the whole subway map, there's a sentence about "if you don't think this is the right form for you" --where does that link take the user back to?
- Make the representative’s email address optional or remove the question.  
- Consider if the Request a Board Appeal button is noticeable enough. (action links - discussed in our VA design sync)
- Change the copy about …opting into the new process on the Board Appeals Info page: use plain language, simplify language, consider not using legacy appeals process, but instead old and new appeals process. 
- Consider making the drop-down link 'Why aren’t all my issues listed here?' more noticeable. 
- Change copy on button Track the status of your claim to ...appeals.
- Change copy of 'representative name' of something that denotes an organization is possible
- Create a sentence to explain that an organization is fine to use as well.

For the second phase:

- Change the copy of the Opt-in note from Legacy Appeals Process to plain language (e.g. new and old appeal process). Simplify and clarify the copy about the opt-in process, and make it consistent with the copy about the opt-in process on the Board Appeals Info page.  
- Due to the incomplete list of issues eligible for Board Appeal, allow veterans to instead manually add the issues they want to appeal to the board. Caveat: if the list of issues in fact shows most of their issues, keeping the list makes sense (we are waiting for more data on this.)  
- Make the copy on the Board review option page consistent with the Board Appeals Info page. Simplify language if possible. Add the time estimates to both pages. 
- Address all of Robin's comments from design --> dev
- Create a 'board hearing preference' page
