### ISSUE TITLE
IA Feedback - Design Intent - Profile: Notification Preferences

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#22741]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- User flow/entry points:  Identify whether static content page is needed to support an entry point for this feature and for SEO.  Most auth tools have a corresponding static landing page optimized for SEO, however, I'm not sure this is a highly sought after feature, and this may not be necessary.  A good alternative would be to include content in Resources & Support to provide support content on the ability to manage notification preferences and how it works.    
- Navigation components: Recent IA and accessibility discussions recommended changes to the breadcrumb, which should be accurately reflected within this prototype. Here is the issue for background info: https://github.com/department-of-veterans-affairs/va.gov-team/issues/19552

**Should:**
- Navigation components: What is the order of nav options within the left nav based on? Recommend reviewing user feedback and usage data to determine priority/high traffic items, and review for potential groupings.  Strongly recommend including all in progress/proposed options within the left nav for user testing to gain insights on the impacts of the growing list of navigation items. 

**Consider:**

**Comment by andaleliz** [comment]
@Samara-Strauss, I didn't include facilities AND notification preferences in my mock-ups because I wasn't sure which one would launch first.  Mikki raises a good point about including all proposed options within the left nav when we test.  Your comment about the order going from "things we know about you" to "general account information" makes sense.  Based on that, I'm thinking the order would be:
- Personal and contact information
- Military information
- Direct deposit information
- Your VA health facilities
- Notification settings
- Account security
- Connected apps

How does that align with how you'd order it? I'll update the mock-ups for both initiatives to reflect the new order so we can learn how that impacts users in usability testing with whichever product ends up going first.

**Comment by Samara-Strauss** [comment]
That looks like how I'd order it! @mnorthuis how does this look to you?

**Comment by mnorthuis** [comment]
The only one I'm not sure about is Account security...I'm wondering if that should be the last option?  Your facilities, notification settings and connected apps are all sort of things personalized for your account, but account settings is sort of its own feature.   Also, the last option in a list like this gets the benefit of added visibility and recall.  Just a thought.   

Ultimately, its still a bit of a space to learn more in, and may continue to evolve as more things are added.

**Comment by Samara-Strauss** [comment]
I would be game to move Account security to the bottom of the list if that's the recommendation. That rationale is sound to me.

**Comment by andaleliz** [comment]
Sounds good to me too. So the new order I'll reflect in my mock-ups will be:

- Personal and contact information
- Military information
- Direct deposit information
- Your VA health facilities
- Notification settings
- Connected apps
- Account security

**Comment by Samara-Strauss** [comment]
Sounds good!

As a side note, I would love to do some testing on the nav as it grows. That would likely be separate from this project work and be something we could test via tree or click testing or some other unmoderated mechanism. But throwing it out there as something that is one my mind as the profile grows and changes.

**Comment by andaleliz** [comment]
@Samara-Strauss I added that to my doc of research ideas for profile so we don't lose track of it.

The prototype now reflects the new nav order and items 🎉 

@mnorthuis, responding to your two other points of feedback:

> User flow/entry points: Identify whether static content page is needed to support an entry point for this feature and for SEO. Most auth tools have a corresponding static landing page optimized for SEO, however, I'm not sure this is a highly sought after feature, and this may not be necessary. A good alternative would be to include content in Resources & Support to provide support content on the ability to manage notification preferences and how it works.

I do think a resources and support content page should be created to support self-service.  Given our dependency on the VA profile team, I'm not sure when it makes the most sense to kick off the process of getting this created. I imagine it'd be completed at the same time we work on updating the profile product guide for the call centers, since we would have all the functionality ironed out by then. I'll ask @ajakabcin to capture this in the roadmap so this doesn't get lost.

As far a a static content page, I think this is something to revisit once we know more about exactly which notifications we'll be launching with. Research can also help us understand if this is a highly sought after feature, and whether or not it'll be necessary.  My gut tells me we don't need both a support page and a static content page for this. I'll add this to my list of research questions to be sure we try to get some answers around this.  

> Navigation components: Recent IA and accessibility discussions recommended changes to the breadcrumb, which should be accurately reflected within this prototype. Here is the issue for background info: #19552

Ack, sorry I made you repeat that catch from the last review! The prototype is updated with this new breadcrumb pattern.
