### ISSUE TITLE
Implement new sidebar navigation on Pittsburgh health care

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#2278]
The sidebar for the [Pittsburgh health care](https://staging.va.gov/pittsburgh-health-care/) section of the website will serve as a pilot for a new site-wide sidebar design.

**Page**:  https://staging.va.gov/pittsburgh-health-care/
**Design**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/page-nav/design/VA-gov-on-page-nav-MASTER.pdf

### Requirements
- [ ] Implement new navigation on Pittsburgh section of the website according to designs
- [ ]  Implement behind feature flag so that it can be tested in Staging prior to being promoted to Production.

### Other considerations
- The markup and style behind this new sidebar should be considered for a migration into the design system
- This sidebar is generated from CMS data. You can see this data by opening the JavaScript web console at https://staging.va.gov/pittsburgh-health-care/. See the output under `Context specific sidebar data recursive`
- If you don't have access to the CMS from your local machine, you can fetch a cached version via [fetch-drupal-cache](https://github.com/department-of-veterans-affairs/vets-website/blob/master/package.json#L10)
- Historically, va.gov sidebars are drawn via Liquid templates (`.drupal.liquid` extension). Should we consider React for this? What would the justification be for using React over Liquid? Is there SEO impact with a React widget loading post-page load?

**Comment by ncksllvn** [comment]
@kelsonic Before getting started, can you walk me through whether you're leaning React vs. Liquid for this?

**Comment by kelsonic** [comment]
@ncksllvn I'd prefer to use React over Liquid, but I'm actually not opinionated at all. What do you think is best for this? Just trying to think of how we can reuse this navigation component in other parts of the site if/when the use-case comes up :)

**Comment by ncksllvn** [comment]
On one hand, if we use a sidebar, our React applications will be able to leverage the component if that's ever necessary. And, in general, it's more dev-friendly, scalable, and easier to debug. So there's a definite argument to be made for React.

But I think Liquid would be a quicker implementation, since we're already set up to draw sidebars using Liquid. And, since the end HTML is written directly to the page (as opposed to being rendered post-page load from React), there _may_ be an SEO disadvantage to React (unlikely though.) I'm also not sure how much interactivity there is with the new sidebar, so maybe React is overkill.

If you want to take some time to do a deep dive into the designs and think more about which tool to use before deciding, please do!

**Comment by ncksllvn** [comment]
Either way, we should definitely consider its end markup and style to be included in the design system, https://design.va.gov/components/. The repo for that is [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools).

**Comment by kelsonic** [comment]
1. >our React applications will be able to leverage the component if that's ever necessary
True, so I think we need to know whether or not we want to continue using Liquid files for these facility location show pages (e.g. https://staging.va.gov/pittsburgh-health-care/) or if we would prefer controlling everything with React/Redux in the long-term.

2. >I think Liquid would be a quicker implementation, since we're already set up to draw sidebars using Liquid.
So after looking at the code a bit more, it will definitely be easier to do this in Liquid since the nav is already implemented in it (we'd just need to change some conditional rendering and styling). That said, if we plan on trying to unify the FE tech stack to just React/Redux in the long-term, it's probably worth the time investment to convert this page to React/Redux over Liquid.

3. >there may be an SEO disadvantage to React (unlikely though.)
For Google SEO, this is not a problem. For other search engines, I'm uncertain if they wait until time to interaction finishes before they move on to index other pages. This is something we should test.

4. >I'm also not sure how much interactivity there is with the new sidebar, so maybe React is overkill.
True, though my guess is that the design will change a few times in the near future, which could result in more complex functionality.

So I think I will go for updating Liquid designs at the moment unless our goal is to move to a fully React/Redux tech stack in the long-term. @ncksllvn

**Comment by Karak888** [comment]
@kelsonic is hoping to finish by end of week.  we can then go to usability and UI work.  potentially can create resuable sidebar nav and have that live in formation.

**Comment by Karak888** [comment]
Hi @kelsonic, just wondering who was doing the QA review and what status of that was?  Thanks!

**Comment by kelsonic** [comment]
@Karak888 Nick has reviewed the [current PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10881) and all comments have been addressed. That said, there's still a few blockers I need to update:

1. bug when switching pages since the raw data we get is incorrect (some items are expanded when they shouldn't be)
2. unit tests
3. standardize the styling
4. the design didn't specify the behavior when hovering/clicking nav items/etc., so should confirm that the UX and the UI is correct
5. need to update the sidenav to be 1/3 instead of 1/4 width
6. fix rogue linting errors I couldn't seem to find/fix 🤔
7. Add aria attributes to buttons, make nav item row a `button` instead of a `div`
8. (stretch) abstract out complexities in SideNav into functional components

I will put a green checkmark by each point above as I knock them out! 🔨

**Comment by Karak888** [comment]
thank you @kelsonic!  we miss you already!

**Comment by kelsonic** [comment]
Just to keep in mind when validating this ticket, there needs to be 6 tickets that get created for the new `SideNav`:

1. Accessibility improvements (maybe loop in 1Copenut to check it out)
2. Port to the design system (Formation) (Mostly SCSS naming conventions)
3. Unit tests
4. Need to update the sidenav to be 1/3 instead of 1/4 width on each page that uses it.
5. Abstract out complexities in SideNav into functional components.
6. Update expanded logic to not rely on original data structure.

**Comment by jenniferlee-dsva** [comment]
@kelsonic - when you're ready, please connect with @rtwell for a few additional design things we want to get in for the usability test. I will check in later to see if it looks like we are okay to give Kevin Hoffman okay to start recruiting for users. Thanks all.

**Comment by Karak888** [comment]
moving to close this issue as it is encapsulated elsewhere,
