### ISSUE TITLE
RFC- enable branch protection rule: "Require branches to be up to date before merging"

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2286]
# Overview 

- Branches are not required to be up to date with master before before merging changes. 
- Automatic validation occurs when a pull request is created. It can take up to two days for a pull request to be reviewed by the front end review group which makes the automatic validation stale when the PR is approved to be merged 
- Purpose of this RFC is to gather feedback on forcing branches to be up to date before they are merged. This is type of [required status check](https://help.github.com/en/articles/enabling-required-status-checks) provided by Github. 

## Pros 

- no chance for conflicts / collisions from multiple merges with stale automatic approval 
- more accurate automatic checks: automatic checks / approves are performed against the current HEAD of master branch instead of the commit used when the branch was created 

## Cons 

- can delay merges: merges by other engineers can require additional merges + additional automatic checks to be run  

## Notes

- `vets-api` has this feature enabled. 
- decision should be made no later than 10/14/2019

**Comment by cvalarida** [comment]
We've definitely felt the effect of not requiring branches to be up-to-date with `master`, so I'm generally in favor of this.

Waiting for additional builds after merging in master is not ideal, but usually just a minor annoyance. (Potentially not-so-minor if it delays merging by hours because you can't time it right.)

The only genuinely negative downside I can see is if we're trying to merge an emergency bug fix. Possible solutions include
- Having an option to merge anyway
  - Does GitHub provide this override?
- Communicating to the whole team to not merge anything into `master` until the fix is in
  - As always, if the process involves humans, it's liable to break down at some point—especially as we add more teams making changes to `vets-website`

**Comment by jbalboni** [comment]
Some historical context: in the early days of vets.gov, we had this turned on. We turned it off because there were a lot of merges happening in vets-website at that time and it was often difficult to go 20 minutes (the build time) without someone merging something. There was a lot of babysitting of PRs, trying to get them merged. One dev wrote a JS snippet (maybe an extension, don't remember) to ping him when a build on a PR finished, so he could merge it ASAP.

It's hard to say if that's a problem now, but if you look at 10/3, there are 13 commits between 8am and 5pm EST, which is about 1.4 per hour. There likely would have been times that day when trying to get your changes merged would have required a couple extra pulls from master.

In my experience, this is a setting that doesn't scale up. If you expect more and more commits, this setting becomes more and more painful.

**Comment by annaswims** [comment]
@cvalarida we have "Enforce all configured restrictions for administrators." set. But in a pinch, I think and admin could unselect that and then merge.

**Comment by rianfowler** [comment]
@jbalboni good points- I guess we could:

- figure out if we can shorten the automatic validation to an acceptable execution time (e.g. parallelizing it into multiple validations, re-evaluating what we're validating / removing work) 
- moving the merge step into `Jenkins` as part of the automatic validation.

**Comment by cvalarida** [comment]
:thinking: The problem we're trying to solve is conflicting code causing errors or bugs in `master`. I initially thought moving the merge step into Jenkins would solve it, but consider the following scenario.

**Scenario**
Say we have the file `awesome-feature.js`:
```js
import foo from 'foo';
...
const { someCoolThing } = foo;
...
```
PR A removes the need for `someCoolThing`, so they remove that line. Since it was the only line using `foo`, they remove the `import` as well.

At the same time, we have PR B, which has the following:
```js
import foo from 'foo';
...
const { someCoolThing } = foo;
...
const { anotherAwesomeWidget } = foo;
...
```
Both PRs pass by themselves.

1. PR A gets pushed out
    - Jenkins pulls in `master` and runs all the validation
1. PR B gets pushed out
    - Jenkins pulls in `master` and runs all the validation
1. PR A gets merged
1. PR B gets merged

Now our file looks like:
```js
const { anotherAwesomeWidget } = foo; // foo is undefined; the import was removed in PR A
```

The only way to prevent this would be to have Jenkins run all the validations _before merging_ and PR. It didn't even result in a merge conflict, so we can't only re-validate when we detect a merge conflict. :disappointed:

There's some fancy footwork we could maybe work with git, but it gits (:trollface:) mighty gross mighty quick, I think.
