### ISSUE TITLE
IA Request [Platform Analytics, Analytics Grouping]

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#22860]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kick-off ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/google-tag-manager/google-tag-manager-product-outline.md) 
- Link to or attach [prototype or mockups](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-pages/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.pageGroup1&explorer-table.plotKeys=%5B%5D/)
- Link to or attach user/page flows
- Link to or attach your [content source of truth](https://github.com/department-of-veterans-affairs/va.gov-team/blob/ga-event-label-consolidation/teams/vsp/teams/insights-analytics/ga-events-data-dictionaries.md), including H1s (if separate from prototype/mockup)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

Background: we’re organizing analytics to the VA.gov benefit hubs and want to ensure we’re not doing it in opposition to how y'all are organizing the IA on VA.gov. This will help us:

- give analytics to VFS teams that they can more easily navigate and more accurately read
- use the analytics on Platform to prioritize top Veteran products 
- ensure that we're reporting more accurate data on VA.gov - not over or underreporting usage
- ensure that our analytics is consistent with how VA.gov is organized

**Content/feature placement** - Google Analytics, and eventually BigQuery & Domo

**Keywords and SEO** - N/A

**URL(s)** - N/A

**Primary entry points** - N/A

**Crosslinking opportunities** - N/A

**Redirects** - [Old dashboard tool](https://docs.google.com/spreadsheets/d/1-1GYhR5RFItrYee2Yki_nuMW3XKYrWVzoZ8dppS3hb4/edit#gid=628587422)

## Definition of Done
- [ ] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
Here are thoughts/questions on the Benefit hub and Product Groupings.   I wasn't sure if you wanted me to continue to review beyond these groupings?  There are others on this page that interest me, but didn't want to go too far :-)

General questions/thoughts:
- For invalid URLs  (i.e. /gibill, /health-?care, etc), I can see the value of tracking these in their appropriate grouping because its a way to get at that group of content, however I have a couple of questions  1) can we capture these in a 404 report so we can track the frequency these happen?  Then we can look at options to help users get to the right content (i.e. custom 404, redirects, etc).   2) Is this approach sustainable as the site grows to identify and group invalid urls?
- There is a work effort to move certain content pages out of their respective benefit hubs and into /resources.  This may be worth a discussion in terms of how this will impact benefit hub reporting - numbers may appear to go down as content is shifted. 
- What is generally the difference between a Benefit hub grouping and a Product content grouping?   It looks like most of the product groupings are forms/tools/funnels, but there are some that are strictly content - I'm more thinking about those strictly content areas that include a significant number of pages (i.e. /resources, *-health-care).
- The `/resources` area also has a search function in it, it may be helpful to look at that capability separately from the general /resources content.  That functional also ties into the global search. 


Benefit Hubs Content Grouping
- `/pension` - We do not currently have any Fiduciary content in our modernized VA.gov as of yet.  I am not sure if this will be part of Pension, it may likely be more global, so may not be accurate to include in label at this time. 
- `/health-care/get-medical-records` - I would consider getting feedback from the health tools team (Lauren A) on this one.  In my mind, they may want this grouped with health care with the other health tools, but they could feel this is a different type of information not related to health tools. 
- `/track-claims/your-stem-claims` - Wondering what the rationale of tracking this with education instead with the rest of the tool traffic is?  The tool contains a number of different types of claims/appeals
- `/track-claims` and `/claim-or-appeal-status` - The majority of traffic to this tool is for disability claims, however, this tool is more global than disability, I would keep this out of a benefit hub grouping and just treat it as a product
- The "Records" hub is a bit of an odd duck in that its more of a jumping off point.  Some things live under this directory, and other things do not.   Its a grouping of various products.  I could see this hub evolving over time, just an fyi. 


Products Content Grouping
- For things like Debt Management, there are multiple tools that live under a top level parent page (`/manage-va-debt`), I am assuming that we can always look at this group of related tools based on that parent page?  
- For the VAMC product grouping, there is one page within the health care hub that includes `-health-care` in it's url: www.va.gov/health-care/about-va-health-benefits/va-health-care-and-other-insurance/.  Its not a highly trafficked page, but might get pulled into this data?
- Curious as to why the GI Bill comparison tool is broken up between the main url and the /profile page?
- When looking at data for specific products/tools, do (should) teams want to include the static page that is the entry point for that tool?  For example `/discharge-upgrade-instructions/guidance.*`, why not just look at anything in `/discharge-upgrade-instructions*`?
- I noticed `/change-direct-deposit` and `/change-address` are tracked as products - they are only static pages and the actual capability is in profile. 
- FYI the URL for the Veteran Readiness and Employment Form CH31 (28-1900) is incorrect.  I just informed the team today - I'll make sure they follow up with you on that correction once they make it. It should be /careers-employment/vocational-rehabilitation/apply-vre-form-28-1900/
- Curious about tracking the static How to apply pages as products, i.e. `/disability/how-to-file-claim`. 
- This url `^/disability/eligibility/special-claims/automobile-allowance-adaptive-equipment` is a static page, the form referenced in what is being tracked (4502) is just a pdf, not an online form. 
- Should `/education/yellow-ribbon-participating-schools/` be tracked as a product/tool?  It is a search tool to find yellow ribbon participating schools. 
- Should the overall `/find-locations` tool be tracked as a product?  I see the facility detail pages are in the list - those will eventually (long term) wind down and be replaced with the modernized pages. 
- What is the difference between `^/health-care/apply/application.*` and `^/health-care/apply/application/introduction.*`?

**Comment by jonwehausen** [comment]
Hi @mnorthuis , 

Thank you so much for your thorough review and analysis here. 

A couple follow-up notes: 
>For invalid URLs (i.e. /gibill, /health-?care, etc), I can see the value of tracking these in their appropriate grouping because its a way to get at that group of content, however I have a couple of questions 1) can we capture these in a 404 report so we can track the frequency these happen? Then we can look at options to help users get to the right content (i.e. custom 404, redirects, etc). 2) Is this approach sustainable as the site grows to identify and group invalid urls?
 
 _**Yes we do have the ability to look at the content within each bucket that is 404s. Today, you can see a breakdown of where 404s have occurred in GA [here](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath&_r.drilldown=analytics.eventLabel:nav-404-error/). To your point, if we want to filter-out 404s in the content grouping reports, we would need to make some tracking adjustments to ensure these pageviews don't count with the other valid URLs in the group**_

>There is a work effort to move certain content pages out of their respective benefit hubs and into /resources. This may be worth a discussion in terms of how this will impact benefit hub reporting - numbers may appear to go down as content is shifted.

_**You are correct -- as content is shifted, pageviews will be reflected according to the content group the page lived in at the time the data was collected. There are certainly positives and negatives to this on the GA side-- the biggest thing to note on this is we have the ability to alter the content groupings according to whatever taxonomy we need within BigQuery, and we can do so for historical pageviews when/if we need to as well.**_

>What is generally the difference between a Benefit hub grouping and a Product content grouping? It looks like most of the product groupings are forms/tools/funnels, but there are some that are strictly content - I'm more thinking about those strictly content areas that include a significant number of pages (i.e. /resources, *-health-care).

_**Great question - the general difference is the benefit hubs are designed to align with the Veteran benefit hubs (and/or "parent product") reflected in the main site navigation while the products are a mixed bag of forms/tools/funnels/apps/content/feature that reflect a more specific component of the site within a larger benefit hub. I know this has been an ambiguous concept for other folks within VSP as well -- for us we try to have any specific deployment "item" identified as a product content group where we can. For items that don't have a clear benefit hub, we may identify the product directly (i.e Privacy Policy)**_

>The "Records" hub is a bit of an odd duck in that its more of a jumping off point. Some things live under this directory, and other things do not. Its a grouping of various products. I could see this hub evolving over time, just an fyi.

_**Yes I agree, we would like to have a further discussion of this one as well**_


_**Will continue with the rest of your questions/points in a separate post**_

cc: @laurenernest @bsmartin-ep

**Comment by joanneesteban** [comment]
Thanks @mnorthuis ! Really appreciate your support on this work.

To answer your question,
> I wasn't sure if you wanted me to continue to review beyond these groupings? There are others on this page that interest me, but didn't want to go too far

Benefits & Products content grouping is great! Those are the groupings that are in scope right now for us. So no need to delve beyond that unless you want to!

**Comment by mnorthuis** [comment]
@joanneesteban Perfect, thank you!  As much as I'd like to dig further, I don't have the bandwidth right now.  However, I'd love to continue to partner any time you see fit.  I'll mark this issue as complete for me, but am available to answer any questions or provide more information regarding my feedback above. Thanks for including me in this work!

**Comment by shiragoodman** [comment]
Thank you @mnorthuis for helping out a fellow VSP team :)

@joanneesteban did you still need assistance with content/plain language? Let me know and we can discuss.

**Comment by joanneesteban** [comment]
@shiragoodman @mnorthuis thank **you** for your support! 

We have a few things that I think we'll need some plain language review on, but the first priorities would be:
- Dashboard review (reviewing the language on our dashboards to ensure that they're plain language)
- Dashboard _data_ review (reviewing the data _labels_ that users can see from the dashboard data so that they can better understand it)

I'd say that those are medium-high priorities right now, so I can open a content/plain language ticket, but if y'all don't have time to QA, we can push this back if we need to.

Thank you!

**Comment by shiragoodman** [comment]
@joanneesteban could you open a ticket for this work, assign to myself and Peggy and put the vsp-product-support label on it? Peggy has some time this sprint and can get started on it.

**Comment by mnorthuis** [comment]
IA work complete for this, closing issue.
