### ISSUE TITLE
Find a VA Form: Internal testing - test search matching/ranking in Forms API on Staging

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#22866]
## User Story

As a Veteran, I would like search results to be highly relevant to the search term I entered, and ranked in order of relevance/popularity.

## Expected Behavior

When a Veteran enters a search term, the results presented and are highly relevant based on how well they match the term entered, and ranked on where the term appears in the metadata, as well as how popular the form is, based on metrics.

### Test search terms
Direct Deposit - currently returns 9 results in Production
health - currently returns 37 results in Production
Power of Attorney - currently returns 162 results in Production
Care - currently returns 22 results in Production
Certificate of Eligibility - returns 178 results in Production
SF - returns 28 result, An actual SF form is #7
1010 => 10-10
1010ez => 10-10ez
21P1775 => 21P-1775
210304 => 21-0304

## Acceptance Criteria
- [ ] Test Find a VA Form on Staging with search ranking/scoring logic incorporated into Forms API,  determine if additional iterations, further testing needed
- [ ] Create new issues for remaining work and/or testing

**Comment by zacharymorel** [comment]
Going to delay this @MarciMcGuireGCIO correct?

**Comment by MarciMcGuireGCIO** [comment]
We are going to work with Lighthouse on it.  I will update the description to indicate that, and you can put your time on this issue.

**Comment by MarciMcGuireGCIO** [comment]
Note - updated description and AC based on meeting with Lighthouse team about implementing the logic in the Forms API so that all users can benefit from better matching.

**Comment by MarciMcGuireGCIO** [comment]
Moved to Sprint 47 since we asked the Lighthouse team to make the Spanish URLs a priority this sprint.

**Comment by MarciMcGuireGCIO** [comment]
Add list of search terms to test with

**Comment by MarciMcGuireGCIO** [comment]
2021-05-12 - meeting with Zach & Mark
- Mark has already implemented search matching built into Postgres, which is very advanced.   If the page is refreshed on Staging, it produces very good results.  
- Zach and Mark are working together to figure out why it requires a refresh & that will likely need a front-end code change.
- We will test results on Staging with the goal of hitting our Staging review with VSP next Tue

**Comment by MarciMcGuireGCIO** [comment]
Internal testing results:  

Direct Deposit - currently returns 9 results in Production, 9 in Staging, but direct deposit forms are at the top now.

health - currently returns 37 results in Production - returns 37 in Prod, but the ones with Health in the name and related to Health care are at the top.

Power of Attorney - currently returns 162 results in Production - returns 2 in Staging, one has Power of Attorney in the name, the other has Attorney in the  name.

Care - currently returns 22 results in Production - 22 results in Staging, top results have Care in the name

Certificate of Eligibility - returns 178 results in Production - 63 results in Staging, form with that phrase is now at the top

SF - returns 28 result, An actual SF form is #7 - 23 results in Staging; all start with SF

1010 => 10-10  - **this one needs tweaking.  It returns 172 in Staging, and forms that start with 10-10... are not at the top.  First form is 10-0094

1010ez => 10-10ez - Staging matches Prod. Returns correct form.

21P1775 => 21P-1775  **Returns 21P-1775.  Doesn't return anything on Staging, but 21P-1775 is in the DB.**
210304 => 21-0304  - Staging matches Prod. Returns correct form.

Other improvements - 
- Disability returns Disability and Disabled.
- Nurse returns Nurse and Nursing
- 'ed' only returns things with Education in them instead of any string with the letters 'ed' (22 vs. 138)
- 'med' returns medical, meds, medicine-related results on Staging.  Prod also include things with "med" in the middle of a word.

**Comment by johnhashva** [comment]
Promising results -- is ranked by popularity (downloads) a component of the logic -- or can it be?

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva that will be in another iteration once Mark has the ability to pull popularity data into his table.

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO I pointed Mark to reference this chart for additions to the api => https://github.com/department-of-veterans-affairs/va.gov-team/issues/20651#issuecomment-797594089

**Comment by MarciMcGuireGCIO** [comment]
| Prod | Staging | Change Direction            | Comments                                                                                                                                                                                             |
|------|---------|-----------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 3    | 3       | Neutral                     | No change                                                                                                                                                                                            |
| 2    |         | Positive                    | Now includes "nursing"                                                                                                                                                                               |
| 9    | 9       | Positive                    | full phrase matches at top                                                                                                                                                                           |
| 170  | 40      | Better, but not as expected | Expect forms with literal "release of information" in name to appear at top.  Looks like "of" is being disregarded, even in the middle of a phrase.  Other: Title of 10-259 needs to be fixed in CMS |
| 12   | 12      | Neutral                     | No change                                                                                                                                                                                            |
| 0    | 0       | Neutral                     | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                 |
| 110  | 6       | Positive                    | full phrase matches at top,  not matching "and" as a single word drastically improves results                                                                                                        |
| 1    | 101     | Negative                    | Looks like "va" and "form" are no longer being disregarded                                                                                                                                           |
| 178  | 63      | Positive                    | full phrase matches at top, not matching "of" as a single word drastically improves results                                                                                                          |
| 6    | 6       | Neutral                     | No change                                                                                                                                                                                            |
| 170  | 4       | Positive                    | No exact match, but not matching "of" as a single word drastically improves results                                                                                                                  |
| 87   | 3       | Positive                    | full phrase match at top, not matching "to" as a single word drastically improves results                                                                                                            |
| 4    | 4       | Neutral                     | No change                                                                                                                                                                                            |
| 195  | 44      | Positive                    | No exact match, not matching "of" as a single word drastically improves results                                                                                                                      |
| 170  | 4       | Positive                    | partial phrase matches at top, not matching "of" also drastically improves results                                                                                                                   |
| 5    | 5       | Positive                    | full phrase match at top                                                                                                                                                                             |
| 2    | 2       | Neutral                     | No change                                                                                                                                                                                            |
| 9    | 15      | Positive                    | Bonus - now includes "disabled"                                                                                                                                                                      |
| 0    | 0       | Neutral                     | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                 |
| 24   | 32      | Positive                    | Full phrase match at top; bonus - also includes "medical record" without the s                                                                                                                       |
| 0    | 0       | Neutral                     | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                 |
| 162  | 2       | Positive                    | full phrase match at top                                                                                                                                                                             |
| 8    | 9       | Positive                    | Matches with both words (even though not the the same order) at the top                                                                                                                              |
| 29   | 29      | Neutral                     |                                                                                                                                                                                                      |
| 249  | 206     | Better, but not as expected | "va" and "form" are no longer being disregarded                                                                                                                                                      |
| 17   | 20      |                             | bonus - also includes "authority"                                                                                                                                                                    |
| 0    | 0       | Neutral                     | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                 |
| 162  | 12      | Positive                    | full phrase match at top                                                                                                                                                                             |
| 240  | 87      | Positive                    | No exact match, but not matching "for" as a single word drastically improves results                                                                                                                 |
| 325  | 69      | Positive                    | full phrase match at top, not matching "in"  and "of" also drastically improves results                                                                                                              |
| 1    | 1       | Neutral                     | No change                                                                                                                                                                                            |
| 165  | 9       | Positive                    | full phrase match at top, not matching "of" also drastically improves results                                                                                                                        |
| 26   | 29      | Positive                    | full phrase match at top                                                                                                                                                                             |
| 249  | 120     | Positive                    | full phrase match at top, not matching "for" also drastically improves results                                                                                                                       |
| 50   | 50      | Positive                    | full phrase matches at top                                                                                                                                                                           |
| 3    | 7       | Neutral                     | also brings back matches for "direct"                                                                                                                                                                |
| 13   | 13      | Neutral                     | No exact match before or after                                                                                                                                                                       |
| 42   | 42      | Positive                    | full phrase matches at top                                                                                                                                                                           |
| 12   | 6       | Positive                    | Not returning every form with 35 in in the number                                                                                                                                                    |
| 21   | 24      | Positive                    | Also returns matches for "authority"                                                                                                                                                                 |
| 199  | 61      | Positive                    | No exact match, but not matching "of" as a single word drastically improves results                                                                                                                  |
| 233  | 90      | Positive                    | full phrase match at top, not matching "for" also drastically improves results                                                                                                                       |
| 2    | 2       | Neutral                     | No exact match before or after                                                                                                                                                                       |
| 87   | 90      | Positive                    | Matches with both words (even though not the the same order) at the top                                                                                                                              |
| 232  | 86      | Positive                    | No exact match, but not matching "for" as a single word drastically improves results                                                                                                                 |
| 15   | 9       | Positive                    | No longer including results with "change" found in the middle of the word "exchange".                                                                                                                |
| 255  | 107     | Positive                    | Matches with both words (even though not the the same order) at the top. Excluding "for" also improves results                                                                                       |
| 4    | 8       | Positive                    | Also includes matches with  "parties"                                                                                                                                                                |
| 28   | 31      | Positive                    | Matches with both words (even though not the the same order) at the top.  Also includes "benefit".                                                                                                   |

**Comment by MarciMcGuireGCIO** [comment]
> @MarciMcGuireGCIO I pointed Mark to reference this chart for additions to the api => [#20651 (comment)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/20651#issuecomment-797594089)

Poifect! 👍🏻

**Comment by MarciMcGuireGCIO** [comment]
Moving this testing to Sprint 38 due to delays in technical delays that prevented Lighthouse team from initially getting deployed to Staging https://dsva.slack.com/archives/CUB5X5MGF/p1620663287173100

and technical delays that prevented deployment of the subsequent bug fixes on 5/18  - see https://dsva.slack.com/archives/CUB5X5MGF/p1621368477004200?thread_ts=1621368229.003800&cid=CUB5X5MGF

**Comment by MarciMcGuireGCIO** [comment]
Consolidated internal testing comments:

**Comment by johnhashva** [comment]
Based on 5/23 (Sunday) Review:

- We are going to default by Closest Match, right?
-

| Search term                                                    | Prod | Staging | Change Direction                                                   | Comments                                                                                                                                                                                           |
|----------------------------------------------------------------|------|---------|--------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1010                                                           | 26   | 187     | 🔴 Negative                                                           | (Marci: what is most popular 1010 form?) 187 results for Staging vs. 26 for Production.                                                          |
| 1010ez                                                         | 3    | 4       | 💚 Positive                                                           |                                            |
| 21P1775                                                        | 1    | 1       | Neutral                                                            | same results                                                                                                                                                                                       |
| 210304                                                         | 1    | 2       | 💚 Positive                                                           | Also brings back 21-0307 which could account for a potential mis-type                                                                                                                              |
| va form 21-526                                                 | 1    | 1       | Neutral                                                            | same results                                                                                                                                                                                       |
| represenative                                                  | 0    | 4       | 💚Positive                                                           | purposely misspelled based on research study; now brings back forms with the word Representative in the name.                                                                                      |
| representive                                                   | 0    | 4       | 💚Positive                                                           | purposely misspelled based on research study; now brings back forms with the word Representative in the name.                                                                                      |
| travel                                                         | 3    | 3       | Neutral                                                            | No change                                                                                                                                                                                          |
| nurse                                                          | 2    | 5       | 💚Positive                                                           | Now includes "nursing"                                                                                                                                                                             |
| direct deposit                                                 | 9    | 9       | 💚Positive                                                           | full phrase matches at top                                                                                                                                                                         |
| release of information                                         | 170  | 40      | 💚 Positive, but not ideal; technical limitiation of PostGres feature | Expect forms with literal "release of information" in name to appear at top. Looks like "of" is being disregarded, even in the middle of a phrase. Other: Title of 10-259 needs to be fixed in CMS |
| travel pay                                                     | 12   | 12      | Neutral                                                            | No change                                                                                                                                                                                          |
| dbq                                                            | 0    | 0       | Neutral                                                            | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                               |
| aid and attendance                                             | 110  | 5       | 💚Positive                                                           | full phrase matches at top, not matching "and" as a single word drastically improves results                                                                                                       |
| va form 21-526                                                 | 1    | 1       | Neutral                                                            | Same result                                                                                                                                                                                        |
| certificate of eligibility                                     | 178  | 63      | 💚 Positive                                                           | full phrase matches at top, not matching "of" as a single word drastically improves results                                                                                                        |
| appeal                                                         | 6    | 6       | Neutral                                                            | No change                                                                                                                                                                                          |
| notification of personnel action                               | 170  | 4       | 💚 Positive                                                           | No exact match, but not matching "of" as a single word drastically improves results                                                                                                                |
| intent to file                                                 | 87   | 3       | 💚 Positive                                                           | full phrase match at top, not matching "to" as a single word drastically improves results                                                                                                          |
| burial                                                         | 4    | 4       | Neutral                                                            | No change                                                                                                                                                                                          |
| report of contact                                              | 195  | 44      | 💚 Positive                                                           | No exact match, not matching "of" as a single word drastically improves results                                                                                                                    |
| sf-50/ notification of personnel action                        | 170  | 4       | 💚 Positive                                                           | partial phrase matches at top, not matching "of" also drastically improves results                                                                                                                 |
| clothing allowance                                             | 5    | 5       | Neutral                                                                   | full phrase match at top                                                                                                                                                                           |
| ptsd                                                           | 2    | 2       | Neutral                                                            | No change                                                                                                                                                                                          |
| disability                                                     | 9    | 15      | 💚 Positive                                                        | Bonus - now includes "disabled"                                                                                                                                                                    |
| coe                                                            | 0    | 0       | Neutral                                                            | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                               |
| medical records                                                | 24   | 32      | 💚 Positive                                                        | Full phrase match at top; bonus - also includes "medical record" without the s                                                                                                                     |
| fmla                                                           | 0    | 0       | Neutral                                                            | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                               |
| power of attorney                                              | 162  | 2       | 💚 Positive                                                        | full phrase match at top                                                                                                                                                                           |
| travel reimbursement                                           | 8    | 9       | 💚 Positive                                                        | Matches with both words (even though not the the same order) at the top                                                                                                                            |
| pension                                                        | 29   | 29      | Neutral                                                            |                                                                                                                                                                                                    |
| va form 10-2850c application for associated health occupations | 249  | 120     | 🔴 Better, but not as expected                                     | Probably a limitation of Postgres feature.  There is a form number 10-2850c whose name is "Application for Associated Health Occupations", but it appears pretty deep in the results.              |
| authorization                                                  | 17   | 20      | 💚 Positive                                                        | bonus - also includes "authority"                                                                                                                                                                  |
| rfs                                                            | 0    | 0       | Neutral                                                            | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                               |
| notice of disagreement                                         | 162  | 12      | 💚 Positive                                                        | full phrase match at top                                                                                                                                                                           |
| request for service                                            | 240  | 87      | 💚 Positive                                                        | No exact match, but not matching "for" as a single word drastically improves results                                                                                                               |
| statement in support of claim                                  | 325  | 69      | 💚 Positive                                                        | full phrase match at top, not matching "in" and "of" also drastically improves results                                                                                                             |
| caregiver                                                      | 1    | 1       |  Neutral                                                         | No change                                                                                                                                                                                          |
| change of address                                              | 165  | 9       | 💚 Positive                                                        | full phrase match at top, not matching "of" also drastically improves results                                                                                                                      |
| burial benefits                                                | 26   | 29      | 💚 Positive                                                        | full phrase match at top                                                                                                                                                                           |
| application for associated health occupations                  | 249  | 120     | 💚 Positive                                                        | full phrase match at top, not matching "for" also drastically improves results                                                                                                                     |
| home loan                                                      | 50   | 50      | 💚 Positive                                                        | full phrase matches at top                                                                                                                                                                         |
| advance directive                                              | 3    | 7       | Neutral                                                            | also brings back matches for "direct"                                                                                                                                                              |
| award letter                                                   | 13   | 13      | Neutral                                                            | No exact match before or after                                                                                                                                                                     |
| supplemental claim                                             | 42   | 42      | 💚 Positive                                                        | full phrase matches at top                                                                                                                                                                         |
| chapter 35                                                     | 12   | 6       | 💚 Positive                                                        | Not returning every form with 35 in in the number                                                                                                                                                  |
| prior authorization                                            | 21   | 24      | 💚 Positive                                                        | Also returns matches for "authority"                                                                                                                                                               |
| statement of service                                           | 199  | 61      | 💚 Positive                                                        | No exact match, but not matching "of" as a single word drastically improves results                                                                                                                |
| application for nurses                                         | 233  | 90      | 💚 Positive                                                        | full phrase match at top, not matching "for" also drastically improves results                                                                                                                     |
| agent orange                                                   | 2    | 2       | Neutral                                                            | No exact match before or after                                                                                                                                                                     |
| nurse application                                              | 87   | 90      | 💚 Positive                                                        | Matches with both words (even though not the the same order) at the top                                                                                                                            |
| request for services                                           | 232  | 86      | 💚 Positive                                                        | No exact match, but not matching "for" as a single word drastically improves results                                                                                                               |
| name change                                                    | 15   | 9       | 💚 Positive                                                        | No longer including results with "change" found in the middle of the word "exchange".                                                                                                              |
| application for pension                                        | 255  | 107     | 💚 Positive                                                        | Matches with both words (even though not the the same order) at the top. Excluding "for" also improves results                                                                                     |
| third party                                                    | 4    | 8       | 💚 Positive                                                        | Also includes matches with "parties"                                                                                                                                                               |
| death benefits                                                 | 28   | 31      | 💚 Positive                                                        | Matches with both words (even though not the the same order) at the top. Also includes "benefit".                                                                                                  |

**Comment by MarciMcGuireGCIO** [comment]
@johnhashva you are correct,  we will default to closest match.
