### ISSUE TITLE
[Design] Notification Preferences: Create resources and support page to support new notification preferences feature

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#22887]
## Background
We need to create a static content page or a resources and support page to accompany the launch of the project.  For reference see this [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22741#issuecomment-815140756) on #22741 

## Tasks
- [x] Determine if we need a static content page and/or resources and support page in conjunction with content team
- [ ] Work with @ajakabcin to create implementation tickets or coordinate with VA Notify

**Comment by andaleliz** [comment]
Created #29557 to start this process

**Comment by andaleliz** [comment]
@ajakabcin Danielle and I didn't get a chance to discuss this during office hours this week, so I'm planning on discussing it next week (9/10). Moving this into our next sprint.

**Comment by andaleliz** [comment]
Hi @ajakabcin I met with Danielle this morning. There are a few other places where content addresses notifications, such as [this TeamSite page](https://www.va.gov/HEALTH/VEText_FAQs.asp).  Danielle is already working on bringing this in, along with some other pages.

Her team is going to evaluate all these sources and figure out how best to fit our new feature into this documentation, but it won't be immediate. She doesn't see this as urgent, and I agree.  

Since her team is doing the bulk of the work, it's tracked in #29557.  

I don't think there is much more for me to do here, in this particular ticket.  I added you as an assignee to their ticket so you can follow along and track for PM purposes.

I'm going to close this out, but if you need anything else please re-open.  Thanks!

**Comment by ajakabcin** [comment]
Thanks @andaleliz !
