### ISSUE TITLE
508-defect-1 ❗ Launchblocker - Debt Resolution, form certification not working

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#22892]
Label: 22685
# 508-defect-1 :exclamation: Launchblocker
     
   https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-1

Issue Title: 508 Defect 1 Launch Blocker! Debt Resolution, form certification not working properly.

Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

<h2>Details</h2>
When I check the box to certify and hit "submit" I get an error message "Must certify by checking box," and yet the form submits successfully. The same behavior occurs when I do not check the box.

**Comment by denisecoveyduc** [comment]
@joshkimux @AngelaFowler82  I am doing a little GH clean up and wondered if you could just take a quick look at this issue for me to validate that this is still a concern? Since (and before I joined the team) the FSR has gone through many changes and this may or may not have already been addressed. Thanks in advance for checking it out for us.

**Comment by AngelaFowler82** [comment]
This issue has been fixed. Closing at this time.
