### ISSUE TITLE
508 Defect 2: Feedback on error messages when reentering emails

### ISSUE THREAD

**Issue by AngelaFowler82** [department-of-veterans-affairs/va.gov-team#22907]
Label: 22685

    - [508-defect-2]

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2

Issue Title: 508 Defect 2: Feedback on error messages when reentering emails.

Point of Contact: Angela Fowler
**VFS Point of Contact:** _First name only: Angela

<h2>User Story or Problem Statement:</h2>
As a screen reader user, when filling out a form, I expect error messages to be clear and the point of the error easily accessed.
<h2>Details</h2>
When testing the reenter email address edit box in the Veteran Information section of the application for debt resolution I encountered the following issues:
<ul>
<li>When I do not reenter my email address and submit the form, JAWS doesn't automatically speak the error message. </li>
<li>When I deliberately type mismatching emails, JAWS does not speak the error, either when I tab away from the edit box or after I submit the form. </li>
<li>When the user begins typing an email, JAWS speaks an error message saying the email must be at least 6 characters long. If the user isn't done typing, this could cause them to think they're doing something wrong.</li>
</ul>
<h2>Acceptance Criteria</h2>
- [ ] JAWS speaks all error messages automatically and places focus at the point of the error.
- [ ] JAWS does not speak error messages prematurely, but when focus is moved away from the subject of the error or the user attempts to submit the form.

**Comment by denisecoveyduc** [comment]
@joshkimux @AngelaFowler82  I am doing a little GH clean up and wondered if you could just take a quick look at this issue for me to validate that this is still a concern? Since (and before I joined the team) the FSR has gone through many changes and this may or may not have already been addressed. Thanks in advance for checking it out for us.

**Comment by AngelaFowler82** [comment]
Users are no longer required to reenter email addresses. This certainly resolves the accessibility issues, but is inconsistent with other VA forms. Was this change made by accident or design?

**Comment by rileyorr** [comment]
Hi @AngelaFowler82 and @denisecoveyduc! We purposefully removed that input field. Previously, we received accessibility feedback to include a secondary email input. However, we were confused by that recommendation since we're pre-filling the form with the Veteran's email listed on their profile. We chatted about this pattern in the #design channel a few months ago; I'm happy to share that link with you both if you'd like! Takeaways from that discussion include:

**Josh**

> From what I know, making folks enter twice is an anti-pattern. It’s a poor replacement for email validation links because:
> - Folks who use switch devices or other slower input devices will face frustration in entering redundant information
> - It’s prone to errors for folks with cognitive or reading disabilities
 
**Ryan**

> i also think we should purge it, esp if it’s a blocker for some, and not a business requirement

Let me know if you have any questions or concerns!

**Comment by AngelaFowler82** [comment]
I can confirm, it is quite gone. :)
