### ISSUE TITLE
Audit flaky test spreadsheet

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#23004]
## Details 

[Original flaky test spreadsheet](https://docs.google.com/spreadsheets/d/1MmseC6sdnCfiwazVYDQIKwW9PgLdREo-_oDkhvsqSD4/edit#gid=0)

[Spreadsheet of tests that have failed in `master`](https://docs.google.com/spreadsheets/d/1FKn9UFrpDcVSjNTmZSLv1S-I82K0d6hgnAWvuKV5LjY/edit?usp=sharing)

* Visit each test in the spreadsheet of tests that have failed in `master`
* Identify anything that is obviously flaky, look for patterns
* Document findings
* Use the original flaky test spreadsheet as a supplement

## Acceptance Criteria 
- [ ] Findings have been documented

**Comment by k80bowman** [comment]
@Cgfor3 and I have been making our way through the updated spreadsheet, analyzing each of the test failures and looking for causes. We're compiling our observations and should be able to start making recommendations for how to fix each test soon.

**Comment by k80bowman** [comment]
@Cgfor3 and I met today and discussed our plan for finishing up this work. Our main concern is that there aren't good or easy fixes for a lot of these tests and it's taking a long time to go through each one to try and identify what's going on. We decided that, for this card, what we would like to do is put a limit on the time we're spending investigating each test. If there is an easy fix, we have created a [document](https://docs.google.com/document/d/1kDyFEgdMM0aS_EhMLkY0ipXnStpSeRW16xwWLZwCYMs/edit?usp=sharing) to capture that information so that we can pass it on to the teams responsible.

For the tests that don't have easy fixes, we're seeing some similar patterns that we feel might be better addressed by creating the unit testing best practices documentation and then passing that along with any additional helpful resources along to the teams responsible for fixing them. We'll want to discuss strategies for encouraging the teams to get these fixed later.

We also discussed some of these patterns and how we would like to handle them in the unit testing best practices documentation. We started a [working document](https://docs.google.com/document/d/1GpoaHx0qt-gRYJuZiuBHlNLV29yQyJ-tymgTMv9TPJA/edit?usp=sharing) to start capturing some of that as well.

**Comment by Cgfor3** [comment]
@k80bowman and I have finished putting our thoughts together in a summary [found here](https://docs.google.com/document/d/1bAnymtfwfp00OvcZlIcVAdSBzfkgYwXTL5NKXWoy4zM/edit?usp=sharing).

We encourage anyone on the team to review the document and provide feedback.

**Comment by Cgfor3** [comment]
After analyzing dozens of tests we were able to accomplish the following:
- Analyze and determine quick fixes for unresolved flaky tests
- Document common mistakes or problem areas and list helpful best practices to lessen and potentially eliminate them
- Identify next steps which include both updating [the existing best practices doc ](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test/) and communicating our findings and quick fixes to their respectful code owners.
- Determine need to clean up unit test output

Marking this as complete.
