### ISSUE TITLE
App Stores - User-facing Text

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#23045]
## Description
The Apple App Store & Google Play have a number of user-facing pieces of content we'll need to write and create:
- Promotional text
- Keywords
- Description

**VA Approver**
- Leanna (if Danielle can help edit, great, but not required)

**Needed by**
- 5/1
- Should be done before the review build is uploaded

**Acceptance Criteria**
- [x] Keywords determined
- [ ] A/B test set up if wanted
- [x] Written content approved by VA
- [x] Written content is input into app store consoles

## Reference Documentation
- List of requirements: https://docs.google.com/document/d/13t36JvEHkqqBOyh1JLxN2mh6jttCRqqtesjZicxSfT0/edit#
- References collected here: https://docs.google.com/spreadsheets/d/1XxhiKlLrUtoeitZyIT5d2O6vk-SoQFC8b2Tq2G-1R5E/edit?usp=drive_open&ouid=103668894305424319543
- VA text guidance:

## Status & Tasks

- 5/27: Andre is helping with this

- 5/24: Bridget met with Andre last Friday to get some help on this, will be ready to go by 6/1

- 5/14: Ad Hoc internal team can help with this, there are still a lot of outstanding comments in the doc. Jen and Cat to work on this

- 5/10: Ayush has reviewed, Leanna will review today and then it can be loaded to app store.  Could someone from Ad Hoc look at it (Andre)? And longer term, can we have a content person help with this?

- 5/3/21: Jen has a draft [here](https://docs.google.com/document/d/13t36JvEHkqqBOyh1JLxN2mh6jttCRqqtesjZicxSfT0/edit#), what should the approval process be for this?

**old**
- It would be helpful to have screenshots of apps in each store, identifying descriptive text and images (seeing the app previews in search, vs the product page)

**Comment by bridgethapner** [comment]
@melissa-lefevre  & Bridget are doing a light audit of other apps to see how they're handling descriptions. We will take a stab at filling out the Google Doc later this week or next.

**Comment by drjecker** [comment]
I've done some [draft text](https://docs.google.com/document/d/13t36JvEHkqqBOyh1JLxN2mh6jttCRqqtesjZicxSfT0/edit#heading=h.a0n5c2ln7tfh) in the GDoc that could probably use review before I touch it further. Specifically I've put in comments around Categories, and wrote draft copy for Description, Subtitle, Keywords, and Promotional Text. Flagging for @ayushchak, @ambikaroos, and @leanna-usds.

**Comment by ayushchak** [comment]
Great job, Jen - made some changes to meet app store requirements.

Overall strategic considerations for the team:

- Added a second column for language in later launches, that will change to become less tentative
- Per our general "soft launch" narrative, we want to emphasize the beta nature of this app as much as possible in the first launch. Apple and Google may not approve this language, but we should start with fairly tentative language and adjust as needed - we can also escalate with VA and Apple contacts as needed.
- Any components that positively impact SEO (keywords, mostly) have been shifted to the "next launch" column, since we would ideally like this app to be less discoverable right now.

**Comment by bridgethapner** [comment]
Update here - @drjecker is owning this and we are meeting with Andre this Friday 5/21 to share some context of our project and kick-off the process of Andre or someone on his team assisting us with a content review. We expect this to be wrapped up and ready to place into app stores by 6/1. 

A question that came up in a Google Play knowledge transfer meeting today: **Who is owning uploading final content/images to the app stores in their consoles?** I am happy to do it or if someone else can that's cool - @ashley-matthews, @drjecker, and I should all have the right permissions in both stores soon.

**Comment by bridgethapner** [comment]
In the 6/1 launch command center, we decided as a team to dial back the hedging in images and in the text due to concerns over approvals. The app store text that was submitted to app stores this morning are here: https://docs.google.com/document/d/1OIBK33fOyoWfojkOvwyKJC39szMxQwW9I69aKEnzBWk/edit?usp=sharing

**Comment by ambikaroos** [comment]
May add to GH in the future if we want to track changes over time, or automate anything.
