### ISSUE TITLE
User Survey Request for Find a Yellow Ribbon School

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#23208]
# Request the Feedback Survey

## What this form is for
Use this template to request adding the Medallia Survey to your product.

Read more about Medallia [link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) & how to request a survey [link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/contact-center/medallia/medallia-request-survey.md)

## Description
Find a Yellow Ribbon School is a tool that enables Veterans to search for largely private higher education institutions that offer education benefits not covered under the Post 9-11 GI Bill.

### Launch Date
April 2020

### Staging URLs
https://staging.va.gov/education/yellow-ribbon-participating-schools/

### Production URLs
https://www.va.gov/education/yellow-ribbon-participating-schools/

---

*Please leave the following blank*

---

## Acceptance Criteria
- [ ] URLs added & QA'd with the Medallia survey

**Comment by jwoodman5** [comment]
Hi @MarciMcGuireGCIO Great to see this come through as well. Can you please confirm you are wanting the _standard_ Medallia _feedback_ survey on just https://staging.va.gov/education/yellow-ribbon-participating-schools/ (no detail pages)? Double checking because there has been some confusion with other folks. Thank you!

**Comment by MarciMcGuireGCIO** [comment]
@jwoodman5 Thank you.  Yes, the standard survey should provide us with sufficient feedback.  If we find later we need something more customized, we'll circle back around. In this case, there are no detail pages; only search results that load into the same page.  cc @johnhashva

**Comment by jwoodman5** [comment]
@MarciMcGuireGCIO Okay, great. Thanks for the quick reply. We will get this in the queue and keep you updated on timing, which likely be early next week.

**Comment by jwoodman5** [comment]
@MarciMcGuireGCIO Okay, this survey is up and looking good. We will monitor submissions over the next week as part of our due diligence, but please check it out and let us know if you have any questions or concerns. Thank you!
cc @johnhashva

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @jwoodman5!  I probably should request Medallia access now.  LOL

**Comment by jwoodman5** [comment]
You're welcome, @MarciMcGuireGCIO. The Medallia instance is not setup for external users right now, but we are working on bringing the data into DOMO for reporting. In the meantime, I am happy to work with you on getting the insights you need.

**Comment by MarciMcGuireGCIO** [comment]
@jwoodman5 is there a template I should use to request insights from Medallia now that it's been in place for a few weeks?  Thanks!

**Comment by jwoodman5** [comment]
@MarciMcGuireGCIO We don't have a template as _hopefully_ we won't be doing this long. Please just email me your request (jason.woodman@oddball.io) and include the following:

- URL (where the survey lives - parent/main URL is enough)
- Date range

Unfortunately, the Medallia segmenting we have available turns out to not be very robust, so we can't use their charts. This means, we can only provide a raw .csv export.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @jwoodman5 !
