### ISSUE TITLE
[Design] Prototype - Preferred facility in VAOS

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#23259]
## Requirements

- A user is not required to set a preferred facility in their profile to use the application
- A user enrolled in healthcare at a facility may attempt to schedule an appointment

## Tasks
- [x] Prototype for user research

## Links to in-progress work
* User Research Prototype:
[Scenario 1](https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669675)
[Scenario 2](https://adhoc.invisionapp.com/console/share/B72LX6SPTP/633532185)
* [Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/research-plan.md)
* [Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/conversation-guide.md)

**Comment by outerpress** [comment]
@peggygannon here's the prototype for VAOS preferred facilities: https://adhoc.invisionapp.com/console/share/392JRZTTMD

I'd love to get your review of this ahead of testing. A couple of notes:

* We'll go over the context during the next sync. I hope to have the conversation guide draft ready by then, that'll help clarify the goals
* Not all screens need feedback - I'll note in here which ones specifically from VAOS, but you can skip all of the Profile-related screens as you already provided feedback on those
* Along with language feedback, if you have any questions we can uncover during research, I'd be interested in adding them to the research plan (which I'll post here once it's ready)

**Comment by Samara-Strauss** [comment]
**Research plan**

Moving feedback from Slack to here.

Can you please add the following people as observers for the research?
- AJ — ana@adhocteam.us
- Erik — erik@adhocteam.us
- Lihan — lihan@adhocteam.us

Also, under observers, you have Lauren listed but with Liz's email address, so I'm not sure what you intended to be there. Perhaps listing them both as observers?

**Convo guide**

- With regards to the profile, do they understand that unchecking a facility does *not* un-register them from that facility? Sorry if I missed this and this is already in the convo guide, but this issue came up in Liz's mini-usability test she did, and I want to make sure the updates she made to the prototype help clarify this. If no, we should also ask participants how we can make it clearer that they aren't un-registering themselves by unchecking a facility.

- Question: From your past research, how much do you already know about how people understand the difference between being registered at vs. receiving care at a facility? If we know a lot, I don't think we need to spend too much time on this, but if we don't know a lot or want additional clarification since this is a new study with new participants, I think we should assess this much earlier than the follow-up questions at the end. The language around being "registered" appears in the VAOS tool early in the prototype — this would be the perfect time to ask people what think this means and to have a discussion around that vs. where they receive care.

**Comment by peggygannon** [comment]
Hi, @outerpress do you have a list of screens you need me to review in VAOS? 

*Not all screens need feedback - I'll note in here which ones specifically from VAOS, but you can skip all of the Profile-related screens as you already provided feedback on those*

**Comment by outerpress** [comment]
@peggygannon sorry for the delay, I've been moving things around for the test and wanted it to be a little more solid before sending these along. 

**Opt out flow**
Tests a workflow where facilities are modified primarily in the Profile section - Veterans "opt-out" of facilities where they no longer receive care.

Facilities page with no preferences set
(Note: we're not testing the new dropdown as part of this, but I can share the context of that if it's helpful)
https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/629320983

Facilities page with  preferences set + a recently visited facility
 https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669689

--------

**Opt-in flow**
Veterans can "save" facilities they want to revisit from VAOS, which updates the Profile

All facilities - if no prefs have been set
https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669709

Save facility page
If they choose a facility that hasn't been manually set in Profile
https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669741

-----

**Same across both flows**
Facilities page with preferences set BUT preferred facility doesn't offer online scheduling for TOC
https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669698

Facilities page that follows above if "I need a different facility" is selected - facilities that offer online scheduling for that TOC
https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669700

Call to schedule page - if we can't show any facilities that offer online scheduling
https://adhoc.invisionapp.com/console/share/BX2JRZTUR2/621669702

**Comment by outerpress** [comment]
@Samara-Strauss thanks for the notes! You'll see the changes noted below updated in GH by tomorrow late morning (PT)

> Can you please add the following people as observers for the research?

Done!

> Also, under observers, you have Lauren listed but with Liz's email address, so I'm not sure what you intended to be there. 

Thanks for the typo catch, fixed!

> With regards to the profile, do they understand that unchecking a facility does not un-register them from that facility? 

We get into that [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/conversation-guide.md#task-3---manage-facilities-in-profile) and [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/may-2021-facilities-personalization-research/conversation-guide.md#task-4---manage-facilities-in-profile) - and after running through it today we do think the "what do you think this change did" question could use a follow-up.

> If no, we should also ask participants how we can make it clearer that they aren't un-registering themselves by unchecking a facility.

We're aiming to get that answer through the above two questions along with the wrap at the end. I'm trying to avoid priming them with an idea of what registration is, so that they'll tell us in their own words what they know about it. 

> Question: From your past research, how much do you already know about how people understand the difference between being registered at vs. receiving care at a facility? 

I'm not clear on whether there's a common understanding among Veterans on that difference. That's definitely a key area we're digging in to.

> if we don't know a lot or want additional clarification since this is a new study with new participants, I think we should assess this much earlier than the follow-up questions at the end. 

I'll look at pulling it forward in the test (as a potential follow up to "what do you think this change did) but want to hear if they use that language at all or what they think the process is broadly before drilling in on the registration question.

**Comment by Samara-Strauss** [comment]
Thanks for all of this, @outerpress! These clarifications are really helpful. Looking forward to getting to sit in on some sessions!

**Comment by Samara-Strauss** [comment]
Can we close this since testing has started?

**Comment by andaleliz** [comment]
Side note - are there any existing tickets I can tag along w/ for tracking the effort to run the sessions, and synthesis?

**Comment by outerpress** [comment]
Thanks all, closing this one. I'll ping y'all on any new tickets we create for this work
