### ISSUE TITLE
Document Tugboat requirements

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23266]
## Issue Description
This issue will collect the limitations/requirements observed in Tugboat instances used for previewing/testing content for VAMC and Vet Center FE implementations. 

Documenting these items will allow
1. appropriate expectations about what to expect from the environment
2. identification of showstoppers/significant blockers which could be addressed

----

### Issue: CORS errors from API calls
**Situation:** Tugboat URLs are dynamically generated and CORS isn't able to whitelist them all. 
**Impact:** Content/functionality dependent on API calls does not render/is not available and cannot be tested in a Tugboat environment (ie: static maps)

---

### Issue: Plugins for links to add target=blank
**Situation:** Liquid template filter (update-external-links.js”) converts some links to target=_blank -> may be failing based on domain
**Impact:** Expected functionality of any external links opening in a new window cannot be tested. 

Screenshots from [Erie health care Policies page](https://www.va.gov/erie-health-care/policies/)
<details>
<summary> In Production </summary>

![image](https://user-images.githubusercontent.com/55411834/114788990-a7e16880-9d3f-11eb-8dbf-0f672778d595.png)

</details>

<details>
<summary> In Tugboat </summary>

![image](https://user-images.githubusercontent.com/55411834/114789004-aca61c80-9d3f-11eb-9a15-d9003fa9ed72.png)

</details>

**Comment by mpelzsherman** [comment]
Since this issue was created, I've learned that for domains ending in "va.gov", the `update-external-links.js` plugin adds `target=blank` only to links that are found in a whitelist. That list currently includes the following domains:

```
  'myhealth.va.gov',
  'ebenefits.va.gov',
  'www.accesstocare.va.gov',
  'www.gibill.va.gov/wave',
  'www.blogs.va.gov',
  'www.data.va.gov',
  'mobile.va.gov',
  'www.accesstocare.va.gov',
  'www.oit.va.gov'
```

The link I found on the Policies page points to "ethics.va.gov". Since `ethics.va.gov` is not in the whitelist, it does not get the `target=blank` added.

HOWEVER: I've added ethics.va.gov to the whitelist, and re-built the tugboat instance from my branch (`vamc_hardened_policies_page`), and `target=blank `is still not getting added. So it appears that the plugin isn't being run in the tugboat environment. This raises concerns about what other parts of the production build process are being skipped in the tugboat builds.
