### ISSUE TITLE
[PM] My VA redesign - Hold go/no-go for QA

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23306]
## Background
We need to confirm that we're ready to send the feature forward for formal QA

## Tasks
- [x] Ensure feature is done
- [x] Review the feature and functionality

**Comment by Samara-Strauss** [comment]
@ajakabcin, so things that will be helpful for you:

- [This is the go/no-go template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/go-no-go-meeting-template.md), but it is really geared toward launch and not applicable to figuring out if we are ready for QA. I think you can customize it to figure what questions we need to ask to make sure we are ready for QA. It'll likely be very short. 
- Since it's a go/no-go for QA, you can save a copy of this in the [My VA 2.0 QA folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/2.0-redesign/qa).

Let me know what questions you have!

**Comment by ajakabcin** [comment]
We ran through a [readiness checklist today](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/qa/QA%20Readiness%20Checklist.md) after standup and we're in good shape to continue with our QA request submitted for next sprint.
