### ISSUE TITLE
[FSR] Unbold labels in VA benefit cards

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#23316]
## Issue Description
Unbold ‘Total amount:’ and ‘Amount received last month:’ in the VA benefit cards:
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/dcc4501b-e5f9-408c-b6ac-0dede0c49e34)
[UXpin link](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/136159512/specification/sitemap?mode=i)

---
## Tasks
- [ ] Unbold ‘Total amount:’ and ‘Amount received last month:’ in the VA benefit cards

## Acceptance Criteria
- [ ] THING SUCCESSFULLY UNBOLDED

**Comment by LinnJS** [comment]
Looks like `total amount` was removed due to the BE not supporting this value currently, just wanted to document that will will look like the picture below till the BE supports totals.

Reached out to @craigwheeler for confirmation.

![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/c70641a6-fdb4-49f9-a771-999fab8f6b96)
