### ISSUE TITLE
[Design] Notification Preferences - Begin research plan

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23321]
## Background
In order to validate our assumptions and defined business goals we need to put the feature in front of users. We need to design a research plan for this.

## Tasks
Begin documenting a research plan
- [x] Research method (moderated user interviews)
- [x] Participants & Recruitment
- [x] Timeframe

## Acceptance Criteria
- [x] Research Plan has been started for later review

**Comment by andaleliz** [comment]
[Initial doc with research question](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/discovery-and-research/notifications-research-plan.md)s captured added to our folder.

**Comment by Samara-Strauss** [comment]
I think I may have been thinking of things from more of a planning perspective. I thought that we might have frontend able to start work before we actually had definition on actual notifications and groups, in which case we might as well have done some testing in staging. However, it appears we're gonna have notifications and groups defined maybe even before we can start frontend discovery, so I think moving forward with a UX Pin prototype is fine. Thank you for checking in about this!

**Comment by andaleliz** [comment]
Wonderful, glad to hear that! I'll proceed w/ the prototype route as I work on my plan and guide.

**Comment by andaleliz** [comment]
@Samara-Strauss and @ajakabcin I've got a great start on this - super excited to do some research on this.  I think it'll be too much to try to test mobile AND desktop for this study.  I have more questions about desktop than mobile at this point - mainly because of our new `edit` button treatment and using that to edit a group vs one thing at a time.  

What are your thoughts on testing w/ a desktop prototype for this first round, and then doing another study on mobile once we have our MVP on staging?  I have a hypothesis that people will be more likely to do task on mobile than desktop, and it would be wonderful to let them use the mobile environment in a more natural way than they would with a prototype.

**Comment by andaleliz** [comment]
Created #24166 to extend this work in sprint 48.

**Comment by Samara-Strauss** [comment]
> What are your thoughts on testing w/ a desktop prototype for this first round, and then doing another study on mobile once we have our MVP on staging? I have a hypothesis that people will be more likely to do task on mobile than desktop, and it would be wonderful to let them use the mobile environment in a more natural way than they would with a prototype.

This sounds good to me. You should test in whatever view you feel will help you answer the questions you have. If that's desktop, then go for it. 

> Created #24166 to extend this work in sprint 48.

Great, thank you!

**Comment by andaleliz** [comment]
Closing this since all the docs have begun  🎉
