### ISSUE TITLE
Analytics Implementation for [Authenticated Experience - My VA redesign]

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23336]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

For more information, please check out the [Google Tag Manager resources](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/google-analytics/readme.md).

An example of a completed request template can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7199). A fully completed issue can help speed up the implementation process.
</div>
</details>

## Description
- Is this request for Google Analytics implementation or QA?
    Google Analytics

- Who is this request for?
    - DEPO Product Lead: @Samara-Strauss 
    - Product Manager: @ajakabcin 
    - Designer: @tressaellen 
    - Frontend engineer: @erikphansen
    - Backend engineer: @lihanli  
   
 _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    Authenticated Experience, [My VA redesign product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md)
  
    
- Provide the Domain where Google Analytics needs to be implemented
    va.gov/my-va

- Identify if PII is passed in URL or title tag
    No
  
- Please provide any upcoming deadlines or important milestones
   Targeting phased launch rollout late Q2 early Q3 (June/July 2021)
    

**-  Interactions to Track**
Background here: [Analytics to track as part of initial My VA 2.0 redesign](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/analytics/analytics-to-track.md)
    1. How many logged in users visit My VA
    2. Top My VA interactions (clicks)
    3. Top searches initiated from My VA
    4. Average Foresee score (note: we understand we can't get this in GA, so this would be if we eventually had a Domo dashboard)
    5. Tracking on My VA link in unauth nav

Additional documentation around OKRs and KPIs here: [Product outline: My VA > Measuring Success](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/README.md#measuring-success)
    

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - [My VA test cases and users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_
    - [My VA test cases and users](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva.md)

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by Samara-Strauss** [comment]
I see QA needs to be complete for this morning forward. That'll be happening early in May.

Otherwise, let us know if a regroup would be helpful. I imagine it might be given that there are a few states of the new My VA and we can guide you to what those are on staging. Let us know if that would be helpful!

Also, I had a questions around how we'll track interactions on the new page given that a lot of them are the same as the interactions on the current page, the design is just different. Will there be different tracking for links on the new My VA than the current version of the page? Or will the tracking for actions on the 1.0 and 2.0 version be the same?

Example: On the current page, there's a link to view all claims. There's also a CTA to view all claims on the new version of My VA. Are those going to show as the same metric in GA, or will that be two different metrics once the new version of the page launches?

**Comment by jonwehausen** [comment]
Thanks for your notes here @Samara-Strauss & @ajakabcin! We appreciate you submitting this request well in advance and already [documenting your KPIS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/README.md#measuring-success) and/or thinking through the areas you're looking to track. 

@bsmartin-ep or @laurensimpson14 would one of you mind scoping this work? I feel that may be best here with the phased roll-out not beginning until June/July.

**Comment by laurensimpson14** [comment]
After looking at the Analytics to track as part of initial My VA 2.0 redesign, below are my notes: 

> Updated tracking for all links on the page
>- We should talk with the analytics team on how we want to do this. A lot of interactions are the same, but the design is different. What does this mean for tracking? Should there be some way to track the difference between My VA 1.0 and My VA 2.0 links?

Most of the tracking will carry over with the new design. The following items are automatically tracking in the 2.0 design: 
- All header links (My VA, My Health, VA Benefits and Health Care, etc.) 
- Menu expand for “What other benefits does VA offer?”
- All menu options within the “What other benefits does VA offer?” expanded menu
- Continue your application
- All footer menu options

The following links are not tracking: 
- Go to your profile
- Manage all your claims and appeals
- Schedule your appointment
- You have _ unread messages
- Refill and track your prescriptions
- Get your lab and test results
- Get your VA medical records
- How to file a VA disability claim
- Learn how to apply for VA education benefits

We would need to update the tracking to begin capturing the above links. 

As for tracking the difference between My VA 1.0 and 2.0 links - I think that would best be done by just being aware of when the 2.0 links go live and knowing that anything pre-launch date is 1.0, and anything post-launch date is 2.0. If we change the tracking/naming schema I’m concerned that you’d lose historical data & comparisons in your KPI dashboard. 

> Add tracking to My VA link in the unauth nav

We are currently tracking clicks to the My VA link in the top navigation bar, and yes - there would be a way to see the funnel of people who click that link and make it to the My VA dashboard. 

You are correct that we won’t need to do anything to continue tracking how many loggedin users visit My VA, search from that page, and Foresee survey scores. 

Looking at the above list I think that's a good plan for what we should begin implementing and then QA before launch. Is there anything that I'm missing? Or anything that you'd like to add?

**Comment by Samara-Strauss** [comment]
> Most of the tracking will carry over with the new design. The following items are automatically tracking in the 2.0 design:
> 
> - All header links (My VA, My Health, VA Benefits and Health Care, etc.)
> - Menu expand for “What other benefits does VA offer?”
> - All menu options within the “What other benefits does VA offer?” expanded menu
> - Continue your application
> - All footer menu options

The menu for “What other benefits does VA offer?” does not currently exist in the 1.0 design. How is there already tracking for this and the options within the expanded menu?

Also, what about links into individual claims? People can click into individual claims now from the My VA dashboard, and they will still have that option in the 2.0 design, but I don't see that on this list.

Finally, there is a link to "View all claims and appeals" on the 1.0 design, and we are carrying that over to the 2.0 design. However, I see "Manage all your claims and appeals" in the list below as something that would need tracking and doesn't have it already. Can you clarify whether that would need different tracking from what we have now or not?

> The following links are not tracking:
> 
> - Go to your profile
> - Manage all your claims and appeals
> - Schedule your appointment
> - You have _ unread messages
> - Refill and track your prescriptions
> - Get your lab and test results
> - Get your VA medical records
> - How to file a VA disability claim
> - Learn how to apply for VA education benefits

There are items missing from this list:

- The link to view all disability ratings, shown in the screenshot below:

<img width="1279" alt="Screen Shot 2021-05-06 at 10 25 22 AM" src="https://user-images.githubusercontent.com/34068740/117315271-87e02900-ae55-11eb-8cf1-b7ebbfcd6ee3.png">

- The link to Learn how to apply for VA health care, shown in the screenshot below (note: this only shows for users who do not have and have never applied for health care):

<img width="933" alt="Screen Shot 2021-05-06 at 10 27 25 AM" src="https://user-images.githubusercontent.com/34068740/117315814-089f2500-ae56-11eb-89ca-b4401144c24b.png">

- Also, the "You have X unread messages" link will change copy and say "Send a secure message to your health care team" if someone has no unread messages. Idk if this affects the tracking, but I wanted to call it out in case it did. The link ultimately goes to the same place, so I imagine it wouldn't affect tracking.

<img width="933" alt="Screen Shot 2021-05-06 at 10 27 25 AM" src="https://user-images.githubusercontent.com/34068740/117318048-12c22300-ae58-11eb-9e20-1988eceb8cf2.png">

> We are currently tracking clicks to the My VA link in the top navigation bar, and yes - there would be a way to see the funnel of people who click that link and make it to the My VA dashboard.

Got it. So it doesn't matter that this link is now available in an unauth state? I want to make sure it's clear who is clicking that from an unauth state and making it through the sign in process vs. who clicks the link from an auth state.

Otherwise, everything made sense. Please let me know if you'd like a walk through of the design given that it has a few different states and, understandably, not everything will be crystal clear just from looking at staging or the InVision prototype.

**Comment by Samara-Strauss** [comment]
Hi all, I want to check in and get a status update on this work. Barring unforeseen issues, we're about a month out from beginning the phased  launch for My VA. We can't do that, however, without making sure all analytics/tagging are correctly in place. 

Given that, do you have a rough estimate on when your team thinks you realistically might be able to get to this ticket? I completely understand you all are swamped right now, and what I'm looking for is what you can realistically accommodate without taking on too much. If we don't think you'll have time for this work in the next few weeks, that's fine, but just let us know so we can adjust our expectations around launch. Since I'm going on maternity leave within the next few weeks, it's super important that we have and idea of how we should plan so I can set up @ajakabcin  for success while I'm out.

Thanks, all! We really appreciate your hard work in supporting all the teams across VSA.

**Comment by joanneesteban** [comment]
Hi @Samara-Strauss, thanks for the ping and apologies for the late reply as I was out of office last week. 

@laurensimpson14 will be working on this, and can get started next sprint (this Thursday).

Also, congratulations!!!

**Comment by Samara-Strauss** [comment]
> @laurensimpson14 will be working on this, and can get started next sprint (this Thursday).

Great, thank you so much for letting me know! 

> Also, congratulations!!!

Thank you!

**Comment by laurensimpson14** [comment]
> The menu for “What other benefits does VA offer?” does not currently exist in the 1.0 design. How is there already tracking for this and the options within the expanded menu?

There is already tracking for this since it's using "additional info" in the Data Layer (DL). This causes it to be tracked automatically as part of our standardized tracking plan. The click text will be captured so you'll be able to distinguish it from other buttons that use that DL component. 

> Also, what about links into individual claims? People can click into individual claims now from the My VA dashboard, and they will still have that option in the 2.0 design, but I don't see that on this list.

I don't believe this is tracking currently. Please have your developers implement the `Button` component found in this documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md

> Finally, there is a link to "View all claims and appeals" on the 1.0 design, and we are carrying that over to the 2.0 design. However, I see "Manage all your claims and appeals" in the list below as something that would need tracking and doesn't have it already. Can you clarify whether that would need different tracking from what we have now or not?

We would need to implement additional tracking for "Manage all your claims and appeals". Are there any other links on this page that take them to the same place/url that this button leads? 

Based on the missing items you gave me I updated the list. Current list of links that need tracking: 
- Go to your profile
- Manage all your claims and appeals
- Schedule your appointment
- You have _ unread messages (text changes to "Send a secure message to your health care team" if there are 0 unread messages, but still links to same place)
- Refill and track your prescriptions
- Get your lab and test results
- Get your VA medical records
- How to file a VA disability claim
- Learn how to apply for VA education benefits
- Link to view all disability ratings (ex. "40% service connected")
- Learn how to apply for VA health care (only shown for users who do not have and have never applied for health care)

Regarding the two states of "schedule and view your appointments", unauth v auth, and just to make sure we've got everything, I think it would be good to set up a meeting with @bsmartin-ep and me. Would you have 30 minutes Tuesday (5/25) between 1:00 - 2:30 pm EDT or Wednesday (5/26) between 10:00 - 11:30 am EDT? 

After the meeting I can give you a better time estimate on how long getting this tracking implemented will take… Also, congrats on the new baby!

**Comment by Samara-Strauss** [comment]
> I don't believe this is tracking currently. Please have your developers implement the Button component found in this documentation: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md

We are tracking clicks into individual claims unless I am misunderstanding what I am seeing in the current analytics. Let me know if this data isn't displaying what I think it's displaying:

<img width="1280" alt="Screen Shot 2021-05-24 at 4 20 53 PM" src="https://user-images.githubusercontent.com/34068740/119403427-50260d80-bcac-11eb-8c1f-09e0d7b9099c.png">

> We would need to implement additional tracking for "Manage all your claims and appeals". Are there any other links on this page that take them to the same place/url that this button leads?

Just to confirm: this is regardless of the fact that we send people to this URL via My VA 1.0 now (see screenshot above)? If so, sounds good, and let's add tracking for that. And no, no other links on the page go to the same place.

> Based on the missing items you gave me I updated the list. Current list of links that need tracking:

Add tracking for clicking into an individual claim into this list, and we should be good.

> Regarding the two states of "schedule and view your appointments", unauth v auth, and just to make sure we've got everything, I think it would be good to set up a meeting with @bsmartin-ep and me. Would you have 30 minutes Tuesday (5/25) between 1:00 - 2:30 pm EDT or Wednesday (5/26) between 10:00 - 11:30 am EDT?

It's not unauth vs. auth, it's all auth but two different states for when someone has an upcoming appointment and when someone does not. But it all goes to the same URL. If we need to meet, I can do Tuesday at 1:00.

> After the meeting I can give you a better time estimate on how long getting this tracking implemented will take… Also, congrats on the new baby!

Sounds good, and thank you!

**Comment by laurensimpson14** [comment]
> We are tracking clicks into individual claims unless I am misunderstanding what I am seeing in the current analytics. Let me know if this data isn't displaying what I think it's displaying:

You are correct! That is being tracked. Looking at the way it's tracked that should carry over to the new 2.0.

> Just to confirm: this is regardless of the fact that we send people to this URL via My VA 1.0 now (see screenshot above)? If so, sounds good, and let's add tracking for that. And no, no other links on the page go to the same place.

Correct, regardless of the link to this URL in 1.0. 

Updated list: 
- Go to your profile
- Manage all your claims and appeals
- Schedule your appointment
- You have _ unread messages (text changes to "Send a secure message to your health care team" if there are 0 unread messages, but still links to same place)
- Refill and track your prescriptions
- Get your lab and test results
- Get your VA medical records
- How to file a VA disability claim
- Learn how to apply for VA education benefits
- Link to view all disability ratings (ex. "40% service connected")
- Learn how to apply for VA health care (only shown for users who do not have and have never applied for health care)
- Tracking for clicking into an individual claim (should carry over from 1.0, but double check - will look like `Dashboard - Navigation - View Button -View Claim`)

I just sent you a calendar invite for Tuesday!

**Comment by Samara-Strauss** [comment]
All of this sounds great! See you tomorrow!

**Comment by Samara-Strauss** [comment]
Can you also add @ajakabcin to that call?

**Comment by Samara-Strauss** [comment]
Hi all, [here is most of the staging user info you'll need](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-passwords.md). The Cerner user listed will see the Cerner alert I mentioned in the health care section, and the LOA1 user will see the prompt to verify their identity. Otherwise, below is who can see what:

|User| What links they can see|
|-----|------------------------|
|226| This user can see most things, so you can use it for most of your testing, including the disability rating, Go to your profile, Manage all your claims and appeals, Schedule and view your appointments, You have X unread messages, Refill and track your prescriptions, Get your lab and test results, Get your VA medical records, All the links under "What benefits does the VA offer?", Learn how to file a VA disability claim, and Learn how to apply for VA education benefits|
|15 | View details for an individual claim. **Note**: We may need to add a claim for this user if the current one has expired|
|[judy.morrison@id.me](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-vaos.md)| Shows what it looks like when someone has an appointment|
|272| Can see the "Learn how to apply for VA health care" under Apply for benefits > Benefits you might be interested in|

**Comment by joanneesteban** [comment]
@Samara-Strauss thanks for checking in! Brian will work on this, and we should be getting you the tracking beforehand.

**Comment by Samara-Strauss** [comment]
Great! If I happen to be out by then, please work with @ajakabcin and the team to confirm everything is tracking accordingly before launch!

**Comment by bsmartin-ep** [comment]
Apologies @Samara-Strauss.  A bit of debate over keeping the existing dashboard events vs something more generic.

We decided to keep the dashboard events as-is and use the existing the `nav-linkslist` event for the menu items.

Let me know if you have any questions.

cc @ajakabcin 

<table>
  <tr>
    <th>Interaction</th>
    <th>Data Layer</th>
    <th>Notes</th>
  </tr>

  <tr>
    <td>Go to your profile</td>
    <td>
      <pre lang="js">
{    
event: 'dashboard-navigation',   
'dashboard-action': 'view-link',  
'dashboard-product': 'view-your-profile',
}</pre
      >
    </td>
    <td>This exists in the current My Va, but is a view-button.</td>
  </tr>
  <tr>
    <td>Manage all your claims and appeals</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Check your claim or appeal status',        
'links-list-section-header': 'Claims &amp; appeals',
}
</pre
      >
    </td>
    <td>This is the "Manage all your claims and appeals" link, correct?</td>
  </tr>
  <tr>
    <td>Schedule your appointment</td>
    <td>
      <pre lang="js">
{                
event: 'nav-linkslist',        
'links-list-header': 'Schedule and view your appointments',        
'links-list-section-header': 'Health care',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
      Schedule and manage your appointments (the "We can’t access your
      appointment information" version)
    </td>
    <td>
      This is already tracking with nav-alert-box-link-click. Just wanted to
      note this.
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
      You have _ unread messages (text changes to "Send a secure message to your
      health care team" if there are 0 unread messages, but still links to same
      place)
    </td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'You have n unread messages',        
'links-list-section-header': 'Health care',
}
</pre
      >
    </td>
    <td>
      I would use n vs the actual number to reduce the cadinality on these
      events.
    </td>
  </tr>
  <tr>
    <td>Refill and track your prescriptions</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Refill and track your prescriptions',        
'links-list-section-header': 'Health care',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Get your lab and test results</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Get your lab and test results',        
'links-list-section-header': 'Health care',
}
</pre
      >
    </td>
  </tr>
  <tr>
    <td>Get your VA medical records</td>
    <td>
      <pre lang="js">
{        
event: 'nav-linkslist',        
'links-list-header': 'Get your VA medical records',        
'links-list-section-header': 'Health care',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>How to file a VA disability claim</td>
    <td>
      <pre lang="js">
 {    
event: 'dashboard-navigation',    
'dashboard-action': 'view-link',    
'dashboard-product': 'recommendations-disability-file-claim',
}
</pre>
    </td>
    <td></td>
  </tr>
  <tr>
    <td>Learn how to apply for VA education benefits</td>
    <td>
      <pre lang="js">
 { 
event: 'dashboard-navigation',
'dashboard-action': 'view-link', 
'dashboard-product': 'recommendations-education-apply-now',
}
</pre>
    </td>
    <td></td>
  </tr>
  <tr>
    <td>Link to view all disability ratings (ex. "40% service connected")</td>
    <td>
      You can infer this by looking at pageview for
      "/disability/view-disability-rating/rating" with a Previous Page Path of
      "/my-va/".

But let me know if you want to throw this in a      dashboard-navigation event.
    </td>
    <td>&nbsp;</td>
  </tr>

  <tr>
    <td>
      Learn how to apply for VA health care (only shown for users who do not
      have and have never applied for health care)
    </td>
    <td>
      <pre lang="js">
{    
event: 'dashboard-navigation',    
'dashboard-action': 'view-link',    
'dashboard-product': 'recommendations-health-care-apply-now',
}</pre
      >
    </td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>
      Tracking for clicking into an individual claim (should carry over from
      1.0, but double check - will look like Dashboard - Navigation - View
      Button -View Claim)
    </td>
    <td>I see this in the dataLayer still, so I think we're good.</td>
    <td></td>
  </tr>
</table>

**Comment by Samara-Strauss** [comment]
Thanks for this, @bsmartin-ep.

- What are next steps from here? It is unclear to me what you need, if anything, from our team.

> This is the "Manage all your claims and appeals" link, correct?

Yes.

> I would use n vs the actual number to reduce the cadinality on these events.

What does this mean?

**Comment by bsmartin-ep** [comment]
@Samara-Strauss -

> What are next steps from here?

For these currently untracked links, your developers would need to ensure they are sending in the appropriate events to the dataLayer.

-----------

> I would use n vs the actual number to reduce the cadinality on these events.
>  >   What does this mean?

This is the event your developers would need to send in to track these...

```js
{        
event: 'nav-linkslist',        
'links-list-header': 'You have n unread messages',        
'links-list-section-header': 'Health care',
}
```

One option is to send in the actual link text, with the actual message count.  So...

```js
'links-list-header': 'You have 3 unread messages',  
```

or

```js
'links-list-header': 'You have 5 unread messages',  
```

..but this will increase how many different Event Actions we have for this event.  If the number of messages is a useful metric for you, then it's probably worth the increase in cardinality.  But otherwise, I would stick with one click text label  (with _n_) for all versions...

```js  
'links-list-header': 'You have n unread messages',  
```

**Comment by Samara-Strauss** [comment]
> For these currently untracked links, your developers would need to ensure they are sending in the appropriate events to the dataLayer.

Got it. @ajakabcin can you create a ticket for this for sprint 50 (next sprint) and make sure that Brian's documentation above is part of that ticket?

**Comment by ajakabcin** [comment]
Created #25984 - will follow up with Brian and Erik to make sure I've captured what needs to happen correctly.

**Comment by erikphansen** [comment]
@bsmartin-ep [the table you posted above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23336#issuecomment-859260656) is super helpful. Thank you!

I'm about to post a PR to implement all of the new tracking. Should be on staging tomorrow. Will let you know.

**Comment by erikphansen** [comment]
@bsmartin-ep PR merged so this will be ready to validate on staging soon.

**Comment by ajakabcin** [comment]
@laurensimpson14 and/or Jenna Ouellet could you review this for Erik?

https://github.com/department-of-veterans-affairs/vets-website/pull/17627

**Comment by laurensimpson14** [comment]
@erikphansen and @ajakabcin Everything is tracking and coming through correctly! Please see my QA screenshots and notes below: 

| Interaction | Screenshot | Status |
| :------- | :-------: | :-------:|
|Go to your profile| ![image](https://user-images.githubusercontent.com/80417436/122413984-cd177080-cf54-11eb-8849-fc71976f4d7d.png) | 🟢 Tracking Correctly|
|Manage all your claims and appeals|![image](https://user-images.githubusercontent.com/80417436/122417217-562fa700-cf57-11eb-9e14-d2fe32b3e8b1.png) |🟢 Tracking Correctly|
| Schedule your appointment | ![image](https://user-images.githubusercontent.com/80417436/122414268-00f29600-cf55-11eb-81ed-7a9b850f30f0.png) | 🟢 Tracking Correctly|
|Schedule and manage your appointments (the "We can’t access your appointment information" version)| ![image](https://user-images.githubusercontent.com/80417436/122421375-52515400-cf5a-11eb-8764-6fbaa63cf0c3.png) | 🟢 Tracking Correctly|
|You have _ unread messages| ![image](https://user-images.githubusercontent.com/80417436/122414403-1ebffb00-cf55-11eb-92b0-eea4cbe25286.png)| 🟢 Tracking Correctly|
| Refill and track your prescriptions| ![image](https://user-images.githubusercontent.com/80417436/122414519-339c8e80-cf55-11eb-9f7b-24b820e9d6cf.png)| 🟢 Tracking Correctly|
|Get your lab and test results| ![image](https://user-images.githubusercontent.com/80417436/122414706-562ea780-cf55-11eb-8dcc-1c05712f4cb2.png)| 🟢 Tracking Correctly|
|Get your VA medical records| ![image](https://user-images.githubusercontent.com/80417436/122414900-79f1ed80-cf55-11eb-8ed9-8e0536f500e4.png)| 🟢 Tracking Correctly|
|How to file a VA disability claim| ![image](https://user-images.githubusercontent.com/80417436/122415918-4cf20a80-cf56-11eb-867c-b178fbc85c2c.png)| 🟢 Tracking Correctly|
|Learn how to apply for VA education benefits| ![image](https://user-images.githubusercontent.com/80417436/122416019-62ffcb00-cf56-11eb-8165-0d7d688b5345.png) |🟢 Tracking Correctly|
|Learn how to apply for VA health care | ![image](https://user-images.githubusercontent.com/80417436/122417721-b292c680-cf57-11eb-9714-84f0a711eb00.png)|🟢 Tracking Correctly|
|Tracking for clicking into an individual claim| ![image](https://user-images.githubusercontent.com/80417436/122419941-4add7b00-cf59-11eb-8555-1659d99b7e34.png) | 🟢 Tracking Correctly|

I believe that is everything that you need from the Analytics team Anastasia, but please let me know if there's anything that I'm missing!

**Comment by erikphansen** [comment]
Thanks @laurensimpson14 !
