### ISSUE TITLE
Create E2E tests for form in Cypress 

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#23345]
Create e2e tests to include 508 test case coverage. 

Def. of done: All tests are integrated and passing

**Comment by mdewey** [comment]
Create the 7 tests in cypres

**Comment by mdewey** [comment]
I have updated our form tester e2e test. The good news is that it works, the bad news is that it fails accessibility checks. 

The accessibility check that is failing is on the list loop on the review page. This was first encountered and documented with ticket #14175. 

The continued dilemma is that I can work with the platform to fix the current list loop, but supposedly a new list loop is coming. 

My questions
- Will this be a release blocker? I don't think it's a severity 0 or 1 defect, but I am not the accessibility or release expert 😅. THis also means that one of our e2e is running and it's the full happy test so it has some weight to it. 
- Is there any status up on the list loop work? Is it time to just do it ourselves and make the current one more accessible?

@leahkeeler  and @kristenmcconnell, thoughts?

**Comment by kristenmcconnell** [comment]
I think this would be a good question for Josh Kim or Trevor Pierce. We made the decision a while ago to stick with the default component, since there was so much discussion on list loops. The current discussion is to break list loops into asking one question at a time (when appropriate). It could be a page where the only question displayed is "Do you have a question to ask your provider?" Yes/No (then write in the question), then on a new page asking again if they have another question for their provider. We didn't test this though, which is what was mentioned as the preferred approach in the last discussion that I was a part of. I would hope that this is something that we could revisit when we add in the Health Records (medications, allergies, and immunizations) review to the questionnaire.

**Comment by leahkeeler** [comment]
@mdewey Review page is failing accessibility (and usability for that matter) it should not be a release blocker. Call it out in the staging ticket as a known issue - caregivers just ran into same with staging. The bigger question - overall review page-- debt team plans to address it after release of fsr with forms team .... it is affecting all the teams now

**Comment by mdewey** [comment]
To circle back, pulling out the list loop will allow our e2e tests to pass with a problem
