### ISSUE TITLE
Design Feedback - Design intent -Decisions Tools - Sitewide Search UI Consistency

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#23458]
## VFS acceptance criteria
- [x] Let VSP know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- I reviewed the answers Crystabel provided on the epic and agree with them. We discussed the right rail and you have the option to keep or remove it. If analytics show the links are not being used and you have time you can feel free to remove it.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Replace green [action links](https://design.va.gov/components/action-links) with blue action links. There should only be 1 green action link per page.

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @allison0034!  @callen2563 and @mgleo please let me know when you've had a chance to review and we'll discuss next steps.

**Comment by callen2563** [comment]
@allison0034 @MarciMcGuireGCIO I have made the design edits requested for FAF and R+S. Let me know if there is any thing else or if I missed any thing. 

[Mobile updates](https://vsateams.invisionapp.com/overview/UI-Search-Consistency---mobile-cknr2uisl2tl001ymf60mfq36/screens?sortBy=1&sortOrder=1&viewLayout=2)

[Desktop updates](https://vsateams.invisionapp.com/overview/UI-Search-Consistency---desktop-cknr2uisl2tl101ymmt48cx3z/screens?sortBy=1&sortOrder=1&viewLayout=2)

**Comment by mgleo** [comment]
+ Updates have been made to Global Search on Invision.

**Comment by rtwell** [comment]
If I recall correctly, we decided in the design intent meeting the scope of this work is focused specifically on the search results themselves. Given that, I would update these mockups to reflect content beginning with “Search results for…” and beneath it. 

1. **Semantics vs visual hierarchy** — We should indicate which heading level is which and note any changes to the visual hierarchy (for example, if an H3 looks like an H4). In Sketch, we have symbols to indicate headings (Insert > Symbols > VA.gov Pattern Library > Markup tag). Use these symbols to indicate how the page should be structured and note any deviations. In Sketch for Teams or Zeplin, developers cannot see the names of text styles, they can only see properties (e.g. font-size). Markup tags allow the entire team to align on how the page is structured, and is particularly important for screen readers and assistive technology. If you’re not sure what tags to use, please work with Josh or reach out to the design channel for help and we’ll gladly work with you. Here are a few bits that would benefit from this:
   1. “Our top recommendations for you” on global search
   2. “Form 10-0491A” and similar on Form search and Resources and Support
   3. Because each search results page contain different levels of headings, how do we want to address the headings in the search results themselves?

2. **Spacing** — Ensure the spacing between rules, typography, and other elements is consistent. In the VA design system, we should be using [spacing units](https://design.va.gov/design/spacing-units) to indicate how much white space is present between elements, which are multiples (or divisions) of 8.
   1. The space between “Showing X – X of X results…” and the first rule following it should be consistent
   2. Spacing between search results themselves (e.g. Change your address on file with VA) and the first element that follows 
   3. Spacing between each search result group

3. **Rules** 
   1. Global search — it looks like rules are reserved for top recommendations, but we use them to divide all search results. Is this intended?
   2. Find a form does not have a top-most rule
   3. Are we using a rule at the end of the results? Global search does, the other two do not.

4. **Color**
   1. Rule thickness and color should be consistent
   2. Hover color should be `gray-dark / #323a45`
   3. Green typography on global search should be `green / #2e8540` 
   4. At first glance, the green type on Global search strikes me as interactive. Do we want to explore changing it or testing to see if it's a factor for users?

5. **Typography**
   1. We should not alter the default line height of a given heading style. I recommend updating the Sketch files to more accurately reflect how this will look in browser by assigning styles using the VA Pattern Library. 
   2. "Showing 1–10 of 999 results…" should use an en dash (`option`  `-` on a Mac), not a hyphen

6. **Grid** — I seem to recall some questions regarding the width of the main column of content. The grid rendered in-browser and the grid in Sketch do not (and cannot) match perfectly. We should be indicating the width of elements in terms of columns, not pixels. You can read about how columns work in the design system [grid documentation](https://design.va.gov/layout/flexbox-grid). If you have any questions about how this works, feel free to reach out in Slack

**Comment by mgleo** [comment]
Updates have been made to Global Search on Invision.

**Comment by callen2563** [comment]
Updates have been made to FAF and R+S on InVision

[Mobile updates](https://vsateams.invisionapp.com/console/share/8Y10IE2JN2J4)

[Desktop updates](https://vsateams.invisionapp.com/console/share/SD10IE31CENR)

**Comment by MarciMcGuireGCIO** [comment]
@rtwell, @mnorthuis @joshkimux @1Copenut - specific recommendations have been incorporated into the designs.  Please let us know if you have additional feedback.

As for the yet-to-be decided items, I can schedule a working session with you all, @callen2563 and @mgleo when Megan returns next week?  Based on my review, the following still needs to be decided on:

-  Horizontal rule placement
- Treatment of headings in search results
- Form number in front of the link (or not)
- Reducing amount of content above search fields

Thanks!

**Comment by rtwell** [comment]
@MarciMcGuireGCIO sounds good—please include me in the working session. I'll do my best to attend.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @rtwell.  Will do!

**Comment by MarciMcGuireGCIO** [comment]
Scheduled a working session for 4 PM ET to discuss 


- Horizontal rule placement
- Treatment of headings in search results
- Form number in front of the link (or not)
- Reducing amount of content above search fields
- When/how we should address the search field itself:
    - Having a magnifying glass on button (global search, R&S) vs. not (Find VA Form)
    - Inconsistent spacing between text field & button
    - R&S button that stays inactive until three characters are entered, others are always active
