### ISSUE TITLE
Health Questionnaire 

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#23465]

**Comment by miabecker** [comment]
@Kennon-git here is our own issue that we tracked for this since the intake came in through VANotify. Maybe we should get together to discuss what an intake / tracking process might look like for collaborative efforts such as this one might be cc @bevnobev @shanemelliott @pcshah1026 

https://app.zenhub.com/workspaces/vanotify-business-intake-board-606cc5c49392c900162c3971/board?repos=133843125,261511794&showPRs=false

**Comment by Kennon-git** [comment]
confirmed with ming - MVP will be sms, email will follow. expect high level estimate after roadmap meeting.
