### ISSUE TITLE
0994: Update Direct Deposit Widget

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#23485]
As a developer, I need to update the direct deposit section of the application so that it uses the latest DEPO design pattern and applicants have a consistent experience while completing the application.

## Assumptions:
1. This work is completed behind a prod flag.
2. DEPO is updating the direct deposit widget to remove "(No more than 17 digits)" from bank account number; that may result in an inconsistency with the prototype.

## Acceptance Criteria:
1. The sentence in the note:

    > Updates here will not change accounts on file for your VA health benefits.

    is replaced with

    > Updates here won’t change accounts on file for your VA health benefits.

2. If the applicant has bank account pre-fill information:
    a. The content `This is the bank account information we have on file for you. We’ll pay your housing stipend to this account.` is not displayed.
    b. The content `This is the bank account information we have on file for you. We’ll send your housing payment to this account.` is displayed within the "Payment Information" box.
    c. The `Update Account` label is replaced with `Update account information`.

3. If the applicant does not have bank account pre-fill information:
    a.  The content `We don't have your bank information on file.  Please provide your direct deposit information below.  We'll pay your housing stipend to this account.` is not displayed.
    b. The content `We make payments only through direct deposit, also called electronic funds transfer (EFT). Please provide your direct deposit information below. We’ll send your housing payment to this account.` is displayed within the "Update bank account" box.
    c. "Account type" is required
    d. A sample check is displayed in the "Update bank account" box.
    e. The "Bank account number" is required
    f. The "Bank routing number" is required
    g. The "Bank routing number" is displayed before the "Bank account number"
    h. The "Bank routing number" label is replaced with "Bank’s 9 digit routing number".

4. The `What if I don’t have a bank account?` content is replaced with:

    > The [Veterans Benefits Banking Program (VBBP)](https://veteransbenefitsbanking.org/) provides a list of Veteran-friendly banks and credit unions. They’ll work with you to set up an account, or help you qualify for an account, so you can use direct deposit. To get started, call one of the participating banks or credit unions listed on the VBBP website. Be sure to mention the Veterans Benefits Banking Program.
    > 
    > Note: The Department of the Treasury requires us to make electronic payments. If you don’t want to use direct deposit, you’ll need to call the Department of the Treasury at [888-224-2950](url). Ask to talk with a representative who handles waiver requests. They can answer any questions or concerns you may have.

## Supporting Artifacts:
1. [Prototype](https://bahdigital.invisionapp.com/d/main#/console/14222606/296058972/preview)
2. [Content Doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/258aa04d798dbfd09db4005e64bf0a54c5f71654/products/education-careers/application/vettec-0994/design/0994-content.md)
3. [VA.gov Direct Deposit Pattern](https://design.va.gov/patterns/form-templates#direct-deposit)
4. 
<img width="525" alt="dd_prefill" src="https://user-images.githubusercontent.com/48260534/115411475-8100b780-a1c1-11eb-849c-a2fcd6e53471.png">
<img width="529" alt="dd_no_prefill" src="https://user-images.githubusercontent.com/48260534/115414732-49473f00-a1c4-11eb-90a2-907ff9d621fd.png">

**Comment by SebVortex** [comment]
@dneel-bah @mrblanco1 
I know this has been here a while but looking at this a bit more in depth and wondering if this fix is even applicable anymore.

It's been assumed since the beginning that this work was completed already and has been linked to another issue but there never was a PR associated with this or the other issue.

This refers to a form but direct deposit information for a user is updated on the user's profile under "Direct Deposit Information". And going to using a test user on staging.va.gov/change-direct-deposit just refers you back to change the information on your profile page.

I've done done some work on changes that match the criteria of this ticket, but I think that, either I and others have been looking in the wrong area and need to know where this change actually lies, or this form doesn't exist anymore and hasn't for a while. I think the reason this hasn't been realized sooner is due to issues with logging in locally in the past and difficulty finding appropriate test users to investigate the issue.

Without more information I think this ticket should probably just be closed.

**Comment by SebVortex** [comment]
> @dneel-bah @mrblanco1 I know this has been here a while but looking at this a bit more in depth and wondering if this fix is even applicable anymore.
> 
> It's been assumed since the beginning that this work was completed already and has been linked to another issue but there never was a PR associated with this or the other issue.
> 
> This refers to a form but direct deposit information for a user is updated on the user's profile under "Direct Deposit Information". And going to using a test user on staging.va.gov/change-direct-deposit just refers you back to change the information on your profile page.
> 
> I've done done some work on changes that match the criteria of this ticket, but I think that, either I and others have been looking in the wrong area and need to know where this change actually lies, or this form doesn't exist anymore and hasn't for a while. I think the reason this hasn't been realized sooner is due to issues with logging in locally in the past and difficulty finding appropriate test users to investigate the issue.
> 
> Without more information I think this ticket should probably just be closed.

**Correction:**
The form being referred to here is not to update direct deposit, it's to enter information with for a VET-TEC application.
This was confused with changing direct deposit in general. Thanks to @hallihocine, for clearing out this confusion.

**Comment by SebVortex** [comment]
90% of the way through this ticket. However, having difficulties using the schema.
Opened a support ticket with design after looking through the documentation (https://dsva.slack.com/archives/CBU0KDSB1/p1645028528355829) and trying to avoid a schemaBypass, though that might be the best option if help from design doesn't prevail.
A schemaBypass would be require recreating the page and integrating it with the rest of the schema driven form.

Work is being done on branch `23485-direct-deposit-widget`

**Comment by SebVortex** [comment]
After an ongoing conversation with the design team and an assessment of work vs value that could be brought to veterans with these changes, the recommendations for this issue are going to be taken as far as the schemaForm system allows. Members of the design team were reached out too but a conclusive solution addressing this specific issue was not met.

Slack thread: https://dsva.slack.com/archives/CBU0KDSB1/p1645028528355829
Support ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/37080

All attributes but 3d are to be implemented.
(schemaForms doesn't support adding a description field between input elements).

**Comment by SebVortex** [comment]
For issue 3 c, e, & f

This bit was a pernicious to fix given that while the method ultimately used here was a convention use elsewhere in schemaForms, employing it here caused tests to fail. Originally thought to maybe be a discrepancy in local and staging environments, with the help from from design, @k80bowman, it was found that there is a side effect to making 0994 bank fields required: The form is unable to submit without error when bank fields are required. Whether there is prefill Information or not. This issue requires investigation but is out of the scope of this ticket and holding up progress given the value provided to users relative to look and research put into this ticket.

It is highly recommended that this schema side effect be investigated as its own issue.

**Comment by hallihocine** [comment]
Ticket has been validated in staging: Direct Deposit Widget is now updated to DEPO recommendation and design pattern. All changes have been implemented except for AC 3c e & f, due to the schema forms side effect. 

1. If the applicant does not have bank account pre-fill information: 
<img width="453" alt="Screen Shot 2022-03-08 at 10 41 34 AM" src="https://user-images.githubusercontent.com/86266024/157336832-e49bb2de-1535-43ab-8bd7-4c9655ec5732.png">
2. If the applicant has bank account pre-fill information:
<img width="564" alt="Screen Shot 2022-03-08 at 5 32 18 PM" src="https://user-images.githubusercontent.com/86266024/157337080-956f4b40-9919-44a5-b9e0-5f41bb82ac4d.png">
3. The What if I don’t have a bank account? content is updated to:
<img width="518" alt="Screen Shot 2022-03-08 at 5 04 26 PM" src="https://user-images.githubusercontent.com/86266024/157337293-5a8e4efe-65cd-47ff-9eac-08ab5c326ad7.png">

**Comment by hallihocine** [comment]
- Test Run in Test Rail: 
https://dsvavsp.testrail.io/index.php?/runs/view/3039&group_by=cases:section_id&group_order=asc&group_id=3710
- Test Steps: 
[0994-Update Direct Deposit Widget.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8210097/0994-Update.Direct.Deposit.Widget.xlsx)

**Comment by mrblanco1** [comment]
QA and UAT passed on 3/10/2022.
