### ISSUE TITLE
Convo guide for accessibility research 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23493]
## User Story

- As a Veteran using assistive tech and a mobile device to search on Facility Locator, I want the experience to be consistent with accessibility best practices.
- As the Facilities team, we want the Facility Locator to be easy to use with assistive technology so the search experience is an equitable experience for all Veterans.

## Background
Please see background in [RESEARCH] Begin research planning for Mobile search expectations (assistive tech) (v1) #18685

## Goals of research

- Establish foundational knowledge for the search experience for Veterans using assistive tech (with a mobile perspective)
- Validate recent keyboard navigation and voiceover changes
- Identify pain points for Veterans using assistive tech to search for facilities on a mobile device
- Understand how Veterans expectations for search results differ for mobile vs desktop users
- Understand how industry standards impact Veteran expectations for the Facility Locator search experience

## Tasks
- []  Create conversation guide to support research plan created in #18685
 
## Acceptance Criteria
[ ] Conversation guide is accepted

**Comment by lildziner** [comment]
@AngelaFowler82 @joshkimux as a follow up to accessibility office hours this morning, I wanted to give us a paper trail to refer to. 

Thank you for your time and input on my email response to Dr. Vernon Humphrey for him to circulate [study details](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/screenreader-usability-study/call-for-participants.md) to members of the National Association of Blind Veterans.

Also, here is a [draft of the conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/screenreader-usability-study/research-plan.md) in the works for your review, when it's convenient for you. 

Lastly, we will need to collaborate on this [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/screenreader-usability-study/research-plan.md). To get something started, I came up with dates in isolation and don't yet factor in your schedules. Feel free to leave your comments in this issue or let me know what's best for you both. I can also schedule some time for us next week to over some of these details.

**Comment by joshkimux** [comment]
@lildziner Hi Leyda, I have some suggestions along with some edited changes in the conversation guide.

**Suggested:**
- Instead of just an hour, we should let them know that this entire session should take an hour and a half, but we’re available to be here longer should the need for flexibility arise. Setting up a screen share on a mobile device, having folks navigate through pages, etc will likely take much longer than a sighted user study.
- Update intro on service history to something more general and introductory. e.g. “How would you introduce yourself to a friend of a friend? [Answer] How about what it’s like being a Veteran?” 
- Do we want to include “You decide to start your search on the internet” there? Would we be interested in if they’d even go about using the internet to begin with to search?
- Scenario set up should be updated to be a real page, not a prototype

**Changed:**
- Added intro for accessibility specialist, so they know they have someone they can ask for help in regards to AT
- Removed “In this study” in favor of just “Today,” in the intro
- Added in right to leave the session
- Changed “visually impaired” to “low vision”
- Added preference for communication into iPhone zoom script, split up the script, and reworded some items to be more fitting with VoiceOver

**Comment by mmiddaugh** [comment]
The working version of the convo guide is found [here](https://docs.google.com/document/d/1KKLmlwHv7M-tOd05kPhWC7jPOMNomH3iWc43zIPnakg/edit?usp=sharing) 

This work will continue in #24148
