### ISSUE TITLE
IA Request [Public Website, Campaign Landing Page / Trust (VEO)]

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#23519]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kick-off ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to [Campaign Landing Page Production MVP] - VA Trust #23304 (CLP Request Ticket)

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
Campaign Landing Page (CLP) per request.

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
Truth

**URL(s)** - What are your suggested URLs and why? www.va.gov/trust (Stakeholder Requested) or e.g. should it be va.gov/campaign-trust and instead set va.gov/trust as a redirect.

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
Possibly e.g. should it be va.gov/campaign-trust and instead set va.gov/trust as a redirect.

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?
None
## Definition of Done
- [X] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by johnhashva** [comment]
@brianalloyd this looks good -- I'm putting a note into Tim to see if he has metadata in mind.  Will add to the ticket if he provides some input for that.

**Comment by mnorthuis** [comment]
Questions:
 - I am seeing both "truth" and "trust" used above.  It looks like per the CLP issue #23304 that va.gov/trust has been requested, but  want to clarify what the verbiage around this campaign looks like. 
- Do we have any draft content for this campaign, or any idea of how they are referring to this when they communicate out links? 

Thoughts:
- Using a single word for a url slug is generally avoided unless the word is super specific or the content is intended to be super broad.  "Truth" or "Trust" by itselft, at the root level of the site could be interpreted as a number of things for our audience - is it related to privacy, security, equality, safety, etc.  I would recommend  campaigns be titled very specifically in order to be viewed separately from formal communication such as policies or press releases. 
- I would like to know more about what this content is focused on:  Veterans trusting VA benefits?  Veterans trusting VA services?  Veterans trusting in VA in general?  Is it more than just Veterans, but also caregivers and family?    
- If this is related to this PR, https://www.va.gov/opa/pressrel/pressrelease.cfm?id=5464, we could look at something like `www.va.gov/veterans-trust-va/` or `www.va.gov/trust-in-va/`.  I realize that "va" is somewhat redundant in this case, but it also gives the url a bit more of the story.

**Comment by brianalloyd** [comment]
@mnorthuis its definitely "Trust" sorry for the confusion, I was moving fast yesterday and might have arbitrarily inserted "Truth" into the equation, since I've updated tickets and details to reflect current reality.  Really like the URL recommendations, I'm certain @johnhashva will chime in on feedback in regards to desired direction.

**Comment by johnhashva** [comment]
@mnorthuis thanks for helping us get to the root of what's needed here for the URL.  Some quick responses in-line with you Q's:

**Comment by johnhashva** [comment]
@mnorthuis thanks for helping us get to the root of what's needed here for the URL. Some quick responses in-line with you Q's:   

- Re: What is Campaign all about -- you guessed right, VA would like to bring more awareness to its Trust score.   Front and center of this CLP will be info graphics like this one:

<img width="165" alt="VA Trust Score" src="https://user-images.githubusercontent.com/63107147/115725873-36fa0c00-a350-11eb-8f15-a785dea0721b.png">

            
Here is some additional context via the FAQs section in the CLP being developed:     
**Why does VA measure trust?**
Asking Veterans, their families, caregivers, and survivors directly about their experiences with VA empowers VA's public servants to provide better access to needed resources.
**How does VA measure trust?**
VA measures customer experience through the ease, effectiveness, and empathy we demonstrate in the delivery of our care, benefits, and services.

**WHY THIS MATTERS**
The more than 6M digital surveys returned by Veterans are enabling enhancements to the way VA provides care, benefits, and services.
Improving access to VA’s resources with equity starts with listening to the voice of the Veteran community and then designing tailored customer experiences to meet their individual needs.

@mnorthuis your recommendation and reasoning for a more specific URL --- www.va.gov/veterans-trust-va/ -- makes a lot of sense.  Any concerns if VEO wanted to set up va.gov/trust as a redirect as well?

**Comment by mnorthuis** [comment]
@johnhashva thank you for clarifying the above info, that is super helpful!   Will this CLP be the page that contains all the info on the veteran trust data, or will it link out to the data somewhere else?  In other words, is this truly a campaign page that will be used to temporarily promote communication of trust data, or is this really intended to be a permanent page?

In regards to creating `/trust` as a redirect...that still establishes a high level, broad term as the url for this content  - in other words, the same rules apply for a "vanity url".    If we use `/trust` as a redirect/vanity url, we are still communicating out a very broad term that may be misinterpreted by users.  Also, in our vanity URL guidelines, we state that we do not create vanity URLs for pages that are already at the top 2 levels, or already have relatively short URLs. 

I have some thoughts on options, but clarification on whether this is really permanent info or just a campaign will be helpful.   If this is permanent info, we should treat it that way (despite that its using a campaign template), and find the appropriate home within the site for it first, then figure out if a vanity URL is also needed.

**Comment by johnhashva** [comment]
@mnorthuis (with @brianalloyd) -- after conferring with VEO, some more guidance to help us finalize a decision re: URL and where this CLP might sit w/in VA.gov

-  For context: the new SECVA plans to use VA.gov/Trust in remarks about transparency and our commitment to earning back trust. It’s a common WH theme with the new admin.  (the focal point will be the updated Trust Score-- see attached PDF. Each quarter Veterans Signals (VSignals), VA’s customer experience feedback program, randomly surveys approximately more than 200,000 Veterans with recent interactions VA-wide with claims, appeals, health care, memorials and other services to rate their overall trust in VA.)
- This campaign has no end-date at this time; the Trust VA theme is likely to be a focal point for the next four years of the new SECVA administration.  (Note: Perhaps we transition from CLP to a permanent page when we modernize About VA content?)
- For site positioning in the current IA, this probably fits best under About VA in the mega-nav -- perhaps between About VA and History of VA -- however, that breaks our current precedence and there is not modern About page (as of yet)
- We could go with trust-in-VA URL as long as there’s a va.gov/Trust redirect to it


[VATrustReport_1.1-3.30_2021_v04.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6365412/VATrustReport_1.1-3.30_2021_v04.pdf)

@mnorthuis as a next step, shall we schedule a convo on this?

**Comment by mnorthuis** [comment]
@johnhashva Ok, thank you for following with that info, super helpful!  Here are my thoughts, and if you want to meet to finalize or discuss, just let me know.   If everything sounds good to you, then I'll go ahead and start formalizing the IA work. 

**Regarding the core IA of this page**... I'm going to treat this like it is a permanent part of our site- similar to the performance dashboard, it is data and information that will be continually updated - despite that it is using the CLP template. 
- This means that there will be a permanent home with an accurately formatted URL per our standards, and entry point links - typical short term campaigns would not necessarily have these since they are essentially stand-alone marketing entities.
- I think the "About VA" menu is a valid option for an entry point, but would like to look through this a bit more - I think the footer is also an option alongside the performance dashboard.
- I will go ahead write up full IA recommendations based on this, along with the URL, if we are in agreement

**Regarding the campaign side of this page**...If they want to use a shortened/vanity URL for the purposes of "marketing" and communication, that is not something that we (OCTO/VSP) are technically in the business of (I am definitely not an expert on managing marketing campaigns and associated URLs/landing pages, nor do we have any standards for this), but we can technically set it up for them - they would likely go around us to create it anyway if we didn't do it. So, given that, I'd like to offer some advice/recommendations on it:
  - URL paths (the section after the va.gov domain) are case-sensitive, so if they communicate out a capital "T" in trust, we will need to also establish the lower case version of that URL, because people do not type capitals.  For example www.va.gov/health-care/ is a valid URL, but www.va.gov/Health-Care/ is not. 
  - I personally would suggest they use the "Trust VA" language in the vanity URL if that's how they are leading their campaign.  If those are the words they will be saying and putting in communications, then mimicking that in the URL can be helpful:  www.va.gov/TrustVA   (again, we would also set up the lower case of this `/trustva` as well, but using the casing when the dashes aren't being used, makes for a more readable URL for communication purposes).

**Comment by johnhashva** [comment]
@mnorthuis all sounds good here.  I will go back to the VEO lead on this one -- Tim Hudak -- and provide your smart guidance about www.va.gov/TrustVA as the more optimal shortened/vanity URL.   Will post final word on that here.

**Comment by johnhashva** [comment]
@mnorthuis update from VEO stakeholder/lead for this CLP:   They have already committed internally with SECVA to **va.gov/Trust** as the promoted vanity/url.  (plus, they feel va.gov/TrustVA is somewhat redundant) VEO is fine with /veteran-trust-va -- or similar -- as the actual URL.

**Comment by mnorthuis** [comment]
Thanks for the update @johnhashva.  Here is the documented IA info, please let me know if you have any questions. 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/clp-truth.md

A few notes:
- Links added to global navigation elements should be reviewed and approved by appropriate OCTO-DE stakeholders prior to implementation to make sure everyone agrees and is on the same page. 
- You can submit the redirect request whenever you are ready to for the implementation of the vanity URL(s). 
- Feel free to close this issue if you have everything that you need.

**Comment by brianalloyd** [comment]
Think we've achieved everything we need in support of this ticket, closing out in support.
