### ISSUE TITLE
Backend: Update 10-10CG PDF generation for new form

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23528]
Open a PR to replace the PDF being generated with the new form

**Comment by ala-yna** [comment]
Moving to Sprint 47 since we haven't received the new PDF yet

**Comment by kevinmirc** [comment]
This work is blocked because the data types in the new PDF have changed.

The signature fields in the PDF are now "Signature" type fields, when before they were "Text" type fields. Our code cannot write text into the signature because it's not "Text".

We understand why this change was made and request from the Caregiver Program a version of the PDF where signature fields are all "Text" type, for the purpose of signing them programmatically.

**Comment by kevinmirc** [comment]
Increased the scope to `5` pts. The original `3` pt size was assuming none of the data fields would change in the new PDF. The new PDF had multiple field changes: 
- All (4) signature fields were no longer text fields
- All (6) button fields on the new PDF had different fields references
- All (6) button fields had different True, False values 

The new scope size accounts for troubleshooting, adding "Text" data type on signature fields, and updating changes data references for "Button" type fields.
