### ISSUE TITLE
Error messaging work-around Front End work

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#2352]
## Background 
Better error messaging is needed to prompt users to input or correct their phone number or mailing address information when trying to complete their direct deposit update. 

## User Story
As a veteran, I want to be prompted to fix/correct my submitted information on the form when attempting to go through the user flow to update my direct deposit information

## Goal 
Display appropriate user err messaging for phone number, mailing address or both when the system cannot validate the information. 

## Definition of Done
- [ ] FE work has been completed and tested and validated
- [ ] Content for error messages have been review and suggested changes have been given "if needed"
- [ ] Content has been approved
- [ ] Ticket can be closed

**Comment by Justin-Pickett** [comment]
@erikphansen can you upload screen shots of the proposed error messaging solutions to this ticket. Thank you.

**Comment by erikphansen** [comment]
![image](https://user-images.githubusercontent.com/20728956/66589026-839d3e00-eb42-11e9-9dc6-a53f4c27d049.png)

The error messages will live in the alert box at the top of the modal if there is an error when updating DD info. As @Justin-Pickett said, we'll need better copy (something not written by me) for the following error messages:
- they need to update/fix their mailing address
- they need to update/fix their phone number
- they need to update/fix both

**Comment by erikphansen** [comment]
@Justin-Pickett is this a ticket for the dev work and a content writer will update this with the appropriate error messages? Will there be another ticket to handle showing a helpful error message when we get the `payment.restriction.indicators.present` error code?

**Comment by Justin-Pickett** [comment]
@erikphansen yes this ticket is for the dev work and for Peggy to do the content review as well. I will open a separate ticket for the error handling for the payment.restriction.indicators.present erro code.

**Comment by erikphansen** [comment]
@Justin-Pickett @peggygannon These are the error messages we'll need better copy for. Note that we don't need to handle the case where both their phone numbers and address are throwing errors because we don't know what sort of error message we'd get in that case. Chances are even if there are multiple problems with their contact info, we'll only get one error from the server.

`Update your home and mailing addresses in your profile and try again.`
`Update your work phone number in your profile and try again.`
`Update your home phone number in your profile and try again.`

**Comment by erikphansen** [comment]
There's another error message we are seeing in the Sentry logs that is not given any special handling: `cnp.payment.routing.number.fraud.message`. Is there some better messaging that we can put in place for this error?

**Comment by peggygannon** [comment]
@Justin-Pickett @erikphansen Hello, please see suggested error messages below. Please let me know if these will work? 


**We couldn't update your information**
We're sorry. We couldn't update your address. Please go back to [your profile](link) and try again. 

**We couldn't update your information**
We're sorry. We couldn't update your home phone number. Please go back to [your profile](link) and try again. 

**We couldn't update your information**
We're sorry. We couldn't update your work phone number. Please go back to [your profile](link) and try again. 

**We couldn't update your information**
We're sorry. We couldn't update your address and phone number. Please go back to [your profile](link) and try again.

**Comment by erikphansen** [comment]
@peggygannon sorry we didn't do the best job communicating the need. In these scenarios the user is trying to update their direct deposit/bank info. But the server rejects the change because some of their required contact info is missing or invalid. So the error should be more along the lines of "we couldn't update your direct deposit bank information because your phone number is missing..."

**Comment by peggygannon** [comment]
@Justin-Pickett @erikphansen OK, updated messages below. Please let me know if these will work? 


**We couldn't update your bank information**
We're sorry. We couldn't update your direct deposit bank information because your phone number is missing or invalid. Please go back to [your profile](link) and fill in this required information.  

**We couldn't update your bank information**
We're sorry. We couldn't update your direct deposit bank information because your address is missing or invalid. Please go back to [your profile](link) and fill in this required information.  

**We couldn't update your bank information**
We're sorry. We couldn't update your direct deposit bank information because your address and phone number are missing or invalid. Please go back to [your profile](link) and fill in this required information. 


Could I get some more information on what might cause these errors below? It this a case where a user has missing or invalid info on  their routing number or bank info? 
- `payment.restriction.indicators.present`
- `cnp.payment.routing.number.fraud.message`

**Comment by erikphansen** [comment]
Here are some examples of the new errors in place:

<img width="429" alt="Screen Shot 2019-10-16 at 10 35 29 AM" src="https://user-images.githubusercontent.com/20728956/66943916-f4d86780-f000-11e9-9bed-cb5a3aa6eaa9.png">
<img width="442" alt="Screen Shot 2019-10-16 at 10 34 46 AM" src="https://user-images.githubusercontent.com/20728956/66943917-f4d86780-f000-11e9-9f6e-c91897d831a6.png">

I tweaked it a bit since we differentiate between home and work phone numbers.

**Comment by peggygannon** [comment]
thanks, @erikphansen the updates look good. Let me know when you have more information about the other two error codes.

**Comment by Samara-Strauss** [comment]
@peggygannon — can you update the copy for the following error? Danielle wrote this copy, so 99% of it shouldn't need to be changed, but Lisa/Justin pointed out that this copy is slightly confusing because it says the account is locked when in fact someone's entire account is not locked, just the direct deposit functionality and the ability to edit and update direct deposit information.

### Design

<img width="271" alt="Direct deposit error message" src="https://user-images.githubusercontent.com/34068740/67035758-427bcf80-f0e8-11e9-964e-86308e9209f1.png">

### Existing copy

*(Samara's note: The line that needs changing is "You can’t change your direct deposit information right now because we’ve locked your account." to something like "You can’t change your direct deposit information right now because we’ve locked your ability to do so.")* 

We’re sorry. You can’t change your direct deposit information right now because we’ve locked your account. We do this to protect your bank account information and prevent fraud when we think there may be a security issue.

If you have any questions, please call us at 800-827-1000 (TTY: 800-829-4833). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET

**Comment by peggygannon** [comment]
@Samara-Strauss  @erikphansen Please see my suggested edit below: 

One question for you: Is there a set period of time that this function typically stays locked (24-48 hours?) 
If so I'd like to suggest that we add a CTA for resolution  (for example, "Please try again in 24 hours.... ") depending on how long this feature stays locked. Let me know your thoughts. 


**We couldn’t update your bank information**
We’re sorry. You can’t change your direct deposit information right now because we’ve locked the ability to edit this information. We do this to protect your bank account information and prevent fraud when we think there may be a security issue.
If you have any questions, please call us at 800-827-1000 (TTY: 800-829-4833). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by erikphansen** [comment]
as far as I know the locking is permanent until they call and get it unlocked

**Comment by peggygannon** [comment]
ok, thank you. If that's the case, then I'd like to suggest we add that to the message, like below:

**We couldn’t update your bank information**
We’re sorry. You can’t change your direct deposit information right now because we’ve locked the ability to edit this information. We do this to protect your bank account information and prevent fraud when we think there may be a security issue.
To request that we unlock this function, please call us at 800-827-1000 (TTY: 800-829-4833). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by erikphansen** [comment]
this is what it looks like in place:
![image](https://user-images.githubusercontent.com/20728956/67050603-b8cf0080-f0ed-11e9-8cf3-27f8af6d46cf.png)

**Comment by peggygannon** [comment]
@erikphansen looks good!

**Comment by Samara-Strauss** [comment]
@peggygannon @erikphansen all of this looks good to me! Thanks!
