### ISSUE TITLE
Disable CSRF on KMI /unsubscribe route

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#23542]
Remove CSRF protection on the unsubscribe route for the KMI app. Users post data to that route via an email link, so there is no opportunity to establish a CSRF token before making the call the /unsubscribe.

Identification and discussion here:

https://dsva.slack.com/archives/C01FNSTQD7H/p1618509459301500

**Comment by patrickvinograd** [comment]
We're also seeing a significant number of events on the original KMI `:create` action:
http://sentry.vfs.va.gov/organizations/vsp/issues/6196/tags/?environment=production&project=3

 I'm not quite sure why since it should be running well after the website has loaded and had an opportunity to get the CSRF token. My suspicion is that because it's a custom frontend component not using the VA Form System, maybe it's not _sending_ the CSRF token even though one is present? I'm going to merge the fix for opt_out specifically, and then investigate the create action.

**Comment by patrickvinograd** [comment]
Actually that makes me wonder if the issue with opt_out is the same - that there is an opportunity to get the CSRF token but the unsubscribe app is not using it. After all it's not like the email link is direct to the API. Going to investigate a bit before skipping the authenticity check on the backend.

**Comment by patrickvinograd** [comment]
I believe this is actually a frontend fix: https://github.com/department-of-veterans-affairs/vets-website/pull/16880

Though I do have a branch where I disable CSRF protection specifically for the opt_out endpoint on the backend in case there is a timing issue there. Should be pretty easy to launch the equivalent unsubscribe link from a browser and see whether it has the opportunity to get the CSRF token during page load.

**Comment by patrickvinograd** [comment]
Backend PR for completion's sake: https://github.com/department-of-veterans-affairs/vets-api/pull/6625

**Comment by patrickvinograd** [comment]
Both frontend and backend PRs were merged, we should keep an eye on the sentry event and verify it looks to be resolved, and then close this one.
