### ISSUE TITLE
IA Request LGY: COE (eBenefits)

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#23573]
## What this is:
Work with VSP Information Architecture experts to finalize the IA of your product for VA.gov

## When to use this: 
After you have received a response to your Collaboration Cycle kick-off ticket that indicates Information Architect Request is needed. 

## Requested artifacts:
*Provide artifacts as available. If not available at the time this issue is created, please add information as it becomes available.*

- Link to [product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/apply-for-home-loan-COE/README.md)
- Link to [prototype](https://xd.adobe.com/view/6c65f5c2-36e1-4051-81be-6f8b9415a3cd-3936/screen/a940748b-b2c7-41f1-9285-2eaee18313cd) 

## Information Architecture worksheet:
*Provide any the following information, as available, to help provide direction and support of your IA.*

**Content/feature placement** - Where do you believe this content and/or feature should live within VA.gov and why?
We think it might be best around the housing assistance and/or records.   

**Keywords and SEO** - What keywords does the primary audience use when they talk about or search for your content?
home  
loan  
mortgage  
VA-backed   

**URL(s)** - What are your suggested URLs and why?
va.gov/housing-assistance/home-loans/how-to-apply  
va.gov/housing-assistance/home-loans/apply-lgy-form-1880  

**Primary entry points** - What do you see as the primary entry point for users to find your new content/tool?  
va.gov  
va.gov - Mega menu  
va.gov/housing-assistance/  
va.gov/records/  

**Crosslinking opportunities** - What additional related areas of the site would links to your content/tool be helpful?
va.gov/records/  

**Redirects** - Will any existing content and/or tools need to be retired and redirected the new feature?
From EBN, eventually

## Definition of Done
- [x] VFS: Creates issue and provides all required information above
- [ ] VSP: Completes final IA feedback/recommendation
- [ ] VSP: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated
- [ ] VFS: Closes issue once all IA feedback/recommendations are implemented

**Comment by mnorthuis** [comment]
@jason-gcio IA is available here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md

Questions:
- Will there be a way for them to access their approved COE on the site after it is approved? 

A couple of things in regards to your suggestions above and my recommendations:
- I utilized "COE" rather than "LGY" in the URL and link references because I believe that is the more known acronym for this.  If Sitewide content utilizes "LGY" more, then I would potentially update my IA to reflect that where necessary/applicable. 
- In regards to crosslinking from the Records hub...the Records hub is (supposed) to be focused on retrieving (get) and managing your existing records, not applying for new things.  The existing link for "Learn how to apply for a COE" was a rather large debate on the stakeholder side, and should not have been included in that hub.   Therefore, I am not recommending adding an "apply for coe" option or changing the one that is there right now.   HOWEVER, based on my question above, if there is going to be a specific way for them to download or retreive their COE after it is approved (outside of it just be part of the benefit letters feature), then we could look at linking to that - although I don't see anything like that as part of the scope. 
- Assumption is that eBenefits will handle redirects.

**Comment by mnorthuis** [comment]
Notes per discussion with @jason-gcio @sporeboy

I'm keeping the IA request open until we can resolve these 2 items.  Let me know if I missed anything.   

How will returning users access their COE or see information about what to do after they have applied? 
1. Jim will be reviewing the user flow to accommodate returning users who want to 1) know what to do next, 2) check the status of their application and/or 3) download their COE. Right now various states of the /introduction page are handling returning users, but they are required to sign in to see the information and a CTA labeled "Apply for COE" will likely not draw attention from those that have already applied.  We will need a more relevant CTA/link for returning users to "check status" or "get coe".
2.  Mikki to work with @bethpottsVADEPO on an additional placement for content related to what to do after applying.  Currently this content is displayed only on the confirmation page, which isn't available to returning users.  The content solution will depend on the functional solution for the #1.  Once the user flows are established, then content can be layered on as appropriate.  



Future state 
- Jim has opened conversations with auth exp team on potential placement within My VA
- Team will keep it in mind if a team starts any work on the "Download benefit letters" tool
- Will be included in any other broader authenticated experience type work

**Comment by mnorthuis** [comment]
@sporeboy @jason-gcio Can you provide an update on your work so I can update/finalize IA?

**Comment by sporeboy** [comment]
@mnorthuis I think we're set:

Feature flow diagram: https://xd.adobe.com/view/03f5874d-242c-4e74-9616-641276b2b238-56a6/
User flow diagram: https://xd.adobe.com/view/03f5874d-242c-4e74-9616-641276b2b238-56a6/screen/475bb5b9-8551-41f9-9b1e-236b052316e0

Prototype w/ initial content (use sitemap to navigates screens): https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/139055586

- How to apply for a VA home loan Certificate of Eligibility
https://www.va.gov/housing-assistance/home-loans/how-to-apply/
- Eligibility requirements for VA home loan programs
https://www.va.gov/housing-assistance/home-loans/eligibility/
- Buying a home with a VA-backed loan
https://www.va.gov/housing-assistance/home-loans/home-buying-process/
- Download VA benefit letters
https://www.va.gov/records/download-va-letters/
- About VA Form 26-1880
https://www.va.gov/find-forms/about-form-26-1880/
- The Claim Status Tool (Still TBD)
- Check your VA claim or appeal status
https://www.va.gov/claim-or-appeal-status/
- Check COE status (Section or page?) URL pending
- Your COE page (View, download, status tool) URL pending

**Comment by mnorthuis** [comment]
@sporeboy @jason-gcio All IA information is finalized here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md

Worked through this with @bethpottsVADEPO to align on H1s, URLs and link labels for consistency.  

Please let me know if you have any questions, otherwise you are free to close this issue when you have the information you and your team needs.

**Comment by mnorthuis** [comment]
@sporeboy @jason-gcio 

Based on the stakeholder's request to change the language from "apply" to "request", I have made a few updates to the original IA documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-home-loan-coe.md

Here are the highlights:

- The application URL has been updated to `/housing-assistance/home-loans/request-coe-form-26-1880`.  Please make sure this is communicated to your devs. 
- The language change will result in an H1 change for that page as well, please make sure the breadcrumb matches the H1 of the page.  
- The existing "How to apply" page will need a URL change and a redirect.  Does this need a stakeholder notification before we move forward with this change?  I created the redirect request ticket, which can be implemented as soon as you say good to go. I will coordinate with sitewide content and PW team for implementation. 


You can close this issue once you have the information you need.
