### ISSUE TITLE
Collaboration Cycle Kickoff [Facilities, Emergency mash-up]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#23583]
## Steps to complete Collaboration Cycle Kickoff
- [x] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [x] VFS: Answer the questions below.
- [x] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [x] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [x] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- [Product brief](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator/product/emergency-care-mashup)
- Link to wireframes, mockups, or prototypes
- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [ ] New
- [x] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [x] Yes
- [ ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [x] Yes
- [ ] No

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work include content changes for: (Select all that apply)
- [ ] Tools and applications*
- [ ] Static pages
- [x] This work doesn’t involve content changes.

*For tools and applications, take into account if any content on static page entry points will need updates.

Content changes could include: updates to buttons, links, labels, headings, reordering content, or adding error messages.

### 6. Are you making a change to the user flow?
- [ ] Yes
- [x] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 7. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 8. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [x] Yes
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 9. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @mmiddaugh. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a static content page(s) so we are recommending the following Collaboration Cycle touchpoints: 

- Design Intent ([scheduled](https://github.com/department-of-veterans-affairs/va.gov-team/issues/23439))
- Research Plan Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit

Since your work impacts static pages, please reach out to Dave Conlon and John Hashimoto to review how your work may overlap with any existing work. This will help them prioritize and identify possible areas of support needed from other teams. 

The following practice areas will be included throughout the Collaboration Cycle process: (select all that apply)

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the[ Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by shiragoodman** [comment]
hey @mmiddaugh  - apologies, but I think I made a copy/paste error in my response above. We would recommend a Midpoint Review for this initiative. Midpoint Review's can be held asynch so please feel free to take advantage of that option. The Platform Collaboration Point Tracker has been updated to reflect the change. Please reach out if you have any questions.
