### ISSUE TITLE
[Debt letters] Content bug in error alert on 'download debt letters' page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#23596]
## How to recreate the bug

1. Sign into [the debt management portal](staging.va.gov/manage-va-debt/) with test user 1
2. Click on 'Go to debt details' under the CH 35 education debt card
3. Scroll down to the 'Download debt letters' header and click on the link 'Download letters related to your VA debt'
3. You should see the error alert attached below. There's a space missing between the number '800-827-0648' and 'to'
![Screen Shot 2021-04-21 at 3.12.27 PM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/833097c2-cca1-4e52-9447-63e895d466d0)

---
## Tasks
- [ ] _Add a space between the phone number and 'to'_

## Acceptance Criteria
- [ ] _The content has been updated in the error alert_

**Comment by LinnJS** [comment]
@craigwheeler and I are having issues logging in to the http://localhost:3001/manage-va-debt/ URL due content build separation redirects.

**Comment by LinnJS** [comment]
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17432) where this work is being done

**Comment by LinnJS** [comment]
So I opened a PR because I was hoping that I would be open to just test in a Review Instance since on localhost when I try to sign in as noted above on http://bb8107db5bd35a18be888792c40619b4.review.vetsgov-internal/manage-va-debt/ I get redirected away and signed out and can not get to http://bb8107db5bd35a18be888792c40619b4.review.vetsgov-internal/manage-va-debt/my-debt what so ever and this was the page the error message is being rendered on so its a bit of gap in development experience.

**Comment by LinnJS** [comment]
Turns out there was a old feature flip that defaults to off and the redirect was being caused by the feature flip.

**Comment by LinnJS** [comment]
Open this [ticket](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/25648) due to some cleanliness issues that lead to this bug to fix it application wide
