### ISSUE TITLE
Increase conversion of saved-in-progress health care applications by sending a reminder email

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#23609]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)

## High Level User Story/ies
As a Veteran, I would like to be reminded about my in-progress health care application so that I can complete the application or seek assistance in completing the applicate to start accessing my VA health care benefits.

## Hypothesis or Bet
**If** _we send a reminder to Veterans with a saved-in-progress health care application_ **then** _we expect conversion (online form completion) to increase._.

## OKR
_Which Objective / Key Result does this epic push forward?_
- Objective: More eligible Veterans apply for health care online from the VA.
- Key result: Increase conversion of Saved-in-Progress applications by ___%

### What must be true in order for you to consider this epic complete? 

- Phase one of this epic will be exploratory research to explore feasibility 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [X] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `tools-be`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by mlighdc** [comment]
Notes from conversation with Dror:
#### Goals
Figure out path forward for a solution to send Veterans reminders when they have started their form but have not completed it. These can be either SMS or Emails.

#### Discussion Topics
High level technical description (proposed by Dror Matalon)

- Create a Rails job that runs periodically.
- It checks the db for forms that have been completed in a certain time frame
- It contacts VA Notify and send the message based on a supplied template
- To simplify things the job does not update the db to mark which reminders have been sent
- On completion the job should post to a slack channel a message: X number or reminders sent, Y number failed

#### Resource Allocation and Estimation
Dror Matalon estimated one engineer full time for one sprint to implement this. On the safe side, we should probably allocate two sprints, since it involves cross team collaboration.

The platform does not have resource to implement this functionality until 3rd or 4th quarter of 2021, and possibly beyond. The platform should be involved in the implementation so we have a generic implementation that other teams can use as well.

The cost of sending the messages to 10,000 vets, based on back of the envelope calculation, is $1/month. The platform will bear that expense.

**Comment by mlighdc** [comment]
@bevnobev here is the ticket for the email / text reminders.

**Comment by kevinmirc** [comment]
From what I recall about the form system, the `InProgressForm` record is created when the first page of the form is visited (something that is easy to do if you're just browsing). And once an `InProgressForm` is created it cannot be simply discarded by the user - they only have the option to continue the form, start over from scratch (creating another `InProgressForm`, or let it expire after 60(?) days.

Before adding notification features, we should confirm the above details of the form system and consider:
- giving the user the ability to delete an in-progress form
- only creating in-progress forms when data is entered

This way users aren't receiving notifications for a form they didn't know they started and can delete unintentionally created forms in order to stop notifications.

**Comment by bevnobev** [comment]
@ffafara-tw @miabecker looping you both in

**Comment by miabecker** [comment]
@kevinmirc we are going to try and find someone who has more in depth knowledge. If that is the case @mlighdc we most likely can't build out a notification now. But if the behavior is different then we could help. @annaswims do you have more insight on how the form and its statuses works?  cc: @ffafara-tw @bevnobev

**Comment by mlighdc** [comment]
@miabecker feel free to reach out to Dror as I talked to him initially. Or Dror can suggest someone. Also, if a save in progress form is created when a user hits the first page, I got believe we can check where they are in the form process and potentially use two conditions to do the notification, such as (1) form is saved in progress, and (2) they are at step 2 of 5 of the form. Thanks.

**Comment by annaswims** [comment]
Everything @kevinmirc said is correct, though you could filter by only those who entered a certain amount of data or progressed beyond a certain page.  We store the last visited page on the form in the database.

**Comment by ffafara-tw** [comment]
The in-progress forms are used only for authenticated users, correct? So there should be enough information in the form to load user's contact information from VA Profile?

**Comment by miabecker** [comment]
@annaswims @kevinmirc any thoughts on @ffafara-tw's question above?

**Comment by annaswims** [comment]
In-progress forms are used for authenticated users, but not all authenticated users are identity-verified.  VA Profile is only available for identity-verified users. Though, some forms require a user to be identity-verified, not sure about this one. @kevinmirc ?

**Comment by kevinmirc** [comment]
I'm not so sure that the online 10-10EZ requires identity-verified users only, so this can be an additional condition when selecting which users to notify.

**Comment by drorva** [comment]
btw, my "one sprint, one engineer" was off the cuff basic estimate. This now looks like at least two sprints

**Comment by bevnobev** [comment]
Tagging the Notification Strike Team @megansiddle @nathanbwright @RookTKO I don't have Andrew's github ID

**Comment by megansiddle** [comment]
@ajmauricio

**Comment by hdjustice** [comment]
Met with Megan Siddle & VA Notify Strike team on updated process for reminder emails - they will be sent after 7 days of inactivity only.  If Veteran accesses and triggers the Save In-progress, the 7-day clock resets.  
Per Megan, they saw the most engagement with the 7-day reminder, and a huge increase in conversion!  
>(The open rate was 71% is now 91%; the click rate was 28% is now 51%; the conversion rate was 3.5% is now 7.5%)!

The team has agreed that this updated timeframe satisfies our concerns for not wanting to over-engage (bother or annoy) the Veteran.  We are happy to get this launched again!  The VA Notify Strike team will review their Sprint plan and let us know when they can start the launch.
cc: @markfallows

**Comment by hdjustice** [comment]
This feature has been launched to 100% as of November 1st, 2022.
