### ISSUE TITLE
Determine messages and logic for service-related error conditions

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#2362]
There are several broad error situations where we need to determine the right course of action:

1. A service or services in the Community Care eligibility check process fail 
A) try again later  
B) go down the VA path 
C) call and talk to a human
I'm thinking this could be a giant alert @peggygannon 

2. One of the services related to fetching supported VA facilities fails
A) throw an alert that says something like "something went wrong, try to schedule an appt later "
B) Call the main VAMC?

3. One of the services used to determine if a user is eligible to request or direct schedule
A) If the direct schedule fails, we can route into Request flow
B) if something else fails (we try to check past appts or check appt limit) we throw a generic something went wrong, try again later error

4. One of the services used to route a user to direct scheduling fails
This error could be something like an error fetching the list of clinics. We could
A) show them all the clinics
B) throw an error to try again later, but im inclined to just show the giant list (which is how legacy VAOS works anyway)

5. The final request/appointment submission fails.
A) This is an alert that says something to effect of "oops, something went wrong when you submitted your appointment / appointment request. We can schedule you online right now. You can call [Name of facility and contact info] (we know this from the session) or try again later

6. We're unable to fetch the available appointment slots during the DS flow
A) we could route users into the request flow—the challenge with this option is…something i dont remember and didnt write down when we were talking @jbalboni if you could fill this in i would :heart: you
B) we could have them call
C) They could try again later

For each of those situations we need:

A. What action should we take and
B. If the user can go no further, what message we show

**Comment by markgreenburg** [comment]
@jbalboni is this still something we need to go through?

**Comment by jbalboni** [comment]
@markgreenburg We have some of these handled, but I think we have gaps.

**Comment by markgreenburg** [comment]
@rtwell for scenario 1, feels like we could do some type of alert or content-only page where we usher veterans down the VA path and let them know that they _might_ be eligible for CC but that they will need to check back later because we can't know right now. Same thing for 4 - we could probably tell veterans that they might be able to self-schedule later, but can only request an appointment for the time being. Thoughts? We also need a UI and copy for when self-scheduling or request submission fail - some sort of fail page instead of the confirmation screen.

2 & 3 feel like we could just use the standard 'something went wrong' error messaging since these errors would block them from being able to do anything.

**Comment by markgreenburg** [comment]
cc @peggygannon

**Comment by peggygannon** [comment]
@markgreenburg @rtwell Here are messages for scenarios 2, 3, and 5. I need additional info about how scenarios 1 and 4 will be rendered on the screen (alert? content-only page) before I craft a message.  

@jbalboni  For #5, I wrote a draft message for number 5. Can you let me know if the resolution is that the user needs to start over? or that they need to come back to the application later and try submitting again?

Scenario 2: One of the services related to fetching supported VA facilities fails

**We’re sorry. We've run into a problem**
Something went wrong on our end. Please try again later.

---- 

Scenario 3: One of the services used to determine if a user is eligible to request or direct schedule

**We’re sorry. We've run into a problem**
Something went wrong on our end. Please try again later. 


------

Scenario 5: The final request/appointment submission fails
message options: 

**Your {request}{appointment} didn’t go through**
We’re sorry. Something went wrong when we tried to submit your request and you’ll need to start over. We suggest you wait a day to try again.
For help submitting your request: 
TKTKTKTTKTK

**Comment by markgreenburg** [comment]
@peggygannon @rtwell @jbalboni To answer some outstanding questions:
Scenario 1: all veterans (who chose a CC-supported ToC) would see this error because it happens at point where we check all veterans for CC eligibility. So the preference would be to put them straight into the VA flow and show any errors / alerts on the first page in that flow.
Scenario 4: Put veterans into the request flow. If we want to show alert, show it on the first page in the request flow. Alternatively we could show veterans all their clinics and let them continue to DS, but that seems like it might produce suboptimal scheduling outcomes even though it's on par with legacy functionality. @rtwell to confirm whether or not I'm crazy to think that.
Scenario 6: Stop flow, show an error

**Comment by lenaecb** [comment]
@jbalboni - is this something we still need to address?

**Comment by jbalboni** [comment]
@lenaecb I'm not sure, I will go through this ticket today and figure out what is still outstanding.

**Comment by jbalboni** [comment]
All of these issues have been broken out into separate tickets, closing this.
