### ISSUE TITLE
[FE] My VA: Implement error for when we can connect to MPI but user does not exist 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#23696]
## Background
As noted in #22656 we need to implement an error for when can connect to MPI but the user does not exist in MPI . This is the same alert that already exists in Profile that we'll be implementing in My VA dashboard.

## Task

- [ ] Implement alert as depicted below in screenshot and copy.

Copy should read as follows:

**We can't match your information to our records**

We can’t give you access to VA.gov tools to manage your health and benefits right now. We’ll need to match your information and verify your identity first.

If you’d like to use these tools on VA.gov, please contact the VA help desk at 800-698-2411 (TTY: 771) to verify and update your records.

## Screenshot of alert with correct copy:

![Screen Shot 2021-04-23 at 4.12.47 PM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/a3e642d0-1b92-43c8-a41e-1f1eb37cc415)

**Comment by tressaellen** [comment]
@bethpottsVADEPO we are now tracking this work in this ticket instead of in #23468. I noticed I didn't exactly have the wording the same as what we have in profile, so I updated it to what we have there:

**We can't match your information to our records**

We’re sorry. We can't give you access to health and benefit tools until we can match your information and verify your identity.

If you’d like to use these tools on VA.gov, please contact the VA help desk at 800-698-2411 (TTY: 771) to verify and update your records.

 For My VA the only change that we're looking to make is to change. 
-  "profile or account information" --->  "health and benefit tools"

What are your thoughts about that? I'll drop the profile alert below so you have some context. I'm happy to chat if you have any questions.

![Screen Shot 2021-04-23 at 10.37.04 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/467cc375-feb7-4925-a389-b2157d550d63)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @tressaellen! Beth and I chatted quickly about this. Think it would be good to change this to the following. Let us know if this works - thanks!

We can’t give you access to VA.gov tools to manage your health and benefits right now. We’ll need to match your information and verify your identity first.

**Comment by tressaellen** [comment]
Thank you @bethpottsVADEPO and @DanielleThierryUSDSVA ! I've updated the copy and screenshot in the main portion of this ticket. Should this also be updated in the profile version of this alert?

**Comment by bethpottsVADEPO** [comment]
@tressaellen Probably, but can you paste that alert here so we can see it?

**Comment by erikphansen** [comment]
I'm not sure if this can be easily validate on staging or not. It can be closed if we don't have a staging user who is not in MPI.

**Comment by ajakabcin** [comment]
Closing

**Comment by tressaellen** [comment]
Sorry, just going to close the loop with @bethpotts and then I'll close this ticket. Here's the screenshot for the updated profile version of this alert using the copy that you recommended. 

If this is approved, then we can update. (cc @ajakabcin )

<img width="717" alt="Screen Shot 2021-04-28 at 11 32 16 AM" src="https://user-images.githubusercontent.com/58752772/116431053-deb18700-a7f3-11eb-940a-9b4ba2416089.png">

**Comment by tressaellen** [comment]
I think that we need to streamline these alerts. So I've made two tickets for this.

- #24105 - updating the above copy in profile (@bethpottsVADEPO if you have objections or changes, please comment in #24105)
- #24108 - to take a look at the other MPI error and figure out copy for that. 

Since this ticket is done, I'm re-closing. :)
