### ISSUE TITLE
Engage with Global UX about an Unauthenticated Page

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#2375]
## Goal
Learn what the process or guidance is from the Global UX perspective to create an unauthenticated page before landing into the Rated Disabilities Tool so that we can determine who should be building that page.

## Considerations
- A [link to mockups](https://xd.adobe.com/view/0db723ac-52ff-48b3-4877-9d5882cb2e1f-7b86/screen/8990839d-80b5-450d-8164-c1f203a8991d/RD-Screen-Tool-2/)

## Task
- Schedule a meeting with members of the Global UX Team (DSVA - Jen and PM Kara)
- Invite all of eBenefits Team

## Acceptance Criteria
- [ ] Establish who is responsible for creating an unauthenticated page ahead of the Rated Disabilities Tool.

**Comment by Karak888** [comment]
hi @jason-gcio we will not be able to get to this for a few weeks, because in addition to content / design, it will require a build out of the page (i.e., work on the REACT part of the tool page), and we will not have our FE engineers for a month.  Looks like you have started with IA and design (Mikki / waiting on Shawna), and if you need conrtent maybe Megan Kelly can help you?  I am going to move this to our backlog for build out once you have everything finalized.  Thanks!

**Comment by jason-gcio** [comment]
Thanks @Karak888.  We will keep an eye out on this and we will chat a little further down the road.

**Comment by Karak888** [comment]
closing this as we did engage, but commented in other ticket. @mnorthuis @jenniferlee-dsva @Karak888  to connect on how we are going to do this.
