### ISSUE TITLE
SQL Injection Vulnerability

### ISSUE THREAD

**Issue by f1337** [department-of-veterans-affairs/va.gov-team#23853]
## Summary

@darkbushido found a SQL-injection vuln in one of our engine modules. This is the line of code:

https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/app/models/vba_documents/upload_submission.rb#L30

Here is the error, from a targeted scan:

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "(metadata -> 'status' -> 'pending' -> 'start')::bigint asc". Non-attribute arguments will be disallowed in Rails 6.1. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block in <class:UploadSubmission> at /srv/vets-api/src/modules/vba_documents/app/models/vba_documents/upload_submission.rb:30)
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "(metadata -> 'status' -> 'uploaded' -> 'start')::bigint asc". Non-attribute arguments will be disallowed in Rails 6.1. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from block in <class:UploadSubmission> at /srv/vets-api/src/modules/vba_documents/app/models/vba_documents/upload_submission.rb:30)
```

## Acceptance Criteria:

- [x] Determine why our automated scanners (brakeman, sonarqube) did not catch this
- [x] Ensure our automated scanners (brakeman, sonarqube) are scanning Rails engines
- [x] Fix the SQL-injection vulnerability, ideally with the help of the team who originally wrote it (if possible & determinable in a short time frame, this is urgent)
- [x] Open related tickets that come out of this one (as defined below)
- Enlist *any* member of the VSP Platform team you need to close this ticket ASAP.

**Comment by jeff2d2** [comment]
@jeff2d2 to clean this issue up

**Comment by ericboehs** [comment]
The aged_processing scope is only called in one place: vba_documents/slack_notifier.rb#L44. The variable here comes from a static list via the UploadSubmission::IN_FLIGHT_STATUSES. No user input is used in this method.

There could be a concern that one of our engineers would call this elsewhere with user input so we may want to consider safe guarding against that but at the time there is no security vulnerability being exposed here.

Furthermore, the code was written to avoid Brakeman’s detection by using a lambda instead of a whitelist override (as the code comments and commit messages point out). Perhaps we should change that but it’s also not an immediate issue.

Finally, wrapping it in Arel.sql is essentially forcing it to use the raw SQL. It's Rails' way to make us inspect the code for SQL injections. It's a good thing but doesn't solve any problems besides silencing the warning.

**Comment by LindseySaari** [comment]
I don't see any immediate risk because there's no user input being used for the status. I see that [fetch_stuck_in_state](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/app/workers/vba_documents/slack_notifier.rb#L99-L104) calls aged processing on line 103/104, but are both method call/parameter instances hard coded as [:minutes](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/app/workers/vba_documents/slack_notifier.rb#L57) and [:days](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vba_documents/app/workers/vba_documents/slack_notifier.rb#L64)  (no user input)

**Comment by ericboehs** [comment]
Even though the concern raised isn't a security issue, we should still create a few tickets out of this:
- [ ] Investigate all `Dangerous query method` deprecations for security vulnerabilities
- [ ] Use config/brakeman.ignore for vulnerability whitelist instead of hiding warnings with a lambda
- [ ] Determine if other warnings are hidden with lambdas (search for `.call`)
- [ ] Limit status variable to known list within scope definition

**Comment by jeff2d2** [comment]
Above issues created and comment above edited to include links

**Comment by ericboehs** [comment]
Repeating the message above so GitHub links the tickets to this one:
- [Investigate all `Dangerous query method` deprecations for security vulnerabilities](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/23953)
- [Use config/brakeman.ignore for vulnerability whitelist instead of hiding warnings with a lambda](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/23954)
- [Determine if other warnings are hidden with lambdas (search for `.call`)](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/23955)
- [Limit status variable to known list within scope definition](https://app.zenhub.com/workspaces/vsp---backend-tools-6019ab9387ae890011e05e73/issues/department-of-veterans-affairs/va.gov-team/23956)

**Comment by ericboehs** [comment]
@f1337 Closing this in favor of the four issues that we spun out of this one. Let me know if we missed something we should address!
