### ISSUE TITLE
Design Feedback - Midpoint Review [Claims & Appeals Team, Notice of Disagreement]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#23960]
## VFS acceptance criteria
- [ ] Let VSP know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Replace all green buttons with the green [action link](https://design.va.gov/components/action-links)
- Remove blue circle for steps on progress bar and change font to bitter. See Sketch/Styles/Feedback for example
![Screen Shot 2021-04-28 at 3.29.57 PM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/aa5453ca-c691-4f0b-a048-6977f1950870)
- The chevrons on the << Back button should be blue.  See Sketch/Styles/Buttons for example
- Delete file should be a secondary button. See [file upload](https://design.va.gov/patterns/form-templates#file-upload) for example
- Edit on profile should be a button
- Add space between headings in review page. See the screen shot below and the spacing between ‘Which categories…’ and ‘Mailing address’![Screen Shot 2021-04-29 at 7.59.40 AM.png](https://images.zenhubusercontent.com/5f7e15543782a5c1ee10f1f0/91fa3ec6-63dd-4d4e-8ad1-275e5d35a486)

**Should:**

**Consider:**

## VSP directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the VSP Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Usability Testing Prep**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by Mottie** [comment]
Hi @allison0034!

I have a couple of questions related to the implementation. First off, the screenshot isn't from our NOD form.

> Replace all green buttons with the green action link

Last I heard, Shawna and Chris V. were going to test this to determine if should be done globally. I have a PR to switch this for NOD introduction page specifically, but held off after our discussions in the Design Council Meeting.  

> Delete file should be a secondary button.

This is currently globally implemented as a button that visually appears as a link. If I fix it, it'll apply to _all_ forms that upload files. Is that what needs to be done?

> Edit on profile should be a button

We've had discussions with our accessibility specialist and since it's a link to the profile page, it should be a link. Should we change it back?

Please let me know how we should proceed.

**Comment by sshein** [comment]
Regarding the action link, I asked the council to hold off recommending the action link until it had been more thoroughly tested. Some of them circled up and decided that they would set up some kind of test but that they would continue recommending it for all buttons that act like links. Maybe Allison can give you background on why that is. 

Regarding the upload button on the upload component, can you circle up with Justin because he hasn't to do this too for his feature. Allison, if it's a change that impacts things globally, does anyone need to do an audit and check that we aren't going to mess anything up on other's forms? Or at least alert all the teams to check their upload components after the change?

**Comment by rtwell** [comment]
- [additional info component](https://design.va.gov/components/additional-info) is not bold
- "Upload" language seems a bit vague, maybe "Upload document" or "Upload evidence"?
- on the [add another doc](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538570) screen i would use the same language as the initial action. So if the initial action is "Upload", then the second screen would read "Upload additional document" in stead of "add".
- @Mottie you are correct — Edit on profile should be a link (capitalized E in Edit)
- on the [add issue page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538584) — what happens if a user clicks add issue while the add issue card is active? should the add issue button hide while there is an open entry? @joshkimux i'm curious on your thoughts here

**Comment by shiragoodman** [comment]
@Mottie @sshein Allison was off yesterday and is off today too. She can get back to you next week!

**Comment by Mottie** [comment]
> * what happens if a user clicks add issue while the add issue card is active?

Currently, if the content of the edited card is valid, it'll add a new empty card and leave the previous card in edit mode. If the edited card content is invalid, it'll scroll to and focus on the element wrapping the error, but it won't add any additional cards.

**Comment by kevinstachura** [comment]
@rtwell some comments/questions:

>additional info component is not bold

We decided to bold this as a few testing participants stated that this was not easily apparent and felt like they would just never see it / skip over it, even if they were wondering where their issues were. We thought placement wasn't an issue since it is contextually close to the actual issues. However, it did seem to get lost in the visual reading --> interaction flow, so we decided to bold it. Is that a 'violation' of the component customization? Lemme know!

>"Upload" language seems a bit vague, maybe "Upload document" or "Upload evidence"?

I don't mind being more prescriptive on this. I think we decided to not be so specific since the heading and paragraph above the upload button tell you specifics. But for quick scanning (which we didn't really observe in testing - users typically read through the file requirements) I can see this being valuable.

>on the add another doc screen i would use the same language as the initial action. So if the initial action is "Upload", then the second screen would read "Upload additional document" in stead of "add".

Consistency makes sense here - agreed 👍

>on the add issue page — what happens if a user clicks add issue while the add issue card is active? should the add issue button hide while there is an open entry? 

What @Mottie said while I was typing out this novel 😂 but would love to hear Josh's comments as well!

**Comment by rtwell** [comment]
> additional info component is not bold
> 
> We decided to bold this as a few testing participants stated that this was not easily apparent and felt like they would just never see it / skip over it, even if they were wondering where their issues were. We thought placement wasn't an issue since it is contextually close to the actual issues. However, it did seem to get lost in the visual reading --> interaction flow, so we decided to bold it. Is that a 'violation' of the component customization? Lemme know!

this is a UI fix to a UX problem—imo there is a bunch (possibly too much) happening at once on this page. not only are we asking users to confirm issues on file, we're simultaneously asking them to add new issues. One of our core [design principles](https://design.va.gov/design/principles#simple) is to focus users on one task at a time. 

In addition, "Why aren't all my issues listed here?" in bold reads as the primary question of the page, but only pertains to the issues we've presented below (not issues a users hasn't added yet, which could be confusing). If it's getting lost on the page because of lots of text, then I suggest cutting the amount of text.

You might consider separating these 2 tasks into separate pages in a sequence like the following (this is my terrible language, do not use this verbatim): 

**Do you want to review any of these existing issues VA has on file?**
- [ ] tinnitus
- [ ] another thing
`additional info component` Why aren't all my issues listed here?

**Do you want to add a new issue for review?**
- [ ] yes
- [ ] no

**Add a new Issue for review**
[  Add new issue interaction  ]

**Comment by rtwell** [comment]
regarding the checkbox: how do users know which issues would be considered part of the legacy appeals process? is there any way we can indicate this?

**Comment by Mottie** [comment]
> how do users know which issues would be considered part of the legacy appeals process

There is no way to know. We talked to Lighthouse about differentiating the issues, but I don't think it's possible.

**Comment by 1Copenut** [comment]
> > on the add issue page — what happens if a user clicks add issue while the add issue card is active? should the add issue button hide while there is an open entry? @joshkimux i'm curious on your thoughts here
> 
> I think completely hiding the add issue button both visibly and accessible while there is an open entry is fair. I'd be more worried of the accessibility issues related to folks having more than 2+ add issue cards open at any given time as there could be multiple dynamic fieldsets present with generic labels.
> 
> @1Copenut would like your thoughts on this too

I agree with @joshkimux on the benefit of hiding the add issue button visibly and accessibly when there's an open entry. I think having multiple forms to add items feels like a high cognitive load, and opens the possibility for conflating data.

**Comment by rtwell** [comment]
> > how do users know which issues would be considered part of the legacy appeals process
> 
> There is no way to know. We talked to Lighthouse about differentiating the issues, but I don't think it's possible.

how then do veterans know what they are agreeing to here?

**Comment by allison0034** [comment]
Hello @Mottie @sshein, sorry for the delay, I was out of office. 

Green action link - I have been told to still recommend this for now and going forward. 

Delete file button vs Delete file text link, this is an accessibility issue. Delete is an 'action' there for it should be a button vs a text link. The basic rule is if it is an action it should be a button. If it is navigation it should be a text link. @1Copenut may be able to provide exact clarification. @rtwell the 'Delete file' is a global component. Do you know what impact this will have and do we need to do anything else?

**Comment by allison0034** [comment]
@sshein by the 'Delete file' being global... do you mean if you change the component in this project it will have an affect on other 'Delete file' text links? Or are you meaning it is a visible change only (eg. we have text links and buttons for the same 'Delete file' action) on VA?

**Comment by sshein** [comment]
Hi @allison0034 yes, not arguing about the delete file being a button for a11y reasons, I get it - but earlier in the thread, Robin said "Delete file should be a secondary button. - This is currently globally implemented as a button that visually appears as a link. If I fix it, it'll apply to all forms that upload files. Is that what needs to be done?" - so yes, it sounds like if he changes this it will have an affect on all other "delete file" text links

**Comment by rtwell** [comment]
i checked in w/the design system team, and we're OK changing it globally @allison0034 @Mottie

**Comment by Mottie** [comment]
This page https://design.va.gov/patterns/form-templates#usability-guidance-12 shows the delete button with a primary style on the review & submit page. Should we _not_ show that button if the review page isn't being edited, and should it also have a secondary button style when it is visible?

**Comment by allison0034** [comment]
@Mottie Ryan is looking into this. The review section was just recently updated.

**Comment by kevinstachura** [comment]
Great! Thanks for all the feedback, folks. 

We'll be implementing all the designated 'must' changes and considering the suggested changes as well. We should have those set by the time we have our scheduled staging review. Definitely on an unprecedentedly tight deadline for this project so thank you all for the prompt responses!

**Comment by kevinstachura** [comment]
Changes have been made and can be viewed here:

https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538562

Here's what's changed:

**'Must' category**

- Replaced all green buttons with the green action link
- Removed blue circle for steps on progress bar and changed font to bitter
- The chevrons on the 'Back' button are now blue
- Delete file has been changed to a secondary button
- Added space between headings in review page

Omitted:

- **Edit on profile should be a button** - After ensuing discussions on this thread, this was dropped per accessibility's recommendations to keep it a link.

**Should (or all comments not specified in 'must') category:**

- We have changed the flow for 'Issues for review' to follow the 'one task per page' model, as best as we could for this complex flow. 


Please let me know if you have any comments/concerns. Thanks!

**Comment by rtwell** [comment]
this is is great @kevinstachura thank you for these quick updates
