### ISSUE TITLE
[DESIGN] My VA: Write UAT Research Plan

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24059]
## Background

We need to make sure with users that everything is working properly on My VA.

## Tasks

- [ ] Write [UAT research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-research-plan.md)
- [ ] Review with Samara/AJ.

**Comment by tressaellen** [comment]
Here is the [UAT research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-research-plan.md). :)

**Comment by Samara-Strauss** [comment]
This is looking great! The research questions are really thorough, and will be a good map for the script. We can fill in the rest of the dates and times info once we know exactly when UAT will be.

**Research questions**

- For LOA1 use cases, we can test that on our own in production. We won’t recruit veterans to test for this.

**Participant requirements**

Totally agreed that we need participants that are all LOA3, some that have health care, and some that have a claim or appeal in progress. I would say that we also need some that have a disability rating to make sure that works. This group may or may not overlap with those that have claims or appeals in progress.

Also, Idk if we have any way to screen for this through Perigean, but it would be nice to be able to check what the experience looks like for Cerner patients. But I'm unsure if recruiting for this is possible. I'll ask around.

**Attendees**

- I don’t think Lihan needs to be there, as there aren’t any new integrations that he built as part of this work. Since it’s primarily a frontend project, Erik should be sufficient from the dev end of things.

**Comment by Samara-Strauss** [comment]
Re: Cerner — it seems like we may not be able to recruit for this, so we likely won't be able to validate this use case.

**Comment by tressaellen** [comment]
@Samara-Strauss thanks for looking over this and thank you for asking around about Cerner. Bummer that we can't recruit for Cerner - I took that point out of the research plan. 

If you don't have any other edits, then I think we're good to close this ticket.

**Comment by Samara-Strauss** [comment]
Sounds good to me!
