### ISSUE TITLE
[DESIGN] My VA: Write UAT Conversation Guide

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#24061]
## Background

We need to ensure My VA is working properly for users.

## Tasks

- [ ] Write Conversation Guide
- [ ] Review with Samara

**Comment by tressaellen** [comment]
Hi @Samara-Strauss here is the [UAT conversation guide.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-conversation-guide.md)

Also, question. I'm considering making the study a little longer and throwing a few usability questions at the beginning or end. If I end up doing that, I'd want to make sure we're addressing the most important things, so I'd need to think it through. If you prefer to keep UAT and usability sessions separate that's fine too. I just wanted to get your thoughts.

**Comment by Samara-Strauss** [comment]
This looks great! Great job.

- For navigating to My VA via the link in the main nav, let’s have them go to VA.gov and click My VA **from the logged out state** in order to test that flow.

> Also, question. I'm considering making the study a little longer and throwing a few usability questions at the beginning or end. If I end up doing that, I'd want to make sure we're addressing the most important things, so I'd need to think it through. If you prefer to keep UAT and usability sessions separate that's fine too. I just wanted to get your thoughts.

I think this really depends on what the questions are. You'll have just walked them through the entire page, so then asking usability questions at the end might skew the results because participants may already have the answers. Of course, if people happen to mention usability issues or confusion while we're going through UAT, you should definitely note that down and feel free to ask follow up questions before you continue.

**Comment by tressaellen** [comment]
> For navigating to My VA via the link in the main nav, let’s have them go to VA.gov and click My VA from the logged out state in order to test that flow.

I've updated this in the conversation guide.

>I think this really depends on what the questions are. You'll have just walked them through the entire page, so then asking usability questions at the end might skew the results because participants may already have the answers. Of course, if people happen to mention usability issues or confusion while we're going through UAT, you should definitely note that down and feel free to ask follow up questions before you continue.

This is true... I think it's probably best to just wait on usability and note any issues that people have. 

If there's no other updates then I think we're good to close this!

**Comment by Samara-Strauss** [comment]
Great! Closing :D
