### ISSUE TITLE
Collaboration Cycle Kickoff Healthcare Experience - Checkin MVP

### ISSUE THREAD

**Issue by leahkeeler** [department-of-veterans-affairs/va.gov-team#24154]
## Steps to complete Collaboration Cycle Kickoff
- [ ] VFS Product Manager: Create this issue and fill in your team and feature name in the title.
- [ ] VFS: Answer the questions below.
- [ ] VFS: Link to this issue once created in vfs-platform-support in Slack; tag @vsp-product-support-members.
- [ ] VFS: Attach any available artifacts.
- [x] VSP: Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] VSP: Add project/feature to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).
- [ ] VFS: Close this ticket when all steps above are completed.

## Artifacts (if available)
- Link to draft of [[product outline]](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-outline.md)
- Included in Product Guide 
- The BE interface is being developed in parallel with this product and will be a micro services layer built on Vets API ![image.png](https://images.zenhubusercontent.com/5e41d853bb7b6d67d84e6080/a6e52584-6cb6-4c0f-a4c3-f6acd0d1a645)Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/collab-cycle-get-started.md) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X ] Yes
- [ ] No

Examples of **visible changes** include:
 - Any changes that the user will see
 - Adding a new form, tool, or page
 - Modifying buttons, design elements, interactions, or page layouts
 - Reordering content, adding new calls to action, alert boxes, expandable sections, or error messages

Examples of **no visible changes** include:
 - Changes to code that the user won’t see
 - Changes to accessible labels. These might include aria-label, aria-labelledby, aria-describedby

### 2. Is your work a new product/feature or an iteration to an existing product/feature?
- [X ] New
- [ ] Iteration

Examples of a **new** product/feature include:
 - Migrating over a paper form that has new design components
 - Creating a new design component to a page layout
 - Adding new functionality to an existing tool that is completely new to VA.gov

Examples of an **iteration** to an existing product/feature include:
 - Modifying or adding functionality, an interaction, or content to an existing page
 - Adding additional form fields or interactions to an existing online form
 - Re-organizing content (adding headings, subheadings, new paragraph order)

### 3. Are you making changes to the visual design?
- [ ] Yes
- [X ] No

Examples of **changes to the visual** design include:
 - Any changes to design components, buttons, layout, or patterns
 - Any changes to colors, icons, or typography

Examples of **no changes to the visual** design include:
 - Code-only changes

### 4. Are you doing research with VA.gov users?
- [ ] Yes
- [ X] No - this feature does not exist on va.gov yet

Examples of **research with VA.gov users** include:
 - Usability testing
 - User surveys
 - Card sorting

### 5. Will your work include content changes for: (Select all that apply)
- [X ] Tools and applications*
- [ X] Static pages
- [ ] This work doesn’t involve content changes.

*For tools and applications, take into account if any content on static page entry points will need updates.

Content changes could include: updates to buttons, links, labels, headings, reordering content, or adding error messages.

### 6. Are you making a change to the user flow? **N/A New product** 
- [ ] Yes
- [ ] No

Examples of **changes to the user flow** include:
 - Adding a new section to a form 
 - Moving from a wizard to one thing per page form model

### 7. Are you making a change to urls, navigation, or entry points? **N/A New product** 
- [ ] Yes
- [ ] No

Examples of **changes to url, navigation, or entry points** include:
 - Moving an online tool or content page within the site or needing to retire/redirect a page
 - Modifying options within core navigation elements (for example, top nav, left nav, home page)

### 8. Does your product/feature have Google Analytics tracking ~and a KPI dashboard in Domo~?
- [ X] Yes
- [ ] No

Please note that Domo is on pause until end of June. See [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/DEPO/team-wide-messages/analytics-services-paused-for-infra-work.md) for more information. Google Analytics tracking support will still be provided.

### 9. If yes, then do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X ] Yes
- [ ] No

## Additional information
Please refer to the [VSP Collaboration Cycle README](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/working-with-vsp/vsp-collaboration-cycle) on Github for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
@leahkeeler can you complete the title section? I have no idea what team this is for (since you're now supporting 2) and I don't know the name of the project. Thanks!

**Comment by leahkeeler** [comment]
@shiragoodman - I will stop doing this at all hours of the night - sorry about that :)

**Comment by shiragoodman** [comment]
Hi @leahkeeler. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project (pick 1 below) is a new tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- Design Intent ([tentatively scheduled for 5/6](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24149))
- Information Architecture (IA) Request
- Research Plan Review
- Analytics Request
- Midpoint Review
- Contact Center Review
- Staging Review
- Privacy and Security Review

Post Launch: 

- Full Accessibility and 508 Office Audit
- Post-launch Check-in

We recommend that you bring the tool/application and static pages through the Collaboration Cycle together so we can review the full flow/user experience. 

Please reach out to Dave Conlon and John Hashimoto to let them know your work will impact static pages, the nature of the work, and your projected timeline.

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 
 
Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) (under the New tab). Please review the guidance on our Collaboration Cycle README page for next steps.

**Comment by leahkeeler** [comment]
Thank-you @shiragoodman
