### ISSUE TITLE
How to attach a file FAQ page - formatting - bullets should be indented to match designs

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#24371]
## What happened?
The formatting in designs shows the bullets being indented.
In the app, the bullets are at the same level as the text above and below the bullets.
See screen shot.

## Specs:
- Device: All

## Steps to Reproduce
View How to attach a file FAQ page.

## Desired behavior
Bullets are indented to match designs.

## Acceptance Criteria
See above.

## Bug Severity
- 4 - Low

## Linked to Story
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/21200

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/e3a6a0d1-4fbb-45a1-b76c-b32e6831122e)

**Comment by bessgreen** [comment]
@digitalken given the quick turnaround for SM designs, the team agreed as a general rule to leverage the UI patterns and styles that already exist in the app, rather than amending these patterns for SM screens. 

The bulleted list on this FAQ page is formatted consistently with some of the other pages in the app that display a bulleted list, including the **LOA1 gate** and the **Ask for your claim decision** pages. Across each of these, the bullets are not indented.

Closing this ticket.
