### ISSUE TITLE
[FE] My VA 2.0 post-launch: Investigate whether we can hide the health care section for people not actively receiving care at the VA

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#24448]
## Background

On 5.6.21, we did a usability session for our preferred facilities work with a team member who happens to also be a veteran. This session revealed that the following can be true:

- A veteran is not formally part of the VA health care system and is not currently a patient.
- BUT, that veteran has received some sort of care in the past, and is therefore registered at a VA facility.
- Because this person is registered at at least one VA facility, their `GET user` object comes back that they are a VA patient.
- And because of that, we show them the Health care section of the My VA dashboard even though they aren't actually receiving care at the VA.

Ideally, we would not be showing veterans the Health care section of My VA unless they were actively receiving care at the VA. I'm not sure if we'll be able to better handle this use case, but we should at least investigate what our options are based on the data we can get about any given user.

## Tasks

- [ ] Investigate if there is a way to differentiate between people registered at a VA facility and patients who are part of the VA health care system and are active patients
- [ ] Determine next steps based on what we find

**Comment by erikphansen** [comment]
Liz and I just had a chat with some VAOS folks. At this point there isn't more we can do to properly determine if someone is actively receiving care (or even what that term really means). Both VAOS and My VA check to see if the user has any facilities associated with them and if they do we treat them as someone who has health care.

They did mention that lots of non-Vets are getting registered at facilities because they got their covid vaccine there. So the number of people who we are treating as VA Patients who really aren't is only going up. At some point in the future we will be able to use ESR to filter out these "vax-only" patients.

**Comment by Samara-Strauss** [comment]
Got it. Given this, is there any point in keeping this open and doing further investigation, or are we pretty sure based on the conversation with VAOS that there's not much we can do to improve this experience?

**Comment by Samara-Strauss** [comment]
Frowns :( OK, closing this, then
