### ISSUE TITLE
Content Feedback - Staging review - Health care questionnaires

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#24494]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
@leahkeeler @kristenmcconnell 

Content feedback for Healthcare questionnaire staging review. Please let me know if you have any questions. 

**Questions**
1. Have the static page entry points to this tool been implemented? I don’t see any implemented entry points on staging. 
2. On the questionnaire Step 1 screen, the intro says: 
*Below is the personal and contact information we have on file for you.*

- There is no contact information on this screen. Should there be? 
- In the  content source of truth artifact, mailing and home address and phone numbers are listed. Should this info also appear in staging? 
 
2. Related question:  Is the user's information coming from their profile? If so, should we be directing users to their profile to update information, rather than this note for them call? *Note: If you need to update your personal information, please call Veterans Benefits Assistance at 800-827-1000, Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.*

--------

**Must feedback**

1.  The content that pops up when you click on the [Privacy Act Statement] is specific to education forms. This information is usually pulled from the paper version of a form. Is there health-related information that should go here instead? 

2. Please fix/update the placeholder content that is showing up under the **Need help?**  and the completed questionnaire card components:
-	For questions about your appointment or if you have a health-related concern, call your VA provider. You can contact them at TEM MH PSO TRS IND93EH 2 at 254-743-2867, ext. x0002.
-	Under “Completed” tab Psychiatry clinic questionnaire
for your appointment at TEM MH PSO TRS IND93EH 2, CHEYENNE VA MEDICAL

3. Please fix broken link for [Contact your VA provider]
--------

**Should feedback**

Error messages

1. This expired questionnaire error message doesn’t provide content or navigation to help users understand what they should do next. Do they need to try again? Should they call someone? Will they need to fill this out the questionnaire at their appointment? 

I recommend tweaking this message so it clearly indicates what the user should do next. 
Your questionnaire has expired
Your saved upcoming appointment questionnaire has expired.


2. The “user can’t proceed” error message in the content artifact: 
I recommend removing “If you’re having trouble” from this message, as it sounds like the user can’t proceed at all from this point. 
 
Here’s a recommended  tweak: 
**We can’t submit your questionnaire right now**
We’re sorry. Something went wrong when we tried to submit your questionnaire. The information you’ve entered so far has been saved. Please try again later. 


3. On Questionnaire Step 2 screen 
Should “Routine or follow-up visit” header be styled as H3? It carries same weight as "What's the reason for your visit?" head. 

4. Please use sentence case for all buttons/labels/header
- Button: Add another Question > Add another question
- Label/head: New Question > New question

**Comment by kristenmcconnell** [comment]
**Responses to questions**
1. The [static page](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/22530) is in progress. Our main entry point is a text message, which is ready to go. Email will quickly follow. We are piloting with literally one doctor at the Loma Linda VA, who only practices one day a week (so we are looking at ~50 patients per month to start). Therefore, we would like to continue with the launch even if the static landing page isn't completely ready. We will make sure that the static page and left nav are completed before the pilot is expanded.
2. We worked hard on test data; it was a little complicated coordinating across the systems. As a result, this user didn't have a lot of associated contact information. If a user had mailing address, home address, and phone numbers, then that information would display. 
3. I had this question many times myself. Fundamentally, we need contact information changes to make it to the individual medical offices for our use case. From my understanding, we could link them to profile, but that doesn't mean that the information would actually make it to medical offices. Phone is the best option for now to address our use case. We do plan to revisit this with our team's next release, because this will become much more important for the check-in process.

**Responses to Must feedback**
1. Ming is working with @DanielleThierryUSDSVA on quickly updating the privacy statement for our use case. Once that is complete, we are going to make the fix for our product. We will include more details for our use case within the already exist platform ticket related to this, so this privacy statement can be variable (it is currently static across products). @mdewey Tagging you, since we will be addressing this.
2. This is actually not placeholder text; it is an actual name of a clinic. To correct this, someone will need to adjust the clinic names' in the database.
3. Already fixed.

**Responses to the Should feedback**
1. We should have let you know to ignore this expired case. It appeared due to bad test data. It has to do with the connection between appointment date/time and appointment status. The statuses that we are showing on the To Do tab in real life will never correlate to an appointment that occurred in the past. We don't want that use case to appear, because there is literally nothing that a Veteran can do at that point. The questionnaire isn't needed any more. In the test data, the status wasn't updated (as it would in production), when the time/date passed.
2 and 3. We are going to work through the musts first (engineering-wise), then we'll discuss these.
4. We will be removing the list loop and replacing it with a text area, so these issues will disappear as a result.

**Comment by kristenmcconnell** [comment]
Update on the privacy statement...due to the revisions to the privacy question/answer that exists higher up on the intro page, we think that the link to the privacy statement (and subsequent modal) at the bottom of the page might not be needed. Ming is checked with our legal contact.

@mdewey Work through the other staging review changes first, so we can give Ming some time to hear back from legal on this.

**Comment by peggygannon** [comment]
HI, @kristenmcconnell Thank you for your follow up!

**Comment by kristenmcconnell** [comment]
The privacy wording within the modal and intro page will be update in ticket #24041. We have the final approved wording from legal. Besides that, all of the Musts are complete. Most of the Shoulds are complete too. There are a few that we will tackle at a later date. We added them to #25208.
