### ISSUE TITLE
Migrate Frontend Support Dashboard

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#24545]
Move Frontend Support Dashboard to Gatsby (Documentation) from Bill's personal account

**Comment by jhonnyoddball** [comment]
[PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/618) created

**Comment by billfienberg** [comment]
Jhonny, nice job on https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard. 

![image](https://user-images.githubusercontent.com/6130520/118840506-152b7080-b88d-11eb-9854-1063cdac586d.png)

@timwright12, is it safe for me to delete the old dashboard? 

### Additional Information

Since the dashboard started out as a prototype, I never implemented auth and/or handled problems from rate limiting. 

>For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests. - https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting

If the dashboard usage starts going up significantly, you might start hitting that rate limit. If you don't have a ticket for it already, you might want to add a ticket to the backlog for auth and/or handling rate limit errors.

**Comment by timwright12** [comment]
Closing this out, the [dashboard has been released ](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard)and teams have been notified:
[Slack announcement](https://dsva.slack.com/archives/CBU0KDSB1/p1621445800099600)

**Comment by jhonnyoddball** [comment]
> If the dashboard usage starts going up significantly, you might start hitting that rate limit. If you don't have a ticket for it already, you might want to add a ticket to the backlog for auth and/or handling rate limit errors.

We might need create one to handle that. We will see how it behaves and if it'll be necessary to add authentication to increase the rate limit.

Thanks @billfienberg for the heads up!
