### ISSUE TITLE
Add yarn watch option in vets-website to prevent server on 3001

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#24599]
When editing files in the content-build repo that require a watch on CSS/JS from vets-website, the current command spins up a server on port 3001.

We have a request to add an option to stop the server from running to reduce CPU usage.

Context from Slack thread: https://dsva.slack.com/archives/C01S39QMSSV/p1620764292233500?thread_ts=1620760639.229300&cid=C01S39QMSSV

**Comment by timwright12** [comment]
Updated context: https://dsva.slack.com/archives/CBU0KDSB1/p1621952783389800

**Comment by mpelzsherman** [comment]
Correction: what we need is a yarn command in content-build that just starts up a server without re-building everything.

This may become unnecesary once we address the problems with `yarn watch` in content-build.

Until then, something like this would be useful for those times when you've just run a full build and you just want to test your changes, and don't need to recompile anything:

`ys='node src/platform/testing/e2e/test-server.js --buildtype=localhost --port=3002'`

**Comment by mpelzsherman** [comment]
Is there any plan to address this, or should we just close the ticket?

**Comment by theodur** [comment]
`yarn watch` in the `content-build` repo uses the `http-server build/localhost -s -c-1 -p 3002` command to run the server while watching files. What we could do is make an alias to the `http-server ...` command in the `package.json`, so that just the server is running when that command is executed. Maybe something like `yarn serve`.

Adding a yarn command for the `content-build`'s server seems like a separate ticket than this though. Do we still want to add an option to `vets-website` for watching files without running a server?

**Comment by mpelzsherman** [comment]
It’s rare that we work on tickets that require changes to both repos simultaneously but it does happen. In those cases it would be nice to have a watch option in that website that does not start a server, but since the server runs on a separate port, it’s a very low priority.

**Comment by theodur** [comment]
After doing some testing, enabling Webpack's [Watch Mode](https://v4.webpack.js.org/guides/development/#using-watch-mode) without the Webpack dev server seemed to reduce CPU and RAM usage. I went ahead and made a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17981) for updating the `yarn watch` command to only watch for file changes without starting a server. The current behavior of the `watch` command will be replaced with `yarn start`.

I also created a PR for starting the server without rebuilding the site in `content-build`. This [PR](https://github.com/department-of-veterans-affairs/content-build/pull/381) adds a new `yarn serve` command to the repo so that we can quickly start the server on a previous build. This could have technically been a new ticket, but since it was a small lift, I thought I would just connect it with this work.

**Comment by theodur** [comment]
The two PRs related to this ticket have been merged:

https://github.com/department-of-veterans-affairs/vets-website/pull/17981
https://github.com/department-of-veterans-affairs/content-build/pull/381

Now, `content-build` has a command to start the server without rebuilding the site: `yarn serve`.
Also, `vets-website` now has a command to watch file changes without starting a web server: `yarn watch:no-server`
