### ISSUE TITLE
Downtime messages

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#24610]
Figure out how UX, Product, and Engineering can work together to deliver downtime notifications in the app.

## Questions and Tasks
- [ ] What downtime messages does VA.gov offer?
- [ ] What downtime messages can we offer? 
- [ ] etc...

## Assumptions
- [x] We can leverage content from VA.gov
- [x] We can use our established mobile alert Common Component

**Comment by patrickvinograd** [comment]
Typical use case is that we want to temporarily disable a feature, or at least warn the user that we expect a feature not to work, because the system that the feature depends on is down. 

This could be scheduled maintenance, or it could be an emergency outage. 

For the most part, this is at the granularity of major app features, like "secure messaging" or "profile" - we don't expect to want to disable only a subset of secure messaging. One exception is claims+appeals, where claims and appeals are housed in two different systems, so one might be down but not the other. Question for Product - do we want to handle those individually, or just disable the entire claims feature if one or the other is down?

There is an API in vets-api that surfaces this information. In addition to the name of the dependency that's experiencing an outage, we also have information about the duration of the outage - so we can say e.g. "appointments will be unavailable from 8PM to 2AM ET" or similar. 

I will provide:
- the list of systems we can set maintenance windows for, and the app features that those map to
- screenshots of a couple of downtime alerts in staging.va.gov

From a UX perpsective my hypothesis is that:
- if we do nothing, users get frustrated by trying a transaction and getting errors, when we could instead warn them in advance.
- we also don't want to totally hide a feature during a downtime, because that's confusing - "where did my button go?"
Instead we want to provide helpful visibility into the state of the service, and an expectation of when it might work again. This is the approach VA.gov takes so there's some grounding in UX/research there, but of course happy to let the UX process play out in thinking through the solution here.

**Comment by patrickvinograd** [comment]
Here are two screenshots showing how the downtime notifications are presented on VA.gov. There is a shared component but not all apps within VA.gov use it so verbiage varies. 

First one shows up within the Profile screens when the service that provides military service history info is unavailable:  

![Screen Shot 2021-05-14 at 4.39.33 PM.png](https://images.zenhubusercontent.com/59ca8f33b0222d5de4793559/b627e744-fd82-42f2-877e-d0ba356b46b9)

Second is on the caregiver application when the service that accepts those applications is down:

![Screen Shot 2021-05-14 at 4.48.34 PM.png](https://images.zenhubusercontent.com/59ca8f33b0222d5de4793559/46a77565-6214-4a6d-9169-be48d8b38531)

**Comment by msmanak** [comment]
## VA downtime Content messaging:
- https://design.va.gov/patterns/messaging-dictionary
- https://design.va.gov/patterns/messaging-error-messages
- https://design.va.gov/patterns/messaging-dictionary#system-messaging
- https://design.va.gov/patterns/messaging-dictionary#engagement-messaging

**Comment by msmanak** [comment]
## Questions/Comments

- how much of impact of backend API affect the mobile app as they do for the web?
- Is there a differentiation for upcoming maintenance that only is for the app?
- The web has over 20 different variations for the downtime and they are set per different teams building out their downtimes, do we follow theirs 100% or are we allowed to assign this to best fit the app?
- According to Danielle, the design system wording is out of date, we would need to rope her in the process.

**Comment by msmanak** [comment]
![Slice- downtime.png](https://images.zenhubusercontent.com/5faabf11b099434179a66d66/402ae801-2dbf-4517-9fd5-4f991c9eb185)

@melissa-lefevre @drjecker  the design is done but questions ^ were blockers  since so many variations

**Comment by melissa-lefevre** [comment]
Here is a simplified message that can be used as a general downtime message. ![Standard Copy 4.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/0d86adb5-7320-43e6-8320-31be02cd7c3c)

**Comment by melissa-lefevre** [comment]
Ready for FE
here is the ticket:
https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/27823
