### ISSUE TITLE
IA Feedback - Staging Review Healthcare Experience - Questionnaires (AKA: Clipboard)

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#24631]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Will the entry point within VAOS be implemented as part of the launch?  
- Confirm the change in originally planned user flows - Will there be an unauthenticated view of the questionnaire, or will they always be directed straight to the sign in? (comment left in epic)

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- There are no implemented entry points
  - The static landing page and left nav entry points must be implemented with the launch of this feature to ensure users are able to access the feature.  

**Should:**
- Categorization or organization of content/information on the page is confusing or misleading. 
  - Expired questionnaires still show in the "To do" tab, but they can no longer be completed.  I am unsure of other types of statuses that could appear here, but questionnaires should be clearly labeled and classified so users know if they still need to complete it. 
- A user flow does not provide content or navigation to help users understand where or what to do next.
  - The expired questionnaire message doesn't clearly indicate what the user should do next.  Will they need to fill this out at the appointment, is it no longer needed, should they call someone?  
  - Message provided: "Your questionnaire has expired. Your saved upcoming appointment questionnaire has expired."  

**Consider:**

**Comment by kristenmcconnell** [comment]
@mnorthuis 

**Regarding the entry point:** Our main entry point is a text message, which is ready to go. Email will quickly follow. We are piloting with literally one doctor at the Loma Linda VA, who only practices one day a week (so we are looking at ~50 patients per month to start). The landing page and left nav (thanks for calling out the left nav stuff in their ticket) are in-progress, but we don't consider it a main entry point for this pilot. Therefore, we would like to continue with the launch even if the static landing page isn't completely ready. We will make sure that the static page and left nav are completed before the pilot is expanded.

**Regarding the should:** We should have let you know to ignore this expired case. It appeared due to bad test data. It has to do with the connection between appointment date/time and appointment status. The statuses that we are showing on the To Do tab in real life will never correlate to an appointment that occurred in the past.  We don't want that use case to appear, because there is literally nothing that a Veteran can do at that point. The questionnaire isn't needed any more. In the test data, the status wasn't updated (as it would in production), when the time/date passed.

**Comment by mnorthuis** [comment]
Excellent, thank you for the response @kristenmcconnell!  I am good with moving forward without the static page or left nav option in place for launch.
