### ISSUE TITLE
Claims Integration | Request decision

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#24756]
## User Story / Task 
This is a backend task to integrate with the request claim decision endpoint. 

## Acceptance Criteria

1. Upon hitting the "Submit" button on the **Ask for your claim decision** page, make a call to the relevant endpoint to submit the claim decision 

## Note for QA
Once this story is complete, retest the following file upload tickets:
#17520

**Comment by bessgreen** [comment]
Note for QA: do not test this until the following tickets have been tested:
- #19238
- #24755

@digitalken

**Comment by digitalken** [comment]
PASS 5/21/2021 - OK on Android and iOS.  Closing.

**Comment by digitalken** [comment]
FAIL 5/25/2021 - I got an error when I requested a decision.  I only tried it once because I didn't want to use up any more decision requests since they are in short supply. (1 left).  Logged bug.

https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/25260

**Comment by digitalken** [comment]
PASS 6/2/2021 - Got the response I was expecting this time.  Closing.
