### ISSUE TITLE
VVC Past Appointments Not Displaying

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#24971]
Log into Virtual Care manager.  Change the filter so that past VCM appts displays.
Validate against VAOS.
VCM past appointments are not displaying in VAOS.  
Screenshot is of Cecil Morgan.

![PastVVCApptNotDisplayed.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/b0c2ea8e-7dda-4ca6-9872-ba36c18fab6f)

**Comment by jbalboni** [comment]
It looks like this is happening both on the refresh and in the current view, because these past VVC appointments have a FUTURE status. That seems like a bug to me, but I need to figure out if that's something they can fix or if we need to stop doing the status check for video appointments.

**Comment by jbalboni** [comment]
The feedback I got from Robbie Mason is that VVS passes through the status from their source systems (VCM and TMP), and if they don't get one, they default to FUTURE. VCM never includes a status, so those video appointments are always FUTURE. TMP may work differently, but in any case we can't treat FUTURE as a meaningful status in the FE, because it's a default that doesn't really mean anything like it does in VistA.
