### ISSUE TITLE
Quality Assurance Feedback - Staging Review - Facilities - Vet Centers

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25024]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- I tweaked the test case references for [this test case](https://dsvavsp.testrail.io/index.php?/cases/view/4791&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1071) one to be a comma delimited list of GitHub ticket IDs. If you drop the whole URL into the field then it doesn't resolve or provide live previews.  Please make sure you have setup the TestRail <--> GitHub integration per this [doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/testrail/github-integration.md).
![image](https://user-images.githubusercontent.com/52456633/119018882-986ec400-b96a-11eb-9ad0-f59e5646040e.png)

- This [report](https://dsvavsp.testrail.io/index.php?/reports/view/227) is actually the `Summary for References (Defects)` does not appear to provide a list of defects discovered by your test plan. Please provide a `Summary (Defects)` report in the future.
![image](https://user-images.githubusercontent.com/52456633/119019751-82153800-b96b-11eb-9adf-2ddb48c0cb6c.png)

- There appear to be two failing test cases in IE11, but I do not see the defects linked to the failing tests.
![image](https://user-images.githubusercontent.com/52456633/119019960-b2f56d00-b96b-11eb-89a5-57101d3e14a3.png)

Please use the `defect` field to link to the GitHub issue that was created as a result of the failing test case.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
* Provide link(s) to defects discovered during testing. Are they all resolved?

**Should:**
* The image of the facility is not correctly loading for me on the preview site -- 

> \<img class="facility-img" src="http://prod.cms.va.gov/sites/default/files/styles/3_2_medium_thumbnail/public/2021-04/Vet%20Center.jpg" alt="The entrance to the Escanaba Vet Center" title="" width="480" height="320">

![image](https://user-images.githubusercontent.com/52456633/119021069-fd2b1e00-b96c-11eb-83ac-050e4e62f863.png)

* The `Counseling services` section mentioned in TestRail case C4791 does not appear on the preview-prod instance. Determine whether or not this section should be present.
* In the second to last step of TestRail case C4792, the Facility Locator is not opened in a new tab as expected. Determine is this behavior is acceptable.

**Consider:**
None

**Comment by mmiddaugh** [comment]
Thank you for your feedback. I had not previously filed issues against the known component defects observed in IE-11. They are now available on our board to connect to sitewide issues for tracking: 

- Vet Center accordions do not have borders in IE-11 #25102
- Back to top component is not displayed in IE-11 #25103

Thank you for reporting the missing Counseling heading - it had disappeared between my testing and your review. Calling it out during our review alerted us to the problem which had been caused by a data change on the CMS side. The issue has been resolved. 

The absence of images in the preview server was also reported in the staging review request issue #24175. This is attributed to the preview server, not to any bug on the front end. 

Link to FL from Vet Center page opens in the same tab #25104 - we will return to this issue in the future to determine if this behavior is acceptable.
