### ISSUE TITLE
Attachment file size is empty in reply/compose POST response

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va.gov-team#25032]
## Issue Description

When a new message or reply with attachments is POSTed, the response body includes info about the attachments including file name, etc.  The file size that is coming back with this response is 0 which needs to be fixed.  This value doesn't seem to be used by the mobile app at the moment so this issue is probably not launch critical.

## Acceptance Criteria
- [ ] Attachment file size is included in response body properly

**Comment by Teesh** [comment]
Was able to determine that at some point in the process, the uploads variable has a calculated non-zero size in vets-api

**Comment by Teesh** [comment]
Was also able to determine that the file size works properly on received messages that contain attachments

**Comment by Teesh** [comment]
The issue is originating with the MHV API, not vets-api. A patch has been put in place to hide the zero size issue wherever it shows up for the moment. It can be revisited and escalated at a later date as it is low priority and does not affect any actual calculations of attachment size within vets-api

**Comment by Teesh** [comment]
Tests were added and the PR was merged

**Comment by Teesh** [comment]
Tested successfully on Staging
