### ISSUE TITLE
Accessibility Feedback - Staging Review - Virtual Agent Chatbot

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#25113]
This will be the epic to capture accessibility tickets (one per issue) for the Virtual Agent Chatbot staging review: https://github.com/department-of-veterans-affairs/va.gov-team/issues/24884

**Comment by 1Copenut** [comment]
@ianpsant & @shiragoodman The accessibility staging review is now complete. All issues entered.

**Comment by ianpsant** [comment]
@1Copenut For the two Must Haves, we've identified them as issues we need to address with Microsoft. The remaining additional 508 issues, we still intend to review, but after our Study release or perhaps during. We still want to look at these because we want to understand for PVA what's within our purview versus what we need Microsoft's intervention. Feel free to leave open and we'll leave similar comments depending on what we find out.

**Comment by shiragoodman** [comment]
hi @ianpsant. @1Copenut is out of the office this week. Thanks for the follow up on Microsoft. You can close this ticket, but please do not close the child tickets linked above until the issues are resolved. Thanks!

**Comment by ianpsant** [comment]
For reference, filed these corresponding tickets with Microsoft:

- https://github.com/microsoft/BotFramework-WebChat/issues/3933
- https://github.com/microsoft/BotFramework-WebChat/issues/3934
- https://github.com/microsoft/BotFramework-WebChat/issues/3935
- https://github.com/microsoft/BotFramework-WebChat/issues/3936
- https://github.com/microsoft/BotFramework-WebChat/issues/3937
- https://github.com/microsoft/BotFramework-WebChat/issues/3938
- https://github.com/microsoft/BotFramework-WebChat/issues/3939
