### ISSUE TITLE
Trace a specific user's authentication and subsequent API requests via log messages

### ISSUE THREAD

**Issue by ayushchak** [department-of-veterans-affairs/va.gov-team#25118]
Acceptance Criteria:

Given an ICN+SecID and a timeframe, engineer should be able to query logs and find:
- [ ] The initial authentication event for the user
- [ ] Any subsequent token refresh/introspection actions
- [ ] All API requests performed using those tokens

**Comment by ambikaroos** [comment]
@jjulian to follow up

**Comment by jjulian** [comment]
per @patrickvinograd - not launch critical

**Comment by patrickvinograd** [comment]
We're half-way here on this item. We are logging the user_uuid of each mobile request, which is a hash of (icn+secid), so is probably the most important thing.

But we don't log any info when the session is established, which seems like a gap. And we don't log the obscured token value on each request (for some reason it does not show up even though we are using the shared Instrumentation concern - probably because the mobile APIs are not using the cookie store, so`session` variable is unset. 

I don't think the obscured token is essential, but we should log something in SessionManager when a new session is established, possibly including the iam_transaction_id if available so we can tie back to an authentication event.

**Comment by patrickvinograd** [comment]
I'm also wondering if we want to log the secid on session establishment - it's linkable PII, but would be helpful in tracing transactions for users since it's a common identifier used by IAM.
