### ISSUE TITLE
Research HTML support for calendar invite descriptions

### ISSUE THREAD

**Issue by jbalboni** [department-of-veterans-affairs/va.gov-team#25157]
We should research how we can use HTML descriptions for calendar invites, in order to provide easy to read links back to VAOS.

Background: ics file descriptions don't support html, but there is an X-ALT-DESC field that some clients support for HTML descriptions. We may want to use this field to get some link formatting

Email clients to research:

Gmail
Apple Mail (iOS and Mac)
Outlook
Microsoft's online mail client

Others?

Questions to answer about each client
- How does it handle urls and/or HTML in the description currently?
- Does it support X-ALT-DESC?

**Comment by vbahinwillit** [comment]
Research results:

I have tested the .ics file format in the following calendar applications:

* Chrome (Desktop and Android)
* Apple Safari (Desktop, iPhone, iPad)
* Outlook (on the web)
* Outlook 365 (connect to Microsoft Exchange Server)

Chrome and Safari (Desktop, iPad) calendar clients rendered the following URL (https://va.gov/health-care/schedule-view-va-appointments/appointments) as a clickable link when viewing the appointment.

**Safari (iPhone)**
I was unable to log into staging from my iPhone

- Failed to load resource: the server responded with a status of 503 (Service Unavailable)
- https://staging-api.va.gov/vaos/v0/appointments?start_date=2021-04-25T05:00:00.000Z&end_date=2022-06-24T05:00:00.000Z&type=va
- https://staging-api.va.gov/vaos/v0/appointments?start_date=2021-04-25T05:00:00.000Z&end_date=2022-06-24T05:00:00.000Z&type=cc
- https://staging-api.va.gov/vaos/v0/appointment_requests?start_date=2021-01-25&end_date=2021-05-25

**Outlook (on the web)**
Outlook (on the web) did not render the URL from the popup as a clickable link. However, the URL was rendered as a clickable link when editing the calendar event.

**Outlook 365 (Microsoft Exchange Server)**
Outlook 365 displays the URL as a clickable link when editing the calendar event. However, I don't know how many users actually use this option since Outlook 365 connected to an Exchange server is typically used by organizations and the assumption here is that the appointment is added to the user's personal calendar.

**Assessment**
Looked into X-ALT-DESC. Anything starting with an 'X' is custom. In this case, X-ALT-DESC is supported by Microsoft only and offers very little benefit over using "DESCRIPTION". So my recommendation is to just use the "DESCRIPTION" tag vs. trying to code for specific browsers. I have not been able to find anything that provides the functionality of using an html anchor tag. The worst case scenario is the user has to cut and paste the URL into their browser.

**Comment by jbalboni** [comment]
@vbahinwillit That seems reasonable to me. The staging issue with Safari might have been a temporary thing, we were having trouble with some of those services.

@outerpress Does this make sense to you? It seems like including urls directly in the invites for the most part makes them clickable, and html support is pretty limited outside of some Outlook versions.

**Comment by outerpress** [comment]
@jbalboni I'm not 100% sure I understand, are y'all basically saying:
- Most users will get a clickable link
- Some will have to copy the text and paste the link in their browser

If so then yep that's fine, as long as the link is available in some way or another.

**Comment by jbalboni** [comment]
@outerpress I think we're on the same page. We have to display the url where we want them to go. It will most of the time be clickable, but in some clients you will have to copy and paste. Displaying an actual link like "Click here to view appointment" or something isn't supported, except in some MS email clients.

**Comment by outerpress** [comment]
> Displaying an actual link like "Click here to view appointment" or something isn't supported

Oh gotcha, that's the part I was missing. So in the [copy docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/calendar-ics-copy.md#va-in-person) we show linked text, like:

`[Sign in to VA.gov ](https://va.gov/health-care/schedule-view-va-appointments/appointments/)to get details about this appointment`

We can't do that, but we can show the full URL like:

`Sign in to VA.gov to get details about this appointment: https://va.gov/health-care/schedule-view-va-appointments/appointments/`

And the URL will sometimes show as a hyperlink, other times as text depending on the mail client?

Our URLs are pretty easy to read and not super long so yep, that's fine.

**Comment by jbalboni** [comment]
@outerpress Yep, that's correct
