### ISSUE TITLE
Discovery: Terraform fmt, plan, and apply

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2519]
@jbritt1 please fill in with more detail.

**Comment by jbritt1** [comment]
### Placeholder, will work on this more tomorrow ### 

# RFC: _title_

- Date: _YYYY-MM-DD_
- Related Issue: _git/zenhub issue if applicable_

## Background
_Explain the current state of the feature._

## Motivation
_Why do we want to change the current implementation? What problem(s) does the change solve?_

## Design
_Explain the proposed changes in enough detail so that a team member with working knowledge 
of the project could implement the change themselves. Bonus points if this is easily mappable
to user stories or specs._

## Risks
_What are the risks of the proposed changes?_

## Alternatives
_What other alternatives solutions were considered, why weren't they chosen?_

**Comment by jbritt1** [comment]
@wyattwalter suggested perhaps using the RFC template which i can do here and then copy over to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering/request-for-change once complete

**Comment by jbritt1** [comment]
I would say the "discovery" portion of this task could be closed at this point if you agree? Seems like we know which option we are going with as a result of the discovery efforts in #2928.
