### ISSUE TITLE
FSR- Verify all input values

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#25242]
Verify all input values being calculated is correct.  Need to include proper calculation logic. Confirm with subject experts. 

Acceptance criteria: 

Make tickets for front end after speaking with subject experts if needed.

**Comment by rileyorr** [comment]
@LindaLi123 I'm currently blocked on this ticket because of the issues with the endpoint that Leah brought up in Slack yesterday. The form breaks when I proceed to the form's debt selection page (see screenshot below). I attempted with both user 1 and user 228. I commented in the thread asking if staging will be updated with mocked data today, If yes, I can complete this ticket before the sprint ends; otherwise it will fall out.

![fsr-broken.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/e0acb77d-be6a-4324-bf26-7e3d220aab04)

**Comment by rileyorr** [comment]
Update: A PR was merged to display mocked data, but I'm still unable to get into the form. Reached out in the thread and Kevin is currently looking into it. Might potentially be an outage.

**Comment by rileyorr** [comment]
Was finally able to complete this ticket now that staging is working again!

**Monthly income includes the following inputs:**
- Veteran's gross monthly income
- Veteran's social security payments
- Veteran's other income
- Spouse's gross monthly income
- Spouse's benefits (disability comp)
- Spouse's benefits (education)
- Spouse's social security payments
- Spouse's other income

**Taxes and expenses include the following inputs:**
- Veteran's payroll deductions
- Spouse's payroll deductions
- Housing expenses
- Food expenses
- Utilities
- Installment contracts & other debts
- Other living expenses 

The logic of deducting the total expenses from total income works correctly. I cross referenced with the paper form and the values correspond to those on the form. We consolidated 14a-e in the payroll deduction list loop so those fields aren't standalone, but that info can still be added to the form. 

Bugs found:
- The Veteran's benefits aren't added to the total income
- Items can be added to list loops without including an amount
- Went back into the FSR and saw that the real estate amount was listed as `$NAN$` instead of a dollar amount. 

I'll write tickets for these bugs and link them in this ticket.

**Comment by rileyorr** [comment]
Tickets:
- [Adding Veterans' benefits to the financial overview's monthly income](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27636)
- [Payroll deduction list loop error handling bug](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27638)
- [Real estate's estimated value bug](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/27640)

Moving this ticket over to validate!
