### ISSUE TITLE
[Content review] VAOS direct schedule flow

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25326]
Request content review of the direct schedule flow for any improvements that can be made.

Comments can be added to the flow screens here: https://adhoc.invisionapp.com/overview/Copy-Review---Direct-Schedule-Flow-ckp5yqgss15tm016u51kuea1t/screens

## 1 - SLP
![1 - SLP.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/1b24a4d9-5ab4-4315-a912-73cf9502c535)

## 2 - homepage
![2 - homepage.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8d89feb9-b8e2-476c-99c8-29d352bd656c)

## 3 - type of care
![3 - type_of_care_page.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/e56fab0b-35e5-4912-8f6f-02e5c664ef1b)

## 4 - facility
![4 - facility_page.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f4e6d2bf-8b2c-4646-88c0-9f3b29aed8de)

## 5 - clinic
![5 - clinic_page.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/8f693b59-0a1b-41f6-9ea1-b593f1efaf0d)

## 6 - preferred date
![6 - preferred_date_page.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/4a84e308-1496-43e6-900d-2a0929154a79)

## 7 - calendar
![7 - calendar.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/1f6c74f8-6cd9-4647-ad54-1fa767d93432)

## 8 - reason
![8 - reason_page_selected.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/f4dc09ed-96f7-4ae4-b70d-fc466f489067)

## 9 - contact
![9 - contact_page.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/0a718f53-3906-43ba-997c-09bc872584be)

## 10 - review
![10 - review_page.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/766aaec2-4a20-439e-8bbb-99ef1497cd7b)

## 11 - confirmation
![11 - confirmation.png](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/0a3ec777-b4fe-4408-aa55-11bb19b4f286)

**Comment by peggygannon** [comment]
@laurenernest Hi, there. I'm not able to access the Invision link above. Can you invite me to this document?

**Comment by laurenernest** [comment]
@peggygannon give it a try now

**Comment by laurenernest** [comment]
Backup plan! The screenshots have been added to the description. I added them in the order of the form flow and included page numbers with headings for ease of reference.

**Comment by peggygannon** [comment]
Hello, @laurenernest @outerpress please see below VAOS direct schedule content recommendations. Most of my recommendations are to make the H1s and intro content more succinct  and less wordy. Please let me know if you have any questions! 


Screen 3
Update intro line to: What care do you need?, to avoid repeating the H1

-----

Screen 4

NEW H1: Choose a VA location 
UPDATE intro line to: Below is a list of VA locations where you're registered that offer primary care appointments. Locations closest to you are at the top of the list. 

------

Screen 5

NEW H1: Choose a VA clinic
Can we update the intro line to include the name of the VAMC rather than have it listed below the intro line? 

So, like this: 
UPDATE intro line to: In the last 24 months you’ve had a primary care appointment at the following {name of VAMC} clinics:
Choose a clinic below or request a different clinic for this appointment.


-----

Screen 6
I'm not sure we need the additional component question "Why are you asking me this?" I think we can incorporate that content into the intro so users don't have to click through to learn this information. 

See recommendation: 

NEW H1: Choose a date 
Tell us the earliest day you’re available and we'll try find the date closest to your request. 

Choose a date within the next 13 months for this appointment.

-------

Screen 7

This calendar screen seems duplicative to the one before when we ask users to pick a date. Why are we asking users to pick a date again?

Is this screen showing  them the *earliest* date we could find for them based on their prior input?  
If so, then I will offer up some content recommendations to make that more clear. Please advise


------

Screen 8

NEW H1: Choose a reason for this appointment 
UPDATE intro to: Let us know why you’re making this appointment. 

Make the 1st radio button a full sentence like the other options.  
And add periods at the end of each of them 

This is a routine or follow-up visit.
I have a new medical issue. 
I have a concern or question about my medication. 
My reason isn’t listed here. 



In the urgent alert message, please change "press" to "select" 
The line should read: Call the Veteran Crisis hotline at [800-273-8255] and select 1

------

Screen 9

NEW H1: Confirm your contact information
UPDATE intro to: This is the information we’ll use to contact you about your appointment. You can update your contact information here, but the updates will only apply to this tool.
To update your contact information for all your VA accounts, please [go to your profile page].

Times should be rendered in this format {hour:minute) like this: 8:00 a.m. (not 8 a.m.)

------

Screen 10

NEW H1: Review your appointment details
UPDATE introduction to: Please review the information before confirming your appointment. If you need to make any changes, click Edit to go back to the screen where you entered the information. If you make any updates, you’ll need to go through the steps again to schedule this appointment. 

------

Screen 11

Confirmation screen
I recommend updating this link [Make appointment] TO [Schedule another appointment]

**Comment by laurenernest** [comment]
@peggygannon Thanks! We can definitely run this through accessibility :)

Screen 6 was set up because of data that needed to be collected for reporting the difference between the 'Preferred date' and the date the appointment was performed. For now, we have to keep both this and the calendar.
> This calendar screen seems duplicative to the one before when we ask users to pick a date. Why are we asking users to pick a date again?

**Comment by peggygannon** [comment]
HI, @laurenernest @outerpress I'm starting my CC staging review for VAOS homepage refresh and I don't see any of the above recommendations or the ones I posted in [this ticket](https://app.zenhub.com/workspaces/vaos---productdesign-5fff340c2d80a4000fb6f69c/issues/department-of-veterans-affairs/va.gov-team/23018) in the staging link. 

I wanted to check in to see if there are recommendations you've opted not to incorporate? I don't want to re-submit any recommendations you've decided to not implement. 

I just want to be sure the VAOS homepage is ready for my Collaboration Cycle review?

**Comment by laurenernest** [comment]
@peggygannon 
cc @outerpress 

Screen 7 - I realized I didn't answer this question. The calendar shows the month based on the prior input and there could be available slots earlier than the input date. Given we have to keep screen 6 & 7, let me know what you recommend.

> Is this screen showing them the earliest date we could find for them based on their prior input?
If so, then I will offer up some content recommendations to make that more clear. Please advise

---

Screen 11 - I don't see a "make appointment" link. Should we update "New appointment" to "Schedule another appointment"?

> Confirmation screen
I recommend updating this link [Make appointment] TO [Schedule another appointment]

**Comment by peggygannon** [comment]
Hi, @laurenernest and @outerpress Here is a recommendation for screens 6 and 7. Please let me know if think this would work and/or if you have any questions: 

Screen 6 (preferred date) recommendation:  
NEW H1:  When do you want to schedule this appointment?  
Tell us the earliest day you’re available and we'll try find the date closest to your request.
Choose a date within the next 13 months for this appointment.



Screen 7 (calendar) recommendation: 
NEW H1: Choose a date and time 
Please select an available date and time from the calendar below. Appointment times are displayed in Eastern time (ET).

**Comment by laurenernest** [comment]
Those should work! Thanks!
