### ISSUE TITLE
Revisit content-build watch command process

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#25379]
## Description

In content-build the current yarn watch command reruns the entire build, which takes a long time to execute. We need to look into how we can fix this behavior to improve VFS workflow.

## Definition of Done

- [x]  The `yarn watch` command doesn't trigger a rebuild of the entire site.

## What we have tried already

We have looked into using [metalsmith-watch](https://www.npmjs.com/package/metalsmith-watch) in conjunction with [metalsmith-serve](https://www.npmjs.com/package/metalsmith-serve). The seem to work as intended, however out setup seems to be very customized and [metalsmith-watch](https://www.npmjs.com/package/metalsmith-watch) is still triggering a full rebuild of the site.

## Some Ideas

- Can we remove some steps from the build process that may not be needed when a watch is running?
- Can we prevent the build directory from being deleted in the first step and only regenerate the changed templates? Even if that means passing an array of letters into the command: `yarn watch --templates c,r,m`
- Can we only rebuild the changed templates and partials?

**Comment by mpelzsherman** [comment]
Thanks for looking into this!! This is a very high priority for the Facilities team.

**Comment by mpelzsherman** [comment]
Hi @theodur . Any updates on this one?

**Comment by theodur** [comment]
Hi @mpelzsherman, this one is currently in progress. I have a solution that should reduce the rebuild time when running `yarn watch`. I'm cleaning up a few things, but should have a draft PR ready by today or tomorrow.

**Comment by mpelzsherman** [comment]
Hi @theodur . Any updates?

**Comment by theodur** [comment]
@mpelzsherman  Here's the [PR](https://github.com/department-of-veterans-affairs/content-build/pull/337) for the updates to watch command process.

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/content-build/pull/337) with updates to the `watch` process has been merged ✅.

As a side note, our `watch` process has not, and currently does not, watch changes made to liquid filters. This is because almost all liquid filters in the content build repo live in one file, [liquid.js](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/filters/liquid.js). This makes it difficult to know which filter was updated. Some of the work planned for incremental builds is looking at separating filters into individual files. In the future we can leverage this work in the `watch` process, as this would make it much easier to know which filter was updated, and we can figure out which layouts need to be updated from the file name of the filter. See the [discovery on strategies for mapping templates to pages](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26198) for more information.
