### ISSUE TITLE
Add "new" label to vaccine option

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#25383]
## Description
Vaccine scheduling has moved to sustainment and has been added to the type of care list. Add a "new" label next to the radio option.

---

## Acceptance Criteria
- [ ] On the type of care page, the "new" label appears next to the COVID-19 vaccine option
- [ ] DESIGN - Designs match the specs

### Design Assets
- [Mobile spec](https://www.sketch.com/s/9212a416-f312-44b3-bdf2-82a8c60bcfb2/a/xr2KAZ8#Inspector)

## Definition of Done
- [x] All acceptance criteria are met

**Comment by laurenernest** [comment]
Reopening for validation

**Comment by laurenernest** [comment]
Looks good! Closing ticket.

![Screen Shot 2021-06-23 at 8.32.12 AM.jpg](https://images.zenhubusercontent.com/5f7dd2dad6b9a9301bbab94e/c49cca60-e4ec-46d3-84eb-e9c11f1e45e7)

**Comment by outerpress** [comment]
I just tested this with VoiceOver and it reads COVID-19 vaccine just fine, but then spells out the letters "N-E-W" without a pause, where it should pause then speak the word "new". 

I think ideally it would speak "New type of care" then pause then "COVID-19 vaccine", but for now just speaking the word "new" instead of spelling it should be fine.

Otherwise looks great to me too!

**Comment by laurenernest** [comment]
Good callout! I've created #26494 to address.
