### ISSUE TITLE
Design Feedback - Midpoint Review [Authenticated Experience, Notification Preferences]

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#25459]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Does the page scroll back to the top after the user clicks [save](https://preview.uxpin.com/bb87d0fa61a32938a47e7bcdc836db235ab77576#/pages/138069327/simulate/sitemap?mode=i)? I am concerned the user will not see the success message if it doesn't. 

## Feedback
**Must** = the feedback must be applied
- Change the [error alert](https://design.va.gov/components/alertboxes#error-alert) icon to red on all error alerts
![Screen Shot 2021-06-04 at 1.12.30 PM.png](https://images.zenhubusercontent.com/5d93fa1ea615ef00010992b0/64379e15-88e0-49b5-956b-a80b16b52389)

**Should** = the feedback is best practice
- Add a link to the actionable text. In this case, you would navigate the user directly to the place where they can add their email address. Do this for all actionable text
![Screen Shot 2021-06-04 at 1.14.33 PM.png](https://images.zenhubusercontent.com/5d93fa1ea615ef00010992b0/1b4ec138-8ed6-496f-b1de-eaba9107e631)

**Consider** = suggestions/enhancements
- You could use a [background-only alert style](https://design.va.gov/components/alertboxes#background-color-only) for any immediate feedback instead of the standard alert styles. Background alert styles are mobile-friendly.
![Screen Shot 2021-06-04 at 1.17.29 PM.png](https://images.zenhubusercontent.com/5d93fa1ea615ef00010992b0/142fa3ec-8723-41d1-bf9b-a1ed972c2d75)

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by andaleliz** [comment]
Hey design team, thanks for the feedback and thank you @ajakabcin for bringing this ticket to my attention.  

We discussed this feedback in the review - will document what we talked about here:
>Change the error alert icon to red on all error alerts

Updated in mock-ups

>You could use a background-only alert style for any immediate feedback instead of the standard alert styles. Background alert styles are mobile-friendly.

The alerts reflected in this prototype are consistent with what we do throughout profile right now. I totally agree with your feedback (including the comments about placement we discussed in the meeting that aren't captured here), but our team will address alert UX as an overall profile improvement as a separate effort, rather than just making the improvements in this one section of profile. I created a [ticket in our backlog](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25820) to ensure this doesn't get lost.

>Add a link to the actionable text. In this case, you would navigate the user directly to the place where they can add their email address. Do this for all actionable text

Updated in mock-ups
