### ISSUE TITLE
Local builds do not re-download cached assets

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#25461]
# Background
Downloading drupal assets is unaccceptably slow in our local environments. It can take 30 minutes or more and often fails due to the SOCKS proxy connection required.

# Acceptance Criteria
Keep Drupal assets in local cache. Do not delete cache between builds. Do not re-download assets if already in cache. If desired, we can add a yarn command to clear the asset cache.

**Comment by timwright12** [comment]
Adding more context, our goal here is essentially to wrap https://github.com/department-of-veterans-affairs/content-build/commit/35f278514816622ce148368c5cf64ad00e868ac8 in an env variable so it only runs on localhost. We'll also need to confirm Review instances, since they run a localhost build as well

**Comment by mpelzsherman** [comment]
Hi there @k80bowman! This is the #1 priority item on our VSA [wish list](https://docs.google.com/spreadsheets/d/1MKqJVkJOeiGciI6kAi1oEfgHyX1v3IK-2L1408y0jPM/edit#gid=0). Please LMK if you have any questions about it!

**Comment by k80bowman** [comment]
I'm not sure there are any changes needed for this anymore. @theodur [made a change](https://github.com/department-of-veterans-affairs/content-build/pull/216) a few weeks ago that includes checking the local file system to see if an asset file exists before re-downloading it. So the assets are no longer deleted during the build process and only assets that aren't already downloaded locally are downloaded during the build process. The relevant check is on [this line](https://github.com/department-of-veterans-affairs/content-build/blob/f1950f5119f37f1846915dec66855124fac0bcdf/src/site/stages/build/plugins/download-drupal-assets.js#L117) in `download-drupal-assets.js`.

@mpelzsherman would you please check the current behavior for `yarn build` and see if it fulfills your requirements for this request?

**Comment by mpelzsherman** [comment]
@theodur 's PR does not address the issue. When we run `yarn build --pull-drupal` to get fresh drupal data, all of the assets are deleted from the local filesystem (we do  an`rm -rf .build`).

My original [PR](https://github.com/department-of-veterans-affairs/content-build/pull/205) keeps the assets in a separate folder (`.drupalAssets`) so they aren't deleted between builds. This is the key to addressing the asset download issue.

**Comment by mpelzsherman** [comment]
BTW my team runs `yarn build --pull-drupal` multiple times per day.

**Comment by k80bowman** [comment]
Thank you so much for the clarification! It's good to know that you are wanting to maintain assets while using the `--pull-drupal` flag. Are there any other considerations here I need to be aware of?

**Comment by mpelzsherman** [comment]
Just that we need to make sure this behavior does not occcur in production builds, because it caused major problems previously.

**Comment by k80bowman** [comment]
Oh yes, absolutely. Thank you.

**Comment by k80bowman** [comment]
[PR](https://github.com/department-of-veterans-affairs/content-build/pull/295) for this is ready for review! I found out that Theo's work had also included saving the assets to the .cache directory, so the solution I landed on was adding a flag that can be used alongside `--pull-drupal` in order to keep and then use those assets from the .cache directory. This way it should give you the option to use the cached assets locally, but it shouldn't affect review instances or staging or prod.
