### ISSUE TITLE
Update yarn build on localhost to pull drupal cache

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#25512]
The current yarn build behavior will pull new data from drupal if a .cache directory is empty. We would like to update this behavior on localhost builds to use fetch-drupal-cache instead to speed up the build time for engineers.

All other environment builds should stay the same.

[Read more context in slack](https://dsva.slack.com/archives/C01512KN35G/p1622641081088300?thread_ts=1622638479.086600&cid=C01512KN35G)

**Comment by timwright12** [comment]
Cache upload example: https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/content/vagovdev_800ac7712de91ca3d537f4de4635faa2.tar.bz2

**Comment by mchelen-gov** [comment]
[readme](https://github.com/department-of-veterans-affairs/content-build#building-static-content_ currently states:
> `yarn build` (`--pull-drupal` runs by default when cache is empty)

so it would be nice to default to `yarn fetch-drupal-cache` instead for perf & SOCKS dependency reasons

however as long as `yarn build` still needs live SOCKS connection for asset download (step 49) then `yarn fetch-drupal-cache` might not really be the bottleneck

**Comment by theodur** [comment]
Locally, `yarn build` doesn't need SOCKS access for [downloading assets](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/plugins/download-assets.js#L71) if a symlink is [created](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/index.js#L78) to the `vets-website` directory. This is how review instances work as well since they don't have access to the SOCKS proxy.

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/content-build/pull/348) for this ticket has been merged. `yarn build` now defaults to fetching Drupal cache from S3, rather than pulling the content from the Drupal API. One thing to note is that the script responsible for fetching Drupal cache ([drupal-aws-cache.js](https://github.com/department-of-veterans-affairs/content-build/blob/master/script/drupal-aws-cache.js)) fetches the dev environment's content by default for local builds. If this is an issue down the road, we can look at having it fetch another environment by default.
