### ISSUE TITLE
Design Feedback - Midpoint Review [Authenticated Experience, Preferred Facilities] 

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#25514]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Looks good! No UI feedback at this time.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Product Support board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review**: VFS PM, yourself (optional)

**Comment by rtwell** [comment]
Reading this text:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/775d4245-49b0-42d8-95ed-dd3eec2b8840)

It's not clear to me what goals this page helps a user accomplish. How does editing this list help a user? What does it do for them? One suggestion (that might help explain my question) might be to replace the text "This list is in alphabetical order" (or add a header above this text) that says something like "Select your primary facilities" or "Select the facilities you want to schedule appointments" — something that kinda explains the usefulness of editing this list. 

Secondly, the additional info component, when expanded reads:

![image.png](https://images.zenhubusercontent.com/5568d4774f7a08fbb7f30688/7cef0ad6-7d22-4f9f-9dd4-f8c079ddf7b7)

Because of the ambiguity of the above, this text is confusing. It might be clearer if it were task/user driven, something like (and this communicates the gist) "Don't see a facility you're looking for on this list? The facility may not offer online appointments or you might not be registered there. Call the facility to make an appointment. If they offer online appointments, you'll see them on this list after you register there for care. Find a VA location {link}"

**Comment by andaleliz** [comment]
Thanks for this feedback! I'll get together w/ Danielle and see how we can improve this. In our usability study, people noticed the link but really didn't read any of the text above the list.

I'd like to leave this ticket open until we have a resolution on this. I agree it needs improvement.

**Comment by andaleliz** [comment]
I don't think we'll build this section of profile, but added MHV discovery as a blocker in case we learn something that suggests we do need this. If we move forward, we'll still need this ticket.

**Comment by andaleliz** [comment]
Closing this out, per Kevin we are putting this work on ice.
