### ISSUE TITLE
Biometrics - FaceID on iPhone - App can hang if FaceID is changed while logged in

### ISSUE THREAD

**Issue by digitalken** [department-of-veterans-affairs/va.gov-team#25538]
## What happened?
I found two ways that the app can hang if the users modifies the FaceID settings while the user is logged in to the device.

1. Observed with iPhone XR set up for FaceID:  While logged in to VA app, turn off faceID on phone in settings.  Return to VA app and find that you are stuck on a splash screen and can not get past it with no explanation or guidance.  Going back into settings and turning on faceID will allow you to get past the splash screen.

2. Observed with iPhone XR set up for FaceID:  While logged in to VA app, navigate to profile > settings and toggle Face ID off.  Shut down app then restart to make sure you are able to get in. (Found that I had to use my phone lock code to get in.)  Turn off Face ID in phone settings.  Turn on Face ID in VA app.  Shut down app and launch again.  User is stuck on the splash screen with no explanation or guidance.  The only way to proceed is to turn face ID back on in the phone settings.

## Specs:
- Device: iPhone XR with FaceID as needed.

## Steps to Reproduce
See above.

## Desired behavior
If a user is logged into the app, disables biometrics in their device's settings, and returns to the app, the following should happen:
1. User should be logged out of the app, and it should display the unauthenticated Home screen
2. Log in flow should exclude the Biometrics Opt In page
3. When the user logs in, the Settings page should exclude the biometrics ListItem

## Acceptance Criteria
See desired behavior

## Bug Severity
- 3 - Medium

## Linked to Story
n/a

## Screen shot(s) and additional information
![image.png](https://images.zenhubusercontent.com/5f6a83c84093730d05b5cee6/3df3c2e6-8138-4ba8-a425-771376f52abc)

**Comment by kxiao133** [comment]
Current PR will prevent user from being stuck on splash screen, but I was not able to find a way to check when the device faceID settings are on/off, so that fix does not consistently hide the toggle bar/biometrics screen. 

Hopefully a future PR will be able to properly update that store variable biometricDisabledInDeviceSettings. So far I only set it to true in the specific case where the user re-opens the app when faceID is on in the app, but off in the device settings.

**Comment by kxiao133** [comment]
^John's feedback for how to go about fixing the bug:
"The core issue of the bug is we can be in a state where the user is configured to log in with biometrics, but the device has them disabled through their settings. This manifests in a rejected promise by the Keychain.hasInternetCredentials (presumably any of the keychain credential calls would behave the same way) call which is currently the only way we know of to check whether biometrics is enabled or not on the device (our current check only includes the device capabilities, not whether they’re disabled or not).
To get around the immediate issue we can include running the hasInternetCredentials call as a part of the deviceSupportedBiometrics check (or as an additional check wherever we make that call) and ensure canSaveWithBiometrics is false for this use case, forcing the user down the path as if biometrics is not supported by their device.
What is needed is a more robust way to check if the app can actually use the biometrics the device is capable of (IE, did they turn them off in the settings) so that the auth flow and settings can respond accordingly."
@jmarchi

**Comment by digitalken** [comment]
PASS 7/14/2021 - Works as expected in iOS.  Closing.
