### ISSUE TITLE
Corrupt Attachments after sending message

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#25539]
### Issue
Attachments are being corrupted after a message is sent. The issue was found when testing with an MHV coordinator on 5/28.  

### How issue was produced: 
- User took a photo using the camera function (jpg file)
- Image successfully attached to the message
- Message successfully sent to a triage group (confirmed by checking the triage group in the staff/provider portal)
- The image could not be opened in the provider portal. Error message: 
![m_image_picker.lib_temp_10ef6754-d1c0-47-536-f1200089 (1).png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/935b23ba-6f27-457a-b099-bc7b28f84f8b)
- The image could also not be opened in the user's SM sent folder on the app

### Expected Behavior:
- Images should be able to be seen in the provider portal and within the app user's sent folder.

### Files
The two corrupted files and the 2nd original file can be found in this SM testing folder: https://drive.google.com/drive/folders/1Zn_Re-zyJJmOoBRcnGk5fbelSGaxYJxN

**Comment by narin** [comment]
This issue has been resolved with the help of Daniel Eaton at MHV (Bylight).  This was due to MHV's API gateway not being properly configured to accept binary attachments.  The same issue was occurring on staging back in March.  I've verified the that fix is working on production using images and a PDF.  Closing out.
