### ISSUE TITLE
[Carryover] Research: Automate reporting for the 10-10CG

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25686]
## User Story

**As a** VFS Stakeholder, **I want to** view accurate reporting on 10-10CG form submissions and the errors that may occur, **in order to** monitor the success rate and address submission or upload errors.

The purpose of this issue is the research the best approach for automating some of the manual tasks for reporting on the 10-10CG so we can get better visibility into submissions and failures.

## Product goals:
- Stakeholder insight into product health
- Automate running the daily query
- Find a better long-term storage solution
- How could individuals run the report themselves?
- How can users access the reports without complicated steps?

## What do we want to know:
- By any given set of dates:
     - How many attempted submissions
     - How many went through to CARMA
     - How many were blocked by MPI
     - How many were blocked by other types of errors
- What kinds of errors are people running into?
- Trends over time

## Short-term goals
- Where does the data in Domo come from, and what does it represent? - Ming, Chris
- What are the differences between the technical (CloudWatch) logs, CARMA-reported metrics, and Google Analytics? - Mike
- Clarify terminology across reporting - what is defined as success, failure, etc? - Justin
- Update documentation to reflect current state (How do we monitor product health?) - Chris
- What are the (preferred?) dashboard-ing options for CloudWatch logs? (Grafana, Loki, CloudWatch Stats, Domo, etc) - Kevin
- What is the use case? Short-term vs. long-term? - Chris, Ming

**Comment by dnalbach** [comment]
Discussed the Loki migration with Demian Ginther of VSP in Slack today. Dev and Staging have already been migrated away from CloudWatch to Loki for querying and visualization in Grafana. Production will be migrated this quarter as well. Legacy CloudWatch data will not be migrated to Loki and will remain available in CloudWatch indefinitely. 

Grafana supports LogQL and after consideration I believe we should be able to convert the existing CloudWatch queries into LogQL queries in Grafana so that we can create a reporting dashboard in Grafana for these events after the Loki migration is completed. Since Dev and Staging are already migrated, it should be possible to generate sample events in Staging, write the LogQL queries, and create the Grafana reporting dashboard prior to the production log migration. I do not believe that sending events to Prometheus will be required since we can directly query Loki from Grafana using LogQL queries. It is also likely that few changes, if any, will be needed to the log data itself since it is already possible to determine metrics for reporting purposes from the existing log events. However, when we write the LogQL queries, we may find opportunities to refine the log events to make querying easier. Any such opportunities should be reasonably considered.

Since the historical data will remain in CloudWatch indefinitely, it will be necessary to try and fix the existing CloudWatch queries that broke in April, as that will continue to be the only data source for the historical data. 

We should end up with two artifacts at the end of this, a legacy report in the Google sheet (or similar), and a new Grafana dashboard.

**Comment by dnalbach** [comment]
Learned recently that Prometheus may be getting replaced with DataDog. This should not impact this effort as we are preferring log data in CloudWatch/Loki rather than Prometheus anyway.

**Comment by dnalbach** [comment]
Chris Dyer fixed or found workarounds for the broken CloudWatch queries used in the old report on June 24th. He was able to backfill some of the missing data and start reporting regularly again. It is a continuation of the old manual process, and should still be automated, but allowed for the continued flow of information during the interim.

**Comment by SKasimow** [comment]
@jchilders can you review the background provided in this ticket? Would like to discuss how we could automate this reporting based on the last comment above.
