### ISSUE TITLE
[Design] 10-10EZ Form Alignment: Update Medicaid Question

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#25697]
## User Story

**As a** Veteran, **I want to** accurately answer whether I'm eligible for Medicaid, **in order to** complete the Insurance section of the 10-10EZ form.

_Note: The current understanding is that this is an update to the wording of the question (Section III, Question 5). Originally, they wanted to add an addition answer for the "Federal Health Insurance for Low Income Adults", but now the thinking is to incorporate this into the question itself and leave the answer as Yes/No._

Will need to design input on how best to approach this.

## Expected Behavior

The question will be worded more clearly.

## Acceptance Criteria

- [ ] The question will be reworded as "_____" **<-- TBD**

**Comment by Dene-human** [comment]
Hello @mlighdc and @tchrisdyer 

I am providing 3 versions in order from easiest to most difficult to implement, but also in reverse order of my recommendation. V2 and V3 will  help with the problem we saw in research (people confusing the more info component with the question). Dat said he would Estimate ~2 for V1 & V2. For V3 he estimates about a 3-4.


### Current/ old version ![old.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/3a8ecac2-60d4-43f9-8762-47677d492c9c)


### Version 1 (copy changes highlighted)
First highlight is directly from the paper form. Second highlight is an addition I made.

![V1.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/b0b678b7-b6ca-4424-940a-95ebccd0da5e)

### Version 2 (removing more info components)

![V2.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/8bcdd930-1da4-4681-a173-ab1296f14d93)

### Version 3 (two pages)
**Page 1**
![V3-p2.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/0fc82b52-8b53-4b56-99b3-aa64325d16fc)

**Page 2**
![V3-p1.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/ca370715-dda6-4008-8294-d3c9fd53791d)

**Comment by Dene-human** [comment]
Submitted for content review #25350

**Comment by Dene-human** [comment]
@mlighdc 

I worked through this with Danielle. Do we need to show this to the HEC team? Or should I prepare the brief for Dat?


![Medicaid:Medicare-new.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/2d12c55c-b9d9-4d7d-b034-d7e64ebfa488)![V3-p2.png](https://images.zenhubusercontent.com/605c95113f60cac14b50309b/6a3deeac-8126-4ca2-987e-f89ee07da112)

**Comment by mlighdc** [comment]
@dene if you give me a mock of the page, then I can send to the Healthcare  Enrollment team to let them know this is how we are implementing the Medicaid question.

**Comment by Dene-human** [comment]
Thanks for sending this to the HEC team @mlighdc !

We re-wrote the Medicaid question to incorporate the new text addition of the paper form. Based on our meeting this week, we also added a note that Medicaid might have a different name based on the applicant's state.

The text with the Medicare question was not touched, but we removed all explainer text from the more information component. Our research showed a need for more explanation before the applicant felt comfortable to answer the question. Additionally, the research showed usability confusion with the more information component on this specific page due to the shortness of the questions.

As we start to make changes to sections we will incrementally move towards a one question per page format.




[1010EZ_Medicaid_6.25.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6718935/1010EZ_Medicaid_6.25.pdf)
