### ISSUE TITLE
Consider using Moment LL Formatting

### ISSUE THREAD

**Issue by LinnJS** [department-of-veterans-affairs/va.gov-team#25717]
## Technial Task

During the code review of this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17474) that we were using abbreviated time formatting. For accessibility purposes we might want to consider replacing moment time formats for the long form LL version so the readout for a screen reader is more descriptive and easier to understand.

LL Format  |  Month name, day of month, year  |  September 4, 1986

![image.png](https://images.zenhubusercontent.com/5dcf313b98e0b800015f2353/2beb24f4-2b47-436c-ab7f-247e4402b873)

## Expected Behavior

Time is formatted correctly

## Acceptance Criteria

- [ ] Rather than time being abbreviated like `Sept. 4, 1986` have the month spelled out like `September 4, 1986`

**Comment by rebeccawalsh** [comment]
@LinnJS I'm not sure where the problem was! In our prototypes, we fully spell out the month names. 

**Example:**
![image.png](https://images.zenhubusercontent.com/5da618a29c4ddf0001b2fd8e/be6c8b2e-0ab8-4be3-be37-bffb7b44d4c2)

We fully endorse switching to LL formatting! I'm gonna remove Riley and I as assignees.

**Comment by craigwheeler** [comment]
verified all months are using LL format no changes needed closing ticket
