### ISSUE TITLE
Figure out how to integrate AWS Cognito to connect to Login.gov auth

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#25712]

**Comment by joeniquette** [comment]
as of 6/15:
- AWS Cognito is not compatible with login.gov OIDC/OAuth2 due to the lack of nonce being present in the query param of the initial request sent from cognito to login.gov. We asked the login.gov team to reconsider parsing the nonce from the state param of the cognito request however they denied this request because of an international OIDC standard that they are committed to meeting. They have asked AWS to add the nonce as a query param to hopefully allow future implementations between the two parties to be successful.
- AWS Cognito seems to have an issue with being able to handle encrypted assertion values (this is where the sensitive data such as SSN, and other PII are displayed), so we are not able to encrypt the assertion values in the request however the data is still encrypted over TLS 1.2 in transit between the two parties.
- AWS Cognito is currently being setup for a demo, the connection between cognito and login.gov is functioning with a SAML setup. Trevor is working on the backend connections to facilitate the round trip. Our goal is to determine if its possible to go from va.gov -> cognito -> login.gov -> cognito -> va.gov for the saml authentication and authorization flow. This may open up more options for us in the future of managing identity.

**Comment by bosawt** [comment]
Current localhost demo implementation for `vets-api` is on this branch: `25712_integrate_aws_cognito_with_login_gov`

Right now we have the authentication round trip from `va.gov -> Cognito -> login.gov -> Cognito -> va.gov` set up for IAL2 (LOA3)
