### ISSUE TITLE
Resolve tests failures related to flipper gem update

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#25730]
See details here:
https://dsva.slack.com/archives/CSCD0B1V3/p1622812246005800

**Comment by ajmagdub** [comment]
With the flipper upgrade and with the Rails env set to test StatsD.backend is set to StatsD::Instrument::Backends::NullBackend and the Rails logger is never called causing the tests to fail.

With the current version of the flipper gem and in test StatsD.backend is initialized to StatsD::Instrument::Backends::LoggerBackend which is a wrapper for the Rails logger. Or with the upgraded flipper gem, setting RAILS_ENV to development and running the test StatsD.backend is also set to  StatsD::Instrument::Backends::LoggerBackend and in both cases the tests pass.

Skipped tests in vaos_logging_integration_spec.rb and vaos_logging_spec.rb that were checking for calls Rails.logger and removed the expect Rails.logger to receive call in registration_email_job_spec.rb since they were no longer valid because of the change in StatsD initialization caused by the flipper update.

**Comment by ajmagdub** [comment]
code changes are in [PR-6910](https://github.com/department-of-veterans-affairs/vets-api/pull/6910)
