### ISSUE TITLE
Re-write Letters E2E Test in Cypress

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#25765]
* src/applications/letters/tests/01-authed.e2e.spec.js

**Comment by CBonade** [comment]
This has been posted for review and Erik Hansen has been tagged due to an issue with `window.Cypress` causing a different data set to be loaded, causing the test to fail. This make it inconsistent with the experience that the Nightwatch test was running against. The errors spread to the profile which additionally has made it impossible to rewrite this test to work around it, as the data set is not complete enough for the application to function. This data is not API data that can be covered with a mock, as it's state that is injected into the React app.

**Comment by CBonade** [comment]
Having a temporary issue holding this one back where the build step of the site is failing.  Seems to be affecting at least one other PR as well, so awaiting a fix.

**Comment by CBonade** [comment]
This is merged to master and ready to be closed!

**Comment by pjhill** [comment]
Nice -- here's hoping this [fix](https://github.com/department-of-veterans-affairs/vets-website/commit/706f983adb287b320c9b9094661872a70745cfad) keeps the dam from leaking until we can refactor something more robust.
