### ISSUE TITLE
Discovery: kick off incremental builds investigation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#25773]
## Details 

The CMS Core Application team has been working on an "accelerated publishing" initiative: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4748

The most likely results from their discovery do not eliminate the need for additional scalability work to be completed. The purpose of this ticket is to do some very initial discovery on the idea of incremental builds.

### Questions to Answer
- What solution is CMS team proposing? What scalability problems will that approach solve (or impact in some way)? What scalability problems will not be impacted by the proposed solution? 
- What do we mean when we talk about incremental builds? 
- What (super high level) ideas do we have for incremental builds? 
- Would these (super high level) ideas solve the scalability problems that are not addressed by the CMS team's accelerated publishing initiative? 
- How do we want to make a decision regarding proposed incremental build solution? What are the next steps? (Do we need proofs of concept?) 

## Definition of Done 
- [x] Document findings to above Qs 
- [x] Create tickets for next steps

**Comment by meganhkelley** [comment]
See ticket #20207 which may be a duplicate?

**Comment by alexandec** [comment]
Some initial answers:

> What solution is CMS team proposing?

CMS proposes an incremental approach where each time an editor modifies a page, Drupal triggers a build and deploy for that page only. They're calling this "small-batch publishing". A [design document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/design-docs/2021-06-11-small-batch-publishing.md) is available with more information.

> What scalability problems will that approach solve (or impact in some way)?

Small-batch publishing builds should execute quickly regardless of total content size, so scalability is excellent. Even if the full build grows to 45 minutes or more, small-batch builds will remain fast (under 5 minutes). Small-batch publishing, when fully implemented, should solve the scalability problem for single-page content changes.

Note that certain types of content changes could require many pages to be published. Examples include the header, footer, menus, and sidebars. These types of changes are less common, but publishing could be slow in such cases.

> What scalability problems will not be impacted by the proposed solution?

Liquid template modifications are not covered by small-batch publishing. The templates live in the content-build repository, not inside Drupal, so  Drupal is unaware of template changes. A different approach will be required to execute incremental builds in response to template changes. See below for a couple potential solutions. Without these solutions, a full site build would still be required whenever a template is changed.

> What do we mean when we talk about incremental builds?

In broad terms, incremental publishing is the ability to build a subset of pages instead of all the pages on the site. Currently we must build the entire site when any content or template changes. The goal is to implement one or more incremental solutions to first reduce, and ultimately eliminate, the need for a full content build.

> What (super high level) ideas do we have for incremental builds?

As mentioned above, the CMS team is taking care of incremental builds for content changes. For template changes, I'm aware of two potential approaches:

1. **Liquid template-triggered builds**: GitHub Actions would trigger this build whenever an engineer pushes a commit which modifies a template. The build itself would function them same way as our current full site build, except that the set of pages built would be limited to those which use the modified template. However, determining which pages to build based on a given template change could be challenging.

2. **Twig template-triggered builds**: With this method we'd first convert all our liquid templates into twig templates. Twig templates are Drupal's native format. This would allow Drupal to render and publish the appropriate pages whenever a template is modified. It's a simpler and cleaner approach, but it has a big hurdle: converting all our templates from liquid to twig. As of 6/11/2021 we have 126 liquid templates.

Approach #1 probably makes the most sense in the short term, since it means we wouldn't have to convert all our templates.

> Would these (super high level) ideas solve the scalability problems that are not addressed by the CMS team's accelerated publishing initiative?

Yes. The CMS team's proposed approach only covers changes to Drupal content. The template-triggered options above cover changes to templates. The combination of both approaches, once fully implemented, should eliminate the need to perform full content builds. Scalability would be greatly improved because the typical incremental build would be much smaller and faster than a full content build.

> How do we want to make a decision regarding proposed incremental build solution? What are the next steps? (Do we need proofs of concept?)

We'll probably want to think through the process of template-triggered builds in more detail. This would include a high-level design, just to get a sense of the major steps involved. Then if the approach still seems feasible, we could move on to implementing a POC. If the POC functions well we could look at what's required for a full implementation.

The main unknown in my mind is: given a template, how do we generate a list of pages which use that template? Templates can be used anywhere inside other templates, and templates can be included dynamically based on template variables. Our incremental build solution must account for all this. Otherwise our solution will be unreliable and parts of the site won't be updated correctly when templates are modified.

**Comment by alexandec** [comment]
@meganhkelley @timwright12 please take a look at the answers above and see if some areas should be expanded, or if any other questions arise.  Also, do you know of any other approaches to handling template changes?

**Comment by timwright12** [comment]
Good stuff, my only comments here are:

1. For incremental builds we also need to solve for the local engineering experience in addition to GHA - I would put pretty equal weight on the importance of that.

2. In response to: "The combination of both approaches, once fully implemented, should eliminate the need to perform full content builds."
We still need to solve for anything that is a global change (header, footer, and the like) as well as the va.gov-content repo if it isn't sunset into Drupal.

**Comment by alexandec** [comment]
Thanks Tim, good points! I've updated the answers based on your comments.

**Comment by alexandec** [comment]
Two followup tickets:

- [#26194](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/26194) Discovery: document inner workings of metalsmith-incremental module
- [#26198](https://app.zenhub.com/workspaces/vsp---frontend-tools-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/26198) Discovery: investigate strategies for mapping templates to pages

We'll need additional followup beyond these, but they should yield a lot of useful information. FYI @meganhkelley @timwright12

**Comment by meganhkelley** [comment]
Thanks Chris, this is a great write up! I wonder why we didn't use Twig in the first place — if that historical info would be helpful for you, let me know and I can help dig it up.

**Comment by alexandec** [comment]
Thanks Megan! No need to spend time looking that up. My guess is that Drupal was always seen as just a source of data (headless CMS) in our implementation, so there was no particular need to use its templating system.

**Comment by alexandec** [comment]
Closing this and moving on to followup tickets (see above).
