### ISSUE TITLE
Generate headerFooter.json on demand

### ISSUE THREAD

**Issue by mpelzsherman** [department-of-veterans-affairs/va.gov-team#25793]
# Description

When running `yarn preview`, if the file `../vets-website/build/localhost/generated/headerFooter.json` does not exist, the server throws an error and dies. The only soluion is to run `yarn build`, which kind of defeats the purpose of using the preview server.

`headerFooter.json` is only 21K. It can probably be generated on demand quickly as needed.

# Acceptance Criteria

The preview server does not throw an error if `headerFooter.json` doesn't exist, and the header and footers render correctly.

**Comment by alexandec** [comment]
Just catching up on how the preview server setup works. Let me see if I have it right. The process is:

1. Run `yarn build` in the vets-website repo (only need to do this once)
2. Run `yarn build` in the content-build repo (only need to do this once)
3. Run `yarn preview` in the content-build repo
4. Visit a url like `http://localhost:3002/preview?nodeId=15595` in your browser

On step 4, the preview server fetches the latest data for the provided nodeId and runs a metalsmith build just for that node. You can reload or change the nodeId anytime to rerun this single-node build to see an up-to-date preview of that node.

When you say that running `yarn build` defeats the purpose of using the preview server, could you please explain further? Doesn't the preview server allow you to see the latest content for the supplied node, without rerunning `yarn build`?

**Comment by theodur** [comment]
I made a [PR](https://github.com/department-of-veterans-affairs/content-build/pull/283) with an update for this. The changes in my PR create the `headerFooter.json` file in the preview server's Metalsmith pipeline rather than just fetching it from the `generated` directory. Also, fetching `file-manifest.json` from the `generated` directory will fail if you don't run a full content build prior, since it makes the symlink to `vets-website/build/localhost/generated`. I updated the preview script to make the symlink if it doesn't exist so that there's no need to run the content build for that as well. @mpelzsherman whenever you get a chance, feel free to checkout the branch and let me know if everything is working properly.

**Comment by mpelzsherman** [comment]
> Just catching up on how the preview server setup works. Let me see if I have it right. The process is:
> 
> 1. Run `yarn build` in the vets-website repo (only need to do this once)
> 2. Run `yarn build` in the content-build repo (only need to do this once)
> 3. Run `yarn preview` in the content-build repo
> 4. Visit a url like `http://localhost:3002/preview?nodeId=15595` in your browser
> 
> On step 4, the preview server fetches the latest data for the provided nodeId and runs a metalsmith build just for that node. You can reload or change the nodeId anytime to rerun this single-node build to see an up-to-date preview of that node.
> 
> When you say that running `yarn build` defeats the purpose of using the preview server, could you please explain further? Doesn't the preview server allow you to see the latest content for the supplied node, without rerunning `yarn build`?

Sorry I didn't see this until just now - it got buried in my email?

The required files, `file-manifest.json` and `headerFooter.json` may not exist for a variety of reasons.
Ideally it should not be necessary to run `yarn build` in vets-website just to re-generate  these files.

@theodur I tried deleting  `file-manifest.json` and `headerFooter.json` from my vets-website folder, then I checked out your branch, ran `yarn preview`, and hit a local URL (http://localhost:3002/preview?nodeId=318). I still get the error:

```
We're sorry, something went wrong when trying to preview that page.

Error id: undefined

Error: HTTP error when fetching manifest: 404 Not Found
```

**Comment by mpelzsherman** [comment]
I will say that if the solution is to run `yarn build` again in vets-website, that build runs pretty fast now... under 1 minute on my laptop. So I'd say maybe just change the error message to say "try running yarn build in vets-website"?

**Comment by theodur** [comment]
@mpelzsherman `file-manifest.json` will still need to be present in the `vets-website`'s `generated` directory. The only other alternative would be to use the fetched file manifest from the dev, staging, or prod bucket, but that didn't work out well when I tried that locally. I think it makes sense to update the error message for local builds to say that.

**Comment by mpelzsherman** [comment]
Yes - I think just updating the error message to say "run yarn build in vets-website" works for me!

**Comment by theodur** [comment]
@mpelzsherman Just [updated](https://github.com/department-of-veterans-affairs/content-build/pull/283/commits/c87c88272af32325f8f7a4000b935066421b9c4a) the error messaging for local ✅

**Comment by mpelzsherman** [comment]
I just had a case where I ran `yarn build` in vets-website but `headerFooter.json` was still not found in my content-build preview. Hopefully this change will adress that.

**Comment by mpelzsherman** [comment]
It looks like currently, `headerFooter.json` is generated by doing a `yarn build` in `content-build`, but the file lives in `vets-website/build/localhost/generated/headerFooter.json`. Hopefully this PR will make it unnecessary to run `yarn build` before we can run `yarn preview`.

**Comment by theodur** [comment]
As a side note, the reason why defaulting to fetch prod or staging's `file-manifest.json` when the local file manifest from `vets-website` is missing won't work is because the url of the assets loaded in the page would need to have their domains rewritten to include the prod/staging hostname. So that rather than fetching `/generated/polyfills.entry.js` as it would locally, it would need to fetch `https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/generated/polyfills.entry.js`. 

We'd have to update a couple plugins to accommodate for if `isPreviewServer` is `true` and if the local file manifest is missing. At that point, developers might as well run `NODE_ENV=production yarn preview --buildtype=vagovprod` to avoid needing to run the `vets-website` build entirely, since that would have the same behavior as updating the plugins.

**Comment by theodur** [comment]
The [PR](https://github.com/department-of-veterans-affairs/content-build/pull/283) for this ticket has been merged. I will monitor the preview servers after deployment to make sure everything is working as expected.

**Comment by theodur** [comment]
I verified that the preview servers are working fine after today's deploy. I think we're good to close this ticket now ✅.

**Comment by mpelzsherman** [comment]
Thanks so much!!

**Comment by theodur** [comment]
@mpelzsherman No problem!
