### ISSUE TITLE
FE Tools review of CMS Core App accelerated publishing proposal 

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#25805]
## Details 

CMS Core App team has been conducting a discovery on accelerated publishing. 

[Initiative](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4746)
[Announcement of recommendation](https://dsva.slack.com/archives/C01SR56755H/p1623165826091200)
[Notes doc from CMS/FE Tools mtg on May 28](https://docs.google.com/document/d/1SLwShTHOfc8VOctQH05WNqLj1l3gWzh1LVVa79sNqdg/edit#)
[Small-batch publishing design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/34d977885efaff7dca6dc06c5aaeaaffe11ca967/platform/engineering/design-docs/2021-06-11-small-batch-publishing.md)

## Definition of Done 
- [x] Review AP implementation proposal and provide feedback
- [x] Provide high level work estimates for any FE Tools work required (if applicable)

**Comment by alexandec** [comment]
I asked Neil some questions [over on the PR](https://github.com/department-of-veterans-affairs/va.gov-team/pull/25956#issuecomment-865950939). You can find his replies there. Regarding possible FE Tools work, he said:

> While I don't expect to directly assign tasks to the FE tools team, continued feedback and support in the form of Pull Requests and questions will occur. Most of the questions will most likely be contained to our current sync call. If it is determined we need more support, we will work with you and @meganhkelley.

**Comment by alexandec** [comment]
A few other thoughts after reading the proposal:

- I don't expect the CMS team's small-batch publishing work to block FE Tools' incremental publishing work. (There may be certain instances where coordination is required, for example if both teams are refactoring the same part of the build process at the same time.)
- We'll likely be able to hand off some build/deploy tasks to small-batch publishing in the future. For example if a template for a particular content type changes, we could make a request to SBP to build and deploy all the pages for that content type. On CI this makes sense. However for local development, we'll still need the ability to build the pages locally so engineers can see their changes without waiting for CI.
- Implementation of SBP will happen in stages rather than all at once. Each content type will be converted to SBP one at a time. This is a good approach because it will provide more opportunities to iron out issues, and give everyone time to adjust to the new approach. We could consider a similar transition for our template-triggered incremental builds.
- Despite the incremental work both teams will implement, we'll still need the ability to perform a full site build. The need for a full build will decrease over time, but it won't disappear for a while. Therefore further improvements in full site build time and/or memory use may be required.
