### ISSUE TITLE
Find a VA Form - Internal Staging Review - Add Relevance, Popularity, Related Forms links

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#25812]
## User Story

Issue for conducting internal staging reviews prior to July 1, 2021 VSP staging review 

## Expected Behavior

Team will test Find a VA Form on the Staging environment at https://staging.va.gov/find-forms/

## Acceptance Criteria

- [x] Designer confirms that updated UI on Find a Form search page matches mockups https://staging.va.gov/find-forms/
- [x] Designer confirms that updated UI Find a Form search results matches mockups  https://staging.va.gov/find-forms/?q=10-10ez
- [x] Designer confirms that updated UI Find a Form detail pages match mockups  https://staging.va.gov/find-forms/about-form-10-10ez/
~~- [ ] Designer confirms that PDF download instructions on search results page match mockups **(final design TBD)** ~~ DESCOPED FROM THIS RELEASE 6/14/2021
~~- [ ] Designer confirms that PDF download instructions on form detail pages match mockups  **(final design TBD)**~~ DESCOPED FROM THIS RELEASE 6/14/2021
- [x] Team verifies that searches produce desired results according to the test cases.  [Search terms below](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25812#issuecomment-857774181).

**Comment by callen2563** [comment]
@zacharymorel Hi Zac, Looks great! Just a couple of small tweaks see attached mock. You just need to change those form links to the Bitter font as well as under line them. Accessibility has determined that all links should have an underline moving forward. Also, any download links should include the download icon. That is all I am seeing so we should be good to go after those are made.
![Find a Form - desktop](https://user-images.githubusercontent.com/68560244/121246693-6f599900-c86f-11eb-8bb3-fd865a906d7b.png)

**Comment by zacharymorel** [comment]
@callen2563 Thank you for the quick feed back! I'll be on it this afternoon. CC: @MarciMcGuireGCIO

**Comment by zacharymorel** [comment]
@callen2563 As far as the Bitter font is concerned, is the Form Title the only text to get that font?

**Comment by callen2563** [comment]
@zacharymorel That is correct, just the form titles need to change to Bitter

**Comment by MarciMcGuireGCIO** [comment]
## Test results for search terms:

| Search term                                                    | Prod | Staging | Change Direction | Comments                                                                                                                                                                                                                                                                                                                                  |
|----------------------------------------------------------------|------|---------|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| assign a representive                                          | 468  | 3       | 💚 Positive      | Phrase added based on research recommendation.  Returns 3 results related to root words in the search terms and seemingly disregards article 'a'.  Also matches despite a mispelled key word.                                                                                                                                             |
| assign a representative                                        | 468  | 3       | 💚 Positive      | Phrase added based on research recommendation.  Returns 3 results related to root words in the search terms and seemingly disregards article 'a'.                                                                                                                                                                                         |
| va representative for appeals                                  | 223  | 10      | 💚 Positive      | Phrase added based on research recommendation.  Now returns 10 relevant results that seemingly disregard 'for'                                                                                                                                                                                                                            |
| how do I get a representative for va assistance                | 477  | 10      | 💚 Positive      | Phrase added based on research recommendation.  Now returns 15 relevant results and seemingly disregards "how do I".  Key search word appears twice in the top result name.  Second result has one key word, and is in the top 70 popular forms.                                                                                          |
| 1010                                                           | 26   | 188     | 🔴 Negative      | Plus: Correctly finds forms starting with 10-10 and places 10-10EZ (most popular) at the top. Minus - returns far more resutls than Prod (188), some of which do not contain 10-10 or 1010.  First page lists 22-10204 which seems irrelevant. Everything from page 4 on seems like it shouldn't be listed.                               |
| 1010ez                                                         | 3    | 4       | 💚 Positive      | Also brings back 10-10EC, which could be useful in the event of user typo                                                                                                                                                                                                                                                                 |
| 21P1775                                                        | 1    | 1       | Neutral          | Staging results same as Production                                                                                                                                                                                                                                                                                                        |
| 210304                                                         | 1    | 2       | 💚 Positive      | Correctly finds 21-0304, even without the dash. Also brings back 21-0307, which could be useful in the event of user typo                                                                                                                                                                                                                 |
| va form 21-526                                                 | 1    | 1       | Neutral          | Staging results same as Production                                                                                                                                                                                                                                                                                                        |
| represenative                                                  | 0    | 4       | 💚 Positive      | purposely misspelled based on research study; now brings back forms with the word "representative" in the name, and a form with "representation", which appears first.  This is not unexpected since the search term is misspelled.                                                                                                       |
| representive                                                   | 0    | 4       | 💚 Positive      | purposely misspelled based on research study; now brings back forms with the word "representative" in the name, and a form with "representation", which appears first.  This is not unexpected since the search term is misspelled.                                                                                                       |
| travel                                                         | 3    | 3       | 💚 Positive      | Staging results list results with word "travel" earlier in the title first.                                                                                                                                                                                                                                                               |
| nurse                                                          | 2    | 2       | 💚 Positive      | Now places 10-2850A at the top (most popular form with the word 'nurse') and also includes a root word match that includes "nursing"                                                                                                                                                                                                      |
| direct deposit                                                 | 9    | 9       | 💚 Positive      | Match for exact phrase at the top, AND most popular form with that phrase is at the very top.  Also includes matches based on root words.                                                                                                                                                                                                 |
| release of information                                         | 170  | 40      | 💚 Positive      | Match for form name containing the full phrase "release of information" does not appear at the top For discussion: A form's popularity probably should not outrank a close match for the exact search phrase.                                                                                                                             |
| travel pay                                                     | 12   | 12      | :question: Mixed | Result with exact string "pay" in title appears first.  Other results are based on root words. Negative - some lower results contain actual string "travel" or "pay", but appear below root word matches containing "payroll"  or "payment".  Popularity doesn't seem to be a factor since higher-ranked aren't listed in popular forms.  |
| dbq                                                            | 0    | 0       | Neutral          | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                                                                                                                                                      |
| aid and attendance                                             | 110  | 6       | 💚 Positive      | Matches with literal string "aid and attendance" appear at the top.  Top result is more popular than second match with exact phrase.                                                                                                                                                                                                      |
| va form 21-526                                                 | 1    | 1       | Neutral          | Staging results same as Production                                                                                                                                                                                                                                                                                                        |
| certificate of eligibility                                     | 178  | 63      | 💚 Positive      | Full phrase match appears at top.  Disregarding "of" drastically improves results.  Second result is in the top 70 popular forms.                                                                                                                                                                                                         |
| appeal                                                         | 6    | 6       | 💚 Positive      | VA9 is listed first, presumably because the word "appeal" appears twice in its name, making it most relevant to the search term. Second result with the word appeal is in the top 70 popular forms.                                                                                                                                       |
| notification of personnel action                               | 170  | 4       | 💚 Positive      | No exact match, but results with "personnel action" are ranked first, and the English version appears before the Spanish version of SF-52, even though the form names are formatted differently in the VA forms database.  Disregarding "of" drastically improves results                                                                 |
| intent to file                                                 | 87   | 3       | 💚 Positive      | full phrase match at top, disregarding "to" drastically improves results                                                                                                                                                                                                                                                                  |
| burial                                                         | 4    | 4       | 💚 Positive      | Staging results list results with word "burial" earlier in the title first.                                                                                                                                                                                                                                                               |
| report of contact                                              | 195  | 44      | 💚 Positive      | No exact match, disregarding "of"  drastically improves results                                                                                                                                                                                                                                                                           |
| sf-50/ notification of personnel action                        | 170  | 4       | 💚 Positive      | No exact match, but results with "personnel action appear at the top with the English version appearing before the Spanish version.   Disregarding "of"  drastically improves results                                                                                                                                                     |
| clothing allowance                                             | 5    | 5       | 💚 Positive      | full phrase match at top; next result with single-word match is in the top 70 popular forms.                                                                                                                                                                                                                                              |
| ptsd                                                           | 2    | 2       | 💚 Positive      | Staging results list results with "PTSD" earlier in the title first.                                                                                                                                                                                                                                                                      |
| disability                                                     | 9    | 15      | 💚 Positive      | Lists 21-526ez first as it's the most popular form with "disability" in the name.  Bonus - now includes root word results for "disabled"                                                                                                                                                                                                  |
| coe                                                            | 0    | 0       | Neutral          | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                                                                                                                                                      |
| medical records                                                | 24   | 32      | 💚 Positive      | Full phrase match at top; bonus - also includes "medical record" without the s                                                                                                                                                                                                                                                            |
| fmla                                                           | 0    | 0       | Neutral          | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                                                                                                                                                      |
| power of attorney                                              | 162  | 2       | 💚 Positive      | full phrase match at top                                                                                                                                                                                                                                                                                                                  |
| travel reimbursement                                           | 8    | 9       | 💚 Positive      | Top result is among top 70 popular forms.  Matches containing both words (even though not in the same order) appear above matches with just one word.  Also returns root word match for "reimbursable"                                                                                                                                    |
| pension                                                        | 29   | 29      | 💚 Positive      | Now puts 21-0966 at the top as it's one of the top 70 popular forms.  Places results with "pension" in the middle of word like "Suspension" below exact word matches.                                                                                                                                                                     |
| va form 10-2850c application for associated health occupations | 249  | 121     | :question: Mixed | 10-10ez appears at the top - it has some matching words in the title AND is a very popular form.  Oddly, form 10-2850C name matches "10-2850c application for associated health occupations", but doesn't appear at the top.  It is ranked 64th most popular, where 10-10ez is 13.  Disregarding "for" greatly improves result relevance. |
| authorization                                                  | 17   | 20      | :question: Mixed | Form 10-0459, in which "authorization" appears at the end of the name is listed second, even though later matches start with the word "authorization"; that particular order is not based on our popularity ranking.  Positive - results also include root word match "authority"                                                         |
| rfs                                                            | 0    | 0       | Neutral          | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                                                                                                                                                      |
| notice of disagreement                                         | 162  | 12      | 💚 Positive      | full phrase match at top; disregarding "of" drastically improves results.                                                                                                                                                                                                                                                                 |
| request for service                                            | 240  | 87      | 💚 Positive      | Top result contains exact phrase and is among top 70 forms.                                                                                                                                                                                                                                                                               |
| statement in support of claim                                  | 325  | 69      | 💚 Positive      | full phrase matches are at the top.  Top match is also most popular form.  Disregarding "in" and "of" also drastically improves results                                                                                                                                                                                                   |
| caregiver                                                      | 1    | 1       | Neutral          | Staging results same as Production                                                                                                                                                                                                                                                                                                        |
| change of address                                              | 165  | 9       | 💚 Positive      | full phrase matches at top, disregarding "of" also drastically improves results                                                                                                                                                                                                                                                           |
| burial benefits                                                | 26   | 29      | 💚 Positive      | full phrase matches at top; also includes root word matches for "benefit".                                                                                                                                                                                                                                                                |
| application for associated health occupations                  | 249  | 121     | 💚 Positive      | full phrase match at top, disregarding "for" also drastically improves results                                                                                                                                                                                                                                                            |
| home loan                                                      | 50   | 50      | 💚 Positive      | full phrase matches at top, seemlingly ranked by how early in the name the string appears.                                                                                                                                                                                                                                                |
| advance directive                                              | 3    | 7       | 🔴 Negative      | Forms 10-0137 and 10-0737A which both contain "advance directive" in the names are ranked 4th and 5th, below results that contain only one word in the search term. Top results are not among most popular. Positive: also brings back matches for "direct"                                                                               |
| award letter                                                   | 13   | 13      | Neutral          | No exact matches; not sure what determines order in this case.  Match with "award" as third word listed after a match for "letter" as fourth word                                                                                                                                                                                         |
| supplemental claim                                             | 42   | 42      | 🔴 Negative      | 20-0995 which contains exact phrase "supplemental claim" is listed second after 21-4138, which is the most popular form, BUT contains only the word "claim".  Exact phrase match should probably outweigh a form's popularity.                                                                                                            |
| chapter 35                                                     | 12   | 6       | 💚 Positive      | No exact match, but returns every form with "chapter" in the name.                                                                                                                                                                                                                                                                        |
| prior authorization                                            | 21   | 24      | 💚 Positive      | Also returns matches for "authority"                                                                                                                                                                                                                                                                                                      |
| statement of service                                           | 199  | 61      | 💚 Positive      | No exact match, but disregarding "of"  drastically improves results                                                                                                                                                                                                                                                                       |
| application for nurses                                         | 233  | 90      | 💚 Positive      | full phrase match at top, disregarding "for" also drastically improves results                                                                                                                                                                                                                                                            |
| agent orange                                                   | 2    | 2       | 💚 Positive      | No exact match, but an English form match is now listed above a Spanish match.                                                                                                                                                                                                                                                            |
| nurse application                                              | 87   | 90      | 💚 Positive      | Matches with both words (even though not the the same order) at the top.  Also returns matches for "nurses"                                                                                                                                                                                                                               |
| request for services                                           | 232  | 86      | 💚 Positive      | Top result contains "request for service" and is a popular form.  Disregarding "for"  drastically improves results                                                                                                                                                                                                                        |
| name change                                                    | 15   | 9       | 💚 Positive      | Top result contains both words, even though not in the same order.  No longer including results with "change" found in the middle of the word "exchange".                                                                                                                                                                                 |
| application for pension                                        | 255  | 107     | 💚 Positive      | Matches with both words (even though not the the same order) at the top.  Top result is among most popular forms. Excluding "for" also improves results                                                                                                                                                                                   |
| third party                                                    | 4    | 8       | 💚 Positive      | Matches with exact phrase appear at the top.  Also includes matches with "parties"                                                                                                                                                                                                                                                        |
| death benefits                                                 | 28   | 31      |                  | Matches with both words (even though not the the same order) at the top. Also includes matches for "benefit".                                                                                                                                                                                                                             |

**Comment by MarciMcGuireGCIO** [comment]
> @zacharymorel That is correct, just the form titles need to change to Bitter

@zacharymorel - please let us know once you've had a chance to incorporate Cassandra's feedback.  Shawna and Ryan would like to view on Staging before we schedule our Staging review.  Thanks!

**Comment by zacharymorel** [comment]
Sure thing!

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO it is live on staging.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @zacharymorel!  Tagging in @callen2563, @sshein @rtwell - UI consistency updates for Find a VA Form are now on Staging for review.  cc @johnhashva

**Comment by MarciMcGuireGCIO** [comment]
This looks really great to me, @zacharymorel!  Let's wait and see what additional feedback we get from the Design crew.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 - will you please make note in this ticket once you've had a chance to review, along with any feedback you may have?  Shawna and Ryan will then take a look. Thanks!

**Comment by johnhashva** [comment]
## John Hashimoto Test results for search terms:

| Search term                                                    | Prod | Staging | Change Direction | Comments                                                                                                                                                                                                                                                                                                                                  |
|----------------------------------------------------------------|------|---------|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| assign a representive                                          | 468  | 3       | 💚 Positive -- but NOT perfect      |  My expectation is I would get same 6 results as those shown for "assign a representative"                                                                                                                                       |
| assign a representative                                        | 468  | 3       | 💚 Positive      | Phrase added based on research recommendation.  Returns 3 results related to root words in the search terms and seemingly disregards article 'a'.                                                                                                                                                                                         |
| va representative for appeals                                  | 223  | 10      | 💚 Positive      | Phrase added based on research recommendation.  Now returns 10 relevant results that seemingly disregard 'for'  (John note: Should we disregard "va"? How can we boost form 21-22 to the top?)                                                                                                                                                                                                                   |
| how do I get a representative for va assistance                | 477  | 10      | 💚 Positive      | Phrase added based on research recommendation.  Now returns 15 relevant results and seemingly disregards "how do I".  Key search word appears twice in the top result name.  Second result has one key word, and is in the top 70 popular forms.  (John note: Should we disregard "va"? How can we boost form 21-22 to the top?)                                                                                         |
| 1010                                                           | 26   | 188     | 🔴 Negative      | Plus: Correctly finds forms starting with 10-10 and places 10-10EZ (most popular) at the top. Minus - returns far more results than Prod (188), some of which do not contain 10-10 or 1010.  First page lists 22-10204 which seems irrelevant. Everything from page 4 on seems like it shouldn't be listed.   👉🏻 **Update: This is a limitation of the search library.**                            |
| 1010ez                                                         | 3    | 4       | 💚 Positive      | Also brings back 10-10EC, which could be useful in the event of user typo                                                                                                                                                                                                                                                                 |
| 21P1775                                                        | 1    | 1       | Neutral          | Staging results same as Production                                                                                                                                                                                                                                                                                                        |
| 210304                                                         | 1    | 2       | 💚 Positive      | Correctly finds 21-0304, even without the dash. Also brings back 21-0307, which could be useful in the event of user typo                                                                                                                                                                                                                 |
| va form 21-526                                                 | 1    | 1       | Neutral          | Staging results same as Production                                                                                                                                                                                                                                                                                                        |
| represenative                                                  | 0    | 4       | 💚 Positive      | purposely misspelled based on research study; now brings back forms with the word "representative" in the name, and a form with "representation", which appears first.  This is not unexpected since the search term is misspelled.                                                                                                       |
| representive                                                   | 0    | 4       | 💚 Positive      | purposely misspelled based on research study; now brings back forms with the word "representative" in the name, and a form with "representation", which appears first.  This is not unexpected since the search term is misspelled.                                                                                                       |
| travel                                                         | 3    | 3       | 💚 Positive      | Staging results list results with word "travel" earlier in the title first.                                                                                                                                                                                                                                                               |
| nurse                                                          | 2    | 2       | 💚 Positive      | Now places 10-2850A at the top (most popular form with the word 'nurse') and also includes a root word match that includes "nursing"                                                                                                                                                                                                      |
| direct deposit                                                 | 9    | 9       | 💚 Positive      | Match for exact phrase at the top, AND most popular form with that phrase is at the very top.  Also includes matches based on root words.                                                                                                                                                                                                 |
| release of information                                         | 170  | 40      | 💚 Positive      | Match for form name containing the full phrase "release of information" does not appear at the top For discussion: A form's popularity probably should not outrank a close match for the exact search phrase.                                                                                                                             |
| travel pay                                                     | 12   | 12      | :question: Mixed | Result with exact string "pay" in title appears first.  Other results are based on root words. Negative - some lower results contain actual string "travel" or "pay", but appear below root word matches containing "payroll"  or "payment".  Popularity doesn't seem to be a factor since higher-ranked aren't listed in popular forms.  |
| dbq                                                            | 0    | 0       | Neutral          | No change; we will need to do another iteration that focuses on common abbreviations                                                                                                                                                                                                                                                      |
| aid and attendance                                             | 110  | 6       | 💚 Positive      | Matches with literal string "aid and attendance" appear at the top.  Top result is more popular than second match with exact phrase.                                                                                                                                                                                                      |
| va form 21-526                                                 | 1    | 1       | Neutral          | Staging results same as Production                                                                                                                                                                                                                                                                                                        |
| certificate of eligibility                                     | 178  | 63      | 💚 Positive      | Full phrase match appears at top.  Disregarding "of" drastically improves results.  Second result is in the top 70 popular forms.                                                                                                                                                                                                         |
| appeal                                                         | 6    | 6       | 💚 Positive      | VA9 is listed first, presumably because the word "appeal" appears twice in its name, making it most relevant to the search term. Second result with the word appeal is in the top 70 popular forms.                                                                                                                                       |
| notification of personnel action                               | 170  | 4       | 💚 Positive      | No exact match, but results with "personnel action" are ranked first, and the English version appears before the Spanish version of SF-52, even though the form names are formatted differently in the VA forms database.  Disregarding "of" drastically improves results                                                                 |
| intent to file                                                 | 87   | 3       | 💚 Positive      | full phrase match at top, disregarding "to" drastically improves results                                                                                                                                                                                                                                                                  |
| burial                                                         | 4    | 4       | 💚 Positive      | Staging results list results with word "burial" earlier in the title first.                                                                                                                                                                                                                                                               |
| report of contact                                              | 195  | 44      | 💚 Positive      | No exact match, disregarding "of"  drastically improves results                                                                                                                                                                                                                                                                           |
| sf-50/ notification of personnel action                        | 170  | 4       | 💚 Positive      | No exact match, but results with "personnel action appear at the top with the English version appearing before the Spanish version.   Disregarding "of"  drastically improves results                                                                                                                                                     |
| clothing allowance                                             | 5    | 5       | 💚 Positive      | full phrase match at top; next result with single-word match is in the top 70 popular forms.                                                                                                                                                                                                                                              |
| ptsd                                                           | 2    | 2       | 💚 Positive      | Staging results list results with "PTSD" earlier in the title first.                                                                                                                                                                                                                                                                      |
| disability                                                     | 9    | 15      | 💚 Positive      | Lists 21-526ez first as it's the most popular form with "disability" in the name.  Bonus - now includes root word results for "disabled"                                                                                                                                                                                                  |

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @johnhashva !

**Comment by johnhashva** [comment]
@MarciMcGuireGCIO Just did a quick run through of a subset of your comprehensive test queries and all your observations look spot-on to me.  Just highlighted three questions/observations in my comments above.    Unless you identify some easy tweaks/refinements -- I think we're good to go.  (And we can keep fine-tuning going forward.)

**Comment by MarciMcGuireGCIO** [comment]
| Search term                                                    | Prod | Staging | Change Direction | Comments                                                                                                                                                                                                                                                                                                                                  |
|----------------------------------------------------------------|------|---------|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| assign a representive                                          | 468  | 3       | 💚 Positive -- but NOT perfect      | **JH note: My expectation is I would get same 6 results as those shown for "assign a representative"**                                                                                                                                 |
| va representative for appeals                                  | 223  | 10      | 💚 Positive      | Phrase added based on research recommendation.  Now returns 10 relevant results that seemingly disregard 'for'  (**John note: Should we disregard "va"? How can we boost form 21-22 to the top?**)                                                                                                                                                                                                                   |
| how do I get a representative for va assistance                | 477  | 10      | 💚 Positive      | Phrase added based on research recommendation.  Now returns 15 relevant results and seemingly disregards "how do I".  Key search word appears twice in the top result name.  Second result has one key word, and is in the top 70 popular forms.  (**John note: Should we disregard "va"? How can we boost form 21-22 to the top?**)                                                                                         |
                                                                                                                                                                                       |

**Comment by mviterna** [comment]
@johnhashva Let me play around a bit, I think I can tweak those for us....

Also, please search on "appeal". Kayce asked us to bump those two 20-09xx up (from her testing) which brings VA9 down. I want to make sure there are no issues with the ordering on that one either.

**Comment by johnhashva** [comment]
@mviterna Kayce's suggestion works for me!

**Comment by callen2563** [comment]
@zacharymorel I have updated the mocks based on feedback from Ryan and Shawna to add the dividers in between search results and I have also updated the header copy to remove "search results" as requested by @Marci in [this ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25640)
Once staging has been updated please ping me and I will take a look with any additional feedback. Thanks! :)

**Comment by mviterna** [comment]
@johnhashva How would you rate 21-22 vs  20-0995/6? When searching 'appeals' or 'representative'?  Should 21-22 be on top no matter what?

**Comment by johnhashva** [comment]
@mviterna let's get a read on this via Marci who can look at both our on-site search data for Forms and PDF downloads.   I'm guessing it should be:

20-0995
20-0996
10182

**Comment by MarciMcGuireGCIO** [comment]
@mviterna @johnhashva - John is spot-on.   They fall in the same order in search and downloads.

20-0995
20-0996
10182

**Comment by MarciMcGuireGCIO** [comment]
@zacharymorel @callen2563 @johnhashva @mviterna Let's try to wrap up all remaining testing today so I can close out this ticket out as it's end of sprint.  Thanks!

**Comment by mviterna** [comment]
@MarciMcGuireGCIO  I'll have that final change in this morning and then we can set a release date, if you would like

**Comment by mviterna** [comment]
@johnhashva @MarciMcGuireGCIO appeals and representative should be tweaked now. We can always make more tweaks after it hits prod, without code changes

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @mviterna !   We are targeting July 1 for our "official" Staging review with VSP, and July 6 go-live.  John and I are both on PTO next week, hence the gap (plus the lead time required by some Platform teams).

**Comment by mviterna** [comment]
@MarciMcGuireGCIO Thanks! I'll pass it along to Nichole

**Comment by sshein** [comment]
do we have an estimate for when the horizontal rules will show up in staging so I can ping Ryan and tell him he can take a look? will that happen today or is that unpredictable?

**Comment by MarciMcGuireGCIO** [comment]
@sshein - Hopefully this afternoon after the afternoon deployment.  @zacharymorel - did you get a peer review on this?

**Comment by zacharymorel** [comment]
No review yet. I can ping my peers pretty soon since it has almost been 24hours.

**Comment by MarciMcGuireGCIO** [comment]
Ok thank you @zacharymorel !

**Comment by zacharymorel** [comment]
@MarciMcGuireGCIO underlines are now on staging.

**Comment by MarciMcGuireGCIO** [comment]
Awesome; thank you @zacharymorel! @sshein this is ready for Ryan to have a look at.

**Comment by johnhashva** [comment]
I, for one, love the lines!

**Comment by callen2563** [comment]
@zacharymorel Hi Zac, thank you for adding in the divider lines! Just one small tweak.. adjust the spacing above and below the dividers so that the so that the divider lines are centered in between each result. Let me know if you have any questions.

**Comment by zacharymorel** [comment]
You got it @callen2563 , I'll let you know when it is updated.

**Comment by zacharymorel** [comment]
Should be live in 30 minutes or so @callen2563

**Comment by callen2563** [comment]
@sshein Hi Shawna, You mentioned in slack it wasn't clear on where I was posting comments for Zac so I'm tagging you on this ticket to clear up any miscommunication that seems to be happening. Scroll up and you will see the latest feedback.
Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 @johnhashva @zacharymorel @sshein please share any new findings/feedback on our Midpoint Review ticket.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/25954  Thanks!

**Comment by callen2563** [comment]
@zacharymorel I just took at look at staging where you adjusted the spacing for the divider lines. I think that looks much closer to the comp so I'm good. Thank you for doing that! :)

**Comment by callen2563** [comment]
@zacharymorel One more little thing I am seeing on staging is that there seems to be a link title that isn't formatted correctly see screen shot: 
<img width="608" alt="Screen Shot 2021-06-15 at 7 46 24 PM" src="https://user-images.githubusercontent.com/68560244/122262053-0099c280-cea3-11eb-9d7e-507b410a0fdb.png">
Do you mind fixing that to match the link header above? Thanks! :)
