### ISSUE TITLE
Spike: Data Store

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#25825]
For the MVP of the CH-IP project (aka Pre-MVP or "Skateboard") - we will need to be able to store data with a level of encryption. We have a number of options that have been outlined, for example in [this thread](https://dsva.slack.com/archives/C022AC2STBM/p1623168065412400).  

**Outcomes**
- Evaluation of our options
- Decision on a path forward

**Criteria for Success**

1. Encrypted data at rest
2. Easy to set up
3. Easy to use (in general, but also in the context of Lambdas & AWS

**Considerations**

- Should we choose an option that works in the short term but may require some re-work for the long-term CH-IP project?

**A few options already suggested**
[DynamoDB](https://aws.amazon.com/dynamodb/)
[Redis](https://redis.io/)

**Comment by kjduensing** [comment]
Scores are all out of 5.

**DynamoDB**:
- [x] Encrypted data: _By default, but advanced options available_
- [ ] Ease of use: _Seems to depend on the language used. Some anecdotes of difficult debugging._
- [x] Ease of setup: _Seems like we can almost "just start using it", i.e. no instance to spin up since it's serverless._
- [x] Use case fit (Pre-MVP): _We're storing Key-Value Pairs (KVP), not relational data_
- [ ] Use case fit (MVP): _Unclear - if we need to start handling relational data, we may want to consider something else_
**Notes**: This option would likely get us going quickly and provide time to consider if we need to switch to another storage. We should heed Jonathan's warnings of it being hard to use and difficult to debug.

**Comment by kjduensing** [comment]
**Redis**:
- [x] Encrypted data: [_By default_](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/at-rest-encryption.html)
- [x] Ease of use: _Seems fairly easy to use. Different languages introduce different idiosyncracies._
- [ ] Ease of setup: _[Harder to set up](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/GettingStarted.html) - need a subnet group, ec2 cluster, access rules_
- [x] Use case fit (Pre-MVP): _Fits the Pre-MVP use case really well as it's short-lived session info_
- [ ] Use case fit (MVP): _Depends on how long-lived we want the UUID-data pair to be. More persistent storage might fit the bill better_
**Notes**: The devops lift is higher on this one since we need to configure subnet groups, ec2 cluster, and access rules. However, it might work as intermediate session storage if we need to persist things for a long time. Not sure if that gains us much, though.

**Comment by kjduensing** [comment]
**DocumentDB**:
- [x] Encrypted data: _[Need to set it up](https://docs.aws.amazon.com/documentdb/latest/developerguide/encryption-at-rest.html) when creating the docdb cluster_
- [x] Ease of use: _Compatible with MongoDB, well documented, straightforward_
- [ ] Ease of setup: _[Need to set up](https://docs.aws.amazon.com/documentdb/latest/developerguide/get-started-guide.html) security group, docdb cluster (not serverless), and encryption at rest_
- [x] Use case fit (Pre-MVP): _fine for our use case. feels bulky for Pre-MVP, but it might hold up better than some other document storage_
- [ ] Use case fit (MVP): _Suffers from same "what if" that DynamoDB does. What if we need a more relational structure? Might not work, but could be better than DynamoDB as I think Mongo has a wider audience_
**Notes**: Comparing this to DynamoDB. Seems slightly better in terms of a larger audience, but slightly more difficult to set up.

**Comment by kjduensing** [comment]
Recommendation:

Use DynamoDB until it is clear it won't work. Got buy-in from Patrick B, Stephen Barrs, Carl, Kennon.

**Comment by kjduensing** [comment]
**PostgreSQL**:
- [x] Encrypted data: _[Need to set it up](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/encrypt-an-existing-amazon-rds-for-postgresql-db-instance.html) when creating the db instance_
- [x] Ease of use: _Once set up, it's just like using a normal relational database_
- [ ] Ease of setup: _[Harder to setup](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/TUT_WebAppWithRDS.html) since we'll need an instance, VPC w/ security groups, subnets, etc_
- [x] Use case fit (Pre-MVP): _Feels very bulky for Pre-MVP_
- [x] Use case fit (MVP): _Might fit the bill better if we're going to need strong relationships in our data and want a more robust solution_
**Notes**: The most robust solution that would work in broad set of cases, but likely too heavy, esp right off the bat
