### ISSUE TITLE
Community Care UC3 "Post Appointment Message"

### ISSUE THREAD

**Issue by Kennon-git** [department-of-veterans-affairs/va.gov-team#25884]
UC3 Sending texts after the veteran's appointment confirming they have attended the appointment in order to initiate records of the request. This requires a response from the veteran. Those responses need to be processed in some way. 
#### Overview
VEText supports 3 timeframes for messages before appointment - initial / follow up / (nirmo) 
This would be the first after appointment message. 
No GUI changes, just adding 4th message type. would not take more work for use outside of cc

#### Requirements
1. Need Stock Verbiage for message itself for stopcode 669 (Julia)
2. Business Logic - should only be sent if the veteran did not cancel the appointment. (there are other use cases but starting with this one)
3. Add post appointment message type
4. Additional message for each message template in "Message Template Editor"
5. Under "enabled clinics" - an additional 4th message type "Post appointment message" with a timeframe in the future (30 days) in Clinic / Stop Code configuration
6. Change label structure for "Message Timeframe" (past / future?) in Clinic / Stop Code configuration - change values so they are before / after appointment date. 
7. Ability to process responses from Veterans
8. Ability to handle multiple appointments in the workflow. 

#### Notes
Feature would be useful for other things beyond cc, implement that as a general reminder feature so sites could config post- appt messages

9 Jun 2021 - CC team cleared this to move forward as next objective. 

Folks have been asking for this for a while - surveys etc.

**Comment by kjduensing** [comment]
Progress made last few days.

**Comment by Kennon-git** [comment]
70% done - hoping to wrap up this week.

**Comment by snyderje** [comment]
> Did you attend your recent VA Community Care appointment on Oct 15 at 0900?
> 
> If you DID attend, reply Y1.
> If you DID NOT attend, reply N1.
> For more details, reply D1.
> 
> Or, call your facility's Community Care office to report this information: %VA_PHONE%.

"Gary, did you attend your recent cardiology appointment on Oct 15 at 0900?

If you DID attend, reply Y1.
If you DID NOT attend, reply N1.

Or, call your facility's Community Care office to report this information: %VA_PHONE%."
"Thank you for confirming that you did attend your recent appointment. 

If you need any further assistance, please call your facility's Community Care office: %VA_PHONE%"
"Thank you for letting us know you did not attend your recent appointment.

If this care is still needed:
... and for assistance rescheduling, REPLY S1
... and no scheduling assistance is needed, REPLY T1

If you don’t need this appointment because you received this care:
... from VA, REPLY V1.
... outside VA under non-VA insurance, REPLY H1.

If this care is no longer desired, REPLY X1.

If you need any further assistance, please call your facility's Community Care office: %VA_PHONE%"

**Comment by kjduensing** [comment]
Probably can't demo for wed.

**Comment by shanemelliott** [comment]
Need to include a new requirement:

When the Veteran responds with YEs, place the follsoing consult factor in the consult:
![image.png](https://images.zenhubusercontent.com/5fb2cc990446ae1e7ea9453b/de509c02-5fab-4bf7-a4a2-ddbc4bc4183c)

**Comment by Kennon-git** [comment]
still about 80% done.

**Comment by shanemelliott** [comment]
Pilot Sites:
Team,

 

I reached out to Denver and Salt Lake (both of whom have a large volume of referrals with appt. in the past) to ask if they would be willing to pilot use case #3.  I will let you know.  

 

Elaine, if you have anyone in your VISN, let us know.

 

Have a great weekend!

 

Katie

 

Katie Beckett, M.D.

Acting Chief Medical Officer

Office of Community Care

(720) 667-6323 cell

mary.beckett@va.gov

**Comment by Kennon-git** [comment]
High priority this week

**Comment by shanemelliott** [comment]
COT-Community Care Appointment has occurred: Per Veteran

**Comment by shanemelliott** [comment]
@robertdurkin  added the factor
