### ISSUE TITLE
better cleanup of docker resources on jenkins-swarm nodes

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2602]
We have a job right now that does a weekly `docker system prune` to cleanup cached images and other things that are stored locally for CI. It looks like this is probably not enough as a couple of Fridays lately we've seen disk warnings.

So far I've just kicked off the cleanup job early, but we should come up with a better system to keep the filesystems from filling.

**Comment by nathanhruby** [comment]
One thing we are looking at for department-of-veterans-affairs/va.gov-team#3508 is if we can switch to c5d's and use ephemeral machine storage for the workspace.  This particular issue presents a problem since the local space on the equivalent c5d is about 200GB versus the 500GB of gp2 we use for the rootvol now.

I took a look at this and see a few things
- multibranch pipeline jobs are not cleaning up, appears because we don't set
`orphanedItemStrategy { discardOldItems { numToKeep(SOME_NUMBER_HERE) } }`
  - We do set a `daysToKeep()` but I I suspect we need to set both or at least this so get it to run
- Similarly we set `periodicFolderTrigger` to seven days but probably should set to one to check for things to remove daily (when used with daysToKeep I think though should keep us with 7 rolling history of builds)
- I picked a random node to look at, the space when I logged in was 345G used and the jenkins workspace was 266GB.
- I spot checked a branch in jenkins that should be removed (strikethough in MS list, branch merged) and found the workspace still on the node from 9 days ago, that node has 43 workspaces older than 7 days put of a 141 total (node is about 2 weeks old)
- vets-website builds are 5-8GB in size (will probably be larger once we add git lfs checkouts) so these do add up quickly
- docker also doesn't seem to be getting well cleaned, I tried a few things:
  - `docker system prune --volumes -f` -> Total reclaimed space: 48.86GB
  - `docker image prune --all --filter until=$(date --date="5 days ago" +"%Y"-"%m"-"%d")` -> Total reclaimed space: 11.26GB

So it seems like fixing the workspace cleanups, fixing hte docker cleanups, and lowering daysToKeep() to something like 3 would get us comfortable under the 200GB threshold.

**Comment by nathanhruby** [comment]
note also that last week's "weekly maintenance" jenkins job failed to run, so the docker numbers are higher than the normally would be.
