### ISSUE TITLE
Content Feedback - Midpoint review - Decision Tools - Find a VA form

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#26099]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
@MarciMcGuireGCIO @callen2563 Hello, Platform content feedback is below. Please let me know if you have any questions. 

This feedback refers to content on this page: https://staging.va.gov/find-forms/about-form-10-10ez/

**Should** (16)

1. In the Helpful links listed at the bottom of this page, please update the language of this link "Schedule and view your VA appointments"  TO "Schedule and manage health appointments"  to align with the H1 on the page we’re sending users 

2. The link for the Spanish version of the 10-10EZ takes me back to the "Find a VA form" landing page instead of the online version of this form. 

----

**Consider** (19)

Consider replacing "Online tool" with "online form" in the following areas to be consistent and clear that we are talking about the online version of the form. Not a “ tool” 
Additionally, we use "online form"  elsewhere on the page and  on VA.gov, so we should be consistent in this language. 

Header: Online tool > Online form
Action link: Go to the online tool > Go to the online form

**Comment by MarciMcGuireGCIO** [comment]
Thank you for the feedback, @peggygannon! 

To clarify, this update did not modify the Helpful Links from the way they were originally designed for the MVP last year.   

Re: the Spanish 10-10ez form - that is a temporary redirect because of an accessibly issue related to language.  The Spanish version of 10-10EZ has a detail page, but the copy was a mix of Spanish and English, so we temporarily archived it and redirected the link to the main search page.  Once the localization team has a solution in place, we will remove that redirect so that links back to the detail page. 

It's also my understanding that the "Online tool" text was agreed upon after significant debate during the MVP because there are several instances where the link goes to a informational page rather than an online form.

**Comment by MarciMcGuireGCIO** [comment]
Putting this into the backlog so we can revisit the "Go to Online Tool" button verbiage with the Content and IA teams, as well as possibly coming up with a better solution for the 10-10EZ redirect.
