### ISSUE TITLE
Determine why queries with Typeahead Suggestions are appearing on reports

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#26100]
##  Description
Determine why searches terms that we have hardcoded suggestions are showing up as "searches with no suggestions"

## Background/Context
- To establish a seeding strategy we would like to look at queries that do not generate any typeahead suggestions. 
- We are looking for monthly reports showing terms
    - May 13-May 31 #25483
     - June 1 - June 30 (once available) 

## Tasks
- [x] Work with analytics team to identify why terms with suggestions are appearing. We anticipate this will take a few sprints to resolve with the analytics team to identity the root cause of the issue

## Acceptance Criteria
- [ ] Any issues are resolved and we are able to generate reports showing query terms that have no typeahead suggestions being presented to users.

**Comment by srsuddath** [comment]
We believe that this issue is not a problem with our analytics tagging or typeahead functionality, but rather a problem with the delay in fetching typeahead suggestions.

Our hypothesis is that certain users with slow internet connections, or users who follow the "type a suggestion and then press enter" search pattern will initiate a search faster than suggestions can populate, reading to "false positives": searches appearing to have no suggestions.
