### ISSUE TITLE
Update BGS Gem: Rejection Notes

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#26204]
## Goal
We need to call the BGS `DevelopmentNotesService` to add a rejection reason in the notes field when setting the status to `MANUAL_VAGOV` for manual review.

## Tasks
- [ ] Update the BGS gem to allow the `createNote` service to be utilized

## Acceptance Criteria
- [ ] BGS gem code is submitted and a PR is requested for merging

**Comment by kathleencrawford** [comment]
Draft PR submitted here: https://github.com/department-of-veterans-affairs/bgs-ext/pull/61

It needs to stay in draft until VA.gov has access to the `createNote` service.

Note for after we have access to `createNote`: we will need to update the response data and test specs.  I'm not able to do that now because I don't know how the response is formatted.

**Comment by jason-gcio** [comment]
I think we have access now.  (yay! 🎉)
