### ISSUE TITLE
DS Logon down - Va.gov/EBN

### ISSUE THREAD

**Issue by Kimberley2019** [department-of-veterans-affairs/va.gov-team#2626]
Today, 10/21/2019, the following information was reported to us by the HRC Call Center.

Problem description. How might we fix the newly identified issue of:

eBenefits Help Desk is receiving reports of blank screen, latency, “page cannot be displayed”, page spinning/loading when using DS Logon to log into Va.gov or ebenefits.va.gov

 
![image.png](https://images.zenhubusercontent.com/5d3b2f7176f8655a8ad39ace/ae6fa1fb-b165-42c5-aac6-b2d27ca5694c)

## Goal
_What outcome(s) do we want to see?
_ The outcome that we want to see is the error message being investigated and ultimately resolved.
_Please add additional assignees or labels accordingly.

## Objectives or Key Results this is meant to further
- _lorem ipsum_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by AZSchneider** [comment]
This was not a DS Logon issue.  Here are the results of the HPI held on 10/22/19. Issue closed at 3 pm eastern on 10/22:

The HPI call resumed at 0930 ET.
Root cause analysis is ongoing. There is no significant increase in the number of users however the issue with loading documents is continuing in approximately 3 out of 5 attempts.
A support request with NSOC BPE Operations has been submitted.
0958 ET Servers were rebooted with no improvement in the errors being caused. A null pointer exception error is being shown. AWS support is being requested to join the HPI.
1011 ET There are 2 nodes within the managed cluster reporting errors. The remaining nodes in the cluster are not showing any errors. The nodes with the errors are being removed from the cluster to see if resolves the MyDocs errors being reported by users.
1019 ET Nodes have been removed and initial testing is not showing any errors. Additional testing is being done to ensure the issue has been isolated. At this time it is believed the ICMP traffic is blocked at the VBMS Virtual Private Cloud (VPC) layer.
1022 ET NSOC BPE joined the HP call.
1032 ET Additional testing shows no further issues.
1036 ET 760 users logged in to eBenefits, approximately 1500 users on the site.
1054 ET No further errors have been reported. HPI is on pause until 1500 ET. Banner will remain up on eBenefits while a triage team performs root cause analysis on the servers that were removed from the cluster.
 
 
1500 ET HPI call resumed.
No further issues have been reported.
Root cause analysis is continuing.
The banner on the eBenefits portal is being taken down.
The HPI call is now closed.
