### ISSUE TITLE
API latency 2019-10-21

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#2633]
Incident from 2019-10-21 where vets-api experienced high latency and caused instances to cycle in and out of the ASG. Incident first detected here: https://dsva.slack.com/archives/C30LCU8S3/p1571670614020900

Looks like some issues with Sidekiq workers caused abnormally high polling by the front-end which eventually resulted in latency issues and instances becoming unhealthy. Need to write up learnings from this and any items we want to address in the platform.

**Comment by kfrz** [comment]
## Incident Root Cause Analysis Synopsis

### Timeline
#### 21-10-2019 -> 25-10-2019
- VSP Triage engineers begin investigation into root cause
- VSP Ops team adjusted the ASG settings

#### 28-10-2019
VSP Triage engineers continued investigation.

- Identified pattern of CPU max use and noticed that it occurs in a somewhat regular time pattern (around 04:55 UTC daily)

- From the following graph of CPU Utilization on `vets-api` worker instances in production over the known incident timeline, we can see somewhat of a pattern indicating a trigger or catalyst of some sort. 

It's clear that the "problem child" is only running on one core of a single instance, indicating it's likely a particular job/worker. See [Grafana - 2 wks](http://grafana.vfs.va.gov/dashboard/db/job-queue?orgId=1&from=1571291525566&to=1572368400000&panelId=8&fullscreen)

- Drilled down into Grafana graph where the CPU utilization spikes, to discover a common timeframe with which to correlate with the CPU spikes, as they appeared to ramp up very quickly

- From this we can see the spikes commonly occur in the minutes between 04:50-04:59 UTC http://grafana.vfs.va.gov/dashboard/db/job-queue?orgId=1&from=1572327947724&to=1572368400000&panelId=8&fullscreen

- Cross referencing w/ the Sidekiq schedule file we see a string of FacilityLocator jobs that are run in that hour, the PSGG job being added the day before issue began ocurring. See: https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/sidekiq_scheduler.yml#L107-L110

- Identify which instance (by id) experienced the CPU spike, and cross-reference via EC2 in order to identify the private host IP for that instance

- Use that host IP to filter in Cloudwatch over given time frame and only on that host

- The newest pSSG job happens to run at 04:55 each day

- Applying a filter pattern to the vets-api-worker log stream [here](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-vagov-prod/srv/vets-api/src/log/vets-api-worker.log;filter=%22PSSG%22;start=P1D) for vets-api prod worker instances deployments with the job queued up on a given day, and by searching with the assigned `jid` we can identify the single thread & job instance that runs for 299 minutes before failing:

```json
{
    "host": "ip-10-247-34-208",
    "application": "vets-api-worker",
    "timestamp": "2019-10-29T13:54:38.845320Z",
    "level": "info",
    "level_index": 2,
    "pid": 2456,
    "thread": "69999276994480",
    "named_tags": {
        "jid": "b86acfb9cf70a547cf1ebbc6",
        "request_id": null,
        "remote_ip": null,
        "user_agent": null
    },
    "name": "Sidekiq",
    "message": "fail: 17978.66 sec"
}
```

- This amounts to a lot of evidence pointing towards that job being a culprit. Can be repeated with other moments of "CPU spike" and find a correlated, long-running failed download job.

---

@LindseySaari and I chatted w/ @edmkitty to share what we have learned. Lighthouse team will investigate potential fixes/improvements to the assumedly CPU-heavy polygon calculations, including: 
  - refactor logic if needed
  - organize concurrency more effectively
  - investigate alternative solutions

- Kat's [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/3479/files) may address the retry time for getting drive time bands
  - these changes should reduce total estimated job run time from ~6hrs to ~1.5hrs, though it's unclear if the CPU will still be maxed for the shorter duration


### VSP Triage next steps:

- Revisit the Grafana metrics in AM of 10/30/19 to see if [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/3479/files) has reduced the issue severity
- Run profile on sidekiq worker ruby thread with `rbspy` or `rbtrace/stackprof` in order to track down which ruby/C calls are "most used"
- Update the [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/14/commits/8b5b554f71282d137f8dcb74350c9a8c251f194d) accordingly.
