### ISSUE TITLE
Edit Draft Reply

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#26357]
## User Story
As a user, I want to edit a draft reply message so that I can make updates before sending it.

## Acceptance Criteria
* In the Drafts folder, when a user taps on a message that was a response to an existing message thread, it opens the reply edit screen. 
* Data from the original reply message displays in the Message field
     *Note: users cannot edit the 'To' or 'Subject' fields 
* 'Edit Draft' displays as an H1

Not included in this story:
[Save Integration](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26508)
[Save Success](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26336)/[Cancel Confirmation ](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26333)
## Accessibility Guidelines
* 'Edit Draft' is marked as H1
* Assuming all of the accessibility requirements from the original [Reply to Message form](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/20486) and the new [Save button](https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/26239) criteria 

## Design
![Edit Reply.png](https://images.zenhubusercontent.com/5fa59749c2f3e3e913ad2b06/1d2bf58b-8c8b-42d9-a54c-52a888f61330)

**Comment by digitalken** [comment]
PASS 7/28/2021 - Aside from the bug that "sometimes" happens where the reply edit draft screen opens with editable To and Subject fields (logged bug, link below), it looks good on iOS and Android.  Since I've recorded the bug in the system, I'm going to go ahead and close this ticket.

Bug:  https://app.zenhub.com/workspaces/va-mobile-app-5f205eac3155a2000f422ecb/issues/department-of-veterans-affairs/va.gov-team/28050
