### ISSUE TITLE
[FSR discovery]: Fatal Error Submission Page

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#26629]
**Description**
When I'm at the "sign and submit" page of the FSR, the submit button is primary style and on the left. If I submit, and it fails, I'm still on the same page. I can re-attempt the submission by signing again, but the "Submit" button gets replaced by a button that redirects me back to the home page on VA.gov.

This causes a lot of confusion (though the form broke). It also results in me going through the entire form again just to try and re-submit.

**Story**
As a VA.gov user 
I'd like less confusion about how to re-attempt a form submission.

**Screen Shots**
- On Submission:
![Screen Shot 2021-06-25 at 11.27.46 AM.png](https://images.zenhubusercontent.com/5df3b02f7e9c5dbde476fd6a/33c8aa80-7766-4446-a918-1ae24a1d88b6)
- On Re-submission:
![Screen Shot 2021-06-25 at 11.10.13 AM.png](https://images.zenhubusercontent.com/5df3b02f7e9c5dbde476fd6a/b447f581-89a5-44fb-b9d6-87e3e9b59975)

**Comment by craigwheeler** [comment]
hey @kevinmirc I agree that the process may be a bit confusing but the form submit states are platform components and should be the same for all other forms. In this particular case the "submit again" link found [here](https://github.com/department-of-veterans-affairs/vets-website/blob/176626490fb8c92f824b29786b1c95b2c5feebda/src/platform/forms-system/src/js/review/submit-states/GenericError.jsx#L33) is meant for development purposes and should only render for all envs that are not prod so the user shouldn't see the link.

I assume our intent to avoid confusion in the event of an actual error is to let the user know in the error message to re-submit their request the next day and since save in progress is enabled should prompt the user to nav to the review page without having to fill out the entire form and try again at a later time.

@rebeccawalsh or @rileyorr do you see any room for improvement here?

I've attached a video of what a user would typically see on prod in the event of a submission error

https://images.zenhubusercontent.com/133843125/6e362870-b364-4136-bac3-52c18b9a20bb/screencast_2021_07_01_13_12_45.mp4

**Comment by rileyorr** [comment]
Thanks for calling this out @kevinmirc!

That error alert isn't supposed to display on the 'Review submission' page; it's supposed to display on its own page ([UXPin prototype for reference](https://preview.uxpin.com/803dc24213cf723bfce6c5e3eaef5a2c3f3e344b#/pages/138809468/specification/sitemap?mode=i)). It may be beneficial to add a button to that alert redirecting users back to 'Manage your VA debt' but it also seems ironic since they're trying to manage their debt by requesting help but can't submit the form.

**Comment by rileyorr** [comment]
There should be an example of a submission error alert on its own page in the medical device re-ordering tool ([link](https://staging.va.gov/health-care/order-hearing-aid-batteries-and-accessories/order-form-2346/introduction))

**Comment by LinnJS** [comment]
This ticket was created around the confusion of the primary submit button being replaced with a primary go back button. Some users might not realize its not a re-submit button and is a go back button instead. It was raised in grooming that when a fatal error occurs routing the user to another page might be a better solution.

@rileyorr mentioned referencing the MDOT (Medical device form) to see how they implemented an error page rather than a inline error on the submission page.

This ticket is to found out how to do this so it can be implemented in another ticket.

**Comment by LinnJS** [comment]
Bumped this ticket to a 3 to a 5 due to some cross team coordination needing to take place

**Comment by denisecoveyduc** [comment]
@rileyorr Can you find a test user for mdot that shows this error that can be mimicked for FSR?

**Comment by rileyorr** [comment]
Per our discussion during backlog grooming: 

@craigwheeler explained that @OptionSelect and @Dr-Pongo should be able to recreate this if they edit the endpoint url prior to submitting the form. `vets.gov.user+14` (Jerry) has items available to order so y'all should be able to mimic the error! Let me know if you run into any issues or have questions about the form.

**Comment by HeatherRienks** [comment]
FE to confirm LOE and scope.

@OptionSelect @Dr-Pongo @amponce

**Comment by HeatherRienks** [comment]
Per 5/8/23 sync, this is a lower priority and does NOT need to be done by end of S98.

**Comment by HeatherRienks** [comment]
Per Backlog Refinement, we will take this discovery ticket on in an upcoming sprint

**Comment by amponce** [comment]
For some reason I see some errors after login with user 14, trying to trouble shoot.

```
{
  "errors": "User attributes contain multiple distinct CORP_ID values"
}
```

**Comment by HeatherRienks** [comment]
@amponce  -not sure if this is helpful or not, but see Kevin's Slack thread, linked on this ticket: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/30907

**Comment by amponce** [comment]
Follow up thread with Veteran Facing Forms https://dsva.slack.com/archives/C044AGZFG2W/p1717605582619329

I’ll go ahead and close this ticket. If any further investigation is needed, we can always revisit it.
