### ISSUE TITLE
New 'Financial Hub' page creation request from Debt Resolution Team

### ISSUE THREAD

**Issue by rebeccawalsh** [department-of-veterans-affairs/va.gov-team#26646]
## What do you need content guidance and support for?

- [x] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[ ] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[ ] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?
During usability testing for Debt Portal / "Manage your VA debt" and work for Medical Copay Tool, we found a strong preference from Veterans that all financial matters be found in one place. While we're not quite ready to create a complete financial dashboard for Veterans, we'd like to provide a hub where Veterans can find all of the financial tools linked in one place.

This static page would need to provide content and launching points for various financial matters at the VA, including:
- ["Manage your VA debt" tool](https://staging.va.gov/manage-va-debt/), which surfaces benefits debts related to education, disability compensation, and pension.
- ["Payment history" tool](https://www.va.gov/va-payment-history/)
- ["Medical copay" tool](https://preview.uxpin.com/361636c369f65453b4880d1445911c4d9b869349#/pages//simulate/no-panels?mode=i)
- [Travel pay reimbursement info + instructions](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/)
- Other types of payments to Veterans and money they owe VA that may exist (TBD)

## When does this content work need to be done?
Product release on December 1st, 2021

## Do you plan to bring this to an upcoming content office hours session?

- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

-      Team name: Debt Resolution Team
-	OCTO-DE product owner: Matthew Self
-	Product manager: @denisecoveyduc 
-	Designer: @rileyorr & @rebeccawalsh 
-	FE engineer: @craigwheeler 
-	Product/team Slack channel: #vsa-debt

## Links to related tickets

*Please include here a link to the epic, or other relevant tickets, for this product work.*

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by RLHecht** [comment]
@shiragoodman @peggygannon @mnorthuis for awareness

**Comment by mnorthuis** [comment]
@RLHecht @DanielleThierryUSDSVA I'd like to meet with y'all to discuss this one.

**Comment by mnorthuis** [comment]
IA is in progress and can be found here:  https://app.zenhub.com/workspaces/platform---product-support-5f85b91c14d8df0018fac414/issues/department-of-veterans-affairs/va.gov-team/25663

This page is related to the build of the medical copay tool.  Is there another content ticket for that work?  Want to make sure that we capture all content and entry point work needed for this effort.

**Comment by DanielleThierryUSDSVA** [comment]
**Notes from 7.15 meeting (Danielle, Mikki):**

- We don't have much to offer folks except for links to the respective tool pages. We could try to deep link folks who are signed in and/or add sign-in widgets for each tool (but the latter would likely not work visually and would require too much scrolling). So this will be a simple intro + list of links with brief descriptions + perhaps some related links (like direct deposit update).

- Name of page is tricky. Some potential initial options (will continue brainstorming):
  - Manage your VA finances
  - Manage your VA financial transactions
  - Manage your VA payments and bills
  - VA financial compensation and bills

**- Some shared questions and concerns:**
  - Do all these tasks/tools fit together well enough to share this page? Question about travel pay in particular?
  - What value are we offering with this page in an unauthorized experience and does it make more sense to wait until we can offer a place for authenticated links in My VA?
  - What is the percentage of users that will find all of these tools useful?  Not all users have health care copays, debt or compensation payments, so what is the value of combining these tools for them?
  - How do we navigate SEO with this page without competing with more direct tool landing pages (and thus adding a click for folks)?
  - What are the logical entry points for this and how do the compliment/replace the existing tool entry points?  If we provide a link to this page from top nav or hub pages, does this page provide more value than a direct link to the individual tools?

**- Next steps:**
  - Content team will do a quick audit of potentially related links.
  - Mikki will mock up draft page so we can continue to consider options.

**Comment by rileyorr** [comment]
Hi @mnorthuis and @DanielleThierryUSDSVA! I wanted to circle back on this work as we're getting closer to launching the Medical Copay Tool. I updated this ticket to reflect that we're expecting to launch on December 1st. Do you need anything from our team regarding this work? 

> Will you all be doing usability testing on this page and the wayfinding to it?

I apologize for not answering your question until now - this ticket must have slipped away from me. We don't currently have plans to conduct a usability study for this page. However, our team is actively documenting features to release in another iteration so I can bring this up as something we could incorporate into a study if we test the next iteration's features prior to launch. 

FYI @denisecoveyduc I'm looping you into this ticket! It's related to the "financial hub page" we chatted about this morning.

**Comment by mnorthuis** [comment]
@denisecoveyduc @rileyorr We need to land on a name/H1 for this page and would like your thoughts.

- The biggest struggle here, is that this has a risk of taking SEO value from the other tool landing pages and ultimately adding a click to user navigation paths.
- We already link to these tools individually in key hubs, so this would be adding another link that they just takes you to the other tools.
- We can add a link to this, but the I want to get the H1, link labels, teaser text and URLs very sharp.
- We also strongly recommend that we look at baseline traffic for the existing tool pages and then watch this page after it launches to ensure it is not a detriment to the overall experience.
- We provided some ideas in an above comment https://github.com/department-of-veterans-affairs/va.gov-team/issues/26646#issuecomment-881891576

For entry points,  as mentioned above, this is tough because it's providing a secondary path to the same tools most hubs already link to.  For that reason, I wouldn't add a link to hub pages or primary navigation components.  My suggestion is that we place links for this page within the related/other info grey boxes at the bottom of the content pages.  In many cases it may have to be framed up as "find other financial tools" type link.  

- https://www.va.gov/health-care/pay-copay-bill/
- https://www.va.gov/health-care/get-reimbursed-for-travel-pay/
- https://www.va.gov/va-payment-history/
- https://www.va.gov/manage-va-debt/

**Comment by rileyorr** [comment]
@mnorthuis in terms of the H1, @rebeccawalsh and I are both leaning towards 'Manage your VA payments and bills' because of the keywords that Veterans would look for when searching for copay information ([view the research here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Medical_Copays/research/apr-2021/readout.md#veterans-looked-for-a-variety-of-keywords-when-searching-for-a-pathway-to-copayment-information-but-primarily-looked-for-bill)). 

Your concerns about SEO value and diverting traffic from existing tool pages makes sense to me. Should we set up some time to talk through these points so we have a path forward with this page?

**Comment by mnorthuis** [comment]
@denisecoveyduc Could you take the above concerns and approach back to the product owner and anyone else with a vested interest to confirm that we are fulfilling a need with this?  We want to make sure that this serves the intended benefit before teams take time to do this work.   We could definitely do this via a meeting as well if that would be more helpful.

**Comment by rileyorr** [comment]
@denisecoveyduc bumping this for your awareness as we get closer to launch!

**Comment by denisecoveyduc** [comment]
@mnorthuis @rileyorr I have been delinquent in moving this along. Let me set up some time to discuss with interested parties so we can move this forward. Watch for the invite and let me know if there are any scheduling conflicts. Thanks for your patience.

**Comment by mnorthuis** [comment]
@denisecoveyduc Please make sure @DanielleThierryUSDSVA is included in the meeting.  Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
I believe we determined that we do **not** want to proceed with this for now. So, I'm putting this in the icebox. @denisecoveyduc, if that's not correct or if we need to reopen and revisit, just let me know. Thanks!

**Comment by denisecoveyduc** [comment]
Implementation of Combined VA Debt Portal will address this concern.
