### ISSUE TITLE
Logout needs loading screen

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va.gov-team#26678]
## What Happened?
As a user, when I tap the sign out button, there is no UI to tell me that the process is running. If the network is slow, it just seems to do nothing and tapping multiple times does nothing. eventually the request completes and the app resets to the log in screen.

## Steps to Reproduce
See "What Happened?" above.
## Desired behavior
A loading screen or some UI element shows that the log out is processing

## Acceptance Criteria

- [x] UI/UX decides what the Veteran Experience should be for log out.

- [x] User can log out and is shown some UI that indicates log out is processing
- [x] On Sign Out, redux action to set a new auth state variable `signingOut` to true while the logout function is calling the api. 
- [x] When `loggingOut === true`, the `App.tsx` should render a `SignoutProcessScreen.tsx` that displays the below. Use the same dimensions as used in the `SyncScreen.tsx`
- [x] When signout is complete, redux action sets `signingOut` back to false and the `LoginScreen.tsx` should be displayed.

## Bug Severity
2 - High

**Comment by melissa-lefevre** [comment]
I explored the "loading message type screen at first but after playing with the app a bit and singing on and off, I think it would make most sense to have the same type of screen as the "signing in." The language in the ticket is "log out" but in the app it is "sign out" I think it is best to say "signing out" since that is what the button says.![signing out.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/ca548dd0-d987-4ed9-8983-94ff9a50080c)

**Comment by jperk51** [comment]
Note about AC: I used the existing SyncScreen instead of creating a new one specifically for this

**Comment by digitalken** [comment]
PASS 7/15/2021 - Got the Signing Out screen.  Closing.
