### ISSUE TITLE
Too much padding when VCL banner wraps to multiple lines

### ISSUE THREAD

**Issue by bessgreen** [department-of-veterans-affairs/va.gov-team#26713]
## What happened?
When the content in the VCL banner wraps to multiple lines, there is too much left- and right-padding between the edge of the screen and the content.
![Screen Shot 2021-06-28 at 4.15.20 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/9b88421f-7396-4a5d-82c6-ff186c179957)

## Specs:
- iPhone 11 (with larger text enabled)
- User: judy.morrison

## Steps to Reproduce
1. Log in and view the Home page of the app. 
2. Depending on the device size, update the text size so that the VCL banner text wraps to 2 or more lines. 
3. Note the amount of padding on either side of the banner content. Compare this to the amount of padding in the LIstItems further down the screen, such as "Find a VA Location" and "Contact VA".

## Desired behavior
1. When the content in the VCL banner wraps to multiple lines, the left- and right-padding are consistent with other [simple ListItems](https://adhoc.invisionapp.com/console/Mobile-App-Design-Library-cknr12ik52y3q01yq037sp4nb/cknr136x63na401ys0t5epa4b/play). 

## Acceptance Criteria
See desired behavior.

## Bug Severity
- 4 - low

## Linked to Story
n/a

## Screen shot(s) and additional information
Orange lines indicate where the VCL content should start/stop (i.e. desired behavior). The VCL banner content should follow the same padding as the simple ListItems at the bottom of the Home screen. 

![Screen Shot 2021-06-28 at 4.06.53 PM.png](https://images.zenhubusercontent.com/5f64e41291069a617acc1b47/43ca4c02-8fad-415a-93e5-f022136398e0)

**Comment by bessgreen** [comment]
@bridgethapner tagging you for transparency / to get your input on desired behavior.

**Comment by bridgethapner** [comment]
@kxiao133 and I chatted about this one and we see 2 options: 

# Option 1 
Style the VCL banner the same way at the simple ListItem, meaning the text would be left-aligned with the standard gutter and the arrow would be right-aligned. It would look like this at 1 line:

![Screen Shot 2021-06-30 at 8.31.37 AM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/571e71d6-bd01-4b6e-a3c7-a6f25a39c31f)

This would fix the issue of too much padding when the text goes to multiple lines, but the text could look imbalanced at 1 line depending on the user's text size and device width.  

# Option 2
Leave as-is, which:
- Would maintain the way the Veterans Crisis Line text appears as center-justified when it's 1 line. 
- The issue of too much L & R padding appearing when the text goes to 2 lines would persist. Per Kelly, the justification doesn't change depending on line-number since the multi-line is caused by largeText scaling, so right the multi-line content is still center-justified. And the L & R padding isn't actually set -- the only padding set is the standard gutter of 20px -- the center-justification property puts elements in the middle and leaves whatever leftover space is available onto the sides. During large text, iOS determines the text cannot fit onto one line without breaking the specified 20 px margins, so it wraps to multi-line, which creates extra space on the sides. 


It seems like there's a trade-off here of either the potential of looking imbalanced at 1-line or the appearance of extra padding at 2 lines & not being able to do both. 

If we need to pick one I think Option B - my reason is we will likely rethink the UI of this component this summer anyway and we can address this then to consider differing widths & text sizes a bit better.

**Comment by bessgreen** [comment]
Team decided to leave current implementation as is, and revisit the UI for the VCL banner later on.
