### ISSUE TITLE
NOD - Final Design Changes

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#26729]
## Issue Description

Recently, we presented a demo of the NOD product to the board and, in the process, gained some content feedback. Most of the content feedback was centered on the Board Review Option page. Stakeholders felt that the language within that page could be made to be more 'positive' (i.e. there are sentences such as "you cannot submit new evidence"). The request was to review the page and make the language read in a more positive manner. Also, we were told that the timelines for each review option should be updated. Direct Review should be 1.5 years, and we have asked The Board for clarification on the other two option timelines - will update when that becomes available.

During the demo, one stakeholder suggested this wording for direct review:

>Direct Review: "Because the Board already has all your evidence, choosing this options will often result in a Veterans Law Judge being able to issue a decision most quickly." [with updated timeline]

This content lives on the [board review options page](https://vsateams.invisionapp.com/console/share/8Y10I6K7DU9R/600538585).

---
## Tasks
- Work with Beth to modify language
- If possible, create more positive language for the board review options page
- Update the timelines per Board advisement

## Acceptance Criteria
- [ ] Design has been updated with the above changes
- [ ] Content changes have been shared with FE development
---

**Comment by bethpottsVADEPO** [comment]
I bolded the places where I've edited/rewritten... do you think this addresses stakeholder concerns @kevinstachura ?

Request a direct review:
A Veterans Law Judge will review your appeal based on evidence **you've** already submitted. You **won't be able to** submit more evidence or **request** a hearing. **This Board review option usually gives you the fastest decision because the Board already has all your evidence.** The direct review option will take **1.5** year for the Board to complete.

Submit more evidence:
You can submit more evidence for a Veterans Law Judge to review, but you **won't be able to** have a hearing.

Then I think you're still waiting to hear about the time frames for the other two options...

**Comment by kevinstachura** [comment]
Thanks @bethpotts! I think we can only do what we can do here...we are making it clear that there are certain actions one can or cannot expect as part of each process; some things will just need to be written in the negative to be clear and understandable.

We are definitely trying to get an indication of each time frame for sure, and I don't believe the Board has gotten back to us on that.

I will update the mockups with the language you've given here and we can follow up later once we get the final details from the board. Thanks Beth!

**Comment by kevinstachura** [comment]
This has been updated and can be found on this Sketch project: https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27

On screen 153: https://www.sketch.com/s/0424c51d-7818-43ea-8821-6de91eb7ab27/v/zzZw1r/a/WKZQq4k

Closing this ticket because the requirements we have set out to complete are now complete. We will create a follow up ticket for the timelines of the other two board review options, when the board gets back to us.
