### ISSUE TITLE
Discovery|  Remove Anchor Tags | Corona FAQ Page | Experiment |C&L Team

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#26744]
## Background

The Anchor links on the Corona FAQ page, inside the accordions, no longer work. The sole anchor link outside the accordion (near the top of the page) however, is working correctly:

- https://www.va.gov/coronavirus-veteran-frequently-asked-questions/

Given the experimental run has completed and the  plan is to remove the anchor links from this page after Design Council review, we'd like to research and understand the LOE for 2 potential approaches:

1. remove the broken anchor links (the ones inside the accordions) and leave the one anchor tag outside an accordion intact for the time being
2. if above requires significant extra effort to research and implement, we will want to move towards removing all the anchor tags and need to understand LOE for this

**Comment by adamwhitlock1** [comment]
I have discovered where this bug has come from. We are moving to a new 'web component' called `va-accordion`  for usage throughout the platform, and several days ago the drupal liquid template for 'collapsible panels' was changed to use this new web component.

Moving to this new implementations for accordions broke the shareable link component when it is used inside the accordions.

Since the new va-accordion is a web component it uses something called a 'shadow dom' and we will have to adapt the code to accommodate this breaking change. It is also messing with the styling as far as the button sizing and icon alignment, and will also need to be addressed.

The easiest solution would be removing the shareable link from the accordions from now, as that would just be a simple change to the drupal template, and right now the shareable link component only is active on this one url.
