### ISSUE TITLE
Create POC in Applitools

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#26740]
# Description
Using a free account set up an Applitools scan of the va.gov landing page. Attempt to tease out any unknown unknowns related to using this tool for production monitoring.

## Things we do not need to do
* Don't need to connect this to the PagerDuty service at this time

**Comment by holdenhinkle** [comment]
Repo - https://github.com/department-of-veterans-affairs/applitools-canary

**Comment by holdenhinkle** [comment]
It's working beautifully, just like we want it to.

It's also very fast compared to Percy. It takes approximately 0.5 seconds to analyze an image vs the approximately 40.0 seconds it took Percy to analyze the same image.

One small thing which I need to reported to Applitools:
Passing `false` to `runner.getAllTestResults()` like the following is supposed to suppress an exception from being thrown: 

```
  const results = await runner.getAllTestResults(false);
```

Here's the documentation - https://applitools.com/docs/api/eyes-sdk/classes-gen/class_visualgridrunner/method-visualgridrunner-getalltestresults-selenium-csharp.html

> Parameters
> shouldThrowException
> Type:bool
> If a value of true is passed and any test did not pass, or there was a failure, then an exception is thrown. If a value of false is passed, then the object returned contains the test results and status of all the tests. The calling program should use the method Exception to examine the exception status and, if it is null, check the various methods in the TestResults returned by the method TestResults to see if the tests passed or mismatched where found. If no parameter is passed, then the default value is true.

I know that's for the Selenium SDK but the Tutorial script I used to get this setup says the same thing:

URL - https://applitools.com/tutorials/puppeteer.html

```
        // we pass false to this method to suppress the exception that is thrown if we
        // find visual differences
        const results = await runner.getAllTestResults(false);
        console.log(results);
```

Here's the error I keep getting, which I'd prefer to handle in code:

```
?130 applitools % node index.js
(node:60985) UnhandledPromiseRejectionWarning: Error: Test 'Search Page' of 'VA.gov' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251777055925278/00000251777055925153?accountId=YilShP-zPkW1va4W7KdrVw~~
    at Eyes.close (/Users/holdenhinkle/Documents/Oddball/va_website/my-canary-scripts/applitools/node_modules/@applitools/eyes-api/dist/Eyes.js:222:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async applitoolsVisualRegressionCheck (/Users/holdenhinkle/Documents/Oddball/va_website/my-canary-scripts/applitools/index.js:88:3)
```

This is definitely not a dealbreaker.

I'm going to implement this in a CloudWatch Canary now...

**Comment by holdenhinkle** [comment]
Btw - An important page on matching levels - https://applitools.com/docs/common/cmn-eyes-match-levels.html

**Comment by holdenhinkle** [comment]
I added the Applitools token to the AWS Parameter Store.

I converted the Applitools script to a Synthetic Canary and then moved the code to this PR - https://github.com/department-of-veterans-affairs/devops/pull/9508

I added an entry to this Terraform file - https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/global/canaries.tf

Waiting for Terraform to create the Canary so I can start debugging it...

**Comment by holdenhinkle** [comment]
I haven't gotten very far getting the canary to run. Here's a link to a convo with Bill Ryan in Slack - https://dsva.slack.com/archives/CBU0KDSB1/p1625584677194400?thread_ts=1625067149.442700&cid=CBU0KDSB1

In the meantime, I implemented Visual Regression testing on the VA.gov homepage using Applitools in a GitHub Action on the Testing Tools Team repo.

Here's the pr - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/42

If we do the visual regression testing in github actions instead of in an aws canary, we need to have Applitools fix the issue I found on Friday. I just reported it to them:

> Keith profile
> Thank you for reporting the issue. I created a support ticket for our engineering team to reach out to you soon and have notified my colleague, Seth, who will be leading the upcoming meeting.

---

A convo with Peter and I over slack about implementing this:

Peter Hill  3:48 PM
Sooo, the reason that Percy deals with this better is because of the comparison to master that you mentioned briefly? Like since the change is merged to master it is flagged once and then considered resolved because the code change representing the visual diff is merged to master?

Holden Hinkle  4:18 PM
Well, it sounds like Percy wouldn’t have detected the last two incidents (when images went missing and when css broke).

Percy assumes that everything that is merged to master is correct. It assumes that the changes have been reviewed and checked. So if there are visual changes, they’re assumed to be approved changes.

Peter Hill  4:19 PM
right, ok, kinda thought it might be like that

Holden Hinkle  4:20 PM
when there are unexpected changes during working hours, we can maybe just notify a slack channel or two.
when there are chances after hours/weekends/holidays we can create pageduty incidents. (edited) 

that would give us good coverage.

during the day, people will have to login to applitools to approve changes.

or maybe we can create a button that appears with the slack notification. click the button to approve the change.
:heavy_plus_sign:

and to be clear, we’re only looking for huge changes, like images missing, css breaking, etc.

Peter Hill  4:24 PM
yeah

Holden Hinkle  4:24 PM
so it won’t take an expert to know if something is really wrong or not.

Peter Hill  4:24 PM
i think to start, as a platform we are looking for things that are obviously wrong

not anything that could be a legit change related to a product

Holden Hinkle  4:24 PM
yeah, like text or image changes, new banners, etc.

**Comment by holdenhinkle** [comment]
I submitted this pr to make a minor change to the `cypress.yml` GitHub Actions workflow file because one of the modules for `puppeteer` required for Applitools was over 100mb, too big to upload to GitHub. So I'm planning to delete `node_modules` from from the Testing Tools Team Dashboard Data repo and instead run `yarn install` in each GitHub Actions workflow file.

PR - https://github.com/department-of-veterans-affairs/testing-tools-team-dashboard-data/pull/42

**Comment by holdenhinkle** [comment]
My attempts to create a canary continue - https://dsva.slack.com/archives/CBU0KDSB1/p1625667540279200?thread_ts=1625067149.442700&cid=CBU0KDSB1

Bill created a new s3 bucket for me with a scripts directory where I can add/delete files. That's where my Canary zipFile will live.

I still can't create a canary; I don't have permissions or something.

---

Applitools support emailed me back last night:
	

> Matt Jasaitis (Applitools)
> 
> Jul 6, 2021, 2:31 PM PDT
> 
> Hi Holden,
>
> 
> This is Matt with the Applitools support team. I see you're reporting an issue with the runner.getAllTestResults(false);​ function in the Puppeteer SDK.
> 
> However, I have confirmed that this is working as expected. The failed test will be printed out each time the test fails. However, if you pass false​ to the above function, it will allow the rest of your test suite to be run. If you don't pass false, then your test suite will exit early when the error is thrown and not handled.
> 
> You can validate this on your end by running the modified script I've attached below. If you remove the false argument on line 66, you'll notice that the 2nd test will not run when the first one fails.
> 
> Let me know if this makes sense.
> 
> Thanks!
> Matt

I still can't get it to work. I went over their documentation with Curt today and Curt looked at my code and confirmed that 1) their sdk isn't doing what their docs say it should, and 2) my code is right.

I emailed Matt @ Applitools back (the email formatting didn't carry over to zenhub):

> Holden Hinkle <holden.hinkle@oddball.io>
> 4:17 PM (20 minutes ago)
> to Peter, Applitools
> 
> Hi Matt,
> 
> Thanks for getting back to me so quickly.
> 
> It's not working for me for some reason. I've attached the script I'm running.
> 
>  applitools_script.js
> 
> When I call await runner.getAllTestResults(false) and a difference is detected, I get the following error:
> (node:60069) UnhandledPromiseRejectionWarning: Error: Test 'Homepage' of 'VA.gov' detected differences! See details at: https://eyes.applitools.com/app/batches/00000251776623354585/00000251776623354413?accountId=YilShP-zPkW1va4W7KdrVw~~
>     at Eyes.close (/Users/holdenhinkle/Documents/Oddball/va_website/testing-tools-team-dashboard-testrail-data/node_modules/@applitools/eyes-api/dist/Eyes.js:222:27)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async applitoolsVisualRegressionCheck (/Users/holdenhinkle/Documents/Oddball/va_website/testing-tools-team-dashboard-testrail-data/src/applitools/index.js:56:3)
>     at async run (/Users/holdenhinkle/Documents/Oddball/va_website/testing-tools-team-dashboard-testrail-data/src/applitools/index.js:106:3)
> 
> getAllTestResults(false) is throwing an error. From what I understand, if I pass false as an argument, it's supposed to return a results object. I need that object so I can handle the failure myself.
> 
> Your docs:
> https://applitools.com/tutorials/puppeteer.html
> 
>         // we pass false to this method to suppress the exception that is thrown if we
>         // find visual differences
>         const results = await runner.getAllTestResults(false);
>         console.log(results);
> 
> https://applitools.com/docs/api/eyes-sdk/classes-gen/class_visualgridrunner/method-visualgridrunner-getalltestresults-selenium-csharp.html
> shouldThrowException
> Type:bool
> If a value of true is passed and any test did not pass, or there was a failure, then an exception is thrown. If a value of false is passed, then the object returned contains the test results and status of all the tests. The calling program should use the method Exception to examine the exception status and, if it is null, check the various methods in the TestResults returned by the method TestResults to see if the tests passed or mismatched where found. If no parameter is passed, then the default value is true.
> 
> - -
> 
> In short, your docs say passing false will suppress an error from being thrown and the object returned will contain the test results and status of all the tests. That's not happening.
> 
> Thanks so much, and we're looking forward to our meeting tomorrow!
> 
> Thanks,
> 
> Holden

This is an issue because I need to get the tests results object from Applitools so I can handle the passes and failures programatically. Right now, when a difference is detected (when there's a possible regression) the code stops execution.

Hopefully we'll get this sorted out.

**Comment by holdenhinkle** [comment]
The bug I encountered persists, but Applitools says:

Matt Jasaitis (Applitools)

Jul 9, 2021, 10:38 AM PDT

Hi Holden,

Interesting, I'm not seeing the same problem on my side. How did your meeting go? Was this issue resolved?

If not, I'm happy to set up a quick call to go over this issue in your environment so I can better understand what the problem is.

---

I'm moving this ticket to Review/QA because it's unlikely we'll be using Applitools because it's so expensive.

**Comment by pjhill** [comment]
Work for the POC is complete -- the remaining discussion is around pricing and purchasing.
