### ISSUE TITLE
[Design] Facilities Selector Search and Radio buttons

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#26754]
## User Story

As a user, I want to search for and select my preferred facility, in order to receive the appropriate care.

The purpose of this story is to redesign the Facilities Selection portion of the 10-10CG form in order to replace the existing static state and facilities lists with a live call to the facilities API.

This would allow us to:
- Dynamically search for facilities based on City, State, or Zipcode
- Display more facility information such as name, location, distance

Looking to mirror behaviors on the Facility Search UI and with-in the VAOS Form.

## Expected Behavior

Given a user is completing the 10-10CG (or EZ in future) form, when they arrive at the facilities selection screen, it will display a list of facilities based on the Zipcode they previously entered alongside their address.

Give a user is on the facilities selection screen, when the manually input a City, State, or Zipcode, it will display a list of facilities based on the new information they have provided

## Acceptance Criteria

- [x] Create design 
- [x] Attend design intent
- [x] Make edits based on design intent
- [x] Update midpoint review ticket
- [x] Write tech specs

**Comment by sshein** [comment]
interested in this, so I'll follow the ticket :)

**Comment by Dene-human** [comment]
Sketch [designs](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8)

Design intent completed: #27066 


**Next steps**
- Coordinate with Peter Russo to ensure consistency and update accordingly 
- Midpoint review is scheduled for 7/23

**Comment by Dene-human** [comment]
Development ticket updated with specs: #27375

Things to be defined during dev: 
- "miles filter" breakdowns and dropdown design
- mobile design
- This likely won't affect the 10-10CG, but when implementing the 10-10EZ, we may need to define how many results are shown at a time (pagination) if the number is large.


Midpoint review ticket updated with designs: #27255

Notes:
- VAOS use case is different because the user is already familiar with the facility as it is tied to their profile. 
     - VAOS user doesn't need to locate a facility- there is no city/state/ postal code input field
- Our user is closer to the VA facility finder user which is why we provide the full address and "Get directions"                 
     - Their research shows that "miles away" is the most important factor for the majority of users
     - People are not familiar with VA names so it is important to show the address
