### ISSUE TITLE
R&S Updates: What your decision review or appeal status means

### ISSUE THREAD

**Issue by lwalsh617** [department-of-veterans-affairs/va.gov-team#26998]
### Issue

As R&S further evolves, we've reviewed live articles and are making updates. The following changes will be made to[ the live page](https://www.va.gov/resources/what-your-decision-review-or-appeal-status-means/):  

- Intro:

Change "Find your type of decision review or appeal below to learn what your status means," to:
On this page, you can choose a type of decision review or appeal to learn what each status statement means. When you're ready, you can check your VA claim status.

1st CTA, button label:
Add "appeal" to the CTA button to match page title/content:
**Check your claim or appeal status**

2nd CTA:  Delete the 2nd CTA button.

### Tasks

- [x] DEPO to approve changes as described above (Beth)

- [x] SC to make changes (Laura)

- [x] DEPO to approve changes (Beth)

- [x]  SC to QA and publish (Randi)

### Acceptance Criteria

- [x]  Updated page is live

**Comment by lwalsh617** [comment]
@bethpottsVADEPO - Let me know if I should go ahead and make these changes in Drupal. Thanks!

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 Please move forward with removing the second CTA. But hold on the rest. I'm going to check a nuance with the decision review POC. 

We don't want to say "choose a type of decision review or appeal" because the user isn't choosing anything, they're just finding the right chart on the page to look at. And they may not need to check their claim status, as they may have a letter in from of them with that--so it's more of an option as a next step rather than something we want to direct them to do "when they're ready." 

What I want to talk through with the SME is the wording of No. 2 below here. Ideally, we keep the CTA label as is and just reword the intro. We'll go with one of these for the intro (I just bolded to show the diff). And you'll see I'm using "on this page" in this instance because I think it works really well in this case!:

1/ Your status tells you where your **decision review or appeal is in the review** process. Find the chart on this page with your type of decision review or appeal, and learn what your status means.
or
2/ Your status tells you where your **claim is in the decision review or appeal** process. Find the chart on this page with your type of decision review or appeal, and learn what your status means.

**Comment by bethpottsVADEPO** [comment]
@lwalsh617 After a conversation with Paul Shute in disability comp, let's move forward with: 

1/ "Your status tells you where your claim is in the decision review or appeal process." (and leave the second sentence of the intro as is)
2/ Leave first CTA button label as is
3/ Delete second CTA button altogether

Thanks!

**Comment by lwalsh617** [comment]
@RLHecht - I made the edits per Beth's comment ^. The page is ready for you to review and publish. Thank you!
http://preview-prod.vfs.va.gov/preview?nodeId=9626

**Comment by RLHecht** [comment]
This is reviewed and published. Will close after next deploy.
