### ISSUE TITLE
Create a Spike of Visual Regression Testing with Applitools

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#27051]
## User Story

As a platform participant, I need a quick and intelligent analysis of my product for unexpected regressions resulting from the changes being integrated for each build.

## Expected Behavior

Visual regression testing tooling provides immediate feedback about regressions to the product that have a visual impact.

## Acceptance Criteria

- [ ] One product hosted on the platform is evaluated by a visual regression testing tool.
- [ ] The solution can be expanded upon to evaluate additional products.
- [ ] The results of the visual regression testing are easy to understand.
- [ ] Visual regression testing reports can be parsed and presented in a unified QA dashboard.
- [ ] Determine whether Applitools is capable of snapshotting platform hosted products in Internet Explorer 11
- [ ] Quantify the impact to execution time when Cypress specs contain Applitools snapshots
- [ ] Verify that Applitools is compatible with our E2E test parallelization solution

**Comment by holdenhinkle** [comment]
I chatted with Applitools. They say Cypress tests can run in parallel and gave me a link to their site 
 - https://applitools.com/docs/topics/overview/using-the-ultrafast-grid.html

---

The chat:

Keith
Hi Holden!

Holden
Hi there!
Two things: my product manager will be joining our meeting tomorrow. his name is Joe Tice. I sent him an invite.
So it will be Joe Tice, PM, Peter Hill, Engineer Lead, and myself...

Keith
That's perfectly fine. :)

Holden
Secondly, I'm going to try implementing Applitools into our Cypress tests which run in parallel in GitHub actions...
Does Applitools support tests that run in parallel?
For example - Percy (your competition) handles this nicely - https://docs.percy.io/docs/parallel-test-suites
And I got it to work easily...
However, Percy only runs in ci
Applitools is more flexible in that regard, which is why we're interested in Applitools.
** Percy is meant to run in CI. It uses GIT branches for logic

Keith
Cypress and Github is one of our most popular integrations. Tests can run in parallel on Cypress with the Ultra Fast Grid. We had a customer once run 300+ tests in under 3 minutes.
﻿
﻿You can find out more information about it here: https://applitools.com/docs/topics/overview/using-the-ultrafast-grid.html
﻿https://applitools.com/blog/cross-browser-testing-stiennon/

My colleague, Seth, can go over it in more detail over the call tomorrow.

Holden
We have ~150 cypress spec files. We divide the files amongst 6 different machines and they're executed in parallel. We want to take snapshots of pages while Cypress tests are running and have Applitools analyze them.
Will applitools analyze each image individually? Or does it group them into a 'build' of all the tests (which is what Percy calls it)?

Keith
I am not sure what Percy refers to as a "build" of all tests. Applitools looks at each individual screenshot and will notify you when it spots a significant difference. If a difference is spotted that is similar amongst a multi-step test you can "group by similar differences" and collectively pass or fail screenshots grouped by that specific difference.

**Comment by holdenhinkle** [comment]
# GitHub integration
https://applitools.com/docs/topics/integrations/github-integration.html

From https://applitools.com/docs/topics/integrations/github-integration.html#Installing

> By default, GitHub integration closes a batch automatically once the CI build operation is completed. If your build runs concurrently or consists of multiple test and you want all of the results to appear together in a single batch, you need to disable automatic closing of the batch and close the batch explicitly when the build is complete in your CI.

I’ve been searching and searching using the words ‘applitools’ and ‘parallel’… They use the word ‘concurrently’ here…

# Synchronizing multiple concurrent builds
https://applitools.com/docs/topics/integrations/github-integration-ci-setup.html#SynchronizeBuilds

By setting the APPLITOOLS_BATCH_ID environment variable, as described in the previous section, you instruct Eyes to put the results of all tests in a particular CI build in the same Test Manager batch. If your CI runs multiple builds concurrently, then you need to follow two more steps :

1. In the GitHub integration page of the Test Manager, follow the instructions to disable automatic batch closing described in the article Enabling the Eyes GitHub integration. This is a one-time configuration that needs to be done by each team for each repository that has concurrent builds.

2. You need to indicate to Eyes when all of the concurrent builds have completed. You do this by sending the Eyes server an HTTP command. How you do this depends on your environment. For example, on a Linux-based system you can do it as follows:

```
eyesserver="eyesapi.applitools.com"  # set this to your Eyes server name.
githubserver="your_gituhub_server"   # as entered in the Eyes/github integration screen e.g. github.com
apikey=$APPLITOOLS_API_KEY
batchid=$APPLITOOLS_BATCH_ID         # this was previously set to the CommitSha	
url="https://$eyesserver/api/externals/github/servers/$githubserver/commit/$batchid/complete?apiKey=$apiKey"
header="Content-Type: application/json --data `{\"serverId\": \"$githubserver", \"commitSha\": \"$batchid\"}`"	
extraInfo="-H $header  -v -L"

curl -X POST $url $extraInfo
```

Note that various values represented here as "$xxxx" are values set in other parts of the integration:
- $eyesserver: The URL of your eyes server - the same value that you set when defining the Eyes server when you run visual Eyes tests (or the default shown in the snippet above).
- $githubserver: The GitHub server you entered on the Eyes/GitHub integration screen as described in Enabling the Eyes GitHub integration.
- $apikey: The same API key you use when running visual Eyes tests.
- $batchid: The unique value that defines the batch. It is the value assigned to the APPLITOOLS_BATCH_ID environment variable, as described in the section Setting up the start of the build above.

**Comment by holdenhinkle** [comment]
I'm pausing this until further notice, based on the cost of Applitools.

**Comment by JoeTice** [comment]
This is no longer a viable option based on cost, removing this from Icebox and moving it to 'Closed'
