### ISSUE TITLE
Analytics Implementation or QA Support for AFS-Education team - GI Bill Comparison Tool Redesign 

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#27074]
# Google Analytics Implementation or QA Request

> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?

Implementation

- Who is this request for?

    - Abe Blanco, Gina Ronat

    _Provide any relevant contact information and link this issue on the DSVA Slack Channel: `#VFS-Platform-Support` and tag `@platform-analytics`._
    
- What team/project is this work for?  
    - Education Benefits / AFS-Education team (originally was Booz Allen team)
    
- Provide the Domain where Google Analytics needs to be implemented
    
    - https://staging.va.gov/gi-bill-comparison-tool-sandbox/

No PII is passed in the URL or title

- Please provide any upcoming deadlines or important milestones
    _ex: launch_
    
    - Beta release (testing) on staging: 8/30/21

- Please provide website interactions to Track

**We want to track everything that generally would be tracked** (no opt-out of standard component tracking)

- *Conversions - Understanding the User Flow:* 
_This application currently exists in VA Staging / Sandbox environment_
    - Landing page https://staging.va.gov/gi-bill-comparison-tool-sandbox/
    - Comparison page https://staging.va.gov/gi-bill-comparison-tool-sandbox/compare/?facilities=31002214%2C31048113 (typical, these are 2 specific institutions) 
    - Profile page https://staging.va.gov/gi-bill-comparison-tool-sandbox/profile/31002214 (typical, this is a specific school)
    

  - *Other User Interactions*: 
    
  - Other interactions listed here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/redesign/design/analytics.md

- Sample Users when authentication is required _**N/A**_

- Test Users to replicate the event _**N/A**_

- Additional Comments
 

> Please leave the following blank

## Acceptance Criteria
- [ ] [All items of checklist have been executed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/customer-support-guide-v2.md#%EF%B8%8F-checklist-before-closing-any-ticket)
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed
- [ ] Platform: [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) is updated

**Comment by bsmartin-ep** [comment]
Apologies for the delay @amyknox.  I'll have your mega analytics document prepared shortly, but had a few clarifying questions.

1.  In general, are we making a clean break from the old GIBCT analytics?  Most (if not all) of the old tagging seems to be represented in your request, but wanted to make sure we only want to track what is in your document.  If you need me to outline what might be missing, let me know.<br><br>One thing I'm doing is cutting GIBCT over to the standard site search event, which will let us add the data to our [Search KPI dashboard in Domo](https://va-gov.domo.com/page/1964748112?).

2.  Would this component be considered a variation of an [alert box](https://design.va.gov/storybook/?path=/docs/components-va-alert--default)?  Or is it a re-styled accordion / additional info?

![image](https://user-images.githubusercontent.com/62304138/127004571-700417f8-a5d5-4f53-8b5b-dd763412d222.png)

3.  "Cautionary warnings" are a characteristic of the school (or branch), correct?  And not reliant on something the user did?  If it's the former, I think we just add an extra custom dimension - like schoolHasWarnings = true - to the pageview.

> For schools with cautionary warnings, do users visit profiles?

4.  Can you point me to these two interactions in the sandbox?

> User exits to About this tool page

> User downloads data on all schools (Excel download)

**Comment by amyknox** [comment]
> In general, are we making a clean break from the old GIBCT analytics? 

Yes - a clean break but we don't want to lose the old analytics so we can compare before & after. 

> Most (if not all) of the old tagging seems to be represented in your request, but wanted to make sure we only want to track what is in your document. If you need me to outline what might be missing, let me know.

Thanks for the offer to identify what's missing in this new request.  I would really appreciate your insights on that.

> One thing I'm doing is cutting GIBCT over to the standard site search event, which will let us add the data to our Search KPI dashboard in Domo.

I'm ok with that as long as we can still get to the GIBCT search results on their own. 

> Would this component be considered a variation of an alert box? Or is it a re-styled accordion / additional info?

Yes - the "Cautionary warnings" are an alert box - with bonus interaction. 

> "Cautionary warnings" are a characteristic of the school (or branch), correct? And not reliant on something the user did? If it's the former, I think we just add an extra custom dimension - like schoolHasWarnings = true - to the pageview.

Yes, Cautionary warnings show up based on data associated with the institution's facility number.  Their appearance has nothing to do with UI.  However, we are interested to see if users click the carat to open a cautionary warning and read the full warning content. 

> For schools with cautionary warnings, do users visit profiles?

Users _can_ visit the school profiles but one goal of these cautionary warning is to discourage those visits.  Since the cautionary warnings come & go on the profiles, it's difficult to track which specific profiles have them but perhaps we can aggregate open/close/visits.  ?? 

> Can you point me to these two interactions in the sandbox?
> User exits to About this tool page>
> User downloads data on all schools (Excel download)

For "About this tool" page... users can get there via many of the "Learn more" modals
![image](https://user-images.githubusercontent.com/41081945/127008303-0c7cacad-f300-46e9-8874-7d34fa13432d.png)
![image](https://user-images.githubusercontent.com/41081945/127008403-21357c77-1183-41fb-bcd0-1cb48cc88c84.png)


And for "About this tool" and "Download all data", there will be links at the bottom of the search, compare and profile pages similar to what's on production now.  These are missing from the sandbox right now but you can [see them in action here](https://www.va.gov/gi-bill-comparison-tool/).

**Comment by bsmartin-ep** [comment]
@amyknox -

> Yes - a clean break but we don't want to lose the old analytics so we can compare before & after.

Definitely!  Most of the events will be slightly restructured, so getting all historical data in **one** GA report might be tough.  But the events will be in there.

> Thanks for the offer to identify what's missing in this new request. I would really appreciate your insights on that.

I double checked everything and I think everything in the current GTM tagging is represented in your request.  We would like you to transition from GIBCT specific tags to our more generic tagging, but all your form interactions, modal clicks _etc_ are in the new doc.

> I'm ok with that as long as we can still get to the GIBCT search results on their own.

Absolutely!  One of the parameters is `search-selection` which identifies which search it is.  You will have that + the page path of the event.

> Yes - the "Cautionary warnings" are an alert box - with bonus interaction.

OK - we have analytics baked into the alert box component, but only the link clicks in the content.  We can map out  a`nav-` event for this.

> Users can visit the school profiles but one goal of these cautionary warning is to discourage those visits. Since the cautionary warnings come & go on the profiles, it's difficult to track which specific profiles have them but perhaps we can aggregate open/close/visits. ??

I'll get some sort of identifying dimension into this - like the heading of the school block - so we can map this process.  It may be a job for BigQuery to be honest.

**Comment by bsmartin-ep** [comment]
## Components or manual?

Depending on how you approach this, we may only need to define a few of these interactions for you.

Some of this is already tracked, but using old and GIBCT-specific events.  This is probably our best opportunity to fix this particular tech debt.  It will make the transiition to GA4 easier plus get your interactions onto our [KPI Content dashboard](https://va-gov.domo.com/page/426422632?userId=2108773409).

Ideally your developers would use the React or web components that have analytics baked-in for form interactions, accordions, and modals.  Otherwise, we would need to manually push in our updated event taxonomy for these events. We also now have generic **link_click** and **button_click** events to use for those interactions.  

----

### Accordions
This is currently tracking in your demos, but is using the old event taxonomy (`nav-accordion-expand|collapse` vs `int-accordion-expand|collapse`).  Ideally, this is replaced with the [va-accordion](https://design.va.gov/storybook/?path=/docs/components-va-accordion--default) web component, which has analytics built in.  Otherwise, you should [update your manual dataLayer push to the new event](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md#:~:text=of%20the%20button%60-,Accordions,-%3Cva-accordion%3E).

### Radio buttons / selects / checkboxes
Ideally, these would be updated to use the new web components ([va-select](https://design.va.gov/storybook/?path=/docs/components-va-select--default), [va-checkbox](https://design.va.gov/storybook/?path=/docs/components-va-checkbox--default), [RadioButtons](https://design.va.gov/storybook/?path=/docs/components-radiobuttons--default) - soon to be a web component as well).  For these form components, if you add an enableAnalytics parameter, they will log events in GA.  

Otherwise, you will need to manually push an event for these interactions - [which can be found her](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md#:~:text=Form%20Controls%20-%20Select%20box)e.  All existing `gibct-form-change` events should be updated.

### Modals
If these can be updated to use the component library's [Modal](https://design.va.gov/components/modal).  Otherwise, the `gibct-modal-link-click` event should be updated to use the [new modal event](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md#:~:text=%27event%27%3A%20%27-,int-modal-click,-%27%2C%0A%27modal-status%27%3A%20this).

### Link Clicks
Out of the box, you can look at a pageview's URL + Previous Page Path and back your way into a lot of link clicks.  But if manual and deliberate tracking of link clicks is desirable - or necessary if a link doesn't change the page URL - we recommend our `link_click` event.  Documentation incoming for this.

### Button Clicks
We have a `button_click` event that we can use for this. Most of the parameters are straightforward, but we'll have to map out the button types for you. Documentation incoming for this.

**Comment by amyknox** [comment]
@bsmartin-ep - thanks for all the intel.  Is this ready for us now or is there more mega doc in the works?

**Comment by amyknox** [comment]
@bsmartin-ep - great - I can pass this info on to our BA.  Where do we look to access the events for search, link clicks & button clicks?

**Comment by dneel-bah** [comment]
@bsmartin-ep After discussing with the team, we're going to have to proceed with the manual route.  I see that we have link, button and search guidance above.  Is similar guidance available for Accordions, Radio buttons / selects / checkboxes, and modals?

**Comment by bsmartin-ep** [comment]
@amyknox - our Confluence docs are still a WIP but all form tracking events can be found here:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md

**Comment by bsmartin-ep** [comment]
Apologies @dneel-bah - I meant to tag you...

> Our Confluence docs are still a WIP but all form tracking events can be found here:
> 
> https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/tracking-design-system-components.md

**Comment by joanneesteban** [comment]
Platform Analytics will be moving this ticket to blocked until another VFS team takes this up.

**Comment by ERRonat0609** [comment]
The above issues associated with this issue were closed as duplicates of the following issues that are in progress now:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32625
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32626
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32627
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32629
https://github.com/department-of-veterans-affairs/va.gov-team/issues/32631

**Comment by bsmartin-ep** [comment]
## QA - WIP

GTM container:
https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000578

Interaction | Data Layer | Tag
----|-----|-----
