### ISSUE TITLE
Research IAL implementation constraints for VA.gov

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#27089]
ID.me has the capability to process IAL1 and IAL2 instead of LOA1 and LOA3, Login.gov also prefers the usage of IAL. This ticket asks the backend team to research any potential issues with dependencies on the LOA credential and naming convention. What would it take to flip to using IAL.

**Comment by bosawt** [comment]
Looks like we aren't able to use this as it will break some of our SSO partners. It seems like we won't get around to this anytime soon, so probably best to close this and come back to it later. 

To be clear, from vets-api standpint, we can convert LOA to IAL no problem, but since this breaks partners, we will need them to make changes before we can make the conversion
