### ISSUE TITLE
Move up home screen buttons

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#27115]
## Background
We'd like to maintain the spacing between the 'Sign In' button and the 'Find a VA Location' button but move them both up 80 total pixels away from the bottom of the screen to make the screen look more visually balanced & avoid any potential for interference with the swipe-up control. 

## Reference screenshot
![homescreen-reference.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/7b43f702-dc51-40fa-9ef9-f64a22304250)

## Acceptance Criteria 

- [x] Create a new dimension in the theme called `loginContentMarginBottom` and set it to 80px

- [x] Change the margin bottom on the login screen from `contentMarginBottom` to `loginContentMarginBottom`

- [x] Test on iPhone 11

## Accessibility Guidelines
* No changes to the current accessibility requirements for this button
Title: "Find a VA Location"
accessibilityRole: Button
accessibilityHint: "Go to VA Facility Locator"

**Comment by travis-newby** [comment]
There are a couple of issues here...

1. Originally there was a bug. Find a VA location was super close to the swipe up control because someone used the wrong margin between them. That issue was fixed (and will be a part of the 1.0 release).
2. So now the question is, is the standard spacing enough space so that there's not as much interference between the swipe up control and the button and does it look visually balanced. I'll leave that up to the design team.

**Comment by bridgethapner** [comment]
Thanks @travis-newby! Good to know the bug was fixed. I think it does still look low visually -- even though I'm not experiencing interference with the swipe up is just looks really close, so we can keep this open and increase the spacing.

**Comment by lexicalninja** [comment]
Updated the ACs just a little bit.

**Comment by digitalken** [comment]
PASS 7/14/2021 - Looks good on Android and iOS.  Accessibility passed, also.  Closing.
