### ISSUE TITLE
Remove or fix  "opt out" tagging from GTM

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#27125]
We have a `Opt Out Clicked` event that fires when someone opts out of GA tracking.  This is not recording in GA because the cookie update takes effect before the dataLayer push, thereby blocking the event from reaching GA.

My recommendation is removing the `Opt Out Clicked` tag and trigger from GTM or - if this is useful - update the code to fire the dataLayer push.

**Comment by laurensimpson14** [comment]
I agree, I don't think that the `Opt Out Clicked` tag and trigger are useful. I've gone ahead and deleted those. 

@bsmartin-ep I noticed that we have an event called `Education - Virtual PV - Opt Out Modal`, however when the `Opt Out` button is clicked on [this page](https://www.va.gov/education/opt-out-information-sharing) it also fires the `Interaction` event for the Modal Click. I think since we're gathering this info via the `Interaction` event then we can delete the `Education - Virtual PV - Opt Out Modal` tag. Thoughts?

**Comment by bsmartin-ep** [comment]
Published to production.  Closing.
