### ISSUE TITLE
tome-sync filter entities based on published state

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#2717]
## Problem Statement
We need to filter out unpublished content when doing the normal content build, but have a way to _not_ filter unpublished content for the preview server

## Acceptance Criteria
- [ ] Unpublished content is filtered out by default
- [ ] The entity tree assembler accepts an argument which causes unpublished content to _not_ be filtered out

**Comment by ElijahLynn** [comment]
tome-sync only exports published entities by default and since it is on disk the entire filesystem in the default export folder is considered to be published. 

For the preview server, maybe we can have the preview hook first tome:export to a subfolder just for preview. The default folder is `content`so maybe `content/preview/<nid>/<rid>/node.<UUID>.json?

cc @mortenson (maintainer)

**Comment by cvalarida** [comment]
Thanks for that insight, @ElijahLynn. Don't think we actually need this one, then. Closing.
