### ISSUE TITLE
Create consistent 'action color' in UI

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#27186]
## Background
Improve consistency in action/destructive patterns

## UX Actions
- [x] Identify colors for action/destructive actions

**Comment by melissa-lefevre** [comment]
Something to consider is to avoid using red buttons for normal call to actions, otherwise you’ll alarm users. Reserve them for destructive actions only. We follow this for the most part but we do have red for the crisis hotline, perhaps it is worth considering alternatives here. 

All of the actions in the top right of the nav are affirmative such as "Save" and all of the top left are dismissive taking the user back to a previous screen such as "Back" and "Cancel." 

Destructive actions like "delete" or "remove address" should be red. In a modal type screen or a confirmation screen, where the affirmative action is destructive, it can be solid red. However when the destructive action is not the CTA, it should not be solid or red to avoid accidentally selecting it. On the left if the current version and the right is my suggestion: 

<img width="525" alt="Screen Shot 2021-07-14 at 10 34 30 AM" src="https://user-images.githubusercontent.com/79866060/125641529-6761852c-60e0-4ac5-82ad-c82c4c22b17e.png">


I found these articles helpful: https://uxframework.pearson.com/c/buttons/v2.2.3 
https://uxmovement.com/buttons/how-to-design-destructive-actions-that-prevent-data-loss/

**Comment by bridgethapner** [comment]
@melissa-lefevre This is great! Is the re-color of the "Remove" buttons in Profile ready to become a FE ticket?

**Comment by melissa-lefevre** [comment]
Yes. 
![01-Default Copy](https://user-images.githubusercontent.com/79866060/125666352-dca3c1c2-0b3a-4de7-89f8-c0552bb4acf4.png)

**Comment by melissa-lefevre** [comment]
User Story: 
As a user I feel frustrated when the button I want to select is grayed out because it looks disabled. I need a clear affordance.  

Change: 
The chevron on a white background throughout the app to Primary-blue #0071bb

Example: 
<img width="419" alt="Screen Shot 2021-07-14 at 3 13 19 PM" src="https://user-images.githubusercontent.com/79866060/125679420-2b2ac04d-3122-4027-9278-1441f3e0b0e3.png">

Instances:
1. Simple List table 
2. Default list table
3. Lists / Secure Message List / Rows / Default Message Row
