### ISSUE TITLE
Leaving the App UI

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va.gov-team#27188]
## Background
When users click on a link that directs them outside of the app, we'd like to explore a UI pattern that indicates to users that they will be leaving the app.  

## UX Actions

- [x] Develop UI pattern
- [x] Understand accessibility implications

**Comment by melissa-lefevre** [comment]
![Leaving the app blue](https://user-images.githubusercontent.com/79866060/125651541-c766ba65-1070-44dd-87c9-756e37b33a44.png)

A11y Considerations:
It seems like the most important thing to consider here not abruptly changing the context. Especially for low vision users we need to make sure there is a clear transition ie a confirmation to inform the user that they are being redirected and give them the option to stay if that is not what they were trying to do. This will prevent confusion of all of the sudden change of context.

As far as opening a website outside of the app vs opening an website within a frame, I am not seeing exact WCAG guidelines for that. The guidelines around progressive enhancement seem like they could be applicable here but I am not 100% sure how it applies to an app since it is for the web. When the user opens a site like the covid site that keeps them in the app, I would not suggest the same "you are leaving pattern" and only apply this to the situations when the user is being redirected to their browser.
