### ISSUE TITLE
Upgrade Sentry npm package

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#27231]
We need to upgrade Sentry in order to dial down the amount of duplicative alerts coming in. The current version in vets-website and content-build is `^5.4.0`, however the latest release is [6.9.0](https://www.npmjs.com/package/@sentry/browser).

Definition of Done

- [x] Figure out if we need sentry in both vets-website and content-build
- [ ] Remove it from one repo if we don't need it
- [x] Upgrade where applicable 
- [x] Make sure sentry is still reporting and there are no errors

**Comment by timwright12** [comment]
Update here. Confirmed that Sentry is used a lot in vets-website. It is used only once in content-build for the mocha-setup.js:
```
Sentry.init({
  transport: sentryTransport,
});
```

Not entirely sure what that's doing, but we can upgrade it in both repos to be safe

**Comment by theodur** [comment]
I agree, we might as well update Sentry in both repos to be safe. I'll dig into it's use in the content-build repo as I begin working on this ticket.

**Comment by theodur** [comment]
Looking at the [release notes](https://github.com/getsentry/sentry-javascript/releases/tag/6.0.0) for `v6.0.0`, the most recent major release, it states:

> This major version release doesn't contain any breaking API/code changes.

Hence, why they didn't make migration guide like they did for [upgrading from v4.x to v5.x](https://github.com/getsentry/sentry-javascript/blob/master/MIGRATION.md). I didn't have to change much code, other than setting the `autoSessionTracking` to `false` since it's enabled by default in `v6.x`, and updating the fake DSN that's used in our Mocha setup.

One interesting issue I ran into was getting a unit test in the forms system, [SubmitController.unit.spec.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms-system/test/js/review/SubmitController.unit.spec.jsx), to pass with the new upgrade. I kept receiving the following error:
```shell
Error
expected 0 to equal 1
Stacktrace
AssertionError: expected 0 to equal 1
    at Context.<anonymous> (src/platform/forms-system/test/js/review/SubmitController.unit.spec.jsx:413:37)
    at Test.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
    at Hook.Runnable.run (node_modules/mocha-snapshots/src/index.js:19:22)
    at processImmediate (internal/timers.js:461:21)
```
This was ultimately due to the `beforeEach` and `afterEach` Mocha hooks calling the `testkit.reset()` function. The Sentry testkit was only used in one test in the block, and resetting it in tests where it wasn't used seemed to cause an issue. I ended up calling the `reset` function in a `before` hook so that it only gets reset once for the one test that uses it in that block.

**Comment by theodur** [comment]
In the `content-build` repo, Sentry is only referenced in our Mocha setup, so it would only be used in unit tests, specifically with the [Sentry Testkit](https://wix.github.io/sentry-testkit/#/). Currently, no unit tests in the repo are use Sentry Testkit. Technically, we could remove it from `content-build`, but it's possible that a developer may want to use it down the road. Keeping it would save us the hassle of needing to add it back in the repo if it's ever needed in the future. I went ahead and updated the version in this repo as well.

**Comment by theodur** [comment]
PRs for Sentry upgrades: 
- https://github.com/department-of-veterans-affairs/vets-website/pull/17899
- https://github.com/department-of-veterans-affairs/content-build/pull/376

**Comment by theodur** [comment]
After merging the PRs, I monitored Sentry and verified that errors are being reported as expected ✅.
