### ISSUE TITLE
Document MAPSUP ticket creation process

### ISSUE THREAD

**Issue by laurenernest** [department-of-veterans-affairs/va.gov-team#27347]
Document our current process for reporting issues in MAPSUP tickets. Including, but not limited to: information to include, dashboards/images, where to create the ticket.

**Comment by ajmagdub** [comment]
Usually the first indication that that we have an problem comes from Slack's **[#vaos-alerts](https://dsva.slack.com/archives/C016QB6T340)** channel on the **DSVA Service @VA** workspace.  The alert will look something like this:

![Grafana Error graph](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/4525c4f1-be34-4be1-b9f3-154420989962)

The next step is to gather information from our logging tools. Currently these consist of the VAOS alerts page on Grafana, [VAOS Alerts](http://grafana.vfs.va.gov/d/EmC4pa6Wz/vaos-alerts?orgId=1&from=1629547130060&to=1629564174841); vets-api server logs on AWS Cloudwatch, [Cloudwatch](https://console.amazonaws-us-gov.com/cloudwatch/home); and Sentry logs, [Sentry 
](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production). Note that in the near future viewing logs from AWS Cloudwatch will be replaced by Loki. Following is a snapshot of Cloudwatch logs:

![Cloudwatch logs](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/14744cce-d81b-449a-9e2b-acbc25da21c4)

Once the problem is understood, the next step would be to check Slacks **VA PPG Workspace** to see if the backend group has already identified the problem and is working on it.

**Comment by ajmagdub** [comment]
Usually the first indication that that we have an problem comes from Slack's **[vaos-alerts](https://dsva.slack.com/archives/C016QB6T340)** channel on the **DSVA Service @VA** workspace.  The alert will look something like this: 

![Alert from Slacks #vaos-alerts](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/2b7b64c8-ca87-4179-8407-06bba2ee8abd)
The next step is to gather information from our logging tools. Currently these consist of the VAOS alerts page on Grafana, [VAOS Alerts](http://grafana.vfs.va.gov/d/EmC4pa6Wz/vaos-alerts?orgId=1&from=1629547130060&to=1629564174841); vets-api server logs on AWS Cloudwatch, [Cloudwatch](https://console.amazonaws-us-gov.com/cloudwatch/home); and Sentry logs, [Sentry 
](http://sentry.vfs.va.gov/organizations/vsp/issues/?environment=production). Note that in the near future viewing logs from AWS Cloudwatch will be replaced by Loki. Following is a snapshot of Cloudwatch logs: 

![Grafana Alerts graph](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/1c200732-bae0-40f9-8d3c-a5911bf6b58d)

Once the problem is understood, the next step would be to check Slacks **VA PPG Workspace** to see if the backend group has already identified the problem and is working on it. 

If the problem is from the VAMF backend and the backend groups (MACM, CKM) are not aware of it the next steps are to create a MAPSUP ticket with the information gathered.  In order to create a MAPSUP ticket an Atlassian account is needed. Open the Issues browsing page in Jira, [Issues](https://issues.mobilehealth.va.gov/) and click on the Create link found on the right in the upper menu:

![Screen Shot 2021-08-23 at 9.47.13 AM.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/b49dce48-7cf2-4540-9dbb-4901e56f36cc)

**Select MAP Support (MAPSUP)** in the Project dropdown and fill out the relevant field on that page:

![Screen Shot 2021-08-23 at 9.52.15 AM.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/37349545-8f53-45ca-a5cf-5c498ae03351)

Click on the **Issue Report** section and fill in any relevant information gathered in discovery (making sure that production is selected in MAP Environment).

![Screen Shot 2021-08-23 at 9.55.44 AM.png](https://images.zenhubusercontent.com/58c9796351aa2c3057788fd5/f96520c3-4cc5-4b9a-aa13-ee02dfee32a8)

When all necessary information is entered click on the Create button.

**Comment by laurenernest** [comment]
@grossb1 @jbalboni where in our GH docs do you recommend we keep this info?

**Comment by jbalboni** [comment]
@laurenernest I think in here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/incident_response

**Comment by laurenernest** [comment]
> @laurenernest I think in here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/incident_response

@ajmagdub please add your steps to the location above. thanks!

**Comment by ajmagdub** [comment]
added MAPSUP ticket creation process to https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/appointments/va-online-scheduling/engineering/incident_response
