### ISSUE TITLE
Review and determine approach for feature toggle request

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#27352]
## Details 

VFS teams (specifically VFS) have submitted a feature request: Provide global access to feature flags on app start up #25105

The purpose of this ticket is to investigate the request, gather additional info as needed, and recommend a path forward. 

Possible outcomes might be: 
- Recommend implementation of the request
- Recommend implementation of the request but hand to another team to implement (BE Tools?) 
- Hand investigation to BE Tools 
- Do not recommend implementation of the request

... etc etc

**Comment by meganhkelley** [comment]
FE Tools team member comments: 

> There's a wider question with fetching flag values during the build process, which I think is what this ticket is proposing. It's helpful in some ways, but also it means that if we change a flag value, we have to wait until the next production deployment for the flag value to change for users. Not sure but it might require OCTODE to weigh in first

>Yeah, I’m not sure if that’s exactly what they want. It means you can’t just toggle the flag and have it take effect next time it’s loaded. Tying it to deployment would counter one of the benefits of using feature toggles. If the behavior is going to be determined during build, you might as well just use some hard-coded value in the conditional instead of basing it on a value in Flipper. This probably needs more clarification before work can start on it.

**Comment by k80bowman** [comment]
After reviewing the request and gathering information about other difficulties with our current feature toggle system, I am recommending that we not do anything with this right now, but that we leave this open for reconsideration later.

The main concern with our system right now is that there is a chance that a feature will load before the feature flag API request is returned. If the feature is inside of the React/Redux ecosystem, this should not be a concern, as the feature flags are stored in Redux. If the feature is outside of the React/Redux ecosystem, this is more of a concern, but still not something that is happening enough to cause large problems. 

Performing this call during our current build process (in order to have the feature flags loaded and ready when the applications load on the client) is not an option at this point. This would mean we wouldn't be able to turn feature flags on and off without a re-deploy of the applications and we wouldn't be able to use features like turning a feature flag on for only a percentage of users. These are essential features that we are not going to disable.

A real resolution to this would probably require server-rendering this call, which is a big shift and would require a lot of work to re-think how our applications work (and how we want them to work). This may be something we want to revisit later.

**Comment by ericboehs** [comment]
It looks like the original ask wasn't to do it at build time but rather at server render time (something we aren't doing). The value isn't immediately available in redux but it would be if done via SSR.

I'd say we close this ticket as SSR isn't something we are planning to do any time soon.
