### ISSUE TITLE
Remove "vets.gov" and "preview.va.gov" tagging from GTM 

### ISSUE THREAD

**Issue by bsmartin-ep** [department-of-veterans-affairs/va.gov-team#27405]
We still have several objects related to `vets.gov` and `preview.va.gov`.  As those domains are decommissioned, we can remove them...

- [x] `Environment Lookup IDs` contains two rows that can be removed
- [x] `Vets.gov Umbrella Tracking ID` can be removed
- [x] `Testing Tracker ID` can be removed
- [x] `Navigation Click - Vets.gov to Preview Button` and its trigger `Sitewide Alert - preview.va.gov Button Click` can be removed
- [x] Remove vets.gov from `Cross-Domains` variable
- [x] `Content Grouping - Hostname` is unused and can be removed
- [x] I would also like to update and rename tag `Exception - preview.va.gov` to `Exception - dev.val.gov and staging.va.gov only` and remove the `preview` reference. (`Page Hostname = (dev|staging)\.va\.gov`)

**Comment by laurensimpson14** [comment]
I deleted 3 rows in the `Environment Lookup IDs` variable: 
1.  `(dev|staging|preview)\.vets\.gov` that had the output of `{{Testing Tracker ID}}` (also deleted)
2.  `vets\.gov` that had the output of `{{Vets.gov Umbrella Tracking ID}}` (also deleted)
3.  `^www\.|preview\.)?va\.gov` that had the output of `{{WBC VA.gov Production Tracking ID}} (also deleted since the default value of this lookup table is the prod tracking ID: UA-50123418-16)

**Comment by bsmartin-ep** [comment]
LGTM though I did restore the `{{WBC VA.gov Production Tracking ID}}` so we don't have the value hardcoded anywhere.

**Comment by bsmartin-ep** [comment]
Published to production.  Closing.
