### ISSUE TITLE
Disability Rating

### ISSUE THREAD

**Issue by bridgethapner** [department-of-veterans-affairs/va.gov-team#27418]
# User Story
As a user, I want to view my total combined and individual disability ratings in the app.

### Notes
We should look at making the various user calls that make up this response in parallel.

**Comment by melissa-lefevre** [comment]
Specs: 
Profile header with Disability rating
Background color: Primary #0071BB 
Headline text: Bitter Bold
Headline color: white #ffffff
Subhead: Mobile Body
Subhead color: white #ffffff
Margin: no gutter L/R; marginBetween vertical 
Internal padding: 20px total
![Profile.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/fad339d5-a8eb-489c-9075-1faeece9a18b)

Q: What happens if the Veteran has a Pension with Aid and Assistance? Does it show?
A: No. Currently we are only showing service connected disability ratings... we might eventually work to incorporate other ratings in the future. But that would be down the line some time.

Q: What happens if they don't have a disability rating?
A: The area where it would say % combined disability rating, is blank
![Profile disability blank.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/56792d52-2a4c-4479-9f36-c465ba0b9ec0)

Q: What happens if the disability rating tool is down? 
A: In the event of an error state where we can not connect to the disability endpoint, show a generic "View disability rating" link instead of the customized link with the rating. We realize this means that some people who do not have a disability rating may see that link, and that is OK.
![Profile disability down.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/cb332559-f567-4111-9a8f-9c7eb001e889)

Here is a link to the decision making done by the web team:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/frontend/documentation/nametag.md

**Comment by melissa-lefevre** [comment]
**Disability Rating screen**
![disabilityrating.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/30d40b12-632d-4364-86dc-c29f2375e5a1)

Disability rating card
Background color: white #ffffff
Margin: 0px between rows
Internal padding: 10px between rows of text
Border-bottom: 1px solid gray-light #aeb0b5
Headline text: Mobile Body Bold
Body text: Mobile Body

List title is the “list header” component

List Header
Background color: AEB0B5
L/R gutters: 20px gutters to the L/R
Margin: 0px between rows
Internal padding: 10px 
Border-bottom: 1px solid gray-light #aeb0b5
Text: Mobile Body Bold

The icon in the “Learn about VA disabilities” section is the visit the web button.

**Comment by ashley-matthews** [comment]
I've added the above screenshots/details to the appropriate FE disability tickets.
