### ISSUE TITLE
Content request from Decision Tools Team

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#27427]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
-	[ ] Writing/editing to update existing unauthenticated (static) VA.gov page
-	[X] Content support for an app or tool
-	[ ] Something else (please add details in the next question)

## What do you need help with?

In our most recent Staging review, an issue was raised related to the label on our "Go to online tool" button. 
 Please see https://github.com/department-of-veterans-affairs/va.gov-team/issues/26907.  
 
 We need some guidance on a better way to label this button, considering that:

- Multiple instances of this button can appear on the [Find a Form search results page](See https://www.va.gov/find-forms/?q=10-10e) for different forms 
- In some cases the button links to an web app-based version of the form, and in others it links to another VA site (insurance.va.gov or AccessVA) where they can answer questions/submit info.

## When does this content work need to be done?
- As soon as the content team's schedule allows.

*In addition to the date you need this content work to be done, please let us know the ETA for the app/tool launch.*
- The tool is already in Production.  See https://www.va.gov/find-forms/?q=10-10e and https://www.va.gov/find-forms/about-form-10-10ez/

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: John Hashimoto
-	Product manager: Marci McGuire
-	Designer: Cassandra Allen
-	FE engineer: Zach Morel
-	Product/team Slack channel: #vsa-decision-tools

## Links to related tickets
https://github.com/department-of-veterans-affairs/va.gov-team/issues/26907

## Next steps

Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.	

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).

**Comment by bethpottsVADEPO** [comment]
@joshkimux @AngelaFowler82 I wasn't sure who on the accessibility side to tag here since you both seem to have been involved in the original collab cycle feedback and how it relates to Spanish translation in a separate ticket. So I'll let you two decide who should respond! But I'd love your feedback on my suggestions outlined here. 

@MarciMcGuireGCIO asked for content help reworking the action link label that's currently "Go to the online tool." I see an opportunity to improve surrounding and related text as well. I'd like to do something like this:

1. Add an H2 called "How to submit this form" to more appropriately house the 2 options users have to submit either a paper form or an online form. I put here the previous for context.
2. Add "Option 1" and "Option 2" before the 2 options. 
3. Tell the user where they are going by changing the action link to "Go to VA Form XYZ online"

It would look like this:

**H2: When to use this form**

Use VA Form 10-10EZ if you’re a Veteran and want to apply for VA health care. You must be enrolled in VA health care to get care at VA health facilities or to have us cover your care at a community care provider (an approved non-VA provider).  


**H2: How to submit this form**

**Option 1: Download a PDF form to fill out and submit by mail or in person**
Use this option if you want to submit a paper form.
TEXT LINK Download VA Form 10-10EZ

**Option 2: Fill out and submit this form online**
ACTION LINK Go to VA Form XYZ online

**Comment by MarciMcGuireGCIO** [comment]
@bethpottsVADEPO - Thank you so much for helping us out with this copy.  Chiming in re: the above. 

For the PDF option, we will also need to eventually include the PDF alert info that we preparing to test for the search page.  Users need to be made aware they need to fill the PDF forms with Adobe Reader since some don't open or don't work correctly in a browser.  

We may also want to consider reversing the order of Option 1 and Option 2 since we are trying to encourage folks to complete them online when possible.

Thanks!

**Comment by AngelaFowler82** [comment]
Sorry for the late response. This is much better. The only suggestion I would make is to add some descriptive text to the link I.E. “Download VA form 10EZ apply for VA health care.” This makes the purpose of the form more clear to those who are tabbing through links with a screen reader.

**Comment by bethpottsVADEPO** [comment]
@MarciMcGuireGCIO Good one! I agree with reversing the order of Options 1 and 2. Let's figure out separately how to handle Angela's suggestion to add the name of the form in addition to the number. That's a bigger ball of wax because of (PDF) already being there in parentheses. We should consider that, but let's not have it hold up the rest of the changes here.

@AngelaFowler82 Thanks so much for the input! Really appreciate it.

**Comment by MarciMcGuireGCIO** [comment]
Hello hello! Just wanted to see if there is any update for this as we prepare for our Sprint Planning.  Thanks!

**Comment by bethpottsVADEPO** [comment]
Sorry, @MarciMcGuireGCIO I thought we were all set with this. But of course now I've revisited and tweaked again! So I'm glad you pinged me. Let me know if you want to talk through any of this!

1st use case:
https://www.va.gov/find-forms/?q=10-10e
ACTION LINK Fill out VA Form 10-10EZ online online

2nd use case:
https://www.va.gov/find-forms/about-form-10-10ez/
**H2: When to use this form**

Use VA Form 10-10EZ if you’re a Veteran and want to apply for VA health care. You must be enrolled in VA health care to get care at VA health facilities or to have us cover your care at a community care provider (an approved non-VA provider).  

**H2: How to submit this form**

**Option 1:** Download a PDF form to fill out and submit by mail or in person
Use this option if you want to submit a paper form.
TEXT LINK Download VA Form 10-10EZ

**Option 2:** Fill out and submit this form online
ACTION LINK Fill out VA Form 10-10EZ online

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @bethpottsVADEPO !  This is very helpful!  We'll ping you if we have questions.

**Comment by MarciMcGuireGCIO** [comment]
Updating Beth's comment to reflect agreed-upon change to change the order of online tool vs. PDF (submit online will be first, PDF second)

**Comment by callen2563** [comment]
@bethpotts quick question: do you mean you want "H2: How to submit this form" under "H2: When to use this form" ?

**Comment by MarciMcGuireGCIO** [comment]
Looping in @bethpottsVADEPO.  Beth - can you answer @callen2563's question above? I think she has it right, but we just wanted to confirm.  Also, let us know if this copy is good in the mockup or if you want to tweak. Thanks!

**Comment by callen2563** [comment]
@MarciMcGuireGCIO @bethpotts I ended up figuring it out so I deleted the question I had posted for Beth but let me know if there any tweaks to these. thanks!

**Comment by MarciMcGuireGCIO** [comment]
Thanks for the update @callen2563 !  @bethpottsVADEPO - when you have a minute can you take a peek at Cassandra's mockups and see if you're still good with the copy?  Thx!

**Comment by bethpottsVADEPO** [comment]
@callen2563 @MarciMcGuireGCIO Sorry for the delay... meetings, meetings...

I like it! That's exactly what I intended with the two H2s. Let's get the content following Options 1 and 2 more consistent in style:

Option 1: Fill out and submit this form online. _(only change here is to add a period)_
Option 2: Download a PDF form to fill out. _(shorten the message, and add the part we're cutting to the next line of text)_
Use this option if you want to submit a paper form by mail or in person.

**Comment by MarciMcGuireGCIO** [comment]
@callen2563 when you get a minute, can you please make the two updates that Beth requested above?  Thx!
