### ISSUE TITLE
Content review - [auth experience] notification settings and sign in vs. contact email

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#27422]
# Background
**Update:** We aren't moving forward with the modal UX anymore.

We need review of a content update in the personal and contact section of profile, clarifying the difference between the contact and sign in email address.

## Notifications 
[Mock-up](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140375964/simulate/sitemap?mode=i)

### Confirmation message

You've updated your VA [channel] notifications.

<img src="https://user-images.githubusercontent.com/55992116/126001558-56d5917c-694f-49b3-a4ae-0cbe1217641b.png" width="50%" />

### FAQ 

[trigger label] Learn more about VA email and SMS text notification options.
[content] Currently, VA.gov can only offer some notifications by both email and text.  We working to add more notification options, and you will see them here when they are added.  

**Note:** The business reasons contributing to notification options are:
- Notification channels are determined by a request by the business lines
- The business lines do research before requesting to determine the appropriate channels
- Sometimes budget plays a part in this decision because notifications aren't free

![image](https://user-images.githubusercontent.com/55992116/125823801-a5bce695-ba68-46f4-869c-87ef025463eb.png)

## Contact vs Sign in email

[section heading] Email addresses

[label 1] Contact email
[hint text] This may be different from the email you use to sign in.

(display email address)
[buttons] edit , remove

[label 2] Sign in email
The email you use to sign in is managed separately from the email VA uses to contact you. You can view or [update your sign in email on ID.me]. (link to ID.me)

For reference, here is what we have now:
![image](https://user-images.githubusercontent.com/55992116/125823611-8960efe9-aa13-49f1-8e2e-54a556f33e0c.png)

and here is what I'm proposing:
![image](https://user-images.githubusercontent.com/55992116/125823651-02667cc8-fe10-4f7b-ae4b-712b63b4ded4.png)

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA there's also one point we didn't discuss. People found one notification name confusing in research:
"Scheduled payment updates"

They weren't sure what kind of payments that referred to.  That's a notification requested by the comp + pen team, so I'm recommending we update it to:

"Scheduled compensation and pension payment updates"

What do you think?

**Comment by andaleliz** [comment]
Actually, I was just reminded that payment update notification won't be part of our MVP, so we can revisit that verbiage down the road.

**Comment by andaleliz** [comment]
**Update:** we've had to pivot with our designs _again_ so we are no longer going with the modal UX 🙃

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA just checking in - any chance you were able to review this while I was out last week? Was hoping to provide updates to my team today and close this work out by the end of our sprint (ends tomorrow). Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi and welcome back, @andaleliz! Yep, will post comments today. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Morning, @andaleliz! Initial thoughts on content below. Happy to talk through more as needed.
- For the FAQ, let me know if you think this sounds right. This one felt a little tricky to me in messaging.
- For the contact vs. sign-in emails, let me know what you think about this version. It's shorter than what we talked about in slack because I'm thinking we may be able to remove the "This email may be different..." line from contact email and just get at that under "Sign-in email."  Would love your thoughts on whether this is too little context.
- Still have my open question about folks who sign in with an MHV or DS Logon account.

## Update notices

- Add a period at the end of the sentence ("You've updated your VA email notifications.")
- Make sure all of these are active voice and parallel. In the mockup, the notices when you check text are written differently.
- For the health care notifications, consider including more words in the My HealtheVet link to give screen readers more context than just the name of the site. We could remove the "Note" perhaps and just replace it with a link that reads:
[link] Manage your health care email notifications on My HealtheVet
Or possibly go shorter with just:
[link] Manage health email notifications on My HealtheVet

## FAQ
[trigger label] Learn more about notification options
[content] At this time, we can only offer some notifications by both email and text message. We're working to expand options for more notifications. You'll find new options here as we add them.

## Contact vs. sign-in email
[section heading] Email addresses
[label 1] Contact email
[hint text] We use this email to send you information.
 (display email address)
 [buttons] edit , remove
 
[label 2] Sign-in email
You may use a different email to sign in to VA.gov.
[Edit your sign-in email at ID.me] (link to ID.me)

**Comment by DanielleThierryUSDSVA** [comment]
FYSA @peggygannon @shiragoodman

**Comment by andaleliz** [comment]
Thanks Danielle! 
- The FAQ is **perfect**. Thank you!
- For contact vs. sign-in emails, I think that may not be enough context.  I'm hearing the voices of those participants asking specifically about why/how those were two different things.   What about
"The email you use to sign in to VA.gov may be different from your contact email"

I am **so glad** you asked that question about MHV and DS Logon. I still don't have an answer to that question, but I don't want that to block the overall improvement we're making.  Can we work on improving what is there, and then address the MHV/DS Logon discrepancy as a separate thing once we can learn more about it? I'll have to do some digging to learn more about that.

**Comment by andaleliz** [comment]
Oooph. This sign in email is a bit of a doozy.  I'll summarize the thread:
- Only ID.me actually uses an email address to sign in
- There is code in place in profile to detect how a person logged in, and update that URL and text in the "sign in email" section accordingly.  

IMO it doesn't even make sense to show this sign in email block to people who log in via MHV or DS Logon, if they don't use an email to log in.  It seems like it would be more appropriate under account settings, rather than "personal and contact information".  What do you think?

**Comment by andaleliz** [comment]
Good morning @DanielleThierryUSDSVA  

Just FYI, I created a new issue #27979 to dig into the question you brought up.  I'd like to move forward with this particular improvement with a tweak to the suggestion you made for the sign-in email:

[label 2] Sign-in email
The email you use to sign in to VA.gov may be different from your contact email.
[View or edit your sign-in email at ID.me] (link to ID.me)

Does that look good to you? If so, I'll close this out.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you, @andaleliz!

Agree, I like the added context. Always trying to balance keeping it brief with providing enough info, and I think this is a good balance.

If we can just change "View" to either "Check" or "Review" that would great. Aiming to avoid language that specifically implies sight. Thanks!

**Comment by andaleliz** [comment]
Ack, of course! Thanks for catching that. I'll update that to Review. Appreciate all your help!
