### ISSUE TITLE
Add language code field to nodes in CMS

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#27428]
## Description:

We need a field to set a language for a given page.
This field should most likely be a dropdown where several possible language options are available. (English, Spanish, Tagalog)

- [x] Add field to sidebar of cms node editing UI with 3 main options
![Screen Shot 2021-07-15 at 7.18.03 AM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/ddd0db59-241e-4031-a5f5-b42be9e58e1c)

- [ ] Document needs and requirements for using this new field data in the drupal liquid templates for translated pages
- [ ] Investigate displaying this field setting when using Entity Reference or Relation modules 

## Acceptance Criteria:

Demonstrate the ability to link the 3 Covid pages (English, Spanish and Tagalog) by using the relation module

- [ ] Query and return the correct page by using just the newly created field
- [ ] Query the current page's language

**Comment by adamwhitlock1** [comment]
As a demo environment a tugboat environment has been created at: 
[CMS Demo with Entity Reference and Language Code Fields](https://cms-ezgnp2mymxyqhi4wodnaouqxdbixtrwo.demo.cms.va.gov/)

The Language Code Field is a dropdown style field that has 'language name' as the label and the language code (es, en, tl, etc) as the value for each option.

![Screen Shot 2021-07-19 at 4.20.31 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/13c786d3-3ef5-42ac-856d-85e382d57245)

The resulting data can then be queried via GraphQl with a query similar to this:

![Screen Shot 2021-07-19 at 4.20.31 PM.png](https://images.zenhubusercontent.com/60ddebd504ce2452d0e0fa92/460ce47e-1f41-4fd3-ac0f-ac9b0f242d55)

**Comment by adamwhitlock1** [comment]
**Requirements for further usage:**

* Set the language on every 'content type' via this field, and otherwise default to english
* Every content type would eventually need this field added via drupal or within a custom drupal module. Right now the example only includes the Language Code field on the content type of 'Benefit Detail Page'.
* include this sub-query on the content-build process for this content type
* modify existing content-build drupal.liquid templates to utilize the field value
* modify existing react widget to perform additional dom manipulations based on language code value
* documentation needs / training for editors / workflow process refinement

**Additional Considerations**
This type of field is included and more deeply integrated if we were to use the built in translations/localization drupal module.

The available query for that value would look similar to this:
```
query getPageLanguageViaTranslationModule {
    nodeById(id: "11463") {
    title,
    langcode {
      value
    }
    entityUrl {
      path
    }
	}
}
```

**Comment by adamwhitlock1** [comment]
This work is now complete and ready to be closed. See the above comments for further details into the capabilities demonstrated.
