### ISSUE TITLE
[Discovery] Harassment Reporting Tool - Ongoing content strategy and content design work

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27438]
_The Office of Resolution Management, Diversity and Inclusion (ORDMI) is the office in-charge VA Wide for processing complaints from Veterans and Employees for alleged Civil Rights Violations as well as for Harassment, Reasonable Accommodations, and other inappropriate behaviors while on a VA Site._

_In response to Section 5303 of the Deborah Sampson Act which is part of the Megabus Bill that was passed in January, and new congressional demands for action, a team of Presidential Innovation Fellows (PIFs) is scoping the feasibility of creating a secure, online reporting tool on VA.gov that would enable Veterans and VA employees to report alleged incidents about violations from Veterans and VA employees which occur while on a VA Site._

Tasks:
- [x] Collaborate with Content team on Content needs for the HRT initiative 
- [x] Review provided content from VA.gov Business Partners to ensure it meets VA.gov content standards 
- [x] Provide feedback in support of mockups and provide suggestions on updates, fixes, changes
- [x] Work with Public Website designer to ensure content tickets are submitted in support of content needs for HRT

**Comment by callen2563** [comment]
[HRT Flow Mural Board](https://app.mural.co/t/vsa8243/m/vsa8243/1625100817340/c87980e063ad3ee8eebcb54ee1a76474d97b882e?sender=u7ad68f2a3a694c00d8a38130)

[Initial HRT Sketch Mocks](https://www.sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

**Comment by callen2563** [comment]
Here is a mock up for the unauthenticated HRT content page that will need some content help:

![HT-Content page - Unauthenticated - Desktop](https://user-images.githubusercontent.com/68560244/127703576-8a5f22fe-0fda-4245-9bb2-82e2bcbf4247.png)

**Comment by johnhashva** [comment]
Great start @callen2563 -- thanks for this "starting point"!

**Comment by callen2563** [comment]
I have updated this content page using the PDF flyer that Soni sent over but I'm sure there will be changes once Danielle starts working on the content for this page.
![HT-Content page - Unauthenticated - Desktop](https://user-images.githubusercontent.com/68560244/128086017-d5a2407a-b291-4307-be30-2156df9bc460.png)

@DanielleThierryUSDSVA Here is a copy of the PDF for content to refer to as it has the approved copy:
[VA HPP Infographic (07302020 FINAL)pja edits (002) updated by Michelle 5-27-2021pja.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/6927058/VA.HPP.Infographic.07302020.FINAL.pja.edits.002.updated.by.Michelle.5-27-2021pja.pdf)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @callen2563 @johnhashva @brianalloyd ! I've started to do some content strategy thinking on this and the content in the tool (from , and talked with @mnorthuis today about IA. Some questions and thoughts that we had to start:

- I'd provided an example of a tool landing page as requested. But that was before I realized this was also going to have an intro page. Since it has an intro page, I don't think we need a tool landing page but rather a simple detail "how to" type page. The main difference is that, instead of a sign-in widget we would just have a button that goes to the intro page. This is the way we would typically do a "how-to" type of page that leads into a form. 

**Some questions:**
- Question: What is the purpose behind asking the person filing the report to characterize the type of harassment (i.e. "harassment" vs. "sexual harassment" vs. "sexual assault") instead of having someone on the backend use the details provided to do this characterization? Our questions/concerns here are:
  - The person filling out this form has been through a difficult experience, so asking them to do this work is an added burden. Are we required to have them give this information?
  - We would imagine some folks could be unsure of which type to pick, even with examples or definitions. This could cause added stress to an already stressful experience. If we do need this information about type of harassment, could we potentially ask them different questions to make it easier? For example, if the only thing we really need to know is whether this was a physical assault (so we can prompt the person to contact the police), could we just ask something like, "Did this incident involve any type of physical contact?"
- Is there an option for the person to request to provide details about the incident later? And/or do we know when and how they'll be asked about the details again later in the process? We could include some content to the effect of, "Please share what you can about what happened here. We'll also need to ask you for more details later so we can understand how to best help you..." 
- Would it be helpful to helpful the person understand when to file a harassment report vs. a discrimination complaint?
- We'd like to make sure that we provide information about how to get mental health services on this page and likely throughout the experience of filling out the form.
- VA employees should **not** use this form to report harassment at this time, correct? 
- Anyone who uses this form **must** sign in (even if they're not a Veteran), correct? If yes, we'll need to change the "save time/save in progress by signing in" component to a simple "sign-in" button since they're not getting an added benefit by signing in...but rather they have to sign in to continue. 
  - Connected to this, we want to confirm that the person filing the report can save their report and come back later to finish it, correct?

**Comment by DanielleThierryUSDSVA** [comment]
Above updated w/ an added question.

**Comment by DanielleThierryUSDSVA** [comment]
cc @peggygannon @shiragoodman for platform content review awareness

**Comment by johnhashva** [comment]
@callen2563 thanks for the update.  @DanielleThierryUSDSVA + @mnorthuis (with @brianalloyd FYSA) -- thank you for "digging in" -- you raise some vital questions -- and Soni, with her VA collaborators at ORDMI -- should be able to address most if not all.  We will get these Q's over to Soni today -- so she can either address before or during tomorrow's working HRT/Content-IA session at 11am EST.

**Comment by DanielleThierryUSDSVA** [comment]
@johnhashva Sorry, another question to add to the list!

I'm a bit confused about the concept of "anonymous" and requiring someone's name. If a name is attached, I don't know that we can talk about it being "anonymous," right?

**Comment by callen2563** [comment]
@DanielleThierryUSDSVA For the anonymous question we notated on the [flow](https://app.mural.co/t/vsa8243/m/vsa8243/1626971557496/936e375b82d0af58a76ef2b36da3ecf4585bb118?sender=u7ad68f2a3a694c00d8a38130) that for MVP we still need to collect their name but access is different than confidential. For anonymous reporting only headquarters has access their name and their information will not be shared with investigators and fact finders there is very little they can do to take action. Soni will be better at explaining this further but wanted to at least share the notes we have.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @callen2563! I just want to be sure we're super careful about the language we use around that.

**Comment by DanielleThierryUSDSVA** [comment]
@davidconlon @brianalloyd @callen2563 Just checking in to let you know that I will post the rough start of content review likely this evening before I head off to vacation. I need to turn to some urgent covid work first. Just making sure you know I'm not forgetting about this before being out for a week :)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @callen2563 @brianalloyd. Here's the rough start of content for this. You'll see my suggestions to address the issue I'd raised above about lessening the burden (both cognitive and stress related) around some of the questions as part of this. I also added some notes throughout.

@artsymartha68 and I have talked about this as well, and she can help answer questions and provide guidance. I'll check back in when I return on the 23rd!

[File a harassment report 8.13.21](https://app.zenhub.com/files/133843125/7de363ec-39bd-4bb7-b38b-0f6e4c69cbc4/download)

**Comment by callen2563** [comment]
@DanielleThierryUSDSVA @brianalloyd Here are the latest mobile and desktop layouts with updated copy placed in: 

[HRT Mobile and Desktop Designs](https://sketch.com/s/b3f90417-a2a0-41f5-8fb9-151ce163710a)

**Comment by DanielleThierryUSDSVA** [comment]
@brianalloyd @callen2563  Working Drupal preview as we continue working on content in the Drupal page: http://preview-prod.vfs.va.gov/preview?nodeId=34641.

Meeting with Soni to go over this and ask some questions next week.

**Comment by DanielleThierryUSDSVA** [comment]
**Status note:** Sent Soni preview (with questions) for accuracy check. Meeting Tuesday 9/7 to talk through any questions/concerns/other feedback.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @callen2563 @brianalloyd (cc @artsymartha68 @davidconlon). I've gone through the [UX Pin prototype](https://preview.uxpin.com/2421e73be8eba75acea37ad3fbdd09bfc147940f#/pages/141512978/comment/sitemap) and added comments, questions, and recommendations in context. Could you please review, implement what you can, and let me know questions + thoughts? Happy to jump on a call later in the week to talk through any questions.

Brian, I also updated the title of this ticket to reflect the broader scope of the work beyond a copy review. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @brianalloyd. All stakeholder feedback addressed in this preview: http://preview-prod.vfs.va.gov/preview?nodeId=34641. Next step is legal review. My instinct is that we should be okay to proceed with staging review with the knowledge that we may have content tweaks from legal review and that we'll add the phone number once we have it from the stakeholders. The content team always does a final QA/proofread of all Drupal pages before we publish.

**Comment by brianalloyd** [comment]
@DanielleThierryUSDSVA thanks so much for the hard work, concur on moving forward with staging review and incorporating details into final copy once received.  It looks like QA is completed and we should be ready, set for staging review on Thursday.  Thanks again for all the great help.  I'm going to close this ticket in support and open a new ticket for the long path content needs for the 1. Updated landing page with form mention, 2. Intro page details 3. Form flow. Please let me know if any questions remain.
