### ISSUE TITLE
Content Feedback - Midpoint review - Debt resolution, Medical copays

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#27560]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Comment by peggygannon** [comment]
Medical copays midpoint review

**Question**
Should the wizard layout be 1 thing per page? 

----

**Must**

Fix misspelling of “already” on wizard intro

-----

**Should**

Current copay balances screen:

1. Assistance > I recommend changing to “help” to be more plain language and to be consistent with how we refer to assistance/help across these screens. 

2. please change instance of Admin TO administrative 

3. I recommend tweaking this sentence: Contact the VA care facility you received your bill from
TO
Contact the VA care facility that sent your bill. 

-----

**Consider**

For the alert on current copay balances screen: 

Consider adding more detail about what the balance for collection is in reference to.  
Is the amount/ information that appears in these type of alerts related to the amounts that are listed under “What you owe to each facility” headings?

**Comment by rebeccawalsh** [comment]
@peggygannon 

## Question
- Wizard is already built since it belongs to the FSR. We're making changes in the future where we will consider the new pattern, but since it already exists, we're not prioritizing functional changes to the Wizard ahead of launch.
- We used 'tool' because of our observation that Veterans don't expect to be able interact with their benefits on the product pages. Everyone understood 'online tool' in testing. I'm not sure if content specifically looked at the label.

## Must
- Done

## Should
- I *think* I managed to replace all of the assistance mentions - sometimes I wish I had a command+f for Sketch files. (Maybe a plugin exists!)
- It exists as 'admin' on the communications from DMC + the paper statement. Do you still think it should be changed?
- Done 
- I think this is resolved now - a balance can have multiple bills associated, so we mostly use balance
- Yeah, we kept changing H1s and it got screwy. I think this is fixed pending any more changes to the H1s. 

## Consider
- Yep, this is on our list from usability to work on. We have a ticket to provide specific charges and stuff.

**Comment by peggygannon** [comment]
Hi, @becca, thank you for your followup! 

I do think we should spell out admin, as not everyone might be familiar with that abbreviation and we should avoid using internal abbreviations in our content. This word is also spelled out in a later screen (Copay bill detail), so we should be consistent in how we present this.

**Comment by LindaLi123** [comment]
@peggygannon Hello Peggy i believe the change you requested has been done, is there anything else we need to do before we can close the ticket?

**Comment by peggygannon** [comment]
@LindaLi123 thanks for following up. Feel free to close this ticket.
