### ISSUE TITLE
VA Mobile App crashes when attempting to access shared calendars on iOS

### ISSUE THREAD

**Issue by travis-newby** [department-of-veterans-affairs/va.gov-team#27561]
## What happened?
When attempting to add an appointment to a shared calendar, the app crashes.

## Specs:
iOS

## Steps to Reproduce

1. Navigate to any upcoming appointment
2. Select Add to calendar
3. On calendar page, select Calendar
4. [Observe crash](https://user-images.githubusercontent.com/83976412/126207327-61718a1c-46a9-4e79-b8b7-2d373773aa11.MP4)

## Desired behavior
The app allows a user to add the appointment to any calendar.

## Acceptance Criteria
- [ ] Don't crash

## Bonus Content
Termination Reason: TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSContactsUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by lexicalninja** [comment]
Moving to Design Review and assigning @drjecker @melissa-lefevre @msmanak to review. 

We need to add a permission request for users with shared calendars. When a Veteran taps Add to Calendar and they have shared calendars, the app currently crashes. We will need to add a string to tell the user why we need the permission. The below screen shot shows what is temporarily in the app: "This app needs permission in order to access your shared calendars."

Please review and let us know if there is an updated string we can use instead of this one to let users know that we need this permission to access any shared calendars.

If you need any more info, please let me of travis know in a comment here or ping us.

**Comment by drjecker** [comment]
We're going to go with:
```
"VA" Would Like to Access Your Contacts
This lets you add appointments to your shared calendars.
```
