### ISSUE TITLE
[Spike] Log clinic info so it can be surfaced in Loki

### ISSUE THREAD

**Issue by grossb1** [department-of-veterans-affairs/va.gov-team#27595]
Is there a way for us to log clinic names that get returned whenever the clinic selection page loads?

**Background**
There is a known issue with the clinic data including unfriendly clinic names that are then displayed to the user. To target feedback for updating the names and understand the extent of the user impact, we would like to see how often and what kinds of names are actually seen by a user.

**Comment by cferris32** [comment]
Discovery findings:

### Some initial context
What does the clinic response data look like?
- current vaos service clinics endpoint will return clinics with both "clinicName" and "clinicFriendlyLocationName" attributes
- clinicFriendlyLocationName will not always have a meaningful value, sometimes the field is blank and other times it's the same as clinicName
- some example sets of clinic actual names and friendly names, outlining the scenarios described previously:
  - "clinicName" : "CHY PC KILPATRICK",
    "clinicFriendlyLocationName" : "Green Team Clinic1"
  - "clinicName" : "CHY PC CASSIDY",
    "clinicFriendlyLocationName" : ""
  - "clinicName" : "MCINTYRE PC",
    "clinicFriendlyLocationName" : "Green Team Clinic2"
  - "clinicName" : "CHY PC VAR2",
    "clinicFriendlyLocationName" : "CHY PC VAR2"

### The questions at hand
How would we log the returned clinic names?
- we can easily access both of these clinic name fields in the response data, iterating over each returned clinic
- check for a meaningful clinicFriendlyLocationName value, then display what's available
- this way we can track the total number of clinics returned, and gather a percentage of how many clinics only had their default name


How often will users see this clinic data?
- from graphana, roughly 72 hits to the clinics endpoint over the past week
- based on this sample, users are seeing clinic data returned to them just over 10 times per day
- this gives us an initial frame for how active this endpoint is


### Looking ahead
How will this change in the new vaos service?
- the new vaos service utilizes a single "serviceName" field that replaces the pair of "clinicName" and "clinicFriendlyLocationName" fields
- per the new vaos swagger doc, "If the clinic is configured with a patient-friendly name then that will be the value. Otherwise it will be the internal clinic name."
- we may need a different approach to programatically determine how many user friendly names are returned in this field, since we will no longer have two fields to compare
- the new vaos service clinics endpoint may also affect the traffic metrics we've seen, but that is tbd
