### ISSUE TITLE
Add Error message intro/crosslinks to content section in design system

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#2760]
We need to add and landing page with crosslinks to the Error messaging guidelines in the content section of design system. 

Crosslinks:
[Error message dictionary](https://design.va.gov/patterns/messaging-dictionary)
[Error message styleguide](https://design.va.gov/patterns/messaging-error-messages)

## Acceptance Criteria
- [x] Peggy to create short introduction to place on landing page in content
- [x]  Randi to update left nav with error messaging landing page and links to the resources in design.

**Comment by peggygannon** [comment]
Hi, @jenniferlee-dsva @RLHecht I've written up some copy for the Error message landing page for the content section of design system. Can you give it a review when you get a chance and let me know what you think? 

Error message landing page for VA.gov content styleguide

**Error messages**
 
Error messages alert the user that something has gone wrong. These messages should be clear, direct, and have an actionable CTA (call-to-action) for the user. 

In some cases, an error might not be resolved with the initial CTA (for example, “Check back later”). In these cases, a next step CTA might also be needed (for example, we might ask the user to call the VA.gov help desk).  In every error message, we should provide the most actionable, detailed, and accurate information as possible. 

When writing an effective error message, ask yourself the following:  

1. What’s the error or issue? 
2. What’s causing the error or issue? 
3. What do we need to tell the user to resolve the issue? 
4. If the resolution fails, what’s the next step for the user?

For more information and guidance on error messages:

[See the error message styleguide](https://design.va.gov/patterns/messaging-error-messages) for additional guidance on writing an error message. 
[See the error message dictionary](https://design.va.gov/patterns/messaging-dictionary) for specific error message examples and use cases.

**Comment by RLHecht** [comment]
@peggygannon This looks good to me as the landing page. Just one copyedit:

These messages should be clear, direct, and have an actionable call to action (CTA) for the user. [Delete hyphens and switch what's in parentheses to the acronym)

**Comment by peggygannon** [comment]
thanks, @RLHecht for taking a look! 

@jenniferlee-dsva Let me know if this content is what you had in mind for this landing page? or iif we should add more info?

**Comment by jenniferlee-dsva** [comment]
A few comments as well... Suggested edits in [brackets].

**General:**
- We use the spelling "style guide" in the content style guide, not "styleguide." 
- Since this is a lp meant to direct ppl to the complete info in the design section, I wonder if we can bring up the cross-links to the top, so people see it right away; or include a cross-link opportunity at the top as well as at the bottom...

**1/ **
Error messages [tell] the user that something has gone wrong. These messages should be clear, direct, and have an actionable call to action (CTA) for the user.

[Error messages mainly appear in interactive experiences such as tools, forms, and applications. Because this category of messaging usually has a lot of visual design and formatting that affects copy, go to the design section for more comprehensive error message guidance.]  <--  added cross-link to design section of error messages???

**2/** 
[Error messages should provide the following information]:

What’s the error or issue?
What [caused] the error or issue? 
[What does the user need to do to continue]?
If [there's nothing they can do,] what’s the next step for the user?

**3/**
 For more [detailed guidance and visual formatting of] error messages:

See the error message [style guide in the design section]. 
See the error message dictionary for specific error message examples and use cases.

@peggygannon - could we also add some guidance on when we say and when we don't say "We're sorry..."?  I can see some teams adding that like a preamble for everything and becoming filler/white noise. We can discuss in weekly, if we haven't really solidified a rationale on this. 

FYSA, noticed a couple very minor copy editing errors in the design system error message page (like missing periods in "i.e.," and such). Didn't look thoroughly, but maybe something @RLHecht  can create a ticket to help review on that page.

**Comment by Karak888** [comment]
@peggygannon please review and another version as necessary.

**Comment by peggygannon** [comment]
Thanks, @jenniferlee-dsva for your feedback. Below is updated copy for the Error message landing page.If all looks good, it's ready for @RLHecht to put into the content section of design system. 

Re: I can provide additional guidance on "We're sorry". I've been asked to also providing additional guidance on "downtime messaging", so I will create an issue for both of these:
Provide additional error guidance on messaging for: 
"We're sorry" usage
Downtime notifications


**Error messages**

Error messages tell the user that something has gone wrong. These messages should be clear, direct, and have an actionable call to action (CTA) for the user.

Error messages mainly appear in interactive experiences such as tools, forms, and applications. Because this category of messaging usually has a lot of visual design and formatting that affects copy, the design section has more comprehensive error message guidance. 

See  the [error message style guide](https://design.va.gov/patterns/messaging-error-messages) for additional guidance on writing an error messages.
See the [error message dictionary](https://design.va.gov/patterns/messaging-dictionary) for specific error message examples and use cases.

**Error messages should provide the following information:**
-  What’s the error or issue?
- What caused the error or issue?
- What does the user need to do to continue?
- If there's nothing they can do, what’s the next step for the user?

More [detailed guidance and visual formatting](https://design.va.gov/patterns/messaging-error-messages) of error messages, can be found in the design section.

**Comment by jenniferlee-dsva** [comment]
@peggygannon - th u. Looking at it in whole, I think my feedback incorporated introduced some unfortunate redundancy.  Can we go back where you first had your CTA links, but incorporate as embedded link, reference link to design section in 2nd para? 

Like this... 

**Error messages**

Error messages tell the user that something has gone wrong. These messages should be clear, direct, and have an actionable call to action (CTA) for the user.

Error messages mainly appear in interactive experiences such as tools, forms, and applications. Because this category of messaging usually has a lot of visual design and formatting that affects copy, go to the design section for more [detailed guidance and formatting of error messages](www.link.com).

**Error messages should provide the following information:**

What’s the error or issue?
What caused the error or issue?
What does the user need to do to continue?
If there's nothing they can do, what’s the next step for the user?

See the [error message style guide](LINK) for additional guidance on writing an error messages.
See the [error message dictionary](LINK) for specific error message examples and use cases.

**Comment by peggygannon** [comment]
@jenniferlee-dsva Yes, this looks good...  Is this ready for @RLHecht to implement? 

fyi for you both, I'll be creating a separate issue for the "We're sorry" guidance.

**Comment by RLHecht** [comment]
@jenniferlee-dsva and @peggygannon Checking back in on this. Are there any more edits that need to happen or should I create the error landing page?

**Comment by peggygannon** [comment]
@RLHecht I don't think there are any additional edits needed at the moment. Unless @jenniferlee-dsva wanted to add something more?

**Comment by Karak888** [comment]
@RLHecht @jenniferlee-dsva @peggygannon if no further edits are needed, I am going to close this out. If needed we call always reopen or refer to this ticket.  Thanks

**Comment by Karak888** [comment]
@RLHecht @peggygannon I think we discussed at standup we can close this since Peggy has other tickets she created and will talk to @jenniferlee-dsva about those tickets for error messaging.  Thanks!

**Comment by RLHecht** [comment]
@Karak888 The work is done but I need to add the page to the menu and we need to validate it on the live site. I would hold off on closing.

**Comment by Karak888** [comment]
@RLHecht  sorry I misunderstood!!! just reopened!

**Comment by RLHecht** [comment]
This was added to the content style guide. Moving to validate and will close when looks good on the live site.

**Comment by RLHecht** [comment]
Validated on live site. Closing issue.
