### ISSUE TITLE
[New] File Upload Accessibility fixes from staging review

### ISSUE THREAD

**Issue by dat-gcio** [department-of-veterans-affairs/va.gov-team#27655]
### Description
Implement feedback from staging review https://github.com/department-of-veterans-affairs/va.gov-team/issues/27414

### Acceptance criteria
- [ ] Error messages are announced

**Comment by dat-gcio** [comment]
This is in staging.

**Comment by tchrisdyer** [comment]
Reopening @mdewey . I'm still seeing the old messaging and delete button in Production.
![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/93e28c57-0487-4d38-93e7-80aa3611bf13)

The correct messaging and buttons are showing in staging:
![image.png](https://images.zenhubusercontent.com/60a82759d2c5ea6177753bf1/93cd19e0-d86e-45b1-a330-d6bfa7f0d14b)

Perhaps the fix for the progress bar went in but not the other changes.
