### ISSUE TITLE
Builds and tests are timing out in GHA implementation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#27683]
## Details 

Resources on self-hosted runners are getting strained and not allowing builds to complete in a timely manner. They end up timing out 

This may be on Ops to fix, but we need to support them with information about the issues we're experiencing

## Acceptance Criteria

- Builds and tests are not timing out in GHA

**Comment by CBonade** [comment]
Since moving the Cypress tests to running inside a container, we have seen Cypress test timeouts almost completely disappear.  There may occasionally still be a very rare timeout (as it did as well in Jenkins), but I have not been able to locate any regular timeouts (or even sporadic ones) for at least a week now in searching through our Github Actions history.

Build timeouts may still be occasionally happening, however, often when someone hits a build timeout they hit "rerun jobs" and we somewhat lose the record of that happening.  I am unable to currently find a timeout for a build either, so this may or may not still be happening.

**Comment by oseasmoran73** [comment]
After discussing with Ops and @timwright12 , first step to try and reduce timeout and flakiness for build would be to add "retries".

In regards to the tests, with latest changes from TT, seems the timeout are less frequent.

**Comment by oseasmoran73** [comment]
Pipeline seems to be stable with a couple of one offs. Continuing to monitor for timeouts along with #27680

**Comment by oseasmoran73** [comment]
Closing ticket as there has been stability. Issue behind TIC resolved in this [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27681).
