### ISSUE TITLE
Cypress Viewport Automation Discovery

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#27727]
## User Story

Currently, we have an automated mechanism in place to retrieve data from Google Analytics about the top 5 most used screen sizes for desktop and mobile use. PRs are being automatically generated to incorporate that data into vets-website, but they are backing up as the viewport altering mechanism is largely unused.

We need to investigate why the automation is generating 4 PRs each month. Example --
https://github.com/department-of-veterans-affairs/vets-website/pull/17040
https://github.com/department-of-veterans-affairs/vets-website/pull/17041
https://github.com/department-of-veterans-affairs/vets-website/pull/17042
https://github.com/department-of-veterans-affairs/vets-website/pull/17043

This should be condensed to 1 PR if possible, or perhaps we should turn off the automatic update for now since this is largely unused.

## Expected Behavior

At most one PR per month is generated with the updated statistics for the month and the updated viewport sizes.

## Acceptance Criteria

- [x] Redundant PRs are no longer created
- [x] Existing backlog of PRs have been cleaned up

**Comment by holdenhinkle** [comment]
It took a little while to get this the Cypress Viewport Updater running locally (with the secrets and all) because it's been many months since I last worked on it.

All the secrets are in the `settings.local.yml` file. 

I'll create a `readme.md` file at `https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/workers/cypress_viewport_updater` and post the secrets in `va.gov-team-sensitive` and link to them.

When I run the Viewport Updater locally, it only submits 1 PR. When Sidekiq executes the job, it creates 4 PRs.

The first two PR have the same commits. The second two PRs don't have commits.

I talked to Lindsey H in BE Tools about this and she's not sure why this is happening.

I'm going to add extra logging to see if we can identify why this is happening. I'm also going to login to Sidekiq UI for prod and review the logs for this job.

Here's the documentation for logging into Sidekiq UI, prod - https://vfs.atlassian.net/wiki/spaces/VI/pages/926089332/Sidekiq+Production+Access

I'll login to Sidekiq first thing in the morning.

Btw, when I was building this app, it always submitted just 1 PR. I reviewed the code and executed some of it line by line in the console (`make console`) today and can’t see how it can submit more than 1 PR.

**Comment by holdenhinkle** [comment]
I closed 3 out of the 4 PRs that were created each month for the past 3 months and deleted their branches.

Here's the list of PRs that haven't been approved - https://github.com/department-of-veterans-affairs/vets-website/pulls?q=is%3Apr+is%3Aopen+Update+Cypress+Viewport+Data+%28Automatic+Update%29

**Comment by holdenhinkle** [comment]
Some ideas:
I remember Eugene asking me if we could be the code-owners for it, so we receive alerts when the PR is submitted each month, and so we can approve it. Is it okay to implement that?

A few more things:
1. Add code to update the following when the job runs each month:
```
  "viewportWidth": 1920,
  "viewportHeight": 1080,
```

That’s setting the default Cypress viewport. This update shouldn't take long to implement.

2. I can also add env vars called `vaTopMobileIterateUptoIndex` or something so people can start using this to at least hit the top desktop and mobile viewports. Then, like I said, if we ever want to iterate through the top 2, or 3 or whatever, we’d just change the value of that env var…

This should take no time at all to implement, but I’d have to update the documentation (edited)

**Comment by holdenhinkle** [comment]
Lindsey Hattamer  7:13 AM
So random early morning thought… I’m wondering if your sidekick job is running in each of the environments sandbox, dev, staging, prod and that’s why there’s 4 PRs? Could be the reason for the identical time stamps too :thinking_face:

Holden Hinkle  8:19 AM
Hey! Oh, that’s interesting. I’ll look into that. How do I designate which environment to run it on?

Out of the 4 prs, there seem to be 2 sets, each with the same commits, which I find super strange.
This set has changes to the files committed:
https://github.com/department-of-veterans-affairs/vets-website/pull/17040/commits/c5a6e175e668794e045231fa073da7cd0ad4a926
https://github.com/department-of-veterans-affairs/vets-website/pull/17041/commits/c5a6e175e668794e045231fa073da7cd0ad4a926
https://github.com/department-of-veterans-affairs/vets-website/pull/17040/commits/5977437e338bd965fc51ca283b89b0ba621e8169
https://github.com/department-of-veterans-affairs/vets-website/pull/17041/commits/5977437e338bd965fc51ca283b89b0ba621e8169

This set doesn’t:
https://github.com/department-of-veterans-affairs/vets-website/pull/17042/commits/ed273c37a3c948515c3d6b84ddfc5f77e9d89da1
https://github.com/department-of-veterans-affairs/vets-website/pull/17043/commits/ed273c37a3c948515c3d6b84ddfc5f77e9d89da1
https://github.com/department-of-veterans-affairs/vets-website/pull/17042/commits/43a1306834838a5457b0b7297dc9fd792a6fa074
https://github.com/department-of-veterans-affairs/vets-website/pull/17043/commits/43a1306834838a5457b0b7297dc9fd792a6fa074

Lindsey Hattamer  8:20 AM
I think you can log into the sidekiqUI and disable there

Lindsey Hattamer  8:20 AM
There should be a disable button under the recurring jobs

Holden Hinkle  8:21 AM
Okay, thanks

**Comment by holdenhinkle** [comment]
Lindsey Hattamer  8:27 AM
It looks like that job is enabled in all envs right now:
https://staging-api.va.gov/sidekiq/recurring-jobs
https://staging-api.va.gov/sidekiq/recurring-jobs
https://sandbox-api.va.gov/sidekiq/recurring-jobs

Lindsey Hattamer  8:32 AM
Would you like me to disable them? I have access right now

Holden Hinkle  8:32 AM
Yeah, that would be great!
8:33
Thank you!

Lindsey Hattamer  8:33 AM
You're welcome!
8:33
They're all disabled, besides prod :white_check_mark:
8:34
I'm thinking that should fix the issue, but I could be wrong

**Comment by holdenhinkle** [comment]
Testing Tools Team is already the code owner for `config/cypress.json` and `src/platform/testing/e2e/cypress/support/commands/viewportPreset.js`.

In `.github/CODEOWNERS`:

```
# VSP Testing Tools
src/platform/testing/contract/ @department-of-veterans-affairs/vsp-testing
src/platform/testing/e2e/ @department-of-veterans-affairs/vsp-testing
config/cypress.json @department-of-veterans-affairs/vsp-testing
```

**Comment by holdenhinkle** [comment]
I just pulled [the last PR](https://github.com/department-of-veterans-affairs/vets-website/pull/17773) submitted by the bot and merged master into it. Let's see if I can approve it!

**Comment by holdenhinkle** [comment]
PR for adding the following 'Interate Upto Index' Cypress env vars - https://github.com/department-of-veterans-affairs/vets-website/pull/17982

```
vaTopMobileViewportsIterateUptoIndex
vaTopTabletViewportsIterateUptoIndex
vaTopDesktopViewportsIterateUptoIndex
```

**Comment by holdenhinkle** [comment]
PR for adding documentation about using the new `IterateUptoIndex` Cypress env vars - https://github.com/department-of-veterans-affairs/va.gov-team/pull/27779

**Comment by holdenhinkle** [comment]
PR for updating the default Cypress width and height - https://github.com/department-of-veterans-affairs/vets-api/pull/7507

**Comment by holdenhinkle** [comment]
I added the following secrets to AWS Parameter Store:

```
/dsva-vagov/testing-team/cypress_viewport_updater/github_private_pem
/dsva-vagov/testing-team/cypress_viewport_updater/github_installation_id
/dsva-vagov/testing-team/cypress_viewport_updater/github_integration_id
/dsva-vagov/testing-team/cypress_viewport_updater/google_analytics_credentials
```

**Comment by holdenhinkle** [comment]
PR for updating the Viewport Bot docs - https://github.com/department-of-veterans-affairs/va.gov-team/pull/27788

Add notes about how to configure `config/settings.local.yml` so you can run the updater locally.

**Comment by holdenhinkle** [comment]
Testing Team is codeowners of the files updated by the Viewport Updater Bot
=> Yes
=> Peter configured a Slack notification each month for our team to approve the PR

Addressed cause for 4 PRs being submitted each month
=> Probably. We'll see the next time this runs on August 3rd

PR for adding the following 'Interate Upto Index' Cypress env vars - https://github.com/department-of-veterans-affairs/vets-website/pull/17982
=> Merged

PR for adding documentation about using the new IterateUptoIndex Cypress env vars - https://github.com/department-of-veterans-affairs/va.gov-team/pull/27779
=> Merged

PR for updating the default Cypress width and height - https://github.com/department-of-veterans-affairs/vets-api/pull/7507
=> Merged

PR for updating the Viewport Bot docs - https://github.com/department-of-veterans-affairs/va.gov-team/pull/27788
=> Pending

PR to update the default Cypress viewport - https://github.com/department-of-veterans-affairs/vets-website/pull/17985
=> Approved, but checks keep failing because of GHA

**Comment by pjhill** [comment]
Thanks for all these changes -- we'll see how we do with the August update!
