### ISSUE TITLE
Review and Feedback for Home Page Banners Product Outline 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#27736]
## Issue Description
_As a business Public Websites team has supported/enabled "emergency communications/messaging" from VA leadership at OPIA with a Home Page banner alert. The process by which that banner is used and deployed is unique and problematic_

[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page-banner/product-outline.md) 

## Front end tasks
- Review and provide feedback and technical update to outline

## Acceptance Criteria
- [x] updated and is technically sound in support of meeting with VSP ops team

## Appendix
<details> 

 <summary>Ensure your code changes are covered by E2E tests (expand)</summary>
 
 - Add E2E tests if none exist for this addition/change. 
 
 - Update existing E2E tests if this code will change functionality. 
 
 - Include axe checks, including hidden content
 
</details>

<details> 

 <summary> Run axe checks using the Chrome or Firefox browser plugin (expand)</summary>
 
- Ensure no heading levels are skipped.

- Ensure all buttons and labeled inputs use semantic HTML elements.

- Ensure all buttons, labeled elements and images are identified using HTML semantic markers or ARIA roles.

- Ensure form fields have clearly defined boundaries or outlines.

- Ensure form fields do not use placeholder text. 

- Ensure form fields have highly visible and specific error states. 

</details>

<details> 

 <summary> Test for color contrast and color blindness issues (expand) </summary>
 - All text has appropriate contrast. 

</details>

<details> 

 <summary> Zoom layouts to 400% at 1280px width (expand)</summary> 
 - Ensure readability and usability are supported when zoomed up to 400% at 1280px browser width
 - Ensure no content gets focused offscreen or is hidden from view.
 
</details>

<details> 

 <summary> Test with 1 or 2 screen readers (expand)</summary> 
 
 - Ensure the page includes a skip navigation link. 
 
 - Ensure all links are properly descriptive. 
 
 - Ensure screen reader users can hear the text equivalent for each image conveying information. 

 - Ensure screen reader users can hear the text equivalent for each image button. 

 - Ensure screen reader users can hear labels and instructions for inputs. 
 
 - Ensure purely decorative images are not announced by the screenreader. 
 
</details>

<details> 

 <summary>Navigate using the keyboard only (expand)</summary> 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be reached with the tab key in a logical order. 
 
 - Ensure all links (navigation, text and/or image), form controls and page functions can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure all interactive elements can be reached with the tab key in a logical order 
 
 - Ensure all interactive elements can be triggered with the spacebar, enter key, or arrow keys.
 
 - Ensure focus is always visible and appears in logical order.
 
 - Ensure each interactive element has visible focus state which appears in logical order.
 

</details>

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kelsonic** [comment]
## Short-term fix

*Brief description:*
Instant publishing via HTTP request for emergency banner config on page load in React widget.

*Related PRs*:
https://github.com/department-of-veterans-affairs/vagov-content/pull/784
https://github.com/department-of-veterans-affairs/vets-website/pull/17968
https://github.com/department-of-veterans-affairs/content-build/pull/389

*Blocked by*:
Need GitHub Action that listens for [the banner config](https://github.com/department-of-veterans-affairs/vagov-content/blob/master/fragments/home/banner.yml) file being updated and upload it to S3 so that we don't get a CORS issue when requesting the content on the client.

## Long-term fix

*Brief description:*
Store the emergency banner in Drupal and have it update whenever it is updated in Drupal.

*Related PRs:*
https://github.com/department-of-veterans-affairs/content-build/pull/325

*Blocked by:*
The current PR assumes the emergency banner will be ID 42, but that likely won't be the case. We need to know which ID the emergency banner will be. We also need an easy way for OPIA to update it without accidentally affecting anything else in Drupal. We also need a way to republish + deploy the emergency banner quickly so that it can be updated on https://www.va.gov very soon (less than 15 minutes) after updating it.

**Comment by brianalloyd** [comment]
Thanks for the update @kelsonic, did you place the comments in the Github?  Going to close this in support as the review and feedback has been done.
