### ISSUE TITLE
Discussion: Should we add repos to Sentry?

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#278]
## Background
We have the ability to [add repos](http://sentry.vetsgov-internal/settings/vets-gov/repos/) in Sentry. I think this is through the [GitHub integration](https://docs.sentry.io/workflow/integrations/global-integrations/#github).

## Question?
- Should we add the GitHub integration and connect the repositories to Sentry?
  - Are there any security / privacy concerns?
  - What are the benefits of doing this?
  - Does it create any undesirable overhead?

**Comment by cvalarida** [comment]
## Benefits
- Commit tracking
  - I think what this means is we can easily figure out when a bug was introduced, but that's not super hard to find out right now via `git blame`
- Resolving Sentry issues via commit messages
  - This may be the biggest benefit

## Drawbacks
- To track commits, I think we have to [make releases in Sentry](https://docs.sentry.io/workflow/releases/?platform=browser), which seems kind of complicated
  - Because we make releases every weekday, this would be a thing we'd want to set up using the API, but I don't know that it's really worth it

**Comment by annaswims** [comment]
It looks like it would be nice to have if we can get it to work. @wyattwalter has done some work on getting it set up within the past month and documented a bit here.  https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/sentry/README.md#github-integration

we had to make a new app in GitHub since the default sentry-github app points to hosted sentry.

**Comment by alexpappasoddball** [comment]
The answer is Yes.  We should add repos to sentry per our conversation on 7/1/19.
