### ISSUE TITLE
Analytics KPI dashboard request for Platform Content/IA

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#27914]
# Request a Standard KPI Dashboard

## What this form is for

Use this template to request a KPI dashboard on Domo for your product. 

We are currently only supporting standardized dashboards for Forms, Content, & Search products. If you have another VA.gov product, please reach out to the Platform Analytics & Insights team on #vfs-platform-support. Please note that these dashboards will require additional data and design discovery, and will take additional time to deliver.

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 

- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).

### Expected delivery timelines

Your KPI dashboard request will be added to the Platform Analytics & Insights team's customer support queue, and we expect tickets at the top of the queue to be pulled in every Platform Sprint Planning & Refinement (every Wednesday). We appreciate your patience.

- Once your ticket has been pulled into the Platform sprint, we expect to deliver your completed dashboard within the next 4 business days. Please use this ticket for any follow up questions.

## Instructions for the VFS team

- [x] [Filled in KPI dashboard template](https://docs.google.com/spreadsheets/d/1i7FS3oMU-pr-PawZvSWi2Ie_QrZfUtzQaj8iI-JGaEQ/edit#gid=0)
- [x] Add your team label to follow progress
- [ ] If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

## VFS-provided information

[Funnel Information](Add your product/feature's funnel information here) - Add your product/feature's funnel information here

*Please leave the following blank*

---

## VSP Analytics & Insights Acceptance Criteria

1. Build (See [internal process document](https://vfs.atlassian.net/wiki/spaces/AT/pages/1464598569/New+KPI+Dashboard+Request+Process) & [how to](https://vfs.atlassian.net/wiki/spaces/AT/pages/1538294010/WIP%2B-%2BHow%2Bto%2Bcreate%2Bstandardized%2Bdashboards%2Bin%2BDomo))

- [ ] Add the `VSP Analytics & Insights` Group as the dashboard owner
- [ ] Structure funnel data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Document any blocked/unavailable metrics in the Analytics team space
- [ ] Update the dashboard header, including Google Analytics links
- [ ] If any, add [implementation issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+%5BTeam+Name+-+Feature+Name%5D) for additional necessary implementation

2. Q&A

- [ ] Please see & complete the [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

3. Share

- [ ] Add VFS group & default group to the dashboard

  *For new VFS customers only:* 

- [ ] Schedule onboarding meeting

- [ ] Host the meeting to explain how the dashboard works

## Definition of Done

- [ ] Accepted Criteria has been completed
  - [ ] KPI Dashboard full QA checklist completed
- [ ] Dashboard has been shared back with the VFS team

**Comment by joanneesteban** [comment]
@lianilychee - hi there! Are you requesting a Platform Content & IA dashboard? This form is for standardized VFS/VA.gov products, so we may need to talk about scoping and an edge case dashboard if y'all would like.

**Comment by lianilychee** [comment]
@joanneesteban hi!  Yes, the Content/IA team is requesting a dashboard for the Platform website.  We are all pretty new and unversed with a lot of GA and GA-related things, so we were wondering if we could start with a "default" content KPI dashboard to help gather our thoughts (and iterate from there)

Happy to come to the Collab Cycle office hours to discuss further, like I mentioned [in the other issue I opened](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27792#issuecomment-888524528)

**Comment by lianilychee** [comment]
hello Analytics team!  Checking in on this - has this been groomed or is it still in your backlog?  No worries if it's still in the backlog.  LMK if there is anything else my team can provide 👍 😄

**Comment by joanneesteban** [comment]
### Proposal for dashboard creation:

**Proposal:** A Platform Website dash with the highlights section of the VA.gov Content KPIs dashboard? Maybe adding a couple of other charts from the Search KPI dashboard (i.e. top search terms) in as well.

**Why:**

- Adding the Platform Website to the VA.gov Content KPIs dashboard is going to be confusing for the VFS folks and make the experience a bit inconsistent since the Platform Website is VFS-facing.
- To duplicate the entire dashboard would be a large lift for the team, and would take a long time for us to get off the ground.
- Several of the charts in the whole dashboard wouldn’t apply to the Platform Website, so we’d have to do a bunch of business requirements gathering with what will work and what won’t to try to dupe the whole dashboard.
- To keep the KPI dashboard lean

**Comment by lianilychee** [comment]
along with ^^^, Joanne sent this screenshot as an example of the Highlights section:
![image](https://user-images.githubusercontent.com/6895034/132908036-aeb5f0c7-8c7c-4923-8055-7378f0703674.png)

**Comment by chloedotbrown** [comment]
### Content/IA

Hi @lianilychee and @gmaciolek! Sharing a work-in-progress version of this dashboard for your team [here](https://va-gov.domo.com/page/1182586883) so I can gather you're initial feedback while our team continues to QA. Does this seem like it would meet your needs? Let me know if there are any have-to-have edits you'd need for this to be a useable MVP for your team (add metrics not here, change chart types, switch unique pageviews to total, remove something entirely, etc.). Some FYIs:

#### Data not yet available
Heads up that there are two KPIs we don't yet have – `time_on_page` isn't yet in Domo for our Platform GA data. We'll need to add this as a view in BigQuery, which shouldn't be too difficult, since we can copy the logic we're using for the VA Content dashboard. Similarly, we don't have any Platform user satisfactions in Domo yet, but I'll be connecting with the Service Design team to connect the quarterly survey data. I'll add these to your dashboard as soon as they're available.

#### Update schedule
Lastly, this datasource is filters out incomplete weeks, so you'll only ever see data from the most recent Saturday and earlier. That said, if you'd rather the data update daily, we can discuss ways to change the dashboard view and I'll give you some tips so potential discrepancies aren't confusing.

----------

### Analytics
Meanwhile – QA! @bsmartin-ep I know you're currently on this ticket, but if you'd like to bring Jenna or Lauren on for this feel free to assign them. 

One thing I made a guess on was for counting link clicks – does `searchCategory = '(not set)' AND hit_type = 'EVENT'` seem like a decent guess? If not, feel free to update Beast Mode or flag for removal.

**Comment by chloedotbrown** [comment]
Hi @lianilychee and @gmaciolek – checking back in! Did you have any thoughts about the questions above? How does the work-in-progress version look for your needs?

**Comment by lianilychee** [comment]
From 11/9 office hr -- Domo dashboard modification requests:
(1) Possible to track a particular GH project board's issues over time?
  - A: Can't track by project board, but _can_ track by label
  - **action:** Liani to FUP with team
(2a) Possible to top track unique views per space?  
(2b) And within the Developer docs space, the top unique views within each subsection?  IE top three within Infrastructure," top three within "Frontend developer docs," and so on


Based on these requests ^^ we think we'll have to cut some of the cards, but don't wanna confirm those deletions yet.

**Comment by chloedotbrown** [comment]
Thanks, @lianilychee! We'll wait to hear back from you on (1), but in the meantime, I'll start work with @pavanhothi and @jonathan-epstein13 on (2a) and (2b). 

As a potential (3), we'll look into adding a card for tracking the `Internal User Opt Out` event action as well.

**Comment by lianilychee** [comment]
hello @chloedotbrown !  update on (1) -- we'll have an answer to you by the end of the week; the team is mulling over what phrase to use as a label.  Thank you for your patience :woman-bowing:

**Comment by lianilychee** [comment]
hello @chloedotbrown !  update on (1) -- we want to track the GH label `pw-footer-feedback`.  Thank you again 🙇‍♀️

**Comment by chloedotbrown** [comment]
Awesome, thanks for the update @lianilychee! We'll add this to our update list. 

In return – a couple follow-up questions for you:

1. **Workspaces**: Even in the more recent data, we're seeing a couple workspaces when we grab them from the URL that don't match up with what's on the site (Test Release, Integrations, etc.). These seem like pretty close matches for subpages in the Developer space. Should we recategorize them to fall there?
2. **Workspace index pages**: When counting pageviews-per-workspace and the top pages in each space, do you want us to include the landing pages for that section (`/index.html`) that include mostly links? These tend to make up ~10% of views in a workspace _(see table below for November example)_.
3. **Developer views**: Because the subsections in this space aren't in the URL, I don't think there's a way for us to create that field to organize views within each subsection. However, what we could do is show top link clicks on each of the FE developer, Infrastructure index pages etc. It wouldn't catch pageviews that came through another path, but it would probably give you similar info. Would that work for you?


![PageviewsByWorkspace](https://user-images.githubusercontent.com/45518242/142520603-4676c95c-422d-4fef-83be-0d688f936a7d.png)

**Comment by jonathan-epstein13** [comment]
@lianilychee when you get a chance, can you send the link for the GA report that you shared in office about opt-out events. Thank you so much!

**Comment by lianilychee** [comment]
heey there @jonathan-epstein13 , here's that [GA opt-out report](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w224573768p249894295/_u.date00=20210601&_u.date01=20211020&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=internal%20user%20opt%20out/).  Thanks for the patience, as I was off for all of Thanksgiving week!

**Comment by jonathan-epstein13** [comment]
Thank you @lianilychee for sending the report! I appreciate it and hope you had a great Thanksgiving week off!

**Comment by pavanhothi** [comment]
@lianilychee when you are able to, can you please create a new ticket with the new GH label pw-footer-feedback. This is so that I have data to create your new card for you, tracking this new label. Thank you!

**Comment by lianilychee** [comment]
@pavanhothi here you go! https://github.com/department-of-veterans-affairs/va.gov-team/issues/33648

**Comment by pavanhothi** [comment]
Thank you @lianilychee !

**Comment by jonathan-epstein13** [comment]
Hello @lianilychee we've add the changes/cards you requested! Here is the [WIP - Platform Website KPIs](https://va-gov.domo.com/page/1182586883?userId=44062480) Let us know if this is what you were looking for and please let us know what you think of the new dashboard.

**Comment by pavanhothi** [comment]
Hi @lianilychee ! Just wanted to follow back up with you and see if you were able to take a look at the changes made to the dashboard. Let us know if you have any questions or feedback. Thank you!

**Comment by lianilychee** [comment]
hello @pavanhothi !  Thanks for the patience (and for following up on Slack)!!  I will review before the week is over.  Team is getting our feet under us after quarterly planning and personnel changes.

**Comment by lianilychee** [comment]
@pavanhothi @chloedotbrown these updates are :chef-kiss:  Thank you so much! :D

**Comment by chloedotbrown** [comment]
Awesome, so glad this works @lianilychee! We'll have @laurensimpson14 finalize the QA and then close this ticket for you.

**Comment by bsmartin-ep** [comment]
@chloedotbrown / @laurensimpson14 -

These numbers are looking good now...

<img width="226" alt="image" src="https://user-images.githubusercontent.com/62304138/154368381-79eb74e4-a02b-478f-b5d1-8ef9322816d2.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/62304138/154368636-70762951-5b08-40db-b50a-bb1bdfcf03a7.png">

The remaining issue was that our dataset is both events and pageviews.  So these Unique Pageview metrics were counting events as well.  This was affecting a few other cards as well.

I went ahead and filtered to `hit_type = PAGE` on every card with 'page' in the name.

OK to close?

**Comment by laurensimpson14** [comment]
Thank you Brian! Closing this ticket.
