### ISSUE TITLE
[FE] My VA Action Items Disc: Look into messages API specifics 

### ISSUE THREAD

**Issue by tressaellen** [department-of-veterans-affairs/va.gov-team#28023]
## Background

My (Tressa's) understanding is that we cannot link directly to a specific message, but I'd love to know if we can show the Dr. name in a new message, and then link to 'View all messages'.

**Comment by erikphansen** [comment]
Yes, I'm 99% sure that we can show the sender's name, and subject, and date sent, if we wanted to, based on the content in the mock responses https://github.com/department-of-veterans-affairs/vets-website/blob/3acf5b3cb3cf7c2bc154dc7f1d6c1061f82da58b/src/applications/personalization/dashboard/utils/mocks/messaging/messages.js

And we can definitely link to "view all messages".

I'm also wondering if we could deep-link directly to a specific message. I'd think it should be feasible but finding a definite answer might be hard because finding a user with recent unread messages seems to be hard :(
