### ISSUE TITLE
Caseflow error handling for Appeal Status

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#2803]
## Problem Statement
Errors for Appeal Status are not being handled correctly on va.gov side. The Appeal Status displayed that it was unavailable and was returning 500 error, however upon deeper review the error was that there was no SSN provided for this user in their system.

Caseflow owns the Appeals Status API - Peter Karman and Alisa Nguyen are their lead developers who can help or point us to the right person. 

### Additional Information:
“The Appeals Status API is used on VA.gov and lives in vets-api, just like the Lighthouse Appeals Status API. however they are separate branches of code. There are no active consumers of our instance of the status API (except for WHCC maybe someday). Much like how VA.gov supports Disability Claims submissions for auto-establishment and our API supports it but VA.gov uses a separate code branch”

## Goal
_Display accurate error_

## Acceptance Criteria
- [ ] _What needs to happen or be created?_

### User's Screenshare
![image.png](https://images.zenhubusercontent.com/5d52c3244773cd34ebdf4867/c78e9909-bf04-4167-9f4d-ee1045162262)
### Error details
![image.png](https://images.zenhubusercontent.com/5d52c3244773cd34ebdf4867/5f89eed3-45cd-4b9f-a18c-8d0316a16bdf)

**Comment by camerontesterman** [comment]
Assigned myself to this ticket. Will be taking a look at this today.

**Comment by camerontesterman** [comment]
I checked the logs for the ELBs around that time - and I did identify one of the requests that I believe came from the veteran we spoke to on October 25, it did return a 500 on the GET appeals call.

Testing in staging with a user that does not have any valid appeals, the response returned is the proper 404 response. I have not been able to recreate the 500 Internal Server Error call that the veteran was experiencing; this problem does seem to be at least somewhat isolated to this particular veteran because it is only 500 call related to /appeals that I could find after reviewing a handful of log files.

**Comment by camerontesterman** [comment]
I traced the 500 error to a specific error and did indeed find that Rails had returned a 500 error around that time. It appears as though the JSON validation failed, so whatever we are getting from caseflow for this particular veteran - that data isn't passing our validation and is incorrect in some way.

**Comment by camerontesterman** [comment]
Fix has been implemented and merged into master.

**Comment by gunsch** [comment]
Drive-by reading through this, I'm curious if there are other errors we have of a similar class that are flying under the radar. Are there other cases like this we could do an audit pass across, maybe via Sentry? @camerontesterman @omgitsbillryan @annaswims
