### ISSUE TITLE
[Content] Check-in Phase 2 from the Healthcare Experience Team

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#28110]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
- [ ] Writing/editing to update existing unauthenticated (static) VA.gov page
- [x] Content support for an app or tool
- [ ] Something else (please add details in the next question)

## What do you need help with?

Per a conversation with @DanielleThierryUSDSVA, we'd like to use this ticket to track content needs for Phase 2 of the check-in experience.

All portions of the [user flow (screens and error states)](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=uc940f53ad96ac0203d6d3631) need to be reviewed. 

Phase 2 is focusing on 3 times:
- Adding last name and last 4 of SSN checks to verify identity
- Adding the ability to check-in if the Veterans has multiple appointments in the day (Phase 1 only allowed check-in if the Veteran had only one appointment that day)
  - Even if the Veteran has multiple appointments in a day, we will only allow them to check-in for one at a time. 
- Adding statuses to check-in.

## When does this content work need to be done?

EOD August 9, 2021 

## Do you plan to bring this to an upcoming content office hours session?

Since this is a ticket for ongoing work, I plan to attend content office hours as needed!

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [X] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Healthcare Experience Team
-	OCTO-DE product owner: Patrick Bateman
-	Product manager: @jparker0425
-	Designer: @kristenmcconnell 
-	FE engineer: @mdewey 
-	Product/team Slack channel: #check-in-experience

## Links to related tickets

- [Mural user flow](https://app.mural.co/t/vsa8243/m/vsa8243/1627494875812/0bcffe14dbd722d29b066a437e3e2b1d2be4dccb?sender=uc940f53ad96ac0203d6d3631)

**Comment by DanielleThierryUSDSVA** [comment]
## Text messages

_**_Note for discussion: * Had a thought about instructing folks to "text 838255" for crisis help. Do you think this could potentially confuse people to think they need to **reply** to this message with "838255" to get that help rather than start a new text? If yes, is there a way we can transfer to VCL if that happens? If no, do we want to give the VCL phone # instead?_

### Message content != "Check in" & Veteran Not Identified by #

We're sorry. We don't have this mobile phone number in our records.

If you're trying to check in to a VA appointment, use a mobile number that's on file with VA.

If you need more help with your appointment, call your VA facility.

If you're in crisis, text 838255 for 24/7 confidential help.

### Message content matches accepted responses for other use cases, i.e. CONFIRM, CANCEL, etc.

_**Note for discussion:** I'm not sure I quite understand this one from the message in the file. Specifically, I'm not sure what's meant by the "response options" from the "previous message." So I may not have this one right. If you can provide more details, we can refine further. Thanks!_

We're sorry. Our automated system doesn't understand your text. Check in with a staff member or reply with a response option from the last message.

Questions? Ask a staff member or call %FACILITY_PHONE%.

If you're in crisis, text 838255 for 24/7 confidential help.

To stop getting VA texts, reply STOP.


### CHIP not available for handoff

We’re sorry. Our automated system can’t check you in today. We're here to help. Ask a staff member to help you check in.

If you're in crisis, text 838255 for 24/7 confidential help.

### CHIP (message from dotted arrow)

We don’t have this phone number in our records. Try again using a mobile phone that’s on file with VA.

If you need more help with your appointment, ask a staff member or call us. Find our phone number: [facility locator URL].

If you're in crisis, text 838255 for 24/7 confidential help.
	
### Veteran has 0 appointments today.

We’re sorry. We couldn't check you in online today. Ask a staff member or call us for help with your appointment. Find our phone number: [facility locator URL].

If you're in crisis, text 838255 for 24/7 confidential help.

### At least one appointment is >30 minutes in future

_**Note for discussion:** We can go with the current message, or I also wrote up this version that might work. Let me know your thoughts._

You have at least one appointment today. But it’s not time to check in online yet. Try again up to 30 minutes before your appointment.

### Push text when time comes to check into appointment

You can check in for your VA appointment now at [URL].

## Check in at VA

**Check in at VA**

We need more information to check you in.

[field label] Your last name

[field label] Last 4 digits of your Social Security number

### Error (can’t verify identity)

**We couldn’t check you in**

We’re sorry. We couldn’t check you in with this information. Ask a staff member for help.

## Your appointments

**Your appointments today**

Here are your appointments for today: [Month, DD, YYYY]

[time] 

Clinic: [Clinic name]

[messages]
[appt time >10 minutes in past] 
Your appointment started more than 10 minutes ago. We can't check you in online. Ask a staff member for help.

[already checked in]
You’re checked in. We’ll come get you from the waiting room when it’s time for your appointment to start.

[check in now]
[button] Check in now

[appt >30 minutes in future]
You can check in starting at this time: [time]

### Error message (system not operational)

**We couldn’t check you in**

We’re sorry. Something went wrong on our end. Ask a staff member for help.

## You’re checked in for your [time] appointment

_**Note for discussion:** I know we all didn't like the "wait in the waiting room" so we could consider this alternative. Let me know your thoughts when you have a moment._

**You're checked in for your [time] appointment**

Clinic: [Clinic name]

We’ll come get you from the waiting room when it’s time for your appointment to start.

**Comment by DanielleThierryUSDSVA** [comment]
cc @peggygannon @shiragoodman

**Comment by DanielleThierryUSDSVA** [comment]
@peggygannon @RLHecht. From this form, we'll also have a new field label to add to the [design system list](https://design.va.gov/patterns/form-labels):

Last 4 digits of your Social Security number

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA I updated the va.gov page with the above content. My only comment is on the confirmation page. Here is a version with your suggested changes:
![Screen Shot 2021-08-10 at 11.10.28 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/8884afe9-b4e6-46eb-9d59-37e8bca5e7e0)

The spacing between the clinic and the waiting room sentence looked off. What are your thoughts about combining it in this way?
![Screen Shot 2021-08-10 at 11.49.38 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/c911242c-d657-4a97-99a9-dc073e54881d)

I like how you got rid of the waiting in the waiting room text.

@snyderje I only updated the va.gov part. I figured you would want to review the text messages and comment back to Danielle. Can you update the Mural when the final text wording is figured out?

**Comment by snyderje** [comment]
The concern about "text 838255" is a valid one, I could see a few possible solutions: 
1) adding an auto-reply from VEText if it receives a message with "838255" as the content, with more explicit instructions. 
or 2) changing language in the text to "text 'Hello' to 838255" - Hello being a placeholder for whatever word is a good fit.

I'll add the updates to sms messages to the phase 2 diagram, and the MVP flow where applicable. Thanks Danielle!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @kristenmcconnell and @snyderje!

@kristenmcconnell Yep, I think the 2nd version can work, at least for now.  I was just trying to keep the clinic name out of the middle of the sentence, as we're going to want to aim for not having dynamic content in the middle of sentences if/when we move forward with translating this. But I think it works here and we can address that in the future. I do wonder if we want to bold the clinic name in the sentence? 

@snyderje I like the simplicity of changing the wording, though the auto-reply seems like a good backup just in case. I think either of your suggestions in #2 can work. I kind of like the simplicity of "send a text to". Thank you!

**Comment by kristenmcconnell** [comment]
I'm torn on bolding clinic names. Clinic names are so important to Veterans. They commented on its importance in user testing, which is why I originally made them a heading style (so they stood out more). However, the actual names in the database are horrible (even the patient-friendly names aren't the best). If the names are so horrible, is it worse if we make them bold and large? I'm talking to VAOS more about this particular topic. They decided to minimize the clinic name on purpose and I want to hear more about what they have found out. I'll keep you in the loop.

**Comment by DanielleThierryUSDSVA** [comment]
That makes total sense to me re: bolding and the general issues with clinic names, @kristenmcconnell. Yes, keep me in the loop - thanks!

**Comment by kristenmcconnell** [comment]
@DanielleThierryUSDSVA Summary of what we discussed at today's sync. Again, we were hoping to have your content feedback by the end of this week.

Based upon the research findings from the Martinsburg visit ([draft research report](https://dsva.slack.com/archives/C022AC2STBM/p1631824953375300)) and Phase 2 Usability study ([Synthesis document - report coming soon](https://app.mural.co/t/vsa8243/m/vsa8243/1629923298341/3f6e350a2b322a4c77a92b30ae0dac25e42439d5?sender=uc940f53ad96ac0203d6d3631)), the following UX/UI updates are recommended to be made in the near-term: 
- Wording for an automatic text reply after the Veteran texts "check in," since the link takes awhile to appear.
  - Evaluate already existing wording from COVID screener listed in this text thread: https://dsva.slack.com/archives/C022AC2STBM/p1631890661399600?thread_ts=1631824953.375300&cid=C022AC2STBM
  - The COVID screener wording is ""Working on it. Standby..."
- Confirm "identity verification" wording with Danielle. This wording tested well.
![Identity Verification.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/ecbae90b-2085-4158-b9e3-0caca20371a5)
- Create the error state needed if identity verification fails, but a Veteran can still retry. A Veteran will be able to retry three times. This is connected to the next bullet down. I envision this error message to just change the last sentence to let the Veteran know that they can retry. Use error state style near the continue button on this page: 
![Screen Shot 2021-09-20 at 9.24.43 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/30ad3639-d359-4517-b2ef-10f068ee1d39)
- Verify the error state wording when identity verification fails and a Veteran can no longer retry. We somehow created two versions and we need to pick one. I'm assuming we want to go with the actual error state styling, but I wanted your opinion, Danielle.
![Screen Shot 2021-09-20 at 9.25.43 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/e84c74a2-3c56-49ad-bde4-4ec53436ecf8)
versus
![Screen Shot 2021-09-20 at 9.26.00 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/9b08414a-19a8-44d9-94f5-c3db7a5b8da3)
- Remove the word "ineligible" from the following appointment status:
![Screen Shot 2021-09-20 at 9.21.02 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/75733981-7018-405f-99fd-bbccfa094ec0)
  - This status will appear for appointments at clinics that haven't been onboarded to the mobile check-in project yet.

These last two items Check-in UX will work on first, then will review with content.
- Add facility information to the appointment cards. Look at VAOS design as an example.
- Look into refresh button or page last updated at X time for the appointment page.
  - We might want both "last updated..." wording paired with an action.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @kristenmcconnell! Let me know if you have questions or thoughts on any of this.

**1. Automatic text reply**
2 options:
We’re getting some information to start the check-in process. We'll text you a link to check in soon.
Or
We’re getting some information to start the check-in process. We’ll text you a link in a few minutes so you can check in.

**2. Identity verification**

Just a minor tweak:

We need some information to verify your identity so we can check you in.

**3. Error message with retry option**

Do we want to be explicit that we couldn’t verify their identity, or just generally state that we couldn’t check them in with the info they provided? Here are 2 options:

**We couldn’t check you in**
We’re sorry. We couldn’t check you in with the information you provided. Check your information and try again.
Or
**We couldn’t check you in**
We’re sorry. We couldn’t verify your identity with the information you provided. Check your information and try again.

**4. Error state with ask staff for help.**

Same question about explicitly mentioning verifying identity. Also, I think we dropped the facility phone number in other "ask a staff member for help" messaging so we might want to do that here as well. 2 options:

**We couldn’t check you in**
We’re sorry. We couldn’t check you in with the information you provided. Ask a staff member for help.
Or
**We couldn’t check you in**
We’re sorry. We couldn’t verify your identity with the information you provided. Ask a staff member for help.

**Comment by kristenmcconnell** [comment]
Any suggestions on content for this:
- Remove the word "ineligible" from the following appointment status:
![Screen Shot 2021-09-20 at 9.21.02 AM.png](https://images.zenhubusercontent.com/5f44055c65a5c54f7cfe5928/75733981-7018-405f-99fd-bbccfa094ec0)
  - This status will appear for appointments at clinics that haven't been onboarded to the mobile check-in project yet.

**Comment by DanielleThierryUSDSVA** [comment]
@kristenmcconnell Here you go!

We don't offer online check-in yet for this type of appointment. Check in with a staff member.

or

Online check-in isn’t available yet for this appointment. Check in with a staff member.

**Comment by ytsaoca** [comment]
@DanielleThierryUSDSVA 
For this part, 4. Error state with ask staff for help, do you recommend to use the title "We couldn’t check you in"
rather than "Check in with a staff member"?

Thanks

![Screen Shot 2021-09-28 at 10.37.25 AM.png](https://images.zenhubusercontent.com/6148b41faabf78b679dbacff/50309a9a-42af-4371-899e-20df4beaf592)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @ytsaoca. Yes, that's in #4 above.

4. Error state with ask staff for help.

Same question about explicitly mentioning verifying identity. Also, I think we dropped the facility phone number in other "ask a staff member for help" messaging so we might want to do that here as well. 2 options:

We couldn’t check you in
We’re sorry. We couldn’t check you in with the information you provided. Ask a staff member for help.
Or
We couldn’t check you in
We’re sorry. We couldn’t verify your identity with the information you provided. Ask a staff member for help.

**Comment by ytsaoca** [comment]
Hi @DanielleThierryUSDSVA We've good with Phase 2 changes. You may close this ticket. Thanks.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @niradatta1! Thanks so much for coming to office hours today. I love where you're going with the poster. 

As a follow-up, here's the text wording options I'd put in the ticket earlier for the automatic text that Veterans will receive before they get the text with the link.

1. Automatic text reply
2 options:
We’re getting some information to start the check-in process. We'll text you a link to check in soon.
Or
We’re getting some information to start the check-in process. We’ll text you a link in a few minutes so you can check in.

In our call, we talked about maybe avoiding "to complete your check-in" in the poster so we don't potentially risk giving them impression that clicking the link in the text is the last step.

We talked about "to check in" or maybe something with "start" or "continue."

We can definitely tweak the language in the text as needed. We'll just want to make sure that the poster and text language matches for consistency. Thanks!

**Comment by niradatta1** [comment]
@DanielleThierryUSDSVA Thank you, Danielle! Appreciate the feedback. 

I updated the language so it says "start your check-in" to better set up the expectation that the check-in is a process. This aligns with what's in the text messaging too, so it will be consistent. Let me know if you have any concerns, otherwise, we'll go ahead and use this language in our usability testing. 

Here's the  content design wireframe again for your reference:  https://whimsical.com/check-in-poster-content-design-concept-s-UWsas6z574Ca8MsjT6ZSep

**Comment by DanielleThierryUSDSVA** [comment]
No concerns at all, @niradatta1. Thank you!

**Comment by DanielleThierryUSDSVA** [comment]
@niradatta1 Yep, we can close. I'll do that now. @RLHecht for awareness. Thanks!
