### ISSUE TITLE
Auto-Scaling Jenkins 

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#2821]
## Problem statement
Right now Jenkins gets held up on longer Qs, if we introduced auto-scaling, this would take another manual step out of the process and make Jenkins more adaptable.

## AC
- [x] Look into ways to auto-scale Jenkins
- [x] Enable auto-scaling in Jenkins

**Comment by tskinn** [comment]
# Update

## How things work currently

The [bootstrap.groovy](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/bootstrap.groovy#L296-L363) file has been updated to configure a new Jenkins "cloud" via the ec2 plugin. The newest AMI with a label of app=jenkins-worker is used along with other config in the [jenkins-master-vetsgov-utility.yml](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-master-vetsgov-utility.yml#L166-L243) file.

Each worker template is configured to have a minimum of 1 instance running at all times and a maximum of 8 so Jenkins will immediately spin up two instances upon starting.

Each worker node has a single Jenkins [label with a value of 'vetsgov-worker'](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-master-vetsgov-utility.yml#L178) and is set to [only run jobs that require that label](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/bootstrap.groovy#L318) to facilitate testing of specific jobs before opening up the new workers to the world.

### Worker EBS Volumes

The worker nodes have two EBS volumes and an instance storage (because we are using c5d instance types). The instance storage is configured and mounted to the jenkins home directory /home/jenkins where the jenkins workspace will reside. The secondary EBS volume is configured and mounted to /var/lib/docker.

The root volume is only 8GB because the *ec2 plugin does not give us the ability to speficy the root volume size* of instances that the plugin spins up. However, it does give us the ability to add volumes via a [coustom mapping parameter](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/bootstrap.groovy#L339). Our AMI build process doesn't currently support specifying volume information so I decided to add an extra volume via the custom mapping parameter.

We wanted to use c5d instance types to take advantage of the higher disk performance provided. I'm not sure if I am making the best use of it at the moment.

Should we partition the instance storage in two and mount to docker and jenkins workspace and not provision an extra EBS volume? That would leave us about 90GB per partition if split evenly. (Currently the c5d.2xlarge gives 200GB instance storage but in reality its closer to 186GB it seems)

### EC2 Instace Userdata

Since we don't "deploy" the worker instances via ansible or package up the deployment via ansible like in most other situations we handle "deployment" configuration via userdata configured via the ec2 plugin.

Currently consists of this:

<details><summary>userdata shell script</summary>

```bash
#!/bin/bash
# setup local disk NVMe SSD drive provided with c5d types
# nvme1n1 corresponds to custom mapped device in SlaveTemplate
if [[ -e /dev/nvme1n1 ]]; then
  sgdisk -n 0:0:0 /dev/nvme1n1
  mkfs.ext4 /dev/nvme1n1p1
  service docker stop
  tar -c --use-compress-program=pigz -f /tmp/docker.tar /var/lib/docker
  mount /dev/nvme1n1p1 /var/lib/docker
  tar -xvf /tmp/docker.tar
  service docker start
fi
# setup local disk NVMe SSD drive provided with c5d types
if [[ -e /dev/nvme2n1 ]]; then
  sgdisk -n 0:0:0 /dev/nvme2n1
  mkfs.ext4 /dev/nvme2n1p1
  mount /dev/nvme2n1p1 /home/jenkins
  chown -R jenkins:jenkins /home/jenkins
fi

# The ec2 plugin uses aws key pairs to connect to nodes but we want the main user to be jenkins
# so we copy over the aws key pair
mkdir /home/jenkins/.ssh
cp /home/ec2-user/.ssh/authorized_keys /home/jenkins/.ssh/authorized_keys

# setup aws default region
mkdir /home/jenkins/.aws
echo -e "[default]\nregion = us-gov-west-1\n" >> /home/jenkins/.aws/config
# setup new tmp dir
mkdir /home/jenkins/tmp

# setup ssh config for github
echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile /dev/null\n" >> /home/jenkins/.ssh/config
cat << EOF > /home/jenkins/.ssh/id_rsa
{{ lookup('credstash', 'jenkins.va_vfs_bot.id_rsa') }}
EOF
cat << EOF > /home/jenkins/.ssh/id_rsa.pub
{{ lookup('credstash', 'jenkins.va_vfs_bot.id_rsa_pub') }}
EOF
chmod 0600 /home/jenkins/.ssh/*
chown -R jenkins:jenkins /home/jenkins
```
</details>

It starts by configuring volume devices and mounting them. The assumption is made that the instance storage is the last nvme device which has been the case as far as I can tell. The device is partitioned, formatted, a snapshot of the docker directory is taken, the partitionis mounted of the docker dir and snapshot is replaced. Same is done for jenkins home except no snapshot is necessary. Custom mapping notation: <image here>

Then the authorized_keys are copied from the ec2-user. This is necessary because ec2 plugin requires that we provide an AWS keypair that jenkins uses to connect to the ec2-instance. You can see in the UI that it will validate the given keypair. I'm not sure if there is a way around this.

The instance uses a instance profile role to access AWS but we still need to provide a default region so that is done here.

SSH keys are also setup for the purpose of accessing github repositories from the worker.

## TODO

Originally I was using the default ec2-user but found that there are docker images that use the jenkins user with a uid and gid of 504. So updated the ami build job to create a jenkins user matching those requirements and now the jenkins master has a jenkins user and the swarm/workers nodes have a jenkins user but they have different uids.

So the todo is to unify jenkins users between the swarm/workers and the master. I had updated the jenkins master build to create a jenkins user to use a specific uid when the EBS volume shared between deploys had the wrong UID because a user was added to jenkins.

## Other

We had talked about the possibility of having worker nodes custom built for specific jobs and I've tried to show how that can be easily added in the configuration by giving and example values optionally provided for each worker template and obiously we can expand on that. [Example](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-master-vetsgov-utility.yml#L232-L243)

## Status

### Deployments

Nothing has really changed here. Running the ansible jenkins deployment will terminate the jenkins instance without terminating any current worker nodes. You will need to terminate those manually at the moment. This is definitely something we can improve upon. You will notice immediately upon seeing Jenkins come back up that two worker nodes will be spinning up and the swarm nodes will eventually connect much later.

### Testing so far

I've tested the following jobs:
- [vets-website](http://jenkins.vfs.va.gov/job/testing/job/vets-website/job/test-on-new-jenkins-nodes/)
- [vets-api](http://jenkins.vfs.va.gov/job/testing/job/vets-api/job/test-on-new-jenkins-worker-nodes/)
- [devops](http://jenkins.vfs.va.gov/job/testing/job/devops/job/test-pipeline-job-new-jenkins-worker/)
- [jenkins-shared-lib](http://jenkins.vfs.va.gov/job/testing/job/va.gov-devops-jenkins-lib/job/test-on-jenkins-worker/)

### Updating

Instead of redeploying Jenkins for every little change it is possible to edit the configuration in jenkins directly in the cloud configuration UI. However it's possible to *break the plugin* this way.

I'd say your best chance of changing config and not breaking the plugin is to spin down all worker nodes (set min to 0 for each template, then delete the agents which terminates the underlying nodes as well) and then update the config. I've done this a few times with success but its not fool proof. It seems it depends on the part of the config being changed. Sorry I don't have more details on this.

**Comment by wyattwalter** [comment]
Implementation side is done, we have a PR to remove the old method queued up for merging in a couple of weeks. Leaving the old stuff there in case we need to fall back, but not seeing a need to fall back at this point.
