### ISSUE TITLE
Content review from VSA Claims & Appeals

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#28262]
## What do you need content guidance and support for?

- [ ] Content strategy and writing to create new unauthenticated (static) VA.gov page
- [ ] Writing/editing to update existing unauthenticated (static) VA.gov page
- [x] Content support for an app or tool
- [ ] Something else (please add details in the next question)

## What do you need help with?

For our Notice of Disagreement form, we received content updates to the Board review options page and the opt-in text. Please review the content added to this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28260

## When does this content work need to be done?

We would like to get this review done before 8/10. We don't have a definite date that we need to present these changes to the Board yet, but it may be soon.

## Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, chatbot content office hours (Fridays, 2:00 p.m. to 3:00 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VSA Claims & Appeals
-	OCTO-DE product owner: Matt Self 
-	Product manager: @vhenry07 
-	Designer: @kevinstachura (on vacation this week)
-	FE engineer: @Mottie   
-	Product/team Slack channel: #vsa-claims-appeals

## Links to related tickets

https://github.com/department-of-veterans-affairs/va.gov-team/issues/28260

**Comment by RLHecht** [comment]
@mnorthuis @shiragoodman @peggygannon for awareness

**Comment by bethpottsVADEPO** [comment]
@Mottie Can you show me the current screens for this content so I know what's changing here with stakeholders' latest edits?

**Comment by Mottie** [comment]
@bethpotts Screenshots as requested:

<details><summary>Opt-in page</summary>



![Screen Shot 2021-08-05 at 8 25 30 AM](https://user-images.githubusercontent.com/136959/128357806-d6fec91e-45a9-48c7-9a07-af66bebd2a16.png)</details>

<details><summary>Board option</summary>


![Screen Shot 2021-08-05 at 8 25 57 AM](https://user-images.githubusercontent.com/136959/128357803-51e17d71-fcb5-4a3e-8bb7-ab2af7e21dc6.png)</details>

**Comment by bethpottsVADEPO** [comment]
@Mottie Do you have a sense of how much we can cut/edit? This is a wall of text.

**Comment by Mottie** [comment]
I have no idea... it took a long time to get that back from the Board, so we might need to coordinate with them? cc: @vhenry07

**Comment by bethpottsVADEPO** [comment]
@Mottie Also, I'm not sure if what I'm seeing in the screen shots you sent me is the latest text I worked on with Kevin. Is it possible what you have is different from Kevin's mockups?

**Comment by Mottie** [comment]
I thought I had the most up-to-date available in staging... maybe I missed one change. Kevin will be back next week.

**Comment by bethpottsVADEPO** [comment]
@Mottie I may be wrong, but it seems different from my last suggestions I gave Kevin. I just would love to reuse that text instead of coming up with it again right now. I'd also like to have a sense of how much we can cut at this point, so I'll check in with him about that too.

**Comment by vhenry07** [comment]
@bethpotts We're looking for your expertise, so if you have thoughts on what should be cut, we'll take that back to the board for approval.

**Comment by bethpottsVADEPO** [comment]
**Opt-in text**

You can submit this online form (VA Form 10182) to appeal a VA decision dated on or after February 19, 2019. The Board must receive your completed form within 1 year (365 days) from the date listed on your decision notice. 

**If our decision involves a contested claim,** the Board must receive your completed form within 60 days from the date listed on your decision notice. A contested claim is when a favorable claim decision for one person results in denial or reduced benefits for another person. This includes claims about attorney fees or apportionment (when we assign part of a Veteran's VA benefits to a spouse, child, or dependent parent).

**If you have a Statement of the Case (SOC) or a Supplemental Statement of the Case (SSOC) from the old appeals system dated on or after February 19, 2019,** the Board must receive your completed form in one of these timeframes, whichever is later:
- Within 60 days from the date on the SOC or SSOC letter, **or** 
- Within 1 year of the decision date by the agency of original jurisdiction

If you opt in, we'll process your claim under the review option you choose. We won't continue to process your appeal in the old system. 

### Some notes for stakeholders:
- This text aligns with the VA.gov voice, style, and plain language standards.
- I'd strongly advise against linking off this opt-in page to https://www.va.gov/decision-reviews/ since the Veteran is already engaged in the application process. They may have trouble getting back to this page to finish their application.

**Comment by bethpottsVADEPO** [comment]
@vhenry07 @Mottie @kevinstachura Here's some plain language text for you to run by the Board for the Board review options screens. Let me know if you need anything else or need me to make any adjustments! For the opt in text above in this ticket, it may still be waaaaaay too long, but I tried to organize it and group it more effectively. Want to show me what it looks like when it's in and we can decide if we need to cut also? One thing we could do is cut the sentence I crossed out above...

**Board review options text**

**Direct Review:**
A Veterans Law Judge will review your appeal based on evidence already submitted. Because the Board has all your evidence, choosing this option will often result in a faster decision by a Veterans Law Judge. Based on current estimates, it takes the Board about 1 year to make a decision for this type of appeal.

**Evidence Submission:**
You can submit additional evidence within 90 days after submitting your Board appeal. Choose this option if you want to turn in additional evidence but don’t want to wait for a hearing with a Veterans Law Judge. Based on current estimates, it takes the Board more than 1.5 years to make a decision for this type of appeal.

**Hearing:**
You can request a Board hearing and submit additional evidence within 90 days after your hearing. Please keep in mind that this option has the longest wait time for a decision. Based on current estimates, it takes the Board more than 2 years to make a decision for this type of appeal. This is because of the high number of pending hearing requests.

**Comment by kevinstachura** [comment]
Ok, this is what I have for the updates to Board Review Options:

<img width="737" alt="Screen Shot 2021-08-10 at 2 24 49 PM" src="https://user-images.githubusercontent.com/54544300/128914556-2ea7040f-0053-4ee9-96e7-f6cb618cb9e7.png">

@bethpottsVADEPO: do you want me to re-bold up the time frames? Also, do you like the bolded labels like we had them before ("request a direct review" vs. "direct review")? Let me know what you would like to see changed and I will do so, then apply to all screens. Thank you!

**Comment by kevinstachura** [comment]
Also, here's a visual of what the opt in page would look like with the content changes:

<img width="675" alt="Screen Shot 2021-08-10 at 2 37 00 PM" src="https://user-images.githubusercontent.com/54544300/128916189-c17b24c5-6d43-4f16-94d0-fbdccab14bac.png">

**Comment by bethpottsVADEPO** [comment]
@kevinstachura Thanks! We're almost there. A couple tweaks to Board review options:

1/ Remove "Please" since I also saw that the error message in red uses "Please" and it is weird to have double "please" show up stacked. So: **Select a Board review option:**
2/ **Request a direct review:** remove second instead of Veterans Law Judge (it's in the second sentence). That'll shorten it a bit. 
So it'll be: "Because the Board has all your evidence, choosing this option will often result in a faster decision."

3/ **Request a hearing:** Add "with a Veterans Law Judge" to the first sentence.
So it'll be: "You can request a Board hearing with a Veterans Law Judge..."
Also: I'd like to incorporate the message from the last sentence into the second one like this:
"Please keep in mind that this option has the longest wait time for a decision because of the high number of pending hearing requests." (Then delete the last sentence altogether.)

And now just 1 tiny thing for opt in:
Where the bolded content is for SOC and SSOC, please remove bolding for "or a" that separates those 2.

This opt-in text is way too long, but when we shortened it, they lengthened it, and this has happened a couple times at least. So I think they're not going to accept anything shorter than this. We'll go with it. But definitely show them the plain language revisions.

**Comment by kevinstachura** [comment]
@bethpottsVADEPO also wanted to get your input on whether or not we should bold up the time frames again? From an experiential standpoint, I see value in doing so, but wanted to get your thoughts on that from a content perspective!

**Comment by bethpottsVADEPO** [comment]
@kevinstachura I agree with you--bolding will be good for scanning. Let's bold these words:
- about 1 year to make a decision
- more than 1.5 years to make a decision
- more than 2 years to make a decision
