### ISSUE TITLE
[Bug] VA accordion web component focus/scroll issue

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#28506]
## Description
_Sitewide content team identified a bug that's happening on this page: https://www.va.gov/pension/how-to-apply/fully-developed-claim/. 

## Replicating the Issue:
When I click the first and then the second accordion, they open fine. When I click the third, it bumps me down to the bottom of the page, though it does open the accordion. Same with if I were to click the fourth after click the second one open. Not sure what is going on. 

Link: https://www.va.gov/pension/how-to-apply/fully-developed-claim/

## Possible Solution
It's likely that it's a component-library (design system) issue. [Slack Convo](https://dsva.slack.com/archives/C52CL1PKQ/p1628617238133100) for reference.

**Comment by Rleahy22** [comment]
The web-component version for vets-website has been upgraded from 0.7.1 to 0.9.1 which includes the fix for this issue, and also changes the default behavior for `va-accordions` to allow multiple items open at once. That second change alone should prevent us from seeing this issue in the same places, but even with accordions that do not use the default behavior we should no longer see this issue due to the fix from https://github.com/department-of-veterans-affairs/component-library/pull/134

This fix should go out in the 3:00pm deploy today (8/12)

**Comment by brianalloyd** [comment]
Thanks @Rleahy22 validated this AM and fix is working good.  Appreciate the effort, closing out in support.
