### ISSUE TITLE
[FE] Notification Prefs: Replace checkbox component with adjusted radiobutton component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28502]
## Background
Now that we have made the necessary adjustments to the radiobutton component we need to replace the checkboxes in our existing design with this adjusted component.

## Tasks
- [x] Replace checkboxes with radio buttons as developed in [28114](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28114)

**Comment by erikphansen** [comment]
@ajakabcin A PR for this is up.

I did find a couple of bugs while developing it:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/28988
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28987

**Comment by ajakabcin** [comment]
thanks @erikphansen ! I'll drop these into next sprint

**Comment by erikphansen** [comment]
also found this bug https://github.com/department-of-veterans-affairs/va.gov-team/issues/29002

**Comment by erikphansen** [comment]
This can be validate on staging by either @ajakabcin or @andaleliz . I looked at it myself and it seems fine technically. There are some known visual bugs as I mentioned above. Feel free to call out any other additional refinements that you'd like to see, @andaleliz

**Comment by andaleliz** [comment]
@erikphansen it does seem fine technically, in fact, better than fine - great job! Thanks for catching and documenting those bugs you referenced too.

I have a couple visual refinements I want to ask about:

- I noticed the font size is sent to 1.7 rems for the legend, which works out to 17px. Is that the design system norm? I thought we had 16px for font size everywhere, so just want to be sure we're being consistent with the rest of the site.

- Is there a way to make the legend left align with the `h2` notification group title?  Whether or not it has the left border, everything should left align with the `h2`.  Right now, everything is a little farther left than the `h2`.  Here's a screenshot of the static design (left) and staging (right) side by side, and then another of the alignment I see once the border is gone on staging.

![Screen Shot 2021-08-24 at 10 14 27 AM](https://user-images.githubusercontent.com/55992116/130634903-f8ce17b2-18c5-4b09-8418-96dc10310511.png)

![Screen Shot 2021-08-24 at 10 16 06 AM](https://user-images.githubusercontent.com/55992116/130635769-b140f78c-7c83-4d3b-b23a-2bbebaf27f4e.png)

Also, want to confirm - is the indentation of and space between the radio buttons aligned with the design system component? I don't love that (I think I would prefer they be left aligned with the legend, and have a little more space between) but if that's the design system component styling then I trust that it's like that for a reason.  I mocked things up based on what I saw in the design system, but noticed the covid-19 email sign up form Maria showed us recently was different so want to double check.

I noticed some content things that don't reflect the latest, but assume those will get updated separately.

Thanks for all your work on this!

**Comment by ajakabcin** [comment]
Excellent work here @erikphansen! And big thanks to @andaleliz for the detailed notes! I'll reach out to tomorrow AM to get these into tickets.

**Comment by ajakabcin** [comment]
Confirmed on staging closing.

Will create follow-up tickets to capture [Liz's notes](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28502#issuecomment-904699852)

**Comment by erikphansen** [comment]
For the record I have seen this and will be address the issues soon.

@andaleliz The indentation and radio button spacing _does_ seem to be in line with the existing radio buttons component. It's interesting that indentation and spacing of the the checkboxes is different: https://design.va.gov/components/form-controls#radio-buttons vs https://design.va.gov/components/form-controls#checkboxes So I kind of doubt that all of the form controls have been reviewed with a fine-toothed comb recently. I also think that we should probably feel free to do whatever you think is best with these new radio buttons since we are already breaking away from the normal radio buttons.

As far as the 4px colored vertical bar falling off outside of the viewport, it seems like this is a consistent issue with all of the form controls and the "fix" for it is to make sure there is always adequate left margins/padding on the form control so that doesn't happen, which the notification settings page currently doesn't have.
