### ISSUE TITLE
[FE] Notification Preferences: Update UI to match new designs

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28503]
## Background
We need to ensure that the UI of the notification preferences feature is aligned with the new design as documented in [28126](https://github.com/department-of-veterans-affairs/va.gov-team/issues/28126).

- Designs linked [here](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/141756016/simulate/sitemap?mode=i)
- Content documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/frontend)

## Tasks
- [ ] Update UI to match designs linked above (_more specific punch list to come_)

**Comment by ajakabcin** [comment]
This looks good to me. I see the jump link is working after you make a selection for one of the notification items, clicking the link  again jumps you to the next notification item. Awesome work @erikphansen 

I think this is good to close, but would appreciate another set of eyes from @andaleliz

**Comment by erikphansen** [comment]
Thanks. I think we are at least 80% of the way there and further UI tweaks should get their own tickets so we don't miss them.

**Comment by andaleliz** [comment]
Hey, things are looking great! I verified the some content updates, and see jump link works as well in terms of taking me to the right section. I'm not seeing the focus halo go to the first radio button though. Is that coming later?

I see the description says "more specific punch list to come. Does that punch list exist yet?  It'd be helpful to know specifically what changes I should be reviewing vs what are further tweaks that haven't been addressed yet. 

E.g. I logged in with user 38 and see a double alert situation.
![image](https://user-images.githubusercontent.com/55992116/132540264-77322a63-5196-4e01-8955-16a0e4e4b9f0.png)

I'm not sure if that's something that should've been addressed in this ticket, would be covered later, or if it's something that actually doesn't matter since we're getting rid of the COVID email anyway.

**Comment by ajakabcin** [comment]
My hunch is that the double alert is tied to the covid notification item and when that's removed we would normally only see the "provide your phone number" alert in this scenario? 

Agreed on additional tickets for more specific issues. I was planning to cover that today in planning.

**Comment by andaleliz** [comment]
Okay - I just need to know a specific list of things I should be reviewing in order to respond appropriately.

**Comment by ajakabcin** [comment]
Closing this - additional UI changes will be documented as needed in individual issues
