### ISSUE TITLE
Evaluate CSS optimization libraries 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#2860]
# Overview 

vets-website's build process has nothing to reduce / remove unused CSS. Removing dead CSS can be a challenge in a large and long running repo.

# Tasks

- Evaluate PurifyCSS

**Comment by U-DON** [comment]
CSS optimization libraries may not be suited for the use case of improving performance on our static pages (including the home page). The process might involve using a tool that analyzes all the CSS being used for individual pages and outputs a filtered stylesheet without the unused styles. The issue is that all of the static pages uses the general `style.css` across the whole site, and it will likely not be scalable to scan the entire set of pages pulled from the CMS to generate pared down stylesheets for each and every page.

My current approach to the `style.css` that every static page uses is to look at the third party dependencies in our design system (Formation) and determine what parts of each library we can remove or load from other sources. Font Awesome and Foundation seem to account for a large part of Formation's size:

```
# Print the CSS files and their sizes (in KB) from local build of static pages.
# The CSS includes a local build of Formation with different modifications.
> stat -f "%-60N %z" *.css
```
```
Current:

style.7318e42ba76690217eb1-1574773704076.css                 492174
styleConsolidated.bb0d7d3e16682c7e997b-1574773704076.css     597260

Without Font Awesome:

style.ff900a163131a9e5299b-1574777850893.css                 437490
styleConsolidated.8f39ac7846186088d9a4-1574777850893.css     523017

Without FA and Foundation:

style.2e88b2671dc37311d2c7-1574774340932.css                 416879
styleConsolidated.73f161e3ec9a526e3c5b-1574774340932.css     496172
```

I think it will be more achievable to automate the CSS optimization in our React apps. CSS Blocks is a library that can integrate with React to generate stylesheets for particular components that remove the unused CSS. We currently use app-specific stylesheets, so we can potentially also use CSS Blocks at the app level instead of in specific components.

Sources:
- [How Do You Remove Unused CSS From a Site?](https://css-tricks.com/how-do-you-remove-unused-css-from-a-site/)
- [CSS Blocks](https://css-blocks.com/)

**Comment by rianfowler** [comment]
- We should optimize the app specific stylesheets- especially if it's not hard to implement. Do you know what the potential impact would be? For example the [comparison tool ](https://www.va.gov/gi-bill-comparison-tool) has a 4.5kb app stylesheet: 

<img width="466" alt="Screen Shot 2019-12-03 at 10 16 04" src="https://user-images.githubusercontent.com/4998130/70077489-337cae00-15be-11ea-95f8-ebb4a4267302.png">

**Comment by U-DON** [comment]
We could potentially use `critical`, an NPM package that takes critical (above-the-fold) CSS and inlines it. If we keep track of pages that have been scanned and "inlined", it might not be a huge time burden on CI once we have our initial set of modified pages.

https://github.com/addyosmani/critical
