### ISSUE TITLE
Update links to IRIS and GI Bill systems on the Contact Us page from Ask VA Team on the VRM product line

### ISSUE THREAD

**Issue by niranjan-sathindran** [department-of-veterans-affairs/va.gov-team#28848]
### Engineering support for:
- Redirects that have **first been vetted by the Platform Product Support team**. If you are requesting a redirect, please submit the [Redirect Issue Template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=vsp-product-support%2C+ia&template=redirect-request.md&title=Redirect+Request)
- REACT sign-in widgets or feature flags (flipper)
- Other engineering support from the Public Websites Team

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

## How to submit your request

- [x] Complete each area of this intake form that applies to your team's needs. Provide as much detail as you can so we can fully understand your request.  
- [x] Post a link to this issue: [#vsa-public-websites](https://dsva.slack.com/channels/vsa-public-websites), and in slack tag @brianalloyd, @kelsonic.    
- [x] If noted in the guidance below, please schedule any relevant meetings.

### When to submit your request

Please submit all engineering requests **at least 1 full sprint in advance** (so we can work it into our next sprint).

---

## About your app/tool/functionality

* **Is this request related to a VA.gov tool? If yes, provide a brief description of the tool or functionality:**  
   * The links that point to IRIS and Gi Bill on the https://www.va.gov/contact-us/ page needs to be updated to a new system called AVA that is going to replace all the functionality provided by IRIS and GI Bill. Currently this page on VA.gov has two links - Ask a question about your GI Bill benefits and Ask a question about your other VA benefits that points to the IRIS and Gi Bill systems. We need these two links to be combined into one link that just says "Ask a Question" or something similar, which then points to 3 different URLs based on conditions below:

1. If the user if unauthenticated, redirect to URL1
2. If the user is authenticated, and is LOA 1, redirect to URL2
3. If the user is authenticated and is LOA 2 or higher, redirect to URL3

* **Provide links to any available collateral: **Please link to existing IA requests**, product briefs/outlines, wireframes, prototypes, user research synthesis:** 
   * < links to collateral >

---

## About your support needs
*Please select all that apply, and follow related guidance.*        

### Frontend engineering support 
Not sure
   
- [ ] **Implementation of REACT sign-in widgets**
   * **Full spec including different states and behaviors:** 
     - < link to spec >
   * **Flipper unique id:** 
     - < unique id >
     
 - [ ] **Support for UAT testing or phased roll out of app/tool landing page**
    * **Full spec including different states and behaviors:** 
      - < link to spec >
    * **Flipper unique id:** 
      - < unique id >

**Note:** Apps teams engineers are responsible for flipper implementation related to their products. Our engineers can provide consultation as needed. [Read feature toggle documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/)

- [x] **Other**
   * Please describe in detail
      

### Desired/target implementation date

What's the ETA for the app/tool launch or the date when you need this request completed? Our team's capacity will determine which sprint the work falls into.

* 10/18/2021 in production. And earlier dates in lower environments to allow testing.

**Note:** As a best practice, PW does not release new products over weekends or holidays. Please plan accordingly. 

---

### About your team

- Team name: VRM
- OCTO-DE product owner: We're not an OCTO-DE product. Our Product owner is Stan Moran (stan.moran@va.gov)
- Product manager: Vine Reynolds / Kim Van Allen
- Designer: NA
- FE engineer: NA
- Product/team Slack channel: NA

--- 
#### Acceptance Criteria
- [x] Convert this request into a Zenhub epic
- [x] Follow-up with requestor to address any lingering questions/concerns
- [x] Create epic/tickets as needed for the Public Websites team to implement

#### Definition of Done
* Request ticket is closed and implementation tickets created as needed - **If you have content requests, please fill out the content [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/.github/ISSUE_TEMPLATE/sitewide-content-intake-form.md)**

**Comment by kelsonic** [comment]
Could someone please provide `URL1`, `URL2`, and `URL3`? 🙂

![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/e23c0287-dc63-454c-ab06-d3cf9f0efe72)

**Comment by brianalloyd** [comment]
@bethpottsVADEPO could you help us get clarification on the `URLs` @kelsonic specifies above?  Looks like this team is not and VSA team so not sure who to ping in ticket.  Thanks.

**Comment by bethpottsVADEPO** [comment]
@niranjan-sathindran Can you connect with @kelsonic about the urls you mention above?

**Comment by brianalloyd** [comment]
@bethpotts in regards to the below, could you confirm exact verbiage we should use in support:

> We need these two links to be combined into one link that just says "Ask a Question" or something similar,

**Comment by bethpottsVADEPO** [comment]
@kelsonic This may change (not sure at this point), but you can move forward with this link label:

**Ask us a question through Ask VA**

**Comment by kelsonic** [comment]
Perfect, thank you! 🙂

**Comment by bethpottsVADEPO** [comment]
@kelsonic Please adjust the link label to: **Ask us a question online**

Thanks!

**Comment by kelsonic** [comment]
PR is up: https://github.com/department-of-veterans-affairs/vets-website/pull/18689
I won't be able to test this until there's a react widget content block with react widget ID `ask-va`, perhaps you can help @RLHecht? We can sync on it tomorrow or whenever you have time 🙂

**Comment by kelsonic** [comment]
The new widget is live on staging (not production): https://staging.va.gov/ask-va/

We mocked up the page to look similar to the `/contact-us` page but as you'll notice it's not exactly like it. However, you can try out the `Ask us a question online` link with various authenticated profiles to ensure the link works as desired. The link is the only part of the page that is a React widget, so that's really all we're testing here:

![image](https://user-images.githubusercontent.com/12773166/134234487-72f9a24a-6df5-459b-a705-572db81e4fb2.png)

One last thing, if you want you can see all of the helpers that are used to calculate the `href` for the link [here](https://github.com/department-of-veterans-affairs/vets-website/pull/18689/files#diff-06f015f4454645e75b3613b77330578731e220ffaee219d6eb13b2e08ea385a5)

Thanks for the coordination on this everyone! Let me know if you have any questions and when I should promote this to production! 🙂

**Comment by kelsonic** [comment]
Was about to move this to validate but then I see that the AC on here incorporates other tasks as well, so moved it back to in progress 🙂

**Comment by kelsonic** [comment]
I think our work on Public Websites is done tbh, except for a follow-up ticket to promote it to production

**Comment by brianalloyd** [comment]
@kelsonic shifting to S57 until we can promote to prod, should be a quick lift for this sprint.

**Comment by bethpottsVADEPO** [comment]
@kelsonic When I click the link on the staging page you set up, I get an error message.

**Comment by kelsonic** [comment]
What error message do you get? [https://staging.va.gov/ask-va/](https://staging.va.gov/ask-va/)

I see this:
![staging va gov_ask-va_](https://user-images.githubusercontent.com/12773166/134401539-295da77a-03b8-4343-a9c6-cb0f2a522223.png)

Oh if you mean the ask-va react widget link, PW just links to the sites they provided, we don't have control over whether or not their sites work 🙂

**Comment by bethpottsVADEPO** [comment]
@brianalloyd Not yet. I think we'd better chat about what's needed next for this. Would it be appropriate for me to come to a standup or should we set up a separate meeting?

**Comment by VinePM** [comment]
Our standup?


Thank you,


Vine Reynolds
Project Manager/Scrum Master | GDIT
AVA Team
***@***.******@***.***>
***@***.******@***.***>


From: Beth Potts ***@***.***>
Sent: Wednesday, September 22, 2021 7:15 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Reynolds, Vining T (GDIT) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Update links to IRIS and GI Bill systems on the Contact Us page from Ask VA Team on the VRM product line (#28848)


@brianalloyd<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrianalloyd&data=04%7C01%7C%7Cdf67f0fcfbe94575e2be08d97e273dde%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637679529283551399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RekyH0pnAUZ1Rqy6vuzKRqANYnESlNq3lZmx5mNenmc%3D&reserved=0> Not yet. I think we'd better chat about what's needed next for this. Would it be appropriate for me to come to a standup or should we set up a separate meeting?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F28848%23issuecomment-925418999&data=04%7C01%7C%7Cdf67f0fcfbe94575e2be08d97e273dde%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637679529283551399%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jAmBHY%2BFseOoKC030o0uDDZfGTmzaB611hfKlHVotv0%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASHUH7ILTZUPORF4NGHHVEDUDJWRJANCNFSM5CKA2I7A&data=04%7C01%7C%7Cdf67f0fcfbe94575e2be08d97e273dde%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637679529283561355%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OonK1iaOWYPgDGKiCiGbawnPHUgFdaCWsERymyzi9rM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cdf67f0fcfbe94575e2be08d97e273dde%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637679529283561355%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uugXUxp6h1QdvDxAFOIer7MBQdWH5i3w2F3UzCVuspE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cdf67f0fcfbe94575e2be08d97e273dde%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637679529283571314%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NrusSDljf5Y1MKzQZGncwLxHOK3mzg1C0eo402bioTE%3D&reserved=0>.

**Comment by bethpottsVADEPO** [comment]
@brianalloyd @kelsonic Can you connect with @VinePM and @niranjan-sathindran regarding what they need to test this entry point react link ahead of launch of AVA on October 18?

**Comment by kelsonic** [comment]
Hey @VinePM and @niranjan-sathindran! 👋 

So my PM @brianalloyd is out tomorrow, but would you folks have time to set a date/time to meet early next week to discuss the next steps for you? 🙂 

https://staging.va.gov/ask-va/

**Comment by VinePM** [comment]
Hi Kelson,

Sure, I’ll put a meeting on the calendar for Monday.


Thank you,


Vine Reynolds
Project Manager/Scrum Master | GDIT
AVA Team
***@***.******@***.***>
***@***.******@***.***>


From: Kelson Adams ***@***.***>
Sent: Thursday, September 23, 2021 8:29 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Reynolds, Vining T (GDIT) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Update links to IRIS and GI Bill systems on the Contact Us page from Ask VA Team on the VRM product line (#28848)


Hey @VinePM<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVinePM&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796144145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fBXil2ESt4iDEJRpFeP68sC5rXdBYseo3ctO63eoUU0%3D&reserved=0> and @niranjan-sathindran<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fniranjan-sathindran&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796144145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kTcXpEwrGpxjl8UA2WsbKpAmSHA8y7pLrrsOabSF7dA%3D&reserved=0>! 👋

So my PM @brianalloyd<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrianalloyd&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796154109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S0Re6iiK4BSoDGMLuNk2fV%2FV07seseb0r3CoqIFP7X8%3D&reserved=0> is out tomorrow, but would you folks have time to set a date/time to meet early next week to discuss the next steps for you? 🙂

https://staging.va.gov/ask-va/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaging.va.gov%2Fask-va%2F&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796154109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jsabVh3zUgq3skl12vG7G6JXYxOHCTyDx6JvTQSjzec%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F28848%23issuecomment-926277591&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796164073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f8%2FDtAY3zcvKBPgMhAW0L21ZrMQNbvP6KJwGj8RAlp4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASHUH7N4Q54B3L4CIET575DUDPH7HANCNFSM5CKA2I7A&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796164073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cmXOydbY4v9vfFSnV43L9ple23dZQP0u2yXiQMDFZVQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796174017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=152f5SBV%2F9418echSqRcljgQ1%2BT6fM4uvjzyhHznfDc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796174017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nbBOU1jvWPMOe9lJWWM5HHswezAWMM%2FcnxZ%2FEkWp0FU%3D&reserved=0>.

**Comment by VinePM** [comment]
Could you all please forward your email addresses?


Thank you,


Vine Reynolds
Project Manager/Scrum Master | GDIT
AVA Team
***@***.******@***.***>
***@***.******@***.***>


From: Kelson Adams ***@***.***>
Sent: Thursday, September 23, 2021 8:29 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Reynolds, Vining T (GDIT) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Update links to IRIS and GI Bill systems on the Contact Us page from Ask VA Team on the VRM product line (#28848)


Hey @VinePM<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVinePM&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796144145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fBXil2ESt4iDEJRpFeP68sC5rXdBYseo3ctO63eoUU0%3D&reserved=0> and @niranjan-sathindran<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fniranjan-sathindran&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796144145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kTcXpEwrGpxjl8UA2WsbKpAmSHA8y7pLrrsOabSF7dA%3D&reserved=0>! 👋

So my PM @brianalloyd<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrianalloyd&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796154109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S0Re6iiK4BSoDGMLuNk2fV%2FV07seseb0r3CoqIFP7X8%3D&reserved=0> is out tomorrow, but would you folks have time to set a date/time to meet early next week to discuss the next steps for you? 🙂

https://staging.va.gov/ask-va/<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstaging.va.gov%2Fask-va%2F&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796154109%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jsabVh3zUgq3skl12vG7G6JXYxOHCTyDx6JvTQSjzec%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F28848%23issuecomment-926277591&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796164073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=f8%2FDtAY3zcvKBPgMhAW0L21ZrMQNbvP6KJwGj8RAlp4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASHUH7N4Q54B3L4CIET575DUDPH7HANCNFSM5CKA2I7A&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796164073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cmXOydbY4v9vfFSnV43L9ple23dZQP0u2yXiQMDFZVQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796174017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=152f5SBV%2F9418echSqRcljgQ1%2BT6fM4uvjzyhHznfDc%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd00082531f974f23577608d97efac4f0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637680437796174017%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nbBOU1jvWPMOe9lJWWM5HHswezAWMM%2FcnxZ%2FEkWp0FU%3D&reserved=0>.

**Comment by kelsonic** [comment]
Of course! 🙂 

Brian's email: brian.lloyd@gcio.com
My email: kelson.adams@gcio.com

**Comment by brianalloyd** [comment]
Notes from this AM's zoom sync:  On OCT 17th we'll send up a follow on PR to merge to production.  Work with Randi and publish Drupal page for publication.  Once pushed to production we'll send an email to all parties advising prod links are live in support of launch.

**Comment by kelsonic** [comment]
Let's do October 16 just to be safe 🙂

**Comment by VinePM** [comment]
October 16 is good, we will be Deploying to PRODUCTION on that day.
On October 18 we will Go Live.


Thank you,


Vine Reynolds
Project Manager/Scrum Master | GDIT
AVA Team
***@***.******@***.***>
***@***.******@***.***>


From: Kelson Adams ***@***.***>
Sent: Monday, September 27, 2021 9:43 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Reynolds, Vining T (GDIT) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Update links to IRIS and GI Bill systems on the Contact Us page from Ask VA Team on the VRM product line (#28848)


Let's do October 16 just to be safe 🙂

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F28848%23issuecomment-927943127&data=04%7C01%7C%7C1f4f1611f33d483c11bd08d981c51f0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637683505904484254%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zxprWP%2Fa2yJqK62TW%2Beoi5zXgP42UGOFmKGd4A7zHWQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASHUH7LIM7YWVTZO57GGAILUEB7HJANCNFSM5CKA2I7A&data=04%7C01%7C%7C1f4f1611f33d483c11bd08d981c51f0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637683505904494205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oBTSlefFaSIvG9wo0o54e%2FxqiStkhRKlsG%2BCZeuD4nw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C1f4f1611f33d483c11bd08d981c51f0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637683505904504158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=v8zE1oR%2FBe5NwLn2ySz6Nmu4duBtdaJwgk1YtFWTKG8%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C1f4f1611f33d483c11bd08d981c51f0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637683505904504158%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mnAV%2BHnHxrWMow9hnJIq4GzUIlrSdl2TVrj4i5ODRHY%3D&reserved=0>.

**Comment by kelsonic** [comment]
![image](https://user-images.githubusercontent.com/12773166/134931172-15b6f3cc-23fa-4344-9bda-f6fe483584d2.png)

@VinePM When you have a chance, could you please confirm that we mean:

3. If the user is authenticated and is greater than or equal to LOA 2, redirect to URL3

**Comment by brianalloyd** [comment]
Team, I created a new ticket to address the implementation of this component as reviewed this AM during our sync.  Since that action is during next sprint, I'm going to close this ticket in support and would ask everyone to shift conversation to the new ticket in support.  New ticket is #30570
