### ISSUE TITLE
[repo migration]: SiP Prefill

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#2895]
Content/IA steps:

- [x] Review vets.gov-team documentation with SME
- [x] Generate migration plan based on SME feedback; link to issue
- [x] Review PRs generated by Product Support
- [x] Complete Part 1 of [migration UAT checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/content-ia/vsp-repos/migration-uat-checklist.md) on documentation post-migration
- [ ] Follow-up communication with SME

Product Support steps:

- [x] Run migration script on linked migration plan file
- [x] PR for va.gov-team
- [x] PR for vets.gov-team
- [x] Merge va.gov-team PR
- [x] Merge vets.gov-team PR

**Comment by thatmattjohnson** [comment]
link to migration plan: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/sip-prefill

**Comment by billfienberg** [comment]
`vets.gov-team` PR: https://github.com/department-of-veterans-affairs/vets.gov-team/pull/20023
`va.gov-team` PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/3681

ZH: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/2895

One file was being problematic when running the migration script: https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Global/SiP-Prefill/Prefill/eMIS_Integration/eMIS_Documents/v2/eMIS_VADIR_xsd_Mapping_Build%25207.0%2520rules.xlsx

I suspect it's because the URL seems to be encoded. I'm currently investigating.
Aside from the one file, the migration plan calls for 73 files, and the PR contains 72 changed files.

**Comment by thatmattjohnson** [comment]
UAT completed for #3618 and #20023; all looks good. Closing this issue.
