### ISSUE TITLE
[FE] Notification Preferences: Implement conditional display rules for Prescription shipment and tracking  notification item 

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#28982]
## Background
One of the communication items for MVP under the Healthcare communication group, is Prescription shipment and tracking updates. This functionality is only available for the Asheville ([Charles George](https://www.va.gov/asheville-health-care/), 637, I assume)and Denver (554QA) facilities. Therefore, if the Veteran is not registered with either facility, this communication item should not display for them.

## Acceptance Criteria
- [ ] If a Veteran is not registered with a participating prescription shipment tracking facility (at launch, Asheville or Denver), i.e. they do not receive prescriptions from that facility, then this communication item does not display for the Veteran. Note: our filtering will be limited due to data limitations around parent-child facility ID's
- [ ] Display hint text explaining that this functionality is only available for specific facilities (text TK)

**Comment by erikphansen** [comment]
There are some issues with properly gating the Rx tracking feature based on the Veteran's facility or facilities. Basically, it seems like the Rx tracking feature is only available at certain _child_ facilities, but all we know if the _parent_ divisions a Veteran is registered at. 

For example, Denver's facility ID is 554QA. So, if someone is a patient at the Denver facility, we will know they are registered at ID 554 (not 554QA specifically). The same goes for someone who is a patient at Aurora (554GB) or Golden (554GC) or the Rocky Mountain Regional VA Medical Center (554). All we know is that they are associated with 554.

So the best we can do for gating the Rx tracking notification item is to gate it based on the parent division (554). Which means someone who is a patient at Aurora (554GB) will see the Rx tracking notification item even though they can't get those notification items.

To make things more confusing, a Veteran can be registered at more than one division. They might be registered at both 554 and 558 (Durham). We'd show the Rx tracking item because they are registered at 554. But maybe they only went to a 554 facility once and normally go to a facility in the Durham division. It would be slightly misleading to show them the Rx tracking checkbox since their normal facility does not support this feature.

I think the best approach might be to do two things:
- filter the Rx tracking item as best we can
- also add some supporting text next to the item that tries to explain this situation.

**Comment by ajakabcin** [comment]
Oof thanks for the explanation here @erikphansen. Let's discuss further in planning

**Comment by andaleliz** [comment]
@erikphansen How does this line up with what you were thinking in terms of supporting text? 
![image](https://user-images.githubusercontent.com/55992116/132732927-b5712259-73b7-4315-b235-c078b75e5720.png)

**Comment by erikphansen** [comment]
Yeah I think the first one is the way to go.

**Comment by erikphansen** [comment]
So I'll proceed with only showing this item to users who have 554 or 637 in their list of facilities. I'll also show it to users who have 983 in their list of facilities. 983 is not a real facility ID, but it's used in staging and it's the facility that user 36 is associated with.

**Comment by andaleliz** [comment]
Sounds good.  I've pinged Danielle to review the hint text messaging.

**Comment by ajakabcin** [comment]
Depending on what info Paras and Shane are able to provide on Monday we may be able to be more specific in the hint text. My concern is if there are multiple Denver facilities and only one or some of them have the Rx tracking, so it could still be misleading to a Veteran to see "Denver facility" and assume it's theirs.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz.

- For hint text, should it be "for patients registered at" or "for prescriptions filled at"?
- If we can get more specific with hint text, great. If not, what do you think about framing this as:

"Only available at some VA health facilities. Check with your facility first."

If it has to be vague, I want to at least give a call to action to check first so we're not leaving the Veteran guessing as to which facilities and what they should do with that info.

- If this isn't available at the person's facility but the "Select an option" alert remains persistent, that feels like it could get confusing/frustrating (ie, "Stop telling me to select an option when the option isn't available to me."). Makes me wonder if there's a way to add a third "Not available at my facility" option?

**Comment by erikphansen** [comment]
> Makes me wonder if there's a way to add a third "Not available at my facility" option?

The technical lift for that would probably not be worth it given how few people will ever see this radio button group. And how infrequently users will even see this page. Plus they could always select NO to get the yellow warning message to go away.

**Comment by DanielleThierryUSDSVA** [comment]
Makes sense - thanks, @erikphansen!

**Comment by andaleliz** [comment]
> should it be "for patients registered at" or "for prescriptions filled at"?

I'm not sure about that, or if we can be more specific.  If we can't, I like the idea of giving users some kind of step they can take by checking with their facility. Maybe it should be "Check with your pharmacy first?

@ajakabcin can you gather some more details about this notification from Paras and/or Shane and see what we can learn about 
- exactly which facilities are participating, 
- who at the facility users might be able to call, and 
- if it is about where people are registered or where they're filling prescriptions? Those might be the same thing.

**Comment by ajakabcin** [comment]
@andaleliz and @DanielleThierryUSDSVA - thinking about how to make this as clear as possible for Veterans while also keeping it evergreen to some degree, what if we simplified the message even further to this? 

> Only available at certain VA health facilities. Check with your facility first.

cc @erikphansen

**Comment by DanielleThierryUSDSVA** [comment]
@ajakabcin Absolutely in favor of simplifying further. 

The only question I have is for Veterans who might be registered at a facility in Asheville or Denver + one or more facilities outside of these areas. The simple version would be accurate, but including "Asheville and Denver" gives the person the signal that they shouldn't even bother checking at facilities outside of these areas. Not sure how likely that scenario is or how much the added detail would help. So, I'm good with removing the locations - just noting thinking here. Thanks!

**Comment by erikphansen** [comment]
Another thing to keep in mind is that the list of facilities that support this feature will grow.

**Comment by andaleliz** [comment]
Yes, exactly.  I know these two are a pilot - it'd be good to understand what the plan is once the pilot proves successful. Will all facilities participate, or will it be a very slow going process?

**Comment by ajakabcin** [comment]
Great convo with @shanemelliott  and @pcshah1026  this morning that answered several questions for us and helped relieve our concerns about child/parent facilities:

- The fact that we only receive the parent station ID indicating facility(ies) a Veteran is registered with is not an issue because for the pilot all child facilities under Denver and Asheville are participating. Facilities like this are known as consolidated sites.
- In the future, when consolidated sites want to opt into the Rx tracking functionality, Vetext will require an "all or nothing" buy in, so that all child facilities will need to participate, thus making the fact that we only receive the parent ID for a facility sufficient
- As new facilities are added the Vetext team will notify our team so that we can make the necessary updates on the frontend (low lift)
- In our proposed hint text, we recommend that the Veteran contact their facility to determine if it's participating in Rx tracking. The best place for them to ask about this is with their registered pharmacy.
- There is no difference between being registered with the VA facility and being registered with the pharmacy at the facility

@andaleliz and @erikphansen - did I miss anything?

Thanks again Shane and Paras!

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA, in addition to what we learned above we also talked about conditionally showing the hint text.  We'll show this hint text only to users who are registered at the participating facilities and any others. 

Since sites will continue to be added, we'd like to keep the text as generic as we can while still making it helpful.  

What do you think about:

"Only available at some VA health facilities. Check with your VA pharmacy first."

**Comment by erikphansen** [comment]
Initial version of the conditional display of this radio button group can be validated on staging. https://github.com/department-of-veterans-affairs/va.gov-team/issues/29879 will update the "hint" text and also _hide_ the hint text unless the user is associated with a mix of facilities that support Rx tracking and that do not support Rx tracking.

**Comment by ajakabcin** [comment]
Confirmed conditional display rules on staging with 36 (to appear) and cerner test user mhvcss4 (to not appear). Awesome @erikphansen !

**Comment by andaleliz** [comment]
Woot woot! Thanks @erikphansen! 

Just a heads up, since we haven't heard back from @DanielleThierryUSDSVA on the content suggestion, we might need to tweak that down the road.  

Danielle, you can still leave your feedback here even though it's closed. That will help us close the loop in the same place it started :)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @andaleliz. Looks good to me!

**Comment by MarciMcGuireGCIO** [comment]
Looking through the QA docs, it looks like there is already a [mockup](https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/142049300/simulate/sitemap?mode=i) for this case that looks like this:

![image](https://user-images.githubusercontent.com/73354907/160680455-76f6b7a0-fbf4-4d7d-b100-090c2f01a91c.png)
