### ISSUE TITLE
Determine approach for React landing pages

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#291]
We need to determine if React landing pages should live in Drupal and how to manage build flags around those pages.

We also need to figure out how to handle React pages that have a sidenav, which has to come from Drupal.

Some context in https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16395

**Comment by ncksllvn** [comment]
Adding site-wide team label, because doing this will help us be able to cut down on vagov-content  by removing content directories that are otherwise migrated completely into the CMS. For example, in the [`pages/health-care` directory](https://github.com/department-of-veterans-affairs/vagov-content/tree/master/pages/health-care), there are only two pages, both of which are almost empty and serve only as app entry points.

CC: @Karak888

**Comment by ncksllvn** [comment]
Created a ticket for updating documentation - https://github.com/department-of-veterans-affairs/va.gov-team/issues/1793 - but otherwise, this is done!
