### ISSUE TITLE
Deploy changed application builds for dev in master CI

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#29140]
## Description

For dev in master CI we are running a full build and deploy. We need to change this to run the same partial build we're using in the PR CI and sync the artifacts to S3 instead of doing a normal full deployment.

We still need to ability to run a full dev deployment for global upgrades or fixing any issues. This can be a manual option passed into the GitHub action to run and deploy the full build to S3.

## Definition of Done

- [x] master CI run partial dev build
- [x] master CI deploys only the built/changed files to S3 for dev
- [x] Full dev build/deploys are still possible

**Comment by theodur** [comment]
The [Manual dev/staging Deploy](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/manual-deploy-dev-staging.yml) workflow was updated to run a full build in correlation to the work for updating the [prod deploy](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34836), so full manual dev and staging deploys are still possible.

**Comment by theodur** [comment]
Currently, dev/staging deploys in `master` use the same [deploy script](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/github-actions/deploy.sh) that's used for prod deploys. Since this script is used for full deploys, one option is to make a new script, maybe something like `partial-deploy.sh` that simulates `deploy.sh`, but only syncs the assets from single app builds, without overwriting the S3 buckets.

In `deploy.sh`, the `--delete` option is [used](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/github-actions/deploy.sh#L213) in the [aws CLI sync command](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html), which deletes files that exist in the destination but not the source. This would cause the other untouched assets to be deleted in single app deploys, so we'll need to remove the usage of this option when we create `partial-deploy.sh`. There are also a few parts of the deploy script that won't be needed for the partial deploy, like [re-syncing the global assets](https://github.com/department-of-veterans-affairs/vets-website/blob/master/script/github-actions/deploy.sh#L158-L170).

Once we have the partial deploy script in a branch, we can test it on dev deploys by updating the [manual dev/staging deploy workflow](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/manual-deploy-dev-staging.yml#L163) to use it instead of the current deploy script. We'll also need to update the [Build dev job](https://github.com/department-of-veterans-affairs/vets-website/blob/master/.github/workflows/manual-deploy-dev-staging.yml#L49) to run a single app build, by changing the command to something like:
``` shell
yarn build --verbose --buildtype=${{ env.BUILD_ENV_DEV }} --entry=APP_ENTRY_TO_TEST
```

We can manually dispatch the [workflow](https://github.com/department-of-veterans-affairs/vets-website/actions/workflows/manual-deploy-dev-staging.yml) using the testing changes from our branch

![image.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/e9b9ceaa-0240-4279-a057-98d5a1355400)

It'll be important to use only the `dev` environment for testing so that we don't disrupt staging. The commit we use shouldn't matter as much, since the workflow will run a single app build with our testing changes regardless. We'll want to make sure to check the `dev-va-gov-assets` and  `dev.va.gov` buckets to make sure the correct assets are being synced, without deleting the other assets.

**Comment by theodur** [comment]
I added a [draft PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20479) for this after testing the functionality over the past week. 

Rather than determining which app assets should be synced in the `Deploy` job, the approach taken in the PR removes the unneeded global assets in the `Archive` job. This removes some extra complexity in the `Deploy` job and also optimizes the `Archive` step in the pipeline, since unneeded assets won't be uploaded to the `vetsgov-website-builds-s3-upload` S3 bucket for single/grouped app builds. 

If we didn't remove unneeded assets in the `Archive` job, we would need to know the names of the lazy loaded assets in the `src/platform` directory, so they can be excluded in the partial deploy. The problem with that is lazy loaded assets in `src/platform` can change, resulting in the need to update to  the exclude list in the partial deploy, which isn't ideal. Also, staging and prod builds have unnamed non-app chunk files that get lazy loaded, and it's harder to exclude those since they're not named.

The global asset removal happens in the `global-asset-removal.sh` script. This is needed so we can get the names of lazy loaded chunks in the directories of the changed apps. This lets us know which lazy loaded assets belong to the changed apps. Doing this in the `Archive` job is easier, since we can checkout the repo in the job and use the `app_folder` output from the `Unit test` job to know where to search for the Webpack chunk file names.

I also added the `partial-deploy.sh` script that I mentioned in the previous comment. This script works similarly to the `deploy.sh` script that we currently use, except it doesn't delete assets that aren't in the source tar when syncing. It also doesn't sync global assets like the `deploy.sh` script does. Global assets in `partial-deploy.sh` are still excluded in the S3 sync just to be safe, but they should already be removed in the build tar from `vetsgov-website-builds-s3-upload` since they'll be removed in the `Archive` job.

An example workflow looks something like:

```mermaid
  graph TD;
      A[Build] -- app entry names -->C;
      B[Unit Tests] -- app folder paths -->C;
      C[Archive] -- only upload app entries and app lazy loaded chunks-->D[Deploy];
```

Where the `Archive` job runs `global-asset-removal.sh`, and the script searches the `app folder paths` from the `Unit Tests` job for instances of `webpackChunkName:` being used in imports, and grabs the names of those chunks. Only files with the name of the `app entry names` and chunk file names are compressed in a new tar before being uploaded. All .txt files, like `BUILD.txt` are also included in the tar. 

This also reduces the chances of global assets ever being modified in changed app deploys, since they won't exist in the build bucket. The `global-asset-removal.sh` script won't run for full builds, so those assets will be uploaded unfiltered to `vetsgov-website-builds-s3-upload` as usual.

**Comment by timwright12** [comment]
makes sense to me, let's see if it works

**Comment by theodur** [comment]
After having this enabled for the past week and monitoring, assets have been syncing properly for changed app deploys.

Here's an example of two changed app builds that were deployed consecutively in `master`:
![Screenshot 2022-03-18 at 11-38-30 department-of-veterans-affairs_vets-website Frontend for VA.gov.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/11bfc6fd-011c-40cb-987a-fe37a5c46333)

The `dev-va-gov-assets` bucket after the two deploys:

![Screenshot 2022-03-18 at 11-37-55 dev-va-gov-assets - S3 bucket.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/dbbea3ec-5dec-41ad-850a-d89698febdf0)

The assets were sorted by descending `Last modified` in the screenshot. Only the Check In and GI application assets were recently synced at the time, while all other assets were untouched.

The same can be seen in the `dev.va.gov` bucket:

![Screenshot 2022-03-18 at 11-36-49 dev.va.gov - S3 bucket.png](https://images.zenhubusercontent.com/5e56a58c13bedb092ce69379/8ef207c8-4e0d-4de4-b3ee-f81f50ce7549)

This has been the case for all the changed app deployments I've monitored. I have been doing E2E testing using the test plan from https://github.com/department-of-veterans-affairs/va.gov-team/issues/34864

**Comment by theodur** [comment]
Once E2E testing has been completed with the remaining apps in the test plan, I'll close this ticket and enable changed app deploys for staging (announcement will be made before enabling).

**Comment by theodur** [comment]
Testing for dev has been completed. Closing this, and moving on to enabling for staging
