### ISSUE TITLE
IA Review from Facilities Team

### ISSUE THREAD

**Issue by lildziner** [department-of-veterans-affairs/va.gov-team#29332]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page

## What do you need help with?
Would like input on some page layout ideas and talk through some challenges before design intent.

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to [problem statement detailed in discovery issue](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/24630)
- Link to [user flows](https://app.mural.co/t/vsa8243/m/vsa8243/1627038564401/bdd84c5da65e1000f7d3d2f2d365d03839a1466e?wid=0-1629295040929&outline=open)
- [Link to rough mockups](https://app.mural.co/t/vsa8243/m/vsa8243/1627038564401/bdd84c5da65e1000f7d3d2f2d365d03839a1466e?wid=0-1629899357084&outline=open)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes (Tues, Aug 31st 11:30a eastern)

## When does this work need to be done?
- Content and IA work needed by: Friday Aug 27, 21
- Ideally, would like to discuss the ideas and refine before design intent.

## Do you plan to bring this to an upcoming content office hours session?
- [ ] No, but I'd like to schedule time to talk about this request **OR**
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Dave Conlon
-	Product manager: Michelle Middaugh
-	Designer: Leyda Hughes
-	Product/team Slack channel: #vsa-facilities

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

**Comment by mnorthuis** [comment]
@lillianjwarner  Feedback based on mocks here: https://app.mural.co/t/vsa8243/m/vsa8243/1631037297093/f42e9797d06d776f255651afcc64b977025d977a?wid=0-1631797331748&outline=open

V2
- This version creates a flow that leads with dates rather than locations.  The user needs to drill down through a specific date to see the location details and the full schedule for that location.  Would be curious if users are generally willing to travel to a location based on a date, or would they be looking for a location near them first?  
- The schedule-based view and label is somewhat of a mismatch for a "locations" section
- The locations would be listed multiple times if multiple events are scheduled (high likely), and all would link to the same location detail page. This creates the potential for a lot of extra clicking without getting any new information. 

V3
- Creating a list of locations for this type of facility is a better match to the locations area of the site.  And segmenting the mobile locations into their own section keeps the primary left nav shorter. 
- However, the mobile clinic listing page doesn't provide a lot of value to the user and creates an additional click to get to a specific location.  

V4
- This option puts all location types on the same level - VAMC, clinics and mobile clinics.  This creates a much shallower structure and fewer clicks to get to location details. 
- However, this does create a very long locations page and very long left nav. 
- With a shallower structure, a schedule page could be supported under each mobile location. 
- This would be my preferred option since it keeps a consistent and simple structure. 
- Some options may need to be explored for the left nav such as setting the order of locations so that all mobile clinics appear at the bottom of the list, or removing mobile clinic options from the left nav all together. 
- Another option to explore is to add something like the "on this page" component to the locations page to provide visibility and quick access to the different types of locations on the page - Main locations, Health clinic locations, Mobile clinic locations, Other nearby VA locations.

**Comment by mnorthuis** [comment]
@lildziner Just checking in to see if you had determined a direction yet.  Let me know if there is any additional information you need from me.  Based on the 3 options you are looking at currently, there isn't any new templates/pages to be added to the VAMC structure, only use of existing templates and structure.   

If you decide you want to explore left nav options, or need help with any on page navigation, let me know.  Also, if you decide to add a schedule page to the structure, we can work out  placement and URL for that new page.

**Comment by lildziner** [comment]
@mnorthuis thanks for checking in. This is the design that the Facilities team landed on for MVP [UXPin:](https://preview.uxpin.com/20fd05cf8e86ce628f0c813166424d0a6ca38bfd#/pages/142311876/simulate/no-panels). 

![image](https://user-images.githubusercontent.com/4960080/135523819-0fc84a67-298e-425d-bf15-9923a229da56.png)
It is the smallest change that we can do, in the short term, to offer mobile clinics the ability to list a schedule without impacting IA or broader page design, as it just replaces the 'Clinical hours' section of the page.

That said, I am finishing up synthesizing two feedback sessions [#30687](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30687) where this design was discussed to validate/invalidate its effectiveness. Palo Alto immediately challenges this solution.  In short, we learned that for this calendar year they have 200+ “stops”, traveling to 46 unique locations. In their case, there could be 5+ unique locations in “San Jose, CA” alone so those would show up as “Mobile clinic - Jan Jose, CA” 5 times in the left nav but all would actually be different addresses.  Their MMU services are “walk-in”, not scheduled but felt strongly that they were healthcare services and not events (which they also support).

So, in my recommendations, I will point be pointing to a your suggestions for a near term improvement iteration.  

@mmiddaugh Correct me if anything has changed in this plan.

**Comment by mnorthuis** [comment]
@mmiddaugh Wanted to check in with you to see if there is anything you need from content or IA regarding the mobile units for MVP?  Sounds like you are working with what you have for the MVP and will come back around for enhancements at a later time, is that correct?

**Comment by mmiddaugh** [comment]
exactly - thanks for checking @mnorthuis - we can close this issue
