### ISSUE TITLE
[MCP] Add 'Notice of rights and responsibilities' content to the details page

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#29384]
## Issue Description

Our stakeholders requested that we provide the 'Notice of rights and responsibilities' content on the subsequent Veteran Patient Statement pages within MCP's UI.

---

## Tasks
- [ ] Design the detail page's modal with the content in alignment with other tools' Privacy Act modal design

## Acceptance Criteria
- [ ] The UXPin has been updated and linked in this ticket

**Comment by rebeccawalsh** [comment]
@leahkeeler FYI while Linda is out of the office -- Riley was working on this ticket and felt that the text was excessive (the first image isn't even all of the text). Most of the contents are found elsewhere in the tool. We're questioning whether or not the full Notice of Rights and Responsibilities as it's written in the paper letter is required in our tool. They did request it, but we don't think that it will provide any value because it would require someone reading a looot of info that's not really plain language.

Should we bring this up to them synchronously in a meeting or async?

**Comment by leahkeeler** [comment]
Let's bring this up in the big wed. meeting for input - I agree it's a lot

**Comment by rebeccawalsh** [comment]
It doesn’t look like we have a Wednesday meeting until next week?

**Comment by leahkeeler** [comment]
shoot - we do not. Go ahead and email brandon and jerry cc: Jill - they should be able to reach consensus in the background.

**Comment by rileyorr** [comment]
FYI I opened a sitewide content intake request [(#29489)](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/29489) for this work to get support on how the content team has approached this with other forms/tools. I plan on going to Thursday's content office hours to chat with Danielle about it.

**Comment by rileyorr** [comment]
Went to content office hours and Beth said she would sync with Danielle about this work and would get back to us on the ticket I linked above

**Comment by rileyorr** [comment]
Danielle suggested that we include all the content because it's a legal notice and that we create a ticket in the backlog to condense/plain language it post-launch. 

She also sent me an example of a privacy act modal on the site that uses scrolling, so we can utilize that for this content. 

I updated the design with an example of the general size/look of the modal ([link](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/141491503/simulate/sitemap?mode=i)) and added a frontend ticket explaining what we're going for ([link](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/29678))
