### ISSUE TITLE
TIC Gateway 503 message for VA.gov Outage Events

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#29401]
## High Level User Story/ies
As a Veteran, I need a lightweight informative/helpful 503 page that I can reference when VA.gov is experiencing technical issues via an offline event. In the event the site is completely down, reassuring messaging such as "we're working to fix the issue..."  accompanied with key phone #s to call if they need help quickly would help Veterans remain proactive in gaining access to benefit related questions or services. 

[Slack Thread](https://dsva.slack.com/archives/C52CL1PKQ/p1630007038026300) 

## Hypothesis or Bet
**If** _create a lightweight informative/helpful 503 page that can be referenced when VA.gov is experiencing technical issues and offline._ **then** _Veterans will better understand next steps in order to remain proactive in gaining answers to questions/services._

## Considerations / Next Steps
- Define "Content" messaging for 503 message 
- Determine "design/UX" elements for 503 message (mockup) 
- Implement FE solution for review/validation on Staging Environment 
- Determine hosting solution (host ourselves or ask the Gateway Operations team create another subdomain under va.gov, such as error.va.gov, and create a DNS record from error.va.gov to a hosted environment such as our S3 bucket within AWS).

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## Definition of Done 
- New 503 messaging FE build (Content + Design Components provided) 
- Validated in Staging and tested (a11y, WCAG 2.1 Compliant) 
- Hosting solution is determined and validated 
- New 503 message deployed and in place ISO next total outage event

**Comment by FranECross** [comment]
@chriskim2311 @jilladams Do you know if there's a 503 message implemented? No rush, just going through and trying to clean up the backlog. I found that another ticket on this epic was implemented, but not closed or noted in the ticket. Thanks!

**Comment by jilladams** [comment]
A 503 page like this would fall in the category of system level pages. This is sort of like the 404 page discussion last week -- since Sitewide contract began in April 2022, the system pages haven't explicitly been in our product portfolio. 

Most of them live in the very old vagov-content repo, per Tim's note here: https://dsva.slack.com/archives/C01SR56755H/p1688146527609169?thread_ts=1688075566.034609&cid=C01SR56755H, and AP folks are some of the only folks I know who have write access to / know anything about that repo. 

So: I would say this sits in a similar place as the 404 discussion [here](https://dsva.slack.com/archives/C03ES2LMNTH/p1704995732462979) in the private PW Product channel with Dave, where the system level pages probably don't currently have an owner and @davidconlon is working out who makes the call about the destiny of them.

**Comment by jilladams** [comment]
(This ticket, though, makes a case that they stay with Public Websites. TBD.)

**Comment by jilladams** [comment]
Oh - and to your previous question re: whether this 503 page was created: no idea.

**Comment by jilladams** [comment]
Ah ha! Accelerated Publishing is tracking the deprecation of vagov-content, and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10929 addresses the utility pages I mentioned. Tim references a 503 page, which means: it exists! Closing.
