### ISSUE TITLE
[FE] Notification Prefs: Implement recommendations for radio button spacing

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#29473]
## Background
As noted in the comments of #28502 we needed to make some additional tweaks to the radio buttons in Notification Preferences to improve the spacing in/around them. Liz provided her recs in #29276.

See documentation and specs for full details.

https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/notifications/notification-preferences/frontend
 
## Acceptance Criteria
- [ ] inputs are left aligned with the legend
- [ ] inputs are spaced 24px apart

**Comment by erikphansen** [comment]
@Mottie did you change something with this ticket 21 minutes ago?

**Comment by erikphansen** [comment]
@andaleliz this can be validated on staging

**Comment by Mottie** [comment]
I added a new ZenHub workspace (`va-claims-and-appeals`) and it automatically migrated a bunch of tickets, but it shouldn't have effected the pipeline in the VFT workspace.

**Comment by andaleliz** [comment]
Hey @erikphansen definitely looks better! Thanks for your work on this. 

I noticed the spacing between the two inputs is 20px vs 24px. I think it's probably still sufficient to prevent people from fat fingering on touch screens, but curious to learn the thinking behind knocking those 4px off.

![image](https://user-images.githubusercontent.com/55992116/132557375-8589b542-3a42-4c8b-b095-30740654fdad.png)

**Comment by erikphansen** [comment]
@andaleliz I was visually measuring the px between the actual radio buttons which was 23 between them when they are in the unselected state and I figured that was close enough.

<img width="467" alt="Screen Shot 2021-09-08 at 1 02 23 PM" src="https://user-images.githubusercontent.com/20728956/132577307-2e9f3cff-9308-4b46-87c6-88bdb9b5a1ca.png">

But we can and should revisit this because the actual hit areas for each radio button and associated label is _not_ what it should be. The hit area should be vertically centered around where the button and label appear to be. This is also an issue with the standard radio buttons, not just ours.

<img width="677" alt="Screen Shot 2021-09-08 at 1 07 46 PM" src="https://user-images.githubusercontent.com/20728956/132578065-a0234760-2ac7-4998-8f47-d2cd4dad3f27.png">

**Comment by andaleliz** [comment]
Oh, great catch! We should revisit that.  Do you want to tackle that as part of this work, or should I open a separate radio button bug issue for the design system team?

**Comment by ajakabcin** [comment]
> But we can and should revisit this because the actual hit areas for each radio button and associated label is not what it should be. The hit area should be vertically centered around where the button and label appear to be. This is also an issue with the standard radio buttons, not just ours.

@erikphansen and @andaleliz by this do you mean the alignment or the spacing? trying to determine if this particular ticket can be closed or if it needs additional work. Thanks!

**Comment by erikphansen** [comment]
If Liz is amenable I'd like to call this spacing good enough and refine it along with the hit areas in a future ticket

**Comment by andaleliz** [comment]
I'm completely amenable to that :)

**Comment by erikphansen** [comment]
Chances are the fix to the hit area will only be for our radio buttons. We've probably diverged enough from the original for a fix to apply to both.

**Comment by erikphansen** [comment]
Closing since Liz seems to have agreed that the padding is good enough for now!
