### ISSUE TITLE
Form 526 Supplemental Forms

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#29708]
## Issue Description
We need to implement 2 additional forms but we need to determine if there are any technical or content changes to the forms prior to implementation. Reference this [Epic.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3475) 

---
## Tasks
- [x] Look at paper pdf forms and see if there are any changes we'd need to make for the digital version prior to release.

## Acceptance Criteria
- [x] Completed documentation outlining any required changes. Are forms ready to go as-is?
---

**Comment by chrvalla** [comment]
Form 21-8940. All questions in the paper form exist in the online Staging environment, except: 
The paper form asks for "VA File number". This is not asked for in Staging. 
The paper form has a separate section for treatment by doctor and hospitalization. In Staging, this is one question. 
Otherwise, Form 21-8940 and Form 21-4192 in Staging have all the questions from the paper form. The two forms in Staging seem to be ready to go online. Closing ticket.
