### ISSUE TITLE
Discovery: Audit cross app imports and make recommendation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#29742]
## Details 

As part of #29134 we discovered a complication of numerous cross app imports that will complicate single app builds. 

The goal of this ticket is to better understand the issue and decide how we want to proceed (should we address the issue now? If so, how?) 

## Notes

* edu-benefits may need to be treated as a single app
* forms system executes some Cypress tests on other apps? That might be something we need to look into further (if the app's deploy goes out we need to make sure the forms system's tests also pass) — note that we can have required builds and tests if we need (a subset of things that always happen)

## To Do 

- [x] List all cross app imports
- [x] Determine which imports should be moved over to a Platform directory
- [x] Determine which imports are necessary to remain as is 
- [ ] Determine approach for completing this work and coordinating with VFS teams (make tickets)

**Comment by theodur** [comment]
# Instructions on getting dependent imports for an application
There are two ways to get the dependent imports of an app. Both of these ways will list all the files outside the app that import code from the app. The benefit of getting external files (files outside the app) that import from an application rather than getting the external app imports that an application has is that the former allows us to see whether an application can pass CI in a single app build. If an application doesn't have external files that import its code, any code changes to that application shouldn't affect any other part of the repository, and therefore only need to run the app's tests in CI.

## Method 1: Using the [Madge](https://github.com/pahen/madge) dependency tool
Madge is a tool used for generating dependency graphs. You should be able to use the Madge CLI via `npx`, but if not, you can always [install](https://github.com/pahen/madge#installation) it on your machine.

To get a list of the external files that import from the app that you're inspecting, run:
`npx madge --extensions js,jsx --depends "APPLICATION_DIRECTORY" src`

What this does is it checks if there are any files in the `src` directory that depend on any import containing the name of the `Application_directory`. If the output is empty, then there are no external dependencies on the app directory specified, otherwise, you will see a list of the external files that import from the app. These are the files that need to be added to the `Dependents` column in the spreadsheet.

## Method 2: Using ESLint to find unresolved imports
Since ESLint will throw an error when the path to an import doesn't exist, we can use this to our advantage. This method temporarily deletes the directory of an application locally, and runs the linter to see if any errors are thrown. If so, we know that there are external files that import code from that application.

Steps:
1. Locally delete the directory of the application you are inspecting.
2. Run `yarn lint` (Usually takes about 2-3 minutes).
3. Examine the console output. If there are any `Unable to resolve path to module` errors, we know that external files import code from the application. If there are no `import/no-unresolved` errors, we know that no external files import code from that application ✅.
4. Copy the path of the files from the `import/no-unresolved` errors, if any, and add them to the `Dependents` column in the spreadsheet.
5. Discard the local changes that deleted the application's directory

## Testing single app builds in GHA
If after using either of the methods above, and you find no external files that import code from the application, you should test the single application build in GitHub Actions to ensure it passes.

To test a single app build, you can edit the `Build` step in the Continuous Integration workflow to only run the build of the app you are inspecting. You would add the `entry` option to the command for that step: 
```yml
# Full build
yarn build --verbose --buildtype=${{ matrix.buildtype }}

# Single app build
yarn build --verbose --buildtype=${{ matrix.buildtype }} --entry ENTRY_NAME_OF_APP
```
After updating the Build step in the GHA workflow, you'll need to update a file in the application's directory to trigger its tests to run. You can add a comment to a random file in the directory, and that should trigger the single app build's Cypress tests to run.

In addition, you'll need a few more changes to ensure test selection always runs, since we're updating files outside the `src/applications` directory. You can use the changes from this [branch](https://github.com/department-of-veterans-affairs/vets-website/compare/single-app-build-template).

**Comment by theodur** [comment]
After completing the audit, there are 23 applications that have other apps importing from them. I recorded the audit in this [spreadsheet](https://docs.google.com/spreadsheets/d/1K2QtE9qQXS1uFnlKXzAIsGr9Grin5k5RzLsSreQosCU/edit#gid=0). Next steps are for me to go through the imports and determine which ones need to stay, and which ones need to be removed.

**Comment by meganhkelley** [comment]
@theodur could you make that spreadsheet publicly viewable? Thanks!

**Comment by theodur** [comment]
@meganhkelley Whoops, sorry about that. You should be able to view it now!

**Comment by theodur** [comment]
# Types of external imports

Going through the external imports of apps, I found some common themes in the imports and divided them into these types.

## Manifest File
Some applications, primarily the Dashboard app, import the `manifest.json` file from other applications. This is done solely to get the `rootUrl` of the app. Since places that import the manifest files are getting the `rootUrl` dynamically, we probably don't need to run the build of the importee, or run their Cypress tests.

One thing to note is that some Cypress tests in the repo visit the hard-coded URL of the application's root URL. For example, the static-pages app test `src/applications/static-pages/tests/application-status.cypress.spec.js` uses the hard-coded root URL for multiple apps. This means if any of those apps made changes to their `manifest.json`, the static-pages test would fail. This can be resolved by converting them to dynamically import the app's root URL from their manifests.

**Needs to be removed for single app builds**: No

## Constants
Just as the name of this section describes, these are constant variables that are imported from applications. Most of these imports are objects of static lists. Although the likelihood of constants changing is low, These imports will cause code breaking changes if not tested for.

**Needs to be removed for single app builds**: Yes

## Widget
These imports are used by the static-pages app. They are mostly importing widgets or data needed for widgets. These imports probably won't be able to be removed, since the widgets in the app directories tend to use code from the app. So even if we moved them into the static-pages directory, they would still be dependents of the app. We'll probably have to figure something out for these imports. We may end up having to build and run static-pages tests.

**Needs to be removed for single app builds**: No

## Utility Functions
There are situations where apps are importing helper functions from other apps. These imports would cause issues with single app builds, because we'd be in a situation where we need to build two unrelated apps together and run both tests just because one of the apps uses a helper functions of the other. Some examples I saw were the `scrollToTop` and `inferAddressType` function.

**Needs to be removed for single app builds**: Yes

## Form Definitions
There are only a few instances of these imports, but these will also be problematic for single app build. Some apps are importing form system definitions from other apps, which isn't ideal. These form definitions can probably be moved into the `src/platform/forms-system/src/js/definitions` directory, and both apps import from them. `confirmationEmailUI` is a good example of this, where one app creates this definition, and another app uses that definition from the app. 

**Needs to be removed for single app builds**: Yes

**Comment by theodur** [comment]
I created tickets for the applications that can have some or all of their dependent's imports removed. There are some applications with dependent imports that I didn't make tickets for because their dependent's imports can't be removed:

`facility-locator`: Most dependent imports are importing the manifest file. The only other app that is importing anything different is the static pages app, and those imports most likely need to stay.

`gi`: The only dependent application that is importing from `gi` is the `gi-sandbox`. These two apps will most likely need to be deployed together anyway, since they seem to share common functionality and is owned by the same team

`validate-mhv-account`: The only dependent application is the static pages application, and it's importing constants that are specific to the `validate-mhv-account`application. Since those constants are application specific, it probably isn't the best option to move it into the `platform` directory.

The other applications in the [spreadsheet](https://docs.google.com/spreadsheets/d/1K2QtE9qQXS1uFnlKXzAIsGr9Grin5k5RzLsSreQosCU/edit#gid=0) that don't have tickets have dependents that solely import types that can't be removed, such as manifest file and widget imports.
