### ISSUE TITLE
Discovery: What would it take to make padding/margins for checkboxes and radio buttons consistent

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#29836]
Follow up from DSC meeting on 9/10 when issue around Margin/padding discrepancy between checkboxes and radio buttons was discussed. 

Action items for DST

- [ ] Determine level of effort to make this change. Look at code for these components and see how they’re structurally formed. 
- [ ] Identify any down stream effects if we change padding to get margins and spacing equal. 

Original issue
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/534

**Comment by caw310** [comment]
@bkjohnson , Sorry, assigned to you since you were at the DSC meeting. We'll figure out when we can get this LOE done.

**Comment by caw310** [comment]
There is a chance that the spike team working on the new forms system may rebuild these.

**Comment by pdavies88** [comment]
This issue is linked to: [https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/29838](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/29838)

**Comment by pdavies88** [comment]
Current Analysis:
Checkboxes in default state have `margin-bottom: 0.65em;` and `margin-top: 3rem;` 
When an error state is initiated `margin-top` is set to `0`

Other issues:
All `input` tags have the following rules set on them `height: 4.2rem;` `margin: 0.2em 0;` `border: 0.1rem solid #5b616b;` causing both Radio and Checkbox `input` elements to overlap with the sibling element below them

.form-radio-buttons have the css rule of `padding: 6px 12px;` on them.

Recommendations:
- Design team should be looped in to provide mocks of how the checkboxes and radio buttons should look when in the default state and error state.
- The padding, margin, and general spacing should be the same for both checkboxes and radio buttons.
- Styles should be unified for both components since sometimes they are being applied to both components and other times they are not which is causing the inconsistency.

**Comment by pdavies88** [comment]
LOE once we get design input is probably half a day of work since it's just CSS updates

**Comment by pdavies88** [comment]
Designs for spacing: [here](https://www.sketch.com/s/cbfcac05-b6fa-4f3d-a1b6-5defe1dd79c6/a/JnmM5mb)
