### ISSUE TITLE
Discovery: Determine LOE to fix the issue where error message causes checkboxes to jump around

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#29838]
Follow up from DSC meeting on 9/10. 

- [ ] Determine LOE to fix the issue where error message causes checkboxes to jump around

- [ ] Get priority from Kevin and Ryan once we have the estimate. 

Original ticket
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/532

**Comment by caw310** [comment]
See this issue for additional information. https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/vets-design-system-documentation/532

**Comment by pdavies88** [comment]
Issue that's occurring which is that[https://github.com/department-of-veterans-affairs/component-library/blob/master/packages/web-components/src/components/va-select/va-select.css#L23]( https://github.com/department-of-veterans-affairs/component-library/blob/master/packages/web-components/src/components/va-select/va-select.css#L23) overwrites the CSS for margin-top set here: [https://github.com/department-of-veterans-affairs/component-library/blob/master/packages/web-components/src/components/va-select/va-select.css#L48](https://github.com/department-of-veterans-affairs/component-library/blob/master/packages/web-components/src/components/va-select/va-select.css#L48)

**Comment by pdavies88** [comment]
Natalie with design team to provide spacing between Description, Error Message, and Checkboxes and/or Radio buttons when Error state is active to create consistency in the components.

**Comment by pdavies88** [comment]
Current Analysis:
Checkboxes in default state have `margin-bottom: 0.65em;` and `margin-top: 3rem;` 
When an error state is initiated `margin-top` is set to `0`

Other issues:
All `input` tags have the following rules set on them `height: 4.2rem;` `margin: 0.2em 0;` `border: 0.1rem solid #5b616b;` causing both Radio and Checkbox `input` elements to overlap with the sibling element below them

.form-radio-buttons have the css rule of `padding: 6px 12px;` on them.

Recommendations:
- Design team should be looped in to provide mocks of how the checkboxes and radio buttons should look when in the default state and error state.
- The padding, margin, and general spacing should be the same for both checkboxes and radio buttons.
- Styles should be unified for both components since sometimes they are being applied to both components and other times they are not which is causing the inconsistency.
Related issue:

**Comment by pdavies88** [comment]
@caw310 LOE once we get design input is probably half a day of work since it's just CSS updates

**Comment by pdavies88** [comment]
Designs for spacing: [here](https://www.sketch.com/s/cbfcac05-b6fa-4f3d-a1b6-5defe1dd79c6/a/JnmM5mb)

**Comment by pdavies88** [comment]
Issue stems from Formation: [here](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-form-elements.scss)
