### ISSUE TITLE
BGS::PeopleService::VAFileNumberNotFound

### ISSUE THREAD

**Issue by craigwheeler** [department-of-veterans-affairs/va.gov-team#29864]
## Issue Description
Receiving errors in Sentry for the BGS people service. Sentry Link: http://sentry.vfs.va.gov/organizations/vsp/issues/35358/?project=3&query=is%3Aunresolved+source%3Ayour-debt+VAFileNumberNotFound&sort=user&statsPeriod=90d

```
BGS::PeopleService::VAFileNumberNotFound
```

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by denisecoveyduc** [comment]
@ScottyRJames doing some GH clean up.. I am popping this out out of the Sentry epic and just adding it into the portal tech debt. That said I am not sure the work is clearly defined nor am I sure that this is still a relevant issue since Craig opened it in Sept 2021. When you have time, could you validate that this should remain in our backlog? thanks.

**Comment by HeatherRienks** [comment]
Per backlog refinement on 10/18.....

**Comment by HeatherRienks** [comment]
Per @ScottyRJames o he identified 7 instances of this in the past week. Still an issue.  Is this expected behavior? Need more info, no BE work needed

http://sentry.vfs.va.gov/organizations/vsp/issues/135038/?environment=production&project=3&query=is%3Aunresolved+controller_name%3Adebts&statsPeriod=14d

BGS is used to fill in payment history (used to auto-populate FSR). 

Need BGS contacts - @kjsuarez will reach out in vfs- all-teams channel for help

**Comment by HeatherRienks** [comment]
@kjsuarez to chat with Thomas Blackwell from BGS to get more info

**Comment by HeatherRienks** [comment]
@Tom-Davis - is this something we should take a look at before next sprint? (S113)

**Comment by Tom-Davis** [comment]
Yes - Per BR this can be pulled in the next sprint

**Comment by kjsuarez** [comment]
I did some digging and it looks like the error is just a harmless clash between identifier services. This is pretty typical of platform and as far as I'm concerned, not a huge concern.

We already fall back to user ssn when this error occurs, which appears to be the way that other teams handle these identifier clashes: https://github.com/department-of-veterans-affairs/vets-api/pull/12530

Credit to Thomas Blackwell for the help finding precedent.
