### ISSUE TITLE
Business intake form for Claims & Appeals Team

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#30005]
## What is the business outcome you are trying to achieve? (required 1-2 sentences) 
We would like an automated alert to notify a Veteran if their disability claim submission has failed and provide instructions for how to resolve. 

## What is an overview of the notification use case? (required 3-5 sentences) 
Today, when a Veteran submits a disability claim on va.gov, most of the time the claim is successfully received and proceeds through upstream processing. However, there is no notification of failure. When for technical or other reasons, that claim submission fails, the Veteran has no way of knowing. 

## What is the user journey during which this notification will take place? Is there a desired behavior change? ( required 3-5 sentences) 
The Veteran will attempt to submit a claim via our online application. If that submission fails, then the Veteran should be notified so that they can try again. 

## Is this notification already being sent and if so how? (Yes/No and optional 1-2 sentences) 
No

## What kind of notification would this be? (required Email, Text, Not sure)
Email or text

## Have you spoken to your Privacy Officer about your content /  use case and has it been approved? (Yes, No, Not Sure) 
No

## What system will your notification be triggered from i.e. vets-api? (required 1-2 sentences) 
vets-api

## Do you have the business logic in that system to trigger an API request to us? (required 1-2 sentences) 
Yes. We already have a notification configured for when a form526 submission succeeds.  We would like to add notifications for the final time a job fails and we can call and can make that call from: EVSS::DisabilityCompensationForm::SubmitForm526#sidekiq_retries_exhausted

## Do you have the data or access to the data needed for your notification i.e. email addresses, unique identifiers (optional yes, no, not sure)
Yes

## Do you have a budget for this? Please see details on the cost of using our service here. (optional yes, no, not sure)
Not sure

## What is your estimated volume of notifications per day, week, month? (optional - open space)
Unsure

## When does this notification need to be in production? (optional - open space)
30-90 days

**Comment by miabecker** [comment]
Hi @vhenry07 welcome to our VANotify intake! Your ticket looks great and the use case totally makes sense. When you are ready can your share your content and we can help a bit with that as well as get you into staging. Looking forward to working together!

**Comment by vhenry07** [comment]
Thanks @miabecker. We'll work on the content and update when ready.

**Comment by miabecker** [comment]
@vhenry07 checking in and updates on your content here?Thanks!

**Comment by vhenry07** [comment]
Should be done this sprint.

**Comment by vhenry07** [comment]
Update. We will need more time to work on the specific messaging for Veterans as during our discovery, we realized that there may be several error conditions, warranting different email message. We also need to be sure we're able to direct Veterans on the proper course of action to take. Dependencies on other teams involved, so this work will take some time.

**Comment by vhenry07** [comment]
Hi @miabecker linking to the content that we'd like included in the email. [34119](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34119)

**Comment by miabecker** [comment]
Thank you for sharing! We actually launched a new UI where folks can create their own notification template. Here is the information to access it so you can create your new notification:

**Comment by vhenry07** [comment]
GM @miabecker I've signed into staging.

**Comment by miabecker** [comment]
Hi @vhenry07 great to hear from you. We've given you access to staging so you can create your draft template and test in staging. Let us know if you have any questions or concerns.

**Comment by bevnobev** [comment]
Hi @vhenry07.  Happy New Year!  If you are interested in analytics around the form  download, don't forget to add utm info to the link.

**Comment by vhenry07** [comment]
Hi @miabecker I've signed into staging, ready to release our email template.

**Comment by miabecker** [comment]
@vhenry07 we normally like folks to create their notification but given it seems like you are close to launch I created one for you here. You'll still need to add the UTL like Bev mentioned and we'll need to recreate in production but at least you can test with this notification in staging. Let me know if you have any other questions: https://staging.notifications.va.gov/service/5e5cded3-3c76-46a3-9eef-cb63589e76be/templates/7efb8dfc-f30c-4072-b900-ae393aa1114b

**Comment by miabecker** [comment]
Here is your template in prod for when you are ready and like Bev mentioned above don't forget to add in the UTM info to the link: https://notifications.va.gov/service/5bda137e-689e-4532-b3d2-2c81c0324331/templates/7e7719cb-f2c8-4856-9733-825e25f39dd8

**Comment by bevnobev** [comment]
Hi @vhenry07.  Checking in to see when you plan on launching.  I saw you sent an email in prod last week, so I'm curious

**Comment by bevnobev** [comment]
Hi @vhenry07.  Checking in to see when you plan to go live with this notifications.  No rush, just trying to get an idea of a date range.    cc: @mjones-oddball

**Comment by bevnobev** [comment]
Thanks @vhenry07.  Do you recall the go live date?

**Comment by Eallan919** [comment]
@zlaw would you please add your notes for the meeting here for posterity? Thank you!

**Comment by zlaw** [comment]
Sure, trying to find out who the new team is.  Once I'm able to talk to them, I'll include notes.

**Comment by zlaw** [comment]
From Kyle Soskin:

- Now owned by the 526 team #benefits-ce-disability_exp_1
- Intended to be triggered here: https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/evss/disability_compensation_form/submit_form526.rb#L49
- Has a specific error it looks for and that error has since been resolved or now comes back differently [submit_form526.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/workers/evss/disability_compensation_form/submit_form526.rb)

**Comment by RakshindaAslam** [comment]
https://dsva.slack.com/archives/C04KW0B46N5/p1681835540155059Kyle Soskin
  27 minutes ago
I would be wary about turning it on or using it without full testing of WHEN it triggers, and if those are correct times for it to be triggering, especially because there are now backup submission paths where, previously it would have failed, will now still get through via a paper submissions. I have also heard in passing that the VBA does not always want a veteran to know when certain types of failures occur (for example, when an application fails to establish due to suspected fraud or a fraud-lock on an account/veteran they would not want any email to notify the (potential) fraudster that in any way that would tip them off or possibly cause them to alter or change their methods/whatever they are doing. (edited) 


Kyle Soskin
  24 minutes ago
So, while yes this notification is for sure super useful, we are actively working to ensure that there is never an instance that this would need to fire. IE all submitted claims either get established automatically, and if not, get sent through central mail as a PDF. So the only time this email would be valuable to go out is if neither of those actions happened. But in that case it should really go to someone at the VA or ones of these teams or someone to investigate and fix/figure out why, rather than the veteran... or at least, some think that.


Kyle Soskin
  22 minutes ago
.... in summary, I would not try to just turn this on without significant thought and discussion and testing, and think it NOT going out at the moment, is for the best, since without all the thought/discussion/testing it could actually cause more trouble than it helps. If for instance it sends an email incorrectly, or when a claim has already been filed via one of the 2 ways, but then it prompts them to fill one out, to mail, resulting in duplicate claims, causing delays and issues for the veteran.

**Comment by zlaw** [comment]
Thanks, @RakshindaAslam!  Closing this issue accordingly.
