### ISSUE TITLE
[Research] Notification Prefs: Prep materials for UAT

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30165]
## Background
We need to ensure that Notification Preferences is working properly for users. This ticket is to prepare the materials needed to conduct UAT.

- [UAT research plan example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-research-plan.md)
- [UAT conversation guide example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-conversation-guide.md)
[VSA UAT Guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/platform/research/planning/what-is-uat.md)

## Tasks
- [x] Create the UAT research plan and conversation guide (examples linked above)

**Comment by andaleliz** [comment]
[Draft started](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/uat/notification-preferences-uat-plan.md)

**Comment by andaleliz** [comment]
@ajakabcin and @erikphansen can you please review the [primary participant criteria](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/uat/notification-preferences-uat-plan.md#recruitment-criteria) I've come up with and confirm it'll meet our needs?

I'm thinking we **have** to have:
- people with LOA3 accounts (do they have to be Veterans, or could they be a caregiver)?
- people with and without health care to test that section logic correctly
- people who are or aren't registered at a Denver or Asheville VAMC to test that notification logic

And I'd like to run the whole thing on mobile since we haven't done any mobile testing so far.

**Comment by erikphansen** [comment]
That looks good to me

**Comment by ajakabcin** [comment]
Yup agreed - looks great! I don't know if Veterans vs caregiver is critical, but I suppose wouldn't hurt to have that mix. Would just want to note in case we encounter different experiences

**Comment by andaleliz** [comment]
[Conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/uat/notification-preferences-uat-convo-guide.md), [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/uat/notification-preferences-uat-plan.md), and [notes template](https://docs.google.com/spreadsheets/d/1sgvVtdbtEaRT9oKpgpFNTmHdgpa2e0Vlu3qJurDneIs/edit#gid=0) created. I'll move the notes template out of google docs, if needed, once we know who will take notes.  Otherwise I'll export and upload to GH once we're done.

I'm getting some fellow researchers to review this; will seek review from @ajakabcin once it's all buttoned up from the practice area perspective.

**Comment by andaleliz** [comment]
@ajakabcin The docs linked in the comment above are ready for your review. Can you please take a look before I close this ticket out?

**Comment by ajakabcin** [comment]
Looks great @andaleliz! One main question for you and it's more so for coordination/logistics, but in the research plan and the convo guide you reference ensuring that the backend systems are working properly, for example:

- In the research plan, under [research questions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/uat/notification-preferences-uat-plan.md#research-questions), the 4th bullet says "are the backend systems supporting those actions functioning as expected?", and 
- In the convo guide, item [3. Manage notification settings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/uat/notification-preferences-uat-convo-guide.md#3-manage-notification-settings---5-minutes) - in the 6th UAT task you mention confirming their changes were saved in the API. 

How are we planning to confirm those? For the second item, I assume through the save message that should appear, but do we need people from VA profile on the sessions with us to help confirm these are functioning properly?

Otherwise looks great! Awesome work as always : )

**Comment by erikphansen** [comment]
I just thought of something to keep in mind as part of recruitment. Ideally we'd know the email address they use to sign in so we can turn the feature on for them before the session begins.

**Comment by andaleliz** [comment]
@ajakabcin to answer your question
>How are we planning to confirm those? 
I'm completely unsure. I wrote those in assuming UAT covers the whole product, not just FE.  How did you ensure everything was working correctly with all the APIs for My VA UAT? We can probably do it the same way.

@erikphansen, great catch on the email address. I'll include that in the recruitment plan so Perigean knows to provide that with the participant roster.

**Comment by ajakabcin** [comment]
@andaleliz excellent point! I'm also not sure. I'll consult with Samara and see what she things :)

**Comment by ajakabcin** [comment]
@andaleliz I checked in with @Samara-Strauss on this and while the testing for My VA and Notification Prefs is different given that Veterans are actually saving (writing to a database with their actions), her thought was that we could add one step to the UAT tasks after the make a selection and that is to have them refresh the page to ensure that their actions were properly saved. Of course this is in addition the error and success messages built into our UI that appear when the selection is saved or not saved in the case of an error. 

So the tl,dr is that we don't think we need someone from VA profile, assuming that @erikphansen and @lihanli agree with the idea of testing the refresh as an additional way to ensure everything was saved.

cc @Samara-Strauss in case I missed anything here :)

**Comment by erikphansen** [comment]
Adding a page reload make sense. It should definitely just work. And if it didn't work it'd point to a problem with VA Profile.

**Comment by andaleliz** [comment]
That sounds good to me! Thanks everyone. I've updated the UAT and am closing this out. All tasks completed 🎉
