### ISSUE TITLE
[Research] Draft Conversation Guide: Harassment Reporting Tool (HRT)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30234]
## Issue Description
Research ticket to draft conversation guide to support #24883, Harassment Reporting Tool initiative.  

## Acceptance Criteria
- [x]  Draft conversation guide
- [x] Share both with Lauryl, Brian, Dave, Cassandra, Shawna, Soni
- [x] Incorporate all feedback 
- [ ] Discuss recruiting and launch with Lauren
- [ ] Start collaboration with VSP (if needed)--Brian is coordinating an async midpoint review

**Comment by cindymerrill** [comment]
Started drafting conversation guide but have a long way to go on it.

**Comment by cindymerrill** [comment]
Worked on this using my notes from SME interviews.

**Comment by cindymerrill** [comment]
Incorporated feedback from a researcher, an SME, and Dave Conlon. Updated on Github and downloaded slightly shorter versions for Soni to share with her stakeholders on Friday.

**Comment by cindymerrill** [comment]
Since hearing today about the pause in this project research, I'm closing this ticket for now. I'm ready to launch Veteran recruiting whenever I receive the go-ahead from stakeholders. Here's the link to the conversation guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/harassment-reporting/research/usability/conversation-guide.md
