### ISSUE TITLE
Resolve open content parity/rewrite items: Education

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#3028]
Bulk of parity and legacy rewriting content work is complete except for a few outstanding items. The tickets associated with this epic tracks those open items to make sure they get completed. 

EX: Some pages still need to be reviewed w/stakeholders, rewritten, and/or migrated from Heroku versions into Drupal. 

Yellow Ribbon participating schools content
Edu parity open items

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  Here is the updated document with all the Education parity/rewriting updates, including the main Yellow Ribbon landing page, with question to SMEs about how often the individual state school info changes, and that if it's often - annually for each state and several schools per state, we recommend linking to legacy pages so they can easily manage those updates for now. If updates are few and not every year, we can show them how we would pull each state info into the accordions in the main page: States A-D > Alabama > List of schools in Alabama.

[Education rewrites for SMEs v1]
(https://app.zenhub.com/files/133843125/64325d92-f097-42c9-b9b4-4630c403e14c/download)

**Comment by jenniferlee-dsva** [comment]
Hi Anne - about to send them email with deck and CC you. 

Can you provide me a list of the pages (page names) that you want to discuss with them? I'd like to give them a quick, easy to scan table of contents in the email, of exactly what pages are being covered. 

Also, the preview links go to 404 errors. I've played with them a bit and it looks like it has to include the http:// in order to work, so I'll add that before turning the deck into PDFs for them.

**Comment by jenniferlee-dsva** [comment]
@Anne - Let's tb 1:1 before I send. Seeing a few things that I don't understand, maybe just an oversight, but thought I'd check with you first. 

EX: 
![image.png](https://images.zenhubusercontent.com/5bb2975c143b4d2ee7a35ef6/1d639d71-37c5-46c8-b54c-b30f044de9c3)

**Comment by AnneHurley** [comment]
@jenniferlee-dsva Apologies, yes we should delete that random text box, thought I had. Let me know when you'd like to chat to go over the edits.

**Comment by AnneHurley** [comment]
Direction from SMEs:
1. We'll implement updates and edits to the setup to the L&C tool page
2. We'll remove the non-relevant copy related to DEA benefits from the area about benefits for children and spouses with disabilities. Will link to the two types of programs that we mention in the copy remaining.
3. We'll remove language about, and links to, "check our interactive map" for regional claims timelines, and to the separate maps page.
4. For Yellow Ribbon schools, we'll add a link to the GI Bill Comparison Tool at the top of the page with all the states listed. And as we discussed, we will continue linking to the Team Site pages for the individual sites because of all the detailed updates that Tammy is already making to those pages. It definitely makes sense to keep the links to those pages which will have the latest info. 

We should also touch base in the spring as Tammy is updating those state pages, so that we can make sure we have all the current state link URLs. 

@jenniferlee-dsva @Karak888 @RLHecht  - I'll  do these updates, and then we need to generate preview link to share with the SMEs. 
 
NOTE - some of the state pages - including Alabama: https://www.benefits.va.gov/gibill/yellow_ribbon/2018/states/al.asp are still linking to the 2018-2019 info. According to Tammy all we need to do to fix this is to change 2018 in the URL to 2019 as she says all the current ones are live. 
I will create a list ^ of the URLs that need to be updated and include on this ticket.

**Comment by FranECross** [comment]
All tickets in this epic have been completed.  Closing.
