### ISSUE TITLE
Remove imports dependent on the edu-benefits app

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va.gov-team#30303]
## Details
The edu-benefits app currently has forms system code that imports from it. We want to remove that imports so that the edu-benefits app can be built in a single app build without needing to run platform tests.

The files that import from `edu-benefits` are listed in the [cross app import audit](https://docs.google.com/spreadsheets/d/1K2QtE9qQXS1uFnlKXzAIsGr9Grin5k5RzLsSreQosCU/edit#gid=0) as a note in the `Dependents` column.

## To Do 

- [ ] Remove external `edu-benefits` imports.
- [ ] Verify that the edu-benefits app can be built in a single app build. See the `Testing single app builds in GHA` section in [this comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/29742#issuecomment-917303902) for instructions

**Comment by alexandec** [comment]
Details and plan for these imports:
- [src/applications/personalization/dashboard/helpers.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/personalization/dashboard/helpers.jsx) imports manifests from a variety of apps inside edu-benefits for use in a dashboard. Probably not a good candidate for refactoring.
- [src/applications/static-pages/static-pages-entry.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/static-pages-entry.js#L44) imports two components from edu-benefits. We have a separate effort to evaluate the static pages app and address these types of issues.
- [src/applications/static-pages/tests/wizard/edu-benefits.unit.spec.jsx](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/tests/wizard/edu-benefits.unit.spec.jsx#L9) imports multiple components from `applications/edu-benefits/wizard/pages` in order to run unit tests on them. Should be able to just move this file into the edu-benefits app so it's located near the components it tests.
- [src/platform/forms/definitions/nonMilitaryJobs.js](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/forms/definitions/nonMilitaryJobs.js#L1): Imports a component from edu-benefits. However, the imported component isn't used in edu-benefits, so we can move the component into `platform/forms/definitions`.
