### ISSUE TITLE
[Design] Revise PoA Document messaging to improve upload percentage on the 10-10CG

### ISSUE THREAD

**Issue by tchrisdyer** [department-of-veterans-affairs/va.gov-team#30333]
## User Story

As a Caregiver that represents a Veteran, I need to know what documents I should and should not upload, in order to prove that I have the legal right to represent the Veteran.

As of August 2021, only about 30% of Power of Attorney (PoA) documents uploaded via the online 10-10CG are valid and complete PoA documents. Most are either incorrect documents or partial documents. We recently added messaging via an expandable section to specify the correct document types, but it hasn't had much of an impact.

The purpose of this ticket is to find a better way to message the valid types of documents in order to improve the percentage of uploads that are correct.

## Expected Behavior

- The UX clearly explains the appropriate document types to upload

## Acceptance Criteria

- [x] New design/content flow options for Now vs. Future

**Comment by MickinSahni** [comment]
10/1 Standup: Larger/more wholistic approach is prob necessary. And that approach may touch on backlog items e.g. sec caregiver, mail/physical address.

**Comment by MickinSahni** [comment]
10/4 Standup: New ticket needed to refine PoA approach recommendations in Sprint 58

**Comment by Dene-human** [comment]
The CG program team has expressed that the wrong documents uploaded are causing a problem in the field offices and for Veterans/CGs who have to fill out an new application as a result. 
- They set the goal of receiving 75% accepted legal rep documents. 

- They have confirmed that we can remove the selection for "Do you have a legal representative document you’d like to share with us?"  Is  “Yes. But I’ll provide my document later.”

**Hypothesis**
- Messaging on approved/not approved is hidden in accordion
- Users don't see the connection that this documentation is so that they can sign on behalf of the Veteran

I have created two flows
- [Revised document upload flow](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/wLpODZq) - this just impacts the representative document section (likely quicker to implement) 
- New ["progressive" flow](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8/a/qerZvg2) - this impacts the entire form and makes it progressive based on applicant's selections (likely to take longer to implement)

Design and planning in this ticket #30855
