### ISSUE TITLE
VFS IA Support: School Resources Migration 

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3041]
As a UX designer on the SCO migration process, I need IA Support so I can ensure navigation, labels and re-routing URLs are effective, optmized, and aligned with VA Style. 

### Product Outline
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/office-administration/vba/sco-migration/design/content/SCO-migration-content-v0.1.md

### Planned Launch
Nov. 22, 2019

### Prototype
inVision Prototype https://bahdigital.invisionapp.com/share/VMIAC05S2DC

**Comment by amyknox** [comment]
Labels update... Ideally we'd also like to tag this with "bah-sco-migration."  If you could create that label and tag this issue with it, that'd be great.

**Comment by mnorthuis** [comment]
Recap of our conversation today (11/5/2019)

Since this is tier 2 content and is being done prior to a designed approach to tier 2 content is complete, the recomendations below are based on current va.gov standards and potential approach to tier 2 content in relation to tier 1 content. 

**Structure & Proposed URL: www.va.gov/school-administrators**
- This content will not live with the Education hub content - it is not Veteran-facing benefit content.  It will live separately as a "persona" or "audience"  hub
- The goal is to create a generalized URL for this audience, or, persona. 
- The content already includes some content that is not specific to the title of "School Certifying Officials", and this direction allows the content to continue to expand to any content related to a broader administrators audience. This also avoids using proper nouns, or position titles/labels that may evolve over time. 
- The H1 does not need to match this exactly and can incorporate specific terms, i.e. "VA Resources for School Administrators and SCOs"

**Navigation/Primary Entry Points**
- From the legacy Education & Training site - the BAH team will work with appropriate Team Site contacts to change the left nav to reduce it to one option labeled "School Administrators & SCOs".  Consider dropping the "For" in front of the navigation label.  The option "For Students" will likely change over time as well, or change be changed with this to drop the "For". 
- From the Education Hub (www.va.gov/education) - the current link in the right rail of the hub page will remain.  The label can be updated to "School Administrators & SCOs" for consistency. 


**Redirects**
- BAH will document legacy pages that need to be retired/redirected and indicate where they should redirect to - looks like 3 pages to be redirected to this new URL - and assign issue to Mikki.  Mikki/VSP will work on process for implementing redirects. 
- BAH can work with stakeholders to help communicate the movement of this content to the new URL so that other content owners start to link to the correct page. 


**Additional Recommendations**
- Tier 2 content will be part of the VA.gov platform and will include the full header/footer, it is recommended these designs are updated to utilizing the full va.gov header/footer as well.  If the plan is to treat this content as a separate entity from va.gov, then the minimal header/footer can be used, but content should live on a subdomain of va.gov (i.e. schools.va.gov).

**Comment by amyknox** [comment]
Issue for Redirects: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3145
