### ISSUE TITLE
[FE] Notification Prefs: Make a11y updates to notification settings radio buttons

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#30512]
## Background
Per feedback from Angela during a11y office hours  we have some adjustments to  make to our radio buttons on the notification preferences feature.

## Tasks
- [x] Replace `legend` with `h3` for easier navigation
- [x] Make the radio button "supporting text" a polite alert

**Comment by ajakabcin** [comment]
Linked PR https://github.com/department-of-veterans-affairs/vets-website/pull/18867

**Comment by erikphansen** [comment]
@AngelaFowler82 I made the two changes you suggested earlier this morning:

1. The radio button legends are now h3 elements
2. The supporting text that lives alongside the radio buttons now have a role of alert and aria-live polite.

To test I'd suggesting signing in with user 2 and then going to the Notification Settings section of the Profile. That user has not explicitly opted into or out of the one notification they have access to, so that will give you the full UX from start to finish. Let me know if you have any questions!

**Comment by ajakabcin** [comment]
HI @AngelaFowler82 can you check out the changes Erik made for validation when you have a moment? Thank you!

**Comment by AngelaFowler82** [comment]
This looks good. Closing at this time.
