### ISSUE TITLE
Analytics KPI dashboard request for [Debt Resolution Team]

### ISSUE THREAD

**Issue by LindaLi123** [department-of-veterans-affairs/va.gov-team#30551]
# Request an Edge Case KPI Dashboard

## What this form is for

Use this template to request a KPI dashboard on Domo for your product. This template is for products that fall outside of our standardized dashboards.

If you have another VA.gov product, please reach out to the Platform Analytics & Insights team on #vfs-platform-support.

### Expected delivery timelines

Please note that these dashboards will require additional data and design discovery, and will take additional time to deliver. 

## Instructions for the VFS team

- [ ] **Please fill out [this template](https://docs.google.com/spreadsheets/d/1TSynjEUrOrm_HfLxb2NAPDXxnn7wyy1bSEb2RruC67Q/edit#gid=0) and link it below to help define your product/feature's information.** _(Please request the Excel sheet from the Platform Analytics & Insights team if you do not have Google access.)_ The Analytics team will ***not*** be able to pull this ticket into the queue until this is provided and linked.
  - [ ] If a part of your product involves any sort of linear process/funnel for which you want to be able to measure conversions, please include it in the "Forms" tab of the template.
  - [ ] All other pages associated with your product for which you'd want to track visits and engagement should be added to the "Content" tab.
- [ ] **Add links** to product outlines, feature information, or any other resources you think would help us better understand your product and OKRs to the "VFS-provided information" section below.
- [x] **Add your team label** to this ticket to follow progress.
- [x] If you do not have **Domo access**, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

## VFS-provided information

Add links to product outlines, feature information, or any other resources you think would help us better understand your product and OKRs below. Feel free to also type background information into this section directly. The more context you're able to provide, the fewer questions we'll need to ask you before getting started!

#### Product resources
- 
- 
- 

#### Other product info
_(Add here as needed.)_

**Additional Resources from the Platform Analytics team**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards.
- For additional info, read through the [How to Request a KPI Dashboard Documentation](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).

*Please leave the following blank*

------

## VSP Analytics & Insights Acceptance Criteria

1. Discovery & Design

- [ ] Determine appropriate product questions
- [ ] Determine appropriate metrics & charts
- [ ] Design dashboard layout

2. Build (See [internal process document](https://vfs.atlassian.net/wiki/spaces/AT/pages/1464598569/New+KPI+Dashboard+Request+Process) & [how to](https://vfs.atlassian.net/wiki/spaces/AT/pages/1538294010/WIP%2B-%2BHow%2Bto%2Bcreate%2Bstandardized%2Bdashboards%2Bin%2BDomo))

- [ ] Add the `VSP Analytics & Insights` Group as the dashboard owner
- [ ] Structure funnel data for ETL
- [ ] Pipe available metrics to Domo
- [ ] Document any blocked/unavailable metrics in the Analytics team space
- [ ] Update the dashboard header, including Google Analytics links
- [ ] If any, add [implementation issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+collaboration-cycle%2C+collab-cycle-review%2C+gtm&template=analytics-implementation-and-qa-request-template.md&title=Analytics+Implementation+or+QA+Support+for+[Team+Name+-+Feature+Name]) for additional necessary implementation

3. Q&A

- [ ] Please see & complete the [checklist for full KPI dashboarding QA checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsp/teams/insights-analytics/analytics-tools/domo-dashboard-qa-checklist.md)

4. Share

- [ ] Add VFS group & default group to the dashboard

*For new VFS customers only:*

- [ ] Schedule onboarding meeting

- [ ] Host the meeting to explain how the dashboard works

## Definition of Done

Acceptance Criteria has been completed

- [ ] KPI Dashboard full QA checklist completed
- [ ] Dashboard has been shared back with the VFS team

**Comment by LindaLi123** [comment]
@denisecoveyduc  Hello Denise, would you please fill the template for Joanne?

**Comment by chloedotbrown** [comment]
Hi @denisecoveyduc - thanks for filling out the template and sorry for the delay in getting back! 

We actually hadn't realized when Linda submitted this ticket that MCP was the same product as the Debt Portal, which means we'll need a bit more info to get going. Your team is one of the few that has some products eligible for our standardized dashboards and some like this one, which don't easily fit into any of those [3 main categories](https://va-gov.domo.com/page/1550814739). If filling out this template was a bit confusing, that is why! 

**I've edited the ticket above☝️so that it's now a request for an edge case dashboard, instead of a standardized one.** This will give you more detailed instructions for filling out the spreadsheet and ask for some additional info about MCP. For example, you should now see a new `VFS-provided Information` section, where you can link product outlines and other resources. Adding these will help our team understand what success looks like for this product and determine the best metrics and charts for your needs. 

Once you're able to add those in, just comment on the ticket so our team will get an update. We'll then use that information to figure out when to pull this in from our backlog. Heads up that because these dashboards require custom data and design discovery, they will take longer to deliver than our standardized KPI dashboards. In the meantime, please feel free to reach out if you have any questions about the process, dashboards, or anything else!

**Comment by michelle-dooley** [comment]
Hi @denisecoveyduc.  Wanted to reach back out on this one.  Would love to complete this for you.  If you would still like us to proceed could you please complete the docs as directed by @chloedotbrown above.  If you would like to meet to discuss we can do that as well, just let me know how you would like to proceed.  Thanks!!
