### ISSUE TITLE
Synthetic Monitors: Identify Dashboard Tool

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#30763]
# Description
Let's understand which dashboard tool we should use. It's our current understanding that DataDog is already setup to ingest data from AWS services, so that makes it a good candidate. On the other hand, all other dashboards that the Testing Tools Team owns are hosted on DOMO.  Additionally, DOMO maintains an AWS connector in order to easily collect and use data from AWS.

## Prospective dashboard tools
* DOMO
* DataDog

## Acceptance Criteria
- [x] Dashboard tools have been compared to each other for attributes like ease of implementation, visualization fit for the dataset, and maintainability
- [x] The dashboard tool has been selected
- [x] The reasoning for selecting the dashboard tool has been recorded in this ticket

**Comment by JoeTice** [comment]
Info from a conversation with Mike CHelen that relates to this task...  Covnersation from 9/29/21 - I've condense the convo to what details are relevant to this topic...

Joe Tice  4:12 PM
Hi Mike - wanted to circle back with you to provide more detail related to some of your questions...

Related to the Synthetic Monitor Dashboards, this ticket contains both: metrics that we intend to track, and thoughts related to a discussion on BigQuery/Domo vs DataDog - https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/28852
And this Research ticket contains some documents/articles related to the Cypress spec change we were talking about: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/30434

Hope that is helpful! Let us know if you'd like to discuss any of that further... 

Mike Chelen (he/him)  4:48 PM
ah cool, ty for circling back!
regarding 28852 i might suggest targeting DD for data source rather than AWS
ingesting data into Domo would be really cool, i'm guessing creating dashboard in DD would be lower effort though (edited) 

Joe Tice  4:53 PM
Yes that certainly could be the case… I think the big decision point for us is around consistency, we have a number of our tools and metrics already being recorded in big quarry and displayed in Domo… So we’re concerned that we’d end up with a depress toon that we don’t want

Mike Chelen (he/him)  4:56 PM
yup that makes sense, so if you want to pull synth monitoring data into Domo, it might be good to pull that from DD rather than AWS

Joe Tice  5:10 PM
Ok cool, I'll mention it to the team and put that note in the ticket

Mike Chelen (he/him)  5:33 PM
ok cool, i hope that helps! lmk if there is any other info that would be useful

**Comment by JoeTice** [comment]
This work has been deprioritized by Rachael, based on our recommendation that further development into this was not worth the effort at the current time.

**Comment by pjhill** [comment]
OBE
