### ISSUE TITLE
[Design 2 Research Handoff] HRT Design Prototype in UX Pin (Landing page/Intro page/Form)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#30910]
## Issue Description
_ORDMI PIFs have never actually produced any design mockups for the harassment tool. They took conversations with business owners, synthesized requirements from these, then directly put them into code using the https://VA.gov CMS, strictly to save time. They will share screenshots the prototype and the business requirements assembled.  We'll need to take these screenshots and requirements and produce envision mockups that are compliant to VSA/VA.gov design systems.  The designs will be used for both design intent review and initial FE build of the prototype_

[Standing Draft [UX Pin prototype](https://preview.uxpin.com/2421e73be8eba75acea37ad3fbdd09bfc147940f#/pages/141512978?mode=chidm) 

[Link to Design Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/26765) 
## Design tasks
- Create a prototype in UX pin for user research testing (Intro page/Form)
- Test prototype to ensure functionality is working as intended
- Validate with @cindymerrill ISO research efforts 
- Update/Finalize as needed 

## Acceptance Criteria
- [x] Designer comments on this issue to approve prototype for review
- [x] Designer posts link to Prototype for review by PIF/PM/PO
- [x] Researcher reviews prototype ISO research plan
- [x] Feedback is documented on ticket for follow up and review

**Comment by cindymerrill** [comment]
@brianalloyd When is the mid point review going to happen? Before user research starts (Oct 25)? If so, it would be great to do it before the pilot test (Oct 21).

**Comment by cindymerrill** [comment]
Waiting for @callen2563 to get back to the prototype when she has time

**Comment by callen2563** [comment]
@cindymerrill @brianalloyd 
_1. When I click the Back button, I am taken to the unfilled out version of the previous screen, rather than the one in which I already selected a radio button/date/etc. Is it possible to see what I selected/typed, or is that not possible in UXPin? (It's probably OK if it's not possible or a ton of work to do.)_

I'm not sure how to do this I would need @sporeboy to look at this. Another thought is I'm wondering if we can leave out complex functions like this for prototypes in general unless we have dedicated help from @sporeboy planned upfront. 

_2. Is it possible to do field validation so you can't click the Continue button unless you've selected one of the radio buttons or typed some text in a field? I think that would be more realistic, wouldn't it?_

For this tool they way it was designed is that questions are not required for the user because we want them to only fill out the sections they are comfortable with and they are allowed to skip questions if they want. I don't think we should add this function since it's not how it would actually work if that makes sense but let me know your thoughts.

**Comment by cindymerrill** [comment]
@callen2563 @brianalloyd 

> 1. When I click the Back button, I am taken to the unfilled out version of the previous screen, rather than the one in which I already selected a radio button/date/etc. Is it possible to see what I selected/typed, or is that not possible in UXPin? (It's probably OK if it's not possible or a ton of work to do.)
> 
> I'm not sure how to do this I would need @sporeboy to look at this. Another thought is I'm wondering if we can leave out complex functions like this for prototypes in general unless we have dedicated help from @sporeboy planned upfront.

**Since this prototype is all about filling out the form, I think it's important that information entered before be seen when you navigate back to the previous screens. I agree that @sporeboy has the technical know-how to make this happen (and tell us how complex this is to do).**

> 2. Is it possible to do field validation so you can't click the Continue button unless you've selected one of the radio buttons or typed some text in a field? I think that would be more realistic, wouldn't it?
> 
> For this tool the way it was designed is that questions are not required for the user because we want them to only fill out the sections they are comfortable with and they are allowed to skip questions if they want. I don't think we should add this function since it's not how it would actually work but let me know your thoughts.

**I think I'm OK with skipping this type of field validation so that users can skip screens whenever they want. However, there are exceptions to this when it affects the flow of screens, as I noted in my comment below:**

> @callen2563 In addition, we might want to consider adding conditions to require a certain radio button selection before showing the next screen (e.g., you have to say that someone else saw what happened before showing the screen asking about that person) wherever needed for the user flow. @sporeboy

**Comment by callen2563** [comment]
@cindymerrill  _In addition, we might want to consider adding conditions to require a certain radio button selection before showing the next screen (e.g., you have to say that someone else saw what happened before showing the screen asking about that person) wherever needed for the user flow._ 
 
Yes, creating conditions in the flow when we get to the dev build would makes sense but I don't think we need to spend the time adding conditions in UXPin prototype since the conversation guide has the user selecting that there was a witness. Does that makes sense? @sporeboy @sshein let me know your thoughts.

**Comment by sshein** [comment]
I agree that we should try to keep the prototype as simple as possible, **as long as we are still able to answer our key research questions**. Overall we don't want folks to be spending a lot of time creating complex prototypes. I don't think we need to test things like field validation if that isn't one of our key research questions. I'd be happy to jump in a call to look at the key research questions and help decide what's necessary in the prototype if that would be helpful.

**Comment by callen2563** [comment]
@sshein @cindymerrill I think a call to look at key research questions to help decide what's necessary in the prototype would be a big help thank you!

**Comment by brianalloyd** [comment]
Team, as discussed in sprint planning today, closing out this ticket based on the work completed.  Plan to open a separate ticket that addresses prototype interactions as discussed.  Please let me know what questions remain.

**Comment by cindymerrill** [comment]
I think we need to talk about all of the outstanding issues that I've identified in the comments above in relation to the research goals. This ticket should be preserved for that work. @brianalloyd

**Comment by cindymerrill** [comment]
And when we resume this work, we can revisit the research goals and research questions alongside the capabilities of the prototype.

**Comment by brianalloyd** [comment]
@cindymerrill concur, I'm connecting this ticket to the new ticket that addresses the prototype interactions in order to preserve the conversation and pertinent details. Appreciate it.
