### ISSUE TITLE
Create QA Process document for review/approval

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#3114]
## User Story

As a VSA Engineering team-member, I want to easily learn about how to engage QA-resources to ensure test-readiness when a product/feature is deployed to Staging.

A formal QA Process document would help facilitate understanding of basic QA rules of engagement.

# Problem

Currently, the process of requesting QA testing is “ad-hoc,” relying on VSA Engineering teams to proactively reach-out to VSA DevOps’ QA-resources.

Historically, QA-requests are often made with little time to ensure/document test-readiness on Staging.

## Goals
- Formalize the QA Process for VSA Engineering teams, so as to ensure proper documentation of test-readiness is completed **before** testing gets scheduled.

## Objectives or Key Results this is meant to further
- Formalize QA Process, and develop toward maturity as VSA-QA staffing gets built-up;
- Facilitate Engineering-QA collaboration with standardized processes.

## Acceptance Criteria
- [ ] QA Process Document published into va.gov-team documentation repo.

**Comment by tlei123** [comment]
Since VSP (VFS Platform team) owns the standard QA-practice documentation on va.gov-team, I asked @peterhill-oddball (VSP Product Support’s Sr. QA Specialist) what he has in-place/in-progress re. QA process docs there.

He & I will chat further about them tomorrow (Wednesday); he & other OddBall colleagues are currently in their company-retreat.

**Comment by peterhill-oddball** [comment]
@tlei123 , per our discussion I encourage you to develop your **internal** quality assurance process as a superset of the **platform's** quality assurance process.  In that way, you ensure that your QA activities will be sufficient to satisfy the platform's minimum standards for QA.  Obviously, any specific deliverables that your team needs to generate in order to fulfill aspects of your statement of work should be accommodated by your internal process as well.

The essentials of an excellent quality assurance process include the following artifacts and their logical links --

1. User stories linked to
1. Test plan linked to
1. Test cases linked to 
1. Test execution logs linked to
1. Test incidents / issues

In this way, the final artifact -- **the test report** -- which will include information from all of the above can be quickly generated and provides a traceable, comprehensive, and coherent summary of the QA activities performed in support of the product's sprint / release.

**Comment by tlei123** [comment]
PR merged.
