### ISSUE TITLE
Help with migration of Back to top web component

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#31200]
Help with migration of Back to top web component

- [ ] Work with public websites or front end tools teams to migrate to the new back to top component
- ~~[ ] Remove 'stuff' from formation related to back to top.~~

**Comment by bkjohnson** [comment]
I'm going to look into the CSS specificity issue and try to figure out why being more specific with `<va-back-to-top>`'s `:host` selector doesn't seem to be working. If that doesn't reveal _how_ to get the specificity to work, then I'm going to do one of the following:

- Continue forward with https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/707
- Refactor `<va-back-to-top>` so that it has an extra internal wrapping div which receives the margin styling. `uswds` shouldn't be able to impact this internal styling like it's doing with the styling on the host element itself.

**Comment by bkjohnson** [comment]
Once the migration is completed, we should be able to remove the following files from `formation`:

- [`back-to-top.js`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/39eafcbbc698faae521cf3d6078ea84ab495130e/packages/formation/js/back-to-top.js#L6)
- [`_m-back-to-top.scss`](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/39eafcbbc698faae521cf3d6078ea84ab495130e/packages/formation/sass/modules/_m-back-to-top.scss#L4)

As well as remove related imports like this:

https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/39eafcbbc698faae521cf3d6078ea84ab495130e/packages/formation/js/index.js#L4

**Comment by bkjohnson** [comment]
I'll create another ticket for the work around removing "Back to top" JS & CSS from `formation`.
