### ISSUE TITLE
Content and style review for search and appoint rep from eBenefits team

### ISSUE THREAD

**Issue by candy-gcio** [department-of-veterans-affairs/va.gov-team#31230]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
The search and appoint rep feature will have flows for both unauthenticated and authenticated users. Veterans, SM, or dependents can search for a rep, then choose a rep to generate a pre-filled or fillable PDFs. The ideal path would be for a veteran to search for a rep and contact them directly. Most representatives facilitate filling out the form and submitting it to VA so the client will not need to generate and return the PDF themselves. 

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows: https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/dlG4Y22
- Link to prototype or mockups: https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/PGJ3ZlP
- Link to any epics/issues that may be helpful: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3672

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: 
-	Product manager: 
-	Designer: 
-	FE engineer: 
-	Product/team Slack channel:

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by candy-gcio** [comment]
Hi, @bethpottsVADEPO, here is the transition screen we talked about earlier:
- [search-to-appoint transition](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/09O8Gr2)
The confirmation screen is also new:
- [confirmation screen](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/a/1KmzW4p).

I think I got all of the other updates incorporated. You can arrow left/right through the updated workflow from either of those screens, or go to the [v2 folder view](https://www.sketch.com/s/6fcfb0c5-8c2d-4231-8b1b-c423e75bf5e2/p/47673127-1304-4E6D-8CBE-C8A160E00A55) to see all of the screens.

**Comment by bethpottsVADEPO** [comment]
@candy-gcio It doesn't look like my edits were all made. I wanted to confirm that you saw all 3 previous comments that I made in this ticket. There are still some edits to incorporate.

I'm continuing to go through the screens. Here are some more edits:

Screen 27:
- Change the question to avoid sighted language: Where would you like to search for an accredited representative?

Screen 28:
- Change the question to: Do you already have the name of an accredited representative you want to find?
- Add this text: If you know who you're searching for, enter their name here.
- Change "This is not required." to "This isn't required."

Screen 29:
- Change the question to: Do you already have the name of a Veterans Service Organization you want to find?
- Add this text: If you know the organization you're searching for, enter that name here.
- Change "This is not required." to "This isn't required."

Screen 30:
- Change the question to this: Select an accredited representative
- Add an info alert with this header: **Make sure the representative you want to select is available**
- Text for the info alert: Before you select a representative listed here, make sure you've contacted them and they're available.

Screen 31: _I think the alert should be an info alert rather than a warning._ 
- I'd recommend this header for the alert: **Continue filling out this form**
- Please change the alert text to this: You're not quite finished. You'll need to give us some more information to complete this form. 
- Delete the text that currently appears beneath the alert box.

Screen 32: 
- Minor edits to the text: Change "Here is" to "Here's" and change "on this request only" to "on this application only." Also, the second sentence in the "Note" needs a period at the end.

Screen 33:
- Capitalize "Social Security"
- Change the last field label to remove the "s" from "insurance numbers," add a comma, and add the word "the" like this: Your insurance number, including the letters in front

Screen 34:
- Lowercase "Address" in the header, like this: Mailing address
- Lowercase "Code" for the last field label: Postal code
- Update the text under "What if my information is wrong?" to match the previous screen.

Screen 35:
- Update the text under "What if my information is wrong?" again.

Screen 36:
- Add a period at the end of that one sentence that's standing alone.
- For the second check box, change "alcohol abuse" to "alcohol use problems"
- For the third check box, fix the spelling (there's an errant "i" in there) and lowercase the second and third words, like this: Human immunodeficiency virus

Screen 37:
- Match the text in the additional info component with the previous screen--the text is all there, but the bullet points themselves are missing.

Screen 38:
- I think the text just beneath all the accordions may be misplaced and doesn't belong on this page? I'm not sure. Either that or a "Download PDF" button or link is missing.
- In the "Note" please fix the spelling of "imprisonment."

Screen 39:
- Change the header in the alert box to: Download your completed form 
- Change the text in the box to: Download then print your form so that both you and your representative can sign it. 
- Change the button label to: Download your form
- Delete "selected" from the first question, like this: **When can my representative begin helping me?**
- Replace the text under the question to this: Your representative can begin helping you only after we've received and processed your signed form. At that point, we've officially appointed your representative. 
- Delete the second Q&A because we'll be retiring that page upon the launch of this tool.

**Comment by bethpottsVADEPO** [comment]
@peggygannon for awareness--I have multiple comments in here as I needed to break up my reviews due to time constraints. Let me know if there's anything you'd like to talk through once this product reaches you for review.

**Comment by candy-gcio** [comment]
Notes from Beth/Candy sync:

1. I think all of the previous edits (screens 1-22) were incorporated, but they were made to the related screens in the version 2 wireframes (screens 23-39).
2. On screen 31, we decided to leave this as a warning with the new language, pending midpoint review feedback and usability testing results.
3. On screens 34-35 (also applicable to screens 32-33), @bethpottsVADEPO is going to investigate how we update personal information. Once we have an answer, I will update the text.

The other edits have been made (adding the info alert to screen 30 should be done by the EOD today).

cc: @peggygannon

**Comment by mnorthuis** [comment]
Connecting the IA design to your content ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/23490
