### ISSUE TITLE
[01/07/22] Use Case 3 Training 

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#31297]
- [x] Meet with Justin to get UC3 walkthrough
- [ ] Build powerpoint skeleton
- [ ] Incorporate User Guide step-by-step instruction
- [ ] Review training with @jwowk 
- [ ] Review training with VT Leadership
- [ ] Present

**Comment by BensonWD** [comment]
Draft due to Paras for review 14 October.

Stated requirements so far:
so for both Pharmacy and CC UC3, the VA staff will most likely be new to the VEText portal.  so both trainings should cover the following topics:
--how to log into VEText portal
-- high-level overview of the VEText portal (tabs, reports, etc.)
-- review specific reports for the use case
--Q&A
there is no configuration from their end, so it should be very high-level (edited)

**Comment by BensonWD** [comment]
CCUC3 Powerpoint briefing slides are ready, but need a date for delivery. As mentioned previously, desired attendee list is needed to ensure presentation goes well. I need a SME or access to robust "sandbox" data and time to train on it for this to work out well for attendees. **Determination needs to be made if this will be held via the VEText Teams channel or via ad hoc chat.**

**Comment by BensonWD** [comment]
Clarification of sandbox (DevEnv) data: populated in a way that a demonstration could show a Veteran scheduled for an appointment with outside provider, prior to showing templates.

**Comment by BensonWD** [comment]
Current UC3 draft.[https://app.zenhub.com/files/133843125/f63e7c30-eab9-442c-9a26-2d3ed1b8961c/download](https://app.zenhub.com/files/133843125/f63e7c30-eab9-442c-9a26-2d3ed1b8961c/download)

**Comment by lindsay-insco** [comment]
Material completed and approved by Shane - Next step = scheduling
