### ISSUE TITLE
FE | User flows and navigating | Mobile Phone Extension | Your content does not support a necessary user flow or user scenario.  (03.10.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#31447]
#### VFS team name
Authenticated Experience

#### VFS product name
Notification Preferences

#### Point of Contact/Reviewers
Mikki Northuis (IA)

---

### Platform Issue
Your content does not support a necessary user flow or user scenario. 

### Issue Details
The mobile phone number fields on personal contact information allow the user to enter an extension, however, that extension doesn't carry over to the display on the  notification preferences page. 

### VA.gov Experience Standard
[Category Number 03, Issue Number 10](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References

---

### Platform Recommendation
Display the extension along with the phone number on the  notification preferences page. 

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] VFS team closes the ticket when the issue has been resolved

## Profile work to close this ticket
- [x] #89234
- [x] #89233

**Comment by SKasimow** [comment]
@Samara-Strauss - I'm going to close this out based on AJ's comment above,  but should I open a ticket to hide the mobile extension field on the Contact info page unless that field has an entry?

**Comment by shiragoodman** [comment]
@SKasimow I am opening this back up. We ask that you don't close out any Collab Cycle Staging Review issue tickets until the identified issues has been resolved.

**Comment by Samara-Strauss** [comment]
I don't think it's worth our team adding extensions to mobile numbers in notification preferences since, to the best of my knowledge, people can't legitimately have extensions for mobile numbers. At most, an extension for a mobile number is likely a mistake.

We're in talks with VA profile about removing the extension field for home and mobile numbers. I'm gonna leave this open and hope we can wait things out until the extension field is removed altogether from non-work numbers.

**Comment by SKasimow** [comment]
Thanks @Samara-Strauss!

**Comment by mtcA6** [comment]
@adamwhitlock1 @andaleliz do we need to clean up data that has errantly been input into the extension for mobile phones?

**Comment by adamwhitlock1** [comment]
VA Profile would handle if it is warranted, so I would defer to Samara to make that call as to how to get them to move forward on removing that data so that we could remove that field from our profile section.

**Comment by shiragoodman** [comment]
FYI @ajakabcin see above comment

**Comment by mtcA6** [comment]
@ajakabcin and @shiragoodman working on getting an answer here. BCC'd you on an email chain. I've got this one on my list.

**Comment by shiragoodman** [comment]
FYI @mnorthuis (since you were the original creator of this ticket). I will forward you the email (see @mtcA6 comment) for reference.

**Comment by mnorthuis** [comment]
Update 6/13/23: Per email discussion between VA.gov profile team and VA Profile
- leaving extension on home phone numbers; use case is account holders that may live in a care facility may have an extension for their room in the facility
- no decision yet on whether extension should continue to be collected on mobile numbers
- some discussion around international numbers or improperly entered numbers end up with part of the overall number in the extension field

**Comment by mtcA6** [comment]
Does va-profile support international phone numbers?

**Comment by mnorthuis** [comment]
That is a good question, but they should.  We have Veterans enrolled in the Foreign Medical Program and very likely have international phone numbers and addresses.

**Comment by mtcA6** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/16587996-bd23-4b00-9440-d5322f51b74f)
we don't currently support international phone numbers, at least it wouldn't appear so based on the UI.

**Comment by mnorthuis** [comment]
I agree that the international phone number is a different issue not to be addressed by this ticket.  I'm going to take that back to the MHV work for future discussion with AE.   For the purposes of this issue, its an FYI that the extension field may be populated for a variety of reasons, one of which is potentially someone trying to enter an int'l nbr into a US nbr field and it flows into the extension field.  Or it's been entered into VA Profile in another way.   So whether we continue to collect it is the question here.

**Comment by andaleliz** [comment]
If we can validate that there are actually mobile providers who support extensions, or that there is some other valid use case for mobile numbers to have extensions, we should continue to collect it.

Otherwise, the extension field is misleading and we're capturing data in a way that doesn't align with whatever the person is trying to do.

**Comment by andaleliz** [comment]
@Samara-Strauss, I'm sure a lot of things got buried in your inbox while you were out, and wanted to make sure the update on this ongoing conversation (I think since 2021?!) doesn't get lost in the mix.  Here's summary:

We had some email exchanges regarding the extension field on mobile and home phone numbers, and decided to leave the extension field in place for home phone numbers. The use case for this is folks who live in a facility where there is a main number for the facility, and the extension is direct to their room.

We are TBD on mobile numbers.  Mikki summarized:
>its an FYI that the extension field may be populated for a variety of reasons, one of which is potentially someone trying to enter an int'l nbr into a US nbr field and it flows into the extension field. Or it's been entered into VA Profile in another way. (I was trying to summarize the email chain about this) So whether we continue to collect it is the question here.

What are your thoughts on this? I'm honestly not sure if any cell carriers support extensions or if there is a valid use case to keep this; quick googling tells me no, though there are some articles that suggest _maybe_? I can dig into it further if it's something we think is worth the time.

**Comment by Samara-Strauss** [comment]
@andaleliz thanks for this!

1. Travis mentioned the use case for home number about people who live in facilities, so that's fine with me to leave the extension field there.
2. I'm more skeptical about the mobile number. One question I have is that if someone entered an international phone number and the last few digits ended up in the extension field, is that clear for people trying to call this veteran? Would people know to include the extension field in the phone number? I would imagine this would not be clear, rendering the data kind of useless. Does that make sense?

**Comment by mtcA6** [comment]
I'm w/you @Samara-Strauss it's going to be totally devoid of meaning for an international number. Eg that's what a mock Chilean phone number would look like in any of those fields. If someone were to do that would va notify be able to process the subsequent messages? 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/a3b23058-e876-4613-8aec-ab16342202f7)

**Comment by andaleliz** [comment]
@Samara-Strauss that does make sense, and after imagining the Chilean phone number example Travis gave as a mobile number, I stand by my earlier comment that the extension field is misleading for both the person inputting the data, and someone trying to use it later to reach that person.

I vote to remove the mobile number extension, and inquire about VA Profile supporting international phone numbers (especially since they support international addresses).

**Comment by andaleliz** [comment]
@mtcA6 I can't speak to FE needs, but for our design files, we haven't been creating screens to represent every possible scenario with dynamic data. Given the uncommon nature of mobile extensions, I'd vote for keeping the design files as they are. If you feel strongly though, it would be a 1 point of work to add a state to the notification settings flow showing an extension on the page when a user has a phone number in their file. 

For edit-as-a-subtask, that flow is already set up to be generic to _any_ kind of contact information in the profile, so no updates are needed there. I feel strongly about not creating mock-ups for this flow for every possible scenario it could be used for.

**Comment by mtcA6** [comment]
Editing as a subtask 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/f48366bf-0645-40ee-8196-8d88e4868937)

vs the same thing on the contact info page

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/6bc73d90-ac7b-4368-910c-fcee41f08dab)

seems problematic to accept it in one place and not the other.
