### ISSUE TITLE
OmniChannel link content suggestions from Claims & Appeals

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#31707]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
*Use this space to describe your content need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

An OmniChannel Enterprise chat link is to be added to the Claims status tool within the side bar (no design was provided).

![](https://user-images.githubusercontent.com/20994159/128422090-ed157927-88a7-4bc3-a672-f4235a2766c3.png)

The content within the link that was provided is "Click Here to Chat!" which is not optimal given its use of title case, "click here" and an exclamation point. Additionally, I think it might read better if we combine it into a sentence with the "Submit a question to VA" link.

## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:
    - https://github.com/department-of-veterans-affairs/va.gov-team/issues/28360#issuecomment-893789185

## Will this work be going through the Collaboration Cycle?
- [x] Yes - see issue link above 
- [ ] No

## When does this work need to be done?
- Estimated launch date: mid-November
- Estimated staging review date: ?
- Content and IA work needed by: ? 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: VSA Claims & Appeals
-	OCTO-DE product owner: @mattpointzxer0 
-	Product manager: @vhenry07   
-	Designer: @kevinstachura   
-	FE engineer: @Mottie   
-	Product/team Slack channel: #vsa-claims-appeals

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Adding myself to the ticket, thanks for the tag @Mottie!

Questions I have:
1) Is the intent for this to open in a pop-up window or new browser window/tab? 
2) This is a live chat with an agent or is it an interactive chatbot?  I was under the impression that it was a live agent initially, but not entirely sure.  I want to be careful about the language we use, as we also have an online form to submit a question.

**Comment by Mottie** [comment]
Any updates on the status of this work? I'm off the next two days, and our sprint ends next Tuesday. If getting it done before Tuesday isn't possible, we'll need to push this work to our next sprint. Thank you!

**Comment by bethpottsVADEPO** [comment]
@Mottie I have some questions, so yes, please push to next sprint. 

@LucianaAlexanderMorais Have you discussed messaging with @DanielleThierryUSDSVA yet about how you want to distinguish this service from other ways to contact VA online? It makes sense to place the chatbot link in the Need help? section, where there's already a link to Ask VA with this label: Contact us online through Ask VA. So the label for the chatbot needs to set it apart from this online form submission. 

Robin said that this text (below) was provided, but I'm not sure where it came from and it doesn't align with our VA.gov style and voice: "Click Here to Chat!" Is there any research that may inform the messaging here for the link label? What are we calling the chatbot? Thanks!

**Comment by stephenjames1** [comment]
All,

Can we have a meeting to discuss this ASAP?  I would be happy to set something up when everyone is available and bring in our OIT PM.

Thanks,
Steve James
PM/Scrum Master, Contractor (GDIT)
OIT/Veteran Experience Services/Contact Center
Enterprise Portfolio Management Office (EPMO)
***@***.***
***@***.******@***.***>
410-322-4833 (cell)
www.gdit.com<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gdit.com%2F&data=04%7C01%7C%7C411e779783974b95082708d94555ec3b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637617058125446553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0&sdata=ys34G38F8Y7WVGXax6N6gSGYwhkaiMonamogKGaFtZY%3D&reserved=0>


From: Beth Potts ***@***.***>
Sent: Thursday, November 11, 2021 4:16 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: James, Stephen C. (GDIT) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] OmniChannel link content suggestions from Claims & Appeals (Issue #31707)


@Mottie<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMottie&data=04%7C01%7C%7Ce4be4fe0c5ff40f0fa8e08d9a5586c51%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637722621469306604%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=316OqK7RF%2FaloSfPVTWzKzW%2F9o7uJA4sVVYEYWl0DAU%3D&reserved=0> I have some questions, so yes, please push to next sprint.

@LucianaAlexanderMorais<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLucianaAlexanderMorais&data=04%7C01%7C%7Ce4be4fe0c5ff40f0fa8e08d9a5586c51%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637722621469306604%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=W7jeS8pG44fo1lzMUzW4F%2Be6aXFZE6WuxncSppqx%2FjE%3D&reserved=0> Have you discussed messaging with @DanielleThierryUSDSVA<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDanielleThierryUSDSVA&data=04%7C01%7C%7Ce4be4fe0c5ff40f0fa8e08d9a5586c51%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637722621469316557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c1koBdXtqmMAxRIWqgrJ8NVk0HSBFo9O1I8tuN8TomQ%3D&reserved=0> yet about how you want to distinguish this service from other ways to contact VA online? It makes sense to place the chatbot link in the Need help? section, where there's already a link to Ask VA with this label: Contact us online through Ask VA. So the label for the chatbot needs to set it apart from this online form submission.

Robin said that this text (below) was provided, but I'm not sure where it came from and it doesn't align with our VA.gov style and voice: "Click Here to Chat!" Is there any research that may inform the messaging here for the link label? What are we calling the chatbot? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F31707%23issuecomment-966630570&data=04%7C01%7C%7Ce4be4fe0c5ff40f0fa8e08d9a5586c51%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637722621469316557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p9n5hkQQY1LyP43NNYbjsNizrqZStyWnhhZOqf7cumc%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT35IDG6EFAJMDKP62J2EY3ULQW7XANCNFSM5GJ5N2ZQ&data=04%7C01%7C%7Ce4be4fe0c5ff40f0fa8e08d9a5586c51%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637722621469326515%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=frCUgQyBm48aFed9pB%2FLNwvH0%2BDUpfjn6Kk%2BEYeyVtM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ce4be4fe0c5ff40f0fa8e08d9a5586c51%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637722621469326515%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i%2F7U9nlyuBVoeeJr1LwEwhXxtXQ12cAl%2BwSwCU07lqM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ce4be4fe0c5ff40f0fa8e08d9a5586c51%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637722621469336474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MOSXEuIVMohiq5yBq3F314CInJQjTMxh7VXu7SrH7R4%3D&reserved=0>.

**Comment by Mottie** [comment]
I'm off today, but I would gladly meet about this on Monday.

**Comment by vhenry07** [comment]
Happy to hop on a call on Monday

**Comment by stephenjames1** [comment]
Thanks All.  Who from your team should attend?

Thanks,
Steve James
PM/Scrum Master, Contractor (GDIT)
OIT/Veteran Experience Services/Contact Center
Enterprise Portfolio Management Office (EPMO)
***@***.***
***@***.******@***.***>
410-322-4833 (cell)
www.gdit.com<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gdit.com%2F&data=04%7C01%7C%7C411e779783974b95082708d94555ec3b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637617058125446553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0&sdata=ys34G38F8Y7WVGXax6N6gSGYwhkaiMonamogKGaFtZY%3D&reserved=0>


From: Veronica Henry ***@***.***>
Sent: Friday, November 12, 2021 9:47 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: James, Stephen C. (GDIT) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] OmniChannel link content suggestions from Claims & Appeals (Issue #31707)


Happy to hop on a call on Monday

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F31707%23issuecomment-967171988&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059899454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pbTfCDuctWgKRmVqaWOhNrzne%2B1FZ%2FeeKoWFyLZ1xzE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT35IDHU7USVGF3X5EMPGN3ULUSFFANCNFSM5GJ5N2ZQ&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059909407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DIrpGxlZJtaHoBMCRyLHzsVp47jnEqsQZ%2B7m6%2BNLuH4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059909407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FCL2zzQkz3WdVXzILVVgOSUyr0NIst1eUxHZlN%2B1kJk%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059909407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T53Mf9UMFRtgvUklV38fjM%2BbmvZmbLBXW%2Fj2ZP6gS9A%3D&reserved=0>.

**Comment by vhenry07** [comment]
Robin Garrison, Kevin Stachura, and myself from Claims & Appeals.


[cid:03b3a4a5-1648-4678-b532-3594df145783]

Veronica Henry

Senior Product Manager



Email ***@***.***



Government<http://governmentcio/>CIO<http://governmentcio/>

LinkedIn<https://www.linkedin.com/company/governmentcio/> | Facebook<https://www.facebook.com/GovernmentCIO> | Twitter<https://twitter.com/GovernmentCIO> | YouTube<https://www.youtube.com/channel/UCME29XZCQYpPENNZFyULeYg>





Confidentiality Note: This email may contain confidential and/or private information. If you receive this email in error, please delete and notify sender.

________________________________

**Comment by stephenjames1** [comment]
I've set up 2 meetings, one for Monday and one for today, with no acceptance or attendance by the Claims and Appeals Team.  Ronnie, can you set up the next attempted meeting and we will be sure to attend?

Thanks,
Steve James
PM/Scrum Master, Contractor (GDIT)
OIT/Veteran Experience Services/Contact Center
Enterprise Portfolio Management Office (EPMO)
***@***.***
***@***.******@***.***>
410-322-4833 (cell)
www.gdit.com<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gdit.com%2F&data=04%7C01%7C%7C411e779783974b95082708d94555ec3b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637617058125446553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0&sdata=ys34G38F8Y7WVGXax6N6gSGYwhkaiMonamogKGaFtZY%3D&reserved=0>


From: James, Stephen C. (GDIT)
Sent: Friday, November 12, 2021 9:56 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>; department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] OmniChannel link content suggestions from Claims & Appeals (Issue #31707)

Thanks All.  Who from your team should attend?

Thanks,
Steve James
PM/Scrum Master, Contractor (GDIT)
OIT/Veteran Experience Services/Contact Center
Enterprise Portfolio Management Office (EPMO)
***@***.******@***.***>
***@***.******@***.***>
410-322-4833 (cell)
www.gdit.com<https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.gdit.com%2F&data=04%7C01%7C%7C411e779783974b95082708d94555ec3b%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637617058125446553%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0&sdata=ys34G38F8Y7WVGXax6N6gSGYwhkaiMonamogKGaFtZY%3D&reserved=0>


From: Veronica Henry ***@***.******@***.***>>
Sent: Friday, November 12, 2021 9:47 AM
To: department-of-veterans-affairs/va.gov-team ***@***.******@***.***>>
Cc: James, Stephen C. (GDIT) ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] OmniChannel link content suggestions from Claims & Appeals (Issue #31707)


Happy to hop on a call on Monday

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepartment-of-veterans-affairs%2Fva.gov-team%2Fissues%2F31707%23issuecomment-967171988&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059899454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pbTfCDuctWgKRmVqaWOhNrzne%2B1FZ%2FeeKoWFyLZ1xzE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT35IDHU7USVGF3X5EMPGN3ULUSFFANCNFSM5GJ5N2ZQ&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059909407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DIrpGxlZJtaHoBMCRyLHzsVp47jnEqsQZ%2B7m6%2BNLuH4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059909407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FCL2zzQkz3WdVXzILVVgOSUyr0NIst1eUxHZlN%2B1kJk%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C50b448e14682466a3f9108d9a5eb3f15%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637723252059909407%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T53Mf9UMFRtgvUklV38fjM%2BbmvZmbLBXW%2Fj2ZP6gS9A%3D&reserved=0>.

**Comment by vhenry07** [comment]
Hi Stephen,

Never received any meeting invites.. I wonder what happened.


[cid:9c06bce9-0dee-40c7-9ce1-4790b0ffda6b]

Veronica Henry

Senior Product Manager



Email ***@***.***



Government<http://governmentcio/>CIO<http://governmentcio/>

LinkedIn<https://www.linkedin.com/company/governmentcio/> | Facebook<https://www.facebook.com/GovernmentCIO> | Twitter<https://twitter.com/GovernmentCIO> | YouTube<https://www.youtube.com/channel/UCME29XZCQYpPENNZFyULeYg>





Confidentiality Note: This email may contain confidential and/or private information. If you receive this email in error, please delete and notify sender.

________________________________

**Comment by Mottie** [comment]
Hi @stephenjames1, this is what I wanted to demo for you today, but my computer was super-laggy and I didn't get it working in time.

I don't think the link stands out very well, but @kevinstachura told me that we may be moving that side bar under the content in our next iteration of the claim status tool...

<details><summary>Link on page</summary>


![Screen Shot 2021-11-18 at 1 27 14 PM](https://user-images.githubusercontent.com/136959/142485280-88da1cfd-7dfd-4ca1-8859-d455a1af873b.png)</details>

We don't need to assign the popup window a title since it will get overridden by the document title of the destination page, but the hamburger menu is very subtle in its current state. And the link text has not been finalized.

<details><summary>Link in action</summary>


![omni-channel-popup](https://user-images.githubusercontent.com/136959/142485184-cd285268-2cec-4fc9-9f2b-bedbee9b7dcc.gif)</details>

**Comment by bethpottsVADEPO** [comment]
@Mottie Could we try this for the link label?:

Open a live chat

**Comment by Mottie** [comment]
Sounds good, thanks Beth!
