### ISSUE TITLE
Analytics Feature Request/Bug Report: Updates to the My VA analytics dashboard

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#31951]
# Analytics Feature Request/Bug Report

## Ticket Description

**Who is this request for?**

* Auth experience/the My VA dashboard. 

**Is this a feature request or a bug?**

- [X] Feature request
- [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

These requests are for the [My VA analytics dashboard](https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/).

- Can you make it so we can click through on all reports? This will be super helpful for drilling down into data.

**(Data) What timeframes are you looking to analyze (e.g. before vs. after dd/mm/yy)?**

- Whenever you can. No deadline.

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by bsmartin-ep** [comment]
Dashboard widgets have been linked @Samara-Strauss.

https://analytics.google.com/analytics/web/#/dashboard/XOEdSZeVT9qyxQU5T29PNw/a50123418w177519031p176188361/

Wasn't quite sure what to point "Average API latency (ms)" to since there isn't a standard report that lets you apply custom metrics like this.  I linked to the same Dimension report as the "API latency (ms) distribution" widget.

Let me know if you would prefer a link to a custom report template.

Otherwise, OK to close this one out?

**Comment by Samara-Strauss** [comment]
Thank you! This is great! We are good to close.
