### ISSUE TITLE
Request Design QA - SCO Migration

### ISSUE THREAD

**Issue by amyknox** [department-of-veterans-affairs/va.gov-team#3196]
#### Context
We were tasked with migrating three pages of content from the School Resources pages to a single page, a “one-stop shop” for all the information School Certifying Officials (SCOs) and school administrators need to do their work. The challenge was amplified when senior stakeholders reacted to the length of our first iteration, "This page is still too long!"  The work you'll review is a solution which delights our users and effectively meets our stakeholders expectations.  

This work also is content for a non-Veteran audience so serves as a test case for Tier 2 content migration efforts. 

#### URL
Prototype https://bahdigital.invisionapp.com/share/HKIAC3863ST#/screens
Staging https://staging.va.gov/school-administrators/

#### Design Challenges
_The use of accordions within spokes_
One of the client's goals was to create a new page that felt fairly short and light without seeming cluttered. Incorporating accordions within the page spokes provided a viable solution for organizing and presenting a large amount of content into compact spaces and not extending the page's vertical real estate. 

In addition to helping condense the content, the accordions provide a helpful navigation structure for the resources that live within each spoke. Users can view content by relevant and helpful categories.

_Inclusion of Announcements_
One of the project requirements was a prominent announcements area that would allow for updates and automatically expiring content. Stakeholders wanted this content to be highly visible to visitors to the page, and for the page to always display fresh content.

We used the light blue, featured content component with select modifications to accommodate the nature of the content, essentially a list of headlines with dates. This announcements area was placed below the jump links and the “Key Resources for SCOs” areas in order to maintain the appropriate information hierarchy.

_Key Resources for SCOs_
This section comprises the most valuable resources for School Certifying Officials, which were identified during discovery interviews with SCOs. These are links the SCOs can access quickly as arrive on the page, reducing challenges they may have had finding what they need when they need it. Since the links are small and concise, SCOs can immediately see what is available to them. During usability testing, SCOs expressed how helpful these resources were to them, and they appreciated how prominent they are on the page.

_Resources to support students_
The final section of the School Resources page is dedicated to a collection of Veteran-facing resources SCOs use to support military-connected students.  The styling for this section is based on the Related Links pattern found at the end of many of VA.gov’s hub pages. Despite being the last section on the page, SCOs easily navigated to this content during testing, and they expressed how helpful these links would be to them, in addition to the rest of the content on the page. Since this proved so valuable to SCOs during testing, we included a jump link to it at the top of the page to ensure ease of access.

**Comment by amyknox** [comment]
We'd like to request that DSVA start the design review on the inVision prototype and finish on staging.  Our target launch date for this work is 11/22 and we'd like to do what we can to keep UX work moving forward while dev is underway.  

A 2-part design review would allow UX to address any "early" issues and then save the more granular, pixel-almost-perfect reviews for the last part of the process.  Below you'll find our thoughts on which Design Review Tasks could be reviewed on the prototype and which would need to be on staging.  

We've discussed this approach with our DSVA contacts ( @KevinMHoffmanUSDS  and @mattpointzxer0 ), who felt the approach was workable.  Appreciate your attention and happy to respond to any questions you may have.  

To review in PROTOTYPE:
*  New design patterns have been vetted by DSVA and documented
*  Correct use of design patterns in context
      *  Form chapters in place
      *  Privacy policy is present
      *  Address form follows pattern if applicable
      *  Name form follows pattern if applicable
*  Correct use of typography
*  Padding and spacing has been applied appropriately
*  Form components used correctly in context
*  Consistent use of iconography
*  Primary and secondary CTA buttons used correctly in context

To review on STAGING:
*  Correct use of typography
*  Padding and spacing has been applied appropriately
*  Consistent use of iconography
*  Colors use are consistent with color palette
*  :hover and :focus states have been accounted for and are consistent with design patterns
*  Alert messages have been used appropriately
*  Error states have been accounted for and used appropriately
*  Loading indicators have been used where appropriate

**Comment by amyknox** [comment]
@emilywaggoner - the SCO page is ready for DSVA design review on staging. Please let me know if there's anything I can do to help your team along with this process. Thanks!

**Comment by emilywaggoner** [comment]
Hi @amyknox, here is the feedback from the design review! This contains input from myself, @CrystabelReiter and @1Copenut and includes accessibility-related recommendations, marked with [A11y]. 

# Booz Allen Hamilton: School Administrator Content Page Design Review
- Page: Resources for schools
- Staging link: https://staging.va.gov/school-administrators/

## General
- **New pattern:** The hub template is being used for a content that is not a benefit hub. Risk: The hub template was designed specifically for Veteran an audience of Veterans and family members. It is meant to provide entry points into many pages of information about each benefit hub, rather than be the end destination. The SCO content serves a different purpose, and may merit different structure/presentation.
- All of the links with the > caret at the end seem like they’re linking to external pages, or away from the SCO resource pages. [A11y]

## Under "Key Resources for SCOs":
- New pattern: The horizontal text links separated by pipes
    - Question: Why use this approach instead of an unordered list?
    - Recommendation: Add an underline to the text links so that they do not rely on color alone to communicate interactivity. [WCAG reference.](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html) [A11y]
    - This pattern is not clear -- it feels like tabs, but as far as I can tell is a list of links to other places. There’s a high cognitive load required to separate it from the “On this page” table of contents. I’m with the recommendation above to make this an unordered list, and to make it our visual H2 treatment. [A11y]
    - The “On this page” should not be a heading, maybe a paragraph with utility classes to make it render properly. By not making this a heading and bumping the Key Resources for SCOs to the next visual heading level, we maintain a good H2 > H3 visual and semantic flow. [A11y]

## Latest announcements from VA section
- Question: Is there a minimum amount of events required for this block? (What if there were 1 or 2 only?)
- The headline in the featured content component uses a heading with an underline whereas in the design system, there is no underline. Recommendation: Use the heading with no underline (to remain consistent with the design system)
- Recommendation: Add an underline to the links in the Latest Announcement section so that they do not rely on color alone to communicate interactivity [A11y]
- Recommendation: Make heading an H3. Feels like nested content under the Key Resources for SCOs [A11y]
- Check the color contrast between blue background and blue links. Should be 4.5:1 and should have the same text size and line-height as other callout boxes. [A11y]
Training and guides section
- Accordion content: It's unclear why some of the links are in unordered lists, and some use the style with bold type and the arrows. Recommendation: Use the unordered list style with text links with underlines for better readability.
- Accordions should have proper heading nesting under their H2’s. These accordions look like H3’s. The newest version of [WebAIM’s Wave tool](https://wave.webaim.org/extension/) can show you the shape of these nested headings and structures. VSP A11y practitioners can help also. [A11y]
Resources to support students section
- Add either the right caret icon to these links or an underline to indicate interactivity [A11y]

**Comment by amyknox** [comment]
@emilywaggoner - thanks for the input.  We'll take a look at it and get back with questions / answers for you earlytomorrow.

**Comment by amyknox** [comment]
@emilywaggoner, @CrystabelReiter & @1Copenut - thank you for the input on the SCO page.  Our comments & notes are noted in the attached doc. Please reach out with any questions or concerns. 
[https://app.zenhub.com/files/133843125/69dbaadc-55ce-43a2-8099-5f265ac3c015/download](https://app.zenhub.com/files/133843125/69dbaadc-55ce-43a2-8099-5f265ac3c015/download)

**Comment by mandifrances** [comment]
@emilywaggoner is this still needed? Should this have the Product Support label on it?

**Comment by emilywaggoner** [comment]
I think we can close!
