### ISSUE TITLE
Update VetSuccess on Campus page in the Careers/employment hub

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#3198]
**User story:** As a Veteran, I want accurate information about career counseling in an easy to understand, plain language, user friendly way. 

**ETA: SME will send draft sometime next week.**@AnneHurley - please work with her (Robyn) to make their copy into our voice and style, and once finalized, work with @RLHecht to put into Drupal. 

**Note: This team must be sent preview links and we must get explicit email/documented ok before publishing.**

Background: Voc Rehab SME would like to update several pieces of content on this page, mostly missing information; and remove the manual contacts list which is outdated on our page. This content apparently changes frequently and until we have a better way of keeping this content fresh, we will point to the legacy page (currently SME's have direct TeamSite access to update info; they do not have Drupal access to do this on our page).

1/ In the section “How our counselors can help you as a Veteran or service member”: Add info about career counseling services. **Robyn will provide draft content.** 
 
2/ Above the **VetSuccess for dependents** section, add new section, like "VetSuccess eligibility for Veterans and service members." **Robyn will provide draft content.**
 
3/ Remove VSOC locations and counselors contacts list (currently in a section of accordions) and instead link to: https://www.benefits.va.gov/vocrehab/vsoc.asp 
 
I'm sizing this as a 5 bc of anticipated rounds of stakeholder reviews and changes, but it could be more.

**Comment by jenniferlee-dsva** [comment]
@Karak888 Part of this ticket was completed via special content only deploy day before Thanksgiving. 

![image](https://user-images.githubusercontent.com/43381063/70358986-a436fb00-1848-11ea-9ee5-6cd907714f7b.png)

**Comment by jenniferlee-dsva** [comment]
Uploading attached doc from Robyn and Bettye - this doc contains other changes they asked for but we didn't have time to connect with them on:

[VSOC Webpage Edits-RT-112019.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3934165/VSOC.Webpage.Edits-RT-112019.docx)

@AnneHurley - please be sure to take a look at the other changes in the doc. Per a different message thread - we are not changing "service member" to "Servicemember" and other non-VA.gov style changes. Let me know if you need a call with them, if you have any questions for them. 

RE "VetSuccess" vs "VSOC" -- could you ask Laura Walsh to check via MOZ which term gets more search volume? I see no issue changing VetSuccess to VSOC if VSOC is indeed the more common usage among Veterans, as SME claims.

**Comment by Karak888** [comment]
Hi @jenniferlee-dsva @AnneHurley Just wanted to point @lwalsh617  "VetSuccess" vs "VSOC" -- could you ask Laura Walsh to check via MOZ which term gets more search volume? I see no issue changing VetSuccess to VSOC if VSOC is indeed the more common usage among Veterans, as SME claims.
For tracking purposes is this easier for me to create a subtask ticket for you @lwalsh617 ?

**Comment by Karak888** [comment]
@RLHecht and @AnneHurley  to have a conversation about what happens next, who does what....

**Comment by AnneHurley** [comment]
@lunascoop @jenniferlee-dsva @Karak888  Hoping Selina can pick up these final edits, etc., on this page. We may need a short meeting/call with Jen to go over the issues from SMEs so both Selina and I are aware of them. I can do the dev edit on Selina's doc when it's done.

**Comment by lunascoop** [comment]
Note from Jen via slack (Abbreviated version): This is a very tricky stakeholder group.
Let's see if we can minimize # of POCs and assign Anne or Peggy (if needed me) as the public POC.  (One of the many critical complaints -- but actually valid one, unlike the others -- that they had was that they have experienced way too many changeovers of content people.)

Do not publish w/out their approval.

**Comment by lwalsh617** [comment]
@AnneHurley @lunascoop - From Moz, it looks like VetSuccess is the way to go. CTR is 100% vs 29% with VSOC. Here's a snapshot. 
<img width="373" alt="Screen Shot 2020-01-15 at 1 55 58 PM" src="https://user-images.githubusercontent.com/53535663/72462321-d2402100-379e-11ea-8cb0-38e7b2bcf5fc.png">

**Comment by jenniferlee-dsva** [comment]
@AnneHurley @lunascoop Per ^ SEO research from Laura, we will keep "VetSuccess" terminology. We will share research with them (and if needed can include"VSOC" for them maybe as parenthetical copy, but we will not replace, lead or optimize for VSOC). 

Thank you @lwalsh617 !

**Comment by lunascoop** [comment]
@AnneHurley I included an updated version of the copy here per our conversation earlier.
[VSOC.Webpage.Edits-SC-012020.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4078072/VSOC.Webpage.Edits-SC-012020.docx)

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  @lunascoop  @Karak888  Great job, Selina. I took the liberty of condensing and clarifying things a bit more on this doc. But @jenniferlee-dsva , would like you to take a read through of it first and see if you think it's OK and will be all right with the stakeholders. I have not yet worked with them. Once you read and provide feedback, I will clean up the edits and I can send them the clean version. 

A couple of notes:
I combined who is eligible and their requirements into one section/H2, since it wasn't clear to me that dependents are also eligible till I was pretty far down the page. 
I made the "How can I find out if my campus has a VSOC counselor" its own H2. I know it's big, but it seems to me the big three questions are, what is it, who qualifies and how, and do I have one at my school. The way the previous link was it was sort of getting lost, and not really attached to the H2 above it. I also disagree with Robyn's suggestion to put "how do I find out if my school participates" below under the More Resources section - though I suppose we could add it there a second time. 

Let me know what you think and then I can tidy it up and forward it to the right folks.
[VSOC.Webpage.Edits-SC-ah.docx]
(https://github.com/department-of-veterans-affairs/va.gov-team/files/4078975/VSOC.Webpage.Edits-SC-ah.docx)

**Comment by jenniferlee-dsva** [comment]
Taking a look at doc ^. Not sure why this is labled for content and IA - this is an existing page, so doesn't need IA review.

**Comment by jenniferlee-dsva** [comment]
@AnneHurley @lunascoop - ^ Trying to review but it's realllly hard to comprehend with all the tracking. Could you provide a deck version FOR SMEs - for me to review before SMEs?  I.e., using our previous copydeck styling - screenshot of current page with call outs of the section that's changing, then the new changed text below that - and so on.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  @lunascoop  I actually have set this to the side for other, more pressing projects. And yes, once there is a deck to share with these SMEs for sure it will be on the formal template etc.,. and I'll ask you, Jen, to review before we send. Hope to get back on this shortly.

**Comment by jenniferlee-dsva** [comment]
Thanks @AnneHurley - to clarify: Instead of sending me the raw super rough WIP, I would prefer to see something closer to ready and in the copydeck format. I need to see what SMEs will review, and then I can provide my internal review and comments to you and @lunascoop to incorporate before SME share out.

**Comment by AnneHurley** [comment]
Yes absolutely.



*[image: GovernmentCIO]* <http://www.governmentcio.com/>

*Anne Hurley** |*
  Content writer

| *mobile* (503) 298-7203
| *e.* ahurley@governmentcio.com

*Government**CIO*
*website <https://www.governmentcio.com/> **|** media
<https://governmentciomedia.com/> **|** services
<https://www.governmentcio.com/services> **|** jobs
<https://careers-governmentcio.icims.com/> **|** map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>*

*[image: Twitter]* <https://twitter.com/GovernmentCIO> *[image: Facebook]*
<https://www.facebook.com/GovernmentCIOMedia> *[image: LinkedIn]*
<https://www.linkedin.com/company/governmentcio> *[image: YouTube]*
<https://www.youtube.com/user/GovernmentCIO/videos> *[image: Instagram]*
<https://www.instagram.com/gciotalent>


*Confidentiality Note: This email may contain confidential and/or private
information.If you received this email in error please delete and notify
sender.*





*From:* jenniferlee-dsva <notifications@github.com>
*Sent:* Wednesday, January 29, 2020 9:53 AM
*To:* department-of-veterans-affairs/va.gov-team <
va.gov-team@noreply.github.com>
*Cc:* Anne Hurley <ahurley@governmentcio.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [department-of-veterans-affairs/va.gov-team] Update
VetSuccess on Campus page in the Careers/employment hub (#3198)



Thanks @AnneHurley <https://github.com/AnneHurley> - to clarify: Instead of
sending me the raw super rough WIP, I would prefer to see something closer
to ready and in the copydeck format. I need to see what SMEs will review,
and then I can provide my internal review and comments to you and @lunascoop
<https://github.com/lunascoop> to incorporate before SME share out.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/department-of-veterans-affairs/va.gov-team/issues/3198?email_source=notifications&email_token=ALDJYX6KBNFM4ZBGQRGCL6TRAG7BJA5CNFSM4JJ5TNSKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKIEFWY#issuecomment-579879643>,
or unsubscribe

**Comment by MickinSahni** [comment]
carrying this to sprint 14

**Comment by AnneHurley** [comment]
[VSOC page revise - ah]
(https://app.zenhub.com/files/133843125/f19436d7-995a-4c52-8842-02184e47f92a/download)
@lunascoop  @jenniferlee-dsva  Here is the cleaned up version of the VSOC revise. We incorporated all of Robyn's edits, with a couple of notes:
1. We decided to move the Who is eligible section up, above the Watch these videos section, as the former seems more important to a reader of this page
2. We also put a link Robyn wanted at the bottom, up higher. In this case I am not worried about having duplicate links - I'm happy to keep one at the bottom, but also think the user of the page will want that info higher in the page, to take action if desired. 

Let me know if you have any edits/feedback and thanks.

**Comment by jenniferlee-dsva** [comment]
@AnneHurley (CC @lunascoop ) - I'm uploading review w/ edits and comments here. I'm happy to sync to explain rationale behind changes. 

1. What I'd love to see next is for these changes to be made in Drupal and for the Drupal preview page to be provided as a screen capture with the specific changed areas either highlighted or boxed out in red. 
2. Can provide this as multiple chunked images to better fit as embeds in final copyeck.

[vet-success-updates-020320-jl.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4148879/vet-success-updates-020320-jl.docx)

**Comment by AnneHurley** [comment]
@RLHecht  The edits and new featured content are here: https://prod.cms.va.gov/node/724/latest

Let me know what you think. Once it's finalized I'll capture screen grabs to send to Robyn et al.

**Comment by RLHecht** [comment]
@AnneHurley I read over the page and made a few copy tweaks throughout the page. I also changed VetSuccess on Campus to VSOC after the first instance per the style guide when using acronyms. Though I remember there was discussion about what was better for SEO, so if this is not correct, let me know and I can change them all back. We should be consistent though.

**Comment by MickinSahni** [comment]
2020-02-06 Standup
- awaiting feedback from education team
- if we don't get this feedback by monday-ish, we'll pull out of sprint 14

**Comment by AnneHurley** [comment]
[VetSuccess_updates_for SMES_v1]
(https://app.zenhub.com/files/133843125/56b3fc7e-5984-4aa8-ad7e-ee8166c626b5/download)

@jenniferlee-dsva  I'll send you an email with some explanations of what we've done as well as a draft of this. When you're done, if you'd like me to send it to Robyn, I'm happy to- just let me know.

**Comment by MickinSahni** [comment]
2020-02-07 PW Standup
- Anne waiting for feedback, but not sure if we'll get stakeholder insight before EOSprint on Tuesday
- Check Monday if we'll need to pull out

**Comment by MickinSahni** [comment]
2020-02-10 PW Standup
- Awaiting Jen's feedback
- Pulling out of Sprint 14 and into Ready (no sprint) until we're good to go with stakeholder feedback (we'll use this ticket as a test case in not committing to content work at the beginning of a sprint and instead pull it into whatever sprint we're on when we've gotten all we need)

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  Here's the revised copy deck with recommendations, notes, and the SEO Moz screenshot for you to share with Bettye and Robyn. Note that I've taken out the extraneous bullet in the videos section from that first line, which is the intro to the bullet list. Let me know if you have any questions. 
[VA.gov VetSuccess revisions-v2]
(https://app.zenhub.com/files/133843125/8e432348-5050-46ea-9639-08f7db80cd98/download)

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  Here's the updated copy deck to send to the VetSuccess SMEs. Preview link is: http://preview-prod.vfs.va.gov/preview?nodeId=724

[VA.gov VetSuccess Page Updates v2]
(https://app.zenhub.com/files/133843125/ad116238-fa68-4990-973b-1e74fd80d661/download)

**Comment by jenniferlee-dsva** [comment]
@AnneHurley - A couple of quick things - 

- The preview link included in the copydeck is of the wrong page.
- The screen grabs are not showing quite right - ex: the first one is showing the eligiblity div.feature that was added but it cuts off the blue box completely. 

I am going to re-do the copydeck, as we have gone back and forth already, and I'd like to move this forward to the SME phone call stage.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva if  you haven't redone that deck I will do it. I had some challenges in taking screen grabs as you saw, and I should have just made two completely separate shots of the top area, even if it were small, and then the bottom area which contains the changes. Let me know and I can take care of this right away.

**Comment by AnneHurley** [comment]
@jenniferlee-dsva  Here is the revised/cleaned up copydeck with correct URL and more readable blocks. Let me know what you think. 
[VA,gov VetSuccess edits v2]
(https://app.zenhub.com/files/133843125/2f31a9cc-4736-4433-a54d-6750e7e1a526/download)

**Comment by jenniferlee-dsva** [comment]
Finished it last night @AnneHurley. Will send out meeting invite to SMEs for next Weds regular VBA sync. Please be sure to attend, thank you!

**Comment by MickinSahni** [comment]
2020-02-13 PW Standup
- anne and jen meeting next week to review copy deck with stakeholder group before closing this out! (sent the copy deck to the group today). will add to sprint 15 once it's complete

**Comment by AkucherGCIO** [comment]
2020-26-02 PW Planning:
Waiting for SME Feedback. Moving it to backlog.

**Comment by AkucherGCIO** [comment]
2020-27-02
Still awaiting SME Feedback.

**Comment by AnneHurley** [comment]
@RLHecht  I've updated the page with the stakeholders' request to change wording in featured content from "2 sets of requirements" to "2 ways to qualify." It's in draft stage: https://prod.cms.va.gov/node/724/edit

@jenniferlee-dsva  FYSA

Moving to current sprint.

**Comment by RLHecht** [comment]
@AnneHurley I reviewed this change and set it to publish. I missed today's deployment but it should be live late tomorrow afternoon. Can this be moved to validate or are there going to be other rounds of changes on this ticket?

**Comment by AnneHurley** [comment]
@RLHecht  This should be done and we can move to Validate. thanks!

**Comment by RLHecht** [comment]
@AnneHurley This is published and will be live later today.

**Comment by AkucherGCIO** [comment]
03/05/20 PW Standup
@annehurley - will validate they are live first.  @lunascoop will communicate with Robin and Betty and cc @jenniferlee-dsva  after.

**Comment by AnneHurley** [comment]
@lunascoop @AkucherGCIO  - Robyn Turlock has approved on behalf of stakeholder team. Ready for redirect.

**Comment by AkucherGCIO** [comment]
03/06/20 PW Standup
Closing this ticket.  @lunascoop  will be creating the redirect ticket.
