### ISSUE TITLE
BE Unit: Create Back-end Unit Test Flakiness Coverage Visualization

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#31990]
## User Story

_As a VFS product stakeholder, I would like to have a dashboard card that will show how what percentage of branches are currently being covered by our back-end unit testing suite._

## Tasks
- [ ] Create a Domo Dashboard Card that reflects what percentage of tests are exhibiting flakiness on average in our back-end unit testing suite.
    * This data requires the prior `Ingest Back-end Unit Test Data Into BigQuery` task to be completed first. The data source for this should already exist in Domo.
    * This card should support filtering by application.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria

- [ ] _A dashboard card exists reflecting what percentage of tests are exhibiting flakiness on average in our back-end unit testing suite provides_

**Comment by ddzz** [comment]
It was discovered that retries were not enabled in back-end unit tests. This PR enabled them, which should help with flakiness: https://github.com/department-of-veterans-affairs/vets-api/pull/8891

In order to capture flaky unit tests in RSpec it would likely require modifications to RSpec itself and the RSpec JUnit reporting used in `vets-api`, which is a larger effort than anticipated.

**Comment by pjhill** [comment]
OBE
