### ISSUE TITLE
Analytics Discovery - [Veterans Crisis Line]

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-team#32018]
I’m looking for analytics for clicks on the Veterans Crisis Line (VCL) links across all VA.gov pages, and subsequent clicks on the various links in the modal dialog that opens. In particular, I'm wondering

1. What triggers `Navigation - Jumplink Click - Veterans Crisis Line` 
2. How the # of clicks in (1) compares with the VCL links in the top right corner (red button) and in the footer
3. Analytics for each of the interactions in the modal (call, text, chat, TTY, VeteransCrisisLine.net)

## Acceptance Criteria
- [ ] Responses to 1-3 above

**Comment by bsmartin-ep** [comment]
Hey @cindymerrill -

1. It turns out event `Navigation - Jumplink Click - Veterans Crisis Line` is **also** from this CTA...

![image](https://user-images.githubusercontent.com/62304138/139603137-2a1e2bb5-859d-40ea-9c80-898fa67d58df.png)

The way this is coded, if the user clicks the "Veterans Crisis Line" part of the image, that is what is sent into GTM.  Took some intense zooming to recreate this consistently.

I'm thinking we want to SUM these event metrics for now.  But I'm going to backlog an issue to address this problem.

----

2.  [This filter regex](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22Navigation%20-%20Jumplink%20Click%20-%20(.*)Veterans%20Crisis%20Line%22,0%5D%5D/) will get you all the events for that CTA.  For comparison, [here are the footer metrics](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22EQ%22,%22Navigation%20-%20Footer%20-%20Veterans%20Crisis%20Line%22,0%5D%5D/).


-------

3.  Event actions with links to GA reports....

**Call 800-273-8255 and select 1**
[Event action](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22EQ%22,%22Outbound%20Link%20Clicked:%20tel:18002738255%22,0%5D%5D&explorer-table.secSegmentId=analytics.pagePath/):  `Outbound Link Clicked: tel:18002738255`

**Text 838255**
It does not look like we have tracking for the `sms:` protocol.  Should I enter a ticket to get this tracked point forward?

**Start a confidential chat**
[Event action](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22EQ%22,%22Outbound%20Link%20Clicked:%20https:~2F~2Fwww.veteranscrisisline.net~2FChatTermsOfService.aspx%3Faccount=Veterans%252520Chat%22,0%5D%5D&explorer-table.secSegmentId=analytics.pagePath/):  `Outbound Link Clicked: https://www.veteranscrisisline.net/ChatTermsOfService.aspx?account=Veterans%20Chat`

**Call TTY if you have hearing loss 800-799-4889**
[Event action](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22EQ%22,%22Outbound%20Link%20Clicked:%20tel:+18007994889%22,0%5D%5D&explorer-table.secSegmentId=analytics.pagePath/): `Outbound Link Clicked: tel:+18007994889`

**Get more resources at VeteransCrisisLine.net.**
[Event action](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22EQ%22,%22Outbound%20Link%20Clicked:%20https:~2F~2Fwww.veteranscrisisline.net~2F%22,0%5D%5D&explorer-table.secSegmentId=analytics.pagePath/): `Outbound Link Clicked: https://www.veteranscrisisline.net/`

**Comment by cindymerrill** [comment]
Thank you, @bsmartin-ep ! Here are my responses by numbered items above:

1. I don't understand the difference between _Navigation - Jumplink Click - Talk to the Veterans Crisis Line now_ and _Navigation - Jumplink Click - Veterans Crisis Line_. Are there two different clickable areas in the same red rectangle? I don't mind adding the two numbers together, but I'm curious about what they're each tracking.
2. I set all the timeframes to Oct 1-31 and added together both Jumplink tallies, and the date shows that most clicks are from the red button (not the footer link), which isn't surprising: 
![image](https://user-images.githubusercontent.com/69914583/139739436-b057a15e-a1c9-40e4-a354-1fe49da0a436.png)
3. Yes, could you please enter a ticket to get the SMS link tracked going forward? I'd like to add compare that to these numbers: 
![image](https://user-images.githubusercontent.com/69914583/139739392-71df8704-88f2-41d0-8694-0420206c2da3.png)
4. (NEW question) Can analytics help explain the big drop-off from 14,227 clicks on the VCL to 5,168 actions in the modal? Perhaps people finding the number on a computer then typing a number to call or text into their phone?

Thanks!

**Comment by bsmartin-ep** [comment]
@cindymerrill -

> Are there two different clickable areas in the same red rectangle?

Correct - it is grabbing the click text of the "nearest" element.  In this case the internal `<strong>` element:

![image](https://user-images.githubusercontent.com/62304138/139969805-ab79c610-7b9a-4b32-9c3c-e00eea2edfa6.png)

> Yes, could you please enter a ticket to get the SMS link tracked going forward? I'd like to add compare that to these numbers:

[Ready for QA](https://github.com/department-of-veterans-affairs/va.gov-team/issues/32330) from my team.   I'll let you know when we're live.

> (NEW question) Can analytics help explain the big drop-off from 14,227 clicks on the VCL to 5,168 actions in the modal? Perhaps people finding the number on a computer then typing a number to call or text into their phone?

So how many do the following?

1. Close the modal without clicking on one of the links
2. Abandon the page
3. Something that we can't track like "Perhaps people finding the number on a computer then typing a number to call or text into their phone"

**Comment by bsmartin-ep** [comment]
@cindymerrill -

1. That is correct.
2. Just deployed this today, so we should [start seeing events here shortly](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_u.date00=20211103&_u.date01=20211103&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=sms:&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22sms:%22,0%5D%5D/).
3. To track modal closes, we would need a developer to add that to the custom modal component they are using.  Or switch to the standard modal component.  Exits / abandonments from events are not something we can track in GA, but could write a BigQuery query to calculate how my sessions end with the launching of the VCL modal.

**Comment by cindymerrill** [comment]
Thank you, @bsmartin-ep ! I see no VCL chat events yet, but I'll check again tomorrow...

**Comment by cindymerrill** [comment]
Now I see 2 hits, so analytics tracking must be working now :)
