### ISSUE TITLE
Google Analytics - Self Serve Link for pulling reports

### ISSUE THREAD

**Issue by Justin-Pickett** [department-of-veterans-affairs/va.gov-team#3203]
## Goal 

Work with analytics team to get proper link configurations to be able to pull/generate reports of mail address error reporting. 

Orginal Ticket for Tracking this GA information is - [ #2359 ](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/2359)
## Task

- Get link from analytics team
- Get proper configurations set to share with team

## Definition of Done 

- Share/Walkthrough with team

**Comment by nedierecel** [comment]
@Justin-Pickett Please see a few starting self-serve links: 

1. Segment to see Direct Deposit Failures with Phone Errors - [Open this link to see the segment](https://analytics.google.com/analytics/web/template?uid=L8vnwX4gQ628-x5Hb1e8ig) to your `Personalization Modernized` view. The logic here is to look for sessions with a `Profile Save Failure - Direct Deposit` and an error key of `home-phone-error`. 

After you do so, navigate to [Audience>User Explorer](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-legacy-user-id/a50123418w177519031p187673796/_u.date00=20191024&_u.date01=20191107&_.useg=usereo9GBKvxQ_2dC5Wu_l5v3w&_.advseg=&_.sectionId=/) and then apply the segment.

2. [Direct Deposit Dashboard - High-level overview of performance](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p187673796/_u.date00=20191024&_u.date01=20191107&_.useg=builtin1/) 

**FYI** 
The total events for errors means that multiple errors can happen in one session. This is why the errors might not match the total sessions. 

- Use Case: I encounter a direct deposit failure with a `home-phone-error` 2x in my session. Google Analytics counts me as 1 session with 2 events for `home-phone-error`

3. [Profile Save Failures with Error Keys](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p187673796/_u.date00=20191024&_u.date01=20191107&_.useg=builtin1&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.customDimension57&_r.drilldown=analytics.eventCategory:API%20Calls/) - This might be helpful for @erikphansen to see the breakdown of Failure types against Error Keys. Erik, there is a handful of error mapping like this that seemed odd, but it was a small percentage of total errors:

![image](https://user-images.githubusercontent.com/24525739/68428757-c6baf300-017a-11ea-95b9-92141fc86ba4.png)

*Helpful Tip*:
If you hit `Save` in the upper right, this will save the settings and segments for the #1 and #3 reports to your personal assets. You can then access these reports from Customization>Saved Reports. The dashboard should already be accessible to anyone who has Google Analytics access for this view.

**Comment by nedierecel** [comment]
@Justin-Pickett Please see a few updates from the Analytics-Insights team:

1. **Add Link Interactions are 0**: I noticed the `Add Link` events are no longer. Is this expected behavior?

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/2725184d-2199-4afd-8fc1-e206cff31bf0)

[Link to Dashboard Displaying 0 events for Add Link](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/T7daIpzoRw2LOg1BVHJ0Dw/a50123418w177519031p187673796/)

2.  **Phone Error Tracking**: I also created a segment to track phone errors. I am sharing the link to [save this segment to Google Analytics](https://analytics.google.com/analytics/web/template?uid=L8vnwX4gQ628-x5Hb1e8ig).  Let's connect this week if you'd like to review the phone errors. 

3. **Reorganized the Dashboard**: I moved around some of the charts to put more common user interactions together.
