### ISSUE TITLE
TUD: Track page views per day

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#32162]
## User Story
_As a TUD stakeholder, I would like to have a dashboard card that will display how frequently pages are viewed in TUD._

## Tasks
- [x] Create a Domo Dashboard Card that visually presents the frequency with which the pages are accessed.
    * This data requires the prior `Evaluate TUD Data Ingestion` task to be completed first.
    * If possible, it'd be ideal to allow the filtering to be applied via clicking any of the bars to show a single application view, in addition to top-of-page filtering.

## Acceptance Criteria
- [ ] _A dashboard card exists visualizing the frequency of help page access._

**Comment by holdenhinkle** [comment]
This is the first thing I'm going to track in GA. After this, I'll make tickets to track the other pages.

I just asked the Analytics Team to create the TUD GA property - https://dsva.slack.com/archives/CBU0KDSB1/p1641244680267100

Here's the ticket we were working from - https://github.com/department-of-veterans-affairs/va.gov-team/issues/32617

Since TUD is a Gatsby app, I'm going to use the Gatsby GA plugin - https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/

Here's the draft PR - https://github.com/department-of-veterans-affairs/vsp-test-user-dashboard/pull/100

**Comment by holdenhinkle** [comment]
Analytics setup the property and added our team as admins (but not Darius) - see https://github.com/department-of-veterans-affairs/va.gov-team/issues/32617.

The `gatsby-plugin-google-analytics` plugin doesn't work with GA v4. But they have another plugin that does, which I'm using instead - `gatsby-plugin-google-analytics`.

We're tracking page views in TUD now. I excluded the following paths which aren't pages, just redirects -- `/oauth` and `/logout`.

Screenshot of GA:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/9504bdf6-eb44-4a19-a84d-6ccf7b9557be)

**Comment by holdenhinkle** [comment]
This ticket is complete.

I confirmed that the `/oauth/` and `/logout/` paths are being excluded.

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/3b3c92b4-2de7-4fb9-a352-78fad51839fa)

**Comment by holdenhinkle** [comment]
Still waiting on analytics to tell me how to get the TUD GA data in to BQ/DOMO. See
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/32617#issuecomment-1005924338
- https://dsva.slack.com/archives/CBU0KDSB1/p1641477276003300?thread_ts=1641244680.267100&cid=CBU0KDSB1

**Comment by holdenhinkle** [comment]
All the content for the TUD help page resides in a number of markdown files. Some of the content contains links to external resources. Because the links are configured in markdown there isn’t a way to track clicks to outbound links.

To track the clicks to external resources we need to use the Gatsby `OutboundLink` component:

```
import React from "react"
import { OutboundLink } from "gatsby-plugin-google-gtag"

export default () => (
  <div>
    <OutboundLink href="https://www.gatsbyjs.org/packages/gatsby-plugin-google-gtag/">
      Visit the Google Global Site Tag plugin page!
    </OutboundLink>
  </div>
)
```

This isn't possible, because of the way the Help page is setup. So, we're not gonna track clicks to outbound links on the Help page.

**Comment by holdenhinkle** [comment]
This is done.

![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/dd84b84e-90e8-44a0-b1b8-a83db9570ffd)

**Comment by pjhill** [comment]
Looks good -- hopefully this will be informative once we've onboarded more teams.
