### ISSUE TITLE
[UX] Mock up adding BTSSS link to appointment confirmation screen

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#32172]
## Description
We need a prototype/mock up of what it will look like to ad the BTSSS link to the appointment confirmation screen so that we can solidify the design for development. 

## User Story
As a veteran I would like to be able to access BTSSS during the check in process so that I can easily submit my claims for travel reimbursement. 

## Acceptance Criteria
1. A mock-up showing the link to BTSSS  confirmation screen. 

Link to BTSSS:
https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

**Approved wireframe:** 
https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/v/9xa0w0/a/3OvpYVm/r/y5a1wa

**Comment by julieadair1** [comment]
Note that this will involve syncing with @DanielleThierryUSDSVA for the verbiage

**Comment by kristenmcconnell** [comment]
Sketch file where the edits will occur: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e

**Comment by zach-park** [comment]
@kristenmcconnell @jparker0425 , here are confirmation UI options w/ BTSSS link:
Option 1: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/3OvpYVm
Option 2: https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e/a/ZOl8Zvp 
Pls lmk what you think. Thank you!

**Comment by stephenBarrs** [comment]
@zach-park have you already worked with @DanielleThierryUSDSVA on this or is that still ToDo?  I would think the verbiage might be something like 'You can submit a travel pay request here'.  Not all Veterans will know what BTSSS is or what the acronym stands for; one of the benefits of adding the link here is to let more Veterans know about BTSSS and that they can use it to submit travel pay.

**Comment by kristenmcconnell** [comment]
@zach-park I looked at the Sketch files first before I checked here, so I added the same comment as Stephen in the Sketch files. I also added some ideas about the placement of the link within the success message. @DanielleThierryUSDSVA should review content.

**Comment by zach-park** [comment]
Hi @kristenmcconnell , the mockup is updated now and I also updated the sketchcloud link above. Thank you!

**Comment by zach-park** [comment]
Hi @DanielleThierryUSDSVA , here is the ticket I was referring to on the UX Slack channel. Thank you. (Cc: @kristenmcconnell @jparker0425 @julieadair1 )

**Comment by DanielleThierryUSDSVA** [comment]
Hi @zach-park. I think you mentioned in our call today that for this use case, we don't need to address eligibility for travel pay. If that's the case, we can just provide the link. But since the page we're taking them to isn't the actual page where you file your claim, I would still recommend the "Find out how..." messaging for the link:

[Find out how to request travel pay reimbursement](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/)

If we want to take them directly to the BTSS system to file their claim, we could also consider adding this link below the first one:

[Sign in to file a travel pay reimbursement claim now](https://eauth.va.gov/accessva/?cspSelectFor=bts)
