### ISSUE TITLE
Analytics Implementation or QA Support for Home Page Promo Banner

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va.gov-team#3238]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?
GA implementation

- Who is this request for?
Patrick B. (@patrick in DSVA Slack)
    
- What team/project is this work for?
VSA Public Websites Team (Unauthenticated experience)
    
- Provide the Domain where Google Analytics needs to be implemented
www.staging.va.gov
www.va.gov
    
    _Identify if PII is passed in URL or title tag_
    
 None.

- Please provide any upcoming deadlines or important milestones
Would like this in place as soon as possible to measure clicks around Veterans Day.
  

- Typical Website Interactions to Track
Would like to discover how much interaction the promo banner on the home page is getting. What percentage of users are clicking the promo banner link, what percentage of users are clicking dismiss, etc... How do these totals compare with other elements on the home page?
  
> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by joanneesteban** [comment]
Banner no longer on VA.gov. Iceboxing and setting a reminder to review any potential banners the sprint before Veterans Day 2020.

**Comment by batemapf** [comment]
I'd still like to move forward with instrumenting the promo banner, even if it's not being used currently. It will definitely be used before next Veteran's Day (prior to Veteran's Day it had been used to promote the MISSION Act for months) and I'd like to have analytics in place ahead of time.

**Comment by joanneesteban** [comment]
Good to know! Removing from ice box and putting into Ready.

@batemapf do you have the specs for the promo banner?

**Comment by batemapf** [comment]
as much as i hate to pull him into more things... @ncksllvn might be your best bet here. cc @jenniferlee-dsva for awareness.

**Comment by ncksllvn** [comment]
Ah yep, this is probably overdue. 

@nedierecel @jonwehausen  I think this ties into your [Epic](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1531) - `UX Standardized Datalayer Analytics`. It calls for implementing analytics into the [PromoBanner](https://design.va.gov/components/promo-banners), a design system component.

**Comment by nedierecel** [comment]
Thanks @ncksllvn - we'll tackle this post-Thanksgiving but can begin giving it some thought. 

Let's also think through a QA plan as other teams use this component (and other standardized UX analytics). I am thinking particularly of the `accordion-expand|collapse` issue we ran into a few weeks ago with it breaking the mobile footer.

**Comment by ncksllvn** [comment]
@nedierecel Sounds good.

That issue, btw, came as a side effect of this work - https://github.com/department-of-veterans-affairs/va.gov-team/issues/1846 - not the accordion standardization. An event was explicitly added into the footer, for some reason. I reviewed the corresponding PR, but I didn't understand the scope of the work, so I thought it was intentional.

**Comment by nedierecel** [comment]
Thanks @ncksllvn - Ah, good point on the #1846 issue not being specific to standardization!

**Comment by jonwehausen** [comment]
Hi @ncksllvn , 

In order to future-fit for future promo banners stood up, would it be possible to get a sample banner stood up in staging? 

If so, we would like to move forward with DL implementation for the promo banner. 

```javascript
dataLayer.push({
   'event': 'nav-promo-banner-link'
});
```

**Comment by ncksllvn** [comment]
Hey @jonwehausen sorry I missed this. I'm going to get it on our team's radar ASAP.

**Comment by ncksllvn** [comment]
Front-End steps to do this -

1. In the [Promo banner component](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation-react/src/components/PromoBanner/PromoBanner.jsx) -
    - When the anchor tag or close button is clicked, dispatch an event called `@department-of-veterans-affairs/formation/promo-banner/click`.
1. In vets-website, subscribe to that event, like we do other [design system components](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/subscribeAdditionalInfoEvents.js)
1. Create a promo banner in vets-website that is disabled below prod.

**Comment by ncksllvn** [comment]
@nedierecel @jonwehausen sample banner is up on staging

**Comment by nedierecel** [comment]
Thanks @ncksllvn - Jon is OOO today, but he and I will review when he returns tomorrow.

**Comment by jonwehausen** [comment]
Thanks @ncksllvn for getting this setup in staging. 

Looks like the event is firing just fine. 

### Datalayer
![image](https://user-images.githubusercontent.com/48527022/72896422-bc29e780-3ced-11ea-9d57-7d0829546d1f.png)

### Google Analytics Event [GTM Preview]
![image](https://user-images.githubusercontent.com/48527022/72896862-a668f200-3cee-11ea-86ff-2e20d303aa87.png)


@nedierecel , I've added the ``nav-promo-banner-link`` event to the Navigation Action Lookup table. I believe this is the only change needed on our part. _Side Note: It appears the promo banner disappears after initial click._

**Comment by ncksllvn** [comment]
Perfect! The thing with the promo banner disappearing after click is intentional. It's designed that way so that it doesn't feel spammy. But you can open an Incognito tab to see it again.

**Comment by nedierecel** [comment]
@ncksllvn I noticed both in Staging and in Prod that the links have UTM parameters appended. I also put this as an issue in #5013.

UTM parameters are typically used for external sites or emails driving traffic back to VA.gov. The impact of its use is that it will start a second session each time someone clicks on the link. Can we remove? Happy to discuss with the Public Websites team if there are more questions.

**Comment by ncksllvn** [comment]
@nedierecel that is so strange! There is no code in the direct implementation that would append that parameter. The parameter is only appended on mouse down it looks like, because when I hover over it at first there's no UTM, but when I right click, I see it appear. Is this a global behavior for GTM? Something with absolute links?

**Comment by nedierecel** [comment]
@ncksllvn Thanks for diving in! We don't typically append utm parameters to internal links within GTM; there's usually a process attached to define the values that populate in source, medium, and campaign.

These are usually provided by someone on a content or marketing/PR team. I'd like to request removal but want to make sure the original requestor is notified, in case this was intentional by another party.

**Comment by jonwehausen** [comment]
Hi @ncksllvn ,

Wanted to follow-up on Nedie's note here? Were we able to get the UTM params removed for the promo link? 

Also what is the status of the event ready to go in production? 

Thanks,
Jon Wehausen

**Comment by ncksllvn** [comment]
Hey @jonwehausen -

> Wanted to follow-up on Nedie's note here? Were we able to get the UTM params removed for the promo link?

The UTM params aren't a thing implemented in the promo banner...it appears that the UTM params are appended to the URL right as you click. You can see it happen if you hover and then right click. Because of that, it seems like some weird global behavior that I think we should track in a different ticket. I really don't know why that's happening.

> Also what is the status of the event ready to go in production?

It's in production. We'll see it working next time there's a promo banner rolled out.

**Comment by jonwehausen** [comment]
Okay great! Our tracking is ready to go in production as well. 

Understood and agreed on the UTM params -- we will want to just find out why those are being appended since it will effect campaign data. 

One thing to just to note - Nedie and I noticed that there is a [warning alert UX component](https://design.va.gov/components/alertboxes) currently in production for CDC. 

To be clear on a distinction here, the promo banner DL event asked for here is related to [this type](https://design.va.gov/components/promo-banners) -- _as the one presented and tested in staging_. Therefore, if we need to get tracking for alert box types that are intended to serve as "banners" we will need to build that in. Just want to make sure there wasn't a need to get tracking for the "alert box" component in case there is a need for tracking these currently.

**Comment by ncksllvn** [comment]
Understood about the distinction between the promo banners and alert boxes! I didn't touch the alert boxes during this work.

**Comment by nedierecel** [comment]
@ncksllvn Thanks for the update! 

To help us understand usage of the components, will content producers have the option to create warnings OR alert boxes for homepage promo banners, or do you think we might be standardizing to one type?

**Comment by ncksllvn** [comment]
Of course @nedierecel! The promo banner has three types, described [here](https://design.va.gov/components/promo-banners) - 

1. Benefit announcements
1. Email signups
1. News stories

They're all very similar though. The only design difference is the icon on the left side.

Also, we usually think of the homepage when we think of promo banners, but they aren't necessarily tied to the page. They can be configured to show up anywhere, and sometimes they are site-wide. If you login with a user on Staging on a fresh browser (make sure `localStorage` is cleared because the promo banner persists its cleared state via `localStorage`), I think you'll see a promo banner for the user profile/dashboard on every page. I _think_, anyway.

**Comment by nedierecel** [comment]
Thanks @ncksllvn - I noticed the latest banner on the homepage for Coronavirus is missing the tracking.

@jonwehausen For future use of alert boxes, should we use the same `nav-promo-banner-link`? Thanks!

**Comment by ncksllvn** [comment]
> I noticed the latest banner on the homepage for Coronavirus is missing the tracking.

Of course! The homepage banner is actually a separate component from the promo banner (promo banners are sticky to the bottom of the page.) Should the homepage banner have tracking? I think I recall a discussion about that, but I don't recall working on it.
