### ISSUE TITLE
Show `bookingNote` and `instructionsToVeteran`

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#3257]
Currently, the front end has access to - but is not showing - `bookingNotes` and `instructionsToVeterans` fields for confirmed appointments. These fields likely correspond to 'reason for appointment' (which is a 150 character veteran-supplied text response), and 'Prepare for your appointment', respectively. We should decide whether we want to display these fields (if they provide sufficient value to veterans) and, if so, how.

**Comment by rtwell** [comment]
## bookingNotes

`bookingNotes`— is this the same as the "Additional details" that we're including on the "Why do you need an appointment" page? here's the page i'm referring:

![image](https://user-images.githubusercontent.com/12564977/68679682-57545300-052e-11ea-926a-c0b7db6d341f.png)

If that's the case, yes, we want to show it. If not, where is the user inputting the info for this data point? Or is it from a scheduling clerk?


## instructionsToVeterans

Can we list the actual information / functionality possible with this? All I ever saw this do on the test accounts is drill down to details and that's where you could see some other stuff + cancel + add to calendar. To that end, since we are surfacing cancel and calendar at the top level, i'm not seeing a use for it.

Are there other functionalities that i'm not aware of?

**Comment by jbalboni** [comment]
@rtwell @markgreenburg I think these questions are covered in the latest mocks and we can close this?

**Comment by rtwell** [comment]
i say thee YAY
