### ISSUE TITLE
Login.gov research

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#32690]
This story will be done when we have answers to the following questions:

1. What would the developer experience look like if login.gov was used as the primary identity provider?
2. Assuming login.gov was our chosen solution, how have we made things easier for developers?
3. Assuming login.gov was our chosen solution, what do developers need to consider now that they didn't before?

**Comment by ken-non** [comment]
federal, not owned by VA so support will be more difficult

**Comment by ken-non** [comment]
Have to decide between OIDC and SAML if we use Login.gov

**Comment by patrickvinograd** [comment]
Login.gov is a generic, non-VA identity. So it's not going to have any notion of "is this a VA platform developer" or even "is this a VA person". Literally any US person can sign up for a Login.gov account and identity proof it. So we'd need to maintain a separate mapping of who among login.gov users is authorized for access. Put this in contrast to something like GitHub, where membership in the VA GH org is somewhat controlled (though probably more weakly controlled than is needed). 

Plus side - Login.gov provides a strongly authenticated (via 2FA) and strongly identity proofed credential. So better than GH OAuth in that respect, but slightly weaker (in assurance terms) than PIV auth. 

We don't necesarily **need** strong identity proofing because we have an out-of-band way of ensuring that - through human communication/approval processes, like the program manager telling the COR "yes this is a new person on a contract".  We just need to be clear about how we're ensuring identity and authenticator certitude - whether that's through a credential or another mechanism.

**Comment by patrickvinograd** [comment]
Users can self-register for a login.gov account, and go through the identity proofing, without relying on the VA PIV machinery. Combine this with some sort of approval/onboarding process (that could be within the VA.gov platform adminstrator's control) and it could make for a faster onboarding experience.

Possible roadblock - if we require that platform user login.gov accounts are identity proofed, some number of developers may run into trouble with the identity proofing, which requires either scanning a photo ID or answering credit history type questions. We know some percentage of va.gov users are unable to complete this process for various reason, including e.g. having locked ones credit file. So there will be a support burden there.

**Comment by kjduensing** [comment]
@patrickvinograd You mentioned Login.gov being slightly weaker in assurance terms than PIV auth. 

In playing around with Login.gov, I was able to easily set up a PIV card and use that as my 2FA. I'm a little unclear in what you mean by Login.gov being weaker in assurance than PIV auth. Would you mind clarifying a little? Thanks!
