### ISSUE TITLE
[Discovery]: Explore options for handling icons in web components

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#32758]
## Description
Right now, we are using a combination of Font Awesome and text codes for icons in the web-components. We would like to come up with a better and more efficient system for using icons.

Ideas that have been discussed include:
- figuring out a better way to use Font Awesome
- switching to use SVG icons

## Definition of Done
- [ ] Complete investigation on best practices for using icons inside web components
- [ ] Make recommendation for a path forward and review with PM and TL
- [ ] Make cards for completing work

**Comment by bkjohnson** [comment]
For additional context, some of icons for web components are [using SVGs](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/web-components/src/assets). This is because `formation` uses `uswds`, which uses SVG icons.

Here is an example: https://github.com/uswds/uswds/blob/c4c9410d54b537c6112037a36ed289d8b7e8940a/src/stylesheets/components/_accordions.scss#L32

**Comment by pdavies88** [comment]
Idea: 
Move away from Font Awesome and create an internal Icon Library since we are only using a small subset of all the icons available in Font Awesome. This could also allow for designers to use Icons not in Font Awesome if they'd like and we can support them. 

Steps would be to download all the Font Awesome icons and disparate icons that we are currently using as svgs and put them into a single file or multiple files within a folder and then export them as components which can then be imported into our Web Components and used there. 

Doing this would make things a bit easier to provide additional context to the element since they would be converted from Fonts or Unicode values to actual DOM elements where we could then add aria related context and pass those values as props.

**Comment by bkjohnson** [comment]
There may be greater value in switching to SVG icons instead of sticking with `fontawesome`. `fontawesome` is used in `vets-website`, and it's used with `<i>` tags and setting the appropriate FA class name. One of the problems is making sure that the icons are compatible with assistive tech - a purely decorative icon should have `aria-hidden="true"`, and there is a GitHub action that will leave a comment on a PR and tag frontend tools anytime an `<i>` tag is found. This creates a lot of noise, so having something like `<va-icon icon="arrow-up">` that can pull in the appropriate SVG file may be useful for several reasons.

**Comment by k80bowman** [comment]
We might want to include this as part of our USWDS v3 discovery work. If it's possible to use their icons, that's not a bad idea.

**Comment by bkjohnson** [comment]
In https://github.com/department-of-veterans-affairs/component-library/pull/540 I explored a few different options for using USWDS SVG icons inside one of our web components and I was able to get them to work using the "USWDS way" using an inline `<svg>` and a sprite sheet. This seems like the best path forward.

**Comment by bkjohnson** [comment]
If we wanted to modify the spritesheet either to remove some USWDS icons or add our own, that seems possible as well. The [USWDS icon documentation](https://designsystem.digital.gov/components/icon/#using-the-icon-component) has a section that reads:

> Active icons are found in `dist/img/usa-icons`. The icons in this directory will be packaged into an SVG sprite. The complete set of available icons are located in two directories: `dist/img/material-icons` and `dist/img/uswds-icons`. Copy icons into a usa-icons directory within your project images directory, and rebuild the SVG sprite using [uswds-compile](https://github.com/uswds/uswds-compile/).

And that `uswds-compile` tool [has instructions on rebuilding the spritesheet](https://github.com/uswds/uswds-compile/#updating-the-uswds-icon-sprite). I haven't explored doing this as part of the discovery, but it's available if we want to do it.

**Comment by k80bowman** [comment]
Do you feel like rebuilding the spritesheet is worth exploring? Or should we move forward with the inline `<svg>`?

**Comment by bkjohnson** [comment]
I don't think it's worth exploring now unless we know that we want to change, remove, or add icons to the spritesheet.
