### ISSUE TITLE
Collaboration Cycle Kickoff [Caregiver, American Indian Question 10-10EZ]

### ISSUE THREAD

**Issue by JSorensen55** [department-of-veterans-affairs/va.gov-team#32765]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [ ] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [ ] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/health-benefits/healthcare-application/product-outline.md)
- Wireframes, mockups, or prototypes https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6
- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [x] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: 10-10EZ

### 4. Are you making changes to the visual design?
- [x] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [ ] Yes
- [x] No

### 6. Will your work involve changes to: (select all that apply)

- [x] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [x] New content
- [ ] Changes to existing content

### 8. Are you making a change to the user flow?
- [x] Yes
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [ ] Yes
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [ ] No

### 12. Does your team have a Github label for this product?

- [ ] No. 
- [ ] Yes. Please specify: ____________

### 13. Who is the VA business owner for this body of work?

- [x] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.

**Comment by shiragoodman** [comment]
Hi @JSorensen55. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)

- [Analytics Request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) (only needed if your team plans on modifying analytics/metrics for the 1010ez)

- [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)

- [Contact Center Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) 

- [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)

- [Privacy and Security Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

Post Launch: 

- [Full Accessibility and 508 Office Audit](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html)

- [Post-launch Check-in](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Post-launch-check-in.1781956691.html)


The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

**Comment by shiragoodman** [comment]
also @JSorensen55  - I try and meet with all the new PMs to do a more in-depth review of Collab Cycle, specifically PM responsibilities. It usually takes 30 minutes. If you're interested, please DM me on Slack and we can set something up.
