### ISSUE TITLE
Fix Storybook Radio button examples

### ISSUE THREAD

**Issue by noahgelman** [department-of-veterans-affairs/va.gov-team#33072]
# Bug Report

Radio buttons are incorrectly coded in storybook

https://design.va.gov/storybook/?path=/docs/components-va-radio--default

The radio inputs need to have the same name to group them together in the same radio group
The id's for each input need to be unique. Current they're both just "input"
The label for each input needs to have its' "for" attribute value updated to the unique id of its' related radio input.
The radio inputs need their focus styling applied when focused

**Comment by andresriveratoro** [comment]
@noahgelman 
> The radio inputs need to have the same name to group them together in the same radio group

This PR https://github.com/department-of-veterans-affairs/component-library/pull/225 addresses this issue. The Storybook example was updated to use the same name "example" for all radio options in the radio group.

> The id's for each input need to be unique. Current they're both just "input". The label for each input needs to have its' "for" attribute value updated to the unique id of its' related radio input. The radio inputs need their focus styling applied when focused

These changes were made in https://github.com/department-of-veterans-affairs/component-library/pull/214. 

`va-radio` and `va-radio-option` were updated to have keyboard navigation functionality using https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton and https://www.w3.org/TR/wai-aria-practices-1.1/examples/radio/radio-1/radio-1.html as a reference. One of the drawbacks of using encapsulated web components is having to manually implement functionality that is otherwise provided by the browser when using semantic HTML. This was the major reason for implementing the roving tabindex.

The id and label `for` attributes for each radio option were updated to use `<va-radio-option>`'s label attribute value. The ids will not conflict because of the encapsulation provided by the shadow DOM for these web components. Focus styling was also fixed to target the correct elements.
