### ISSUE TITLE
[PERFORMANCE] Discovery: determine which bundler would be best for React Components

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33187]
## Description
We are currently only minifying our React components without using a bundler like webpack or rollup. This means our package is larger than maybe it should be and we don't get the optimization benefits. Currently, our react-components package is 245.3kb (uncompressed). We'd like to reduce that, if possible.

The question here, though, is whether we should use webpack or rollup. We are currently using rollup for the web-components, which makes it an easy choice. But rollup can sometimes create larger packages than webpack and is not as familiar to most developers. We'd like to evaluate the two options for (1) ease of use and (2) resulting bundle size.

## Acceptance Criteria
- [x] Evaluate use of webpack and rollup for React Components
- [x] Provide results of evaluation based on ease of use and resulting bundle size
- [x] Create a ticket (or tickets) for completing the work

**Comment by andresriveratoro** [comment]
### Ease of use
I think this comes down to preference as I ran into issues for both bundlers that weren't exactly easy to troubleshoot. Rollup required more explicit configuration settings, whereas Webpack took care of these under the hood. Webpack also required changes to our CI yml files, but I think we're going to want to update these regardless of the bundler we choose.

### Bundle size
Rollup's bundle size was almost 20% bigger than Webpack. I wasn't able to get Storybook to run due to "react is not defined" errors that should have worked using the externals property, but the difference in bundle size may warrant further discovery into fixing the Webpack configuration.

**Comment by k80bowman** [comment]
Great work @andresriveratoro. And I was really curious about that bundle size question... seems like the rumors I heard were true. From a performance perspective, I would definitely be in favor of going with webpack. It sounds like you think that configuration issue is solvable, is that true?
