### ISSUE TITLE
[Design] On-site Notifications: Update design on MVP notification

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#33266]
## Background
As a proof of concept, we will build one notification, assessing metrics and scalability, then determine next steps for the overall strategy.  [On-site Notification MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/vagov-notifications/mvp/README.md) has been determined as an Outstanding Debt notification.
The notification will be a simple line of copy and a link to more information.

**We do not need to show personalized data in notifications.**

- [Project outline from discovery](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/action-items-discovery#readme) for reference. 
- Discovery epic: #25886 

## Tasks
- [ ] Update design of My VA dashboard showing the MVP notification, on which a logged-in user can take action.

## Acceptance Criteria
- [ ]  My VA dashboard page will display a notification for the logged-in user to take action.

**Comment by tressaellen** [comment]
All screens and comments will be in [this Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1638500075560/0e849f61e282ebe2d8e7119eea504e4c05b0bbe4?sender=tressafurner7646).

**Comment by tressaellen** [comment]
This is all updated, [designs can be seen in this mural](https://app.mural.co/t/vsa8243/m/vsa8243/1640028268317/2ba4e1b2846c87f5d0bfc6bcb643bef84720bea1?sender=tressafurner7646). We are in the process of working with content, so that might change. But everything else is pretty set (pending the experimental design process). So I think we're good to close this ticket!
