### ISSUE TITLE
Simplify process for versioning releases

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#33337]
## Details
Currently, when either the React components or the web components are updated, we need to manually bump the version for whichever portion of the design system is updated and also for the core package. We would like to explore ways we can automate this process more and make it simpler for design system developers and outside contributors

## Acceptance Criteria
- [ ] The versioning process is simplified and only requires one manual intervention at most.

**Comment by bkjohnson** [comment]
## Thoughts

I'm saying all of this with the following underlying assumption:
- We want to enable any contributor to release & publish their changes as they see fit

We can't enable/disable the "Create a new release" button based on arbitrary criteria, such as whether or not the package version in the repo is higher than the published version. What we _can_ do is control what gets approval to merge. This can let us ensure that a release can be tagged for whatever is in `master` at any point, and the published package will have a version corresponding to the generated release notes.

---

Yarn has [deferred versioning](https://yarnpkg.com/features/release-workflow#deferred-versioning) which looks interesting. Here is one possible workflow from development to publishing:

1. Apply label (`breaking`, `enhancement`, or `fix`) to PR
2. CI runs [`yarn version [major|minor|patch] --deferred`](https://yarnpkg.com/cli/version) based on label
    - Runs in correct packages based on changes
    - Commits to branch
3. Special PR comment (i.e. :shipit: ) can be used to trigger `yarn version apply` in CI
    - Similar to a [Lyft tool](https://increment.com/development/what-its-like-to-be-a-developer-at/)
    > We built a tool called submitqueue, which manages the submission, revert, and testing of pull requests via a number of different emoji commands in the pull request comment section.
    - Maybe this leaves a comment on the PR with the new version number for publishing
4. Merge PR
5. Create release, matching release tag to `version` in `packages/cores/package.json`
6. Release triggers publish

_Steps 3, 5, and 6 could be left out when developing a PR which won't be used for immediate publishing_

This would shift the responsibility of micromanaging multiple package versions into CI and would leave the important decisions in the hands of humans:

- What kind of change am I making?
- Do I want to publish a new version with this change?

The only chore work remaining would be making sure that the release tag matches the package version. We could make this even easier by having step 3 leave a PR comment with a tag that can be copy-pasted.

### Advantages

- Less chore work
- No need to update at least two manifest files for publishing
- SemVer version number will always correspond to the developer's intent (due to labeling)

### Cons

- Upfront development work in CI
- Undoing or handling mistakes may require manual intervention
    - If the CI has appropriate handling, this might not be an issue
- Contributors would need to know workflow
    -  GitHub action requiring a label (`fix`, `docs`, `enhancement`, etc) on PRs could help
    - `CONTRIBUTING` doc could contain instructions on how to automatically trigger appropriate version updates
    - Requiring workflow knowledge isn't really any different from what we currently have, but I still want to call it out

**Comment by bkjohnson** [comment]
Another idea is to have CI manage a constantly updated `next` draft release. A rough outline of how this might go:

1. anytime `master` is updated, check for the presence of a `next` draft release
    - If it exists, re-generate the release notes and update the git ref
    - If it doesn't exist, create it
 
We would likely need to account for the possibility of accidentally publishing a release with the `next` tag. We could modify the action for publishing so that it fails if the triggering release had a tag other than the `vX.Y.Z` format.

The idea behind this is that a user could just click on the draft release and click "Publish" when ready.

**Comment by bkjohnson** [comment]
Action items from the meeting were:

1. A ticket for a Github Action requiring PRs to have certain labels
    - i.e. `major`, `minor`, `patch` or `ignore-for-release`
1. A ticket for adding the [`yarn version` plugin](https://yarnpkg.com/cli/version) and updating README documentation with how to use it
1. A ticket for adding a script to appropriately increment the version in the right packages when we're ready to publish
