### ISSUE TITLE
QA Feedback - Staging Review - Decision Tools - Find a VA Form PDF Download Instructions (modal)

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#33341]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/33134

Thanks for using TestRail! Only one small point of feedback.

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
None

**Consider:**
- According to [this test case](https://dsvavsp.testrail.io/index.php?/tests/view/312075&group_by=cases:section_id&group_order=asc&group_id=3025), the modal will not appear a second time within 24 hours. Determine if this timeframe is acceptable UX.

**Comment by MarciMcGuireGCIO** [comment]
Thank you, @ddzz !  This is a good call out, and it is acceptable behavior.  Our intent was to show the modal only one time in 24 hours due to its disruptive and obtrusive nature.  The use of a modal was a last-ditch effort to address technical issues with the PDFs themselves, and was not our first choice.  Unfortunately, all other inline options we tested with users were almost universally disregarded.
