### ISSUE TITLE
[UX] Determine content of shortened url

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#33449]
UX to work with IA (Mikki Northius) to confirm content of shortened url. Follow-up with Stephen to get context for the IA meeting.

Acceptance Criteria:
- [ ] Recommendation on what the URL structure actually looks like.

**Comment by sarahknoppA6** [comment]
Nira to propose to Mikki what we'd like to do and go from there.

**Comment by sarahknoppA6** [comment]
@jparker0425 can you add the collab cycle ticket reference here so we can ensure that ticket is updated with any takeaways?

**Comment by niradatta1** [comment]
@mnorthuis Hi Mikki, The check-in team is planning on creating a URL shortener, that we'll initially use in the SMS text that goes out to veterans to check-in. Other teams are also interested in leveraging this shorterner. 

We'd like to ensure the shorterner at least has "va.gov", since user research shows  veterans wanting assurance that the link is legitimate and from the VA. So the shorterner could be as follows:  
 "va.gov/u/r". 

Do you have any recommendations on what content should come after  "va.gov/"? I haven't seen any standards around this based on a quick competitive analysis I've done. Thank you! 'cc @kristenmcconnell

**Comment by mnorthuis** [comment]
This is great and much needed! I am happy to help in any way I can.  

This isn't something that I've put a lot of time and thought into, but I do agree we should definitely leverage "va.gov".   

Some questions/thoughts off the top of my head as we start to look into it:
-  in regards to url structure:
  - do we need to utilize a sub-domain (i.e. m.va.gov, go.va.gov, app.va.gov, etc)
  - do we need sub-directories to separate the types of emails that may utilize the shortener (i.e. appointment check-in uses va.gov/a/e8th7 while a campaign may use va.gov/c/e8th7)
  - do we just want to use a random character string or do we want to set a pattern for specific use cases
- will the shortener be used as just a redirect or will each unique short url actually house content?
- what are the different applications of this (in the short term at least)
- what tracking is needed

**Comment by jparker0425** [comment]
Collab Cycle ticket for the dev work can be referenced [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33988).

**Comment by kristenmcconnell** [comment]
@acrollet Wanted to bring you in to help answer some of Mikki's questions.

**Comment by acrollet** [comment]
Hi @mnorthuis thanks for the response! Answers inline below:

> do we need to utilize a sub-domain (i.e. m.va.gov, go.va.gov, app.va.gov, etc)

The idea scenario right now is to use www.va.gov, in order to be able to leverage existing infrastructure. (Specifically, the reverse proxy)

> do we need sub-directories to separate the types of emails that may utilize the shortener (i.e. appointment check-in uses va.gov/a/e8th7 while a campaign may use va.gov/c/e8th7)

I don't know of any need for separate subdirectories at this time, I'd suggest that we settle on a single sub-dir (perhaps `/u/`) for simplicity and re-visit if and when it's necessary.

> do we just want to use a random character string or do we want to set a pattern for specific use cases

For now let's assume that we're using strings of random characters, probably deliberately excluding known words to avoid confusion and/or potential offense. I believe this should simplify both implementation and review.

> will the shortener be used as just a redirect or will each unique short url actually house content?

Redirects only.

> what are the different applications of this (in the short term at least)

In the short term, the single application is to shorten long URLs (e.g. `https://www.va.gov/health-care/appointement-check-in/?id=a46cc0ae-f3a5-4305-af90-4d26b34f97ba`) for mobile check-in applications. These links are sent via SMS, so it's important for readability and reduced costs to veterans.

> what tracking is needed

I can't speak to this from an SEO perspective, but from a technical perspective we'll need to have logging and alerting in place to ensure that the service is reliable and any issues reported can be efficiently investigated.

**Comment by mnorthuis** [comment]
A couple of follow ups...

> I don't know of any need for separate subdirectories at this time, I'd suggest that we settle on a single sub-dir (perhaps /u/) for simplicity and re-visit if and when it's necessary.

Is there a significance/meaning to using /u/?  Just trying to understand what the "u" stands for.  Also, if a sub-directory is utilized, a redirect will need to be put in place at the directory level.  In addition appropriate redirects should be put in place for an invalid or expired character string.  

> In the short term, the single application is to shorten long URLs (e.g. https://www.va.gov/health-care/appointement-check-in/?id=a46cc0ae-f3a5-4305-af90-4d26b34f97ba) for mobile check-in applications. These links are sent via SMS, so it's important for readability and reduced costs to veterans.

By this, I am assuming that the single application is for appointment URLs, not any long URL.  There are other potential applications for this shortener but I want to be careful before we allow use of it for anything, as the format and tracking needs may differ.  So can we keep the scope to the long parameter-based URLs used in appointment check-ins?  Or do you feel there are more needs than that?

> I can't speak to this from an SEO perspective, but from a technical perspective we'll need to have logging and alerting in place to ensure that the service is reliable and any issues reported can be efficiently investigated.

The tracking I was asking about was not for SEO, but analytics and general user/click-through tracking.  Do you need to track all shortened URLs in play?  Do you need a process by which you can look them up, retire them, re-use them, etc?  Any look-ups, management of, or activity tracking needed will need to be part of of your solution.  These URLs should not play into SEO at all.

**Comment by acrollet** [comment]
> A couple of follow ups...
> 
> Is there a significance/meaning to using /u/? Just trying to understand what the "u" stands for.

No particular significance, I think it was first suggested by @stephenBarrs - probably standing for "Url". :-)

> Also, if a sub-directory is utilized, a redirect will need to be put in place at the directory level.

To clarify, you're saying a re-direct would need to be put in place from `/u/` to the root?

> In addition appropriate redirects should be put in place for an invalid or expired character string.

So you would want the shortener service to return a redirect to the homepage instead of a 404 if a person visited an invalid URL?

> > In the short term, the single application is to shorten long URLs (e.g. https://www.va.gov/health-care/appointement-check-in/?id=a46cc0ae-f3a5-4305-af90-4d26b34f97ba) for mobile check-in applications. These links are sent via SMS, so it's important for readability and reduced costs to veterans.
> 
> By this, I am assuming that the single application is for appointment URLs, not any long URL. There are other potential applications for this shortener but I want to be careful before we allow use of it for anything, as the format and tracking needs may differ. So can we keep the scope to the long parameter-based URLs used in appointment check-ins? Or do you feel there are more needs than that?

Our current need is for these long URLs that are used for check-in and (soon) pre-check-in. If other teams have a need for this functionality it would probably be good to discuss if it could become a platform service at that time.

> > I can't speak to this from an SEO perspective, but from a technical perspective we'll need to have logging and alerting in place to ensure that the service is reliable and any issues reported can be efficiently investigated.
> 
> The tracking I was asking about was not for SEO, but analytics and general user/click-through tracking. Do you need to track all shortened URLs in play? Do you need a process by which you can look them up, retire them, re-use them, etc? Any look-ups, management of, or activity tracking needed will need to be part of of your solution. These URLs should not play into SEO at all.

At this time we view it as a solution for short-lived ephemeral shortened URL redirects. There should be no need for lookups or re-use and they will be expired as the links they point to expire.

Thanks!

**Comment by acrollet** [comment]
Hi @mnorthuis, just doing a post-holiday ping to check on the status of this and see if you have other questions or follow-ups 🙂 Thanks!

cc @jparker0425

**Comment by mnorthuis** [comment]
Hi!  Just a recap based on the back and forth above or where I believe we landed:

- this initial solution will only apply to the appointment URLs used for the check-in and pre-check-in scenarios.  This solution will need to be reviewed for necessarily modifications to support any other use case or VA product.  
- We will utilize a sub-directory structure for these short URLs that includes a single character sub-directory and a unique random character set:  www.va.gov/a/xxxxxx
  - I picked "a" for appointments, but we could use "h" for health as well, or something else.  
- We will want to avoid users getting the generic 404 when possible
  - users trying to view the base sub-directory `www.va.gov/a/` should be redirected to either the home page or a custom error page.
  - users trying to access an invalid/expired short URL should be either redirected to the home page or a custom error page. 
- These shortened URLs should not be tagged or included in analytics
- These shortened URLs should not be indexed

**Comment by acrollet** [comment]
@mnorthuis thanks for this!

@kristenmcconnell @niradatta1 do you have any preference on using `/a/`, '/h/` or another prefix for shortened URLs? Also, do we want to redirect to the home page or show a custom error page for invalid/expired short URLs? (Maybe we need to spin off an issue or two, not sure)

I've updated [the design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/url-shortener/design-doc.md) to include the requirements re: analytics & indexing

**Comment by kristenmcconnell** [comment]
I don't have a strong preference on the prefix. My only thinking is that there could be other things that are health-related that might match better with /h/ in the future. What about /c/ for check-in?

I think we should let the user know that it is an invalid/expired short URL. I could see a Veteran being very confused/trying to navigate around if we place them on the homepage. @julieadair1 We will need tickets (UX and engineering) to craft the error wording and implement the invalid/expired short URL.

**Comment by kristenmcconnell** [comment]
I created this [ticket](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/34960). 

@acrollet  Let me know when the design doc is updated with the /c/ prefix, then I think we can close out this ticekt.

**Comment by acrollet** [comment]
@kristenmcconnell done! Closing this issue.
