### ISSUE TITLE
Investigate spinner times on unified sign in page

### ISSUE THREAD

**Issue by Kwoly** [department-of-veterans-affairs/va.gov-team#33474]
# Description
Spinner times on the unified sign-in page feel excessive.  This work is to investigate ways to improve them.

# User Story
**As a** VA.gov user
**I want** to not experience excessive loading/waiting on the sign-in page
**So that** I can more quickly access the services I need

# Acceptance Criteria
- [ ] Causes of excessive spinner times identitifed
- [ ] Tickets created to improve spinner times

**Comment by nsoutouras** [comment]
Nick: Add template.

**Comment by Kwoly** [comment]
The way the vets-website is built, it that it stitches together numerous react applications via webpack and routing. When navigating the site, we use a "spinner" (loading indicator) when switching from one "application" to another. 

Since `/sign-in` route is the entry point to the `SignInApp` application, we will always see this spinner icon when navigation to it. This is actually a good thing as it provides the user a sense of progress being made vs seeing a white screen while the application is loaded.

I have tested on multiple devices, and network speeds (chrome throttling) and have resolved the spinner in 2 seconds or under for speeds 4g and higher.

3G throttle resolved the spinner in ~4s.

Closing this as a non-issue for now as it's working as intended and the speeds seem inline with standards

**Comment by codyreinold-usds** [comment]
@Kwoly How would we move the experience closer to a static page / completely remove the spinner. I ask because the VA.gov homepage is arguably a similar experience--a largely static experience that still renders _some_ elements dynamically.

I ask because this isn't on-par with other private sector experiences. If I visit similar sign in pages (eg: Google, Amazon, etc.), I receive an instantly rendered sign in page--not a react app that takes ~2 seconds to load. Google's sign in experience tends to render in the 500-600ms range, whereas we tend to be in the 1500-2000ms range. While I don't expect we'll be able to match Google's performance, I'd like us to dive a bit deeper into this!

I'd like us to tear apart what is causing the bloat and identify:
- Break down the page load, identifying bottlenecks, render blocking resources, etc.
- Are there potential areas for improvement within **our** app / codebase / how we're rendering our experience
- Are there potential areas for improvement within the **platform** / across VA.gov (and vets-website)

I think this would be a learning experience for our team, as well as an opportunity to _potentially_ give back to the platform overall! (Although I know you guys are already incredible team players re: assisting other teams)

Would love to hear thoughts / recommendations.

(cc @nsoutouras @joeniquette for situational awareness)

**Comment by Kwoly** [comment]
@codyreinold-usds I can do a little more investigation into this, however, here are some findings from a little bit of performance testing I did last night.

throttling on chrome devtools `3G`

va.gov is roughly 2s slower to load than va.gov/sign-in. It appears faster since it does not have a loading spinner. Without that spinner, we are able to see a pretty quick first paint of the site, then over the course of the next 10 seconds we are seeing elements pop in as they load.

While va.gov/sign-in finishes loading in 8 seconds we hide the first paint, and the "popping in" of elements behind the loading screen so when we do render, we are fully interact-able.

I think the undesirable effect we would get if we just removed the spinner, is a quick first paint of the buttons, but the page may still be parsing javascript to check for AutoSSO Logins, and other logic which could render the elements non interactive.

I am curious though, what sort of network speed you are on, as I have to throttle pretty hard for the page to load to be > 2s

**Comment by Kwoly** [comment]
I think we have 2 potential courses of action to take here:

1. This is probably a little more on the feasible side, but provides fewer improvements than the 2nd option. This option revolves around keeping the `authentication` components within the `vets-website` repository as they live today and working on removing as much "bloat" as possible to reduce the load time of the `sign-in` page. This would involve researching the possible ways to move the `sign-in` page components to the initial application load as to avoid the "spinning" icon altogether.

2. This option is a bit more extreme but in an ideal world, it's the route I would take. We would split authentication components out of `vets-website` altogether, and set up our own repository. This would allow us to use some later technologies like Next.js which can take advantage of SSR (server-side rendering). This would also allow us to create the experience with only the necessary dependencies, thus creating the fastest experience. 

With option 1, we can start on this immediately, and not be blocked by anything. I think there are some gains we can achieve here, but we still have to adhere to the global rules of `vets-website`.

With option 2, we control our own destiny as we will set everything up from scratch, utilizing newer technologies, and have a much smaller bundle size to deliver. This will provide greater results than option 1, but comes packaged with a lot of overhead and some caveats:

- We will have to set up a new repository and migrate all the existing authentication code over
- We will need to create an npm package that delivers the `LoginContainer` component and logic so that `vets-website` can import and render the auth experience in modal
- This NPM package would also need to deliver the `AutoSSO` component and logic
- We would need to set up a new build process and have our standalone sign-in page built and hosted somewhere. This would also require ensuring that `va.gov/sign-in` had a reverse proxy set up to our newly hosted sign-in page. This would require a lot of setup and support from external teams. (I don't think the Identity team has the rights to do all of this?)

**Comment by Kwoly** [comment]
@codyreinold-usds Let me know your thoughts on this latest comment.
