### ISSUE TITLE
Draft documentation for Bold text on headings 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#33746]
## Issue Description
During the 2/5 DSC meeting, Trevor had raised the topic of bold text turning into HTML on scheduling cards. The DST has been tasked with doing an audit of this pattern and draft guidelines. 

Link to #19301 has more information. 
Bold text on headings must be consistently marked up as headings
https://github.com/department-of-veterans-affairs/va.gov-team/issues/19301

There is also a Slack conversation about this that Ryan shared. 
 https://dsva.slack.com/archives/C0FQSS30V/p1611085952085600

---
## Tasks
- [ ] Draft Documentation related to guidance of how to use headings. What is or isn’t a heading. 

## Acceptance Criteria
- [ ] Documentation on how and when to use headings. 

---

**Comment by GnatalieH** [comment]
The [audit portion of this work](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19573) is for the current sprint. I didn't realize this ticket was also for the current sprint, as I thought the documentation would follow the audit in the next sprint. I'll need to work with @CourtneyChambers77 on this too.

**Comment by CourtneyChambers77** [comment]
Using accessibility for the content, I recommend using semantic markup to properly announce style changes to all users. Bold and italics are often used to highlight words or phrases in a paragraph of text. The Strong tag, <strong>, and the Emphasis tag, <em>, are considered Semantic Markup that allows for added meaning to your content.  It serves as an indication to the screen reader (SR) of how something should be understood. When using bolded in a piece of text using the <b> tag, it will come to no benefit for users using screen readers. This is especially critical when the tag helps to convey special meaning for the words or phrases being highlighted. Content editors may be using the bold tags (<b>) in place of a heading tag (<h1>) thinking it will be conveyed to all users. But as we have identified, bold tags are not announced to screen reader users. Additionally, heading tags are an essential way for screen reader users to scan a page. Using short-cut keys, the screen reader would read all the headings on the page so that the user can navigate quickly to areas of need or interest. Avoid from using style tags such as <b> and <i>. Use semantic tags <strong> and <em> (italics). Use heading levels to break up content and make it more scannable

**Comment by GnatalieH** [comment]
@caw310 I spoke with Beth Potts last week and she confirmed that these usage guidelines on headings vs. bold text should live in the Content style guide, and should also be included when I publish the Cards Pattern. I'm going to meet with Randi Hecht tomorrow about this (she was out last week). Can I close this ticket? Should I create a new ticket to capture my work collaborating with Randi? Thanks.

**Comment by caw310** [comment]
I would say capture work here since it is related.

**Comment by GnatalieH** [comment]
I met with @RLHecht this morning to discuss how we'll incorporate these bold text usage guidelines into our documentation. Starting in the Content style guide, Randi will add a bullet point (related to accessibility considerations) to the Bold text entry. When I publish the Cards pattern, I'll also include the bold text guidelines. The Content style guide Bold text entry will crosslink to the Cards entry in Patterns.
