### ISSUE TITLE
Refactor GitHub Actions report jobs by creating reusable actions

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#33795]
## Issue Description
GitHub actions testing reports actions can be broken down into reusable actions to avoid repetitive steps and eliminate many lines of code in workflow files that are quite bloated

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by CBonade** [comment]
So far I was able to condense two repeat groups of steps into composite actions:

1) The checkout and dependency install of the dashboard data repo is now a two-line step instead of 20+
2) The step that gets the bigquery service credentials and configures the cloud SDK (always done together) is also now a two-line step instead of ~6-8ish each

Looking for more opportunities for more reductions as we continue down this road. Currently at a 72 line reduction in the workflow file and a much easier to read set of steps.

**Comment by CBonade** [comment]
This is in for review with code owners.

**Comment by CBonade** [comment]
Merged and done!

**Comment by pjhill** [comment]
Hurray, thanks for this!
