### ISSUE TITLE
COVID-19 education updates

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#33809]
We need to reach out to education SME to connect on current and upcoming COVID-19-related updates for https://www.va.gov/coronavirus-veteran-frequently-asked-questions/:

**Current immediate update:** We received notice that there's been an update around needing to be in person for GI Bill benefits. I'm not 100% clear on what the update is. The team needs to reach out to the education SME to get full clarity and then we can make needed update(s).

**The special COVID-19 rules for education benefits end on December 21, 2021.** We'll need to rework or remove related content. We should ask education SME about whether they are expecting any potential extensions and, if not, how they are planning to update their content at https://www.benefits.va.gov/GIBILL/COVID19EducationBenefits.asp so we can align in our updates.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here is the response back from stakeholders on the in-person question:

The special COVID-19 provisions enacted through the Student Veteran Coronavirus Response Act of 2020 and extended by the Isakson and Roe Veterans Health Care and Benefits Improvement Act of 2020 are set to end on December 21, 2021. Once these provisions expire, students will no longer receive the Monthly Housing Allowance (MHA) at the resident (in person) rate for classes taken online. When enrolling for courses after that date or any subsequent term, students will need to enroll in approved resident (in person) classes to continue receiving MHA at the resident rate. Otherwise, they will receive the online rate (half the national average).

And here is her response for the December 21 date:

The content on our Student COVID-19 FAQs currently reflects the impending, December 21, 2021, expiration date. However, we are aware that these provisions may be extended through June 1, 2021 if H.R.5545 - REMOTE Act is passed.

Do you want us to take a look at the current language on the page and make edits for you to review? It sounds like we should hold off on doing anything on the December 21 date for now but I can ask when they think they might know more about whether this gets extended to June 1.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Here is the new language Selina and I worked on for the FAQ accordion "What happens to my GI Bill benefits if my school changes to online classes or temporarily closes?"

**If your school changes to online classes**

If you’re currently receiving GI Bill benefits, payments will continue automatically. You don’t have to do anything. 

To help students affected by the COVID-19 pandemic, we paid in-person (called “resident”) monthly housing allowance rates if you were enrolled in online classes from March 1, 2020, to December 21, 2021. As of **December 22, 2021**, your monthly housing allowance payments will change back to the online rate.

We’re working closely with schools to ensure enrollments are accurately certified and processed.

Let us know if we should send this to the stakeholders for approval.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Yes, please send - thank you! I just added a sentence about the online rate being half the national average. If we can include the actual rate, that's even better. 

**If your school changes to online classes**

If you’re currently receiving GI Bill benefits, payments will continue automatically. You don’t have to do anything.

To help students affected by the COVID-19 pandemic, we paid in-person (called “resident”) monthly housing allowance rates if you were enrolled in online classes from March 1, 2020, to December 21, 2021. As of December 22, 2021, your monthly housing allowance payments will change back to the online rate. The online rate is half the national average.

We’re working closely with schools to ensure enrollments are accurately certified and processed.

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Based on the new information the stakeholder sent us this morning we updated this text. We would change the accordion question to the following:

What happens to my GI Bill benefits if I take online classes or my school temporarily closes?

Then we reworked the first subhead and information in it to the following:

**If you’re taking online classes**

**If your school offers approved online classes,** you’ll continue receiving GI Bill benefits automatically. You don’t have to do anything. 

**If your school doesn’t offer approved online classes,** you’ll need to return to in-person classes to continue receiving GI Bill benefits. This begins on **December 22, 2021**.

To help students affected by the COVID-19 pandemic, we paid in-person (called “resident”) monthly housing allowance rates if you were enrolled in online classes from March 1, 2020, to December 21, 2021. As of **December 22, 2021**, your monthly housing allowance payments will change back to the online rate. The online rate is half the national average.

We’re working closely with schools to ensure enrollments are accurately certified and processed.


If this looks good to you, I'll send it back to the stakeholder.

**Comment by DanielleThierryUSDSVA** [comment]
@RLHecht Awesome! Thanks so much for staying on top of this!

**Comment by RLHecht** [comment]
Now that the REMOTE law was signed, in-person rates are being extended until June 1, 2022. We updated the date on the FAQs page in all three languages. Moving to validate and will close once live. I'll make a note in the editorial calendar to revisit this before June 1.

**Comment by RLHecht** [comment]
Changes are live. Closing ticket.
