### ISSUE TITLE
Community Care Latency issues

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3381]
## Problem
High latency/search performance: Users have reported that when they try to search on Community Care that it could take anywhere up to 2 minutes to return data.

## High Level Background
- The community Care Facility Locator is the only FL that stores and retrieves data from the PPMS database.
- PPMS database (Cosmos) is relational dynamic db which was never intended to be geographical search
There are a few fields that do not get returned in the first call to PPMS, such as phone number, address and services. In order to get that information, a second call is made for every result they get up to 20. The second call gets the additional information and adds it to the record before returning it to the front end.

## Task
Recommend options for improving PPMS/Community Care search performance. These recommendations should also be informed by the following: 
- Please review the information found in [#2742] to evaluate if reducing the search parameters might improve performance 
- Findings from investigation of Data discrepancies in [3051](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/3051)
-  Findings from investigation of the data organization in [3095](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1961)

**Comment by mmiddaugh** [comment]
Will address with Microsoft

**Comment by davidconlon** [comment]
Part of the issue here relates to the density of providers coming out of PPMS.  
So the speed performance, as it stands now, is not based upon distance alone, but based upon the number of providers within a given distance.

e.g. If you search for a Community Care provider within a 80-like radius around an urban center (like Washington DC) will perform significantly slower than if the same search is conducted with the same distance parameters around a rural area (like Moab, UT)
