### ISSUE TITLE
Update link for VAMCs

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#3385]
## User Story
- As a Veteran using the Facility Locator, I need to be directed to the new VAMC pages so that I have access to complete and accurate information for the facility I have chosen.
- As the Facility Locator team, I need the process to be sustainable so that manual effort is not required each time a new set of VAMC pages is launched. 

## Task 
- Replace link to facility detail pages for Pittsburgh and 7 associated locations with new VAMC urls

**Anticipated timing:** December 1, 2019

## Acceptance criteria:
- When University Drive (vha_646) is selected from the search results, the user should be directed to https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

- When H. John Heinz III (vha_646A4) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

- When Beaver County Clinic (vha_646GC)is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

- When Belmont County Clinic (vha_646GA) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

- When Fayette County Clinic (vha_646GE) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic

- When Washington County Clinic (vha_646GD) is selected from the search results, the user should be directed to:-> https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic

- When Westmoreland County Clinic (vha_646GB) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic

- Existing interstitial pages for each facility will no longer be part of the workflow from the search results page.

**Comment by davidconlon** [comment]
I believe this is going to be done by the Facilities API & Dave Mazik's team automagically but we should monitor.

**Comment by davidconlon** [comment]
I just checked with @andrewlewandowski The link on the facility detail page is what we get from the Facilities API. We **do** need to change the link on the facility locator map results page when Pittsburg and the locations go live and retire the facility detail page in lieu of the new facility pages

1. **University Drive**: https://www.va.gov/find-locations/facility/vha_646 ->  https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

2. **H. John Heinz III**:  https://www.va.gov/find-locations/facility/vha_646A4 -> https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

3. **Beaver County Clinic**: https://www.va.gov/find-locations/facility/vha_646GC -> https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

4. **Belmont County Clinic**: https://www.va.gov/find-locations/facility/vha_646GA -> https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

5. **Fayette County Clinic**: https://www.va.gov/find-locations/facility/vha_646GE -> https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic 

6. **Washington County Clinic**: https://www.va.gov/find-locations/facility/vha_646GD -> https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic  

7. **Westmoreland County Clinic**: https://www.va.gov/find-locations/facility/vha_646GB -> https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic

**Comment by mmiddaugh** [comment]
[Process for requesting redirects](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/request-redirect.md) 
- Simple ticket request assigned to Mikki who will assign back to front-end once the redirect has been vetted 
- Once assigned, it can be slot in a sprint accordingly.

**Comment by jeff2d2** [comment]
For all 7 sites listed above, the website URL being returned by the Facilities API is currently http://www.pittsburgh.va.gov/.

For clarity come launch time, the request will be for us to update the website URLs like so, correct?

1. **University Drive** (vha_646): http://www.pittsburgh.va.gov -> https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

1. **H. John Heinz III** (vha_646A4): http://www.pittsburgh.va.gov -> https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

1. **Beaver County Clinic** (vha_646GC): http://www.pittsburgh.va.gov-> https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

1. **Belmont County Clinic** (vha_646GA): http://www.pittsburgh.va.gov -> https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

1. **Fayette County Clinic** (vha_646GE): http://www.pittsburgh.va.gov-> https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic

1. **Washington County Clinic** (vha_646GD): http://www.pittsburgh.va.gov-> https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic

1. **Westmoreland County Clinic** (vha_646GB): http://www.pittsburgh.va.gov-> https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic

**Comment by jeff2d2** [comment]
Got [a draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/3551) going to prepare. Feel free to review!

**Comment by davidconlon** [comment]
On the search results for the following VAMCs, instead of the hyperlink going to a Facility Detail Page, the link should go to the New Facility Page in Drupal.

University Drive (vha_646) -> https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

H. John Heinz III (vha_646A4):  -> https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

Beaver County Clinic (vha_646GC):  -> https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

Belmont County Clinic (vha_646GA): -> https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

Fayette County Clinic (vha_646GE):  -> https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic

Washington County Clinic (vha_646GD): -> https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic

Westmoreland County Clinic (vha_646GB):  -> https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic


We should look to make this a sustainable solution ongoing and, if possible, driven by the changes from Facilities API.

Assumption: none of the existing URLs for Facilities are www.va.gov but instead are SUBDOMAIN.va.gov

if (Facilities API URL does not contain "www.va.gov" ) then use the facility ID and have a facility landing page.  If it DOES have a "www.va.gov" URL then use that URL as the hyperlink and I don't need a Facility landing page

We should look to make this a sustainable solution ongoing and, if possible, driven by the changes from Facilities API.

Assumption: none of the existing URLs for Facilities are www.va.gov but instead are SUBDOMAIN.va.gov

So we can do something like: 
- if the URL for the facility **is not** www.va.gov, then use the facility ID (like wed currently do) and send users to the facility detail page

- if the URL for the facility *is* www.va.gov use the URL in the Facilities API because we *do not* want a Facility Detail Page and instead want to send the user direct to the facility page in Drupal

**Comment by davem-va** [comment]
@davidconlon I think your last response is more for the facility-locator implementation rather than a confirmation response to @jeff2d2, correct?  If Jeff good to go with the API changes he mentioned above?

**Comment by davidconlon** [comment]
Hey @davem-va and @jeff2d2 
Those URLs look correct but we're holding on those until we get the green light from @andrewlewandowski.

This issue is actually tracking what the FL needs to do on our front-end on our search results page that (current state) links to a facility detail page but (future state) will link directly to the VAMC Facility Page from search results as they roll out.

**Comment by mmiddaugh** [comment]
**Acceptance criteria:**
- When University Drive (vha_646) is selected from the search results, the user should be directed to https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/

- When H. John Heinz III (vha_646A4) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/

- When Beaver County Clinic (vha_646GC)is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/beaver-county-va-clinic/

- When Belmont County Clinic (vha_646GA) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/belmont-county-va-clinic/

- When Fayette County Clinic (vha_646GE) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/fayette-county-va-clinic

- When Washington County Clinic (vha_646GD) is selected from the search results, the user should be directed to:-> https://www.va.gov/pittsburgh-health-care/locations/washington-county-va-clinic

- When Westmoreland County Clinic (vha_646GB) is selected from the search results, the user should be directed to: -> https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic

- Existing interstitial pages for each facility will no longer be part of the workflow from the search results page.

**Comment by mmiddaugh** [comment]
Hold for QA effort
