### ISSUE TITLE
"Create ID.me account" link - LOA3 user not returning auto-upgraded

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#33967]
**Description**
When an LOA 3 user clicks the "Create ID.me account" link, and signs in, they are not returned as an LOA3 user.

**User Story**
**As a** VA.gov user 
**I want** to be able to click the "Create an ID.me account link and sign in with my appropriate LOA\
**So that** I can properly utilize VA.gov services

**Notes**
This issue was reported by @codyreinhold-usds.    Full text of report below:

_the "Create an ID.me account" link; when you click it and sign in w/ an LOA3 account, you don't come back as an LOA3 user. the user should come back auto-upgraded with their LOA3 attributes, identical to if they had clicked to sign in w/ id.me. suspect we didn't  update that to send the minimum comparison._

**Comment by nsoutouras** [comment]
Assigning to Joe for delegation.

**Comment by alyssagallion** [comment]
Closing as this is no longer something we need to work on (new PM cleanup). Context: 

Alex Garcia:
This is when a user "Creates an account" and decides to go through the verification process they are returned via LOA1 rather than LOA3.  Although this was created during Cody's time here so I'm not sure if this is even a thing.


Joe Niquette:
We modified all the create account buttons that would normally require they be an LOA3 user to do the verified create call.
