### ISSUE TITLE
Conversations with the CMS content team to understand next steps.

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#3402]
## User Story or Problem Statement

As a VSP Ops, I need understand the solution that the CMS super team recommends so I can we can talk through an appropriate solution for the content deploys.

## Goal
Have a clear understanding of what work needs to be done to unblock the Pittsburgh launch. 

## Acceptance Criteria
- [x] Talk with the CMS team to understand what their approach to the problem is.
- [ ] Review the process and provide feedback to the recommended approach.
- [ ] Work with the team to provide a list of steps to take to ensure we can do a content deploy faster

**Comment by ricetj** [comment]
met with Elijah, speak through some of the problems that need to be addressed with the Deploy section. We came up with maximizing and improving what we currently have to get things in a reasonable timeframe for developments.

**Comment by wyattwalter** [comment]
Had a couple of meetings around this. The primary ask right now is to reduce the release + deploy time by 5 minutes on the pipelines since this'll happen many times a day now instead of the old normal. This is required for the re-launch of the pittsburgh.va.gov work which is currently slated for Dec 10 as a go/no-go.

While Elijah did work through a potential re-architecture that would remove the S3 website hosting bits, we decided to not aim for that longer-term thing on such a short timeline. We can add some pretty dramatic speedups to the existing system without having to rush large architectural discovery/decisions. I'm going to open an epic with our notes and takeaways from that so we can split up this work.
