### ISSUE TITLE
Claim Status Tool - Upload Issue

### ISSUE THREAD

**Issue by vhenry07** [department-of-veterans-affairs/va.gov-team#34032]
## Issue Description
As a Veteran, I would like to be able to upload documents/evidence in connection with my claim. 

---
## Tasks
- [x] Investigate error uncovered during research. Veterans click on "upload documents" and nothing happens

## Acceptance Criteria
- [x] Issue documented. Create additional tickets as needed for resolution tasks.
---

**Comment by cnemeth** [comment]
Could not duplicate/find error, therefore, concluding investigation.

## Investigation results

### Production logs

Searched production log (Grafana/Loki) for HTTP error codes returned by the `POST /v0/upload_supporting_evidence` API endpoint. This endpoint returns either a `400 (bad request)` or a `422 (un-processable entity)` error code in conjunction with some other status codes, e.g., `225 (signal interruption)`.  Mostly found `422` errors in conjunction with `225`, which means the upload could not be performed because of service interruption.

### Test uploading supporting evidence in `staging`

2. Successfully uploaded multiple files (PDF, jpg) as supporting evidence to an in-progress application for user `vets.gov.user+228@gmail.com` in staging. There were no error codes  in the logs (see attached screenshot).
<img width="569" alt="Screen Shot 2022-01-07 at 11 20 39 AM" src="https://user-images.githubusercontent.com/138761/148817483-817a332b-674f-4f1d-85a5-b2b93078798d.png">
