### ISSUE TITLE
[UX] Add/Edit Demographics

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#34087]
As a veteran I need to be able to add or edit demographic information when I am checking in so that I can ensure VA has the most up to date information. 

Tasks
- [x] Design wireframes - UX can be worked on.
- [x] The whole pattern of editing profile information in a workflow needs to be reviewed design system team (including accessibility).
- [x] Sync with profile on mailing/home address syncing pattern (since they are working on this, it is out of scope for us for this ticket)

Acceptance Criteria
- [x] Post to Sketch Cloud

**Comment by kristenmcconnell** [comment]
The profile team is working on a solution to get users to review both their mailing address and home address (if they don't check the box to apply changes to both). Liz Lantz is taking the following proposal to content tomorrow: https://app.mural.co/t/vsa8243/m/vsa8243/1639511492636/a7d05e80d5289ba70da1cd6f7b99fb8f7bf3276f?sender=uc940f53ad96ac0203d6d3631

**Comment by kristenmcconnell** [comment]
[Information on a similar pattern done on the Claims and Appeals team. ](https://dsva.slack.com/archives/C02GXKL8WM6/p1638303129266000)

**Comment by kristenmcconnell** [comment]
Draft wireframes: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/p/5BCAB931-5EBD-4208-BDA4-592B768DE26F

**Comment by kristenmcconnell** [comment]
Slack thread requesting feedback and providing some information from profile team: https://dsva.slack.com/archives/C022AC2STBM/p1640186272410000

**Comment by kristenmcconnell** [comment]
Due to timing, I think the review of the final edit pattern with accessibility and the design system should take place within #31808. @jparker0425 @julieadair1 Thoughts?

**Comment by kristenmcconnell** [comment]
Reviewed designs with the UX team on Dec. 23. Here are a few decisions made at the Check-in UX team meeting...

- Due to accessibility and limiting number of font styles, we are going to format the labels (such as "Mailing address") as bold body text. If it is bold body copy, then a screen reader will read the entire block of contact information together.
- We are going to leave the "home address same as my mailing address" the same as the current profile design. We will revisit following profile's research study.

I also don't know what form field are required for editing Next of Kin. Will write a separate story to add this required questions as well as review design one final time with the content and accessibility.
