### ISSUE TITLE
Collaboration Cycle Kickoff eBenefits, Specially Adapted Housing Grant

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#34092]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [ ] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-apply-SAHG/README.md)
- Wireframes, [mockups](https://www.sketch.com/s/f0ac7ad9-03cf-49c4-b2a8-9fb85a88b31a/a/eKJnozj), or prototypes
- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes: new form
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [x] New
- [ ] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: ____________

### 4. Are you making changes to the visual design?
- [ ] Yes
- [x] No

### 5. Are you doing research with VA.gov users?
- [x] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [ ] Static pages
- [x] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [ ] New content
- [x] Changes to existing content: need to update [some existing pages](https://www.va.gov/housing-assistance/disability-housing-grants/how-to-apply/) to reflect migration

### 8. Are you making a change to the user flow?
- [x] Yes: moving from eBenefits to VA.gov
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [x] Yes: moving from eBenefits to VA.gov
- [ ] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [x] Yes: it will 
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No: don't think so

### 12. Does your team have a Github label for this product?

- [ ] No. 
- [x] Yes. Please specify: `SAHG`

### 13. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [x] Other. Please specify: LGY | Specially Adapted Housing

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.

**Comment by chaseakirby** [comment]
Hi @jason-gcio. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is a new tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
- [Research Plan Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)
- [Analytics Request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
- [Contact Center Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [Privacy, Security, Infrastructure Readiness Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

Post Launch: 

- [Full Accessibility and 508 Office Audit](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html)
- [Post-launch Check-in](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Post-launch-check-in.1781956691.html)

Since your work impacts static pages, please reach out to Dave Conlon to review how your work may overlap with any existing work. This will help them prioritize and identify possible areas of support needed from other teams. 

We recommend that you bring the tool/application and static pages through the Collaboration Cycle together so we can review the full flow/user experience.

Please reach out to Dave Conlon to let him know your work will impact static pages, the nature of the work, and your projected timeline.

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

**Comment by jason-gcio** [comment]
Re: the static page(s) - will do...the top of funnel landing page looks to be in mostly good shape so I doubt we will have a ton to request there although we will most likely look for a feature toggle for the button to come back from EBN to VA.gov.  This will be a ways out but its on our radar to get some guidance on that when we get there.  Thanks @chaseakirby!
(cc: @davidconlon)
