### ISSUE TITLE
[Content organization] Long or complex sections of content aren't broken up into content chunks or bulleted lists. (02.05.1)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#34172]
#### VFS team name
Debt Resolution

#### VFS product name
Medical Copays (MCP)

#### Point of Contact/Reviewers
Jim Ryan (@jimuhh) - IA

---

### Platform Issue
Long or complex sections of content aren't broken up into content chunks or bulleted lists.

### Issue Details
On Copay Balances page, copay name, facility name and location are all on the same wrapping line, not "chunked" as per card design pattern best practices

### Link, screenshot or steps to recreate
https://d.pr/i/3zKH85

### VA.gov Experience Standard
[Category Number 02, Issue Number 05](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/VA.gov-experience-standards.1683980311.html)

### Other References
WCAG SC 3.1

---

### Platform Recommendation
If possible, consider turning those three chunks of info into semantically distinct headings. Also, if possible, consider adding date of service to copay summary

### VFS Team Tasks to Complete

- [ ] Comment on the ticket if there are questions or concerns
- [ ] Close the ticket when the issue has been resolved or validated by your Product Owner. If a team has additional questions or needs Platform help validating the issue, please comment in the ticket.

**Comment by denisecoveyduc** [comment]
@jimuhh We worked with Accessibility @joshkimux @AngelaFowler82 who recommended we write the information in this way. Let us know which way we should go. Thanks

**Comment by joshkimux** [comment]
More than happy to sync with you here @jimuhh -- in order for these headings to be semantically unique, they need to contain information of the price _and_ the location (as there can be multiple receipts per location). The compromise we ended up reaching was a heading that contains the price with a subtitle (location) that is connected to the heading via an `aria-describedby`

**Comment by denisecoveyduc** [comment]
@joshkimux @jimuhh Just checking in to see if you had a chance to sync up on this one? wondering if there is work here for the debt team or how we should proceed?

**Comment by joshkimux** [comment]
@denisecoveyduc I haven't had the chance to sync with Jim yet (I've recently returned from a long PTO), but have just reached out to him to get synced up! I think we can find a compromise to meet both IA and a11y requirements in the middle and will keep you posted with updates as soon as we meet! 🙇

**Comment by denisecoveyduc** [comment]
Not a problem at all! Just wanted to follow up so we don't loose sight of it. Thanks so much @joshkimux 🙂

**Comment by jimuhh** [comment]
@denisecoveyduc Thanks for keeping on this. Josh and I are planning to talk and I'm sure we can work something out.

**Comment by joshkimux** [comment]
@denisecoveyduc , @jimuhh and @AngelaFowler82 got synced up to remember the original context of the ticket and the changes that were made ahead of the holiday season. 

We agreed we could close out this ticket by simply removing the "Copay balance for..." string ahead of the name of the facility.

<img width="691" alt="Screen Shot 2022-01-21 at 11 38 48 AM" src="https://user-images.githubusercontent.com/14154792/150565687-c7d0f637-4049-4435-b377-ddfa43cb9923.png">

Reasons behind this were:

- Headings are no longer links, so they no longer need to include purpose + target in an isolated context
- The `h1` and the `title` (which are announced when user's navigate to the page) both explicitly state this is for copay balances specifically
- Removing "Copay balance for..." accomplishes @jimuhh 's goal of reducing complex sections of content

@rileyorr apologies ahead of time if my goldfish memory forgot any other important design decisions here that would argue otherwise-- let me know if this feedback makes sense! I hope it will be an easy change to close this out 🙏

**Comment by jimuhh** [comment]
Thanks @joshkimux for consulting on this. This solution addresses the issue, IMO.

**Comment by rileyorr** [comment]
@joshkimux no worries! I'm all for simplifying 👍 

I've updated the designs ([view on UXPin](https://preview.uxpin.com/16e8675a9898914d5615d6ea2d23e310b7d8dfaa#/pages/142712285/simulate/sitemap?mode=i)) and opened a frontend ticket ([#35745](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/department-of-veterans-affairs/va.gov-team/35745))

**Comment by denisecoveyduc** [comment]
@joshkimux @jimuhh @rileyorr  Thank you everyone! Sounds like we have a path forward in #35745 and we can close this one out! Appreciate the team effort!
