### ISSUE TITLE
[Design] Auth Profile - Personal Info Revision -  Prep for user testing

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34184]
## Issue Description
_Research participant-related tasks needed in support of upcoming research project_

## Preparatory tasks
- [x] Send instructions to observers
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Schedule team debrief sessions once a day
- [x] Followup with Perigean re participant list
- [ ] Other tasks as needed 

## Acceptance Criteria
- [ ] Ready to conduct research sessions

**Comment by MarciMcGuireGCIO** [comment]
Blocked until we have research participants lined up

**Comment by andaleliz** [comment]
👋  Hi! I removed the blocked label since we have participants lined up now, and added myself as an assignee so I can track this more easily.  RE the task list above:

> Send instructions to observers

This will happen before each  session via #feedback-backchannel, so I'll mark it as done above. 

>Make sure all research sessions are in my calendar

Is Christina the "my" in that sentence?

> Schedule team debrief sessions once a day

@cgednalske these are usually a 15 minute meeting. Ideally, they immediately follow the last scheduled session of each day. These are opportunities for everyone who observed to:
-  share what stood out to them from the day's sessions, 
-  identify any patterns that are coming up, and 
- talk about anything that might need to be tweaked for the next days sessions. 

You can invite all of the observers listed in the research plan to these sessions. Attendance is optional (it is 50/50 whether or not people show up), and it's totally fine to cancel if they're not needed/helpful for the team.

**Comment by MarciMcGuireGCIO** [comment]
Thanks, @andaleliz !  I think the "my" would probably apply to both of you in this case.  I actually used a list of tasks that Cindy used, so feel free to make any adjustments that you want.

**Comment by andaleliz** [comment]
Just scheduled debrief sessions, closing this out.
