### ISSUE TITLE
Content support for 2 new screens for Form 526

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#34275]
## Issue Description
Christian Valla asked for content help for 2 new screens in the 526 Form. The text needs to be shortened and rewritten in plain language. 

**The purpose of the question:** If the Veteran says yes, and fulfills certain criteria, they do not have to answer all the questions about PTSD (that has proven triggering / re-traumatizing), but will be called into an examination instead.

![image (11).png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/214c6edc-4f65-4cbe-a97b-2f8f6a8b95d1)

![image (12).png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/abc1fd1f-192f-41e0-8f2d-2b35be902eb5)

Here's the full text for that additional info component:
38 CFR 3.403(f) states, “If a stressor claimed by a veteran is related to the veteran's fear of hostile military or terrorist activity and a VA psychiatrist or psychologist, or a psychiatrist or psychologist with whom VA has contracted, confirms that the claimed stressor is adequate to support a diagnosis of posttraumatic stress disorder and that the veteran's symptoms are related to the claimed stressor, in the absence of clear and convincing evidence to the contrary, and provided the claimed stressor is consistent with the places, types, and circumstances of the veteran's service, the veteran's lay testimony alone may establish the occurrence of the claimed in-service stressor. For purposes of this paragraph, “fear of hostile military or terrorist activity” means that a veteran experienced, witnessed, or was confronted with an event or circumstance that involved actual or threatened death or serious injury, or a threat to the physical integrity of the veteran or others, such as from an actual or potential improvised explosive device; vehicle-imbedded explosive device; incoming artillery, rocket, or mortar fire; grenade; small arms fire, including suspected sniper fire; or attack upon friendly military aircraft, and the veteran's response to the event or circumstance involved a psychological or psycho-physiological state of fear, helplessness, or horror.”

## Tasks
- [ ] Rework text into plain language

## Acceptance Criteria
- [ ] Text is written in plain language and ready to be added to form

**Comment by bethpottsVADEPO** [comment]
@chrvalla 
I actually don't think it's necessary to point to or quote the law at all in explaining why the Veteran is being asked this question. I'm curious if Paul thought we should for some reason. If not, here's what I'd suggest--I've simplified the question too and revised the additional info label since we're not asking for more information, but rather a simple yes or no. I'd especially like to keep this additional info as short as possible so that we're being sensitive and empathetic to the Veterans with PTSD who will be reading it. Not only do we not want to trigger them, we also don't want to burden them with too much text to read through. Please note my updates to all 3 element here--question, additional info label, and answer text that unfurls:

Is your PTSD related to a situation where you feared hostile military or terrorist activity during your active military service?

_Why we ask this question_

If you answer “yes,” we don’t need to get more details from you at this time about the events that caused your PTSD. We'll skip you ahead to the supporting evidence section of the application. And then after you submit your claim, we’ll contact you to schedule a claim exam.

Let me know if you think this might work, or if you want to check with Paul and get back to me. I could also get on a call with you and Paul if that would be helpful.

**Comment by bethpottsVADEPO** [comment]
@chrvalla Now that I see the screens (thank you for slacking that to me!) I have a little concern about the way I've worded it. I don't want to encourage people to answer "yes" just so they'll finish the application faster. Would you replace the additional info text with this?:

If your PTSD is related to a situation where you feared hostile military or terrorist activity, we don't need to get more details from you at this time about the events that caused your PTSD. We'll take you straight to the supporting evidence section of the application.

**Comment by bethpottsVADEPO** [comment]
Chris V. has what he needs, so I'm closing this ticket.
