### ISSUE TITLE
Build.txt error in content-build (502 GraphQL Error)

### ISSUE THREAD

**Issue by oseasmoran73** [department-of-veterans-affairs/va.gov-team#34296]
## Description

There have been a few cases where the `build.txt` error is returned. This has been an ongoing case since Jenkins that has surfaced in Github Actions as well.

I suspect build.txt are "missing" due to `build` step not error-ing out correctly. See [workflow](https://github.com/department-of-veterans-affairs/content-build/runs/4526320282?check_suite_focus=true). Observe that despite `build` having GraphQL errors, it still is has check mark and seen as "successful".

**Comment by cweagans** [comment]
`build` doesn't error correctly specifically when the error is happening inside of the node script. That probably needs to be updated to emit the proper exit code. I think that's only half of the solution here though: we need to know when things fail, but we also need to _prevent_ the fails in the first place. I've seen a few different categories of failures that result in that missing build.txt error:

1. CMS is deploying before graphql queries start (immediate fail on first graphql request)
2. CMS starts deploying while the graphql queries are running (fail after some number of graphql requests)
3. Unexpected content (fail after some number of graphql requests)

There are probably other failure modes, but they aren't frequent enough that I've noticed them.

Case 1 is fixed by https://github.com/department-of-veterans-affairs/content-build/pull/851
Case 2 and 3 are both things that would need to be resolved in the node script. Maybe retries/waits for when the CMS is unavailable. Not sure what to do about unexpected content, though. That might be something that could/should be prevented at the point of entry.

**Comment by oseasmoran73** [comment]
I think prevent is absolutely the way, but having a defensive method in addition may be the play as well. At least my initial thought, having some method of `try/catch`, `retries/wait`, or if there is in place to see if we can force it to error out appropriately via node script.

Thoughts?

**Comment by cweagans** [comment]
Emitting the right error code so that the job fails is a great first step. If an error _can_ be handled by a try/catch + some retries or waiting or whatever, that seems good. I think there are probably some things that just can't be handled by the node script though (e.g. getting bad content back from the API - it would be better to just fail at that point so that we don't inadvertently deploy incorrect or incomplete content).

**Comment by timwright12** [comment]
Closing out as I don't believe this is an issue anymore.
