### ISSUE TITLE
Spool file issue

### ISSUE THREAD

**Issue by ericboehs** [department-of-veterans-affairs/va.gov-team#34342]
[Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1639762159212100)

**Comment by thilton-oddball** [comment]
Going to consider this issue closed. The issue was one of the spool files missing. I re-ran the job and the spool file was generated and delivered. It happened to have about 10 times the number of applications processed as normal. That aspect of it seems related to [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34343).
