### ISSUE TITLE
[PM] Personal Information Revision - Update test cases to reflect content/UI changes

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#34466]
## Background
Need to update initial set of test cases to reflect the changes that have occurred since they were initially written before midpoint review.

## Tasks
- [x] Update test cases to reflect current state

## Acceptance Criteria
- [x] Update test cases to reflect current state

**Comment by MarciMcGuireGCIO** [comment]
Noting that this ticket will need to be carried into Sprint 71.

**Comment by Samara-Strauss** [comment]
Thanks, Marci!

**Comment by SKasimow** [comment]
Still unable to get mocks for 4 test cases in staging.

**Comment by Samara-Strauss** [comment]
Which test cases? How can we resolve this?

**Comment by SKasimow** [comment]
There are a few tests cases for successful and unsuccessful saves for Preferred name and Gender. (I think this won't be available until Adam completes the FE work). However, I don't think this will impede QA from starting their preparations for testing since we provide descriptive text along with each use case (and these use cases are pretty straight forward).

I've already reached out to Tze and gave him a heads-up that my ticket was coming and we were missing a few screenshots; he will be reviewing tomorrow (hopefully) and will lmk if that presents any problems.

**Comment by Samara-Strauss** [comment]
> There are a few tests cases for successful and unsuccessful saves for Preferred name and Gender. 

Can you pull these from Christina's mockups? She should have save/error states in her files.

**Comment by cgednalske** [comment]
@SKasimow @Samara-Strauss Actually we didn't have any error or success states in these mockups yet, but I just added some screens to show what our usual error and alert patterns would look like for Preferred name ([Sketch mockups](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/jgx5LD9)).

**Comment by SKasimow** [comment]
@cgednalske @Samara-Strauss - actually the ones I need are the success messages; are they similar to the ones used on Contact info successful updates? If so, I have those....

**Comment by cgednalske** [comment]
@SKasimow If you arrow right, the success message is on the next screen. But here's the [direct link](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/dlx9pv3) as well. And yes, it is also similar to the ones used in Contact info! 👍

**Comment by SKasimow** [comment]
@cgednalske thanks!

**Comment by SKasimow** [comment]
[Completed Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-profile-personal-information.md)

Closing.
