### ISSUE TITLE
[Design] My VA - Payment Information: Create copy documentation

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34542]
## Background

After Liz' meeting with Mikki and Danielle with Content, we're ready to create a copy document for the payment section of my VA.

- Update Payment information heading to Benefit payments and debts
- Update the alert copy from a single link to improve clarity about where the user would go if they clicked the link, and to align with other similar CTAs on VA.gov. The new copy is: You have 3 outstanding debt. [Manage your VA debt]
- Update the card copy to use active voice. It now reads: We deposited [$$] in your account ending in [acct] on [date].

## Tasks

- [ ] Create copy documentation reflecting cards and alerts

## Acceptance Criteria

- [ ] The documentation for this initiative will be aligned with the feedback from Content

**Comment by andaleliz** [comment]
Hi @hdjustice! The Sketch files have already been updated; is there other documentation that needs to change too? If so, can you provide a link? I checked in the product folder and don't see any content documentation so not sure what else might need to change. I'll add an estimate once I know more. Thanks!

**Comment by andaleliz** [comment]
Oooo nevermind! I'm making my way through all my email notifications and now I understand what this is 😆  thank you! Estimate added.

**Comment by hdjustice** [comment]
@andaleliz is there more detail I can add here so it is more clear and we don't have a question about it later?

**Comment by andaleliz** [comment]
@hdjustice I updated the title and description to reflect that the copy documentation needs to be created, since the Sketch files have already been updated.

When we get to this task for onsite notifications, we'll just need to update the copy since Tressa started a doc. Though, it'll only be one line that matches exactly to the mock-ups so a copy doc _might_ be overkill...

**Comment by andaleliz** [comment]
@hdjustice actually, since this content is so minimal, I'm adding it directly to the FE documentation that already exists, since they're the ones who will need to implement the content. I added a "content" section to each part of the doc. I've done this with previous FE documentation and it worked well for Erik. Hopefully Taylor will feel the same way. Just seems easier to have it in context with the screenshots.

I need help filling in some gaps though - what are the URLs for the "Manage your VA debt" and "Request travel reimbursement" links?

**Comment by hdjustice** [comment]
Staging URLs: 
- https://staging.va.gov/manage-va-debt
- https://staging.va.gov/health-care/get-reimbursed-for-travel-pay/ 

Prod URLs:
https://www.va.gov/manage-va-debt/
https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

**Comment by hdjustice** [comment]
Adding it to the FE doc sounds fine to me.

**Comment by andaleliz** [comment]
Wonderful, and thanks for the links! The content has been added to [this documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md).

**Comment by hdjustice** [comment]
Updated the [FE documentation ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md)to reflect the proper links (changed debt link from comment above).  Also mentioned in this [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1641404166285900?thread_ts=1641400895.283500&cid=C909ZG2BB).

Staging URLs:
- (updated) https://staging.va.gov/manage-va-debt/your-debt
- (new) https://staging.va.gov/va-payment-history/payments
Prod URLs:
- (updated) https://www.va.gov/manage-va-debt/your-debt
- (new) https://www.va.gov/va-payment-history/payments

Travel Reimbursement link provided in previous comment remains the same
