### ISSUE TITLE
Form 21P-530EZ

### ISSUE THREAD

**Issue by nicole-leonard** [department-of-veterans-affairs/va.gov-team#34613]
#[https://app.zenhub.com/files/133843125/5cc6ea20-2fdb-423b-9a95-567058280b41/download](https://app.zenhub.com/files/133843125/5cc6ea20-2fdb-423b-9a95-567058280b41/download)Issue Description

 21P-530EZ is not showing up in search results. This is an active entry in Lighthouse. We also have a "draft" version in Drupal as well as an older archived version. I hypothesize that this collision is what is causing issues in search.

*** According to Mark this was deleted on "deleted_at": "2020-10-22T00:00:00.000Z", This deletion came from the drupal database. Application for burial benefits. 

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by nicole-leonard** [comment]
@swirtSJW Can you please take a look at this one as well? I am wondering if it is the same issue we ran into with ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/34202

**Comment by swirtSJW** [comment]
As you identified @nicole-leonard there are two in the CMS.  Looks like back in oct 2020 they flagged the first for deletion so it got  archived.
The one in draft showed up on 12/1/2021 and has sat in draft ever since. 
![image](https://user-images.githubusercontent.com/5752113/148592198-34b4509a-4c9e-4366-b3c0-9b8e90096a46.png)


I am not sure what makes them show or not show in search, I see other form detail pages in the CMS that are in draft that still show in search.
The archived one is Row Id: 2420
the draft one is  Row Id: 10654
Other than that they both have the same file http://www.vba.va.gov/pubs/forms/VBA-21P-530EZ-ARE.pdf
Here is the data from the formsDB in the CMS
![image](https://user-images.githubusercontent.com/5752113/148593383-7eae5e2c-5f9e-4c42-8b84-b6ad4193478c.png)

My guess is the way Lighthouse is consuming data from the CMS is not using the Row Id as the unique identifier. So likely there is a race condition where it processes the old after the newer and sets it to archived.
![image](https://user-images.githubusercontent.com/5752113/148593915-984d7bd8-2aea-4ab5-86ac-7e7fa74f8951.png)

**Comment by nicole-leonard** [comment]
Thank you @swirtSJW extremely helpful!!

**Comment by mviterna** [comment]
The API treats the row_id as a primary key. So when it hits a match, it assumes there is only one (hence a primary key) and then you hit the race condition. We just need to get rid of one or the other and reconcile the data.

**Comment by mviterna** [comment]
Let me look around a bit and see what we can do. It is definitely recognizing Row_id, or it would not have loaded that form number twice, since those are the same.

**Comment by nicole-leonard** [comment]
I would appreciate it. Thank you. @davidconlon for transparency.

**Comment by mviterna** [comment]
@swirtSJW Ok, so there are two version in the DB, so the load takes in the row_id, which is why we have two on the back end also. But there was old code on the controller that only rendered the first it saw. We still need to consolidate the form and remove the duplicate. Because even though VA.gov will only show one (after my PR to fix it is merged), other Lighthouse consumers will see both copies and not know which is valid, because they don't know about row_ids

**Comment by nicole-leonard** [comment]
Fixed

**Comment by nicole-leonard** [comment]
Fix deploying at 2 pm EST.
