### ISSUE TITLE
[FE] Day of - Convert "facility" and "clinic" to lower case

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#34744]
We need to convert the"Facility" and "Clinic" on the appointments page to use lower case letters, vs. all caps.  This recommendation came from a ux audit that was performed.   See this document: https://docs.google.com/spreadsheets/d/1NWvcrCyEdCjaNAAxZDMUqYMT5MK0hCO4G7DePT-Kb68/edit#gid=1933420590

**Comment by mdewey** [comment]
![Screen Shot 2022-01-12 at 10 48 50 AM](https://user-images.githubusercontent.com/1793923/149173731-d0f0feba-b2d8-41da-9508-684e1fbc4e85.png)

I am not sure if we control the capitalization. Since some of the names (see screenshot of the mocks) have acronyms. 

We some options to address this

- Get the format from CHIP in already formated
- Maintain a lookup table of all the clinics/facilities
- Maybe use the Facility API (if they have the formated name)

**Comment by mdewey** [comment]
To unblock this: 

- Cross-team sync on the above comment to come to a resolution

**Comment by julieadair1** [comment]
@mdewey - I spoke with the CHIP team this morning and they can make the needed tweaks.  They do have some higher priority items at the moment so I'm going to put this ticket back into the backlog for now.  
cc: @jparker0425

**Comment by Hortonio** [comment]
@julieadair1 thanks for bringing this to our attention. I entered the following ticket, [539](https://app.zenhub.com/workspaces/chip-api-6149f6401b0b3c001219802f/issues/department-of-veterans-affairs/chip/539), for the CHIP backlog. 

Thinking through the data, I do wonder about the point @mdewey makes with acronyms. These will be cases where we do not want to remove the all caps format. Applying a global formatting rule would negatively affect these acronym cases. 

The formatting we are sending is also pulled directly from VistA. Would it make more sense to try to correct in the source?

... Just thoughts, feedback welcome!
