### ISSUE TITLE
[Research] My VA - Payment Information and On-site Notification: Complete topline summary and share

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#34801]
## Background
We have conducted our research sessions to determine the usability of the functionality, as well as the value of the information in My VA.  We now need to summarize our findings and share with the team.

## Tasks
- [ ] Create informal topline summary of findings after the final research session
- [ ] Share summary with the team

## Acceptance Criteria
- Informal topline summary of research findings is created and shared with the team to gain feedback

**Comment by andaleliz** [comment]
Hi @hdjustice @Samara-Strauss @tmitchellgcio, and @lihan, and @adamwhitlock1 (since you observed so many sessions) I have the [topline summary](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/research/topline-summary.md) for the research from last week ready for your review! I thought we'd start with an async review, and if there are any major discussion points or discrepancies, I'll set up a meeting.

This doc is a bit information, and you'll see notes to myself to grab quotes once I go through the recordings. The main purpose of this document is to ensure the high-level findings I've identified line up with what you observed, and that I haven't missed anything you thought was important. It's also an opportunity for you to say "XYZ is so interesting, please pay special attention to that when you go through the recordings".

I'd like to get started on the synthesis ASAP; can everyone please reply to this GH issue by this time tomorrow with a "looks good" or any feedback you have? I won't edit this doc but will ensure your feedback is translated to the final report.

Thanks in advance for your time and feedback!

**Comment by hdjustice** [comment]
Here are my notes:
- P5 (seemed comfortable with computer navigation) did actually say that he felt the notifications were redundant (the only person to say so, i believe)
- P5 actually had debt and was able to see that reflected in My VA - I cant remember if he got an on-site alert or not (i think he did!)
- I dont believe that all the participants understood that the Onsite notification was for a NEW debt notice, and not necessarily representative of their CURRENT debt.  I don't remember anyone making that clear distinction, even after reading the content.
- P16 and P13 both used phone to share screen (mobile versions), when revisiting those recordings, capture any feedback related to the mobile experience (I know one person said they might miss stuff because it was so long to scroll).

That is all I can think of.  If i think of anything else before tomorrow afternoon, I will post here again.  Thanks @andaleliz

**Comment by Samara-Strauss** [comment]
This is great and feels reflective of what we heard last week. Looking forward to the final report. Great job!

**Comment by andaleliz** [comment]
@hdjustice thanks for calling out those bullets! I'll keep these in mind as I dig into the recordings. It's super helpful - I **so** appreciate your engagement in these sessions. 

@Samara-Strauss glad you feel I captured what we heard! 

I'm getting started on synthesis today but will stay tuned for additional feedback from other team members,

**Comment by adamwhitlock1** [comment]
Great summary so far! The quotes seem good and you hit all the major points that I noticed 💯
