### ISSUE TITLE
Define/document process for when single app builds fail in master/main

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#34863]
## Details 
Once single app builds are enabled for the `master` branch in `vets-website`, we need to have a process for triaging build failures. This process should outline the steps and actions needed for addressing failed single app builds.

## To do
- [x] Document a process for failed single app builds in the `master` branch.
- [ ] Publish documentation.

**Comment by theodur** [comment]
An enhancement that would make it easier for VFS teams to stay up-to-date with single app build failures is having the failure notifications in [#status-vets-website](https://dsva.slack.com/archives/C02V265VCGH) tag the team that owns the app who's build failed. If VAOS had a single app build fail in `master` for example, the notification would read

``` text
@vaos-fe-all VAOS build in vets-website master branch CI failed! <Link to failed run>
```

We could add an option to the changed apps build [config](https://github.com/department-of-veterans-affairs/vets-website/blob/master/config/changed-apps-build.json) that would allow teams to specify which group or person to ping if their single app build fails in master.

I didn't add anything about this to the draft document yet since we haven't implemented this.

**Comment by theodur** [comment]
I've written a [draft document](https://vfs.atlassian.net/wiki/spaces/pilot/pages/edit-v2/2066645150?draftShareId=6e433455-b24b-4ccc-be6b-8db5dd263d02) that we can modify once we implement changed app builds in `master`. I left out some things since the implementation could impact a few details in the documentation

**Comment by theodur** [comment]
I created a [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36598) for the implementation of the Slack failure notification update based on part of the process defined in the draft documentation.

**Comment by theodur** [comment]
Another copy of the documentation was moved into a [Google doc](https://docs.google.com/document/d/1pAOugBIQ9EZDKGp0ahiFmAoDWCNyRu0ggmh7B27jr9Q/edit#) for easier collaboration. The documentation in confluence matches the Google doc. Now that the details of the process have been finalized for now, I’m going to close this ticket. The documentation will be published alongside the release of single/grouped app builds in `master`.
