### ISSUE TITLE
User having issues with ID.me on authentication.

### ISSUE THREAD

**Issue by boris-ning-usds** [department-of-veterans-affairs/va.gov-team#3499]
### Status

[UNRESOLVED]

### Severity Analysis

Critical for a particular user, as it's been mentioned that he could never login, and that it has never worked. User is having difficulty during the ID.me 2FA process, where it fails coming from within the network. I have been told in the channel that the 2FA token for text is outdated because the user could be receiving outdated keys.

- `sev 2` 
    - Needs SME for ID.me login

### User Impact 

- *Who is the user impacted by this problem?*
User is identified in INC8277061. Contact me for it.

- *How does this problem affect the user?*
User is unable to get through ID.me 2FA process even after receiving 3 or 4 MFA keys.

### Steps to Reproduce

I can't personally reproduce it, but the user says he has never been able to login.

#### Expected Results

User should be able to login through the 2FA process.

#### Actual Results

- ServiceNow (or other source) link
INC8277061

### Proposed Solution
Walk through the login steps with the user, or be able to debug with him.

**Comment by alexpappasoddball** [comment]
@pradsam Is this something your team can tackle?

**Comment by alexpappasoddball** [comment]
Pradheep Sampath 2:24 PM
Hi Boris! This is Pradheep from ID.me.  Alex contacted me with regards to an issue that someone had accessing VA via ID.me.  We are regularly helping users overcome any hurdle they may be having with either ID.me authentication or identity verification. The process that’s currently in place is for them to either open an issue directly via VA at https://www.accesstocare.va.gov/sign-in-help in which case the issue gets routed as appropriate from VA’s Dynamics to ID.me or directly on ID.me at https://help.id.me/hc/en-us/requests/new?ticket_form_id=360001932893 I’ve also looped in Mere who can help coordinate in case this requires escalation
we would need details about the specific user’s problem so our helpdesk can help
we’re regularly dealing with lots of users successfully assisting them
new messages


Boris Ning 2:27 PM
The user is getting to the 2FA page, but every time he punches in the 6 digit code, it rejects him.
I suspect de-synchronization or some timing issue since he's coming in from within VA network to get to the outside. He also said it has never worked for him.
I can send him over to those links tonight in an email.

**Comment by boris-ning-usds** [comment]
This issue has been resolved thanks to the ID.me team. The resolution involved a browser update. 2FA worked just fine after that.
