### ISSUE TITLE
Allow vets to set up Direct Deposit if they have a payment address

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va.gov-team#3504]
Currently the ability to add/set up direct deposit is removed. We want to allow vets to set up DD _if_ they don't have it set up currently _and_ the `"payment_address"` object that comes back from the `GET ppiu/payment_information` endpoint contains address data. Essentially we will treat the existence of payment address data as a flag indicating that they currently get compensation via paper checks and therefore should be able to enroll in direct deposit.

**Comment by erikphansen** [comment]
@Justin-Pickett for your awareness

**Comment by Samara-Strauss** [comment]
@erikphansen I talked with @lkoenigsberg this morning and we've got some questions:

- Does the payment address ever come up blank? I think the question here is whether someone will receive compensation but the payment address won't be filled in, therefore not accurately detecting who receives compensation.
- Is payment address also used for education benefits? I want to make sure that this metric is a payment address for compensation only so that we're not showing the DD fields to people who receive $$ for education but not compensation.
- For the PPIU vs. EVSS for payment address, what is the right long term solution? Should we plan long-term to consume this datapoint via EVSS? Or does it not really matter? Or do we not know that yet?

**Comment by erikphansen** [comment]
@Samara-Strauss:

Looping in @hinzed1127  and @SMLuthi since they might have answers to your questions.

- We have no idea. Without seeing what real users are seeing in prod I don't think there's a way to know what sort of data we get (or don't get) for the payment address. It's possible that the payment address data could be filled in even if a user isn't getting compensation at all (in which case we'd be telling them they can sign up for DD when they can't). It's also possible that the address data could be empty for a user who's getting paper checks (in which case we still won't allow them to sign up for DD). We are flying blind here.
- Again, I have no idea what when payment address may or may not be populated with data. So, yes, it's possible that after I do this work we might be making it seem like someone getting education benefits can now sign up for DD. Which of course would be no worse than the situation we were in before where _everyone_ could try to sign up for DD.
- PPIU _is_ a service of EVSS

**Comment by Samara-Strauss** [comment]
> We have no idea. Without seeing what real users are seeing in prod I don't think there's a way to know what sort of data we get (or don't get) for the payment address. It's possible that the payment address data could be filled in even if a user isn't getting compensation at all (in which case we'd be telling them they can sign up for DD when they can't). It's also possible that the address data could be empty for a user who's getting paper checks (in which case we still won't allow them to sign up for DD). We are flying blind here.

Got it. But can we assume that if we experience these kinds of weird use cases on our end, things would also be the exact same on eBenefits (ie. this is still our best approach and the approach that has the most parity with how eBenefits is handling things)?

> Again, I have no idea what when payment address may or may not be populated with data. So, yes, it's possible that after I do this work we might be making it seem like someone getting education benefits can now sign up for DD. Which of course would be no worse than the situation we were in before where everyone could try to sign up for DD.

I'm gonna ask the eBenefits/EVSS folks about this. 

> PPIU is a service of EVSS

I feel like a dumbo 😂 OK, let me make sure I have this straight. 

Michael Walker said "The flag [for payment address] IS BEING PASSED TO EVSS, and in fact is used by EVSS logic to decide if a Veteran can make Direct Deposit and/or Address changes. The problem is this flag is NOT BEING PASSED TO VA.gov."

So what's the difference between PPIU and EVSS that allows us to consume this information from PPIU if it's not currently being passed to VA.gov via EVSS? (Honestly this makes me feel like 😭)

**Comment by erikphansen** [comment]
> But can we assume that if we experience these kinds of weird use cases on our end, things would also be the exact same on eBenefits (ie. this is still our best approach and the approach that has the most parity with how eBenefits is handling things)?

Yes. That's what we're trying to do. In lieu of getting the same flag that eBenefits uses to indicate if someone is getting paper checks or not, we're gonna use this address data object as a proxy for that flag.

> So what's the difference between PPIU and EVSS that allows us to consume this information from PPIU if it's not currently being passed to VA.gov via EVSS?

This one flag that's missing from the response we get from EVSS PPIU is a piece of data that EVSS gets from BGS. So EVSS gets it from BGS, uses it to power some logic in the eBenefits dashboard, but EVSS fails to pass that piece of data to us for some reason.

What I'm not clear on is where the `payment_address` data comes from. @SMLuthi might know. Relevant Swagger: https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getPaymentInformation

**Comment by Samara-Strauss** [comment]
> Yes. That's what we're trying to do. In lieu of getting the same flag that eBenefits uses to indicate if someone is getting paper checks or not, we're gonna use this address data object as a proxy for that flag.

Got it. I think we're good to move forward with this approach and monitor for errors.

> This one flag that's missing from the response we get from EVSS PPIU is a piece of data that EVSS gets from BGS. So EVSS gets it from BGS, uses it to power some logic in the eBenefits dashboard, but EVSS fails to pass that piece of data to us for some reason.

I get the whole thing about EVSS not passing us the payment address data, but I don't understand how we're then still able to consume this somehow. I'm not sure it's totally important for me to get all the details, so as long as you guys are clear on a path forward, I'm sure I'll understand it over time.

**Comment by erikphansen** [comment]
> I get the whole thing about EVSS not passing us the payment address data, but I don't understand how we're then still able to consume this somehow

So we don't get the _flag_ that eBenefits uses to determine if the user is getting paper checks. But we do get an entire payment address object. So we'll essentially treat that address object as the flag. What I don't know is where that payment address object actually comes from. That's a question for a BE eng.

**Comment by Samara-Strauss** [comment]
> So we don't get the flag that eBenefits uses to determine if the user is getting paper checks. But we do get an entire payment address object. So we'll essentially treat that address object as the flag. What I don't know is where that payment address object actually comes from. That's a question for a BE eng.

Got it! That makes more sense now 😃
