### ISSUE TITLE
ProcessList web component: development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35073]
## Description
Build a web-component version of our [ProcessList React component](https://github.com/department-of-veterans-affairs/component-library/tree/master/packages/react-components/src/components/ProcessList).

## Details
Styles: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/8ce0431d342a5be24170d9329e19257eb6e678db/packages/formation/sass/modules/_m-process-list.scss

## Acceptance Criteria
- [ ] `va-process-list` is written
- [ ] E2E tests are written
- [ ] component is checked for accessibility issues
- [ ] Alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

**Comment by k80bowman** [comment]
Related a11y bug: https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/9936

When we check for a11y on the web component we should make sure this issue is resolved.

**Comment by bkjohnson** [comment]
I read through the issue and found this PR through another linked issue: https://github.com/department-of-veterans-affairs/component-library/pull/191

It appears that the React implementation of the component fixed the issue, so I believe that this is not an issue in the web component since it is based off of the React implementation. We can probably close https://github.com/department-of-veterans-affairs/va.gov-team/issues/9936

We can check if JAWS and NVDA announce the list number [on this page](https://60f9b557105290003b387cd5-tvwyhhypmi.chromatic.com/iframe.html?id=components-va-process-list--default&viewMode=story) to be sure.
