### ISSUE TITLE
ProcessList web component: migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35095]
## Description
Dependent on #35073

The ProcessList React component is not used in vets-website, so we don't may not be able to write an ESLint rule for it. However, if when creating guidance for converting existing patterns inside the Liquid templates you decide that we might be able to use an ESLint rule to assist in this process, let us know and let's discuss it as a team.

For an example ESLint rule, see https://github.com/department-of-veterans-affairs/vets-website/pull/20002

Create guidance for converting existing patterns inside the Liquid templates to these components and add it to our [Liquid template migration guidance ](https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance)Confluence page.

## Acceptance Criteria
- [x] Create guidance for using `va-process-list` inside Liquid templates
- [ ] Reach out to static templates teams about migration
- [x] Add Liquid templates conversion guidance to Confluence page

**Comment by bkjohnson** [comment]
> However, if when creating guidance for converting existing patterns inside the Liquid templates you decide that we might be able to use an ESLint rule to assist in this process, let us know and let's discuss it as a team.

There are some options in this space that could be useful:

- https://www.curlylint.org/
    - This looks pretty limited and doesn't have the kind of ecosystem that ESLint does
- https://github.com/BenoitZugmeyer/eslint-plugin-html
    - I don't know how well this would handle the liquid-specific syntax such as `{%`, but it may be possible to just ignore that since we aren't interested in linting liquid features, only the markup
- https://markuplint.dev/
    - This specifically calls out that it supports liquid templates

**Comment by bkjohnson** [comment]
Here's some guidance on using `<va-process-list>` inside liquid templates:

- Classes are no longer necessary in order to achieve the component styling
- `<li>` elements can be passed as children, there is no need to pass an `<ol>`

Here's a diff where I changed the `process.drupal.liquid` template to use the web component:

<details>

<summary> process.drupal.liquid diff </summary>

```diff
diff --git a/src/site/paragraphs/process.drupal.liquid b/src/site/paragraphs/process.drupal.liquid
index cfa538218..9721b584a 100644
--- a/src/site/paragraphs/process.drupal.liquid
+++ b/src/site/paragraphs/process.drupal.liquid
@@ -11,12 +11,8 @@
   }
 {% endcomment %}
 
-<div data-template="paragraphs/process" data-entity-id="{{ entity.entityId }}" class="process schemaform-process">
-    <ol>
-    {% assign count = 1 %}
-        {% for item in entity.fieldSteps %}
-           <li class="process-step list-{{ count | numToWord }}"> {{ item.processed }} </li>
-           {% assign count = count | plus: 1 %}
-        {% endfor %}
-    </ol>
-</div>
+<va-process-list data-template="paragraphs/process" data-entity-id="{{ entity.entityId }}" >
+  {% for item in entity.fieldSteps %}
+    <li> {{ item.processed }} </li>
+  {% endfor %}
+</va-process-list>
```

</details>

Here's some sample output:

![image](https://user-images.githubusercontent.com/2008881/153673434-316217ec-369d-4118-9b67-ae47590e184d.png)

---

The `step_by_step.drupal.liquid` template is a bit more interesting. Here is a sample live page:

![image](https://user-images.githubusercontent.com/2008881/153675065-6db23893-274c-4e66-a7cf-3811aa47efb5.png)

Notice how there is [some CSS](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/af04178a28587fcc77c2733e74786403d7b687b4/packages/formation/sass/modules/_m-process-list.scss#L23-L26) for the `process p` selector that is stripping out the top margin.

With our web component that global margin is not overridden so we end up with this:

![image](https://user-images.githubusercontent.com/2008881/153675499-d775c7c7-1278-4846-8547-d4532eab44bd.png)

This could be addressed a few different ways:

- In the component library by [adding a `p` selector in the main CSS file](https://github.com/department-of-veterans-affairs/component-library/blob/009d9dad35ea12dd6d4c7f3ad923ad3601e48373/packages/web-components/src/global/main.css#L3-L4)
- Adding global CSS in `formation` or `vets-website`
- Using headings instead of `<p>` tags as the first elements in each list item for a process list
    - Design system guidance implicitly prefers headings on the [component documentation](https://design.va.gov/components/process-list) with the statement:
    > Make headings clear and concise. You can always write more content in paragraphs and other HTML elements below the heading.

**Comment by bkjohnson** [comment]
Guidance has been added to the linked confluence page.
