### ISSUE TITLE
Banner web component: migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35103]
## Description
Dependent on #35102

This component is only used in [one place](https://github.com/department-of-veterans-affairs/vets-website/blob/7c95d43962de29fff92169c44b9d9dbe6716bc92/src/platform/site-wide/banners/index.js#L4) in `vets-website`. We probably don't need a migration script, but we should reach out to the Public Websites team who are the codeowners on this file. If they are not able to prioritize the work, we could offer to migrate the component for them.

Create guidance for converting existing patterns inside the Liquid templates to these components and add it to our [Liquid template migration guidance ](https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance)Confluence page.

## Acceptance Criteria
- [ ] Reach out to Public Websites about migrating component
- [ ] Add Liquid templates conversion guidance to Confluence page

**Comment by pdavies88** [comment]
Current Implementation:
Content Build:  
Vets-Website:  
New Implementation:
Content Build:
* Aria Role and Aria Label can be removed as those will now be handled by the Web Component
```
<!-- Banners -->
{% for banner in visibleBanners %}
  <div
    data-template="components/banners.drupal.liquid"
    data-content="{{ banner.body.processed | escape }}"
    data-dismissible-status="{{ banner.fieldDismissibleOption }}"
    data-title="{{ banner.title | escape }}"
    data-type="{{ banner.fieldAlertType | formatAlertType }}"
    data-visible="true"
    data-widget-type="banner"
  ></div>
{% endfor %}
```
Vets-Website:
- Importing the React Component can be removed as the Web Component will be available
- Since this is no longer a React Component it does not need be wrapped in startReactApp
- Content is moved inside the Web Component and will be rendered as part of the <slot>
- Record Event has been replaced by Component Library Analytics Events
- Storage has been changed to determine if it should be local or session based off a boolean
- Show Close will determine if storage is available to be used, if showClose is disabled storage is not needed
- Headline replaces title as title is a protected keyword
```
    // Create each banner component.
    if (banners) {
      for (let index = 0; index < banners.length; index++) {
        const banner = banners[index];

        // Render the banner.
        <va-banner
          showClose={banner?.dataset?.dismissibleStatus !== 'perm'}
          windowSession={banner?.dataset?.dismissibleStatus === 'dismiss-session'}
          headline={banner.dataset.title}
          type={banner.dataset.type}
          visible={banner.dataset.visible}
        >
          {banner.dataset.content}
        </va-banner>;
      }
    }
```

**Comment by pdavies88** [comment]
Potential Message once Staging Review is complete for #vsa-public-websites 

:wave: Hi Public Websites Team,

Reaching out today because we on the Design System Team have created a new Web Component for Banner to replace the old Banner React Component. I wanted to reach out to see if you all would like to have our team migrate the component for your team or if you would like to do the migration yourselves. We have detailed the steps to take to migrate here: https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance#va-banner but if you would like me perform those steps and then tag you all on the PR happy to do so. Please let me know which would be best for you all. Thanks!

**Comment by k80bowman** [comment]
I would recommend re-wording to read:

> 👋 Hi Public Websites Team,
> 
> Reaching out today because we on the Design System Team have created a new web component for Banner to replace the old Banner React Component. We have detailed the steps to take to migrate here: https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance#va-banner. Would it be possible for you all to migrate to the web component soon? We'd like to deprecate the React version. Thanks!

Are there any advantages you can think of for them to migrate? Are there any accessibility fixes we can highlight or other improvements?

If they reply that they can't prioritize it any time soon (or they don't respond at all), then we can follow up and offer to migrate the component for them.

**Comment by pdavies88** [comment]
No advantages that I can think of it's a single component and everything is detailed as how it should be done. Accessibility wise we just move the region into the Web Component so there isn't a difference just its placement.

Big thing is that we are removing the code from vets-website and getting rid of some of the janky react repaint dom fetching that is required to use it in liquid by just straight using the web component in liquid instead

**Comment by k80bowman** [comment]
Oh that would be good to highlight. So maybe something like:

> 👋 Hi Public Websites Team,
> 
> Reaching out today because we on the Design System Team have created a new web component for Banner to replace the old Banner React Component. The new version can be used directly inside the Liquid templates, with no need to inject React through `vets-website`. We have detailed the steps for migrating to the web component here: https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance#va-banner. Would it be possible for you all to migrate to the web component soon? We'd like to deprecate the React version. Thanks!
