### ISSUE TITLE
[MS] UAT (Techy & Business) of Mulesoft

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#35125]
## Background

Verify 10-10CG submissions against a live instance of Mulesoft.

[VA.gov_MuleSoft_Integration_Test_Plan  (3).docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8120846/VA.gov_MuleSoft_Integration_Test_Plan.3.docx)

**Comment by SKasimow** [comment]
Incomplete due to environmental set-up and issues that prevented us from beginning integration testing; see history/discussion threads below:

- https://dsva.slack.com/archives/CMJ2V70UV/p1642790109026800 
- https://dsva.slack.com/archives/CMJ2V70UV/p1642790129027300

**Comment by RudyOnRails** [comment]
We submitted a 1010CG on staging on Friday around 20:00 UTC to Mule's staging env after they turned off validations, and we are still receiving a 400 from Mule (422 from `vets-api` to `vets-website`).

Sentry: http://sentry.vfs.va.gov/organizations/vsp/issues/74317/?environment=staging&project=3&query=is%3Aunresolved&statsPeriod=1h

datadog: https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Astaging%20service%3Avets-api%20operation_name%3Arack.request%20resource_name%3A%28%22V0%3A%3ACaregiversAssistanceClaimsController%23create%22%29&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&sort=desc&spanID=2039492263100563332&spanViewType=errors&streamTraces=true&timeHint=1644004825733&trace=AgAAAX7GUtqFAFNeLQAAAAAAAAAYAAAAAEFYN0dVdW1aQUFEU1pQSV9wZFM1dTZVWAAAACQAAAAAMDE3ZWM2NjAtMzE2NC00Zjc1LTgwODItNzNiZTY0ZWZjYmJi&traceID=1703915818166751865&start=1643950800000&end=1644037140000&paused=true

Grafana: http://grafana.vfs.va.gov/explore?orgId=1&left=%5B%221643954400000%22,%221644040799000%22,%22Loki%20(Staging)%22,%7B%22expr%22:%22%7Bapp%3D%5C%22vets-api-server%5C%22%7D%20%7C~%20%5C%22V0::CaregiversAssistanceClaimsController%7C10CG%5C%22%22%7D%5D

<img width="801" alt="Screen Shot 2022-02-07 at 12 30 50 PM" src="https://user-images.githubusercontent.com/1021154/152849710-e6203ec5-1e1e-44e9-8a0c-64bdd60511b2.png">

**Comment by RudyOnRails** [comment]
Once #36543 is complete and SSL is back on in vets-api, we should be able to run another test and hopefully wrap up testing.

**Comment by RudyOnRails** [comment]
# Possibly rolling over 67 to 68

@SKasimow this may get completed in 67, but probably not. I am doing some configuration to try and record the cassettes and then will have to adjust our test code to use those cassettes.

Reasons this is rolling over is because of the SSL cert issue last week, personal issues yesterday, and the time required to connect local env to staging fwdproxy so we can record VCR cassettes. 

Once our test suite can run against the VCR cassettes, they may pass and we may be done, but they may fail and we may require changes on the mulesoft side or possibly just tweaks in our tests. And some tests may not even exist, so I may have to write those.

**Comment by SKasimow** [comment]
@RudyOnRails I'll roll this over to 68. In addition to everything noted above, we also lost a BE dev this sprint.
