### ISSUE TITLE
Promo Banner web component: migration

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35157]
## Description
Dependent on #35152

The React component is only used in the site-wide application, so we don't need to write a migration script for it. 

But we should create some guidance for migrating to this component inside the Liquid templates and reach out to the team responsible for them. Right now the way this functions is we have a [site-wide widget](https://github.com/department-of-veterans-affairs/vets-website/blob/1282d03d12eab2ee071d8846a7535e445a6b7c41/src/platform/site-wide/promoBanners/index.js) that looks for `data-widget-type="promo-banner"` on all pages and then adds the PromoBanner component. This `data-widget-type` is currently added to pages in the content-build repo in the [banners.drupal.liquid](https://github.com/department-of-veterans-affairs/content-build/blob/436cc1b7fd1b708a23c98d7da7fc43f51c5e653c/src/site/components/banners.drupal.liquid#L39) file. What we would like to be able to do is delete the widget and use the web component directly in the Liquid template. We should coordinate with the public websites team to see if we can make this happen.

## Acceptance Criteria
- [ ] Reach out to public websites team about using `va-promo-banner` directly in the Liquid template
- [ ] Follow through on the results of that discussion

**Comment by pdavies88** [comment]
👋 Hi Public Websites Team,

Reaching out today because we on the Design System Team have created a new web component for Promo Banner to replace the old Promo Banner React Component. The new version can be used directly inside the Liquid templates, with no need to inject React through vets-website. We have detailed the steps for migrating to the web component here: https://vfs.atlassian.net/wiki/spaces/DST/pages/2051080448/Liquid+template+migration+guidance#va-banner. Would it be possible for you all to migrate to the web component soon? We'd like to deprecate the React version. Thanks!

**Comment by pdavies88** [comment]
Adding class to body for additional padding into the Promo Banner Web Component https://github.com/department-of-veterans-affairs/vets-website/pull/20457#discussion_r822074695
