### ISSUE TITLE
[BE] Datadog metrics dashboard for vets-api/pre_check_in operations

### ISSUE THREAD

**Issue by kanchanasuriya** [department-of-veterans-affairs/va.gov-team#35257]
## Related Documentation

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)

## Acceptance Criteria

- [ ] Deployed and tested on staging.

**Comment by randomsync** [comment]
I setup a threshold alert for vets-api to lorota get token endpoint to understand DataDog's alerting and monitoring capabilities: https://app.datadoghq.com/monitors/62065034. I was able to test it to send alerts and recovery messages to our slack channel. 

I believe next steps should be to have a wider discussion with the rest of the team regarding our monitoring and alerting expectations, so that we can set meaningful alerts on the DataDog captured metrics.
