### ISSUE TITLE
IA request from Digital Health Platform

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/va.gov-team#35290]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [X] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [X] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

We are in the early stages of defining how Veterans can connect and share their patient-generated health data with VA and their care team. One piece of this experience includes Veterans connecting their accounts/devices through VA.gov. The scope of our work is on innovation and evaluation which will limit the use of this tool to a small number of Veterans. To help inform more detailed designs, we would like to discuss the IA and where on VA.gov it makes the most sense to include this experience. 

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-platform/product/dhp-device-connection-product-outline.md](Product Outline)
- Link to or attach user flows:
<img width="1630" alt="Screen Shot 2022-01-13 at 8 30 11 AM" src="https://user-images.githubusercontent.com/56000470/149359408-7d3d8607-dbaf-438c-b02b-958e36634e47.png">

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD this is still early stage
- Estimated staging review date:
- Content and IA work needed by: We would like direction on IA in the next week or two.

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [X] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed
**We'll plan to bring this to the next office hours on 1/20. Also open to a dedicated meeting if this team would prefer.**

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: @kimberlymcm 
-	Product manager: Suzanne Scott (currently being onboarded to Github)
-	Designer: @toddstanich 
-	FE engineer: @mchaffee-tw 
-	Product/team Slack channel: #digital-health-platform-team

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content](https://dsva.slack.com/channels/va-sitewide-content) Slack channel and tag @RLHecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
A few notes from our discussion.  Please add anything I may have missed.  Thank you!

- Functionality will be piloted with 1 location and 1 device (Fitbit)
- Communication to connect the device would happen with the clinician (who is providing the device) and likely an email. 
  - There will be no entry points to this flow on VA.gov and potentially should be hidden from those not in the pilot (they will confirm with stakeholders)
- Initial landing page will need to support 2 functions: connect a device and manage connected devices. To disconnect a device, users will be directed to the device website. 
- Unsure of need to include any data privacy or terms and conditions content.  
- Once logged in, the process of connecting the device (or disconnecting it) would happen through the device's site (i.e. Fitbit's site. They are then returned to va.gov as confirmation of process complete.
- Discussed how this relates to the connected apps feature currently live in profile...
  - Future hope is that this would be in profile for users to manage connected devices
  - Unsure if it can be in profile initially due to only being a pilot - team will connect with Auth Exp team to discuss

Next:
- Team will continue building out mocks, will work with content and will meet with profile team
- Mikki will start drafting IA recommendations

**Comment by mnorthuis** [comment]
Here is a draft user flow showing new VA.gov pages for purposes of discussion.  This assumes this functionality is not part of profile.  

![image](https://user-images.githubusercontent.com/20994159/150610468-271ad119-ae66-4697-90f0-71825c5116c1.png)

**Comment by toddstanich** [comment]
Thank you, @mnorthuis

**Comment by toddstanich** [comment]
@mnorthuis Update on this after exploring our options and discussing with our stakeholders. 
- Short-term We will go with the approach of having a standalone flow and URL separate from the profile for our pilot use cases.
- Long-term we believe the Health Apartment/MHV (specifically the "Track Health" functionality) is an appropriate home when device integrations scale beyond the pilots. 

We're currently working through design and content. I know we will eventually need a URL, is there anything else from an IA perspective needed as next steps?

**Comment by mnorthuis** [comment]
Thank you for the update @toddstanich!   

Does the flow I attached accurately represent your stand-alone MVP?  If not, getting that finalized helps the Sitewide Content and IA team understand your content needs and navigational flows, so we will want to getting that set.   

After that, our process is to work with you on content creation and establishing any navigational components (i.e. breadcrumbs, left nav, as applicable) in prep for any upcoming research.  Having content and navigational elements as accurate as possible ensures a realistic experience for gathering feedback, 

Beyond the research, we will finalize IA (URLs) and begin building out content pages in Drupal.  

Since this issue is pretty IA focused, could you submit the[ Sitewide Content and IA intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+SgardnerPMP&labels=sitewide+content%2C+sitewide+content-product+support%2C+Sitewide+IA&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E) for content support?  We will make sure the issues are connected. 

Thank you!

**Comment by toddstanich** [comment]
Thanks @mnorthuis The flow does represent the stand-alone MVP. One potential change is that we are considering the "connected devices landing page" and "your connected devices" to be the same page just displaying a sign in prompt in the connected devices area if the user is not authenticated. We've created some mockups documented on this Confluence page - https://community.max.gov/display/VAExternal/Device+Connection+Experience

We'll create a separate ticket to track content.

**Comment by mnorthuis** [comment]
FYI, I can not access the link you sent. Is there another place I can access the mocks or can you paste them here for reference?

**Comment by toddstanich** [comment]
Pasting them below 

![1-Landing](https://user-images.githubusercontent.com/56000470/154364327-d8777e56-cb2f-4cb0-978f-fb1375188d33.png)
![2-Sign in](https://user-images.githubusercontent.com/56000470/154364336-8ae219aa-4766-4255-9e38-d1d5d1d12720.png)
![3-Connected Devices](https://user-images.githubusercontent.com/56000470/154364338-9e6a708f-f0d3-4566-aa70-9880fed564dd.png)
![4-Vendor Flow](https://user-images.githubusercontent.com/56000470/154364339-67660d21-d895-44da-a36a-d39a6c56e888.png)
![5-Connected](https://user-images.githubusercontent.com/56000470/154364343-545e61e3-e572-406c-bc8a-5f90231e396c.png)
![6-Disconnect](https://user-images.githubusercontent.com/56000470/154364345-a69f059e-b6be-40b8-be23-36dd419cf79d.png)

**Comment by mnorthuis** [comment]
Hi @toddstanich, checking in on this work.

To finalize the IA and URL(s), I'll need to know 
1) where you landed with the flow - will this be a single page or 2 pages (static unauth and dynamic auth)?  
2) have you connected with Danielle on content per #37053?  The content and H1s inform the ending URL segment, so let me know if there were offline conversations where decisions were made.

**Comment by toddstanich** [comment]
Hi @mnorthuis 
1. We've designed it as a single page, but I will confirm with our devs about that approach.
2. We are meeting with Danielle on Thursday. I've added you as optional to that meeting.

**Comment by mnorthuis** [comment]
Hi @toddstanich!  All IA elements are documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/health-connected-devices.md.

Please let me know if you have any questions on anything.  Thank you!

**Comment by toddstanich** [comment]
Thank you for this @mnorthuis!

**Comment by RLHecht** [comment]
IA work is documented. Closing this ticket but please reopen if it's still needed!
