### ISSUE TITLE
Define the Mapping from QA Artifacts to the New Product Directory in BQ

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#35435]
# Description
We need to formally define how the QA artifacts that we collect from tools across the platform are related to our unified product directory. We need to be sure that the attributes we collect in the product directory CSV have whatever links we need to establish a relationship with QA artifacts.

For each product this involves asking questions like the below,

* GI Bill Comparison Tool maps to E2E tests by what related attribute that we are aware of?
* GI Bill Comparison Tool maps to what manual functional test attribute that we are aware of?

## Acceptance criteria
- [ ] Our current list of products can be mapped to related QA artifacts using the defined mapping.
- [ ] Our expected future list of products can be mapped to likely QA artifacts using the defined mapping.
- [ ] Any rules that we need to ask VFS teams to comply with are available in a document for publishing to Platform Website in the future

**Comment by holdenhinkle** [comment]
Google sheet - https://docs.google.com/spreadsheets/d/1WQi8NKn7s7gJmb4voBFWSXb45-W0trOrndYj-VAOnsU/edit#gid=0

There's huge overlap with this ticket and the one Curt is working on, so he's going to help me on this ticket as he completes his.

We should get this finished on Monday.

**Comment by holdenhinkle** [comment]
Curt and I got the rest of the vets-website data filled in (e2e, unit, contract test paths).

I spent the rest of the day researching the vets-api structure, along with SimpleCov, and RSpec JUnit Formatter.

There are two metrics:
- rspec results
- rspec coverage

For rspec results, we're gonna have to create a list of `spec` files that are associated with each app.

For rspec coverage, we're gonna have to create a list of `.rb` files that are associated with each app, and then create a 'group' for each app, with an app name, and an array of `.rb` files that belong to the app. Read about SimpleCov [groups](https://github.com/simplecov-ruby/simplecov#groups) here.

SimpleCov is reporting coverage for ~2131 files that will need to be grouped. :-(

I haven't counted how many `spec` files there are yet.

We might be able to use the `simplecov-json` gem to export the SimpleCov results as `json` - https://github.com/vicentllongo/simplecov-json

Regarding Manual Functional Testing (TestRail) and GitHub Issues, I'm convinced we're gonna have to create an ID for each app which will act like a primary key/foreign key for the tables in BigQuery. We can programmatically create the tag in GitHub so issues can be tagged with the product ID, and we can programmatically create a new project in TestRail with the name as the ID. It would be best if the ID could be human readable, like `1-covid-19_chatbot` or something. As I think about this, I can't image there being thousands of products, so if there were hundreds, and the IDs started at 1, I don't think it would be too much for the ID to simply be an integer, like `200`; people should be able to easily memorized the ID for the product they're working on and tag issues easily, look for their product in TestRail, etc.

So I think we'll need the following:

- `id` - which will NEVER change
- `product_name` - which can be changed

Regarding the attributes to identify tests in `vets-api` and `vets-website`, each attribute should be an `array` of `strings` which contain one or more paths or filenames for the product.

I'll continue this tomorrow...

**Comment by holdenhinkle** [comment]
Something useful that I put together last year - [Epic #17228: QA Dashboard: Functional Testing, E2E Testing, Accessibility Testing](https://docs.google.com/document/d/1jc4FGRMNFIlNuWlkB4p5MFhKdOQRHE4vutOyot48kHw/edit#)

**Comment by holdenhinkle** [comment]
Lots of the code in `vets-api` doesn't map directly to a single product in `vets-website`; `vets-api` simply provides different apis that `vets-website` products can consume.

To identify the files that are executed in `vets-api` for each `vets-website` product, I think we'd have to go through each product, make note of the `vets-api` endpoints it's hitting, then track down the files in `vets-api` by first looking in `config/routes.rb`, noting the controllers that are hit, making note of the `controller` file and corresponding `model` file, and any additional files that are required within those files. There is bound to be significant `vets-api` file overlap between the `vets-website` products.

We should rethink how to map files in `vets-api`.

Perhaps we can simply make note of which `vets-website` products use which `vets-api` `modules`, and include the test results and coverage for those `modules` in each products' QA Dashboard?

I'm certain that a number of files in `vets-api` do have a 1-1 relationship with a `vets-website` product, especially files in the the `/app` directory, but it will take a lot of work to figure all of that out.

**Comment by holdenhinkle** [comment]
I met with Curt to talk about this ticket and the issues we've been running into with mapping test results and coverage results, TestRail projects, GitHub issues, etc., to specific products. We agreed that we need to meet with Joe, Peter, and Ryan to discuss how to proceed. I mentioned this in a meeting with Joe and Peter.

**Comment by pjhill** [comment]
Thinking about it in relational database terms like this --
![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/b8b3674e-5b09-43bc-adde-bc33113d72c0)

**Comment by holdenhinkle** [comment]
Ideas:

### Tracking overlaps between applications
For each artifact attribute in the schema (like `vets_website_e2e_paths`), have a corresponding `has_overlap` attribute, type `boolean`.

Another idea is to have a separate table of paths with a `has_overlap` attribute, type `boolean`. This would allow use to update the `has_overlap` attribute for each path, which would update the 'overlap' status of all products. But this would be another thing to maintain.

- [ ] Make list of pros and cons for both ideas

### Product IDs

Use a `uuid` + `id` attribute (a human readable string) to identify each product in a service OR a human readable `id` (a string) that's would never be changed as a GitHub label, the name of a TestRail project, etc.

- [ ] Make list of pros and cons for both ideas

### Displaying `vets-api` code coverage

#### Idea 1
Display the `vets-api` `api`s (modules) a product consumes in each product's QA Dashboard. There would be probably be significant overlap between products in this regard but it could be helpful to know the 'health' of each api being consumed.

#### Idea 2
Use the `#add_group` method provided by SimpleCov to identify groups of paths and `spec` files associated with each product. This would give us nice control over displaying metrics for the applicable tests for a product.

---

More to come. Leaving to pickup Hadiya... Still need to review and edit the above^

**Comment by holdenhinkle** [comment]
Ideas (continued):

### Displaying `vets-website` E2E results

Display the results for each product. If the E2E path has a `has_overlap` value of `true`, or if if `e2e_test_paths_has_overlap` has a value of `true` (whichever way we track `overlap`), then we add a disclaimer to the DOMO card representing the E2E tests that tests overlap with other products. We could even name the other products in the disclaimer.

**Comment by holdenhinkle** [comment]
Sheet - https://docs.google.com/spreadsheets/d/1fXZGDV1YjkXEc1-Z3KO2QAF7j-vllX7HvbusKAhIKoY/edit#gid=0

<table class="waffle" cellspacing="0" cellpadding="0"><thead><tr><th class="row-header freezebar-vertical-handle"></th><th id="0C0" style="width:478px;" class="column-headers-background">A</th><th id="0C1" style="width:370px;" class="column-headers-background">B</th><th id="0C2" style="width:32px;" class="column-headers-background">C</th><th id="0C3" style="width:281px;" class="column-headers-background">D</th><th id="0C4" style="width:245px;" class="column-headers-background">E</th></tr></thead><tbody><tr style="height: 20px"><th id="0R0" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">1</div></th><td class="s0" dir="ltr" colspan="2">UUID as the product ID + seperate ID to indentify a product in each service (eg GitHub, TestRail)</td><td class="s0" dir="ltr">VS</td><td class="s1" dir="ltr" colspan="2">Human readable ID as the product ID</td></tr><tr style="height: 20px"><th id="0R1" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">2</div></th><td class="s2" dir="ltr">Pros</td><td class="s2" dir="ltr">Cons</td><td class="s2" dir="ltr"></td><td class="s2" dir="ltr">Pros</td><td class="s2" dir="ltr">Cons</td></tr><tr><th style="height:3px;" class="freezebar-cell freezebar-horizontal-handle"></th><td class="freezebar-cell"></td><td class="freezebar-cell"></td><td class="freezebar-cell"></td><td class="freezebar-cell"></td><td class="freezebar-cell"></td></tr><tr style="height: 20px"><th id="0R2" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">3</div></th><td class="s3" dir="ltr">A standard id-type</td><td class="s3" dir="ltr">IDs would be different in each service (not uniform)</td><td class="s3"></td><td class="s3" dir="ltr">Nothing to maintain</td><td class="s3" dir="ltr">Not a standard id-type</td></tr><tr style="height: 20px"><th id="0R3" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">4</div></th><td class="s3" dir="ltr">If a label changes somewhere (in GH, TestRail, etc.), you can easily update the value in the csv</td><td class="s4" dir="ltr">If a label changes somewhere (in GH, TestRail, etc.), you might forget to update the value in the csv which would break stuff</td><td class="s3"></td><td class="s3" dir="ltr">A prodcuts ID would be the same across all services</td><td class="s3" dir="ltr">If a GitHub label serving as the product id was changed and the change was discovered because stuff broke, it might be difficult to identify which label was changed, making it impossible to fix; all issues associated with a product through a known label wouldn&#39;t be any longer.*</td></tr><tr style="height: 20px"><th id="0R4" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">5</div></th><td class="s3" dir="ltr">Multiple labels could be associated with a product (GitHub) with the id type was an array of strings. However, is that necessary? Probably not.</td><td class="s3" dir="ltr">The CSV would have to be mainainted more</td><td class="s3"></td><td class="s3" dir="ltr">You don&#39;t have to go to the trouble of updating the csv</td><td class="s3" dir="ltr">If a GitHub label serving as the product id was deleted all issues associated with a product through that label wouldn&#39;t be any longer. There wouldn&#39;t be a way to fix this.*</td></tr><tr style="height: 20px"><th id="0R5" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">6</div></th><td class="s3"></td><td class="s3" dir="ltr">If a GitHub label serving as the product id was deleted all issues associated with a product through that label wouldn&#39;t be any longer. There wouldn&#39;t be a way to fix this.*</td><td class="s3"></td><td></td><td class="s3" dir="ltr">If the product&#39;s name changed and deviated from the gist of the human readable part of the ID, there would be an incongruency between the ID and the product&#39;s name that would never be able to rectified.</td></tr><tr style="height: 20px"><th id="0R6" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">7</div></th><td class="s3"></td><td class="s3"></td><td class="s3"></td><td class="s3"></td><td class="s3"></td></tr><tr style="height: 20px"><th id="0R7" style="height: 20px;" class="row-headers-background"><div class="row-header-wrapper" style="line-height: 20px">8</div></th><td class="s3" dir="ltr" colspan="5">* Lots can go wrong with GitHub labels.</td></tr></tbody></table></div>

**Comment by holdenhinkle** [comment]
Joe, Peter, Curt, Ryan and I had a meeting for about 1.5 hours to finalize some decisions about the the product schema. Results:

- assign a `uuid` to each product
- create an attribute called `github_labels`, type `array,` takes `strings` that will hold the GitHub labels for each product
- correlate all test results in `vets-website` through each apps' `manifest.json` file
  - each `manifest.json` will need to have a `uuid` property and value added to it
    - QA Standards will submit a PR to become codeowners of `*manifest.json` files temporarily, so we can update each file without having to wait for PR approvals from each team
    - QA Standards will announce on Slack why and when we'll be updating the `manifest.json` files so no-one is caught off guard
- create an attribute called `has_overlap`, type `boolean` to designate if an app's tests overlap with one or more other apps

**Comment by holdenhinkle** [comment]
I'm not sure this ticket is complete yet because of `vets-api`.

For code coverage, we'll associate products with directories and files using the `SimpleCov` `#add_group` method.

However, I'm not sure how we're going to associate test results with Products. I'll try to finalize this today.

**Comment by holdenhinkle** [comment]
## `vets-api`

### Code coverage:
Currently, the total % coverage for the following 'groups' is being saved to Bigquery:

Jobs
VAOS
MebApi
Mobile
Models
AppsApi
CheckIn
Helpers
Mailers
VAForms
Veteran
AllFiles
Policies
Services
ClaimsApi
Libraries
Ungrouped
Uploaders
AppealsApi
OpenidAuth
Controllers
HealthQuest
Serializers
CovidVaccine
VBADocuments
CovidResearch
FacilitiesApi
TestUserDashboard
VeteranVerification
Swagger
Channels
Identity

Example pic from BigQuery results preview:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/9250a71f-1e82-4f0c-966e-c540d21d8bda)

We can only see the total for the group (the average of all the files in the group), not the % coverage for each file in the group.

#### Do we want the % coverage for each file in each group?

### Test Results
Currently, BigQuery is tracking the high-level test results: total, failed, skipped:

BigQuery Table & Schema:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/3fe9e07c-f74e-4278-804b-84a442e386a6)

We're also tracking failed tests overall:

BigQuery Table & Schema:
![image.png](https://images.zenhubusercontent.com/5f85bcde4f4764585e8ff820/c3758b1a-3e46-41fd-ab71-c8b387077399)

#### Are we okay tracking only failures in BigQuery? It makes sense to me. I'm only asking because we're tracking EVERYTHING for Cypress tests (pass, fail, skip, etc.).

**Comment by holdenhinkle** [comment]
I went over this ticket with Joe. It can be closed.

**Comment by pjhill** [comment]
Cool, since Joe signed off on this ticket's AC being completed, I'm closing it.
