### ISSUE TITLE
Allexe Law-Flood, UX-Team

### ISSUE THREAD

**Issue by Allexelaw** [department-of-veterans-affairs/va.gov-team#35442]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Allexe Law-Flood

### Your Email

allexe.law-flood@adhocteam.us

### Name of Your Team

VA-API Lighthouse:UX Team

### Service(s) You Want Access To

AWS

### Desired AWS Services

I am a UX Researcher and will need to upload interview files to create transcripts.

**Comment by jbritt1** [comment]
Duplicate of https://github.com/department-of-veterans-affairs/va.gov-team/issues/35143?

**Comment by jbritt1** [comment]
Hi Allexe, if there are any differences here not captured in #35143 can you please update / edit the original request? That was the approvers don't have to track two separate access requests for one person. Going to close this one as a duplicate since the process is already started on the other ticket.

**Comment by Allexelaw** [comment]
Original request was just updated f #35143 <https://github.com/department-of-veterans-affairs/va.gov-team/issues/35143>

Thank you.
