### ISSUE TITLE
Update Deployment Guide Publishable on Sharepoint

### ISSUE THREAD

**Issue by lindsay-insco** [department-of-veterans-affairs/va.gov-team#35446]
Create an information article for pharmacy prescription tracking notification feature including:

- What is prescription tracking?
- What are the steps to sign up?

**Comment by vlivshin** [comment]
@lindsay-insco, I met with @ahicksfearless and @jwowk to discuss. Details below!

Justin and Paras discussed having the onboarding process through the VEText Support App, which might remove the need to include the onboarding steps in the user guide. However, while Chase is focusing on AVS, it'll take a couple of weeks to get it on the app. In the meantime:

- [ ]  Add onboarding section to the guide. It's it's already in the word version of the [guide](https://docs.google.com/document/d/1m3KF5JxOFYJFQdS1u9-WHn4WZlSNbtOA16mjhQ_5ld0/edit#heading=h.y3dix3xg1stx), but it may be out of it date now, so will need a review.
- [ ]  Update guide with more detail about how it works:
      - [ ] Add a screenshot of a message that a Vet will receive.
      - [ ] Add the value proposition to the intro.
      - [ ] Add a prerequisite section.
      - [ ] Add a limitations section.

**Notes**

- Sites might want a library of messages that they can reuse.
-   The [guide](https://docs.google.com/document/d/1m3KF5JxOFYJFQdS1u9-WHn4WZlSNbtOA16mjhQ_5ld0/edit#heading=h.y3dix3xg1stx) has been added to SharePoint, but some updates have since been made so the word version is a bit different from the SharePoint version.

**Comment by ahicksfearless** [comment]
met with @lindsay-insco for clarity on this item and am awaiting further instruction

**Comment by lindsay-insco** [comment]
@lindsay-insco follow up with @ahicksfearless

**Comment by lindsay-insco** [comment]
Steps uploaded to sharepoint for users to view.
