### ISSUE TITLE
Re-run December 2021 and early January 2022 component usage reports

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#35496]
## Description
This ticket is dependent on the completion of #34713 and #34696

Since we have updated how the component usage data is counted, we need to re-run the component usage data and update it in DOMO.

## Details
You will need access to BigQuery, Domo, and Domo datasource to complete this ticket.

[Basic instructions for updating component usage data](https://vfs.atlassian.net/wiki/spaces/DST/pages/1962213425/Updating+component+usage+data) (not specific to this task)

The report is run every Friday afternoon, so you will need to run a new report for each Friday in December and early January and then update the report in Domo.

Steps:
- Identify dates for each Friday in December and early January
- for each date
    - Check out the last commit for that date in `vets-website` and `content-build`
    - In the `design-system-dashboard-cli` repo, run `yarn report`
    - Follow the [instructions](https://vfs.atlassian.net/wiki/spaces/DST/pages/1962213425/Updating+component+usage+data) to transfer the query to BigData.
        - Before you run the query, you will need to change `INSERT INTO` at the beginning of the query to `UPDATE`.
- Once all dates have been updated in the table, follow the instructions for [manually running an update](https://vfs.atlassian.net/wiki/spaces/DST/pages/1962213425/Updating+component+usage+data#Manually-running-the-update) in Domo
- Review data in [Domo](https://va-gov.domo.com/kpis/details/1322397216?userId=1325487961) to make sure that it has been updated
    - you can run `yarn search` in `design-system-dashboard-cli` to get numbers for comparison

## Acceptance Criteria
- [ ] Component usage data has been updated in Domo for December 2021 and early January 2022

**Comment by k80bowman** [comment]
@bkjohnson I'm assigning you this first one so that someone who is familiar with the process can go through it and make sure the instructions are correct. If anything needs to be updated, we can change for the November and October tickets:
- November: #35497
- October: #35501

**Comment by bkjohnson** [comment]
I think if we went the `UPDATE` route we would have to do more than just replace `INSERT INTO`. The update syntax is like this:

> UPDATE 'table_name' set col_1 = val1, col_2 = val2, ... where condition is true

And what we're generating is:

> INSERT INTO `table_name`
>   (col_1, col_2, ...)
> VALUES
>   (val_1, val_2, ...)
>   (other_val_1, other_val_2, ...)

It may be simpler (or at least require fewer code modifications) to delete those rows and generate `INSERT` statements again, where `vets-website` _and_ `content-build` are checked out to older commits on the same day.

---

For getting the date to checkout, I think we could use this and maybe have a shell script/alias for it to parameterize the date:

```sh
git log --until=2022-01-15 -n 1
```

This will give us the last commit on **Jan 14th**:

![image](https://user-images.githubusercontent.com/2008881/149989537-9deaeda3-741b-4c74-8ef4-9765a0911ab3.png)

![image](https://user-images.githubusercontent.com/2008881/149989661-f05804b5-a5d9-4fd0-821d-66a2634d3caa.png)

We could shorten it even further if we wanted to use the output directly in `git checkout` without doing any parsing:

```sh
git log --until=2022-01-15 -n 1 --pretty=format:%H
```

**Comment by k80bowman** [comment]
Since we have to run this update for many weeks, do you think it would be useful to write a script to generate this query?

**Comment by bkjohnson** [comment]
I think that would be nice to have. We may have to have the script to generate multiple queries like this for a single `yarn report --update` or whatever the usage is:

```
UPDATE table SET app_1 = 4, app_2 = 4, ... where component_name = 'AlertBox' and date = 'XXXX-YY-ZZ`;
UPDATE table SET app_1 = 12, app_2 = 1, ... where component_name = 'AdditionalInfo' and date = 'XXXX-YY-ZZ`;
...
```

**Comment by k80bowman** [comment]
I can create a ticket for that and then we can prioritize that work first, then this. Even if we do that, I'd still like to have you do the first set of updates, just to be sure there aren't any more hitches to the process.

**Comment by k80bowman** [comment]
Created ticket #35611

**Comment by bkjohnson** [comment]
I went ahead and inserted rows for the React bindings as far back as we needed them to go. Now we just need to update the React components as far back as we want.

Currently the [update script](https://github.com/department-of-veterans-affairs/design-system-dashboard-cli/pull/9) doesn't filter out the bindings or the web components. This means that if we want to copy & paste the output directly into BigQuery and run it then we also need to checkout older commits of `content-build` that match the same date as the older commits we check out in `vets-website`. This isn't hard, it's just something to be aware of.

## Overview

Here is my process. In order to make it easy to checkout the latest commit on a specific day I modified one of my [fish](https://fishshell.com/) functions which you can look at below if you like.

<details>

<summary> fish function </summary>

```fish
function gco
  argparse 'd/date=' -- $argv
  if set -q _flag_date
    echo "Checking out last commit on" $_flag_date
    set dated_commit (git log --until=$_flag_date -n 1 --pretty=format:%H)
    git checkout -q $dated_commit
    git log -n 1
    return
  end
  git checkout $argv
end
```
</details>

If I want to checkout a commit on Nov. 1 2021 I would run my function as:

```
gco --date 2021-11-01
```

![image](https://user-images.githubusercontent.com/2008881/153097728-a2a977cc-b6cf-44d3-92ab-89934d73842f.png)

Feel free to write this as a bash alias (bash scripting is too esoteric for me :upside_down_face: ) - the important parts are:

1. Get the last commit hash as of YYYY-MM-DD
    - `git log --until=YYYY-MM-DD -n 1 --pretty=format:%H`
1. Checkout that commit
    - `git checkout <output from previous command>`
    
### Update process

1. Find the date that you want to update
    - To get a list of dates in the usage table run:
        ```sql
        SELECT SUM(total), date FROM `vsp-analytics-and-insights.platform_design_system.component-usage-count`
        GROUP BY date ORDER BY date
        ```
1. Checkout the old version of `vets-website`
    - `gco --date YYYY-MM-DD` or equivalent
1. Checkout the old version of `content-build`
    - `gco --date YYYY-MM-DD` or equivalent
    - You only need to do this if you don't manually delete the UPDATE queries for the plain web components. I do it just to keep things simple
1. Generate the update queries in the `design-system-dashboard-cli` repo
    - `yarn report --update --date YYYY-MM-DD | xclip -sel c`
    - The pipe to `xclip -sel c` copies the output to my clipboard. Your mileage may vary on MacOS
1. Paste the UPDATE queries into an editor in BigQuery
    - Make sure to remove any yarn output such as `yarn run v1.22.17` at the top
1. Format the query and make sure you see the green checkmark indicating that there are no syntax issues
1. Run the update
    - This may take 2-3 minutes

At this point the table should be updated. If you want to see what this looks like in Domo:

1. Open the [Dataset](https://va-gov.domo.com/datasources/f802aec9-6533-4abc-b0b4-989b7317fc8f/details/overview)
1. Click the stacked "..." icon towards the top right next to the `Open with` dropdown
1. Click "Run now"
1. Open the [visualization](https://va-gov.domo.com/page/1537522750/kpis/details/1322397216) and check to see that the data updated for the date you ran the report for
    - The easiest way is to look at the `<Telephone>` spike
