### ISSUE TITLE
Collaboration Cycle Kickoff [Offices/Tier3 team, Office Directory product]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#35583]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [ ] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [ ] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [ ] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/tier-3-fom). 
- Wireframes, mockups, or prototypes – 
   - New Offices Directory with filter ("search") function – preliminary wireframe: <img width="377" alt="preliminary wireframe - Office Directory search" src="https://user-images.githubusercontent.com/4054752/150192126-2101936f-7892-4962-baea-d7f76db46f31.png">
   - Replaces this list page under main menu _About VA > VA Organizations_: <img width="651" alt="screenshot - About VA   VA Organizations" src="https://user-images.githubusercontent.com/4054752/150192283-9a6a2b12-c14d-428a-b209-170569df7440.png">

- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [x] New
- [ ] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: ____________

### 4. Are you making changes to the visual design?
- [x] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [x] Yes – limited testing possible, not with Veterans
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [x] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [x] New content
- [x] Changes to existing content

### 8. Are you making a change to the user flow?
- [x] Yes
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [x] Yes
- [ ] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [x] Yes (yes to GA, no to Domo)
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [x] Yes (probably; TBD)
- [ ] No

### 12. Does your team have a Github label for this product?

- [ ] No. 
- [x] Yes. Please specify: "⭐ Offices" (within the VAgov CMS Team repo)

### 13. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [x] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Hi @wesrowe. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is a new static content page so we are recommending the following Collaboration Cycle touchpoints: 

- [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
- [Research Plan Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)
- [Analytics Request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
- [Contact Center Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [Privacy, Security, Infrastructure Readiness Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

Post Launch: 

- [Full Accessibility and 508 Office Audit](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Full-accessibility-and-508-office-audit.1774846068.html)
- [Post-launch Check-in](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Post-launch-check-in.1781956691.html)

If they selected static pages for question #6, include the following:

Since your work impacts static pages, please reach out to Dave Conlon to review how your work may overlap with any existing work. This will help him prioritize and identify possible areas of support needed from other teams. 


The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

**Comment by wesrowe** [comment]
Hi @shiragoodman – I'll start with the last question: my PO is Dave Conlon, so we'll be very aligned with the modernized VA.gov effort. :) 
I'm so new to the ecosystem, I can't find my way around the repos yet. The star really is part of that label, but you're right that it's within the VA.gov CMS team repo. I'm right alongside Kev Walsh, "CMS" and "sitewide" seem to be our usual signifiers. Glancing over the issues in this repo, "sitewide content" might be us?

**Comment by shiragoodman** [comment]
thanks @wesrowe . `Sitewide content` is actually used by the Sitewide Content team :) If you don't have a gh label yet in the va.gov-team repo, then we can create one. Not a big deal. The reason it is needed is because my team tracks the issues we find. All issue tickets must have a team label. We are also in the process of tracking products as well so it would be great if we could create a product label for the Office Directory product.

Here is my suggestion: `CMS-Offices` as a team label and 'office-directory' as a product label. Does that work for you?

**Comment by wesrowe** [comment]
@shiragoodman that sounds perfect to me.
