### ISSUE TITLE
SideNav - Remove SideNav on `Events`, `News Releases`, and `Stories` subpages

### ISSUE THREAD

**Issue by kelsonic** [department-of-veterans-affairs/va.gov-team#3575]
# Context
This pertains to the new SideNav, which is visible [here](https://staging.va.gov/pittsburgh-health-care).

# Current Behavior
On an `Events` subpage, the SideNav is currently visible with nothing selected.
![image.png](https://images.zenhubusercontent.com/5d812458c75aaf0001c430f8/bc0c9485-8820-4496-8cab-a5d5acbca893)

# Desired Behavior
On an `Events` subpage, the SideNav is not visible.

# Acceptance Criteria
- [ ] Remove SideNav on `Events` subpages.
- [ ] Remove SideNav on `News Releases` subpages.
- [ ] Remove SideNav on `Stories` subpages.

**Comment by aeltarhoni** [comment]
@kevwalsh Once you finish 2B (Breadcrumbs are rendering correctly on staging Pittsburgh), please let @kelsonic know.

**Comment by kevwalsh** [comment]
@aeltarhoni @kelsonic Staging CMS has the right breadcrumbs for all stories, events, and news releases. But they won't show up on the front end until there's another content build.

**Comment by kevwalsh** [comment]
I should clarify, the current breadcrumbs are not exactly to the spec's mentioned by Andy. Instead of 
`VA Pittsburgh health care > Events > [event-content-detail-page]` 
we have
`VA Pittsburgh health care > News and events > Events > [event-content-detail-page]` 

Instead of 
`VA Pittsburgh health care > Leadership > [Name of person]` 
we have
`VA Pittsburgh health care > About VA Pittsburgh > About us > Leadership > [Name of person]` 

etc.

**Comment by kelsonic** [comment]
Awesome! Thanks @kevwalsh! @ncksllvn I sent up a PR for this that you approved, but I made quite a few changes so if you could spot check it on Monday that'd be great! Thanks and happy holidays to both of you! :) https://github.com/department-of-veterans-affairs/vets-website/pull/11166
