### ISSUE TITLE
[Alert] Update va-alert using onClose to use bindings and new event name in vets-website

### ISSUE THREAD

**Issue by andresriveratoro** [department-of-veterans-affairs/va.gov-team#35890]
## Issue Description
There are 5 files using va-alert with an onClose prop in vets-website. These will need to be updated to use bindings and the new event name (after merging https://github.com/department-of-veterans-affairs/component-library/pull/271).

src/applications/claims-status/components/MobileAppMessage.jsx (1)
src/applications/gi/containers/SearchPage.jsx (1)
src/applications/my-education-benefits/config/form.js (3)
src/applications/my-education-benefits/containers/ConfirmationPage.jsx (3)
src/applications/yellow-ribbon/containers/SearchResults/index.jsx (2)

---
## Tasks
- [ ] Update instances of va-alert using an onClose prop to use bindings and the new event name

## Acceptance Criteria
- [ ] Alerts with closeable and onVaClose prop should trigger onVaClose when clicking to close the alert
---

**Comment by bkjohnson** [comment]
Closing since the only instance of an `onClose` handler for a `<va-alert>` component now is [copy-pasted code that serves no purpose](https://github.com/department-of-veterans-affairs/vets-website/blob/8705802bf9d778119bbeb65a0cbd11caeab42d73/src/applications/gi/containers/SearchPage.jsx#L117).

![Ripgrep search showing that the only use of on `onClose` handler on a `<va-alert>` web component is the gi search page.](https://user-images.githubusercontent.com/2008881/192043352-fffdc146-4483-4454-b01f-eeff831abbe9.png)
