### ISSUE TITLE
Remove flipper for Mobile Header V2 

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#35933]
## Issue Description
_It appears Mobile Header V2 is still wrapped in a flipper, so it defaults to the old design (which displays in browser) and then you see a visible switch to the new design, once the flipper loads. Since this is 100% / fully rolled out we need to improve performance and UX by removing the flipper._

## Front end tasks
- Remove the flipper from the mobile header V2
- Test locally and ensure legacy load is not happening 
- Test in production and validate performance and UX is optimized 

## Acceptance Criteria
- [x] Mobile header V2 performance and UX is improved 
- [x] All tests and passed 
- [x] Close ticket once completed

**Comment by brianalloyd** [comment]
@tmac9494 let's knock this ticket out next.

**Comment by longmd** [comment]
@brianalloyd, for note: This issue also goes back to what we talked about regarding the root cause of #36322. The Desktop header is, by default, left in the DOM until such time that the reactive mobile header is initialized and a check is performed to see what our viewport width is. Only then do we hide the Desktop/Legacy header. 

I can scrub in on this one as well.

**Comment by brianalloyd** [comment]
@longmd that would be awesome.

**Comment by longmd** [comment]
@brianalloyd , This update is now active in Dev/Staging for final validation.

**Comment by brianalloyd** [comment]
Looks great @longmd, let's move to prod. Thanks.

**Comment by brianalloyd** [comment]
Closing ticket, validated.
