### ISSUE TITLE
Modify Tome Sync output to include entityId

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#3599]
## Problem Statement
The current `tome-sync` output doesn't include `entity_id`, but we [use it in the templates](https://github.com/department-of-veterans-affairs/vets-website/pull/11123/files#diff-0fb338986febdf5448b268aa1b330778R238).

## Acceptance Criteria
- [ ] The `entity_id` is exported from the CMS

**Comment by ElijahLynn** [comment]
Hrm, I discussed the Entity ID early on with the Tome Sync maintainer (@mortenson) and I _think_ he said there would be too many content collisions. But I think since we use a "content edit lock" system to prevent editors from editing the same content that we should be able to add this safely. 

I'll dig into this at least as a PoC.

**Comment by cvalarida** [comment]
Interesting. Alternatively, we'll have to modify the templates to use a different field.

CC @ethanteague for visibility.

**Comment by ElijahLynn** [comment]
K, found it. https://twitter.com/DrupalSAM/status/1186793434213863424

> Ah, unfortunately this can't go in. Greatly increases the chance of merge conflicts if two users add entities locally then push.

So the main use case for Tome Sync was for putting content into version control, which we are not doing. This should work out fine to add this in our case, especially since we have https://www.drupal.org/project/content_lock enabled.

**Comment by mortenson** [comment]
I don't think the content collisions will be a problem for you since you're never doing an import and you only have one site - the collisions happens in cases where two editors use the site in separate editing environments, create a Node (both with the same ID), then try to commit.

**Comment by cvalarida** [comment]
Thanks for that context, @mortenson!

@ElijahLynn Any idea how making this change might prevent us from evolving the CMS in the future? It sounds like it will limit some changes we may have down the road. (Mind you at this point, I have mostly no idea what I'm talking about. I don't have a clue what our plans are for the far-flung future or if we're already pretty well pigeon-holed into one specific approach. I'm just trying to get an idea of what implicit restrictions this might place on our implementation of the CMS.)

**Comment by ElijahLynn** [comment]
Crosslinking #4081.

**Comment by ElijahLynn** [comment]
Thank you @mortenson for validating that! 

@cvalarida We are good to go on adding this, I don't see any issues in the future. I'll get this done soon.

**Comment by ElijahLynn** [comment]
This is done now in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/827.
