### ISSUE TITLE
Discovery: identify options for automating review of vets-website CSS for potential Design System usage

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36043]
## Description
There are a lot of places where frontend engineers on Va.gov are using custom CSS where they could be using Design System utility classes. Without examining every PR, however, it is difficult to identify these and encourage frontend engineers to use the Design System instead. We would like to identify some ways we could automate this process and then figure out how we would like to implement whichever options we deem most appropriate.

## Details
from @bkjohnson in a Slack discussion:
> There are existing stylelint rules that I'd like to put in at some point to flag obvious things like display: block or margin: 1em. Based on what I've seen on the ESLint side of things, I think we'd have to build our own linting rule to warn/alert on certain values for className, but that shouldn't (:fingers_crossed: ) be too much effort.

Other things we may want to look out for:
- uses of the `vads-` prefix inside vets-website CSS files (shouldn't be happening

## Acceptance Criteria
- [x] Generate a list of ideas for automating review of CSS in vets-website for potential Design System usage and add as a comment on this ticket
- [x] Discuss options with Design System engineering team and determine a path forward
- [x] Create tickets for implementation of selected idea(s)

**Comment by bkjohnson** [comment]
Here are some linting rules that may be useful to add:

## ESLint

1. [`react/forbid-component-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md)
    - This can prevent using the `style` attribute on React components
2. [`react/forbid-dom-props`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-dom-props.md)
    - This can prevent the `style` attribute on HTML elements like `<div>`

These rules could help ensure that styling is using CSS that targets id/elements, or by directly setting `className`.

## StyleLint

1. [`declaration-property-value-disallowed-list`](https://stylelint.io/user-guide/rules/list/declaration-property-value-disallowed-list/)
    - We could use this to throw linting errors when custom CSS does things that we have utility classes for, like setting `display: block`
2. [`selector-class-pattern`](https://stylelint.io/user-guide/rules/list/selector-class-pattern)
    - We could use this to enforce that selectors can't start with `.vads-`

If we wanted to build a rule for triggering on certain values of `className`, we may be able to build something [based on this rule](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/566011b89df811b95bc4e99799a5ea03d440411d/src/rules/tabindex-no-positive.js#L26-L46) that triggers on certain values for `tabindex`

**Comment by bkjohnson** [comment]
Here's an example of what the `selector-class-pattern` can tell us. I configured it locally to throw an error on any selector that begins with `vads-`:

```diff
diff --git a/.stylelintrc.json b/.stylelintrc.json
index f1cab113c4..e96ceb04fb 100644
--- a/.stylelintrc.json
+++ b/.stylelintrc.json
@@ -13,6 +13,7 @@
     "declaration-colon-space-before": "never",
     "function-url-scheme-disallowed-list": ["ftp", "/^http/"],
     "no-eol-whitespace": true,
+    "selector-class-pattern": "^(?!vads-)[a-zA-Z]+",
     "order/order": [
       {
         "type": "at-rule",
```

![image](https://user-images.githubusercontent.com/2008881/159100528-01a2d51d-2015-4272-b0db-2d8eed62f1b3.png)

https://github.com/department-of-veterans-affairs/vets-website/blob/6b6c88b0398cc260a1dab1a3adba78471b07837c/src/applications/my-education-benefits/sass/my-education-benefits.scss#L329-L330

There is custom CSS taking a `.vads-u-display--block` utility class and setting `display:none` on it. This defeats the purpose of having a name in the markup that tells you exactly what to expect.

**Comment by andresriveratoro** [comment]
Here is a [Github Action](https://github.com/marketplace/actions/problem-matcher-for-stylelint) used with Stylelint that we could modify to create annotations in pull requests. 

Currently, it does not create annotations when the severity of the rule is set to "warning". We're going to want to implement our Stylelint rules with a severity of warning as to not block PRs from being able to be merged because of linting errors that will surface with rule changes and already exist in the codebase. 

I've implemented this GHA along with the `declaration-property-value-disallowed-list` Stylelint rule (thanks @bkjohnson!) to disallow what we already have in our DS in this [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/20899) on vets-website for us to review.
![Screen Shot 2022-04-28 at 17.48.25.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/e7cf4ad6-424c-4ffb-9549-21d3c7fd4ea6)
Unfortunately, the error message isn't very useful and there isn't a way to modify the GHA to include a custom message. 

Problems matchers can be used to scan a build's output to automatically surface lines to the user that matches the provided pattern. ([Source](https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers))
We might be able to customize the message engineers are presented with by modifying the problem matcher json file.

This is the problem-matcher.json used in the GHA linked above. [Here](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) is some useful information on these properties.
```json
{
  "problemMatcher": [
    {
      "owner": "stylelint",
      "pattern": [
        {
          "regexp": "^([^\\s].*)$",
          "file": 1
        },
        {
          "regexp": "^\\s+((\\d+):(\\d+))?\\s+(✖|×)\\s+(.*)\\s{3,}(.*)$",
          "line": 2,
          "column": 3,
          "message": 5,
          "code": 6,
          "loop": true
        }
      ]
    }
  ]
}
```

A GitHub Action in conjunction with the suggestions provided by @bkjohnson should allow us to discourage engineers from creating styles that already exist and to surface any linting warnings in PRs for reviewers to see (and to hopefully withhold on approving until they've been corrected).

**Comment by andresriveratoro** [comment]
Tagging for awareness @bkjohnson @k80bowman @pdavies88

**Comment by bkjohnson** [comment]
This [CI step](https://github.com/department-of-veterans-affairs/vets-website/blob/66c6b977af9ed5a0ab60aa3632fa4a67887acebf/.github/workflows/pull-request.yml#L262-L264) supposedly leaves stylelint annotations on PRs like we see for ESLint rules. Does that do what we need (annotating on warnings) without adding the additional GitHub action?

**Comment by andresriveratoro** [comment]
I did see that, but they are hidden away and not surfaced in the PR's `Files changed` section where a reviewer would be looking at. If the rules are set to "warning", a reviewer would have to go inside `Checks` and manually verify that there are no warnings. If the rules are set to "error", then we wouldn't need any of this because the linting errors would prevent a PR merge.

![Screen Shot 2022-04-28 at 18.56.47.png](https://images.zenhubusercontent.com/617ff9ad86edf726772188b8/8998b886-88e4-474f-9703-bf0ab641572f)

**Comment by andresriveratoro** [comment]
Oh you're right. I just opened a new PR and tried it for a rule that existed. 😓

**Comment by bkjohnson** [comment]
I love that we can even give it a custom warning message!

**Comment by andresriveratoro** [comment]
- In order to display Stylelint warning annotations in PRs, we need to modify `script/github-actions/stylelint-annotation-format.js`
```diff
diff --git a/script/github-actions/stylelint-annotation-format.js b/script/github-actions/stylelint-annotation-format.js
index 86dbb19825..ba30c7e885 100644
--- a/script/github-actions/stylelint-annotation-format.js
+++ b/script/github-actions/stylelint-annotation-format.js
@@ -12,8 +12,6 @@ if (!fs.existsSync(styleLintReport)) {
 const styleLintData = JSON.parse(fs.readFileSync(styleLintReport));
 
 styleLintData.forEach(fileMessages => {
-  if (!fileMessages.errored) return;
-
   for (const [key, value] of Object.entries(fileMessages)) {
     if (key !== 'source' && key !== 'errored' && value.length) {
       fileMessages[key].forEach(fileMessage => {
```
---
- Ideally, engineers should be aware of any linting errors (including warnings) before committing their code and without having to run linting script commands. This is an option for engineers using code editors and a Stylelint extension for that IDE, but may require us to update `stylelint` dependencies on `vets-website`. For example, the latest version of the [Stylelint extension](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) for VSCode only works for stylelint versions above 13. `vets-website` is currently using `13.13.1`.
---
- We would like to prevent engineers from creating styles for properties and values that exist in the Design System by creating ESLint and Stylelint rules, but we should not create them without researching possible valid use cases and exceptions. If exceptions should be made, how should we implement them?

We can prevent engineers from creating properties and values that exist using the Stylelint rule [declaration-property-value-disallowed-list](https://stylelint.io/user-guide/rules/list/declaration-property-value-disallowed-list/).
```json
"declaration-property-value-disallowed-list": [
      { "display": ["block", "inline", "inline-block", "flex", "none"] },
      {
        "severity": "warning",
        "message": "Please use the corresponding utility class from https://design.va.gov/foundation/utilities/display"
      }
    ]
```

We can prevent engineers from using the style property on React components and DOM elements using ESLint rules [react/forbid-component-props](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md) and [react/forbid-dom-props](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/forbid-dom-props.md).
```json
    'react/forbid-component-props': [
      // 0 = disabled, 1 = warn, 2 = error,
      1,
      {
        // array of props that will trigger a warning
        forbid: [
          {
            propName: 'style',
            message: 'Custom message about not using style prop goes here',
          },
        ],
      },
    ],
    'react/forbid-dom-props': [
      1,
      {
        forbid: [
          {
            propName: 'style',
            message: 'Custom message about not using style prop goes here',
          },
        ],
      },
    ]
```

---
- We would like to prevent engineers from overriding Design System utility classes. We can do this by updating `.stylelintrc.json` with the `selector-class-pattern` rule.
```json
"selector-class-pattern": [
      "^(?!vads-)[a-zA-Z]+",
      {
        "severity": "warning",
        "message": "Please do not override Design System utility classes"
      }
    ]
```
---
- We should consult with the release tools team before implementing ESLint and Stylelint rules.
- We want to eventually increase the severity of rules from "warning" to "error", but we need to research and consult with the release tools team as to not block builds.
