### ISSUE TITLE
Research | Spanish Chatbot

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36052]
Description: The Chatbot team is considering a spanish chatbot and wants to understand how we set-up our translated content and what systems we use:

Acceptance Criteria:

- [x] Document in this ticket the approach used today and future plans

Details:
- as far as the Language entity goes and supporting multi-lingual through Drupal, that is something that we have asked about, but at this time it is not supported in the current VA CMS instance.
- The CMS team would have to set up the multilingual modules and configure the CMS for the additional Spanish language content in order to be able to use all the language features and for querying via graphql based on language.
- The current Spanish language content on the website is actually just a regular page (considered ‘English’ in the eyes of the entities) since it needed to be published quickly, and we have some front-end workarounds for setting page language attributes etc, as a stop gap.
- Currently the list of urls is maintained here:
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/static-pages/i18Select/utilities/urls.js
You can see the english / spanish / tagalog urls for each page
- Could you elaborate on what the front-end workarounds for setting page lang looks like? 
     - So far the front-end provides a few things:
     - A ‘language switcher’ at the top of the article that provides links to the article in the various languages
     - A process for updating the lang attribute of the main content div for screen readers
     - A process for updating any links to foreign language content with the correct lang attribute
     - When viewing a foreign language page, the sidebar gets modified to only show the links to the articles in that language (because otherwise the other links in the sidebar would show and is potentially confusing)

Today the Chatbot team has a knowledge base that is populated by Drupal with content from a variety of pages on the website. They've scraped the health benefits page for example, so someone can ask the bot “How do I apply for benefits” and the bot will reply with a summarized answered based on the page, and then link to the page itself. Hoping that in the future if the user is interacting in spanish, we can link to the spanish version of the page

**Comment by adamwhitlock1** [comment]
Additional ideas to note:

If we were looking to make it easier for the chatbot team to 'scrape' foreign language content, then we might be able to make it easier to programatically get the link urls to content by exposing the list of urls via a global JS variable on the translated pages. This way the scraping tool could first access a singular page as an 'entry' to translated content pages, and then subsequently scrape the remaining pages by using this global variable. This may or may not be ideal to the chatbot team, but it is one option. We would need to make sure that this first entry page was consistent and its url didn't change or the page isn't removed without first notifying the chatbot team first so that they could modify their code.

A secondary option for exposing this could be generating a JSON file for the list of pages similarly to how the resources and support application works and uploading it to S3 to be accessed by ourselves and the chatbot team. This seems less viable in my opinion because this work would need to be done in the content-build repository, and does not lend itself to scaling as well. This solution would require code to be maintained in two places. The upside could be that in the future if we turned on the translation modules in drupal, then we could modify the JSON generation process to possibly just query graphQL directly for a list of translated urls, and that could potentially be a more hands off method. SInce the public api and other Drupal dependencies are still in flux, then this approach would probably be more long term after those dependencies are resolved.

At this point, the chatbot team is in a discover phase about multilingual support in their product, but I wanted to document these options and make sure we can support them in any way possible.
