### ISSUE TITLE
[Spike] Disruptive Flag Discovery Meeting

### ISSUE THREAD

**Issue by kristenmcconnell** [department-of-veterans-affairs/va.gov-team#36119]
# Description
Meet with Jami Falk and product to learn more about the disruptive flag feature.

# Tasks 
- [x] Attend meeting

# Acceptance Criteria
- [x] Meeting was held

**Comment by kristenmcconnell** [comment]
Based upon this morning's stand-up, changing the assignees for this ticket to @niradatta1 and @ytsaoca.

**Comment by niradatta1** [comment]
Captured notes from the meeting here: https://docs.google.com/document/d/1XTSlXgEzyQ4Lr8Q-1CAIO9flaK_MTIzywNJ3t3fmP38/edit?usp=sharing

@kristenmcconnell @jparker0425 @julieadair1 Based on the conversation, there doesn't seem to be any immediate impact on the veteran user flow for pre-check-in and check-in, since behavioral flags are mainly useful for staff. We don't see any UX related work. However, there may be considerations for the back-end team. For instance, we'd want to ensure that when a Veteran is checked in or completes pre-check-in, their behavioral flag information (if any) is relayed to the staff facing app. But would need to discuss this with engineering team to verify. 'cc @ytsaoca
