### ISSUE TITLE
[Technical Discovery] NOD | HLR Comparison

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3615]
## User Story or Problem Statement
As a Front-end developer on the Benefits and Memorials team, I need to identify similarities between the Notice of Disagreement claim form and the Higher Level Review form so that I can easily recreate the digital steps of the HLR form as it relates to the NOD form.

## Goal
_Identify the NOD steps that would be duplicative of HLR online steps_

## Acceptance Criteria
- [x] NOD steps that would mirror HLR online steps identified

**Comment by Mottie** [comment]
NOD Similarities to HLR:

- [x] Veteran details
  - Veteran's Name (first, middle & last)
  - Veteran's SSN and VA file number
  - Veteran's date of birth
- [x] Veteran contact information (or person filling out form)
  - Mailing address (street, City, State, ZIP & Country)
  - Email address
  - Phone number
- [x] Issues
  - Choose specific issues
  - Issue date of decision (not on HLR, but we should already know that) since we're displaying the issues

New portions in NOD (not in HLR)

- [ ] I am not the veteran
  - Name (first, middle & last)
  - Date of birth
- [ ] I am homeless
  - Only a checkbox on the NOD
  - I think we should determine if it needs to be more involved like how form 526EZ's asks for more details. HLR doesn't deal with homelessness at all. In discussions with @kevinstachura, I think this (how form 526EZ handles it) should be a more standard part of every form.
- [ ] Board review options
  - 3 radio buttons (not checkboxes like the form)
  - Maybe include an additional info component to show more details about each path
- [ ] Opt in from SOC/SSOC
  - Similar but may not be exactly the same as the opt in planned for the HLR.
  - This checkbox seems to be a more global option; if the applicant checks this box, does the person doing input processing decide which legacy issues match and then opts out? Or should it be more granular like we have planned for HLR?
