### ISSUE TITLE
Collaboration Cycle Kickoff [Auth Profile, Bad Address Indicator]

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36440]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [X] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [X] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [ ] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [ ] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/contact-information/bad-address-indicator)
- Wireframes, mockups, or prototypes
   - TBD
- Any other artifacts you have so far

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [X] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: VA.gov Profile contact information

### 4. Are you making changes to the visual design?
- [X] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [X] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [X] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [ ] New content
- [X] Changes to existing content

### 8. Are you making a change to the user flow?
- [X] Yes
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [X] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [X] Yes
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes - we will need to capture the number of addresses that have bad address indicators
- [ ] No

### 12. Is there a GitHub label in the va.gov-team repo for this product?

- [ ] No. 
- [ ] Yes. Please specify: `bad-address-indicator`

### 13. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [X] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Hey @MarciMcGuireGCIO. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html)
- [Research Plan Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html)
- [Analytics Request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
- [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html)
- [Contact Center Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)
- [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html)
- [Privacy, Security, Infrastructure Readiness Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)


The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

Also @MarciMcGuireGCIO  - does the Auth Profile have a team github label? I know this is something we discussed a while back and I'm not sure where you landed.

**Comment by MarciMcGuireGCIO** [comment]
Thank you @shiragoodman !  We are sharing vsa-authd-exp with the My VA team, and we add the profile tag to differentiate our tickets from theirs.

cc @Samara-Strauss

**Comment by Samara-Strauss** [comment]
+1 to what Marci said. The auth experience team is a larger team made up of folks who work on the My VA product primarily and the Profile product primarily. However, I don't consider them two separate teams considering some of the overlap between these two products, so we haven't created separate team tags for them.

**Comment by shiragoodman** [comment]
ok thanks @Samara-Strauss and @MarciMcGuireGCIO  - if that's the case, I think we'll just continue to use the vsa-authd-exp label. Our queries aren't advanced enough (yet) to be able to pull in or assign multiple labels. All this means is that issue tickets created by my team at Staging Reviews for Auth Exp and Auth Profile will both be findable under the vsa-authd-exp label. If you ever decide to change what you have in place, please let me know. thanks!

**Comment by MarciMcGuireGCIO** [comment]
Kickoff is complete.
