### ISSUE TITLE
[Design, FE] My VA - Payment Info: Click through feature in staging

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36444]
## Background

Now that development has completed, we will need to click through the functionality, per the **[Use Cases](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md)** outlined.  We will need to confirm that all functionality is working as expected for users currently listed.

## Tasks
- [x] Liz - Informal click-through of the feature, confirming it is ready for QA
- [x] Taylor - Informal click-through of the feature, confirming it is ready for QA

## Acceptance Criteria
- All functionality is working as expected, including any new changes implemented as a result of research findings.

**Comment by andaleliz** [comment]
Do we need to consider various browsers and mobile devices as we do this, or is that something that will be covered during a more formal QA process?

**Comment by hdjustice** [comment]
I meant to answer this, apologies for the delay.  We should cover at least Chrome and Edge, and the mobile view.  If you want to try other browsers that you might have installed, that is only a plus!  I think Tze will also be trying multiple browsers.

**Comment by andaleliz** [comment]
Thanks for the info @hdjustice! I'll check in Chrome, Edge, and on my iPhone 12 mini in Safari.

I noticed the 3rd use case states:
>There will also be 2 additional links displayed: "Manage your direct deposit" link and "Learn about VA debt" link.

I was thinking we'd show that Learn about VA debt link if they **don't** have debt, since the Manage your VA debt link they see in the alert has essentially the same information.  Does the test case need to be updated, or did we decide to change that logic? Either is fine just want to be sure I mark the result of the testing accordingly.

**Comment by andaleliz** [comment]
FYI I am tracking my results [in this Google Sheet](https://docs.google.com/spreadsheets/d/1qdWFjj128aVoKMNDeUZ8-uAR7ljMayr4kmtr4cU7hq8/edit?usp=sharing). Taylor, feel free to copy my worksheet and make one for yourself if that makes it easy for you to track your work.

**Comment by hdjustice** [comment]
The test cases should be up to date with all our most recent logic changes.  If you think anything (and I mean any little thing) is weird, wrong or out of place, please let me know so I can address it.  Thanks so much!!

**Comment by andaleliz** [comment]
Ok, will do! I deleted my previous comment because I realized I was looking at the wrong line. Totally my bad. However- I realized something else. Angela's work on #36182 means that the design of the alert will change, so I'm not sure it makes sense (yet) to validate across browsers. 

@tmitchellgcio correct me if I'm wrong, but I think the only thing that would be impacted cross-browser _how_ things display, not _if_ they display. We can confirm the logic in one browser if we want to now, but it feels like it's better to wait to check all until the CSS reflects the latest designs.

**Comment by hdjustice** [comment]
That is correct, the design/style will need to change (sorry Taylor!) 
However, that is **after** the logic/functionality of the error states and no-debt state are implemented.  I will have tickets for the style changes created today.

**Comment by tmitchellgcio** [comment]
@hdjustice @andaleliz you are right. Most logic shouldn't be affected across browser. It can happen but it's rare with the stack we are using and usually only if we use some obscure or brand new coding techniques, but checking if and when something is displayed should never be different across browsers, however design can be affected a lot cross browser. Error states look like they are using the old style with different wording due to testing with the new style. The good thing is I should have that done pretty soon. I had those in there already with generic wording. I will need to write some tests first though to be sure my logic is sound for them. I should have time this sprint to handle the other changes though, I expect.

**Comment by hdjustice** [comment]
Did not complete in sprint 67 due to technical issues during development testing and code merging.  Click-through could not be completed.  Will complete in sprint 68.

**Comment by tmitchellgcio** [comment]
I'm not sure how else to test this. I flipped through a few different profiles. It all looks fine for me

**Comment by andaleliz** [comment]
Oh, I didn't realize this was ready to test again! I can do it too. Did you check in different browsers / responsiveness @tmitchellgcio ?

**Comment by tmitchellgcio** [comment]
oh nope I guess I will do that now sorry

**Comment by tmitchellgcio** [comment]
Today I'm getting 500 errors. Luckily I can test the error messages which looks great, but payment information's api is erroring out.

**Comment by andaleliz** [comment]
Moving this to blocked since the payment API is down.

**Comment by andaleliz** [comment]
Hi @tmitchellgcio are you done with your work on this? Wondering if I can do my part of the click through. Thanks!

**Comment by tmitchellgcio** [comment]
yes but the updated alerts aren't up yet

**Comment by andaleliz** [comment]
Ok, I'll stay tuned.

**Comment by tmitchellgcio** [comment]
PR completed should be up in staging soon. Keeping an eye on it. Will let you know when it's up

**Comment by andaleliz** [comment]
The payment API came back up! Tested in Edge on my Mac. We are close 🎉  but there are some kinks to iron out:

1.  Across all the users I tested, it looks like the 2 column layout is displaying as one column. [Here's a mock-up](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/1KnQlRO), compared to what I see in staging with user 1:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/55992116/157233190-5acd2017-8fdc-49a4-a021-0f6b0071db11.png">

2. The most recent payment isn't showing up for anyone for some reason. I checked the view payment history page for users that are supposed to have a recent payment. The data is showing up there but not on My VA.

3. The links are all going to the right places, but opening in a new tab. I am 99% sure the practice on VA.gov is to open them in the same window instead of a opening a new tab. I can't find that documented anywhere, so I'm checking with the UX team. If either of you @tmitchellgcio or @hdjustice could check w/ your practice peeps, you may be able to get an answer sooner than me. I'll report back when I confirm that.

I'm going to hold off on testing mobile until these issues are sorted out.  

Also, I made a couple of updates to the test case doc:
-  I added a test case to the [links section](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md#benefit-payments-and-debts-links), to test the `Manage your VA debt` link when it appears.
- I updated the user for the direct deposit link test. Although it was displaying for `user+21`, that user doesn't have access to direct deposit information because they are flagged as incompetent. I updated it to `user+1`.

Putting this ticket back in the blocked column until the above issues are fixed.

**Comment by hdjustice** [comment]
> The links are all going to the right places, but opening in a new tab. I am 99% sure the practice on VA.gov is to open them in the same window instead of a opening a new tab. I can't find that documented anywhere, so I'm checking with the UX team. If either of you @tmitchellgcio or @hdjustice could check w/ your practice peeps, you may be able to get an answer sooner than me. I'll report back when I confirm that.
I am checking with the VA product channel.

> Also, I made a couple of updates to the test case doc:
Thank you!  I didn't put the "Manage your VA debt" link there, because it would never be listed in the link list, but having that test case there is fine, helps cover all the bases.  And I thought User 21 did have direct deposit, but perhaps something changed.  Thank you for updating these!

**Comment by hdjustice** [comment]
> The most recent payment isn't showing up for anyone for some reason. I checked the view payment history page for users that are supposed to have a recent payment. The data is showing up there but not on My VA.

It seems that the users that have payment histories haven't had anything since Feb 1, which is more than 30 days ago, and it doesn't look like the system has triggered one for March 1.

![image](https://user-images.githubusercontent.com/92328831/157259241-1fd7d859-a9cb-4774-a8e5-556ce9e693a0.png)

**Comment by andaleliz** [comment]
Oh, that makes sense @hdjustice! Not sure how we will be able to test this exactly then. Is it something we can ask the payment team to set up for us?

Also, I did confirm that it is an a11y best practice to open links in the same window ([WCAG guidance](https://www.w3.org/TR/WCAG20-TECHS/G200.html)), and something the platform team decided on but hasn't documented. Mikki, our IA consultant, shared this:  
> Links should only open in a new tab if clicking the link will result in the user losing progress or data.  This includes scenarios where a user may be immediately logged out of their [VA.gov](http://va.gov/) session, may lose their place in the middle of an application that is not saved, or may lose data that they are entering/uploading into a form.  (In all of these cases, it should also be considered whether the link is worth potentially taking the user away from where they are.)

**Comment by tmitchellgcio** [comment]
> The payment API came back up! Tested in Edge on my Mac. We are close 🎉 but there are some kinks to iron out:
> 
> 1. Across all the users I tested, it looks like the 2 column layout is displaying as one column. [Here's a mock-up](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/1KnQlRO), compared to what I see in staging with user 1:
> 
> <img alt="image" width="955" src="https://user-images.githubusercontent.com/55992116/157233190-5acd2017-8fdc-49a4-a021-0f6b0071db11.png">
> 
> 2. The most recent payment isn't showing up for anyone for some reason. I checked the view payment history page for users that are supposed to have a recent payment. The data is showing up there but not on My VA.
> 3. The links are all going to the right places, but opening in a new tab. I am 99% sure the practice on VA.gov is to open them in the same window instead of a opening a new tab. I can't find that documented anywhere, so I'm checking with the UX team. If either of you @tmitchellgcio or @hdjustice could check w/ your practice peeps, you may be able to get an answer sooner than me. I'll report back when I confirm that.
> 
> I'm going to hold off on testing mobile until these issues are sorted out. All my results are [captured in this Google Doc](https://docs.google.com/spreadsheets/d/1qdWFjj128aVoKMNDeUZ8-uAR7ljMayr4kmtr4cU7hq8/edit?usp=sharing).
> 
> Also, I made a couple of updates to the test case doc:
> 
> * I added a test case to the [links section](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/staging-test-accounts-myva-payment-info.md#benefit-payments-and-debts-links), to test the `Manage your VA debt` link when it appears.
> * I updated the user for the direct deposit link test. Although it was displaying for `user+21`, that user doesn't have access to direct deposit information because they are flagged as incompetent. I updated it to `user+1`.
> 
> Putting this ticket back in the blocked column until the above issues are fixed.

1. The two column layout you show is different than the sketch you are showing as it has a deposit on it. Tressa had a sketch where it is one column when it's been more than 30 days since the last payment because it looked to her like too much whitespace. I didn't realize this was updated 3 weeks ago back to 2 columns. Sorry I didn't see this change, but I'm glad it was changed as this reduces some code that had to change formatting based on if a payment exists so it will be easier to read in this case.
2. I am not sure how the system works, but like Heather said they are all past 30 days right now. Hopefully they get paid soon.
3. The links are mirrored the same way that the healthcare links are so if that's wrong we likely have to change that everywhere

**Comment by andaleliz** [comment]
> The two column layout you show is different than the sketch you are showing as it has a deposit on it. Tressa had a sketch where it is one column when it's been more than 30 days since the last payment because it looked to her like too much whitespace. I didn't realize this was updated 3 weeks ago back to 2 columns. Sorry I didn't see this change, but I'm glad it was changed as this reduces some code that had to change formatting based on if a payment exists so it will be easier to read in this case.

Oh, my bad - I linked to the wrong mock-up 😞 . Sorry about that! [Here is the correct mock-up](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/paD25yQ)

I think one column is correct when there are no alerts, or no payment cards. Essentially if it's just text + links, it should be one column. If it includes other components, it should be 2 columns.  And healthcare should be the right way.

>The links are mirrored the same way that the healthcare links are so if that's wrong we likely have to change that everywhere

I think that's because all of the healthcare links are linking to MHV, which isn't part of VA.gov.  Based on that guidance Mikki shared, they technically all should open in the same window, but since that isn't "official" guidance, I would update it so any links pointing internally to our site open in the same window and leave the rest as they are.

**Comment by tmitchellgcio** [comment]
@andaleliz is there a mockup without alerts for debt? I think if there is no debt we also have the text for 0 debt balance. If there are two layers of text for 0 debt and 0 payments in the last 30 days is it one column or two? Also no problem on the links. I think I can fix that and the column issue shortly just want to be sure I'm asking all the right questions for it so I get it right

**Comment by andaleliz** [comment]
Yep, [here's the mock-up](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/R1JK3qy) - it's 1 column in that case.

Keep the questions coming! The [FE specs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/documentation/payment-history-frontend.md) may also be helpful if I can't respond quickly enough. I don't want to hold you up.

**Comment by tmitchellgcio** [comment]
Very helpful! Thank you @andaleliz

**Comment by hdjustice** [comment]
Carrying over to sprint 69 due to some issues found during testing, which halted QA from being fully completed.  Issues are being actively worked on and should be resolved quickly so that QA can resume.

**Comment by hdjustice** [comment]
great, thank you @andaleliz !

**Comment by andaleliz** [comment]
@tmitchellgcio I'm dying to close this out - did you complete your part of this?

**Comment by tmitchellgcio** [comment]
yep I am done with this sorry about the delay
