### ISSUE TITLE
Mulesoft SSL Cert's | VA.gov Platform Fix(es) Required

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#36504]
## What happened?

- Platform fix required for an SSL certification error encountered during integration set-up/testing on staging.
 ## Background

- Same fix will have to be done in prod (and tested) before going live with MS.

## Acceptance Criteria
- [x] Open platform ticket to get this fixed - https://github.com/department-of-veterans-affairs/va.gov-team/issues/36543
- [x] Confirm fix is working as expected in staging (example [PR](https://github.com/department-of-veterans-affairs/devops/pull/10763) of how to achieve)
- [x] Confirm fix is working as expected in production

**Comment by SKasimow** [comment]
Hi @RudyOnRails here's the placeholder ticket we discussed to track platform fix. Let me know if we need to add anything else (or feel free to edit directly - whichever is easier). 

-S

**Comment by RudyOnRails** [comment]
@SKasimow this is incomplete due to the time it is taking to understand the problem. I did not sumbit a DevOps issue until yesterday, and the Devops team is asking for more information about detailed connection instructions to Mulesoft staging and I believe we may actually be able to solve this ourselves by adding the connection to the fwd proxy for each env, and using existing SSL/TLS certs versus trying to connect directly from `vets-api` servers.

Either way, this should be resolved soon! we are getting close I can 👃 it!

**Comment by RudyOnRails** [comment]
@RudyOnRails when you get a chance, try curling to mule staging from staging fwdproxy and  use an existing key and pem like the amazing @jbritt1 exampled on that PR where James switched over the EZ domains.

**Comment by RudyOnRails** [comment]
`curl -vvv https://vapi.va.gov` succeeded already in prod fwdproxy, so we can close this.

comment with confirmation of curl:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/36543#issuecomment-1045013460

comment with confirmation of `VA-Internal-S2-ICA4.pem` cert existing: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36543#issuecomment-1045011429
