### ISSUE TITLE
Analytics Reporting Request for Pension and Burials

### ISSUE THREAD

**Issue by goldenmeanie** [department-of-veterans-affairs/va.gov-team#3665]
# Metrics Reporting Request

## What this form is for

Use this template to request performance, usability, or outcomes va.gov metrics that is difficult to access or that needs analytics interpretation.

Insights will usually provide data reports within the current sprint, but if there is time-sensitivity, please note them in "additional comments."

## Instructions

Please fill out the following sections:
- [ ] Description
- [ ] Timeframe for Analytics Requested
- [ ] Analytics to Track Down
- [ ] Which Product Questions are you trying to answer?
- [ ] Additional Comments

## Description
Who is this request for? Pension (also Burial and DIC) Automation effort.

- [Insert Name(s)]
Alex Taylor
- What team/project is this work for?
    - Pension Automation 🦅 
    

## Timeframe for Analytics Requested
This is not emergent, but it would help with some work prioritization and planning that we are doing right now.

## Analytics to Track Down
We'd like to understand the percentage of burial and pension claims that are coming from the VA.gov version of those forms (vs the overall, mostly paper submissions).

We expect that this is a pretty small number, but would like to understand the trend. There was a slide in a recent presentation that listed 6.5k (↑91%) and 8.0k (↑59%) respectively but I'd like to make sure we have the right context for these numbers. 

<img width="1275" alt="pension-and-burial-stats" src="https://user-images.githubusercontent.com/1969/69432783-567aa880-0d08-11ea-84eb-a8fce2651ea8.png">

I'd especially like to understand the relationship between these trends and points in time like Web Brand Consolidation launch.

## Which Product Questions are you trying to answer?
We want to understand how to weight the impact of work on the digital stream of applications relative to work on the paper-based flow. Not a competition, but we want to be confident in our estimates of impact that different streams of work will bring. We know the digital stream is small but we want to understand its likely growth over the next year.

## Additional Comments
_Add any comments or questions for the Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
Thanks @goldenmeanie - Confirming we have received this and thanks for sharing that picture!  To make sure we're aligned with your pension and burial discovery, are the forms that would be in question the following: 527EZ for Pension, 40-10007 for Pre-Need, and Form 530 for Burial submissions?

Many of the metrics our team compiles will compare the modernized versions of the forms that were on vets.gov vs. WBC-VA.gov. I don't see a footnote on this particular slide but that can serve as our starting point to help you uncover these questions. Can we plan to huddle post-Thanksgiving for :30? 

CC: @joanneesteban

**Comment by goldenmeanie** [comment]
@nedierecel not listing the forms was an oversight on my part!
527EZ and 530 are the two relevant to us. 
If the 40-10007 is commingled in that burial stat in the slide, that would be good to know.

**Comment by nedierecel** [comment]
@goldenmeanie Hope you had a nice Thanksgiving!

I'm adding links directly to Google Analytics within the metrics I've pulled below. The timeframes I pulled are WBC (11/8/2018-11/7/2019) vs. Vets.gov (11/8/2017-11/7/2018) since the modernized launch occurred on 11/8/2018. 

**Unique Successful Submissions of Pensions 527EZ**
[WBC Successful Submissions](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184310106/_u.date00=20181108&_u.date01=20191107&_.useg=&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.eventLabel:pensions-527EZ--submission-successful) - 8,236

[Form 527EZ Successful Submissions](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w107014820p157538327/_u.date00=20171108&_u.date01=20181107&_.useg=&_r.drilldown=analytics.eventLabel:pensions-527EZ--submission-successful&explorer-table.plotKeys=%5B%5D/) - 5,273

**Unique Successful Submissions of Form 530**
[Form 530 WBC Successful Submissions](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w177519031p184297632/_u.date00=20181108&_u.date01=20191107&_.useg=&_r.drilldown=analytics.eventLabel:burials-530--submission-successful&explorer-table.plotKeys=%5B%5D) - 6,599

[Form 530 Vets.gov Successful Submissions](https://analytics.google.com/analytics/web/?authuser=0#/report/content-event-events/a50123418w107014820p157543929/_u.date00=20171108&_u.date01=20181107&_.useg=&_r.drilldown=analytics.eventLabel:burials-530--submission-successful&explorer-table.plotKeys=%5B%5D) - 3,409

There was a gap in tracking for both forms February 2018-April 2018, so the YoY growth is not fully apples-to-apples.

**Comment by goldenmeanie** [comment]
First of all, thank you for pulling these stats!

I read those numbers as
527EZ ↑64% YoY
530 ↑51% YoY (_seems like zooming in on that image failed me here_)
...with the caveat that the 2018 numbers were undercounted (Feb–Apr) and so that growth is probably exaggerated

Does that sound like I'm following @nedierecel?

**Comment by joanneesteban** [comment]
Hi @goldenmeanie !

The submission increase should actually be:
**527EZ** ↑56.19% YoY
**530** ↑93.58% YoY

Let us know if you have any questions!

**Comment by goldenmeanie** [comment]
_Back to school_ for me apparently! Thank you for the correction :)

**Comment by nedierecel** [comment]
@goldenmeanie
