### ISSUE TITLE
[Research] My VA - Payment Info: Create Conversation Guide

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36678]
## Background
Now that designs, development and QA is complete, we are ready to begin UAT on our new functionality.  
The [**UAT Research plan**](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36675) is ready, so next we need to create a Conversation guide.

### Resources
- [UAT research plan example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-research-plan.md)
- [UAT conversation guide example](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/uat/MyVA-uat-conversation-guide.md)
- [VSA UAT Guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/69833737d9fe22b8990bb987e7c50de13205c5d5/platform/research/planning/what-is-uat.md)

## Tasks

- [x] Create a draft Conversation guide
- [x] Tag Samara for review

## Acceptance Criteria
- A Conversation guide and Research plan are ready for submission 
     - (Due to the change in submission process, the tasks are in a separate ticket [**#36679**](https://github.com/department-of-veterans-affairs/va.gov-team/issues/36679))

**Comment by hdjustice** [comment]
@andaleliz Is this Conversation guide done too?
cc @Samara-Strauss

**Comment by andaleliz** [comment]
It is! Just needs a review. I can’t access GH at the moment but I believe I
tagged Samara on this issue Friday.
-- 
Liz Lantz
Senior UX Designer, Ad Hoc
adhoc.team
<https://www.google.com/url?q=https%3A%2F%2Fadhoc.team%2F&sa=D&sntz=1&usg=AFQjCNE4MGCYSFhDl_lZwwTif1R0KYNm0w>
|
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>
@adhocteam
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com%2FAdHocTeam&sa=D&sntz=1&usg=AFQjCNE4GKY_Z86vvRgx9vcdArRxzNO-Hg>

**Comment by Samara-Strauss** [comment]
### Confirm payment feature - X minutes

- Very minor -- you had "UAT TASK: Confirm the payment section is showing" twice, so I went ahead and took one out.

### Confirm debt feature - X minutes

>  Usability: What do they think about the debt information?
>  Usability: What do they think about the number of outstanding debts?

Since Angela is running this and not you (Liz), I would recommend getting more specific with what you're looking for. What are we really trying to assess? It comes down to more than what the user "thinks" or if they like/don't like it, so I would be more specific so it's clearer to Angela what to ask and what to look for.

### 3. Confirm all links - X minutes

>  UAT TASK: Confirm View payment history link is showing for users who do not have a recent payment

This is slightly confusing since this link shows both when people do and do not have payments, albeit it shows in different ways depending on the use case. So I might clarify that so Angela isn't confused.

> Usability: How did Veteran expectations match up with where the links took them?

Was this a point of confusion in our original user testing?

Otherwise, this is great!! Nice work!

**Comment by andaleliz** [comment]
Thanks Samara! Now that I'm in GH, I see I _didn't_  tag you- sorry about that. Totally my bad.

I've made these updates and will close out the ticket:

>Since Angela is running this and not you (Liz), I would recommend getting more specific with what you're looking for. What are we really trying to assess? It comes down to more than what the user "thinks" or if they like/don't like it, so I would be more specific so it's clearer to Angela what to ask and what to look for.

Excellent point! I clarified to: "Do participants who actually have debt find the debt information helpful, particularly the number of outstanding debts?"

> This is slightly confusing since this link shows both when people do and do not have payments, albeit it shows in different ways depending on the use case. So I might clarify that so Angela isn't confused.

Another good point- updated to read: "Confirm View payment history link is showing in the list of links with icons for users who do not have a recent payment"

>Usability: How did Veteran expectations match up with where the links took them? Was this a point of confusion in our original user testing?

No, it wasn't a specific point of confusion, but since we didn't test with anyone who actually had debt, I thought it would be worth checking. I don't feel strongly about it though, so I'll take it out. I feel confident that people will speak up if they're confused about something when they verify a link.
