### ISSUE TITLE
[Research] My VA - Payment Info: Summarize findings from UAT sessions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#36694]
## Background
We have conducted our UAT sessions, we now need to summarize findings from UAT.

## Tasks
- [x] Summarize UAT findings, identifying any changes that will require tickets for scheduling
- [ ] Share summary with the team

## Acceptance Criteria
- UAT summary is completed and shared

**Comment by aagosto90** [comment]
[Link](https://docs.google.com/spreadsheets/d/1fu-suo3XRUVrfhDUqyOhtqjkqrH5L3oWGVq9PAULkOw/edit#gid=0) to notes document from UAT sessions

**Comment by Samara-Strauss** [comment]
@aagosto90 I don't have access to the doc above  -- can you add the notes to [this folder on Github](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/payment-history/uat)? Otherwise, we don't need a formal write-up here and this might be good to close once the summary is uploaded to Github. cc/ @ajakabcin

**Comment by Samara-Strauss** [comment]
Posting this here since I mentioned it in Slack and don't want it to get lost -- since the notes are currently in an Excel file (which has since been uploaded to Github -- thank you), we also need a Github one-pager that is a super quick summary of the results. Nothing formal that will take days to put together, just something quick that summarizes what we did, who we talked to, about what, and any major findings. I don't think this should be more than an hour's worth of work. We just need something that is easier to draw conclusions from than a spreadsheet.

**Comment by Samara-Strauss** [comment]
@aagosto90 [has added findings here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/uat/Benefit%20Payments%20%26%20Debts%20UAT%20Findings%20Summary.md). Closing!
