### ISSUE TITLE
[FE] SPIKE - Address Validator Definition

### ISSUE THREAD

**Issue by julieadair1** [department-of-veterans-affairs/va.gov-team#36745]
## How to configure this issue

- [ ] Attached to an Epic (what body of work is this a part of?)
- [ ] Correctly Labeled
- [ ] Fill in User Stories
- [ ] Fill in Documentation
- [ ] Fill in Tasks
- [ ] Fill in Acceptance Criteria

---
## Description
The profile team has access to an address validator api that we need to use. 
1. How do we access it? 
2. How do we use it? 

- (%FILL IN%)
- (%FILL IN%)

## Related Documentation

> these should be links to feature docs

- [Sketch](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e)
- [Product Docs](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin)
- [Feature Doc](%FILL IN%)

## Description

> this should be an understandable description of the ticket. This description should have enough context meaning that non-technical team members should get the idea.

## Tasks

1. Set up meeting with va profile team to get our questions answered - @julieadair1  to coordinate with Barie Flowers (PM of profile)

- [ ] %Add any tasks%
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria

1. Code sample with a sample request to the address validation api

- [ ] %Add any additional Acceptance Criteria%
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Here are my initial findings. I would like to poke around at the sandbox api a bit more, but am waiting on an API key.

**### How do we access it:**
Sandbox endpoint: https://sandbox-api.va.gov/services/address_validation/v2/candidate
Prod endpoint: https://api.va.gov/services/address_validation/v2/candidate

API docs: https://developer.va.gov/explore/verification/docs/address_validation?version=current 

Requires an API key for the sandbox and production. I have applied for a sandbox key. For production we will need to apply again.

**### How do we use it:**
 We use it by making a POST request to the endpoint with the following body for the address: 
```
{
  "requestAddress": {
    "addressLine1": "string",
    "addressLine2": "string",
    "addressLine3": "string",
    "city": "string",
    "zipCode5": "string",
    "zipCode4": "string",
    "internationalPostalCode": "string",
    "stateProvince": {
      "name": "string",
      "code": "string"
    },
    "requestCountry": {
      "countryName": "string",
      "countryCode": "string"
    },
    "addressPOU": "RESIDENCE/CHOICE"
  }
}
```

It will return a JSON object in this structure: 
```
{
  "messages": [
    {
      "code": "string",
      "key": "string",
      "text": "string",
      "severity": "INFO",
      "potentiallySelfCorrectingOnRetry": true
    }
  ],
  "candidateAddresses": [
    {
      "messages": [
        {
          "code": "string",
          "key": "string",
          "text": "string",
          "severity": "INFO",
          "potentiallySelfCorrectingOnRetry": true
        }
      ],
      "address": {
        "addressLine1": "string",
        "addressLine2": "string",
        "addressLine3": "string",
        "city": "string",
        "zipCode5": "string",
        "zipCode4": "string",
        "internationalPostalCode": "string",
        "county": {
          "name": "string",
          "countyFipsCode": "string"
        },
        "stateProvince": {
          "name": "string",
          "code": "string"
        },
        "country": {
          "name": "string",
          "code": "string",
          "fipsCode": "string",
          "iso2Code": "string",
          "iso3Code": "string"
        }
      },
      "geocode": {
        "calcDate": "2022-02-10T23:46:42.916Z",
        "locationPrecision": 0,
        "latitude": 0,
        "longitude": 0
      },
      "usCongressionalDistrict": "string",
      "addressMetaData": {
        "confidenceScore": 0,
        "addressType": "string",
        "deliveryPointValidation": "CONFIRMED",
        "residentialDeliveryIndicator": "RESIDENTIAL",
        "nonPostalInputData": [
          "string"
        ],
        "validationKey": 0
      }
    }
  ]
}
```

I am assuming that warnings or success will be returned in the messages object. From there we will need to provide displays for several scenarios including but not limited to: 

- Message with warnings and allow the veteran to submit anyway or go back and correct
- Message with alternative suggestions for the address submitted that allow the veteran to choose from or submit anyway or go back and manually correct
- API Error message
- Submission Error (non address validation error)

**### Things to look out for:**
One unfortunate thing is that it looks like the endpoint can sometimes return a non-standard object. For example 401, 403, and 429 errors will return a singular message key with a string value instead of the plural messages key with an array value like so:
{
  "message": “message”
}

Which means that we will need to check for both when catching errors. 500 and 404 errors will return the plural array format.

**Comment by sarahknoppA6** [comment]
Michael Richard on VA Profile team is following up on this- can be closed for now.
