### ISSUE TITLE
Discovery: How could we leverage other open source design systems to help improve our web-component library?

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36777]
## Description
We are a relatively small team responsible for building and maintaining a design system for use in pages and applications across VA.gov. We need to make sure that the components, utility classes, design resources, and guidance we create are high quality and well-tested.

One option for helping us to do this is to leverage other open source design system resources that are supported by larger teams and are well-used and tested.

For this ticket, we'd like to explore what resources are available to us to help improve our component library and evaluate how we might take advantage of them.

## Acceptance Criteria
- [ ] Generate list of resources available
- [ ] Evaluate how we could leverage those resources to help in building and maintaining our component library
- [ ] Add list and evaluations as comment(s) on this ticket.

**Comment by humancompanion-usds** [comment]
Here is my $.02 on this and would love to discuss more. The VA Design System is based on v1 of the USWDS system, which is open source and which taxpayers are already paying for. If we're going to be based on an open source system, it's going to be USWDS. 21st Century IDEA says that all agencies must use the USWDS, or have a good reason not to. Thus we're not going to deviate far from the USWDS. Our system exists in a wider ecosystem of government that we need to be respectful of. If every agency deviates wildly from USWDS we won't really have standards nor cohesion. 

That said, if we're just considering where we might "borrow" components from, the systems we look at would have to be:

1. Open source
2. Share their research in a clear way
3. Have components that are relevant to what is in use, or are components we'd like to use, on va.gov
4. Ideally, to save time, have really considered accessibility
5. Ideally, the driver or raison d'etre of the system has to be in the same ballpark as our system.

If the goal is to identify systems that meet all or some of those criteria and that we can use as a reference point then by all means let's do that. But for me at least, I need a finer understanding of #3 on that list (via audit), especially components and patterns that are in use and not yet in our design system, before I can make that determination. So many design systems out there have the same exact set of components and patterns (and most systems lack patterns entirely or they are just overgrown components) which we or USWDS already have. 

To explain a bit more on #5, while I like to look at other systems such as Google's Material and Adobe's Spectrum, they have a particular focus or bias towards their ecosystem of their products that sometimes makes the problems they are solving for a bit distant to the things we are solving for. From a design perspective, some of those things just are not appropriate or relevant for the tasks Veterans have at hand on va.gov. 

Anyway, again, just my $.02 but some things for us to discuss before we embark on this.

**Comment by k80bowman** [comment]
@humancompanion-usds thanks so much for your input here! Just for clarification, this ticket is centered on our web component library, not our CSS library, and our web components library is not currently based on USWDS. We had a separate [ticket](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/36043) to look into what we could use for our CSS library. So this ticket is not related to jumping to v3.

I do agree with your points about where we might "borrow" components from, though, and thank you for listing those out. The impetus for this ticket was a comment from a previous PO that there may be resources that we could leverage to help our team provide new features more quickly. The original suggestion was to consider building a library based on Bootstrap, though we decided to not go in that direction. I'm not expecting this ticket to result in a decision to move in one direction or another, this is just intended to be a very shallow initial exploration.

**Comment by andresriveratoro** [comment]
In order for us to be able to leverage other design system **components**, we need to have complete control over the styling to match ours. This means that this flexibility has to be explicitly available in the form of props, [shadow parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) or CSS custom properties unless the component wrapper element is the only element we need to style. If that requirement is met, then we need those components to be accessible. This accessibility could be built in or added by us using aria attributes for simple cases.

Auro - https://auro.alaskaair.com/ (partial WCAG 2.0 level AA)
Bolt - https://boltdesignsystem.com/
Carbon - https://web-components.carbondesignsystem.com/
Crayons - https://crayons.freshworks.com/ (i18n)
Elix - https://component.kitchen/elix (customizable using [shadow parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part))
FAST - https://explore.fast.design/
Graphite - https://graphitedesignsystem.com/
Helix - https://helixdesignsystem.github.io/helix-ui/
**Ionic - https://ionicframework.com/docs/components (customizable using part/custom properties and accessible)**
Kor - https://kor-ui.com/introduction/welcome
Lightning - https://developer.salesforce.com/docs/component-library/overview/components
**Lion - https://lion-web.netlify.app/ (customizable and accessible)**
PatternFly - https://patternflyelements.org/components/ (customizable using CSS custom properties)
**Shoelace - https://shoelace.style/ (customizable using part/custom properties and accessible)**
Spectrum - https://opensource.adobe.com/spectrum-web-components/
Vaadin - https://vaadin.com/components (customizable and accessible - some components are not free)
Vivid - https://vivid.vonage.com/
**Weightless - https://weightless.dev/ (customizable and accessible)**

From this list of web component design systems, Ionic, Lion, Shoelace and Weightless provide us with the customization we would need and accessibility. The accessibility provided by these components will have to be evaluated at the component level to see if it meets our requirements.

I think it would be very difficult for us to leverage other design systems in this way because we would be unable to make any updates, fixes or modifications to components if needed. A lot of these design systems were not customizable or accessible. Those that passed the basic requirements did not offer a lot of components that we aren't already using. I think we would be giving up too much control, and the initial time savings could quickly translate to a loss if/when we have to abandon these components when any modification is required.

_While exploring these design systems, I found [zeroheight](https://zeroheight.com/) and  [web-component-analyzer](https://github.com/runem/web-component-analyzer) tools that we may want to look at to improve our documentation. I know it's slightly off topic, but I wanted to document this somewhere._

**Comment by k80bowman** [comment]
Thank you @andresriveratoro! And thanks for the extra resources.
