### ISSUE TITLE
[ArgoCD] Problem with the UI refreshing over and over (refresh loops)

### ISSUE THREAD

**Issue by dginther** [department-of-veterans-affairs/va.gov-team#36782]
## Description
ArgoCD is having an issue where, when you try to access logs, or manifests, or delete/sync an item in the UI, the screen will refresh before things are drawn, and you end up in a loop of screen refreshes.

I'm not sure why this happens, but you should be able to replicate it by going into ArgoCD, going into an application, and then trying to view details on a pod or other resource.

https://user-images.githubusercontent.com/4662758/153455720-0230c87e-f541-4c64-b44e-45f150321924.mov

As you can see, this makes trying to use the UI almost impossible. This will need to be solved before this tool can be used widely.

## Background/context 
This may be related to authentication, which in this case is using the built-in Dex server and Github OAuth, as it does make you re-authenticate. Not sure exactly why it happens. More troubleshooting is needed.

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- [ ] _What things need to happen?_

## Acceptance Criteria 
- [ ] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jhouse-solvd** [comment]
@dginther - Thanks so much for submitting this! I know we're keen on getting it solved. 

We'll follow up as we begin to work through it.

**Comment by jhouse-solvd** [comment]
might impact https://app.zenhub.com/workspaces/platform-infrastructure-team-6112bc325f570300140f7852/issues/department-of-veterans-affairs/va.gov-team-sensitive/406

**Comment by mleclerc00** [comment]
Based on this link, I believe I have found the solution.  https://github.com/argoproj/argo-cd/issues/2347#issuecomment-662139989

The problem being that we do not have a service account that will allow the argocd-server to successfully list resources in another server.

`there needs to be 2 trust relationships for the one role: one for the argocd-server ServiceAccount and one for the argocd-application-controller ServiceAccount`

as seen in the following file we only have a trust relationship for the `argocd-application-controller` https://github.com/department-of-veterans-affairs/devops/blob/70f7075e536cfaaf0dd69300e3d1729dd37df5d3/terraform/environments/dsva-vagov-utility/eks.tf#L315

In order to fix this we will need to 
- create a new service account for `argocd-server`
- create the trust relationship for it to assume the correct role in aws
- tie the role back to the `aws-auth` configmap and map to a user for every cluster 
- create a role, and role binding for said user that allows the correct permissions to list resources within in each cluster itself (https://github.com/argoproj/argo-cd/tree/master/manifests/base/server)

**Comment by mleclerc00** [comment]
This is now fixed, the problem was indeed that the `argocd-server` service account that lives in the utility cluster did not have the proper permissions to query the external servers.

After creating the trust relationship with aws and then tying it back to the aws-auth map on the other clusters everything works as expected.

The real gotcha here is that the trust relationship with aws is created by adding a annotation to the service account in utility  (https://github.com/department-of-veterans-affairs/vsp-infra-argocd/blob/0a1fb7ff1244d345562be9f70f7b1da71c2aed34/chart/values.yaml#L64)

However this link was not truly initialized until I deleted the `argocd-server` service account and recreated it.  Patching the account that already existed previously did not work.

**Comment by pavankumar-go** [comment]
For those EKS users facing this issue
create an IAM role or create IRSA (IAM role for service accounts) for both argocd-application-controller & argocd-server
with eks:ListCluster & eks:DescribeCluster permissions to the target/external cluster.
Now on the target/external cluster 
edit aws-auth configmap and append both roles to `mapRoles`
```
    - rolearn: arn:aws:iam::REDACTED:role/irsa-application-controller
      username: arn:aws:iam::REDACTED:role/irsa-application-controller
      groups:
      - system:masters
    - rolearn: arn:aws:iam::REDACTED:role/irsa-argocd-server
      username: arn:aws:iam::REDACTED:role/irsa-argocd-server
      groups:
      - system:masters
 ```

**Comment by jhouse-solvd** [comment]
@dginther - Can you verify that this is working as expected from your perspective?
