### ISSUE TITLE
Manual Functional Tests: Decide on Display Method

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#36800]
## Issue Description
Discuss and determine the approach for how the Manual Functional Testing cards are displayed

---
## Tasks
- [x] Discuss the best approach for cards (detail additional tasks as needed

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_

**Comment by CBonade** [comment]
One hurdle we will have here relates to https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-team/issues/36802.

Because this data ingestion is not currently functioning, two of these cards are not able to update their stale data. Domo's default when it can't update stale data, is to keep the old data as opposed to wiping it.  This will not permit us to figure out a proper display method for these two cards until the data ingestion is fixed.

Impacted cards: Fail Rate and Defects created

Other cards will be able to proceed with refinement.

**Comment by CBonade** [comment]
I was able to convert our two cards that are displaying data to a single number display. Domo is fairly limited on display options for numbers that exist in isolation without any comparison happening. I'll continue to evaluate options that may be better for this. I believe that the other option we've used of the gauge only works well if you have a max target (such as a percentage out of 100).

**Comment by CBonade** [comment]
I do not believe we have plans to change any of this at this time. We have added another chart since then and have planned for release with these cards in their current display formats. Moving this to review.

**Comment by pjhill** [comment]
Yeah, we are in good shape with MFT for the MVP. Thanks!
