### ISSUE TITLE
Content Request from Authenticated Experience - Profile Team for Personal Information Revision 

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#36862]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [X] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [X] Content support
  - [ ] IA support
  
We continue to work on a new personal information page for the VA.gov Profile and need Content to review the language in the accordion help text and error messages to confirm they meet VA standards.

Updating 2/2022 to add three new tasks that came of the meeting between Danielle and Christina:

- Language around "If not listed, please provide your ___
   - 0ther language options for this sentence, such as not using "provide" and maybe exploring "self describe.
- Language around "Prefer not to answer" selection logic. 
    - (unchecks other boxes) - consider "selections" or "options" instead of "boxes"
    - Danielle would like to talk through the instructions for the checkboxes.
- Preferred name - do we add "first"? 
   - Danielle has been working on something similar with Dené on this so wants to look at what they've already worked through and see how that can apply. 

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/personal-information/personal-information-revision/README.md
- Link to or attach user flows: 
- Link to prototype or mockups:  
    -  Why do we ask for this info: https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/kavvLel
    - How do I update my name and date of birth: https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/kavvLel
    - Alerts/error messages:  https://staging.va.gov/profile/personal-information - log in as user 36, select "do not wish to answer" for Pronouns, and then attempt to select another option for Pronouns.
- Link to any epics/issues that may be helpful:  

## Will this work be going through the Collaboration Cycle?
- [X] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: mid-late April
- Estimated staging review date: Mid-March
- Content and IA work needed by: Mid-March

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Marci McGuire
-	Designer: Christina Geldanske
-	FE engineer: Adam Whitlock
-	Product/team Slack channel: #vsa-auth-profile

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by MarciMcGuireGCIO** [comment]
@DanielleThierryUSDSVA - I thought we already had a ticket for reviewing/editing the content for the new Personal Information page, but I don't see it, so I'm creating this one to capture time you spend reviewing the info text and warnings, error messages.  Thanks!  cc @cgednalske @adamwhitlock1

**Comment by MarciMcGuireGCIO** [comment]
Thank you @Samara-Strauss !

**Comment by DanielleThierryUSDSVA** [comment]
Hi @Samara-Strauss @MarciMcGuireGCIO @cgednalske. Content recommendations below. A few notes:

- I think we talked about usability research showing that it's better to include "why we ask" info specific to each field. And I see that in the designs, which is great. Are you thinking we also still want the overall "Why we ask" FAQ at the top of the profile? I'm not sure it's needed if we provide that information contextually within each field. 
- For gender identity and sexual orientation, the "why we ask/what to know" information is pretty long even before we add more depth in an R&S article. I'm wondering what you all think about potentially including some of the info up front and then an addition info component of "What to know before you share this information"? Let me know what you think of the suggestion below. Or we can simply plan to include a link to the R&S article when that's ready instead of trying to add everything here.
- I think we should separate out the 2 different reasons a person might need to update your name or date of birth: 1) They changed their legal name or 2) There's a misspelling or other error in their name or date of birth. There are different processes for each. For the more complex process of reason 1, we can link out to the Resources and Support article. We should run this note by the VHA folks who provided the fact sheet info on this (and check with VBA too). In the future, we can create an R&S article on requesting corrections in personal information, but let's just keep here for now given the content team's limited capacity at this time.


## "Why we ask" information

### Preferred name (also called a chosen name or name-in-use)
Share this information if you'd like us to use a first name that's different from your legal name when you come in to VA. Please know that we can’t use a preferred name in certain documents that require a legal name.

### Pronouns
Share this information if you'd like to help us understand the best way to address you. For example, choose “she/her” if you’d like us to say, “She’s ready for her appointment now.”

### Gender identity
If you get health care at VA, this information can help your care team better assess your health needs and risks. But you don’t have to share this information in your VA.gov profile.

_[additional info component link]_ What to know before you share this information
We follow strict security and privacy practices to keep your personal information secure. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information. If you want to share your gender identity in your health records only, talk with your health care team.

### Sexual orientation
If you get health care at VA, this information can help your care team better assess your health needs and risks. But you don’t have to share this information in your VA.gov profile.

_[additional info component link]_ What to know before you share this information
We follow strict security and privacy practices to keep your personal information secure. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information. If you want to share your sexual orientation in your health records only, talk with your health care team.

## How do I update my name or date of birth?
### How to update your legal name
If you've changed your legal name, you'll need to tell us so we can change your name in our records.
[Learn how to change your legal name on file with VA](https://www.va.gov/resources/how-to-change-your-legal-name-on-file-with-va/)
### How to fix an error in your name or date of birth
If our records have a misspelling or other error in your name or date of birth, you can request a correction. We'll ask for a current photo ID that shows proof of the correct information. We’ll accept a government-issued photo ID, driver's license, or passport as proof.

Here’s how to request a correction:

- **If you’re enrolled in VA health care,** contact your VA medical center.
[Find your VA medical center](https://www.va.gov/find-locations/?page=1&facilityType=health&serviceType)

- **If you receive VA benefits but you’re not enrolled in VA health care,** call us at 800-827-1000 (TTY: +711). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m. ET.

**Comment by Samara-Strauss** [comment]
First and foremost, I love all the content you put together. No suggestions on my part.

> I think we talked about usability research showing that it's better to include "why we ask" info specific to each field. And I see that in the designs, which is great. Are you thinking we also still want the overall "Why we ask" FAQ at the top of the profile? I'm not sure it's needed if we provide that information contextually within each field.

We do **not** plan on still including "Why we ask" info at the top. That should all be in-line as you've outlined.

> For gender identity and sexual orientation, the "why we ask/what to know" information is pretty long even before we add more depth in an R&S article. I'm wondering what you all think about potentially including some of the info up front and then an additional info component of "What to know before you share this information"? Let me know what you think of the suggestion below. Or we can simply plan to include a link to the R&S article when that's ready instead of trying to add everything here.

I won't prescribe a specific design solution -- Christina knows the design system and potential solutions better than I do -- BUT, what I will say is that I LOVE what you outlined and want to include as much of it on the page as possible before we link out to R&S. It's clear, it's helpful, and it's necessary to state the this is not just health information without making people go to another page.

> I think we should separate out the 2 different reasons a person might need to update your name or date of birth

Totally fine by me. I love what you outlined.

> I tried signing in to staging with user 36, but it wasn't working. Could you paste a screenshot of the error message in question here?

@cgednalske or @MarciMcGuireGCIO, can you provide a screenshot? I'm not sure which error we're looking for copy updates on.

**Comment by cgednalske** [comment]
@Samara-Strauss @DanielleThierryUSDSVA @MarciMcGuireGCIO --- with the new changes to the checkbox logic Adam is working on, the error message in question should no longer be included. So I think we can disregard that one! 

As part of some of those new content considerations coming up that Danielle and I discussed at office hours last week, this is related to how we can instead explore clarifying this logic by including "instructions" for the multi-select checkboxes to accompany the "(unchecks other boxes)" that was added to "Prefer not to answer." This no magic solution was also suggested by Josh to help with accessibility.

<img width="688" alt="Screen Shot 2022-02-22 at 11 14 32 AM" src="https://user-images.githubusercontent.com/79372956/155197985-48709d5b-0fd5-445a-b16b-40b8a0dfbc2f.png">

**Comment by cgednalske** [comment]
I agree with Samara on all points - love what you've outlined @DanielleThierryUSDSVA! 

> I think we should separate out the 2 different reasons a person might need to update your name or date of birth

One clarification I have: are you referring to including these items where the FAQs were at the top? That's my understanding and seems like the only option because legal name does not have a field on the page, but want to double check I'm interpreting that correctly.

> For gender identity and sexual orientation, the "why we ask/what to know" information is pretty long even before we add more depth in an R&S article. I'm wondering what you all think about potentially including some of the info up front and then an additional info component of "What to know before you share this information"? Let me know what you think of the suggestion below. Or we can simply plan to include a link to the R&S article when that's ready instead of trying to add everything here.

The design system does not recommend grouping hint text and an [additional info component link] together, nor does it specifically discourage it. Based on discussions with Angela I'm fairly confident that for accessibility the preference would be the following:

    Heading
    Hint text + link to outside page.

But I will also check into the following to see if it this combo was ever considered when added to the experimental design system, and what sort of accessibility challenges it may or may not present. Our case might be unique because it's so important to be upfront about considerations around providing this info. 

    Heading
    Hint text
    FAQ/dropdown with additional info

**Comment by Samara-Strauss** [comment]
> One clarification I have: are you referring to including these items where the FAQs were at the top? 

@cgednalske this is how I am interpreting this as well -- there would be two FAQs at the top of the page as Danielle outlined.

> The design system does not recommend grouping hint text and an [additional info component link] together, nor does it specifically discourage it. Based on discussions with Angela I'm fairly confident that for accessibility the preference would be the following:

Now that we have content, it might be helpful to regroup with Angela/Josh to explain the problem and why it's so important for us to be up front and not relegate helpful information to another page. But that is totally up to you. Just something I would suggest if you'd find it helpful.

**Comment by cgednalske** [comment]
@Samara-Strauss definitely agree! Would like to sync up with Shawna first to make sure I'm clear on the considerations and explorations that went into adding the different hint text formats to the experimental design system (she led that initiative), and then absolutely regroup with Angela/Josh to talk through the circumstances and see how we can best balance transparency and accessibility.

**Comment by MarciMcGuireGCIO** [comment]
@DanielleThierryUSDSVA cc @cgednalske I added three tasks in the description up top based on the meeting you two had last week.

**Comment by cgednalske** [comment]
Hi @DanielleThierryUSDSVA!  @Samara-Strauss, @MarciMcGuireGCIO, and I met today to review the desktop and mobile designs with the new hint text added. With all information above included, we found the fields to appear a bit too text-heavy, particularly on mobile. While still aiming to include as much of this information as possible, we have a few thoughts for minor changes that we'd like to run by you.

Below are some proposed edits that we hope can help shorten the copy without changing much of the information you've presented. When you get a chance to review, could you please let us know your thoughts or if you have any different suggestions? Thank you!

## Preferred name and Pronouns
We'd like to shorten the hint text for these two fields to include only the first sentence of each. Because there weren't necessarily concerns with the inclusion of the two fields in research, mostly clarifying questions, we're wondering if we could do without the examples/details to help with spacing. 

### Preferred Name
**Previous:**
Share this information if you'd like us to use a first name that's different from your legal name when you come in to VA. Please know that we can’t use a preferred name in certain documents that require a legal name.

**Proposed Update:**
Share this information if you'd like us to use a first name that's different from your legal name when you come in to VA. 

### Pronouns
**Previous:**
Share this information if you'd like to help us understand the best way to address you. For example, choose “she/her” if you’d like us to say, “She’s ready for her appointment now.”

**Proposed Update:**
Share this information if you'd like to help us understand the best way to address you.


## Gender identity and Sexual orientation

For the Gender identity and Sexual orientation fields, we'd like to take the current hint text and incorporate it into the "What to know before you share this information" additional information component (dropdown) with the rest of the information, so that the bulk of the text is in the dropdown.

We'd then like to change the hint text to something very short than can clarify the fields are optional, so this is still immediately clear. 

**Previous:** 

_Hint text:_
If you get health care at VA, this information can help your care team better assess your health needs and risks. But you don’t have to share this information in your VA.gov profile.

_Dropdown:_
We follow strict security and privacy practices to keep your personal information secure. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information. 
If you want to share your gender identity in your health records only, talk with your health care team.


**Proposed Updates:**

_Hint text:_ 
Very short phrase conveying this field is optional

_Dropdown:_
If you get health care at VA, this information can help your care team better assess your health needs and risks. But you don’t have to share this information in your VA.gov profile.

We follow strict security and privacy practices to keep your personal information secure. But you should know that any information you share in your VA.gov profile goes into your VA-wide records. Veterans Benefits Administration and National Cemetery Administration staff can also access this information. If you want to share your gender identity in your health records only, talk with your health care team.

---------------

For reference, here are examples of the mobile screens with the current hint text length compared to the (approximate) proposed hint text length:
 
<img width="353" alt="Screen Shot 2022-03-01 at 4 16 00 PM" src="https://user-images.githubusercontent.com/79372956/156264931-02873cdd-b0d7-4e38-8801-d1a4b6b53b9c.png">

**Comment by MarciMcGuireGCIO** [comment]
@DanielleThierryUSDSVA hi!  I know you are overloaded; just wanted to confirm that you saw this note I left last week 

>https://github.com/department-of-veterans-affairs/va.gov-team/issues/36862#issuecomment-1049923719  

I'm happy to create a separate ticket if you prefer.  Thanks, and let me know

**Comment by DanielleThierryUSDSVA** [comment]
I did, yes, thank you, @MarciMcGuireGCIO!

Yes, let's try the shorter versions. If we see that there's any confusion in the future, we can always revisit.

For gender identity and sexual orientation, I think "This field is optional" is probably good there, and then with the hint text.

**Comment by Samara-Strauss** [comment]
Question for the group: Do you think it is confusing if we don't also have "This field is optional" for preferred name and pronouns? I wonder if the omission implies that they are required when they are not. One idea to clarify things would be to use the FAQ for preferred name and pronouns as well. Hint text would be "This field is optional", and the FAQ for preferred name and pronouns would be what we currently have as the hint text.

Let me know your thoughts!

**Comment by cgednalske** [comment]
@Samara-Strauss If we can manage it, it sounds like it's better for accessibility to have only hint text wherever possible rather than a dropdown in every field - just to avoid having too many reveals and also to lighten the interaction load a bit. But I definitely see what you mean about it possibly implying the others aren't optional!

In standup today, Tom, Marci, and I were reminded of how Tom and Adam had determined we can now add the Remove button in the Personal info fields like elsewhere on Profile. With the addition of that button, could we possibly go without "This field is optional" completely? 
(We can't remember during which standup this took place, so not sure if you were there for that or not.)

**Comment by Samara-Strauss** [comment]
> If we can manage it, it sounds like it's better for accessibility to have only hint text wherever possible rather than a dropdown in every field - just to avoid having too many reveals and also to lighten the interaction load a bit. But I definitely see what you mean about it possibly implying the others aren't optional!

Thanks for letting me know. I definitely don't want to introduce any accessibility hurdles, but also don't want it to be confusing what is optional (all of the fields). We might need to continue iterating on this.

> In standup today, Tom, Marci, and I were reminded of how Tom and Adam had determined we can now add the Remove button in the Personal info fields like elsewhere on Profile. With the addition of that button, could we possibly go without "This field is optional" completely?

We never made a decision on whether to add a "remove" button or not. Ultimately, this comes down to whether the backend will accept us removing a selection. Tom should be able to determine this. From a product perspective, it's not required to allow removal, but I also don't think it's not allowed.

**Comment by DanielleThierryUSDSVA** [comment]
@Samara-Strauss I'm glad you raised that! I'd wondered a bit about that too, and then thought it was likely okay because the hint text for the other fields' hint text implied that those fields are optional too. But I do think explicitly calling out optional in these fields only could muddy that message.

A few additional thoughts:
- I like the "Remove" button approach
- We could also rewrite the hint text for gender identity and sexual orientation to be more like the hint text for the other optional fields, like this: "You may want to share this information if you receive health care from VA."
- Another approach (maybe with or without the "Remove" button) - could we potentially just have the additional info component (with no hint text) and have that link text read as something like this: "What to know before you decide if you want to add this information"

**Comment by Samara-Strauss** [comment]
OK, so it sounds like we are all in agreement on the following:

- Look into whether backend can support removal of information. 
- Don't only have "this is optional" for only two fields.

> We could also rewrite the hint text for gender identity and sexual orientation to be more like the hint text for the other optional fields, like this: "You may want to share this information if you receive health care from VA."

IMO, I think we already cover this well in the dropdown.

> Another approach (maybe with or without the "Remove" button) - could we potentially just have the additional info component (with no hint text) and have that link text read as something like this: "What to know before you decide if you want to add this information"

I would be open to this, though it sounds like accessibility wants us to avoid the dropdowns as much as possible.

**Comment by MarciMcGuireGCIO** [comment]
^^ Agreed on points #1 and #2.  I also think the dropdown covers the reason for sharing the info.

I also believe the Remove button is sufficient to imply the fields are optional, but Staging review will prove that out.  Platform Content may disagree.

**Comment by Samara-Strauss** [comment]
So "remove" IS possible -- confirmed with Tom -- so if we add that in, we can potentially do without the "this is optional" helper text.

**Comment by MarciMcGuireGCIO** [comment]
^ My vote is for this as well.

**Comment by cgednalske** [comment]
I also vote for remove button and no "this is optional" text if possible ^

Josh confirmed that it is better not to use the dropdown in all fields. His message below is referring to two examples I sent him: one with dropdown components in Gender identity and Sexual orientation only and another with one in every field. He also has a suggestion for a small change in wording within the Gender identity and Sexual orientation dropdowns.

> The former would be better as having a large amount of repeating interactive content can create a lot of noise for screen reader users who prefer to navigate by interactive items on the page.
> I'd also recommend uniquely labelling your additional information components. For example , "What to know before you share your gender identity" instead of "What to know before you share this information."

**Comment by adamwhitlock1** [comment]
+1 for adding the removal button

**Comment by cgednalske** [comment]
To confirm, can I go ahead and start adding the Remove buttons and removing the "This field is optional" text in Gender identity and Sexual orientation? Sounds like we are all in agreement but want to double check before I start changing the Sketch symbols. Thanks!

**Comment by MarciMcGuireGCIO** [comment]
@cgednalske Yep; I believe everyone in in agreement on that change -- thank you!.  Please check the language on other similar buttons (do they say Remove or Delete?)  @tpharrison, @adamwhitlock1 - can you verify that this is still feasible if we end up using MPI instead of VA Profile?  cc @Samara-Strauss

**Comment by Samara-Strauss** [comment]
@cgednalske yes, you can add the remove buttons (echoing Marci to double-check copy)

> an you verify that this is still feasible if we end up using MPI instead of VA Profile

We are still integrating through VA Profile no matter what, but regardless, we should be able to end date information no matter what.

**Comment by MarciMcGuireGCIO** [comment]
@DanielleThierryUSDSVA @cgednalske Updating this ticket to note that in our last meeting with VA Profile, we were advised that a remove function is only available for SOME of these fields.  The delivery team agreed that having remove buttons on some fields and not others would create confusion and likely generate support calls, so we will not have the option on any of the new personal info fields.

Since the remove buttons are being removed, we will need to include language stating that the fields are optional

**Comment by SKasimow** [comment]
@cgednalske @Samara-Strauss - just doing some board clean-up; is this ok to close out?

**Comment by Samara-Strauss** [comment]
Yep! Thanks for checking.
