### ISSUE TITLE
Table web component: development - sort functionality

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#36938]
## Description
Add sort functionality to the table web component

## Acceptance Criteria
- [ ] Add sort functionality to the table web component
- [ ] Add Chromatic link to #36835, assign ticket to Courtney, and move ticket to Current Sprint column
- [ ] Once accessibility review is complete, alert Carol that component is ready for staging review
- [ ] Address any staging review comments

**Comment by caw310** [comment]
Staging review scheduled on 3/31.

**Comment by bkjohnson** [comment]
>  The sorting column’s header becomes a button whose text is the header text. But the button also has an aria-label that doesn't include the button's actual text. So screen readers won't announce all the relevant information, and voice command software won't successfully match if a user speaks the on-screen text.

So, this is what you're talking about, right?

![image](https://user-images.githubusercontent.com/2008881/160936841-b5cc3573-824a-4dd0-9188-822e7ba307e2.png)

Do you have a recommendation for what the `aria-label` of the button should be? Also, this would not be a regression since it is [modeled after the implementation in the React component](https://github.com/department-of-veterans-affairs/component-library/blob/3c44d4a5e3b134c8d8be692fde19caa9e708cdda/packages/react-components/src/components/Table/Table.jsx#L58-L67), but is it a "must-fix" type of issue?

![image](https://user-images.githubusercontent.com/2008881/160937310-e612a1aa-35b5-4914-83b1-6d151f5897be.png)

**Comment by CourtneyChambers77** [comment]
@bkjohnson can we add in caption for the tables
