### ISSUE TITLE
Residual discovery following Veteran session on 11/20

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3700]
## Problem Statement
During a screen sharing session with a Veteran on 11/20, the team was unable to identify what was preventing the user from submitting a claim. 

## Goal
_Identify what caused the FE issue for the user_

## Acceptance Criteria
- [x] Issue identified
- [x] Front-end issue created with work needed to resolve the problem _(if needed)_

**Comment by Mottie** [comment]
I've spent some time trying to replicate this issue today... no luck so far.

I did the following tests on user 228 on the dev.va.gov site. The form did not submit, but immediately showed an error after making a server call. In the situation the veteran showed us, the front-end stalled (showing only a grayed out submit button with a progress indicator) and did not make server call.

### Less likely causes

The problem may not be an issue with the following settings since the page did make a server call (veteran references are from the save in progress JSON):

- Including additional private medical records - I only uploaded 2 pdfs, the veteran had uploaded 34
- Including supporting evidence - I only uploaded 1 pdf, the veteran had uploaded 2
- Ask for medical records from a specific treatment facility - veteran used his own name in the facility autocomplete, I used a mock name

### Unknown

The following settings could not be replicated (so far):

- Veteran had 7 rated disabilities, the mock user only had 4
- Veteran had 1 previous rated disability selected and one new worsened condition added. I'm not able to coax the form (or maybe just the mock user I chose) to add both
- 3 incidents & secondary incidents with no data - not sure where this is modified in the form

**Comment by Mottie** [comment]
After attempting to duplicate this issue on the local server, the only way I could get the submit button to get stuck in progress (grayed out), was to prevent the API call from completing - in dev talk, we prevent the `submitFormFor` promise from resolving or rejecting. I have not been successful at trying to duplicate this issue from entering "similar" data into the form - it's essentially guess-work at this point.

In order to prevent this process from getting stuck, I think adding a timer for about 10 (or more) seconds that then automatically aborts would prevent this "stuck" state. In addition, we could output some essential data to the console log, so that we can better troubleshoot this problem when it happens in production. This output will contain PII, but it will be permanently erased if the user closes the tab or reloads the page.
