### ISSUE TITLE
HLR: Add other benefit types

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#37468]
## Description

Lighthouse has removed the gating for Higher-Level Review benefit types. For phase 1, only "compensation" type claims could be made, but in this next phase all types can be submitted.

See https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/constants/BENEFIT_TYPES.json

```js
{
  "compensation": "Compensation",
  "pension": "Pension & Survivor's Benefits",
  "fiduciary": "Fiduciary",
  "insurance": "Insurance",
  "education": "Education",
  "voc_rehab": "Veterans Readiness and Employment",
  "loan_guaranty": "Loan Guaranty",
  "vha": "Veterans Health Administration",
  "nca": "National Cemetery Administration"
}
```

## Tasks

- [ ] Add other enum types to `VetsJsonSchema::SCHEMAS.fetch('HLR-GET-CONTESTABLE-ISSUES-REQUEST-BENEFIT-TYPE')['enum']`

## Definition of done

- [ ] All tasks complete

**Comment by michelpmcdonald** [comment]
Dev notes:
Benefits type is used in the call to get a vets "contestable issues"

There are two related v2 endpoints that lighthouse offers to get contestable issues:
(https://developer.va.gov/explore/appeals/docs/decision_reviews?version=current)
**/appeals/v2/decision_reviews/higher_level_reviews/contestable_issues
/appeals/v2/decision_reviews/contestable_issues/**

**/appeals/v2/decision_reviews/higher_level_reviews/contestable_issues** is currently documented as only having one valid benefit type: 'compensation'

**/appeals/v2/decision_reviews/contestable_issues/** is documented to accept the following benefit types:  compensation, pensionSurvivorsBenefits, fiduciary, lifeInsurance, veteransHealthAdministration, veteranReadinessAndEmployment, loanGuaranty, education, nationalCemeteryAdministration

I think Lighthouse would like us to use **/appeals/v2/decision_reviews/contestable_issues/** based on a past casual conversation I had with them....and it might be required to switch to this endpoint since it seems to be the endpoint that can offer the needed contestable_issues benefit types we are moving towards.
