### ISSUE TITLE
<VA Education Inbox> from <My Education Benefits>

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-team#37492]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*
The My Education Benefits team is submitting an additional request for your team's review per recommendation from our midpoint review (https://github.com/department-of-veterans-affairs/va.gov-team/issues/37328). The product we're asking you to review is the VA education inbox (the MVP version of our Secure Inbox). We're seeking additional feedback/approval on our tool's proposed entry points, the static unauthenticated page content, and any other desired content/IA feedback. 

The VA education inbox is a the MVP version of the Secure Inbox that we brought through the collaboration cycle in late 2021. Designs have been simplified for the MVP release so that students are able to view their decision letters when applying for Post-9/11 GI Bill benefits. A Link to the collection can be found at: https://share.goabstract.com/d47c74f7-251c-4e31-86f6-27bbfeaaf9e3 . 

## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows: https://accenturefederal.invisionapp.com/freehand/VA-Edu-Inbox-User-Flow-fqQ0RWoGi?dsid_h=b39bd77e328532dc226ff76c90d5741f934a8ed1196eb0d7f1a9409366794ea1&uid_h=3850c01aa08037284fab1cff4c26de053d5bcd667acc2f234dd81dce8e213d01 
- Link to prototype or mockups: https://share.goabstract.com/d47c74f7-251c-4e31-86f6-27bbfeaaf9e3 
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/36497

## Will this work be going through the Collaboration Cycle?
- [x] Yes - completed midpoint review.  
- [ ] No

## When does this work need to be done?
- Estimated launch date: TBD
- Estimated staging review date: TBD
- Content and IA work needed by: Wednesday, March 2nd

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name:  My Education Benefits
Leelah Holmes
Gaige Dickerson
Alex Ferzola
Audra Ayotte

OCTO-DE product lead: Matt Self
Product manager: Shamik Desai
OCTO-DE Design Lead: Ryan Thurlwell

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
For reference, IA work is documented here:  https://github.com/department-of-veterans-affairs/va.gov-team/issues/30790

**Comment by bethpottsVADEPO** [comment]
@alexander-ferzola Thanks for the meeting! Here's some content feedback for you so these screens align with our VA.gov voice, style, and plain language standards. The H1s I have here match the IA guidance you've received from @mnorthuis 

## TOOL LANDING PAGE

**H1: Download your VA education letters**

1/ For the intro:
If you're a Veteran and you recently received your VA education Certificate of Eligibility (COE) or a denial letter, you can download it now. (we'll update the intro text as types of letters get added for download)

2/ Add an info alert (in drupal this is a gray box with a blue stripe down the left side), as on this page:
https://www.va.gov/education/about-gi-bill-benefits/post-9-11/

Text for info alert: 
**You'll have access to other types of education letters here soon**
Right now you can download only your education COE or denial letter. But we're working to make other types of education letters available too.

2/ Change "Can I use this tool?" to "Who can download VA education letters?" 

3/ The second H2 feels misleading since the user can't "see" the information, but rather the action is to download the letter: **What information will I be able to see?** I'd recommend bringing the information in the blue box up under the first H2 in the form of a note--and there's no need for a blue box. (see below)

4/ I'd cut "In your VA education inbox you'll find" and what's under it since we're refocusing this page entirely and this would be repetitive.

With all the above changes, the page would look like this:

H1: **Download your VA education letters**

INTRO (we'll update the intro text as types of letters get added for download)
If you're a Veteran and you recently received your VA education Certificate of Eligibility (COE) or a denial letter, you can download it now.

[sign-in modal]

INFO ALERT
--------------------
**You'll have access to other types of education letters here soon**
Right now you can download only your education COE or denial letter. But we're working to make other types of education letters available too.
--------------------

H2: **Who can download VA education letters?**

You can download your education letters if you're a Veteran and you meet both of the requirements listed here. At this time, family members and dependents can't get their education letters online.

**Both of these must be true:**
- You applied for Post-9/11 GI Bill benefits, **and**
- You received a decision from us about your application after Month Day, Year

**Note:** If you have an older COE or denial letter—or you're a family member or dependent—you can contact us through Ask VA to request a copy of your letter. [Request your VA education letter through Ask VA](https://ask.va.gov/)


## AUTHENTICATED: The user has a letter on file

General feedback: Usually we only enable the TOC when it's a long page. Because this page is pretty short, I'd advise against it. 

H1: **Your VA education letters**

INTRO (again, we'll update the intro text as types of letters get added for download)
Download your VA education Certificate of Eligibility (COE) or denial letter.

H2: **Letters available for you to download**

GRAY CARD
Education COE
This letter is proof of your eligibility for VA education benefits. It shows details like which program you're getting benefits through, the percentage of benefits you're entitled to, and the time limit for using your benefits. 

H2: **How do I download and open a letter?** (I want to note here that we have an article about [how to download PDF fillable forms](https://www.va.gov/resources/how-to-download-and-open-a-vagov-pdf-form/), but it is too specific for this use case of downloading PDF letters. However, my team is looking to expand the scope of this article, probably in Q2, at which point, from this DGIB screen we could just point to that article)

First, you'll need to make sure you have the latest version of Adobe Acrobat Reader installed on your computer. It's free to download. [Get the latest version of Adobe Acrobat Reader]

**Then, follow these steps to download and open a PDF letter:**
See this example of a subway map: https://www.va.gov/health-care/apply/application/introduction

(1) Click on the link on this page for the letter you want to download. The PDF will download to your Downloads folder. You can save it to a different folder if you'd like.

**Note:** If the PDF form opens in your browser automatically or if you get a “Please wait” error message, you'll need to take one more step to download the PDF: Click on the download icon in your browser. Save the PDF to your device.

(2) Open Adobe Acrobat Reader.

(3) From the File menu, chose **Open**.

(4) Go to your Downloads folder or the location on your device where you saved the PDF. Select the PDF and your letter will open.

H2: **What if my letter isn't listed here?**
At this time, we only have letters available here that you received a decision on after Month Day, Year. To request a copy of an older letter, you can contact us through Ask VA. [Request your VA education letter through Ask VA](https://ask.va.gov/)

## AUTHENTICATED: The user has no letter on file

General feedback: 
1/ I'm concerned about saying "on file" in this messaging since VA would have them on file, just not available through this tool. See my suggestions below.
2/ I'm not sure we need to say this on each screen (as well as on the tool landing page). It may be overkill. But let's see how it works. 

**We don't have any letters available to you through this tool**
At this time, we only have letters available here that you received a decision on after Month Day, Year. To request a copy of an older letter, you can contact us through Ask VA. [Request your VA education letter through Ask VA](https://ask.va.gov/)

**Comment by alexander-ferzola** [comment]
@bethpottsVADEPO  @mnorthuis 

Thank you for all of the in-depth feedback. We'll work with our Product owners to incorporate as much of this feedback as possible. We'll keep you in the loop for anything substantive we cannot implement. Appreciate the review!!

**Comment by mnorthuis** [comment]
@cesaresantiago @btruongafs Assigning to you for reference for your upcoming staging review on the download letters work (formerly referred to as Inbox)

**Comment by mnorthuis** [comment]
@btruongafs Given this has now gone through staging review, can we close this issue?

**Comment by btruongafs** [comment]
@mnorthuis yes nothing else needed from our team.

**Comment by bethpottsVADEPO** [comment]
Closing ticket. @RLHecht for awareness
