### ISSUE TITLE
ADDRESS - [FE] Implement Logic for Address Page

### ISSUE THREAD

**Issue by sarahknoppA6** [department-of-veterans-affairs/va.gov-team#37619]
## User Story
As a veteran, I would like to be able to update an address for me, my emergency contact, or my next of kin so that the VA has my most recent information. 

## Wireframe
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/760BBCDA-2157-4F1F-BC42-AE6B2730B869

## Description
- Given I
    - Am performing pre-check-in
- When I
    - Am asked to confirm any contact information that has an address
    - Choose to edit the address for the contact
- Then I
    - Can edit the following
        - Indicator for "I live on a US military base"
        - Country (required)
        - Street address (required)
        - Street address 2
        - Street address 3
        - City (required)
        - State (required)
        - Zip code (required)

## Tasks
- [ ] Create or update unit tests
- [ ] Create or update e2e tests
- [ ] Update relevant documentations
  - [ ] README
  - [ ] Use Cases

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature

**Comment by brianseek** [comment]
Updated docs to include a few address related questions: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/architecture-docs/edit-demographics/demographics_edit_data_flow.md

Also we discussed breaking this up in a future refactor to be smaller components for the address form and keep the data in context rather than useState
