### ISSUE TITLE
Add Usable Metrics to the Product Success Tool

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#3772]
## User Story or Problem Statement
How might we visualize error rates on the Product Success Tool so that users have actionable data?

## Goal
Add actionable and available metrics to the Product Success Tool.

## Objectives or Key Results this is meant to further
Add error rates chart to the Product Health Tool front end solution so that VFS teams can see the rate at which veterans are not able to complete their forms.

## Acceptance Criteria
- [ ] Add submission error rates to the Tool
- [ ] Add links and help text for missing metrics

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by joanneesteban** [comment]
Keeping in mind insights from https://github.com/department-of-veterans-affairs/va.gov-team/issues/3412

**Comment by deweydell** [comment]
Feeling frustrated on this one because of problems with calculating error rate and hitting a point where I feel like it's not worth it to spend more time on right now. 

I can't successfully query accurate looking data for almost any of the education products using the event labels I've grabbed from the MVP. The main inconsistencies are: 
- the API request doesn't return the past 12 months for failed submission for almost all of the forms
- the numbers are different in google analytics console and in the API request response body and I am not sure why
- the GA event labels may not all be accurate/consistent?
  - for ex. most forms have a total submissions label and a failed submissions label but the Post 9-11 GI Bill Statement of Benefits form has a failed and success label which has to be calculated differently.

**Comment by joanneesteban** [comment]
@nedierecel @jonwehausen Can you provide insight as to why the inconsistencies are occurring? 

@deweydell Let's de-prioritize this and focus on the Data Visualization software [issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/406). Adding a blocked label to this issue.

**Comment by deweydell** [comment]
Ok sounds good, I can demonstrate in standup tomorrow my issues if they aren't clear.

**Comment by deweydell** [comment]
Update on inconsistency issues above:

## API request doesn't return the past 12 months
This issue was solved by including the following in the request `includeEmptyRows: true`

## Different values in GA console and in the API request response body
Resolved: the operator defaulting to REGEX for the requests that were returning way more values than in the GA console. (ie. querying for the event label edu--submission was returning every label that includes that phrase such as edu--submission-failed and edu--submission-failed-client
### Successful syntax for eventLabels
```
{
	"reportRequests": [
		{
			"viewId": educationModernizedViewId,
			"samplingLevel": "LARGE",
			"includeEmptyRows": true,
			"dateRanges": [
				{
					"startDate": "365daysAgo",
					"endDate": "yesterday"
				}
			],
			"metrics": [
				{
					"expression": "ga:totalEvents"
				}
			],
			"dimensions": [
				{
					"name": "ga:yearMonth"
				}
			],
			"dimensionFilterClauses": [
				{
					"filters": [
						{
							"dimensionName": "ga:eventLabel",
							"operator": "EXACT",
							"expressions": [
								"edu--submission"
							]
						}
					]
				}
			]
		}
	]
}
```

## Inaccurate/inconsistent event labels
1. **Some forms have two failed event labels** for ex: `edu--submission-failed` and `edu--submission-failed-client`. I confirmed that it's working properly when I add both event labels to the `expressions` field in the `dimensionFilterClauses` of the request.

### Successful syntax for multiple event labels
```js
{
	"reportRequests": [
		{
			"hideTotals": true,
			"viewId": educationModernizedViewId,
			"samplingLevel": "LARGE",
			"includeEmptyRows": true,
			"dateRanges": [
				{
					"startDate": "365daysAgo",
					"endDate": "yesterday"
				}
			],
			"metrics": [
				{
					"expression": "ga:totalEvents"
				}
			],
			"dimensions": [
				{
					"name": "ga:yearMonth"
				}
			],
			"dimensionFilterClauses": [
				{
					"filters": [
						{
							"dimensionName": "ga:eventLabel",
							"expressions": [
								"edu--submission-failed",
								"edu--submission-failed-client"
							]
						}
					]
				}
			]
		}
	]
}
```

2. **The post911 GI Bill has success and failure event labels (instead of a total events label and a failed events label)**: The solution is to use a different function to calculate error rate for this product.

**Comment by joanneesteban** [comment]
Since we have completed testing a custom front-end solution and are moving towards using Domo, this ticket can be closed.
