### ISSUE TITLE
Collaboration Cycle Kickoff The Debt Resolution Team, Combined VA Debt Portal

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#37730]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [ ] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [ ] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_va_debt_portal/product_outline.md)
- [User flows - Mural](https://app.mural.co/invitation/mural/vsa8243/1645453970389?sender=riley5075&key=b9051645-ff1a-4307-a1df-bd9622b9ca31) | [User flows - GH documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/combined_va_debt_portal/design/user-flows)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [X] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: We are combining [the Medical Copay Tool](https://staging.va.gov/health-care/pay-copay-bill/) and [the VBA Debt Portal](https://staging.va.gov/manage-va-debt/) into the Combined VA Debt Portal

### 4. Are you making changes to the visual design?
- [X] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [X] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [ ] Static pages
- [X] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [ ] New content
- [X] Changes to existing content

### 8. Are you making a change to the user flow?
- [X] Yes
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [X] Yes
- [ ] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [X] Yes
- [ ] No

The VBA Debt Portal and Medical Copay Tool have GA tracking and a KPI dashboard in Domo. I imagine we'll iterate on these as we move towards the combined experience

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes
- [ ] No

### 12. Is there a GitHub label in the va.gov-team repo for this product?

- [ ] No. 
- [X] Yes. Please specify: CombinedVADebt

### 13. Who is the VA business owner for this body of work?

- [X] VHA (Veterans Health Administration)
- [X] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
@rileyorr if this is ready for review, please post on the #vfs-platform-support per the first checkbox above.

**Comment by rileyorr** [comment]
Hi @shiragoodman! Thanks for the reminder to post it in the channel. I believe @denisecoveyduc is going to update our product outline and then we'll send it your team's way 😄

**Comment by rileyorr** [comment]
@chaseakirby I updated the ticket to answer those questions! Let me know if you have any additional questions.

**Comment by chaseakirby** [comment]
Thank you @rileyorr! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints:

- [Design Intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html )
- [Research Plan Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html )
- [Analytics Request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html )
- [Midpoint Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html )
- [Contact Center Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html )
- [Staging Review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html )
- [Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html)

We recommend that you bring the tool/application and static pages through the Collaboration Cycle together so we can review the full flow/user experience.
Please reach out to Dave Conlon to let him know your work will impact static pages, the nature of the work, and your projected timeline.

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product
- Research

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.
