### ISSUE TITLE
Discovery: Add Prop to va-additional-info to disable blue line

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#37751]
## Situation
On https://www.va.gov/health-care/health-needs-conditions/mental-health/ they have a `va-alert` web component that is being generated via the Content Build from https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/blocks/alert.drupal.liquid

Inside that alert they have an expandable option which is created via css classes named `form-expanding-group`. This expandable option is essentially the same thing as `va-additional-info` with one minor difference this being it is fully left aligned without a blue border.

## Question
Should we add a prop to the current `va-additional-info` that would disable the blue border and additional left padding to allow for adoption of the `va-additional-info` into the Alerts generated via the Content Build?

## Screenshots
![Screen Shot 2022-02-25 at 3.45.40 PM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/910019a5-92c3-4e99-a849-1d389fae610d)
![Screen Shot 2022-02-25 at 3.46.40 PM.png](https://images.zenhubusercontent.com/618570fbb420f53ff83732e5/d04a7db7-3d02-4236-809d-9d1d57d02057)

## Conversation that prompted this ticket
https://dsva.slack.com/archives/G01BJ3ESXL4/p1645727855840219

**Comment by caw310** [comment]
This was discussed in the DSC meeting on 3/4. 
Action items: 

- Add the prop and 
- Include task add to the documentation.
- Create a ticket for “Fleshing out Additional info” documentation 
- Work to be prioritized for a future sprint by Katy and Carol

**Comment by k80bowman** [comment]
We can use this ticket for adding the prop and updating the documentation to include information about the prop in Storybook. The design.va.gov documentation can be addressed in #38612

**Comment by CourtneyChambers77** [comment]
Disabled buttons should not be designed in a way that they cannot be read by a screen reader (buttons are not focusable, so the users can't reach them with a keyboard). No need to explain that users with disabilities will face problems with such behavior.
Ensure color contrast is checked minimum requirements if not it will be difficult for users to read or recognize the button.
It’s best not to disable buttons or inputs.
Add some nearby visible help text for the button. This would work for sighted users, but not necessarily for low vision users or blind users using a screen reader.
Add aria-disabled="true” instead of disabled. Programmatically link some contextual help text using aria-describedby="id-of-the-help-text”, use JS to stop click and submit events.
