### ISSUE TITLE
[SW-Content] Update "Verifying Your Identity On Va.gov"  [CW]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#37790]
## Story
As a Veteran the information on the Verify your identity needs to be updates, so I know the correct information and documentation I need to verify my identity to VA.gov.

## Resources
McMillian, Gwendolyn VACO 
** PLEASE BE ADVISED -- This article has draft content that can't go live until login.gov launches** confirm with Danielle for more information.

## Task(s)
- [x] Review and update the Verifying Your Identity page by - removing references and actions related to VA Form 10-5345A-MHV
- [x] Read through the page to make sure the removal does not affect the continuing content.

![image.png](https://images.zenhubusercontent.com/5dae20cd6a7fc5000106eec0/2f9836d6-d467-4733-8f87-9dbfe39e6f88)

## Acceptance Criteria
* References are removed
* Content is confirmed by Copy Editor
* Stakeholder approves content

**Comment by lunascoop** [comment]
@psanders86 these changes are ready for review.

**Comment by RLHecht** [comment]
Thanks @psanders86. I made 2 updates:
- I added back in a link to "Find your nearest VA health facility"
- I changed "health care facility" throughout to "health facility" since that's the verbiage we use on our other pages. We don't use it in any of the other accordions so I only needed to fix it on this one.

@bethpottsVADEPO Do you want to review this before we publish? Neither of these single Q&As are ones that Danielle has changes in draft for so we can publish them at any time. 

http://preview-prod.vfs.va.gov/preview?nodeId=8500
http://preview-prod.vfs.va.gov/preview?nodeId=8501

**Comment by bethpottsVADEPO** [comment]
http://preview-prod.vfs.va.gov/preview?nodeId=8501 looks ready to publish. Thanks! 

@RLHecht Would you please proofread my tweaks to the lead-ins to bullets (making those complete sentences in preparation for translation in the future): 
http://preview-prod.vfs.va.gov/preview?nodeId=8500

@lunascoop Thank you for addressing the sub-bullets!

**Comment by RLHecht** [comment]
Thanks! I reviewed and published both pages. This is good to close once changes are live.
