### ISSUE TITLE
Access for Joshua Faulkner

### ISSUE THREAD

**Issue by JordanSWhite** [department-of-veterans-affairs/va.gov-team#37825]
### COR Name

Mary O’Toole

### Vendor Onboarding Representative Name

Other

### Your Name

Joshua Faulkner

### Your Email

joshua.faulkner@va.gov

### Name of Your Team

1095-B. Joshua is a software engineer at the VA

### Service(s) You Want Access To

AWS

### Desired AWS Access

Joshua is a software engineer at the HEC at the VA. He is our point of contact there for digitizing the 1095B form. He'll need access to our s3 bucket in prod, to pull the data from the HEC enrollment system via biweekly batch job that then gets sent to our prod bucket. 

### Access Expiration

ongoing

**Comment by mleclerc00** [comment]
## For AWS Access

User: William Gardner
COR: Mary O’Toole
VOR: Liberty IT - ?
Approval required: @department-of-veterans-affairs/operations-aws-approvers

@JordanSWhite can you please provide your VOR

**Comment by JordanSWhite** [comment]
@mleclerc00 I didn't think there would be a VOR, since Joshua is a VA employee, not a contractor. I discussed some of this with @jhouse-solvd yesterday. 

Also, I'm not sure who William Gardner is?

**Comment by mleclerc00** [comment]
Sorry, copy/paste error.  Updated comment

**Comment by jhouse-solvd** [comment]
@td-usds - They may be requesting programmatic access, ie they need a credentialed AWS service account (in DSVA's GovCloud account) with access to the S3 bucket in question. Typically, the infrastructure team manages these credentials so that they can be easily changed/rotated. I'm not sure where Joshua and the team intend to store the credentials in this scenario, but... 

Can we ask Joshua if the application connecting to the S3 bucket has a repository in the department-of-veterans-affairs GitHub org? 

If this is the case, you're correct that this would need to be a different request. And, I believe we have a corresponding request template to provide.

**Comment by td-usds** [comment]
@jhouse-solvd, I think that this is that bucket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/38079
Which template should they use?

**Comment by JordanSWhite** [comment]
@jhouse-solvd @td-usds Joshua said that the application connecting to the s3 bucket has a repo in the VA github: /ves-esr

**Comment by jsgarmon** [comment]
Just to keep this moving forward, I believe Joshua just needs access similar to Teagan Stephson (basic read access + read-write to the 1095B dev bucket). I don't believe there are plans to make the prod bucket accessible to humans.

**Comment by td-usds** [comment]
access to that dev bucket approved.

**Comment by jsgarmon** [comment]
Login instructions sent via Slack. @josh2145: please close this issue when you've confirmed access.
