### ISSUE TITLE
IA Feedback from Facilities Team

### ISSUE THREAD

**Issue by nicko-amida** [department-of-veterans-affairs/va.gov-team#37835]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [x] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [ ] Content support
  - [x] IA support
  
**Background**

The Lovell Federal health care system is taking on a unique design pattern: there are two distinct user flows for VA and for DoD members. Updates have been made to the side nav, user flow, and a new top level intermediary page has been created.

**Help we need**

(Let's meet for any explanation/questions - @nicko-amida)

- Any advice on the overall structure of the user flow?
- Feedback on the side nav changes on the top level user flow page.
- Any feedback on the "switching": returning to the beginning of the flow, and switching to the opposite flow's equivalent page in specific circumstances.
  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to or attach user flows:
     - [Lovell Federal user flow mural](https://app.mural.co/t/vsa8243/m/vsa8243/1639752014389/5eeb47259cd9128ac0eef10e483761a6247137e0?sender=u8a90be72499ecb4354e14700)
- Link to prototype or mockups:
     - [Lovell Federal UXPin](https://preview.uxpin.com/93cf67f26d2b936504ffc415de7cf97fcb8d8e1c#/pages/147178609/simulate/sitemap?mode=i)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Q2 2022
- Estimated staging review date: Q2 2022
- Content and IA work needed by: Q2 2022

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [x] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Facilities Team
-	OCTO-DE product owner: @davidconlon 
-	Product manager: @mmiddaugh 
-	Designer: @nicko-amida 
-	FE engineer: @GcioNapoleon 
-	Product/team Slack channel: [Facilities Slack](https://dsva.slack.com/archives/C0FQSS30V)

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Hi @nicko-amida!  Thank you for walking me through where you are at.  This one is a tough nut to crack for sure.    Here are the areas of consideration from an IA perspective that we talked through today.    We can leave this issue open until the designs are finalized and use it for any further collaboration needed until then.  Please reach out if you have any questions!

- The flows appear to assume that users are going to enter at the very top level page and then drill down into either the DoD or VA system
  - Have you mapped against all possible entry points such as facility locator, search, external links (emails, social media, bookmarks, etc.)?  Many of these may have users entering at deeper levels. 
  - Looking at analytics of existing VAMC sites to compare the entry % on the location pages versus the top level health system level, page views, and previous page data may be helpful.
- Navigation components in the mocks are not accurately representing the structure.  
  - Top level/entry page shows DoD and VA systems as children by showing them in the left nav, but once on those pages, reference to the entry page is gone and it appears as though you are now on the top level. 
    - The "entry page" could be included as the top level of the structure, if the content is deemed important and should be made available to visitors on any page in either system.  If so it should be represented within the breadcrumb and left nav.  This may require some left nav work to include "Systems" as another navigation level.
    - The "entry page" could also be considered an independent page that just serves as a routing page, and possibly not important to the experience once the right destination is found.  In this case, you could consider removing the left nav entirely from that page to remove the illusion of a hierarchy, and have 2 CTAs towards the top to direct traffic, and any child pages of that entry page linked to from within the content of the page.  
  - Some implications of inaccurate navigation components:
    - Users cannot easily identify where they are in the site, how pages are related, or how to navigate within the structure.  
    - Using the left nav sends a signal that you are in a hierarchy and shows you all content related to the top level. In the current state, the DoD and VA systems appear as children AND siblings to one another, but once you click over to one of them, the top level page disappears from the all navigation components along with the reference to the sibling. 
- What content is intended to be shared versus duplicated between systems?
  - What ability does CMS have to share content into multiple health system hierarchies? Or does content have to be duplicated across multiple health systems in order to appear in each one
  - Duplicated content - will have impacts on SEO and findability.  The differences are very subtle, so ensuring users who come directly to a page with very similar content are clear they are on either the DoD or VA version will be important. 
- Content hierarchy of the DoD versus VA alerts (shown at the top of the pages in mocks)
  - Since the alert is related to the page they are on,  placement within the page's content be more appropriate and more visible than in a global/site level alert.  Recommend testing this.

**Comment by nicko-amida** [comment]
@mmiddaugh Tagging you for visibility!

**Comment by mnorthuis** [comment]
Feedback/questions from [design intent meeting on 3/21/22](https://github.com/department-of-veterans-affairs/va.gov-team/issues/38196)

- Still thinking about the top level page and how it's represented in the experience (i.e. breadcrumb, left nav)...in the benefit hubs, when you are on a page in health care for example, we have a heading above the left nav for that hub.  It's not clickable, but it serves as labeling the area that you are in.  That element doesn't exist within VAMC sites currently, and I do not have data on whether it is useful or not, but it may be an option to look at.  I've attached an image of the health care example below.  You wouldn't need an icon, and the length of the system name may be troublesome, but wanted to put that out there as something we currently do.  This space could be used for the super-system (top level), or the system to o help define the area you are in.
- For testing purposes, I'd also like to see you add the home link back into the breadcrumb.  That is something we have considered bring back into play for the VAMC sites and need an opportunity to test it.  The label for that link would be "VA.gov home".
- Another thing to consider - in place of the using the alert to toggle between the experiences - you could use something similar to what we use for the language toggle.  It is also something that we also worked with CMS on to switch out left nav links as well, so it may be useful work here.  The [Covid-19 vaccine](https://www.va.gov/health-care/covid-19-vaccine/) page uses this toggle. 

As a follow up to this, I want to work out a couple of structural things with you, and then they should go to the CMS team as soon as possible:
- Supporting content pages (i.e. under services, news/events, and about sections) - discuss which are shared between the experiences/systems and which are unique.  
- The addition of a level above the system and it's related child pages 
- The toggle relationship between the systems

![image](https://user-images.githubusercontent.com/20994159/159502737-9e0d2964-d798-4a9f-8c6e-72214addcdfe.png)

**Comment by mmiddaugh** [comment]
looks like links were broken during some reorganization efforts - [Lovell Initiative brief is available here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/product/lovell/lovell-initiative-brief.md)
