### ISSUE TITLE
Deploy Dev Keycloak using Quarkus

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/va.gov-team#37864]
We need to deploy dev Keycloak using Quarkus as a separate instance with the new K8 helm chart in dev 17

This needs to be meticulously documented (reference implementation in #37855 would involve this)

**Task is done when:***
Keycloak-next-dev.vfs.va.gov is available and running Keycloak version 17 in development, alongside the keycloak-dev.vfs.va.gov (separate)

**Comment by dginther** [comment]
As it turns out, the Helm chart for Keycloak we are using: https://github.com/codecentric/helm-charts/tree/master/charts/keycloak does not yet support the Quarkus distribution for KC17, but rather the legacy Wildfly KC.

This has been installed to the dev cluster: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vsp-amt/keycloak-next

the URL is https://keycloak-next-dev.vfs.va.gov
