### ISSUE TITLE
Create service so Console UI doesn't need to directly access the Github API

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va.gov-team#37907]
## Description

The release tools team is building a first app for the platform console. The app is currently hitting the Github API directly. A requirement of the system is to have a microservice that the console UI can reference/use instead of directly accessing GitHub.

## Definition of Done

 -[] Console UI can access necessary github features through the microservice without directly accessing the GitHub API

Please reach out to @laineymajor @rmessina1010 and @timwright12 for more information.

**Comment by jjulian** [comment]
This will be a very valuable piece of the system - improving the "console plugin developer" experience, providing a service layer to abstract github (and aws in the future). @jchapin

**Comment by jchapin** [comment]
I added a comment on AMT's RFC: https://vfs.atlassian.net/wiki/spaces/AMT/pages/2109964348/RFC+Github-based+Console+UI+plugins+will+provide+authorization+directly+through+Github

We're going to retain the ability to authenticate users via GitHub as an optional secondary form of auth in Console UI. Console UI is set up as a Github OAuth app, and asks for permission to access GitHub on behalf of the user.

@ericvoshall's example plugin shows how to use authenticated GitHub user to trigger a GitHub action.

https://github.com/department-of-veterans-affairs/backstage-test/tree/main/plugins/github-deployment

Eric and Ray have been chatting about this on DSVA Slack.

To address the concerns that such an integration may exhaust API requests allotted to an app or a user, we opened this issue, https://github.com/department-of-veterans-affairs/backstage-test/issues/135, to expose the number of requests used by a user or an app so that we can measure/monitor that activity.

Whether we want to continue this pattern of triggering GitHub Actions in the future is still up for discussion though.

**Comment by timwright12** [comment]
@jchapin I believe this is more related to the data being pulled rather than the authentication. OCTODE had wanted us to not directly hit github as a longterm solution

**Comment by jchapin** [comment]
> @jchapin I believe this is more related to the data being pulled rather than the authentication.

That's why I added this:

> Whether we want to continue this pattern of triggering GitHub Actions in the future is still up for discussion though.

^ Yep. It's a bit like side-loading an app onto an Android phone... you can install an app by going that route. Users will always be able to do that... But the organization may benefit from providing a layer of abstraction... simplifying processes,  catching more information, having automation on other vendors kick in at the same time.

>  OCTODE had wanted us to not directly hit github as a longterm solution

What were OCTODE's goals/concerns in putting a layer of abstraction between the GitHub user and GitHub?

**Comment by timwright12** [comment]
> What were OCTODE's goals/concerns in putting a layer of abstraction between the GitHub user and GitHub?

I think it was just that we would be able to control a microservice better

**Comment by npeterson54** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/35512

My team has been working on this, you can access this in the github ticket above

**Comment by ericvoshall** [comment]
Related to this,  Backstage (our current candidate for the Platform Console UI) relies on a direct integration to Github for at least two relevant use cases:

1. registering a Github repo as an entry in the software catalog
2. being able to use any Backstage-provided or third-party plugins that depend on Backstage's built-in Github authentication
