### ISSUE TITLE
Collaboration Cycle Kickoff [Authenticated Experience, Medical Copays]

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#38006]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

This enhancement to My VA is quite small - simply adding a link/revising the debts link (which has not yet launched, in QA now) - however we would like to have support for design/content..  We will be happy to go through any reviews recommended, which should be pretty quick and easy.
- With medical copays information now being available on VA.gov, and the current work by the Debt resolution team to combine both debts and copays into their debt portal, we would like to pull that information into the My VA dashboard.
     - We will be coordinating with the Debt Resolution team to be included in their usability research, by accessing the link from My VA dashboard, which would direct the user to the debt/copay portal.
     - Depending on the Debt teams launch, we might be able to include this enhancement as part of our MVP for the new Benefit payments and debts section.
- We do not want to create a new section, and we have determined the best place for a link to the information should be within the Benefit payments and debts section.
- We have worked through discovery, and plan to start designs in this sprint as well (2/23-3/8)
- [Project folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/my-va/Copays) (nothing in there just yet)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [x] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: My VA dashboard - we are adding outstanding medical copays information to My VA

### 4. Are you making changes to the visual design?
- [x] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [x] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [x] Tools and applications*
- [ ] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.*

### 7. Will your work include:  

- [ ] New content
- [x] Changes to existing content - Editing a component of the Benefit payments and debts section, which has not yet launched

### 8. Are you making a change to the user flow?
- [ ] Yes
- [x] No

### 9. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [x] Yes - Analytics will be implemented as part of Benefit payments and debts launch, we will be using the same URL as debts
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

### 12. Is there a GitHub label in the va.gov-team repo for this product?

- [ ] No. 
- [x] Yes. Please specify: myva-copays

### 13. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [x] Other. Please specify: VFS/VSA (OCTO portfolio, Samara Strauss)

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Hi @hdjustice. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: 

- [Design intent](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Design-intent.1782153235.html) 
- [Research plan review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Research-plan-review.1781891143.html) 
- [Midpoint review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Midpoint-review.1781039167.html) 
- [Contact center review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html) 
- [Staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) 
- [Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) 

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product
- Research


We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [[Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886)](Platform Collaboration Point Tracker ). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle [Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html)](Touchpoints ) page.

**Comment by hdjustice** [comment]
@Samara-Strauss  - FYI

**Comment by Samara-Strauss** [comment]
@hdjustice I think you should update this request give what we've decided about the approach. If this ends up being some light copy updates and that's it, we won't need the collab cycle reviews.

**Comment by shiragoodman** [comment]
@Samara-Strauss @hdjustice just let us know if your approach changes. I agree that if it's just copy updates, we don't need to be involved.

**Comment by Samara-Strauss** [comment]
@shiragoodman we've pared down this work pretty significantly, so it might end up being a really small update. We're working closely with Riley's team on this as the combine debts and copays into one tool. Once they do that, this is just going to be a matter of us updating our existing links to the debt tool to mention it's for debts & copays.

**Comment by hdjustice** [comment]
Ok, I will close this ticket then and if more than just copy changes are needed, I will schedule the reviews.
