### ISSUE TITLE
Discovery with SME to understand YR content updates and audience needs

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#3807]
Meet w/ Tammy Hurley, Lucas Tickner (YR SME), Anne Hurley to better understand Yellow RIbbon content.  Questions _(revised 12/6/2019)_:

- How do schools receive the notice for the open period, and how do they respond to the notice?
- What is the current process for VA team updating website?
- What are the easiest/most challenging parts of updating the information?
- Is there any research available that we should be looking at?
- Is there anything about the history of these processes you feel is relevant to the future state?
- Do we have any insight into the criteria that matters most to beneficiaries when reviewing this information? e.g. location, degree type, $$ available?
- Do beneficiaries need access to historical data (past school years) for YR funding?
- Is there any info currently provided that beneficiaries do not need? 
- Is there any info not provided that beneficiaries do need?
- Are there any future plans impacting YR content we should know about?
- What does WEAMS stand for?
- In an email, Luke suggested the possibility that these pages may not be required at all and that YR would be part of the GIBCT.  Interested to hear thoughts around that.

**Comment by Lucastickner** [comment]
Liz - I tried to answer a few questions here to let us maximize our time when we meet.

What is the background of Yellow Ribbon content presentation / process?

- Tammy can expand but it has been a long time to get where we are today.  Short version - we needed something quickly to capture data on YR schools.  The team used an access database for this.  That database is updated yearly in order to generate a report that is provided to Tammy to update the website.  The database went away this year.  The YR data has been moved to a SP site.  Also WEAMS has some YR data, mostly just a yes or no though.  

How did it get to be in the state it's in today?

- Years ago it was a rush job to get something up and we needed to make it also available to folks publicly.  The quick fix was to use some brute force and get it on the website.  That process has not changed.  

Has any research been done in this area previously?

- Not that I am aware of.

What is the current process and frequency for schools providing info to VA?

- Every year we have an "open season" for YR agreements (15 March to 15 May more or less).  We put out a notice to schools that schools can 1. request participation, 2. modify participation, or 3. request to withdrawal.  Agreements are open ended so if we don't hear from the school the previous agreement stands until it is modified or withdrawn.

What is the current process and frequency for VA team updating website?

- Currently we update it once a year after the open season closes and we are provided all the updates.

What are the easiest/most challenging parts of updating the information?

- Defer to Tammy

Do we have any insight into the criteria that matters most to beneficiaries when reviewing this information? e.g. location, degree type, $$ available?

- We do not have any data or research on this.  My guess is the most important things are 1. does the school/program offer YR, 2. how much do they offer, 3. what does that mean for my out of pocket costs.

Do beneficiaries need access to historical data (past school years) for YR funding?

- I don't know why they would.  We use it for historical purposes and to provide information about changes with program participation from year to year.

Is there any info currently provided that beneficiaries do not need?

- I don't think so.  Right now we show the school name, location, degree level, division/school, number of students that are eligible to use it, and the max contribution about per student, per year.

Is there any info not provided that beneficiaries do need?

- I don't think so but that would be something we'd have to get from the folks using the information.  

Are there any future plans impacting YR content we should know about?

- the data is no longer being captured in access and is now in SP.  That is new and they are still working that out.  Brian Grubb is doing all the SP work.  

- We also capture YR info in WEAMS associated with the schools.  That data is then displayed on the GIBCT.  If a student is using the GIBCT, they can see that a school has YR and how much the school will provide in YR payments.  That updates the benefit calculator for the veteran to determine what their out of pocket costs may be.

**Comment by andaleliz** [comment]
Draft meeting agenda:

**Introductions**
Goal: Meet each other! Understand persons role in YR

**Information sharing** (high-level conversation guide [here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/3807))

Goal: Gain insight into our YR users, current processes, and upcoming changes
- Insight to beneficiaries needs and behaviors
- Current process to update and publish school information
- Any relevant background information
- New SharePoint database + link with GIBCT

**Discuss high-level solutions**
Goal: Share ideas for what MVP 1.0 might look like

**Wrap Up**
Goal: Tie up loose ends and define next steps

**Comment by andaleliz** [comment]
Notes synthesis from meeting:
[YR SME Notes Synthesis.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3952382/YR.SME.Notes.Synthesis.pdf)
