### ISSUE TITLE
[Bug] Page Title/h1 and page intro overriding VAMC event calendars h1

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38147]
## What happened?
Page title/h1 and the Page introduction from the Outreach Hub events calendar are now overriding the h1 and page intro on all VAMC event calendars.  This should not override VAMC H1 and page titles. 

### Screenshots
![Screen Shot 2022-03-08 at 9 16 31 AM](https://user-images.githubusercontent.com/70410912/157279937-cdb159e4-9456-4bd2-a94f-9059cfe9ac34.png)

## Steps to Reproduce
- URL: https://prod.cms.va.gov/pittsburg-health-care/events
- Pulling from URL: https://staging.va.gov/outreach-and-events/events/ (This occurred when pushed to production environment, need to determine what is causing the VAMC pages to be overwrote with Title and H1)

## Desired behavior
- [x] Title and H1 of Events details pages shouldn't override VAMC H1 and Title pages as shown above.

**Comment by RLHecht** [comment]
@LindaLi123 These pages are in Drupal but I don't know who controls the templates. Usually it's Public Websites who works on the FE for our pages in Drupal, but I don't know if it's different for VAMC. @kevwalsh Is it the CMS team?

**Comment by jilladams** [comment]
Events V2 / Recurring events have relaunched. After that launch, this issue is resolved: 
![Screen Shot 2022-06-08 at 12 33 26 PM](https://user-images.githubusercontent.com/85581471/172702039-b5012016-5533-48a2-8038-cfdedb899e24.png)
![Screen Shot 2022-06-08 at 12 33 50 PM](https://user-images.githubusercontent.com/85581471/172702044-92e0134b-1204-4937-bcc9-6d1ca9af1f10.png)
