### ISSUE TITLE
Date on expired ITF messaging is inaccurate

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3814]
## What happened?
_The messaging displays a future date for an already expired Intent to File._

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_: vetsgov+test207@id.me 

## Steps to Reproduce
- URL:
- Test User _(if applicable)_: vetsgov+test207@id.me 

## Desired behavior
_The date should not be in the future if the Intent to File already expired._

## Acceptance Criteria
- [ ] _The date for an expired ITF is accurate and is in the past_

## Screenshot
![Screen Shot 2019-11-26 at 9.42.46 AM.png](https://images.zenhubusercontent.com/5d52c3244773cd34ebdf4867/89b45eec-3579-4b66-9b22-6ae919f5b517)

**Comment by Mottie** [comment]
The ITF component doesn't appear to check the expiration date. It searches through all ITFs, but only checks if there is an active ITF. If an active ITF is not found, it _uses the last ITF entry_. This entry is then set as the current ITF ([ref](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/disability-benefits/all-claims/reducers/itf.js)) .

Once the current ITF is determined, a new ITF is created. It then sets the current ITF as the previous, and sets the new one to current. 

This doesn't sound like the desired behavior. We need to map out the expected behavior in order to fix this issue.
