### ISSUE TITLE
[FE] HRT static landing page content updates (Staging)

### ISSUE THREAD

**Issue by brianalloyd** [department-of-veterans-affairs/va.gov-team#38202]
## Issue Description
_Content update to the HRT static landing page in support of research efforts_

- Link to Original Build Ticket #35161 

## Frontend tasks
- Apply updates to static landing page comments inserted into this ticket in "Staging" with required interactions 
- Collaborate with Content and researcher to determine items needed ISO research plan/convo guide
- Hold a "Validation" sync with content to ensure all fixes have been applied and page is ready for research sessions kicking off on 3/14/2022. 
- Update/Finalize as needed/determined

## Acceptance Criteria
- [ ] Content and Research comments on this issue to approve staging prototype for review
- [ ] Content/Researcher reviews prototype ISO research plan/Convo guide 
- [ ] Feedback is documented on ticket for follow up and review

**Comment by DanielleThierryUSDSVA** [comment]
Good morning, @brianalloyd @tmac9494. 

In addition to the changes that Cindy captured in the previous ticket, there are some header level issues.

1. This highlighted header is currently an H4. Change to an H3.
![image](https://user-images.githubusercontent.com/62957278/157465856-446a2037-ca04-4a52-8d61-efad0730aa93.png)

2. It looks like these accordions are H2s. Change to H3s.
![image](https://user-images.githubusercontent.com/62957278/157467669-65933d35-df55-471b-86b1-3529470bef4c.png)

Please check the other header levels as well to make sure they're in order.

Once these changes + the changes Cindy requested are appearing in staging, let me know and I'll give the page another look. Then we can meet tomorrow to make sure we're all good. Thank you!

**Comment by brianalloyd** [comment]
@longmd please see above updates for HRT static page implementation.  Let myself or @DanielleThierryUSDSVA  know what questions arise.  Ideally would like to clean this up today and have a review tomorrow in support of upcoming research.

**Comment by longmd** [comment]
UPDATE: The branch @tmac9494 merged yesterday just went into staging within the last 45m. This fixes the majority of Cindy’s issues from Monday, but obviously does not include any of the updates I have applied today based on @DanielleThierryUSDSVA feedback. 

Per our slack discussion on deployments, there is currently nothing in the queue for `content-build` to trigger a staging deployment at this time, so we will just have to monitor when those will happen. 

One additional note for @DanielleThierryUSDSVA , Cindy had noted the alert H2 was being populated in the Table of Contents on the page. Danielle, I believe you commented or emoji'd a slack conversation about that this morning between Randi and the Design team. That same issue they created with an update to that component has created that issue here.. so that one is out of our hands at fixing.

**Comment by DanielleThierryUSDSVA** [comment]
Re: H2 in Toc - got it, @longmd. Thank you! And thanks so much for the detailed updates overall!

**Comment by longmd** [comment]
@brianalloyd / @DanielleThierryUSDSVA - GOOD NEWS: I was able to trigger the `content-build` repo deploy with a PR merge from another ticket. All of the current updates are in place on [Staging](https://staging.va.gov/hrt)! If additional edits are required, just post them here and I will get them in place.

**Comment by DanielleThierryUSDSVA** [comment]
Woohoo! That is fantastic news, @longmd! Will review and let you know if there's anything else. Thanks again!

**Comment by brianalloyd** [comment]
Awesome work @longmd thanks for the work effort on this, greatly appreciated.
