### ISSUE TITLE
Request IA Review: Higher Level Review

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3822]
## User Story:
As the PM on the Benefits and Memorials team, I need request an IA review so that I can ensure all of the IA processes have been followed and executed correctly.

## URL and Credentials
- URL: https://staging.va.gov/disability-benefits/apply/form-0996-higher-level-review/
- Credentials: vets.gov.user+228

<details>
<summary>** NOTE **</summary>

<br />
As only the front-end has been created and the backend has yet to be set up to work on the staging site, please be aware of the following issues:
<br /><br />

* Form URL
  * Only this URL will work: https://staging.va.gov/disability-benefits/apply/form-0996-higher-level-review/
  * If the site shows a page not found message, it’s because the above url + any path will show a page not found message because we don’t have the route set up on the back-end. **Remove the `/introduction` from the URL and it’ll work again**.
* Mock data:
  * The form is prefilled with made-up data. It doesn’t matter which user you log in with, you’ll see the same mock data prefilled on most pages.
  * Some prefills don’t happen because we're not actually pre-filling the form, it's adding initial data.
* Opt out page
  * If you’re logged in, you’ll see the Opt out page first. Check the box and click continue to go to the actual introduction page.
  * If you’re not logged in, you’ll see the introduction page with a log in button.
  * This order will be fixed once design has finished work on moving the opt out button and we remove the checkbox component.
* Save in progress
  * Because the back-end isn’t hooked up yet, you’ll always need to choose to **start the application over**.
  * If you choose to continue the form, it will appear to restart over and over.
</details>

## Acceptance Criteria:
- [x] IA Review has been completed in staging
- [x] IA feedback has been provided to the Benefits and Memorials team

**Comment by YanaRoy** [comment]
@Mottie could you please provide the URL and credentials in the body of this ticket for IA review

**Comment by mnorthuis** [comment]
# IA Review and Feedback: 
If you have any questions or would like to walk through this on a call, please let me know.  This issue documents IA feedback and can be closed at your discretion. 

## Structure, Breadcrumbs & URLs
- Pages shown in site map here: https://app.moqups.com/Rnc4BDEKrA/view/page/a4dc7a719
- The new form will live under the Decision Reviews “branch”.

**PAGE:** “Request a Higher-Level Review” content page
- Existing page
- No change to URL:  https://www.va.gov/decision-reviews/higher-level-review/
- Modify breadcrumb: remove “Request a” from breadcrumb
	- Current: Home > VA decision reviews and appeals > Request a Higher-Level Review 
	- Revised: Home > VA decision reviews and appeals > Higher-Level Reviews 
- Recommend modification to page title:  remove “Request a” from page title so it is not confused with the actual request form which currently shows the same title. 

**PAGE:** “Request a Higher-Level Review” online form
- New online form
- Base URL: https://www.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/
- Breadcrumb: Home > VA decision reviews and appeals > Higher-Level Reviews > Request a Higher-Level Review
- Subsequent pages will add on to the above URL using short and simple labels, i.e. /introduction/, /veteran-details/, etc.

**PAGE:** “After you request a decision review” content page
- Existing page
- No change to URL: https://www.va.gov/decision-reviews/after-you-request-review/
- No change to breadcrumb: Home > VA decision reviews and appeals > After you request a decision review

## Navigation and Entry Points: 
**Top Nav, Header and Footer**
-	No additional options to be added to the top nav, header or footer
-	Consider changing the “File an Appeal” link and label within the top nav (under Disability fly-out) to prioritize the Decision Review process over the legacy appeals process
o	Change the link label to incorporate the “Decision Review” language – i.e. “Appeal or Request a Decision Review” or “Request a Decision Review or Appeal” (discuss with writer to finalize)
o	Change the links to go to the main Decision Review page instead of the legacy appeals page in disability: https://www.va.gov/decision-reviews/
**Add Left Nav**
-	Add a left nav component to the Decision Reviews content area as either part of this work, or as follow up work, to improve navigation within this section of content.  
-	Include a link to this new online form as a child of the Higher-Level Review content page
-	Left nav was defined for this area previously but should be reviewed and revised as needed based on the addition of this option : https://github.com/department-of-veterans-affairs/vets.gov-team/issues/16360
-	
**Disability Hub**
-	Change the existing “File an Appeal” option to include the Decision Review language – i.e. “File an Appeal or Request a Decision Review” (discuss with writer to finalize)
-	Change the link to go to the main Decision Review page instead of the legacy appeals page in disability: https://www.va.gov/decision-reviews/

**Other Entry Points:**
-	From within Disability content
o	Entry point from “File a VA disability appeal” page already exists and should remain as is: https://www.va.gov/disability/file-an-appeal/
-	From main Decision Reviews page
o	The main Decision Reviews landing page contains a link to the HLR content page and a PDF download - replace the pdf link with a link to the online form, or add a link to the online form within the content so both options are available. 

**Crosslinking**
- None at this time  

## Redirects
- Not aware of any redirects needed at this time.  If any redirects are needed, please submit a Redirect Request at least 2 weeks in advance per the [Redirect Request Process](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/request-redirect.md).

**Comment by mnorthuis** [comment]
@jenniferlee-dsva @lwalsh617 FYI regarding HLR IA feedback

**Comment by mnorthuis** [comment]
@Karak888 @peggygannon

**Comment by mnorthuis** [comment]
@YanaRoy Feel free to close this issue if you have what you need or do not have any further questions.

**Comment by luke-gcio** [comment]
Comments have been provided.  HLR changes to URLs ticket attached for future work.

**Comment by mnorthuis** [comment]
Reopening to review work and refresh...

**Comment by mnorthuis** [comment]
@luke-gcio I reviewed the IA work done last December and most of it has been done.  The only work remaining is to add a link to the form in the left nav and add the appropriate content and CTA to the static page.  Both of these items are work that the Public Websites team would do.  If you have not submitted an intake request for that team for the work, I would do that asap and work with them on timing to complete.  

The two items are listed below and the full IA information can be found here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/bam-higher-level-review.md

**Open items to be done with launch of HLR online form:**

- Decision Reviews Left Nav
  - Include a link to this new online form as a child of the Higher-Level Review content page
  - Link text should closely match H1 of form but should not include form number, i.e. "Request a Higher-Level Review"


- Higher-Level Review static page
   - Revise section on how to request an HLR to include information and CTA/button to complete the online form

**Comment by shiragoodman** [comment]
@luke-gcio can this ticket be closed?
