### ISSUE TITLE
[Design] Review what already exists in VA.gov for indicating spanish language support

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#38303]
## Acceptance Criteria
- [x] Log into staging and review other applications

**Comment by kristenmcconnell** [comment]
[All toggle designs that exist on va.gov.](https://dsva.slack.com/archives/C022AC2STBM/p1646935335412889?thread_ts=1646933072.595559&cid=C022AC2STBM) This is blocked until we meet with the forms team on March 23.

**Comment by kristenmcconnell** [comment]
[Design council ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/667) on the language toggle

**Comment by DanielleThierryUSDSVA** [comment]
Adam added a new doc around this: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/Static-Page-I18Select-User-Guide.md

**Comment by ytsaoca** [comment]
[About UI toggle (Notes form communication with Danielle)](https://dsva.slack.com/archives/C036JKN5S3Y/p1648140088053179)

Because of current technical blockers, the current UI toggle isn't necessarily like the end solution. If we start to integrate that into check-in, we may come up with better ways to do that.
She recommends we to iterate on it and learn from testing.
They tried different designs before and will share the testing report.
It had a little icon and that got removed after testing. They've been monitoring and could continue to test different iterations of it.

**Comment by ytsaoca** [comment]
[The old research from 2019 ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/spanish-translation/VA.gov-Spanish-benefits-link-user-research-061019.pdf)
