### ISSUE TITLE
[SW-Content] Review and update VET TEC funding pages [SWC]

### ISSUE THREAD

**Issue by SgardnerPMP** [department-of-veterans-affairs/va.gov-team#38604]
## Story 
As a Veteran I need to have current information on my VET TEC funding pages, so I can make the correct decisions and know documentation that is required.

## Resources 
Terry Warren
[Veterans technology education courses](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.va.gov%2Feducation%2Fabout-gi-bill-benefits%2Fhow-to-use-benefits%2Fvettec-high-tech-program%2F&data=04%7C01%7Cstan.gardner%40govcio.com%7Cf8926f4bbb184507b1da08da06b3b2f8%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637829666124123089%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Fd7g4HrF81L1m86w%2BS5iIBBO7gUX2i2AboT8iNGF%2Bfk%3D&reserved=0)
[Vettec_Providers](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbenefits.va.gov%2Fgibill%2Ffgib%2Fvettec_providers.asp&data=04%7C01%7Cstan.gardner%40govcio.com%7Cf8926f4bbb184507b1da08da06b3b2f8%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637829666124123089%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gzQktNp1KbUp%2BfF6QlxVzJMtVYTEVk0x7crJ%2FvlZJsY%3D&reserved=0)
[GI Bill Carousel](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbenefits.va.gov%2Fgibill%2F&data=04%7C01%7Cstan.gardner%40govcio.com%7Cf8926f4bbb184507b1da08da06b3b2f8%7C6499e3f51d3e4f099ad352b9e2f67fb8%7C1%7C0%7C637829666124123089%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TGXlLWodCw7%2BGTFPDcgxvIgesU5n5haMcrACkrH8npQ%3D&reserved=0)

## Task(s)
**we would like the following update to VET TEC funding be made to the following links –**

The VET TEC program is subject by law to an annual $45 million budget and is rapidly approaching this cap for Fiscal Year 2022. Students must be in receipt of a VET TEC award letter to participate in the program.  Please check back for future funding updates.
- [ ] Update VET TEC pages with above information

## Acceptance Criteria
* Pages are updated with information above and available for stakeholder to review.

**Comment by RLHecht** [comment]
@psanders86 Here's my proposed copy for the alert:

H2: We will soon suspend VET TEC funding for the current fiscal year

Because of the popularity of the VET TEC program, we are close to using our full budget for the current fiscal year. This means we'll soon not be able to accept new enrollments until after October 1, 2022.

If you're currently enrolled, you can continue your training uninterrupted. 

Please check back here for program updates. 

For background, this is the alert we've published in the past once we've run out of funding. The SMEs wanted to post an alert this year before the funding runs out, which they said is most likely in April. 

 ![Screen Shot 2022-03-15 at 6.01.17 PM.png](https://images.zenhubusercontent.com/5c9b7e302ac54336e2c327b8/be3b590a-741d-4a3b-9d2b-ea775aef9227)

**Comment by psanders86** [comment]
Hi @RLHecht,

Just a couple of tweaks, to the H2 and the first sentence to add contractions. Thanks!


H2: We'll soon suspend VET TEC funding for the current fiscal year

Because of the popularity of the VET TEC program, we're close to using our full budget for the current fiscal year. This means we'll soon not be able to accept new enrollments until after October 1, 2022.

If you're currently enrolled, you can continue your training uninterrupted.

Please check back here for program updates.

**Comment by RLHecht** [comment]
@bethpottsVADEPO This alert is ready for you to review.

**Comment by RLHecht** [comment]
Update: The VET TEC program was awarded more money so we no longer need to post the alert. I've removed it and put back in the Isakson and Roe alert and published the page. Moving this to validate.
