### ISSUE TITLE
Vets API on K8s DataDog integration (APM)

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#38613]
## The Problem

The current vets-api K8s setup isn't sending traces to the DataDog agent. 

## Hypothesis

Configuring the APM setting will most likely enable the necessary APM tracing. The following will need to be added the DataDog values.yml because it defaults to false in the helm chart. https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml#L280-L283
```
apm:
  portEnabled: true
```

Additionally see the K8s [trace collection documentation](https://docs.datadoghq.com/agent/kubernetes/apm/?tab=uds)

## Definition of Done

- [x] Vets-api is sending traces to datadog agent

**Comment by thilton-oddball** [comment]
I spoke with Matt Leclerc on Friday about Datadog integration with vets-api as well as platform-console-api. He suggested, since he is going to be busy on another project for the short-term,  we reach out to [jhouse-solvd](https://github.com/jhouse-solvd) for assistance.

In this [PR] (https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/434) he mentioned that "the better route here to connect APM with the datadog agents themselves is going to be using a unix socket which will take some more configuration".

**Comment by thilton-oddball** [comment]
Blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/38723
