### ISSUE TITLE
Exclude internal form URLs from "Previous Page" table on Forms Dashboard

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#38645]
## Issue Description
The "previous page" table on the Forms dashboard includes internal form URLs that we do not want to count there.  Need to exclude those from BQ so they do not show up on the dashboard.
---
## Tasks
- [x] Review BQ data and determine best way to exclude and provide direction accordingly.

## Acceptance Criteria
- [x] The URLs will no longer be included on the "Previous page" table of the forms dashboard.
---

**Comment by michelle-dooley** [comment]
@chloedotbrown - I knew I remembered creating something for this.  Did this work not complete this?  https://github.com/department-of-veterans-affairs/va.gov-team/issues/36515

**Comment by chloedotbrown** [comment]
@michelle-dooley - I thought I remembered a card for this too! I'm not sure what changes were made on the BQ end, but unfortunately, it doesn't seem to have solved the issue

<img width="1003" alt="Forms_example step links" src="https://user-images.githubusercontent.com/45518242/159029924-453bfe77-357f-4575-b6fa-bec3d8ae3a3e.png">

**Comment by michelle-dooley** [comment]
@obrienjulie it looks like you did some previous work on this issue in a different ticket  https://github.com/department-of-veterans-affairs/va.gov-team/issues/36515 but doesn't appear to have resolved the issue.  Anything you can share?

**Comment by chloedotbrown** [comment]
Hi @jennaouellet - I think this is ready for your QA! I created an [ETL](https://va-gov.domo.com/datacenter/dataflows/185/details#datasets) that removes any of the form-related URLs from the Funnels and Landing page datasets. This way, the card of pages viewed before accessing the form will come from other parts of the VA website and won't be swamped with internal forms steps in the top spots.

Unfortunately, this doesn't give us a way to pull out form steps that teams haven't added to their funnel - this is especially obvious in the Higher Level Review (20-0996) and Disability Claims (21-526EZ). However, I don't really think there's anything we can do on our end to remove these at this point, though it does make the issue more obvious. Who knows, maybe it can be an incentive for teams to update their funnels with us. 

I've created a [test card ](https://va-gov.domo.com/kpis/details/110787736)to QA the data. I've also changed the metric to unique user, since we've been moving more in that direction with other updates as well. Once this looks good to go, I'll hook the data up to the card on the dashboard, update the data dictionary, and delete the testing card. If you have any questions, let me know!

**Comment by jennaouellet** [comment]
### Previous Page test card QA

Form| Assets | Pass / Fail
-- | -- | --
10-10CG| GA Custom Report | :green_circle: PASS
10-10EZ| GA Custom Report  | :green_circle: PASS
20-0996 | GA Custom Report  | :green_circle: PASS
21-526EZ| GA Custom Report  | :green_circle: PASS
22-1995| GA Custom Report | :green_circle: PASS
28-1900| GA Custom Report | :green_circle: PASS

The same [custom report](https://analytics.google.com/analytics/web/template?uid=czISoF_TT5qxBABlQ35NYw) was modified for each URL.

@chloedotbrown QA is done and it looks good!

**Comment by chloedotbrown** [comment]
Great! Going to go ahead and close this out.
