### ISSUE TITLE
Design Feedback - Design Intent - VA Notify Forms Strike Team - In Progress Reminders

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#38707]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Great work and thank you for the user flows!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Use 1 green action link per page. I am waiting to get clear guidelines on this but we do have some documentation that says [multiple action links should be primary blue](https://design.va.gov/experimental-design/action_links#when-to-use-action-links). Or consider using an active link style or default style.

**Should:**
- Follow the style of cards as seen in [Sketch on the Forms Status card](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/Gmwl2nb), specifically looking at the font family

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle touchpoint meeting epic
- Add to the Feedback pipeline on the Platform Governance team board
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by ElissaFolk** [comment]
1. In order to address the "Must" Feedback, we opted to eliminate all action links and styles and make the application name the link and utilize the default style for links. 
2. We followed as closely to the "Should" Feedback as possible keeping in mind the context of font usage in email.

![or Remove Dependents) Copy](https://user-images.githubusercontent.com/87875579/159991113-fe5c5d43-f3dc-40cf-84b9-8d35e3894fd6.png)

![or Remove Dependents)](https://user-images.githubusercontent.com/87875579/159991118-434ed637-3bbe-43cf-86ba-fabab7919839.png)

**Comment by allison0034** [comment]
Hi @ElissaFolk! 

1. Looks great, you could use the blue action link or [active link styles](https://design.va.gov/experimental-design/action_links#active-links) if you want or leave as you have above.
2. You can change the [card title](https://www.sketch.com/s/610156b6-f281-4497-81f3-64454fc72156/a/Gmwl2nb) to Bitter font family if you want and its possible, probably an H2 or H3 but since this is email I know there are constraints. We don't have specific guidelines around this so what you have above works too.

Thank you!
