### ISSUE TITLE
Spike Improve CT Search results performance

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#38825]
## Issue Description
Currently, Search  results have a 3-5 second lag. EDU would like us to improve search results response to soemthing like <1 sec.

We want to just look at to see where the performance lags are here. No work necessary, just an investigation and possible ideas for fixes.
---
## Tasks
Conduct analysis
Work with Dev Leads Manish and Anthony
Reduce the amount that currently takes CT results to be displayed 

## Acceptance Criteria
~ <1sec should be acceptable

**Comment by AdamFreemer** [comment]
Observations:

1) Total response running on local is approximately 1500ms total on average, with 1300-1400ms of that typically coming from GIDS.
2) Running SQL explain from the index controller action in the GIDS Institution controller which is where the response for search by name occurs, yields multiple problems, such as: Nested loops, Parallel Sequential scans and ordering, done in the results scopes.
3) There are multiple selects on version, from the versioning scheme used which is costing quite a bit

Recommendations so far:

1) The results scopes look to be causing most of the problems, with the large order cost on the search_v1 and search_order_v1 scopes (sort cost ~ 15k). The filer_result_v1 scope is part of a design pattern of using string Institution type filter flags to designate institution type. Replacing this whole mechanism with a boolean flagged column per filter might help here. 

2) The approved_institutions scope with the `(approved AND (((campus_type)::text <> 'E'::text) OR (campus_type IS NULL))` query has high cost (~15k) and is called multiple times. Refactoring this would probably be helpful.

3) There are roughly a couple dozen indexes seemingly not all needed which could be a performance ding at a high level, and with over 150 columns, either breaking the table up or doing a select after determining what fields are actually needed in the results query might also help significantly.

**Comment by AdamFreemer** [comment]
To follow up on my first comment, this task ties into the the redesign task of the CT landing page: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/31151

Because both tabs have shared portions of their backend operation, optimizing performance (where most of the lag is in GIDS code) should be combined with the redesign task.

The redesign will have a few major components I believe:

1. At the highest level, UI changes, which would would assume to keep the Filtering checkboxes and combine Search by Name and Search by Location tabs into a combines omnibox requiring a wireframe from the business to initially move forward with.

2. The core discussion point for the redesign and performance optimization tasks should be centered around the current Filtering Checkboxes. 

![Screen Shot 2022-03-28 at 11.09.45 AM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/9f442183-b82f-4216-ade4-ef586cab6ee2)

Currently the tags are grouped by an OR condition on the 6 possible classification School Types: Public, For profit, Private, Foreign, Flight, Correspondence. I.e., each Institution is currently classified as only one type, meaning an Institution can't be Public AND Flight, or Public and For Profit for example. 

High School filtering is done separately based on specific components of the Institution's facility_code, with no direct linkage, which can cause some unusual anomalies.

A possible solution to the separated filtering, would be to add per Filter Checkbox item "flags" (boolean columns) on the database. This would allow discrete selection and filtering of Filter choices, as well as being more performant as text string queries on the database vs. boolean queries are generally faster. This would require a major redesign of the query logic in GIDS, as well as updating the Institution Builder script to accommodate the new database structure.

3. Beyond the Filter code, Search by Name and Search by Location would have to be combined and most likely rewritten, which could also address performance  at the same time during this refactor. 

4. Exploring options like ElasticSearch, Sunspot, etc might be worth looking into, notably the infrastructure requirements attached to each solution. https://devcamp.com/site_blogs/implementing-a-search-engine-in-a-rails-application

5. Clarification on ownership of GIDS code in general might help guide some of the above.

**Comment by mrblanco1** [comment]
This spike is completed. Dev believe performance will greatly improve when #31151: Remove Search tabs and make it one - is completed. Testing will need to be performed then to assess either performance did improve or not.
In the case it does not then a new ticket will be created for Dev to work on.
