### ISSUE TITLE
Port remaining operations epics to va.gov-team

### ISSUE THREAD

**Issue by gunsch** [department-of-veterans-affairs/va.gov-team#389]

**Comment by ricetj** [comment]
From Vets.gov (taged DevOps) to VA.gov Repo,

**Comment by ricetj** [comment]
@wyattwalter something we can talk about next week, but I'm assuming not all the epics come over to the ops team, ie epics labeled with ATO and DevOps, or is it better to just bring everything over to ops?

**Comment by ricetj** [comment]
Update:

**Moved over to public Repo:** 
- vets.gov migration to VA Enterprise Cloud #10434. …..  Now is #444 (not closed on Vets.gov, because work is still being done there.)
- measure and reduce on-call burden #16150 …..  Now is #447
- vets.gov VIP process compliance #10260 …..  Now is #449 (may not be safe in public repo, only title is on ticket. Will need reviewed)
- make deployments safer #9421 ….. Now is #453
- Exercise Backup, Recovery, and Rollback Process #5954 …..  Now is #468
- Create Backup and Recovery Plan #1542… Now is #475 (with Product Support team, may also have some ops work, so tagged for such)
-Ongoing ATO Maintenance #6154 …..  Now is #476 (with Product Support team)

**Need to review before moving over:**
- Complete Downtime Notification Work #10712
- Supporting Decoupled CMS Approach #15365
- New Home for DSVA Handbook #13817
- Improve backend error handling sitewide #5229 (may be completed)
- Update Standard Operating Procedures #1546
- Develop a general asynchronous processing model for vets-api requests #9400 (checking with Tools and Improvement to see if they already ported this work.)

**Comment by ricetj** [comment]
@gunsch All epics have been ported.

**Comment by ricetj** [comment]
complete
