### ISSUE TITLE
Accessibility - Design Intent - [Authenticated Profile - Bad Address Indicator]

### ISSUE THREAD

**Issue by Saraharaba8** [department-of-veterans-affairs/va.gov-team#38905]
## Feedback

- **Consider**

### Erroneous State

 I would Link the error state with the field using aria-describedby. So that way, The screen reader provides a way to read the description while being inside the erroneous field.

![8B49DA19-A9A8-44C2-AF61-5FE6D9B4D91E_4_5005_c.jpeg](https://images.zenhubusercontent.com/61a30b7171cd32352c4465c0/f844f5ff-e635-4a6e-8898-66ca8ea9b576)

### Implementing aria-live="polite."

 In this case, assistive technologies would announce updates at the next graceful opportunity, such as at the end of a sentence. The polite value can be used for warning notifications when the user needs to know something. An example where this value could be used is dynamically injected messages, such as the success alert shown below.. 

![B78FEBEE-431E-4B54-B177-C7BD9315AF58.jpeg](https://images.zenhubusercontent.com/61a30b7171cd32352c4465c0/bdeb8f3b-77ee-4c03-b8da-47bea8fae9fb)

###  Developer Feedback -  Form System (HTML Markup) 

I would Use aria-required to notify of required fields. Just so that way , The screen reader is saying "required" when tabbing into those fields. 

Secondly, I would Use aria-invalid to notify of fields that are currently invalid. So that our screen readers our saying  "invalid" when tabbing into the field.

### Another Consideration (Success Alert State)

![B78FEBEE-431E-4B54-B177-C7BD9315AF58.jpeg](https://images.zenhubusercontent.com/61a30b7171cd32352c4465c0/f36490b0-a9a8-45c0-b114-00146a6b8a07)

An approach could be to send focus to the edit home address button with an aria-live polite announcing the update was saved. This may be more semantically natural as focus will remain on an interactive element and provide an immediate "undo" kind of action."
cc @joshkimux

**Comment by MarciMcGuireGCIO** [comment]
@adamwhitlock1 -- leaving this here from the Design Intent for when you get ready to start building the FE.

**Comment by SKasimow** [comment]
@adamwhitlock1 - this was the other "Bad Address" ticket I found and wanted to know if I should include with other Bad Address work for this sprint (sprint 73)?

**Comment by mdewey** [comment]
Absolutely!

**Comment by Samara-Strauss** [comment]
It's unclear to me whether there is work for us to do at some point, or whether this ticket belongs with the design system team. What do you think, @mdewey?

**Comment by mdewey** [comment]
Update for `Erroneous State`

- The message in the ticket was for the mailing address, but because that is a generic `system is down ` message, we cannot link it back to a specific field.  I did manage to do the recommendation for the phone numbers fields, PR#21494. This causes the screen reader to read out the error when the user is focused on the field and the error message is displayed. I could add this to the emails and other simple fields and forms, depending on the error messages. 
- In doing this, I found out that the error messages for the phone numbers are not lining up with the server response. For example, we are getting validation errors from the server, but display a server down message. This should probably be updated
- I also found that the screen reader for the phone number is not that accessible. It reads out the phone number as a number, 123-123-1,234, would be read out as `one billion, two hundred and thirty-one million, two hundred and thirty-one thousand two hundred and thirty-four`. That should probably be fixed in a ticket as well.  


**Summary**: Two tickets should be created, and minor improvements happened. This ticket can be closed
