### ISSUE TITLE
Update va-text-input component to use native events

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#38907]
## Description
We would like to update the va-text-input component to use the input and blur native events. This would mean the component would be easier to test in Cypress and may mean that teams using this component in React would be able to use it without the React bindings.

## Acceptance Criteria
- [ ] Update va-text-input to use native input and blur events
- [ ] Update tests as necessary

**Comment by bkjohnson** [comment]
`va-text-input` fires 3 custom events at the moment:

- `vaBlur`
- `vaChange`
- `component-library-analytics`
    - This needs to stay

The `onVaBlur` handler is only used once in `vets-website`:

![image](https://user-images.githubusercontent.com/2008881/162849415-d8fd704b-2561-4362-a920-d1730dd54908.png)

So if that handler switches to `onBlur` we could safely remove [the custom event](https://github.com/department-of-veterans-affairs/component-library/blob/ffe9df32efc94776cb7141120afa5725c14a61fb/packages/web-components/src/components/va-text-input/va-text-input.tsx#L135).

The `change` event is special in React, and [React won't attach `onChange` handlers to custom elements just yet](https://github.com/facebook/react/blob/05a55a4b09b7b7c8f63778fb8252a001ca66f8d7/packages/react-dom/src/__tests__/DOMPropertyOperations-test.js#L294-L318). However, `vaChange` is actually being [fired from a handler for the `input` event](https://github.com/department-of-veterans-affairs/component-library/blob/ffe9df32efc94776cb7141120afa5725c14a61fb/packages/web-components/src/components/va-text-input/va-text-input.tsx#L170). Because of this, I think `onVaChange` could be updated to `onInput` on `<VaTextInput>` instances without any other changes. This change would need to be made in several `vets-website` files:

```
✔︎ vets-website (master) ✗ rg --multiline --multiline-dotall "<VaTextInput[^<]*onVaChange" -l
src/applications/check-in/components/pages/validate/ValidateDisplay.jsx
src/applications/check-in/components/pages/Edit/Email.jsx
src/applications/check-in/components/pages/Edit/Name.jsx
src/applications/check-in/components/pages/Edit/Address.jsx
src/applications/check-in/components/pages/Edit/PhoneNumber.jsx
```

Then we could also remove the `this.vaChange.emit()` from the component's definition.
