### ISSUE TITLE
FE - Auth Profile - Personal Info Revision - Add ability to Add/Update Preferred Name

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#38953]
## Background

Add ability to Add/Update Preferred Name

## Tasks
- [x] Add ability to Add/Update Preferred Name

## Acceptance Criteria
- [x] Add ability to Add/Update Preferred Name

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by adamwhitlock1** [comment]
@SKasimow and @Samara-Strauss this is ready to validate in staging. Users are able to add and edit their preferred name.

**Comment by Samara-Strauss** [comment]
I did find a weird bug:

- Use user 36, who already has a preferred name saved.
- Click Edit for preferred name.
- Empty out the form.
- Click cancel. You get an error saying the form can't be blank.

Given that there is already a name saved, I would expect to be able cancel a blank form without receiving an error.

**Comment by SKasimow** [comment]
@adamwhitlock1 - aside from what Samara's found above, I tested the 2 scenarios below and didn't find any issues:

-  adding a preferred name to an account without one
- changing a preferred name to an account that already has a preferred name

**Comment by adamwhitlock1** [comment]
@Samara-Strauss per your findings on the weird bug. 

We discussed this a bit last week during one of the standups and this issue seems somewhat dependent on the form systems method of validating inputs. Maybe there is a way to fudge this to not make it occur, but basically when an input loses focus is when the validation happens.

I discovered some interesting things about this validation. For user 36 for instance

- Empty out the form.
- Click anywhere else on the page
- Click cancel. You see the cancel modal as expected.
or

- Click edit preferred name
- Click anywhere on the page first
- Click on name field and clear out value
- Click cancel. You see the cancel modal as expected.

Also interestingly the same issue occurs within other areas of the profile like the address sections. If you edit the mailing address click right into the street input and clear it then immediately click cancel it will also show the validation first without displaying the cancel alert modal.

🤔

**Comment by Samara-Strauss** [comment]
@adamwhitlock1 got it! So it sounds like this isn't a bug with your work -- it's a weird interaction that's part of the forms system. So, there's nothing for you to do to change it. Understood, and if there is no other work, this is probably good to close.
