### ISSUE TITLE
Unable to log in with Login.gov and Safari

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#39018]
Safari users are unable to login via login.gov to the platform console.

See: https://github.com/department-of-veterans-affairs/backstage-test/issues/115

**Comment by kylesoskin** [comment]
After some investigation, I have found that it has something to do with Safari not letting you set cookies in a popup window.
If you login to login.gov first in safari (not as a redirect/pop-up from the platform console) and then go to the platform-console and click login, it'll open the popup and immediately redirect to the logged in platform console, because it already has your logged in cookies.

**Comment by kjduensing** [comment]
Closing this ticket since there isn't anything AMT can do to fix the way cookies + popups work in Safari.
