### ISSUE TITLE
Date web component: accessibility review

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#39047]
## Description
We need to conduct a full accessibility review of the new Date web component. The component can be viewed in Storybook here: https://60f9b557105290003b387cd5-kdzjshpbzk.chromatic.com/?path=/docs/components-va-date--default

## Acceptance Criteria
- [ ] Full accessibility review of the Date component is completed
- [ ] Add descriptions of any issues found to this ticket
    - [ ] If any problems are found, add screen recordings and/or screenshots to comments on this ticket that show the problem.
- [ ] Alert Katy and the developer who built the component when the review is complete
- [ ] Re-review any fixes the developer makes to the component

**Comment by pdavies88** [comment]
@CourtneyChambers77 Chromatic Link for Testing: https://60f9b557105290003b387cd5-qhcjdudpcs.chromatic.com/?path=/docs/components-va-date--default

**Comment by CourtneyChambers77** [comment]
Thank you

**Comment by CourtneyChambers77** [comment]
Adding in the Aria-label, aria-labelledby and aria-describedby can be used in interactive HTML elements.
These should not be used for non interactive elements such as <div>, <span> and so on.
It is used when you have a text that has information about the element. Aria-describedby must be the same as the id of the text that describes it.
Aria-invalid and aria-describedby are used together to indicate an error when the personal identification number (PIN), email address, or start date are not in the expected format.
Aria-describedby This is very similar to aria-labelledby described above.This attribute allows the description to be set for an element based on ids.
A label describes the essence of an element where as the description provides greater information to help the user.
Aria-described by tends to be longer although this is only a heuristic, not a rule.
Aria-label or one of aria-labelledby and aria-describedby allow the screen reader to better narrate the inputs of a form to the user and should be used in form input elements. Hence these must be leveraged while developing web forms.
How it works:
To interact with a form the Tab key is used to move between form controls (inputs, textarea, select, etc.).
As paragraphs are not inherently keyboard focusable, a person using a screen reader to navigate the form may completely miss the snarky password description.
To help ensure the instructions are not missed, the paragraph is given a unique id for the aria-describedby attribute to reference.
This will result in the announcement of the snarky content, after the accessible name and role of the password input, when focused.

**Comment by pdavies88** [comment]
@CourtneyChambers77 @SarahKay8 looking for some guidance and the best way to code this component for accessibility.
Right now we have a version of this component in Production which can be viewed here: https://60f9b557105290003b387cd5-qhcjdudpcs.chromatic.com/iframe.html?id=components-date--default&viewMode=story
It interacts the same way as the new component here: https://60f9b557105290003b387cd5-qhcjdudpcs.chromatic.com/iframe.html?id=components-va-date--default&viewMode=story

From my testing with JAWS and can also be seen in the video on this ticket, both of these components when JAWS read the page it reads all the Text and Labels before stopping on the last Label which is "Year". Upon finishing its reading if a user presses the Tab key the focus goes into the Year `input` element because the final focus of JAWS was the "Year" label above it. 

So I am wondering if this behavior is correct, and if not what is the correct way for JAWS to read the page? Is it to read the first Label ie: Month and then stop or focus on the `select` element below? Should a tab-index be given to the `select` element under Month to force the browser to have that as the first element that gains focus? If there is a different type of behavior are their specific `aria` attributes that I should be leveraging to have the screen reader read things in a specific order and what should that order be?

@k80bowman

**Comment by pdavies88** [comment]
@CourtneyChambers77 the most recent link is this: https://60f9b557105290003b387cd5-kdzjshpbzk.chromatic.com/?path=/docs/components-va-date--default

**Comment by CourtneyChambers77** [comment]
I will suggest the region main change to section because this will part of the page, unless the component is the main component on the page, and an aria-label="Select Month and two-digit day XX and four-digit year format XXXX" to be set on a parent element within the component.

**Comment by pdavies88** [comment]
@CourtneyChambers77 I think you meant to write we should set the aria role to region not section. Section per Mozilla is not to be used: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles#6._abstract_roles

However region is a catch all role and best fits our scenario: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Region_role

I think what you were trying to communicate is that using the <section> element automatically tells a browser that the role of region should be given. However since we are not going to use the <section> element within our component we should use role="region" instead.
@k80bowman for awareness

**Comment by pdavies88** [comment]
@CourtneyChambers77 here is the updated link: https://60f9b557105290003b387cd5-xinykysqau.chromatic.com/iframe.html?id=components-va-date--default&viewMode=story
Attached is a video I took using VoiceOver to test:
https://images.zenhubusercontent.com/133843125/6c8d6a15-680d-46ba-8407-ef1cc67ea9da/screen_recording_2022_04_20_at_3_50_07_pm.mov

**Comment by SarahKay8** [comment]
The first link works as expected for me, for both JAWS and NVDA. The only thing I would change is the yellow focus indicator to something darker (should be at least 3:1 in contrast), but that's not a screen reader issue.
Behavior is correct..

**Comment by pdavies88** [comment]
@SarahKay8 I would agree and I believe this ticket in our backlog should fix this: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/654
I know we chatted about that a few weeks ago in Design System Council since the current color is a bit too light

**Comment by pdavies88** [comment]
@SarahKay8 thank you so much I am going to make these updates this afternoon and will message back as soon I have a new Chromatic link with the corrected updates.

**Comment by CourtneyChambers77** [comment]
@SarahKay8 a quick question concerning the required label? If the label is hidden or not visible but screen readers can hear the label out, my question are we constructing the component for screen reader devices only or all accessibility devices and commendations, the reason is, this is great for SR only but however when putting all the other accessibility disabilities in play, I would consider add the label required to be visible for memory loss or cogitative disabilities, let me know so I know how to address the components moving forward. Thanks

**Comment by pdavies88** [comment]
@SarahKay8 updates have been made to component and can be tested here: https://60f9b557105290003b387cd5-uupmsemdfs.chromatic.com/iframe.html?id=components-va-date--default&viewMode=story
General view is here: https://60f9b557105290003b387cd5-uupmsemdfs.chromatic.com/?path=/docs/components-va-date--default

**Comment by CourtneyChambers77** [comment]
Please add Require label back - ![image.png](https://images.zenhubusercontent.com/61b2260296ae8721195bcef1/9a9e3c0e-08b3-4d12-aef8-96ad1fbdd60a)

**Comment by pdavies88** [comment]
@CourtneyChambers77 @SarahKay8 I reverted the changes made to the `required` label based on the screen grab above.
To summarize then the changes that have been made for accessibility are the following:
- Utilize `fieldset` element
- Utilize `legend` element
- Add `aria-label` of "Select Month and two-digit day XX and four-digit year format XXXX"

Most recent link to Chromatic with these updates: https://60f9b557105290003b387cd5-heswquhwxa.chromatic.com/iframe.html?id=components-va-date--default&viewMode=story

**Comment by SarahKay8** [comment]
Thanks @pdavies88! No further feedback on my end. URL has been retested and it looks good. Happy Courtney and I could help!

**Comment by SarahKay8** [comment]
@shiragoodman
