### ISSUE TITLE
Date web component: development

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#39046]
## Description
Build a web-component version of our [Date React component](https://design.va.gov/storybook/?path=/docs/components-date--default).

## Details
Styles are in this file: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/modules/_m-form-elements.scss#L53

Where possible, use native HTML events.

## Acceptance Criteria
- [ ] `va-date` is written and added to Storybook
- [ ] E2E tests are written
- [ ] Add Chromatic link to #39047, assign ticket to Courtney, and move ticket to Current Sprint column
- [ ] Once accessibility review is complete, alert Carol that component is ready for staging review
- [ ] Address any staging review comments
- [ ] Merge component

**Comment by pdavies88** [comment]
Per Slack Conversation: https://dsva.slack.com/archives/G01BJ3ESXL4/p1649096885111219
We are going to move this ticket to the backlog in favor of completing a Web Component for `NumberInput` first. This is due to an issue with Rollup and Stencil when trying to import a React Component inside a Web Component. At its core this Web Component is a combination of two `va-select` and one `NumberInput` components and the structure of the internal components will help determine the best way to complete this combination component.

**Comment by caw310** [comment]
Staging review 4/28.
