### ISSUE TITLE
A11y component testing best practices 

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39067]
Document the steps done for the accessibility component testing in the following confluence page.  https://vfs.atlassian.net/l/c/7RMytu8G

- [ ] Describe how you test a component - write out the steps
- [ ] List the Assistive technology devices / Software used 
- [ ] List the tests that are done

**Comment by CourtneyChambers77** [comment]
Color Contrast 
Enough color contrasts
Meaning color hue an example, red versus green.
Referring to differences in color lightness or luminance an example, dark versus light.
To determine if the text has sufficient contrast is to view your image using a Firefox or Chrome browser that has the Firefox extensions -on which will display the color of any pixel beneath the user's cursor. That color can then be entered into a contrast checker to see if the contrast ratio is 4.5:1 or more.
Most color contrast issues can be evaluated when using automated testing, manual testing is needed when dealing with interactive elements, it is common for them to change colors when they are hovered, focused, or activated.
Ensure that there is enough contrast between, the color on hover and the color on active, you can use a developer tool or browser extension that updates in real-time as you interact with the site, TPGi’s free color contrast checker tool that allows you to easily determine the contrast ratio of two colors simply using an eyedrop tool.
Don’t use color alone to convey meaning. It is important to know screen readers do not read aloud visual information. The screen reader does not read color information. Non-visual and visual users who cannot access color must be considered when using color to emphasize elements. Information conveyed with color must also be communicated textually to be effective.
Keyboard Tab key
By tabbing through the app, meaning pressing the Tab key on the keyboard to navigate between interactive elements on the page.
Check by testing:
All interactive elements are focusable and have a visible focus state.
The tab order should make sense; usually, it should follow the visual order of elements on the page.
The focus should be trapped inside modals, meaning we shouldn’t be able to tab back to the page behind the modal until we close it, and once we close the modal, the focus should go back to the element that opened the modal.
Skip Link
Skip navigation link should appear when you press the Tab key for the first time. 
Zoom
When zooming the site or app, check how it handles, well, zooming. Zoom in to 200% in the browser and see what breaks. Zoom in when the text is too small for them, make sure that the layout isn’t breaking, the text isn’t cropped, and elements aren’t overlapping each other.
Screen reader
By using the site or app with a screen reader, consider to check - 
All interactive elements are focusable and have accessible labels.
tab order, semantic markup, and textual content make sense.
The skip navigation link brings us directly to the main page content, so we don’t have to listen through all navigation links again and again.
Testing with a screen reader
Screen Readers are in many ways similar to testing with a keyboard. Since we can’t see the screen - recommend turning it off or closing your eyes during testing, do noy  use a mouse or a trackpad to select items on a page, you can only tab to them with a keyboard. The main difference is that you can’t recognize elements like buttons by their look or can’t connect form inputs with labels by their location. Try to define these relationships using semantic markup or ARIA attributes.

On macOS, recommendation is VoiceOver. On Windows, there are built-in Narrator, free NVDA, or paid JAWS. There’s also ChromeVox that we can install as a Chrome extension.
Browser 
Browser reading mode is an accessibility tool itself: it helps readers concentrate on the main content or make colors readable. When using it as a quick way to test the semantic markup of our pages: you should see the main page heading, complete main content, all content images but nothing extra like decorative images or banners.
Reduced motion is an operating system option that tells sites and apps (via prefers-reduced-motion media query) that the user prefers to minimize non-essential motion on the screen. When using it to disable animation on things like reveal on scroll or carousels.

The dark mode could be a site or app option or an operating system option that you can read via prefers-color-scheme media query. Ensure that our site or app, especially colors, is still accessible in the dark mode.
Hover alternatives for keyboard and touchscreens: hover shouldn’t be the only way to reveal some content or an interactive element. A common example is a menu that appears on hover on an item in a long list. A tooltip is another example. When showing these elements, the container is in focus for keyboard users, and always show them on touchscreens.

Manual Testing
Tab Focus ability and order
Keyboard Functionality (with and without screen reader)
Visual Focus indicator
Effective focus managements (forms, dialogs, dynamic content)
Keyboard Traps
Test for meaning conveyed with color
Test alt text quality
Test video/audio accessibility
Test for landmarks
Test link text quality
Test form labels and instructions
Test form validation
Test custom widgets
Manual testing needs to be conducted to validate automated tests and to discover issues that automated tests cannot identify

**Comment by k80bowman** [comment]
Thanks for adding the a11y tools to the document @CourtneyChambers77! I took your list and reformatted it a little, please feel free to correct it if I messed anything up. Otherwise this ticket should be good to close.
