### ISSUE TITLE
Additional Evidence documents don't display after upload

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#3909]
## What happened?
_Within the Claim Status Tool, a capability exists to upload additional evidence for an existing claim. Using a file that conforms to the file types allowed, and seemingly being accepted and uploaded, the file is not available to be viewed._

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: Claim status landing page (will update with link)
- Test User _(if applicable)_: vets.gov.user+299@gmail.com

## Desired behavior
_The [intended behavior](https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Global/Claim%20Status/Screenshots/Claim%20Details%20-%20Files.png) should show the files uploaded_

## Acceptance Criteria
- [ ] After user uploads document with supporting evidence in the Claim Status Tool, the file name, type and date of submission should be displayed.

## Screenshots
![screencapture-staging-va-gov-track-claims-your-claims-600162773-files-2019-12-03-15_28_42](https://user-images.githubusercontent.com/44190602/70948168-dc002880-2028-11ea-9846-6043a53a2a91.png)

**Comment by ndsprinkle** [comment]
I've dug into this a bit and can replicate every time using the user listed above (299). I don't think the user will matter, but I'll try out a couple other users to make sure. Regardless, for this user, this was my testing method:

1. On staging, navigate to claim 600174345 for user 299
2. Switch to the "Files" tab and click "View Details" under "Additional evidence"
3. Click "Add Files" and select my test file called "test.txt"
  - this file simply contains the string "test"
4. Select a file description of "Other Correspondence" and click the checkbox and hit "Submit Files for Review"

After this, the page redirects to the "Files" tab with a confirmation message indicating that the evidence has been uploaded successfully and that it may take a few minutes for the uploaded file to show. Just like with the user, I'd imagine it doesn't matter what file I upload or what file description I choose. No matter how much time passes, no files will appear under "Documents filed". This is expected based on the ticket, but the main observation I took note of was the network request that vets-website made to vets-api.

Upon clicking "Submit Files for Review", a POST request is made to "https://staging-api.va.gov/v0/evss_claims/600174345/documents" that gets a response of "202 Accepted". In the headers under "Form Data", this information is present:

```
tracked_item_id: null
document_type: L023
qquuid: 795e5869-d4dd-4b65-bb41-32fdff2192d4
qqfilename: test.txt
qqtotalfilesize: 4
file: (binary)
```

To me, this seems to be sending the appropriate information to the background. @SMLuthi will need to confirm if anything seems off in this or let me know if any other data is needed from the request, because there's a whole lot of header information. The other thing of note is the response from that request which is:

`{"jobId":"9b1c9e5816a4d0921050cc72"}`

Looking at the request made for the specific claim information, I see a GET request to "https://staging-api.va.gov/v0/evss_claims_async/600174345" that contains the following response:

```
{
    "data": {
        "attributes": {
            "claimType": "Compensation and Pension",
            "contentionList": [
            ],
            "currentPhaseBack": false,
            "dateFiled": "2019-07-11",
            "decisionLetterSent": false,
            "developmentLetterSent": false,
            "documentsNeeded": false,
            "eventsTimeline": [
                {
                    "date": "2019-07-11",
                    "type": "filed"
                }
            ],
            "everPhaseBack": false,
            "evssId": 600174345,
            "maxEstDate": "2021-07-22",
            "minEstDate": "2020-09-22",
            "open": true,
            "phase": 1,
            "phaseChangeDate": "2019-12-11",
            "requestedDecision": false,
            "updatedAt": "2019-12-17T18:30:10.738Z",
            "vaRepresentative": "AMERICAN LEGION",
            "waiverSubmitted": false
        },
        "id": "600174345",
        "type": "evss_claims"
    },
    "meta": {
        "syncStatus": "SUCCESS"
    }
}
```

From that response, I don't see anything related to evidence uploaded other than the Boolean flag "documentsNeeded". This would seem to suggest that vets-website is not receiving any information on documents in this GET request from vets-api, but it is unknown to me if they are even supposed to come in this request. My guess would be that the documents are actually supposed to come from a request to the documents endpoint as seen above with the related POST request to documents. Again, @SMLuthi will probably be able to answer this. If this is the case and the evidence is supposed to come from a GET request to the documents endpoint, then the new mystery would be why vets-website isn't making this request. This will be what I look into next.

**Comment by SMLuthi** [comment]
This has been looked into a bit in the backend. It has been verified that the document upload to S3 works correctly and the job that submits these docs does run as intended. EVSS has mentioned that they want to setup a meeting time to look into these matters and verify that they are, indeed, seeing these files being submitted. As far as I can see, the files are being submitted properly and veterans are not losing their information that they have submitted. This does not explain, though, why the files are not visible to the user afterwards. More investigation needs to be done to see why this is the case (this will take Front End debugging as well).

I have a theory that, since the the submission job that runs the evss document service and submits the files, also removes them from S3 (since we dont need to hold onto them anymore). If thats the case then they would be deleted from our system and the front end would not be able to pull them anymore (since, i believe, we only check our local data for submitted documents). This is A LOT of theory but its plausible and needs to be explored.

**Comment by YanaRoy** [comment]
Primary discovery has been completed for this ticket. Additional BE and FE discovery and resulting work will be identified in separate tickets.

**Comment by SMLuthi** [comment]
@YanaRoy @AZSchneider @ricetj I wanted to give an update on this since I've been working on this all day.

First of all, I want to describe the current procedure on how documents are uploaded and how they are retrieved. All claims are retrieved from an EVSS Service (appropriately named `EVSS::ClaimsService`) and stored in a database table (per user). This is done when a user navigates to the claims page which lists all the documents. These table entries are always updated (both when navigating to the base claims page or the claim details page) since the updates are asynchronous jobs (which is why it takes a bit before anything is displayed).

Furthermore, documents are uploaded via the `EVSS::DocumentsService` which is another asynchronous job. When a veteran selects a file to upload and submits the api will first upload the file to an S3 bucket where we store it locally. The job will then be kicked off where it will retrieve the document from S3, attempt to upload it to the document service, and then, if successful, remove the file from our S3 bucket.

I have tested this entire process by hand and monitored the S3 bucket, the upload job, and what we get back from the claims call... and i've determined that the files are being uploaded correctly to EVSS but the claim data we get back from them does not include them. For example, heres claim data for a claim that i've submitted multiple files and whose upload jobs succeeded (which can be verified since the files do not exist in the S3 bucket anymore):

```
[{"appeal_possible"=>"No",
  "attention_needed"=>"No",
  "base_end_product_code"=>"400",
  "benefit_claim_type_code"=>"400PREDSCHRG",
  "claim_consolidatable"=>true,
  "claim_phase_dates"=>
   {"current_phase_back"=>false,
    "ever_phase_back"=>false,
    "phase_change_date"=>"10/08/2019"},
  "claim_status"=>"PEND",
  "claim_tracked_items"=>{},
  "consolidated_tracked_items_list"=>[],
  "date"=>"02/01/2020",
  "dbq_list"=>[],
  "decision_notification_sent"=>"No",
  "development_letter_sent"=>"No",
  "end_product_code"=>"407",
  "id"=>"600167902",
  "latest_evidence_recd_date"=>"11/29/2012",
  "new_evidence_received"=>false,
  "past_est_claim_date"=>false,
  "past_evidence_due_date"=>false,
  "past_phase_est_date"=>false,
  "program_type"=>"CPL",
  "status"=>"UNDER REVIEW",
  "status_changed"=>false,
  "status_type"=>"Compensation",
  "submitter_application_code"=>"VBMS",
  "submitter_role_code"=>"VBA",
  "vba_document_list"=>[],
  "waiver5103_submitted"=>false,
  "wwd"=>[],
  "wwr"=>[],
  "wwsnfy"=>[]}]
```

Im not familiar with all these fields or what they represent but I assume `vba_document_list` *should* contain the list of uploaded documents(?) as well as `latest_evidence_recd_date` should contain todays date since I uploaded evidence(?).

Regardless, at this point the EVSS sustainment team *must* become involved to see how they are associating and tracking this evidence on their side. Hopefully, the evidence is being submitted correctly by then but is just not being retrieved correctly so no data loss is occurring.

In any case, I will attempt to setup a meeting next week so we can correspond and hopefuly solve this quickly.
