### ISSUE TITLE
Consistency Audit: Alert Boxes

### ISSUE THREAD

**Issue by k80bowman** [department-of-veterans-affairs/va.gov-team#39112]
## Description
We would like to identify any discrepancies in the documentation on design.va.gov and the component and any associated documentation in Storybook.

Analyze the documentation for the [Alert Boxes component](https://design.va.gov/components/alertboxes) component on design.va.gov and the instance of the [va-alert](https://design.va.gov/storybook/?path=/docs/components-va-alert--default) component in Storybook and add a list of discrepancies found to this ticket.

## Acceptance Criteria
- [x] Identify discrepancies between design.va.gov and Storybook for the Alert Boxes component
- [ ] List discrepancies in this ticket
- [ ] List information and discrepancies in this google sheet   https://docs.google.com/spreadsheets/d/17Fw7flaFcd4CG24E_bBTb4Hq0AEfrT2ivjHqrjuACos/edit?usp=sharing 
- [ ] Alert Carol and Katy for review

**Comment by humancompanion-usds** [comment]
Discrepancies thus far:
1. Labels are different. Alert boxes vs va-alert
2. Examples and stories do not line up well. Specifcally, for ""Sign in or tool prompt"" the example in the Sketch library is much more useful and instructive than what is in the design system. The example in Storybook should be updated to match 
3. There are more stories than examples
4. The background-color examples have a ""close-btn-aria-label"" but don't need it since there is no close button. Would be good to remove the extraneous attribute.
5. The Design System doesn't show each background color alert and it should ala USWDS.

**Comment by humancompanion-usds** [comment]
For the Sketch library:

1. Variation named "Sign in or tool prompt" in Design System looks to be the same as "Continue" in Sketch Library. Use the design system name. 
2. There is a "success-small" variation in Sketch that doesn't exist in the system. It seems similar to the USWDS Alert - Slim variation. 
3. The padding issue mentioned in issue #470 must have been fixed at some point. However, our padding should probably be 16px instead of 20px and our left-border 8px instead of 10px in order to match the USWDS. Our alerts are a little chonky.
