### ISSUE TITLE
Create mockup of recent claim and show more button

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#39206]
Create rough mockup for the claims status list that displays the most recent claims item with a button to show or hide more, with an eye toward making it a11y as quickly as possible. 

Here is the original ticket from Robin that was discussed. 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38778

Here are the DSC meeting notes. 
https://docs.google.com/document/d/1O1eF-2PVy2kzkmeYAWDVqonab6ue7p1b0u4yoG76xnE/edit?usp=sharing

- [x] Create mockups
- [x] Share mockups with Kevin Stachura and Robin

**Comment by humancompanion-usds** [comment]
@kevinstachura and @Mottie - I created a few variations here: 
https://sketch.com/s/7911b32b-fc39-4a44-b9e8-f0f9b1554170

### Artboard 01
Artboard01 is, I believe, what we landed on during the Design System Council meeting. It has:
* Headers for latest and older updates with a count 
* A button for showing older updates

Artboard 01b shows the expanded state which expresses Kevin's note that the button/toggle should stay put rather than shift down the page. This doesn't solve the problem of paginating or handling in some way the length of the list.

### Artboard 02
Artboard 02 mitigates that issue slightly by adding in a "Recent updates" section which could show 5, 10, or 25 recent entries (I used 5 in the mock-up but you pick what you think is appropriate for your data and use case) and then pushes the remaining entries into an "Older updates" section with a "+ Show older updates" link. I have a question into Courtney about whether it would be appropriate or not from an a11y perspective to combine that link and header into a header that is visually styled to look like a link. For now I went with the safer option of keeping them distinct.

Also, while I choose "recent" to mean some number of items you could also consider organizing and displaying them by time. For example, "recent" could mean in the last 1, 3, or 6 months. 

While I didn't show the expanded state here the link would simply change from "+ Show older updates" to "- hide older updates" and stay in place ala the button in 01. 

### Artboard03
Artboard 03 shows the "[View more items in a list](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/677)" component that was just proposed. IMHO, that works well when the list is short but doesn't do much to address a long list nor the a11y navigation issues that Courtney raised in the discussion on Friday. I would not advise doing this one.

Finally, one thing that is a concern on this page is the mashup of the Process list and Accordion components. I don't know that the drawer handles (+, -) by themselves give enough visual affordance for the accordion. When I've seen this problem in the past it causes users to feel that they have to be very precise in interacting with the tiny drawer handle. [Fitts Law](https://lawsofux.com/fittss-law/) speaks to this and is why accordions generally have a large drawer face that is easy to recognize and interact with (in our case the entire large, grey bar that makes up the drawer face can be clicked on). I tried to address this in artboard02b but, I'm new here so if this is a combination of components that we have tested and know it works then feel free to ignore me. If not, perhaps we can talk more about it.

**Comment by kevinstachura** [comment]
Hey @humancompanion-usds, thanks for putting all this together! These are all excellent options. After taking a look and conferring with @Mottie about what makes sense currently in the Claims Status Tool, we determined Artboard 01 (and expanded 01b) is the best option to work from. From your comment above it sounds like it checks off all the boxes brought up in the aforementioned Council meeting with the one exception being length of expanded list. Of course, we can always implement this as a foundation to get started and improve it in the future to add pagination or some sort of progressive reveal. 

Any thoughts, comments or concerns? Let us know! Thanks.

**Comment by humancompanion-usds** [comment]
No immediate concerns. There was another suggestion that if the list is particularly long that it be replaced by a link to an additional page with the full history. We've got a [similar issue coming up ](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/677) where perhaps we can start to address the long list issue.
