### ISSUE TITLE
[Design] Update wireframes for the change from using last 4 to DOB

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#39283]
## Description
Update wireframes for the change from using last 4 to DOB.

## AC
- Post to sketch for teams

## UX Deliverable
- [Wireframe](https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/B487E10B-C67A-4B83-9567-E0257BEF855C) is ready for review: 
https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/B487E10B-C67A-4B83-9567-E0257BEF855C

**Comment by zach-park** [comment]
The wireframe is ready for review now: https://www.sketch.com/s/5331b114-280d-4ff5-8d36-ec49b1696b9e/a/uuid/B487E10B-C67A-4B83-9567-E0257BEF855C
@loripusey @niradatta1 @kristenmcconnell @acrollet @brianseek

**Comment by loripusey** [comment]
Looks good!

**Comment by acrollet** [comment]
@zach-park the wireframe looks good! I'm seeing a couple of discrepancies between the design and what the DS date component gives us:

1. At a similarly narrow width, the year field wraps to the next line, as we discussed before:
![Screen Shot 2022-04-22 at 8 40 12 AM](https://user-images.githubusercontent.com/101649/164737423-6e24a3a3-c558-492b-af55-c4a86e8cb111.png)
2. The DS component provides a text entry field for the year rather than a dropdown as you have specified.

Do we want to proceed with what the DS component offers or start a discussion with the DS team about whether the DS component could be changed or made configurable?

**Comment by zach-park** [comment]
Hi @acrollet , regarding the #1, yes we did discuss it to allow for wrapping to the next line in <400-ish. - While I was working on the wireframe, I thought it didn't look ideal. It is challenging to make that change, then we can leave it as is. As for the second commetn, thanks for catching it. It was intended as a text fielf form as you mentioned. I've updated the wireframe. Thank you!

**Comment by kristenmcconnell** [comment]
@acrollet @zach-park 
Side note: The design system team decided on Friday that they will be redesigning this text input component soon. If we do learn anything that would be helpful to their redesign, we might want to send it to Carol Wong.
