### ISSUE TITLE
Analytics Feature Request

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#39328]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [x] Ticket Description
- [x] Request/Report Description
- [x] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - [Product Manager, Facilities team, Vet Center pages]

- Is this a feature request or a bug?

  - [x] Feature request
  - [ ] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 

For a new feature request:

- Description of desired feature: 
  - For VA.gov Content KPIs, Click interactions section: Table for interactions with most clicks should have the ability to expand display beyond top ten. Example of current functionality (filtered for the Vet Center product)
  
![image](https://user-images.githubusercontent.com/55411834/160705681-43088a91-4457-4c88-a4e2-d5466d0e5e38.png)

**Why the feature is needed**
- Current list doesn't give full information, particularly when viewing analytics for pages in aggregate. There will be 300 Vet Centers when they are all rolled out. 

**Who is your audience?** 
- Product Managers - but also Vet Center leadership who need/want to view analytics for all Vet Centers in aggregate or even at a district level. 

**To answer questions such as...**
 - Interactions with accordions...
   - Which counseling/referral/other service is viewed most often? Least often? 
   - Which "Prepare for your visit" content is most often viewed? Least often?
   - Which FAQ is most often viewed? Least often?
   - The above are in 24+ accordions (10-18 service accordions, 4+ "Prepare for your visit" accordions and 4 FAQ accordions) so a list of 10 provides a partial view of the world. 
- Links...
  - pages have some common links (national spotlight featuring a Veteran testimonial video, for example) but individual Vet Centers highlight local activities with registration links or community partner websites, etc. 

**What area of the VA are you hoping to assess?** 
  - Vet Center pages (example: [Cape Cod Vet Center](https://www.va.gov/cape-cod-vet-center/))

**How frequently do you need this data?** 
  - monthly data would probably suffice

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by michelle-dooley** [comment]
@mmiddaugh thank you for your request.  That certainly makes sense.  We will update that card so it has scroll capabilities to see more entries past 10.

**Comment by chloedotbrown** [comment]
Hi @mmiddaugh - I've updated the [Content Dashboard](https://va-gov.domo.com/page/426422632) card: 

- All interaction events are now listed in descending order, with no "Top 10" limit.
- I've added a new column for `Page title`, so that click events with the same name are disaggregated by the page where they occur (and easier to find!). 
- I've also added a Quick Filter to the card, so that you and your stakeholders can search for matches by event action. This doesn't appear on the dashboard itself, but it should pop up in the [card detail view](https://va-gov.domo.com/page/426422632/kpis/details/1727922670?pfilters=%5B%7B%22column%22:%22product%22,%22operand%22:%22IN%22,%22values%22:%5B%22Vet%20Center%20pages%22%5D,%22dataType%22:%22string%22,%22affectedCardUrns%22:%5B%5D,%22label%22:%22product%22,%22dataSourceId%22:%22b677d6c5-5a79-41c8-a3a8-438fb769ffc3%22%7D%5D&refreshPageFilters=true). This should help with the use-case you mentioned in the ticket. Check out the GIF-based demo is below!

As you can see in the demo, there are an unusual amount of "section - label" events we're getting for your product. Addressing this probably makes more sense to wrap into the tagging work from the other ticket you submitted (#39329), but I'll flag it for folks on our team as well.

Let me know if these changes solve this part of the issue or if you have any questions!

![Content_Engagement_Demo](https://user-images.githubusercontent.com/45518242/160926669-c08dfb05-c7c9-417a-8f89-d099e515a334.gif)

**Comment by mmiddaugh** [comment]
These changes are amazing and I can't believe how quickly you made them happen! Thank you!!
So now my question is....is it still possible to see a particular event action in aggregate? (for example: the number of clicks on "Couples and family counseling" for all Vet center pages, rather than Colorado Springs specifically)

I love the access to the quick filter - is there a way to select all? 
For example: 
![image](https://user-images.githubusercontent.com/55411834/161124407-21542de3-c03e-475a-af4a-1df5f5560085.png)

**Comment by chloedotbrown** [comment]
Hey @mmiddaugh - thanks for your patience on these questions!

1. **Viewing event actions in aggregate** -  Yes, we can totally do this. With Domo's drilldown functionality, the easiest way is actually going to be to return to the original version of the card, showing just event label and click counts. From there, I've enabled drilling in place, so you can click to see which pages had the the highest totals with that event label - all without leaving the dashboard. You could then even add specific page title filters on the dashboard and return to the original version of the chart to see what the other top clicks were on that particular page. I'll include another GIF demo below.
2. **"Select all" on card-level filter** - This is also doable! All you need to do is hit the orange "apply" button. Because the filter limits by any value that contains that text, all the options in the preview will be included.

If you have any other questions on the dashboard-side, please let me know!

![Content_Engagement_Demo_2](https://user-images.githubusercontent.com/45518242/161864583-c8be7e21-d26d-43b3-8fe9-fed03d6ea041.gif)

**Comment by mmiddaugh** [comment]
fantastic!! Thank you!
