### ISSUE TITLE
Design - Auth Profile - Update Direct Deposit Sketch files to reflect what is in staging + prod

### ISSUE THREAD

**Issue by MarciMcGuireGCIO** [department-of-veterans-affairs/va.gov-team#39348]
## Background
Liz noted in a [Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1646671685108269) that the Sketch files for Direct Deposit do not match what is currently in Prod. 

## Tasks
- [x] Update Sketch files to match what is currently coded out (reflected in staging + production)

## Acceptance Criteria
- [x] Update Sketch files to match what is currently in (reflected in staging + production)

**Comment by cgednalske** [comment]
[Desktop](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/p/0132D414-4FCE-4F51-A4A4-EE4238E8BE6A) and [Mobile](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/p/837E4048-F554-48CA-B877-2C1007AB5D43) have been updated based on prod/staging (and guidance in Contact Center Documentation). I've also checked the spacing compared to staging.

@andaleliz do you want to take a look and see if there's anything missing? I've also added just a few on-screen comments where I wasn't sure about a couple things.

**Comment by andaleliz** [comment]
Thanks @cgednalske! I don't see anything missing. Wrt to your comments (your eagle eyes are awesome!):

1. The copy for the EDU section was leftover from the first version of DD, before we added the ability to update EDU dd info. The very first screen has the current copy and I updated it across the screens. 

2. The success message looks like it's following the previous style of success message we had in profile, where the message displays at the top of the page. At the time, our focus was contact info so it looks like DD got missed when we moved the success message above the edit button, and shortened to say "update saved" instead of the longer message we see here:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/55992116/168902159-7fbf915b-f10a-40e0-b3c4-833a7abe66ef.png">

@Samara-Strauss I think we should update the DD success message to follow the same pattern in the other parts of profile. Do you agree? If so, is there any reason we need to keep the long success message, or can we just say "update saved" like we do in contact info? 

3. The "You can't update your financial info" alert you questioned, Christina, is no longer in use and I deleted it. Thank you!

**Comment by Samara-Strauss** [comment]
> I think we should update the DD success message to follow the same pattern in the other parts of profile. Do you agree? If so, is there any reason we need to keep the long success message, or can we just say "update saved" like we do in contact info?

Agreed that we should update, and I don't think there is any reason for more lengthy copy. We can follow the same pattern/copy we use elsewhere.

**Comment by andaleliz** [comment]
Awesome! Thank you. I will create a ticket to update the Sketch file with this new update. 

Note to self/team: when FE works on it, we should also update all success/error alerts to match the design - currently they are too narrow. Erik knew about this and meant to fix it but he didn't get around to it before he left. Ah! I still miss him.

**Comment by cgednalske** [comment]
@andaleliz Awesome, thanks for checking all that and deleting the outdated info! Doesn't sound like there's anything else for me to update, but let me know if something else comes up.

**Comment by andaleliz** [comment]
Will do! I think we can close this one out. Just in the nick of time.
