### ISSUE TITLE
Internal - Authenticated Experience Edge Case

### ISSUE THREAD

**Issue by michelle-dooley** [department-of-veterans-affairs/va.gov-team#39361]
## Issue Description
This ticket is for internal team communication regarding the Authenticated Experience edge case. 

https://github.com/department-of-veterans-affairs/va.gov-team/issues/31302

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by michelle-dooley** [comment]
@pavanhothi is leading.  We have a meeting scheduled on 4/4 with @michelle-dooley @pavanhothi @jonathan-epstein13 and @chloedotbrown to discuss findings and next steps.

**Comment by chloedotbrown** [comment]
Hey @pavanhothi - great news! I think you'll be able to use the data we already have in Domo for a new search ETL after all. It's probably worth connecting directly to the [Standard Search BQ connector](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/overview) instead of the output from another ETL, but the data is the same and it looks like "my-va" `page_paths` only come up for All VA search (as expected), so we don't need to filter by `search_scope`.

Sounds like you're set for the ETL creation, but if you have any questions about that or syntax for tech defs, always feel free to reach out!

**Comment by pavanhothi** [comment]
Updated [KPI discovery & Build/QA tracker - MyVA](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=871242321) with requested Medallia KPI metric, also created and linked new [search ETL](https://va-gov.domo.com/datasources/52770ab7-579a-44df-8f0c-5294acd9105e/details/overview) for MyVA specific search queries, and updated all technical definitions as needed. 

Wrapping up dashboard mock-up, will update ticket again and share out shortly.

**Comment by pavanhothi** [comment]
Here is the [MyVA dashboard mockup](https://docs.google.com/presentation/d/1pRNXgjE-h5g1JLhzOJM-DTePMoKAkdWKytsJ4OdADvI/edit#slide=id.g11b31d375b2_0_0) based off the metrics in the [KPI discovery & Build/QA tracker - MyVA](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=871242321). @jonathan-epstein13 if you want to look over and provide any feedback, that would be great. Thanks!

**Comment by chloedotbrown** [comment]
### Overall notes:

- **Length**: This draft still feels too brief! How can we build out what we're showing? I'll add some suggestions below.
- **Presentation**: Before sharing this with stakeholders, we should clean this up a bit:
  - Aspect ratio of screenshots should be locked so that text is not obviously stretched. Whenever possible, text should not be included in image and done with Google Slides text boxes instead for readability. 
  - Even when using demo data tables, we should avoid placing identical tables next to each other, as this can distract and confuse readers. Consider building tables from scratch out of Google Slides shapes ([see example from All VA mockup](https://docs.google.com/presentation/d/1o3MHYr2Xpd4wXoXcY-c--wI6qoF1P34iXNzdQIhVJVk/edit#slide=id.ged7232c0b1_0_190)).
- **Visualization style**: This dashboard is very table-heavy, and in general, the visualization type doesn't always make the most sense for the type of data / use case.
- **KPI framework**: There are no Findability metrics on this mockup/spreadsheet - the team actually defines all their search rank metrics under "findability" in their [OKR / KPI plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md#okrs--kpis), so we should too.
- **Team reporting needs**: Related to point above, we should be making sure that the way we're visualizing this data matches how we know this team needs to report on it to their stakeholders, so that we're saving them time.
- **Triple-check datasources**: There's a couple datasets listed in the spreadsheet I'm not sure are the best fit for what we're actually trying to show here. We should take a _really close_ look at the query setting to make sure they match our use case and/or what we're trying to carry over from their existing custom GA reports! 

### Feedback by section:

_I'm including notes on both the [mockup](https://docs.google.com/presentation/d/1pRNXgjE-h5g1JLhzOJM-DTePMoKAkdWKytsJ4OdADvI/edit#slide=id.g11b31d375b2_0_105) and the metrics definition [spreadsheet](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=871242321) here, so that it's easier to track everything in one spot._

- **Highlights**
  - _**Percent of logged in users who interact with the homepage**_ - The way this metric is created in the query vs. how segment is defined in the team's existing [GA report](https://analytics.google.com/analytics/web/?authuser=0#/report/visitors-overview/a50123418w177519031p184624291/_u.date00=20210401&_u.date01=20210630&_.useg=builtin1,useroZx0HcxxRpWtuNYX7IFkHA,userTBuj9_dPSF-sBQQO9Srv-g/) does not match. I'd recommend we defer to the GA report logic, assuming it makes sense (I'm not sure why their segment has a LOA rule?).
  -  **_[Suggested add] Total interaction clicks_** - combines clicks into claims, messages, appointment, and prescription CTAs
    - **_[Suggested add] Percent of MyVA searches including feature keywords_** - (total search events including flagged words originating from MyVA) ÷ (total search events originating from MyVA). Would require new ETL and would require new feature request from team if they wanted to change their feature term list. 
- **Ease of use** (current content needs to be moved to Findability)
  - **_[Suggested add] Percent of logged in users who visit MyVA by month_** - same metric as gauge in Highlights, but shown over time.
  -  **_[Suggested add] Unauthenticated clicks to MyVA_**: Tracks whether header nav link is helping non-logged in users find MyVA. Reason for including - team has [GA report ](https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p184624291/_.useg=builtin1,userBgZiUrK9Sieg7jBAnx44OQ&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.filter=Navigation%20-%20Header%20-%20My%20VA/)linked in their [OKR / KPI plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2.0-redesign/README.md#okrs--kpis).
- **Findability** (section currently missing) 
  - **_Search ranks on MyVA_** - This card is not quite showing the data requested. Instead of showing the top searches, they need to be able to see the rank number of specific search terms. I don't think one of these heatmap tables is going to be the best way to accomplish this, so we should go back to the drawing board on chart selection. 
  - **_Search ranks on MyVA_**: Same as above ☝️. Also, we will need to add LOA to [Standard Search dataset](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/data/schema) to be able to provide the metric they asked for, since they're tracking [_logged in_ VA.gov search](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-search-terms/a50123418w177519031p184624291/explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&_.useg=user8twPUpCZT8qMEc9RwdXoUg/). (cc: @obrienjulie)
- **Task completion**
  - **_[Delete] Total My VA CTA interactions by month_** - New suggested Highlights card covers this information. Also, we will need a new datasource to support either way, since the one listed here is only going to grab `dashboard-navigation` events.
  - **_MyVA interactions by clicks_** - similar to the search ranking cards, I'm not sure a table is the best way to show the data as this team needs to be able to report on it. Rather than asking "what are the top interactions?", they want to know "how many clicks are these _specific_ interactions getting?" Recommend experimenting with small multiples, multi-line charts, etc. to be able to show with time component too.
- **User satisfaction**: Currently listed as not in BQ - which it isn't for security reasons! But Contact Center does have this data in Domo. You should explore to see if product mapping for MyVA already exists and if so, if there are any other KPIs that might be meaningful to visualize here.

**Comment by pavanhothi** [comment]
Thanks for all the feedback @chloedotbrown! Will begin going through making the necessary updates and changes. May ping you as questions come up.

**Comment by pavanhothi** [comment]
@michelle-dooley @chloedotbrown The [MyVA dashboard mockup](https://docs.google.com/presentation/d/1pRNXgjE-h5g1JLhzOJM-DTePMoKAkdWKytsJ4OdADvI/edit#slide=id.g11b31d375b2_0_0) has been revised and updated based off feedback received. 
- Reordered sections so Task completion comes before Ease of use
- Moved previous content in Ease of Use to new Findability section
- Added new metrics to Ease of use section (Percent of logged in users who visit MyVA by month, Unauthenticated clicks to MyVA)
- Added additional new metrics to Highlights (Total interaction clicks, Percent of MyVA searches including feature keywords)
- Removed Total My VA CTA interactions by month from Task completion
- Changed previous chart types as needed to make more sense and align more with the metrics being tracked and reporting needs of the team
- Locked aspect ratio of screenshots
- Changed any identical tables to avoid confusion

The [KPI discovery & Build/QA tracker - MyVA](https://docs.google.com/spreadsheets/d/1OVHaY2wewVz06s8TAwrdXxPSLzjC0Oqg-d39ECXjduY/edit#gid=871242321) has also been updated to reflect new metrics and deleted any metrics which were removed. There are a few metrics currently on the spreadsheet where the data source column is blank. Working on new ETLs etc and will have those updated soon as well.

**Comment by chloedotbrown** [comment]
### Feedback by section:

- **Highlights**
  - _**Title length**_ - Remember, Domo does not wrap titles! Some of these will be too long to be readable. Rewrite to shorten in mockup with that constraint in mind.
- **Task completion**
  - **_MyVA interactions by clicks_** - There's too much going on here for it to be easily understandable by the viewer. However, since the "total clicks" metric in the Highlights section is just a multi-value gauge, we have to worry less about potential redundancy here. I'd recommend splitting this into the following two charts:
    - Single line chart showing ALL click interactions by month
    - Table or horizontal bar chart showing top X clicks across time period selected
  
- **Ease of use** 
  - **_Titles and headers_** - Title text is a little long and pretty similar. Let's rewrite the headers to better frame why metrics are important and the titles are easier to skim.
  - **_Percent of logged in users_** - The aspect-ratio is stretched on the text and seeing Y-axis in the millions when it's for a metric that's in percents is probably going to be distracting, even for a mockup. I'd recommend cropping the image to remove them.
  -  **_Unauthenticated user interactions_** - It's a good idea to use a different chart type to clarify that these are pretty different metrics. However, showing this one as a PoP chart makes is seem like year-over-year comparisons are especially important for this metric versus others, which I don't think as true. Maybe try a line chart instead?
  
- **Findability**
  - **_Search ranks on MyVA/VA.gov_** - This card _still_ isn't showing the data requested. Instead of showing the top searches, we need to be able to see the rank number of specific search terms. I've put together [two potential alternatives](https://docs.google.com/presentation/d/1OIWWIPkroAsnftoK8WJs2q5VRJvd76wXgfuCTEFy0BY/edit#slide=id.g11b31d375b2_0_216) to consider. The table would likely be easier to read and skim for reporting, but are less interesting to look at or view trends over time on the dashboard. The line charts are easy to see trends, but may be confusing because of how they're constructed.

- **User satisfaction**: This section is a little slim. To expand, you might want to just borrow a screenshot from the bottom of the [VAOS dashboard](https://va-gov.domo.com/page/202515362), since it'll be using the exact same structure of data.

**Comment by pavanhothi** [comment]
@michelle-dooley @chloedotbrown Just wanted to leave latest update for the [MyVA Edge Case Dashboard Mockup](https://docs.google.com/presentation/d/1pRNXgjE-h5g1JLhzOJM-DTePMoKAkdWKytsJ4OdADvI/edit#slide=id.g11b31d375b2_0_0)

- Rewrote and shortened titles on Highlights slide
- On Task completion slide split the metric into two charts: line chart showing total click interactions and a horizontal bar chart showing top X clicks
- On Ease of use slide fixed titles and headers so not so long and similar, locked aspect ratio for "Percent of logged in users" metric and cropped out misleading y-axis, and used a line chart now instead for the "Unauthenticated user interactions" metric
- For Findability slide used @chloedotbrown table chart mockups for the metrics
- For User satisfaction slide used screenshot from VAOS dashboard's User satisfaction section since it'll have the same structure of data

If we are content with the mockup and will be moving forward with getting it to the Authenticated Experience team, the only thing left to confirm with them regarding the search rankings as @chloedotbrown mentioned would be:
- Is the list of MyVA keywords they want tracked still current/complete?
- Do they want this to only be logged-in searches, like their current [GA report](https://analytics.google.com/analytics/web/?authuser=0#/report/content-site-search-search-terms/a50123418w177519031p184624291/explorer-table.plotKeys%3D%5B%5D&explorer-table.rowCount%3D25&_.useg%3Duser8twPUpCZT8qMEc9RwdXoUg)? If so, we'll need @obrienjulie to add LOA to the Standard Search dataset.

**Comment by chloedotbrown** [comment]
Thanks, @pavanhothi - these are strong edits! @michelle-dooley - any other changes you'd like to see before we reengage with the team?

**Comment by michelle-dooley** [comment]
Thanks @pavanhothi for the updates and @chloedotbrown for your feedback assistance!!  The only additional feedback I have is can we add the labels to the "Top key click interactions" chart on Task Completion slide just so its clear.  They will probably get it but just to avoid possible questions as to what we will be showing there.  @pavanhothi once you make that update I will add the link in their original ticket and and ask to schedule time to review with them.  Thanks again!!

**Comment by pavanhothi** [comment]
@michelle-dooley labels have been added to the "Top key click interactions" chart. Please let me know if any other updates are needed, thank you!

**Comment by michelle-dooley** [comment]
Closing this ticket.  We can update client ticket after meeting today if they decide to proceed and create a new internal ticket for that work if needed.
