### ISSUE TITLE
Content Review from VA Notify Strike Team

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#39389]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [x] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*
We would like to have our content reviewed for the reminder emails we plan to send to Veterans when they have begun a form but haven't completed it. I've attached our artifacts below.

  
## Supporting Artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [Here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va.gov-strike-team/in-progress-reminders.md)
- Link to or attach user flows: [Here](https://github.com/department-of-veterans-affairs/va.gov-team/files/8366172/Application.reminders.user.flow.pdf)
- Link to prototype or mockups: [HTML Email Here](https://images.zenhubusercontent.com/5bbd3157d467817a2f85fcf4/b1cd4b08-7a04-43b9-b1b5-6589f17687bd) [Plain Text Email Here](https://images.zenhubusercontent.com/5bbd3157d467817a2f85fcf4/a853f80a-6299-48a0-b704-acacc77ab046)
- Link to any epics/issues that may be helpful: [Here](https://github.com/department-of-veterans-affairs/vanotify-team/issues/151)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Late April/Early May
- Estimated staging review date: April 15
- Content and IA work needed by: April 15

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Beverly Nelson
-	Product manager: Megan Siddle
-	Designer: Ian Hilton and Elissa Folk
-	FE engineer: Nathan Wright
-	Product/team Slack channel: va-notify-forms-strike-team

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Stan Gardner.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by megansiddle** [comment]
@bethpottsVADEPO @DanielleThierryUSDSVA  Hello! This work has passed the staging review of the Collab Cycle which has some Content checks.  Is there anything else we need to do?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megansiddle. @bethpottsVADEPO and I just took a quick look at this and we do see some style guide issues to address. We're in between content teams right now so couldn't get to this before now. Will post feedback early next week. Thanks!

**Comment by megansiddle** [comment]
Ok thanks @DanielleThierryUSDSVA Just wanted to include the latest email. I didn't realize the other was outdated.
<img width="473" alt="image" src="https://user-images.githubusercontent.com/99678581/164803163-aa7470d5-fd03-49de-b273-2d8efc074ac1.png">

**Comment by megansiddle** [comment]
Hi @DanielleThierryUSDSVA and @bethpottsVADEPO! I wanted to touch base on your potential feedback. Is it something we could address post launch? Our email templates allow for easily made updates and tweaks.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megansiddle! Good timing to check in!

Here are the plain language/style guide comments from @RLHecht (Thank you, Randi!).

[VA notify_copy edit.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/8574090/VA.notify_copy.edit.pdf)

Let us know if you have any questions about these!

**Another consideration that isn't specifically tied to the style guide:**

Beth and I recommend removing "Thank you for your service, VA.gov" from our notifications. 

We know that while this sentiment is appreciated by some Veterans, others feel negatively about it. In some cases, it can even trigger a trauma response. Since this is a mass communication, we want to err on the side of not risking causing a negative or painful reaction. And it seems impersonal to be coming from "VA.gov" as a website so we don't think it adds enough value to warrant the risk. 

This is especially important in notifications that deal with negative impacts to a Veteran. For example, we wouldn't ever want to juxtapose a claim denial notice or a notice about debt with "Thank you for your service," as that could feel almost dismissive or lacking in empathy.

Feel free to reach out with questions about this and let us know if you'd like to talk about other options for a sign off. Thanks!
 
 cc @bethpottsVADEPO

**Comment by megansiddle** [comment]
Thank you! We have updated the content accordingly!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks so much, @megansiddle!
