### ISSUE TITLE
Transform "QA Dashboard documentation"

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#39409]
# User story

# Tasks

- [ ] make a copy of the live page, into the drafts space
- [ ] revise the page for plain language and readability, consult slack thread listed below
- [ ] 

# Acceptance criteria
* Revised page is ready for twice-weekly deploy

# Reference info
Page to be updated: https://depo-platform-documentation.scrollhelp.site/developer-docs/QA-Dashboard-Documentation.2013200394.html

Slack thread with Gretchen's notes on the doc: https://adhoc.slack.com/archives/C02LYB7QXS5/p1648492666951729

**Comment by amygoldman** [comment]
Copy link: https://vfs.atlassian.net/wiki/spaces/PWD/pages/2151317518/Copy+of+QA+Dashboard+Documentation

**Comment by amygoldman** [comment]
Gretchen's notes on the QA Dashboard Documentation page

Proposed new title: QA Dashboard guide
Rationale: The user is on a documentation site. Including “Documentation” in the title is redundant.
Also consider updating it to something like “QA Practice Health Dashboard guide” to be more descriptive of what the dashboard communicates.

1. I would **revise and combine the first sentence** with the “Why a QA dashboard?” section and convert it to the intro to the page.
2. I’m not sure that **the screenshot** is adding much value to the page as it is now. I think they’re trying to give a sense for what the dashboard looks like, but it doesn’t have any descriptive text and I think it might be more of a distraction than a help. Consider moving to after the intro section and adding a caption or moving it to the “Front End Unit Tests” section (and adding a caption) since it’s a screenshot specific to Frontend unit tests.
3. The “Why a QA dashboard section should be revised to be more concise, focused on the end user, with simpler sentence structure.
- It gets a Hemmingway readability level of Grade 15: https://hemingwayapp.com/ We should shoot for a max of Grade 8.
- I think we can remove the entire second paragraph
3. There are several **style guide tweaks** that should be made. Here are the issues I think are highest priority:
- Front End —> frontend
- platform —> Platform
- veteran —> Veteran
- There’s one sentence that includes “VFS teams.” Per the style guide, reword setnence to have a more conversational tone e.g., “VFS teams execute functional tests manually based on their own cadence.“—> “Execute functional tests manually on your own cadence.”
4. **Heading structure tweaks:**
- “Getting around the Product Dashboard” section has an orphaned sub-heading. If we can’t break that section up into more than one subsection, we should rework it to eliminate the need for the “Filtering” heading.
- Update “How to access the QA Product…” heading to be “Accessing the QA Product Dashboard List” for parallel structure
- Update “Getting around the Product Dashboard” heading to be “Using the QA Product Dashboard” for simplicity and consistency in how we refer to the dashboard
5. **The “How to access the QA Product Dashboard” section** 
- includes step-by-step instructions. Change paragraph format of section to a numbered list
6. **The “Product Directory” section:**
- It’s not abundantly clear how the product directory relates to the dashboard when scanning the headings. Would it be accurate to give this section a heading of “Data sources”?
- Update the formatting of the list of critical fields. Per the style guide, we use numbered lists for things that happen in a sequence. Either use a bulleted list for this or convert it to a table. Consider also adding a subheading to make it easy to recognize that these are “Critical” fields when scanning the page.
- The last paragraph could also have a heading added for easier scanability. Something like, “Updating blank data fields”
- The last sentence could be removed since there is a section on the page dedicated to requesting support from the QA team.

**Comment by amygoldman** [comment]
Amy & Lauren are doing #1 and #3 together during sync

Lauren will focus on #4 today

**Comment by laucon** [comment]
There are 4 substeps in step 4. I haven't done step 4 substep 4 because I don't understand the sentence, "VFS teams execute functional tests manually based on their own cadence." Like, what even is "cadence?" So maybe we can work on that together later.

**Comment by laucon** [comment]
In step 4, someone asked to turn "platform" into "Platform." But I think most instances of "platform" should stay lowercase because these specific instances involve mentions slack channels like "#vfs-platform-support" and slack channels are lowercase. So I think the context overrides this specific style guide rule here.

**Comment by amygoldman** [comment]
> In step 4, someone asked to turn "platform" into "Platform." But I think most instances of "platform" should stay lowercase because these specific instances involve mentions of slack channels like "#vfs-platform-support" and slack channels are lowercase. So I think the context overrides this specific style guide rule here.

Yes, whenever "platform" is in a Slack channel name, leave it lowercase.

**Comment by amygoldman** [comment]
> There are 4 substeps in step 4. I haven't done step 4 substep 4 because I don't understand the sentence, "VFS teams execute functional tests manually based on their own cadence." Like, what even is "cadence?" So maybe we can work on that together later.

It's a confusing sentence! We can definitely work on this together. I'll set up another sync for tomorrow.

**Comment by laucon** [comment]
@amygoldman hey! so there was so much here to go through and rewrite. I didn't quite have the mental capacity to go through everything because there was so much to do. And I wasn't clear if we should have a finished draft by tomorow or if we should just have a ton of stuff done to talk about tomorow. We have a ton of stuff done, but not the whole thing because there's a lot. So number 6 was a biggie and I tackled it. It entailed a complex process that I had inadvertently just done myself and was wishing someone had written out better instructions for me (that process being getting access to DOMO.) So I wrote that out. I wasn't sure if the second process, requesting access to QA Dashboard Product List, was a complex process like the last one or if that was literally "click a button." I wish there was a way to find out complex or not complex that process is.

**Comment by laucon** [comment]
So I did task number 6 and some of task number 5. I haven't gotten to task number 7 because 6 was so big.

**Comment by amygoldman** [comment]
General note: Lots of writing in the passive tense. Should we correct this?

**Comment by amygoldman** [comment]
General note: Lots of instances of using the `code` formatting that seem unnecessary?

**Comment by amygoldman** [comment]
General note: edit/crop Lauren's screenshots

**Comment by amygoldman** [comment]
Update: Addressed all of Gretchen's recommendations. See notes ^ and [notes on doc](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2151317518/QA+Dashboard+guide+-or-+QA+practice+health+dashboard+guide) for remaining issues. 

General note: The entire doc could probably use a plain language pass, especially the cards.

**Comment by amygoldman** [comment]
**Next steps:**
- Lauren will do her thing with the steps and links  
- Amy will:
  - Rework this text and add to the intro https://va-gov.domo.com/page/1950369682?userId=1546595816  
  - Create a doc with all SME questions + outline of the edits we've made so far 
  - Make next round revisions on what we can move forward on
- Next week: Message SME(s) to ask if they'd prefer to schedule a sync or discuss any next steps asynchronously

**Comment by lianilychee** [comment]
Mon 4/11:
- today
  - Amy - will compile and send out SME questions today
  - Lauren - tbd

**Comment by amygoldman** [comment]
Update: here are the [SME questions and the to-do list ](https://vfs.atlassian.net/wiki/spaces/~832277940/pages/2155938014/QA+Dashboard+doc+tasks)

**Comment by amygoldman** [comment]
Update 4/12:

- asked Peter & Joe to answer the SME q's
- Lauren is working on resizing and captioning screenshots and adding alt text
- Amy is working on other items on the to-do list

**Comment by lianilychee** [comment]
4/13 Weds - want to publish by next Tues, but totally dependent on SME response time

**Comment by lianilychee** [comment]
4/14 Thurs - waiting on Peter and Joe feedback; first reached out couple of days ago

**Comment by lianilychee** [comment]
4/15 Fri 
- today: Amy Lauren FUP with Joe

**Comment by lianilychee** [comment]
4/18 Mon:
- lauren has one outstanding question for holden
- amy FUP with Joe

**Comment by amygoldman** [comment]
Most recent [update from Joe](https://dsva.slack.com/archives/C02UW9Z7M1R/p1650298334479659)
- Peter is occupied elsewhere with re-compete efforts, if we can please wait on this until Wednesday - we can definitely get you answers then
- regarding the switch to main (from master), I'd heard that there was a planned change to this already proposed, though I'm not sure who was leading it or where it stands

**Comment by lianilychee** [comment]
4/21 thurs:
- peter will give us feedback sometime tmr (Fri)

**Comment by lianilychee** [comment]
4/25 Mon:
- Lauren going to edit a few things
- Amy/Lauren copy the drafts page to the live page (Lauren set up time with Amy)

**Comment by lianilychee** [comment]
4/26 Tues:
- all big edits, just need to run against linter
- will copy to live site today!
