### ISSUE TITLE
Access for Allison Christman

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#39571]
Allison Christman
allison.christman@oddball.io
UX Designer
Governance team
Oddball

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzgdsbHddwIn5k42JBI7EDTjqUqJsOB9eHsi7C7ZnNix2Q4EMBpkK2Xgb0nRMt4mVzz2/DQReGYuOMheoNiaZllagb5KqVPYsrMO5WUOmdOHT07uOlg7rRAfa2IbD3IMAA497uN32qoG5iujWkexW1YEQ9GT6tLptSV6iPJoIg0o+AC9NYjOu8O4aLAdvOo4XlB+n/SDFM5TvwbDtEKlrGWEiCXo1bv2ZogNuvHecilicoGm2I/YY4si+BHw/m1jtaRai+Nmu+R74Iq51wmjWt/y/IQZf4t0KrK3hpAd4k5+qmeKCMNSXSbeDtR5yWFrvK0s4YUSOT0auIXzxcCZxJBTG+Mq6ZB8105FM01ZNn9D94K2DFcSlpJnSvKjPWM4h1mCigsrgTbQgN+Fl7slGWd9/fy8JD/8QNlXr3Ela8DgbmKQTsNzFVdYtR1IGWxV7I0o9hIwUtwlzjqyoqqhPuz+2BQGhcz4rp6Bh3pijIyuHM3MQNYz7yB/6AdqovJ/E= allisonchristman@Allisons-MacBook-Pro.local

**Comment by rmtolmach** [comment]
@allison0034 How did you go about creating this Issue? I ask because I _thought_ i updated all of the docs last week with the right link, but I'm wondering if I forgot to update a doc somewhere. 

Here is a link to the new template for requesting SOCKS access: https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D

I went ahead and created you one: https://github.com/department-of-veterans-affairs/va.gov-team/issues/39573, so I'm going to close this Issue. (The GitHub Action we use to process this request relies on the ssh key and email being located in the template.)
