### ISSUE TITLE
Add a direct link to the CDC’s COVID-19 symptom checker page on the coronavirus FAQs and COVID-19 vaccine pages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#39790]

**Comment by RLHecht** [comment]
@DanielleThierryUSDSVA Is this the link we're using for the symptom checker? https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/coronavirus-self-checker.html

If so, one of our team can add it to the pages and you can review before we publish. Do you already know where on the pages it should go or should we look at what makes the most sense?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht. Let's use this link (https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html#self-checker) instead, since this is a more customer-friendly presentation of this.

**Comment by RLHecht** [comment]
@aliyahblackmore The FAQs page to work on is https://www.va.gov/coronavirus-veteran-frequently-asked-questions/. 

We don't need to add it to the vaccine pages anymore.

**Comment by aliyahblackmore** [comment]
Hi @laurawillwerth ! I went ahead and [created a doc ](https://docs.google.com/document/d/1ONWTdVZQ9ud5e8DyebBumqqFlDq5Fvd6kb2gEwF1TOA/edit)with a suggestion of how the language above the link and link placement could change here.  Passing this off to you to review and then the suggestion can be pasted in Github (to be shared with Danielle)! cc: @RLHecht

**Comment by DanielleThierryUSDSVA** [comment]
Hi all! @RLHecht You mentioned that there was a question for me in this issue. I think it's the question about this already existing on the page. That's great and looks like the suggested content is in progress (thank you, @aliyahblackmore!).

FYSA, there is an evolving separate covid issue going on that's causing us to need to make a bunch more revisions to the FAQs page. I'm in there working on that since it's urgent, but will be passing along for a copy edit. We can work this content update into that same batch of changes and send all changes to translators together. Let me know if you want to sync on this!

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , just noting that Aliyah's suggestion was to move the CDC symptom checker link directly under the "call 911 now" list of severe symptoms. And from the draft Drupal updates, it looks like that's exactly where this link appears in the "What should I do while I'm waiting for results?" accordion! So the only potential change to consider here would be to move the CDC link to the same position in the "What should I do if I have symptoms?" accordion farther down the page. 

Let us know if you'd like us to do anything else here! Otherwise I think we can close this ticket and wait for your updates to copyedit in the [larger FAQ reworking task](https://github.com/department-of-veterans-affairs/va.gov-team/issues/40829).
