### ISSUE TITLE
Profile: Sprint 72 (Apr 20 - May 3)

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#39933]
## PTO/OOO/Unavailable

- **Christina**: 4/20
- **Sharon**:  Fingerprinting Appt 5/3 (out from 1pm - 4pm-ish)
- **Tom**:  PIV Appt 4/29 @ 2pm (probably be out 12:45 - 3:45)
- **Mark**: 
- **Adam**:
- **Liz**: 1.5 days out this sprint (most of 4/21 **or** 4/22, and on 4/27)

# Sprint Priorities

1. **Personal information Revision - Be ready for QA by sprint 73 (starts 5/4). Complete front-end work and all QA-related tasks.**
2. Bad Address Indicator, Notification preferences, and Direct Deposit work

### PM - Sharon
- [x] #34001 
- [x] #39373 
- [x] #34466 
- [x] #34008 
- [x] #40249 (QA ticket)

### Design - Christina
- [x] #38961 (hold off on submitting until we have updates for direct deposit from Liz)
- [x] #39318
- [x] #39866 

### FE - Adam
- [x] #38953 
- [x] #38952 
- [x] #38950 
- [x] #38637

### BE - Tom

- [x] #38788

 ## 📩 Bad address indicator

### BE - Tom
- [x] #38583 

### PM - Sharon
- [x] #39381 

### Design - Christina
- [x] #39883 (Final adjustments based on DT's feedback)

### FE - Mark
- [x] #40173

### Design and Research - Liz

Display Direct Deposit consistently 

- [x] #40216
- [x] #40191
- [x] #40196
- [x] #40198 
- [x] #40244
- [x] #40253

### FE - Mark
- [x] #39775

### BE - Tom 
- [x] #39776
- [x] #40479 (added 4/26)

**Comment by SKasimow** [comment]
Hi @Samara-Strauss - here's an update for the Sprint 72 epic; lmk if it needs any adjustments. Planning to create tickets for the "placeholder" spots tomorrow.

**Comment by Samara-Strauss** [comment]
Thank you for this! This is looking great. Just a few things:

- You can remove the Bad Address tasks for you since they are not part of this sprint. I know you labeled them "if time", but let's just assume there won't be and take them out. If we can pull them in later on, great, but let's just take them out for now.
- You can also take out the documentation task for Christina for address change messaging for this sprint. This isn't required for the sprint, but we can pull it in if there is time.
- For the MHV research, please add a task for Liz to share out this work with OCTO and a separate one to share with MHV stakeholders.
- Given that Liz will need to make some updates to the call center guide for the direct deposit updates, we should hold off on submitting the call center guide for review as part of the personal information work. Once she has made the updates related to the direct deposit changes, we can submit the guide and note that these updates -- personal info and direct deposit -- will be released in June.
- You can also take out the ticket for Mark to do diagramming work for now. Again, we can pull it in if there is time, but it's not required for this sprint. I'd rather he focus on familiarizing with notification preferences, and I'm going to ask him to pitch in on a My VA task as well.

**Comment by SKasimow** [comment]
Thanks for your feedback @Samara-Strauss - that was really helpful!

Here's what I changed:
- Removed Bad Address work for PM and Design (started a ticket for Sprint 73 and moved these over)
- Moved Christina's task for the FE doc re: Address Change to Sprint 73
- Added 2 placeholder tickets to Sprint 72 for MHV research meetings with OCTO and MHV stakeholders 
- Added note to here and in #38961 to hold off on submitting to CC until we have direct deposit updates.
- Moved diagram ticket for Mark to Sprint 73 as a placeholder

**Comment by Samara-Strauss** [comment]
Great, thank you!
