### ISSUE TITLE
Withdrawn Schools Testing

### ISSUE THREAD

**Issue by mrblanco1** [department-of-veterans-affairs/va.gov-team#39961]
## Issue Description
Brian G. reported yesteday 4/12/2022 withdrawn schools were displaying in production when they were not supposed to. He also noticed that in staging they were not displaying (expected).

---
## Tasks
Conduct testing in both Staging and Production environments and validate whether withdrawn schools are displaying in CT or not.

The expected behavior is that withdrawn schools do NOT display in either environment.

## Acceptance Criteria
Validate withdrawn schools are NOT displaying in either staging or prod.
---
## Steps
1. From the shared via email Withdrawn Schools 04132022.xls (column CT), use any withdrawn schools in the Search
2. When conducting a search please use both facility code (column A) firs and then try (separate search) institution name (column B)
3. Do this in staging and then production for 10-15 institutions on each environment
4. Record your results
5. Share your results

Adam: Rows 2 -> 20
Nick: Rows 21 -> 40
Jake: Rows 41 -> 60

**Comment by jfinnern** [comment]
Unable to reproduce the issue of withdrawn schools being visible using rows 41-60.
Both staging and prod do not include the withdrawn institution in search results for a search by name and display a "We've run into a problem." error message when attempting to navigate to the institution page URL using the facility code.

**Comment by AdamFreemer** [comment]
Same as @jfinnern. Perhaps this adds a bit of color. I ran through a few different Insitutions with varying complexities in their naming. When you search for something more simplistic, you are more likely to see result(s) with similar namings, even though they are not related. 

![Screen Shot 2022-04-13 at 1.24.48 PM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/70090c46-01ce-4682-92c3-bdd952b8db79)

![Screen Shot 2022-04-13 at 1.25.16 PM.png](https://images.zenhubusercontent.com/611a8f6c2ea95cb7b7c913b6/de82398c-51f3-46a9-a0e4-d726e7208d85)

I chose "Troy" and "Jones" from the withdrawn list which were good examples. When you enter the actual facility code, that Institution is no longer there. When searching by name, because they're so generic, you'll see other results.

**Comment by nbarthelemy** [comment]
I was unable to reproduce the issue of withdrawn schools being visible using rows 21-40. My results are inline with @jfinnern and @AdamFreemer. Both staging and prod do not include the withdrawn institution in search results for a search by name and display a "We've run into a problem." error message when attempting to navigate to the institution page URL using the facility code.
