### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-team#39977]
### Description
Broken link: https://dsva.slack.com/channels/vfs-product-support

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/developer-docs/Automated-code-quality.1845887276.html

**Comment by gmaciolek** [comment]
@timwright12 there's a broken link on the Automated code quality page, but I suspect the Slack channel names are also out of date. 

My suggestion on this one is to review/update the list of Slack channels and links and remove the `(last updated: 3-9-20 )` text from the subheading. One of our documentation principles in our style guide is that our documentation should be "timeless." Any user looking at our docs should be able to assume the information is up-to-date. Seeing the last updated date of 2 years ago will likely make the user concerned that the information is out-of-date, rather than reassure them that it's being actively maintained. See the "[creating timeless documentation](https://vfs.atlassian.net/wiki/spaces/AP/pages/2017001494/Content+principles#Create-timeless-documentation)" section of the style guide for more details.

**Comment by gmaciolek** [comment]
CC: @amygoldman

**Comment by timwright12** [comment]
@gmaciolek @amygoldman Those slack #vfs-product-support references and links should be updated to use #vfs-platform-support 

Going to pass this over to @rmessina1010 since he's leading that team now

**Comment by lianilychee** [comment]
@rmessina1010 awesome thanks!  I reckon the change has already gone out in the twice-weekly deploy.  Gonna close the ticket now 👍
