### ISSUE TITLE
"Invalid date" Time Display on Facility Locator Hours

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-team#4000]
## What happened?
" Invalid date" is being shown as a time.  Not sure if this is a problem with the data or with the front-end. 
Not sure how many facilities this may be affecting.

## Specs:
- Device: Win10
- Browser: Chrome
- Test User _(if applicable)_: N/A

## Steps to Reproduce
- URL: https://www.va.gov/find-locations/facility/nca_901
- Test User _(if applicable)_: n/A

![image.png](https://images.zenhubusercontent.com/5d93a452c8e4d80001227a6c/cdf3a885-6163-432d-bbac-9746250917a9)

## Desired behavior
Actual Hours or String needs to be shown.
Hours supplied by API are displayed. 
If operating hours are not supplied by API, the info box will not be displayed. 

## Acceptance Criteria
[ ] Given the facility has available hours of operation in the data source and user has input a city, state and/or zip code and VA facility type = VA cemeteries; when user clicks on name of cemetery in search results, then valid facility hours should be displayed on the facility detail page. 
[ ] Valid facility hours will be displayed by day of the week and may be expressed as "Sunrise - Sunset", clock time such as "8:00 a.m. - 4:30 p.m." or combination, such as "8:00 a.m. - Sunset"
[ ] If the hours of operation are not included in data source, the entire block will be hidden. 

## Steps to test

1. Go to Facility Locator. 
2. Search California plus VA Cemetery as the Facility type
3. Zoom out on the map until results include at least 4 cemeteries 
4. Select Riverside National Cemetery from search results
5. View facility detail page
6. Observe the hours of operation are valid and displayed as expected. 
7. Return to results page
8. Select Bakersfield National Cemetery from search results
9. View facility detail page
10. Observe the hours of operation are valid and displayed as expected. 
11. Return to results page
12. Select Los Angeles National Cemetery from search results
13. View facility detail page
14. Observe the hours of operation are valid and displayed as expected.

**Comment by mmiddaugh** [comment]
I have done some additional testing and found other locations with this same issue, @davidconlon. Turns out if the data sent is a mix of opening time expressed as a number (8:00 a.m, for example) + "sunset", it displays "Invalid" for the closing time. 
- Alexandria National Cemetery in Pineville, LA
- Beaufort National Cemetery in Beaufort, SC
- Corinth National Cemetery in Cornith, MS
- Memphis National Cemetery in Memphis, TN
- Natchez National Cemetery in Natchez, MS
- Riverside National Cemetery in Riverside, CA

**Comment by mmiddaugh** [comment]
I have done some additional testing and found other locations with this same issue, @davidconlon. Turns out if the data sent is a mix of opening time expressed as a number (8:00 a.m, for example) + "sunset", it displays "Invalid" for the closing time.
Alexandria National Cemetery in Pineville, LA
Beaufort National Cemetery in Beaufort, SC
Beverly National Cemetery in Beverly, NJ
Camp Butler National Cemetery in Springfield IL
Corinth National Cemetery in Cornith, MS
Finn's Point National Cemetery in Salem, NJ
Fort Gibson National Cemetery in Fort Gibson, OK
Fort Smith National Cemetery in Fort Smith, AK
Memphis National Cemetery in Memphis, TN
Natchez National Cemetery in Natchez, MS
Philadelphia National Cemetery in Philadelphia, PA
Riverside National Cemetery in Riverside, CA

**Comment by davidconlon** [comment]
@mmiddaugh this is likely the last item to take care of in order to have Cemeteries start using FL as opposed to the legacy item.

**Comment by mmiddaugh** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/3541
This issue describes a very small change (the addition of a space) that needs to be made in the hours displayed. It may be reasonable to address these together.
