### ISSUE TITLE
Error on 1010EZ: Marriage Date and Spouse DOB

### ISSUE THREAD

**Issue by lalexanderson-dsva** [department-of-veterans-affairs/va.gov-team#40039]
## What happened?
_Veterans are complaining that they receive an error when they are filling out the online 10-10EZ application form. When filling in spouses DOB and marriage date it kicks back the date saying it is invalid. The error code that comes up reads that the marriage date is before the date of birth. The above error is being thrown at this block of ```vets-website``` [code here](https://github.com/department-of-veterans-affairs/vets-website/blob/ae3d33359eeea88929348a268b7921bf80b81bb2/src/applications/hca/validation.js#L55-L73). 

We are hearing of approx 100 reports of this issue. 

### Timeline - 
It should be noted that on [March 21, 2022](https://github.com/department-of-veterans-affairs/vets-api/commit/c92e699f5cda7ffd44cda2052e92e7a1ea45597e) - ```vets-api``` was updated to allow 1010 EZ Short Form submissions (not yet live on frontend).

It appears that [the PR here](https://github.com/department-of-veterans-affairs/vets-api/pull/9503), merged on April 4, 2022 - made in good faith - was to make vets-api add back validation for a few fields marked as required on the 1010 EZ on production.

### Potential Areas to Dig Deeper - 
1. In the [change to the validation API](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/health_care_application.rb#L23), the method used is ```validate``` and not ```validates``` (plural) as is used elsewhere. The two methods appear at a glance to have different signatures/responsibilities.
2. The business logic for date validation [here](https://github.com/department-of-veterans-affairs/vets-website/blob/ae3d33359eeea88929348a268b7921bf80b81bb2/src/applications/hca/validation.js#L65) is a little confusing, but it could suggest that the error thrown is not the error caught as it includes non-date validation

### Next Steps - 
1. Determine course of action to mitigate issue with Form Submission
2. Post Mortem + Next Steps Determined w/ Contract Team.
3. Increase ```vets-api``` test coverage to better match form logic (i.e. Marriage date having to be after birth date, Birth date being before death date, etc...)
_

## Specs:
- Device: All
- Browser: All 
- Test User _(if applicable)_: Unknown

## Steps to Reproduce
- URL: 
- Test User _(if applicable)_:

## Desired behavior
_A Veteran should be able to enter a marriage date that is correctly and chronologically after the spouse's birth date and not receive an error._

## Acceptance Criteria
- [ ] _An error is not thrown when a Veteran enters a marriage date that is chronologically after the spouse's birth date._

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by hdjustice** [comment]
Walkthrough with a Veteran who has experienced this issue is scheduled for Thursday, 4/21 at 10am ET

**Comment by hdjustice** [comment]
Notes and screenshot of page loading errors from today's session with a Veteran walking through his experience while completing the 10-10EZ application.

### Apr 21, 2022 VA Health Care Application walk-through with development team

#### Notes:
- User confirmed that we could record the session, and destroy once analysis is complete.  
     - Recording will be accessed by Lisa Zapson only, due to PII
- User was logged in when the error occurred
- User is already logged in in preparation for this session
- User selected to “continue with the application”
- User shares the Review screen
- No errors are showing on the screen
- User selects Edit on Household, then selects Update (no changes were made to the data).  This is when he receives error message
- The Error message is indicating that the Veteran’s DOB cannot be before the Marriage date 
     - FYI - error message verbiage was updated recently to determine if it is the Veteran’s DOB, Spouse’s DOB or both
- Lisa directs User back to the first page to verify his date of birth, which should be pre-filed since he is logged in.
- As the User selects the Back button and nears the first page, the page does not load correctly
- Lisa directs the User to right-click, select “Inspect” and then select “Console”, so that we may view the errors on the page (behind the scenes)
- Many errors are appearing there
- User agrees to participate in further sessions, if needed. We can contact him via his email address that we have.
- The session is ended

#### Post-interview debrief

- Some Error logs are showing preceding zero being added to DOB year
- Some Error logs are showing DOB being today’s date.
- Lisa wants to start troubleshooting the Update button and the discrepancies with the DOB issues seen in the logs
- Mark Dewey & Lisa will meet this afternoon to discuss findings further

![image.png](https://images.zenhubusercontent.com/6172ff6d924e737b978a12ea/329a2392-c637-4990-86f8-4b4fe3519657)

**Comment by hdjustice** [comment]
Closed ticket as we have created additional tickets to address the issue of date validation between Marriage and Birth dates, as well as when the data is showing as 'null', causing further validation errors.
