### ISSUE TITLE
QA Feedback - Staging Review - Design System Team - Date web component

### ISSUE THREAD

**Issue by ddzz** [department-of-veterans-affairs/va.gov-team#40575]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

Feedback for https://github.com/department-of-veterans-affairs/va.gov-team/issues/40287

**Comments:**
- None

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
None

**Should:**
- The year input field should only accept up to four characters and only digits. Right now there is no limit on the length of the year, and the following non-numeric characters can be entered: `.`, `+`, `-`, `e`. This can cause issues with validation.

- Scrolling to select the year should be disabled to avoid unexpected changes to the value:

https://user-images.githubusercontent.com/3535749/165642095-f2bcf20e-12b4-4d9b-a575-b2082cc54311.mov

**Consider:**
None

**Comment by pdavies88** [comment]
Tasks:
- [ ] Merge in `va-date` as a minor version in its current state
- [ ] Use this ticket to make updates and switch from `va-number-input` over to `va-text-input` for `va-date`
- [ ] Add 2 additional props for `va-text-input` - `minlength` and `pattern` so that we can replicate what is being done by [uswds](https://designsystem.digital.gov/components/date-input/)
- [ ] Add tests and storybook examples for `va-text-input` to accommodate the new props
- [ ] For `va-text-input` switch `handleChange` to `handleInput` and use `onBlur` and `onInput` per [PR](https://github.com/department-of-veterans-affairs/component-library/pull/363/files) 
- [ ] Once updates are made for both `va-text-input` and `va-date` a new patch version should be created
