### ISSUE TITLE
"Description" field on pdf-generated version of the sub-form used to provide information about traumatic incident cuts off the actual description.

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#40605]
In order to process a claim, a case processor must receive the veteran's disability claims information on a pdf form generated using the information collected from the online 526 form (and sub forms). The field associated with the veteran's description of a traumatic event associated with PTSD is "printing" with cut-off text; therefore, the claims processor cannot actually read the description. This has necessitated a painful workaround by which claims processors are reaching out to veterans and asking them to describe the event again. 

We need to determine options for technical solutions that will either A) ensure that the text pulled into this pdf form fits within the field (but we cannot rely on character constraints) or B) utilizes the notes field found in a different location of the PDF. It has been noted that solution B has not been preferred in similar cases, but given the nature of this sensitive data and the urgency to correct this issue, B is on the table as a possible solutions. 

Acceptance Criteria: 
- Claims processors no longer receive a PDF with "cut-off" text in the description field
- The full length of the text is fully visible in either the designated description field or the applicable notes section.

**Comment by Mottie** [comment]
I believe the Form 781 schema value of the description is PTSD `incidents` [`incidentDescription`](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-526EZ-ALLCLAIMS-schema.json#L1247-L1249) or maybe the [`personsInvolved` description](https://github.com/department-of-veterans-affairs/vets-json-schema/blob/master/dist/21-526EZ-ALLCLAIMS-schema.json#L1297-L1299). Neither has a size limitation for the description on the front-end.

This issue is likely with the backend generating the 781/781a PDF and then attaching it to the 526 submission. If there is overflow, it should be including that on an additional page in the PDF. I'll discuss this further with @michelpmcdonald.

**Comment by michelpmcdonald** [comment]
Also the form itself says to just attach extra pages for overflow as needed...unsure why B is not preferred when that's exactly what the official va provided form instructs vets to do

![image](https://user-images.githubusercontent.com/865014/165854645-b6687c6c-605a-450b-a91a-c06d88276fd6.png)

**Comment by michelpmcdonald** [comment]
Do we have an example of a cut-off PDF ?

**Comment by saderagsdale** [comment]
@jacobworrell Michel is taking this on right with your squad, rite?

**Comment by jacobworrell** [comment]
@saderagsdale yes, Michel has been working on this.

**Comment by michelpmcdonald** [comment]
Turns out this is not a "bug" with the overflow code, it's more of a configuration issue.

PDF fill fields have to be configured with a max length setting, and a data that is longer than the set limit triggers the overflow onto a page added on to the end of the generated 20-0781 pdf form.

I'm unsure why this field was never set as an overflow-able field.  Seem like it would have been especially considering it's a free form field that allows the vet to describe the PTSD incident in detail.

**Comment by michelpmcdonald** [comment]
@jacobworrell - have a fix, so can the agents who pointed out this issue be notified one the fix is merged ?

**Comment by michelpmcdonald** [comment]
Merged
