### ISSUE TITLE
Trigger PagerDuty Step Not Followed

### ISSUE THREAD

**Issue by raywangoctova** [department-of-veterans-affairs/va.gov-team#40648]
## Who is the devops resource on your team?

@little-oddball 

## Description
There were two events that required OOB deployments. In both cases, the PagerDuty was not initiated. Mike insisted on the second one to be triggered for correct approval. Is there something we need to communicate or reinforce so the support team can help with the PagerDuty trigger? It is preferred since we OCTO approver might not be checking Slack 24/7. 

## Background/context 
Trigger PagerDuty using /pd trigger and select “Out-of-band Deployment (service). Leave “Assign to” blank and put a link to the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) Slack thread in the description.
The above step was not followed. The documentation of the steps is linked below.
https://depo-platform-documentation.scrollhelp.site/support/Deployment-Policies.1279787009.html#DeploymentPolicies-Ismyissuecritical

---
## Tasks
Support team to ensure the step is followed for PagerDuty.

## Acceptance Criteria 
Future OOB deployment triggers PagerDuty for OCTO approver.

**Comment by zachclarity** [comment]
I am working with my team to see what was missed.  Thanks

**Comment by powellkerry** [comment]
These were my first OOB deployment requests. The first was done with supervision from Tim Wright and the second I relied on Chris Alexander. For both of these it was communicated that approval from OCTO-DE was normally obtained by tagging them in the slack thread (at least during normal business hours). I understand that OOB deploys are rare, so it is understandable that steps from memory can get forgotten or may not match current policy and documentation. I have updated the documentation with the help of Mike Chelen so it can be followed more closely next time. 
 
The previous version of the documentation for OOB deploys makes it sound like the team submitting the support ticket is responsible for triggering PagerDuty. It wasn't till Mike Chelen clarified that to me that I understood I was responsible for that step. The first OOB deploy as stated in the description did not have a PagerDuty trigger.

The version of the documentation used yesterday can be found here: https://depo-platform-documentation.scrollhelp.site/support/Deployment-Policies.1279787009.html#DeploymentPolicies-Step-by-stepprocessforout-of-banddeploymentapproval

I have updated the documentation and it will be published to the above site on Tuesday: https://vfs.atlassian.net/wiki/spaces/SUP/pages/1279787009/Deployment+Policies

Ultimately this came down to me being inexperienced in the process, but hopefully updating the docs will prevent this in the future. It also may be worth developing an integration with PagerDuty from the slackbot so that whoever is on support does not need to worry about manually triggering PagerDuty for OOB deploy requests.
