### ISSUE TITLE
Design Feedback - Design Intent - Auth Exp My VA, Benefit Payments and Debt Version 2

### ISSUE THREAD

**Issue by seanasewell** [department-of-veterans-affairs/va.gov-team#40757]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions

Great job so far!

- Test around linked titles
- Test around the “And 1 more outstanding bill”. Users might expect it to be linked.
- Make sure you use the correct heading tags for hierarchy 

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

- [Active links](https://design.va.gov/components/action-link#active-links) should have a >

**Should:**

**Consider:**

**Comment by ajakabcin** [comment]
#40774 captures the work to implement the must feedback here for active links to have >

**Comment by aagosto90** [comment]
We are not making this update because we decided to move forward with a design where the titles of the bills and payments are not individual links. Here are the updated designs for [desktop](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/ELmbGe2) and [mobile](https://www.sketch.com/s/9b0e6efc-423a-4354-9db3-ab2083d566c9/a/jg20r4z).
