### ISSUE TITLE
Collaboration Cycle Kickoff for the Debt Resolution Team, adding medical copays to the Financial Status Report (VA Form 5655)

### ISSUE THREAD

**Issue by rileyorr** [department-of-veterans-affairs/va.gov-team#40813]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [x] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/combined_fsr/product_outline.md)
- ["List loop" redesign flow (Mural)](https://app.mural.co/invitation/mural/vsa8243/1651159117540?sender=riley5075&key=ad860a2e-fabf-4e2c-8c7c-cd736b8ed467)
- [UXPin prototype (in progress)](https://preview.uxpin.com/552e9ad135f7d7ee943a92576feab45190b069f4#/pages//comment/no-panels?mode=i)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [X] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [X] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: Financial Status Report (VA Form 5655)

The online Financial Status Report (FSR) currently allows Veterans to request financial help for benefit debts incurred with the Debt Management Center. This initiative will expand the FSR's capabilities to allow Veterans to request financial help for VA medical copay bills. Additionally, we're incorporating feedback from [the MVP usability study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/Financial-Status-Report/research/mar-2021/readout.md) to redesign the list loop components. The goal is to simplify the experience and make it more accessible, as the existing list loop components were unintuitive to participants and the component is not navigable for folks who use assistive technology. 

One thing I'm eager to receive guidance on is the suggested path forward for the wizard pattern. When we launched the FSR's MVP, the wizard still used progressive disclosure. Since then, I've heard that we're moving away from progressive disclosure to a more accessible one-question-per-page format. 

### 4. Are you making changes to the visual design?
- [X] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [X] Yes
- [ ] No

### 6. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [ ] Static pages
- [X] Both

*For tools and applications, take into account if any static page entry points will need updates.<br/>
**For information and examples of Static vs Dynamic pages, review the [Static vs Dynamic guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md).

### 7. Will your work include:  

- [ ] New content
- [X] Changes to existing content

### 8. Are you making a change to the user flow?
- [X] Yes
- [ ] No

### 9. Are you making a change to urls, navigation, or entry points?
- [X] Yes
- [ ] No

We will potentially make changes depending on IA's feedback. We'll be working closely with Mikki on this initiative! 

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [X] Yes
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [X] Yes
- [ ] No

### 12. Is there a GitHub label in the va.gov-team repo for this product?

- [ ] No. 
- [X] Yes. Please specify: FSR

### 13. Who is the VA business owner for this body of work?

- [X] VHA (Veterans Health Administration)
- [X] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [ ] VACO (Veterans Affairs Central Office)
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Hi @rileyorr. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a tool and/or application so we are recommending the following Collaboration Cycle touchpoints: (select all that apply)

- Design Intent
- Sitewide Content and IA intake request
- Research Review
- Analytics request
- Midpoint Review
- Contact Center Review
- Staging Review] 
- Privacy, Security, Infrastructure Readiness Review

We recommend that you bring the tool/application and static pages through the Collaboration Cycle together so we can review the full flow/user experience.

Please reach out to Dave Conlon to let him know your work will impact static pages, the nature of the work, and your projected timeline.

The following practice areas will be included throughout the Collaboration Cycle process: 

- Design
- Content
- Information Architecture (IA)
- Quality Assurance (QA)
- Accessibility
- Product
- Research

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886) When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.
