### ISSUE TITLE
IA & Content recommendations from Benefits Team 1

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#41055]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [x] IA support
  
Form 686c-674 is already in production. There is a collaboration cycle ticket for the related "Dependency Verification" modal that describes an issue with this form. Form 686c-674's [document title is currently "686C-674 | Veterans Affairs"](https://github.com/department-of-veterans-affairs/va.gov-team/issues/30014). This doesn't match the [SEO recommendation for page titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles#page-titles).

We need help with the actual page title, which should match the H1 content and the breadcrumbs.

<img width="609" alt="Form 686 introduction page on staging showing different text in document title, breadcrumbs and H1" src="https://user-images.githubusercontent.com/136959/167203780-27bc76ad-9645-49dd-892d-622ac423635b.png">

Document (browser tab) title: 686C-674 | Veterans Affairs
Breadcrumb: Add or remove dependents form 21-686c
H1: Add or remove a dependent on your VA disability benefits

Given the three choices, the title and breadcrumb aren't optimal since they include the form number. And the H1 content would be too long (75 characters) if used as the document title (SEO recommends a max of 52 characters).

Please provide recommendations.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/30014 & https://github.com/department-of-veterans-affairs/va.gov-team/issues/21426

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: No defined deadline

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits team 1
-	OCTO-DE product owner: Matt Self
-	Product manager: @jacobworrell & @saderagsdale 
-	Designer: @thehastingsp & Skyler Schain
-	FE engineer: @Mottie, @jerekshoe & @scottymeyers
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#va-sitewide-content-ia](https://dsva.slack.com/channels/va-sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mnorthuis** [comment]
Hello @Mottie!   I talked with @bethpottsVADEPO and @DanielleThierryUSDSVA about this one because I noticed that the titles in place across this group of pages was inconsistent, and I wanted to review our current standards and documentation against this question and make sure everything shored up - the title tags, breadcrumbs, URLs, and H1s are very intricately related.  Below is our recommendation for this page, as well as some recommendations for the 2 related pages (static landing page and view dependents tool) for your team and the content team to take on when possible in order to bring this set of pages back to standard.


**Recommendations for: [Add or Remove Dependents Form 686](www.va.gov/view-change-dependents/add-remove-form-21-686c/introduction)**
- The title tag should match the H1 of the page.  In reviewing the H1 of this page, we recommend updating the page H1 to better follow standards, and then using that new H1 in the breadcrumb and the title tag.  
- Current state
  - H1: Add or remove a dependent on your VA disability benefits
  - Breadcrumb segment: Add or remove dependents form 21‑686c
  - Title tag: 686c-674 | Veterans Affairs
- New 
  - H1: Add or remove dependents with VA Form 21-686C
  - Breadcrumb segment: Add or remove dependents with VA Form 21-686C
  - Title tag: Add Or Remove Dependents With VA Form 21-686C | Veterans Affairs
- In addition, when  you are on this form, the breadcrumb segment for it's parent page is incorrect and should be fixed
  - The final full breadcrumb when on this page should be:  Home > View or change dependents on your VA disability benefits > Add or remove dependents with VA Form 21-686C
- No URL changes at this time
- Will implementing the new breadcrumb component help keep the segments updated with any H1 changes?  

**Recommendations for: [Your VA dependents page](www.va.gov/view-change-dependents/view)**
- The H1 should not be title casing, "dependents" should be lower case - Your VA dependents
- The breadcrumb segment should match the H1 with the same casing structure - Your VA dependents
- The title tag should match the H1 but with title casing - Your VA Dependents | Veterans Affairs
- When on this tool, the breadcrumb segment for the parent page is incorrect and should be fixed
  - The final full breadcrumb when on this page should be:  Home > View or change dependents on your VA disability benefits > Your VA dependents
- No URL changes at this time
- Same question as above, will implementing the new breadcrumb component help keep the segments updated with any H1 changes? 

**Recommendations for: [View or change dependents static landing page](www.va.gov/view-change-dependents)**
- @RLHecht these changes are for the content team to implement, can you please create a separate ticket for this work?  These changes can be done independently of the above work by the benefits team.
- The H1 of this page is good, but the breadcrumb and title tags need to be updated to match the H1
- H1 will stay as is:  View or change dependents on your VA disability benefits
- Current state
  - Breadcrumb segment: View or change your dependents
  - Title tag: View Or Change Dependents | Veterans Affairs
- New
  - Breadcrumb segment: View or change dependents on your VA disability benefits
  - Title tag: View Or Change Dependents On Your VA Disability Benefits | Veterans Affairs
- No URL changes at this time

**Comment by Mottie** [comment]
Thanks @mnorthuis!

**Comment by Mottie** [comment]
@mnorthuis 
> Will implementing the new breadcrumb component help keep the segments updated with any H1 changes?

Sadly, no. The new breadcrumb webcomponent is only a wrapper to display the breadcrumb links.  I can discuss this with the Design System Team since it needs to match the document title.

**Comment by Mottie** [comment]
@mnorthuis Should the "Or" in the title tag be capitalized? I'm asking because I'm trying to be efficient and use a function that converts a sentence-case string to title-case for the title tag, but the function specifically ignores small words, e.g. a, an, and, or, the, if, etc.
