### ISSUE TITLE
Analytics Implementation for [Bandicoots - Lighthouse Developer Portal]

### ISSUE THREAD

**Issue by ChineduNwagwu** [department-of-veterans-affairs/va.gov-team#41102]
# Google Analytics Implementation

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [X] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Bandicoot, for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]
    
    
- **Provide the link(s) for Google Analytics implementation**
  
    - https://lighthouse-dev.va.gov/
    - https://lighthouse-qa.va.gov/
    - https://lighthouse-sandbox.va.gov/
    
- **When is the launch date?**
    - End of May 2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - Feature engagement
           - Daily active users
           - Weekly active users
           - Number of logins
           - User Retention
           - Time in-app
           - Returning users
           - Feature usage
    - Duration of feature engagement
    - Workflows (i.e. A -> B -> C)
    - Where users are coming from
    - Bounce Rate
    - Where users bounce
    

> Please leave the following blank

## Acceptance criteria
- [X] All appropriate issue tagging is completed
- [ ] QA has been completed
- [X] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jennaouellet** [comment]
Hello! We have configured the Google Analytics property, which can be found under the main GA account as "[GA4] Lighthouse Developer Portal".
Once you've added the analytics code to the application, pageviews will automatically collect for all pages. Below are the corresponding code snippets to initialize GA.



Development:

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-J4CG115C58"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-J4CG115C58');
</script>
```


QA

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R872F6E1X4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-R872F6E1X4');
</script>
```

Sandbox

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VWBX09GPQ4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VWBX09GPQ4');
</script>
```


 
Since this is an internal application, our team can assist with providing the GA4 event structure and best practices but ultimately additional tagging would be implemented on your end.
Events for all interactions should match GA4 standards. Others can be any event with any parameters, but should try to follow verb_noun or noun_verb structure like filter_accounts. Suggestions: link_click, button_click, table_sort.
We recommend using a React package like react-ga4 to initialize GA and push events. Events can be pushed in components in the application or via CustomEvent listeners for component library analytics a la vets-website.
