### ISSUE TITLE
Opening accordions on form review page causing disappearing UI

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4114]
## What happened?
Opening accordions on form review page causing disappearing UI - basically the issue is that on the review page for 526 (this should also apply to all other forms) when some of the accordion headers are opened, the whole UI for the form disappears.

## Specs:
- Device: (e.g. iPhone 8, Macbook)
- Browser: (e.g. Firefox, IE 11)
- Test User _(if applicable)_:

## Steps to Reproduce
- URL:
- Test User _(if applicable)_:

## Desired behavior
_UI is supposed to remain on the review page of 526 (and all other forms)_

## Acceptance Criteria
- [ ] _Identified code causing the issue_
- [ ] _Resolved the issue_

**Comment by ndsprinkle** [comment]
The code causing this issue is the recently modified line 142 in the file ObjectField.jsx within the review directory. Specifically, this issue happens when calling `.trim()` on the `title` variable when `title` is null. I am going to identify why this line was modified and make adjustments so the reason for the change is still satisfied and the error no longer happens.
