### ISSUE TITLE
DE | Profile | Bad Address Indicator | Research Plan

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#41175]
Placeholder

**Comment by cgednalske** [comment]
@SKasimow and @Samara-Strauss -- Here is the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/contact-information/bad-address-indicator/research/research-plan.md) for review. I'll need to talk more with Mark and Adam when back next week to understand what is most feasible for them to do for testing (prod, CodePen, staging - see [comment in Slack](https://dsva.slack.com/archives/C909ZG2BB/p1653517608262249)), so for now I've included info for both. Depending on the conversation around this, I could see some of these questions extending partially into next Sprint.

**Comment by Samara-Strauss** [comment]
### Recruitment criteria: Primary criteria

- You have two bullet points for "All participants must be able to screenshare via Zoom." My guess is that this wasn't intentional, and that you can probably take out the second mention of this.

**A note on inclusion criteria**

I would make sure you know which of these is the most important to your research. As we've seen in the past, it can be hard for Perigean to recruit when there are a ton of requirements because while they have a large database, people aren't able to participate in more than one study every six months (right?). So, if every study we do -- and every study every team does -- has a ton of requirements, it can be really hard to recruit, and they may come back to us and ask us if we are sure we need every requirement.

We also need to consider that if we decide to recruit people who have the BAI in prod, recruiting for a lot of inclusion criteria would be especially challenging. Perigean can absolutely recruit from a list we give them, but they will not have any of the usual metrics they have on people, like race, gender, education level, use of assistive tech, etc. In this case, we'd be relying on people's self report and hope that it's accurate.

**Comment by SKasimow** [comment]
@cgednalske - looks good! No additional comments.

**Comment by cgednalske** [comment]
@Samara-Strauss Good catch on the screen share bullet points! Definitely just need one of those, so removed the second one.

I see what you mean for the recruitment criteria. Would still love to aim fairly high in the push for inclusivity, but I've reduced some of the numbers in Inclusion section of the Primary Criteria where it doesn't seem necessary to have numbers quite that high. Does that help?

I'd imagine we'll get more clarity shortly in our testing method discussion, but hopefully we won't need to recruit directly from the group of people who actually have their addresses flagged. 🤞 I agree that would definitely create additional hurdles!

**Comment by Samara-Strauss** [comment]
> I've reduced some of the numbers in Inclusion section of the Primary Criteria where it doesn't seem necessary to have numbers quite that high. Does that help?

I think any reduction helps. We'll see what Perigean says and go from there.

> 3 participants who identify as other than straight/heterosexual
> 2 participants who identify as transgender, non-binary, or another gender identity other than cis-gender

I would move this to secondary criteria to be sensitive to the fact that (1) we don't need to know this about participants the same way we did for the personal information work, which directly affected the LGBTQ+ community, and (2) this is really personal information for people to share, and some people within the community may not want to disclose. We should not require people disclose this unless it's absolutely necessary for our work.

**Comment by cgednalske** [comment]
Thanks @Samara-Strauss! I think that makes sense for this work 👍  Those changes have been made, so I will go ahead and close this out.
