### ISSUE TITLE
Bug: VA Notify Domo Dashboard Landing Page Inconsistencies

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/va.gov-team#41188]
# Analytics Feature Request/Bug Report

## What this form is for

Use this template to request an Analytics dashboard feature or report a dashboarding or Google Analytics/Google Tag Manager bug. This form is for enhancements to the existing KPI dashboards. If you have any analytics questions, please use the `/support` command on [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel in Slack, or attend one of our [office hours](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-5.AdditionalAnalyticsSupport).

Platform Analytics & Insights will use the information you provide to help improve our products and services.

## Instructions

Please fill out the following sections:

- [x] Ticket Description
- [x] Request/Report Description
- [x] Additional Comments

## Ticket Description

Who is this request for?

- What is your role, and which team/project is this work for? (optional for feature requests, required for bug reports)

  _this adds research context for any data or features being requested_

  - VA Notify, Melanie Jones - PM and Beverly Nelson - PO, VA Notify Domo Dashboard

- Is this a feature request or a bug?

  - [ ] Feature request
  - [x] Bug report

## Request/Report Description

Please describe the feature you are requesting or bug you are reporting. Please be as detailed as possible. 
[VA Notify Dashboard](https://va-gov.domo.com/page/2040841289?userId=81060956)
**(1) Section: Filter by Landing Page**

FSR Confirmation emails launched 5/8 and data showed up on 5/9, however the email still wasn't appearing in the filter by landing page campaign list as of 5/10 despite having referral data. Today, 5/11, it does show up and the data shown is labelled 5/9. I attended office hours and Chloe thought the data set may have been from 5/8. 

![image](https://user-images.githubusercontent.com/99204969/167856016-25247ec4-55bc-4c9d-b144-d2bf845b97b8.png)

- [x] Can you please look into this to confirm we're refreshing it on the same daily cadence as the rest of the data? (between 4-6am for the prior day)
- [x] Can you also confirm why the filter "not set" is an option if the source is vanotify? There should be campaigns specified in all UTM parameters coming from our notifications. If this is expected behavior can you explain what it represents?

**(2) Section: Landing Page Graphs**
1. Filter by debt notification, which has a single URL in the email that goes to https://va.gov/manage-va-debt/
2. See that data appears in all the landing page charts, not just **Manage VA Debt**.

![image](https://user-images.githubusercontent.com/99204969/167856391-bc70e18d-fbd6-4aa2-a829-cbccfcfbac88.png)

- [x] Display landing pages only (initial entry from the campaign) rather than pages that may have been clicked throughout a user's session.

**Product questions to think through if you're requesting new data features:**

- Who is your audience?
- Why do you need this data?
- What are you hoping to find?
- What is your hypothesis that you're hoping the data will support?
- What area of the VA are you hoping to assess?
- How frequently do you need this data?

## Additional Comments

_Add any comments or questions for the Platform Analytics & Insights team here (if applicable)._

N/A

> Please leave the following blank

## Acceptance Criteria

- [ ] Relabel the issue where appropriate
- [ ] Follow up with the requester where necessary

For features:

- [ ] Groomed & backlogged with notes

For bugs:

- [ ] Document issue & fixes
- [ ] Report findings with team & requester

## Definition of Done

- [ ] All AC completed

**Comment by mjones-oddball** [comment]
@bevnobev @megansiddle Submitted domo bug ticket here

**Comment by chloedotbrown** [comment]
Hi @mjones-oddball, @bevnobev, and @megansiddle! Thanks for your patience. Some answers to your questions and follow-ups from us below. Please feel free to drop by our office hours today or Thursday if you'd like to discuss further!

## Responses

### Filter by landing page:

 _**Confirm update schedule**_ - We've adjusted the landing page update schedule to ensure that the GA table for the previous day's data will always be loaded into BigQuery before this data is pulled. All 3 datasources on the dashboard are now set to run at **10:15am ET**. To make it easier to tell at a glance the most recent date in the data, I've also added date range sub-titles to your bar and line charts. Since we're displaying your data by day, the X-axis can be a little tough to read quickly.

_**Campaign = (not set)**_ - We looked into the data affected by this issue, and luckily, it's very small. Landing page data with source set to "VANotify" and campaign listed as "(not set)" only affects 26 pageviews and 23 unique users. This would be easy to exclude without impacting any of the overall trends in your data. But! as for why you're seeing this at all - because this is how the data was originally collected in GA, this indicates an issue with the UTM parameters. It's possible something was missed in the original campaign configuration, but we also noticed that for some of the pagepaths, there's a space or missing parameters in the UTM section of the url. These could be accidental user edits, and while they would still take the user to the landing page, they'd impact how the data was able to be recorded.

### **Landing page graphs:**

**_Confirm landing pages only_** -  Correct. This data source is configured to _only_ bring in data when 1) the source is VANotify, 2) the url matches the 3 selecting landing pages, and 3) the pageview is the first hit of the user's session.

**_Campaign and landing page mismatches_** - So if the above:point_up: doesn't explain the mismatches we're seeing, what does? Turns out, this use case is in tension with some of the campaign attribution settings of our GA property. If a user first visits VA.gov first through one campaign and then a second campaign, each session will be logged to their respective campaigns. However - if the second session comes through direct traffic (i.e. types in url, bookmarked in browser), the second session will still be attributed to the first campaign by GA. ([Article here, if that's useful!](https://www.optimizesmart.com/understanding-sessions-campaigns-timeout-settings-google-analytics/#1-what-is-google-analytics-campaign-attribution)) 

This hasn't come up in a lot of our work previously, but since your GA data is entirely campaign-based, it's clearly an issue! Unfortunately, because this has to do with how all traffic is attributed by GA across the entire property, we can't change those configuration settings or "clean" the data, since this is how it was originally collected. But we _can_ take steps to better match how we're filtering that data to your use case, given what we know about the attribution model.:point_down:

   
## Next steps

To address the campaign and landing page mismatches, we recommend 1) removing the section filter and 2) applying card level filters to each of the landing page cards, so that they only capture the campaigns that you'd expect to see for each. This will _not_ exclude sessions of users who land on these pages through direct traffic after doing so through a VANotify campaign - but it will limit them to the appropriate campaigns only.

### What we'll need from you

- Confirmation of which campaigns should be shown on each of the 3 landing pages shown.
- _Optional_ - We could also train folks on our team on how to adjust these filters so that you're able to add any new relevant campaigns yourself in the future. Otherwise, you'll need to contact Analytics to have them added if campaigns with different names are launched in the future. Let us know if a training is of interest!

**Comment by michelle-dooley** [comment]
Note:  this should address the other ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/41099

**Comment by chloedotbrown** [comment]
Morning @mjones-oddball - just wanted to follow up on this to see if you had any questions about the explanation above?

We'd love to finalize the landing page/campaign matches so we can close this ticket out for you. And if removing us as the middle-man for adding new campaigns helps make this a more useful, easy to maintain tool for your team, we'd be more than happy to train you all on how to make those changes yourselves. 

Feel free to join us for [office hours](https://dsva.slack.com/archives/C1Q4294JJ/p1652987751728739) this week too!

**Comment by mjones-oddball** [comment]
Hi @chloedotbrown Sorry for the delay. We're meeting internally to review your findings and see what other questions we have. We might join for office hours! Thanks for checking in :)

**Comment by mjones-oddball** [comment]
Hi @michelle-dooley I see you mentioned https://github.com/department-of-veterans-affairs/va.gov-team/issues/41099 on here, but I'm not seeing an updating on getting that landing page added. Is there an update on that?

@chloedotbrown We discussed and understand what you've sent. We are not going to change the referrals/landing page section at this time based on the options available.

So I saw that there was potential training for adding campaigns ourselves, which we don't need since we aren't going with that change. However, I was curious if it was possible for us to add our own landing page cards if training was available?

**Comment by chloedotbrown** [comment]
Hi @mjones-oddball - glad to hear the current version of campaign referrals / landing pages is working! If your configuration needs ever change in the future, please feel free to reach out.

Unfortunately, we won't be able to hand the task of creating new landing page cards over to your team. This process involves not just card creation, but also requires changes to the BigQuery view and edits to the Domo dashboard itself. For governance reasons, those are permissions we have to keep tighter reins on to make sure the data ecosystem is in good shape. 

If any of that changes in the future, we can reach out to your team. In the meantime - is there anything else you need or should we close this ticket out?

**Comment by mjones-oddball** [comment]
@chloedotbrown No problem, thanks for letting me know. We can close this as long as the landing page work is still happening on https://github.com/department-of-veterans-affairs/va.gov-team/issues/41099

**Comment by chloedotbrown** [comment]
Great! Yes, work is continuing on #41099 so I'll close this one out.
