### ISSUE TITLE
Create on boarding intake questionnaire

### ISSUE THREAD

**Issue by accbjt** [department-of-veterans-affairs/va.gov-team#413]
Experience with GitHub, Slack, Zenhub
Exp. With relevant technologies
Consider all steps and meetings that are part of the MVP

**Comment by accbjt** [comment]
Link to google forms. @hpjaj @emilywaggoner @smoonpeyes @1Copenut Please take a look at the google form and review and add to it. I tried to add what I can think of but there might be some things that I am missing.

https://docs.google.com/forms/d/1cgl-gjSli4yq4gwfAvzLXhi0HNTQef2VUoVwhUS8NSg/edit

**Comment by hpjaj** [comment]
@accbjt  This is looking great!  Here are some initial thoughts I had:

- Typo, Questionaire is Questionnaire
- Instead of "List the best times to schedule meetings.", perhaps ask for any times the team cannot meet?  In that sense, we'd have more options to work with when trying to align all of our calendars with theirs.
- In this question, "List each team member's full name, position, and email address.", perhaps we can request their GitHub handles, as well.
- In this question, "Which computer operating system(s) does your team use? (Check all that apply.)", perhaps we should scope that to just the engineers?  And perhaps designers (Layla?)?
- Perhaps instead of, or in addition to this question, "List the software your team uses to communicate remotely."; Have a question around letting them know our primary tools, and if they anticipate any blockers gaining access to them?  For example, Slack, GitHub, ZenHub, Zoom, design software?, Google docs/slides/sheets, etc.
- In this question, "List the programming languages your team is proficient with", perhaps lead with something letting them know the chief languages that are used on the project (i.e. ruby, rails, rspec, react, redux, etc. etc.)
- "List all technologies your team uses for development", outside of highlighting the overlap between what VSP uses, and what they use, curious what would be the gain here?  
- "What continuous integration systems has your team used?", perhaps lead with the tools that the VSP uses here, and inquire around their experience with them?
- "List testing technologies your team is experienced with"; I believe this one is already captured in some of the above questions
- Maybe some disclaimer/question around the VSP has a strong code review culture.  What are your team's experience and practices around code review?
- re: the "A short description of your project" question, perhaps a follow up question around including any links to their code, product docs, etc. etc., should they have any available to share

**Comment by 1Copenut** [comment]
@accbjt I agree with Harry, this is looking great and gives us a lot of starting information. Here's a few thoughts around 508 and accessibility:

* I'd like to change the question `Rate your team's experience level with 508 accessibility standards.` to `Rate your team's experience level with WCAG web accessibility standards.` Section 508 started using WCAG for their baseline set of criteria last year, so it'd be good to level set teams' familiarity with those more comprehensive criteria.
* What do you think about adding a question for screen reader experience. I'm interested in knowing which assistive technologies teams have used. Maybe a checkbox group of `[NVDA, JAWS, VoiceOver, Dragon Text or alternative, ZoomText or alternative]` and the question could be phrased like "Have you tested applications or websites with assistive technology? Please check all that apply."
* Is it worth considering adding a mobile testing and/or mobile accessibility testing question? Given our responsive, mobile-first mantra, it might be good to know how comfortable teams are with this methodology.

**Comment by rtluu** [comment]
This looks great @accbjt and team, thanks for all of your hard work

**Comment by emilywaggoner** [comment]
This looks awesome! I made a couple of copy edits and added a final question:
"Is there anything else that you'd like to share about the way your team works?"

**Comment by accbjt** [comment]
@emilywaggoner great thanks. That is a great added question.

**Comment by hpjaj** [comment]
LGTM!
