### ISSUE TITLE
Research recruitment blurbs

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#41320]
## Story

As the VA.gov design and research team, we want to encourage more Veterans, service members, caregivers, and family members to sign up for research studies.

## Need

Recruitment blurbs:

- 1 for the Medallia survey confirmation screen
- 1 that a research participant can share with others

**Comment by DanielleThierryUSDSVA** [comment]
## Draft for Medallia survey

Thank you for sharing your feedback.
Want to give more feedback to improve digital tools for Veterans? 
Register for our online user experience studies. If you're a Veteran, transitioning service member, caregiver, or dependent, we want to know what you think. Because we know that the tools we build to serve you are better when you design them with us.
You can register now through our trusted research partner, Perigean Technologies. You’ll get a thank-you gift for your time.
[Learn more about our studies on our Perigean recruitment website](https://veteranusability.us/)

## Draft of shareable blurb

Hi. I just participated in an online user experience study through VA. I shared my feedback to help their team improve the digital tools they’re building for Veterans. 

I thought you might want to share your feedback too. If you’re interested, you can register for online studies now through VA’s trusted research partner, Perigean Technologies. You’ll get a thank-you gift for your time.

To learn more, go to our Perigean recruitment website at veteranusability.us.

**Comment by DanielleThierryUSDSVA** [comment]
## Notes on changes from original in slack

- Worked in some language from the page for consistency/expectation setting (i.e. "improve digital tools and "user experience studies."). We could change the language on the webpage (and I see other things we could change there content wise), but that's not in the scope of this request so for now I'm keeping the language consistent. Let me know if you do want to explore changing language across the materials.
- Since we're sending them off to a Perigean site, we need to introduce who Perigean is.
- Added target and purpose to link in the Medallia version. In the shareable email version, probably better to just include the URL for spam worries.
- In the Medallia version, because this could be anyone giving feedback (an employee, a congressional representative, a VSO, etc.), I think we want to include the audiences we're looking for to set expectations.
- In the Medallia version, considering some more inspirational language ("Because we know that the tools we build to serve you are better when we design them with you.") Would love your thoughts on that.
- Removed "the" before "VA" because VA style doesn't use "the" (Perigean site does, I see)
- Some general content tweaks.

**Comment by andaleliz** [comment]
Hi Danielle! Thanks so much for this. The updates are a definite improvement and it's helpful to read through your thought process.  It all makes sense to me.

### Draft for Medallia survey
My concern is that the blurb for the Medallia version is too long since it appears in a modal. Here's how it looks as-is on desktop. 
![Screen Shot 2022-05-13 at 10 16 49 AM](https://user-images.githubusercontent.com/55992116/168307552-3e6b1c5b-e558-4255-9d07-2d746d236bf6.png)

I'm not sure how much control we have over line breaks, text alignment, and font style. I'm looking into it.

If we can control the appearance, what do you think about shortening it to:

Thank you for sharing your feedback.

**Want to give more feedback to improve digital tools for Veterans?**

If you're a Veteran, transitioning service member, caregiver, or dependent, we want to know what you think. We know the tools we are better when we design them with you. You’ll get a thank-you gift for your time.

[Learn more from our trusted research partner, Perigean Technologies](https://veteranusability.us/)

If we can't modify  it, what do you think about:

Thanks for your feedback.  You can give more feedback to improve digital tools for Veterans by participating in online research. If you're a Veteran, transitioning service member, caregiver, or dependent, we want to hear from you.  You will receive a thank you gift for your time. [Learn more from our trusted research partner, Perigean Technologies](https://veteranusability.us/).

### Draft for shareable blurb

I think the last sentence should use "the" instead of "our":
To learn more, go to the Perigean recruitment website at veteranusability.us.

**Comment by andaleliz** [comment]
Hi Danielle, just following up on my last comment. Looking forward to your thoughts and getting these out there :) 

Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @andaleliz! The visual and added info about formatting is super helpful in adjusting content to work in this context. 

A few notes on interations:
- Since the Perigean site uses the term "user experience studies" instead of "research," I think we should stick with that (or shorten to "online studies") for consistency. Note that I only shortened this to "online studies" in the last version, but we could likely do that in all 3.
- I don't think the link quite works in the above iterations
- We want to avoid language like "we want to hear from you?" that implies hearing
- A few words missing in the one line in the above


Some iterations that I think can work with or without the formatting of the bold and separate lines:

## V1

Thank you for your feedback. Want to share more? If you're a Veteran, transitioning service member, caregiver, or dependent, we want to know what you think. We know the tools we build to serve you are better when we design them with you. Register for online user experience studies through our partner, Perigean technologies. You’ll get a thank-you gift for your time. [Learn more about our studies on the Perigean recruitment website](https://veteranusability.us/)

##V2

Thank you for your feedback. Want to share more to help us build better digital tools for Veterans? If you're a Veteran, transitioning service member, caregiver, or dependent, we invite you to join our online user experience studies. Register now through our trusted partner, Perigean Technologies. You’ll get a thank-you gift for your time. [Learn more about our studies on the Perigean recruitment website](https://veteranusability.us/)

##V3

Thank you for your feedback. Want to share more? If you're a Veteran, transitioning service member, caregiver, or dependent, join our online studies. And help us build better digital tools for Veterans. Register now through our trusted partner, Perigean technologies. You’ll get a thank-you gift for your time. [Register for studies on the Perigean recruitment website](https://veteranusability.us/)

**Comment by andaleliz** [comment]
Thanks so much @DanielleThierryUSDSVA! I think v2 is the most direct and clear; I'll submit that for consideration. thanks for working with me on this! I'll leave this ticket open until I get confirmation from the platform team.

**Comment by DanielleThierryUSDSVA** [comment]
You're welcome, @andaleliz! Always a pleasure working with you. And thank you for driving this effort to encourage more research participants!

**Comment by andaleliz** [comment]
Aw, back at you! I really appreciate your support in this effort. We lucked out - today is the weekly Research Ops meeting so they've added these to their agenda for review ❤️  hopefully we can start using these soon.

**Comment by andaleliz** [comment]
Adding an update here that Kevin Hoffman is working w/ Perigean on some other ways to approach this since we can't promote a private company on a govt website.

**Comment by andaleliz** [comment]
Followed-up with Kevin and Shane in slack today to see if there are any updates available.

**Comment by andaleliz** [comment]
OCTO is going to share the suggested email content we created. At this time we're not moving forward with updates to the content in Medallia.
