### ISSUE TITLE
VHA partner request to add information about medical records + Additional medical records page changes

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#41342]
## Request

The VHA Health Informatics Office would like us to add more information about different ways to request medical records + how to request DoD medical requests.

Their request is to add this information to our [Get medical records](https://www.va.gov/health-care/get-medical-records/) online tool landing page.

However, we should assess the ask from a few different perspectives and recommend what we believe is the best solution:

- The landing page is about getting your VA health records online. So, we don't necessarily want to add this information to the page. We could, however, add links to Resources & Support for the additional information. We can think about how to best represent that information in R&S article(s).

- We have a [ticket in the backlog](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/22716) to move the VHIE information off of this page and into R&S. We can likely tackle that at the same time as this request or as a fast-follow.

- We need to confirm how the Cerner/not Cerner factors in here. And we can look at the pattern changes that we want to make to these pages while we're updating or as a fast-follow.

**Email info and attachments directly from VHA partner's request for more context:**

For clarification, the instruction documents attached are intended to be provided to a first party requestor (the Veteran)  under a specific situation that is described in the content at the beginning of each document.  

We are requesting to add content to the existing va.gov page, Get Your VA Medical Records Online | Veterans Affairs,   We want to add the sections “Request your records in person, fax or email” and “ordering process time” in the “How to request VA records OHI_Template” document.  The “Request your records in person, fax or email” section describes how someone utilizes the find locations function on the va.gov website to look up the VHA facility medical records/release of information office contact information.

We would also like to add a section describing how to request DoD health records under certain circumstances with a link to the  TRICARE website for DoD:  https://www.tricare.mil/Resources/MedicalRecords and the attached document titled “How to request DoD health records v2”

[How to Request VA Medical Records_OHI Template 02 16 22_v2](https://app.zenhub.com/files/133843125/c46ff5dd-e8d4-477d-bd1a-96295f4c9b7c/download)

[How to Request DoD Health Records v2](https://app.zenhub.com/files/133843125/f7fed801-d0a8-4b21-8c05-e8d03292262b/download)

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , since this will involve Cerner and passing off some of the updates to Public Websites, we're thinking we'll do this all in one go, rather than fast-follows. Here's our suggested approach:

1. Create **new R&S article for VHIE** using the multiple Q&As template. (May need editing to fit template — could switch to Detail template if Q&A doesn’t work.)
2. Create **new R&S article for getting VA medical records that aren't in Blue Button**. This one may be a double Step-by-Step or a Detail page with instructions under Option 1, Option 2 ([example](https://www.va.gov/health-care/how-to-apply/)). Note: Local VA medical centers already have some of this info on their “[access your medical records](https://www.va.gov/central-western-massachusetts-health-care/medical-records-office/)” pages.
3. Create **new R&S article for getting medical records from DOD** using the Detail template with Accordions for 3 situations.
4. Make **updates to Get medical records** page:
- Assess entire page to implement [new tool landing page pattern updates](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/tool-landing-pages.md) from [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/34123)
- Add H3 with new notification content from [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33349)
- Remove VHIE content and link to new R&S article on VHIE
- Link to 2 new R&S articles on DOD and VA records requests — maybe under a new H3 like “How do I get medical records that aren’t in Blue Button?”

Also noting one important question that came up: How would a Veteran know whether their missing medical records are at their local VA medical center versus at the DOD?

I'll find a time for us to chat through this approach next week!

**Comment by DanielleThierryUSDSVA** [comment]
Hi @RLHecht @laurwill. I was updating some old tickets re: R&S and came across this draft single Q&A of "How do I get a copy of my VA medical records?": http://preview-prod.vfs.va.gov/preview?nodeId=37651. I think this new approach will subsume this Q&A, but sharing for awareness and if content is useful. Thanks!

**Comment by laurwill** [comment]
Hi @coforma-terry , just noting that I closed this incredibly old ticket, but didn't add it to the capacity tracker — we completed this work last year :)
