### ISSUE TITLE
Update Storybook Side Navigation

### ISSUE THREAD

**Issue by pdavies88** [department-of-veterans-affairs/va.gov-team#41381]
## Description
We would like to fix the layout of the side navigation in Storybook to match up with the hierarchy on design.va.gov
- Per conversation on Hierarchy Side Navigation in Storybook should follow this pattern:
  - title: 'Components/Pagination/React Component/Pagination'
  - title: 'Components/Pagination/Web Component/va-pagination'
- If a component does not have a corresponding React Component associated with it it should follow this pattern:
  - title: 'Components/Pagination/va-pagination'
- Groupings and Titles should match side navigation groupings on https://design.va.gov/components/ ie:
  - Form and Progress Bar should be broken out further
    - title: 'Components/Form/Radio button/React Component/RadioButtons’
    - title: 'Components/Form/Radio button/Web Component/va-radio’

Once all navigation has been updated we need to update all of permalinks in Storybook so that the  iframes in design.va.gov to match up with the urls that will be created due to the new structure. To do this we can add permalinks to our stories: https://storybook.js.org/docs/react/configure/sidebar-and-urls#permalink-to-stories. Therefore we should add an id in each of stories with the existing structure.
Example:
```
export default {
  title: 'Components/Form/Checkbox/va-checkbox',
  id: 'Components/va-checkbox',
};
```

## Acceptance Criteria
- [ ] Rework titles in storybook files to match hierarchy listed above
- [ ] Add Permalinks to storybook files to help us from needing to update design.va.gov with our new url paths
- [ ] After changing titles and adding permalinks put an announcement in #vfs-frontend #vfs-all-teams #vfs-engineers and #design

**Comment by andresriveratoro** [comment]
Storybook allows us to create [permalinks](https://storybook.js.org/docs/react/configure/sidebar-and-urls#permalink-to-stories.) to stories. Since links will change due to the work in this issue, we should consider using permalinks to not have to update links in design.va.gov in the future should our structure or stories change.

**Comment by pdavies88** [comment]
@andresriveratoro great call I'm going to update the ticket and AC to reflect that thanks!

**Comment by caw310** [comment]
Any ones that are blank, add use with caution indicator.

**Comment by k80bowman** [comment]
The structure recommended here didn't end up working out as well as we had hoped in practice. Instead we have decided to restructure the sidebar in a different way:
- The main components section will contain whatever version of the component has the highest maturity scale rating. These components will be named with the primary component name (in the case of web components, this will be instead of the `va-` name).
- Deprecated React components that are not yet ready to be removed from Storybook will go in their own section at the bottom of the sidebar.
- Form components will be grouped, but a maturity scale sidebar indicator will not appear for the top-level grouping

One thing we didn't discuss as a group is how to handle web components that are intended to replace existing React components. We would want to keep the React component in the main components section until it is deprecated in favor of the web component, but we still need to keep the in-progress web component somewhere in the meantime. I recommend adding a separate "In progress" section under the main components section, but above the deprecated components section, to house those temporarily.

**Comment by k80bowman** [comment]
This https://github.com/department-of-veterans-affairs/component-library/pull/482 is ready for re-review. I plan to go over this with the engineers in our weekly sync today (8/22), since it would mean changing how we assign maturity scales and guidance URLs for web components.
