### ISSUE TITLE
Postmortem on latency increases on vets-api services

### ISSUE THREAD

**Issue by zachclarity** [department-of-veterans-affairs/va.gov-team#41448]
We need to document the details on what, why and how we plan to prepare for future events.

See -  https://dsva.slack.com/archives/CBU0KDSB1/p1652729244646429

**Comment by jhwuz** [comment]
## What

Started seeing cycling activity on `prod-vets-api` around 12:00pm EST yesterday(5/16/22). This caused overall mean latency in the system to go above 2s and impacted the production environment.

## Why

Checking datadog traces, it was determined that the cause of the issue was an influx of slow requests from controllers using the external `BGS` service (in particular, PaymentHistoryController). These requests were often taking several minutes to return a response and this caused all of the puma workers to become congested. As a result, the instances were unable to respond to ELB health checks and started shutting down and cycling.

**Comment by zachclarity** [comment]
Comments from @ericboehs   

```
My current recommendation would be to increase the number vets-api servers (and bump their instance type to have more memory) and if that didn’t resolve it, temporarily block traffic to the payment history endpoint via rev proxy.
As far as I can tell, this endpoint was not written to use our breaker pattern or feature flipper so we are not able to disable this route from within Vets API.
Samara has pointed out this service was written by a team who no longer is on the project. (edited) 
```

**Comment by zachclarity** [comment]
More comments from @tpharrison  for the issue:  https://dsva.slack.com/archives/CBU0KDSB1/p1652807102419569?thread_ts=1652730373.238989&cid=CBU0KDSB1

```
Here is some more details about the errors from May 8th...
Payment History - Payment Information Service?WSDL returned 403: User does not have access to the requested resource (~25k+ requests)
CH33 Bank Accounts - Benefit ClaimWeb Service?WSDL returned 500: Internal server error (~1,380+ requests)
Debts - BGS People Service - VA File Number Not Found - (~5,500+ requests)
BGS did inform us that Corp Prod was down on May 8th from noon to 6pm CT for patching.  I'm not sure what would cause this activity though.
```
