### ISSUE TITLE
Dev: content updates to Direct Deposit react widget 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#4148]
## User Story or Problem Statement
We need to update content that appers within the DD react widgets to correspond with other copy changes are are making on that page. 

This is an update that needs to be done by a developer, as these widget code is part of the rest of codebase with our applications. 

@ncksllvn @kelsonic Please see below for screenshots for the 3 DD widgets that need copy updates: 

- Pre-sign on widget (embedded in the static page)
- Verify your identity CTA
- 2FA CTA

## Goal

The following copy updates updates need to be made to the React widgets: 

**Pre-logon sign on widget**

![Direct deposit content page: Nov 2019 pre DS logon gate](https://user-images.githubusercontent.com/34068740/70251314-440f5e80-174d-11ea-8d79-49f0f916da3a.png)

**Verify your identity CTA**

[Direct deposit content page: Verify your identity prompt .pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3922700/Direct.deposit.content.page.Verify.your.identity.prompt.pdf)

![Direct deposit content page: Verify your identity prompt](https://user-images.githubusercontent.com/34068740/70156757-71dba100-1682-11ea-9148-a349c856466f.png)

**2FA CTA**

[Direct deposit content page: Add 2FA prompt.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/3922701/Direct.deposit.content.page.Add.2FA.prompt.pdf)

![Direct deposit content page: Add 2FA prompt](https://user-images.githubusercontent.com/34068740/70156771-756f2800-1682-11ea-87a4-4dad5355ac15.png)

## Acceptance Criteria
- [ ] Widget copy is updated based on screenshots above
- [ ]  updated copy reviewed by Peggy and Samara before being deployed

**Comment by ncksllvn** [comment]
Hey @peggygannon, I've been looking into this just now. Some findings -

1. I haven't worked on the CTA widgets before, but I'm seeing a limitation - the different states of the CTA widget share the same "service description" used for the title. For example, in our case - `Please sign in to (service description)` becomes `Please sign in to change your direct deposit information online`. Similarly, `Please set up 2-factor authentication to change your direct deposit information online` uses the same words, and same with the prompt to verify your identity. We can of course modify that to make it more flexible, but we should scope it for a sprint then. (Correct me if I'm wrong on this @erikphansen)
1. The blue alert banner for eBenefits appears to be configurable from Drupal, so that one you should have control of without dev support.

**Comment by peggygannon** [comment]
@ncksllvn Ok, thank you.  So to clarify: 

1. There is a character limitation for the react widget titles and we can't customize these titles at this time. Depending on use cases, we could scope this change for another sprint? 

2. Are you able to add the copy that is in red above the green buttons for 
--Verify your identity CTA widget
--2FA CTA widget

3. And yes, I've already update the eBenefits Alert message in drupal!

**Comment by peggygannon** [comment]
Closing. As we can update Widget headers without affecting other widgets that use the same service description.
