### ISSUE TITLE
Analytics KPI dashboard request for [Sitewide homepage - content]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41503]
# Request a New Standardized KPI Dashboard

## What this form is for

Use this ticket template to request a new standardized KPI dashboard on Domo for your product. To make updates to a product already on a standardized dashboard, please use the [Request an Update to your Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D).

Standardized dashboards are currently available for Forms, Content, & Search products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within **2-4 business** days from this time. 

## Instructions for the VFS team
In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

*NOTE: If you do not have Google access, you can download an Excel version of the template [here](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f).*

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet - [KPI Dashboard Product Details - Sitewide homepage - content](https://docs.google.com/spreadsheets/d/1h0wa8m4lSqFtulFipHPTyYU66CUlCyT6DuNcASYWSIs/edit?usp=sharing)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by chloedotbrown** [comment]
@obrienjulie I did some scoping work on this as well - confirming we will need to take a different approach than adding "www.va.gov" to the `content_urls` table to avoid accidentally bringing in the whole website. I think the question of where in the pipeline the new code should be added is clearer than in the case of [Search](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41512), since unlike all our other datasources, the join between the standardized view and the `content_urls` table happens in the Domo connector, not BigQuery.

Adding something like this to the [Domo query](https://va-gov.domo.com/datasources/b677d6c5-5a79-41c8-a3a8-438fb769ffc3/details/settings) might work?
```
UNION ALL

SELECT date,
  user,
  session,
  product as product_url,
  -- 2 hard-coded descriptive fields since not in content table
  'VA Homepage' as product,
  'Task-oriented landing page for Veterans and beneficiaries of VA benefits and services' as product_description,
  benefit_hub,
  hub_product,
  page_title,
  page_name,
  new_or_returning,
  previous_page,
  device_category,
  browser,
  mobile_brand,
  mobile_model,
  mobile_device_info,
  device_os,
  medium,
  source_medium,
  hit_number,
  hit_time_sec,
  hit_type,
  time_on_page,
  time_to_event,
  event_action,
  event_label,
  engagement_type,
  link_label,
  search_keyword
FROM `vsp-analytics-and-insights.vsp_sites.vw_content_engagement_last_week` 
WHERE site_url IN ('www.va.gov', 'www.va.gov/index');
```

**Comment by obrienjulie** [comment]
@chloedotbrown  - Yes, adding this in to the DOMO connector is the cleanest option. I updated the Domo connector and am now running the backfill.  With the size of this data, backfill won't be complete until later today.

**Comment by mmiddaugh** [comment]
@chloedotbrown any update on this DOMO for VA.gov home page?

**Comment by michelle-dooley** [comment]
@mmiddaugh - we just completed the homepage search request, we will move our focus onto this one now.

**Comment by chloedotbrown** [comment]
Hey @mmiddaugh - thanks for your patience on this! After some investigation, it seems like the all traffic to the homepage would increase the data size of the [Content Dashboard](https://va-gov.domo.com/page/426422632) by ~50%. This dashboard already has some latency issues and some cards take a noticeably long time filter by product. When we've got a data engineer again, we plan on refactoring the data sources that support this dashboard so that it processes more efficiently.

However - we don't want you to have to wait for us to complete that tech debt in order to have access to these metrics! As a temporary solution, we propose this: we'll create a standalone copy of the Content Dashboard that only includes homepage data. This would look _exactly_ like the current version, but would be connected to a different datasource, minimizing performance issues for your new dashboard and the current version.

Let me know if this would work for you! I also want to confirm which urls we should be filtering for, since we'll need to do exact matches. Anything besides `www.va.gov/` and `www.va.gov/index/`? Thanks!

**Comment by mmiddaugh** [comment]
Thank you for going to the extra effort to make this temporary solution available! Tracking interactions on homepage (`www.va.gov/`) is the biggest priority. 
`www.va.gov/index/` doesn't open like a valid url for me but if it makes sense on the analytics side, I'm not opposed!

**Comment by chloedotbrown** [comment]
Great! We'll get working on it and will let you know when it's ready.

**Comment by mmiddaugh** [comment]
@chloedotbrown any update on timing?

**Comment by chloedotbrown** [comment]
Hi @mmiddaugh - apologies for the delay on updates! I'm hoping to finish this build today and send it over to my teammates for QA tomorrow. The end is at last in sight!

Some background on why this has taken so long. Even separating the Homepage data out from our other Content products, we still ran into processing issues due to the size. We've solved this by transforming the data more thoroughly before it hits the dashboard. The biggest impacts this will have on your end is that 1) it will run a _lot_ faster and 2) some metrics that are scoped by user on the Content dashboard will instead be scoped by session on your version. This allows us to get the data down to a manageable size while still giving you the flexibility to change the date range or date unit and get accurate counts. 

If you have any questions or concerns about these changes, please let me know. Otherwise, we'll ping you in the next few days when this is ready!

**Comment by mmiddaugh** [comment]
Thank you for the update! Sounds great - thanks for your persistent effort to make this available

**Comment by chloedotbrown** [comment]
@mmiddaugh Quick question for you - noticed while I was QAing this that your page has a number of different navigation `event action` configurations that we weren't catching, likely because they aren't used / were determined to be less useful for non-homepage folks. For example, "Header," "Zone One," "Main Page Button," and "Footer" events aren't being captured.

I can definitely add these in! But since we're doing this as a custom job and the homepage **_is_** mostly links - would adding these as categories to the "engagement types" you can filter by on the dashboard be useful? That way, you could filter to see what folks are clicking on most by section. I don't think doing so would add on that much more time. Let me know what you think!

**Comment by mmiddaugh** [comment]
That information would definitely be helpful - yes, please!

**Comment by chloedotbrown** [comment]
Thanks for your enormous patience, @mmiddaugh - your [Homepage Engagement dashboard](https://va-gov.domo.com/page/80919003) is finally ready to roll!

You'll notice this looks extremely similar to the Standardized Content dashboard and loads a lot more quickly. (In fact, we may update the Content dashboard to match your version in the future). In the meantime, we've left links to the Content data dictionary, though there are some metrics that are calculated differently - most importantly, we've switched some previous user counts to sessions instead.

As we discussed, I also customized the interaction categories in hopes of making them more useful to your team. Current categories, in order of most-to-least common are: Zone One, Anchor links (includes header and nav clicks), Link List, Buttons, Accordions, Alert Box, Other links, and Footer. You can use these to filter the "Top interactions" table in the 2nd section on the dashboard. You can also drill in place for this card, showing the `event action` that's used to create the more readable `link label`, and showing totals for that event by week.

Similar to the Content data, we did exclude any events with "Login - vagovprod" as the `event action`. These tend to drown out the actual engagement - but if it's something you'd actually like included, you can put in a new feature request ticket and I'll add it in.

Let me know if you have any questions - otherwise, we'll go ahead and close this ticket!

**Comment by mmiddaugh** [comment]
Thank you @chloedotbrown ! I am so excited to kicking the tires on this new dashboard!

**Comment by chloedotbrown** [comment]
Fantastic! Feel free to reach out or drop by office hours next week if you have any questions. For now, closing the ticket for this phase of work!
