### ISSUE TITLE
Analytics KPI dashboard request for [Sitewide homepage - search]

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#41512]
# Request a New Standardized KPI Dashboard

## What this form is for

Use this ticket template to request a new standardized KPI dashboard on Domo for your product. To make updates to a product already on a standardized dashboard, please use the [Request an Update to your Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=michelle-dooley&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-update-kpi-dashboard.md&title=Analytics+KPI+dashboard+update+request+for+%5BTeam%5D).

Standardized dashboards are currently available for Forms, Content, & Search products only. To see if you should request a standardized dashboard, check [Should I request a standardized KPI dashboard](https://docs.google.com/presentation/d/16mRcslbkWtW44rlsfQGXZnHtQ3GoLjn6GpFnd3Gvva8/edit#slide=id.p). If you’re not sure which dashboard(s) your product(s) qualify for, check the [Eligibility Dashboard](https://va-gov.domo.com/page/1550814739).

If your VA.gov product is not eligible for a standardized dashboard, you may be able to request an “edge case” dashboard. Please reach out to the Platform Analytics & Insights team on #vfs-platform-support for more information on this process.

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within **2-4 business** days from this time. 

## Instructions for the VFS team
In order to pull the correct data for your product, we need your help to define what pages and events to include, in addition to basic product info. We’ll need a filled out [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) before we can pull this ticket into our sprint.

*NOTE: If you do not have Google access, you can download an Excel version of the template [here](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f).*

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet [KPI Dashboard Product Details - Sitewide homepage - search](https://docs.google.com/spreadsheets/d/1xYSYMwD1enES6J3MkXLfGp3fWdmX2ni-4-zzibRzMJI/edit?usp=sharing)
     - This will be a modified version of the search dashboard, hoping to answer questions such as 
        - what are the most common searches initiated from the homepage (rather than those which occur across all of VA.gov)?
       - which searches initiated from the home page are not successful (or ultimately lead to search results outside of the first few returned)?
        - which search result(s) are selected following searches initiated from the home page?
        - which searches initiated from the home page cannot be answered using the consolidated search functionality?
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the Standard KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by chloedotbrown** [comment]
@obrienjulie Confirming that this will require an additional BQ view, but luckily, it should be pretty simple! I did a bunch of exploration into the search data today, and a select-all of the current standardized views with the following where clause should get us what we need:

```
WHERE search_scope = 'All VA.gov'
    AND (event_label = 'view_search_results' 
      AND page_path IN ('www.va.gov/','www.va.gov/index'))
    OR (event_label = 'onsite-search-results-click' 
      AND previous_page IN ('www.va.gov/','www.va.gov/index'))
```
We'll need to hard-code the `search_scope` field as well - maybe just "VA Homepage" would work? I'm not sure where in the pipeline will be least disruptive / easiest to maintain to add this, so defer to your judgement! Let me know if you have any questions.

**Comment by SKasimow** [comment]
@mmiddaugh - so sorry! I accidentally changed some labels thinking I was in my own ticket :(
I've added them back but just wanted to let you know in case you were wondering what I was doing here!

**Comment by chloedotbrown** [comment]
Hi @obrienjulie - I think this is for sitewide search, not content! But either way, what we actually need is for this data to end up in the [Standard Search dataset](https://va-gov.domo.com/datasources/24e12077-2040-4d15-9cac-d832cbffe289/details/data/table) with everything else. Otherwise, we'd have to build an ETL to combine the two and reconnect every single card on the dashboard. 

Since this is its own new view in BQ, it makes more sense for us to union these within the Standard Search Domo connector. This will require another backfill, but it will be a much more efficient fit for our overall workflow. If you have any questions, please let me know!

**Comment by chloedotbrown** [comment]
@michelle-dooley Think I've got a strategy that will get us where we need to be to include accurate VA Homepage searches by making slight changes to both of the Standardized Search views in BigQuery. 

I've created a temporary view in BigQuery (`vw_search_homepage_last_week`) and [test Domo dataset](https://va-gov.domo.com/datasources/d244333c-7ba5-4dbc-a299-66e1f8ce7e1b/details/overview) where I've been QAing the approach. Basically, I've unioned a nearly identical version of the existing search query below the current one, but hard-coded the product field and fixed some of the parenthesis issues in the additional homepage criteria so that only the correct rows are getting through

### QA process
Here were the tests I ran to QA the data:

- [x] BQ - Row counts by product was identical for existing 4 products was identical to current production dataset for 5/22-5/28.
- [x] BQ - Row count for "VA homepage" was lower than for "All VA.gov," since former is a subset of the latter.
- [x] BQ - Row count for "view results" events was higher than for "results clicked" events for the new homepage product.
- [x] Domo - Row count excluding new product was identical to current production dataset for 5/22-5/28.
- [x] Domo - For "view results" events, homepage URL was only pagepath value.
- [x] Domo - For "results clicked" events, homepage URL was only previous page value. 

### Next steps

1. Confirm this is the strategy we'd like to use
2. Update both versions of Standardized Search views in BigQuery
3. Complete backfill of Standardized Search data in Domo to pull in historical data for homepage searches.
4. Reset Domo dataset to last week view moving forward.
5. Final check of data on dashboard when filtered for new homepage product.

**Comment by michelle-dooley** [comment]
@chloedotbrown - I think that strategy sounds great, thanks for digging into this!!  Please proceed as you outlined above.

**Comment by chloedotbrown** [comment]
Update - backfill is running again, and I'll double-check it first thing in the morning. To solve the issue, I've added a subquery to the "Homepage" section of both BigQuery views so that refinements are identified before the product filter is applied. 

The refinement rate when tested in BQ is much closer to other search products, as expected. The total refinements per session definitely skew lower, though that makes sense for how we're defining the product as a url-based subsection of "All VA.gov" searches.

**Comment by chloedotbrown** [comment]
Hi @mmiddaugh ! Wanted to give you an update that your data is finally moving into QA for sitewide search on the VA homepage. We'll confirm on this ticket once it's completed.

Also, wanted to provide some context for how we're scoping what counts as "VA Homepage" search data. We're counting "All VA.gov" search events that happen on the homepage and search click events where the homepage was the previous page. The place where we had to make a judgement call was for consecutive searches. 

So - say User A searches from the homepage, but instead of clicking a results, they search again on the results page. That first search _**will**_ be counted as a refinement (a search that led to another search, not a click), but that second search _**won't**_ be counted as part of the "VA Homepage" data, since it happened on the search results page. You'll just want to keep that in mind when looking at the distribution of [search sessions by total refinements](https://va-gov.domo.com/page/1964748112/kpis/details/875940030) card. If you have any questions, let us know!

**Comment by mmiddaugh** [comment]
@chloedotbrown can we make that logic/definition available in the dashboard or data dictionary somewhere? I just want to be able to find it easily when I need it - thank you!

**Comment by chloedotbrown** [comment]
Sure thing, @mmiddaugh! I've added a section at the top of the [Search Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/data-dictionary-va-gov-search-kpis) on how products are defined and give yours a specific call-out. It's not visible now, but it should be live after the next Platform Content batch update to the website on Tuesday.
