### ISSUE TITLE
Update front-end support dashboard to be accurate per the changed app build process

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#41668]
**DESCRIPTION / USER STORY**
VFS engineers want to know if their commit, specifically for apps on the allowlist, is deployed to prod or not. 
*The current dashboard they use for this, due to changed app builds process, will no longer remain completely accurate.

**ACCEPTANCE CRITERIA**
There are 2 functionalities that will be built out, and 1 that should remain:

- [x] Apps not on the allowlist: checks the daily full deploy for the most recent commit that was deployed - checks this status. This is current functionality; needs to be kept working.

- [x] Apps on the allowlist: checks individual workflow runs to ensure recent commit was deployed to prod.

- [x] Acknowledging that commits get deployed to dev and staging environments, we need to determine a way to show if the commit that was deployed, was deployed with a full deploy or changed app deploy.

**DEFINITION OF DONE**

- [x] The dashboard has current functionality (for apps NOT on the allowlist) AND 

- [x] functionality for apps added to the allowlist that represents accurate information for deploys.

**Comment by alexandec** [comment]
I did some discovery on this topic. Here are my findings so far.

### Current approaches to determining commit deployment state

#### Existing FE Support Dashboard
The existing [FE Support Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/) does not use a GH token, so requests [are limited](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-personal-accounts) to 60/hour per user. This is fine since a single page load makes exactly two GHA API requests: one for vets-website commits, and one for content-build commits. These requests, as well as requests for the BUILD.txt file for each environment, are sufficient to display deployment information based on the daily deploy. (Fetching the BUILD.txt files does not count against the request limit since those are just raw file requests, not GH API requests.)

The FE Support Dashboard does not take changed app builds into account, so it's not adequate in its current form going forwards.

#### Existing Console UI Plugin
The [Console UI plugin](https://platform-console-ui-dev.vfs.va.gov/release-tools) uses a GH token to make requests, so requests are limited to 15000/hour per user. This is no problem because a typical page load makes about 10 GH API requests. This includes a request for commits, a request for workflow runs, a request for user info, a request for team members, and a separate request for each commit to get workflow job information. The maximum number of requests in a very unusual case would be about 100 which is still fine. The idea here is that by checking the deployment workflow jobs for every commit, we can display the deployment results for that commit, regardless of whether the build was for a single app or all apps.

The Console UI plugin does take single-app builds into account, but it uses a large number of additional requests to do so (a separate request per commit). This is only possible because it uses a token to make requests.

### Potential approaches to incorporating single-app builds into the dashboard

In order to display single-app build results in the dashboard, we need some additional information. Exactly what information is required depends on our approach. Some potential approaches are described here.

#### Request job status for each commit
This approach, as used in the Console UI plugin, would require 62 requests per page load: 1 request to fetch the 30 most recent vets-website commits, a separate request for each of those commits to get job info for the commit (30 requests), and the same set of requests for content build, for a total of 62 requests. A single page load would exceed the unauthenticated rate limit of 60 requests/hour per user (unique users are determined by IP address since there is no user information provided to the GH API). For this approach to work, we would have to modify the FE Support Dashboard to require a token. However this would entail further work on our side to add such functionality. Also users would be inconvenienced since they would have to log in or generate a token in order to use the dashboard.

This approach does not require knowledge of whether a particular commit triggered a full build or a single-app build. We would have to research how much effort is required to add a token to determine the difficulty of this approach.

#### Request workflow run info for each repo
This approach would increase the existing number of requests per page load from 2 to 4. Requests would be: vets-website commit info, vets-website run info, content-build commit info, and content-build run info for a total of 4 requests per page load. So where a user can currently load the dashboard 30 times/hour before hitting the limit (30 * 2 requests), they would only be able to do so 15 times/hour (15 * 4 requests). This may be a reasonable compromise.

Note that with this approach, we would get the overall workflow run conclusion for each commit (success, failure, in progress, queued, etc) but we wouldn't have information about individual jobs in the workflow run (deployment success/failure for example). So we would have to infer that if the overall workflow for a given commit succeeded, deployment of that commit also succeeded (should be the case), and if the overall workflow failed, the deployment failed (probably true, but there could be occasional exceptions where the workflow run failed, but the deploy actually succeeded).

This approach does not require knowledge of whether a particular commit triggered a full build or a single-app build.

#### Use GH's GraphQL API request to fetch all commit, workflow, and job data in a single request
 I explored this approach since it could potentially allow us to work around the request limit. The GraphQL API still has a limit on resource use, but it's calculated/enforced differently than the REST API. However, I discovered that it's not currently possible to fetch GitHub Actions data using the GraphQL API. This approach is a non-starter.

#### Recommendation
I think the second method, requesting commits and workflow runs for each repo and correlating them by SHA, is the most promising. It could potentially allow us to support changed app builds, but avoid having add token functionality to the dashboard.

### Questions
- Currently if we fetch https://www.va.gov/BUILD.txt we know that the commit SHA contained there represents a full deployment of all apps. The same is true for https://dev.va.gov/BUILD.txt and https://staging.va.gov/BUILD.txt. Will this remain true when single-app builds are in place? Currently the dashboard assumes that all commits prior to the SHA were deployed. However if the SHA could potentially represent a single-app build/deployment, it could either mean all prior commits were deployed, or just the single commit associated with the SHA was deployed. If the SHA ceases to be a reliable indicator, we'd probably have to fall back on the workflow run conclusion for each commit.
- We'd like to add a column to the dashboard indicating whether a given commit was built/deployed as a single app, or whether all apps were deployed. What's the best way to determine whether a particular commit triggered a full deployment or a single-app deployment? One method would be to get a list of changed files for the commit, determine which app was modified, and check whether the app is on the allow list. This code is already written since it's used when the build/deploy is performed. Maybe the code could be shared, but we'd need to find the right place to put it for proper sharing. Another method would be to inspect the workflow run in some way to determine the type of build/deploy which was performed. The challenges with this approach are 1) how should the GHA run expose the deploy type and 2) how should the dashboard fetch the deploy type without adding a large number of additional requests.
- What's the best way to get a list of changed files for a given commit? The GHA API [commit endpoint](https://docs.github.com/en/rest/commits/commits#get-a-commit) provides a list of changed files, but we'd have to call that endpoint once for each commit. Can we group this info together with all the other commit info we are already receiving? I checked whether we could create a GraphQL query to fetch a list of commits along with changed files for each commit. Unfortunately the GH GraphQL API only provides a [count of changed files](https://github.community/t/get-a-repositorys-commits-along-with-changed-patches-and-the-url-to-changed-files-using-graphql-v4/13585/12), not an actual list of the filenames for changed files.
- An advantage of the BUILD.txt approach is that we know the deployed files actually made it to the server, because if not, the BUILD.txt would not have been updated. It's almost a type of integration test where we know all the pieces are working. Is there a way to achieve a similar level of certainty using a different approach?
- What about an approach where we create a file called DEPLOYMENTS.txt which lives next to BUILD.txt and contains a list of all the SHAs that have been deployed? There is the challenge of keeping this file up to date. But it would better represent the single-app build world, where individual commits are deployed as needed.

**Comment by theodur** [comment]
Thanks for the thorough write-up Chris, this is very insightful. I agree that the approach of getting the commits and workflow runs for each repo seems like the best path to take. I was experimenting with tha approach, and it seems to work well for the most part. There are some caveats like you mentioned (the level of certainty for whether a commit was deployed).

The approach of having a `DEPLOYMENTS.txt` file seems like an easy way to track which commits we deployed. I agree that maintaining it would be a challenge. There's also the risk of the file growing large overtime if we were going to add all deployed commit sha's to it going forward.

I was thinking of an approach where we upload a `BUILD_ARTIFACT.txt` file to the archive bucket `vetsgov-website-builds-s3-upload` that contains information on if the build was a changed app build. This would allow us to have a consistent URL to check to determine whether a commit was a full build or not. That URL would be `https://s3-us-gov-west-1.amazonaws.com/vetsgov-website-builds-s3-upload/COMMIT_SHA/BUILD_ARTIFACT.txt`. I implemented this in a [branch](https://github.com/department-of-veterans-affairs/vets-website/compare/add-changed-app-details-to-archive-bucket) for testing. Some caveats with this is it adds additional requests to the dashboard, which isn't ideal, like you mentioned, and potential CORS issues with that bucket. With those two issues, we might just have to go with the approach of determining the build type based on the changed files in the commit. 

Here's a [draft PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/829) I've been working on that uses the workflow runs to determine the deployment status. Feel free to tinker with stuff on that branch.

**Comment by alexandec** [comment]
Some further thinking on the logic for the dashboard here, assuming we can no longer rely on BUILD.txt to tell us that everything before the commit shown there was deployed.

### Showing commit status for dev/staging
A commit can be deployed to dev/staging in either of the following ways:
- The commit is merged into main and has a successful CI run. We know the commit is deployed whether it's a single-app build or not, because its own CI run has deployed it.
- A later commit is merged into main, has a successful CI run, and is not a single-app build. We know all prior commits are deployed to dev and staging because this was a full build.

We can display green checkmarks for dev/staging on the dashboard for a given commit, if that commit had a successful CI run. No further logic is required in this case.

However if the commit had a failed CI run, we aren't yet sure of the commit's deployment status -- it could have been deployed by a later commit's CI run. In this case we have to check further to find the last commit that had a successful CI run which performed a full build/deploy. 

This used to be straightforward because we could fetch `BUILD.txt` and get the SHA from that file. Now that the SHA in BUILD.txt could represent either a full build or a single-app build, the check becomes more complex.

### Showing commit status for production
A commit can be deployed to production in either of the following ways:
- The daily deploy ran successfully on this commit or a later commit. In this case all prior commits are deployed to production, because the daily deploy always performs a full build of all apps.
- [FUTURE IMPLEMENTATION] The commit is merged into main, has a successful CI run, and is a single-app build

Currently there is only one way a commit can be deployed to production, which is during the daily deploy. So it's simple to check whether a commit is in production: get the SHA from `BUILD.txt` and check whether the commit in question matches that SHA/is prior to that SHA. If so, the commit is deployed to production. Otherwise it's not.

However, once single-app builds are turned on for production, the check becomes more complex because the SHA in BUILD.txt could represent either a full build or a single-app build. If the SHA was placed in BUILD.txt by a daily deploy, it represents a full build. But if the SHA was placed there by a single-app build when a commit was merged into master, it represents a single-app build.

### Potential solutions
#### Keep old BUILD.txt approach
To keep the dashboard logic simple and the number of requests low, we could ensure that the SHA in BUILD.txt always represents the last full build. Single-app builds would leave BUILD.txt untouched. Would this create any other issues? I'm not sure. But it would allow the dashboard to keep its existing simple logic, while adding only two new requests: one for workflow runs in vets-website, and one for workflow runs in content-build. The BUILD.txt SHA would cover full builds, and the workflow run requests would cover single-app builds.

#### Create a LAST_FULL_BUILD.txt file
If we have to change the functionality of BUILD.txt so it's no longer useful for the dashboard, we could create a second file called `LAST_FULL_BUILD.txt`. As the name suggests, it would contain the SHA of the last full build. Deployments to dev/staging would update the dev and staging versions of the file. For production, the daily deploy would update the production version of the file.

#### Stop relying on BUILD.txt and track the type of each deployment
If BUILD.txt could represent either a full build or a single-app build, it's no longer useful to us in determining which commits are deployed. So we could fall back to checking A) the workflow run result for the commit and B) the build type for each commit (single-app or full). Checking the build type would require adding a `BUILD_ARTIFACT.txt` file for each commit as described above, and then fetching that file for each commit. So there is additional file creation and many additional requests required (one per commit shown on the dashboard). This is a more complicated solution, though it could still be worthwhile if there are other benefits.

**Comment by theodur** [comment]
You brought up a lot of good points. I like the approach of keeping the `BUILD.txt` file and only updating it for full builds. This way, every commit that came before the SHA in `BUILD.txt` can be shown as deployed, and we'd only need to check the workflow runs for commits that come after the SHA. This shouldn't cause any issues with changed app builds. I also like that we won't need to make an additional request to the build artifact, because if a commit comes after the SHA in `BUILD.txt`, and its workflow is successful, it has to be a changed app build.

**Comment by alexandec** [comment]
@theodur I [created a PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21343) to prevent changed app builds from updating `BUILD.txt`. You know this part of the code best, so lmk if I missed anything, or if these changes will cause any unwanted side effects.

**Comment by theodur** [comment]
Thanks Chris, I just approved the PR ✅. This shouldn't cause any unwanted side effects. The only thing is the dashboard in its current state won't show when changed app build commits have been deployed, so people may think their changed app build commit hasn't been deployed, but there's no way around this while we're making changes to the dashboard, plus it's already been inaccurate haha. At least in the meantime, it won't show false positives for deployments, which is probably better.

**Comment by alexandec** [comment]
PR merged! Yes, that's my thinking too, neither state is perfect but once we finish the changes we'll be in a good place.

With the BUILD.txt only representing full builds, we can limit any additional checks to workflow runs that happened after the full build. However I think we'll still need a way to determine whether a given build was a full or single-app build. I was hoping that with this BUILD.txt change we could get away with just the request to list commits, and the request to list workflow runs. That works for dev and staging, but for production, we still need to know if a specific run was for a full build or a single-app build. If it was a full build then it won't actually be deployed until the next daily deploy. If it was for a single-app build then it was already deployed (once we turn on single-app build deployments for production). So maybe we still need the `BUILD_ARTIFACT.txt` for that specific case (production build that happened after the last daily deploy).

**Comment by theodur** [comment]
I'm glad that's merged! I'm not sure if we'll have CORS issues with that bucket, but it shouldn't be difficult to fix that if we need to

**Comment by alexandec** [comment]
Good point, we can see if CORS ends up being an issue or not. Now that we have the BUILD.txt change in place, and BUILD_ARTIFACT.txt being uploaded, remaining dashboard changes I see are:

1. Fetch recent workflow run results from the GH API ([Theo's draft PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/829) contains an implementation for this. CORS fix may be required)
2. For commits which are not already deployed by a full deploy (that is, commits added after the commit in BUILD.txt), fetch `BUILD_ARTIFACT.txt` for the commit and determine whether the commit has a single-app build
3. If the commit has a single-app build, check the workflow run result for the commit (these results are already fetched in step 1). If commit's run was successful, show that the commit is deployed to all environments

**Comment by alexandec** [comment]
Add single-app build check to dashboard PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/845
Add function for getting CI workflow runs PR: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/844

These PRs represent the remaining work required to complete this ticket.

**Comment by alexandec** [comment]
[Workflow runs PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/844) is merged. That code is integrated into the [dashboard update PR](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/845). Remaining tasks:

- [ ] Review PR
- [ ] Test dashboard locally
- [ ] Resolve CORS issue

**Comment by alexandec** [comment]
The CORS issue couldn't be resolved, so instead we are putting the build artifact files in a different bucket where we can easily manage CORS ([see PR](https://github.com/department-of-veterans-affairs/vets-website/pull/21597), which is merged).

**Comment by alexandec** [comment]
The [dashboard update PR ](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/845)is merged and deployed. Currently monitoring the dashboard for any issues or abnormalities. The dashboard should now reflect single-app builds. Note that production deploys for single-app builds are not shown on the dashboard because they are not enabled. When we do turn on single-app builds in prod, we'll need to make a small change to the dashboard (very quick to make).

**Comment by alexandec** [comment]
Still monitoring the dashboard, no issues found so far.
