### ISSUE TITLE
Analytics KPI dashboard update request for 10-10 Team

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#41752]
# Request an update to your KPI Dashboard  

## What this form is for

Use this ticket template to request an update to your existing KPI dashboard. To request a new product be added to our dashboards, please use [Request a New Standardized KPI Dashboard template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+kpi-dashboard&template=analytics-request-kpi-dashboard.md&title=Analytics+KPI+dashboard+request+for+%5BTeam%5D).

### Expected delivery timelines

Once you’ve submitted this ticket template, your KPI dashboard update request will be pulled into the Analytics team’s workflow the following Wednesday during Platform Sprint Planning or Refinement. We expect to deliver your completed dashboard within the next sprint. 

## Instructions for the VFS team
First, tell us what type of change you need to make:

- [ ] Change basic product info
- [x] **Forms**: funnel changes
- [ ] **Content**: Add or remove pages included
- [ ] Other_____________________________

Next, use the original [KPI request template](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) or [(downloaded Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f) you filled out to update your information. If you are not able to find that spreadsheet, reach out to the Analytics team on #vfs-platform-support for a new spreadsheet that reflects what we currently have on file.

- [x] Make a copy of the [Google Sheet](https://docs.google.com/spreadsheets/d/1gipo-h3GCeVPsw6t6tEHJM5dtJMvotVm0LUgbpAeqZY/edit#gid=981224988) [(or download Excel version)](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/1586823275/KPI%20Dashboard%20Product%20Details%20Template%20-%20MAKE%20A%20COPY.xlsx?inst-v=ced1f4dd-e997-4aa2-9ae8-2cebe369b42f)
- [x] Complete worksheet as instructed
- [x] Link your completed spreadsheet here: [KPI Dashboard Product Details - 10-10EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZ%20Form/Analytics/KPI%20Dashboard%20Product%20Details%20-%2010-10EZ.xlsx)
- [x] Check your sharing settings to make sure the Analytics team will be able to access it
- [x] Add your team label to follow progress

**Additional Info**

- Please use the [KPI Framework](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/analytics/Analytics%20Playbook/va-gov-platform-analytics-kpi-framework.pdf) for more information on the metrics used in the KPI dashboards. 
- If you need any analytics support, read through the [How to request Analytics support](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Analytics-customer-support-guidelines.1586823275.html#Analyticscustomersupportguidelines-4.RequestaKPIDashboardinDomo).
- If you do not have Domo access, please [request access here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=joanneesteban&labels=analytics-insights%2C+analytics-request%2C+access-request&template=analytics-request-google-analytics-domo-access.md&title=Request+access+to+Google+Analytics+and%2For+Domo).

**Comment by hdjustice** [comment]
When looking at the current funnel and the actual pages, I noticed some pages were missing or out of order.  The completed spreadsheet linked in this ticket has the correct list of pages in proper order.
I am wondering how we will be able to tell the difference between people who complete the long form and those who complete the short form (essentially skipping pages).

**Comment by chloedotbrown** [comment]
Hi @hdjustice - thanks so much for submitting this! A couple follow-up questions before we get started making these changes:

### Current version of funnel
How should we handle the old version of the funnel currently in use? I know you mentioned that some steps were missing or in the wrong order. If this version was previously valid, we can keep it in the older data and use the new version moving forward. Alternatively, if you know when the production version of the funnel changed, we can backfill the new version to that point. 

However, if the version we currently have on file doesn't match _anything_ you've seen previously implemented and is just plain wrong, we can also backfill all previous data for the 10-10EZ to match what you've submitted here. And of course, if you're not sure, we can also help with some discovery work to see when the funnel changed - know there's been a lot of turnover on this team in the past 6 months, and that info may not have been passed along!

### Short vs. long funnel
We can certainly investigate how to break this up into a short and long version - whether it's feasible or not will depend on whether there's anything in the business logic we can use to separate out user paths early on. 

First - I've added some new columns to the [template](https://docs.google.com/spreadsheets/d/14K-5MfPKhSEtTcYt8HwdIcjYZtHrWGUEfAl_ANHLG3w/edit#gid=779923358) you submitted that would be helpful to have you fill out:

- `On short form?` - Check boxes if steps are included in the short version fo the funnel
- `Optional step?` - Check boxes if steps are skippable by users, in short or long version. _(If this is the same as the previous column, feel free to leave it blank!)_

Second - here are a couple other questions that will help us figure out whether we can create two versions of this funnel that will help you view short and long versions of the form separately:

- Are there any events that fire when users select the short/long version of the form? Any specific buttons one group would click and the other would not?
- Are there any steps that short form users would always skip, but long form users would always pass through? For example, a short form user always goes directly from "Personal Information" to "Birth Information," but all long form users fill out the "Profile Information" step.

Feel free to add any other context that would be helpful! And if it's simpler to talk things through, you can join us at [office hours](https://dsva.slack.com/archives/C1Q4294JJ/p1652987751728739) Tuesdays and Thursdays.

**Comment by hdjustice** [comment]
Also to answer some questions around optional/skippable steps - For each flow, the steps listed cannot be skipped.  The user may not have information to enter, but they would still have to press "continue" and move to the next step in the applicable flow.  More to come on any events or triggers for Short Form flows.

**Comment by chloedotbrown** [comment]
Perfect - thank you, @hdjustice! We'll dig into the spreadsheet and see what we can do. And the note about all steps being required is extremely useful!

One last question: how new are these pathways? Are these 4 versions something that recently launched or was this the structure in past months too?

**Comment by hdjustice** [comment]
The long form flows are in production now, I am not sure how long the form has allowed for authentication.  The short form flows are not yet deployed, we are still in QA right now.

**Comment by chloedotbrown** [comment]
Hi @hdjustice! After looking over the spreadsheet, I think we'll have some options to distinguish between Auth and Un-Auth user paths:

- If user journey is determined by authentication status at the time of landing on the "Introduction" page, we can bucket users from the very start of the funnel.
- If users have prompt to login on the "Introduction" page, we can bucket them based on that interior login event or by which page they move onto for Step 2. This would slightly shorten the funnel, but only by the one step where you're likely to get the most drop-off anyway.

However, I'm less sure how we'll differentiate between Long and Short user paths. You may have mentioned this in office hours, but what is it that determines whether the user will be in the long or short funnel? Is it something based on the information already associated with their account? Or based on their responses to the first 15 steps?

If it's something pre-determined and your team can add an event that fires for the short version when the user starts the form, we should have no problem. However, if they get bucketed based on their early responses, we won't be able to provide accurate exit rates/accurate user counts for preceding steps, since there's no way to know which users _would_ have been assigned long or short had they gotten further into the process.

Hope that makes sense - please feel free to drop by office hours again if it's more efficient to talk us through the process in real time!

**Comment by hdjustice** [comment]
This is great information, thank you @chloedotbrown!  I plan to attend the office hours today to talk through it.  I got some more details from Lisa Zapson on what we might be able to use to determine short form applicants.  Talk soon!

**Comment by hdjustice** [comment]
Hi @chloedotbrown and @michelle-dooley 
We plan to release the 10-10EZ Short Form very soon (possibly next week) and I was wondering if the changes we talked about a couple months ago will impact metrics for our release. 
I think we should be OK, we will just see more folks completing the Compensation page, then similar volume into the Insurance information pages (skipping Household pages).  
I know we were talking about looking for metrics around authenticated vs unauthenticated, but that would be a bit more complicated.

**Comment by chloedotbrown** [comment]
Hi @hdjustice - thanks for your patience on this! You're correct about the impact the Short Form launch will have on 10-10EZ metrics on the [Forms Dashboard](https://va-gov.domo.com/page/447193050). This won't throw off most of the cards, but you will see some changes in the funnel table, funnel visualizations, and exit rate table. As you mentioned, you'll likely start to see a drop in users where folks skip steps (Household, etc) in the short form, as well as a spike where they rejoin the shared flow around Insurance. 

**In the long term**, we're thinking it might make sense to break this form out into it's own edge case dashboard that can handle the logic of login-status and disability rating. This would let you filter the entire dashboard by these 4 form flows, as well as composite view that shows metrics across the steps they share. This would definitely be a bigger project for our team and we wouldn't be able to start work until a later sprint. But if this would be useful, let us know and we can add this to our edge case pipeline! 

**In the shorter term** - I want to make sure we're adding the [steps](https://docs.google.com/spreadsheets/d/1HIafokhIwcjourXhBbFYp04QMbKjf1kfqJeMfSH8-a4/edit#gid=794748867) that are at least shared across both long versions of the form to the current logic. Of these 5 missing steps, it looks like all were added by 3/8 at the latest:

- Maiden Name
- Birth Sex
- Marital Status
- Medicaid
- Medicare Part A

For simplicity's sake, I can add these all as a "V2 - updated 3/8/22" and pull in the data since March so you can filter to see them on the funnel and exit rate visualizations. Let me know if that sounds good, and I can update it this week!

**Comment by hdjustice** [comment]
Hi @chloedotbrown - I think both of those Short term and Long term suggestions are great, and we can definitely work with that.  Thanks so much for your help through this!
cc @markfallows

**Comment by chloedotbrown** [comment]
Hi @hdjustice and team - know you've got another ticket in the hopper as well, but just wanted to confirm that the short term version of this fix is complete. You should start to see a drop in users for long-form steps and a bump where the short-form users rejoin the flow later in the process. 

Closing this ticket for now, but I'll create a placeholder in our backlog for addressing the long-term solution in the future!

**Comment by hdjustice** [comment]
Sounds great, thanks so much @chloedotbrown !
