### ISSUE TITLE
Collaboration Cycle Kickoff [Public Websites team, IE11 Deprecation Banner]

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#41829]
## Steps to complete the Collaboration Cycle Kickoff

**VFS Product Manager**

- [x] Create this issue and notify the Collaboration Cycle team of this ticket in the in #vfs-platform-support ([see Slack Workflow (User guide](https://depo-platform-documentation.scrollhelp.site/support/Getting-help-from-the-Platform-in-Slack.1439138197.html)).  
- [x] Answer the questions below and attach any artifacts you have available.
- [ ] Close this ticket when kickoff is complete and Platform has provided the recommended touchpoints. 

**Platform**

- [x] Review the responses and comment in ticket with recommended touchpoints and practice area involvement.
- [x] Platform: Add project to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=266151061).

## Artifacts (if available)

Provide links or documents for the following: 

- Draft of [product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/ie11-deprecation-banner/product-outline.md)
- [Mockup](https://user-images.githubusercontent.com/9451726/170102337-30c6a2f7-0c0f-4422-8916-5da7107ec8f9.png)

## Questions
Please refer to the guidance in [Getting Started with the Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Getting-started.1760493650.html) for detailed information and examples for the below questions.

### 1. Will your work result in visible changes to the user experience?
- [x] Yes
- [ ] No

### 2. Is your work a new product or an iteration to an existing product?
- [ ] New
- [x] Iteration

### 3. If this is an iteration, please tell us what product or feature you're iterating.  

Product or feature: sitewide header

### 4. Are you making changes to the visual design?
- [x] Yes
- [ ] No

### 5. Are you doing research with VA.gov users?
- [ ] Yes
- [x] No

### 6. Will your work involve changes to: (select all that apply)

- [ ] Tools and applications*
- [x] Static pages
- [ ] Both

*For tools and applications, take into account if any static page entry points will need updates.<br/>
**For information and examples of Static vs Dynamic pages, review the [Static vs Dynamic guidance](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/static-and-non-static-page-documentation.md).

### 7. Will your work include:  

- [x] New content
- [ ] Changes to existing content

### 8. Are you making a change to the user flow?
- [ ] Yes
- [x] No

### 9. Are you making a change to urls, navigation, or entry points?
- [ ] Yes
- [x] No

### 10. Does your product or feature have Google Analytics tracking and a KPI dashboard in Domo?
- [x] Yes (events available in GA)
- [ ] No

### 11. If yes, do you need to capture any other analytics or metrics in addition to what you're currently tracking?

- [ ] Yes
- [x] No

### 12. Is there a GitHub label in the va.gov-team repo for this product?

- [x] No. 
- [ ] Yes. Please specify: ____________

### 13. Who is the VA business owner for this body of work?

- [ ] VHA (Veterans Health Administration)
- [ ] VBA (Veterans Benefits Administration)
- [ ] NCA (National Cemetery Administration)
- [x] VACO (Veterans Affairs Central Office) – Dave Conlon
- [ ] Other. Please specify: ____________

## Additional information
Please refer to the [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) guidance on Platform website for more information about the Collaboration Cycle.
FYI: @shiragoodman , @chaseakirby

**Comment by shiragoodman** [comment]
Hi @wesrowe. Thanks for completing this Collaboration Cycle Kickoff ticket! Based on your responses, your project is an iteration to a static content page so we are recommending the following Collaboration Cycle touchpoints: 

- [Sitewide Content and IA intake request](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Sitewide-Content-and-IA-intake-request.2124906551.html)
- [Staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Staging-review.1810137181.html) 
- [Privacy, security, infrastructure readiness review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Privacy-and-security-review.1782317101.html) 

Since your work impacts static pages, please reach out to Dave Conlon to review how your work may overlap with any existing work. This will help them prioritize and identify possible areas of support needed from other teams. 

We understand that scope of work and/or solutions can change as you work through your design process. If you find that your scope and/or solution changes, please reach out so that we can update and/or modify your touchpoints appropriately. 

Your project has been added to the [Platform Collaboration Point Tracker](https://docs.google.com/spreadsheets/d/1OgPyEvUlNF6EnaYMFAXJkV6FKOvZnlPnbOQ2fAJ7W7A/edit#gid=1116695886). When you’re ready to schedule your recommended Collaboration Cycle touchpoints, please review the guidance outlined on the [Collaboration Cycle Touchpoints](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Touchpoints.1768423528.html) page.

**Comment by wesrowe** [comment]
I just talked to Dave C about our proposed design – we think it would be good to consult with Matt Dingee (@humancompanion-usds) about our options and get his take. I'll slack him about it.

**Comment by shiragoodman** [comment]
@wesrowe if you'd like to schedule a Design Intent, you still can. @humancompanion-usds attends those, as does @artsymartha68, so it would be a great opportunity to get early feedback on your design from OCTO and from us.

**Comment by wesrowe** [comment]
Scheduled for Tuesday morning. Thanks!

**Comment by wesrowe** [comment]
@shiragoodman, I reviewed the recommended steps with folks, and they were a little surprised that the Privacy & security review was recommended. I wonder if I miscommunicated our scope? There's no new PII involved or anything – we're just introducing non-PII data into the FE in a little different way. The json payload itself is just a list of facilities and which medical records system they use (Cerner or VistA). Thoughts?

**Comment by shiragoodman** [comment]
@wesrowe The privacy & security review is mandatory for every feature that's brought through the Collaboration Cycle. It's entirely possible that there is no security concern, however that's not a call I, as PM on Governance, can make.

@troymosher and @td-usds are the Platform Security leads and manage the touchpoint, so I'm pulling them in for awareness and so they can decide whether or not the P&S review is necessary.

Thank you for asking, Wes!

**Comment by wesrowe** [comment]
Ah, got it. Thanks for the clarification, @shiragoodman. We knew we were brigning something "pretty small" to the CC, ie, something less impactful than the CC is optimized for.

**Comment by shiragoodman** [comment]
for your awareness, we do have a flow that we follow for determining which touchpoints are recommended/necessary. It's based off your responses to the kickoff questions above. Unfortunately, it doesn't account for every niche scenario, so you did the right thing asking about it (both wrt P&S and the Design Intent). 

We're always looking to improve our process, so if you have ideas for how we can better recommend Collab Cycle touchpoints, I encourage you to [submit a feature request](https://depo-platform-documentation.scrollhelp.site/support/Submitting-a-feature-request.1938915400.html) for Platform :)
