### ISSUE TITLE
Validate LOGIN represents user

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#41935]
# Description
In order to ensure that the login represents a user, we want to ensure we are validating the JWT and refresh token actually belong to the user who originally created the token via the standard auth flow.

- access token isnt possible because we sign the hash of the values, only way they could modify jwt (which should not be possible unless they compromise our private key)
- two csps issuing uuids could cause a collision and thus allow a user to see data for another person. To mitigate this we are going to use the user accounts (new method) uuid instead of accounts table (old method)
- refresh token only matches up with session id it does not populate the session with anything
- user data sent from CSP
   - logingov: user data could be modified in the response from logingov to the backend of vets-api. However we use a state param that is signed by vets-api backend and the code that is used is one time use. @nsoutouras please make a spike ticket to this.
   - idme: they encrypt the user data so it cannot be modified

# Acceptance Criteria
- [ ] Update SiS Access Token to store the `User`'s `user_account_uuid` to find & load users instead of the current `user_uuid`
- [ ] Update SiS Refresh Token to store the `User`'s `user_account_uuid` to find & load users instead of the current `user_uuid`

**Comment by bramleyjl** [comment]
@bosawt @joeniquette I'm digging into this now and am finding the specifics of this a bit confusing. To make sure I parsed everything correctly:
> In order to ensure that the login represents a user, we want to ensure we are validating the JWT and refresh token actually belong to the user who originally created the token via the standard auth flow.

This is in reference to validating both the tokens used with user that created them for the vets-api/CSP exchange and the bulk of SiS, the client/vets-api exchange

> access token isnt possible because we sign the hash of the values, only way they could modify jwt (which should not be possible unless they compromise our private key) two csps issuing uuids could cause a collision and thus allow a user to see data for another person. To mitigate this we are going to use the user accounts (new method) uuid instead of accounts table (old method)

This is our access token with the client, we encrypt it with our private key so it's not modifiable. However we're using the `User` `uuid`, which is sourced from the `UserVerification`'s `credential_identifier`, which is the CSP uuid and could thus cause a collision between two CSP uuids. To prevent this we are going to use the `User` `user_account_uuid`, which is the parent of `UserVerification` and guaranteed to be unique.

> refresh token only matches up with session id it does not populate the session with anything

The refresh token only generates new tokens, since it doesn't otherwise affect the session or user we don't need extra validation.

> user data sent from CSP
logingov: user data could be modified in the response from logingov to the backend of vets-api. However we use a state param that is signed by vets-api backend and the code that is used is one time use. @nsoutouras please make a spike ticket to this.
idme: they encrypt the user data so it cannot be modified

This seems to be talking about validation between vets-api and login.gov between `/authorize` and `callback`. Are we saying that that's enough validation and we don't need additional validation within the two calls to login.gov for the tokens and then the user_info in `/callback`?

In sum, is the only issue here that needs work the switch from `User.uuid` to `User.user_account_uuid` as the user identifier carried by the SiS access token?

**Comment by bramleyjl** [comment]
Since the Refresh token also uses the `user_uuid` and uses it to generate the `user_uuid` used in the new Access token created during the `/refresh` call we should probably change both over to `user_account_uuid` at the same time.

**Comment by bosawt** [comment]
Yeah I'm confused about this ticket as well. I agree with you that the biggest component of work is making `User.uuid = User.user_account.id`. However, that process is going to be a multi-ticket process. We have to switch over many existing tables that assume `user.uuid = idme_uuid/logingov_uuid` before we can make the switch for `user.uuid`

**Comment by bosawt** [comment]
(I originally tried `user.uuid = user.user_account.id` for SiS, but we had a few instances of services failing because of the difference in uuid expectations, so switched back to `idme_uuid/logingov_uuid` for now)

**Comment by joeniquette** [comment]
- refresh token can only be created or recreated if there is a valid matching session identifier in the postgres DB: app/services/sign_in/session_refresher.rb
  - user verification stored in redis, take verifier code to verify code challenge, this should prevent the creation of refresh tokens at scale with random CSP IDs

**Comment by joeniquette** [comment]
This will be mitigated once user account uuid is used in all locations (work TBD):
- two csps issuing uuids could cause a collision and thus allow a user to see data for another person. To mitigate this we are going to use the user accounts (new method) uuid instead of accounts table (old method)
