### ISSUE TITLE
Improve eslint enforcement 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#4199]
# Overview 

- It's easy for VFS teams to circumvent eslint rules in vets-website 
- disabling rules is sometimes necessary but should be subject to review by the platform team 

# Goals 

- make it easy for the platform team to review eslint rule exceptions 

# Potential tasks / approaches 

- use github approvals to enforce
  - add a github action / use github api to look for inline eslint configurations e.g. `eslint-disabled` 
  - add comment to PR that links to / calls out lines where eslint has been disabled in the change
  - update the PR to require review by the FE review group 
  - document eslint rules that should always be enforced 
- run eslint against two configs- one that has "must enforce" rules init that ignores inline configs and one that has rules that can be disabled at programmer discretion 

# Notes

This can't be done with eslint config without disabling all inline commands. Any additional eslint rule we could enforce could be circumvented with the inline commands.

**Comment by erikphansen** [comment]
> document eslint rules that should always be enforced

Or, on the flipside, document all instances where it's okay to disable a rule :) I mean, `eslint-disabled` exists for a reason. Sure it can very easily be abuse and has been in the past (don't even get me started on people who have disable prettier rules just because they didn't like them). But there are times when it makes some sense to disable a rule. And I think the case where we import an action creator and then want to pass it to a component via `mapDispatchToProps` is a place where it might be okay to disable it. Otherwise we're renaming things just to make our linter happy. I am _totally_ open to be told why that's actually a bad idea; I'm here to learn. But I think ESLint should be serving us and not the other way around.

**Comment by rianfowler** [comment]
@brandonrapp I think this is related to what Brooks is working on and we can probably link / close this ticket.
