### ISSUE TITLE
Cross links for FE <> QA Standards team

### ISSUE THREAD

**Issue by lianilychee** [department-of-veterans-affairs/va.gov-team#42116]
From Jesse Cohn.  He and I Slack Huddle'd about this.

### Description

I was looking at the organization of the developer docs and wondering if we could get some cross-links added?
- The "Frontend developer documentation" has "Frontend testing > Unit tests" but nothing regarding e2e tests
- "QA and accessibility testing" should include a link to the "End-to-end testing with Cypress" within the "Accessibility testing" section
- And the "Keyboard testing helper functions" should be linked within those sections above as well.
I know I can use the search to find those sections, but if I was newly onboarding, I may not know to look for these sections specifically,

### Relevant URLs
n/a

**Comment by laucon** [comment]
Jesse said, "The "Frontend developer documentation" has "Frontend testing > Unit tests" but nothing regarding e2e tests" I'm gonna need him to clarify. There is a page
<img width="1792" alt="Screen Shot 2022-06-13 at 12 1
<img width="234" alt="Screen Shot 2022-06-13 at 12 16 12 PM" src="https://user-images.githubusercontent.com/14806304/173398860-6075854b-e7f2-4e7a-994e-454c01678ce9.png">
5 21 PM" src="https://user-images.githubusercontent.com/14806304/173398853-3754790e-afaa-4a54-bbd5-daa1d4d0a5e9.png">
 called [Frontend testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/frontend-testing) that contains info about both unit tests and end to end tests. But underneath the menu where it says, Frontend testing, there are pages about unit tests but not pages about end to end tests.

**Comment by laucon** [comment]
Per: "QA and accessibility testing" should include a link to the "End-to-end testing with Cypress" within the "Accessibility testing" section.
I can add that. Sure. No problem.

**Comment by laucon** [comment]
Per And the "Keyboard testing helper functions" should be linked within those sections above as well.
I know I can use the search to find those sections, but if I was newly onboarding, I may not know to look for these sections specifically,.

I can add that. Sure. No problem.

**Comment by laucon** [comment]
I fixed the second 2 requests. On each page he mentioned, there is a list of children pages under parent pages. I didn't want to move these children pages and parent pages around, so I added a section where it says "See also" and then links to the 2 pages in question. Because you're right, they should be accessible there even if they're not children pages.

**Comment by lianilychee** [comment]
hey @cohnjesse  - We've addressed your final two bullets, and those changes have gone out in yesterday's Platform website deploy.

For your first bullet, Lauren and I are going to pull in some SMEs.  @laineymajor @rmessina1010 and @JoeTice @pjhill , Jesse Cohn, I believe from Benefits/Appeals, is asking:

> The "Frontend developer documentation" has "Frontend testing > Unit tests" but nothing regarding e2e tests

Can you five (Lainey, Ray, Joe, Peter, Jesse Cohn) clarify what is being asked?  And then, Release Tools or QA Standards addresses so it can go out in a subsequent Platform website deploy?

Thank you!

**Comment by vbellissimo** [comment]
Lauren is continuing the discovery of bullet point #1 in slack with Jesse Cohn and Peter Hill.

**Comment by laucon** [comment]
[Peter Hill](https://app.slack.com/team/UL40L1W94)  [12:10 PM](https://adhoc.slack.com/archives/C03LW7DBFMM/p1656346236553259)
Yeah, breaking products down into the two categories form or not-form is a fairly useful way to categorize products. We kinda sorta have these patterns documented in the Cypress docs, but they are not at the top level as the first branch in the decision tree. For example, [this page](https://depo-platform-documentation.scrollhelp.site/developer-docs/writing-an-end-to-end-test#Writinganend-to-endtest-Formtests) includes descriptions of how to name your test specs, the structure of tests within the files, and [points the document consumer](https://depo-platform-documentation.scrollhelp.site/developer-docs/writing-an-end-to-end-test#Writinganend-to-endtest-Formtests) to the [form tester documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/form-tester-utility) if their product is a form.
Do you think it would be useful to reorganize the documents into a decision tree that encourages certain patterns for products that are applications for benefits and other patterns if the product is for managing benefits?
+1
thanks
go-team-ad-hoc







[Jesse Cohn](https://app.slack.com/team/UMJMWKLA1)  [12:12 PM](https://adhoc.slack.com/archives/C03LW7DBFMM/p1656346324694139)
Yes definitely, and I would actually lead with these pages first so that folks get a primer when reading the docs about the best practices first before being shown how to set up a test

**Comment by laucon** [comment]
Hey! So I've parsed through the whole conversation. It sounds like Jesse and Peter want:
- A document explaining best practices for how to set E2E tests with examples of what a good E2E test looks like and some examples of what bad E2E tests look like.
This leads to more questions:
- Is this document in our team's scope?
- Who should write this document? Someone on our team? Someone on another team?

**Comment by vbellissimo** [comment]
@laucon Thanks for going through this. Let's ask our team tomorrow at stand-up what the process has looked liked for new content requests in the past. If we determine this new content is something for us to create, I can help figure out the level of priority.

**Comment by vbellissimo** [comment]
New documentation content request needs prioritization.
