### ISSUE TITLE
[Design, Research] 10-10EZ: Look at the 10-10EZ confirmation page

### ISSUE THREAD

**Issue by Dene-human** [department-of-veterans-affairs/va.gov-team#42321]
After the update is made to the 10-10EZ confirmation page content for accuracy  #42304

**Now let's look at it holistically**
1. What's up with the blue box "featured content"- should it be an alert?
2. What's up with the typography?
3. Is this page providing everything it needs- does it need new content and design?

[Design file](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/v/aeRYrv/a/zxvza3r/)

**Comment by nicko-amida** [comment]
The Content team completed their review of the [1010CG confirmation page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/44510) - these suggestions may also apply to the 1010EZ confirmation page.

**Comment by nicko-amida** [comment]
Here's the updated [1010EZ confirmation page](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dlRpem2), that incorporates applicable Content team feedback.

**Comment by jessicastump** [comment]
Figma file conversion note: this design was in the Sketch file but because it was not implemented this way, we are not migrating it as is. Image for reference / archive here:
<img width="414" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmdTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e33854351069ff4e1f7dd15dce1a66076c9d6491/Confirm%20page.png" alt="Confirm page.png" />
