### ISSUE TITLE
[Issue] Your military details should only allow Spouse and Child to apply to Ch. 35 on the Search Page

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#42472]
The Comparison Tool currently allows Veterans/users to select Veteran, Active Duty, National Guard / Reserves from What's your military status? drop down and allow them to select "Survivors' and Dependents' Educational Assistance (DEA) (Ch 35) on the [search page](https://www.va.gov/education/gi-bill-comparison-tool/?search=name&name=Philippines%20
). 

Spouse and Child are the only options eligible for CH 35.

Dev - Please make sure to disable/grey-out Ch 35 if their first choice is NOT Spouse or Child.

QA - Please validate the option is greyed-out when not selecting Spouse or Child.
QA - Please make sure all calculations works as expected. Please do a thorough comparison with production.

Thank you.

**Comment by hallihocine** [comment]
Ticket has been validated in staging: the DEA (Ch 35) benefit option is only active/selectable if the military status is: Spouse or Child. Otherwise it will be disabled/greyed out.

- DEA (Ch 35) benefit option is greyed out for Veteran/Active Duty/National Guard:
<img width="816" alt="Screen Shot 2022-06-08 at 4 22 38 PM" src="https://user-images.githubusercontent.com/86266024/172710270-1fe279e3-4017-4d72-ba5a-6f681626a513.png">

- DEA (Ch 35) benefit option is active/selectable for Spouse/Child:
<img width="784" alt="Screen Shot 2022-06-08 at 4 23 29 PM" src="https://user-images.githubusercontent.com/86266024/172710451-de3eb64e-1e10-4c89-b50b-e97d4d88a973.png">

**Comment by hallihocine** [comment]
- Test Run: 
https://dsvavsp.testrail.io/index.php?/runs/view/3292&group_by=cases:section_id&group_order=asc&group_id=5172
- Test Steps: 
[Your military details should only allow Spouse and Child to apply to Ch 35 on the search page.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/8864846/Your.military.details.should.only.allow.Spouse.and.Child.to.apply.to.Ch.35.on.the.search.page.xlsx)

**Comment by MitchLivingstone** [comment]
QA and UAT passed on 06/09/2022
