### ISSUE TITLE
[Spike] - Feature to allow veterans to opt into new features

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#42499]
## Background/Request
Currently when launching a new feature in VAOS to veterans, the only options are to release the feature to a percentage of users, a percentage of the time or to specifically name users.  When releasing the appointment list feature later this year, it is desired that once a veteran sees the new appointment list, they continue to see the new appointment list on subsequent visits.  This would only be possible if specific veterans were named in the user list.  There are two issues with this method, there is not an automated way to add veterans who wish to see the new appointment list as a named user and using this method would not scale.

### Goal
The goal of this spike is to investigate an alternative method to release a new feature in which veterans could opt into the new feature and continue to see that new feature on subsequent logins, even if they log in from different devices.

### Requirements to Consider
VA.gov had a previous function that was used to enroll veterans in a Beta application.  Veterans who signed up for the program were instructed to go to a URL where they could opt into the Beta program.  Doing so enabled them to see the new web pages and design.  This Beta signup feature was recently removed from the VA.gov website, but there may be features of this code that could be re-used.  The ticket to remove the feature is:

https://github.com/department-of-veterans-affairs/vets-website/pull/20971/files

Ideally a veteran would be prompted with an option to view the new functionality.  If they choose to view it, that choice would be saved, and they would see the new features on that visit and all subsequent visits.  The veteran would also have the option to leave the beta program and revert to the existing public website.

## Tasks
- Answer the following questions:
  - Q1: Could the previous Beta program code removed in the link above be used (in part) to track veterans that have signed up for the Beta program?
  - Q2: Where could we persist data on which veterans have signed up for the Beta program so that this feature could scale?

- Perform the following task:
  - T1: List any recommendations on methods for prompting the veteran to join the Beta, and include pros and cons.

## Time Box
24 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [x] **Attached to an Epic**
VAOS - Appointment List Improvements #38062
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by cferris32** [comment]
Backend findings:

Q1: Could the previous Beta program code removed in the link above be used (in part) to track veterans that have signed up for the Beta program?
A1: There may be potential to reuse some of this code - there appeared to be scaffolding in place for all the necessary UI elements, service calls, and analytics events. Will defer to a frontend website dev for additional analysis.


Q2: Where could we persist data on which veterans have signed up for the Beta program so that this feature could scale?
A2: Two general approaches seem possible in order to track veterans who want to opt in to new features.

Add a new field to the user data we can retrieve on a veteran, eg. "feature_opt_in", where the value will indicate if they have chosen to see new features. It can default to "no/false" then be switched to "yes/true" when a user takes the appropriate actions in the scheduling flow.
Pros - persists across different methods of using VAOS, scales well with new users opting in, very little manual overhead.
Cons - will also require work from our backend service teams to add field, subject to their priorities and backlog. May need additional discussions and coordination.

2. Utilize a cache that is more isolated to the frontend (vets-website/vets-api) that tracks names of users who opt into new features, essentially providing us with a user whitelist. Check the whitelist when features are loaded for the user.
Pros - requires work from less teams, data would be a little more accessible requiring less external calls.
Cons - less lightweight than option 1, in practice it may be more similar to the manually maintained whitelist which we want to move away from.

**Comment by ldelacosta** [comment]
BE analysis has been completed. A FE developer will need to review this spike.

**Comment by ldelacosta** [comment]
This ticket is not needed anymore. Closing it out. cc: @JRRoof
