### ISSUE TITLE
[SOCKS / Named] Duplicate DNS records prevent named from starting

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#42649]
## Description
SOCKS access can be affected when there are problems with internal DNS, resulting in an error like: 

`open failed: administratively prohibited
`

## Background/context 

- Automation exists to create DNS records needed for review instances (RIs)
- Duplicate DNS records are sometimes created in the zone: vetsgov-internal
- These duplicates prevent named from starting, due to config errors 

## Technical notes
_Notes around work that is happening, if applicable (optional, please delete if unused)_

---
## Tasks
- Investigate potential fixes 
- Implement fixes

## Acceptance Criteria 
- [x] _What are the specific things that must be true in order for this to be accepted?_

**Comment by jhouse-solvd** [comment]
Relevant PR when this was previously addressed: 

https://github.com/department-of-veterans-affairs/devops/pull/10827

There may be add'l edge-cases to account for.

**Comment by jbritt1** [comment]
This has only happened once since the original fix was implemented in an extremely rare case where two RIs were created at the exact same time with the exact same branch parameters. This has not been observed since this ticket was created in June. Closing, but happy to reopen / revisit if the issue arises again.
