### ISSUE TITLE
Remove content from tables on birth defect compensation rates page

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#42774]
## Issue Description
As part of our ongoing effort to remove unneeded tables from VA.gov for accessibility reasons, we need to rework the content on the [birth defects compensation](va.gov/disability/compensation-rates/birth-defect-rates/) rates page.

Once we take the content out of the current rates page, we should apply the same changes to the past rates pages in Drupal.

## Tasks
- [x] Rework content to remove from table
- [x] Copyedit (Megan)

## Acceptance Criteria
- [ ] Content is ready for OCTO-DE review

**Comment by katherine-fung** [comment]
This is ready for review: http://preview-prod.vfs.va.gov/preview?nodeId=993

**Comment by megzehn** [comment]
@bethpottsVADEPO this post is ready for your review. 

http://preview-prod.vfs.va.gov/preview?nodeId=993

Thank you!

**Comment by megzehn** [comment]
@bethpottsVADEPO - FYI, I made a word change on this one after talking with the team, because "disabling" felt odd. Please let us know if there are any issues. We're happy to discuss and roll back if needed. 

**Edit:** Changed "disabling" to "severe" within the ratings. For example, I changed "Level I (least disabling)" to "Level I (least severe)."

**Comment by RLHecht** [comment]
I created a second ticket for Beth's review, stakeholder review and publishing. I carried over Megan's note into the new ticket as well. Going to close this one out.

**Comment by megzehn** [comment]
quick update: we reverted back to the original language ("least disabling" instead of "least severe")
