### ISSUE TITLE
Design | Profile | Personal Information revisions | UAT Summary 

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#42896]
## Background

Complete summary for UAT

## Tasks
- [x] Create summary

## Acceptance Criteria
- [x] Publish summary and Sharon with PO and PM
- [ ] Post to Github research folder

## How to configure this issue
- Include practice area in title -- e.g., [Design], [FE], [BE]
- Include project/initiative name - e.g., Auth Profile: Address Change Messaging
- Add label for practice area (frontend, backend, design)
- Add label for project if applicable
- Assign to a Profile team member
- Associate with an Epic if applicable
- If creating for yourself: estimate work if enough info exists to do so

**Comment by SKasimow** [comment]
Hi @cgednalske - here's a new ticket for topline research summary. Feel free to edit/add to the tasks and ac.

**Comment by cgednalske** [comment]
Thanks @Samara-Strauss! That all sounds great.

> Add Remove button to give Veterans more autonomy over selections, particularly because some participants already had their Gender identity information auto-filled (see Finding [#12](https://github.com/department-of-veterans-affairs/va.gov-team/pull/12)).
> We're not doing this, as we don't have clearance from our stakeholders to do so. :( Can you change the wording to clarify that?

Oh bummer - wasn't sure if there was still the possibility of working towards this sometime soon :( I've clarified that is not something we're doing.

> I don't know if we need to meet. I think you can get tickets into the backlog for anything you can more immediately tackle (eg. updates to hint text; confirming character maximums or allowed characters, etc). However, we don't need to add tickets for things we can't do right now, like adding remove functionality, adding pronouns and sexual orientation, or adding an open text field for gender identity. Let me know if you have questions about what falls under can-do vs. can't-do.

Ok no problem! Will add tickets around those items and let you know if I have questions about others. 

> Also, I understand this report is lengthier than other UAT reports because we were assessing a lot of usability questions alongside testing functionality. However, I just want to make sure it's clear that if a (future) UAT session is mostly focusing on whether a feature works/doesn't work, the report will probably be much shorter, and that's OK! 

Absolutely! I agree this is definitely much longer than UAT findings would usually be - just lengthy in order to thoroughly document the findings related to our secondary goals for usability/content questions. I absolutely expect it to be a minimal format for future studies that are sticking to UAT only.

**Comment by SKasimow** [comment]
Thank you @cgednalske - awesome summary!

Do you want to grab a few minutes and go over what tickets are needed and then I'll create them?
