### ISSUE TITLE
[Design] Create MVP User Flow

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#42935]
## User Story
As a Veteran uses uses Mobile Check-in on my mobile device, I would like to easily submit my claim for travel re-imbursement when I check-in for my appointment so that I don't have to do it in another system.

## Tasks
- Synthesize 18F Research and Wireframes/Mocks
- Create User Flows for the 2 MVP options
- Present to and discuss with Stephen before we actually create prototypes
    - What is the MVP?

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 [Here are actually four different user flows for review](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da). 1 through 3 are shortened travel workflows directly connected to check-in. The differences are the transitions from check-in to travel. I have an opinion on which one might work best (if we want to narrow down our proposal), but I wanted to get your feedback.

I still need to work on the scoping, phasing, and pro/con list that we discussed earlier today.

**Comment by kristenmcconnell** [comment]
Beginning of the [user flow presentation,](https://docs.google.com/presentation/d/1V1y0JiqRv_wWMqQvmBi4GiMJ0UBwapJknZBpdSI6oAs/edit?usp=sharing) which we will use for discussions with Stephen and Patrick. I will continue to work on this presentation on Tuesday and ask for a review then.

**Comment by benbrasso-agile6** [comment]
I guess we'd have to solve for that same scenario within check in. Although, if someone submits multiple claims, maybe the clerks just only reimburse for one. So, maybe it doesn't need to get accounted for in the ux. Thinking aloud..

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 Option 4 is 18F's proposal. Check-in and travel are separate. Travel happens after an appointment when a separate SMS is sent. 

Good point about only filing once per day. Take a look at the changes that I just made to Option 4. It now shows all the appointments for the day in one box. I also removed the contact information step in Option 4.

Thanks for the assessment. I agree about Option 3. 

Option 1 and 3 are actually the exact same workflow except for the prominence of the CTA, which we can refine later.

I added an Option 5 to show the workflow that you proposed: contact info > emergency > next of kin > travel reimbursement > check in.

I see a possible problem with Options 2 and 5. They potentially require a Veteran to fumble around and scan travel receipts (which they might not have organized) in order to complete check-in.

**Comment by kristenmcconnell** [comment]
Finished the user flow presentation ([Google doc](https://docs.google.com/presentation/d/1V1y0JiqRv_wWMqQvmBi4GiMJ0UBwapJknZBpdSI6oAs/edit?usp=sharing) and [PDF](https://app.zenhub.com/files/133843125/bb2720af-8ffd-4b08-95ed-4d389e8d6a17/download)) and reviewed it with Ben. Will present to Stephen and Patrick on Friday.

**Comment by kristenmcconnell** [comment]
Based upon Friday's discussion, I updated the user flows. I came up with two possible options:
- [Verify identify > Contact info > EC > NOK > Travel reimbursement > Your Appointments > Check-in complete](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/v/2rlmAe/a/kaPaz5A/r/nZ5m14)
- [Verify identify > Contact info > EC > NOK > Your appointments > Check-in complete > Travel reimbursement](https://www.sketch.com/s/42a478e7-cb38-49e5-9500-9b21182873da/v/2rlmAe/a/dlAA519)

I posted this on [Slack](https://dsva.slack.com/archives/C022AC2STBM/p1657660604299739) to start discussions with the team.
