### ISSUE TITLE
Midpoint Review - design feedback - Profile Team | Bad Address Indicator

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#43076]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Great job on reworking the flow of this!

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**
- Make sure you user test with the on this page link and background only alert since they are slightly outside of our guidance but seem appropriate for this pattern.

**Should:**

**Consider:**

## Platform directions
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by SKasimow** [comment]
@cgednalske - here's Allison's feedback from today's review (I also added you to ticket).

cc @Samara-Strauss

**Comment by SKasimow** [comment]
Hi @allison0034 - thank you for your feedback., Just wanted to confirm that in your feedback above, you are just asking that we test what we reviewed with you Fri, correct? Just want to make sure I am not missing anything on this...

>Must:

Make sure you user test with the on this page link and background only alert since they are slightly outside of our guidance but seem appropriate for this pattern.

cc/ @cgednalske

**Comment by SKasimow** [comment]
Closing...
