### ISSUE TITLE
[BUG] [SPIKE] Disability Rating Effective Date Bug

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#43308]
## Spike Question

Can we identify the likely cause of this bug after investigating for two hours or less? What are the results? 

## What happened?
The Veteran is seeing incorrect information when they use the disability rating tool on VA.gov. Specifically, the Veteran is seeing "Invalid Date" in the "effective date" field. 

Typically when a Veteran is seeing incorrect information, it's because of some kind of inconsistency in their data across the various systems. When I sent this over to EVSS, they found a data mismatch and fixed it but the Veteran reported the problem had not been resolved. The EVSS helpdesk also shared this "CORP db has the proper ratings/dates, and in our logs we saw the correct response being sent to queries." 

## Specs:
- Device: (e.g. iPhone 8, Macbook): PC, iphone
- Browser: (e.g. Firefox, IE 11) chrome, firefox, safari
- Test User _(if applicable)_:

## Steps to Reproduce
- URL: https://www.va.gov/disability/view-disability-rating/
- Test User _(if applicable)_:

## Desired behavior
The user should see their disability rating. 

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by jacobworrell** [comment]
This is copy to a slack response, but recording here for posterity: 

Does anyone have the PII for this veteran? We ma not end up needing it, but I ask because it might end up being easier to isolate the issue if we can investigate the unique aspects of the individual's data records. Also, the ticket mentions that EVSS fixed a "data mismatch". More specifics about that might be helpful. Was that mismatch theoretically related to the "invalid date" error the veteran was receiving on the front end? And is it possible that once it was corrected, it did not appear that way to the veteran due to caching?

In addition to the information Sade asked for, it is always helpful to receive screenshots from the user related to what they're seeing on the front end.

Finally, in the ticket, the description of the bug suggests the veteran is seeing "invalid date" instead of the effective date for their decision. It doesn't say they can't see their disability rating.
But then in the Desired Behavior section, the tickets says "user should be able to see their disability rating". This is confusing. Is the veteran unable to see their disability rating?

**Comment by jacobworrell** [comment]
Response: 

_does anyone have the PII for this veteran?_  - Yes I do and can share it with you over encrypted email if you have a VA email.
_Also, the ticket mentions that EVSS fixed a "data mismatch"._ I can get more specifics but our team works closely with the EVSS team because these types of issues (missing information, wrong information, etc) are often caused by data inconsistencies across the various VA databases. I don't know what the data issue was here, they vary, but there was some type of issue they fixed. I can also ask the Veteran to clear their cache and see if that fixes anything.
_it is always helpful to receive screenshots from the user related to what they're seeing on the front end._We always ask for screenshots but Veterans don't always provide them. I reached out again asking for screenshots but he hasn't provided them.
_Finally, in the ticket, the description of the bug suggests the veteran is seeing "invalid date" instead of the effective date for their decision. It doesn't say they can't see their disability rating._That was a mistake on my part. As far as I know (because I haven't received screenshots) this is just a matter related to the effective date.

**Comment by jacobworrell** [comment]
@jerekshoe please explain what happened.
