### ISSUE TITLE
PACT Act content updates to health care hub pages

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#43391]
## Story

As a Veteran, I need to understand how the PACT Act affects my VA health care eligibility and services.

### Day 0: When law passes

**[Eligibility for VA health care](https://www.va.gov/health-care/eligibility/):** 
  - Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.
  - Change the bullet "You’re a recently discharged combat Veteran" to "You're a combat Veteran who separated from active duty within the past 10 years"
  - Change "5 years" to "10 years" in the "Active-duty service members and VA health care" related link description
  - Need to ask VHA partners if we need to make any other updates here (such as updates around service time period in Vietnam and other locations, post-911 service, or other radiation exposures)

**[Priority groups](https://www.va.gov/health-care/eligibility/priority-groups/):**
  - Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.
  - Change "5 years" to "10 years" in the Priority group 6 section
  - Need to ask VHA partners if we need to make any other updates here (such as updates around service time period in Vietnam and other locations, post-911 service, or other radiation exposures)

**[Active-duty service members and VA health care](https://www.va.gov/health-care/eligibility/active-duty/):**
  - Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.
  - Update 5 years to 10 years and note change per PACT Act

**[Operation Enduring Freedom Veterans health issues](https://www.va.gov/health-care/health-needs-conditions/health-issues-related-to-service-era/operation-enduring-freedom/):**
  - Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.
  - Update the step in disability to reflect burn pits

**[Iraq War Veterans health issues](https://www.va.gov/health-care/health-needs-conditions/health-issues-related-to-service-era/iraq-war/):**
  - Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.
  - Update the step in disability to reflect burn pits

**[Gulf War Veterans health issues](https://www.va.gov/health-care/health-needs-conditions/health-issues-related-to-service-era/gulf-war/):**
  -  Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.
  - Update the step in disability to reflect burn pits

**[Cold War Veterans health issues](https://www.va.gov/health-care/health-needs-conditions/health-issues-related-to-service-era/cold-war/)**
  -  Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.

**[Vietnam War Veterans health issues](https://www.va.gov/health-care/health-needs-conditions/health-issues-related-to-service-era/vietnam-war/)**
  -  Add the [Get the latest PACT Act updates](https://prod.cms.va.gov/block/179?destination=/admin/content/alerts%3Fpage%3D2) alert.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn @RLHecht. Notes above on what I'm doing on the different pages. Posting these as they're ready for you:

Health care eligibility: http://preview-prod.vfs.va.gov/preview?nodeId=31

Priority groups: http://preview-prod.vfs.va.gov/preview?nodeId=708

**Comment by DanielleThierryUSDSVA** [comment]
@megzehn @RLHecht Additional pages ready:

- Operation Enduring Freedom Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=15
- Iraq War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=13
- Gulf War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=12
- Cold War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=11
- Vietnam War Veterans health issues: http://preview-prod.vfs.va.gov/preview?nodeId=16

**Comment by megzehn** [comment]
Hi @DanielleThierryUSDSVA! Thanks for this work. I reviewed the changes, and they look good. I had a few questions/notes throughout that I'll leave here: 

[Eligibility for VA health care:](http://preview-prod.vfs.va.gov/preview?nodeId=31)

- @RLHecht said that you were going to look into whether it should be "separated... within the past 10 years" (language in the ticket) vs "discharged..." (currently in there).  

- Note: there's a nested bullet list that feels a little awkward. Is that worth revisiting another time? 

[Priority groups:](http://preview-prod.vfs.va.gov/preview?nodeId=708)

- I'm not seeing the PACT alert in here. Should it be in there? 

[Active-duty service members](http://preview-prod.vfs.va.gov/preview?nodeId=1005)

- I'm not seeing the PACT alert in here
- In the current alert box, the "[Visit our mental health site for transitioning service members](https://www.mentalhealth.va.gov/transitioning-service/programs.asp) goes to a 404 page. Do you know if there's a better link to use for that? I'm wondering if it should go here instead:  https://www.mentalhealth.va.gov/transitioning-service/resources.asp

[Operation Enduring Freedom](http://preview-prod.vfs.va.gov/preview?nodeId=15) 

- Looks good (note to myself to update redirects and add curly quotes before it goes live) 

[Iraq war Veteran issues](http://preview-prod.vfs.va.gov/preview?nodeId=13) 

- I think(?) this statement is still true once PACT Act passes, but I wanted to double check: "Infectious diseases: There are 9 infectious diseases related to Southwest Asia and Afghanistan military service. These are malaria, brucellosis, campylobacter jejuni, coxiella burnetii (Q Fever), mycobacterium tuberculosis, nontyphoid salmonella, shigella, visceral leishmaniasis, and West Nile Virus."

- otherwise this looks good

[Cold War Veterans health issues](http://preview-prod.vfs.va.gov/preview?nodeId=11)

- I uncapped "experiments" in this: "Edgewood/Aberdeen Experiments," because I didn't see it in the style guide or AP as a proper noun, but let me know if that's incorrect. 

[Vietnam War Veterans health issues](http://preview-prod.vfs.va.gov/preview?nodeId=16)

- This looks good. Note to myself to update the redirects.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @megzehn. Thanks very much for all of this!!

Eligibility for VA health care:

@RLHecht said that you were going to look into whether it should be "separated... within the past 10 years" (language in the ticket) vs "discharged..." (currently in there).

- Should be "discharged or released"

Note: there's a nested bullet list that feels a little awkward. Is that worth revisiting another time?
 - Yes!

Priority groups:

I'm not seeing the PACT alert in here. Should it be in there?
- Yes.


Active-duty service members

I'm not seeing the PACT alert in here
 - Let's leave it out because there's already an alert there.

In the current alert box, the "Visit our mental health site for transitioning service members goes to a 404 page. Do you know if there's a better link to use for that? I'm wondering if it should go here instead: https://www.mentalhealth.va.gov/transitioning-service/resources.asp

- Oh, thank you for catching this!! Yes, that looks right, update to that.

Operation Enduring Freedom

Looks good (note to myself to update redirects and add curly quotes before it goes live)
Iraq war Veteran issues

I think(?) this statement is still true once PACT Act passes, but I wanted to double check: "Infectious diseases: There are 9 infectious diseases related to Southwest Asia and Afghanistan military service. These are malaria, brucellosis, campylobacter jejuni, coxiella burnetii (Q Fever), mycobacterium tuberculosis, nontyphoid salmonella, shigella, visceral leishmaniasis, and West Nile Virus."

- Yes, this still looks right to me. Thank you!

Cold War Veterans health issues

I uncapped "experiments" in this: "Edgewood/Aberdeen Experiments," because I didn't see it in the style guide or AP as a proper noun, but let me know if that's incorrect.
Vietnam War Veterans health issues

This looks good. Note to myself to update the redirects.

**Comment by RLHecht** [comment]
This work was completed. Closing.
