### ISSUE TITLE
Education rewrites: Final copyedit and publishing of new rates pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#43553]
## Issue Description
Once we have stakeholder approval on the new education rates pages, we need to do a thorough copyedit with the pre-publishing checklist and publish the pages. 

When we publish these pages, we need to confirm the url and menu title is correct and add the page to the left nav. 

Mikki's ticket with updated IA info is here: #[42952](https://github.com/department-of-veterans-affairs/va.gov-team/issues/42952#issuecomment-1156924652). 

**Note:** We may publish these pages in 2 stages, depending on stakeholder approval. If so, we should keep this ticket open until we've completed all the rates pages.

**Rates pages:**

- [x] [Current VA education benefit rates](http://preview-prod.vfs.va.gov/preview?nodeId=938) (this is the landing page)
- [x] [Post-9/11 GI Bill (Chapter 33) rates](http://preview-prod.vfs.va.gov/preview?nodeId=1009)
- [x] [Montgomery GI Bill Active Duty (Chapter 30) rates](http://preview-prod.vfs.va.gov/preview?nodeId=5355)
- [x] [Montgomery GI Bill Selected Reserve (Chapter 1606) rates](http://preview-prod.vfs.va.gov/preview?nodeId=5449)
- [x] [$600 Montgomery GI Bill Buy-up program rates](http://preview-prod.vfs.va.gov/preview?nodeId=5572)
- [x] [Chapter 35 rates for survivors and dependents](http://preview-prod.vfs.va.gov/preview?nodeId=5496)
- [x] [Fry Scholarship rates](http://preview-prod.vfs.va.gov/preview?nodeId=49549)

**Past rates pages:**
- [x] [Past rates for Post-9/11 GI Bill](http://preview-prod.vfs.va.gov/preview?nodeId=49728)
- [x] [Past rates for Montgomery GI Bill Active Duty](http://preview-prod.vfs.va.gov/preview?nodeId=49445)
- [x] [Past rates for Montgomery GI Bill Selected Reserve](http://preview-prod.vfs.va.gov/preview?nodeId=49449)
- [x] [Past rates for Chapter 35](http://preview-prod.vfs.va.gov/preview?nodeId=49484)
- [x] [Past rates for the Fry Scholarship](http://preview-prod.vfs.va.gov/preview?nodeId=49719)

**Program pages with cross linking to current rates pages (copyedit only the related links unless otherwise noted next to the link below):**
- [x] [Post-9/11 GI Bill (Chapter 33)](http://preview-prod.vfs.va.gov/preview?nodeId=935)
- [x] [Montgomery GI Bill Active Duty (MGIB-AD)](http://preview-prod.vfs.va.gov/preview?nodeId=932)
- [x] [Montgomery GI Bill Selected Reserve (MGIB-SR)](http://preview-prod.vfs.va.gov/preview?nodeId=934)
- [x] [Survivors' and Dependents' Educational Assistance](http://preview-prod.vfs.va.gov/preview?nodeId=950)
- [x] [Fry Scholarship rates](http://preview-prod.vfs.va.gov/preview?nodeId=49549)
- [x] [$600 Buy-Up program](http://preview-prod.vfs.va.gov/preview?nodeId=933)

**Note:** We will NOT publish this page at this time. Please keep it in draft:
- [Post-9/11 GI Bill MHA rates](http://preview-prod.vfs.va.gov/preview?nodeId=47411)

We will create a separate ticket for publishing the other migrated education pages once they're sent to stakeholders.

### New pages to copy edit and publish
- [x] Final copyedit of **Current VA education benefit rates** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Current VA education benefit rates** (Megan)
- [x] Final copyedit of **Post-9/11 GI Bill (Chapter 33) rates** (Megan)
- [x] Final copyedit of **Past rates for Post-9/11 GI Bill** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Post-9/11 GI Bill (Chapter 33) rates** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Past rates for Post-9/11 GI Bill** (Megan)
- [x] Final copyedit of **Montgomery GI Bill Active Duty (Chapter 30) rates** (Megan)
- [x] Final copyedit of **Past rates for Montgomery GI Bill Active Duty** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Montgomery GI Bill Active Duty (Chapter 30) rates** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Past rates for Montgomery GI Bill Active Duty** (Megan)
- [x] Final copyedit of **Montgomery GI Bill Selected Reserve (Chapter 1606) rates** (Megan)
- [x] Final copyedit of **Past rates for Montgomery GI Bill Selected Reserve** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Montgomery GI Bill Selected Reserve (Chapter 1606) rates** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Past rates for Montgomery GI Bill Selected Reserve** (Megan)
- [x] Final copyedit of **$600 Montgomery GI Bill Buy-up program rates** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **$600 Montgomery GI Bill Buy-up program rates** (Megan)
- [x] Final copyedit of **Chapter 35 rates for survivors and dependents** (Megan)
- [x] Final copyedit of **Past rates for Chapter 35** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Chapter 35 rates for survivors and dependents** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Past rates for Chapter 35** (Megan)
- [x] Final copyedit of **Fry Scholarship rates** (Megan)
- [x] Final copyedit of **Past rates for the Fry Scholarship** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Fry Scholarship rates** (Megan)
- [x] HOLD UNTIL ALL PAGES ARE COPYEDITED Publish **Past rates for the Fry Scholarship** (Megan)
- [ ] ~Final copyedit of MHA rates page (Megan)~
- [ ] ~HOLD UNTIL ALL PAGES ARE COPYEDITED Publish MHA rates page (Megan)~
- [x] Set up rates pages in left nav (Megan/Randi)

### Updates to existing benefit pages to copy edit and publish
- [x] Final copy edit of [Post-9/11 GI Bill (Chapter 33)](http://preview-prod.vfs.va.gov/preview?nodeId=935) (1/ changes to the bottom of the page--I moved links and content from the last H2 into the related links box and intentionally left out the R&S link, 2/ minor changes to content in the H2 up higher on the page "How does VA determine my monthly housing allowance (MHA)?")
- [x] Publish Post-9/11 GI Bill (Chapter 33)
- [x] Final copy edit of [Montgomery GI Bill Active Duty (MGIB-AD)](http://preview-prod.vfs.va.gov/preview?nodeId=932) (changes to the bottom of the page--I moved links and content from the last H2 into the new related links box; also moved the current payment rates link from the "How can I use..." H2 to the "How does VA determine..." H2)
- [x] Publish Montgomery GI Bill Active Duty (MGIB-AD)
- [x] Final copy edit of [Montgomery GI Bill Selected Reserve (MGIB-SR)](http://preview-prod.vfs.va.gov/preview?nodeId=934) (changes to the bottom of the page--I moved links and content from the last H2 into the new related links box; also deleted the current payment rates link from the "How can I use..." H2 because it's already on the page up higher in the "What benefits can I get" H2)
- [x] Publish Montgomery GI Bill Selected Reserve (MGIB-SR)
- [x] Final copy edit of [Survivors' and Dependents' Educational Assistance](http://preview-prod.vfs.va.gov/preview?nodeId=950) (In "What benefits can I get" H2, changed the label and url for the text link going to current rates; added related links box at bottom of page
- [x] Publish Survivors' and Dependents' Educational Assistance
- [x] Final copy edit of [Fry Scholarships](http://preview-prod.vfs.va.gov/preview?nodeId=951)
- [x] Publish Fry Scholarships
- [x] Final copy edit of [$600 Buy-Up program](http://preview-prod.vfs.va.gov/preview?nodeId=933) (edits to the H1 and throughout the page--and a new related links box)
- [x] Publish Montgomery GI Bill $600 Buy-Up program

## Acceptance Criteria
- [x] All migrated rates pages are live on VA.gov
- [x] All migrated rates pages are displayed in the left nav

**Comment by bethpottsVADEPO** [comment]
Hi @megzehn! When this work is ready for you (I'm still waiting for feedback or a thumbs up from SMEs), I think it would be good for you to check consistency across all the pages for certain elements like the past rates section (I think there might me an em dash in some cases for the range and a dash in other cases). Also, check the related links boxes to see if those are generally all done the same way--see if anything jumps out at you. You don't need to spend tons of time on this, but I'm mentioning it since this ticket is set up to walk through each page as a distinct unit and publish each one separately rather than in one fell swoop. Also, we have to publish these all simultaneously because of all the crosslinking between them or we'll have broken links. 

I'm going to amend the tasks so that you hold to publish until you're done copyediting all the pages. They can't publish separately.

**Comment by megzehn** [comment]
Got it! Thanks for the heads up, @bethpottsVADEPO. Super helpful.

**Comment by RLHecht** [comment]
@megzehn I just added all the past rates pages to this ticket too. Since the content is the same as it is on the current pages (except for the numbers) it might be helpful to have them open at the same time, so if you find something to correct on the current rates page you can go in and make that same update on the past rates page. 

Since the past rates pages were cloned from the current pages, you shouldn't have to do a full copyedit of the page separately (though it would be good to spot check some of the numbers against the legacy pages to confirm they are correct).

**Comment by bethpottsVADEPO** [comment]
Couple notes for you to try to head off questions that will come up for you:
- $600 Montgomery GI Bill Buy-Up program (shortened version of this is ok to use: $600 Buy-Up program)
- On that buy-up page: PL rule bending happened--please leave "contributed" as is for clarity (because the Veteran pays into the program then VA pays them--all the use of "pay" got to be too much)
- Intros for the past rates pages: I decided to snug the text link up with the preceding text rather than bump it down a line. We generally bump links down to their own lines, but sometimes to make a stronger connection with the preceding text, we can do it this way instead. What we definitely avoid is linking groups of words embedded within a sentence.

**Comment by bethpottsVADEPO** [comment]
@megzehn Couple more notes for you!
- We decided to hold on publishing the Monthly Housing Allowance (MHA) page, so if you see any text links or crosslinking to that, please delete the link. You'll see that in a couple places where we want to link to MHA info, there are jump links to the Post-9/11 GI Bill H2 about housing allowance (that's all we're going to launch with). If you find a place where you think we should add another link like that pointing to the Post-9/11 GI Bill H2 about MHA, would you ping me to verify?
- Noting here something mentioned in slack... there's a definition for "prorated" that's now in the Chapter 35 page. If you see "prorated" anywhere else, would you add in the definition if it's missing?

**Comment by katherine-fung** [comment]
Hi @megzehn - I think you may already have the links for the Chapter 35 pages, but I'm putting them here: 

Current rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=5496 

Past 2022 rates page: 
http://preview-prod.vfs.va.gov/preview?nodeId=49484

**Comment by katherine-fung** [comment]
Hi @megzehn - here are the MGIB rates pages for copyedit. 

MGIB-AD 
http://preview-prod.vfs.va.gov/preview?nodeId=5355 

MGIB-SR 
http://preview-prod.vfs.va.gov/preview?nodeId=5449 

I made the changes the stakeholders discussed with us last Wednesday (below for reference) 

On MGIB-AD page:

-	Deleted “without a break” after less than 3 continuous years 
-	Changed “a” to “the $600 buy-up program.” Said "...kicker (sometimes called “college fund”)" 
-	For NCD example, used "program" instead of "term"
-	Added “per week” after "clock hours"

On MGIB-SR page

- Took out the mention of the buy-up program (there isn't one for MGIB-SR)

**Comment by katherine-fung** [comment]
Hi @megzehn, 

The Post-9/11 GI Bill rates page is ready for copy edit: 

http://preview-prod.vfs.va.gov/preview?nodeId=1009 

Just a note that in last week's meeting, Jodie had said they would get back to us with information about certain eligibility tiers excluding training time from the time that counts as part of your service for benefits. We don't have that information yet, but I will follow up with them today when I follow up about something else.

**Comment by megzehn** [comment]
Thanks, @katherine-fung! 

Are you able to make these same changes on the past rates pages? 

- [Past rates for Post-9/11 GI Bill](http://preview-prod.vfs.va.gov/preview?nodeId=49728)
-  [Past rates for Montgomery GI Bill Active Duty](http://preview-prod.vfs.va.gov/preview?nodeId=49445)
-  [Past rates for Montgomery GI Bill Selected Reserve](http://preview-prod.vfs.va.gov/preview?nodeId=49449)

I made _most_ of the updates on MGIB AD past rates (up until Flight and correspondence training, because I wanted to confirm with you where that lives). 

MGIB SR past rates and Post-9/11 GI Bill still need updates.

**Comment by katherine-fung** [comment]
Thanks @megzehn! I made the changes on the 3 past rates pages for Post-9/11 GI Bill, MGIB-AD and MGIB-SR. 

For the MGIB-AD past rates, in order to add the 1 sentence the stakeholders wanted ("you must submit..."), I broke correspondence and flight training into their own sections. This matches the MGIB-AD current rates style.

**Comment by katherine-fung** [comment]
Hi @RLHecht @megzehn,

The Fry Scholarship rates pages are ready for copyedit:

current rates: 
http://preview-prod.vfs.va.gov/preview?nodeId=49549 

past rates: 
http://preview-prod.vfs.va.gov/preview?nodeId=49719

**Comment by katherine-fung** [comment]
@RLHecht @megzehn, 

The education rates landing page is also ready for copy edit: 

http://preview-prod.vfs.va.gov/preview?nodeId=938

**Comment by katherine-fung** [comment]
@RLHecht @megzehn - 

The Post-9/11 GI Bill program page is ready for copy edit. 

http://preview-prod.vfs.va.gov/preview?nodeId=935 

We mainly changed the "How does VA determine my monthly housing allowance (MHA)?" and "How can I get more information?" section, though there are other tweaks throughout.

**Comment by megzehn** [comment]
Confirming that all pages have been copy edited!

**Comment by RLHecht** [comment]
All the rates pages and these program pages have been published! Moving this to validate. Will close once the program pages are live.

**Comment by RLHecht** [comment]
Closing!
