### ISSUE TITLE
[Research] Create the Optimal Workshop Survey

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#43576]
## Background
UX has questions about what appointment data is really important to display to Veterans at different points throughout the pre-check-in and check-in process. With the additional data that will be available after VAOS V2, this is even more of a question. We would like to do a remote card sort and 5 sec impression test with Veterans to try and answer this question.

## Tasks
- [x] Create the questions for the survey for 4 scenarios
    - use the matrix tool
- [x] Do a pilot

**Comment by loripusey** [comment]
@kristenmcconnell @benbrasso-agile6 can you point this so we can pull it into the sprint tomorrow?

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 Here is a [preview link](https://dj540s05.optimalworkshop.com/questions/0e10i43k) to the study. I think that it might be too long. Maybe we need to break it up into two studies: check-in and pre-check-in. If you agree, then I can quickly do that on Tuesday.

cc @loripusey

**Comment by kristenmcconnell** [comment]
@loripusey Thanks for catching the typo. We were wondering if there was any need for the information to be context specific, which was part of the reason for this test. For instance, we already know that date doesn't make as much sense for day of an appointment compared to pre-check-in. Is there anything else that should be in pre-check-in and not check-in? I agree that I should reword the question and remove "pre-check-in." What about "answer questions in order to prepare for your appointment" or something like that? I was going to compare our results to the VAOS and mobile app study. Where can we all show the same info in the same order and where do we need to purposely deviate?

I forgot that Ben isn't back until tomorrow. I'll see if Nira could review it as well.

**Comment by kristenmcconnell** [comment]
After talking through the study with Nira, we determined that it is too long. I'm going to quickly separate this into two studies: pre-check-in and check-in. It should take me that long.

**Comment by benbrasso-agile6** [comment]
I do sort of agree with one of Lori’s points. If we can get feedback on what data is important agnostic to the step they’re in (e.g., pre vs day of), then that might be good enough. But, if we can get feedback on pre vs day of, without confusing them, I think that’s good to. 

I haven’t looked at the survey yet, but wanted to provide a quick thought in case it’s helpful. 

I’m cool proceeding with however you think is best.

**Comment by kristenmcconnell** [comment]
I made all the changes from Nira and divided this into two studies:
- pre-check-in ([research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/research/2022-09-precheckin-appointment-info-prioritization/research-plan.md) and [draft survey](https://dj540s05.optimalworkshop.com/questions/d1210c5a73e15adae71c744812db1313))
- check-in ([research plan](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/2022-09-checkin-appointment-info-prioritization) and [draft survey](https://dj540s05.optimalworkshop.com/questions/0e10i43k))

@benbrasso-agile6 Would you be able to do one final walkthrough?

**Comment by benbrasso-agile6** [comment]
Here is feedback on the pre-check-in survey. Most of this feedback can be used for day of survey as well. 

**Welcome page** 

Your responses will help us understand what information is most important to you when confirming your appointment with the VA a few days before your actual appointment. 

^ I think "information" provides enough context vs. "appointment information." And, tried to use "confirming your appointment with the VA" as a way to describe pre-check-in. 

**Intro on the question**

Pretend that it is 3 days before your appointment and the VA has texted you a link to confirm your appointment. You just finished answering questions on your smartphone to prepare for your appointment, such as reviewing your contact information and medication list.

^ Felt like this needed something referencing the VA and that you'll be texted something to be able to complete pre-check-in. 

How important is each of the following to you to see when confirming your appointment with the VA? The information should help you feel good about confirming your appointment and knowing what to do on the day of your appointment.   

^ Rephrased a bit to ask "how important" vs. "what's important?" And, removed details that I think Veterans will get hung up on understanding. E.g., removed mention of confirmation page and pre-check-in. 

**List of information**

Address. Who's address? Appointment address or your own address? 

Does seeing the examples of clinic names make it less helpful? I feel like it does. I might recommend removing the examples. 

Date. Today's date? Date of the appointment? 

Instructions on how to attend video or telephone appointments. This one throws me off a bit because the majority of appointments are for in person. So, if I'm ordering this for an in-person visit, I would probably but this at not important at all. I think we need to think through this a bit more. My gut is to remove this. Or, maybe it somehow needs to be paired with directions to appointment.  

Maybe change Patient name to Patient's name to be consistent with Provider's name

Time. Appointment time

Type of care. What is type of care? This is hard to rank without knowing what it is. Definitely include examples.  

Weekday. Does that mean, day of appointment? If so, would try day of appointment instead. 

Suggestions for clearing up type of care vs. appointment type, etc. 

- Reason for visit (this is conditions, symptoms, etc.) 
- Appointment type (this is f/u, vaccination, etc.) 
- Visit type (this is modality)
- Specialty OR Type of care (e.g., cardiology, primary care, etc.) 

**Other comments**

The validation isn't great lol. I pressed continue, but it didn't scroll me up. Any options around validation? Maybe you need a note at the top of the page in the intro to please answers all questions. 

Remove second question/page. 

Need to rephrase the validation message on the promo code question. 

I would maybe recommend randomizing the list of questions to rank. Is that possible?

**Comment by kristenmcconnell** [comment]
Made the updates. Sent to Ben for a pilot run through. Then, will send out to Stephen for approval.

**Comment by kristenmcconnell** [comment]
Approval message sent via [Slack](https://dsva.slack.com/archives/C02GXKL8WM6/p1662661414816509).

**Comment by kristenmcconnell** [comment]
Approval received in that Slack message.

Research repo tickets created: [check-in](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/179) and [pre-check-in](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/180).

**Comment by kristenmcconnell** [comment]
Sent for [research review](https://dsva.slack.com/archives/C0216PL32HJ/p1663001453420169).
