### ISSUE TITLE
[Spike] - Grafana Discovery for VAOS V2

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#43608]
## Background/Request
Grafana is currently used to monitor the health of VAOS.  The current VAOS dashboard tracks the following metrics:
- Sum of Errors
- Breakers Skipped
- Sum of VAMF Failures
- Sum of VAMF Partials
- Average VAOS Latency
- Request Rate

These metrics are designed for the current backend architecture with VAOS connected to VAR-RES.  When VAOS V2 goes into production a new dashboard will be required to monitor the new architecture.

### Goal
1) Document what each metric above is monitoring and at what threshold an alert is triggered
2) Determine if these metrics still make sense to monitor with VAOS V2
3) Identify any additional metrics that should also be monitored with VAOS V2

### Requirements to Consider
Link to current dashboard:  https://grafana.vfs.va.gov/d/EmC4pa6Wz/vaos-alerts?orgId=1&from=now-24h&to=now

## Tasks
- Answer the following questions:
  - Q - What does the current Grafana VAOS dashboard monitor and when does it trigger an alert?
  - Q - Should these same metrics be tracked for VAOS V2?
  - Q - If so, what are the equivalent events in VAOS V2 to monitor?
  - Q - What should we be monitoring that we are not?

## Time Box
10 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [X] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by cferris32** [comment]
VAOS Alerts V0 Dashboards:

*- Sum of Errors
  - tracks number of error responses raised from the controllers
  - watches over a rolling 10 minute interval
  - organized by controller, action, and response code
  - would be valuable to continue tracking as it allows a quick zoom in on errors we raise from vets-api
  - utilize VAOSLogging and monitoring classes, as well as additional rails logger statements at the controller level to continue tracking this info

- Breakers skipped alert
  - alerts when the breaker flips, which blocks extra http calls when the request rate exceeds a certain threshold
  - tracks over a rolling 10 minute interval
  - may be valuable to continue tracking if we want a notice for high traffic scenarios
  - utilize VAOSLogging and monitoring classes to continue tracking this info

*- Sum of VAMF failures
  - tracks number of error responses received from downstream services
  - rolling 10 minute interval
  - oragnized by http status, http interval, and which endpoint raised the error
  - would be valuable to continue tracking as it lets us quickly identify errors that originate due to a downstream service as opposed to our own error handling in vets-api
  - use rails logger statements to echo error responses returned to the controller, which will feed into Loki, potential to use VAOSLogging and monitoring classes as well

- Sum of VAMF Partials
  - tracks partial error responses from downstream services
  - organized by code, source, and message summary
  - may be valuable to continue tracking as it differentiates the partial errors from other responses

*- Average VAOS Latency
 - calculates average latency of VAOS endpoints over a rolling 10 minutes interval
 - would be valuable to continue tracking as we have been working to optimize response times and this will help us keep tabs on that
 - utilize VAOSLogging and monitoring classes to continue tracking this info
 - this is also tracked with logging via the middleware, which won't change between V0 and V2, meaning that carrying this dashboard over should be relatively easy

- Request Rate Alert
  - tracks how many requests come in over a rolling 1 minute interval
  - may be valuable to continue tracking as it easily shows unusual upticks/downticks in VAOS request activity

As a general note for all these dashboards, they currently feed into prometheus which we learned will be supported through the V2 launch, meaning it should be feasible to carry most of these over without too much overhead. At an undetermined point in the future, DataDog will take over as our primary data stream, at which point we'll want to work on updating all our prometheus and loki logs to use DataDog. This will not affect monitoring for the V2 launch.
