### ISSUE TITLE
Communicate changes to dev and localhost mock data for Sign in Service

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#43666]
We need to inform all dev teams that dev and localhost environments will not work the same for sign in service as it does currently for SSOe. We will attempt to assist with the fact that the mock data will not match the ssoe data, but devs can add in new user entries for mock data for sign in service if they wish.

**Comment by bosawt** [comment]
- Pre-sign in service change, authentication would redirect through IAM (eauth), to the CSP (ID.me/Login.gov), and back to VA.gov. This redirect flow still occurred on localhost, and so the calls to eauth, and to the CSP, are 'live', they make real calls to the IAM and CSP test stacks. This means IAM was able to leverage the CSP test stack data to make a call to MPI, and then store this information in a SAML header for the redirect back to localhost vets-api. So you would see 'real' MPI test stack data for an authenticated user
- MPI queries straight from vets-api are mocked on localhost. This is necessary because MPI can only be accessed on the VA network, so our local machines don't have direct access, even to the MPI test stacks. These mocked MPI queries are located in vets-api-mockdata repository. The way MPI queries are mocked, is by saving the id used to query a record as a filename. For example, an MPI query by ICN for icn: `1012853893V362415`, would be stored in this file: `mvi/profile_icn/1012853893V362415.yml`. An MPI query by idme_uuid for idme_uuid: `ec8be01aa8d744979ff6df40ff2037bf`, would be stored in this file: `mvi/profile_idme_uuid/ec8be01aa8d744979ff6df40ff2037bf.yml`
- Sign In Service will introduce two changes to the way localhost user data is supplied. First, we no longer get SAML headers from IAM, so we will fully rely on MPI for user information. This means localhost will be completely mocked with records from vets-api-mockdata, instead of a combination of mocked/not-mocked data. Some records that may not have been mocked will now need to be mocked to continue developing using them on localhost. Second, traditionally we preferred an ICN MPI query, but this will change to a CSP uuid (idme_uuid/logingov_uuid) MPI query. This means that many users mocked in vets-api-mockdata for an ICN value (`1012853893V362415.yml`) will need to have these mock files copied to the equivalent CSP uuid file (`ec8be01aa8d744979ff6df40ff2037bf.yml`)
- This impacts the localhost and dev stacks. This does not impact staging stack, as it is not mocked at all (also does not impact production)

**Comment by joeniquette** [comment]
announced in three engineering channels on 7/25/22

**Comment by nsoutouras** [comment]
Added to the pinned post in #VSP-Identity on 7/26 and also communicated in #VFS-all-teams
