### ISSUE TITLE
Sign-in Service: External Issue Tracker

### ISSUE THREAD

**Issue by nsoutouras** [department-of-veterans-affairs/va.gov-team#43757]
# Description 
This is the primary place for users external to the VSP Identity Team to report bugs and issues with the sign-in service.  Please leave anything as a comment on this ticket with the following details:

Instructions for how to use the new sign in service can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity/Sign-In%20Service/Sign-in-service_Web-OAuth.md#sign-in-service-will-provide).

- Description of the issue
- Reproduction steps
- Expected behavior
- Actual behavior
- username of test user
- exact time and date of error (for log searching)
- error messages seen (screen capture preferred)

**Comment by Samara-Strauss** [comment]
Hi all -- I am just getting back from vacation today, and therefore just seeing the announcement about the new sign-in update. I tested our profile, and I am seeing serious, launch-blocking issues with the new sign-in flow (http://staging.va.gov/sign-in/?oauth=true) that I am not seeing when I go to staging with https://staging.va.gov/. 

Here are the issues I am seeing. Specifically, I tested with user 36:

- I can not save information in the profile with /sign-in/?oauth=true. I get an error with forms that otherwise work just fine in "regular" staging.
- The direct deposit feature has a gate for DS Logon and MHV users that tells them to log in with ID.me or Login.gov. I do not see this gate in "regular" staging when I log in with user 36. However, I do see it when I sign in with /sign-in/?oauth=true even though I am logged in with an ID.me user.
- The notification preferences section of the profile just doesn't work with /sign-in/?oauth=true when it does work in "regular" staging.

Effectively, the profile is really broken, with this new flow. Please do not launch these updates without working with our team to figure out what is causing these issues. Thanks. cc/ @SKasimow @cgednalske @adamwhitlock1 @tpharrison

**Comment by tlei123** [comment]
**Major os-/browser-agnostic bug**: 2FA screen-pair repeated. see example video below: 
https://images.zenhubusercontent.com/133843125/2f236317-77cf-4c65-805e-d525459ccb4a/stg_new_sign_in_flow_2fa_repeated_220729.mp4

**Comment by joeniquette** [comment]
This phase is complete.
