### ISSUE TITLE
Design Intent - IA Feedback - VAOS, VA Online Scheduling, Appointment List Feature

### ISSUE THREAD

**Issue by jimuhh** [department-of-veterans-affairs/va.gov-team#43777]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
-

## Feedback
- **Must** = the feedback must be applied
- **Should** = the feedback is best practice
- **Consider** = suggestions/enhancements

**Must:**

- Replace "back" link on [Details page](https://www.figma.com/proto/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?page-id=389%3A28395&node-id=389%3A28828&viewport=700%2C371%2C0.12&scaling=min-zoom&starting-point-node-id=389%3A28711&show-proto-sidebar=1) with standard breadcrumb
- Find alternative, more user-friendly  term to replace "pending" 

**Should:**
- Consult with Design team on advisability of using [tab component ](https://design.va.gov/components/tabs)for links above table that read "Pending, Canceled" 

**Consider:**
- Getting feedback from Design System team about non-standard application of responsive table component and new "In real life" building icon to see if these might be worth adopting in future Design System iterations. 
## Platform directions
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by outerpress** [comment]
Thanks @jimuhh !

One follow-up question: what are the benefit of tabs vs. links in this scenario? cc: @allison0034 

We went with links because requests, upcoming appointments, and past appointments all represent different Veteran tasks (roughly outlined below), with viewing upcoming appointments being the most important. We're betting that by separating them, we can better build out these pages to support those tasks in the future. 

For example, we could offer a link off to all medical history on past appointments, or structure requests to make it easier to understand the status (currently pending or canceled).

**Upcoming appts**
* Plan for my appointment day
* Check that VA has my information right

**Pending appts**
* Check that VA is following up on my requests

**Past appts**
* Check my history
* Plan future appts

**Comment by outerpress** [comment]
Gotcha @allison0034 , thanks for the context!

**Comment by ldelacosta** [comment]
No further action needed. Closing out the ticket.
