### ISSUE TITLE
RFC to summarize solution to race condition issue

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#43864]
**PROBLEM STATEMENT**
Autonomous deployment initiative is blocked by a race condition issue. An RFC is being completed to propose next steps/architecture and will be disseminated to appropriate parties for comment and decision.

Current proposal summary:
- Update the vets-website build to store assets in a subdirectory for changed app builds
- Update the content-build to not hardcode the app assets to load on a page
- Figure out how to handle running CI for changed app builds and full builds with this new setup (likely utilize yarn workspaces)

**ACCEPTANCE CRITERIA**

- [x] Agreement on next steps/architecture for autonomous deploys
- [ ] Go-ahead from architecture workgroup

**Comment by theodur** [comment]
Draft PR for the RFC: https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/32

**Comment by theodur** [comment]
After creating the RFC and discussing the issues mentioned in it, we decided to take a simpler approach by using the process we have now for dev & staging changed app deploys. One of the main concerns was the frequent syncing of application bundles with outdated global bundles, breaking applications in production. After some consideration, it's unlikely to happen often, since global bundles don't change often. To handle the race condition, we will add logic to the `Deploy` job in the CI workflow to pause or stopped a changed app deploy if the daily production deploy is happening.

As a result, I closed the RFC since we're no longer pursuing the solutions outlined in it at this time.
