### ISSUE TITLE
STEM: Review stats from EDU

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4395]
- [x] Remind Luke to send these
- [x] Reasons for rejections
- [x] Counts of applications / rejections
- [ ] Document notes, Q’s for stakeholders
- [x] Share additional questions for EDU Buffalo team w EDU (Jan 2)
- [ ] Any commonalities in the individuals being rejected 

- [x] TM
- [x] CC
- [x] AK

**Comment by amyknox** [comment]
From EDU... 

Data update:

1.	So it appears that the only way to view the answers to the questions would be to go into each individual applicant’s record in TIMS and transcribe that data into a spreadsheet or database.  Currently the application responses are captured into TIMS, but you cannot export or view all the applications…
  a.	Recommendation: we have received 10358 applications.  I do not recommend that we go the manual look up and transcribe route.  I recommend we try to have a way to capture this data going forward with the changes we are going to make.
2.	Ricardo seemed to think that response data would be available through Google Analytics.  I said I don’t think that is captured.
3.	High level data as of 12/19/19:... About 30% are denied b/c they are not in an eligible program and another 30% because they have not exhausted their benefit.

**Comment by amyknox** [comment]
![image.png](https://images.zenhubusercontent.com/5b51ea398c1a7628d9218a42/d0f1c07e-e636-4539-83a4-fcf4a2c2cd6e)

**Comment by ccruzgra** [comment]
@amyknox  I'll document what they shared with us in GitHub.

**Comment by ccruzgra** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/research/wizard-update/discovery-artifacts/EDU-stats-for-wizard-1995.md
