### ISSUE TITLE
Error messaging and recovery content from Benefits-Team 1

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#44006]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
The Notice of Disagreement form is experiencing some PDF upload errors that we currently don't have a solution for, but we need to message the error with helpful, but not overly prescriptive or technical guidance. Ticket [is here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43037) for more info.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful: https://github.com/department-of-veterans-affairs/va.gov-team/issues/43037

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale
-	Designer: Pam Hastings
-	FE engineer: Robin Garrison
-	Product/team Slack channel:https://join.slack.com/share/enQtMzc4NTQzNTgwMzEzNy1hZWQwZWRjYWY2OTNkN2ZiZDlhZTMwYzRlZDRlNGNhZWIwNTg5MmUxMzA4YWRmMTk3ZjM2ZDkyYzU3MWMzM2U2

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by thehastingsp** [comment]
@RLHecht there is no current way to shrink the PDF, so we would like to provide an error message while that problem is worked out. I thought we could [consider adding guidance in the upload evidence section](https://design-system.service.gov.uk/components/file-upload/) that speaks to being able to scan a document, or take a picture of it. We suspect many folks are taking a photo with a phone which can result in a very high resolution photo - so perhaps we can offer a paragraph that speaks to best practices for capturing and uploading evidence. For this specific ticket, though, we may just want to offer a simple error like: ‘The selected file must be smaller than [largest file size]’

**Comment by Mottie** [comment]
We have 2 cases where an incorrect password is supplied along with a PDF

<details><summary>Notice of Disagreement</summary>


An incorrect password error message is shown above the password input
![nod-incorrect password-inline-error](https://user-images.githubusercontent.com/136959/182646640-2f005217-082d-4201-9f56-8b08d836bf59.gif)</details>

<details><summary>Claim Status Tool</summary>


An incorrect password error is shown in an alert at the top of the page. This is because the Claim Status Tool uploads all the files after the files are submitted for review.
![cst-upload-error](https://user-images.githubusercontent.com/136959/182646992-1e1e7815-5291-4d3b-97b9-92db08e20316.gif)

</details>

**Comment by katherine-fung** [comment]
Thank you for the recorded demo!! 

@thehastingsp - I just chatted with my team and we have some questions about submitting evidence for the NOD more broadly, that we think will be useful for crafting a helpful message.

1. What are the alternatives to submitting a NOD if you can't upload your additional evidence through the online tool? i.e. can you do it by mail?

2. Is there a phone number you can call for help if you can't upload your file?

3. Does this same kind of error (printed page size is more than --) happen for other VA online tools where you have to upload documents?

**Comment by thehastingsp** [comment]
@Mottie can you help answer some of these questions or point us to who might know more, since I am newer to decision reviews?

**Comment by Mottie** [comment]
1. If they can't upload, they can snail mail, fax or deliver the evidence in person
2. There isn't a specific phone number that I know of, I think we'd direct them to the help desk
3. We don't show any other upload errors, that I know of. The front end checks the file for password and if the internal file type matches the extension. And it should show any upload errors that are returned from the backend after uploading.

**Comment by katherine-fung** [comment]
Thanks @Mottie! Is the printed size error something that would occur at the front end, or get returned from the backend?

**Comment by Mottie** [comment]
It would be an error the backend would return, but we could detect and change the content of the message on the frontend.

**Comment by katherine-fung** [comment]
Thank you @Mottie and @thehastingsp!  

A few more clarifying questions: 

It's [VA style to offer some type of guidance for next steps in error messages](https://design.va.gov/patterns/messaging-error-messages), which could be valuable for users trying to meet the deadline for submitting additional evidence with the NOD. We're playing around with the idea of an error message that advises people to mail/deliver their materials or call the helpline as an alternative if their PDF is rejected.    

1. If the online tool rejects a user's PDF over printed size dimensions and the user wants to submit hard copies of their materials instead, should they submit hard copies of VA form 10182 AND their additional evidence, **or** just the additional evidence? 
 
2. Who is the best person to definitively tell us the best alternative to submitting their materials via the online tool? Whether it's mail, fax or deliver in person -- and where users should send or deliver their materials to? 

3. Who is the best person to definitively tell us if there is a phone number users can call for technical support? Or if they call the general helpline, will agents know how to help them upload their documents? We wonder if it would be helpful to direct users to a helpline -- but only want to do that if we can confirm that agents are in fact equipped to help with this problem.

**Comment by Mottie** [comment]
1. We were playing around with this. You _can_ create a PDF the correct size if you follow these steps, assuming it's an over-sized image:
    - Open the image in Chrome or Firefox (Safari doesn't allow this)
    - Use <kbd>Command</kbd> or <kbd>Ctrl</kbd> + <kbd>P</kbd> to print the page (or choose Print in the browser menu)
    - In the print modal "Destination" selector, choose "Save as PDF" (Chrome) or "Save to PDF" (Firefox)
    - Use the "Save" button
    - The shiny new PDF will be saved to the download folder
    - Upload that PDF 
2. I don't know who the best person is for this, but there is an [upload supporting evidence page](https://staging.va.gov/disability/upload-supporting-evidence/)
3. I'd recommend contacting Chante, Kimberley or Ervin in the #vsp-contact-center-support channel. They would know what the helpline is capable of doing.

**Comment by thehastingsp** [comment]
My answers: 
1. I do not know the answer to if they need for 10182 - @saderagsdale do you? I don't recommend offering how to create a PDF advice in this ticket, but consider a new ticket where we build support in the upload supporting evidence page as Robin mentions. 
2. Not sure who this is either but likely the same person that we identify for 1.
3. Agree with Robin support channel is likely a good idea.

**Comment by saderagsdale** [comment]
@thehastingsp I am not aware of a requirement to submit a hard copy of form 10182 (Notice of Disagreement) with the evidence. 

@Mottie Claimants can submit their notice of agreement (form 10182) digitally without attaching a hard copy of the form at the time of submission on VA.gov, right?

**Comment by Mottie** [comment]
> Claimants can submit their notice of agreement (form 10182) digitally without attaching a hard copy of the form at the time of submission on VA.gov

Right, Lighthouse takes the 10182 data we provide and builds a PDF for central mail. We're talking about uploaded PDFs provided by the Veteran here. I'm not sure where this uploading of 10182 question came from?

**Comment by thehastingsp** [comment]
@Mottie this was the original questions: `should they submit hard copies of VA form 10182 AND their additional evidence, or just the additional evidence?`

**Comment by katherine-fung** [comment]
@thehastingsp @saderagsdale @Mottie - 

Thanks for providing this information! If someone can't upload their PDF because of printed size limits, we want to let the user know that their PDF is getting rejected AND give them some type of next step. Providing some sort of next step is part of [VA's style for error messages](https://design.va.gov/patterns/messaging-error-messages) (see the "What you can do" section" in the example. This is both to improve the experience for users who are probably frustrated that they can't upload their file, and to give them an option for getting their documents in by the deadline. I spoke to Pamela, who made the case for leaving technical advice about how to re-size PDFs out of this particular error message. 

With this in mind, the content team thought maybe we can offer users guidance about the next best way to submit additional evidence, for a quick, short-term solution. 

Here's an example of the direction we're considering. It's a draft, and not the final message. I just wanted to give you some context for my next questions. 

Example error message: 

"We're sorry. We couldn't upload your file. One or more pages in your PDF are too big.

You can send mail the evidence to this address:

Board of Veterans' Appeals
P.O. Box 27063
Washington, DC 20038

Include your name and file number on the pages."

For the immediate error message solution: 
1. Who is the best person to confirm whether the guidance above holds up? 
a. Can people in fact complete the NOD online and then mail in hard copies of their evidence? We don't want to direct people to do this, if the BVA can't actually match hard copies of evidence to someone's online application. 

For further investigation: 
2. Thanks for directing me to Chante, Kimberley or Ervin in the #vsp-contact-center-support channel to ask about the help line's ability to help with upload issues. I'll check with them. If I'm not able to get an answer quickly, we'll forgo directing people to call for help for now, and investigate that option later. 

3. re: the best guidance for next steps, the [uploading evidence R&S article](https://www.va.gov/disability/upload-supporting-evidence/#can-i-upload-evidence-online-t) mentions that people can "use the QuickSubmit tool through AccessVA to upload evidence to support a decision review or an appeal." @Mottie, do you think the QuickSubmit tool has similar limitations on printed page limits for uploads, or if this might be a viable option for people whose files are rejected? We'll also investigate the QuickSubmit after getting a short-term solution up.

**Comment by Mottie** [comment]
> 3\. do you think the QuickSubmit tool has similar limitations on printed page limits for uploads

I don't know. We were told that Central mail has this PDF size limitation, so if QuickSubmit eventually leads to processing through Central mail, then I think it would have the same limitation.

**Comment by thehastingsp** [comment]
Thanks for making headway on this @katherine-fung - I think the back up mail option is great. Quick submit is a tough interface and not sure what the history is there. I think we may need to dig a little deeper into that tool, the plan to upgrade or maintain it before we commit to sending users there. @saderagsdale do you agree?

**Comment by katherine-fung** [comment]
Thanks @thehastingsp. Can you confirm that the back up mail option is valid and the folks receiving the files by mail would process them correctly? Or can you point me to someone who can confirm that?

**Comment by thehastingsp** [comment]
@saderagsdale can you help us follow up on this one?

**Comment by saderagsdale** [comment]
@thehastingsp Let me know when you're free to discuss. Given our conversation with Lighthouse, QuickSubmit seems to be a highly used tool within the workflow. I would want to get input from our Lighthouse and our PO before suggesting to users that they mail in evidence. I'm not aware of his kind of guidance being given in other scenarios of evidence upload failure. Mailing in also doesn't seem to support our desire for efficiency or our north star for more favorable decisions.

**Comment by katherine-fung** [comment]
@saderagsdale that makes sense, and we definitely want to make sure whatever we suggest helps the process go smoothly for users. @saderagsdale @thehastingsp please let me know what you discuss or find out!

**Comment by thehastingsp** [comment]
@katherine-fung here are our preliminary findings - QuickSubmit is a third party tool that we can't confidently point them to, nor can we ensure that what they mail will be matched to the online claim they are filing, so we don't want to instruct them to mail it. LH is working on a solution to remedy this behind the scenes, so for this effort a simple error message will do. I recommend going with "We're sorry. We couldn't upload your file. One or more pages in your PDF are too big. Please try again." I've also created a [separate ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45470) to address the guidance they receive before they upload, which may helps as well.

**Comment by thehastingsp** [comment]
I'm thinking we could break this work into 2 tickets, so we offer the error message resolution, then follow up with the guidance we can offer them for an alternative avenue @katherine-fung @saderagsdale

**Comment by thehastingsp** [comment]
To resolve this @katherine-fung can you provide the final error messaging you recommend and we can create a new ticket for the fallback advice?

**Comment by bethpottsVADEPO** [comment]
@thehastingsp @saderagsdale I'm concerned that if we don't advise Veterans on an alternate way to submit evidence, we could be setting them up to miss their deadline for getting evidence in for Board appeals. That's a pretty big deal. 

I'd only really be comfortable with the phase 1 / phase 2 approach (first get up a general error message, then follow with a specific error message with guidance about alternate ways to submit) if we are actively seeking other ways to submit evidence. In other words, I wouldn't want to relax too much on the timing of phase 2 just because we have a general error message in place (that doesn't give Veterans a course of action so will definitely be frustrating to read). 

Do you have a sense of timing or a path to finding the answer to alternate ways to submit evidence? Or have you hit a dead end? I'm wondering if Paul Shute has been brought in to this convo yet. He may be helpful...

**Comment by thehastingsp** [comment]
Thanks for the context @bethpottsVADEPO we'll do some more discovery on what is a feasible alternative.

**Comment by saderagsdale** [comment]
@bethpottsVADEPO Hey there, Beth! Definitely agree that we don't want to delay the discovery for phase 2 (a specific error message with guidance about alternate ways to submit). I'll raise this tomorrow with Lighthouse and our PO, Matt Self, in our recurring sync to explore established practices and VA guidance for this non-frequent use case scenario. For phase 2, we need to understand if the recommendation to mail evidence for a digital submission is viable based on the current working processes (_Main questions: how does that digital form and mail-in evidence get connected? is there an unintended consequence to suggesting this?_) 

With that in place, I think we're in good shape to proceed with phase 1 (simple error messaging). Let us know if that covers the bases.

**Comment by bethpottsVADEPO** [comment]
Thanks so much @thehastingsp @saderagsdale! I know you have to keep moving forward with this. Appreciate your efforts to find an alternate way to send in evidence. Would you like me to ping Paul Shute for his thoughts or will you do that? (maybe you already have...)

@katherine-fung will be in touch today with the more general language you can use initially for the error message.

**Comment by katherine-fung** [comment]
Thank you @bethpottsVADEPO @thehastingsp @saderagsdale! 

Here's the language for the initial general error message: 

We're sorry. We couldn't upload your file. One or more pages in your PDF are too big.

**Comment by thehastingsp** [comment]
We're all set to close this and will continue to discover alternative ways to submit. Thanks!
