### ISSUE TITLE
Standardize platform address UI schema

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#44009]
## User Story

_As a developer, I would like to have a standard address definition, because it would help me with not needing to duplicate the `profileAddress` definition_

## Expected Behavior

I would like to be able to pass in a key/value pair for the address (e.g. `addressLine1`, `address1` or `street1` for `street`) to the function in `src/platform/forms-system/src/js/definitions/profileAddress.js` and have it return a uiSchema with values that match.

Right now, it will always return a predefined set of keys for the address UI schema: `isMilitary`, `view:militaryBaseDescription`, `country`, `street`, `street2`, `street3`, `city`, `state` and `postalCode`. So most forms are rolling their own address UI function, or copying the file above, leading to lots of duplicated code.

For example:

```js
const schemaCrossXRef = {
  isMilitary: 'isMilitary',
  'view:militaryBaseDescription': 'view:militaryBaseDescription',
  country: 'country',
  street:  'street',
  street2: 'street2',
  street3: 'street3',
  city: 'city',
  state: 'state',
  postalCode: 'postalCode',
};

export default function addressUiSchema(
  path,
  checkBoxTitle,
  uiRequiredCallback,
  schemaKeys = schemaCrossXRef,
) {
  // ...
  return {
    [schemaKeys.isMilitary]: { /* ... */ },
    [schemaKeys['view:militaryBaseDescription']]: { /* ... */ },
    // ...
  };
}
```

## Acceptance Criteria

- [ ] Determine a method for making the address UI schema match the schema where it will be used
- [ ] Update tests

**Comment by taylorkaren** [comment]
Hi @Mottie: Thank you for filing this issue. 

Per our [Forms Library support policy](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2129920044/Forms+Library+Support), we are not prioritizing feature request work on the current Forms Library so that we can focus on building out the new VA Forms System Core (VAFSC).

I spoke with Micah and Matt Dingee about this, and we are all good with you working on this, if you have the time and inclination, and tagging the Forms Library Team to review any PR(s) you would like to submit.

**Comment by Mottie** [comment]
Done
