### ISSUE TITLE
[repo migration]: link remediation

### ISSUE THREAD

**Issue by thatmattjohnson** [department-of-veterans-affairs/va.gov-team#4410]
[X] complete repo migration batches
[X] run GH reports showing all references to vets.gov-team URLs in va.gov-team repo (dev)
[X] manually update or remove vets.gov-team references

**Comment by billfienberg** [comment]
Now that the last of the migration PRs have been merged, the [`find-vets-links` script](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/scripts/find-vets-links.sh) has been run on both the `va.gov-team` and `va.gov-team-sensitive` repos. 

I uploaded the files to Slack because I wasn't able to drag and drop a `.csv` file to ZenHub.

**Comment by thatmattjohnson** [comment]
remediation source files with statuses:

https://docs.google.com/spreadsheets/d/1w-ox9_vFaWQkMa9LVgd4djwoR--4Ce4yBeNEJhAZu-E/edit#gid=2057929502
https://docs.google.com/spreadsheets/d/1OMF77aF-7O6wM0M6EV5Org3RZzxdsrxNgWe0s7VZ9o4/edit#gid=279070905
https://docs.google.com/spreadsheets/d/1RjCAoEgc9VmR8lnlpkzsira09rtB1qJu_1fichHoDH0/edit#gid=1711595673
https://docs.google.com/spreadsheets/d/1yN3oQPcbHqWNIyXMoJ0mFlP56ZUTjw3d39ZwMCS2BEc/edit#gid=1094340867
https://docs.google.com/spreadsheets/d/1gJVGWISqCI-ssRO2kwyOsZ9OTdHNEhicBa8vGjDM7HA/edit#gid=991002603
https://docs.google.com/spreadsheets/d/1NQvjJu1DO_1QbJm5J3dceoTtrcHJUJfJRLkcLbiBVTU/edit#gid=1046371785

**Comment by thatmattjohnson** [comment]
remediation completed for all above files. closing this issue.
