### ISSUE TITLE
Simplified VA Header & Footer

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44181]
## Problem Statements
- A small percentage of Veterans who use Pre-Check-in and/or Check-in are unnecessarily clicking the "Sign In" button and signing into VA.gov. Because this is not required for these features and because this takes time to do, we would like to remove or disable this ability so that Veterans are not spending time doing it.
- It takes a significant amount of time to load the VA header and footer, causing our page load times to be large

This was a recommendation that came out of the [Bay Pines research study](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/bay-pines-in-person-uat).

## Background
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1658841196101469)

[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1654182863283549?thread_ts=1652386398.232339&cid=C022AC2STBM)

## User Story
As a Veteran, I get confused using the Pre-Check-in and/or Check-in applications because I don't understand that there are multiple steps and am confused by the header & footer.

## Idea
- Test a stepped form design for check-in with Veterans as a way to better communicate the remaining steps.
- Test simplified header & footer

**Comment by benbrasso-agile6** [comment]
@loripusey we have [approval via Design System Council](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1339) to move forward with the simplified header and footer. However, Patrick needs to seek some information about what we can hide or show in the footer. I have messaged Patrick separately already about it. 

Re, [progress bar](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1333), DSC needs to better define whether a segment is to be used for a "step" vs. a larger "chapter." So, they're going to be doing some research on their side. For us, I need to speak with Christina Gednalske who is wanting to make a similar update. However, because how we're imagining the progress bar will work, we actually wouldn't be able to use it until after travel pay is launched. And then, because travel will only be seen by about 50% of users, and pre-reg will be complete by about 20% of users, the progress bar would only be shown to that 30% of the 50%. Point being, I believe this gets deprioritized for us, but we could proceed if we wanted to. I would also need to better define how we're planning to test this. It would need more discussion with research ops and/or at design council again.

**Comment by benbrasso-agile6** [comment]
Chatted with Patrick this morning about the footer. We may change the simplified footer to include the legal links at the bottom. I'm going to crowd source this idea in slack in just a few moments. Per Patrick: 

> morning! can dig into the need for the legal links, but i suspect we’re not going to get a clear answer. is there a “meet in the middle” option where we put a single text link next to the footer that says something like “legal info” and maybe pops up a modal?
