### ISSUE TITLE
Discuss VFS Products List with team

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#44225]
Share with team info about product list project from QA team.

Acceptance Criteria:

- [x] Review product outline and product 

- https://vfs.atlassian.net/wiki/spaces/PPS/pages/2138800169/VFS+Product+Directory+-+Product+Outline
- https://vfs.atlassian.net/wiki/spaces/TTT/pages/2220556289/User+Research+Product+List

- [x] Start thinking about where in the IA to fit this product list

**Comment by laucon** [comment]
I think a product directory is a great idea, but I'm wondering: is the Console going to have a product directory? Isn't that what the Console Catalog is? Maybe I'm wrong. But if it is, maybe we should still have a directory on the Platform website anyway? I'm not sure.

**Comment by vbellissimo** [comment]
@laucon I asked the product manager that same question and the answer was that the long-term plan is that, in a way, the Console _would_ be that large product list. But that is a longer-term goal. In the meantime, they want to continue to keep this outside of the Console and the Platform website makes the most sense.

**Comment by laucon** [comment]
A few notes:
1. We'd recommend placing the Product List under "Getting Started" in the Platform site as its own document on the sidebar, similar to how "Welcome" and "Set Up Encrypted Email" and "Offboarding" are their own documents on the sidebar.
![Screen Shot 2022-07-18 at 12.00.43 PM.png](https://images.zenhubusercontent.com/62c4300b21b68e6ecd4413f1/110e1f5c-6dfb-4432-959b-13776835a942)
2. We'd like to consider using an [Overview template](https://vfs.atlassian.net/wiki/templates?space=~6218e48cc34549007199170b&template=1476558950) to write the document that contains the product list. This would make it more consistent with other Platform documents.
3. The current product list goes into a lot of detail. We feel that this level of detail isn't necessary on the Product List on the Platform Website because the Console will go into that level of detail and because the details make the list excessively long.
