### ISSUE TITLE
[SPIKE] [BUG] Research if there’s any known QR code bugs associated with text messages not populating

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#44239]
## Background
This was a recommendation that came out of the [Bay Pines research study](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/release-plan/check-in-release-notes.md).

This bug was witnessed on an Android device during research efforts.

## Task
- Research if there’s any known QR code bugs associated with "check in" text messages not populating

**Comment by brdunfield** [comment]
Android smart phones have built-in QR code support as of Android 8 and higher. Devices previous to Android 8 can still scan QR codes using an app.

I haven't been able to find any evidence of widespread QR code bugs on Android. Based on how QR codes work, it doesn't seem technically possible that the code would successfully scan to the point where it knew to open the SMS app, without also having scanned the message that should have populated. QR codes seem like they either scan fully or they don't.

Likely causes of the observed issue from what I have learned:
- User is using an older device or an app to scan the QR code instead of native support, and the app either modified or errored the scan in such a way that only the message text portion of the QR code was dropped.
- User is on an android version that has or had an error with QR codes (although I can't find any evidence of widespread issues on specific android versions), and has not updated their device to a newer version

I think without knowing the user's device / Android version, and what app (if any) was used to scan the QR code, it will be difficult to troubleshoot this further.

**Comment by brdunfield** [comment]
@loripusey Given the above, should I close this ticket for now?

**Comment by loripusey** [comment]
Yes, thank you I would close the ticket.
