### ISSUE TITLE
[SSO-Login] Alert box updates on VA.gov Health pages

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#4437]
**User Story**
As a Veteran who is a patient at a facility using Cerner, I need the alert boxes on VA.gov health pages (Messaging, Medical Records, Prescriptions, Scheduling, Test Results) to show me which patient portal I need to go to in the alert box after I've authenticated

**Comment by christine-dillman** [comment]
Not applicable to Identity/SSO.

**Comment by FranECross** [comment]
@jilladams This epic isn't labeled for the PW team, but many of the tickets are. Should they be, though? Thanks!

**Comment by jilladams** [comment]
Interesting. This is going to be an annoying answer, sorry in advance. 

This is an old epic, from a time where Public Websites was managing our infamous CTA React widget. Some education first: 

## What's going on
Wes put together this Mural that really effectively describes how these widgets work -- it's probably worth looking over for context: https://app.mural.co/invitation/mural/vagov6717/1651166973924?sender=u907f83e01e35bb04de6f8139&key=1a1e030f-8c9f-4b94-9960-b0a45b04a511. 

So what happens is, as a user, when I login: 
* if the facility(or facilities) where I have received care use Cerner for their electronic health records (EHR), and I click one of those buttons, I'll be sent out to the My VA Health portal (which is owned/operated by Oracle Health (which bought Cerner), to see my info. 
* If my facility uses VistA for EHR, I'll get sent out to the MyHealtheVet portal.  

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/85581471/834f6240-26d4-45ba-ba06-b139a6489576)

## But then: MyHealtheVet on VA.gov (MHV)
But then: VA has decided: it's not great to send Veterans out to 2 different portals, if you happen to receive care at 2 facilities that use different EHR solutions. So VA is building "MyHealtheVet on VA.gov" which is a proprietary product* that will integrate the VistA and Cerner APIs. So a Veteran will click one of these CTAs, and stay within VA.gov, but see all their portal information. 

That migration /product build is a work in progress, and as it rolls out, all of the messaging described in these tickets will change. Our friend @wesrowe went to MHV team, so may have insights on timing, someday. 

*MyHealtheVet is a VistA-owned product. "MyHealtheVet on VA.gov" is a VA-owned product. They are totally different products, and VA just worked out some trademark navigation name borrowing, bc MyHealtheVet is a name Veterans know and trust. Not confusing at all. 🙃 

## Does PW still own these tickets
Who knows. 😂 This is all tied up in the conversation with Dave about transitioning ownership of the CTA widget -- which is used in all kind of other additional places, as Laura pointed out in this comment this week: https://github.com/department-of-veterans-affairs/va.gov-team/issues/50215#issuecomment-1966695750

I think some of this messaging work has already been performed, as you can see in the screenshot above that clearly states "on My VA Health" and "Go to My VA Health". So these tickets may be outdated / no ops. But I don't know for sure, as they predate me. I'd be surprised if they were still relevant, but we can't likely just close them without a scrub and verification. 

**Verification is hard.** Because you have to have a test user, who is affiliated with a Facility that uses each EHR flavor, in order to see what happens to the CTA text once they log in. OR: we need engineers to follow the bunny trails in code and verify the language used on each CTA as a logged in user with whichever EHR in play.  

I might be inclined for now to say: let Dave decide if we should close these, or let sleeping dogs lie.
