### ISSUE TITLE
AWS access for [Igor Yegorov]

### ISSUE THREAD

**Issue by ewilson-adhoc** [department-of-veterans-affairs/va.gov-team#44681]
### COR Name

Courtney Bethea

### Vendor Onboarding Representative Name

Liberty IT -  Michael G. Lovejoy

### Your Name

Igor Yegorov

### Your Email

igor.yegorov@adhocteam.us

### Team, Role, and Company of the target individual

PST-IET, Software Developer, ad Hoc

### Product Manager (PM) name and email

Frank Hiatt, frank.hiatt@adhocteam.us

### Product Owner (PO) name and email

Thomas Delrue thomas.delrue@va.gov

### Desired AWS Access

Igor needs to be able to access parameter store in order to add parameters to the services that pst-iet maintains (/dsva-vagov/vets-api-sidekiq-ui/, /dsva-vagov/vets-api-file-upload etc)

### Access Expiration

09/12/2022

### User must exist in a roster before AWS access can be granted

- [ ] Search for user on the VFS Team Roster: https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665
- [ ] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by jbritt1** [comment]
Igor is already part of the pst-iet team within AWS that allows access to the necessary Parameter Store paths:

![image](https://user-images.githubusercontent.com/56260532/180222621-60dc0786-e516-4603-9efe-2571e50df830.png)
![image](https://user-images.githubusercontent.com/56260532/180222459-975ce6b1-8f8a-44df-9515-3a807cce6ec9.png)

If he is having trouble accessing the Paramater Store, it is because he has no MFA device synced to his account. This is a requirement for all AWS activity to work as we apply a policy that will block all actions for any user not MFA'd.

![image](https://user-images.githubusercontent.com/56260532/180222862-d13fbc67-36ae-4e81-bfbb-e944026d33a7.png)
