### ISSUE TITLE
[ISSUE] Caution Flag showing up in INDIANA WESLEYAN UNIVERSITY 

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#44783]
## What happened?
On 7/21/2022 it was reported by Joshua Lahbrook (VA) the previously removed caution flag for INDIANA WESLEYAN UNIVERSITY was showing again in production.
AFS Dev took a look in staging and the flag was NOT showing. On 7/22/2022, around 10:00am EST, AFS Dev removed the caution flag from production and begun investigating the root cause.

It appears as if one of the files Mr. Grubb manages in GIDs triggered the flag. A follow up with Mr. Grubb preceeds Monday 7/25/2022 when he is back from PTO.

Caution flag showing in institution link.

**Caution Flag was not present in Staging, but visible in Production.** 
Link - https://www.va.gov/education/gi-bill-comparison-tool/institution/31923414

 ![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/47db91ed-843e-4611-ad87-91b5b14f208d)

**The following was discovered and corrected.** 

- Three database fields that are different, production has caution_flag=true, accreditation_status="Loss of Accreditation or Preaccreditation: Other", caution_flag_reason="Loss of Accreditation or Preaccreditation: Other (Other - Provide unlisted or multiple justifications)" 

- Discovery has shown the values in production were set to "Nill". Production was updated to reflect the same values in staging which did not show a production flag. After updating the fields, the caution flag was no longer present in Prod.  

- The caution flag is no longer present after the update. 

![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/ff78f535-8277-4950-adad-a2f13b37fc1e)

**Comment by mrblanco1** [comment]
AFS Dev removed the flag in prod on Fri 7/22/2022 around 10:30am EST.
Brian Grubb provided feedback and an explanation to why the flag re-appeared in prod Fri 7/22/2022 evening:
Hello All,
 
I am out due to my wife having surgery but saw the importance and wanted to shed light on this quickly. Please see below explanation below.
 
“”The flag showed up again because the Dept of ED file still shows the flag in the data file listed as Accreditation Action.
 
Url: https://ope.ed.gov/dapip/#/download-data-files
 
Please use the DAPIP ID below to find the flag in question for which we do not control the data file.
 
Indiana Wesleyan University- DAPIP ID: 115311
 
This flag was removed in 08302021 but the Dept of ED controls the file in question and if the file is not correct we CLAP Team will not know because we do not own the data nor manage it.””
 
Please see the file attached of when this was removed.↑
 
I can and will explain in the meeting on Monday and show all that attend the issues with the Dept of Education file.
 
Special Note: This is when the Comparison Tool was updated and the Flag was removed and it’s time stamp.↓
Accreditation Action       Succeeded         AccreditationAction_08302021.csv              August 30th, 2021 14:04              brian.grubb@va.gov      INDIANA WESLEYAN UNIVERSITY-Flag Removal

There is a follow-up meeting with Brian, Darla and AFS this afternoon (7/25/2022) at 4pm EST to endure this issue does not happen again and to make sure the file process is been followed.
