### ISSUE TITLE
Additional Evidence Documents don't display after upload 

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4505]
## User Story:
As a Front-end Engineer on the Benefits and Memorials team, I need to finalize research and fix any issues for the additional evidence documents within the Claim Status Tool functionality so that it is performing properly.

## Original Bug Ticket
#3909

## Tasks
- [ ] If back end code/endpoints for documents changes, adjust any front end code required to properly display uploaded documents

## Acceptance Criteria:
- [ ] Additional evidence on the Claim Status Tool is uploading properly

**Comment by ndsprinkle** [comment]
Back end coding changes have been completed and deployed for this issue. All seems to be working as it should, but I will still make sure all tests are passing and try a few test scenarios to verify no front end code changes are necessary. If no tests are failing, then I should probably write some so that there are failing tests if the additional evidence is not appearing in the future.

**Comment by ndsprinkle** [comment]
After digging into this, all functionality relating to the additional evidence inside the claim status tool is functioning as it should. In addition to the veteran being able to view all uploaded evidence, other areas that were referencing the additional info are properly working now, including details relating to the timeline of events for the claim. 

As far as testing goes, all tests are passing and there already exists tests relating to the displaying of additional evidence, so no additional tests will be written.
