### ISSUE TITLE
Request for Analytics: Update Git Hub tracking data in DOMO

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#45084]
**User Story**
As a Platform Content team,
I want to have a more holistic view of our team's Git Hub intake support form data,
So that we can analyzing our team's support services trends, support workload and make more data-driven decisions.

**Request**
Build onto the existing Git Hub tracking visualization found at the [bottom of this dashboard](https://va-gov.domo.com/page/1182586883), the [form we want to track is this one](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=vbellissimo%2C+ssimmorins%2C+amygoldman&labels=documentation-support%2C+pw-footer-feedback&template=platform-website-footer-feedback.md&title=), and the labels for the form are `documentation-support` and `pw-footer-feedback`.

Ideally, if we could group them by:

- Number of new tickets per week/month
- Number of tickets resolved or closed per week/month
- If possible, # of tickets assigned to other Platform teams. The labels might vary such as `governance-team` or `tools-fe` or `qa-standards`
- If possible, list of ticket creators (usernames?) and the # of tickets they have submitted.

**Comment by chloedotbrown** [comment]
Hi @vbellissimo! Think we'll be able to create a new dataset in Domo that meets you needs. Before we do though, I just want to verify a couple things:

- **Other potental Platform Content labels** - The original request only includes `pw-footer-feedback` and `documentation-support`, so the only tickets we'll bring in are ones that have either of those labels. However, I also noticed that there are a couple other tags, like `platform-content-team` that are also on these tickets as well. 
- **Platform team labels** - Are you looking for a way of segmenting other Platform team labels on the `pw-footer-feedback` and `documentation-support` tickets? Or totals of all tickets assigned to these other teams? Either way, the info we'd need to do this would be a list of all the Platform team tags, otherwise, we won't be able to filter for a complete list. And if digging this up is a blocker, we can hold off for now and bring it in later.

Once I have this info, I can load your data into Domo. Then @jonathan-epstein13 and I will put together some resources and walk you through how to build what you need with it. Thanks!

**Comment by vbellissimo** [comment]
Hi @chloedotbrown Thanks for following up. Here are my answers:

- **Other potential Platform Content labels:** The `platform-content-team` may or may not be part of this ticket list. This is because we add it AFTER the ticket has been created, based on whether our team is doing the work for it or not. In this case, I don't think this tag needs to be a requirement to be pulled into this visualization.

- **Platform team labels:** For this, I'm looking for a way to see totals of all tickets assigned to other Platform teams. We can start with pulling in these tags:
`tools-fe`
`governance-team`
`qa-standards`
`service-design`
`analytics-insights`
`vsp-design-system-team`
`operations`
`console-services`

Let me know if you have any other questions. Thanks!

**Comment by chloedotbrown** [comment]
Perfect! This seems great for now - will follow up if I have any other questions.

**Comment by chloedotbrown** [comment]
## Internal Analytics Process: BigQuery QA
Created a `vw_vsp_content_github` view in the vsp_sites folder in BigQuery. In order for a Github ticket to be included in this set, it had to meet one of the following conditions:
- Have at least one Content label: `documentation-support`,`pw-footer-feedback` OR
- Have at least one Platform Team label: `tools-fe`,`governance-team`,`qa-standards`,`service-design`,`analytics-insights`,`vsp-design-system-team`,`operations`,`console-services`

Each row contains ticket details and new columns for Content and Team labels. Importantly, the ticket_number is NOT a unique identifier - if a ticket has more than one Content or Team label, there will be more than one row in the data. Therefore, people using this dataset should always use a `count(distinct ticket_number` function to count tickets.

_Process reference: [BigQuery QA instructions](https://vfs.atlassian.net/wiki/spaces/AT/pages/2215870977/How+to+QA+data+in+BigQuery)_

## Structure tests

### Uniqueness
✅ **Passed!** Total rows is the same value as the distinct count of combined ticket number, content labels, and platform teams. 

Total rows | Unique IDs
 -- | -- 
11,222 | 11,222

<details> 
  <summary>Expand for test code</summary>

```sql
select
  count(*) as total_rows,
  count(distinct concat(ticket_number, ifnull(content_labels,'~'), ifnull(platform_teams, '~'))) as total_uuid
from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`;
```
</details>

### Nulls
✅ **Passed!** For columns with nulls, rows have patterns that align with business logic (i.e. we understand why).

Column | Null rate  | Explanation
 -- | -- | -- 
`content_labels` | 99% | ✅  There are 157 rows where content labels have values. Of the rows that don't, 100% have platform team values.
`close_date` |  15% | ✅  Corresponds with 1,658 (15%) tickets in set with "open" status.
`days_to_close` | 15% | ✅ _(see above)_
`platform_teams` | 1% | ✅  There are 70 rows where team is null. Of these, 100% have content label values.

<details> 
  <summary>Expand for test code</summary>

```sql
with gh_nulls as (
  select 
    col_name, 
    count(1) nulls_total,
    'a' as join_key
  from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github` g,
  unnest(regexp_extract_all(to_json_string(g), r'"(\w+)":null')) col_name
  group by col_name 
),

gh_all as (
  select 
    'a' join_key,
    count(*) as total_rows
  from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
)

select
  col_name,
  round((nulls_total/total_rows), 2) as pct_null
from gh_nulls
left join gh_all using (join_key)
```
</details>

### Completeness
✅ **Passed!** Checked row distributions for metrics requested in ticket.

<details> 
  <summary>Expand for test code</summary>

```sql
/**************************************
   NOTE: Highlight and run separately
**************************************/

-- Number of new tickets per week/month
select 
  open_date,
  count(distinct ticket_number) as total_tickets
from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
group by 1
order by 1 desc

-- Number of tickets resolved or closed per week/month
select 
  close_date,
  count(distinct ticket_number) as total_tickets
from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
where ticket_status = 'closed'
group by 1
order by 1 desc

-- Number of tickets assigned to Platform teams
select 
  platform_teams,
  count(distinct ticket_number) as total_tickets
from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
where platform_teams is not null
group by 1
order by 2 desc

-- Number of tickets with content review labels
select 
  content_labels,
  count(distinct ticket_number) as total_tickets
from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
where content_labels is not null
group by 1
order by 2 desc

-- Number of tickets submitted by creator
select 
  creator,
  count(distinct ticket_number) as total_tickets
from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
group by 1
order by 2 desc
```
</details>

## Accuracy tests
Tested key totals against un-transformed GitHub data tables.


Ticket count metric | Pass/Fail
-- | :--: 
Total `documentation-support` | ✅
Total `pw-footer-feedback` | ✅
Total `governance-team` | ✅
Total `tools-fe` | ✅
Total `qa-standards` | ✅
Total `service-design` | ✅
Total `analytics-insights` | ✅
Total `vsp-design-system-team` | ✅
Total `operations` | ✅
Total `console-services` | ✅
Total `platform-content-team` | ✅
Total tickets opened on 8/15/22 | ✅
Total tickets closed on 8/15/22 | ✅

<details> 
  <summary>Expand for test code</summary>

```sql
/**************************************
   NOTE: Highlight and run separately
**************************************/

-- Change label content between quotes for tag tests
  select 
    'BQ view' as data_source,
    count(distinct ticket_number) as total_tickets
  from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
  where content_labels = 'documentation-support'
  -- where platform_teams = 'platform-content-team'

  union all

  select 
    'GH data' as data_source,
    count(distinct cast(number as string)) as total_tickets
  from `vsp-analytics-and-insights.vsp_testing_tools.github_issues`,
    unnest(labels) as unnest_labels
  where unnest_labels = 'documentation-support'

-- Change date for tickets opened on day tests
  select 
    'BQ view' as data_source,
    count(distinct ticket_number) as total_tickets
  from `vsp-analytics-and-insights.vsp_sites.vw_vsp_content_github`
  where open_date = '2022-08-15'

  union all

  select 
    'GH data' as data_source,
    count(distinct cast(number as string)) as total_tickets
  from `vsp-analytics-and-insights.vsp_testing_tools.github_issues`,
    unnest(labels) as unnest_labels
  where cast(timestamp(created_at) as date) = '2022-08-15'
    and unnest_labels in ('documentation-support','pw-footer-feedback','tools-fe','governance-team','qa-standards','service-design',
        'analytics-insights','vsp-design-system-team','operations','console-services','platform-content-team' )
```

**Comment by jonathan-epstein13** [comment]
Hi @vbellissimo! We’ve created a new [Domo data source](https://va-gov.domo.com/datasources/e2511a00-7457-4be1-aa5a-330d40bff80f/details/overview) for you that includes GitHub ticket data that can be segmented by the content labels or Platform team labels you provided. You should be able to use it to create cards for all the metrics you requested above.
 
### About this data
The dataset updates daily and includes information about GitHub tickets that meet either (or both) of the following conditions:

- They have one of the content / document review labels
- They have one of the Platform team labels

You can learn more about each column by looking at the [data dictionary](https://va-gov.domo.com/datasources/e2511a00-7457-4be1-aa5a-330d40bff80f/details/data/schema) we created for you, or by hovering over the variable in the data pane when building cards.
 
A few important notes about the data:

1. There is usually more than one row per ticket in the data, which allows the data to be spliced several different ways. However, this means you will never want to do a row count (or Domo’s aggregation option “COUNT”) in order to count tickets. More info on what to do instead in the next section.
2. This includes all data for the labels you specified in the ticket and comments. If you later discover that a team label is outdated or that a content label needs to be added, please reach out to us to make the change.

 
### Building cards
**Counting tickets** - When it comes to total tickets, always use the Beast Mode we’ve created for you, `Count of ticket number`.
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/dcf37730-f982-4bf9-b6aa-bf4faff9d164)
As mentioned above, each row contains the ticket details and one content label or Platform team value. If the ticket has more than one content label and/or team label, that ticket will have more than one row in the dataset. To use this beast mode, you can drag it to the card builder fields like any other variable from the dataset.

**Filtering for the right tickets** - To only view tickets with content review labels, drag  `content_labels` from the left side quadrant in dimensions to the filter section. 

Select both content labels and then click apply. GitHub data in the dataset that only has a Platform team label, but no document review tags will be excluded.
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/73f53a5f-9bb9-4ef5-8090-93eb1c9e6ebf)
![image.png](https://images.zenhubusercontent.com/616700bf2a260a7323c067fd/771571ec-cadb-4e63-87db-31f3c42a602c)
If you have any other questions, feel free to come to office hours. We’ll also be releasing a Domo training video sometime next week.

**Comment by chloedotbrown** [comment]
Going to go ahead and close out this ticket. @vbellissimo - if you end up having more questions or want to walk through together, please reach out or join us in office hours again!
