### ISSUE TITLE
Update Telephone component:  Add tty prop to the telephone component.

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#45155]
The Design System team just made an update to the telephone web component which adds a new tty prop for indicating if the number is a TTY number or not.
If the component is used like this:

`<va-telephone tty contact="711" />`

The following markup will be rendered inside of the component:

`<a href="tel:711" aria-label="TTY. 7 1 1.">TTY: 711</a>`

[Telephone Design component](https://design.va.gov/content-style-guide/dates-and-numbers#phone-numbers)
[Telephone storybook](https://design.va.gov/storybook/?path=/docs/components-va-telephone--default)

---
Here is the review instance: [http://0dd79fcbca9b2563e87ff06938e86eb3.review.vetsgov-internal/](http://0dd79fcbca9b2563e87ff06938e86eb3.review.vetsgov-internal/)

**Comment by ryanshaw** [comment]
@ldelacosta 

Currently we display phone numbers like this:

![image](https://user-images.githubusercontent.com/587812/189198246-71634f90-5c7b-4f00-9efe-ee34d2aa300f.png)

When updating the component to use the `tty` attribute, it will output like this:

![image](https://user-images.githubusercontent.com/587812/189198506-8d691a16-1983-478b-a8a2-60f7661d45b3.png)

Looking at other apps, specifically the health care application [landing page](https://staging.va.gov/health-care/apply/application/introduction) it looks like the numbers are handled a bit differently:

![image](https://user-images.githubusercontent.com/587812/189198734-76935169-2dfc-4129-8fc7-424b8e8dd055.png)

Is it ok to change how we display the TTY numbers in order to update the components?

**Comment by ryanshaw** [comment]
For clarification, it would be displayed like: 

**Main phone:** [307-778-7550](#) ([TTY: 711](#))

**Comment by ldelacosta** [comment]
I think we are OK to display the TTY on the same line as the phone number. @outerpress will double check and will advise shortly.

**Comment by RLHecht** [comment]
The way Ryan has it written above is correct. The TTY:711 should always follow a phone number, should be displayed in parentheses, and be wrapped with an aria label.

**Comment by ldelacosta** [comment]
@ryanshaw - [copy docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md) have been updated for the telephone components.

**Comment by ldelacosta** [comment]
@tlei123 - This is ready to be tested. Please let me know if you have any questions. Thanks!

**Comment by tlei123** [comment]
@ldelacosta @ryanshaw , this has been successfully validated in Staging.

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
