### ISSUE TITLE
Fix column widths of search results table

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#4516]
After performing a search on the [Find VA Forms React widget](https://dev.va.gov/find-va-forms-beta/), the column widths of the results table could use some adjusting. Specifically, the values of the Form Number, Issue Date, and Revision Date fields wrap to the next line, making the cells look weird. The column widths also fluctuate after performing a click on one of the column headers to sort the results.

### Screenshot of issue
![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/79d2b5ad-f5f6-410b-ac90-fa76c948e910)

### Acceptance Critera
- [ ] Values under `VA form number` do not wrap to next line
- [ ] Values under `Issue Date` do not wrap to next line
- [ ] Values under `Revision` do not wrap to next line
- [ ] Column widths do not change after performing a sort

**Comment by andaleliz** [comment]
@kelsonic I've been thinking about your suggestion to update the column heading `VA Form number` to `Form #`.  

I'm all for improving the column widths, but I don't think using the `#` for number is acceptable, as I believe a screen reader will read that as "hash" or "pound" and not the word "number". Plus, it might confuse some people who aren't familiar with that abbreviation/nomenclature.

I don't know enough about our users to say for sure this would work but could "Form ID" be an acceptable substitute that they'd understand? Maybe a content person could help guide us there.

Other ideas:
Can the widget have any more space? I think right now it's set up on a page using the right rail, but since it's empty, maybe there's a different template we could use?
Can we set the 2nd column to `width: 250px`? That seems to give all the columns an appropriate amount of room with `Form number` as the label.

As an aside, I noticed the first column sorting is an `<a role=button>`.  Could it just be a button instead? I think that is more semantically correct and accessible for screen readers.

**Comment by kelsonic** [comment]
@andaleliz I was also thinking that `Form #` may be confusing! I really like your idea of having that be `Form ID` as that's actually what that field is called, plus it's still brief enough to not make the column width arbitrarily long. Should we go with that then for the column title?

**Comment by kelsonic** [comment]
>Can the widget have any more space? I think right now it's set up on a page using the right rail, but since it's empty, maybe there's a different template we could use?
That seems reasonable! It would be helpful if the design spec could be updated so I can get an idea of exactly what you are envisioning 🙂

**Comment by kelsonic** [comment]
>As an aside, I noticed the first column sorting is an <a role=button>. Could it just be a button instead? I think that is more semantically correct and accessible for screen readers.

I would need to change this [in our formation-react npm package](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation-react/src/components/SortableTable/SortableTable.jsx#L82), but this certainly can be done.

**Comment by kelsonic** [comment]
>Can we set the 2nd column to width: 250px? That seems to give all the columns an appropriate amount of room with Form number as the label.

@andaleliz We can but then it's not as responsive as it was:
![image](https://user-images.githubusercontent.com/12773166/71751451-d7b17900-2e38-11ea-8c1d-15db993597ff.png)

**Comment by kelsonic** [comment]
> > Can we set the 2nd column to width: 250px? That seems to give all the columns an appropriate amount of room with Form number as the label.
> 
> @andaleliz We can but then it's not as responsive as it was at smaller resolutions:
> ![image](https://user-images.githubusercontent.com/12773166/71751451-d7b17900-2e38-11ea-8c1d-15db993597ff.png)

Created an issue for this: https://github.com/department-of-veterans-affairs/va.gov-team/issues/4558

**Comment by andaleliz** [comment]
> helpful if the design spec could be updated
Where is the design spec to update, @kelsonic ? Would be glad to do that if it is appropriate. I'm not sure of the origination of this work and who was involved in the OG design.

If `Form I.D.` is an acceptable label, then we don't need to mess with the CSS for the second column. Who can we check with to be sure that's okay (probably whoever said to use `VA form number`)?

**Comment by kelsonic** [comment]
> Who can we check with to be sure that's okay (probably whoever said to use VA form number)?

I think @jenniferlee-dsva!

**Comment by jenniferlee-dsva** [comment]
@kelsonic: 

1. I'm okay with column labels wrapping to 2nd line. However, I'm @rtwell to confirm that this isn't breaking with our design system. Please check me @rtwell! 
2. Column labels should be sentence case. 
3. Per recent reqs changes discussed with you, Nick, et al previously: For launching in staging, use the following columns:
- Form number
- Form name
- Issue date
- Revision date

[ ^ Reminder: when Kevin Reid adds the 2 new db fields to their forms db, we will replace issue and revision dates with "Related to" and "Available online" columns. <-- FYSA @RLHecht since you are doing final copy checking prior to launch.]

**Comment by jenniferlee-dsva** [comment]
@andaleliz - original design mocks (prior to temporary reqs changes) are located here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign

**Comment by ncksllvn** [comment]
One of the columns is being removed per https://github.com/department-of-veterans-affairs/va.gov-team/issues/4768, but the pattern is there for column widths -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/829c8683-f2cf-4d60-995c-75d87d31bab5)

Thanks @kelsonic!
