### ISSUE TITLE
Discovery: Research open source plugins for backstage to determine if any of the Release Tools Team products would be relevant for open source plugins.

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#45296]
Notes on open source plugins to consider:
*Include name of plugin, how it relates to the work of release tools, pros, cons, and any special things to note

_1. EXAMPLE NAME_
_- Description of plugin_
_- How it relates to work of RTT_
_- Pros_ 
_- Cons_
_- Things to note_

**Comment by jhonnyoddball** [comment]
### Initial research brings the following plugins to be considered:

- [Tech Radar Plugin](https://github.com/backstage/backstage/tree/master/plugins/tech-radar)
- [Sentry Plugin](https://github.com/backstage/backstage/tree/master/plugins/sentry)
- [Lighthouse Plugin](https://github.com/backstage/backstage/tree/master/plugins/lighthouse)
- [Datadog plugin](https://roadie.io/backstage/plugins/datadog/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=datadog)

**Comment by jhonnyoddball** [comment]
## [Tech Radar Plugin](https://github.com/backstage/backstage/tree/master/plugins/tech-radar)

The Technology Radar is a concept which allows you to visualize the official guidelines of software languages, processes, infrastructure, and platforms at that particular company

### Lifecycles

- **Use:** This technology is recommended for use by the majority of teams with a specific use case.
- **Trial:** This technology has been evaluated for specific use cases and has showed clear benefits. Some teams adopt it in production, although it should be limited to low-impact projects as it might incur a higher risk.
- **Assess:** This technology has the potential to be beneficial for the company. Some teams are evaluating it and using it in experimental projects. Using it in production comes with a high cost and risk due to lack of in-house knowledge, maintenance, and support.
- **Hold:** Teams should not use it in new projects and should plan on migrating to a supported alternative if they use it for historical reasons. For broadly adopted technologies, the Radar should refer to a migration path to a supported alternative.

This plugin will show us some of the infrastructure used in the platform. 

It also provides a simple installation that will provide an out-of-the-box Tech Radar experience.

**Comment by jhonnyoddball** [comment]
## [Sentry Plugin](https://github.com/backstage/backstage/tree/master/plugins/sentry)

The Sentry Plugin displays issues from [Sentry](https://sentry.io/).

It will provide us with a more centralize way of display all sentry issues.

**Comment by jhonnyoddball** [comment]
## [Lighthouse Plugin](https://github.com/backstage/backstage/tree/master/plugins/lighthouse)

A frontend for [lighthouse-audit-service](https://github.com/spotify/lighthouse-audit-service), this plugin allows you to trigger Lighthouse audits on a website.

**PROS:**
- Provides with all the data from Lighthouse
- It can be added to the Backstage catalog

**CONS:**
- We need to enable CORS
- The plugin only supports one website URL per component at this time.

**Comment by ndsprinkle** [comment]
Adding my personal pros/cons for each plugin.

## [Tech Radar Plugin](https://github.com/backstage/backstage/tree/master/plugins/tech-radar)

Pros
- Extremely easy to set up the UI, out of the box it just works by putting it in the routes
- There's also an optional advanced set up for customizing the React UI component
- When configured for all of our technologies, it'll definitely look cool

Cons
- At first glance, it's not exactly clear what the radar is showing
- Also, do I even care about this information that the radar is giving me?
- Setting up for all technologies seems difficult even when using the `TechRadarApi`
- Difficult to automate?

**Comment by ndsprinkle** [comment]
## [Sentry Plugin](https://github.com/backstage/backstage/tree/master/plugins/sentry)

Pros
- Relatively easy to set up a card or full page implementation out of the box
- Seems straightforward for how to connect to Sentry

Cons
- Which Sentry issues to show? Scoped by team? By user? How to authenticate?
- Seems easier to just go to Sentry

**Comment by jhonnyoddball** [comment]
## [Datadog plugin](https://roadie.io/backstage/plugins/datadog/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=datadog)

With this plugin, you can embed Datadog graphs and dashboards into an instance of Backstage.

PROS:
- We can add dashboards or graphs from datadog

CONS:
- It's not open source
- It costs about $2000 for 130 developers

**Comment by laineymajor** [comment]
@ndsprinkle @jhonnyoddball in your descriptions of the plugins you researched, can you make sure you've included:
1. Description of the plugin (what problem does it solve? and for which user(s)?)
2. How this plugin applies to the work of the Release Tools Team
