### ISSUE TITLE
Review if redis has a call backoff function if we call it too often

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#45356]
- focus for this is if feature toggles is causing a redis backoff network call delaying responses back to vets-api
- Does the network layer have connection restrictions which are affecting this. We believe redis has plenty of connections available.

**Comment by LindseySaari** [comment]
Feature toggles currently utilize Redis (Elasticache) and see ~30,000 get commands per second during business days/hours. This is due to the high number of calls to the FeatureToggles#index endpoint, which currently returns ALL feature toggles for a given request. While reviewing vets-api latency issues, it doesn't appear that Redis calls are a factor. Elasticache supports up to 65k concurrent connections and doesn't appear to have any sort of rate limiting in place otherwise 

[I created this ticket](https://app.zenhub.com/workspaces/platform-console-services-6221189e9d589600144196ca/issues/department-of-veterans-affairs/va.gov-team/45395) to investigate and possibly refactor feature toggles at a later date
