### ISSUE TITLE
IA Review: View Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4545]
## Goal
The eBenefits Team would like some guidance on where the "View Dependents" tool will reside so that we can make accurate adjustments to the mockups, frontend and to inform Public Websites about where to create the unauthenticated landing page.

## Required
- **Description and goals of the page/tool or link to a product outline**
  - [Link to feature outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents)
- **Planned/estimated launch date**
  - Estimated end of Q1 2020, or beginning of Q2 2020
- **Link to prototype or mock ups of all pages in the user flow**
  - [Mockup](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/)

## Helpful, but not required:
- **Any IA documentation you/your team has created**
  - [Design research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/ebenefits/features/view-update-dependents/research-design)
- **Links to any applicable research**
  - [Stakeholder kickoff](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/discovery/stakeholders/dec-18-2019.md)
  - [Discussion with Rainbows Team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/features/view-update-dependents/rainbow-meeting-notes.md)
- **SEO data**
  - TBD
- **Applicable analytics**
  - TBD

## Acceptance Criteria
- [x] Feedback has been shared with the eBenefits Team

**Comment by mnorthuis** [comment]
Notes from recent discussion with @jason-gcio and team:

- We discussed the options of the unauthenticated view of the new tool:
  - option 1) create an unauthenticated view of the tool itself
  - option 2) utilize a separate static page
  - Considerations: ensure there is SEO content about the tool accessible to search engines and general content must be readily available/manageable by stakeholders. 
  - Give this information, the team determined that option 2 would better meet the above considerations at this time. 
- eBen team will engage the Public Websites team to discuss the existing static page within Disability hub:  https://www.va.gov/disability/add-remove-dependent/
- This existing page should be considered as the starting point/unauthenticated view of the tool rather than creating another static page.  The eBen and Websites team can discuss how the page content (and possibly URL) can evolve to provide the best UX and visibility/access to the tool. 
- The static page may be moved out of the Disability hub to the root of va.gov - this is inline with the current Global IA redesign work (decoupling tools from benefits hubs) and allows for future growth of the dependents functionality.   This will be confirmed when the final IA is done.

IA work is in progress at this point.   Mikki will stay involved/up to date on discussions between eBen team and Public Websites team on the content revisions of the existing static page, and IA/URL will be finalized in collaboration with that effort.

**Comment by mnorthuis** [comment]
@jason-gcio Have you connected with the public websites team regarding updates to the existing static page https://www.va.gov/disability/add-remove-dependent/ ?

**Comment by jason-gcio** [comment]
@mnorthuis - Not yet, but we will.  I want to chat with Jim some more on this so we have something more concrete to share with them.

**Comment by mnorthuis** [comment]
@jason-gcio @sporeboy 
Draft structure for the Add/Remove Dependents form: 
- The existing add-remove-dependents page that is in Disability would be move out of that hub and up to the root level (URL would change) - content would be modified as needed.
- The form for adding/removing a dependent will also sit at the root level, the form will not require authentication
- All URLs are TBD
- Diagram shows these pages along with the View Dependents static page and tool. 


![image](https://user-images.githubusercontent.com/20994159/73783529-78a59380-4759-11ea-96dc-30cbdfaac7da.png)

OPTION:   The 2 static pages utilized (for 686c and for the view dependents tool) could be combined into one static page that provides information viewing/adding/deleting.  Considerations for this would be how complicated/long does the static content get, and does the login module required for the view tool discourage those that want to complete the form.

**Comment by jason-gcio** [comment]
@mnorthuis - thank you, this is helpful!

**Comment by mnorthuis** [comment]
@jason-gcio @sporeboy 
Final IA is documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-view-dependents.md

Please let me know if you have any questions. This issue can be closed at your discretion.

**Comment by mnorthuis** [comment]
Revisions to this IA have been made based on the addition of the Add/remove dependents form 686c.  Please reference the combined IA for that work (linked below).  It does include some modifications to the URLs and breadcrumbs for this tool as well as a slight change in handling authenticated users.  

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/information-architecture/ia-reviews/ebenefits-dependents.md

Please let me know if there are any questions.  This issue can be closed at your discretion.
