### ISSUE TITLE
PDF Upload Content Change

### ISSUE THREAD

**Issue by thehastingsp** [department-of-veterans-affairs/va.gov-team#45470]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*
Current PDF upload instructions are misleading as they instruct users to scan documents to their mobile phone, when the expected action is to take a photo and convert it to a PDF. I'm proposing a change to the language and would like a review. 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  Fall
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

![CURRENT UPLOAD](https://user-images.githubusercontent.com/68615337/183666685-44be78ba-102e-45e6-81dd-1851b5fc868d.png)

![PROPOSED](https://user-images.githubusercontent.com/68615337/183666698-e11dfdf4-844f-4b8e-9535-ec0bd893d1b1.png)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: September
- Estimated staging review date: Not sure
- Content and IA work needed by: August 18

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [x] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Sade Ragsdale
-	Designer: Pam Hastings
-	FE engineer: Robin Garrison
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by thehastingsp** [comment]
Here's the copy I'd like to review for clarity and possible improvement. I'm purposely adding the term convert as it is easy to search "convert image to pdf" and find [this free service](https://www.adobe.com/acrobat/online/jpg-to-pdf.html). In lieu of giving them explicit instructions, I thought we might offer the information scent of the keyword to search. 

CURRENT:
You can upload your document in a pdf file format. `You’ll first need to scan a copy of your document onto your computer or mobile phone camera. `You can then upload the document from there.
Guidelines for uploading a file:
• File types you can upload: pdf
• Maximum file size: 100MB

SUGGESTED STARTING POINT:
You can upload your document in a pdf file format. You’ll first need to `scan a copy of your document onto your computer or take a picture of it with your mobile phone camera and convert it to a pdf`. You can then upload the document from there.
Guidelines for uploading a file:
• File types you can upload: pdf
• Maximum file size: 100MB

**Comment by thehastingsp** [comment]
hello @RLHecht we are hoping to move into testing soon, so wondered if we could get a review of the PDF upload language sooner rather than later. It's a small change, but may affect broader thinking about upload language, so wanted to be sure to surface it. Thank you!

**Comment by katherine-fung** [comment]
Hi @thehastingsp. I'm reviewing the content, and will try to have it back to your team as soon as possible! 

I do have a question about the instructions to scan onto your phone vs. take a photo and convert it to a PDF. It is possible to scan documents onto a phone, using pre-installed apps (Notes app on iPhone and Google Drive on Android). Those apps would automatically save the scan as PDFs. I'm curious if users currently aren't scanning because they don't know how to, given the lack of instructions. 

Would offering slightly more clear instructions for how to scan a document on your phone, rather than matching the instructions to what we believe is the current behavior (take a photo and convert to a PDF), lead to more favorable outcomes for Veterans? Scanning the documents through those apps 1. might be easier for people who have multi-page documents and need to save them as one PDF and 2. would avoid people having to seek out 3rd party online tools like Adobe for converting potentially sensitive documents. 

I'm also wondering if scanning would avoid creating PDFs that exceed the printed size limits.  

Here is **a draft** of what telling people to scan the documents might look like (not final or approved): 

<img width="502" alt="scan documents" src="https://user-images.githubusercontent.com/105367381/185461385-128a5412-df1e-418f-a489-d4661d3e94ea.png">

If your team's insights suggest that having people take photos and convert them to PDFs leads to more favorable outcomes for Veterans using this tool, I'm happy to work with that approach. I also have draft language for that! (not final or approved)

<img width="501" alt="convert photos" src="https://user-images.githubusercontent.com/105367381/185461462-e8c672e1-802e-448f-82c0-ff038a118b87.png"> 

I just wanted to surface the other considerations above. Either approach requires the user to do their own googling on how to successfully upload their documents (either by scanning, or by converting photos to PDF).

**Comment by thehastingsp** [comment]
@katherine-fung thanks for offering both options and your insights. Our hypothesis is that taking photos and converting is actually resulting in big files, so I would lean towards trying the first option. We plan on testing this in prototype so I suggest we go with option 1 and see if Veterans find it helpful and easy to follow. Thank you!

**Comment by thehastingsp** [comment]
@katherine-fung is it misleading to say "you'll first need to scan each document" when they may have a copy of it on their computer already? Perhaps we could say "we'll prompt you to locate your document on your device, or you'll need to scan it."?

**Comment by laurwill** [comment]
Hi @thehastingsp , Katherine is OOO so I'm picking up this work — here's some updated language for that option to use for testing. Let us know if you need anything else on this!

**H3: Step 3 of 5: New and relevant evidence (required)**

You’ll need to upload new and relevant evidence for your Supplemental Claim. This may include supporting statements (also known as lay statements) and other types of evidence.

If you already have a PDF of the evidence, you can upload it now.

If you need to scan your paper document to make a PDF, follow the steps here for the device you’re using:
- **On a computer connected to a scanner,** scan the document onto the computer. Then, save the file as a PDF.
- **On an iPhone,** scan the document using the Notes app. The file will automatically save as a PDF when you’re done scanning.
- **On an Android phone,** scan the document using the Google Drive app. The file will automatically save as a PDF when you’re done scanning.

BUTTON: Upload evidence

**Note:** If you have a slow Internet connection, large files may take longer to upload.

LINK: Finish this application later

We’ll save your application every time you make a change. Your application ID number is 13863.

**Comment by thehastingsp** [comment]
@laurwill got it thank you! I'll go ahead and close this and implement the changes.
