### ISSUE TITLE
Content review from Authenticated Experience, Profile for 1095-B

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#45511]
## What does your team need support for? 
- [ x] Making revisions to an existing online form, app, or tool on VA.gov

## What do you need help with?
  - [x ] Content support
  - [x ] IA support
  
We're adding a preference to profile notification settings for people to opt into paperless delivery for their 1095-B form. We have the following content needs:
1. We've placed this notification under the "health care" notifications group since it's related to health care. I see the content page is under "Records", and [the previous research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/1095b-tax-form/research/Research-Findings-Round1.md#finding-the-1095-b-document) suggests that's where the majority of folks the team talked to would look for it. Should we make a new group called "Records"?

2. Review copy in mock-ups, in the section starting with "Paperless delivery".... [One mock-up is for users who don't have an email address on file](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/v/LDyxMQ/a/JnEgDg9/r/z54Lnl/), and the other shows [when a user does have an email address on file](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/8ydMW9Y).  

A few notes: 
   - I'm not totally certain we need to include the "learn more" content, but it would surprise me if people know what this form is by the number alone.  Not everyone will have the context from the content page when they see this.
   - I took the labels and content from the most recent mock-up of that page, provided to me by the 1095-B team in [this slack thread](https://dsva.slack.com/files/U02PU62PKHR/F03SHRHUVFZ/1095-b_post-mvp_paperless_designs.pdf).  I'd like for them to be well aligned.
   - The proposed copy for the additional info component is as follows:
   > Your IRS 1095-B tax form is used to show proof that you had VA coverage in the most recent tax year. Due to changes in the Affordable Care Act (ACA) you no longer need a 1095-B tax form to file your federal taxes.  
   (line break, having a hard time with md formatting)
   **Note:** Some states have their own individual health care la. If you don’t have health coverage, you may be changed a fee when you file your state taxes.   
    (line break, having a hard time with md formatting)
    Learn more about which states have their own state health care laws (link to content page or healthcare.gov)
 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes

## When do you expect to launch your product to 100% of users?
  
December, but we won't need content review for this at that point.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

-[Product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/1095B-preference/README.md)
- [notifications page mock-up](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/a/8ydMW9Y)
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
We'd like to review this during office hours

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [x] Also, let's work asynchronously and meet if needed

## About your team

- Team name: 
-	OCTO-DE product owner: Samara Strauss
-	Product manager: Sharon Kasimow
-	Designer: Liz Lantz
-	FE engineer: Adam Whitlock
-	Product/team Slack channel: #accountexp-authexp

**Comment by andaleliz** [comment]
cc @cgednalske since you are so kindly taking this to office hours on behalf of our team 😄

**Comment by cgednalske** [comment]
Hello @andaleliz! Here are @DanielleThierryUSDSVA's suggestions from our office hours discussion: 

([Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1660164067461/b35d891f276b0de5205b140204ece5c08fa65cfe?sender=u28f508d646c449cc1afe4873))

**1.** It is fine to keep the addition in the **Health care** section for now. Danielle reached out to Mikki as well and they both agreed that we can revisit the possibility of adding a **Records** section if other items come up that might require it.

**2.** If permitted, suggested combining the two FAQ / additional info components to end up with just one with the following info:

 > **[expandable link] Learn about 1095-B form paperless delivery**
 >  
 > Your IRS 1095-B form is used to show proof that you had VA coverage in the most recent tax year.
 > 	
 > We mail you a paper copy of this form each year.
 > 	
 > If you want to stop getting paper forms, you can choose paperless delivery. We’ll send you an email every year when you can download your form from VA.gov. You can update this setting anytime.
 > 	
 > [link] Learn when you need a 1095-B form and how to download a copy


**3.** If not permitted to combine the two FAQs (legal reasons or otherwise) the content you have will work with the following changes:

- Change additional info component "Learn about paperless delivery of form 1095-B" to "Learn about paperless delivery"
- Separate out link in "We mail you a paper copy of your…." to more closely follow the combined example above.

**4.** We were not able to get to the alert during office hours. @DanielleThierryUSDSVA, do you think any changes are needed for the alert below? It's an alert type that you already approved in the past, so hopefully it’s still fairly close or good to go 🤞 

And thanks so much for going through all this for us! 😃 

<img width="221" alt="Screen Shot 2022-08-11 at 8 54 00 AM" src="https://user-images.githubusercontent.com/79372956/184429151-86d3a46f-3ad2-429a-b0fa-4990fa0f9082.png">

**Comment by andaleliz** [comment]
Thanks to both of you! This is all very clear; I'll update the mock-ups accordingly.  

@DanielleThierryUSDSVA please let me know if you have any updates to the alert.

**Comment by andaleliz** [comment]
@DanielleThierryUSDSVA I'm just going to use the more generic alert you approved back when we first worked on this 

"To manage settings for email notifications, first..." instead of being specific about the 1095-B. Going to close this out. Thanks!
