### ISSUE TITLE
Update the Button Pair web component in the VAOS application

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#45517]
Platform Design System team created the Button Pair web component. We should replace the existing Button Pair React component to the updated Button Pair web component. 
[Button pair web component details ](https://design.va.gov/components/button/button-pair)
 
---
## Known Differences
Tasks:
- Try out replacing the Button Pair React component with Button Pair web component and document any differences that appear
---
## Acceptance Criteria 
[ ] Replace Button Pair React components with Button Pair web component

**Comment by ryanshaw** [comment]
@simiadebowale It looks like most of not all of the button pairs are utilizing the [ProgressButton](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/forms-system/src/js/components/ProgressButton.jsx) and the [LoadingButton](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/loading-button/LoadingButton.jsx) components from `/src/platform`.

They are used together in VAOS [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/vaos/components/FormButtons.jsx).

Unsure if we should look further into this because:
- The buttons in use with VAOS are coupled with the form library in use
- The new component is still in the `USE WITH CAUTION: CANDIDATE` state
