### ISSUE TITLE
[Spike] VAOS Choose a date and time page alerts

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#45582]
### Request
Product and Design team are requesting help from VAOS FE Engineering team to understand the logic that triggers the alerts on the Choose a date and time page

### Goal
The team would like to [update the user flows in VAOS](https://www.figma.com/file/xRs9s6QWoBPRhpdYCGc3cV/User-Flow?node-id=267%3A19283). 

### Screenshots

1. Login: cecil.morgan@id.me
- Type of care: Mental health 
- VA location: Springfield VA Clinic
- Clinic: Telehealth Spring MH Provider 

![Screen Shot 2022-08-15 at 11.23.23 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/7a0c4c34-4fcd-4597-9d22-18334bc74a79)

2. Does this alert still exist? 
![Screen Shot 2022-08-15 at 11.25.32 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/ca0380f6-fb36-4051-b240-27793bc29f01)

3. Unable to re-create it in staging. 
Login: cecil.morgan@id.me
- Type of care: Mental health 
- VA location: Springfield VA Clinic
- Clinic: Mental Health Clin A

![Screen Shot 2022-08-16 at 1.59.15 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/42961fa4-3ec2-4764-9c0c-fbd91c032985)

---

## Tasks
- Answer the following questions:
  - Q1: What are all the alerts on the `Choose a date and time` page? Please provide mobile screenshots. 
  - Q2: What triggers these alerts to show? 
  - Q3: For item number 3 (double stacked error), was that a bug? We can't replicate in staging. If not a bug, what triggers the alert?

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by jenniemc** [comment]
@outerpress @ldelacosta 

Settings: facility is configured for Direct and Request enabled

This only happens when user enters TODAY as preferred date (i.e.  user enters 10/1/2022 but next available slot is on 11/22/2022)

Recommendation: 
1. disallow users to enter TODAY as preferred date
2. have the calendar display the month the earliest appointment is available


 
<img width="349" alt="Earliest-date-warning-request-enabled-empty-calendar" src="https://user-images.githubusercontent.com/54327023/193466072-5d58ec1a-3e8f-4708-a260-59f0a2d10f96.png">
<hr>

Settings: facility is configured for Direct enabled and Request disabled 

This only happens when user enters TODAY as preferred date (i.e. user enters 10/1/2022 but next available slot is on 10/22/2022

Notice there is no link to request for earlier appointment button

<img width="346" alt="earliest-date-warning-request-disabled-empty-calendarpng" src="https://user-images.githubusercontent.com/54327023/193466584-59c4f9e2-aa90-40ad-b3ed-df8408630b89.png">

<hr>
Settings: facility is configured for Direct and Request enabled. Clinic have not made available future appointments slots.



User enters a preferred earliest date in the future (tomorrow or later) but there are NO slots for the clinic

<img width="346" alt="earliest-date-info-request-enabled-empty-calendar" src="https://user-images.githubusercontent.com/54327023/193467029-d5c98600-bf76-48f1-996a-1523350ffe23.png">

<hr>


Settings: facility is configured for Direct enabled; Request is disabled


User enters TODAY as preferred earliest date 

First message comes from entering TODAY as preferred date. Second error message is from a failed api fetch call for appointment slots

Recommendation:
1. disallow users to enter TODAY as preferred date. It will eliminate the first warning message

<img width="350" alt="double-error-no-appointment-warning-request-disabled" src="https://user-images.githubusercontent.com/54327023/193605848-481f0806-3d5f-4464-a62d-4089f9b1dccb.png">


<hr>

Settings: facility is configured for Direct enabled; Request is enabled

User enters future date as preferred earliest date 

error message is from a failed api fetch call for appointment slots

<img width="457" alt="error-finding-appointment-time" src="https://user-images.githubusercontent.com/54327023/193606943-fa80c2d8-3f0b-4561-b4c6-87f0249951e5.png">


<hr>
We don't show this message anymore

![image](https://user-images.githubusercontent.com/54327023/193631103-bfda2a97-9999-4801-9e87-a4b8b5223875.png)

**Comment by outerpress** [comment]
Thank you @jenniemc , this is great!

One follow-up question regarding the error that shows when the API fetch for appointment slots fails (copied below):
* What does that error look like when requests are disabled?
* If it looks the same, what happens when you click the link to "submit a request for an appointment"?

> Settings: facility is configured for Direct enabled; Request is enabled
> User enters future date as preferred earliest date
> error message is from a failed api fetch call for appointment slots
> ![image.png](https://images.zenhubusercontent.com/5f7ce3163782a585b910eaf3/aa2ac960-10fe-490b-b286-187121777e45)

**Comment by jenniemc** [comment]
here is the screenshot when the request is disabled.
<img width="295" alt="Screen Shot 2022-10-24 at 10 56 07 AM" src="https://user-images.githubusercontent.com/54327023/197595339-2386669b-d52c-4631-8517-567a96f129ab.png">

**Comment by outerpress** [comment]
Thank you @jenniemc ! From our chat today where you answered my questions:

> What does that error look like when requests are disabled?

The error looks the same.

> If it looks the same, what happens when you click the link to "submit a request for an appointment"?

The link doesn't do anything, it's broken.

FYI @ldelacosta

**Comment by jenniemc** [comment]
@outerpress, Happy to walk through the alert screens anytime. 

> What does the error look like when the requests are disabled? 

Assuming the user wants to go by the way of a request flow, he will not see the error message. Instead, he will receive a warning message that facility does not allow online request. 
<img width="295" alt="Screen Shot 2022-10-24 at 10 56 07 AM" src="https://user-images.githubusercontent.com/54327023/197630719-4c4eeb93-9400-42b2-bc20-ae04b6efbd3b.png">
If at this point the user selects one of the clinic options and there is a failed api call for appointment slots, then the error message looks the same.
<img width="457" alt="error-finding-appointment-time" src="https://user-images.githubusercontent.com/54327023/197633904-8129185b-79de-4322-8524-5102e3cb1d56.png">



> If it looks the same, what happens when you click the link to "submit a request for an appointment"?

The link doesn't do anything, it's broken.
