### ISSUE TITLE
STEM: Content Reviews - External

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#4577]
- [x] Review with VA / DEPO Content
- [ ] Update GH content doc, as necessary

**Comment by amyknox** [comment]
@desireeturner - this will carry over to Sprint 39

**Comment by amyknox** [comment]
@peggygannon - The Booz team is working on updates to the VA.gov Education form routing wizard and the 22-1995 application. Last year we incorporated a short-term solution for individuals to apply for the Rogers STEM Scholarship within the 22-1995 form.  As it turns out, too many individuals who don't meet the eligibility requirements are applying and 90% of the applicants are being denied for various reasons, chief among them 1) they're not in a STEM field or 2) they don't meet the "exhaustion of benefits" requirement. 

Full prototype is here: https://bahdigital.invisionapp.com/share/7PIACMAVBHD#/screens

Specific screens / language we'd like you to review:
1- The updated wizard content - Q3, the helper text and confirmation question that appear
https://bahdigital.invisionapp.com/share/7PIACMAVBHD#/screens/296029276

2 - The info alerts and warnings on the STEM Scholarship page 
https://bahdigital.invisionapp.com/share/7PIACMAVBHD#/screens/296029306

We refer to that last screen as "Worst Case Scenario" - the individual is not in the right benefit program, they're not STEM and they've not exhausted their benefits, so they get all the info alerts AND the most dire warning.  Note that we can't prohibit them from applying at this point but we can and do alert them that they probably aren't eligible.  

We're prepping for usability testing next week will incorporate your feedback as we're able. 

Thanks in advance. Look forward to your input.

**Comment by peggygannon** [comment]
Hello, @ccruzgra and @tmcmurdo I've updated the mockup with my content suggestions/recommendations. Please let me know if you have any questions. 

Thank you!

**Comment by ccruzgra** [comment]
Hi @peggygannon thanks for your feedback! We'll take a look and let you know if we have any questions.
