### ISSUE TITLE
Platform website KPIs DOMO dashboard maintenance

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#45824]
**User stories**
As a product manager of the Platform content team,
I want to provide access to the Platform website DOMO dashboard to other Platform teams,
So that they have website data (such as page views, engagement, etc.) about the content they maintain on the website.

As a new product manager of the Platform content team,
I want to clean up the existing DOMO dashboard for the Platform website,
So that I can have an organized/clean view of data to present to other Platform teams about content they care about on the website.

**Request**
Some items discussed that could use maintenance/"cleaning" during office hours are:
- Removing the extra "workspaces" being shown on the "Pageviews by workspace (click to drill down)" visualization.
- Reviewing and adjusting as needed, filters set on other visualizations that do not update when the higher-level filter is changed. Example: filtering to the "collaboration cycle" workspace on the top left side does not currently update the Usage trends, or unique page views.

Screenshots attached.

![Screen Shot 2022-08-17 at 10 27 18 AM](https://user-images.githubusercontent.com/106613300/185161721-1ac101f1-26b3-43c9-9ba6-635275db7655.png)
<img width="1383" alt="Screen Shot 2022-08-17 at 10 24 42 AM" src="https://user-images.githubusercontent.com/106613300/185161771-ff916787-9159-4967-82d8-c65d7d7e2bd0.png">

**Comment by chloedotbrown** [comment]
@jonathan-epstein13 - As Vicky mentioned in her ticket above, we need to add the `workspace` field to all the GA-related data sources powering these cards, so that Platform teams will be able to filter by their workspace.

### Problem statement
Currently, we have two GA-related datasets that are output from ETLs powering cards on this dashboard:

- [Platform Website Engagement](https://va-gov.domo.com/datasources/0aa9363a-50e7-42bf-a3c9-b0e5acfbad76/details/overview) - Filters for only Platform website data, creates a URL substring to remove main page address, removes opt-out behavior, and adds capitalization to page titles.
  - [Platform IA Pageviews](https://va-gov.domo.com/datasources/286b81a7-1338-4541-aba1-3e831acbc7bf/details/overview) _(2nd tier ETL)_- Performs same substring as above, cleans up link click event actions, removes opt-outs **_and_** homepage visits, creates `workspace` fields, standardizes `workspace` values to group previous iterations in same categories, and additional text cleanup.

Because the `workspace` field creation happens only in the 2nd ETL, the field is only available as a filter for that dataset. Any cards connected to the Website Engagement data won't respond to this filter, because the field doesn't exist there.
In addition, the `workspace` field needs more safeguards to remove or recategorize incorrect values like ")", ")**", "Index.htm", etc.

### Suggested steps

- [ ] Move the steps to create `workspace` field upstream from the ETL creating Platform IA Pageviews to the ETL creating Platform Website Engagement. 
- [ ] Once completed: remove these steps from Platform IA Pageviews ETL, so it only has to be maintained in one place.
- [ ] Review ETLs causing faulty `workspace` values. Should they be removed? Should they be recategorized into valid workspaces?
- [ ] Add steps to ETL that accomplish tasks above.
- [ ] QA new output data to ensure only correct fields appear in `workspace` filter.
- [ ] QA new output data to ensure that totals are correct and no extra data is filtered out.
- [ ] QA dashboard to make sure all GA-related cards (except opt-outs) filter by workspace.
- [ ] Rename datasets to reflect current team names and better differentiate data they contain.

### Acceptance criteria
- [ ] All GA cards (minus opt-outs) filter by workspace.
- [ ] Workspace filter only shows correct values.
- [ ] Data still passes accuracy checks.

**Comment by jonathan-epstein13** [comment]
@vbellissimo we are looking over the datasets/ETLs, making the necessary adjustments, and we will update the ticket.

**Comment by vbellissimo** [comment]
Thanks, @jonathan-epstein13 . I appreciate it!

**Comment by chloedotbrown** [comment]
Happy Friday, @vbellissimo! [Your dashboard](https://va-gov.domo.com/page/1182586883) has been [QA'ed](https://docs.google.com/spreadsheets/d/1x59Iktvn0whO55T4VW3kh-fSWIWfJH8EjMK6_fq4EQk/edit?usp=sharing) and is ready to go. 

All GA cards should now filter by workspace, with the exception of internal opt-outs and the search metrics at the bottom of the page. In addition, we've cleaned up the `workspace` field to weed out errors and misspellings generating by incorrect URLs. 

Unfortunately, these may appear in the future, if folks publish new kind of incorrect URLs that don't match the patterns we're already filtering for. If that happens and you see anything in your workspaces that shouldn't be there, please let us know in the [#vfs-platform-support](https://dsva.slack.com/archives/CBU0KDSB1) channel. It will be a manual process for us to add the filter, but it should only be 5 minutes of work, so does not require a new Github ticket.

Closing this ticket for now, but if you have any questions or concerns please reach out!

**Comment by vbellissimo** [comment]
@chloedotbrown This looks so good! I wish share this info with my team. I appreciate your attention to detail and work put into this. Have a great weekend.
