### ISSUE TITLE
[SPIKE] Explore How We Might Isolate Check-in and Pre-Check-in from VA.gov Outages

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#45832]
## Timebox
2 day

## Problem Statement
Based on the deployment that broke the web controls in Production and the discussion we had after stand-up, we want to determine the practicality of self-hosting the check-in application.

Slack [thread](https://dsva.slack.com/archives/C02UP02HHGX/p1660677940622219)

## Questions to answer

- Is vets-website just a hosting infrastucture for us, or do we gain other things from using it? (e.g. feature toggles)
- what advantages are there to not using the vets-website infrastructure?
- what drawbacks are there to not using the vets-website infrastructure?
- what hosting solutions are available to us? (lambda/S3/etc)
- how much effort would it take to pull in VA web components/minimal header/footer/etc.
- would we be shooting ourselves in the foot if we need full authentication later?
- etc.

**Comment by loripusey** [comment]
@acrollet can you add some detail to the problem statement?

**Comment by acrollet** [comment]
I've dug into this and also discussed with @brianseek, some conclusions:

**Q:** Is vets-website just a hosting infrastructure for us, or do we gain other things from using it? (e.g. feature toggles)
**A:** vets-website provides several additional pieces of functionality for us, including:
- Analytics integration
- Monitoring integrations such as Sentry and Datadog
- CI/CD infrastructure
- Use of trusted www.va.gov domain
- Use of vets-api
- platform operations support
- covered by ATO

**Q:** what advantages are there to using the vets-website infrastructure?
**A:** In addition to the functionality listed above, using the vets-website infrastructure prevents us from having to get into the business of hosting our hosting and deployment pipeline, and taking on additional operations, support and infosec burdens. In short, it lets us focus solely on delivering a high-quality application.

**Q:** what advantages are there to not using the vets-website infrastructure?
**A:** The biggest advantage would be complete control over our own stack, giving us the ability to reduce some of the many dependencies brought in by various www.va.gov  components. (more info [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/research/fe_perf_analysis.md)) 

**Q:** what hosting solutions are available to us? (lambda/S3/etc)
**A:** Generally the options most easily available to us are all offered via AWS GovCloud, including:
- S3 with static hosting
- lambda
- elastic beanstalk
- stand up custom hosting infrastructure with EC2 and/or Elastic Container Service

Options likely not available to us, because they are not on GovCloud:
- Cloudfront
- Lambda @edge

All these options would require high effort to create a deploy pipeline and pursue any necessary ATO modifications.

**Q:** how much effort would it take to pull in VA web components/minimal header/footer/etc.
**A:** @brianseek and I discussed and assume it to be low to medium effort, I didn't pursue any prototyping/PoCs to validate.

**Q:** would we be shooting ourselves in the foot if we need full authentication later?
**A:** Unknown, but quite possibly. This should probably be the subject of its own spike if we decide we need to do our own hosting.


Recommendation:

- let's not spend more cycles exploring this for now, but instead focus effort on #44278 and [simplifying the header & footer as much as possible](https://dsva.slack.com/archives/C01DBGX4P45/p1663076199994119?thread_ts=1662746993.807039&cid=C01DBGX4P45) and re-evaluate performance afterwards.

**Comment by loripusey** [comment]
Thanks @acrollet , I agree with your recommendations.
