### ISSUE TITLE
[SPIKE] Distributed logging and traceability

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46180]
### **User Story**
As an engineer, I would like to easily trace the logs across all the services, so that I can interpret the workflow by looking at the logs

### Tasks
- Determine how we might implement this

### **Description**
Currently, veteran facing side team uses `lorotaUuid` to correlate the logs across vets-api, CHIP, Lorota & Clinician workflow. As LoROTA generates temporary `lorotaUUID` for day-of check-in & pre-check-in, downstream service Vista doesn’t have knowledge on `lorotaUUID` & developers get lost beyond LoROTA while debugging any failure.

One approach could be to define a `request-id` in the header while initiating any request & pass it across all the services to include in logs.  It enables not only identifying logs in Vista for any user workflow but will also help in segregating logs by workflow origination.  

For example, consider a scenario where a veteran tries to check in but is dropped with a failure in the system & a staff member checking in the veteran from the staff facing app.  Currently, when the issue gets reported to the developer, debug logs show only halfway through the workflow with `lorotaUUID` & engineers cannot identify it from debug log until verbally told about the staff member initiated check-in.

**Comment by loripusey** [comment]
@kanchanasuriya Do you know what this ticket is for?

**Comment by kanchanasuriya** [comment]
@loripusey Pls find the details below.

### **User Story**
As an engineer, I would like to easily trace the logs across all the services, so that I can interpret the workflow by looking at the logs

### **Description**
Currently, veteran facing side team uses `lorotaUuid` to correlate the logs across vets-api, CHIP, Lorota & Clinician workflow. As LoROTA generates temporary `lorotaUUID` for day-of check-in & pre-check-in, downstream service Vista doesn’t have knowledge on `lorotaUUID` & developers get lost beyond LoROTA while debugging any failure.

One approach could be to define a `request-id` in the header while initiating any request & pass it across all the services to include in logs.  It enables not only identifying logs in Vista for any user workflow but will also help in segregating logs by workflow origination.  

For example, consider a scenario where a veteran tries to check in but is dropped with a failure in the system & a staff member checking in the veteran from the staff facing app.  Currently, when the issue gets reported to the developer, debug logs show only halfway through the workflow with `lorotaUUID` & engineers cannot identify it from debug log until verbally told about the staff member initiated check-in.

**Comment by loripusey** [comment]
too old, closing
