### ISSUE TITLE
[Design] Same Office Checkbox Location

### ISSUE THREAD

**Issue by YanaRoy** [department-of-veterans-affairs/va.gov-team#4620]
## User Story:
As a designer on BaM, I need to move the same office checkbox so that it can apply to all contested issues.

## Tasks
_The steps that must be done by the team to complete the acceptance criteria_
- [x] Change the design of checkbox to apply to all issues

## Acceptance Criteria:
_The requirements that must be met in order to mark this user story as completed_
* The checkbox has been moved to the proper location of the form

**Comment by kevinstachura** [comment]
The new design for the 'same office' screen can be located here:

https://vsateams.invisionapp.com/share/PMVHSE4DRN6#/400137224_HLR_Contested-Issues_same-Office-No

Some notes:
- This screen will happen later in the flow than the previous version - instead of being nested within a particular issue, it will happen after all sub-choices (within a particular issue) have been chosen.
- We are assuming that the 'notes' box for a given issue (located [here](https://vsateams.invisionapp.com/share/W5U21BDFTQK#/400511836_HLR_Contested-Issues_questions-Tinnitus-No-Office-Option)) may still be implemented, but it will be the **only** 'sub' step within a given issue.
- After all sub steps for each issue are completed, this 'same office' will be the next screen to show.

@Mottie let's talk about this when you're ready to get some frontend dev implementation going - Christian and I are still going through and cleaning up this Invision project as it has many iterations living within it. Want to be as clear as possible.
