### ISSUE TITLE
VA loan numbers from Benefits team

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#46233]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [x] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
We're having trouble finding answers to the following, and were hoping someone from the sitewide content team might have better answers: 

- What are the different ways in which Veterans identify a loan number? (e.g. Loan identification number, loan identifier, loan account number)
  - Are these all referring to the same thing or different things? If they are different things, could we explain that difference to the user or provide validation so they don't accidentally submit the wrong number?
 - What is (if any) the standard format of a VA loan number? Has it changed over history (e.g. 8 characters to 12 characters)
   - If it has always been the same standard, we should validate for those standards accordingly
   - If the VA loan number only contains numbers, use the number input field; otherwise, use the text input field

[We found documentation online of a LIN (Loan identification number)](https://github.com/department-of-veterans-affairs/va.gov-team/issues/45026#issuecomment-1218012071) which states that they are 12 characters in length, but have been unable to confirm this elsewhere.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Staging link](https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880/introduction)
- [Prototypes](https://preview.uxpin.com/65c0623a799c268173fe1a3cb4375f9ce00ad820#/pages/137557312/simulate/sitemap)
- vets.gov.user+245@gmail.com
- vets.gov.user+228@gmail.com
- [Passwords](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Benefits
-	OCTO-DE product owner: @mattpointzxer0 
-	Product manager: @saderagsdale 
-	Designer: @jsokohl 
-	FE engineer: @Mottie 
-	Product/team Slack channel: #benefits-team-1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by laurwill** [comment]
Hi @joshkimux ,
We're reaching out to our home loans stakeholder with these questions — we'll update you when we hear back!

**Comment by laurwill** [comment]
Hi @joshkimux ,

We heard back from our stakeholder — he reached out to 2 SMEs, and I'm pasting their responses below. Key takeaways from my reading:
- LIN and loan identifier are the same, but loan account number is different and more tied to the lender
- loan numbers are always 12 digits (numbers only)

Let us know if you need more info here!

First response:
“I would say Loan Account number would be more of a reference to the lender’s loan number which is variable. It could help us track down a loan nonetheless but the term “loan identification number” or LIN or the loan identifier I would expect to mean the same thing.

VA Loan numbers always take the format: xx-xx-x-xxxxxxx the first two sets of digits are jurisdictional locators (ex: 40-40 means New Mexico) the middle digit tells us what kind of loan it is (direct, guaranteed, refunded, partial claim) and the last seven digits are the identifier.”

 Second response:
“The VA loan number from VA (sometimes shortened to LIN) is in this format xx-xx-x-xxxxxxx.  No letters, just numbers and is the LIN number in VA records.  At a time before computers, we would sometimes see the last seven digits and the state afterwards when the number was hand written instead of the full 12 digits.   (xxxxxxx NM for Heather’s  New Mexico example)   Also, while generally loans in the past 20 plus years have had the same two digits begin a loan number (40-40-x-xxxxxxx), some LINs previously had the same number of digits; however, when there was more than one VA office in a state (CA, TX, or NY for example) the LIN will have a different XX and XX to begin the loan number and define the office location.  The state would be the first two numbers and is consistent with what is used now.   I don’t remember an office code for the second set of numbers, but they are rare now as most of these loans would be paid in full.”

**Comment by joshkimux** [comment]
This is amazing @laurwill , thank you so much for verifying! @jsokohl looping you back in here, I think we have what we need to write better messaging.

**Comment by joshkimux** [comment]
@RLHecht absolutely, thank you again, this was a huge help 🙏
