### ISSUE TITLE
Update Vets API Rspecs to handle change in domains

### ISSUE THREAD

**Issue by ajmagdub** [department-of-veterans-affairs/va.gov-team#46292]
Currently the Vets API rspec tests match on method and uri. In order to accommodate the new domains the VCR Cassette matching should be changed to match on method and path so that any change in hosts will still allow the tests to pass.

**Comment by JRRoof** [comment]
**Note:** In some cases, vets-api code makes subsequent Lighthouse API requests to iterate over paginated data. It is important to ensure that vets-api makes these additional request using the same API URL defined in the settings file (i.e. the forward proxy address and port) rather than directly using the API links provided as part of the API response. This might require some code changes in vets-api that swap out the host portion of the API address to the one defined in the settings.

**Comment by ldelacosta** [comment]
Reference the [ RFC overview ](https://github.com/department-of-veterans-affairs/va.gov-platform-architecture/pull/46) from Cloud Isolation Team.

**Comment by ldelacosta** [comment]
[Hostname Transition Plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/f3389a1a1aed15d54f9f0f2580f6c2ea188cf9e8/platform/engineering/infrastructure/hostname_transition_plan.md) (not owned by Cloud Isolation Team anymore). Release Tools and Identity team will be the owners for this initiative.
