### ISSUE TITLE
Make Case & Present

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#46318]
## Tasks
- Build case/presentation on why this is important
- Present to Stephen & Patrick
- Determine if we can move forward with it

**Comment by benbrasso-agile6** [comment]
I moved this out of this sprint

**Comment by benbrasso-agile6** [comment]
Should be looking for feedback from vsignals for "poster" "QR code" "text"

**Comment by benbrasso-agile6** [comment]
https://dsva.slack.com/archives/C022AC2STBM/p1664316112669309

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell would you mind adding any comments/thoughts to this [presentation outline](https://docs.google.com/document/d/13tiOp5FWISe5GAwUves-fr61YZfe83FzQYfYZdR4oZQ/edit#)? thanks

**Comment by kristenmcconnell** [comment]
@benbrasso-agile6 I added some comments. Overall, the structure and points are good.

**Comment by benbrasso-agile6** [comment]
@kristenmcconnell @loripusey could you review this presentation when you have time? https://docs.google.com/presentation/d/1pwgrjvJU7XH-rQjIgcsuKdkSHSkIHPmM9khK1a2NlNY/edit#slide=id.g11bc03a7278_0_768

@kristenmcconnell I didn't include anything related to "From Corpus Christi... Veterans aren't sure what appointment types can use PCI to check-in" because I don't see the exact connection. For example, we wouldn't send a "You can't check in for this appointment" message to Veterans at clinics that aren't PCI-enabled. If I'm missing something, let me know. 

@sarahknoppA6 for awareness, we'll probably want to schedule a meeting with Patrick and Stephen to discuss this. But, will want to hear if Lori or Kristen have any thoughts around that. And, Stephen is now out, so it may just wait a week or so.

**Comment by loripusey** [comment]
Looks great and well laid out!

**Comment by loripusey** [comment]
@sarahknoppA6 need to set up a meeting, please sync with @benbrasso-agile6

**Comment by sarahknoppA6** [comment]
@loripusey please include or link to relevant information about the ticket in the future- there is no context about what this ticket is about.

**Comment by loripusey** [comment]
the information is in the parent Epic

**Comment by sarahknoppA6** [comment]
There is no link to an epic that I can see on this ticket

**Comment by loripusey** [comment]
![image](https://user-images.githubusercontent.com/86678742/196746838-dfe48494-adf6-409b-83b8-1c111f3b781c.png)

**Comment by loripusey** [comment]
sometimes GitHub & ZenHub doesn't show the Epic even though there is one there, I have run into that issue before

**Comment by sarahknoppA6** [comment]
Thanks. It appears to be a github/zenhub issue, it's just not showing on my screen at all

**Comment by sarahknoppA6** [comment]
sorry!

**Comment by loripusey** [comment]
@benbrasso-agile6 were we going to present this to Stephen/Patrick? What was the next step on this one?

**Comment by benbrasso-agile6** [comment]
Yes, @sarahknoppA6 scheduled a meeting and it's on the calendar for Thursday
