### ISSUE TITLE
Alert content review from Authenticated experience, profile team

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#46357]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [x] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  
  
*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

We have an edge case in profile's miltiary information section where the API could return a 403 unauthorized response, and we can't access the person's military information. This could happen to a Veteran or non-Veteran (e.g. a contractor like myself), and if we get a 403, we can't tell which one the person is.

We need the following content reviewed for a warning alert:

**We can’t match your information to any military service records**
We’re sorry. If you want to learn what records are available, call the Defense Manpower Data Center (DMDC) at [800-538-9552](tel:8005389552) (TTY: [866-363-2883](tel:8663632883)). Their office is open Monday through Friday (except federal holidays), 8:00 a.m. to 8:00 p.m. ET.
If you think there might be a problem with your military service records, you can learn how to apply for a correction.
[Learn how to correct your military service records on the National Archives website.](https://www.archives.gov/veterans/military-service-records/correct-service-records.html)

![image](https://user-images.githubusercontent.com/55992116/187294064-f4e380f1-377c-442c-9830-f85d37433014.png)

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @andaleliz! I made a few minor tweaks + a few things I want to call out for your thoughts:

- It felt like we needed something after "We're sorry" since we took the sentence after it out so as not to repeat the header.  
- "what records are available" felt a little too vague. Let me know what you think of the edit there.
- For ease of scanning, I think we should put each "If" statement on its own line and bold it. Thoughts?

## We can’t match your information to any military service records

We’re sorry for this issue. 

**If you want to learn what military service records may be on file for you,** call the Defense Manpower Data Center (DMDC) at 800-538-9552 (TTY: 866-363-2883). The DMDC office is open Monday through Friday (except federal holidays), 8:00 a.m. to 8:00 p.m. ET.

**If you think there may be a problem with your military service records,** you can apply for a correction.
[Learn how to correct your military service records on the National Archives website](https://www.archives.gov/veterans/military-service-records/correct-service-records.html)

**Comment by andaleliz** [comment]
These all make sense to me! Thanks Danielle. I will update the mock-ups. 🎬
