### ISSUE TITLE
Burials redirects for parity and rewriting 

### ISSUE THREAD

**Issue by AnneHurley** [department-of-veterans-affairs/va.gov-team#4645]
### Instructions
- Requests for redirects need to be submitted **AT LEAST** 2 weeks in advance.  Some redirects take significant amount of time and coordination to implement, so start the process as soon as you know you will need one. 
- This issue will be used from initial request through implementation of the redirect to ensure all individuals working on this are notified of status updates.  Please do not create multiple issues to track different steps.
- It is your responsibility to notify VA stakeholders of pending redirect.  

### Description
*This ticket represents all the Parity and Rewriting legacy redirects for the Burials hub on VA.gov. A list of all the old URLs, and where they are redirecting, with a few we aren't moving for now, is attached.*

### Requestor Info
Public Websites/Anne Hurley managing project for Burials and Cemetery SMEs.

### Implementation Date
**1/17/20** (Date communicated to stakeholders)

Please indicate when the redirect(s) needs to be implemented"
- [X] On the same date the new URLs launch
- [ ] Can happen within 1-5 business days after new URLs launch
- [ ] Other - Please indicate timing : 

**The requesting team is responsible for notifying the group working on this issue if the target date changes**

### Redirects Needed

Current URL  |  Redirect to new URL

[Burials redirects list v2-ah.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/4032875/Burials.redirects.list.v2-ah.docx)

### Steps to complete
- [X] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Redirect request is vetted and documented and implementation plan is clear - *@ Content & IA team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [x] Implementation team completes work - *@ Implementation team*
- [x] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by mnorthuis** [comment]
These redirects are vetted and ready to go when your team is ready to implement.

**Comment by Karak888** [comment]
@kelsonic please have these url's redirected and respond back when you have verified them in Prod?  Thanks!

**Comment by kelsonic** [comment]
To confirm, I'll be implementing these redirects:

Current URL  |  Redirect to new URL
---  |  ---
www.cem.va.gov/cem/burial_benefits/eligible.asp | www.va.gov/burials-memorials/eligibility/
www.cem.va.gov/cem/Women_and_Minority_Veterans.asp | www.va.gov/burials-memorials/eligibility/
www.cem.va.gov/cem/burial_benefits/burial_at_sea.asp | www.va.gov/burials-memorials/eligibility/burial-at-sea/
www.cem.va.gov/cem/burial_benefits/private_cemetery.asp | www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/
www.cem.va.gov/cem/burial_benefits/burial_flags.asp | www.va.gov/burials-memorials/memorial-items/burial-flags/
www.cem.va.gov/cem/hmm/index.asp | www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
www.cem.va.gov/cem/hmm/eligibility.asp | www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
www.cem.va.gov/cem/hmm/order_instructions.asp | www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
www.cem.va.gov/cem/hmm/apply_by_fax.asp | www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
www.cem.va.gov/cem/hmm/order_by_mail.asp | www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/
www.cem.va.gov/cem/pmc.asp | www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/
www.cem.va.gov/cem/pre-need/index.asp | www.va.gov/burials-memorials/pre-need-eligibility/
www.cem.va.gov/CEM/pre-need/FAQ/ | www.va.gov/burials-memorials/pre-need-eligibility/
www.cem.va.gov/cem/burial_benefits/committal_service.asp | www.va.gov/burials-memorials/what-to-expect-at-military-funeral/
https://www.cem.va.gov/cem/hmm/replacements.asp | www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/

And not these redirects:

Current URL  |  Redirect to new URL
---  |  ---
https://www.cem.va.gov/cem/hmm/types.asp | /burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/
https://www.cem.va.gov/cem/hmm/pre_WWI_era.asp | /burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/
https://www.cem.va.gov/cem/hmm/abbreviations.asp | /burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/
https://www.cem.va.gov/cem/hmm/emblems.asp | /burials-memorials/memorial-items/headstones-markers-medallions/types-inscriptions-emblems/
https://www.cem.va.gov/cems/listcem.asp | /burials-memorials/find-a-cemetery/

Does that sound right? 🙂

**Comment by mnorthuis** [comment]
That is correct to me.  Will let @AnneHurley to confirm as well.

**Comment by AnneHurley** [comment]
@kelsonic  @mnorthuis  - yes that looks great. 

And no rush but can one of you show me how you created that grid in the comment field so I can do that next time? I tried a few times but they ended up wonky.

**Comment by kelsonic** [comment]
Perfect! @AnneHurley Of course! I'll reach out to you via slack and show you real quick 🙂

**Comment by Karak888** [comment]
Thank you!  @kelsonic are you able to implement redirects for this?

**Comment by AnneHurley** [comment]
Thanks everyone!

**Comment by kelsonic** [comment]
I have a PR open for it 👍https://github.com/department-of-veterans-affairs/vets-website/pull/11436 Just need to validate with @ncksllvn that this is the right place to add those redirects in the code since this is the first time I'm adding cem.va.gov redirects!

**Comment by kelsonic** [comment]
@AnneHurley Could you validate to see if these redirects are live and as you're expecting? 🙂

**Comment by lunascoop** [comment]
Stakeholder comm has been sent. Redirect go-live date is **01/17**.

**Comment by lunascoop** [comment]
### Posting Slack thread for how to handle URL redirect below (screenshot)
**@RLHecht please see Mikki's last comment.**

_**Kelson Adams  6 days ago**_
@Anne Hurley @Selina Cooper @Mikki Need some help figuring out what we need to do with a specific redirect:

![image (2)](https://user-images.githubusercontent.com/42546515/72545671-61107480-3857-11ea-88fa-2d643e8574a4.png)



**_Kelson Adams  6 days ago_**
I currently have a follow-up PR ready to go with all of the redirects except the one mentioned above https://github.com/department-of-veterans-affairs/vets-website/pull/11459

**_Kelson Adams  6 days ago_**
Should I leave the /cem/burial_benefits/need.asp redirect for now until we can get more context? :slightly_smiling_face:

**_Selina Cooper  6 days ago_**
I think so. You have until the 17th.

**_Kelson Adams  6 days ago_**
Sounds good! Please reach out when we know the steps to implementing the last redirect and I'll send up a PR for it :slightly_smiling_face:

**_Anne Hurley  6 days ago_**
Thank you both so much!

**_Kelson Adams  6 days ago_**
Of course! Always happy to help!

**_Kara Kemahli  6 days ago_**
yes thanks all!  Certainly don't want to rush anything!
:+1:
1


**_Mikki Northuis  3 days ago_**
This one will take some coordination since it will include a redirect within drupal for an existing page and then a redirect for the legacy page...similar to the DIC page we did last month.  @RLHecht  may have some insight on coordinating that. I believe we will need to change the drupal page and implement that redirect first, then you can redirect the legacy page.

**Comment by RLHecht** [comment]
@lunascoop I can change that URL now if you want. So instead of /plan-a-burial it should be /schedule-a-burial? Let me know if I should go ahead.

**Comment by ncksllvn** [comment]
Okay, so -

1. We need to move `va.gov/burials-memorials/plan-a-burial/` to `va.gov/burials-memorials/schedule-a-burial/` via Drupal
1. Then, we need a server-side redirect from `va.gov/burials-memorials/plan-a-burial/` to `va.gov/burials-memorials/schedule-a-burial/`
1. Tomorrow, we need a client-side redirect from `cem.va.gov/cem/burial_benefits/need.asp` to `va.gov/burials-memorials/schedule-a-burial/`

**Comment by lunascoop** [comment]
@mnorthuis can you confirm where the URL should redirect to? It seems it may be **/plan-a-burial** instead of **/schedule-a-burial**.

![image (2)](https://user-images.githubusercontent.com/42546515/72548884-a041c400-385d-11ea-92a6-cd9281d9889c.png)

@RLHecht Once Mikki confirms the correct redirect URL, you can move it in Drupal.

**Comment by mnorthuis** [comment]
There is one more item for the steps/list above @ncksllvn  - there is an old vets.gov URL that is currently redirected to the /plan-a-burial/ page, so that redirect should be updated as step 4.  

In summary, these URLs: 
https://www.va.gov/burials-memorials/plan-a-burial/
https://www.vets.gov/burials-and-memorials/burial-planning/
https://www.cem.va.gov/cem/burial_benefits/need.asp

Should be redirected to: 
https://www.va.gov/burials-memorials/schedule-a-burial/



1. We need to move `va.gov/burials-memorials/plan-a-burial/` to `va.gov/burials-memorials/schedule-a-burial/` via Drupal **AND** ensure all nav options updated. 
1. Then, we need a server-side redirect from `va.gov/burials-memorials/plan-a-burial/` to `va.gov/burials-memorials/schedule-a-burial/`
1. Tomorrow, we need a client-side redirect from `cem.va.gov/cem/burial_benefits/need.asp` to `va.gov/burials-memorials/schedule-a-burial/`
1. Update current server-side redirect of `https://www.vets.gov/burials-and-memorials/burial-planning/` to `va.gov/burials-memorials/schedule-a-burial/`

**Comment by RLHecht** [comment]
@nick and @Mikki All the Drupal work for the Plan a Burial/Schedule a Burial redirects should be done now. I changed the URL of the page, fixed the name in the top nav as well as the left nav and made sure that on other pages the link points to the node ID so it will update automatically. Let me know if there's anything else I need to do before redirects are in place.

**Comment by ncksllvn** [comment]
All of these things are done! And it only took me all day. @RLHecht please confirm and close 😄

**Comment by ncksllvn** [comment]
There are three broken redirects - 

1. www.cem.va.gov/cem/burial_benefits/eligible.asp, 
1. www.cem.va.gov/cem/burial_benefits/burial_at_sea.asp
1. www.cem.va.gov/cem/burial_benefits/private_cemetery.asp

The first was a tech issue and am [fixing now](https://github.com/department-of-veterans-affairs/vets-website/pull/11522). The bottom two redirect to the page as specified in the spreadsheet. However the destination does not exist. The destination listed is `https://www.va.gov/burials-memorials/eligibility/burial-at-sea/`, a 404. What's the correct destination?

**Comment by RLHecht** [comment]
@ncksllvn This link is should have an "and" between burials-memorials: https://www.va.gov/burials-and-memorials/eligibility/burial-at-sea/

**Comment by lunascoop** [comment]
@mnorthuis  are these the correct URLs?  I know there may be another issue with the first one mapping to **"burials-and-memorials."**

Current URL  |  Redirect to new URL
---  |  ---
www.cem.va.gov/cem/burial_benefits/burial_at_sea.asp | www.va.gov/burials-and-memorials/eligibility/burial-at-sea/
www.cem.va.gov/cem/burial_benefits/private_cemetery.asp | https://www.va.gov/burials-and-memorials/eligibility/burial-in-a-private-cemetery/

**Comment by ncksllvn** [comment]
Per @mnorthuis, the redirects are okay, but the live URLs aren't correct. So then, in Drupal, we need to move these pages -

`www.va.gov/burials-and-memorials/eligibility/burial-at-sea/` -> `www.va.gov/burials-memorials/eligibility/burial-at-sea/`

`www.va.gov/burials-and-memorials/eligibility/burial-in-a-private-cemetery/` -> `www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/`

**Comment by Karak888** [comment]
@ncksllvn this is the part of the process that you would like to see added in per comment on DSVA correct?

**Comment by ncksllvn** [comment]
There were a lot of surprises in this ticket. I think we really just need to scope these well during grooming  and not do anything with them unless they have been groomed.

**Comment by ncksllvn** [comment]
@RLHecht when you're back, it would be awesome if you can move those pages.

**Comment by ncksllvn** [comment]
Thanks @RLHecht! I fixed the first broken redirect yesterday. Assuming today's deployment goes out, then this ticket should be all done.

**Comment by lunascoop** [comment]
Hi @RLHecht Can you update this drupal page: **www.va.gov/burials-and-memorials/eligibility/burial-in-a-private-cemetery/**  to -> **www.va.gov/burials-memorials/eligibility/burial-in-private-cemetery/**

Basically, delete the "a"

**Comment by RLHecht** [comment]
@lunascoop This has been fixed in Drupal.

**Comment by lunascoop** [comment]
Redirect for URL www.cem.va.gov/cem/burial_benefits/private_cemetery.asp has been implemented. Closing ticket and updating stakeholders.
