### ISSUE TITLE
nomethod error on refresh endpoint SiS

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#46583]
http://sentry.vfs.va.gov/organizations/vsp/issues/133253/?environment=production&project=-1&query=is%3Aunresolved+assigned%3A%23vsp-identity+controller_name%3Asign_in&sort=freq&statsPeriod=24h

**Comment by bosawt** [comment]
This appears to have occurred because the user redis model expired when the user attempted to 'refresh'. This was only happening because we were retrieving the user model as part of a log, otherwise is unnecessary for 'refresh'. Additionally, any other authenticated route will reload the user redis model if necessary. The change that was merged earlier today to change logging around callback and other routes mean we don't look up the user redis for 'refresh' so this should be fixed
