### ISSUE TITLE
Caution Flags Not Showing Correctly for the Heightened Cash Monitoring file

### ISSUE THREAD

**Issue by MitchLivingstone** [department-of-veterans-affairs/va.gov-team#46984]
## Issue Description
_The Comparison Tool is not showing the Caution Flags for the schools below from the Caution Flag file or known as the VaCautionFlag file as of 08312022_

Image provided by Brian Grubb:

![image.png](https://images.zenhubusercontent.com/62699917a261e69763726e6b/0339084e-30aa-447d-8e91-c9f3e8989026)

**This is the flag it should be displaying: Caution Flag-  “School operating under provisional accreditation (previously accredited by ACICS)” to the below schools:** 

University of North America: UNIVERSITY OF NORTH AMERICA: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
VA Facility Code 21806046
ED IPEDS code N/A
ED OPE code N/A

Southern Technical College-Sanford:  SOUTHERN TECHNICAL COLLEGE-SANFORD: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
SANFORD, FL 
VA Facility Code 24843110
ED IPEDS code 446552
ED OPE code 03903500

Southern Technical College-Orlando : SOUTHERN TECHNICAL COLLEGE-ORLANDO: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
ORLANDO, FL 
VA Facility Code 24843010
ED IPEDS code 446552
ED OPE code 03903500

SOUTHERN TECHNICAL COLLEGE-BRANDON: SOUTHERN TECHNICAL COLLEGE-BRANDON: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
BRANDON, FL 
VA Facility Code 25843310
ED IPEDS code 446552
ED OPE code 03903500

SOUTHERN TECHNICAL COLLEGE- AUBURNDALE: SOUTHERN TECHNICAL COLLEGE-AUBURNDALE: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
AUBURNDALE, FL
VA Facility Code 24843410
ED IPEDS code 446552
ED OPE code 03903500

San Diego Global Knowledge University: SAN DIEGO GLOBAL KNOWLEDGE UNIVERSITY: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
VA Facility Code 21120305
ED IPEDS code 493512
ED OPE code 04265700

San Ignacio University: SAN IGNACIO UNIVERSITY: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
VA Facility Code 219D5210
ED IPEDS code N/A
ED OPE code N/A

Gwinnett College: GWINNETT COLLEGE: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
VA Facility Code 24010811
ED IPEDS code 444714
ED OPE code 03804400

California University of Management and Sciences: CALIFORNIA UNIV OF MGMT AND SCIENCES: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
VA Facility Code 11105905
ED IPEDS code N/A
ED OPE code N/A

California Aeronautical University: CALIFORNIA AERONAUTICAL UNIVERSITY-BAKERSFIELD: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
VA Facility Code 21122205
ED IPEDS code 433420
ED OPE code 00998900

California Aeronautical University: CALIFORNIA AERONAUTICAL UNIVERSITY: GI Bill® Comparison Tool | Veterans Affairs (va.gov)
VA Facility Code 21007803
ED IPEDS code N/A
ED OPE code N/A

---
## Tasks
- [ ] _Determine what is keeping these flags from showing_

**Comment by AdamFreemer** [comment]
As per card: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/45408 this task is blocked until process flow information from Brian / VA is provided detailing how to properly add / remove caution flags non-programatically. Manually overriding the existing process with the dev team directly changing data in production is not advised (as has been done before).

**Comment by mrblanco1** [comment]
Please proceed with this request as EDU asked us to manually take care of these caution flags. Please let me know if you have any questions. Thanks!

**Comment by dan-brooking** [comment]
There appears to be some weird data in the caution flags file that may or may not be causing this issue.

One of the schools listed above with this issue is  University of North America

![image.png](https://images.zenhubusercontent.com/614247435cb473fa0e5fd3d1/cb454bcf-649e-42c6-9799-e3886ad6b875)

Looking at the spreadsheet, we see four records for this institution. The first one is the correct facility code. The other 3 records have facility codes for completely different schools.

![image.png](https://images.zenhubusercontent.com/614247435cb473fa0e5fd3d1/95340de9-7fff-45ed-b2e8-bfd74d6b699b)

![image.png](https://images.zenhubusercontent.com/614247435cb473fa0e5fd3d1/1f356d51-e43d-40f3-b0b2-79abdb81c356)
![image.png](https://images.zenhubusercontent.com/614247435cb473fa0e5fd3d1/9ac53ac6-8b38-4309-b32f-ca6a1a3e8f9b)
![image.png](https://images.zenhubusercontent.com/614247435cb473fa0e5fd3d1/a0f595e3-9967-4975-8426-d8680c81dba1)
![image.png](https://images.zenhubusercontent.com/614247435cb473fa0e5fd3d1/a6676a0f-c5d4-44fb-9cd8-5c1de13f8893)

**Comment by mrblanco1** [comment]
This institutions were updated via CT's GIDS data file upload process by Brian Grubb. The root cause is been investigated by EDU Brian Grubb.
