### ISSUE TITLE
Request Content Review: View Dependents

### ISSUE THREAD

**Issue by jason-gcio** [department-of-veterans-affairs/va.gov-team#4702]
[_Per the instructions for requesting a content review_](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/content/content-review-process.md#how-to-request-a-content-review)
## User Story
As a member of the eBenefits Team building with, or on, VSP, I need to have my content reviewed before product launch to ensure it's accurate, aligns with VA style, adn is error-free.

## Goal
- The content
  - [View Dependents mockup made in XD](https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/9b63b2b8-42a8-4501-b07b-0cdcd8fdcaa5/View-Dependents-End-State-1/)
- Context
  - Page 1: Older, current, soon to be legacy page
  - **Page 2: The best page for this content review. This is the heart of what this request is seeking.**  
  - **Page 3: A scrollable mobile version of page 2 to ensure we are looking good and working well on mobile.**  
  - Page 4: Loading spinner screen while data is being called for display.   
  - **Page 5: Blue (400) error notification message that data could not be found.**  
  - Page 6: Red (500) error notification message that something**  
  - Page 7: Not needed for this review; this page is trying to help describe some potential living quarters and is not applicable for this review.  
  - **Page 8: We welcome any suggestions here, but this page is optional since it is a potential future page as it would include some expanded functionality options in interacting with the various dependents in the Veterans account.**  
  - Page 9: Just a handy page that describes the inbound links to the "View Dependents" tool page.  
  - Other:  It should be noted that we call this page "View Dependents" but the _actual_ name for the page is "Dependents added to your VA disability benefits" as seen on page 2.  
- Launch Date  
  - Estimated March/April 2020?  
- Design elements to consider  
  - I think everything is covered.  We are not introducing any new design elements, and those being used were approved within the Rated Disabilities tool page (a similar view task).
- User research
  - [Found here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-summary.md)
  - [TL;DR, in second half of doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/ebenefits/research/disabilities-dependents-usability-1119/disabilities-dependents-usability-readout.pdf)

## Acceptance Criteria
- [ ] Feedback has been shared with the eBenefits Team for and checked for implementation.

**Comment by jason-gcio** [comment]
@peggygannon 
Just a note - while there is not a ton on this page to review, I didn't want to assume that it could be completed before the end of this sprint and I have yet to "create" the next sprint so the Milestone is blank.

**Comment by jason-gcio** [comment]
FWIW, we added some refinements around handling the SSN and wrote the dates out to be more clear.

**Comment by peggygannon** [comment]
Hi, @jason-gcio  and @sporeboy I'm so sorry for the delay in getting my feedback to you! Please see below for my content recommendations to the "View Dependents" prototype. Please let me know if you have any questions or want to discuss in a call. 


View Dependents content review (prototype)

Screen 1
I recommend we rewrite breadcrumb and header to: 
Breadcrumb: Your VA dependents
New header: Your VA dependents

Content recommendation for intro paragraphs: 
Below is a list of dependents we have on file for you. You can file a claim for additional disability compensation whenever you add a new dependent.  
{button} Add a dependent (we try to keep button length as short as possible)

Header: Dependents on your VA benefits
The following dependents have been added to your VA benefits. Please let us know if a dependent’s status has changed. [Learn more about adding or removing a dependent from your VA benefits](https://www.va.gov/disability/add-remove-dependent/).

Question: where does the "Change Status" button take users? 


Header: Dependents not on your VA benefits
The following dependents aren’t on your VA benefits. This is because either their dependent status is still awaiting a decision or their status has changed and they're no longer eligible to be on your benefit award. 
Please let us know if a dependent’s status has changed. [Learn more about adding or removing a dependent from your VA benefits](https://www.va.gov/disability/add-remove-dependent/).

**Comment by jason-gcio** [comment]
@peggygannon - Awesome, thanks for the feedback!  To answer your question, the "Change Status" button would eventually be deployed to take the Veteran into the submission part of the form to adjust their placement within the award; like remove someone who has died, or a divorce etc.  We thought that "Change Status" would be as concise and inclusive as possible but that page will most likely evolve as we traverse deeper into the submission process.
cc: @sporeboy

**Comment by sporeboy** [comment]
@peggygannon Thank you so much for the review and revisions. I have everything in place; you can review the latest here: https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/screen/61211510-a9de-477c-950c-ae7fe5d2ce65/View-Dependents-2
