### ISSUE TITLE
Address Accessibility Issues in tabs on Clams Status Details

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#47242]
# Details

[original ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/41449#issuecomment-1235618752) 

> Styling links as tabs is deceptive – when a link is clicked, the content is shown after a page refresh with the focus moving back to the top of the viewport.
> 
> But tabs don’t work like this – when a tab is clicked, the content is shown instantly without a page refresh and with the focus remaining on the tab.
> 
> Keyboard users may expect to be able to use the left and right arrow keys in order to switch tabs. This wouldn’t be expected with a list of links.
> 
> And (sighted) screen reader users may expect certain functionality, like using a shortcut to move focus to the associated tab panel or announcing which tab is selected.
> 
> Tabs should only look like tabs if they behave like tabs otherwise it can be in disorienting and confusing for users.

[Avoiding tab styles for navigation](https://adamsilver.io/blog/avoiding-tab-styles-for-navigation/), Adam Silver (gov.uk)

## Current experience

https://user-images.githubusercontent.com/14154792/168847941-dda1f857-a82c-4b14-9433-02e5108b97bb.mov

Left and right arrow keys navigates _characters_ , not tabs

## Steps to address this issue

this becomes a default level 3 if the the following criteria are met: 

- [ ] Remove any roles related to UI tabs
- [ ] List `ul` has navigation role
- [ ] List `ul` has name with `aria-describedby` to associate with `h2` on the page
- [ ] Each "tab" panel has a heading (?????)
- [ ] When a link is clicked, focus is transferred to the heading in the "tab" content area

## Point of Contact

**VFS Point of Contact:** @joshkimux 

## Next steps

- [x] Josh to document necessary code and design changes for both fixes
- [x] Review with other a11y specialists ( @jaredcunha would love to pull you in here if you have time)
- [x] Confirm with @skylerschain the necessary design lift required for both fixes
- [x] Confirm with @jerekshoe the necessary engineering lift required for both fixes
- [x] Select a fix between the two options
- [ ] Confirm with platform if this requires or does not require a collab cycle review

## Steps to Recreate

1. Enter `https://staging.va.gov/track-claims/your-claims/600219085/files` in browser
2. Start preferred screen reading device
3. Log in as user 233
4. Navigate to the tab list
5. Confirm right and left arrows do not navigate tab to tab

## Reference material
[Avoiding tab styles for navigation](https://adamsilver.io/blog/avoiding-tab-styles-for-navigation/), Adam Silver (gov.uk)

**Comment by jaredcunha** [comment]
This component sort of acts like a hybrid of navigation on tabs. 
![Screen Recording 2022-09-28 at 02 17 13 PM](https://user-images.githubusercontent.com/1094951/192858875-e13cfd13-7ed5-4868-bfff-2b4fab845999.gif)

Feels like something that might need some more work. I do think that removing the `tablist` and similar roles is the right approach. 

However, we might want to explore some additional behaviors as well:
- Give the `<ul>` a `navigation` role, as wells as `aria-label`
- Transfer focus to the content. Hitting the tab key focuses on the next link instead of the tab content. See [Scott O'Hara's accessible tabs](https://scottaohara.github.io/a11y_tab_widget).
- Updating the visual design, following **Avoiding tab styles for navigation** link above. Though I don't feel like that is a priority because as the author states, their solution still resembles tabs.

**Comment by jacobworrell** [comment]
@jaredcunha agree with the approach, let's incorporate the first two bullets of the solutions approach but omit the third for now: 

- Give the <ul> a navigation role, as wells as aria-label
- Transfer focus to the content. Hitting the tab key focuses on the next link instead of the tab content. See [Scott O'Hara's accessible tabs](https://scottaohara.github.io/a11y_tab_widget).

**Comment by jaredcunha** [comment]
@joshkimux wanna take a look at this suggestion and let me know your thoughts?

**Comment by joshkimux** [comment]
@jaredcunha brilliant, I love it! Some minor thoughts here:
- we can use `aria-labelledby` if we want to point to the `h2` on the page so it reads out as "Compensation claim navigation" and won't require manual updating if the name ever becomes more specific 😄 
- I do still think we should keep the bit on avoiding tab styles so these feel more like links (and less like buttons or tabs) in case
  - keyboard users expect to be able to use the `⬅️ ` and `➡️ ` keyboard buttons (when they can only tab since these are links)
  - voice input technology users get confused about how to trigger an interaction (e.g. do I say, "click link" or "click button" or "click tab"?) styling as a link may make the former more likely

**Comment by jaredcunha** [comment]
@sortizsh I've updated the main content above to keep it relevant based on the decisions we've made. 

**Notes that I've removed**
- Instructions to add kekyboard functionality to the tabs
- Screenshots, code snippets, and reference materials to the MDN tabs

**To reiterate how we've decided to address the accessibility issues:**
- Remove any `role` related tabs, then we can use aria-labelledby if we want to point to the h2 on the page so it reads out as "Compensation claim navigation" and won't require manual updating if the name ever becomes more specific.
- Transfer focus to the tab content. Hitting the tab key focuses on the next link instead of the tab content. See [Scott O'Hara's accessible tabs](https://scottaohara.github.io/a11y_tab_widget).
- No visual design changes, but mainly just changes in the code to remove the tab affordances to screen readers and allow to serve as navigation links since the URL path updates.

**Something I just thought of**
@joshkimux When transfer the focus to the tab content area, should it be the entire containing div? Should that container have an accessible name that matches the tab? Or should we add a visible heading and transfer focus to that (which is a minor visual design tweak)?

Another question for @joshkimux… agree on documenting this, but where does it go? Assuming for FUTURE reference and not changing design on these now. In [Avoiding tab styles for navigation](https://adamsilver.io/blog/avoiding-tab-styles-for-navigation/), Adam Silver (gov.uk), the other does admit that their solution still resembles tabs. I'd know I'd say "tab" looking at their designs.

**Comment by joshkimux** [comment]
@jaredcunha sorry for coming back to this so late 🙇 

When transfer the focus to the tab content area, should it be the entire containing div? Should that container have an accessible name that matches the tab? Or should we add a visible heading and transfer focus to that (which is a minor visual design tweak)?

The latter will likely be more intuitive to screen reader users. I believe (from my goldfish memory) that unique headings already exist, they're just set to be `sr-only` (visible only to screen readers) at the moment. 

> Another question for @joshkimux… agree on documenting this, but where does it go? Assuming for FUTURE reference and not changing design on these now. In [Avoiding tab styles for navigation](https://adamsilver.io/blog/avoiding-tab-styles-for-navigation/), Adam Silver (gov.uk), the other does admit that their solution still resembles tabs. I'd know I'd say "tab" looking at their designs.

Mhmm. I think at some point a more wholesale redesign of this would be needed so that we don't have to be so reliant on `aria` and focus management for it to work. I could file a bug ticket for the [design system instance of tabs](https://design.va.gov/components/tabs) as a starting point just so other teams know this is an issue more transparently and so it can be a bit more findable in the future .

**Comment by joshkimux** [comment]
@jaredcunha small nudge on this one ❤️

**Comment by skylerschain** [comment]
@davidakennedy I'm pretty sure we can close this since our [new tab design](https://www.figma.com/file/F8U4wddaFouUPVd4mGBMDI/CST---Evidence-Submission---Spec?type=design&node-id=0-593&mode=design&t=CAy6JM6Co9OeVB6I-4) styles the navigation more as links. Can you confirm?

**Comment by davidakennedy** [comment]
@skylerschain Correct! We fixed this with those navigation design changes. cc: @jacobworrell
