### ISSUE TITLE
[Spike] VAOS code to re-direct Veterans to Cerner (isCerner flag) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#47253]
## Background/Request
Public Website team plans to deprecate the [file](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/utilities/cerner/index.js) that has `isCerner` flag hardcoded. VAOS FE code uses the `isCerner` flag to determine if the Veteran is associated with a VAMC facility that uses Cerner or Vista. 

When the facility uses Cerner (the name of the facility is listed in the file), the Veteran will be routed to the Cerner portal from the VAOS static homepage. When the facility uses Vista, the Veteran will be directed to VAOS to book or request an appointment. 

### Goal
To review the updated logic of the `isCerner` flag in Drupal as the source of truth. VAOS team will need to do research to see if it will have any impact to the current VAOS code. 

### Requirements to Consider
[Public Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for) has provided documentation of the proposed changes. 

---

## Tasks
- Answer the following questions:
  - Q1: Do we need to update the FE and/or BE code? 
  - Q2: What is the recommendation/plan for the initiative? Please provide a comparison of current code versus proposed code. 

## Time Box
12 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

**Comment by JRRoof** [comment]
Public Websites plans to deprecate the isCerner flag Dec 1 in favor of the new Drupal-driven Cerner API. 
https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for

**Comment by vbahinwillit** [comment]
Answer the following questions:
Q1: Do we need to update the FE and/or BE code?
A1: Yes, since the 'isCerner' flag will be deprecated 12/1/2022

Q2: What is the recommendation/plan for the initiative? Please provide a comparison of current code versus proposed code.
A2: All changes will be behind the 'vaOnlineSchedulingAcheronService' feature flag. The function, 'connectDrupalSourceOfTruthCerner' will be called when creating a new appointment. This function call will dispatch the following redux events:

* FETCH_STATIC_DATA_STARTED
* FETCH_STATIC_DATA_SUCCEEDED

**NOTE:** FETCH_STATIC_DATA_SUCCEEDED depends on the existence of the file, vamc-ehr.json. This file is generated during the Drupal content build. 

You can generate the file during development or retrieved the file from production (https://www.va.gov/data/cms/vamc-ehr.json). The file should be placed in the 'build/localhost/data/cms' directory. Use the following command when running the content build locally:

```
yarn build --pull-drupal --use-cached-assets
```
This can take a wile to complete so I retrieved the file from production.

The changes required to use the Drupal driven Cerner API are in the following files:

* ../vaos/routes.jsx - Dispatch the redux event when the new appointment page is loaded
* ../vaos/redux/selectors.js - Determine which function to call depending on feature flag

The bulk of the changes consists of determining which function to call depending on the feature flag, 'vaOnlineSchedulingAcheronService' being true or false. Please see the following branch for details.

* https://github.com/department-of-veterans-affairs/vets-website/pull/22489

** NOTE: ** Please ignore the other changes that fix the eslint cyclic dependencies warnings

**Comment by cferris32** [comment]
Backend Findings:

Q1: Do we need to update the FE and/or BE code?
A1: We do not need any BE updates for this work. The api code already contains the 'vaOnlineSchedulingAcheronService' feature flag, along with individual cerner facility flags, in our features.yml configuration. The FE will still be calling the same vets-api endpoints.

Q2: What is the recommendation/plan for the initiative? Please provide a comparison of current code versus proposed code.
A2: N/A

**Comment by ldelacosta** [comment]
Will create a new working ticket for this update. Closing out the spike ticket.
