### ISSUE TITLE
Update the logic for facilities timezone offset 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#47354]
## Description
We would need to update the facilities timezone offset in the preferred timezone VAOS FE is sending back (endpoint/name of field) 
This would apply to direct appointment workflow. 

Background:
For V0, we were sending the veterans preferred date with a 0 offset: `desiredDate: ${data.preferredDate}T00:00:00+00:00Z` and the facility timezone in a separate timezone field. It was confirmed that VAR appears to be ignoring the timeZone field on direct booking requests and getting the value from MFS v2 directly.
Vaos service doesn't do this so for v2, we need to send the veterans preferred date with the facility offset. i.e, if the facility's offset is UTC-5, we will send `desiredDate: ${data.preferredDate}T00:00:00-05:00`.

## Dev Notes
 Update `desiredDate` found in the `transformFormToVAOSAppointment` transformer in `src/applications/vaos/new-appointment/redux/helpers/formSubmitTransformers.v2.js`. 
- We have a util called `getTimezoneByFacilityId`, we can pass the facility Id to this util to get the facility timezone. 
- We already return the facility id in the `transformFormToVAOSAppointment` transformer here: `locationId: data.vaFacility`, we can use that.
- Momentjs is very helpful for parsing timezones so we can do something like: 
`moment.tz("2013-11-18 11:55", "America/Toronto").format();`
Check https://momentjs.com/timezone/docs/#/using-timezones/ for more info

---

## Acceptance Criteria
Background: the va_online_scheduling_vaos_v2_next toggle is on and Preferred dates are passed with facility timezone offsets.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by marcynadeau** [comment]
### **Notes for testing:  Once this is fixed test in the course of testing this defect test the Clinic Wait Time 2.**  
MBAA*1*13 caused the Clinic Wait Time2 NULL issue in CHYSHR.   The patch was backed out of CHYSHR. I retested today.

The  CID/Preferred date I entered  in VAOS was 10/1:
VistA shows.....OCT 02, 2022@18:00.  This is known defect.  https://github.com/department-of-veterans-affairs/va.gov-team/issues/47354

Clinic Wait Time2 was NULL and now is being calculated but the calculation is off by a day since the above date is off by a day.
VistA show.....Clinic Wait Time2: 1 day. This should be two days since Preferred date 10/1 and actual appt date is 10/3. This will get fixed once 47354 is fixed.

**Comment by ldelacosta** [comment]
Referencing the new working ticket #48115
