### ISSUE TITLE
[bug] Certificate of Eligibility | Error message when uploading document

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#47434]
## What happened?

![image002.png](https://images.zenhubusercontent.com/61438f9a4cc76e287dda36ce/93c754e6-ef93-4b62-baec-a7f761e26b0d)

## Specs:
- Device: TBD (e.g. iPhone 8, Macbook)
- Browser: TBD (e.g. Firefox, IE 11)
- Test User: Login info in snapshot

## Steps to Reproduce
- Info in snapshot

## Acceptance Criteria
- When a user uploads a document they should not receive error messages

**Comment by data-doge** [comment]
@saderagsdale @jerekshoe 

Jerek and I looked into this. This error occurs because, on staging, the antivirus takes too long to scan uploaded files. So long that it exceeds a newly configured timeout. See https://dsva.slack.com/archives/CBU0KDSB1/p1663701068979789. Lindsey provided context on this timeout and offered a few suggestions for avoiding it. Unfortunately, those suggestions don't work for us. https://dsva.slack.com/archives/CBU0KDSB1/p1663880610954789?thread_ts=1663701068.979789&cid=CBU0KDSB1. However, Lindsey said that she would be able to move our file-upload endpoints to a second ASG that does not enforce a timeout. https://dsva.slack.com/archives/CBU0KDSB1/p1663936151803309?thread_ts=1663701068.979789&cid=CBU0KDSB1.

**Comment by data-doge** [comment]
Drafted a PR for the devops team to review: https://github.com/department-of-veterans-affairs/devops/pull/11992

**Comment by data-doge** [comment]
Jerek has addressed the root cause (unusually long antivirus scans) here: https://github.com/department-of-veterans-affairs/vets-api/pull/10791.
