### ISSUE TITLE
Support tickets: Craft reminder/offer assistance message to SME

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#47525]
Acceptance criteria:

- [x] Consider the following:

- how long a ticket has been open
- what can we do without SME assistance?
- do we have any suggestions for the content SME?
- has the work requested already been done by someone in their team?

- [x] Draft a message that we will send to Peter Hill and Joe Tice (that we can repurpose for reaching out to other SMEs we triage support tickets to)

**Comment by taylojill** [comment]
Message below:
Hi, ___! The Platform Content team would like to help you close ticket #____. The ticket author recommends adding a sentence and/or link to an existing page. It looks like an easy fix since they provided a suggested link. Let us know if you'd like to work with us to close this ticket!
