### ISSUE TITLE
Content and IA Request from MHV Secure Messaging: Patient safety message

### ISSUE THREAD

**Issue by alexiawunder** [department-of-veterans-affairs/va.gov-team#47747]
## What does your team need support for? Check all that apply.
- [x] Launching one or more new unauthenticated (static) VA.gov pages
- [ ] Making revisions to one or more existing unauthenticated (static) VA.gov page
- [ ] Launching a new online form, app, or tool on VA.gov
- [ ] Making revisions to an existing online form, app, or tool on VA.gov
- [ ] Something else (please add details in the next question)

## What do you need help with?
  - [x] Content support
  - [ ] IA support
  

*Please describe your need and provide any additional documents and/or links that will help us help you. If we need to add a react widget to a page, be sure to provide the code here.*

As a more urgent, smaller piece of the larger Content discussion, our team will test the 911/emergency note in our upcoming usability study. While the other content for SM can change after testing, this particular note can't go into the beta without a successful test outcome. To stay within our proposed timeline, we'd like to make this content as final as possible prior to testing. We anticipate that our research plan and conversation guide will be submitted as early as Tuesday, October 4th, thus Usability Testing may start as early as Monday, October 17th. 

We have provided a full screen for context, but for this issue, we are only focusing on the "Note: Call 911 if you have a medical emergency..." paragraph. The note will exist on the main landing page (the inbox) and on any page where the user may send a message (compose, reply, drafts). When the user selects the 911 link, their browser will prompt them to choose which app they want to open to make the call. The Veterans Crisis line will open the same modal as the red Veterans Crisis Line banner at the top of every page. 
[Inbox List Mobile.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/9679177/Inbox.List.Mobile.pdf)

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users? 
TBD, but current estimate is Q2 2023.
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
- Link to any epics/issues that may be helpful:

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: Q1 2023
- Estimated staging review date: Q1 2023
- Content and IA work needed by: October 17th for this specific ticket. 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Lauren Alexanderson
-	Product manager: Marci McGuire (Health Modernization Product Spike Team) / Bryan Riley (MyHealtheVet team)
-	Designer: Jessica Robertson, Alexia Wunder, Arienne Walters
-	FE engineer: Michael Moyer
-	Product/team Slack channel: mhv-secure-messaging

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by laurwill** [comment]
Hi @alexiawunder ,
Here's our suggested content updates for the emergency note:

[Alert header] **When to get help right away**
**If you think your life or health is in danger,** call [911](url) or go to the nearest emergency room.
**If you’re in crisis and need to talk with someone right away,** call [988](url), then select 1.
**If you have an urgent question for your VA care team,** call your VA health facility.
[Find your nearest VA health facility](https://www.va.gov/find-locations)

And a few notes about this approach: 
- We think an alert component may work better than a simple note here — the content felt a bit crowded in the note, and we'd want to break out the 3 parallel if/then steps onto separate lines for ease of reading.
- Instead of having the user click on hyperlinked "Veterans crisis line" and popping up the 988 modal, we tried moving the main crisis line phone number directly into the content. (I think we'll also be providing more complete Veterans crisis line info in the secure messaging FAQs, but wanted to keep this message as brief as possible.)

Let me know if you have feedback or want to chat!

**Comment by alexiawunder** [comment]
I forgot to mention on our Wednesday sync - which color alert do you recommend this new content go into? Should we go with or without the icon?

**Comment by laurwill** [comment]
Hi @alexiawunder , let's use a blue info alert for this — the warning alert might be too scary in this context.

And based on discussion in our sync, we also took another look at more explicitly saying that secure messaging is not for urgent/emergency needs. We think this could work better in the content above the alert instead of the alert itself: 
<img width="493" alt="image" src="https://user-images.githubusercontent.com/104158104/195938887-62927bc7-2351-4f19-aa49-56a751c55267.png">

**Messages**
When you send a message to your care team, it can take up to 3 business days to get a response. So if you need help now, use a different contact option.

[and then the alert]

Let us know what you think!

**Comment by laurwill** [comment]
Hi @AnneCostello , thanks for this update on usability testing! We'd be happy to adjust the wording here, but we'll need a bit more context first. Could you share the findings that led to these changes? We'd be happy to hop on a call to discuss if that's easier!

**Comment by laurwill** [comment]
@AnneCostello here's the text we chatted through on zoom:

**Don't use messages for emergencies**

- **If you think your life or health is in danger,** call [911] or go to the nearest emergency room.
- **If you're in a mental health crisis or thinking about suicide,** call 988 then select 1. Or you can chat at 988lifeline.org. 

Messages are only for non-urgent questions and concerns. It can take up to 3 business days to get a response.

**Comment by laurwill** [comment]
Hi @AnneCostello ,
Just noting a followup here — we were thinking about the value of calling out mental health and suicide more specifically versus leaving the use case for the crisis line more broad. Danielle mentioned some earlier feedback from Veterans who wanted to know that they could call the line even if they weren't actively considering suicide/in a severe crisis.

So it would be great if we could test a more general "if you need to talk to someone now" version along with a more mental health crisis/suicide specific version. We'll plan to take another pass here after we see the full testing findings—and happy to help prep multiple versions for testing if needed. Thanks for your collaboration on this!

**Comment by laurwill** [comment]
Hi @AnneCostello ,
Here's our working draft of the new interstitial screen approach to this safety message content:

**[H1] Do you need help right now?**

**If you think your life or health is in danger,** call 911 or go to the nearest emergency room.
Call 911 [secondary action link]

**If you feel hopeless and need to talk to someone right now,** our Veterans Crisis Line offers confidential support anytime day or night.
Connect with the Veterans Crisis Line [secondary action link]

**If you have an urgent question for your VA care team,** call your VA health facility.
Find your nearest VA health facility [secondary action link]

**[H2] Continue to message for non-urgent needs**
Your care team may take up to 3 days to reply.
Continue to message [button]

We can chat about this in our sync today! We're also considering whether to change the order of the first 2 options — so we'd lead with the crisis line, followed by 911.

**Comment by laurwill** [comment]
Hi @AnneCostello @alexiawunder (I'm not able to tag Joel and Jessica, but I'll link them from slack),
Thanks again for walking through the interstitial screen content with us today, and for raising the H1 concerns! Here's our suggested content to bring into testing, and a question/option for you on the H1:
- We went back and forth between the negative framing "Don't use" vs "Only use messages for non-urgent needs"
- We generally avoid negative framing in VA.gov content, especially in an H1. So we'd only want to use that version if we could get feedback on that wording in testing. Otherwise, we'd suggest going with "Only use for non-urgent."

[H1] **Don’t use messages for urgent needs** or **Only use messages for non-urgent needs**

**If you think your life or health is in danger,** call 911 or go to the nearest emergency room.
Call 911 [secondary action link]
**If you feel hopeless and need to talk to someone right now,** our Veterans Crisis Line offers confidential support anytime day or night.
Connect with the Veterans Crisis Line [secondary action link]
**If you have an urgent question for your VA care team,** call your VA health facility.
Find your nearest VA health facility [secondary action link]

[H2] Continue to start a message for non-urgent needs
Your care team may take up to 3 days to reply.
Continue to start a message [button]

Let us know if you have questions or need anything else from us here! And @AnneCostello we're standing by to consult on the conversation guide whenever that's ready for us.

**Comment by laurwill** [comment]
And this approach also carries over with minimal changes on the new message screen — see notes in [that sketch file as well](https://www.sketch.com/s/77fd8aec-67b1-446d-b64a-8b942865be82/a/m1388vg)!

**Comment by RLHecht** [comment]
Going to close out this ticket. When we're ready  for the next phase of Secure Messaging we'll open new tickets.
