### ISSUE TITLE
Design and Research tool access

### ISSUE THREAD

**Issue by naomimarcussen** [department-of-veterans-affairs/va.gov-team#47849]
## Description
Currently, we don't mention accessing tools that designers and researchers will need in order to work. Could we add a section to address them?

### Researchers

- Access to the [va.gov-research-repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1) 
- Reach out to Shane Strassberg

### Designers

- Access to Sketch for Teams
- Reach out to Kevin Hoffman

**Comment by vbellissimo** [comment]
@naomimarcussen Hi Naomi. Thanks for your submission. I have a question regarding this.

1. Are you suggesting that we add a section about this to let VFS team members to reach out to Shane and Kevin? OR
2. Are you suggesting to us (Platform Content team) to reach out to Shane and Kevin to find out how they need to access each of those tools?

Thanks.

**Comment by naomimarcussen** [comment]
Great question! I'm sorry, that totally wasn't clear. I'm suggesting 1) we add a section for VFS Designers to let them know that to get access to Sketch for Teams they need to contact Kevin and 2) add a section for VFS Researchers to let them know to get access to the research repo they need to contact Shane.

**Comment by laucon** [comment]
@naomimarcussen Hi Naomi! I want to get started on this. I think one good way to approach this would be to do this:
Option A:
1. We create a new page where we explain these accessing rules.
2. We put that new page under "Getting Started-->Request access to tools"

<img width="1792" alt="Screen Shot 2022-10-07 at 9 48 52 AM" src="https://user-images.githubusercontent.com/14806304/194570164-5917b06a-e687-4dc2-96f7-b013dc74542e.png">


However, I can also see several alternatives.
Option B:
- instead of creating a new page, we add this info to an existing page. One good existing page where we can put this would be the [Research and Design homepage](https://depo-platform-documentation.scrollhelp.site/research-design/)

Another alternative would be...
Option C:
We make this a new page and we put it somewhere in the Research and Design section, perhaps under "Research at VA" except that maybe we retitle that to "Research and Design at VA"

<img width="1792" alt="Screen Shot 2022-10-07 at 9 53 07 AM" src="https://user-images.githubusercontent.com/14806304/194570193-5703b0a6-49a3-41a6-9ee1-fb3a78707ffd.png">

If you like one of these options, can you tell me which one you like best? If you would prefer another option that I haven't mentioned yet, can you explain to me that option? I think the first option makes the most sense now that Research and Design section is so Research-focused now.

**Comment by laucon** [comment]
@naomimarcussen I have 3 more questions for you.
1. What is Kevin's last name?
2. What is Shane's last name?
3. How should people contact them? In github? If in Github, where in github? In slack? And if using slack, what slack channel should they use? Is there a special slack form or github form they should fill out?

**Comment by laucon** [comment]
I wrote a draft [here](https://vfs.atlassian.net/wiki/spaces/PWD/pages/2399535285/Accessing+Research+and+Design+Tools).

**Comment by naomimarcussen** [comment]
These are great options @vbellissimo! I think if we follow the path we are asking new VFS team members to go down, we'll come to a good place. 

Currently, [new VFS team members](https://depo-platform-documentation.scrollhelp.site/getting-started/guidance-for-new-teams-and-team-members#Guidancefornewteamsandteammembers-NewVFSTeammembers) are asked to complete the [Platform Orientation template](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=governance-team%2C+analytics-insights%2C+analytics-request&template=orientation-epic.md&title=Platform+Orientation+Template+%5BYour+name+here%5D) where they are directed to the [Request Access to Tools page](https://depo-platform-documentation.scrollhelp.site/getting-started/request-access-to-tools). It might make sense to add the 2 sections to that page.

But, looking at the left nav in the Getting started section, does it make sense to group the Platform Tools and Request access pages? I'll leave that up to y'all.

@laucon Sorry, I should have been more specific. To answer your questions:
1. To access Sketch for Teams reach out to Kevin Hoffman in the #design Slack channel
2. To access the [va.gov-research-repository](https://github.com/department-of-veterans-affairs/va.gov-research-repository/projects/1), reach out to Shane Strassberg in the #research-ops Slack channel

**Comment by naomimarcussen** [comment]
@laucon That sounds like a great plan. Let's do it! Thank you :)

**Comment by laucon** [comment]
Awesome. I'll do that on Monday (just becuase it's almost 5pm eastern on a Friday.) lol

**Comment by laucon** [comment]
@naomimarcussen Ok, I fixed all the stuff we discussed this morning. [Here](https://vfs.atlassian.net/wiki/spaces/GS/pages/969605215/Request+access+to+tools) it is. I'll deploy it around 3:30pm or 4pm today.

**Comment by naomimarcussen** [comment]
This is great @laucon! One small tweak I might suggest here is to make it clear that access to Sketch and the research repo isn't something that everyone can get access to. Maybe you could make a header similar to "Additional access to developers" with a brief explanation like "There are a few tools that designers and researchers can request access to."

**Comment by laucon** [comment]
Sure. I changed it so there was a heading that says "Additional access for researchers and designers" and then I wrote underneath it "These tools are specifically for researchers and designers to use:" I think that gets the message across without sounding like "research and designers only get access to these tools and no one else because it's exclusive" or something. lol

**Comment by naomimarcussen** [comment]
That's great. Thank you!
