### ISSUE TITLE
[Datadog] Eval/Setup Monitoring for AWS:RDS

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#47975]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for RDS

# Acceptance Criteria
- [ ] RDS is evaluated for monitoring needs
- [ ] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
- Use the USE method for systems:
  - **U**tilization: The average time that the resource was busy serving work. We usually represent utilization as a percentage over time.
  - **S**aturation: The amount of work that a resource is unable to serve. We usually represent this metric as a queue length.
  - **E**rrors: The number of error events. We usually represent errors as a total count.
- Use the RED method for services
  - **R**ate: The number of requests the service is handling per second
  - **E**rror: The number of failed requests per second
  - **D**uration: The amount of time each request takes (latency)

**Comment by rsmithadhoc** [comment]
I created monitors for the following and added them to our [dashboard](https://vagov.ddog-gov.com/dashboard/9dk-y7n-6vf/platform-monitors--alerts)

- Fundamental system resources 
    - [CPU Utilization](https://vagov.ddog-gov.com/monitors/100036)
    - [Memory Utilization](https://vagov.ddog-gov.com/monitors/100039)
    - [Free Storage Space](https://vagov.ddog-gov.com/monitors/100275)
- Database activity
    - [Connections](https://vagov.ddog-gov.com/monitors/100040)
- Query performance
    - [Read Latency](https://vagov.ddog-gov.com/monitors/100060)
    - [Write Latency](https://vagov.ddog-gov.com/monitors/100061)

I would have liked to tracked errors for the following, but did not see any related metrics:
- Query errors
- Connections refused due to server errors
- Connections refused due to max connections limit
- Failed connection attempts
