### ISSUE TITLE
[Datadog] Eval/Setup Monitoring for AWS: Auto Scaling Groups

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#47981]
# Description
As a platform engineer Datadog monitors and alerts need to be evaluated and/or setup for Auto Scaling Groups

# Acceptance Criteria
- [ ] Auto Scaling Groups are evaluated for monitoring needs
- [ ] Monitors are created, if appropriate
- [ ] Alerts are created, if appropriate

# Notes
- Use the USE method for systems:
  - **U**tilization: The average time that the resource was busy serving work. We usually represent utilization as a percentage over time.
  - **S**aturation: The amount of work that a resource is unable to serve. We usually represent this metric as a queue length.
  - **E**rrors: The number of error events. We usually represent errors as a total count.
- Use the RED method for services
  - **R**ate: The number of requests the service is handling per second
  - **E**rror: The number of failed requests per second
  - **D**uration: The amount of time each request takes (latency)

**Comment by alexandec** [comment]
We've created six monitors for ASGs. I've grouped them here by type:

UTILIZATION
Platform - AWS ASG Instances In Service
Platform - AWS ASG Total Instances

SATURATION
Platform - AWS ASG Abnormal Scaling
Platform - AWS ASG Pending Instances
Platform - AWS ASG Terminating Instances

ERROR
Platform - AWS ASG Instances Failing Status Checks

Each monitor tracks the autoscaling groups separately. This helps us quickly track down an issue to a single group, instead of having to guess the location of the problem.

Of the available metrics, I think these best capture the overall state of the ASGs. We can see the overall number of instances, as well as determine when there are excessive or unusual amounts of instances being created or terminated. We can also see if a group has too many unhealthy instances which are failing status checks.

Metrics I considered but didn't include because I decided there was too much overlap with the above metrics:
aws.autoscaling.group_min_size
aws.autoscaling.group_max_size

Also, I did not add EC2 instance monitoring beyond instance error rates per ASG, because that information is/will be tracked by other monitors.

I determined warning and alert thresholds by looking at 3 months of past data and checking peak values.

**Comment by ph-One** [comment]
@alexandec (AWS ASG Total Instances) https://vagov.ddog-gov.com/monitors/98620 - Try and use a title that indicates what the issue is. For example, "Platform - AWS ASG Runaway Scaling"

![image.png](https://images.zenhubusercontent.com/622146ffd0422cdb4d9fdd52/78c1dd74-fd7e-48b2-bc30-0a28fef208c8)

**Comment by ph-One** [comment]
@alexandec For ASG, see if you can create a monitor showing the % of the ASG being used. This would fall under Utilization. Possible settings could include a warning at around 80%, and an alert at 95%

**Comment by ph-One** [comment]
@alexandec You can do away with "Alert: Platform - AWS ASG Instances In Service," as this is more informational. You _could_ however, look into creating a monitor that is somewhat the inverse of this one to make sure that ASGs always have at least one healthy instance In Service

**Comment by ph-One** [comment]
@alexandec (Platform - AWS ASG Instances Failing Status Checks) https://vagov.ddog-gov.com/monitors/98636 Can you make this one a bit more aggressive. Something more close to a warning at 3 and alert at 5

**Comment by alexandec** [comment]
@ph-One I've updated the monitors as you suggested above.

I also investigated alerting on ASGs with zero instances and found exactly what you mention. ASGs drop to zero instances fairly frequently, so I think that monitor would add too much noise to make it useful (multiple alerts per day). If it were possible to distinguish between healthy empty ASGs, where going to zero instances is fine, and unhealthy ones, where zero instances indicates a problem, the monitor could be useful. But I'm not sure how to do that.
