### ISSUE TITLE
[Research] My VA Audit UX Improvements: Create Conversation Guide

### ISSUE THREAD

**Issue by ericasauv09** [department-of-veterans-affairs/va.gov-team#48243]
## Background
Create the conversation guide for the My VA Audit UX Improvements initiative. 

## Tasks
- [x] Create Conversation Guide for Audit Research
- [x] Share with team for review

## Resources
- [Conversation Guide Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/planning/conversation-guide-template.md)

**Comment by aagosto90** [comment]
Audit [convo guide draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/research/audit-conversation-guide.md) is ready for team review. No rush on this - @Samara-Strauss @ajakabcin @andaleliz Please take a look when you have time and let me know if you have any feedback you'd like me to incorporate. For reference, here's the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/2022-audit/research/MyVA-audit-research-plan.md).

**Comment by andaleliz** [comment]
Thanks @aagosto90! This convo guide looks like it'll support the research questions in your plan. A few minor comments/possible edits: 

- If you are planning on leveraging the transcription feature for notes, I would add a reminder to turn them on when you start the recording.
- IMO you don't need that first warm up question about their relationship to VA, but if you feel like it's a good starter just to get people talking, keep it in.  
- The task goal "Determine if the updated information architecture of My VA still aligns with Veterans' mental model." is nested under the Warm Up Questions heading, and I think it should be it's own separate task as it seems like you're moving out of the warm up by then.
- I sometimes forget to ask a question if it's added on to another one, they way you have question 2 in the post-task interview. If that happens to you, I recommend making "what did you see that you didn't want or need to see?" into a separate question so you don't miss it.

Great job!

**Comment by Samara-Strauss** [comment]
Great job, @aagosto90!

- I think you can leave the warm-up questions since they influence the rest of the convo guide.

> Once the full page has loaded You said you use VA.gov to do X. Tell me how you'd go about doing/looking into X from here.

A couple things on this question:

- Is the plan to ask it more than once if they do multiple things online (eg. check appointments, check claim status, etc)?
- I would frame this as "You said you go online to check X..." instead of making it exclusive to VA.gov. People may use eBenefits or MHV for tasks that we also support on My VA, so the task matters more than the specific platform they currently use.

> Let's scroll down to the education and training section. Can you tell me what you think this section is for?
> Are any of the links in this section of interest to you? (If not) How do you feel about seeing this section on My VA? 

Something isn't sitting quite right with me about these questions. What are we trying to evaluate re: Education & Training? My hypothesis is that it will be pretty obvious what the section is for, and "how do you feel about this section" will probably depend on whether they are currently using education benefits or not. It also implies that they know it's a new addition to the page, which they likely won't realize unless they use My VA all the time. So, I might revisit this depending on what we are trying to learn about this section. I would also consider only asking people with education benefits questions around whether the links are useful or if anything is missing, since other participants may not care.

**Comment by aagosto90** [comment]
Hey @Samara-Strauss  - thank you so much for reviewing and sending this feedback along! 

- Good point that many veterans we speak to don't use VA.gov and we want to know if they'd be able to find what they look for on MHV and eBenefits, on My VA. I changed the language in this question.
- Very fair points about the education and training section. I thought we might want to know if these links are popular enough that they need to be there for every user and that they don't get in the way for say, older veterans who will never be interested in them. But we do know these benefits are extremely popular overall on the site and I suppose for that fact, we don't intend for any data in this study to cause us to not include the section. So then I suppose the only goal here is to make sure those either using or interested in education benefits find the section useful, as you said. I edited this section so that I'll only ask veterans who mention education benefits about the content of this section in particular, but I'll certainly note any other unsolicited feedback we get about it.

**Comment by Samara-Strauss** [comment]
> I was intending to ask it about any and all benefits a veteran mentions in the intro questions. This convo guide will end up being pretty personalized to the user which is what I intended since there will be a range of benefits veterans are using in the study.

Great! That's what I suspected but wanted to confirm. Thank you for letting me know!

>  I edited this section so that I'll only ask veterans who mention education benefits about the content of this section in particular, but I'll certainly note any other unsolicited feedback we get about it.

Sounds good to me!!

Great work!
