### ISSUE TITLE
Design Intent - Design Feedback - 10-10EZ Household Information Optimization

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#48260]
## VFS acceptance criteria
- [ ] Let Platform know when the **Must** feedback has been incorporated 
- [ ] Leave any comments for feedback you decide _not_ to take
- [ ] VFS team closes the ticket

## Thoughts/questions
- Use alerts sparingly. We have noticed alert fatigue on va.gov. Try to use alerts sparingly, eg. financial disclosure, does that really need to be styled as an info alert? 

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**
- Follow our current [list/loop design pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses) and style (eg. no blue background). If you want something different you could use a Card with a drop shadow there instead (and white background). You would need to submit this to experimental design
- If you do decide to use alerts, consider the [expandable alert style](https://design.va.gov/components/alert-expandable) when you have additional info.

**Should:**
- Use the [Memorable Date](https://design.va.gov/components/form/memorable-date) instead of the Month/Day date component.
- Instead of doing conditional logic, consider doing 1 question per page. "Spouse's information 2" is okay because it only progressively discloses one question. That's not worth an entire new screen to cover.

**Consider:**

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by nicko-amida** [comment]
[The 1010EZ household section updated designs](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/208CCE1E-DC03-457F-B2FA-1232663983CF/canvas)
**Must**
- [List and loop design](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/4a1LYqx) differs from the design system, but was OK'd by design team and Matthew Dingee.
- We considered the expandable alert design but want to stay with the current design, if possible.

**Should**
- The memorable date is something we want to work towards, but this requires additional changes to the backend that require additional research/work
- Conditional now appear on the their own pages - no longer using an expandable component for conditionals.
