### ISSUE TITLE
Store PR timing data in Prometheus

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#4829]
As a developer, I would like to store the data in Prometheus so that I can use it in grafana to display PR timing data

AC: 
- [ ] Able to store data fetched from github API's in prometheus.

**Comment by Clark-W-Griswold** [comment]
While researching tools/libraries that can help us with this process, we came across this:
https://github.com/prometheus/client_ruby

Should help us by giving us tools out of the box to do the calculations needed and push up to prometheus.

**Comment by Clark-W-Griswold** [comment]
Lot's of thoughts around how to get this data into prometheus. 

> Keifer Furzland  14 minutes ago
> I think pushgateway is going to be your best option,if it's ran on a vets-api-like instance you could just use builtin settings and echo out to StatsD.host

> Keifer Furzland  14 minutes ago
> like, spin up an instance of vets-api-worker as a test bed, maybe it'd eventually be wrapped in it's own container but can point to the existing statsd-exporter

> Bill Ryan  13 minutes ago
> we also have a sidekiq scheduler that you could add to https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/sidekiq_scheduler.yml

> Dan Shank:snow_capped_mountain:  13 minutes ago
> So if I am understanding correctly @Keifer [VSP/BE Tools] && @billryan, we can leverage the existing infrastructure in vets-api and that should give us the tools to dump the data into prom from this script. Is that accurate? :smile:
> 
> Bill Ryan  13 minutes ago
> yes
> 
> Keifer Furzland  13 minutes ago
> Yeah
> 
> Keifer Furzland  12 minutes ago
> setup a mtg tomorrow to do more discussing


> Keifer Furzland  12 minutes ago
> it can live in the vets-api code/infra, for now, but likely we should build it's own utility resources w/ just the config it needs.
> for now though, if you can get it working from a vets-api* instance you should have a PoC/MVP
> 
> 
> Bill Ryan  11 minutes ago
> here’s where our StatsD config gets setup: https://github.com/department-of-veterans-affairs/vets-api/blob/74d0d2b6eef408d795d9002f150b069d72a874e5/config/initializers/statsd.rb
> There’s tons of examples of how we use StatsD in vets-api, heres a random one i just found: https://github.com/department-of-veterans-affairs/vets-api/blob/74d0d2b6eef408d795d9002f150b069d72a874e5/app/controllers/v0/sessions_controller.rb#L26

**Comment by Clark-W-Griswold** [comment]
After further discussion, we have 2 paths to take here. 

The short term path is to add the ruby script written by Travis and have that live in vets-api. This will leverage existing internal tools for scheduling the task to get the data from github as well as pushing that data up to prometheus. This code does not need to be deployed to production and can live in a single dev or staging instance. 

The long term path is to have this live in the utilities instance. This will require more work around tooling/support to get the base numbers we would like to see. Due to the additional time needed, we will approach this solution as the long term goal.

**Comment by Clark-W-Griswold** [comment]
> Nathan Hruby:writing_hand:  4 days ago
> if that doesn’t work, let’s have a chat about getting that turned into a real service instead of attaching it with vets-api, since it doesn;t seem like it needs to be in vets-api anyway
> 
> 
> 
> 
> Wyatt Walter  4 days ago
> yes, let’s not do that in vets-api if it doesn’t need to be there. we can get it in Jenkins or run the Prometheus GitHub exporter itself if that works
> 
> 
> Keifer Furzland  4 days ago
> Agreed that it should be a standalone service in the util vpc probably but we wanted to make sure they were able to get data for the insights team and a temporary rake task seemed to fit the bill

**Comment by Clark-W-Griswold** [comment]
Dan Shank:snow_capped_mountain: Yesterday at 11:12 AM
@nathanhruby @wyattwalter @Keifer [VSP/BE Tools] @billryan We are continuing to iterate on our approach to get github PR data from the github api's and would like to start a thread. It looks like the recommendation has been to make this a service. With that, we have identified a few things that we might need to do. If we could all brainstorm and discuss in this thread, maybe we can lock down a solid approach? 


Dan Shank:snow_capped_mountain:  23 hours ago
Some of the things we have identified are the following:
We will need a local dev instance (docker compose) to run prometheus and the github exporter 
We will potentially need IAM roles added for ansible. 
It should probably live in the utilities instance and some coordination with ops will be needed to get it on the Utilities VPC.

Bill Ryan  22 hours ago
Last I knew, the plan was to use dev to make a cron/scheduled sidekiq job to go fetch the GH data and export using StatsD. Was that done already and this is V2?

Bill Ryan  22 hours ago
sorry, im probably OOL

Dan Shank:snow_capped_mountain:  22 hours ago
All good @billryan! When iterating down that path, we received feedback that it would be best for it to live as a service. So we have gone down that path instead of trying to get the numbers as soon as possible.


Wyatt Walter  22 hours ago
docker-compose is fine. what i use for things like this is the vagrant setup for running it locally: https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/vagrant


Wyatt Walter  22 hours ago
if it’s just a single exporter, i’d just run it right on the Prometheus node itself for the moment, or throw it on the “utility-exporter” deployment

Wyatt Walter  22 hours ago
shouldn’t need any of that plumbing to do any of that


Keifer Furzland  22 hours ago
Oh nice, so https://github.com/infinityworks/github-exporter runs via a docker container "automagically" just like most typical exporters and for the very MVP case we don't even need the github token added to credstash



Keifer Furzland  22 hours ago
I'm not quite 100% on how we define additional containers on the utility deployment, but I'm guess it's in the ansible & deployment folders in devops

Keifer Furzland  22 hours ago
might need a bit of guidance there specifically

**Comment by Clark-W-Griswold** [comment]
Discussing a pivot to reduce the amount of effort on this ticket:

> Keifer Furzland  8:29 AM
> maybe take a look at some of the tasks in vets-api/rakelib/* but if you have the ruby code already it's mostly a matter of formatting it correctly

**Comment by Clark-W-Griswold** [comment]
Pivot: 
Get ruby code ready for rake task in vets-api.
Get Jenkins to run rake task.

**Comment by Clark-W-Griswold** [comment]
>Bill Ryan: @Travis Hilton @Dan Shank here’s the jenkins rake tasks i was referring to http://jenkins.vfs.va.gov/job/rake_tasks/

> Bill Ryan: in order to add your job - you’d need to add to seed_job.groovy here: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/jenkins-vetsgov/seed_job.groovy#L1897-L1930
> it would also require it’s own Jenkinsfile here:
https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/Jenkinsfiles/rake
