### ISSUE TITLE
Content work for PDF certificate messaging

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#48458]
## Issue Description

Adobe has been issuing certificates under an authority that is set to expire on January 7, 2023. This means that a user who opens any PDFs after January 7, 2023, that were saved before March 2, 2022, will not be able to fill them out.

VA's form managers are resaving all of their form PDFs so that this won't be an issue. However, if a Veteran has a PDF saved under the old certificate and they open it after January 7, they won't be able to fill it out.

Public Websites created [this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1664838770820/f454c9875a67a1d2db4b5d5331388b38b557e98b?sender=7ca4cf4a-2e14-44d8-976a-a317afbc2823) with more detailed information about the issue and what we need to message to Veterans. 

We need to create messaging to Veterans alerting them of this upcoming problem. We discussed with Public Websites the idea of putting an alert on the [Find Forms landing page](https://www.va.gov/find-forms/) as well as on the landing page for any form that hasn't been updated after a certain last-updated date. 

If we are putting this alert on the 2 pages, they would need different content. 

## Tasks
- [x] Create alert content
- [x] Copyedit (Megan)

## Acceptance Criteria
- [x] Alerts are created

**Comment by jilladams** [comment]
From today's meeting, we would like to handling language against timing like so: 

pre-Jan (old cert expiration): 
* Leading up to Forms Manager Dec 15 target deadline to update all forms:
  * Search: forms are being updated
  * Details: this form is in process of being updated
* Once all forms are updated:
  * Search: forms have been updated
  * Details for every page: this form has been updated

For 6 months post-Jan 7: 
  * Search: forms should be good
  * Details on updated forms: form has been updated
  * (If a form doesn’t get updated: we may need more language for that bad scenario? )

User next step: download form again if you have older saved version. 

Collab cycle: PW can proceed, they will flag need for Content, but can go ahead and pursue design sign off and reference this ticket.

cc @wesrowe

**Comment by laurwill** [comment]
Hi @megzehn , could you give this alert text a copyedit?
- Note we tried to avoid "version" as "new version" is typically used when the actual content of a form changes, which isn't happening here.

**Info alerts on Find a Form landing page**:
 
**We’re updating our forms**
Starting January 8, 2023, you won't be able to use VA forms that have a “last updated” date before March 2022. If you downloaded any of these older VA forms, you may need to download new copies in January. 
 
**We recently updated our forms**
If you downloaded certain VA forms before December 2022, you may not be able to use them anymore. You can download new copies now. 
 
 **Info alert on form detail pages of affected forms only**:

**We’re updating this form**
If you download this form now, you may not be able to use it after January 8, 2023. You can download a new copy in January.
 
**We recently updated this form**
If you downloaded this form before December 2022, download a new copy now.

**Comment by megzehn** [comment]
These look good, @laurwill! 

My only suggestion is to consider adding "you'll need to" in the last detail page alert to soften it. 

**We recently updated this form**
If you downloaded this form before December 2022, you'll need to download a new copy now.

**Comment by laurwill** [comment]
Great, thanks @megzehn !

@jilladams @wesrowe , here's our suggested content for the PDF cert messages. Let us know if you have feedback or want to chat! 

Info alerts on Find a Form landing page:
 
**We’re updating our forms**
Starting January 8, 2023, you won't be able to use VA forms that have a “last updated” date before March 2022. If you downloaded any of these older VA forms, you may need to download new copies in January.
 
**We recently updated our forms**
If you downloaded certain VA forms before December 2022, you may not be able to use them anymore. You can download new copies now.
 
 Info alert on form detail pages of affected forms only:

**We’re updating this form**
If you download this form now, you may not be able to use it after January 8, 2023. You can download a new copy in January.
 
**We recently updated this form**
If you downloaded this form before December 2022, you'll need to download a new copy now.

**Comment by wesrowe** [comment]
Thank you, these look good! I'll mock them up and move us to implementation.

**Comment by RLHecht** [comment]
Thanks all! Going to close this out but please reopen if you need anything else from our team here.

**Comment by wesrowe** [comment]
@laurwill, As I went to add your "future copy" (the 2nd versions of each message) to tickets, I realized I'm not quite sure how the content you all provided is meant to be used.

In [this comment above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48458#issuecomment-1298944244), we meant to say that we need three versions of each message. 
1. One for now, 
2. One for mid-Dec, once all forms have been re-saved
3. One for Jan 7, when bad-cert PDFs will start breaking

So for example, from above:

> Info alerts on Find a Form landing page:

>We’re updating our forms
After January 7, 2023, you won't be able to use VA forms that have a “last updated” date before March 2022. If you downloaded any of these older VA forms, you may need to download new copies in January.

>We recently updated our forms
If you downloaded certain VA forms before December 2022, you may not be able to use them anymore. You can download new copies now.

... Obviously the first version is for situation 1 in my list above. Is your 2nd version for situation 2 or 3 in my list above?

**Comment by laurwill** [comment]
Hi @wesrowe , sorry about that! I misunderstood the ask — I thought we were only doing 2 versions. Here's updated content for the 3 situations you outlined. Let me know if you have feedback or need us to adjust again!

Situation 1: Messages before all forms are updated

**We’re updating our forms**
After January 7, 2023, you won't be able to use VA forms that have a “last updated” date before March 2022. If you've downloaded any of these older VA forms, you’ll be able to download new copies after December 15, 2022.
- Note: Since we're doing new messages for post-12/15 update, we thought it could be helpful to note the 12/15 date when new forms will be available. But if there's concern about meeting this deadline, we can adjust!

**We’re updating this form**
If you download this form now, you won't be able to use it after January 7, 2023. You can download a new copy after December 15, 2022.

Situation 2: After forms are updated, but before old forms will break

**We recently updated some of our forms**
If you downloaded older copies of VA forms, you may not be able to use them after January 7, 2023. To avoid problems with older forms, download new copies now.
- Note: We're assuming that after the updates are complete, people won't necessarily know if they have pre-March 2022 forms saved (since the date on the form itself won't change). So we've gone with a blanket rec to download new copies.

**We recently updated this form**
If you downloaded an older copy of this form, you may not be able to use it after January 7, 2023. You can download a new copy now.

Situation 3: After Jan 7, when old forms will break

**We recently updated some of our forms**
If you downloaded older copies of VA forms, you may not be able to use them anymore. You can download new copies now.

**We recently updated this form**
If you downloaded an older copy of this form, you may not be able to use it anymore. You can download a new copy now.

**Comment by wesrowe** [comment]
@laurwill, I'm sorry I missed your updates above. I see now that your team proposed an update to the copy to include a "dec 15" date when all forms will have been updated. This would be a nice "next steps" detail to offer Veterans if it were safe to offer it. But we can't commit at this time to Dec 15 resolution of last few forms, as the final 16 haven't budged in a couple weeks.

Since we don't have any confirmation that this will be resolved by Dec 15, I don't think we should commit to it to Vets. So for the Search page, really I think it's best to go with the previous version (which is now coded and in PR). Same for the Form Detail page. 

Lmk your thoughts. FYSA, we have an email out to Forms Managers to inquire about progress on those last 16 forms.

**Comment by laurwill** [comment]
Hi @wesrowe , now it's my turn to be late replying! Sorry about that. Totally understand about not offering the 12/15 date. Let me know if you need any other updates to these!

**Comment by RLHecht** [comment]
This new work is now finished. Closing and will reopen if PW needs more support.
