### ISSUE TITLE
Investigate "Refresh token is not defined" error

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48559]
https://vagov.ddog-gov.com/logs?query=signinservice%20signincontroller%20error%20deployment_env%3Avagov-prod%20%20-%22logout%22%20%22refresh%22%20%22Refresh%20token%20is%20not%20defined%22&cols=host%2Cservice&index=oct-01-oct-02-service-traefik-vets-api%2Cmain&messageDisplay=inline&stream_sort=service%2Cdesc&viz=stream&from_ts=1666195200000&to_ts=1666209600000&live=false

**Comment by bosawt** [comment]
This appears to happen when a user spends more than 30 minutes idle, then attempts an action. We appear to call for a `/refresh` without a refresh token, because the token itself has expired and the cookie is automatically removed.

The info token cookie probably is also removed, so if we want to prevent this specifically we could make sure frontend logs out a user if the info token cookie is gone

**Comment by bosawt** [comment]
![image.png](https://images.zenhubusercontent.com/5fb55f12a11eae1f7ca15bde/dbb5e4f6-ab4c-4560-b781-cfacad173929)

**Comment by bosawt** [comment]
This shows multiple successful `refresh` calls as the user is actually active, but then a more than 30 minute idle time, then the user attempts an action and `/refresh` is called, but without a refresh cookie because it has been automatically expired

**Comment by bosawt** [comment]
If there is an action item here, it is to force `/logout` if `vagov_info_token` does not exist

**Comment by joeniquette** [comment]
closing until frontend route calls are fixed
