### ISSUE TITLE
Investigate "Anti CSRF token is not valid" error

### ISSUE THREAD

**Issue by acaruso-oddball** [department-of-veterans-affairs/va.gov-team#48560]
https://vagov.ddog-gov.com/logs?query=signinservice%20signincontroller%20error%20deployment_env%3Avagov-prod%20%20-%22logout%22%20%22refresh%22%20-%22Refresh%20token%20is%20not%20defined%22&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=service%2Cdesc&viz=stream&from_ts=1666195200000&to_ts=1666209600000&live=false

**Comment by bosawt** [comment]
It seems like this happened because a `/refresh` was called after more than 30 minutes of apparent inactivity. The user did actually have activity, but it was `InProgressForms` related, so likely to be related to the issues we are seeing with certain forms routes not properly asking for updated tokens. 

Additionally, the user authenticated with SSOe halfway through filling out the forms. I think this happened because the user did an action that required they verify (or log in with a verified account after initially not being verified).

**Comment by joeniquette** [comment]
We will close for now and reinvistigate the errors after Alex fixes how some frontend routes are called
