### ISSUE TITLE
Add client_id to SiS refresh token calls

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#48795]
Need this for both success and failure of refresh calls

Why: https://github.com/department-of-veterans-affairs/va.gov-team/issues/48367

**Comment by bramleyjl** [comment]
This is our current `/refresh` controller method:
```
    def refresh
      refresh_token = params[:refresh_token] || token_cookies[SignIn::Constants::Auth::REFRESH_TOKEN_COOKIE_NAME]
      anti_csrf_token = params[:anti_csrf_token] || token_cookies[SignIn::Constants::Auth::ANTI_CSRF_COOKIE_NAME]

      raise SignIn::Errors::MalformedParamsError, message: 'Refresh token is not defined' unless refresh_token

      decrypted_refresh_token = SignIn::RefreshTokenDecryptor.new(encrypted_refresh_token: refresh_token).perform
      session_container = SignIn::SessionRefresher.new(refresh_token: decrypted_refresh_token,
                                                       anti_csrf_token: anti_csrf_token).perform
      serializer_response = SignIn::TokenSerializer.new(session_container: session_container,
                                                        cookies: token_cookies).perform
      sign_in_logger.token_log('refresh', session_container.access_token)
      ...
```
We call the route with the `refresh` & `anti_csrf` tokens, neither of which directly hold the `client_id`. The client_id becomes available to us in the refresh method after we run the `SessionRefresher`, we can call `session_container.client_id` to get it. Because the method has to go through
* param validation
* refresh_token decryption
* session lookup
* token validations
before we know for sure that we'll have the `client_id` there are a lot of instances where the method will fail and we call the error handling without knowing the `client_id`. The only workaround for this would be to perform some sort of check on whether the `/refresh` call was made with cookies or request parameters to determine if the *current* call is an API or web one - it's pretty hacky and doesn't tell us definitively about the session itself.

**Comment by joeniquette** [comment]
Closing as I found a solution that doesnt require us to add client_id to refresh
