### ISSUE TITLE
Design | Profile | Notification Preferences | Next Steps

### ISSUE THREAD

**Issue by SKasimow** [department-of-veterans-affairs/va.gov-team#49007]
### Background

We expect to support additional channels and notifications within our Notification preferences section. Next step is to start thinking about whether we need to change our edit model to accommodate this.

Tasks:

- [x] Determine what we need to answer this question: should we change the edit model for notification preferences or not?
  - Things to think through:
    -   Do we have enough information now to make a yes or no determination on if we want to change the edit model as we scale to add channels and notifications?
    - If we do not have enough information to decide whether we should change the edit model or not, what do we need in order to make this determination (eg. research, more info on how the feature is expected to scale near term, etc)?

Once the above is complete:

- [ ] Talk through with Samara/Sharon
- [x] Start documenting next steps

Acceptance Criteria:
- [ ] We have alignment on plan for next steps
- [ ] Can begin ticketing in support of this effort

**Comment by Samara-Strauss** [comment]
IMO the tasks are not to do any explorations or even determine if we should 100% make changes here. The task is to determine what we need to answer the question: should we change the edit model for notification preferences? So, thinking through:

- Do we have enough information now to make a yes or no determination on if we want to change the edit model as we scale to add channels and notifications?
- If we do not have enough information to decide whether we should change the edit model or not, what do we need in order to make this determination (eg. research, more info on how the feature is expected to scale near term, etc)?

Once Liz has thought through the above, then we can:

- Talk through with Samara/Sharon
- Start documenting next steps

I'm going to update the tasks for this ticket accordingly.

**Comment by andaleliz** [comment]
Hi @Samara-Strauss and @SKasimow [documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/notifications/notification-preferences/design/notifications-2.0-next-steps.md) is ready to review - it includes what we discussed yesterday, as well as a quick mock-up exploring how things could look today with the auto-save model, and what we learned from the first iteration.

If you'd like to meet again on this, I'm happy to discuss. Or you can leave any feedback/questions here. I'll hold off on closing this out until I hear from you. Thanks!

**Comment by SKasimow** [comment]
Hi @andaleliz - 100% agree with your recommendation for user research! 

With an increase in available notifications and choice of how users can receive, research will give us better guidance on how to move forward.

**Comment by Samara-Strauss** [comment]
Thanks for this write-up, Liz! It's super helpful. I don't have any further comments or questions.

**Comment by andaleliz** [comment]
You're welcome, glad you both thought this was helpful. I'll close this out.
