### ISSUE TITLE
Should KPI dashboards extend to other platforms outside of Domo? 

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#49437]
### Description

Should "4. Does your product/feature have Google Analytics tracking and a KPI dashboard in Domo?" consider to include a KPI dashboard in Google Analytics or other platforms? For example, our application has dashboards within Domo, Google Analytics and DataDog. 

There's probably a rationale for mentioning Domo explicitly, but I figured I would pose the question. 

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff

https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=collab-cycle-review%2Ccollaboration-cycle%2CCC-Request&template=collaboration-cycle-request.yml&title=Collaboration+Cycle+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D

**Comment by vbellissimo** [comment]
@benbrasso-agile6 Hi Ben, to answer your question, question 4 is worded that way because we determine whether or not the Platform Analytics team should be involved in your collaboration cycle or not. Based on your question, however, we've gone ahead and clarified that on the page there: https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/collaboration-cycle-kickoff Thanks!

cc @shiragoodman
