### ISSUE TITLE
[EVSS to Lighthouse] write the new code for the BE

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#49504]
Jerek did this.

**Comment by jacobworrell** [comment]
waiting for internal code review

**Comment by jerekshoe** [comment]
I've had Kevin and Kyle from the other squad review the code for this and so far there don't seem to be any major issues. I've decided to go ahead and write all the tests for this as well so that we can neatly wrap up the BE development phase of the project. Once testing is done merging approvals can be requested and the PR can be merged
