### ISSUE TITLE
Clarify freezing and unfreezing deployments during code freezes

### ISSUE THREAD

**Issue by holdenhinkle** [department-of-veterans-affairs/va.gov-team#49619]
Quick note, to capture the ticket:

- What do we need to freeze during code freezes, besides `vets-api` prod on Jenkins? 
- What about the other envs?
- What about GitHub Actions workflows?
- Other?

This came up in a conversation between Kyle Matheny and Holden Hinkle this morning while unfreezing `vets-api` prod on Jenkins after Veterans Day.

Is `vets-website` part of this question?

## Issue Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by rmtolmach** [comment]
Someone correct me if I'm wrong, but I know of three deployments that need frozen and unfrozen:
- vets-api - NOTHING needs to be done with this currently, because deploys to prod are manual and so they just wouldn't occur on a holiday
- vets-website - @rsmithadhoc is there documentation for the frontend code freeze?
- devops - Instructions are here: https://vfs.atlassian.net/wiki/spaces/OT/pages/1807777797/Enable+a+Holiday+Code+Freeze+By+Disabling+Automatic+Releases

I guess code freezes will be handled by the relevant CoPs going forward, so we just want to make sure there is relevant documentation and that the CoPs are reminded when they need to happen. This could be a Slack reminders for the dates listed here: https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-Holidayreleasefreezeschedule

**Comment by rsmithadhoc** [comment]
> Someone correct me if I'm wrong, but I know of three deployments that need frozen and unfrozen:
> 
>     * vets-api - NOTHING needs to be done with this currently, because deploys to prod are manual and so they just wouldn't occur on a holiday
> 
>     * vets-website - @rsmithadhoc is there documentation for the frontend code freeze?
> 
>     * devops - Instructions are here: https://vfs.atlassian.net/wiki/spaces/OT/pages/1807777797/Enable+a+Holiday+Code+Freeze+By+Disabling+Automatic+Releases
> 
> 
> I guess code freezes will be handled by the relevant CoPs going forward, so we just want to make sure there is relevant documentation and that the CoPs are reminded when they need to happen. This could be a Slack reminders for the dates listed here: https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-Holidayreleasefreezeschedule

https://vfs.atlassian.net/wiki/spaces/PTST/pages/2630975664/Front-end+Support+Responsibilities#Holiday-Deployment-Pause

**Comment by alyssagallion** [comment]
Verified with @rsmithadhoc good to close ticket. Closing!
