### ISSUE TITLE
Best bet request for "Mental health"

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-team#49894]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [ ] NEW: You would like to create a new best bet
    - [x] CHANGE: You would like to change an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @Joni Chan

# Section 2: Change Request

### Description
Please provide a brief description of the initiative and supporting information for the creation of a best bet.  
> During usability research for the VA.gov homepage, we discovered a few tasks which were challenging for Veterans and beneficiaries to complete from the homepage. Some Veterans prefer "counseling" to "mental health". Adding best bets will support discoverability of this important content.

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
> date/time: The redesigned homepage will be soft launched in December 2022 and should replace the current/existing homepage in January 2023. 
 
 ### Please provide the following information:
 - [ ] Identify the Best Bet requiring changes
> associated best bet: 
> VA Mental Health Services - URL: www.va.gov/health-care/health-needs-conditions/mental-health/
> Description: Find out how to access VA mental health services for posttraumatic stress disorder (PTSD), psychological effects of military sexual trauma (MST), depression, grief, anxiety, and other needs.
- [ ] Specify the change(s) that are required.  
> details about required change - suggest additional key words such as "therapist", "therapy", "counselor", and "counseling"
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: These requests are handled by the Sitewide Content and IA team. Reach out via Slack #sitewide-content-ia with any questions.***

**Comment by mmiddaugh** [comment]
[Best bets export](https://app.zenhub.com/files/133843125/24eb3f2b-9b9e-47a6-8c8b-9d90471d1322/download)

**Comment by heyjoni** [comment]
Hi @mmiddaugh, I considered "counselor" and a few other related terms (therapist, counseling, therapy) but they might be too broad to be a best bet. For instance, people might be searching for a physical therapist or career counselor instead. 

What I'll do is tag the VA mental health services page with these terms so it'll turn up in search, but not as a "top recommendation." Let me know what you think.

**Comment by mnorthuis** [comment]
@mmiddaugh Can you provide context to how the task was framed up in research so we can understand more about the finding.  I see the note "Some Veterans prefer "counseling" to "mental health"" but am not clear on what the task and subsequent results are that got to that.  For example, were they asked to "find information on mental health" or were they asked to "find someone who can help with mental health" - those two tasks have different direction in them, so I just want to be clear on what Veterans were trying to accomplish. 

@heyjoni Let's do a current state analysis on this topic so we can make sure we are surfacing the most important information based on what visitors are currently searching for.  Can you take a look at a few things in analytics
- What search terms are being used on VA.gov related to this topic today 
- What best bets are currently in play on those terms
- How does our current mental health page rank in our search results for those terms

This is a really important topic that needs to be surfaced, I just want to make sure we surface it where it's most needed, and that we don't create too many best bets that just result in banner blindness for them all.

**Comment by mnorthuis** [comment]
## Notes, data and recommendations

### Background on research:
- The research referenced in this request used a task framed up as "Find a mental health counselor or therapist". The task language can lead participants to use and look for terminology provided in the task itself
- The research task asked participants to find a provider, not information on services.  The landing page requested is focused on the services available, not on finding a provider. 

### Information on landing page (07/1/22 - 12/30/22)
- Page views: 80,877
- Bounce rate: 0.88%
- Entrance rate: 44.92%
- Top previous pages
  - Health care application - 29%
  - Health care hub page - 16%
  - Search - ~13%
- Top 5 VA.gov searches leading to the requested landing page 
  - mental health - 976
  - mental health program - 231
  - behavioral health - 59
  - anxiety  - 58
  - mental health services - 43
- Other searches leading to the request landing page relevant to this request
  - mental health counseling - 16
  - counseling - 12
  - mental health therapy - 4
  - mental therapy - 4

### Information on "counseling" in search (07/1/22 - 12/30/22)
- Search terms including the word "counseling" in the past 6 months with > 120 searches (avg 20/month)
  - marriage counseling - 686, CTR 18%
  - counseling - 521, CTR 16%, 
    - #1 page clicked (43 clicks) -  www.va.gov/health-care/health-needs-conditions/mental-health/ptsd/
    - #2 (22 clicks) - https://www.va.gov/burials-memorials/bereavement-counseling/
    - #3 (12 clicks) - www.va.gov/health-care/health-needs-conditions/mental-health/
    - Clicks resulting from this search term were mostly focused on mental health topics (~72 clicks to mental health related content)
  - financial counseling 351, 25%
  - There are a number of additional searches related to mental health services such as family counseling, relationship counseling, ptsd counseling, etc
- Current best bets for this term
  - [Bereavement counseling](https://www.va.gov/burials-memorials/bereavement-counseling/) - Bereavement counseling
  - [Education and Career Counseling (VA Chapter 36)](https://www.va.gov/careers-employment/education-and-career-counseling/) - Personalized Career Planning and Guidance (PCPG), or VA Chapter 36, offers free educational and career guidance, planning, and resources to Veterans and their dependents who are eligible...
- Mental health related pages that appear on first page of results for "counseling"
  - 6 - [PTSD treatment](https://www.va.gov/health-care/health-needs-conditions/mental-health/ptsd/)

### Information on "therapy" in search (07/1/22 - 12/30/22)
- Search terms including the word "therapy" in the past 6 months with > 120 searches (avg 20/month)
  - physical therapy - 1236, CTR 18%
  - therapy - 436, CTR 6% 
    - #17 (1 click) - www.va.gov/health-care/health-needs-conditions/mental-health/
  - occupational therapy - 423, CTR 28%
  - recreation therapy - 143, CTR 63%
  - massage therapy - 132, CTR 48%
  - mental health therapy - 12, CTR 50%
  - mental therapy - 8, CTR 50%
  - other searches containing "mental" and "therapy" - 10 additional search terms for 24 searches
- Current best bets for this term
  - [Application for Associated Health Occupations (VA Form 10-2850C)](https://www.va.gov/find-forms/about-form-10-2850c/) - https://www.va.gov/find-forms/about-form-10-2850c/- Mental health related pages that appear on first page of results for "therapy"
  - 2 - [Understanding Cognitive Behavioral Therapy for Insomnia](https://www.veteranshealthlibrary.va.gov/142,41434_VA)
  - 5 - [Animal-Assisted Therapies - Whole Health Library](https://www.va.gov/WHOLEHEALTHLIBRARY/tools/animal-assisted-therapies.asp)
  - 6 - [Cognitive Processing Therapy (CPT) for PTSD](https://www.ptsd.va.gov/publications/print/CPT_familyhandout.pdf)
  - 10 - [Acceptance and Commitment Therapy for Moral Injury](https://www.hsrd.research.va.gov/for_researchers/cyber_seminars/archives/video_archive.cfm?SessionID=3592)



## Recommendation

**General**
- Any best bets for this page should focus on terms related to mental health services, not on terms for specific types of providers/roles. 
- Not pursuing "therapist" and "counselor" at this time. These terms may be better served by content within the mentalhealth.va.gov subdomain, or facilities such as Vet Centers. 
- VA.gov search has low referrals to this page, the majority of traffic comes from external sources 
- After implementing the recommendations, the referrals from VA.gov search and performance of best bets should be evaluated to ensure they are successfully helping visitors find this content

**Keyword: "counseling"** 
- Observations
  - This term is somewhat broad in meaning, however many of the top searches are related to mental health topics
- Recommendations
  - Add "counseling" to the existing mental health best bet as either part of the description or as an additional key word. 
  - Improve description for existing bereavement counseling best bet
  - For the search term "counseling", ensure that the mental health landing page and the bereavement counseling page are the 2 best bets that are prioritized 

**Keyword: "therapy:**
- Observations
  - this term is likely a very broad term that is not returning desired results for any focused area of therapy as shown by the low CTR
  - because of the range of potential modalities under therapy, implementing a mental health best bet has some risk (low) that other types of therapies will not be found
  - very little mental health related content was included in clicks from this search term, the few items that were clicked on only had 1 click each 
  - However, mental health content and services are top priority, and finding ways to surface this content appropriately is critical
- Recommendations
  - change the existing best bet for the 10-2850c form to "match keywords only", then add the specific keywords from the description.  Use "therapist" in place of "therapy" in key words. This will target that best bet to those looking for information on specific roles, not therapy as a service.
  - Update the existing mental health best bet to include "therapy" as a key word 
  - Evaluate the performance of this keyword addition to see if it improved the CTR on the search term

**Comment by mnorthuis** [comment]
The following recommendations have been implemented:

- [x] Add "counseling" to the existing mental health best bet as either part of the description or as an additional key word.
- [x] Improve description for existing bereavement counseling best bet
- [x] For the search term "counseling", ensure that the mental health landing page and the bereavement counseling page are the 2 best bets that are prioritized
- [x] Update the existing mental health best bet to include "therapy" as a key word


This item will not be done until a business owner can be identified to approve change, or it is determined that it is a detriment to the veteran mental health content. 
- change the existing best bet for the 10-2850c form to "match keywords only", then add the specific keywords from the description. Use "therapist" in place of "therapy" in key words. This will target that best bet to those looking for information on specific roles, not therapy as a service.
