### ISSUE TITLE
Design Intent  - IA Feedback - Modernized Check-in, eCheck-in & Pre-Check-in, Simplified VA Header/Footer

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#49904]
## VFS acceptance criteria
- [x] Let Platform know when the **Must** feedback has been incorporated 
- [x] Leave any comments for feedback you decide _not_ to take
- [x] VFS team closes the ticket

## Thoughts/questions
- I think this is a really creative and thoughtful design. I'm excited to see how these experimental design components test, especially the simplified header/footer for your use case.

## Feedback
- Practice areas will document their feedback following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback).

**Must:**

**Should:**

**Consider:**
* Experiment with the location of the Spanish/English language toggle. Other teams that have done some user research on similar placement of this component were briefly discussed during the meeting - or connect with sitewide to determine what constraints we have around language elements. The simplified header in your designs may be a particularly great landing spot for this component. 

## Platform directions
- Remove the governance-team label
- Update "Issue Title"
- Link to collab cycle Request epic
- Add your feedback
- Remove the CC-Request label (only if you created the ticket using the New Issue link from the Collaboration Cycle Reviews board)
- Add assignees based on collab cycle touchpoint
  - **Design Intent**: VFS designer, VFS PM (optional), yourself (optional)
  - **Midpoint Review**: VFS PM, yourself (optional)
  - **Staging Review QA Only**: VFS PM, yourself (optional)

**Comment by benbrasso-agile6** [comment]
We have done some previous research and exploration on 1, different design patterns for the language toggle, and 2, reviewed some of Josh Kim's ideas. 

It's a bit interesting because Patient Check In, from what I understand, is the only app on VA.gov that has language translation, and therefore the component needs to almost appear related to our app vs. the entire VA.gov. For example, if we explored including it in the simplified header/footer, it might send a signal that all of VA.gov is translatable, which it is not today. 

We will be continuing to explore this in a subsequent epic, and therefore for now are not exploring this more as part of this collab cycle.
