### ISSUE TITLE
Provide samples of Forms with Tables for Nick

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#49967]
- [x] Provide a sample of forms with tables
- [x] Nick to update with simple, moderate or complex

 to review tables and determine which table types are doable using the Forms Library

**Comment by tbaker1026** [comment]
Here are some samples of table
[https://app.zenhub.com/files/133843125/1daae5bd-3bfe-44fe-8a6c-01520fbec138/download](https://app.zenhub.com/files/133843125/1daae5bd-3bfe-44fe-8a6c-01520fbec138/download)
[https://app.zenhub.com/files/133843125/5922a073-fab8-49f2-9fd4-37f120db1b92/download](https://app.zenhub.com/files/133843125/5922a073-fab8-49f2-9fd4-37f120db1b92/download)
[https://app.zenhub.com/files/133843125/5d143f7d-62a8-4e95-9992-68f174872b32/download](https://app.zenhub.com/files/133843125/5d143f7d-62a8-4e95-9992-68f174872b32/download)[https://app.zenhub.com/files/133843125/ca64599c-037c-445d-9985-9fe13f399a71/download](https://app.zenhub.com/files/133843125/ca64599c-037c-445d-9985-9fe13f399a71/download)[https://app.zenhub.com/files/133843125/68e5a59b-a3a7-4b3e-a00f-a107666837a2/download](https://app.zenhub.com/files/133843125/68e5a59b-a3a7-4b3e-a00f-a107666837a2/download)[https://app.zenhub.com/files/133843125/489f43bb-d937-45d6-8243-f8a7f7265298/download](https://app.zenhub.com/files/133843125/489f43bb-d937-45d6-8243-f8a7f7265298/download)

**Comment by tbaker1026** [comment]
@ndsprinkle attached are some sample tables let me know if you need a broader set

**Comment by ndsprinkle** [comment]
### 10-8678

The table shown in questions 7-11 is a relatively small table, but questions 8 and 11 ask for a "list", so in our code that would be an array. This definitely starts to get complicated because that means having arrays as properties inside of our arrays of objects. It seems like the lists in this example would just be arrays of strings, which is at least somewhat easier, but I still don't know exactly how the forms library would handled nested arrays like this. I would considering this very complex until I learn more from research/talking to Robin.

### 21-0304

Not sure what the "table" is in this form. If it's for questions I and J, those look like arrays of two date objects, so that's not super complicated. Still more complicated than a basic question, but not as bad as a multi-property array of objects. If we're talking about questions 14a and 14b, then that's also similar. It would be a relatively simple array of objects with two properties per object, so again more complicated than a regular property, but not impossible.

### 21P-534

Assuming the table is 23C to 23G, so that would probably be slightly too complicated. There are only 5 columns, but because one of the columns asks for a full name object (first, middle, last) and two of the columns need a date AND a city/state/country, it ends up being something like 10 properties for each object.

### 21P-534a

Looking at the table for question 8, I think this is right on the edge of being too complex. Again we have five columns, but the first column needs a full name object and the fourth column needs a city and state. This ends up making it like eight total properties per object, but their all simple, so it probably would be possible. It might just start to make our single page structure in the form look ugly.

### 26-6393

This is a complicated looking PDF. Section D and section E don't appear to be terrible. Section D might get slightly complicated because the first "Items" column would end up being an array of strings in our code, but if the forms library renders that well then the other columns look like simple integers/booleans that we could implement fairly easily. Section E looks fine, I think it's just two columns of integers. It's also not an unlimited list as there are a set amount of properties. There is that one "Other" line 35 that might get funky because we'd need to have a string property for just that, but the parent object wouldn't even be an array so it should be fine. Ultimately, this is a good example of a table that **doesn't** end up being an array of objects in our code.

### 26-6807

Questions 15 and 18 are probably too many properties per object. In addition to a handful of columns, they both have a column that asks for the name and address. In our code, the full name object is three properties and the address object is at least 6 more, so those arrays of objects end up having over 10 properties each.
