### ISSUE TITLE
Subway map for applications

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#50]
Placement of the "Start Application" buttons (before, in the middle of, & after subway map steps); # of "start application" buttons (1 or 2)

**Comment by jaredcunha-usds** [comment]
I can't really find the best way to describe this, but I think instead of "Subway map for applications," I'm trying to think of a way to describe some multistep process where a form might be involved, like: 

1) Create an account
2) Gather some documents
3) Submit application
4) VA processes
5) Decision

Another version of this might be for a user to track where they are in a process, so imagine the steps above for an authenticated user, we can indicate steps 1, 3, 4, and 5 as a 'current' step.

So to avoid confusion between patterns and components, maybe lead with the problem we're trying to solve instead of the dominant component.

**Comment by rtwell** [comment]
closing as these topics are captured in a slew of tickets #71 #70 #68 etc
