### ISSUE TITLE
Updated VTK SOCKS Access Instructions

### ISSUE THREAD

**Issue by mmccollum-va** [department-of-veterans-affairs/va.gov-team#50079]
### Description
For Mac users following [instructions](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy) for setting up VTK SOCKS Access, please include updated versions of overall steps and tutorial video for submitting GitHub SOCKS Access Request [form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D). The SOCKS Access Request form discussed in tutorial [video](https://www.youtube.com/watch?v=OnBhO3FVTTg) is very different compared to current [form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D) and does not include instructions for getting listed on Platform or VFS rosters.

### Relevant URLs

- Current VTK SOCKS Access instructions [link](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy)
  - Tutorial video [link](https://www.youtube.com/watch?v=OnBhO3FVTTg)
- Current GitHub SOCKS Access Request [link](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Coperations%2Cops-access-request&template=socks-access-request.yml&title=SOCKS+access+for+%5Bindividual%5D)

**Comment by laucon** [comment]
@mmccollum-va Do we want someone to rewrite the process and/or to make a new video of the process? I can do that if you want. I have experience making video tutorials and also with the Socks Proxy process. But maybe you wanted to do it yourself or have someone else do that. I'm not sure.

**Comment by laucon** [comment]
@mmccollum-va Also, if it helps, I noticed some inconsistencies with the Mac users process as written and the actual process I went through and I tried to make a few improvements to the process back in around May or June of 2022, but it was a bit of a complicated process and only limited changes were made. Also, I'm wondering if video is truly the best method since it's easier to edit text when a process changes than it is to edit video and because when using a video to do a process, a lot of people struggle to scan through the video's timeline to sync up with where they are in the process.

**Comment by mmccollum-va** [comment]
Please feel free to proceed with updating the process for requesting VTK SOCKS access for Mac users. Time permitting, an updated video would be valuable in providing visual cues to the user that they are on the right path.

**Comment by laucon** [comment]
@mmccollum-va Thanks! I'm doing this right now and I've spent the past several days improving this document. We're going to publish it soon, much improved and without videos because we feel that the text without videos will actually be both clearer and easier to edit when the processes changes and updates need to be made.

**Comment by laucon** [comment]
@mmccollum-va Quick update: I made a ton of great progress in the last week. We had one more question to get through before we could finish it, but our SME left for the holidays before that final question could be answered. So we should be able to publish the improved version after the New Year, but we will have to take that pause due to circumstances. Thanks

**Comment by laucon** [comment]
hey! I'm just letting everyone know that this is still being worked on. The SME went away for both Christmas and New Years before we could finish. But now everyone is back and we're back to fixing this! :)

**Comment by laucon** [comment]
We have now edited [the document](https://depo-platform-documentation.scrollhelp.site/getting-started/accessing-internal-tools-via-socks-proxy). I think it will be much more understandable to readers, now. If you have any additional issues, please let me know. Thanks!
