### ISSUE TITLE
X-Real-IP for EKS deployment

### ISSUE THREAD

**Issue by LindseySaari** [department-of-veterans-affairs/va.gov-team#50210]
## Description

We use the [X-REAL-IP header here for vets-api rate limiting](https://github.com/department-of-veterans-affairs/vets-api/blob/master/config/initializers/rack_attack.rb#L7). It appears that it's set in the ansible config in the devops repo on the revproxy:
- https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/deployment/config/revproxy-vagov/files/vagov-proxy.conf#L16

- https://github.com/department-of-veterans-affairs/devops/blob/b13559c10c8c6a7911de5505dad4d2f1520d1f1d/ansible/deployment/config/revproxy-vagov/templates/nginx_website_server.conf.j2#L110

- https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/deployment/config/revproxy-vagov/files/proxy-headers.conf#L5

We should be sure that this is still set in the EKS deployment to be used for vets-api rack attack rate limiting.

**Comment by considerable** [comment]
I've seen in the DataDog remote_ip logged both as IPv4 and as IPv6. The below sample has IPv6 from Comcast (2601:644:680:80b0:6d64:429d:7caa:beeb).

I will check if it comes from X-Real-IP header or from elsewhere.

```json
{
  "host": "9efe4cb07f99",
  "application": "vets-api-worker",
  "environment": "production",
  "timestamp": "2022-12-01T20:35:19.051502Z",
  "level": "info",
  "level_index": 2,
  "pid": 9,
  "thread": "processor",
  "duration_ms": 445.7890090000092,
  "duration": "445.8ms",
  "named_tags": {
    "dd": {
      "trace_id": "3952524573479249267",
      "span_id": "2189852476710972056",
      "env": "production",
      "service": "vets-api",
      "version": ""
    },
    "ddsource": "ruby",
    "class": "EVSS::CreateUserAccountJob",
    "jid": "f27f616e9d4e868ebc40e557",
    "request_id": "984a9c3b-0503-4da9-9c1c-ba963bb487a8",
    "remote_ip": "2601:644:680:80b0:6d64:429d:7caa:beeb",
    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "user_uuid": "N/A",
    "source": null
  },
  "name": "Rails",
  "message": "Performed MVI Query",
  "payload": {
    "uuid": "221a9fd351264e46a68233ed7a7065ee",
    "authn_context": "myhealthevet"
  }
}
```

**Comment by considerable** [comment]
It turns out that the logs are captured by the DataDog (DD) Agent which is configured as follows:   
- Parent helm chart package for DD installation on current EKS    
   https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/datadog-agent/
- Ansible role for DD installation on legacy BRD     
   https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/build/roles/datadog/
- Terraform for additional AWS and DataDog config such as DD dashboards, DD synthetic tests, etc.
   https://github.com/department-of-veterans-affairs/devops/tree/master/terraform/environments/datadog/   

None of the above is customized for processing Ruby Rails Puma headers such as X-Real-IP.

Overall for DD installation, this helm chart package gets deployed    
https://github.com/DataDog/helm-charts/releases/download/datadog-3.0.1/datadog-3.0.1.tgz

and these values get applied    
https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/datadog-agent/prod/values.yaml

There are no special rules for logging those custom HTTP headers like X-Real-IP in the current config.

**Comment by considerable** [comment]
It looks like with DataDog we shall learn to rely on standard aka predefined fields parsed from the logs.
Particularly, if the `X-Real-IP` field is not present, rely on the predefined `network.client.ip` field. as per
https://docs.datadoghq.com/logs/log_configuration/attributes_naming_convention/#web-access
