### ISSUE TITLE
Identify how central mail handles non-fillable fields

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#50231]
### Description

When dealing with forms that submit to central mail, we will primarily be using forms that are entirely fillable. However, in situations where a certain field or fields aren't fillable, we need to figure out how to handle this. 

Can we write to PDFs in non-fillable spots? Using an X/Y coordinate?

Can we re-generate the PDF prior to submitting to have all fillable fields? Or prior to digitizing? Are either of these practical as far as defining a standard process goes?

### Definition of done

- [x] We have a documented plan for how to handle non-fillable fields in PDFs
- [ ] If an example exists, identify a form that is currently digitized on VA.gov that uses central mail and has non-fillable fields that ultimately get filled out

**Comment by gmrabian** [comment]
Document for filling fields via X,Y coordinates: https://docs.google.com/document/d/1y49YoxkLbv2kHgIol-4agQ7MSGYI7PwSlrHlcfS89k4/edit?usp=sharing

**Comment by gmrabian** [comment]
I did not find an example of a form submitted to Central Mail that uses this text printing method to fill out a field. This indicates that either the existing forms have not seen this issue, have solved it another way, or that this issue is rare. I think the information collected in the document is enough of a way forward for now.
