### ISSUE TITLE
Facility hours not displayed

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#504]
### Status
UNRESOLVED

### Severity Analysis

- `sev 3` 
    - Can go out in a regular deploy but still needs fixed ASAP
    - Can be put into the owning team's backlog and scheduled by PM

### User Impact 

**Who is the user impacted by this problem?**
Many, many users; anybody looking at a location whose facility hours are malformed

**How does this problem affect the user?**
Malformed hours don't show up on the facility's page.

### Description

Many facilities have malformed hours. The ones I saw had hours like:
- Sunrise - Sunset
- 24/7

I put links to some examples in a [comment on the Sentry issue](http://sentry.vetsgov-internal/vets-gov/website-production/issues/57864/activity/).

### Steps to Reproduce

- Go to [this facility](https://www.va.gov/find-locations/facility/vha_544) (for example; there are _many_)
- Look at the `Hours of Operation`

#### Expected Results
The hours of operation for every day of the week are there.

#### Actual Results
Days with malformed hours are omitted. In I think most cases now, this means every day of the week: 
    ![image](https://user-images.githubusercontent.com/12970166/60737937-558bda80-9f11-11e9-87a3-c189360e966d.png)

### Further Details

- [Sentry Issue Link](http://sentry.vetsgov-internal/vets-gov/website-production/issues/57864/)

### Proposed Solution

- The front end translates a day's operation hours of `24/7` into something that means "always open"
  - Could be "Always open", "12:00a.m. - 11:59p.m.", etc.
- The front end doesn't log an error for `Sunrise - Sunset`
- The front end displays all malformed hours
  - Still logging errors for actually-malformed hours
  - Minimizes the usability impact
  - Should verify this with a UX designer
- The [Swagger doc](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/facilities/showFacility) is updated to show all possible valid times
  - While we're here, update the time ranges `9am - 5pm` to `900AM - 500PM` since that's what's expected...I'm pretty ~sure~ confident

**Comment by ncksllvn** [comment]
I don't think this issue is quite as widespread as it would appear from Sentry. It looks like each time a page is hit for a facility with hours malformed (like the facility linked in the ticket), we hit Sentry a whole bunch of times -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/a6a9d90f-9433-4cf7-9c9f-d31a9c1b5f0e)

Many of the facilities I checked had hours that looked okay ([example](https://staging.va.gov/find-locations/facility/vha_539GD)), but I do see that my local [VAMC facility in Cincinnati](https://staging.va.gov/find-locations/facility/vba_539) has malformed hours, even though the format doesn't look too bad -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/38f5b184-b7b8-4e60-a843-fa2736ce37e3)

As opposed to the formatted that seems to be expected currently -

![image.png](https://images.zenhubusercontent.com/59cb9de1b0222d5de47953d8/271511a1-d93f-4b4c-91dd-6b836772b067)

So maybe we just need to update the Facility Locator's formatter for render this new format? @cvalarida any guidance here?

**Comment by Karak888** [comment]
@andaleliz have you reviewed this and can we close it?

**Comment by andaleliz** [comment]
@Karak888 Thanks for following up - Kelson is going to show me the validation process this afternoon. I'll let you know as soon as I'm done.

**Comment by andaleliz** [comment]
@Karak888 This is validated and can be closed.
