### ISSUE TITLE
Update Camp Lejeune page with PACT Act info

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#50471]
## Issue Description

OPIA has created PSAs about the PACT Act and Camp LeJeune and are pointing people to [our water contamination health issues page](https://www.va.gov/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination/). They created a fact sheet that we'll need to take info from and add to our page so that Veterans have all the info in one place. 

## Tasks
- [x] Update page with info from fact sheet (Laura/Danielle)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance Criteria
- [x] Changes are live on the site

**Comment by laurwill** [comment]
Hi @DanielleThierryUSDSVA , the updated Camp Lejeune page is ready for your review. I didn't have time to refine everything completely, but I made the larger changes we discussed and the necessary accuracy updates.

http://preview-prod.vfs.va.gov/preview?nodeId=883 

Here are some notes and remaining questions:
- Added “if your mother lived… while pregnant with you” to account for in utero exposure for family members, which is also covered
- The family member application form says you don't need a "prior diagnosis" of one of the covered conditions in order to apply. So I went with "we may cover care for these conditions" rather than "you must have a diagnosis of one of these conditions" in the intro to the list of 15 health conditions.
- Live page combined info on filing an application for family member benefits with info on filing claims for reimbursement as a family member. I separated these and added missing claims info based on the [family member page](https://www.clfamilymembers.fsc.va.gov/) and this [claims PDF](https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/FS%2007-02_Claim%20Filing%20Information%20for%20CLFMP%20DEC2021_508).
- I found conflicting info on time limits for filing family member claims. The main Camp Lejeune legacy page says this, which aligns more with our live page:
![image](https://user-images.githubusercontent.com/104158104/206812144-11b19e07-7e0b-491a-8193-24ce491f1f26.png)
The claims PDF says this, which seems to have a different meaning, but it's a little hard to interpret:
![image](https://user-images.githubusercontent.com/104158104/206812205-990d608b-52c6-40eb-93b6-380a75f61eb5.png)
- In the PACT section, I combined the fraud and commercial questions to get down to 5 accordion sections. 

Let me know if you have any questions about my changes!

**Comment by laurwill** [comment]
Hi @megzehn ,

The updated Camp Lejeune page is ready for copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=883 
Let me know if you have questions when you get in there!

Noting that we removed the detailed info about timely filing requirements for family members — we'll plan to add this in a later update, either on this page or in a new family members page for Camp Lejeune.

**Comment by megzehn** [comment]
Thanks, @laurwill! Confirming this has been copy edited. 

One question for @DanielleThierryUSDSVA: should the primary action link that says, "File a disability claim online" go to our [How to file a claim page](https://www.va.gov/disability/how-to-file-claim/) or the [online form itself](https://www.va.gov/disability/file-disability-claim-form-21-526ez/)? 

Right now it goes to the "How to file a claim page." Our [PACT Act page](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) goes to the online form with the same text, so I just wanted to confirm!

Otherwise, this page looks good. Thank you!

**Comment by laurwill** [comment]
Thanks Megan! Danielle confirmed that we'll stick with the "how to file" link for now and potentially revisit later. I changed this back to a normal text link. 

@DanielleThierryUSDSVA this page is ready to share with SMEs. Here are some notes and remaining questions:
- We added a new section of PACT Act content based on the [PDF you provided](https://www.va.gov/files/2022-12/Camp%20Lejeune%20FAQ%20V12.6.22%201030hrs.pdf). We combined some related questions to limit the number of accordions and make this section easier to scan.
- We also moved the information for family members into a new section. Based on this [Camp Lejeune page](https://www.publichealth.va.gov/exposures/camp-lejeune/) and this [claims PDF](https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/FS%2007-02_Claim%20Filing%20Information%20for%20CLFMP%20DEC2021_508), we clarified that VA doesn’t provide health care directly to family members through this program—only reimburses their health care costs for the 15 covered conditions. Is this correct?
- Under “What supporting documents do I need for my application?” in the family member section, we removed the bullets about evidence showing you paid costs for a covered condition. This evidence seems to be required when filing a claim for reimbursement as a family member, not for the initial application to the program. Is this correct?
- We added a new question about filing a claim for reimbursement. We saw slightly different information about the timely filing requirements for family members on this [Camp Lejeune page](https://www.publichealth.va.gov/exposures/camp-lejeune/) and this [claims PDF](https://www.clfamilymembers.fsc.va.gov/Home/DownloadForm/FS%2007-02_Claim%20Filing%20Information%20for%20CLFMP%20DEC2021_508). So for now, we provided only basic information about filing claims and a link to the claim form, but didn’t include the time limits. If you can confirm how the time limits work for family members, we can add this information in a future update.
- We noticed that the [Camp Lejeune family members program page](https://www.clfamilymembers.fsc.va.gov/) includes an online application form. But this page was last updated in 2013. Are you still maintaining this online form, and is that the preferred way to receive family member applications?

**Comment by laurwill** [comment]
Hi @megzehn , 
We got SME feedback on this page, and Danielle and I reconciled. Noting that we only made minimal high-impact PL edits here, since this has gone through a complex legal review and we don't want to hold up publishing. 

Could you do a final copyedit of these updates for errors and omissions only, before we send back to SMEs for final approval? We'll hold to publish until we get the okay.

Here's the [sharepoint doc with tracked changes](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/ETI-TYRQSX9OhGBWTtJHW4cBkY9bFjSIipl7yXzlDpqq_Q?e=AWEoSV) 

I'll also add the Drupal preview here for a final copyedit, but wanted to pass along the Word version. Thank you!

**Comment by laurwill** [comment]
Hi @megzehn ,
Here's the updated Drupal node for copyedit: http://preview-prod.vfs.va.gov/preview?nodeId=883

**Comment by megzehn** [comment]
Thanks, @laurwill! Confirming that I copy edited this page in Drupal.

**Comment by laurwill** [comment]
hi @DanielleThierryUSDSVA , just documenting that Megan copyedited and tracked a couple more small changes in sharepoint doc, I updated Drupal, and she copyedited the Drupal node. This is ready to send back to SMEs.

**Comment by DanielleThierryUSDSVA** [comment]
Awesome! Thank you @laurwill and @megzehn!

**Comment by RLHecht** [comment]
These changes are live. Closing ticket.
