### ISSUE TITLE
Review Form Builder Tools

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#50548]
[Original Audit](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2018279425/COTS+Form+Building+Review+-+FLT)
Form Builders to Review
Cognito Forms: Good feature support across the board (although authenticated/unauthenticated user access is a question mark), would need to find out if using on Cognito’s infrastructure would be acceptable.

Form Assembly: The only candidate that has been through a FedRamp review, although it is only FedRamp Ready, not Authorized; would need to look at data format sent by the HTTPS connector and find out more about the review process for submitting forms that use login credentials.

Formstack: Good feature support across the board (although authenticated/unauthenticated user access is a question mark), probably the top of mind company for form building.

Review the following:

- [ ] Where is the filled in data stored, can the app send the data without storing the data (PPI Concerns)

- [ ] Can we embed the form on va.gov?

- [ ] Do they have an API to submit data?

**Also Review some open source options**

- [Budibase](https://github.com/Budibase/budibase)
- [Formio](https://github.com/formio/formio)

**Comment by tbaker1026** [comment]
**Cognito**

- Looks like store the data but it can be [encrypted](https://www.cognitoforms.com/support/75/entries/encrypting-entries) per field
[Data Security](https://www.cognitoforms.com/support/74/entries/data-security)

- [iFrame on site](https://www.cognitoforms.com/support/10/style-publish)

- Can send [JSON data ](https://www.cognitoforms.com/support/66/data-integration/webhooks)to a URL

**Form Assembly**

**Comment by ndsprinkle** [comment]
### Cognito Forms

No public API: https://www.cognitoforms.com/support/353/faq/does-cognito-forms-have-a-public-api

So that makes finding answers to some questions a bit more difficult. It seems that they're very focused on their UI for form creation.

#### Data Storage

I can't find anything explicitly explaining if you can choose to not store any data. They talk about not storing payment info (https://www.cognitoforms.com/support/74/entries/data-security), but it's unclear if they're saying _they_ don't store the data because a third party is storing it or what. They talk a lot about encryption for the data, so it may be that they generally store everything and encrypt it.

#### Embed on VA.gov

They have this embedding guide: https://www.cognitoforms.com/support/167/style-publish/embedding-guides

But all the embed codes are for various website builders that obviously don't help us. I would assume they have some method of embedding the form in a React app considering they support all these other types of sites, but they don't explicitly list it.

#### API to submit data

There is an API, but I don't have access to it.

**Comment by ndsprinkle** [comment]
### FormAssembly

HIPPA compliance: https://www.formassembly.com/hipaa/
FEDRAMP compliance: https://www.formassembly.com/blog/fedramp-fireside-chat/

Public API docs: https://github.com/veerwest/formassembly-api

#### Data Storage

Interesting help article about setting up Purge Response Data: https://help.formassembly.com/help/purge-response-data

Sounds like it's possible to control what data is retained and for how long it is retained. 

#### Embed on VA.gov

As previously linked, seems fairly straightforward to embed the form on any site: https://help.formassembly.com/help/340358-embed-your-forms-html

#### API to submit data

Docs available here: https://github.com/veerwest/formassembly-api

You can set an `endpoint` to submit the form data to.

**Comment by ndsprinkle** [comment]
### Formstack

#### Data Storage

Looks like you can disable the storing of any data with a simple toggle detailed here: https://help.formstack.com/s/article/Turning-off-on-Data-Storage

You can also disable the storing of submitted data: https://help.formstack.com/s/article/Disable-form-submission-data-storage

#### Embed on VA.gov

As previously linked: https://help.formstack.com/s/article/Can-Forms-be-embedded-into-our-own-web-page

Supports embedding in JavaScript, so should work fine in vets-website.

#### API to submit data

As previously linked: https://help.formstack.com/s/article/Formstack-API-Overview

This one is a little funky. Their API is for making requests to their database to grab info on forms/form submissions. I don't think that's what we care about here.

This seems more helpful: https://help.formstack.com/s/article/Submit-Actions

In the section "Send Data to an External URL (WebHook)" there are instructions on how to specify a specific URL to submit to. It utilizes a "shared secret" method for authentication, so we'd need to make sure this works with our vets-api setup.

**Comment by ndsprinkle** [comment]
### Budibase

General forms docs: https://docs.budibase.com/docs/forms

Seems pretty interesting. Utilizes a schema and has tools to automatically generate fields using field groups, cool stuff.

#### Data Storage

Struggling to find any information on this. If I go purely based on how they describe the submit action, it sounds like you choose what happens when the submit button is pressed, so there may be no storing of data by default.

#### Embed on VA.gov

Docs: https://docs.budibase.com/docs/embed
Discussions: https://github.com/Budibase/budibase/discussions/6839

Looks like we should be able to embed the forms, but their could be potential issues with Cross Site Scripting.

#### API to submit data

Docs on the submit button: https://docs.budibase.com/docs/public-forms#step-7-add-and-configure-submit-button

They use "actions" to control what happens when you hit submit. I _think_ this is the action to set up specific endpoints to hit on submission: https://docs.budibase.com/docs/actions#execute-query

**Comment by ndsprinkle** [comment]
### Formio

Basic overview: https://www.form.io/how-it-works

Supports "drag and drop" form building, so could be a very user friendly interface: https://www.form.io/features/advanced-form-builder
They even have a page about non-developers building forms: https://www.form.io/features/form-manager

#### Data Storage

Data Management page: https://www.form.io/features/data-management

This info isn't quite as clear as everything else, but based on their video it does seem like you have control over all submitted and uploaded data and can export and/or delete any of the data at any time.

#### Embed on VA.gov

As previously linked, step 5: https://www.form.io/how-it-works

Claims to use a single `<formio>` tag and works with React.js. Even supports CSS changes, but it says "simple" CSS changes, so I'm not sure what to make of that. 

#### API to submit data

It seems like you can do whatever you want with the submitted data.

GitHub `SaveSubmission` link: https://github.com/formio/formio/blob/master/src/actions/SaveSubmission.js
Vague "Connect to Anything" page on the main site: https://www.form.io/features/connect-anything

Considering everything is open source, we could conceivably fork the repo and make our own changes.

**Comment by ndsprinkle** [comment]
To summarize the findings, my top picks would be FormAssembly from the closed source group and Formio from the open source group. Formstack could also be a good alternative if neither of the two top picks prove to be that great.
