### ISSUE TITLE
Send a controlled number of users to the new VAOS experience

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5058]
As a product manager, I want to control the behavior that results from clicks on the VAOS CTA(s) on VA.gov so that I can direct some people to the new VAOS tool while continuing to send other people to the existing MHV tool.

AC
- [ ] Internal controls around how many veterans or what percentage of veterans get either experience (legacy link to MHV or new link to VA.gov VAOS)
- [ ] Veterans who have been opted into the new tool will not be sent to the legacy tool on subsequent CTA clicks (i.e., opt-in should persist for any given veteran)

**Comment by jbalboni** [comment]
Some notes on this:

1. Feature toggles are not enabled on static content pages. We can turn them on just for pages with the cta widget by adding the `connectFeatureToggles` call to the code that mounts the cta widget to a page
2. The way the cta widget works is that there are collection of app ids and a bunch of switch statements to put content in place depending on the id. This isn't great for us, since we want to toggle content within an app id. It looks like direct deposit may have worked around this, so maybe follow that pattern
3. There are two app ids for scheduling and both of these are set in Drupal. So we can't change them ourselves and should assume at least one of them will be staying the same
4. The existing scheduling CTA has some additional MHV account checks in front of it because it's a health tool. We don't have the same requirements.

**Comment by markgreenburg** [comment]
Also worth noting that we may need to keep both CTAs on that one content page – we shouldn't assume that we'll be able to consolidate to one CTA before we start the opt-in process.

**Comment by peggygannon** [comment]
@jbalboni @markgreenburg 

hello, here is CTA copy for after sign in. I have a couple of followup questions for you and depending on your answers I might need to tweak the copy further: 

1. The current CTA messages tell users that they *may* need to sign in again. Will this also be true for the new VAOS? 

2. Per our content sync, it's my understanding that a % of users will be "chosen" to use this tool based on their criteria. As such I didn't write the messaging as an "opt in". Can you confirm for that that that is accurate? 

3. In the CTA message, I mention that earlier appointments made through the legacy tool via My HealtheVet, will also be visible on VAOS.  Can you confirm for me that that is accurate?  I don't want users to be alarm that earlier appointments might be lost or not visible to them.  


**View your VA appointments online**
**We’ve launched a new online scheduling tool on VA.gov**
We invite you to try our VA.gov scheduling tool to view your appointments online. With this tool, you'll also be able to see any appointments you've made through My HealtheVet. 

You may need to sign in again to use this tool. If so, please use the same account you used to sign in here. 

{button} Go to VA.gov scheduling tool

**Schedule or cancel a VA appointment online**
**We’ve launch a new online scheduling tool on VA.gov**
We invite you to try our VA.gov scheduling  tool to schedule or cancel your appointments online. With this tool, you'll also be able to see any appointments you've made through My HealtheVet. 

You may need to sign in again to use this tool. If so, please use the same account you used to sign in here. 

{button} Go to VA.gov scheduling tool

**Comment by jbalboni** [comment]
Thanks @peggygannon 

1. No, not for the new one. Still true of the old scheduling app.
2. That's correct
3. This should be true. There's some nuance in that MHV has its own appointment list that previously was out of sync with the old VAOS, but I believe we should be matching it now. In any case, we're not changing where appointments are stored, all that's staying the same, so users aren't losing anything.

**Comment by jbalboni** [comment]
How does this look (I took out the sign in line)?

![Screen Shot 2020-02-04 at 10 34 03 AM](https://user-images.githubusercontent.com/634932/73759381-e346d700-4739-11ea-869e-a831a16977ab.png)

**Comment by peggygannon** [comment]
@jbalboni Hello. Thanks! just a few minor tweaks: 

1. Can we remove the Subheads "View your VA appointments online" and "Schedule or cancel a VA appointment online" from inside the alert box? Since the same header appear right above the box? 
(sorry I think the way I wrote the messages was confusing)

2. The header "We’ve launch a new online scheduling tool on VA.gov" should be the only bolded header in the alert box. Please also remove the periods at the end of this header.

**Comment by jbalboni** [comment]
Heh, I should have noticed those were duplicate headings:

![Screen Shot 2020-02-04 at 1 43 07 PM](https://user-images.githubusercontent.com/634932/73775635-4c3b4880-4754-11ea-9501-d2acf5ff006b.png)

**Comment by peggygannon** [comment]
@jbalboni thanks. Looks good!
