### ISSUE TITLE
SPIKE: What do we need to implement automatic maintenance window triggers

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#50757]

**Comment by brianseek** [comment]
Services that effect check-in:
- chip
- lorota
- vista-api
- clinician workflow
- vets-api

We would likely only want to add chip & lorota as auto dependancies. We may not want to automate this at all. There also may not be the ability to have full automation. Adrian and I are going to meet with Lee DeBoom next week to discuss.

**Comment by brianseek** [comment]
Had a conversation with Lee on the pci-api team. Part of the tier 3 team's priority is getting some of these services in pager duty.

There are blips in even the simple reporting. Getting those right would be key before adding them as dependencies on our app. Automatically putting things into maintenance mode is probably not a great idea without some more confidence in the error reporting. 

I have added this ticket to the backlog to setup some logging on the services after they are in pager duty so that we can evaluate when we feel they are ready to add as dependencies: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/51341
