### ISSUE TITLE
review instance authentication not working

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#5090]
## User Story or Problem Statement

As we are working through #4617, we discovered that authentication likely has not been working for some time on review instances. How might we get this working again so that developers can use these instances for manual and stakeholder testing on feature branches again?

## Goal

An instance that automatically gets created from a feature branch on vets-api has functional login, just like any of the other live environments.

## Objectives or Key Results this is meant to further
5. Ensure VSP scalability through increased self-service tooling and documentation
		
## Acceptance Criteria
- [ ] a review instance is automatically and successfully deployed when a pull request is opened against vets-api master branch
- [ ] a developer can login using staging credentials through the ID.me SAML auth flow without further intervention

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by wyattwalter** [comment]
I put that this as "blocking" the staging move ticket. It's not accurate that the ticket is totally blocked, but we haven't really provided much value in that ticket without this work also being completed.

@alexpappasoddball @johnpaulashenfelter @omgitsbillryan tagging you 3 because I think we've all talked about this at some point. Bill identified today that this was a larger issue when I asked for help with the configuration, and I'd like to get some help getting this going ASAP. I'm going to work with Bennie on getting other aspects of review instance provisioning and setup squared away, but could use some help in getting this straightened out.

**Comment by omgitsbillryan** [comment]
The login now works, yay!

Documentation for how login works on review instance:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/backend/review-instances.md

Logout, OTOH, is still in a "partially" working state and needs some attention. I created a ticket for that here:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/5985

I also create a ticket for future work that moves the SAML ACS url to it's own instance instead of taking up space in the staging revproxy:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/5949
