### ISSUE TITLE
Radio Component: Changing the text weight of the question label

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-team#50930]
To learn more about contributing to the Design System or requesting new components, requesting changes to existing components, and reporting bugs, go here.
https://design.va.gov/about/contributing-to-the-design-system/

---
# Bug Report or Design System update

- [X] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

 
The [Discharge Upgrade](https://www.va.gov/discharge-upgrade-instructions/) wizard is being updated to include the new radio components. The question label text needs to stay bold to enhance the distinction between the questions and answers. Due to how the component is set up, the question label text weight can't be changed.
  
 I've asked in the [DSVA design channel](https://dsva.slack.com/archives/C0NGDDXME/p1671471252709569) about this and have been told that we can leave the text in bold for now. 

This is what the wizard looks like if the question label text isn't in bold:

<img width="511" alt="208203709-24f2406d-a6fa-40c4-acb5-210501b21495" src="https://user-images.githubusercontent.com/104526584/208526325-9d77af92-ca75-4531-85c2-a424d3068dc0.png">
<img width="540" alt="208204698-59dd2045-e48f-4088-a416-0aa8f462ad03" src="https://user-images.githubusercontent.com/104526584/208526344-38019038-6cae-484a-ab8c-2b37faefcae3.png">

## What I expected to happen

We expected to be able to adjust the weight of the question label text to bold, but are unable to do so at this time.

**Comment by GnatalieH** [comment]
Hi @thejordanwood. I didn't realize your team was asking for a component update in our [Slack discussion](https://dsva.slack.com/archives/C0NGDDXME/p1671471252709569) about the Wizard. Since we've officially deprecated the Wizard pattern, it's not a good idea for us to make component updates to accommodate a more readable wizard. We are also in the process of migrating to the USWDS v3 version of [Radio button](https://designsystem.digital.gov/components/radio-buttons/). 

If your wizard requires a component update to bold the questions, I suggest leaving the questions in regular font weight. I also should've tagged @SarahKay8 in our thread yesterday. From an accessibility POV, bolding the wizard questions might not be a good idea. I'm going to tag Sarah in our thread now.

**Comment by FranECross** [comment]
@thejordanwood Is this still a concern, or has a resolution been determined? Not sure if I can close this or not. Thanks!

**Comment by thejordanwood** [comment]
@FranECross This can be closed. The questions now have a header styling on them in the current iteration of the [Discharge Upgrade wizard](https://www.va.gov/discharge-upgrade-instructions/questions). When this wizard is updated, it's going to be using the subtask pattern,[ similar to Income limits](https://www.va.gov/health-care/income-limits/introduction), where each question will get its own page.

**Comment by FranECross** [comment]
See comment above
