### ISSUE TITLE
[SSO-Login] Symmetric SSO from MHV to VA.gov

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#5097]
**User Story**
As a Veteran using VA Online Scheduling (VAOS), I need session interoperability from MHV to VA.gov so that when I am linked from MHV to VA.gov, I do not need to sign in again.

**Additional information**
RFC: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/SymmetricSSOAndUUIDs.md

**Acceptance Criteria**
1. Users logged in to MHV do not need to log in again if they navigate to VA.gov

**Comment by patrickvinograd** [comment]
Some raw numbers to ponder:
Since August 2018, VA.gov has been keeping an association between ID.me UUIDs for every user that logs in, and, if available, their ICN or EDIPI. 
This isn't a perfect mechanism - among other limitations it doesn't account for ICNs changing over time. But the raw data is still helpful. Also we don't track LOA or credential type in this mapping, that would be interesting to further slice and dice but it's not present.

```
Total unique ID.me UUIDs: 2,747,627
Users where we have at least one other identifier: 1,506,879 (54.8%)
    (Within above)
    Users where we have an ICN AND EDIPI: 1,494,801 (54.4%)
    Users where we have an ICN but no EDIPI: 3,661 (0.1%)
    Users where we have an EDIPI but no ICN: 8,417 (0.3%) (probably DSLogon users not found in MVI?)
Users where we have no other identifier: 1,240,748 (45.2%)
```

For that latter case, it would be really nice to know how many were LOA1, and which credentials were used, but as I said that data is not present.

Another related figure: there are just over 20,000 records with different ID.me UUIDs but the same ICN. So this represents two different ID.me wallets (which could be from say an ID.me and a MHV credential, or maybe just two separate email accounts) that map to the same VA identity. 

Takeaways:
* There's a lot of records, if we are going to do any bulk querying or data loading it's not in big data territory but also not trivial; we need to execute the queries in a responsible manner. 

* Thinking through the SSO scenario:  
  * if a user arrives via SSO from another site, and they used an ID.me credential, we're all set.
  * if a user arrives via SSO from another site with any other credential, but their ID.me UUID is already in MVI, we're all set. 
  * if a user arrives and MVI does not have their ID.me UUID, but we have them in this mapping table under their ICN or EDIPI, we can do an AddPerson to insert their ID.me UUID into MVI, and proceed from there.  
  * if a user arrives and their UUID is not in MVI and they are not mapped to any other identifier, we're stuck as far as matching them with existing data. At this point one option (if we don't want to back-fill this data into MVI en masse) is to ask them to one-time re-authenticate through the VA.gov sign-in, which will retrieve their ID.me UUID. This could be done under the guise of "we launched new SSO capability but we need to match up your data, please log in again"). 
  * however, probably a lot of these users without any mappable IDs are LOA1, and hence not even eligible for an MVI lookup. So if somebody SSOs in with an MHV or DSLogon LOA1 account, what can they even do? Save in-progress forms? Are we okay not having that work? Loading them in to MVI is not even an option anyway, right?
  * So then how many users are LOA3 (i.e. can do interesting things on VA.gov) but we don't have any ICN or EDIPI for them? Probably none or vanishingly few, right?

**Comment by patrickvinograd** [comment]
Copying an email (that is somewhat duplicative of last update) here for reference:

I keep going around in circles about this topic, trying to narrow down at least the category if not the exact number of affected users; it's complex. But trying to get some thoughts out for discussion in advance of tomorrow's cross-team meeting.

Basically I think we can solve this issue through a combination of techniques:

1. Using a VA.gov mapping table to insert ID.me UUIDs into MVI.
2. For users not in that mapping table, doing an ETL (extract-transform-load) from ID.me to MVI to add ID.me UUIDs to MVI.
3. For users who we cannot do either of the above, detecting that situation and potentially prompting them to re-authenticate the first time they SSO from elsewhere to VA.gov - this would have the effect of letting us associate their ID.me UUID to something else.

Here's how things break down:

VA.gov has a mapping table of all ID.me UUIDs for users who've signed in since August 2018. There are ~2.7 million records. If we were able to resolve the user in MVI, we have their ICN. There are 1.5 million records (54%) for which we have an ICN. Since we have an ICN, that indicates the user is in MVI and was authenticated at LOA3, so I believe we could safely add all these ID.me UUIDs to MVI where they are not already present. This covers category (1) above.

There are LOA3 users who are not in the VA.gov account table or don't have an ICN recorded there. That could mean they last signed in before August 2018. Or maybe they had bad luck and signed in when MVI was down, etc. But presumably ID.me has records of who they have authenticated successfully at LOA3 to VA.gov. For these we could do an ETL, it would be more complex because it'd need to be based on person search traits known by ID.me instead of a straightforward ICN lookup. This covers category (2) above.

Then there's everybody else - the 1.2 million accounts with no mapped ICN, plus everybody at LOA1 who signed in before August 2018.
* Presumably most of the accounts with no mapped ICN are almost all LOA1 or otherwise not in MVI. This means there's not a ton they could have actually done on VA.gov that would have created any data records. But one thing they might have done is use the save-in-progress forms feature, so they are still relevant.
* We don't need worry about ID.me credential users because by definition we'll have their UUID regardless of how they arrive. So really we are mainly concerned with MHV basic and DSLogon basic credential users.
* We shouldn't be getting *many* MHV basic or DSLogon basic users SSOing inbound to VA.gov because the other likely referrers (like MHV) would require an LOA3 session. (I believe that MHV is not going to switch to SSOe for Basic/LOA1 users)
* We can't insert records into MVI for an LOA1 user anyway. 
So for these users the best we can do is detect that they meet this condition, and prompt them to re-authenticate through the SSOe-ID.me broker flow. This will either get their ID.me UUID populated in MVI (for any LOA3 users that somehow slipped through the cracks) or, for LOA1 users give VA.gov a SECID association that it can store locally for future visits. This covers category (3) above.

If there is no appetite/capacity to do the MVI data population options mentioned in (1) or (2) (particularly the ID.me PII ETL process), that will expand the number of users for whom a one-time re-authentication (3) is necessary.

Another related figure: there are just over 20,000 records with different ID.me UUIDs but the same ICN. So this represents two different ID.me wallets (which could be from say an ID.me and a MHV credential, or maybe just two separate email accounts) that map to the same VA identity. So we'll need to address the case of somebody SSOing in from elsewhere and we have two candidate ID.me UUIDs to try to look up for them :/

**Comment by patrickvinograd** [comment]
Additional follow-up based on discussion with Damien:

- For LOA1 users, SSOe will not provide a SECID association, hence there would be no way to correlate their ID.me UUID to anything else. BUT, SSOe doesn't even support MHV basic users or many LOA1 users in general on any of the relevant partner applications, so we should not expect to see SSO sessions inbound from other sites to VA.gov. But calling it out here as a known limitation, that if there are other properties at LOA1, we can't really do bi-directional SSO.

- There's not a lot of appetite among our immediate (IAM+ID.me+VA.gov) team to do any kind of en masse PII transfer from ID.me to IAM. So we'd like to limit the MVI data loading that we do to the users in category 1, for which VA.gov has a well-established mapping from ID.me UUID to ICN. 

This leaves us in the following situation:
#### Users who can use SSO bidirectionally and seamlessly:
* Anybody with an ID.me credential regardless of when they have ever signed in to VA.gov.
* Anybody who signed in to VA.gov and was resolved in MVI at least once since August 2018

#### Users who can use SSO bidirectionally but will be required to one-time re-authenticate
* Anybody with a MHV Premium or DSLogon Premium who has either never signed in to VA.gov or has not done so since August 2018.

**Comment by patrickvinograd** [comment]
So I think we need two tickets:
1. Perform the account table -> MVI data migration
2. Implement a flow for when we accept an inbound session that prompts the user to re-authenticate if we don't get a ID.me UUID in their MVI correlated identifiers. Will need design work to decide on the UX here.

**Comment by ambikaroos** [comment]
The above tickets have been added
1. Account table > MVI data migration: [#5415](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5415)
2. Re-authentication flow if we don't get an UUID: [#5416](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/5416)
