### ISSUE TITLE
Spike on FormAssembly & Formio css and building a form

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#51128]

**Comment by jeana-adhoc** [comment]
I've played with both form.io and form assembly and have created 2 very basic forms.

- [Form.io](https://pro.formview.io/#/pndpsttigjhvdao/1010dchampvabenefits?header=0&reset=1)
- [Form Assembly](Form Assembly)

You can fill these out now and go through the process.

###Some notes:

**Theming:**
Form Assembly lets me do a lot of design/custom css in the browser. But Form.io needs developer/backend work to do theming  

I think this is in Form.io's favor. We may be able to more easily connect the design system to form.io's theme engine, where it looks like all of this has to be done in the browser on Form Assembly and would be way harder to maintained. But this needs to be further researched. An assumption: this would simplify the UI for form creators and all they have to worry about is getting the fields on the page in the right order with the right labels. All other design aspects would be handled on the back end.

**List and Loop**
List and loop is easy to set up on Form Assembly.

I could not figure out how to do this in form.io. Their documentation states its possible - but i think it's on the form creator, not for the form filler. This needs to be investigated further.

**Data Retention**
On Form Assembly, when setting up "esignatures", I was given this warning, "Notice: Because E-Signature Records must be retrievable by the respondent, all E-Signature Records are stored indefinitely. If you have any questions or concerns, please contact Support.” This leads me to believe we are not able to delete data submissions from form assembly for data privacy reasons. This could be a blocker for us.

I have no comment on data retention for form.io. I have not investigated it

**Accessibility**
Form assembly does have an [Accessibility statement](https://www.formassembly.com/accessibility/) and a [VPAT](https://cdn.brandfolder.io/EY32HRPJ/as/scwkrwszf8xz84nfh5rn8wc9/FormAssembly-VPAT-2021.pdf) However, the VPAT was not created by a 3rd party, it was done internally; There would be more credibility of the VPAT if it was done by a 3rd party.

Form.io does have accessibility support. It seems that this is done through [additional modules that have to be installed](https://help.form.io/intro/developer-tool-ecosystem/accessibility). It looks like that support though comes from (or was started by) [USWDS](https://github.com/formio/uswds).

**Other Gov Orgs using these systems**
Form Assembly
[City government Case Studies](https://www.formassembly.com/cases/)
[FedRamp Ready](https://www.formassembly.com/blog/government-cloud-release/)

Form.io
[USDWS](https://github.com/formio/uswds)
[HUD](https://www.form.io/press-release/form-io-selected-by-us-department-housing-urban-development-for-forms-service-solution)

**Comment by jeana-adhoc** [comment]
It appears I have loaded the Form.io form too many times and now we can't use it. I'm in touch with them to see if this can be changed.

**Comment by jeana-adhoc** [comment]
I demo'd this with the team. And Form.io looks promising/interesting—especially due to the USDWS integration. For now, the trial accounts will expire, but I am likely able to re-open them when needed.

**Comment by jeana-adhoc** [comment]
Related to #51422

Closing this ticket for now.
