### ISSUE TITLE
(Samara) Mention a blue info box in the template

### ISSUE THREAD

**Issue by laucon** [department-of-veterans-affairs/va.gov-team#51330]
### Tasks

- [ ] **Add to Confluence template** how to add a blue info box for permissions access to certain links

**Comment by SSimmorins** [comment]
Since this seems difficult to manipulate the Confluence template, I went ahead and added a short guidance sentence with an example sentence directly in the Style Guide in the Formatting and Organization in the notes and caution section table.  I think it should be an inline note rather than a blue text box just in case there are other sections in the document the author needs to use it and it's not excessively used.  Let me know what you think tomorrow Vicky,
