### ISSUE TITLE
[Platform Website] Update 'Store a secret in Parameter Store' documentation  

### ISSUE THREAD

**Issue by jhouse-solvd** [department-of-veterans-affairs/va.gov-team#51350]
## Description
The Platform Content Team is editing Platform documents so that these documents no longer link to Confluence pages because VFS team members can no longer see Confluence pages. 

The "Key Management" document in the Developer Docs section of the Platform Website has at least one link to a Confluence page. 

## Resources
In [Store a secret in Parameter Store](https://depo-platform-documentation.scrollhelp.site/developer-docs/store-a-secret-in-parameter-store), under the “Managing Secrets” heading where it says “[view our instructions](https://vfs.atlassian.net/wiki/spaces/OT/pages/1951793242),” there’s a Confluence link.

- How do we fix this? 
  - Is there a comparable document we can link to instead? 
  - Is there a way to edit the document, so we no longer have that link? 
  - Should we add a note saying that only certain team members can access the link, so if you’re getting a broken link, don’t worry about it? 
 
## Acceptance Criteria
- [x] "Store a secret in Parameter Store" is updated with accurate information 

## How to configure this issue
- [x] _Team label assigned_
- [ ] _Epic assigned_
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_

**Comment by jhouse-solvd** [comment]
Working on this now.

**Comment by jhouse-solvd** [comment]
I made some updates to [the document](https://vfs.atlassian.net/wiki/spaces/OT/pages/1951793242) linked to "view our instructions." 

My recommendation is to publish the document linked above - "Set up AWS Command Line Interface (AWS CLI) to use Multi-factor Authentication (MFA)" - on the Platform Website as a sub-page to ["Set up your AWS Account"](https://depo-platform-documentation.scrollhelp.site/developer-docs/set-up-your-aws-account). 

Requesting a review from @laucon.

**Comment by laucon** [comment]
This it totally doable and makes a lot of sense. So I will publish this. Thanks!

**Comment by laucon** [comment]
Also, you said "sub-page." I made [Set up AWS Command Line Interface (AWS CLI) to use Multi-factor Authentication (MFA) ](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1951793242/Set+up+AWS+Command+Line+Interface+AWS+CLI+to+use+Multi-factor+Authentication+MFA) into its own page that is listed directly underneath [Set up your AWS Account](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1886781475/Set+up+your+AWS+Account). So I didnt make it into a parent page or add a new section within  [Set up your AWS Account](https://
<img width="665" alt="Screen Shot 2022-12-30 at 11 02 24 AM" src="https://user-images.githubusercontent.com/14806304/210089790-e818b76f-8c9d-41cb-a0ee-136ccd62f67a.png">
vfs.atlassian.net/wiki/spaces/pilot/pages/1886781475/Set+up+your+AWS+Account). But I think what I did works perfectly. Thanks! We will officially publish this on Tuesday since we dont publish Fridays and Monday we have off.

**Comment by jhouse-solvd** [comment]
@laucon - That sounds great. Thank you so much!

**Comment by laucon** [comment]
Done.
