### ISSUE TITLE
[BE] Onsite notifications v2: Support technical discovery

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#51451]
## Background
As the new FE dev for My VA performs technical discovery for adding new onsite notifications, they will need some backend support. This ticket is to capture work supporting that effort.

## Tasks
- [ ] Meet with Allison, our new FE dev, to help them with familiarization of onsite notifications and technical discovery around adding new ones

## Resources
- [Project outline: Scaling onsite notifications](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications/notifications-v2#project-outline-scaling-onsite-notifications-onsite-notifications-v2)
- [ MVP documentation: Backend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#backend)
- [MVP documentation: Frontend technical notes](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications#frontend)

**Comment by tpharrison** [comment]
@ajakabcin @allisonlu and I met and reviewed how the current implementation of onsite notifications works.  

At this point, it is a bit difficult to estimate the level of effort for scaling notification since we don't know what the intake looks like and how it will be designed on the FE.  Can we all meet to discuss this further?  Reminder - I'm OOO next week.

**Comment by ajakabcin** [comment]
Thanks @tpharrison appreciate your help on this! Yes we can reconvene on the LOE question when you're back
