### ISSUE TITLE
MDT- Address step-  Veteran contact details - edit address details, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5165]
## User Story:
As a veteran, I need to be able to edit my mailing address so that I can update or correct information.

## Tasks
- [x] Create a high fidelity mockup depicting how a veteran might edit address and contact details
- [x] Upload exports to Invision and indicate initial focus point as a comment

## Acceptance Criteria:
Mockup aligns with VA.gov’s design system
Veteran is able to edit their mailing address
The screen’s initial focus is incorporated
Sketch artboards are uploaded to Invision and linked in this ticket as a comment

**Comment by rileyorr** [comment]
Since we're using a text input field component to capture email addresses, Veterans can overwrite the existing email with a different one. 
Prototype for reference: [Email address component selected](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/404455879_Page_2-_Contact_Info_-_Email)
@mojaray2k & @mr0sari0 let me know if you have any questions or would like to sync about this ticket :)
