### ISSUE TITLE
MDT- Address step- Veteran contact details - add forwarding address, v1

### ISSUE THREAD

**Issue by wygonikGCIO** [department-of-veterans-affairs/va.gov-team#5168]
## User Story:
As a veteran, I need be able to add a forwarding address so that I can have my items sent to the address I wish_.

## Tasks
Create high fidelity mockups depicting how a veteran might add a forwarding address
Upload exports to Invision and indicate initial focus point as a comment

## Acceptance Criteria:
Mockup aligns with VA.gov’s design system
Veteran is able to add a temporary forwarding address for a set duration
The screen’s initial focus is incorporated

**Comment by rileyorr** [comment]
Hello! We previously discussed a forwarding address feature; since moving towards using text input fields for the shipping address, there isn't really a need for a forwarding address feature. I included verbiage indicating the average time it takes for packages to ship as reference when deciding what address to ship their package to. 

Prototypes to reference: [Pre-filled address](https://vsateams.invisionapp.com/share/Q7VVWGZUG4N) | [Manually filled address](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/404456156_Page_2-_Contact_Info_-_Manually_filled)
@mojaray2k & @mr0sari0 let me know if you have any questions or want to sync about this ticket :)
