### ISSUE TITLE
[Spike] - Determine Logic for Registration Check in VAOS

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#51718]
## Background/Request
For a veteran to see their appointments in VAOS they must be "enrolled" in VA health care and "registered" with at least 1 VA medical center that accepts VA Online Scheduling.  If the veteran does not meet these requirements, then they will see this message once they are logged in and try to view their appointments.

![image](https://user-images.githubusercontent.com/97117349/211656726-dab89e00-c66c-47e0-bc84-96f70249e462.png)

### Goal
The goal of this spike is to document what checks are being made in VAOS to determine if a veteran meets the qualifications of being "enrolled" and "registered".

### Requirements to Consider
No additional requirements.

## Tasks
- Answer the following questions:
  - Q  What api call and fields are being looked at by VAOS to determine if a veteran is "enrolled" and "registered"?
  - Q  Are "enrolled" and "registered" two distinct checks or are they the same thing?

## Time Box
6 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by simiadebowale** [comment]
Q What api call and fields are being looked at by VAOS to determine if a veteran is "enrolled" and "registered"?
A: VAOS FE makes a call to` /v0/user`.  That endpoint returns a response with a field named: `vaProfile`. this vaProfile field contains a field called `facilities`
[Here's a sample response](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/user/getUser)

`"vaProfile": {
        "status": "OK",
        "birthDate": "20010531",
        "familyName": "Morgan",
        "gender": "M",
        "givenNames": [
          "Cecil",
          "Matthew"
        ],
        "isCernerPatient": false,
        "facilities": [
          {
            "facilityId": "983",
            "isCerner": false
          },
          {
            "facilityId": "984",
            "isCerner": false
          }
        ],
        "vaPatient": true,
        "mhvAccountState": "OK"
      },`
Our logic checks if the `facilities` field is empty. If it is, we determine the user/veteran is ineligible to use VAOS because they have no registered VA Medical center.
Q Are "enrolled" and "registered" two distinct checks or are they the same thing?
A: It appears they are the same thing. We do not make any other checks apart from the above listed check.
I logged into staging with my account and I copied the response gotten from the `/v0/user` endpoint and mocked it locally. I was getting the same error message in the image above but after adding a mock facility into the `facilities` field, I no longer got the error message and I was able to get into VAOS.

The facilities data is gotten from MPI.

cc: @JRRoof

**Comment by JRRoof** [comment]
@simiadebowale - Is the "vaPatient" field used for anything?  I'm wondering if it is possible for a veteran to not be registered at any facility but still have the "vaPatient" field be true?  Probably a question for the team managing the /v0/user end point.

**Comment by simiadebowale** [comment]
@JRRoof - I toggled the value from true - false and it did not affect anything. I still got the error message when `vaPatient` was set to true and the `facilities` field was empty.  When `vaPatient` was set to false and the `facilities` field contained a facility, error message did not display so it would appear the value of that field does not affect anything we're checking.

**Comment by ldelacosta** [comment]
Added the spec to the [VAOS GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/product/page-logic/registration-check.md) - @JRRoof could you double check and make sure I have everything covered?

**Comment by ldelacosta** [comment]
@outerpress - let me know if you need help putting this in our GH document. Thanks!

**Comment by outerpress** [comment]
@ldelacosta I added this info to [this feature reference page](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-lists/appointments-home.md)
