### ISSUE TITLE
Yellow Ribbon MVP Design Review

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#5182]
- Hotspots seemed off in the desktop prototype. I assumed we are supposed to click the add to compare button but the hotspots appeared on the text above the button.

- For a quick styling tip for the compare bar--I suggest we use source sans pro rather than bitter, because it seems a bit more appropriate since the bar/button is not a heading 

- Maybe instead of a bar that appears below, we could style it as a drawer that pops from the right? Can't think of any existing patterns like this at the moment. It could be worth exploring! 

- Other styling ideas for the bar (I'm realizing this is a MVP so maybe we could explore later!), could be the way samsung does it's comparison tool on their ecommerce website. The bar pops up with "mini cards" inside, letting you know how many you can compare, there's also the option of clearing all or deleting cards off the list. example: https://www.samsung.com/us/mobile/phones/galaxy-s/?model_family=Galaxy+Note10%2B+5G,Galaxy+S10+5G

- The card does have a little awkward empty space. We could try putting the "add to compare" button on the side rather than under the content and see if that makes it more symmetrical.

**Comment by andaleliz** [comment]
Thanks! I had recently updated the screens but not the hotspots, so those are fixed now.  

I do want to explore alternatives for the compare button, and the Samsung example is really close to something I had in my "gettin' fancy" section when I was doing the initial concepts! I felt like since this is an MVP keeping it simple was the best approach in this instance. But, I do really like that idea for MVP 1.1..or 2.0...whatever the numbering will be :)

I tried some variations on the cards, and in trying to be consistent with Ryan's card designs and placing the CTA in the "footer" of the card, landed on what you see in the prototype. Here are some of the alternatives, so you can see.  I think of these options, the checkbox works the best, but am not sure it's better than what I've got in the prototype.  Perhaps something we can explore down the road? I don't think we have any true comparison tools anywhere else on va.gov to set precedence for us.

![image](https://user-images.githubusercontent.com/55992116/73207455-b9c2f580-4112-11ea-8737-65245013e1fa.png)

Do I close this issue now that the hotspot issue is addressed, as it relates to the usability test? Or is further action required before this can be closed? Thanks for helping me understand this process.

**Comment by CrystabelReiter** [comment]
Sorry Liz! I didn't see the last sentence on your comment. 

I also prefer the compare checkbox as well! I'm hypothesizing that the button at the footer would be more noticeable to click/main action of the card, so I think you went the right direction.

I just discussed the prototype with Emily and we agreed on a couple more points: 

- We recommend to change the table format for a blue header bar to a gray one in the pattern library since the blue bar does seem interactive when it isn't 
- We recommend to change the red x in the comparison section to a text link, perhaps "remove" with an x. Just so that it's easier for screen readers to decipher. Also we can possibly add a clear all/start over button as well
- We suggest to make the hotspot for the green bar to extend across the bar and not just the text 

If it is possible to change the table header to a gray bar before the usability test, we highly recommend it! 
All other feedback points can be taken into consideration after the usability testing.

**Comment by andaleliz** [comment]
Thanks for the feedback! Gray bar updated, and hotspot. I went with blue as an attempt to "breathe life into the page" as other designers have said, but certainly don't want to introduce confusion.

I'll take the suggestion about the text link into consideration.  I'm an advocate for avoiding text-link styling on buttons, to set consistent expectations across the site; I'll explore a middle ground that's clear and SR friendly.  I think we can still make the `x` SR friendly with the right mark-up, but we'll see what the accessibility review reveals.   One reason I chose the `x` was to optimizing space allowance on mobile screens.  This is a great point to take into consideration though - thank you!
