### ISSUE TITLE
Alert usage

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#52]
Picking the right alert level

**Comment by jenniferlee-dsva** [comment]
Couple thoughts and recommendations - as we discussed @rtwell
- In-body alerts
- Banner alerts – ppl conflate these, so I think it’s good to discuss these together, so it’s clear contextually that one is not the other. 

**A.	In-body alerts**
a.	On non-application/non-authenticated pages, we mainly use these 2 types:
- [!] icon warning alert (with/without expander link)
- [info] icon informational alert (with/without expander link)

b.	In-body alert guidance: 
i.	/ use warning alert only when there is serious negative consequence if the user does not do something or know something communicated in the alert. 
ii.	/ use informational alert when it’s not a warning about a consequence. It warrants more attention than a regular note in body copy. (Most situations can be addressed by regular body copy as a bolded Note text.)
iii.	/ any number of  in-body alerts can appear in the body content, anywhere within body content…BUT
iv.	/ they can’t stack on top of each other, right after one another
v.	/ they should be co-located with relevant contextual body content

**B.	Banner alerts -- the full width one that goes across the top of the page**
a.	Banner guidance:
i.	/ use for emergency or very urgent communications only. Ex: hurricane alert; government shutdown affecting VA services, etc.
ii.	/ do not stack - max is one per page at any one time. (If multiple emergency issues occur at once, make message content combined and link out to a landing page or to individual affected medical centers, for example.)
iii.	/ can be used on homepage or lower level pages. (I can imagine that if it is a true emergency, it might warrant displaying on lower level pages - like all the hub landing pages or regional office pages.)
iv.	Nuclear exception – case by case: EX: one instance on the Appeals page. In general: recommend designing the page and content, so you’re not locked into using a banner for informational or navigational content.)
v.	/ OPIA (Josh Tusher) has access to directly publish emergency banner messages on the homepage, since this agreement was made prior with OPIA. In the future: VAMCs will also have access and rights to publish banner alerts on their regional level pages. (Example: The Pittsburgh VAMC sometimes has clinics whose hours are affected during snow outages, and might put up a local snow banner alert on their Beaver County clinic landing page. But they will not be able to publish these "up," at the VA.gov homepage level.)

**Comment by jenniferlee-dsva** [comment]
@jaredcunha-usds  - Based on our Monday meeting, could we get these guidance into the design system section for alert boxes? I can revise ^ above, so it's in smaller chunks and not outline-y. LMK how you want to do next step.  

Also a few other things from Monday...

The alerts are not really 'status' notifications in the non-authenticated experiences, and should simply be called a warning alert or an informational alert. 

And the plain color-only boxes, I think we also decided these were never used as alerts and should not be considered as part of the alert variety of components. (Don't know if there's a better home for these visual color-only call out boxes.... They seem more akin to how we use the gray boxes for "More info" or "Related resources" type of content. )

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva Thanks for reminding me. I'll write some tickets for the platform team to get the ball rolling on some of these. As far as I can tell, that effort will look something like:

- Refactor background-only alert instances on VA.gov to use the feature component (they are used in some places). 
- Remove background-only code from Formation design system 
- Remove documentation and code samples of background-only alerts from design.va.gov
- Revise documentation on alerts component page to reflect VA.gov usage

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva I managed to find several more examples background-color-only alerts in searching the repo for va.gov

https://github.com/department-of-veterans-affairs/vets-website/search?p=1&q=background-color-only&unscoped_q=background-color-only

I don't know the context for all of these, but I don't think we can migrate all of them to featured content components. Many look like they are used to provide feedback in forms, for example: 
```
<div className="usa-alert usa-alert-error background-color-only">
 You’re signed out of your account. {noAuth}
</div>
```

In order to proceed, I'm going to need to know how to migrate all of these so that can be communicated to the devs. 

If I remember correctly, what I mentioned about migrating to the featured content component is correct based on the examples we managed to find in the Monday meeting. With these ones I found on search, I do think the context is an _alert_. So, perhaps what we might need to do is:
1. Change the documentation and examples to reflect that background-only alerts a used as form feedback, and should be very short (ex. " We’re sorry, but we’re unable to connect to VA.gov. Please check that you’re connected to the Internet and try again.")
2. Migrate any examples that are not used for that type of feedback to featured content components

Does anyone have any thoughts on this?

**Comment by jenniferlee-dsva** [comment]
@jaredcunha-usds  - One thing I want to call out:
<<Refactor background-only alert instances on VA.gov to use the feature component (they are used in some places).>>

Definitely was not my intention and we should not automagically migrate these multi-colored boxes into the Featured Content blue box. For one, in Drupal, there will only be 1 Featured Content blue box per page; and it will be used for eligility/requirements type of information, not any old type of content. 

I wanted to address this item first.

**Comment by jenniferlee-dsva** [comment]
@jaredcunha-usds  - So minus ^ Featured Content blue box issue, the remaining questions have to do with:

- Remove background-only code from Formation design system
- Remove documentation and code samples of background-only alerts from design.va.gov
- Revise documentation on alerts component page to reflect VA.gov usage
- Remove background-only alerts from react components
- Remove background-only alerts from React documentation site

AND your other comment: 
<<Change the documentation and examples to reflect that background-only alerts a used as form feedback, and should be very short (ex. " We’re sorry, but we’re unable to connect to VA.gov. Please check that you’re connected to the Internet and try again.")>>

Hmm, could we take a look at a few of these examples of background-only texts being used as form feedback? The ^ example sounds like a typical error message, and I am not familiar with how we provide those types of messages.  This would be good to review together when @rtwell is back (I think next Wed/Thurs).

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva In Drupal, it might be set up that way. In other parts of VA.gov, there are instances where the background-color-only is used in a way that is visually indistinguishable from a featured content component. The main difference is the class naming in the code being used. Which is why we discussed migrating (manually).

It seems we may need to audit the current usage of these alerts. I don't have screenshots handy, but it seems they are used in examples like:
- the user loses internet connection before trying to submit the form
- claims decision ready + additional instructions 

There are lots of others. I'm just looking at the code, but from what I can see, the background-color-only alerts are widely used. What I don't know is whether or not what turned up in the results is still relevant. But after digging around, I am now hesitant to remove background-color-only versions from alert component until we reach a decision about what to do about all the existing instances. I think it's worth going over this in the Monday meeting.

**Comment by jenniferlee-dsva** [comment]
Yep, I did not intend to suggest deprecating those background-only components completely -- just not bucketing them with "alerts" because they appeared to be used for a variety of content types. 

Also, I was primarily focused on non-authenticated experiences AND warning + informational alert components. I.e., that the background-only color components NOT be used or referred to or categorized with the warning + informational alert components, which need to be made a little more rigid for CMS.

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva Because of the way the background-only alerts were built though, they have to be part of the alerts component; because the background color only part is a modification on that component. It's not a separate thing, and it would not make sense from a front-end perspective to present them as a separate thing.

Though the CMS is what is driving this conversation, a lot of these types of decisions have impacts well beyond that. I'm trying to figure out how to modify the design system and handle related cleanup based on whatever we decide to do, especially for things that are not in the CMS.

**Comment by jaredcunha-usds** [comment]
Based on the design meeting today, we agreed to the following:
1) We will change background-color-only alerts to be used for immediate, non-static feedback
2) We will audit existing usage of the background-color-only alert to determine if we should migrate to another component, make a regular alert, or leave as is. 

With that in mind, I have a pull request on changes to the alert page, which you can see on the "Files Changed" tab on this page:
https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/70

I will not be able to document the banner style alerts just yet. The CSS for those in the `vets-website` repo, not Formation. So if we want that documented, I'm going to need to write a ticket to migrate that CSS. 

Here's a screenshot of what the alert page looks like. There are content changes throughout, but compare the examples of the background-color-only alerts to what is on design.va.gov right now.

![Screenshot_2019-04-29 Alert boxes - VA gov Design System](https://user-images.githubusercontent.com/25435289/56924328-a0651e00-6a9a-11e9-8ad5-f27f025f3e26.png)

**Comment by caw310** [comment]
Closing this as alerts has been updated since this ticket was created.
