### ISSUE TITLE
526 v2: Draw attention to 20+ character address line

### ISSUE THREAD

**Issue by ndsprinkle** [department-of-veterans-affairs/va.gov-team#5225]
## User Story
Original ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/1046
As a front end engineer on the Benefits and Memorials team, I need to draw attention to imported address lines in the 526 form that exceed 20 characters to diminish veteran confusion when they click "Continue" and the fields have validation errors.

## Tasks
- [ ] Identify the ideal way to draw attention to the address lines with more than 20 characters (probably validation)
- [ ] Implement the method when the address is pulled in from vet360

## Acceptance Criteria:
Address lines with more than 20 characters are brought to the attention of users before clicking "Continue".

**Comment by 1Copenut** [comment]
@ndsprinkle Would you mind updating this entry in the [Accessibility Product List](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-product-review-list.md) with your new ticket number? It will help the accessibility specialists maintain an accurate count.

**Comment by ndsprinkle** [comment]
@1Copenut Done!

**Comment by Mottie** [comment]
What if we removed address 3 (make it invisible to the user) and use it as overflow for the address 1 field?

This would change the limit to the combined address1 (20 characters) + address3 (20 characters) to get a 40 character limit on that single line. When we submit the data to EVSS, we split the combine line into address1 and address3 respectively. This should also be backwards compatible, but the user would be presented with the combine address showing whatever they entered into address 3 included in the first line.

**Comment by ndsprinkle** [comment]
@Mottie I sort of talk about that solution in the original ticket: #1046 

Basically, I met with Silvio and Cameron and they felt that it could introduce some issues. You could ping them about it if you wanted to debate the best solution, but basically it was just going to get tricky handling addresses that were already 2 or 3 lines, so we felt just letting the user manually fix the address would be better.

**Comment by Mottie** [comment]
Yeah I read about the other considerations, but it was after I added my idea above. I wonder what it would take to get EVSS to increase that limitation?

**Comment by Mottie** [comment]
So, we're going the route of alerting the user when they exceed 20 characters:

- The form system is not set up to dynamically show messages while the user is typing; but only initially. Once an input is blurred, any associated error message will show up and _then_ dynamically update. Changing this behavior would require approval from VSP; which may be difficult to obtain since it would effect _all_ forms.
  - When a maximum length of characters is set on an input, it prevents the user from entering more than that maximum. There is no indication (except visual) that the typing is not being applied to the input.
  - When adding a maximum character validation, an error message can be shown, but it will always show, even when the maximum has not been exceeded. We would need to remove the input attribute limitation ([`maxlength`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength)) to prevent any confusion (i.e. still limit the characters, but not within the input itself)
    ![Screen Shot 2020-02-13 at 3 24 03 PM](https://user-images.githubusercontent.com/136959/74485935-7d68f680-4e81-11ea-9400-b284dba79d95.png)
  - The error message only shows up _after_ the input is blurred.
- The design system isn't set up to show warnings. Only [error messages](https://design.va.gov/patterns/form-feedback).
- An alternative would be to show a warning alert once the maximum is reached (or exceeded, if the input `maxlength` attribute limitation is removed). This isn't as visually appealing to me.
    ![Screen Shot 2020-02-13 at 2 48 03 PM](https://user-images.githubusercontent.com/136959/74486251-29aadd00-4e82-11ea-864c-880e659b6259.png)

We will need to have further discussions with the design, accessibility and content teams to determine the best method to solve this issue.

**Comment by sshein** [comment]
👋 hi there - can we just limit the field to only allow 20 characters? and put hint text that says only 20 characters are allowed per address field? cc @kevinstachura

**Comment by 1Copenut** [comment]
I agree with the comment above about limiting to 20 characters, but adding that as hint text. Something like this puts us in better standing for [WCAG SC 3.2: Labels and Instructions](https://www.w3.org/TR/UNDERSTANDING-WCAG20/minimize-error-cues.html). In cases where there are specific boundaries like this, we can call that out proactively, rather than trigger an error message after the fact.

I distinguish this from other cases like an email address field, because there's a general level of understanding how an email address is formatted -- how it should "look". The situation of allowing only 20 characters for a street address is not general knowledge. Help text smooths out that experience bump.

**Comment by sshein** [comment]
maybe something like this. But check with Kevin/Christian for finalizing
<img width="522" alt="Screen Shot 2020-02-19 at 10 30 41 AM" src="https://user-images.githubusercontent.com/3856611/74863553-ef6a9100-5302-11ea-836c-5d18c690127a.png">

**Comment by sshein** [comment]
also is this an issue for all other address boxes on VA.gov or just this one? If it is, Kevin/Christian should bring this up in a Monday VA.gov-wide design meeting.

**Comment by kevinstachura** [comment]
I agree with @sshein on this direction. Since we are unable to surface the error while user is still focused, that makes for a clunky user experience to leave focus just to have to refocus and fix said error. I think surfacing to the user that the limit is 20 characters via a hint and therefore limiting is probably the best proactive method given the technical constraints.

A tangentially related question: Are 'hints' something that we have available to us as a standard component option? Or is any hint element considered on a case-by-case basis? Just something I was thinking about re:standardization.

**Comment by sshein** [comment]
great question @kevinstachura  can you ask in the #design channel?
