### ISSUE TITLE
Audit & inventory level 4+ child pages in benefit hubs

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#5236]
## Audit & inventory level 4+ child pages in benefit hubs

This work is related to the Pittsburgh side-nav usability test and corresponding 2020 effort to apply learnings to the benefit hubs to flatten the IA and simplify the nav menu. 

**Goal:**
Reduce level 4+ content down to max of 4 levels

**Repo:** 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/header-footer-and-navigation/page-nav

**Pittsburgh side nav research findings:**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/left-nav/research-findings.md

AC - Level 4 and 4+ child pages have been identified and inventoried for each benefit hub:
[ ] Health care
[ ] Disability
[ ] Education
[ ] Pension
[ ] Careers
[ ] Burials
[ ] Records
[ ] Housing
[ ] Life insurance

Acceptance Criteria for each hub: 
- A shared google spreadsheet spun up to track the audit
- Audit doc includes Notes column with summary about each page
- Audit doc includes Recommendation column with proposal about each page (i.e., Make it a level 3 page or combine the content with another page; 
- Audit doc includes Long-term column with recommendation whether it should be moved from Get or Manage spoke and into More resources; or pull it out of benefit hub altogether and move it to new learning center. 
- Audit doc includes page name, url, and level for every page that is beyond the threshold for the nav. 

**Example screenshots of levels 1-4 nav links :**
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/page-nav/Levels-1-4-hub-nav-012820.pdf

**Comment by jenniferlee-dsva** [comment]
@mnorthuis  would love your input on ^. would like to assign content team to start identifying these level 4+ hub pages, but want to make sure this work will capture what you will find useful as ultimate IA user of this info (and to leverage any existing documentation you might already have as part of your work previously with Danielle).

**Comment by mnorthuis** [comment]
@jenniferlee-dsva The site maps can be used to help with this task, the levels are clearly marked.  Use the page navigation on the left to view the different hubs/areas. We also need to make sure we match in what we call "level 4".  

https://app.moqups.com/Rnc4BDEKrA/view/page/abd763ecc

Ultimately I need a list of every page that is beyond the threshold for the nav - page name and URL.   Once the pages are identified, we will need to review content and IA to determine if page should be moved, merged, retired, or reconstructed in a different way to meet the new requirement.

**Comment by MickinSahni** [comment]
Jen and Mickin to groom/assign to subsequent sprints (likely sprint 15). 
@jenniferlee-dsva @MickinSahni

**Comment by ncksllvn** [comment]
I wrote a super quick script for grabbing this information during the website build. I haven't verified the output fully but it looks okay. The description was pulled from the metatag.
| Path | Description |
| ---- | ---- |
| education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program/apply-for-vettec-form-22-0994/index.html | Vet Tec. |
| education/apply-for-education-benefits/application/1990/index.html | Use your VA education benefits to pay for college or training programs. Find out which documents you’ll need to apply for benefits, and start your online application today. |
| education/apply-for-education-benefits/application/1990E/index.html | Use your VA education benefits to pay for college or training programs. Find out which documents you’ll need to apply for benefits, and start your online application today. |
| education/apply-for-education-benefits/application/1990N/index.html | Use your VA education benefits to pay for college or training programs. Find out which documents you’ll need to apply for benefits, and start your online application today. |
| education/apply-for-education-benefits/application/1995/index.html | Use your VA education benefits to pay for college or training programs. Find out which documents you’ll need to apply for benefits, and start your online application today. |
| education/apply-for-education-benefits/application/5490/index.html | Use your VA education benefits to pay for college or training programs. Find out which documents you’ll need to apply for benefits, and start your online application today. |
| education/apply-for-education-benefits/application/5495/index.html | Use your VA education benefits to pay for college or training programs. Find out which documents you’ll need to apply for benefits, and start your online application today. |
| education/gi-bill/post-9-11/ch-33-benefit/index.html | undefined |
| /health-care/health-needs-conditions/health-issues-related-to-service-era/operation-enduring-freedom | If you're a Veteran of Operation Enduring Freedom (OEF) in Afghanistan, learn about health issues that may be related to your service. Find out what steps to take to care for your health and whether you may be eligible for VA health care and disability compensation. |
| /health-care/health-needs-conditions/health-issues-related-to-service-era/iraq-war | Learn about Iraq War Veterans health issues related to service in Operation Iraqi Freedom and Operation New Dawn (OIF/OND). Find out what steps to take to care for your health and whether you may be eligible for VA health care and disability compensation. |
| /health-care/health-needs-conditions/health-issues-related-to-service-era/gulf-war | Learn about Gulf War Veterans illnesses and other health problems related to service in Operation Desert Shield and Desert Storm. Find out what steps to take to care for your health and whether you may be eligible for VA health care and disability compensation. |
| /health-care/health-needs-conditions/health-issues-related-to-service-era/cold-war | Learn about health issues that may affect Cold War Veterans. Find out what steps to take to care for your health and whether you may be eligible for VA health care and disability compensation. |
| /health-care/health-needs-conditions/health-issues-related-to-service-era/vietnam-war | Learn about diseases and other health issues that may affect Vietnam War Veterans. Find out what steps to take to care for your health and whether you may be eligible for VA health care and disability compensation. |
| /health-care/health-needs-conditions/health-issues-related-to-service-era/korean-war | Learn about diseases and other health issues that may affect Korean War Veterans. Find out what steps to take to care for your health and whether you may be eligible for VA health care and disability compensation. |
| /health-care/health-needs-conditions/health-issues-related-to-service-era/world-war-ii | Learn about diseases and other health issues that may affect World War 2 Veterans. Find out what steps to take to care for your health and whether you may be eligible for VA health care and disability compensation. |
| /health-care/health-needs-conditions/mental-health/ptsd | VA is the world leader in PTSD treatment, serving millions of Veterans. Find out how to get help to manage your posttraumatic stress disorder symptoms. Whether you just returned from a deployment or have been home for 40 years, it’s never too late. |
| /health-care/health-needs-conditions/mental-health/depression | If you're a Veteran living with depression, find out how to get help through VA. You may be able to get access to health services as well as VA disability compensation. |
| /careers-employment/vocational-rehabilitation/programs/reemployment | As a Veteran, you’re protected under the Uniformed Services Employment and Reemployment Rights Act (USERRA). This means you can’t be disadvantaged in your civilian career because of your service. |
| /careers-employment/vocational-rehabilitation/programs/rapid-access-to-employment | If you want to follow an employment path that uses your existing skill set, the Vocational Rehabilitation and Employment (VR&E) Rapid Access to Employment track can help you with your job search. |
| /careers-employment/vocational-rehabilitation/programs/long-term-services | If you have a service-connected disability that makes it hard for you to succeed in your employment path, you may be interested in the Vocational Rehabilitation and Employment (VR&E) Employment through Long-Term Services track. |
| /health-care/about-va-health-benefits/dental-care/dental-insurance | The VA Dental Insurance Program (VADIP) offers discounted private dental insurance for Veterans and family members who meet certain requirements. Find out if you're eligible and how to enroll in a plan that meets your needs. |
| /careers-employment/vocational-rehabilitation/programs/self-employment | undefined |
| /pittsburgh-health-care/jobs-careers/internships-fellowships/forms | Find the forms for researchers at VA Pittsburgh, categorized by type of research. |
| /pittsburgh-health-care/jobs-careers/internships-fellowships/trainee-coordinators | Questions about your internship, fellowship, or training program? Contact the trainee coordinator for your program. |
| /health-care/health-needs-conditions/mental-health/suicide-prevention | Find out how to access Veteran suicide prevention support from VA, including our 24/7 Veterans Crisis Line. If you’re a Veteran in a mental health crisis and you’re thinking about hurting yourself—or you know a Veteran who’s considering this—act now. You’re not alone, and you can get help. |
| /education/about-gi-bill-benefits/montgomery-active-duty/buy-up | Find out how you can get more money for monthly GI Bill payments through the $600 Montgomery GI Bill Buy-Up program. |
| /education/about-gi-bill-benefits/how-to-use-benefits/work-study | Find out how our Veterans work-study program can help you earn money while you're enrolled in a college, vocational, or professional training program. You'll earn an hourly minimum wage for working at a nearby VA facility or in a VA-related role at your school. |
| /education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs | Find out if you can use GI Bill benefits for college as a Veteran, service member, or qualified dependent. Learn about payment rates for undergraduate and graduate degree courses at institutions of higher learning. |
| /education/about-gi-bill-benefits/how-to-use-benefits/tutor-assistance | Learn how you may be able to get money to help pay a tutor if you're a Veteran enrolled at least half-time in an educational program and having trouble with a difficult class required for your degree. |
| /education/about-gi-bill-benefits/how-to-use-benefits/entrepreneurship-training | Veteran entrepreneurs can get training and coaching through the Small Business Administration. Contact your local VA Small Business Liaison and find out if you qualify under a GI Bill program or other educational assistance program. |
| /education/about-gi-bill-benefits/how-to-use-benefits/flight-training | Learn how VA education benefits might be able to help you pay for flight training to become a pilot. The amount you get depends on which GI Bill version you use. Anyone who qualifies for any of the GI Bill programs can apply unless you're using Survivors' and Dependents' Educational Assistance. |
| /education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning | View current payment rates for online and distance learning courses you can get money for under the Post-9/11 GI Bill. If you're using GI Bill benefits to pay for online or distance learning courses, you can also get a housing allowance based on 50% of the national average. |
| /education/about-gi-bill-benefits/how-to-use-benefits/accelerated-payments | Learn about accelerated payments for technology industry training like coding bootcamps. If you're eligible for the Montgomery GI Bill Active Duty (MGIB-AD) program, you may qualify for accelerated payments of up to 60% for high-cost program tuition and fees. |
| /education/about-gi-bill-benefits/how-to-use-benefits/co-op-training | Learn about college co-op programs that might be able to help you get full-time work experience in between periods of going to school full-time. Co-op programs may also be able to help cover costs for books, tuition, and housing. The amount you get depends on what type of GI Bill benefits you use. |
| /education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up | Find out if the Tuition Assistance Top-Up program can help you pay for tuition that's more than what's covered by Tuition Assistance (TA). Check current rates and apply if you're a Veteran covered by the Montgomery GI Bill Active Duty or Post-9/11 GI Bill. |
| /disability/how-to-file-claim/evidence-needed/standard-claims | When you file a standard disability claim, VA can take more of the burden for gathering your supporting documents and needed evidence. Find out how to submit a VA standard disability claim. |
| /disability/how-to-file-claim/evidence-needed/fully-developed-claims | File a fully developed claim to get a faster decision on your VA disability compensation claim. With the Fully Developed Claims program, you submit all the evidence (supporting documents) you have—or can easily get—along with your claim, and go to any required medical exams. |
| /disability/eligibility/special-claims/temporary-rating-prestabilization | Find out if you can get temporary VA disability benefits if you recently ended your active military service and you have a service-connected disability. If you qualify, you'll get what's called a prestabilization rating. This rating will continue for one year after your discharge. |
| /disability/eligibility/special-claims/temporary-increase-for-time-in-hospital | If you spent time in a VA or VA-approved hospital for a disability related to your military service, find out if you can get added disability pay. You may be able to get a temporary 100% disability rating for the time you spent in the hospital. |
| /disability/eligibility/special-claims/temporary-increase-after-surgery-or-cast | You may be able to get a temporary disability rating and increased VA disability compensation after surgery for a service-connected disability or after getting a cast that's left you unable to move. Learn more. |
| /disability/eligibility/hazardous-materials-exposure/gulf-war-illness-afghanistan | If you served in Afghanistan during the Gulf War and have illnesses related to your service, you may qualify for VA disability compensation. Learn more about Gulf War Illness and how to file a claim. |
| /disability/eligibility/hazardous-materials-exposure/gulf-war-illness-southwest-asia | You may qualify for VA disability compensation if you have an illness linked to Gulf War service—often called Gulf War Syndrome—in Southwest Asia, including Iraq, Kuwait, Saudi Arabia. Learn more. |
| /disability/eligibility/hazardous-materials-exposure/mustard-gas-lewisite | Find out if you can get VA disability benefits for illnesses related to mustard gas or lewisite exposure. You may have had contact with mustard gas or lewisite if you served in certain areas during World War II or participated in biological and chemical testing. |
| /disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas | Learn how to file a disability claim while you're stationed overseas through the Benefits Delivery at Discharge (BDD) program. |
| /disability/how-to-file-claim/when-to-file/pre-discharge-claim | If you're on active duty and believe you have a service-connected disability, find out how to file a pre-discharge claim for VA disability benefits. You can file through the Benefits Delivery at Discharge (BDD) program 80 to 90 days before discharge. This may help you get your benefits sooner. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange/thailand-military-bases | If you served on a U.S. military base in Thailand or a Royal Thai Air Force Base during the Vietnam War, you may have had contact with Agent Orange. Find out if you're eligible for VA disability pay and other benefits for illnesses related to contact with this herbicide. |
| /disability/eligibility/hazardous-materials-exposure/asbestos | Find out if you can get VA disability pay for illnesses related to asbestos exposure. You may have had contact with asbestos if you served in Iraq or other countries in the Middle East and Southeast Asia, or if you worked in certain jobs or settings, like shipyards, construction, or vehicle repair. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange/c-123-aircraft | If you flew on, or worked with, C-123 aircraft in Vietnam or other locations, you may have had contact with Agent Orange. Find out if you're eligible for VA disability pay and other benefits for illnesses related to contact with this herbicide. |
| /disability/eligibility/special-claims/1151-claims-title-38 | Find out if you can get compensation from VA for a Title 38 U.S.C. 1151 claim. You may have a claim if you suffered an added disability—or your existing injury or disease got worse—while you were getting VA medical care or taking part in a VA program designed to help you find, get, or keep a job. |
| /disability/eligibility/special-claims/unemployability | Find out how to file for VA Individual Unemployability compensation if you're an unemployed Veteran who can't work due to a service-connected disability. With this benefit, you may be able to get disability compensation or benefits at the same level as a Veteran who has a 100% disability rating. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange/registry-health-exam | Find out how to request an Agent Orange Registry health exam if you think you had contact with this herbicide during military service. The exam can help alert you to illnesses that may be related to contact with herbicides and help us learn more to better serve Veterans with these illnesses. |
| /disability/eligibility/special-claims/automobile-allowance-adaptive-equipment | Find out if you can get a VA automobile allowance if you're a Veteran living with a service-connected disability that prevents you from driving. Our automotive adaptive-equipment grants can help you buy or update a vehicle with special features that enable you to drive. Learn how to file a claim. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange/related-diseases | Learn about certain cancers and other diseases we believe are related to Agent Orange exposure (called "presumptive diseases"). If you have an illness or other condition and were exposed to Agent Orange, find out if you're eligible for VA disability pay and health care benefits. |
| /disability/eligibility/hazardous-materials-exposure/ionizing-radiation | Find out if you can get VA disability pay and health care for illnesses linked to ionizing radiation exposure during military service. Illnesses include some cancers. You may have had contact with ionizing radiation if you served in certain roles or locations or were part of nuclear weapons testing. |
| /disability/eligibility/special-claims/clothing-allowance | Find out if you can get a VA clothing allowance to replace clothing damaged by your prosthetic or orthopedic device or by certain medicines. To get a yearly payment, you'll need to qualify by August 1 of each year. Learn more about rates and how to file a claim. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange/testing-storage-areas | If you were part of testing or storing Agent Orange on military bases in the U.S. or elsewhere, you may have been exposed to this herbicide. Find out if you're eligible for VA disability pay and other benefits for illnesses related to contact with Agent Orange. |
| /disability/eligibility/hazardous-materials-exposure/project-112-shad | If you were part of Project 112 or Project SHAD, you may be at risk for certain illnesses. Find out if you can get VA disability pay and other benefits. You can also learn more about certain test sites, ships, and units involved in this chemical and biological warfare testing from 1962 to 1974. |
| /disability/eligibility/special-claims/dental-care | Find out if you can get VA dental benefits for disabled Veterans. If you have a service-connected disability or meet other qualifications, you may be able to get some or all of your dental care through VA. |
| /disability/eligibility/hazardous-materials-exposure/specific-environmental-hazards | Learn about VA disability compensation for illnesses related to environmental hazards. Find out which hazards you may have come in contact with during military service, and how to file a claim for compensation. |
| /education/about-gi-bill-benefits/how-to-use-benefits/correspondence-training | Find out how you can use your Post-9/11 Bill benefits to pay for up to half the cost of correspondence training classes at an in-state school. You may consider completing correspondence courses by mail if you live far from a school or want to take classes from home. |
| /education/about-gi-bill-benefits/how-to-use-benefits/non-college-degree-programs | Learn about ways to use the GI Bill to pay for professional training and trade skills like HVAC repair, truck driving, or Emergency Medical Technician (EMT). Qualified Veterans, service members, and dependents may be able to get money for tuition, books, and supplies. |
| /education/about-gi-bill-benefits/how-to-use-benefits/test-fees | Find out how you can get reimbursed for registration fees, admissions tests like the GRE, GMAT, or LSAT, and specialized tests if your job requires a license or certification. Learn what forms you'll need to submit when applying for this benefit. |
| /housing-assistance/home-loans/loan-types/purchase-loan | Find out if you meet the requirements to apply for a VA-backed purchase loan Certificate of Eligibility. These loans can help you buy, build, or improve a home by offering benefits like better terms and interest rates and lower closing costs. |
| /housing-assistance/home-loans/loan-types/native-american-direct-loan | Find out if you're eligible for a Native American Direct Loan (NADL) to help buy, build, or improve a home on Federal Trust Land. You may also be able to lower your interest rate and refinance a loan you already have. |
| /housing-assistance/home-loans/loan-types/cash-out-loan | A VA-backed cash-out refinance loan lets you replace your current loan with a new one under different terms. Find out if you're eligible—and how to apply for your Certificate of Eligibility. |
| /housing-assistance/home-loans/loan-types/interest-rate-reduction-loan | An interest rate reduction refinance loan (IRRRL) to refinance an existing VA-backed loan and reduce monthly mortgage payments. Find out if you're eligible—and how to apply. |
| /education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program | Learn how the Yellow Ribbon Program can help you pay for tuition not covered by the Post-9/11 GI Bill if you're a qualified Veteran or eligible dependent of a Veteran. Find out if your school participates in the program. |
| /pittsburgh-health-care/research/safety-security/human-research | Learn more about VA Pittsburgh Healthcare System's commitment to providing a safe, secure environment for human research subjects. |
| /pittsburgh-health-care/research/safety-security/animal-research | Find out how to prepare your research safety review submission to meet our special requirements for working with animal subjects. |
| /pittsburgh-health-care/research/safety-security/radiation | Find information about working safely with radioactive materials or sources of ionizing radiation, as well as required forms. |
| /education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program | You can gain computer experience to start or advance your career in the high-technology industry our new Veteran Employment Through Technology Education Courses (VET TEC) program. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange/navy-coast-guard-ships-vietnam | If you served on a Navy or Coast Guard ship in or around Vietnam during the Vietnam Era, you may have been exposed to Agent Orange. Find out if you're eligible for VA disability pay and other benefits for illnesses related to contact with this herbicide. |
| /disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination | Find out if you can get VA disability pay and other benefits for illnesses related to Camp Lejeune water contamination. Learn how to file Camp Lejeune water contamination claims for Veterans or family members. |
| /disability/eligibility/special-claims/birth-defects | If you served in Vietnam, Korea, or Thailand—and your child has spina bifida or certain other birth defects related to Agent Orange exposure—your child may qualify for VA disability compensation and benefits. Learn more. |
| /education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools | VA education benefits can help Veterans and qualified dependents pay for tuition and housing fees while studying at a foreign school for a standard college degree or equivalent degree. See what schools are approved and how you can apply. |
| /education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships | Learn how GI Bill training programs can help you work in an industry like plumbing, firefighting, or hotel management that requires on-the-job training. If your program is approved by VA and you qualify for Post-9/11 GI Bill benefits, you could get money for books, supplies, and housing. |
| /careers-employment/vocational-rehabilitation/programs/independent-living | If your service-connected disability limits your ability to perform activities of daily living (like bathing, dressing, accessing the community, and interacting with others) and you can’t return to work right away, you may qualify for independent living services through the VR&E Independent Living track. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange | If you served in Vietnam—or in or near the Korean DMZ during the Vietnam Era—or in certain related jobs, you may have had contact with Agent Orange and may qualify for disability compensation and other VA benefits. |
| /disability/eligibility/hazardous-materials-exposure/agent-orange/service-in-vietnam-korea | If you served in Vietnam or in the Korean DMZ during the Vietnam Era, you may have had contact with Agent Orange. Find out if you're eligible for VA disability pay and other benefits for illnesses related to contact with this herbicide. |
| /pittsburgh-health-care/events/past-events/page-2 | undefined |
| /health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services | Learn about VA benefits for Veterans who are blind or have low vision. Benefits include blind rehabilitation services at VA blind rehab centers. |
| housing-assistance/home-loans/loan-types/native-american-direct-loan/tribes-with-memorandums-of-understanding/index.html | undefined |

**Comment by jenniferlee-dsva** [comment]
@ncksllvn (for when you return from vacation): couple Qs... 

- is the ^ script result showing the meta description? - if so, that's cool! and could def stand in for initial page summary. (would still want content person to verify against page, in case meta is older than when page last updated. but a great start!)
- can your script pull the complete list of URLs for all hubs? if so, we could start with that as our inventory to check against.

FYSA @MickinSahni @AnneHurley @lunascoop @RLHecht @mnorthuis @lwalsh617

**Comment by jenniferlee-dsva** [comment]
Hey - this audit looks complete now. Is that right? @lunascoop Where is the consolidated spreadsheet we can start looking at together? If you can upload it or link to it from within the product repo, that would be great: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/global/header-footer-and-navigation/page-nav

If complete, we can start creating tickets to review these and solidify proposal for each L4+ page; then implementation tickets to flatten them in the nav (bring them up a level or consolidate them with other pages). 

@DanielleThierryUSDSVA - sorry I can't add you via the assignees feature.

**Comment by lunascoop** [comment]
Hi @jenniferlee-dsva yes, it's complete. Here's a link to the Google spreadsheet and the excel file in GtiHub repo.
https://docs.google.com/spreadsheets/d/14pVRlnkCGL0tuE-qFDvoANM5__Qv01sw_YgWN-k8zng/edit#gid=1606594589
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/global/header-footer-and-navigation/page-nav/Level%204%2B%20Pages%20Audit.xlsx

**Comment by MickinSahni** [comment]
consider turning this into a super-epic with constituent epics e.g. for agent orange work cc @DanielleThierryUSDSVA

**Comment by DanielleThierryUSDSVA** [comment]
@bethpottsVADEPO I added this to our Benefit hub refresh super epic, as this is really part of that larger initiative now rather than a separate goal specific to flattening IA. 

cc @mpeterz @mnorthuis @johnhashva

**Comment by mnorthuis** [comment]
Audit and inventory for this work is outdated.  Any content restructuring or left nav work will be handled separately from this epic.
