### ISSUE TITLE
Determine new H2 to add to benefit hub landing pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#52386]
## Issue Description

PW opened an intake request for an accessibility issue on our benefit hub landing pages. In order to fix a header hierarchy issue, we need to add an H2 above the promo box for each hub that will serve as a header for the right rail. 

Original ticket for more info: [52342](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12169)

## Tasks
- [x] Determine H2
- [x] Post final content for PW in original intake ticket

## Acceptance Criteria
- [x] PW has content for each hub landing page

**Comment by laurwill** [comment]
Hi @RLHecht , I'm adding some thoughts here — I'd like to run this by Beth & Danielle in today's sync before we suggest anything to PW, since it will affect all the benefit hub pages.

Concerns with adding a single H2 to the right rail:
- An H2 in the right column so close to the H1 seems like it may be visually confusing
- The promo box isn't really related to the contact and social info, so this H2 will be a forced grouping to fix the 508 issue. It would be an odd pairing like "Featured resource and contact info."

Alternative idea: 
- Add a new H2 for the promo box like "Featured resource." Then make the promo link a normal text link instead of an H4 — we've been moving away from linking headers for accessibility reasons, so we might as well fix these now too. (This would take a bit of content time to rephrase these.)
- Make "Ask questions" and "Connect with us" H2s and move the content out of accordions — these are expanded by default, so I'm not sure why they're in accordion components. 

So using the disability hub example, the right rail would go like this:

### [H2] Featured resource
Use our Fully Developed Claims program to get a faster decision by submitting evidence with your claim.

Learn more about Fully Developed Claims

### [H2] Ask questions
[H3] Message us
[H3] Call us

### [H2] Connect with us
[H3] Get updates
[H3] Follow us

**Comment by RLHecht** [comment]
Laura posted this content in PW ticket, so I think this is good to close out.
