### ISSUE TITLE
DEV BRD Deprecation: Vets-API deploy when vets-api mockdata has change

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#52436]
http://jenkins.vfs.va.gov/job/testing/job/vets-api-mockdata/job/master/

Take notes on how we might create a github action to build this out for EKS.

**Comment by laineymajor** [comment]
@rmtolmach to verify this is complete.

**Comment by LindseySaari** [comment]
[Changes started here](https://github.com/department-of-veterans-affairs/vets-api-mockdata/blob/master/.github/workflows/build_and_deploy.yml), but I need [a person with devops perms to add the secrets to the mockdata repo.](https://oddball.slack.com/archives/C045LCF8WU8/p1675869288902489)

**Comment by LindseySaari** [comment]
A change has been [implemented here](https://github.com/department-of-veterans-affairs/vets-api-mockdata/pull/248). This is the only ideal way to do this currently because repository_dispatch GHA listen events can only be implemented on the master branch. We will want to note updating these actions as an item after all envs have been released and the k8s branch has been merged into master.

**Comment by LindseySaari** [comment]
This is complete and I [created a ticket](https://app.zenhub.com/workspaces/platform-tech-team-1-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53406) in the backlog to implement changes for the repository_dispatch solution after the vets-api k8s branch is merged to master
