### ISSUE TITLE
Link that directs to a 404 page

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#52472]
### Description

The "quality assurance artifacts" link is directing to a 404 page. That link directs to https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-artifacts. 

<img width="668" alt="Screen Shot 2023-01-24 at 11 16 02 AM" src="https://user-images.githubusercontent.com/101129355/214347588-5d98d512-5056-4ce8-81df-5b0c250ce113.png">

### Relevant URLs

https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-Howstandardsarevalidated

**Comment by laucon** [comment]
I see. It looks like the original [Quality assurance artifacts document](https://vfs.atlassian.net/wiki/spaces/pilot/pages/1906999390/Quality+assurance+artifacts), which is why the link is now broken. Bear with me while I search for the SME who is in charge of the [QA Standards doc](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards#QAstandards-Howstandardsarevalidated). Once I do that, I can work on fixing this. Thank you so much for pointing out the issue.

**Comment by laucon** [comment]
I fixed this so there's no longer a broken link. However, cecause the brand new link is a bit awkward looking, we're going to create a new document and then link to that in the near future. But until we are able to do that, we were able to replace the broken link with a working link. So that solves the problem for now. :)

**Comment by vbellissimo** [comment]
Related to: #49998
