### ISSUE TITLE
[Analytics Request] Personalization Tools Request

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#528]
## User Story
As a VA Product Decision maker, I need to know what the monthly Foresee metrics and personalization metrics mean so I can use them in my workflow in a meaningful way.

## Goal
- Walk through Foresee metrics with Lisa and answer any metrics questions. Provide personalization metrics.
- Request came via Slack from Lisa to (a) provide metrics to research metrics https://github.com/department-of-veterans-affairs/vets.gov-team/blob/master/Products/Identity/Personalization/Discovery/Personalization%202.0/Analytics/Analytics.md and (b) coordinate a meeting to review the metrics I presented from an older dashboard on Data Studio

## Acceptance Criteria
- [x] Met with Personalization decision maker
- [x] Answered any open metrics questions
- [x] Provide Personalization metrics
- [x] Shared results of meeting with team

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

**Comment by joanneesteban** [comment]
Met with Lisa on the Personalization product team on 7/11/19. 

Presented Foresee data that is captured on the vets/va.gov metrics Google Sheet. Walked through the sheet.

LIsa presented questions on Foresee that are relevant to many of our discussions on using Foresee data for product improvement and to add to the product health MVP. Those questions among others are listed on https://github.com/department-of-veterans-affairs/va.gov-team/issues/563. We will be performing a discovery around Foresee background and metrics with the assumption that we can request survey adjustment based on product health needs.

**Comment by joanneesteban** [comment]
Metrics Requested: HCA and Personalization

**Comment by joanneesteban** [comment]
@nedierecel can you add the specific metrics requested? It sounds like they're using this data to start setting baselines for KPIs, which we want to capture as we move forward with the Product Health Tool and streamlining KPIs across teams.

**Comment by nedierecel** [comment]
@joanneesteban Certainly - I updated the Goal criteria with a link to the outline and will organize the KPIs from Lisa's requests.

**Comment by nedierecel** [comment]
@joanneesteban I met with Lisa on 7/18 to review the data points on an older Personalization Tools dashboard I provided via (Data Studio)[https://datastudio.google.com/u/0/reporting/1MEhg3-5vnPBsSc_1wCzh6LByR3RjH92q/page/GELI?s=vS-iovB_OEo].

Requests that will span into Sprint 5:
- Add metrics for LOA level
- Provide an option to filter geography that will exclude VA facilities
- Identify if we can combine several `Next Pages` results that are repetitive and only missing a trailing slash
- Profile Page - Look at the entire user flow from (a) user clicking on update to (b) form submission
- Profile Page - Check if we are capturing errors
- Make date ranges consistent across tabs

CC: @amycesal Input welcome if we should continue serving via Data Studio or use GSheets for more granular, non-Product Health MVP data. Since it's more exploratory than serving as a product health MVP, I like its flexibility in pulling in the GA data.
