### ISSUE TITLE
[POC] Content update for Appointment List Redesign (Mobile/Web/Tablet) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#52817]
## Description
We have started to develop the proof of concept for the Appointment List redesign and looking to make some content updates. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

Update the following: 
- [x] Sentence case for all labels
- [x] No hyphen for "In person" when alone (as label)
- [x] Use hyphen for "In-person" when in sentence form.
- [x] Add "." to a.m. and p.m.
- [x] Remove S from timezones (ie: PT, ET, MT)
- [x] Remove modality icon from Community care.
- [x] Add "At" before facility location. (ie: At Portland VA Medical Center.

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ldelacosta** [comment]
@vbahinwillit - please size the work when you start working on the ticket. Thanks!

**Comment by ldelacosta** [comment]
@Cieramaddox @outerpress - this ticket is ready to be validated in staging. Thanks

**Comment by outerpress** [comment]
@ldelacosta some of the data in the list isn't showing, (not sure if this would be a different ticket):

- If appointment has a type of care, that should show instead of `VA appointment`
- If appointment has a provider, that should show as `[VA appointment/Community care] with [Provider name]`
- If appointment has both, both should be listed in the form `[Type of care] with [Provider]`

Looking at the [design file](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=1194%3A66663&t=nlcormL1oZ7WI5f8-4), we have all but the first case covered, so I'll add that.

**Comment by outerpress** [comment]
@ldelacosta @JRRoof could you enable this feature on a user with Community Care appointments?

**Comment by outerpress** [comment]
@ldelacosta this is a new issue with this change. When tabbing through using voiceover, the details link isn't reading the contents of the aria label. It's just saying "details." It looks like the aria labels are still in the code, but on a different element than what tab is focusing on.
https://user-images.githubusercontent.com/2536801/220471960-3abb7293-f310-4d5d-8e20-228dc75e92fd.mov

**Comment by outerpress** [comment]
> @ldelacosta @JRRoof could you enable this feature on a user with Community Care appointments?

Confirmed with Patient 999 that the modality icon is not showing for CC appointments 👍

**Comment by ldelacosta** [comment]
Closing out the ticket. We will have new tickets for the next updates/fixes.
