### ISSUE TITLE
Set up notifications/codeowners for `vets-json-schema` (if applicable)

### ISSUE THREAD

**Issue by jholton** [department-of-veterans-affairs/va.gov-team#5283]
Currently the `vets-json-schema` repo has no notifications wired up (e.g. #vsp-backend-onpoint channel) or codeowners configured.

Currently VSP team member approval is not necessary to merge a PR.
Any changes to a schema _should_ be felt in `vets-website` and `vets-api` via tests/specs in those repos.
Is that sufficient as a safety mechanism?

We should discuss with leadership what responsibilities VSP should adopt in regards to the `vets-json-schema` repo.

**Comment by gunsch** [comment]
Short-term (tools-be?)
* Codeowners and PR template update
  * Review is only "make sure the FE/BE have corresponding updates"
* Step-by-step doc for “how to test this against vets-api and vets-website” (collab)
* Circle: automatic comment when version is bumped?

Medium-term (forms team)
* Each schema could be published to separate module, which would reduce this problem
* Forms team should own this repo / problem area

Longer-term, automatic validation idea? (forms team, or otherwise)
* Run vets-website + vets-api tests on vets-json-schema changes

**Comment by gunsch** [comment]
reopening, PR only addressed short-term step 1

**Comment by johnpaulashenfelter** [comment]
Moved future ideas to #9635
