### ISSUE TITLE
Limit in Production to either a Station, Clinic, or Facility

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#52868]
## Tasks
- Implement so that we can configure & limit access at any of these levels
    - Station (already exists this way)
    - Clinic
    - Facility

**Comment by brianseek** [comment]
@loripusey should we de-prioritize this for now?

**Comment by loripusey** [comment]
Do we need to? If we have time, it might be nice to knock this out, but if we have bigger fish to fry there is no rush on this as we need to have the texting portion in place before we test with Wilkes-Barre. Up to you.
cc: @benbrasso-agile6

**Comment by brianseek** [comment]
@loripusey sounds good. When I made my comment things seemed more in limbo too. I'll pick this up

**Comment by brianseek** [comment]
@loripusey we removed the facility part of this because we didn't have a facility ID in the data. We only have user entered facility names which seems to un-reliable to filter on. They way this works is that it looks at station first, if there are no clinics listed within the station, the whole station will have travel pay enabled. If there are clinics listed within the station, then only those clinics in that station will have travel enabled. 

Feel free to close this if that all sounds good.

**Comment by loripusey** [comment]
@benbrasso-agile6 ^^^^^^
closing
