### ISSUE TITLE
Sub sites recently moved from on-prem to Azure not loading consistently

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#53022]
## Issue Description
The WebOps team moved several subsites from on-prem to Azure without alerting anyone on VA.gov. 

They reached out to Ray and Cory the week of 1/30. Cory, Kyle, Clint huddled on 2/2 to brainstorm solutions. 

---
## Tasks
- [ ] Assist WebOps team to get sites to load consistently

## Acceptance Criteria
- [ ] All sites that VA.gov Platform can assist with load successfully

**Comment by andreahewitt-odd** [comment]
Ray Wang
  1:39 PM
[2:37 PM] Weinberg, Michele H.
Cory Trimm
[2:38 PM] Vasireddy, Jayasree (TISTA Science and Technology Corp.)
problematic appid's
https://www.va.gov/vdl/application.asp?appid=100
https://www.va.gov/vdl/application.asp?appid=60
https://www.va.gov/vdl/application.asp?appid=139





1:39
reverse proxy work (edited) 
1:42
www.va.gov/vdl
specificly:
https://www.va.gov/vdl/application.asp?appid=60 https://www.va.gov/vdl/application.asp?appid=100 https://www.va.gov/vdl/application.asp?appid=139
U:\>nslookup www.va.gov Server:vac201dc1va.va.gov Address:10.245.128.165
Name:internal-dsva-vagov-prod-revproxy-1633404613.us-gov-west-1.elb.amazonaws.com Addresses:10.247.33.81 10.247.32.42 10.247.32.165
Then this I believes gets filtered and reverse proxy back to AZURE Cloud Virtual IP
10.245.67.211

**Comment by little-oddball** [comment]
@CoryTrimmUSDS and @ph-One have been spear heading this from a "platform" perspective. They have been working closely to troubleshoot and chase the rabbits. Below is a lot of the information shared w/ me. It adds some detail, etc. into what is being tackled:

Investigation was put into place around the actual request for appid 139.

curl https://www.va.gov/vdl/application.asp?appid=139 --v

When I ran this, you can see a bit more details on the HTTP protocol (which was throwing that 200 error as detailed above).
Here is the top of the verbose output on the failure -

*   Trying 10.247.33.81:443...
* Connected to www.va.gov (10.247.33.81) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
> GET /vdl/application.asp?appid=139 HTTP/1.1
> Host: www.va.gov
> User-Agent: curl/7.83.1
> Accept: */*
>
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Thu, 02 Feb 2023 23:26:34 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Cache-Control: No-cache
< Set-Cookie: ASPSESSIONIDQSADTCCT=MECFNFPBMKOGDGCCBHKNGOBB; path=/
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
<
The HTML starts to come back but then freezes within the application body. If you let it sit, in order to timeout, you get this -
* schannel: server indicated shutdown in a prior call
* transfer closed with outstanding read data remaining
* Closing connection 0
* schannel: shutting down SSL/TLS connection with www.va.gov port 443
curl: (18) transfer closed with outstanding read data remaining

When successfully run a verbose curl request of that VDF appid of 139. Also looks to be some dynamic update of links and a failure potentially in Burial Allowance.

Thoughts: (VA.gov) may have an auto-timeout for requests that are stalled open. Which makes sense as to why it is closing the SSL/TLS connection and would wan to verify.

We are getting the data back from the VDL application and definitely able to access the VDL app 139 with way more success now that the main work day has ended.

Additionally a call was had in the morning 2/3 w/ Kenneth Dally. Additionally went and had more detailed conversation in the #sre channel with [this](https://dsva.slack.com/archives/C0S6H6BQU/p1675435132407379) thread.

**Comment by little-oddball** [comment]
Kyle worked with Cory and met w/ team. Marking this resolved based on my understanding. Note: This was several days of unplanned work.
