### ISSUE TITLE
Establish IA approach for initial translation of benefit hub content

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#53150]
### Problem Statement
We are translating key benefit hub pages and other important content into Spanish and other languages. We need an initial MVP approach to IA for this content in order to quickly launch translated pages.  

### Considerations
- Limited dev and technical changes
- Findable via search
- Accessible (i.e. language is correctly read by screen readers)
- Plan for future growth

We will need to plan for 
- Body content with toggle
- title tags
- breadcrumbs
- left navigation
- search
- documentation

**Comment by mnorthuis** [comment]
Current approach:

- Pages are slotted alongside the English pages
- URLs are in english with a 3 character language code appended to the end of the URL
- Each page has a toggle to switch between languages
- The breadcrumb current page segment updates to the appropriate language on toggle
- The left nav updates the current page and child pages to the appropriate language on toggle
- Title tags are translated
- All pages are included in sitemap.xml
- Pages are linked to/referenced in the language resource page (spanish and tagalog)

**Comment by jennymayoco** [comment]
Hi @SarahKay8! Following up our conversation here. My original question had been "My question was pertaining to screenreaders for the translation ticket I mentioned earlier today. As the site is now, a screenreader will read the left navigation in English even if that component itself has been translated to the toggled language. What are some accessibility considerations to keep in mind so that a screenreader can correctly capture the selected language?"

The non-English languages are Spanish and Tagalog for now. @mnorthuis, SK also asked if
there is a `lang` attribute on the container that holds the non-english content, would you have any insight on this?

**Comment by mnorthuis** [comment]
@SarahKay8 @jennymayoco I have been told that there is a language attribute on our navigation components, but would be a good thing to confirm.  However, that would be an attribute for the entire component, not for individual links within the component.  If this can't be confirmed by testing current site with a screen reader, then you can start by reaching out to the CMS team.

**Comment by SarahKay8** [comment]
Thank you! @mnorthuis

**Comment by SarahKay8** [comment]
Hi @mnorthuis @jennymayoco 

After testing, the content is being read out in spanish and tagalog. However, the instructions are still being read out in english because I have my original VO setting set to English. Users will need to modify language preferences on their SR (depending on which one they are using).  On a Mac, choose Apple menu > System Settings, click General in the sidebar, then click Language & Region on the right. (You may need to scroll down.) Under Preferred Languages, do any of the following: Add a language: Click the Add button , select one or more languages in the list, then click Add.

https://user-images.githubusercontent.com/102324990/219129351-43c5b93e-3c47-4e7e-9af5-e59a1e9d8e57.m
![EF072B6E-A755-4DC4-8AAD-480FF9D30B5B_1_105_c](https://user-images.githubusercontent.com/102324990/219130137-becf758c-7a11-4ee9-91b1-ddf2d7b4ed0f.jpeg)
p4

**Comment by SarahKay8** [comment]
https://user-images.githubusercontent.com/102324990/219131751-469d7466-7481-401b-90bf-3efccfaa650d.mp4

**Comment by mnorthuis** [comment]
Thank you @SarahKay8 for clarifying that the individual links are all tagged with a language. That is helpful to know.

@jennymayoco recapping what we discussed Tuesday now that we've confirmed link level language tagging in the nav component works
- Content team can move forward with current approach
  - Create spanish version of page at same URL as english version + `-esp` at the end of the URL (i.e. www.va.gov/health-care/english-page-name-esp)
  - Breadcrumb current page segment, title tags, and left nav option will all be translated when the visitor toggles to the non-english version
- We can do some discovery work around the general navigation and wayfinding experience to identify any potential issues that increasing the amount of translated content might create given our current solution
  - Our goal is not to solve for a global translation approach, it is just to identify where the current solution may break down
  - Areas to consider: left nav and breadcrumb navigation, search, other?
  - Translation will be focused on the content within the "Get benefits" spoke of each hub
  - Please hold on meeting with CMS or PW teams for now, we can just do our analysis to have a viewpoint
