### ISSUE TITLE
[SPIKE] Determine how we might do a cross product veteran path analysis for Pre-Check-in only

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#53232]
## TIMEBOXED
2 DAYS

## Scope
Pre-Check-in only

## Questions to answer
- What does CHIP log & not log?
- What's the gap between the data we have access to now and what we don't have access to?
- What mechanism could we use to generate the data on a repeated basis?

## Examples of the type of info that would be nice

![image](https://user-images.githubusercontent.com/86678742/217354038-db6de18b-1dbe-449d-824e-4859658ec41f.png)

![image](https://user-images.githubusercontent.com/86678742/217354074-e6f19d3c-5036-4392-8463-d23add51dcf6.png)

**Comment by loripusey** [comment]
@acrollet please add some detail to this ticket

**Comment by acrollet** [comment]
Ok, coming back up for air on this one. I definitely underestimated the degree of difficulty, particularly for pre-checkin. This is because for pre-checkin to do a true path analysis for every interaction we'll need to gather a great deal of data (> 200,000 pre-checkin reminders sent per week) from 3 separate datadog instances and store it for at least a month at a time. (Because reminders go out up to 28 days before appointments) @randomsync and I discussed this for some time today and agreed that probably what's needed is something like the following:

1. Update each system (VEText, CHIP, vets-api) to create specific log messages for this purpose with the LoROTA UUID, timestamp and event details for each touchpoint we care about
2. Run a periodic job to call the datadog log API, ingest these messages and place them in some datastore (RDS? Kinesis? TBD)
3. Run another periodic job to do the actual analysis and output

We could probably skip step 2 if attempting to do day-of check-in only, since all interactions should complete on the same day.

T-shirt size for the whole project is at least a large. I think the next step here is to determine if there's some subset of these data that would be most useful in terms of providing actionable next steps, and see if we could bite off a smaller chunk.

cc @shawn-adams

**Comment by loripusey** [comment]
I agree with your conclusion @acrollet ; attempting to eat the whole elephant might be too overwhelming, perhaps we start with just the trunk or an ear. :)

**Comment by acrollet** [comment]
I had one more thought about all this early this morning - it might make more sense to use a veteran identifier like `ICN` (obscured if necessary) as the key for the datastore, for two reasons:

1. It would give us a better sense of a patient's interactions with the system over time. For example, a patient might try to check-in too early, (which would count as a failed interaction) but then successfully check in during the appointment window.
2. It could potentially fill in the missing link for #44360 - if VSE-CS could query these data by patient via an API, it could then display actionable info to MSAs in the field.

cc @shawn-adams

**Comment by loripusey** [comment]
@acrollet would it be good to set up a meeting with Shawn et. al. to discuss next steps?

**Comment by benbrasso-agile6** [comment]
I wouldn't mind being a part of this discussion

**Comment by acrollet** [comment]
@loripusey I think the next step would be a technical discussion with our team's engineers to discuss feasibility and effort, and then take a MVP proposal to stakeholders.
