### ISSUE TITLE
FE | Profile | Notification Settings | Editing as a Sub-Task | Rollout, Cleanup of edit mobile phone page

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va.gov-team#53549]
## Issue Description

Clean up from the rollout, remove unit tests and toggles and stuffs!

## Acceptance Criteria
- [ ] we've got nothing left over from our rollout

**Comment by BerniXiongA6** [comment]
Note for @Samara-Strauss -- @adamwhitlock1 and I worked on this together to scope the FE work for this ticket; one of the things we discussed is to make note that we should get tickets created for any user research sessions we might want to conduct before this FE work gets started.

**Comment by Samara-Strauss** [comment]
Thanks, all! I don't think we need additional user research sessions for this. Liz has already conducted usability testing on the design, and we can validate the functionality internally once its built. We don't need any more usability testing, and I don't think we need to do UAT for this since any of us can log into production with the feature flipper and test ourselves.

**Comment by adamwhitlock1** [comment]
This is in PR and at most 1 point will roll into the next sprint
