### ISSUE TITLE
[PM] Onsite notifications: Build product backlog for notification center,  new notifications, and component

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#53707]
## Background
Build the backlog for onsite notifications v2 (including component build) and the notification center mvp.

## Tasks
- [x] Map out timeline
- [x] Create tickets
- [x] Link to product outline > project outlines for v2 and notification center (when ready)

**Comment by Samara-Strauss** [comment]
## Existing notifications as of March 2023

[From our initial shared review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/notifications-v2/product/shared-notes-existing-notifications-to-review.md#samaras-assessment), we are interested in adding the following:

- **VEText prescription notification**: Once VEText updates their implementation to pass user information to VANotify, we can add this to onsite notifications. ETA for updates from VEText/VANotify is April 2023.
- **VA insurance: Document ready for review**: This email is actually a good candidate, but has low numbers. We should focus on higher priority notifications first.

The following are candidates based on being action-based notifications, but we can't add right now for the reasons stated below:

- **BVA notifications, specifically Decision mailed, Appeal docketed, Hearing scheduled/postponed/withdrawn**: These would be great candidates, but we should not add these **until** we can confirm what someone might see in the claim & appeal status tool with regards to any of these statuses. If we can confirm that people see useful information, let's add them as onsite notifications.

The following are action-based notifications, but we likely can't add because of technical constraints.

- **VBA Education enrollment email**: This email includes links to confirm whether someone is still enrolled in school or not, which is great. However, we don't have anywhere to send people who receive this as an onsite notification, which would make it useless to show on VA.gov.

## Notifications coming down the pipeline

[Summarizing thoughts based on this Slack thread](https://dsva.slack.com/archives/C909ZG2BB/p1677708649133489).

I am interested in the following:

- **Comp and Pen payment deposit notification**: Whenever this is ready, it would be a great candidate for an onsite notification.
- **Any claims-related notifications**: [According to this comment](https://dsva.slack.com/archives/C909ZG2BB/p1677772210579169?thread_ts=1677708649.133489&cid=C909ZG2BB) and in-person conversations I've had with Bev, there are discussions about building an event streaming API that would allow VANotify to trigger claims-related notifications. Bev mentioned these might be 6 -9 months off, but whenever they are available, this would be top priority. 

Potentially interested pending more information:

- **Quick Submit new letter available to download**: This has to do with the claims process. While it's a different system outside of VA.gov, if there was new information people needed to see with regards to the claims process, we'd want to get them there. I am putting this on the "maybe" list until we fully understand what this notification and can make a final call as to whether we incorporate it as an onsite notification or not.
