### ISSUE TITLE
Consolidate VSP documentation into va.gov-team repo

### ISSUE THREAD

**Issue by minafarzad** [department-of-veterans-affairs/va.gov-team#540]
## User Story
As a team member building with or on VSP, I need to navigate VSP documentation easily so I can build in a self-service and agile manner.

## Goal
The documentation in the repos is organized in a way that is easily navigable.

## Acceptance Criteria
- [ ] All documentation that VSP or VFS teams need to operate exists within the va.gov-team repo
- [ ] Any "old" / legacy pages direct to the new versions in va.gov-team repo
- [ ] Onboarding materials for new teams reference the appropriate locations

**Comment by minafarzad** [comment]
@rtluu before you leave we need all your secrets for moving stuff around and across repos in github without pulling our hair out

**Comment by rtluu** [comment]
Thanks for the ping on this @minafarzad! As you likely know moving files around on Github's website is near impossible. 

So to manage the rearranging of files within the various repos, I've been pulling down the repos locally and reorganizing the folders/files in [Visual Studio Code](https://code.visualstudio.com/) and then using the terminal (git) to push the changes to Github. I strongly recommend this for whoever continues this work moving forward.

In addition, one critical part of this process is doing find and replace for the files that are rearranged within a repo, particularly accounting for the urls that link to instances of each file. As an example if all the Product Management files are moving from the deprecated `Work Practices` folder to the new Product folder inside of `Practice Areas`, you'll need to do a find and replace for the whole repo that looks like this.
- **Find:** /Work%20Practices/Product%20Management/
- **Replace:** /Practice%20Areas/Product/

This will catch all the instances of that snippet across the repo and replace them with the new destination. LMK if you have any additional questions, happy to help!

**Comment by mnorthuis** [comment]
Consolidation Decisions:

We will not be moving md files from vets.gov-team repo into the va.gov-team repo.  Instead we will be copying them over, then placing a note at the top of the old file referencing and linking to the new file.  This will ensure that we 1) do not create a bunch of broken links/missing files and 2) do not leave the vets.gov-team repo stripped apart.

For uploaded files (i.e. pdf, ppt, doc, xls, sketch, etc), these may be able to be moved and have referring pages update their links, or a copy can be created but the old file should be dated and content should be added where possible to refer viewers to the newer file. 

For files in va.gov-vfs-teams,  since this repo is a newer repo and does not need a historical view/point-in-time kept, we can either move the files or copy them.  The entire repo will be archived at conclusion.

**Comment by mnorthuis** [comment]
@rroueche Consolidating from repos outside of va.gov-team will be the final step after all docs already in the repo are organized.  This should be moved to the next sprint.

**Comment by mnorthuis** [comment]
Closing this issue, will open separate issues for moving/copying/consolidating from outside repos.
