### ISSUE TITLE
Feedback on MHV on VA.gov landing page

### ISSUE THREAD

**Issue by rtwell** [department-of-veterans-affairs/va.gov-team#54087]
hey gang 

feedback is as follows:

- [x] 1.  The rules in between the links should be **gray-light #aeb0b5** `$color-gray-light` (PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23464)
- [x] 2. In the gray cards, the space between the links and the rules should be 2 spacing units. Here's a screen grab (the space between the H2s and the first link also need some love): <img width="675" alt="image" src="https://user-images.githubusercontent.com/12564977/221008397-3072e8e8-43ce-4f37-82ba-50acae419a4f.png">
- [x] 3. Chevron icons should always wrap with the text on screens larger than desktop: <img width="320" alt="image" src="https://user-images.githubusercontent.com/12564977/221008771-8129f233-4504-4110-97e2-a429989b9025.png">
- [x] 4. When the **Medical supplies and equipment** H2 wraps, the text should left align to the **M** in **Medical** including mobile: <img width="196" alt="image" src="https://user-images.githubusercontent.com/12564977/221009249-6f011fe8-054a-487b-8db0-31a26ae2ef94.png">
- [x] 5. Our headers are looking a little bold—could you look at [this article](https://stackoverflow.com/questions/45204673/font-looks-a-little-bolder-on-chrome) and see if we can leverage the font smoothing (as long as it doesn't break anything, of course). I pasted `-webkit-font-smoothing: antialiased;` in chrome and it worked. 
- [x] 6. The intro text beneath the H1 should be our Intro style [seen here](https://www.va.gov/health-care/refill-track-prescriptions/) (PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23464)
- [x] 7. @DanielleThierryUSDSVA if you have content edits for this, you can drop them here if you want. (PR: https://github.com/department-of-veterans-affairs/vets-website/pull/23464; using recommendation from https://github.com/department-of-veterans-affairs/va.gov-team/issues/53568#issuecomment-1434681007)
- [x] 8. The space around the text in the gray boxes should be visually equidistant. Currently the bottom padding is too generous: 
<img width="226" alt="image" src="https://user-images.githubusercontent.com/12564977/221011858-7d193a23-d0a6-49c6-9a7f-4df6bdc86214.png">

**Comment by dcloud** [comment]
Re h2s being a little bold, I think we'd want to adjust the `font-weight` rather than fiddle with vendor-prefixed styles for adjusting antialiasing. The `-webkit-font-smoothing` is Safari/Chrome compatible, and maybe only available on macOS. There is a similar vendor-prefixed style for Firefox, also only on macOS. Here's [some relevant discussion](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth#see_also) via men webddocs.

@rtwell Would you like the font-weight reduced? Here's a what `font-weight: 500;` looks like:
 
![Screen Shot 2023-03-02 at 12 36 42](https://user-images.githubusercontent.com/279327/222507704-177e0b9a-ea95-4f7f-b44d-ef68369c8b38.png)

**Comment by rtwell** [comment]
@dcloud no we should not adjust the weights. Is there a better fix for the issue (besides changing the weights)? I know it doesnt affect _all_ users, but iut helps _some_ users

**Comment by dcloud** [comment]
You make a convincing argument: https://github.com/department-of-veterans-affairs/vets-website/pull/23464/files#diff-c06ce93e49167c0d586d870914b983f931562cd608372137e6ffb42001cc776dR5-R14

Also, per [this blog post](https://www.joshwcomeau.com/css/custom-css-reset/#five-font-smoothing-6) (and maybe others), it sounds like the issue is subpixel antialiasing, which was removed from macOS but still on by default in browsers? 

This sort of change should probably be made in the design system if this issue affects multiple pages. Should we open a ticket for the design system team? Or a PR if I can figure out where `formation` lives on Github?

**Comment by dcloud** [comment]
The work on this ticket is complete, however as of this morning, something was amiss with the CI, so things haven't deployed to staging. 

We can reopen this ticket or create a new one when things are reviewable in staging

**Comment by humancompanion-usds** [comment]
@dcloud and @rtwell - We'd like to remove font-smoothing as it is resulting in different levels of "boldness" across our buttons. You can follow our thought process here: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1585#issuecomment-1456418002 The usability guidance we've seen recommends that we stop messing with it.

**Comment by dcloud** [comment]
I responded to that issue: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/1585#issuecomment-1458870519
