### ISSUE TITLE
Appointment List Re-design - Improve Voiceover interaction through appointment elements 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54100]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details of their appointment.

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

Problem found: When navigating individual elements (VoiceOver + arrow keys), VoiceOver announces each element independently, which may cause issues understanding the appointment context.

https://user-images.githubusercontent.com/2536801/221654030-33ce8588-b53a-48eb-a3c8-2b864661b835.mov

## Proposed solution

Please review @briandeconinck 's [recommendations in the midpoint review ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48197) for more information on handling this issue.

Hide content from screenreaders and add screenreader-only content to replace it so that,
when a user navigates individual elements using VoiceOver + arrow keys:

- [x] When the user navigates to the upcoming or past appointments **date/time column**, 
    - Then VO announces `[Canceled] [A|a]ppointment on [date/time].` 
    - Where `[Canceled]` is announced only if the appointment is canceled.
    - And [Date/time] is formatted as `[Weekday], [Month] [DD], [YYYY] at [HH:MM][a.m.|p.m.] [Time zone].`
    - See examples [here](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3836%3A59508&t=KYqjcGFs74pCPbjK-4).

- [x] When the user navigates to the upcoming appointments **type of care column**
    - And the appointment is canceled
    - Then VO announces `Canceled` before it reads the cell contents.
    - See example [here](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3806%3A60269&t=KYqjcGFs74pCPbjK-4)

- [x] When the user navigates to the upcoming or past appointments **modality column**
    - And the modality is in person
        - Then VO announces `[Canceled] [I|i]n-person appointment at [Facility name]`
    - And the modality is video care
        - Then VO announces `[Canceled] [V|v]ideo appointment`
    - And the modality is phone
        - Then VO announces `[Canceled] [P|p]hone appointment`
    - And the modality is community care
        - Then VO announces `[Canceled] [C|c]ommunity care appointment`
        - See example [here](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3806%3A60269&t=KYqjcGFs74pCPbjK-4)

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@ldelacosta This one is ready to review with Dev

**Comment by simiadebowale** [comment]
@ldelacosta - this is ready for validation.

**Comment by ldelacosta** [comment]
@Cieramaddox @outerpress - this ticket is ready to be tested in staging. Please let us know if you have any issues. Thanks!

**Comment by outerpress** [comment]
@simiadebowale summing up from our chat:
- Initial readout of full dates is perfect
- Let's default to announcing the content once for the type of care and modality columns, even if that means we can't add the "canceled" announcement
- For details links, see if adding the aria-label directly to the link instead of the group will fix the issue where it's repeating a few times.

**Comment by simiadebowale** [comment]
@outerpress - this is ready for validation

**Comment by simiadebowale** [comment]
@outerpress - this is ready for validation

**Comment by outerpress** [comment]
@simiadebowale this is sounding great, I'm calling it good to go with one note below.

In Chrome, Tab doesn't read the full aria-label when tabbing through the interface. However, Safari is reading the links correctly. And, I'm now seeing the full aria-label in Chrome when [using the VoiceOver rotor menu](https://support.apple.com/guide/voiceover/with-the-voiceover-rotor-mchlp2719/mac), where previously it just showed "Details." Since users have two ways to access the info, and it may be a Chrome bug, let's leave it as is and dig into it during screenreader testing.

**Comment by ldelacosta** [comment]
@simiadebowale - could you review Peter's comment in the ticket?

**Comment by outerpress** [comment]
@ldelacosta let's call this good to go. We'll file new tickets after launch if we need to change this based on user feedback.

**Comment by ldelacosta** [comment]
No new issues. Closing out the ticket.
