### ISSUE TITLE
Inbound SSOe users: implement re-authentication process if missing an ID.me UUID

### ISSUE THREAD

**Issue by patrickvinograd** [department-of-veterans-affairs/va.gov-team#5416]
**User Story**
For the population of users who arrive on VA.gov from elsewhere with an active SSOe session, but who don't have an ID.me UUID present, we need to request them to re-authenticate to establish that mapping. Otherwise they may have previously-submitted data on VA.gov that we will be unable to look up. 
See #5097 for context.

**UX Consideration**
What type of alert/help text needs to be implemented to allude to the fact that we are improving login across VA sites but need them to re-authenticate this one time to match up their records?

**Comment by bridgethapner** [comment]
Reference screenshot of Warning alert in modal attached

![Screen Shot 2020-02-04 at 2.32.15 PM.png](https://images.zenhubusercontent.com/5d8e52f61c53fd000173c5de/eb14f9f0-4c8e-4eb3-bfb5-4487c53904f0)

**Comment by ambikaroos** [comment]
UX decision: We will not be showing any explanation for why a user needs to re-authenticate. Once a user authenticates, they will see the SSO first-time user modal

**Comment by ericbuckley** [comment]
The force parameter is now available on the v1 sessions controller, so when a one time re-authenticate is needed the FE will need to make a request to `/v1/sessions/idme/new?force=true` to force this to happen.

**Comment by ericbuckley** [comment]
@marriej, @ambikaroos, @bridgethapner I have everything I need to move forward with this, but as it stands the UX for one time re-authentication feels a little weird to me, so I wanted to confirm this with you first by running through an example.

- a user, who has never logged into VA.gov before, logs into eBenefits with DS Logon credentials
- after a few mins, they open up a new tab to VA.gov (or possibly click a link on eBenefits to VA.gov)
- because the user already has an SSOe session, we attempt to auto log that user in
- auto login works, and we get a cached SAML response back from SSOe
- the cached response is missing an ID.me UUID because the user had never previously logged into VA.gov
- we immediately redirect the user back to DS Logon to one time re-authenticate

While the above is possible from a technical perspective, it feels weird to me that the user opens up a new tab for VA.gov, but ultimately lands on a DS Logon sign in page....

**Comment by ericbuckley** [comment]
I had a call with @bridgethapner this afternoon to discuss the UX.  In short, she informed me that the original plan was to leave the user logged out, if we attempt an auto login and the SAML request is missing an ID.me UUID.

We did however make changes to the vets-api in April that would allow a [user to login without having an ID.me uuid](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7110).  @patrickvinograd do you have any thoughts about whether this workflow is still desired?

**Comment by bridgethapner** [comment]
**UX POV:** My POV is that users who cannot be auto-logged in on VA.gov when landing there from another site should manually trigger and go through the sign-in process once, by themselves. Adding a modal or other communication explaining that we need a one-time re-auth could be confusing (what if a user lands here to look at information and doesn't want to sign in? what if eBen and MHV haven't explained SSOe or a user didn't read that communication?). It feels simplest given the range of potential user goals and familiarity with SSOe for a user to sign in one more time with no additional messaging and no re-direction or auto triggering of the sign-in modal that might get in the way and remove control from the user.
