### ISSUE TITLE
Best bet request for <Verifying school enrollment>

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#54474]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.
 -  Select Request Type:
    - [ ] NEW: You would like to create a new best bet
    - [x] CHANGE: You would like to change an existing best bet
- Complete the corresponding section below to provide the relevant details  *(Section 1- New Request or Section 2-Change Request)*
- Post a link to this issue in Slack Channel #va-search with tag for  @Joni Chan

# Section 1: New Request

### Description
*Please provide a brief description of the initiative and supporting information for the creation of a best bet.*  
>Example: "The VA is working closely with the Centers for Disease Control and Prevention (CDC) and other federal partners to provide COVID-19 vaccines to Veterans and VA health care personnel. The Find a Facility tool has just added COVID vaccine as a search category and we want to create a Best Bet to ensure veterans seeking looking information are aware of this new tool feature."*

        > description

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
        > 
 
 ### Please provide the following information:

 - [ ] Specify the **Headline** for the Best Bet 

> Example: Get information about the COVID 19 vaccine from your local VA facility_

        > enter headline
 - [ ] Specify the **Text** for the Best Bet 

> Example: Get the latest updates about COVID-19 vaccines at your nearest VA facility._

        > enter text

 - [ ] Specify the  **Keywords** that would generate the Best Bet 

> Examples: covid vaccine, covid vaccine availability, vaccine availability, etc._

        > enter text

 - [ ] Specify the **URL** for the Best Bet 

> Examples: https://www.va.gov/find-locations?facilityType=health&serviceType=Covid19Vaccine_

        > enter url
       

# Section 2: Change Request

### Description
Please provide a brief description of the initiative and supporting information for the creation of a best bet.  
> ****Example:*** "The VA is working closely with the Centers for Disease Control and Prevention (CDC) and other federal partners to provide COVID-19 vaccines to Veterans and VA health care personnel. The Find a Facility tool has just added [COVID vaccine as a search category](https://www.va.gov/find-locations?facilityType=health&serviceType=Covid19Vaccine)and we want to create a Best Bet to ensure veterans seeking looking information are aware of this new tool feature."**

###  Completion Dates
 *Do you have any target  dates we should be aware of?*
   
        > Tool is launching 3/6 so anytime after that
 
 ### Please provide the following information:
 - [x] Identify the Best Bet requiring changes

        > "verify school enrollments" currently points to here: https://www.gibill.va.gov/wave/index.do

- [x] Specify the change(s) that are required.  

        > New best bet should be: www.va.gov/education/verify-school-enrollment/ The teaser text would need to change too.
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: These requests are handled by the Sitewide Content and IA team. Reach out via Slack #sitewide-content-ia with any questions.***

**Comment by jennymayoco** [comment]
Hi @RLHecht! Is there a timeline for when the tool will launch?

**Comment by RLHecht** [comment]
Hi @jennymayoco This should hopefully be launching today. It launched on Monday but there are issues with the tool now that we've published our landing pages so that team is actively working on a fix.

**Comment by mnorthuis** [comment]
Here is the current best bet information
Title: Verify School Enrollment
Description: If you're receiving the Montgomery GI Bill Active Duty or Selected Reserve GI Bill, verify your school enrollment with the Web Automated Verification of Enrollment (WAVE) system.
Destination:  https://www.gibill.va.gov/wave/

@RLHecht Linking to WAVE for the Montgomery benefits is technically correct still.  Did the Edu stakeholders request to route all enrollment verifications through our page first? Otherwise we should probably look at whether it makes more sense to leave this one and add a new best bet for the new tool, or if we should go ahead and route all enrollment verifications through our page.

**Comment by RLHecht** [comment]
@mnorthuis We no longer have the WAVE link in the left nav and only have the link to it from our [new page](https://www.va.gov/education/verify-school-enrollment), so I think it makes sense to route everyone through our page first.

**Comment by RLHecht** [comment]
@katherine-fung Can you supply Jenny with the content that should be used for the verifying school enrollment best bet? Thank you!

**Comment by jennymayoco** [comment]
Hi @katherine-fung ! We are currently developing best bets guidances for IA and based on an earlier decision, we will be using the H1 and metadata for already existing pages so we are good to move forward with referencing the content that is live for this best bet. Thanks!

**Comment by jennymayoco** [comment]
Hi @RLHecht @katherine-fung - we've updated the URL, H1 and metadescription and are also in the process of reviewing the current keywords.

The current metadescription exceeds the 255 character limit so we shortened it for now to -

"If you're using Post-9/11 GI Bill benefits, you can verify your enrollment for school or training on VA.gov. If you're using Montgomery GI Bill benefits, you can verify your enrollment on the WAVE website."

Does the team have suggestions for how to shorten the current metadescription so it fits within that character limit?

**Comment by katherine-fung** [comment]
Thanks @jennymayoco! You can use this as the teaser text: 

"If you’re using Post-9/11 GI Bill benefits, you can verify your enrollment for school or training on VA.gov. Or find out how to verify your enrollment for other education benefits."

**Comment by RLHecht** [comment]
@jennymayoco is this one good to close now?

**Comment by jennymayoco** [comment]
@RLHecht This is currently in progress as we're in the process of reviewing the current keywords as well.

**Comment by jennymayoco** [comment]
Based on the past month's metrics, the current best bet "GI Bill Wave" isn't resulting in as many searches. I would recommend coming back to this best bet after a few months of this tool being available and seeing how the terms are continuing to perform.

The additional best bet "enrollment verification" shows higher searches, but isn't in the top 5 VA searches. It is instead represented as "verify enrollment".

#### Information on landing page (03/08/23 - 04/11/23)
Since tool launch as of 3/8/2023

- Page views: 505,781
- Bounce rate: 0.64%
- Entrance rate: 48,620 (93.20%)
- Top previous pages
   - Verify school enrollment login modal - 42%
   - Education hub - ~12%
   - VA Payment history page - ~10%
- Top 5 VA.gov searches leading to the requested landing page
   - Coe - 15 searches
   - Certificate of eligibility - 14 searches
   - Verify enrollment - 6 searches
   - Wave - 6 searches
   - Enrollment manager - 4 searches

#### Information on "enrollment verification" in search (03/08/23 - 04/11/23)
- Top search terms including the word "enrollment verification" in the past month:
   - Enrollment verification - 471, CTR 43%
   - Verification of enrollment - 10, CTR 50%
   - GI Bill enrollment verification - 9 CTR 44%
- Top URLs clicked
   - [www.va.gov/education/verify-school-enrollment/](https://www.va.gov/education/verify-school-enrollment/) - 148
   - [www.gibill.va.gov/wave/](https://www.gibill.va.gov/wave/) - 43
#### Information on "GI Bill WAVE" in search (03/08/23 - 04/11/23)
- Top search terms including the word "GI Bill Wave" in the past month, only 3 results:
   - GI bill wave - 8, CTR 50%
   - Wave GI bill - 3, CTR 33%
   - GI bill waves - 2, CTR%
- Top URLs clicked
   - [www.va.gov/education/verify-school-enrollment/](https://www.va.gov/education/verify-school-enrollment/) - 2
   - [www.va.gov/resources/gi-bill-wave-faqs/](https://www.va.gov/resources/gi-bill-wave-faqs/) - 2
