### ISSUE TITLE
Sitewide Content review of Form 21-4142(a) from Digitization Team

### ISSUE THREAD

**Issue by tbaker1026** [department-of-veterans-affairs/va.gov-team#54641]
## What does your team need support for? Check all that apply.
- [x] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- [Link to product outline:](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/Product%20Outline.md)
- Link to or attach user flows:
- [Source of Truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/sourceoftruth.md)
- [Link to prototype or mockups:](https://www.sketch.com/s/c8c31a8a-19ae-4cbc-81ef-40eb8f4f8c52)
- Link to any epics/issues that may be helpful:
- [New content only for review](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/new-content-for-review.md)

## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Mid April
- Estimated staging review date:
- Content and IA work needed by: March 24th

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Dingee
-	Product manager: Tricia Baker
-	Designer: Jeana Clark
-	FE engineer: Robert Hasslle
-	Product/team Slack channel: product_forms_team

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by jennymayoco** [comment]
Hi everyone! @kristinoletmuskat and I are reviewing the design assets and we were wondering where would be the best place for any feedback or questions. Would the team prefer we communicate through GH or adding comments directly in Sketch?

**Comment by jeana-adhoc** [comment]
Hi @jennymayoco - I think it depends on the questions/feedback. Sketch comments are fine - although the sketch files are in a bit of disarray right now because we're adding a new 'chapter' due to stakeholder feedback. On our previous form, someone had copied out all of the text from the form into a word doc, and made edits/comments there; or edits could be made to the source of truth document as well as a PR. Truth be told - I'm open to whatever format is easiest for your team to get feedback to us in the quickest manner as long as we can make that consistent across all of our future projects as well. 

We are meeting with the stakeholder later today and anticipate some content changes to the form. It might make sense to hold off a day or two on any review so you can review those changes as well. I will let you know when those changes are incorporated into sketch and the source of truth document.

**Comment by tbaker1026** [comment]
@jennymayoco @RLHecht - I know we still don't know where this form will live but wanted to see if you can check out the content of the form itself, so if there are any changes we can have our developer update them. Thank you

**Comment by jeana-adhoc** [comment]
Here is a link to the new content that is in this form that has not been previously reviewed in other forms. 

- [New content for review](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/new-content-for-review.md)

**Comment by kristinoletmuskat** [comment]
Hey hey @jeana-adhoc , @jennymayoco is out on PTO so I just took a look.

The auth/unauth flows make sense to me. I talked with Jeana about moving the "preparer information" in the unauth flow from the end to the beginning to potentially reduce anxiety for preparers, and Jeana let me know that they want to do that, but aren't making that change for MVP because of engineering difficulty. 

Other workflow thoughts to consider -- my understanding is that this form is part of a larger thing Veterans are trying to do. Submitting the 526 being one of them, but also Pension I think? I know @sterkenburgsara is working on where to put these. I also wonder if we want to ask a question like "why are you submitting this" to get the user's intention. If they submit this one-off but haven't submitted their 526, could we tell them that? That might be wildly out of scope so lmk!

@RLHecht I think having someone in content look at the form fields would be ideal, but here are some thoughts:

Q1: will users know what "Someone else connected to the Veteran" means, or should we give some examples?

Q2: Could we pull this info in by default in some cases so the veteran doesn't have to enter it again if it's themselves?

Q3: Do 'the conditions the patient was treated for at the facility' need to be comprehensive? What if the veteran forgets one? Do they need to be the treatments that they listed on their 526 or other forms?

These Qs are just things that came to mind for me that could trip up a veteran or preparer, so feel free to ignore if you think they aren't relevant.

**Comment by jeana-adhoc** [comment]
> Q1: will users know what "Someone else connected to the Veteran" means, or should we give some examples?

The PDF itself says "PATIENT IDENTIFICATION FOR RECORDS VA IS REQUESTING (If other than veteran)" We don't need to identify the relationship in the form, but, we do need additional information if they are requesting other information. So we ask this question as a conditional to know whether or not we can skip Section 2 of the PDF. I'm open to better ways to wording this.

> Q2: Could we pull this info in by default in some cases so the veteran doesn't have to enter it again if it's themselves?

We're limited to only pulling in information that's available in profile for the authenticated experience. Which is mostly contact information.

> Q3: Do 'the conditions the patient was treated for at the facility' need to be comprehensive? What if the veteran forgets one? Do they need to be the treatments that they listed on their 526 or other forms?

In 526, it connects to other claims that they've made or other illnesses they've selected earlier in the form. We dont' have that capability here--partly because we're also building an unauthenticated experience as well.  We know that the following forms use 21-4142 & 21-4142a to request medical records from private facilities:
- [Supplemental Claims 20-0995](https://www.va.gov/find-forms/about-form-20-0995/)
- [File for disability compensation 21-526EZ](https://www.va.gov/disability/file-disability-claim-form-21-526ez/)
- [Priority Processing Request 20-10207](https://www.va.gov/find-forms/about-form-20-10207/)
- [Application for Burial benefits 21P-530EZ](https://www.vba.va.gov/pubs/forms/VBA-21P-530EZ-ARE.pdf)
- There are likely others

[Here's more sitewide questions we answered for this form](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-4142(a)/ia-sitewide.md)

**Comment by kristinoletmuskat** [comment]
@jeana-adhoc awesome thank you! 

I think once we have a location for this and other multi-benefit forms, we can also think about how to add supporting language/links to make it clear how the form is connected to other larger goals (to actually getting or maintaining benefits). 

I just chatted with @RLHecht and we're going to see if we can pull in a content person to do a light look at some of the areas I pointed out. Stay tuned!

**Comment by jennymayoco** [comment]
Hi everyone! We have put together the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-4142.md) for this form based on the benefit agnostic work provided by Sara.

We left the "a" out of 4142 in the link, so please let us know if there are any questions about this. It was left off as our understanding was that the two forms would be combined. Happy to update this link to best represent the H1!

**Comment by jeana-adhoc** [comment]
The two forms are currently combined into one PDF right now but are labeled within the PDF 21-4142 and 21-4142a respectively. Our Stakeholder is rather particular that both are called out in the verbiage on the online experience. I don't know if that matters when it comes to the URL. But we will need to identify in the form intro and subtitle that it is both 21-4142 and 21-4142a. Let me know if that changes your direction for the URL or not, otherwise I will pass the new URL onto our engineer to get that set up.

**Comment by mnorthuis** [comment]
Hi @jeana-adhoc Representing both form numbers in the URL will be a bit difficult and can start to get long, but I do want to make sure that doesn't create any confusion by not having them both there as well.  

Our standard approach to form URLs is to use 2-3 descriptive keywords plus the word "form" plus the full form number.  In this form, we used "release-records-to-va" for the keywords; the "to-va" part is important because there are other forms that release records from VA, so it's critical context, so it's hard to shorten that.  

Just straight adding the second form number would make this full url way too long - the second segment alone is almost 50 characters:  
 - /supporting-forms-for-claims/release-records-to-va-form-21-4142-and-21-4142a

A few options, which break our standard patterns, but might better meet the needs here:
- /supporting-forms-for-claims/release-records-to-va-forms-4142-4142a   (drops the 21 in form number and the "and")
- /supporting-forms-for-claims/release-records-to-va-4142-4142a (drops the 21 in the form number and the "and", also drops "forms" which is included in parent segment of URL)

Any thoughts on if either of those would work better than just using 4142 alone?  Is for sure there concern that only having the 4142 in the URL might cause confusion?

**Comment by jeana-adhoc** [comment]
@mnorthuis - Thanks for this. After discussing it with Tricia, we will stick with the original URL that's listed in the [IA Spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-4142.md)

**Comment by tbaker1026** [comment]
@jennymayoco Do you have a time estimate when the holding H1 page will be created?  Our stakeholder is going out on personal leave for 3 weeks at the beginning of June so we would ideally like to go live with this form before she leaves.  Thank you

**Comment by jennymayoco** [comment]
Hi @tbaker1026 - content will come from @megzehn at CAIA!

**Comment by megzehn** [comment]
Hi @jeana-adhoc, here's a [Sharepoint doc with the suggested edits](https://dvagov-my.sharepoint.com/:w:/g/personal/megan_zehnder_va_gov/ERdMb_2IM8xGnIBLawPFZoEBMznM4GPNesW8gJ6Zwna15Q?email=Jeana.Clark%40va.gov&e=sloM15) as we discussed on the call today. Let me know if there are any questions. Thanks!

**Comment by jennymayoco** [comment]
Hi everyone! Following up here with the updated [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-4142.md). The URL now reflects the updated H1 - `/release-information-to-va-form-21-4142`

Let me know if you have any questions.

**Comment by tbaker1026** [comment]
@megzehn do you have an ETA on the landing page for this form?  Thank you

**Comment by megzehn** [comment]
Hi @tbaker1026, I don't have an exact ETA yet. But @DanielleThierryUSDSVA and I started talking through the structure of the landing page, and I'll work on filling it in as we get through the individual forms. We can get you the proposed H1 sooner if that helps! Also, I'll post updates in ticket [#52830](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/58230).

One question: Do you have a list of all the supporting forms that will need to be on this landing page? 

CC @RLHecht for awareness!

**Comment by tbaker1026** [comment]
Ok to close

**Comment by jennymayoco** [comment]
Hi @tbaker1026 @jeana-adhoc @megzehn I've updated the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-4142.md) with 3 additional entry points, these are items # 4-6. [Supplemental claim](https://www.va.gov/decision-reviews/supplemental-claim/) and its [Spanish translated page](https://www.va.gov/decision-reviews/supplemental-claim-esp/) are on there as well as [VA's duty to assist page](https://www.va.gov/resources/vas-duty-to-assist/).

**Comment by tbaker1026** [comment]
@jennymayoco anything Jeana and need to do about the new entry points or just an FYI?

**Comment by RLHecht** [comment]
FYSA @strelichl. Do you want to open a new ticket for our team to add these entry points? We'll also need to send out the one on the Spanish page for translation.

**Comment by jennymayoco** [comment]
@tbaker1026 would love to hear your feedback! this was one of the forms that was part of the content audit to identify any other mentions of a form on the modernized site.
