### ISSUE TITLE
Update platform dashboard for analytics reporting

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#547]
## Description

For the spin-up of new contract with new or updated objectives, we need to update or replace the key metrics dashboard to allow values to be pulled regularly for reporting out.

For the moment, we have these:

- % of HTTP requests completed successfully (basically, uptime)
- latency by percentile (i.e. median latency, 90th-percentile latency) of HTTP requests
- page load time (as experienced by user) by percentile [probably comes from Google Analytics and won't be on Grafana for now]
- CI/CD build time (basically "how long does a build take after commit / for a PR"?)
- production deployment success rate (i.e. how many of our daily prod deploys succeed on the first try / without manual intervention?)

Need to figure out what format these are expected to be reported in yet.

The CI/CD job metrics have some data in Jenkins, and we also have a Prometheus plugin installed but I'm not sure that what exists today will be useful for this exact purpose.

## AC

- [ ] updated dashboard covering these metrics

**Comment by ricetj** [comment]
This is to help us understand if VSP is successful. Ops data to show how VSP is successful. This is to help improve VSP KRs

**Comment by wyattwalter** [comment]
> - % of HTTP requests completed successfully (basically, uptime)

We have this and is on the metrics dashboard now, but I do see that it may be filtering out some types of requests unintentionally (it removes any metrics with no "component" value which not as many have that today as there used to be).

> - latency by percentile (i.e. median latency, 90th-percentile latency) of HTTP requests

From the revproxy we do not have this data. The bucketing that we do is the in the opposite direction, we have percentages of requests that fall within specific thresholds (ie. percentage of requests that are served within 100ms, 500ms, etc). This could maybe be supported, but likely a non-trivial addition to the plugin that we use. It _is_ available for vets-api from the rack metrics middleware, but that only covers requests going through vets-api (might be ok). This data is not being sent to longer-term storage in a useful way, but could be fairly trivially.

> - page load time (as experienced by user) by percentile [probably comes from Google Analytics and won't be on Grafana for now]

I think this is just a link that I can add to the Grafana dashboard.

> - CI/CD build time (basically "how long does a build take after commit / for a PR"?)

This is one we probably want to track on a per-repo basis as each repo can be different. Other metrics that may be useful here are things like amount of time waiting before a worker was available. The plugin that we have installed in Jenkins is emitting some pretty limited metrics. I don't know yet how much work it could be to modify this. Jenkins also has some built-in metrics in the UI.. might be able to just export those somehow.

> - production deployment success rate (i.e. how many of our daily prod deploys succeed on the first try / without manual intervention?)

Similar story to the above. Right now we don't keep enough history of these jobs to really be meaningful, so that'll be step 1 for sure. If nothing else, we could link to the page in Jenkins that contains the data on it.

**Comment by ricetj** [comment]
@ricetj to check if this is still needed.

**Comment by ricetj** [comment]
not needed
