### ISSUE TITLE
Appointment List Redesign - Columns space update

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54818]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ]  Columns should be spaced as indicated in [the layout guide](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3842-59523).
   - Upcoming and past: 
      - [Desktop](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3871-135996&t=hfRrO1IcvqqCWqMa-4)
      -  [Tablet](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=4003-70027&t=hfRrO1IcvqqCWqMa-4)
   - Pending:
      - [Desktop](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=3871-135996&t=hfRrO1IcvqqCWqMa-4)
      - [Tablet](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=4052-103031&t=hfRrO1IcvqqCWqMa-4)
   

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by Cieramaddox** [comment]
@vbahinwillit 
Looks like spacing is set to 24px across the board.
Spacing should be as follows (and it looks like it hasn't been addressed just yet): 

- Upcoming and past

![Screenshot 2023-04-12 at 1.38.42 PM.png](https://images.zenhubusercontent.com/618c20406719b91000e30ee6/182232a2-c27f-42e1-ba1a-123be55133c5)

- Pending

![Screenshot 2023-04-12 at 1.39.24 PM.png](https://images.zenhubusercontent.com/618c20406719b91000e30ee6/8202b020-d76d-4afa-a6c2-ea23d303386f)

**Comment by vbahinwillit** [comment]
For Desktop:
In order to get the columns to wrap properly for mobile, the row consists of 3 columns with a gap of 24px (I picked the smallest). It's impossible (as far as I know to specify different gap sizes (24px & 32px). The 1st column contains the time, the 2nd column contains a nested row with 2 columns since type of care and modality must wrap together and the 3rd column contains the details.

For Tablet:
I can change the gap to 32  but 18px and 20px are not multiples of 8 (the same constraint applies for the gap to be the same for the row).

**Comment by Cieramaddox** [comment]
@vbahinwillit Okay. Thank you for explaining that. What we have then is great.
