### ISSUE TITLE
Add backend (postgres) to docker-compose file

### ISSUE THREAD

**Issue by ianhundere** [department-of-veterans-affairs/va.gov-team#54894]
## Description
Instead of relying on postgres.app for the backend, a postgres image will be used in tandem with a `docker-compose` file just so that the steps in regards to configuring is more streamlined and as an opportunity for @teningnkem and @
vidjovanovic to get more Docker exposure.

## Acceptance Criteria
- [ ] No longer necessary to utilize postgres.app
- [ ] http://localhost:3000/v0/status /  http://localhost:3000 provide the correct output when hit
- [ ] postgres image defined in `docker-compose` file

**Comment by vidjovanovic** [comment]
Was able to connect to 5432 via docker-compose.yml with different front-end/db configuration with same pg database type. Issue is somewhere in the app configuration within sisapp and how it communicates with db - it's looking for a UNIX socket directly within the Host OS instead of networking directly within the containers. When creating with local pgadmin+db docker-compose.yml, it works fine: ![F04883FB-7D39-4DBC-ACB4-EE5F33A947E8.jpeg](https://images.zenhubusercontent.com/63ebe88c0371fc7bfde749c1/b83a8817-776a-468e-a7f9-adb0d9caa781)
