### ISSUE TITLE
Formalize SiS cert rotation docs

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#54946]
Can I get a review of [this](https://docs.google.com/document/d/1CU6AF14bMysfbPDJ9AWLXMDBNFmFhXWCVomlHOty7UI/edit#) doc and then drop it into [this](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsp/teams/Identity/How-To/Security) folder.

**Comment by ianhundere** [comment]
please convert this to markdown:
[https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/maste[…]ow-To/Security/SiS%20cert%20rotation%20-%20March%208%202023.txt](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/vsp/teams/Identity/How-To/Security/SiS%20cert%20rotation%20-%20March%208%202023.txt)

and please be sure to open a PR next time around so we can review prior to merging instead of pushing straight to master.

**Comment by ianhundere** [comment]
hey @teningnkem, just some helpful information for you:
- [getting started with markdown](https://www.markdownguide.org/getting-started/)
- [about pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

let me know if you have any other questions

**Comment by vidjovanovic** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/945

PR for markdown conversion
