### ISSUE TITLE
Discovery/research into what might be required to create a one-stop knowledge portal for VFS teams

### ISSUE THREAD

**Issue by hpjaj** [department-of-veterans-affairs/va.gov-team#552]
## Background
We need research and discovery around requirements for a one-stop knowledge portal for VFS team.

## Definition of Done
- [ ] Documentation of ideas, assumptions, etc.
- [ ] Shared with team

**Comment by smoonpeyes** [comment]
Link to research plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/research/Onboarding%20MVP%20-%20Jul%202019/research%20plan.md

**Comment by smoonpeyes** [comment]
@emilywaggoner Do you have any additional details about this objective?

**Comment by emilywaggoner** [comment]
@smoonpeyes Ah so this one was de-prioritized for this sprint. The Content and IA team has a stretch goal for this sprint to begin thinking about initial recommendations for the _Portal_. Let's plan to coordinate with them next sprint, because I imagine that's when this will come up again for this team. Clearing the milestone from this ticket for now.

**Comment by smoonpeyes** [comment]
@emilywaggoner Thanks. Moving it to the backlog.
