### ISSUE TITLE
IA design for Forms 21-4142 and 21-4142a

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#55210]

**Comment by kristinoletmuskat** [comment]
**Overview:**
- This form is part of supplemental claims form, and they want to break it out?
- The form lets the VA get a veteran’s medical info from a private dr or hospital
-- Name and address of facility
-- Medical treatment dates
- Form 21-4142 (without the a), which is different, does the same thing but for:
-- Medical treatment
-- Hospitalizations
-- Therapy
-- Outpatient care
- This applies to veterans and patients related to them
- Current submission rates
-- 98,073 downloads
-- 258,771 mail-in submissions
- They want logged-in and logged-out users to be able to submit

**Questions for product team**
1. Our understanding is this is currently part of the supplemental claims form, and is being broken out. Why is it being broken out?
2. It looks like there are 2 forms – 21-4142(a) and 21-4142 (without the a). 
 - Is this work for both of these?
 - Will they both continue to exist?
3. Feedback about workflow
- Would be helpful to add earlier starting point – what is the veteran actually trying to do that requires them to use this form? Ex: enrolling in healthcare, coordinating care with a new provider, etc. 
- Similar feedback on end point – what happens after they submit the form? Will they have to take any steps? (ex: provide additional docs, check email for result, etc). 

**Next steps**
1. Ask these Qs above in the intake ticket
2. Figure out who other CAIA is working on this with us and set up a little meet to coordinate with them
3. Make sure the Epic has the order of operations and who is doing what

**Comment by jennymayoco** [comment]
Shared the following questions to the Forms team slack:

1. Is there additional detail that can be provided to better explain what happens next, and what, if anything, the Veteran needs to do next? Currently written as “After we review your request we’ll contact you to tell you what happens next in the process.”
In addition to, since this form is part of the 526 flow and also intersects with other benefits, how could the language be updated so that this is reflected in this form?

2. What other use cases, besides disability compensation, is this form used for?  This will impact placement on the site and entry points.  It will also impact if more supporting content is needed to clarify when/why someone would utilize this form.

3. How is this form submission connected with the submitter's disability claim or other benefit application ?  Do we need to identify why they are submitting this up front?  Also, the 526 requires authentication, but this can be done without signing in, will this create any issues in matching this submission to other forms submitted?

**Comment by tbaker1026** [comment]
@jennymayoco - put in slack but adding it here as well 

Some scenarios we came up with (will run them by Stakeholders):  
1.) reapplication of the 4142 (whether it's for a new hospital/doctor or potentially to reapply the request if the prior authorization expired)  
2.) In filing within the 527 on behalf of a disabled dependent  
3.) In conjunction with 20-10207  
4.) In filing within the 686c on behalf of a disabled dependent  
5.) A fiduciary or power of attorney filling out this form and might not have the authenticated experience for the 526 (edited)

6\.  If they chose not to submit the facilities when they fill out the claims form but decide later they would like to submit it, they have up to one year to submit additional evidence

Here is a page that has some information on it - [https://www.va.gov/disability/upload-supporting-evidence/](https://www.va.gov/disability/upload-supporting-evidence/)

**Comment by jennymayoco** [comment]
Here is the [IA spec ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-4142.md)for this form.

- [X] Has been shared with the forms team
- [X] Had been shared with Megan

I added a note about the link name and if this matches with the H1 since the forms are being combined.

**Comment by jennymayoco** [comment]
Adding [Sitewide ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54641) for reference

**Comment by RLHecht** [comment]
Closing this ticket. Work complete.

**Comment by jennymayoco** [comment]
Updated forms team and Megan in intake ticket with 3 additional entry points that we've added to the [IA spec](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/form-digitization-21-4142.md)
