### ISSUE TITLE
[Research] Notification Center Discovery: Draft a plan for stakeholder research

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#55245]
## Background
As part of this next phase of work on onsite notifications, we need to do some discovery around a Notification Center on VA.gov. We need to look internally with stakeholders. This ticket is to create a plan/outline with goals and methodology for capturing feedback from stakeholders.

**Questions to consider**
- Do we need standard research artifacts: research plan + conversation guide?
- What exactly are we asking folks? (See additional questions to consider in Samara's document)
- Who are we speaking with? (see document)
- How will we do this?

## Tasks
- [x] Craft plan for collecting feedback from stakeholders
- [x] Share with PM/PO (and any other team members for review and feedback)

## Resource
[Samara's thoughts on Notification Center discovery](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications/notification-center-discovery/samara-initial-thoughts.md#samaras-pre-maternity-leave-thoughts-on-notification-center-discovery)

**Comment by Samara-Strauss** [comment]
> Do we need standard research artifacts: research plan + conversation guide?

I don't think we need something as formal as what is put together for user research, but I think a rough outline of a plan or convo guide would be helpful to make sure we're all aligned on goals and questions. You can also tailor questions to specific people based on what you know about their roles, but I don't think there is a need for super individualized scripts. The over-arching structure of each call will likely be the same, with some specific follow-ups depending on people's roles and portfolios.

**Comment by Samara-Strauss** [comment]
Hi, this is great! My only comment is below:

> 2. Determine if there's a clear consensus on the vision for notifications on VA.gov.
> 
> Where should notifications be surfaced within the navigation of VA.gov, if at all?
> How should we indicate that a user has new notifications in the navigation, on My VA, and in the notification center (if we create opt to create one)?

I'm 100% aligned on the high level goal. For these questions, I'd broaden them further to remove mention of the navigation for two reasons: (1) first, we don't want to prime people with any approach, and (2) we want to leave room for insights that might not include the navigation (eg. do people think notifications should show on certain pages?).

**Comment by Samara-Strauss** [comment]
Oh, and two more things:

1. On Monday, I will let stakeholders know that I've asked you to speak with them, and see if we need to update or add anyone on this list. There's a couple people I could see adding or switching out with other folks. I'm going to wait to Monday because a lot of OCTO people are out on Fridays.
2. I think you can ask some stakeholder-specific questions about each portfolio. You can let those come up naturally in conversation, or have an idea of what you want to cover per person before the interview.

**Chris Johnston - Portfolio lead; Currently helping out with the mobile app (Note: Julia Badillo manages Chris's calendar)**

I'd focus on overall VA.gov vision with Chris, and thoughts on alignment of notification content and presentation with the mobile app.

**Lauren Alexanderson - Health lead (Note: Alicia Proctor manages Lauren's calendar)**

I'd focus on health-specific notifications and any specific considerations for the health apartment work, including timelines we should be aware of.

**Dave Conlon - Sitewide lead**

I'd focus on broader considerations around the navigation, since we can't surface notifications in a logged-out state. I'd also entertain the discussion around notifications that are a murky space between personalized and general (ie. there is a notification about someone's VAMC being closed for an emergency reason). Dave and I have talked about this before, and I could see it coming up.

**Matt Self - Benefits lead**

I'd focus on notifications in the claim/disability and education spaces, or anything else related to the general benefits portfolio.

**Mikki Northuis - IA/Nav lead**

I'd focus on overall placement of notifications and how we plan to surface them.

**Chante Lantos-Swett - Account experience lead; Also leads customer support work**

I'd focus on notification experience related to customer support.

**Martha Wilkes - Accessibility lead**

I'd focus on whether there are known practices for elevating notifications in an accessible way, and if there's anything we can or should do differently than we normally do to engage accessibility folks (since we are already in the habit of working with them early and often).

**Ryan Thurlwell - Design lead**

I'd focus on overall presentation of notifications or any other design-specific thoughts Ryan has.

**Comment by aagosto90** [comment]
@Samara-Strauss Question as I was thinking through the specific topics for each OCTO lead - isn't Matt Dingee still the design lead? I'm a little unclear of Ryan T's new role but it says in his Slack profile that he's working on the MHV to VA.gov and mobile app teams. Perhaps both would be good to chat with?

**Comment by Samara-Strauss** [comment]
@aagosto90 @ajakabcin I reached out in an OCTO-only Slack channel yesterday to give folks a heads-up that you'll be reaching out about interviews while I am on leave. I also confirmed the final list of who you should be talking to. I've bolded the changes below:

- Chris Johnston (Portfolio lead) -- Remember to use Chris' scheduler, Julia Badillo
- **Rachel Han (Mobile app lead)**
- Lauren Alexanderson, **Coulton Bunney, and Patrick Bateman** (Health portfolio) -- Remember to go through Lauren's scheduler, Alicia Proctor
- Dave Conlon  (Sitewide lead)
- Matt Self (Benefits lead)
- Mikki Northuis (IA/Nav lead)
- Chante Lantos-Swett (Account exp & customer support)
- Martha Wilkes (Accessibility)
- Ryan Thurlwell (Design lead)
- **Ray Wang (Platform)**

Let me know if you have any questions! Really looking forward to seeing your progress on this when I am back from leave.

**Comment by Samara-Strauss** [comment]
> Question as I was thinking through the specific topics for each OCTO lead - isn't Matt Dingee still the design lead? I'm a little unclear of Ryan T's new role but it says in his Slack profile that he's working on the MHV to VA.gov and mobile app teams. Perhaps both would be good to chat with?

We can swap out Ryan for Matt. That's fine with me! My brain was in "oh, Ryan's back" mode, but you're probably right -- Matt might be a better call.

**Comment by aagosto90** [comment]
Hi again @Samara-Strauss! The [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications/notification-center-discovery/scaling-onsite-notifications-stakeholder-convo-guide.md) is ready for your review. No rush; we can carry this ticket into early next sprint if necessary. 

While I expect these conversations to flow somewhat organically, I've tried to think of some specific questions we may have for each product lead. The only one I'm not really sure if I have anything specific to ask is for Platform (Ray Wang). I expect that Matt D. will probably be the best person to discuss components and design patterns with, so the only potential topic (I think) is the collab cycle process for this. So maybe a topic to discuss is how the collab cycle process is different for changes that can affect the entire site versus just our page that we own and any challenges we should expect? But is Ray the right person to ask about collab cycle processes or would that also be a question for Matt D?

Thanks as always!! 
CC @ajakabcin

**Comment by Samara-Strauss** [comment]
Great job, Angela!! My thoughts below:

> But is Ray the right person to ask about collab cycle processes or would that also be a question for Matt D?

I think Ray is probably the right person to talk about the collab cycle with. However, based on my conversation yesterday with him in Slack, it sounds like he has questions for you all on security and related things as we scale this functionality. So, I would leave some time for him to ask questions after you've had a chance to ask him what you need.

### Scaling Onsite Notifications (All)

> How familiar are you with the current state of onsite notifications on My VA? 

I'm curious as to why we are asking this. I'm not totally opposed to it, but I don't think we should be priming people (even if unintentionally) with showing them the current interface before we talk about user and team goals and needs.  Quite frankly, how familiar people are with our current work is the least important part of these calls.

> I'm curious if you know of any studies your team has conducted where they've heard feedback from users about how they expect to see notifications or action items represented on VA.gov. Does anything come to mind that we might want to reference as part of this work?

I'd break this down a little further:

- Who are their users?
- What do they need to do? What are common actions they take on VA.gov?
- THEN I would ask if they've talked at all about notifications with users.

> Do you have any expectations or opinions around how we elevate notifications on VA.gov that you'd like to share? 

Super nit-picky, but instead of asking this in a way where someone could just say "yes" or "no", can we assume they have opinions and ask "What are your expectation around how we elevate notifications on VA.gov?" I think this is a big place for further questions and follow-ups based on what people say. Definitely dig in here!

### Practice-specific

- I would ask each person about any near-term needs they are aware of for their portfolio re: notifications.
- For Mikki, I wouldn't just ask about timelines. I'd broaden that to be "What IA considerations..."

### Challenges

I would maybe ask these questions before the individual portfolio questions.

> Since the feature currently integrates with VA Notify, we can only present notifications that are supported by VA Notify. If users don't see common notifications in a notification center yet because VA Notify does not yet support them (eg. new message from your doctor, or a prescription shipping), what are your thoughts about whether users will trust the feature?

This question makes a lot of leaps, the most important being that we are adding a notification center. I think we can safely assume people won't trust a feature that feels like it's missing obvious information. Maybe we could broaden this to questions around:

- Any thoughts around scaling the feature over time (this could potentially come up in the expectations convo).
- How people think we can build veteran trust as we scale this feature. What are make or breaks re: trust?

**Comment by aagosto90** [comment]
Thanks for reviewing so quickly @Samara-Strauss! Really appreciate your detailed feedback and so glad you've been able to take a look at this before maternity leave. I feel a lot more prepared having been able to work with you on it!

I made updates to the [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications/notification-center-discovery/scaling-onsite-notifications-stakeholder-convo-guide.md) based on your feedback. Let me know if you suggest any other updates. I thought it might be helpful to give an overview of what we've already done for notifications in case people are wondering why it's our team in particular that's asking such broad questions, but I think you make a very good point that it's not important for this study. I especially think that's true because we're not tied to any part of our current implementation except for maybe the component we designed for it. The candid feedback about notifications on VA.gov with no parameters already set is going to be so valuable.

**Comment by Samara-Strauss** [comment]
This looks great! Wonderful job 😃 

> I thought it might be helpful to give an overview of what we've already done for notifications in case people are wondering why it's our team in particular that's asking such broad questions

I think most of the people we are talking to know enough about our work that they won't question why our team is doing these calls. Of course, feel free to answer any questions people have! I think you can do that in a way that's not leading, or wait to answer questions until the end.
