### ISSUE TITLE
[SW] Front End Discovery - Income Limits Threshold

### ISSUE THREAD

**Issue by denisecoveyduc** [department-of-veterans-affairs/va.gov-team#55604]

**Comment by HeatherRienks** [comment]
Add this ticket into Sprint 99 (then, FE Dev work will be completed for FSR enhancements, and we can focus on Fe and BE Streamlined Waiver efforts).

**Comment by HeatherRienks** [comment]
6/26/23 Meeting notes from Income Thresholds Technical Chat: Sitewide Public Sites Team
[https://app.zenhub.com/files/133843125/d3664bc9-54fe-4891-b868-8efebba2e69a/download](https://app.zenhub.com/files/133843125/d3664bc9-54fe-4891-b868-8efebba2e69a/download)

**Comment by HeatherRienks** [comment]
This ticket will rollover; focus has been on FSR launch.

**Comment by Dr-Pongo** [comment]
Some notes on this discovery: 
- Looks like income limits has a starter app configured which has an example of the api call here:
`src/applications/income-limits/api/index.js`. 
 - Chatted with the FE team and decided with the fetch we are going to calculate and store the 150%, 6.5%, and 1.25% of GMT in Redux so we can just compare for the `depends`, and we can adjust easier if they ever change. 
 - I think the best place to drop this fetch is whatever page comes immediately after dependent count. If there is an error I think we just just continue through the normal FSR so all of the data can be collected. If we run into an error during this fetch we can always try again later as we're collecting the income information since the branching doesn't occur until after we get gross income. 

#### Still need clarification
 - When do we switch the year we're fetching from the endpoint? 
 - Should we discard in progress forms when this switch happens (maybe just the ones that are leveraging streamlined functionality? - we'll need to include an indicator if it is)

**Comment by HeatherRienks** [comment]
will close by EOD today

**Comment by Dr-Pongo** [comment]
Closing out discovery and tracking implementation work in:
**Implement income limit back end** [#61841](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/61841)
