### ISSUE TITLE
AWS access for Joshua Drumm

### ISSUE THREAD

**Issue by JoshingYou1** [department-of-veterans-affairs/va.gov-team#55821]
### COR Name

Delano McVay

### Vendor Onboarding Representative Name

Agile Six - Anthony M. Arashiro

### E-QIP Transmittal Date

- [X] Check this box if you have an E-QIP transmittal date.

### Your Name

Joshua Drumm

### Your Email

joshua.drumm@agile6.com

### Team, Role, and Company of the target individual

10-10 Team, Backend engineer, Agile Six Applications, Inc.

### Product Manager (PM) name and email

Heather Justice, heather.justice@adhocteam.us

### Product Owner (PO) name and email

Patrick Bateman (patrick.bateman@va.gov) and Katherine Lawyer (katherine.lawyer@va.gov)

### Desired AWS Access

I'm requesting access to staging, dev, and review `vets-api` ec2 instances

### Access Expiration

ongoing

### E-QIP Transmittal Confirmation

<img width="697" alt="Screen Shot 2023-03-27 at 5 15 42 PM" src="https://user-images.githubusercontent.com/34111449/228068487-40b7ae56-fb84-4491-bd39-99966b04fcab.png">

### Additional Notes

I entered "ongoing" for the "Access Expiration" field because I wasn't sure of an exact date in which my access should be revoked.

### User must exist in a roster before AWS access can be granted

- [x] Search for user on the [VFS Team Roster](https://docs.google.com/spreadsheets/d/11dpCJjhs007uC6CWJI6djy3OAvjB8rHB65m0Yj8HXIw/edit?folder=0ALlyxurHpUilUk9PVA#gid=2042046665)
- [ ] Or search for user on the [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] If user is on a VFS team but not in the VFS Team Roster, add the 'NOT YET' label and instruct them to start the [Platform orientation process](https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html)
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [x] Comment in this issue saying which roster the user is listed in.

**Comment by JoshingYou1** [comment]
Has there been any movement on this? Not having access is now a blocker for me. Please let me know if there's anything I need to do on my end. Thank you!

**Comment by little-oddball** [comment]
@JoshingYou1 - it is awaiting OCTODE approval which last I recall was performed on a weekly basis. @BillChapmanUSDS

**Comment by BillChapmanUSDS** [comment]
I approve this access

**Comment by little-oddball** [comment]
@pjholyoke @considerable - please follow up regarding password? Not sure what the state of the overall request is.

**Comment by considerable** [comment]
Hello @JoshingYou1 !

Also tagging @little-oddball and @BillChapmanUSDS 

My apologies for the waiting time on this tkt. 
We had a team discussion about the trend of AWS requests where the ask is to provide access to Vets-API EC2 instances.
Since the transition of Vets-API from EC2 to EKS earlier in this month of April 2023, there is no such thing as Vets-API EC2 instances. Here is a quote from given to the teams in [#eks-migration-support](https://dsva.slack.com/archives/C04M7T1CZAS)

**ARGO CD ACCESS (SOCKS REQUIRED)**

- If your developer workflow involves running commands in rails console (in AWS), you will need to request access to the terminal in ArgoCD (SOCKS needed)
- Follow the instructions in this [template to submit a ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=external-request%2Cplatform-tech-team-support%2Cops-access-request&template=vetsapi-argo-terminal-access.yaml&title=Vets-api+terminal+access+for+%5Bindividual%5D) for access.

Please let me know if you still need AWS access for things other than Vets-API and I will move it forward.
Otherwise, please use the template above to request ArgoCD/EKS terminal access where Vets-API containers are.
Please be assured your time working on this request is not a lost effort as the approval of access you already received is also good for the ArgoCD/EKS terminal access request.

**Comment by considerable** [comment]
Thank you, Joshua! Closing the tkt.
