### ISSUE TITLE
[Analytics MVP] Foresee Thresholds

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#559]
## User Story
As a product decision maker, I need to understand my tool's critical indicators and to know where users are having trouble with my product so that I can iterate my product for successes and errors and improve the veteran experience.

## Goal
Add Foresee data that is readable and relevant to product improvements.

## Acceptance Criteria
- [ ] Determine which Foresee metrics to include
- [ ] Define and add any necessary glossary terms
- [ ] Determine the thresholds where Foresee metrics are critical for the product's health
- [ ] Iterate on Foresee metrics on the current dashboard

## Definition of Done
- [ ] **Attached to a Milestone** 
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team**
- [ ] **Labeled with Practice Area** 
- [ ] **Labeled with Type**

**Comment by joanneesteban** [comment]
First indications:
- Are the thresholds higher or lower than the average CSAT.

**Comment by amycesal** [comment]
Forsee data is in the weekly metrics and with thresholds colored in the monthly metrics, because there's not enough data to be a reasonable indicator in the weekly view. 

<img width="623" alt="Screen Shot 2019-07-16 at 4 09 06 PM" src="https://user-images.githubusercontent.com/1656046/61326129-21070100-a7e4-11e9-9320-2106f8150a97.png">

<img width="612" alt="Screen Shot 2019-07-16 at 4 09 26 PM" src="https://user-images.githubusercontent.com/1656046/61326130-21070100-a7e4-11e9-919a-b4902e7fbfd7.png">
