### ISSUE TITLE
SPIKE: Investigate Feedback Site for Verification Process

### ISSUE THREAD

**Issue by mjconw3** [department-of-veterans-affairs/va.gov-team#55974]
## Description

One of the solutions we want to investigate for in person proofing is the creation of a feedback site for the verification process. We want a tool that allows users to provide feedback for current authentication processes in place that allows us to better our workflow and product.

### Key Questions and Concerns
- can we create an endpoint on va.gov exposed to users through a link
- we need a way to ensure we don't get feedback from people who didn't actually attempt
- security wise we need to ensure we don't collect any PII during the process
- provide help desk folks with the ability to contact the users back about their issues or to inform them we solved the problem
- uuid, email, time date
- Can we conduct a “survey” or gather feedback? What is involved here? 

## Acceptance Criteria

- [ ]

**Comment by charlye-bluetiger** [comment]
**Pain Point:**
As a user who is going through the authentication/verification process, how might I provide feedback?
- Goal:
Highlight areas where users are encountering the biggest issues in order to focus building solutions to alleviate these problems

**Logistics:**

- Who would monitor this feedback?
- What is the process for monitoring the feedback? Resources/bandwidth

Pain Point:
As a user who is going through the authentication/verification process, how might I provide feedback?

Goal:
Highlight areas where users are encountering the biggest issues in order to focus building solutions to alleviate these problems

Logistics:

Who would monitor this feedback?
What is the process for monitoring the feedback? Resources/bandwidth
Considerations

- an endpoint on va.gov exposed to users through a link
- need a way to ensure we don't get feedback from people who didn't actually attempt
- security wise we need to ensure we don't collect any PII during the process
- provide help desk folks with the ability to contact the users back about their issues or to inform them we solved the problem
- uuid, email, time date
- Can we conduct a “survey” or gather feedback? What is involved here?

**Comment by mjconw3** [comment]
@kingbmike Joe wants us to reach out to Sierra from login.gov to see if we can get data/metrics on their contacts us/feedback page

**Comment by mjconw3** [comment]
Login.gov current "feedback page" https://login.gov/contact/

**Comment by APorter-Clarity** [comment]
Related Spike Ticket: [Feedback Endpoint on VA.gov for verification](https://app.zenhub.com/workspaces/identity-5f5bab705a94c9001ba33734/issues/gh/department-of-veterans-affairs/va.gov-team/55906)

**Comment by APorter-Clarity** [comment]
# Meeting with Carrie (GSA)
### Topics:
1. Data on the number of users who report issues around verification and account creation
2. What comments or feedback do they leave, what drop-off rates, and the point in the process it happens

![Screenshot 2023-05-02 at 3.11.20 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/d54ab284-b4cb-446a-8561-463db589ba72)

### Follow up resources or points of interest:
- IPP Dashboard spreadsheet
- Lessons learned
- Qualitative feedback from Rachel
- Tracking and/or noticing a difference in drop-off rates for the IPP flow depending on which agency the user starts the process

The drop off rates for VA compared to RRB. LIG just started reformatting that page of data, not all stats for PBGC are cleaned up yet. Here you can see the rates for VA & RRB are pretty similar
![Screen Shot 2023-05-02 at 2.59.38 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/0befce7c-1052-4058-b32a-f08918b94b72)

Recently aggregated quotes in that spreadsheet (WIP). LIG goal is to have these organized by topic.
![Screen Shot 2023-05-02 at 3.04.49 PM.png](https://images.zenhubusercontent.com/5f3c2079dacb5150d3da9240/b2aa65d4-35fb-4931-9bbe-55c869cf7aea)

**Comment by APorter-Clarity** [comment]
Amanda-Follow Up with Carrie

**Comment by aparsley** [comment]
Thank you for closing.
