### ISSUE TITLE
Create a list of all VA.gov accessibility resources

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#56000]
`Chipper Project`

## CAIA A11ys Assigned

- Sara
- Eli
- Jamie

## Description

As part of the [CAIA accessibility documentation epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55956), we should begin by creating a trackable list of documentation written across the following locations.

Some docs have moved to other folders, while others have moved to the Platform site or Confluence. 

### Identify Document Status
We need to identify the status of each piece of documentation so we can clean it up ... 
#### Status Options
- Current
- Needs updated
- Archive/Remove
- Needs Reviewed
- Consolidate with VA content and remove from GitHub

## Folder Locations & Assignments
- [x] **GitHub Folder**: [Previous a11y team’s shared support](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/shared-support/accessibility) 
    -   **Assigned to:** @eli-oat and @coforma-jamie in Google Sheet 
    - **Google Sheets:** [(`shared support folder` section)](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831&range=H2)
- [x] **GitHub Folder**: [Previous vsa a11y](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/accessibility) 
    - **Assigned to:** @coforma-jamie** in Google Sheet
    - **Google Sheets:** [(`prev. vsa a11y folder` section](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831&range=H3))
-  <del>**GitHub Folder**: [Sitewide content](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/teams/sitewide-content)
    - **Assigned to:** @eli-oat 
    - **Google Sheets:** [(`sitewide content folder` section)](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831&range=H4)</del>
- [x] **Confluence Folder:** [Accessibility community of practice](https://vfs.atlassian.net/wiki/spaces/ACP/overview)  
    - **Assigned to:** @coforma-jamie 
    - **Google Sheets:** [(` Accessibility Community of Practice folder` section)](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831&range=H5)
- [x] **Platform/Governance Folder**: [Platform documentation](https://depo-platform-documentation.scrollhelp.site/)
    - **Assigned to:** @coforma-jamie 
    - **Google Sheets:** [(`Platform Documentation folder` section)](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831&range=H6)
- [x] **GitHub Folder**: [Platform accessibility](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility) - refer to [comments below/linked here ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56000#issuecomment-1493590460) 
    - **Assigned to:** (@sara-amanda)
    - **Google Sheets:** [(`Platform accessibility folder` section)](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831&range=H7)

#### Divide and Conquer
- We recommend working with other a11y specialists in the #a11y-specialist and #accessibility-ops channel.
    - This will help to determine what is up to date or out of date, as some things are historical knowledge.
- **Information we are collecting:** 
    - Location (selected for you)
    - Item Category (drop-down provided)
    - Type | Item Name
    - Notes/Detail/Action Items
    - Link to Item
    - Last Updated
    - Days Since Updated (calc. field)
    - Status (drop-down provided)
    - Comment in Ticket #56000 ([see example here to track your work for your section 📝 ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56000#issuecomment-1493590460))

## Success criteria
- [x] A trackable list of documentation is created from the folders above - [Google Sheet: Accessibility Documentation Audit 2023](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831)
  - Follow the example for ["`Platform accessibility GitHub`" audit in the Google Sheet](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=1462637072). 
      - [Refer to the comments in this ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56000#issuecomment-1493590460)for additional information on this example.
      - The remaining sections unchecked above have tabs created for them in the Google Sheet with the location in Column A already selected.  
        - [ ] Previous a11y team's shared support folder
        - [x] Previous vsa a11y folder
        - [ ] Sitewide content folder
        - [ ] Accessibility community of Practice folder
        - [ ] Platform documentation
        - [x] Platform accessibility guithub

- [ ] Documentation is flagged with the Status Options (using the `status drop-down` in `column I` in the Google Sheets, linked above), in addition to the `category`, etc. 
- [ ] Broken links are identified (use notes column in the Google Sheet, linked above)

**Comment by sara-amanda** [comment]
## Platform Accessibility GitHub
- **Folder Location Path:** [va.gov-team/platform/accessibility/](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility)
- **Status**: Audited
- **Auditor**: Sara
- **Audit Document Used:** [Google Sheet - Accessibility Documentation Audit 2023](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit?usp=sharing)
- **Spreadsheet Inclusions**: Folder location; item category; type; item name; notes/details/action items; link to item; last updated date; automated counter for days since last update (for pulse check on content freshness); status flag. 
- **Note**: _Items with notes that the item moved to the platform site were automatically flagged as "archive/remove" from GH._ 
- **Next Steps:** See below.
### 📈 Audit Distribution Categories
- **508 Accessibility** 9.62% of the audit
- **Archive** 1.92% of the audit
- **Common** **Issues** 9.62% of the audit
- **Guidance/Process** 13.46 % of the audit
- **Meeting Notes** 26.92% of the audit
- **Resources** 23.08% of the audit
- **Testing** 5.77% of the audit
- **User Research** 5.77% of the audit
- **WCAG21** 3.85% of the audit
### 🔎  Audit Findings Overview
- ❌**Archive/Remove** 65.38% of the audit
- ➕**Consolidate with VA Content and Remove from GH** 25% of the audit
- ✅ **Deemed current** 3.85% of the audit
- ⌛**Needs updated** 5.77% of the audit
### 🔍 Audit Findings Category/Status Detail = 52
#### ❌ Archive/Remove = 34  
- 508 Accessibility: 3
- Archive: 1
- Common Issues: 1
- Guidance/Process: 3
- Meeting Notes: 11
- Resources: 8
- Testing: 2
- User Research: 3
- WCAG21: 2
#### ➕ Consolidate with VA Content and Remove from GH = 13
- Common Issues: 3
- Guidance/Process: 3
- Meeting Notes: 3
- Resources: 3
- Testing: 1
#### ✅ Deemed current = 2
- Common Issues 1
- Guidance/Process 1
#### ⌛ Needs updated = 3
- 508 Accessibility	2
- Resources 1

## Next Steps for Platform Accessibility GitHub Content
- Second review needed. 
- [Review date last updated and notes/detail/action items in Google Sheet ](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit?usp=sharing)to assist in review for quality assurance, by someone with historical knowledge and Platform and Design System site knowledge.
- User authorized in GitHub to remove items marked as removed. 
- [Work with CAIA content via ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E), should consolidation items need assistance with content; otherwise, consolidation can take place on Platform and Design System site, if approved by authorized individual.
- **Time estimate to complete next steps:** TBD

**Comment by eli-oat** [comment]
@coforma-jamie [link to spreadsheet where we're collecting these docs](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=328747831).

**Comment by coforma-jamie** [comment]
## Previous VSA Accessibility GitHub
- **Folder Location Path:** [/tree/master/teams/vsa/accessibility/](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsa/accessibility)
- **Status**: Audited
- **Auditor**: Jamie @coforma-jamie
- **Audit Document Used:** [Google Sheet - Accessibility Documentation Audit 2023 - Tab: Previous VSA a11y Folder Audit](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=182846257)
- **Spreadsheet Inclusions**: Folder location; item category; type; item name; notes/details/action items; link to item; last updated date; automated counter for days since last update (for pulse check on content freshness); status flag. 
- **Note**: _Items with notes that the item moved to the platform site were automatically flagged as "archive/remove" from GH._ 
- **Next Steps:** See below.
### Number of Days Since Last Update
- **Average number of days for items audited below:** 572
- **Min days for items audited below:** 4 (9/10/23))
- **Max days for items audited below:** 1245 (4/17/20)

### 📈 Audit Distribution Categories
**Note:** some items are in 2 categories, so this adds up to over 100%.
- **508 Accessibility** 1.6% of the audit
- **A11y Champs** 27.4% of the audit
- **Checklists** 4.8% of the audit
- **Documentation** 1.6% of the audit
- **Guidance/Process** 32.3% of the audit
- **Onboarding** 4.8% of the audit
- **Resources** 11.3% of the audit
- **Templates** 11.3% of the audit
- **Testing** 1.6% of the audit
- **User Research** 21% of the audit
### 🔎  Audit Findings Overview
- ❌ **Archive/Remove** 16.12% of the audit
- ➕ **Consolidate with VA Content and Remove from GH** 3.2% of the audit
- ✅ **Deemed current** 21% of the audit
- 🔁 **Duplicate, review to consolidate** 4.8% of the audit
- 👁️ **Needs reviewed** 24.2% of the audit
- ⌛**Needs updated** 30.6% of the audit
### 🔍 Audit Findings Category/Status Detail = 62
#### ❌ Archive/Remove = 10  
- A11y Champs: 2
- Guidence/Process: 3
- Templates: 3
- Testing: 1
- User Research: 1
#### ➕ Consolidate with VA Content and Remove from GH = 2
- User Research: 2

#### ✅ Deemed current = 13
- A11y Champs: 7
- Checklists: 2
- Resources: 1
- User Research: 3

#### 🔁 Duplicate, Review to Consolidate = 3
- 508 Accessibility: 1
- Documentation: 1
- Guidance/Process: 1

#### 👁️ Needs Reviewed: 13
- Checklists: 1
- Guidance/Process: 13

#### ⌛ Needs updated = 19
- A11y Champs: 8
- Onboarding: 3
- Resources: 1
- User Research: 7

## Next Steps for Platform Accessibility GitHub Content
in progress

**Comment by coforma-jamie** [comment]
## Previous VSA Accessibility GitHub
- **URL:** [https://vfs.atlassian.net/wiki/spaces/ACP/overview](https://vfs.atlassian.net/wiki/spaces/ACP/overview)
- **Status**: Audited
- **Auditor**: Jamie @coforma-jamie
- **Audit Document Used:** [Google Sheet - Accessibility Documentation Audit 2023 - Tab: Accessibility Comm of Practice Confluence Audit](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=737007164)
- **Spreadsheet Inclusions**: Folder location; item category; type; item name; notes/details/action items; link to item; last updated date; automated counter for days since last update (for pulse check on content freshness); status flag. 
- **Next Steps:** See below.
### Number of Days Since Last Update
- **Average number of days for items audited below:** 380
- **Min days for items audited below:** 62 (9/5/23)
- **Max days for items audited below:** 532 (5/23/22)

### 📈 Audit Distribution Categories
- **Common Issues** 50% of the audit
- **Documentation** 50% of the audit

### 🔎  Audit Findings Overview
- ❌ **Archive/Remove** 16.67% of the audit
- ✅ **Deemed current** 33% of the audit
- 👁️ **Needs reviewed** 33% of the audit
- ⌛**Needs updated** 16.67% of the audit
### 🔍 Audit Findings Category/Status Detail = 6
#### ❌ Archive/Remove = 1  
- Documentation: 1


#### ✅ Deemed current = 2
- Current Issues: 1
- Documentation: 1

#### 👁️ Needs Reviewed: 2
- Common Issues: 2

#### ⌛ Needs updated = 1
- Documentation

## Next Steps for Previous Accessibility VSA Content

- Determine who owns this content now that Josh Kim isn't at VA anymore (he created lots of the content, including Google Slides presentations that are linked to).
- Review audit with that content owner.
- User authorized in Confluence (or CAIA/a11y specialists, if authorized user gives permission) to remove items marked as removed.
- [Work with CAIA content via ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E), should review pages as indicated and update.
- Time estimate to complete next steps: TBD

**Comment by coforma-jamie** [comment]
## Shared Support Accessibility GitHub
- **GH Folder:** [teams/shared-support/accessibility](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/shared-support/accessibility)
- **Status**: Audited
- **Auditors**: Jamie, Eli
- **Audit Document Used:** [Google Sheet - Accessibility Documentation Audit 2023 - Tab: E&J Prev. a11y Team's Shared Support Folder Audit](https://docs.google.com/spreadsheets/d/1YsMFmvgD4hEc93KTaTPJwvR5heHsCNgC3cwj53Eu3Ys/edit#gid=667971773)
- **Spreadsheet Inclusions**: Folder location; item category; type; item name; notes/details/action items; link to item; status flag; date late updated. 
- **Note:** The Platform website doesn't include last edited dates. Dates aren't noted in the spreadsheet or in this summary. 
- **Next Steps:** See below.


### 📈 Audit Distribution Categories
- **Audit**	-	43.24% of audit
- **Documentation**	-	18.92% of audit
- **Guidance/Process**	-	5.41% of audit
- **Product Health**	- 10.81% of audit
- **Reports**	-	13.51% of audit
- **User Research**	-	8.11% of audit

### 🔎  Audit Findings Overview
- ❌ **Archive/Remove** 43.24% of the audit
- ➕ **Consolidate with VA Content and Remove from GH** 2.7% of the audit
- 👁️ **Needs reviewed** 48.65% of the audit
- ⌛ **Needs updated** 5.41% of the audit
### 🔍 Audit Findings Category/Status Detail = 37

#### ❌ Archive/Remove = 16
- Audit 11
- Product Health 4
- Reports 1

#### ➕ Consolidate with VA Content and Remove from GH = 1
- Documentation 1

#### ⌛ Needs updated = 2
- Reports 2

#### 👁️ Needs reviewed = 18
- Audit 5
- Documentation 6
- Guidance/Process 2
- Reports 2
- User Research 3

## Next Steps for Shared Support Accessibility GitHub Content
- [ ] Need to determine how to archive old product audits (or, if not archive, what?)
- [ ] CAIA needs to review Shared Support's documentation/process docs to see what we can adapt for our own needs

**Time estimate to complete next steps:** TBD

**Comment by coforma-jamie** [comment]
After reviewing the Sitewide content folder, we determined that there's no accessibility content to inventory there (this is used by the CAIA content team). We've crossed it off the ticket description.
