### ISSUE TITLE
Offer MHV coordinators a login.gov contact they can reach out to when experiencing issues helping veterans set up accounts

### ISSUE THREAD

**Issue by claytonzook** [department-of-veterans-affairs/va.gov-team#56064]
###Description

**In order to** get MHV coordinators more on board with encouraging veterans to create login.gov accounts,

**we need to** offer them tools when they run into issues helping veterans create login.gov accounts

**so that** more veterans successfully sign up for login.gov accounts

MHV coordinators, [in a group interview in 2022](https://docs.google.com/document/d/1FPoKSKnilFT4cNRMYGUYEOTq_EMo_JS1/edit?usp=sharing&ouid=100683926726097655046&rtpof=true&sd=true), mentioned having a contact with ID.me they can reach out to if they experience issue with helping veterans set up an ID.me account. There is room to learn more about what would be most helpful for MHV-Cs and veterans, but an MVP solution could mimic what they have for ID.me - it sounded like essentially a special reporting/ticketing link. After a ticket is created, a live person contacts the veteran rather quickly and helps them complete the task.

This will take cooperation with login.gov since the idea would be for them provide that point of contact

Reach out to Sierra Stewart, Rachel Houghton and Carrie McGrath to discuss the appropriate POCs for this tasking

#### Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented

#### MR Approver
- TBD

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by aparsley** [comment]
LGA is not working on this, we need to get with Sierra to get a contact for this and send to both Treva Lutes and Susan Haidary to pass on.

**Comment by charlye-bluetiger** [comment]
Amanda to reach out to Tyler and subsequently Sofia from LGA to get access to interview video.

**Comment by APorter-Clarity** [comment]
Still no feedback on the initial research surrounding this ticket. Reached out to Tyler and the LGA team to inquire about the past research.

**Comment by APorter-Clarity** [comment]
Still no feedback on the initial research surrounding this ticket. Reached out to Tyler and the LGA team to inquire about the past research.

**Comment by APorter-Clarity** [comment]
[LIG and MHV Sync.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2pGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7359af3312d90e31d6656b992819fae4ac5dcc96/LIG%20and%20MHV%20Sync.pdf)

**Comment by APorter-Clarity** [comment]
##  | 

Attendees:     


### Notes



* MHV Coordinators are able to reach out to the VA contact center team and Rachel Houghton. 
    * Contact for MHV side to talk to
    * Rachel Houghton and CC’d Sierra 
* Sierra is able to provide a graphic on what LIG can do. (Benefits from LIG)


### Action Items



*  Amanda to find out:
    * **Who the MHV coordinator is working with on ID.ME?**
        * In the interview, participants did not specify who that phone support was coming from. They referenced the number of workstations so it’s possible that they are going through a support number and being connected to other agents/support staff. 
    * **How many people?**
        * In the interview, they reference 8 workstations
    * **What exactly are they able to do on the ID.ME side (legal, can not change things to user accounts)**
        * There was not enough information to specify whether or not ID.ME support staff is changing anything on behalf of the Veterans. Rather, they are helping the MHV Coordinators link the Veteran to someone who can help them within the ID.ME system which they [the coordinator] do not have access to.




### Key Findings:



1. **Preference for Phone Support:** VA/MHV employees expressed a strong preference for credential providers that offer phone support. They noted that most veterans are more comfortable speaking to a live person over the phone rather than using chat-based support. 
    1. “Most of our veterans aren't gonna want to do this on a chat box, they wanna call somebody and talk to a person.”- MM
2. **Positive Perception of ID.ME:** VA/MHV employees reported that they recommend veterans set up an ID.ME account because it offers phone support. They mentioned that  with Login.gov they provide a write up and Login.gov is left to contact the Veteran. 
    2. …“you don't have a customer support number that we were hoping for, but ID dot me finally gave us what they have like 8 workstations now. So, we do have an ID.Me phone support, but we don't have one for login.gov; it's only something that you would write, and then you guys contact them. ”- RDW
3. **Desire for Warm Handoff:** VA/MHV employees expressed a desire for a more seamless support experience, suggesting the possibility of a "warm handoff" from VA/MHV to the credential provider's support team. This would involve VA/MHV employees directly connecting veterans to Login.gov support personnel to address any issues or queries. 
    3. “It would be nice if we could do a warm handoff.”- AW
