### ISSUE TITLE
Adding Rockwell Rice to DSVA Slack

### ISSUE THREAD

**Issue by huggins-va** [department-of-veterans-affairs/va.gov-team#56126]
Good morning,

Please add Rockwell Rice as a multi-user channel to these channels: team-banana-peels and api-benefits-claims
Email: rockwell.rice@oddball.io

Thank you!

**Comment by LEHigley** [comment]
do not have access to either of those; invited and added to general to start

**Comment by KevinMHoffmanUSDS** [comment]
@rockwellwindsor-va @huggins-va Can you confirm that both of these channels exist within the DSVA Slack? I'm not seeing these channels either. If they are private channels, there would be no way for an Slack admin to see them, however someone in the channels can invite you.

**Comment by rockwellwindsor-va** [comment]
I cannot, I only see the general channel.

**Comment by rockwellwindsor-va** [comment]
I cannot, I only see the general channel

**Comment by KevinMHoffmanUSDS** [comment]
@rockwellwindsor-va Advise you to have someone in those channels invite you to them; only members of private channels can do that. Simply ask them to type /invite and your username in that channel. Let us know if that resolves your issue.

**Comment by FonzMP** [comment]
I think there's a bit of confusion here.....

looks like Rockwell is only listed as a "Single-Channel Guest" in DSVA Slack. This is limiting his ability to see and join many of the public channels. Can we have his role in DSVA slack updated from Single-Channel Guest to the recommended multi-user above?

The channels requested in the original comment are actually part of the Lighthouse Slack instance, so I think that's why you all are thinking they're private. There may be a connection between the two Slack instances but I'm not sure exactly how that works?

Thanks all

**Comment by dabaranowski** [comment]
To add some color to what Alex provided above - Rockwell is not able to access [this thread](https://dsva.slack.com/archives/CBU0KDSB1/p1688135543448299), which is in a public channel (#vfs-platform-support). I can see him listed in the members of that channel, but despite that he is not able to access the thread.
