### ISSUE TITLE
Verify frontend communicates with backend over pod local network

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#56150]
# Description
We need to test and verify that the frontend of our preview environment successfully communicates with the backend container in its pod. How might we configure the frontend to communicate over the network instead of trying localhost?

`vets-api` Dockerfile is [here](https://github.com/department-of-veterans-affairs/vets-api/blob/master/Dockerfile-k8s)

Explanation of backend image research and design: [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2490761493/Vets-API+Docker+Image)

Example manifest with pod annotations: [here ](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/preview-environment/dev/pe-envs/vets-website-test-ecr-docker-values.yaml
)

Preview Environment Deployment Workflow: [link](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/preview_environment_deployment.yml)

List of values files to deploy as individual apps within the app of apps: [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/preview-environment/dev/argocd-apps/values.yaml)

Helm chart that tells ArgoCD where to look for the list of values files: [here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/preview-environment/dev/argocd-apps/templates/apps.yaml)

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/fd799e72-26bb-47a0-97b0-51ab14e8eff8)

![image.png](https://images.zenhubusercontent.com/5d2633e0a6db635dbcbaf8d5/9ba537a5-8b58-415f-a789-503ac23d1336)

Cyril's description of the ArgoCD setup: [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2449965057/ArgoCD+configuration+to+read+app+manifest+changes+and+deploy)

Frontend image create scenarios: [here](https://vfs.atlassian.net/wiki/spaces/TT4/pages/2546630657/FE+Image+Scenarios)

# Acceptance Criteria
- [ ] A spike PE configuration that contains the `vets-api` EKS migration version of the backend is deployed by ArgoCD in our Preview Environment app of apps
- [ ] Network requests from the frontend container are able to reach the backend container

**Comment by holdenhinkle** [comment]
Lots of digging through the code and pairing yesterday. Resulted in this PR at EOD - https://github.com/department-of-veterans-affairs/vets-website/pull/23857

This should address the problem with vets-website not communicating with vets-api a preview instance pod. Or at least part of the problem.

**Comment by pjhill** [comment]
The above PR did not resolve the issue. Per Cyril we now know a couple important things --
1. It is not considered best practice to strongly couple the FE and BE into a single pod
2. We can use name spaces and service names instead

Cyril is currently working on creating a PR to pivot the PE creation to use service names.

**Comment by JoeTice** [comment]
This issue may be closed pending progress on some of Cyril's work

**Comment by holdenhinkle** [comment]
Cyril, Hector and I paired on this today. Curt and Gia joined in too.

The deployment files for preview instances were a complete mess.

The `vets-website` service in `preview-environment.yaml` was using the `couchdb` image (I'm not even sure if that's a valid image) even though couchdb isn't used for va.gov. The `containerPort` value was also wrong for `vets-website`. There was also other 'junk' in the file. Probably a copy/paste issue or a file that was used as a template wasn't cleaned up.

Cyril merged a PR to update the `vets-website` service - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1754

I created a PR to clean up the file - https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1755

There's an issue with the Redis image being able to be pulled so Hector is finding out if we're allowed to store it in EKS.

We decided to put vets-website, vets-api, postgres, and redis in the same pod instead of putting vets-website and vets-api in separate pods.

I'm guessing we'll have this done tomorrow.

**Comment by cyriltech** [comment]
I have updated the manifest file to pull Redis and Postgres images from our ECR repository. https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1761The two images are being pull successfully and containers looks good. However, vets-api image is![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/c97e25c6-9031-44f3-bdfe-6fe99ebd0a38)![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/45f4d2a9-4245-4033-aac0-7523f9513a59)![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/ab58e6fb-0205-4b7d-8f2f-5e3717c06af8) crashing. I am pulling vets-api image locally to run a test and see how it behaves locally.

**Comment by cyriltech** [comment]
Updating manifest file for vets-website that lives in the same pod as vets-api to have routing from the internet. https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1783

**Comment by holdenhinkle** [comment]
I [merged a PR yesterday](https://github.com/department-of-veterans-affairs/vets-website/pull/23923) that will hopefully/maybe tell vets-website to send requests to vets-api over localhost:3000 (edited)

**Comment by cyriltech** [comment]
The issue we are facing right now, is with vets-api not being able to start. I pulled the image from ecr and try it on my local. Ran into issues.
Build a new version of vets-api image then replace it in the docker compose file and things worked fine. I pushed that image to ECR, next thing is to ref it on our manifest file [PR](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/1808)

**Comment by cyriltech** [comment]
tested preview-environment deployment file on minikube environment in my local and everything worked fine. Vets-website, vets-api, postgress and redis all connected.  I was also able to hit localhost 3000 and saw the welcome to vets-api page. Tried to replicate same deployment within preview-environment and got an error with vets-api conatiner that is related to the CMD command bundle exec.

**Comment by JoeTice** [comment]
@cyriltech @holdenhinkle - it sounds to me like this is working locally, but not in the environment we care about yet - moving this out of Review and back to In Progress until resolved.

**Comment by holdenhinkle** [comment]
`bundle exec` is a command used in Ruby projects that have dependencies managed by Bundler. Bundler is a popular dependency manager in the Ruby ecosystem, which helps manage and install the required gems (libraries) for a project based on the specified version constraints in the `Gemfile`.

The `bundle exec` command ensures that the subsequent command is run within the context of the current project's bundled environment, using the versions of the gems specified in the `Gemfile.lock`. This helps maintain consistency and avoid conflicts between different versions of the gems installed on the system and those required by the project.

In the context of your statement, the error with the `vets-api` container is related to the `CMD` command `bundle exec`. This implies that there may be an issue with the execution of the command within the container, possibly due to incorrect configuration, missing dependencies, or issues with the container environment.

To troubleshoot the issue, you may want to examine the logs of the `vets-api` container to get more details about the error, ensure that all required gems are correctly installed, and verify that the container environment is set up properly for running the Ruby application.

**Comment by pjhill** [comment]
To be clear, it was originally intended to merge the Dockerfiles when the k8s migration was completed. The history is explained a bit in the PR [here](https://github.com/department-of-veterans-affairs/vets-api/pull/11757/files).

**Comment by cyriltech** [comment]
Update so far on this:-
Trying to mimic the working production version of the vets-api and once it is running in Dev Env, will combine all those changes of manifest in repository and push them to preview-environment infra repository
Currently I'm blocked on this error of vet-api-web image , though was able to combine all the envs and  other config files successfully to the dev env in the test namespace..
"W, [2023-04-24T20:45:07.531854 #1]  WARN -- ddtrace: [ddtrace] Profiling was requested but is not supported, profiling disabled: Your ddtrace installation is missing support for the Continuous Profiler because the `pkg-config` system tool is missing. This issue can usually be fixed by installing one of the following: the `pkg-config` package on Homebrew and Debian/Ubuntu-based Linux; the `pkgconf` package on Arch and Alpine-based Linux; the `pkgconf-pkg-config` package on Fedora/Red Hat-based Linux. (Tip: When fixing this, ensure `pkg-config` is installed **before** running `bundle install`, and remember to clear any installed gems cache). For help solving this issue, please contact Datadog support at <https://docs.datadoghq.com/help/>. You can also check out the Continuous Profiler troubleshooting page at <https://dtdg.co/ruby-profiler-troubleshooting>."![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/80f3dfe2-56d2-49e5-b612-3f32ec823c13)

**Comment by JoeTice** [comment]
Sprint 25 Update - In Progress, work will continue in Sprint 26. We are working with Eric and Lindsey to help us determine what needs to happen to get this resolved

**Comment by cyriltech** [comment]
Update --04/26/2023
using helm install I am able to replicate eks migration's teamwork for vets-api deployment in a test namespace. All containers came up running. Tried severally to integrate this with preview-environment values file kept getting warnings and errors.
 Now, I am modifying the 2400-line code to add to the preview-environment values file.

**Comment by pjhill** [comment]
Summary of the current problem --
Custom `vets-api` configurations are defined in the `watch` script for `vets-website`. But, we are serving up our frontend from the `content-build` web server. If we define a custom API URl in `vets-website` it will not be used. Additionally, we are using `yarn serve` to start the `content-build` web server because the watch command will automatically build `content-build` since we are using a cached build.

The fix will probably be either --
1. Create a custom preview environment watch script that excludes all or part of the build process for `content-build`
2. Reconfigure the local deployment process to allow us to use `vets-website` to serve up the `content-build` contents as well

**Comment by cyriltech** [comment]
Issue is fixed for vets-api deployment to argocd, now the deployment is there for vets api and frontend with everything working, I also tested the connection from frontend pod to the vets api backend pod, also attaching the screenshot below, Now frontend should be able to use that endpoint to call it.  Next step is to have a call with frontend and configure it  to send the request to vets-api endpoint.![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/bb6eaa05-905a-461a-a7c9-74948e141bb5)![image.png](https://images.zenhubusercontent.com/6385292bddbc0cbb14b84a51/1b3c0c4e-fb7a-4766-9335-bc6c113ce86e)
