### ISSUE TITLE
Update HTML div 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#56282]
## Description
During our staging review for Appointment List Redesign feature, the collab cycle team detected the first column in each row has an `aria-label` that has an invalid attribute for div elements.

[Reference collab cycle staging ticket 55851](https://app.zenhub.com/workspaces/vaos-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/55851)

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [ ] The `div` element will be replaced with `<span class="sr-only">`

### Technical Specs

- [ ] 

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by outerpress** [comment]
@vbahinwillit the staging review ticket has this note:

>The first column in each row has an aria-label providing screen-reader-friendly date-time information. aria-label isn't a valid attribute for div elements.

Looking at that, I'm still seeing a `div` instead of a `span` in the first column of each row:

`<div class="vads-u-flex--1 vads-u-padding-top--0 vads-u-flex--auto xsmall-screen:vads-u-padding-top--1 medium-screen:vads-u-padding-y--0" aria-label=" appointment on Wednesday, January 31 8:00 a.m., Mountain time" style="text-decoration: none;">`

That said, I think the fix you did for this is still valid since aria-label isn't valid for divs. The above code just needs to be changed too.

FYI @ldelacosta

**Comment by vbahinwillit** [comment]
I will take a look. The empty id is actual handling the onClick and onKeyDown events. The code looks like this:

`<AppointmentListItem key={`${key}-${j + 1}`} id={appt.id} className="vaos-appts__listItem--clickable">
  <AppointmentFlexGrid idClickable={idClickable} link={link} className="vaos-appts__column-gap--2">
     <AppointmentRow></AppointmentRow>
  </AppointmentFlexGrid>
</AppointmentListItem>
`

I will look at removing the AppointmentFlexGrid abstraction a placing the handlers on the 'li'.

**Comment by vbahinwillit** [comment]
Actually, moving the click handlers to the 'li' is a problem too! Ugh. [jsx-a11y/no-noninteractive-element-interactions](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/db64898fa591f17827053ad3c2ddeafdf7297dd6/docs/rules/no-noninteractive-element-interactions.md). Not sure how to proceed on this.

**Comment by outerpress** [comment]
@briandeconinck any advice on this?

**Comment by briandeconinck** [comment]
Sorry for missing this last week! My staging review ticket wasn't super clear -- the `div` doesn't need to be removed, just the `aria-label` on the `div`. Then a `<span class="sr-only">` inside the `div` can give screen reader users all of the necessary context.

Looking at @vbahinwillit's PR, I think that should be a sufficient fix. Still worth double-checking with a screen reader but that looks good to me.

**Comment by outerpress** [comment]
@briandeconinck @vbahinwillit  I just took a look with two screenreaders:
- VO on Chrome: Reads the label as expected
- TalkBack on Android/Pixel 7: Skips over all date info.

So it's not working on TalkBack yet. I'll see if I can get a screen recording. Any other browser/screenreader combos I should try?

**Comment by briandeconinck** [comment]
Hm, that's unexpected TalkBack behavior. If the `aria-label` is still on the `div`, my gut feeling is that's probably what's confusing TalkBack. Can you share a code sample of the rendered HTML?

> Any other browser/screenreader combos I should try?

If possible, it would be great if you could also test with:
- VoiceOver + Safari on Mac
- NVDA + Firefox on Windows

If you don't have access to a Windows machine for testing, I'm happy to take a look if you can set me up with a test user.

**Comment by outerpress** [comment]
@briandeconinck here's the VO on Safari test, it's working as expected.

https://user-images.githubusercontent.com/2536801/234127787-eebd1c00-7653-43e6-9be1-e41c07d643ea.mov

**Comment by joshkimux** [comment]
@outerpress I got tagged in by @briandeconinck as he's out on kid sick leave ❤️ 

Reviewing this video and the code, while things are indeed reading out (thanks to the power of the `aria-label`, there are some sneaky issues that remain (and will likely persist unless we can rely on semantic HTML here).

**Specifically:**
- Placing an `aria-label` on a div will cause some screen readers to treat it as a group. I _think_ what's happening here is the `aria-label` on that div is resulting in the screen reader announcing out all the content as a group (which this is not semantically). Around `:47` you'll hear "end of, primary care, group" which is an issue as:
  - Primary care is not a group, but is being announced as one (semantics)
  - Because it's being announced as a group, there are two extra "stops" in the experience. Instead of "Primary care, group, -> Primary care -> End of, primary care, group," this should only be "Primary care"

A larger issue, which Brian may have mentioned already, is hiding the `h3` here using `aria-hidden`, as it may no longer appear in the rotor or elements list as a quick navigation item. That may be a critical issue to look into (if it hasn't already).

After reviewing with @AngelaFowler82 , I think our ideal recommendation would be to revisit how the code is written where it doesn't need to rely on a `div` or even `sr-only` text. 

## For example, at its semantic base (without CSS), we'd love for it to look like this:

```html
<h2>May 2023</h2>
  <h3>5 Friday</h3>
    <h4>2:50 p.m. MT Primary Care</h4>
      <p>At Cheyenne VA Medical Center</p>
      <p>Details</p>
    <h4>3:10 p.m. MT Secondary Care</h4>
      <p>At Cheyenne VA Medical Center</p>
      <a>Details</a>
  <h3>8 Monday</h3>

etc etc
```

Which, to visualize in markdown, would feel like this to a screen reader user

> ## May 2023
> ### 5 Friday
> #### 2:50 p.m. MT Primary care
> At Cheyenne VA Medical Center
> [Details](https://www.va.gov/)
> #### 3:10 p.m. MT Secondary Care
> At Cheyenne VA Medical Center
> [Details](https://www.va.gov/)

Doing so will give screen reader users access to valuable shortcuts through headings, and ensure that even without styling it will be readable. We can progressively enhance this using embedded `span` elements for styling, or using `aria-describedby` to get creative with how we attach details together (e.g. connecting "Friday" with 5).

## On the flip side, the current semantic base looks like this:

```html
<h2>May 2023</h2>
  <h3 aria-hidden="true">5</h3>
    <span aria-hidden="true">Fri</span>
```

Which, to visualize in markdown, would feel like this to a screen reader user

> ## May 2023
> appointment on Friday, June 5 2:50 p.m., Mountain time at cheyenne VA medical center details for in person appointment on Friday, June 5 2:50pm, Mountain time
> appointment on Friday, June 5 3:10 p.m., Mountain time at cheyenne VA medical center details for in person appointment on Friday, June 5 3:10pm, Mountain time

But minus quick navigation by headings, which are critical for screen reader navigation [(~70% start with headings)](https://webaim.org/projects/screenreadersurvey9/).

## Next steps
It may be helpful if we could pair up one of our a11y specialists with one of y'alls engineers to work on the semantic HTML bit a little more. We'd be able to understand y'alls constraints a little bit more that way, and could figure out the next best step forward.

**Comment by AngelaFowler82** [comment]
Another thing to consider: ARIA-Label allows a specific label to be attached to an elament.Since we are pulling data from elsewhere, it is better to use ARIA-describedby to link the element to the label.

**Comment by outerpress** [comment]
@ldelacosta as discussed IRL the issue surfaced here requires revisiting our semantic structure so we'll need to do some work on the design side to make some improvements to benefit screenreader users:
* Identify clearer heading structure
* Reduce some of the group noise

I captured that work in UX ticket #57827. We'll plan for those changes to be worked on after the current state is released. 

Given that I think you can close this ticket out.

**Comment by ldelacosta** [comment]
A new ticket will be created post-launch for Appointment list.
