### ISSUE TITLE
Sitewide Content from Debt Resolution Team (Financial Status Report form)

### ISSUE THREAD

**Issue by mgleo** [department-of-veterans-affairs/va.gov-team#56447]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*

- We are adding an Empty state page as well as several Error state pages to the FSR when the user either does not have overpayments/copays or the system is unable to find their overpayments/copays. We are also updating this information on the Debt Portal. Jill Anderson has confirmed contact info.   - [#55028](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55028#issuecomment-1485500190) 
- The language surrounding debt/overpayments/copays has recently changed and we want to ensure that we're on the right track.

- We are also updating the Resolution Option pages to repeat information from the previous page and confirm their selection.   - [#55877](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55877): See After for Resolution Options, Waiver, Monthly Payments, Compromise

- Review minor copy tweaks: https://github.com/department-of-veterans-affairs/vets-website/pull/23727 and [here #56802](https://github.com/department-of-veterans-affairs/va.gov-team/issues/56802)

- We are using the terms "waiver" and "debt forgiveness" interchangeably, but this might not be intuitive to everyone. It does not seem like there is a standard, and we are wondering what would make most sense from a comprehension standpoint? Could we add "waiver (debt forgiveness)" in all the places where we are saying "waiver"? 
Page examples: 
https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd/p/4C744A5D-6A37-4BB8-852B-551F8D9DCE3E/canvas
https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd/p/391D625D-3115-4595-BA31-ACF92E5E6AEC/canvas

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  May, 2023
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [FSR Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/Debt%20Resolution/fsr_enhancements/product_outline.md)
- Link to or attach user flows:
- Link to prototype or mockups:

Full FSR Form: 
- [Staging link (user 228)](https://staging.va.gov/manage-va-debt/request-debt-help-form-5655/)
- [UXPin Prototype](https://preview.uxpin.com/f43733391f52c409c4d3152e9a4b101a392e29df#/pages/161460688)

  - [**Empty and Endpoint Failure**](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55028#issuecomment-1485500190) Empty state: No Overpayments or Copays, Error state: Overpayments and Copays, Error state: Overpayments, Error state: Copay bills
  - [**Resolution Options**](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55877): See After for Resolution Options, Waiver, Monthly Payments, Compromise

- Link to any epics/issues that may be helpful:
  - [[FSR] Empty and endpoint failure designs #55028](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55028)
  - [[eFSR] Updates to resolution options to repeat amount of debt #55877](https://app.zenhub.com/workspaces/vsa---debt-607736a6c8b7e2001084e3ab/issues/gh/department-of-veterans-affairs/va.gov-team/55877)
## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: May, 2023
- Estimated staging review date: May 2023
- Content, Accessibility, and IA work needed by: April, 2023 ahead of user research

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed 
Spoke to Danielle about this on 04/06

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Debt Resolution
-	OCTO-DE product owner: Matt Self
-	Product manager: Denise Coveyduc
-	Designer: Megan Gayle, Joseph Lee
-	FE engineer: Andrew Rodiek
-	Product/team Slack channel: Debt Resolution #benefits-debt-resolution

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by mgleo** [comment]
The [Financial Status Report](https://www.va.gov/manage-va-debt/request-debt-help-form-5655/) form covers the following:

- **Overpayments** on VA disability compensation, education, or pension benefit 
- VA health care **copay** bills

**Comment by HeatherRienks** [comment]
Following :)

**Comment by charlottecesana** [comment]
I added a question about "waiver" and "debt forgiveness" being used interchangeably. We are wondering what makes most sense from a comprehension standpoint.

**Comment by laurwill** [comment]
Hi @mgleo @charlottecesana , 
We have a few notes and questions about the "waiver" vs "debt forgiveness" item here. 
- The [payments and debts section](https://design.va.gov/content-style-guide/specific-topics-and-programs/payments-and-debts) of the style guide uses "waiver" for this type of debt relief — it doesn't use "debt forgiveness." So this content should use "waiver" throughout to align with the style guide. Changing between 2 terms could make people think these are 2 different types of debt relief.
- I didn't see instances of these terms being used interchangeably in the artifacts linked above — could you point us to some examples? 
- Is "debt forgiveness" in new content for testing, or is that term currently in production in the tool?
- What prompted the shift to use "debt forgiveness"? Did previous testing show confusion around the word "waiver"? 

Thank you! And let me know if you'd like to sync to discuss!

**Comment by jennymayoco** [comment]
Hey @mgleo @josephrlee - We have a couple of additional questions about the designs here as well

- I noticed some designs include (VA form 5655) in the breadcrumb, while others do not. Since there was previous IA done for this form, can you confirm if there are plans to update the breadcrumb in the live page?
- Will a "get started" button be added to live page as well? I didn't come across it in the current VA pages, but came across it in the mock-ups.

I will be OOO 4/28 - 5/9. If you have any questions, please tag @kristinoletmuskat. Thanks! 

CC @mnorthuis for visibility

**Comment by mgleo** [comment]
Hi @laurwill, 

It appears as _**debt forgiveness (waiver)**_ on both our mockups and production on the Resolution section. I'm seeing it only referred to as a waiver on the Review pages. @charlottecesana can you add anywhere else you may be seeing them used interchangeably? 
I do not know about any research regarding the term debt forgiveness but I did find a conversation with VHA SME, David Adcock, [that references both debt forgiveness and waiver](https://github.com/department-of-veterans-affairs/va.gov-team/blob/8d51c8e4549c6b17558c76a3125eafd6a5e2e767/products/combined_fsr/research/sme-interviews/05102022-sme-interview.md). This may be why it is written that way on the FSR. 

Hi @jennymayoco, 

- This is the following info we received from Mikki and Danielle. The breadcrumb will eventually read "Request financial help (VA Form 5655)".
> Note: In the new IA that we haven't implemented yet, there is another static page for "Request help with VA debt for overpayments and bills" (breadcrumb would be "Request help with VA debt") that explains all ways to request help for different types of debt (deprecating the wizard). Then, this page title would become "Request financial help (VA Form 5655)."
> 
> Breadcrumbs would be:
> 
> Manage your VA debt > Request help with VA debt > Request financial help (VA Form 5655)
> 
> But for now, the H1 of this page needs to do the work of "overpayments and copay bills."

- There is a "Start your request now" action link on both the mockups as well as production. This should appear on the intro page with the steps.

cc @charlottecesana @josephrlee

**Comment by laurwill** [comment]
Hi @mgleo , thank you for this context! From the VHA SME notes you linked:
- "Waiver" and "debt forgiveness" aren't interchangeable. Debt forgiveness is a type of relief with 2 subtypes: waivers and write-offs. 
- VHA wants to simplify the request so that Veterans don't need to know the difference between a waiver and a write-off.

I'm not sure of the history here, but we can work with you to get the FSR and the style guide back in sync.

**A few follow-up questions:**
- Does "write-off" appear as an option anywhere in the online FSR? 
- When a Veteran requests "debt forgiveness" in the FSR, does VA only consider waivers? Or do they consider write-offs and waivers? 
- Do you know if/when there was a decision to start treating waiver and debt forgiveness as synonyms and drop the concept of "write-offs" altogether?

We need to use 1 term consistently, and before combining as "waiver (debt forgiveness)," we'll want to loop in @DanielleThierryUSDSVA to understand the style guide considerations here. She's OOO today and traveling next week, but I'll try to connect with her on this. 

Would a quick sync be helpful in the meantime?

**Comment by mgleo** [comment]
> Does "write-off" appear as an option anywhere in the online FSR?

It doesn't. The SME interview doc mentions: "David doesn't want to ask the Veteran to determine the difference"
> When a Veteran requests "debt forgiveness" in the FSR, does VA only consider waivers? Or do they consider write-offs and waivers?

I think once the Veteran selects "debt forgiveness (waiver)" it is up to the VHA to consider either a waiver or a write-off. According to the SME interview doc: "A Veteran shouldn't have to choose if they need a write-off or waiver It's a technicality within VHA regulations"
> Do you know if/when there was a decision to start treating waiver and debt forgiveness as synonyms and drop the concept of "write-offs" altogether?

I'm not aware of the history but I wonder if this is a compromise between VHA who wanted to use the term "debt forgiveness" and the style guide that uses the term "waiver".

I'll be OOO next week (back 5/8) but @charlottecesana and @josephrlee will be available.

**Comment by kristinoletmuskat** [comment]
Hey @mgleo, popping in while Jenny is out to give one more piece of feedback on the error message. 

![Screenshot of proposed error messages for overpayments](https://user-images.githubusercontent.com/122126772/235516429-e9dd60e8-9306-4aed-903f-40e379a2146b.png)

We noticed that these error states are for what looks like system issues, but we are offering that the user call the helpdesk. It seems like the helpdesk maybe wont be able to help if it's just a system issue -- is it worth including the helpdesk number there if they wont be able to support?

And similarly for the error message, could we clarify what "soon" means for the user? Ex: check back in 1 hr, 1 day, etc.

**Comment by laurwill** [comment]
Hi @mgleo ,
Thanks for the context around “debt forgiveness.” Here’s our remaining content feedback for this intake ticket. @charlottecesana @josephrlee, if you'd like to chat about any of these items this week or next week when Megan is back, just let us know!

**Waiver vs. debt forgiveness**
I connected with Danielle on the waiver/forgiveness question and also did updated SEO research to confirm which terms Veterans are searching for. 
- “Waiver," "debt waiver," and "debt relief" have significantly higher search volume than "debt forgiveness" on VA.gov site search. And "VA debt waiver" and “VA debt relief” have higher volume than "VA debt forgiveness" in Semrush keyword research.
- Based on this data, we should use "waiver" consistently for this specific option and “debt relief” as the overall category for waivers, write-offs, compromises, and payment plans. These are the terms Veterans are more likely to use and search for. If we get feedback that there's confusion around waivers, we can revisit adding a parenthetical definition. 
- We shouldn't start defining waiver as "waiver (debt forgiveness)" because it's not clear these are synonyms. (Danielle has a question out to VHA SMEs about whether "write-off" is a term that's currently used on the health care side. As far as we know, debt forgiveness also includes write-offs. We can revisit this when we hear back from those SMEs.)
- We can continue to define waiver using a full sentence like "If we approve your request, we'll forgive (or "waive") the debt." 
- Some screens currently say "we'll stop collection on and forgive (or "waive") the debt." Is the “stop collection” piece needed here? If so, suggest removing “on” to make this easier to read — “we’ll stop collection and forgive (or “waive”) the debt.”

**Other items**
I noticed 2 other style items as I was reviewing:
- Offsets vs. repayment plans: Style guide lists “monthly offset” and “repayment plan” as 2 distinct relief options. It seems the FSR combines these 2 options under “extended monthly payment plan." When a Veteran chooses “extended monthly payment plan” in the FSR, is there another step to choose an offset vs repayment?
- I added some comments to the linked [“Wizard - All terminus”](https://www.sketch.com/s/79aa4a84-fef1-4c06-9495-e0431a6390bd/a/YGbvgAd) screen related to decision reviews vs appeals. 

**Minor copy tweaks**
- Minor changes noted in these 2 tickets look good: department-of-veterans-affairs/vets-website#23727 and here #56802
- The only note is to make "waiver" the consistent term throughout

**Errors**
For the errors in #55028, I chatted with Kristin about her previous comment above:
- Suggest removing "please" in “please check back soon." Our error style is moving away from “please.” If there's a specific time frame when we think the error will resolve, we can add it here. If not, "Check back soon" is okay.
- We’re assuming that the 2 help numbers (debt resolution center and health resource center) can help Veterans find info on their debts another way while this system error is happening. Is that correct?

**Repeating debt amount** 
For the change in #55877:
- Placing the dollar amount directly after the colon makes it hard to read (especially when it’s followed by more numbers like Post-9/11)
- Suggest placing the dollar amount on a separate line below this “Debt 1 of 3:” header. Do you already have a field label elsewhere in the tool for the debt amount? We should align with any existing label. If not, it can say “Amount of this debt: $9,525” or something similar.

**Comment by josephrlee** [comment]
@laurwill, thanks for the detailed feedback! We appreciate it. We'll work on getting the feedback incorporated into the eFSR now. We'll let you know if we have any more follow-up questions. 

cc: @charlottecesana @mgleo

**Comment by charlottecesana** [comment]
Hi @laurwill, thank you for this in-depth analysis and your recommendation on the specificity of the resolution options! 

- We will plan to use "waiver" and not "debt forgiveness"
- "Debt relief" will be used as the overall category
-  Please let us know when you hear back from the S.M.E.s regarding "write-offs". I don't believe this is used in the form. 

> Some screens currently say "we'll stop collection on and forgive (or "waive") the debt." Is the “stop collection” piece needed here? If so, suggest removing “on” to make this easier to read — “we’ll stop collection and forgive (or “waive”) the debt.” 

- I have asked Jill from DMC and will follow up

> Offsets vs. repayment plans: Style guide lists “monthly offset” and “repayment plan” as 2 distinct relief options. It seems the FSR combines these 2 options under “extended monthly payment plan." When a Veteran chooses “extended monthly payment plan” in the FSR, is there another step to choose an offset vs repayment?

- I have asked Jill about this too. Currently, there is not an additional step to choose an offset vs repayment.

**Comment by josephrlee** [comment]
@laurwill, I have a follow-up question for you! 

I saw a question on the intake form about the incremental release that platform would have more details about the react content widget. I chatted with my team and learned that we plan on an incremental release. Can you please elaborate on those details? 

<img width="857" alt="Screenshot 2023-05-10 at 11 20 19 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/ba7b3f5c-739e-45dd-8a02-209b2947fbd3">

**Comment by josephrlee** [comment]
@laurawill, I have one more follow-up question regarding the subtitle of the form.

There are a couple of inconsistencies right now based on whether you're in the wizard or in the form. 

I think they should probably all be the same, right?

Here are the variations: 

The wizard reads **Equal to VA Form 5655 (Financial Status Report)**: 
<img width="1211" alt="Screenshot 2023-05-16 at 1 06 39 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/eccf7e26-45e4-4a8c-ab40-7862069a68ec">
<br/>
The form reads **Financial Status Report**:
<img width="1162" alt="Screenshot 2023-05-16 at 1 06 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/1dd7a2ea-4bdc-48d6-828f-09a6413c5fc5">


This is what I have in Sketch and think this is what it should be: **Financial Status Report (VA Form 5655)**: 
<img width="1280" alt="Screenshot 2023-05-16 at 1 08 51 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/1631062/f122e7af-e1c5-4b1a-b073-429c9ea7a4f5">

What do you think?

**Comment by HeatherRienks** [comment]
Discussed with @josephrlee  and we've already made changes to all the content updates/recommendations from this ticket. Closing out!
