### ISSUE TITLE
Analytics Implementation or QA Support for VAOS

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5680]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Onboarding
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- This request is for Analytics implementation for the VA Online Scheduling tool. 
- @markgreenburg is the PM.
- Slack Channel is #vaos-team
- Tool root is https://www.va.gov/health-care/schedule-view-va-appointments/appointments and need all subroutes to also work in Analytics
- There is NO PII in the URLs or title tag
- Launch will start mid to late Feb at small scale and incrementally ratchet up opt-in percentage from there (based on Analytics performance)

## Interactions
- Need page stats to work
- Need custom events implemented by the VAOS FE team to work
- The FE team has already implemented some custom events but they currently don't work until VAOS is configured in Analytics:
    - How many people click on 'schedule a new appointment' button from homepage
    - Did they select VA appt type or CC appt type
    - Did they go down the self-schedule or request route
    - Were they successful in submitting their appointment or request?

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
- An up-to-date list of routes can be found [here](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/vaos/routes.jsx)
 
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    - Also want to track which type of care was selected on the typeOfCare page (there is a list of radios).

- Sample Users when authentication is required

    - Can provide test account upon request.

- Additional Comments
We are generally comfortable implementing event tracking but would like help in getting tags set up properly for the app as well as ensuring that whatever makes it into the dataLayer actually gets into analytics.
> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by nedierecel** [comment]
Thanks @markgreenburg Confirming I see this and will reach out to you via Slack for test users. 

CC: @jonwehausen

**Comment by nedierecel** [comment]
@markgreenburg - Status update that I attempted to reach the page, but it appears to be down at the moment. I will try again this afternoon.

**Comment by markgreenburg** [comment]
@nedierecel what page(s) are you trying to hit? There are some upstream backend changes that are giving us problems in staging at the moment but most pages should still be accessible (only one of the three key flows is 'broken').

**Comment by nedierecel** [comment]
@markgreenburg When attempting to login by going directly to `/health-care/schedule-view-va-appointments/appointments`, I authenticated successfully then reached an error screen that scheduling was not available. 

I tried again today and was able to test 1 of the 3 Options you suggested. Here are the next steps for this issue:

1. I'll complete the remaining 2 options and will validate the routes.
2. I'll outline suggestions for additional dataLayer values that FE will need to pass upon submission to capture items like typeOfCare.
3. We'll do another round of validation after FE implements.

**Comment by markgreenburg** [comment]
Thanks! Staging can be a bit finicky.

**Comment by nedierecel** [comment]
@markgreenburg - Please see the following items for next steps on implementation.

#### FYI Only
1. _Goal Funnel_ - I created a new funnel for the VAOS flow. Google Analytics doesn't always handle branching so elegantly, so I created a funnel with an "OR" statement for Request Date vs. Preferred Date. We can do more tests on Staging to see how this impacts reporting. We'll be able to use the Goal Flow report to see how users traverse the funnel. This report will be more useful than the traditional Goal Funnel, which is very linear. 
2. _Event Action for VAOS_ - I created a new Event Action for VAOS, which is distinct from the Health Care Event Action. I can combine these if you'd like. If we lump all the VAOS events **into** Health Care, you'd have to drill down from "Forms - Health Care" to see the list of `vaos-` event labels.

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/08c6d3eb-d0f6-47e8-bf93-ced968a30244)

3. VAOS Successful Submissions Triggered Correctly - I saw these events - `vaos-community-care-submission-successful`, `vaos-direct-submission-successful`, `vaos-request-submission-successful`

####  Additional Implementation
1. To understand with form submission which values were selected for "Type of Care", "Appointment Type", and "Reason for Appointment", please add these values to the recordEvent:

`dataLayer.push({'event': 'vaos-community-care-submission-successful', // Or vaos-direct-submission-successful OR vaos-request-submission-successful
'health-TypeOfCare': 'Insert Value Here', 
'health-AppointmentType': 'Insert Value Here', // Send 'No Value Selected' if not available for option type
'health-ReasonForAppointment': 'Insert Value Here'});`

**You'll notice that these dataLayer variables _do not_ have `vaos` as the prefix. This is intentional in case other health care teams want to use these dataLayer variables. Open to your feedback.

#### Optional Implementation for Your Consideration:
- [ ] For MVP, would you like to trigger an event to see when users reach this message? 
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/5fd5f459-440e-4f6b-bd2d-bb4a2e195287)

- [ ] Tracking "New Appointments" on Confirmation Page - This button was missing `vaos-schedule-new-appointment-started` again on this interaction. **Within GA, we can add the `page` dimension to distinguish which pages drove the activity.**

![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/b0201497-8758-40e5-9f30-4861ac1dcb24)

- [ ] The plan is to send the values for Type of Care, Facility Type, and Reason for Appointment on submission. The benefit here is we can capture that selection sooner in case the veteran drops out of the funnel.

**Comment by markgreenburg** [comment]
@nedierecel thank you! Looks good to me. Good catch on the new appointment from confirmation page, we'll make sure that's tracked as well. Should we close this ticket?

**Comment by nedierecel** [comment]
@markgreenburg May we keep this open? Are the above events ready for review in Staging? If so, I will shift to our review QA board. Thanks!

**Comment by lenaecb** [comment]
Hey @nedierecel - We have a ticket open right now to implement additional events. #5983

@narin is actually working on that ticket today. We should include some of the implementation requests that you have indicated here, but I also advise that @narin work with you @nedierecel on any of the additional implementation details. 

Let me know if we can address the new appointment form confirmation page event in this ticket or if we need to add it to #5983

**Comment by nedierecel** [comment]
Thanks @lenaecb and nice to work with you again @narin!  

Let's wrap the "New Appointment" from confirmation page into #5983 as well. 

Also for awareness, within Google Analytics reports, these events will be bucketed into "Forms - Health Care" instead of the screenshot above where I indicated it would be organized into "Forms - Online Scheduling". Minor change, but allows us to keep all health care related items under one bucket. Thanks!

**Comment by lenaecb** [comment]
Awesome, thanks @nedierecel! I'll make sure we capture that in our analytics documentation. 

I added "New Appt" from confirmation page to the #5983 ticket.

**Comment by narin** [comment]
Thank you @nedierecel.  Will follow up here or on #5983 with any additional questions.

**Comment by lenaecb** [comment]
@nedierecel - is there anything else outside of what @narin is implementing in #5983 that we need to address for analytics prior to starting our phased rollout?

**Comment by nedierecel** [comment]
@lenaecb May you also keep us posted if there are any last-minute changes to the URL structure of the pages? If so, we will update the goals within Google Analytics to reflect the final IA. Thanks!

**Comment by lenaecb** [comment]
@nedierecel - are we good to close this out? Seems we still looking at some error logging via analytics but in #5983.

**Comment by nedierecel** [comment]
@lenaecb Yes please - let's close this and keep #5983 as active. Thanks!
