### ISSUE TITLE
Design Intent - Design Feedback - Add Self Assessment Part A form information to BDD workflow 21-526EZ

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#56857]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Matthew Dingee: looking at the alert with instructions, I don't love having to explain the UI to folks. If that UI changes there could be problems with the text.
- We have noticed alert fatigue on va.gov, so use alerts sparingly, make sure to check the [guidelines](https://design.va.gov/components/alert). Try to limit the content inside alerts

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Must: The [wizard](https://design.va.gov/patterns/wizards) is deprecated, instead try 1 question per page
- Must: Follow the [intro template](https://design.va.gov/templates/forms/introduction)
- Consider: Consider using [background only alerts](https://design.va.gov/components/alert#examples---background-color-only) if it fits the guidelines

**Comment by lydiahooper** [comment]
Thanks for the feedback!
- I am looking into better solutions than the long instructions on the final alert. 
- The warning alert fits the guidelines best because there are negative consequences for the user, so we plan to keep to that style. 
- We're working on making updates to the deprecated components in 526, and given the expedited nature of this work do not plan to make changes to this page in this regard at this point. 

For further context, one thing I neglected to mention during design intent is that this is a short term solution. DOD will be taking care of Part A submissions starting in the fall.

**Comment by RakshindaAslam** [comment]
cc @lydiahooper @RakshindaAslam
