### ISSUE TITLE
Improve Unit Test output 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#5687]
# Overview 

- current dot output of our unit tests is interspersed with errors and warnings
- the overall log output is very verbose and hard to read 

```
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․,․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․target Element not found
․․․․․Warning: Failed prop type: The prop `removeInProgressForm` is marked as required in `FormStartControls`, but its value is `undefined`.
    in FormStartControls
Warning: Failed prop type: The prop `prefillAvailable` is marked as required in `FormStartControls`, but its value is `undefined`.
    in FormStartControls
․․․Warning: Failed prop type: The prop `fetchInProgressForm` is marked as required in `FormStartControls`, but its value is `undefined`.
    in FormStartControls
Warning: Failed prop type: The prop `startPage` is marked as required in `FormStartControls`, but its value is `undefined`.
    in FormStartControls
․Warning: Failed prop type: The prop `formSaved` is marked as required in `FormStartControls`, but its value is `undefined`.
    in FormStartControls
․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
```

# Task 

- make the output more succinct and easy to read 

#  Notes 

- don't have to stick to the current dot reporter 
- if possible, complete this without refactoring existing unit tests

**Comment by theodur** [comment]
From my initial inspection of the unit test output, the amount of warning and error messages from the passed tests is too much to try and fit cleanly on the command line.

One option I am exploring is to silence the warnings on passed tests, and only display the errors from failed tests. We can achieve this by tapping into the `beforeEach` & `afterEach` [ life cycle hooks of mocah](https://mochajs.org/#hooks) and stubbing `console.log` for tests that passed.

**Pros**: Significantly cleans the terminal output
**Cons**: Possibly valuable information regarding tests is lost

A tool that could help with this is the [mochawesome](https://github.com/adamgruber/mochawesome) reporter. This generates a HTML page that goes in depth with each test that was ran. This would show the information that we hide from the terminal, so that we can keep the terminal output clean, without getting rid of the gritty details of the unit tests.

<img width="1680" alt="Screen Shot 2020-02-10 at 6 02 29 PM" src="https://user-images.githubusercontent.com/9042882/74206317-b316a100-4c2f-11ea-9e64-abb958cf5ce5.png">

<img width="1680" alt="Screen Shot 2020-02-10 at 6 04 45 PM" src="https://user-images.githubusercontent.com/9042882/74206352-e3f6d600-4c2f-11ea-9806-2cf7ac7b54ff.png">

**Comment by theodur** [comment]
Resolved here: https://github.com/department-of-veterans-affairs/vets-website/pull/11705

**Comment by jbalboni** [comment]
Hey folks, I'm finding that I'm having to toggle the error output on and off in order to debug unit tests. I made a PR with an attempt a creating more helpful debug output when you pass in a particular env variable and am curious about your thoughts: https://github.com/department-of-veterans-affairs/vets-website/pull/13541

**Comment by bkjohnson** [comment]
Closing again since Jeff's PR is merged.
