### ISSUE TITLE
[Build] VA Forms API: Consider space-separated queries as separate terms

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#5693]
## Background
We rely on the VA Forms API to power our new Find VA Forms feature. 
However, the API treats space-separated queries as one compound search term (see [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5277#issuecomment-580782604)). 
Not treating the query as separate terms limits the number of form results returned. 

## Acceptance Criteria:
* Update the VA Forms API to treat space-separated queries as separate terms 
* Update documentation as needed
* Run search tests after changes to check on parity of results
  * Sample queries: 
    * "health care" "health care application" 
    * "disability" "compensation" "disability compensation" "disability application" 
    * "526ez" "1010ez" "caregiver" "intent to file" 
    * "supplemental claim" "aid and attendance" "housebound"

## Note: 
* this will require reviews by the Lighthouse team

## Reference:
[VA Forms API documentation](https://developer.va.gov/explore/vaForms/docs/vaForms?version=current)

**Comment by MickinSahni** [comment]
2020-02-19 PW Standup
- will dig into deeper in grooming pt. 2
- prerequisite to launch (#5589)

**Comment by jenniferlee-dsva** [comment]
Added a few more test queries of important forms for us to test internally.

**Comment by MickinSahni** [comment]
- PR is up, still targeting end of sprint

**Comment by AkucherGCIO** [comment]
02-24-20
Hoping for review today and VSP approves it.

**Comment by AkucherGCIO** [comment]
2020-26-02
@kelsonic @ncksllvn  - Can this be closed out as part of Sprint 15 ?

**Comment by ncksllvn** [comment]
Yep! The demo was probably proof enough, but here's a screenshot. Notice my query for `health care` pulls results that only include the word `health`.

![image](https://user-images.githubusercontent.com/1915775/75354448-fa7d6e00-587a-11ea-867c-ea7a37dc1388.png)

**Comment by jenniferlee-dsva** [comment]
Hey - Please also validate using those other sample queries in the ticket ^ 

"disability" "compensation" "disability compensation" "disability application"
"526ez" "1010ez" "caregiver" "intent to file"
"supplemental claim" "aid and attendance" "housebound"

**Comment by AkucherGCIO** [comment]
02-27-02 PW Standup
Nick is comparing the queries given by Jen and will report back.

**Comment by ncksllvn** [comment]
| Query | Modernized total results | Legacy total results |
| --- | ---- | ---|
| disability | [78](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=disability) | [81](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=disability&Action=Search) |
| compensation | [14](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=compensation) | [15](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=compensation&Action=Search) |
| disability compensation | [89](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=disability+compensation) | [92](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=disability+compensation&Action=Search) |
| disability application | [161](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=disability+application) | [170](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=disability+application&Action=Search) |
| 526ez | [1](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=526ez) | [1](https://www.va.gov/vaforms/search_action.asp?FormNo=526ez&tkey=&Action=Search)* |
| 1010ez | [0](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=1010ez) | [0](https://www.va.gov/vaforms/search_action.asp?FormNo=1010ez&tkey=&Action=Search) |
| caregiver | [1](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=caregiver) | [1](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=caregiver&Action=Search) |
| intent to file | [102](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=intent+to+file) | [78](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=intent+to+file&Action=Search) |
| supplemental claim | [38](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=supplemental+claim) | [45](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=supplemental+claim&Action=Search) |
| aid and attendance | [117](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=aid+and+attendance) | [127](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=aid+and+attendance&Action=Search) |
| housebound | [1](http://preview-prod.vfs.va.gov/preview?nodeId=2352&q=housebound) | [1](https://www.va.gov/vaforms/search_action.asp?FormNo=&tkey=housebound&Action=Search) |


`*` indicates that on the legacy search, I had to use the `Form Number` field to search instead of `Title / Keyword(s)`. The modernized search uses a single wildcard input.

-----------------
This is just looking at the count of each search, and "more" doesn't necessarily indicate better. 

At first I thought that the legacy search orders by form number, but looking more closely, I don't really see how it's ordered. When I search `disability`, 526EZ is on the last page. If results were "weighted" somehow, it seems like 526EZ would be one of the first forms. 

On the modernized search, the results aren't returned in any particular order, but users can sort by clicking a column.

**Comment by ncksllvn** [comment]
From call on February 28th, 2020 - 

- Consider adding bold effect into search results to show why a specific form was returned as a result
- Consider stripping hyphens so that `1010ez` will return form `10-10ez`
- Consider allowing quoted input to do a strict search - `"health care"` -> returns results that contain exactly `health care` in the form title

Side note
- Some form results link to external websites (GSA) instead of an actual download. This website is the authoritative source leading to a PDF download. Are these forms valuable for us?

**Comment by jenniferlee-dsva** [comment]
@ncksllvn RE https://github.com/department-of-veterans-affairs/va.gov-team/issues/5693#issuecomment-592075548 Thank you so much for the super easy list of validation comparison chart! 
I've done an extra layer of validation to ensure that the specific form does indeed come up in our modern search, and they do! Since the current live search does not currently bring up the most relevant form at the top (in fact is often on lower pages) - we have pretty good parity with the current search. 
MVP search is definitely acceptable to do soft launch (no-index) with. 

@AkucherGCIO @ncksllvn @kelsonic (fysa @rtwell @mnorthuis ) - Ryan is currently iterating on more mobile and 508 compliant results display. I think we can do soft launch, and then add his new design and ux as iteration releases. Thoughts?

**Comment by AkucherGCIO** [comment]
@jenniferlee-dsva - Sounds good regarding soft launch.  I am thinking we will create new tickets for the iterations.  So are we good to close this one as the validation has been done.

**Comment by ncksllvn** [comment]
@AkucherGCIO Echoing from Slack, soft launch ticket is created - https://github.com/department-of-veterans-affairs/va.gov-team/issues/6317. I think we can close this one!
