### ISSUE TITLE
Word list questions left

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#57]
Hello - Thanks for all your help on this list. There are just these last items that remain unresolved, and if you could look for where you have been @'d to reply, that would be wonderful. 

educational (as an adjective) ***[ @bethpotts @DanielleSoCompany  - not sure why we list out so many examples of the use of "educational" as an adjective -- or if the below are supposed to be examples of this entry. Not sure if we are listing exactly how these terms should be defined in body copy? / jl]***
  - educational assistance (to be consistent with Chapter 35, DEA, Dependents’ Educational Assistance, and other programs such as REAP, Reserve Educational Assistance Program, and VEAP, Veterans’ Educational Assistance Program)
  - educational counseling
  - educational and career counseling (this instance runs counter to the style within eBenefits > Apply > Vocational Rehabilitation and Employment Benefits > Education and Career Counseling, but aligns with VR&E Chapter 36 (Educational and Vocational Counseling)
    - educational and vocational counseling (to be consistent with VR&E Chapter 36: Educational and Vocational Counseling)
  - educational institution
  - educational plan
  - educational program

Guardsman/Guardsmen: Use the gender neutral "Guard member" on VA.gov. Capitalize "Guard." ***[Danielle note: Updated to reflect gender neutral terminology] -- [Jen note: @DanielleSoCompany  - pls confirm re capitalizing Guard; I think this is what Misty advised and we found in the DOD style guide...? Edited guidance language for clarity.]***

Gulf War Illness: Capitalize the I in Illness. This is also sometimes called "Chronic Multi-symptom illness." Note that "Gulf War Syndrome" is the former name, and is no longer used. When needed for clariy or SEO, include the former term on first mention. Example: Gulf War Illness (known in the past as Gulf War Syndrome). [*** @DanielleSoCompany : is it "chronic multi-symptom illness" or "Chronic Multi-symptom illness"? / jl] 

Individual Unemployability: Include a description that makes clear that this benefit is for Veterans who can't work due to a service-connected disability. ***[Danielle note: Revised per latest site definition.] - Jen q to @DanielleSoCompany : Is this an official VA terminology that requires capitalization? Example - "individually unemployable" is lowercase, but seems the same/similar to this term.***

Loan Guaranty agent: Capped per SME. **[@Working Group & Editorial - Do we need parity for this term; do different agencies capitalize this term differently? @Beth, Danielle - can you provide more info on SME & rationale?]** ***[Danielle note: @bethpotts - do you have this history?]*** {jen note to Beth: we are advising AP Style for loan technician -- only cap when it's used in front of someone's name as their title - Loan Technician Jen Lee will see you now.}

post-9/11: Hyphenate. We use the slash rather than the hyphen for 9/11 (*not* 9-11). Example: Post-9/11 GI Bill. ***[ @RLHecht  @bethpotts - can we find a non-proper name example of post-9/11, so we show a lowercase example? Post-9/11 GI Bill is the name of the program, so 'Post" would always be capped here. Or would we never refer to it like that in normal sentence? "She was born after 9/11" vs. "She was born post-9/11"? /jl]

prisoner of war (POW): Don't capitalize per the [DOD military dictionary](https://www.militaryfactory.com/dictionary/military-terms-defined.asp?term_id=4243). **Example:** As a former prisoner of war (POW), you may be eligible for additional VA health benefits and services.  ***/[Jen note: @bethpotts  - could you verify if the second example is not saying something totally offbase? I meant to use it just as an example of when we'd use it as a lowercase noun, but don't want to inadvertently spread misinformation about VA benefits either./]***

regional benefit office: Use "regional office" instead. See [VA regional office](placeholderanchorlink.com) entry for details.  ***/[ @jaredcunha-usds – is there a way to hyperlink/cross-link text within a page. Sorry if I already asked and you said no already! Memory… ☺ /jl]***

Reserve: ***[ @bethpotts  @DanielleSoCompany  - is this entry to indicate always capitalize? It was just listed with no guidance.  / jl]

Reservist: ***[ @bethpotts @DanielleSoCompany - is this entry to indicate always capitalize this word? It was just listed with no guidance. / jl]

work study: Two words, not hyphenated as a noun; hyphenate when used as an adjective preceding a noun. 
  - **Like this (modifying a noun):** Find out if you can earn money while you go to school through our work-study program.
  - **Like this (as a noun):** ***[ @RLHecht  - could your provide example when this would be used as a noun and not hyphenated? Personally, I wouldn't hyphenate "work study program" either./ jl]***

zip code: Lowercase, two words. ***[ @bethpotts @RLHecht - should "zip" be lower case? ZIP is a U.S. Postal Service trademark and acronym, and they use all caps. AP Style calls for “ZIP code.” M-W uses “zip-code” and “zip code.” ]****

**Comment by RLHecht** [comment]
@jenniferlee-dsva , @bethpotts and I went over the rest of these queries that were for us and @DanielleSoCompany. I've put our changes in bold below.


educational (as an adjective)  **[Since different parts of VA style education/educational differently, it seems helpful to have more examples that come up in the pages. I combined the last three onto one line though to make the entry a bit shorter.-RH]**

educational assistance (to be consistent with Chapter 35, DEA, Dependents’ Educational Assistance, and other programs such as REAP, Reserve Educational Assistance Program, and VEAP, Veterans’ Educational Assistance Program)
educational counseling
educational and career counseling (this instance runs counter to the style within eBenefits > Apply > Vocational Rehabilitation and Employment Benefits > Education and Career Counseling, but aligns with VR&E Chapter 36 (Educational and Vocational Counseling)
educational and vocational counseling (to be consistent with VR&E Chapter 36: Educational and Vocational Counseling)
**educational institution, educational plan, educational program**

**Guard member: Use the gender neutral term instead of Guardsman/Guardsmen on VA.gov. Capitalize "Guard."**
**[I confirmed that Guard should be capped. Also reworked the entry to put the term we do use first followed by what is outdated.-RH ]**

Gulf War Illness: Capitalize the I in Illness. **This is also sometimes called "chronic multisymptom illness."** Note that "Gulf War Syndrome" is the former name, and is no longer used. When needed for clariy or SEO, include the former term on first mention. Example: Gulf War Illness (known in the past as Gulf War Syndrome). **[Per NIH and other reputable sites, chronic multisymptom illness is lowercase and there is no hyphen in multisymptom. I've changed it above.-RH]**

Individual Unemployability: Include a description that makes clear that this benefit is for Veterans who can't work due to a service-connected disability. [Danielle note: Revised per latest site definition.] - [**This is a VA term and should be kept capped.-RH]**

Loan Guaranty Agent: Capped per SME. [@working Group & Editorial - Do we need parity for this term; do different agencies capitalize this term differently? @beth, Danielle - can you provide more info on SME & rationale?] [Danielle note: @bethpotts - do you have this history?] {jen note to Beth: we are advising AP Style for loan technician -- only cap when it's used in front of someone's name as their title - Loan Technician Jen Lee will see you now.} **[Per convo with Beth we will lowercase loan guaranty agent, so this entry should be changed.-RH]**

post-9/11: Hyphenate. We use the slash rather than the hyphen for 9/11 (not 9-11). Example: Post-9/11 GI Bill. In cases when post-9/11 stands alone, it should be lowercased. ***[ @RLHecht @bethpotts - can we find a non-proper name example of post-9/11, so we show a lowercase example? Post-9/11 GI Bill is the name of the program, so 'Post" would always be capped here. Or would we never refer to it like that in normal sentence? "She was born after 9/11" vs. "She was born post-9/11"? /jl] **[OK, to not have an example. I just added into the entry what to do if it's a general term not connected with the GI BIll. -RH]**

prisoner of war (POW): Don't capitalize per the DOD military dictionary. Example: **You may be eligible as a former prisoner of war (POW).** /[Jen note: @bethpotts - could you verify if the second example is not saying something totally offbase? I meant to use it just as an example of when we'd use it as a lowercase noun, but don't want to inadvertently spread misinformation about VA benefits either./] **[I reworded the example above to fix the issue of giving misleading info-RH.]**

**regional office: Use instead of "regional benefit office."** See VA regional office entry for details. /[ @jaredcunha-usds – is there a way to hyperlink/cross-link text within a page. Sorry if I already asked and you said no already! Memory… ☺ /jl] **[I switched this to put the correct term as the entry instead of the outdated one.-RH]**

Reserve: ***[ @bethpotts @DanielleSoCompany - is this entry to indicate always capitalize? It was just listed with no guidance. / jl] **[Yes, this is to indicate always capitalize.-RH]**

Reservist: ***[ @bethpotts @DanielleSoCompany - is this entry to indicate always capitalize this word? It was just listed with no guidance. / jl] **[Yes, this is to indicate always capitalize.-RH]**

work study: Two words, not hyphenated as a noun; hyphenate when used as an adjective preceding a noun.

Like this (modifying a noun): Find out if you can earn money while you go to school through our work-study program.
Like this (as a noun): **How much does work study pay?** [ @RLHecht - could your provide example when this would be used as a noun and not hyphenated? Personally, I wouldn't hyphenate "work study program" either./ jl] **[Added in example above. It should be hyphenated if it is modifying a noun.-RH]**
zip code: Lowercase, two words. [ @bethpotts @RLHecht - should "zip" be lower case? ZIP is a U.S. Postal Service trademark and acronym, and they use all caps. AP Style calls for “ZIP code.” M-W uses “zip-code” and “zip code.” ]* **[Keeping lowercase, no hyphen per M-W style.-RH]**

**Comment by jenniferlee-dsva** [comment]
RE Education and educational entries - thx, that makes better sense now. Here's how I propose revising it, now that I understand better why we need to include those examples. For easy reference, I think just have them be each an entry of their own. Like this: 

education: In general, on VA.gov we use "education" as a noun, and sometimes as part of a compound noun or attributive noun to modify another noun. 
__- Like this:__ education benefits OR education and training opportunities
__- Not this:__ educational benefits OR educational and training opportunities

educational: Because businesses within VA apply different usage styles for  “education” and “educational,” we've listed instances here, where we use "educational" in specific phrases rather than "education" as above. (See “education” entry.) 

__- Like this:__ educational assistance, educational institution, educational plan, educational program

educational and career counseling:  We use this style of phrasing to be consistent with VR&E Chapter 36: Educational and Vocational Counseling. (Note: this style differs from the style within eBenefits VR&E > Education and Career Counseling pages.)

educational and vocational counseling: We use this style of phrasing to be consistent with VR&E Chapter 36: Educational and Vocational Counseling.
 
educational assistance: We use this style of phrasing to be consistent with Chapter 35, [DEA, REAP, and VEAP](linktoacronymspage.com).

educational counseling: We use this style of phrasing to be consistent with VR&E Chapter 36: Educational and Vocational Counseling. (Note: this usage differs from the style within eBenefits VR&E > Education and Career Counseling pages.)
@RLHecht @bethpotts @DanielleSoCompany  - LMK if you see anything amiss.

**Comment by jenniferlee-dsva** [comment]
I've updated the remaining open items. Thanks all! Will keep this issue open in case you see anything amiss with revision of ^ education/ecuational approach. If none, LMK and I'll close this out! Have a great w/e.

**Comment by bethpotts** [comment]
@jenniferlee-dsva @RLHecht This all looks great! Thanks so much.
