### ISSUE TITLE
Disability additional forms page corrections

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#57053]
The additional forms page under Disability needs a few updates to reflect the correct list of additional forms, as well as the correct ways that a person can complete the individual forms listed on the page.  

https://www.va.gov/disability/how-to-file-claim/additional-forms/

For each form, we need to capture:
- the form name
- the form number
- indicate if the form is available as part of the online 526 or not
- the link to complete the digitized form online as a stand-alone form, or indicate that this is not available
- the link to the Find a form detail page to download the pdf of the form

**Comment by jennymayoco** [comment]
Hi @RLHecht here are the content updates from the "Additional forms" audit:
- **Form 21-10210** (Lay/Witness Statement) - this one is missing from the page. It's referenced in the 526 PDF and digital form and should be included in the table as a PDF and once live, also cross-link to the digital form
- The 1st row "A National Guard and Reserve member" can be removed since this is supporting documentation and not tied to a specific form.
![Screenshot 2023-04-27 at 3 11 33 PM](https://user-images.githubusercontent.com/122128479/234979900-94711c02-c3bc-4d62-85a1-e154a6b820b4.png)
- **Form 26-4555** (Application in Acquiring Specially Adapted Housing or Special Home Adaptation Grant) - This is still represented as a PDF form only. Will the digital form be cross-linked here as well once live?
- This section doesn't link or reference the form this pertains to. I wanted to flag this one in case it makes sense to move to another section (such as 4142).
![Screenshot 2023-04-27 at 3 37 18 PM](https://user-images.githubusercontent.com/122128479/234985072-78b814db-869d-43d9-8dc6-a32ca27850aa.png)

- **Form 21-4142 (Authorization to Disclose Information to VA)** - stand alone form will need to be cross-linked once the digital form is live as well

**Comment by mnorthuis** [comment]
I'm going to pull back this ticket now that we have a different plan in place for this page.  We will be moving this page out of disability and using it to create a supporting forms for claims section to house benefit-agnostic forms. 

A number of updates will need to be made to the page given this new structure and approach, so closing this ticket.
