### ISSUE TITLE
Design | Profile | Personal Info: Move stray dropdown questions to their appropriate boxes

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#57097]
### Background

Discovered and approved for re-design as part of issue 53227. The two dropdown items, "How to update your legal name" and "How to fix an error in your name or date of birth," are floating above personal info boxes and need to be moved to their appropriate places near "Legal name" and "Date of birth."

![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/135b26be-6fb3-460a-a41b-57eeea9ef0e4)![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/2f598d24-078d-4c00-9898-e7d18361daeb)

### Tasks

- [x] Mock up sketch designs with dropdown items moved to appropriate positions on the page
- [x] Share designs / get approved

**Comment by andaleliz** [comment]
@adamwhitlock1 I started looking at this and noticed these floating FAQs display on the page in instances where there's only an alert on the page due to a system error

![image.png](https://images.zenhubusercontent.com/5d9def68b6de6d00018d50f2/2c320304-7163-4eb6-a69d-fca6e1cc9d54)

That makes me wonder if perhaps they're floating intentionally, so if someone comes to the page and we can't load it for some reason, we can still share this important information with them.

I didn't work on this though, so I don't have any background on it. Do you by any chance remember anything about this? I've searched through GH tickets and can't find anything to speaking to the design decision of keeping these FAQs out of the table. 

If we move them inside the tables, can we still show them if there's a system error? I would imagine we can't, without duplicating content and adding conditionals to show the FAQs outside the table only if there's an error.

Thanks for any insight you can provide!

**Comment by adamwhitlock1** [comment]
Oh interesting! That is a great point. We didn't _mean_ for them to display regardless of an error being present, but I agree that they could then be useful to people in those cases.

You are correct that if we moved them into the tables, then we would have to duplicate them or do some sort of additional work to allow them to still be shown when there is an error.

So do you think we should leave them as they are currently?

**Comment by mtcA6** [comment]
Hmm interesting. 

As an end user, would you update your information if you couldn't see what information is currently on file? That would make more work for me as the end user. I don't think I would follow through with any steps to update the data unless I knew the info currently provide was incorrect. 

And also, the second error message is also related to both name AND date of birth so it doesn't make sense to nest that one next to DoB. 
![Image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/2f20cf8d-7fa8-4e87-94bc-2b2374a96787)

I think maybe the first dropdown should be nested with the first name but the second dropdown should stay where it is

**Comment by andaleliz** [comment]
@adamwhitlock1 thanks for the reply!  I don't know what I think just yet, still gathering info :) 

>We didn't _mean_ for them to display regardless of an error being present, but I agree that they could then be useful to people in those cases.

I checked staging, and they actually don't display now if an error is present. But the Sketch files shows that they do, so it sounds like the Sketch files are out of date? Or is there just a general disconnect and we're not sure why?

@mtcA6 I appreciate your input too! 

>As an end user, would you update your information if you couldn't see what information is currently on file?

It's probably an edge case, but someone might be coming to the profile specifically to update something they saw listed incorrectly elsewhere. Maybe they were filling out a form somewhere else on the site and the pre-fill information was incorrect, or they got something in the mail with wrong information.

>I think maybe the first dropdown should be nested with the first name but the second dropdown should stay where it is

That makes sense to me too. I'm going to bring this to content office hours tomorrow and talk to Danielle. She might remember more about why things are the way they are here, and will have to sign off on any changes anyway.

**Comment by mtcA6** [comment]
Got ya. Fun! we have some fun inconsistencies between sketch and prod. I bet the work you highlighted around creating the flows w/in our sketch files would help us catch some of this!   

It feels like an extreme edge case, didn't we learn recently that the auto-fill wasn't really in use because it was so glitchy?

[See comment:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/18256#issuecomment-1583409329)
> Pre-fill - Pre-fill from Profile is in very limited use. We've discovered on the Veteran-facing Forms team that it largely doesn't work in the Forms library in an easily reproducible way and thus doesn't get used. Thus it is, for the most part, aspirational. As such, I've removed that documentation from the pattern entirely. It's definitely not implemented any longer in the Rogers STEM application nor in the Education Benefits (form 1990) application which I confirmed just now in staging.

How does auto-fill work today? Does it grab the information out of profile? Or does it too trace back to the source eg. VA Profile? 

I'd be concerned if we're not able to pull the data into profile and display it correctly, and we're displaying an error message saying as much, the data pulling into a form could be corrupted in some way or wouldn't pull correctly either. 

Ultimately, I'm w/you, I do think the right thing is to display the instructions and the end user can make the choice to either take the steps to have their information updated or to sit and wait it out and hit refresh or return another day.

**Comment by andaleliz** [comment]
Cool, I will update this ticket w/ more info once I meet from Danielle.  I want to be sure to answer your question:

>Does it grab the information out of profile? Or does it too trace back to the source eg. VA Profile?

everything comes from the same place - the source of our profile product is VA Profile, and so is pre-fill on forms.

**Comment by andaleliz** [comment]
Your point about Matt's comment got me curious, so I [followed up with him in Slack](https://dsva.slack.com/archives/C0NGDDXME/p1688587231807559) about it. He was referring to pre-fill as a reproducible pattern in the design system, not the functionality as a whole. I believe it's actually quite useful, but it's implemented in a custom way pretty much everywhere it exists so it's not something for the design system to adopt.

Also I realized I didn't answer your question about how pre-fill (technically not the same as auto-fill) works. My understanding is that it depends on the data being called. I know the contact information comes from a "Redux" state which I don't totally understand 😅 I bet Adam and Allison do if you want to get into the details about how it works.

**Comment by andaleliz** [comment]
@mtcA6 and @adamwhitlock1 I met with Danielle to discuss this yesterday and we decided:
- we will not display any FAQs when the error page loads (so no FE work needed there), and I've updated the Sketch files to reflect that
- we will keep the "fix an error" FAQ above the table, and move the "update legal name" inside the appropriate cell.  The sketch files have been updated ([desktop example](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/dlVxdm3), [mobile example](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/a/4ajJxKZ)) and this is ready for a FE implementation ticket 🎉

**Comment by andaleliz** [comment]
@mtcA6 or @adamwhitlock1 did a FE ticket ever get created for this? Just double checking.

**Comment by mtcA6** [comment]
@andaleliz looks like i missed it. I'll create one now. 

The process around closing design tickets is something I want to discuss on retro tomorrow. I think it would be good if instead of closing it, it would be better to move it to validate and mentioning me on it, if it's stuck in validate it means I haven't created the necessary follow up ticket.
