### ISSUE TITLE
<Content change on a static public page: BDD> from <Benefits Disability Experience 526ez>

### ISSUE THREAD

**Issue by RakshindaAslam** [department-of-veterans-affairs/va.gov-team#57187]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [x] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*
Starting April 1' 2023, an active service member filing for pre-discharge benefits under the BDD (Benefits Delivery at Discharge) Program needs to submit a completed Self-Assessment form Part A in order to get an exam before discharge from service. Without this form, the claim cannot move forward.  VBA Stakeholders have provided content suggestion for https://staging.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?

As soon as possible. This change in policy went into effect on April 1st, 2023 and any pre-discharge claims being submitted after April '1st without this form will not go further until they have been developed after submission. This can add days/weeks of delay to the claim.

  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/README.md
- Link to or attach user flows:
- Link to prototype or mockups: Page 1 of [Modifications to VA.gov’s BDD Claim Flow for New SHA Part A.docx](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/collab-cycle/Modifications%20to%20VA.gov%E2%80%99s%20BDD%20Claim%20Flow%20for%20New%20SHA%20Part%20A.docx)
- Link to any epics/issues that may be helpful: [Self Assessment Part A for BDD Flow](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56579)
[Collaboration Cycle for [Benefits Disability Experience, Disability Comp Application](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56612)

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [x] No

## When does this work need to be done?
- Estimated launch date: As soon as possible
- Estimated staging review date: Not applicable / Part of sitewide product
- Content, Accessibility, and IA work needed by: Not applicable / Part of sitewide product

## Do you plan to bring this to an upcoming content office hours session?
- [x] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matt Self
-	Product manager: Rakshinda Aslam
-	Designer: Lydia Hooper
-	FE engineer: Christine Cereca
-	Product/team Slack channel: #benefits-ce-disability_exp_1

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by RakshindaAslam** [comment]
cc @lydiahooper @RakshindaAslam

**Comment by katherine-fung** [comment]
Hi @RakshindaAslam. I'm a writer on the sitewide content team and I'm making the changes you've requested to the pre-discharge claims page. 

I've added the link to the pre-discharge claims page, and also the "[File a pre-discharge claim while overseas](https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/)" page. 

For the overseas page, I made a few other changes so that the page aligns more closely with VA.gov style. I'd like to coordinate with the SMEs for pre-discharge claims, so they can review the page and confirm that the changes work. Could you connect me with the SMEs? The page is short so hopefully it won't take long to review. 

After that, we can copy edit and publish the pages.

**Comment by RakshindaAslam** [comment]
Thanks @katherine-fung! Tagging @lydiahooper from our team for review who is leading the design/content changes for this.

**Comment by lydiahooper** [comment]
@katherine-fung I just included you on an email with the SMEs, please let me know if you need anything further (best to message me on Slack as I'm not consistently getting notifications for comments made here).

**Comment by RLHecht** [comment]
@lydiahooper For awareness, these 2 static pages are now live with changes. 
https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/
https://www.va.gov/disability/how-to-file-claim/when-to-file/pre-discharge-claim/file-while-overseas/

I think this ticket should be good to close but let us know if you need anything else.

**Comment by lydiahooper** [comment]
We do need something else. We need to provide information on this page about how to upload Part A (after they've submitted 526 claim), so that if a user searches on va.gov they will be able to find these instructions. The platform team has suggested this to meet criteria, so this change is of a timely nature now that we're at staging review. (Note that data says that every day this change is not live, potentially hundreds of service members' claims are being delayed.)

Here is the content I worked with Beth to create (see this other ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/57175) and I would include it where there is mention of Part A...

You can file a claim for disability benefits through the Benefits Delivery at Discharge (BDD) program online at www.va.gov/disability/how-to-file-claim. When you file your claim online, you can upload supporting documents like this form with your claim.

You can also submit this form on VA.gov after you file your BDD claim. Go to My VA to find your claim. When you upload your Separation Health Assessment, select this for document type: Disability Benefits Questionnaire.

**Comment by bethpottsVADEPO** [comment]
@katherine-fung You can add this language to both static pages (let me know if you think any rewriting is needed for this to work in the context there--a "Note" may be the way to go):
You can also submit this form on VA.gov after you file your BDD claim. Go to My VA to find your claim. When you upload your Separation Health Assessment, select this for document type: Disability Benefits Questionnaire.

**Comment by lydiahooper** [comment]
It occurred to me that since this text won't be in an alert, perhaps we can provide the full instructions on the va.gov page. These are the full instructions:
Go to My VA to find your claim. Review details and select the **Files** tab. Add the file, and in the dropdown select document type: Disability Benefits Questionnaire. Select **Submit files for review*.* The file should then be listed under **Documents filed** on the same page.

**Comment by bethpottsVADEPO** [comment]
@lydiahooper We're tracking this work in a different ticket and prioritizing it so that we'll have content up this week with guidance for how to upload the self-assessment. Will follow up with you on our approach in this ticket either today or Thursday!  FYI @katherine-fung

**Comment by katherine-fung** [comment]
Hi Lydia,

Here's the approach we've landed on: we've created a new Resources and Support page which tells users how to upload their form, step-by-step. We're crosslinking to this page from key areas of [va.gov](http://va.gov/) where we mention the Separation Health Assessment, and where we discuss documents to upload with your claim.

These areas are:
"Pre-discharge claims" page
"File a pre-discharge claim while overseas" page
"Evidence needed" page
"Upload evidence to support your claim" page


Here's a draft of the Resources and Support page: http://preview-prod.vfs.va.gov/preview?nodeId=57111 

This page is with our copy editor right now. She'll also review the 4 other pages. Let us know if you have any concerns. Otherwise, we can get the Resources and Support page live today. And we'll move forward with publishing the changes on the other pages once we've copy edited them.

**Comment by katherine-fung** [comment]
Hi @lydiahooper, 

We've published the page. It will be live within an hour or so. The link will be: 

https://www.va.gov/resources/separation-health-assessment-for-service-members

**Comment by lydiahooper** [comment]
Sounds like this ticket is ready to close?

**Comment by RLHecht** [comment]
Yep, we can close this!
