### ISSUE TITLE
SM spot check content notes

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#57214]
I did a quick spot check of SM in staging and saw a few content issues I wanted to flag. Listing them here in case there's time to adjust before staging!

- [ ] **Breadcrumb**
- Breadcrumb that goes back to phase 0 landing page says "Return to Dashboard." If it's following the pattern of other breadcrumbs, it should say "Back to messages." There's no page or H1 called "Dashboard" in the tool, right?
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/45be89c6-a708-4995-8a5b-4d4c45f06008)

- [ ] **Search box**
- Change “Search your [folder name] messages folder” to “Search messages in [Folder name]”
- Should the top "Search" line be a header style to set it apart from the “Keyword” line? Right now, these lines run together visually.
- Uncap "Sender" in Keyword line: “Keyword (sender, subject line, or category)” 
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/42620d3a-8c89-4c9a-b75c-a8087415beac)

- [ ] **Trash search box**
- Search line in the Trash folder should say “trash" and not "deleted"
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/9356220d-9acd-414d-8790-99214eda80c0)

- [ ] **Unread messages in inbox**
- Can we make this conditional so it makes "message" singular if there's only 1? We should really avoid "1 messages."
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/00973e43-5c59-430f-9cb1-5930b4bce3f2)

- [ ] **Edit contact list**
- Change "Edit List" to "Edit your contact list" (and uncap "list")
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/38772c73-bc15-442c-b56a-c015f83a5beb)

- [ ] **Advanced search instructions**
- Change line under Advanced search that starts "To use the advanced search" to “Select a folder. Then provide at least one other search option."
![image.png](https://images.zenhubusercontent.com/626705c08314b7e2fecdf2eb/99882bfe-e47e-4f81-b5dd-e5cf11469c70)

**Comment by laurwill** [comment]
Hi @underpaid1ntern 
I'm not sure it's letting me tag you here — let's see if this goes through!

**Comment by underpaid1ntern** [comment]
Thanks @laurwill , I got the tag. There are some things that will be different once we hit staging review/deployment and I'll list those things out once I gather them all. Thanks for your help!

**Comment by laurwill** [comment]
Hi @underpaid1ntern, adding 1 more content note here:
In the midpoint for medical records, accessibility asked us to lowercase the email address for phase 0 feedback as "vamhvfeedback@va.gov" (It originally had some letters capitalized.)

**Comment by underpaid1ntern** [comment]
Hi @laurwill ,

We've had some updates that affect the issues you've brought up in this ticket (TYVM for the help). Please see the below and LMK if you have any further updates/questions. I will be rolling this feedback into developer stories to address the staging environment:

**Breadcrumb**
> Breadcrumb that goes back to phase 0 landing page says "Return to Dashboard." If it's following the pattern of other breadcrumbs, it should say "Back to messages." There's no page or H1 called "Dashboard" in the tool, right?

Correct - this is currently being fixed. I believe there are some issues preventing the merge to fully fix it in staging.

**Search box (now called filter)**
> Change “Search your [folder name] messages folder” to “Search messages in [Folder name]”

Text changed to "filter" to help shape the user expectation - the function is very limited and isn't a great search. Otherwise, should fit the formula you outlined.

> Should the top "Search" line be a header style to set it apart from the “Keyword” line? Right now, these lines run together visually.

This has been fixed in the component update (see img below)

> Uncap "Sender" in Keyword line: “Keyword (sender, subject line, or category)”

Design now uses the field labels "to, from, message ID, or subject"

<img width="480" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/126206606/df80faa5-0b65-4772-a148-13688109d5d9">

**Trash search/filter box**

> Search line in the Trash folder should say “trash" and not "deleted"


Addressed by component update
<img width="500" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/126206606/e8001dde-5423-4a15-b1cd-ba9db4dca829">

**Advanced search/filter instructions**

> Change line under Advanced search that starts "To use the advanced search" to “Select a folder. Then provide at least one other search option."

Advanced filters are not a dropdown part of the new component so a user no longer needs to pick a folder. Required fields are marked.

<img width="567" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/126206606/c858eb61-1701-407e-8902-2b7f91ae41b0">

<img width="578" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/126206606/e4ca2e42-4ed9-462e-a071-39a2c352946e">

**Pending items to fix in this ticket**

1. [add conditional to landing page when there's only 1 unread message in inbox](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57214#:~:text=Unread%20messages%20in%20inbox)
2. [change link text "Edit List" to "Edit your contact list"](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57214#:~:text=avoid%20%221%20messages.%22-,Edit%20contact%20list,-Change%20%22Edit%20List)
3. [lowercase the feedback email on the landing page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57214#issuecomment-1529783734)

**Comment by laurwill** [comment]
Hi @underpaid1ntern , checking in on this — are any of these items still pending, or can we close this out? Thank you!

**Comment by coforma-terry** [comment]
Closing for now :)
