### ISSUE TITLE
VAOS Appointment List Redesign (FE) - Regression Test 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#57251]
## Description
This ticket is to track the testing effort for appointment list redesign. We will have a SQA member perform regression testing. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

### Design Assets
Design Specs 

## Definition of Done
- [ ] All acceptance criteria are met

---

**Comment by ldelacosta** [comment]
Target go live for 10% users is May 17, 2023. Please let us know if you see any issues. Thanks! cc: @marcynadeau

**Comment by marcynadeau** [comment]
@ldelacosta SQA has finished testing the new appt list feature and no issues were reported.  I could not test VVS appointments though I previously set up a whole list for you of VVS appointments nd know you  tested those.  

So because you did that testing, I am closing this task.  cc @MaragathaJayashankar85  

The VVS appointments issue is related to a bug in Staging:  VAOSR-6443 - Staging VCM appointments not displaying in VAOS OPEN
