### ISSUE TITLE
GIDS: Upgrade to Ruby v2.5.7

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#5746]
As a developer, I need to upgrade GIDS to Ruby v.2.5.7 so that I can upgrade ruby to the most recent version.

## Assumptions:
1.

## Acceptance Criteria
1. GIDS Ruby is on version 2.5.7.
2. The Readme for the GIDS Repository is updated to reflect version 2.5.7 of Ruby

## Technical Tasks
1. Remove TargetRubyVersion from .rubocop.yml so that rubocop will evaluate based upon the current rails version and fix the resulting issues.
2. Update Dockerfile
3. Update .ruby-version
4. Coordinate with devops for any additional infrastructure changes
5. Perform smoke testing of GIDS application

## Supporting Artifacts
1. https://dsva.slack.com/archives/CBU0KDSB1/p1580502997380900
2. https://github.com/department-of-veterans-affairs/vets-api/pull/3497
3. https://github.com/department-of-veterans-affairs/va.gov-team/issues/2513

### Ruby update
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/579
### Specific dependency related updates
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/582
- https://github.com/department-of-veterans-affairs/gibct-data-service/pull/583

**Comment by jholton** [comment]
> 4. Coordinate with devops any for any additional infrastructure changes

You are definitely going to need this.
GIDS is currently deployed natively.
We were not able to upgrade `vets-api` until devops changed our deployments to use Docker.
The reason?  Native deployments (GIDS) install Ruby via the `yum` package.  The latest version of Ruby available via `yum` is 2.4
Moving to Docker deployments allowed us to install more recent versions of Ruby via the base Docker image specified in the Dockerfile.

If you merge your Ruby upgrade PR before moving to Dockerized deployments, your deployed environments will break since Ruby 2.5 is specified in the Gemfile but will not be present on the servers.

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/issues/6638

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/gibct-data-service/pull/579

**Comment by sonntag-adam** [comment]
Smoke testing of gids complete

**Comment by sonntag-adam** [comment]
In staging, smoke testing complete. Closing story.
