### ISSUE TITLE
Proposed Travel Pay text messages from Modernized Check-In Team

### ISSUE THREAD

**Issue by kellysmith1008** [department-of-veterans-affairs/va.gov-team#57626]
## What does your team need support for? Check all that apply.
- [x ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*
As part of our travel pay rollout, we will be sending a Veteran a text message when they initiate a travel pay reimbursement claim upon check-in. There are three scenarios for the text messages:
1. The claim request was received 
2. A claim already exists
3. The claim couldn't be filed at this time

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [x] Yes
  - [ ] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
End of May
  
## Supporting artifacts
*Please provide supporting artifacts as available.*
We have proposed text in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57560)

- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526
-- all previous information can be found in that ticket
- Link to or attach user flows: [Mural with user flow and text messages](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u5d970cc175b184392a004997)
- Link to prototype or mockups: [Mural with user flow and text messages](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u5d970cc175b184392a004997)
- Link to any epics/issues that may be helpful: [55526](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55526), [57560](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57560)
- 
## Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No

## When does this work need to be done?
- Estimated launch date: end of May
- Estimated staging review date: May 15
- Content, Accessibility, and IA work needed by: May 5

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [ x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: Modernized Check-In Team
-	OCTO-DE product owner: 
-	Product manager: Lori Pusey
-	Designer: Ben Brasso
-	FE engineer: Brian Seek
-	Product/team Slack channel: check-in-experience

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by sara-amanda** [comment]
Hi, @kellysmith1008! We opened a CAIA a11y support ticket for this and it is ticket number #57702. In this ticket you will find my recommendations and two quick questions for you.

**Comment by kristinoletmuskat** [comment]
Hey @benbrasso-agile6 , just looking at this now from an IA perspective. I followed along with this ticket so understand what ya'll are doing and why you made certain decisions. I think the happy path makes sense, but I have two things ya'll might want to consider:

1. For the case where a user self-identifies that they need to submit a claim later, we don't link them to BTSS -- maybe we should? I could see a user being a little stressed about remembering how/where to do that.
![Travel Reimbursement Questionnaire Q3](https://user-images.githubusercontent.com/122126772/235529143-b765997a-7110-4950-a6e5-c234ba7413e3.png)

2. Just to confirm is this text coming from the same number as checkin? I'm thinking about the use case where a veteran wants to look up their claim number later, say in a few weeks. I think the mental model these days is that confirmation numbers / confirmation messages come mostly over email, and maybe also text messages, though they aren't the primary mode. Have ya'll considered also sending an email, where we could give the veteran more guidance/resources for next steps?

I also added some comments to the mural and sketch files you shared! Feel free to respond wherever works for you.

**Comment by benbrasso-agile6** [comment]
Thank you, @kristinoletmuskat !

1. If you look to the far right in our [sketch file](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec), you'll see variations of the confirmation page based on how the Veteran answers the travel related questions. In these variations, we provide information on how to file later. So, we do it on the confirmation page, but we haven't been planning to send a text message to Veterans who didn't file during check in. Thoughts? ([Related convo in sketch](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/a/Ry128Oz?annotation=f09c6a87-7509-4b71-b139-b0f0e5c841e5).)
2. Yes, same number as check in. We may have considered email, but not heavily. Primarily, we wanted to give an immediate response to the Veteran. And, because we couldn't do it in real-time over the web, we thought text message was the next best thing, plus it's the communication method used for pre-check-in and check-in. To date, PCI + VEText do not utilize email. But, I think email is a good idea. And, I can bring that up.

**Comment by benbrasso-agile6** [comment]
I replied to the comments in [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932).

**Comment by kristinoletmuskat** [comment]
@benbrasso-agile6 thanks for your quick response! I see the confirmation pages now -- I think you're right that we don't need to link to BTSS in that question if that info is here, and now I understand the text message being just that second layer of confirmation. 

I think it's worth following up on the email idea, thanks for that.

I think we're good from a IA workflow perspective on this work!

**Comment by aliyahblackmore** [comment]
Hi @benbrasso-agile6 - we just want to confirm that the text messages are the only new pieces of content here that need review? We didn't previously do a close review of the travel pay screens in the user flow because those weren't called out for content review in the other ticket [link to ticket]. 

FYSA @laurwill

**Comment by benbrasso-agile6** [comment]
@aliyahblackmore That's correct. @DanielleThierryUSDSVA had reviewed the web pages in 2022.

**Comment by laurwill** [comment]
Hi @benbrasso-agile6 @kristinoletmuskat ,
We recently updated the travel pay page to include a sign-in block that takes Veterans directly into the BTSSS system without signing in again. (Here's the[ intake request](https://app.zenhub.com/workspaces/sitewide-content-accessibility-and-ia-63a1d63232beba0011a7833f/issues/gh/department-of-veterans-affairs/va.gov-team/53402) for reference)

This is a bit of different situation since they're coming from a text. But would we want to consistently link to that page with the sign-in block from all these texts as well? That way, if the Veteran is already signed in on their phone, they can get into BTSSS without signing in again. 

Any concerns or questions about that?

**Comment by benbrasso-agile6** [comment]
To check their claim status in BTSSS, are you recommending we send Veterans to https://www.va.gov/health-care/get-reimbursed-for-travel-pay/

... instead of directly to BTSSS? https://va.gov/accessva-travel-claim

**Comment by laurwill** [comment]
Apologies, I was forgetting that they're not already fully authenticated to use PCI. So I think we can disregard my suggestion. 

What are the character limits for the texts? And we saw that the original text for pre-check-in used a go.usa.gov link—is that required for all VETexts, or should they all be normal links?

**Comment by benbrasso-agile6** [comment]
I believe VEText used to use a URL shortener that used go.usa.gov, but no longer uses that. And, therefore, we don't either... we just need to update our documentation.

**Comment by laurwill** [comment]
Hi @benbrasso-agile6 , here are suggested tweaks to the text messages:

We're sorry. We couldn't process your travel pay claim. File your claim online within 30 days at https://www.va.gov/health-care/get-reimbursed-for-travel-pay

You already filed a travel pay claim for your appointment on June 8 at 1:00 p.m. ET. Check your claim status at https://va.gov/accessva-travel-claim 

We received your travel pay claim. Your claim number is TC202207000011666. Check your claim status at https://va.gov/accessva-travel-claim

And just echoing that we'll want to revisit how we direct people to take next steps on the confirmation screens — whether that's filing travel pay online, updating contact info in VA Profile, or some other step.

**Comment by kellysmith1008** [comment]
@benbrasso-agile6 @laurwill Thanks for the text suggestions. I've updated the Mural to reflect the new suggestions. Quick question about the third one - there may be a time when Veterans are filing travel pay claims for multiple appointments in a week - if I have an appointment on Monday, Thursday, and Friday, for example. Given that, do we want to keep the date for which the claim was received in that text message? Previously we had included it with this text: "We received your travel reimbursement claim for 2023-09-30. Claim number, TC202207000011666. Check your claim status at https://va.gov/accessva-travel-claim".

**Comment by benbrasso-agile6** [comment]
Yes, I think that’s a good idea. 

We’ll want to check about the second text. I think Melanie was suggesting not to place PII/PHI in the text. I also don’t know if we’re able to pass through the appointment info. That’s some we need to discuss with Guarav. 

If so, we will want to discuss the date format. Historically, there’s been an issue for us showing time zone because of something related to facilities being in different time zones that share the same VistA instance. Maybe it doesn’t apply for the text messages, but I’m not positive.

**Comment by benbrasso-agile6** [comment]
Awesome. Makes sense to me.
