### ISSUE TITLE
Add homeless help contact info to contact us and helpful VA phone numbers

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#58018]
## Veteran story

As a Veteran who is unhoused, or their family member, I need to know who to call to get help.

## What's needed

Add this phone number to the [Contact us](https://www.va.gov/contact-us/#call-us) and [Helpful VA phone numbers](https://www.va.gov/resources/helpful-va-phone-numbers/) pages.

**National Call Center for Homeless Veterans**
877-424-3838
Hours: 24/7

## Other notes

Add to backlog that we'll want to explore inclusive language here. The name of the center includes "Homes Veterans" but it's the official name of the center. Would like to explore in the context of person-first language.

## Tasks
- [x] Add number (Aliyah)
- [x] Copyedit (Megan)
- [x] Publish (Megan)

## Acceptance criteria
- [x] New phone number is live on the site

**Comment by DanielleThierryUSDSVA** [comment]
@clantosswett FYSA for tracking

**Comment by DanielleThierryUSDSVA** [comment]
@clantosswett FYSA for tracking

**Comment by aliyahblackmore** [comment]
Hi @megzehn this is ready for you! I reviewed placement of the number with Danielle via Slack. 

**On the Contact us page**
http://preview-prod.vfs.va.gov/preview?nodeId=8472
After the GI Bill hotline

**On the helpful VA phone number page**
http://preview-prod.vfs.va.gov/preview?nodeId=8427
- After the Women Veterans number 
- Additionally, since we're no longer sending people to eBenefits for VA tasks I went removed the eBenefits technical support number.  

After this work is done, I'll circle back about adding to the backlog that we'll want to explore person-first language.

**Comment by megzehn** [comment]
Thank you, @aliyahblackmore! Confirming that I published these changes! 

CC @RLHecht

**Comment by aliyahblackmore** [comment]
Thank you @megzehn !! 

@RLHecht should I open up a ticket in the backlog to explore person-first language?

**Comment by RLHecht** [comment]
These changes are live. I'll open up a backlog ticket, Aliyah! Closing.
