### ISSUE TITLE
HLR Content review of unique H3 headers from Benefits team 1

### ISSUE THREAD

**Issue by uxgary** [department-of-veterans-affairs/va.gov-team#58324]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [X] Making revisions to one or more existing VA.gov pages
- [ ] Something else 
 
 *Give a brief description of what your team needs support with.*
We are adding H3 tags in the form pages so that Veterans using screen readers can navigate through the form
and understand when the page has changed. We would like the content team to review the page content and make any necessary edits. 

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [X] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
## When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline: [HLR Content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/decision-reviews/higher-level-review/design/content-source-of-truth.md)
- Link to staging: [HLR Staging](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/start)
- Link to any epics/issues that may be helpful: [Github issues](https://github.com/department-of-veterans-affairs/va.gov-team/issues/57045) 

## Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No

## When does this work need to be done?
- Estimated launch date: As soon as it can be made available
- Estimated staging review date:
- Content, Accessibility, and IA work needed by: 

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [X] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

## About your team

- Team name: 
-	OCTO-DE product owner: Matthew Self
-	Product manager: Sade Ragsdale
-	Designer: Gary Homidas, Eileen Chi
-	FE engineer: Robin Garrison
-	Product/team Slack channel: #benefits-ce-decision_reviews

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag Randi Hecht.**

If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)

**Comment by bethpottsVADEPO** [comment]
@RLHecht I wanted to note here that Gary said the content he wants to have us edit is headers only. We're not reviewing all the content.

**Comment by eileen-coforma** [comment]
@RLHecht Do we have an update on this?

**Comment by katherine-fung** [comment]
Hi @eileen-coforma! 

@bethpottsVADEPO and I have reviewed the H3 headers for the Higher-Level Review online form. Our edits are in the attached Word doc. We copied the source of truth content into the doc, and tracked our changes with comments for context. I'm adding a few notes here: 

- We want to confirm that you added H3s to the form to improve accessibility, and wanted us to review the H3 content for plain language/style/accessibility. Is this correct? 
- On the [intro page of the form in staging](https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996/introduction), we noticed that the H2s had H2 tags with H3 font size. And the H3s had H3 tags with H4 font size. Is that intentional? 
- In keeping with the scope of this ticket, we reviewed just the headers in the tool. But there were a few places where we recommend changes to match the header edits, or changes to the content around the headers. These are in the Word doc but I'm calling them out here too and just noting we understand these changes are not in the headers themselves. 

1.  On the intro page of the form, consider getting rid of steps 3 and 4 "VA review" and "Decision." The Veteran doesn’t have to complete these steps, so they don’t need to be listed as steps.  

In the NOD online form, we put this information in an additional information component/drop down.
https://www.va.gov/decision-reviews/board-appeal/request-board-appeal-form-10182/introduction 

2. We're recommending changes to 1 H3 about the reason you disagree with your claim decision, 1 H3 about requesting an informal conference, and 1 H3 about your scheduling availability. There are 5 other places in the form (non-headers) we should update to match the new language. The changes are pretty straightforward. 

Please let us know if you have any questions. Thanks so much for your patience. It's always a pleasure collaborating with you. 
[HLR H3s_06.23.23.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11852866/HLR.H3s_06.23.23.docx)

**Comment by katherine-fung** [comment]
This work is complete, closing ticket
