### ISSUE TITLE
UxPIN + CodePen - Prototype for User Testing

### ISSUE THREAD

**Issue by AndrewCoforma** [department-of-veterans-affairs/va.gov-team#58369]
Explore potential of creating a VA Forms Prototype in CodePen to be used for testing AT users

**Comment by AndrewCoforma** [comment]
## Description
Research potential of using [CodePen](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/codepen-prototyping.md) for User testing 

## Definition of Done
- [ ] Discovery/Research
- [ ] Review demos with Liz Lantz
- [ ] Create v1 MVP of VA Form
- [ ] Build prototype for testing* (*if meets criteria for testing)

## Supporting Documentation

[CodePen Prototyping](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/discovery-research/codepen-prototyping.md)
[Demo 1](https://codepen.io/surfbird/full/gOjmPyj)
[Demo 2](https://codepen.io/surfbird/full/PoBpwzO)

**Comment by jeana-adhoc** [comment]
For the [UXPin prototype test](https://preview.uxpin.com/67880702eb00da6d2274540b4b43dc674eb943e5#/pages/163332420/simulate/no-panels), these are the accessibility issues I've identified so far:

1. Zoom: It does not reflow text when you zoom in the browser, it simply magnifies the content and causes horizontal scroll.
2. I am unable to tab into the form at all, I'm also unable to click into any of the input fields to type anything
3. And since I can't tab into the form at all, a screen reader also cannot access it.

**Comment by AndrewCoforma** [comment]
UXPin HTML export produces same bugs as described in @jeana-adhoc 's comment above:
1. Text Input fields and dropdown menus do not work/function
2. Webpage does not respond to browser/device edges - it stays bound to width of sketch canvas https://images.zenhubusercontent.com/133843125/eeacbc8a-dc47-4682-a32a-61bd43f6a569/uxpin_html_export_test.mov

**Comment by megansiddle** [comment]
Can we close this ticket out and spin up a new one that is focused on any of the remaining concerns?

**Comment by jeana-adhoc** [comment]
I think so - with Andrews work completed yesterday - I think we're in a new 'phase' of the project anyway. Matt needs to convert Andrews login so that I can access it. 

Here are links to the prototype previews:

- [mobile](https://preview.uxpin.com/60532c7a26504c465c55ad85b105971e29e7663c#/pages/163174305/simulate/sitemap?mode=f)
- [desktop](https://preview.uxpin.com/67880702eb00da6d2274540b4b43dc674eb943e5#/pages/163332420/simulate/sitemap?mode=f)

**Comment by megansiddle** [comment]
@PSIEBENLIST can you please spin up a new ticket for the next step for this work?

**Comment by AndrewCoforma** [comment]
added all links for UXPin and CodePen prototypes - closed ticket,
