### ISSUE TITLE
[CAIA A11y]: Medallia modal needs review

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va.gov-team#58372]
### What do you need support with?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/14154792/db03d447-f5cf-44df-bda6-220a9b31075f)

It's uncertain if there have been recent changes to the Medallia feedback modal. Specifically, we're unsure if the following have undergone a11y review and have tickets:
- Tab order of close and submit buttons
- Paragraph text between the submit and input fields (which may be missed by screen reader users)
- Size and contrast of "x" / close button in the top right

### When do you need this support by?

June 30, 2023

### How urgent is this request?

A little urgent, we need this support before the date we provided above

### Supporting artifacts (if any)

[Research Findings, 2022 Disabled Veteran Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/shared-support/accessibility/research/2022-feedback/a11y-feedback-research-findings.md) included a cursory audit by Tiffany Pender identifying issues.

[Previous audit notes (google doc)](https://docs.google.com/document/d/1Wo-rQqBtCCWbgHROtyb5lLbZtkD1E9myq6xKVZFT1N4/edit?usp=sharing)

Josh followed up with Ian and team to address these issues. Aubrey Arcangel's (engineer) last update on these issues:

> Hi Josh! I wanted to give you a quick update on Medallia A11y fixes. I just merged that magnification fix where the X close button would go off screen beyond 300%.
> Since we just missed the daily deploy, the changes wont reflect until tomorrow. And with Medallia styling changes, you can’t view them on staging because it’s a 3rd party app that uses the production stylesheet.
> I  will create some new tickets to track work the others and older ones. I will need to sync up with our VSignal folks to determine if some recommendations are possible. Since it’s a 3rd party app, our scope is limited to styling.

We should confirm if:
- [ ] Any changes have been made to the Medallia form since Tiffany's audit
- [ ] If changes have been made, if they were reviewed for a11y
- [ ] If there are any tickets surrounding the following items: 
    - [ ] Tab order of close and submit buttons
    - [ ] Paragraph text between the submit and input fields (which may be missed by screen reader users)
    - [ ] Size and contrast of "x" / close button in the top right
- [ ] And if they weren't, work with the team to conduct a maintenance audit for changes made

### Who's on your team?

This ticket request was made by Josh on behalf of CAIA

### Do you have an accessibility champion on your team?

Yes, we have a champion

**Comment by sara-amanda** [comment]
@coforma-terry I am going to grab this one.

**Comment by sara-amanda** [comment]
## CAIA Update

@joshkimux  thank you for the ticket! I spoke with @ianMcCullough-ob and they are aware of the Medallia issue. They are working through this issue.

**Content Note:** The language present is required government text. 

cc: @aubreyarcangel @SarahKay8 @coforma-terry

**Comment by aubreyarcangel** [comment]
Hi yall, sorry I'm late to the show. 

Medallia is unique from any app on VA.gov because we do not have direct control of the codebase since it's a 3rd party application.
We have control over SOME styling, but there are limitations to some elements because Medallia has a lot of `in-line styles` with `!important` that we can't override. 

There are also 7 Medallia surveys in total. Here's a list of where to find them:
|Form name                      |Staging url                                     |Production url                              |Notes                                                         |
|-------------------------------|------------------------------------------------|--------------------------------------------|--------------------------------------------------------------|
|VFS Questionnaire              |staging.va.gov                                  |www.va.gov                                  |all pages except /search & /contact-us/virtual-agent/         |
|VFS Search Questionnaire       |staging.va.gov/search                           |www.va.gov/search                           |/                                                             |
|VFS Chatbot Questionnaire     |https://staging.va.gov/contact-us/virtual-agent/|https://www.va.gov/contact-us/virtual-agent/|                                                              |
|VFS A11y Questionnaire         |https://staging.va.gov/find-forms/              |www.va.gov                                  |30% of visitors                                              |
|VA.gov A11 VHA Questionnaire   |https://staging.va.gov/alaska-health-care/      |https://www.va.gov/alaska-health-care/      |25% of visitors on 140 VHA URLs                               |
|External Website Survey (ORMDI)|n/a                                             |https://www.va.gov/ormdi/                   |100% of visitors at least 20 seconds and not again for 60 days|
|Internal Website Survey (ORMDI)|n/a                                             |https://vaww.va.gov/orm                     |                                                              |
|                               |                                                |                                            |                                                              |

Let me know if you have any questions. I'm happy to hop on a call to dive in deeper.

**Comment by sara-amanda** [comment]
## CAIA Inquiry
**Thank you, @aubreyarcangel , are you and @ianMcCullough-ob able to answer these questions posed in the original ticket?** 
- [ ] Any changes have been made to the Medallia form since Tiffany's audit
    - [Research Findings, 2022 Disabled Veteran Accessibility Feedback](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/shared-support/accessibility/research/2022-feedback/a11y-feedback-research-findings.md) included a cursory audit by @TiffanyPender identifying issues, per @joshkimux 's notes above.
    - [Previous audit notes (google doc)](https://docs.google.com/document/d/1Wo-rQqBtCCWbgHROtyb5lLbZtkD1E9myq6xKVZFT1N4/edit?usp=sharing)
- [ ] If changes have been made, if they were reviewed for a11y
    - @ianMcCullough-ob I believe you mentioned there were accessibility updates being made, correct? 
- [ ] If there are any tickets surrounding the following items relating to Medallia?
    - [ ] Tab order of close and submit buttons
    - [ ] Paragraph text between the submit and input fields (which may be missed by screen reader users)
    - [ ] Size and contrast of "x" / close button in the top right
- [ ] And if they weren't, work with the team to conduct a maintenance audit for changes made

_Many thanks in advance to you all!_

**Comment by eli-oat** [comment]
@artsymartha68 follow up here, the info I got: 

> As per the Medallia team’s recommendation, we need to upgrade to the latest version of Medallia, which we are told will incorporate fixes for accessibility issues such as aria labels.

Will close this for now, but we can revisit once the upgrade to the newer version of Medallia is done.
