### ISSUE TITLE
Show past appointments

### ISSUE THREAD

**Issue by markgreenburg** [department-of-veterans-affairs/va.gov-team#5849]
## Story:
As a veteran, I want to see my past appointments in the appointments list in VAOS so that I can see all of my appointment info (past and future) in one tool instead of having to log into MHV.

## AC:
- [ ] Past appointments show in separate tab on appointments list page
- [ ] Both past VA and CC appointments show in the same past appointments list
- [ ] Past appointment list is sorted with most recent appts at top and going back in time
- [ ] Past requests are not in the list
- [ ] Cancelled appointments show as `cancelled` (see mock)
- [ ] Both kept & missed appointments show with no specific status (see mock)
- [ ] Past [TBD: 3 or 6] months of CC & VA appointments loaded into view by default
- [ ] Veteran can [TBD] to load more appointments

## Mock
![image (8).png](https://images.zenhubusercontent.com/59c29173b0222d5de478791d/b16edf2a-9cb9-4b76-96d4-4b3e8aaa720c)

**Comment by jbalboni** [comment]
@markgreenburg @rtwell I'm not sure this is fleshed out enough for us to work on yet. 

We need to do pagination here, I think. Otherwise, the gaps you might have in appt history are confusing. If we show just the last 3 months of appt history, for example, what happens if you have a six month gap between appts after that? Do you click a "Show more" appointments link 2 (or more) times to get that appointment to show up?

I think there's some backend investigation here to see if the paging that the appointments endpoint currently supports is enough and if we can expose that to the front end.

**Comment by rtwell** [comment]
@jbalboni let me know if i'm a crazy person, but my understanding that the way we have to call appts is by date:

`past_appointments?type=va&start_date=[some date]&end_date=[some_date]`

and b/c of that limitation and how sluggish it is to crawl back 6 months (or however long), we are kinda shoehorned into "Show 3 months" and then "show the next 3 months" etc etc

do you need to see a comp? i saw this as simply a button beneath the last appt that says "Show the next 3 months" (again, not sure what the right time span is).

**Comment by jbalboni** [comment]
Fetching over 6 months in one shot is too slow, that's true, but the underlying VAMF api for appointment history supports paging and we are not making use of it. I think we need to figure out if using their paging implementation helps with the speed issue. 

If it doesn't, then yes, we're stuck with the UI you're describing, but I think just having a button without any other explanatory text is confusing, because appointment histories are likely to be sparse and you might have several month gaps. How would a user know that they should click the "show 3 more months" button again if they click it once and nothing changes?

**Comment by rtwell** [comment]
ah, gotcha!

how can we take advantage of the underlying VAMF api for appointment history?  i'm unclear what data it returns so we can use it. or maybe what i dont understand is what paging means for an API.

**Comment by jbalboni** [comment]
We need to do some investigation to see how the VAMF api's paging implementation works. If it does work the way we want, then we would be able to see how many appointment someone had in total over the past 2 years, while only grabbing 10 (or whatever) at a time. So you could then use the pagination component (https://design.va.gov/components/pagination), which I think would be clearer for users.

**Comment by rtwell** [comment]
woo, awesome—let me know what you discover

**Comment by rtwell** [comment]
i'm hoping we can do something like this:
![image](https://user-images.githubusercontent.com/12564977/75267279-0a864680-57c4-11ea-928d-20dd1d7bc626.png)

**Comment by jbalboni** [comment]
@rtwell That's doable with what we know now (except for maybe the "all of 2019" option).

**Comment by rtwell** [comment]
awesome!

do you have any recommendations for what default time frame we should display that isnt too terribly slow? 3 months is a guess. 

also, i assume if we displayed the last 3 months (or whatever span) we could then paginate it?

**Comment by markgreenburg** [comment]
@peggygannon FYI – mocks for a new past appointments tab on the VAOS 'dashboard.' Please let us know if you think any of this content needs to be updated.

**Comment by peggygannon** [comment]
@rtwell @markgreenburg  I don;t have any changes to past appointment dashboard. I want to be sure though that in the intro sentence the m and c are lowercased in VA medical center. I'm not sure if it's showing uppercase b/c this is a mock?

**Comment by jbalboni** [comment]
FYI @narin

**Comment by rtwell** [comment]
i default to your expertise re:capitalization @peggygannon

**Comment by jbalboni** [comment]
FYI, this is blocked until someone with CAG access has time to do some discovery on the existing paging implementation.

**Comment by narin** [comment]
My CAG access was working when I tried it a few days ago, so I can start a bit of discovery on this.

**Comment by jbalboni** [comment]
I created a feature flag for this, `va_online_scheduling_past`

**Comment by lenaecb** [comment]
Action Item - Someone within VAOS team (FE or BE) to help provide CAG access to review VAOS legacy.

**Comment by narin** [comment]
I was finally able to access CAG and test out pagination.

Legacy VAOS makes 3 separate calls for confirmed VA, requests, and CC appointments.  From my testing, it seems only the VA confirmed appointments call supports pagination.

### VA Confirmed Appointments

Confirmed appointment pagination can be manipulated with the following parameters:  

* `pageSize` - number of results per page
* `pageNumber` - determines which page is returned
* `useCache` - determines whether to use cache or not. Currently defaults to `false` in `vets-api.`

I tested the latency when modifying `pageSize` and it does not have any noticeable effect.  The `startDate` and `endDate` and number of total appointments is what determines the duration of the call, which averages about 7 seconds for 2 years of appointments on the judy.morrison staging account.  

Good news is, if we set `useCache=true`, each subsequent call is only around 205ms.

### VA Requests

`pageSize` and `pageNumber`, and `useCache` seem to have no effect. Average time it takes to grab 2 years of requests was about 1.5 sec.

### CC Appointments

`pageSize` and `pageNumber`, seem to have no effect.

When repeating the same fetch, first call averaged ~562ms.  Subsequent calls averaged 300ms

### Usage in VAOS

Because we are grouping all 3 appointment types, and not all endpoints support pagination, we would probably have to keep track of our own pagination in the FE application state anyway.

Due to the fact that the first confirmed appointments call takes the longest regardless of page size, my initial thinking is that we may want to just fetch all the data at once.

If we go with the tabbed design that @rtwell suggested, we could start fetching as soon as the user lands on the dashboard, that way it might be done by the time they click on "Past Appointments", if they click it at all.

Happy to hear other thoughts.

CC: @jbalboni @saneshark @kreek

**Comment by rtwell** [comment]
ccing @lalexanderson-dsva in case this has any conflicts with what we can display in MHV, etc

**Comment by saneshark** [comment]
I'm not crazy about fetching data that might not be used unless we have some rough idea of % of users who would actually click that tab. If it's a pretty high number of users it might make sense, but otherwise I would think we just deal with the latency and work to resolve.

I would however like to work with shared services or upstream data providers to see why page size has no affect on latency.

Great news on CAG access though! I can check that box off on resiliency planning checklist for our team as previously I think it was just Alastair with access.

**Comment by jbalboni** [comment]
Ryan's design has a dropdown that starts with 3 months of history. I think that's an ok amount of time to fetch when the click the Past appts tab. I think we'll have to be careful to request data in chunks to not hit timeouts, like we do when we get the 24 months of history for the clinics check, where we fetch 6 month chunks.

I don't believe we want to show request history, and the CC service doesn't respect any date params, so we'll just have to make do for that.

I think it's doable for us to fetch all the appointments for the selected time periods and paginate on the client.

**Comment by narin** [comment]
@lenaecb @rtwell 

I'm working on the drop down with the different appointment ranges as seen in Ryan's mockup. The default range will be the past 3 months as discussed earlier.  Can I get some guidance/clarification on what the other options should be? 

From the mockup, it looks like 3 month chunks going back one year, and then the final option is all of the current year (YTD), or should it be all of last year?

![image](https://user-images.githubusercontent.com/786704/77482066-5091f280-6de2-11ea-9cdb-610d86c42802.png)
