### ISSUE TITLE
IA work for 526ez intro pages

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#58496]
## Issue Description

The product team working on the 526ez form is making changes to the IA. They're removing the pre-authentication /start page and adding two pages right after authentication to replace it. We need to review the user flow and provide IA feedback for this work.

Sketch file: https://sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092

Other product artifacts that may be needed:

- Link to Research Plan
- Link to Discussion Guide
- Link to product outline: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/README.md
- Link to prototype or mockups: https://sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092
- Link to any epics/issues that may be helpful: https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/55513
- https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/56607
- Link to original content in Google doc: https://docs.google.com/document/d/1FeN68e-udsPEd_bTUmMSUiiB5UpJ34tFoXiZ657jvdY/edit?usp=sharing
- Link to SOT on Github: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/design/introduction%20page%20content.md

Intake request: #57843

## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] Product team has IA feedback and recommendations

**Comment by jennymayoco** [comment]
Shared IA heuristics flows with the team. Paired feedback with user flow standards

**Standard:** A user flow has valid or appropriate closure, and doesn't result in a dead end where a user can't complete a task due to a functional issue (i.e. blank page, missing field or CTA, 404 error).
- Clear next steps. If no to active duty, continue to 526 normal flow. If yes to active duty, continue through BDD flow

**Standard**: A user flow provides content or navigation to help users understand where to go or what to do next.
- N/a

**Standard**: A user flow includes a prominently placed CTA that doesn't lead the user out of the primary flow without notifying them or providing a clear way for them to return to the original flow.
- Flagging this because the H1 changes (although it’s not CTA). Team might implement a question in research to see if this causes any disruption to the flow for participants

**Standard**: A user flow doesn't have repetitive or redundant steps.
- N/a

**Standard**: The primary CTA is clear and/or prominently displayed within the flow or content page.
- N/a

**Standard**: Error messages include a path to resolution and follow guidance in the error messages dictionary and error messages style guide.
-N/a

**Standard**: Your content or feature supports all necessary user flows and scenarios.
- Can non-Veterans fill this form out for someone who is a Veteran or active duty member? If they’re logged in as themselves or logged in as the Veteran?

**Comment by jennymayoco** [comment]
Connected with the team in the intake ticket to see if any additional IA support will be needed for this work

**Comment by jennymayoco** [comment]
Closing this ticket as per team's update in intake
