### ISSUE TITLE
Review exported PDFs from "MHV on VA.gov" team

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#58587]
## What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [x] Something else 
 
 *Give a brief description of what your team needs support with.*

The "MHV on VA.gov" team is making excellent progress with exporting PDFs out of the Veterans' medical record. We need to review these samples to make sure the a11y requirements are being met as development proceeds. Assigning SK since she has PDF expertise.

## Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No

  
## Supporting artifacts
*Please provide supporting artifacts as available.*

There are sample PDFs in the slack channel here (SK is on the thread with Adrian and Bobby):

https://dsva.slack.com/archives/C03Q2UQL1AS/p1684344969816149?thread_ts=1681767385.014929&cid=C03Q2UQL1AS

## Will this work be going through the Collaboration Cycle?
- [x] Yes  (eventually)
- [ ] No

## When does this work need to be done?
- Estimated launch date:
- Estimated staging review date:
- Content, Accessibility, and IA work needed by:  asap as developers are actively working

## Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

**Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.

### Artifacts 
[https://app.zenhub.com/files/133843125/a8ffd18d-7c42-470a-8ae9-8e4e65dc72a5/download](https://app.zenhub.com/files/133843125/a8ffd18d-7c42-470a-8ae9-8e4e65dc72a5/download)[https://app.zenhub.com/files/133843125/fe342527-1092-4515-a744-16ca40e8c107/download](https://app.zenhub.com/files/133843125/fe342527-1092-4515-a744-16ca40e8c107/download)[https://app.zenhub.com/files/133843125/87e0e673-d2d4-48af-b798-d2e4cbfcad30/download](https://app.zenhub.com/files/133843125/87e0e673-d2d4-48af-b798-d2e4cbfcad30/download)[https://app.zenhub.com/files/133843125/9556265b-0b2e-4080-a4c3-fef1d8b7963f/download](https://app.zenhub.com/files/133843125/9556265b-0b2e-4080-a4c3-fef1d8b7963f/download)

## About your team

- Team name: 
-	OCTO-DE product owner: Lauren Alexanderson
-	Product manager: @MarciMcGuire 
-	Designer: @coultonbunney-usds 
-	FE engineer: @acrollet @BobbyBaileyRB 
-	Product/team Slack channel: #[mhv-medical-records]

**Comment by acrollet** [comment]
I just realized that I need to review and fix some issues with word separation/whitespace. I'll upload new PDFs later today.

**Comment by acrollet** [comment]
I've updated the slack link in the issue to point at the more recent PDFs.

**Comment by SarahKay8** [comment]
Hey @acrollet! I would break these sections out into paragraphs ![59B00A48-CBB3-4152-B348-6BFFDE933CAD.jpeg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/0f525fb1-5d3a-4137-a9da-86ec7007d4df), Lists must have the following structure: Label Elements and List Item Body Elements.  
Once I get these PDF's through my commonlook validator, I'll drop more feedback (if any)

**Comment by acrollet** [comment]
thanks @SarahKay8 !

so you're saying that in the example above, "Result: ", "Standard range: " and so on should go in the `Lbl` element? I just ask because the guidance ([for example](https://commonlook.com/pdf-accessibility-lists/)) I've seen online is that the label should contain bullets and/or numbers, which we don't have in this doc.

thanks again 🙂

**Comment by SarahKay8** [comment]
Yep correct! Because these don't have any` lbl `s such as bullets or numbers we should break it into paragraphs. Sorry if I didn't word it correctly @acrollet

**Comment by SarahKay8** [comment]
Yep correct! Because these don't have any` lbl `s such as bullets or numbers we should break it into paragraphs. Sorry if I didn't word it correctly @acrollet

**Comment by acrollet** [comment]
New PDFs using P tags uploaded to slack: https://dsva.slack.com/archives/C03Q2UQL1AS/p1684526163877269?thread_ts=1681767385.014929&cid=C03Q2UQL1AS

**Comment by SarahKay8** [comment]
Hey @acrollet! Thank you for making these changes. 

I would break up each of these lines here into seperate paragraph tags. This is on the Vaccine PDF. I.E "Provider comments: No information no feedback given" in a single tag  ![29385725-68DF-444B-AEDB-023FBCC26C6C.jpeg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/ad4fb276-f50d-4db7-a4a5-9d1917f658f8) 
You also need to give this PDF an English language which can be done In **"Page Properties".** 
Also, because there is a repeating instance of **"Vaccines**" and the paragraph beneath it, you can artifact these on page 2 and so on so it doesn't keep repeating on each page. ![E6F1D550-24C4-4799-9021-B095D046625A.jpeg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/4098017f-14b1-446a-a09f-e2ab03013d0e). There is also an empty H3 tag on the Blood Pressure PDF. ![88BB8928-6D1A-4FE2-85A4-54B4122EAF79.jpeg](https://images.zenhubusercontent.com/623cd4d6774110eeb19922cb/9a0d6106-cd25-4b5c-8045-0aeba5ae5d4a)Lastly, each pdf has failed Tab Order. To remediate in Acrobat, go to **"Page Properties"** in the page panel, select **"Tab Order"** and choose **"Use Document Structure"** , tab order failure will pass.**

**Comment by acrollet** [comment]
@SarahKay8 thanks for your review! I'll be working on your feedback, I've also contributed a fix to the generation package to set the Tab Order to "Use Document Structure", hopefully that will get reviewed and merged in quickly.

**Comment by RLHecht** [comment]
Going to close this ticket but please reopen if there's more work needed!

**Comment by SarahKay8** [comment]
Hey @acrollet! lastly, our a11y specialist Evan ran these pdfs through the commonlook software and this was his feedback. Required fixes
* Tab order is not set in Acrobat 
    * Not sure if this is possible to set in the source software?
    * Since there are no interactive elements in the doc, the tab order won’t make much of a difference, though it does fail the checker
* There are empty <NonStruct> tags throughout the tag tree
    * More so a PDF/UA issue 
* The tagged <Artifact> header and footer content at the end of the tag tree is read by the screen reader when the user reaches the end of the document
    * Though tagged as <Artifact> in the tag tree, the header/footer content is within <Span> tags in the content pane
    * If it is not possible to programmatically ignore header/footer content in the source, could alt text be added to the properties of the artifacted content to let the user know it should be ignored? 
* FOR BLOOD PRESSURE ONLY
    * There’s an empty <H3> tag that is causing a hierarchy issue due to the previous heading being a <H1> 
Recommended fixes
* <Sect> tags are used as a root element, though <Document> should be used as the tag that contains all tags in the tag tree
* Provide content for the Author and Subject fields in the document properties
    * Author is the organization, not an individual

**Comment by acrollet** [comment]
Thanks @SarahKay8 ! Questions inline:

> 
> * Tab order is not set in Acrobat 
>   
>   * Not sure if this is possible to set in the source software?

This will be fixed per our conversation above.

>   * Since there are no interactive elements in the doc, the tab order won’t make much of a difference, though it does fail the checker
> * There are empty `<NonStruct> `tags throughout the tag tree

These tags contain the horizontal rule elements - would it be better to use `Artifact` tags?

> * The tagged `<Artifact>` header and footer content at the end of the tag tree is read by the screen reader when the user reaches the end of the document
>   
>   * Though tagged as `<Artifact>` in the tag tree, the header/footer content is within`<Span>`tags in the content pane

Would it be better to make the `Artifact` tag a `Struct` and place the text content in `Artifact` tags instead of `Span`s?

>   * If it is not possible to programmatically ignore header/footer content in the source, could alt text be added to the properties of the artifacted content to let the user know it should be ignored? 
>     FOR BLOOD PRESSURE ONLY
>     There’s an empty `<H3>` tag that is causing a hierarchy issue due to the previous heading being a `<H1> `

This will be resolved in the next set for review.

>     **Recommended fixes**
> 
> * `<Sect>` tags are used as a root element, though `<Document>` should be used as the tag that contains all tags in the tag tree
> * Provide content for the Author and Subject fields in the document properties
> * Author is the organization, not an individual

👍

**Comment by acrollet** [comment]
> You also need to give this PDF an English language which can be done In **"Page Properties".** 

@SarahKay8 that's odd, I'm giving the document the language code `en-US` - what is acrobat reporting it as? Would you prefer that I simply use `en`? thanks!

**Comment by SarahKay8** [comment]
@acrollet Empty `<NonStruct>` tags: Yes, the horizontal rule elements should be changed to artifacts and ignored by screen readers. Decorative content such as structural elements, non-informative images, or anything that doesn't provide value to a screen reader user should be changed to artifacts so they're not picked up during reading. 

Header/footer content: It would be best to find a way to make sure the content isn't read at all. If this is content is important and should be read, only one instance of the header/footer should be accessed - the header on the the first page and the footer on the last page. This is the ideal scenario. It seems like the app is trying to make the header/footer content hidden from users due to the `<Artifact> `tags, but it's still picked up. Since they come at the end of the document, it doesn't impact the user much, so I'd be okay leaving as is if there's no way to address the issue.

**Comment by BobbyBaileyRB** [comment]
Hi! @acrollet, the footer is helpful information when navigating pages. The header information is a requirement that we must provide, such as the first name and last, along with the DOB. **Should these be accessible to screen readers, it's a good question.** In my option, the footer should be accessible (within the tab order). The header might be unnecessary for screen readers but we are required to put these onto each page.

**When it comes to AT**
I am unsure if all PDF applications will read the page numbers to the Veteran. That is why it is on each page, so that screen readers know which page they are on when tabbing through. However, @SarahKay8 could give us a better direction on if the header and footer is considered essential content or meta/information.

**Comment by acrollet** [comment]
just noting that the `vaccines-list.pdf` file was not generated by the new pdf generation package.

**Comment by BobbyBaileyRB** [comment]
Hi! @acrollet, the footer is helpful information when navigating pages. The header information is a requirement that we must provide, such as the first name and last, along with the DOB. Should these be accessible to screen readers at some point while reviewing the documents.

It wouldn't be a good experience if the header was spoken to screen readers on every page - as Sarah recommended, it would be nice if it only read this to AT users when it first displays the header. However, @SarahKay8 shouldn't the page numbers always be in the tab order and read to AT users? Or does the application itself solve for that? We don't need to read off "the Report generated by" for every page, only needs to be read off on the first time it appears.

**Comment by BobbyBaileyRB** [comment]
Note: the content team has provided some written updates for the PDF - I will be working on the PDF design updates this week (or the next, depending on time and tasks).

**Comment by acrollet** [comment]
> @acrollet Empty `<NonStruct>` tags: Yes, the horizontal rule elements should be changed to artifacts and ignored by screen readers. Decorative content such as structural elements, non-informative images, or anything that doesn't provide value to a screen reader user should be changed to artifacts so they're not picked up during reading.
> 
> Header/footer content: It would be best to find a way to make sure the content isn't read at all. If this is content is important and should be read, only one instance of the header/footer should be accessed - the header on the the first page and the footer on the last page. This is the ideal scenario. It seems like the app is trying to make the header/footer content hidden from users due to the `<Artifact> `tags, but it's still picked up. Since they come at the end of the document, it doesn't impact the user much, so I'd be okay leaving as is if there's no way to address the issue.
> 
> cc: [evan.burnett@coforma.io](mailto:evan.burnett@coforma.io)

Hi Sarah,

I've updated the HR elements and worked on the header/footer content so that the first header will be read at the top of the document, and the last footer at the bottom. Could you review this attached file? Thanks!

[lab_and_test_results (9).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11607111/lab_and_test_results.9.pdf)

**Comment by SarahKay8** [comment]
Looks good! @acrollet Thanks for the update

**Comment by acrollet** [comment]
@SarahKay8 here are PDFs for (hopefully) final review, I believe I've addressed all feedback with the exception of the tab order, which will be resolved once [this pull request](https://github.com/foliojs/pdfkit/pull/1449) is merged into PDFKit and a new version has been released.

[lab_and_test_results.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11639274/lab_and_test_results.pdf)
[single_vital.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11639275/single_vital.pdf)
[vitals.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11639276/vitals.pdf)
[vaccines.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/11639277/vaccines.pdf)

**Comment by SarahKay8** [comment]
HI @acrollet! I have no additional feedback to add. These look great.

**Comment by SarahKay8** [comment]
is this okay to close out? @acrollet

**Comment by acrollet** [comment]
@SarahKay8 I think so, can you just confirm that the tab order change is not a launch blocker?

**Comment by SarahKay8** [comment]
Ah I see! I personally would consider this a minor defect. Once changes are merged, Myra at the 508 office will do one final QA and we should be good to go. @acrollet
