### ISSUE TITLE
Get access to Medallia Qualitative data

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-team#58669]
## Overview
As part of work to define Landing Page metrics and KPIs, we need to access the tools used to capture and display user feedback. 

## Acceptance Criteria

- [x] [Submit ticket to get access to Medallia's qual feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jwoodman5%2C+ianMcCullough-ob&labels=VSP-contact-center%2Ccc-data-request&template=qualitative-data-request.yml&title=Qualitative+Data+Request)
- [x] Ensure that access is successfully obtained

**Comment by fmccaf1** [comment]
[From landing page readme:](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/README.md)

>Status

>The application was initially launched in Production behind a feature flag. During Phase 0 of the landing page rollout, a handful of trusted users were given access via an allow list.

>On March 27, 2023, after the initial smoke testing was completed by the trusted user group, access was changed to allow access to a random 5% of daily MyHealtheVet users who log in via Login.gov or ID.me, have health benefits, have a VAMC associated with their profile, and have never received care at a Cerner VA Medical Center.

>On April 26, 2023, the rollout moved to Phase 2, and access was expanded to 10% of users meeting the same criteria used for Phase 1.

**Comment by fmccaf1** [comment]
First export includes:
- survey submissions associated with va.gov/my-health
- technical issues categorized under MHV
- keywords: "my health" (378), "health dashboard" (1)

**Comment by fmccaf1** [comment]
I did get access to both survey data and call center data , but one thing I realized while browsing through the data, is we could likely make better use of the myhealthevet call center data as opposed to the more general VA.gov call center data (many of the notes say they forwarded the caller on to the myhealthevet call center). 

Another learning is it seems at this point we're not successfully pinpointing users of the new my health dashboard. All the data seems to be coming from users of MHV. I'm wondering if there is a way for us to see which users have gotten access to the new health experience and keep checking call center and survey data to see if anything is coming from those specific users? @batemapf, I'm curious if you have thoughts on this.

**Comment by batemapf** [comment]
> I'm wondering if there is a way for us to see which users have gotten access to the new health experience and keep checking call center and survey data to see if anything is coming from those specific users? @batemapf, I'm curious if you have thoughts on this.

not in any kind of systematic way. we could log who is accessing the landing page (va.gov/my-health) and eventually the other tools as they move over to va.gov (SM being the first one expected), but that would raise privacy issues and i am very doubtful we'd be able to easily link up contact center call info with specific users and sessions.

re:
> we're not successfully pinpointing users of the new my health dashboard

yeah the contact center data is pretty broad and the number of users who see the new landing page is pretty small. furthermore, a user seeing the new landing page might not even realize it is on a different platform (va.gov) than the existing MHV National Portal tools, so in the slim chance they had a problem and called the contact center, they might not even know to mention it.

i definitely expect the medallia data to be more targeted since it is derived right from the `Feedback` button at the bottom of the landing page.
