### ISSUE TITLE
Evaluate on screen notifications for New Secure Message

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#58771]
Evaluate on-screen notifications for New Secure Message.

[Notes with findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/discovery.md)

**TASKS**
- [x] UX evaluation
- [x] Technical evaluation

Mobile team already has a path that we may be able to leverage. Possibly requires change to secure message API.

Secure Messaging team - Leila Rassi and Bryan Riley
MHV API team - Barry Egbert
VANotify - Beverly Nelson
Mobile Team (see slack thread in comments)
Auth Experience/My VA - AJ

Notification has to link to the new secure message that triggered the notification.

### Acceptance Criteria
UX complexity and technical complexity of implementing New Secure Message on-screen notification have been documented.

**Comment by A6-toma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MHV-on-VAgov-Top-Level-View-62619a987d74510018ecc546/issues/department-of-veterans-affairs/va.gov-team/58771?planning-poker) with Zenhub @AngelaFowler82 @carafrissell1 @carlosfelix2 @ericvoshall @fmccaf1 @jonathanjnelson @keithcheung828

**Comment by batemapf** [comment]
fyi, re: new SM notifications in mobile app.

https://dsva.slack.com/archives/C018V2JCWRJ/p1686590948862849

**Comment by fmccaf1** [comment]
Are there any specific questions we're hoping to answer outside of what the process will be technically to make new secure message notifications happen? I'm thinking we'll also secure designs and any design thinking from My VA team/Angela/AJ. Any other questions that we can call out that need an answer at this point?

**Comment by A6-toma** [comment]
I think there are some questions that apply to all notification types we're going to tackle that we'll have to answer as we do this one. Some of these expand on what @fmccaf1 asked. Off the top of my head:

1. If the veteran has more than one notification, how do we want them sorted - ascending or descending order by date/time? Or something else?
2. Because these notifications are generally meant to be reminders of an action the veteran needs to take, when they click the link in the notification itself what credentials do we need to pass to the target page?  Will that vary by notification type?
3. What coordination do we need to have with the Secure Messaging/VANotify/VEText teams to make sure that when the veteran receives a new message it triggers the notification to appear? Specifically, what APIs are involved and what data needs to be in the request/response bodies?

I'm sure there are more questions, but that's a start.

**Comment by jonathanjnelson** [comment]
From flagship mobile app (demo mode) 
![IMG_4697](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/08ec891f-229c-4f2b-a70e-a9481564f7c3)
![IMG_4698](https://github.com/department-of-veterans-affairs/va.gov-team/assets/58444931/19857d83-f0dc-4317-9f5e-ddcdb1e59de6)

**Comment by fmccaf1** [comment]
Screenshot of My VA's first notification (new debt)
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/eba3004d-05ff-43a9-8d0b-0693a4edf02a)

Screenshot from [My VA's onsite notifications product page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/onsite-notifications)

**Comment by fmccaf1** [comment]
### Draft design of Notification Center MVP (from My VA sketch files)
![Notification Center - MVP.jpg](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/62773669-6f4d-4e9f-a421-0fe32b5f4a7a)

**Comment by fmccaf1** [comment]
### On-site notifications flow (from My VA's sketch files)

 [https://app.zenhub.com/files/133843125/17a2ed9f-af73-4fff-bc63-8d0e2444574c/download](https://app.zenhub.com/files/133843125/17a2ed9f-af73-4fff-bc63-8d0e2444574c/download)
