### ISSUE TITLE
Downtime Notifications - Reduce performance burden of previous DTN implementation for apps and forms

### ISSUE THREAD

**Issue by brandonrapp** [department-of-veterans-affairs/va.gov-team#5906]
Previously we employed a DTN implementation for apps and forms that was made quickly and it introduced code that would impact the performance of va.gov. Those changes were rolled back right after the scheduled downtime to remove the performance problem. A long-term solution has drafted, but the effort is not small and the forecast of downtime was also very small so this work was deprioritized. With more scheduled downtime looming there are quick fixes that we can do to refactor the previous implementation so that it can remain in the code permanently with drastically hampering performance.  This will alleviate the issue of having to add and revert this code every time there is downtime. 

- [ ] Refactor the code so it doesn't hamper performance of the FE
- [ ] Test out pager duty document to make sure that it turns on automatically when vets-api is not available.

**Comment by rianfowler** [comment]
Some notes from my conversation with @U-DON 

Goals for this sprint: 
- Remove need for large dependency (moment-timezone)
- Update default content. Override app level downtime notification for global downtime 
look at the triggering logic. Use the copy from [this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4631) and work with @peggygannon to verify via screenshots 

Other notes: 
- Maybe make a robust config
  - the public website team has to hardcode the downtime into the website currently. We should figure out a way to provide this information even when vets-api is down.  (e.g. host the pager duty downtime windows on AWS instead of through vets-api) 
- The website downtime notification relies on a failure to the vet-api call. This could be improved by: 
  - adding retry logic 
  - adding a timeout on the client side
  - improving the timeout in vets-api (e.g. if the database is down vets-api waits the maximum amount of time before timing out) 
- [testing instructions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5754#issuecomment-585450096) for the current implementation

**Comment by peggygannon** [comment]
Hello, @rianfowler and @brandonrapp Please see below for downtime notification for in-app and sign-in modal for the upcoming scheduled downtime: 
Please note: Month and times should be formatted as: 

*Months:* Jan. , Feb. March, April, May, June, July, Aug. Sept., Oct.,, Nov., Dec.
*Times:* should be written using a.m. and p.m. with periods. For example, 9:00 a.m. 10:00 p.m.
*Time zones*: ET (eastern time), CT (central time) MT (mountain time), PT (pacific time)
Spell out noon and midnight. Don’t use 12:00 p.m. or 12:00 a.m.

Sorry if I wasn't clearer about that earlier! 

Sign in message
**You may have trouble signing in or using some tools or services**
We’re doing some work on VA.gov right now. We hope to finish our work by [Date and Time]. If you have trouble signing in or using any tool or services, check back after then.

In-app message
**This form is down for maintenance**
We’re making some updates to this form. We’re sorry it’s not working right now and we hope to be finished by [Date and Time]. Please check back soon.

**Comment by brandonrapp** [comment]
Thank you @peggygannon ! Much appreciated!

**Comment by brandonrapp** [comment]
Work was all closed out!
