### ISSUE TITLE
Let collaboration cycle know about our shift from a modal to email

### ISSUE THREAD

**Issue by alevindecanini** [department-of-veterans-affairs/va.gov-team#59100]

**Comment by alevindecanini** [comment]
Carolyn will email Shane Strassberg on Platform team

**Comment by MOStudioCarolyn** [comment]
Reached out to Shira Goodman on the Collab Cycle team. She recommended we set up a 2nd midpoint review, but it will be asynchronous. We will need to send over the research findings, the new user flow, and updated prototypes.

**Comment by MOStudioCarolyn** [comment]
per collab cycle office hours:

- we will do an async midpoint review to revisit the changes (from modal to email) with organic adoption & reactivation
- they are not requiring us to do additional research
- they suggest starting the privacy review part of collab cycle asap because it may take some time
