### ISSUE TITLE
Update documentation for OOB/Manual deployments to cover approval for deployment.

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#59137]
## Issue Description
When a manual deployment is finished, it requires an approval from an admin on the vets-website repository to approve it. This is not mentioned in our documentation and has lead to confusion for multiple parties trying to do manual deployments. This documentation should be updated.

---
## Tasks
- [ ] Update the manual deployment documentation to cover the approval process at the end of manual deployments.

**Comment by rmessina1010** [comment]
Updated documentation pertaining to  vets-website manual deploy, including adding screenshots of manual deploy procedure.  In process: confirming  procedure for content-build  ( I don't seem  to need admin approval, but I am not  sure  if that is because when I ran my test manual deploy, there was no new content to push)

**Comment by rmessina1010** [comment]
Changes published. Closing.

**Comment by rmessina1010** [comment]
Changes published. Closing.
