### ISSUE TITLE
Design Intent - Design Feedback - Authenticated Experience - Profile - Notification Settings/Edit Mobile Phone Number Flow 

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#59158]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Love the mobile view and error states. It may help if you expand your user flows.
- Matthew Dingee: Look at the [Know how their information](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated) is updated pattern. What you are doing is similar. We were leaning towards keeping you grounded in the main task that you are in. When I do have an error, how do I get back to the main task? Consider adding an eyebrow (sudden header above h1) similar to this screen shot from check in team.
- <img width="208" alt="Screen Shot 2023-05-25 at 4 54 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/878a0264-9008-4ae7-b058-5fcc920a56b8">

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by mtcA6** [comment]
@andaleliz very exciting!!! when you're done this, I think we can schedule the midpoint review since I think we'll have the below items! [insert dancing emoji]

**Provide links or documents for the following:**
Finalized design prototype (desktop and mobile, with accessibility annotations)
Wireframes (with all possible user paths and error states)
~~Research plan~~
~~Conversation guide~~

**Comment by andaleliz** [comment]
Hi all! I've made the following update to our screens and this is ready to close out:
- Added the eyebrow. I'm waiting to hear back on font styling from the check-in team so may need to update that after our midpoint review
- Added a breadcrumb, to reduce cognitive load
- Updated all the "cancel and go back" to be links instead of buttons
- Updated all the mobile screens to include the name tag and help w/ grounding people in the main task
- Updated the H1 pattern so "add or update" is dynamic based on what the person is doing
- Added error states to the user flow

Here are the links:
- [Desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d)
- [Mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/p/06F02913-A0E1-4801-9D24-86E8DC71BB17/canvas)
- [User flow](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/p/293F15EA-9CCC-466C-A3B7-3E54E3111676/canvas)
