### ISSUE TITLE
Past Appointment Details - Phone Appointment 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#59170]
## Summary
When a Veteran has a past phone appointment, the page details should match the [copy doc. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#va-phone-booked-past)

## Specs
- Device: Mac
- Browser: Google Chrome

## Steps to Reproduce
**Test User:** cecil.morgan@id.me

1. Go to: https://staging.va.gov/health-care/schedule-view-va-appointments/
2. Click on `Past` link
3. Select a past appointment (phone) on April 12, 2023

### Desired Result

- [ ] The text should not be included in the details for past phone appointments ([see copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#va-phone-booked-past)).

```
VA appointment over the phone
Someone from your VA facility will call you at your phone number on file at the appointment time.
```

- [ ] `VA appointment over the phone` header should be above the facility name  ([see copy doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/content/copy-docs/appointment-details.md#va-phone-booked-past)).

 
## Definition of Done
- [ ] Desired result is achieved and/or document decisions made
- [ ] Relevant documentation is updated

**Comment by jenniemc** [comment]
Unable to use [cecil.morgan@id.me](mailto:cecil.morgan@id.me) at the time of testing. Used Grethel instead.

**Steps to validate**:
Login as grethel.g.petryniec@id.me
Click on Past link, show all 2023
Select a past appointment (phone) on February 8, 2023.

Please note Type of care is not shown because the appointment is missing "ServiceType"
cc @ldelacosta 
<img width="1666" alt="Screenshot 2023-06-09 at 12 53 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/54327023/5665a95f-f247-40e2-88da-19693b71c079">

**Comment by ldelacosta** [comment]
This looks good @jenniemc . Thanks! 
![Screenshot 2023-06-09 at 6.21.23 PM.png](https://images.zenhubusercontent.com/615208f37e69549d6e01d915/62e7d162-24ed-4ffb-b987-bbc4c71c0c4e)

@marcynadeau - this issue has been addressed. Please let me know if you experience any issues. Thanks!
