### ISSUE TITLE
CF / RVR: Interviews - Recruiting

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#5923]
Recruit participants for interviews
Schedule interviews

**Comment by amyknox** [comment]
Research Plan: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/research/caution-flags/prototype-phase/cf-prototype-rvr-discovery-research-plan.md

Discussion Guide: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/school-comparison-tool/research/caution-flags/prototype-phase/cf-prototype-rvr-discovery-discussion-guide.md

**Comment by lalexanderson-dsva** [comment]
Got it. reviewing today.

**Comment by lalexanderson-dsva** [comment]
Questions:

1. Would you like me to inflate the participant #s beyond 6 & 2 so you hit your targets? 
2. A gentle request for change in language at the opener. Instead of "We generally record sessions" - could you say something like "We like to...". Subtle difference, but it doesn't make the user feel awkward if they want to say no. 
3. Is there something specific about AZ State Univ that you're hoping they'll see? If so, disregard my question.

**Comment by amyknox** [comment]
@lalexanderson-dsva 

For the participant target - increased to 7 Veterans, 3 dependents. Our goal is 6-8, if we end up with 100% participation for the first 8, do we just ask Perigean to cancel the remaining 2? 

Changed recording language to... We like to record sessions in case we need to confirm

I don't see a question from you on AZ State. Can you point me in that direction? 

The "special" thing about it is that it doesn't have caution flags.  For the first scenario, we're interested in giving the participant a chance to engage with the Comparison Tool "in the wild" to see how they search and what they notice as they go through the flow.  Do you have a suggestion for a different school -- or thinking of a different approach to that task?

**Comment by lalexanderson-dsva** [comment]
Yup if you hit your target you can cancel
