### ISSUE TITLE
[FE] SPIKE: Severity 10:  All elements and controls do not receive focus - determine if we can fix or should be fixed by design system team

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#59334]
## Issue
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/9c782397-60a2-4458-ba08-ddce9a841320)

Original Spreadsheet Source for Issue: 
[Mobile Audit 05172023 Patient Check-in (eCheck-in  Pre-Check-in) Android.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11614896/Mobile.Audit.05172023.Patient.Check-in.eCheck-in.Pre-Check-in.Android.xlsx)

## Tasks
- [ ] [FE] Determine if we are to fix or if DST is to fix

**Comment by lee-delarm6** [comment]
Unsure which elements are not receiving focus, will need someone to confirm which elements cannot be gesture focused and how that works

**Comment by loripusey** [comment]
@lee-delarm6 did you try the recommendation in the feedback?

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/86678742/f9deb347-2308-4c1a-a7e9-6b39a8b5c8f7)

**Comment by lee-delarm6** [comment]
I was unsure if this was all input fields, but now that I did a bit more research, I found they're all controlled by the VA component design library. Their suggestion uses native Android commands, not JS or HTML, and their swipe issue may or may not be directly related to just Android devices as well, but I haven't seen it so trying to get a lock on the issue itself.

This all being said, because the VA design team controls all these components, most likely, it will be them implementing the change, or adding a property to allow for proper focus identification during this Android swipe they've listed. They could, alternately, add a property that we must then add to our va-input fields after

**Comment by loripusey** [comment]
Thanks @lee-delarm6 , I'll let the DST know in their slack channel

**Comment by loripusey** [comment]
Platform Support request submitted to the Design System team. 
https://dsva.slack.com/archives/CBU0KDSB1/p1687276321756929

**Comment by Andrew565** [comment]
@lee-delarm6 Are there specific text inputs on the listed pages that are not receiving focus correctly on Android devices, or does it appear to affect all text inputs?

**Comment by lee-delarm6** [comment]
I believe, based on the side summary, it encompasses all the inputs
