### ISSUE TITLE
Discovery on FE work for redesigned intro pages

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#59394]
This work is to replace the /start page and move BDD questions to post-login, and to modify content on the /introduction page.

Sketch file: (see final wireframes page) https://sketch.com/s/0fa92d93-0841-4c62-8112-c9c528204092

Acceptance Criteria:
- [ ] Document findings and share with the team
- [ ] Create new stories for implementation

**Comment by christinec-fftc** [comment]
We also discussed what should happen when a user returns to an in progress form and after they fill out the active duty question page. I will look into whether this is possible.

If user's answer(s) change the claim type (e.g. BDD claim to original claim), user should be redirected to the beginning of the form so they can review everything they filled out.

If user provides same answer for claim type, they should continue where they previously left off (for example, if they were on the supporting evidence page they should return there)

cc @lydiahooper @Kate-allbee

**Comment by christinec-fftc** [comment]
## Summary ##

- Deprecating the wizard and moving to one question per page would best be served by moving to the recommended [Subtask pattern](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-sub-tasks). We can build all the newly designed pages in the mocks with this tooling.

- One caveat - the design mocks are currently proposing to move the wizard questions to post authentication. This was found to be quite challenging. It is outside the scope of tooling available for VFS teams and would also introduce a new UX challenge which we currently don’t have today.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeThIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9efd631494f1e5119733f1881dade338624efe7/image.png)

- Authentication is directly tied to starting a form (not just 526, but any VA form). Asking the active duty question post-auth, means that active duty and separation date questions would now be inside of the form instead of in the wizard or subtask. This brings new challenges around what the review and submit page should look like. Also, this would allow the user to navigate all the way to the active duty and separation questions (something they cannot do today). What happens if a user navigates all the way back to the very beginning of the form and switches between original claim vs BDD. This question is similar to the discovery ticket we have open for switching claim type. 
- Here are some other issues we could file to address the currently clunkiness of starting 526.
  - Explore checking for an in progress form on the intro page. Currently 526 is asking the active duty question every time the user returns. 
  - Explore how to handle a long in progress form that spans from BDD window (90 - 180 days) to outside BDD window (less than 90 days) or to even after separation. For example, should we display a new page informing the user that their claim type has to change? What are all the questions we should re-ask because they were BDD specific or skipped?
- The proposed flow to redirect the user to the active duty upon every return is a heavy lift. We would need to (get buy in) and modify platform code to do this. Therefore, not recommended.
- This approach would also allow us to continue having a BDD version of the intro page that a user would be more likely to see before starting the form.
- Mobile vs Desktop UI: For the intro page, mobile has the content within accordions while desktop presents the content flat/exploded. The current tooling available for this in VADS is minimal (css only). So here are some options
  - Use a library (seems unlikely)
  - Roll our own (risky, heavy lift)
  - Have a consistent UI for both widths (pick either accordions or flat, not both)
  - Add breakpoint support to va-accorions (need to present relevant research)

**(Proposed) Stories**
Stories that will likely be needed for Implementation. Would be a good idea to sync with Kate when she is back and wait until after midpoint review to create all the tickets as there may be further changes.
1. Setup subtask container for desktop
 - Load wizard or subtask container based on environment check (using a toggle is a heavy lift because this is done in the ‘routes.jsx’ file, before the app is created and before the redux store is available
- Determine how much of current subtask container can be reused or should be deleted
2. Create Introduction page
3. Create subtask questions
- Are you on active duty right now?
- When will you separate from active duty?
- Start original claim
- Start BDD claim
- BDD Not eligible
4. Create mobile version of Introduction page
5. E2e tests

[Intro-pages-notes.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBIQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2262296674be9f4a8dd7a5246c2fa01d7338083e/Intro-pages-notes.pdf)

**Comment by christinec-fftc** [comment]
Things were still fuzzy so created another diagram that maps the current state of the mocks to the proposed new flow.

[intro-pages-mapping.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36a883fa33c4c73fee33962ad194c2672bb51e78/intro-pages-mapping.pdf)

Good discussion today with the team, going through both diagrams, discussing open questions and how to move forward.

**Comment by christinec-fftc** [comment]
A few other forms that also have start and introduction pages

https://staging.va.gov/careers-employment/vocational-rehabilitation/apply-vre-form-28-1900
https://staging.va.gov/decision-reviews/supplemental-claim/file-supplemental-claim-form-20-0995
https://staging.va.gov/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996

**Comment by shannonkford** [comment]
@christinec-fftc Can you add a link to the spreadsheet that shows the logic for BDD on different screens?

**Comment by christinec-fftc** [comment]
@shannonkford sure thing! that was the [526 chapter and page notes](https://docs.google.com/spreadsheets/d/1Bi65N54v2yKCFFR42aStk3SGHBXlHDOCNbchKHb8ddg/edit?usp=sharing) doc
