### ISSUE TITLE
[CAIA a11y Review] Fix accessibility issues in VA style guide

### ISSUE THREAD

**Issue by megzehn** [department-of-veterans-affairs/va.gov-team#59528]
We have some accessibility issues in our style guide that we need to address. 

Specifically: 

- There's [no H2 on this page](https://design.va.gov/content-style-guide/plain-language/use-short-sentences) and potentially others throughout the style guide. Headers skip from H1 to H3.
- The "Like this" "Not this" headers are "non-descriptive" or "not unique" headings. There's no aria detail to distinguish the difference.

CAIA needs to:

- [x] Review the new [Plain language section](https://design.va.gov/content-style-guide/plain-language/use-short-sentences) in the style guide and any other pages with "Like this" and "Not this" headers (Sara - see feedback, below in comments)
- [ ] Meet to discuss the best approach for fixing (Megan and Sara)
- [ ] Implement the content changes throughout the style guide (Megan)

**Comment by sara-amanda** [comment]
## CAIA A11y Notes
### Inquiry
- **Megan Z. reached out re: Plain Language Example page “like this” and “not this” examples.** 
### Initial Feedback
- I took a quick looksie, and it appears that there is no H2 on this page it skips from H1 to H3, so that would need to be fixed.  
- Also, yes, it does appear that these are "non-descriptive" or "not unique" headings. 
- Here is the heading list as it appears, and my screen reader also read it during my super-fast check as just the link text, no aria detail was provided to distinguish the difference.  (See image, below.)

![Screenshot 2023-05-30 at 10.13.04 AM.png](https://images.zenhubusercontent.com/63dbe59975ee0eef93e952b2/edae7a82-0dcf-4c44-9f5e-9e99772bcb8d)


### A11y Guidance
- Always use semantic headings, logically nested in the proper order.  
- Use the font-size utility to change the font size of a semantic heading instead.
- https://design.va.gov/components/featured-content#variations   
- https://design.va.gov/content-style-guide/page-titles-and-section-titles#section-titles 
- Every "do don't" box heading shares the same generic h3 making it more difficult for screen reader users to quickly determine if they’ve clicked on the right claim. These are all separate claims. 
- To a screen reader user who determines where they've navigated to by jumping to the h3, it's unclear immediately which item they're actually viewing.
- In situations where it's possible for headings to be repeated multiple times on a page, screen reader users will benefit from some way to distinguish them when navigating the page by heading. I believe using aria here would be the best bet: https://www.w3.org/TR/wai-aria/#aria-label

**Comment by coforma-jamie** [comment]
Hello @megzehn! To elaborate on what @sara-amanda said earlier:

**H2 with a smaller font size:** you can create this using a [font-size utility](https://design.va.gov/foundation/utilities/font-size) class. In this case, you would use the class `.vads-u-font-size--h3`.

**Aria-label to avoid generic headings: ** The idea here is that someone using a screen reader can navigate a page by heading. You can change the "accessible name" - the text a screen reader accesses - of the heading by using `aria-label="Some new text"`. For example, if you had a heading like `<h1 aria-label="How are you">Hello</h1>`, the screen reader would read _How are you_ out loud. The aria-label needs to make sense to a user who has no visual context for the text.

**Example** The final product could look something like:
`<h2 class="do-dont__heading vads-u-font-size--h3 aria-label="Use a conjunction to start a new sentence">Like this</h2>`
 
Let me know if this makes sense, or if you'd like to pair through a couple of these together! cc: @sara-amanda

**Comment by coforma-jamie** [comment]
@megzehn and I are meeting on July 31 to discuss.

**Comment by coforma-jamie** [comment]
@megzehn, a couple of thoughts on this proposed solution:

- Adding an aria-label requires a bit more maintenance. You need to remember that the content _has an aria-label_ and to edit it when you need to. And if this ever gets translated, you'll need to manually change that aria-label as well. 
- Another way people get around this is by simply changing the heading text entirely, making sure that it's unique. That would be a huge change to this pattern, though.

So I think the most important thing when going in the aria-label route is to *document* the aria-label usage so that future editors are aware that it exists. :)

Again, will discuss Monday, but wanted to throw this on your radar!

**Comment by coforma-jamie** [comment]
## Discussion
Spoke with @megzehn this morning! 

We determined that this pattern is used in two different situations:

1. One set of "do/don't" for one topic
2. Multiple sets of "do/don't" for one topic

For the first situation, I suggested breaking up the content on the page a little differently - adding an `<h2>` to mark that topic on the page, then 1 set of "do/don't"s as `<h3>`. That way, the H3s are within a specific topic section, and make sense in context. For example:
```
<h2>Keep the character limit for button labels to 35 characters</h2>
<p> Button labels should be as short as possible with “trigger words” that your users will recognize to clearly explain what will happen when the button is clicked (for example, “Back” or “Continue”).</p>
<h3>Like this</h3>...
<h3>Not this</h3>...
```

However, this becomes an issue for the second situation, where there's really only one category. Multiple headings don't make sense here.

We discussed turning the "do/don't" headings into paragraphs, and styling them using [font utility classes](https://design.va.gov/foundation/utilities/font-size). That way, the screen reader user, parsing by headings, wouldn't be confused by multiple duplicate headings.

I noted that maintaining two sets of "do/don't" components - some as `<h3>`, some as `<p class="...">` - would get cumbersome, and recommended to keep them ALL as` <h3> `or ALL as `<p class="...">`.

I also explained that, as useful as aria-labels are, they can get cumbersome to maintain (you need to maintain two sets of content, essentially: what's visually on the page, and the aria-label).

## Conclusions
@sara-amanda, I'd love your feedback on these suggestions:

### Change "do/don't" headings to paragraphs with font utility classes
This would remove them from heading selection entirely. I suggest that "Like this" and "Not this" aren't really denoting topics in the first place - would you list them in a table of contents? - so changing the semantics here might actually be useful.

### Use topic headings to break up "do/don't" sections, where appropriate
If a page has multiple topics, and an example of each of those topics, use headings to break up the page BY TOPIC. Easier to read for everyone, easier for AT users to parse through.

**Comment by coforma-jamie** [comment]
Spoke with @sara-amanda. 

@megzehn, **don't change the headings to paragraphs yet**. I'm new to the design systems - turns out that anything that marks off a section and looks like a heading needs to actually be a semantic heading. Makes sense.

I'm chatting with the fellow accessibility specialists to see what best practices would be here. In the meantime, reworking pages so that there's an H2 that describes the H3 "do/don't" headings will be helpful regardless!

**Comment by sara-amanda** [comment]
## CAIA Follow-Up

### Original Ticket Notes
> I took a quick looksie, and it appears that there is no H2 on this page it skips from H1 to H3, so that would need to be fixed.
> Also, yes, it does appear that these are "non-descriptive" or "not unique" headings.

- [ ] So the primary issue to tackle first is to make sure that the heading level 2 is not skipped. 

### Discussion Notes
@coforma-jamie you noted 
> that maintaining two sets of "do/don't" components - some as `<h3>`, some as `<p class="...">` - would get cumbersome, and recommended to keep them ALL as`<h3>`or ALL as `<p class="...">.
`

- [ ] According to the VA Design Standards, yes. They have to be headings. So you wouldn't be able to use the <p> mentioned above. The VA Design site says, _"Structure section titles with H2s and subsections with H3s, and so on. This provides a natural hierarchy for your content, and helps SEO."_

**Comment by coforma-jamie** [comment]
Thank you @sara-amanda - after talking with Sara and @joshkimux, we have a couple of thoughts/ideas:

- There's a nice ["before and after" pattern on PlainLanguage.gov](https://www.plainlanguage.gov/examples/before-and-after/ambiguity/) that we like and could possibly emulate? This would involve using a table instead of something more card-like. Our table component has some accessibility issues when it comes to mobile responsiveness, so we'd need to be very careful about what we put in those table cells (for example, images beyond a certain width - or perhaps images at all - would be a no-go). 
- This could instead involve an overhaul of how content is structured on the page. Instead of a "do/don't" model, you could break things up by topic and describe what should be done, top to bottom, using headings and unordered lists. See [this page on the UK.gov design system](https://design-system.service.gov.uk/components/button/) as an example. 

Josh suggested that an audit of where the pattern is used might be helpful. Do you know if this is only used in the content style guide?

Maybe we can work together to pick a specific content style guide page with a "do/don't" and restructure the content to avoid this issue completely? And use that as a model to redo other pages? @megzehn

**Comment by coforma-jamie** [comment]
## Other "low-hanging fruit" accessibility issues in the content style guide
These are issues that are unrelated to the "do/don't" boxes, that @megzehn should be able to able to fix in the content without any design system changes. Most of these are very small changes, such as fixing link text or turning some bolded paragraph text into a proper header:

- [Abbreviations and Acronyms](https://design.va.gov/content-style-guide/abbreviations-and-acronyms): “Exceptions for page titles, headers, and meta title tags” should be an H3
- [Bold & italic text](https://design.va.gov/content-style-guide/bold-text)
	- There are a lot of duplicate links here. “See this page,” repeated multiple times, isn’t parsable by someone navigating the site by links using a screen reader. Link text needs to be descriptive and make sense out of context (see [descriptive link text examples](https://www.accessguide.io/guide/descriptive-link-text)). 
	- “Use bold text only in these cases” and “don’t use bold in these cases” should be H3
- [Bulleted lists](https://design.va.gov/content-style-guide/bulleted-lists): “Punctuation for bulleted lists” should be H2
- [Button labels](https://design.va.gov/content-style-guide/button-labels):
	- There are three “like this” items beneath the bulleted list item “Always take users to the right level of access for the CTA.” These items should be a sub-list/bullets.
	- The three “like this” items have URLs that aren’t link. These should be linked and changed to descriptive text. For example, `<li>….benefits landing page like <a href=“https://www.va.gov/health-care”>VA health care</a>.</li>`
- [Dates, times, phone numbers, and addresses](https://design.va.gov/content-style-guide/dates-and-numbers): Under “Dates and years,” “Exceptions” (without a colon) and “Years” should be H3, since they’re acting as headers here.
- [System messages](https://design.va.gov/content-style-guide/error-messages/system)
	- The “scheduled downtime notifications” and “unscheduled downtime notifications” tables need to be broken up into 3 tables each: site-wide, in-app, and sign-in page. You can use a table `caption` for each table’s heading: `<caption>Scheduled notifications, site-wide</caption>`
	- This applies to all tables - table heading cells (TH) need a scope, either “row” or “col,” to indicate if it’s a heading for a row or a column. See the [Table accessibility considerations](https://design.va.gov/components/table#accessibility-considerations) for more info.
	- The “maintenance banner link” in the first table sometimes links to “https://design.va.gov/components/banner#before-maintenance”, other times “https://design.va.gov/components/banner”. If you’re duplicating link text, that link needs to go to the same place each time. So either:
		- Change the link text when the URL is different, or
		- Make sure they all link to the same URL
- [Form labels](https://design.va.gov/content-style-guide/form-labels): All tables on this page need proper table header cells. The header cells should be TH (not TD), and each needs a scope. See the [Table accessibility considerations](https://design.va.gov/components/table#accessibility-considerations) for more info.
- [Government forms](https://design.va.gov/content-style-guide/government-forms):
	- Add a scope to the table headers (as referred to previously)
	- Just a suggestion: would it be helpful to actually link to the forms listed under “Common government forms,” instead of just listing them out? Not sure :)
- [Health content](https://design.va.gov/content-style-guide/health-content): Under “3. Avoid abstract language,” “Example 1” and “Example 2” should be H4. (This of course leads to the issue of the “like this/not this” boxes always having H3 headers…)
- [Links](https://design.va.gov/content-style-guide/links):
	- Under “Embedded text links vs. CTA links,” “Use embedded text links…” and “Use UTA links…” should be H4.
	- Under “Open internal links in the same tab and window…”, the first bullet point has a couple of weird characters in the ‘target=“_blank”’ code block.
- [Naming and labels](https://design.va.gov/content-style-guide/naming-and-labels): The bold text “Don’t create new brands” and “Avoid alphabet soup syndrome” should be H3.
- [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles): Under “Page titles,” “Exceptions” (without a colon) should be H3.
- [Structure your content](https://design.va.gov/content-style-guide/plain-language/structure-your-content): I think the alt text on your example images should be more descriptive. Instead of “An example of using headers,” maybe it should be something like “An example of properly structured headers on a web page. The page title is H1, the first sub-heading is H2, and sub-headings within that section are H3.”? What do you think?
- [Punctuation](https://design.va.gov/content-style-guide/punctuation#em-and-en-dashes-hyphens): Under “Em and en dashes,” “Em dash,” “En dash,” and “Hyphens” should be H3.
- [Specific topics and programs](https://design.va.gov/content-style-guide/specific-topics-and-programs/): Under “How to suggest a topic or program entry,” the email address should be linked: `<a href=“mailto:vawebdesign@va.gov”>vawebdesign@va.gov</a>`
- [Writing for SEO](https://design.va.gov/content-style-guide/seo):
	- Under “Meta properties,” “Why they’re important” should be H3
	- Under “Title tags,” “Additional guidance,” “Example,” and “Exception…” should be H4

Please let me know if you have questions about any of these, I'd be happy to go over them!

**Comment by megzehn** [comment]
Thank you so much, @coforma-jamie and @sara-amanda !

I talked with a few people on our team, and here's what we propose as a way to fix the Like this/Not this issues. Let me know if these fixes work. 

## When we have one example per topic

For example on this [bulleted list page](https://design.va.gov/content-style-guide/bulleted-lists), we could do something like this:

[h1] Bulleted lists
(text)
[h2] Punctuation for bulleted lists
(text)
[h2] Example of punctuation in lists
(short lead-in text directly related to example)
[h3] Like this / Not this
[h2 Example of using "and" and "or" in lists
(short lead-in text directly related to example)
[h3] Like this / Not this

## When we have more than one example per topic

When we have multiple examples for the same topic, it's harder to make meaningful headings that separate the example boxes. For example, in our [Use short sentences page](https://design.va.gov/content-style-guide/plain-language/use-short-sentences) the multiple examples illustrate the same point. 

For situations like this, could we add multiple examples in one Like this / Not this box? Here's how that could look on the **Use short sentences** page.

[h1] Use short sentences
[h2] Examples of sentences edited down
[h3] Like this / Not this
(text within box includes multiple examples)

I imagine the examples could be separated by an extra return, a gray line, and/or an [h4] that says "Example 1:" "Example 2:" etc. for each one.  

Let me know what you think of these proposed solutions. Thanks so much!

**Comment by coforma-jamie** [comment]
This is great and solves the problem! The "like this / not this" will be read in the context of their section headings. :) As long as the "like this / not this" are contained within a section, and not at the same level as each other, you should be good to go. :)

**Comment by coforma-jamie** [comment]
Split this into 2 tickets, see #64483 @megzehn
