### ISSUE TITLE
Add Jenkins "build" permissions for user swirtSJW (cms-infrastructure team)

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-team#5996]
## User Story or Problem Statement
As a Jenkins user, I need access to build CMS jobs, so I can trigger deployments.

## Goal
@swirtSJW should be able to "build with parameters" e.g. http://jenkins.vfs.va.gov/job/builds/job/cms/

## Acceptance Criteria
- [ ] @swirtSJW should be able to "build with parameters" e.g. http://jenkins.vfs.va.gov/job/builds/job/cms/

We have added @swirtSJW to the 'cms-infrastructure' team and had him revoke the oauth perms in github and logout/login again.

**Comment by ElijahLynn** [comment]
Possible area to look at > https://stackoverflow.com/a/48500338/292408, but doesn't seem likely as other new users should have reported this issue.

> We hit this same error when a github organization administrator changed the organization's settings for "Third-party access" to "restrict third-party application access". Reverting to the previous settings within the github organization resolved the problem.
> 
> See github oauth-app-access-restrictions for details on how to configure that properly.

**Comment by jbritt1** [comment]
This was long-term fixed by adding Steve to the `cms-infrastructure` GitHub team. Unfortunately, due to some caching (we think) his perms still did not exist after membership was granted. For a short term fix, Steve was added manually to the same permission level he would be granted by being a member of the `cms-infrastructure` team. If we can't figure out how / what is being cached, I would bet the next redeploy of Jenkins will populate his permissions provided that he is still a member of the `cms-infrastructure` team. Closing for now, happy to revisit if that winds up not being the case.

**Comment by ElijahLynn** [comment]
Thanks @jbritt1, we will re-open if his perms disappear again.

**Comment by jbritt1** [comment]
Anytime, @ElijahLynn. Sorry for the temp workaround. Please do let me know if anything changes with his permissions.
