### ISSUE TITLE
Update the breadcrumb on the Appointments landing page (MHV on VA.gov) 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#60043]
## Description
The Appointments application will be under the MHV on VA.gov portal. We will need to update the breadcrumb structure. #60043 will focus on the Appointments Landing page. 

---

## Acceptance Criteria
Background: the `va_online_scheduling_breadcrumb_url_update` toggle is on

- [x] Given the user is on the MHV on VA.gov portal
        When the user clicks on `Upcoming VA appointments`
        Then the breadcrumbs will be updated to `VA.gov home > My HealtheVet > Appointments`
        Where the URL for `VA.gov home` is `va.gov`
        And the URL for `My HealtheVet` is `va.gov/my-health/`

### Reference
[Spike ticket #54757](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/54757)

### Design Assets
[Title tag format guidance](https://design.va.gov/content-style-guide/seo#title-tags)

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---

**Comment by JRRoof** [comment]
Blocked until feature flag is added - #59708

**Comment by ldelacosta** [comment]
Unblocked the ticket since #59709 is almost complete. Moved the ticket to the ready queue.

**Comment by melissa-lefevre** [comment]
When I looked at the A11y part of the element, it looks like "Appointments" is not keyboard-focusable and does not have a name. Is this because it is not clickable? ![Screenshot 2023-08-09 at 12.19.27 PM.png](https://images.zenhubusercontent.com/603fe0d8f45baf5a1d422aaf/9e6bee42-b34c-4597-a5c1-67b3b60dee94)

**Comment by melissa-lefevre** [comment]
The URL is behaving as expected.

**Comment by outerpress** [comment]
@melissa-lefevre elements don't need to be keyboard focusable [unless they are interactive](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Keyboard#interactive_elements_must_be_focusable). In this case that part of the breadcrumb is not interactive because it's just indicating what page you're on. So the URL behavior is correct.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
