### ISSUE TITLE
[Bug] Autocomplete API Inconsistent Results Based on Word Order

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/va.gov-team#6006]
## What happened?

This may be a problem with the autocomplete API. I don't know if the same API is used in multiple areas, but the behavior of the autocomplete seems similar.

The number of results is not consistent if you switch the word order:

* GIBCT

  - search for "beauty academy" and the dropdown will not show any results. Press <kbd>Enter</kbd> and 88 results appear.  

    <details><summary>Screenshot</summary>

    
    ![Screen Shot 2020-02-18 at 4 57 07 PM](https://user-images.githubusercontent.com/136959/74866983-70348780-5319-11ea-96ff-d7f1db2100de.png)
    </details>

  - search for "academy beauty" and one result appears in the dropdown and in the search results.

    <details><summary>Screenshot</summary>

    
    ![Screen Shot 2020-02-18 at 4 56 12 PM](https://user-images.githubusercontent.com/136959/74866889-3d8a8f00-5319-11ea-9a46-d9a6a211170a.png)
    </details>

* New disabilities (form 526)

  - search for "left knee" and multiple unrelated results appear

    <details><summary>Screenshot</summary>

    
    ![Screen Shot 2019-11-27 at 3 49 13 PM](https://user-images.githubusercontent.com/136959/74867120-ba1d6d80-5319-11ea-9f2d-80c0d68682d4.png)
    </details>

  - search for "knee left" and completely different results, some that contain "knee", appear

    <details><summary>Screenshot</summary>

    
    ![Screen Shot 2019-11-27 at 4 00 04 PM](https://user-images.githubusercontent.com/136959/74867288-036dbd00-531a-11ea-956b-e6c6756c03a7.png)
    </details>

## Specs:
- Device: Any
- Browser: Any
- Test User: N/A

## Steps to Reproduce

Using the GIBCT

1. Go to https://staging.va.gov/gi-bill-comparison-tool/ (no need to log in)
2. Type in "beauty academy" in the search; no dropdown results are seen
3. Press <kbd>Enter</kbd> inside the input, or go to https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=beauty+academy - it will show 88 results
4. Now in the search input at the top, enter "academy beauty"; only 1 result appears
5. Press <kbd>Enter</kbd> inside the input, or go to https://staging.va.gov/gi-bill-comparison-tool/search?category=school&name=academy+beauty - it will show 1 result

New Disability

1. Log into user 228
2. Go to https://staging.va.gov/disability/file-disability-claim-form-21-526ez/introduction
3. In step 1, choose "A new condition"
4. In step 2, choose "Yes" to add a new condition
5. Enter "left knee" and "knee left" to see the different, and unrelated, results.

## Desired behavior

The autocomplete should display results that are related to the query _and_ be consistent no matter the word order of the query

## Acceptance Criteria
- [ ] Autocomplete results in the dropdown should match the results (GIBCT)
- [ ] Autocomplete results in the dropdown should provide consistent results no matter the word order.
- [ ] Autocomplete results should _only_ match the query

**Comment by SMLuthi** [comment]
Currently, the way the GIDS API is handling automatching on their end is by matching the search term from the beginning as opposed to matching the term anywhere in the string. This is due to how they wrote the index. This is the response I've gotten:

`searching for a substring would be less efficient and that endpoint has caused cascading performance issues from a quantity vs. response perspective.`

aka, it would severely hamper performance if we began searching any other way. I believe, to implement autocomplete how we want, would take a serious overhaul of that system.

**Comment by Mottie** [comment]
@saderagsdale This is still a problem, but ultimately an issue with the platform code. I did try to add a method to include a custom algorithm, but I was told it'd be [better to fix the core matching algorithm](https://github.com/department-of-veterans-affairs/vets-website/pull/18786).

I don't think we should close this ticket, but we don't need to be assigned to it anymore.

**Comment by cohnjesse** [comment]
@saderagsdale it seems like it needs to be fixed at some point but there might not be a clear path forward. I would suggest we use a pre-built algorithm that works for what we need out of the box instead of doing our own. If what we are using doesn't fit the bigg then we may need to swap it out for something else. Also might be good to work with UX a bit to determine what exactly we are trying to achieve here.

**Comment by jsokohl** [comment]
Huge opportunity to coordinate with #sitewide-ia and other IA resources to consider taking a controlled vocabulary approach.
