### ISSUE TITLE
Error message at start

### ISSUE THREAD

**Issue by lydiahooper** [department-of-veterans-affairs/va.gov-team#60330]
ICN 1057155096V233563

I am trying to submit my claims. every time I finished the process of "submit a claim" I put in my date of leaving the military and it says that I have 73 days currently until I can not file a "BDD" claim.  When I click the "start your BDD claim button" it proceeds to the next page and says "we need some more information for your application, we need some more information from you before you can file a benefits delivery at discharge claim with VA form 21-526EZ. Please call veterans Benefitd Assistance at 800-827-1000 (TTY:711). I was doing nothing as I had just opened up my computer. I have tried multiple different methods as in Microsoft edge, safari, google chrome, and explorer. I have also used my laptop and my cellular device and I have been trying to submit it they last week or so. Please help I need to get this submitted before I run out of time to do so.

**Comment by christinec-fftc** [comment]
@Kimberley2019 we looked into the logs for this ICN and we were able to find related logging. It looks like the user is getting this error due to missing SSN in their profile. Will your team be able to help direct the user to the appropriate process for getting this filled out?

On our end I'll file a new ticket to look into displaying more specific error messaging for missing SSN. cc @lydiahooper @aurora-a-k-a-lightning

**Comment by christinec-fftc** [comment]
[Error messaging improvement ticket](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/60420)

**Comment by tblackwe** [comment]
@austinjprice @RakshindaAslam This issue is not resolvable by DBEx teams. The next steps have been communicated and we have a ticket to improve error messaging for user in future. 

Are you ok with Engineers closing issues or do you want us to progress ticket into PM/PO review first and let you close it?

**Comment by christinec-fftc** [comment]
Closing this ticket as instructed. 

@RakshindaAslam @austinjprice Info has been relayed to the CC team about missing SSN and future story/improvement created.
