### ISSUE TITLE
Design Intent - Design Feedback - Authenticated Experience My VA, Onsite Notifications, Notification Center MVP

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#60395]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Great explanation of this product!
- @aagosto90 what happens if I have a debt notification and I pay it? Does that notification stay on the MyVA page? I believe you said the only way those notifications disappear is when the user dismisses them. You may want to think and test around that. And to that same point, will there ever be more than 1 notification for the same thing? For example, if I have not paid my debt from 2 months ago, will a get another notification?

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should**: Matt: Icons are helpful on the name page but explore taking away the blue version here where you have a long list and it can be distracting

**Comment by aagosto90** [comment]
> What happens if I have a debt notification and I pay it? Does that notification stay on the MyVA page? I believe you said the only way those notifications disappear is when the user dismisses them. You may want to think and test around that. And to that same point, will there ever be more than 1 notification for the same thing? For example, if I have not paid my debt from 2 months ago, will a get another notification?

Answer: There is currently no way for our system to detect that a debt has been paid, so a user must manually dismiss a notification from My VA for that to disappear. Those notifications will always live in the notification center as an archive of past notifications. We definitely realize that's not an ideal user experience and [Veterans said so in testing too](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/payment-history/discovery-and-research/june-2022-research/research-findings.md#1-users-will-be-able-to-clearly-see-and-read-the-notification-at-the-top-of-the-page-and-will-know-how-to-act-on-it-if-they-wished-to-see-more-details-or-resolve-a-debt). Ideally if you pay a debt, you wouldn't see the notification at least on My VA anymore. It's a data limitation problem that the debt resolution team is working on. They only show the latest debt statement in the debt portal and don't have a way to tell if an individual debt has been paid, so we have no way of getting that info either yet unfortunately.

A user won't get a second notification of the same type unless we code it to do that (which we don't plan to). The new debt notification is only sent out once. There are other notifications for the same debt through VA Notify that include emails if they're not paid, but we don't have on-site notifications tied to those.

**Comment by aagosto90** [comment]
@humancompanion-usds For the feedback to consider how the icons look on the list page - I explored an [option](https://www.sketch.com/s/1cc4cb25-7de4-492c-bb91-edef871b2a89/a/bLa9EVV) where maybe we don't use icons in the notification center and we think it's hard to scan visually and makes them not really resemble notifications anymore. There is an ongoing discussion about the notification icons with the MHV team because they don't agree with how we've categorized the notifications so far, so we'd like to see where that topic goes anyway in conjunction with how to address this feedback once our PO is back in a couple weeks (before our next collab cycle touchpoint on this). 

We also think this will be less of an issue once we build on the notification center and incorporate [read vs unread](https://www.sketch.com/s/1cc4cb25-7de4-492c-bb91-edef871b2a89/a/L4nMGxy) but we're definitely open to iterating on how the icons appear in the notification center. More to come and appreciate the feedback!
