### ISSUE TITLE
[Research] Prepare for Financial Disclosure/Priority Group Research

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#60690]
As a Veteran, I would like to view and update my Financial Disclosure information, and view my Priority Group online so that I can make sure the VA has accurate information and my correct Priority Group, and not have to pay co-pays if I don't need to.

### Acceptance Criteria
- Write Research Plan
- Write Conversation Guide
- Review these with VA.Gov Profile Team
- Make any required changes
- Go through Research Review and make changes

**Research Review AC:**
- Once wireframes and research plan are done, reach out to research review folks
- UX will prepare to present
-[ See Ecosystem Slide Deck for more info](https://docs.google.com/presentation/d/1E6lK7RMJCwzaLWRzz5rbvUIz9fqlMslA-23GsusvQdI/edit#slide=id.g1e1e7467903_0_129)
- Conduct Meeting
- Make any recommended changes

## Background
The 10-10EZR form is used by Veterans to update their information in their VA Profile. This information includes: mailing address, phone #, SIGI information, Dependents, Insurance, Next of Kin, Emergency Contact, insurance information, and Financial Disclosure. 
The HEC and VEO stakeholders have requested an online 10-10EZR form. While doing discovery for this request, the team learned that there are roughly hundreds of thousands of EZRs filed every year, that some information editable via the paper EZR can be change via the VA.Gov profile, and that the primary purpose for the EZR is to update Financial Disclosure--a capability that is not currently online. 
This team needs to research if Veterans would like to have the capability to review/update financial information online, as well as the ability to view their Priority Group and what it means to them, and if so how and where this capability should "live." 

### Resources
- [Epic](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/57417)
- 10-10EZR paper form PDF (attached)[https://app.zenhub.com/files/133843125/648d269f-69ef-425b-bd82-a78b6af9c7d1/download](https://app.zenhub.com/files/133843125/648d269f-69ef-425b-bd82-a78b6af9c7d1/download) 
- [Research Plan Template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-plan-template.md)
- Overview of EZR form fields and VA.Gov profile fields (attached)[https://app.zenhub.com/files/133843125/adacb673-4c31-4c71-b236-229cf55a5c3d/download](https://app.zenhub.com/files/133843125/adacb673-4c31-4c71-b236-229cf55a5c3d/download) 

### Financial Disclosure Use Cases

- Learn more about how Veterans would like to go about applying, discovering eligibility and getting the most health care benefits they qualify for and what amount of information they feel they need to provide vs what VA should have in that process.
- Learn more about how Veterans would like to go about providing updated information, especially financial and dependent updates, that could impact their health care benefits post-application/initial enrollment.
- as a 0% SC veteran with one dependent who earned $15K last year, i may need to file an annual financial disclosure, so i can maintain access to beneficiary travel
- As a 0% SC veteran with one dependent who lost their $55K/year job and now has no income and was previously assigned to PG 8, i want to file a new financial disclosure, so i can access the medical benefits package under PG 5, be exempt from medication copays, and be reimbursed for my travel expenses.
- As a 20% SC veteran with one dependent who earned $15K last year, i may need to file an annual financial disclosure, so i can maintain access to beneficiary travel
- As a 30% SC veteran who recently enrolled in medicaid, i want to tell VA that im now enrolled in medicaid, so i can access medication copay exemption

### Priority Group Use Cases

- Learn more about Veteran's mental model when applying for health care benefits including the terms they use and how they see levels of benefits/Priority Groups/copays impacting them during the health care application process, during and ongoing after.

### Outstanding Questions

- Do Veterans want this?

**Comment by jessicastump** [comment]
Taking what we can leverage here from the registration only/eligibility mental model plan and convo guide previously started.
[Research folder here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure)

**Comment by jessicastump** [comment]
[Research folder link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure)

[Mural discovery board](https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1687381992402?sender=uadf1ed7fe7c76f0914967329&key=2694912f-19c7-4254-8e86-ce74e6a4bdf0) - research questions and visuals

**Comment by jessicastump** [comment]
Here is the current state of this [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure/research-plan.md) and [convo guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure/conversation-guide.md).

@alexseelig This is somewhat blocked now pending a decision on which wireframe scenario to use for the Veteran research and any other feedback/collaboration with other teams.

**Comment by jessicastump** [comment]
@alexseelig Per meetings over the past couple of days, the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure/research-plan.md) and [conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/research/2023-06-Priority%20Group%20and%20Financial%20Disclosure/conversation-guide.md) have both been updated with the latest direction scenario and dates. This is ready for any needed final reviews and approvals so we can submit to research review/begin recruitment.

**Comment by jessicastump** [comment]
[[Research] Make updates to Research Plan/Convo Guide based on AE/KM feedback#62150](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/62150)

**Comment by jessicastump** [comment]
Going to do another pass, but I believe feedback received has been incorporated into the research guide plan. The remaining item to address tomorrow is getting pilot sessions scheduled then this is ready to submit for review.

From Slack thread:
Pilot sessions
We want to run 3 so all the new(ish) designers get a practice run in. Any volunteers from the team to play the role of the Veteran in these pilots?
We need to get these scheduled - the who and the time - before we submit this for research review
They should happen between Friday this week and next Tuesday if we want to start on Thursday

**Comment by jessicastump** [comment]
Adding from ticket [[Research] Make updates to Research Plan/Convo Guide based on AE/KM feedback#62150](https://github.com/department-of-veterans-affairs/va.gov-team/issues/62150)
that will be closed

Liz Lantz's feedback:
Research plan
Check assumptions and terminology used to remain Veteran-centric
☝️ I love this outcome 😍
Currently, do Veterans prefer to provide updated information in person at appointments or over the phone?
I assume these are the only two ways a veteran can currently provide this info - so you’re wondering of the two options, which do they prefer? Or could “online” be a valid preference in response to this research question?
Do dependent updates cross benefits in the Veteran’s POV or do they associate them only with their health care benefits?
I think to truly answer this question, you should consider adding Veterans who have disability benefits and dependents to your recruitment criteria. If a person only has health care, or disability and no dependents, they may not have any idea that dependents mean different things in the VA ecosystem, depending on the benefits they are associated with. Other combinations might work but I’m not familiar w/ dependents outside of disability
Recruitment criteria
You might want to specify VA health care in your screener question, just to be extra sure you don’t get someone who has applied for health care elsewhere.
You may want to consider requesting a mix of ages, since you’re interested in learning more about how well people understand priority groups and how that fits into their health care. People who have had VA health care for a long time may have developed a strong understanding out of necessity over time whereas people who are new to it might not get it yet.
In the spirit of equity and inclusion, I would love to see you add more underrepresented groups in your primary criteria: people who identify as other than white, women, people with cognitive considerations (diagnosed or otherwise).
Team Roles
I love how you guys are approaching this as a team and taking turns moderating and with the pilot. Is the purpose of 3 pilots so everyone gets a chance to practice, or do you anticipate more changes between each one

Conversation guide
Overall comments
I don’t have experience participating in a study where there is a rotation of moderators, but overall, I wonder if there should be more guidance throughout the guide about follow-up questions, optional probes, etc. Just to minimize variety across sessions and attempt to get the most consistent data possible over the course of the study. I noticed the health wayfinding study that is currently under way has “Optional probes - very flexible, adapt as appropriate depending on participant behavior” throughout their conversation guide which I really liked and plan to use in future guides that I write.
This is totally just me, but you may want to rephrase questions that could be answered as a yes or no. I’m not sure if everyone on the team has the same level of facilitation experience, but in the spirit of minimizing variation I think this could help. I’m making some assumptions on what you are really going for here, but one example is the “Do you know what priority group you’re in…” question. Assuming you’d follow up with “what does that mean” or other questions to get them to elaborate on a “yes or no”, you could start with “Tell me about the priority group you are in…” which starts the whole section of on a more conversational, open note.
Similar feedback for “Can you tell me where you would like to be able to access your Priority Group number? Why do you list [this] place?” Instead you could say “What are some places it would be helpful to be able to access your PG number? Why?”
Warm up
What is the goal of the warm-up question, “And do you sign in every time or how often do you sign in?”
dependents section
I wonder if these prompts will adequately support your research question “Do dependent updates cross benefits in the Veteran’s POV or do they associate them only with their health care benefits?” It feels to me like the questions won’t really get to insights about the POV with crossing benefits, but it could totally be that I don’t fully understand what you’re going for or the follow-up questions that’ll be asked.
EZR Tasks
In this task, you ask how a person would like to receive a communication. Earlier in the session, they answered a question “Have you been notified that since you enrolled that you had to provide new information or updates?” - you might get a more objective response from the participant if you use whatever information they shared about notifications they received earlier in the session vs asking them to predict their preference. Or maybe you could use what they said to tee up the scenario to begin with.
In the [Global questions] section, bullets 2, 3 and 4 feel duplicative of the bullets under [Where to find]. I wonder if the bullets under [global questions] would be better as follow-ups to the [where to find]? I think participants would touch on all of those things as they walk you through, though I’m not sure if “annual income” is different from “financial information”, so I could be misunderstanding.
If you leave those bullets under [Global questions]: “What would you be looking for when you first login to update this information? Something in the sidebar or a notification?” I would recommend adding a note for moderators here to say this only if a person mentions they’d login. I assume every participant will, but you know what they say about assumptions 😉
I’m sure you’ll get at this but if they do validate the profile hypothesis, it’ll be super helpful to learn where exactly within the profile they’d expect to do it. if it’s a new section, we’d love to hear what they would call that section, and what else they might expect to find within it. Could you add those as follow-up questions please?

**Comment by jessicastump** [comment]
Feedback from Robyn Singleton: 

> Recruitment-wise, the only thing that must be addressed before I put in the request to Perigean is to provide a couple screener questions: (1) for cognitive disability (the [#inclusive-research](https://dsva.slack.com/archives/C033ZS9E7EW) has some good examples to draw from) and (2) for immigrant origin. Perigean doesn't have that info in their database. Also, it's real fuzzy how Perigean considers (if at all) secondary criteria, so would recommend identifying the sample you want and communicating that all out as primary criteria.
>  Some suggestions that are more about giving you food for thought:
> You have a lot of research questions and they're all really good. I like how you articulate sub-questions under larger questions. The convo guide is also really good. However, I was having a hard time mapping how your convo guide fully answered all your research questions. Might be worth confirming through a table or matrix of some kind that your most important research questions are being answered via your convo guide, and then if any are not, deciding whether you care or are fine losing that RQ.
> There were some typos in your intro paragraph for the Research Plan
> In the convo guide, the third topic seems like it would benefit from pulling up [VA.gov](http://va.gov/), if I'm understanding it right. Otherwise, you might get either fuzzy answers or answers like "I want it at my local VSO", which probably won't help you with design decisions. You could start broad, then ask them to bring up [VA.gov](http://va.gov/) and show you there... Just a thought.

[Board on Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687381992402/ac027de3375351079c9cbc93d1662510ffd3cb1a?wid=0-1689705630711&outline=open) used to evaluate research questions to convo guide.

**Comment by jessicastump** [comment]
[Submitted to repo for review](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/346)
