### ISSUE TITLE
Discovery on hard-coded assets in content-build

### ISSUE THREAD

**Issue by CBonade** [department-of-veterans-affairs/va.gov-team#60815]
## Description

re: https://app.zenhub.com/workspaces/frontend-cop-backlog-6452b043f27c8b0011a25236/issues/gh/department-of-veterans-affairs/va.gov-team/43866

As this ticket is dated and may or may not be relevant anymore, we need to research into what needs to be done, write up document, provide potential solutions (if possible).

Does it belong in the COP or a project?

Does it still need to be done?

## Tasks

- [ ] Research what needs to be done for this task
- [ ] Document the answers to the above listed questions and report them back to the COP at the next meeting.

**Comment by ataker** [comment]
This ticket is still a good step towards separation between `vets-website` and `content-build`. There is still value in completing it.

Building on Chris Alexander's POC is think is the correct solution. 

The basic outline is:
1. Instead of loading the app bundle directly, `src/site/includes/header.html` in `content-build` loads `load-app.js`, which is provided with an entry name.
2. `load-app.js` uses the provided entry name to load the appropriate js and css files.

We would need to decide where the `load-app.js` file will be located and make sure it's added to the `build/generated` directory when `vets-website` is built.

There is a concern about whether React will break when loading async like this.

This work seems too large for CoP work.
