### ISSUE TITLE
Review of 508 finding from Patient Check-In

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#60912]
## About your team

- Team name: Patient check-in
-	OCTO-DE product owner:  Kay Lawyer
-	Product manager:  Lori Pusey
-	Designer: Ben Brasso
-	FE engineer: Brian Seek
- Accessibility specialist: N/A
- Content writer: Kelly Smith
-	Product/team Slack channel: #check-in-experience
 
### What does your team need support for? Check all that apply.
- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [ ] Accessibility review of wireframes and/or prototypes
- [x] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] Something else 
 
### Give a brief description of what your team needs support with:
We recently had an accessibility audit of our applications. We received [this feedback](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59305) about our focus order starting with the H1. Our apps are single page applications that utilize react router, meaning that if we don't have a script to move focus, then the user gets stuck in un-predictable focus areas when navigating. At some point early in the development of these applications, we created a useEffect that updates focus to the H1 on page load.

Any thoughts or feedback on this? If not the H1 where should we be moving focus on page component load? Removing the script like the audit suggests, could have a worse result in leaving focus at the bottom of a page or form. We did get some positive feedback on the page focus on navigation from screen reader users in the past, so I wanted to make sure we were doing the right thing here.

Update: since initially writing this, I did test and focus is more or less working as expected when removing the script. But I still want to double check this since we were intentionally doing the H1 focus for a reason at some point.
 
### Will this new product be released incrementally (for instance 25% of users initially)? 
  - [ ] Yes
  - [x] No
 
**Note:** If you checked yes, we'll reach out to discuss details about the content in the react widget.
  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
 
### Will this work be going through the Collaboration Cycle?
- [ ] Yes 
- [X] No
 
#### If yes, please check all of the phases in the Collaboration Cycle you have completed: 
- [ ] Design Intent
- [ ] Midpoint Review
- [ ] Staging
 
### When does this work need to be completed?
- Content, Accessibility, and IA work needed by:  No date specified
  
## Supporting artifacts
*Please provide supporting artifacts as available.*

- Link to product outline:
- Link to or attach user flows:
- Link to prototype or mockups:
https://app.abstract.com/projects/ab30c34e-e2f9-4d3e-bb96-3b683b006c24
- Link to your research plan: 
- Link to any epics/issues that may be helpful:
https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/59305

#### Do you plan to bring this to an upcoming content office hours session?
- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health  content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] No, but I'd like to schedule time to talk about this request
- [x] No, let's work asynchronously and meet if needed

 **Note:** If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)
- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next.

**Comment by brianseek** [comment]
updates form the original slack thread: https://dsva.slack.com/archives/C8E985R32/p1687799363417829

Not sure if this can be closed or if you want to dig in to it a bit.

**Comment by sara-amanda** [comment]
## Collective A11y Feedback

⛔ **No action needed at this time.**

- Thank you, @brianseek  for creating this ticket, to address auditor findings. 
- It appears the consensus is to leave as is for now, with the potential development of standards for Va.gov.
- Documenting feedback below from Slack, for quick reference. 

### David Kennedy
@davidakennedy 
- Just as a heads up on this one. We use this approach (placing focus on the h1 on all/most single page application forms across [VA.gov](http://va.gov/)), so it sounds like we need to sync with the 508 Office so they understand the reasoning. 
    - We don’t want to have a few teams break from this and create inconsistency. 
    - I’m sure the CAIA accessibility specialists and others would agree that we want to keep it this way.
- In general, we’ve used this approach because when someone is filling out a form that they’ve started, we assume that they want to finish it, so we manage focus to that section of the page. 
    - That way, they don’t have to expend effort to traverse the header every time a form view changes (some forms have lots of views). That would be very tedious. 
- ([Link to DK's feedback in Slack](https://dsva.slack.com/archives/C8E985R32/p1687881542248259?thread_ts=1687799363.417829&cid=C8E985R32))

### Laura Flannery
@laflannery 
- I just saw this and wanted to note that I am also currently working with a team using the new subtask pattern to create an app and we are actively updating things to put focus on the H1 for each new screen within the form flow. 
- We are doing this for the reasons mentioned here already so I would also be very interested in any potential changes to this recommendation. 
- [(Link to Laura's Feedback in Slack)](https://dsva.slack.com/archives/C8E985R32/p1687986355950999?thread_ts=1687799363.417829&cid=C8E985R32)

## Next Steps

- Per Martha @artsymartha68: Develop standards on [VA.gov](http://va.gov/) that might be cited when being audited.
- This is also being shared with Christopher Walker.
- [(Link to Martha's Feedback in Slack)](https://dsva.slack.com/archives/C8E985R32/p1687988896269559?thread_ts=1687799363.417829&cid=C8E985R32)

cc: CAIA @coforma-terry
