### ISSUE TITLE
Request Design Review - GIBCT Caution Flags

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va.gov-team#6091]
The GIBCT contains some schools that have cautions against them. This work helps update those flags.

* **InVision GIBCT Caution Flags** - https://bahdigital.invisionapp.com/share/AGIACXL4ZJB
* **Related accessibility review** - https://github.com/department-of-veterans-affairs/va.gov-team/issues/4919

**Comment by CrystabelReiter** [comment]
Again, great job at making the caution flags very visible and clear. Enjoyed hearing the context on the fact we're warning users to stay away from these "yellow" flags

Try:
 Try Asking users during testing what the amount of these caution flags mean to them (especially the ones with 2-3 flags). In the design system's usability section for alerts, it says "But don’t overdo it (alerts)— too many notifications will either overwhelm or annoy the user and are likely to be ignored." I suggest asking whether these alerts overwhelm or successfully communicate to them that they should avoid the school. 

Consider: 
Consider Making the "campus closing" caution flag a red alert, to communicate priority with the amount of alerts. 
Consider combining the content in 3 separate alerts into 1. The design system gives these guidelines on "full width alerts" but could be worth exploring "Do not stack - max is one per page at any one time. (If multiple emergency issues occur at once, make message content combined and link out to a landing page or to individual affected medical centers, for example.)"

**Comment by 1Copenut** [comment]
Thank you all for meeting with Crystabel and I on Friday. It was great seeing how the caution flags have evolved and learning more about the stated goals.

I have just a few things, mostly considerations related to Crystabel's notes and future enhancements:

**:heavy_check_mark: Consider**
* Consolidating the cautionary warnings into one `<Alertbox />` component, and using a paragraph to call out single warnings, or an unordered list if there are 2 or more. In pseudo-HTML, this could look like:
```html
<!-- If nested under the H1 -->
<h2 id="warning-header">This school has a cautionary warning</h2>
<p>Deceptive advertising lawsuit</p>
```

```html
<!-- If nested under an H2 -->
<h3 id="warning-header">This school has cautionary warnings</h3>
<ul aria-labelledby="warning-header">
  <li>Deceptive advertising lawsuit</li>
  <li>Financial practices under review</li>
</ul>
```

* Possibility of adding a filter to hide schools with warnings or closures from the search results
* Showing any historical issues with a reasonable time box (3 years, 5 years, etc.)

**:warning:Should**
* Nest the alert or alerts with proper heading level. See the [Props section, specifically the `level` prop](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/visual-design/components/alertbox/).

**Comment by amyknox** [comment]
Thanks for spending the time with us last week and your thoughtful comments here.  We've reviewed and this is where we're at currently: 


**Can / Will Do**

- Try Asking users during testing what the amount of these caution flags mean to them (especially the ones with 2-3 flags). In the design system's usability section for alerts, it says "But don’t overdo it (alerts)— too many notifications will either overwhelm or annoy the user and are likely to be ignored." I suggest asking whether these alerts overwhelm or successfully communicate to them that they should avoid the school. CR

- Consider the possibility of adding a filter to hide schools with warnings or closures from the search results. TP

- Should Nest the alert or alerts with proper heading level.  TP

**Considering / Going to Test**
_Considering combining the content in 3 separate alerts into 1.  Since there’s not guidance on the non-full width Warning alert, we’ll explore the presentation of multiple alerts vs. a single alert during testing to see what performs best._  

- The design system gives these guidelines on "full width alerts" but could be worth exploring "Do not stack - max is one per page at any one time. (If multiple emergency issues occur at once, make message content combined and link out to a landing page or to individual affected medical centers, for example.)" CR
- Consolidating the cautionary warnings into one <Alertbox /> component, and using a paragraph to call out single warnings, or an unordered list if there are 2 or more. TP

**Considered / Not Doing**

- Consider making the "campus closing" caution flag a red alert, to communicate priority with the amount of alerts. 

_We are opting to stick with the yellow alerts because they appear to be focused on back-end, technical issues that stop users from completing their task.  The School / Campus closing updates don’t align with this type of issue exactly and we feel the yellow alerts will work better in the GIBCT._ 

- Consider showing any historical issues with a reasonable time box (3 years, 5 years, etc.). TP

_Education Service has an SOP for when, why and how caution flags are applied to facilities and when they’re removed. We wouldn’t want to unnecessarily penalize schools that have had flags removed by showing negative, resolved issues in a historical view._

**Comment by 1Copenut** [comment]
@ccruzgra 
Thank you for reaching out to us on Friday for another look at the Caution Flags. I will add my small feedback items here. Please let me know if you'd like to discuss any of them further.

* I'd like to see a sentence or two in the search results page that explains to users the search will update on input change (selection made from dropdown, checkbox checked/unchecked, radio changed). This will help us improve our standing with [SC 3.2.2 - On Input](https://www.w3.org/TR/UNDERSTANDING-WCAG20/consistent-behavior-unpredictable-change.html)
