### ISSUE TITLE
Midpoint Review - Design Feedback - Authenticated Experience, Profile, Notification Settings, Updates to Edit Flow (first example using mobile number)

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#61088]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Would be helpful to see a whole flow with real text to see the whole experience of adding a mobile number

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Should** change link from “Cancel and go back to last page” to “Cancel”
- **Consider** adding language on the sub-page (add mobile phone) that helps the user understand that this will update their profile.
- **Consider** creating a consistent minimum page height to reduce jumping when navigating from one page to the other

**Comment by andaleliz** [comment]
Hi! Since I wasn't at midpoint, I need a little more clarification. Apologies if this was addressed during the meeting itself.

>Would be helpful to see a whole flow with real text to see the whole experience

Can you share more about what it would help to see that? Are there particular things that aren't clear about the flow or mock-ups we have already?  If so, I'd prefer to update the existing flows we have to bring more clarity to them.

We try to minimize the number of artifacts we need to maintain over time so I feel a little resistant to creating additional documents without understanding the benefit. 

Otherwise, it looks like there aren't any other edits or change we need to make 🎉 - is that correct?

Thanks!

**Comment by shiragoodman** [comment]
hey @andaleliz  - @naomimarcussen completed this review so I'll hand it off to her. The recording is available in the epic ticket so it might be best to watch that.

**Comment by naomimarcussen** [comment]
@andaleliz We certainly don't want to add extra work for you. Perhaps you already have this, but to make sure we're considering all the things, it would be helpful to see an example of these templates applied to the specific use case of adding a mobile phone number. Currently, we only see screens with generic text in the [user flow](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/p/293F15EA-9CCC-466C-A3B7-3E54E3111676/canvas), [desktop](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d) and [mobile](https://www.sketch.com/s/1fd4d140-84ad-4301-9c74-d5cebc4a012d/p/06F02913-A0E1-4801-9D24-86E8DC71BB17/canvas) mockups. You may have a mockup of an entry screen that might be helpful to add to the user flow.

As far as edits go, aside from changing the link from “Cancel and go back to last page” to “Cancel”, the only other thing that might be addressed is when the user is on the edit page, making sure they are clear on where this info is being updated/added to (i.e. profile) The placeholder text for for "Field label" didn't provide guidance to include that information for the user. 

![Screenshot_2023-06-28_at_5_23_23_PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/56055287/dd2efad5-7e2f-4850-a14f-1fadb84945be)

Hope this makes sense. Feel free to reach out with any other questions.

**Comment by andaleliz** [comment]
Thanks for the additional context @naomimarcussen! We do have the flow applied to the specific use case of adding an _email address_, [in the original prototype](https://codepen.io/surfbird/full/gOjmPyj) but it doesn't include the changes we've made since design intent (and I don't want to update it because it would change the artifact we conducted research with).   I know [the mobile flow for notification settings](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) was briefly shown in the review meeting, and I'm wondering if a closer look at that might help to clarify things for the team. Let me know what you think.

If not, I can create a flow for the purposes of this review and delete it once the Platform team feels comfortable that everything has been reviewed so we can keep artboards that need to be maintained to a minimum.

**Comment by naomimarcussen** [comment]
Thank you @andaleliz! The [mobile flow for notification settings](https://www.sketch.com/s/afd69a1f-72d2-430b-9b62-285e9d3f479c/p/B5792AF8-87F2-496D-AE7A-DAD1448A6018/canvas) was what I was looking for! It would be helpful to add that to the user flow section of the ticket for future reference.

**Comment by andaleliz** [comment]
Oh great! I'm glad that works - I don't think that flow existed when the ticket was created, but definitely good to know for next time that those kind of artifacts are helpful.
