### ISSUE TITLE
[Design] 10-10CG - Improvements: Figma Updates for 1010CG Confirmation Page (design maintenance)

### ISSUE THREAD

**Issue by davidakennedy** [department-of-veterans-affairs/va.gov-team#61093]
## Task Description

We don't have a good source of truth in Figma for confirmation page in 1010CG form. Part of it exist elsewhere in Sketch, and should be copied. It also needs a mobile version. This would help with future work in this area, if it comes up. We could also add some of it to the flow board in Mural.

## Notes and References
- Check out the existing screens in [Submission confirmation - 42322](https://www.sketch.com/s/5a676881-7aa8-4054-9b6e-34d86ced43d8). Also, it needs a mobile version.
- This work grew out of #57951.

## Acceptance Criteria
Design team members can view new Figma files, both desktop and mobile, clearly showing the confirmation page.

## Deliverables
- Figma files for the conformation page of the 1010CG.

**Comment by hdjustice** [comment]
@jessicastump @aagosto90 @katelyncai @IMHieuVo - How about this ticket, would yall say it is still valid (but for Figma)?

**Comment by jessicastump** [comment]
Yeah - there never was much inherited in the design file for the intro page. There is [this page that references some older tickets](https://www.figma.com/file/TxXD5bGUOhbHHWLb85GPjK/10-10CG?type=design&node-id=0-11408&mode=design&t=sVopiO7bh9I8qall-0) that we have to migrate from as a starting point but as mentioned in the ticket description a mobile version never existed either.

**Comment by katelyncai** [comment]
Since this ticket was opened, the VA design team has migrated to Figma. [Confirmation screen](https://www.figma.com/file/TxXD5bGUOhbHHWLb85GPjK/10-10CG?type=design&node-id=89%3A100057&mode=design&t=mK8SXrpYLBE26M84-1) has been created and added to the Figma 10-10CG file.
**Please note:** some components in the Figma designs are v3 (where CG in production currently isn't). The design system will soon move to all v3 components and these components should automatically update in production.
