### ISSUE TITLE
[Spike] [DDL] Add supplemental claim and HLR decisions to DDL

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#61127]
## Value Statement

As a veteran who filed a board appeal, when I visit the CST, I want to be able to see when a decision letter is available for my appeal, so I can navigate to the decision letter page and download it.

## Background

VA stakeholders are asking for this.

## Technical Discovery

If we had the appropriate code from our doc spreadsheets, will letters come through accurately for these use cases? 

## Open Questions

- [x] How might we add a message noting the availability of decision letter on the listing card same as we do for claims? 
- [x] How might we add a message from the appeals detail view that links to DDL same as we do for claims?
- [x] Is there a feasible approach to this based on the data schema provided by CaseFlow? Why or why not?

**Comment by jerekshoe** [comment]
> Is there a feasible approach to this based on the data schema provided by CaseFlow? Why or why not?

We probably need to get a better understanding of when a decision letter gets generated for a decision review. There isn't a field returned by Caseflow that clearly indicates if a decision letter has been sent or not like there is for claims. For HLR / SC we might potentially be able to utilize the status. There are 2 statuses for HLR/SC that stand out (`hlr_closed`, `hlr_decision` and `sc_closed`, `sc_decision` respectively). It would be helpful if we understood what those actually indicated. There is only a `bva_decision` status for appeals so that doesn't gain us much in that respect. The other question we probably want to ask is if Appeals/HLR/SC always have decision letters. Part of the reason we need a flag for claims is that there are certain claim types that don't have associated decision letters. If decision reviews always have decision letters, then it may be safe to just assume that there is a claim letter when the decision review is closed

**Comment by jerekshoe** [comment]
> How might we add a message noting the availability of decision letter on the listing card same as we do for claims?

I think it's safe to assume that we can use a similar indicator to the one that we use currently for claims. It probably makes sense to wait until we redesign the cards for claims before we evaluate this however.
