### ISSUE TITLE
Identity Dashboard (FE) - Teams management integration

### ISSUE THREAD

**Issue by asg5704** [department-of-veterans-affairs/va.gov-team#61180]
## Description
This will track the scope of work that is required to fully integrate the Teams management (Teams page) with the Backend. Note* this can and probably should be further refined into smaller tickets

## Scenarios
- [ ] On the *Register a new team* page
  - [ ] When clicking the "Register team" button
    - [ ] A fetch request occrus to the BE API to "register a new team" endpoint
- [ ] On the "Edit your team" page
  - [ ] When clicking the "Add" button
    - [ ] A fetch request occurs to the BE API to "modify" users belonging to a team
- [ ] When on the "Teams" page
  - [ ] Create a Fetch request to the BE API to see if the teams exist and conditionally render the "Table of Teams" or the "Empty State Teams" page
    - [ ] When on the "Table of Teams" view
      - [ ] Clicking the "Modify" button takes me to the "Edit my team" page
    - [ ] When on the "Empty State Teams" view
      - [ ] Current functionality exists

**Comment by ianmagenta** [comment]
Moving this to blocked for now because the backend routes described above aren't fully functional yet. Once they are, this ticket can be unblocked.

**Comment by ianmagenta** [comment]
@jimcconnelly - Opting to close this because it's a bit outdated. I've broken out all of the tasks listed here into these newer, smaller tickets:
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/69910
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/69911
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/69913
