### ISSUE TITLE
Onboard ByLight Team

### ISSUE THREAD

**Issue by andreahewitt-odd** [department-of-veterans-affairs/va.gov-team#613]
## Onboarding User Story
ByLight team is onboarding to work on the VSP, they need support to get up and running. This epic contains the tasks our team will perform to support them through their onboarding stage.

## Goal
Get ByLight team up and running in their workflow as quickly as possible._ 

## Issues to create within this Epic

```
Send welcome email
Create a place to store all relavent documents for the team we are supporting
Have intake forms filled out
Set up team members as multichannel slack users
Give access to GitHub repo va.gov-team
Setup ZenHub for team
Complete on boarding meeting and present engineering and UX slide decks
Meeting to make sure the team is setup and ready for development
Schedule times to meet with team
```

## Definition of Done
- [ ] **Labeled with `Product Support` Team**
- [ ] **Onboarding is complete and new VFS team is operating in their development workflow**

**Comment by accbjt** [comment]
Just some take aways from the full team on-boarding meeting:
- Most of the team is on Windows and is using the GPC computers. We need to figure out how to solve this issue because most of us use our Mac either personal or company provided but not the GPC.
- We already did intros here so we should change our intros questions in the brake out session to get to know them more.
- We need to get with the DSVA member on their team and make sure they know what they are working on. We need to coordinate with them before doing the Discovery and Logistics meeting.

**Comment by accbjt** [comment]
Note for the Engineer on-boarding meeting:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/research/Onboarding%20MVP%20-%20Jul%202019/notes/Development_team.md

survey:

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/Platform/Onboarding/research/Onboarding%20MVP%20-%20Jul%202019/survey-results/Dev-onboarding-survey-results.md

**Comment by accbjt** [comment]
Documentation needs to be in one place for on-boarding. People are getting lost and not knowing when they are completed with on-boarding and setting up their systems.
