### ISSUE TITLE
Upgrade MVI version

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#614]
upgrade the [MVI version code](https://github.com/department-of-veterans-affairs/vets-api/blob/ce59a2df1ad2e3ec6cbecad42ac3709e12d79ac7/lib/mvi/messages/message_builder.rb#L44) from 3.0 to 4.1 and update specs to reflect the new version.

The version upgrade aspect was overlooked in 
https://github.com/department-of-veterans-affairs/vets.gov-team/issues/15536

Leverage the new MVI version to help us better identify users with different userids.

**Comment by rianfowler** [comment]
# Problem 
- unresolved issue where inconsistent information is shown between va.gov and ebenefits web sites 

# Artifact 
- Deployment of upgrade to production
- Adjustment of tests 

# Notes
- It's not certain this is the root cause of the above issue. 
- This will not resolve the issue. This [item](https://github.com/department-of-veterans-affairs/va.gov-team/issues/462) will need to be completed after upgrading MVI version.

**Comment by brandonrapp** [comment]
Johnny is currently blocked as the MVI endpoint that was used previously times out when he tries to connect. He has been trying to get assistance from the team that is outlined in this document - https://github.com/department-of-veterans-affairs/devops/blob/master/docs/External%20Service%20Integrations/Master%20Veterans%20Index.md but so far he has not had anyone reply with an answer to his question.
