### ISSUE TITLE
Investigate obtaining code access to the IAM Identity Management Toolkit

### ISSUE THREAD

**Issue by jrjamespdx** [department-of-veterans-affairs/va.gov-team#61460]
**Description:**
In order to determine the feasibility of leveraging the Identity Management Toolkit for the LGA Team's In-Person Proofing initiatives we need to not only gain access to see the relevant code repository(ies) but we need to speak with the relevant IAM team members to find out if we can make or propose changes in the future to the toolkit.

**Additional Notes:**
Per Damien DeAntonio, the best points of contact within IAM regarding the Identity Management Toolkit are Danny Reed and Patrick Kiboti.

**Acceptance Criteria:**
- We reach out to Danny Reed and Patrick Kiboti to setup a meeting and discuss first steps
- We get access to the toolkit code repository(ies) or get a clear no from IAM on getting access.
- If we're allowed access to the code, we then need learn and document the IAM required change management process to suggest/make changes to the toolkit in the future.

**Comment by jrjamespdx** [comment]
I emailed Danny and Patrick on 29 June 2023 but have not heard back as of 2:46 PM Pacific Time today ( 05 JUL 2023)

**Comment by jrjamespdx** [comment]
Update:  Still waiting on a response from Danny Reed and Patrick Kiboti.  I sent another email this morning at 09:22 AM PT.

**Comment by djmunoz1** [comment]
Response from Danny Reed:
They do not give access to the code for the toolkit to folks who are users/consumers of the toolkit.

We will have to make service requests (https://dvagov.sharepoint.com/sites/OITEPMOIAM/playbooks/Pages/IAM%20Playbook%20Home.aspx) to request changes.

Since we understand the route to get changes implemented will close this ticket and ensure it's considering during POC ideation.
