### ISSUE TITLE
Design Intent  - IA Feedback - Benefits Management Tools, Claim Status Tool, Improve Evidence Request/Submission Experience

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#61562]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions
**General**
- I love the tag label indicating the status of the claim - this is incredibly scannable.
- There are a ton of nice improvements here based on reading through your user research. This is very thoughtful and looks to reflect so much of the user research feedback you got in really creative ways!
- I'd love to see your team prioritize mobile testing the next time you all get a chance to conduct user research!

**Hanging links / Tabs**
* It was helpful to learn in the meeting that for the details page, the "tabs" are navigational hanging links. For the purposes of this feedback ticket, I'm going to use "tabs" in my language, but if these have unique URLs they are not true tabs. This design is also used for the Appointments tool on VA.gov. I'd recommend connecting with Peter Russo from that team so that design styles align there. 
* Longer-term, there are downstream IA challenges introduced by a details/child page requiring so much navigation, but as @joshkimux said, it's absolutely a wicked problem to solve for. Please work closely with Sitewide CAIA as you iterate, so that we can align approach on Appointments, Secure Messaging, and other relevant tools that may handle this problem in a different way. Tagging @jennymayoco who shared that their team recently met with y'all about the hubless spoke issue. 

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

**Must:** "What you need to do" vs. "What we’re doing" section - where it says “Step 3" can you update to “3 of 5” so that users can contextualize the "3" against the total # of steps in the process? That isn't visible from Status tab.
**Must:** The “How to file a claim” link is a potential task interruption and should probably open in a new tab. Whenever we do this, we need to indicate to users that this will happen via both visual and auditory means. Please use the external link icon with appropriate aria labels to ensure that experience carries through for sighted and non-sighted users. See the [privacy agreement component](https://design.va.gov/components/form/privacy-agreement) in the DS as an example. 
**Must:** Please review these inconsistent word choice clusters. Whenever possible, use consistent language to describe the same concept:
   * "What’s happening with your claim” (Details page) is different language for “Claim status” which was on the list view page
   * Upload / Submit / Add
   * Files / Document / Evidence / Statement (the file input component uses "file" so consider prioritizing that term)
   * Status label/tag text vs. "Status: Closed" or "Status: Decided" 
   * Document Request page: Calling this a “document” request but also use file, evidence, and statement throughout the product. 

**Should:** Icons in use should have consistent meaning across all tools using them on Va.gov
**Should:** On the "documents request" page the breadcrumb reads "Document request" but then has a much more unique H1 ("Request for Buddy Statement"). Will the same URL/breadcrumb be used for all types of requests? Or will you need a unique URL for each type of potential request? Please consider the maintenance of multiple URLs/content pages to support this approach.
**Should:** The “Overview” tab is perhaps unnecessary - this is valuable contextual information, but is not unique to any specific claim. Is there a way to surface it in a different way so that a new URL isn't being created for it every time? 

**Consider**: Under the "Files" tab, consider adding the link to the "Documents request" (in addition to the Status tab). It's a little confusing that the request displays under "status" but then isn't visible from "files."
  * While I think a second way to get to required / needed document requests will be helpful and build consistency, I have some concerns about breadcrumb navigation from that "requested evidence" URL. If you can get to the same URL from two unique pages (status and files), which one is the parent page? The <back breadcrumb should probably navigate horizontally to account for the potential confusion (send users to where they came from last rather than up the tree), but be careful of mixing breadcrumb behavior types within the same tool (avoid horizontal navigation **and** vertical navigation within the same product or task flow). Talk to @jennymayoco and @kristinoletmuskat with Sitewide CAIA about this.

**Comment by skylerschain** [comment]
@sterkenburgsara Here are updates on some of these items. The remaining two, which relate to content and IA, will be resolved shortly! Meeting with IA and content teams next week to discuss and resolve.

**Must:** 
> What you need to do" vs. "What we’re doing" section - where it says “Step 3" can you update to “3 of 5” so that users can contextualize the "3" against the total # of steps in the process?"

Updated design: I added that language (e.g. "Step 3 of 5") to both the card within the Status tab, and on the CST home page itself. 

<img width="651" alt="Screenshot 2023-07-19 at 4 03 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/ace41a14-33e3-4af6-abd0-61291d93026c">
<img width="762" alt="Screenshot 2023-07-19 at 4 03 17 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/9598cf5f-9127-4428-b21a-d499677b07ce">

**Must:** 
> The “How to file a claim” link is a potential task interruption and should probably open in a new tab. Whenever we do this, we need to indicate to users that this will happen via both visual and auditory means. Please use the external link icon with appropriate aria labels to ensure that experience carries through for sighted and non-sighted users."

Done! See below.

<img width="714" alt="Screenshot 2023-07-19 at 4 04 34 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/f6b6d70e-d806-45ef-9141-307a82d9a6c0">

**Should:** 
> Icons in use should have consistent meaning across all tools using them on Va.gov

We discussed these icons at a recent Design Office Hours with @allison0034 and @humancompanion-usds. We resolved to remove the icons for now since we felt they're not necessary and we don't want to introduce inconsistency in their usage. 

<img width="717" alt="Screenshot 2023-07-19 at 4 07 03 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/beec8e7f-3381-44af-8a30-2d279b74c78c">

**Consider:** 
> Under the "Files" tab, consider adding the link to the "Documents request" (in addition to the Status tab). It's a little confusing that the request displays under "status" but then isn't visible from "files."

This is great callout. In the new version, the request alert would also appear in the Files tab. 

<img width="532" alt="Screenshot 2023-07-19 at 4 18 33 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/95102058/eff1d601-1811-49ca-ac1b-9c940e51aa5f">
