### ISSUE TITLE
pull email list for Reactivation Test C

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#61826]
As an email admin I want an email list so that I can run a test of messaging for the Organic Campaign

ACCEPTANCE:
- Test Name: [Reactivation Test C](https://docs.google.com/spreadsheets/d/1Q2W_2PKVwCKaMNEG-RsThlb7nUErJ18rIXg1Mr1W0ZU/edit#gid=218391671)
- volume: 50,000 emails
- random
- excludes the 2500 emails from Reactivation Test A 
- check if original email list from Test A stored in ctirix meets need

DEF OF DONE:
- Reactivation Test C email list shared with Product lead (Dawn) as csv file 
- email list centrally stored along with the email lists from Reactivation Tests A and B

**Comment by jrjamespdx** [comment]
List sent to Dawn's VA email address around 4:15 PM PT/7:15 PM ET.   

List meets the following criteria:
- Contains 50,000 user emails
- Is random (no sequential ids, date ranges, etc.)
- Users on the list have a modern credential (Login.gov or ID.me) AND a DSLogon legacy credential.
- Does NOT contain any of the 2,500 user emails from the first VEO send on/around July 10th
- Does NOT contain any users with associated MHV credentials

**Comment by jrjamespdx** [comment]
Updated:  The previous list was discarded as the request had changed to want two (2) different lists:
- 50,000 emails with only a DSL+Login credential
- 50,000 emails with only a DSL+id.me credential

Unfortunately, due to remaining available emails on the list all having Login.gov credentials, there was no way to provide a list of emails with only a DSL+id.me credential.

Dawn then requested we just pull a list of the roughly ~70k remaining emails that were confirmed to only have a DSL+Login credential (no mhv and no id.me).
