### ISSUE TITLE
[CAIA Intake]: Authenticated Experience, Profile Hub, IA Consult

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#62647]
### What does your team need support for?

- [ ] Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
- [ ] Making revisions to one or more existing VA.gov pages
- [X] Something else

### Describe what your team needs support with

We're working on discovery for a hub page for the VA.gov profile (Kristin and Jenny are familiar with this work), and want to have a meeting w/ the IA folks to get their thoughts on how we might approach organizing the page.  [Here's a product outline ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/hub) that describes our goals with this page.

**Background info**

Profile currently has the following sections:
- Personal information (legal name, dob, preferred gender, preferred name, disability rating)
- Contact information (addresses, phones + email)
- Military information (dates of service, branches)
- Direct deposit (comp + pen, and education)
- Notification settings (currently text only)
- Account security (reflects sign-in email information + status of accepting MHV terms and conditions for some users)
- Connected apps (3rd party apps a person has given access to their data)

We're working on adding Next of Kin and Emergency Contact to the profile - TBD as to whether this becomes it's own section or incorporated into an existing page.  

We also see the hub as an opportunity to link out to the dependents and letters tools (not bring these tools into the profile).

**Talking points**
- Since we're not yet sure how dependents and NOK will fit into the profile, is it better to focus only on what we know for sure will be there? No idea what the timeline would be for adding those things, or how it compares to launching a hub
- One thing I thought of is creating categories for the 7 main profile items. Would love to discuss pros and cons of categorization chunks vs just a straight list. I see various approaches to this out in the wild.
- Another idea is that we could have a "quick links" section where we link to specific popular tasks people want to do from  profile, like update specific pieces of contact information. If we did that, that's where a link to the dependents and letters tool would make sense.  Thoughts?
- Any other IA tips or guidance you can share as we think through this is very welcome

### Will this new product be released incrementally?

- [ ] Yes, we'll be launching incrementally
- [ ] No, we won't

### When do you expect to launch your product to 100% of users?

We're not yet sure we'll move forward with this, still in the discovery phase

### Supporting artifacts (if any)

[Here's a Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690215208596/85132c5e4a025524f742559c6ff773e7f19c4a87?sender=ub868d471cfdb1c56cc0b4512) with:
- examples of profile hubs on other sites
- examples of hub-like pages on VA.gov
- ways we've thought about grouping the existing profile items so far.

### Will this be going through the collaboration cycle?

- [X] Yes, it will be going through the collaboration cycle
- [ ] No, it will not

### When does this work need to be done?

Ideally, we'd like to meet with IA before the close of our current sprint, which is August 2, 2023.

### Do you plan to bring this to an upcoming content office hours session?

- [ ] Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
- [ ] Yes, health content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
- [ ] Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
- [X] No, but I'd like to schedule time to talk about this request
- [ ] No, let's work asynchronously and meet if needed

### Who's on your team?

Team name: Authenticated Experience
OCTO-DE product owner: Samara Strauss
Product manager: Travis Cahill
Designer: Liz Lantz
FE engineer: Adam Whitlock
Product/team Slack channel: #accountexp-authexp
...

### Do you have an accessibility champion on your team?

Yes, we have a champion

### If you have an accessibility champion, what's their name?

Liz Lantz

**Comment by kristinoletmuskat** [comment]
Following up on this with some of the decisions we discussed:

1. Since we're not yet sure how dependents and NOK will fit into the profile, is it better to focus only on what we know for sure will be there? No idea what the timeline would be for adding those things, or how it compares to launching a hub **We decided to focus on the 7 items we know for now, and even in the future we could add these new things (Next of Kin, Dependents, etc) straight into the list, either categorized or not depending on #2 below**
2. One thing I thought of is creating categories for the 7 main profile items. Would love to discuss pros and cons of categorization chunks vs just a straight list. I see various approaches to this out in the wild. **We don't think we need categories for the 7 main profile items, so can move forward with an MVP that has no categories. But we could explore the categorization in a user test on a future iteration of this list if we see in analytics or user feedback that ppl are struggling to find things**
3. Another idea is that we could have a "quick links" section where we link to specific popular tasks people want to do from profile, like update specific pieces of contact information. If we did that, that's where a link to the dependents and letters tool would make sense. Thoughts? **We think this is a great idea to explore in the future, or with user testing, but decided we don't need to do this for MVP.**

**Comment by andaleliz** [comment]
These are the two designs we reviewed, to facilitate a convo about categorization vs a plain list:
<img width="572" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/55992116/ece882e6-a39e-4df0-8e7f-799d173dde2b">

Ultimately, I think there'll be a different visual structure to the page but we will bring options to design intent!
