### ISSUE TITLE
Welcome page has broken links and outdated content

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#62688]
### Description
As part of Platform Orientation, we ask new VFS team members to review the Platform Website welcome page. However, this page currently has links that direct to outdated github docs and contains outdated information. In the intro paragraph, we reference Drupal which is maintained by the CMS team - they are not currently part of Platform.

I think it might be in our best interest to ask what the intent of this page is. We are currently trying to share a lot of varying information and it's clear that it is not well maintained. 

In the [General Orientation deck](https://docs.google.com/presentation/d/1xZMmHtsa65fJ1nMMfFC2PWFBDhBmBWmx1EqQQlPdsVc/edit#slide=id.g13de14d9293_0_31), slide 16, we communicate the mission of Platform. It might be wise to include this on the Welcome page.

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/getting-started/welcome

### Which type of team are you on? (Platform team, VFS team, or Leadership)
Platform Governance team

**Comment by vbellissimo** [comment]
Hi @shiragoodman , thank you for flagging this. We were just talking about deprecated github files that are still being linked from. We'll take a look and put on our backlog for next steps.

**Comment by shiragoodman** [comment]
thanks @vbellissimo . Please let me know where you land. We're going to be taking a look at all of the PW pages that are recommended for review in the Platform Orientation templates. We want to make sure we're directing VFS team members to up to date guidance. If anything else comes up, we will let you know! thanks.

**Comment by vbellissimo** [comment]
@shiragoodman , our team reviewed this page and have updated it as much as possible. This is what our team has done as part of [this work](https://app.zenhub.com/workspaces/platform-content-team-62bde00be46b400017674aef/issues/gh/department-of-veterans-affairs/va.gov-team/62693):

> - Reworked the intro to include content from Platform Orientation slide deck, slide 16.
> - Moved VA.gov definition to the intro section to improve flow.
> - Reached out to governance team to get updated link information for Design section.
> - Updated link in the "Working in the open" section per Vicky's recommendation.
> - Updated links in the Design section per Naomi's recommendations.

Take a look at the updated version of the [page here](https://depo-platform-documentation.scrollhelp.site/getting-started/welcome). If you have any other concerns, let us know.

As a side note... we've recently worked to create a content review process that will allow our team to audit for these kinds of broken experiences due to outdated content, etc in the future. However, this won't be done all at once and we're roadmapping how to tackle this kind of maintenance work in phases. Priority right now is the engineering sections but other parts of the site will also be planned.

Thanks again for flagging this.
