### ISSUE TITLE
Implementation of Configuration in Coordination with DevOps COP

### ISSUE THREAD

**Issue by gia-lexa** [department-of-veterans-affairs/va.gov-team#62736]

**Comment by jilladams** [comment]
@gia-lexa question: does your 7/28 note above, " final configuration that members of vsp can access. Depending on the success of the closed test, this may just entail giving certain VSP teams access to the existing slack room," mean VFS teams will not be able to use Alerts that push to slack? 

This is relevant for my teams due to the increased attention on Forms related to PACT Act deadline issues in early August. My VFS teams (Sitewide Facilities and Sitewide Public Websites) have error reporting in Sentry around [Find a Form click download failures](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?id=19&project=4&statsPeriod=24h) that we'd like to get alerted about at certain threshholds. We've already configured an Alert ([Forms errors warning / critical notifications](http://sentry.vfs.va.gov/organizations/vsp/alerts/metric-rules/platform-web/7/)) that doesn't notify us.   We're currently not able to get Datadog to perform the same function, though we're investigating it. If we're also not going to be able to use the eventual Sentry > Slack solution here, I'll need to let my PO know that.

**Comment by jennb33** [comment]
@gia-lexa has there been any other work done for this ticket? Please advise, thank you!
cc: @LindseySaari

**Comment by jennb33** [comment]
This ticket can be closed, as there is no other work being performed on this Epic. We still need to establish a roll-off plan, but that still needs to be verified by someone at VA. 
For all intents and purposes, this ticket can be closed. Maybe we will reopen it again. Who knows. Zombie.
