### ISSUE TITLE
Iterate design of form search results display, so it's mobile friendly

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#6273]
## Iterate design of form search results display, so it's mobile friendly

**This design ticket is related to Find VA Forms - Search#1632.** 

**Product repo:** 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign 

**Current columns**:
Form number
Form name
Revision date
Related to
Available online

### @rtwell will recommend improved UX to ensure results display is mobile friendly. 

**Possible changes he will consider are:** 
- combining form number and name columns (FE display)
- linking the combined column to the detail landing page
- combining the form PDF link and online tool link in a new action/what you can do column

FYSA @AkucherGCIO @ncksllvn @kelsonic @kevwalsh @mnorthuis

**Comment by jenniferlee-dsva** [comment]
@rtwell - latest API based mvp search functionality can be viewed here: https://staging.va.gov/find-va-forms-beta/

Latest body static copy of page is in Drupal: http://preview-prod.vfs.va.gov/preview?nodeId=2354

**Comment by AkucherGCIO** [comment]
@AkucherGCIO - FE tickets need to be coming out from this ticket.  Needs grooming.

**Comment by AkucherGCIO** [comment]
@rtwell - Please let us know the estimate for the re-design work being done in this sprint.

**Comment by rtwell** [comment]
@AkucherGCIO no estimate needed! The work is already done. Files are in the [design folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-va-forms-redesign/design)

Please note (esp @ncksllvn ):
1) Form number and name condensed onto 1 line (I refer to this as "**Form title**")
2) **Form title** links to the form detail page
3) Download VA form XYX (PDF) actually downloads the form on-click
4) the **Form title** can utilize the same style / interaction as the Hub page links
5) if there is an online application for a search result, use [a button](https://design.va.gov/components/buttons#secondary-button) to send users to the tool

per usual, hit me up if you have any questions

**Comment by jenstrickland** [comment]
@AkucherGCIO @rtwell I'm not sure where these are in the process, or what size the work is. It would be great if it could have a VSP design review before building begins to ensure alignment.

Questions:
- For the PDF download links, was including the size of the PDF file considered? It is considered best practice when offering links to documents. For those with limited data plans, there may be negative consequences if they view a number of large files on mobile.
- Is there a mobile design? I looked in the design folder, in both the PDF & Sketch, but didn't see one.

**Comment by rtwell** [comment]
@jenstrickland happy to have VSP design review
1) yes, PDF size was considered, but we have decided against it. because this would have to be a global change across VA.gov, there are a couple reasons for this decision:
a) lack of scale and consistency—because all PDFs are not hosted on VA.gov, we cannot consistently (or quickly, in most cases) provide the size for all instances. 
b) Some instances of the Download PDF link appear in paragraphs, and the addition of that info adds noise and makes it difficult for sighted users to read. 
2) i don't see a need for a mobile version. is there a question about how this would appear on mobile? It feels pretty straight forward to me, but i'm happy to mock it up if needed.

**Comment by jenstrickland** [comment]
Looping in @sshein — as practice lead on VSA.

**Comment by jenniferlee-dsva** [comment]
Added 2 notes for Nick - to ryan's list above: https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273#issuecomment-594174574

**Comment by AkucherGCIO** [comment]
03/04/20 PW Grooming
@AkucherGCIO - Check with VSP Collab cycle process if we can move this to Staging and have the review there.
Aruna to create an implementation ticket for this effort in Sprint 17.

**Comment by sshein** [comment]
Hi there - I think it would be good for VSP design to look at this at some point before launch if only for awareness - looks like there are a few things that might be happening to start setting "standards" around list-style search results that I think would be good for all of us to know / think about. e.g. the little right arrow icons to the right of the main links. Whether that's part of some kind of "staging review" or just their office hours, I'll let them decide when Aruna chats with them :)

**Comment by sshein** [comment]
also I appreciate this kind of straight-forwardness @rtwell haha ;) "@jenstrickland please let me know if there are any accessibility concerns and i'm happy to argue about it 😄"

**Comment by sshein** [comment]
also fwiw happy this redesign happened so fast! I was thinking switching from the table view to something else would be good but didn't expect it to be iterated on so quickly

**Comment by jenstrickland** [comment]
@rtwell Would you please provide a mobile mockup? 

- I'm concerned about the scannability of the content, as a table it seemed easier to scan.

- I'd like to validate how the search input field and submit button would work on the small viewport.

- I'd like to understand what's linked. In the Hub pages the Blue bold text > and the regular text — all of it is a link. I'd like to understand if that's the intent here.  

- Fwiw, the size of linked files may be obtained programmatically (https://stackoverflow.com/questions/55226378/how-can-i-get-the-file-size-from-a-link-without-downloading-it-in-python). The impact of not knowing the file size could be serious for our users on limited data plans.

**Comment by rtwell** [comment]
ask and ye shall receive!
![image](https://user-images.githubusercontent.com/12564977/76017799-30f76080-5eed-11ea-9ad5-5310196ea643.png)

1) your concern is noted
2) lemme know if the mobile layout raises in concerns
3) I'd love to pick up that component out-of-the-box from the hub page, but if that's an accessibility issue, let me know
4) ✅

**Comment by jenstrickland** [comment]
@rtwell Thank you!
For #3 - I want to ensure that the text that does not look like a link is not a link. In this design, only the blue bold text and the underlined blue text should be linked. On the hub page I reviewed over the past few days, the text that currently is part of the link but doesn't look like a link is an accessibility issue at present. It is confusing for sighted screenreader users, speech control users, and switch users, leading to errors.

Before the team starts coding this, it may be helpful to meet with me. This content should be marked up as either:
- a table, possibly using the responsive table technique noted above in https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273#issuecomment-594832668, unless the VA design system has a responsive table solution that works
- an ordered list `<ol>` if the results are shown in a weighted order
- an unordered list `<ul>` if the order of the results is not based on any order/weight
- the `>` right angle bracket should also have a these attributes: `role="presentation" role="aria-hidden"` so that screenreaders do not speak the bracket aloud

**Comment by rtwell** [comment]
@jenstrickland for bullet 3: this is excellent — let's not perpetuate the current implementation and make sure only the blue text and the > be linked.

**Comment by AkucherGCIO** [comment]
@rtwell @jenniferlee-dsva - Seems like there was design iteration done in this ticket.  Are we complete with this effort for this Sprint ?

**Comment by AkucherGCIO** [comment]
03/11/20 Sprint 17 Planning
There is a design intent meeting with the VSP team on 3/12/20 and based on that meeting, we will know if the design is good or need to iterate some more.

**Comment by MickinSahni** [comment]
Set estimate to 0 as designs for the mobile version are available

https://github.com/department-of-veterans-affairs/va.gov-team/issues/6273#issuecomment-594174574

**Comment by MickinSahni** [comment]
2020-03-18 PW Standup
* Pulling out of sprint so we can groom

**Comment by rtwell** [comment]
@jenniferlee-dsva @jenstrickland @MickinSahni sooooo i decided to iterate on the VA form search landing page to improve the scannability. Attached are the new designs, both large and small screen.

@jenstrickland please review this design and let me know if you have any questions. 

## large screen
![image](https://user-images.githubusercontent.com/12564977/77202803-668f7280-6ac5-11ea-84d2-92d0b066c9a3.png)

## small screen
![image](https://user-images.githubusercontent.com/12564977/77202840-77d87f00-6ac5-11ea-8a50-e8ea93d32969.png)

**Comment by MickinSahni** [comment]
Closing this out. Implementation happening here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7097
