### ISSUE TITLE
Evaluate onsite notifications for New Imaging Results Available

### ISSUE THREAD

**Issue by A6-toma** [department-of-veterans-affairs/va.gov-team#62801]
Evaluate onsite notifications for New Imaging Results Available. 

Marci McGuire is Medical Records SME.

TASKS
- [ ] UX evaluation
- [ ]  Technical evaluation

### Acceptance Criteria
UX complexity and technical complexity of implementing New Imaging Results Available onsite notification have been documented.

[UX notes are here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/medical-records.md)

**Comment by fmccaf1** [comment]
@jonathanjnelson hey, I'm hoping you can take on this ticket and finish it up for this week while I'm gone (thank you!). I got stalled because I haven't heard back on [this Slack thread](https://dsva.slack.com/archives/C03Q2UQL1AS/p1693579011765229). If you hear back, I'd love if you could post the screenshots in[ that github doc we've been working on together](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/medical-records.md). Thank you!

**Comment by jonathanjnelson** [comment]
Hi @fmccaf1, I updated [the document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/notifications/medical-records.md) with Lexi's reply.
