### ISSUE TITLE
Design Intent - Design Feedback - VA Integration - Ask VA

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#62816]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- The [Sitewide Facilities, Facility Locator, Improve Search, Add Filters](https://app.zenhub.com/workspaces/collaboration-cycle-reviews-61d89e9e5f4c120011a0ad37/issues/gh/department-of-veterans-affairs/va.gov-team/61610) is currently reworking filters. It may be useful to talk to them and align some of the content for the questions about facilities.
- Matt: Consider radio buttons and check boxes instead of a select. If it is more than 10 use a select, less than 10 try to avoid it.
- Matt: It seems you already answer things about the Veteran in the beginning. Be clear if you are the Veteran or one of these other things.
- Matt: We are actively replacing our step indicator with the [US indicator](https://design.va.gov/storybook/?path=/docs/uswds-va-segmented-progress-bar--default). Consider [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns) if you want to design something different that would be appropriate.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Look at the [sign in](https://design.va.gov/templates/signed-out-vs-signed-in) template for UI and content.
- **Must**: We have noticed alert fatigue on VA. Review the different [alert styles](https://design.va.gov/components/alert) (including slim alerts) and make sure you meet the guidelines
- **Must**: Use [memorable date](https://design.va.gov/components/form/memorable-date) for DOB/DOD
- **Must**: Matt - [Back to top](https://design.va.gov/components/back-to-top) is no longer a button, it is a link

**Comment by tygindraux** [comment]
Hi Matt! Thanks for your feedback! We're making a number of updates based on your feedback (which we'll update you on once they're finished.)

There's one comment we wanted to clarify with you:

> "It seems you already answer things about the Veteran in the beginning. Be clear if you are the Veteran or one of these other things."

Can you help us understand this comment? We wondered if maybe you're referring to these questions at the start of the flow, but aren't sure:
- Are you a current VA employee
- Are you the Veteran?

Thanks!

**Comment by tygindraux** [comment]
Hi again, @humancompanion-usds! Here are the updates we're making based on your feedback.

We've:
- reached out to Sitewide Facilities about their current work on the facility locator to help update our facility search
- replaced select menus with radio buttons when there's 10 items or less
- updated progress bar to [USDWS step indicator](https://design.va.gov/storybook/?path=/docs/uswds-va-segmented-progress-bar--default) with chapters instead of steps
- reviewed the [sign in template](https://design.va.gov/templates/signed-out-vs-signed-in) and will show an auth and unauth journey at midpoint review
- reviewed the [different alert styles (including slim alerts)](https://design.va.gov/components/alert)
- confirmed we are using [memorable date format](https://design.va.gov/components/form/memorable-date)
- updated [back to top](https://design.va.gov/components/back-to-top) to a link, not a button

We're going to close out this ticket, but if you have additional clarity on the comment we left above, please let us know and we can reopen. Thanks!
