### ISSUE TITLE
Iterate on user flow

### ISSUE THREAD

**Issue by skirkman16** [department-of-veterans-affairs/va.gov-team#62834]
prep ahead of 8/15 stakeholder mtg

**Comment by porta-antiporta** [comment]
# Use Case:

As a team member on either Login.gov or LGA, I want to understand the user flow of a Veteran and Proofing Agent during IPP so that I can keep this big picture in mind as I help develop this capability across our systems.

# Background:

Login.gov currently has a USPS capability which allows a USPS clerk to validate authenticity of the ID. Our process is intended to provide the full gamut of IAL2 verification in person. After a workshop with VA, Login.gov and NIST, there was alignment on a path forward for a pilot.

In preparation of an Aug 15 meeting with Login.gov, we want to update the user flow to reflect the discussion so that we can get in earnest breaking down that flow into deliverable value increments.
# Acceptance Criteria:
- [ ] Update wireframe flow from workshop to reflect discussion (ex: moving where PII is captured from intake to IPP process with proofing agent, guidance on how to check IDs)
- [ ] Highlight areas where handoffs between VA systems and Login.gov will occur
    - [ ] From VA.gov to Login.gov (current flow)
    - [ ] From VA.gov to our IPP application
    - [ ] From IPP application back to Login.gov for establishing verified account

**Comment by skirkman16** [comment]
need to meet to discuss the details of the flow

**Comment by skirkman16** [comment]
Met with Porta yesterday to confirm new user flow. In process of updating wireframes for custom app and emails
