### ISSUE TITLE
[Design] EZR Form Wireframe

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#63037]
As a Veteran, I would like to be able to update my information online so that I don't have to fill out paper forms or call a hotline to do something I can do in five clicks online.

- [x] Look at how the digital EZ form is structured (including short form), and if needed, compare it to the paper form
- [x] Determine what of the existing EZ functionality and design can be used for the [EZR](https://www.va.gov/vaforms/medical/pdf/va%20form%2010-10ezr.pdf)
- [x] Come up with wireframes for how we can present EZR information in form...form
- [x] Treat this as a stand-alone form, e.g. if the user has directly navigated to VA.Gov/forms/1010EZR
- [x] Wireframe should be for authenticated flow(s) only
- [x] Some fields will be uneditable (Legal name, SSN) and will have to "Confirm"
- [x] I believe we can skip Gender Identity as that is being worked on elsewhere but is currently blocked (double check with @hdjustice and @jessicastump )
- [ ] [Use Check-In's approach to "Confirm"](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec) as a reference point and talk to the Check-In team as needed 
- [ ] Use current verbiage wherever possible, utilize check-in team's work and our team's work for this (if we don't have all of the verbiage that's ok). Also, because this is a wireframe, we don't have to have a ton of verbiage
- [x] Collaborate with @longmd 
- [x] Share with team
- [x] Incorporate team feedback
- [ ] Share with Patrick and Kristen (if needed)

**Comment by hdjustice** [comment]
I agree to skip Self-Identifying Gender Identity for now.  It was a hot topic and is on hold from being added to the EZ application.  It is not a requirement to obtain or maintain health care, and so is not a necessity at this time.  If the topic comes back up, we can address EZ and EZR together.

**Comment by IMHieuVo** [comment]
**Things to note**:
1.  The EZR would still need to be processed prior to the Veterans seeing the updated information in the Profile.
2. The paper form is not clear on what adding more than 1 dependent looks like. 
3. If we ultimately go with the Form route (making the EZR like the EZ enrollment), there would be an extensive amount of work with Content to work out the additional information and verbiage.

**Things to consider**:
1. Past Research: How was the Authenticated approach done? What problems or decisions came up? Was there a workaround?
2. Next of Kin and Emergency Contacts are active projects being worked on by the MHV team for VA.gov profile. Both of these sections are on the EZ and EZR paper form but it was not included in the EZ online enrollment. There is no component or wireframe to work off of.
3. The Check-in team did not use the existing design system because it does not have an approved/confirmed function. From a technical feasibility standpoint, we do not have the timeline to go down this path.
4. Our most straight-forward approach that does not change the form library would be pre-filling whatever information we can pull then have Alert Boxes to inform the Veterans.

[Google doc](https://docs.google.com/spreadsheets/d/1IGLA8GT35ffS2PnFvCwdnA7bWTL5187TN9QlVwUXYr4/edit?usp=sharing) - comparing EZ vs EZR vs Profile
[Sketch file ](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/A8A73F5C-CD0D-4862-AE2E-71BCE8F00790/canvas)- Flows and Wireframes
