### ISSUE TITLE
Midpoint Review - Design Feedback - BAH-MBS-SelfServ, Pre-Need Self Service, Pre-Need modernization and CaMEO Integration

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#63115]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Change the green "Apply" button to a green action link. I realize the design system shows a green button but it has been updated to an action link for accessibility reasons.
  - <img width="370" alt="Screen Shot 2023-08-04 at 9 48 23 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/0d85a569-41bf-4609-b734-45fab3dada6e">
  - <img width="651" alt="Screen Shot 2023-08-04 at 9 26 52 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/65885e4e-2bf5-4773-a3e6-a5121c75e300">
- 
- **Must**: Add a "Save" button to the [multiple responses pattern](https://design.va.gov/patterns/ask-users-for/multiple-responses) for service history.
  - <img width="348" alt="Screen Shot 2023-08-04 at 8 45 30 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/e0d1f325-b7f1-4d31-b633-d34b28055ca8">
- 
- **Must**: On the upload file screen, the user can delete the file by clicking the delete button. There is not warning to confirm they actually want to delete. Consider adding a modal to confirm they want to delete the file. I am adding a modal screen shot, this modal uses the word "remove" however the preferred word is "delete".
  - <img width="621" alt="Screen Shot 2023-08-04 at 9 01 54 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/c57b9a75-6abb-48aa-af91-ad67c7c94a03">
- 
- **Consider**: Make sure any select boxes in the form are sorted by the most common item first, or in alphabetical order.
  - <img width="351" alt="Screen Shot 2023-08-04 at 8 37 50 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/f25c7252-5350-4855-85bf-7920a4c5099c">

**Comment by ccruzgra** [comment]
Hi @allison0034. Thank you for your feedback! After discussing with my team, our responses are below:
- "Must: Change the green "Apply" button to a green action link. I realize the design system shows a green button but it has been updated to an action link for accessibility reasons." we looked into this and were informed by Laura from CAIA that her team would be able to make this update in [issue 61517](https://github.com/department-of-veterans-affairs/va.gov-team/issues/61517).
- Adding a "Save" button to service history cards... our application has an "Update" button when editing a previously added card, but no "Save" button when adding a new card. Checking other forms like the Health app (10-10EZ) when adding insurance info, there doesn't seem to be a "Save" button when adding new cards. Is this just a problem with the OOB functionality then?
- Delete confirmation modal: This is already in place for our upload process, just not captured in the prototype. Note that no other card patterns besides for uploading have a delete confirmation modal (e.g. service periods in our form or card patterns not related to uploads in other forms) so that's why it's not a part of our service periods/deceased persons card functionality. 
- Sorting of select boxes: Yes, we have appropriate sorting in place for our select boxes in our existing form.

**Comment by allison0034** [comment]
Hi @ccruzgra for your question "Is this just a problem with the OOB functionality then?" I am not sure. Originally that pattern did not have a "save" button so those may be old instances of the pattern. The save button is for when a user is creating a new service date, not updating a date. The update button would be appropriate when updating. If there is no save button then how does the service date get saved when it is added? I assume when the user clicks continue but that is not vert clear to the user since there is a remove and add another option.

**Comment by ccruzgra** [comment]
@allison0034 yes, agreed. Since these cards don't appear to have a Save button, at least in the couple of forms that I've been able to check, would this need to be a feature request to fix globally?
