### ISSUE TITLE
Midpoint Review - Content Feedback - Identity Core Team, Terms of Use (Terms and Conditions)

### ISSUE THREAD

**Issue by CherylEvans** [department-of-veterans-affairs/va.gov-team#63153]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- This looks great! I really like your use of the accordion folders. I noted a few typos, but overall, nice job.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- Mobile and Desktop Extra word included in heading -> "Do you accept **to** VA's Terms of Use?" I recommend removing the word "to." Screenshot 4
- Mobile and Desktop Extra word included in content under What you can do: heading -> Incorrect use of the article "the." I recommend removing it. (Please disregard the second one that is circled. It is fine.) Screenshot 3
- Mobile and Desktop Extra word included in content under first bulleted list in "What happens if I don't accept? -> The word "do" is used incorrectly in the sentence and should be removed. Screenshot 2
- Mobile and Desktop -> Users of the service -> The subject "services" does not agree with the verb "includes." I recommend using "include" to agree with the plural subject "services." Screenshot 1
- Mobile and Desktop -> Users of the service -> The punctuation after the pronouns is incorrectly placed. I recommend changing punctuation to (comma and then quotation) E.g., (") Screenshot 1
![60961_Cheryl_1_subject:verb agreement and incorrectly place punctuation_Screenshot 2023-08-04 at 8.00.42 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/a9574e5b-4f55-48fa-a832-cc175cd4ba4a)![60961_Cheryl_2_Incorrect use of verbiage "do"Screenshot 2023-08-04 at 7.15.51 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/2b51c26b-77ba-44ec-b612-90d0476a3a55)![60961_Cheryl_3_Incorrect use of the word "the"Screenshot 2023-08-04 at 7.08.01 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/8cac4d8a-c99b-490f-b86b-b1bfd20bf06e)![60961_Cheryl_4_Incorrect use of verbiage_Screenshot 2023-08-04 at 6.56.37 AM.png](https://images.zenhubusercontent.com/61fa9c81372349426637bcfa/62d14648-11b6-4484-a39a-6926ade420e7)

**Comment by claytonzook** [comment]
@CherylEvans It's very helpful to see the screen shots! Appreciate the feedback, we're correcting these items ASAP before we move forward with research.

I'm re-listing listing items here with checkboxes so I can keep track as I go through and correct these:
- [ ] Mobile, Desktop, and screen reader flows -> Extra word included in heading -> "Do you accept to VA's Terms of Use?" I recommend removing the word "to." Screenshot 4
- [ ] Mobile, Desktop, and screen reader flows -> Extra word included in content under What you can do: heading -> Incorrect use of the article "the." I recommend removing it. (Please disregard the second one that is circled. It is fine.) Screenshot 3
- [x] Mobile, Desktop, and screen reader flows -> Extra word included in content under first bulleted list in "What happens if I don't accept? -> The word "do" is used incorrectly in the sentence and should be removed. Screenshot 2
- [x] Mobile, Desktop, and screen reader flows -> Users of the service -> The subject "services" does not agree with the verb "includes." I recommend using "include" to agree with the plural subject "services." Screenshot 1
- [x] Mobile, Desktop, and screen reader flows -> Users of the service -> The punctuation after the pronouns is incorrectly placed. I recommend changing punctuation to (comma and then quotation) E.g., (") Screenshot 1

**Comment by claytonzook** [comment]
@aparsley I think we're good on this ticket now, but want to hand it off to you to close. A couple additional notes here:

- On the first checkbox in my note above, I actually modified the mobile wording there to match the desktop. So we have "Do you accept these Terms of Use" in place over the suggestion here.
- In addition to the items Cheryl pointed out, I also saw a remaining artifact from a previous iteration in the desktop flow on the "decline" page that mentioned a check box. Since we did away with that check box, I updated that to be the same as the mobile wording.
- I also updated the phrase "digital tools" to "VA online services" on that page as we consulted on previously with CAIA content team based on our recent research on the phrasing for another product.

**Comment by aparsley** [comment]
Looks good here, I approve.

**Comment by CherylEvans** [comment]
@claytonzook Thanks again for your comments, Clayton! :-)
