### ISSUE TITLE
Best bet request for Pension Online Form Deactivation

### ISSUE THREAD

**Issue by kristinoletmuskat** [department-of-veterans-affairs/va.gov-team#63240]
-  Select Request Type:
    - [ ] NEW: You would like to create a new best bet
    - [X] CHANGE: You would like to change an existing best bet

### Description
Please provide a description and supporting information for the new best bet, or the existing best bet you want to change. Include any research or data you have to support the request. 
 - here's the background in our google doc: https://docs.google.com/document/d/191ygG1BkqM-QPoBCoXmkyxZOFSCdcuzkCrcuV3R4gu4/edit

###  Target Dates
Do you have any target dates we should be aware of?
 - I think we can do this whenever
 
| Keyword        | Action needed                                                                                                                                              |
|----------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 21p527ez       | Add this keyword to https://www.va.gov/find-forms/about-form-21p-527ez/ instead, and remove from https://www.va.gov/pension/application/527EZ/introduction |
| Form 21p 527ez | Add this keyword to https://www.va.gov/find-forms/about-form-21p-527ez/ instead, and remove from https://www.va.gov/pension/application/527EZ/introduction |

**Comment by jennymayoco** [comment]
@kristinoletmuskat -
- For the existing best bet page for [the online form](https://www.va.gov/pension/application/527EZ/introduction), I have added an end date of 8/7/2023 so this best bet should now be archived. This is because there is already an existing best bet for [find a form page for 21p-527ez](https://www.va.gov/find-forms/about-form-21p-527ez/) and wasn't able to update the online form best bet with that link.
- I also added the keywords that were under the online form best bet to find a form best best

Let me know if there are any questions!
