### ISSUE TITLE
FE | Editing as a Subtask | Saving when no changes are present

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63333]
## Background
Enter the subtask workflow with a value already saved to the profile 
If no change is made, the first save doesn't redirect back to notification settings page 
When no changes are detected, we need to redirect to the notification settings screen. 
This somewhat mirrors our current behavior in the contact information page. 

## GWT
**Given** a profile where a mobile phone number is saved in the contact information screen 
**When** a user enters the 'editing as a subtask' workflow 
**And** the user doesn't make changes to the phone number displayed 
**Then** saving should return the user to notification settings and display the "saved successfully banner" 

## Tasks
- [x] fix the bug 

## Acceptance criteria 
- [x] the bug is fixed

**Comment by adamwhitlock1** [comment]
So I deployed this to staging, and am able to verify that once you save and no changes are detected that it rediretcs back to the notification settings.

I only thing that is not ideal, is that once the api request is returned with no changes detected, then the button stops showing a loading indicator, but there is a lag between that and the actual redirect to the notification settings page. I think what is happening is that the /user endpoint is hit to 'refresh' the users data after a save, and so that needs to go through first before the redirect can happen.

Not sure where to go with this one at this point, other than maybe look at not doing that /user profile endpoint request specifically for the no changes detected cases.

**Comment by adamwhitlock1** [comment]
I think I have a solution to the lag, so going to spin up one more branch to fix this.

**Comment by mtcA6** [comment]
This looks good! Let me know when you deploy the next fix for the mini pause button indicator situation and I'll re-test!

**Comment by adamwhitlock1** [comment]
I have the latest fixed pushed to staging, so we should now be able to verify that there is no longer a delay in getting redirected when saving with no changes. @mtcA6

**Comment by mtcA6** [comment]
@adamwhitlock1 this looks great! Should I close this or should we wait till your PR is completed?

**Comment by adamwhitlock1** [comment]
I will close this out.
