### ISSUE TITLE
Technical Spike: Research ability to save 526 form data and create new ITF after expiration

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#63533]
See design ticket here: https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/63010

Research and estimate implementation of proposed change. 

Acceptance criteria:

1. Identify way to create test data to accurately replicant current UX when a user has an ITF expire. Validate two possible UX patterns and their current behavior. 
   a. ITF has expired before user accesses their in progress 526 application
   b. ITF expires while user is already in the 526 application 
2. Validate the mechanism that forces the user to restart their application? E.g. is **one or more** of these true?
   a. The current error message that occurs when an ITF has expired forces the user to restart their application since their  
        is no way to access their in progress / draft application
   b. In draft application data is purged when the ITF associated with the application expires
   c. In draft application data is purged when the application expires after x time
   d. In draft application data is purged when the application expires after x time inactive 
3. Build a technical plan to implement the preferred solution as outlined in the design doc: 
   a. When ITF is expired user is greeted with new informational message outlining that their previous ITF has expired, but a new ITF was created
  b. Create and replace ITF
   c. Allow user to continue to in progress application and submit

**Comment by austinjprice** [comment]
@juliepedtke @micahaspyr I believe this captures everything we discussed with Shannon yesterday. Plus I added an additional research ask in 1b. I would like to know how the current pattern works when a user is already in the application before their itf expires as this may take a slightly different UX pattern

also, @micahaspyr Shannon asked about the possible scenarios in 2. Depending on difficulty to assess we may want to break out into different ticket, but can discuss

**Comment by micahaspyr** [comment]
[ITF ticket expiration.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12448767/ITF.ticket.expiration.docx)

**Comment by SamStuckey** [comment]
Can we put this in Github?  ☝️ 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/engineering_research

**Comment by sortizsh** [comment]
- this error is happening inconsistently, but we do not know when it happens and have not been able to reproduce. 
- look into how often it's happening - time box to 1 day. escalate to Jen B. if we aren't able to find solutions 
- think about what type of monitoring we can add 
- check and see if we're logging the fe error in domo (ask Nathan) 
- @micahaspyr

**Comment by micahaspyr** [comment]
I updated the doc with new findings and avenues to fix.  Turns out the InProgressForm is validated when it is finally submitted but gives a nondescript error that doesn't make sense for what is happening which causes the error to be hard to track down. This is all backend related 

I think we can monitor this once I can change the error messaging so we can look for an expired form error. (YAY!) Right now it's an InvalidFormValue error, which is misleading.  That value isn't something set by the user, but automagically when an IPF is saved/updated.  The error needs to mention that there is an expired IPF

I should also be able to write a unit test around checking the expiration of the form itself.  Currently when changing the expiration value in our request spec tests, all tests fail (to be expected) but no insight for those failures is given.  Here is the updated doc

[ITF and IPF things.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/12563982/ITF.and.IPF.things.docx)

**Comment by micahaspyr** [comment]
Well this is annoying/frustrating.  Someone looks to have put a test in vets-api in August to check for an applicationExpirationDate when the in progress form is submitted, but the error thrown is still attached to an InvalidFieldValue, which is not really what should be logged.

That being said, I can switch the error type and message to something more explicit to this scenario.  I feel this portion may be a bit of a dead end now since another group was in the same codebase.

**Comment by micahaspyr** [comment]
Plan of Action:

- Make sure an ITF is active on the review and submit page
  - If not, create one and redirect BACK to the review and submit page
  - If one is active, update the form application expiration date to today on viewing of the application, no matter what page the veteran is on.  
  

IMHO, just accessing the 526 application should be enough to extend the expiration date as it shows the veteran is active in trying to file their compensation claim.

**Comment by austinjprice** [comment]
So is the long and short of it that IPF is a date that expires separately than the ITF and they get out of sync?
