### ISSUE TITLE
Set up feature flag to hide Pension & Burial pages

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#63596]
Description: We need a feature flag to gate whether or not we are displaying the pension and burial forms.
 
Acceptance Criteria:
- a flipper feature flag should be added to the vets-api repo for the burial page
  - the flag should default to false
- a flipper feature flag should be added to the vets-api repo for the pension page
  - the flag should default to false

**Comment by fred-khoury-oddball** [comment]
After research there will be no updating of unit tests for this task specifically. I updated the title to include the burial page as well. This is a one line change in the vet-api repo & vets-website repo for each flag. Now that we know more I think it makes more sense to have 1 pr with a 2 line change in each repo instead of 2 prs with a 1 line change in each repo.
