### ISSUE TITLE
Research | Profile Hub | Research Plan

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#63617]
## Background 
We're moving forward with the Profile Hub, now we need to figure out what the best design by testing with veterans.  

## Keep in mind 

**Are there any other small usability tasks we want to include?**
- ~~If dependents and letters are live in the personalized menu, we could ask something about those~~ [moved to the [concurrent UAT](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-09-UAT-edit-as-subtask-default-send-checkbox-ui/conversation-guide.md#optional-task-1-review-authenticated-menu---5-minutes)]
- Test the “We don’t have your contact information” alert in Notification Settings

**Design Intent IA Feedback #63129**
- Consider: Continuing to work with CAIA for any IA guidance along the way
- Consider: Including a findability task in user research to determine whether to include an additional mobile nav on the hub page

**Design Intent - Accessibility Feedback #63127**
- No real feedback! Just wanted to commit to text the discussion about the left nav. I don't think the left nav is necessary on the profile landing page as presented in the wireframes, but if you eventually end up adding a bunch of extra links to the cards it may become necessary. Definitely doesn't make sense for a keyboard user to tab through two duplicative lists of seven links, but if there's lots of extra clutter in the cards then having quick access in the left nav becomes more helpful

## Tasks 
- [x] Write [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-09-profile-hub-usability/research-plan.md)

## Acceptance Criteria 
- [x] Get [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-09-profile-hub-usability/research-plan.md) reviewed

**Comment by andaleliz** [comment]
@mtcA6 what is the timeline for identifying how we're going to measure success on the hub? I see [that section](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/hub/mvp/README.md#measuring-success) is still TBD on the product outline. That'll be useful information to have to inform the research questions and what we want to test in the study.

**Comment by mtcA6** [comment]
Thanks for the nudge!!! I've added one in there, it's not great, [made a ticket ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63767)so Samara and I can go back and forth and discuss our ideas about this.

**Comment by andaleliz** [comment]
@pamela-drouin [here's a link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690215208596/85132c5e4a025524f742559c6ff773e7f19c4a87?wid=0-1692197534025) to the research questions on the mural board. Since you're leading this one, I'll bow out for now but please don't hesitate to ask if you need anything! Happy to help in any way I can.

**Comment by pamela-drouin** [comment]
Sounds good, thank you, @andaleliz! 🙏 

You know I will definitely have questions 😁

**Comment by pamela-drouin** [comment]
@mtcA6 thanks! I have feedback from @andaleliz as well, so I will start to work on both later today.

**Comment by pamela-drouin** [comment]
@mtcA6 great, thanks, Travis!

**Comment by andaleliz** [comment]
@mtcA6 does it make sense to include any KPIs that measure indications that we haven't negatively impacted things?  E.g. making sure we're not seeing a drastic decrease to any parts of profile, which could suggest people are having a hard time navigating

**Comment by pamela-drouin** [comment]
I've updated the research plan -- most of the changes/additions are around recruitment criteria and screening questions. I would love another look from @andaleliz and @mtcA6 as well as @Samara-Strauss! 

Here's a link to the [research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-09-profile-hub-usability/research-plan.md) for ease of clicking.

I look forward to any/all feedback!

**Comment by andaleliz** [comment]
I'm excited to check it out @pamela-drouin! What is the best way for us to provide any feedback/edits?

**Comment by pamela-drouin** [comment]
@mtcA6 carry over two points

**Comment by Samara-Strauss** [comment]
This looks great to me! The only suggestion I have is that I don't think we need 16 completed sessions, even considering that you have different cohorts. I think we'll get redundant information after a while, and for this kind of usability study, I personally don't think we need more than 8 max. If I recall correctly, participants can only participate in studies every 6 months. So, given that there's a limited pool of folks for all teams to use, I'd like us to be judicious and make sure we're only getting what we need.

Also, this has more to do with the convo guide than the research plan, but I think it would be great if we let people independently navigate to the profile hub instead of landing them there. Since this study is partially about findability, that seems like the best way to assess if the hub is truly helping/scannable/doing its job.

**Comment by pamela-drouin** [comment]
Thanks, @Samara-Strauss! Did I capture the accurate essence of Profile 2.0 and its issues? I really tried to wrap my head around the previous state!

**Comment by Samara-Strauss** [comment]
@pamela-drouin yes, definitely! You did a great job.

**Comment by andaleliz** [comment]
@pamela-drouin this looks fantastic! You've done a great job being thorough and capturing all the needed details, especially in the research goals, questions + hypothesis section.   Here's some more specific feedback you can take or leave 😄 

**Background section**
- You did a great job explaining the background of profile and IA problems!
- The points you make about a11y best practices are accurate, but the profile hub doesn't solve any of them. It may be helpful to add something that helps people connect the dots between those problems and the profile hub. Or, update the a11y section to reflect only the problem that the hub is resolving (which is captured in the 3rd bullet of your hypothesis. 

**Recruitment**
- Perigean will find it helpful if you specify a number of people for each inclusive criteria. For example, "4 people who are 55+", "At least 4 people who identifiy as having a cognitive consideration".  Otherwise, they may give you one of each (who may not show up for the session) or they may try to find only people who match ALL criteria. 
- You have a screener for cognitive consideration in each cohort; you may want to add clarification that the response to that question satisfies that particular criteria.

**Timeline**
- Do you want to have a kick-off meeting with Perigean to be sure they understand the recruitment criteria, and you can review the screener they send out? If so, I recommend calling that out in this section.
- In my experience, magnification sessions don't take much longer than non-magnification sessions, so you may not need 90 minutes for those. Once you write the conversation guide and have a better sense of task timing, it may make sense for you to move those users into the 60 minute group (or however long the non-AT sessions end up being)

**Comment by pamela-drouin** [comment]
@Samara-Strauss I have updated the research plan recruitment numbers. I appreciate your feedback!

@andaleliz Thank you so much for this in-depth feedback! I have adjusted the recruitment details. I have also adjusted how I talk about a11y issues in the background (to better match the hypothesis). If you'd be up for reading it again, that would be great. I want to ensure I'm being accurate in my description.

**Comment by pamela-drouin** [comment]
@Samara-Strauss -- thank you for catching that! I do need to update that! Everything else is up-to-date except for that.

**Comment by andaleliz** [comment]
@pamela-drouin this all looks great! 

I have one request - can we please specify that we want at least 2 magnification users on desktop? I really want to validate that the multi-column approach isn't problematic, especially since this pattern hasn't really been tested with magnification users on desktop in other parts of the site.

2 other things that I'll comment on are: 
- For cohort 3, you have a screenreader question that qualifies them for using a screenreader, but not for a screenreader _on desktop._   The question has some mobile devices as options, so you may want to rewrite that to use desktop screenreader examples (JAWS is one, which is already there; NVDA is another, and VoiceOver on a Mac could be a third option), or add one more screener to clarify they must join on desktop.
- the cognitive consideration question for cohort 1. this one is missing a detail that is present in the other cohorts: "we need a minimum of 3 people with cognitive considerations, so after this requirement is met, any response is acceptable" Not sure if that is intentional or not but wanted to call that out in case it wasn't.

This is exciting! I'm looking forward to checking out the conversation guide.

**Comment by pamela-drouin** [comment]
@andaleliz updates have been made. I appreciate your feedback!

**Comment by pamela-drouin** [comment]
@mtcA6 I think this is actually done -- have you had a chance to review?

**Comment by mtcA6** [comment]
@pamela-drouin sure thing, I can review! I suspect because it's "In Progress" I didn't know it was ready. 

RE: auth menu questions, If you have the time and can fit it I think that's a great idea, we just saw movement on the analytics questions which is what was preventing us from launching. Hoping we can have that resolved in a couple of days and can start to launch. 

cc: @Samara-Strauss would be great to get your eyes on the research plan as well to make sure I don't miss anything

**Comment by mtcA6** [comment]
@pamela-drouin [here ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/Research/2023-09-profile-hub-usability/research-plan.md#research-materials) it would be good to link to the conversation guide. And I think you might be able to add the link to the hub (https://staging.va.gov/profile) even though dev isn't complete.
