### ISSUE TITLE
[Spike] Implement Cron Job for Bulk Facility Fetches

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#63696]
In related efforts to improve bulk facility fetch performance as noted in [this ticket](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/63695), we think there's potential for a cron job that regularly fetches an updated facility list to be another possible approach. This ticket will be to look into the viability of this option and research other examples of how to best use them.

A few notable questions that will need to be explored:
- How do we minimize stale data?
- If the job refreshes every night, can MFS handle the load?
- If the job extends the expiration time will it increase the chances of out-of-date data being cached?
- The mobile team caches appointments and can provide guidance on handling outdated cached data caused by changes made in external systems. What are some key takeaways from their implementation?

We could possibly refer to `modules/mobile/config/initializers/va_facilities.rb` in vets-api for a dictionary of VA facilities. 

We'd like to look into the above questions and ultimately determine if this is a viable option or not.

Timebox: 30 hrs

**Comment by ajmagdub** [comment]
The Vets API currently uses Redis to cache facility information. Whenever a user requests facility information, the Redis cache is checked first to determine if the facility is already cached. If the information is present in the cache, it is retrieved and sent to the user. If the information is not cached, the Mobile Facility Service (MFS) is queried to fetch the information, which is then cached and sent to the user. Facility information is kept in the cache for twelve hours.

The 'cron' function is not typically used for tasks that occur periodically in the Vets API. Instead, it is preferred to use Sidekiq for processing. To create a Sidekiq job, it needs to be registered in the `lib/periodic_jobs.rb` file, while the implementation of the task should be placed in a `modules/vaos/app/sidekiq` directory.

Since these tasks are designed to run automatically, monitoring uses the [Sidekiq UI](https://depo-platform-documentation.scrollhelp.site/developer-docs/sidekiq-jobs).

Vets API caches both parent and child facilities. However, the **va_facilities.rb** file in the mobile app only references parent facilities and would need to be updated to include child facilities.

As this task is expected to run during off hours, there will be little load on the Mobile Facility Service. However, we need to be cautious about not overloading MFS, as it has been observed that high loads often lead to the deactivation of backend service pods.

Although facility data is less susceptible to change than appointment data, the issue of outdated data still needs to be addressed. Currently, the facility cache is programmed to expire every twelve hours to balance the benefits of caching against the risk of serving stale data. To prevent data from becoming too outdated, the process must fetch facility information from MFS and replace the cached data.

The benefits of nightly refreshing the cached facility data vs allowing the cache to expire and then be recached during the next request for the same facility should be weighed. The average time to get a facility response from MFS is approximately 0.5 sec, and once that response is cached it will be available for 12 hrs. This cost occurs normally during requests for appointment lists and if none of the facilities are cached is about one third of the total time to get an appointment list; but once in the cache this cost is spread out over other requests for the same facility within the same twelve hour period. It doesn't seem like Vets Web would gain much from refreshing the cache on a nightly basis.
