### ISSUE TITLE
Add AVS Link to Appointment Response for Past Appointments

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#63692]
This ticket is for the technical implementation of the work from this spike: https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/63359

We would like to provide an after visit summary link in our appointment response for displaying on past appointments. The logic would roughly follow these steps:
- we will only be applying an AVS link to past appointments, we can look for a status of `booked` and a `startDate` that is in the past to determine this
- extract the station number and IEN from the `identifier` field in the appointment response
- pass these values on to a vets-api `AVSService`, which will call out to the AVS endpoint outlined in the spike
- that endpoint will return a path field containing the AVS link, which we will then add to the appointment response under a new field `avsPath`

AC:
[ ] - create a vets-api `AVSService`, which will query for an AVS link based on an appointment's station number and IEN
[ ] - add new `avsPath` field to appointment response, containing the returned link
[ ] - unit and integration tests for new functionality

**Comment by ldelacosta** [comment]
@young1205 - once the [FE ticket #62906](https://app.zenhub.com/workspaces/appointments-team-603fdef281af6500110a1691/issues/gh/department-of-veterans-affairs/va.gov-team/62906) is completed and validated (and there are no issues), you can close this ticket out. We can leave it open until the initiative is complete. If @cferris32 requires a new vets-api ticket, we can open a new one. cc: @JRRoof

**Comment by cferris32** [comment]
Adrian has provided the following details for AVS testing in staging:

- staging hostname for AVS endpoint: `https://oitdvrappclin04.r01.med.va.gov/avs/api`
- station 500 and appointment ien 34376 are available for test calls
- according to Adrian we will need to use a param store to store the jwt for this endpoint, details [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/store-a-secret-in-parameter-store)

**Comment by ajmagdub** [comment]
Changes are behind the **va_online_scheduling_after_visit_summary** feature flag.

Made several changes to the **VAOS::V2::AppointmentService** class. An After Visit Summary (AVS) link is now included in the `get_appointments` and `get_appointment` responses.

Added the following helper methods to the VAOS::V2::AppointmentService class:
`fetch_avs_and_update_appt_body`: retrieves an AVS link from **AVS::V0::AvsService** for a given appointment. 
It updates the appointment's avsPath with the obtained link. If it encounters an error during these operations, 
it logs it and sets the avs_path to nil. 

`get_avs_link`: Retrieves an After Visit Summary (AVS) link for a given appointment from the AvsService. 
It ensures station number and appointment ien are available and verifies that the ICN from an AVS service response 
matches the user ICN. If these conditions fail, it logs any mismatches and returns nil. Otherwise, it returns the AVS link.

`avs_service`: A memoized method to get a AVS::V0::AvsService instance.

`avs_applicable?`: Checks if the appointment is in the past and is booked.

`extract_station_and_ien`: Returns the station number and appointment IEN if it exists, nil otherwise.

`normalize_icn`: Strips out the trailing V + 6 digits, checksum, from ICNs

`icns_match?`: Checks if two normalized ICNs match

Updated VAOS Swagger Appointments schema with added avsPath attribute.
