### ISSUE TITLE
FE | Profile | Contact information | Update change address sign in CTA

### ISSUE THREAD

**Issue by andaleliz** [department-of-veterans-affairs/va.gov-team#64085]
## Background

On va.gov/change-address/, the sign-in CTA keeps the user on the page after signing in. Let's update it so a person is redirected to `/profile/contact-information/` upon signing in.

## Tasks
- [ ] Update CTA widget to redirect to the profile instead of keeping a person on the page

## Acceptance Criteria
- [ ] user is redirected to `/profile/contact-information` after signing in on va.gov/change-address/.

**Comment by adamwhitlock1** [comment]
I took a look at the change-address page, and I would like to discuss if making the CTA auto-redirect is the best idea for this.

Because there is specifically a section that talks about the benefits that need to have their contact info updated directly through that department that handles each benefit instead of using the Profile contact info, it feels like auto-redirecting everyone could impact those people looking for that information.

Users wouldn't be able to see the section pictured below if they are automatically redirected
<img width="716" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af162116352d6f8394f2ae2d310178b29cce981b/Screenshot%202024-05-16%20at%209.28.26%E2%80%AFAM.png" alt="Screenshot 2024-05-16 at 9.28.26 AM.png" />

**Comment by ACParker89** [comment]
Closing 5.20 based on a conversation in huddle to not complete the work- ux is poor, and requires further discussion.
