### ISSUE TITLE
[SPIKE] Figure out how to fetch all appointments for a Veteran for some period of time regardless of station/facility

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#64096]
## Background
[Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1692893127087559)

## Tasks 
- [ ] Figure out if we have a way to fetch all appointments using LoROTA (ASAP)
- [ ] Figure out how to fetch all appointments for a Veteran for some period of time regardless of station
    - Determine all of our implementation options & their pros/cons
    - If we can't do above, could we get all appointments for a single station

**Comment by brianseek** [comment]
slack convo here: https://dsva.slack.com/archives/C022AC2STBM/p1692893127087559

**Comment by brianseek** [comment]
github doc outlining pros and cons of potential paths: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/decisions/all-appointments-fetch.md

**Comment by brianseek** [comment]
Had a meeting with Stephen, Shane, and our team. Stephen started a conversation in #nextgensharedservices to see if we could use the same route as mobile and VAOS to fetch appointments with LoRota.

We identified a potential plan b of fetching stations associated with a patient either via MPI (Master patient index) or the lighthouse appointments api, then batching multiple vista requests to fetch appointments. This is plan b because other teams have already done this work and we should see if we could also leverage existing work.

Going forward, it will take a couple of weeks for Stephen to get an answer and in the mean time our team will work on the FE side of things and potentially do some spiking into plan b.

**Comment by loripusey** [comment]
Here is a link to the [Slack convo](https://dsva.slack.com/archives/C022AC2STBM/p1692893127087559) where Stephen dropped some documents and links for implementation purposes
