### ISSUE TITLE
[Design] Onsite Notifications: Update My VA health section use case documentation

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#64258]
## Background
Once the experiment around the dot indicator on My VA Health unread messages is complete and we have a path forward for full implementation, we'll need to update our use case documentation accordingly.

## Tasks
- [ ] Update use case documentation

## Acceptance Criteria
- [ ] documentation is updated

**Comment by aagosto90** [comment]
Latest [health care use case documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/use-cases/health-care-use-cases/health-care-messages.md) includes language about the red indicator (has been updated since we used to have an unread messages alert). It should be updated again if we ultimately go with something other than the red dot indicator for unread messages.

**Comment by ajakabcin** [comment]
Thanks @aagosto90 ! These updated are getting incorporated into the product guide as well
