### ISSUE TITLE
Page Feedback Mechanism 

### ISSUE THREAD

**Issue by aubreyarcangel** [department-of-veterans-affairs/va.gov-team#64271]
## Product Outline
[Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md)

## High Level User Story/ies
As a _____, I need _____ so I can _____.

## Hypothesis or Bet
**If** _we make this change_ **then** _we expect this to happen_.

## OKR
_Which Objective / Key Result does this epic push forward?_

### What must be true in order for you to consider this epic complete? 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

## How to configure this issue
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `Console-Services`, `tools-fe`,`content-ia`, `service-design`, `vsa-*`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by UXCamG** [comment]
# Draft: Research Plan for Search & Discovery Team, Resources and Support, Submit Feedback Tool 2.0

## Background
Resources and support (R&S) contains tier 2 content (benefit-adjacent content). The Submit Feedback Tool was introduced to R&S article pages last year with the option to rate articles as either good or bad. As a part of the Submit Feedback Tool 2.0 product initiative, once a user rates an article as 'bad', we would like to implement a way for users to report the reason why they rated the page poorly. We would also like these issues to be actionable and easily accessible for the content owners so that improvements can be easily made.

We would like to make improvements to the layout of R&S article pages. Overall, links on R&S articles do not have a high engagement rate. CTA had the highest click through rate and Tags had the lowest click through rate. Participants in the <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/learning-center-mvp-findings-summary.md">last R&S research study</a> did not see tags as clickable. <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/on-site-search/research/user-research/2021-Aug-research-study/research-findings.md">Previous research</a> has shown that users are hesitant to click on R&S because the name and we would like to further explore that issue as well. "Value and Purpose" was also identified as a top issue during our <a href="https://github.com/department-of-veterans-affairs/va.gov-team/issues/32746#issuecomment-970466533">roadmap session</a>.

- <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/resources-and-support/article-pages/discovery.md">Discovery: Resources and Support Article Pages</a>

- <a href="https://github.com/department-of-veterans-affairs/va.gov-team/issues/32746#issuecomment-970466533">Resources and Support Roadmap Session Summary</a>

- <a href="https://github.com/department-of-veterans-affairs/va.gov-team/tree/69833737d9fe22b8990bb987e7c50de13205c5d5/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research">Learning Center Original Reseach Folder</a>
	- <a href="https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/discovery-and-research/learning-center-mvp-findings-summary.md">Learning Center Moderated Usability Study</a>

[Link to product brief coming soon]

### OCTO Objectives 
Improving Resources and Support will allow Veterans and those in their support system to find information on utilizing their VA.gov account, gaining supplemental information on benefits, and easily find links to apply for benefits or make changes to their account.

### Veteran Journey
Resources and support impacts the Veteran journey from Starting up and all phases thereafter.

## Research Goals and Questions	

### 1. Validate that users are able to easily use the Submit Feedback Tool to rate the article page and report an appropriate problem.
- Are users able to find where they can report feedback?
- What do users expect to see after they submit feedback?
- In what situation would a user rate this page? Why would they rate it 'good', why would they rate it 'bad'?
- Does the wording make sense? If not, what should it say?
- Do the options under "Report a problem' make sense to users?
- What other types of problems would they expect to report?
- What do users think about the amount of issues presented to them? Is the amount overwhelming?
- What are their perceptions on the difference between this feedback tool and Medallia?
- **Content creator question:** 
	- What type of feedback is helpful and actionable to them?
	- How can we make this feedback more accessible to them?

### 2. Are users able to easily navigate and discover the feedback mechanism on the article pages?
- Are CTAs clear to the user?
- What do users think of the "Related information" section?
- What do users think of the "Va benefits" section?
- What do users think of the "Tags" section?
- Do users utilize a search bar on the article pages?
- Do users utilize list of topic links on the article pages?


### 3. Is the question "How would you rate your experience" a helpful title that tells users what they will find?
- What do users think of the title, "How would you rate your experience"?
- If users do not feel like "How would you rate your experience" reflects what they find on the section, what else would they name it?


### Outcome
We will confirm whether:
- Updates allow users to provide feedback which will inform content editors on changes that can be made to improve R&S articles
- Updates to R&S article pages improve navigation and discoverability of more R&S articles
- The name "Resources and support" accurately informs users of what content they will find


### Hypothesis

- Users will not know the purpose of the rate your experience feedback mechanism, 
- The good/bad buttons that are currently used to track feedback, are not helpful as the data is only recorded in Google Analytics. 
- Users will be more likely to use the feedback button near the footer to leave feedback on the Article page 


## Method	
We'll conduct remote usability testing over Zoom using a prototype.

### Location
Zoom

### Research materials
*Note: your OCTO/VA lead must review and approve all research materials – including this plan –  prior to submitting a recruitment request.*

Provide a link to any materials you need to run your study, including any materials needed for set up and recruitment.  

For moderated interviews:
- [Link to conversation guide](url goes here) 

For moderated usability tests: 
- [Link to conversation guide](url goes here)
- [Link to prototype](url goes here)

	
## Recruitment	

### Recruitment approach
We will recruit Veteran participants using a lean maximum variation strategy. We'll leverage Perigean's recruiting services to find our participants.

### Recruitment criteria
Schedule 10 Veterans for a minimum of 8 successfully completed sessions.

**Primary criteria (must-haves)**

- 50% of participants should be able to participant from a desktop device.

- 50% of participants should be able to participate from a mobile phone.



**Secondary criteria (nice-to-haves)**

**Gender**
- 8 women, 8 men

**Inclusion**
- 3 participants who use assistive technology (e.g. screen reader, magnification)
- 10 participants who identify as other than white
- 5 participants who identify as other than straight/heterosexual and cisgender
- 8 participants age 55+
- 8 participants who identify as having a cognitive disability
- 5 participants who do not have a college degree
- 5 participants who live in a rural area


## Timeline
If you are using Perigean to recruit please submit 1 FULL week prior to the start of research for remote research, 2+ weeks for in person. 

### Prepare
When will the thing you are testing be finalized? (Goes without saying, but should be a few days before testing will begin.)

Please indicate the date and name of a mock participant for a pilot session. 
* Pilot participant email:
* Date and time of pilot session: 

### Research sessions
What dates do you plan to do research? 

### Length of sessions
45 minutes. Perigean will schedule the sessions with buffer 15 minutes of buffer time to allow for participants who can't make it on time, or if you might go over time.

### Availability
When would you like sessions scheduled? Please list exact dates and times in EASTERN Standard Time. *Note: we recommend providing availability outside of work hours, as many Veterans are only available before and after working times, and live across the U.S.* 
Please request enough dates and time slots for the number of requested participants. (e.g. Monday 9-1, 3-6; Tuesday 9-6, etc.). 
	
## Team Roles	

- Moderator: Camille Green ,404-428-2313,Camille.green@oddball.io
- Research guide writing and task development: Camille Green
- Participant recruiting & screening: Perigean	
- Project point of contact: Camille Green
- Participant(s) for pilot test: TBD	
- Note-takers: Perigean, Aubrey Archangel, Sarifa Khalilullah 
- Observers: chante.lantosswett@va.gov,anita.middleton@oddball.io

**Comment by clantosswett** [comment]
Closing this epic because a new one was created with more details.

**Comment by ATMiddleton** [comment]
Combined with #66409
