### ISSUE TITLE
Create a test plan for unit test allow list

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#64287]
# Description
Let's analyze the functionality and logic we are aiming to create with the unit test allow list system. Then we can use TestRail to create a test plan. Our test plan should include manual test cases as well as a list of automated tests that we expect to create.

# Acceptance Criteria
- [ ] Unit test allow list test plan is available for execution in TestRail
- [ ] Stubs for automated tests are listed in the test plan
- [ ] Detailed steps for each manual test case are listed

**Comment by IGallupSoCo** [comment]
Unit Test Allow List - Test Plan


File(s) to be tested:
unit-stress-test.yml


Jobs to be tested:

testing-reports-prep

fetch-unit-allow-list

stress-test-cypress-tests

update-unit-allow-list


Test scenarios:
All tests pass, no flakiness
With an “empty” allow list
With a “full” allow list
All tests fail, no flakiness
With an “empty” allow list
With a “full” allow list
Unit test is identified as flakey for the first time
A single test is identified as flakey
Multiple tests are identified as flakey
A flakey test is resolved by the responsible party
The PR is merged and the associated GitHub issue is closed/solved
The resolved unit test is returned to the allow list

Needed fixtures/inputs:
A set of allow lists tailored for each test scenario
All necessary environment variables
All expected tokens/credentials

Questions/needs/decisions to be made:
Initial scope?
Long term scope?
Where are the damned yarn scripts stored?
What do we need to do in order to intercept/capture outputs without modifying the code?
A crash course on non-e2e testing

**Comment by IGallupSoCo** [comment]
Local Github Action testing is a thing, but it won't provide for an automated solution as it exists now.  We might be able to adapt the functionality into an automation solution, though.

**Comment by IGallupSoCo** [comment]
Would it be possible to create a new Github action and begin by subbing out the default repo, as shown, to a cloned, static repo?

steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

**Comment by IGallupSoCo** [comment]
It would make sense to me to create three new jobs in the single, new workflow.  First a test version of fetching the allow list, then testing prep and execution.  The Prep job is where the repo to be used is designated, test variables are defined, and the number of test iterations is determined.  We could point the test prep run to a stripped down, static repo and separately define any paths that aren't relative to the repo.

**Comment by IGallupSoCo** [comment]
Currently within the e2e stress test workflow, this block of three jobs sets up the test runs:
fetch-e2e-allow-list
cypress-tests-prep
stress-test-cypress-tests

This takes some assumption, but I suspect that the unit test stress test will have a block of jobs like this:
fetch-unit-allow-list
unit-tests-prep
stress-test-unit-tests

I propose, in the case of the unit test, we add this to the workflow immediately before those jobs:
fetch-self-diagnostic-unit-allow-list --> new path to a stripped down, static repo
unit-self-diagnostic-test-prep --> same new path as above
self-diagnostic-stress-test-unit-tests --> repetition testing, except, instead of for flakiness, for testing all test cases

**Comment by IGallupSoCo** [comment]
After a sync meeting with Peter and Curt, we are refocusing the testing effort to only the JS scripts being called by by the stress testing workflows.  For now, we will explore options that use GitHub Actions.

**Comment by IGallupSoCo** [comment]
Scripts to be tested:

generate-app-list.js - two uses
get-allow-list.js
update-unit-allow-list.js
cypress-mochawesome-to-bigquery.js
create-github-issues-for-flaky-tests.js

So far I've located one of these scripts.

**Comment by IGallupSoCo** [comment]
https://dsvavsp.testrail.io/index.php?/suites/view/2740&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

**Comment by JoeTice** [comment]
Sprint 34 Update - In Progress, Work will continue in Sprint 35
