### ISSUE TITLE
Request Pre-launch ATO review/ Confirm pre-launch ATO readiness

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#6460]
**Notes about issue:**
In Oct/Nov ATO Review was considered complete (#2431). 
I want to make sure we have consider ATO from both VAOS side and VA.gov side. It's unclear to me however if anything has changed from Oct/Nov to now. 

## Answer the following: 
- [ ] What data is VAOS-R collecting? For example, what data are you requesting from users?
- [ ] What data is VAOS using? For example, what data are you requesting from some VA service?
- [ ] Where does that data come from? For example, what API endpoint are you getting the data from?

**Reference ATO documentation here:** https://github.com/department-of-veterans-affairs/va.gov-vfs-teams/blob/master/Request-Reviews/request-ato-reviews.md

**Comment by lenaecb** [comment]
@andreahewitt-odd - This is circling a bit, so I decided create a ticket to track it.

@saneshark - is going to be answering the 3 questions outlined above here in the comments. We're hoping that will help VSP decide on ATO needs for VAOS. We do not think there is any concern/changes that would warrant another review, but we'll let you all decide.

**Comment by saneshark** [comment]
> What data is VAOS-R collecting? For example, what data are you requesting from users?

In addition to email / phone, all other data is populated by a drop down list or appointment location / date time information selection through a calendar tool. The only exception is "reason for appointment." This is an open text field and the user could provide information such as "HIV Appointment" or "Drug / Alcohol" or who knows what. I would characterize this field as the riskier of the fields we are introducing. That being said it is only stored "in memory" and never cached. It is provided by the user, sent to vets-api, who in turn sends that request to VAMF. We do not store it or cache it in any way.

What data is VAOS using? For example, what data are you requesting from some VA service?

Available appointment times, health care facility triage teams, data pertaining to decisioning on community care, upcoming and future appointment information. In addition vets-api uses SSN and other data as part of its JWT session token when making requests to VAMF. The PII is never cached and vets-api is acting strictly as a pass through. In fact, in this manner we also suppress low risk PII such as ICN and EDIPI which would otherwise be a part of the URI scheme.

> Where does that data come from? For example, what API endpoint are you getting the data from?

The data comes from a variety of upstream sources through services exposed by the VA Mobile Framework and Lighthouse API team. Some of their upstream dependencies include CDW, VistA, PPMS, and other sources.

This might not go into as granular detail as you are looking for but please let me know and I am happy to elaborate.

**Comment by lynnecase** [comment]
Just FYI, we do not "ATO" individual applications.  Each app is a minor application inside of the one MAP environment.  We cover all of our interfaces such as CDW, Vista, etc. at the platform level.  Each app is then just a "minor application" inside of the MAP major app.  So, with the web service being hosted in VA.gov, we have a new interface from VA.gov into our platform, but it doesn't fundamentally change anything.  It doesn't change the data we are storing or receiving.

**Comment by nsmith1982** [comment]
quick question, or not:  has a Privacy Threshold Assessment (PTA) or Privacy Impact Assessment (PIA) been conducted? To clarify VAOS doesn't actively store PII it's only cached for 15 mins and then purged?  What security measures are in place if there's an incident during that 15-minute caching window?

**Comment by saneshark** [comment]
There aren't any security measures in place that go beyond that which the VSP platform already has in place. If an incident arose the incident commander would get me and any other upstream partners from whom we receive the data involved and we'd work through the challenges.

We have logs in cloudwatch that give detailed and accurate history of every single user action performed as part of VAOS which include remote IP Address and other information which could aid an investigation. Beyond this we're really not doing anything more than what VSP makes available.

To my knowledge a PTA / PIA for the redesign work on VSP was not performed as an addendum to any existing ones as part of this effort. As for upstream APIs being consumed from VAMF, I don't know but would imagine they do exist.

**Comment by lenaecb** [comment]
I am moving this to our 'Epics' column and providing the following update on next steps. 

Per meeting with Chris J and Kevin H, it's been determined that VAOS will be absorbed into the existing VA.gov ATO and no 'new' ATO we be needed specifically for VAOS. 

We are taking the next following steps to ensure full and proper ATO accountability for new VAOS-R on VA.gov:

1. We will be updating the current ATO documentation for VA.gov to account for VAOS as an access point - "VA.gov is now an entry point to another system (MAP) via the VAOS application."
2. Reaching out to VAOS to confirm if it's necessary to also update their ATO documentation to include something similar to this - "MAP is now an entry point to another system (VA.gov platform) via the VAOS application."
