### ISSUE TITLE
discovery -- login.gov account creation flow on VA.gov

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#64619]
As a PM I need to understand the user experience when a Veteran creates an ial1 account on VA.gov so that I understand the potential Veteran outcomes for interstitial page implementation.

AC:
document user flow on VA.gov for login.gov account creation
Questions to answer:
- what happens after mfa? Is Veteran forced into identity verification or can they return to VA.gov?
- what happens if a Veteran cannot complete verification?
- at what point is the Veteran redirected to VA.gov?
- if account creation is unsuccessful, what information can we offer the Veteran for support? Can the flow be updated to illustrate where they can go to next?
- set up time with Dawn, Porta, Lauren 

DEF OF DONE:
- [ ] ~user flow and answers to questions documented on Mural https://app.mural.co/t/innovationboards1199/m/innovationboards1199/1692029447960/78e61d1057d7aa48c5f655c4980ffbca7b87de3f?sender=uc3c8b97062727fbe21716300~
- [X] answers to questions documented in Github (to preserve formatting not available in Mural)
- [ ] review internally with PM and share with PO for vetting the flow

**Comment by porta-antiporta** [comment]
@djmunoz1 @MOStudioCarolyn here are some responses to the questions in anticipation of ourmeeting:

**what happens after mfa? Is Veteran forced into identity verification or can they return to VA.gov?**

This is all dependent on the authentication request that VA.gov sends to Login.gov.

** IAL1 ** Requests Login.gov to send just the email and UUID.
** IAL2 ** Requests Login.gov to send email, UUID and PII attributes requested (Available attributes for request are at [Login.gov's developer site](https://developers.login.gov/attributes)
** IALMAX ** returns the highest of what the Veteran's account is now.

So if a VA.gov sends a Veteran to Login.gov with an IAL2 request, Login.gov will automatically have the Veteran perform enough steps to get the requested information to be sent back to Login.gov. It's important to note that Login considers "Creating an Account" the steps to get an IAL1 account, and "Verifying" the steps to get an IAL2 level. This isn't always clear to the Veteran/user.

i.e. look at the following scenarios.

- Veteran does not have a Login.gov account
   - The Veteran will choose Create account (as they don't have an existing one) Login.gov will have the user create an account (IAL1 which includes configuring an MFA) and then will immediately send the Veteran to start identity verification. After identity verification, Login.gov will send the PII back to VA.gov
- Veteran only has a Login.gov IAL1 account (say used at usajobs)
    - After the Veteran signs into their account,  Login.gov will recognize the account is only IAL1 and immediately have the Veteran start identity verification. After identity verification, Login.gov will send the PII back to VA.gov
- Veteran has a Login.gov IAL2 account
    - After signing in Login.gov recognizes the account is IAL2 already, so just sends the PII back to VA.gov.

- what happens if a Veteran cannot complete verification?
     - Each RP can configure a <FAILURE-TO-PROOF> URL which is where Login.gov sends the user to if they click the "Get Help from <RP>" link on any of the interim or end failure pages on Login.gov.
     - What I mean by an interim failure page: A failure page where a user can retry their attempt at that step (ex. reupload image of their ID)
     - What I mean by an end failure page: if a user exhausts the attempts they have, Login.gov has a page where it indicates the user cannot retry until they've waited some more. At the bottom of the page they have the "Get Help from <RP>" link.
     
- at what point is the Veteran redirected to VA.gov?
   - Veteran is redirected back to VA.gov upon successful verification of their PII.
   - If the VA.gov is the <FAILURE-TO-PROOF> URL, then Veteran also gets sent there if they click on that link on a failure page on Login.gov.
   
- if account creation is unsuccessful, what information can we offer the Veteran for support? Can the flow be updated to illustrate where they can go to next?
    - When we say account creation is unsuccessful here, are we using the Login.gov parlance (i.e. failed to create an IAL1 account?) or we including IAL2 failures?
    - For failed IAL1 account creation, we don't know if the Veteran will come back to VA.gov, i.e. they could just close the browser.
    - For failed IAL2 (identity verification), the Veteran only "comes back" if they click on the "Get Help at <RP>" link. As a result, we can configure whatever content needed on that URL. Note, likely this already exists today as part of the initial launch of the VA.gov and Login.gov integration.

**Comment by porta-antiporta** [comment]
@djmunoz1 i tried transposing the above in MURAL, but with MURAL's poor formatting capability, think it's better to have the comments in this ticket.
