### ISSUE TITLE
[bug spike] SC same-day submission 422 error

### ISSUE THREAD

**Issue by saderagsdale** [department-of-veterans-affairs/va.gov-team#64894]
- a few 422 (unprocessable entity) errors experienced by the same Veteran; seem to have been resolved.
- Want to investigate and resolve so that it doesn't happen for any other Veterans.
- Link to [Slack thread](https://dsva.slack.com/archives/C5AGLBNRK/p1693919012689079)
- Kyle's commentary on issue: 
  - "Unprocessable Entity Error x3 (account UUID = 87e3e651-3949-4a65-b9ec-fcda21dc0e9d; SiP ID = 8912132 twice, and one unknown). This in progress form also does not exist, so the user got the errors, and changed whatever was needed to somehow, to get a successful submission. So this is not super urgent I dont think, but we should still make a ticket to prioritize and investigate the 422 error as the goal is to not make it possible for the user to send a bad request downstream"
- [Sentry link](http://sentry.vfs.va.gov/organizations/vsp/discover/results/?end=2023-09-06T04%3A59%3A59&field=message&name=Supplemental+Claims&project=4&query=url%3Ahttps%3A%2F%2Fwww.va.gov%2Fdecision-reviews%2Fsupplemental-claim%2Ffile-supplemental-claim-form-20-0995%2F%2A+level%3Aerror+message%3A%22vets_server_error%3A+Unprocessable+Entity+Error+%2Fgenerated%2F995-supplemental-claim.entry.js+%3F%28generated%2F995-supplemental-claim.entry%29%22&sort=-message&start=2023-08-28T05%3A00%3A00&widths=-1)

**Comment by data-doge** [comment]
Bug: veteran submits SC on same day as decision date, get 422. Lighthouse requires submission to be on future date. So, we need to figure out what the VBA policy w.r.t. these two questions:
1. Is there any problem with a same-day submission?
2. What is the datetime cutoff, and what timezone is that cutoff. 

@saderagsdale to direct these questions to Emily, Carla, and Michael H.

If VA says same-day submission allowed, then LH needs to change. Otherwise, we need to update our validation to adhere to datetime/timezone cutoff.

**Comment by saderagsdale** [comment]
I sent an email to Karla Leal just now.

**Comment by saderagsdale** [comment]
@kylesoskin @data-doge Karla Leal sent a response: 

> They can submit it the day of their notification letter. So, if the rating decision is finalized 9/18 and their notification letter was sent 9/19 they can submit their supplemental claim 9/19.

**Comment by kylesoskin** [comment]
From what Karla just said in the latest response email the following is true: 

"a veteran can never file an appeal, on the same day as their decision date"

Given that, @Mottie , I think we need to protect on this on the frontend. 

cc @saderagsdale that I am moving this out of blocked now and into the sprint backlog.

**Comment by Mottie** [comment]
Yes, the frontend is already checking and preventing same day submissions, but only in the Veteran's timezone. What timezone is the backend using?

**Comment by saderagsdale** [comment]
@kylesoskin Were you able to get an answer to the above?

**Comment by data-doge** [comment]
I've been tracking Veteran with user_uuid `89b75cba7bf6407d8abc6ee09ba3aeec`, who was experiencing this error repeatedly over the course of several days. They no longer have an InProgressForm, which suggests the issue was resolved. We suspect the issue was the result of the Veteran misinterpreting the decision date field on the Add Issue page as asking for today's date.
