### ISSUE TITLE
Properly deal with errors from MAP STS service

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#65130]
The MAP STS token generation integration doesn't seem to properly deal with error responses from the service, so we should figure out what they're returning and why we're not dealing with it properly

**Comment by achievedaniel** [comment]
@bosawt  Did you get a body response that included body[:error_description] I can't replicate any response error with that. 

The issue seems to be that the errors response bodies are fairly useless and have ambiguous descriptions. For example if we pass a non existent ICN and it just returns "Internal Server Error" in the body. Also if you pass the wrong JWT it just returns "invalid client". Not sure we will get any good description from the API itself.

**Comment by achievedaniel** [comment]
When there is something wrong with the API or the RSA key is invalid the api returns:
 `e.body = "{\"error\":\"invalid_client\"}"
  e.status = 401
 `
