### ISSUE TITLE
Create Prototype for Viewing, Adding, and Editing Next of Kin and Emergency Contact Information in VA.gov Profile

### ISSUE THREAD

**Issue by LynneJohnson224** [department-of-veterans-affairs/va.gov-team#65163]
**Description**
As a Veteran, I need to be able to view, add, and edit my Next of Kin and emergency contact information, so that VA has this information in case of an emergency.

As an OCTO Stakeholder, I want to see a production-quality, demoable prototype of this feature, even if back-end API access for Next of Kin and emergency contact is not yet available. The prototype should mimic real-world interactions based on the API format.

**Acceptance Criteria**

- Request access to the back-end API for Next of Kin and emergency contact information.
- Design the UI/UX fields for viewing Next of Kin and emergency contact information in the VA.gov profile.
- Build a demoable prototype with the newly designed fields.
- Conduct unit and UI tests to ensure the prototype is functional and meets design specifications.
- Present the prototype to internal stakeholders for review and feedback.
- Create documentation outlining the prototype's features, limitations, and next steps for full implementation.

**Comment by LynneJohnson224** [comment]
@radavis can you please add a story point value?

**Comment by radavis** [comment]
**Acceptance Criteria**

- [x]     Request access to the back-end API for Next of Kin and emergency contact information.
- [x]     Design the UI/UX fields for viewing Next of Kin and emergency contact information in the VA.gov profile.
- [x]     Build a demoable prototype with the newly designed fields.
- [x]     Conduct unit and UI tests to ensure the prototype is functional and meets design specifications. 
- [x]     Present the prototype to internal stakeholders for review and feedback.
- [x]     Create documentation outlining the prototype's features, limitations, and next steps for full implementation.

**Prototype Features**

- read and display NOK/EC from vets-api serving mock data
- initial backend API implementation: `{GET, POST} /v0/{emergency_contacts,next_of_kin}`, OpenAPI documentation, building off of existing Vet360/Profile API classes, validation errors
- frontend components (approximately) styled to provided designs.
- redux actions, selectors, reducers for NOK and EC

**Prototype Limitations**

- Presents Help Desk phone number instead of a form for adding/editing NOK/EC. (no add/update)
- Limited to one EC and one NOK entry.

**Next Steps**

- onboard with VA Profile API team
- complete front-end view logic and add tests
- refactor back-end code, if necessary
- integrate feature into Profile's "Contact Information" section

**Comment by radavis** [comment]
backend: https://github.com/department-of-veterans-affairs/vets-api/pull/13739
frontend: https://github.com/department-of-veterans-affairs/vets-website/pull/25845
