### ISSUE TITLE
[BE] 10-10EZ - Performance: Create and run tests for non-critical endpoints

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#65197]
As a Veteran, I would like to be able to submit my 10-10 EZ during peak submission times so that I can get the PACT Act-related benefits that I have earned.

- [ ] Test Submission API at 100x the normal rate (100x/minute)
- [ ] Record results
- [ ] **Success: We know that the `health_care_applications/rating_info` endpoint can handle 100x requests per minute and that they get to the ES okay. We have documentation, ideally visual-based, to show this.**

---------------------------
## Background
As part of the PACT Act resiliency load testing activities, we want to ensure that non-critical endpoints can demonstrate readiness for up to a 10x spike in submissions between 9/20-9/30. 

- [Load Testing report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/engineering/Load%20Testing/10-10EZ%20Load%20Testing%20report.md)

**Comment by lihanli** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/de72aa36-c8ec-4281-9911-2882046acf61)
The load test ran successfully for 832 requests at a rate of 1.39 req/s. The one error in the results was not a real error, it was due to the login session expiring, when that happens in the browser the frontend automatically retries the request and the user doesn't experience any error occuring.

### cpu load
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/e0eb91cf-a63d-4bb7-85f6-32ce3ce13c94)

### latency
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/e1a1eea1-4b6e-4650-b649-23b78ed938cd)


### bytes sent
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/0127009f-c0a4-4313-a19d-c714172ee8ba)

### bytes received
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/830084/32e4a74e-82bd-443a-846b-9865920e8e93)

**Comment by hdjustice** [comment]
Thank you @lihanli !  This looks great.  Load Testing report has been updated with these results
