### ISSUE TITLE
Reorganization and Addition of Support Bot Fields

### ISSUE THREAD

**Issue by alyssagallion** [department-of-veterans-affairs/va.gov-team#65229]
## Description 
The purpose of this ticket is to update the order of the Support Bot fields to ensure a better UX for VFS teams. The proposed changes are: 

- Update Support Bot to offer List of 32 active Topics drop-down first
- The assignment feature should be removed (tickets should auto-assign to Tier 1 for triaging)
- Wherever possible/appropriate, the Assignment should be automatically selected by the Bot (Ex: selecting Topic EKS skips creating the Assignment field and automatically creates Slack ticket assigned to Back End)
- Where an Assignment choice is required from the requestor, Topic drop-down results in Assignment field with drop-down of 1-3 choices, requestor selects Assignment, Slack ticket is created (Ex: selecting Topic PR Review results in drop-down showing choices Front End and Back End)
- Keep the "Other" category and add a field for them to explain the category their issue is related to (this will help us shape future categories)
- Remove the link [Page not found · GitHub · GitHub from Assignment](https://github.com/department-of-veterans-affairs/platform-console-ui/blob/main/docs/getting-started/setting-up-the-platform-console-ui.md): Backend or Frontend > Topic: App Setup

---

## Definition of Done
The below tasks are accomplished.

---

## Tasks 

- [ ] TBD based on engineering scoping

--- 

## Resources & Additional Info 
_Links, screenshots, etc. go here_ 

---

**Comment by jknipes** [comment]
Adding detail to requested improvements: Every option should result in a GitHub ticket for tracking

**Comment by CBonade** [comment]
Current state of this in testing:

>Update Support Bot to offer List of 32 active Topics drop-down first

This is exactly what you'd expect. You type "/support" and a window pops up with only two fields - a dropdown for topic and a field for summary.

> The assignment feature should be removed (tickets should auto-assign to Tier 1 for triaging)
> Wherever possible/appropriate, the Assignment should be automatically selected by the Bot (Ex: selecting Topic EKS skips creating the Assignment field and automatically creates Slack ticket assigned to Back End)

These two were slightly conflicting. In order to give your team full control to do what you want, I made the decision to auto-assign to whatever the first team is that's assigned to that topic. For example:

App Setup as a topic has 4 teams assigned to it on the sheet - in order, they are: 1, 2, 3, and 11. In this case, an App setup ticket would be assigned to team 1 (frontend support, currently). In order to designate Tier 1 as the option, we'll need to go one of two ways:

1) Add a team for Tier 1 to the teams page and then add them where you want Tier 1 auto-assigned
2) Default to Tier 1 for any topics that have no team assigned

I believe option 1 would give your team the most control in this scenario, and is how I have it currently set up to work.

> Where an Assignment choice is required from the requestor, Topic drop-down results in Assignment field with drop-down of 1-3 choices, requestor selects Assignment, Slack ticket is created (Ex: selecting Topic PR Review results in drop-down showing choices Front End and Back End)

We've decided against this update currently as the request above to remove the assignment function is at odds with this one. If Tier 1 is triaging anyway, asking for users to input assignments for some things is only likely to have a Tier 1 have to reassign it after possibly tagging the wrong person. We believe the auto-assign is the more efficient, more reliable option here.

> Keep the "Other" category and add a field for them to explain the category their issue is related to (this will help us shape future categories)

An "Other" category can be added via the spreadsheet at any time. However, adding an additional field that only pops up if "Other" is selected is prohibitive to keeping the code flexible and in our opinion does not add much value that is not already provided by the "Summary" field, which will contain the nature of the issue. If "other" topics are going to have to be manually reviewed to see what topics can be added/updated in the future, that information should be in the summaries anyway.

Please let us know what you think! We're happy to discuss any of this if it's not exactly what you're hoping for. Note that all of these are in my testing Slack space only and no code has been pushed to GitHub yet nor deployed out to the actual support bot. Happy to screenshare any of these feature adjustments as well. Still have a little more testing to do to ensure the GitHub issues are being properly created, etc.

**Comment by jknipes** [comment]
Thanks @CBonade. The "Other" category is actually one of the available options for Assignment, not Topic.
Under Topics, the equivalent is "Something Else"
