### ISSUE TITLE
[SSO Launch] Unit Test Coverage of 90%

### ISSUE THREAD

**Issue by ambikaroos** [department-of-veterans-affairs/va.gov-team#6535]
VSP guidance: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/quality-assurance/unit-testing/README.md

- [ ] Confirm unit test coverage at 90%

**Comment by ericbuckley** [comment]
I spoked to Peter Hill about this requirement the other day and he gave me the following feedback.

>Hey Eric, I don't believe that VSP needs to review any specific artifact regarding unit test coverage.  Our documentation site calls out 75% coverage [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/983d84608cc0ca24350bdf8d9f1282e25a9d3cac/platform/engineering/frontend-testing-guidelines.md).  More detailed documentation for creating the unit tests is [here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/getting-started/common-tasks/new-unit-test).  I've never been a part of a unit test coverage review. Perhaps Jenkins is reporting the code coverage percentage somewhere?  I'll have a look around.

So it sounds like we don't have to produce any artificat/deliverable to show the 75% coverge.  So the goal should be that with each PR we complete that we're maintaining at least 75% unit test coverage with the feature we're introducing.

Since the 3 of us are already doing that, I think we can close this issue.
