### ISSUE TITLE
[SW] Discrepancies Identified by VHA

### ISSUE THREAD

**Issue by HeatherRienks** [department-of-veterans-affairs/va.gov-team#65409]
## Issue Description
Mike Dewey from VHA has requested we crunch the numbers on a couple of queries. 

1. Select all Form5655Submissions for VHA copays exceeding $5000 (`pHAmtDue ` is the copay object value that indicates this)
2. Select all Form5655Submissions which are longform streamlined.

---
## Tasks
- [ ] Collect Form5655Submissions ids that meet the above queries.

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by denisecoveyduc** [comment]
@kjsuarez  For what it is worth, my understanding was that if a Veteran selected a VHA debts over $5000 that they are going for manual review. That was discussed during the requirements and the FE team built that into the logic. I agree, validating that this is indeed happening is certainly needed. 

I also know there was that one 'long' form submission that was not captured in our analytics (I had heard because the Veteran opted out of analytics). When I last asked (5 days ago on slack - [here](https://dsva.slack.com/archives/CPE4AJ6Q0/p1694180829972149) there were no additional submissions. Again, good to validate!

**Comment by kjsuarez** [comment]
Results as of 09/14/2023:
Still only 1 longform SW thus far: `["3b40dd53-0450-4ee1-88b5-2df96f9bf1dc"]`
0 Streamlined Waivers with a copay over $5000
6 NON-Streamlined Waivers with a copay over $5000: 
```
["abe8a0f8-b233-4f66-b5e0-8238702b449a",
"2a1e5937-c139-40c1-8fdc-47c05d27cd03",
"6c4c5987-4e64-4654-a48b-1c3b6457d3bc",
"05f4a235-bf29-4121-b259-dc20e29a8337",
"e178d561-96d2-4730-9deb-433068f8daa0",
"bdd0ccea-6bc3-4fdb-9eb2-34471c61a11d"]
```
