### ISSUE TITLE
Spike: Document upload failure for pdfs with new encryption standard

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#65483]
Summarized from conversation from Jerek Shoemaker: 

'We are using a gem called pdftk to decrypt pdfs (we get a password protected PDF from the veteran along with the password, then we create a non-password protected version of that PDF to pass to downstream systems). It does not support new encryption methods (AES256, which from what I understand was introduced as an extension to PDF 1.7) and we see errors sometimes related to this:

http://sentry.vfs.va.gov/organizations/vsp/issues/95118/?environment=production&project=3&query=is%3Aunresolved+encryption&statsPeriod=14d

Unfortunately we are using the latest version of the gem and there is a good chance that the only real path to resolution is to find a new gem to do the decrypting'

Screenshots from Sentry:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa084IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7a20bd7b3e60aa7f965c092330b4eaed73a090e2/PDF%20Encryption%20Error%201.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1M4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a0f952bed4b93cbd3b40300004df7a2b3659efe9/PDF%20Encryption%20Error%202.png)

Additional info:

https://gitlab.com/pdftk-java/pdftk/-/issues/87

**Comment by austinjprice** [comment]
Is there a new gem or update that can handle new encryption and is there any complication with adding new gem?

**Comment by freeheeling** [comment]
@austinjprice – It doesn't appear that the [pdftk](https://github.com/konrad-glowacki/pdftk) gem is being used. Instead, the [pdf-forms](https://github.com/jkraemer/pdf-forms) gem that is installed works in conjunction with [PDFtk Server](https://www.pdflabs.com/tools/pdftk-server/) to decrypt up to 128-bit strength encryption. According to the [PDFtk Server Examples](https://www.pdflabs.com/docs/pdftk-cli-examples/), using a provided password should open a 128-bit strength encrypted PDF. 

We are currently running version 1.3.0 of pdf-forms. As of 09-15-2023, the most recent version is 1.5.0, but none of the updates since 1.3.0 seem to address any issues related to PDF encryption state. Decryption is handled by PDFtk Server, the last version update being 07-24-2013. [A user guide](https://pdftk-builder-enhanced.sourceforge.io/PdftkBuilder.pdf) from 05-28-2021 notes that support for 128-bit AES (PDF 1.6) decryption was added in PDFtk Server v2.00 in May 2013, but 256-bit AES (PDF 1.7 Extension Level 3 and PDF 2.0) is not
supported.

Noteworthy, is that errors I am encountering when testing locally reference an incorrect password and not an unknown AES256 encryption type associated with later PDF versions mentioned in the issue description, although encryption level seems to be the consensus from my research. In fact, my attempt to unlock a password-protected version 1.4 PDF was unsuccessful, whereas I could unlock a password-protected version 1.6 PDF. It is possible that stronger-level encryption may likely have been the blocker, but I'm not certain how to determine a PDF's encryption level without a tool like Adobe Reader.

Following are alternatives to the current methods and tools being used to decrypt password-protected PDFs:
- In the linked [GitLab issue](https://gitlab.com/pdftk-java/pdftk/-/issues/87), a user commented that they had used [qpdf](http://qpdf.sourceforge.net/files/qpdf-manual.html) to decrypt a pdf and then processed it with pdftk. This option is further advocated for in [this article](https://zhauniarovich.com/post/2019/2019-06-using-pdftk/#:~:text=use%20qpdf%20to%20protect%20your%20document).
- [ConvertAPI](https://www.convertapi.com/pdf-to-decrypt#snippet=ruby) provides a paid option with [pricing plans](https://www.convertapi.com/a/plans) starting at $0.05 per conversion. 

If we were to switch to a different tool or process for decrypting password-protected PDFs, those models currently dependent on the tooling provided by PDFtk that would require an update include:
- `EVSSClaimDocument`
- `FormAttachment`
- `LighthouseDocument`

**Comment by jerekshoe** [comment]
Yeah when I started looking into this issue I was leaning towards the approach of leveraging qpdf somehow to decrypt the files. That would probably be the best approach to move on, even if that means utilizing qpdf alongside pdftk instead of treating qpdf as a replacement to pdftk

**Comment by sortizsh** [comment]
this ticket needs additional discussion based on the work scott did above.

**Comment by sortizsh** [comment]
@tblackwe can you figure out our next steps for this

**Comment by lisacapaccioli** [comment]
@tblackwe This opened last year and it looks like the discovery was done, but not sure if any work was 1) planned and 2) delivered. What do you want to do with this ticket?

**Comment by tblackwe** [comment]
😬 We landed on this being a platform issue. Closing this out.
