### ISSUE TITLE
Investigate crashing runners

### ISSUE THREAD

**Issue by JoeTice** [department-of-veterans-affairs/va.gov-team#65485]

**Comment by CBonade** [comment]
This appears to be due to the runners running out of memory. I have been able to circumvent this issue by parallelizing the stress test to avoid taxing any one runner too much. This comes with the added bonus of the stress test running in less than 20 minutes, instead of taking hours. Turned out to be a great thing to have to work around.

Being that this fix took place on the unit test branch that has all the upcoming changes on it, i'm going to make sure it's solidified before copying it over to a new branch and running with it. That said, the principal work for this ticket is done and just awaiting being ready to merge it in.

**Comment by CBonade** [comment]
This is all set and merged.
