### ISSUE TITLE
[Spike] Intent To File behavior when a back-end service is unavailable

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#65481]
I (Steve Albers) want to check in with you on the current Intent To File behavior when a back-end service is unavailable.  I'm looking at the 7 PM - 11 PM ET 9/9 outage/degradation in service caused by an unavailable back-end service - it caused a number of ITF errors - can we talk about this during the next bug triage meeting?  (link for start of Slack channel notifications)

Slack thread - https://dsva.slack.com/archives/C04KW0B46N5/p1694440762541849

Acceptance Criteria:

- [ ] Investigate current behavior and propose potential technical solutions for allowing users to continue with 526 application when ITF service is not available.

**Comment by austinjprice** [comment]
Two take aways: what are expectations on ITF type errors / problems? All ITFs get processed? Some are blocked?

For this one in particular : what is the current behavior?

**Comment by SamStuckey** [comment]
Considering this temporarily blocked until I better understand the desired outcome.  [Slack thread for context](https://dsva.slack.com/archives/C04KW0B46N5/p1695064685597689?thread_ts=1694440762.541849&cid=C04KW0B46N5).  TL;DR - 

- ITF must be a synchronous call, due to the possibility of incorrectly dated ITFs affecting payment
- ITFs must be present / created at the time a vet starts an application
- If the ITF endpoint is down, we should (can) not allow the user to continue

Since the cause of this failure was a maintenance window in a downstream service, there is no bug to investigate.  However, we could do a few things
- add alerting around this (WIP)
- improve Vet facing error messaging.  

Not sure if there is much else to do?

**Comment by austinjprice** [comment]
Per discussion in Slack - Sam will be investigating what it would take, technically, to bypass ITF when service is down and backfill date when available. Once his investigation is complete we will review with OCTO and UX to determine best user experience and then do estimation.
