### ISSUE TITLE
Consolidate CTA widgets Authenticated Appointments page

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#6560]
## User story
Currently there are two widgets on the page and we need to consolidate them into a single "sign in to schedule or view a VA appointment online" message on the unauthenticated and authenticated pages. We need to do this for VAOS full launch phased rollout (https://www.va.gov/health-care/schedule-view-va-appointments/)

I/A review captured in this ticket:
https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/3152

## Acceptance Criteria
- [ ] Authenticated page: update react widget and message into single "Sign in to view, schedule, or cancel a VA appointment online for page flow into VAOS 
- [ ] Authenticated page: update react widget and message into single "Sign in to view, schedule, or cancel a VA appointment online for page flow into MHV 
- [ ]  Updated widgets have been implemented by VAOS FE engineers

**Comment by peggygannon** [comment]
@lalexanderson-dsva @lenaecb @rtwell @jbalboni 

Please see below content recommendations for the consolidated sign-in widgets for Authenticated Appointments page. Let me know if you have any feedback or questions. 

1. Authenticated page - Auth page flow into VAOS

**View, schedule, or cancel a VA appointment online**
{begin alert box}
**Go to the VA appointments tool to  view, schedule, or cancel your appointment online**
You'll be able to manage and see all your appointments in one place on VA.gov. You can also schedule or cancel some VA and Community Care appointments online.

{button} Go to your VA appointments(https://www.va.gov/health-care/schedule-view-va-appointments/)
{end alert box}


------

2. Authenticated page – Auth page flow into MHV

**View, schedule, or cancel a VA appointment online**
{begin alert box}
**Go to My HealtheVet to view, schedule, or cancel your appointment online **
You may need to sign in on MyHealtheVet. If you do, sign in with the same account you used to sign in on VA.gov. You also may need to disable your browser’s pop-up blocker so that My HealtheVet will open. 

{button} Go to My HealtheVet(https://veteran.mobile.va.gov/var/v4/)

{end alert box}

**Comment by lenaecb** [comment]
Just to a a note here, the current flow (with 2 widgets) has you going to 2 different locations - for 'view VA Appts' you go to the MHV appointments list/page on MHV, and for 'Schedule or Cancel' you go to a MHV page that has a button that sends you to legacy VAOS tool.

Here we are taking away both of those pathways in favor of a single pathway straight to the VAOS tool from the static content page. If you are instead one of the 'opt-in' users, you will see Peggy's Option 1 - Authenticated user widget CTA.

I want to make sure we had that context.

**Comment by lalexanderson-dsva** [comment]
Everything is right but the URL in 2. we want to send users to the MHV view appointments page (https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/appointments) not (https://veteran.mobile.va.gov/var/v4/). 

The reason:

Cutting from two sign-in alerts to one meant we had to pick one of the two routes to view and make appointments for legacy VAOS. As a reminder the old routes were:  
1. = link to MHV View appointments (https://www.myhealth.va.gov/mhv-portal-web/web/myhealthevet/appointments); 
2. = link to the MHV path that takes a user to the legacy tool (mobile.va.gov/var/v4.)

The first path has a clearly defined and tested route to get users into the scheduling app; the second path doesn't have a clearly defined and tested path to get users back to being able to view their appointments (particularly past appointments) on MHV. Since we currently do NOT have past appointment functionality in new VAOS, I chose to send them to MHV so they would get their past appointments AND STILL be able to get into legacy VAOS through a tested route. (edited)

**Comment by peggygannon** [comment]
Thanks, @lalexanderson-dsva and @lenaecb I've updated that 2nd URL in my message above^^

**Comment by jbalboni** [comment]
One thing, whomever makes this change in Drupal is going to have to pick which CTA widget id to keep. Either `schedule-appointments` or `view-appointments`. The latter points to the url we're going to use going forward, but it doesn't matter all that much which one is picked because we're updating the React code either way.

But someone needs to let me know which one we're keeping.

**Comment by peggygannon** [comment]
Thanks, @jbalboni for this guidance. I'll be one updating the actual drupal page (pulling in the new, consolidated widget alert). I'll be sure to coordinate with @kelsonic.
