### ISSUE TITLE
draft shared network diagram

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#65612]
AC
- displays VA.gov env and the systems it connects to
- research, ask Core and search Github to see if there's existing diagrams 
- modify as it relates to IPP as needed

DEF OF DONE
- draft doc that can be shared

**Comment by sdickson-gt** [comment]
There are various diagrams in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive under engineering and ATO folders

**Comment by rdvyas** [comment]
@sdickson-gt - Thank you for sharing that valuable section of GH. I was able to find some very interesting documents, including some interesting documents specifically related to login process noted below. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2JvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--32fee585b32e89f0da1f87bf5c0d32131c5efcda/Screenshot%202023-09-25%20at%2011.16.36%20AM.png)

At this time we can close this ticket since we have a draft topology diagram that we are working on located in the following Mural workspace. We will continue to update this document as new developments/data are presented to us. 

https://app.mural.co/t/devteam6365/m/devteam6365/1695049051626/482066a4aecb25e55fac1cbd095501bc893c1e91?sender=ubaed9022e894858e004b6707
