### ISSUE TITLE
Design Intent - Design Feedback - Appointments FE Team Appointment Details Redesign

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#65837]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- This is looking great! Thank you for the user flows and new vs old, it is very helpful!
- Matt Dingee: There is a bit of concern around dropping the status alert banners. Canceled would be the one I am most concerned about because it seems like the Veteran might want to take an action. You could make a case that the others are a status and not an alert.
- Matt Dingee: The primary action is clear for join appointment. Could we identify a primary action for some of these other ones. Eg when it is advance something like prepare for visit. It does seem like we want them to do some things but it isn't necessary clear what. Should after visit summary be a primary action?

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

-

**Comment by outerpress** [comment]
Hi @allison0034 @Cieramaddox , I was cleaning up old tickets and found this one from the details redesign that was lost in the shuffle. I'm hoping you can help me sort out if we've resolved this or not. The current details pages are documented [here](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1150-105402).

> There is a bit of concern around dropping the status alert banners.

We ended up keeping most of the alert banners, including canceled. We removed the banners on "Past" but the page heading includes the status. So I think this is resolved. Thoughts?

> Could we identify a primary action for some of these other [appointment types]

If you see any actions that you think should be primary, let's discuss. This'll be an ongoing topic as we add features like travel pay, which will live with AVS on past appt pages. To start we're framing our thinking around which actions 'should not' be primary because we can't say for sure it would be the user's priority to click that (like canceling or adding to calendar). 

Thanks!

**Comment by allison0034** [comment]
Oh lawd... this was over a year ago so I do not remember the conversation.

> We ended up keeping most of the alert banners, including canceled. We removed the banners on "Past" but the page heading includes the status. So I think this is resolved. Thoughts?

That works!

As far as the primary action links, since you are adding features I would def consider how users would scan this page and could easily see the happy path. I agree canceling and adding to calendar would likely not need to be a primary action link.

**Comment by outerpress** [comment]
Okay sounds good! We'll definitely look at link hierarchy as we add new features to the details pages. I'm going to close this one out - thank you!
