### ISSUE TITLE
[Claim Status Tool] Address LH Timeout Issues

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#66098]
We are currently getting many noisy alerts from our CST monitors. In an effort to improve the signal-to-noise ratio of our alerts, we need to solve the underlying problems in CST.

Lighthouse times out after 10 seconds, which is often sooner than the claims status tool or upstream dependencies do. We need to work with Lighthouse and Steve Albers to reduce the number of timeout errors we're alerted to.

Solution inspiration:
- Change monitor parameters (threshold, window, etc) (bandaid?)
- Work w/ LH to increase timeout duration (difficult?)

Done when:
- [ ] Identify potential issues causing errors and elevate them to LH

**Comment by va-albers** [comment]
[Recent thread noting this issue](https://lighthouseva.slack.com/archives/C01B0M3M85B/p1695055745961469)
- on 9/21/2023 Michael Harlow noted that "You should not be seeing any 504s after 10:46 ET because the platform team increased the node count to prevent scaling which appears to be the root cause.", but Beau Grantham wrote "I don’t think this is a permanent fix - it was an attempt to isolate the root problem - but do keep an eye on it" (both from the same Slack thread)
