### ISSUE TITLE
Dynamically remove pods for vets-api based on backlog

### ISSUE THREAD

**Issue by rmtolmach** [department-of-veterans-affairs/va.gov-team#66255]
Follow up on https://github.com/department-of-veterans-affairs/va.gov-team/issues/49794 to see if the work done there is working as expected. Fix and re-enable readiness.sh.

**Updated ticket on 4/8/2024:**
When 30% of our threads are in use, it triggers a scale of the pods. We need to do discovery on this, because it doesn't make sense to have 70% availability and there is still a backlog. It can be optimized by using Traefik to allow the use of more bulkheads. An upgrade was just done in January, and we are still having backlog issues.

We need to look into:
- [ ] HPA
- [ ] Dashboard bulkheads
- [ ] Errors
- [ ] Traefik routing (and round robin)
- [ ] When we scale, how long do we have before we can scale again
- [ ] Does a puma backlog only happen during bursts of traffic

**Comment by LindseySaari** [comment]
We may want to look into uneven request load. I believe that traefik does round robin routing but some requests may be more latent or resource intensive than other requests, leading to uneven load and backlogs. It may be worth potentially looking into readiness probes. If the pods threads are all in use, we could prevent requests from being sent to pods under heavy load. Another suggestion is potentially a middleware of sorts that route based on pod health/threads in use. 

Also, we could potentially identify some more of these resource intensive or latent requests and their endpoints and isolate them into a bulkhead

**Comment by LindseySaari** [comment]
Some things that could potentially contribute to the puma backlog
1. Sudden spikes in traffic - the demand may outpace the rate at which free threads are available and additionally for HPA to catch up since we have an initialDelay of 30 seconds
2. The initialDelaySeconds: 30 means each newly created pod won't start accepting traffic until at least 30 seconds after it's been started.
3. Even with round-robin load balancing, not all requests are equal. Some might require significantly more processing time than others. This can lead to situations where pods get backed up processing a few resource-intensive requests even if they're under the threshold for scaling. Do we need some more bulkheads? Could we consider some advanced load balancing strategies? 
4.

**Comment by LindseySaari** [comment]
Some things that could potentially contribute to the puma backlog
1. Sudden spikes in traffic - the demand may outpace the rate at which free threads are available and additionally for HPA to catch up since we have an initialDelay of 30 seconds
2. The initialDelaySeconds: 30 means each newly created pod won't start accepting traffic until at least 30 seconds after it's been started.
3. Even with round-robin load balancing, not all requests are equal. Some might require significantly more processing time than others. This can lead to situations where pods get backed up processing a few resource-intensive requests even if they're under the threshold for scaling. Do we need some more bulkheads? Could we consider some advanced load balancing strategies? 
4.

**Comment by rmtolmach** [comment]
> Follow up on https://github.com/department-of-veterans-affairs/va.gov-team/issues/49794 to see if the work done there is working as expected. Fix and re-enable readiness.sh.

I see readiness.sh mounted at `/app/bin/readiness.sh` in prod and sandbox. But It doesn't look like it's actually being called anywhere (I'm looking for something like `command: ["app/bin/readiness.sh"]`) so it looks like the work is not done from that ticket (🤔 if I'm understanding it correctly).

I'm unclear what exactly the tasks are for this ticket. It seems to overlap with https://github.com/department-of-veterans-affairs/va.gov-team/issues/72438. I will follow up with @LindseySaari tomorrow to clarify.

**Comment by rmtolmach** [comment]
Lindsey informed me we do use the [readiness probe here](https://github.com/department-of-veterans-affairs/vets-api/blob/parent-helm-charts/chart/templates/server-deployment.yaml#L87-L97) by calling the /v0/healthcheck endpoint ([config here](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vets-api/prod/values.yaml#L53-L59)). So I think the custom script in readiness.sh is not used, which is fine because we use `readinessProbe`.

**Comment by rmtolmach** [comment]
- I opened https://github.com/department-of-veterans-affairs/va.gov-team/issues/83694
