### ISSUE TITLE
[Discovery] Data availability from Grafana

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#666]
## User Story
As a product decision maker, I need data reflecting my product's system health so I can understand my product's health.

## Goal
Meet with system SMEs and discover how the tools work and what data can be retrieved from those products.

## Acceptance Criteria
- [x] Set up meeting with SME
- [x] Meet with SME
- [ ] Document how the product functions (where the data comes from, how it's recorded, any available APIs, etc.)
- [ ] Document relevant data points

## Definition of Done
- [ ] **Attached to a Milestone**
- [ ] **Attached to an Epic** 
- [ ] **Labeled with Team** 
- [ ] **Labeled with Practice Area**
- [ ] **Labeled with Type**

**Comment by amycesal** [comment]
### Discovery Questions (ongoing):

- What data is collected in Grafana?
- How often is it updated?
- Who owns the data?
- Who can access the data?
- Where does each data source live?
- What do the outputs look like?
- Where is the data stored? How do we get access to it?

**Comment by joanneesteban** [comment]
Meeting recording with Wyatt: https://zoom.us/recording/play/Wieztfz1sVRZ5ceUSA6YmWIbAV7aDH8kCc4k_5f8c_k3nYtI8riQuJfU0RdnUhBj?continueMode=true

**Comment by amycesal** [comment]
> system and application metrics are collected and stored in Prometheus 
> cloudwatch, metrics that aren't queried directly, like databases

What data is collected?
> can get data from many sources and aggregate together,
systems level metrics about servers, latency for services, status codes, error rates, measure things that operationally that's being debugged. 

How often is it updated?
> when we pull 

Who can access the data?
> anyone with VA network and SOX proxy. 

Where does each data source live?
> prometheus or grafana api


- data around what backends we interact with are doing (circut breakers in the API) 
- amount of requests that were skipped because the service was down
