### ISSUE TITLE
discovery on login.gov integration

### ISSUE THREAD

**Issue by djmunoz1** [department-of-veterans-affairs/va.gov-team#66633]
As a developer I need to understand how to connect to login.gov so that I can integrate their sandbox env with the IPP app.

**ACCEPTANCE CRITERIA:**
- Learn about the process the user will go through to access your application and what steps are involved in configuring your app on the Integration page.
- Determine your application needs (e.g. level of proofing, requested attributes)
- Select between Open ID Connect (OIDC) or SAML implementation protocols

**DEF OF DONE:**
- [ ] document decisions based on AC and store in GH

**Comment by rdvyas** [comment]
After a couple of Tech Meeting and research within the Login.gov developer portal we were able to determine the following:

Learn about the process the user will go through to access your application and what steps are involved in configuring your app on the Integration page.
- We will be able to piggyback on the IdP integration that already exists between VA.gov and Login.gov. Essentially we needed a way to access User Locator data (UUID, email, encryption key), we will be able to pull that data with the IdP integration that already exists between VA.gov and Login.gov

Determine your application needs (e.g. level of proofing, requested attributes)
- During the authentication process Login.gov will send over specific user information depending on whether that user account is in IAL2 or not. Since the IPP process will get the accounts into an IAL2 status, we can assume that when a user account logs in after IPP that Login.gov will return IAL2 related data when we login. This is usefuel when testing as we will need to correctly identify when an account is in IAL2 status, more info below:
https://developers.login.gov/attributes/

- Select between Open ID Connect (OIDC) or SAML implementation protocols
Based on our research either is a viable option since currently VA.gov uses both of these protocols in the application. Our team is leaning toward OIDC since its a newer and more modular protocol. 

Closing this ticket as resolved based on research data above.
