### ISSUE TITLE
Research ITF date for Pension

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#66958]
## Issue Description

Veteran perspective:

As a veteran filling our the Pension claim form,
I want to make sure that the online form is capturing my Intent to File (ITF) when I first start the form (and not when I submit),
So that when my benefits are awarded, they can backdate them to this date and my claim can be processed as fairly as possible.

Team perspective:

As a new Pension team,
we need to understand how to set up an Intent to File (ITF) date to the VBA,
so that veterans can have their benefits backdated to the date when they first started to fill out to the form (and saved) without having to finish it.

As a new Pension team,
we need to understand if we can change the ITF date from the `submission_date` to the `creation_date` ASAP,
so that veterans can have their benefits backdated to the date when they first started to fill out to the form (and saved) without having to finish it.

How might we start transitioning the Pension form's ITF date captured from "submission" to "create"?
 
---
## Tasks
- [x] Research if there is an existing mechanism for providing the specific ITF date to VBA, and if not, what it would take to build one.
- [x] Research whether and how we can submit a `create date` rather than `submit date` as part of the new form

## Artifacts

_- Link to any artifacts gathered or created_

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/66958?planning-poker) with Zenhub @mjknight50 @TaiWilkin @ToddWebDev

**Comment by danlim715** [comment]
It looks like there already exists a mechanism to fetch existing ITFs as well as create new ITFs. However, ITF info isn't stored in our system, so it invokes either Lighthouse or EVSS APIs to fetch or create. There is a ClaimsApi::IntentToFile table in our system database, but it looks like it's only used for reporting purposes to track the daily success/failure number of ITFs submitted to the BGS. We don't have any routes or endpoints for modifying an existing ITF, but we can view a list of all past ITFs so we may be able to track down the ITF date when the claim was first created. Also, I'm unsure if attempting to create a new ITF when there's currently an active ITF will auto deprecate the old one, or if it'll just error out. Seems like it might error out, since I see some logic in our application with conditionals stating things like "if there is no active ITF and  createITF hasn't already been called, submit a new ITF". For our new form, we should have the ability to use the create date instead of the submit date when creating a new ITF, but might be a bit tricky to consistently figure out the "create date" for veterans who have already filed a claim to try and backdate their benefits.

**Comment by vbellissimo** [comment]
Closing and created #68346 as a next step.
