### ISSUE TITLE
BE | Profile | Military Info | Staging Data for Military Info

### ISSUE THREAD

**Issue by tpharrison** [department-of-veterans-affairs/va.gov-team#67101]
## Background
The VA.gov Authenticated Experience team is looking to add realistic military data to users in our staging environment (VA Profile's QA environment). This will enable researchers to gain a more accurate preview of how the data will appear in production.

## Tasks
- [ ] Reach out to VA Pro support to request that multiple users have military unit assignment data assigned.

## Acceptance Criteria
- [ ] Verify that staging users have realistic data assigned.

**Comment by tpharrison** [comment]
Email message was rejected...
>  The following message to <[vaprotestsupport@va.gov](mailto:vaprotestsupport@va.gov)> was undeliverable. Recipient address rejected.

Reached out to Michael Richard to ask for another email address.  Waiting to hear back...

**Comment by tpharrison** [comment]
Haven't heard anything back.  Reached out to Jay Krishnappa baed on Micheal Richards suggestion.

**Comment by mtcA6** [comment]
@tpharrison on this ticket, want to check my understanding. We're stuck unless we submit a request with the data we're looking for? In other words, there isn't great mock data for most of the military data endpoints.  

Why I'm asking, on the [mural board ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697125319596/c13810c02c96a58a4b6b72288c6b9a8d617f711a?wid=0-1698676937725) Liz posted a question about being able to get realistic data. It seems like the rough answer to that question is "No we don't have realistic data" and any data we might need would likely need to be mocked up (which doesn't make me feel too terribly confident anyway). 

If you agree with that statement, let me know and I'll post a comment on Liz's mural board linking back here.

**Comment by mtcA6** [comment]
@tpharrison thanks for the details. My gut says we shouldn't spend too much time working on getting specific and detailed mock data and instead can make use of the data dictionary/schema for those fields that aren't lookups to understand any potential UX/UI impacts and we should review this work sooner in production rather than later. 

I did just ask a clarifying question though, because Mike mentioned the VADIR team owns that list of Units but didn't specify who the contacts are. I don't want to assume the access question where he listed a few names are the same folks who would be able to get us the extract of the units. Unless you already know those contacts it may be worth it to reach out and attempt to get an extract. (I can own this) 

Some stream of consciousness thoughts here.... If we get an extract of the current data, understanding that it could change frequently, it may not be helpful, we really should hue to whatever constraints are provided in the data dictionary looking at the max and min values supported. 

@Samara-Strauss what are your thoughts? 

cc: @andaleliz

**Comment by Samara-Strauss** [comment]
Re: the meeting we just had -- it sounds like our current approach is to try to get access to realistic production data, which we can then use to inform mock data (likely by using the shell of a structure and then updating to obscure anything sensitive. Think changing dates and the like.) I am OK with the approach we just discussed. The more realistic the data, the better we can build something usable and scalable.

**Comment by tpharrison** [comment]
@mtcA6 Should we close out this ticket since we are going to be looking at production data?

**Comment by mtcA6** [comment]
Sure, that works. If we end up needing to seed better staging data we can do that w/a different ticket.
