### ISSUE TITLE
Provide Feedback for Onboarding project

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#67202]
Identity - Backend Onboarding Project 

Feedback Questions

Overall, do you feel that this project accomplished the intended goals of onboarding? (Learning about modern authentication concepts, understanding the developer pipeline, preparing you for technical contributions, keeping you engaged while waiting for permissions)
Was this project appropriate for your level of experience? Would it be appropriate for someone with less experience? More?
Do you have any ideas to improve the onboarding project, or even onboarding in general?

Open Feedback

**Comment by dickdavis** [comment]
*Overall, do you feel that this project accomplished the intended goals of onboarding?*

*Learning about modern authentication concepts*
Absolutely. By digging through the OAuth RFCs and implementing the requirements from scratch, I gained a deep understanding of authorization as well as the appropriate use of JWTs. Contrasting what I learned in the project with the specifics of how `vets-api` implements OAuth will be much easier with this base level of understanding.

*Understanding the developer pipeline*
I am already familiar with how changes are introduced to the codebase through tickets/code reviews/testing, etc., but it was helpful to get an idea of how the individual team members approach the process, particularly code reviews.

*Preparing you for technical contributions*
I feel much more confident in being able to understand `vets-api`'s OAuth implementation and make changes, fix bugs, etc. It would have been significantly more difficult without the base-level of understanding this project afforded me.

*Keeping you engaged while waiting for permissions*
Absolutely. I stayed engaged on this project and don't want to call it quits yet! It was a fun project to work on, and I think there are definitely some improvements I could make to my solution over time.

*Was this project appropriate for your level of experience? Would it be appropriate for someone with less experience? More?*
This project was perfect for my level of experience (mid-senior level), though it might be challenging for someone with less experience. This isn't necessarily a bad thing, but we can do a few things to make it more straightforward. I'm the kind of guy who enjoys reading specs, but others might have some challenges with that. I have included some suggestions below which may help improve the experience the next new team member has when working through the project.

*Do you have any ideas to improve the onboarding project, or even onboarding in general?*
I think the biggest improvement to the onboarding project would be to create a project skeleton that a new team member can fork and work on. The project skeleton should contain a README with setup instructions and the project requirements.

Additionally, it should have a docs/ folder that contains sequence diagrams and other relevant details about the specific processes associated with the OAuth flow. This additional documentation will supplement what the new team member reads in the OAuth RFCs.

A PR template and some actions for testing and code quality will also be helpful, especially to reviewers.

The skeleton should also have user authentication already implemented so the new team member can focus on implementing the OAuth requirements. This suggestion is optional; it may make sense to have them build authentication from scratch as well to improve their understanding of how that works.

We can provide some Postman scripts that will be useful for them in testing their progress, and helpful to us as we review/test their work.

On the process side, we could get better about how quickly we give code reviews. The onboarding project PRs always took a back seat to real work, so I ended up branching off branches of branches at some points just to keep it moving. I think it would make sense to assign a rotating onboarding partner who is responsible for ensuring PRs are reviewed quickly. This onboarding partner would also be available for questions/comments/concerns and help them get past any blockers they might have with the project. They could also serve as a guide of sorts for the overall onboarding process. We could assign the latest person to go through onboarding as the onboarding partner, which would take care of rotation and ensure that person is familiar with any recent changes to onboarding since it will be fresh in their minds.
