### ISSUE TITLE
Redis Update Assessment

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#67419]
**Problem Statement**
Our current development environment relies on Redis in Amazon Elasticache, specifically version 3. However, this version has become outdated and poses potential security and performance risks. To ensure the continued reliability and security of our development environment, we need to upgrade our Redis instance to version 6.2 or a higher compatible version.

**Action Items**
Conduct a thorough assessment of the existing Redis configuration and dependencies within our development environment.

**Comment by laineymajor** [comment]
We are upgrading (hopefully) a shorter/simpler upgrade path! Fingers crossed. Chris continuing to research.

**Comment by flooose** [comment]
The update to redis 6 or 7 (see below) should be relatively
straight-forward because [backward compatibility has always been a
design principle of the Redis project](https://redis.com/blog/redis-7-generally-available/). The following points need to
be addressed before moving to the actual upgrade.


<a id="org8db8228"></a>

# their stuff

-   [ ] do we need to do an incremental update or is jump to 7.x fine
    -   advantages of incremental
        1.  we get two versions with which to test automation
    -   advantages of direct jump
        1.  we're done with one go
    -   [ ] is direct upgrade even an option?
        -   I suspect, yes
-   [ ] how do we upgrade with terraform?
    -   we should be able to test this locally with `terraform plan`
-   [ ] Since this is a managed redis instance, the only redis config we
    should have to validate is `redis.yml` in the vets-api repo. @LindseyHattamer do you see this the same way?
-   [ ] Assess ssm for back-ups

**Comment by flooose** [comment]
This is the documentation https://vfs.atlassian.net/wiki/spaces/TT1/pages/2806808593/Redis+Update

**Comment by laineymajor** [comment]
Seems like this can be closed since we have the proper documentation... correct @flooose ?

**Comment by flooose** [comment]
I'm of the opinion that it can be closed. Is it worth getting a second developer opinion on this though? Maybe there's something I failed to consider? @Kshitiz-devops or @LindseySaari maybe?

**Comment by laineymajor** [comment]
duplicate https://app.zenhub.com/workspaces/platform-product-team-633af4074573d06c3cda142a/issues/gh/department-of-veterans-affairs/va.gov-team/53708
