### ISSUE TITLE
Draft screener questions for IPP Pilot Usability Test Proofing Agents

### ISSUE THREAD

**Issue by SophiaPhilipMO** [department-of-veterans-affairs/va.gov-team#67578]

**Comment by skirkman16** [comment]
I think this is getting at what we want to know and I have started to tie this in with the recruitment criteria. I think with this scale it's hard to know how often is often because we are unaware of how identity verifier roles vary. I also want to screen their comfort with the toolkit so I might ask the following questions:
Are you trained to use the Identity Management Toolkit?
	Yes
	No (end screening if “No” is selected, immediate disqualification)
2. Are you with using the Identity Management Toolkit for complete a proofing task?
	Yes
	No (end screening if “No” is selected, immediate disqualification)
3. How often do you use the Identity Management Toolkit to open a proofing task?
Daily
Weekly
Monthly
Never (end screening if “Monthly” or "Never" is selected, immediate disqualification)
4. What VA facility do you work in? (Consider just having them select which state they live in)
Drop down menu
Allow for multiple selections

**Comment by skirkman16** [comment]
Update: 
1. Are you trained to use the Identity Management Toolkit?
Yes
No (end screening if “No” is selected, immediate disqualification)


2. On a scale of 1-5, with 1 being uncomfortable and 5 being an expert, how comfortable are you with using the Identity Management Toolkit for complete a proofing task?  [1, 2, 3, 4, 5] (For 3 or below, immediate disqualification)


3. How often do you use the Identity Management Toolkit to open a proofing task?
Daily
Weekly
Monthly
Never (end screening if “Monthly” or "Never" is selected, immediate disqualification)
4. What VA facility do you work in? (Consider just having them select which state they live in)
Drop down menu
Allow for multiple selections

**Comment by SophiaPhilipMO** [comment]
Screener Questions

Are you trained to use the Identity Management Toolkit?
	Yes
	No (end screening if “No” is selected, immediate disqualification)
2. Please indicate your level of confidence in using the Identity Management Toolkit to complete a proofing task by selecting the option that best represents your feelings. (End screening if response is 3 or below)
Scale:
1 = Not at all confident
2 = Slightly confident
3 = Moderately confident
4 = Very confident
5 = Extremely confident


How often do you use the Identity Management Toolkit to open a proofing task?
	Daily
	Weekly
	Monthly
	Never (end screening if “Monthly” or "Never" is selected, immediate disqualification)
What VA facility do you work in? (Consider just having them select which state they live in)
	Drop down menu
Allow for multiple selections
Confirm with Perigean and OCTO if we can ask for more details on their work location

**Comment by SophiaPhilipMO** [comment]
@lmorris3 @porta-antiporta please review screener questions for Veterans in the usability test posted on 10/20/23 in the comments
