### ISSUE TITLE
Midpoint Review - Design Feedback - Accredited Representation Management

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#67699]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Welcome Michael!
- We have noticed alert fatigue on VA so make sure you are only using alerts when it falls in the guidelines.
- We are slowly moving to the USWDS. If you see a v3 component that is the current USWDS component, I would recommend using those if possible.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: The prototype has a new alert style we currently do not have in the Design System for sign in. You can see the current styling in the [Sketch intro template](https://www.sketch.com/s/dc844743-277e-41d4-81ba-a48fd0743952/p/D1B466E9-348C-4C47-BC86-CC9B46A3B0D9/canvas) and [Design System introduction page](https://design.va.gov/templates/forms/introduction). Change your alert styling to match the info alert (either [v1](https://design.va.gov/components/alert#sign-in-to-start-your-application---no-pre-fill) or [v3](https://design.va.gov/components/alert#examples---v3), we will move to v3 at some point so that may be the better option).
- <img width="634" alt="Screen Shot 2023-10-16 at 3 23 51 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/04a308a6-9ffc-47b5-86bc-72df64cb12aa">

- **Must**: According to our guidelines for additional info components, you should not try to put multiple paragraphs inside Additional info. Instead link to another page, consider an [Accordion](https://design.va.gov/components/accordion), or shorten the content. There are 2 instances where the additional info components have too much content. The first is in the process list. Either use accordions or create a page before this similar to the [how to apply pattern](https://design.va.gov/templates/forms/how-to-apply) and move that content into that page.  The second is what is my representative type. You could use accordions instead.
- **Must**: Remove the new alert styling on the "Your current representative" as it is not currently in the Design System and this is not an alert. Instead you could use one of our [card style options](https://design.va.gov/components/card) if you prefer.
- <img width="660" alt="Screen Shot 2023-10-16 at 2 36 35 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/a2ef834e-4992-4b15-96b0-888f3fbd9a32">
- **Must**: There is a slim alert for "Keep in mind...". This current use case does not meet the [slim alert guidelines](https://design.va.gov/components/alert#when-to-use-a-slim-alert), instead use a [standard alert](https://design.va.gov/components/alert#examples---v3). Also, review the [guidance for placement](https://design.va.gov/components/alert#placement) and move closer to the top of the page.
- <img width="377" alt="Screen Shot 2023-10-16 at 2 48 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/0f27bf6f-0ae9-4430-a7d7-ecffc2ebfe3e">
- **Must** Matt Dingee: The representative selected page needs some rework as it is not very clear what to do. In my mind there should be a clear question/step: Here is your current representative. Do you want to appoint a new representative? Yes/No. If you say yes, you fill out the form and continue. Break it into sub tasks. If you say no, you don't. You stop.
- **Must**: Matt Dingee: It is not completely clear that the user must contact the representative and could be denied before they fill out the form. You may want to stop them before they fill out the form in case they are rejected by the representative. Make sure they know to contact and get approval before they fill out the form.
- <img width="647" alt="Screen Shot 2023-10-16 at 2 54 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/d7acfc37-280e-4102-9626-6ce78dd8b538">

- **Must**: Look at the [know their information is updated pattern](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated#how-to-design-and-build). Unbold "This is the personal..." and remove the blue color from the name.
- <img width="263" alt="Screen Shot 2023-10-16 at 3 07 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/7ead92bb-403e-46c8-a8f4-1c1d85d6bf2b">
- **Must**: Follow the [communicate information can be updated](https://design.va.gov/patterns/help-users-to/know-how-their-information-is-updated#communicate-information-that-can-be-edited) pattern and styling. Remove the cards, add the left blue border, change the edit button to a link, use correct heading styles.
- <img width="478" alt="Screen Shot 2023-10-16 at 3 13 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/2244f85d-8082-4b4c-9402-5c6007d0db32">
- **Must**: Add the i icon to the info alert. You should also consider using the [v3 alert styling](https://design.va.gov/components/alert#examples---v3).
- <img width="530" alt="Screen Shot 2023-10-16 at 3 15 52 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/3f4ff464-8126-44c2-8d07-7b554b26b063">
- **Must**: On the authorization for record access there is content asking the user to authorize the VA to disclose records and then below that there is content asking the user to select which treatments the do NOT authorize. This seems confusing to ask to authorize and then not authorize. I am also unclear what happens if a user selects No, I do not authorize, but then does not select any treatments below. My suggestion would be...
  - Ask the "Do you authorize the VA to disclose..." question on it's own page.
  - If the user selects "Yes" then ask which treatments they want to select on the next to authorize. Not, which treatments they do NOT authorize.
  - If the user selects "No" then you do not need to show which treatments.
  - Also add a close button to the modal.
  - <img width="1190" alt="Screen Shot 2023-10-16 at 3 32 09 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/72398073/91130396-a975-4ae6-a7a5-ebb7ba20681a">
  - **Must**: Our [guidance for primary action links](https://design.va.gov/components/link/action#choosing-between-variations) says to only show 1 primary action link on a page. You currently have 2 on the confirmation page, make one a secondary action link. 
  - **Must**: Follow the [confirmation page template](https://design.va.gov/templates/forms/confirmation) in our design system.

- **Should**: Use the [v3 version](https://design.va.gov/components/process-list#examples---v3) of the process list as that aligns with USWDS.

**Comment by oddball-lindsay** [comment]
@allison0034 hoping you can help us with some clarification around managing legal copy in a form experience.

We currently are using two different design patterns related to legal content:
1. The authorization for [record access](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/eyAmw0/p/0244ED81-DE1E-4D67-AEB8-D45E9596162F/canvas?posX=-9352.79951459288&posY=-84.8370552847835&zoom=0.41505199670791626) and [address change](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/eyAmw0/p/0244ED81-DE1E-4D67-AEB8-D45E9596162F/canvas?posX=-11694.674768078346&posY=-260.71863296424726&zoom=0.41505199670791626) uses a **radio pattern**
2. The [final review](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/v/eyAmw0/p/0244ED81-DE1E-4D67-AEB8-D45E9596162F/canvas?posX=-12275.32490808863&posY=-78.80518443746814&zoom=0.41505199670791626) with a button that launches a modal with full legal content uses a **checkbox pattern**.  This is slightly different but consistent with the pattern in VADS where there's simply a small new tab link to the full legal copy rather than having all the legal copy right in the page 

Interestingly -- and this adds to our quest for clarification -- we see that the [21-4142 form experience](https://www.va.gov/supporting-forms-for-claims/release-information-to-va-form-21-4142/introduction) has two different experiences around legal copy:
1. Step 6: the full legal content visible with an acknowledgement/authorization checkbox at the end
2. Step 10: The step the privacy policy is in a link off the page. 

Because we have existing research showing that the full legal copy is overwhelming and confusing for users, we would like to avoid a situation with long legal copy.  **Can the authorization pieces in our designs can also use the checkbox pattern** (and not the radio pattern), as reflected in the final review experience for both our designs and the 21-4142 form experience?

And for our own learning, we are very curious as to why these different design patterns exist around legal content if you happen to have any context around that!

cc @mtri

**Comment by allison0034** [comment]
Just making a note, we met with Lindsay and discussed some options. I am following up with Matt Dingee on Monday.

**Comment by oddball-lindsay** [comment]
Talked with @mtri and we are keeping the radio pattern for the authorization steps.  The concern with the checkbox pattern was that users might think the authorization was required to continue; the radio pattern helps to convey that they can select "no" and still continue.  

From our conversation yesterday, we've:
1. updated the button that reveals legal content form a primary to secondary button
2. made sure the legal content is available before the authorization step

**Comment by allison0034** [comment]
@oddball-lindsay that is a good point!
