### ISSUE TITLE
Ramp up profile forms to 100%

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#6782]
## Tasks
- [ ] Ramp up profile forms to 100%
- [ ] Monitor Google Analytics to ensure everything stays consistent

Relevant Google Analytics views:
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-transaction/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-deleted/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-edit-failure/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-saved/

**Comment by erikphansen** [comment]
@mshea0606 @Samara-Strauss 

I checked the analytics at Monday, March 16, 2020 11:32 AM ET. I'm no statistician but I see no change in contact info submission tracking since I rolled out the new forms to 50% of people last week. So I'm pushing it to 100%.

![image.png](https://images.zenhubusercontent.com/5b4d0309a8d8be5bda39303e/ff28d4c2-eaf4-45a5-820d-1084ee66756c)

- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200215&_u.date01=20200315&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-transaction/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200215&_u.date01=20200315&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-deleted/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200215&_u.date01=20200315&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-edit-failure/
- https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.date00=20200215&_u.date01=20200315&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=25&_r.drilldown=analytics.eventLabel:profile-saved/

**Comment by erikphansen** [comment]
Done.

**Comment by mshea0606** [comment]
Thanks Erik!
