### ISSUE TITLE
Midpoint Review - IA Feedback - Accredited Representation Management

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#67848]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this to us! Much of my feedback will echo what you will hear from design, content and accessibility.
- Question: the Sketch file shows search results for representatives that do not include email addresses, but instructions for the Veterans mention emailing the representative. Will email addresses for representatives be included in the future designs?

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must - update/clarify relationship to entry point pages:** Please continue work with CAIA to build in changes to the entry page(s) for this form. Will the page [Get help filing a claim](https://www.va.gov/disability/get-help-filing-claim/) be the primary entry point? If so, what will the relationship between the content of this page and the intro screen be?
- **Must: clarify user next steps on intro**: On the [intro screen](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/prototype/8A37B221-9C94-4989-9F81-783A6EF2FF37/a/8A37B221-9C94-4989-9F81-783A6EF2FF37), it is unclear which action the user should take - signing in, or find and appoint a representative? Though this isn't a standard form, how might the [intro page pattern from the form template library](https://design.va.gov/templates/forms/introduction) help clarify this intro screen?
- **Must: clarify breadcrumb text**: The breadcrumbs in the Sketch file show a parent page of "Disability" - is this correct, or is it [Disability benefits](https://www.va.gov/disability/)? Also ensure that breadcrumb capitalization and H1 capitalization match.
- **Must - search results**: Use a list rather than a table to display [search results on the Find a Rep screen](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/prototype/8A37B221-9C94-4989-9F81-783A6EF2FF37/a/D1B61F11-C688-4281-A5E1-90BCCEFA6001). The content should be easy to scan quickly and act on. The formatting from the [Find a location](https://www.va.gov/find-locations/) search results might be helpful.
- **Must - clarify Appoint a Rep page user flow**: Seconding (thirding?) design feedback from the meeting, the [appoint a rep](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/prototype/8A37B221-9C94-4989-9F81-783A6EF2FF37/a/C194F26C-0C9F-473D-B03E-AD4E249CD415) page is a bit confusing, with unclear next steps. It could be broken into separate pages: confirm your selection of a new rep, then move ahead with the form flow.
- **Must - heading text**: Continue to work with CAIA on heading text and capitalization. Headings should have consistent capitalization patterns using sentence case to increase readability. There are also a few screens, including search, which include colons at the ends of headings. I don't know if we have guidelines on this, but it seems unusual.
<img width="355" alt="Screenshot 2023-10-17 at 4 35 09 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/213864e4-e840-43b0-8a12-13ee226e5b93">

**Comment by mtri** [comment]
> Question: the Sketch file shows search results for representatives that do not include email addresses, but instructions for the Veterans mention emailing the representative. Will email addresses for representatives be included in the future designs?

WIP copy from CAIA for the new version of Appoint a representative does not currently include explict reference to emailing a representative. We will potentially have new data that includes email as of November 10th when we receive a new OGC spreadsheet so it is possible we will be able to support email in search results soon.

**Comment by mtri** [comment]
> Must - update/clarify relationship to entry point pages: Please continue work with CAIA to build in changes to the entry page(s) for this form. Will the page Get help filing a claim be the primary entry point? If so, what will the relationship between the content of this page and the intro screen be?

The main entry point will be a static landing page with links to both the Find a representative and Appoint a representative products. Links to the previously existing eBenefits experience will redirect to this landing page. An Accredited representative FAQs page will also crosslink for supplementary content and is also a possible entry point.

**Comment by mtri** [comment]
Feedback has been incorporated into the prototypes for both Find a representative and for 
Appoint a representative. Thank you again for all the very thoughtful feedback!

WIP Find a representative is viewable here (do not open in Sketch/save a new version because these are being used for usability testing currently and may refresh the prototype view. Viewing using the links below is fine though)

[Mobile view](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/prototype/91C5F671-4BC5-4CE9-B9EA-2D384B20C83A/a/91C5F671-4BC5-4CE9-B9EA-2D384B20C83A) 
[Desktop view ](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e/prototype/100C57E4-87B4-417E-BC4C-F24D85F39C91/a/100C57E4-87B4-417E-BC4C-F24D85F39C91)
[Canvas view](https://www.sketch.com/s/dfb0333d-65db-41f9-807e-6b25d6c5396e#About)

WIP Appoint a representative is viewable here:

[Desktop Prototype view](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/CB1C3151-23CF-40F6-9928-30D7900D7F25/a/CB1C3151-23CF-40F6-9928-30D7900D7F25)
[Mobile Prototype View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836/prototype/F68BAB55-E083-411A-A706-CD4251A38CB7/a/F68BAB55-E083-411A-A706-CD4251A38CB7)
[Canvas View](https://www.sketch.com/s/a75e9329-dae9-4984-867e-451d6e2fa836) (Has other states and paths not in prototypes as well as AB test screens for authorization pages.)

As the products were split into three(Find, Appoint, Widget), this feedback has been applied to the newly split products as best as possible. We are continuing to work with CAIA up to and through Find a representative and Appoint a representative user testing which may result in slight changes to content and breadcrumbs nomenclature.
