### ISSUE TITLE
Eligibility - Benefit applications - design.va.gov documentation

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#68]
This is a macro-level description of the Eligibility section of Benefit applications. 

Here are some points. These bullet points are not in any particular order.
• purpose of the form—plain language explanation of your eligibility of that benefit (draws heavily from SEO and keyword tools).
• prerequisites—what you have to have to be eligible
• wizards—disambiguate the form (help you figure out if you are actually eligible). walk someone through how this form applies to them
• Green button - why use the green button. what goes above/below
• Check your status (where would I look for it on the page? / prevent submitting twice)

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by KevinMHoffmanUSDS** [comment]
# Eligibility
For Veterans, determining whether or not they (or their beneficiaries) are eligible for a specific benefit is a difficult process. The policies governing those benefits can be complex, fraught with dependencies and variations that can be overwhelming. 

The associated pattern of content and functionality designed to help Veterans understand their eligibility, therefore, needs to accomplish a few things which can seem at odds with one another. Manifested as a single page, it should
* provide a simple introduction to eligibility rules that covers the most common scenarios,
* scale (expand) to represent variations in complexity,
* prevent Veterans from going to the wrong form,
* provide the ability to announce changes in the law or availability of benefits that may impact their eligibility, 
* provide space to connect Veterans to benefits that are likely to be related to their question about the benefit they are viewing, 
* guide Veterans to the next logical step in determining their eligibility, ultimately concluding getting them to the proper benefit application.   

## Eligibility Page Hierarchy
The hierarchy of the eligibility pattern allows it to be flexible enough to cover simple or complex benefit eligibility information while still feeling straightforward and easy to follow. The page consists of the following elements:

PAGE HIERARCHY ILLUSTRATION TK

### 1. Title and Statement of Intent
The title should be “Eligibility for (Most Commonly Used Benefit Name).” The statement of intent should state the job the page will do for the Veteran, by stating something like “Find out if you are eligible for (most commonly requested benefits, described in plain, Veteran language). This allows a Veteran to quickly assess if they are in the right place, and it helps search engines highly rank these pages for appropriate searches.

### 2. Optional: Eligibility change announcement
When time sensitive content about a benefit — such as a new benefit being made available or a significant change in the laws around eligibility for a particular benefit — you can place an alert box on this page. Follow the recommendations governing alert box usage, including
* Use informational alerts to announce upcoming benefits
* Use warning alerts to announce deadlines or expiring options
* Use alert boxes with expandable content to hide detail that may not apply to everyone visiting the page
* Do not use full-width alert boxes

View the alert box component. _components_alertboxes

### 3. Common Scenario Overview

The featured content component is used to present the Veteran with the most commonly sought benefit eligibility scenario. Because some benefits are complex and contain several optional paths, it is occasionally acceptable to repeat this element on the page where there is an additional eligibility use case that is common enough to warrant it. Note: please do not overuse this pattern (no more than 2 occurrences per eligibility landing page) as it decreases its effectiveness at being more easily seen on the page. 

DO DON’T ILLUSTRATION TK

View the featured content component. _components_featured-content

### 4. How to Apply Heading and Primary Call to Action Button 

A brief heading should precede and call attention to the primary call to action button. This heading can be followed by an optional single sentence of text or phrase if necessary. 

The button will lead the Veteran/applicant to one of two places: either the application flow for the benefit or a wizard mini-form interface allowing the Veteran to self-select into (or out of) the appropriate benefit form. 

Having a single green button on the page helps the Veteran follow the most logical path. Note: never put more than one green button on the page. If you have a page that requires multiple benefit form links, use the wizard mini-form interface to create branching logic to get the correct benefit application (or prevent a Veteran from applying to the wrong benefit). 

The button can be followed by 

View the button component. _components_buttons

#### 4.1 Optional: Wizard for Branching Eligibility Choices

In the case where there are multiple benefit options, the wizard allows a Veteran to branch into (or out of) the appropriate benefit application from the eligibility page. 
* A primary button (green button) reveals the first question of the wizard. 
* The text on the primary green button should represent the job the wizard is performing, such as “Find your education benefits form.” 
* After the wizard is revealed, the green button turns blue. This maintains the “one primary button per page” rule as the wizard will likely reveal a new primary button. 
* It should consist of mutually exclusive choices which use radio buttons. 
* The entire form is hidden by being contained within in an additional info component, so the choices are clearly displayed as interdependent and contained. 
* Steps dependent on not-yet -answered questions are hidden. It should only display the most recent question answered, which reveals the next unanswered question in the sequence. 
* The wizard mini-form should conclude with a primary (green) button linking to the appropriate form, or an 

Wizard logic should be documented in the following format. 

WIZARD LOGIC ILLUSTRATION TK 

View the form controls components. _components_form-controls
View the additional info component. _components_additional-info

### 5. Optional: Additional Benefit-Eligibility-Specific Relevant Content

Any additional content necessary that is connected to the primary benefit eligibility use case for the page can be added here. 

### 6. Optional: Benefit Eligibility Frequently Asked Questions

Use the accordion component to present questions that are common about eligibility for a benefit. 

View the accordion component. _components_accordions

### 7. Optional: Related Benefits Content

Any additional benefits (e.g. vocational benefits eligibility that is related to education benefit eligibility) can be added to the bottom of the page using the MYSTERY GREY BOX component. 

## Design Components Used for Eligibility
The following design system components are used to form the eligibility pattern:

* Alert boxes _components_alertboxes are used when you need to make a time-sensitive announcement about when eligibility for a benefit might become available, change, or be affected by the availability of a technical system or too. 
* Featured content _components_featured-content can be used to promote the most common benefit scenario for that category of benefits. Note: please do not overuse this pattern as it decreases its effectiveness at being more easily seen on the page. 
DO/DON’T illustrations TK
* Primary buttons _components_buttons are used to provide the Veteran with a single call to action to begin the application process. Note: please only use one button per eligibility page. In some cases the button may initiate a wizard, which can walk someone through pre-requisite questions to guide them to the correct form, or in some cases, prevent them from applying using the wrong form. 
DO/DON’T illustration TK
* Accordions _components_accordions are used to provide frequently asked questions about benefits eligibility that may not necessarily be the primary reason a user has come to the page. 
* Sidenav _components_sidenav can be used to identify secondary or sub audiences relevant to benefit eligibility, such as Active-duty service members,  POWS, or other variations in constituencies that may also be eligible for a benefit in question. Note: this should only be used when the benefit

**Comment by jaredcunha-usds** [comment]
@KevinMHoffmanUSDS This is really good! I have some small bits of feedback: 
- Lauren is working on the Wizard documentation, so I think instead of getting into that documentation here, I'll just link out to the wizard pattern documentation she's writing. 
- For the components used, the sidenav seems to belong more to the benefits hub structure vs eligibility.

**Comment by KevinMHoffmanUSDS** [comment]
Thanks, @jaredcunha-usds!

**Comment by KevinMHoffmanUSDS** [comment]
@lalexanderson-dsva Since it sounds like you've written this up, take a look and see if any of this is useful to add to what you've already assembled.

**Comment by jaredcunha-usds** [comment]
Oh, so reading one of @lalexanderson-dsva's responses on the wizard documentation, we should be using the word "users" instead of "veterans" in this case. Sometimes the applicant for a benefit might be a family member, for example.

**Comment by jaredcunha-usds** [comment]
@KevinMHoffmanUSDS I just updated your text to knock the heading levels down and link the links, to format for the page I'm working on. I'll provide more info as I start getting things ready.

**Comment by KevinMHoffmanUSDS** [comment]
@jaredcunha-usds Cool, I'm making a few more edits and adding images from the road. Cheers!

**Comment by KevinMHoffmanUSDS** [comment]
Eligibility

For Veterans, determining whether or not they (or their beneficiaries) are eligible for a specific benefit is a difficult process. The policies governing those benefits can be complex, fraught with dependencies and variations that can be overwhelming.

The associated pattern of content and functionality designed to help users of the website understand their eligibility, therefore, needs to accomplish a few things which can seem at odds with one another. Manifested as a single page, it should
* provide a simple introduction to eligibility rules that covers the most common scenarios,
* scale (expand) to represent variations in complexity,
* prevent users from going to the wrong form,
* provide the ability to announce changes in the law or availability of benefits that may impact their eligibility,
* provide space to connect users to benefits that are likely to be related to their question about the benefit they are viewing,
* guide users to the next logical step in determining their eligibility, ultimately concluding getting them to the proper benefit application.   

### Eligibility Hierarchy
The hierarchy of the eligibility pattern allows it to be flexible enough to cover simple or complex benefit eligibility information while still feeling straightforward and easy to follow. Generally, the eligibility pattern manifests itself as a single web page. It sits within a benefits hub based upon the following rules:

* For benefits hubs with a single benefit (such as [Health care](https://www.va.gov/health-care)), we link to a separate [Eligibility](https://www.va.gov/health-care/eligibility/) page as well as [How to apply](https://www.va.gov/health-care/how-to-apply) page from the hub landing page.
* For benefits hubs with multiple benefits (like [Life insurance](https://www.va.gov/life-insurance/)), we link to the [main options/Eligibility](https://www.va.gov/life-insurance/options-eligibility/) page from the hub landing page. From this page, the user can choose the option for which they want to explore their eligibility.
* For a benefits hub where there is only a single benefit available, such as [Veteran's Pension](https://www.va.gov/pension/), we link directly to the [Eligibility](https://www.va.gov/pension/eligibility/) and page for that benefit from the hub landing page. We also link to pages for other, related benefits (Aid and Attendance, and Survivors Pension) from the hub landing page using the RELATED PAGES COMPONENT.

The eligibility page consists of the following elements:

![](eligibility_page_heirarchy.png)


#### 1. Title and Statement of Intent
The title should be “Eligibility for (Most Commonly Used Benefit Name).” The statement of intent should state the job the page will do for the user, by stating something like “Find out if you are eligible for (most commonly requested benefits, described in plain language). This allows a user to quickly assess if they are in the right place, and it helps search engines highly rank these pages for appropriate searches.

#### 2. Optional: Eligibility Change Announcement
When time sensitive content about a benefit — such as a new benefit being made available or a significant change in the laws around eligibility for a particular benefit — you can place an alert box on this page. Follow the recommendations governing alert box usage, including
* Use informational alerts to announce upcoming benefits
* Use warning alerts to announce deadlines or expiring options
* Use alert boxes with expandable content to hide detail that may not apply to everyone visiting the page
* Use full-width alert boxes, warning or informational as contextually appropriate. 

[View the alert box component](https://design.va.gov/components/alertboxes).

#### 3. Common Scenario Overview

The featured content component is used to present the user with the most commonly sought benefit eligibility scenario. Because some benefits are complex and contain several optional paths, it is occasionally acceptable to repeat this element on the page where there is an additional eligibility use case that is common enough to warrant it. Note: please do not overuse this pattern (no more than 2 occurrences per eligibility landing page) as it decreases its effectiveness at being more easily seen on the page.

![](eligibility_common_scenario_do-don%27t.png)


[View the featured content component](https://design.va.gov/components/featured-content).

#### 4. Pre-requisite Content

Content detailing pre-requisites should follow common scenarios on the page. Group pre-requisites logically by benefit type, and order benefit types from most common to less common.

![](eligibility_prerequisites.png)

#### 5. How to Apply Heading and Primary Call to Action Button

A brief heading should precede and call attention to the primary call to action button. This heading can be followed by an optional single sentence of text or phrase if necessary.

The button will lead the user/applicant to one of two places: either the application flow for the benefit or a wizard mini-form interface allowing the user to self-select into (or out of) the appropriate benefit form.

Having a single green button on the page helps the user follow the most logical path. Note: never put more than one green button on the page. If you have a page that requires multiple benefit form links, use the wizard mini-form interface to create branching logic to get the correct benefit application (or prevent a user from applying to the wrong benefit).

The button can be followed by item 6, Additional Benefit-Eligibility-Specific Relevant Content, if necessary. 

View the [button component](https://design.va.gov/components/buttons).

##### 5.1 Optional: Wizard Pattern for Branching Eligibility Choices

For a detailed overview, view the Wizard pattern. The following information applies to building a Wizard in the Eligibility page.  

In the case where there are multiple benefit options, the wizard allows a user to branch into (or out of) the appropriate benefit application from the eligibility page.
* A primary button (green button) reveals the first question of the wizard.
* The text on the primary green button should represent the job the wizard is performing, such as “Find your education benefits form.”
* After the wizard is revealed, the green button turns blue. This maintains the “one primary button per page” rule as the wizard will likely reveal a new primary button.
* It should consist of mutually exclusive choices which use radio buttons.
* The entire form is hidden by being contained within in an additional info component, so the choices are clearly displayed as interdependent and contained.
* Steps dependent on not-yet -answered questions are hidden. It should only display the most recent question answered, which reveals the next unanswered question in the sequence.
* The wizard mini-form should conclude with a primary (green) button linking to the appropriate form, or an

View the Wizard pattern

[View the form controls components](https://design.va.gov/components/form-controls).

[View the additional info component](https://design.va.gov/components/additional-info).

#### 6. Optional: Additional Benefit-Eligibility-Specific Relevant Content

Any additional content necessary that is connected to the primary benefit eligibility use case for the page can be added here.

#### 7. Optional: Benefit Eligibility Frequently Asked Questions

Use the accordion component to present questions that are common about eligibility for a benefit.

View the [accordion component](https://design.va.gov/components/accordions).

#### 8. Optional: Related Benefits Content

Any additional benefits (e.g. vocational benefits eligibility that is related to education benefit eligibility) can be added to the bottom of the page using the RELATED PAGES component.

### Design Components Used for Eligibility
The following design system components are used to form the eligibility pattern:

* [Alert boxes](https://design.va.gov/components/alertboxes) are used when you need to make a time-sensitive announcement about when eligibility for a benefit might become available, change, or be affected by the availability of a technical system or too.
* [Featured content](https://design.va.gov/components/featured-content) can be used to promote the most common benefit scenario for that category of benefits. Note: please do not overuse this pattern as it decreases its effectiveness at being more easily seen on the page.
* [Primary buttons](https://design.va.gov/components/buttons#primary-buttons) are used to provide the user with a single call to action to begin the application process. Note: please only use one button per eligibility page. In some cases the button may initiate a wizard, which can walk someone through pre-requisite questions to guide them to the correct form, or in some cases, prevent them from applying using the wrong form.
* [Accordions](https://design.va.gov/components/accordions) are used to provide frequently asked questions about benefits eligibility that may not necessarily be the primary reason a user has come to the page.
* [Sidenav](https://design.va.gov/components/sidenav) can be used to identify secondary or sub audiences relevant to benefit eligibility, such as Active-duty service members,  POWS, or other variations in constituencies that may also be eligible for a benefit in question. Note: this should only be used when the benefit

**Comment by KevinMHoffmanUSDS** [comment]
@jaredcunha-usds Hey there - I've added a few illustrations, replaced all Veteran's with users (except where it didn't make sense to do so), and added links for the Wizard pattern (those links will have to be double checked.)

**Comment by jaredcunha-usds** [comment]
I've added your content to a draft page on dev-design.va.gov:
https://dev-design.va.gov/patterns/benefit-applications

For any updates moving forward, please edit this page directly using the link in the yellow box at the top of the page.

**Comment by jenniferlee-dsva** [comment]
@KevinMHoffmanUSDSn and @jaredcunha-usds  - just a quick note about the Featured Content (div.feature) component. To standardize these for CMS migration, there will only be one of these enabled per page, and limited to eligibility or requirements information. 

There are instances currently where a page might have 2 or even sometimes more, but we are fixing these instances hub by hub in time for the CMS migrations that are in-flight.

**Comment by caw310** [comment]
Closing as this is an old ticket. DS components and patterns should have addressed this.
