### ISSUE TITLE
Revisit best bets for 4138 ecosystem of forms

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#68003]
We need to assess how to add links or info about related forms on this "catchall" form page, to redirect people to the correct, more specific form to use.

**Comment by megzehn** [comment]
Update: I added the first 2 related forms from Tricia's request, since they have been digitized or are close to being digitized. 

Note that when we add related forms, the link to the digital form does not show up. That's a limitation of the Find a form template.

[Detail page for form 4138](https://www.va.gov/find-forms/about-form-21-4138/)

With that in mind, we may want to discuss a better way to link to the digital versions of the forms. I'm going to move this to the backlog for now until we can pick it back up.

**Comment by aprocik1** [comment]
@megzehn, you mentioned that we can close the intake ticket for this. Does that mean we can close this related task ticket too?

**Comment by kristinoletmuskat** [comment]
Thank you @megzehn ! I think we can revisit existing best bets around the new 4138 ecosystem, thank you for flagging! @scjwalker I added to our 1:1 for tomorrow to walk through this work. I also changed the title of this ticket and tagged IA so it shows up on our board. 

cc @aprocik1

**Comment by megzehn** [comment]
Yay thank you @kristinoletmuskat for revisiting Best bets! (And thank you for wading through this ambiguous ticket with my confusing updates!)

**Comment by scjwalker** [comment]
I've been collecting a list of the newer forms, to update best bets for. After chatting with the Veteran Facing Forms team, that list is looking like:
- 21-10210 - lay witness statement
- 20-10206 - personal records / FOIA request
- 20-10207 - priority processing
- 20-10208 - additional evidence for dissabilty claim (digital form is not in prod yet)

**Comment by kristinoletmuskat** [comment]
Yes I think that sounds good!

**Comment by aprocik1** [comment]
I'm closing this ticket as complete and adding it to the tracker.
