### ISSUE TITLE
[FE][CHIP] SPIKE - Determine if we can use custom datadog metrics from CHIP to measure time in a dashboard.

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68147]
## Background
IVC has asked us to measure and report to them how long it takes to complete check-in with and without travel.

Ask: Average length of time to do eCheck-in with and without travel.

## Tasks
 - [Install Datadog Lambda extension](https://docs.datadoghq.com/serverless/libraries_integrations/extension/) 
 - On dev hard code the [custom metrics](https://docs.datadoghq.com/serverless/custom_metrics/) that we are wanting to track
     - seconds to completion
     - was travel enabled
     - was travel submitted
 - Create a datadog dashboard to see if we can plot the data as described in [this ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/67177)

**Comment by lee-delarm6** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGJWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39c9b288e1e354902422a106e85ae9e8e7e698ae/Screenshot%202023-11-14%20at%205.47.18%20PM.png)

I have a test dashboard for the spike. This can be expanded into the final version easily. This is based on "real" travel data (fake). Once integration is complete, we can tie this into real data. We will likely need to make sure this works as expected in prod as well, but it is versatile and maintainable through using dogstatsd in the CHIP code (rather than groking log metrics)

**Comment by lee-delarm6** [comment]
Let's validate this with another engineer before calling it good tomorrow @wullaski @brianseek @randomsync @kanchanasuriya

**Comment by loripusey** [comment]
@wullaski can you validation this one before sprint review?
