### ISSUE TITLE
Midpoint Review - Content - Collaboration Cycle for Veteran Facing Forms - VA form 21-0779 #66342

### ISSUE THREAD

**Issue by BSmolensky** [department-of-veterans-affairs/va.gov-team#68157]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts
This is a great midpoint for your project. Things are clearly laid out and you don't overload the user on any one page. Well done! There are, however, a few areas for improvement. Please reference my feedback below. 

### MUST

- Page 0: Header case is inconsistent with the rest of the pages. Please use consistent header case. 
- Page 0: Passive Voice 1 - "This form is used..." Please use active voice. 
- Page 0: Passive Voice 2 - "This form should only..." Please use active voice. 
- Page 0: Passive Voice 3 - "After the form is submitted..." Please use active voice. 
- Page 0: Typo - In the first sentence of the second paragraph of the section "What to know before you fill out this form," the user finds a list that includes "File number." This "f" in file needs to be lowercase. 
- Page 0: Not in Plain Language - In the paragraph that begins "This form is used to verify..." the user finds the following sentence: "A responsible official of the nursing home certifies that the claimant is a patient (and not a resident) of the nursing home." This is a confusingly worded sentence that is not in plain language. Please put this sentence in plain language. 
- Page 0 - Not in Plain Language - "Respondent Burden" is not in plain langue. Please put this in easier to understand language. 
- Page 1: Typo - "Only a nursing home official should fill out this form" is a complete sentence and needs a period. 
- Pages 3.2 Mobile & 3.2 SSN pattern 1 Desktop: Spacing Issues - The instructions underneath Veteran's Information overlap with the words "veteran's information." Please fix this so that they are both readable. 
- Review Page: Typo - In the Statement of Truth section, the user finds a "Note." That note needs a period at the end. 
- Review Page: Passive Voice - In the legal statement "Note" the user finds "there are criminal penalties for withholding..." This is passive voice. Please change to active voice. 

### SHOULD

- ALL PAGES: The H1 on every page is immediately contradicted by its subtitle. The H1 says "Submit" the subtitle says "Request." This is a confusing. The VFS team should ensure that these action verbs match so as not to confuse the user. 
- Page 0: What is the difference between a resident and a patient? The VFS team should provide the user with enough information to determine if this is the correct form for them. 
- Page 0: Near the bottom of the page, the user finds this sentence: "After the form is submitted, The VA can..." The VFS team should change "can" to "will" to help the user understand that the process will continue. 
- Page 3.1 (all) - The "page" of the process is titled "Patient Information" but the prompt is for "Veteran's Information." The VFS team should make this less confusing for the user. 
- Page 3.2: The VFS team should make it more apparent that the user only needs to provide one of these inputs in order to proceed. 
- Review Page: The VFS team should provide instructions for the user before the user reaches the list of toggles. This will allow the user to better understand what they need to do on this page. 
- Confirmation Page: Confusing Repetition - The word "Confirmation" appears twice in this list. This is confusing, especially when it appears in "Confirmation for your records." The VFS team should eliminate the confusing repetition to make the instructions clearer to the user. 

### CONSIDER
Page 1: "Your Personal Information" - Please consider clarifying exactly whose information is required here. 

### NOTES:
Thank you again for the opportunity to review this product. You are on the right track and there is so much good stuff here. Please continue to work with CAIA to maximize your efforts.

**Comment by rachelshearerux** [comment]
Thank you so much for the thoughtful feedback! I’ve updated our sketch and [source of truth](https://github.com/department-of-veterans-affairs/VA.gov-team-forms/blob/main/Forms/21-0779/sourceoftruth.md) to incorporate most of the recommendations, and the form is in a great place for developer handoff thanks to your team. 

Here’s what **hasn’t** been incorporated: 

**MUST**:
- Page 0 - Not in Plain Language - "Respondent Burden" is not in plain langue. Please put this in easier to understand language.
- Review Page: Passive Voice - In the legal statement "Note" the user finds "there are criminal penalties for withholding..." This is passive voice. Please change to active voice.

These are both examples of standard language from OMB a for consistency sake a change here should kick-off a change at the design system level. CAIA is aware of both issues raised, and plans to bring them up with OMB and Legal in the future. A VFS team member flagged the legal language issue with the DST in the past, here’s the ticket for reference.


**SHOULD**:
- Review Page: The VFS team should provide instructions for the user before the user reaches the list of toggles. This will allow the user to better understand what they need to do on this page.
- Confirmation Page: Confusing Repetition - The word "Confirmation" appears twice in this list. This is confusing, especially when it appears in "Confirmation for your records." The VFS team should eliminate the confusing repetition to make the instructions clearer to the user.
These are both design-system components that are standard across multiple forms and a change here would require a larger design-system update. 

**SHOULD**: 
- ALL PAGES: The H1 on every page is immediately contradicted by its subtitle. The H1 says "Submit" the subtitle says "Request." This is a confusing. The VFS team should ensure that these action verbs match so as not to confuse the user.

I understand why this might be confusing when you see the titles side-by-side. Ideally, the .pdf title would better reflect what the form *filler* is doing, which is submitting information to the VA. We made the change so that it is more clear to users what this form is for, and speaks to their point of view. We’ll work with content to explore other options.
