### ISSUE TITLE
Privacy and Security Review [SSOe]

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#6823]
## Steps to complete the Privacy & Security Review: 
- [x] Lead engineer or product manager: using this template, create issue and fill in feature name in the title 
- [x] Reach out to Andrew Gunsch (@ gunsch in Slack) to schedule a 60 minute meeting 
- [x] VSP privacy and security review team provides written feedback for your team on your feature, including clear action items to complete
- [ ] **Requesting team** completes action items
- [ ] Requesting team requests validation of completed action items and signoff from Andrew Gunsch before rollout 
- [ ] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please provide the following artifacts 2 days before scheduled meeting_
- An architecture diagram, showing involved systems + data flows
- Description of any new publicly-exposed endpoints (vets-api or otherwise)
- Description of any new interactions with dependent services (i.e. vets-api --> ???)
- Description of any other security hotspots you're concerned about / want extra attention on

## Meeting attendees from **SSOe team**
- Lead engineer (required): **Patrick Vinograd*
- Product manager (required): **Ambika Roos and/or Alexis James**
- DEPO product lead (required): **Lauren Alexanderson**
- Anyone else on your team whose presence is needed to speak to the technical architecture and security concerns (required): **Dan Hinze, Eric Buckley**

## Scheduling 
Preferred dates or times: Wed. 3/25 - Thu. 3/26 - Fri 3/27

## Additional Notes
Following this review, VSP engineers will provide a list of concrete action items that need to be addressed, or approval to begin roll out

**Comment by patrickvinograd** [comment]
Requested artifacts are available here:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/sso/security-review/SSOSecurityReview.md

**Comment by patrickvinograd** [comment]
Tagging @gunsch for awareness.

**Comment by gunsch** [comment]
Thanks for meeting today! We had a great long conversation, couple AIs that we'd like the team to make sure happen _eventually_ (not launch-blocking) and a couple we';d like to see happen _before launch_.

Eventually (not launch blocking):
- [ ] Fetch SSOe SAML metadata (public key, etc.) from public endpoint rather than checked into devops repo
- [ ] Find way to allow login during local development (localhost) without needing secret client key + cert configuration

Launch blocking:
- [ ] Look into what kind of traffic SSOe is prepared to handle for launch (noting we have both logins + KeepAlive endpoint sessions) so we can have more confidence that the rollout of SSOe won't break the experience for Veterans
- [ ] Look into ways we can measure how much add'l latency SSOe is adding to the login flow (coordinate with @annaswims on this)
- [ ] Look into ways to distinguish (in reporting from vets-api) which identity broker (SSOe vs. ID.me) is at fault when there's a failure
- [ ] Make sure rollout plan is starting small (recommended 1% since this is hitting all users) with metrics to compare before rolling out further
- [ ] Version tags/labels on statsd metrics for SAML error responses
- [ ] IAM contacts/escalation process is documented and checked in

Some of these are "look into" items, which means they don't necessarily have a pre-determined solution. If there's something achievable that makes sense / isn't too difficult, let's try to get it in for launch. If not, we can decide case-by-case whether they should be punted for launch.

**Comment by marriej** [comment]
Meeting complete, continued work captured in #7885.

**Comment by gunsch** [comment]
Reopening this issue until launch-blocking actions are complete.

**Comment by marriej** [comment]
@gunsch please see ticket #7885 for after actions.
