### ISSUE TITLE
Identify Necessary CHIP Work

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68275]
## Background
In order to prepare for our work to support the CERNER integration, we need to have an initial whiteboarding session to begin to understand what work may be necessary on the CHIP side.

## Tasks
- Anita schedules a meeting with Stephen & Kay & Lori & our engineers
- Have an initial whiteboarding session to begin to understand what work may be necessary on the CHIP side.
    - 1, 1-hour meeting + document decisions

**Comment by brianseek** [comment]
@anita-halici just an FYI if we want to do this during this sprint, we should have the meeting tomorrow or Thursday since I am out Friday to Wednesday

**Comment by brianseek** [comment]
meeting recording: https://us06web.zoom.us/rec/share/KcL1oXAFJ9gbpsKGckJygFzNtzD3q2m6j7T9eOox4ygwbMXfyRvVFaNNVxvMjMfn.8B5Ja8_WdTHKmy7w

Key take aways:
 - We can start planning work to integrate with profile to handle demographics rather than CW/Vista
 - MAP api to do all appointment things is a desired outcome, need to work with vetext on what may be feasible there.
 - Not cerner related but we need to move to a new AWS instance. Stephen to look into devops support.

**Comment by brianseek** [comment]
Moving to validation for @loripusey to review when she returns

**Comment by loripusey** [comment]
I guess the first step then is to reach out to the Profile team and re-start the effort to integrate with them. We had been meeting with them once a week for the better part of a year and that never went anywhere so we will need to figure out where we left off and how we can move this forward.
