### ISSUE TITLE
High Priority: Undo Redirect of Disability Special Monthly Rates Pages

### ISSUE THREAD

**Issue by lunascoop** [department-of-veterans-affairs/va.gov-team#6833]
### Description
These pages were redirected on 3/10 but displays the incorrect special monthly rates and is causing confusion.

**This is an updated ticket based on work completed in ticket #6087 ** 

### Requestor team info
Public Websites

### Implementation date
**ASAP****

### Redirects needed

Redirect back to URL  |  Current URL
---  |  ---
https://www.benefits.va.gov/compensation/rates-index.asp | https://www.va.gov/disability/compensation-rates/
https://www.benefits.va.gov/compensation/resources_comp02.asp | https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/

### Definition of done
- [x] Above information is provided and issue is tagged and assigned appropriately - *@ requesting team*
- [x] All appropriate VA stakeholders are notified of pending redirect - *@ requesting team*
- [x] Request is assigned to appropriate team for implementation - *@ Content & IA team*
- [ ] Implementation team completes work - *@ Implementation team*
- [ ] Implementation pushed live and redirect is validated in production - *@ all*
- [ ] Ticket is closed - *@ requesting team*

**Comment by AnneHurley** [comment]
Note: No need to redirect this page:
https://www.va.gov/disability/compensation-rates/veteran-rates/



As I am updating that and will have that page ready to push live tomorrow.



*[image: GovernmentCIO]* <http://www.governmentcio.com/>

*Anne Hurley** |*
  Content writer

| *mobile* (503) 298-7203
| *e.* ahurley@governmentcio.com

*Government**CIO*
*website <https://www.governmentcio.com/> **|** media
<https://governmentciomedia.com/> **|** services
<https://www.governmentcio.com/services> **|** jobs
<https://careers-governmentcio.icims.com/> **|** map
<https://www.google.com/maps/place/101+Constitution+Ave+NW+%23100,+Washington,+DC+20001/@38.8927387,-77.0151008,17z/data=!3m1!4b1!4m5!3m4!1s0x89b7b787cdfdb85f:0x1e5a93a8a2b38b03!8m2!3d38.8927345!4d-77.0129121>*

*[image: Twitter]* <https://twitter.com/GovernmentCIO> *[image: Facebook]*
<https://www.facebook.com/GovernmentCIOMedia> *[image: LinkedIn]*
<https://www.linkedin.com/company/governmentcio> *[image: YouTube]*
<https://www.youtube.com/user/GovernmentCIO/videos> *[image: Instagram]*
<https://www.instagram.com/gciotalent>


*Confidentiality Note: This email may contain confidential and/or private
information.If you received this email in error please delete and notify
sender.*





*From:* lunascoop <notifications@github.com>
*Sent:* Thursday, March 12, 2020 12:59 PM
*To:* department-of-veterans-affairs/va.gov-team <
va.gov-team@noreply.github.com>
*Cc:* Anne Hurley <ahurley@governmentcio.com>; Assign <
assign@noreply.github.com>
*Subject:* [department-of-veterans-affairs/va.gov-team] High Priority: Undo
Redirect of Disability Special Monthly Rates Pages (#6833)


Description

These pages were redirected on 3/10 but displays the incorrect special
monthly rates and is causing confusion.

**This is an updated ticket based on work completed in ticket #6087
<https://github.com/department-of-veterans-affairs/va.gov-team/issues/6087>
**
Requestor team info

Public Websites
Implementation date

*ASAP***
Redirects needed

*Current URL*

*Redirect Destination (new URL)*

https://www.benefits.va.gov/compensation/rates-index.asp

https://www.va.gov/disability/compensation-rates/

https://www.benefits.va.gov/compensation/resources-rates-read-compAndSMC.asp

https://www.va.gov/disability/compensation-rates/

https://www.benefits.va.gov/compensation/read_rates.asp

https://www.va.gov/disability/compensation-rates/

https://www.benefits.va.gov/compensation/resources_comp01.asp

https://www.va.gov/disability/compensation-rates/veteran-rates/

https://www.benefits.va.gov/compensation/resources_comp02.asp

https://www.va.gov/disability/compensation-rates/special-monthly-compensation-rates/

https://www.benefits.va.gov/compensation/special_Benefit_Allowances_2018.asp

https://www.va.gov/disability/compensation-rates/special-benefit-allowance-rates/
Definition of done

   - [X] Above information is provided and issue is tagged and assigned
   appropriately - *@ requesting team*
   - [X] All appropriate VA stakeholders are notified of pending redirect - *@
   requesting team*
   - [X] Request is assigned to appropriate team for implementation - *@
   Content & IA team*
   - [ ] Implementation team completes work - *@ Implementation team*
   - [ ] Implementation pushed live and redirect is validated in production
   - *@ all*
   - [ ] Ticket is closed - *@ requesting team*

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/department-of-veterans-affairs/va.gov-team/issues/6833>,
or unsubscribe

**Comment by lunascoop** [comment]
@ncksllvn @kelsonic redirects are ready to be reversed.

**Comment by AnneHurley** [comment]
@RLHecht  The updated 2020 disability compensation rates tables are now updated here: https://prod.cms.va.gov/node/986/edit

Uploaded the applicable charts from Sandy and team below. I checked the numbers and math and hope to get one more fresh read tonight, but they can use your eagle eye as I entered everything manually.

@jenniferlee-dsva  Question about historic rate charts - I added 2018 to this page. But 2019 doesn't seem to exist any more in benefits.va.gov, and I'm guessing that's because we redirected it to this page in VA.gov. Perhaps VBA needs to convert their historic rate tables pages to PDFs or something going forward, so we don't eliminate the older pages when we redirect. If they are in fact necessary.

**Comment by AnneHurley** [comment]
[2020 disability rate tables.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4327094/2020.disability.rate.tables.pdf)

**Comment by AnneHurley** [comment]
This now encompasses #6183

**Comment by RLHecht** [comment]
This has all been checked and published with a content only deploy. @AnneHurley @AkucherGCIO @jenniferlee-dsva

**Comment by lunascoop** [comment]
Validated and notification to staekholders sent. Closing ticket. Thanks everyone!
