### ISSUE TITLE
Add feature toggle to API for upcoming proof of veteran status feature

### ISSUE THREAD

**Issue by liztownd** [department-of-veterans-affairs/va.gov-team#68342]
As a Developer I want a Feature Toggle for the Veteran Status feature on VA.gov so that we can develop and test the feature and prevent it reaching production before it is ready.

Acceptance criteria:
Feature toggle makes feature available when toggled on and unavailable when toggled off
Toggle is initially set to Off

The feature toggle prevents new work from appearing on prod/staging until the feature is ready to release. Before we begin merging any front end code we need a feature toggle (switched to OFF) in the API so we can work without an accidental pre-release of the proof of veteran status feature on va.gov.

**Comment by matt4su** [comment]
As a Developer I want a Feature Toggle for the Veteran Status feature on VA.gov so that we can develop and test the feature and prevent it reaching production before it is ready.

Acceptance criteria:
Feature toggle makes feature available when toggled on and unavailable when toggled off
Toggle is initially set to Off
End to end tests are created as needed
