### ISSUE TITLE
[Design] 10-10EZR - V2 form: Emergency Contact and Next of Kin (EC/NoK)

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#68375]
As a Veteran, I would like to update my Next of Kin and Emergency Contact so that if something happens to me the VA knows who to contact and who to provide support to. 

- [x] Contact MHV team to see how they're building the "edit" functionality for NoK/EC and see if there is any overlap (e.g. content explanation)--Wes Rowe (PO) and Lynne Johnson (SM)
- [x] Confirm data fields with Devs (when they're available) or Alex
- [x] Design for the following fields:
- [x] -- Emergency Contact Name
- [x] -- EC #
- [x] -- Next of Kin name
- [x] --NoK Address
- [x] --NoK relationship 
- [x] --Nok Phone #
- [x] Use the [10-10 EZR paper](https://www.va.gov/vaforms/medical/pdf/va%20form%2010-10ezr.pdf) form as a reference
- [x] Build files in Figma
- [x] We'll have a story for designing for EZ as well
- [ ] **Success: We have designs for EC/NoK which match the API data fields **

**Comment by IMHieuVo** [comment]
[Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698340057865/2e2eced8589757c192a1601579a871cab97d3565?sender=ubf5503bf47b6eb1e92730053)
[Sketch](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/46008C1C-7A97-4B7F-A41D-E3EFBDB0C53D/canvas)

Things to note:
- Authenticated experience is only designed read-only version for their MVP.
- Their research is around the week of 11/13.

**Comment by IMHieuVo** [comment]
Enrollment System splits the dataset into Primary and Other EC/NOK. We don't know what happens when the Primary EC/NOK is deleted. After we reach the (2) contact limit, we don't know what happens when we add an additional contact. 

Since devs can only confirm that the info can be sent-to/received-from the Enrollment System, frontend will need to out the screens and then we'll start testing to see what happens when we remove/add EC/NOK.

**Comment by IMHieuVo** [comment]
Since the basic mockups were completed we'll close this ticket and open a new one for consequential modifications and changes.
