### ISSUE TITLE
[CAIA Intake] Contention Classification work on 526 EZ conditions list

### ISSUE THREAD

**Issue by yurenanava** [department-of-veterans-affairs/va.gov-team#68416]
## About your team

- Team name: Contention Classification
-	OCTO-DE product owner: Jennifer Bertsch
-	Product manager: Yurena Garcia-Hevia
-	Designer/Researchers: Eva Heintzelman, Sudeepti Bhatnagar
- Accessibility specialist: We do not have a dedicated accessibility specialist
- Content writer: Designer/researchers are responsible for writing terms
-	Slack channel: #benefits-contention-classification
 
### Describe what you need in a few sentences: 
We are updating the suggested conditions list that is used in the 526 EZ flow on the screen where Veterans can name a condition to add to their claim. The suggested conditions list is the source list for the autosuggest component. In the short term, we need a review of our revised conditions list from a content perspective. 

Over the long-term, we envision translating this conditions list into a conditions taxonomy that can be broadly shared and used across the platform. We need your continued collaboration and guidance as we take steps in this direction. This might include continued expert content review of the taxonomy as we go through iterations and guidance on the following:
- taxonomy structure (fields, hierarchy)
- research methods for testing the taxonomy
- technical solutions for managing the taxonomy
- taxonomy governance (How and who can make changes to the taxonomy? what does this process look like?)
</br>

### Which are you doing?
- [ ] **Launching a new** page, tool, form, or app
- [x] **Making changes** to an existing page, tool, form, or app

### Types of Support
What areas does your team need support in? Check all that apply.
#### Content
- [x] Collaboration on content written by your team’s dedicated content writer 
- [ ] Collaboration on content if your team does not have a dedicated content writer
#### Accessibility
- [ ] Accessibility review of wireframes and/or prototypes
- [ ] Accessibility issue (general request)
- [ ] Accessibility PDF review request
- [ ] Accessibility user research support ([submit a separate, additional request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name))
- [ ] DST component or pattern 
- [ ] Something else 
#### IA
- [ ] User Flows
- [ ] Page placement
- [ ] URLs
- [ ] Breadcrumbs and Left Nav placement
- [ ] Redirects
#### Multilingual content
- [ ] Translating content
 
## Timeframe
Target timline for upcoming releases
- Early November 2023: release of "quick win" update, which entails simply removing items from the existing list in production. *Note that we are not requesting CAIA review of this list*
- Early December 2023: release of first iteration on redesign of conditions list. *We are requesting CAIA review of this list prior to release* In order to achieve this, we would like any feedback on the list itself by Nov 15, so that we can incorporate any changes.
- The proposed conditions list taxonomy is a longer-term project, and our main focus, in the short-term, is on gathering perspectives and guidance so that we can build the best product possible

### Have you worked with CAIA before? 
  - [ ] Yes
  - [x] No

### What's your team’s next step and its timing?
- **Release "quick win" update**: early November 2023

#### Timing for your next step: 
  - [ ] Next week
  - [x] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Is this timing related to a specific event or Congressionally mandated deadline?
  - [ ] Yes
  - [x] No

### If you're conducting research, when is that starting?
We are in the synthesis phase of a [research study with Veterans](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/526ez/research/CC-Team-Research/2023-10%20Conditions%20List). The purpose of the research is to understand their mental model for medical condition and to evaluate the existing UI component (with are revised conditions list as the source for auto-suggestions). We anticipate that this will result in some changes to specific terms on this list, but that it will not change our overall approach to creating/structuring the terms. Veteran research sessions have been completed. Synthesis will be completed in early November, so that changes can be incorporated into the list prior to target release in December. 

**Provide date if available:** see note above
  - [ ] Next week
  - [ ] This month
  - [ ] Next month
  - [ ] This quarter
  - [ ] Next quarter
  - [ ] 6 months
  - [ ] 1 year

### Will you release this new product incrementally (for example, release to 25% of users to start)? 
  - [ ] Yes
  - [x] No
 
**Note**: _If you checked yes, we’ll reach out to discuss details about the content in the react widget (we use these widgets to display entry points for new products to a certain percentage of users who visit our static pages)._
  
### When do you expect to launch your product to 100% of users?
  
*Please provide an estimated date so our team can create other relevant tickets.*
- **We expect to launch our product to 100% of users on:** xx/xx/xxxx
  
### Will this work be going through the Collaboration Cycle?
- [x] Yes 
- [ ] No
 
#### Please provide the link to your Collaboration Cycle ticket: 
- For "quick win" update (removal of terms from current conditions list)
  - **Ticket (number)**: [#65064](https://github.com/department-of-veterans-affairs/va.gov-team/issues/65064) 
  - **Collab. Cycle Ticket Opened (date)**: 09/06/2023
 
- For first redesign of conditions list
  - **Ticket (number)**: [#67617](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67617)
  - **Collab. Cycle Ticket Opened (date)**: 10/13/2023
 
#### Please check all of the phases in the Collaboration Cycle you have completed: 
- For "quick win" update (removal of terms from current conditions list)
  - [x] Design Intent
  - [x] Midpoint Review
  - [x] Staging
 
- - For first redesign of conditions list
  - [x] Design Intent
  - [x] Midpoint Review
  - [x] Staging
 
##### Design Intent
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Midpoint
- [ ] Accessibility
- [x] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
##### Staging
- [ ] Accessibility
- [ ] Content
- [ ] IA
- [ ] Translation
- [ ] Already completed, no assistance needed
- [ ] Unknown at this time
  
## Supporting artifacts
*Please provide links to supporting artifacts as available.*
- **Product outline**: See [product brief](https://github.com/department-of-veterans-affairs/vagov-claim-classification/blob/main/collab-cycle/202310%20Redesign%20Suggested%20Conditions%20List/README.md)
- **User flows**: See [design intent](https://github.com/department-of-veterans-affairs/vagov-claim-classification/blob/main/collab-cycle/202310%20Redesign%20Suggested%20Conditions%20List/Design%20Intent%20-%20202310%20Redesign%20Suggested%20Conditions%20List.md) for how this conditions list fits into the 526EZ flow
- **Prototype or mockups**: [Codepen prototype](https://codepen.io/ccteam/live/poqxVpB) This prototype approximates functionality currently in production. The source list for the auto-suggestions is the revised suggested conditions list. 
- **Content source of truth**: [Conditions list for review](https://github.com/department-of-veterans-affairs/vagov-claim-classification/blob/main/collab-cycle/202310%20Redesign%20Suggested%20Conditions%20List/Conditions%20List%20for%20Review) and [Conditions List Guiding Principles](https://github.com/department-of-veterans-affairs/vagov-claim-classification/blob/main/collab-cycle/202310%20Redesign%20Suggested%20Conditions%20List/Conditions%20List%20Guiding%20Principles.md)
- **Research plan:** [Research Plan for Form 526 Conditions List, 2023-10](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/disability/526ez/research/CC-Team-Research/2023-10%20Conditions%20List/research-plan.md)
- **Any epics/issues that may be helpful**: [First redesign of dropdown list](https://app.zenhub.com/workspaces/contention-classification-640a24db5dcd08457cebbc79/issues/gh/department-of-veterans-affairs/vagov-claim-classification/229)
- **Link to testing accounts** (please do not paste them in this ticket): NA

### Have you already worked with someone from OCTO leadership?
- [x] Danielle
- [ ] Beth
- [x] Mikki
- [ ] Martha

### How do you plan to work with us on this request?
- [ ] I’ll take this to Beth or Danielle’s office hours.
- [ ] I’d like to schedule time to talk about this.
- [ ] Let’s work async and meet as needed.
- [x] Schedule a kick-off call with your team and CAIA for your project **(Recommended)**

 
### Accessibility Help in Slack
The [#accessibility-help channel](https://dsva.slack.com/archives/C8E985R32) in the DSVA Slack, is also available to you as a resource. Everyone is welcome to ask questions or get help from our a11y (accessibility) specialists. Tag `@Terry Nichols` to get a11y help asap.

## Next steps

**Once you’ve submitted this ticket, please post a link to this issue in the [#sitewide-content-ia](https://dsva.slack.com/channels/sitewide-content-ia) Slack channel and tag `@Terry Nichols`.**

- If you also need engineering support from the Public Websites team, fill out their [intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E).
  
- If you need a page/URL redirected, a URL changed or a vanity URL set up, please submit a [Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=jennymayoco%2C+kristinoletmuskat%2C+strelichl&labels=sitewide+CAIA%2C+Sitewide+IA%2C+Public+Websites%2C+VA.gov+frontend%2C+Redirect+request&projects=&template=redirect-request.md&title=Redirect+Request)
 
 - If you are creating an [experimental design,](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns#what-is-an-experimental-component-or-pattern?) please [also contact the DST. ](https://design.va.gov/about/contributing-to-the-design-system/suggest-an-addition-or-update)

- If you are requesting [a11y support for user research,](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=coforma-terry%2Cangelafowler82&labels=508%2FAccessibility%2C+sitewide+CAIA%2C+sitewide+accessibility%2C+CAIA-a11y-research&template=caia-a11y-research.yaml&title=%5BCAIA+A11y+Research%5D%3A+Team+name%2C+product+name) please complete this form, next. 
```[tasklist]
### CAIA Tasks
- [x] CAIA introduction sync scheduled with @strelichl and @coforma-terry 10/30 at 1pm EDT
```

```[tasklist]
### Content Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/69002
```

**Comment by laurwill** [comment]
Hi @yurenanava , could you give me access to this Google sheet? [Contention list master for CAIA Review](https://docs.google.com/spreadsheets/d/1KH-YCWwFKHdXV0KzMJUA3A6vo1bAQdEXJmo-4wGxDaQ/edit#gid=1500941157) Thank you!

**Comment by laurwill** [comment]
Hi again @yurenanava , I've added 2 columns with suggested term changes and notes/questions to the "Revised terms (proposed)" sheet in the [Contention list master for CAIA Review](https://docs.google.com/spreadsheets/d/1KH-YCWwFKHdXV0KzMJUA3A6vo1bAQdEXJmo-4wGxDaQ/edit#gid=1500941157).

Here are some general notes on my approach here:
- I used .gov sources like MedlinePlus to confirm plain language terms and other details about the conditions in the sheet. But just want to be clear that my suggestions are based in content and not clinical expertise, so all adjustments I've suggested will need to go back to your clinical SMEs for review. I'd be happy to join a call or be copied on any communications with those SMEs to support this process.
- I've added plain language definitions of terms when I could easily find a brief, natural plain language swap. For terms that are too complicated to explain in a brief parenthetical, I haven't added explanations.
- I suggested changing "bilateral" to "both" throughout, since left, right, or both are more plain language options.
- I adjusted some of the existing parentheticals to include the entire term being defined. For example, I changed "wrist replacement (arthroplasty)" to "wrist replacement (wrist arthroplasty)" to avoid the impression that "arthroplasty" means "wrist replacement."
- I've left questions in some rows about how sensitive the autosuggest function will be—for example, if a user types "tracheal" will it suggest "trachea cancer"? Or do the spellings need to be more exact?
- I didn't make this change in the sheet, but I suggest sentence casing (capping first letter) of the condition terms when they appear in the autosuggest list, to match styling on items in lists across VA.gov.
- The list varies between leading with the familiar plain language term (like "ringworm (dermatophytosis)") and leading with the medical jargon term (like "dysphagia (difficulty swallowing)"). I think this variation is okay—but I've adjusted some rows to lead with what seems to be the more commonly used term, regardless of whether this is the plain language or jargon term.

Let me know if you have questions or want to chat about anything I've suggested!

**Comment by laurwill** [comment]
Hi @yurenanava I saw some of your responses in the sheet and added some new comments. Also noting I shared the sheet with Danielle and Mikki, in case they have any higher-level thoughts they want to share. Thanks for the collaboration!

**Comment by laurwill** [comment]
Oh and one other question: If we change the name of a condition, does that change apply across past claim records? Or could a Veteran end up with 2 claims in their claim history for the same condition, but with different names?

**Comment by eheintzelman** [comment]
@laurwill Thank you for your collaboration on this. We very much appreciated all of your comments and suggestions. There are still a few items we are deliberating on, and I will be in touch to chat!

In response to your question on the impact of changing condition names: Any changes we make to the conditions list does not impact previously submitted claims (it also doesn't impact the names of conditions already added to in-progress applications).  So yes, it could be that a Veteran has multiple variations on a condition name in their claim history (but only if they submitted a new contention for the same condition twice, which I don't imagine is common behavior). This could happen today as well though, since users can type in their own condition names. 

Another thing to keep in mind is that the conditions list is just for submissions. On decisioning a claim, RVSRs will typically write a more medically specific description. If the result is a rated disability, the description of the rated disability is as described by the RVSR, not as described by the Veteran.

**Comment by laurwill** [comment]
Hi @eheintzelman , since this content is closely PACT-related, @DanielleThierryUSDSVA is going to do this review. She's at an OCTO offsite this week — is there a deadline you're working against for this content? Thanks!

**Comment by eheintzelman** [comment]
Thank you @laurwill, Would it work for @DanielleThierryUSDSVA to review by April 19th? I'm out the week of 15-19, but I can pick up on the review when I return. That way I can get the terms finalized and off to engineers so that we can realize in early May, which is our goal. Since we know that Veterans are submitting PACT Act claims now, we are trying to get this out ASAP.

**Comment by DanielleThierryUSDSVA** [comment]
Hi there @eheintzelman! I was aiming for this morning, but it will be more like EOD. Just letting you know. Thanks!

**Comment by eheintzelman** [comment]
Hi @DanielleThierryUSDSVA Is the review complete?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @eheintzelman. Yes! Thank you for checking.
