### ISSUE TITLE
SPIKE: How do logouts work with auto-auth logout?

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#68501]

**Comment by achievedaniel** [comment]
References:
[OpenID Logout documentation](https://openid.net/specs/openid-connect-frontchannel-1_0.html)
[OpenID Back-Channel logout](https://openid.net/specs/openid-connect-backchannel-1_0.html)
[Lobgin.gov logout documentation](https://developers.login.gov/oidc/logout/#logout-request)


Based on the Login.gov documentation each service needs to be log out independently. 

> Login.gov does not support Single Logout (SLO). The logout action will terminate the user’s session at Login.gov but will not end any other potentially active sessions within service provider applications. For example, if a user signs in to applications A and B through Login.gov, a logout request from A will end their Login.gov session, but will not affect the session in application B.

Assuming that the issues raised on this spike department-of-veterans-affairs/va.gov-team#68502 there is still an issue with only being able to logout with one service at a time if we are able to auto-auth into new services based on the lack of implementation of the single logout. 

In order to support multiple logouts Login.gov would need to implement Back-Channel Logout this will provide the ability to logout users without their presence. However it doesn't appear that Login.gov has Back-Channel Logout implemented.
