### ISSUE TITLE
SPIKE: What object should /authorize take to confirm user is already authed

### ISSUE THREAD

**Issue by bosawt** [department-of-veterans-affairs/va.gov-team#68500]
* vagov_access_token?
* vagov_refresh_token? 
* some new token?

**Comment by dickdavis** [comment]
Bottom line up-front: **Using the `vagov_access_token` is the most favorable approach as it is the most semantically valid, requires the least amount of developer time, and results in less technical debt/complexity.**

The simplest implementation allowing `/authorize` to determine if a user is authenticated would be to inspect the bearer token in the authorization header. This can be done easily by including the `SignIn::Authentication` concern in the `SignInController` and then loading the user via the `load_user` method. If the user is nil, they are not authenticated.

The `prompt=none` process results in a silently refreshed token pair, which may seem to make the `refresh_token` a fit at first glance. However, none of the other flows refresh the token pair without some form of user interaction, rendering this approach less favorable for semantic reasons. Also, `refresh_token` is not listed as an optional parameter for the authorization request in the spec; this leads me to conclude the authors assume authentication by normal means and did not set aside a special case for authenticating via refresh token when planning the spec.

Using another token is the least desirable approach because it would require the effort and security concerns associated with introducing a new authentication mechanism or the coordination challenges and lack of control associated with adopting a third-party solution.

From my research into the codebase, there is nothing inherently wrong with using the standard authentication check here, and there doesn't appear to be anything in the spec mandating or suggesting an alternate authentication scheme be used. My recommendation is to authenticate via `vagov_access_token`.
