### ISSUE TITLE
[Design, FE] 10-10EZR - V2 form: SHOULD feedback - Content update on Review page for instructions

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#68670]
## Background
During Midpoint review, we received [SHOULD feedback on the Review page](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68507).  

>Review Pages
>- All pages: The VFS team should provide the user with instructions between the header “Review” and the list of toggles.

## Tasks
- [ ] DESIGN - Update design content for the Review page
- [ ] Frontend - Update the UI content for the Review page

## Acceptance Criteria
- The SHOULD Content feedback item has been addressed

**Comment by aliyahblackmore** [comment]
**Tracking the response to feedback here:**

**Noting that my recommendation is that updates happen before staging. 1010 team will determine if this will be feasible given their timelines - may have to happen V2**

All pages: The VFS team should provide the user with instructions between the header “Review” and the list of toggles. I recommended adjusting the title "Review" to be "Review your updated information." _This adjustment can happen before staging. [This is the comment in the sketch screen](https://www.sketch.com/s/912cab8e-d234-44dd-be1f-2bedb3f50b22/p/AE6DF9B2-59AA-47A8-A038-DD8F238C92DB/canvas?annotation=7431f9ca-315c-48c6-ab81-c83fb8a6cb42)._

**Comment by jessicastump** [comment]
@longmd  - is this possible in the forms library? Was about to mock it up, but thought I recalled a convo that this is not possible...

**Comment by longmd** [comment]
@jessicastump , I was able to update the title for the breadcrumb, as recommended, BUT we cannot add any sort of instructions to the page due to limitations from the lib.

**Comment by hdjustice** [comment]
@aliyahblackmore - Please see the post above, we are limited on what we can do for this finding.

**Comment by aliyahblackmore** [comment]
Hi @hdjustice! Yes, my recommendation here was **only** to update the title to **"Review your updated information."** I didn't recommend adding any instructions to the page.

Since, as Matt mentioned, instructions can not be added to the page due to lib restrictions, I think that my recommendation is a middle ground to address the midpoint feedback. The title that Matt changed, per my recommendation, is now better describing what the user needs to do on the page - which is reviewing their updated information.

I'll adjust my comment above to note that you all can't add instructions due to lib restrictions.

**Comment by hdjustice** [comment]
Ah I gotcha now, thank you for this response!

**Comment by hdjustice** [comment]
@longmd - In this case, we should be able to close this ticket?

**Comment by longmd** [comment]
@hdjustice , yup!! All good to close.
