### ISSUE TITLE
Update & Add Questions to Answer to LoROTA GitHub Page

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#68702]
## Background
There are some concerns surrounding our low-risk one-time (LoROTA) authentication model with respect to future, planned features. Some of these questions include:

- Are we allowed to use LoROTA for these future planned features
- How would LoROTA need to change to accommodate these future planned releases

## Tasks
- Update the [GitHub page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/lorota) to make it easy for others (e.g. Kay) to understand what LoROTA is and how it is used (e.g. LoROTA entry is deleted at the end of the appt day)
- Add questions that must be answered before we can move forward with our planned featured
    - Will the VA allow us to use LoROTA to do a task not associated with the custom-generated link
    -  Will the VA allow us to use LoROTA to view past appointments
    -  Will the VA allow us to use LoROTA to submit a travel claim for a specific appointment
    -  Will the VA allow us to use LoROTA to submit a travel claim for any past appointment

**Comment by brianseek** [comment]
Added this to the doc: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/lorota/readMe.md#a-simple-explanation-of-lorota

**Comment by brianseek** [comment]
I brought up the LoRota questions post in priorities sync, but I think we got the questions answered before the meeting anyway. 

Kay mentioned providing us with a future roadmap for things they would like to use low auth for so that we may try to reverse engineer what we need permissions wise in the future.

@loripusey let me know if my new simple explanation of LoRota helps or if I need to add anything there. We can regroup on anything still outstanding next week

**Comment by loripusey** [comment]
Perfect, I think this gives people the basic understanding.
