### ISSUE TITLE
Update axe in vets-website

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#68728]
# Description
Currently, `vets-website` has the following outdated axe packages --
* @axe-core/react 4.4.3
* axe-core 4.4.3
* cypress-axe 1.0.0

We need to update to versions --
* @axe-core/react 4.8.2
* axe-core 4.8.2
* cypress-axe 1.5.0

# Acceptance Criteria
- [ ] Vets-website CI pipeline shows no regressions in performance or test passes

**Comment by IGallupSoCo** [comment]
Following the above updates for the three Axe packages, the following e2e specs in vets-website are failing locally due to newly detected accessibility violations:

claims-status/tests/e2e/07.appeal-status.cypress.spec.js
Applications/vaos/tests/e2e/flows/community-care-flow/audiology.cypress.spec.js
Applications/vaos/tests/e2e/flows/community-care-flow/podiatry.cypress.spec.js
Applications/vaos/tests/e2e/flows/community-care-flow/primary-care.cypress.spec.js
Applications/vaos/tests/e2e/flows/va-appointment.cypress.spec.js
Applications/vaos/tests/e2e/flows/va-request.cypress.spec.js
applications/vaos/tests/e2e/flows/vaccine-workflow/covid19.cypress.spec.js

The violations fall under two rules:
**aria-required-children** - https://dequeuniversity.com/rules/axe/4.8/aria-required-children?application=axeAPI
and
**list** - https://dequeuniversity.com/rules/axe/4.8/list?application=axeAPI

There is an additional e2e test spec that is now failing locally after the package changes, but it does not appear to be an accessibility violation:
simple-forms/21-0966/tests/e2e/21-0966-intent-to-file-a-claim.cypress.spec.js
The e2e test fails with a 404 error.  I do not understand why accessibility package changes could break a page in this way, but I can investigate further if needed.
