### ISSUE TITLE
[bug discovery] DR | How is CMP handling upstream failures?

### ISSUE THREAD

**Issue by data-doge** [department-of-veterans-affairs/va.gov-team#68756]
## What happened?

- Roughly ~500 Evidence files for NOD and SC generated errors after Lighthouse passed the file to Centralized Mail Portal. 
- Error types include:
    * `max page Dimensions(inches) exceeded`
    * `Unsupported File type (only PDFs are accepted)`
    * `Unidentified Mail`
    * `Non-string values for keys: zipCode`
    * `ZIP Code must be 5 or 9 digits`
    * `Upstream status: Errors: Batch Submitted with all blank Images.;`
    * `Invalid PDF content, part content`
    * `Max File size(bytes) exceeded`
    * `ERR-EMMS-FAILED, Corrupted File detected.`

## What do we need to know?
Questions for Centralized Mail Portal:

1. Is CMP aware of all error types?
2. Is there a handling process for each error type?
3. Does CMP retain a copy of the file for each error type?
4. Does someone reach out to the Veteran to get the evidence? Do we make the submission whole through an existing process, and if so, what is the process?
5. How is the zip code format used to develop the appeal, or correspond with Veterans? When exploring solutions for this type of error, we want to ensure that validation doesn’t cause unintended consequences.

## Action items
- [x] Compile and send questions to Centralized Mail Portal
- [x] Confirm if Centralized Mail Portal has intervention processes in place for each error type
- [x] @data-doge Confirm if evidence files are living somewhere in an S3 bucket (or elsewhere).

## Slack threads and background context
- Link to Slack [thread 1](https://dsva.slack.com/archives/CKUCFQAHJ/p1697134097537579) and [thread 2](https://dsva.slack.com/archives/CKUCFQAHJ/p1698238297544329).

## Definition of done
- [ ] Action items above are completed
- [ ] We know if CMP has a process in place to handle each error and make the submission whole

## Out of scope
- Coding solutions

**Comment by data-doge** [comment]
Lighthouse putting together a list of errors and error types, at which point we can begin prioritizing and spiking.

**Comment by saderagsdale** [comment]
@saderagsdale upload details to the ticket.

**Comment by saderagsdale** [comment]
Sent a reminder to Janet in thread 1 mentioned above to email the list to CMP.

**Comment by saderagsdale** [comment]
@Mottie @anniebtran confirm if today's evidence failures are different types than the ones listed above. If so, please confirm and add a comment here.

**Comment by saderagsdale** [comment]
Following up on yesterday’s convo with CMP (I was on PTO). Here’s what Michael shared from the convo:

Across the upstream errors they’re handled differently:

- ZIP errors are still passed through, it’s just a metadata issue that has a minor effect on automated routing. Folks at CMP correct it, it moves along
- Unidentifiable Mail is handled by people in the same way as with appeals, as we were told previously
- The others (Blank files, corrupt files, and unsupported file types) are generated by either EMMS or Data Dimensions automated services (submissions go BI -> EMMS -> DD -> CMP) and CMP doesn’t follow up at all, the error just gets returned through Benefits Intake.
- The files are retained indefinitely in AWS.

Notes from Zach:

Below are a few actions I would add as likely needing to happen. I'm sure there are more I'm not thinking of. How would you like to track this effort? E.g., a GitHub ticket, ZenHub, google doc, something else?

- Spot-checking records for the Veterans who had errors that CMP does take action on, and confirming that the evidence files we would expect to see, are present.
- If we get positive and successful verification, determine which of the ~500 errors can be removed from the list of errors that require remediation
- Spot-checking records for the Veterans who had errors that CMP does not take action on, and seeing if the evidence files are unexpectedly present.
- If we get positive and successful verification, determine which of the ~500 errors can be removed from the list of errors that require remediation
- Determine what changes we need to make on the [VA.gov](http://va.gov/) and Lighthouse services, and what changes we want to propose to CMP, to better handle these evidence uploads errors moving forward.
-  This could include fixing common error types, changing the way we indicate success or failure to the Veteran at the moment of submission, changing the way the [VA.gov](http://va.gov/) system defines a successful or failed upload to Lighthouse, changing the way Lighthouse communicates successful or failed uploads to consumers, etc.
- Figure out how we want to remediate whatever remains of the ~500 errors so that the impacted Veterans are made whole

**Comment by Mottie** [comment]
@saderagsdale I believe this is a different error. Steve Albers showed [this error message](https://dsva.slack.com/archives/C053U7BUT27/p1699396095827009?thread_ts=1699391690.430119&cid=C053U7BUT27):

> Error: Invalid PDF: unknown.encryption.type.r
> Error: Failed to open input PDF file:....

And an engineer from another team responded with this:

> The current utility we use to unlock password-protected PDFs is not equipped to handle 256-bit encryption, thus the reason for the error and why the attempts to upload failed.
> More details here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/65483#issuecomment-1799581712

**Comment by saderagsdale** [comment]
@Mottie Thank you. Did the Veteran receive an error message when the upload failed? Also to confirm, it sounds like this error occurred multiple times for one individual, right?

**Comment by Mottie** [comment]
We show the Veteran an incorrect password error, which may not be appropriate in this situation. This happened to 2 separate Veterans two times.

**Comment by saderagsdale** [comment]
@Mottie Can you make a bug ticket for this? @anniebtran Sounds like something we need to address with how we're mapping errors.

**Comment by Mottie** [comment]
[Bug ticket created](https://github.com/department-of-veterans-affairs/va.gov-team/issues/69617)

**Comment by HeatherWidmont** [comment]
@saderagsdale is waiting to hear back from Zach on next steps

**Comment by saderagsdale** [comment]
Pinged Zach again today via DM.

**Comment by HeatherWidmont** [comment]
@saderagsdale got a response from Zach & will add the action items to this ticket

**Comment by saderagsdale** [comment]
Considering the first stage of this complete. Next step is to document what we know about the path for each error type and connect with EMMS and Data Dimensions.

**Comment by saderagsdale** [comment]
Created an epic for this effort and added this as a ticket. Need to think through how to break down the discovery. This contributes to a separate effort to map our responses and error messages on the front end.
