### ISSUE TITLE
investigate inbound login from MHV 

### ISSUE THREAD

**Issue by joeniquette** [department-of-veterans-affairs/va.gov-team#68791]
there are reports that people are logging into MHV then clicking on a link to go to va.gov and not being auto logged in. Please investigate.

**Comment by asg5704** [comment]
Do we have more information on which authentication method they used: 1, 2, or 3?

**Comment by joeniquette** [comment]
posted questions in thread: https://dsva.slack.com/archives/CSFV4QTKN/p1698972657350979?thread_ts=1696432043.966989&cid=CSFV4QTKN

**Comment by asg5704** [comment]
Reassigning to @ianmagenta

**Comment by ianmagenta** [comment]
@kingbmike - After doing research and speaking with Alex, I'm opting to close this. The issue some testers are running into is that they have a cookie or a localStorage property from a previous login still set and it's not auto-logging them in when they go to sign in again. I think that the frontend and api are working as expected in this case: a user who has uncleared cookies or localStorage properties from a previous login should not be auto-logged in. 

As Joe mentions in the thread linked above, this is an edge case that actual production users won't likely run into, because the existing code clears these cookies and localStorage properties for them when they log out. In a scenario where their browsers don't clear them properly, they can just log in again.

It's probably much easier for a tester to create this setup where they have leftovers from a previous login, hence why they likely experience this issue more regularly.
