### ISSUE TITLE
CT: Infinite Spinner: Design Review

### ISSUE THREAD

**Issue by desireeturner** [department-of-veterans-affairs/va.gov-team#6879]
Review implementation on staging / production

**Comment by ccruzgra** [comment]
@amyknox, @ksantiagomorgan6 demo'ed to UX the new error functionality and different scenarios on GIBCT, both for standard searches/profile pages and for VET TEC. He explained that they are not including the blue button for returning to the GIBCT landing page in search results and profile pages because you’d see the same error message on the landing page, as well, which renders the button as redundant. UX approved the updates, but suggested tweaking the error message to:

We've run into a problem.
We're sorry. Something went wrong on our end. Please refresh this page or check back soon."

The copy adjustment provides users with a suggested action to follow since the blue button to take them to the landing page is not provided.

**Comment by desireeturner** [comment]
@ccruzgra @amyknox @ksantiagomorgan6 We refrained from "please refresh..." because if they refresh they will just get the same error message again. May be worth discussing.

**Comment by desireeturner** [comment]
@ksantiagomorgan6 @ccruzgra @amyknox We discussed this on the UX-BA sync this morning and agreed to the following error messaging: 

**We've run into a problem.**
We're sorry. Something went wrong on our end. Please refresh this page or check back soon.
