### ISSUE TITLE
[MVP] Figure out what creates the PDFs for Pension form

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#68913]
## Issue Description
When central mail or lighthouse benefits intake API are used, a PDF is created in the process.  

https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?wid=0-1698863820992

For additional context and help, see this:
[https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/pensions/21p527ez#async-and-error-ha[…]for-form-submission](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/pensions/21p527ez#async-and-error-handling-for-form-submission) 

(scroll to "Creates a PDF")

## Acceptance Criteria
- [x] Investigate what creates the PDF when an online Pension form is submitted
- [x] Investigate whether the PDF generation service lives in `vets-api` and doesn't rely on `BGS`
- [x] What is the validation?
- [x] What is the process to change the validation and to send new fields?
- [x] What is the downtime?

**Comment by danlim715** [comment]
Here's a summary of my investigation into the PDF generation of the Pension form and the scope of work that needs to be done in order to accommodate the new version of the form:

**Investigate what creates the PDF when an online Pension form is submitted**
- PDF generation for the pension form occurs via a Ruby gem called `pdf-forms` ([link](https://github.com/jkraemer/pdf-forms/)) and is essentially just a wrapper that invokes `PDFtk` ([link](https://www.pdflabs.com/tools/pdftk-server/)). Using this tool we can retrieve field metadata from PDF form fields, as well as fill in data in each field.
- `vets-json-schema` is the repo where the pension data schema that is defined by us (the devs) resides, and it defines how the data is captured from the front end and validated in the backend. These schemas are being pulled into `vets-api` as a gem, `vets_json_schema`. Details to add new fields/schemas are defined [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/vets-website/creating-form-schema.md) and steps to version and prep for opening a PR are listed in the repo's [README](https://github.com/department-of-veterans-affairs/vets-json-schema/tree/master#readme) file.
- `PdfFill::Forms` is the backend module where all the data mapping logic lives. We take all the data from our schema and map it to fields on the PDF via field keys on the PDF. Additional info on PDF generation and adding new forms is documented [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/pdf-generation).

**Investigate whether the PDF generation service lives in vets-api and doesn't rely on BGS**
- All PDF generation and data mapping logic lives in the `vets-api` repo. All form schema definitions live in the `vets-json-schema` repo. There is no dependency on BGS services.

**What is the validation?**

On form submission, only 3 validations occur on the `SavedClaim` model:
- Form data must not be blank.
- Form data must be a JSON string.
- Form data must match the JSON schema defined in `vets-json-schema`.

**What is the process to change the validation and to send new fields?**
- No additional changes to validations are necessary
- Steps to add new fields to the schema or create a new schema are referenced above. More info on utilizing the forms library can be found [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-using-forms-in-production).
- Steps to creating a new form in vets-api are referenced above. This is probably where the majority of the work needs to be done. The new version of the pensions form is massive compared to the old form. For comparison, the old form was 4 pages (pages 5 - 8) with about 246 uniques fields, but the new form is 10 pages (pages 8 - 17) and has a little over 500 unique fields. A lot of that is due to increase granularity of fields on the new form (i.e. SSNs and phone numbers are split into 3 fields instead of being 1 field). This may or may not have a significant impact on the schema, but we will definitely need to rewrite the vets-api pension form from scratch.

**What is the downtime?**

There should be no downtime since all the changes we need to make live in `vets-api` and `vets-json-schema`, but this rework could potentially increase the scope of what we originally thought needed to be done.

I've also attached the old and new versions of the PDF here as a reference:

[21P-527EZ (old).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFRCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8954b22ba7e83096c2ab6a4804998821917788cd/21P-527EZ.pdf)

[VBA-21P-527EZ-ARE (new).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEhCQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46f76a50d00af9af2ef48317dc38c6ce92fbbb78/VBA-21P-527EZ-ARE%28new%29.pdf)

**Comment by danlim715** [comment]
@emilytheis @va-albers Please let us know your thoughts on this, or if there's something I missed/misunderstood.
