### ISSUE TITLE
How to apply - Benefit applications - design.va.gov documentation

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#69]
This is a macro-level description of the How to apply section of Benefit applications.

Notes. These bullet points are not in any particular order.
- Intro statement - how to apply, how we use SEO
- Important info box - chunked, scannable snippets of critical info pertaining to the majority that apply (including what you need to apply). 
- Structure - what goes above or below the CTA button
- Listing the different methods of filling out the form (emphasizing the optimal path for Veterans), calling out getting help from a human
- How to get help info from a human
- How we set expectations 
-  FAQ accordions about applying at bottom of the page
-  Using the green button
-  Check your status (where would i look for it on the page? / prevent submitting twice)

We should note that it could have some overlap with eligibility or apply now

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by smoonpeyes** [comment]
# How to apply
**_draft_**
This is a high-level description of the “How to Apply” page for benefit applications. The content recommended for the “How to Apply” page may overlap with the “Eligibility” or “Apply now” sections.
 
## Intro text
Intro text is required and describes what the page is about. For the “How to Apply” page, the intro text usually includes the following:
* The benefit(s) the application is for
* The type(s) of users the application is aimed at (Veteran, service member, qualified family member)
* SEO keywords (See [Writing for SEO](https://design.va.gov/content-style-guide/seo).)

## Preparing to apply (informational callout)
On the “How to Apply” page, use the [informational callout](https://design.va.gov/patterns/content-presentation) box to present chunked, scannable snippets of critical information needed by the majority of applicants. For example, 

* describe what a user needs to do before they begin the application 
* list items needed to complete the application (SSN, military history, etc.). Required items should be called out.

Note: The blue [informational callout](https://design.va.gov/patterns/content-presentation) box should only be used for the most important information on the page. Since it includes critical information, the callout should appear near the top of the page.

## How do I apply?
The “How do I apply" section lists possible application methods. It should emphasize the optimal path for Veterans, (which may be how to get help from a human instead of online help.) Some common application methods are:
* Online
   * green CTA button
* By mail
   * Link to the printable application form
   * Instructions for mailing the completed, printed form
* In person
   * link to find nearest VA regional office
* With the help of a trained professional
   * link to get help

## What happens after I apply?
The “What happens after I apply” section sets the user’s expectations about what will happen next in the application process. This section may include:

* Concise content or a link to a page describing what the user can expect after they apply
* A call to action (primary blue button) that allows the user to track the status of their application
* A card that sets the user’s expectation for how long it takes to receive a response

## More information
Include the “More information section” if there is helpful supporting information about applying for the benefit.
* For many short content items, consider using the accordion component to reduce the content on the page.
* For longer content items, consider linking to a separate page. 

## Live examples
* [How to apply for VA health care](https://www.va.gov/health-care/how-to-apply/)
* [How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)
* [How to apply for the GI Bill and other education benefits](https://www.va.gov/education/how-to-apply/)
* [How to apply for a VA pension as a Veteran](https://www.va.gov/pension/how-to-apply/)

**Comment by jaredcunha-usds** [comment]
@smoonpeyes Love the way you broke this down!

**Comment by jaredcunha-usds** [comment]
@smoonpeyes How do you feel about this documentation? I'd to start putting this into a pull request on design.va.gov for a Benefit Applications page under patterns. Won't be merged in until all main sections are ready.

**Comment by smoonpeyes** [comment]
@jaredcunha-usds I think it's in a good place, but for context, I wonder if we should wait to push it with the other sections of the benefit applications?

**Comment by jaredcunha-usds** [comment]
@smoonpeyes I edited your content, but the edit was only knocking the heading levels down by one. I'm putting all of these together into a single so that we can evaluate. I'll let you know when that is ready to view.

**Comment by jaredcunha-usds** [comment]
I've added your content to a draft page on dev-design.va.gov:
https://dev-design.va.gov/patterns/benefit-applications

For any updates moving forward, please edit this page directly using the link in the yellow box at the top of the page.

**Comment by caw310** [comment]
This is over 3 yrs old. closing.
