### ISSUE TITLE
Research and possibly fix primary submission error: Direct Deposits

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#69018]
Errors being researched:
- form.directDeposit.isNull
- form.directDeposit.accountNumber.Size

## Acceptance Criteria
- [x] Determine root cause of errors
- One of the following
  - [ ] New ticket created to fix issue
  - [ ] PR Opened to Fix issue
  - [ ] Comments on this ticket describing why it is not fixable at this time

**Comment by tblackwe** [comment]
[Datadog query link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.submission_id%3A%282425786%20OR%202425790%20OR%202425954%20OR%202430663%20OR%202430680%20OR%202434416%20OR%202434420%20OR%202434425%20OR%202434436%20OR%202434441%20OR%202436916%20OR%202436924%20OR%202436933%20OR%202436940%20OR%202437199%20OR%202437602%20OR%202437637%20OR%202452646%20OR%202454183%20OR%202535780%20OR%202557973%29%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false)

**Comment by freeheeling** [comment]
{"key"=>"**form526.directDeposit.accountNumber.Size**", "severity"=>"ERROR", "text"=>"size must be between 4 and 17"}
- submission IDs: 2545842

{"key"=>"**form526.directDeposit.isNull**", "severity"=>"WARN", "text"=>"Direct deposit information was not provided"}
- submission IDs: 2557973

**Comment by freeheeling** [comment]
**Questions:**
- Account numbers of less than 4 characters appear to be unvalidated, prefilled bank account data provided by a PPIU service provider, raising the question of what, if anything, should be done in this situation
  - leave as is and expect an ERROR?
  - require the Veteran to update?
    - how should this be communicated?
    - should the application submission be blocked until resolved?
- Should account numbers that include non-numeric characters, including spaces, be accepted if the only downstream validation is that "size must be between 4 and 17"?

**Comment by freeheeling** [comment]
**To Do:**
- Confirm whether PPIU service provider is validating number of characters in account number.
- Confirm what types of characters are accepted: letters, spaces, symbols, dash?

**Comment by freeheeling** [comment]
```
LighthousePPIUProvider#get_payment_information
DirectDeposit::Client#get_payment_info
DirectDeposit::Configuration#get("?icn=#{@icn}")
DIRECT_DEPOSIT_PATH = 'services/direct-deposit-management/v1/direct-deposit'
```
Sent [inquiry](https://dsva.slack.com/archives/C03P6C3FYMR/p1709932323405769) to #api-direct-deposit-management regarding account number validation.

**Comment by freeheeling** [comment]
Concerning the [5 instances](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40named_tags.user_uuid%3A%28%2239cec8bc-4f58-4f6f-8cca-30fbf8994003%22%20OR%20%220b95f3c12f484cc199819a48802e28d6%22%29%20%40payload.error_message%3A%2Aform526.directDeposit.accountNumber.Size%2A%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id%2C%40named_tags.user_uuid&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1677444960000&to_ts=1708980960000&live=true) of claim submission failures attributed to account number size violating the 4- to 17-character range, [a response](https://dsva.slack.com/archives/C8R3JS8BU/p1710184095007139?thread_ts=1710177330.247619&cid=C8R3JS8BU) from Michael Harlow was as follows:

> "These requests are too old and failed validation, so the JSON requests are not in the EVSS database. The directDeposit element in the JSON request is optional, so it's unfortunate that it causes errors instead of just a warning when a field is too long."

As such, going to mark these instances as anomalies, the last of which was 6 months ago, and only recommend further investigation be performed if an error arises again where the number of characters in an account number otherwise meets the expected validation. 

With regards to account number validation performed by VA.gov, in a conversation with Tom Harrison, I was informed that authorized users can update their direct deposit information at `/profile/direct-deposit`, and validation of bank account details includes the following criteria:
- VA.gov Frontend:
  - Presence of the account number
  - The account number comprises only digits (0-9)
  - Account number length is under 18 digits
- VA.gov Backend (vets-api):
  - Presence of the account number
  - The account number comprises only digits (0-9)
- Lighthouse Direct Deposit Management API:
  - Validation details are currently unspecified.
-BGS:
  - Validation details are currently unspecified.
  - BGS may generate errors based on additional criteria, such as flagged account numbers, though specifics are not provided.
  
According to Tom, the validation standards within VA.gov (frontend and backend) remain aligned with the previous EVSS validation standards before transitioning to Lighthouse. EVSS might have more validation rules in place than LH does. LH provides a few simple validations, but most of the validation errors seem to be returned from BGS.

Tom confirmed that:
- the C&P DD info is added/updated from the profile in VA.gov and ultimately stored in the BGS system
  - the data flow is `VA.gov <--> LH DD API <--> BGS`
- an account # can be between 1 and 17 digits, which is a front-end validation and is not enforced by the vets-api
- there are validations performed by LH DD API, but for account number, it may only validate that there is a value present and that it contains digits. The swagger docs can be found [here](https://developer.va.gov/explore/api/direct-deposit-management/docs?version=current)
- updating a DD account in staging with an account number of '1' saves successfully

**Comment by freeheeling** [comment]
**Blocked** as I'm uncertain what steps should be taken, if any.

Account numbers of as few as 1 character are allowed for C&P DD info added/updated from the profile in VA.gov, which, according to Tom Harrison, aligns with EVSS validation standards. However, Michael Harlow has confirmed that EVSS has always required account number to be at least 4 characters.

I messaged Tom regarding this discrepancy in hopes of gaining clarity on the matter.

**Comment by freeheeling** [comment]
Response from Lorri Glover from the LH team:

> _In this case, it's the Direct Deposit API that needs to add in validation for minimum 4 numbers in account number. My team has has an item in this sprint to add it..._
> _Our sprint ends April 16 so we can say we will have it deployed no later than 4/16._

**Comment by freeheeling** [comment]
Messaged Tom Harrison to inquire about status of update to Direct Deposit API as docs to not indicate any change.

**Comment by freeheeling** [comment]
Lorri Glover, on the LH team, stated that this is now in the sprint that ends on 4/30. I'll follow up after that date to confirm completion.
