### ISSUE TITLE
Research and possibly remediate happy path failures around form.disabilities

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#69016]
Research and possibly remediate happy path failure 
- form.disabilities.Size
## Acceptance Criteria
- [x] Determine root cause of errors
- One of the following
  - [ ] New ticket created to fix issue
  - [ ] PR Opened to Fix issue
  - [x] Comments on this ticket describing why it is not fixable at this time
  
[Datadog Link](https://vagov.ddog-gov.com/logs?query=%40named_tags.class%3A%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitForm526AllClaim%22%20%40level%3Aerror%20%40payload.submission_id%3A%282437296%20OR%202450206%20OR%202453224%20OR%202475574%20OR%202477636%20OR%202477640%20OR%202477649%20OR%202477659%20OR%202532122%20OR%202532123%20OR%202532125%20OR%202532226%20OR%202532472%20OR%202544008%20OR%202545581%20OR%202557776%20OR%202567525%20OR%202570099%20OR%202575542%29%20&cols=host%2Cservice%2C%40payload.error_message%2C%40payload.submission_id&context_event=AY2JIxEsAAB1aZOJsTXH6QAn&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&viz=&from_ts=1698811200000&to_ts=1707414600000&live=false)

**Comment by freeheeling** [comment]
Took some work, but I was able to get the form in a state, from the review page, where I could submit a claim where each rated disability had a `disabilityActionType` of 'NONE' and no `newDisabilities` were entered. This effectively creates and submits a claim where the translated disabilities value is empty.

Seems to be possible only for veterans with rated disabilities who have previously filed and then, at the review page, change their reason for claim to be a new condition, as opposed to one of their rated conditions.

On the review page, there's the option to select a new condition, but it's not possible to provide any additional information about the condition, neither is there any new condition validation as there is for that same section earlier in the form, other than whether the veteran has ever been a POW.

My theory is that any veteran that has previously submitted a claim is routed to the form review when selecting to continue their application. They then select that they are claiming a new condition, which doesn't prompt any additional information be provided (except for maybe a POW response), before submitting the application again.

Perhaps because that new condition doesn't have any of the required supplemental information, no new primary disabilities are passed in the form data to be translated and added to the final disabilities array.

**Comment by freeheeling** [comment]
- 226 instances of this error in the course of the last year
  - corresponding to 61 unique veterans
    - 32 of which have an `InProgressForm`
    - and 2 others with 2 `InProgressForm`s each
    - each veteran has between 1 and 17 `Form526Submission` records

Case of a particular veteran:
- who has a single `Form526Submission` (2475574)
  - created 2023-12-07 04:06:50.69
  - which failed the primary path due to no new disabilities or increase in rated disabilities being claimed
  - backup claim was submitted 
- and what appears to be the associated `InProgressForm` (9610516) was not deleted
    - created 2023-11-28
    - updated 2023-12-07 04:06:50.47

This could be explained by the fact that an `InProgressForm` submitted via the backup path is not destroyed, as is the case for successful primary path claim submissions. In the case of a backup path submission, a veteran, therefore, would presumably be presented with the option of continuing their otherwise previously backup-path submitted form, being routed to the review page, the next time they access VA Form 21-526EZ, although I'm not certain how to verify that assumption.

I have been able to determine that what causes the `form526.disabilities.Size` error is a submission that doesn't include any new disabilities or increases in rated disabilities.

Some questions stemming from this investigation:
- Should a change be made to the review page that requires supplemental information be included if a new condition is selected, similar to the what's required in the new-disabilities section?
- Should `translate_disabilities` in `EVSS::DisabilityCompensationForm::DataTranslationAllClaim` be modified to **not** strip disabilities with ActionType 'NONE' so that claims may proceed to be processed via the primary path without raising an exception downstream? 
- Should an `InProgressForm` be destroyed when a claim is submitted via the backup path?

**Comment by freeheeling** [comment]
Some questions stemming from this investigation to determine a possible solution:
1. Should a change be made to the review page that requires supplemental information be included if a new condition is selected, similar to what's required in the new-disabilities section?
  - This would require a significant FE update
2. Should `translate_disabilities` in `EVSS::DisabilityCompensationForm::DataTranslationAllClaim` be modified to **not** strip disabilities with ActionType 'NONE' so that claims may proceed to be processed via the primary path without raising an exception downstream? 
  - This depends on whether a claim without any new or increased conditions being submitted is acceptable
3. Should an `InProgressForm` be destroyed when a claim is submitted via the backup path? 

Implementing either of the first 2 changes would prevent this error from reoccurring. The latter deviates from the current process, which may have been instituted with intentionality.
