### ISSUE TITLE
Research Backend Feature Flags

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va.gov-team#6910]
## Problem Space

Given that the CARMA backend service may not be available for connection until July/August
I want to understand what options are available
So that we can still develop and deploy the backend as it is built.

**Comment by kevinmirc** [comment]
So the official Feature Flag functionality is very robust and can accept lots of parameters. There are a couple of details about what we're building that makes it not applicable though:
- (1) We have an unauthenticated feature
The feature flag allows you to narrow down usage by specifying which users can use the feature. Since our feature can be accessed without logging in, the parameters the Feature Flagg uses doesn't help us. The user has to be logged in to be filtered via the parameters.

**Workaround**
So since we can't use the Feature Flag system, we can come up with our own "feature flag".
- (1) Our integration will skip the creation of database entries.
For every record in our database, there should be a related record in CARMA. Since we can't assure that during testing, we'll not be storing any entries in our database until the production release. This will also allow us to make changes without the need to support old database records used for testing. It will also (also) prevent the case of only staging connecting to the DB (for testing) and prod not being connected to the db (which would lead to all sorts of issues).
- (2) The CARMA connection will be stubbed for all submissions
The CARMA library will be written but will not connect to the rest of the app. When we submit a 1010cg, we will just return mock data and not hit CARMA at all. This will allow us to do user and end-to-end testing on without the external dependency.
