### ISSUE TITLE
Design | Profile | VBA maintenance period Alerts | craft new alert to be placed on personal info + DD page

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#69385]
## Background 
We have a maintenance period 11/18-19/2023 that we need to quickly stand up this alert that advises users to an outage 

Danielle is working on language for an alert (on personal info page), we need to coordinate w/Danielle and update sketch files and provide details to FE so this alert can be built 

The alert should display on the main page of the profile (ie. the hub if the hub is the landing page or personal information) and on the corresponding sub page that is impacted by the outage 

## Acceptance Criteria 
- [ ] we've confirmed copy with the appropriate teams and we've coordinated with FE to ensure they have enough information to build the short term maintenance alert

**Comment by andaleliz** [comment]
@mtcA6 just to clarify, this maintenance window coming up is for only DD, correct?

**Comment by andaleliz** [comment]
FYI Danielle let me know she is hoping to have content completed early next week.

**Comment by andaleliz** [comment]
@mtcA6 and @Samara-Strauss I've thought through several options and chatted with Danielle about her thoughts from a content strategy perspective, given that we currently have a stacked alert situation on personal info if a user has a bad address indicator on their account.

My recommendation is on personal information, we prioritize the maintenance alert and don't show the BAI alert during this window. I think this is OK because we'll still have the alert on the contact information page, and we know from analytics that hardly anyone sees the BAI alert anyway.

Overall, the approach I recommend is to:
- Not show the maintenance alert to LOA1 users
- For LOA3 users, on the personal information page, show a dismissible, warning alert [like so, though ignore the copy](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/D130CA92-9C25-46FB-97F2-154AFE6B0591/canvas) (sticking with current V2 style from the design system, since that's what we have elsewhere in profile)
- On the DD page, [use the v2 warning alert we already have in place when the page is down](https://www.sketch.com/s/1a920e73-1dcb-47c4-aae8-08656756c131/p/5B113DB9-0187-4A98-BB9A-6BD34FA97265/canvas), with updated copy once we get it.

How does that sound to you?

**Comment by mtcA6** [comment]
That all makes sense but also want to consider the complexity for @adamwhitlock1 and we should opt for the simplest thing to implement even if it breaks the stacked alert rule. Since this is short term and in reading the metrics Samara shared in the morning, only ~200 people last month had the BAI. I'm not sure breaking the rule and stacking the alerts for one weekend for ~200 profiles will be a terrible thing to do.

We should certainly consider for our longer term solution but feels less urgent to tackle within the short term alert. 

That said, opt for the easiest!
- If swapping is not more complex for Adam to code up, then I say we go for it
- If stacking is less complex than swapping I'd suggest we stack

**Comment by andaleliz** [comment]
@mtcA6 I hear you and definitely don't want to make things more complex for Adam. Let's see what he says.  It kinda feels like I'm being disrespectful if I were to recommend stacking the alerts given the [feedback/guidance I asked for in the design channel](https://dsva.slack.com/archives/C0NGDDXME/p1699480165165799). 

Ultimately, that's a product call and I totally get having to balance _all the things_, and this being a pretty short window of time overall. Either way it sounds like we have viable options to choose from 🎉

**Comment by Samara-Strauss** [comment]
@andaleliz I agree with all your recommendations re: not showing the alert to LOA1 and how you've mocked up the LOA3 experience.

Re: stacking/swapping -- I agree with @mtcA6 that we should do whatever is easiest.

**Comment by andaleliz** [comment]
[Here are the mock-ups](https://www.sketch.com/s/ba254d92-3c3d-4eba-825d-d7f5bda35565/p/D130CA92-9C25-46FB-97F2-154AFE6B0591/canvas) with the content Danielle provided

@adamwhitlock1 do you need any more information from me?

Also, out of curiosity, if the alert is dismissed, is it just for the session?

**Comment by adamwhitlock1** [comment]
This looks great! 

I see the mockup for the personal information page, but does the direct deposit page also show that same language or a more direct message about the tool being down in general since the whole page will be gated and just show the alert?

As far as the dismissible alert, I have it wired up now to persist through the session, so if they refresh the page it will persist, but if they closed their tab or restarted their session it would be shown again. That is probably the most straightforward way of getting it hidden when dismissed, but did you have thoughts on the matter?

**Comment by andaleliz** [comment]
@adamwhitlock1 and I talked over Slack DM about the DD mock-up. I updated that too, just tweaked the language a little bit to be specific to DD since that's the only thing showing on the page (and obviously the person will "have problems using the tool" as stated in the provided copy.
