### ISSUE TITLE
[Design] 10-10EZ - Intro page update: Update the Apply for Healthcare page to align with correct content & pattern

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#69447]
## Background
The [Apply for Healthcare page](https://www.va.gov/health-care/apply/application/introduction) has incorrect content and pattern than what we currently have in Sketch. Please update the page so it follows the [correct pattern and content](https://www.sketch.com/s/dc844743-277e-41d4-81ba-a48fd0743952/p/D1B466E9-348C-4C47-BC86-CC9B46A3B0D9/canvas) (eg. remove the "Have you applied for VA health care before?" alert and update content to match).

#### Resources
- Other EZ Intro page tickets we have
     - #67390 

## Acceptance Criteria
- The 10-10EZ Intro page is updated to align with current content and pattern

**Comment by jessicastump** [comment]
@allison0034 Does this include the use of the subway map pattern component or just the alerts?

**Comment by allison0034** [comment]
You can use the process list, however, confirm with CAIA that the content is correct.

**Comment by jessicastump** [comment]
@allison0034 Is the first heading “What to know before you fill out this form” set and a requirement of the template, or can that heading text be changed? Can also go looking/asking via Slack or Platform office hours too :)

We were leaning towards the route of removing the process list component but wanted to use the h2 headings as the main callouts of the steps before applying - checking eligibility and gathering information.

[Sketch canvas here
](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/p/069789E2-2533-4A81-ABA5-BD8F3A5A0A1E/canvas)

Will review with content/CAIA still too and tagging @aliyahblackmore to loop in too.

**Comment by allison0034** [comment]
@jessicastump would you mind asking this question in the sitewide-content-ia-accessibilty channel? They make that decision. : )

**Comment by aliyahblackmore** [comment]
Thanks for looping me in @jessicastump ! 

I'm sending a chat to the CAIA team about form templates and this intro page!

**Comment by aliyahblackmore** [comment]
Hi folks @allison0034 @jessicastump 

**Updates from me:**

- Danielle is going to chat more with Matt Dingee about the intro page pattern for applications that aren't supporting forms. I'll update you all when she's had that conversation and I'll provide feedback to the intro page content then.

- Re: the "Have you applied for VA health care before?" alert - Danielle shared that there was previously a need for this alert due to there being some folks who were applying for healthcare care again. Before we decide whether to remove this or not, @jessicastump would it be possible for your team to look in to whether there are folks who are submitting a health care application more than once and whether there is any data that points to this alert still being necessary here? 

- @jessicastump re: changes to the H2 "What to know before you fill out this form"  - this may not apply for any future updates we'll make to this intro page, but generally the text in the H2 "What to know before you fill out this form" shouldn't change. There can be additional H2s on the intro page, if needed. Happy to be in further conversation with our copy editor if there are any forms where this pattern is used and there may need to be an adjustment to the H2 "What to know..." But we'd likely want this to remain as is.

**Comment by jessicastump** [comment]
> would it be possible for your team to look in to whether there are folks who are submitting a health care application more than once and whether there is any data that points to this alert still being necessary here?


@hdjustice and @longmd -  Not sure if one of you have historic context here - was the "applied before" alert at the top of the page implemented before or after all the ES introduction page status alerts? From what I can tell looking in tickets/Sketch maybe these status warning alerts solved the original issue?

**Comment by hdjustice** [comment]
@jessicastump - I actually found the [feature info](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/vets-application/product/Feature%20Guide%20for%20HCA%20Duplications%20Update.docx) on this "applied before" alert, which looks like it was implemented along with a bunch of other alerts (all in that same document).  This was ~3 years ago.
There isn't a go-to status page that shows the Veteran whether they have applied before and what is going on with it (before approval or rejection), so this statement might give them at least a place where they can at least feel like they will see 'something'.  However, the other side of that is if a Veteran submitted the application unauthenticated, even if they have a VA.gov account, they will not see a "status" of their application when they log in.  I believe that is a rare use case, but possible.
Not sure where I am trying to go with all this, but overall, the "applied before" question was for encouragement to sign in.

**Comment by jessicastump** [comment]
Thank you for this additional context @hdjustice!! 
We do have the various version where if they applied before, the alert does show more at the top - but yes they have to be signed in first. Let's review the page in the next design and/or content sync and discuss if removing the stepper component and page template helps solve the encouragement to sign in concern or if we need to do something else, like contend adjustments.

**Comment by jessicastump** [comment]
Hi @allison0034 - 
We were going over this in our weekly 1010 team design sync and have a question.
We noticed the 526 form does something similar and has an alert at the top prompting Veterans to sing in first. Is this page also flagged for not aligning with DS pattern guidance?

**Comment by jessicastump** [comment]
Got it, thank you!! This has been a history hunt for sure as this was made before I was on the team. I will update and follow up.

**Comment by jessicastump** [comment]
The [Sketch mock](https://www.sketch.com/s/da85cf44-4503-4e98-834e-ff068b242ef6/a/dgdAa53) is updated with the correct alert usage for review.

@aliyahblackmore I realize you are working on some content updates, but this is existing/placeholder for now.

**Comment by aliyahblackmore** [comment]
Hi @jessicastump ! 

Yes - Danielle is planning to talk with Matt about the intro page pattern (including sign in widget placement).
Can you all hold on pushing this production until she has that conversation? I'll make content updates once I hear back from Danielle. 

Just so I'm following - based on application data, is there no longer a need for the "Have you applied for VA health care" alert?

**Comment by jessicastump** [comment]
Thanks! Yes, this is only the design portion, won't open the FE ticket until all this is sorted out. 
The latest draft is a proposed solution to the alert need. By moving the sign in widget to the top and including the sign in primary button at the bottom, the thinking is this will meet the latest pattern guidance (also following order of the 526 form) and still meet the needs of encouraging to apply.

**Comment by allison0034** [comment]
@jessicastump once you get the proper pattern from Danielle and Matt can you send me a screen shot? I would like to get the DS updated. : )

**Comment by aliyahblackmore** [comment]
Hi @jessicastump and @hdjustice - I have a follow up question about the "Have you applied before?" alert. 

Danielle shared that there was previously a need for this alert **due to there being some folks who were applying for healthcare care again after they already submitted an application.** Could you all confirm if there's data that shows whether or not users are submitting this application more than once?

**Comment by hdjustice** [comment]
Hello @aliyahblackmore! - I copied you on an email to the stakeholders for this.  We don't have any data that would tell us whether duplicates are still an issue, I hope they do

**Comment by aliyahblackmore** [comment]
Hi @hdjustice - great, thanks so much for including me on the email and for the update!

**Comment by jessicastump** [comment]
Still in the process of migrating the design files over - but the [Figma page can be found here](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-16200&mode=design&t=JwZY1vr9IwWyhBez-0) (the area by the green check has been updated)

**Comment by hdjustice** [comment]
Sent followup email on the original request for data from HEC

**Comment by aliyahblackmore** [comment]
@hdjustice Perfect timing (I had a reminder on my calendar to follow up next week). Thanks so much for following up!!

**Comment by hdjustice** [comment]
Based on the response from the HEC stakeholders, there is no data tracking on duplicate applications, however they would like to keep the alert in place.

> At this time there is no data available to confirm this.  However I would recommend  that we continue with the alert.

**Comment by allison0034** [comment]
@aliyahblackmore if you want to keep it, can you please style it with the correct [alert style](https://design.va.gov/components/alert#examples---standard---v1)? You could make is a slim v3 alert style if you change the "Save time and save your work in progress" to a v3. We cannot mix and match v1 and v3 of the same component on a page.

**Comment by jessicastump** [comment]
@hdjustice - A couple of options since we also heard back from stakeholders too.
- [Figma link here](https://www.figma.com/file/UljiHam46o5DItC5iDgmPd/10-10EZ?type=design&node-id=0-16200&mode=design&t=UHuO59ke8LoHBZnU-0) (first two options on the far left of the Progress List Template section)
- Option 1: Still have 2 alerts, one at the top using the v3 slim alert style and the second alert at the bottom of the page using the v3 sign in alert
- Option 2: One alert, keeping the main alert at the top - but it is the standard v3 sign in version

And then hopefully we can close out this ticket :)  and open the FE one needed

**Comment by hdjustice** [comment]
@jessicastump - Let's go with Option 1. 
This decision is based on the HEC stakeholders requesting to keep the prompt for those who have applied already to sign in, and also having two touchpoints (top and bottom) for signing in helps reduce scrolling, especially on a mobile device.

**Comment by aliyahblackmore** [comment]
Hi all - just catching up on this ticket! 

I'll take a closer look next week and just confirm with Danielle that we'll leave the alert given the SME reply.
cc @jessicastump and @hdjustice

**Comment by jessicastump** [comment]
Wanted to circle back to this to see if we can resolve this ticket. :)  Is all that is needed is to open a new ticket for the development work on v3 component updates, the design files reflect the correct guidance now? No alert removing/content edits needed. Thanks!

**Comment by hdjustice** [comment]
There are additional logic rework items that need to happen with this update.  Ticket coming soon!

**Comment by aliyahblackmore** [comment]
@jessicastump as we chatted, no alert removal/content edits at this time. You all will open a ticket for the alert component update work. 

And @hdjustice, great I'll look out for that other ticket re: the additional logic.

Thank you all!

**Comment by hdjustice** [comment]
Ticket #75437 created for frontend work to address this and update logic to ensure the V3 web components display and work properly.

**Comment by hdjustice** [comment]
Closing this ticket
