### ISSUE TITLE
[QA] Benefits Delivery at Discharge (BDD) Test Plan

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#6949]
## Product/Feature summary

\[Provide brief summary of product/feature to be tested on Staging by VSA-QA. Also, be sure to include links to the Product/Feature Outline, Epic, and Pre-Launch Checklist.]

Product/Feature Outline: [GitHub doc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/disability/disability-compensation-claim/bdd)

Product/Feature Epics:
- Super: [1834](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1834)
- Design: [4197](https://github.com/department-of-veterans-affairs/va.gov-team/issues/4197)
- Development: [5571](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5571)

Launch Checklist: [5574](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5574)

### Design references
526 Orig Claims flow-mapping ([Mural board](https://app.mural.co/t/vsa8243/m/vsa8243/1585337518279/fd50c081ad0ce756fb4c8ec0ea79ff443024cbc4))
BDD v3 ([InVision prototypes](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens))

## Product-team SMEs

PM: Luke Majewski (@luke-gcio)
Design/Research: Kevin Stachura (@kevinstachura) & Christian Valla (@chrvalla)
Front-end: Nicholas Sprinkle (@ndsprinkle) & Robin Garrison (@Mottie)
Back-end: Sarah Jaine Szekeresh (@SarahJaine)
QA: Tze-chiu Lei (@tlei123)

## Proposed user-scenarios & Staging test-accounts

\[Provide specific user-senarios (all the different interactive usage-flows and/or data-specific states) to be tested.  Or, link to existing issues/docs.]

1. Main Flow (`vets.gov.user+229@gmail.com` (Colder); 228):
    - Will not trigger Missing-info alert.
    - Will not trigger Intent-to-File-already-submitted alert.
    - Has not separated from service.
    - Separation date between 90 and 180 days out
2. Missing-info Alert (test-account TBD):
    - Has not separated from service.
    - Separation date between 90 and 180 days out

## Definition of Done

- [ ] Test Plan & Cases reviewed by Product Team.
- [ ] Test Plan & Cases finalized per review feedback.
- [ ] Actual Test Run(s) completed on Staging, and defects logged.

## How to configure this issue

- [x] Attached to a **Milestone** (when will this be completed?)
- [x] Attached to **Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] Labeled with **Team** (`vsa-authenticated-exp`, `vsa-benefits`, `vsa-benefits-2`, `vsa-caregiver`, `vsa-ebenefits`, `vsa-facilities`, `vsa-public-websites`, etc.)

**Comment by tlei123** [comment]
[TestRail Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/214) started.

**Comment by tlei123** [comment]
@chrvalla @Mottie , pls. let me know how you'd like to go over these test-case questions \[either with a Zoom meeting or just further Comment(s) here].

I updated my ["Main Flow" test-case](https://dsvavsp.testrail.io/index.php?/cases/view/701), and here are the things I couldn't determine based on the [v3 design prototypes](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens): 
- What happens if you click **Yes** for **Have you separated from... service?** \[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421391041)
- Would a 2nd **service-history period** is removable? \[[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421397837)]
- What happens (or where does the form skip to) if you click **No** for **Do you have any new conditions...?** and then **Continue**? \[[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421401836)]
- What happens if you click **Yes** for **Would you like to learn more about addition benefits?** (and what happens if you then click **Continue**)? \[[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421401851)]
- Is the **Add another disability** behavior/functionality on **Summary** form-page the same as on upstream **New Condition(s)**? \[[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421401852)]
- What happens (or where does the form skip to) if you click **No** for **...upload your service treatment records?** AND then **Continue**? \[[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421404547)]
- File-uploads:
  - Is it expected on Staging that file-uploads trigger server-errors?
  - Does clicking **Delete file** trigger confirmation dialog?
- What happens (or where does the form skip to) if you click **No** for **...other evidence** AND then **Continue**? \[[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421405995)]
- What happens if you click **Yes** for **...other evidence**, **Other evidence** for **What type...**, then **Continue**? \[[see this prototype](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421406543)]

It's not that I can't figure most of these out by myself, but for QA we need documentation somewhere (even if it's just with follow-up Comment(s) here in the ticket).

Please let me know.  Thanks much!

**Comment by kevinstachura** [comment]
Hi @tlei123 ! Here are the responses to your above questions:

_1. What happens if you click Yes for Have you separated from... service?_

If you choose 'yes' here, it follows the same pattern as the standard 526. It reveals another question in the gating, seen here:

<img width="785" alt="Screen Shot 2020-06-18 at 10 27 23 AM" src="https://user-images.githubusercontent.com/54544300/85033795-58e29b00-b14f-11ea-811d-450f10f569a5.png">
If the user chooses the first option ("I’m filing a claim for a new condition or for a condition that has gotten worse") then the form simply reveals a button to start the 526 disability compensation form. If they choose the second option("I’m disagreeing with a VA decision on my claim") a date dropdown appears, like so:

<img width="736" alt="Screen Shot 2020-06-18 at 10 28 53 AM" src="https://user-images.githubusercontent.com/54544300/85034182-cd1d3e80-b14f-11ea-8942-db5f13e1482e.png">

If the user enters a date that is less than one year in the past, they are told to file a decision review (as seen above). If they enter a date that is greater than one year in the past, they are asked to file a supplemental claim:

<img width="760" alt="Screen Shot 2020-06-18 at 10 29 23 AM" src="https://user-images.githubusercontent.com/54544300/85034496-29805e00-b150-11ea-9771-e6b7a9067fad.png">


_2. What happens if you click Yes for Did you serve under another name?_

I do not have a visual for this at the moment (need to find a staging user who has not yet established a disability claim) but it simply drops down a field where the user can enter in the other name they served under.

_3. Would a 2nd service-history period is removable?_ 

Absolutely - this is how that looks:

<img width="581" alt="Screen Shot 2020-06-18 at 10 52 15 AM" src="https://user-images.githubusercontent.com/54544300/85036343-08b90800-b152-11ea-92bd-6bbc7ba7da18.png">

The user would either click edit --> remove or they could simply remove at the time they are entering (as seen in the screenshot above).

_4. What happens (or where does the form skip to) if you click No for Do you have any new conditions...? and then Continue?_

This is conditional. If a user does not have a previously existing rated disability, then they essentially must choose 'yes', otherwise they will see this error:

<img width="681" alt="Screen Shot 2020-06-18 at 10 55 53 AM" src="https://user-images.githubusercontent.com/54544300/85036670-69484500-b152-11ea-9de9-221206ca22ac.png">

In the 526 'normal' claim (original claim, primary, secondary claim) - If they have an existing rated disability, and are filing to claim that a disability has indeed gotten worse, they are able to progress to the next screen and choose the rated disability for which they are claiming. 

It is important to note for BDD: this screen is procedurally unnecessary for BDD (since it will be a first time claimant - they **must** add a new disability). However it is so ingrained in the 526 form logic that we must keep it until we find a technically feasible way to remove it.

_5. What happens if you click Yes for Would you like to learn more about addition benefits? (and what happens if you then click Continue)?_

The user will see an added flow that tells them of additional benefits for which they may apply, starting with automobile allowance and adaptive benefits:

<img width="705" alt="Screen Shot 2020-06-18 at 11 02 56 AM" src="https://user-images.githubusercontent.com/54544300/85037535-80d3fd80-b153-11ea-962d-749d7ae8f5fb.png">

This opens up a myriad of choice possibilities via 'sub-forms' within the 526 form. To see the full breadth of possibilities, please refer to the disabilities section in the OC Flow Mapping document located here: 

https://app.mural.co/t/vsa8243/m/vsa8243/1585337518279/fd50c081ad0ce756fb4c8ec0ea79ff443024cbc4



_6. Is the Add another disability behavior/functionality on Summary form-page the same as on upstream New Condition(s)?_ 

Yeah, pretty much. It just happens inline, like so:

<img width="628" alt="Screen Shot 2020-06-18 at 11 09 18 AM" src="https://user-images.githubusercontent.com/54544300/85038201-50d92a00-b154-11ea-8174-4ce929e1b4ce.png">

<img width="589" alt="Screen Shot 2020-06-18 at 11 09 35 AM" src="https://user-images.githubusercontent.com/54544300/85038182-4a4ab280-b154-11ea-8d48-995adbd93138.png">


_7. What happens (or where does the form skip to) if you click No for ...upload your service treatment records? AND then Continue?_ 

So if the user chooses 'no', then they get the warning you see on this page:

<img width="742" alt="Screen Shot 2020-06-18 at 11 13 11 AM" src="https://user-images.githubusercontent.com/54544300/85038553-b4fbee00-b154-11ea-9a64-ec8f852e8fa3.png">

If the user chooses 'continue', the next page they will see is the one to add any other pertinent supporting evidence types:

<img width="586" alt="Screen Shot 2020-06-18 at 11 11 34 AM" src="https://user-images.githubusercontent.com/54544300/85038611-c7762780-b154-11ea-80c3-1dbbc51bb337.png">


**File-uploads:**

_1. Is it expected on Staging that file-uploads trigger server-errors?_

Hmm, let me as @Mottie or @ndsprinkle about this one...

_2. Does clicking Delete file trigger confirmation dialog?_

For supporting evidence, after uploading the document and then immediately clicking the 'delete' button/link, no dialog box is triggered.

_3. What happens (or where does the form skip to) if you click No for ...other evidence AND then Continue?_

It will just take you to the summary of evidence page, seen here:

<img width="758" alt="Screen Shot 2020-06-18 at 11 18 31 AM" src="https://user-images.githubusercontent.com/54544300/85039284-90544600-b155-11ea-86ca-2b2cb4054941.png">



_4. What happens if you click Yes for ...other evidence, Other evidence for What type..., then Continue?_ 

We don't have this mocked up, but it would be very similar to this page seen here:

https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens/421409444

But instead it would contextually say 'other evidence' as opposed to 'private medical records.' Functionality would be the same essentially, but it would be another area where the user could upload other evidence (as explained in the 'which evidence type should I choose?' dropdown on the additional evidence selection screen).


Hopefully this helps a bit, Tze! Please let me know if there's anything else you need from me or the rest of the team.

**Comment by kevinstachura** [comment]
Good afternoon @tlei123 - good news! Our ITF loop issue has been fixed, and BDD is viewable in staging. Take a look:

https://staging.va.gov/disability/file-benefits-delivery-at-discharge-form-21-526ez/introduction

I have success with using user 228 to log in. Please let me know if you need exact credentials or if you have any further questions. Thanks!

**Comment by tlei123** [comment]
@kevinstachura , I have Main-Flow test-case ready for you to preview:
- [Functional test case](https://dsvavsp.testrail.io/index.php?/cases/view/701)
- [Copy/Layout/Links test-case](https://dsvavsp.testrail.io/index.php?/cases/view/707)

@luke-gcio should be able to share TestRail login creds with you to access these cases. Alernatively, feel free to ping me on Slack if you prefer that I set up a screenshare to show them to you.

The Functional test-case has only a few remaining ToDos \[see the Preconditions section at the top] with which I'd need your help to address, but most of the steps have been updated based on answers you provided in your Comment above.

Based on your answers to those Functional-case ToDos mentioned above, I should be able to finalize both that one & its accompanying Copy/Layout/Links case.

Please let me know how you'd like to proceed.  Thanks much!

**Comment by kevinstachura** [comment]
Hi @tlei123 ! So sorry for the delayed response (we're doing usability testing sessions all day on the 26th, 27th and 29th). But that sounds great - I will make an attempt at viewing them in TestRail tomorrow and will ping @luke-gcio for the credentials. I will certainly let you know if I have any questions. Thanks again!

**Comment by kevinstachura** [comment]
Hi, @tlei123  - per @luke-gcio it _is_ possible for users to have/file multiple BDD claims - so the test case where the user is blocked from filing another BDD claim (if one already exists) will not be necessary. Thank you!

**Comment by tlei123** [comment]
New design screens added to [BDD 3](https://vsateams.invisionapp.com/share/8GXOG91ZWNJ#/screens) \[see [Staging Review ticket comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12544#issuecomment-675670053)].

Will update test-cases based on above.  Planning to start test-runs this evening, and finish by tmrw (Wed) evening.

**Comment by tlei123** [comment]
@luke-gcio , test runs done.  QA artifacts generated.

[Test Plan](https://dsvavsp.testrail.io/index.php?/plans/view/214):
- [Coverage for References report](https://dsvavsp.testrail.io/index.php?/reports/view/131)
- [Summary (Defects) report](https://dsvavsp.testrail.io/index.php?/reports/view/132)
