### ISSUE TITLE
Review Async Design options with Stakeholders and create design intent

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#69491]
During a recent volume increase of Veterans attempting to submit their application before the PACT Act deadline it was discovered that the ITF service was overwhelmed and blocking Veterans from continuing with their form.

As part of mitigating this, it has been determined that we want to change the ITF creation to be asynchronous. I.e. if the Veteran gets to the point of the application where an ITF would be created, but the ITF service is unavailable, we should allow the user to continue but queue the ITF creation date-time and backfill as needed.

Scenarios:

Axioms:
1. Never block start of filling out a form (for technical or UX reasons)
2. Never stop a user from submitting a form (for technical or UX reasons)
3. What information does the Veteran need around ITF and when to ensure they don't stop themselves at point due to ITF confusion

Acceptance criteria:

- [x] Review low fidelity mock ups with Octo stakeholders
- [x] Review low fidelity mock ups with other teams using current ITF api for auto creation
- [ ] Collect feedback and create design intent once we have alignment

**Comment by juliepedtke** [comment]
Sharing an update before the holiday - we discussed during DBex Design Sync and reviewed MVP with Shannon and Emily. We have alignment on moving forward with this MVP so that we don't block work on the technical solution, since we're agreed that we never want to block a user from starting or submitting and application. 

We _think_ that the MVP won't prevent us from pursuing future UX improvements, and we're ok with a bit of risk here as the tradeoff to moving more quickly. 

We haven't connected with other teams yet, but will continue to do so as we develop UX improvements that divert from the existing experience, so my understanding is we can move forward with a design intent for the MVP.

**Comment by juliepedtke** [comment]
I'd also propose we combine this ticket with #66903 in our next refinement so there isn't redundancy!

**Comment by juliepedtke** [comment]
Also created a new Mural for ITF work to keep things tidy: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1700602283685/fef07188052ef83487d76762990509d0619626d6?sender=udbd39c1bbebb4ec4d7d08829
