### ISSUE TITLE
SEP walkthrough Rebecca

### ISSUE THREAD

**Issue by RivkaCGates** [department-of-veterans-affairs/va.gov-team#69580]

**Comment by uxrebecca** [comment]
Notes from walkthrough on 11-29:

Lesley and Zach in attendance. (Pop in from Mike Frueh, who works closely with Josh Jacobs in Veteran Benefits Administration (VBA)). Also attending: Rivka, Harold, Emily, Janelle. Martin Caraway did intro and bounced out. DAV is there to show the walkthrough: Steve Wolf, Scott Hope, and Jim Marszalek. 

Have been around a long time, around 20 years or more, when SEP was created, when eBenefits was created, working in regional offices across the country but all in DC. Steve Wolf (assistant service director) in DC uses SEP daily. We love va.gov, but it's for the veteran experience not the VSO experience. They manage regional offices - 265 service officers that are co-lated in regional offices, they work on site (1 day/week telework option). They operate on VA firewall system. They're a "tenant" of the VA in these facilities. A lot of their contact is still face-to-face these days. But also tons of phone interviews, emails (250k emails last year client interaction). They've evolved from in person; during covid went remote and that's when it took off doing everything electronic. 175k claims/year for half a million issues. 98% of that is electronic. Just 2% is on paper still, and usually if a service member drops off a stack of medical records, we give to VA to send to scanning facility type thing. That's why SEP is so important to us from a VSO perspective. Submit through SEP and [quicksmit?]. Anytime we submit through SEP, we get a letter it's an outdated form. It's a ton of work on our part to follow up, we don't see the notice, veteran loses time, it's a pretty serious issue for us. 

The veteran has to initiate the first part of the process: assigning them POA. If the vet is sitting in front of me and hasn't yet assigned me POA, I can't access their information. And on the VA network so can't have the veteran use their computer. The vet needs to go into their eBenefits account, assign DAV as their POA, if they do it right then, the VSO can accept in SEP and have immediate access. So that works if they are in front of a computer. NEED: They need to be able to assign POA from their phone, because they don't have a laptop if they're in person. 

SEP speaks directly to VBMS. Right now we have to search for requests. We need an automatic update virtually when we submit it. Otherwise we have to wait. 

They can't do that Print out 2122, they fill out, there's a POA email address. 

Whether a new claim or supplemental claim. 25 years ago they filed a claim for hypertension, we fill out something and it's supplemental because they . We want to take care of them properly the first time, want to have them on their way. and the only way to do that is to see access to information up front. We don't want to file incorrect things. Need access to their history. 

Flow: searches for veteran , clicks "Actions" dropdown, gets to claims status information. You can look at representative, disabilities, dependents. You can see how many active intent to files, open applications, open claims. Click "Apply" > Online Applications Dashboard. You can add dependent benefits live. If you do it on a paper form, going to take a few days. The main benefit is the connection to VBMS, live. Click "Compensation Benefits." Obviously a big problem is the new SEP needs a way to update VA forms automatically as they come out, otherwise we'll have the same problem - outdated forms get denied by VA. 

Cool thing about SEP is it autofills information about the veteran (social, birth date, gender, contact, etc.) - the autofill is really nice, it's captured withing VBMS (also less likely to have errors). Tells you if the veteran is receiving any type of payment. 

It knows their address by default for scheduling exams, but you can also change the address in case they are traveling or snowbird, etc. Also information/options if they are homeless. 

Intent to File is really important, and goes back to POA question. Without taking any action, created ITF. Veterans do it when they X out of it, they actually have an ITF. ITF can expire and they don't understand that. The ITF process is pretty confusing. The access right away is sooo important, because if their ITF expires tomorrow got to take action today, could use a year of potential benefits. One day could be the difference of one year of benefits. 

We can print and get the veteran to sign ("claimant signature"), and then upload. The signature has to appear on original claims. 

Period of service can be added and updated. (Why isn't this automatically pulled from somewhere?). And National Guard / active duty service. Service separation - assumes they are on a base in the list. There's an "other" option but several bases not on there. Should be ok if you type in a base. 

Military pay question is weird - do you want to receive compensation vs. retirement? Odd and creates more confusion than anything. Same with "do you receive any type of separation etc. pay?

Option under Disability Benefits to "Claim a new disability." Past claims are listed. The auto-complete is useful (e.g. knee condition, left). Claiming PTSD goes to a bunch of other stuff - filing incidents, etc. Stuff about unemployability. Another cool feature about adding treatment information, you select the state and it has a drop-down of treatment centers, good feature pretty self-explanatory. 

Document uploading - adding information supporting the claim. But here's the problem: once I add something, have to indicate why. Under "type" it's a limited list: medical records, treatment record - dental, government - medical, social security, military personnel record, "other." Stuff that's not on there we'd click "other" but you can't provide any context. Need to describe what the document is and why you uploaded it. In VBMS it's just going to say "correspondence," so VSRs often miss these because they don't think they're important. Could label it, like "stressor statement." Could be character limited but need to have a label. We've had cases rated wrong because they missed something labeled "correspondence." 

Right now you can't file a supplemental claim through SEP. SEP captures what a veteran is denied for. If you're filing a supplemental claim, could relate to that. Otherwise cheat the system kind of and use the wrong form? 

Only the veteran can change their information - phone number, etc. 

Issues: permissions. NVSOs (national VSOs) - 265 of them - and 26 transition SOs at military installations. Have to have full SEP permissions, by OGC, otherwise they are limited in what they can access. You can login with your CAC, need to request access through the VA, and new people right now aren't really getting it. 

DMU (Direct Mail Upload) - takes 1-4 days, vs. in SEP it's directly talking to VBMS. We know it's more accurate. Timing is really important, the longer it takes us to do our job the fewer people we can help. VA.gov is excellent, I love it, but there's nothing for VSOs there. We take care of veterans and their families, the more we can work together the better we can care for veterans and their families. 

Logging in as a VSO under my accreditation, but also being able to access my own eBenefits if I want to file a claim. Keeping them separate is important.

7 new requests, a bunch of pending request. They have a case management system they can use and verify information (it's called CMS, it's basically how we track our individual cases, a place to take notes etc. - all manual, it doesn't interact with VA APIs at all), it's like their notes on the actions they've taken for their claimants. You "accept" the request. 

Wouldn't it be great if a veteran could come to their website and request a rep directly through there.

Magic wand? Instantaneous access to VBMS. (Don't have to wait a day). No veteran should go unrepresented, we're going to represent them, we're an organization of veterans helping veterans. We don't need anything other than access to files to properly help them. 

Would be great for a vet to go to vets.gov, submit stuff, and it goes to us. Issue right now is twofold: 7332 verification must be actively clicked (changed in 2015ish?). Veteran has to authorize, and they must do this. The VSO has to then acknowledge the POA. We have to touch it right now. If they don't actively click yes, they can have access to my records. We can accept and be their POA but the VA can't parcel out alcoholism, STDs, etc. - so we have full access or no access to VBMS. If they don't check, the VSO can't get access to their records. Need to get a failure notification - we can't represent someone if we don't have access to their records.
