### ISSUE TITLE
[DA] 10-10CG - Performance Monitoring: Create additional monitoring for the 10-10CG

### ISSUE THREAD

**Issue by hdjustice** [department-of-veterans-affairs/va.gov-team#69676]
## Background
As we have now added additional monitors for the 10-10EZ application, we want to add some more monitors in a similar format for the 10-10CG.

- [x] Research / ID the resources & metrics connected to the CG form within Datadog
- [x] Create visual representations of the health check from the backend proxies for CG
- [x] Create visual representations of the the # of PDF download failures of the CG

controller to target when using a vets_api.statsd.api_rack_request:   "controller:v0/caregivers_assistance_claims"

This includes health checks and download failures.

**Comment by luis-simauchi** [comment]
Notes on Error Handling (from github repo)
If the Veteran cannot be found in MPI, the submission will not go through and the user will be prompted to print and fill out the paper form
The same error page will occur if the submission cannot flow through to CARMA for any other reason
vets-API retries and MuleSoft queing has been implemented as of 9/23/2022. This will greatly reduce submission errors due to system issues, allowing for the application submission to be retried until the system is available. See Ultimate Failure handling process for details in the event that the queuing and retries fail.

**Comment by luis-simauchi** [comment]
CG form is not formatted in the RUM function for Datadog, so views (site pages) do not load the same way that other forms do (such as the EZ form)
SO we will not create a page view funnel for this CG dash.

**Comment by luis-simauchi** [comment]
We are going to amend the vet-api section of the widgets to only include a create submission & POA attachment section. Plus the generic vets-api section

**Comment by luis-simauchi** [comment]
might dedicate a whole section for mulesoft widgets similar to the vets API sections
