### ISSUE TITLE
[FE] SPIKE: Investigate how we would Switch headings and body and icons to v3

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#69829]
## Tasks
- Investigate how we would Switch headings and body and icons to v3
    - How would we switch headings and body (any typography that is not a component) to v3. 
    - How would we switch all icons to v3 (including building, phone, directions)

**Comment by loripusey** [comment]
@benbrasso-agile6 this is now a SPIKE ticket

**Comment by brianseek** [comment]
@benbrasso-agile6 I spent some time digging into this, and I don't think there is a defined USWDS v3 style for headings. I imagine that the DS team will eventually make an update for overall styling at some point but for now I only see work that they have done on individual components. I was going to ask in the DS channel but I want to sync up with a UXer on our team to make sure I understand this first.

For the icons, I notice that they are missing most of the icons we use. See the USWDS icon list here: https://design.va.gov/storybook/?path=/docs/uswds-va-icon--icons#icons

They are missing the road and the building. Not sure that it makes sense for us to use a mix of icon usage at this time. But if you want we can utilize the phone, and chevron. But in the case of the phone it would add some overhead since we have dynamic logic to show the phone vs. building icon leveraging the font-awesome classes.

**Comment by benbrasso-agile6** [comment]
Location_city
Phone
Video-appointment
Directions

**Comment by benbrasso-agile6** [comment]
I think based on this thread, body and headings aren't in storybook yet. 

https://dsva.slack.com/archives/C01DBGX4P45/p1702572272854699

@cgednalske thoughts?

**Comment by brianseek** [comment]
@benbrasso-agile6 thanks for that link to the slack thread. That means there is no work for us other than waiting for DS to make the change since we inherit all of those styles globally.

**Comment by benbrasso-agile6** [comment]
I'd agree, but, do you want to go ahead and do the icons now?

**Comment by brianseek** [comment]
Sure, but did you see my note on available icons? Do you want to refactor the icons that we are using today to ones that ate in the list, or work with DS to get them added? I feel like the won't be inclined to add icons that aren't part of the USWDS. So we could update our building to use `location_city` and the road one to use the `directions` icon that is just road sign looking thing.

**Comment by brianseek** [comment]
yeah lets just chat on it tomorrow with visuals. It will require wireframe and product guide updates and all that since the icons would be changing

**Comment by brianseek** [comment]
closing this ticket, to re-cap body and headings will eventually get update globally by DS and icons will be updated in this ticket: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/71840
