### ISSUE TITLE
[Spike] Document empty/error state logic for VA Video Care on GFE appointment

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#69849]
## Background/Request
Product and UX wants to know how VAOS is currently displaying missing data on details pages. We'll use the information to add and update those patterns in the details page redesign.

We also want to understand the field names and data calls for each data point so we can map these and align with other teams who display appointment data.

### Goal

Document the situations where VAOS doesn't display data, or displays an error state when data is missing from VA in-person appointment details pages. (This does not apply to the list view). Also, capture technical information about the data calls.

### Requirements to Consider

For each data field that can show on the details page of a **VA Video Care on GFE** please provide:
- The services or endpoints that are being called to retrieve the data.
    - The technical name of the field in the data call.
- The logic or error (if any) that triggers missing data states.
- Screenshots of the missing data states.

---

## Tasks
- Answer the following questions for each data point (noted in the table that follows):
  - What (if any) logic is in place to handle situations where the data point can’t be displayed to the user?
     - Note if logic is for an error state or other situation.
     - Please provide screenshots of the details page in each state where data is missing.
     - Please the services or endpoints that are being called to retrieve the data.
     - Please provide the field name used in the data call.

Data points to review for VA In-person booked appointments: 

- Appointment Date and Time      
- Type of Care 
- Modality                
- Provider Name  
- Facility Name             
- Facility Address                            
- Facility Phone Number          
- Veteran Reason For Appointment 

## Time Box
8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by vbahinwillit** [comment]
The following service endpoint is called to retrieve all appointments:

http://localhost:3000/vaos/v2/appointments?_include=facilities,clinics&start=2024-05-16&end=2024-09-14&statuses[]=proposed&statuses[]=cancelled

The technical name of the field in the data call.

Display Name | Technical Name
--- | ---
Video link | telehealth.url
Appointment date and time |  localStartTime
Type of care | serviceTypes
Modality | N/A
Provider name | providers[0].name.given, family
Facility name | location.attributes.name
Facility address | location.attributes.physicalAddress
Clinic | friendlyName or serviceName or null
Location | physicalLocation or null
Facility phone number | extension.clinic.phoneNumber, extension.clinic.phoneNumberExtension or default "800-698-2411"
Veteran reason for appointment | N/A

**NOTE:**
This mapping might change since business logic is being migrated to the middle tier.

Example JSON appointment object returned from API call.
```
{
   id: 1
   type: "appointment",
   attributes: {
      localStartTime: "2024-11-22T18:19:34",
      practitioners: {
         name: {
            family: "Last name",
            given: ["First name"],
         },
         serviceType: "primaryCare",
         status: "booked",
         telehealth: {
            url: "link to join the appointment",
            vvsKind: "MOBILE_GFE",
         },
      },
   },
}
```
**Use cases:**
When type of care is missing, don't display at anything.
When provider is missing, don't display anything.
When facility information not available, display "Facility not available''.
When clinic name missing, display "Clinic not available'.
When current time is more than 30 minutes before the appointment time, the link is disabled
When current time is more than 4 hours after after the appointment time, the ink is disabled
<img width="597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWw2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac2a42322f077543f81bc5830acb90e5d639bae8/localhost_3001_my-health_appointments_10aa456vvs%20%281%29.png" alt="localhost_3001_my-health_appointments_10aa456vvs (1).png" />

When there is no link to join the video, error is displayed
<img width="521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXA2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf447a4f76dc0dc3ae24978e82c4335f09289618/localhost_3001_my-health_appointments_10aa456vvs.png" alt="localhost_3001_my-health_appointments_10aa456vvs.png" />

**Comment by ldelacosta** [comment]
UX and Product will review the ticket.

**Comment by outerpress** [comment]
Added this to the [feature reference](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/feature-reference/appointment-types/va-video-care-on-gfe.md#empty-states-and-alerts) @ldelacosta @JRRoof

**Comment by ldelacosta** [comment]
No additional details needed. Closing out the ticket.
