### ISSUE TITLE
[Spike] Document empty/error state logic for community care request

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#69861]
## Background/Request
Product and UX wants to know how VAOS is currently displaying missing data on details pages. We'll use the information to add and update those patterns in the details page redesign.

We also want to understand the field names and data calls for each data point so we can map these and align with other teams who display appointment data.

### Goal

Document the situations where VAOS doesn't display data, or displays an error state when data is missing from community care request details pages. (This does not apply to the list view). Also, capture technical information about the data calls.

### Requirements to Consider

For each data field that can show on the details page of a **community care request** please provide:
- The services or endpoints that are being called to retrieve the data.
    - The technical name of the field in the data call.
- The logic or error (if any) that triggers missing data states.
- Screenshots of the missing data states.

---

## Tasks
- Answer the following questions for each data point (noted in the table that follows):
  - What (if any) logic is in place to handle situations where the data point can’t be displayed to the user?
     - Note if logic is for an error state or other situation.
     - Please provide screenshots of the details page in each state where data is missing.
     - Please the services or endpoints that are being called to retrieve the data.
     - Please provide the field name used in the data call.

Data points to review for Community Care Requests: 

- Appointment Date and Time      
- Type of Care  
- Provider Information
- Preferred Dates and Times
- Veteran Reason for Appointment
- Veteran Contact Information   

## Time Box
 8 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---

**Comment by vbahinwillit** [comment]
Is this spike for a In-person appointment or CC requests? I see references to 'in-person'.

**Comment by outerpress** [comment]
@vbahinwillit this is for CC requests, I pulled the references to in-person appointments.

**Comment by vbahinwillit** [comment]
NOT DONE YET
The following service endpoint is called to retrieve all appointments:
http://localhost:3000/vaos/v2/appointments?_include=facilities,clinics&start=2024-05-16&end=2024-09-14&statuses[]=proposed&statuses[]=cancelled

**NOTE**: The statuses[]=proposed is used to return all appointment requests.

The technical name of the field in the data call.

- Appointment Date and Time => localStartTime
- Type of Care => serviceTypes
- Provider Information =>
- Preferred Dates and Times => requestedPeriods
- Veteran Reason for Appointment => reasonCode
- Veteran Contact Information => contact
- 

**NOTE:**
This mapping will change since business logic is being migrated to the middle tier.


Data points to review for Community Care Requests: 

- Proposed appointment Dates and Times
This field is always populated since it is a required field when completing the appointment request workflow.      
- Type of Care
This field is always populated since it is a required field when completing the appointment request workflow.      

- Provider Information
The following information is display when provider information is missing:

  - Provider name not available
  - Treatment specialty not available
  - Address not available


- Preferred Dates and Times
This field is always populated since it is a required field when completing the appointment request workflow. However, for appointment request, nothing is displayed since the appointment has not been booked   

- Veteran Reason for Appointment
This information is optional. So, the following is displayed when the information is missing:

  - Reason: Not available
  - Other details: none

- Veteran Contact Information
This field is always populated since it is a required field when completing the appointment request workflow.

**Comment by ldelacosta** [comment]
Team will review the ticket. As of right now, no additional research is needed. 

cc: @outerpress
