### ISSUE TITLE
[MVP] Test how data gets pushed/viewed on PDF the VA business stakeholders receive

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#69927]
## Issue Description
As a Pension team,
we need to see how the VA business stakeholders currently see the PDF generated from an online form submission,
so that we can make an assessment on our next steps for any data mapping efforts.

---
## Tasks
- [x] Test how the data of an online form entry gets pushed to the PDF that VA business stakeholder receive and use to process a claim
- [x] Share findings with Pension engineers and product manager

## Acceptance Criteria
- We will understand how the PDF data is formatted and viewed by the VA business stakeholders when it is not properly mapped to the PDF form fields.

**Comment by danlim715** [comment]
Here's a summary of my investigation:

For this sample application, I had a spouse with 1 dependent child, and it entered the child info in the appropriate field, but the income info was all added in the additional information section.
It seems like theres logic that detects if the provided data exceeds the space given on the form, it will fill in the field with "See add'l info page" and append ALL that data in the additional information section instead of filling in as much of the form as possible and appending the remaining info in the additional information section. Here's the generated PDF:

[21P-527EZ_9_final.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1hiQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fd8144184f0199f3551c84de48ff1a7200d6b44/21P-527EZ_9_final.pdf)
