### ISSUE TITLE
Design Intent - IA Feedback - Employee Experience Team, 21-526EZ, Max CFI

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#69941]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thank you for bringing this to us! It is indeed very thorny...

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- **Links in new window/tab:** If linking out to a page with more information from within the form flow, please open the link in a new tab/window and include a visual and Aria indicator letting folks know it'll open in a new window. The [privacy agreement design system component](https://design.va.gov/components/form/privacy-agreement) is a good example.

### Should 
- **IA placement for more information page:** If there is a separate page with more information, work with CAIA team to locate that page within the VA.gov hierarchy. I'm guessing it would be a page under [Resources and Support](https://www.va.gov/resources/)
- **Placement of maxed out conditions in the list:** I recommend pulling out max-rated conditions into a separate list of conditions on the page for visual emphasis and clarity, with a separate header for scannability. A distinct section would also a good home for an accordion or link to more information about extraschedular ratings. 

### Consider
- **Ability to request increase for maxed-out conditions**: I think the big reason this user flow is so thorny is because the policy/business case it supports is for the one successful applicant rather than for the 19,999 denied applicants. I wonder if the PO would be on board with removing the ability to request an increase for maxed-out conditions via the web at all, given the extreme rarity of exceptions and the number of applicants. Should there instead be language encouraging folks to file an appeal, or to talk with their doctor? Is it better to create additional friction for the action up front, rather than to allow folks to request it easily and have it quickly be denied? 
- **Future state - user flow for schedular exception requests:** It sounds like this is something y'all have thought about as well. Depending on the goals of the VA and the likelihood of other maximum-rated conditions being included down the road, perhaps a second workflow would eventually be in order, walking folks through an exception workflow and asking for additional documentation. This would indeed be a big lift **and** how might thinking about a future workflow like this impact the design decisions today?
- **Including links to information about maxed out rating on subsequent pages** - if possible/relevant, are there ways to show the information about maxed out ratings on subsequent pages of the form flow? So, if someone still selects a maxed-out condition and proceeds through the flow, could the additional information or link to a separate page be displayed on subsequent pages? This might help folks to remind themselves of the type of documentation they would need to submit.

**Comment by carodew** [comment]
## Must
Links in new window/tab: 

* We're a bit out from coding this, but I've added a visual indicator and notes for engineers regarding how to handle this: 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/10144074/69ae40d3-f0d2-4c44-9a11-1345692c7b79)


## Should
IA placement for more information page: If there is a separate page with more information, work with CAIA team to locate that page within the VA.gov hierarchy. I'm guessing it would be a page under [Resources and Support](https://www.va.gov/resources/)
* This is in progress with CAIA 

Placement of maxed out conditions in the list: I recommend pulling out max-rated conditions into a separate list of conditions on the page for visual emphasis and clarity, with a separate header for scannability. A distinct section would also a good home for an accordion or link to more information about extraschedular ratings.
* Something like this is the ultimate goal but is out of scope for this release. At the moment we only have the max rating available programmatically for tinnitus, so separating that out from the list more strongly implies that other conditions are not at the max rating (which they may be). We have been exploring an LOE and are seeking stakeholder buy in to create a max-ratings service so we can pursue solutions like this one in future releases. 


## Consider
Ability to request increase for maxed-out conditions: I think the big reason this user flow is so thorny is because the policy/business case it supports is for the one successful applicant rather than for the 19,999 denied applicants. I wonder if the PO would be on board with removing the ability to request an increase for maxed-out conditions via the web at all, given the extreme rarity of exceptions and the number of applicants. Should there instead be language encouraging folks to file an appeal, or to talk with their doctor? Is it better to create additional friction for the action up front, rather than to allow folks to request it easily and have it quickly be denied?
* This has not been something our stakeholders have been open to thus far and may be against existing laws/policies. 

Future state - user flow for schedular exception requests: It sounds like this is something y'all have thought about as well. Depending on the goals of the VA and the likelihood of other maximum-rated conditions being included down the road, perhaps a second workflow would eventually be in order, walking folks through an exception workflow and asking for additional documentation. This would indeed be a big lift and how might thinking about a future workflow like this impact the design decisions today?
* Something like this is definitely something we'd consider for the future, in particular whether there is a way to walk people through the process of uploading the required (additional) documentation for an extra-schedular rating. 

Including links to information about maxed out rating on subsequent pages - if possible/relevant, are there ways to show the information about maxed out ratings on subsequent pages of the form flow? So, if someone still selects a maxed-out condition and proceeds through the flow, could the additional information or link to a separate page be displayed on subsequent pages? This might help folks to remind themselves of the type of documentation they would need to submit.
* We did come up with a mock up of this showing additional information on the following page. However we had concerns that the information was coming [much further up in the form flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?wid=0-1690560405651) than the [section where they're uploading documentation](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1686768383603/3f4415dd2ddb71bbd104ebefd92a2c7b553ad792?wid=0-1687360821546), and were worried that expecting Veterans to remember the details of what types of evidence they'd need to upload for the duration of the application flow would be adding too much cognitive load and be a bad user experience. 
* Additionally, right now the evidence upload process is kind of one big 'dump' of information, and there's not always a way to specify which evidence is for which conditions (and in some cases, the same document upload will cover more than one condition). Ideally, we'd have a prompt that says, in effect, "Upload documentation of how this qualifies for extra-schedular," but that would imply a larger redesign of the supporting evidence section. Something we can consider for a future release.
