### ISSUE TITLE
Service period data mismatch

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#69997]
### PROBLEM STATEMENT
This is a watch item re the difference in data in lower environments for eMIS and VA Profile.

**Comment by laineymajor** [comment]
Check to determine the correct QA envs are being used.

**Comment by rmtolmach** [comment]
Mike R. has confirmed ([in this Slack thread](https://dsva.slack.com/archives/C7TE0PFTL/p1700151999730059?thread_ts=1699374680.726619&cid=C7TE0PFTL)) that the data sources are different for eMIS and VA Profile. 

Questions:
Did the VADIR bug only impact "service occupation codes"?

- Why are the calling different QA envs? Is it just for test users? - _see below_
- What if there is some mocking going on? emis calls VADIR and every single response is response is mocked with the same response. 

### Notes from call with Mike:
PPD == pre-prod
VA Profile has `dev` - this is only for the VA Profile team, `int`, `qa`, `ppd`, and `prod`.
VADIR has environments named exactly the same (but they're different envs). The mapping  from QA, PPD, and PROD goes back and forth . BUT VA profile INT goes to VADIR dev env. 
emis has two lowers and they BOTH connect to the VADIR int. (the two lowers are called. CERT and SQA.)

We are calling VA Profile's QA and it maps to VADIR's QA. 

He's wondering if we have a "pre-prod" env (we don't 😞) because when VA Profile connects to VA.gov, we all line up in PPD, so that would be the place to test.  Our staging hooks to VA Profile QA. But our staging is also calling emis which calls VADIR INT. To demonstrate all of this, Mike drew this for us: 
<img width="695" alt="Screenshot 2023-11-16 at 3 33 11 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/10993987/437a521a-f7da-4728-98ad-3f305c318e4c">

So, the data is not guaranteed to match when we call emis and VA Profile in staging. 

**To allow us to test one or two users, Mike has offered to take a couple `edipi`s and make sure the data matches in the INT and QA VADIR envs and then we would have a day to test. After that, there's no guarantee the data would match.**

### Action items
If we determine we want to do this:
- [ ] Find two users that have mismatch data
- [ ] Organize the testing schedule.

**Comment by rmtolmach** [comment]
✅  Test users with edipi `1005123832` and `1007701663` will work for us. 
✅  Meeting with Mike Richard on 11/28

**Comment by LindseySaari** [comment]
Looks good! We have a path forward and a way to unblock our testing!
