### ISSUE TITLE
Apply now  - Benefit applications - design.va.gov documentation

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#70]
This is a macro-level description of the Apply Now section of Benefit applications.

These bullet points are not in any particular order.
- OMB equivalency statement
   - This can be multiple
- Info alert / sign in to save progress
    - sign in prompt
    - What content goes in
    - document what this looks like signed in as well
- Check your status (where would i look for it on the page? / prevent submitting twice)
- Subway map - steps to apply
- Green button - start application. why use green button. what goes above/below
- OMB control pattern (on every page of the form?)
   - Respondent burden
   - OMB control numer
   - Privacy act (link)
- Need help number
- Check your status (where would i look for it on the page? / prevent submitting twice)
- Link to form design pattern thing (however that gets defined)

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by peggygannon** [comment]
@jaredcunha-usds Hello, please see below my write-up on From introduction apply pages. Please let me know if you if you have any questions or need additional information. 


*User Story*
As a user, I need information about what steps I need to take and documents I need to apply for a benefit. 

*Use Case*
 Users can navigate to a form’s introduction page either from a static VA.gov page (Eligibility or How to Apply) or through an online search. 
Since users can navigate to this page from outside of VA.gov,  this page should include benefit eligibility information as well. 

*What is a purpose of a form's introduction page?*
This page gives users step-by-step information about how to apply for a benefit. This page also gives users ways to get help if they are having trouble filling out the form, as well as important information about that specific form or benefit.  

This page also gives users basic housekeeping information about the form such as: 
- The VA paper form that it corresponds to
- Respondent burden (how long it typically takes to fill out the form)
- OMB control number (form's expiration date or update date)
- Privacy act (link)

-------
*Page template*
{page head} Apply for [TK benefit]
Equal to VA Form TK NUMBER (put official form name in parenthesis).

{Sign in message}
Save time—and save your work in progress—by signing in before starting your application
When you’re signed in to your VA.gov account:
We can prefill part of your application based on your account details.
You can save your application in progress, and come back later to finish filling it out. You’ll have 60 days from the date you start or update your application to submit it. After 60 days, we’ll delete the form and you’ll need to start over.
Note: If you sign in after you’ve started your application, you won’t be able to save the information you’ve already filled in.
{Blue button} Sign in to Start Your [benefit] Application
{link} Start your application without signing in

 {end blue box}
**Follow the steps below to apply for [benefit]. **

{subway map}
1. **Prepare**
**To fill out this application, you’ll need your: 
* [example] Your Social Security number 
* [example] copy of DD214
* 
{optional}
**[If you have a conditional situation] You may also need:**
*Loreum upsem
* Loreum upsem

**What if I need help filling out my application?** 
An accredited representative with a Veterans Service Organization (VSO) can help you fill out your [claim/application]. 
[Get help filing your claim](/disability-benefits/apply/help/) 

{optional blue box with important info to call out about this application or benefit}
**header **
Content Loreum upsem
{end optional blue box}


2. **Apply**
Complete this [disability/education/pension, etc..] TK benefits form.
After submitting the form, you’ll get a confirmation message. You can print this page for your records. 

3. **VA review**
The content under this heading depends on application or benefit. Some examples: 

We process applications in the order we receive them. We may contact you if we have questions or need more information. 
OR

The amount of time it takes to review your claim depends on:
	*
	*
	*


4. **Decision**
Once we’ve processed your claim, you’ll get a notice in the mail with our decision.

{boilerplate info. This comes from the paper form or VA stakeholder}
Respondent burden: TK
OMB Control #
Expiration date: 
[Privacy Act Statement] link

{footer}
**Need help?**
For help filling out this form, or if the form isn’t working right, please call VA Benefits and Services at 800-827-1000.
If you have hearing loss, call TTY: 711.

---------
*Ways to improve page?* 
1. As we've modernized forms, the content on the form introduction page has evolved.  I recommended we go back to introduction pages of our earlier forms to ensure parity in content and formatting with our later forms. 
2. For forms that require the user to sign in to fill out, I recommend we review the form introduction page to see if any additional eligibility requirements need to be added to the page. This is to avoid having a user sign in (or create an account to sign in) only to find out that they aren’t eligible for that benefit. 



**Sample Form Introduction Apply page**
Health Care form introduction page: 
https://www.va.gov/health-care/apply/application/introduction
Disability Compensation form introduction page:  
https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction

**Comment by jaredcunha-usds** [comment]
@peggygannon Thanks. I think this might be a good start. Since this content will serve as a section in the benefits application design patterns, we'll probably make some adjustments to some things so each of the sections has some consistency. If there's anywhere you'd like to include screenshots, looks like there might be a few places, can you include them in your content?

**Comment by peggygannon** [comment]
OK, @jaredcunha-usds thanks for your feedback. I can take a look at Layla's format.

**Comment by peggygannon** [comment]
@jaredcunha-usds OK, take 2. Let me know how this format works and if you need me to include any more information. 

------------

## Application introduction apply page

**_draft_**
This is a high-level description of the introduction page for benefit applications. 
## File for [benefit] header
VA paper form equivalency appear under the page header. This shows the equivalent VA paper form 
*Equal to VA Form 21-526EZ (Application for Disability Compensation and Related Compensation Benefits).*

## Sign-in
Message when a user isn't signed in: 
- Lets applicants know that by signing in some information from their profile account could be prefilled into the application and that they can save their work as they go.  
- Gives time on how long the application will be saved for
- Blue CTA button *Sign In to Start Your Application*
- Link to fill out the application without signing in. (For all online applications except for Disability Compensation) 

[screenshot]
![signed out.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/1d5d3f75-9047-44d1-8ebb-93c5c7c25e53)

Message when a user is signed in:
- Lets applicant know they are signed in and can save work as they go
- Green CTA button

[screenshot]
![signed in message.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/a965f3f5-5065-4b54-bfda-5ebb5452e4bb)

## Subway map 
Subway, or process, map (https://design.va.gov/components/process-list) shows the applicant the steps they need to take to apply for a benefit. The headings are action words, short and concise, and consistent across forms. 

**Prepare**
- Gives the applicant the information they’ll need to fill out the form, such as if they need to submit any documentation or provide their SSN, bank information, military history, spouse information, etc. 
- Items that are optional are called out.

**Apply**
We use the same language for this step across all forms: 
*Complete this [benefits] form. After submitting the form, you’ll get a confirmation message. You can print this page for your records.*

Within the **Apply**  header we also include content about how an applicant can get help filling out the form. This message is also consistent across all form introduction pages:

*What if I need help filling out my application? An accredited representative, like a Veterans Service Officer (VSO), can help you fill out your claim.*
[Get help filing your claim] 

**VA Review**
The step tells applicants how much time it takes VA to review the application.  The content under this heading depends on what type of benefit they're applying for. For example: 
{for Health Care) *We process health care claims within a week.* 
(for Education) *We usually process claims within 30 days. We’ll let you know by mail if we need more information.*
(for Disability) *We process applications in the order we receive them. We may contact you if we have questions or need more information.  The amount of time it takes to review your claim depends on:
	*xxxyxlxlx
	*
	*

**VA Decision**
This step tells applicants how and when they will be informed of the status of their application (if denied or approved) and the next steps. It sets the user’s expectation for how long it takes to receive a response.


## Other components on the intro page
Depending on the type of benefit, we sometimes include an alert box with specific info about that benefit (https://design.va.gov/components/alertboxes). 
This is an optional component and should only be used if there is an important benefit or application process to call out to the applicant.  
[screenshot]
![alert box.png](https://images.zenhubusercontent.com/59b0414bb0222d5de476aa22/05c0adb9-7d2d-4040-8d2f-9742273d7771)


## OMB information 
This appears at the bottom of the Introduction page and shows
•	Respondent burden
•	OMB control number
•	Privacy act (link)


## Need help? 
This footer appears on the bottom of every page of the form. It includes phone numbers if an applicant needs more support or has questions about filling out the form. 

## Page examples
https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction
https://www.va.gov/education/apply-for-education-benefits/application/1990/introduction
https://www.va.gov/burials-and-memorials/pre-need/form-10007-apply-for-eligibility/introduction
https://www.va.gov/pension/application/527EZ/introduction

**Comment by jaredcunha-usds** [comment]
@peggygannon I've updated your text, which was just changing some of the heading levels as i put these all into a single page. I'll let you know more about that when its ready.

**Comment by jaredcunha-usds** [comment]
I've added your content to a draft page on dev-design.va.gov:
https://dev-design.va.gov/patterns/benefit-applications

For any updates moving forward, please edit this page directly using the link in the yellow box at the top of the page.

**Comment by peggygannon** [comment]
OK, thank you @jaredcunha-usds Can I close out this issue?

**Comment by jaredcunha-usds** [comment]
Not yet. I'm still keeping track of these on the project board. I'll close them once the pages are no longer a draft.

**Comment by peggygannon** [comment]
@jaredcunha-usds I've made content and image updates to the Apply Now info in vets-design-system-documentation. I think this section is ready to "publish"

**Comment by caw310** [comment]
This is over 3 yrs old so closing.
