### ISSUE TITLE
"Hot topics" area: supply-reorder design UI and approach

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70068]
### User story

As a user who is eligible to reorder ~~CPAP~~ supplies, I want to be invited to do so in a personalized area near the top of the MHV landing page, so that I feel that the VA is proactively helping me maintain my health _without hindering_ my self-directed use of the rest of the page and health tools.

## Acceptance criteria

- Defined MVP of "hot topics" area and potential next iteration(s) if known
- Documented a decision for how to validate the MVP with users to a reasonable degree of confidence – e.g., moderated usability testing, un-moderated testing (controlled release to production), etc.
- Technical feasibility and approach has been documented for integrating supply-reordering data
- ~~MVP of hot topics MVP  ~~space-saving copy changes~~ is implemented behind a feature flag~~

## Tasks

- [ ]

**Comment by dcloud** [comment]
The 2346 form [makes requests to an endpoint](https://github.com/department-of-veterans-affairs/vets-website/blob/0be4d332ab15dd16db581a1f782726b93db11d8a/src/applications/disability-benefits/2346/actions/index.js#L39-L48), `/v0/in_progress_forms/mdot`, which I haven't found api docs for. There is an MDOT library in vets-api that has a [`determine_eligibility` method](https://github.com/department-of-veterans-affairs/vets-api/blob/4591657f988ba2572c9e61e29e9557b951110bba/lib/mdot/response.rb#L35-L44) , so that might explain the presence of an `eligibility` in the API response


The Swagger documentation includes a ["Create a MDOT supply order"](https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/mdot/addMdotOrder) endpoint, but not other endpoints. 


MDOT is "Medical Device Ordering Tool" per [this PDF](https://www.prosthetics.va.gov/audiology/Form2346OnlineGuide.pdf) (I don't see it used anywhere else).

**Comment by wesrowe** [comment]
Discussion in UX sync today: the cross-tool navigation design (i.e., secondary nave + "four boxes" on landing page) might impact the landing page design. Solving for nav needs to come before hot topics. So we are most likely tabling hot topics for a while.

**Comment by wesrowe** [comment]
@fmccaf1, we decided in planning discussion to table this. If you're not at a stopping point yet, please find a way to put on hold.

**Comment by wesrowe** [comment]
re-closing
