### ISSUE TITLE
Disable Cerner site on Facility page & redirect

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7014]
As a Veteran registered at both Cerner and non-Cerner sites, I need to be alerted and redirected to my "My VA Health" portal on the VAOS Facility page if I try and schedule an appointment at a Cerner location.

## Acceptance Criteria
- [x] User cannot select the Cerner-enable location from the registered Facility list (disabled)
- [x] User is informed they cannot schedule an appointment at this specific Facility
- [x] User is provided link to their My VA Health portal if they want to proceed with scheduling appointment at that specific Cerner-enable Facility
- [ ] Add event tracking to My VA Health portal link

**Comment by rtwell** [comment]
@peggygannon these words can probably use some of your attention. 

![image](https://user-images.githubusercontent.com/12564977/77326951-ee0cf980-6cf0-11ea-8e28-9642f07467a6.png)

**Comment by peggygannon** [comment]
@jbalboni @lenaecb 

Here is  my content recommendation for this page. 
I have a question regarding the radio button options. Can we add the name of the VAMC associated with the VA health system?   

For example, for VA Spokane should we say instead, VA Spokane, Mann-Grandstaff, since the alerts we'll be using for Cerner sites use the VAMC name, not the health system name. 

-------

You’re registered at the following VA health systems. Please choose where you’d like to schedule your appointment. (*Required)

{radio buttons}
-VA Cheyenne
-VA Spokane, Mann-Grandstaff

{validation message if they choose a Cerner site}
To schedule a VA appointment at this location, go to [My VA Health].

**Comment by jbalboni** [comment]
@peggygannon We currently just show the VAMC name, I think. Ryan's mock isn't using real data.

**Comment by jbalboni** [comment]
@peggygannon What you're describing sounds different than the way @rtwell designed it. I put your message in all the different presentations we could use on this page. Which one is the one we want to use (or start from)?

Inline radio message
![Screen Shot 2020-03-24 at 4 16 35 PM](https://user-images.githubusercontent.com/634932/77474120-edf22400-6dec-11ea-94db-9d46ff2879ff.png)

Validation message
![Screen Shot 2020-03-24 at 4 31 15 PM](https://user-images.githubusercontent.com/634932/77474112-e9c60680-6dec-11ea-985d-a32ba9bec3c2.png)

Alert message
![Screen Shot 2020-03-24 at 4 28 19 PM](https://user-images.githubusercontent.com/634932/77474115-eb8fca00-6dec-11ea-8034-bbe725cc3396.png)

**Comment by jbalboni** [comment]
Final decision was this:

![Screen Shot 2020-03-24 at 4.40.54 PM.png](https://images.zenhubusercontent.com/599c94608f62dc7798c3b2cd/b33040a6-3f52-49dd-a87a-85c07b21f09f)
