### ISSUE TITLE
[MVP] Confirm uploaded documents for Lighthouse Benefits Intake API migration

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#70376]
## Issue Description
**User Story**

As a Pension team, **we want to kickoff engineering build efforts to migrate the Pension 527 form from `Central Mail API` to `Lighthouse Benefits Intake API`,** so that we can proceed with the goal align with the Benefits Portfolio Strategic Priorities - Focus on increasing stability, performance, and efficiency of our core products by eliminating the loss of VA.gov submissions of any kind.

- Continuation of work from #69023
- We need to fully confirm uploaded documents based on info from Slack thread: https://dsva.slack.com/archives/C053U7BUT27/p1700233242312199

---
## Tasks
- Determine if upload validation should be in the same initial upload job or a second async job
- Determine point for sending confirmation email (currently after initial upload)
- log and notify if there is an upload issue
- update rspec tests

## Acceptance Criteria
- Fully confirm uploaded documents are part of the Lighthouse Benefits Intake API migration

**Comment by vbellissimo** [comment]
cc @mjknight50

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/70376?planning-poker) with Zenhub @mjknight50 @danlim715 @wayne-weibel @TaiWilkin

**Comment by wayne-weibel** [comment]
I believe we will not need to perform any additional engineering for this.  It should be handled via the Datadog integration done as part of the overall polling effort to BenefitIntake https://dsva.slack.com/archives/C053U7BUT27/p1703185269242709

**Comment by wayne-weibel** [comment]
@vbellissimo @mjknight50 
https://dsva.slack.com/archives/C053U7BUT27/p1703185269242709

**Comment by vbellissimo** [comment]
@mjknight50 @wayne-weibel Is this ticket still relevant today or should we re-write or close?

**Comment by mjknight50** [comment]
Right now, the only way we can confirm upload status is via a curl as described here:
https://developer.va.gov/explore/api/benefits-intake/docs?version=current

```
curl -X GET 'https://sandbox-api.va.gov/services/vba_documents/v1/uploads/someGUID' \
--header 'accept: application/json'
```

The polling work that other teams has done updates the status in the database accordingly.   However, this isn't sufficient because we don't have access to the database in production
We really need some way to easily track the status of a given submission via a dashboard or a better integration within datadog to the DB.

For now, this ticket is satisfied, but we will continue to explore this issue.
