### ISSUE TITLE
Display active state on "My HealtheVet" in site header

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#70684]
# User story
As a user on Va.gov, I want to see the "My HealtheVet" link highlighted as my active state when logged in and viewing that page as an authenticated user, so that my experience is consistent across Va.gov and the active page I'm on is clear to me.

## Description
All authenticated pages that fall under the `va.gov/my-health` directory should display an active state on the "My HealtheVet" link in the Va.gov site header. Currently, the landing page does not. We need to fix this and display the active state for users who are on our page. 

Note: this active state can be seen on the Appointments page (pictures below). 

## Acceptance criteria

- Users on the MHV on VA.gov landing page see the blue underline beneath "My HealtheVet" in the site header

**Comment by wesrowe** [comment]
@carlosfelix2, can you share the status of this story? I just checked in Staging, and the active underline is present for My HealtheVet. But it's not present for My VA. I don't know if it was working before or not.

@sterkenburgsara, I don't see the pictures of the example that you mentioned in ticket details. I wondered about it because the underline in Staging right now is such a dark blue I can barely see it even though I'm looking for it. 
<img width="227" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/d463c125-12af-4ac9-a8e8-b00b32b688a5">

Screen shot from My VA:
<img width="240" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/1be2eb1f-9766-4d30-a4d3-6543b1e18ea3">

**Comment by sterkenburgsara** [comment]
Yes, this is correct. We got some feedback in Design Intent from Matt Dingee about this directly during Design Intent, that we should try to way more clearly indicate that we're within this section (like put an entire square over the "My HealtheVet" text like a tab almost, if you will. But for now this is the approved way to indicate active state. 

![Screenshot 2023-11-28 at 6 15 13 AM (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/ae2eb7ab-ecd2-439d-93bf-7c46617b24c1)
![Screenshot 2023-11-28 at 6 14 59 AM (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/d9eb8247-8de3-4180-afd5-b5f4149ff45e)

**Comment by wesrowe** [comment]
the design system changed one of their blues recently, I wonder if they darkened the one we're using for underline. I really think it was more visible before.

I'll write an issue for the backlog.
