### ISSUE TITLE
Midpoint Review - Design Feedback - Ask VA Integration - Ask VA

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#70719]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- Must: You are using action links to navigate back to the form. This was explored however it is not something currently in the DS so you can either use the [approved review page pattern](https://design.va.gov/templates/forms/review) (edit inline) or fill out an [experimental request](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns) and go to the designs system council.
- Must: review the UI for which sign in option you need and update your design. [Sign in required vs not](https://design.va.gov/templates/signed-out-vs-signed-in#possible-states-of-a-contextual-cta).
- Must: as noted in the Design Intent, Consider radio buttons and check boxes instead of a select. If it is more than 10 use a select, less than 10 try to avoid it. I am not sure how many items you have in the select.
- Must: We have an established pattern for card UI with a status. Your content is very similar so follow the UI/placement/style of a [status card](https://design.va.gov/components/card#status-via-label-with-indicator). Work with CAIA and content on aligning content. Eg. do we use :resolved" for other similar statuses or do we say something different? Same for "reply".
- Must: remove the blue background on "There are no attachments" as that is reserved for alerts and featured content for eligibility. 
- Must: Instead of using the word "documents" on the upload section, the [preferred word is "files"](https://design.va.gov/patterns/ask-users-for/files#content-considerations). Our guidelines are updated in the design system, however our images still show "documents", we are working on updating that.
- Matt: I do not have any problems with tabs since I don't have an alternative off the top of my head. You could use a [segmented bar from the US system](https://designsystem.digital.gov/components/button-group/#segmented-button-group) between list view and map view. I agree accordions are not doing the job.

**Comment by tygindraux** [comment]
Hi Allison (@allison0034), thanks for your feedback! We briefly reviewed and everything makes sense to us. We'll update you once we've made changes based on the feedback.

And also, big thanks to Matt for his feedback about the accordions/tabs, we'll explore the segmented bar. If we do move forward with tabs, we'll look forward to testing to see that they are working okay in this context.

**Comment by tygindraux** [comment]
Hi @allison0034, thanks again for your feedback. Here are the updates we've made based on your comments:
- no update needed, but we reviewed [(Sign in required vs not)](https://design.va.gov/templates/signed-out-vs-signed-in#possible-states-of-a-contextual-cta) guidance again
- no update needed, but we understand that if it's more than 10 we should use a select menu, less than 10 we should use radio buttons
- removed the blue background on "There are no attachments"
- updated wording from 'documents' to 'files'
- asked CAIA to help us align status/reply content to other status/reply wording across VA.gov

We added a ticket to our backlog to explore using a [segmented bar/button group](https://designsystem.digital.gov/components/button-group/) instead of tabs. If we change our approach from tabs, we'll let you know.

The only feedback we have a follow-up question about relates to the UI/placement/style of a [status card](https://design.va.gov/components/card#status-via-label-with-indicator). We reviewed the guidance in the design system, however, we feel that in this case rearranging the content to fit this format could be more confusing. This is because:
- we need to include date last updated, which we think makes more sense when it's close/next to status
- since we include a status and date last updated, we think it may be easier to read/more consistent if we left align both labels – this means we have to move the icon to the right of the status instead of the left

Can you let us know your thoughts on these points? Since this is 'must' feedback, I'm going to leave this ticket open until we've resolved this point. Thanks!

**Comment by allison0034** [comment]
@tygindraux I confirmed with Matt Dingee that the card layout you have is ok to use, however I noticed we missed your review page which is using both action links and inline editing. I have updated my feedback and added something around the review page.

**Comment by tygindraux** [comment]
Thanks Allison!

We'll discuss the review page feedback and come back to this ticket to comment on our approach, before we close this ticket.

**Comment by tygindraux** [comment]
Hi Allison (@allison0034)! Thanks again for all your help over Slack yesterday, regarding the review page and options for editing. We thought through all the different options you suggested, as well as some others.

We think the best call is to remove the return links on the review page and just retain inline editing. Certain items (as before) will remain uneditable due to conditionals.

We want to test this to understand whether we're missing a need (for returning all the way back to edit something like your 'category' or 'topic') but our hypothesis is that it's unlikely that these items will need to be changed by the time a user gets to the review page. We see the risk in keeping the return links, particularly because if something is changed in the flow, the user will need to go through basically the entire flow again, due to the number of conditionals that are tied to certain questions and exist in the form.

Anyways, thank you! I'm going to close this ticket now that all must feedback has been incorporated, but, lmk if there's any follow up comments.
