### ISSUE TITLE
Downtime alert behind feature flag

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70803]
## Description

**NEEDED BY DAILY DEPLOY ON THURS, 11/30**

### User story

Placement: landing page only
SM will take care of their own
Mobile will take care of their own

Tools affected: probably NOT Appts

#### DRAFT wording 
Heading: System maintenance may affect some [products/services/links/things???]
Body: My HealtheVet will have scheduled maintenance starting on Nov 30, 20203, at 10:00 pm ET, and will continue until 4:00 am ET.

- Patrick [queried in slack](https://dsva.slack.com/archives/C04DRS3L9NV/p1701281078595179?thread_ts=1701273741.062769&cid=C04DRS3L9NV) about what message MHV NP will display
- this is the VAgov sitewide banner for inspiration/reference:
- 
<img width="917" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/4054752/3ec6021a-2cb6-44ee-a376-3009798d6f30">

## Acceptance criteria

- VA-Alert displayed using warning level, and is not dismissable
- Feature flag driven so that we can switch on/off and re-use in the future

## Tasks

- [ ]

**Comment by laurwill** [comment]
Hi @wesrowe ! Here's suggested content updates — it looks like we usually do start and end times on separate lines. Will that work here?

**Upcoming maintenance on My HealtheVet**
We'll be working on My HealtheVet. This maintenance will last 6 hours. During that time, you may have trouble using some My HealtheVet health tools.
**Start:** Thursday, November 30, 2023, at 10:00 p.m. ET
**End:** Friday, December 1, 2023, at 4:00 a.m. ET

**Comment by laurwill** [comment]
@batemapf doubling for caution makes sense! But we should probably align with MHV. 

Do you want to ask the MHV team if they want to change theirs to 6 hours/4 a.m. instead? Otherwise we can update our version to 3 hours. Let me know what you prefer! cc @DanielleThierryUSDSVA

**Comment by batemapf** [comment]
Let's just stick with the 3hrs. I know suggesting to the team that their 3 hour outage might be a 6 hour outage will cause swirl and I admittedly don't have the heart to deal with it 🙂
________________________________
From: laurwill ***@***.***>
Sent: Thursday, November 30, 2023 10:45 AM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Patrick Bateman ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Downtime alert behind feature flag (Issue #70803)


@batemapf<https://github.com/batemapf> doubling for caution makes sense! But we should probably align with MHV.

Do you want to ask the MHV team if they want to change theirs to 6 hours/4 a.m. instead? Otherwise we can update our version to 3 hours. Let me know what you prefer! cc @DanielleThierryUSDSVA<https://github.com/DanielleThierryUSDSVA>

**Comment by laurwill** [comment]
Sounds good! We hit publish about an hour ago, I'll go update to 3 hours and repub now.

And here's the MHV version for reference: 
Notice: My HealtheVet National, Secure Messaging and Administrative Portals (11/30/23)
The My HealtheVet National, Administrative and Secure Messaging portals will be unavailable on Thursday, November 30, 2023 from 10:00 p.m. Eastern Time (ET) to Friday, December 1, 2023, 1:00 a.m. ET (estimated 3 hours) for maintenance.
Thank you.
