### ISSUE TITLE
Move landing page to isolated app build

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#70837]
**MAY BE BLOCKED on IA dependency in Medications tool**

### User story

As a Cartographers team member, I want our landing page to be built in isolation, so that deploys are done quickly and on-demand with less exposure to unrelated flaky CI steps.

### Notes

See first comment below for[ two in-flight PRs](https://github.com/department-of-veterans-affairs/va.gov-team/issues/70837#issuecomment-1833947641).

**See steps/discussion [here](https://dsva.slack.com/archives/C044WNQT4P9/p1701274912874659?thread_ts=1701272812.524889&cid=C044WNQT4P9)**

> * each app would have to be moved to its own directory, rather than live under /mhv/
> * all shared code in use would have to be either duplicated in the app directory or (ideally) moved under platform

Steps mentioned by Adrian in slack:

- PR to move any used functions from /shared into the app dir
- PR to duplicate the app to the new location and enable isolated app builds
- PR to update app registry (in content-build) to move to the new app location
- PRs to remove the old app dir and clean up the app registry

## Related docs
- https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds
- https://depo-platform-documentation.scrollhelp.site/developer-docs/continuous-deployment

## Acceptance criteria

- Landing page CI is isolated/independent
- Cartographers' steps and learnings are documented to help health tool teams follow our path

## Tasks

- [x] Determine how we should remove `/my-health/about-medications` as a cross-app dependency, understanding that the URL was chosen for IA reasons, per [#issuecomment-1836275393](#issuecomment-1836275393)
Veteran flow through it, including removal of the app from codebase~~
- [ ] Refactor code within `src/platform` to **not** import from `src/applications/mhv/landing-page`. department-of-veterans-affairs/vets-website#27006

**Comment by radavis** [comment]
Documentation on Isolated Application Builds: https://depo-platform-documentation.scrollhelp.site/developer-docs/isolated-application-builds

**Comment by radavis** [comment]
There are some issues we will need to address before taking on this ticket:

### `/my-health/about-medications` 

Currently, there is code within the MHV Landing Page that routes to a component within Medications. The Medications team/IA wanted the above URL path. Because of technical limitations and time constraints, we did a cross-app import and mounted their component within our routes file. We will need to address this in order to make our landing page an isolated application.

**Potential Options**:

* Move the Medications Landing Page component into `mhv/landing-page` -- not ideal
* Move the Medications app code into the MHV Landing Page app code folder -- It's a better solution than the above. However, the Medications team will no longer have their own application folder. Their team would have to be OK with this.
* Move About Medications to a path underneath `/my-health/medications`. e.g. -- `/my-health/medications/about`, and redirect requests for `/my-health/about-medications` to the new path.

### Address shared code with the Mega Menu:

* rewrite `src/platform/site-wide/mega-menu/tests/my-health-link/mega-menu.my-health.cypress.spec.js` to avoid importing from `application/mhv/landing-page`. I believe importing our manifest is OK, but other imports from our landing page should be refactored out.

[Relevant Slack conversation](https://dsva.slack.com/archives/C0581MN69TJ/p1701377408589769)

**Comment by sterkenburgsara** [comment]
Update: [related thread in Medications Slack channel](https://dsva.slack.com/archives/C04PRFEJQTY/p1701456713098739) to gauge timeline for moving /about-medications content to a new URL to unblock this work.

**Comment by wesrowe** [comment]
Refinement notes:
- Way forward: can move about-medications content into Drupal, would solve this
  - need Coulton, Kay and CAIA confirmation on approval and timing
- Consult with Danielle to ensure we have a viable Drupal template

**Comment by dcloud** [comment]
[Per Slack](https://dsva.slack.com/archives/C0581MN69TJ/p1701802762040569?thread_ts=1701698400.364689&cid=C0581MN69TJ):

> Update: cannot use Drupal for authenticated content (it only works for publicly viewable / unauth pages).

We can still temporarily copy the medication landing page, but would need a different approach for where the content will move to in the future since Drupal is out:

1. It can be its own app… 🙁 
2. It moves URLs and lives at a path under `/mhv/medications/`, such as `/mhv/medications/about`

**Comment by dcloud** [comment]
It's done?!
