### ISSUE TITLE
[UX] 10-10EZR: Discovery - Ask HEC about updated Expenses verbiage

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#70968]
As a Veteran, I would like a clear explanation of expenses for my dependents so that I know that information I need to enter.

- [ ] Ask Shana about "Surviving Spouse"
- [ ] Talk to HEC folks about whether or not Surviving Spouse needs to earn income (and any other questions)

**Comment by jessicastump** [comment]
Emailed 12/4: 
The UX team has some clarifying questions around the education expenses questions as we are thinking through how this change will impact the online form flow. We know you are working on the verbiage of these questions now, but our questions are more around the logic and conditionality of the question.
For dependent education expenses (paid by the dependent) question - today that logic appears based off of the dependents age being between 18-23. Is it correct in that the issue is this question logic should not be based off of age but based off of if the dependent reported income that year?
On the question under the deductibles section about education expenses, the draft verbiage stated "surviving spouse", we wanted to confirm that was correct because wouldn't that mean the Veteran is deceased?

**Comment by jessicastump** [comment]
What HEC answered with did not include 'surviving spouse' question. 

> It has taken some time for us to review and research what the appropriate language should be for both forms.  We have received approval to move forward with the following language:
> 
> 10-10EZ
> 
> Current: section IV-2G: EXPENSES PAID BY YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
> Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)


> 10-10EZR
> 
> Current: section IV-14: EXPENSES PAID BY YOU FOR YOUR DEPENDENT CHILD FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)
> Suggested: EXPENSES PAID BY YOUR DEPENDENT CHILD WITH REPORTABLE INCOME FOR COLLEGE, VOCATIONAL REHABILITATION OR TRAINING (e.g., tuition, books, materials)


> Both forms - Definitions of terms used on this form: want to add
> 
> Reportable Income: The minimum amount of gross income required to file a Federal income tax return according to the Internal Revenue Code of 1954 Section 6012(a).

**Comment by jessicastump** [comment]
@alexseelig - Circling back on this ticket, should we put the "surviving spouse" question on hold until... ? January or the next HEC meeting?
