### ISSUE TITLE
User Signed at Date for ancillary forms (form4142, form0781, form8940) should be distinguished from programatic submission date

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#71011]
Currently, User Signed at Date on ancillary forms are being stamped with a date that can sometimes be after the Veteran submitted the 526 application. This can happen under a few different circumstances:

1. In submissions where the form goes through multiple primary path retries but successfully submits through the primary path a day after Veteran submission (rare)
2. Submissions that fail primary path and go through the back up path, sending the pdfs to central mail
3. Submissions that go through batch processing

Actions:
1. Review mechanism for date stamp in each of the above pathways and determine if they are all the same
2. Update mechanism to always use Veteran submission date

A.C.
1. Signed at Date in all three pathways reflects Veteran submission date on ancillary forms ( **form4142**, **form0781**, **form8940** ) regardless of when the submission was 'programmatically' completed 

-- N.B. -- this needs to be fixed before we reprocessing of remaining 526 historical + modern failures...e.g. batch 4

**Comment by tommasina-va** [comment]
Notes from our questions to Austin: Austin Price  [3:42 PM]
Use case 3 is where it was first discovered and the most urgent to solve as it is stopping us from reprocessing the last batch of historical failures. I can ask emily to send us a specific example.
2 is theoretical and I don't know if we have seen one, but the assumption is if it happens during three it could happen in 2 as well.
1 is even more unlikely and we arent sure it the same mechanism (piece of code) would be involved in these (edited)
Austin Price  [3:46 PM]
oh another note, I think this was first discovered on the 4142's and Emily asked to determine if this is happening on the 0781 and 8940 as well. We can ignore the 8940 since it actually isnt live in production. (edited)
