### ISSUE TITLE
[SPIKE] Describe UX for authentication POC

### ISSUE THREAD

**Issue by emily-gullo** [department-of-veterans-affairs/va.gov-team#71061]
Choose a small and typical subset of authentication UX flows to implement in our POC.

### Existing Research Documentation
[Authentication flow spec](https://docs.google.com/document/d/1gQOPIwLmuIMrDXvYEE08XjV3IQfh3jBEEbNN7KNIIJw/edit#heading=h.6rbev4qhc1ag)
[November 14, 2023 - Identity meeting notes](https://docs.google.com/document/d/1RY8nU2rlWlHYClKJcPBvZxIBqQPSLO_Ds_ypRjpxgns/edit)
[10/13 meeting with VSP Identity team](https://docs.google.com/document/d/1ngr2k5vqQcNnnG233kunV-XHE_XG4GcriNZ6kjrR5Kg/edit) + [video recording](https://dsva.slack.com/files/U0428T1EJEA/F061G2SMKDX/identity_team_meeting_recording.mov?origin_team=T03FECE8V&origin_channel=C05SUUM4GAW)

### Output
Contributory documentation in the `authentication POC specification`
Contributory documentation in the `architecture options documentation`

**Comment by nihil2501** [comment]
- **Now**: Decided to proceed with leveraging Sign-In Service (SiS) since we’re leveraging all of the VA.gov platform ([ADR](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73248))
  - Architectural decision record (ADR) is [forthcoming](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/73406)
  - Technical kickoff with the identity team is [forthcoming](https://dsva.slack.com/archives/CSFV4QTKN/p1704925918179709?thread_ts=1704304081.034039&cid=CSFV4QTKN)
- Next: SiS just handles authentication, so the next phase is about [authorization UX](https://docs.google.com/document/d/1gQOPIwLmuIMrDXvYEE08XjV3IQfh3jBEEbNN7KNIIJw/edit#heading=h.m2kg1txwk6zv) and then technical implementation. It involves finding or provisioning a user’s record of accreditation in OGC as well as an associated POA code for them in CorpDB.
  - Slating of this work as our [“First Application Slice” epic](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/72901) is possibly forthcoming
