### ISSUE TITLE
Consider eliminating target="_blank" attributes on links within the page

### ISSUE THREAD

**Issue by mengA6** [department-of-veterans-affairs/va.gov-team#71215]
### Description
The links within the page content (under each collaboration cycle phase) open in a new window since they have target="_blank" on them. I'm finding it disruptive to how I'm trying to navigate (I use modifier keys to open in a new tab / new window when desired). Not sure what consideration took place / what constraints were at play when applying target="_blank" to all these links, but I would recommend not having any target attributes on these links since the audience for this is fairly technical and probably wants to control the link behavior using modifier keys rather than being forced to open the links in a new window (which creates a lot of clutter).

### Relevant URLs
https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/

### Which type of team are you on? (Platform team, VFS team, or Leadership)
VFS team

**Comment by johnny-jesensky-adhoc** [comment]
Hi @mengA6, thank you for flagging this. Our team will take a look and see what might be going on here, and look to correct. 

We'll provide further updates in this ticket.

**Comment by CherylEvans** [comment]
@jknipes @mengA6 Here is the issue: Multiple links connect to Platform pages instead of linking to the Confluence source documentation. I performed an audit to find which links on the page were incorrectly linked to Platform pages vs. Confluence pages by doing the following: Open page -> (E.G., [depo-platform-documentation.scrollhelp.site/collaboration-cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/)) -> Right-click anywhere on the page and select INSPECT -> A developer panel will open up on the right side of the page -> Use Control F (Mac) or whatever 'FIND' function keys for your particular computer's OS -> type what you are searching for on the page (taget="_blank"). It will return every instance of the attribute on the page. Because code can be very touchy, I recommend searching for one word only and not the whole string (target). The up/down arrow will point you to every attribute instance. This tells you which links are tied to Platform pages (incorrect) and which links are tied to Confluence pages (correct).

**Comment by CherylEvans** [comment]
@jknipes @johnny-jesensky-adhoc @mengA6
All CC touchpoint links are updated on the [CC page](https://vfs.atlassian.net/wiki/spaces/CC/overview)
The links open in the same tab when selected once SVP deployment on Monday is complete.
I will update the ticket on Monday to ensure everything performs as expected.

**Comment by CherylEvans** [comment]
@jknipes @johnny-jesensky-adhoc @mengA6 All links now open in the same tab. Closing ticket.

**Comment by CherylEvans** [comment]
Closed.
