### ISSUE TITLE
Midpoint Review - IA Feedback - VYE Team - Verify Your Enrollment

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#71228]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [x] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [x] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Excited to see this app coming to VA.gov! Thanks for bringing it through the Collab Cycle.
- I'm excited to hear that you are including a findability task in your user research.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

#### Standard bottom of page components

Please include a [Need Help?](https://design.va.gov/components/form/need-help) component and a [feedback](https://design.va.gov/patterns/ask-users-for/feedback) component at the bottom of each page. We ask teams working on applications to include these as standard items at the bottom of each page. CAIA's content team might have guidance on what additional specialized information the Need Help? section might include.

#### Juicier "verify" links

Verification links that appear under each monthly subheader should either be turned into [active links](https://design.va.gov/components/link/), or more of the text should be linked. Right now, only the word "verify" is a hyperlink. This is both an accessibility concern (small touch target is more difficult for users without fine motor control), and a link that is harder to understand out of context when scanning the page. The [content style guide for links](https://design.va.gov/content-style-guide/links#link-text) might be helpful here too.

<img width="770" alt="Screenshot 2023-12-04 at 2 52 33 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/862a6239-9f5c-433c-b190-8104505c5a3a">

#### Confirm existing bank information

Ideally, users should be able to determine/confirm that (1) they have banking information on file at all, and (2) it's the correct banking information. The design in Sketch doesn't indicate that there's an account connected; and the button could lead some users to believe that their account is not connected, and that they need to resubmit their information.

<img width="681" alt="Screenshot 2023-12-05 at 10 30 20 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/755248/aa8c4949-8ec6-47e4-89a8-badebd30526d">

Given the limitations of the backend systems y'all are working with, I understand if this isn't feasible right now. In the future, there should be some indication to let users feel secure in knowing that we have the banking information and they're all set; or, if they added/updated their banking information, that their form submission was successful and we have their information on file. 

### Consider

The title for the **Benefits profile** page may be confusing for users. (I was not sure what it meant right away - it took me a minute to understand what the action link "Manage your benefits profile" might do). Is there different wording for what this page, or the link to it from the landing page, might be called? This could be something to explore during user research.

**Comment by cassidy-beach** [comment]
**Must 1:** Standard bottom of the page components. The "Need Help?" component was added to the bottom of the page, as requested. See attached photo. We have not added the feedback component to the bottom of the page. An additional comment will be left with a photo when it is completed. 
**Must 2:** VYE created a large, single button for users to verify their enrollment. See attached photo. This provides context and makes it easier to scan the page. See attached photo. 
**Should:** Cannot be completed because BDN store the banking information, but does not return it to the app (VYE) so users will not see what the banking info is or if the information is on file. 
**Consider:** VYE changed _Benefits Profile_ to _Your Benefits Profile_. VYE users easily found the benefits profile page during moderated and unmoderated testing, so we did not make additional changes. 
![Must 1 71228](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/fdeedb66-d796-4930-b721-8b8f390b369d)
![Must 2 71228](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/fb31d339-cc11-45b8-bedd-e4b46ca9e49f)
![Should 71228](https://github.com/department-of-veterans-affairs/va.gov-team/assets/143453442/9ae66a9e-08f1-4608-a5fa-bfb4dc9cda5e)
