### ISSUE TITLE
Platform Atlas - Create Team types

### ISSUE THREAD

**Issue by RachalCassity** [department-of-veterans-affairs/va.gov-team#71393]
Teams in the VFS Roster do not all belong to VFS. A type should be added to Teams to prevent team members from octo or other products from modifying VFS data.

**Comment by rmtolmach** [comment]
@RachalCassity there's also VES, which I _think_ is slightly different from VFS, but you'd probably want to check that with Clint.

**Comment by LindseySaari** [comment]
I left some comments on [Rachals' PR](https://github.com/department-of-veterans-affairs/platform-atlas/pull/383/files). I've suggested to create a high level table (potentially called `TeamType`) and then doing a belongs_to on the Team records via `team_type_id`. This way, instead of an enum, we could have a belongs_to association. Given this, if we have the TeamType administrative table, the support team could perform CRUD actions on the team types. We will want to be more hands off and allow editing of these record types in the UI instead of having to use rails console for support members who aren't engineers.

**Comment by jennb33** [comment]
Added to the next Sprint (4/11-4/24) so that @LindseySaari and @RachalCassity can meet when they are back in the office to discuss Lindsey's comments, above.
