### ISSUE TITLE
Usability Testing Prep [Profile 2.0] - IA Feedback

### ISSUE THREAD

**Issue by mnorthuis** [department-of-veterans-affairs/va.gov-team#7140]
## User story

VSP IA feedback on Profile 2.0  (Usability Testing Prep stage)

Template prototype we're reviewing: https://vsateams.invisionapp.com/share/Z8W8ACWN3UG#/

## Prototype feedback

1. There is no change to the breadcrumb with each nav selection - is this intended to be a single dynamic page?
  a. If yes, the user test should include a task that asks users to return to the main page to see if they attempt to go to the breadcrumb or back button. 
  a. If yes, then the mobile version testing should look for feedback/issues around knowing that the page content changed since the page H1 is not visible until you scroll.
  b.  If yes, please be sure that users can deep link to specific content on this page - for example, users should be able to go from the Direct deposit static page directly to the direct deposit info in profile. 
  c.  If no, then breadcrumbs need to be defined
2. Will you be alternating starting with desktop or mobile?  I'm curious if individuals who start on desktop would look for military info differently if they hadn't already been introduced to the profile concept - for example, do they look under Records?

## Definition of Done

- [x] Team acknowledges and provides response to each feedback item
- [ ] IA closes issue once all feedback is implemented or

**Comment by mshea0606** [comment]
Hey @tressaellen , is it safe to close this ticket?

**Comment by tressaellen** [comment]
@mshea0606 not quite.  @mnorthuis - I'm sorry this somehow got buried so this is a little out of order since usability testing has just wrapped up.  But to answer these questions. 

1. We are going to do separate breadcrumbs for each page. I'd assume we'd just use the title of the pages as the breadcrumbs (ie Personal and contact information, Military information, Direct deposit information, Account security and Connected apps) - but let me know if you think this won't work and I can work with Peggy to get something better.

2. We did alternate between desktop and mobile in testing - two participants looked for military information on desktop in the 'records' section.

**Comment by mnorthuis** [comment]
Thank you @tressaellen. Will close this for now and look forward to seeing research results!
