### ISSUE TITLE
[UX] Get Local Review Environment Functioning

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#71439]
## Tasks
- Meet, individually, with Brian or another engineer to resolve your issues with running a branch/review environment locally
    - Goal is for every UX team member to be able to validate the applications in any branch or review environment

## AC

- [x] Zach complete
- [x] Christina complete
- [x] Ya-Ching complete
- [x] Ben complete

**Comment by ytsaoca** [comment]
Big thanks to @brianseek, finished setting up.

**Comment by loripusey** [comment]
@zach-park @cgednalske Any luck with this yet?

**Comment by cgednalske** [comment]
Not yet, but I set up a session today with Brian and Zach, so fingers crossed that will do it 🤞

**Comment by cgednalske** [comment]
@zach-park and @ytsaoca - regarding the Figma work above, we should meet so I can fill you in on a method I stumbled on and have tested in our production file that allows better imports (doesn't connect to library components, but keeps our designs and artboard titles completely accurate otherwise). Going to look for a time today or tomorrow for a quick sync on this.

**Comment by cgednalske** [comment]
@loripusey Brian got @zach-park and I all set up! 🎉 🎉 🎉  Thank you, @brianseek!
