### ISSUE TITLE
[Congressional] V11150327 Due 1/19/2024 (Rep. Diaz)

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#71450]
## Issue Description
The veteran verified his identity with Login.gov. After the verification, the name field in his VA record was populated with the incorrect suffix listed incorrectly as III and it should be II. He has made multiple attempts to get the name reset with no success.
Case Attachments in Folder:  V11150327 - Name correction needed for va.gov (Rep. Díaz) 

---
## Tasks
- [ ] Review congressional correspondence
- [ ] Resolve issue 
- [ ] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [ ] Veteran issue will be resolved or responded to with final answer to issue 
- [ ] Congressional Correspondence will receive details of the resolution 

https://app.slack.com/client/T03FECE8V 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Issue details have been sent to the EVSS help desk manager, Jeremy Haas, by Vicki C. on 12/6/2023. Awaiting rseponse.

**Comment by Kimberley2023-CSM** [comment]
Issue is resolved, see correspondence from Jeremy Haas confirming. 

Victoria,
I can now confirm this issue is resolved.  The EVSS HD was able to confirm this, and the veteran confirmed the resolution as well (attached). The veteran did have a further question about when their suffix was incorrectly changed.  We provided a further reply that we could verify in our logs the incorrect suffix being in place back to 2011, but we do not see who made that change, and have no previous records to that effect.  We also invited Mr. Rodden to contact us should he have any further issues of this nature, so that we can quickly support his needs.  Thank you!
Jeremy
