### ISSUE TITLE
[Bug] Google Analytics Referral Path (not set) for Facility Locator

### ISSUE THREAD

**Issue by nedierecel** [department-of-veterans-affairs/va.gov-team#7164]
## What happened?

The Referral Path for the Facility Locator is `(not set)`, and we expect it to have a value since direct entrances to the page would be very low. 
![image.png](https://images.zenhubusercontent.com/5b295b9ff378ea1890b3d77e/e7606dcd-1e24-48c8-b30b-c3b3f60b32f2)

## Steps to Reproduce
- URL: Visit [Facility Locator report](https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p184317761/explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.referralPath&_r.drilldown=analytics.pagePath:~2Ffacilities~2Findex.html%3FXXX/)

## Acceptance Criteria
- [ ] Identify if Referral Path=(not set) is due to Direct Navigation traffic or an issue with historyChange
- [ ] Communicate fix to Platform Front End OR VFS engineering

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with `Bug`**

**Comment by bsmartin-ep** [comment]
@nedierecel - What would be the expected data for most of these Referral Paths?  _/find-locations/_ with query string parameters?

**Comment by bsmartin-ep** [comment]
@mmiddaugh - I believe this is expected data for the Referral Path - which is the path / file of the external referrer (if it exists).  Are you maybe looking for the _Full Referrer_ or _Previous Page Path_ dimensions?

**Comment by bsmartin-ep** [comment]
@mmiddaugh - Any thoughts on this?

> I believe this is expected data for the Referral Path - which is the path / file of the external referrer (if it exists). Are you maybe looking for the Full Referrer or Previous Page Path dimensions?

**Comment by mmiddaugh** [comment]
@bsmartin-ep I apologize for my delay. I missed your first comment. 
I'm not not exactly following your question. I initially asked how to interpret the (not set) referral path since it represents the vast majority of our traffic. We don't expect veterans are directly navigating to the [Facility Locator search page](https://www.va.gov/find-locations/) but must be arriving from the home page or other areas within VA.gov.

**Comment by bsmartin-ep** [comment]
@mmiddaugh -

(Correct me if I'm wrong @nedierecel ...)

I believe the _Referral Path_ is primarily _(not set)_ because _Referral Path_ refers to the file path on an **external referrer** like google.com or another non-VA site.  Because - like you said - most of our traffic is direct or from VA sites, there is no external referrer and therefore no _Referral Path_.

Here is what it looks like with the Previous Page Path as a secondary dimension...

https://analytics.google.com/analytics/web/?authuser=0#/report/content-pages/a50123418w177519031p184317761/_r.drilldown=analytics.pagePath:~2Ffacilities~2Findex.html%3FXXX&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.previousPagePath/

**Comment by nedierecel** [comment]
@bsmartin-ep That's correct. 

@mmiddaugh to Brian's point, we should look at Previous Page path to leverage how people were arriving to that page within VA.gov.

**Comment by nedierecel** [comment]
Closing this issue since link above has the Previous Page path for reference.

**Comment by mmiddaugh** [comment]
Thank you!
