### ISSUE TITLE
MVI Port Change

### ISSUE THREAD

**Issue by tskinn** [department-of-veterans-affairs/va.gov-team#7187]
## Description

MVI has changed the ports their service listens on in lower environments and will change prod next month.
We need to file a ticket with ESECC

dev: 10.247.96.0/23       -> int.services.eauth.va.gov:9303
staging:  10.247.34.0/23  -> sqa.services.eauth.va.gov:9303
prod:     10.247.32.0/23  -> vaww.esrpre-prod.aac.va.gov:9303

## AC

- [x] fixup lower environments to use the new port so MVI comes back up
- [ ] request access to the new port in prod so we are ready for the cutover when MVI does it in prod

**Comment by wyattwalter** [comment]
Firewall update completed last night for staging, and I'm pushing out the changes now to fixup staging. We need to request all the other environments and get setup for production still.

**Comment by wyattwalter** [comment]
Taking over this ticket to get the rest of the change control board tickets done and environments updated.

**Comment by ricetj** [comment]
@wyattwalter is this done?

**Comment by wyattwalter** [comment]
Not quite. The change control board request was finally approved and firewall rule implemented. Looks like we are good on access, just need to roll out changes on our systems to utilize the new port. Should be done in the next day or so.

**Comment by wyattwalter** [comment]
Update:

- All the lower envs are now fixed up.
- I was able to test the new port for production and it’s reachable. Gonna try to coordinate with someone who knows the app a bit better to be available when we swap that port out. We have until April 23.
- I cannot test that we can reach MVI’s “prod2” network (their DR site) right now because they have nothing listening there until a failover happens. Working on that still with them, hopefully I can convince them to give us something to hit to make sure the connectivity at least works.
