### ISSUE TITLE
Design | Enhanced Military Info | Design Noodling - MOS

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#71889]
## Background 
Work through the designs based on our most recent calls

## Tasks 
- Just include MOS

- attack the design comments from mural board that are feasible to work on
- [dust off the language for the expanded FAQ ](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/uuid/09B5F1B1-EEA5-4C07-AA9C-3A281FD35E74), having DVU values returned from VADIR resulting in missing information is slightly different from an error in the data. 

## Acceptance Criteria 
- [x] refreshed mocks shared out w/the team

**Comment by andaleliz** [comment]
Hi team! I have some refreshed mock-ups to share, and set up a time on Tuesday for us to discuss.  I'll drop some detailed notes here for context (and my sanity), along with links in case you want to review ahead of time. No prob if not.  Danielle and I are still working through FAQ content so that piece isn't part of these notes.

**Note:** I'm noticing some weird rending in Sketch's browser version so if things don't seem sized/aligned correctly, please ignore that at this stage. 


## What I'd like to learn from you
- Where do these designs fall short? There's a lot of complexity with this data and I'm sure I missed something :)
- @tpharrison and @adamwhitlock1 are there technical complexities you see with any of these options that feel overly complicated for an MVP?
- If you have a preference for one over the other, which one and why?

## Assumptions

- We want to take an MVP approach and leverage existing patterns from the profile and design system, instead of designing from scratch and working with untested components.
- Both of the examples in the design system ["Navigate a long list" pattern](https://design.va.gov/patterns/help-users-to/navigate-a-long-list) are accessibility friendly.
- We'll show all the entries for MOS, as long as the `occupationText` and `effectiveDate` are different
- We should show dates along with the MOS because dates matter when it comes to proving toxic exposure.
- We'll want to scale the page to show countries, and more. I primarily explored ideas that I think would scale well if we add another subheading under the branch + dates.

## Options

### A

[Option A-1](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/v/wJMLG9/a/P1npg0d) uses the first example from the design system ["navigate a long list" pattern](https://design.va.gov/patterns/help-users-to/navigate-a-long-list#examples).  This uses a trigger to reveal additional content 5 items at a time, and then it changes to a collapse button once all the content is revealed.  
- An a11y advantage to this pattern is that it gives us the real estate to be specific with the label on the trigger.
- I'm thinking if we were to add countries, or other sections, each section would get it's own trigger. 

With this option, the user has more data up front since the first 5 items are exposed on page load. Because of this, I felt like it was more scannable and scalable to move each period of service (POS) into a separate section like we have on other pages of profile.  I also tried a variation of the main section following the exact pattern we have now (with all POS in one "table"), show in [option A-2](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/L4YyOVd).


### B

[Option B-1](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/g1GeMOx) uses a show/hide button to reveal details beyond the duty status and dates of service. For now, that's only MOS but this could work when we add more content. [B-1.1 shows an example with the details expanded](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/8VO8LRR). 
- Since this design has pretty minimal data showing initially, it felt OK to keep this inside one main section like the page is currently laid out.  
- I tried this pattern with the same kind of chunking shown in option A-1 so you all could see that too ([option B-2](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/27ZL0aQ)).

## Other things I explored
- Early on, I talked with an a11y specialist about using the accordion component as an option.  Ultimately we landed on an expand/collapse button in order to maximize real estate on the screen, avoiding concerns about magnification users finding the trigger and concerns folks w/ cognitive considerations having to interpret what the icons mean on the trigger. 
- I thought about having a page for each period of service, considering there could be a ton of data eventually. Working through the technical implementation + IA considerations felt like more than an MVP solution so I scratched that for now.
- Using [alternating colors](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/3oJ7kAZ) and [borders instead of bullets](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/bLZzwJV). Ultimately, I think the bullets will do a good job helping people scan the page once there are more subheadings (e.g. countries)

**Comment by andaleliz** [comment]
Met with the team today and we've decided to bring both options to design intent, with a slight lean toward the `+5 more` option.  
- The team had some good comments and suggestions, captured in the Sketch file.  No major changes or things to explore, other than Samara's feedback about the duty status getting lost and exploring ways to make that stand out more.
- We will have design intent in the new year, and Pam will attend in my place since I'll be OOO.

@mtcA6 I have about 3 points of exploration/updates left to do in response to the feedback before design intent. Is it better on your end to open a new ticket for that, or just roll this one over? I have no preference and am happy to do whatever is easiest from a PM or velocity tracking perspective.

**Comment by mtcA6** [comment]
@andaleliz rolling over is fine by me, if we initially have a story that goes on longer than we expected, I'm often partial to rolling that ticket so we don't splice the work up. We all make comments where the work is happening so it's easier if it's in one ticket than spliced to multiple. 

The only thing I think we should attempt to be better at in the new year is, when we do roll things over we should discuss why, during our retro. I think this is important since it could be a series of things happening:
- we might need to estimate a bit better 
     - this could also mean we're not discussing our assumptions thoroughly enough during refinement and planning  
     - we should probably as a team discuss definitions of ready and done 
- maybe we need to break tickets down into smaller sections of work 
- maybe it was unavoidable and unforeseeable 

cc: @ACParker89 something to 

For duty status, if we need to explore an experimental design, while more work, it might be a route we consider exploring. How do you feel about a ticket to focus on JUST the duty status in the designs?

**Comment by andaleliz** [comment]
@mtcA6 that's a great idea to start talking about these things in retro.  Thinking through those points makes me realize the AC is satisfied for this ticket, and there's no real need to keep it open.  Iterating based on feedback, including duty status, makes sense to me as a separate ticket. Going to close this one out!
