### ISSUE TITLE
EMIS-VaProfile Monitoring post migration

### ISSUE THREAD

**Issue by laineymajor** [department-of-veterans-affairs/va.gov-team#72216]
### PROBLEM STATEMENT
The migration is complete, but to ensure things are going as expected, our team will be monitoring DD.

### ADDITIONAL INFORMATION
Rebecca to involve DD charts
https://vagov.ddog-gov.com/dashboard/7yz-4e3-6hs/vsp-breakers?refresh_mode=sliding&from_ts=1703074675744&to_ts=1703089075744&live=true

### ACTION ITEMS
- [ ] monitor
- [ ] touchbase with Fred on the emis-deprecation channel to let him know how things are looking before COB 12.21 (prior to code freeze)

### DEFINITION OF DONE
- [ ] no alarming events = stable

**Comment by rmtolmach** [comment]
[this datadog metric](https://vagov.ddog-gov.com/metric/explorer?start=1702417723710&end=1703022523710&paused=false#N4Ig7glgJg5gpgFxALlAGwIYE8D2BXJVEADxQEYAaELcqyKBAC1pEbghkcLIF8qo4AMwgA7CAgg4RKUAiwAHOChASAtnADOcAE4RNIKtrgBHPJoQaUAbVBGN8qVoD6gnNtUZCKiOq279VKY6epbINiAiGOrKQdpYZAYgUJ4YThr42gDGSsgg6gi6mZaBZnHKGniqyIwY8to4xFgAdIL1IghwIlBNXAjyTUZBGhZNCDgIGGjAdQ1YyHCqEBoubQg8AAQARljrwJ0AbhBt6u08TRjLmfjtABQAlCB8oJHRubFYAEyJyRNpGdnKfKFYogd7lSrVWr1RpNTYYTIAa063W2HQ0TXwCFG40m02hcwWSyccMRG22uwORykJzW50u1wQ90eAF0qK53HhMKFwuzVJyMDFSvFHhRQLz+YKdJ8WVRhlg0DlQPJJogOsooDgYE5MlyNBBMok0KI4E45IpyjgjVBDcanPQmMoRG4PGgRUklvJMFhTQociAjSIlDxmTw+CB7EaEABhKTCGAoESctA8IA) shows that total requests to the frontend from `emis_front` dropped to zero at 9:30am yesterday (when we turned veteran_status flipper ON for VA Profile) and same with total bytes from `emis_back`, so that is good and expected.

**Comment by rmtolmach** [comment]
Follow-up on that metric I linked above. There is still something calling emis _in staging_. Click staging in the graph to see it. I did just confirm that our three flippers are all ON in staging, so I'm not sure what's calling it. Prod is still at zero.

**Comment by laineymajor** [comment]
No new concerns to date.

**Comment by laineymajor** [comment]
Work will continue on this during our part 2 of the double sprint.

**Comment by laineymajor** [comment]
There's something still calling staging.
Lindsey thinks it's something with review instances...we think these are where the remaining calls are coming from.

Prod has no more calls coming from EMIS.

**Comment by jennb33** [comment]
Per Lindsey, there are no more calls appearing to eMIS so this ticket will likely close on 1/12/2024. The phantom calls were likely coming from the review instances that were created before the config change.

**Comment by LindseySaari** [comment]
No phantom calls from staging in three days! Closing!
