### ISSUE TITLE
Midpoint Review - Content - Accredited Representation Management: Appoint a Representative + Representative Status Widget MVPs

### ISSUE THREAD

**Issue by rferguson13** [department-of-veterans-affairs/va.gov-team#72335]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts
Overall, this is looking really good. This is a complicated form and the content does a good job of addressing the steps. That said, I think making some tweaks to the subheadings and organization (especially on the landing page) will provide an overall clearer experience for the user.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### Must
- Find and appoint a rep landing page > Intro > Appoint and accredited representative - This section has a lot of information, and the “options” as subheadings seem to come from nowhere. Please revise with clearer subheadings and organization. It’s unclear what needs to be done for each process (paper form vs. online form). 
- Find and appoint a rep landing page > Intro > Appoint and accredited representative - The user finds the prompt: “If you don’t want to use our online tool…you can print and complete one of these PDF forms instead:” Nothing is listed after the colon. Please link the PDFs in a bulleted list after the colon. 
- Find and appoint a rep landing page > Intro > Appoint and accredited representative - If the user wants to use the paper forms, they are given this direction: “Then, submit one of these PDF forms to appoint…” How does the user submit the form? Please revise by adding clarity to the directions. 
- Step 1 > Representative Information > Replace your current accredited representative - When the user already has an accredited representative on file and selects a new one, they are given these headers: “This is your current accredited representative that we’ll replace” and “This is the new accredited representative you’ve selected.” Both of these headers are in the passive voice, which is against the style guide. Having more “active” headers may also help with clarity. Please revise so the headers use active voice.  
  - Or, the content could be changed a bit on this page to act more as a warning text — letting the user know that their current accredited representative will change once they fill out and submit the form. There are several ways the writers could do this. For example, the text could be: “You’ve chosen a different accredited representative than what we have on file. Continuing with this new representative will mean we’ll replace the old one. Are you sure you want to do this?”
- Step 2 > What’s your relationship to the Veteran? - The user finds several options in a list. The “I’m the accredited representative” option is the only one that doesn’t end in a period. Please revise so all answer options are consistent.
- Step 6 - Review and complete - The user finds the following info component: “What happens after I submit my form”. There is no question mark at the end, even though the component is phrased as a question. Please revise by adding a question mark.

### Should
- Step 1 > Representative Information > Enter the accredited representative’s name - The user finds a search bar with the following prompt: “Enter the accredited representative’s name.” However, some of the search results aren’t individuals, but organizations. The use of “name” in the search bar prompt may confuse some users because they may think that they need to list an individual rather than an organization. This prompt should be revised to make it more broad. There are several ways the writer could do this. For example, they could write: “Enter the accredited representative.”
- Prototype A > Step 3 > Permission to access your medical records - The user finds the legal terms of the records release policy hidden in an accordion. The user is then asked: “Do you give this accredited representative permission to access your medical records?” However, the language in the accordion is: “I authorize the VA facility…” This may be semantics, but “I give permission” may be viewed differently from “I authorize.” The language around these legal terms should match to avoid potential confusion. For example, if the legalese is “I authorize,” then the question should be: “Do you authorize this accredited representative to access your medical records?”
  - Additionally, instead of “records release policy,” the nature of the accordion may be clearer to the user if the title was: “Authorization for records release.”

### Consider
- Find and appoint a rep landing page > Intro > Appoint and accredited representative - The user finds the following directions (paraphrased here): First, contact the accredited representative to see if they’re available. Then, fill out this form that appoints them. To make things extra clear, consider adding content such as, “Once the accredited representative has confirmed that they’re available to help you, use our online tool…”

## Notes
Thank you again for the opportunity to review your work. It's looking really good. Please continue to work with CAIA to reorganize and/or add subheaders to the main landing page.

**Comment by aprocik1** [comment]
@oddball-lindsay, I'm commenting here to record my content updates following your midpoint review.

### Must
**- Bullet points 1, 2, 3, 5, 6:** These updates are due to inconsistencies between the AAR prototype content source of truth document and the design. I left comments in the Sketch file where these inconsistencies occur.
**- Bullet point 4:** I updated the content on this screen to active voice.

### Should
**- Bullet point 1:** The FAR tool is launching with VSOfficers, rather than VSOrganizations. Meaning, search results will only ever return names of individuals. However, based on other updates elsewhere, I updated the content in this label to: "Enter the name of the VSO or accredited attorney"
**-  Bullet point 2:** I updated the content on all relevant screens from "permission" to "authorization."

### Consider
**- Bullet point 1:** I updated the content in the "appoint" section on the landing page to: "After you've confirmed that the accredited representative can work with you..." 

### Updated content sources of truth
**- Google documents:** [FAR landing page](https://docs.google.com/document/d/1tIdX3Y444fxG16SCdwWdVssBb5vCbLDnVGMp32sCqiw/edit?usp=sharing), [AAR landing page](https://docs.google.com/document/d/1S4rwiPUqxDtloWTuqLSwbQzLPsBct4ak-ZEJpLcxBjo/edit?usp=sharing), [FAR prototype](https://docs.google.com/document/d/1C3up542aM1XsqmyEq7UMZWFrODH1QtDOBXeRzXhlQqo/edit?usp=sharing), [AAR introduction page](https://docs.google.com/document/d/1QRHXsvfw8YXCir83QoXzGw9mrOnGUlfd6RN9sSlKuew/edit?usp=sharing), [AAR confirmation page](https://docs.google.com/document/d/1czbzSWj-tNG4ZWV-SEI8ja3uVew3u2adhhvml5HD2-g/edit?usp=sharing)
**- Word document:** [AAR prototype](https://dvagov-my.sharepoint.com/:w:/g/personal/anthony_procik_va_gov/ESBhwaJYiI9Hs6IMoWyVwGcBMr02J_DyJwzl1Xj6w9P9cg?e=Y3247s)
