### ISSUE TITLE
[Duplicate] ARP Permissions Flow

### ISSUE THREAD

**Issue by RivkaCGates** [department-of-veterans-affairs/va.gov-team#72575]
Replaced by: [[ARF] Permissions admin Epic#78526](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/78526)

Permissions include users who can accept POA for themselves (21-22a), users who cannot accept POA on behalf of their organization, and users who can accept POA on behalf of their organization. Additionally, permissions include the ability for "superusers" to assign to other members of their organization the ability to accept the POA on behalf of the organization.

**Comment by RivkaCGates** [comment]
One note is we need to take the 2122a reference out of this epic. That's now out of scope. I think there are some design side tickets that could be added, like mapping the needed hierarchy.

**Comment by nihil2501** [comment]
@gabezurita @RivkaCGates I am tempted to say that the next steps are really on the research side:
> 1. Augment current state map with permissions administration flows
> 1. Interview userbase to understand their needs around permissions administration

In particular, it might be inefficient to pursue work that goes beyond that research

**Comment by RivkaCGates** [comment]
That's what I was thinking about it needing to be design tickets. Do you think we would cover this at unSAFe planning or do we need a dedicated meeting? @gabezurita @nihil2501

**Comment by emily-gullo** [comment]
Re: #2 - While I think it's good to look into every possibility, I have serious security and maintenance concerns on maintaining a single file.  It feels like it would be extremely easy for that to fall off and get out of sync. I feel this is something worth the extra cost in maintaining in a more automated and secure way.

All that said, I think these are solid issues to tackle for the epic, they will set the tone.  If there are mirroring design tickets, let's sync with them sooner rather than later - not sure if there are.

**Comment by nihil2501** [comment]
@RivkaCGates At unSAFe planning, you could fill in some details of a permissions administration epic. You could include the typical research work into discovering current state + deciding on a desired future state. And then for whatever would have been at the product and engineering execution level leave it more conceptual. For example, "enable permission administration for national VSOrg users" rather than "build permission administration frontend + backend".
