### ISSUE TITLE
[Discovery] Logged-in homepage: User research — Kick-off recruiting

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#7273]
## Background

Epic #7268

As part of the logged-in homepage discovery phase, we have decided to conduct user interviews/testing to help us better gauge user needs and expectations.

## Tasks

- [ ] Send off research plan and conversation guide to Lauren Alexanderson to kick-off recruiting

## Acceptance criteria

- [ ] Recruiting has started

**Comment by andaleliz** [comment]
In our meeting yesterday, we talked about using an internal pilot participant, possibly a content person, who isn't super familiar with Mural. I'll post our need in the Public Websites channel (since a lot of content folks are there) later today so we can include this person in our research plan. Let me know if there's any reason I should hold off.  

"I'm looking for someone who isn't familiar/comfortable with using Mural to serve as a pilot participant for a research study on May 7, between 11-3 eastern time.  The session will take 45-60 minutes.  Any volunteers?"

**Comment by andaleliz** [comment]
Submitted research plan + convo guide to Lauren on 5/1; received confirmation from Pergiean team that we're all set up in their study tracker and recruiting will begin.
