### ISSUE TITLE
GIDS: Research viability of adding Dashboard Data Validator to GIDS

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#7277]
As a developer, I need to research the technical feasibility of adding the Excel Data Validator to the GIDS tool so that additional manual steps can be removed from the CT maintenance process.

##Assumptions:
1. N/A

## Acceptance Criteria
1. If this is technically feasible, a document is created outlining the technical approach to implement the functionality.

## Supporting Artifacts:
1. <img width="681" alt="dashboard_download" src="https://user-images.githubusercontent.com/48260534/78681278-8642db00-78ba-11ea-83e5-736235fd330a.png">
2. <img width="1306" alt="data_validation_checker" src="https://user-images.githubusercontent.com/48260534/78681481-cc983a00-78ba-11ea-90c4-e51cad85d849.png">

**Comment by zurbergram** [comment]
There are 55 validations that occur

**Comment by zurbergram** [comment]
There are 55 validations that occur

The validations are a bunch of `countif`, `sum` , `counta` , `sumif` excel functions with occasional addition or subtraction

Validations all use the `Comparison_Tool_Data_Full` sheet which is the exported current production version of `institutions` table without any related tables

**Comment by zurbergram** [comment]
implementation could be something like

- validations table for each group of validations (there’s 9 groups) with a column for each validation in the group, version_id and timestamps
- when a version is published to production run the logic that creates the data validations for that version
- when user loads the GIDs UI component it compares 2 most recent production versions’ groups of validations
- GIDs UI component is just a better looking version of the what the spreadsheet looks like

**Comment by zurbergram** [comment]
Possible story breakdown for the Data Validation Checker Sheet
- Create process that calculates validations when a version is published to production
  - Task 1: Create datatables
  - Task 2: setup process that occurs on publish to production (this will be the highest level of effort as there 55 validations to setup)
- Create UI component 
  - Task 1: create UI GIDs page that displays 2 most recent production version sets of validations similar to spreadsheet display
  - Task 2: Create percent different display and Good/Bad indicator (maybe as checkmark/X instead of the words)

**Comment by zurbergram** [comment]
[research.txt](https://github.com/department-of-veterans-affairs/va.gov-team/files/4451927/research.txt)
