### ISSUE TITLE
Create backend program for 10-7959a

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#72803]
Work with Rachel E. to map for form data to PDF in the backend for Form 10-7959a. This section marks the initial utilization of work accomplished on the frontend.

Include the form in the FORM_NUMBER_MAP hash, using the form ID provided by the frontend as the key (typically hyphen-separated and in uppercase letters) and the corresponding snake case representation in vets-api as the value (typically underscore-separated and in lowercase letters). Ensure the value adheres to the naming convention for all files containing the form ID in their name.

For the form data, analyze the mapping of each property to a fillable field in the PDF. This necessitates collaboration between the front and back ends to ascertain the schema.

In the form_mappings/*.json.erb file for the designated form, update the mappings on the right side of the object. Note: the keys are translated from camel case to snake case in the API call, so treat them as snake case in the backend.

**Comment by cloudmagic80** [comment]
Hey Bryan. This story will be a good exercise for you to work on. Rachel should be done with the front end. You will need to integrate Rachel's work.

**Comment by marywang2** [comment]
Updated to 10-7959f-1, assuming we can repurpose this one?

**Comment by balexandr** [comment]
@marywang2 I'm not sure it helps to do an update as it's still only a dry run. @reiting did the FE work already for 10-7959A so she would have to repurpose the FE for me to do the BE. So I think we should keep this as the original unless it wouldn't be difficult for @reiting to update

**Comment by reiting** [comment]
I agree with @balexandr. I think keeping tickets separate for the 7959a and the 7959f is best, because we did do the work for the 7959a. Although it was just practice after all, I think it'd be better overall to have 2 tickets to avoid any future confusion and so we can have the work we did for the 2 different tickets kept separate.

**Comment by marywang2** [comment]
OK I reverted this one back to 7959a and created a new one for 10-7959f-1. Was there any backend work done on this one or can I move it to the backlog?

**Comment by balexandr** [comment]
@marywang2 There are two current issues with this form.
1. 10-7959A is technically two pages even though only the first one gets filled out. So when "stamping" the PDF with "X" in checkboxes it seems to be duplicating those "X"s on the second page. Any of the current documentation for multiple pages is meant for stamping multiple pages in the same spot so this needs to be figured out.
2. There is a radio button list that I can't seem to get the 2 middle radio buttons selected. Again, needs to be figured out.

Since this form has been deprioritized if these issues can't be resolved by the time the sprint ends, I'll push up all my work to a branch to be looked at in the future but not waste additional time working on a form that isn't in the front of the line. Just wanted to give you that transparency.

**Comment by balexandr** [comment]
I don't believe we can actually put up a pr to `master` so I'll just add the GH PR URL here if anyone wants to look at it:
https://github.com/department-of-veterans-affairs/vets-api/compare/72803-create-backend-program-107959a?expand=1

**Comment by marywang2** [comment]
Closing since the work was done.
