### ISSUE TITLE
Step 4 Household Info/Current marriage: Update copy for "Type of marriage" question

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#72867]
## Info from business

VA says the most common marriage types for pension applicants are ceremonial and common law. If someone has a common law marriage, VA will process their application in a different way. We need to give the applicants some guidance that they can enter "common law" in the "other" field.

## Issue Description

The copy for existing question "Type of marriage", found in Step 4 for Current marriage page should be updated.

New copy for questions and answer options:

How did you get married?
[ ] In a civil or religious ceremony with an officiant who signed my marriage license (this is equivalent to the current option ceremonial marriage)
[ ] Some other way (this is equivalent to the current option other)
You can enter common law, proxy (someone else represented you or your spouse at your marriage ceremony), tribal ceremony, or another way.
[open text field]

## Example of existing question:
<img width="1082" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VkQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84f3a3d9a7a8862d368193fffcbe534452937dfc/Screenshot%202024-01-04%20at%202.20.49%E2%80%AFPM.png" alt="Screenshot 2024-01-04 at 2.20.49 PM.png" />

## PDF form
- Maps to [question 6F on the PDF form](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf)
<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99bf702fff70da4dc1d760b820ee8d664b9ba067/Screenshot%202024-01-03%20at%202.47.00%E2%80%AFPM.png" alt="Screenshot 2024-01-03 at 2.47.00 PM.png" />

---
## Tasks
- [ ] Update the copy to the question "type of marriage" to: How did you get married?
- [ ] Update the single-answer options to what is listed above.

## Acceptance Criteria
- The type of marriage question will be updated to the copy and answer options listed above.

**Comment by ToddWebDev** [comment]
@vbellissimo For additional clarity, can we please add a design reference for these changes?

**Comment by ToddWebDev** [comment]
@katherine-fung @mayacoforma Can you please add a design reference for these changes?

**Comment by katherine-fung** [comment]
Hey @ToddWebDev @Midge-dev. I'm sorry, I don't have access to edit in Sketch, so I can't provide a design reference. 

I actually need the "You can enter common law, proxy (someone else represented you or your spouse at your marriage ceremony), tribal ceremony, or another way." sentence to replace "Please specify." 

Here's a drawing of what I mean: 
![295027529-a95d006d-a881-4253-b9c0-32faadf1b93a (1)](https://github.com/department-of-veterans-affairs/va.gov-team/assets/105367381/48d6304c-0626-4011-a5b0-7aed5bcdbcce)

I'm really sorry for the rework. I tried to make the request as clear as possible with copy, without Sketch. If it's too much effort to rework it now, we can save this for post-MVP  cc @vbellissimo 

We'll need to change it at some point because screenreader users will hear the question, the hint text, and then the first radio option, which is none of those things in the hint text.
