### ISSUE TITLE
Deploy Proofing Agent Application to Vercel QA

### ISSUE THREAD

**Issue by lmorris3** [department-of-veterans-affairs/va.gov-team#72918]
Get the vercel deployment up to date with the main branch in the new repo:

- [x] Push `main` branch code from new VA repo to the old mo-studio remote repo. Basically use mo-studio repo as a mirror.
- [x] Get Google Maps API key configured in Vercel secrets

**Comment by mateoclarke** [comment]
Anu and I were able to deploy the latest code to Vercel today. We also confirmed that the Google Map API key is in Vercel. But the intake map still isn't working. This seems like a common problem with Vercel and we can work to resolve it but since its not important for the Proofing Agent UT, we decided to stop before digging into troubleshooting.

For the short term purposes of using the proofing agent app in UT, this task is complete and can be accessed here: https://va-in-person-identity-proofing.vercel.app/proofing/1a-case-number

**Comment by lmorris3** [comment]
This is great - thank you!! Do you have instructions for how to test? Can we use any case number?

**Comment by lmorris3** [comment]
Pulling this back to Review/QA so we can test.

**Comment by mateoclarke** [comment]
Yes, you can use any case number. The place where we've been maintaining manual test procedures is this [QA Review file](https://docs.google.com/spreadsheets/d/18v5DcUe0J5GlFZrXR219dvPCij4x-0_kdUGJ6zdzG4A/edit#gid=0)

**Comment by lmorris3** [comment]
Reviewed support/bug fixes. Closing this ticket as complete.
