### ISSUE TITLE
Implement downtime alert on landing page for all-MHV pagerduty service

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#72981]
### User story

As a user visiting the MHV landing page, I want to be alerted when an MHV maintenance window might affect my experience using health tools, so that I have less chance of stumbling into a frustrating experience.

### Notes

- Follows on #70798 discovery
  - Findings and recommendations from that ticket [in github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-downtime-notification-discovery.md)
  - [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1702946244611/d44fd191e13bc9d66a67d6e27deda6f1ee4a6f88?sender=u4c72b2ff45e7c2f8e2942500) from that ticket
  - Murals may not be 100% accurate regarding current state of tool pages
- See recommendations doc for refactor concept about making it a functional component; Jim has a nearly-ready PR to share
- Keep an eye on OCTO channels about PagerDuty, use _new PD service_
- Ignore single-tool API PagerDuty services for this MVP
- [CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75276) for this work (Laura Willwerth)

## Acceptance criteria

- The MHV landing page displays a warning-level alert during a service window for the main MHV Pagerduty service (ie, not the tool-specific PD services), with USWDS 3.0 style
- Other va-alert components on the mhv landing page are updated to USWDS 3.0

## Tasks

- [x] Consult with IA specialist about whether breadcrumbs are required to be added to the tool pages during downtime (along with H1), and update recommendation [doc](https://github.com/department-of-veterans-affairs/va.gov-team/edit/master/products/health-care/digital-health-modernization/engineering/mhv-downtime-notification-discovery.md)/Mural as appropriate

**Comment by wesrowe** [comment]
dev estimate from planning: medium

**Comment by dcloud** [comment]
Per https://dsva.slack.com/archives/C03R5SBELQM/p1705503589174489:

> On February 16 all design system web components will default to their v3 variant. v3 will become opt out only.

So I think we can add `uswds` prop/attribute now, but in the future it won't be necessary

**Comment by sterkenburgsara** [comment]
H1 definitely required. I feel less strongly about breadcrumbs during a downtime, but for consistency's sake would argue for exposing them. It's also possible that the page linked in a breadcrumb is unaffected by downtime and the availability of that component could help them navigate.

**Comment by wesrowe** [comment]
Okay, SO... after a long tete-a-tete with Keith and Daniel, we have a conclusion. The complexity in our system (4 or 5 pagerduty services) was driving a complex UX, and that was a potentially unsolvable problem. Instead, the landing page will use a single, vague message regardless of whether one or 4 tools are down.

See [slack thread about content](https://dsva.slack.com/archives/C0581MN69TJ/p1705692350346939). Will post the final content here when it's decided.

**Comment by dcloud** [comment]
The two PRs that create the keys for the MHV services:

- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2585/files
- https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/pull/2616/files

This tells me that (on the api/server side) `mhv_platform` will be the "all-MHV" Pagerduty and `mhv_meds`, `mhv_mr`, and `mhv_sm` for the services.

I can create a PR to update https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/monitoring/DowntimeNotification/config/externalServices.js if the OCTO folks haven't already (will check).

**Comment by dcloud** [comment]
Draft PR for the Downtime component changes related to adding new PagerDuty services: department-of-veterans-affairs/vets-website/pull/27618

**Comment by dcloud** [comment]
Status: "scaffolding" PR that set up `src/platform/mhv` merged, and I pushed a branch with my work-in-progress on MHV downtime components and related code.

**Comment by dcloud** [comment]
WIP/Draft PR: department-of-veterans-affairs/vets-website/pull/27782

That has content from the Mural, so need to check on approved content.


## Notes to myself
Also a WIP since I haven't done the dismissible feature of the downtime approaching alert. Need to refresh myself on how I might make that "universal" for mhv downtime notifications and whether the existing downtime warning actions](https://github.com/department-of-veterans-affairs/vets-website/blob/dcloud/72981-implement-mhv-downtime/src/platform/monitoring/DowntimeNotification/actions/index.js) are adaptable or not

**Comment by dcloud** [comment]
## Friday afternoon notes on "dismissible alerts"

Started wiring up the `platform/monitoring/DowntimeNotification` dismissible alert logic, then realized that because the `dismissedDowntimeWarnings` array (in redux store) is keyed on the `appTitle` supplied to `DowntimeNotification`, the calculated `isDowntimeWarningDismissed` value won't work with the appTitle overrides I was doing. I could inspect the redux store inside `MHVDowntime` component instead… 🤔 

💭 To take a step back, the existing work uses `appTitle` to determine whether an alert has been dismissed or not. So the session-based dismissal is in theory per-app, not per service that goes down. Apps could use the same `appTitle` to have "shared dismissal", but `appTitle` is also content showed to the user, so that could be confusing.

💡 If I want to have "shared dismissal" for MHV applications, the (unrendered) `externalService` key/label, e.g. `mhv_sm`, could implement a way to dismiss based on a service rather than an application title. However, as stated above, we would need to calculate our own "is warning" dismissed. We could possibly use the same `dismissedDowntimeWarnings` array in redux, though there may be issues that I haven't considered.

I could also create a separate/parallel "dismiss warnings" implementation that stores data in a separate place in redux. Likely I'd copy `src/platform/monitoring/DowntimeNotification/actions` and alter it slightly to be namespaces. If I did that, it might be tempting to fully separate the MHV downtime implementation from the existing one. 🤷

**Comment by wesrowe** [comment]
CAIA ticket – Laura said this morning that she provided updates there and in the Mural (yellow stickies)

**Comment by dcloud** [comment]
Revisiting my Friday notes, we aren't doing "shared dismissal" so we are okay to use the existing mechanism. I adjusted the code accordingly. Now to go back and look at the yellow stickies

**Comment by dcloud** [comment]
Looking at the yellow stickies in the Mural, and the headings appear to be generic rather than tool/app specific:

> Upcoming maintenance on My HealtheVet

This seems to go in a different direction than having multiple MHV services in PagerDuty, etc., per [our recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/engineering/mhv-downtime-notification-discovery.md#iteration-recommendation) and work in progress. I'm not sure if that's intentional, or if the tool page alerts should be "Upcoming maintenance on Messages" (for example) per our approach

@wesrowe ☝️

**Comment by dcloud** [comment]
Edits on [the Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705509202969/42becb4e1bcb478d93488ced78511a9c6acf9276?sender=u21fe6e201db26095d6911676) may affect some of the text (see [sticky note "[tool type] variants"](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1705509202969/42becb4e1bcb478d93488ced78511a9c6acf9276?wid=0-1707265579954))

Hadn't gotten to figuring out the `[link to facility locator with health prefill]` piece, beyond the `/find-locations` page. Meaning I haven't found out how to prefill/preselect health locations

**Comment by dcloud** [comment]
Found the URL for facility locator with health prefill: `/find-locations/?facilityType=health`, and I should have known its in the [landing page NoHealthAlert](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/mhv-landing-page/components/NoHealthAlert.jsx). Past me knew more than present me

**Comment by dcloud** [comment]
Put this into _Review/QA_, though with the CI being down, only people set up to run this locally can review the PR.

I'm also not sure how we can QA this, but it might involve asking someone with PagerDuty access to creating a maintenance window for `mhv_platform` when folks are looking at it. I don't have a PagerDuty account yet
