### ISSUE TITLE
Design Intent - IA Feedback - AE Profile - Enhanced Military Info

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#73027]
## VFS actions
- [ ] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [ ] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] Close the ticket when all feedback has been addressed.

## Thoughts/questions

- Thanks for bringing this to us, and showing the flow so clearly alongside the very helpful documentation. I felt like I had great context coming into the meeting and could ask better questions.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

#### Additional info component

The structure/type of content in the "Why some of your service details might not be included here" is out of step with how we see this component used across VA.gov. The content is lengthy and asks the user to take an action without providing a mechanism to do so (no links!). One approach could be to pull some of this info out into a standard heading/paragraph, structure it for scannability, and place it closer to the bottom of the page and the "Feedback" button.

#### Heading uniqueness

Brian also raised this from the Accessibility perspective. How can each of the headings on the page offer unique text that is able to be differentiated for (a) screen reader users who scan through all the headings tags, and (b) sighted users who are visually scanning the headings only?

This applies both to the `h2` tags for the branch of service, and the `h3` tags for the type of duty. There could be instances where there are multiple `h2`s that say "United States Army" and multiple h3's that say "Active Service". 

Some potential opportunities here include putting the years of service in the heading alongside branch of service; or grouping all service periods from the same branch into the same section. As the team adds more data to this view, there will be more opportunities to make these headings unique with that data.

This is a great opportunity to probe user research participants for their mental models of their past service periods, and use that to inform the information grouping and heading labels for the page.

What names do Veterans use to describe those service periods, and how are those periods grouped in their minds - by year, by branch of service, by deployment, all of the above? Should the list on this page be ordered by date, or by branch of service?

#### "Military occupational specialties" terminology

Research could also be a good time to understand the language that Veterans might use for "Military occupational specialties" across branches of service. What plain-language term might work here? "Job role", "Work history", etc.

**Comment by andaleliz** [comment]
@erinrwhite thank you for this feedback, and I'm glad you found all the background info helpful 🎉 

The design ticket also mentioned the additional info component. I moved your suggestion over there so I can consider it along side a potentially different component.  Ultimately, I'm wondering if we can get a resources and support page created that we can link to, because the [_other_ additional info component on the page](https://www.sketch.com/s/fc96664a-1c62-40ed-9fcd-90218c54e775/a/AxGmVg5) also has 3 paragraphs. I'd like to avoid having a hybrid page that combines profile info with an article, so hopefully the content team will be down with that.

The two items you brought up for `consider` make a ton of sense, and we're going to run research as a next step to learn more about both of those. We're very curious to learn how veterans naturally chunk this information, and talk about it.  I'm going to close this ticket since those will be taken care of in our next step.
