### ISSUE TITLE
Midpoint Review - Design Feedback - Facilities, VA Medical Centers, Police Transparency

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#73098]
## VFS actions
- [x] Assign this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Comment on this ticket:
  - [ ] If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - [x] When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - [ ] When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [x] Close the ticket when all feedback has been addressed.

## Thoughts/questions

-

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- **Must**: Per [our guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else), Additional Info components should not have too much content. You should not try to put multiple paragraphs inside Additional info. This includes form fields that require a lot of explanation. Link to another page, consider an [Accordion](https://design.va.gov/components/accordion), or shorten the content.

**Comment by xiongjaneg** [comment]
Hi @allison0034 Just checking if there will be more feedback for design? We got the content review and want to consolidate work timing. Thanks!

**Comment by allison0034** [comment]
No, just anything that Matt may have discussed during the meeting!

**Comment by xiongjaneg** [comment]
Awesome, thank you all!

**Comment by davidmpickett** [comment]
> Must: Per [our guidance](https://design.va.gov/components/additional-info#when-to-consider-something-else), Additional Info components should not have too much content. You should not try to put multiple paragraphs inside Additional info. This includes form fields that require a lot of explanation. Link to another page, consider an [Accordion](https://design.va.gov/components/accordion), or shorten the content.

It seems like your comment is based on the Sketch file, rather than the [content source of truth on Sharepoint](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/ESKYtD-cnh9Pg8rBf_kgYaoBmr8Mg7eMTrtKtKoGrXCDiA?e=IQyeOD). Apologies for any confusion, keep our artifacts in sync has been a challenge.

We have already significantly reduced the amount of content in each Additional Info component. Each definition is now limited to a single sentence. Here is the relevant copy from the content source of truth:

**[Additional info] What counts as an arrest?**
An arrest is when VA police take someone into custody for criminal charges.

**[Additional info] What counts as a ticket?**
A ticket is when VA police give a written notice to someone for violating the law.

**[Additional info] What do these police conduct terms mean?**
- A **complaint** is when someone reports that a VA police officer may have violated VA policies.
- An **investigation** is when VA checks if a VA police officer violated VA policies.
- A **sustained allegation** is when VA finds that a VA police officer violated VA policies. 
- **Disciplinary action** is when VA holds a VA police officer accountable for violating VA policies. 

**[Additional info] What do these use of force terms mean?**
- **Use of force** is when a VA police officer uses physical force to get someone to follow their orders.   
- **Weapons discharge** is when a VA police officer fires a gun.

**Comment by davidmpickett** [comment]
@allison0034 With that revised copy, are we okay to use the Additional info component?

**Comment by thejordanwood** [comment]
I've also updated [the Sketch file](https://sketch.com/s/b48c905c-7c7f-46fb-9ae5-6020ff0e5174) to show the updated copy in the additional info components.
