### ISSUE TITLE
Design | Move Artifacts to Figma

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#73196]
## Issue Description
_The VA is migrating design artifacts from Sketch to Figma, so all artifacts need to be moved into Figma before access to Sketch is discontinued on Feb 16, 2024._

---
## Tasks
- [ ] Move relevant design artifacts into Figma.

## Acceptance Criteria
- [ ] All non-disability design artifacts are in Figma.
---

**Comment by fiorella-io** [comment]
@steele-lm the only 686 designs I see on Sketch are the ones Ajia worked on regarding the Foreign address issue. If this has been implemented we don't need to transfer these designs. And I couldn't find any 674 designs on Sketch. Unless the creator used a different title.

**Comment by steele-lm** [comment]
@fiorella-io Great! I didn't know how many we might have to move. We don't have to move the address files. I'll move this ticket to done.

**Comment by fiorella-io** [comment]
@steele-lm In February I might need to move Burial to Figma. I have not wanted to do that because it's close to getting implemented but I'll move it just in case then. It should be quick. I won't recreate it using Figma components which would be a heavy lift. I'll just use the Figma out-of-the-box import they have for Sketch files.

**Comment by steele-lm** [comment]
@fiorella-io I just realized that I never changed the AC to non-disability...sorry. I copied a ticket I made for Ajia onto the non-disability board. I'll update this ticket, so we can account for the burial files that may need to be migrated.
