### ISSUE TITLE
Fix with_tracking use in 526 submission

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#73266]
[We have been getting this error for a while now...](http://sentry.vfs.va.gov/organizations/vsp/issues/248025/?project=3#message) It's caused by the running of a `job_tracker.rb` method on code that has not been wrapped with the `with_tracking` method.

This is a super weird, arguably bad pattern, but for now we just want to fix the bug.  The primary culprit seems to be    `submission.send_post_evss_notifications!` running in EVSS::DisabilityCompensationForm::SubmitForm526#perform *after* the `with_tracking` block ends.  

If EVSS is down when that call happens a Breakers::OutageException is raised.  This error is caught and delegated to the job_tracking error handlers, which only work if the breaking code exists within the `with_tracking` block. 

We should refactor this with_tracking thing to not be so easy-to-misuse.

**Comment by SamStuckey** [comment]
[PR is done](https://github.com/department-of-veterans-affairs/vets-api/pull/15066), someone just needs to figure out how to test this

**Comment by freeheeling** [comment]
From what I have been able to discern from Datadog, these warnings are actually something that extends back to April 2023 (see image below). When a form is submitted for processing, in `EVSS::DisabilityCompensationForm::SubmitForm526`, `prepare_for_evss!` is run before the `with_tracking` block that assigns the `submission_id`, the value of which must not be null when attempting to update the corresponding `Form526JobStatu`s on retryable error handling events.

In the [instances raised by Steve](http://sentry.vfs.va.gov/organizations/vsp/issues/248025/), a request to EVSS's `/ratedDisabilities` endpoint raised a `Breakers::OutageException`, which was rescued within `EVSS::DisabilityCompensationForm::SubmitForm526#perform` that calls the `retrayable_error_handler` defined in `Sidekiq::Form526JobStatusTracker::JobTracker`.

However, because submission is not used in the method and passed through to the handler, and EVSS pre-processing lies outside of the `with_tracking` block, the `upsert_job_status` method called in the handler has no knowledge of the corresponding `@status_submission_id`, resulting in the "PG::NotNullViolation: ERROR" being thrown.

The errors being raised don't seem to be impacting ultimate submission processing as the handful I examined were eventually reattempted and processed. I believe the  issue could be addressed by relocating `prepare_for_evss!` within the `with_tracking` block, but I'd like to get other's perspectives on my interpretation and assessment, including anything I may have overlooked or am misunderstanding. Thanks!

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUMrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72d25805e455bbb4bee36de8035cb6a73c31bdc2/image.png" alt="image.png" />

**Comment by SamStuckey** [comment]
Reassigning to Scott cc @austinjprice

**Comment by freeheeling** [comment]
Submitted for review 1/19.

**Comment by freeheeling** [comment]
Resubmitted for review 1/22 after making changes to pass specs.

**Comment by freeheeling** [comment]
Requested review 1/24.

**Comment by freeheeling** [comment]
vets-api PR [#15195](https://github.com/department-of-veterans-affairs/vets-api/pull/15195) deployed to prod. Moving to done.
