### ISSUE TITLE
Step 4 household info: Update copy to remove "your" from Dependent Child name fields

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#73288]
## Issue Description

<img width="619" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMit4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89c11e497f4375ccd8bc00b2b7d6bf63ecdcd299/Screenshot%202024-01-09%20at%206.34.25%E2%80%AFPM.png" alt="Screenshot 2024-01-09 at 6.34.25 PM.png" />

---
## Tasks
- [ ] 

## Acceptance Criteria
-

**Comment by aplatt-coforma** [comment]
Child address screen looks good.
<img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy9SQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9681f69102e2f857061031a7f7a89771c6910fb/Screenshot%202024-01-16%20at%205.50.51%E2%80%AFPM.png" alt="Screenshot 2024-01-16 at 5.50.51 PM.png" />

On the dependent child screen, instead of just removing "Your", the word "Child's" was added. Is that OK @vbellissimo 
<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEhSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbc298d52aa5f88ad174cb253470860770a62543/Screenshot%202024-01-16%20at%205.49.06%E2%80%AFPM.png" alt="Screenshot 2024-01-16 at 5.49.06 PM.png" />
