### ISSUE TITLE
Design - State Machine

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#73542]

**Comment by NB28VT** [comment]
@austinjprice TLDR on my sync with @SamStuckey this afternoon:
- Presented my sort of high level philosophy on how we should think about this, rough overview of some potential state mapping, some gotchas/things to consider down the line.
- TLDR we can map out and put together a framework for tracking post-submission actions _regardless_
 of whether we end up using polling or webhooks etc. We don't need to solve all that now.
- Sam had good feedback on focusing on just realizing what steps and fail states/pending states would existing in this entire process, and suggestions on what we should do in certain situations (for example, what do we do if Lighthouse is down and a document doesn't get to them? What happens if some documents fail but others don't? Etc.
- Next step is to visualize all of this in a big Mural document, this will be a great tool for us to identify all of the use cases, get feedback on how we want to handle all of these situations/how they play into the backup path etc.

So putting all of that together will become my main focus starting tomorrow.

**Comment by austinjprice** [comment]
based on recent dicsussions this work has helped clarify need for light polling for each of the migrations (4142 and Veteran documents) along with 526 audit, which can follow known patterns like the 686c polling work. Actionable take aways:
--MPV solution needed
--need to ticket the problems identified in ancillary process
-- waiting for concurrence with Nathan

**Comment by shaunburdick** [comment]
This was split into two actionable items:
- Form526Submission Improvements: #75526
- Upload Polling: #75804
