### ISSUE TITLE
10-7959f-1 - Create from directory and skeleton in front end repositories

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#73561]
Build skeleton of [10-7959f-1](https://www.va.gov/find-forms/about-form-10-7959f-1/)

 [ ] create repository and directories
 [ ] Generate form skeleton using Yeoman generator
[  ] Make tweaks to generated code as necessary (can skip Introduction and Confirmation pages for now)
[  ] Create vets-website pull request for platform approval
[  ] Create content-build pull request for platform approval
[  ] Merge pull requests

**Comment by reiting** [comment]
I completed the skeleton, but I'm not sure how to have it reviewed by product, since it's not up anywhere yet. If I create a codespace, it will only be active for a specific amount of time, so I wanted to check what we think we should do for this. I'm planning to finish building it out this coming sprint, for the frontend.
