### ISSUE TITLE
Remove the DAP (Digital Analytics Program) script from 404 template pages

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#73740]
# Google Analytics Implementation Request

Opening here per advice of @davidconlon but I'm not sure where this issue belongs. Per Dave, no one officially owns the VA.gov 404 page.

We need to remove the DAP ([Digital Analytics Program](https://digital.gov/guides/dap/add-your-site-dap/)) script from 404 template pages. Google Analytics (GA) reports that the script loaded so the script is always found even though the page actually may not be found. The end result is that deleted pages (or non-existent pages caused by a typo) are reported in VA-wide Web A11y Intetgrated Project Team a11y scan reports which are built off GA traffic data. 

Example: Even a typo like https://www.va.gov/idme causes the 404 page to appear on our a11y scan reports based on GA traffic data. 

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by jestutt** [comment]
@artsymartha68

**Comment by jestutt** [comment]
@artsymartha68  Thanks for the quick call this morning. As I said then, I don't believe the DAP team would be willing to remove tracking from the 404 page since that's valid traffic and would effect their data and reporting. Instead, the optimal solution to remove 404 URLs from your dataset is to filter it out using the "VA.gov | Veterans Affairs" page title that's shared across all 404 pages. 

I also would like to reiterate that PDFs (and any other document or image file extensions) should not be showing up in the list of site page URLs -- downloads are tracked as events, not page views. Any PDFs that are in the list of site page URLs happen when, for what ever reason, that PDF URL did not go to a PDF document at the time of the interaction so a 404 page loaded instead. 

I'm closing the ticket but I can continue to assist in the [Slack thread we have going on the same topic](https://dsva.slack.com/archives/C1Q4294JJ/p1705435315694149).
