### ISSUE TITLE
FE | USWDS V3 Component Migration | Personal Information

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#73847]
## Background 
We need to migrate to the new components. This ticket is to work through the personal information page which is one of our largest!

## uswds v3 components that are in profile
<details><summary>Details</summary>
<p>

from [VA design system Storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-accordion--default)

| components that can be upgraded to v3 | on Profile? | what section/s or file/s? |
| -- | -- | -- |
| Accordion | ❌ | |
| Additional info | ✅ | many |
| Alert | ✅ | also many |
| Breadcrumbs | ✅  | ProfileBreadcrumbs |
| Button pair | ❌ | |
| Button | maybe | AccountSecurityTables has a non-web-component button that has a `va-button-link` class - this probably won't be affected |
| Checkbox group | ❌ |  |
| Checkbox | ✅  | NotificationCheckbox (react-binding) |
| Featured content | ✅  | CopyAddressModalPrompt, MilitaryInformation |
| Icon | ❌ | |
| Memorable date | ❌ | |
| Modal | ✅  | CopyAddressModalFailure, CopyAddressModalSucess, BankInfo, EditConfirmCancelModal (all react-bindings) |
| Number input | ❌ | |
| Pagination | kind of (derivative) | ConditionalProcessList |
| Privacy agreement | ❌ | |
| Process list | ❌ | |
| Progress bar | ❌ | |
| Radio button | ❌ | |
| Search input | ❌ | |
| Select | ❌ | |
| Statement of Truth | ❌ | |
| Text input | ❌ | |
| Textarea | ❌ | |

_Originally posted by @allisonlu in https://github.com/department-of-veterans-affairs/va.gov-team/issues/69483#issuecomment-1852648582_

</p>
</details> 

## Acceptance Criteria 
- [ ] the page is using all the new components 
- [ ] we've alerted the design system team of any bugs/issues we've uncovered ahead of the forced migration on Feb16
- [ ] double check that the profile field information controller is good to go> the "main god component" is working > make sure it's functioning correctly on contact info as it is shared between the two pages and on the edit page (it's used in all the places we're hoping if it's correct on the personal information page and contact information page that it's okay everywhere else it may be used as well)

**Comment by mtcA6** [comment]
@adamwhitlock1 should there be a little bit of padding between the error and the link to "learn more about your disability rating"? 

<img width="814" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMklQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8240456337ea775513a506e0a763a4d0d197bb42/image.png" alt="image.png" />

cc: @pamela-drouin @andaleliz

**Comment by adamwhitlock1** [comment]
> @adamwhitlock1 should there be a little bit of padding between the error and the link to "learn more about your disability rating"?
> 
> <img alt="image.png" width="814" src="https://camo.githubusercontent.com/3d337e78aa3b4908659cedb835e8477a231f754a72c6c1e36f191250bc089150/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a42614842424d6b6c515158633950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d383234303435363333376561373735353133613530366530613736336134643064313937626234322f696d6167652e706e67">
> 

Hmm I'll take a look, but the screenshot that you posted doesn't appear to be a valid image / isnt loading for me

**Comment by mtcA6** [comment]
@adamwhitlock1 weird it shows up when i look 

how about this one? 

![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/129431463/0ed8ddd6-2a9c-4a52-995c-d23a108220d7)

**Comment by adamwhitlock1** [comment]
Yep I see that one and it does look a little more spaced out in the figma file, I'll adjust that and put in another PR. Thanks @mtcA6

**Comment by adamwhitlock1** [comment]
Since there is one more tweak to make to this, I would say we roll this over as 1 point to next sprint. I would also like to get design's feedback on the loading and error state of the modal. 

When there is an error: <img width="506" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38f72d55da57738c5a2fc8f28eaca79a1fa95b93/Screenshot%202024-01-30%20at%207.39.11%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 7.39.11 PM.png" />

^ to me the contrast of the error alert against the yellow of the modal doesn't look _great_ so wondering if there should be an alternate approach to this.

For any modal that results in a direct api call / loading indicator to be displayed within the button, it looks like this:

<img width="523" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9456279d6443fe235742b9779bfb0f83c088a914/Screenshot%202024-01-30%20at%207.43.24%E2%80%AFPM.png" alt="Screenshot 2024-01-30 at 7.43.24 PM.png" />

^ which again the background of the elements combined isn't ideal, so maybe that is another treatment that we could do with the loading indicator.

@andaleliz and @pamela-drouin are welcome to chime on this or we can discuss more in sprint planning

**Comment by andaleliz** [comment]
@adamwhitlock1 those are so terrible! My eyes!!!! My accessibility-minded heart! The horror!!!!

A quick, not well-thought-out-thought is what if we close the modal when the button is clicked, and the error message displays where the success message would show, in the "card" (or table, what do we call it?) where the user initiated the action? And then if we did that, do we need the loading state?

If we need to keep these in the modal for any reason, given that these are changes being made at the DS/platform level, I'm inclined to bring this to their attention first and see if they have any solutions before we spin our wheels solving for this as a team.
