### ISSUE TITLE
Send metadata to VBA OBI intake team

### ISSUE THREAD

**Issue by sortizsh** [department-of-veterans-affairs/va.gov-team#74032]
## Issue Description
Emily reporting this issue from the VBA OBI intake (mail portal) team. 

the automation that runs on the mail portal doesn't work on our 526 backup submission because of the way we print the contentions on an extra page. So we need to send some metadata along with the submission that indicates it needs to be offramped from automation. This helps them appropriately route it to a person.
Originally this was set up with the right metadata, but it looks like on 5/27/23 at 20:52 something changed.
We need to adjust the metadata back, the two elements are forceofframp and doctype  metadata.
Set the ForceOffRamp field to 1 (true)
Set the DocumetType field to 21-526EZ

additional context in this thread: https://dsva.slack.com/archives/C04KW0B46N5/p1705090286903309

This must be complete at the end of the sprint 1/30 
---
## Tasks
- [ ] _What work is necessary for this story to be completed?_

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---

**Comment by freeheeling** [comment]
I'll double confirm tomorrow, but I think the form526_backup_submission_force_offramp flipper mentioned [here](https://api.va.gov/flipper/features#:~:text=form%2026%2D4555-,Off,form526_backup_submission_force_offramp,-If%20enabled%20add) just needs to be toggled to "On" to meet the first expected update. Unless a value of `'true'` does not correlate with `1`, then a code change will be necessary.

Regarding the second field update, the current `docType` value sent as part of the metadata is '21-526EZ', but all the communication refers to `DocumentType` [_sic_] as the data element field name. Some clarity would be helpful to know whether a different field name, and its format, should be passed other than the one currently being used. Otherwise, the value shouldn't require an update.

**Comment by freeheeling** [comment]
Toggled [form526_backup_submission_temp_killswitch](https://api.va.gov/flipper/features#:~:text=form526_backup_submission_temp_killswitch) to 'On' yesterday afternoon. 

Email this morning from VBA confirmed that backup submissions are now routing to the outbound comp queue as requested. 

Moving to 'Done'. @austinjprice Should this also be considered 'Closed'?
