### ISSUE TITLE
[CST][BUG][Spike] Some closed claims are not showing the decision letter

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#74194]
## Background

A-20240105-1293384             Claim ID:         101910317      File #: 

I filed for surviving spouse benefits on September 13, 2023. January 2, 2024 a decision was made on my claim. It says that I can download my decision letter, but every time I try, it says no letters are available. How do I see what decision was made on my claim? 

A-20240105-1292334             Claim ID:         103917212      File #: 

Although it says my claim is closed and a decision letter was mailed, I have not received it and cannot download a copy from the site.  How do I find out the status of my claim? 

## Acceptance criteria

- [ ] Investigate why these users are unable to find the letters they're looking for, report findings

**Comment by jerekshoe** [comment]
I will need the EDIPI or the ICN for the Veterans in question as well as the claim IDs in order to view their eFolders and determine the `docType`s of the decision letters that they are not seeing currently. If we get lucky then there will be documents that have a `receivedAt` date that is the same or close the close date of the associated claim.

If that doesn't work, then I may need to have someone with production VBMS access look at these Veterans eFolders and tell me what the titles of the documents that should be considered decisions letters are.

**Comment by jacobworrell** [comment]
@jerekshoe details added
