### ISSUE TITLE
Bug - T1917: Standalone sign-in page

### ISSUE THREAD

**Issue by marriej** [department-of-veterans-affairs/va.gov-team#7421]
https://dsvavsp.testrail.io/index.php?/tests/view/1917&group_by=cases:section_id&group_order=asc&group_id=70

**Comment by ericbuckley** [comment]
This looks to be a backend issue, I'm still debugging but will post more information about whats going on when I figure it out.

**Comment by ericbuckley** [comment]
@marriej after running some tests locally and on staging, I noticed that there is an inconstancy between the data we receive in development from IAM (their PINT environment) and in staging (their SQA environment).  Because of the missing data, the redirect back to cerner is broken.  I've emailed the IAM team (and CCed you).

**Comment by ericbuckley** [comment]
@marriej I just ran a test on staging, with Chrome, and it worked.  If you can verify this, I believe we can close this ticket

**Comment by marriej** [comment]
@ericbuckley ran it in chrome and got the Internal Protocol Error.
