### ISSUE TITLE
parse ICN number from SSOe SAML response (optimization)

### ISSUE THREAD

**Issue by ericbuckley** [department-of-veterans-affairs/va.gov-team#7424]
The ICN number should be available in all/most responses from SSOe SAML Response when the user has an MVI record.  That number will appear in the `va_eauth_gcIds` attribute in the same format that we currently see in the MVI lookup.

If available, we should parse that out and store in an user_attributes variable, and allow the user record to use that before falling back to the value in the MVI record.  This optimization will allow us to create new Account records for a subset of users without having to query MVI first.

refs https://github.com/department-of-veterans-affairs/va.gov-team/issues/5760

**Comment by ericbuckley** [comment]
@patrickvinograd is the [mhv_icn](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user.rb#L126) number specified in the SSOe SAML Response the same value as the [mvi icn](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/models/user.rb#L133) number?

**Comment by ericbuckley** [comment]
if so, my thought is a simple change like this will let us create Accounts without having to lookup the MVI record first.

```

app/models/account.rb
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

──────────────────────────────────┐
class Account < ApplicationRecord │
──────────────────────────────────┘
85
       idme_uuid: user.idme_uuid,
       sec_id: user.sec_id,
       edipi: user.edipi,
-      icn: user.icn
+      icn: user.mhv_icn || user.icn
     }
   end
```

**Comment by patrickvinograd** [comment]
Yes, especially for SSOe, they are one and the same. SSOe does the work of resolving the user in MPI based on external identity attributes, then gives us a SAML payload that has the ICN in it, and if we plunk that into the `mhv_icn` attribute.

You can see that the `user.mhv_icn` attribute is populated from the SSOe-issued `va_eauth_icn` SAML attribute here:
https://github.com/department-of-veterans-affairs/vets-api/blob/919ea3a940fcf41bfb776ea53c22e2e5ed6b3e49/lib/saml/user_attributes/ssoe.rb#L100

For non-SSOe it's a little tricker. In that scenario, we only get an ICN for MHV credentials (that's why the attribute is named `mhv_icn`). For other  credentials, neither ID.me nor DSLogon knows the ICN, so we perform the MPI lookup using their PII traits or EDIPI (which we do get from those credential providers).

So this will work fine in an all-SSOe world for sure (because as soon as we have the SAML, we don't even really need to look up in MPI - the SAML is sufficient). But I'd have to re-review the account creation logic to know how it will behave in non-SSOe cases. Happy to think through that with you tomorrow.
