### ISSUE TITLE
EVSS::DisabilityCompensationForm::SubmitUploads has exhausted its sidekiq queue -  Jan 24 2024

### ISSUE THREAD

**Issue by austinjprice** [department-of-veterans-affairs/va.gov-team#74386]
Review and identify cause of this sidekiq job exhaustion spike, notice of which originated in Slack, with [a thread](https://dsva.slack.com/archives/C04KW0B46N5/p1706114839266409) covers discussion on the matter. 

https://vagov.ddog-gov.com/monitors/189093?q=total&view=spans&live=1w

- Confirm what the root cause of SubmitUpload queue exhaustions are,
- What the outcome is for the Veteran,
- And how we can fix it going forward

**Comment by freeheeling** [comment]
6 different types of warnings (and total number of occurrences since 12/12/23 when new logging of exhausted retries was implemented):
- EVSS-15001 (47)
- file type is not a supported format (115)
  - the error message also mentions to "Try using a different file type such as PDF (unlocked), JPEG, BMP or TXT."
- file did not match the file extension (11)
- file is corrupted (27)
- Unique ID: [####] Server Name: [ManagedServer###] (19)
- BackendServiceException: {:status=>503, :code=>\EVSS503\"}" (3)

Documented thus far for each occurrence of an error message type, I have timestamps, job IDs, and associated submission IDs.

**Comment by freeheeling** [comment]
The data I've recorded thus far only goes back to 12/12/23, when we began logging exhausted retries. It may be possible to search further back, but it won't be as straightforward.

Once I gain more insight into EVSS's validations, I can analyze some failed uploads to determine if there's a remedy that can be implemented moving forward. In the meantime, any upload that errors, exhausting all retries, will only be apparent if inspecting the [EVSS::DisabilityCompensationForm::SubmitUploads has exhausted its sidekiq queue](https://vagov.ddog-gov.com/monitors/189093?q=total&view=spans&live=1w) monitor.

**Comment by freeheeling** [comment]
I have some theories as to why many file uploads are erroring:

- for the "file type is not a supported format" and "file did not match file extension" errors, there appears to be a pattern where files with a `txt` extension are not passing validation, this despite the fact that the file format error message suggests `TXT` is a supported file type
- for the "file is corrupted" error, it appears that uploaded files with an uppercased `PDF` extension are not passing validation, whereas I haven't observed a case where those with a lowercased `pdf` extension have failed

This is not a definitive conclusion, given that I have not conducted a thorough review, but I think it's definitely something worth digging into.

**Comment by freeheeling** [comment]
[Messaged](https://dsva.slack.com/archives/C8R3JS8BU/p1706204744445839) #evss-prod Slack channel seeking clarity, asking the following:

> I'm hoping to gain some insight into the following error message keys returned from POST requests of uploaded files to `.../wss-document-services-web-3.7/rest`
  ~ EVSS-15001
  ~ EVSS-15004
  ~ EVSS-15005
  ~ EVSS-15006
  ~ File Upload
Each error contains accompanying text, but what I'm hoping I might be able to be provided are the exact validations that lead to an error.

**Comment by freeheeling** [comment]
from https://dsva.slack.com/archives/C1VBAHWQL/p1537980384000100:

> On uploads of attachments to wss-document-services, one of the validations the service performs is to sanity check the given file extension (e.g., “.pdf”) to the “detected” mime type of the file itself. If there’s a mismatch, the service will return the EVSS_15005. So chances are the service was not able to recognize the upload as a valid pdf file. 
> it seems that when document-services analyzes the actual content of a problematic attachment, it’s determining the attachment to be a “plain/text” file.  and with the file extension being a .pdf is why document-services is returning the 15005

**Comment by freeheeling** [comment]
EVSS validation checks for doc upload:
1. EVSS_15001
a. pdf creation fails at any step
b. Unable to save doc to inflight database
c. If the pid is invalid
d. File cannot be null
e. DocType cannot be null
f. DocTypeDescription cannot be null
g. ClaimId cannot be null
h. ClaimId cannot be non Alphanumeric
i. SystemName cannot be null
j. Doc exceeds the maximum allowed size or is empty
k. Error calling BGS to read or update claim suspense data
l. BENEFICIARY_CANNOT_BE_NULL
m. SSN_CANNOT_BE_NULL
n. FIRST_NAME_CANNOT_BE_NULL
o. LAST_NAME_CANNOT_BE_NULL
p. Error stamping PDF with “Submitted Electronically”
q. ReceivedDt cannot be null
r. Filename cannot be null
2. EVSS_15002
a. PDF is locked
3. EVSS_15004
a. Invalid file text encoding. Needs to be UTF-8
4. EVSS_15005
a. Actual MimeType does not equal the implied File name based on the extension of the file
5. EVSS_15006
a. PDF is corrupt or any unexpected error occurs when validating file. The file type validation is not case sensitive.

**Comment by freeheeling** [comment]
@austinjprice @va-albers @emilytheis According to the above validations provided by Michael Harlow in [this thread](https://dsva.slack.com/archives/C8R3JS8BU/p1706204744445839), following are contributing factors to each of the `SubmitUpload` queue exhaustion errors:
- any of the `EVSS-15001` errors could have been caused by 1 of 18 different validation checks, some of which we have no control over
- the `EVSS-15004` (file type is not a supported format) errors occurred because the file text encoding was **not** UTF-8
- the `EVSS-15005` (file did not match the file extension) errors occurred because the uploaded file's actual MimeType was determined to **not** equal the implied file name based on the extension of the file
- the `EVSS-15006` (file is corrupted) errors are the result of a corrupt PDF or any unexpected error that occurred when validating the file, the latter of which is beyond our control

In summary, all of the following are file upload validations that we must assure be met prior to submitting to EVSS:
- pid is valid
- file is not null
- `docType` is not null
- `docTypeDescription` is not null
- `claimId` is not null and must be alphanumeric
- `systemName` is not null
- doc cannot exceed maximum allowed size or be empty
- `BENEFICIARY` is not null
- `SSN` is not null
- `FIRST_NAME` is not null
- `LAST_NAME` is not null
- Error stamping PDF with “Submitted Electronically”
- `ReceivedDt` is not null
- `Filename` is not null
- file text encoding is UTF-8
- `MimeType` must equal the implied file name based on the extension of the file
- PDF is not corrupt
 
Uploads are performed asynchronously as part of the form 526 submission process, when a Veteran submits their claim. Uploads post to EVSS individually, and an error message is returned to the system for any upload that fails validation. A veteran wouldn't be aware or notified of a file upload failure to EVSS. So, it's likely many of the identified error instances have gone unresolved (i.e., some submitted uploads never made it to VBMS and into the veteran's eFolder).

Record of a failed upload attempt is identifiable from ["Submit Form 526 Upload Retries exhausted" query logs](https://vagov.ddog-gov.com/logs?query=%22Submit%20Form%20526%20Upload%20Retries%20exhausted%22%20&cols=payload.job_id%2Cpayload.form526_submission_id%2Cpayload.error_message%2Cpayload.error_class&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=desc&view=spans&viz=stream&from_ts=1701122746499&to_ts=1706306746499&live=true). [Documented](https://dvagov-my.sharepoint.com/personal/scott_regenthal_va_gov/Documents/Submit%20Form%20526%20Upload%20Retries%20exhausted.xlsx?web=1) thus far for each occurrence of an error message type, I have recorded timestamps, job IDs, and associated submission IDs. Unfortunately, as mentioned in an earlier comment, that specific warning only began being logged 12/12/23.

Searching ["EVSS\:\:DisabilityCompensationForm\:\:SubmitUploads" ](https://vagov.ddog-gov.com/logs?query=env%3Aeks-prod%20service%3Avets-api%20%22EVSS%5C%3A%5C%3ADisabilityCompensationForm%5C%3A%5C%3ASubmitUploads%22%20status%3Ainfo%20&cols=&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=time%2Cdesc&view=spans&viz=stream&from_ts=1680328800000&to_ts=1702450740000&live=false) for the period prior to 12/12/23, there are ~1800 logs dating back to 4/6/23. Error messages were not recorded for these upload exhaustion events.

I may have to search the git history to determine why record of these errors for the particular search query used doesn't extend back further than 4/6/23. I also am not sure, based solely on the recorded job ID, which of a veteran's uploads (if they submitted more than one) was the upload that failed.

There are a number of questions regarding this issue and next steps:
1. Is there any indication on a form 526 package as to the name and/or number of uploads submitted by a veteran, something that would indicate to the reviewer that an upload was missing? 
2. What action should be taken concerning those 219 exhausted submit upload events that have been documented thus far?
3. Is there value in documenting all additional ~1800 dead jobs from 4/6–12/12/2023, even if we don't know why the upload errored?
4. It is not clear yet how to determine which of a veteran's multiple uploads failed. This requires investigation if we reattempt to submit any uploads.
a. Do we make the necessary corrections so these uploads don't raise an error when reattempting?
b. Alternatively, do we submit uploads to a different service with more relaxed validations? 
5. Do we attempt to search further back than 4/6/23 for any record of dead `SubmitUploads` jobs?
6. What validations can be implemented in code prior to the `SubmitUploads` step to EVSS to decrease/avoid failures moving forward?
7. Should a process be developed for handling a submitted upload once all retries to send to EVSS have been exhausted?

**Comment by austinjprice** [comment]
This originated from a slack thread from Steve and Emily - @freeheeling and @austinjprice to add link to slack thread. Need to revisit when we have feedback

**Comment by freeheeling** [comment]
Slack thread added to description.

**Comment by freeheeling** [comment]
Documented 1,804 retry failures logged between 4/6 and 12/13/2023 in a tab [here](https://dvagov-my.sharepoint.com/:x:/g/personal/scott_regenthal_va_gov/EYNQEW9sNaxJhLoTIgx6hkoBiI2PxsaZInHl4eVuIAl04g). Each record includes a timestamp, job ID and the submission ID.

Each record represents a supplemental document associated with a 526 submission that failed to upload. Some submissions include multiple documents that failed to upload. Reasons for failures from this time period are not provided in logs.

Undetermined is the failure of supplemental document uploads prior to 4/6/23.

**Comment by freeheeling** [comment]
To get a sense of scope, [these](https://vagov.ddog-gov.com/logs?query=%22EVSS%3A%3ADisabilityCompensationForm%3A%3ASubmitUploads%22%20%22died%20with%20error%22%20&cols=host%2Cservice&index=%2A&messageDisplay=inline&refresh_mode=paused&storage=online_archives&stream_sort=desc&view=spans&viz=stream&from_ts=1706079600000&to_ts=1707755280000&live=false) are logged SubmitUploads errors over a 19-day period, since I performed my initial investigation on 1/24. Averaging approximately 4/day.

I was able to confirm availability of S3-stored submitted uploads as far back as at least 4/5/23.

**Comment by freeheeling** [comment]
**BLOCKED**
- Awaiting input concerning remediation of historic failures:
  -  370 instances of ["Submit Form 526 Upload Retries exhausted"](https://vagov.ddog-gov.com/logs?query=%22Submit%20Form%20526%20Upload%20Retries%20exhausted%22%20&cols=payload.job_id%2Cpayload.form526_submission_id%2Cpayload.error_message%2Cpayload.error_class&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=desc&view=spans&viz=stream&from_ts=1701374640979&to_ts=1709150640979&live=true) from Dec 12, 2023 to Feb 28, 2024, out of approximately 285,115 uploads (0.13% error rate)
- Answering questions concerning how to fix going forward:
  - What validations can be implemented in code prior to the SubmitUploads step to EVSS to decrease/avoid failures moving forward?
  - Should a process be developed for handling a submitted upload once all retries to send to EVSS have been exhausted? Something similar to the backup path utilized by form 526?

**Comment by sortizsh** [comment]
Talked to Emily and we will: 
- talk to HCD to figure out what error/email we can show the status to Veteran @juliepedtke 
- trigger for VA Notify email when doc fails to upload? 
- add validations to the front end that we can 
- do we need addtl investigation with EVSS, we cannot let them fail out 

priority is above doc upload

**Comment by freeheeling** [comment]
Created [Augment document upload validations](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/78539) ticket to address following action item:
> add validations to the front end that we can

Newly created [Form 526 Confirmation Email VaNotify Service research](https://app.zenhub.com/workspaces/disability-benefits-experience-team-carbs-6470c8bfffee9809b2634a52/issues/gh/department-of-veterans-affairs/va.gov-team/78265) ticket addresses action item:
> trigger for VA Notify email when doc fails to upload?

Remaining is following action item:
> talk to HCD to figure out what error/email we can show the status to Veteran
