### ISSUE TITLE
[Design] 10-10EZR V2: EC - Add "Address" and "Relationship" to Designs

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#74554]
As a Veteran, I would like to have relevant and up-to-date information for my Emergency Contacts so that if something happens to me I know that the people I trust will be contacted.

- [x] Rework EC designs to add Relationship and Address
- [x] Address and Relationship will be optional fields (Name and # are required)
- [x] Determine if we default "Relationship" to "Unrelated Friend" in the UI, or just have it default to "Make a selection..."  (AS Note: I don't remember what we say when there is no default option but that) (AS Note 2: [Hieu has proposed defaulting to Unrelated Friends](https://dsva.slack.com/archives/CMJ2V70UV/p1706128977193179?thread_ts=1706123716.573839&cid=CMJ2V70UV))
- [x] Allow user to add two separate contacts
- [x] **Success: We have designs for all four EC fields**

**Comment by IMHieuVo** [comment]
**1 - Relationship, required**: 
- When we initially talked about this, we noted that it should be optional since it does not exist on the paper form. 
- Katelyn noted that there could be a good reason why the API requires the Relationship field that we’re not purview to, such as medical visitation. 
I initially had the mockup default to “unrelated friend”, but after the discussion of the flow, we speculate that the Veteran will try to change the relationship to one that is more reflective of reality. So keeping it optional and defaulting to “unrelated field” does not save time and makes the experience slightly awkward. Leaving the selection blank and making it a requirement may be a better flow.


**2 - Relationship, Not Available**: 
- Something to consider, we noticed the Check-in team’s demo had the Emergency Contact’s relationship as “not available”. Their Figma file had the EC’s relationship as “spouse”.
Demo Link in Slack:https://dsva.slack.com/archives/C022AC2STBM/p1703024152289909

**3 - Adress, Existing:**
- I initially thought that when the Veteran does not fill out the address, dummy data will autofill. Patrick Faulker notes that the address does not exist in soap service, when it does, it can be made optional on the validation. 

Figma Link: https://www.figma.com/file/tggcJk382w9yQ0ElwKfh3N/10-10EZR?type=design&node-id=0%3A11540&mode=design&t=VNxKtCWb3QPzepT5-1
