### ISSUE TITLE
Drupal training: request for intermediate user training session on all the new features and changes

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/va.gov-team#7469]
## Drupal training: request for intermediate user training session on all the new features and changes

@howardbrande - I would like to request a Drupal training session for the following ppl. Preferred scheduling time frame is end of April (so new folks have time to get their CAG/VA email/PIV set up). 

I will send you an email with people CC:d so you have their emails. (Danielle and John are not yet @-able in GitHub.)

1/ Please get training on calendar at least 2 weeks in advance. 
2/ Ahead of the training session, please send out instructions to all for getting access to Drupal. 
3/ Please give the user access type noted below for each person. 
4/ Please include me as well. 
5/ Prior to training, please send complete list of CMS users per this request: [#7325](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7325)

People:
Danielle Thierry - Content strategy - publish access
John Hashimoto - Product - publish access 
Michelle Midaugh - Product - publish access
Randi Hecht - publish access
Anne Hurley - publish access
Laura Walsh - edit access
Selina Cooper - edit access
~Lou Cardoza - edit access~
Kim Mueller - whatever she already has
Peggy Gannon - publish
Ryan Thurwell - review access
Mikki Northuis - review access <--added 4/6
Stephanie Orkland - review  <-- added 4/21

fysa @davidconlon @kevwalsh

**Comment by howardbrande** [comment]
@kevwalsh from @jenniferlee-dsva 

I’d like to take the first 10 mins to run through the editorial workflow process for tier 1 benefit content, and it would be helpful to just do it once. It’s also hard for me to attend multiple sessions. There will also be some people who are attending more for awareness – like Ryan and John – and not because they will be actively working in Drupal themselves.

 Perhaps we can do 1 all-team session and then schedule follow up smaller call for those who need/want more?

**Comment by jenniferlee-dsva** [comment]
^ updated & emailed Howie. FYSA @cmaeng

**Comment by cmaeng** [comment]
This issue looks to have been addressed last year with training. @jenniferlee-dsva please let us know if anything additional is needed to fulfill the need.
