### ISSUE TITLE
Determine where to store documentation for tutorials

### ISSUE THREAD

**Issue by bramleyjl** [department-of-veterans-affairs/va.gov-team#74896]
### Issue Description

SiS documentation is currently primarily hosted at the [va.gov-team Github repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity/Products/Sign-In%20Service). The Identity team should determine the optimal application(s) to host SiS documentation, considering

- Github
- Swagger
- The [VA Platform scrollhelp site](https://depo-platform-documentation.scrollhelp.site/)
- somewhere else

**Comment by acaruso-oddball** [comment]
[Swagger Resource](https://swagger.io/tools/open-source/getting-started/)
[Github Wiki Resource](https://github.com/MyHoneyBadger/awesome-github-wiki)


**Swagger:**
Pros:
- Interactive API documentation: Swagger provides a user-friendly interface for exploring and interacting with your API endpoints.
- Standardized format: Swagger follows the OpenAPI specification, ensuring consistency and compatibility with a wide range of tools and platforms.
- Automated generation: Swagger can automatically generate documentation based on your API code, reducing manual effort and ensuring accuracy.
**- Integration with development workflow: Since Swagger is often integrated directly into the API development process, keeping documentation up-to-date can be easier for developers.**

Cons:
**- Limited scope: Swagger is primarily designed for documenting APIs, so it may not be suitable for documenting other aspects of your project.**
- Complexity: Setting up and configuring Swagger can be complex, especially for larger or more complex APIs.
- Maintenance overhead: Keeping Swagger documentation in sync with changes to your API code can require ongoing maintenance effort.

**GitHub Wiki:**
Pros:
**- Built-in version control: GitHub Wiki is tightly integrated with Git version control, making it easy to track changes and collaborate on documentation.**
**- Familiar interface: Many developers are already familiar with GitHub, making GitHub Wiki a natural choice for documentation.**
**- Markdown support: GitHub Wiki supports Markdown formatting, which is simple and widely used for writing documentation.**
**- Integration with GitHub ecosystem: GitHub Wiki can easily be integrated with other GitHub features, such as issues and pull requests, streamlining the documentation workflow.**

Cons:
- Limited customization: GitHub Wiki has limited customization options compared to other documentation platforms, so it may not be suitable for complex documentation needs.
**- Limited search capabilities: GitHub Wiki's search functionality is basic, which may make it difficult to find specific information in large documentation sets.**
- Dependency on GitHub: Since GitHub Wiki is part of the GitHub platform, you are dependent on GitHub's availability and reliability for accessing your documentation.

**Scroll Help Site:**
Pros:
**- Rich formatting options: Scroll Help Site offers a wide range of formatting options, allowing you to create visually appealing and easy-to-read documentation.**
- Structured documentation: Scroll Help Site allows you to organize your documentation into multiple pages and sections, making it easy to navigate.
- Integration with Confluence: If you're already using Confluence for collaboration and documentation, Scroll Help Site integrates seamlessly with Confluence, allowing you to leverage existing workflows and permissions.
- Advanced search capabilities: Scroll Help Site provides advanced search capabilities, making it easy for users to find relevant information quickly.

Cons:
- Cost: Scroll Help Site is a paid solution, so it may not be suitable for organizations with budget constraints.
**- Learning curve: Setting up and customizing Scroll Help Site may require some learning if you're not already familiar with Confluence and Scroll add-ons.
- Dependency on Confluence: Since Scroll Help Site is a Confluence add-on, you are dependent on Confluence's availability and reliability for accessing your documentation.**
