### ISSUE TITLE
Improve the order of dependent children's addresses in PDF overflow

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#74994]
## Issue Description

Dependent children information is all there, but the order of fields may cause confusion to the reader of the PDF. 

Examples of PDFs

[OverflowTestReviewPage_Jan30.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1XQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bbbe557967a6dc04a082d4272f774e2ac79cfd3/OverflowTestReviewPage_Jan30.pdf)

[OverflowTest_Jan30_PDFgenerated.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd6ccbff6d06a508f1af0afb364e54d625e3464d/OverflowTest_Jan30_PDFgenerated.pdf)

## Acceptance Criteria

**Some suggestions on order of overflow data:** 
Start the overflow list with the child/dependent’s name, and then the rest of the fields that correspond to that person
If they don’t live with them, place amount $ contributed after their custodian name and address

_Example if they live with you:_
- Child name
- DOB
- Place of birth
- SSN
- Child status line

_Example if they DO NOT live with you:_
- Child name
- DOB
- Place of birth
- SSN
- Child status line
- Custodian name
- Custodian address
- Amount of contribution for child

**Comment by emilytheis** [comment]
<img width="403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94e28d7d4d644207965e166206833e4b6e79fe0f/image.png" alt="image.png" />


<img width="549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--711dcacb922bafac6001f07be63defc008cbf939/image.png" alt="image.png" />


<img width="1006" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1VTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ea079ef940ca91715c618b0c858a08d02cf1dd3/image.png" alt="image.png" />

**Comment by aplatt-coforma** [comment]
This ticket should be linked to #74700

**Comment by TaiWilkin** [comment]
@vbellissimo I have some questions regarding this ticket, having dug through the PDF and code a bit more. 

In the UI, we do list the custodian details once for each dependent. 

In the PDF, however, the custodian is listed separately. Specifically, questions 8b-8f are about the first dependent; 8g-8k are about the second dependent; 8l-8p are about the third dependent; 8q asks if all the dependents live with the same custodian, and instruct the veteran to fill out an additional form if not; and 8r asks for the custodian's details. There is no place to state which children live with the custodian, since that's a different form.
<img width="1392" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90684e9e53d4e7f7477fa2421f5686a24a44f1ac/Screenshot%202024-02-02%20at%204.47.36%E2%80%AFPM.png" alt="Screenshot 2024-02-02 at 4.47.36 PM.png" />

The way we list the custodians in the overflow is closer to the PDF's structure than the UI. We list each custodian's information, and then have an extra bit of info where we say which children live with the custodian. Which custodian a question is about is indicated by "Line 1", "Line 2", etc. 

I'm concerned that altering the order of the fields to list a custodian under each dependent might result in confusion for the individual filling out the form, since they'll expect the overflow data to continue to follow the structure of the form (I presume).

**Comment by vbellissimo** [comment]
@TaiWilkin I think what is throwing off the reader of the PDF is that the amount of contribution also in an unnatural place. 

What if we kept the order _as is_ in the overflow for the following:

1. custodian address
2. custodian first name
3. custodian last name
4. dependent living with this custodian

But...

Could we still update the placement of the following fields. So ideally, the field order would look something like:

1. Child name
2. Child DOB
3. Child's Place of birth
4. Child's SSN (_if they have one_)
6. Child status line
7. Amount of contribution (_if they have one_)

Example:

![Screenshot 2024-02-05 at 10 42 10 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/106613300/896af79d-e689-4a9c-b167-2eefcd154054)

**Comment by TaiWilkin** [comment]
@vbellissimo That makes sense - I'll take a pass and see what I can do.
