### ISSUE TITLE
Create middleware that creates trace ID header

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7500]
Create middleware that creates trace ID header

Linked to #7000 discovery

**Comment by lenaecb** [comment]
@saneshark @kreek - this issue is blocked due to Zipkin access correct?

**Comment by saneshark** [comment]
More specifically, it on the VAMF side they're limiting the origin of hosts that can set the trace-id, someone from that side, I think Mike Lemiux or Lemier was looking into it, but yes -- it's blocked.

**Comment by saneshark** [comment]
Lets see if we can find a ticket related to that effort though and link here maybe? I'll ask during scrum of scrum next time.

**Comment by saneshark** [comment]
I think Alastair did a lot of the work. Brad mentioned that Zipkin is currently being evaluated on the VAMF side with something like a 10% sample rate. Even if we were to start providing the trace id it won't provide us with any value in triage until Zipkin is utilized at closer to 100%.

I would say this issue is blocked technically. It could provide real value in the future.
