### ISSUE TITLE
[Discovery] Deploy strategy for Sentry 10

### ISSUE THREAD

**Issue by kfrz** [department-of-veterans-affairs/va.gov-team#7503]

**Comment by LindseySaari** [comment]
**Notes from meeting on 4/1/20:**

- Since we can’t just run the install script, there will have to be some more breakout
- How to use RDS and Elasticache?
- Let AWS manage Postgres
- Should be straightforward to do the breakout of Postgres and Redis
- Migrating the data
- How do we want to do the rollout, how to migrate projects over to it?
- Plan for rollout for switching a portion of the traffic to the new version

**Comment by omgitsbillryan** [comment]
The `vagov-utility` vpc (a.k.a. "VAEC utility") only has 12 ip addresses remaining. This is a problem because an ELB requires at least 20 ip addresses. As a result, we plan on deploying an new Sentry10 ELB and it's EC2 instances in the `vetsgov-utility` VPC and have the RDS & EC in the VAEC.

![image.png](https://images.zenhubusercontent.com/59c291c1b0222d5de4787932/94ee5713-a4a0-4924-9b83-a9b83bdf5af9)
