### ISSUE TITLE
Design Feedback - Pre-Usability Review Medical Device Reordering Tool

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#7504]
**Feedback framework:**
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**User story:**
Design feedback on Pre-Usability Review [Profile 2.0 Connected Apps - FAQ and App Directory pages]

**Template prototype we're reviewing:** 
All states: https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens
Walkthrough: https://vsateams.invisionapp.com/share/8NWBZNBFPMV#/screens

**Do:**

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/409266593) the United States form field is not solid white
- The info alert icon should be consistent across. Please change the icon to black instead of blue. 
- Button on Review & Submit page should be “Submit order” (defer to Peggy)
- On all pages “Finish this application later” seems like weird wording, maybe “finish this order later” (defer to Peggy)

**Try:**
- [Select your supplies > Add batteries screen] - The vertical blue bar on the battery card seems excessive, try removing it

**Consider:**

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/405269598) there is a *lot* of blue bar action happening (both vertical and horizontal)… maybe try a different header for “left ear only” that doesn’t have the blue underline. And maybe we can get rid of the outermost vertical blue bar? And maybe a different “chosen” state for the selected card (instead of a blue outline)

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/406260563) and others, the nested vertical bars are getting a little overwhelming--consider accessibility/content’s feedback about having the information on the page vs tucked into the additional info component 

- Consider having “Do you need to add batteries…” not to be a conditional question on the same screen? But just move to the next appropriate screen depending on the answer?
  - Same thing for “Do you need to order accessories for your hearing aids?”

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407509410) Consider why are there radio buttons and checkbox buttons in the same question? Seems like it should be one or the other.

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407683960) Consider why the unselected box is outlined?

**Definition of Done**

- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out

- [x] Leave any comments for feedback you decide _not_ to take

Emily or Crystabel will close the ticket once those things are all set. Thank you!

**Comment by rebeccawalsh** [comment]
@CrystabelReiter 

**Do:**

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/409266593) the United States form field is not solid white
  - The form field is not white because it's disabled when the checkbox above is selected.
- The info alert icon should be consistent across. Please change the icon to black instead of blue. 
  - Reflected in design
- Button on Review & Submit page should be “Submit order” (defer to Peggy)
  - Reflected in design
- On all pages “Finish this application later” seems like weird wording, maybe “finish this order later” (defer to Peggy)
  - Reflected in design


**Try:**
- [Select your supplies > Add batteries screen] - The vertical blue bar on the battery card seems excessive, try removing it
  - We tried to remove it, but the three pieces of data are linked together as a single child of the category (device) it's under. We've decided to leave it as-is for now before gathering feedback that might affect the paradigm more broadly.


**Consider:**

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/405269598) there is a *lot* of blue bar action happening (both vertical and horizontal)… maybe try a different header for “left ear only” that doesn’t have the blue underline. And maybe we can get rid of the outermost vertical blue bar? And maybe a different “chosen” state for the selected card (instead of a blue outline)
  - Those ear-specific headers were accidentally left in after they were nixed - they've been removed entirely.
- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/406260563) and others, the nested vertical bars are getting a little overwhelming--consider accessibility/content’s feedback about having the information on the page vs tucked into the additional info component 
  - We've heard this feedback from across the disciplines but have chosen to put off reflecting this change until the next iteration as we believe we'll be receiving broader feedback that will make this smaller change moot. Making a change at this point would also overwhelm our developers.

- Consider having “Do you need to add batteries…” not to be a conditional question on the same screen? But just move to the next appropriate screen depending on the answer? Same thing for “Do you need to order accessories for your hearing aids?”
  - Same as the above

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407509410) Consider why are there radio buttons and checkbox buttons in the same question? Seems like it should be one or the other.
  - Sketch symbols got screwed up. They're all radio-only or checkbox-only - fixed.

- [On this page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407683960) Consider why the unselected box is outlined?
  - Copy paste mishap - fixed.

**Comment by CrystabelReiter** [comment]
@rebeccawalsh 

"The info alert icon should be consistent across. Please change the icon to black instead of blue."

There's [one page](https://vsateams.invisionapp.com/share/6MVTG94WNH5#/screens/407889090) where the icon is still blue but other than that this is good to go! 

Thank you for taking the time to read through, apply feedback, and reply to pieces that you're going to look into further. Riley and you did a great job taking this complex process and making it into a digestible order flow.

**Comment by rileyorr** [comment]
Thank you for your feedback, @CrystabelReiter! 

- On this page the United States form field is not solid white
  - For reference, this is a pattern that currently exists on VA.gov and was created by the authenticated experience team. Veterans who live on military bases were listing the country associated with that military base even though the military base is technically US soil. The design prevents other countries from being selected to mitigate mailing errors. I've attached a screenshot of the design in a staging account's profile.  

![Screen Shot 2020-04-03 at 9.38.26 AM.png](https://images.zenhubusercontent.com/5d66a8f72a515f013c440719/73b4b490-6a65-4a9c-ae9b-8ad9b0825095)

**Comment by rebeccawalsh** [comment]
@CrystabelReiter Changed the icon on that one page you noted.

**Comment by CrystabelReiter** [comment]
Thank you for the explanation @rileyorr @rebeccawalsh  That was an oversight on my part! I'll keep this in mind when I'm checking future work. 

Thanks, I will close the ticket.
