### ISSUE TITLE
Discovery - Facilities

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#7513]
**This will include:**
- Parent Facilities
- What is supported?

Create discovery documentation using this template -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/engineering/discovery/FHIR/template.md

While you are working through this discovery doc, please add WIP to doc header

FHIR Resource list -- http://hl7.org/fhir/dstu2/resourcelist.html

**Comment by davem-va** [comment]
Lighthouse (https://developer.va.gov) currently has FHIR APIs for health history and facilities APIs.

The services taxonomy used to show what services are offered at what facility is only 12 deep at the moment.

We do have work on our roadmap to do 2 things:
1) Expand the taxonomy to describe the list of services offered at a facility  from 12 to > 100.  Work to connect to the source that enables this is in progress.
2) Provide a FHIR-facility API/resource  using (1) and the existing APIs we have today.

Please let us know how we might collaborate on this and anything else that might be required here.

**Comment by jbalboni** [comment]
@davem-va I think it might be good to talk with Brad Crosby's team about what overlap exists there. I know they're going to create FHIR apis that put facility data into the FHIR Organization and Location resources.

**Comment by aparcel-va** [comment]
👋 @jbalboni, I work for Dave on the Lighthouse side and can, hopefully, off-load Dave from answering any FHIR-related questions.  Is Brad leading the overall FHIR Discovery Epic (#6387) or just the Facilities-related aspects?

**Comment by jbalboni** [comment]
@aparcel-va There are two streams of work happening:

1. On the VAMF platform (outside of va.gov), Brad Crosby and team are building a services to support scheduling appointments in VistA, using FHIR.
2. We, the VAOS-R team on va.gov, as part of #6387, are doing discovery around how to replace our usage of the current VAMF services that we use with the new FHIR based ones built in 1).

So, it sounds to me like you both Lighthouse and Brad's team would be building a FHIR-based facilities service, and it might be worth talking to see if it makes sense that both teams are doing similar work there.

For the epic this ticket belongs to, I'm not too concerned about where the FHIR based facility data comes from (Lighthouse or VAMF), just trying to figure out how we would use it in FHIR format.

I'm sure @saneshark will be reaching out to you all about your use of FHIR, since we're likely going to have to have vets-api consume FHIR apis and serve them to the va.gov front end.

**Comment by jbalboni** [comment]
Closing because outstanding questions are covered in individual tickets
