### ISSUE TITLE
[CHIP][BUG] Resolve emfile errors in pre-checkin

### ISSUE THREAD

**Issue by brianseek** [department-of-veterans-affairs/va.gov-team#75182]
## Description
There have been these lingering errors in pre-check-in. Research the issue and find a resolution to the problem.

Error: `Error occurred initiating CHIP Pre-Checkin: Status=500, Message=Error getting token from VistA API: getaddrinfo EMFILE alb.prod.vista-api.va.gov`

Turning on advanced monitoring in AWS lambda could help trace the problem.

Relevant Slack threads:
https://dsva.slack.com/archives/C052BC1893K/p1706059310407089
https://dsva.slack.com/archives/C051S52N1C6/p1694013894492499
https://dsva.slack.com/archives/C02UP02HHGX/p1690292058081969
https://dsva.slack.com/archives/C02UP02HHGX/p1689691489567989

## Acceptance Criteria
- [ ] Passes Accessibility checks using axe
- [ ] Deployed to staging.
- [ ] Tested on staging
- [ ] Designer has signed off on the feature
- [ ] Product team has signed off on the  feature
- [ ] Prod validation:
  - [ ] not necessary
  - [ ] scheduled

## Code Review Steps
- [ ] Read ticket details and verify that ACs are met
- [ ] Review code in PR
- [ ] Run branch locally
- [ ] Check that new and updated translations use new keys
- [ ] Check for hardcoded strings

**Comment by lee-delarm6** [comment]
Investigation on this found the Elasticache (memcache) nodes are the bottleneck for this error. It bubbles up errors to various other services causing log bloat and maintenance issues as well as alerts. Since these changes could cost money, we wanted to ping someone like @stephenBarrs for permission before acting

With a maximum `backlog_queue` of 1024, I found with the assistance of @brianseek that the nodes currently run very hot at over 7000 requests at a time, far exceeding the limit of available connections. If this is the bottleneck, we have a few options. We can increase the number of nodes via our devops terraform file (changing a 3 to a 6 is my suggestion to see verifiable results) or we can increase the `backlog_queue`, which I'm not positive we can alter, but we can certainly try, to a number which allows the current maximum number of connections to flow through. This may also incur a cost, since those are held in memory until used.

We can analyze the number of errors thrown per day (since it's around 100k of "EMFILE" errors every day), and see if that number is reduced by this change which should only take a few moments to do, virtually no work for possibly large payoff. If neither of these changes work, we can continue digging.

I did note one thing, one, there were no `backlog_queue limit reached` errors in datadog. This may be due to the fact AWS doesn't bubble those errors up properly, or that this is not the root problem.

**Comment by lee-delarm6** [comment]
@stephenBarrs One of the reasons this made priority is that these errors do bubble up to other services such as Vetext and they wanted us to handle them (since they occur at the CHIP level).

There's no downside to upping the amount of available nodes as far as I know, and they should theoretically scale requests automatically once deployed. There WILL likely be a cost associated with this, although I don't have perms or insight to how much these are costing us currently. I'd assume a 1-1 scale (increase in cost being the same as current cost)

**Comment by brianseek** [comment]
@stephenBarrs Another thing we discussed being a potential fix was to modify initiatePreCheckIn to not call vista at all, eliminating the request strain on vista tokens when a batch of pre-check-ins are being created by vetext.  Since refreshPreCheckIn is always called, we would just fetch the data then. This ties into another backlog item of reducing the patient data we store in LoRota for several days. This is something that you have discussed with us in the past.

But I feel like we could do both. Lee's suggestions would be immediate and the code changes would take time to get planned and prioritized.

**Comment by stephenBarrs** [comment]
This sounds like a good plan to me.  Thanks!

**Comment by lee-delarm6** [comment]
We attempted to increase the number of nodes, which increased the number of errors proportionally. I believe this fix has to be done in code at this point. @brianseek Has some ideas, but further I wanted to add this should probably change:

`const getCacheClient = () => new MemcachePlus({ autodiscover: true, hosts: [MEMCACHE_URL] });`

to this

`const getCacheClient = new MemcachePlus({ autodiscover: true, hosts: [MEMCACHE_URL] });`

(Which will change the way this is called and used as well). This will prevent a new connection being created every time we use getCacheClient or something that uses it. Instead, it will reuse the created item. Since we don't insert anything into this "function", it should be fine to be called as such and reduce the number of newly created connections.

**Comment by brianseek** [comment]
oh that is interesting. So as a func its creating a new instance every time it is used, moving to a var it uses the instance that already exists. Is that what you are thinking?

**Comment by lee-delarm6** [comment]
Yes, exactly, it's what I noticed while trying to find why so many
connections were being attempted in the first place

**Comment by brianseek** [comment]
makes sense to me. Go ahead and try this as part of this ticket and we can do a little CHIP release after a little testing in stage

**Comment by anita-halici** [comment]
@lee-delarm6 it is going to be closed today?

**Comment by brianseek** [comment]
This work has been validated in stage. I think we should leave this ticket here until we have about a weeks worth of data on Prod. We can look at making a CHIP release to get this into prod tomorrow 2/22
