### ISSUE TITLE
Midpoint Review - Design Feedback - Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#75239]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] Swap primary and secondary buttons in prototype
- [x] Find out representative amounts of data for locations and exposures (Emily for locations, VBA via MS Teams - to look in VBMS for exposures) - [asked in Slack](https://dsva.slack.com/archives/C053UDWMH7U/p1707415200973649) - info is likely not available, and if it is, would take 2-6 weeks to get. Skipping this.
- [x] Explore more intermediary summary screens - mock up with large and typical amounts of data
- [x] Explore additional links back to sections on last summary screen
- [x] Tell users they are about to enter more data about those items (as in [step 3 on the current multi-page multi-response flow](https://design.va.gov/patterns/ask-users-for/multiple-responses#how-to-design-and-build---multi-page))
- [ ] Explore other approaches to allow users to return to the parent list at any time to add / remove items - editable card pattern?
- [ ] Confirm whether we are changing flow from other radio buttons or just the one - per [Christine's figma comment](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK?node-id=0:1132&mode=design#693796939) - some [discussion in Slack](https://agilesix.slack.com/archives/C04MJV66ZPC/p1707779704941649).
- [x] Consider feedback from [Design team: sharing feedback session](https://docs.google.com/document/d/1krbpuscXeKusc0O6nZQbdWfJUM4qHn923cbJtSfml48/edit#heading=h.15y8d3fxhkdu)
- [x] Explore current position in the list (i.e. "Post-9/11 Service location 1 of 3: Lebanon")
- [ ] Complete together with [IA Feedback](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/75362)
------
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- [ ] I love the idea of using check boxes for the multiple response pattern. There are a few things to consider with this. I know our current multi page list and loop does not have a "mini" review after adding each item, however our current pattern is also only 1 screen. Your is multiple screens. I would figure out the minimum number of screens and maximum a user may see and then try to solve that issue. If the user needs to go back and edit a date or add a new one the idea of stepping through 12 screens might not be great. You may want to sync with IA and accessibility also, again thinking of a use case with a lot of screens, is cognitive load a concern? You may want to consider [experimental design](https://design.va.gov/about/contributing-to-the-design-system/experimental-components-and-patterns), I think the check box idea has great potential, just some things to work out.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

## Acceptance Criteria for DBEX team
- [ ] Updated mocks allowing a Veteran to come back and add/remove a location/hazards
- [ ] Agreed upon approach with team and OCTO
- [ ] Reviewed by governance team by adding a comment to this ticket
- [ ] Complete the IA feedback ticket

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone
- [x] Add the Collaboration Cycle initiative epic

**Comment by mengA6** [comment]
I put together initial options and [ran them by our internal team for feedback](https://dsva.slack.com/archives/C053UDWMH7U/p1707503984231639).

**Comment by mengA6** [comment]
Updated [Design screens](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=0%3A411&mode=design&t=ikmFLfBXoZEpI8su-1) / [prototype](https://www.figma.com/proto/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?page-id=0%3A411&type=design&node-id=0-1296&viewport=-599%2C-454%2C0.17&t=0Fx49obkqM0SCuX0-1&scaling=min-zoom&starting-point-node-id=0%3A1296&show-proto-sidebar=1&mode=design) . They will change a bit as we address the content and accessibility feedback separately.

Thank you for the feedback! We explored ways to address these points and all the points @erinrwhite mentioned in [Midpoint Review - IA Feedback - Disability Benefits Experience Team 1, 21-526EZ, Toxic Exposure Page#75362](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/75362) and decided with @shannonkford to keep some but not all of them. You can see earlier versions in lower pages in [the Figma file](https://www.figma.com/file/dBKlB23Hs2oa53euXcXmmK/526-toxic-exposure?type=design&node-id=0%3A1132&mode=design&t=aFjdm99hyFNuqNI5-1) (under "----Older Versions----" in the pages list). Noting all the points below:

1. **not** adding any intro / orientation screens for each section that say "Now we're going to ask you when you served in these locations"
    1. Justification: too many screens in an already-lengthy flow. It's especially superfluous when people only select one checkbox. Also the `1 of 3: Afghanistan` header as mentioned next addresses the goal of orientation without adding another screen
2. on date range screens: adding a header like `1 of 3: Afghanistan` to orient users in the list and loop
3. **not adding** "edit locations" links on the screens where we are asking for date ranges
    4. Justification: concern about distracting users from the main task of entering dates, and we will present the edit links on the section summary screen soon after this
5. Adding summary screens for each section (`After August 2, 1990`, `Post-9/11`, `Agent orange`, `additional exposures`), with an `edit locations / hazards and dates link` on the summary screen
6. **no** full Toxic Exposure summary screen since it's duplicative after adding the summary screens per section
7. "we are having a hard time designing this flow because the business rules are asking for a lot of detail. Is that level of detail necessary to process the claim?… If there is flexibility on the business requirements it'll make the form more manageable for Veterans. It's likely a long shot, but I have to ask!"
    8. Yes, very good point. That is the root of many of these challenges. However, we don't have that flexibility to reduce the amount of detail we are asking for right now. We pushed back on this a couple of times, and the response from our VBA stakeholders was that this level of detail is useful and sought after by VSRs for cases where they don't have these aspects of the Veteran's service history elsewhere and need to look it up.
    
Let me know if you have any questions.
