### ISSUE TITLE
Design | Figma migration | Update Use Case Documentation

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#75434]
Now that we've migrated all of our profile (and auth menu) designs from sketch to Figma we need to update our team documentation 

## Acceptance Criteria 
- [ ] use case pages are now pointing to figma instead of sketch

**Comment by andaleliz** [comment]
Working in alpha order. Tomorrow will pick up with military information and go from there. All others complete.

**Comment by andaleliz** [comment]
@mtcA6 we've recently talked about teams who add things to profile are responsible for the maintenance of those things. I realized a few things related to that, which would be very helpful if you could help coordinate.

- We don't have anything about Veteran Status in the military info use case docs
- We have [use case docs for personal health contacts](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile/next-of-kin-emergency-contact/use-cases) that team will need to update once their design files are migrated. I'm not sure of the status of that work.
- Should the Lighthouse team be team be responsible for connected apps docs too? I've already updated those for this round but curious about future maintenance since I know this is a product they requested be added to profile too.

**Comment by andaleliz** [comment]
- Sketch links have been removed from all product outlines
- Sketch links have been replaced with Figma links in all use case docs managed by our team
