### ISSUE TITLE
[BUG][SPIKE][CST] some veterans unable to see claim letters in DDL

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#75471]
## Background

User issues described below.

A-20240105-1293384             Claim ID:         101910317      File #: 

I filed for surviving spouse benefits on September 13, 2023. January 2, 2024 a decision was made on my claim. It says that I can download my decision letter, but every time I try, it says no letters are available. How do I see what decision was made on my claim? 

A-20240105-1292334             Claim ID:         103917212      File #: 

Although it says my claim is closed and a decision letter was mailed, I have not received it and cannot download a copy from the site.  How do I find out the status of my claim? 

## Acceptance criteria

- [x] Investigate why these users are unable to find the letters they're looking for, report findings/recs

**Comment by jerekshoe** [comment]
#### A-20240105-1293384
The user can't see the claim letter in this case because they don't have a File number (VBMS needs the file number to get to the eFolder). There is a document with type 184 in the eFolder when I look using the File number of the Veteran (the one provided above). There is also a document with type `508` labeled 'Award Print' with the same `received_at` date

**Comment by jerekshoe** [comment]
#### A-20240105-1292334
Same as above, this user is not a Veteran and can't see the claim letter because they don't have a File number (see explanation above). I do see a 184 doc in the eFolder and there is a doc with type 508 with the same `received_at` date as well

**Comment by jerekshoe** [comment]
#### Update (2/13)
Found the issue with both of these cases, if there are any plans to fix these then those will happen in a different ticket. @jacobworrell you can see my findings above
