### ISSUE TITLE
Apply application unique IDs to supporting documents

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#75508]
As a PEGA analyst of the submitted forms, I would like a unique identifier that ties a given 10-10d to its supporting documents. 

Acceptance criteria
- Each submitted form 10-10d has a unique identifier
- Supporting documents uploaded along with a given form 10-10d will have the unique ID for that 10-10d in their metadata

**Comment by cloudmagic80** [comment]
As a PEGA analyst of the submitted forms, I would like a unique identifier that ties all the forms together. The unique identifier will be in this format: "91400c95-a44d-4191-830e-703ba7266eff" and this id will be on the top center for each form submitted including the attachments.

**Comment by dhill802** [comment]
@baltes

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/15866

**Comment by cloudmagic80** [comment]
@baltes   Do we need this ticket? The UUIDs are already embedded in the file name.

**Comment by baltes** [comment]
@cloudmagic80 The AC for this are specific to metadata rather than the filename. The important part is that we're confident going forward that we're implementing that UUID in a way that lets us identify all documents related to a specific application. So, for example, if someone isn't sure 6 months from now what happened to that birth certificate that was attached to Peter Griffin's 10-10d, how confident are we that we can track it down and provide as much information about it as possible? Should we also include the UUID in the metadata so we have some redundancy? Open to thoughts, but we should consider whether this is helpful in the metadata so we're confident in the relationship we're recording between files.

cc @balexandr since you're also working on metadata

**Comment by cloudmagic80** [comment]
https://github.com/department-of-veterans-affairs/vets-api/pull/16006/files

**Comment by cloudmagic80** [comment]
@baltes Morning Bo. Please take a look at this and close if appropriate!
Thanks

**Comment by baltes** [comment]
@cloudmagic80 I see the link to the PR, but I think we need sample files or something a non-engineer can use to verify that the work is done. There should be verifiable output that can be attached.
