### ISSUE TITLE
VetsAPI: Determine routing strategy for Oracle Health appointment requests

### ISSUE THREAD

**Issue by drewconnelly** [department-of-veterans-affairs/va.gov-team#75505]
To facilitate cancelling of appointments at Oracle Health sites via VetsAPI, we must first determine how to properly route appointment requests to the correct backend system.

Research how the current VAOS module hosted on VetsAPI routes requests to OH and determine whether it will work for an OH cancellation request. If not, document the reasons here and create follow-on Stories for implementing the necessary changes to enable this routing.

**Comment by devin-mccurdy** [comment]
The base va-mobile URL is configured in application config, but won't need to be updated to make use of VPG instead of vaos-service.

The request path and method can be updated in the relevant service behind a feature flag.

As an example, if we were updating path used to update appointment status, we could check a feature flag within `modules/vaos/app/services/vaos/v2/appointments_service.rb` to make either a PATCH request to `/vpg/v1/patients/#{user.icn}/appointments/#{appt_id}` or a PUT to `/vaos/v1/patients/#{user.icn}/appointments/#{appt_id}`
