### ISSUE TITLE
Spike - Investigate the 401 errors in production

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#75632]
The production pension inProgress is generating 401 errors.
<img width="442" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1JBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--005540ee331e30615ebc6f5a751eb78a9b716769/Screenshot%202024-02-08%20at%2010.15.50%E2%80%AFAM.png" alt="Screenshot 2024-02-08 at 10.15.50 AM.png" />

This may not be an issue because it is being handled by redirecting a user to authentication.  However, it might be something else un-handled.  

This spike is to investigate the 401 errors and determine if there are any necessary steps to take to resolve it.

**Comment by mjknight50** [comment]
These continue to decline:
0.068%

**Comment by TaiWilkin** [comment]
@mjknight50 I've determined the specific cause of the increased 401 errors prior to 100% release, and their relationship to the flipper. 
In the normal flow of the application, logged-out users first enter (or are redirected to) a page where they are given the option to either log in before beginning the form or start a new form without logging in. If they start without logging in, we don't attempt to fetch their form; if they log in first, their form is fetched with no 401 error. The only way for them to get a 401 error is if their authentication times out when they're already in the form, in which case their next autosave will return an error. 
In the flow while the application was disabled, ALL users were directed to a page which immediately checked if the user had a saved form, regardless of whether they were logged in yet. If the user is logged in, this allows us to tell them whether they had a form in-progress. If they're logged out, there's a 401 error caused by attempting to load a form for a logged-out user (no visual error for users). This explains the huge difference in 401 errors between the disabled an enabled flow. 
Image from DataDog demonstrating the drop in errors when the form was re-enabled:
<img width="890" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWk3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8dd14f20a81f2143fe204a68753d4b767e00784d/Screenshot%202024-03-06%20at%2012.23.20%E2%80%AFPM.png" alt="Screenshot 2024-03-06 at 12.23.20 PM.png" />
