### ISSUE TITLE
Global Typography changes

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va.gov-team#75641]
## Description
[Original RFC](https://vfs.atlassian.net/wiki/spaces/DST/pages/2775253429/RFC+Migration+Strategy+Formation+to+CSS-Library)

This initiative tracks the progress of sunsetting Formation in favor of the new CSS Library which will house all of the styles (element selectors, utility classes, variables, tokens, etc) VA.gov imports and uses. There are 4 high level steps in this migration:
1. Set up [CSS Library](https://github.com/department-of-veterans-affairs/component-library/tree/main/packages/css-library) so it's maintained separately from the component library.
2. Migrate global base styles from Formation to CSS Library
3. Migrate application utility class usage 
4. Archive Formation

High Level User Story/ies
As a VFS team member, I want the VA design system typography to be up-to-date so that my apps are using the USWDS font. 

Hypothesis or Bet
If we update the typography globally, all apps will be using the USWDS font so all VFS team apps are using the latest font so there is consistency across VA.gov. 

OKR
Quarterly Operations and Maintenance Delivery - (Q1) FY Q2 2024

Definition of done
What must be true in order for you to consider this epic complete?
We have updated typography to the USWDS font.

**Comment by humancompanion-usds** [comment]
Current plan is to change the underpinnings of VA.gov to move from a base size of 10px to 16px to match USWDS, with no user visible changes, on Wednesday 5/22. We'll make this change available to teams on 5/8 in a Preview environment and then give teams a sprint to visually QA their applications (they should see no change and that should be fast). We've already done this QA on a number of applications and pages across the site. 

Once we deploy that change on 5/22 we'll then make available in Preview the final change of bumping up the base font-size from 16px to 16.96px (the normalized size of Source Sans Pro in USWDS) which will be user visible. Again teams will have a sprint to verify. If all goes well then we will deploy that change on Wednesday 6/5.

**Comment by humancompanion-usds** [comment]
We did a bit of refinement on this earlier this week.

## Typography Step 1: Root change from 10px to 16px - Wednesday May 22nd

* The ask: Visual QA starting on May 8th and lasting one sprint.
* IMPORTANT: There should be no visual changes due to this code change. 
* This change alters the underpinnings of the entire typography setup in the system and prepares us to match the USWDS and bump up our base font size. 
* The Design System team has done [visual QA detailed in this spreadsheet](https://docs.google.com/spreadsheets/d/1rztXbVQdwD3ZuHHH89fvKN2tmKqH_Wo99Opg84t2UE0/edit#gid=0). We are asking VFS teams to go over their specific applications. Pick some heavily trafficked exemplary pages and visually QA those. Our expectation is that if those look okay then your application is likely going to be fine with these changes.

## Typography Step 2: Increase base font-size from 16px to 16.96px - Wednesday June 5th

* The ask: Again visual QA starting on May 22nd and lasting one sprint.
* IMPORTANT: Focus on reviewing any "imposter", or exempted v1, components. No development is required, only QA. The base font size increase should not break imposter or v1 components since those will inherit both the new base font size and also the scaled rem values. However, given that they are not Design System web-components the Design System team will not have been able to QA them in advance.
* NOTE: v3 web-components have already moved to 16.96px within the components and you will have already moved to v3 by now.
* This change increase our base font size to match the normalized value of 16.96px for Source Sans Pro in the USWDS.

**Comment by caw310** [comment]
Update for Q2
Typography Step 1: Root change from 10px to 16px - deployed May 22. 
Typography Step 2: Increase base paragraph font-size from 16px to 16.96px will be done Wednesday June 26th.

**Comment by humancompanion-usds** [comment]
Step 2: Font size increase from 16px to 16.96px will merge later today.
