### ISSUE TITLE
[Research, Product] VA.gov Onboarding: Kickoff + deep dive

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#75798]
## Background
To officially begin our work to create a solution for first time onboarding to va.gov we will have an internal kick-off and deep dive to share what we know and a bit about the history behind this work.

## Tasks
- [x] AJ to schedule "what's next convo"
- [x] Hold "what's next convo"
  - Liz to share [research review](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/research-review.md) and [comparative analysis findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onboarding/discovery-research/comparative-analysis.md)

**Comment by andaleliz** [comment]
When we have this meeting, something that would be good to better understand is the parallel transition work VES is doing. When I met with Samara, she hadn't yet met with them to learn about their work. Since then we’ve confirmed it makes sense for us to continue with our work, but I'm curious what their plans are for the MVP discussed in their channel, where it will live, etc.

**Comment by ajakabcin** [comment]
Pushing to next sprint due to high priority direct deposit work.

**Comment by andaleliz** [comment]
@ajakabcin I thought of something else that would be really helpful to review during the kickoff - what is the problem we're trying to solve?  What I know so far is:
1. We wanted to learn "where does VA.gov fit into the transition process?" so we looked at previous research + the experience of leaving the military and becoming a veteran
2. We want to explore an onboarding solution for VA.gov

IMO so far this is framed as if we are working toward a solution without really defining what the problem onboarding is intended to solve. I think it'll be important for the whole team to be clear and aligned on whatever that problem is before we move toward a solution.

**Comment by ajakabcin** [comment]
Due to scheduling we're going to have a re-cap/what's next convo with Samara and Chante and then another convo when Alex is back from pto/her move.

**Comment by ajakabcin** [comment]
Going to close this out and get Alex up to speed separately

**Comment by andaleliz** [comment]
@ajakabcin are we not going to get the rest of the My VA folks up to speed? Matt was interested in learning about this too.  If we're not involving the rest of the team, I can present to him separately.

**Comment by ajakabcin** [comment]
Oh I'm sorry you're right - not trying to keep the rest of the team out of this. I'll schedule a separate deep dive for the broader team.
