### ISSUE TITLE
[EKS,Helm] Add labels to all shared service deployments

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#75951]
- Add labels to all deployments to make future network policies simpler
- https://github.com/department-of-veterans-affairs/vsp-platform-infrastructure/tree/main/terraform/modules/platform-distro
- This is only for Platform v.Next cluster, and not the current live clusters

## Labels:
- service: shared, 
- application (DD, trafik, etc..)

If you think of additional labels that might be helpful, create a new ticket and we'll pick it up at a later date

Be sure to test it!

**Comment by Efe-Oddball** [comment]
I have created the labels and added to all the deployments. Will be testing with NEXT Clusters before creating PR

**Comment by Efe-Oddball** [comment]
I have intergrated the labels for most of the helm deployments in vnext clusters. However, I am having issues with csi_efs, cilium, and datadog-agent.

**Comment by Efe-Oddball** [comment]
Most of the labels have been updated in vNext clusters. More work is required for Platform, priority-class and overprovisioner helm deployments as the source helm chart values.yaml will have to be updated.
More work will also be required for csi_efs, cilium and datadog helm series. as for csi_efs, the way we currently have it configured with a wrapper is not the same way it is set within the source repo, so the set values.yaml file is possibly being overwritted by the default source.
cilium and datadog-agent label addition have not been quite straight forward, possibly due to multiple layers within the helm deployment.

I will either roll this ticket over or close this out, create a new ticket to tackle the rest considering more work will be required to add the necessary labels to those deployments.

**Comment by ph-One** [comment]
Please close this ticket to show the progress already made, and create a ticket _per service_ that remains

**Comment by Efe-Oddball** [comment]
Moving this ticket to a resolved state.
