### ISSUE TITLE
[FwdProxy to AL2] Dockerfile creation for HA Proxy Configuration

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#76238]
## Description
In order to complete the effort of moving FwdProxy to AL2 we need to create a stable Dockerfile that will add all necessary HA Proxy configuration

## Resources 
- https://github.com/department-of-veterans-affairs/vsp-platform-revproxy/tree/main/template-rendering

## Acceptance Criteria
- [x] Identify and load 2.X HAProxy Configuration Image into ECR
- [x] Design Dockefile build that leverages the current config file locations (need to minimize interference with current user processes)
- [x] Test locally or via GHA that the end Image has everything needed to function as our current FwdProxy instance does

## Refinement Guidance - Check the following before working on this issue: 
- [x] _Team label assigned ("platform-tech-team-2")_
- [x] _Epic assigned (if needed)_ 
- [x] _Estimated (points assigned)_
- [x] _Sprint assigned (once planned)_
- [x] _Team member(s) assigned_
- [x] _Understands how this work aligns with the overall platform_

**Comment by barbarello** [comment]
- refactored fwdproxy-vagov-dev.yml  into fwdproxy-vagov-dev-vars.yml  and fwdproxy-vagov-dev-tasks.yml so that variables and tasks can be included or imported separately into the main playbook.
- refactored main playbook layout (renderer.yml) 
- reworked Dockerfile to include missing user, directories and volumes
- tested locally for deployment_env = dev
