### ISSUE TITLE
Spike: LOE to update mapping to new version of PDF using checkboxes (instead of radio buttons)

### ISSUE THREAD

**Issue by vbellissimo** [department-of-veterans-affairs/va.gov-team#76388]
## Issue Description

- The VBA team is intending to change all questions on the Pension PDF currently using radio buttons to checkboxes.
- The rules about the number of options they can currently select varies among these questions (single choice vs multiple choice). _This update to checkboxes will not change any existing rules about the number of options they can select._

---
## Tasks
- Investigate the number of questions currently using radio buttons on the PDF (these will change to checkboxes).
- Investigate how this update may affect the data mapping of these questions.
- Investigate if/how this update may affect data mapping on a broader scale.
- Provide an estimate of the level of effort it would take to update the online Pension form to map its data to an updated version of the Pension PDF that replaced radio buttons to checkboxes.

**Comment by danlim715** [comment]
@vbellissimo 
- There's 183 different radio buttons on the PDF (if I counted correctly).
- This change will not affect the data mapping of the questions, since the appearance is just an option you can toggle per field. These are the different appearance options for all single and multi-select button fields: <img width="298" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjEwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--233ab9ce812518d303bba1ced62c1bec94e7cee8/image.png" alt="image.png" />
- It's a little bit tedious, but the change is straight-forward and should take maybe an hour or 2, depending on how much sanity the dev has left while working on this change. Whoever works on this will need Acrobat Pro access (so it will probably be me). I can take a break from ITF and knock this out in the next few hours if it's a higher priority.

**Comment by aplatt-coforma** [comment]
@vbellissimo - something to consider this that @danlim715 Acrobat Pro license was only approved for 1 month. So if we want him to do it, we should proceed soon. I believe it expires on 2/23.
