### ISSUE TITLE
FE/PM | EDU CH33 Changes | Analytics (I think it's important we track based on EDU, C&P, Both)

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#76723]
Since we're migrating away from two separate forms in the UI, we're going to need to enhance our GA tracking to capture more information about what behaviors are happening. 

We'll want to make sure the different scenarios have the appropriate level of tracking so we can determine if there are issues for specific types of users. Eg. is an error occurring for C&P users or is it occurring for users who have C&P and CH33 Edu. 

## Acceptance Criteria 
- [ ] we have direct deposit tracking in the new GA4 forms page

**Comment by adamwhitlock1** [comment]
We need a concrete task list here for me to implement. I'm not exactly sure what I need to do for this.

In our current analytics dashboard, we have the error-keys captured, for example:

```
cnp.payment.night.area.number.invalid | No changes were made. Request was sent to Benefits Gateway Service (BGS), but BGS update failed. Unknown issue(s). Raw response from BGS: 'Update Failed: Night area number is invalid, must be 3 digits'-enroll
```

Once the implementation of unifying the EDU and CNP data is set up and we know about how the BE will providing errors we should be able to add additional data if it's available, but otherwise I'm not sure what else to do for this ticket.

**Comment by mtcA6** [comment]
@adamwhitlock1 [is this the right board to look at](https://analytics.google.com/analytics/web/?authuser=0#/dashboard/naG_-UneTxy50WvvIH0GGQ/a50123418w177519031p176188361/_u.date00=20240414&_u.date01=20240423/)? or the sandbox?

**Comment by adamwhitlock1** [comment]
That is the right board to look at, except you want to look at it for non-production in order to see the UNIFIED events
