### ISSUE TITLE
Identify any additional screens needed for MVP

### ISSUE THREAD

**Issue by karafaithsanchez** [department-of-veterans-affairs/va.gov-team#76830]
### Description
After we've defined and prioritized top tasks and the site architecture, we need to identify any additional screens needed for the MVP (as currently defined). If any are considered out of scope, do not build out yet, until they've been approved as additions to the MVP by team and VA stakeholders.

### Output
- A list of screens and roughly what they should include

### Leads or Collaborators
- Lead: @kristen101606 
- Co-lead: @karafaithsanchez 

### Resources
- [add as needed]

### Acceptance Criteria
- [ ] A list of screens and roughly what they should include

**Comment by kristen101606** [comment]
Screens for usability testing are underway. We've already begun refining the features we'll include in MVP after our feature evaluation workshop, and I'm translating those into screens in our [Figma file](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=410%3A10081&mode=design&t=XATX29S5EJGL6Cql-1). Since this work is in progress and addressed as part of the [Version 1 designs ticket](https://app.zenhub.com/workspaces/accredited-representative-facing-team-65453a97a9cc36069a2ad1d6/issues/gh/department-of-veterans-affairs/va.gov-team/76829), I'll close this one.
