### ISSUE TITLE
Implement analytics - Find VA Forms Search

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7691]
## Background
We're preparing Find VA Forms Search for launch and that includes [a request for analytics](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7174). 

We have [tasks on our end](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7174#issuecomment-608043998) to implement to track certain interactions.

## Goal
Analytics tracking implemented on Public Websites end for Find VA Forms Search

**Reference: analytics request - https://github.com/department-of-veterans-affairs/va.gov-team/issues/7174**

---
## Developer Notes

From here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/7174#issuecomment-608043998
- Dynamically populate the DL variable ```featured-content-header``` with the header for each blue box

Interaction | Screenshot | Datalayer Requirements
------------ | -------------  | -------------
Clicks on Top Tasks blue featured content (Read more) | ![image](https://user-images.githubusercontent.com/48527022/78290004-09e27d80-74f1-11ea-90d5-e3febfb78904.png) | ```dataLayer.push({```<br>```'event':'nav-featured-content-link-click',``` <br>```'featured-content-header': 'File a VA disability claim'```<br>```});``` | 
Clicks on links within "Manage your VA and other information online" section | ![image](https://user-images.githubusercontent.com/48527022/78290306-8e350080-74f1-11ea-9702-69cafc30c25f.png) | ```dataLayer.push({```<br>```'event':'nav-header-link'```<br>```});``` | 
Clicks on links within "More information" list | ![image](https://user-images.githubusercontent.com/48527022/78290447-c2102600-74f1-11ea-8939-d19081ef3ab1.png) | ```dataLayer.push({```<br>```'event':'nav-linkslist'```<br>```});``` |

## Acceptance Criteria
- [ ] Confirm we're not already tracking analytics for Find VA Forms components
- [ ] Analytics tracked for Find VA Forms Search

**Comment by MickinSahni** [comment]
Sprint 19 Planning
- Confirm we're not already covered

**Comment by ncksllvn** [comment]
This is a bit confusing so I'm going to try to map things out -

> Clicks on Top Tasks blue featured content (Read more)	

We definitely have to implement this, because these are hardcoded in React code since Drupal only supports them on VAMC pages. The event also aligns with the event at `/pittsburgh-health-care/health-services/`, so that's good.

> Clicks on links within "Manage your VA and other information online" section	

This is a global event that needs to be set up. Find Forms is just using a Drupal template for this like other Drupal pages. Ideally this request would come through recognizing this as a global event, but we can do this change here.

>  Clicks on links within "More information" list	

Also a global event for the same reasons. Looking into this to make sure that the global event is set up, I found a conflict. On Find Forms, these links are already set up to trigger the event `nav-linkslist`. However, this issue calls for the event `nav-header-link` to trigger. I don't know which is correct.

**Comment by MickinSahni** [comment]
- Nick to ask Jon and team for clarity on 3rd scenario
- note: the update associated with the second scenario will affect more than the Find VA Forms Search page

**Comment by jonwehausen** [comment]
@MickinSahni Okay - didnt notice there was `nav-linkslist` already on those "Manage your VA Info..." We can use that existing structure.

**Comment by kelsonic** [comment]
Interaction | Screenshot | Datalayer Requirements
------------ | -------------  | -------------
Clicks on links within "More information" list | ![image](https://user-images.githubusercontent.com/48527022/78290447-c2102600-74f1-11ea-8939-d19081ef3ab1.png) | ```dataLayer.push({```<br>```'event':'nav-linkslist'```<br>```});``` |

Looks like this one is already implemented as desired.

![image](https://user-images.githubusercontent.com/12773166/79233433-15ee0980-7e26-11ea-8607-34f5fd4c71de.png)

Thus, per @jonwehausen's comment, @ncksllvn the below 2 items are already implemented as desired:

Interaction | Screenshot | Datalayer Requirements
------------ | -------------  | -------------
Clicks on links within "Manage your VA and other information online" section | ![image](https://user-images.githubusercontent.com/48527022/78290306-8e350080-74f1-11ea-9702-69cafc30c25f.png) | ```dataLayer.push({```<br>```'event':'nav-header-link'```<br>```});``` | 
Clicks on links within "More information" list | ![image](https://user-images.githubusercontent.com/48527022/78290447-c2102600-74f1-11ea-8939-d19081ef3ab1.png) | ```dataLayer.push({```<br>```'event':'nav-linkslist'```<br>```});``` |

I sent up a PR to address the first AC: https://github.com/department-of-veterans-affairs/vets-website/pull/12212

**Comment by ncksllvn** [comment]
@kelsonic @jonwehausen Sorry, my comment wasn't accurate.  On the `More information`, we do already trigger `nav-linkslist` so that one we can cross off. 

I don't think the analytics are set up at all for `Manage your VA and other information online` though.

**Comment by kelsonic** [comment]
@ncksllvn I can't seem to find the liquid template for `Manage your VA and other information online` 🤔Do you have an idea where that might be in `vets-website`?

**Comment by ncksllvn** [comment]
Looks like it's `fieldRelatedLinks` - 

![image](https://user-images.githubusercontent.com/1915775/79236916-91a68100-7e3b-11ea-97ff-15b0064efd17.png)

**Comment by kelsonic** [comment]
Huh... so actually those fields are just being rendered inline without any templating surrounding it aside from this file: `src/site/paragraphs/wysiwyg.drupal.liquid`, which I believe means if we want to add analytics to those links it has to be added on Drupal... @ncksllvn

**Comment by kelsonic** [comment]
PR merged! https://github.com/department-of-veterans-affairs/vets-website/pull/12212

**Comment by stephorkandatx** [comment]
@kelsonic this is a comment that @jonwehausen left on #7174 , after your PR was merged. I cannot tell if this feedback was incorporated into your Acceptance Criteria or made its way to you & the PR. Can you take a look and let me know your thoughts?

" @MickinSahni Apologies for not including in original, since we need to correct the "Manage your VA and other information online" section -- if for the "Manage your VA and other information online" and "More Information" nav-linkslist event, if we could also add in the DL variable links-list-header with the each click, that will aid us in identifying each click more simply." with an example attached to the comment in #7174 .

**Comment by kelsonic** [comment]
Hey @stephorkandatx! So this PR only completes the first AC for that ticket. The 2nd and 3rd ACs are actually blocked until [this semi-related PR is merged](https://github.com/department-of-veterans-affairs/vets-website/pull/12250).

![image](https://user-images.githubusercontent.com/12773166/79576151-0f5ace80-8080-11ea-86b0-74efeb9be959.png)

AC 3 was already implemented long long ago (in a galaxy far far... nevermind lol). But AC 2 requires us to dynamically add the click event in our templates, maybe @ncksllvn you can include it in your [current PR](https://github.com/department-of-veterans-affairs/vets-website/pull/12250) if it's relatively low LOE?

**Comment by ncksllvn** [comment]
I'm noticing that the whole `Helpful online tools` section is WYSIWYG content. I think we should leave the heading and the paragraph below it as a WYSIWYG, but the links should be converted to the "list of link teasers" content model in Drupal. 

I suggest this because I'm implementing some complex analytics for the Coronavirus page over at https://github.com/department-of-veterans-affairs/va.gov-team/issues/7890 and Find Forms will inherit the same event-tracking for free if we switch to that content model. Otherwise, I don't think we'll be able to do this tracking on Find Forms because `Helpful online tools` is just raw WYSIWYG content without any clear way for us to attach selectors to capture events.

**Comment by stephorkandatx** [comment]
@beeyayjay this is the ticket we discussed

**Comment by stephorkandatx** [comment]
We separated the work for the Helpful Online tools section into a new ticket. 
Closing this one out.
