### ISSUE TITLE
[Team] 10-10EZ AND EZR: Come up with Error and Outage Procedures for 1010 Team

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77008]
**Must be done be March 5 TERA Launch**

As a Veteran, I would like the 1010 EZ and EZR forms to always be available and working so that I can apply for Healthcare and update my VA information online at my convenience. 

- [x] Review our documentation for "Monitors, alerts, and actions" [CG](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/caregivers/10-10CG%20Form/Existing%20Monitors%20and%20Alerts.md), [EZ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/Monitors%2C%20Alerts%20and%20Actions.md) and [EZR](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/10-10EZR%20Form/Monitors%2C%20Alerts%20and%20Actions.md) on responding to incidents and outages (AS: I have also created some notes [here](https://docs.google.com/document/d/1m0D35RI0KOTTN0u2ZlDRD9f0YHEefHEk8rFquK7t1v4/edit))
- [x] Expand upon and come up with specifics for a standardized way to respond to issues, who will respond, who will investigate, who will facilitate and communicate (e.g. who is "on call?" What does the first responder do? Who investigates issues, etc.)
- [x] Document these things in a shared repository
- [x] Present to Alex and Heather
- [x] **Present to Patrick**
- [x] Make changes as requested
- [x] Come up with any action items/access requests (e.g. Pager Duty)
- [x] **Success: The ENTIRE team has standardized ways of responding to EZ and EZR errors and outages 

Maybe future iteration: - [ ] Come up with a window for the team to be "On Call" (this doesn't seem to be contractually defined so I would propose 8am-6pm ET)

**Comment by luis-simauchi** [comment]
Version one of the error & outage procedures:

Acknowledge & Communicate that there is an error or outage present
 -- Should be handled by the Data Analyst & PM team first as they typically have eyes on this. However Devs should be receiving notifications that an error or outage is present (when an alert captures it) and can start preparing to address it.

Informing Product owners that there is a problem (i.e. Tell Patrick, Adrian, and Kristen, etc...)
-- PMs can inform the stakeholders that there is an issue

Review the errors (if any) and VA.gov monitors to determine if the root cause is on the form or sitewide
-- Data analyst is the first one on the scene here; Check logs to determine a root cause if possible (DD, Sentry, etc.). But as the investigation furthers past the dev op tools in place, Dev team will be pulled in shortly there after these sources have been exhausted.

Mini Check Ins (1-2 hours)
-- Devs (when possible) to communicate a root cause when identified. Or update the team that a cause is still unidentified within the first hours of the triage process.

Tell Stakeholders (HEC, CG team)
-- PMs can inform the stakeholders that there is an issue, or communicate that the scope of the issue extends outside of the code base we have access to with a context given by Devs.

Talk to Platform
-- If needed we can communicate with the platform team of changes or reverts needed in the code base or that there needs to be other engineers from their side present to triage the problem.

Talk to CoPs (link to chats)

Start postmortem and document timeline as you go
-- This is everyone contributing to the doc as they continue to do their part in the overall procedure.

**Comment by emily-brown34** [comment]
@luis-simauchi  based on our discussion today and the above team agreement, please update the existing documentation to reflect the 'new' process(es)

@alexseelig @hdjustice for tracking

**Comment by luis-simauchi** [comment]
document exists here on the github repo: 
products/health-care/application/va-application/Error and Outage Procedures for 1010 Team

**Comment by JoshingYou1** [comment]
Do we have to do a post-mortem for every error? If not, maybe we can adjust the last point to be specific to outages?

**Comment by alexseelig** [comment]
@JoshingYou1 Not for every error, no. But for almost every outage, and certainly every major outage.

**Comment by Mitch-A6** [comment]
Would the postmortem be where we'd discuss systemic changes to prevent the issue / improve mitigation? 

Like, if we frequently need to gather contact info for affected vets, where could we discuss something like building a tool for nontechnical folks to be able to get that info? (with appropriate access constraints and safeguards, of course)

**Comment by alexseelig** [comment]
@Mitch-A6 A postmortem is certainly one place for that. But that's also something we could discuss as a team, be it in Retro, Parking lot, Refinement/Planning, etc.

**Comment by luis-simauchi** [comment]
CG outage procedure is not included in this! it has its own thing for that form

**Comment by luis-simauchi** [comment]
new doc name:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/application/va-application/Error%20and%20Outage%20Procedures%20for%201010%20Team.md

**Comment by luis-simauchi** [comment]
added a small blurb for "in case of PT afternoon time"

**Comment by luis-simauchi** [comment]
what happens with luis is out (planned or unplanned)?
– Heather is capable of doing all of the DD & sentry related tasks associated with this exercise. Alex can also dive in as he has gone through one training session with myself about error tracking. We can train other members of the team if need be.
under what circumstances are different groups informed (product owners, stakeholders, others?). defining these ahead of time is much easier than trying to decide in the moment.
– If the error or outage persists for longer than 1 hour / leads to multiple failures of form submissions / or a spike in error rate that exceeds 10%; then the PO is informed there is an issue.
– If the error / outage persists for longer than 4 hours / leads to multiple failures of form submissions / or a spike in error rate that exceeds 10%; then HEC is informed that there is a full stop blockage preventing veterans from accessing benefits
who serves as incident commander? what are the responsibilities of the incident commander?
– I nominate Emily Brown, as the tasks / responsibilities of an incident commander most closely align with that of a delivery manager so she is best suited to tackle the role.
	– How does an incident commanders handle critical incidents:
Identify the objectives of the incident response.
Next, devise a command plan to address the problem. Can be more of a collaborative effort
Monitor the situation and make adjustments as needed.
For notifying HEC of an issue:
that should always be done by an OCTO person
– Got it, can do! the HEC distribution list should be used instead of individual emails
what happens if an OCTO person cannot be reached?
– PMs should be viable backups for OCTO/PO.  In the event PO is not available, the team could reach out to Crew Lead (Currently Lauren Alexanderson) if OCTO representation is needed
at what point is a call set up? again, defining the criteria for all jumping on a call together makes it easier than deciding to do so in the moment.
-- still fleshing this out
how are maintenance windows handled? who makes the call? what is the criteria?
– Patrick can make the call to put up the maintenance windows if we determine that the error / outage is severe enough to warrant. Maintenance window’s length of time will be assessed on an hourly basis of whether we can isolate the problem and push a hotfix out to prod within the hour.

**Comment by hdjustice** [comment]
Pending final review from Patrick

**Comment by emily-brown34** [comment]
I've created the following new document https://docs.google.com/document/d/1r8w7BkE18F-yC7e1hd16-N7_zl_0XWCq2NuE39XUojw/edit 

Luis to review and edit by EOD today

**Comment by luis-simauchi** [comment]
@emily-brown34 
doc refresh for the SOP: https://docs.google.com/document/d/1r8w7BkE18F-yC7e1hd16-N7_zl_0XWCq2NuE39XUojw/edit
