### ISSUE TITLE
[Ongoing support] PII

### ISSUE THREAD

**Issue by npeterson54** [department-of-veterans-affairs/va.gov-team#77283]
- Slack thread https://oddball.slack.com/archives/C044WM9PBMY/p1706023713355099

**Comment by ph-One** [comment]
Spun up a debug container within the compactor pod to make `localhost` calls. Same results as before -- 404's

**Comment by ph-One** [comment]
Because logs are stored in Datadog and Loki is redundant for this time period, I axed the log files since the API was not supporting deletion. I also cleared all Loki Querier cache. The query below resulted in 16 records; it is now returning 0 records.

<img width="1613" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3JUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--def5855d1467431c9b3ee9f7d3a4af18a9cc2a51/image.png" alt="image.png" />
