### ISSUE TITLE
URGENT [FE] 10-10EZR: Build new widget for static page content on 3/4

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#77517]
- [ ] Use the existing widget to build a new widget to fit static page
- [ ] Work with Matt L to copy over files
- [ ] "Register" widget
- [ ] Make sure content is the latest, including the change "millions more Veterans" to "millions of Veterans" (This can go out on 3/6)
- [ ] Turn widget on
- [ ] Notify Aliyah that the widget is ready
- [x] Add content (waiting on @aliyahblackmore for content)
- [ ] Have UXers and/or QA review for accuracy
- [ ] Make sure it works for both users who can see the online EZR, and those who can't, and that the content references or doesn't reference the online EZR accordingly
- [ ] Release to Prod
- [ ] **Success: New widget with updated content on EZR static page on 3/4, it is turned on and we notify Aliyah to tell the copy editor**
<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL21tQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34716d5ab41bf823fbf7f94d36c8c0793ea70149/Screen%20Shot%202024-03-01%20at%2012.30.40%20PM.png" alt="Screen Shot 2024-03-01 at 12.30.40 PM.png" />

**Comment by aliyahblackmore** [comment]
Hi folks here's the alert content. 

Again, to recap, since the online EZR form is still launching incrementally we need two versions of this alert. This is an information alert.

Once you all have the widget code, our copy editor will need you all to toggle it on so she can review both versions of the content. 

This [Eligibility for VA health care page](https://www.va.gov/health-care/eligibility/) is an example of the alert placement and information alert style - between the H1 and page intro and the first H2.

### **Static page alert (users who CAN'T use the online form)** 

[header] Veterans enrolled in VA health care and expansion of benefits 
 
On [bold] **March 5, 2024** [bold], we expanded health care to millions more Veterans.

Learn more about the PACT Act and VA health care and benefits [link - https://www.va.gov/resources/the-pact-act-and-your-va-benefits/] 
 
Veterans who are enrolled in VA health care can now provide more information about their military service history.

We’ll use this information to determine if you may have had exposure to any toxins or other hazards. And we’ll also determine if we’ll place you in a higher priority group. This may affect how much (if anything) you’ll have to pay towards the cost of your care.

### **Static page alert (users who CAN use the online form)**

[header] Veterans enrolled in VA health care and expansion of benefits 

On [bold] **March 5, 2024** [bold], we expanded health care to millions more Veterans.

Learn more about the PACT Act and VA health care and benefits [link- https://www.va.gov/resources/the-pact-act-and-your-va-benefits/]

Veterans who are enrolled in VA health care can now answer more questions about their military service history.We’ll use this information to determine if you may have had exposure to any toxins or other hazards. And we’ll determine if we’ll place you in a higher priority group. This may affect how much (if anything) you’ll have to pay towards the cost of your care.

These questions are only available on our PDF form at this time. If you want to answer these questions, you’ll need to submit your form by mail or in person.

**Comment by aliyahblackmore** [comment]
And here's a screen capture just to reference the alert style (i.e. info alert/header etc.), if needed<img width="581" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3l0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dbf26aa6de2186fee1d98e45890aa882a965b19/Screen%20Shot%202024-03-04%20at%206.08.17%20PM.png" alt="Screen Shot 2024-03-04 at 6.08.17 PM.png" />

**Comment by lihanli** [comment]
widget will automatically be turned on for all ezr users

**Comment by mkerns1** [comment]
This has been merged and deployed to Prod.

**Comment by alexseelig** [comment]
This ticket has been closed. Outstanding issues has been migrated to [77720](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/77720)
