### ISSUE TITLE
Improve form introduction context (H)

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#77724]
## Why do this?
The intro page can be improved to better inform Veterans
- Users may mistakenly think that the 527-EZ Pension Form is for military retirement pension, A&A pension or survivor pension.
- Eligibility criteria and instructions are on different pages and could be missed
- There is updated guidance on intro pages, refer to this [**conversation**](https://dsva.slack.com/archives/C05MS96P6P2/p1709137738252799) which refers to a draft document on standardizing introduction pages https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/content-patterns-and-standards/form-intro-pages.md

**Research:**
- Participants who indicated that they were eligible for military retirement pensions (P1, P5, P7, P10, P13,  P15) were not aware that the 527-EZ Veteran Pension Benefits form was only for Veterans who were below a certain income level.  Participants were provided a link to an introduction on the Veterans Pension Benefit application and neither the introduction nor the first page of the application included eligibility criteria for pension benefit. 
- VBA subject matter experts confirmed that too frequently Veterans confuse VA pension with military retirement pension.
- All participants chose to sign in rather than start the application without signing in. Some participants noted that they did not want to lose the information they entered and others mentioned that they thought some information would be auto-populated if they signed in. 

## Solution ideas/thoughts
- Refer to latest [**527 PDF**](https://www.vba.va.gov/pubs/forms/VBA-21P-527EZ-ARE.pdf) - what's most important to surface from evidence tables, checklist, calculations etc?
- Help users understand what kind of pension 527 is NOT. Refer [**military pension**](https://www.usa.gov/military-pensions)
- Any context that could be picked up from [**Pension Annual Report 2023**](https://www.benefits.va.gov/REPORTS/abr/docs/2023-pension-fiduciary.pdf) - there are other pension forms, can we help users find the right form?  NOTE: Annual report provides simpler language as to what the 527 pension is: "Veterans Non-Service-Connected Pension and Survivors Pension Pension is a needs-based benefit designed to provide certain wartime Veterans and their survivors with a minimum level of income that raises their standard of living. Wartime Veterans who are age 65 or older or have a permanent and total nonservice-connected disability, and who have limited income and net worth may be eligible. Veterans who are more seriously disabled may qualify for pension at the increased housebound or aid and attendance (A&A) rates. Surviving spouses and dependent children of deceased wartime Veterans are eligible for monthly pension benefits if they meet the net worth and income requirements. "
- An interactive quiz like [**526 form**](https://www.va.gov/disability/file-disability-claim-form-21-526ez/introduction?next=loginModal) so the applicant is aware of high-level eligibility criteria and can only proceed provide they don't violate any of them (and don't waste their time doing the wrong things!)
- Pg1 on [**686c PDF**](https://www.vba.va.gov/pubs/forms/VBA-21-686c-ARE.pdf) form provides tables to help easily understand criteria and what's needed
- Inspiration from an [**outdated pension flyer**](https://www.benefits.va.gov/BENEFITS/benefits-summary/SummaryofVAPensionBenefits.pdf)
- Include an [**FAQ**](https://www.va.gov/resources/how-are-pension-benefits-and-disability-compensation-different/#:~:text=Your%20level%20of%20disability%20(your,benefit%20is%20the%20greater%20amount.)) - since there's a lot of info, what secondary info can go here?
- There is also information about how to determine if you are financially eligible that we may consider providing a link to  https://www.va.gov/pension/veterans-pension-rates/

## To do (suggestions)
1. Propose updates to form landing page and intro content. Streamline info that appears before and after login to improve clarity on who can use the pension web form, when, how and what's needed etc. How do they understand their eligibility, know what's needed and not waste their time?
2. Suggest any higher level pension content updates at www.va.gov/pension/ which we don't control
3. Define clearer content and interactions to avoid confusion and support users to do what's needed

## AC
Intro content:
1.  Is simple, concise, precise, complete and not overwhelming
2. That enables a Veteran to understand that they are the right place, know if they are broadly eligible
3. That provides and idea of what's required for this application
2. Meets VA platform content guidelines

In addition:
- Stakeholders have signed off
- Follow on tickets have been created
- Recommendations outside our scope have been shared (CAIA?)
- Product guide has been updated

**Comment by Allexelaw** [comment]
May want to consider providing a brief explanation of eligibility such as:  Pension is a needs-based benefit designed to provide certain wartime Veterans and their survivors with a minimum level of income that raises their standard of living. Wartime Veterans who are age 65 or older or have a permanent and total nonservice-connected disability, and who have limited income and net worth may be eligible. Veterans who are more seriously disabled may qualify for pension at the increased housebound or aid and attendance (A&A) rates. Surviving spouses and dependent children of deceased wartime Veterans are eligible for monthly pension benefits if they meet the net worth and income requirements.   Additionally, how might we provide additional information (e.g. accordion drop down) with more detailed  information about the criteria: • 90 days of service during a period of war; OR  • 90 days of consecutive service at least one day of which was during a period of war; OR  • 90 days of combined service during more than one period war:                                                                                                (None:  If your service began after September 7, 1980, additional length of service requirements may apply, typically requiring two years of continuous service or completion of active-duty obligation), OR • any length of active service during a period of war with a discharge due to a service-connected disability  • Suffering from a disability that is reasonably certain to continue throughout your lifetime that would make it impossible for an average person to follow a substantially gainful occupation; OR To support a claim for Veterans pension, the evidence must show: 1.  You met certain minimum active service requirements during a period of war.  Generally, those requirements are: 2.  You are age 65 or older or are permanently and totally disabled.  Your disability or disabilities do not have to be related to your       military service.  You are considered permanently and totally disabled if medical evidence shows you are: • A patient in a nursing home for long-term care or medical foster home; OR  • Receiving Social Security disability benefits; OR  • Unemployable due to a disability reasonably certain to continue throughout your lifetime; OR                                                  • Suffering from a disease or disorder that VA determines causes persons who have that disease or disorder to be permanently and totally disabled 3.  Your income and assets are within established limits.  You must report income and assets for: • Yourself  • Your spouse (unless you live apart and you are estranged, and you do not contribute to your spouse's support)  • Your child (unless custody has been legally removed by a court and you do not contribute to your child's support or the child's income is not reasonably available to you).                                                                                                    Assets means the fair market value of all property that an individual owns, including all real and personal property (excluding the value of the primary residence including the residential lot area, not to exceed 2 acres unless the additional acreage is not marketable) less the amount or other encumbrances specific to the mortgaged or encumbered property.  Personal property means the value of personal effects that are in excess of being suitable and consistent with a reasonable mode of life.

**Comment by mtri** [comment]
CAIA intake ticket for content has been created [here.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/83740)

Design WIP:
[Introduction page - Desktop](https://www.figma.com/proto/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?page-id=4138%3A26061&node-id=4412-7714&viewport=437%2C683%2C0.25&t=aYzokIwsvaEjienF-1&scaling=min-zoom)
[Introduction page - Mobile](https://www.figma.com/proto/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?page-id=4138%3A26061&node-id=4418-10303&viewport=437%2C683%2C0.25&t=aYzokIwsvaEjienF-1&scaling=min-zoom)

After meeting with the team last Friday, I wanted to capture these notes:
- Further testing may reveal additional opportunities for content under the Gather your information step.
- The new introduction page links the eligibility page. Testing how the introduction page interacts with the eligibility page in the pension hub may reveal additional opportunities.

**Comment by mtri** [comment]
After meeting with CAIA office hours last week:
• A [content document in Sharepoint](https://dvagov.sharepoint.com/:w:/s/SitewideCAIA/EcoTka8xFXVAnvg419JkrcMB7ig-Vcmq1UJeKuj9hTyRhQ?e=HYONL5) has been started for a resources and support page disambiguating VA pension and military pension.
• Some initial feedback and discussion has been provided on the design in Figma [here](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc?node-id=4571-8417#821339346) and [here](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc?node-id=4571-8417#821347275)

Full discussion and kickoff to come next Wednesday along with the other design tickets.

[CAIA has been engaged on this ticket.](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/gh/department-of-veterans-affairs/va.gov-team/83740)

**Comment by mtri** [comment]
[Designs with CAIA content are ready.](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5352-82095&t=b6yAPRgWdqCmIk9u-11)

**Notes**
• Specific supplementary form mentions have been moved into the form experience itself and are only shown to Veterans when relevant 1. when the action triggers the request for supporting evidence/form in the respective section 2. the supporting documents page context.

[Additional notes here on supporting documents page here.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/79210#issuecomment-2166901041)

**Comment by mtri** [comment]
Midpoint feedback to be implemented (applies to whole batch of usability improvements):

[Midpoint Review - Accessibility Feedback - Pension-Benefits, Pension, Usability Improvements #86503](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86503)
[Midpoint Review - IA Feedback - Pension-Benefits, Pension, Usability Improvements #86499](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86499)
[Midpoint Review - Design Feedback - Pension-Benefits, Pension, Usability Improvements #86451](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86451)

**Comment by mtri** [comment]
[Figma for Engineering](https://www.figma.com/design/9JKK5Eo43uJWEr66JPiebc/Pension-Claim-Form-21P-527EZ?node-id=5352-82095&t=V5dUy3B0nNzkKbAT-11)

**Comment by aplatt-coforma** [comment]
Created eng ticket #88387
