### ISSUE TITLE
[Development] Claim Status: Determine Whether Claims Status Usage Can Be Correlated to Call Center Calls

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#7776]
## User Story or Problem Statement
Problem description. How might we determine if the Claim Status tool is not providing the information the veteran is asking for or is having design/accessibility issues that result in Call Center calls.

Kelson Adams did some initial work for this, possibly.  I will reach out and see if I can add more details here.

## Goal
Veterans getting what they need and not needing to call the Call Center for help.

## Objectives or Key Results this is meant to further
- Veterans are able to easily obtain their claims status

## Acceptance Criteria
- [ ] We can correlate usage of Claims Status to Call Center tickets
- [ ] If we can do the above, provide findings (Call Center tickets) to design team to add to their research

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
@kfrz did some work to correlate the claim status log data to the user's edipi, prompted by a request from Charles Worthington.  Our logs have id.me uuid, and our Account table has both deipi and id.me uuid, so he was able to correlate the two id's.  Presumably, the list of edipi's was enough to correlate with call center data.

**Comment by luke-gcio** [comment]
Nice.  Does that mean we can get a spreadsheet with 2-3 weeks or so worth of data to begin looking for correlations (based on time)?

**Comment by annaswims** [comment]
The I'm checking with @kfrz but I think it means we can get the data (one way or another).  The big question is how to keep the PII safe.   previous discussion happened in   #temp-claim-status-lookup-investigation

**Comment by kfrz** [comment]
We should loop in @clantosswett on this -> I'm confident we *can* correlate the data points to generate a report as mentioned but would need to do some more discovery to understand the specific workflows envisioned. 

Is the data going to the call center on a regular basis? Which individuals should be able to generate or request a report, for what period(s) of time? How exactly would this ensure Vets can get their claims status? 

What appears to be the problem from my understanding is an uncertain level of trust in the Claims Status lookup tool data, resulting in frustrated Veterans calling in for help. Thus, a report of claims lookups by time and ID.me account could provide useful insights for debugging. Is this an accurate understanding?

Happy to get on a call to talk more about any of this if I can be helpful.

**Comment by annaswims** [comment]
From a DM from Charles In Febuary

`I have a question that I could use your brain on. Maybe you've already heard of this issue, but i'm not sure it made it to anyone technical on the team.
Andrea, Chante and I are trying to do an analysis of VA Claims Status lookup tool on call center. Specifically, we want to figure out how often veterans who use the claims status tool on VA.gov wind up calling the call center with a question within X period of time (i.e. within the same day, etc.)
The call center maintains record of every veteran that calls, so they can do a lookup if we can provide them some identifier of veteran. EDIPI would be preferred, but also could use CorpID or maybe we could do something even more creative.
I know VA.gov doesn't keep PII in our server logs, but I don't know what we DO log. Is there anything we log that we could work backwards to correlate with an EDIPI? LMK if you think there's someone else I could ask... I've been working through the benefits apps teams but they dont' have any engineers that I know so I'm not sure the question has made it to someone who could really know/think through options

also potentially relevant is Google Analytics picks up some IDs in the claim status views i.e. /disability-benefits/track-claims/your-claims/55776248/document-request/108680345/

I also think it's probable/possible that EVSS server logs might have this info since I believe that's the backend tool that supports us. i think andrea has asked that team`

**Comment by annaswims** [comment]
@luke-gcio the conversation in[ #temp-claim-status-lookup-investigation](https://dsva.slack.com/archives/CTFV03BSP/p1583413081003800) makes it sound like VSP provided the 30 days worth of EDIPI's for veterans who accessed the claim status tool on March 5.  Do they want and update or is that recent enough.  

 [cloudwatch logs](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-vagov-prod/srv/vets-api/src/log/vets-api-server.log;stream=c5bfd58ade58c25fdc28bbf574bf3320d2483fd211afa23c95dbaa20e21fd87a;filter=%22v0/evss_claims_async%22;start=PT30S) 

For future reference[the steps were (from what I can piece together on Slack:(https://dsva.slack.com/archives/CJYRZK2HH/p1581517292444600?thread_ts=1581517292.444600) 
1. get raw logs to machine with `awslogs --filter-pattern '{ $.payload.path="*evss*" }' > out.log`
1. process raw logs with `sed 's/^.*|\(.*$\)/\1/' -i out.log`
1. extract values with `cat out.log | jq -r '[.payload.user_uuid, .payload.status|tostring] | join(", ")'  >> claims_log.csv`
then I have the values and I have de-duped based on the user_uuid
1. something that can ingest a .csv of user_uuid strings and then run something like this on the production db: `Account.where(idme_uuid: [ingested_values]).in_batches.each_record { |x| csv[0], csv[1] = x.try(:edipi), x.try(:idme_uuid) }`

**Comment by annaswims** [comment]
@AZSchneider said that we're waiting to hear back from the call center about the first batch of data we sent and don't need any more data at this time. Pausing this writeup for now.
