### ISSUE TITLE
[Congressional] INC31796335 Veteran's Account potentially compromised

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#77807]
## Issue Description
Veteran is concerned account has been compromised because certain pieces of information were changed. 
https://dvagov.sharepoint.com/sites/OCTOInformationSecurity/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=vDGjo2&cid=9e439f23%2D7076%2D4a92%2D82fe%2D229d9d4babe2&RootFolder=%2Fsites%2FOCTOInformationSecurity%2FShared%20Documents%2FGeneral%2FSecurity%20Incidents%2FINC31796335%20Veteran%27s%20Account%20potentially%20compromised&FolderCTID=0x01200094CE077BA4E2E84A95DBC13DBFD6C6DE
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Gained access to link today from Ray Wang.  Reviewed issue, sent message to Victoria C. due to issue coming in a different way.
Reached out to Jason (Veterans son) to learn if the email address he is questioning is still linked to his father's account and what email addresses SHOULD be linked to the account.

I also provided contact information for the department he needs to engage since our team does not manage fraud activity.

**Comment by Kimberley2023-CSM** [comment]
From Kimberley to Vicki C.

This Congressional has been on our board for a little while now.  I wanted to check in with you to see if you need to add it to your list, because it seems to have taken a different route getting to us.  I was just granted access by Ray Wang in order to review the issue, but you shouldn’t have any problems accessing the link.

 

I’m still going to reach out to the user and if they are still in need of assistance, I’m going to pass it along to Adam Kinder for his team to take a look.

 

After you review, let me know if you need anything else.

**Comment by Kimberley2023-CSM** [comment]
This issue was previously resolved.  No follow up needed.
