### ISSUE TITLE
Build survivors landing page for FMB hub

### ISSUE THREAD

**Issue by strelichl** [department-of-veterans-affairs/va.gov-team#77991]
## Issue description

Mikki has stubbed out new pages required for the family member hub and will add links to this ticket:
*Note: the formatting and elements used in these are not necessarily final, they were simply a way to experiment with the content that we needed to represent.  

- Survivors page:  http://preview-prod.vfs.va.gov/preview?nodeId=65341

Per Mikki: The required pages to be linked to from each landing page is documented in the [family member hub mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1684260449054/7d2a6588b6861b0fb19a31d73cad49fe1a5abd3d?wid=0-1704984305251) - on the far right under "Final working structure"

---
## Tasks
- [x] Compare links on the stub page in Drupal to the updated [IA design](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/family-hub-phase-1.md) and update Drupal to match IA design as needed (Derek)
- [x] Adjust all sections to use the "List of link teasers" style with linked H3 headers followed by blurbs (Derek)
- [x] Draft intro for the page and blurbs for each link on the page (Derek)
- [x] Review draft landing page (Laura)
- [x] Decide on H1 (Derek, Laura, Kristin)
- [x] Copyedit and prepub checklist (Sara)
- [x] Send to SMEs (Danielle)
- [x] Publish **(coordinated effort)**

## Acceptance Criteria
- [x] The landing page is live on VA.gov

**Comment by d-beyer** [comment]
@laurwill -- I've finished drafting this page. It's ready for your review.

**Comment by laurwill** [comment]
@kristinoletmuskat 2 Qs on this one:
- [Pension Management Centers](https://www.va.gov/pension/pension-management-centers/) is a page we've been trying and failing to archive for years. It makes you scan to find the address of your pension management center, but all the pension management centers share an address. The "how to apply" pages for pension, DIC, etc, just list that address and don't link to this page. I think we should cut it (and eventually remove it from the left nav in main hubs and then archive it entirely, once we get agreement from SMEs.)
- Why is the [Tragedy Assistance Program for Survivors](https://www.taps.org/) linked here, but not in burials or life insurance?

**Comment by kristinoletmuskat** [comment]
@laurwill

1. Pension management centers -- that sounds good to me! I'll remove it from the Mural and the Phase 1 IA spec. 
2. Tragedy Assistance Program -- I think you're right that it probably belongs in both of those pages as well. We can add to the 'More' section of the subhubs for both of those as well, ya?

**Comment by laurwill** [comment]
Thanks @kristinoletmuskat ! 

The Tragedy Assistance Program (TAPS) link is also a .org — I thought we were trying not to link off of VA.gov from the landing pages (that's why we had to create the TRICARE page in health subhub). Do we want to link to this .org in phase 1?

TAPS is also not linked on any existing hub pages. The only VA.gov page I could find that links to it is this [Resources for military and Veteran family members page](https://www.va.gov/careers-employment/family-resources/), and that leads me to another question!

I don't see that page in the IA spec for the Education and training subhub. But I do see a ticket to create an R&S version of that page in phase 3 for the Education and training launch. Are we not planning to link to the Resources for military and Veteran family members at all in phase 1?

cc @aprocik1 for phase 3 connection

**Comment by kristinoletmuskat** [comment]
Hey hey @laurwill and @aprocik1 

1. I think we do want to link to TAPS -- in discussion yesterday with Mikki we confirmed that we do want to link to non-VA benefits from these subhub pages but not like migrate them into the hub. I double-checked with Mikki over slack and will let you know if she disagrees.
2. We might have mmissed that [resources page in careers](https://www.va.gov/careers-employment/family-resources/) -- I asked Mikki in slack and will let you know what she says (whether we should link to it in phase 1)

**Comment by laurwill** [comment]
Lots o' updates: 
- H1 for launch is **Survivor compensation** (singular survivor, no accrued benefits)
- Accrued benefits content only exists in [PDF form](https://www.benefits.va.gov/BENEFITS/factsheets/general/Accrued.pdf). Rather than linking to a PDF, we'll create a webpage for this content and add it to the landing page after phase 1 launch. 
- Removed .org TAPS link for now, may add later

**Comment by laurwill** [comment]
Hi @saratorres2 , the survivor compensation subhub landing page is ready for your copyedit. Let me know if you have questions!

**Comment by saratorres2** [comment]
@laurwill Copy edits complete! One open query about use of phrase "Veteran with wartime service" captured in [backlog ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85640#issuecomment-2161101966).

**Comment by d-beyer** [comment]
@saratorres2 I've added the related links and they're ready for copyedit. Screenshot attached.
![Survivor-FMB-related-link-20240614](https://github.com/department-of-veterans-affairs/va.gov-team/assets/141662117/8e3e8165-8dd8-4567-83e1-2aea944725ea)

**Comment by saratorres2** [comment]
@laurwill Copy edit complete for new related links section.

**Comment by kristinoletmuskat** [comment]
Confirmed live in prod, closing out.
