### ISSUE TITLE
Appointments React App Does Not Handle Unknown URLs

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#78040]
## Description
Currently, an HTTP 404 error code is generated by the VA web server if a veteran tries to access an unknown or bad URL on the VA site for a static content page (e.g. https://www.va.gov/dummy). The web server is set up to respond to HTTP 404 error codes by showing a "page not found" page to the user as shown below. This works well for static content served by the web server.
However, dynamic content that gets rendered on the client side (like from a React app) cannot generate HTTP codes for missing pages for the web server to respond to. All React apps that the VA site uses render on the client side. Each React app has a specified root URL in its manifest.json file (e.g./health-care/schedule-view-va-appointments/) that links to the app regardless of any sub-path provided in the URL (e.g. /health-care/schedule-view-va-appointments//path/path/path leads to the same React app). The apps use React Router conditional code to render content based on the child path(s) of the root URL (e.g. /path/path/path). An empty or incomplete page can result if the app’s routing logic does not explicitly handle the provided path(s). A sample of this behavior can be found below.

<img width="819" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkROQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f2b29bfca3e7fad3976f989611e34da0c478a19/image.png" alt="image.png" />

This results in the VA site rendering empty or incomplete pages with no further information or action for the user. 

## Recommendation
React apps have various routing patterns that restrict our ability to implement a catch-all solution at the React Router level. These various patterns also mean that the routing for some apps may need to be refactored in order to properly handle unknown URLs. Our recommendation is as follows:

1. Create a shared page-not-found component to be used by all React apps. This component should replicate the existing static content 404 page for a consistent user experience. 
2. Update each app to have a default React route that shows this new page-not-found component. This may need to be done for child paths as well. This implementation will retain the unknown URL in the browser’s address bar allowing the user to inspect/fix the URL. This will also duplicate the existing behavior of the static content 404 page. For example, we can add the following default route to an app to serve the page-not-found component for unknown URLs.

<Route>
  <PageNotFound />
</Route>

1. Add documentation requiring a default route for all React apps and to use the shared page-not-found component. It should be noted that the page-not-found page should contain any other app content (some apps generate content like breadcrumbs before the routing logic). It also needs to be noted to generate the page-not-found page for any child routing that is not supported. 
2. Open tickets to get the different React apps updated to have default routes. This could be done by one team updating all the apps or individual tickets for each app. A lot of the apps can be quickly and easily updated since they have simple routing, so perhaps one person can update a lot of them at the same time.

[Slack Canvas](https://dsva.slack.com/docs/T03FECE8V/F06G3J52NJE) outlining issue and ask

---

## Acceptance Criteria

Given an authenticated user
When navigating to an unknown or bad URL starting with va.gov/my-health/appointments/
Then page-not-found component is displayed

### Design Assets
All spec copy is FPO. Use copy in copy doc.

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by JRRoof** [comment]
The component can be found here:
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/user-nav/components/PageNotFound.jsx

You can import it using:
import PageNotFound from '@department-of-veterans-affairs/platform-site-wide/PageNotFound';

**Comment by JunTaoLuo** [comment]
Here's a few implementation notes and a question.

1. At the [top level router](https://github.com/department-of-veterans-affairs/vets-website/blob/04fb7788c72512483a4cb384ba9efd5e7b415574/src/applications/vaos/routes.jsx#L41-L73) we have three paths: New Appointment, Covid Appointment and Appointment Lists.
2. New Appointment and Covid Appointments both have [redirect logic](https://github.com/department-of-veterans-affairs/vets-website/blob/04fb7788c72512483a4cb384ba9efd5e7b415574/src/applications/vaos/new-appointment/index.jsx#L60-L69) that ensures all direct navigations to subroutes are redirected to `/` which is handled by Appointment Lists. [^1]
3. Given that New Appointment and Covid Appointment flows are designed to be navigated with "Next", "Back" and "Edit" buttons (which only appears on the confirmation page) and any direct navigation to unknown paths are redirected to `/`, I think the design is safe enough and we don't need to add 404 pages. The only risk here is if our "Next", "Back" and "Edit" buttons are mis-coded to lead to a non-existent page. At that point, it's not an user error and displaying a 404 page wouldn't be appropriate anyway.
4. We will add a 404 page to Appointment Lists for handling unknown paths. This is implemented in the [this PR](https://github.com/department-of-veterans-affairs/vets-website/pull/32381).

There is one remaining question which is the subtle distinction between navigating to `my-health/appointments/bad/path` vs `my-health/appointments/bad_id` specifically noting one fewer slash in the latter. This is because a `bad_id` is treated as an appointment ID which will route to the appointment details page and display the "We're sorry. We've run into a problem." error page when the backend fails to retrieve the appointment. Ideally we should have an VAOS specific "Appointment not found" page with a message like: "We're sorry. We can't find your appointment". However, I feel that this should probably involve the design team and best separated out to a separate ticket rather than this one. What do you think @JRRoof @outerpress?

[^1]: Technically, we do allow direct navigation to bad URLs that ends with 'confirmation' e.g. `http://localhost:3001/my-health/appointments/schedule/covid-vaccine/bad/confirmation`. However, I think this is such a bizarre corner case that I don't think it's worth refactoring our routing logic. But do let me know if anyone thinks otherwise.

**Comment by outerpress** [comment]
@JunTaoLuo providing a specific message when a user encounters a bad appt ID makes sense to me. Aside from the user trying to hack the URL, are there other situations where we might get an incorrect/missing appt ID?

**Comment by JunTaoLuo** [comment]
@outerpress I think entering an incorrect ID is the only way to get a 404 error. In case the BE service is down, we'll get a 500 error which will display the current error page, which also makes sense.

**Comment by JRRoof** [comment]
I agree with bullets 1, 2, and 3 above.  We should not direct to a 404 page from a bad URL within the scheduling workflow.

I agree that a unique error message should be created for a malformed appointment ID.

@outerpress - Can you create a UX ticket for the error message of the malformed appointment ID?

Everything else looks good, so I'm closing out this ticket.

**Comment by outerpress** [comment]
@JRRoof UX ticket: #96076
