### ISSUE TITLE
[Drupal] Add support for homepage banner

### ISSUE THREAD

**Issue by ncksllvn** [department-of-veterans-affairs/va.gov-team#7817]
The [homepage banner](https://github.com/department-of-veterans-affairs/vagov-content/tree/master/fragments/home) still lives in vagov-content instead of Drupal. We need to move it into Drupal so that it's consistent with where the rest of our content lives, and so that we can ultimately remove vagov-content.

## Technical problem
The dilemma seems to be that the homepage itself not as a Drupal node/page, but rather a collection of menus. This means that the homepage cannot be targeted for a banner to be published, making the homepage a special case for a banner.

## Acceptance criteria
- [ ] Homepage banner can be written in Drupal
- [ ] FE template added or edited
- [ ] Deprecated code removed

**Comment by ncksllvn** [comment]
CC: @beeyayjay

**Comment by kevwalsh** [comment]
There's probably some questions about whether this should be a new content type, or leverage the existing alert block content model. Since the alert block content type was created in Feb 2019 (which as stated can only be placed on Drupal-known URLs–at the time only the benefits hubs pages), a new banner alert type was added for VAMC systems. It might be worth looking at that content type for a variety of reasons: 
1. Governance
2. Editorial experience
3. Content model (eg the CTAs)
4. Content style guidelines (like character counts)  
5. The way the front end build places it on all pages that start with /pittsburgh-health-care (including, theoretically, URLs that are not known to Drupal).

**Comment by FranECross** [comment]
Added to the 3/18/2024 Product Sync with Dave/Jill.

**Comment by jilladams** [comment]
This has been resolved. Full Width Banners can now be used on the homepage, from within Drupal.
