### ISSUE TITLE
Identity Slackbot Is Here! Comms

### ISSUE THREAD

**Issue by jimcconnelly** [department-of-veterans-affairs/va.gov-team#78263]
*User Story*
As an Identity Team Member, I would like to make it known to other teams that the Identity Slackbot exists in the VSP-Identity Slack channel, so that they may be able to use it for requests

*Acceptance Criteria*
The following things are communicated:
* Identity Slackbot exists.
* It can be used for the following kinds of requests
   * Data Pulls
   * Mocked Auth login issues
   * PR Review
   * Sign-in Service integration

**Comment by kdmeg-bluetiger** [comment]
Met with @LisaLindsey to discuss comms plan and [chatted about next steps](https://dsva.slack.com/archives/C06FD8276DD/p1710358721732089?thread_ts=1710358576.202759&cid=C06FD8276DD) with @joeniquette 

**Comms plan will include**
- Updated Slack description in #vsp-identity (approved by OCTO POs and submitted to Slack admins for update)
- A written announcement shared in #vsp-identity (and potentially more channels pending the branding workshop discussion) with details about the new Identity support processes supported via Slackbot
- I looked into "welcome" messages for when new individuals join the channel and it appears these are standardized throughout VA to be pretty minimal so that will not be in scope at this time.
