### ISSUE TITLE
Publish expanded TOE for dependents

### ISSUE THREAD

**Issue by aprocik1** [department-of-veterans-affairs/va.gov-team#78531]
## Description
We need to migrate the content from these legacy pages:
- [Isakson and Roe Veterans Health Care and Benefits Improvement Act of 2020](https://www.benefits.va.gov/GIBILL/docs/IsaksonRoe/IsaksonRoeFactSheet.pdf) (PDF)
- [Isakson and Roe Veterans Health Care and Benefits Improvement Act of 2020](https://www.benefits.va.gov/gibill/isaksonroe.asp)
- [Isakson and Roe Act Summaries](https://www.benefits.va.gov/gibill/isaksonroe/summaries.asp)

We only need to migrate this remaining content to the modern site:
> Section 1011. Expansion of Transfer of Entitlement for Dependents under the Post-9/11 GI Bill: Eligibility now includes certain unmarried children placed in the legal custody of the Service member for at least 12 months as a result of a court order.

We need to migrate the remaining content to these modern pages:
- [Transfer your Post-9/11 GI Bill benefits](https://www.va.gov/education/transfer-post-9-11-gi-bill-benefits/)
- [Transferred education benefits for family members](https://www.va.gov/education/survivor-dependent-benefits/transferred-benefits/)

### Step 1: Place
- [x] DB: Provide recommendation on where to place content on both modern pages
- [x] AP: Review recommendation

### Step 2: Draft
- [x] DB: Draft content in Drupal
- [x] AP: Review content in Drupal
- [x] AP: Share Drupal preview with BP
- [x] BP: Review content in Drupal
- [x] DB: Update content with BP feedback
- [x] DB: Share Drupal preview with stakeholders
- [x] DB: Update content in Drupal with stakeholder feedback
- [x] MZ / ST: Copyedit and publish

## Criteria
- [x] Legacy content has been published on the modern site

**Comment by d-beyer** [comment]
@aprocik1 I drafted changes to both pages: it's one sentence under the section about the eligibility of children. I think it should go on both since it's basically the same copy in both places.

The phrasing is a bit funny and I'm not totally satisfied with my solution. I think the original copy on the modern pages implies _dependent_ children in a lot of places without actually saying that, whereas children put in a service members custody _weren't_ dependents before. Maybe the important thing is that children put in a service members custody for 12 months by court order are considered dependents for the purpose of this benefit.

Also, the marriage status thing is a bit funny. I'm trying to imagine a _married_ child being put in a service member's custody.

Interested in your thoughts!

Links:
- [Transfer your Post-9/11 GI Bill benefits](https://prod.cms.va.gov/node/952/latest)
- [Transferred education benefits for family members](https://prod.cms.va.gov/node/44698/latest)

**Comment by aprocik1** [comment]
Thanks, @d-beyer. I think you're right about adding it to both pages. And I think you're right about the definition of "dependent" children for the purposes of this benefit. We could ask SMEs about this too.

It seems odd to stack eligibility requirements like this, but here's another approach:

> **Your child is eligible for these benefits if one of these is true:**
> - They've turned 18, **or**
> - They've gotten a high school diploma, **or**
> - They've gotten a certificate that's equal to a high school diploma
> 
> **Your child is also eligible for these benefits if both of these are true:**
> - A court order puts them in your custody for at least 12 months, **and**
> - They aren't married
> 
> You're child must use these benefits before they turn 26 years old.

For the transferred education benefits pages, it also seems odd to say, "if a court order puts you in the custody of the service member." Maybe it's something like, "if you're put in the custody of the service member for at least 12 months by a court order."

I don't feel solid about either of these edits, but I wanted to respond before I'm OOO starting at 1 pm ET today. We can brainstorm on this together on Monday if you'd like!

**Comment by aprocik1** [comment]
@d-beyer, here's another option:

> **Your child is eligible for these benefits if one of these is true:**
> - They’ve gotten a high school diploma (or a certificate that’s equivalent) or turned 18 years old, **or**
> - They're put in your custody by a court order for at least 12 months and they're not married
> 
> You're child must use these benefits before they turn 26 years old.

**Note:** Both of these suggestions, I'm assuming that the 26 year cutoff isn't actually an eligibility requirement.

**Comment by d-beyer** [comment]
I'm not sure that means the same thing. I think it's more like: "Your child can get these benefits if they're your dependent **or** placed in your custody for 12 months by court order. They must also meet these requirements... (high school diploma, over 18, under 26)"

<details>
<summary>So maybe the best place to put this piece of information is right under the H3, like this:</summary>

### Children
Your child can get these benefits if they're your dependent or a court order puts them in your custody for at least 12 months.

Your child can start to use these benefits only after you’ve finished at least 10 years of service. They can use these benefits while you’re on active duty or after you’ve separated from service.

**Your child must meet these requirements:**
- They can’t use the benefit until they’ve gotten a high school diploma (or a certificate that’s equivalent) or turned 18 years old, **and**
- They must use these benefits before they turn 26 years old

**Note:** Your child may qualify for the monthly housing allowance even when you’re on active duty.

---

</details>

Obviously I need to revise/potentially reformat that first sentence, but does that make sense? We can talk about this at our check-in today and potentially bring it up at tomorrow's meaning.

**Comment by d-beyer** [comment]
@aprocik1 I tried another revision as discussed in our sync. Let me know if you think we can share with Beth.
- [Transfer your Post-9/11 GI Bill benefits](https://prod.cms.va.gov/node/952/latest)
- [Transferred education benefits for family members](https://prod.cms.va.gov/node/44698/latest)

**Comment by aprocik1** [comment]
Thanks for making these updates, @d-beyer. Feel free to share them with Beth. It'd be ideal to get clarity on these requirements today with Tammy, although I know that's quick turnaround for Beth's review.

**Comment by d-beyer** [comment]
Update from 05.01 meeting with SMEs:
- SMEs were able to clarify that the next eligibility requirements include dependent children that aren't *your* children. This is what we needed to move forward.
- Ideally, we won't have to re-check this page with SMEs because we were so specific about the change we wanted to make in our discussion.

**Comment by d-beyer** [comment]
@megzehn Hi @megzehn -- We revised Q&As on two modern pages in order to migrate a single legacy page. They are ready for copyedit and publishing. You may want to do this in conjunction with #77509 since that is another minor text change to the same pages.

- [Transfer your Post-9/11 GI Bill benefits](http://preview-prod.vfs.va.gov/preview?nodeId=952) (Q&A: When can my dependents use the transferred benefits?)
- [Transferred education benefits for family members](http://preview-prod.vfs.va.gov/preview?nodeId=44698) (Q&A: When can I use transferred benefits?)

**Comment by megzehn** [comment]
Confirming that I reviewed and published these changes. Thanks, @d-beyer!
