### ISSUE TITLE
Update vets-website to use new CSS-Library color sass variables.

### ISSUE THREAD

**Issue by it-harrison** [department-of-veterans-affairs/va.gov-team#78822]
## Description

Recently in [2294](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2294) the tokens used to generate sass color variables were updated to incorporate uswds [semantic tokens](https://design.va.gov/foundation/color-palette#semantic-color-tokens) instead of the color primitives previously in use. Ticket [2311](https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/vets-design-system-documentation/2311) was created before this effort and focused on updating certain sass variables in `vets-website` to account for updates made to formation to make colors consistent with uswds. 2311 is no longer relevant because it was opened before 2294; however, in the light of 2294 `vets-website` needs to be updated to use the new sass color variables generated in css-library.

## Tasks
* import sass color variables from `css-library` into `vets-website`
* replace all sass color variables in `vets-website` with their new `css-library` counterparts

**Comment by it-harrison** [comment]
PRs:
* [28690](https://github.com/department-of-veterans-affairs/vets-website/pull/28690)

**Comment by it-harrison** [comment]
@danbrady the formation color variable that is used in `vets-website` that does not have a matching color in uswds is [color-focus](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/9f28d6c22e9324f8f0787f3e33189344d6b7b0aa/packages/formation/sass/base/_b-variables.scss#L114).

**Comment by danbrady** [comment]
Thanks, @it-harrison. 

@humancompanion-usds Ian is updating Formation colors to use USWDS values. There is one variable in Formation, `$color-focus` that doesn't have a USWDS value. I'm catching up on this, this is what I see: 

* `$color-focus` hex value is currently `#3e94cf` which is not a USWDS color. I'm guessing this is pretty old because it is a blue focus color, before we switched to the yellow ring.
* `$color-focus` looks only to be used in one place in Formation which is a [secondary button that's within an accordion](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fveteran-facing-services-tools%20%24color-focus&type=code) which component uses this color for a subtle box shadow when in focused state. (The default 2px gold focus ring also applies to this.)
* However, it looks like this variable is used in a [few places in vets-website](https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fvets-website%20%24color-focus&type=code)

I can think of two ways to move forward on this:
* Find the closest color to `#3e94cf` that we use already and use that token. (No current colors are close this blue surprisingly, but we can find something that works.) 
* Change `$color-focus` to use the same focus color as the rest of the components which is `$color-gold-light` (`#face00`).  

Thoughts?

**Comment by it-harrison** [comment]
Followup ticket: https://app.zenhub.com/workspaces/platform-design-system-5f8de67192551b0012ebb802/issues/gh/department-of-veterans-affairs/va.gov-team/79489

**Comment by danbrady** [comment]
Hey @it-harrison - I discussed this with Matt. He said let's update `$color-focus` to our focus color: `$color-gold-light` (`#face00`).
