### ISSUE TITLE
Set up Google analytics

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#78837]
## Description
In order to respond to travel pay users' feedback, we need to set up Google Analytics to keep track of interactions

## Prerequisites:
- [x] We have the something to analyze (top-level page views, link clicks, etc)

## Acceptance Criteria
- [x] I can visit the travel pay claims status page in staging, interact with it, and see results in google analytics
- [x] I can navigate to a custom report/dashboard in Google analytics

## Demo
- Demoable? Yes
- How? Show the GA page
- Impact? Shows product maturity 

## Definition of Done
- [x] All acceptance criteria are met
- [x] Documentation is updated

**Comment by ayush-chak** [comment]
An example of what a GA dashboard could look like: https://analytics.google.com/analytics/web/?authuser=1#/dashboard/2UeDqFDEQr-Dwv1peR4hnA/a50123418w177519031p176188361/

**Comment by ayush-chak** [comment]
Final page - closing since everything looks good. Thank you, Kevin!

https://analytics.google.com/analytics/web/#/p419143770/reports/explorer?params=_u..nav%3Dmaui%26_r.explorerCard..filterTerm%3D%252Fmy-health%252Ftravel-claim-status%26_r.explorerCard..startRow%3D0&ruid=D4F7103F-DEA1-4A09-B066-EE554BF6F5F0&collectionId=8429185582&r=all-pages-and-screens
