### ISSUE TITLE
Implement updated flows

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#78848]
[Per figma tracked here](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/74023)

10-7959c form should include all data capture represented in the above Figma as a baseline, including conditional pages/inputs.

Acceptance criteria
- [ ] Updated form exists in code and matches inputs/conditional flows found in above Figma

**Comment by michaelclement** [comment]
PRs planned:
- [ ] Intro page content
- [ ] Signer info
    - [ ] First pass at flow
    - [ ] Checkboxes for relationship to applicants
- [ ] Applicant info
    - [ ] First pass at flow
    - [ ] Shared address functionality
    - [ ] File uploads
- [ ] Medicare info
    - [ ] First pass at flow
    - [ ] File Uploads
- [ ] Health insurance
    - [ ] First pass at primary info flow
    - [ ] Shared coverage functionality
    - [ ] File uploads
    - [ ] First pass at secondary insurance info flow
    - [ ] Shared coverage
    - [ ] File uploads
- [ ] Certify & submit section
- [ ] Files overview section

**Comment by michaelclement** [comment]
@baltes As an update: this ticket will almost definitely have to be carried over to the next sprint. 

The medicare section of the form is done and I'm working on healthcare now. Medicare had to be broken into multiple PRs due to the scope of the changes (and healthcare section will likely be the same). Waiting on approvals, but there's almost no way everything will be up on staging this week.

**Comment by baltes** [comment]
@michaelclement Understood and no worries, thanks for the update.

**Comment by michaelclement** [comment]
All this work is done, but it's sitting in PRs that have yet to merge. I'll update here when they're in and can be viewed on staging. Thanks! @baltes
