### ISSUE TITLE
Priority #1: Make sure live Caregiver pages have accurate and up-to-date information

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7891]
## Background 
[Public Websites update request from Caregivers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7326)

## High Level User Story/ies
As a Veteran and/or Caregiver, I need accurate Caregiver program information so I understand program details better.

## Hypothesis or Bet
**If** we update existing Caregiver content on VA.gov **then** we expect less confusion from Caregivers, Veterans, and others.

## Acceptance Criteria
- [x] Kickoff meeting (2020-04-08)
  - Align on process, schedule, and information
- [x] Check-in (2020-04-08-2020-04-13)
  - VA.gov content team will reach out to caregiver team with specific questions on wording as needed to ensure a collaborative writing process and alignment on key phrases
- [x] VA.gov content team edits Drupal page(s) and sends preview to caregiver team for accuracy review (2020-04-13)
  - Team will send a PDF 
screenshot of the edited Drupal page, with changes highlighted
- [x] Meeting to review content (if needed based on review) (2020-04-15)
  - Goal of meeting is to answer any questions and align on final content. If we need more rounds of revision, we can accommodate that as needed.
- [ ] VA.gov content team publishes edited Drupal page(s) (2020-04-17)
  - Once content is final, the page will go through our internal quality assurance (QA) process and go live in afternoon daily deployment

**Comment by AnneHurley** [comment]
[Updated copy for Caregiver program page -word doc]
(https://app.zenhub.com/files/133843125/27c51d63-626f-44ac-9548-6fa3e2033e03/download)
@daniellethierryusdsva @RLHecht  FYSA

**Comment by RLHecht** [comment]
Copyedits on page complete. PDF sent to Danielle to send to stakeholders.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @MickinSahni. Quick update on this issue. We've received stakeholder feedback (though more may come today/tomorrow from one stakeholder who is OOO). I'm meeting with stakeholders tomorrow at 3:00 p.m. to go over any questions, so I don't think we'll be able to push changes live tomorrow. But hopefully Monday or Tuesday latest. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
Good morning @AnneHurley @RLHecht. Met with caregiver program team on Friday and finalized copy in meeting. 

Could you please update the program page and related pages to match the attached today, and send me a preview link and pdf?


**1) Main program page:** Please update per attached. I highlighted areas that changed, but please also check against the full, clean doc. [PCAFC clean copy for Drupal 4.20.20](https://app.zenhub.com/files/133843125/f5207313-f801-437d-ac3f-deb020d9b6be/download)

**2) Related pages:** Please update per attached.

[updated caregiver descriptions for landing pages 4.20.20](https://app.zenhub.com/files/133843125/5c5fb63f-f5cc-4d96-b20d-b5ad1cac3427/download)

**Comment by stephorkandatx** [comment]
Thanks for sharing the finalized copy @DanielleThierryUSDSVA .
@AnneHurley or @RLHecht any questions or concerns with updating the pages & generating previews? Would we be able to knock that out today?

**Comment by AnneHurley** [comment]
@stephorkandatx @DanielleThierryUSDSVA @RLHecht  I will make the content updates to the main page today, then the related pages. @DanielleThierryUSDSVA Will send you a preview link when it's updated so you can share w stakeholders.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @AnneHurley. I'm meeting with Mikki at 12 noon to confirm questions re: related pages for her, so will update here after that.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @AnneHurley, was able to sync with @mnorthuis. Can we please make these additional 2 updates on the family member benefit hub (https://www.va.gov/family-member-benefits/)? Thank you!

1.  Update this subhead to:

**More benefits and services for those caring for a Veteran or service member**

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/94387b14-51e9-4ace-b788-41db16e93a81)

2. Update this link label and description to:

**[More VA Caregiver Support Program resources](https://www.caregiver.va.gov/)**
Caregivers of Veterans who aren’t eligible for the Program of Comprehensive Assistance for Family Caregivers may still be able to get support and resources through our Program of General Caregiver Support Services. Learn how to access training, educational resources, tools, and advice to help support you in caring for a Veteran.

![image.png](https://images.zenhubusercontent.com/5e8b13016a4378a604f5e799/54d49e99-7e3d-45b6-90ca-3d66114479ba)

**Comment by AnneHurley** [comment]
@RLHecht  This page is ready for your edit: prod.cms.va.gov/node/10/edit
@DanielleThierryUSDSVA - the two links in your word doc about "visit our website" I have linked to 2 caregiver.va.gov links - correct?

And @DanielleThierryUSDSVA - thanks for the above info, will make those fixes next.

**Comment by DanielleThierryUSDSVA** [comment]
@AnneHurley I think you mean the below links, yes?

- [Caregiver Support Program website] - yes, goes to caregiver.va.gov
- [Read about the Program of General Caregiver Support Services] - goes to https://www.caregiver.va.gov/Care_Caregivers.asp (direct link to that program page)

Thank you for double checking. I'm not sure why the hyperlinks didn't show up in the doc for those!

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA - ^Yes thanks

**Comment by RLHecht** [comment]
@AnneHurley I reviewed the page and made a few copy tweaks.

**Comment by AnneHurley** [comment]
[Caregiver page updates - April 20]
(https://app.zenhub.com/files/133843125/364b044d-eb1d-4ca1-8eab-e90609b6c762/download)
@DanielleThierryUSDSVA  Here are the updates/edits for the main page.

**Comment by AnneHurley** [comment]
[Health care for spouses etc - April 20](https://app.zenhub.com/files/133843125/4d55880d-4ef3-40b8-815b-cfeb7c8e3d72/download)

**Comment by DanielleThierryUSDSVA** [comment]
Hi @AnneHurley. I think something got mixed up on the family and caregiver health benefits page.

The provided description was to replace the Program of Comprehensive Assistance for Family Caregivers description on that page. But it looks like it's replaced the page intro. Could you please revert to the existing intro and use the provided copy to replace the program description? Thanks!

**Comment by AnneHurley** [comment]
[Family And Caregiver Health Benefits _ Veterans Affairs-April 20 -v2.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4506431/Family.And.Caregiver.Health.Benefits._.Veterans.Affairs-April.20.-v2.pdf)
@DanielleThierryUSDSVA  FYSA and @RLHecht Ready for your copyedit

**Comment by AnneHurley** [comment]
[VA benefits resources page incl caregiver info](https://app.zenhub.com/files/133843125/87e24381-7082-4b42-8f2d-a6a7dcdee5ca/download)
@RLHecht  Ready for copy edit
@DanielleThierryUSDSVA  FYSA 

preview-prod.vfs.va.gov/preview?nodeId=810

Now all three va.gov pages with caregiver related info should be updated.

**Comment by RLHecht** [comment]
These last two pages have both been reviewed. @DanielleThierryUSDSVA I slacked you the PDFs and the preview links.

**Comment by DanielleThierryUSDSVA** [comment]
Thank you both. And @RLHecht, thank you x100 for all your Drupal help. I so appreciate it, and I'm hoping to have Drupal access this week so I hopefully won't have to bug you for all the things :)

@stephorkandatx  for tracking purposes, I've sent the updated previews/pdfs to the stakeholders. Hoping for their final okay either tomorrow or Wednesday, and will post here with the go-ahead to publish updated pages as soon as I have that.

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA  and @RLHecht  - Were there Drupal issues?

**Comment by DanielleThierryUSDSVA** [comment]
@AnneHurley Mainly the one I slacked you about w/ the missing words in the copy.

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA and @RLHecht Here are the links that Pam requested updates for. The main thing they’d noticed was the links not working in preview so we should be good once pages are published.

1.	Main PCAFC page: preview-prod.vfs.va.gov/preview?nodeId=10  
Request: To swap the order of the phone number and the caregiver directory link. Done.
2.	The family member landing page within the Health Benefits section of VA.gov: preview-prod.vfs.va.gov/preview?nodeId=32 
Request: To remove comma in the serial list “health care, insurance,” to make it simply “health care insurance.” Done – however it looks strange to say “health care insurance” when everywhere else we seem to use health insurance. However, I did make this change, fyi.
3.	VA benefits for spouses, dependents, survivors, and family caregivers landing page on VA.gov: preview-prod.vfs.va.gov/preview?nodeId=810
Request to add a definition of the program in the 2nd resource blurb under caregivers. This was the full request: 
The Program of General Caregiver Support Services (PGCSS) provides resources, education and support to caregivers of eligible Veterans from all eras. The Veteran does not need to have a service-connected condition, for which the caregiver is needed, and may have served during any era. No formal application is required.

I shortened it but I hope kept to the spirit of the request. Otherwise, this blurb would have been one of the longest on the page. We needed to keep in the language that this is a second program, if you don’t qualify for the one above. Also we are using second person in these blurbs so I wanted to work in that as an action the reader could take.  The suggested text says “any era” twice, and also has some phrases that seemed either a little awkward or too much info (we don’t say, for example, what kind of application is required in the other blurbs). 

So I changed that blurb to:

More VA Caregiver Support Program resources
Caregivers of Veterans who aren’t eligible for the Program of
Comprehensive Assistance for Family Caregivers may still be able to
get support through our Program of General Caregiver Support
Services. Learn about the resources available to caregivers of eligible
Veterans from all eras. For this program, the Veteran doesn't need to
have a service-connected condition.

Questions:
1.	Is the above still took long?
2.	Are the changes I made so significant the stakeholders will be unhappy? 

I made a PDF of this page even though all three pages need copyedit, Danielle, so you can take a look at this last one in context. Let me know if you want edits/additions/etc.

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @AnneHurley! 


1. For this page, they also had a request for a change of a link. I've highlighted that in the attached and left a comment.
[caregiver program - additional edit for link.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4513065/caregiver.program.-.additional.edit.for.link.pdf)

2. Agree, "health care insurance" doesn't seem right. Let's change to "health insurance" and we can just let them know about that. I don't think they'll care, as long as we're not implying that the person gets some other kind of insurance as well.

3. Agree with you 100% about length, voice, etc. Since they now want that link to go straight to the PGCSS program page, though, what do you think about just making that the title and using their description with some tweaks for our style? I think if we're going to link directly to that program page, we should make the link label match the page title.

**[Program of General Caregiver Support Services](https://www.caregiver.va.gov/Care_Caregivers.asp)**
Find out how to get resources, education, and support available to caregivers of eligible Veterans from all eras. For this program, the Veteran doesn't need to have a service-connected condition, for which the caregiver is needed, and may have served during any era. We don't require a formal application for this program.

And then for the main page,

**Comment by AnneHurley** [comment]
@DanielleThierryUSDSVA Yes that's a good solution - I'll make these updates to all pages first thing in the morning.

**Comment by DanielleThierryUSDSVA** [comment]
Hi @AnneHurley. I'd like to get the preview links back to the caregiver team asap since we'd need their feedback by 1 p.m. in order to publish for today's deploy. When the pages are ready, would you be able to reply all to that group and send the preview links and details about each of the updates and our rationale for how we addressed them and ask for approval by 1 p.m.? Thank you!

**Comment by AnneHurley** [comment]
4/22/20 - Sent final edits in email to stakeholders:
Hello all – 
 
We’ve made your latest edits on these Caregiver-related pages. If you can send me your feedback by no later than 1 p.m. Eastern today, we can get these fixes live with today’s deploy:
 
1.	Main PCAFC page: preview-prod.vfs.va.gov/preview?nodeId=10  
Request: To swap the order of the phone number and the caregiver directory link, and to make the second instance of the caregiver directory link to, and use the same text as, the mention higher on the page. 
Status: Done.

2.	The family member landing page within the Health Benefits section of VA.gov: preview-prod.vfs.va.gov/preview?nodeId=32 
Request: To remove comma in the serial list “health care, insurance,” to make it simply “health care insurance.” 
Status: Done, but with one edit to make it consistent with other mentions on the site and the page. It now says “health insurance” not “health care insurance.”

3.	VA benefits for spouses, dependents, survivors, and family caregivers landing page on VA.gov: preview-prod.vfs.va.gov/preview?nodeId=810
Request: To revise headline and text in blurb on main Family resources page. 
 
Status: Done
The blurb now reads per below, and the headline links to the program page:
Program of General Caregiver Support Services
Find out how to get resources, education, and support available to caregivers of eligible Veterans from all eras. For this program, the Veteran doesn't need to have a service-connected condition, for which the caregiver is needed, and may have served during any era. We don't require a formal application for this program.
@DanielleThierryUSDSVA  @stephorkandatx  @jenniferlee-dsva  @RLHecht

**Comment by RLHecht** [comment]
These changes have been copyedited. There was an extra line space in the alert copy on node 10, which is now fixed.

**Comment by DanielleThierryUSDSVA** [comment]
@stephorkandatx quick update:  Pam (one of the key stakeholders) has signed off, and is just waiting for sign off from the full team. We'll either do a content-only deploy today or publish in tomorrow's daily deploy. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
@AnneHurley @RLHecht @stephorkandatx Just capturing officially in ticket that we're good to publish!

**Comment by RLHecht** [comment]
These pages have been published. Moving to validate and will close after tomorrow's deployment when live on the site. FYSA @stephorkandatx

**Comment by RLHecht** [comment]
Changes are on live site. Closing ticket. FYSA @DanielleThierryUSDSVA @AnneHurley @stephorkandatx
