### ISSUE TITLE
Priority #2: Update program page to support launch of new online 10-10CG form - Create Content, Send to stakeholders

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#7892]
## Background 
[Public Websites update request from Caregivers](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7326)

The goal in this meeting is to align on the process and end deliverable date. The VA.gov content team will then work with our product manager to solidify timeline dates for each deliverable, and will send an update by next week at the latest. The VA.gov content team will also share links to our GitHub tickets to keep the caregiver team fully in the loop on progress.

## Acceptance Criteria
- [x] Kickoff meeting (4.8.20)
  - Align on process, schedule, and information
- [x] Content and design briefing (5.6.20)
  - VA.gov content team will review all references, including the 10-10CG form and additional documentation provided by the form team. Team will come to the meeting prepared with any open questions for clarification.
- [x] Content/design review (5.14.20 - 5.21.20)
  - VA.gov content team will provide the caregiver team with preview of changes for accuracy review. The caregiver team will have 5 business days to review, with a meeting scheduled as needed to answer questions and align on content

Update: ticket updated to focus on the content creation, and being provided to the caregiver team for review. Rounds of revisions, final design preview and signoff to take place in the follow-up ticket at 9376

**Comment by DanielleThierryUSDSVA** [comment]
**Next steps:**

Stakeholders have requested that we reach out at the end of this month (April) to schedule a meeting for the week of May 4. Danielle to reach out then.

**Comment by DanielleThierryUSDSVA** [comment]
## Recommendations for 5.5.20 content strategy/IA meeting

[Go to content for mockup](https://docs.google.com/document/d/1kQSUo5cuzsZ144F0V4BfThTglaf3qtfa7WVGujZzbi8/edit?usp=sharing)

Danielle and Mikki to represent team and present a mockup of the following recommendations:

**Family member benefits hub page**
- Update family member benefits hub page to better highlight caregiver-specific programs

**Overall navigation**
- Move the PCAFC page from the health care hub to the family member benefits hub (rationale: program does include health care benefits, but it also includes non-health care benefits such as a monthly stipend and other services)
- Include the PCAFC application also in the family member benefits hub (accessible via the PCAFC main page and not directly via the hub page or left nav due to the IA of this section)

**PCAFC page**
- Update the PCAFC page to accommodate the online application, and frame mail and in person application methods as "other ways to apply"
- Consider 2 different potential treatments to raise "how to apply" information up on page a bit for greater visibility
- Redirect that current PCAFC page from caregiver.va.gov to point to the VA.gov page (rationale: this will help to address the issue of duplicative and potentially inconsistent information)
- Make any necessary parity updates to the VA.gov PCAFC page in order to make the redirect possible (specifically, include the information about appealing a decision)

**PGCSS information**
- Keep PGCSS information on the careigver.va.gov site at this time, and continue linking over to this page from the family member benefit hub page and PCAFC page (rationale: this program is more of a resource than a benefit, following the current VA.gov definition of a benefit, and diving more into the caregiver.va.gov content isn't within the scope of this effort at this time)

**Comment by DanielleThierryUSDSVA** [comment]
@peggygannon We'll need to sync on when/if we need a formal platform review for the content. Thanks!

**Comment by DanielleThierryUSDSVA** [comment]
# Notes from 5.6.20 meeting to discuss next steps for caregiver program content on VA.gov

**Together, the VA.gov and caregiver program teams reviewed page mockups and agreed that we will:**

- Provide a URL for the online 10-10CG application.
- Update the VA.gov family member benefits hub page to better highlight caregiver-specific support and services within a caregiver-specific section. We’ll link to the VA.gov PCAFC page from this hub page as well as the caregiver.va.gov PGCSS page.
- Move the PCAFC page out from within the health care section and into to the family member benefits hub, where it will live alongside the new online 10-10CG application.
- Get the PCAFC page ready to accommodate a button and related copy to direct users to the online application. We’ll go with the approach that incorporates this information and button into the current flow of information on the existing live page. We’ll have this page ready by May 29. However, we will not publish the updates to the page until everything is ready on the backend and we get the go-ahead from the caregiver team.
- Ensure that the button and related copy on the PCAFC, and the path to the online 10-10CG application, can be removed/shut down quickly if needed after launch.
- Continue to think about ways to ensure that caregiver.va.gov and VA.gov can work together to provide information about PCAFC to Veterans and caregivers that’s always up-to-date and consistent without being duplicative or confusing. We’ll continue thinking and talking about this together as the caregiver program expands and the team continues to update caregiver.va.gov.

**Timeline:**

- [ ] 5.5.20: Priority 2 kickoff and review of proposed updates and related questions 
- [ ] 5.13.20: VA.gov PW team to provide preview of updated PCAFC page in ready-to-support-application state to caregiver team
- [ ] 5.20.20: Caregiver team to provide any feedback
- [ ] 5.22.20: VA.gov PW team to provide final preview 
- [ ] 5.27.20: Caregiver SMEs to provide sign off and any final feedback

**Comment by DanielleThierryUSDSVA** [comment]
**Note:** Send attached mockup to caregiver team along with urls for main page and online application form. [https://app.zenhub.com/files/133843125/56c53607-9b4b-4620-ad4a-f5b4c797ec5c/download](https://app.zenhub.com/files/133843125/56c53607-9b4b-4620-ad4a-f5b4c797ec5c/download)

**Comment by stephorkandatx** [comment]
Split into this as content creation, and then create an implementation ticket.

**Comment by stephorkandatx** [comment]
As discussed, we have updated the ticket to focus on the initial creation, and sending the work to the caregiver team for review. feedback and iteration/implementation taking place in a separate story, split among sprints

**Comment by stephorkandatx** [comment]
@DanielleThierryUSDSVA as discussed in sprint planning, this has been split into two tickets and I am going to close this one out as completed. The new ticket will be assigned to you!
