### ISSUE TITLE
FE | Profile | Maintenance | Rework account security headings as links

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#79187]
## Background

Use the [figma mock](https://www.figma.com/file/05k2PTmuDVgBj2HnzUZayg/Profile---Account-Security?type=design&node-id=124-1858&mode=design&t=vowe90BXuJ1jl4Tj-0) up to incorporate the changes recommended by design in #74053. 

## Tasks 
- Custom code for list has been removed
- Use the web component for the list and update content to match figma design

## Acceptance Criteria 
- [x] we've incorporated the revised design into the account security page 
- [ ] the updates are in production

**Comment by adamwhitlock1** [comment]
@mtcA6 I have merged in work for this ticket and it is live in staging. I used test user 202 to view the list in its new form:

<img width="886" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUM1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dbe8f83af7b3efa767addda594d904c4e2a22d4e/Screenshot%202024-05-06%20at%2010.20.39%E2%80%AFAM.png" alt="Screenshot 2024-05-06 at 10.20.39 AM.png" />

I also used an LOA1 user (just used one of my email accounts) to view the list for that type of user:
<img width="718" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUc1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f86de5a2979816354d99803ce23b1fa48bd90d80/Screenshot%202024-05-06%20at%2010.21.44%E2%80%AFAM.png" alt="Screenshot 2024-05-06 at 10.21.44 AM.png" />

This should be good to close once you validate.

**Comment by adamwhitlock1** [comment]
Also FYI you will notice for LOA1 that the MFA link is a button, and that is because it is triggering some JS logic that needs to run prior to the user being redirected to the MFA next steps, so it needed to be a button. I mentioned this to Liz and she was cool with that being a button for now and will look at updating it's style further in the future if need be.

You can read our comments about it in my PR here: https://github.com/department-of-veterans-affairs/vets-website/pull/29580
