### ISSUE TITLE
Edits to staging of 10-7959f-1 | Visual Design and Interactive Acceptance Testing Results

### ISSUE THREAD

**Issue by brian-wilke** [department-of-veterans-affairs/va.gov-team#79546]
After reviewing the pages uploaded to the staging site beginning at:
https://staging.va.gov/health-care/foreign-medical-program/register-form-10-7959f-1/introduction

The following screens (along side the corresponding figma pages) were captured in order to illustrate the variances from the intended designs.

PLEASE NOTE: the scale of text is not referenced here, and not in the scope of this review.

PLEASE NOTE: though the same error may repeat from page to page (i.e. the number of steps within the form), it is only called out once for this review. 

These call-outs should be reviewed before this ticket is brought into a sprint for work. 

PLEASE NOTE: additional changes may be added to this ticket (or subsequent tickets) that reflect insights from User testing that is currently in progress. 

<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0280174cc8e670f569cb16d5a5ca1c0504e2661/Changes_10-7959f-1_Step1.png" alt="Changes_10-7959f-1_Step1.png" />

<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4057ce21cc61143d5221d236cafdbd837f98f1d6/Changes_10-7959f-1_Step3.png" alt="Changes_10-7959f-1_Step3.png" />

<img width="1001" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL29kQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5fc23e83b935b0967044e6385febf26a9acfff0/Changes_10-7959f-1_Step4.png" alt="Changes_10-7959f-1_Step4.png" />

<img width="992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41377f1f6cca2731c421f3f8b33e9aeb9c9c2ac1/Changes_10-7959f-1_Step6.png" alt="Changes_10-7959f-1_Step6.png" />

**Comment by marywang2** [comment]
My comments (in addition to what is above): 
- intro page: how do I check the copy for this screen?
- Veteran info screen: remove helper text (unnecessary)
- SSN screen: move helper text underneath "VA file number" text (and update text to read 'or' rather than 'of', 'file' should also be lower case)
- review screen: Figma has 'personal information' rather than 'name and date of birth'
- confirmation screen: how do I check this? (url is not working for me)

**Comment by brian-wilke** [comment]
The pattern of using middle initial is what we have seen (and was referenced by users) in other places. It is not a deal breaker, but it seems like that is the most up to date item (the design system has it that way).

The updates to the figma (in the prototype being used in testing...) reference the "Name and date of birth" so that is correct on staging.

**Comment by marywang2** [comment]
Do you have the link to the design system where it is this way (middle initial)? Only because I haven't seen it before (here is the [design system link](https://design.va.gov/patterns/ask-users-for/names) I am referencing).

Ah, I was looking at the figma design that has 'handoff', do we want to follow the [design system](https://design.va.gov/templates/forms/review) here or is it fine as is....

**Comment by brian-wilke** [comment]
Duplicating this ticket in order break into 2 tickets.
1 for pattern corrections - a
1 for visual/string/text adjustments - b

**Comment by marywang2** [comment]
Adding note here that we will need to make updates to the section headers (what the text should be and how to get them to show up) - we can combine this change with whatever comes out of the user interview analysis changes.

**Comment by brian-wilke** [comment]
@marywang2 closing this ticket as it was a "template" for other change tickets per UAT
