### ISSUE TITLE
[DISCOVERY][Fwdproxy] Health Check configurations

### ISSUE THREAD

**Issue by hgbarreto** [department-of-veterans-affairs/va.gov-team#79541]
## Description
Some health checks need to be revisited and possibly explicitly configured to log. Users are wanting to see the network / HTTP call that is happening, both for success and failed calls. We currently only have a metric.

## Resources 
- https://dsva.slack.com/archives/CBU0KDSB1/p1707347207813759
- https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-dev.yml

## Acceptance Criteria
- [x] Health Checks are being logged

## Refinement Guidance - Check the following before working on this issue: 
- [ ] _Team label assigned ("platform-tech-team-2")_
- [ ] _Epic assigned (if needed)_ 
- [ ] _Estimated (points assigned)_
- [ ] _Sprint assigned (once planned)_
- [ ] _Team member(s) assigned_
- [ ] _Understands how this work aligns with the overall platform_

**Comment by Efe-Oddball** [comment]
This ticket is no longer required as the new fwdproxy have been configured to log all healthcheck status code [here](https://github.com/department-of-veterans-affairs/vsp-platform-fwdproxy/blob/f2b2880ca13d46cc93b745b42d64fe336574e676/fwdproxy-config/files/haproxy.conf.j2#L96). Here is also a snippet from the fwdproxy container log showing that healthcheck status codes are being logged regardlesss of what they are. ![Image](https://github.com/user-attachments/assets/2e989ce1-a1f0-4d1c-b9db-e78bbe5ba4a9)
![Image](https://github.com/user-attachments/assets/c06db310-b038-4a3b-b1cc-ed52f3d16314)
![Image](https://github.com/user-attachments/assets/1e28e6c2-9e11-4e34-bfe4-d3c23dd57446)

Closing out this ticket because it is no longer needed.
