### ISSUE TITLE
VFS Custom Events for Public Websites & All Our Products

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-team#79590]
# VFS Custom Event Audit Form

## Description of Attachment
I've attached the spreadsheet that @randimays and @jestutt chatted about. The Public Websites Team has many products, so I created a worksheet for each product's information within the Google Sheets [workbook ](https://docs.google.com/spreadsheets/d/1iDtKAagOxMlkqoYHGWvrNsG9MtDZZxl39i_5BkP0hik/edit#gid=1385316268)that Randi produced. 

Please let me know if you prefer it presented differently, and I'll be happy to comply! Thanks in advance.

### What this form is for.
In prepration for the migration to GA4, we need information on _all_ custom events used by your products so we can continue to track them.

> [!IMPORTANT]
> Please complete this form with the related spreadsheet included as soon as possible, but no later than **Friday, April 5.** The final deadline where Universal Analytics will stop collecting data is **June 30, 2024**, so we are trying to ensure tracking coverage _well_ before that date.

Please reach out to the **#_vfs-analytics_** Slack channel if there are any questions.

---
_Our team will follow up with you for next steps._

 > [!NOTE]
> If your team manages more than one product, you can submit this form multiple times, or alternatively, include multiple copies of the spreadsheet to the same Github form. Whichever option is easiest.

**Comment by FranECross** [comment]
@jestutt Apologies for the delayed response! Thanks for this info. I'll take your suggestion and create a ticket to dispose of the nav-link-click. cc @randimays

**Comment by johnny-jesensky-adhoc** [comment]
The work from this ticket carried over from last sprint into our current one. This particular submission of custom events is one of our largest, and more complex batches, which has taken more time to implement than anticipated. While we gave it an 8, we likely should have broken this out further in hindsight.

We anticipate this work being completed early in the current sprint, in order to be finished before the Universal Analytics (UA) sunset date of **Monday, July 1.**

FYI @jestutt, @davidconlon, @jwoodman5
