### ISSUE TITLE
[Post-release] Remove composer.json from vets-website

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7975]
## Description
Once the CMS repo [no longer requires `vets-website` as a dependency](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7974), we can remove the `composer.json` file.

**Comment by billfienberg** [comment]
@cvalarida, should this ticket say `composer.json` instead of `composer.lock`? 

I found a [`composer.json` file in the repo](https://github.com/department-of-veterans-affairs/vets-website/blob/master/composer.json), but I couldn't find a `composer.lock` file in the `master` branch. 

Search result for `composer.lock`: https://github.com/department-of-veterans-affairs/vets-website/search?q=composer.lock&unscoped_q=composer.lock

I did find a [PR](https://github.com/department-of-veterans-affairs/vets-website/pull/10270) that included a [commit to add `composer.lock`](https://github.com/department-of-veterans-affairs/vets-website/pull/10270/commits/c23750158535b5b840aeafdce2f230a3691df6c2), and then a [subsequent commit to delete `composer.lock`](https://github.com/department-of-veterans-affairs/vets-website/pull/10270/commits/2384a1cbc9ed3ce095ef1c98be76fdf702ee36ee). Also, that PR is now closed, and looks like it was never merged.

**Comment by cvalarida** [comment]
Huh, coulda swore it was a lock file too....but yeah. You're right. :+1:

**Comment by timwright12** [comment]
Confirming with CMS team that this should be done.

**Comment by indytechcook** [comment]
The file can be removed after the CMS has migrated to using the new repo and the github hooks has been removed from the `vets-website` repo.
