### ISSUE TITLE
[Pre-release] Deploy applications to new application S3 bucket

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va.gov-team#7978]
## Description
To avoid the application build from overriding any content, we need to have it deploy to a separate bucket that exists exclusively for application builds. 
---
## Tasks
- [ ] Derive a new deploy script from the existing `vets-website` deploy script to deploy only the webpack build to the application bucket

## Acceptance Criteria
- [ ] Only files within `generated/` are deployed to the new application S3 bucket when running the application build

**Comment by theodur** [comment]
[PR](https://github.com/department-of-veterans-affairs/devops/pull/8593) for adding new s3 bucket in `devops` repo.
[PR](https://github.com/department-of-veterans-affairs/vets-website/pull/16219) for deploying `generated` directory to new application s3 bucket _(Waiting for approval on first PR before opening the second PR up for review)_.

These changes only affect the dev environment.

**Comment by theodur** [comment]
Apps are now being uploaded to the apps S3 bucket (apps.dev.va.gov). The [application-build](http://jenkins.vfs.va.gov/job/deploys/job/application-build-vagovdev/) deploys are also now being triggered. There is an [issue](http://jenkins.vfs.va.gov/blue/organizations/jenkins/deploys%2Fapplication-build-vagovdev/detail/application-build-vagovdev/2/pipeline/) with the `speedy-s3-deploy.sh` script not finding the `BUILD.txt` file in the apps bucket. This is because the `BUILD.txt` is only [created](https://github.com/department-of-veterans-affairs/vets-website/blob/master/jenkins/common.groovy#L305) in the `build` directory and not the `generated` directory which includes the assets.

I created a [PR](https://github.com/department-of-veterans-affairs/devops/pull/8657) for removing the check for `BUILD.txt` in the application deploy. This should resolve the error in the application-build deploys. Once resolved we should hopefully see the assets at http://apps.dev.va.gov.s3-website-us-gov-west-1.amazonaws.com

**Comment by theodur** [comment]
Apps are now being deployed in a separate bucket at http://apps.dev.va.gov.s3-website-us-gov-west-1.amazonaws.com. For now content is being deployed here as well to avoid issues with only deploying the generated directory.
