### ISSUE TITLE
[UX] 10-10EZR: Update Figma to reflect sign in widget changes

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#79800]
As a team member, I would like Figma to be updated so that I know our design system, which is our source of truth, can be referenced at any point to see how pages should look in Production. 

- [x] Work with FE (and any stakeholders) to make sure everyone understands the changes that need to be made
- [x] Update Figma to move Sign in widget from Intro page
- [x] Add sign in widget to Static Page if necessary (I don't think we have static page designs but wanted to call this out just in case)
- [x] Make any other changes that come up during this process
- [x] **Success: Figma is the source of truth for how the Intro Page should look without the sign in module.**

**Comment by katelyncai** [comment]
The sign-in widget is now removed from intro page designs on Figma.

I'm going to close this for now, but I will open a placeholder ticket for updating the Static page's widget content. That content is still pending per an [update from Aliyah](https://dsva.slack.com/archives/C05QKRZGHFS/p1714073101233029). We do have static page designs represented on Figma, since we like Figma to be a source-of-truth for anything our designs can impact. Plan to make those changes when we get notice from content.
