### ISSUE TITLE
[Congressional] V11403718 Due Rep. Hoyer  4/19/24 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#79833]
## Issue Description
Veteran's has no access to his accounts due to ex-wife illegally accessing veteran's accounts.

https://app.slack.com/client/T03FECE8V?selected_team_id=T1ZD0UBMZ 
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
I reached out to Adam Kinder and fraud team on 4/8/24 for asssitance with this fraud case.

**Received from Adam Kinder on 4/8/24:** Benefits Delivery Protection & Remediation (BDP&R) reviewed the Veteran’s VA record on December 15, 2023, based on a VA Hotline inquiry. BDP&R conducted an in-depth review of the Veteran’s VA benefits record and potential fraud incident involving attempted diversion of the Veteran’s VA disability benefits was not evident. Mr. X reported that his ex-spouse has authorized his eBenefits and VA.gov accounts without his permission. BDP&R reviewed available IP logs and unauthorized access could not be confirmed without additional information since the Veteran and his ex-spouse live in close geographical proximity and IP access could not be delineated between the individuals. Local law enforcement or VA OIG could subpoena the internet provider to identify IP access ownership. BDP&R confirmed that there was no attempt to divert Mr. X VA disability benefits.
A BDP&R representative spoke with the Veteran on December 18, 2023, to share the findings of the investigation. The Veteran reported that the Maryland State Department was working on the issue. The BDP&R representative provided the Veteran identity theft resources to include how to contact the three credit bureaus and place an alert on the Veteran’s credit file, how to order a credit report, how to file an identity theft report, and explained the steps that VA takes in instances of potential fraud incidents. More specifically, the Veteran was provided contact information on how to secure his online accounts to prevent unauthorized access.
As of April 8, 2024, the Veteran’s VA disability benefits continue to be delivered to his requested account since September 16, 2022. If Mr. X is still experiencing issues with securing his online accounts, that would need to be addressed with the individual credential service provider (DMDC, ID.Me, Login.gov, and MyHealtheVet).

**Comment by Kimberley2023-CSM** [comment]
4/16/24 Update: Veteran responded on 4/8/24 and requested a phone call as follow up.
Today I responded informing the Veteran I will reach out to ID.me and Login.gov to see if there are any extra security steps that can be taken to help secure his account.  I will follow up with a phone call to him.

**Comment by Kimberley2023-CSM** [comment]
Hi, good news. OIT is giving us an extension to next week to give us more time in hoping veteran responds. :slightly_smiling_face: I'm waiting for the new date. Will let you know shortly.

**Comment by Kimberley2023-CSM** [comment]
Update:
**On 4/16/24 received guidance from Login.gov -**
I have confirmed with our technical team that this user does not have a Login.gov account using the email address provided in your protected message. Nor has anyone with that email address submitted a case through phone or web using that email address. In regard to the authentication options provided by Login.gov, there are several options that are available, from most secure to least secure. These options are spelled out in our Login.gov Help Center article. Just a note that we also recommend that users add two authentication methods to their account to keep from having to recover their account (delete and recreate).
**On 4/16/24 received guidance from ID.me -**
What we can tell is account under email XXXXXXX@proton.me was created today but there was no verification attempted. This means only the logging in (email) and MFA was set up. It looks like this may have happened in the past with the account under XXXXXXXXX@icloud.com (this account no longer exists). Since there was no verification under this most recent account that means there is no PII, just that they logged in, confirmed the email and set up MFA (MyHealtheVet was used)
There are a few options here but my first question/recommendation would be
Is XXXXXX@proton.me the Veterans email?
If so they should go in and change their password and MFA that they currently have set up. This will ensure the ex no longer has access to this.
If the Ex tries to verify it will not let them because it not their identity. We can either purge the account or suspend the account.
If we suspend the account this locks out anyone from accessing (even the Veteran)
If we purge the account (delete) the Veteran would have to go in and begin to set up a new account with their email. 
**On 4/18/24 -** Called Veteran and left voicemail regarding email I was about to send and to follow up via phone call or email.  Email included guidance from both CSPs from above and question asking if he has reached out to MHV or DS Logon for account suspension or deletion.

**Comment by Kimberley2023-CSM** [comment]
New date for completion is 4/29 from OIT as of 4/19/24.

**Comment by Kimberley2023-CSM** [comment]
Update: 4/24/24:  Still no call back or response to email from user.  Sent a follow up email to confirm if the information provided by ID.me and Login.gov matches the notes he may have. Awaiting a response from Veteran.

ID.me and Login.gov are both unable to place passwords or PIN on his account, however, both CSPs have provided instructions for the most secure experience he can have.  Unsure what else VA will be able to assist with.

**Comment by Kimberley2023-CSM** [comment]
4/16 Veteran responded advising they had screen shots of errors. Kimberly responded asking to email. Waiting on a response.
4/18: Veteran has not sent over screen shots. Kimberly followed up with via. email and phone call.
4/24: No response from Veteran. Kimberly followed again via. email. Waiting on a response.

**Comment by Kimberley2023-CSM** [comment]
Good Morning, Hope you had a nice weekend. This is due today. If we do not hear from Veteran by COB we'll close case.

**Comment by Kimberley2023-CSM** [comment]
4/30/24 Complete: Case has been closed. OCTO will continue to monitor case and hope to make a connection with Veteran.
