### ISSUE TITLE
[Congressional] V11604658 Due 5/22/24 Rep D'Esposito

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#79949]
## Issue Description
The Veteran's sister is his power of attorney and is requesting access to his online information. The veteran is blind, and his license expired and is unable to obtain another one.

https://app.slack.com/client/T03FECE8V/C02BS78NYRM?selected_team_id=T1ZD0UBMZ
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Sent an email on 4/16/24 inquiring:

- Is this still an issue?

- Is there a way to obtain a state ID card, not a driver license since he is blind?

- If she has provided ALL POA documentation to all of the CSPs (ID.me, DS Logon, Login.gov, and MHV)

- Provided contact information for all 

No reply as of 4/18/24 so I sent a follow up email.

**Comment by Kimberley2023-CSM** [comment]
4/19/24 Update:  Sister emailed back advising they are out of town until the end of next week and will call once they are back.

**Comment by Kimberley2023-CSM** [comment]
4/19/24: Sent email to POCs at ID.me, Login.gov and MHV for assistance with this matter and to verify if the previous information provided is correct.

**Comment by Kimberley2023-CSM** [comment]
From our Login.gov partner:
Login.gov supports:

Current driver’s license (valid, unexpired)
State-issued ID (valid, unexpired)
 

At this time, Login.gov does not support:

an expired state-ID or extension document
passport/passport card
military ID
Veteran's card/VIC
Green card/Permanent resident card
student ID
PIV
CAC
local or state government card
anything else
 

So, the veteran would need to have an unexpired, valid state-issued identification card (it need not be a driver's license). We also have this information available in a Login.gov Help Center article: https://login.gov/help/verify-your-identity/accepted-identification-documents/

 

We would redirect any questions about power of attorney to VA. Since Login.gov is CSP that provides secure sign-on, and has no access to the veteran's information, it would be up to VA to allow the person with the power of attorney to link a Login.gov account to the veteran's information.

**Comment by Kimberley2023-CSM** [comment]
**Update 4/26/24:** Called user and spoke to Veteran's sister.  I explained to her that the identification has to be valid in order for our CSPs to accept it.  She asked if the VA could use her ID instead since she is POA, I informed her I would take this to leadership and provide her with an update.
Emailed user recap of phone conversation.

**Comment by Kimberley2023-CSM** [comment]
Sent another email reminder to Tom Black for guidance/assistance.

**Comment by Kimberley2023-CSM** [comment]
Sent an email to MHV Coordinator, Michele Rodriguez, at North port VA in NY for assistance.  Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
Sent follow up email, inquiring if the POA has reached out to the MHV Coordinator.  Awaiting response.
