### ISSUE TITLE
Spike: flippers to show/hide text, questions, pages

### ISSUE THREAD

**Issue by buddhima-coforma** [department-of-veterans-affairs/va.gov-team#79963]
As part of the Collaboration Cycle process, certain FE changes will need to undergo a review. As these review cycles take time, they suggested releasing these updates behind a feature flag so that they are hidden in production until sign-offs are provided.

Flipper behavior:
>- Flippers can be used to show/hide content/fields/pages
>- There will be multiple flippers tied to different features/tickets, and they can be used independent of each other
>- A flipper can hide content/fields --> show it once approved
>- A flipper can hide updated content/fields and show old content/fields in place --> show new content/field once approved

Staging and production behavior:
> - We need to review items in staging without having to turn it on in prod env too (ie: a feature shows in staging while remaining hidden in prod)
> - When an update is not approved, keep it hidden in prod and continue with other flippers and release cycles

**To do**
With reference to above context:
1. Are there any negative impacts to account for in the form flow, schema, PDF etc when above flippers are activate/inactive?
2. What needs to be done to avoid any issues? What situations do we need to be mindful of/avoid? (ie: dependencies between flippers etc?
3. Document findings and recommended practices
4. Create any follow on tickets if there's some setup or experimenting we need to do before we begin to use flippers for this purpose

**AC**
- You know how to use feature flags aka flippers without causing issues for users in production for use cases (above) in production
- Necessary exploration has been done and documentation and follow on tickets created

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/79963?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by TaiWilkin** [comment]
*Introduction*

Feature flags are required to manage continuous deployment workflows, and will allow Pensions to control the release of features and changes across different environments. This guide outlines the process for utilizing feature flags to group changes for review on staging before production release. We'll focus on implementing and managing feature flags within the vets-website application.

In our workflow, we'll be grouping features by sprint to facilitate easier review and management. This means that features developed within a sprint will be bundled together under a single feature flag for testing and review purposes.

*Alternative Approach*

If, instead of creating per-sprint flags, we decide to create flags for each change or feature, the process would be almost the same. Instead of creating the flag at the beginning of the sprint, we would create it before beginning work on the feature; and instead of removing it at the end of the sprint, we would remove it once the feature has been approved. 

*Prerequisites*

Before proceeding, ensure you have access to the Flipper UI endpoints for vets-API, following the guidance here.

*Creating Grouped Feature Flags at the Beginning of the Sprint*

1. *Feature Toggle Name*:  Name the feature toggle pensions_sprintX, where sprintX represents the current sprint number.

2. *Update vets-API Configuration*: Add the feature name to config/features.yml under the features section in vets-api. Specify the actor type and provide a brief description of the feature.

3. *Run vets-API Locally*: After your pull request (PR) is merged, navigate to http://localhost:3000/flipper/features to verify the addition of your new feature toggle.

4. *Update vets-website Configuration*: Add the feature toggle name to featureFlagNames.js following the provided format.

5. *Submit PR*: Create a vets-website pull request for the feature toggle addition, cross-linking the PRs in a comment for easier review.

6. *Flip the Toggle on Staging*: In Staging (staging-api.va.gov/flipper/features) update the sprint feature toggle to enable the sprint features for all users.

*Implementing Grouped Feature Flags During the Sprint*

1. Utilize the Toggler component within your React components and the useFeatureToggleHook hook in functional components to access toggle values.

2.  If a feature is large and work will continue over multiple sprints, consider assigning it an individual feature toggle to dissociate it from the general sprint work. Otherwise, it must be updated to be wrapped in the toggle for the new sprint.

3. Begin any vets-json-schema changes (see Managing vets-json-schema Changes, step 1).

*Cleaning Up Feature Toggles After the Sprint*

1. Allow stakeholders to review the changes on Staging. 

2. Once approved for Production release, enable the sprint features on Production (api.va.gov/flipper/features).

3. Remove the Toggler components and the useFeatureToggleHook hooks wrapping the sprint features from the code. Remove the feature toggle name from featureFlagNames.js.

4. Once the vets-website PR removing the sprint feature flag has been merged, remove the feature name from config/features.yml under the features section in vets-api.

5. Once the vets-API PR has been deployed to Production, delete the feature from the respective databases by running Flipper.remove(:feature_name) in the Rails console for each environment.

6. Clean up any vets-json-schema changes (see Managing vets-json-schema Changes, step 2).

*Managing vets-json-schema Changes*

There is no method currently implemented which would allow us to include two separate versions of the schema in the application by using feature flags. This means that we will need to complete schema changes in multiple steps, in order to temporarily create a schema which will accept both the old and new structures of the data. 

1. During the sprint, if a feature requires a change to vets-json-schema, the schema must temporarily be adjusted to allow both versions of the form.

	1. If the change removes a field, the field must be left in the vets-json-schema but made optional.
	2. If the change adds a field, the field must be added to the vets-json-schema but made optional.
	3. If the change updates the format of a field, vets-json-schema must allow both the old and new format.

2. After the sprint, if the feature required a change to vets-json-schema, update the schema to only allow the new version of the field, and add a migration to update older in-progress forms.
	1. Create a migration to update old in-progress forms to the new schema structure.
	2. If the change removed a field, remove the field from the schema.
	3. If the change added a required field, make the field required in the schema.
	4. If the change updated the format of a field, update vets-json-schema to only allow the new format.

*Example*
Say we wanted to remove the required field, "Social Security number". We would first need to create a feature toggle via backend and frontend PRs, and then turn the toggle on in Staging (unless we were using one which had already been created for the sprint). We would then update vets-json-schema (requiring vets-json-schema, vets-website, and vets-api PRs) to make the field "Social Security number" optional. We would then remove the field from the UI, but wrap the change in the Toggler component, so that it's only removed when the flipper is switched. 

At this point in the process, Production has the "Social Security number" field, and Staging doesn't. Both environments are using the newest version of vets-json-schema, where the "Social Security number" field is optional, so vets-json-schema accepts both versions of the form. 

Once the change has been approved on Staging, we would need to clean up the feature flag. First, we would remove the Toggler components in the FE, causing the "Social Security number" to be removed regardless of the flipper status, and add a FE migration to remove the "Social Security number" field from in-progress forms. We would also update vets-json-schema to remove the "Social Security number" field, and create PRs to merge that change to the FE and BE. 

Once all changes covered by the flag are present on Production and no longer using the flag, we would then remove the flag from the codebase completely. Once the removal has been propagated to all environments, we would delete the feature flag from the various databases. 

*Resources*
https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide

**Comment by aplatt-coforma** [comment]
Thanks for the write up @TaiWilkin. Linking #80343 that @danlim715 is working on. Let's meet to decided on next steps on sprint workflow and ticket management
