### ISSUE TITLE
[DISCOVERY] Maintain Accepted/Denied POA state in vets-api

### ISSUE THREAD

**Issue by gabezurita** [department-of-veterans-affairs/va.gov-team#79973]
## Description
It's questionable whether we need this! This might be an exploratory issue on how ARP will handle potentially slow LH<>BGS<>CorpDB responses.

When a `RepresentativeUser` submits a POA request, it goes to BGS through LH. While the accept/deny state is in BGS, ARF must also determine how to maintain it in the ARP engine for the table view.

We might use [ClaimsApi::PowerofAttorney](https://github.com/department-of-veterans-affairs/vets-api/blob/60f4aa8adeb96c0d10f06181baea21bcd43f3272/modules/claims_api/app/models/claims_api/power_of_attorney.rb#L6-L7), which uses `include Filedata`, though that [does not have statuses](https://github.com/department-of-veterans-affairs/vets-api/blob/60f4aa8adeb96c0d10f06181baea21bcd43f3272/modules/claims_api/app/models/claims_api/power_of_attorney.rb#L15-L19).

## AC
- [ ] Figure out how to maintain the POA Request state in the ARP engine to be displayed on the front end. Implement it if possible.
- [ ] Sync w/ Design Team on implications for user experience

**Comment by kristen101606** [comment]
In the [mock ups](https://www.figma.com/file/C3sdnDf8anVqXVdmiCWwq8/%F0%9F%9A%A7-Accredited-Rep-Facing?type=design&node-id=437%3A34556&mode=design&t=l46PDZLf1uzm3CIj-1), we don't currently account for the potential wait time needed between the VSOfficer clicking accept the acceptance being received in BGS. Based on a discussion on 4/8/24, we might need to account for a few seconds--maybe more--to get confirmation of acceptance. My guess is that VSOfficers would be open to waiting with a spinner on the page for a few seconds and then getting a confirmation that their acceptance worked, rather than immediately getting a message saying, "You'll get an update later if this acceptance went through."
