### ISSUE TITLE
Remove age-based logic in "is your child disabled question"

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#80086]
## Issue Description
The purpose of this ticket is to update the logic for displaying the "is your child seriously disabled" question in the Household Information section of the pension benefits application.  Currently, the “Is your child seriously disabled?” field only displays if the child is under 17.75 years old. Based on instructions in the form (bullet one), this logic is not accurate.

---
## Tasks
- [ ] Remove age-based logic so that this question is visible when inputting data about children, regardless of their age

## Acceptance Criteria
- [ ] Question is visible regardless of value entered for child's age

**Comment by danlim715** [comment]
@matt4su Is removing veteran's responses to this question necessary? If they didn't answer the question the first time around due to the question being hidden, they will be prompted to answer before submission. But can you help me understand the value of re-asking the question to veterans who already provided this info?
