### ISSUE TITLE
Spike: Research ITF Backend Options

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#80083]
### Description of Spike

**In order to identify the most efficient technical approach for  implementing ITF into the online pension benefits application, research the existing ITF backend and document findings.

Investigate:
1. Does an endpoint exist that we can repurpose or do we need to create our own.
2. What is in place for logging?
3. Initial technical work identified to implement ITF includes creating flipper, creating endpoint, retrieve at submission.  Anything else needed?

#### Acceptance Criteria
- [ ] Documentation has been updated
- [ ] Next steps have been determined and documented

#### Timebox
Single Sprint

Context:
This investigation will support future work to implement the backend logic to use the 527EZ online application Start date/time rather than the Submit date/time as the Intent to File date/time.  When an authenticated user clicks the button to start the 527EZ online application, provide the ability to:

Identify if a valid pension ITF date/time exists and if so make it available for display to the front-end.
if there is a technical issue and it cannot be determined if a valid pension ITF date/time exists make this status available to the front-end. Do not block the user from populating and submitting the application.
If there is no pension ITF or an invalid pension ITF, set a new pension ITF for this user based on when they clicked the button to start the online application and make it available to the front-end.
Expiration dates: when a saved application is re-opened, calculate the dates to expiration and make available to the front end or if expired set a new date (last expiration date + 1 day).

**Comment by aplatt-coforma** [comment]
Please reference #75583 for some past work that we already did for ITF

**Comment by mjknight50** [comment]
What do we do when an ITF is more than 365 days old?

**Comment by sanjabaj2** [comment]
What do we do for unauthenticated user that is starting the application? If we are allowing unauthenticated user to submit pension application, should we create ITF for them too? Is that even feasible?

**Comment by danlim715** [comment]
1. There are currently 3 endpoint routes for v2, `get`, `submit`, and `validate`. If we want to update this controller to make the `create_or_find_itf` an async process, we will really only want 1 endpoint that will perform the lookup and create a new ITF entry if one doesn't exist. We probably can keep the validate endpoint as is, depending our frontend solution. This change may be a large enough overhaul to warrant creating a v3 endpoint instead.
2. As for existing logging, the v2 endpoint currently uses `ClaimsApi::Logger`, which is just a Rails logger wrapper. These logs are tagged with `itf_type`, `itf_validate`, or `itf_submit`.
3. If we opt to create a v3 ITF endpoint, we can go ahead with creating the new endpoint and controllers, but hidden behind a feature flag which wouldn't be activated until v3 was ready. If we want to modify the existing v2 controller, it'll be messier trying to add a flipper to toggle between old and new behavior, especially because we will need to consolidate some routes.

@sanjabaj2 No, ITF is for the authenticated experience only, since veterans' `participant_id` is needed to lookup existing and create ITF entries.

**Comment by danlim715** [comment]
Once the async changes are made to this ITF endpoint, the response given by this new `find_or_create` endpoint should always return success (barring any validation failures), since the lookup and create logic would be kicked off in a separate thread. The frontend design should be updated to either remove some of these ITF components or have the verbiage be updated to include additional info i.e. `An ITF will be submitted with the date of <current date>. If we find an existing intent to file that pre-dates <current date> we will continue to use that date. Please come back later to view your ITF status. If you believe you should have an ITF currently active for <benefit type> but aren't seeing any status updates, please contact <contact info>`.  Not sure how we're planning on displaying that info just yet, but the core messaging should include the fact that if we don't find an existing ITF, we will use today's date, otherwise we will keep using the earlier date.

**Comment by mjknight50** [comment]
Do a clean version, V3, please

**Comment by aplatt-coforma** [comment]
Linking #81408: Add v3 ITF endpoint as the next step to this ticket.
