### ISSUE TITLE
Find VA Forms Search - Release Plan

### ISSUE THREAD

**Issue by MickinSahni** [department-of-veterans-affairs/va.gov-team#8017]
## Acceptance Criteria
- [ ] Complete release plan for the launch

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/soft-launch/release-plan.md

**Comment by MickinSahni** [comment]
@stephorkandatx @jenniferlee-dsva @ncksllvn here's [the release plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/soft-launch/release-plan.md) for the launch. 
tl, dr: 
- ✅ Phase I: completed with the Forms Working Group 
- 🌀 Phase II - 4/20-4/23: 
  - Removes auth but leaves out any redirects/Top Recommendations updates
  - Success = achieving consistent % PDF download conversion rate with `/vaforms` for top searches e.g. 526
    - this is dependent on a) [analytics available](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7174) for `/find-forms` and b) baseline data for `/vaforms`
      - @jenniferlee-dsva I'm having a tough time wrangling this data from the work a couple months ago that Nedie helped with. Thoughts on where this might be?
- 🧃 "Go live" 4/23: 
  - Implement redirect from `/vaforms` to `/find-forms` ([IA Request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/5163))
  - Update [Top Recommendations](https://github.com/department-of-veterans-affairs/va.gov-team/issues/7695)

What questions do we have about this plan?

**Comment by stephorkandatx** [comment]
@ncksllvn Question for you - as we finalize the release plan, it would be good to know we can redirect a % of traffic to the new experience (/find-forms) from legacy (/vaforms) as Mickin mentioned above. Is  this currently possible or would require additional development effort?

**Comment by ncksllvn** [comment]
@stephorkandatx So there isn't a way to apply that kind of behavior to the redirects. It's either all or nothing. So, we should hold off on the redirects until we're ready for the 100% of users.

That said, we could do a semi-public launch by allowing traffic to `/find-forms` but not redirecting. We could throttle users from `/find-forms` and refer them to `/vaforms` if we've already reached our traffic %. But that may not be necessary if we aren't bringing in a lot of users to `/find-forms` without the redirects.

**Comment by MickinSahni** [comment]
Gotcha. And this was our hunch; the next phase of the roll-out is likely just removal of the auth until we hit a certain success milestone (likely PDF conversion rate consistent with `/vaforms`). At that point, we'd implement redirects and Top Recommendations updates.  

@ncksllvn could you explain what that throttling would look like to the user and what we'd need to do on our end?

**Comment by ncksllvn** [comment]
On our end, we'd need to implement the Flipper feature toggle into the API and FE code. We'd then be able to user the Flipper UI to limit traffic. I haven't used Flipper myself, but I think if the user has been rate limited, then we could show a message about what happened instead of the search form. 

So it would be -

- FE and API integrates a Flipper feature flag
- We use Flipper UI to allow 25% of users (not just page hits)
- 4 users come to `/find-forms` 
- The search tool is shown to one of them.
- The other 3 see a message like `We're sorry, but we are still developing this search tool. For now, please use /vaforms/ to search VA forms.`

**Comment by jenniferlee-dsva** [comment]
@ncksllvn 
>The other 3 see a message like We're sorry, but we are still developing this search tool. For now, please use /vaforms/ to search VA forms.

Instead of turning away the users not in the 25% bucket, is there a way to just NOT show them the /find-forms page? 

E.g., users who search for va forms on google - they see a link to the legacy https://www.va.gov/vaforms/ ; X% of traffic to `/vaforms `is sent to  `/find-forms`. 

And similarly - same but different path: users click on the Find a VA form link in our global footer;  X% of traffic to `/vaforms `is sent to  `/find-forms`.

**Comment by jenniferlee-dsva** [comment]
hi @stephorkandatx Replying to 

> I'm having a tough time wrangling this data from the work a couple months ago that Nedie helped with. Thoughts on where this might be?

Including the GA link here from the [older analytics ticket #1828](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/1828), which we used to identify our top forms:

https://analytics.google.com/analytics/web/?authuser=0#/analysis/a50123418w177519031p176188361/edit/8-kxQse4QCS3fyG8N0v98g

**Comment by ncksllvn** [comment]
> Instead of turning away the users not in the 25% bucket, is there a way to just NOT show them the /find-forms page?
> 
> E.g., users who search for va forms on google - they see a link to the legacy https://www.va.gov/vaforms/ ; X% of traffic to /vaforms is sent to /find-forms.
> 
> And similarly - same but different path: users click on the Find a VA form link in our global footer; X% of traffic to /vaforms is sent to /find-forms.

Hm, we haven't considered this before 🤔 So basically, we want our product released to the public  but not direct tied to a user flow. Users will instead still be directed to `/vaforms/`. However, on `/vaforms/` we redirect a % of users to `/find-forms/`.

This would be a new thing for teams. Basically, I think we would need to implement a Flipper feature toggle for Find Forms to control traffic %. Then, we would need to reference that inside of the header/footer JS injection script ,so that we could leverage it on `/vaforms/`. Then, if the user is in the bucket for showing `/find-forms/`, we simply redirect them off of `/vaforms/` and into `/find-forms/` via a client-side redirect. We'd hold off on the permanent server-side redirects.

So I _think_ this is doable, but it would be a new pattern. What do you think?

**Comment by MickinSahni** [comment]
That was the gist of my suggestion earlier but it sounded like it was an all or nothing thing?
https://github.com/department-of-veterans-affairs/va.gov-team/issues/8017#issuecomment-615302815

**Comment by ncksllvn** [comment]
It's all-or-nothing in the form of server-side redirects and being cautious not to do something a little different (we haven't used our inject script for conditional redirects or feature flags before) so that's where my head was at then, I think, but it does seem like we could get this redirect behavior now if we want to

**Comment by jenniferlee-dsva** [comment]
I think the flipper and traffic throttling %age issue is  now moot, post-last week's release plan discussion with @stephorkandatx and @MickinSahni . But correct me if I'm wrong, @stephorkandatx . 

Summary of last week's call was... 
step 1 is (like noted ^ in original ticket description) - remove the basic auth credentialing. 
step 2 is watching to make sure everything is functioning okay. [the main purpose of the mvp search exp is adding those conversion paths to those itesm in the blue cards and other online tools on this page for managing your benefits and info.] 
step 3 is doing a permanent redirect of the legacy find forms URL to the new page.
step 4 is when api is connected directly to the forms db, redirect the search-action.asp page to the new forms page -- ? [this part seems still up in the air - whether to do it post-db connection or to do it before by duplicating the scraped page somewhere else...? ] 

@stephorkandatx @MickinSahni @ncksllvn

**Comment by ncksllvn** [comment]
> step 4 is when api is connected directly to the forms db, redirect the search-action.asp page to the new forms page -- ? [this part seems still up in the air - whether to do it post-db connection or to do it before by duplicating the scraped page somewhere else...? ]

We're actually good on this front. We'll redirect section-action.asp as well. The Lighthouse API will be able to still tunnel to search-action.asp in its script by using a certain HTTP request method for submitting the form (POST). Once we do have direct DB access though, we should clean that up and request all forms HTTP requests (doesn't affect SEO, but it cleans up the code)

**Comment by jenniferlee-dsva** [comment]
Thank you @ncksllvn - I love it.
