### ISSUE TITLE
[RESEARCH] Spike: determine low-fi or tree test research study

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#80283]
## Tasks

- [ ] Identify what early questions we want answered from an unmoderated research study
- [ ] Identify type of research method that would work best, e.g., tree test or low-fi prototype from Figma

**Comment by benbrasso-agile6** [comment]
@cgednalske I think the goal here is to do some quick, unmoderated study to understand a Veteran's preference on the choose a provider page to validate our own recommendation: 

- [Day toggle option](https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?type=design&node-id=202-7450&mode=design&t=7g3CyPD9uIVbPsxa-4)
- [Multiple dates option](https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?type=design&node-id=222-8545&mode=design&t=7g3CyPD9uIVbPsxa-4)
- [Next available option](https://www.figma.com/file/DsRXEFiYLCFnY5nBkp9Dc4/CC-Referral-%7C-Appointments-FE?type=design&node-id=222-9499&mode=design&t=7g3CyPD9uIVbPsxa-4)

Likely, we probably need to add some more "actual/fake" content in those, if we're going to use screenshots. But, I think that's a good first research study. E.g., validate that Veterans think option 3 is the optimal solution.

**Comment by benbrasso-agile6** [comment]
If you want to think through this, confirm, and if confirmed, we close it and stub out a ticket for draft research plan. Should run idea by @Cieramaddox too. Maybe meet tomorrow to discuss? I'm out on Friday.

**Comment by cgednalske** [comment]
Adding the starting info here after meeting with Cara. 

### Notes from speaking with Cara:
- First click test probably won’t work in this situation 🙁
- Survey is still our best bet if unmoderated --- show an image and ask questions 
- Different pathways to test multiple flows (2 images each)
- Every cohort sees every pattern, but order is different to offset the fact that they learn from the first. (Sounds like we can’t show different cohorts different things due to PRA specifics.)
- Questions center less around what they would do — more around do they understand what their options are here? Examples:
  - How would you describe this page?
  - How would you describe it in a few words?
  - Describe what you can do on this page.
  - Which of the following descriptions matches your idea of the page?

### Some questions we want answered
1. Which scheduling pathway do Veterans consider most clear and in line with their scheduling needs?
2. What, if anything, do Veterans find confusing about the included scheduling pathways? 
3. Are there any provider selection needs/preferences these screens are not addressing?
4. _Depending on what we test: Do Veterans find value in having a choice between provider vs. availability/calendar pathways?_

### Recommended Approach
- Survey format - show images (likely 2 for each pathway/userflow)
- All cohorts see every pathway option but in a different order (can’t match different cohorts to different pathways due to PRA specifics).
- Questions center around if Veterans understand what their options are / what they can do.
- Aims to recreate a micro version of a moderated study

**Comment by benbrasso-agile6** [comment]
Ready for validation?

**Comment by benbrasso-agile6** [comment]
@anita-halici how do we get the swimlanes between Check-in and cc-scheduling to sync up. For example, ideally, if the ticket is moved into validate in cc-scheduling, then it moves into validate in check-in. 

Is that possible? Right now, they've very unsynced.

**Comment by cgednalske** [comment]
@benbrasso-agile6 yes! Ready for validation, but I didn't want to move/break anything 👀
