### ISSUE TITLE
Spike: Use of feature flipper for backend AND schema changes

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#80343]
## Background
As part of the Collaboration Cycle process, certain FE changes will need to undergo a review. As these review cycles take time, they suggested releasing these updates behind a feature flag so that they are hidden in production until sign-offs are provided.

We understand that some FE changes require changes to the BE and schema which need to be released as the same time. Our understanding is the currently available flipper does not apply to BE and schema code. This spike is to investigate possibility and what needs to developed to implement a feature flipper in the backend code and schema. 

## Acceptance Criteria

- [x] Research how a feature flipper can control what is available on PROD for BE changes
- [x] Research how a feature flipper can control what is available on PROD for schema changes
- [x] Document both findings
- [ ] Create eng. implementation tickets as needed

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/80343?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by aplatt-coforma** [comment]
@danlim715  can you please review @TaiWilkin write up in #79963 Spike: flippers to show/hide text, questions, pages and share your thoughts. See the section titled _Managing vets-json-schema Changes_ specifically.

I think we should agree on how we should use the feature toggles and how best to manage tickets/requests so it is very obvious which tickets need to behind these toggles. 

cc @mjknight50

**Comment by danlim715** [comment]
After reading over the Spike findings above and chatting with Tai, it was determined that Flipper implementation for the vets-json-schema repo wouldn't really accomplish much. We pre-generate the json schema during a version update and import the generated schema dist files into each respective code base (FE and BE). Since we don't generate the latest schema on the fly, adding flippers in vets-json-schema still wouldn't address the FE/BE deployment timing issues. It might be worthwhile to suggest to the VA.gov team to modify the deployment process to kick off the backend deployment before kicking off the frontend deployment. That way, each deployment is consistent and we can prevent failed submissions.

**Comment by danlim715** [comment]
Flipper does apply for BE code. We include a series of Flipper-related gems in the Gemfile and Flippers can be checked in the code via: `Flipper.enabled?(:name_of_feature_flag)`.
