### ISSUE TITLE
VRO/ARP Vulnerability Report

### ISSUE THREAD

**Issue by kingbmike** [department-of-veterans-affairs/va.gov-team#80499]
After finding that within SEP, anyone, not just a VRO, can create an account, make changes on behalf of a veteran, access veteran PII, etc.  Being that this is an enormous security issue, we need to escalate this to the proper channels.

Repro

- How do we access SEP
- How do we repro vulnerability
- What is the fix for this
- What are the negative impacts if this is not fixed

**Comment by bosawt** [comment]
Here are the notes I put in the leads channel to answer these:

First of all, there is NO current vulnerability on VA.gov production related to this. We have been advising a team that was tasked to bring the sep.va.gov VRO application to VA.gov, and luckily we inserted ourselves during their development, not after they integrated into production.
Background: On the sep.va.gov application, representatives are able to log in with a verified ID.me or login.gov account, and through an integration with an OGC database, these representatives are associated with an OGC number that is linked to veterans that they can perform delegate actions on behalf of.
Issue: The sep.va.gov application requires that a representative user log in with a verified ID.me or login.gov account. However, the issue is how they link a logged in user to a record in the OGC database. They check first name, last name, and input OGC number (which is publicly available and easily procured here: https://www.va.gov/ogc/apps/accreditation/index.asp) and match an authenticated user to an OGC record. This means that any user with the same verified first name and last name as an existing representative potentially can access the sep.va.gov as if they were indeed that representative.
Test: We noticed there were already multiple 'Richard Davis' entries in the OGC database, and we had our own 'Richard Davis' attempt to log in with an existing OGC number (which we searched for and found easily: https://www.va.gov/ogc/apps/accreditation/accredpeopledetail.asp?ID={03580EE7-3FC1-44E7-B4AB-30F216395720}&Type=Representative). The conclusion was that he was not only able to log in and potentially perform actions as if he were the representative 'Richard Davis', but he was actually able to lock out the other 'Richard Davis' from logging in (Dick Davis will present these findings at the next sprint demo).
Follow Up:
Dick has been working with the SEP stakeholders to fully inform them of this vulnerability
Joe has asked that the team leading the SEP replacement app (the ARP team) report this
Trevor has been working with the ARP team to identify ideas and options for how they might move forward. ARP team may propose a more manual process for their initial pilot and then some new feature for a full rollout
Ultimately Identity team controls whether the ARP team can release to production, as we will have to create a production authentication configuration record to allow them to authenticate users
Besides any sort of responsibility with reporting the vulnerability and reaching out and advising the ARP team, I don't think there's much else for the Identity team to do here
