### ISSUE TITLE
test out datadog

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#8053]
we got access to VA's datadog account, let's try this with new infra to see if we can replace out tooling with it.
- add aws integration
- try on ami
- add config with terraform / cloud-init
- ingest some logs
- can we do our funky stuff? (external monitoing, VAEC Connectivity, etc..) 
- apm?
- slo?

##  AC
- [x] Demo to stakeholders
- [x] Get to a point where we can say we will use DD or not.

**Comment by wyattwalter** [comment]
I did a writeup of what I've been thinking as I approach this so far: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/platform/infrastructure_recommit/monitoring/solution_evaluation.md

**Comment by wyattwalter** [comment]
We do not have anything in writing from the team that's managing DataDog because it was relayed in a call, but the spirit is this:

- Trial any features that we may want to make use of, but keep usage low
- Production data is not allowed, only dev/test
- Keep the node count low — no hard and fast rule but in the order of low 10's of nodes, i.e. 15 is ok but 150 is not

Our account is a sub-account under some VA organization and we've been given administrative access to it to invite folks on the program. I do not know what the intent is regarding login and administration of users once this system achieves an ATO.

Things that are missing for us to use it fully:

- Guidance as to what features can be used
- Permission to use it in production
- Node limit lifted, we'll need 150-200 nodes (there is not a technical limit to my knowledge, but we do not want to violate the verbal agreement here)

**Comment by wyattwalter** [comment]
At this point I think we have tested everything that we can and are ready to move forward. We are waiting for budget approval to continue, but the test itself (this ticket) is concluded.

**Comment by wyattwalter** [comment]
Still waiting on budget approval, but the decision to move forward with DD is a yes. Hopefully we can, but we're not going to revisit this exact decision. If we can't get the budget approval, then we'll fall back to our own internal Prometheus again.
