### ISSUE TITLE
Codeowners - PDF Audit

### ISSUE THREAD

**Issue by tblackwe** [department-of-veterans-affairs/va.gov-team#80807]
Platform noted in PR #[16334](https://github.com/department-of-veterans-affairs/vets-api/pull/16334) that the codeowners for various pdfs + fillers was out of date

Please audit the vets-api codeowners file for ownership on pdfs and pdf fillers for:

Non-disability: 
28-1900
28-8832
21-530 V1 & V2

Dependents
21-686C
21-674

**Comment by evansmith** [comment]
The generic folder of lib/pdf_fill defaults to this: `lib/pdf_fill @department-of-veterans-affairs/vsa-debt-resolution @department-of-veterans-affairs/backend-review-group @department-of-veterans-affairs/vfs-10-10 @department-of-veterans-affairs/vfs-1095-b`

It seems like the files themselves are not covered by codeowners otherwise, but the test files are.

Narrowing down within lib:
28-1900 - no codeowners present
28-8823 - no codeowners present
21-530V1 - no codeowners present
21-530V2 - no codeowners present
21-686c - no codeowners present
21-674 - no codeowners present

Narrowing down within spec
28-1900 - spec/fixtures/pdf_fill/28-1900 @department-of-veterans-affairs/Benefits-Team-1 @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group
28-8832 - spec/fixtures/pdf_fill/28-8832 @department-of-veterans-affairs/Benefits-Team-1 @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group
21-530V1 - spec/fixtures/pdf_fill/21P-530 @department-of-veterans-affairs/Benefits-Team-1 @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group
21-530V2 - spec/fixtures/pdf_fill/21P-530V2 @department-of-veterans-affairs/Benefits-Team-1 @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group
21-686C - spec/fixtures/pdf_fill/686C-674 @department-of-veterans-affairs/Benefits-Team-1 @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group
21-674 - spec/fixtures/pdf_fill/21-674 @department-of-veterans-affairs/Benefits-Team-1 @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group

**Comment by tblackwe** [comment]
Please update the owners as follows:

Benefits-Team-1 can be removed from All spec Files

For each appropriate file in `lib/pdf_fill/forms` `lib/pdf_fill/forms/pdfs` and `spec/fixtures/pdf_fill/`

686/674 files owned by `@department-of-veterans-affairs/benefits-dependents-management @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group`

1900, 8832, 530 V1/V2 owned by `@department-of-veterans-affairs/benefits-non-disability @department-of-veterans-affairs/va-api-engineers @department-of-veterans-affairs/backend-review-group`
