### ISSUE TITLE
Project Kickoff STEM Scholarship Form 22-10203

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8089]
## Steps to complete Project Kickoff
- [x] Product Manager: create this issue and fill in feature name in the title and other bolded information appropriately
- [x] Link to this issue once created in #vfs-platform-support in Slack; tag @ Megan Kelley @ AndreaHewitt
- [x] Andrea and Megan will schedule meeting with VSP reviewers and **requesting team** attendees (as listed below)
- [x] VSP <> **requesting team** kickoff meeting completed
- [x] All requesting team attendees complete brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Artifacts - _please bring the following to the kickoff meeting_
- [Product Outline Rough Draft](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/10203_product_outline.md)
- Explanation of the problem space

> The introduction of the Edith Nourse Rogers STEM scholarship resulted in a temporary modification to the 22-1995 in order to support digital submission while the details for the stand-alone application were finalized.  Now that the stand-alone form has been finalized, this effort is to revert the 22-1995 to it's original state and create a new digital application for form 22-10203.

- Any other artifacts you have so far
[22-10203 OMB (STEM application form).pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4488519/22-10203.OMB.STEM.application.form.pdf)
[1995 with STEM Flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/VA%20Form%2022-1995%20with%20STEM%20Process%20Flow%20122419%20v0.3.pdf)
[STEM Eligibility Flow](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/education-careers/stem/VA-Form-22-1995-Process-Flow-for-STEM-Pages-Only-021020.pdf)

## Meeting attendees from **requesting team**
- Product Manager (required): Darrell Neel
- DEPO Product Lead (required): Matt Self
- Entire VFS team (recommended): 
> Will McCormack
> Dan Shawkey
> Amy Knox
> Desiree Turner
> Michael Delli-Gatti

## Scheduling
Preferred dates or times: 
- Tuesday 4/21 (preferred): 11-12, 1:30-2:30
- Thursday 4/23: 10:00-10:30

**Comment by meganhkelley** [comment]
Scheduled for 4/21

**Comment by andreahewitt-odd** [comment]
Product outline feedback: 

Add information to the problem statement about issues with veterans not meeting criteria but still applying for the scholarship because it was part of the 1995 and the numbers about rejection because the criteria couldn’t be made clear as part of that other form. 

This is just a question or you to ponder and think about but I wonder if you want to break up your desired user outcomes/undesired user outcomes/desired business outcomes/undesired business outcomes/KPIs by form?
 - Matt pointed out when I asked this that there’s no desire from EDU to track KPIs around 1995 form 

Make it clear that “Valid Application submissions, # and %” in KPIs refers to 22-10203 form

Overall feedback:

Don’t forget to add this to Collaboration Point Tracker: https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit#gid=1341642809

**Comment by dneel-bah** [comment]
- Feedback integrated into the product outline.
- STEM Effort added to Collaboration Point Tracker
- Survey link provided to BAH team member participants.
