### ISSUE TITLE
Tooltips in form design on design.va.gov

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#81]
- Tool tips are components. We may use tool tips to help user understand context (Why does this matter? What is this thing?)
- Tool tips are NOT used to bury additional content that may be relevant to a user's application. 

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by rtwell** [comment]
## Additional info

The additional info pattern is a context specific interaction where we provide users with relevant information that helps gain about the decision they are about to make. This information is hidden beneath a quasi-accordion-like interaction because it isn’t necessary for the majority of users and would impede the primary action on the page. 

### Example:
A user might need to list conditions they have in a disabilities form. We ask them: 
Search the name of your condition
And the additional info interaction would be:
“What if I don’t know the name of my condition? >”
When the user clicks, they see an explanation of what to search for, and an example search to further illustrate the explanation.

![image](https://user-images.githubusercontent.com/12564977/58118228-6afdad00-7bce-11e9-843f-6e3782b46d84.png)
![image](https://user-images.githubusercontent.com/12564977/58118237-6df89d80-7bce-11e9-87af-d7736a4a6131.png)


### Do: 
Help users by providing contextual, relevant information that brings clarity to content they are taking action. 

### Don’t:
Don’t use this pattern to house information that is critical to the form or content relevant to the specific interaction a users has to take.  

@goldenmeanie @smoonpeyes @jaredcunha-usds some thoughts:
1. Do we want to continue calling this "Addional info"?
2. There is at least one instance of this pattern used in an alert that feels weird to me from a UX/pattern perspective which is the [Homeless alert](https://www.va.gov/housing-assistance/) we have on a few pages. I have no idea what to do about this (well, that's not true, i have strong opinions about what to do about it, but that's just me 😄). Which leads me to…
3. How do we want to approach improving patterns we know could be better (this example or otherwise)?

**Comment by smoonpeyes** [comment]
@rtwell I think "Additional information" works. 

Maybe you could add an "Issues" and/or "Recommended improvements" section to identify where we can improve? Maybe we could also create ZenHub issues to track patterns that need more work.

**Comment by jaredcunha-usds** [comment]
Adding @jenniferlee-dsva's comment here. Not sure why the comment button was disabled?

>Saw this and tried to comment but for some reason the comment button is disabled for me.<br>
Just as an FYI – the content team calls this affordance “helper text,” which describes the context and function this is used.<br>
It would be helpful to have real hover helper text rather than this kind-of-dropdown-kind-of-accordion. (Am thinking of future needs we may have, for instance, around Spanish translation affordance….)

**Comment by jaredcunha-usds** [comment]
@jenniferlee-dsva From what I understand, there were accessibility concerns with using hover actions on these.

**Comment by rtwell** [comment]
see in draft form: https://dev-design.va.gov/patterns/additional-info
