### ISSUE TITLE
Analytics Implementation for VA Coronavirus Chatbot

### ISSUE THREAD

**Issue by rumyeahs** [department-of-veterans-affairs/va.gov-team#8104]
# Analytics Implementation or QA Request

## What this form is for
Use this template to request Google Tag Manager and Google Analytics implementation or QA for your product. Please fill out all brackets. 

> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints:
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

## Description
- Is this request for Google Analytics implementation or QA?
Google Analytics implementation

- Who is this request for?

    - @kaeliwyuen 
- @batemapf 
- @karlbrown-va 
@rumyeahs 
@katieho-va 

    _Provide any relevant contact information and link this issue to the insights team on the DSVA Slack Channel: `#VFS-Platform-Support`._
    
- What team/project is this work for?
    _this adds context for the data_
    
This is for the VA-Chatbot project
https://github.com/department-of-veterans-affairs/covid19-chatbot

    
- Provide the Domain where Google Analytics needs to be implemented
    _i.e. www.staging.va.gov_
This is for a new page on VA.gov. The final URL will be https://www.va.gov/coronavirus-chatbot 
    
    _Identify if PII is passed in URL or title tag_
    
    - [Provide Domain here]
- Please provide any upcoming deadlines or important milestones
Chatbot Launch
    
    - [Provide relevant dates here]
Looking to launch this next week (~ Apr 23)

- Typical Website Interactions to Track

    - *Conversions - Understanding the User Flow:* _Provide URLs that are part of the application from introduction page to successful form completion; conditional pages that are visible depending on an applicant's answer should be marker accordingly._
    

1. Visitors on the new chatbot page
2. Sources for the new chatbot page (Incoming traffic)
3. Total users vs New users on Chatbot page, as compared to for FAQs page, and Facility Locator page
4. Time on Chatbot page and Session duration

    - [URLs here]
    
    - *Other User Interactions*: _Provide details on other interactions and metrics, like click to help text links, that are helpful in understanding user behavior._
    
    - [Other user interactions here]

- Sample Users when authentication is required _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide sample users or link to user information here]

- Test Users to replicate the event _**do not put staging credentials in your `va.gov-team` ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository**_

    - [Provide test users or link to user information here]

- Certain conditions/responses that need to be reviewed

    - [Provide conditions/responses here]

- Additional Comments

    - [Add any comments or questions for the Insights team here (if applicable).]

> Please leave the following blank

## Acceptance Criteria
- [ ] QA has been completed
- [ ] VFS team completes brief [VSP Collaboration Cycle Feedback](https://adhoc.optimalworkshop.com/questions/20260uu8-0-0/questions/before) survey

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@rumyeahs Thank you! Confirming receipt!

**Comment by leahbannon** [comment]
For the following metrics we'd like to track, would these be tracked in google analytics? If so, are these metrics already a part of the implementation you have planned?

- an event triggered every time /coronavirus_chatbot is loaded
- an event triggered for success in opening chatbot convo
- an event triggered for failure in opening chatbot convo
- an event triggered for success in connecting to chatbot
- an event triggered for failure in connecting to chatbot

**Comment by jonwehausen** [comment]
Hi @leahbannon,

Thanks for your input here! We are set to have a conversation with the team here in a bit to flush out requirements. 

We can work to include these metrics per your recommendation.

**Comment by jonwehausen** [comment]
### Datalayer Requirements

cc: @katieho-va @shaunhubbard-va @batemapf @leahbannon @rumyeahs

Description of Interaction | Screenshot | Datalayer Push
------------ | ------------- | -------------
Successful load of the chatbot | N/A | `dataLayer.push{(`<br>`'event': 'chatbot-load-successful'});`
Failure to load chatbot | N/A | `dataLayer.push{(`<br>`'event': 'chatbot-load-failure',`<br>`'error-key':'<code_description>'`<br>`});`
Successful connection of the chatbot | N/A | `dataLayer.push{(`<br>`'event': 'chatbot-connection-successful'});`
Failure to connect to chatbot | N/A | `dataLayer.push{(`<br>`'event': 'chatbot-connection-failure',`<br>`'error-key':'<code>_<description>'`<br>`});`

@katieho-va These dataLayer requirements are now ready for begin implementation when you all are ready.

**Comment by bsmartin-ep** [comment]
Datalayer / record events JS...

https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/monitoring/record-event.js

Example usage...
https://github.com/department-of-veterans-affairs/vets-website/blob/b38a5be6ec384428ca9c09607205bedbf49d47c6/src/applications/vaos/actions/newAppointment.js#L641

In case you want to see the Google docs...
https://developers.google.com/tag-manager/devguide#events 

cc @katieho-va

**Comment by jonwehausen** [comment]
@bsmartin-ep Lets proceed with the following:
- Staging a workspace with GTM that utilizes this taxonomy 
- Event Category: API Calls, Event Action: COVID - Chatbot, Event Label: {{Event}}
- Making sure non-interaction is set to false so they do not impact bounce rate

**Comment by jonwehausen** [comment]
## QA Testing
cc: @batemapf @bsmartin-ep 

### Failure Simulation
Description | Screenshot | Test Status | Notes 
------------ | ------------- | ------------- | -------------
Simulated a **successful** load, yet **unsuccessful** connection | ![image](https://user-images.githubusercontent.com/48527022/80028134-af668c80-84b2-11ea-9739-1422c82a0f1b.png) | ✔️ **PASSED** | n/a
Simulated an **unsuccessful** load | ![image](https://user-images.githubusercontent.com/48527022/80028754-98746a00-84b3-11ea-8f6e-b0390d2128d5.png) | ✔️ **PASSED** | <br> - This scenario causes the conversation to never start, therefore not also firing a `connection-failure` event <br> - Noticed there is no `error-key` passed here, just want to make sure this was intentional @batemapf ? 


### Successful Simulation
Description | Screenshot | Test Status | Notes 
------------ | ------------- | ------------- | -------------
Simulated a successful load | ![image](https://user-images.githubusercontent.com/48527022/80029339-a5de2400-84b4-11ea-8630-7c03e2d9cb16.png) | ✔️ **PASSED** | n/a
Simulated a successful connection | ![image](https://user-images.githubusercontent.com/48527022/80029400-b8585d80-84b4-11ea-8936-8806d428432a.png) | ✔️ **PASSED** | n/a


### GTM Tag Testing
Event Name | Screenshot | Test Status | Notes 
------------ | ------------- | ------------- | -------------
`chatbot-load-successful` | ![image](https://user-images.githubusercontent.com/48527022/80029567-f3f32780-84b4-11ea-9c80-50c3ffe7639f.png) | ✔️ **PASSED** | n/a
`chatbot-connection-successful` | ![image](https://user-images.githubusercontent.com/48527022/80029625-0ec59c00-84b5-11ea-88eb-9a6b1fa91293.png) | ✔️ **PASSED** | n/a
`chatbot-connection-failure` | ![image](https://user-images.githubusercontent.com/48527022/80030464-36693400-84b6-11ea-9b2f-a916e47343bf.png) | ✔️ **PASSED** | n/a
`chatbot-load-failure` | ![image](https://user-images.githubusercontent.com/48527022/80030240-eee2a800-84b5-11ea-9ee0-ae0ca478f593.png)  | ✔️ **PASSED** | n/a
