### ISSUE TITLE
21P-0969 Research Approach for vets-api architecture

### ISSUE THREAD

**Issue by matt4su** [department-of-veterans-affairs/va.gov-team#81163]
The purpose of this spike is Engineering team research to  sketch out or plan architecture/design for vets-api.  Can we reuse or do we duplicate code?

Tasks

- Perform documentation and code review
- Discuss with applicable SMEs
- Document findings and proposed approach

PDF Form:
[VBA-21P-0969-ARE.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHlIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f60b3839705ffe3cbf964a0bebee6c7c6dbe2538/VBA-21P-0969-ARE.pdf)

**Comment by aplatt-coforma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/issues/department-of-veterans-affairs/va.gov-team/81163?planning-poker) with Zenhub @danlim715 @mjknight50 @scottsdevelopment @TaiWilkin @ToddWebDev @wayne-weibel

**Comment by danlim715** [comment]
@matt4su @aplatt-coforma @mjknight50 How are we envisioning submitting this form? This it going to be attached as an attachment to the pension application?

**Comment by danlim715** [comment]
Since we'll be adding a new form, there's not much code available to reuse outside of web components on the frontend and helper functions in the backend. There are well documented standard procedures for the [frontend](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-overview) when adding new forms. In the backend, we'll need to create a new route for this form, as well as any models, DB tables, and a new controller to handle submissions. For [PDF mapping](https://depo-platform-documentation.scrollhelp.site/developer-docs/pdf-generation), we can follow the same structure as our 527EZ form. We'll also need to add a new schema for this form, which is also well documented [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/frontend/vets-website/creating-form-schema.md). Overall, this new form should be pretty standard and there doesn't seem to be any reason to deviate from the documented procedures for this implementation.

**Comment by danlim715** [comment]
Here's the link to the technical architecture document: https://docs.google.com/document/d/1VpFXr5NdXNgwHyYCZ1LBFqytNEC4IqUkLNTt0aZzlcw/edit

**Comment by aplatt-coforma** [comment]
Based on Dan's tech doc, I created the backend tickets for implementation. They can be found using here:
https://app.zenhub.com/workspaces/benefits-pension-64e775aaa6b1ca1ed49b2ede/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzODA3Mg&labels=backend
