### ISSUE TITLE
[Login] Terms of Use: Downtime launch copy for 4/25 launch

### ISSUE THREAD

**Issue by Samara-Strauss** [department-of-veterans-affairs/va.gov-team#81353]
@DanielleThierryUSDSVA can you review this copy for the downtime alert we plan to put on the unified sign-in page during the 4/25 TOU launch? Let us know if we need to change this.

----

We’ll be doing some work for the authentication to the MyVAHealth Portal. The maintenance will last 1 hour. During that time, you won’t be able to sign in to the MyVAHealth Portal.

**Date**: Thursday, April 25th, 2024
**Start/End time**: 9:00 p.m. to 10:00 p.m. ET

**Comment by DanielleThierryUSDSVA** [comment]
Thanks, @Samara-Strauss! 

We'll want to add the **Upcoming site maintenance** header. And a few suggested tweaks. I think since this is health care, we should make it clear that they can always contact their VAMC.

**Upcoming site maintenance**

We’ll be doing some work on the sign in experience for the My VA Health portal. The maintenance will last about 1 hour. 

If you use the My VA Health portal, you won’t be able to sign in to the portal during this time. You can always contact your local VA medical center for health care needs. [Find your local VA medical center](https://www.va.gov/find-locations/)

**Date:** Thursday, April 25, 2024
**Start and end time:** 9:00 p.m. to 10:00 p.m. ET
