### ISSUE TITLE
Review Sentry errors for systems and facilities - Part of Conversion spike

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8137]
Review Sentry logs and better classify the facilities error categorization

**Comment by lenaecb** [comment]
@jbalboni - find anything interesting / noteworthy from your review?

**Comment by jbalboni** [comment]
Front end errors on facility page since 3/24:

1. Timeouts: 10
2. Bad gateway error: 19
3. Misc network/client errors: 3
4. Bad request error: 14 (all on 3/24 due to FE bug, none since)

I would say that then that we have 46 instances of someone being blocked on the facility page. I don't know if you can directly compare that to our conversion numbers, but it would cover 7% at most of the 626 users who didn't started the flow but didn't finish (and be responsible for a 3% drop in the conversion rate).

We've already addressed 4), and 3) is not something we can reasonably impact. 1) and 2) are things we can research and possibly address.

I don't see anything in our current Sentry data that suggests errors are causing a significant number of our failed conversions.

**Comment by jbalboni** [comment]
I've also merged a change to group facility page Sentry errors together, so we should see those more clearly in the future.

**Comment by lenaecb** [comment]
Interest, ok, thanks @jbalboni 

I'll add your notes to our spike story. The segmentation that I worked on with Jon is showing an interesting breakdown of users dropping off from eligibility constraints. looking like about 16% of our dropout relate may have some correlation to the eligibility checks. Adding in this 3% here, we're about 19% accounted for in our conversion (potentially).
