### ISSUE TITLE
Document backend_name and url for APIs that Pension service calls

### ISSUE THREAD

**Issue by aplatt-coforma** [department-of-veterans-affairs/va.gov-team#81990]
Fwdproxy logs on Datadog are indexed starting 04/30/24, so we can now monitor all our backend API services. 

Logs can be seen [here.](https://vagov.ddog-gov.com/logs?query=source%3Afwdproxy%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1714499224058&to_ts=1714502824058&live=true) 

We'd like to setup monitors for our services by filtering per backend_name and url.

- [x] Document all backend_name of services used by Pension service
- [x] Document all urls used by Pension service

Creating actual monitors is out of scope for this ticket.

**Comment by mjknight50** [comment]
Moving as @sanjabaj2 requested

**Comment by TaiWilkin** [comment]
I identified a number of endpoints accessed by the front- and back-end during the Pensions form flow, by reviewing endpoints called by the browser and logs and metrics created locally during form creation and submission, and cross-referencing those with production logs and metrics, as well as reviewing the code for the services called by the modules called by Pensions endpoints. 

In the case of the third-party services, especially those used for prefilling the form, the Vets API services which we connect to (such as VaProfile) sometimes connect to additional services and third-party services. I've tracked as many of these services through all their possible paths as far as seemed reasonable to gather the endpoints that Pensions definitely calls during prefill, but without a way to identify which endpoints are called by which applications within the production logs, a complete audit would require significantly more time than we originally estimated for this work. 

## Vets API Endpoints  

The following Vets API endpoints are called directly while filling the Pensions form as part of the form process. Because these endpoints are within Vets API, they don’t go through the forward proxy, and they don’t have a backend_name. 

|   |   |   |   |  |  |
|---|---|---|---|---|---|
|Route|Action|Controller|Rails Action|Endpoint|Owned by Pensions|
|/v0/in_progress_forms/21P-527EZ|GET|V0::InProgressFormsController|show|/v0/in_progress_forms/21P-527EZ|Yes|
|/v0/in_progress_forms/21P-527EZ|PUT|V0::InProgressFormsController|update|/v0/in_progress_forms/21P-527EZ|Yes|
|/v0/pension_claims|POST|V0::PensionClaimsController|create|/v0/pension_claims|Yes|
|/v0/pension_claims/:id|GET|V0::PensionClaimsController|show|/v0/pension_claims/:id|Yes|
|/v0/in_progress_forms/21P-527EZ|DELETE|V0::InProgressFormsController|destroy|/v0/in_progress_forms/21P-527EZ|Yes|
|/v0/feature_toggles|GET|V0::FeatureTogglesController|index|/v0/feature_toggles|No|
|/v0/user|GET|V0::UsersController|show|/v0/user|No|

In addition, endpoints such as /v0/backend_statuses, /v1/sessions/logingov_signup/new, and /v0/maintenance_windows/ are sometimes called while filling the Pensions form, but not as part of the form process.

## Forward Proxy Endpoints

The following endpoints are called by Vets API endpoints used by the Pensions form during the form creation and submission process. Because these are third-party services, they do go through the forward proxy. These services are used by multiple applications, and there doesn’t seem to be a way to track the source of the calls to specific applications.

|   |   |   |
|---|---|---|
|Purpose|backend_name|Endpoint|
|ITF|lighthouse_gateway_back|/services/claims/v2/veterans/{id}/intent-to-file/pension|
|Claim Submission|lighthouse_gateway_back|/services/vba_documents/v1/uploads<br><br>/services/vba_documents/v1/uploads/{id}|
|Prefill|vet360_back|/contact-information-hub/cuf/contact-information/v1/{id}|
|Prefill|vet360_back|/profile-service/profile/v3/2.16.840.1.113883.3.42.10001.100001.12/{edipi_id}%5ENI%5E200DOD%5EUSDOD|
|Prefill|evss_back|/VONAPP2/wss-pciu-services-web/rest/pciuServices/v1/emailAddress|
|Prefill|evss_back|/VONAPP2/wss-pciu-services-web/rest/pciuServices/v1/primaryPhoneNumber|

**Comment by TaiWilkin** [comment]
@sanjabaj2 @mjknight50 I've included my write-up on this above.

**Comment by sanjabaj2** [comment]
Tagging @va-albers for input. Thank you Tai.
