### ISSUE TITLE
[UX] 10-10EZR Attach Docs: Designs for Attaching Documentation

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#82042]
As a Veteran who was exposed to toxins in the Service, I would like to have a way to attach my old orders to my EZR so that the VA has all the information I can provide on my toxic exposure.

- [x] Get validation for new file input component
- [x] Kick off with Devs and content
- [x] Capture technical constraints
- [x] Incorporate content changes
- [x] **Success: Team has designs for attaching documentation**

**Comment by emily-brown34** [comment]
Hieu to follow up/meet with Aliyah for content updates to the designs/doc upload

**Comment by IMHieuVo** [comment]
Supporting Doc, Upload Menu v1 vs Upload Menu v3: since the backend schema is not ready for V3, we’ll revert to V1. In Upload Menu v1, the Document Type dropdown list is confusing because every option is an official government document but HEC is okay with non-governmental documents such as journey, photo, etc for TERA. So to avoid confusion, the team wants to hide the document type dropdown from the user and confirm with that backend/VES that they can receive an “Other document” type label. HEC is also not expecting an exhaustive file type all documents uploaded can be “Other documents”.

DEV: The dev team has to confirm that we can add “Other document” as a label and that the backend can receive such an item. 
UX: The UX team has to confirm that changing V3 to V1 does not inherently change the design and content.
