### ISSUE TITLE
10-7959f-2 - payment screen

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82129]
As a VA.gov user, I want to be able to select payee for my FMP claim so that payment is made for my claim.

- use v3 components
- Figma [link](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?node-id=732-40895&t=Xp5d6bGBoSRA7fiG-0)

## Acceptance Criteria

  - Given the user is filing an FMP claim and filling out the 10-7959f-2 form, 
  - When the user gets to the payment screen
  - then the user should be able to select payment recipient

**Comment by reiting** [comment]
@marywang2 @brian-wilke I have a question about this screen. I see on Figma that the required is listed next to the send payment to at the bottom of the screen (right above the 2 radio buttons). However, the way the forms library works, the required is at the top of the page. I can think of a way to probably make it work (making the entire thing except for the last bit a component of its own and then have the bottom bit be the payment component. I can't guarantee it would work, but I think it most likely would. However, I wanted to ask if that's what you want me to do because I know  that we usually want to do what follows the patterns in the forms library. If so, that's fine! Just let me know either way and I'll work on it...including a screenshot below just for reference: 

<img width="809" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGdUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f62ccc32d7eb76d20a8647c031aada797926ccef/Screenshot%202024-07-26%20at%202.04.50%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 2.04.50 PM.png" />

**Comment by marywang2** [comment]
@reiting thanks for checking - we can follow the standard pattern for this one. cc @brian-wilke

**Comment by brian-wilke** [comment]
I also support using the library v. custom. 
I am not able to see the screen capture though (Github issue).

If I can get a visual on it, I would like to match up the Figma, too.

**Comment by reiting** [comment]
This is now in platform review

<img width="809" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c723f31e6ba8933d97ed3cf3c318350800f0a6c/Screenshot%202024-07-26%20at%202.04.50%E2%80%AFPM.png" alt="Screenshot 2024-07-26 at 2.04.50 PM.png" />

**Comment by reiting** [comment]
Got this merged just now! Should be in staging in a few hours, or by tomorrow morning at latest.

**Comment by reiting** [comment]
@marywang2 this should be in staging now.
