### ISSUE TITLE
10-7959f-2 - Veteran Contact Information page

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#82127]
As a user on va.gov, I want to enter my phone number and email address so that I can be contacted for about my FMP claim.

[Figma](https://www.figma.com/file/WYZCqWcS2gJWIqLtmQlvl7/10-7959f-2?type=design&node-id=726-21596&mode=design&t=WkD8EY1rrT2jQsNa-0)

- phone number can be entered in open text field (optional)
- email can be entered in open text field (optional)
- user can go forward or back to previous pages
- user data should be pre filled if signed in
- use v3 components

AC:
- given I am a VA.gov user, 
- when I navigate to the online form 
- then I should be able to enter my phone and email address into the form fields

**Comment by marywang2** [comment]
@reiting I added some more details regarding phone number validation - please let me know if this should be its own ticket.

**Comment by marywang2** [comment]
@reiting I didn't get the notification when you tagged me, there's a separate ticket for this for the FMP registration (but it would also apply here) so I removed it.

**Comment by reiting** [comment]
@marywang2 (I know you don't get notifications, but I'm just tagging you anyway) this PR is in platform review. The numbers at the top (eg 3 of 4) aren't correct right now, because we don't have the mailing/physical address pages yet. So it defaults to this being the third page. But it will be corrected once we add those pages before it. 

<img width="976" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--087496b17a28be289fd39cef45f334f1aed74a14/Screenshot%202024-05-31%20at%2011.32.59%E2%80%AFAM.png" alt="Screenshot 2024-05-31 at 11.32.59 AM.png" />

Branch is 10-7959f-2-contact-information.

**Comment by reiting** [comment]
Done. Sorry, form wasn't capitalized in Figma, but I should have asked about it to be sure.

**Comment by marywang2** [comment]
@reiting I see it capitalized in the Figma - just want to make sure you're using the latest version ([mobile](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=726-21596) and [tablet](https://www.figma.com/design/WYZCqWcS2gJWIqLtmQlvl7/FMP-Claim-Cover-Sheet-(10-7959f-2)?node-id=732-40895)):
<img width="370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzR2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91cfab2e6b0a44be0955216f0b7fa7fb4d0963b4/Screenshot%202024-06-03%20at%2010.18.23%E2%80%AFAM.png" alt="Screenshot 2024-06-03 at 10.18.23 AM.png" />

**Comment by reiting** [comment]
I must have had the wrong version up, because I know I double and triple checked to be sure form was not supposed to be capitalized and that was definitely what it was showing.

**Comment by reiting** [comment]
This has been merged
