### ISSUE TITLE
Investigate vet experience at submit (IPF?)

### ISSUE THREAD

**Issue by SamStuckey** [department-of-veterans-affairs/va.gov-team#82474]
We need to answer two questions

1. After a vet hits submit, what do they see if they return to the page / their in progress forms area, whatever is available?  Underlying question, are we still showing them an open, unsubmited form while our submission jobs are running?
2. Is this linked to the presence of an InProgressForm record?  If so, how does the presence of this record affect the UX?

**Comment by mengA6** [comment]
Thanks! Commenting to get updates on this. cc @evelynhilbrichdavis

**Comment by evelynhilbrichdavis** [comment]
First, the high level understanding of the relationship between submission and deleting the IPF/ITF.

The jobs to clean up the IPF/ITF after submission happen after the Claim ID is established and all of the `perform-ancillary-jobs` (see visual for included jobs for uploads, 4142,0781,8940, etc) run. If any of those jobs have to retry, it extends the timeframe before cleanup and IPF deletion can happen. As a result, the IPF remains available and open to Veterans for resubmission until that cleanup is complete. 
<img width="329" alt="def perforn_ancillary_jobs(first_name)" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/142252841/cf7e7b1b-4d34-47eb-a63e-ff3380cd55ef">

**Breaking down what happens based on different user experiences**

**1. Veteran receives a "We're sorry" submission failure error with no claim ID**
- They can still access their IPF. When they do open it, they are sent to the beginning of the 526, fully prefilled with the claim they just submitted. 
- As they click through to resubmit, they can make changes so the resubmission is not an exact duplicate (contributing to the challenge of identifying "duplicates" when slight changes are made
- They will be able to continuously open the IPF and resubmit it until a claim ID is generated and `perform-ancillary-jobs` runs successfully.

**2. Veteran is told their claim was successfully submitted with claim ID**
- On staging, the IPF is deleted and there is no way for them to create a duplicate
- However, in production, it is likely that all Veterans have a window where they can access and resubmit a 526 because even after the claim ID is established, `[perform-ancillary-jobs]` still needs to run all the way through before it gets to cleanup.

**3. Veterans are told submission is "taking longer" without claim ID**
- We have not been able to recreate this scenario, but because the cleanup doesn't run until after the claim ID is generated, we can assume that Veterans still have access to their IPF for a longer period of time until that claim ID is created and [perform-ancillary-jobs] runs all the way through to cleanup the IPF and ITF.

**Comment by evelynhilbrichdavis** [comment]
[Veteran hits back during submit loading screen](https://dsva.slack.com/files/U05NY30QW6N/F0749FT8J58/back_button_on_loading_screen_duplicate.mov)
[Veteran submission fails, returns to In Progress Form](https://dsva.slack.com/files/U04THN07094/F0730B2GZTN/dupesy_ux.mov)

**Comment by SamStuckey** [comment]
@evelynhilbrichdavis 's answer nails it. This was an question that was floated by @emilytheis in a retro (or planning?). I don't recall what the next steps were intended to be here.  My guess is we can close this and have the research herin for when this question resurfaces.  Closing
