### ISSUE TITLE
Burial | Update File Upload Pattern

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#82545]
## Issue Description
_The updated burial form uses the v1 file upload design system pattern, and it needs to be updated to the [new v3 pattern](https://design.va.gov/components/form/file-input)._

---

## Acceptance Criteria
- [ ] File upload pattern uses v3
---

**Comment by Midge-dev** [comment]
@steele-lm After reviewing the code, I realized I made a mistake in thinking there was a V3 "**pattern**" available for the File uploads.  This is not the case. There _is_ a new V3 "**component**", but there isn't a pattern available yet that uses this component. Currently, platform is rendering a normal input in the existing pattern, which doesn't take the `uswds` prop that would enable V3 styling to appear. The existing pattern would need to be updated or rebuilt in order to use the new V3 styling in our upload pages.
