### ISSUE TITLE
Design Feedback for Design Intent Collab, PCPG CH36

### ISSUE THREAD

**Issue by CrystabelReiter** [department-of-veterans-affairs/va.gov-team#8294]
**Do:** Mandatory feedback
**Try:** Exploratory next step
**Consider:** Sharing ideas/alternate ways of thinking

**Do:**
No “Do” feedback at this time

**Try:**
No “Try” feedback at this time

**Consider:** 

- Make sure the “Print this page” interaction is consistent with how Jonathan and Riley have been building (I feel like I remember seeing a printer icon and maybe it was a text link? Not totally sure but seems different than theirs)

- [On this page](https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/screen/9193f386-a740-4a07-89b3-0d981ce49aa8/CH36-Landing-1),  the “Apply for Educational and Career Counseling” can be a green primary button, also  in the sentence case. 

- Consider adding the double arrow icons to the “Continue” and “Back” buttons

- [On this page](https://xd.adobe.com/view/d37b343f-1a48-4aee-782d-2a78d6109478-a54a/screen/76aa9cae-754d-4914-8ed1-7c8ba9aa0a9b/8832-Intro-LooggedOut-1), the top nav bar appears to be logged in when it says on the page that you need to sign in order to start application

**Questions:**
If the Veteran is logged in, does that change the options on Step 1 at all? (Would we make any assumptions about who they are if they already have an account? For example - would we remove “Active duty service member with 6 months or less before discharge”?--We discussed this and for MVP we will give all the options--there’s talks in the future that it’d be more specialized 

**Definition of Done:**
- [x] Incorporate the **Do** feedback, and let us know on this ticket when they are updated mockups to check out (since there is no do feedback on this ticket, this is checked off)

- [x] Leave any comments for feedback you decide _not_ to take

**Comment by sporeboy** [comment]
Thank you for the feedback! Addressing the questions raised:

- Revised **Print** button and placed it in blue confirmation box to align with Caregiver mocks; not 100% sure this is canon yet; no icon in Sketch file button
- Made **Apply** button green; title case is used because PCPG is the new formal program title
- Double arrows added
- Fixed snot-signed-in state

I'll need to defer answering the question of changing the form to present Veteran-only options when a Veteran user is logged-in. Some investigation is still needed.

**Comment by CrystabelReiter** [comment]
@sporeboy Thank you for letting us know! closing ticket now
