### ISSUE TITLE
[Congressional] V11751442 Due 6/25/24 Rep Lankford

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#82985]
## Issue Description
Veteran is trying to validate their ID by using his Oklahoma driver's license for his VA.gov account, but it keeps rejecting.

https://app.slack.com/client/T03FECE8V/C02BS78NYRM
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
5/14/24:  Sent initial contact email to Veteran for further detail.  Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
5/14/24: Sent Rachel and Login.gov team Congressional for assistance.
5/15/24: Veteran responded. Advised that email address is different and using Login.gov to sign in.

**Comment by Kimberley2023-CSM** [comment]
Updates:
5/14: KMD emailed veteran; veteran responded same day confirming issue is that they cannot login with previous credentials,
5/15: KMD looked into veterans credentials and responded asking which credential service provider are they using when encountering this issue. Login.gov looked into and found that they do not have record of an account using the email address veteran provided. Veteran responded same day advising they provided the wrong email address and sent correct one for us to look into.
5/16: KMD spoke to the veteran to get more information. The veteran since they had a OK driver's license they updated certain information with the DMV, which could be causing the issue uploading ID. Kimberley provide a couple of options for the veteran  to chose from and confirm if they were successful. Waiting for a response.

**Comment by Kimberley2023-CSM** [comment]
Veteran replied on 5/21, advising that he contacted Service Oklahoma and they insisted the barcode information is correct and has a copy of the output for verification.
I contacted Login.gov again on 6/10 to see if there is anything else that could be causing this issue.  Awaiting a response.
6/10 - Reached out to user again to see if any of the other suggestions were utilized.  Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
6/10 - Login.gov responded with more details of issue and provided guidance on how to upload images with better quality.
6/17 - Reached out to user with new information and guidance provided by Login.gov.  Awaiting response to see if that resolved his issue.

**Comment by Kimberley2023-CSM** [comment]
6/17 - Veteran responded advising that he has given up on Login.gov and used ID.me since their process is more user friendly.  Does not want to continue with trying to login with Login.gov.
