### ISSUE TITLE
Design Intent - IA Feedback - IIR, Veteran New Account Flow within Authenticated Experience, Welcome Pathway V1

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#83149]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [x] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Thanks for coming through the collab cycle!
- I love this idea, think it is really important, and look forward to seeing what y'all build.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] **Must: work with CAIA** and other teams including Profile and Authenticated Experience to integrate this welcome screen into My VA and find a permanent place for the page in the IA. Veterans should be able to find this screen again after seeing it for the first time.

- [ ] **Should: maintain user trust by always displaying the same screen on login** One thing we want to be sure to do is to give the Veteran the same, predictable experience every time they log in. I recommend sending Veterans to My VA as usual during their initial logon, rather than intercepting users with a separate page. On My VA, there could be a react widget, alert, or call to action to nudge them toward the welcome page. The other benefit of doing this is that it could show Veterans how to access the page again from within My VA if they want to find it again. 

- [ ] **Consider: Landscape of other benefits navigation tools and opportunities for differentiation** There are many different (mostly unauthenticated) tools that attempt to help Veterans understand what benefits are available - y'all have a great opportunity to improve upon this work with the authenticated experience! Some of the other tools that exist:
  - https://discover.va.gov
  - https://va.gov/reach
  - https://choose.va.gov/
  - https://www.va.gov/welcome-kit/
  - The VES transition experience team is working on an [unauth tool for benefits navigation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/80976) - not sure if it'd be helpful to reach out to them as well.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by emcruer** [comment]
**1. Must: work with CAIA and other teams including Profile and Authenticated Experience to integrate this welcome screen into My VA and find a permanent place for the page in the IA. Veterans should be able to find this screen again after seeing it for the first time.**
- We have worked with CAIA, Profile, My VA and the Auth Exp team to move the message onto My VA. Rather than a separate page, we have worked on a message that welcomes Veterans and encourages them to complete their Profile, an initiative that we worked on with the Profile team.

**2. Should: maintain user trust by always displaying the same screen on login One thing we want to be sure to do is to give the Veteran the same, predictable experience every time they log in. I recommend sending Veterans to My VA as usual during their initial logon, rather than intercepting users with a separate page. On My VA, there could be a react widget, alert, or call to action to nudge them toward the welcome page. The other benefit of doing this is that it could show Veterans how to access the page again from within My VA if they want to find it again.**
- The user will arrive at My VA, as per usual, but will see a different message depending on if the are LOA1/LOA3 (for example, for LOA3, we can address them by name and encourage actions within Profile).

**3. Consider: Landscape of other benefits navigation tools and opportunities for differentiation There are many different (mostly unauthenticated) tools that attempt to help Veterans understand what benefits are available - y'all have a great opportunity to improve upon this work with the authenticated experience! Some of the other tools that exist:**
https://discover.va.gov/
https://va.gov/reach
https://choose.va.gov/
https://www.va.gov/welcome-kit/
The VES transition experience team is working on an https://github.com/department-of-veterans-affairs/va.gov-team/issues/80976 - not sure if it'd be helpful to reach out to them as well.
- We have met with other teams, such as the VES transition team, to see where our work will intersect and have been able to link to some of their new resources for Veterans that are not LOA3 (we can provide the unauth resources to everyone, but the Profile completion is contingent upon LOA3 verification).

Closing this out and cc'ing @KKufalk13 for awareness!
