### ISSUE TITLE
consider swapping Jenkins back to LTS

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#8321]
## Description

Karl raised today in Slack that we are still running on the weekly builds of Jenkins. Even though we are moving off Jenkins, it may be worthwhile to swap because I think the switching cost is low and the benefit is we get hopefully smoother upgrades. https://dsva.slack.com/archives/CJYRZK2HH/p1587608411051200

Looks like we probably just change the `jenkins_repo_url` setting to the RedHat stable repo and away we go. https://pkg.jenkins.io/redhat-stable/

I'm putting this in as needs grooming because it needs a decision on whether or not we want to do this.

Note:  We don't want to downgrade.

## AC

- [ ] Jenkins is running the LTS version instead of weekly builds
- [ ] We want to make sure the LTS is not older than the current instance's weekly release

**Comment by tskinn** [comment]
After some discussion it was agreed to undo this effort. From our experience it seems that it is the Jenkins plugins that are the culprit for breakages. Since we have pinned the jenkins plugin versions we feel more comfortable using a newer version of Jenkins. Also some updated plugins required a newer Jenkins version. So it was eitehr use much much older plugins with the LTS Jenkins or use a decently new plugin version with newer Jenkins. This issue should be closed.

**Comment by dginther** [comment]
Closing issue on above commentary.
