### ISSUE TITLE
Analytics Reporting Request for Authenticated Experience: Mobile Discovery

### ISSUE THREAD

**Issue by srmyers17** [department-of-veterans-affairs/va.gov-team#8329]
# Metrics Reporting Request

## Description
Building on an earlier [request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6322) that was made for the Authentication team, we have a few questions about what we're seeing in GA and would like some clarification on three issues. 

Please see the initial request for context on team and project but note that our work is focused specifically on mobile and our discovery aims to understand user behavior on mobile VA today.

## Timeframe for Analytics Requested
Would be great to get some clarification before the end of next week.

## Analytics to Track Down
No specific analytics to track down rather we've started doing some analysis to understand mobile behavior with VA products and are running into a few issues in the data that we'd love some help with. 

**Issue 1 - Overview and All Pages within Behavior show totally different data** 

The total pageviews, rank order, and pageviews per URL are all different between Overview and All Pages, even though clicking "view full report" from Overview leads directly to the All Pages data

<img width="1429" alt="Issue 1" src="https://user-images.githubusercontent.com/58053619/80107455-b2a85980-8540-11ea-9d1d-2d654e849ded.png">

https://analytics.google.com/analytics/web/#/report/content-overview/a50123418w177519031p176188361/_u.date00=20190420&_u.date01=20200420&_.useg=builtin11/

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20190420&_u.date01=20200420&_.useg=builtin11&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10

**Issue 2 - filtering between Page and Page Title shows totally different data**

The "Primary Dimension" from Page to Page Title changes the rank order and numerical value of the pageviews. Why?

<img width="1438" alt="Issue 2" src="https://user-images.githubusercontent.com/58053619/80118195-b1c9f480-854d-11ea-919e-45c810626be7.png">

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20190420&_u.date01=20200420&_.useg=builtin11&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-segmentExplorer.segmentId=analytics.pagePath

**Issue 3 - changing the time period from 1 year to 1 year + 1 day shows significantly different data**

As you can see here, we changed the time period by only 1 day, but the rank order and value of pageviews totally changes. The difference of a day surely couldn't mean that the #2 most visited site changed from ebenefits (12M pageviews) to MHV (29M pageviews)?

<img width="1438" alt="Issue 3" src="https://user-images.githubusercontent.com/58053619/80118425-ff466180-854d-11ea-848e-c3a5d5158b25.png">

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20190420&_u.date01=20200421&_.useg=builtin11&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-segmentExplorer.segmentId=analytics.pagePath

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20190420&_u.date01=20200420&_.useg=builtin11&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=10&explorer-segmentExplorer.segmentId=analytics.pagePath

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
@srmyers17 Thanks! Acknowledging receipt!

**Comment by joanneesteban** [comment]
@jonwehausen @bsmartin-ep something to note is that it looks like eBen traffic stopped tracking as of 4/2/20, coinciding with the timing of https://github.com/department-of-veterans-affairs/va.gov-team/issues/6382. Not sure if it's related, but wanted to call it out.

**Comment by bsmartin-ep** [comment]
@joanneesteban -

It looks like the URL without a trailing slash dropped off, but overall numbers for Pages containing "ebenefits.va.gov" look pretty consistent.

https://analytics.google.com/analytics/web/#/report/content-pages/a50123418w177519031p176188361/_u.date00=20190420&_u.date01=20200420&_.useg=builtin11&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=250&explorer-table.filter=ebenefits.va.gov&explorer-table.rowStart=0&explorer-segmentExplorer.segmentId=analytics.pagePath/

**Comment by bsmartin-ep** [comment]
@srmyers17 - 

These three issues are all related to the [1,000,000 row limit](https://support.google.com/analytics/answer/1009671?hl=en) in daily processed tables in GA.

You can see in your linked reports that they are bumping against this limit:

![image](https://user-images.githubusercontent.com/62304138/80511185-c5100200-8949-11ea-9a92-ee8326c2d852.png)

<hr>

### Issue 1 - Overview and All Pages within Behavior show totally different data

This discrepancy is because the total in the _All Pages_ report is the total of the 999,991 rows in the report, while the _Overview_ is a **more accurate** total of every pageview recorded.

<hr>

### Issue 2 - filtering between Page and Page Title shows totally different data

In this case…

_Page URI_ as the primary dimension gives us > 1,000,000 rows, so we once again get a row limited total in the report.

_Page Title_ as the primary dimension gives 'only' 61,560 rows, so it's able to use all available data and we get a number closer to the _Overview_ total.

<hr>

### Issue 3 - changing the time period from 1 year to 1 year + 1 day shows significantly different data

In this case, we are seeing a discrepancy due to what Google decides should go in the (other) rollup row:

> The top value combinations are determined by sorting the table by the relevant metric (e.g., Sessions Pageviews, Transactions, etc.). Lower volume dimension value combinations are then aggregated into the (other) entry.↑

So… a bit of a black box.  Adding the extra day may have introduced enough new data to skew exactly what gets rolled up into _(other)_. Or one report may have been processed before the other.

Oddly enough, if you take the reports you linked up to 500 rows, things start to line up:

![image](https://user-images.githubusercontent.com/62304138/80511405-0d2f2480-894a-11ea-8890-5aa9d5faa8b8.png) | ![image](https://user-images.githubusercontent.com/62304138/80511434-161ff600-894a-11ea-859e-e4f23d7e5a35.png)

<hr>

## So how do we work around this?

- One option is to **export an Unsampled Report.** This requires usage of "tokens", but even the All Pages export would use less than 400 of our daily allotment of 12,500 tokens: <br> ![image](https://user-images.githubusercontent.com/62304138/80511554-3e0f5980-894a-11ea-8809-7aa55ab76369.png)
- **Reduce the timeframe** in your report to get total Page URIs under 1,000,000.  In the past, I've built Google Sheets / Excel queries to fetch report data month-by-month and merge the data together to avoid row limits.
- **Use a different view.**  All VA.gov Website Data includes all *.va.gov subdomains, including My HealtheVet, which is responsible for much of the high cardinality in Page URIs.  Would something like WBC - VA.gov Modernized Content, which includes only modernized VA.gov pages and forms, work for your purposes?
- **Move this data to BigQuery.**  While I think we still have some "soft" filtering we can do on our Page URIs like removing index.html and lowercasing URIs, ideally we would put any and all unique URIs into BigQuery and analyze them in there.

**Comment by srmyers17** [comment]
Thank you, @bsmartin-ep! These answers and tips are very helpful. I think we can limit our date range as suggested, so I'll start there.
