### ISSUE TITLE
dev UAT on main for pilot

### ISSUE THREAD

**Issue by schisslerg** [department-of-veterans-affairs/va.gov-team#83307]
# AC
-  [ ] Check to see if there are any missing features from develop that need to make their way into main prior to the pilot
-  [ ] if needed, move those features to main 
-  [ ] let Gus know once you're finished

**Comment by mateoclarke** [comment]
Just went through the `/intake` side and AFAIK, `main` branch is in a good state from a dev perspective. If we want to do any product UAT or any extra QA before pilot, it should be good to go!

_That said, here are a few comments or ideas we could add to the backlog or address as 1 pt enhancements (take for leave)..._


### 1. Display email address
Since we've added "Your email address" to the list of things to bring, we could display the email they used with the Login.gov assuming its available in the `userinfo` we're storing to the app's ephemeral context.

**Example 1: What to Bring (added a spot for email address to display in bold):**

![Screenshot 2024-05-16 at 11 50 56 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5697474/9939b906-e942-4ef2-8cdb-bb55ba305018)


**Example 2: Registration complete**

Same idea as the final page. Display their associated email alongside their newly assigned confirmation number

![Screenshot 2024-05-16 at 12 03 05 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5697474/4740ee3c-c891-4b07-9e64-c135e4ff201e)


### 2. Business days

We've updated from saying 10 days to 10 **business** days in most places across the intake app. One spot we missed is on the `/confirm-site` page

![Screenshot 2024-05-16 at 12 03 05 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/5697474/63fa8ff0-4925-4a1f-b473-ea502e8d525f)

**Comment by mateoclarke** [comment]
In `/proofing` there is a bug where after you click the "Sign in with PIV card" it automatically redirects you to the `/intake` app and you have to manually put in the right URL: `/proofing/case-number`. 

I think this bug has to do with downgrading our params when we hit the proxy-server from IAL 2 to 1. 

Here is the link on the button. http://localhost:9292/auth/request?aal=2-phishing_resistant&ial=1

The IAL 1 is the new part. Our proxy server's logic on where to send someone after logging in depends on whether we have access to their x509 data. [Here is a link](https://github.com/department-of-veterans-affairs/va-in-person-identity-proofing/blob/main/proxy-server/app.rb#L112-L120) to where this happens in the proxy server code. This is only available AFAIK if you use IAL 2 for login (which we stopped doing based on [Porta's recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81167))

From my perspective, we have two options:
1. Role back the change from IAL1 and go back to IAL 2 for the pilot. This would mean a proofing agent needs to verify their test Login.gov account which I created a [Loom video](https://www.loom.com/share/98995077b30d41db9ef4b2ce54a63ba4).
2. Figure out a new way to differentiate when a user is logging in as an intake user vs proofing agent. Not sure how exactly we'd do this without more triage and brainstorming.

**Comment by mateoclarke** [comment]
Other than the bug mentioned above (big caveat), the `/proofing` flow in `main` branch is in a good state from a development perspective and ready for further UAT/QA as needed. In our `develop` branch we added some error messaging and validations on inputs as part of the cATO remediations that we could deploy to `main` but there is nothing significant or requested from product/design missing in `main`
