### ISSUE TITLE
Sidekiq: Ensure jobs are idempotent and transactional

### ISSUE THREAD

**Issue by scottsdevelopment** [department-of-veterans-affairs/va.gov-team#83424]
- https://github.com/sidekiq/sidekiq/wiki/Best-Practices#2-make-your-job-idempotent-and-transactional

We should verify that the Pension Benefit Intake Job is transactional. Our current hypothesis is that it is, however we need to make sure that during failures or reruns, the state continues where it left off and that things such as "email" or "uploads" do not trigger again once they have been set. These kind of issues can occur depending on where in the job the code had failed and when running them again, there should be fail safes and checks to make sure that resuming the job occurs at the correct operations.

- Ensure that a job always completes without additional side effects, the same way when stopping and starting from various points of failure.

**Comment by TaiWilkin** [comment]
Within the Sidekiq job, we take several actions with an external impact. 
1. We create date-stamped versions of all submitted attachments and of the form. If the Sidekiq job fails at any point, these files are cleaned up, so no permanent changes are made.
2. We create a FormSubmission and a FormSubmissionAttempt. This is not removed if the job fails, but because we want these to track both failed and successful attempts, I believe this is the expected behavior. 
3. We upload the claim to Lighthouse. There's no way to 'undo' this step, and we don't have any checks in place to see if the claim has already been submitted, so this step could get run more than once if the job fails after this step. 
4. We send a confirmation email. There's no way to 'undo' this step, and we don't have any checks in place to see if the confirmation email was already sent, so this step could get run more than once if the job fails after this step. (It's unlikely the job will fail after this, since all we do afterwards is log the success, but in a worst-case scenario...)

*Recommendations*
1. Update Sidekiq job to check whether a copy of the claim has been successfully submitted to Lighthouse before attempting to submit the claim.
2. Update Sidekiq job to check whether a confirmation email has been sent for the claim before sending the confirmation email. 
@mjknight50
