### ISSUE TITLE
SPIKE: Troubleshooting SPA Tracking Issues

### ISSUE THREAD

**Issue by johnny-jesensky-adhoc** [department-of-veterans-affairs/va.gov-team#83583]
### Description
Jamie discovered a page view tracking issue that seems to affect products using a single-page application (SPA) structure -- pages load dynamically instead of an HTML page load. Specifically, it was noticed as she was working on funnel repots for secure messaging and claims status tracking. This has required some investigation on our part to understand what might be going on and how to fix it.

---

### Tasks

- [ ] Investigate cause of tracking issue impacting SPAs.
- [ ] Document findings in ticket.

---

### Findings/Next Steps
- UA and GA4 both use a GA4 for page tracking but UA does not have this issue. Digging into the trigger and property settings to see if the cause is the GTM implementation or a GA4 specific issue.

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc  It's hard to troubleshoot issues that don't appear when for you but I published a possible solution this evening -- version 518 -- that shifts the page_view event to the Enhanced Measurement event instead of the GTM tag event. 

I think it will take a full day's worth of data to confirm if it worked or not so I'll circle back Thursday morning.

**Comment by jestutt** [comment]
@johnny-jesensky-adhoc  Defaulting everything to GA4's Enhanced Measurement didn't work - made it worse. I'm going to go the other way completely turn off turn off the EM tracking, using only GTM like UA does. Will be published early afternoon .

**Comment by johnny-jesensky-adhoc** [comment]
@jestutt, given this one carried over, can you provide a quick update/summary on the latest on this? Did turning off EM tracking work?
