### ISSUE TITLE
Collect system id and care type on 'Facilities' Page for eligibility event

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#8366]
We have learned that a high percentage of users drop out of the scheduling funnel on the "Facilities" page.
We've also learned that approx. 16% of all users receive an 'facilities not supported' alert

**Goal:** Collect data about the specific system id and care type id to understand which facilities and which care types are not being supported. 

Acceptance criteria:
- collect the system id when user triggers vaos-eligibility-supported-facilities-failed event
- collect the 'care type selected' when user triggers vaos-eligibility-supported-facilities-failed event

**Comment by jonwehausen** [comment]
### Datalayer Requirements - @lenaecb 

- @lenaecb We have got the dataLayer prepared for you and your team below. One thing - this ticket is currently not showing on our board despite having the correct label (_I think it may be since this is currently Pipeline of VFT_)

Description of Interaction | Screenshot | dataLayer Example
------------ | -------------  | ------------- 
_When the user hits an ineligibility alert_ | ![image.png](https://images.zenhubusercontent.com/5d234c844828605fd8bf8ede/4f44e3b7-6596-45dd-a356-d2ed31cb5058)| `dataLayer.push({`<br>`'event': 'vaos-eligbility...'`<br>`'health-TypeOfCare': <dynamically_pass_in_type_of_care>`<br>`'health-FacilityID': <dynamically_pass_in_facility_id>'`<br>`});`

**Comment by lenaecb** [comment]
Thanks @jonwehausen. And yes, we are in VFT. Should we not be? I feel like our analytics work has showed before in y'alls board... very weird

**Comment by jonwehausen** [comment]
Confirming able to see on our board now. Thanks

**Comment by jbalboni** [comment]
To clarify here: when this event happens, we don't have a facility or clinic id. The user chooses that in the question that comes after the parent/system choice, but when this event happens, it means they didn't get to that second question. The id we have is a parent/system id, which is the VistA site (or parent CBOC) a user is registered in. It's kind of a nuanced distinction, but I believe we want the parent id in the event data, since that's the most specific facility information we have when this event happens.

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Our GTM workspace for this:  https://tagmanager.google.com/#/container/accounts/144676348/containers/2214120/workspaces/1000281

I created the _DL - VAOS FacilityID_ variable and added it to the _VAOS - Form Events_ tag.  I haven't added the new CD to GA yet.

**Comment by lenaecb** [comment]
@jonwehausen @bsmartin-ep - how's this looking on your end?

**Comment by lenaecb** [comment]
@jonwehausen @bsmartin-ep - wanted to check in on this. How is this looking on your end?

**Comment by jonwehausen** [comment]
Thanks Lenae! Apology for the delayed response -- Looks like we're still needing to see the Facility ID and type of care being pushed to the dataLayer [per this comment. ](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8366#issuecomment-623651554). 

Once we get in staging, we should be able to get tested / deployed / closed out relatively quickly.

**Comment by lenaecb** [comment]
@jonwehausen - ok, _now_ we should be good to go :)

**Comment by jonwehausen** [comment]
@lenaecb Correct now we're ready to move forward with the dataLayer.

**Comment by lenaecb** [comment]
@jonwehausen - awesome, thanks! let me know when we're ready to start these ids populate in GA

**Comment by bsmartin-ep** [comment]
@jonwehausen -

Interaction | Data Layer | Tag | Result
--- | --- | --- | ---
_When the user hits an ineligibility alert_ | ![image](https://user-images.githubusercontent.com/62304138/82944469-44a0e900-9f69-11ea-92ee-92c92ba0de61.png) | <h4>VAOS - Form Events </h4> ![image](https://user-images.githubusercontent.com/62304138/82944590-7ca82c00-9f69-11ea-822b-bd94e9a7070b.png) | :heavy_check_mark: **PASS**

It looks like we are clearing out these CDs on subsequent _vaos-_ events as expected.

![image](https://user-images.githubusercontent.com/62304138/82944957-1cfe5080-9f6a-11ea-9a80-49f057838987.png)

**Comment by jonwehausen** [comment]
@bsmartin-ep Thanks for your testing here. Replicated your testing above on my end and have published out. 

![image](https://user-images.githubusercontent.com/48527022/83043067-65704980-a010-11ea-8b86-efcd09199d8d.png)
 
@lenaecb we will begin collecting facility IDs and type of care with ineligibility events this point forward. 🎆 Closing!
