### ISSUE TITLE
Create updated documentation for Profile error codes

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#8372]
## Background 
See ticket [Users are not able to update their address on VA.gov Profile #6012](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6012)

We need updated documentation related to Profile Error codes
[Error codes](https://github.com/department-of-veterans-affairs/vets-website/blob/655fca74b24378320141777a409dc351f72a3bb6/src/platform/user/profile/vet360/util/transactions.js#L19-L37)

## Tasks
- [x] obtain updated error codes from VA Profile team
- [x] create updated documentation in Github

**Comment by Samara-Strauss** [comment]
Please create a document in [the profile folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/identity-personalization/profile) the documents these errors. Spreadsheet format would be ideal.

**Comment by mshea0606** [comment]
@Samara-Strauss I've added the excel doc to the profile folder.

**Comment by Samara-Strauss** [comment]
Can I ask a favor? Instead of uploading the spreadsheet, can you create a spreadsheet in a Github document? For small/not super complex spreadsheets, this makes it so much easier to view and update the content without everyone having to download the excel file. Idk if you know how to do a spreadsheet in markdown, but in case not, this is the format. You can edit this comment to see the markdown:

| Column title | Column title | 
|-----|------|
| Row contents | Row contents |

**Comment by Samara-Strauss** [comment]
Also thank you for tracking down this information!!

**Comment by mshea0606** [comment]
@Samara-Strauss no problem! Changed this to a github markdown table.

**Comment by Samara-Strauss** [comment]
Looks great! Thank you!
