### ISSUE TITLE
Forms detail page - content model design

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-team#8389]
**Acceptance Criteria**
- [ ] The form detail page content model has been approved by the websites team
- [ ] The VA Forms content model, including content type and related taxonomies and views, has been approved by the CMS team.
- [ ] The VA Forms content model has been approved by the Lighthouse team.

**Implementation**
- [x] Document content model design
- [x] Prototype design
- Submit design for approval to:
   - [x] Websites team members
   - [x] CMS team representative
   - [x] Lighthouse API representative

**Comment by beeyayjay** [comment]
VA Form field listing: https://airtable.com/shrhOeUjiqNrWfXYs
CMS content mapped to website content: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-va-forms-redesign/form-detail-landing-pages/WIP-technical-specs-and-docs/va-forms-cms-content-model.pdf

**Comment by beeyayjay** [comment]
Outstanding issue:
Determine whether 'Related to' categories can be aligned with other categorization schemes within the CMS. (Meeting scheduled w/ @kevwalsh to resolve this)

**Comment by stephorkandatx** [comment]
@beeyayjay were you able to meet with @kevwalsh to resolve the outstanding issue? 
Is this ticket ready to validate and close?

**Comment by beeyayjay** [comment]
Meeting resulted in resolution of categorization issue. Updated whimsical to reflect decision: https://whimsical.com/6BS5uYwmWgF7YMBQ9tDz5F

Submitted pr to update pdf in github.

**Comment by beeyayjay** [comment]
PR: https://github.com/department-of-veterans-affairs/va.gov-team/pull/8816

**Comment by jenniferlee-dsva** [comment]
Per PR comment @beeyayjay - I'm uploading your PDF with annotations here. LMK if a call would be helpful. Also - for your purposes, instead of the outdated mockups, could you diagram/map to copydeck?   If updated mockups are needed, this task may be blocked until I get a ticket to get designer to update mockups with latest iterations. 

[va-forms-cms-content-model-jl-may6-2020.pdf](https://github.com/department-of-veterans-affairs/va.gov-team/files/4589466/va-forms-cms-content-model-jl-may6-2020.pdf)

**Comment by stephorkandatx** [comment]
Closing this, has been reviewed
