### ISSUE TITLE
Forms detail page - migration plan

### ISSUE THREAD

**Issue by beeyayjay** [department-of-veterans-affairs/va.gov-team#8390]
**Acceptance Criteria**
- [x] A detailed migration plan has been documented
- The plan has been reviewed and approved by:
  - [x]  cms team
  - [x] Websites team
  - [ ] Spotlight api team.

** Implementation **
Plan will include:
- [x] Field mapping
- All required content manipulation defined
  - [x] Generate node title (e.g. VA Form 10-10EZ)
  - [x] Generate form filed URL
  - [ ] ~Modify 'Owner'?~
- [x] Strategy for integrating nightly migrations into cron (coordinate w/ cms team)

**Comment by stephorkandatx** [comment]
Note: we have a dependency on the lighthouse team, to complete this

**Comment by beeyayjay** [comment]
## Foundational migration
- Fields to migrate:
  - Page title (= "VA Form" + Form title)
  - Form title
  - Form number
  - Form administration
  - Issue date
  - Revision date
  - Number of pages
  - Link to form*

*When there is only a file name, the full URL for Link to form will be generated using the pattern outlined by @jenniferlee-dsva in Slack:
```
According to Kevin Reid:
IF the form owner ID is VA, URL_prefix= https://www.va.gov/vaforms/va/pdf/ + FileName value from spreadsheet – like this: https://www.va.gov/vaforms/va/pdf/VA40-10088.pdf
IF VBA, URL_prefix= http://www.vba.va.gov/pubs/forms/ + FileName value from spreadsheet
IF VHA, URL_prefix= https://www.va.gov/vaforms/medical/pdf/ + FileName value from spreadsheet – like this: https://www.va.gov/vaforms/medical/pdf/10-10EZ-fillable.pdf
```

- Nightly migrations will be implemented using the process developed for the Vet Center facility status migration.

Once the foundational migration is active, the Lighthouse team can start planning and testing the queries they will use to retrieve forms data from the CMS.

## Handling deleted forms
- Forms that are deleted from the Forms DB will be unpublished in the CMS.
- Implementation TBD - Kevin Reid will let us know whether they'll be able to generate an 'archive' table to help determine which forms have actually been deleted. The implementation depends on his answer.

## Notification when new forms are migrated
- PW should be notified when new forms have been added so they can add additional content (help text, etc)
- Implementation TBD

**Comment by jenniferlee-dsva** [comment]
@beeyayjay - Q for ^ foundational list of data fields: 

1. Why does the API need the # of pages? (Since we don't use or display this data at all.) 

2. When you say ^ "when only a file name is available," which data field does that correspond to on your list of fields to migrate? 

- ( In the forms database, there is a "FileName" data field, but it corresponds to the actual form PDF file name, and not to the form title or form number (although both of these things might be part of the PDF file name.) The database "FileName" value looks like this usually: VBA-26-8736a-ARE.pdf  or like this vha-10-0491e-fill.pdf )
