### ISSUE TITLE
Design Intent - Design Feedback - Transition Experience, tbd, V1 Transition Experience

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#83947]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Review Ryan Thurlwell's comment
- I see you are using a color other than gray for the [tags](https://design.va.gov/components/tag). Reach out to Matt Dingee on the #platform-design-system Slack channel and ask if using those colors for the tags needs to go thru experimental design.
- Check the content style guide and with CAIA about italics. I do not believe we use italics on VA.gov.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [ ] Per our [guidance on action links](https://design.va.gov/components/link/action#usage), use only one primary (green) Action link per page. Review the guidance and then pick if there is 1 action that is the primary focus. You can also use an [active link style](https://design.va.gov/components/link/#active) to create hierarchy. 
- [ ] We do have a pattern for a [review page for a form](https://design.va.gov/templates/forms/review). I realize your product is slightly different. Forms team is working on a new review page pattern that may fit better. If neither of those work, fill out an experimental design request.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by rtwell** [comment]
Here are my initial thoughts/questions

1. There are other websites about benefits which serve as entry points and that VA owns or are VA-adjacent (eg choose VA, eBenefits). How is this different? right now VA.gov is barely in the top 5 search results. Is this supposed to replace those other pages/sites?
2. I understand we want to make it easy for people to figure out what they might be eligible for (hence the rationale for unauth UX), however there are some pretty huge benefits to making this an authenticated UX. A) I can save my results instead of having to fill this out all over again if I leave (assuming I miss or don't use the share results link), B) we can prepopulate a lot of this information if they are known to VA to make a shorter form or maybe not need a form at all, C) almost every benefit has to be accessed behind the authentication wall anyway, so we're kinda just delaying the inevitable. it _almost_ feels like these questions might be part of the create account flow…? and finally D) won't users have to dig into each benefit anyway because we cannot say with absolute certainty that they ARE eligible? So like…here's a bunch of stuff you _might_ be able to get, but you're still going to do the heavy lifting and figure out if you can actually get the benefit…kinda feels misleading to me. I guess the real question I'm asking is: what is this tool doing that a google search or a phone call to VA isn't already doing?
3. Just to reiterate feedback from the collab call on the 24th: [we are mobile first.](https://design.va.gov/about/principles)
4. are there enough search results to warrant 3 tiers of filtering and sorting? will there be pagination? 
5. Some of the results said "available in 60 days" but there was a "Apply now" action link. this is confusing. Will we offer some kind of email reminder to check back?
6. I would like to +1 @briandeconinck's feedback from the meeting last week.
7. How do we plan on measuring the efficacy of this tool?

**Comment by nkontrabecki** [comment]
In response to: “We do have a pattern for a [review page for a form](https://design.va.gov/templates/forms/review). I realize your product is slightly different. Forms team is working on a new review page pattern that may fit better. If neither of those work, fill out an experimental design request.”

1. The team will be using the existing review page pattern that is referenced. 
2. The team plans to submit an experimental design request in the future for an inline review component. 
3. For V1, the team will make the review page a separate page, using the existing review pattern.

@cora-goldston-bah @iseabock  @iseabock-va @YevgenyDreyband @vetskrieg

**Comment by nkontrabecki** [comment]
Closed per above comments.
