### ISSUE TITLE
Wizards documentation on design.va.gov

### ISSUE THREAD

**Issue by jaredcunha-usds** [department-of-veterans-affairs/va.gov-team#84]
How is it different from a form?

I don't have any other notes on wizards

You may submit your write-up as a comment on this issue. Happy to help if you have any questions.

**Comment by lalexanderson-dsva** [comment]
*Use Case*
Sometimes, a VA benefit or resource is so complex that it has multiple access pathways, depending on a user's specific needs or circumstances. Users may experience consequences (e.g. not getting the benefit or limiting benefit options), if they misunderstand eligibility content or choose the wrong pathway. VA.gov uses a wizard pattern to guide users down an optimal pathway for their circumstances. 

*What is a wizard*
The wizard typically consists of a series of simple questions, written in plain language, to glean a user's specific eligibility status, background, or specific needs/goals. Wizards serve up one question at a time. Wizards use conditional logic, whereby the answer to the first question determines the next question to be asked, or answer options that should be made available. 

*Examples of wizards used correctly on VA.gov*
- [Find your benefits education form](https://www.va.gov/education/eligibility/)
- [How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/)
- [How to apply for a discharge upgrade](https://www.va.gov/discharge-upgrade-instructions) 

*Where to place wizards*
- If your goal is to help users to find the correct application or process for their circumstances (i.e. Education), the wizard will live on both the **Eligibility** and **How to Apply** sections of an application. 
- If your goal is to help Veterans find the correct process (i.e. Discharge Wizard), your wizard should live on a content landing page that explains the process. 

*Specifics of the pattern*
- A wizard is launched typically through a primary button (green).
- Questions appear 1 at a time under the button, using the expanding blue vertical left bar (see Information Alert) as new questions are added. 
- If a user makes a selection that will require them to stop what they are doing and follow a different process (e.g. How to file a disability claim), show the Error Alert and provide concrete next steps and directions. 

*Research/Accessibility rationale*
- We show questions one at a time for accessibility/universal design reasons: we try not to show irrelevant content to users. 
- We learned through research to add blue left bar to show users that the wizard questions are related and part of the same process of finding the correct form. 
- Wizard questions may come from user research, i.e. a point of confusion for many users regarding their eligibility for a VA benefit.

**Comment by lalexanderson-dsva** [comment]
Screenshots show a good wizard. 

1. 
<img width="723" alt="Screen Shot 2019-05-14 at 3 05 03 PM" src="https://user-images.githubusercontent.com/32132681/57727301-21a5de80-765f-11e9-8d1c-49efc45e1ab6.png">

2. <img width="691" alt="Screen Shot 2019-05-14 at 3 05 10 PM" src="https://user-images.githubusercontent.com/32132681/57727300-21a5de80-765f-11e9-9c80-2f79074a7bee.png">

3. <img width="691" alt="Screen Shot 2019-05-14 at 3 05 10 PM" src="https://user-images.githubusercontent.com/32132681/57727300-21a5de80-765f-11e9-9c80-2f79074a7bee.png">

4. <img width="686" alt="Screen Shot 2019-05-14 at 3 05 21 PM" src="https://user-images.githubusercontent.com/32132681/57727299-21a5de80-765f-11e9-9a31-3713fde1087b.png">

5. <img width="703" alt="Screen Shot 2019-05-14 at 3 05 44 PM" src="https://user-images.githubusercontent.com/32132681/57727298-21a5de80-765f-11e9-970c-42c59c39f3d5.png">

**Comment by jaredcunha-usds** [comment]
Yay! First documentation submitted! 

I'm wondering if we also want to address some of these questions in the documentation:
1. Does a wizard submit data? Assuming no, but we might want to be explicit so that teams don't build wizards that submit stuff
2. If a user does not meet the eligibility criteria, does it to try to deny the user access to the benefit application?
3. As far as linking to the examples, any concern about people being able to find them on the page? We, unfortunately, cannot deep link. 
4. Can we not include the 3rd example. Its behavior is different from the other examples in that it:
    - Removes the content that was originally on the page
    - Changes the URL
    - Does not use the blue bar 
    - Uses a different color button to launch
    - Button has a different icon 
5. This sort of feels like a weird pattern to me. Is there any appetite for iterating on it? If so, do we indicate that here? Or do we have a blurb about how to go about updating patterns on the overview page?
6. I've seen warning alerts too… not sure if there are any informational or success type alerts out there. Should we have more info about when/how different types?
7. I may reach out to devs if they think any dev guidance might be helpful. I'd want this to be short, but just maybe something that would be helpful for front-end teams how may need to implement a new one.
8. Why do questions appear one at a time? Are they conditional based on previous answers?
9. Just an idea. What are your thoughts on capturing the screenshots as an animated .gif?
10. Under the use case, should we change "user" to "Veteran?" Is the user always a Veteran? If not, maybe just leave as user.
11. Why does the green button turn blue when I click it?

@rtwell - Do you have any thoughts on any of this?

**Comment by lalexanderson-dsva** [comment]
All good questions @jaredcunha-usds ! 

> 1. Does a wizard submit data? Assuming no, but we might want to be explicit so that teams don't build wizards that submit stuff? 
I actually don't know the answer to this. @jbalboni might though.

> 2. If a user does not meet the eligibility criteria, does it to try to deny the user access to the benefit application?
I think this is really context dependent. Theoretically, we want to make the BEST thing they can do the EASIEST thing to do. So, if we hypothesize that they are ineligible based on how they answered the wizard questions, we should be making the easiest next step to do the next best thing that they can do. For disability, it is usually going to EBN for now. If they disagree with the outcome, the best thing may be to call a number. That said, I think we always still offer a pathway into a form, even if it is not the most obvious next step, because there's always that edge case. 

> 3. As far as linking to the examples, any concern about people being able to find them on the page? We, unfortunately, cannot deep link. 
May need to tell people to scroll? If someone is brand new to Formation, they may not know to scroll to find the wizard. 

> 4. Can we not include the 3rd example. Its behavior is different from the other examples in that it: Removes the content that was originally on the page, Changes the URL, Does not use the blue bar, Uses a different color button to launch, Button has a different icon
Honestly, I think it's important. If we need to make it clearer how it could be different OR call it a different thing, fine.

> 5. This sort of feels like a weird pattern to me. Is there any appetite for iterating on it? If so, do we indicate that here? Or do we have a blurb about how to go about updating patterns on the overview page?
Are you saying wizards in general are a weird pattern? There's of course always room for iterating if there's a better way to do this. Right now, wizards solve a problem in that we don't have great ways to handle super complex user pathways, and user research has suggested that these wizards help. 

> 6. I've seen warning alerts too… not sure if there are any informational or success type alerts out there. Should we have more info about when/how different types?
Don't understand this question. 

> 7. I may reach out to devs if they think any dev guidance might be helpful. I'd want this to be short, but just maybe something that would be helpful for front-end teams how may need to implement a new one.
YES. 

> 8. Why do questions appear one at a time? Are they conditional based on previous answers?
Because we do not want to show Veterans questions that are irrelevant. Yes, they're conditional based on previous answers. 

> 9. Just an idea. What are your thoughts on capturing the screenshots as an animated .gif?
i'm open to whatever works best in design.va.gov that anyone can use. @1Copenut may be able to add in here. 

> 10. Under the use case, should we change "user" to "Veteran?" Is the user always a Veteran? If not, maybe just leave as user.
Not necessarily. 

> 11. Why does the green button turn blue when I click it?
No clue. @goldenmeanie may have more context.

**Comment by jbalboni** [comment]
@lalexanderson-dsva I don't _think_ we ever submit data after a wizard. I haven't seen that. Though I think for the discharge wizard application, if we could submit something, we would. But that's not exactly the pattern we're talking about here, even though it's called a wizard.

**Comment by goldenmeanie** [comment]
All good questions @jaredcunha-usds ! 

> 1. Does a wizard submit data? Assuming no, but we might want to be explicit so that teams don't build wizards that submit stuff? 

@lalexanderson-dsva: I actually don't know the answer to this. @jbalboni might though.

@jbalboni: [see above](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84#issuecomment-493988167).

@goldenmeanie: I think we should continue to think about this. The chief obstacle (unless they are signed in) is "save it where?" The main scenario this comes up is: We have no idea what path people may take to these forms, they may travel through the wizard having pages, or follow a direct link from a forum somewhere to the first page of the form. The direct link possibility has led us to put more wizard structure _in_ the form as a safety measure. But this means that people who travel through the wizard having pages may be asked the same questions twice. Being able to save wizard answers locally and use them to skip in-form wizard content when present is attractive. But we have not thought through all the complexities.

> 2. If a user does not meet the eligibility criteria, does it to try to deny the user access to the benefit application?

@lalexanderson-dsva: I think this is really context dependent. Theoretically, we want to make the BEST thing they can do the EASIEST thing to do. So, if we hypothesize that they are ineligible based on how they answered the wizard questions, we should be making the easiest next step to do the next best thing that they can do. For disability, it is usually going to EBN for now. If they disagree with the outcome, the best thing may be to call a number. That said, I think we always still offer a pathway into a form, even if it is not the most obvious next step, because there's always that edge case. 

@goldenmeanie: Agree! I think there is a distinction between a wizard helping you understand eligibility for a single thing (let them start anyway) and a situation where we are helping you choose between two or more things. In that case the instructions might be more like "please call this number to get help." We might also direct them to content pages that further explain the situation in a less interactive/conditional format.

> 3. As far as linking to the examples, any concern about people being able to find them on the page? We, unfortunately, cannot deep link. 

@lalexanderson-dsva: May need to tell people to scroll? If someone is brand new to Formation, they may not know to scroll to find the wizard. 

@goldenmeanie: I don't understand the context here.

> 4. Can we not include the 3rd example. Its behavior is different from the other examples in that it: Removes the content that was originally on the page, Changes the URL, Does not use the blue bar, Uses a different color button to launch, Button has a different icon

@lalexanderson-dsva: Honestly, I think it's important. If we need to make it clearer how it could be different OR call it a different thing, fine.

> 5. This sort of feels like a weird pattern to me. Is there any appetite for iterating on it? If so, do we indicate that here? Or do we have a blurb about how to go about updating patterns on the overview page?

@lalexanderson-dsva: Are you saying wizards in general are a weird pattern? There's of course always room for iterating if there's a better way to do this. Right now, wizards solve a problem in that we don't have great ways to handle super complex user pathways, and user research has suggested that these wizards help. 

> 6. I've seen warning alerts too… not sure if there are any informational or success type alerts out there. Should we have more info about when/how different types?

@lalexanderson-dsva: Don't understand this question. 

> 7. I may reach out to devs if they think any dev guidance might be helpful. I'd want this to be short, but just maybe something that would be helpful for front-end teams how may need to implement a new one.

@lalexanderson-dsva: YES. 

> 8. Why do questions appear one at a time? Are they conditional based on previous answers?

@lalexanderson-dsva: Because we do not want to show Veterans questions that are irrelevant. Yes, they're conditional based on previous answers. 

> 9. Just an idea. What are your thoughts on capturing the screenshots as an animated .gif?

@lalexanderson-dsva: i'm open to whatever works best in design.va.gov that anyone can use. @1Copenut may be able to add in here. 

@goldenmeanie: I think animated GIF would be a nice add here. This is one of a few places on VA.gov where we use animation. We should think about how to best document things like pace, easing settings, etc. I think it might be baked into the CSS right now, but surfacing it would be helpful for consistency as we (carefully) expand animation as a signifier in our designs. I think @smoonpeyes might have some thoughts on this?

> 10. Under the use case, should we change "user" to "Veteran?" Is the user always a Veteran? If not, maybe just leave as user.

@lalexanderson-dsva: Not necessarily. 

@goldenmeanie: Agreed. As we accommodate more family members, caretakers, etc. on VA.gov this description gets more complicated.

> 11. Why does the green button turn blue when I click it?

@lalexanderson-dsva: No clue. @goldenmeanie may have more context. 

@goldenmeanie: Green button is most important CTA. Wizards eventually provide you with a _really_ most important CTA at the end. Transition from green to blue is intended to set that hierarchy correctly when the sequence is complete, instead of having two competing green buttons.

**Comment by jaredcunha-usds** [comment]
Thank you, @goldenmeanie!

@lalexanderson-dsva - Would you want to work some of these responses into your documentation? I think this additional info would be really helpful for folks. 

---

> I've seen warning alerts too… not sure if there are any informational or success type alerts out there. Should we have more info about when/how different types?

@lalexanderson-dsva: Don't understand this question.

I had noticed an example that showed a warning alert:
https://www.va.gov/disability/how-to-file-claim/
<img width="759" alt="Screen Shot 2019-05-22 at 12 34 46 PM" src="https://user-images.githubusercontent.com/25435289/58192242-46690a00-7c8e-11e9-860a-4cf93c406aa7.png">

So where you have: 
- _If a user makes a selection that will require them to stop what they are doing and follow a different process (e.g. How to file a disability claim), show the Error Alert and provide concrete next steps and directions._

Maybe add an additional bullet point?
- If a user makes a selection that will ________________________________________, show a Warning Alert and __________________________________


---

The last question I have is circling back to linking out to examples. If we are providing images of the pattern in use, do we really need to link to other examples? I thought it might be a little tedious that for each example, we have something like:

- [Find your benefits education form}(https://www.va.gov/education/eligibility/) - Scroll the bottom of the page, and under the heading "How do I apply?", click the green button to open the wizard.

Can you clarify why it's important if it doesn't align with the documentation? I think it might be confusing for designers reading documentation about how something should be designed, and then pointing them to an example of something that is not designed that way. But I guess that's also another reason why I felt a little hesitant about linking out real world examples.

**Comment by rtwell** [comment]
@jaredcunha-usds makes a good point about linking out to specific, live examples. It's tough b/c it's _so great_ to see a living version of the pattern we're talking about, but if we got a little sloppy with our implementation of it…that's less than ideal. I think excluding those "wrong" anomalies (the bad examples) and only referring to the "right" instances at least steers folks in the right direction.

**Comment by lalexanderson-dsva** [comment]
*Use Case*
Sometimes, the eligibility for a VA benefit or resource is so complex that it has multiple access pathways, depending on a user's specific needs or circumstances. Users may experience consequences (e.g. not getting the benefit or limiting benefit options), if they misunderstand eligibility content or choose the wrong pathway. VA.gov uses a wizard pattern to guide users down an optimal pathway for their circumstances. 

*Wizard pattern, defined*
- The VA.gov wizard pattern consists of a series of simple questions, written in plain language, used to glean a user's specific eligibility status, background, or specific needs/goals. 
- Wizards serve up one question at a time. 
- Wizards use conditional logic, whereby the answer to the first question determines the next question to be asked, or answer options that should be made available. 
- Wizards do not submit or store data. 

*Examples of wizards used correctly on VA.gov* (You may need to scroll down to find the wizard.)

[Input animated gif from Ryan here]

- **Education Wizard: **[Find your benefits education form](<https://www.va.gov/education/how-to-apply/>). This wizard is used to help guide users to the correct education benefits form. 

- **VA Disability Claim**: [How to file a VA disability claim](https://www.va.gov/disability/how-to-file-claim/) This wizard is used to ensure that the right users are entering the disability claim application process at the right place. Some users, such as active duty service members, need to complete a different form on Benefits. Other users may need to complete an intent to file form before they can start the form on VA.gov. This wizard tries to divert users to the correct place. 

- **Apply for service discharge upgrade**:  [How to apply for a discharge upgrade](https://www.va.gov/discharge-upgrade-instructions). Applying for a service discharge upgrade is a relatively new and very complex process. Depending on a user's specific set of circumstances, they may need to complete different forms and send them to different places. This wizard is meant to collect information about those specific circumstances to give users the best available guidance of what they can do next. There are over 100 different combinations from the wizard that can yield different results, so it does not make sense to do a simple content page to explain eligibility.

  This tool was developed prior to Formation, so some of the patterns are not in alignment with other wizards. For example, the wizard starts at a new URL, does not use the blue sidebar, etc. However, this can be used as an example for similar use cases, where a very complex set of characteristics or circumstances may determine a user's next step. 

*Where to place wizards*
- The wizard should live *on the page* on both the **Eligibility** and **How to Apply** pages for an application. The wizards begin under blue [information callout](<https://design.va.gov/patterns/content-presentation#information-callouts>) eligibility boxes but before [accordions](<https://design.va.gov/patterns/content-presentation#accordions>) or additional information.

*Specifics of the pattern*

- **Green "Start" Button**: A wizard is launched through a primary button (green), with a clear label about what the wizard will help the user do, for example "Find your education benefits form".  A wizard may also END with a call-to-action, for example, "Apply now"; this button kicks off the next step, given the details that the user provided in the wizard. To distinguish between the call-to-action that starts the wizard and the call-to-action that takes the user to their next step and to set the hierarchy correctly when the sequence is complete, the first button changes from green to blue once clicked, and the final button becomes the green, primary call-to-action. 

- **Questions**: Questions appear 1 at a time under the button, using the expanding blue vertical left bar (see Information Alert) as new questions are added. Questions are conditional, based on previous answers. Structure the logic tree for wizard questions to get users to gather information from users in as few questions as possible, while still directing them to the best next step for their circumstances. 

- **Warning alerts in the wizard.** Show a [warning alert](<https://design.va.gov/components/alertboxes#warning-alert>) if a user answers a question in a way that is uncommon, or if they need to first do some other process that cannot be accessed via the wizard. For example, in the Education Form wizard, Show the Warning Alert immediately after the question, and provide concrete next steps and directions.  
- 	ADD IN RYAN's GIF

- **Error alerts in the wizard**. Show an [error alert](<https://design.va.gov/components/alertboxes#error-alert>) if a user answers a question in a way that would render them ineligible to complete any of the forms serviced by the wizard. Instead, they may need to stop what they are doing and follow a different process on a different page or website. For example, in the Disability Claim wizard (shown below), a user who is still active duty needs to complete a completely different form on EBenefits, and completing an application on VA.gov would be a waste of time. Show the Error Alert immediately after the question, and provide concrete next steps and directions. 

  <img width="779" alt="Screen Shot 2019-05-14 at 3 40 00 PM" src="https://user-images.githubusercontent.com/32132681/57727297-21a5de80-765f-11e9-811a-e8f564ab0ebb.png">

- **Editable answers**: Users can scroll up to see all of their previous answers and make changes at any time. If a user makes a change to the answer to an earlier question, hide all previous answers and show only the next appropriate question in the series, based on the user's answer. 

Note: For both alert cases, a user can still change their answer in the wizard to access and complete the form. We do not block users from accessing a form completely based on their answers to the wizard questions because there is always an edge case. Theoretically, we want to make the BEST thing they can do the EASIEST thing to do, based on the information the user has provided. So, if we hypothesize that they are ineligible based on how they answered the wizard questions, we should be making the easiest next step to do the next best thing that they can do. 

ADD RYAN GIF here

*Research/Accessibility rationale*

- We show questions one at a time for accessibility/universal design reasons: we try not to show irrelevant content to users. 
- We learned through research to add blue left bar to show users that the wizard questions are related and part of the same process of finding the correct form. 
- Wizard questions may come from user research, i.e. a point of confusion for many users regarding their eligibility for a VA benefit.

**Comment by jaredcunha-usds** [comment]
@lalexanderson-dsva this looks really nice. I'm going to move this into a draft page. @rtwell Wanna just update this with PRs on the draft as we did for your other page?

**Comment by jaredcunha-usds** [comment]
Here's the link to the draft page on design.va.gov
https://dev-design.va.gov/patterns/wizards

**Comment by andaleliz** [comment]
Hi @lalexanderson-dsva - I know this is an old issue, but I'm working on https://github.com/department-of-veterans-affairs/va.gov-team/issues/6315 and am curious about a couple of things.

Above, you said:
> user research has suggested that these wizards help.

Are there any specific studies you can point me to?

Second, the guidance states:
> The wizard should live on the page on both the Eligibility and How to Apply pages for an application. The wizards begin under blue information callout eligibility boxes but before accordions or additional information.

Can you share any more info on why it was decided that the wizards should go on the content pages, rather than on the tool/application landing page itself, or follow a format similar to the discharge upgrade where the wizard is on it's own page? 

Thanks in advance for any info you can provide.  And, if I need to direct this to someone else, let me know.

**Comment by lalexanderson-dsva** [comment]
@andaleliz - A guide to most of the past research lives in the [research history](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/research/research-history.md). Researchers are supposed to update it when they're done with a study, but often forget, so I recognize its out of date. Working with @LEHigley and @LizCallaghan to do a better job of keeping it up to date. I would recommend looking at old research for some of those applications. 

One reason it goes on both pp. is because of SEO. Both of those pages (eligibility) and (how to apply) tend to pop up in search engine results. 

Another reason is that in some cases we may want to route you to a different form altogether and into a different application process.

**Comment by andaleliz** [comment]
Thanks @lalexanderson-dsva; I had taken a look at that research history folder but there are tons that come up when I search for `disability` or `education`, so wasn't sure if you were referring to a specific study when you made those comments.  Will dig in deeper there.

And, thanks for sharing that background info on why it goes on both pages and not on the form applications themselves. Very helpful to know. If you think of anything else that should be on my radar, don't hold back! :)

**Comment by lalexanderson-dsva** [comment]
@andaleliz - I unfortunately don't remember the specific studies for each that informed the creation of the wizards. @goldenmeanie worked on both of these applications as well.

**Comment by goldenmeanie** [comment]
I would look specifically at the Education and Comp studies. I don;t recall if we did any that were specifically boxed tot he wizard pattern. I kind of suspect it was mixed into other usability sessions. I'm happy to find some time to look at them, or just chat about wizards with you @andaleliz

**Comment by andaleliz** [comment]
@goldenmeanie thanks, grabbed some time to talk tomorrow. What do you mean by 
> comp studies
Comparison tool is what is coming up when I `cmd + f` comp...

**Comment by goldenmeanie** [comment]
Disability **Comp**ensation. Sorry for the jargon!
