### ISSUE TITLE
[Discovery] How will Claim Contextualization UI updates impact other claims?

### ISSUE THREAD

**Issue by skylerschain** [department-of-veterans-affairs/va.gov-team#84173]
## Background

There are many different claim types that exist in CST: [Full list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/product-guide/appeals-type-list).

The current understanding is that the same UI is used for all claim types. So updating it for disability compensation claims (what we are working on now as part of Claim Contextualization) will update it for all.

We need to determine: 
- Will updating the UI for disability compensation claims update it for all claims? (Assuming yes)
- What will other claim types look like when we update the Overview tab?

## Open questions
- What are the most common claim types in CST? (Jerek started a [dashboard](https://vagov.ddog-gov.com/account/login?next=%2Fdashboard%2Fp2a-9ii-9hz)) 
- Is there a way to create more bespoke experiences for other claim types? Can there be unique content for the accordion based on the claim? Or we could take the Top 5 claim types and make more bespoke experiences for those. This would be its own epic. 

## Acceptance criteria

- [x] Answer the open questions above
- [ ] We have captured current UI states of claim types not served by the compensation claim phases
- [ ] Identify strong candidates for a different claim process description in CST

**Comment by uxgary** [comment]
## Answers to some of the open questions. 
**Is there a way to create more bespoke experiences for other claim types?**
Yes, we will be able to show the Accordion UI on a claim bases. In other words, as part of the initial launch, we will only launch the new UI (Accordion UI) for disability claims. 

**Can there be unique content for the accordion based on the claim?**
Yes, members of the engineering team has confirmed we can create bespoke content for different claim types. 

**Identify strong candidates for a different claim process description in CST**
After conduct our meeting with the Pension team, we have concluded that the pension claims process follows virtually the same process steps as disability claims. The one key difference as it pertains to claim step names is Rating. Pension claims does not have Rating in the same sense as disability claims because disability claims give a percentage rating (disability rating) that is factored into award amount. Contrastingly, pension claim has a "Pension rate", based on income and number of dependents. Consequently, this instead of "rating" we would use "pension rate" as a step title. 

We are in the process of identifying additional candidates as we meet with other teams.

**Comment by uxgary** [comment]
Created an [epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/84260) in places of this issue, because we have to conduct discovery work on multiple claim types individually

**Comment by uxgary** [comment]
Screenshots from the current pension UI. 

![Overview-Of-October-1-2009-Pension-Claim-Veterans-Affairs](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/c6b89a9f-4e92-490b-9ca5-c552ef58edb0)
![Files-For-October-1-2009-Pension-Claim-Veterans-Affairs](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/40764c58-fcb8-4bfd-9fe1-095a891066d2)
![Status-Of-October-1-2009-Pension-Claim-Veterans-Affairs](https://github.com/department-of-veterans-affairs/va.gov-team/assets/13239903/0d0f5714-bc29-4df2-bac5-4d5b53ddd55b)
