### ISSUE TITLE
Remove "new tab" text/behavior from VA-subdomain links

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#84339]
## Description

VADS updated external link guidance a day after we implemented the last update this link. Sorry! I don't think this is pressing, but external link guidance now states that external links should not open in a new tab. 

### User story

As a Cartography team member, I want to update the BTSSS link on the My HealtheVet home page so that it no longer opens in a new tab (or indicates that it will do this), so that I am complying with the latest VADS guidance for external links.

NOTE: checked in with Patrick in comments below re whether to make this change.

<img width="771" alt="Screenshot 2024-05-31 at 11 59 25 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/9fa5fd8d-0920-440e-8d72-044fda4b8eb3">
<img width="767" alt="Screenshot 2024-05-31 at 11 59 10 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/115033532/eb387f33-169b-46a6-99a7-94ca1531dd73">

### Notes
- [Notice of updated VADS guidance](https://dsva.slack.com/archives/CE4304QPK/p1717097782458959)
- [Figma file here](https://www.figma.com/design/CAChU51fWYMZsgDR5RXeSc/MHV-Landing-Page?node-id=2404-21524&t=1RU7JnEPBqNoD6j4-0)

Possible tasks:
- [ ] Update the link under **payments** that reads "File a claim for travel reimbursement....." by removing the parenthetical text that says (opens in new tab)
- [ ] Update link behavior to no longer open in a new tab. Should now open in the same tab. 

## Acceptance criteria
- [ ] BTSSS link now opens in same tab & link text has been updated

**Comment by wesrowe** [comment]
@sterkenburgsara – I updated the title. Can you confirm whether we need to make this update to the newsletter subscription link also?

**Comment by sterkenburgsara** [comment]
I thought we couldn’t do the newsletter link in a new tab bc of security
reasons with GovDelivery on public computers or something? That came from
Patrick, can you possibly check with him? I think if that’s the case an
exception for that link is likely fine.

**Comment by wesrowe** [comment]
@sterkenburgsara, you're totally right, that slipped my mind. Do you have a link to the new guidance? The [link I found](https://design.va.gov/content-style-guide/links#linking-to-external-sites) didn't seem to cover _why_ a link would open in a new tab (the heart of the change).

Now that you reminded me of the security concern, I wonder if the Why of the rule has really changed? I'll investigate.

**Comment by wesrowe** [comment]
Neither of the links that are being referenced in "changed guidance" posts says much that sounds different from the status quo.
- [external links guidance](https://design.va.gov/content-style-guide/links#linking-to-external-sites) just talks about clarity
- [content guide](https://design.va.gov/components/link/#behavior) has the thing about VA links open in new tab only if data loss is possible

Fran Cross (from Public Websites) shared an additional [link to the VA subdomains](https://github.com/department-of-veterans-affairs/content-build/blob/9052cf032d9b10ff62b8981ec1afb87be8c14c9d/src/site/stages/build/plugins/modify-dom/update-external-links.js#L2) that Drupal will no longer update in new tabs:

>   'myhealth.va.gov',
>   'ebenefits.va.gov',
>   'www.accesstocare.va.gov',
>   'www.gibill.va.gov/wave',
>   'www.blogs.va.gov',
>   'www.data.va.gov',
>   'mobile.va.gov',
>   'www.accesstocare.va.gov',
>   'www.oit.va.gov',
>   'ethics.va.gov',

So @sterkenburgsara, I think you're right about GovDelivery being a new-tab domain still, due to security concerns.

I wonder about BTSSS, using that same security lens. I believe VA.gov authentication carries over to BTSSS, so a Veteran on MHV Home will deep link straight into BTSSS. But can they also log out from there and have it end their session on VA.gov?
@batemapf, do you know the answer to that question?

**Comment by wesrowe** [comment]
this got done with BTSSS link addition. Closing.
