### ISSUE TITLE
Life insurance rewriting batch 3: Update your beneficiaries

### ISSUE THREAD

**Issue by DanielleThierryUSDSVA** [department-of-veterans-affairs/va.gov-team#8437]
# User story
As a Veteran with a VA life insurance policy, I want to be able to quickly and easily update the beneficiaries of my policy.

# Details

## Process steps to completion

**Previous steps completed before this was paused in July 2019:**

- [x] Strategy guidance
- [x] First draft in GitHub

**Steps needed to complete this work now:**

- [x] Confirm original IA/content strategy is still valid (Mikki, Danielle, Laura)
- [x] Do a side-by-side comparison of the rewritten & legacy pages to bring over any new/different info since it's been so long since start of work (Laura)
- [x] Identify and address any potential content anomalies in preparation for moving to Drupal (Laura, Randi)
- [x] Finalize existing GitHub draft (Laura) 
- [x] Migrate to Drupal (Laura)
- [x] Add cross links to this page from other appropriate pages (Laura, Randi)

### IA details 
_(note: IA and specifically urls may change based on l4 initiative)_
- **Where this page will live:** This page will be the 2nd page within the "Manage your life insurance benefits" spoke.
- **URL (WIP):** /life-insurance/update-beneficiaries/ 
- **Left nav label:** Update beneficiaries
- We'll also crosslink to this page from other pages within the section.

### Content details
_(note: may need to adjust structure to work in Drupal components, as these pages were started prior to Drupal migration)_
- **Source page:** https://www.benefits.va.gov/INSURANCE/updatebene.asp
- **SEO keywords:** not necessarily an optimal primary keyword for this one, but keywords to consider: sgli update, how to update sgli, how to change sgli beneficiary, sglv 8286, va life insurance form 29 336 
- **What's needed for the rewrite:**
  - Create a new page in our VA.gov style  (ie, brief intro, plain language, bite-sized information presented as a conversation with the Veteran).
  - Optimize page for keywords listed above
  - Implement VA.gov approach to how to apply info (look at existing how to apply pages in other benefit hubs for examples)
  - Add related links to relevant pages

## Github files for reference

- **Current page in GitHub:** https://github.com/department-of-veterans-affairs/vagov-content/blob/content-wip-rewriting-life-insurance/pages/life-insurance/update-beneficiaries-update-rewrite.md

**Comment by DanielleThierryUSDSVA** [comment]
Adding info from our meeting:

- Check to determine if we need to incorporate any relevant contact information from this page (https://www.benefits.va.gov/INSURANCE/resources-contact.asp) per open question document.

**Comment by lwalsh617** [comment]
@RLHecht -- This page is ready for your review:

**Drupal Preview Link**

<http://preview-prod.vfs.va.gov/preview?nodeId=5583>

**Cross Links**

While the SGLI, FSGLI and VGLI detail pages already include cross links, we should add them to the following.

<https://www.va.gov/life-insurance/totally-disabled-or-terminally-ill/>
Add under related links/h3: More information about your benefits

<https://www.va.gov/life-insurance/options-eligibility/tsgli/>
Add under related links/h3: More information about your benefits

<https://www.va.gov/life-insurance/options-eligibility/s-dvi/>
Add under related links/h3: More information about your benefits

Note: I did not include VMLI in this list because insurance money is paid directly to the bank or lender that holds the mortgage.

**Comment by lwalsh617** [comment]
Closing this ticket. Added the Drupal preview link to [Life insurance rewriting batch 3: Content Review #12267](https://github.com/department-of-veterans-affairs/va.gov-team/issues/12267)
