### ISSUE TITLE
[Jenkins] Add Nginx to Jenkins AL2 Terraform

### ISSUE THREAD

**Issue by ph-One** [department-of-veterans-affairs/va.gov-team#84457]
- Nginx is required for GitHub Webhooks to access Jenkins
- Nginx is essential an ACL for webhooks
- :warning: Do _not_ apply this Terraform without collaboration with @ph-One

**Comment by 7hunderbird** [comment]
Additionally it was trying to deploy to staging and prod at the same time.  Which caused some errors when we were rolling out our deployment for staging in our scheduled out-of-bound deploy on 5/28.

The error would be that the AutoScaling Group would fail and leave us in a bad state which we had to manually rollback.

We didn't even understand that it was that two jenkins were both trying to deploy to staging  at the same time.  And since we didn't understand and turn off the second jenkins until I think it was Wednesday morning 5/30, I'm not even sure how prod did deploy correctly if two were going.

**Comment by 7hunderbird** [comment]
In retrospect this deploy http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-prod/1070/console failed probably because of the "two deploys happening at the same time" problem.

**Comment by adhoc-nshipman** [comment]
PR: https://github.com/department-of-veterans-affairs/devops/pull/14435/files
