### ISSUE TITLE
UX: Define solution to make at least one "non-4" tool easier to find on mobile, with metric

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#84523]
### User story

As a Cartography team member, I want to define the smallest change we can make to the landing page so that one or more non-4 tools is easier to find on mobile breakpoints, so that we can take action to address research findings on findability.

"How might we" make one of the non-4 tools easier to find on mobile layout?

### Notes
- "Non-4" means: not the big four tools that are available in the secondary nav
- "Tool" means: a destination for a veteran task (i.e., not an article link)
- "One or more" in case the solution lifts all boats

Possible tasks:
- identify data that defines success for finding a tool (and using it)
- consider process we used on help desk ticket?
- crazy 8s

## Acceptance criteria

- Defined UX solution(s) to make a tool more findable
- Defined the data we would use to validate that our solution contributes to improved use of that tool (not just clicks; seeking proxy for task completion) – e.g., a metric (preferably with a baseline), or an approach for A/B testing
- Got Patrick's and Kaitlin's feedback and validation on solution(s)
- Ticketed for chosen solution: UX design, implementation, and post-launch monitoring plan

**Comment by katbrinkley** [comment]
Update: UX team synced about this this morning, did a brainstorming exercise for ideas. hit some road blocks on deciding how to move forward. See [Mural board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1718373911019/ee8b1ae677d09c231c61d3cd00dba4bae054054e?sender=uf94a77a19aaf687331c09367). Sara also put 3 potential solutions in Slack chat:
Ideas:
- Flip the order of the gray boxes & put payments & supplies boxes at the top
- Maintain the same order, but significantly reduce the size of the boxes for the "big 4" since they're duped by the secondary nav already
- Don't touch landing page design, but prioritize a notification for medical supplies with the longer-term goal of removing the need for that box; eventual follow on to do same for replacing links to payments box with conditional notifications.
- There is still some value in having the concept of looking at your historical payments & including links to exploratory content about what medical supplies are available. We may need to think through what that should look like (R&S pages, etc.)

Kat is working on finding analytics to support these.

**Comment by jonathanjnelson** [comment]
[Async Slack conversation thread](https://dsva.slack.com/archives/C0581MN69TJ/p1718639334494659?thread_ts=1718386082.398439&cid=C0581MN69TJ)

**Comment by katbrinkley** [comment]
Update:
- UX team defined a couple UX solution(s) to make these tools more findable and found that we had more questions about the larger picture/value of the landing page site.
- Kat and Jonathan defined the data we would use to validate that our solution contributes to improved use of that tool:
  - Funnel analysis of a user clicking into a tool and starting* a task (not conversion rate)
  - Using current metrics from this [GA3 dashboard](https://analytics.google.com/analytics/web/?pli=1#/dashboard/Zz-BsIsFTru7HI16l-D2MA/a50123418w177519031p176188361/) as a baseline for comparison of the new UX solution
- Tickets created for next steps:
  - Design review ticket for 'assigned' UX designers + Kaitlin to get her feedback & validation on ideas
  - Figma design ticket + development/implementation efforts once solution is confirmed
  - Analytics monitoring ticket for analyzing the data after a finite time period to compare baseline UX analytics to the new solution

**Comment by jonathanjnelson** [comment]
- Follow-on design ticket #86112
- Follow-on post-launch monitoring plan #86242 
- Follow-on implementation ticket #86246

**Comment by sterkenburgsara** [comment]
**Update**: UX team + Wes met with Kaitlin Fink on Monday, 6/24/2024 to get feedback on 3 different design ideas for starting to iterate on the landing page in order to improve the findability of the non-4 tool links. Two of the ideas were approved to move forward into further ideation, and follow-on tickets are being developed for that work.

**Comment by wesrowe** [comment]
What's needed to close this?
