### ISSUE TITLE
Page not found component should set a generic page title

### ISSUE THREAD

**Issue by carlosfelix2** [department-of-veterans-affairs/va.gov-team#84588]
### User story

As a user, I want to to see a generic page title for any page not found message instead of an application's title, so I am not confused as to where the error is coming from.

### Notes
- The current implementation shows the page title of the application serving the 404 page. This should be generic like for Drupal. Suggestion is the same as Drupal: `Page not found | Veterans Affairs`

Possible tasks:
- 

## Acceptance criteria
UX: 
- [x] Get approval on updated title tag from IA CoP:`Page not found | Veterans Affairs`
- [x] Get approval on page title update from CAIA: 
  - New H1: **We can't find that page**

Dev:
- [ ] Change 404 page title to agreed-upon title regardless of what application is serving the page
- [ ] Update page title to be an H1 (not H3) 
- [ ] Update page title tag to whatever is approved by IA CoP - TBD
- [ ] Create follow-on ticket to review full page heading hierarchy and make necessary updates
- [ ] A11y review
- [ ] QA review

**Comment by sterkenburgsara** [comment]
This makes sense to me! Thank you for noticing this & being so thorough. I don't see issues with this approach, but wonder what you think about being really explicit with the title tag? Something like: `Page not found | Veterans Affairs`?

**Comment by wesrowe** [comment]
@sterkenburgsara to validate with IA CoP that we picked the right title.

**Comment by sterkenburgsara** [comment]
Update: shared with IA CoP for approval and waiting for thumbs-up from Mikki Northuis. But realizing that the Drupal version has wonky heading hierarchy (there are no H1s or H2s, only H3s), which violates a11y requirements. May need a follow-on ticket to rework heading hierarchy and submit those improvements to CAIA for the Drupal version.

**Comment by sterkenburgsara** [comment]
Update: @mnorthuis suggested that we fix the heading hierarchy on our version of the 404 and get content to peek at the H1 before deciding the title tag. Then contribute our recommendations back to the Design System Team and ask that the Drupal version be updated to follow our guidance. 

[I filed this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85865) for @laurwill and myself with CAIA

The whole page (not just the title) has heading hierarchy issues, so I think we probably need another ticket to adjust those. But for now, what do you think about taking these steps to close this ticket? (pending CAIA approval):
* Change title from "Sorry -- we can't find that page" to **"We can't find that page"**
* Make that title (which is an H3) an H1 so that it is a true page title and meets a11y requirements
* Update the title tag to `Page Not Found | Veterans Affairs`

//cc @carlosfelix2 @wesrowe

**Comment by wesrowe** [comment]
TO clarify, that list of bullets is what you want us to do to the 404 component, right? and it's the same list that CAIA will apply to the Drupal 404? If so, these sound good and let's add to ACs.

**Comment by sterkenburgsara** [comment]
@wesrowe I am waiting for CAIA to approve these bullets, but yes :-)

**Comment by sterkenburgsara** [comment]
@carlosfelix2 @wesrowe CAIA approved plan articulated in A/Cs above in this ticket. 

More details / improvement suggestions for a11y are listed [in the linked CAIA ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85865). I will create a follow-on ticket to this one for our backlog detailing those additional updates.

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the title tag has been updated to what is in the Description of this ticket.

<img width="1363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUdLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d61cd9d19db9ced1c6901d8b760c9736a8d6ddd/Screenshot%202024-06-24%20at%202.06.52%E2%80%AFPM.png" alt="Screenshot 2024-06-24 at 2.06.52 PM.png" />
