### ISSUE TITLE
[Development] 526 Claims: EVSS Has Identified Several Additional Schema Discrepancies

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8486]
## What happened?

Per our previous #8350 ticket we have some remaining work.  Essentially, we want to be able to transform our data into exactly what EVSS is expecting so that we can get strict schema checking.

In our process:
- We pull in all rated disabilities from this API - https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/getRatedDisabilities
- Collect user selected disabilities & newly added disabilities
- Return un-modified disability data through this API - https://department-of-veterans-affairs.github.io/va-digital-services-platform-docs/api-reference/#/form_526/postSubmitFormV2

## Specs:
- Device: All
- Browser: All
- Test User: user 228

## Steps to Reproduce
- URL: https://staging.va.gov/disability/file-disability-claim-form-21-526ez/review-and-submit
- Test User: user 228

## Desired behavior
Completed form 526 v2 is submitted without any errors

## Acceptance Criteria
- [ ] Transform our 526 submission data into exactly what EVSS is expecting
- [ ] Match the Swagger docs

**Comment by Mottie** [comment]
The `ratingDecisionid` was already addressed in ticket #8350.

Since there are more fields that don't need to be submitted, I was planning on only allowing valid keys; but now I see it's removing probably important fields

This is the list of allowed keys that I added:

- `classificationCode`
- `diagnosticCode`
- `disabilityActionType`
- `name`
- `ratedDisabilityId`
- `serviceRelevance`
- `specialIssues`

But while testing, I noticed removing the following keys:

- `decisionCode`
- `decisionText`
- `ratingPercentage`
- `unemployabilityDisability`
- `disabilityPreventingEmployment`

I think Silvio said, it's fine that it's removing the `decisionCode`, `decisionText` and `ratingPercentage`, but the last two we never discussed. And I fear removing even more that aren't showing up in my testing.

I may just end up expanding the initial method of (continuing to) remove `ratingDecisionId` and additionally remove `decisionCode`, `decisionText` and `ratingPercentage`.

**Comment by Mottie** [comment]
I ended up removing the following fields prior to submission:

- `decisionCode`
- `decisionText`
- `ratingPercentage`
