### ISSUE TITLE
"No MHV access" route guard: Evaluate path forward for each app and PR

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#84911]
### User story

As a Cartography team member, I want to understand in light of the recent analysis whether or not each of the apps in the MHV space needs us to provide a "No MHV access" alert, so that we can make sure we're delivering an improved UX to Veterans.

As a Cartography team member, I want to evaluate each route-guard pull request in light of the recent analysis, so that we can get closure on each of them in separate tickets.

### Notes
- picks up from #77237
- [Mural of sign-in account checks and back-end systems](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717177396025/367057c4a9219404c3b7080e71210082b3c65771?sender=uebde62ceb342c6477fb09406)
- [Huge slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1717185477450519) on subject
- Review discussion in [the original UX ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75533) that led to route guard concept
- there might be a better phrase to describe this than "no MHV access" (and the content of the alert may also be incorrect)

#### Supply reordering-specific notes:
- [Slack thread](https://dsva.slack.com/archives/C0581MN69TJ/p1717526862232939?thread_ts=1717512744.362889&cid=C0581MN69TJ) with key questions/topics and input from Patrick re the app and existing alert gaps
- Work to add a sign-in widget to the unauthenticated entry-point page for the tool is also heavily impacted (#79823)

## My Health Tool Pages
1. [Add mhv route guard to after visit summary](https://github.com/department-of-veterans-affairs/vets-website/pull/29313) - Needs route guard based on AVS API facility count
2. [Add mhv route guard to medications ](https://github.com/department-of-veterans-affairs/vets-website/pull/30062)- MERGED
3. [Add medical records mhv route guard](https://github.com/department-of-veterans-affairs/vets-website/pull/30063) - MERGED
4. [Add mhv route guard to Secure Messaging](https://github.com/department-of-veterans-affairs/vets-website/pull/29371) - Needs route guard based on MHV SM API which validates presence of messaging in user services
5. [Add mhv route guard to supply re-ordering](https://github.com/department-of-veterans-affairs/vets-website/pull/29373) - Needs route guard based on ROES / DLC facility count
6. [Add route guard component and unit test and copy for NoHealthAlert](https://github.com/department-of-veterans-affairs/vets-website/pull/29374) - MERGED
7.  Appointments - Needs route guard based on VAOS enrollment status 
8.  1010 EZR - Needs route guard based on form Enrollment Status

</details>

## Acceptance criteria

- Documented in a single location whether each of the applications in [PR list] has a UX need for a no-mhv-access alert, and whether a route guard is the right way to provide it
- Documented what needs to be done with each route guard PR – merge as-is, modify, get external/octo input, close, etc.
- Reviewed proposed path forward with Patrick 
- Ticketed next steps in individual tickets under this epic

**Comment by sterkenburgsara** [comment]
I don't think this is right! The After-visit summary is a type of care summaries & notes (Medical records) which does rely on the MHV-API. Right now, the only tool in Phase 1 that can cross-link to the AVS is Appointments, but it doesn't actually rest on the VAOS API. 

Is the rationale different than what I wrote above? Can you explain why the route guard logic needs updating? 

// cc @jzucadi @wesrowe

**Comment by jzucadi** [comment]
Doc on what health tools under /my-health` use for their backend data, which health tools can use facility count:
https://docs.google.com/document/d/1tqJZ2NwZkAxxwwWeL-8OVdCl_7JaYPqVvtIGcI73VEI/edit

**Comment by jzucadi** [comment]
Two of the My Health tools actually rely on the MHV data from vets-api using the `mhvAccountState` property, and those two PRs have been approved and can now be merged.

Those PRS are for:
1. [Medications](https://github.com/department-of-veterans-affairs/vets-website/pull/30063)
2. [Medical Records](https://github.com/department-of-veterans-affairs/vets-website/pull/30062)

**Comment by radavis** [comment]
Authorization rules for MHV Health Tools: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/4e489855a085b10a0a621886e45bc70ad8a0fb0c/teams/mhv-landing-page/authorization.md

**Comment by radavis** [comment]
Here a are some suggestions on how to approach gating access to the remaining health tools.

## Health Tools

1. avs
2. mhv-medications -- route guarded
3. mhv-medical-records -- route guarded
4. mhv-secure-messaging
5. supply reorder -- on hold until path/URL changes
6. mhv-landing-page -- where all the alerts are being displayed
7. vaos
8. ezr

### avs

Within the [`<Avs /> container`](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/avs/containers/Avs.jsx#L95), add the `verify` prop to `<RequriedLoginView />`.

Since this is an "After Visit Summary" and the user is providing an id referencing a specific after visit summary, is redirecting to `/my-health` even necessary? How would they get an AVS id without being registered at a facility (aka, being a VA patient)?

### mhv-secure-messaging

Within the [<App /> container](https://github.com/department-of-veterans-affairs/vets-website/blob/c69aed6/src/applications/mhv-secure-messaging/containers/App.jsx#L154:L160), add the `verify` prop to `<RequiredLoginView />`, and change the argument to `window.location.replace()` to `/my-health`.

```jsx
// src/applications/mhv-secure-messaging/containers/App.jsx

{user.login.currentlyLoggedIn &&                            // if authenticated and
!userServices.includes(backendServices.MESSAGING) ? (       // no authorization
  window.location.replace('/health-care/secure-messaging')  // then, redirect
```

### vaos

Within [`<EnrolledRoute />`](https://github.com/department-of-veterans-affairs/vets-website/blob/a7abd19/src/applications/vaos/components/EnrolledRoute.jsx#L12), wait for `/data/cms/vamc-ehr.json`, and `state.user.profile.loading === false`. Check patient facilities and redirect to `/my-health` when user has no associated facilities (i.e. - `!hasRegisteredSystems`).

### ezr

Authorization for the 10-10EZR is different than all other health tools. Recommend showing the link on the landing page and letting the app determine authorization.

**Comment by wesrowe** [comment]
At end of sprint, ACs/actions outstanding:
- Need to review proposed tickets with UXers
- Wes and Patrick review

**Comment by dcloud** [comment]
## After review with UXers

While reviewing Richard's proposed tickets for next steps, Sara and I considered how a future where [vets-api's backend services feature](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/services/users/services.rb) could enable us to be granular in detailing which tools/pages are available (on the landing page).

That said, Richard's tickets reflect reasonable next steps to take in partnership with tool teams.

## Next steps

Review with @batemapf and @wesrowe

**Comment by dcloud** [comment]
After talking further with @radavis and @wesrowe and following up with Oleksii regarding SM, we have narrowed down the remaining work to:

- https://github.com/department-of-veterans-affairs/va.gov-team/issues/86422


## Closed tickets


### AVS

The **AVS** ticket was closed after a [discussion with Adrian Rollet](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86439#issuecomment-2195168584):

> Via slack with Adrian Rollett we determined that there is no probable way for an unverified user to reach the AVS app. Closing as a no-op.

### Appointments

The **Appointments** ticket was closed because Appointments already shows an appropriate alert to users who don't have access, and their alert is well-suited to their tool's access requirements and remediation steps.

**Comment by dcloud** [comment]
@wesrowe Given we've figured out a path forward for each tool and PR, and Richard created [the SM ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/86422) we need, I think this is safe to close

**Comment by wesrowe** [comment]
Thanks! Closing.
