### ISSUE TITLE
NoK: Medallia user feedback analysis

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#85067]
### User story

As a Cartography team member, I want to request qualitative feedback frequently after launch of NoK/EC, so that we can identify issues that Veterans experience.

### Notes
- feature launched 4/8
- [example request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/81207) from 4/11 thru 4/19
- NOTE: phone number was fixed (replaced with "call a facility") around 5/8 

Possible tasks:
- request data

## Acceptance criteria

- Relevant feedback noted in comments below and escalated to team for remedy
- Data saved to team Sharepoint site alongside previous analysis – [Sharepoint link](https://dvagov.sharepoint.com/:x:/s/oitmhvonvagovcartographyteam/EZpDQYj0oCVMpdtX7osS1ZEBtPu5JQ9_E58FTMF-mzc40A?e=bassvg)

**Comment by fmccaf1** [comment]
Submitted request for data, [ticket here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/85559)

**Comment by fmccaf1** [comment]
#### Of the 702 responses to the VFS Questionnaire from 4/19-6/10 that touched on VA.gov profile:
- 66 responses mention NoK
- 65 of those 66 mention they were trying to change NoK information but could not 
- 1/66 who did not try to change NoK information said they were simply verifying that the info was correct and it was
- There is no clear change stemming from the change of phone number in early May 

#### Some quotes:
- "Unable to update emergency contact information location at: https://www.va.gov/profile/contacts. Call the number listed on the page and spoke to three different people, who were UNABLE to resolve issue" (this was 4/25)
- "Change my emergency and next of kin's old phone number to the new phone number on my va.gov account. It took me 4 separate calls since yesterday and approximately 1 hour of my time." (4/19)
- "Change next of kin information. The website says to do it at the clinic. The clinic says to do it online." (5/16)
- "I have tried to change emergency contact info. several times nothing works even going to a VA facility" (5/20)
- "I went to an appointment today. During the automated check-in, I was asked to confirm who to notify in an emergency. It had my ex-wife instead of my current wife. At my auditory appointment I asked the check-in person to change it. She didn't and I can't change it myself online." (5/22)
- "Update my next of kin address. I did this at the VA clinic in Honolulu and it was never updated in the system" (5/27)
- "I call the VA and had her removed, now I see you have put her back, please remove her from my contacts" (5/29)
- "Needed to update my 'health care contact' info but you defer that to my closest VA facility. That is a joke as in talking to my patient advocate, my healthevet coordinator and benefits sections, NO ONE was competent enough to do so." (6/1)

#### Recommended change(s)?
I am hesitant to recommend a change but wonder about adding some text to explain _why_ the data is not able to be changed on the site. It sounds like many who responded were frustrated about the seemingly arbitrary lack of affordance there.

**Comment by wesrowe** [comment]
The first two verbatims above seem to indicate they called the old number, which makes sense since the update didn't go out til 5/8.

The recommendation would be to implement the edit functionality. It sounds like just under 10% of feedback for the entire profile product was about NoK not having edit functionality.
