### ISSUE TITLE
[V0.1] Pull ITF sample data

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#85071]
# Overview
Based upon work previously done by @danlim715, we need to pull a sample of the ITF records from production.

This script might be what he used:
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/scripts/pensions/in-progress-forms.md

This relates back to:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/81413

**Comment by TaiWilkin** [comment]
Please find a data download from production attached. I redacted all PII; the first row is fake data, to show what the real data looks like. 
[inprogressdata-redacted.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5iQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c8eba43a9551aaec1dff7578bc75914e3ee11ce/inprogressdata-redacted.pdf)

**Comment by buddhima-coforma** [comment]
@sanjabaj2 Tai has pulled a sample dataset above. Once you hear back from OIT do let us know what we need to adjust.

**Comment by sanjabaj2** [comment]
Thank you. Do we know when are we going to be ready to do this? Meaning when do we plan to launch V0?
We agreed to do this after the launch. Right? I am trying to get a timeline for when do we expect them to do this.

From: Buddhima Kurukulasuriya ***@***.***>
Sent: Wednesday, June 12, 2024 2:57 PM
To: department-of-veterans-affairs/va.gov-team ***@***.***>
Cc: Bajovic, Sanja ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [department-of-veterans-affairs/va.gov-team] Pull ITF sample data (Issue #85071)


@sanjabaj2<https://github.com/sanjabaj2> Tai has pulled a sample dataset above. Once you hear back from OIT do let us know what we need to adjust.

**Comment by buddhima-coforma** [comment]
We are ready to do this once you instruct us, based on the OIT request you put in.

Yes, this task is independent of V0 launch.

cc: @aplatt-coforma

**Comment by buddhima-coforma** [comment]
@TaiWilkin we also want to manually process application start dates for those who submitted after 1/31. Can you bring in a column for that as well?

**Comment by TaiWilkin** [comment]
@buddhima-coforma I want to check what the desired data is. The list that was provided is the started date and veteran identifier from all existing in-progress forms. Are you looking to have a second list that has the started date and veteran identifier from submitted forms?

**Comment by buddhima-coforma** [comment]
@TaiWilkin let's go for one list with an additional column.
Think of it as a list of dates and identifiers for everyone who started a form in a given window. Some of them would still be in progress (they have only a start date) while others have submitted a claim (they have a start date and a submission date).
cc @sanjabaj2

**Comment by sanjabaj2** [comment]
I would only excluded those whose submission date is the same as the start date. Importing ITF would not change benefit effective date for those cases.

**Comment by mjknight50** [comment]
[in_progress_redacted.csv](https://github.com/user-attachments/files/15838329/in_progress_redacted.csv)

**Comment by TaiWilkin** [comment]
This data is from staging, not from production, and I haven't done any filtering by date, but it should give you a sense: [dc07d6cc-e90b-4732-8c9c-75a0b3ca3381.csv](https://github.com/user-attachments/files/15840090/dc07d6cc-e90b-4732-8c9c-75a0b3ca3381.csv)
From line 17 on (counting the header as line 1), each row comes from the SavedClaim table, which includes ITF (as `itf_datetime`) when available and the form_started_date (as `created_at`) when available. I wasn't able to find any SavedClaims with a `form_started_date`, so as a backup I added the column `claim_created_at`, which is the `created_at` field of the saved claim. This represents when the user first attempted to submit the claim. Unfortunately, since the InProgressForm is deleted when the SavedClaim is created, I can't go back to the InProgressForm for the SavedClaim to see when that was created. 
In regards to filtering, before rerunning this on production, I'd like to confirm which objects you'd like data on. Is it InProgressForms where the created_at date is after 1/31/2024, or where the updated_at date is after 1/31/2024? For SavedClaims, is it SavedClaims where the created_at date for the SavedClaim is after 1/31/2024?

**Comment by buddhima-coforma** [comment]
Let me know if I understood these correctly, as my suggestions are based on them. @TaiWilkin 

InProgressForms = claims not submitted. Let's use created_at as that gives the earliest possible ITF
SavedClaims = submitted claims. For claims that were submitted after 1/31, grab the created_at date

**Comment by TaiWilkin** [comment]
@buddhima-coforma Yes, InProgressForms are unsubmitted claims, and SavedClaims are submitted claims. Unfortunately, we generally don't have access to the original creation date of the claim for SavedClaims; only the date that the SavedClaim was created, which is the submission date.

**Comment by buddhima-coforma** [comment]
Based on the above, the previous file you provided with start dates for in-progress claims is sufficient @TaiWilkin.
@sanjabaj2 let us know if the analysts using the file need us to update the format

**Comment by sanjabaj2** [comment]
> [in_progress_redacted.csv](https://github.com/user-attachments/files/15838329/in_progress_redacted.csv)

Just looked at the file. The SSN columns has many rows where number of Xes is less than 9. Did we lose trailing or leading 0s?   Also, this file has 6k rows. I thought we have around 3k in progress apps.

**Comment by sanjabaj2** [comment]
While you are at it, feel free to exclude records that don't have SSN nor participant_id.

**Comment by TaiWilkin** [comment]
[in_progress_forms6.20.24.csv](https://github.com/user-attachments/files/15919166/in_progress_forms6.20.24.csv)

Here is an updated version, with rows with no valid user identifier excluded, and only including in-progress forms since 1/31/24. (All PII redacted)

**Comment by sanjabaj2** [comment]
For those records that we excluded because they were missing participant_id and SSN, do we have ICN for them? If we have ICN, we may be able to create a person in corpDB.

**Comment by TaiWilkin** [comment]
> So we have 4281 in progress forms as of today?

As of right now, we have closer to 5000 in-progress forms that were started after 1/31/24. Some were excluded because they had no valid identifier, and some were excluded because the user wasn't logged in (based on the previous ITF script). If desired, I can add the SSN from the in-progress form for logged-out users where available/valid.

> Also, some participant ids have 8 characters and some have 7. Is that expected?

I believe so - I think that's a database identifier, which often vary in length. 

> For those records that we excluded because they were missing participant_id and SSN, do we have ICN for them?

For logged-in users, we do have the ICN in some cases, although I don't know whether those are the same user for whom we're missing another valid identifier. I can rerun the script and include ICN where available, if you'd like. 

If I rerun the script, would you like a count of the total number of forms excluded due to invalid identifiers?

**Comment by sanjabaj2** [comment]
I thought we are only saving in progress form for logged in users. Yes, please provide count for excluded users.

**Comment by TaiWilkin** [comment]
> I thought we are only saving in progress form for logged in users

Updated previous message to clarify this point - yes, the users are logged in then the form is initially saved.

**Comment by sanjabaj2** [comment]
Where can I access un-redacted file? How many did we exclude because of missing id fields?

**Comment by mjknight50** [comment]
@sanjabaj2 - What else do you want to see done with this ticket?
I feel like the scope has changed from having a sample format, to then doing sample data, and now to something else.

**Comment by mjknight50** [comment]
Re-opening
------------
Can we get a count of how many of these in-progress form users do not have a participant ID?

**Comment by aplatt-coforma** [comment]
To be continue when Tai gets back and v0 ITF is launched.
