### ISSUE TITLE
Add "Prepare for your appointment" section to in-person appointments

### ISSUE THREAD

**Issue by AdamOye** [department-of-veterans-affairs/va.gov-team#85118]
## Issue Description
Add a "prepare for your appointment" section to in-person and phone appointments. These appointment types do not include the "how to set up your device" instructions for video appointments.

## Acceptance Criteria

- [x] The `va_online_scheduling_med_review_instructions` feature flag is on

---

- [ ] When the user opens an in-person appointment
     A `Prepare for your appointment` section shows above the appointment actions
       And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=1-35050&t=B6ZBY0DKteqWV4XQ-4)
       And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/)
      
<br />

- [ ] When the user opens a canceled in-person appointment
        A `Prepare for your appointment` section shows above the appointment actions
       And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=356-8533&t=B6ZBY0DKteqWV4XQ-4)
       And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/) 

---

- [ ] When the user opens an in-person vaccine appointment
       A `Prepare for your appointment` section shows above the appointment actions
       And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=1-35050&t=B6ZBY0DKteqWV4XQ-4)
       And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/)

<br />

- [ ] When the user opens a canceled in-person vaccine appointment
        A `Prepare for your appointment` section shows above the appointment actions
        And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=356-8533&t=B6ZBY0DKteqWV4XQ-4)
        And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/)    

---

- [x] When the user opens a Video at VA appointment
       A `Prepare for your appointment` section shows above the appointment actions
      And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=114-32979&t=B6ZBY0DKteqWV4XQ-4)
      And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/)
     
<br />

- [ ] When the user opens a canceled Video at VA appointment
       A `Prepare for your appointment` section shows above the appointment actions
       And the content matches the [design spec](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=356-8871&t=B6ZBY0DKteqWV4XQ-4)
       And the `Find out what to bring to your appointment` link points to the [URL](https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/)

---

- [ ] The changes are approved by the UX/UI team and any relevant stakeholders.
- [ ] The updated wording is reflected in user guides and help documentation where applicable.

## Design

[Mockups](https://www.figma.com/design/zdLjBmeymTyHALf5lBzVgI/Medication-Review-Language-%7C-UAE?node-id=13-32911&t=MybgwPnCCJcgmy0u-4)

**Comment by ldelacosta** [comment]
Validated in staging. UX team will do a second review. cc: @outerpress

**Comment by outerpress** [comment]
@JunTaoLuo @ldelacosta a couple of issues, looking at Judy's appointments:
- The new section shouldn't appear for past appointments - just upcoming and canceled. Past appointments are kind of a mini-medical record, with (soon) info like after-visit summary and travel pay, so we treat those differently. This is not totally clear from the AC in the ticket ticket, apologies for that.
- The link should open in the same tab since it's a va.gov link and there's no risk of data loss. See [guidance on opening external links](https://design.va.gov/components/link/#behavior).
- The content under the heading has a font size of 16px, while the link is 16.96px (which is the new standard base size) - see screenshot below. Both should be 16.96px.
- The content under the heading should ideally be wrapped in some kind of semantic tag (like `<p>`) to help screenreader users navigate - see the paragraph elements section in [this WebAIM article](https://webaim.org/techniques/screenreader/#navigating). Let me know if this is going to make it tricky to get the spacing right.

I'm fine if it'd be easier to deal with these in new tickets after this is released.

<img width="1328" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjBaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c3536b5de288efd99745fcf359e489a636375bb/Screenshot%202024-07-29%20at%203.13.58%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 3.13.58 PM.png" />

**Comment by ldelacosta** [comment]
Since this work is sitting behind a feature toggle, lets open a new ticket to address the other items. cc: @outerpress

**Comment by JunTaoLuo** [comment]
Sounds good, but for the tickets that I still have in progress (video and CC) I'll try to incorporate these feedback items.

**Comment by JunTaoLuo** [comment]
@outerpress Just curious what the behavior should be for cancelled appointments in the past?

**Comment by outerpress** [comment]
Thanks @JunTaoLuo ! We don't display canceled appointments at all in the past list, so no need to consider that case

**Comment by JunTaoLuo** [comment]
Ah that makes sense. However I see that our logic is a little strange since we fetch cancelled past appointments and then filter it out. I might file a spike issue to see what's going on there.

**Comment by ldelacosta** [comment]
Closing out the ticket. Will address the items above in a new ticket. cc: @outerpress @JunTaoLuo

**Comment by ldelacosta** [comment]
Addressing it in [#89551](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89551)
