### ISSUE TITLE
Support CMS infra team in enabling CD for va.gov-cms in new infrastructure

### ISSUE THREAD

**Issue by wyattwalter** [department-of-veterans-affairs/va.gov-team#852]
Create a dev and staging pipeline to deploy CMS to those environments upon commit to master trunk in the repo. In the image below this ticket would comprise the green box in the bottom left.

![image.png](https://images.zenhubusercontent.com/5b44bc10d37aac6fb649fa57/09435374-84dc-447e-b84d-5502b388252c)

- [x] Webhook is configured and sending events to Jenkins
- [ ] Pipeline builds and deploys for `dev` and `staging`

**Comment by b00klegger** [comment]
CMS `develop` builds blocked by #1134 . During build composer is run twice, the second run fails. According to Elijah this is due to a post-install command added recently. The second compose is attempted to run as the `apache` user which fails as the composer binary is not in the users PATH. The tenative solution is to create a dedicated user to install and run the application.

**Comment by ricetj** [comment]
Currently blocked

**Comment by ricetj** [comment]
Done
