### ISSUE TITLE
10-10d: update copy - intro screen WIP

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#85308]
staging url: https://staging.va.gov/health-care/champva/apply-form-10-10d/introduction

**_Note: waiting for input from Syd/Jamie and update to copy - particularly Step 3_**
- add breadcrumb (per guidance [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/ia-design-docs/champva-online-form.md))
- add updated subtitle ("Application for CHAMPVA....")
- Remove sign in box at the top of the intro page
- add sign in button at the bottom of the page (blue sign in box)
- update copy to match [figma](https://www.figma.com/design/UmAtr3ULQEInMXfNFwP0g0/CHAMPVA-Application-(10-10d)-User-Testing-Prep?node-id=2017-51097&t=HNQmuLvTpNX5JaVq-0)
- URL (for supporting documents link): https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/champva-apply.asp
- remove 'after you apply' section

**Comment by michaelclement** [comment]
@baltes @marywang2 Do we know what URL this should link to? (from the Figma)
<img width="345" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHlVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--680808d879722b41f56332c2326fa861686b84c2/link.png" alt="link.png" />

**Comment by baltes** [comment]
@syd-hoeper Do you know where the link Michael's asking about should take the user?

**Comment by syd-hoeper** [comment]
@baltes I'm not sure since I'm not able to see the image -- @michaelclement could you explain which link you're referring to?

**Comment by baltes** [comment]
@syd-hoeper I think this is viewable in zenhub but not github. Here's the [zenhub link](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/85308) , but the question is about the "Find out which documents you'll need to apply for CHAMPVA" link.

**Comment by syd-hoeper** [comment]
Thanks @baltes ! So right now this is the link: https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/champva-apply.asp butttt CAIA is working on migrating this info to VA.gov in the next month or so, so we will have to check with them once it gets switched over to get the new URL. We are facing the same thing with the CHAMPVA Claims form as well

**Comment by marywang2** [comment]
It sounds like they will do a redirect whenever they do switch so we can update this later to the final url.

**Comment by marywang2** [comment]
@syd-hoeper @michaelclement @baltes  I just reached out to Laura, we can use this one for that link (I added a comment to the figma): https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/#how-do-i-get-champva-benefits

**Comment by syd-hoeper** [comment]
@marywang2 @baltes I would like to push back on that second link -- I don't think that's an appropriate spot to send them given the language of the link. Since the link says "find out which documents you'll need to apply for CHAMPVA" the goal here is to show people an overview of which specific documents they will need to gather before filling out the form (health insurance cards, marriage certs, etc). 

When I click this second link, provided by Laura, while it brings me to a section that says "To apply, submit these required documents:" the problem is that the list of required documents is "10-10d" and "OHI" -- this is too high level and not helpful for the user, since they are already in the process of filling out this form. When I dive in deeper and click the 10-10d link, there are no specifics on that page about which actual documents they'll need in order to fill out 10-10d. 

Because of this the first link that I provided should be the page that's linked because that is the page that has the actual details that the user is looking for

**Comment by laurwill** [comment]
Hey @syd-hoeper ! Just hopping in to explain the rationale — totally agree that the link I suggested is not ideal. We try to always link to a modernized page rather than a legacy page when possible, because modernized VA.gov pages are much more accessible. This situation is a bit less clear, because both the modernized page and the legacy page have roughly the same outdated content that we know we want to change. And you're right that the legacy page has more helpful headers related to supporting documents. 

So we could go either way here, and I'm fine with including either link because this is only a temporary solution. We'll ask you to update the link when we publish updates to the modernized page, which will hopefully happen before you launch this form. The new link will point to a new H2 "Supporting documents for your application." See screenshots here of the sections on the legacy, modernized, and updated modernized pages. 

[Legacy page](https://www.va.gov/COMMUNITYCARE/programs/dependents/champva/champva-apply.asp)
<img width="933" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2FaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db134b4c23724bb637e1269a8dde1b16c1164bab/image.png" alt="image.png" />

[Current modernized page](https://www.va.gov/family-and-caregiver-benefits/health-and-disability/champva/#how-do-i-get-champva-benefits)
<img width="656" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM21aQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45519f8d8287b990da9ee18d5ea55675b16c697e/image.png" alt="image.png" />

Draft updates to modernized page (not yet published)
<img width="1026" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMytaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--203f15803145bdbe22644250ff31f8d30f587d23/image.png" alt="image.png" />

**Comment by syd-hoeper** [comment]
Thank you so much for that additional context @laurwill !! 

In that case I really think we should have the legacy link in the meantime until we can provide the newest URL. I think that because while it may be less accessible, I'd argue that there's no value in the page being accessible if it doesn't provide the necessary information. 

But yes, hopefully the timing will work out so that once it's in production it will link to y'all's newest page and we'll be giving users the best experience ha. Thank you!!
