### ISSUE TITLE
FE | Profile Privacy Statements | Feature Toggle

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#85603]
## Background 

As we build the privacy statement component for the bottom of the profile pages we should put this behind a feature toggle so we can manage the deployment 

We'll use this toggle for both privacy statements, the one for notification settings #85100 and the profile component that will go on all pages mocked in #85101

## Tasks 
- [x] create the toggle 

## Acceptance Criteria 
- [x] we have a feature toggle

**Comment by adamwhitlock1** [comment]
@mtcA6  We added the toggle `profile_show_privacy_policy` and built a component that shows at the bottom of each page.

I turned on the toggle for just user 226 on staging so that it can be validated. 

I realize yall are talking about going a different way on this this work, but figured we can close this out and create further tickets when work resumes or things change.

![Screenshot 2024-06-18 at 11 37 04 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/8332986/fffbfa22-3b30-4e31-898d-2545cb1f9b78)
