### ISSUE TITLE
VSP content review: 10-10CG Caregiver form 

### ISSUE THREAD

**Issue by peggygannon** [department-of-veterans-affairs/va.gov-team#8565]
## User story
As a caregiver and Veteran, I need to know how to apply for Caregiver benefits. 

This ticket captures VSP content feedback on the 10-10C Gform. 

Prototype link: https://vsateams.invisionapp.com/share/9XWSQZ6SMG5#/screens
 

## Acceptance criteria
- [x] Peggy provides content feedback for the 10-10G form
- [ ]  Caregiver team incorporates feedback and/or asks follow up questions on the feedback
- [ ]  Leave any comments for feedback you decide not to take
- [ ]  Peggy checks form after content feedback has been incorporated

**Comment by peggygannon** [comment]
VSP content feedback (prototype review)

[https://app.zenhub.com/files/133843125/829ae94e-990a-45ed-86c0-03cbd7f7f7f3/download](https://app.zenhub.com/files/133843125/829ae94e-990a-45ed-86c0-03cbd7f7f7f3/download)

**Comment by peggygannon** [comment]
@ala-yna @psanders86 checking in to see if you have any additional questions about my VSP feedback? 

If not, can you let me know when I'll be able to see an updated mockup? 

thanks!

**Comment by psanders86** [comment]
Thanks! No questions on my end -- we are presenting findings to the program team tomorrow afternoon, and then we'll do the deck after they sign off and post here.

**Comment by sshein** [comment]
Wanted to let you know Peggy regarding the button to "print screen" inside the blue box - that is a redesign because the copy at the top was hard for users to see when tested. We already showed that to VSP and got it approved awhile ago... @jonathanjnelson was there a ticket for that work or was that more of an informal review?  The idea is that we're improving the stylesheet that shows after the user clicks "print" as well, since right now there's no special formatted stylesheet. @jonathanjnelson maybe you can link here to those designs just so Peggy is aware.

Additionally there is no logged in experience for this form, therefore no indication for a user to login.

**Comment by psanders86** [comment]
One question -- on the review page, does the privacy link go to this site? https://www.va.gov/privacy-policy/

**Comment by peggygannon** [comment]
Hi, @psanders86 
Yes, that privacy link goes to: 
https://www.va.gov/privacy-policy/
