### ISSUE TITLE
Toxic Exposure 1.1: Discovery for SiP and Review and Submit Alerts

### ISSUE THREAD

**Issue by christinec-fftc** [department-of-veterans-affairs/va.gov-team#85695]
## Overview
Look into whether we can customize these two areas of the form. 
1. SiP (save in progress)
Check if we can customize with this content for TE 1.1 when the conditions in the mock are met. We should make sure this content can continue to be customized in the future for other form changes. 

- The 'Continue your application' button should have dynamic logic. Redirect to the TE conditions page if: 1. have not filled out the TE conditions page and 2. they have not seen it yet (we'll need to add some kind of flag to remember this). Otherwise, use default redirect.

<img width="445" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d1f8227ad9173bf3288d6ecb11c5181631cd5ed/image.png" alt="image.png" />

2. Review and Submit
Check if we can add an alert to the top of the Review and Submit page. Should also be customizable.
<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFpVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2f326662e02b02d942f2fa6164ae1b09a9b1acb/image.png" alt="image.png" />

**Comment by christinec-fftc** [comment]
For #1 SiP on the Introduction Page
- This component is called the Save In Progress Intro component and lives in the platform folder ([link](https://github.com/department-of-veterans-affairs/vets-website/blob/dbex/83849-update-toxic-exposure-page-visibility-logic/src/platform/forms/save-in-progress/SaveInProgressIntro.jsx#L1)). 
- The platform component has a bunch of conditionals for different content in this alert including if logged in, saved vs expired form, prefill enabled with verification vs no verification, and finally a default (aka not signed in). This TE alert is not something we'd want to put into the platform code for all forms, but i do think we have another way of doing a customization. 
- Proposal: update 526's IntroductionPage to check if the appropriate TE 1.1 criteria is met. If it **is not met**, use the SiP component currently in use today. If the criteria **is met** show a new uniquely 526 alert component (from the mock). This will also allow us to not just customize the content but also customize the behavior of the continue button.
- The continue button is the bulk of the complexity. This is an edge case but we could have a situation where 
1. a Veteran sees the new SiP alert
2. clicks on 'Continue your application'
3. user is redirected to the 'toxic-exposure/conditions' page
4. user does not select any checkboxes. clicks Continue button
5. user fills out more of the form, say they get to the evidence chapter
6. user leaves the form and returns
Expected behavior: user is redirected to the evidence chapter and not the TE conditions page again. They should only be taken to the TE conditions page one time.
**Challenge**: because the TE conditions page has all optional fields, we can't rely on form data to know whether a Veteran has seen the first TE page.

**Comment by christinec-fftc** [comment]
### 2. Review and Submit

Found two configurable options for review and submit page. The first is a per page option to customize it's review field within the accordion (see [ui:objectViewField](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-about-schema-and-uischema#VAFormsLibrary-AboutschemaanduiSchema-ConfiguringuiSchemausingFormsLibraryoptions)). The other allows for a custom component underneath the accordions (see [preSubmitInfo](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-form-config-options#VAFormsLibrary-FormConfigOptions-preSubmitInfo). 

### Proposal 1
In order to add the alert before the accordion, looks like we'd have to modify the platform component to read in a new form config param for the custom component. Then we could build the custom component connected to the redux store to conditionally display the alert.
**Estimate:** Heavy lift since this isn't something we've done before and we're touching code that affects all forms. Size L

### Proposal 2
Add the alert below the accordion using existing preSubmitInfo option
**Estimate:** Much lighter lift. Several forms already doing something similar, but 526 is not currently utilizing this. Size S to M

**Comment by mengA6** [comment]
Created [Decide on approaches to implement for Toxic Exposure alerts announcing new questions to Veterans with in-progress forms#85977](https://app.zenhub.com/workspaces/disability-experience-63dbdb0a401c4400119d3a44/issues/gh/department-of-veterans-affairs/va.gov-team/85977) to make decisions based on this.

**Comment by pacerwow** [comment]
Thank you for the wonderful writeup, @christinec-fftc . Let's go with Proposal 2 on the Review and Submit page. Here's my reasoning:

- Elegantly handling edge cases for the SiP Intro Component is highly complex, and we could readily come up with additional edge cases.
- If the Vet clicks on the link in Proposal 2, they may miss sections of the form, and could forget to go back to complete them if they don't review the form closely on Review and Submit. 
- The logic for the SiP Intro Component is highly complex
- SiP Proposal 2 may require additional approvals, which we don't have time for... and it may not be the best idea to touch Platform code.
- Timeline; We have 2 sprints left before our target date to release TE 1.0 and we need to finalize the design in order to execute the implementation work.
- To meet the target date, Staging Review must be scheduled prior to the end of Sprint 35, ending July 16 (and Staging has to be unchanged for 4 days prior to Staging Review). If we go with Sip Proposals or Review and Submit Proposal 1, it's unlikely we'll be able to complete design and implementation before then.

- The UX on Review and Submit is the cleanest due to the simplicity of the interaction and redirect logic.
- As mentioned, several other forms are using this pattern, so this is well established and we could find support from others who have done it if needed.

CC: @mengA6

**Comment by mengA6** [comment]
See discussion [here in Slack](https://agilesix.slack.com/archives/C04MJV66ZPC/p1718910829649329?thread_ts=1718902962.121789&cid=C04MJV66ZPC)
