### ISSUE TITLE
Findability request for <VSignals FAQs>

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-team#85764]
# Template Instructions
- You are here to creation or change a Best Bet on VA.gov pages.

 -  Select Request Type:
    - [x] NEW: You would like to create a new best bet
    - [ ] CHANGE: You would like to change an existing best bet

- Post a link to this issue in Slack Channel #sitewide-content-ia and tag  @Jenny Mayo

### Description
Please provide a description and supporting information for the new best bet, or the existing best bet you want to change. Include any research or data you have to support the request. 

 The VSignals team created a list of FAQs based on common questions Veterans are asking on their calls. All of these Q&As already have content on VA.gov. So we discussed that it may be a matter of Veterans finding the information easily. I've listed the pages that relate to the questions being asked. Some of these may already be a best bet. 

###  Target Dates
Do you have any target dates we should be aware of?

 - 
 
### Specify the target page for the Best Bet 
What is the destination page for the best bet?
       
- https://www.va.gov/resources/signing-in-to-vagov/
- https://www.va.gov/disability/va-claim-exam/
- https://www.va.gov/disability/effective-date/
- https://www.va.gov/resources/non-compensable-disability/
- https://www.va.gov/decision-reviews/supplemental-claim/
- https://www.va.gov/get-help-from-accredited-representative/find-rep
- https://www.va.gov/health-care/health-needs-conditions/military-sexual-trauma/
- https://www.va.gov/disability/eligibility/

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

***Note: All requests will be reviewed against the [Search best bet standards](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/information-architecture/standards/search-best-bets.md) by the Sitewide Content, Accessibility, and IA team. Reach out via Slack #sitewide-content-ia with any questions.***

**Comment by jennymayoco** [comment]
Hey @RLHecht! I connected with Kristin on this to see how we can use the analytics template we created to inform best bets here. We decided to look at this as a findability request with recommendations that might include best bets as well as general IA recs that could help folks find this info more easily. Do you happen to have access to the FAQ you mentioned in the ticket?

**Comment by RLHecht** [comment]
@jennymayoco I just shared the sharepoint with you and Kristin. Here's a link: https://dvagov-my.sharepoint.com/:w:/r/personal/randi_hecht_va_gov/Documents/Apps/Microsoft%20Forms/VAgov%20intake%20request/Question/04.09.24%20Frequently%20Asked%20Questions%20Based%20on_Jacqueline%20Imboden.docx?d=w531f55ab9e9449ba97c1ccba0facd004&csf=1&web=1&e=nx7LFW

**Comment by jennymayoco** [comment]
Hi @RLHecht thank you for sharing the FAQ list! [Here is the spreadsheet](https://docs.google.com/spreadsheets/d/1PmsE7Q-B90ZFErooDa6je5AXeJrLnkaGmWcpvbRZjzI/edit?gid=1565273584#gid=1565273584) we used to document data as well as our recommendations. Some sections are missing as I wasn't able to pull data for those sections before GA4 transition.

Link | Recommendations | Action item | Who does it
-- | -- | -- | --
https://www.va.gov/resources/signing-in-to-vagov/ | There's already a best bet for this page | N/a | N/a
https://www.va.gov/disability/va-claim-exam/ | There's already a best bet for this page. I updated title and description to remove random characters | N/a | N/a
https://www.va.gov/disability/effective-date/ | There's already a best bet for this pageThe /how-to-file page has a section titled "Should I submit an intent to file form?" that references effective date. I think there a crosslinking opportunity here. It's also confusing what the effective date is for the disability claim because the page states that the effective date is set when you start the online application. It also is equated to ITF. This info isn't on the /effective-date page. We recommend confirming if ITF or starting an online app info is also a valid situation and adding that to this page | If adding content | CAIA
https://www.va.gov/resources/non-compensable-disability/ | Create best bet | Create best bet | Jenny
https://www.va.gov/decision-reviews/supplemental-claim/ | One of the FAQs was a general question around what is a supplemental claim. Since there's already a best bet for this link, we don't think there's a need for additional keywords. The other FAQ asks about submitting multiple supplemental claims. The response says yes if there's new evidence but that's not made clear on the benefit page. We recommend adding content to indicate this possibility on the benefit page | If adding content | CAIA
https://www.va.gov/get-help-from-accredited-representative/find-rep | Best bets are set up so I think we're good to leave as is since the CAIA recently added these | N/a | N/a
https://www.va.gov/health-care/health-needs-conditions/military-sexual-trauma/ | Add a keyword for "mst coordinator" since Veterans work closely with them to file a claim- Highest number of entries are from an r&s page and the highest number of exits are back to this page. The R&S page has more clear action for how to file using 526ez form. This isn't as clear on the benefit page. Should the main CTA be to apply for disability? |  Add keyword. Confirm if benefit page needs CTA to file for disability | Jenny, CAIA
https://www.va.gov/disability/eligibility/ | Since this page is in the top nav, high on the hub page and left nav, and has pretty high page views, we don't think this page needs a best bets. The FAQ relating to this page asks about a "service-connection", is there a probability that folks received a 0% disability rating? If so, I wonder if there's an opportunity to crosslink this R&S non-compensable page on the eligibility page | If adding crosslink to non-compensable page | CAIA
  | There was an FAQ on "why was my claimed condition deferred"? I didn't find anything in R&S or search so I wonder if this is a FAQ that can be created to help folks understand the status of their claimed condition |   |

**Comment by jennymayoco** [comment]
###  Jenny's to-dos based on recommendations up top
- [ ] Create best bet for /resources/non-compensable-disability
- [ ] Add keyword to existing best bet for /health-care/health-needs-conditions/military-sexual-trauma

**Comment by jennymayoco** [comment]
@RLHecht for `/resources/non-compensable-disability`, the metadescription exceeds the character limit and cuts off at 

> If you receive a 0% disability rating for a service-connected condition, we call this a non-compensable disability. It means you can't get disability compensation (payments) for this condition. But you may be eligible for other VA benefits. Find out what

What do you recommend to shorten it so it fits within the 255 character limit?

**Comment by jennymayoco** [comment]
Hi @RLHecht ! Checking in on this, are there any updates on the shortened metadescription for non-compensable disability?

**Comment by RLHecht** [comment]
sorry for the delay. Let me know if this fits:

If you receive a 0% disability rating for a service-connected condition, we call this a non-compensable disability. Find out what benefits you qualify for with a 0% disability rating and if you can file for an increased disability rating.

**Comment by jennymayoco** [comment]
That fits, thank you!! @RLHecht

**Comment by jennymayoco** [comment]
I've created the best bet for `/resources/non-compensable-disability/`. I shared the remaining recommendations up top, let me know if you have any questions! Happy to chat some more about other IA recs. Moving this ticket to closed
