### ISSUE TITLE
VSP QA feedback on Facility operating status [Staging Review]

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#8597]
### Links
**Test Plan / Execution logs:**
https://dsvavsp.testrail.io/index.php?/plans/view/245
**Coverage for References Report**
https://dsvavsp.testrail.io/index.php?/reports/view/62
**Summary (Defects) Report**
https://dsvavsp.testrail.io/index.php?/reports/view/63

### Feedback
**Test Plan**
1. TBD

**Test Execution Logs**
1. Not yet executed

**Coverage for References Report**
1. This is a "Summary for References Report" which is quite similar.  Instead of focusing on overall test coverage for references it is a representation of all references used in the test plan.
2. It appears based on this report that two test cases ([C419](https://dsvavsp.testrail.io/index.php?/cases/view/419) and [C430](https://dsvavsp.testrail.io/index.php?/cases/view/430)) do not have user stories / requirements to draw from.  If possible I recommend backfilling these references when possible.

**Summary (Defects) Report**
1. Test plan is not yet executed, so there are no defects to discuss.

## Definition of Done
- [ ] Acknowledge each item of feedback with a decision
- [ ] VSP QA will close ticket after reviewing feedback decisions

**Comment by mmiddaugh** [comment]
Thanks, @pjhill. 

I am quite confused by the expectations for this portion of the staging review. I went through the test cases and reviewed functionality but don't seem to be documenting well. I'll work with Tze to learn how to provide the requested artifacts. 

Rather than [245](https://dsvavsp.testrail.io/index.php?/plans/view/245), I ran [R318](https://dsvavsp.testrail.io/index.php?/runs/view/318&group_by=cases:section_id&group_order=asc&group_id=73)

[C419](https://dsvavsp.testrail.io/index.php?/cases/view/419) and [C430](https://dsvavsp.testrail.io/index.php?/cases/view/430) are both linked to https://github.com/department-of-veterans-affairs/va.gov-team/issues/7212 but neither is related to the Facility operating status. They must have been connected to this test rail in error. My apologies. 

I am confused about the requested report. You reference a "Coverage for References" Report, which I do not see listed. Should I be providing the "Comparison for References" Report? 

![image](https://user-images.githubusercontent.com/55411834/80737932-7ab98d00-8ad1-11ea-9e92-317a06278e55.png)

**Comment by pjhill** [comment]
I'm sorry I left your question at the end unanswered for so long!  You've probably figured this out already, but the report requested for these reviews is the "Coverage for References" report listed under the "Cases" section of reports.
![image](https://user-images.githubusercontent.com/52456633/87311111-d39f9b80-c4ec-11ea-810f-a51acc037b5b.png)
Please DM me on Slack if you have any more questions regarding TestRail, or if I can help you out in anyway -- I sometimes miss the email notifications for tags in GitHub.
