### ISSUE TITLE
[FE/QA] 10-10EZR Attach Docs: Discovery and Implementation -- Veteran with a saved in progress form 

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#85985]
As a Veteran, I would like to return to my in progress EZR form and be able to upload documents so that I can get more access to VA healthcare more quickly.

- [x] Investigate how SIP work with current build--when a SIP form created before attach docs see the attach docs once we have deployed Attach Docs?
- [x] If not, figure out how to make this happen and come up with next steps
- [x] Build this out
- [x] **Success: We have a plan for making sure SIP forms created before Attach Docs is deployed and we implement it so that Veterans will be able to see attach docs module when they return to their form.**

**Comment by mkerns1** [comment]
@IMHieuVo Should we get content involved with this?

**Comment by mkerns1** [comment]
Removed this AC: - [ ] Tweak content to alert to let user know they can now upload documentation due to the creation of [ticket #86919](https://app.zenhub.com/workspaces/10-10-health-apps-5fff0cfd1462b6000e320fc7/issues/gh/department-of-veterans-affairs/va.gov-team/86919) which addresses this based on feedback from @IMHieuVo and Sara.
