### ISSUE TITLE
10-10d: File upload update: require front and back of cards

### ISSUE THREAD

**Issue by marywang2** [department-of-veterans-affairs/va.gov-team#86230]
For 10-10d, require both front and back of cards in the file uploads section (to match OHI experience)

**Comment by michaelclement** [comment]
| |error message|
|-|-|
|Medicare AB|<img width="616" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOStJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7558175771b05fab856fc9e5d235a97327b7a0c1/Screenshot%202024-06-24%20at%2010.32.38.png" alt="Screenshot 2024-06-24 at 10.32.38.png" />|

**Comment by michaelclement** [comment]
@marywang2 PR has been merged, should be viewable on staging shortly. Thanks!

**Comment by marywang2** [comment]
@syd-hoeper (and @jamiefiore) for your review

**Comment by syd-hoeper** [comment]
@marywang2 I'm not seeing this updated -- it looks like the Medicare cards say "Required", but there's no "required" in red next to the upload prompt, and it allows me to move forward without uploading
<img width="846" alt="Screenshot 2024-06-27 at 8 49 42 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/151581608/b6df7d7f-056f-4826-8b68-130768698f11">

**Comment by marywang2** [comment]
@syd-hoeper if you add a file - it will require you to upload both front and back. (Having an upload be required at all is another question).

**Comment by syd-hoeper** [comment]
@marywang2 Okay looking now and while I think this entire pattern does not make sense and could use some work, it does meet the requirements outlined in this ticket.

I'd like to just document my concern here: I can see why we would want to require both documents, but I can see a scenario where a person has the front and back in the same file (aka me lol). Do we require that they are on separate pages? If we do not, I suggest we add a third option to the dropdown that is "front and back of card" and if they select that they aren't required to have two uploads.

Apart from that, the main issue I have is that there is no indication that both uploads are required until I hit the error message, which is a bad UX practice. As a user I need to know what is required of me up front in order to prevent errors, but it doesn't actually say anywhere that I need to upload two things:
<img width="489" alt="Screenshot 2024-06-27 at 9 49 53 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/151581608/f4f15420-210f-4df1-b26d-87f9db13bcde">
It just says that one is required. Then when I click continue I get the error:
<img width="477" alt="Screenshot 2024-06-27 at 9 51 05 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/151581608/af08c3fd-de04-4ec3-85ab-4f852db3c74f">
I'm sure y'all are over the back and forth of the designs at this point, so I'm going to assume that my suggestions won't be implemented at this time, but I do think this is something that we need to revisit -- either test it or rethink it because I very very strongly believe that this pattern, as it is now, is not a great experience for the user

**Comment by michaelclement** [comment]
@syd-hoeper I'm inclined to agree. Re your first comment, we don't have the red "required" text because the pattern is to only require the file if the user starts the upload process there, otherwise we let them go on until they reach the overall summary page that shows files yet to be uploaded. 

For your second comment, I do agree that it's not great - Unfortunately as far as I know we can't dynamically change the number of files required in the moment, though.
The way I see it we have two options here:
1. Update the language so users know they have to upload two files
2. Drop the requirement for two files

**Comment by marywang2** [comment]
Closing this one for now since it was completed. @jamiefiore @syd-hoeper let's regroup when Jamie's back and see what we want the experience to be and (if we can bundle in with any future 10-10d changes).
