### ISSUE TITLE
[Spike] Determine a method for tracking volume of appointments with fields returned with null state

### ISSUE THREAD

**Issue by JRRoof** [department-of-veterans-affairs/va.gov-team#86273]
## Background/Request
When appointment details are retrieved it is common for some of the fields to be returned without any data.  It is desirable to identify the fields and track the frequency at which it occurs.  The following are examples of fields that can be returned with null data.

- Null value for type of care for all appointment types
- Null value for the facility (but receive the facility ID) for all appointment types
- Null value for the facility (no facility ID) for all appointment types
- Null value for the clinic phone number for all appointment types
- Null values for the clinic phone number and facility phone number for all appointment types

### Goal

- Determine the frequency at which these fields contain null data
- Identify appointment types most likely to contain null data

### Requirements to Consider

---

## Tasks
- Answer the following questions:
  - Q  What percentage of appointments contain null data?
  - Q  What fields are most likely to contain null data?
  - Q  What percentage of the time does any of these fields contain null data?
         - Type of Care
         - Facility name
         - Facility ID
         - Clinic phone number
         - Facility phone number

## Time Box
10 hours

## Definition of Done
- Tasks are complete
- Research and recommendations are documented in this ticket

---
## How to configure this issue
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)

**Comment by JunTaoLuo** [comment]
I've taken a look at our codebase and I think we have most of the ingredients needed to address the above questions. Here are my current thoughts:

1. We choose to report statistics either on the BE or FE. For reporting, see 3.
  - i. If we decide to track these stats on the BE, we'll use [`StatsD`](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/services/vaos/middleware/vaos_logging.rb#L62-L70) like we do for [outbound request](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/services/vaos/middleware/vaos_logging.rb#L23-L42). At report time we'll use DataDog to query results and produce answers to the questions listed above. (See 3. for more details)
  - ii. I see the "backend" label is added but I still want to entertain the possibility of tracking stats on the FE. If the decision has already been made, we can ignore this option. If we decided to track on the FE, we'll use GA4 events similar to what we do for [fetch results](https://github.com/department-of-veterans-affairs/vets-website/blob/436ce04628d106e6c8673fd1b51dbb30807bf07b/src/applications/vaos/appointment-list/redux/actions.js#L191C15-L200). At report time we'll use GA interface to query for the results and produce answers to the questions listed above. 
2. Before appointment(s) are returned by the BE or on being received on the FE we will increment the following base metrics (naming TBD but included for strawman purposes):  
  - i. `{PREFIX}.total_appointments` incremented for each appointment
  - ii. `{PREFIX}.missing_type_of_care` incremented for each appointment without a type of care. [^1]
  - iii. `{PREFIX}.missing_facility_details` incremented for each appointment without a facility name or address but has a facility ID. [^2]
  - iv. `{PREFIX}.missing_facility_phone` incremented for each appointment without a facility phone but has a facility ID. [^3]
  - v. `{PREFIX}.missing_clinic_phone` incremented for each appointment without a clinic phone. [^4]
  - vi. `{PREFIX}.missing_facility_id` incremented for each appointment without a facility ID. [^5] Note that this would imply `missing_facility_details`, `missing_facility_phone`as well.
  - vii. `{PREFIX}.missing_any_field` incremented for each appointment that has at least one missing field (i.e. one or more of case ii - vi)
3. Base metrics will be queried via Datadog/GA to create the required synthetic measures for reporting:
  - i. What percentage of appointments contain null data?
  For a given timeframe, we can calculate this as `{PREFIX}.missing_any_field/{PREFIX}.total_appointments`
  - ii. What fields are most likely to contain null data?
    For a given timeframe, we can calculate this as whichever has the highest total: `{PREFIX}.missing_type_of_care`, `{PREFIX}.missing_facility_details`, `{PREFIX}.missing_facility_phone`, `{PREFIX}.missing_clinic_phone`, `{PREFIX}.missing_facility_id`.
  - iii. What percentage of the time does any of these fields contain null data? For a given timeframe, these can be computed as
    - Type of Care: `{PREFIX}.missing_type_of_care/{PREFIX}.total_appointments`
    - Facility name: `{PREFIX}.missing_facility_details/{PREFIX}.total_appointments`
    - Facility ID: `{PREFIX}.missing_facility_id/{PREFIX}.total_appointments`
    - Clinic phone number: `{PREFIX}.missing_clinic_phone/{PREFIX}.total_appointments`
    - Facility phone number: `{PREFIX}.missing_facility_phone/{PREFIX}.total_appointments`
    
Finally I have a few questions that I'm having trouble tracking down:
1. FE or BE metrics: This is a major decision which I'm not sure is already made. If not, what do we need to finalize our decision?
2. Type dependent null states: Although the request claimed that the requested null states are applicable for all appointment types, this is a little inaccurate. For example, for VA request and CC appointments, clinic details aren't expected to be present. To be precise in our measurements, we'll need to modify the base metrics to account for the fact that not each appointment expects all fields to be present. I have an approach in mind but I haven't included it at the moment since it might be confusing. 
3. Additional null states: For example, in several appointment types, we display the provider if the information is available but I didn't see this in the request above. Are we not tracking this because it could be optional? Also consider "Reason" and "Other details".

And I do have a few recommendations:
1. If we decide to track these metrics on the BE, we should consider doing this after moving some more transformer/selector/getter logic from the FE to the BE. That would likely reduce the amount of duplication of logic between FE and BE significantly.
2. If we decide to track these metrics on the FE, we might need more people to get GA access before we start the work on the engineering side.

Footnotes:
[^1]: On the BE, we'll need to duplicate/move [this logic](https://github.com/department-of-veterans-affairs/vets-website/blob/620b4f7613aaf11952108dc900528c735946f299/src/applications/vaos/appointment-list/redux/selectors.js#L282-L294) from the FE.
[^2]: On the BE, this information is stored in `appt[:location][:attributes][:name]`, `appt[:location][:attributes][:physicalAddress]`
[^3]: On the BE, this information is stored in `appt[:location][:attributes][:phone][:main]`
[^4]: On the BE, this information is stored in `appt[:extension][:clinic][:phoneNumber]`
[^5]: On the BE, we'll need to duplicate/move [this logic](https://github.com/department-of-veterans-affairs/vets-website/blob/620b4f7613aaf11952108dc900528c735946f299/src/applications/vaos/services/appointment/index.js#L256-L276) from the FE.

**Comment by JRRoof** [comment]
For event naming in GA4, please start all event names with _vaos_ and use a dash as a separator.  
     For example: _vaos-new-appointment-list_
This is needed for filtering when creating reports and dashboards.

1. FE or BE metrics: This is a major decision which I'm not sure is already made. If not, what do we need to finalize our decision?
_No decision has been made.  Doing this in the FE would allow PM and others to query results easily._

2. Type dependent null states: Although the request claimed that the requested null states are applicable for all appointment types, this is a little inaccurate. For example, for VA request and CC appointments, clinic details aren't expected to be present. To be precise in our measurements, we'll need to modify the base metrics to account for the fact that not each appointment expects all fields to be present. I have an approach in mind but I haven't included it at the moment since it might be confusing.
_Good point.  Agreed._

3. Additional null states: For example, in several appointment types, we display the provider if the information is available but I didn't see this in the request above. Are we not tracking this because it could be optional? Also consider "Reason" and "Other details".
_We know that the provider is not always available.  This is related to the type of care or modality of the appointment.  PM would like to understand under which types of care and/or modalities we receive/don't receive the provider name._

**Comment by JunTaoLuo** [comment]
@JRRoof I've updated the recommendations above but I also had two more questions, can you take a look? Q4 needs some guidance from PMs but Q5 is a bit more technical/engineering leaning so feel free to let me know if it's not relevant for this spike ticket.

**Comment by JRRoof** [comment]
4. I'm unsure how to track the metrics for CC appointment and requests. For CC appointment, we display provider address and provider phone, which is functionally similar to facility details and facility phone. The question is whether we should use the facility metrics for these null states or use separate ones (i.e. vaos-null-states-missing-provider-details, vaos-null-states-expected-provider-details, vaos-null-states-missing-provider-phone, vaos-null-states-expected-provider-phone)? The same goes for CC requests which displays provider address.
_The CC data we receive from HSRM is better than other sources, like VistA.  I'm less concerned about CC data, so this is something that could be looked at later._
5. I think instead of reporting these metrics when appointments are received from the BE, it actually makes more sense to report them when appointment details are displayed. 
_Agreed.  Reporting on appointment details is the preferred approach._

**Comment by JunTaoLuo** [comment]
Thanks @JRRoof! The findings are updated and I'm ready to file engineering work tickets.

**Comment by JunTaoLuo** [comment]
@ldelacosta I'm just wondering why this has been moved to External Dependencies and had the high priority tag added?

**Comment by ldelacosta** [comment]
@JunTaoLuo  Removed the high priority tagged. I moved it to External Dependencies for now. Wanted to check in with @JRRoof when he's back to make sure. we are good to close. Plan to close it out by EOD Tuesday.

**Comment by JRRoof** [comment]
No external dependencies, closing out the ticket.
