### ISSUE TITLE
[Team] 10-10EZR TERA: Discovery -- Can we pre-populate/display TERA answers/eligibility?

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#86399]
As a Veteran, I would like to know if I have answered the TERA questions and they have been recieved and processed by VA so that I don't have to answer them again.

- [x] Work with VES to determine what, if any, TERA info we can get back on the Veteran (and how complete that info is)
- [x] Based on that, determine if it's worth it to display to the Veteran
- [ ] If it's worth it, come up with a proposal for how to display this info and how the workflow will go (Visual and workflow--can be high level)
- [ ] **Success: We have determined if we can, and should, display TERA answers/eligibility.*

**Comment by JoshingYou1** [comment]
https://dsva.slack.com/archives/C06FDF2EN0H/p1716563549828229

**Comment by IMHieuVo** [comment]
**PAINPOINT:** 
- TERA painpoint: There are at least (4) different locations where the Vetearns are asked about TERA but we cannot pre-filled their previous answer for them.
- See Lois’s TERA mural: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1717705233693/dfef1c5648f761c3ac1d1cb856f56b551060e65c?sender=ubf5503bf47b6eb1e92730053 

**The current process:**
- Veterans opt-ins into the TERA questions, answers them, HEC uses the responses to determine eligibility 
Note: HEC does not take the response as fact, the intent of these responses and documents is to help HEC in the TERA review process.
- There is no TERA individual-answer data in the backend system, so we cannot prefill previous answers (the team is not exactly sure why).

**Summary and recommendations:**
- We currently cannot pre-prefill previous answers from other systems. 
- Is it worth it to display eligibility to the veteran and where?
- If we were to display eligibility, the TERA intro screen would be the most logical place. 
- **I recommend against simply displaying eligibility because the HEC intent of TERA is to bring Vetearns above Priority Group 6 and extra is useful in case TERA’s definition expands later. So historical answers may play a role down the line**.
- With each department/service collecting the TERA questions into different backend systems (VISTA, VES, Oracle, etc), is it even possible to have an ideal flow where Veterans only have to answer it one time then it is pre-filled the other times?
- At a minimum, TERA response in EZ should pre-fill in EZR. We should push for the VES to collect TERA info in a while so we can pre-fill.
