### ISSUE TITLE
Eng discovery: Acct Creation API requirements for MHV-on-VAgov apps

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#86801]
### User story

As a Cartography team member, I want to understand how the addition of a call to the MHV Acct Creation API to the sign-in flow will affect the UX of MHV-on-VAgov apps, particularly around authorization and error messaging, so that we can suggest requirements to the Identity and MHV teams to make sure Veteran UX will make the best use of the new API.

### Notes
- Meeting with Patrick scheduled for Thurs 6/27
- Topics to consider
  - Fields MHV apps will need from the API the MHV team is building – both happy path and errors
  - What the various error cases will mean from the MHV backend perspective (so that we can communicate later to UXers)
  - What assumptions should we make about how quickly the API call will come back with up-to-date info on the user? On every sign-in or will vets-api sometimes send cached data to us?

Possible tasks:
- Meet with Joe Niquette about needs from our team, process, etc

## Acceptance criteria

- Discussed scenarios with Joe and how they could affect UX of MHV Home and tools
- Documented which API errors would need to be accommodated by UX

**Comment by carlosfelix2** [comment]
Document with notes from account creation API meeting: https://docs.google.com/document/d/1QyP0x3pRYjVjrZC0SGj7MXhnitvPXq80s4l10ZH81go/edit?usp=sharing

**Comment by carlosfelix2** [comment]
Initial brainstorming of requirements for API: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581177532/3cbc80571562a1f162a0887c4a60e06c3014f99a?sender=u0bae2cc7dcef022d3fc90742

**Comment by carlosfelix2** [comment]
From: Bateman, Patrick F. <[Patrick.Bateman@va.gov](mailto:Patrick.Bateman@va.gov)>
Sent: Monday, July 8, 2024 3:02 PM

- MHV Access team will deliver formal requirements / design decisions to VA.gov Identity team by end of this week (7/12)
- Expectation is that this will include the directive to only call the account creation API when 200MH is not found in MPI attributes
- MHV Access team will target beginning of August (~8/5) for delivery of initial "90-95% solution" to be available in lower environment(s)
- VA.gov Identity team will target end of August (~8/30) for completion of VA.gov integration
- MHV Access team and VA.gov Identity team will collaboratively develop a test plan, targeting end of August (~8/30) for completion
- MHV Access team and VA.gov Identity team will test account creation API integration during September
- MHV Access team and VA.gov Identity team will incrementally release functionality to production around beginning of October (~10/1)

This assumes that the account creation API work will be prioritized for the MHV Access team in the upcoming program increment.

Outstanding question:
(To be answered by MHV Access team) Should the account creation API be called when users are signing into MHV National Portal using Option 1?

**Comment by carlosfelix2** [comment]
@batemapf mentioned that based on the current path that 
> Correct, that is my understanding based on the recent conversations. Everything should happen as part of the sign in process, and the result of that should be used by individual apps.

**Comment by carlosfelix2** [comment]
Joe Niquette is a good POC for the VA.gov Platform Identity team

**Comment by carlosfelix2** [comment]
From Joe on the current plan for the account API integration:
- plan to look for the ability to create an MHV account upon every login
- We will also make available a call for apps to use if they want to try and make the account creation api call in the middle of a user session. 
  - your app will need to look at the user object (or some other object made for this) to see that the user has an MHV IEN 
  - @carlosfelix2 - I am unsure how this can be used if the call is made already at login
- we dont plan to expose the errors to apps right now, but its something we can consider if there is a use case for this
  - We currently plan to run the account creation api as a sidekiq job at the start of a successful login by the user. Any errors will be written to datadog and sentry
- The user will not be presented with an alert [upon a failure from the account API]
  - I think there may be some use cases on [va.gov](http://va.gov/) where the user logs in and immediately goes to an app that requires the MHV account be present. We could add something that allows the apps on [va.gov](http://va.gov/) to see that a request is pending and then  show the user a wait screen
  - This wait screen I think we would like your team to make this and allow for it to be re-used for all mhv apps on [va.gov](http://va.gov/)
- we plan to not interact with any apps at all. We will make the call to the account creation api according to the requirements given to us by MHV. We will then store the user information needed for the MHV apps on [va.gov](http://va.gov/) into an object accessible by the backend (we could make it available to the frontend too). Otherwise we will not be tracking how teams use the resulting information from the account creation api. We would like to try and make it so none of the apps ever need to care about the api or that its being called. We just want to present the data thats needed to the app when they need it.

**Comment by wesrowe** [comment]
In a standup at the end of last week, we identified the need to get the intended API workflow (ie all the errors that can be thrown) so that we can study them through a UX lens. @carlosfelix2 took the action item to request it.

The UX team doesn't yet need to actually design how the portal experience should handle the various possible outcomes of the API call. (That will come later, when we understand how the integration has been built.) Right now, we need to determine if any of the error cases need to be passed to the MHV portal to influence the UX.

cc @fmccaf1

**Comment by carlosfelix2** [comment]
Latest is that the teams will try to get everyone together for a meeting to bring up all the new info and schedule.

**Comment by carlosfelix2** [comment]
Please see links below for Account Creation API Specs. The first link contains most of the relevant information.

- https://confluence.devops.va.gov/display/VAExternal/Account+Creation+API+Spec
- https://confluence.devops.va.gov/display/VAExternal/Account+Creation+API+User+Stories
- https://confluence.devops.va.gov/display/VAExternal/Check+MHV+Account+API+-+Quick+Check

**Comment by LynneJohnson224** [comment]
@wesrowe @carlosfelix2 can this close?
