### ISSUE TITLE
PW intake: Left nav for family member benefits hub from Sitewide CAIA

### ISSUE THREAD

**Issue by laurwill** [department-of-veterans-affairs/va.gov-team#86962]
### Indicate if you need front-end engineering support for

- [ ] Content audit
- [ ] Implementation of REACT sign-in widgets
- [ ] Support for UAT testing or phased roll out of app/tool landing page
- [ ] Implementation of Translation widgets
- [X] Something else

### Describe your request

We published the new family and caregiver benefits hub page and related child pages on Monday 6/24. Tim Cosgrove from CMS team is creating a new menu for this hub, so that we can assign the child pages to the intended left nav structure. 

Now we need PW help to understand and complete any other steps needed to make the left nav display in the new hub.

### Time constraints / launch deadlines

The pages are already live and redirects are happening tomorrow 6/25, so as soon as you can fit this in, but we understand this is an unplanned request. Apologies for not opening this earlier, I very much underestimated the work needed to set up a new hub.

### Your product/team Slack channel

#sitewide-content-accessibility-ia
**THREAD**:  Use this thread for comms with CAIA: https://dsva.slack.com/archives/C01K37HRUAH/p1719332572216609

### Your OCTODE product owner

Danielle Thierry

## ACs

- [x] documentation is added to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/teams/sitewide-content/how-to-do-different-tasks/adding-left-nav-and-url.md with steps for how it works to create new left nav for a Benefit Hub 
- [x] Testing in Tugboat successfully renders the left nav on the new benefit hub in FE before merge
  - [x] Ping Laura Willwerth on this thread: https://dsva.slack.com/archives/C01K37HRUAH/p1719332572216609, and ask her to preview / sign off - https://dsva.slack.com/archives/C01K37HRUAH/p1720202664619519?thread_ts=1719332572.216609&cid=C01K37HRUAH
- [x] After merge / deploy: Left nav appears correctly on new Benefit Hub in prod

**Comment by FranECross** [comment]
@laurwill Thanks for creating the ticket and alerting us! I'll get this poised to possibly be pulled into the sprint starting today, if there's room and the team can async refine it. cc @jilladams @mmiddaugh 

@chriskim2311 @dsasser  I'm not sure if this is an FE or Drupal ticket, and was wondering whichever it is, can one of you async refine it sometime this week so that we can have it in Stretch/Next Sprint as a possible stretch goal for Sprint 7? Thanks!

**Comment by dsasser** [comment]
Engineering notes:

Once the CMS changes are done by Tim, the work is 100% FE, and involves:

- Adding the menu to hubNavNames.json
- Adding the GraphQL query for the menu in Sidebar.nav.graphql.js
- Add the sidebar to the page template data in src/site/stages/build/drupal/individual-queries.js (at line ~192)
- Add the sidebar template to the base page template, if not already present.

Overall I would point this work at a 5 (3 for the dev work and a 1 or 2 for testing/qa).

**Comment by jilladams** [comment]
PR has been merged that creates the necessary menu in config: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18395

**Comment by laurwill** [comment]
cc @kristinoletmuskat for awareness of left nav process :)

**Comment by jilladams** [comment]
Added an AC here to get Laura Willwerth's explicit review /signoff in tugboat before this ships.

**Comment by laurwill** [comment]
I built the left nav menu in Drupal, so it's ready for testing: https://prod.cms.va.gov/admin/structure/menu/manage/family-and-caregiver-benefits

**Comment by laurwill** [comment]
Hi @jilladams , I'm OOO next week 7/1-7/5, so if this fix happens while I'm out, @kristinoletmuskat will be available for review/signoff of the left nav in Tugboat. 

Neither of us have used Tugboat before—is this something we can review over a screenshare? 

Thank you again so much for your help with this!

**Comment by jilladams** [comment]
Yes, we realized yesterday that y'all won't have Tugboat access without SOCKS so we can provide screenshots (or do a screenshare), either way. (FYI @kristinoletmuskat )

**Comment by dsasser** [comment]
## Mid Sprint Update 7/3/24

Status: PR is up and I have a Tugboat setup with the changes applied there.

A couple things to note:

- The structure of the hub menu matters. The current menu (screenshot below) structure needed to be re-organized in order to have the sidebar display correctly. So the Tugboat menu has been reorganized. I made as assumption, based on other benefit hubs, as to what the top level accordion label should be named. I chose 'Get benefits'.
- There are a few breadcrumbs that don't look correct (screenshot below). This may need some discovery, as I couldn't immediately determine why the breadcrumbs are off (it is a Drupal concern, and most likely a content change).

![screencapture-prod-cms-va-gov-admin-structure-menu-manage-family-and-caregiver-benefits-2024-07-03-09_58_23](https://github.com/department-of-veterans-affairs/va.gov-team/assets/221539/fd7a6275-1290-4ebb-8cc3-95a481e09887)
![screencapture-main-cxx409f6boe4hw9loluqkm4f2kwclllf-demo-cms-va-gov-admin-structure-menu-manage-family-and-caregiver-benefits-2024-07-03-09_59_28](https://github.com/department-of-veterans-affairs/va.gov-team/assets/221539/60193728-dc01-44ac-acbf-a5d5afa5d970)
<img width="1143" alt="Screenshot 2024-07-03 at 10 12 41 AM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/221539/f499cd37-885e-4234-a008-9c544f58f04b">
<img width="1427" alt="sidebar-menu-structure" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/221539/47bcf0a6-6290-4414-832e-3897e78cfdea">
![Screenshot 2024-07-01 at 12 44 32 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/221539/7c07c054-dc62-49b5-b15e-03fa48d55b7d)

**Comment by kristinoletmuskat** [comment]
Hi @dsasser , thank you so much for these screenshots! 

To confirm, that Second Level menu item (Get Benefits) -- we have to have that?

Here is the nesting we were going for in the first section, health and disability benefits. So other than what you have above, we also need an 'Apply now' link that links to the [PCAFC form](https://www.va.gov/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg/introduction) (which does not live in drupal)
![Screenshot 2024-07-03 at 12 20 18 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/122126772/4656fef6-5e24-4d71-b79e-c7409b9397aa)

The breadcrumb is part of an ongoing issue documented in this [PW ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18412). 

@jilladams FYI the broken breadcrumb is appearing in this tugboat instance, looking like it might impact all the pages in the structure?

**Comment by dsasser** [comment]
@kristinoletmuskat 

> To confirm, that Second Level menu item (Get Benefits) -- we have to have that?

Yes that level is required. It doesn't need to be named 'Get benefits' however. Similar hub menus have 'Get benefits', 'Manage benefits', and 'More resources' at that level. See https://staging.cms.va.gov/admin/structure/menu/manage/disability-benefits-hub.

**Comment by dsasser** [comment]
Laura Willwerth has been asked to review the demo [here](https://dsva.slack.com/archives/C01K37HRUAH/p1720197516465399?thread_ts=1719332572.216609&cid=C01K37HRUAH).

**Comment by kristinoletmuskat** [comment]
@dsasser we can use 'get benefits' for that second level for now!

**Comment by dsasser** [comment]
I changed the menu in production, adding the 'Get benefits' level, and disabling the 'Apply now' link:
![Screenshot 2024-07-08 at 11 45 05 AM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/221539/695dd1a2-91eb-437e-8b74-c7bf1aca96a1)

**Comment by kristinoletmuskat** [comment]
Thank you for adding the 'Get Benefits'! We do want the 'apply now' to be nested under the Program of Comprehensive Assistance for Family Caregivers -- are you able to nest that in there @dsasser ?

**Comment by dsasser** [comment]
> Thank you for adding the 'Get Benefits'! We do want the 'apply now' to be nested under the Program of Comprehensive Assistance for Family Caregivers -- are you able to nest that in there @dsasser ?

Yes! Is this what you are after?
![Screenshot 2024-07-08 at 1 34 58 PM](https://github.com/department-of-veterans-affairs/va.gov-team/assets/221539/0d82a2d1-7a1a-4739-8d8c-89cf6a476dfe)

**Comment by kristinoletmuskat** [comment]
@dsasser yes! And then the spanish link -- that will only show if the toggle is selected, right? I know we had another ticket for the spanish toggles here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/84625

**Comment by dsasser** [comment]
@kristinoletmuskat that is correct, once https://github.com/department-of-veterans-affairs/va.gov-team/issues/84625 ships the Spanish toggle will be displayed and the Spanish link along with it.

**Comment by kristinoletmuskat** [comment]
Ok! I think it's ok to publish with the spanish page for now while PW works on the toggles.

**Comment by jilladams** [comment]
@kristinoletmuskat clarifying: it seems like the requirements in this ticket are met, and the left nav is appearing in Prod. e.g.: https://www.va.gov/family-and-caregiver-benefits/health-and-disability/

I would like to close this, and track any further updates related to translation in that other ticket https://github.com/department-of-veterans-affairs/va.gov-team/issues/84625. Does anyone on here (@kristinoletmuskat @dsasser ?) object?

**Comment by kristinoletmuskat** [comment]
Yes that's fine! @jilladams
