### ISSUE TITLE
Post-vets.gov repo migration broken links

### ISSUE THREAD

**Issue by ricetj** [department-of-veterans-affairs/va.gov-team#8716]
## Please describe your documentation feedback, describe your request, or ask your question here: 

Looking through some of the Engineering docs more specifically the [infra](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/engineering/infrastructure) one. Most of the links in the TOC  just link back to this page. I went to the [vets.gov repo](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Practice%20Areas/Engineering/Infrastructure) to see and it looks like some of those files may be in the sensitive repo now. Some of the docs like this [one](https://github.com/department-of-veterans-affairs/vets.gov-team/tree/master/Products/Platform/Infrastructure) I think didn't make the migration to va.gov-team repo. 

### _What happens now?_ 
The docs are not discoverable or not migrated.

**Comment by gmaciolek** [comment]
Hi TJ, sorry for the delayed response on this! I'm just now going through old documentation tickets and doing some cleanup and found this one.

I am vaguely familiar with the va.gov-team repo migration prior to my joining VSP. At this point, it would probably be best for people within the practice area that owns/maintains a doc to address any broken links or migrate any missing docs on a case-by-case basis. We don't have plans to do any further post-migration cleanup in our roadmap. Let me know if you disagree or if I'm missing some context since this issue predates my involvement.

**Comment by gmaciolek** [comment]
Closing this one out. We will evaluate broken links as part of current and future documentation initiatives. In the meantime, teams that own/maintain docs can address any broken link issues in their own docs.
