### ISSUE TITLE
Research: Document the various options of patterns

### ISSUE THREAD

**Issue by megansiddle** [department-of-veterans-affairs/va.gov-team#87206]
create documentation based on our types and patterns

**Comment by rhasselle-oddball** [comment]
Status update:
- Been experimenting with auto generating docs using jsdocs, with our existing types.
- I've been making some assumptions as I've go, such as trying to create custom integration documentation for the form builder team, but got some alignment after meeting with Nick and form builder team.
- Met with Nick and form builder team, and decided not to create new custom documentation to try to integrate with form builder team. Ultimately that's their responsibility, and creating custom documentation will lead to multiple sources of truth. Everyone agreed that was best.
- Instead regular documentation on our existing types is still helpful.
- However another problem is: jsdocs can't produce nice documentation for many of our existing types because they are too complex, leaving the value of many types equivalent to just looking at the code. Form builder said their approach is looking at code first anyways, making me wonder the value of all this after all. 
- Another problem is the current approach with using jsdocs, is can it be put in a public place versus just locally? Meeting with a devops engineer today to query about that.

**Comment by rhasselle-oddball** [comment]
Update:
Work is basically finished. However, now I'm uncertain about committing this after going through the whole experience and learning how jsdocs works with its documentation.
Basically, we get nice docs for all of our types.... but at the expense of some worse dev experience with our intellisense. For example, today when you hover over anything, it tells you exactly what it does. However with the new changes, everything had to be broken and up into small pieces, so you can no longer see exactly what you're getting when you hover it, so it basically obscures what is happening for a lot of our types, so you have to dig into each type definition to find out.
I value dev experience so I feel conflicted.

**Comment by rhasselle-oddball** [comment]
Research summary:
PR example: https://github.com/department-of-veterans-affairs/vets-website/compare/main...docs-patterns
This uses jsdocs with docdash.
This can be used to document all of our types. But we have to refactor to very modular types that use no inline anonymous functions, and don't use unions or intersections. This makes dev experience worse, so choosing not to commit this. Instead, let's update existing documentation on how to look at and read types.
