### ISSUE TITLE
SPIKE: Can we Update Mocks for Scenario

### ISSUE THREAD

**Issue by loripusey** [department-of-veterans-affairs/va.gov-team#87414]
## Question to Answer
Can we simulate in one of the mocks selecting "go back to today's appts" after checking in and seeing the task card removed and the appt changed to "you're checked in"? Or, no, we can't do that right now? (I'm assuming no, but just wanted to double check. Could use a mock to demonstrate this. E.g., you're checked in to your appt already after authentication.)

**Comment by brianseek** [comment]
@loripusey  Instead of just saying "no" right away, I decided to explore this a little bit. We have known that trying to do dynamic or stateful things with mock-api is not really possible, but I tried a few things to trick it into working for this scenario. The bad news is that I couldn't really get it to work in a way that I was satisfied with. I did get it to work, but only by passing extra data through the request, and adding test data is not something I want to do with in-prod code.

One way where this is possible-ish is in our Cypress tests. We don't have a current test for this but [here is a ticket](https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/87721) for it. So you can test this in action locally by running Cypress once that work is done. Does that solve the problem here? 

One issue with Cypress is that it runs super fast and you can’t really see what is going on. If that is an issue for you, we can explore adding a library to our dev-dependencies that will conditionally slow the tests down on local if you pass a parameter to the command. The you would be able to see things in closer to real time. Let me know if that is worth exploring.

**Comment by loripusey** [comment]
Sounds good, we can include the ticket above in the next sprint, closing this one
