### ISSUE TITLE
Flipper UI access for Alex Chan

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#87595]
### Your Name

Alex Chan

### Your GitHub handle (Flipper UI access is managed through GitHub)

@alexchan-va

### Team, Role, and Company of the target individual

VFEP, GovCIO, Backend Dev

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

As a developer, Alex Chan will need access to create/ and toggle Flipper toggles

**Comment by bdech** [comment]
@jsimonVA Alex Chan is not a member in Atlas. In order to receive access to Flipper Alex must go through [platform orientation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D).

**Comment by jsimonVA** [comment]
@bdech  Oh, I thought this put him in Atlas. https://github.com/department-of-veterans-affairs/va.gov-team/issues/85588

**Comment by bdech** [comment]
Yea, my mistake, was looking in the wrong environment

**Comment by bdech** [comment]
Alex Chan has been granted access to `lower` and `production` environments
