### ISSUE TITLE
Flipper UI access for Chad Chotikasatien

### ISSUE THREAD

**Issue by jsimonVA** [department-of-veterans-affairs/va.gov-team#87596]
### Your Name

Chad Chotikasatien

### Your GitHub handle (Flipper UI access is managed through GitHub)

@govcioChad

### Team, Role, and Company of the target individual

VFEP, GovCIO, Frontend Dev

### Please confirm if you are on Atlas, Platform Team Roster or are a Federal User

- [X] [Atlas](https://dev.va.gov/atlas)
- [ ] [Platform Team Roster](https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster)
- [ ] Federal User (Bill Chapman will need to confirm)

### Flipper UI Access requested for the following environments

- [X] Lesser Environments (Dev/Staging/Sandbox)
- [X] Production (if requesting, justify prod access below)

### Reason for Production Access (If requested)

As a developer,  Chad Chotikasatien will need access to create/ and toggle Flipper toggles

**Comment by bdech** [comment]
@jsimonVA Chad Chotikasatien is not a member in Atlas. In order to receive access to Flipper Chad must go through [platform orientation](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=platform-orientation%2C+new-vfs-team-member%2C+platform-tech-team-support&projects=&template=orientation-epic.md&title=New+VFS+Team+Member+Template+%5BYour+name+here%5D).

**Comment by jsimonVA** [comment]
@bdech  https://github.com/department-of-veterans-affairs/va.gov-team/issues/79654

**Comment by jsimonVA** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-team/assets/88905347/96854516-4bba-4496-bb02-533fabf2ff25)
This means that he is added, yes?

**Comment by bdech** [comment]
@govcioChad You've been granted access to `production, and `lower` environments.
