### ISSUE TITLE
Drupal Update to support Static Landing Page for 686 Changes (eBenefits)

### ISSUE THREAD

**Issue by stephorkandatx** [department-of-veterans-affairs/va.gov-team#8804]
In order to complete our support of the desired changes for the static landing page for the 686 changes, please make the necessary updates in Drupal to set up the new React widget.

**Tasks**
(details of the widget are in #8115 )
- [ ] Set up a new React widget with type 686UnauthContentBlock , on /disability/add-remove-dependent/ (confirm that is the correct page by cross-referencing changes in #8114 )
- [ ] The placement and set-up of the widget should mirror the mock-ups https://xd.adobe.com/view/8cdfe895-c907-4662-7234-305056778b2a-faee/

Big note: In #8114 "We would like this link: /disability/add-remove-dependent changed to reflect the content on this mockup and made to this url: /view-change-dependents/. Please note that the disability hub has been removed; this will simply be off the root." Depending on which ticket is completed first, we will need to be aware of the page we are updating

**Comment by lunascoop** [comment]
Draft copy should be complete by 06/03 for review w/team.

**Comment by MickinSahni** [comment]
Pulling into backlog until this is ready to be committed to.

**Comment by DanielleThierryUSDSVA** [comment]
## How to view current dependents

You can use our online tool to review the current dependents you've added to your VA disability benefits. To do this, you need to be signed in to VA.gov with a verified account.


_**Note:** From my understanding, to "change" a dependent from inside the view dependents tool, you would need to click through to go to eBenefits, correct? Since we give the instructions to go to eBenefits directly below, I think it's just confusing to try to also work it into the view dependents piece._

**Comment by DanielleThierryUSDSVA** [comment]
@bethpotts If the above looks good to you, please share with Selina. Thanks!

**Comment by lunascoop** [comment]
@DanielleSoCompany @bethpotts 
A quick question about the second sentence:
This text will be shown on the both the unauthenticated and authenticated experience. Is the second sentence necessary/applicable for authenticated users since they'll already be signed in?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @lunascoop. Great question. Yes, it's worded this way of "you need to be signed in" instead of "you'll need to sign in" so it can work across both states. Thanks!

**Comment by MickinSahni** [comment]
@lunascoop to confirm whether this can be closed as won't do
