### ISSUE TITLE
Update userflow

### ISSUE THREAD

**Issue by benbrasso-agile6** [department-of-veterans-affairs/va.gov-team#88086]
## Tasks

- [ ] Update userflow based on [initial userflow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1695774555765/73dec2c323f80ae6cb2a6e0a646221e2aeb680c4?sender=u37bb983bd3fc3cc00c7d3286) and [wireframes](https://www.figma.com/design/7Ib7RxiIC4QB53FDBO2a8c/Unified-check-in-%7C-PCI?node-id=0-17259)

**Comment by benbrasso-agile6** [comment]
@loripusey I created this ticket. We will also need to include a line item in sprint goals to schedule design intent and create CAIA ticket for IA and content review.

**Comment by benbrasso-agile6** [comment]
If you want to start the collab cycle kickoff process. That would be good. We'll be able to schedule design intent pretty quickly.

**Comment by benbrasso-agile6** [comment]
Actually, we might need to wait on collab cycle; I wonder if we can pair with BTSSS so it's just one collab cycle.

**Comment by benbrasso-agile6** [comment]
@zach-park @cgednalske rdy for validation https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1722263210448/33062955940eb08d097dbd88a8dc98488ac2ffcc?sender=u37bb983bd3fc3cc00c7d3286

**Comment by cgednalske** [comment]
@benbrasso-agile6 This is looking really thorough! 👍 I can't comment still 😞 (high on my list to take care of), so adding my comments here. 

- For the details page - we currently have paths that go to no "BT information," but I'm wondering if it's helpful to have something about BT for the appointments that don't offer it as well - namely to say BT is not available and give a little info on why. We didn't test this previously since we were focusing on only one appointment type, but atm I'm hypothesizing that it's also helpful to know if/why it's not available. Thoughts?

- For "Veteran is told that they'll receive a confirmation text message," do we need to consider a text OR email message depending on preferences? And what if they are opted out of notifications all together? Do we need info that tells them to check the claim status after a certain amount of time?

- Do we need any No path for "did the claim make it into BTSSS via BTSSS API?"

**Comment by benbrasso-agile6** [comment]
> For the details page - we currently have paths that go to no "BT information," but I'm wondering if it's helpful to have something about BT for the appointments that don't offer it as well - namely to say BT is not available and give a little info on why. We didn't test this previously since we were focusing on only one appointment type, but atm I'm hypothesizing that it's also helpful to know if/why it's not available. Thoughts?

I'm going to add this comment in and tag Peter on it for his thoughts.

**Comment by benbrasso-agile6** [comment]
> For "Veteran is told that they'll receive a confirmation text message," do we need to consider a text OR email message depending on preferences? And what if they are opted out of notifications all together? Do we need info that tells them to check the claim status after a certain amount of time?

For BTSSS FE Team to make some decisions. They might even wait until the API is better where a text message is not needed.

**Comment by benbrasso-agile6** [comment]
> Do we need any No path for "did the claim make it into BTSSS via BTSSS API?"

I think so. Let me fix.
