### ISSUE TITLE
Access for Jon Kislin

### ISSUE THREAD

**Issue by nelabdiel** [department-of-veterans-affairs/va.gov-team#8812]
# Description
- Please provide your Contracting Officer's Representative (COR) name.
   > Erick Zenteno, Erick.Zenteno@va.gov

- Please provide your name.
   > Jonathan Kislin 
   > Andrew Spiegelman
   > Dan Fein
   > Mokeli Pelamoko
   > John Horton
   > Megan Savel Hawryluk
   > Michael Macmahon
   (Submitted by Nelson Colon Vargas)

- Please Provide your email.
   > jonathan.kislin@va.gov 
   > Andrew.Spiegelman@va.gov
   > Daniel.Fein@va.gov
   > Mokeli.Pelamoko@va.gov
   > John.Horton3@va.gov
   > Megan.SavelHawryluk@va.gov
   > Michael.Macmahon@va.gov
   (submitted by nelson.colonvargas@va.gov , nel.abdiel at DSVA Slack)

- Please provide the name of your team, your role on that team, and the name of the company you work for.
   > We are currently being referred to as the VBA Fraud Waste Abuse (FWA) Team (previously the VBA Data Quality & Fraud Prevention (DQFP) Team)

- [if requesting SSH key authorization] Not needed

- [Grant AWS Console access?]
  > YES
  >  The VBA FWA team requires access to OIT resources to support successful detection and investigation support of fraud occurring against VBA benefit recipients. Team will use this data to proactively act on suspicious authentication and login events, incorporating it into persistent monitoring capabilities deployed to detect potential fraud; and use data such as IP addresses to perform connected case analysis in support of investigations against criminal fraud rings and actors. After a meeting with Charles Worthington, ID.me and VA.gov where we discuss the recent detection efforts of fraud prevention we discovered that the data on CloudWatch is the missing factor to conflate identities from multiple datasets.

**Comment by nelabdiel** [comment]
@department-of-veterans-affairs/vsp-operations

**Comment by jholton** [comment]
cc: @wyattwalter @gunsch

**Comment by Jeff-Hayter** [comment]
@nelabdiel Can you confirm that all of these individuals are VA employees (not contractors) and have completed their necessary background investigations (i.e. have a PIV or VA email)?

**Comment by gunsch** [comment]
cc @ricetj + @jbritt1 (current support)

**Comment by ricetj** [comment]
Hello, thank you for your patience with this request. We will be issuing you all access to our AWS account in order for you to access the CloudWatch logs. The current way we access our logs through CloudWatch will be changing in the coming few months.  We are moving away from CloudWatch to an alternative tool, which will not live in our AWS account. We are letting you know this so that you all are aware of these upcoming changes. Yet, again thank you for your patience.

**Comment by jbritt1** [comment]
User accounts created for all requested users. Working on a way with the team to pass first time login credentials.

**Comment by jbritt1** [comment]
At this time, first time login credentials have been passed to Daniel and John (just adding for tracking purposes).

**Comment by jbritt1** [comment]
Due to inactivity, we the Ops team have removed the unused accounts from this list at this time [(pull request for reference)](https://github.com/department-of-veterans-affairs/devops/pull/7183). The three that have used their first time login credentials will be keeping their accounts (Daniel Fein, John Horton, Jonathan Kislin). We will be happy to revisit / reopen / assist if the other accounts are need in the future. Closing for now.
