### ISSUE TITLE
SOCKS access for Erin White

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#88184]
### Your Name

Erin White

### Your Email

erin.white@adhocteam.us

### Your GitHub Handle

erinrwhite

### Your Role and Team

Information Architect/Platform Governance Team

### Product Manager (PM) name and email

Shira Goodman <shira.goodman@oddball.io>

### Product Owner (PO) name and email

Matt Dingee <matthew.dingee@va.gov>

### Access Type Requesting

platform

### Public SSH Key

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICw6zUudTe5LrJTfSRebeteulXzwHwU/aIrGHIyqLn9+ root@erinwhite-FVFGH0PG0KPF

### E-QIP Transmittal Confirmation

![Screenshot 2024-07-12 at 9 25 29 AM](https://github.com/user-attachments/assets/a7a0532c-0d14-49ab-9a14-77b8dc28b2b2)

### User must exist in a roster before SOCKS access can be granted

- [ ] Search for VFS team member in [Atlas](https://www.va.gov/atlas/product_directory/team_members)
- [x] Or search for user on the Platform Team Roster: https://vfs.atlassian.net/wiki/spaces/AP/pages/1908834623/Platform+Roster
- [ ] If user is on a VFS team but not a team member in Atlas, add the 'NOT YET' label and instruct them to start the Platform orientation process https://depo-platform-documentation.scrollhelp.site/getting-started/Platform-Orientation.1877344532.html
- [ ] If a user is on a Platform team but not on the Platform Team Roster in Confluence, add the 'NOT YET' label and instruct them to reach out to their Product Manager to be added.
- [ ] Comment in this issue saying which roster the user is listed in.

**Comment by flooose** [comment]
Hi @erinrwhite! I'm not sure why this issue was opened again, or who did it 🙀. Are you having problems with SOCKS access? It looks like everything should be in place, so if things aren't working, it might be better to contact [platform support](https://depo-platform-documentation.scrollhelp.site/support/getting-help-from-the-platform-in-slack). You can reference this issue and I'll leave it open until things get figured out 🤞

**Comment by erinrwhite** [comment]
I'm all set! Ticket can be closed.
