### ISSUE TITLE
CT-EYB: Adjust mobile behavior on answer field focus.

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#8821]
As a user, I need to research and implement a solution if possible to adjust the behavior on mobile devices when answer fields are focused in order to avoid the jarring jumping behavior that is currently exhibited.

## Assumptions:
1. If there is a solution, this work is completed behind a feature flag #7780.
2. If there is no viable solution, documentation is provided outlining the issues that prevent the recommended behavior.

## Acceptance Criteria
1. If the entire answer field is entirely in view, the screen does not move when the user sets focus on an answer field on a mobile display.
2. If the answer field is partially in view, the screen only moves enough to bring the entire answer field into view on a mobile display.

## Supporting Artifacts:
1. [ID2 - accordion & question behavior.mov.zip](https://github.com/department-of-veterans-affairs/va.gov-team/files/4588349/ID2.-.accordion.question.behavior.mov.zip)

**Comment by hughes-dustin** [comment]
We can get this to work with almost all of EYB fields except for the zipcode input field. This input field is created using an imported library that we have no ownership over. 

![image.png](https://images.zenhubusercontent.com/5c98ddbd98ed1e00013adfec/00e64f0e-f95c-40b2-a97d-38fb6932220a)

**Comment by hughes-dustin** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12627
Branch: bah-8821

**Comment by delli-gatti-michael** [comment]
Tested by the following test cases which cover *all* input fields in the comparison tool:

https://dsvavsp.testrail.io/index.php?/cases/view/621
https://dsvavsp.testrail.io/index.php?/cases/view/622
https://dsvavsp.testrail.io/index.php?/cases/view/623
https://dsvavsp.testrail.io/index.php?/cases/view/624
https://dsvavsp.testrail.io/index.php?/cases/view/625

**Comment by hughes-dustin** [comment]
All prod flags in vets-website are labeled by "bah-8821". 

Prod flags are located in:
- src/applications/gi/components/search/InstitutionSearchForm.jsx 
- src/applications/gi/components/Checkbox.jsx
- src/applications/gi/components/Dropdown.jsx
- src/applications/gi/components/RadioButtons.jsx
- src/applications/gi/components/search/KeywordSearch.jsx
- src/applications/gi/components/vet-tec/VetTecSearchForm.jsx
- src/applications/gi/components/vet-tec/VetTecEstimateYourBenefitsForm.jsx
- src/applications/gi/containers/SearchPage.jsx
- src/applications/gi/containers/VetTecSearchPage.jsx

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah 
This is on Staging and ready for review

**Comment by ccruzgra** [comment]
AC 1 and 2 are working well for me on android. The only issue I’m seeing is that when I tap a field to add in an amount, the bottom sheet is covering up the field so I can’t see what I’m doing. In this screenshot, I had tapped the Tuition and Fees text field, and this happened: 

![Screenshot_20200522-125222](https://user-images.githubusercontent.com/41477797/82693888-519f9e80-9c30-11ea-9b45-c46e37b6f8ea.png)

**Comment by JenLJ** [comment]
On iPhone, the selected field moves directly above the keyboard regardless of whether there is space or not.  So AC 1 is failing and AC 2 is passing
![iOS_after selection](https://user-images.githubusercontent.com/36964225/82694256-f3bf8680-9c30-11ea-8927-bf46318e9267.png)
![iOS_initial](https://user-images.githubusercontent.com/36964225/82694261-f4f0b380-9c30-11ea-9c20-c339290357c6.png)

**Comment by hughes-dustin** [comment]
**Problem:** 
In iOS Safari, when user makes selection from dropdown or textbox the screen jumps to the middle regardless if the field is already in view or not.
**Explanation:**  
The reason the screen is jumping is because Safari is having to fit in the dropdown options list or the touch keyboard and is pushing the input field either up or down to do so. 
**Solution:** 
 A potential solution may be found [here](https://stackoverflow.com/questions/37287148/ios-safari-chrome-unwanted-scrolling-when-focusing-an-input-inside-the-modal). Though nothing I tried from the suggestions seemed to work for our situation. 

**Problem:** 
In iOS Safari, when user selects a radiobutton or checkbox that is partially out of view, the input field doesn't scroll into view. 
**Explanation:**
iOS Safari is ignoring our `onFocus` action listeners either because of asynchronous onChange() events or it just hates us.
**Solution:** 
Move the onFocus logic into the onChange action listener.

**Note:**
iOS Safari currently does not support smooth scrolling animation option for the scrolling methods we are using.

**Comment by hughes-dustin** [comment]
Fixes radiobuttons and checkboxes not scrolling into view in iOS Safari.  

PR: https://github.com/department-of-veterans-affairs/vets-website/pull/12840
Branch: bah-8821-c

**Comment by delli-gatti-michael** [comment]
All inputs behave as expected using an emulator except for the following field types

#### Android
- Text and Numeric input fields (anything that would cause the keyboard to pop up) are automatically centered

#### iPhone
- Text and Numeric input fields (anything that would cause the keyboard to pop up) are automatically centered
- Drop-downs are automatically centered

**Comment by amyknox** [comment]
@delli-gatti-michael - UX review complete
