### ISSUE TITLE
[Bug] 526: Continued Use of the Same Transaction ID Over Several Days

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#8822]
## User Story or Problem Statement
During our call with EVSS, they mentioned that a large file was causing a failure on their end.  Although this is an issue, this ticket is intended to solve/determine why the same Tx ID was being used for all of the submissions even though it was over at least a 24 hour period.  The expected behavior will use a different Tx ID each time the user logs in.  This ticket is intended to discover how this could be happening.  Our hypothesis is that this is part of an async job.

## Goal
Understand why we are having the same Tx over a long period of time. 

## Acceptance Criteria
- [x] If this is a fix on our end, create ticket for development work.
- [x] Provide explanation of how/why this is occuring.

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by annaswims** [comment]
Many of the calls that va.gov makes to EVSS are run as background jobs and we set the va_eauth_service_transaction_id when we create the job.  If the job fails (say, if we receive a 500 error) we retry the job 25 times with exponential backoff over about 20 days.  We’re just using Sidekiq’s default retry policy and it’s really helpful when we want to retry jobs after a maintenance window, but I could see reducing our number of retries. So that problematic file upload was uploaded once by the veteran and va.gov was retrying it, not the veteran.

This seems reasonable to me and I don't think any changes to vets-api are necessary.  I could see reducing the number or retries, but I think the core issue is that we can't differentiate between when EVSS sends us a 500 error to mean "bad data format" as well as "major system error"

**Comment by annaswims** [comment]
[Sidekiq retry documentation](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry)

**Comment by annaswims** [comment]
[Michael Walker agrees](https://dsva.slack.com/archives/C8R3JS8BU/p1588868098174400) that no changes are necessary.  Closing
