### ISSUE TITLE
PrefName: Update Welcome component to use new field

### ISSUE THREAD

**Issue by dcloud** [department-of-veterans-affairs/va.gov-team#88477]
### User story

As a Cartography team member, I want the `Welcome` component to leverage `preferredName` and to display an appropriate `<va-icon />` and for the `<va-link />` to provide an action name that Datadog can track.

### Notes

- The `<va-link />` provides custom GA analytics call
- 11/19 update: [Trevor Bosaw's PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19488) that adds preferredName to the User object (from MPI) was merged. So we can leverage it.

Possible tasks:

- Add `data-dd-action-name` to an `<a>` element and ensure both Datadog and Google Analytics report the way we want.

## Acceptance criteria

- Welcome component on MHV Home displays Veteran's preferred name (if present), or falls back to old behavior (first name, then null), based on MPI value
- Both GA and Datadog track "Profile" link click. Track GA navigation with 'nav-linkslist' event, similar to existing card/hublink
- QA review

**Comment by wesrowe** [comment]
@dcloud, FYSA you could help us get a jump on refinement by recording here what we learned about this work (and what it turns out is _not_ getting done for us).

**Comment by wesrowe** [comment]
I wanted to take this to office hrs on 9/30 but Patrick wasn't in. Will try again 10/7

**Comment by wesrowe** [comment]
@nichia @dcloud, I'm struggling to follow the updates to the ticket. It seems to me like we need to adapt this to the MPI/User object path.

**Comment by wesrowe** [comment]
And I updated to make it clear that the component needs to use the new field on User.

**Comment by LynneJohnson224** [comment]
@nichia the PR for this has been open for 2 weeks. what other reviews are needed before this ticket can be moved to QA?

cc @mcarterA6

**Comment by allanto-ah** [comment]
Environment: Staging

### Issue 1: Updating the Preferred Name in Profile does not reflect on the MHV landing page

https://github.com/user-attachments/assets/ddd51d95-38e1-45d7-8b2a-54f64b4cae6b

**Comment by allanto-ah** [comment]
Environment: Staging

Verified that the Preferred Name set in the Profile page shows up on the MHV landing page. However, there is a delay and does not happen instantly because of the frontend and backend are not in sync. 

This is a known issue (Issue 1 above) and is not on our team to get fixed. In terms of our team's work, this is considered done

Slack context: [Link](https://dsva.slack.com/archives/C0581MN69TJ/p1733503690562629)

![Image](https://github.com/user-attachments/assets/191e895d-d094-42f0-9d6d-a70206f10810)
![Image](https://github.com/user-attachments/assets/e460edbb-80c1-4f7d-bcf9-622a1269ef0f)

**Comment by wesrowe** [comment]
@allanto-ah @dcloud , is it possible the cache-busting story in our backlog will fix this delay?
