### ISSUE TITLE
Evaluate Phase 1 migration epic and consolidate into Epic 538

### ISSUE THREAD

**Issue by rroueche** [department-of-veterans-affairs/va.gov-team#885]

**Comment by rroueche** [comment]
A repo reorg was started during the transition period from VA.gov to VSA / VSP and that's documented in this Phase I epic: https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/96

Now we are iterating on our approach to the repo organization, and are tracking that work in Epic 538.

The goal of this task is to evaluate the Phase I epic and see if there's any work we need to bring over to the new epic, and/or things we can close out bc they are complete or obsolete.

**Comment by mnorthuis** [comment]
@rroueche 
Closed or moved remaining issues into epic #538 for this new phase of the repo work.  Issues moved to our new epic are:
#135 - Rewrite repo root level README.md
#195 - Write documentation/repo use standards/best practices


This issue is very specific and will need to be reviewed if it should be part of this effort or specific documentation work for the Triage team:
#247 - Combine incident response playbooks

**Comment by mnorthuis** [comment]
Looks like #247 has been handled. Closing this issue.
