### ISSUE TITLE
Datadog: ensure data is pulling from the right environment

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#88741]
Currently the datadog dashboard shows the same numbers in certain charts regardless of environment selection.

We want to ensure that the environment selected in the dropdown results in the charts only showing data for that environment.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekR3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae28f81d059a5fbdb3a486f2480e64ef2815a0c7/Screen%20Recording%202024-07-18%20at%2011.03.16%E2%80%AFAM.mov)

**Comment by balexandr** [comment]
@baltes I updated all the DD widgets to use `env:$env.value` so that it looks at whatever environment is set at the top. Here is the past day for `eks-prod`
<img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMndDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--618727a8d7f05e56a8fd293cd0f2d471033ccbdf/Screenshot%202024-07-23%20at%204.59.46%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 4.59.46 PM.png" />

And here is `eks-staging`
<img width="1122" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjRDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fed1b2eab0f35f86d87822dc02378ab9be6af11/Screenshot%202024-07-23%20at%204.59.57%E2%80%AFPM.png" alt="Screenshot 2024-07-23 at 4.59.57 PM.png" />
