### ISSUE TITLE
[Congressional] V11981367 Due 8/28/24 (Sen. JD Vance)

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#89092]
## Issue Description
_Veteran cannot log into his healthevet account. Has tried for over six months to get help over the phone and is given the run around. His username and password work but he keeps getting a "ERROR 500" message after he logs in.

https://app.slack.com/client/T03FECE8V/C02BS78NYRM?selected_team_id=T1ZD0UBMZ&cdn_fallback=1

---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve Issue
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue
- [x] Congressional Correspondence will receive details of the resolution 
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
7/29/24 - Sent email to Brenda and team to request assistance and to confirm they are able to assist with this issue.
Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
7/29/24:  Brenda responded:
We can see where the Veteran has accessed his MHV account multiple times in the last few months (recently in July). We called him to see if there were other challenges. He said he is at work and requested a call back tomorrow.
We’ll follow up.

**Comment by ATMiddleton** [comment]
Vicki Caruso
  Yesterday at 8:49 AM
8/7 Brenda Torres-Hill's Update: Our staff member called the Veteran and did preliminary research. However, the technical issue is with Cerner, per the Veteran. He said he spoke with Jennifer at Cerner and was told that the issue would be escalated via ticket 12240892. I have two POCs at Cerner that may be able to help regarding the status of this ticket.

**Comment by Kimberley2023-CSM** [comment]
Update: 8/27:  Brenda replied with information showing that the issue is not resolved but being tracked by Oracle Health.  VA isolated the issue to be within Oracle Health and is working with the OH dev team.

Email includes screenshot of OH's Error 500, which points Veterans to the OH Help Desk.

**Comment by Kimberley2023-CSM** [comment]
Vicki Caruso
  Wednesday at 4:02 PM
Complete: Case has been closed. It's now being handle by the Oracle Health Team

**Comment by Kimberley2023-CSM** [comment]
Update 9/4/24:  The Oracle team reached out to the Veteran and was able to work with him to get screenshots and additional information which is allowing them to review the logs and system information to address the issue.  The team enacted a fix to the Veteran's patient portal account on 9/3/24.  The team will contact the Veteran on 9/4 to inquire if he now can access his patient portal account.

**Comment by Kimberley2023-CSM** [comment]
Update 9/5/24:  Rick D. provided an update, see below.
Good afternoon team - I have good news. The Veteran regained access to their patient portal this afternoon. The OH help desk confirmed with the Veteran this afternoon and notified VA stakeholders at 1:13PM CDT today of the successful login. We can report to Sen Vance’s office the issue has been resolved.
After Wednesday’s unsuccessful attempt to reset the Veterans portal account, Apothesource – VA sub-contractor who maintains the patient portal sign-up service - reviewed their logs and discovered the sign-up service did not account for the Veteran accepting the new VA-Enterprise Terms of Use (TOU). The Sign-Up Service assumed the Veteran’s account did not need to be reprovisioned because it had data indicating the legacy TOU was accepted. Apothesource corrected the issue by adding a step to force the Sign-up Service to reprovision the Veteran when they logged in again. The OH help desk called the Veteran this afternoon and confirmed with him that the have access again to the portal.
Because of the complex VA-owned login procedure, it took several weeks of investigation and coordination to develop this fix. We are still investigating with stakeholders how the issue occurred so we can determine a root cause in case the issue occurs again when we deploy to new sites.
As background, the VA internally developed and deployed a new enterprise wide terms of use (TOU) on 4/25/2024. Oracle Health’s (OH) patient portal was the first VA solution to use it. The new TOU requires Veterans to accept it in order to access all VA web applications. If a Veteran declines the new VA TOU, then their VA accounts are deprovisioned. OH started to receive reports of Veterans experiencing 500 errors shortly around the time the new VA TOU was enacted..
·         The login process to the OH patient portal is owned and maintained by the VA. OH requires VA subject matter experts assistance to troubleshoot and resolve any access issues that may be related to login process.
·         VA OIT internally developed the new TOU. OH was aware of the TOU project and actively tracked its deployment. OH was not involved in the formal development or testing of the new TOU.
·         OH is only tracking ~128 reported cases of access issues to the OH patient portal that are Terms of Use related, with ~104 cases being resolved. The majority of cases were resolved after we had Veterans manually decline the new TOU, and then reaccept.
o    VA Digital Health Office, Office of Connected Care advised us to no longer have Veterans decline the new TOU as it deprovisions their VA My HealtheVet account and requires the My HealtheVet help desk to manually reprovision the My HealtheVet account. OCC issued this guidance after the VA’s legacy portal My HealtheVet, went live with the new TOU in Mid-May 2024.
·         There are currently ~23 active cases; 17 cases are related to a 500 error similar to this Veteran.
·         OH, VA Identity Management (IAM), VA OIT, the VA Digital Health Office, Office of Connected Care, the VAMC Connected Care Coordinators, and other stakeholders have been meeting weekly since 7/17/2024 to review the remaining open cases and develop course(s) of action to address. We will attempt to resolve the other access issues by applying this fix.
·         Stakeholders are reviewing the system logs associated with these cases to try to identify root cause(s) for the reported access issues.
·         OHGS Issue 1682 “New VA Terms of Use (TOU) Affecting Veterans Logging Into My VA Health” was externalized to EHRM-IO on 8/12/24 to document this issue.
Please let the team know if there are any other questions we need to address to close out this congressional.
Case closed :task_done:
