### ISSUE TITLE
MHV API: Document API-dependent apps and error flows

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89122]
### User story

As a Veteran, I want to be alerted that the sign-in process on VAgov (ie, the call to the MHV account creation API) returned an error as soon as I reach a page on VAgov that requires an MHV account identifier, so that I can take action to resolve it (call MHV Help Desk?) before I get into a bad experience due to lacking MHV account.

As a Cartographer, I want to provide the VA.gov Identity team with any additional requirements that health apps have for handling various responses from the API, so that the apps can provide a good user experience to Veterans.

### Notes
- We are still trying to get the API workflow chart that the MHV team presented several weeks ago in an engineering kickoff meeting. Sandeep shared Confluence links but :
  - https://confluence.devops.va.gov/display/VAExternal/Account+Creation+API+Spec
  - https://confluence.devops.va.gov/display/VAExternal/Account+Creation+API+User+Stories
  - https://confluence.devops.va.gov/display/VAExternal/Check+MHV+Account+API+-+Quick+Check
- Patrick provided PDFs of the above files in slack on 7/31
- Technical stakeholders:
  - Patrick & Joe Niquette from VA.gov
  - MHV side: Carnetta, Sandeep
- Assumption: work from existing documentation (above)

Possible tasks:
- 

## Acceptance criteria

- [x] Identified which apps on VAgov require an MHV account and/or secure message account
- [x] Documented user flows from unauthenticated states (paths in) to health tools that require MHV identifier, and how each should be handled if an error comes back from API (i.e., user doesn't have MHV account identifier)
- [x] Identified information that the front-end would need from the sign-in process (if any) to handle Veteran cases
- [x] Gathered items in a document we can share to VA.gov Identity team
- [ ] Ticketed follow-up needs as necessary (e.g., if documentation isn't sufficient)

**Comment by sterkenburgsara** [comment]
Synced with @carlosfelix2 on 8/2/2024 to discuss. Here are some notes: 
* Approaches to implementation of Account Creation API are included [in this Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581177532/3cbc80571562a1f162a0887c4a60e06c3014f99a?sender=uf94a77a19aaf687331c09367)that Carlos created in the previous eng discovery ticket. These routes _all assume_ a single happy path entry point through the VA.gov front door. UX analysis is that we need to identify the side door entry points to any /my-health URL leading to an affected API and make sure that error messaging would display on those pages. 
* Information we need on the front end is relatively simple: 1.) did the API fail (no MHV account was created)? 2.) if the API hasn't completed and is still working, we need to indicate this to the user. 
* If the API fails for any reason (we don't think the type of error matters on the FE), we will want to edit the current "Register for My HealtheVet" alert that we have in place and adapt content to direct users to call the My HealtheVet helpdesk for assistance with getting an MHV account created in order to access Medications, Medical records, or Secure Messages. 
* We are waiting for the account creation API to be built, and the identity team to determine which implementation approach they will take. 


Outstanding questions: 
* We don’t know how the identity team plans to trigger the account creation (during login? synchronous? async? )
* if async, how do we check that the process is done?

**Comment by carlosfelix2** [comment]
Applications that use an MHV account

- MHV landing page
- Medical Records
- Secure Messaging
- Medications
- Personalization Dashboard (/profile) - to show health care information

**Comment by sterkenburgsara** [comment]
Carlos and I synced with @joeniquette on 8/8/2024 - great conversation, was really helpful to get on the same page. Joe drew up a sketch of how the service might function and we collaboratively wrote down questions for him to take to the MHV Access team. They have ear-marked 3 sprints for this work but think it could take as little as one to engineer the implementation for this API. Joe mentioned he'd sync back up with us in a few weeks. 

Screengrab of notes for follow-up with Account creation API team. // cc @batemapf 
<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfc03b9dd43a2ebbaaefc8253e47b5e4e13dce56/Screenshot%202024-08-08%20at%2010.48.40%E2%80%AFAM.png" alt="Screenshot 2024-08-08 at 10.48.40 AM.png" />

**Comment by sterkenburgsara** [comment]
@carlosfelix2 Is it only Profile, or does MyVA page use it? I know MyVA displays upcoming appointment information but I'm not sure if data from the MHV-API apps gets pulled onto that page. It could be that there are simply cross-links to content from the other MHV apps and no actual data being displayed.

**Comment by sterkenburgsara** [comment]
Update: [Added a user flow to the Mural ](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1719581177532/3cbc80571562a1f162a0887c4a60e06c3014f99a?sender=uf94a77a19aaf687331c09367) based on @carlosfelix2 analysis of which apps use the MHV account to display data. Since the plan is for the API to run as an async sidekiq job, we'll need to pass a request to the API to check for job completeness and/or resulting errors when a user hits certain pages, so that we can deliver appropriate alert messages (if/as needed) to the user on the FE.

There are many side door entry points to My HealtheVet that we'll need to cover for / consider when implementing those alerts on the FE after the API is ready. 

The alerts that I can foresee needing, the places those should appear, and the data behind those alerts are documented. 

// fysa @wesrowe

**Comment by sterkenburgsara** [comment]
Carlos answered the question I posed above in a meeting: MyVA does not display data on the page about applications that rely on the MHV-API - it only surfaces cross-links to URLs in those apps. But, there is an exception with the red dot indicator, which does rely on data from the SM API. This data is also being pulled by the My HealtheVet home landing page, which surfaces the red dot indicator next to the "Go to inbox" link as well.

**Comment by sterkenburgsara** [comment]
Iterated on flow diagram per conversation with @carlosfelix2 yesterday. I think we're on the same page, and are up to speed in our conversations with Joe. We have a sync planned in the next sprint with lots of involved parties, including Joe and the MHV "Access" team who is developing the API. 

Can I move to QA column? Not sure what follow-on tickets we may need? We'll probably want to monitor progress and potential changes over time?
