### ISSUE TITLE
Design and research - 10-10d + 59c merge- Wireframes

### ISSUE THREAD

**Issue by jamiefiore** [department-of-veterans-affairs/va.gov-team#89590]
Begin exploratory designs and research for merging 10-7959C (OHI cert) into the 1010D (CHAMPVA Registration) for a more cohesive and streamlined user experience. 
Consider adding the questions in the flow for the 10-7959c in this [Figma file](https://www.figma.com/design/sSPoS7R9HE6ZlxRESRy2ms/Other-Health-Insurance-Certification-(10-7959c)-Form?node-id=1155-73969&t=3eQvCdJ0yEOPsU8z-0)

- [ ] Create wireframes of the OHI cert questions and uploads included within the CHAMPVA Registration form

**Comment by syd-hoeper** [comment]
Following up from the Design sync on Monday -- I'm waiting for Matt Dingey to be back from PTO to let me know if we're allowed to use the existing "Download completed PDF" button even though there's a new pattern in the works. This is blocked for now, but the project is on ice since it's so far ahead. Here's the link to the Slack thread: https://dsva.slack.com/archives/C01DBGX4P45/p1724180305823079

**Comment by syd-hoeper** [comment]
Just kidding -- there's a few more things I need to investigate per Lois's request. Slack thread: https://dsva.slack.com/archives/C076R0F49L0/p1724180087168479

**Comment by syd-hoeper** [comment]
Wrapping this ticket up for now. Everything I researched is documented in the "Documentation" section of the Figma. This is going to be put on ice until Premal can get some more information about PRA and until we need to prioritize this work again.
Link to Figma file: https://www.figma.com/design/aYa45eB5OxU0l0gqyjQORa/59c-and-10-10d-merge?node-id=53-181395&t=oGsSm2voOzKdT4cc-1
