### ISSUE TITLE
SPIKE: What does form submission entail?

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#89650]
## Overview

We need to better understand what exactly happens on form submission, specifically as it relates to the process of converting Veteran data into a PDF.

## Acceptance Criteria
Answer the following questions
- [x] Is PDF translation currently being done on the client or server side, or mix of both?
- [x] What is happening with `transformForSubmit`? Is there a way we could generalize this or is there a need for custom, per-form code?
- [x] A list of questions is compiled for the Veteran Facing Forms team.

**Comment by Karak888** [comment]
need to prioritize what sprint it will happen in, but not for immediate next sprint

**Comment by ryguyk** [comment]
WIP

# Findings

## Overview

The process of submitting a form is split up into two parts:

1. `vets-website` (the browser)
2. `vets-api` (the server/API)

Among the most important takeaways of this spike is determining that PDF creation happens on the _server_. This process is partly automated, but requires some initial setup on a per-form basis.

The browser portion of the process boils down to some data transformations that take place prior to making the API request. The degree to which this happens depends on the form in question. Importantly, there _is_ some custom code being used on a per-form basis. The question for our team will be whether we can architect a way to more generally handle this without per-form custom code. If not, we'll need to provide a way to define and tie into custom code for each form.

## vets-website

Let's first take a look at the browser side. As mentioned above, this part of the process effectively amounts to transforming/preparing the form data for passing to the API.

### `formConfig` properties

There are a few properties on the `formConfig` object that relate to this process:

- `submit`
- `transformForSubmit`
- `submitUrl`

Here is a block of code from `src/platform/forms-system/src/js/actions.js` that paints a picture of how these properties work and relate:

```
let promise;
if (formConfig.submit) {
  promise = formConfig.submit(form, formConfig);
} else {
  const body = formConfig.transformForSubmit
    ? formConfig.transformForSubmit(formConfig, form)
    : transformForSubmit(formConfig, form);

  promise = submitToUrl(
    body,
    formConfig.submitUrl,
    formConfig.trackingPrefix,
  );
}
```

#### `submit`

As we can see, if this property is defined, then it solely defines the submission logic. Importantly, in this case, `transformForSubmit` is not called. That is to say, if `submit` is defined, `transformForSubmit` has no effect. Generally speaking, especially on "simple" forms, `submit` is not defined.

#### `transformForSubmit`

This is the most interesting of the three properties, as this is the property that captures the bulk of the business logic that takes place in the browser regarding form submission. There are a number of things that take place across various forms in this step, but the most notable and universal is the serialization of the form data. That is to say, the form data object is transformed into a JSON string via `JSON.stringify`.

Notably, defining this property is optional. As we can see in the code block above, if it is not defined, a default transformation will be applied. Often times, and seemingly with all or most "simple" forms especially, a custom tranformation is defined but that custom code calls the default transformation as part of its logic. So it seems the default transformation is almost always applied.

Said very briefly, the default transformer appears to remove unused pages and unnecessary fields (fields prefixed with `:view`) from the form data object. In this way, at the very least, the payload is trimmed. Whether this is strictly necessary is a question for the Veteran Facing Forms team (see question section below).

As mentioned, custom transformations can be applied (generally in addition to the default/shared transformation) to perform transformations on a per-form basis. Here is a (partial) list of some of the transformations that are defined for some of the "simple" forms:

- **Data truncation**: This is generally done, it seems, in order to comply with string-length limitations imposed by the existence of OCR boxes on the PDF form. It does seem that this _could_ be done on the server rather than the browser, which might help remove one possible need for per-form custom code on the browser. That is a question for the Veteran Facing Forms team (see below). Alternatively, we might consider some more general truncation logic based on a form creator/editor entering the maximum length from the original PDF.

- **Removal of other unnecessary fields**: Example: when the form might be completed by different parties (eg. Veteran or third party), remove the third-party fields when the preparer is a Veteran.

- **Merging first, middle and last names into a single full-name field**:
  ```
  if (middle) {
    transformedData.fullName = {
      first: first.slice(0, 12),
      middle: middle.charAt(0),
      last: last.slice(0, 18),
    };
  } else {
    transformedData.fullName = {
      first: first.slice(0, 12),
      last: last.slice(0, 18),
    };
  }
  ```
- **Reshaping/normalizing data**:

  ```
  const { formNumber } = getFormContent();
  const { idNumber = {}, address = {} } = transformedData.veteran;
  const { confirmationCode } = transformedData.uploadedFile;

  return JSON.stringify({
    confirmationCode,
    formNumber,
    options: {
      ssn: idNumber.ssn,
      vaFileNumber: idNumber.vaFileNumber,
      zipCode: address.postalCode,
    },
  });
  ```

#### `submitUrl`

This indicates the API endpoint to which the form should submit. For "simple" forms (the forms we're dealing with initially, all of which will be sumbitted via Central Mail), the URL is as shown below:

```
submitUrl: `${environment.API_URL}/simple_forms_api/v1/simple_forms`,
```

## vets-api

### General

"Simple" forms are all submitted to the same API endpoint (as show above). This endpoint is defined as part of a larger module in `vets-api` that handles the server-side processing related to submitting forms to Central Mail.

Below is an explanation from `modules/simple_forms_api/README.rdoc` that helps outline this process:

```
= SimpleFormsApi
This module allows you to generate form_mappings based on a PDF file.
With this in place, you can submit a form payload from the vets-website
and have this module map that payload to the associated PDF and submit it
to the Benefits Intake API in Lighthouse.

To generate files:
rails simple_forms_api:generate\['path to PDF file'\]

```

The first step, it seems, is to add the PDF file to the `vets-api` repo (e.g. `modules/simple_forms_api/templates/vba_20_10206.pdf`) and then run the utility mentioned above to generate the mappings (e.g. `rails simple_forms_api:generate[vba_20_10206.pdf]`, though it's not clear how qualified that path needs to be).

### PdfFiller

It looks like we will need to define a model class for each new form. A question for our team is whether we might be able to somehow define a single model for all of our forms. That seems unlikely, but certainly worth examining.

e.g. `modules/simple_forms_api/app/models/simple_forms_api/vba_20_10206.rb`

### PdfStamper

### PdfUploader

## Questions

1. Is the removal of unused pages and unused/unnecessary fields strictly required, or is it simply to trim the payload? Will these unused pages break the PDF creation?
2. Why is truncation done on the browser? Could it be done on the server? Is there any downside to this?
