### ISSUE TITLE
SPIKE: Technical Feasibility of paragraph editing on separate pages

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/va.gov-team#89735]
## Overview
Initial UI design exploration for the Drupal-based Form Builder calls for component (paragraph) sub-forms that are their own pages (rather than inline in the main body of the Digital Form input). We need to determine the technical feasibility of this.

## Acceptance Criteria
Answer the following questions:
- [x] Can paragraph edit screens be their own pages?
- [x] How would we handle paragraph selection? Would we still use the modal? Or would/should/could this be a separate page as well?
- [x] Is there any significant risk that is introduced by doing this?

**Comment by ryguyk** [comment]
WIP
# Findings

## Overview
In short, as is the case with almost all things engineering, this almost certainly _can_ be done. It would introduce a good amount of custom engineering, and would introduce some risk.  Read on for more specifics.

First, though, it's important to acknowledge that this spike largely goes hand-in-hand with our [other spike worked on simultaneously](https://github.com/department-of-veterans-affairs/va.gov-team/issues/89812). As such, this write-up will address the questions explored in that spike as well. The write-up for that ticket will direct readers here.

## Questions to be answered
### Can paragraph edit screens be their own pages?
Yes. Rendering forms for individual paragraphs on their own pages is possible. This spike demonstrated success in doing that:

![image](https://github.com/user-attachments/assets/98f91f5c-ab8b-439f-9007-6136530d9a82)

There are (at least) two challenges that would need to be addressed to make this work in the wild:
1. We would need to be able to access the paragraph form so as to not have to custom-build every field for every possible paragraph. In the spike code, the paragraph-edit page in the screenshot shown above is manually built - two fields are manually added to the page. I don't think this obstacle would be huge, but it's notable.

2. The bigger obstacle lies in passing data back to the main node-edit page in a meaningful way. This seems to be the biggest challenge - and biggest risk - and is discussed in detail below.

### How would we handle paragraph selection? Would we still use the modal? Or would/should/could this be a separate page as well?

It's arguable that we would want to use the modal, and that could likely be done, though that wasn't a main focus of this spike. Instead, this spike explored the idea of using a separate page for this step as well. That is possible:

![image](https://github.com/user-attachments/assets/55a72403-0615-4ca0-9c70-48cb164cc1b6)

This piece of the puzzle isn't particularly challenging because there isn't a whole lot of data that needs to be passed or handled between this step and the others. We can have a selection UI of some sort and then pass the selected paragraph type as a url parameter. This is working well in the spike code.

The biggest challenge here would be tying into the list of paragraphs that are options for the content type and/or tying into the existing paragraph explorer that we see in the modal. Neither of these feel insurmountable, but it's worth noting that the current spike code does not handle either of those. The radio buttons are hard-coded.

### Is there any significant risk that is introduced by doing this?
Yes, there's risk introduced and it largely boils down to this representing a fundamental deviation from how Drupal handles this OOB (or at least with our current environment at the VA with installed modules, etc.). The existing paradigm when working with arbitrary paragraph collections attached to a field on a node is that those paragraphs are edited inline and are all submitted with the rest of the form when it is submitted. 
1. We would need to have


The spike code _does_ handle this in part - the data that is entered on the paragraph-edit page does get passed back to the node-edit page successfully.  But getting the node-edit page to use it properly is not trivial. It can render the _data_ just fine, but the reality is that the current default flow is highly coupled with the concept that
