### ISSUE TITLE
Midpoint Review - Design Feedback - IIR, Veteran New Account Flow within Authenticated Experience, Welcome Pathway V1

### ISSUE THREAD

**Issue by allison0034** [department-of-veterans-affairs/va.gov-team#89754]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Please listen to the recording for all of Matt Dingee's and Ryan Thurlwell's feedback.
- Do some research around the screen describing what information the user will be adding. Is it necessary to tell them they will need email, phone and address?

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] Must: [Per our guidance](https://design.va.gov/components/alert#how-to-use-alerts), you cannot stack alerts. Listen to the recording for Matt Dingee's feedback around using the task list. Please link the experimental design ticket for the task list.
- [ ] Must: Listen to the recording for Matt Dingee's feedback around the alert vs putting the information directly in the card on profile.
- [x] Must: We really do not have the "Skip this..." check box in our current forms or Design System. Is it necessary? Our forms are optional unless the *Required is next to a field.
- [x] Should: Add a [confirmation alert ](https://design.va.gov/components/alert)when they have successfully updated their contact info.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by emcruer** [comment]
1. Stacked alerts are removed.
2. We currently have the general alert, which users responded to in testing. We are not opposed to putting information in the card in a later phase, but there isn't a precedence for this and we do have some considerations (i.e. Only some profile information is editable by the person, so we could only include the prompt on like 3 or 4 cards. However, that doesn't mean they can't or shouldn't take actions on the other cards. For example, if we prompt them on "contact information" and they complete that, they may assume every other cards are fine if they DON'T see the specific card alerts, when in reality, we're not going to prompt them to edit emergency contacts since they can't do that in profile anyways. Given the way the information is segmented right now, we think the general prompt will work better). We can work with Profile in the future to see if this might be a better option or more feasible in the later phases. 
3. Skip this has been removed.
4. Added a confirmation alert (still working on which page makes the most sense for it to appear).

Thank you so much for your help!
