### ISSUE TITLE
CT: Missing padding between the School Summary and Estimate your Benefits sections

### ISSUE THREAD

**Issue by delli-gatti-michael** [department-of-veterans-affairs/va.gov-team#8981]
That padding between the bottom of the School Summary section and the "Estimate your benefits" header on a school profile page is no longer present. There should be 32px of padding between these two elements. This issue only exists on school profile pages (non-vettec).

1. Navigate to the following profile page:
https://staging.va.gov/gi-bill-comparison-tool/profile/11802405
2. Observe padding under School Summary (see screenshot below)

### AC:
1. 32px of margin between the School Summary section and the "Estimate your benefits" header

## Current:
![Screen Shot 2020-05-12 at 10.06.14 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/2914e83a-c9b7-4adc-8f61-2ba2120321ac)

## Expected:
![Screen Shot 2020-05-12 at 10.06.49 AM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/c8f1e652-b9dd-4512-9d38-9a48f08d6453)

[Sketch Document](https://www.sketch.com/s/0ee1f7c7-6692-4ef8-912d-0a929b5e5154)

**Comment by zurbergram** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/12687

**Comment by sonntag-adam** [comment]
The fix for AC 9 and 10 for story https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8918  is in this bug


The profile page:
9. On mobile view, the spacing between the Approved programs section header and the Additional resources link is 32px. (Appears to be a 16px bottom margin on the additional resources section and a 16px top margin on the Approved programs section)
10. On desktop view, the spacing between the Approved programs section header and the header content is 32px. (Appears to be a 16px bottom margin on the additional resources section and a 16px top margin on the Approved programs section)

**Comment by sonntag-adam** [comment]
This bug needs to be tested first for non-vettec changes. Then once merged test https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/8918 the changes along with the vettec changes.

**Comment by delli-gatti-michael** [comment]
Local testing complete

![Screen Shot 2020-05-21 at 3.35.18 PM.png](https://images.zenhubusercontent.com/5c07f000391a6f6357adc430/51cb9171-40bc-4a7e-8314-5d48d2a2030f)

**Comment by delli-gatti-michael** [comment]
@department-of-veterans-affairs/uxbah This is on staging and ready for review

**Comment by JenLJ** [comment]
@delli-gatti-michael  UX has reviewed and it looks good to go!

**Comment by delli-gatti-michael** [comment]
Closing this issue with QA and UI/UX approval
