### ISSUE TITLE
Prep month of August metrics report for Office Hrs 9/16

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#89881]
### User story

As a Cartography team member, I want to try a first read-out of how metrics answer the questions in our evaluation plan for the MHV landing page with our immediate OCTO stakeholders, so that we can learn from the discussion and home in on a reporting strategy for a wider audience.

### Notes
- octo office hours on Mon 9/16 was picked in a meeting with Robyn on 8/13
- this presentation can be "very MVP", we're just trying something out and expect feedback
- Florence's [documentation on using GA](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/landing-page/research/how-to-eval-plan.md) to answer (some) questions in eval plan

Possible tasks:
- Discussed as team what the deliverable looks like, based on Robyn statements/previous reports

## Acceptance criteria

- Drafted a presentation (not overly polished) for discussion on 9/16

**Comment by fmccaf1** [comment]
Ideas of analytics to include:
- Clicks on landing page: what gets the most clicks and the least? Include a sense of ratio through percentages or other way to show a ratio of some kind. Include also comparisons of clicks on secondary nav vs. tool cards
- Change of entry points over time: did we see number of users coming over from nat'l portal decrease since june? have we see changes of returns back to national portal?

**Comment by fmccaf1** [comment]
@katbrinkley ^

**Comment by katbrinkley** [comment]
thank you both!
