### ISSUE TITLE
Create Issue Template for Requesting Access

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#90]

**Comment by leahbannon** [comment]
Here's a template to start with. Some of the processes won't make sense since it's for external teams, but the questions might be sufficient to copy. HT Nedie

https://github.com/department-of-veterans-affairs/vets-external-teams/blob/master/Request-Reviews/request-google-analytics.md#request-google-analytics

cc @rtluu -- does this match what you were thinking from our discussion?

**Comment by joanneesteban** [comment]
Issue moved to [department-of-veterans-affairs/vets.gov-team #18588](https://github.com/department-of-veterans-affairs/vets.gov-team/issues/18588) via [**ZenHub**](https://www.zenhub.com/)
