### ISSUE TITLE
Flipper UI access for Harshil Moradia

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va.gov-team#90017]
Access to the Flipper UI for the staging environment to effectively carry out my responsibilities as a developer within our team. The Flipper UI will enable me to manage feature flags, control the rollout of new features, and perform A/B testing in the staging environment. This access is essential for ensuring that our application features are deployed and tested efficiently before going live, allowing for a smooth and controlled user experience.

**Comment by AnthonyWFlowers** [comment]
Greetings @harshil1793 in order to process your request you will need to fill out a Flipper UI ticket following the directions found [here](https://depo-platform-documentation.scrollhelp.site/developer-docs/flipper-ui-access#FlipperUIAccess-RequestingAccess)

Please let me know if you have any additional questions or concerns.
