### ISSUE TITLE
Sprint 13 - Appointments Production Support Ticket 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#90027]
## Description
If a developer is pulled to work on a production issue or need to support another team on VA.gov/Scheduling Product Line (backend services). The developer should add their comments into this ticket and reference a slack thread, email or JIRA/VAOSR ticket. 

We will need to track the production support for our reporting.

**Comment by cferris32** [comment]
Triaged with backend team around upstream latency and outages related to HSRM and other systems, noticed improvements after some backend updates. Also discussed ways to improve certain call performances with potential vets-api updates related to retrieving AVS.

**Comment by ldelacosta** [comment]
Team supported latency issue during Mobile app recent deployment. @JRRoof

**Comment by JRRoof** [comment]
### August 5-14: 
- Started seeing latency and HSRM not responding Monday, August 5 during peak usage.
- AWS and AT&T outage on Wednesday, August 7 complicated matters
- Issues continued after AWS and AT&T outage resolved
- No large increase in web user traffic was found
- Reduced session timeout from 55 to 25 seconds to reduce session backlogs
- Root cause was determined to be a 2x increase in calls to VAOS Service from Mobile app
- Mobile app had released a new homepage that calls appointments when loading
- HSRM capacity was increased to resolve the issue on Wednesday, August 14
- Additional monitoring added to alerts dashboard for better visibility in the future
