### ISSUE TITLE
Overhaul/update VA forms system documentation

### ISSUE THREAD

**Issue by meganhkelley** [department-of-veterans-affairs/va.gov-team#9023]
## User Story 

As a VFS team member, I need to understand how to build a form on VA.gov, so that I can embrace self-service, work in an agile way, and build great VFSs. 

## Background/Description

- [Brainstorm/kickoff doc](https://docs.google.com/document/d/1a2DCQ1_0OSOTIK9b9GehFQefTX7pQy29SSPdsZ5dHd0/edit)

## Definition of Done

**Comment by meganhkelley** [comment]
Initial meeting 5/12 to discuss this problem space — [notes](https://docs.google.com/document/d/1a2DCQ1_0OSOTIK9b9GehFQefTX7pQy29SSPdsZ5dHd0/edit)

**Comment by taylorkaren** [comment]
[Brainstorm/kickoff doc](https://docs.google.com/document/d/1a2DCQ1_0OSOTIK9b9GehFQefTX7pQy29SSPdsZ5dHd0/edit) and Initial meeting 5/12 to discuss this problem space — [notes](https://docs.google.com/document/d/1a2DCQ1_0OSOTIK9b9GehFQefTX7pQy29SSPdsZ5dHd0/edit) are both deleted. 

Overhaul of Forms Library System documents is being worked on by the Forms Library Team during Q1 2022 on this epic: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/98.

Since there are no tickets linked to this epic, closing this issue.
