### ISSUE TITLE
Staging Review finding: Sentence case for links 

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#90542]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** govcio-vfep-codereviewers
**Product:** Resources for schools
**Feature:** Convert Legacy Markdown SCO page into a React App

## Findings details
**VA.gov Experience Standard - issue:** [User encounters content with errors or inconsistencies.](https://design.va.gov/about/experience-standards/#user-encounters-accurate-consistent-content)
**VA.gov Experience Standard - category:** [Consistency](https://design.va.gov/about/experience-standards/#category-consistency)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @kkitagawa-bosch (content)

### Description

Many of the links in headers currently use Title Case capitalization. These should all be Sentence case unless (1) referring to a proper noun with distinct capitalization rules listed in the [content style guide word list](https://design.va.gov/content-style-guide/word-list) or following [SEO best practices for link text](https://design.va.gov/content-style-guide/links)

(https://design.va.gov/content-style-guide/capitalization)

## Recommended action

Review the content style guide capitalization rules and exceptions, and adjust capitalization throughout to match. 

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Capitalization](https://design.va.gov/content-style-guide/capitalization)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by GcioNapoleon** [comment]
@KKitagawa-Bosch , just finished having a quick conversation with @shiragoodman. Can you please let us know if you have a list of the specific links you want us to change so we don't accidentally change the wrong one.

**Comment by KKitagawa-Bosch** [comment]
@GcioNapoleon sure thing! I'll break it down by header for easy navigation! I've also written out each link as it should be capitalized so you can pretty much just copy and paste! 

**Resources for schools**
Everything under here is good 

**Handbooks**
These are okay as title case because they're directly referencing the titles of the handbooks

**Trainings and webinars**
The following should be sentence case: 
- Training requirements
- SCO training portal
- Office hours and webinars
GovDelivery Message Archive is fine because it's directly referencing the title of the next page, and it's title case in all instances on that page 

**Program approval information**
The following should be sentence case: 
- Licensing and certification
- National exams
- Program approvals
- Foreign program approvals
- Federal on-the-job training/apprenticeship approval
The last link under this header is unique. "State Approving Association" is a proper noun and should be capitalized, but contact information should be lowercase/sentence case 

**Upload files to VA**
"Education File Upload Portal" is not directly referenced in the word list or SEO guidance, so I could see an argument either way on this one. I'm currently waiting to hear back from the other content folks on this, I'll comment again when I get an answer! 

**Other resources for schools**
Any instance of "enrollment manager" should be lowercase/sentence case.
"Launch VA Education Platform Portal" - same as above with "Education File Upload Portal"
The following should be sentence case
- Enrollment manager user guide 
- Enrollment manager FAQs
- Institutions of higher learning
- Non-college degree programs
- On-the-job training/apprenticeship 
- Enrollment manager system updates
- GI Bill overpayments and debt
- VA debt management center
- VR&E Tungsten invoicing 
- VR&E Tungsten customer campaign 
- The 85/15 rule 
- Reporting requirements
- 35 percent exemption
- Department of Defense exemption
- Education service waiver
- Supported and non-supported students 
- Restricted aid 
- Suspension and review

**Understanding Veteran education benefits**
The following should be sentence case
- About GI Bill benefits
- How to use GI Bill benefits 



Bonus points: add the hyphen to "paper-based" in "VA Paper-Based Forms to Enrollment Manager Crosswalk"

Note that for the "enrollment manager quick start guide" links, the title after the hyphen is fine title case because it's a direct reference to the title of the guide

**Comment by GcioNapoleon** [comment]
Thank you sir

**Comment by KKitagawa-Bosch** [comment]
@GcioNapoleon re: the upload portals, other content folks are recommending those get changed to sentence case

**Comment by GcioNapoleon** [comment]
I think I've made most of the changes everything. I only had one question.

Federal on-the-job training/apprenticeship approval
The last link under this header is unique. "State Approving Association" is a proper noun and should be capitalized, but contact information should be lowercase/sentence case



Are you recommending that we change "State Approving Agency (SAA)" to "State Approving Association"

**Comment by KKitagawa-Bosch** [comment]
@GcioNapoleon No, sorry about that! Totally just a mistake on my part, thank you for catching that!

**Comment by alexisbetz** [comment]
https://jira.devops.va.gov/browse/VEBT-420
