### ISSUE TITLE
HLR | Staging Review - E2E tests and Unit Test Coverage

### ISSUE THREAD

**Issue by eileen-coforma** [department-of-veterans-affairs/va.gov-team#90553]
## E2E Test Participation
VFS teams should create at least one Cypress test spec in a tests/e2e folder in your product’s directory that follows the conventions described in the [Writing an end-to-end test](https://depo-platform-documentation.scrollhelp.site/developer-docs/writing-an-end-to-end-test) document. See [End-to-end testing with Cypress](https://depo-platform-documentation.scrollhelp.site/developer-docs/end-to-end-testing-with-cypress) for more information about writing Cypress tests on the platform.

## Unit Test Coverage
The overall product must have 80% or higher unit test coverage in each category: Lines, Functions, Statements, and Branches. Either provide a link to your product’s entry in the [Unit Test Coverage Report of the Frontend Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/) or generate the code coverage report locally for an app by running the following command within vets-website: yarn test:coverage-app {app-name}

## Tasks

- [ ] Create Cypress test spec
- [ ] Either provide a link to your product’s entry in the [Unit Test Coverage Report of the Frontend Dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/) or generate the code coverage report locally for an app by running the following command within vets-website: yarn test:coverage-app {app-name}

**Comment by Mottie** [comment]
### E2E test coverage

HLR has the following [end-to-end tests in place](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/appeals/996/tests)
- HLR contact loop tests (for contact info page)
- HLR downtime notification tests
- HLR keyboard only test (happy path)
- HLR subtask test (start page subtask)
- HLR tests
  - HLR minimal (happy path with 1 issue and an informal conference for the Veteran)
  - HLR maximal tests (2 issues, 2 added issues, and an informal conference for the Veteran's representative)
- HLR v3 test (new content tests; 2 issues, 2 added issues, and an informal conference for the Veteran's representative)

### Unit test coverage

[Frontend support dashboard](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/unit-test-coverage-report/) shows: 

98.14% Statements, 90.52% Branches, 95.83% Functions & 98.11% Lines which closely matches the results I see locally

Locally determined unit test coverage - tests that have reduced coverage in "content" and "pages" folders are due to the feature toggle code not fully covered because it is temporary, and will be removed once the new content is fully released.

<img width="872" alt="local code coverage table showing 98.14% Statements, 90.51% Branches, 95.83% Functions & 98.1% Lines" src="https://github.com/user-attachments/assets/dd75fc6d-8d3f-4d08-b053-1c5332ef67d2">
