### ISSUE TITLE
Discovery: how Profile FE app handles edits/updates

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-team#90659]
### User story

As a Cartography team member, I want to understand how the Profile app (vets-website) handles update operations, so that we can plan our NoK/EC update code.

### Notes
- Assume working in Profile react app

Possible tasks:
- 

## Acceptance criteria

- Documented in teams repo (assuming nothing sensitive) findings that will enable us to more quickly implement NoK/EC edit
- Recommend what pattern to follow
- Outline next steps: what components, containers, redux code, etc, needs to be written.

**Comment by radavis** [comment]
## Suggested front-end approach

Ticket: Feature toggle between read-only and new edit Personal health care contacts UI

Steps/Description:

Create folders `src/applications/personalization/profile/components/personal-health-care-contacts/{v0-read,v1-update}`, put existing code into `v0-read`, change import statements.

Add `_Content.jsx` and `_Section.jsx` components to `v1-edit` (following code organization in the `personal-information` folder).

Copy the necessary code from `v0-read` into `v1-edit` to display personal health care contacts.

Feature toggle the `v1-edit` code using the appropriate feature flag.

AC: Can toggle old and "new" EC/NOK UI. Note: New UI won't do much, yet.

---

Ticket: Edit EC/NOK from UI

Steps/Description:

Using api fixtures obtained from vets-api, write the necessary front end code to allow a user to edit an Emergency Contact or Next of Kin, showing a form when clicking "Edit", and writing changes directly to redux state.

This may or may not require the `<ProfileInformationFieldController />` component from `@vap-svc`, and the `<SchemaForm />` component.

AC: Can demo EC/NOK edit functionality. An e2e test exists for interacting with the form. Note: Updates won't persist, since redux actions & reducers aren't implemented.

---

Ticket: Update EC/NOK from UI

Steps/Description:

Write redux actions and reducers to update EC/NOKs by POSTing to `/v0/profile/contacts`. Connect the "save" button to the appropriate redux action.

AC: Can demo EC/NOK update functionality. Unit specs for redux code.

---

Ticket: Validate address for NOK when saving

Steps/Description:

Write redux code and UI to validate an address with the vets-api address validation service. Prompt the user to use the corrected version of the address, or the version they entered.

See `va.gov/profile/contact-information` for an example of how this is done.

AC: Can demo update functionality with address validation. Unit/e2e specs updated.

---

Ticket: Address A11y concerns for EC/NOK edit/update

Steps/Description:

Update e2e specs covering use of the feature, adding any accessibility concerns.

AC: EC/NOK edit feature is covered by e2e specs and is ready for a11y review.

**Comment by carlosfelix2** [comment]
The list of stories has been reviewed a few times. We agreed to close it as completed.
