### ISSUE TITLE
BE | IES | Discovery for the API

### ISSUE THREAD

**Issue by mtcA6** [department-of-veterans-affairs/va.gov-team#90654]
## Background 
There's an IES API! We should figure out how to connect and the best POC to work with (start with Lisa G Jefferies). 

- https://confluence.devops.va.gov/display/VAExternal/%28new%29+Individual+Longitudinal+Exposure+Record+%28ILER%29+API
- https://confluence.devops.va.gov/pages/viewpage.action?pageId=48090012
## Tasks 
- [ ] connect to the be? or find someone who can help us connect
## AC
- [ ] we've located a be we can use and have found someone to help us plug into the system

**Comment by tpharrison** [comment]
@mtcA6 Who sent you the link to the confluence doc?  I'll need to reach out and ask some questions.

**Comment by mtcA6** [comment]
@tpharrison sorry I thought i had  included that! i thought for sure I drafted a message including it I must not have submitted it. 

Lisa G. Jefferies

**Comment by tpharrison** [comment]
Emailed Lisa on Aug 15 asking for help connecting to the API.

**Comment by tpharrison** [comment]
Travis shared [this document](https://confluence.devops.va.gov/pages/viewpage.action?pageId=48090012) on Aug 19th.  See [this thread](https://dsva.slack.com/archives/C909ZG2BB/p1723145095346509) for more details.

I am able to view the [Claim Evidence API Swagger](https://claimevidence-api-int.dev.bip.va.gov/api/v1/rest/swagger-ui.html) documentation using the CAG, but I haven't been able to test anything yet.  I'm assuming I'll need to authenticate in order to do so.  Also, I believe that our staging environment hits BIS LINKTEST, and I'd like to verify that the Claim Evidence API is available in this environment for testing.

These documents may be helpful, but I am unable to view these documents (I get a 404 page not found error):

- [Developer Documentation](https://github.com/department-of-veterans-affairs/bip-vefs-claimevidence/tree/development/Documentation)
- [Wiki](https://github.com/department-of-veterans-affairs/bip-vefs-claimevidence/wiki)

Travis sent an email to Thomas Moore explaining our situation and asking for assistance in getting connected to the appropriate API.

Waiting to hear back...

cc/ @mtcA6 @ACParker89

**Comment by mtcA6** [comment]
asking VEO to bump the email chain to see if chris will respond

**Comment by tpharrison** [comment]
Chris Miller replied in our email thread on Thu, Aug 8th...
> _we are looking at who can help with this discussion on this side and we will set up a meeting next week._

**Comment by mtcA6** [comment]
Requested meeting time for 9/4 3-4:30pm ET 🕺

**Comment by tpharrison** [comment]
Created slide deck with questions for VBMS/VA.gov ILER meeting on 9/4.

**Comment by ACParker89** [comment]
For Sprint 45: We need to discuss the BE further to find next steps for our API. 

New discovery ticket is being created for next steps/mapping - AC Determine path forward 

Scott Simon is POC for this - meeting set up by Lisa Jefferies on Thursday 9/12
