### ISSUE TITLE
Pension | Findings | Separate processing_attachments from sidekiq job perform

### ISSUE THREAD

**Issue by wayne-weibel** [department-of-veterans-affairs/va.gov-team#90724]
The `upload_to_lighthouse` function is combining 2 steps - processing attachment and calling the async job - we want to separate these calls.

#90282

Tasks:
- [x] refactor to use `process_attachments!` (see parent SavedClaim)
- [x] call `perform_async` for the job from the controller (not the model)
- [x] add error catch and logging for processing attachments

Acceptance:
- [x] eliminate use of `upload_to_lighthouse`
- [x] error logging for `process_attachments` appears in DataDog
- [x] 100% code coverage
- [x] 100% documentation

**Comment by danlim715** [comment]
@wayne-weibel The `process_attachments!` function also performs 2 steps similar to `upload_to_lighthouse`. It also processes the attachments but calls the `SubmitBenefitsIntakeClaim` async job instead of our `PensionBenefitsIntakeJob`. Do we really want to call that job as well as our `PensionBenefitsIntakeJob`? Or are we planning on deprecating the use of the `PensionBenefitsIntakeJob`? Our `upload_to_lighthouse` function was built to replace `process_attachments!` and call our `PensionBenefitsIntakeJob` instead of the `SubmitBenefitsIntakeClaim` job. Please advise.

**Comment by wayne-weibel** [comment]
> [@wayne-weibel](https://github.com/wayne-weibel) The `process_attachments!` function also performs 2 steps similar to `upload_to_lighthouse`. It also processes the attachments but calls the `SubmitBenefitsIntakeClaim` async job instead of our `PensionBenefitsIntakeJob`. Do we really want to call that job as well as our `PensionBenefitsIntakeJob`? Or are we planning on deprecating the use of the `PensionBenefitsIntakeJob`? Our `upload_to_lighthouse` function was built to replace `process_attachments!` and call our `PensionBenefitsIntakeJob` instead of the `SubmitBenefitsIntakeClaim` job. Please advise.

I would like to return to the more descriptive `process_attachements!` (can override that function in Pension::SavedClaim to only be what it should) and have the call to PensionBenefitsIntakeJob separate and explicit (`upload_to_lighthouse` was the quick and dirty stopgap during mvp).  It would be very nice if we could deprecate the pension specific job, but I have a feeling with moving to modules we will end up going the other way, since SubmitBenefitsIntakeClaim is used by several other forms.

**Comment by balexandr** [comment]
PR for ref: https://github.com/department-of-veterans-affairs/vets-api/pull/18671
