### ISSUE TITLE
Refactor MVI Lookup to allow search by user attributes

### ISSUE THREAD

**Issue by kevinmirc** [department-of-veterans-affairs/va.gov-team#9083]
Refactor MVI Lookup in Form1010cg::Service to not build a UserIdentity

Background: MVI relies on a user profile to search for attributes. On the 10-10CG, we create a mock profile to be able to query the data. We'd like to change the MVI interface to allow searches with only user attributes, without needing to create that mock profile. 

Our goal is to reduce complexity of the attribute search functionality. 

See: https://github.com/department-of-veterans-affairs/vets-api/pull/4064#discussion_r424115957

Use the `MVI::Attributes` service

**Comment by kevinmirc** [comment]
`MVI::Attributes` is tightly coupled to `HCA` (has on Faraday client, with own config and service name), so I can't use this service for `Form1010cg::Service`.

Can either follow suit and make an independent `CARMA_MVI` service or merge the `MVI::Attributes` features to `MVI::Service` and make all consumers use the same generic service.

Waiting to hear others' input: https://github.com/department-of-veterans-affairs/vets-api/pull/4064#discussion_r452275225

**Comment by bosawt** [comment]
@nsoutouras This is an interesting refactor, I think this is important (maybe medium priority), but I think we should come up with a different idea rather than the suggestion in this ticket.

Basically, one of our goals is to isolate MPI from other services, but there are certain forms that need the ability to query based off input attributes that may not be the attributes of the logged in user. We should come up with an idea of how we want to support this functionality, and force these forms to use that interface
