### ISSUE TITLE
[Congressional] V12070551 Due 9/16/24 (Rep. Buchanan) 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#90847]
## Issue Description
Veteran's VA login is completely incorrect with regards to his military history. Veteran previously reach out to VBA St. Pete but they were unable to resolve the issue.

https://app.slack.com/client/T03FECE8V/C02BS78NYRM?selected_team_id=T1ZD0UBMZ
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
8/23:  Sent email to Veteran advising that direct contact must be made with DMDC in order to have his requested information updated.

**Comment by Kimberley2023-CSM** [comment]
8/19 3:00 PM: Case sent to the EVSS team to investigate.
4:37 PM EVSSs Update on case: EVSS HD reviewed the information provided, audited the veteran’s account and logged internal JIRA ticket #ETSHD-2598, for tracking and recording of this issue. Unfortunately, this is not something EVSS can resolve for the veteran. The issue in question is with the DEERS record, and is a field that EVSS does not have the DEERS permissions to fix. For this issue DMDC requires the veteran to contact them directly. EVSS spoke to the veteran to inform them of this, and provided them the support contact information they will need, in order to get this resolved. (edited)

**Comment by Kimberley2023-CSM** [comment]
8/23:  Sent email to Veteran advising that direct contact must be made with DMDC in order to have his requested information updated.

**Comment by Kimberley2023-CSM** [comment]
Sent another email verifying that the Veteran was able to complete their task.
One additional email attempt remaining and a final phone call.

**Comment by Kimberley2023-CSM** [comment]
9/10/24: Sent 3rd and final email attempting to confirm the Veteran was able to complete his task.  Final email attempt.  Last attempt will be via phone call on Thursday, September 12th

**Comment by Kimberley2023-CSM** [comment]
9/19/24:  Sent email for status update to Chante.
