### ISSUE TITLE
Implement Get Single Claim endpoint

### ISSUE THREAD

**Issue by kjduensing** [department-of-veterans-affairs/va.gov-team#91011]
## Description
In order for the claim details page to get a single claim detail - we need an endpoint on vets-api that returns only a single claim based on claim ID.

## Notes
- The recommended solution: call the endpoint we have and pull out the matching claim by ID
- The recommended solution is not the permanent solution. To reduce delivery time, we've made the decision to not rely on the API team finishing a claim details endpoint in the short extension period. when we move on to complex claims and or claim management, we'll need more robust claim details support.

## Questions
- How do we handle the different cases?
  - 0 claims for 1 appt at 1 facility
  - 1 claim for 1 appt at 1 facility
  - 1 claim for 2 appts on the same day at 1 facility (_assign to first appt of the day case_)
  - 2 claims for 2 appts on the same day at 2 facilities
  - 2 claims for 2 appts on diff days at 1 facility
  - 

## Response Schema
```json
{
  "data": {
        "id": UUID,
        "claimNumber": STRING,
        "claimStatus": ENUM(string),
        "appointmentDateTime": STRING,
        "facilityName": STRING,
        "createdOn": STRING,
        "modifiedOn": STRING
      }
}
```

## Back end tasks
- [x] Client code written - calls correct endpoint
- [x] Service code written - transforms/processes response from client
  - [x] Handle errors
- [x] Controller endpoint written
- [x] Config
  - [x] settings.test.yml updated if needed
  - [x] settings.local.yml updated if needed
  - [x] settings.yml updated if needed
  - [x] [infra-manifests](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/infra-manifests-context.png) [updated if needed](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/engineering/infra-manifests-behavior.png)
    - [x]  [dev](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/dev)
    - [x]  [staging](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/staging)
    - [x]  [prod](https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/tree/main/apps/vets-api/prod)
- [x] Tests written
  - [x] Unit
    - [x] Happy path
    - [x] Exhaustive failure paths
  - [x] Integration
  - [x] VCR Cassettes
  - [x] Betamocks registration
- [x] Mock data
- [ ] Testing
  - [x] Unit tests pass
  - [ ] QA testing - try to break it in staging
- [x] Improve 1 thing about the codebase
- [x] Swagger docs updated

## Acceptance Criteria
- [ ] I can use postman/insomnia/curl to hit the endpoint: /travel-pay/claims/{claim_opaque_id} and get a single claim back for a claim that belongs to 1 appointment
- [ ]  I can use postman/insomnia/curl to hit the endpoint: /travel-pay/claims/{claim_opaque_id} and get a single claim back for a claim that belongs to many appointments
- [ ]  I can use postman/insomnia/curl to hit the endpoint: /travel-pay/claims/{claim_opaque_id} and get a 404 if there is no claim for an appointment

## Definition of Done
- [ ] All acceptance criteria are met
- [ ] Documentation is updated

**Comment by ayush-chak** [comment]
In some cases, Veterans might have multiple appointments on the same day, either at the same or different facilities. 
We have sketched out a few possible options:

We only display one appointment per day/claim
We display all the appointments per day/location for a single claim

A - 0 claims for 1 appt at 1 facility
B - 1 claim for 1 appt at 1 facility
*C - 1 claim for 2 appts on the same day at 1 facility (assign to first appt of the day case) - 1 SMOC claim*
Because the portal and CIE both associate claim to the first appointment of the day, even if two appointments to the first facility, a user might click on one appointment on that day and see that there is a claim and be able to go check the status of it. When they go back and click on the other appointment, they would see that there is no claim associated (to that appointment), but we also don't want to allow claim creation since it's a second appointment on the same day.

1. How often does this happen?
2. How do we display that information to this user?
- When they're viewing a claim details page, do we show a list of appointments to which that claim is associated?
- When they're viewing either appointment for that day, do we just show them the same link?



D - 2 claims for 2 appts on the same day at 2 facilities - manual review for 1 claim since one of these is not their home facility
E - 2 claims for 2 appts on diff days at 1 facility - 2 SMOC claims
F - 2 claims for 2 appts on diff days at 2 facilities - manual review for 1 claim since one of these is not their home facility
