### ISSUE TITLE
Cleanup merge_clinic logic in appointments controller and service

### ISSUE THREAD

**Issue by cferris32** [department-of-veterans-affairs/va.gov-team#91164]
Through some recent talks with web we realized that we can pull the station and ien fields needed for the avs flow from fields straight off the appointment response body rather than needing to dig into the indentifier field like the `extract_station_and_ien` method does, so this work will be to clean up that method and ensure it's no longer needed.

AC:
[ ] - cleanup of `extract_station_and_ien` method
[ ] - ensure avs flow still functions correctly
[ ] - test updates

**Comment by JunTaoLuo** [comment]
After discussing with @simiadebowale @cferris32 we decided to not update the current logic for extracting station and ien fields since the `/vaos/v1/patients/#{user.icn}/appointments` API do not explicitly return this directly. Instead of digging through the `/vaos/v1/locations/#{station_id}/clinics` API for this information via `stationId` and `id` we'll stay with the current logic for extracting staion and ien fields from `identifiers` from the `/vaos/v1/patients/#{user.icn}/appointments` API.

However, in this process we noticed there is some cleanup we can do in the `appointments_controller` and `appointments_service` for logic that merge clinic information with the appointment so we're repurposing this issue to track that work instead.

**Comment by ldelacosta** [comment]
There are still open items for this ticket. This ticket will most likely be moved to the next sprint. FYI @Bren22va @JRRoof @simiadebowale

**Comment by simiadebowale** [comment]
@ldelacosta - checking on what the open items are for this ticket?

**Comment by ldelacosta** [comment]
@cferris32 advised yesterday that we should leave this ticket open as there's some open items around that work still. 

@cferris32 - can you re-confirm again?

**Comment by ldelacosta** [comment]
Discussed with the development team today. No additional work is needed. Closing out the ticket.
