### ISSUE TITLE
Write-up for form-within-a-form experiences

### ISSUE THREAD

**Issue by juliepedtke** [department-of-veterans-affairs/va.gov-team#91195]
See list of questions from CAIA: https://github.com/orgs/department-of-veterans-affairs/projects/1263/views/6?filterQuery=assignee%3A%40me+sprint%3A%22Sprint+36%22++-status%3ADone&pane=issue&itemId=71608308

- [x] Review Slack thread of past conversations
- [x] Write up our responses based on research (start in G Doc for easy collab)
- [x] After internal alignment, share back via Slack/Github TBD

**Comment by rubensun** [comment]
We're looking to restructure the writeup in 3 sections focusing on **_structural_**, **_navigational_** and **_presentation_** concerns. Additional areas we're looking to firm and finalize recommendations relating to:
- Overall form instruction
- Additional Forms Section
- Form sub-sections / Pages, including prompts from one set of forms
- Form Sub-sections / Pages, including prompts from multiple forms
- Sections / Pages Embed prompts from a different form

**Comment by nnicholas7** [comment]
The form within a form write-up is complete and is currently located in [Google docs](https://docs.google.com/document/d/1v3Bu-6vYhLq2HyCJKOY6k3YhHy1IKNjGDkjSjkVU7fk/edit).  The reason we have not uploaded to Github is because we want to make sure the suggestions from research are things we are able to do in the design system and provide an explanation for the final decisions that are made. We are working with Jina to implement the items from this write-up.

**Comment by nnicholas7** [comment]
This document has been migrated to #Slack
https://dsva.slack.com/docs/T03FECE8V/F07NBTCBC11
