### ISSUE TITLE
[Bug] Form 526: Strip unallowed characters from treatmentCenterName before sending to evss

### ISSUE THREAD

**Issue by annaswims** [department-of-veterans-affairs/va.gov-team#9121]
About 500 form 526 submissions were rejected over the past week due to characters that EVSS doesn't like, for example
````js
    {
      "treatmentCenterName": "VA Medical Center, Miami Florida",
      "treatmentDateRange": {
        "from": "[REDACTED DATE]"
      },
````
was rejected by EVSS, due to the comma.
and we got bac this response from evss
{message="[{"key"=>"form526.treatments[0].center.name.Pattern" "text"=>"must match \"([a-zA-Z0-9\"\\/&\\(\\)\\-'.#]([a-zA-Z0-9(\\)\\-'.# ])?)+$\"" "severity"=>"ERROR"}]"}

[prometheus data over past week](http://prometheus-prod.vetsgov-internal:9090/prometheus/graph?g0.range_input=2w&g0.expr=sum(increase(worker_evss_submit_form526_non_retryable_error%7Bmessage%3D~%22.*must%20match.*%22%7D%5B1w%5D))%20&g0.tab=0). we would expect this rate to go to 0 after the fix.  

[relevant graphana graph](http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?panelId=10&edit&fullscreen&orgId=1&from=now-7d&to=now)

**Comment by SarahJaine** [comment]
The dotted blue line in the below graph denotes the approximate time my PR was deployed in production.  It's clear that the regex errors for facility name dropped after that deploy, but I'm a little concerned that there are any errors at all.  My understanding is that the regex error was a non-retryable error so the errors can't be submissions made before the fix that were retried automatically after the fix.
<img width="1421" alt="Screen Shot 2020-05-22 at 6 04 34 PM" src="https://user-images.githubusercontent.com/9893700/82715085-29776600-9c57-11ea-8f50-d4e82d8446b4.png">
http://grafana.vfs.va.gov/d/000000066/evss-526-submissions?panelId=16&fullscreen&orgId=1&from=1589666981815&to=1590358181815

**Comment by annaswims** [comment]
The PR you made was a huge fix, but the regex is odd.  It won't match if there are two spaces in a row. 
<img width="720" alt="Screen Shot 2020-05-28 at 12 25 06 AM" src="https://user-images.githubusercontent.com/19188/83098961-f2032200-a079-11ea-96ac-92b4ddd36a9b.png">

**Comment by annaswims** [comment]
or even worse... `123 Street , Whatevertown, MD`

**Comment by SarahJaine** [comment]
The second dotted blue line (reading left to right) represents the time the second fix (PR 4347) went into production. We haven't seen any regex errors in the 21 hours since the second fix.  In that same time period we've had 733 successful submissions so I'm sure that this isn't due to a lack of traffic.  In 21 hours before the fix, we had about 20 regex errors, so there's no reason to think that users simply stopped typing in a way that would normally have resulted in a regex error.  The two PRs together have successfully resolved this error.
![Screen Shot 2020-06-03 at 11 11 58 AM](https://user-images.githubusercontent.com/9893700/83661027-2fd8dc80-a58b-11ea-8e5e-b0cad96903d2.png)
