### ISSUE TITLE
DR | Refactor form submission logic

### ISSUE THREAD

**Issue by shaunburdick** [department-of-veterans-affairs/va.gov-team#91324]
## Value Statement

Do a code review on the process of form submission to identify any failure points that would result in an entry not being added to `saved_claims` but the form is submitted. Come up with a plan to notify when that might happen and how to remediate.

---

## Background Context

- Check to be sure there is no way for a submission to skip the storage step, opening us up to a new form of silent failure

## Outcome, Success Measure, KPI(S), and Tracking Link

- Code review and remediation plan

## Definition of Ready

- [ ] Clear value description
- [ ] Testable acceptance criteria
- [ ] Accessibility added to acceptance criteria
- [ ] Approved designs attached
- [ ] Sample data provided where appropriate
- [ ] Estimated to fit within the sprint
- [ ] Dependencies and blockers linked

## Definition of Done

- [ ] Meets acceptance criteria
- [ ] Passed E2E testing (90% coverage)
- [ ] Passed unit testing (90% coverage)
- [ ] Passed integration testing (if applicable)
- [ ] Code reviewed (internal)
- [ ] Submitted to staging
- [ ] Team approved production verification process
- [ ] Reviewed and approved by product and/or design

**Comment by dfong-adh** [comment]
There are three places where we are currently storing the submitted form request in the `saved_claims` table:
* [HigherLevelReviewsController](https://github.com/department-of-veterans-affairs/vets-api/blob/91b759275b1cd82096f3e1952360ce74f3da1daf/app/controllers/v1/higher_level_reviews_controller.rb#L28)
* [SupplementalClaimsController](https://github.com/department-of-veterans-affairs/vets-api/blob/91b759275b1cd82096f3e1952360ce74f3da1daf/app/controllers/v1/supplemental_claims_controller.rb#L110)
* [NoticeOfDisagreementsController](https://github.com/department-of-veterans-affairs/vets-api/blob/91b759275b1cd82096f3e1952360ce74f3da1daf/app/controllers/v1/notice_of_disagreements_controller.rb#L27)

We are currently logging the guid and error message on [DecisionReview::SavedClaim::Service](https://github.com/department-of-veterans-affairs/vets-api/blob/91b759275b1cd82096f3e1952360ce74f3da1daf/lib/decision_review/utilities/saved_claim/service.rb#L22) but not reraising any exceptions, to avoid blocking the request.

These are the identified situations where a SavedClaim record *is not* created for a DR form submission are as follows:
* DB error when saving `AppealSubmission` or `SavedClaim` records. An error message is logged for these events.
* Feature flag [decision_review_form_store_saved_claims](https://github.com/department-of-veterans-affairs/vets-api/blob/91b759275b1cd82096f3e1952360ce74f3da1daf/lib/decision_review/utilities/saved_claim/service.rb#L16) is disabled. Nothing is logged for this event.

Possible Solution:
1) Refactor controllers to persist a record to SavedClaim with a placeholder guid before submitting an API request to LH
1) Submit form to LH
1) Update the SavedClaim record with the LH response guid
1) Add a log message to be a backup remediation step of the mapping from the old to new guid values

If an error occurs, raise an exception and log the guid. This will require cleanup of orphaned records if there is an error with obtaining the LH response guid.

Alternative Solution:
1) Move SavedClaim persist as early as possible after receiving a response from LH and raise any exceptions instead of only logging 

Additional tasks:
* Add a DD monitor for error messages to email/slack
* Remove feature flag to prevent accidental disabling of flag

**Comment by shaunburdick** [comment]
New Steps:
1. Submit to LH
2. Create DB Transaction
3. Create `AppealSubmission` record
5. Create `SavedClaim` record
6. Kick off SideKiq Jobs (Evidence, 4142)
8. Delete `InProgressForm` record
9. Commit DB Transaction
10. Respond to request

Rescue Statement to catch any errors in that process, and response with error prompting user to resubmit.

**Comment by eileen-coforma** [comment]
In progress. Moving some of the code so everything's in the transaction. PR will be ready by today.

**Comment by eileen-coforma** [comment]
PR is ready for code review. May be in conflict with another PR. We'll figure it out after.

**Comment by eileen-coforma** [comment]
Conflict has been fixed. Will be merged after platform team reviews.

**Comment by dfong-adh** [comment]
Needs a code review from the team + platform

**Comment by eileen-coforma** [comment]
Derek to include Molly and Robin for a code review walkthrough

**Comment by eileen-coforma** [comment]
Code review completed. Needs tests to stop timing out to get this merged.

**Comment by eileen-coforma** [comment]
Need to message platform for review, so it can be merged.

**Comment by dfong-adh** [comment]
PR has been merged.

**Comment by dfong-adh** [comment]
Changes have been validated in staging, no errors. Production logs being monitored as well.
