### ISSUE TITLE
[Call Center] Call Center Cadence

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#915]
## User Story
As a VSP member with work in Call Center, I need to determine a call center-based workflow so I can efficiently prioritize my work and understand call center needs as necessary.

## Goal
Call Center workers will meet on Wednesday, 8/14/19, to discuss and determine work cadence around call center issues.

## Acceptance Criteria
- [x] Meet with Call Center leads to determine best workflow
- [x] Agree on and follow through with determined workflow (sprint cadence

## Questions to be Discussed
- Which meetings should/can Chante and Kimberley attend on Triage and Insights?
   - How will participation in those meetings look like?
- How will Call Center issues be managed on Github?

## Definition of Done
- [x] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2019** [comment]
In order to for Call Center, Insight/Analytics, and Triage to remain on the same page and not duplicate efforts the following decisions have been made collectively.

Kimberley and Chante will attend Insight and Analytics daily standups unless otherwise informed.
Kimberley will attend Triage meetings held on Monday, Wednesday, and Friday.
Kimberley will report any viable data back to Chante.
Kimberley and Chante will continue to hold stand up each Tuesday.
Ad hoc meetings will be held between members (departments) if needed.
Proper labeling of ZH tickets
Triage incident vs Triage
Triage = Items that the triage team is working on
Triage Incident =  An incident reported from another team that needs to triaged
Insight/Analytics
Tickets will be flushed out by Chante
Tickets not a top priority
Proper assigning of ZH tickets
Chante will determine if Kimberley needs to be added as an assignee to ticket

**Comment by joanneesteban** [comment]
@Kimberley2019 looks good! Next step will be to put it in a formatted version on the Call Center repo (or whichever folder call center will live on).

**Comment by Kimberley2019** [comment]
Document has been created in GitHub and linked to this ticket.
Requesting that other assignees assist in the definition of being done @clantosswett @joanneesteban Confirmation has been provided by @alexpappasoddball
