### ISSUE TITLE
Analytics Reporting Request for Jen L

### ISSUE THREAD

**Issue by joanneesteban** [department-of-veterans-affairs/va.gov-team#9151]
# Metrics Reporting Request

## Description
**Who is this request for?**

Jen L

**What team/project is this work for?**

Covid Content
    
## Timeframe for Analytics Requested
Since page launch

## Analytics to Track Down

**Download data on:**
https://www.va.gov/welcome-kit/

_specifically the welcome kits and COVID FAQ:_
https://www.va.gov/va-welcome-kit-bw.pdf
https://www.va.gov/va-welcome-kit-color.pdf
https://www.va.gov/covid-19-links-and-resources.pdf

## Which Product Questions are you trying to answer?

What are VA.gov users looking to download on COVID FAQ?
Is there anything we need to change about the content we're delivering?

## Acceptance Criteria
- [ ] The data has been identified and documented in this ticket - items that we don't have access to are noted with _cannot be accessed_
- [ ] The metrics are shared back with users.

## Definition of Done
- [ ] All appropriate issue tagging is completed
- [ ] All AC completed

**Comment by jonwehausen** [comment]
Hi @JenLJ ,

Confirming receipt, thank you!

**Comment by bsmartin-ep** [comment]
@jonwehausen / @joanneesteban -

Here are all PDF downloads on the _Welcome Kit_ page for the last 30 days...

https://analytics.google.com/analytics/web/#/report/content-event-events/a50123418w177519031p176188361/_u.dateOption=last30days&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100&explorer-table.secSegmentId=analytics.pagePath&explorer-table.advFilter=%5B%5B0,%22analytics.eventAction%22,%22RE%22,%22PDF%22,0%5D,%5B0,%22analytics.pagePath%22,%22BW%22,%22www.va.gov~2Fwelcome-kit%22,0%5D%5D/

Do you think this covers her request?

**Comment by jonwehausen** [comment]
Hi @jenniferlee-dsva,

The report Brian linked to above allows you to see each of the 3 welcome kit downloads addressed in your ticket. You can see the report has been filtered to only include downloads that occurred on the www.va.gov/welcome-kit/ page. 

**Total Events** will refer to the total number of times that PDF was downloaded (including duplicates). 

**Unique Events** will refer to the unique number of times that PDF was downloaded (excluding duplicates, unique to the user)

You can also adjust the date range back to the time period needed since launch. 

@jenniferlee-dsva we are going to close this ticket, please let us know if this report does not meet you needs. 😄

**Comment by jenniferlee-dsva** [comment]
@jonwehausen - one question. When I go to compare the same period in 2019, it looks like there were 0 downloads. Is that because we were not tracking downloads last year or because there just wasn't?  Trying to suss out if the 2020 numbers are due to VA's  email and newsletter promotion this year driving ppl to the COVID PDF and the Welcome Kit or if it's just that we weren't tracking last year.

**Comment by bsmartin-ep** [comment]
@jenniferlee-dsva -

Yes - it does appear PDF tracking was begun in July 2019 and enhanced (or possible fixed) in October 2019...

![image](https://user-images.githubusercontent.com/62304138/82241989-138e3c00-990b-11ea-8d3f-acae51a74d33.png)
