### ISSUE TITLE
[Development/Design] BDD: Add Wording for Exam Availability

### ISSUE THREAD

**Issue by luke-gcio** [department-of-veterans-affairs/va.gov-team#9152]
## User Story or Problem Statement
Barry Cooper has identified a requirement that we provide messaging to the veteran to remind them they need to be available for exams once they submit their application.  We had asked Barry "how many" and he said it depends on how many things you are filing for since it requires different doctors/exams for most.  Therefore, the wording should be pretty generic.

Question for the design - should it be included at the start of the application somewhere as well as at the end when the submission occurs?

## Acceptance Criteria
- [ ] We have the messaging in the appropriate places on the BDD flow

## How to configure this issue
- [x] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to an Epic** (what body of work is this a part of?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by kevinstachura** [comment]
We have wording for exam availability in the gating:

_"Please be aware that you will need to be available for 45 days after you file in order to complete VA exams during this period."_

But we should also add this same wording as a paragraph under the bulleted list in the Preparation section of the intro page:

https://staging.va.gov/disability/file-benefits-delivery-at-discharge-form-21-526ez/introduction

<img width="738" alt="Screen Shot 2020-06-02 at 3 54 40 PM" src="https://user-images.githubusercontent.com/54544300/83563616-6100d080-a4e9-11ea-9a6f-f8333396d4fc.png">

I will make this change in the design. For the sake of time however I will ask @ndsprinkle to make this content change in staging as well.
