### ISSUE TITLE
Staging Review finding: Appointment details title different from h1

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#91563]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Appointments FE Team
**Product:** Appointments
**Feature:** Medication Review

## Findings details
**VA.gov Experience Standard - issue:** [User can't determine where a page is within the VA.gov website.](https://design.va.gov/about/experience-standards/#user-can-determine-where-a-page-is-within-the-vagov-website)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

On appointment details pages, the <title> is `[Type of] appointment on [date] | Veterans Affairs`, but the H1s on these pages are, `Type of appointment`.

<details><summary>Link, screenshot or steps to recreate</summary>

<img width="261" alt="Screenshot 2024-08-26 at 11 07 46 AM" src="https://github.com/user-attachments/assets/0b304693-ed7f-4f80-b2ca-b137a392fa53">

</details>

## Recommended action

The first part of the<title> tag before | Veterans Affairs should match the text in the H1 on the page. See [guidance on title tags](https://design.va.gov/content-style-guide/title-tags) for more details.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** [Page titles and section titles](https://design.va.gov/content-style-guide/page-titles-and-section-titles)
- **Context:** N/A

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by outerpress** [comment]
Note: I originally dropped this in the wrong ticket, moving here

----

Hi @erinrwhite ! Sorry for the screed; a lot of background on our page headings/titles follows. I wanted to capture this in one spot since questions about this come up a lot, and this will hopefully get us toward a better solution (I dropped some options at the bottom). 

### What we’re trying to solve

Veterans identify/differentiate their appointments primarily by looking at what each appointment is for, and when it is. 

For example, if one has four mental health appointments in a month, they could easily differentiate them from an upcoming primary care appointment by the date, and comparing the type of care. 

However, we aren’t able to display type of care data for many appointments. So for the details pages we use status (past, canceled), modality (i.e. “In-person appointment” or “Canceled request”), and date in the title. Here’s what that looks like in the browser history:

<img width="779" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0dhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd46db785af271a4e5e00362704766c8fa916012/Screenshot%202024-08-29%20at%208.33.22%E2%80%AFAM.png" alt="Screenshot 2024-08-29 at 8.33.22 AM.png" />

For the H1 on the details page, we use just status, modality and whether it’s an appt or request. The date of the appointment follows in the appt data below that.

The feedback is to make the title and heading the same. Before we get there, here’s some guidance we’ve looked at to get us to the current iteration:

### H1’s/titles should be unique

Previously, we used only date and time as the heading. This is technically unique but this turns the browser history/open tabs into a list of dates, which aren't descriptive of the page you want and don't help identify the appointments.

When we worked through the redesign, we discussed this issue with accessibility SMEs and they agreed that multiple tabs named only with a date wouldn’t be helpful. Uniqueness is an a11y best practice, not a hard requirement - a descriptive title is the main goal.

### Headings should clearly and quickly tell people the main purpose of the page—what they can do or what information they can get on that page.  

[From the content guidelines.](https://design.va.gov/content-style-guide/page-titles-and-section-titles)

Without type of care data, we do this by telling users the status (past, canceled), whether it’s an appointment or request, and how they will attend it. 

### H1’s/titles should not contain PHI/PII
This is a new requirement. I think it’s mainly because this data shouldn’t be exposed in Google Analytics, but there might be other reasons. Given this, even if we had type of care data, we likely shouldn’t use it in the browser title to avoid issues with exposing PHI/PII in our analytics. (I’d argue that we should still use it as page title, but that’s a future that might never exist so I’ll leave that alone.)

### Try to keep page titles to 52 characters maximum, with spaces. 

If we included the date and time in the H1, it would often go over this limit I believe it would be difficult to read an understand.

For example, this is 60 characters:

`In-person appointment on December 5th, 2024 at 5:00 p.m. ET`

More important, this is a lot of information for someone to parse out from a heading: 
<img width="493" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK09hQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9bd92badb7c5061533eb053fe75a884c6c841b7/Wednesday%2C.png" alt="Wednesday,.png" />

That's why we broke out date and time info during the redesign, to make the page easier to scan and understand.

### Possible solutions

If we’re trying to match the title to the h1 we could:

#### Include the date in the H1

I wouldn’t do this just because it’s too much information for the heading.

#### Use just the date as H1 and Title

I’d argue against this one too, since date alone isn’t descriptive of the page or its purpose.

#### Show only status and modality in the title tag

This could work, but if I was looking through my history for mental health appointments I’ve had in a given month, I would have no way of distinguishing them. They would just be listed as: 

```
Past video appointment
Past video appointment
Past video appointment
Past video appointment
```

#### Other ideas?

I don't think any of these work better than what we have - open to other ideas! And thanks for reading this far :)

**Comment by outerpress** [comment]
Hi @erinrwhite ! Just following up, do you have any recommendations based on my novel in the previous comment?

**Comment by erinrwhite** [comment]
@outerpress thank you for the nudge! I appreciate all the background.

It seems to me that the most vanilla option, `Show only status and modality in the title tag` (and h1) is probably the best. It doesn't really reveal specifics of PII/PHI in the title tag, and if that information is in the H1, the date/time will be listed adjacent to it on the page. It's not super exciting but I think it's a solid move. @sterkenburgsara might have thoughts here as well.

**Comment by outerpress** [comment]
Thank you @erinrwhite ! @sterkenburgsara I added this to the agenda for next week's SME sync

**Comment by sterkenburgsara** [comment]
@erinrwhite @outerpress yes, the identification of PHI/PII risks in the auth experience details pages has forced a pivot, where we can no longer comply with current VADS standards for title tags at this level of the experience. Having the title tag or URL match the page title could inject PHI/PII into data that gets passed into data collection platforms such as GA4, Datadog, etc. We are being asked to mitigate this.

Knowing the title tag isn't a match with the H1 in order to avoid PHI (this has been approved by the 508 office) I think you all could consider the following: 
* Leave it as is: appointments title tags were not an identified risk, and they are fine as-is
* Update to more closely align your title tags with what the other "big-4" health tools are doing for consistency (examples below), however you'll lose some accessibility value in the uniqueness that your current tags present if we go this route (again, it was approved by the 508 office, so I do think it's acceptable):
  * Care Summaries And Notes Details - Medical Records | Veterans Affairs
  * Lab And Test Results Details - Medical Records | Veterans Affairs
  * Conversation - Secure Messages | Veterans Affairs

cc @rileyorr

**Comment by benbrasso-agile6** [comment]
I'm just here admiring all this work, collaboration, communication, and attention to detail 😃

**Comment by outerpress** [comment]
@erinrwhite @sterkenburgsara I'm okay with dropping the date from `title` tags so we can match `h1` and `title`.  

I would continue breaking from the big-4 pattern and keep modality and status in the title tags and h1s. I'd worry that if every appointment had a title like `Appointment Details - Appointments | Veterans Affairs` it would make it hard to find appointments in your tabs and history.

But @sterkenburgsara your examples bring up two more questions: 

- Should we include `- Appointments` to align with the other tools? 
- Should we use Title Case for browser titles? I'm guessing yes because I see it in all the examples [here](https://design.va.gov/content-style-guide/title-tags) but it's not explicitly called out.

  
For example:

Current title tag: `Past in-person appointment on Saturday, August 31, 2024 | Veterans Affairs`

New title tag: `Past In-person Appointment - Appointments | Veterans Affairs`

@rileyorr I'm def interested in a11y perspective on all of this since a lot of this conversation started from accessibility concerns around uniqueness.

**Comment by rileyorr** [comment]
@outerpress although the Section 508 office approved title tags not matching H1s for MHV products that pose a PHI/PII risk, my recommendation from an accessibility perspective would be to keep the uniqueness since this tool's title tag format doesn't pose any PHI/PII risks. Additionally, it would be worth considering the pros and cons of prioritizing accessibility and the user experience vs consistency across the big-4 tools using a title tag pattern that we know isn't ideal.

[WCAG Success Criteria 2.4.2 Page Titled](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-title.html) is meant to help users quickly identify if a web page is relevant to their needs without requiring them to read/interpret page content. It accomplishes this by making sure the page titles clearly describe their topic and purpose. For example, having unique titles for appointments helps users quickly orient themselves to make sure they're viewing the correct appointment they had intended to. It's also helpful for differentiating content if multiple tabs are open.

I would also recommend avoiding redundancy when possible by not including 'Appointment' twice in the title tag. But I will defer to @sterkenburgsara since IA is not my specialty! 

Hopefully that helps - let me know if you have any questions.

**Comment by rileyorr** [comment]
@outerpress I would recommend keeping the date in because that's the unique identifier that separates appointments from each other. The tag I'm referring to is `Past in-person appointment on Saturday, August 31, 2024 | Veterans Affairs`

If you use the new title tag `Past In-person Appointment - Appointments | Veterans Affairs` then every appointment the Veteran navigates to will display that title tag, so there's no way to differentiate between them by title alone. 

For example, if a Veteran has a couple appointments coming up and they open both in separate tabs and navigate between the two then both would have the same title tag. So it's not readily apparent which appointment they're switching tabs to until they've selected one of the tabs and search for more details within the page. 

I've added a recording for reference of what the new experience is like in the Secure Messaging tool since they've updated their title tags to remove PII/PHI: 

https://github.com/user-attachments/assets/25db57c6-7a0b-4b8a-9474-0ef601915115

In the recording I've navigated to the inbox and opened the first two messages in separate tabs. After both pages load the title tag reads `Conversation - MHV Secure Messaging | Veterans Affairs` for both conversations.

**Comment by outerpress** [comment]
That makes sense to me @rileyorr . I'll distill this down to some guidelines and we'll see how far apart we are - @erinrwhite @sterkenburgsara as well, everyone feel free to push back on any of this:


### Title tag guidelines
- Shouldn't include PHI/PII - namely type of care, and any information about the user
- Should include the H1 of the page, but doesn't need to match it exactly - it can include more information
- Are as unique wherever possible, with exceptions as noted for other tools above.
- Are written using Initial Case (found this in the [title tag guidelines](https://design.va.gov/content-style-guide/title-tags))


### Patterns

Appointment details: `[Status][Modality] Appointment On [Date] - Appointments | Veterans Affairs`

Request details: `[Status][Modality] Request For Appointment - Appointments | Veterans Affairs`

(Note - Veterans can request multiple dates for the same request, or the same date for different requests, so we don't have anything to make these completely unique.)

### Open questions
- Do we need to include the `- Appointments` to align with the other health tools? It creates some redundancy with the pattern. For @sterkenburgsara 
- Where can we document whatever decisions we land on? Should we add health tools-specific title tag guidance to the documentation [here](https://design.va.gov/content-style-guide/title-tags)?

**Comment by outerpress** [comment]
Thanks @sterkenburgsara ! 

I think we have a decision. We'll follow the pattern in my [previous comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/91563#issuecomment-2374635921) except we won't include `- Appointments` in the title tags. And yep always happy to iterate as needed.

And I'll link any dev tickets and other documentation we create to this ticket, for help with future efforts around broader documentation.

**Comment by sterkenburgsara** [comment]
Thanks so much! That's perfect.

**Comment by outerpress** [comment]
Dev ticket: #95539

**Comment by outerpress** [comment]
Dev work is complete and new pattern is documented [here](https://www.figma.com/design/eonNJsp57eqfPqx7ydsJY9/Feature-Reference-%7C-Appointments-FE?node-id=1847-64497). Thanks all!
