### ISSUE TITLE
Make entire icon link clickable and remove sr-text attribute

### ISSUE THREAD

**Issue by outerpress** [department-of-veterans-affairs/va.gov-team#91739]
## Description
_What details are necessary for understanding the specific work or request tracked by this issue?_

The phone and direction links include icons, but those icons aren't clickable along with the link content. Also the link icons are decorative, so we can remove the sr-text attributes that announce them as icons. See staging review ticket #91571 and #88450 for more details

---

## Development Checklist
Background: the `toggle` toggle is on (remove if not needed) 

For all applicable appointment types
- [x] The directions icon is a clickable part of the link
- [x] Remove `srtext` attribute from directions icon
- [ ] ~~The phone icon is a clickable part of the link~~
- [ ] ~~Remove `srtext` attribute from phone icon~~
- [x] Remove the phone icon from phone links

### Design Assets
<img width="1943" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMm1WQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5447aed07f4ff0b4bccf7185197cfaf9e5f519c0/Screenshot%202024-08-28%20at%209.46.06%E2%80%AFAM.png" alt="Screenshot 2024-08-28 at 9.46.06 AM.png" />

### Developer Reference

- [Swagger File]() (remove if not needed)
- [File path]() (remove if not needed)

## Definition of Done
- [ ] All tasks criteria are met
- [ ] [Technical Documentation]() is updated (must confirm if needed/or remove) 

---

## How to configure this issue (Delete this section before creating the ticket)
- [ ] **Attached to a Feature** (what body of work is this a part of?)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Bren22va** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Appointments-Team-603fdef281af6500110a1691/issues/department-of-veterans-affairs/va.gov-team/91739?planning-poker) with Zenhub @cferris32 @jenniemc @JunTaoLuo @ryanshaw @simiadebowale @vbahinwillit

**Comment by JunTaoLuo** [comment]
@outerpress I took a quick look at the work required here and wanted to let you know that we can't move the phone icon into the clickable area. The reason is that the phone link is a `VaTelephone` element which we can't nest an icon under. I see a few different approaches here:
1. Add a separate link without text that points to the same reference as the `VaTelephone` element and add the icon underneath that. This seems cumbersome and I'm not sure if the juice is worth the squeeze.
2. Ask platform to add `icon-name` and `icon-size` to the `VaTelephone` element like they did for `va-link` so we can specify the telephone icon and the icon size. This seems the most reasonable approach but I don't know how long this would take.
3. Leave the icon as is without being part of the link. The simplest but least desirable no-op approach.

The other three items can be completed pretty easily.

**Comment by outerpress** [comment]
@JunTaoLuo we only use the phone icon next to the telephone link on VA Requests, right? If so, we can remove the phone icon since it's not consistent with the rest of the details pages.

We might be able to merge the phone number under the Facility section, similar to how we do it on other details pages, but I want to look at that separately.

**Comment by JunTaoLuo** [comment]
Ah good point, looks like it's used for VA request and cancel appointment confirmation page. It's fairly limited in terms of where we show it, so we can just remove it. One thing I like more than writing code is deleting code 😄.

**Comment by outerpress** [comment]
Looks good, validated @ldelacosta @JunTaoLuo . I updated the AC to reflect the final path.

**Comment by ldelacosta** [comment]
No issues to report. Closing out the ticket.
