### ISSUE TITLE
decsion: deployificator config sources

### ISSUE THREAD

**Issue by nathanhruby** [department-of-veterans-affairs/va.gov-team#9185]
In department-of-veterans-affairs/vsp-infra-fluentd#6 @tskinn wrote:
> 1 I've rethought this strategy a few times. I feel like it is kind of messy to have docker in docker as part of the deployer and maybe fragile because not all buildpacks set the working dir. I have played with an idea to not package the deployment files in the docker image and just send them with the deployment event payload so the deployer tool doesn't have to run any docker commands. Also we could package up the deployer tool to be the used for creating the deployment events and probably create a custom orb for people to use that abstracts the details from users. (we might want to think about doing that regardless) I think we should have a conversation about this again. I know Nathan liked the idea of having an all in one build pack but I would like to get more thoughts.

This is a good point, this ticket serves to document the discussion and decision.

**Comment by nathanhruby** [comment]
My reasoning for having the deploy configs in the artifact were:
- The deploy configs **must** live with the code they are deploying.  Splitting the deploy configs from the rest of the app adds extra cognitive load about where to find, update, release, and deploy the deploy configs and can cause gating issues when multiple repos with differing deploy cadences.  We want to encourage self-service, which means we need to eliminate these kinds of cross-cutting dependencies.  
- Nomad does not indefinitely persist configs.  Stopped jobs are eventually cleaned up, and you can trigger that immediately with a `nomad job stop -purge JOB_ID`.  In this case, we need to refetch the config when we want to redeploy.  Since we will already have the configs in the repo and build artifact in our network, pulling the config from the container seems like the simplest thing in total.  No other databases, persistence, state, or dependencies would be needed, at the cost of some deploy logic complexity.
- Additionally bundling the config from the repo into the build artifact also means that we get versioned configs which is needed for ATO, audit, and debuggging purposes.  That they are in the artifact also provides some level of immutability as well.
- Originally I had planned on running an pull-through artifact repo inside the network, so the deployer would need to initially fetch the artifact to validate we would ingress it into the network and cache.  Since we had to do that _anyway_ it seemed like not a big deal to crack open the container and grab what we needed.  Seems like we're going to use ECR so we'll have everything housed in-network / off-github already so we don't need to do this.

Of the above, we can eject the last one and figure out a way to handle the first three.  

Note that users don't have to use buidlpacks if they don't want to.  I think they are easier for new apps, but we don't have the bandwidth currently to support them well (ie: maintain our own stack and buidlers) so I don't want to force people to use them.

**Comment by tskinn** [comment]
**point 1** I don't mean to say that we move the nomad job spec and deploy config out of the app repos. I mean to say that we would send those files as the payload of the deployment event. We could use the deployer to package up and create github deployments. This makes it easier for app developers as we can provide/simplify the means of deployment creation and since the deployer is creating the payload it is easily decoded by the deployer. (not that we wouldn't anyways)

**point 2** is an interesting case that I think we are hoping doesn't happen often right? The case being we need to manually intervene and deploy/redeploy because something went wrong? I think this might be most applicable when github isn't functioniing and we need to manually trigger a deploy. In that case packaging config in the image is definitely the most convenient route. Although if github isn't functioning then lots of things aren't happening lol. 

> No other databases, persistence, state, or dependencies would be needed, at the cost of some deploy logic complexity.

I'm not proposing any other state it would just be github deployment creation events with a payload. Also I think ideally we would only intervene with nomad jobs in urgent circumstances as we will be creating inconsistent state in github deployments. For instance if a developer wanted to deploy a previous commit they could use deployer to easily create a new github deployment via the deployer.

But you are right in that if we were going to do a deploy without the github deployment api we would need to fetch the deployment files.

**point 3** What exactly are the requirements for the versioned configs by ATO? The config stored in git and the config used by the application are two different things. The config that is actually used is a combination of consul/vault values and the templates stored in git. Does ATO require that we store the generated configs or somehow version or save history of consul kv?


To be clearer, I was proposing a flow that goes something like this:
1. dev pushes commit to github
1. circleci runs
   1. test / lint / build / push
   1. deployer utility creates github deployment
      1. reads deploy/config.hcl and reads all files listed there
      1. encodes deploy/config.hcl and all related files as payload of deployment 
      1. creates deployment using github api
1. github creates deployment and sends out webhook
1. deployer server gets event 
   1. decodes payload
   1. writes files listed in config.hcl to tmp dir
1. deployer deploys
   1. runs steps according to config.hcl
   1. updates status of github deployment

**Comment by nathanhruby** [comment]
I think that looks good with the addition of one extra step in `4` to save the payload to durable storage (s3? dynamo?) so we can redeploy if we need to.  

Starting fresh doesn't happen often, but it does happen.  Often often as a manual "nuke the job and start fresh" step when debugging so in lower envs we'll definitely see this.  

That also gives us a record of who deployed what and when, which should address any kind of "manually tweak the config and run it by hand" issues where the deploy is not recorded someplace.  

I don't think we need to worry about keeping the generated config post-templating -- there's logging, auditing, and versioning on the backing stores for keeping an eye on that.
