### ISSUE TITLE
[Congressional]  V12126054 - Issues with ID.me  Due 10/7/24 (Congressman Griffith) 

### ISSUE THREAD

**Issue by ATMiddleton** [department-of-veterans-affairs/va.gov-team#91981]
## Issue Description
Veteran understands that he will need a verified ID in order to log into his VA account in the future. He has been trying to set up an ID.Me account in order to take care of this, however, ID.ME is requiring a cell phone code as part of it's two factor authorization process. He does not have a cell phone and needs another way to confirm his identity.sue?_

https://app.slack.com/client/T03FECE8V/C02BS78NYRM
---
## Tasks
- [x] Review congressional correspondence
- [x] Resolve issue 
- [x] Notify Veteran and congressional correspondence channel of solution.

## Acceptance Criteria
- [x] Veteran issue will be resolved or responded to with final answer to issue 
- [x] Congressional Correspondence will receive details of the resolution 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by Kimberley2023-CSM** [comment]
Sent details to POCs at ID.me for further investigation.
Awaiting response.
Because this issue is in regards to verification, it has to be handled by the appropriate CSP.

**Comment by Kimberley2023-CSM** [comment]
9/4/24:  Jessica from ID.me responded advising she has escalated the issue to their support team and they should be reaching out to the Veteran shortly.
Awaiting an update.

**Comment by Kimberley2023-CSM** [comment]
9/5/24: From Jessica with ID.me:

From what we can tell the member has not actively done anything on the account. A cell phone is not needed for the MFA if he has a landline he can use that option. He also can choose from the other option that we have for an MFA. Our support team reached out and sent him instructions on how to add an MFA to the account but he has not actively logged into the account in over two months.
Also looking at their phone number it has a spam blocker so MFA calling wouldn't work since you have to hit 1 to then get to him.
Right now we are waiting to hear back from the user, we will keep you updated!

**Comment by Kimberley2023-CSM** [comment]
9/13/24 Update:  Jess responded, stating:  Our support team spoke with the member on Monday for a planned meeting. We were able to get the security key on their account for MFA but the member needs to go through a trusted referee session in order to successfully verify. He only has Microsoft Edge and does not want to download Chrome. He told our support team he wanted to stop the process for now until he had help. We offered to call him when he has help and walk him through whatever questions he has.
I replied inquiring if the user accepted to offer.
Awaiting response.

**Comment by Kimberley2023-CSM** [comment]
**9/18/24:** Jessica advised that they have not heard back from the Veteran as of yet.

**9/23/24:** Responded to Jessica asking if they have heard from the Veteran as of yet.  Inquired about the ID.me process of reaching out to users and to send the correspondence they are sending to me in hopes that I can reach the Veteran.

**9/23/24:**  Response from Jessica -
Great question and I think this really depends and is a case by case basis. If we were able to initially get in contact with the end user and then we follow up a few times with no response we will usually close out the ticket. Since the member told our team he wanted to take a pause and we have reached out a few times without an answer from him my assumption is the ticket may now be closed out. (I will reach out to my team and double check)
Also, let me connect with our support staff since they are sending the emails and not myself. I need to see if we can loop anyone in since this may contain PII around the user and have them access their account.

**Comment by Kimberley2023-CSM** [comment]
10/1/24:  Contacted Jessica from ID.me:
Have you received any responses from the user? If not, can you provide the following information:
How many times was the user contacted?
Can you provide those dates and method?
Can you send over the correspondence that was sent to the user minus any PII?
I can attempt to send the exact same information from my side, just to ensure we exhausted all options.
The closure date for this case is Monday October 7th, 2024, so I’d like to have everything wrapped up no later than Thursday October 3rd by COB if possible.

**Comment by Kimberley2023-CSM** [comment]
Multiple attempts have been made to the Veteran, both phone and email.  Please see detail below below from my ID.me POC and advise.
Here is what our support team shared with me:
We were in touch with this member starting on September 4, Support called him twice at 16:57 & 17:30. Support then contacted the member again on September 5th at 16:14pm but he said he did not have time to continue the verification. We then reached out again through email on September 6th with instructions on how to change his password and scheduled for September 9th for us to do a verification walk through.
We called the member on September 09th at 11:01 am and 11:08 am, we were able to reset the password, activate the security key but when it came time for the verification he was using the wrong browser. We told him that we would need to switch to Google chrome in order to continue. He stated that he has no idea how to work his device and that he no longer wanted to proceed with the call and would need to get help. We asked if he wanted a call on another day and he said no. We explained what he would need to do for verification and sent him the email " Complete an ID.me Trusted Referee session" on September 9th at 09:19 am .
Since the phone call on the 9th there have been 4 outgoing emails with no response:
Sep 9: Action Required: Continue Verifying your Identity
Sep 9 again: Action Required: Continue Verifying your Identity
Sep 11th: Action Required: Continue Verifying your Identity
Sep 13th: Complete an ID.me Trusted Referee session
When there are no responses for a specific amount of time we close out the ticket. I also cannot send over the direct comms but hopefully this is enough information.
