### ISSUE TITLE
[Design]- Show a more specific error message when we cannot initialize somebody in VA Profile 

### ISSUE THREAD

**Issue by mshea0606** [department-of-veterans-affairs/va.gov-team#9353]
## Background
Related ticket : [https://github.com/department-of-veterans-affairs/va.gov-team/issues/6012](https://github.com/department-of-veterans-affairs/va.gov-team/issues/6012)

[Slack Convo](https://dsva.slack.com/archives/C909ZG2BB/p1588797312090200?thread_ts=1588795690.086000&cid=C909ZG2BB)

Related ticket: [FE]- Show a more specific error message when we cannot initialize somebody in VA Profile #8847

## Tasks
- [ ] Create error messaging copy/design

**Comment by tressaellen** [comment]
Hi @erikphansen - could you give me some clarity about what specifics/wording need to be in this messaging? I've added a line about 'having issues connecting to our database', but I don't think that really adds any value. Also, is there some kind of timeline of when the issue might be resolved that we could include - like for example 'Please try again in 24 hours'. Any clarity would be great! 

We’re sorry. We’re having issues connecting to our database and couldn’t update your mailing address at this time. Please try again.

cc/ @peggygannon adding you ![Screen Shot 2020-05-28 at 10.31.18 AM.png](https://images.zenhubusercontent.com/5dfa65bbbd078d1699e52294/8306d01b-5ed5-4bc1-93b2-f39b51ca1878)as we'll need your help as well!

**Comment by erikphansen** [comment]
@tressaellen this error will only live at the top of the profile and show up on load. I'll get a screenshot of what is shown now.

As for messaging, I'm not sure. @Samara-Strauss had some advice for the guy who ran into this problem. Honestly it's probably not an issue that will resolve itself so we should give some specific guidance on how they can straighten out the issue which will involve calling people or visiting VA offices :(

**Comment by erikphansen** [comment]
@tressaellen This is the error we need to make more specific when a user cannot be initialized in VA Profile 
![image](https://user-images.githubusercontent.com/20728956/83180867-ea269a80-a0d8-11ea-9da7-d21416f7151c.png)

**Comment by erikphansen** [comment]
We are also going to need to determine which VA Profile error codes are related to failure to initialized. I'll add that in the FE implementation ticket.

**Comment by tressaellen** [comment]
Here's a Frankenstein message using some of the DD messaging. Any direction on other specifics that might need to be included would be great @Samara-Strauss  

**Your recent profile update didn’t save**

We’re sorry.  Something went wrong on our end and we couldn’t save the recent updates you made to your profile.
To resolve this issue, please contact your local VA facility or call us at 800-827-1000 (TTY: 800-829-4833). We’re here Monday through Friday, 8:00 a.m. to 9:00 p.m.

<img width="330" alt="Screen Shot 2020-05-28 at 11 25 54 AM" src="https://user-images.githubusercontent.com/58752772/83184506-06750800-a0d6-11ea-8ea7-245ced46e652.png">

**Comment by Samara-Strauss** [comment]
We *think* the failure to initialize has to do with people having multiple IDs at the VA based on the one veteran we talked to and some conversations Lihan has had with Ian from VA Profile. [There are more details here](https://github.com/department-of-veterans-affairs/va.gov-team/issues/8847#issuecomment-627571101). The SSOe team is working on an update that will stop people with multiple IDs from logging in in the first place, so eventually these people won't be able to get to the profile at all. 

In the meantime, I think something like this should work. I've included some of the copy Peggy has already written for the SSOe work, though I did abbreviate it a bit and she should review for approval. These directions will show for people that we can't initialize:

### We are unable to load your contact information

We're sorry, but we're unable to load your contact information in your profile. This may have to do with My HealtheVet or the Department of Defense having multiple IDs or accounts for you.

**To check if this has to do with your My HealtheVet information**
 
Contact us at 877-327-0022. We’re here Monday - Friday, 8:00 a.m.- 8:00 p.m. ET. If you have hearing loss, call 800-877-3399. 

Tell the representative that you tried to sign in to VA.gov, but got an error message that you may have more than one MyHealtheVet account or internal control number (ICN). 

Or, you can fill out a [MyHealtheVet online help form]( https://www.myhealth.va.gov/mhv-portal-web/contact-us) to get help signing in.  

**If you suspect this issue has to do with your Department of Defense (DoD) information information:** 
 
To fix this issue, please [submit a request to get help signing in](https://www.accesstocare.va.gov/sign-in-help).

**Comment by peggygannon** [comment]
Hi, @tressaellen @Samara-Strauss 

Question: Would this error occur when a non-intialize user makes **any** profile update or an update to only a certain part of profile?

**Comment by erikphansen** [comment]
This error does not happen when a user tries to make an update. It happens when they go to their Profile, are not yet in the VA Profile service, so we try to initialize them in VA Profile but are unable to do so for some reason. That's why the current messaging about not being able to save a recent update is so bad :)

**Comment by Samara-Strauss** [comment]
> Question: Would this error occur when a non-intialize user makes any profile update or an update to only a certain part of profile?

+1 to what Erik said. This is a problem happening because we can't initialize, ie. determine people are who they say they are even if they are LOA3, in VA Profile because they have multiple IDs at the VA. So, that means we can't even load their contact information in the first place.

Unfortunately, unlike the SSOe work, we do not have insight at this level into what kind of duplicative IDs they have, so that is why the advice has to be more generic than user specific.

**Comment by peggygannon** [comment]
Hi, @tressaellen @Samara-Strauss @erikphansen 

Please let me know if this recommended message would work for this situation:

**We can’t upload your information**

We're sorry. We can’t upload this information to your profile. This may be because you have multiple IDs or accounts at VA. 

**To find out if this about an account on My HealtheVet:**
Contact us at 877-327-0022. We’re here Monday - Friday, 8:00 a.m.- 8:00 p.m. ET. If you have hearing loss, call 800-877-3399.
Tell the representative that you tried to sign in to VA.gov, but got an error message that you may have more than one My HealtheVet account or ID.

Or, you can fill out a [My HealtheVet online help form](https://www.myhealth.va.gov/mhv-portal-web/contact-us) to get help signing in.

**To find out if this about an account with the Department of Defense:**

You can [submit a request to get help signing in].

**Comment by Samara-Strauss** [comment]
> We can’t upload this information to your profile

I think we need to reword this since "upload" sounds like this has to do with an action the user took. How about "We can't load your contact information to your profile. This may be because..."

**Comment by peggygannon** [comment]
@Samara-Strauss Yes that'll work. 

So it would read:
**We can't load your information**

We're sorry. We can’t load this information to your profile. This may be because you have multiple IDs or accounts at VA.

**To find out if this about an account on My HealtheVet:**
Contact us at 877-327-0022. We’re here Monday - Friday, 8:00 a.m.- 8:00 p.m. ET. If you have hearing loss, call 800-877-3399.
Tell the representative that you tried to sign in to VA.gov, but got an error message that you may have more than one My HealtheVet account or ID.

Or, you can [fill out a My HealtheVet online help form] to get help signing in.

**To find out if this about an account with the Department of Defense:**

You can [submit a request to get help signing in].

**Comment by Samara-Strauss** [comment]
> We can’t load this information to your profile

So this error will sit above all of the sections of the profile, so "this information" won't have the context it needs as it would if it was a per-section error. 

To account for the fact that we don't know exactly what will or won't load, how about "We can't load some of the information in your profile. This is because..."

**Comment by tressaellen** [comment]
I think this messaging is really thorough and informative - but it's extremely long, especially on mobile. Is there any way we can shorten it at all? Or have a link to a content page with all of this information?

<img width="163" alt="Screen Shot 2020-05-29 at 3 49 49 PM" src="https://user-images.githubusercontent.com/58752772/83313776-123ef800-a1c4-11ea-964d-679e126789ec.png">
<img width="595" alt="Screen Shot 2020-05-29 at 3 49 36 PM" src="https://user-images.githubusercontent.com/58752772/83313774-0f440780-a1c4-11ea-8a3e-d8797473e084.png">

**Comment by Samara-Strauss** [comment]
I agree, *but* in this case I think it's OK:

- This message is not going to be a common thing that people see. If this was something lots of people would see often, I would say yes — let's shorten or get an FAQ created or something. But since this isn't going to be a super common use case, I don't think we should get a content page created.
- Furthermore, since people seeing this message won't be able to see basically anything in their profile because of the duplicate ID problem, this error isn't really competing with other content. I'd rather have detailed content that could help them resolve this issue than make things shorter for the sake of our normal standards (brevity, scalability, etc).
- Finally, there may come a point when nobody see this — after the SSOe updates are launched. At this point, people with the duplicate ID issue won't be able to log in in the first place, let alone get to their profile. Given that, I don't think it's a good use of our time to try to figure out alternatives to how we can shorten this content.

But that's just my opinion. Totally open to others. What do you think, Tressa and Peggy?

**Comment by tressaellen** [comment]
@Samara-Strauss you make very good points - I agree. Especially if there's a possibility that it won't be used in the future.  In that case - I'm going to close this ticket.
