### ISSUE TITLE
Evidence Upload Silent Failures - investigate logged email notice events of files in eFolder

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#93647]
A comparison was made of the number of logs indicating an upload failure email notification had been sent and the number of failures identified when comparing form uploads and eFolder contents.

Submission IDs created after the evidence upload failure email service was enabled that require further investigation:

- 2967040 & 3043407
  - The filenames included in logged email notice events appear in the associated eFolders, but with an upload time that is a couple of hours to a day later than the logged times, indicating the files were uploaded after the claims were submitted, perhaps as a result of receiving notification that the files failed to upload (which would imply the notification prompted resubmission)
- 3043328
  - 3 logged email notice events, of which 2 of the obscured filenames appear to be included in the eFolder documents contents; however, those files include an upload date that was a day before the failed upload email was sent (which I'm unable to explain)

**Questions**
1. Are these normal, expected results?
2. Is event logging and execution of the `Form526DocumentUploadFailureEmail` occurring as intended, when the `SubmitUploads` job has exhausted all retries?
3. What other avenues exist to submit evidence post-526ez submission? Could this explain the presence in the eFolder of files that have logged failed transmission events?

For 2967040 & 3043407:

- [ ] confirm whether mail template mentions claim status tool as option for uploading failed documents
- [ ] confirm how files that failed transmission ended up in eFolder after email notice sent (if through Claim Status Tool, can corresponding logging data be obtained to substantiate?)

For 3043328:

- [ ] compare timestamps of [DD logs](https://vagov.ddog-gov.com/logs?query=%40payload.form526_submission_id%3A3043328%20%7C%7C%20%40payload.submission_id%3A3043328%20&agg_m=count&agg_m_source=base&agg_t=count&cols=%40payload.form526_submission_id%2C%40payload.obscured_filename&event=AgAAAZHEt80seEeb8QAAAAAAAAAYAAAAAEFaSEV0OXAwQUFDT1pXTVpfQ2VrLVFBNAAAACQAAAAAMDE5MWM0YjgtMGQxMC00ZjUzLTgxMTEtNTIzMDM1OGFmNjIx&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=online_archives&stream_sort=%40payload.form526_submission_id%2Casc&view=spans&viz=stream&from_ts=1721331787582&to_ts=1726515787582&live=true) against eFolder document upload times (is it possible files submitted successfully, but job continued running as if they hadn't and sent a erroneous failure email?)
- [ ] confirm how files that failed transmission ended up in eFolder after email notice sent (similar inquiry as above)

Evidence Upload Silent Failures - Compare doc upload failure email count to suspected failures
[#92914](https://github.com/department-of-veterans-affairs/va.gov-team/issues/92914)

**Comment by freeheeling** [comment]
### Submission ID 2967040
- updated_at: "2024-08-06 00:14:19

**DD "Form526DocumentUploadFailureEmail notification dispatched"**
form526_submission_id | 2967040
obscured_filename | the_XXXXXXXXXXXX_XX_XXXXXXes.txt
supporting_evidence_attachment_guid | 1431ba13-85cf-4576-813f-26acba9f17b0
timestamp | 2024-08-07T01:15:10Z

**Form json Uploads:** 2 identically named files (nearly identical content – 2 sentences and contact information different)
name: with spaces, no underscores
attachmentId: "L015" 
confirmationCode: different than `supporting_evidence_attachment_guid` in DD log

name: with spaces, no underscores
attachmentId: "L023" 
confirmationCode: matches `supporting_evidence_attachment_guid` in DD log

**Coded Document Types**
['L015' => 'Buddy/Lay Statement']
['L023' => 'Other Correspondence']

**eFolder contents:** ordered chronologically by `uploadDateTime` 
originalFileName: "FIRST_LAST_ID_526.pdf"
uploadDateTime: "2024-08-06T00:14:27Z"
documentTypeLabel: "VA 21-526EZ, Fully Developed Claim (Compensation)"

originalFileName: with spaces, no underscores
uploadDateTime: "2024-08-06T00:15:50Z"
documentTypeLabel: "Buddy / Lay Statement"

originalFileName: underscores instead of spaces
uploadDateTime: "2023-08-07T17:01:20Z"
documentTypeLabel: "Correspondence"

**error_message:**
[{"key"=>"EVSS_15004", "text"=>"We were unable to complete your request because your file type is not a supported format. Try using a different file type such as PDF (unlocked), JPEG, BMP or TXT. ..." }]

**Summary:** Two identically named files, but different document types ("Buddy / Lay Statement" and "Correspondence"), were uploaded. It appears that the upload labeled "Correspondence" failed transmission to the eFolder as part of the 526 submission job, but was uploaded with a modified filename (underscores in place of spaces) ~16 hours after the upload failure email notification was dispatched.

**Comment by freeheeling** [comment]
Posed the following questions to Jerek Shoemaker in the #benefits-management-tools channel [[message](https://dsva.slack.com/archives/C04KHCT3ZMY/p1727382885136549)]:

- how soon after a disability claim and any supplementary evidence is uploaded to a Veteran's eFolder before those details would be visible within the tool?
- which service is used for uploading evidence to a pre-existing claim?
- is the process asynchronous?
- is there an option for selecting document type when uploading evidence?
- what validations other than file type and file size are uploads subjected to?
- do filenames have to be unique?

**Comment by freeheeling** [comment]
Considering done/completed as the failed files associated with the referenced submissions appear to have been submitted via the Claim Status Tool after form 526 was submitted, possibly either after receiving an email notification of evidence upload failure or even before notice of failure was sent.

What isn't clear is how a particular file can fail upload to EVSS and VBMS via the form 526 flow, yet ultimately be successful submitting to the eFolder, presumably using Claim Status Tool, if both are using the same Documents Services API endpoint.
