### ISSUE TITLE
[526/4142 Email] Trigger an email after LH 4142 polling returns explicit failure/error

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#94144]
As a user, if I submitted a disability claim with a 4142 document that appeared to be successful when I submitted it online, but the system failed to produce the end results, I want to be notified (via email) that I need to take action in order to get my claim processed. 

The solution must solve for when the 4142 document is considered a failure and there are no more attempts to deliver it to central mail (VBMS). 

- [x] Trigger the email when [insert solution here] 
- [x] Use existing 4142 failure email 
- [x] Polling is required
- [ ] DD monitoring (dashboards will be in a new ticket)

Testing the following in the staging environment: 

4142
- [x] Trigger an email after LH 4142 polling has exhausted
- [x] That the email it not triggered on a successful 4142 upload

Datadog monitors:
- [ ] For when the trigger on email after LH 4142 polling has exhausted
- [ ] For when an email fails

- Validate DD Dashboards 
- Provide screen shots to R&D for product guides

**Additional Validations**
- Validate that no email is triggered when successful to VBMS

NOTE: This may be dependent on polling, if it is, we need to add a ticket to do that. 

Out of scope for now
- Polled failure due to stuck in pending state

**Resources**
- [Va.gov Benefits forms - Normal backup emergency flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1697740873991/4be42fcadc013be6b3d65bd620522ee68e8e0faf?sender=ua8d1f105fba69675aba15464)
- [Zero-Silent-Failures-Checklist-.md](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/teams/benefits/investigations/Disability%20526-%20Zero-Silent-Failures-Checklist-.md)

**Comment by freeheeling** [comment]
@lisacapaccioli – Please confirm in which of the following events should emailed notification be sent?
a) polling for the status of a transmitted form 4142 exhausts all retries
b) Lighthouse returns anything other than 'vbms' when polling after a set amount of time since transmission
c) a different event

**Comment by lisacapaccioli** [comment]
@freeheeling I'm glad you asked. I didn't intend to put a solution in there, I just copied what was said. What I heard was that we use polling (and that if it wasn't done, we would need to add it - see note in the description above) to determine if we have a complete failure of the 4142 to VBMS. If LH returns a state **every time** that would tell us that's never going to VBMS, it's possible we use that instead. You should confirm with @aurora-a-k-a-lightning and @kylesoskin on the solution. 

I will write it back to just what the ask is - To trigger an email when we know it's no longer possible to go to VBMS.

**Comment by freeheeling** [comment]
**SubmitForm4142Job**
- submits generated PDF using [Benefits Intake API](https://developer.va.gov/explore/api/benefits-intake/docs?version=current) to be routed to Central Mail
- logs 'Successful Form4142 Submission to Lighthouse' **before** uploaded
  - should logging be relocated to occur only when upload is successful?
- if `sidekiq_retries_exhausted`
  - no assigned retry count (what's the default?)
  - call `Form4142DocumentUploadFailureEmail.perform` (feature-gated)
  - log warning: 'Submit Form 4142 Retries exhausted'
- possibly remove `Flipper` logic 
- Given the following guidance in the [Benefits Intake API](https://developer.va.gov/explore/api/benefits-intake/docs?version=current) docs, should `lighthouse_service` **not be** memoized?
  - `location`: The URL is specific to this upload request, and should not be re-used for subsequent uploads. The URL is valid for 15 minutes from the time of this response. If the location is not used within 15 minutes, the GUID will expire. Once expired, status checks on the GUID will return a status of `expired`.

Note: A successful document submission does not mean it was successfully received by VA. Successful document submissions can fail later, as discussed above in the "How to avoid submission errors" section.

**Document Submission Statuses**
- pending
- uploaded
- received
- processing
- success: Indicates the document submission has been successfully received within VA's mail handling system
- VBMS: Indicates the document submission was successfully uploaded into a Veteran's eFolder within VBMS. Some document packages are worked in VA systems other than VBMS. For these submissions, Success is the final status.
  - is 4142 worked in a VA system other than VBMS?
- error
- expired

The POST /uploads/validate_document endpoint can be used to ensure individual PDF documents meet system requirements prior to submission.

---

**information on how to monitor the status of submissions**
1. Client Request: GET https://sandbox-api.va.gov/services/vba_documents/v2/uploads/{id}
  - `id`: An identifier (`guid`) returned by the previous submission.
2. Service Response: A JSON API object with the following attributes:
- `guid`: The identifier of the submission for which a status was requested.
- `status`: The current status of the submission.
- `code`: Only present if `status` is 'error'. An error code specifying why the submission is in an error state. 
- `detail`: Only present if `status` is 'error'. Plain language detailing of the error corresponding to the error code and the specific submission.
- `updated_at`: The last time the submission status was updated.

If submissions to the API are made frequently, the bulk status endpoint should be used in place of Step 1 to request updates for multiple submissions:
1. Client Request: POST https://sandbox-api.va.gov/services/vba_documents/v1/uploads/report
ids: A list of identifiers ( guid) returned in step 2 by the previous submissions.
2. Service Response: A JSON API object with the same attributes as listed in step 2 above for each `id`:
- Due to current system limitations, data for the /uploads/report endpoint is cached for one hour. The /uploads/{id} endpoint isn't cached.

**Comment by lisacapaccioli** [comment]
@kylesoskin I added the testing to this ticket for you. Feel free to make changes to them as needed. Thanks

**Comment by kylesoskin** [comment]
Code for this has been merged https://github.com/department-of-veterans-affairs/vets-api/pull/18801

Going to test in staging today/tomorrow (records/polling in staging)
Then will toggle on in prod Wednesday (polling records only)
Will validate all records/polling in prod so that it starts creating the polling records on Thursday

I am then out of office until Nov 6th. Will verify all records/polling is still good, then toggle on in prod then.
