### ISSUE TITLE
686 | Infinite redirect loop in Staging

### ISSUE THREAD

**Issue by steele-lm** [department-of-veterans-affairs/va.gov-team#94154]
## Issue Description
_The staging instance of the 686/674 form flow is not currently working due to an issue with a redirect._

The FE redirect logic checks if there is a form in progress and depending on the form ID and flipper, it redirects you to the correct form to finish. This is because Veterans might already have a form (on V1) in progress and we allow them to finish and submit. If they choose to start over, it starts a new app on V2 and creates a save in progress for the V2 form ID. It may have something to do with this commented line in dependents_applications_controller.rb - but Evan Smith may need to confirm.

This looping issue may be happening if there is in fact a V1 form in progress that isn't being destroyed.

![Image](https://github.com/user-attachments/assets/180e8e92-d118-4de4-bb40-1cdd8741c749)

---
## Tasks
- [ ] Determine issue and fix

## Acceptance Criteria
- [ ] Staging instance of 686/674 form functions as expected
---

**Comment by AmyPlange** [comment]
@tfink419 Could you start looking into this to gather any inisghts as to what the issue might be here? 

CC: @micahaspyr @steele-lm

**Comment by mjknight50** [comment]
I think this can be closed.

**Comment by Midge-dev** [comment]
@mjknight50 @steele-lm I noticed an issue in our FE logic that I am pretty sure is causing this issue. This happens because of a session check that the V1 application does on entry that the V2 application isn't doing:
`if (hasSession) {document.replace(manifest.rootUrl)}`
Because all of our redirect logic starts on the V1 entry application, V1's logic is executed first. And because the user does not yet have a valid session, it kicks them back to manifest.rootUrl (`/view-change-dependents/add-remove-form-21-686c/introduction`). Then the flipper check occurs, which if the flipper is `true`, it will kick the user to the V2 url (`/view-change-dependents/add-remove-form-21-686c-v2/introduction`), which also doesn't have a valid session yet, and causing the looping behavior.
