### ISSUE TITLE
Midpoint Review - IA Feedback - Disability Benefits Experience Team 2, Disability Comp Application (21-526 EZ), Updated 0781 Flow

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#94386]
## Next Steps for the VFS team

- [x] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [x] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Thoughts/questions

- Y'all asked for feedback on the interstitial review page - in short, please proceed! This pattern would help a lot.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

- [x] **Must: (opens in a new tab) should be part of link text**: For links that open in a new tab, `(opens in a new tab)` should be part of link text rather than adjacent to the link.
  ![Image](https://github.com/user-attachments/assets/37704ecf-e3f7-43f4-86b1-e29fb60f176f)

- [x] **Must: add a heading on the evidence orientation page** Most/all pages have a heading summarizing the purpose of the page, but that's missing from the [evidence orientation page](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8423-100776&t=97mv84WyRm76Hp1j-4). Please add one.

- [ ] **Should: break up treatment location page** The [Add a Vet Center or non-VA treatment location](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8742-40339&t=97mv84WyRm76Hp1j-4) page is very long and should be broken into multiple pages.

- [x] **Should: clarify consequences of completing or not completing the 781 form** +1 to @allison0034's [question to the team](https://dsva.slack.com/archives/C053UDWMH7U/p1728068964275769?thread_ts=1724963883.648259&cid=C053UDWMH7U) about what happens if folks do or do not complete the additional form. On the [opt-in page for 781](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8423-101970&t=dMADQLdW4lWzDUxs-4), can we clarify what will happen if users do or do not complete this form?

- [x] **Should: show character counts if relevant** I see we have a [character counter on a textarea in step 2](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8423-102453&t=dMADQLdW4lWzDUxs-4) of the 526 form but none on the free-text form fields on step 3. If there's a character limit, let's include one here. If not, great!
  ![Image](https://github.com/user-attachments/assets/b73792ce-8fbe-41cc-abab-910f5c730f7c)

- [x] **Consider: keep full form title in headings within sub-form flow** To help users with placemaking within the form, consider displaying the full sub-form name, not just the VA form number in the eyebrow, on each page of the form. Below that, the page title/question could be a sub-heading. This _might_ be too much repetition - but could be worth some research. 
  ![Image](https://github.com/user-attachments/assets/fdf3c047-ff8f-4160-9ac5-d98603fed259) 

- [x] **Consider: include "No report" option on official reports page** When asking about [whether there was an official report](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8742-33191&t=dMADQLdW4lWzDUxs-4) for an event, it could be helpful to include a "No report" checkbox as part of the list, just to ensure folks that they have answered that question - even if this question is not optional.
  ![Image](https://github.com/user-attachments/assets/1bfc23c7-a404-47eb-af28-413ce7de9513)

- [x] **Consider: if someone opts out, add note/link to 781 at end of form** if someone opts out of completing the 781, it might be useful to remind them once they've submitted the 526 that they are encouraged to complete the 781, with a link to the find a form page.

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by jinaryu** [comment]
@erinrwhite re: **Should:** break up treatment location page The [Add a Vet Center or non-VA treatment location](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8742-40339&t=97mv84WyRm76Hp1j-4) page is very long and should be broken into multiple pages.

This is something we synced with the 0995 team on ([their figma](https://www.figma.com/design/2LGebZcUuu5Iqh4QLPII6A/Supplemental-Claims-(VA-0995)?node-id=909-27614&t=IbCKd7IniPmj5OKb-1)) and decided as a team to keep everything on one page. When they tested with screen with users (including screenreader users) they had no problem with the page. We thought it makes sense to keep all the fields on the page because they're all related to the same task of "adding a provider"

**Comment by jinaryu** [comment]
@erinrwhite re: **Should:** clarify consequences of completing or not completing the 781 form +1 to @allison0034's [question to the team](https://dsva.slack.com/archives/C053UDWMH7U/p1728068964275769?thread_ts=1724963883.648259&cid=C053UDWMH7U) about what happens if folks do or do not complete the additional form. On the [opt-in page for 781](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=8423-101970&t=dMADQLdW4lWzDUxs-4), can we clarify what will happen if users do or do not complete this form?

We are working on this opt out page. A new policy makes the 0781 completely optional, so it's tricky to say definitely "if you don't complete this form, it will harm your claim." You can see what we have so far [here](https://www.figma.com/design/r3Aj9FtLFS989mlVeBsgJg/0781-Redesign?node-id=9008-32489&t=f0cpIESWp0UJrs7x-1). We are mainly emphasizing this "This form is optional, but it can support your disability claim application."

**Comment by jinaryu** [comment]
Discussed form title heading in[ slack thread](https://dsva.slack.com/archives/C04KW0B46N5/p1728416857360949) with Erin and Ruben

**Comment by jinaryu** [comment]
We've addressed all feedback. For "should" feedback we haven't addressed, we have discussed it in Slack or I have posted rationale in the comments above. Thanks!
