### ISSUE TITLE
CT-EYB: Update Bottom Sheet Implementation

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9444]
As a developer, I need to update the EYB bottom sheet implementation based on DEPO feedback so that it meets design and coding standards.

## Assumptions:
1. This work is completed behind the bottom sheet feature flag #9403.
2. AC 1, 2, & 3 are to address feedback in #8819.
3. The bottom sheet continues to slide out of view when the update button slides into view and vice versa.

## Acceptance Criteria
1. The estimated benefits drawer is a `<button> + <div>` that shows/hides a regular accordion. 
2. The following aria tags are added to the estimated benefits drawer:
    a. aria-expanded="false || true"
    b. aria-controls="UNIQUE_ID" The unique ID should be associated with the div of benefits.
    c. aria-controls should only appear when the drawer is open, otherwise it should be a null value (or we'll get an axe accessibility error)
3. The estimated benefits drawer uses the `prefers-reduced-motion` browser functionality.

## Supporting Artifacts:
1. [Prefers reduced motion documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).

**Comment by elder-joseph** [comment]
Associated PR: https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/vets-website/12835

**Comment by sonntag-adam** [comment]
![Screen Shot 2020-05-29 at 12.54.48 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/1b4dad3c-148b-463a-bdb9-5d56d15f86a3)
##
![Screen Shot 2020-05-29 at 12.54.56 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/74467888-0182-4c6d-a288-7241ade27bb4)
##
![Screen Shot 2020-05-29 at 12.55.04 PM.png](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/5868bd01-bc21-41f5-95b3-3d1c79e0a359)
##
![ezgif.com-video-to-gif.gif](https://images.zenhubusercontent.com/5c98df9c534e09000148f8d1/d8e93331-04ed-45cd-9d87-988698854f3f)

**Comment by sonntag-adam** [comment]
https://dsvavsp.testrail.io/index.php?/runs/view/418&group_by=cases:section_id&group_order=asc

**Comment by sonntag-adam** [comment]
@department-of-veterans-affairs/uxbah in staging

**Comment by ccruzgra** [comment]
@sonntag-adam, @JenLJ and I took a look and there are no issues.

**Comment by sonntag-adam** [comment]
Closing story.

**Comment by 1Copenut** [comment]
@ccruzgra & @amyknox 
I've been looking at the estimated benefits tray that slides up from the bottom for mobile users. Specifically I tried it out by navigating with the keyboard, TAB and arrow keys.

I wasn't able to reach the tray with the keyboard, because as I tabbed forward, it opened, then closed as I moved to the next few elements. If I fudged a bit and focused the tray expand/collapse by clicking it, it disappeared as soon as I SHIFT + TAB to move backwards by focusable elements. I'm adding an animated GIF to show this second flow.

This could be a significant issue for keyboard users who zoom their browsers up, and screen reader users who have some vision and use the assistive tech for reinforcement. Just hiding the tray from screen readers with an `aria-hidden` attribute won't work because the automated checks will throw an error on focusable elements that are hidden from assistive tech.

I think the tray is a useful feature, and can be made fully accessible for these users. I'm specifically thinking about:
* Moving the button to open/close the tray before the content it's showing/hiding in the HTML
* Moving the tray HTML block before the standard Estimate your benefits gray panel
* Adding a keyboard-only "jump" link from the Your military details that would allow users to skip to the estimated benefits drawer. This link would only appear at mobile width in our stylesheets on focus, so would only be reachable by pressing TAB or the arrow keys using screen readers.

Let me know if you'd like to review this more, or have questions about my comments.
