### ISSUE TITLE
Review usage of `activerecord-import` gem

### ISSUE THREAD

**Issue by johnpaulashenfelter** [department-of-veterans-affairs/va.gov-team#9482]
The `activerecord-import` gem has a minor version upgrade. But before it is upgraded, its worth evaluating if it is truly needed.

It is used one place: `vets-api/modules/veteran/app/workers/veteran/vso_reloader.rbL:42` which is only referenced `Veteran::VsoReloader.perform_async` from `lib/tasks/veterans_tasks.rake`. It is unclear if that is used anywhere in the app.

Tracking down any information on this task and either upgrading or removing as appropriate, likely removing, is the outcome of this issue.

**Comment by LindseySaari** [comment]
The Veteran::VSOReloader reloader job runs at 2:00 everyday (0 2 * * *) There are 93 Veteran::Service::Organization records in the prod database currently. I think active record import makes sense here to do a bulk insert BUT we do use on_duplicate_key_ignore, which will skip duplicate entries. There’s only been two new records since 1/1/21 so they're not changing very often. Does activerecord-import still make sense?

**Comment by LindseySaari** [comment]
Reloading does not reboot the application, and therefore code executed during initialization does not run again. So, if you reload, changes to classes in the initializer won't be reflected in that stale Class object because the initializer only runs on reboot. Therefore, code that references a reloadable class or module, but that is not executed again on reload, becomes stale. 

The [rails guide](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#reloading-and-stale-objects) has some great examples

Also see:
https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-when-the-application-boots
