### ISSUE TITLE
QA updates: Review page

### ISSUE THREAD

**Issue by mtri** [department-of-veterans-affairs/va.gov-team#95020]
## Issue Description
QA for https://github.com/department-of-veterans-affairs/va.gov-team/issues/91411

## Defects

- [x] Add the content and checkboxes below the standard accordions. User should not be able to advance past the review page without checking the boxes.
![Image](https://github.com/user-attachments/assets/5e2d0b68-639a-4fc1-bf83-6ae0ae6070f4)

- [x] Under the Your information accordion, the form inputs display immediately. In other accordions the information is viewed in a table and then the user has to tap/click edit to display the inputs. Can this be made consistent?
- [ ] Chapter name "Review application" should be "Review"
- [ ] Is the "Review the information for your form" text above the accordions possible to add?
![Image](https://github.com/user-attachments/assets/3037160a-2c99-4862-97dc-aa26bcf14fa6)

## Acceptance Criteria
- [ ] Defects have been addressed

**Comment by cosu419** [comment]
re: the first two items (changing "Review application" to "Review" and adding "Review the information in your form"), it looks like this will require a custom review component - can discuss this further online.

**Comment by oddball-lindsay** [comment]
Failing CI test, so may need to bring this back to In Progress to correct, before design review.

**Comment by oddball-lindsay** [comment]
PR has merged, just waiting for the changes to make it to Staging. @oddball-lindsay can step in for Michael to review in Staging.

**Comment by oddball-lindsay** [comment]
The "Your information accordion" is looking good (inputs only appearing when I click "Edit") and the checkboxes at the bottom of the page are rendering as expected, I also cannot advance without checking both boxes 👍 .

There is a bug though -- when I select both checkboxes, the screen loads for a moment then throws this error. I'm able to re-select the checkboxes, but the error comes up again so I'm stuck in a loop at this moment and cannot advance to the Download page. Here's a quick screencap of what I'm seeing:

https://github.com/user-attachments/assets/443f487f-66c5-421c-af9e-f290966ff889


Since we're so close to QA, can we address that in this same ticket @cosu419? 🙏

**Comment by oddball-lindsay** [comment]
What I was experiencing seems to have been _mostly_ resolved by connecting Appoint to the `original_entities` temporary endpoint, and getting to the real representative data.

We can now progress to the Download page after:
1. A VSO representative with multiple organizations has been selected
2. An attorney has been selected
3. A claims agent has been selected

We are unable to progress to the Download page when:
1. A VSO representative with only one organization is selected
2. An entire VSO has been selected
These two scenarios will be addressed in this issue
