### ISSUE TITLE
Midpoint Review 2 - IA Feedback - Accredited Representation Management, digital submission designs (Appoint a Representative v2, Find a Representative v3, Representative Status Widget v2)

### ISSUE THREAD

**Issue by erinrwhite** [department-of-veterans-affairs/va.gov-team#95074]
## Next Steps for the VFS team

- [ ] **Assign** this ticket to the team member(s) responsible for addressing feedback provided by Platform.
- [ ] **Comment** on this ticket:
  - If the Platform reviewer has any **Thoughts/Questions** that require responses.
  - When **Must** feedback has been incorporated. As appropriate, link to any other GitHub issues or PRs related to this feedback.
  - When **Should/Consider** feedback has been incorporated, or if any feedback will not be addressed. As appropriate, link to any other GitHub issues or PRs related to this feedback.
- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members`.
- [ ] **Close the ticket** when all feedback has been addressed.

## Feedback
Practice areas will document their feedback on the VFS-provided artifacts following the [Must, Should, and Consider Framework](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/must-should-and-consider-framework-for-feedback). Platform Governance reviewers may also provide additional notes that don’t comment on the artifacts themselves but are important for implementation (eg. engineering/coding notes).

### both tools

- [x] **Must: indicate when links open in a new tab when inside a form flow** On find a rep, the search filters accordion, the link to `View our list of VA-recognized Veterans Service Organizations` looks like it opens in a new tab; if so, the [link text should say `(opens in a new tab)`](https://design.va.gov/components/link/#behavior). You might consider doing this for the "Find an accredited representative" link in the footer on some pages of the Appoint a rep too.
  ![Image](https://github.com/user-attachments/assets/ffe8cc3d-e2a7-4673-9c0d-850d1e92eb7a)
  ![Image](https://github.com/user-attachments/assets/f9a54087-b771-429b-81e7-03214d2d7f80)

### find a rep

- [x] **Must: clarify `Back to search results` mechanism** On the search tool's [representative detail page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=8275-216574&t=nhlpRxc9kKZ6vCRQ-4) there is a back link (in addition to the breadcrumb) because the breadcrumb links will return users to a blank search page, not the search results page with the user's filters applied. It seems like this is a bit of a workaround for the fact that the state of the search results is not saved when navigating to a new screen in the app. The impact of this is that using the breadcrumbs to go back, and potentially using the browser back button, could result in losing that search state. If possible please find a way for users to successfully navigate back to the search results using the breadcrumbs and the browser back button. If not possible, this could be a candidate for the [Back link](https://design.va.gov/components/link/#when-to-use-a-back-link) variant which would be used instead of breadcrumbs. Some other teams that are doing this include (with contact names): Secure Messages (Alex Morgun), Medications (Tony Gravell), and Claims Status (Skyler Shain).
  ![Image](https://github.com/user-attachments/assets/7c11a759-7362-4542-86fa-c928aec21c57)
        
- [ ] **Should: clarify headings on contact detail page** Headings related to organizations a rep belongs to are more descriptive and less action-oriented. How might they be revised to focus on actions the user can take next? We know we're directing people to take an action here. What is it?
  ![Image](https://github.com/user-attachments/assets/0a9b1239-9736-430c-9b74-460d3a501a91)

- [x] **Should: only show legal/previous names the representative has approved** Please ensure that accredited reps are aware of names that might appear on the public search tool. This might impact folks who have gone through gender transition, or folks who may have safety concerns and do not want a certain name shared.
  ![Image](https://github.com/user-attachments/assets/da9dd567-fbff-4b30-9783-77602a967f1c)

### appoint a rep

- [x] **Must: display feedback/query details above search results** On the [search representatives screen](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6329-256216&t=1aMdxN4V8eL66kqJ-4), once the search is submitted there should be status text indicating what you searched for and how many results (and sort criteria - what is it?). "Showing 12 results for Daniel, sorted by distance". If there will be pagination of results, include that information as well. I assume @briandeconinck will have more feedback about this pattern as well. We're still awaiting official guidance on this for VADS, but this is the advice we've been giving teams for a few months now.
  ![Image](https://github.com/user-attachments/assets/a2fd24ed-a2d4-4d09-9b07-cd612ad158f1)

- [x] **Consider: Appoint a rep download option for digital submissions** On the appoint a rep flow, we tell people [they won't be able to download a copy of their form](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4615-202534&t=U8HBe3uQCOrdyLtM-4) after they submit it. That seems unusual and like it could raise some questions about reliability and trustworthiness. It also creates a little bit of precarity/urgency toward the end of the flow. Is there a way to offer an option for download on the confirmation page, after form submission? Will folks receive a copy in email?

- [ ] **Consider: move personal/contact info to the front of the flow** Most of our forms on VA.gov ask for your contact information first, then form-specific questions. That said, I can see how we would want to prioritize understanding _if someone even has a rep_ before moving through the rest of the form.

- [ ] **Consider: checkbox or radio on [contact the representative](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6539-262589&t=1aMdxN4V8eL66kqJ-4) page** Y'all might consider making this page not a warning, but a regular page in the form flow. "You need to contact this person to continue. Have you done it? yes/no" (Similar to the print flow, where we ask folks to check a box to verify that they have printed their form.)
  ![Image](https://github.com/user-attachments/assets/e94559f3-5cf9-4a0b-b27b-3842fd096d43)

- [ ] **Consider: clearer language for checkbox on review page** On [the review page](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=10172-399758&t=1aMdxN4V8eL66kqJ-4), the "I accept that this form will replace all my other forms..." checkbox is a little jargon-y. Maybe something like, "By submitting this form I'm replacing all previously assigned reps" or something that otherwise mirrors the [Replace your current representative](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4521-225920&t=1aMdxN4V8eL66kqJ-4) page.
  ![Image](https://github.com/user-attachments/assets/c2505f15-2198-4276-a270-cf962eddf7bb)

## Governance team actions
- [x] Format feedback as individual tasks (check boxes)
- [x] Assign this ticket to the VFS team member that opened the Slack request
- [x] Add the VFS team product label
- [x] Add the VFS team the feature label (if applicable)
- [x] Add the touchpoint labels
- [x] Add the practice area labels
- [x] Add the Collaboration Cycle initiative milestone

**Comment by oddball-lindsay** [comment]
> Must: display feedback/query details above search results On the [search representatives screen](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=6329-256216&t=1aMdxN4V8eL66kqJ-4), once the search is submitted there should be status text indicating what you searched for and how many results (and sort criteria - what is it?). "Showing 12 results for Daniel, sorted by distance". **If there will be pagination of results**, include that information as well.

@erinrwhite calling out that there will be no pagination in this experience! Pagination will be available in the Find a Representative tool, but we hope by the time the user gets to Appoint a Representative, they will have that rep's full name in mind and will not need to explore pages of search results.

**Comment by oddball-lindsay** [comment]
> Consider: Appoint a rep download option for digital submissions On the appoint a rep flow, we tell people [they won't be able to download a copy of their form](https://www.figma.com/design/bzbwObT9hiItve0q3cQX9c/Find-and-Appoint-a-Representative?node-id=4615-202534&t=U8HBe3uQCOrdyLtM-4) after they submit it. That seems unusual and like it **could raise some questions about reliability and trustworthiness. It also creates a little bit of precarity/urgency toward the end of the flow.** Is there a way to offer an option for download on the confirmation page, after form submission? Will folks receive a copy in email?

@erinrwhite because the form captures PII, we do not plan to email a copy of the completed form. Could you share more though, about how this download option may raise questions about reliability and trust, and create precarity/urgency? I'm having trouble imagining a scenario that would lead to these takeaways.

---

**Including some background on this particular download step:**

Originally we had the option to download the completed PDF on the final confirmation page, but we observed users skimming over the content and assuming they were done, in which case they'd close the page or leave the experience. Users failed to comprehend that they needed to download their completed form -- a critical piece to appointing a representative -- then bring it to the accredited representative for signing and submitting. 

This led us to split the download into it's own page, before the confirmation page. This tested well, and all participants understood the task and next steps. 

Research references:
- (Point 3 of [Task 5](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest/research-findings.md#task-5--veteran-expectations-and-understanding-of-the-review-page-and-next-steps))
- [Recommendation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-01-ARM-appointarep-usertest/research-findings.md#recommendations) 4) 
- (Step 5 in [Task 2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/accredited-representation-management/research/2024-06-ARM-appointarep-digitalsubmit-usertest/research-findings.md#task-2-complete-appoint-a-representative-21-22-form-and-provide-feedback-on-the-experience))

**Comment by erinrwhite** [comment]
Thanks for this background and the chance to think through this a little more! It's helpful and definitely changes my thinking. I see how having the step before submission is more effective in getting folks to download the form, **especially** for users who need to download, print and submit their forms. 

The thing that caught my eye was the download page for folks submitting digitally. The `You won't be able to download a copy of your form after you submit` message appears only when folks are submitting the form digitally, yes? I think I flagged this because we don't really do this for other forms that submit digitally, so it seems to diverge from other forms. Here's the pattern to help users [keep a record of submitted information](https://design.va.gov/patterns/help-users-to/keep-a-record-of-submitted-information) - which is in fact a download after submission.

This is "consider" feedback, so whatever the team chooses here will not be a launch-blocking finding at staging. This is a complex product and I appreciate you following up on this!

**Comment by oddball-lindsay** [comment]
Ah that makes sense - thanks @erinrwhite! I was thinking it was the placement of the entire screen, but I do see how that particular line of content could be interpreted poorly 👍.

I'll chat with design/CAIA for updating that content to match that pattern you've linked to, perhaps we align content with that so it'd read `If you'd like a PDF copy of your completed form, you can download it.`

**Comment by mtri** [comment]
**Unchecked items with notes:**

> Should: clarify headings on contact detail page 
Headings related to organizations a rep belongs to are more descriptive and less action-oriented. How might they be revised to focus on actions the user can take next? We know we're directing people to take an action here. What is it?

After some iteration, we've settled upon testing a direction that will communicate more information with a smaller amount of text and unify wording across products. This uses the headings to communicate information about the representative and relies on the action links for calls to action. We've finalized copy with CAIA.
<br>

>Consider: move personal/contact info to the front of the flow Most of our forms on VA.gov ask for your contact information first, then form-specific questions. That said, I can see how we would want to prioritize understanding if someone even has a rep before moving through the rest of the form.

For our flow the selection of the representative and making sure someone has a representative to select is more important than collecting their basic information. If they don’t have a rep to select, they’re funneled to the Find experience. We've tested this and it's understood so we'll move forward with the existing flow.
<br>

>Consider: checkbox or radio on contact the representative page Y'all might consider making this page not a warning, but a regular page in the form flow. "You need to contact this person to continue. Have you done it? yes/no" (Similar to the print flow, where we ask folks to check a box to verify that they have printed their form.)

We've tested this as it is and it functions well. Previously it was missed when it wasn't a warning alert. We'll move forward with the existing direction.
<br>

>Consider: clearer language for checkbox on review page 
On the review page, the "I accept that this form will replace all my other forms..." checkbox is a little jargon-y. Maybe something like, "By submitting this form I'm replacing all previously assigned reps" or something that otherwise mirrors the Replace your current representative page.

Working with CAIA, we landed about a balance of succinct and specific language that communicates what form is being filled out with as little content as possible. We are a little jargony, but in service of naming the specific form so claimants understand exactly what is happening. We'll move forward with this language.
<br>

**Noted:**
> Should: only show legal/previous names the representative has approved
Please ensure that accredited reps are aware of names that might appear on the public search tool. This might impact folks who have gone through gender transition, or folks who may have safety concerns and do not want a certain name shared.

This has been noted to the ARP team and will be integrated into the contact information workstream.
