### ISSUE TITLE
[DD] Logging unresolved silent failures

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#95216]
Logging unresolved silent failures
In all cases where a system fails to notify the user of a failure, Datadog metric which captures the issue is required.

Currently DD logs that capture silent failures may be missing the new label. See [DataDog metric increment](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md) for details. 

- [ ] Discovery - is this still needed? If no, we can close this ticket as already delivered. 
- [ ] Add a log message when there is an identified a silent failure: 

Note: We don't know if this one is needed yet, we need to dive into the DD stuff and see if it was already handled through the [#94147](https://github.com/department-of-veterans-affairs/va.gov-team/issues/94147) ticket.

**Comment by freeheeling** [comment]
May not be needed – confirm.

**Comment by freeheeling** [comment]
Unresolved silent failures are those that occur when the application is not sending an email notification to the user for any reason. Logging has been added in the case where the user is not notified by email that the following have failed to upload:
- [x] [form 0781](https://github.com/department-of-veterans-affairs/vets-api/pull/19081)
- [x] [form 4142](https://github.com/department-of-veterans-affairs/vets-api/pull/19121)
- [x] [evidence uploads](https://github.com/department-of-veterans-affairs/vets-api/pull/19097)

Remaining:
- [ ] `Form526SubmissionFailureEmailJob` exhausts all retries or is never executed because of an error/failure in the:
  - [ ] `Form526StatusPollingJob` 
  - [ ] `Form526BackupSubmissionProcess::Submit` exhaustion block
