### ISSUE TITLE
Verify Test Cluster Postman Pods

### ISSUE THREAD

**Issue by pjhill** [department-of-veterans-affairs/va.gov-team#95631]
# Description
Reports from Product Team are that the postman helm tests are not executing as expected in the test clusters. We need to investigate and verify that these tests are working as intended, and if they are not then we will need to understand the root cause of the failure and recommend a fix in a separate ticket.

## Acceptance Criteria
- [ ] Test cluster postman execution status is evaluated as succeeding or failing
- [ ] A fix for any uncovered issues has been described in another ticket and approved by the Product team stakeholders

**Comment by LindseySaari** [comment]
I think our best bet might be to run this post sync instead of the test hook. Right now, it seems the helm test would need to be run via CI processes after a release, but right now we're still releasing manually via Github pages. If we add a `PostSync` hook to the Postman Pod manifest, the tests could run automatically after deployment via ArgoCD.

**Comment by JoeTice** [comment]
BUmped out of current sprint for further conversation
