### ISSUE TITLE
[LH Doc Upload] Veteran-uploaded docs (2) datadog dashboard setup

### ISSUE THREAD

**Issue by lisacapaccioli** [department-of-veterans-affairs/va.gov-team#95732]
- [x] Create a dashboard on staging first, based off of the BDD example: https://github.com/department-of-veterans-affairs/va.gov-team/issues/91269

- [x] Once tested on staging, clone the staging dashboard and update it with production variables before production release

**Comment by NB28VT** [comment]
Noting one trick with this one is we can't query the logs based on a VA document type, since this type differs based which type of evidence the veteran selected

**Comment by NB28VT** [comment]
> Noting one trick with this one is we can't query the logs based on a VA document type, since this type differs based which type of evidence the veteran selected

Nevermind I can exclude certain codes with "-", will need to do this for 0781 and 0781a as well so we don't get those results![Image](https://github.com/user-attachments/assets/2ea8effc-003b-4374-9a22-00e74834f60a)

**Comment by NB28VT** [comment]
Dashboard is set up [here](https://vagov.ddog-gov.com/dashboard/aq9-bew-hjh?fromUser=false&refresh_mode=sliding&from_ts=1730757209072&to_ts=1730760809072&live=true); I did end up negating the 0781 and 0781a codes as mentioned in my last comment

**Comment by ajones446** [comment]
@NB28VT Here is the dashboard naming convention acceptance criteria, copied over from the BDD ticket. https://github.com/department-of-veterans-affairs/va.gov-team/issues/91269#issue-2481116990 )

---

Acceptance Criteria

- [ ] Matches the behavior of the staging dashboard
- [ ] Conforms with all of the DataDog standards set out for all teams (see below)
- [ ] [DataDog metric increment](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/274bea7fb835e51626259ac16b32c33ab0b2088a/platform/practices/zero-silent-failures/logging-silent-failures.md)

**Datadog standards** ([from slack 7/24](https://dsva.slack.com/archives/C04KW0B46N5/p1721841520391079) )

- [ ] For monitors, tag them “service:disability-application”
  - For monitors we are more flexible with the titles because they double as the title of notifications that are posted in Slack - so starting everything with "Benefits - Disability Claims - etc" makes them less readable
  - An added benefit to using the service:disability-application tag is that it adds the monitor to the disability service overview found [here](https://vagov.ddog-gov.com/apm/services/disability-application/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&isInferred=false&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3Aall%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&view=spans&start=1721840782530&end=1721844382530&paused=true):
- [ ] Naming convention, consistently name Dashboards “Benefits - Disability- 526 - [details]"
- [ ] Use a shared, editable list that contains all of the Disability-related dashboards.
  - Steve created - [Benefits - Disability - 526](https://vagov.ddog-gov.com/dashboard/lists/manual/1735) (This can be renamed later if we feel there’s a better one to use.)
  - Team members should add their dashboard to this shared list when they create new dashboards
  - Team members should check to see if any existing dashboards have been added and add them if necessary

**Comment by NB28VT** [comment]
Alert monitoring: TBD, we may decide based on how many errors we see when this goes to prod, since we do expect some errors with veteran uploads

**Comment by NB28VT** [comment]
[Production dashboard](https://vagov.ddog-gov.com/dashboard/eg6-c6p-ny8?fromUser=false&index=%2A&refresh_mode=sliding&from_ts=1733173872926&to_ts=1733177472926&live=true) created so closing this (subject to tweaks we still haven't completely finished testing)
