### ISSUE TITLE
Establish Target Milestones for Migration

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-team#95843]
11/12 - GH Migration Plan Complete
11/13 - Migration Kickoff to All OCTO Delivery Teams, start of office hours
12/29 - All teams migrated
12/30 - ZH License Expires

**Comment by tabinda-syed** [comment]
@jefflbrauer Do you mean target milestones for Outreach? 

I would recommend that we specify an outreach scope + timeline that includes the development of the runbook, any templates, migration scripts, etc. along with socializing all of these in ample time so that teams can leverage them to migrate. The migration itself falls within each team's wheelhouse (with support from us via Office Hours and Slack channel, of course).
