### ISSUE TITLE
[10/28/24 - 10/29/24 ] Monitor incident - Missing PEGA status - wrong naming convention 

### ISSUE THREAD

**Issue by cloudmagic80** [department-of-veterans-affairs/va.gov-team#96030]
After implementing this PR:https://github.com/department-of-veterans-affairs/vets-api/pull/19060
Something is causing the form name to come before the UUID.
We need the form name to come after the UUID.
If the form name comes before the UUID the PEGA system can't process it.
It shouldn't be this format: vha_10_7959f_1-cf1b6e07204447096d9bf37837c61df7.pdf
This format is correct: 0099687f-7e9c-45a9-8865-ac67f0d7ef31_vha_10_7959f_1.pdf

Per playbook, opening ticket to track details of this [DD monitor alert](https://dsva.slack.com/archives/C06RQR7V9CM/p1728595123325609).

**Intake**
- [X] PM (Bo) and DM (Andrea) have been notified
- [X] PM and DM confirmation of ticket creation

**Investigation**
- [x] Verify that vets-api is receiving submits from vets-website
- [x] Verify that files are sent successfully to s3
- [x] Verify that the callback API is available
- [x] Determine whether the issue arose due to a deployment, either by the IVC Forms team or the PEGA team.
  - [x] IVC
    - [x] If root cause has been identified as an issue in vets-website or vets-api, notify PM and DM to determine next steps with PO
  - [ ] PEGA
    - [ ] If root cause has been identified as an issue outside of vets-website and vets-api, work with the PM, DM, and PO to determine contacts and next steps.

**Resolution**
- [x] Acknowledge monitoring alerts in slack
- [x] IVC Forms engineering will provide updates on development and deployment of a solution and its status in each environment
- [ ] IVC Forms engineering will notify PM and DM when resolved
- [x] IVC Forms engineering will monitor outstanding missing statuses and ensure they are cleared appropriately. No statuses should be deleted or cleared without agreement from PO and or PM
- [ ] If traffic to the site has been altered, PO or PM will determine when to return to previous levels. 
- [ ] Document appropriately if these count as a ZSF

**Comment by andrea-merrill** [comment]
Incident was a result of this ticket: [PDF_Filler temp files need to be unique](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/95644)

Because the story was still in this current sprint, the pr reversal and future fix to create unique names will all be captured in that same ticket

**Comment by andrea-merrill** [comment]
[Discussion](https://dsva.slack.com/archives/C06RQR7V9CM/p1730136702760289) in team Data Dog channel

**Comment by andrea-merrill** [comment]
We did get asked to update the [ongoing ticket ](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/275)from Watch Officer

**Comment by cloudmagic80** [comment]
Fix is in this PR. All have been tested in the lower environments. Will need to merge this so that we can test in staging.
https://github.com/department-of-veterans-affairs/vets-api/pull/19143/files

**Comment by andrea-merrill** [comment]
Related tickets:
- [Compile list of 32 applicants](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/962140 - create spread sheet of all affected users to send to Pega team in order to document/confirm their application is being processed
- [Send confirmation emails to users affected by incident](https://app.zenhub.com/workspaces/ivc-forms-652da2d3f0ae4c0016bfb109/issues/gh/department-of-veterans-affairs/va.gov-team/96121) - send email confirmation by hitting VA Notify with Postman and passing in affected users' names/emails. 
- [Post Mortem] (https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2024/2024-10-28%20-%20IVC%20Forms%20-%20Wrong%20naming%20convention%20lead%20to%20no%20confirmation%20email%20being%20sent%20to%20user.md)
