### ISSUE TITLE
Unified backend change for PMR Pending TrackedItems

### ISSUE THREAD

**Issue by iandonovan** [department-of-veterans-affairs/va.gov-team#96081]
# Problem

This issue is for implementing the PMR Pending changes discussed in [this issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/95618) and others.

The status of PMR Pending items is erroneously coming in as `NEEDED_FROM_YOU` rather than the correct status of `NEEDED_FROM_OTHERS`.  This is causing PMR Pending items to appear in the wrong categorization for the user, appearing as though they need to take action on it when in fact they do not.

# Solution

The `vets-website` frontend already contains code that corrects this display issue, but a better solution will be to move it to the backend so that the mobile services can also utilize this fix.

The code change here, in English, sets all Tracked Items with the "PMR Pending" `display_name` to have a status of `NEEDED_FROM_OTHERS`.

# Acceptance Criteria

- [ ] API response for calls related to Tracked Items for items with a `display_name` of *PMR Pending* will have a status of `NEEDED_FROM_OTHERS`

**Comment by dysbo** [comment]
Verified that the status coming in from `vets-api` is indeed `NEEDED_FROM_OTHERS` instead of `NEEDED_FROM_YOU`, and the representation in the timeline has the correct information regarding who needs to address it.

![Image](https://github.com/user-attachments/assets/f25e70e0-b0e4-440e-a553-ad0d5b5192c7)
![Image](https://github.com/user-attachments/assets/b4151ed9-f3de-499d-ad9e-d62e4b3949cd)

QA passed ✅

**Comment by dysbo** [comment]
`displayName` change also confirmed to be coming in correctly in the API response.

![Image](https://github.com/user-attachments/assets/817402cb-7805-4b47-9768-20a680180564)
