### ISSUE TITLE
Add previewing changes to formation react doc to documentation site 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9634]
This doc isn't showing up on the documentation site menus: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/7b94d9d0c97d21df2526f9566bc43e84e12e618b/packages/documentation/src/pages/getting-started/common-tasks/previewing-changes.md

**Comment by timwright12** [comment]
Closing because this file has since been deleted from the repo on [commit 58a1fca1ee351b067316718048e55e23575c2f4e](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/commit/58a1fca1ee351b067316718048e55e23575c2f4e#diff-45f76ace3031550a3aa649cd2a99021fdd2db7611e1fb19c79ed3e9060618e1a)
