### ISSUE TITLE
Monitoring: track the response time between submit and callback

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#96605]
As a member of the IVC forms team, I want to see when callbacks are taking longer than usual to reach us in Datadog so that I have additional context for missing status or other errors that come up.

### Acceptance criteria
- IVC Forms team members can see trends that help identifiy unusually long or short response times between the times forms are submitted and a callback is received
- Trends can be viewed for each form so that the impact of supporting documents

**Comment by michaelclement** [comment]
Update on this:
1. I've not been able to find a way to un-redact certain properties in DD like in the screenshot below (this may be a policy control at a higher level, so I've asked platform support).
![Image](https://github.com/user-attachments/assets/dad6061f-afb8-42f4-95c5-d2f31b579b4d)
2. We need a way to correlate an upload event to a Pega response, and currently we don't have a direct way to do that. This is both because of the redacted issue stated above, and because an upload event doesn't share any common identifiers with a Pega response. We will need to an explicit logging call to the BE

As a potential stopgap/alternative, we can roughly approximate when Pega is getting behind showing the difference between upload calls and Pega responses (which should ideally match 1:1). Here's an example with anomalies annotated:
![Image](https://github.com/user-attachments/assets/745af80b-5f09-40be-a67b-65bf3d495973)

**Comment by michaelclement** [comment]
Another update on this - I'm currently working on adding some more in-depth logging to the BE, which should let us track the actual times + correlate between submits received/updated.

**Comment by michaelclement** [comment]
[PR here adds the necessary logging](https://github.com/department-of-veterans-affairs/vets-api/pull/19669) - once it's been reviewed and merged I can start in on the DD graph.

**Comment by michaelclement** [comment]
Visualization is in place and data is being collected on staging:

![Image](https://github.com/user-attachments/assets/db911aaa-26e6-4d71-adcd-396dad4027a1)

**Comment by michaelclement** [comment]
@baltes I accidenti
