### ISSUE TITLE
Spike:  Evaluate the error rates for September

### ISSUE THREAD

**Issue by mjknight50** [department-of-veterans-affairs/va.gov-team#96601]
# Overview
We've been asked to dig deeper into the [error rates](https://vagov.ddog-gov.com/dashboard/vk2-6zi-zzu/benefits---form-527-pension-benefits?fromUser=false&refresh_mode=paused&from_ts=1726593660000&to_ts=1726939260000&live=false) on the pension form.  

# Related Tickets
https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/247
And the fix was https://github.com/department-of-veterans-affairs/vets-api/pull/18661

# Questions to answer
- [x] - When the bug happened? 
- [x] - How many days? I see increased numbers between Sep 17-21, but not every day, which is unusual.
- [x] - What was the user impact? How many individual users affected (I can see 369 failures, but are those unique users).
- [x] - Is that potentially the reason for reduced number of submissions compared to previous 3 months?

**Comment by TaiWilkin** [comment]
# Tickets for investigating and fixing the error:
[Pension | investigate validation errors from 9/26](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93779)
[Monitor Alert: Please review Benefits 21P-527EZ Pension Metric pensions/v0/claims 422 validation error >=1](https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/247)

# Timeline: 
Between September 6th and September 30th, 504 validation errors occurred.
- August 8th - [Pensions Military Prefill](https://github.com/department-of-veterans-affairs/vets-api/pull/17846) merged behind a flipper
- September 3rd - [Prefill enabled in Production](https://dsva.slack.com/archives/C05MS96P6P2/p1725383631038319. 
- September 6th - First validation error from the prefill bug occurs.
- September 25/26 - @wayne-weibel finds an error in the validation error monitor and corrects it as part of [Pension | datadog monitors clean-up](https://github.com/department-of-veterans-affairs/va.gov-team/issues/93599)
- September 26th - The validation error monitor alerts. 
- September 27 - [Filter invalid service_branches values](https://github.com/department-of-veterans-affairs/vets-api/pull/18661) merged,  preventing the introduction of the error into any additional forms.
- September 30 - [Pension: migrate invalid service branches](https://github.com/department-of-veterans-affairs/vets-website/pull/32146) merged, allowing any forms with the error to be submitted if/when submission is reattempted. No additional errors occur after this date. 

# Cause of the error and veteran impact
When we added service branch prefill, we didn't know that the list of possible service branches we had for the endpoint wasn't exhaustive. When a veteran with a service branch of "Unknown" began their form, this was added into the form but caused a validation error on attempted submission. This validation error appeared as a message that there was an error submitting the form and to try again later. Based on error logs in Sentry, veterans generally responded by attempting to resubmit the form multiple times.
Since many logs are deleted after 30 days, I can't definitively give a count of number of users affected, but about a 5th of the errors do appear in Sentry, and only 14 users were involved in those errors, so I estimate between 14 and 100 users were impacted.
Any impacted veterans who attempted to submit their form after the September 30th fix were able to submit their form successfully. I identified 10 in-progress forms in the database that were impacted by this specific issue where the veteran never retried submission after the fix was implemented, and so never successfully submitted their form.

# Number of monthly submissions
The impact on the number of total successful submissions is -10.

The validation error occurred synchronously while attempting to create a SavedClaim from the submission. The number of submissions which successfully reached the SavedClaim state for each month of 2024 so far are:
Jan: 12
Feb: 238
Mar: 1071
Apr: 1.02k
May: 966
June: 926
July: 1009
Aug: 1057
Sep: 948
Oct: 919
Excluding Jan/Feb, the average is 970 per month, making September just fairly close to average.
