### ISSUE TITLE
[Discovery] Pulling markdown files into client documentation site from other repos 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9703]
## Overview 

- Goal of this is to avoid duplicate documentation and to keep the editable content close to relevant code 

## Notes 

- Focus on simple configuration. it should be simple to point to a specific markdown file in another repo to add it to the client doc site

**Comment by U-DON** [comment]
Currently, the Gatsby site is only pulling from the `working-with-vsp` folder, since I originally set it up that way as a demo of how it could work. We could easily expand it to encompass the structure from a higher level, and it would follow the IA of the source repo (va.gov-team).

This doesn't mean that the navigation (sidebar, header menu, etc.) automatically adapts to that structure; we'd have to figure out how we want to handle navigation to these pages. The pulled pages are currently acccessible only through search (if you search by the terms in the top level heading of the doc).

The docs from the team repo seem to only populate or update when the Gatsby site gets deployed. It gets deployed when there are direct commits to it, so it doesn't update on a schedule. In the specific example of moving a file, the doc on the Gatsby site will retain the same URL until the site gets re-deployed, at which point it will update the URL of that doc to the current one.

**Comment by U-DON** [comment]
To use an example, let's look at this [Request Access to Tools doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/orientation/request-access-to-tools.md), which got updated yesterday (as of this comment). Meanwhile, the Gatsby site was updated 2 days ago.

This doc falls under the `working-with-vsp` folder that I designated as the source (again, could expand to a higher level folder), so [it does get included in the Gatsby site](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/working-with-vsp/orientation/request-access-to-tools) at the corresponding URL. It can also be searched by the title "Requesting access to tools", which isn't actually it's current title, so I will explain that next.

Because the site was updated and deployed before the most recent changes to the source doc, it doesn't include those recent changes, such as the top level heading being "Getting access to tools" instead of "Requesting".

**Comment by meganhkelley** [comment]
Thanks for this info @U-DON ! A couple more questions ... 

(1) It looks like the "Edit page in GitHub" feature doesn't work on this page https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/working-with-vsp/orientation/request-access-to-tools — could you do some poking around [maybe timebox 30 min] as to whether that would be easy to fix? 

(2) There's no way to tell from looking at the doc in `va.gov-team` that it is rendering on the Gatsby site. How might we signify that on the MD file itself?

**Comment by mchelen-gov** [comment]
@meganhkelley it seems like currently all the files in `https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp` are included so maybe add something to https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/README.md? this would change if all/more of `va.gov-team` became included

**Comment by meganhkelley** [comment]
Yeah @mchelen-gov re: your first point of just noting it in the readme, I worry that someone who's movin' stuff around in GitHub won't notice that, will move the doc, will break a link that's serving to the Gatsby site (once we put some of that stuff in the IA), etc. But I suppose the only ones moving those VSP docs will be VSP, so it shouldn't be impossible to just keep an eye out for it in the short term. 

Re: your question of moving all documentation out of the tools repo — yep, same page, Rian is really pushing for that. Waiting to figure out the long term documentation site strategy (following the lead of VSP Content & IA team) before making big moves.

**Comment by U-DON** [comment]
Changing the edit link seems pretty simple. I can do that.

I don't think there's a automatic way to indicate on the va.gov-team doc that it's on Gatsby. It's more of a one-way relationship since Gatsby is pulling from va.gov-team without the repo having to acknowledge it. Maybe we could clarify on the Gatsby version of the doc when it was last updated (in va.gov-team) or pulled? I could look into that.

If we decide to move all of the documentation so that the site is entirely based on va.gov-team, I would like to add that the Gatsby site IA can be flexible, so it doesn't have to be an exact copy of the va.gov-team IA if we don't want it to be. In other words, if we wanted, for some reason, to shove all of it into some gatsby-docs folder, we could translate the file paths to different URLs (without the "gatsby-docs" in the path) on the Gatsby site.

**Comment by meganhkelley** [comment]
Discovery is complete; further plan & info gathering may be required before we do this at scale. 

cc @alexpappasoddball keep us posted on your team's timeline for BE docs -> Gatsby site so that we can ensure we're working with y'all on making that happen
