### ISSUE TITLE
Generate jsdocs from vets-website 

### ISSUE THREAD

**Issue by rianfowler** [department-of-veterans-affairs/va.gov-team#9705]
## Overview

There are several helper functions that are not documented in a central place that should be in the client documentation site 

## Notes

- Focus on simple configuration. 
- For now add all of the jsdocs to one tab on the client documentation site. we can iterate on it later if a more complex structure is needed 
- Talk to Rian if you want to support searching for functions. I think we should get the jsdocs published to the site before trying to figure out how to do this.

**Comment by laineymajor** [comment]
@it-harrison is this something that you could consider for console ui? teams start writing more jsdoc comments and this could be extracted into their personal console??

**Comment by it-harrison** [comment]
> @it-harrison is this something that you could consider for console ui? teams start writing more jsdoc comments and this could be extracted into their personal console??

@laineymajor I could be wrong but that might be too granular for console ui since jsdoc comments refer to specific functions in the code and the console ui is taking a higher view...but we might ask teams if they would like to have a way to access that data in the same place.

**Comment by timwright12** [comment]
We have a command in vets-website for this already `yarn jsoc`. I used it on platform code with `yarn jsdoc ./src/platform/**/*.js` just to see what comes out. It's definitely a neat thing, I'm not sure how useful the generated documentation is since the usage of JSDoc comments it's as active as it should be.

I think there's value in running this for applications and pushing those docs into the console. Then it would be up to the app team to use the formatting.

Obviously not an MVP thing though

**Comment by rmessina1010** [comment]
Expired. Closing.
