### ISSUE TITLE
Add data so we can know if QR code, text, etc. is referring traffic

### ISSUE THREAD

**Issue by artsymartha68** [department-of-veterans-affairs/va.gov-team#9710]
I think we should track the source of our traffic. We have a few referrers that spring to mind:

1. Direct URL from poster
    - User enters `va.gov/covid19screen` directly into browser
2. QR code
    - User scans QR code from poster 
3. SMS link
    - User sends message to shortcode and receives SMS with link to click
4. Re-take button (once we add it in)
    - Depending on implementation, could reset state or perform page refresh

**Comment by mchelen-gov** [comment]
Clarified meaning for direct URL entry, and added SMS link as additional source.

Re-take button (once implemented) would probably be considered an "event" in GA rather than a referrer. If we want to get it grouped with other referral sources, we might be able to have the re-take button trigger a page refresh and then do something like https://www.quora.com/Does-Google-Analytics-give-you-a-way-to-track-page-refreshes-separately-from-normal-page-views
