### ISSUE TITLE
Documentation Support Request

### ISSUE THREAD

**Issue by drorva** [department-of-veterans-affairs/va.gov-team#9718]
## Please describe your documentation feedback, describe your request, or ask your question here: 
I would move the getting started section to the top. The experienced users can scroll down :-).
<br>

### _What happens now?_ 
_The VSP Content & Information Architecture will triage your request and reach out for more info as needed. If your issue is urgent or you don't hear from us in a timely manner, please reach out to @Megan Kelley, @Gretchen Maciolek, @Kristina Gore in #vfs-platform-support._

**Comment by drorva** [comment]
This is on https://department-of-veterans-affairs.github.io/va.gov-team/ in case it wasn't clear.

**Comment by gmaciolek** [comment]
We did consider putting Getting started on the top, but opted to leave it at the bottom. Since we were only building one page and theorized that the majority of people using it would be people who are already onboarded, having Getting Started at the top would just force most people to have to scroll every time the used the page. Depending on what happens long-term with documentation tooling and we have a broader content strategy, I definitely think that promoting "Getting started" more prominently will be important.

(Sorry for the delayed response on this! I'm in the process of cleaning up outstanding tickets and figuring out a better triage process.)
