### ISSUE TITLE
[BE] My VA Forms Status: Integrate PDF download into forms status tracker

### ISSUE THREAD

**Issue by a6marinos** [department-of-veterans-affairs/va.gov-team#97541]
Implement new API endpoint for fetching a single, signed PDF url for a given status form.

Requirements:
- endpoint should support a POST method that accepts a single submission UUID (retrieved from benefits intake lighthouse api using our existing form_statuses endpoint) plus the Form ID
- result should return the signed url for the pdf file stored on S3
- errors should follow expected vets-api conventions
  - 200 success
  - 500 internal server error
  - 404 when pdf for uuid is not found
  - Forbidden error if form_id is not supported
  - params validation errors
- controller needs access to a valid S3 config for the team's S3 bucket
- new endpoint should be behind the `my_va_form_submission_pdf_link` feature toggle

Example usage of forms api on BE:
```
config = YourTeamsConfig.new
SimpleFormsApi::FormRemediation::S3Client.fetch_presigned_url(<SUBMISSION_UUID>, config:)
```

In order to fetch pdf URLs from any team's bucket, we'll need a way to load the appropriate S3 config based on the type of form.  We could maintain a map of Form IDs to Config constructors (or necessary config values) to instantiate the proper Config within our controller.

More forms api documentation for pdf downloads:
https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/simple_forms_api/app/services/simple_forms_api/form_remediation/docs

Notes:
- Not all forms will support this functionality (at least at first), so we'll need to ensure that we only show these download links on cards that support them (to avoid making requests for nonexistent pdf urls).  ~An "allow list" could exist on the FE, since we won't be able to preemptively know which forms are supported on the BE using our new endpoint.~  **Otherwise, the submission_statuses endpoint would need to provide metadata per form to let the FE know if PDF downloads are supported for the submission.** (Discussed with team; we will make updates in seperate ticket to apply a "pdf supported" flag to the response from `/v0/my_va/submission_statuses`)

**Comment by DanielMiller-agile6** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/19654

**Comment by DanielMiller-agile6** [comment]
I verified that the endpoint is working as expected on staging. Here's a screenshot of making this request from chrome dev tools with a returned URL.  I'm still having issues when I try to load the actual PDF using this url, but this is likely due to issues with the staging environment and testing data, or otherwise an issue we'll need to collaborate on with another team.  We'll work with VFF team to follow up on this as we begin more integrated testing in staging environment and new tickets can handle additional work. 

![Image](https://github.com/user-attachments/assets/de07848f-2324-4b7a-a968-0a2d276a5541)
