### ISSUE TITLE
EDU: Research Date of Birth Population in Statement of Benefits

### ISSUE THREAD

**Issue by dneel-bah** [department-of-veterans-affairs/va.gov-team#9801]
As a developer, I need to research why the Date of Birth is not populating appropriately in the Statement of Benefits so that a fix can be determined.

## Assumptions:
1. This story is in regards to the form found here: https://www.va.gov/education/gi-bill/post-9-11/ch-33-benefit/

## Acceptance Criteria
1. A root cause and proposed fix is identified for the reported issue of the Date of Birth populating 1 day off.

## Supporting Artifacts:
1. N/A

**Comment by ksantiagomorgan6** [comment]
After reaching out to the platform team and EVSS team.

Response from EVSS team:
The EVSS chapter33 API gets Post 9/11 GI Bill data from the LTS web service by sending them DOB, SSN and EDIPI. These fields are sent by VA.gov in request headers when calling the API. EVSS obtains the DOB from 2 headers: va_eauth_birthdate and va_eauth_birthdate_v1. EVSS uses va_eauth_birthdate_v1 if it’s available, otherwise it uses va_eauth_birthdate. That’s how EVSS gathers DOB for CH33.


It looks like the data DOB is being parsed by DateTime `1995-11-12T00:00:00.000+0000` in vets-api which is causing the birthday to be displayed incorrectly. The issue lies in between EVSS and Vets-API and is external to our control.
