### ISSUE TITLE
UX: Document plan for alert standardization work across portal

### ISSUE THREAD

**Issue by sterkenburgsara** [department-of-veterans-affairs/va.gov-team#98545]
## Description
Following on ticket #[97034](https://github.com/orgs/department-of-veterans-affairs/projects/1420/views/1?pane=issue&itemId=87127549&issue=department-of-veterans-affairs%7Cva.gov-team%7C97034) from last sprint, we have established that alert inconsistency is a serious issue across the portal, and that some tool teams are surfacing alerts that are inaccurate or incorrect. This creates a very poor user experience when clear next-steps and expectations are not set up front in alert messaging. 

In office hours on 12/9, Robyn and Kaitlin let us know that they in order to actualize updates to these alerts **(focus on no access to MHV alerts and ID-verification alerts that span across the portal)**, they will need to be brought up and accepted as part of PI planning in mid January. To get everything ready for the PI planning conversation, Cartography has some work to do laying a foundation.

[Link to github document here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/digital-health-modernization/mhv-to-va.gov/governance/alert-standardization.md)

### User story

As a Cartography team member, I want to enable our stakeholders to move forward with addressing the problem of alert inconsistency by preparing them for PI planning in January.

### Notes
- [Mural from previous ticket](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1731351008810/d0d07089fe24bd66d16a95d86ca67f42fa6794aa)
- Why did some tool teams not accept Cartography's route guard PR and alert for users without access to MHV? (We think Appts was one of these teams)
- Kaitlin and Robyn mentioned they would like to understand the potential impact of this work. If possible, we should find out how many Veterans fit these account criteria and would see these different alerts if they were to access MHV today. 

Possible tasks:
- [x] Document standards in Github with images of the expected alerts
- [ ] Work to understand impact of the work on numbers of users (how many users coming to the portal now experience these alerts? Provide estimate/ballpark to Kaitlin and Robyn)

## Acceptance criteria
- [x] Clear documentation exists of desired standards for most common alert / access scenarios in the health portal, where in tool applications these alerts need to live, and how to implement that logic

**Comment by wesrowe** [comment]
Instead of injecting this ticket, we decided to write a spike that covers office hours discussion of this topic.

**Comment by kjsuarez** [comment]
### AC-api changes made in #97281
Before this feature we used the `userHasMhvAccount` selector (sourced, I believe, from MPI) to determine if the user has an mhv account. We sometimes encounter cases where this state returns `false` wrongly, so we characterize it as stale. The result of this stale selector determines if the `AlertMhvRegistration` alert is shown or not.

With the feature added, we still check `userHasMhvAccount`, and if it returns false we double check with an api call to `/v0/user/mhv_user_account` and return the response (error or otherwise) to the `mhvAccountStatus` selectors. The api call happens as a `useEffect` block on the LandingPageContainer component. Currently there is no new component, only this useEffect block.  
 
The  `mhvAccountStatus` selectors then determine if the new `AlertMhvUserAction` alert is rendered, as well as if the messages, medications and medical records cards will rendered as error cards instead.

**Comment by fmccaf1** [comment]
I'm thinking we can close this since ACs are complete

**Comment by mcarterA6** [comment]
@sterkenburgsara - I am going to move this ticket to completed. Let me know if it needs to be reopened.
