### ISSUE TITLE
[BE/Data] 10-10EZR: Determine if we have had any Silent Failures

### ISSUE THREAD

**Issue by alexseelig** [department-of-veterans-affairs/va.gov-team#98691]
### Issue Description

As a Veteran, I would like to be notified if my EZR is not submitted so that I know what I can do to rectify the situation.

- [x] Determine how many failures we had last month
- [x] Figure out why we had the one silent failure last month
- [x] Go through all previous months and figure out if we've had any other silent failures
- [x] Go through December and make sure this hasn't happened this month.
- [x] Email HEC with info for Veteran(s) who have had silent failures
- [x] Come up with fix for cause of silent failure
- [x] **Success: We have determined if we have had any silent failures and we have remedied the issue in Production**

**Comment by JoshingYou1** [comment]
The one silent failure was due to logic in the code that makes it so when an EZR fails VES validation, it is not retried. We only had one silent failure last month and the Veteran's info has already been sent to HEC. Because `PersonalInfomationLog` records only last two weeks (https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/delete_old_pii_logs_job.rb) in the DB, we can't go back farther than that to send emails for other failures. A fix has already been implemented (https://github.com/orgs/department-of-veterans-affairs/projects/1433/views/35?pane=issue&itemId=90428932&issue=department-of-veterans-affairs%7Cva.gov-team%7C98783)
