### ISSUE TITLE
Staging Review finding: Link on primary entry point page not added for Appoint a Rep tool

### ISSUE THREAD

**Issue by shiragoodman** [department-of-veterans-affairs/va.gov-team#98996]
_Need help? Please review [how to read a Staging Review ticket](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/anatomy-of-a-staging-review-issue-ticket). Tag `@platform-governance-team-members` on Slack if you need further assistance._

## Product Information
**Team:** Accredited Representation Management
**Product:** Appoint a Representative MVP
**Feature:** Appoint a Representative + Representative Status Widget

## Findings details
**VA.gov Experience Standard - issue:** [User has a path to the content or feature.](https://design.va.gov/about/experience-standards/#user-has-a-path-to-the-content-or-feature)
**VA.gov Experience Standard - category:** [Findability](https://design.va.gov/about/experience-standards/#category-findability)
**Launch-blocking:** No
**Design System review:** No
**Collab Cycle Reviewer:** @erinrwhite (IA)

### Description

The primary entry point for this tool, [Get help from an accredited rep or VSO](https://staging.va.gov/get-help-from-accredited-representative/), is not updated to reflect this new tool.

<details><summary>Link, screenshot or steps to recreate</summary>

![entry point not updated](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/vsp-collaboration-cycle/staging-review-images/71535-erin-entry-point.png?raw=true)

</details>

## Recommended action

Work with CAIA to add content and the link to this online application. Ensure that the language on this page clearly indicates that the tool helps the user fill the form that they then mail in, rather than submitting directly to VA.

## References

- **Accessibility Defect Severity:** N/A
- **WCAG Success Criteria:** N/A
- **Modality:** N/A
- **Design System Component:** N/A
- **Design System Pattern or Template:** N/A
- **Design System Foundation:** N/A
- **Content Style Guide:** N/A
- **Context:** User flow

---

### Next Steps for the VFS Team

- [ ] **Questions?** For the most timely response, comment on Slack in your team channel tagging `@platform-governance-team-members` with any questions or to get help validating the issue.
- [ ] **Ticket ownership:** If you believe that this issue is out of scope, not your team's responsibility, or a Design System issue, comment and tag `@platform-governance-team-members` on your team channel in Slack to provide an explanation and who you believe is responsible. The Governance team will follow up.
- [ ] **Close this ticket** when the issue has been resolved or validated by your Product Owner.

**Comment by oddball-lindsay** [comment]
Since this is our first version of the Appoint product, we will be exposing the entry point as part of our staged rollout.

We are creating a React Widget to handle existing content as well as the new content with the entry point, and that will be included in our feature toggle for managing the staged rollout. For example, for our first stage we will set the feature toggle to expose the entry point and the Appoint a Rep experience to 10% of users.

This is to avoid folks seeing the entry point without actually being able to access the Appoint product. And this work is being coordinated with CAIA [in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67034#issuecomment-2521069523).

**Comment by erinrwhite** [comment]
Thanks @oddball-lindsay this can be closed!
