### ISSUE TITLE
VERA Access Request

### ISSUE THREAD

**Issue by jpacheco-va2024** [department-of-veterans-affairs/va.gov-team#99364]
### VA Notify:  Important Scheduling Information
As we approach the end of the year, please note that VA Notify will ***not*** be starting any new notification intakes after November 15th. Our focus will be on supporting in-progress notifications, urgent zero silent failure use cases, and completing 2024 initiatives. Kick-off meetings for new intake forms submitted ***after November 15th*** will be scheduled in January.

***Important Reminder:*** Please be mindful of launching new notifications before the holidays unless there is a business-critical deadline. There will be a ***VA platform code freeze 12/23/2024 - 1/3/2025***, with limited support during this time.

If you have any other urgent needs that require attention before the end of the year, please reach out as soon as possible for review.

## Your Details
1.  Joseph Pacheco 
​
2.  VAVBACO - Outreach, Transition and Economic Development (OTED)
    
3. Kevin Powers (kevin.powers2@va.gov) & Joseph Pacheco (joseph.pacheco@va.gov)     
​
## Notification Details
1.  both
​
2.  Request access to VA Notify for the Visitor Engagement Reporting Application (VERA) Workspace.
​
3.  VA Notify has already been configured for VERA.

4.  N/A
​
5.  Visitor Engagement Reporting Application (VERA)
​
6.  N/A

7.  N/A
  
8.  N/A
​
9.  N/A
​
10.  N/A
​
11.  N/A
​
12.  N/A
​
13.  N/A

**Comment by kbelikova-oddball** [comment]
Users already have access to VERA service on the [portal](https://staging.notifications.va.gov/) 
Please login with PIV.

**Comment by kbelikova-oddball** [comment]
Please make sure you are on VA network when attempt logging in

**Comment by jpacheco-va2024** [comment]
I confirm I am connected through the VPN.  See attached snip.![Image](https://github.com/user-attachments/assets/53679f46-5b8a-4cb4-b052-2c4106f256df)

**Comment by kbelikova-oddball** [comment]
which environment are you trying to access - [staging](https://staging.notifications.va.gov/) or [prod](https://notifications.va.gov/)?

**Comment by kbelikova-oddball** [comment]
@jpacheco-va2024 - I see you're in on the prod portal :)

**Comment by jpacheco-va2024** [comment]
I can get in production.  I cannot access stagging, which I need also.  I also need to confirm the level of access I need in both environments.  I have VERA (viewer) but will need VERA (Editor).

**Comment by kbelikova-oddball** [comment]
Interesting... I changed your access on prod to editor. Also turned your access off and back on on staging. Can you please try again?

**Comment by jpacheco-va2024** [comment]
I have editor access now in prod. -Thank you.  
I still cannot access stagging.

**Comment by mjones-oddball** [comment]
@jpacheco-va2024 FYI Ksenia had to head out and is out of office through 1/3. 
I updated your prod access to view only, apologies the edit access there was a mistake. All templates are created, edited, and promoted directly through Staging.

As for that blank page! So that happens when login with PIV hits an error. I just checked the VA IAM system and it's saying in the lower environment you're not in Active Directory. I'm waiting to hear back from the IAM team to see if they have more info on how we can get that resolved for you. Will let you know what I hear back.

Can you please have Kevin try logging into [Staging](https://staging.notifications.va.gov) again? I double-checked and he looks OK in the IAM system. I would suggest he restart the browser if he got the error earlier to make sure it's not cached.

In case this issue isn't resolved by tomorrow I'm looping in @nathanbwright as I am also heading out soon for time off.

Thanks for your patience as we work to resolve this!

**Comment by jpacheco-va2024** [comment]
Thank you for the update.  Kevin access is good.  Please update when able about my active directory stagging issue.

**Comment by mjones-oddball** [comment]
@jpacheco-va2024 Good morning! Can you please try logging into [Staging](https://staging.notifications.va.gov/) again? The IAM team made a change - so hopefully your PIV login will work now.

**Comment by jpacheco-va2024** [comment]
I can access staging now.  Thank you for fixing the problem.

**Comment by mjones-oddball** [comment]
Happy to help! Enjoy the holidays.
