### ISSUE TITLE
Research & Discovery - Next round of VAOS User Research & Testing

### ISSUE THREAD

**Issue by lenaecb** [department-of-veterans-affairs/va.gov-team#9948]
## Background
With VAOSR MVP in prod and live since March 2020, it's time to perform another user research and testing with Veterans.

This research should focus on areas in the experience that we know (through analytics and user feedback) are confusing or need iteration. Additionally, we want to collect general feedback and requests from Veterans for new VAOSR considerations in the future. 

## Some starting Research questions:
1. What's impacting 'type of care' dropoff? (15.5% dropout rate on this page in the VAOS flow)
     - Does 'Type of Care' offerings meet Veteran expectation for online scheduling
2. What's impacting the high dropoff rate of Veterans on the 'Facilities' page?
   - 21% of users drop out of the Facilities page
   - 14% of that 21% of users drop out after receiving the "Your facility does not support online scheduling"
   - We have received multiple some user feedbacks that Veteran is not seeing the right facility/provider
   - One hypothesis: that users are confused by the new Parent Facility and Child Facility name selection for picking a VAMC and a specific child Facility. Old VAOS displayed location (city, state) then had user pick the facility name they were familiar with. 
3. Why are we seeing 10% dropoff rate on 'Select a time/date' calendar page? Is there UX/interaction issues or confusion? 
4. Appointments list - appointments listed first in ascending order with date furthest away at bottom of list. Then we show the 'requests' in alphabetical order. Received some feedback on this sorting/statuses. 
5. Past Appointments - this is a new feature - we want to see if it's meeting Veterans' needs. 
6. Cancellation - are Veterans having issues when trying to make cancellations? Are they expecting something additional when they try and cancel?
7. Are Veterans expecting additional methods for communication in VAOS?
     - Example is in-app messaging to Schedulers and/or providers. Previous version of VAOS had a very limited 2-way messaging feature limited to 2 messages to scheduler. 
     - Specifically, if they have questions about specific appointment
     - Verification of notifications of appointment - email, phone, text 
8. Telehealth / video appointments - issues/expectations for these appointments through VAOS?

9. Login and tool instructions - a few Veterans have expressed that the login experience and the VAOSR tool instructions are confusing/hard to understand. 
10. General feedback on new experience 
     - Do Veterans hit certain roadblocks in their scheduling experience in new VAOSR? What are those roadblocks?
11. Feedback on Express Care prototype

## Areas we know need attention:
- expanding 'reason for appointment' text box from 150 characters (already have user story for this)

## Supporting resources:
- Latest collection of user entered feedback -- reach out to @lenaecb 
- [User flow analytics ](https://analytics.google.com/analytics/web/#/analysis/a50123418w177519031p184318975/edit/5pTuYti2SICJcXOmDUObBA)

## Issues to create within this Epic
- [ ] Create research plan
- [ ] Design v2 of Express Care prototype
- [ ] Recruit for research sessions/Schedule research sessions
- [ ] Create conversation guide
- [ ] Conduct Discovery Research Sessions (at a minimum, the team lead, PM, designer, content person should join these sessions).
- [ ] Discovery Synthesis - should be conducted as a team, led by designer.
- [ ] Discovery Research Readout (at minimum, it is expected that the designer should do a readout at design meetings & for their team. If stakeholder readouts are needed, the team lead/PM are responsible for scheduling those. Designers should also plan to do research readouts at the end-of-sprint demo.)

**Comment by lenaecb** [comment]
@melissajschaff - this is the initial epic for the Rd 2 research. I'll create the tickets outlined below next, but first wanted to get your eyes on this. 

Can we setup a quick 'kickoff' meeting this week?

cc: @lalexanderson-dsva - anything additional to consider?

**Comment by melissajschaff** [comment]
notes/thoughts about the strategy from my convo with @lenaecb:

**Hypotheses:**
- *DEPO has repeatedly heard from Veteran participants that it is difficult to complete forms online due to certain conditions, which contributes to frustration when trying to complete tasks such as online scheduling*
- Users have information overload on VA appointments page
- Users have information overload on VA schedule an appointment page
- Users have information overload/confusion as they are going through the flow to schedule an appointment
  - Users are looking for, but can't find a specific appointment type, either because it is not listed/supported by online scheduling, at that location, or the user has a different name for the appointment type than what is listed
  - Users are looking for a specific location, but can't find the specific location they have in mind, either because the location isn't listed or it is listed using a different name/nested within a category they are unfamiliar with
  - Users are looking for a specific provider, but can't find the specific provider they have in mind
- Users are confused by the different look/feel, if this is new to them. Easily give up, rather than trying to figure it out

@lalexanderson-dsva we believe that 7 (Are Veterans expecting additional methods for communication in VAOS?) is out of scope for this research effort and should be considered for a separate research engagement. 

Strategy for research session/script:
- Start here: https://www.va.gov/health-care/schedule-view-va-appointments/
  - [9 Login and tool instructions] Have you seen this before? What do you think?
- [user logs in]
  - Have you seen this tool before?
- Reorder research questions: 
  - [4 Appointments list]
  - [5 Past appointments]
  - [6 Cancellation]
- Schedule an appointment
  - [1 What's impacting 'type of care' dropoff?]
  - [2 What's impacting the high dropoff rate of Veterans on the 'Facilities' page?]
  - [3 Why are we seeing 10% dropoff rate on 'Select a time/date' calendar page? Is there UX/interaction issues or confusion?]
  - [8 Telehealth / video appointments]

**Comment by melissajschaff** [comment]
@lenaecb @lalexanderson-dsva After thinking about it a bit more, I think we may be able to tease at 7 throughout the conversation, but I still feel this is its own research. For example, we can ask participants if they expected to be able to leave notes for schedulers, nurses, drs, etc. to review; if they expect a response and where they anticipate being able to get that message. 

I think that will also help shape future research on the topic.

**Comment by lenaecb** [comment]
Research report here -- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/appointments/va-online-scheduling/research/july-2020-user-research/2020-july-VAOSR-EC-research-report.md

Closing ticket
