### ISSUE TITLE
Discovery: Applying AC-API code to tool teams

### ISSUE THREAD

**Issue by kjsuarez** [department-of-veterans-affairs/va.gov-team#99610]
## Description
The MHV landing page now consumes the AC-API and displays alerts based on its response. This feature is implemented in a fashion highly specific to the landing page.  We want to port the AC-API alert feature in such a way that it can be easily used by tool teams with minimal setup or change to their applications design.
### User story

As a Tool team member, I want an easy way to implement AC-API alerts without having to make significant changes to my application

## Notes
- Kevin started documenting options in this [ACapi slack canvas](https://dsva.slack.com/docs/T03FECE8V/F080HK4F997)

## Possible tasks:
- Explore architecture options that could make the AC-API feature more portable
- Investigate the [Downtime Notification docs](https://depo-platform-documentation.scrollhelp.site/developer-docs/downtime-notifications#Downtimenotifications-Example) for a possible implementation pattern
- Investigate the structure of the Messages, Medical Record and Medications applications to better understand how they currently implement alerts.

## Acceptance criteria

Original ACs:
- A ticket is drafted detailing the approach to porting this feature for other teams

New ACs: ?
- Level of effort for packaging is documented, along with whatever light detail is needed to differentiate options, if appropriate

**Comment by wesrowe** [comment]
@kjsuarez, I think we might want to break this work down to a smaller chunk; more of an estimate of effort than a detailed plan as envisioned in the ticket as-is. TBH, now that I have heads-down time to focus on it, I'm not confident we should package this for other teams right out of the gate. 

Timeline to Veteran value is my main concern. The overall timeline for Veterans of that approach would be (in series, not parallel): the time it takes to package + the time it takes each team to implement alerts and UX/a11y fixes. 

Coordination is also a big challenge: we would somehow have to help monitor/manage that process while it's hidden from us in Jira. 

The alternative MVP I'm weighing: In tools, when a user doesn't have an mhv-uuid, we could require a redirect/route-guard sort of experience instead of the ideal of keeping these Veterans in-place on the tools. I'm hypothesizing that would be _acceptable_ (though not ideal). To resolve this, I need to have a tradeoffs discussion with @sterkenburgsara when she's back.

To enable that tradeoffs discussion, I need to know less about the package plan:
- What's the approximate level of effort (preferably in points) for packaging? A range is okay.
- If there is a wide range depending on approach, give us a few sentences about the approach options. (The level of detail you wrote in [the canvas ](https://dsva.slack.com/docs/T03FECE8V/F080HK4F997)is more than enough probably.)

My suggested AC would be something more like "Level of effort for packaging is documented, along with whatever light detail is needed to differentiate options, if appropriate."

Lmk your thoughts!

**Comment by wesrowe** [comment]
For discussion with @sterkenburgsara:

**Cons:**
  - UX of secondary nav – Can we alleviate "broken nav" concern by hiding the secondary nav?
  - Some very small % of users who come in to tools through a side door (not involving landing page) could end up on the landing page instead of the tool, for no apparent reason (sign-in call to ACapi had error, but landing page call was successful)

**Benefits:** 
  - Tool teams get one consistent message to redirect/route-guard for all 3 scenarios
  - No eng. work required before PI planning
  - No planning burden on our eng team
  - Overall timeline to ACapi implementation on tools could be 3-6 sprints earlier (rough estimate), because lift is lighter and it can go straight to engineers (no UX needed)

**Comment by kjsuarez** [comment]
> I think we might want to break this work down to a smaller chunk; more of an estimate of effort than a detailed plan as envisioned in the ticket as-is. 

IMO this ticket's current AC is more or less required to in order to accurately gauge level of effort.

That said, if porting this functionality to the tool team apps isn't a priority then I agree we should pivot away from this work.
The good news is, my heads down time has also been quite productive and I think I have a solid approach mapped out already. I'm dropping this ticket down to a 3, I'll draft a new ticket detailing my planned approach and we can cram it in the backlog until it's time.

**Comment by kjsuarez** [comment]
[Ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/99650) added as a result of this work

**Comment by wesrowe** [comment]
Thanks for the level of detail in that ticket, @kjsuarez. Do you have any idea what the points estimate would be? Just a ballpark would be helpful if you know it. No sweat if not.

**Comment by kjsuarez** [comment]
A conservative estimate would be 5pts, which is what I've given it.
